### DISCUSSION TITLE
Skip Link on signed-out pages

### DISCUSSION THREAD

**Discussion by asizer** [community/community#10089] [Other Feature Feedback, Questions, & Ideas]
Hi there,

This is more of a bug report for github.com, but I couldn't find a better place to report it. Please let me know if there's somewhere else this should go!

Github has a keyboard-accessible `Skip to content` link at the top of each page (yay). When a user is signed out, this SkipLink is under the header. Sometimes it's visible through the header elements because the header has a transparent background. Most of the time it isn't visible at all because the header gets a solid background. In any case, the SkipLink should be on top of the header.

### Signed out landing page

Here's what this looks like on the landing page (screen width needs to be <1300px): 
<img width="1092" alt="Screen Shot 2022-01-13 at 12 41 12 PM" src="https://user-images.githubusercontent.com/1692781/149383378-20313104-923f-4d75-97af-1496f591c6f1.png">
In this case, the header css is:
```css
.header-overlay .header-logged-out, .header-overlay .Header {
  position: absolute !important;
  right: 0;
  left: 0;
  background-color: transparent; // <-- this is why we're seeing the SkipLink through the header
}
.Header-old {
  z-index: 32;
}
```

### Signed out other pages

On other signed-out pages, the SkipLink is under the header (this is the focused state, inspected with devtools, note the actual button is not visible): 
<img width="614" alt="Screen Shot 2022-01-13 at 12 57 18 PM" src="https://user-images.githubusercontent.com/1692781/149383763-ec7764b6-a391-4147-bcbf-cf43b02608bf.png">
Here the body doesn't get the `header-overlay` class, so the `background-color: transparent;` above isn't applied to `.header-logged-out`. The header then gets a solid background, and blocks the SkipLink. 

### Signed in pages

The SkipLink appears as expected on signed-in pages. 
<img width="859" alt="Screen Shot 2022-01-13 at 1 02 24 PM" src="https://user-images.githubusercontent.com/1692781/149384747-233046be-a71c-46e9-bfea-065db53c28bd.png">

I'm not suggesting a css solution here (though I think it has to do with the positioning of the `<header>`), just pointing out the current state of things. It's cool you've got a SkipLink, would be nice if it were also visible when signed out. 

Thanks!
