### DISCUSSION TITLE
Support `maxlength` attribute for Issue Form text inputs

### DISCUSSION THREAD

**Discussion by pglevy** [community/community#10101] [Projects and Issues]
The ability to further structure input by limiting the character count could be useful in some situations.

Something like this:

```
- type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: And what did you expect to happen, in 280 characters or less
      placeholder: Tell us what you see!
      value: "A bug happened!"
      maxlength: 280
    validations:
      required: true
```
