### DISCUSSION TITLE
Edited Issue Trigger management

### DISCUSSION THREAD

**Discussion by Carloca7** [community/community#101340] [Actions] [answered]
### Select Topic Area

Question

### Body

Good morning, I'm trying to make a github action which modify issue's body to a template at the moment an user modify the issue in github.com. To get it, I'm using 
`on:
  issues:
    types:
      - edited`
Which is working perfectly. However, this action is being triggered when repository's API is in use, for example a PATCH to modify issue's body. How could I differentiate when an issue is modified by API or github.com?

**Comment by fury-05** [comment, marked as answer]
GitHub Actions doesn't provide a built-in way to distinguish between changes made via the GitHub.com web interface and changes made through the API. The on: issues event with the edited type is triggered whenever an issue is modified, regardless of whether it's done through the GitHub web interface or the API.

You can infer the source of the modification by examining the payload provided to your action. The payload includes information about the changes made to the issue. For instance, the sender field in the payload represents the user or app that triggered the event.

For Example Sample Code :

```yaml
name: Issue Edited

on:
  issues:
    types:
      - edited

jobs:
  issue-edited:
    runs-on: ubuntu-latest
    steps:
      - name: Check if edited by GitHub.com
        run: |
          if [ "${{ github.event.sender.login }}" != "github-actions[bot]" ]; then
            echo "The issue was edited by a user on GitHub.com"
          else
            echo "The issue was edited by an API call"
          fi


```

In this example, it checks if the sender is the github-actions[bot]. If it's not, then it assumes that the issue was edited by a user on GitHub.com.

Note that this approach relies on the assumption that GitHub Actions will consistently use the github-actions[bot] user for API operations.
