### DISCUSSION TITLE
Add previous GitHub workflow runs status in the `github` context

### DISCUSSION THREAD

**Discussion by mckelvin** [community/community#101518] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi there,
I'd appreciate it if the status of the previous workflow runs can be added to the `github` context. My original requirement is to send Slack notification when the run status is CHANGED between previous run and next run. My current [implementation](https://stackoverflow.com/a/77863821/721331) works but it is really tricky.

Thanks!

**Comment by fury-05** [comment]
Here is how you can do it Refer this as example you may need to change it according to you requirements:

Access Previous Run Status: You can use GitHub API to fetch information about previous workflow runs. Specifically, you can use the workflow_run context to get details about the previous run. 

```yaml
- name: Get Previous Run Status
  id: get_previous_status
  uses: actions/github-script@v4
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const { data: runs } = await github.actions.listWorkflowRuns({
        owner: context.repo.owner,
        repo: context.repo.repo,
        workflow_id: context.workflow,
        per_page: 2,
        page: 1,
      });
      return runs[1].status;
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
This script fetches the status of the previous run and stores it in the get_previous_status.outputs context variable.

Check for Status Change: After getting the previous run status, you can compare it with the current run status to determine if there has been a change. If there's a change, trigger the Slack notification. 
```yaml
- name: Check Status Change
  id: check_status_change
  run: echo "Status has changed!"
  if: ${{ steps.get_previous_status.outputs.result != success() }}
```
This step will only run if there's a change in status.

Send Slack Notification: Use an existing GitHub Actions Slack notification action or create a custom one to send a message to Slack. You can include information about the current and previous run statuses in the message.
```yaml
- name: Send Slack Notification
  uses: some-slack-notification-action
  with:
    slack-token: ${{ secrets.SLACK_TOKEN }}
    message: "Workflow status changed from ${{ steps.get_previous_status.outputs.result }} to ${{ job.status }}"
  if: ${{ steps.check_status_change.outputs.result == success() }}
```
Replace some-slack-notification-action with the actual action you are using or consider creating a custom script for this purpose.
