### DISCUSSION TITLE
Why do my background images don't show properly?

### DISCUSSION THREAD

**Discussion by ilwoongchoi** [community/community#101523] [Repositories]
### Select Topic Area

Question

### Body

https://github.com/ilwoongchoi/ancellwebsite

My background image for the index page don't show properly. I have set the background image correctly but the background for the content section shows only light-grey colour.

**Comment by ananuness** [comment]
Hii! Instead of `1.jpg` you can use `./1.jpg`, like:

```css
.content-section {
    background-image: url('./1.jpg');
}
```
