### DISCUSSION TITLE
Runner's Working Directory Issues

### DISCUSSION THREAD

**Discussion by dominicfarr** [community/community#101513] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello

My repo structure is two sub folders representing two tiers [Frontend & Backend] 
I'm trying to create my GitHub Actions pipeline.  
Unfortunately, I keep running into an issue. 
The working director for the runner is wrong, it duplicates the project name.  This causes other issues. 

Is this correct? Am I missing something? 

I have tried adding working-directory attributes but they were not effective. 

Logs
```
##[group]Getting Git version info
Working directory is '/home/runner/work/million-dollar-idea/million-dollar-idea'
[command]/usr/bin/git version
git version 2.43.0
2024-01-22T23:09:26.7202182Z ##[endgroup]
```

Project Structure
```
million-dollar-idea/
.
├── .github
    └── workflows
         └──  pipeline.yml
├── million-dollar-idea-core
    └──  src
└── million-dollar-idea-ui
    └── src
```

**Comment by dominicfarr** [comment, marked as answer]
Found the solution.  Needed to set the cache-dependency-path to the location of the lock file. 
```
  uses: actions/setup-node@v4
        with:
          cache-dependency-path: ui/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"
```
