### DISCUSSION TITLE
How can I trigger an action when only the pull request title is updated?

### DISCUSSION THREAD

**Discussion by yeikel** [community/community#101695] [Actions]
As part of pull request linting, I have the following workflow : 

```yaml

name: "Semantic Pull requests Validation"

on:
  pull_request:
    types:
      - opened
      - edited


jobs:
....
```

In my case, I would like to trigger the workflow when : 

1. The pull request is created
2.  The title of the pull request changes

Sadly, `edited` also happens when the body of the pull request changes and that is not what I am looking for (it produces unnecessary executions)

**Comment by jsoref** [comment]
https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=edited#pull_request

you probably want something like:
```yaml
       if: event.type == 'opened' || event.changes.title.from
```

**Reply by yeikel** [reply]
Thanks, that might work for now. The only challenge of doing this is that it still triggers the workflow (ie: it allocates resources, pulls the images, etc), so it is not as ideal as simply not running like the native `on` clauses  

The jobs finish very quickly, but they still run

**Reply by jsoref** [reply]
You can try using a reusable workflow: https://docs.github.com/en/actions/using-workflows/reusing-workflows

My guess is that it wouldn't make you wait for the resources of the called workflow until the condition is true. But I don't actively use that feature, so I'm not certain.

**Reply by yeikel** [reply]
I am using re-usable workflows but I am not sure I understand the connection for this problem

Do you mean to perhaps do something like this? 


```yml

jobs:
  call-workflow-passing-data:
   if: event.type == 'opened' || event.changes.title.from
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
```

From what I understand, this will still allocate a runner and create a workflow run to execute the filter condition

**Reply by jsoref** [reply]
I don't think `call-workflow-passing-data:` allocates a runner as you didn't specify a runner. 

Something in `uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main` will allocate runners. 

Some of the flavors of GitHub's more recent modular things (I've been using GitHub workflows for a while, so there have been a lot of new features) allow disconnects between caller and callee such that you could see the callee in workflow runs and filter for them separately.

I think the flavor of reusable workflow that you're using here wouldn't do that.

Note that you can filter workflows by result, so, only successful or only failed, and that would skip all the skipped workflows. 

Alternatively, if you don't care about billing and delays, and really like being able to see a view that only shows workflows that have run, you could use `on: workflow_dispatch` in the callee and have the caller trigger it when your if is true.

**Reply by jsoref** [reply]
@yeikel could you please select this as the answer? (so that people won't "bump" it)

**Reply by pferreirafabricio** [reply]
@jsoref  This is a **workaround**, not the desired final solution (a proper event for the **PR title** — that's the reason for the "bumps"), since it still triggers the workflow and clutters the repository's actions tab with `Skipped` runs.

**Comment by ghost** [comment]
GitHub Actions does not have a trigger event that specifically differentiates between pull request title changes and body changes. The edited type for the pull_request event will trigger on changes to the title or the body.

However, you can minimize unnecessary job executions by using conditions within your job steps. While this does not prevent a workflow run from being created, it can stop the job steps from running if the conditions are not met.

Here's how you might structure your workflow to utilize conditions within your jobs:
```
name: "Semantic Pull requests Validation"

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  check-pr-title:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || (github.event.action == 'edited' && contains(github.event.changes, 'title')))
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: echo "PR title has changed or PR has been opened"
        # Add your steps for linting the PR title here
```
In this example, the if condition is used within the job itself. The job should only run if the event is a pull_request that has either been opened or edited with changes that include the title.

The contains function checks if the changes object in the event payload includes a title key, indicating that the title has been edited.

While this does not prevent the allocation of a runner, it does prevent unnecessary steps from executing, which can save on execution time and reduce the load on your CI/CD infrastructure.

As for reusable workflows, they follow the same rules regarding triggers and conditions. The condition would also apply to the job that calls the reusable workflow.
