### DISCUSSION TITLE
Commit history for a file?   (Or, lookup a GitHub handle from an email?)

### DISCUSSION THREAD

**Discussion by dogweather** [community/community#101764] [Apps, API and Webhooks] [answered]
### Select Topic Area

Question

### Body

(I suspect the answer will be that I should use the API directly, not the CLI app.)

I want to create HTML with links to commits and the authors' profiles for a file.

I can get create a nice file history with `git log`:

```yaml
- date:    "2024-01-23T17:24:11-07:00"
  commit:  ec44f1ac02ba2f6cd6247764b7ab2c18fbbb291b
  author:  "Robb Shecter <robb@public.law>"
  subject: "copy a file"
- date:    "2024-01-23T00:16:25-07:00"
  commit:  f926ebd8ad18c5f34ceeda2f68f414198b81edac
  author:  "Robb Shecter <robb@public.law>"
  subject: "changelog (#12)"
```

But I realized, (doh) git doesn't have the _GitHub_ author (i.e., handle). I realized, I really wanted this:

```yaml
- date:    "2024-01-23T17:24:11-07:00"
  commit:  ec44f1ac02ba2f6cd6247764b7ab2c18fbbb291b
  author:  "Robb Shecter (@dogweather)"
  subject: "copy a file"
- date:    "2024-01-23T00:16:25-07:00"
  commit:  f926ebd8ad18c5f34ceeda2f68f414198b81edac
  author:  "Robb Shecter (@dogweather)"
  subject: "changelog (#12)"
```
