### DISCUSSION TITLE
How to write (or simulate) `runs-on` expressions?

### DISCUSSION THREAD

**Discussion by nedrebo** [community/community#10178] [Actions]
Are there any official ways or any workarounds to express more advanced `runs-on` directives?

Example of what I would like to  achieve:

```yaml
some-gpu-job:
    runs-on:
        - self-hosted
        - ! low-end
        - gpu-intel || gpu-amd
```

So basically I want to run on a self-hosted machine, but not one of the oldest and slowest ones and I need a GPU, Intel, or AMD (but not other vendors).

This is of course a toy example, real life is more complicated.

I am aware I can make labels such that I can write this instead:

```yaml
some-gpu-job:
    runs-on:
        - self-hosted
        - mid-end-or-high-end
        - gpu-intel-or-gpu-amd
```

This will be error-prone to manually maintain at scale. Just for GPUs I would need the following labels:

```
gpu-intel
gpu-amd
gpu-nvidia
gpu-intel-or-amd
gpu-intel-or-nvidia
gpu-amd-or-nvidia
gpu-intel-or-amd-or-nvidia
```

If I want to do more advanced expressions than one `||` then this does not scale at all.

In addition to being complicated to maintain, this will even add a bottleneck to the CI. Assume I can run a maximum of 2 jobs on any physical GPU because of memory constraints. With simple labels, I can have the following setup and run 4 x `some-gpu-job` at the same time on one agent.

```
Agent setup A:
    runner 1: gpu-intel
    runner 2: gpu-intel
    runner 3: gpu-amd
    runner 4: gpu-amd
```

If I change to the setup below that is reduced to 2 x `some-gpu-job` at the same time per agent and throughput is halved.

```
Agent setup B:
    runner 1: gpu-intel, gpu-amd, gpu-intel-or-amd
    runner 2: gpu-intel, gpu-amd, gpu-intel-or-amd
    runner 3:
    runner 4:
```

Because of these maintainability and throughput problems, the label hack is not viable, I am looking for something better.
