### DISCUSSION TITLE
Container push fails on _some_ containers with "403 Forbidden"

### DISCUSSION THREAD

**Discussion by hugelgupf** [community/community#101769] [Actions]
### Select Topic Area

Bug

### Body

I added new container builds using a matrix strategy to my repo. secrets.GITHUB_TOKEN is used for authn to ghcr.io.

Some of the builds succeed, and some of them fail: 
![7MMLxRN3cezvmqa](https://github.com/community/community/assets/1994130/67d26f96-883e-4b31-aa67-4b8239d92530)

Definition looks like this, and the PR is not from a fork:

```
env:                                                                     
  REGISTRY: ghcr.io 

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image: ['kernel-amd64', 'kernel-arm', 'kernel-arm64', 'uefipayload-amd64', 'multiboot-test-kernel-amd64']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/test-${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./.circleci/images/${{ matrix.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

Is this an issue with ghcr.io? I can't imagine why authentication would sometimes work and sometimes not with the same token.

(At the org and repo level, the token is set to allow read & write for all scopes.)
