### DISCUSSION TITLE
Can you set default inputs in a single place when running caller workflow?

### DISCUSSION THREAD

**Discussion by konck2** [community/community#101825] [Actions]
### Select Topic Area

Question

### Body

Having a single source for reusable workflow definitely helps with not repeating the functionality of the code.

```
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      A:
        default: abc
        required: true
        type: string
      B:
        default: abc
        required: true
        type: string
      C:
        default: abc
        required: true
        type: string
      D:
        default: abc
        required: true
        type: string
      E:
        default: abc
        required: true
        type: string
     ...

jobs:
  my-reusable-workflow-job:
    [ do something]
```

However, each caller workflow is still required to define its own inputs in every single file (imagine having 100's of these files). I am aware this is manual trigger, I want this to be manual and allow users to change inputs as needed. There is so much unnecessary repetition
```
name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      A:
        default: abc
        required: true
        type: string
      B:
        default: abc
        required: true
        type: string
      C:
        default: abc
        required: true
        type: string
      D:
        default: abc
        required: true
        type: string
      E:
        default: abc
        required: true
        type: string

jobs:
  call-reusable-workflow:
    uses: <reusable-workflow-ref>
    with:
      A: ${{ inputs.A }}
      B: ${{ inputs.B }}
      C: ${{ inputs.C }}
      D: ${{ inputs.D }}
      E: ${{ inputs.E }}
```

Is there anything that can be done to set above inputs in one place and reference it there?
