### DISCUSSION TITLE
How to always disable/skip a job in Github actions?

### DISCUSSION THREAD

**Discussion by alniv94** [community/community#101945] [Actions]
### Select Topic Area

Question

### Body

I have encountered an issue that needs me to temporally skipped on running a specific job every time i pushed a commit. Below is my workflow which is not working:
![image](https://github.com/community/community/assets/89484751/5982a656-bfa7-4c3f-8ebc-09349e9861ed)

name: Tests

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  e2e-test:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

**Comment by ghost** [comment]
To skip a job in GitHub Actions, you can use the if conditional with a value that always evaluates to false. It looks like you've attempted to use this approach. However, if the job is still running despite the if: false condition, this could be due to a syntax error or misconfiguration elsewhere in your workflow.

Here's a snippet that should effectively skip the e2e-test job:
```
name: Tests

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  e2e-test:
    if: false # This condition will always evaluate to false, thus skipping the job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # Your other steps
```
Ensure that the if: false line is correctly indented and aligned with the runs-on or steps fields. Also, double-check that there are no other conditions or steps overriding this behavior.

If you find that the job is still running, it could be helpful to validate your entire workflow file with a YAML linter to ensure there are no issues with the format or structure.

Additionally, if you plan to skip this job for a longer period, you might want to comment out the entire job or remove it temporarily from your workflow file to make it clear that it's not supposed to run.
