### DISCUSSION TITLE
Actions Secrets for collaborator to a private repository

### DISCUSSION THREAD

**Discussion by lidiapierre** [community/community#102193] [Actions]
### Select Topic Area

Question

### Body

Hello,
I am struggling with using secrets in a Actions workflow, I have looked at the documentation but still not working.

I am a collaborator to a private repository. The repo owner created repository secrets (action secrets). I am using those secrets in a Actions workflow, but they seem to be empty.

Here is how I am testing them in the workflow (jobs > build > steps):
```
    - name: Test Secrets 
      env:
        TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_MY_API_KEY: ${{ secrets.MY_API_KEY }}
      run: |
        echo ${#TEST_GITHUB_TOKEN}
        echo ${#TEST_MY_API_KEY}
```

and in the build I get an output for TEST_GITHUB_TOKEN but not for TEST_MY_API_KEY.

I confirmed with the repo owner that TEST_MY_API_KEY is correctly set... Can it be a permissions issue ?

Thank you for your help!
