### DISCUSSION TITLE
Matrix include and exclude as an array

### DISCUSSION THREAD

**Discussion by ghost** [community/community#102111] [Actions] [answered]
### Select Topic Area

Product Feedback

### Body

For [matrix variables](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) we can define an array of values. But for [include](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations) and [exclude](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#excluding-matrix-configurations) only lists are supported.

It would be very useful to be able to specify arrays for include/exclude, like the following
```yaml
jobs:
  build:
    strategy:
      matrix:
        os: [linux, macos, windows]
        arch: [amd64]
        node: [18, 20, 22]
        tests: [unittest, integration, all]
        include:
          - os: linux
            builder: [ubuntu-20.04, ubuntu-latest]
          - os: macos
            builder: [macos-13, macos-latest]
          - os: windows
            builder: [windows-2019, windows-latest]
        exclude:
          - os: linux
            tests: [unittest, integration]
          - os: macos
            tests: [unittest, integration]
          - os: windows
            tests: all
```

Existing approach is almost twice longer (14 vs 24) and is harder to read
```yaml
jobs:
  build:
    strategy:
      matrix:
        os: [linux, macos, windows]
        arch: [amd64]
        node: [18, 20, 22]
        tests: [unittest, integration, all]
        include:
          - os: linux
            builder: ubuntu-20.04
          - os: linux
            builder: ubuntu-latest
          - os: macos
            builder: macos-13
          - os: macos
            builder: macos-latest
          - os: windows
            builder: windows-2019
          - os: windows
            builder: windows-latest
        exclude:
          - os: linux
            tests: unittest
          - os: linux
            tests: integration
          - os: macos
            tests: unittest
          - os: macos
            tests: integration
          - os: windows
            tests: all
```
