### DISCUSSION TITLE
Install a program in a step, but isn't available in another one

### DISCUSSION THREAD

**Discussion by moi15moi** [community/community#102175] [Actions] [answered]
### Select Topic Area

Question

### Body

I have [this workflow](https://github.com/moi15moi/FontCollector/blob/Back_up-V3-on-going/.github/workflows/run_test.yml)

In my workflow, I install ``mkvtoolnix`` on ubuntu, mac and windows.
But, on windows, I don't know why, but the program is only available in the same step where I install it (in this case ``Install platform-specific requirements (Windows)``). I think it is because the environnement variable are cleaned in each different step.

But, in that case, how can I install ``mkvtoolnix`` and still be able to call the program in a another step (for instance, in ``Run tests``)?

Here is the [run](https://github.com/moi15moi/FontCollector/actions/runs/7675541832/job/20921900075?pr=34) of the workflow

**Comment by GirishHakki** [comment]
It seems like you're facing an issue with installing and using mkvtoolnix in different steps of your workflow, particularly on Windows. If environment variables are getting cleared between steps, you won't be able to access mkvtoolnix installed in a previous step.

**Comment by naveen-98** [comment]
The issue you're facing is likely due to the fact that environment variables set in one step are not automatically carried over to the next steps. To make the installed program (`mkvtoolnix` in this case) accessible in subsequent steps, you need to persist the environment changes. You can do this using environment files.

Here's an updated version of your workflow:

```
name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    name: "Test (${{matrix.os}}, Python ${{ matrix.python-version }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python requirements
      run: pip install --upgrade --upgrade-strategy eager .

    - name: Install platform-specific requirements (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install mkvtoolnix

    - name: Install platform-specific requirements (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install mkvtoolnix

    - name: Install platform-specific requirements (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install mkvtoolnix
        echo '##[set-output name=PATH;]${env:PATH};${env:ChocolateyInstall}\bin'

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run tests
      run: |
        mkvpropedit -h
        pytest

```

Changes made:

Windows Environment Variables:

On Windows, set the output for PATH in the `Install platform-specific requirements (Windows)` step. This output is then used to update the PATH for subsequent steps.

Use Persisted Environment in Subsequent Steps:

When setting the PATH in the Windows step, it's now appended to the existing PATH. This makes the changes persist across steps, allowing you to use `mkvpropedit` in the `Run tests` step.

**Reply by moi15moi** [reply]
For the answer, see: https://github.com/moi15moi/FontCollector/pull/38

**Comment by ghost** [comment]
Hello. The issue you're encountering on Windows with GitHub Actions is indeed related to how environment variables (and the system `PATH` in particular) are handled between steps in a workflow. When you install a program like mkvtoolnix using Chocolatey in one step, the changes it makes to the system `PATH` (to make its executables available) are only effective for the duration of that step. This is why `mkvpropedit` is not recognized in subsequent steps.

To resolve this, you can manually update the system `PATH` within the GitHub Actions environment to persist across steps. This involves using the `echo` command to add a `PATH` update to the GitHub Actions environment file, which GitHub Actions automatically processes and applies to the entire job.

Here's how you can adjust your Windows-specific step to ensure `mkvtoolnix` is available in subsequent steps:

```yaml
    - name: Install platform-specific requirements (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install mkvtoolnix
        echo "MKVToolNixPath=$(choco list --local-only mkvtoolnix --format=csv | ConvertFrom-Csv | Select -ExpandProperty 'InstallLocation')" | Out-File -Append -FilePath $env:GITHUB_ENV
        echo "PATH=$env:PATH;$env:MKVToolNixPath" | Out-File -Append -FilePath $env:GITHUB_ENV
```

In this updated step:

1. `choco install mkvtoolnix` installs mkvtoolnix as before.
2. We then use a PowerShell command to find the installation directory of mkvtoolnix (`$(choco list --local-only mkvtoolnix --format=csv | ConvertFrom-Csv | Select -ExpandProperty 'InstallLocation')`). This directory is then saved to a temporary environment variable `MKVToolNixPath`.
3. Finally, we append this path to the `PATH` environment variable and update the GitHub Actions environment file using `echo "PATH=$env:PATH;$env:MKVToolNixPath" | Out-File -Append -FilePath $env:GITHUB_ENV`. This makes the mkvtoolnix executables available in all subsequent steps.

This approach ensures that the changes to the `PATH` are recognized in subsequent steps of your workflow, allowing you to use `mkvpropedit` and other mkvtoolnix utilities as needed.
