### DISCUSSION TITLE
Run job on each node of label

### DISCUSSION THREAD

**Discussion by mihalt** [community/community#102215] [Actions]
### Select Topic Area

Question

### Body

Hi! Say me, please, how can I run a job of each node of labels? Not just one of node of label, like in matrix https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Comment by gopal-jogi** [comment]
To run a job for each node of labels, you might not necessarily use a matrix, but instead, you can iterate over the nodes and create separate jobs for each label. 
ex:
name: Run Job for Each Label

on:
  push:
    branches:
      - main

jobs:
  run_for_each_label:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        label:
          - node1
          - node2
         

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run job for each label
        run: |
          echo "Running job for label: ${{ matrix.label }}"

**Comment by ghost** [comment]
Hello Mihail, you can utilize the matrix strategy to define multiple jobs that run under different conditions. However, if you want to ensure that a job runs on every node of a specific label, you might need to explicitly specify each node or set up a more dynamic approach if the list of nodes is subject to change.

Here's a basic example using a static list of nodes:

```yaml
name: Multi-Node Label Job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_label: ['label1', 'label2', 'label3'] # Replace these with your actual labels

    steps:
    - uses: actions/checkout@v2

    - name: Run Job for Each Node Label
      run: echo "This job runs for node with label ${{ matrix.node_label }}"
      # Add additional steps here
```

In this example, the `matrix.node_label` array specifies different labels that you might have assigned to your self-hosted runners. The job named `Run Job for Each Node Label` will run separately for each label specified in the matrix.

If your labels correspond to different self-hosted runners and you want to ensure that the job runs on a runner with the specified label, you should use the `runs-on` field dynamically with the matrix, like so:

```yaml
jobs:
  build:
    runs-on: ${{ matrix.node_label }}
    strategy:
      matrix:
        node_label: ['self-hosted-linux', 'self-hosted-windows', 'self-hosted-mac'] # Specify your self-hosted runner labels here

    steps:
    - uses: actions/checkout@v2
    - name: Run Job
      run: echo "Running on ${{ matrix.node_label }}"
```

This setup ensures that the job runs on different self-hosted runners based on the labels specified in the matrix, allowing for parallel execution across different environments or configurations.

If your nodes change dynamically and you cannot specify all labels statically in the workflow file, you might need to use a more advanced setup, potentially involving a preliminary job that determines the available nodes/labels and outputs them for use in a matrix by subsequent jobs. This could involve scripting and leveraging the GitHub API or other dynamic configuration tools.
