### DISCUSSION TITLE
Write Actions variables for another repo

### DISCUSSION THREAD

**Discussion by thomasreiser** [community/community#102565] [Actions]
### Select Topic Area

Question

### Body

I am currently trying to write Actions variables and/or secrets for another repository within my private organization.
It seems like there are no `permission`s existent that allow me to do this.

Do I need to manually create a custom token and use this one?

**Comment by thisisthetechie** [comment]
Depending on what your output is, you may need to use a custom token (sort of like a service account) as you suggest.

It's easy enough to add in the token - just create a user with (limited) permissions to the target repo's and get it's PAT. Store that PAT as a secret in your source Repo (or Org, or Environment) and then pass it as an environment variable to in your Action:
```
- name: Update Variable
  env:
    GH_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT }}
  run: |
    gh secret set --app actions --body "MySecretValue" --repo MyOrg/MyRepository2
```
