### DISCUSSION TITLE
run a workflow when a PR created from branches starting with BASH and to base branch main

### DISCUSSION THREAD

**Discussion by uday1kiran** [community/community#102516] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

want to create a workflow which should trigger when creating a PR to main from branches starting with name BASH
Created with below but not working.
name: Validate PR

```
on:
  pull_request:
    branches:
      - 'BASH*'
```

When I keep just * instead of BASH* it will run with any branch PR to main.
But I want to run this workflow only when the branch name starts with BASH and workflow to main as base branch.

Even tried this below which got from chatgpt. But it didn’t work.

name: Validate PR

```
on:
  pull_request:
    branches:
      - 'BASH*'
    base:
      - 'main'
```
