### DISCUSSION TITLE
Mirroring the repo to another github repo using Github Actions

### DISCUSSION THREAD

**Discussion by OsmaniMirand** [community/community#102630] [Actions]
### Select Topic Area

Question

### Body

Is it possible using Github Actions to make a private Repo that i have for production, to mirror the client's private repo? so in general, they want to have always my latest change on my production branch to their branch into the repo that they have? if yes, please let me know how.

**Comment by ravindudil5han** [comment]
Yes, it's possible to use GitHub Actions to mirror changes from your private repository to your client's private repository. You can achieve this by creating a workflow that triggers on changes to your production branch. Within the workflow, you can use Git commands to push changes to your client's repository.

Here's a simplified example:

1. Create a GitHub Actions workflow file (e.g., `.github/workflows/mirror.yml`) in your production repository.

2. Define the workflow:

```yaml
name: Mirror to Client Repo

on:
  push:
    branches:
      - production

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Mirror changes to client's repo
        run: |
          git remote add client_repo https://github.com/client_username/client_repo.git
          git push client_repo production
        env:
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
```

3. In the example above, replace `https://github.com/client_username/client_repo.git` with the URL of your client's repository. Also, make sure to set up a personal access token with appropriate permissions in your repository secrets and use it in the `CLIENT_TOKEN` environment variable.

4. Adjust the workflow according to your specific needs, and be cautious about handling credentials securely.

Remember to test thoroughly before deploying such workflows to avoid unintended consequences.
