### DISCUSSION TITLE
Inconsistent Environment deployment approval behavior with max-parallel matrix strategy

### DISCUSSION THREAD

**Discussion by mbmcmullen27** [community/community#102771] [Actions]
### Select Topic Area

Bug

### Body

Github Actions workflows that use the matrix strategy have inconsistent behavior around approving deployments, when using the max-parallel option. When the option is set high enough to include all of the values defined in the matrix, only 1 approval is required, if its lower, it will take as many approvals as it takes to cover all the jobs. I set up [this repo](https://github.com/mbmcmullen27/max-parallel) to model the problem.

The specific scenario this came up in, I was trying to repeat a job multiple times with different input all for a single environment. All of these should run in `test` and are part of the same workflow so I only want to approve it once

Here is a workflow that showcases the problem:
```
name: Max Parallel
on:
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      max-parallel: 2
      matrix:
        value: [one, two, three, four, five]
    steps:
      - name: echo
        run: echo ${{ matrix.value }}
```
- with max-parallel set to `2` I need to approve this workflow 3 times every time its run, when its set to `5`, I only have to approve it once

[example with max-parallel high enough to include all matrix values](https://github.com/mbmcmullen27/max-parallel/actions/runs/7713067562)
[example with max-parallel covering only a subset of values](https://github.com/mbmcmullen27/max-parallel/actions/runs/7712189058)

I'm curious if this was a specific design choice or not because I would expect to only need one approval per workflow run, regardless of how many jobs run. Otherwise I'm approving the same workflow 3 or 4 times for a single deployment. If it is intentional, an option to disable this behavior would be helpful

We've worked around this with a bash loop and consolidating the steps in the workflow, but it would be much preferred and easier to read if we could use the official Github matrix feature.

Thanks,
Mike
