### DISCUSSION TITLE
Merge queue: How to run a job ONLY on the merge queue?

### DISCUSSION THREAD

**Discussion by Goddchen** [community/community#102764] [Actions]
### Select Topic Area

Question

### Body

Hi! We are using the merge queue with quite some success so far. But now we have job that should **only** run on the merge queue, not anywhere else.

* The job has to be listed under the required jobs under the branch protection rules (to make it a blocker for merging)

So, we're not able to merge any PRs anymore, because they do not have a job with that name.

Our workaround: create a job with the same name, that is run on PRs, but that does literally nothing (just echo something). That works, the NOOP job is run on PRs and we can add them to the merge queue.

But now this happens:

The merge queue lists the NOOP jobs as successfully run on the merge queue. Although they haven't actually run there. The merge queue triggered the correct jobs. I can see them running with "Merge group checks requested" and "Triggered via merge group". But the merge group does not pick up those jobs, it simply says that the NOOP jobs (that were triggered hours before, on the last push on the PR) have been successful and is happy with that.

How do we fix that?

Here are our configuration files:

NOOP:

```yaml
on:
  push:
    branches:
      - "**"

jobs:
  build_android:
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "NOOP, the actual job is executed only on the merge queue"'

  build_ios:
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "NOOP, the actual job is executed only on the merge queue"'
```

Real one:

```yaml
on:
  merge_group:
  workflow_dispatch:

jobs:
  build_android:
    ...
  build_ios:
    ...
```

Is it because the NOOP workflow also triggers on all branches and is therefore valid for the merge queue? If so, how to we prevent that?

**Comment by ghost** [comment]
Looks weird, but why your are using
```yaml
on:
  push:
    branches:
      - "**"
```

Shouldn't that be a `pull_request` event instead of the `push` one?

[Triggering merge group checks with GitHub Actions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions)
> Note: If your repository uses GitHub Actions to perform required checks on pull requests in your repository, you need to update the workflows to include the `merge_group` event as an additional trigger. Otherwise, status checks will not be triggered when you add a pull request to a merge queue. The merge will fail as the required status check will not be reported. The `merge_group` event is separate from the `pull_request` and `push` events.

1. Create a PR and it will trigger a workflow `NOOP` and report a status for `build_android` and `build_ios` jobs which are in the branch protection rules
2. Merge the PR and it will be added to the merge queue
3. During merge queue execution a workflow `Real one` will be triggered and will report a status for `build_android` and `build_ios` jobs.
4. After performed checks PR should be merged

Did [similar checks](https://github.com/orgs/community/discussions/53922#discussioncomment-8349817) and it should work.

**Comment by Goddchen** [comment]
Yeah `pull_request` works fine, **until** you find out that PRs created by bots (with a `GITHUB_TOKEN`) will not trigger `pull_request` 🤦 

What exactly is your suggested fix here? In your linked post I can see no difference to what we currently do - which produces the issue.

**Reply by ghost** [reply]
Just described that merge queue is working when we use `pull_request` event. From your question the whole context was probably not so clear.

Per documentation [Using the GITHUB_TOKEN in a workflow](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow), `GITHUB_TOKEN` will not work on `push` either.

Did you try to call workflow manually after the push?
- [Push from Action does not trigger subsequent action #25702](https://github.com/orgs/community/discussions/25702)
- [pull requests triggered from actions don't trigger other actions #57484](https://github.com/orgs/community/discussions/57484)

**Comment by Goddchen** [comment]
> GITHUB_TOKEN will not work on push either

It does for us on multiple workflows 🤷‍♂️ 

Maybe I provided too much context and that confuses people. Let me rephrase the question:

Why does the merge queue consider a job with the same name that has run on the PR before as success and does not run the job again as part of the merge queue?

**Reply by ghost** [reply]
**Workflows**

<details>
<summary>workflows</summary>

`push.yaml`
```yaml
name: Push

on:
  push:
    branches:
      - "**"

jobs:
  build_android:
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "event_name is ${{ github.event_name }} and ref is ${{ github.ref }}"'
```

`mq.yaml`
```yaml
name: MQ

on:
  merge_group:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "event_name is ${{ github.event_name }} and ref is ${{ github.ref }}"'
      - run: 'exit 1'
```
</details>

**Test**
Did a simple check with the following flow
1. Update the file and push it to a new branch - `Push` workflow is triggered and `build_android` = 🟢 
2. Create a PR - **check is passed** without any additional workflows run and this is probably because `build_android` is already 🟢 on `Push` with that `commit id`
3. Press "Merge when ready" to move PR to the Merge queue
4. `Push` workflow is run again and probably because condition `if: github.event_name != 'merge_group'` is not working here
      > event_name is push and ref is refs/heads/gh-readonly-queue/main/pr-4-132e628a9c06bfa9e31bffc2e7b13956289a926e
     
     Anyway, `build_android` = 🟢

5. `MQ` workflow is run and fail - `build_android` = 🔴  and PR is moved back from Merge queue, even if on step 4 we have `build_android` = 🟢 from `Push` workflow.

**Result**
In that flow, with these workflows, Merge queue trigger workflow and use the check from it.
