### DISCUSSION TITLE
Github Actions - Workflow job not setting status check

### DISCUSSION THREAD

**Discussion by alniv94** [community/community#102709] [Actions]
i have this github workflow: name: Tests

on:
  workflow_dispatch:
  
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  e2e-test:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:

The current functionality is operating correctly under the specified condition. However, an issue arises when I submit a commit in a pull request (PR). In this case, the workflow skips, as per the condition. Although triggering the workflow manually runs it successfully, the PR checks still show a skipped status. I aim to modify this status from skipped to running when triggered manually via workflow_dispatch in the context of a PR. Any idea how to update those status checks, as of now it never get updated in the pull request UI.

**Comment by fury-05** [comment]
It appears that you are facing an issue where the GitHub Actions workflow triggered by a manual workflow dispatch in the context of a pull request (PR) shows a skipped status in the PR checks. To address this issue, you can make a small modification to your workflow to ensure that the status is updated correctly. You can use the github.event_name context variable to determine if the workflow is triggered by a push or a manual dispatch.

updated script of your workflow that should address the issue:
```yaml
name: Tests

on:
  workflow_dispatch:
    branches:
      - '*'
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  e2e-test:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.triggering_branch == 'develop')
    runs-on: ubuntu-latest
    steps:
      # Your workflow steps here

```

1. I added a workflow_dispatch trigger that can run on any branch ('*').
2. I modified the condition for the e2e-test job to run on both push to the develop branch and manual workflow dispatch but only when the triggering branch is 'develop'. This condition ensures that the workflow runs for manual dispatch only on the 'develop' branch.

When you manually trigger the workflow with workflow_dispatch, make sure to specify the branch as 'develop' to satisfy the condition for the workflow to run in the context of a PR. This should ensure that the checks are not marked as skipped in the PR checks.
