### DISCUSSION TITLE
workflow_run triggered only on success

### DISCUSSION THREAD

**Discussion by uridium** [community/community#102876] [Actions]
### Select Topic Area

Question

### Body

```yaml
name: Workflow B

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed
```

That triggers "Workflow B" regardless of the result of "Workflow A". That would be REALLY great to have "types: success".
With the current approach I not only end up with a tons of skipped runs in the UI, but also have to do some gimmicks, like:

```yaml
jobs:
  Run-Workflow-B:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
```

Could we please finally have:

```yaml
on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - success
```
