### DISCUSSION TITLE
Is there a way to install my actions modules before running the main index.js file

### DISCUSSION THREAD

**Discussion by amosmachora** [community/community#102976] [Actions]
### Select Topic Area

Question

### Body

I am creating a reusable action. The problem is its a JS action and I also use other libraries to help me during development. Libraries like uid, Axios, etc. The problem is i can't install the libraries. I ran into "module cannot be found etc". I tried adding a pre-script to my action.yml like `pre: npm install` but that created an error cannot find the file npm install. I don't know wtf that is. I tried creating a composite action but that kept installing the dependencies of my actions users. Like not my actions deps. 

Somebody help.

Here is my current YML file.

```
name: "release-auto-blogger"
description: "A github action to deploy blogs automatically to hash node"

inputs:
  project-name:
    description: "The name of the project for the blog"
    required: true

  hashcode-host:
    description: "The hashcode host e.g amosmachora.hashnode.dev"
    required: true

  subtitle:
    description: "Subtitle for your blogs"

  cover-image:
    description: "A cover image url for the blog"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "book"
  color: "yellow"

```
right nowIi have opted to just push node modules to Github which is making me feel cringe and bad.
