### DISCUSSION TITLE
How to pass variables to Cron on Schedule?

### DISCUSSION THREAD

**Discussion by airtonchagas** [community/community#103053] [Actions]
### Select Topic Area

Question

### Body

Hey guys!!!

Is there a way to pass variables to the schedule cron?
My idea would be to use the variable as a condition in jobs, saving cron rewriting.

Like this:

```yaml
name: My workflow

env:
  CRON_JOB1: '00 09 * * 1-5'
  CRON_JOB2: '00 21 * * 1-5'

on:
  schedule:
    - cron: ${{ env.CRON_JOB1 }}
    - cron: ${{ env.CRON_JOB2 }}

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job 1
    if: ${{ github.event.schedule == env.CRON_JOB1 }}
    steps:
      ...

  job2:
    runs-on: ubuntu-latest
    name: Job 2
    if: ${{ github.event.schedule == env.CRON_JOB2 }}
    steps:
      ...
```
