### DISCUSSION TITLE
Allow for contexts variables in a "uses:" line

### DISCUSSION THREAD

**Discussion by cboyd-impinj** [community/community#103171] [Actions]
### Select Topic Area

Question

## BODY

Is there any way to pass a variable to an action path in the uses line for instance:
```
## top of the workflow:
name: example
env:  
  REPORTER_VERSION: v1.7
Jobs:
  Example:
     Steps:
    - name: Test Report
              uses: dorny/test-reporter@${{ version }}
              with:
                  version: ${{ env.REPORTER_VERSION }}
```
