### DISCUSSION TITLE
Merge queue specific checks

### DISCUSSION THREAD

**Discussion by eduprozo** [community/community#103114] [Actions]
### Select Topic Area

Question

### Body

I'd like to have required status checks as branch protections ONLY for merge queue PRs. At the moment, I can only enable them for what seems to include all PRs, merge queue ones included. This leads to having to run things twice, when users open a PR and when the queue opens a `gh-readonly` PR as well.

Things I've tried:
- Use rulesets to only run checks on merge queue PRs: I get Push Blocked error
- PR Path filtering: doesn't work

Any ideas on how to get this done? Or is it not supported (discouraged even?) at all

**Comment by ghost** [comment]
This is a [known issue](https://github.com/orgs/community/discussions/46757?sort=old#discussioncomment-4909336) (almost 1 year already) and this is because status and merge checks jobs coupled. And currently we have just some workarounds for that.

### Run workflows on both events

1. Run `PR` and `MQ` workflows on both events and add their jobs in the list `Require status checks to pass before merging` under branch rules
   ```yaml
   on:
    pull_request:
    merge_group:
   ```

2. Use [conditional job execution](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif) in `PR` and `MQ` workflows
    ```yaml
    # PR
    if: github.event_name != 'merge_group'
    # MQ
    if: github.event_name != 'pull_request'
    ```

3. In case of matrix, we also can use an additional job, which will [check matrix status](https://github.com/orgs/community/discussions/26822) and use just it under branch rules
    ```yaml
    jobs:
      build:
        strategy:
          matrix:
            node: [16, 18, 20]
          ....

      status-check:
        if: always()
        needs: [build]
        runs-on: ubuntu-latest
        steps:
          - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')  || contains(needs.*.result, 'skipped') }}
            run: exit 1
    ```

In that way
 - Both jobs will be started on PR and MQ
 - Only required steps will be executed and all required jobs will report their status to pass checks


### Use same job name for `PR` and `MQ`

 1. Create a job with the same name in `PR` and `MQ` workflows - `status-check`
    `pr.yaml`
    ```yaml
    name: PR

    on:
      pull_request:

    jobs:
      status-check:
        runs-on: ubuntu-latest
        steps:
          - name: PR check
            run: sleep 10
    ```

    `mq.yaml`
    ```yaml
    name: MQ

    on:
      merge_group:

    jobs:
      status-check:
        runs-on: ubuntu-latest
        steps:
          - name: Merge queue check
            run: sleep 120
    ```

 2. Add just `status-check` job under branch rules

 3. In case of matrix we can use an additional job as well

In that way
 - Only required workflow will be started on each event
 - On PR and MQ steps check will pass because in both cases required job (by name) will be executed
