### DISCUSSION TITLE
React App builds but GitHub actions cant find the build dir.

### DISCUSSION THREAD

**Discussion by jasoncsmith** [community/community#103182] [Actions] [answered]
### Select Topic Area

Question

### Body

I have attached a screenshot of my directory structure. the react app lives in `client`. the package.json file at root has the script `deploy` in there which will: 
```
"deploy": "cd ./client && npm i && npm run build"
```
My .yaml file is:
```
   name: GH Pages deploy

  on:
    push:
      branches: master

    pull_request:
      branches: master

  jobs:
    build-deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout 🛎️
          uses: actions/checkout@master
          with:
            persist-credentials: false

        - name: Build 🏗️
          run: npm run deploy
          env:
            NODE_ENV: production

        - name: Deploy to GH Pages 🚀
          if: ${{ github.event_name != 'pull_request' }}
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./client/build

```

I can see that it builds fine. 
Then in the deploy step it is removing all the build files and then
says that it cant find .../client/build directory.

Can anyone please explain to me what might be going on? Thank you.

```
. . .
  rm 'static/media/iconic_stroke.5a749975e528b4be3aed.woff'
  rm 'static/media/iconic_stroke.6a021521fded41c6bd26.ttf'
  rm 'static/media/iconic_stroke.8f1417580145acbe0e93.eot'
  rm 'static/media/iconic_stroke.a467f613989209a71754.svg'
  rm 'static/media/loader-o-yellow.abe59b1aab08249d4a65.gif'
  [INFO] chdir /home/runner/actions_github_pages_1706902835106
  [INFO] prepare publishing assets
  [INFO] copy /home/runner/work/React-Portfolio/React-Portfolio/client/build to /home/runner/actions_github_pages_1706902835106
  cp: no such file or directory: /home/runner/work/React-Portfolio/React-Portfolio/client/build/.*
  [INFO] delete excluded assets
  rm: no paths given
. . .
```
Directory structure:
![ss2](https://github.com/community/community/assets/5572206/d8a54fd5-0b63-4ba0-bf5e-b13399845565)

The artifact has everything but the build directory:
```
PS C:\Users\jason> tar -xvzf C:\Users\jason\Downloads\github-pages-1\artifact.tar -C .
x ./
x ./assets/
x ./assets/css/
x ./assets/css/style.css
x ./database.rules.json
x ./backend/
x ./backend/index.js
x ./backend/api/
x ./backend/api/user/
x ./backend/api/user/index.js
x ./backend/api/user/createUser.js
x ./backend/api/projects/
x ./backend/api/projects/index.js
x ./backend/api/projects/getProjects.js
x ./backend/package.json
x ./backend/package-lock.json
x ./backend/schemas/
x ./backend/schemas/project.js
x ./backend/schemas/user.js
x ./firebase.json
x ./config.js
x ./client/
x ./client/README.md
x ./client/index.html
```
