### DISCUSSION TITLE
How to save and load docker images using actions/cache or other mechanisms?

### DISCUSSION THREAD

**Discussion by Nefcanto** [community/community#103495] [Actions]
### Select Topic Area

Question

### Body

This is a sample of my action YAML file:

```
      - name: Build production docker
        run: |
          docker build -t ghcr.io/my-org/my-repo/api:latest . --no-cache --progress=plain

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the image
        run: |
          docker push ghcr.io/my-org/my-repo/api:latest

      - name: Logout from GitHub Container Registry
        run: |
          docker logout
```

As I see logs for actions, the `docker build` takes a lot of time, and a major part of it is because it downloads a `FROM` image from the docker hub.

The image name is `holism/api`. I want to cache this image but I'm stuck at how to cache it and how to load it in subsequent action runs.

I can't find a good documentation for this and ChatGPT is not helping either. Can anybody please help me with this?

**Comment by ghost** [comment]
GitHub Actions doesn't directly support Docker image caching in the same way it does for dependencies with actions/cache.

**Comment by ghost** [comment]
you can achieve similar results by combining a few techniques. First, ensure Docker's BuildKit is enabled as it has improved caching mechanisms. You can enable it by setting the environment variable DOCKER_BUILDKIT=1 before your docker commands. BuildKit stores its cache separately from docker images and layers. You can leverage actions/cache to cache this BuildKit cache. try like this:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker BuildKit
      run: |
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and cache Docker image
      run: |
        docker build --tag ghcr.io/my-org/my-repo/api:latest . \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache-new

    - name: Move new cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

```
Log in to GitHub Container Registry, Push, Logout steps remain the same
