### DISCUSSION TITLE
Allow options array to be defined in external .yml file

### DISCUSSION THREAD

**Discussion by ROMVoid95** [community/community#10455] [Projects and Issues]
There could be a situation where a repo might need or want a dropdown options list that contains a fair amount of selections.

It would be great if you were able to define a dropdowns options array in an external .yml file instead of directly inside of the issues template.

Possibly by allowing the defined file to reside in the .github directory
Example: using the example from [GithubDocs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#example-3)
```yml
body:
- type: dropdown
  id: download
  attributes:
    label: How did you download the software?
    options:
      - Homebrew
      - MacPorts
      - apt-get
      - Built from source
  validations:
    required: true
```

you could optionally a file in `.github/` called `dropdownlist.yml`.
The list is obtained by referencing the `id` of the dropdown type 
```yml
download:
  - Homebrew
  - MacPorts
  - apt-get
  - Built from source
```

And define this file in the ISSUE_TEMPALTE. example uses `.github/` directory as the relative path
```yml
body:
- type: dropdown
  id: download
  attributes:
    label: How did you download the software?
    options:
      - file: dropdownlist.yml
  validations:
    required: true
```
