### DISCUSSION TITLE
Support dynamic outputs in Composite Actions

### DISCUSSION THREAD

**Discussion by miyajan** [community/community#10529] [Actions]
JavaScript Actions can set dynamic outpus.

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs
> If you don't declare an output in your action metadata file, you can still set outputs and use them in a workflow.

But Composite Actions seem not to be able to set dynamic outputs. This difference makes it impossible for some actions to be composite actions.

I found the support community entry about this.
https://github.community/t/dynamic-outputs-from-a-composite-action/221684

Please support dynamic outputs in Composite Actions.

**Comment by ethomson** [comment]
Thanks @miyajan - I'll talk to the engineering team about this.

**Reply by keramblock** [reply]
Any news about it? I really do not want to learn JS just to make something for my CI =(

**Reply by RichardTMiles** [reply]
https://github.com/actions/runner/pull/2477

**Comment by wudstrand** [comment]
+1

**Reply by RichardTMiles** [reply]
bump https://github.com/actions/runner/pull/2477

**Comment by RichardTMiles** [comment]
https://github.com/orgs/community/discussions/32628#discussioncomment-3620321

Might we consider the following:

```
outputs:
${{ format('privateAZASubnet-{0}', matrix.aws-region ) }}: ${{ steps.network.outputs[format('privateAZASubnet-{0}', matrix.aws-region )] }}
```

**Reply by RichardTMiles** [reply]
https://github.com/actions/runner/pull/2477
```yaml
   strategy:
      matrix:
        os: ['linux', 'windows','macos']
        arch: ['x86','x64']
    outputs:
      ${{ matrix.os }}_${{ matrix.arch }}_result: ${{ steps.step1.outputs.test }}
```
