### DISCUSSION TITLE
Is it possible to cache build outputs and dependencies from the prior job?

### DISCUSSION THREAD

**Discussion by unokim-dev** [community/community#105308] [Actions] [answered]
### Select Topic Area

Question

### Body

I have difficulties running github `check` action to build and test my kotlin + spring boot project because of the memory shortage issues like OOM,
so I'm planning to make the check workflow which consists of jobs like this:

![image](https://github.com/community/community/assets/111929571/2ecf7fec-da68-4b6f-aefb-8890ac295846)

1. `warm-up` job just builds and never tests using gradle command `./gradlew build -x test`
2. `check-*` job just runs part of the tests and never builds but uses build cache from `warm-up` using gradle command `./gradlew test -DtestIncludeTags=?`
3. `check` just lets me know that all the jobs are completed.

So I'd like to expect some benefits from the flow of the jobs above like:

- `check-*` jobs execute entire tests for the project parallel running action runners simultaneously.
- `warm-up` provides build outputs and dependencies, so `check-*` jobs never have to build the project, therefore it speeds up the overall process and most importantly, save memory.

Will my idea be possible?
If so, how do I achieve this?
Here's my current workflow script in testing:

```yaml
name: Checks
on:
  pull_request:
  workflow_dispatch:

jobs:
  warm-up:
    runs-on: my-self-hosted-runner
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: See Gradle Daemon Status
        run: ./gradlew --status
      - name: Build with Gradle
        run: ./gradlew build -x test

  check-repository:
    needs: warm-up
    runs-on: my-self-hosted-runner
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: See Gradle Daemon Status
        run: ./gradlew --status
      - name: Test with Gradle
        run: ./gradlew test -DtestIncludeTags=repository


  check-others:
    needs: warm-up
    runs-on: my-self-hosted-runner
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: See Gradle Daemon Status
        run: ./gradlew --status
      - name: Test with Gradle
        run: ./gradlew test -DtestExcludeTags=controller,repository,integration-service

#  check-controller:

#  check-integration-service:

  check:
#    needs: [check-controller, check-repository, check-integration-service, check-others]
    needs: [check-repository, check-others]
    runs-on: my-self-hosted-runner
    steps:
      - name: Checks complete
        run: |
          echo "Checks complete!!!"
```

I think the script has problem. When I see how it works, each job has "post" steps that finishes its work. It doesn't seem to pass their outputs like caches to the next job. In order to make my plan work, the `warm-up` should pass the caches to the next jobs. I just don't know how to do it.

Thank you.

**Comment by ghost** [comment]
Hello. 
Here’s how you can modify your workflow to cache the build outputs and dependencies from the warm-up job and use them in the subsequent jobs: 
Cache the output in the warm-up job: You need to add steps to save the build cache using the actions/cache action after the build is complete.
Restore the cache in the test jobs: Before running the tests, add steps to restore the cache from the warm-up job.
Here's an example of how you can do this:
```
jobs:
  warm-up:
    runs-on: my-self-hosted-runner
    ...
    steps:
      ...
      - name: Cache Gradle layers
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

  check-repository:
    needs: warm-up
    runs-on: my-self-hosted-runner
    ...
    steps:
      ...
      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Test with Gradle
        run: ./gradlew test -DtestIncludeTags=repository
```
What this does is:

The actions/cache step in the warm-up job saves the Gradle cache after the build.
The actions/cache step in the check-repository (and other test jobs) tries to restore the cache with the same key.
You can adjust the path to include any other directories where build outputs are stored.

Make sure to generate a unique cache key for each build. This is typically done using a combination of static strings and functions that hash your dependency files, like hashFiles('**/*.gradle*', '**/gradle-wrapper.properties').

Please note that the cache is immutable once created, and if the key doesn't change, newer caches won't be saved. The restore-keys option is used to fetch the cache if an exact match is not found, allowing fallback to previous caches.

By doing this, the build outputs and dependencies from the warm-up job will be available to the test jobs, which should help you avoid redundant builds and save memory as you intended.

**Comment by unokim-dev** [comment]
Thank you very much @h0vhann1syan , I am trying to apply your suggestions to my action script, but here are 2 concerns before taking action.

1. I simply wrote `runs-on` runner information like `my-self-hosted-runner` in the example above, but actually there are 6 independent runners on my github action environment. This is to run 4 subsequent test jobs(`check-*`) in parallel. Will the stored cache in `warm-up` job be available to the subsequent jobs like `check-repository`, `check-controller` each running on different runners? I'm afraid `my-self-hosted-runner-2` running `check-repository` would never know the cache stored in `my-self-hosted-runner-1` which ran `warm-up` job.
2. I'm using `setup-gradle` action in the middle of the jobs. The guide of it says "Avoid using actions/cache", because `setup-gradle` already does the cache thing. I'll put the reference  below. What do you think about that?

Thanks.

ps. cache action has been upgraded to `v4` 3 weeks ago. 👍 

```
uses: actions/cache@v4
```

## Reference

* https://github.com/gradle/actions/blob/main/setup-gradle/README.md#incompatibility-with-other-caching-mechanisms
* https://github.com/actions/cache

**Comment by ghost** [comment, marked as answer]
Hi @unokim-dev. You raise valid concerns. Let's address each of them:

1. **Cross-runner caching**: If your subsequent jobs (`check-repository`, `check-controller`, etc.) are running on different self-hosted runners, then the cache stored in one runner won't be directly accessible to another runner. In this case, you can use a shared network file system (NFS) or another shared storage solution to store the cache and make it accessible to all the runners. Alternatively, you can use a cloud-based caching solution like Amazon S3 or Azure Blob Storage, which can be accessed by all your self-hosted runners. You'll need to modify your caching strategy accordingly to ensure that the cache is accessible across different runners.

2. **setup-gradle action and caching**: If you're using the `setup-gradle` action, which already handles caching internally, you might not need to explicitly use the `actions/cache` action for caching Gradle dependencies. In this case, you can rely on the caching mechanism provided by `setup-gradle`. However, you should ensure that the caching strategy used by `setup-gradle` aligns with your requirements and that it's effectively caching the dependencies you need across your jobs.

Given these considerations, you may want to:
- Review the caching mechanism provided by `setup-gradle` to understand how it works and whether it meets your caching needs.
- If `setup-gradle` handles caching effectively, you might not need to use the `actions/cache` action explicitly for Gradle dependencies. Instead, focus on ensuring that the cache managed by `setup-gradle` is accessible across your jobs, especially if they're running on different self-hosted runners.

It's essential to test your workflow thoroughly after making these adjustments to ensure that caching works as expected across different runners and that your build process remains efficient and reliable.

**Reply by unokim-dev** [reply]
Thanks @h0vhann1syan.

I can't do cross-runner caching unless I use shared storage, so I just made the cache right in front of the test like this:

```yaml
jobs:
  check-controller:
    runs-on: my-self-hosted-runner
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
      - name: Gradle Daemon Status
        run: ./gradlew --status
      - name: Build Gradle (Warm-up)
        run: ./gradlew build -x test
      - name: Compile Gradle Test (Warm-up)
        run: ./gradlew compileTestKotlin
      - name: Test with Gradle
        run: ./gradlew test
```

This isn't beautiful enough, but it works to get cache before testing for each job on every runner.
