### DISCUSSION TITLE
Add 'lowercase' and other string manipulation functions

### DISCUSSION THREAD

**Discussion by chriskuech** [community/community#10553] [Actions]
Please add more GitHub Actions expression functions for manipulating strings.  Specifically, a `lowercase` function would be very beneficial, but generally, there is no way to set environment variables across the entire workflow if they require even basic manipulation (such as converting to lowercase).

Motivation: https://github.community/t/github-actions-repository-name-must-be-lowercase/184924

**Comment by ethomson** [comment]
That's true; I don't want to add _too_ many functions to the syntax, but there are a few that would be very useful, including case changing.  I appreciate your feedback, and we'll put it on the backlog.

**Comment by lukasz-mitka** [comment]
There are workarounds if anyone is interested:
https://github.com/ASzc/change-string-case-action
https://github.community/t/additional-function-s-lowercase-uppercase/140632/2

That said, I would love to have this built in.

**Reply by Entepotenz** [reply]
I wrote an alternative to the ASzc/change-string-case-action version.
https://github.com/Entepotenz/change-string-case-action-min-dependencies

It is using pure python for the string conversion.
It does not depend on any library and therefore does not require any maintenance from security perspective :-)
Additionally I have a couple of tests running automatically before publishing.

**Comment by mpusz** [comment]
Another motivational example: https://github.com/conan-io/conan/issues/11705.

**Comment by dahlia** [comment]
It's not that problematic when you need to change letter cases in shell, because shells usually has built-in feature for that (and I believe it shows how frequent we need changing letter cases).  However, when you need to change letter cases before put it in input parameters of actions, it gets us in trouble.

Here's another motivational example.  Whereas GitHub's container registry disallows image names to contain any upper letters, `github.repository` preserve letter cases (i.e., if you put any upper letters in your org name or repo name `github.repository` contains upper letters too).  Therefore, I cannot reuse `github.repository` for image names:

```yaml
- uses: docker/build-push-action@v3
  with:
    push: true
    tags: ghcr.io/${{ github.repository }}:latest  # Does not work if any upper letter appears
```

At present, I need to work around this problem by utilizing shell script:

```yaml
- id: lower-repo
  shell: pwsh
  run: |
    "::set-output name=repository::$($env:GITHUB_REPOSITORY.ToLowerInvariant())"
- uses: docker/build-push-action@v3
  with:
    push: true
    tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
```

**Reply by lukasz-mitka** [reply]
For docker it's actually better to use `docker/metadata-action` which handles casing and much more.
```yaml
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

**Reply by dahlia** [reply]
That looks cool.  However, it's just an example.  My standpoint is still valid.

**Reply by lukasz-mitka** [reply]
Of course it's still valid. What I mean is, this example is not perfect since it's designed to be used differently.

**Reply by Silvenga** [reply]
It should be noted that cache syntax can't make use of docker-meta, so lowercasing the repository name is still required.

**Reply by spectrapulse** [reply]
> It should be noted that cache syntax can't make use of docker-meta, so lowercasing the repository name is still required.

I'm running into a case of this as we speak. So it kind of sucks that there's still no proper solution for this.

**Reply by lukasz-mitka** [reply]
It's ridiculous how Github ignores these obviously missing features. To little AI in it for them to bother.

**Reply by yanyongyu** [reply]
I encountered the same problem when using docker buildx. My work around is using the bash lower transformation:

```yaml
- id: lower-repo
  run: |
    echo "IMAGE=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
```

**Reply by tinohager** [reply]
These two variants are suitable for me


**Bash string to lowercase**
```
    - id: lower-repo
      name: Repository to lowercase
      run: |
        echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest

```

**with powershell - ToLowerInvariant()**
```
    - id: lower-repo
      name: Repository to lowercase
      shell: pwsh
      run: |
        "::set-output name=repository::$($env:GITHUB_REPOSITORY.ToLowerInvariant())"
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest

```
