### DISCUSSION TITLE
Passing/Using artifact installs (e.g. npm installs) between jobs

### DISCUSSION THREAD

**Discussion by someguynamedmatt** [community/community#106345] [npm]
### Select Topic Area

Question

### Body

In a workflow, is it possible to have one job be the env setup step, one job the install step, and then use those results (i.e. use the `node_modules` directory created from the `npm install` run in that job) in the successive job?

I've been toying around with this and it doesn't seem to work for me. If someone can point out a simple "no", or show me the missing step that'd be great! In my example (below) I get "cannot find node/npm" in the install step. As a workaround I've shoved the `setup` job and the `install` job together, but then any job after that complains of not being able to find dependencies.

What I've tried:

```yaml
name: Example

on:
  pull_request:
    branches:
      - dev

jobs:
  setup:
    name: Setup Env
    runs-on:
      - linux
    defaults:
      run:
        shell: bash
        working-directory: "."
    steps:
      # setup node, npm, etc
 
  install:
    name: Install Deps
    needs: setup
    steps:
      - name: Install
        run: |
          npm i

  build:
    name: Build Apps
    needs: install
    # This fails due to a seeming inability to resolve any npm dependency    
```
