### DISCUSSION TITLE
Is there a way to get the commit message header

### DISCUSSION THREAD

**Discussion by Th3S4mur41** [community/community#106392] [Actions]
### Select Topic Area

Question

### Body

The default [run-name](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name) for `push` or `pull_request` event, it is set as the commit message.

If I'd like to have the same info for `workflow_run` event, it seems logical to set `run-name` to `${{ github.event.workflow_run.head_commit.message }}`
However, in this case, it would use the entire commit message including body and footer.

It there a way to get only the commit message header for such use cases to have a run-name that is aligned with other events?

**Comment by ghost** [comment]
Hello Michaël.
To get only the commit message header (i.e., the first line of the commit message) in a GitHub Actions workflow, especially for a workflow_run event where you want to set the run name to match the commit message header used in push or pull_request events, you can utilize a combination of shell commands and GitHub Actions expressions.

GitHub Actions doesn't provide a direct method to extract just the header of a commit message, but you can use shell commands within a run step to achieve this. Here's a basic approach:

Use git to get the full commit message.
Extract the first line using shell utilities like head or awk.
Here's an example of how you could set up a step within your job to extract the commit message header and set it as an environment variable that you can use later in the workflow:
```
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message header
        id: get_commit_message
        run: |
          COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -n 1)
          echo "COMMIT_MESSAGE_HEADER=${COMMIT_MESSAGE_HEADER}" >> $GITHUB_ENV

      - name: Use commit message header
        run: |
          echo "The commit message header is: $COMMIT_MESSAGE_HEADER"
```
In this example:

The Checkout code step checks out the repository code so you can perform git operations.
The Get commit message header step uses git log -1 --pretty=%B to get the full commit message of the last commit, then pipes it to head -n 1 to get the first line. It then sets this as an environment variable COMMIT_MESSAGE_HEADER.
In the Use commit message header step, you can see how to use the COMMIT_MESSAGE_HEADER environment variable in subsequent steps.
This approach gets the commit message header of the latest commit. If you need the commit message header from the workflow_run event specifically, you might need to checkout the commit using the SHA from github.event.workflow_run.head_commit.id and then apply the same method to extract the header.
