### DISCUSSION TITLE
Daily scheduled workflow using an old commit

### DISCUSSION THREAD

**Discussion by anthonyStratis** [community/community#106371] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a daily scheduled workflow that is using the same commit each day even though there are newer commits. Also, the workflow has been changed in newer commits, including the schedule time (the changes are not being used). The workflow and commits are on the default branch.

I can see it's an old commit by the workflow history and in the logs (I have a job that outputs the current sha):
![image](https://github.com/community/community/assets/60459632/92fc9bb5-c4fc-46fa-874d-bdd11107e7ff)

`echo 'Current sha:    ${{ github.sha }}'`
outputs:
` Current sha:    0ffe7325d750bc68191c4638cb88df7c63407700`

What would cause this?

Here is an incomplete sample of the workflow:
```yaml
name: Nightly Build

on:
  schedule:  # schedule runs against last commit on default branch (master)
    - cron: '0 5 * * *'  # Daily at 05:00
  workflow_dispatch:  # Allows running manually from the Actions tab

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

...
```
