### DISCUSSION TITLE
No artifacts found when reusing a workflow

### DISCUSSION THREAD

**Discussion by lars-berger** [community/community#106325] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a separate workflow for building + releasing:
```yaml
# build.yaml
name: Build
on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            tauri-target: universal-apple-darwin
          - platform: windows-latest
            tauri-target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

     # various build steps...
      
      - uses: actions/upload-artifact@v3
        with:
          name: bundle-${{ matrix.tauri-target }}
          if-no-files-found: error
          path: tmp
```
```yaml
# release.yaml
name: Release
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yaml # calls build workflow

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4 # doesn't find any artifacts!
        with:
          path: tmp
```

From what I can tell this should be possible ([example](https://stackoverflow.com/a/70005652)). Perhaps the issue is that I'm using matrices in the reused workflow?

Is there some way to work around this? Maybe by outputting the job id's somehow to the release workflow, and then passing the `job-id` param to `actions/download-artifact`?

GH Actions run: https://github.com/glzr-io/zebar/actions/runs/7785119789/job/21227169214 (the project where I'm running into this issue)
