### DISCUSSION TITLE
Downloading artifact from different workflow

### DISCUSSION THREAD

**Discussion by adamjstewart** [community/community#106300] [Actions]
### Select Topic Area

Question

### Body

I have a `pull_request` [workflow](https://github.com/microsoft/torchgeo/blob/ef10eb14b649d21c03dd9601dbed4bcbde849560/.github/workflows/tests.yaml) that uploads code coverage as an artifact. I want to download that in a `workflow_run` [workflow](https://github.com/microsoft/torchgeo/blob/ef10eb14b649d21c03dd9601dbed4bcbde849560/.github/workflows/coverage.yaml), but I'm having trouble getting it working. So far I'm using:
```yaml
    - name: Download coverage artifacts
      uses: actions/download-artifact@v4.1.1
      with:
        run-id: ${{ github.event.workflow_run.id }}
```
According to [the docs](https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories), `download-artifact@v4` should support this. I believe `github.event.workflow_run.id` will be the run-id of the workflow that triggered the `workflow_run`, but I'm not sure. Do I need a `GH_PAT`? Where do I get one? If I create one for the upstream repo, will it be able to access artifacts generated by PRs from forks, or do I need a `GH_PAT` for every single fork? (obviously not possible)

P.S. I'm aware of the third-party [action-download-artifact](https://github.com/dawidd6/action-download-artifact) and will try that if I can't get the official [download-artifact](https://github.com/actions/download-artifact) working.

**Comment by ChristopherHX** [comment]
I have been hit by the same unexpected behavior, it didn't even logged a warning that a required input was not explicitly passed.

_github-token seem to be a flag in the code to use the rest api, which supports different run-id as source_

```yaml
    - name: Download coverage artifacts
      uses: actions/download-artifact@v4.1.1
      with:
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ github.token }}
```

Depending on your repo settings you might need to enshure that it has access to `actions` scope
e.g.
```yaml
permissions: read-all
```
```yaml
permissions:
  # ..... all other required perms, using this syntax removes all other permissions
  actions: read
```

I think that I just stopped at this point without actually trying to provide a token.

`workflow_run` is an elevated job, it can use secrets so prividing a secret is a non issue. However I don't think it is even required for workflows of the same repo / public workflow runs
