### DISCUSSION TITLE
Using GHA secret to clone private repositories using git config url

### DISCUSSION THREAD

**Discussion by fmessmer** [community/community#106406] [Actions]
### Select Topic Area

Question

### Body

I'm trying to setup a workflow where I try to clone a private repository.
I have configured a `secret` with proper permissions and scope - accessible within the GHA workflow via `${{ secrets.GITHUBPAT }}`

During one of the workflow steps, I want to clone (multiple) private git repositories.
The `url` of those repositories are specified in the form:
```
git@github.com:<organization>/<repository>.git
```

I now would like to use `git config --global --add url."https://....@github.com/".insteadOf"git@github.com:` command to replace the ssh url with a url that uses the toke/secret.
But somehow I cannot figure out the correct syntax/command.

Does anybody know the correct syntax?

Here is my workflow:
```
name: git test

on:
  workflow_dispatch:

jobs:
  git_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUBPAT }}

      - name: git config
        run: |
          git config --global --add url."https://${{ secrets.GITHUBPAT }}@github/".insteadOf "git@github:"

      - name: git clone
        run: |
          git clone git@github.com:<organization>/<repository>.git
```
