### DISCUSSION TITLE
253 when connect to an AWS role from a GitHub repository

### DISCUSSION THREAD

**Discussion by cristi2000b** [community/community#106412] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm trying to migrate a repository from AWS to GitHub using GitHub Actions. I have set up a basic workflow to connect to an AWS role from the GitHub repository. However, when the workflow runs, I encounter the following error:
Run aws sts get-caller-identity Unable to locate credentials.
You can configure credentials by running "aws configure". 
Error: Process completed with exit code 253.

Here's the workflow code I'm using:
name: Connect to an AWS role from a GitHub repository
on:
  push:
    branches:
      - int

env:
  AWS_REGION: "us-east-1"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

I have verified that the AWS credentials are correctly configured on my local machine. Any help or insights on resolving this issue would be greatly appreciated. Thank you!

**Comment by ghost** [comment, marked as answer]
Hi. You need to ensure that AWS credentials are provided to the GitHub Actions workflow. Even though your AWS credentials are configured on your local machine, GitHub Actions will not have access to them unless you explicitly provide these credentials in your workflow.

Please Store AWS Credentials as GitHub Secrets: The first step is to store your AWS credentials securely in your GitHub repository as secrets. You can do this by going to your repository settings, then to the "Secrets" section, and adding your AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as secrets.

Modify Your Workflow to Use the Secrets: Update your GitHub Actions workflow file to use these stored secrets. You can use the aws-actions/configure-aws-credentials action to automatically configure AWS credentials.

You can update your workflow like this:
```
name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches:
      - int

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
```
Ensure you've added your AWS credentials (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY) to your GitHub repository's secrets before running this workflow. This approach keeps your credentials secure and not exposed in your workflow file. If you're using an IAM role rather than IAM user credentials, you might need to adjust the workflow to assume the role. This can be done within the configure-aws-credentials action by specifying additional parameters like role-to-assume.
