### DISCUSSION TITLE
Trouble Connecting to LocalStack from GitHub CI |  Connect to 127.0.0.1:4566 [/127.0.0.1] failed: Connection refused

### DISCUSSION THREAD

**Discussion by SujithKrishnan31** [community/community#106595] [Actions]
### Select Topic Area

Hello,
		  
Has anybody noticed similar issue when  running 'localstack' application in a service container and access the application from the GitHub Actions host.  I'm trying to set up LocalStack within GitHub CI pipeline, but I'm encountering following error.

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 127.0.0.1:4566 [/127.0.0.1] failed: Connection refused (Connection refused): Unable to execute HTTP request: Connect to 127.0.0.1:4566 [/127.0.0.1] failed: Connection refused (Connection refused)
```

CI workflow
```
  tests:
    name: Run unit tests
    runs-on: enterprise-runner
    timeout-minutes: 10
    container:
      image: ...../airflow_testbed:latest
      env:
        TEST_MOCK_SERVICES_HOST: localstack
      volumes:
        - ${{ github.workspace }}:/airflow-utils/
    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3
        ports:
          - 4566:4566
          - 4571:4571
```

Basically I'm trying to run pytest for my airflow codebase and it works fine when running in locally.

Here I access the env value in test file

```
	TARGET_HOST = os.environ.get("TEST_MOCK_SERVICES_HOST", "localhost")
	host = f"http://{TARGET_HOST}:4566"
    mocker.patch.object(
        BaseHook,
        "get_connection",
        return_value=Connection(
            conn_id="s3_connection",
            host=host,
            extra='{"host": "' + host + '"}',
        ),
    )
```

Dont know why --network and --endpoint options are not supported here
