### DISCUSSION TITLE
Why is this step failing?

### DISCUSSION THREAD

**Discussion by Hyperhook** [community/community#106612] [Actions] [answered]
### Select Topic Area

Question

### Body

I have the following job:

```
linting:
    name: Check lint rules
    runs-on: [self-hosted]
    needs: build-container
    continue-on-error: true
    timeout-minutes: 3
    steps:
      - name: Check flake8 rules
        run: |
          FILES=$(gh pr diff ${{ github.head_ref }} --name-only | grep -i -o '.*\.py$')
          [ -n "$FILES" ] && make lint FILES_TO_LINT="$(echo ${FILES})" || echo "No python files to lint"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

The script works fine when there are Python files changed, but when there are none, it fails.

I've tried using an if/else block but it didn't work, I've tried returning a 0 exit code but the step still fails.

What am I missing?

**Comment by ghost** [comment]
Hello. The issue likely stems from the way the shell script handles the case when no Python files are found. In shell scripting, the last command executed in a script determines the exit status of the script. If the last command fails (i.e., exits with a non-zero status), the entire script is considered to have failed. In your script, when no Python files are found, the echo "No python files to lint" command runs. This command by itself should not cause the script to fail, as echo usually exits with a status of 0, indicating success. However, the way the script is structured with the logical OR (||) could be causing unexpected behavior, especially in the context of a GitHub Actions workflow.

**Comment by ghost** [comment]
After the echo "No python files to lint" command, explicitly add an exit 0 to ensure the script exits successfully when no files are found.
```
run: |
  FILES=$(gh pr diff ${{ github.head_ref }} --name-only | grep -i -o '.*\.py$')
  if [ -n "$FILES" ]; then
    make lint FILES_TO_LINT="$(echo ${FILES})"
  else
    echo "No python files to lint"
    exit 0
  fi
```

**Reply by Hyperhook** [reply]
Thank you for your replies, I'm afraid I've tried this before and it was still failing.

**Comment by ghost** [comment, marked as answer]
you can try this approach too. use GitHub Actions' conditional execution feature to only run the linting step when Python files are changed.
```
steps:
  - name: Check for Python files
    id: check_files
    run: |
      FILES=$(gh pr diff ${{ github.head_ref }} --name-only | grep -i -o '.*\.py$')
      echo "::set-output name=python_files::${FILES}"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  - name: Check flake8 rules
    if: steps.check_files.outputs.python_files != ''
    run: make lint FILES_TO_LINT="${{ steps.check_files.outputs.python_files }}"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
