### DISCUSSION TITLE
If condition doesn't work for job if either either of needs condition is skipped and below condition also requires always() to run

### DISCUSSION THREAD

**Discussion by jostar5** [community/community#106662] [Actions]
### Select Topic Area

Question

### Body

In the below yml job4 doesn't run even if job2 & job3 are successfull I have a similar scenario where I have to add always() with if condition in every next job to run 

```
name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
jobs:
  job1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Do something in job1
        run: echo "Doing something in job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Do something in job2
        run: echo "Doing something in job2"

  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    if: always() && (needs.job1.result == 'success' || needs.job2.result == 'success')
    steps:
      - name: Do something in job3
        run: echo "Doing something in job3"

  job4:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - name: Do something in job4
        run: echo "Doing something in job4"
        
        
      
```

**Comment by ghost** [comment]
you can try this variant:
```
name: ci
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  job1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Do something in job1
        run: echo "Doing something in job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Do something in job2
        run: echo "Doing something in job2"

  job3:
    needs: [job2]
    runs-on: ubuntu-latest
    if: success() || cancelled()
    steps:
      - name: Do something in job3
        run: echo "Doing something in job3"

  job4:
    needs: job3
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Do something in job4
        run: echo "Doing something in job4"
```
