### DISCUSSION TITLE
[Bug] Reusable workflow for pull requests giving parse error

### DISCUSSION THREAD

**Discussion by tarunwadhwa13** [community/community#10679] [Actions] [answered]
Reusable workflows when triggered are failing with this parse error

> The workflow is not valid. [my-org]/[my-repo]/.github/workflows/reusable_workflow.yml@[git-sha]: Expected document start parse event Unexpected type '' encountered while reading 'root'. The type 'MappingToken' was expected.

This issue is generally observed for pull_request based triggers.

Any help in this is seriously appreciated. We have been struggling to  update our workflows because of this

**Comment by Puneeth-n** [comment]
@tarunwadhwa13  may be something for [actions/runner](https://github.com/actions/runner)?

**Comment by dannyskoog** [comment]
I have experienced the same issue when I've used a **relative path** for calling my reusable workflow (i.e. `./.github/workflows/reusable_workflow.yml` in combination with the `pull_request_review` event. And the bug is most likely related to that the `pull_request` event uses a simulated merge commit as ref (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review). And as an example of that it works perfectly fine using a **relative path** in combination with the `issue_comment` event (which uses the HEAD commit from the default branch as ref).

For now I've gone with:
`[my-org]/[my-repo]/.github/workflows/reusable_workflow.yml@main`

**Reply by gadgadskiy** [reply]
unfortunately, the error reproduces sometimes with this fix as well

**Comment by dylanrandle** [comment]
I am also facing this problem. Is there any timeline for a fix?

**Comment by dylanrandle** [comment]
Others are facing this problem as well: https://github.community/t/ref-head-in-reusable-workflows/203690/64

**Comment by AivarasGluodas** [comment]
We are also facing this problem. Is input available from GitHub team?

**Comment by ViacheslavKudinov** [comment]
Same problem with `pull_request` , 
but is fine with `push`.

**Reply by mopsek** [reply]
Confirming, - the same here 😄

**Reply by shashanklmurthy** [reply]
I have this problem on `push` but my `pull_request` event is fine :/

**Comment by umid-podo** [comment]
I am also facing this problem.

**Comment by ethomson** [comment]
Hi everyone - thanks for reporting this, the engineering team is investigating.

**Reply by dianjuar** [reply]
Here you have an example with the error in case you need it
https://github.com/bikecoders/ngx-deploy-npm/actions/runs/1800250922

The simplified YML is

```yml
name: PR's
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-test:
    uses: ./.github/workflows/basic-test.yml
```

**Reply by tomgrossman** [reply]
@ethomson any update?

**Comment by constgen** [comment]
Have just decided to try reusable workflows for the first time in my life and they are unfortunately broken. Is it a regression or they never worked for PRs? Hope there will be automated tests to track the regression of this issue again whet it will be fixed.

**Comment by ralucaelenavasiliu** [comment]
We are facing the same issue on our pipelines on` pull_request`

**Comment by ajaykn** [comment, marked as answer]
Hi all, apologies for the inconvenience caused. We have rolled out the fix now.

We starting seeing this issue when workflows started referencing reusable workflows locally and this issue was coming for pull_request events.


Thanks for the patience and please let us know if you still face issues.

**Reply by dianjuar** [reply]
It's solved.
Now I can use that feature.

Thank you

**Reply by vincentchalamon** [reply]
Hi @ajaykn,

Thanks for the feedback. The original issue seems solved, but now I'm facing a new issue:
> Input push is required, but not provided while calling.

Here is a part of my original `foo.yml` workflow:
```yaml
name: Foo

on:
  issue_comment:
    types: [ created ]
  pull_request: ~

jobs:
  foo:
    uses: ./.github/workflows/bar.yml
    with:
      baz: bar
    secrets:
      secret-pat: ${{ secrets.SECRET_PAT }}
```

And the `bar.yml` file:
```yaml
name: Bar

on:
  workflow_call:
    inputs:
      baz:
        type: string
        description: 'Baz'
        required: true
    secrets: 
      secret-pat:
        description: 'A secret PAT'
        required: true

jobs:
    # ...
```

Did I miss something? Thanks for your answer

**Reply by ajaykn** [reply]
@vincentchalamon Thats strange to see the error `Input push is required, but not provided while calling.`

The reusable workflow bar.yml has the required input: `baz` defined and i can see you are passing while calling from foo.yml.

But as per the error its showing the error for input key `push`. Do you have any other workflow you are calling from your foo.yml ?

**Reply by vincentchalamon** [reply]
@ajaykn fixed, it was a typo on my side. Thanks for your help :-)

**Reply by alexbatashev** [reply]
@ajaykn FWIW, it seems, that local reusable workflows can't be cancelled. The 'cancel' button just has no effect, all jobs are executed till very end. Works fine if I use workflow by referencing it from main branch.

**Reply by niall-shaw** [reply]
@ajaykn - I am still experiencing this issue today.

Relevant part of continuous integration workflow file:
```
name: Continuous Integration

on:
  pull_request_review:
    types: [submitted]
  push:

concurrency:
  group: build

jobs:
  validate_test:
    name: Validate & Test
    uses: ./.github/workflows/validate-test.yml

  build_uat:
    if: ( github.event_name == 'pull_request_review' && github.event.review.state == 'approved' ) || github.ref == 'refs/heads/main'
    needs: validate_test
    name: Build UAT
    uses: ./.github/workflows/build.yml
```

Error:
```
[Invalid workflow file: .github/workflows/continuous-integration.yml#L14](...)
error parsing called workflow "./.github/workflows/validate-test.yml": workflow was not found.
```

**Reply by niall-shaw** [reply]
@ajaykn  - can you follow up on this please

**Reply by ajaykn** [reply]
@niall-shaw Apologies for inconvenience.
 local reference of workflow was supported before for Pull request event only
And we have released a fix to support for pull_request_review and pull_request_review_comment.

Can you please check once again and see if you are still facing the issue.
cc @yujincat

**Reply by kemalizing** [reply]
hi @ajaykn I have the same issue now with local reference. I want to deploy when we get an approval for the PR on staging environment. I also want to use the local workflow to see the real impact but getting the same error "Invalid workflow file...". Could you please help me?

**Comment by dannyskoog** [comment]
> Invalid workflow file: .github/workflows/dev.yaml#L14
error parsing called workflow "./.github/workflows/create-image-and-release-to-env.yaml@": workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.

I get the above error when trying to run a reusable workflow (using a **relative path**) triggered by the `pull_request_review` event. 

Here's the _relevant parts_ of the initiating workflow file (`dev.yaml`):

```yaml
name: Dev release
on:
  pull_request_review:
    types: [submitted, edited]
  issue_comment:
    types: [created, edited]

jobs:
  release:
    name: Create and release image
    uses: ./.github/workflows/create-image-and-release-to-env.yaml
```

Important to know is that there's **no error** when the reusable workflow is ran triggered by the `issue_comment` event (although I'm aware that `issue_comment` events have a ref of the default branch. But it doesn't change my point).

I have verified that the reusable workflow file is part of the PR branch that the event got triggered for, which should be enough since according to the docs  `pull_request_review` events should have a ref of `refs/pull/:prNumber/merge` (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review).

Could you please look into this @ajaykn? Thanks!

**Update:** I opened a separate ticket for this https://github.com/github/feedback/discussions/14306

**Reply by ajaykn** [reply]
@dannyskoog  Apologies for inconvenience.
local reference of workflow was supported before for Pull request event only
And we have released a fix to support for pull_request_review and pull_request_review_comment.

Can you please check once again and see if you are still facing the issue.

**Comment by christohbiorad** [comment]
I'm getting an error where it is requesting "required key: runs-on" for jobs that are calling re-usable workflows.

**Comment by DomVinyard** [comment]
I'm getting similar `Missing required key 'steps'`

**Comment by djthornton1212** [comment]
I receive:

> error parsing called workflow "./.github/workflows/identify-apps.yml": workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.

 when running a local reusable workflow w/ `pull_request_review_comment` as the event.

```yml
---
name: PR Notifications

on:
  pull_request: 
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main
  pull_request_review_comment:
    types:
      - created
      - edited

jobs:
  identity:
    uses: ./.github/workflows/identify-apps.yml
```

**Note that this works just fine on a `pull_request` event.

**Reply by djthornton1212** [reply]
Response from GitHub Support:

> Thank you for writing to GitHub Enterprise Support.
> 
> Apologies for the trouble here.
> 
> I am able to reproduce this. I have opened an issue for Engineering to investigate further. I'll let you know as soon as I have an update from them.
> 
> As a workaround at the moment, you could refer to the reusable workflow with the {owner}/{repo}/.github/workflows/{filename}@{ref} syntax to unblock you.

I can confirm that this workaround did indeed work for me.

**Reply by ajaykn** [reply]
@djthornton1212   Apologies for inconvenience.
local reference of workflow was supported before for Pull request event only
And we have released a fix to support for pull_request_review and pull_request_review_comment.

Can you please check once again and see if you are still facing the issue.

**Reply by djthornton1212** [reply]
@ajaykn Adding it to my todo list.

**Comment by gbetous-swir** [comment]
Same issue again.

It happens only when using the "local" syntax `uses: ./.github/workflows/xxx.yml`

**Reply by mortenkjelling** [reply]
Had a brief hickup today with the same issue here as well.
Some workflow runs failed with
```
Invalid workflow file: .github/workflows/ci.yml#L63
                      
error parsing called workflow "./.github/workflows/build-standard-app.yml": error in fetching the workflow file
```

I closed the PR and opened a new from the same branch, it worked.

We run it with:
```
on:
  pull_request:
    types: [opened, synchronize]
```

**Comment by jim5252** [comment]
This is also happening again to us again on a push to the main branch:

```
name: Terraform CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    uses: ./.github/workflows/template-terraform.yml
```

`error parsing called workflow "./.github/workflows/template-terraform.yml": error in fetching the workflow file`

**Comment by vladimir-carpa** [comment]
We are issuing the same problem right now 

```yaml
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]
    
deploy:
  needs: ["test", "build", "check_deploy"]
  if: "${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}"
  uses: "{organization}/{repo}/.github/workflows/cd.yml@master"
  with:
    stage: "guess_from_github_ref"
```

**Comment by ThomasMarcelo** [comment]
I've been getting the `error parsing called workflow` repeatedly for 2 days now. It comes and goes.
I'm referencing a local workflow (private repo) with the `uses: ./.github/workflows/myresusable.yml` reference.

Is this a known bug? And it is random as well... Retriggering the workflow run sometimes fixes it.

Using the `public` way of referencing the workflow does not work for me because I need to use the workflow from the commit, not a fixed branch or SHA. The `use` parameter doesn't seem to accept variables, making it impossible to do what I need.

**Comment by lascufa** [comment]
Hi there!

We experience this issue also since about 2 days now. Something must have changed regarding reusable workflows.
`error parsing called workflow "xyz.yml": error in fetching the workflow file`

When the main workflow uses reusable workflows, we receive the error message randomly for some workflow runs (and in it randomly for some reusable workflow linkages).

**Comment by djthornton1212** [comment]
Hello Community,

For those who have been experiencing this issue the last two days, here's the reply I received from GitHub Enterprise Support:

> Thank you for contacting GitHub Enterprise Support.
> 
> It appears this was due to an internal issue with Actions Checkout. We have since resolved the Checkout issue and I can see that a few other users confirmed this is working for them again per https://github.com/orgs/community/discussions/40839. Can you confirm you are no longer experiencing this issue?
> 
> Best regards,

**Reply by ThomasMarcelo** [reply]
I couldn't find anyone saying it is working again for them there... 🤷🏽‍♂️

**Reply by djthornton1212** [reply]
Follow up response from GitHub Support:

> This issue should now be mitigated. You may have seen this issue occur again this morning while we were still investigating. This looks to have been due to a secondary rate limit being hit. We have patched this and have resolved the issue, we can see the API endpoint is healthy at this point. Is this functioning as intended at this time?

**Reply by djthornton1212** [reply]
Yeah, I can't say that I'm still seeing the issue. My developers appear to be functioning normal since 10a CT yesterday.

**Comment by gbetous-swir** [comment]
And now : 

```
Invalid workflow file: .github/workflows/main.yml#L43
error parsing called workflow "xxx/yyy/.github/workflows/letp.yml@master": error in fetching the workflow file

```

**Comment by gadgadskiy** [comment]
Hi guys! I have a similar error on the pull request opened event.
My reusable workflow:
```
name: Composite Actions Flow
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  add-comment:
    if: ${{github.event.action == 'opened' && github.base_ref == 'develop'}}
    runs-on: self-hosted
    name: Add initial comment
    steps:
      - uses: actions/github-script@v6
        env:
          . . . . . . .
        with:
          script: |
            . . . . . . .
```
And integration in the repository:
```
name: Action integration

on:
  pull_request:
    types: [ opened ]
    branches:
      - develop

jobs:
  action-integration:
    name: Open PR event Event
    uses: [my_org]/[repo_with_workflows]/.github/workflows/reusable-workflow.yaml@master
    secrets:
      token: ${{ . . . }}
```
In most cases, it runs successfully, but from time to time, it fails with an error:
```
[Invalid workflow file: .github/workflows/my-action-integration.yml#L12](https://github.com/[my_org]/[repo_with_integration]/actions/runs/3622295031/workflow)
error parsing called workflow "[my_org]/[repo_with_workflows]/.github/workflows/reusable-workflow.yaml@master": error in fetching the workflow file
```
It fails in 1 case in 10 that's pretty annoying for users. I can't see ways to add retries on our side, so I'm asking for help to look at these errors from your side.

**Comment by mmospanenko** [comment]
Got the same issue with on `workflow_call`, but why it should be related to event/trigger - it is static analysis issue.

**Comment by eneskilinch** [comment]
actual response:
`{
  "configs": [
    "dispatch"
  ],
  "versions": []
}
`

parsing response error in actions:
`Error: google-github-actions/deploy-appengine failed with: failed to parse deploy response: missing or empty "versions", stdout: ***`

**Reply by spicybackend** [reply]
Turns out this is a regression in the [`deploy-appengine` action](https://github.com/google-github-actions/deploy-appengine) in regards to cron job deployments @eneskilinch. You can workaround this for now by specifying the last good version, `v1.0.0`.

```yaml
      - id: 'deploy-cron-config'
        uses: 'google-github-actions/deploy-appengine@v1.0.0'
        with:
          deliverables: cron.yaml
```
