### DISCUSSION TITLE
Using an org var to populate choice input's options

### DISCUSSION THREAD

**Discussion by ghost** [community/community#106810] [Actions]
### Select Topic Area

Question

### Body

I'm trying to use an org-wide variable in various github actions throughout the organization, to populate the options of a workflow_dispatch's choice input.

My variable:
<img width="428" alt="image" src="https://github.com/community/community/assets/13627666/fd25824f-51f9-4066-bd90-e8737d15f43d">

My action:
```yaml
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: choice
        description: "The environment of the deployment"
        options: ${{ fromJSON(vars.ENV_LIST) }}
```

This doesn't work -- when I try to set the branch in the workflow_dispatch GUI to one with this code, it immediately snaps back to the main branch. When I try to run it with `gh workflow run`, it fails with a 500.

How can I use an org variable to populate the options in a choice input?
