### DISCUSSION TITLE
Issue when trying to use dynamic credentials in job.<job-id>.container.credentials

### DISCUSSION THREAD

**Discussion by cschadewitz** [community/community#106845] [Actions] [answered]
### Select Topic Area

Question

### Body

Hey all,

I am having issues using dynamic credentials for my registry when trying to run my job on a container. From my understanding, the credentials should allow for values from an expression. [Docs example here](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#example-defining-credentials-for-a-container-registry)

And job.<job-id>.container.credentials should have access to the needs context.
<img width="386" alt="image" src="https://github.com/community/community/assets/7377200/e341bfaf-2604-449f-9ba8-0913ab092d67">

However, the result is:
`Error: The template is not valid. cschadewitz/workflow-testing/.github/workflows/acr_test.yml@41fe308f2092edb21c978b2b85dbbb56ae74b3ce (Line: 65, Col: 19): Unexpected value ''`

Am I missing something here?

Full Script below:
```
name: KVACRTest

on: 
  workflow_call:
    inputs: 
      kv_name: 
        description: 'Key Vault'
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  login:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      ACR_USERNAME: ${{ steps.get_acr.outputs.ACR_USERNAME }}
      ACR_PASSWORD: ${{ steps.get_acr.outputs.ACR_PASSWORD }}
    steps:
      - name: Login to az cli
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Get ACR
        id: get_acr
        run: |
          echo "ACR_USERNAME=$(az keyvault secret show --vault-name ${{ inputs.kv_name }} --name GithubToAzureUsername --query value -o tsv)" >> $GITHUB_OUTPUT
          echo "ACR_PASSWORD=$(az keyvault secret show --vault-name ${{ inputs.kv_name }} --name GithubToAzurePassword --query value -o tsv)" >> $GITHUB_OUTPUT
      - name: test username
        run: echo ${{ steps.get_acr.outputs.ACR_USERNAME }}

  testusernamejob:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Test
        run: |
          echo ${{ needs.login.outputs.ACR_USERNAME }} #successfully prints here
  

  test:
    runs-on: ubuntu-latest
    needs: login
    container:
      image: githubtoacr.azurecr.io/ubuntu:latest
      credentials:
        username: ${{ needs.login.outputs.ACR_USERNAME }}
        password: ${{ needs.login.outputs.ACR_PASSWORD }}
    steps:
      - name: Test
        run: |
          echo "Hello World"
          
```
