### DISCUSSION TITLE
JEKYLL FAILING TO BUILD MY SITE

### DISCUSSION THREAD

**Discussion by therealsimon14** [community/community#106846] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hey all!

I'm trying to deploy a blog website I made using hexo on GitHub pages. It is working, but images aren't loading and i'm getting the following error when GitHub actions tries to build my site:

`Error:  Logging at level: debug Configuration file: /github/workspace/./_config.yml Theme: redefine github-pages 228 | Error: The redefine theme could not be found`

![image](https://github.com/community/community/assets/97934952/56327bb5-fc35-4f5e-b327-9384535c991b)

Here is my pages.yml file:

```
name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

![image](https://github.com/community/community/assets/97934952/909e04fb-ad44-4980-a418-31d0225eb20b)

Any help?

Simon
