### DISCUSSION TITLE
Add trigger for expressing "on pull request merged"

### DISCUSSION THREAD

**Discussion by thclark** [community/community#10699] [Actions] [answered]
I have an action that executes on a pull request into `main`, with the condition that the action only triggers *when the pull request is merged*.

This currently needs to be assembled as follows:
```yml
name: Do something on merge into main

# Trigger when a pull request into main branch is closed, which can happen either on merge or manual close...
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  thejob:
    if: "github.event.pull_request.merged == true"
    runs-on: ubuntu-latest
    steps:
      - run: echo "This will only show if the PR has been merged (and not if it was closed without merging)."
```

This gets ugly when combining with other if statements. It'd be great to have an additional trigger criterion so we could do:

```yml
on:
  pull_request:
    types: [merged]
    branches:
      - main

jobs:
  thejob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This will only show if the PR has been merged (and not if it was closed without merging)."
```

Any thoughts?
