### DISCUSSION TITLE
Action step logs incomplete

### DISCUSSION THREAD

**Discussion by plocket** [community/community#107531] [Actions]
### Select Topic Area

Question

### Body

The action I made has lots of logs. Just now, I saw that the next step is run before my logs finish and before the logs of the library I'm using (cucumber) are finished. They get cut off in the middle. I assume it's a race condition, some problem with asynchronous code. How can I find where this is happening?

[Example of working logs](https://github.com/SuffolkLITLab/ALKiln/actions/runs/7859500774/job/21445646984#step:7:2349):

![logs_complete](https://github.com/community/community/assets/52798256/c898353d-052b-4f6a-9b53-bc07da88f062)

Note: This action deliberately doesn't run the `takedown` step.

[Example of incomplete logs](https://github.com/SuffolkLITLab/ALKiln/actions/runs/7859500549/job/21446028392#step:3:2267):

![logs_incomplete](https://github.com/community/community/assets/52798256/dc7fd26f-461a-4689-a979-e1cd1e0f3068)

My action code at that point in the script look like this:

```yml
    # run tests and log results
    - name: "ALKiln info: Run tests"
      if: ${{ success() }}
      env:
        ALKILN_TAG_EXPRESSION: ${{ inputs.ALKILN_TAG_EXPRESSION || github.event.inputs.tags && format('{0}', github.event.inputs.tags) }}
      run: alkiln-run $ALKILN_TAG_EXPRESSION
      shell: bash
    
    # sometimes run takedown
    - name: "ALKiln info: Try to delete the project from the playground of the docassemble test account."
      if: ${{ always() && inputs.INSTALL_METHOD == 'playground' }}
      run: alkiln-takedown
      shell: bash
    
    # Upload artifacts that subscribers can download on the Actions summary page
    - name: "ALKiln info: Upload artifacts folder"
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./alkiln-*
```
