### DISCUSSION TITLE
How can callable workflows in a dedicate repo use it's local actions with relative paths?

### DISCUSSION THREAD

**Discussion by axel-h** [community/community#107558] [Actions]
### Select Topic Area

Question

### Body

We have one repo "A" with source code and workflows. These workflows use callable workflows from another repo "B", where we collect the github CI scripts. Now, when a workflow in A calls a callable workflow in B, this one seems run in the context of the caller repo A. Thus, any "local" action it wants to invoke is searched in the caller's workspace. This is quite unfortunately, because in any callable workflow in B, the job steps have to use `<myOrg>/B/path/to/action@master` explicitly. Using just `./path/to/action` does not work, as this would look in A for the action. This becomes even more of a problem when we have forks of the repo B where users can test things. They have to change every reference now manually.

**Comment by ghost** [comment]
Hello. When you use a callable workflow in one repository (repo "A") that references another repository (repo "B"), the context in which the actions are executed defaults to the caller repository's context (in this case, repo "A"). This means that any relative paths used in the called workflow from repo "B" will be resolved relative to repo "A", leading to the problem you're facing.

**Reply by axel-h** [reply]
Yes, I do understand what is happening and this is well documented also. The intention of raising this here is trying to find a way how to use relative paths within repo. Basically, I'm raising a feature request.

**Comment by ghost** [comment]
You can use full repository paths. One workaround is to explicitly reference the full repository path for each action in repo "B". This ensures that GitHub Actions knows where to find the actions, regardless of the calling repository. Or You could consider using Git submodules to include repo "B" (where your GitHub CI scripts are located) as a submodule within repo "A" (where your source code and workflows reside). This way, you can reference the actions in repo "B" using paths relative to the submodule directory in repo "A". This approach keeps your references cleaner.

**Reply by axel-h** [reply]
That might work. However, using submodule usually has pros and cons already. Using submodules for this CI use case alone is overkill then, as this raises more issues than it solves.

**Comment by axel-h** [comment]
One way to solve this would be having for a `workflow_call` entry something in the `github` context  like: 
```
"workflow_call": { 
  "repo" = "<myOrg>/B",
  "branch": "master" 
  "name": "myCallableWorkflow"     // can be used then, because github.workflow gives the caller's name
}
```
so we could use `uses: ${{ github.workflow_call.repo }}/path/to/action@${{ github.workflow_call.branch }}` to have a local reference.

**Comment by axel-h** [comment]
So actually, as a work around the caller could do this. 
```
    uses: someOrg/B/.github/workflows/myCallableWorkflow@master
    with:
      workflow_call_repo: "someOrg/B"
      workflow_call_branch: "master" 
```

This is also not nice, but at least this would allows thing in repo B to be writte in a generic way then.

**Comment by ghost** [comment]
When you invoke the callable workflow in repo "B", you explicitly pass the repository and branch information as inputs. This makes the calling workflow slightly more verbose but adds the flexibility you need.
```
jobs:
  call-workflow-in-b:
    uses: someOrg/B/.github/workflows/myCallableWorkflow@master
    with:
      workflow_call_repo: "someOrg/B"
      workflow_call_branch: "master"

```

**Comment by ghost** [comment]
In the Callable Workflow (Repo B) you can do something like this:
```
on:
  workflow_call:
    inputs:
      workflow_call_repo:
        required: true
        type: string
      workflow_call_branch:
        required: true
        type: string

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use an action in the same repo
        uses: ${{ inputs.workflow_call_repo }}/.github/actions/some-action@${{ inputs.workflow_call_branch }}

```
