### DISCUSSION TITLE
github.event does not exist in called workflow for concurrency group naming?

### DISCUSSION THREAD

**Discussion by axel-h** [community/community#107552] [Actions]
### Select Topic Area

Bug

### Body

I have a callable workflow, where I use this to avoid concurrency 
```
name: myCallableWorkflow

on:
  workflow_call:    # to be called for pushes in pull requests

concurrency:
  group: ${{ github.workflow }}-myCallableWorkflow-pr-${{ github.event.number }}
```
I can see that a newer run kills the older one. But the concurrency group name is shown as `callerWorkflowName-myCallableWorkflow-pr-`, so it looks like `github.event.number` is empty. It seems the whole `github.event` does not exist here, as e.g. `github.event.action` is also an empty string. All I can see that `github.event_name` is `pull_request`. 
When I add jobs in this workflow, then `github.event` works there as expected.

**Comment by axel-h** [comment]
Is this similar to what https://github.com/orgs/community/discussions/13496 ran into? So the value of concurrency group is evaluated on the GitHub Actions server, not on the runner. However, the `github.event` context is set by the runner?

**Comment by nwiltsie** [comment]
I'm experiencing the same issue. One odd detail is that using `github.event` in a workflow-level concurrency block does work in the _calling_ workflow.

### Works As Expected
Caller:
```yaml
---
name: Trigger tests
on:
  issue_comment:
    types: [created]

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.event.issue.number }}

jobs:
  check-user:
    uses: ... (workflow in another repository)
```

Callee:
```yaml
name: Test Setup

on:
  workflow_call:

jobs:
  configure:
    runs-on: ubuntu-latest
    ...
```

### Does Not Work (`github.event.issue.number` is blank)
Caller:
```yaml
---
name: Trigger tests
on:
  issue_comment:
    types: [created]

jobs:
  check-user:
    uses: ... (workflow in another repository)
```

Callee:
```yaml
name: Test Setup

on:
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.event.issue.number }}

jobs:
  configure:
    runs-on: ubuntu-latest
    ...
```
