### DISCUSSION TITLE
Github Workflows + required status checks blocking PRs from merging

### DISCUSSION THREAD

**Discussion by harshtrivedi134** [community/community#108157] [Actions]
### Select Topic Area

Question: Is there something that we could do with concurrency here? I am getting confused by the fact that required checks are being considered separately for each workflow run/instance. 

### Body

Hello Team 👋  
I have a Github workflow verifying approval from a specific group for PRs containing changes to a specific file path. There are two jobs in this workflow and both of them are enforced as required checks to pass before merging in the branch protection rules of my repo. I am not using a `paths` filter. 

```
name: Verify Approval 
on: [workflow_dispatch, pull_request, pull_request_review]

jobs:
    check-file-changes:
        runs-on: ubuntu-20.04
        concurrency: 
            group: ci-${{ github.head_ref }}-${{ github.event.pull_request.number }}-${{ github.workflow }}
        steps:
            # detects file changes

    require-approval:
        runs-on: ubuntu-20.04
        group: ci-${{ github.head_ref }}-${{ github.event.pull_request.number }}-${{ github.workflow }}
        steps:
            # logic to check approval
```

There is an issue when the jobs are triggered for the `pull_request` event followed by the `pull_request_review` event. There is no approval when the workflow run is triggered by the `pull_request` event. However, the subsequent run is successful because somebody approved the PR. Since this is a required check, Github is probably considering the failed workflow run triggered due to the `pull_request` event as a blocker and does not allow merging the PR.
