### DISCUSSION TITLE
How to mask a secret when xtrace is used

### DISCUSSION THREAD

**Discussion by electriquo** [community/community#108129] [Actions]
### Select Topic Area

Question

### Body

How can I mask sensitive data when bash trace flag (-x) is used?

For example, the workflow below reveals `the_secret` because `set -x` is used, which outputs every bash command to the screen

```yaml
on:
  pull_request:
jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - name: Generate, mask, and output a secret
        run: |
          set -x
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret"
```

And in the output below, you can see the value of `the_secret` variable.

```shell
Run set -x
  set -x
  the_secret=$((RANDOM))
  echo "::add-mask::$the_secret"
  echo "secret-number=$the_secret"
  shell: /usr/bin/bash -e {0}
+ the_secret=28879
+ echo ::add-mask::28879
+ echo secret-number=28879
secret-number=***
```
