### DISCUSSION TITLE
Environments variables not working

### DISCUSSION THREAD

**Discussion by antoineCegepRDL** [community/community#108103] [Actions]
### Select Topic Area

Bug

### Body

Not sure if it is a bug, but I'trying to work with environments variables in my project to setup a properly dev, qa, prod env.

Here is my .yml code :
```
name: Build & Deploy
on:
   push
env:
  env_vars: ${{ vars.TEST  }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debugtest
        env:
          REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
          ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
          OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}
        run: |
          echo "repository variable : $REPOSITORY_VAR"
          echo "organization variable : $ORGANIZATION_VAR"
          echo "overridden variable : $OVERRIDE_VAR"
          echo "variable from shell environment : $env_var"
```
And this is the result

![image](https://github.com/community/community/assets/127795114/d6daf3e8-c583-44bf-9e8e-498cc466bab2)

Here is also a screen shot of where I put my variables.

![image](https://github.com/community/community/assets/127795114/25d748c5-c81a-44f2-87d5-f75348852264)

So my question is : How do I link the values from this page : `https://github.com/*****/******/settings/environments/*****0/edit` to my github actions!

I also have the same issue with the secrets, but this should be resolved once I solved my vars problem right?

If this is not a bug, I would love to have a link to the documentation with screen shots and all :).

Thx!
