### DISCUSSION TITLE
agent-adapters - waiting for chatAgents2 proposal

### DISCUSSION THREAD

**Discussion by nalbion** [community/community#108138] [Copilot Conversations]
### Select Topic Area

Show & Tell

### Body

Do you have any idea if/when the chatAgents2 proposal is going to be released?

I've made some cool stuff with it using https://github.com/nalbion/agent-adapters

In a few lines of YAML, you can add a remote agent into 

```yaml
  - name: AutoGPT
    description: The power of AI accessible to everyone
    icon: https://avatars.githubusercontent.com/u/130738209?s=32
    vscode: true
    remote:
      base_url: http://localhost:8000
```
![image](https://github.com/community/community/assets/1866161/d39e2d7a-5557-4dfe-8780-646e9f9b88ad)

With a few more lines of YAML you can pull an agent from a git repo and spawn it as a subprocess.

```yaml
  - name: evo_ninja
    description: Research, analyse and build software
    icon: https://evo.ninja/favicon.ico
    vscode: true
    git:
      repo: https://github.com/polywrap/evo.ninja
      branch: dev
      baseDir: ~/.agents/evo.ninja
    cli:
      command: cmd.exe
      args: ["/K", "yarn", "start"]
      cwd: ~/.agents/evo.ninja
      wait_for: "Enter another goal: "
```
![image](https://github.com/community/community/assets/1866161/aecb7f83-d5ec-4ec5-84df-37410e59fc1b)
