### DISCUSSION TITLE
Facing problem while using Create or Update Comment action

### DISCUSSION THREAD

**Discussion by Krrish777** [community/community#108298] [Actions]
### Select Topic Area

General

### Body

![image](https://github.com/community/community/assets/49588410/7d7cb872-77da-46fd-bfa5-1e258cf973dd)
**here is the error that I am facing**
```
name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Add reactions
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          reactions: |
            heart
            hooray
            laugh
```
Here is the code there is no indentation error
