### DISCUSSION TITLE
Dependabot errors when npmAlwaysAuth is true

### DISCUSSION THREAD

**Discussion by apgrucza** [community/community#108240] [npm]
### Select Topic Area

Bug

### Body

I have `dependabot.yml` and `.yarnrc.yml` configured to use a private npm registry, but the Dependabot update jobs all fail with errors such as this:

```
updater | 2024/02/13 23:29:52 ERROR <job_786741409> Error processing webpack (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2024/02/13 23:29:52 ERROR <job_786741409> ➤ YN0000: ┌ Resolution step
updater | ➤ YN0033: │ webpack@npm:^5.90.1: No authentication configured for request
updater | ➤ YN0000: └ Completed
updater | ➤ YN0000: Failed with errors in 0s 182ms
```

dependabot.yml:

```yaml
version: 2
registries:
  npm-artifactory:
    type: npm-registry
    url: https://[redacted]
    token: ${{secrets.MY_ARTIFACTORY_ACCESS_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/src/tv"
    registries:
      - npm-artifactory
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
```

.yarnrc.yml:

```yaml
npmRegistryServer: "https://[redacted]"
npmAlwaysAuth: true
npmAuthToken: "${ARTIFACTORY_ACCESS_TOKEN:-}"
```

The errors seem to go away when I change `npmAlwaysAuth` to `false`, but I cannot do that because then when I run `yarn` in my local environment (which has `ARTIFACTORY_ACCESS_TOKEN` set), it doesn't authenticate with my private registry. So I need Dependabot to work when `npmAlwaysAuth` is `true`.
