### DISCUSSION TITLE
GHA-Permission issue for for .Net self hosted runners

### DISCUSSION THREAD

**Discussion by manilkumar-wk** [community/community#108224] [Actions]
### GHA-Permission issue for for .Net self hosted runners

Bug

### Body

Facing permission issues when setting up dotnet and specifying a DOTNET_INSTALL_DIR variable, the installation is successful. But the next step of dotnet restore failed because of a permission issue.
```
env:
      DOTNET_INSTALL_DIR: ./.dotnet
```
**Initial dotnet setup Error:**
_Run actions/setup-dotnet@v1.7.2
/runner/_work/_actions/actions/setup-dotnet/v1.7.2/externals/install-dotnet.sh --version 6.0.419
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.419/dotnet-sdk-6.0.419-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.419/dotnet-sdk-6.0.419-linux-x64.tar.gz
cp: cannot create directory '/home/runner/.dotnet/host/fxr/6.0.27/': Permission denied
Error: The process '/runner/_work/_actions/actions/setup-dotnet/v1.7.2/externals/install-dotnet.sh' failed with exit code 1_

_**Dotnet restore error after setting DOTNET_INSTALL_DIR:**
Run dotnet restore

_System.UnauthorizedAccessException: Access to the path '/home/runner/.dotnet/6.0.419.toolpath.sentinel' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.CreateIfNotExists(IFileSystem fileSystem, String filePath)
   at Microsoft.DotNet.Configurer.FileSentinel.Create()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Error: Process completed with exit code 1._

```
name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    # Our previously created self-hosted runner
    runs-on: [self-hosted, small, al2023]
    strategy:
      matrix:
        dotnet: ["6.0.x"]
    # A sequence of tasks that will execute as part of the job
    steps:
      - name: Setup Credentials
        uses: gha-setup-credentials@v1.0.28
      # Checks out repository so our job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0'
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
```
