### DISCUSSION TITLE
More flexible triggers in Github Actions

### DISCUSSION THREAD

**Discussion by norman-zon** [community/community#108268] [Actions]
### Select Topic Area

Question

### Body

Hello,

I have a request regarding triggers in Github Actions.

Often I find the triggers to be not flexible enough.

One scenario we often encounter is PRs being opened by automation tools as drafts, which should not trigger CI runs until they are "Ready for Review".
As far as I understand only the transitional states `converted_to_draft` and `ready_for_review` are possible triggers, but not the condition "PR is a draft PR".
So every PR `synced` event triggers a workflow run, in which I then can check for `if: github.event.pull_request.draft == 'false'` and stop the run. But to get this far a runner has to be used. Is there no other way to achieve this before starting the workflow? Something like a logical `AND` for triggers along the lines of `synchronize && ready_for_review`?

Another scenario is running workflows on certain branches only. When setting things up like this:

```
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
      - '!renovate/**'
 ```

and push a commit to a branch `renovate/TEST` the `pull_request` trigger still fires because I can't restrict it to a source branch. Why is there only an option to restrict the TARGET branch for `pull_request`? Which is very confusing, being named the same as for `push `where it is the other way around btw.

And the last scenario we have issues with is restriction triggers by author. Why is there no such trigger setting as:

```
on:
  push:
    author-exclude:
      - machine1@zyx.com
      - machine2@zyx.com
```

to exclude some authors, machine accounts in our use case, from triggering workflows? The information is there in the moment the push happens. Again I would have to spin up a runner and do the check inside the workflow instead of beforehand.

I'm eager to understand the design decisions and hear your thoughts and maybe get ideas on how to circumvent these issues.

Best regards,

Norman
