### DISCUSSION TITLE
A shortcut to accept only the first line of code.

### DISCUSSION THREAD

**Discussion by ContraHacker** [community/community#10831] [Copilot Conversations]
Greetings.

I often find that I'd like to accept only the first line of code which has been suggested by Copilot. For example:

```scss
// I have already written the .description class. Copilot will use this for context.

p.description {
    color: blue;
    font-size: small;
    font-weight: 500;
    text-align: center;
}

// Now I'm writing new code here.

p.coloredText {
// Let this line be called line n
}
```

On line `n` I'll get the following suggestion from copilot.

```scss
    color: blue;
    font-size: small;
    font-weight: 500;
    text-align: center;
```

I only require `color: blue;`, however, pressing `TAB` will accept all four lines for me. I would be nice if we had a feature to only accept the first line. This sort of scenario appears occasionally, (for me at least) especially when writing CSS code.

Absolutely loving copilot till now. Looking forward to its future!
