### DISCUSSION TITLE
Checkout and access file other repository to set variables in git actions

### DISCUSSION THREAD

**Discussion by smartaquarius10** [community/community#108317] [Actions]
### Select Topic Area

Question

### Body

We are migration the azure devops pipelines to Github action. In ADO, we have defined this code at the top of pipeline to pull resources from other repository to set variables 

```
resources:
  repositories:
  - repository: mytemplates 
    type: github
    endpoint: Org_Name
    name: Org_Name/Repository_Name
    ref: master

variables:
- template: variables.yaml@mytemplates 
```
To access the variables we specify like this `${{ variables.Name }}`

Do we have any alternative of it in Github actions. We have a file in other repository where we maintain all the variables which can be used across pipeline

Regards,
Tanul
