### DISCUSSION TITLE
Can a workflow be triggered on success of an external check?

### DISCUSSION THREAD

**Discussion by WTPascoe** [community/community#108478] [Actions]
### Select Topic Area

Question

### Body

We use Google Cloud Build triggers to build and tag images on various github events (pr, push to main, tag, etc.)

Is there a way to trigger a workflow on completion of the google cloud build step? These show up in the `checks` section of a PR.

I tried using repository_dispatch (with my workflow on `main`) but it doesn't run when gcloud builds complete. My sample workflow file is below.

```
name: External Dep Testing

on:
  repository_dispatch:
    types: [all]

jobs:
  dump_external_info:
    name: Dump external info
    runs-on: ubuntu-latest
    steps:
      - name: Show event data
        run: echo "Event content"
```
