### DISCUSSION TITLE
Can `if` guard be added to `on.<event>`?

### DISCUSSION THREAD

**Discussion by rhysd** [community/community#108504] [Actions]
### Select Topic Area

Question

### Body

Hi, I'm the author of [actionlint](https://github.com/rhysd/actionlint) tool. I'd like to ask the specification of GitHub Actions workflow syntax.

I got [a PR](https://github.com/rhysd/actionlint/pull/357) that said `if` guard can be added to `on.<event>` section like below. However, I and the PR author could not find any official documentation about it.

```yaml
on:
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
```

I have two questions:

1. Is `on.<event>.if` officially supported?
2. If it is, what contexts are available in the `${{ }}` expression in the `if` condition?
