### DISCUSSION TITLE
Problem: Grades not visible, while autograding CI passes fine and release grades

### DISCUSSION THREAD

**Discussion by agilebotanist** [community/community#108906] [GitHub Education]
### Hi everyone,

Dear experts,

We have a very simple assignment in python. The Autograding CI passes well. But the grades are not visible in the Classroom. We tried various combinations and simplifications of classroom.yaml and autograding.json. Nothing helps. Any clues?
Also, it appears that all worked fine couple of weeks ago, when we tested.
![image](https://github.com/community/community/assets/2123188/8e2d119d-9075-451d-95e9-0522e6d2265e)
![image](https://github.com/community/community/assets/2123188/a6fb8985-2f09-4559-bf92-e58fa1102f1c)

But the grades are not visible in Classroom.
![image](https://github.com/community/community/assets/2123188/e1ace4a4-5ce4-4452-95f0-d1f5dc6c1e58)

Could you help please?

Thanks
PS
[Sandbox student's project.](https://github.com/QualityInUse/sand-lab02-agilebotanist)
Scripts.

```YAML
name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    permissions: write-all
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: education/autograding@v1
```

```JSON
{
    "tests": [
      {
        "name": "Tests pass",
        "setup": "sudo add-apt-repository ppa:deadsnakes/ppa ; sudo apt install python3.12 ; sudo -H pip3 install poetry ; poetry install; poetry add pytest",
        "run": "poetry run pytest .",
        "input": "",
        "output": "",
        "comparison": "exact",
        "timeout": 10,
        "points": 1
      }
    ]
  }
```

**Comment by agilebotanist** [comment]
I have tried this workaround. 

There method with `markpatterson27/autograding@dev-points-input-release` by @markpatterson27

Classroom updates as needed when sent with the numbers for grades. I hoped to use this as a workaround by combining with the official Autograding. Since currently my Classroom does not update grades labels :/

Here is my code to debug and pass the grades to the Classroom by this custom action. Unfortunately, this workaround does not  work.
```YAML
name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    permissions: write-all
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto
        id: auto
        uses: education/autograding@v1
      - name: Out
        id: out
        env: 
          GRADES: ${{join(steps.auto.outputs.*, '\n')}}
        run: |
          echo "Auto print $GRADES"
          points=$(echo "$GRADES" | awk -F'/' '{print $1}')
          echo 'points<<EOF' >> $GITHUB_OUTPUT
          echo $points >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT
          totalpoints=$(echo "$GRADES" | awk -F'/' '{print $2}')
          echo 'totalpoints<<EOF' >> $GITHUB_OUTPUT
          echo $totalpoints >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT
      - name: Get points
        env:
          POINTS: ${{ steps.out.outputs.points }}
          TOTAL: ${{ steps.out.outputs.totalpoints }}
        run: echo "Grades $POINTS / $TOTAL"
      - name: mark
        id: mark
        env:
          POINTS: ${{ steps.out.outputs.points }}
          TOTAL: ${{ steps.out.outputs.totalpoints }}
#       run: echo "points=7" >> "$GITHUB_OUTPUT" ; echo "total-points=9" >> "$GITHUB_OUTPUT"
        uses: markpatterson27/autograding@dev-points-input-release
        with:
          points: ${{ steps.out.outputs.points }}
          available-points: ${{ steps.out.outputs.totalpoints }}
#          points: 8
#          available-points: 15
```
