### DISCUSSION TITLE
Consider YAML 1.2 for dependabot configuration

### DISCUSSION THREAD

**Discussion by erickgskovik** [community/community#109188] [Code Security]
### Select Topic Area

Product Feedback

### Body

Hello!

I am trying to integrate dependabot. But I have to quote `updates.[0].scheduel.time` otherwise the field becomes [sexagesimal](https://yaml.org/spec/1.1/#id858734). This is no longer the case for YAML 1.2 where I don't have to quote the time. So this is surprising when the config fails.

Since the document didn't mention YAML 1.1 and GitHub Action seems using YAML 1.2, maybe consider using YAML 1.2 spec for dependabot config file too?

Example:

```yaml
version: 2

updates:
  - package-ecosystem: docker
    schedule:
      interval: weekly
      timezone: Etc/UTC
      day: sunday
      time: '15:00'
    labels:
      - internal
    open-pull-requests-limit: 1
    directory: /dir
```
