### DISCUSSION TITLE
actions/checkout@v4 started to fail

### DISCUSSION THREAD

**Discussion by yvs2014** [community/community#109146] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi all,

Has anyone spotted that some workflow/action started to fail recently?
With simple  ".github/workflows/build.yaml" like
```
defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build, pack, install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install -y dpkg-dev debhelper pkg-config libgtk-4-dev libjson-glib-dev
```

it started to display errors at getting packages (looks like fetching 22.04 instead 23.04 for some debs)
```
Err:28 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libegl-mesa0 amd64 23.0.4-0ubuntu1~22.04.1
  404  Not Found [IP: 52.147.219.192 80]
Err:40 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libegl1-mesa-dev amd64 23.0.4-0ubuntu1~22.04.1
  404  Not Found [IP: 52.147.219.192 80]
...
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_23.0.4-0ubuntu1%7e22.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mesa/libegl1-mesa-dev_23.0.4-0ubuntu1%7e22.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

Sorry if it's not the right place to ask about action failures (just cannot find out a right one)
