### DISCUSSION TITLE
Patterns for caching an executable binary

### DISCUSSION THREAD

**Discussion by Integralist** [community/community#109176] [Actions]
### Select Topic Area

Question

### Body

👋🏻 

I want to cache an executable binary for one day, and then when the cache expires the install will be attempted again and as a result, the latest version of the executable will be downloaded (which may well be the same version as before if there has been no newer releases).

I started writing the following configuration before realising there wasn't a way to specify a TTL or expiry using the `cache` action:

```yaml
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod

      - name: Expose Go bin directory to $PATH
        run: echo "PATH=~/go/bin:$PATH" >> "${GITHUB_ENV}"

      - name: Setup Cache for My Executable
        id: cache-executable
        uses: actions/cache@v4
        with:
          path: ~/go/bin/my-executable
          key: ${{ runner.os }}-my-executable
          save-always: true

      - name: Install My Executable
        if: steps.cache-executable.outputs.cache-hit != 'true'
        run: go install github.com/my/executable@latest

      - name: Use installed executable binary
        run: my-executable --whatever
```

Does anyone know the best way to achieve this?

Thanks!
