### DISCUSSION TITLE
Conditional GHA jobs `services`

### DISCUSSION THREAD

**Discussion by ronjouch** [community/community#109389] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a [GHA Reusable Workflow](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call) that runs tests. Client projects that use it ...

- Sometimes have tests that need one or two local services, e.g. { Redis, MongoDB, PostgreSQL }.
- Sometimes have tests that don't need any local service

I can easily offer the services with [`jobs.<job_id>.services`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idimage).

**However**, I do _not_ want to always start these 3 `services`, as they take time to start up (around 30s for the three of them), which degrades tests speed!

→ I would like to **conditionally enable services**, based on a [workflow `input`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs).

Sadly, I couldn't find support for conditionally enabling/disabling a service. Said differently, [`jobs.<job_id>.services`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idimage) offers no `if` field 😕.

The best I could find is to abuse starting the smallest possible "no-op" / "minimal" image I could find. See `# <-- HERE` marker below:

```yaml
name: Tests reusable GHA

on:
  workflow_call:
    inputs:
      redis:
        description: Whether to provide a Redis service on port 6379. Defaults to false.
        required: false
        type: boolean

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: ${{ inputs.redis == 'true' && 'redis' || 'tianon/true' }} # <-- HERE
        ports:
          - '6379:6379'
        options: ${{ inputs.redis == 'true' && '--health-cmd "redis-cli ping" || '--quiet' }}
```

It works and only incurs a modest 1s to 3s delay, but:

1. It's sad to have to start this machinery all for nothing
2. I don't like adding an external dependency on this no-op `tianon/true` image.

Do you have anything better? Thanks for the help.
