### DISCUSSION TITLE
Docker File is not generating when I am creating my dev container

### DISCUSSION THREAD

**Discussion by akhand769** [community/community#109440] [Codespaces]
### Select Topic Area

Question

### Body

I am trying to create a devcontainer having ubuntu but after creating the devcontainer it is only generating the devcontainer.json and the dockerfile is not generating , Why ?

**Comment by 77v7777** [comment]
You should create that file manually.

I will attach the sample YML file.

This is Azure pipeline file. Hope this helps.

```
trigger:
  - dev

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: "b49b756f-4d39-423a-9ef5-eedea0af4a5a"

  # Web app name
  webAppName: "revaitest"

  # Environment name
  environmentName: "revaitest"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: $(environmentName)
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: revaitest"
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: webAppLinux
                    WebAppName: $(webAppName)
                    packageForLinux: "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
                    RuntimeStack: "NODE|18-lts"
                    StartupCommand: "npm run build && npm install -g serve && serve -s build"
                    ScriptType: "Inline Script"
                    InlineScript: |
                      npm install
                      npm run build --if-present

```
