### DISCUSSION TITLE
Incorrect processing bool logic for two variables

### DISCUSSION THREAD

**Discussion by Chernobrovkin-AD** [community/community#109449] [Actions]
### Select Topic Area

Bug

### Body

Hello, I faced the next confusing behavior.
I have two boolean variables with a job scope:
```
jobs:
  ubuntu20-build:
    env:
      IS_SOME_TAG: ${{ contains(github.event.pull_request.labels.*.name, 'some_tag') }}
      IS_INTERNAL: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository}}
```
The first one has value "false", the second one has value "true".
But when I use "and" condition with both of them, it returns "true", and step is started:
```
    steps:
      - name: Do something on tag for internal builds
        if: ${{ env.IS_SOME_TAG && env.IS_INTERNAL }}
```
Also separate variable calculated with same expression echoed as "true", while "false" expected.

P.s.
I found workaround that gives expected behavior, but it is workaround.
`${{ env.IS_SOME_TAG == 'true' && env.IS_INTERNAL == 'true' }}`
