### DISCUSSION TITLE
Feature Request: Add `for` capability to steps

### DISCUSSION THREAD

**Discussion by thisisthetechie** [community/community#109540] [Actions]
### Select Topic Area

Product Feedback

### Body

When working with workflows, the only option for dealing with repetitive actions is the Matrix. However, this is rather frustrating, as it only applied to a job. Among other annoyances. 
Please consider including something akin to a `for` attribute (similar in action to the `if` attribute) whereby a list can be used to repeat that one step in a `for_each` style.

I envisage the following implementation:
```
my-job:
  - name: Say hi to my little friends
    for:
      - Harry
      - Sally
      - Joe
    run: |
      echo "Hello ${{ each }}"
```
