### DISCUSSION TITLE
How to get the date month and year in GitHub actions along with numbers (1 to 10) based on workflow trigger?

### DISCUSSION THREAD

**Discussion by MadhuPole** [community/community#109573] [Actions]
### Select Topic Area

Question

### Body

Hi everyone!

We need get the date month and year along with the numbers based on workflow trigger. like If we run the workflow first time it will be 20240222.1 (year/month/date). if it is second time 20240222.2 like that and this number will reflect in the build artifact name. for example, dev_20240222.1, dev_20240222.2 and so on. is it possible to pass the numbers and that number reflect in the artifact number?
Please recommend any commands for this.
Thanks

**Comment by Vijaykv5** [comment]
Hi @MadhuPole 
Yes, you can achieve this using scripting or programming languages like Python, JavaScript, or shell scripting. You can write a script that retrieves the current date and the number of times the workflow has been triggered, then formats them accordingly (e.g., YYYYMMDD.N) and passes the resulting string to the build artifact name. This can be accomplished using date functions and counters in your scripting language of choice.

**Reply by MadhuPole** [reply]
Hi @Vijaykv5 
Is it possible to execute with in my yml file? we need to implement within yml file, so that we can pass it to the artifact name.

**Reply by Vijaykv5** [reply]
@MadhuPole  Yes, you can execute a shell script within your YAML file to generate the artifact name dynamically.

**Comment by thisisthetechie** [comment]
I created an action to do this, since I also needed to do semver version bumping, I created it in Python... It's very basic but gets the job done.

main.py:
```
import semver, argparse
from datetime import date

def bump_semver(bump, version):
  ver = semver.Version.parse(version)
  match bump:
    case "major":
      return ver.bump_major()
    case "minor":
      return ver.bump_minor()
    case "patch":
      return ver.bump_patch()

def bump_date_ver(version):
  ver = date.today()
  datver = "{0}-{1:02d}-{2:02d}.".format( ver.year, ver.month, ver.day )
  if (version.startswith(datver)):
    build = int(version.split('.')[-1]) + 1
    return "{0}{1}".format(datver, build)
  else:
    return "{0}0".format(datver)
  
if __name__=="__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("-b", "--bump", type=str)
  parser.add_argument("-v", "--version", type=str)
  parser.add_argument("-t", "--type", type=str)

  args = parser.parse_args()
  
  match args.type:
    case "semver":
      print(bump_semver(args.bump, args.version))
    case "datver":
      print(bump_date_ver(args.version))
    case _:
      raise ValueError("Invalid version type: {}".format(args.type))
```

action.yaml:
```
name: Bump a SemVer Version
description: Updates a SemVer version number

inputs:
  bump:
    description: The version segment to bump (major, minor or patch)
    required: false
    default: minor
  version-number:
    description: The Version number to bump
    required: true
  number-type: 
    description: The Version Numbering Strategy (either `semver` or `datver`)
    default: semver

outputs:
  version: 
    description: The new version number
    value: ${{ steps.bump.outputs.version }}
    
runs:
  using: composite
  steps:

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Bump Version
      id: bump
      shell: bash
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: '1'
      run: |
        # Bump ${{ inputs.bump }} number
        pip install semver argparse
        version=$(python ${{ github.action_path }}/main.py --bump=${{ inputs.bump }} --version=${{ inputs.version-number }} --type=${{ inputs.number-type }})
        echo "version=${version}" >> $GITHUB_OUTPUT
        echo "New Version: ${version}" >> $GITHUB_STEP_SUMMARY 
```
