### DISCUSSION TITLE
hi guys i need help in github workflows. my problem is simple: i have a next app and it relies on env variables also i cannot upload the env file on the repo  so i want to include env variables in docker container from repo secrets so i  can access it  in the next app

### DISCUSSION THREAD

**Discussion by Yassin-Samir** [community/community#109628] [Actions]
### Select Topic Area

Bug

### Body

hi guys i need help in github workflows. my problem is simple: i have a next app and it relies on env variables also i cannot upload the env file on the repo  so i want to include env variables in docker container from github repo secrets so i can access it  in the next app . I need help in writing the github workflow file

**Comment by thisisthetechie** [comment]
You will need to add the secrets via the `env` attribute in your job, step or workflow:

```
jobs:
  create-container:
    name: Create Container
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: Spin up Container
        run: |
          docker build -e MY_SECRET=${{ env.MY_SECRET }} .
```
