### DISCUSSION TITLE
Github Actions workflow error : Unable to find any artifacts for the associated workflow

### DISCUSSION THREAD

**Discussion by imPradhyumn** [community/community#109905] [Actions]
### Select Topic Area

Question

### Body

I am trying to deploy SpringBoot using Azure App Services. Build is fine but I'm getting workflow error in the deployment part at this step

`uses: actions download/artifact@v3`

**Error:** Unable to find any artifacts for the associated workflow.

**Here is my workflow file:**

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F5BC8B41905B44AD9121C770AD2685E1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8DF961F9B7B841FCA221B867971117A5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E50A7F4E4684DFBB9506497C9A67731 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'spotify-clone-backend'
          slot-name: 'Production'
          package: '*.war'
```
