### DISCUSSION TITLE
workflows get triggered automatically even if conditions are not met

### DISCUSSION THREAD

**Discussion by LegendSebastiano-L** [community/community#110271] [Actions]
### Select Topic Area

Question

### Body

We recently added a new workflow that runs on a new tag creation like this:

```
name: Build Docker Container

defaults:
  run:
    working-directory: ./

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
```

but that looks like it also triggers some workflows that are set up in this way:

```
name: Build-serviceName

defaults:
  run:
    working-directory: ./services/serviceName

on:
  push:
    paths:
      - 'services/serviceName/**'
  workflow_dispatch:
```

I assume they are triggered by that because, in the action log in the second column, I see `v2.2.4` or whatever tag has been released.

How can I trigger only the 1st workflow and stop triggering the other ones?
