### DISCUSSION TITLE
Help needed with Github Actions

### DISCUSSION THREAD

**Discussion by philam** [community/community#110277] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I'm trying to deploy a Github Pages website using Docker (I'm using an external theme and plugins).

I have built this action to deploy but it either fails or it succeeds and no website shows up on the domain.

Really not sure what's going wrong here, any assistance would be greatly appreciated :)

```
name: NEW Build and Deploy to Github Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
```

**Comment by jfullstackdev** [comment]
maybe Copilot can help, 

---

Your GitHub Actions workflow seems to be mostly correct, but there might be a couple of issues that could be causing the problem.

1. **Jekyll Build Directory**: The Jekyll build command is running inside a Docker container, and the build output is being written to a directory inside that container. However, the `peaceiris/actions-gh-pages@v3` action runs on the host machine, not inside the Docker container. This means it might not be able to access the `_site` directory that was created inside the Docker container. To fix this, you could try running the Jekyll build command directly on the host machine, rather than inside a Docker container.

2. **GitHub Pages Branch**: By default, the `peaceiris/actions-gh-pages@v3` action deploys to the `gh-pages` branch. However, for user and organization pages, GitHub Pages uses the `main` branch by default. If your repository is a user or organization pages repository, you'll need to set the `publish_branch` input to `main`.

Here's a modified version of your workflow that might work:

```yaml
name: NEW Build and Deploy to Github Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: bundle exec jekyll build --future

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: main  # Change this to 'gh-pages' if your GitHub Pages is set to use that branch
```

This workflow sets up Ruby on the host machine, installs the necessary dependencies, builds the site using Jekyll, and then deploys the site to GitHub Pages. Note that you'll need to have a `Gemfile` in your repository that specifies the `jekyll` gem and any other dependencies your site needs.
