### DISCUSSION TITLE
Bug with GITHUB_STEP_SUMMARY

### DISCUSSION THREAD

**Discussion by yemal** [community/community#110283] [Actions]
### Select Topic Area

Bug

### Body

Hello,

In my composite action I have these steps:
``` yaml
    - name: TEST666
      id: TEST666
      shell: bash
      run: |
        # make the markdown_output in a previous step
        cat markdown_output >> $GITHUB_STEP_SUMMARY
        echo -e "\n### TEST666" >> $GITHUB_STEP_SUMMARY

    - name: TEST777
      id: TEST777
      shell: bash
      run: |
        echo -e "\n### TEST777" >> $GITHUB_STEP_SUMMARY
        find /home/runner/work/_temp/_runner_file_commands/ -ls
        ls -la $GITHUB_STEP_SUMMARY
```

After running this WF I see the markdown from the step `TEST666` and the `### TEST666` line published to the summary.
The step `TEST777` however, doesn't appear in my job summary, but I can see the summary file is created in `/home/runner/work/_temp/_runner_file_commands/` and not empty.

Is it a bug? I was working couple of weeks ago and at some point it got broken, probably because of some upgrade happened to the engine?

Help needed, thanks!
