### DISCUSSION TITLE
Why I can't reference an env var as input for a composite action?

### DISCUSSION THREAD

**Discussion by ay0o** [community/community#110393] [Actions]
### Select Topic Area

General

### Body

```
name: test
env:
  FOO: bar
jobs:
  job1:
    runs-on: ubuntu-latest
   steps:
     - uses: some-composite-action
       with:
         some_input: ${{ env.FOO }}
```

This workflow is not valid because `Unrecognized named-value: 'env'. Located at position 1 within expression: env.FOO`

However, if I set this value as output of another job, it works.

```
jobs:
  job1:
    ...
    outputs:
      foo: ${{ env.FOO }}
    ...
    ...
  job2:
   ...
   steps:
     - uses: some-composite-action
       with:
         some_input: ${{ needs.job1.outputs.foo }}
```

Why?
