### DISCUSSION TITLE
on workflow_run does not trigger the workflow after runninge a worflow using a bot

### DISCUSSION THREAD

**Discussion by kfird214** [community/community#110392] [Actions]
### Select Topic Area

Bug

### Body

I have a workflow that uses

```yaml
# workflow2.yaml
on:
  workflow_run:
    workflows: ["workflow1"]
```

I'm running "workflow1" using Github rest Api and I see on the UI that this run has a `bot` tag on it.
After workflow 1 is done, workflow 2 never gets queued.
