### DISCUSSION TITLE
Serverless Deployment Issue

### DISCUSSION THREAD

**Discussion by ayushkatiyar01** [community/community#110472] [Programming Help]
### Body

I'm working with the serverless framework and want to upload my python project dependencies as a layer for our lambda. So I used the `serverless-python-requirements`  plugin to achieve this goal. So i have all my dependencies in my `requirements.txt` file . It works well with the external packages and i'm able to deploy. But I have some custom packages and i want to add as a dependencies for my project, but it is giving me error.

my project structure/
│
├── lambdas/
│   ├── __init__.py
│   ├── lambda1.py
│   └── lambda2.py
│
├── packages/
│   └── custom-package.zip
│
├── requirements.txt
├── serverless.yml
│
└── README.md
                 
serverless.yml
```
service: service-name

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  stackName: ${self:provider.stage}-stack-name
  deploymentMethod: direct
  deploymentBucket:
    name: bucket-name


custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: external-dependencies
      compatibleRuntimes:
        - python3.11
 
#some code configuration of lambda

plugins:
  - serverless-python-requirements
```

requirements.txt
```
numpy
pandas
sqlalchemy
./packages/custom-package.zip
```

error i got :
```
Error: WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
WARNING: Requirement './packages/custom.zip' looks like a filename, but the file does not exist
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/var/task/packages/custom.zip'
```

### Guidelines

- [x] I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.
