### DISCUSSION TITLE
Count reusable workflows only when conditions are not met

### DISCUSSION THREAD

**Discussion by jonatiao** [community/community#110575] [Actions]
### Select Topic Area

Product Feedback

### Body

Hello,
Can github consider changing the behavior of max reusable workflows to count referenced workflows only when conditions(if) are met?

```
mycondition=false

jobs:
  call_reusable:
    uses: org/repo/.github/workflows/my_reusable.yaml
    if: mycondition == true
```

The above would not count as a referenced workflow because the condition did not met.

The reason I'm asking this is because I would like to have the same reusable being used by all repos, and the decision on which reusable to use would be decided by a nested workflow.
High level:

```
repoN*:
on:
  push:
    branches: [ develop ]

jobs:
  call_reusable_ci:
    uses: org/repo/.github/workflows/ci.yaml
```

```
on:
  workflow_call:

jobs:
  java_maven:
    uses: org/repo/.github/workflows/ci_java_maven.yaml
    if: env.tech == java && env.build == maven
  java_gradle:
    uses: org/repo/.github/workflows/ci_java_gradle.yaml
    if: env.tech == java && env.build == gradle
.. and so on
```

I think this would help us on big enterprises. I believe the alternative for this would be to create a specific workflow for each specific kind of repo, or maybe try to detect which kind of technology I'm using and build some logic to switch versions and stuff..
I'm trying to make easier the work when we have a centralized team to rule all workflows.
