### DISCUSSION TITLE
Dynamic Run-name based on environment variable set in script

### DISCUSSION THREAD

**Discussion by anjalichhabra-clarks** [community/community#110625] [Actions]
For my multiple scheduled job, wanted to set run-name dynamically based on job action/ Platform 

I have 4 scheduled jobs which run on Desktop, Iphone Browser, API Test and Android Browser. Based on scheduled time, I want to set the run-name differently for each run. 

I tried setting it with environment variable but didn't get success.. 

Code Snippet : 

> name: GitHub Workflow Scheduled Test 
> **run-name: Regression Test on ${{github.env.runName}}**
> on:
>   workflow_dispatch:
>   schedule:
>     - cron:  '20 10 * * *'   #Desktop Run
>     - cron:  '25 10 * * *'   #Iphone Run
>     - cron:  '30 10 * * *'   #API run
>     - cron:  '35 10 * * *'   #Android run
> jobs:
>   test:
>     name: Scheduled Job
>     timeout-minutes: 240
>     runs-on: ubuntu-latest
>     steps:
>       - name: Set Run Name
>         uses: dkershner6/switch-case-action@v1
>         id: setRunName
>         with: 
>             default: QA - Desktop
>             conditionals-with-values: |
>               ${{github.event.schedule=='20 10 * * *'}} => QA - Desktop
>               ${{github.event.schedule=='25 10 * * *'}} => QA - Iphone
>               ${{github.event.schedule=='30 10 * * *'}} => QA - API
>               ${{github.event.schedule=='35 10 * * *'}} => QA - Android
>       - run: |      
>           echo runName=${{steps.setRunName.outputs.value}} >> $GITHUB_ENV

I want **run-name: Regression Test on ${{github.env.runName}}** code to print like **Regression Test on QA - Desktop** based on the output. 

Currently it is printing blank : 
![image](https://github.com/community/community/assets/146458999/802fabed-c28b-441f-90a3-5ecf29a380d0)

Expected Response like : 
![image](https://github.com/community/community/assets/146458999/5e35053c-135d-426f-9df5-9a43f7b9aec7)

Looking forward for better approch.. Thanks in advance.

**Comment by AidenJamesYt** [comment]
The environment variable issue may be due to github actions currently experiencing degraded performance, meaning it is down for some people. To stay updated on the status, [visit the GitHub Status Site](https://www.githubstatus.com/) for live status updates.

**Reply by anjalichhabra-clarks** [reply]
It shows all status up for me..
![image](https://github.com/community/community/assets/146458999/8d170dd7-2cf9-4a84-a1a8-fcc91c0961d1)

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by koder101** [comment]
I can confirm that this is working for me. Although the doc says that the `run-name` has only access to `{{ inputs }}` and `{{ github }}` contexts, but when I added a variable at the repository level (under Github secrets) and accessed it using the `vars.DEFAULT_ENVIRONMENT` surprisingly it worked. You may use the same trick to achieve what you are looking for.

May be this is an undocumented feature ( _bit reluctant to post if they remove it after its discovery_ 😁 ).

```
on:
  push:
    branches:
      - main
    paths:
      - 'abcd/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the deployment environment'
        required: false
        default: 'DEV'
        type: choice
        options:
          - DEV
          - UAT
          - PROD

run-name: '${{ github.event.inputs.environment || vars.DEFAULT_ENVIRONMENT }} - Run ID: ${{ github.run_id }} - by @${{ github.actor }}'
```
