### DISCUSSION TITLE
Error `destination path already exists and is not an empty directory` when running step 'flutter pub get'

### DISCUSSION THREAD

**Discussion by trietfidelia** [community/community#110697] [Actions] [answered]
### Select Topic Area

General, Flutter

### Body

Currently I am setting up github action for my flutter project. 
My workflows ran successfully several times until today the error below appeared. I have tried many ways to delete data in the ~/pub-cache/ folder but still get bellow  error. Does anyone have any solution for this problem? Thank you very much

Error:
```
Git error. Command: `git clone --mirror https://github.com/******/my-app.git /c/Users/runneradmin/.pub-cache\git\cache\my-app-f653a1ef882151d633962cffcc7c2526653f0bbe`
stdout: 
stderr: fatal: destination path '/c/Users/runneradmin/.pub-cache\git\cache\my-app-f653a1ef882151d633962cffcc7c2526653f0bbe' already exists and is not an empty directory.
exit code: 128
Error: Process completed with exit code 69.
```

Code workflow:

```
 - uses: actions/checkout@v3
- uses: subosito/flutter-action@v2
  with:
    flutter-version: "3.19.0"
    channel: 'stable'
    cache: true 
    cache-key: 'flutter-windows-stable-3.19.0-x64-df832a426eb5e0e80d12333cd7ee7419ab58ff49'
    cache-path: '${{ runner.tool_cache }}/flutter/stable-3.19.0-x64'
    architecture: x64

- name: Setup credentials to access private repositories
  run: git config --global url.https://${{ secrets.ACCESS_TOKEN }}@github.com/.insteadOf https://github.com/

- name: Clean cache
  run: dart pub cache clean --force
  shell: cmd

- name: Clean and get Flutter packages
  run: flutter clean && flutter pub get
```
