### DISCUSSION TITLE
Hide(minimize) issue comments do not show information in the event

### DISCUSSION THREAD

**Discussion by hellodword** [community/community#11062] [Actions]
I'm using github actions with the `issue_comment` event, like:

```yaml
name: test

on:
  issue_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - run: cat "$GITHUB_EVENT_PATH"
```

and when I hide(minimize) or unhide the comment, the  action will be triggered as `edited`, but there is no information about the `hide` or `unhide` in the event.

And the github api do not show any information either.

For example:

Comment link(minimized): `https://github.com/isaacs/github/issues/1133#issuecomment-363996601`

Comment api: `https://api.github.com/repos/isaacs/github/issues/comments/363996601`

Issue api: `https://api.github.com/repos/isaacs/github/issues/1133`
