### DISCUSSION TITLE
workflow does not bypass repository rules

### DISCUSSION THREAD

**Discussion by abbas-opsguru** [community/community#110674] [Actions] [answered]
### Select Topic Area

Question

### Body

Hey All,

I have a simple workflow that creates and pushes to main branch directly. I also have a repository rule to avoid direct push to the main branch. In the Bypass list, I added a user to be able to bypass this rule.

What I need is to provide the workflow to push directly to main branch.
However, I got this error:

`error: GH013: Repository rule violations found for refs/heads/main.` 

My workflow is like this:

```
name: Create and Push Test File

on:
  workflow_dispatch:  

jobs:
  create_and_push_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "user-email@email.com"
          git config --global user.name "github-username"

      - name: Create test.txt file
        run: echo "hello" > test.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add test.txt
          git commit -m "Add test.txt" --author="github-username <user-email@email.com>"
          git push origin main 
```

Note that when I test pushing directly from my local machine, it works and bypass the rule.
Also, in the settings of my repo, under Actions, the `Workflow permissions` is set to `Read and write permissions`

So, can anyone help me to find the issue?

The complete error:

```
remote: error: GH013: Repository rule violations found for refs/heads/main.        
remote: - Changes must be made through a pull request.
```

**Comment by abbas-opsguru** [comment, marked as answer]
I found the solution if someone has a similar issue.

- Part of the issue is in `Checkout repository` step. The `actions/checkout` action by default persists Git credentials, which might interfere with the subsequent steps, especially if you want to use some specific credentials to bypass the repository rules.
So, the first step is setting `persist-credentials` to `false` in this step. This will prevent the persisted credentials from being used in subsequent steps.

- Now since we remove the credentials. when executing push, we need to send the username and the Personal Access Token (PAT) of the user in the push command as well. Note that we assume the PAT has enough permission to bypass the repository rule (i.e. workflow+repo permissions in classic github token)

So, the push command will be like this:
`git push https://GIT-USERNAME:$PAT@github.com/user/repository-name.git`

So, the final workflow with all these changes will be as follow:

```
name: Create and Push Test File

on:
  workflow_dispatch:  

jobs:
  create_and_push_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.email "user-email@email.com"
          git config --global user.name "github-username"

      - name: Create test.txt file
        run: echo "hello" > test.txt

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git add test.txt
          git commit -m "Add test.txt" 
          git push https://github-username:$PAT@github.com/user/repository-name.git

```

NOTEs:
1. This code used a repository secret with PAT name (`PAT: ${{ secrets.PAT }}`). Make sure to provide the correct name.
2. Make sure to use correct Github credentials in config and replace the user.name and user.email with correct values.
3. Make sure to provide the correct address of your git repository in `push` command.
