### DISCUSSION TITLE
[Reusable Workflow] How can I specify that I need a specific job of a reusable workflow?

### DISCUSSION THREAD

**Discussion by dianjuar** [community/community#11072] [Actions]
My question is:
When I’m using a reusable workflow, how can I specify using the `needs` parameter in an independent job that I need a specific job of a reusable workflow, not the whole workflow?

Let me explain:
I’m using a reusable workflow to store common steps. I have a different job that depends on an inner job of that reusable workflow. **I can not specify that I need a specific job of the reusable workflow**. All that I can do is refer to the whole reusable workflow.

This is the current image of the workflow:
![image](https://user-images.githubusercontent.com/7026066/152658764-e77af413-204c-4fa1-987d-b98750469389.png)

On the dependent job, I put needs: `pr-test`, to wait for `pr-test/lint` because I can not find another way of telling my dependant job to only wait for a specific job of the reusable workflow.

Seems natural to me to put `pr-test/lint`, but it doesn’t work. I tried many other configurations without success. It keeps telling me that Job ‘pr-analysis’ depends on unknown job ‘pr-test/lint’.

This is what I’m looking for:
![image](https://user-images.githubusercontent.com/7026066/152658771-c6ff206f-af82-441e-8bbe-467f1591d8e1.png)

Here is a try: [build: fix sonarqube coverage · bikecoders/ngx-deploy-npm@8402bd9 · GitHub 1](https://github.com/bikecoders/ngx-deploy-npm/actions/runs/1766944764)

here is the yml simplified:
```YML
name: PR's
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-test:
    uses: bikecoders/ngx-deploy-npm/.github/workflows/basic-test.yml@master

  pr-analysis:
    name: SonarCloud Pr Analysis
    runs-on: ubuntu-latest
    needs: pr-test
    steps:
      - run: echo "I only want to wait for pr-test/lint"
```

---

Note:
What I’m genuinely trying to achieve is to only wait for `pr-test/unit-test(16)`, but the matrix seems to add an extra layer of complexity. That’s why I first tried something more straightforward.
