### DISCUSSION TITLE
Reusable workflows: Unable to access correct `vars` context in job that references environment

### DISCUSSION THREAD

**Discussion by hknutsen** [community/community#110873] [Actions]
### Select Topic Area

Bug

### Body

How to recreate:

1. Create reusable workflow `.github/workflows/reusable.yml`:

    ```yaml
    name: Reusable
    
    on:
      workflow_call:
        inputs:
          environment:
            description: The name of an environment to run the job on.
            type: string
            required: false
    
          subject:
            description: The name of the subject to greet.
            type: string
            required: true
    
    jobs:
      main:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
          - run: echo "Hello, $SUBJECT"
            env:
              SUBJECT: ${{ inputs.subject }} 
    ```

1. Create caller workflow `.github/workflows/caller.yml`:

    ```yaml
    name: Caller
    
    on:
      workflow_dispatch:
        inputs:
          environment:
            description: The name of an environment to run the job on.
            type: string
            
    jobs:
      main:
        uses: ./.github/workflows/reusable.yml
        with:
          environment: ${{ inputs.environment }}
          subject: ${{ vars.SUBJECT }}
    ```

1. Add repository level configuration variable:

    ```console
    gh variable set "SUBJECT" --body "Joe Schmoe"
    ```

1. Add environment level configuration variable:

    ```console
    gh variable set "SUBJECT" --env "example" --body "Jane Doe"
    ```

1. Run workflow `Caller` with default inputs.

    Expected output: `Hello, Joe Schmoe`

    Actual output: `Hello, Joe Schmoe`

1. Run workflow `Caller` with the following inputs:

    | Name | Value |
    | --- | --- |
    | environment | example |

    Expected output: `Hello, Jane Doe`

    Actual output: `Hello, Joe Schmoe`

An identical setup works as expected if using secrets instead of configuration variables.
