### DISCUSSION TITLE
Step Fires Despite Condition?

### DISCUSSION THREAD

**Discussion by robwilkerson** [community/community#110893] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a workflow that includes a `deploy` job. As part of that job, I have a final step that creates a GH release _if_ `${{ github_ref_type }} == 'tag'`. What I'm finding, though, so that pushing code to `main` runs this step which then fails because no tag is specified. Where did I go wrong?

```yaml
      - name: echo stuff
        run: |
          echo "ref type: ${{ github.ref_type }}"
          echo "ref: ${{ github.ref }}"
          echo "ref name: ${{ github.ref_name }}"

      # https://github.com/marketplace/actions/create-release
      - name: Create Github Release
        if: ${{ github.ref_type }} == 'tag'
        uses: ncipollo/release-action@v1
        with:
          body: "Final (production) release created from the ${{ github.ref_name }} tag."
```
Output:
<img width="468" alt="Screenshot 2024-03-04 at 9 58 06 AM" src="https://github.com/community/community/assets/7735/cfadfeef-c18c-4238-8ef2-feb0edd39603">

Would appreciate any insight, thanks!
