### DISCUSSION TITLE
Action not ran, no outage

### DISCUSSION THREAD

**Discussion by cindytrieu** [community/community#110867] [Actions]
### Select Topic Area

Bug

### Body

Hi, I have a rebuild action created for my GitHub pages site, which I pasted below. It's been running for almost the past month smoothly.

It ran last night and the night before consistently around 8AM UTC, which is the time I set. However, tonight it did not run. I checked the outages page, everything is operational on GitHub's end. It's been over an hour, still nothing.

I did check in some changes yesterday, but not to the workflow specifically. When rerunning the workflow, it built fine, no errors. (See screenshot)

Was this a one time thing, or should I add something to my workflow to make sure it is always running?

```
name: Rebuild

on:
  schedule:
    - cron:  '0 8 * * *' # Runs every day at 8am UTC

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub pages build endpoint
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $GH_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
```

![Screenshot_20240304-012701](https://github.com/community/community/assets/6626457/b56b9d8b-ce49-4b01-a6a8-4db72574e786)

-------
Update:

It did end up running, but hours after the scheduled time. Why?

![Screenshot_20240304-090507](https://github.com/community/community/assets/6626457/251c1b7d-04fc-4c5e-8a51-7c5405fc7837)
