### DISCUSSION TITLE
cancelled() function not working with matrix job that calls reusable workflow

### DISCUSSION THREAD

**Discussion by tgoric** [community/community#110929] [Actions]
### Select Topic Area

Bug

### Body

The `cancelled()` and `failure()` status check functions do not work properly with matrix jobs which call to reusable workflows. If at least one job of the matrix fails, a job dependent on the matrix job which has a condition of `if: ${{ !cancelled() && !failure() }}` can still execute. 

A full repro is in [this](https://github.com/tgoric/actions-bug-repro) repo, with multiple [workflow runs](https://github.com/tgoric/actions-bug-repro/actions/workflows/bug.yml) exhibiting the issue. 

### To reproduce:
1. Create this workflow as reusable.yml. The job will randomly succeed or fail based on a call to `get-random`:

```yml
name: Reusable

on:
  workflow_call:

jobs:
  test:
    name: Reusable
    runs-on: windows-latest
    
    steps:
      - name: toss a coin
        run: |
          $test = $true, $false | get-random
          if($test) { throw "fail" }
```

2. Call the above workflow in a matrix, and finally have a job that depends on that matrix job:
```yml
name: Matrix bug

on:
  workflow_dispatch:

jobs:
  loop_matrix:
    strategy:
      matrix:
        index: [0,1,2,3]
    uses: ./.github/workflows/reusable.yml

  final_job:
    name: Final step
    runs-on: windows-latest
    needs: [loop_matrix]
    if: ${{ !cancelled() && !failure() }}
    steps:
      - name: Test
        run: |
          write-output "${{ needs.loop_matrix.result }}"
          write-output "${{ contains(needs.*.result, 'cancelled') }}"
          write-output "${{ contains(needs.*.result, 'failure') }}"
```

3. Execute the main job several times to get random failures in different places.

**Expected behavior**: The final job should never execute if one of the matrix jobs fails.
**Actual behavior**: If one or more of the matrix jobs fails, the final job will still run. When it runs, you can see in its printed output that it knows the loop_matrix job was cancelled.

A workaround for this is to use `!contains(needs.*.result, 'cancelled')` instead of `!cancelled()`
