### DISCUSSION TITLE
Allow `workflow_run` to be filtered by tags as well as branches

### DISCUSSION THREAD

**Discussion by drdavella** [community/community#111043] [Actions]
### Select Topic Area

Product Feedback

### Body

I like to use tag-based releases for my projects. I also would like to link multiple GitHub actions using `workflow_run`. For example, I want my test workflow to trigger the release workflow, but only on tags that match a particular pattern (e.g. semver version strings).

This kind of tag-based filtering is easy enough to do with other kinds of workflow triggers. However it doesn't seem to be available for `workflow_run`, which limits my options here.

To be concrete, I'd like to do something like this:
```yaml
name: Deploy

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
```
