### DISCUSSION TITLE
Feedback and signaling from an action triggered with a pull request comment

### DISCUSSION THREAD

**Discussion by gianarb** [community/community#111005] [Actions]
### Select Topic Area

Question

### Body

```yaml
name: "Delivery container"
on:
  issue_comment:
    types: [created]
jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.comment.body, '/push-container') && github.event.issue.pull_request }}
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: read
      statuses: write
    steps:
    - name: Get PR branch
      uses: xt0rted/pull-request-comment-branch@v2
      id: comment-branch

    - name: Start Action
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'Push Container'
        description: 'Push container started'
        state: 'pending'
        sha: ${{steps.comment-branch.outputs.head_sha}}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.comment-branch.outputs.head_sha }}

    - name: "build"
      run: "make"

    - name: Failure Status Action
      uses: Sibz/github-status-action@v1
      if: ${{ !success() }}
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'Push Container'
        description: 'Push container succeded'
        state: 'failure'
        sha: ${{steps.comment-branch.outputs.head_sha}}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Success Action
      uses: Sibz/github-status-action@v1
      if: ${{ success() }}
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'Push Container'
        description: 'Push container succeded'
        state: 'success'
        sha: ${{steps.comment-branch.outputs.head_sha}}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
```

Hello, this action works for me, I want to deploy a container with a comment `/push-container` on a PR. Recently I tried to improve notification and signaling with the `Sibz/github-status-action` that uses GitHub status on a commit, what I don't like is that I need to wait for the job to find a worker in order to get a "pending" state. It is not the same feeling I get when an action runs on a PR where the status pending is there
