### DISCUSSION TITLE
How to specify a group of jobs with needs in Workflow

### DISCUSSION THREAD

**Discussion by andy8leung** [community/community#111049] [Actions]
### Select Topic Area

Question

### Body

```
jobs:
  A:
    ...
  B:
    ...
  C:
     needs: [A, B]
  D: 
     needs: [A, B]
```

When you need to add a new job (let's say E), we would have to update the needs list in C and D. Is there a better way to handle this instead of updating each of C and D's needs list?  

For example something like:

```
testjobs: [A, B, E]
jobs:
  A:
    ...
  B:
    ...
  E:
    ...
  C:
    needs: testjobs
  D:
    needs: testjobs
```
