### DISCUSSION TITLE
Multiple operating systems wait endless for pick up the job

### DISCUSSION THREAD

**Discussion by 4Source** [community/community#111091] [Actions]
### Select Topic Area

Question

### Body

I would like to run a job on ubuntu-latest, windows-latest, macos-latest. But the only thing I get is an endless waiting job to get picked up by a runner: 
```
Requested labels: ubuntu-latest, windows-latest, macos-latest
Job defined at: 4Source/obsidian-plugin-template/.github/workflows/ci.yml@refs/pull/20/merge
Waiting for a runner to pick up this job...
```
I don't know I have error in my code or this is some error in the actions does any one know something?

```
name: Continuous Integration

on: 
  pull_request:
    branches:
      - master
  push: 
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Use Node.js "18.x"
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      
      - name: Install Dependencies
        run: npm i

      - name: Run Tests
        run: npm run test
```
![image](https://github.com/community/community/assets/38220764/9a897200-2a15-4431-9790-96686569edf9)

If I run each of the Systems separate all of them succeed 
```
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
```
![image](https://github.com/community/community/assets/38220764/163de80d-f3ed-4394-9382-ed9c0fabfd63)

```
jobs:
  test:
    name: Run unit tests
    runs-on: windows-latest
```
![image](https://github.com/community/community/assets/38220764/94cf5f13-82bd-4192-9648-4adcffe6c9f3)

```
jobs:
  test:
    name: Run unit tests
    runs-on: macos-latest
```
![image](https://github.com/community/community/assets/38220764/32e5a74d-92d3-46cd-9e28-c81c0e9b68d8)
