### DISCUSSION TITLE
Private npm package that includes a private npm package

### DISCUSSION THREAD

**Discussion by jasonsturges** [community/community#111172] [Actions] [answered]
### Select Topic Area

Question

### Body

With GitHub Packages, I have a npm package that includes another npm package from the same organization.

As in:
- `@my-organization/package-A` = private package
- `@my-organization/package-B` = private package that requires private package `@my-organization/package-A`

Experiencing a permissions issue installing `package-A` and publishing `package-B`.

Base `package-A` publishes fine, and is available in GitHub package.

Setup for `package-B`:

package.json:
```json
  "name": "@my-organization/package-B",
  "repository": "github:my-organization/package-B",
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/@my-organization"
  },
  "dependencies": {
    "@my-organization/package-A": "^1.0.0",
```

publish.yml
```yml
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Tried read and also: permissions: read-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@my-organization"
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

## Using .npmrc (Checkout works / Publish fails)

Normally when I run an action that requires a private repository, I include a .npmrc file:

```
//npm.pkg.github.com/:_authToken=secret_token
@my-organization:registry=https://npm.pkg.github.com
```

This checkout works; however, publish then fails:

```
Run npm publish
npm notice Publishing to https://npm.pkg.github.com/ with tag latest and default access
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://npm.pkg.github.com/@my-organization%2fpackage-B - Permission permission_denied: The token provided does not match expected scopes.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

## Using Package Settings (Checkout fails)

In order to remove the .npmrc file, I tried setting _Package Settings_ in `package-A`
- From the organization
- Packages
- Select package-A
- Go to _Package settings_
- _Manage Actions access_ and _Add Repository_
- Added package-B with Read access

> ![image](https://github.com/community/community/assets/1213591/702342f6-b120-4024-8040-009202c3ff80)

I'd think this means `package-B` can access `package-A` without specifying a .npmrc file, using the GitHub Token.

Also tried just the scope the in the .npmrc:

```
@my-organization:registry=https://npm.pkg.github.com
```

This configuration fails to install, resulting in:

```
Run npm ci
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@my-organization/package-A/1.0.0/sha - unauthenticated: User cannot be authenticated with the token provided.
```

Can't get read `package-A` / write `package-B` permissions correct here.

I have many private packages used by apps that are built by GitHub Actions workflows, but this is the first time trying to build a private dependency with a private dependency.

**Comment by jasonsturges** [comment, marked as answer]
Finally got it.

Using _Package settings_ above, no .npmrc, and the issue was I needed the `env` higher in the setup node:

```yml
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@my-organization"
        env:
         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} # <--- ENV before npm ci
      - run: npm ci
      - run: npm run build
      - run: npm publish
```
