### DISCUSSION TITLE
Using Deployment Environments and Conditionals

### DISCUSSION THREAD

**Discussion by bb03** [community/community#111153] [Actions]
### Select Topic Area

Question

### Body

I have a question about [conditional execution](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) and [deployment environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) for GitHub Actions.  The outcome I'm trying to achieve is this workflow
* Run the tests
* If the tests pass, automatically proceed to the next step (which is deploy to a staging environment)
* If the tests fail,  wait for a manual approval.
** If the user approves the step, then deploy into the staging environment.  Otherwise, do not proceed.

The issue I'm having is that I cannot figure out how I need to author the steps so that I optionally gate on a manual approval. Using environments seems to gate the rest of the workflow regardless of the conditional.  I want the job to be skipped based on the conditional, and not block on the environment manual approval.

I tried something like this at first
```
  run-test:
    uses: workflow/testing-workflow
  
  trigger-deployment:
    runs-on: custom-image
    needs: run-test
    timeout-minutes: 30
    environment: staging
    if: always() && (${{ needs.run-test.result }} == "success" || ${{ needs.run-test.result }} == "skipped")
    steps:
       ...
```
But that didn't seem to work.  I also tried separating out the step, but that didn't work either.  Something like this
```
  run-test:
    uses: workflow/testing-workflow

  manual-review:
    needs: run-test
    runs-on: custom-image
    if: ${{ failure() }}
    timeout-minutes: 30
    environment: staging
    steps:
      - name: Conditional manual approval step
        id: manual_approval
        run: |
          echo " Manual approval step required, e2e tests ${{ needs.run-test.result }}"

  trigger-deployment:
    runs-on: custom-image
    needs: manual-review
    if: always() && (${{ needs.manual-review.result }} == "success" || ${{ needs.manual-review.result }} == "skipped")
    steps:
```

Any help in clarifying what I need to do to get the desired behavior would be very helpful, thanks!
