### DISCUSSION TITLE
Exclude not excluding combinations from matrix

### DISCUSSION THREAD

**Discussion by SiddhantSadangi** [community/community#111128] [Actions]
### Select Topic Area

Bug

### Body

I have the below matrix:

```yaml
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        scripts: # Add in alphabetical order
          - how-to-guides/data-versioning/scripts
          # - how-to-guides/ddp-training/scripts
          - how-to-guides/hello-neptune/scripts
          - how-to-guides/monitor-ml-runs/scripts
          - how-to-guides/organize-ml-experimentation/scripts
          - how-to-guides/present-cross-validation-results/scripts
          - how-to-guides/re-run-failed-training/scripts
          - how-to-guides/neptune-hpo/scripts
          - how-to-guides/sequential-pipelines/scripts
          - how-to-guides/reproduce-run/scripts
          - how-to-guides/restart-run-from-checkpoint/scripts
          - integrations-and-supported-tools/airflow/scripts
          - integrations-and-supported-tools/catalyst/scripts
          - integrations-and-supported-tools/catboost/scripts
          - integrations-and-supported-tools/dalex/scripts
          - integrations-and-supported-tools/detectron2/scripts
          - integrations-and-supported-tools/evidently/scripts
          - integrations-and-supported-tools/fastai/scripts
          - integrations-and-supported-tools/html/scripts
          - integrations-and-supported-tools/kedro/scripts
          - integrations-and-supported-tools/keras/scripts
          - integrations-and-supported-tools/lightgbm/scripts
          - integrations-and-supported-tools/mlflow/scripts
          - integrations-and-supported-tools/mosaicml-composer/scripts
          - integrations-and-supported-tools/optuna/scripts
          - integrations-and-supported-tools/pandas/scripts
          - integrations-and-supported-tools/plotting-libraries/scripts
          - integrations-and-supported-tools/prophet/scripts
          - integrations-and-supported-tools/pytorch/scripts
          - integrations-and-supported-tools/pytorch-ignite/scripts
          - integrations-and-supported-tools/pytorch-lightning/scripts
          - integrations-and-supported-tools/sacred/scripts
          - integrations-and-supported-tools/sklearn/scripts
          - integrations-and-supported-tools/skorch/scripts
          - integrations-and-supported-tools/tensorboard/scripts
          - integrations-and-supported-tools/tensorflow/scripts
          - integrations-and-supported-tools/transformers/scripts
          - integrations-and-supported-tools/xgboost/scripts
          - use-cases/time-series-forecasting/walmart-sales/scripts
          - use-cases/nlp/classification/fasttext/code
          - use-cases/nlp/classification/keras/code
          - use-cases/nlp/summarization/hf_transformers/scripts
        os: ["${{ inputs.os }}"]
        exclude:
          - scripts: integrations-and-supported-tools/detectron2/scripts
            os: windows-latest
          - scripts:
            - integrations-and-supported-tools/kedro/scripts
            - integrations-and-supported-tools/mosaicml-composer/scripts
            python-version: "3.8"
```

I noticed that since last week (around 2024-02-28), the combinations mentioned in the `exclude` clause have not been excluded from the matrix anymore. This used to work fine.

Any pointers?
