### DISCUSSION TITLE
action to use post

### DISCUSSION THREAD

**Discussion by Samyu09** [community/community#111185] [Actions] [answered]
### Select Topic Area

Question

### Body

Hey,
i would like to do a post hit into the application specific to our company which is stil yet to be authenticated. i want to make use of one such github action which can help in using POST query bypassing the authentication.
can someone help with one such action name and the basic template.

**Comment by koeppel** [comment]
Hi,

could you please clarify your question? Do you want to do a POST request to your companies application running on a given server?

What do you mean by:
> our company which is stil yet to be authenticated

Also which authentication do you want to bypass?

**Reply by Samyu09** [reply]
yeah my company meaning its inside our office network, and the authentication is yet to setup. now it is accessible directly.
can you suggest some action??? that help me post the data

**Reply by koeppel** [reply, marked as answer]
I've found this: https://github.com/marketplace/actions/http-request-action
There is already a sample provided:
```yaml
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://ansible.io/api/v2/job_templates/84/launch/'
        method: 'POST'
        username: ${{ secrets.AWX_USER }}
        password: ${{ secrets.AWX_PASSWORD }}
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"key_1": "value_1", "key_2": "value_2"}'
```

Another option would be to create a script (JavaScript / Python / etc.) that is inside your repository which holds the data you want to post. This script can then be executed in a simple action.

Node.js example:

```yaml
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run <name_of_your_post_script>
```
