### DISCUSSION TITLE
On reusing workflows in the context of strategy matrixes, how to cache a step output?

### DISCUSSION THREAD

**Discussion by punkbit** [community/community#111232] [Actions]
### Select Topic Area

Question

### Body

Hi,

Consider a strategy matrix that utilises a hypothetical workflow named "common-action.yml". Let's say that "common-action.yml" has a step which runs a computation that generates several artifacts across a well-defined project structure, as follows:

```
project
project/libA/computed-output/**/*
project/libB/computed-output/**/*
project/libC/computed-output/**/*
```

Each of the presented libs above might depend on each other's "computed-output", so the "computed-output" has to exist in each of the strategy matrix items or iterations. Here, we can determine that the "computed-output" should not have need to be executed for each of the strategy matrix items. A single "compute" to generate all "computed-outputs" should be sufficient, as it'd effectively generate the same output. 

Thus, the question is how to best handle this to cache and reutilize the desired cached resource, e.g., `project/**/computed-output/**/*`?

Here's some pseudo workflows to illustrate the use-case:

The parent workflow

```yaml
name: The parent workflow

on:
  workflow_dispatch:
  push:
    branches:
      - chore/npm-publisher-use-action-error-should-be-verbose

jobs:
  monorepo_packages_handler:
    strategy:
      matrix:
        name:
          - a
          - b
          - c
    uses: ./.github/workflows/common-action.yml
    with:
      name: ${{ matrix.name }}
```

The common-action

```yaml
name: Common action

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  common:
    concurrency:
      group: lib-${{ inputs.name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/some-other.yml

      - name: Compute output
        working-directory: ./lib${{ inputs.name }}
        run: |
           echo "creates the computed-output..."
```
