### DISCUSSION TITLE
github actions failed to create release

### DISCUSSION THREAD

**Discussion by ctrlv0** [community/community#111201] [Actions]
I have a github workflow which executes for about 1.5hrs in a public repo owned by an organization account.

I'm using the create release and upload release asset to first create a release and then upload the compiled program onto github.

however, when at the create release step, the action fails, saying that it does not have access to the resources, which is very vague. other than this there is no other error message to explain this.

```
- name: Checkout code
        uses: actions/checkout@v2
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@cec98b9d092141f74527d0afa6feb2af698cfe89
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\program.zip 
          asset_name: program.zip
          asset_content_type: application/zip
``` 

I have not uploaded the complete workflow for simplicity
