### DISCUSSION TITLE
Help.  Github Workflow Visualization not working correctly when using reusable workflows

### DISCUSSION THREAD

**Discussion by wac84s** [community/community#111233] [Actions]
### Select Topic Area

Bug

### Body

Looking for help.   I have not isolated the cause to the issue yet. The gist of the issue is when I create a github action that calls a reusable workflow that calls other reusable workflows the workflow visualization graph does not correctly reflect/update the status for those jobs.

Action - calls -> reusable workflow (pipeline) -> calls other reusable workflows

```
repo/.github/workflows/pipeline.yml@main
     pre-core-pipeline # status updates fine
     core-pipeline - my-reusable-workflows/.github/workflows/pipeline.yml@main
            PreDebug # status updates fine
            BuildCandidate - my-reusable-workflows/.github/workflows/build-image.yml@main
                   BuildCandidate # status does not update correctly
```

Gist of my repo using the first reusable workflow

```
#runs from a repo/.github/workflows/pipeline.yml@main
jobs:
  pre-core-pipeline:
    name: Pre Core Pipeline
    runs-on: ubuntu-latest
    steps: 
      - name: So Stuff
        run: Do Stuff
        
  core-pipeline:
    name: Core Pipeline
    needs: pre-core-pipeline
    uses: my-reusable-workflows/.github/workflows/pipeline.yml@main
    with:
       .....
```

Gist of my reusable workflow pipeline - my-reusable-workflows/.github/workflows/pipeline.yml@main

```
#my-reusable-workflows/.github/workflows/pipeline.yml@main
jobs:
  # testing if its all reusables the UI works again
  PreDebug:
     name: PreDebug
     runs-on: sw-ubuntu-latest
     steps:
       - name: Status Updates Fine
         run: echo "Ran Fine"

  #STATUS WONT UPDATE   when calling yet another reusable workflow   
  BuildCandidate:
    name: Build Candidate
    uses: my-reusable-workflows/.github/workflows/build-image.yml@main
```

Gist of my build reusable workflow my-reusable-workflows/.github/workflows/build-image.yml@main
```
#my-reusable-workflows/.github/workflows/build-image.yml@main
jobs:
  BuildCandidate:
    name: BuildCandidate
    runs-on: ubuntu-latest
    steps: 
      - name: So Stuff
        run: Do Stuff
       .....
```

It should be noted that anywhere in the graph where I dont use a reusable workflow within my first reusable workflow the status of that job updates correctly.    

![Screenshot 2024-03-07 at 10 36 34 AM](https://github.com/community/community/assets/141072080/62df61bd-3213-4024-a681-401628704ea1)

<img width="1641" alt="Screenshot 2024-03-07 at 10 41 02 AM" src="https://github.com/community/community/assets/141072080/04d3db5e-b0c5-4ad4-ac38-9a94494c7bfe">
