### DISCUSSION TITLE
Variableize Path to action

### DISCUSSION THREAD

**Discussion by whiteninja76** [community/community#111346] [Actions]
### Select Topic Area

Question

### Body

Is it possible to either Variableize the path to an action 
`     
- name: Run CodeBuild
      uses: ${{ env.SOME_STRING }}/aws-codebuild-run-build@v1
      with:
        project-name: pipeline1
        hide-cloudwatch-logs: true
        disable-source-override: true`

or it there a way to tell it to look with in the github organisation im in for a repo with the name
 `     
- name: Run CodeBuild
      uses: ./aws-codebuild-run-build@v1
      with:
        project-name: pipeline1
        hide-cloudwatch-logs: true
        disable-source-override: true`
netiehr of which i have managed to working

I want to do it as i deliver the repo to a third part that has some internal versions of common actions that they want to me to use

**Comment by IsuruSankhajith** [comment]
I believe that You can indeed variableize the path to an action using GitHub Actions. One way to achieve this is by setting up environment variables in your workflow file. For example, you could define an environment variable for the path to the action:
name: Run CodeBuild
uses: ${{ env.SOME_STRING }}/aws-codebuild-run-build@v1
with:
  project-name: pipeline1
  hide-cloudwatch-logs: true
  disable-source-override: true
Then, you can set the value of SOME_STRING in your repository or organization secrets, allowing you to customize it based on the context.

Regarding looking within your GitHub organization for a repo with a specific name, you can use the GITHUB_REPOSITORY environment variable to get the name of the repository. However, directly referencing a local path within your organization's repositories is not supported in GitHub Actions.

Instead, you can either use a specific action published in the GitHub Marketplace or create a custom action within your organization and reference it by its full GitHub URL. This way, you can ensure that the action is consistently available across different repositories and users within your organization.

**Comment by whiteninja76** [comment]
I tried
```
name: Node.js CI

on:
  push:
    branches: [ "main" ]
env:
  RELEASE_NAME: chicken
  ACTION_SOURCE: actions
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: ${{ env.ACTION_SOURCE }}/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm version
```

but get 

`[Invalid workflow file: .github/workflows/node.js.yml#L23](https://github.com/WhitestarTech/testing/actions/runs/8205536004/workflow)
The workflow is not valid. .github/workflows/node.js.yml (Line: 23, Col: 13): Unrecognized named-value: 'env'. Located at position 1 within expression: env.ACTION_SOURCE`
