### DISCUSSION TITLE
Cancellation from "concurrency" doesn't affect "cancelled()" expression

### DISCUSSION THREAD

**Discussion by TjarkoG** [community/community#111323] [Actions]
### Select Topic Area

Bug

### Body

Hi
we've noticed a strange behaviour in our workflows when multiple instances of that workflow ran in parallel. 
We managed to track this strange behaviour down to what seems to be a bug.
When a job gets cancelled due to "concurrency" (pending gets cancelled if another one comes) this doesn't seem to affect the "cancelled()" expression.
So later jobs in a workflow are executed if you start 3 runs within 30 seconds of the following workflow:
```yaml
name: Test cancelled and concurrency
on:
  workflow_dispatch:

jobs:
  waiting:
    concurrency: waiting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Waiting for the other job to start"
      - run: sleep 30
  testing:
    concurrency: testing
    if: ${{ (! failure()) && (! cancelled()) }}
    needs: waiting
    runs-on: ubuntu-latest
    steps:
      - run: echo "running"
      - run: echo ${{ github.run_number }}
```

expected behavior:
the cancelled "waiting" job from concurrency makes "cancelled()" expression return true and "testing" job won't be executed in  workflow run no. 2
actual behavior:
in run no.2 the waiting job gets cancelled and the "testing" step not only gets executed but gets executed first. then from run no.1 and then run no.3

this is just a short example but with multiple jobs with concurrency within one workflow we quickly have a state where all tree runs finish but with different jobs being skipped throughout
