### DISCUSSION TITLE
Calling a composite action from an external workflow using the same ref used in the caller workflow

### DISCUSSION THREAD

**Discussion by Ilyes512** [community/community#111928] [Actions]
### Select Topic Area

Question

### Body

I just started creating an external repository for maintaining my reusable workflows and composite actions. And I got it all working and all, but there is one thing left. (https://github.com/Ilyes512/github-actions)

How can I reference a composite action that is located in the same repository as the (external) workflow. And I want it to use the same ref as the called Workflow.

So, now I used a fixed ref ("main"), but I would like it to point to the same ref as the caller workflow used to call the external workflow.

So from a workflow that is in repository `a` I want to call the external workflow with a ref of `v1`. But within that external workflow there is a call to a composite action in the same repo. And I would like it to use the same ref (`v1`) instead of using a hardcoded ref like I have now: https://github.com/Ilyes512/github-actions/blob/e884cce9bf717362741609245ecba574a784e848/.github/workflows/build.yml#L57

Is that possible? I hope I explained it well enough to be understood. Otherwise I will add some examples.

**Comment by ngljcb** [comment]
Yes, it's possible to reference a composite action located in the same repository as the workflow, and dynamically use the same ref as the calling workflow. You can achieve this by using the github context provided by GitHub Actions.

Here's how you can do it:

1. In your workflow file where you call the external workflow, you can pass the ref dynamically using the `${{ github.ref }}` expression.

```
name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Call External Workflow
        uses: owner/repo/.github/workflows/external-workflow.yml@${{ github.ref }}
        with:
          someInput: someValue
```


2. In the external workflow file `(external-workflow.yml)`, you can use `${{ github.event.ref }}` to dynamically reference the same ref passed from the calling workflow.

```
name: External Workflow

on:
  push:
    branches:
      - main

jobs:
  myExternalJob:
    runs-on: ubuntu-latest
    steps:
      - name: Use Composite Action with Same Ref
        uses: ./path/to/composite-action   # Reference the composite action in the same repository
        with:
          someInput: someValue
```


By using `${{ github.ref }}` in the calling workflow and `${{ github.event.ref }}` in the external workflow, you ensure that they both use the same ref dynamically. This way, you don't have to hardcode the ref in either workflow file.
