### DISCUSSION TITLE
Github pages giving error

### DISCUSSION THREAD

**Discussion by soma2000-lang** [community/community#111980] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Bug

### Body

I have checked the docs and tried to troble shoot the 404 error ofmy github pages but its stll giving me an error

**Comment by CodeByAidan** [comment]
Hello!

I will assume you are talking about this repository of yours: https://github.com/soma2000-lang/soma2000-lang.github.io . 

If you look at your recent "Actions" on the repository, then go to the latest one, and click on the "Build," you should see an error in that: https://github.com/soma2000-lang/soma2000-lang.github.io/actions/runs/8223761583/job/22486799899#step:4:36 .

```console
Error:  Logging at level: debug github-pages 231 | Error: (/github/workspace/./_config.yml): could not find expected ':' while scanning a simple key at line 14 column 1 
```

There's an error in your `_config.yml` file for your GitHub Pages site. The error message indicates that there might be a formatting issue, particularly a missing colon at line 14, column 1.

Now if you go over to the `_config.yml` file here: https://github.com/soma2000-lang/soma2000-lang.github.io/blob/master/_config.yml, you will see on line 14 (https://github.com/soma2000-lang/soma2000-lang.github.io/blob/master/_config.yml#L14):

```yml
email:seckroll16@gmail.com
```

The error is caused by a missing space after the colon in the email field on line 14. YAML syntax requires a space after the colon for key-value pairs. Here's the corrected line:

```yml
email: seckroll16@gmail.com
```

Also, on line 15, this error will trigger again...:

```yml
twitter_username:Raitweet10
```

To:

```yml
twitter_username: Raitweet10
```

I'd also recommend using `null` after blank keys in YAML, e.g.:

```yml
# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:
```

This could be corrected to:

```yml
# Set this to true to get LaTeX math equation support
use_math: null

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: null
```

Finally, I recommend using some better formatting. So we can use the vertical pipe `|` symbol for wrapping text blocks:

```yml
description: |
  This is where the description of your site will go. You should
  change it by editing the _config.yml file. It can be as long as you like!
  Happy blogging... ❤
```

So your file should look like this:

```yml
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
title: Somasree's blog
description: |
  This is where the description of your site will go. You should
  change it by editing the _config.yml file. It can be as long as you like!
  Happy blogging... ❤
github_username: soma2000-lang

# Email and twitter are optional:
email: seckroll16@gmail.com
twitter_username: Raitweet10

# Set this to true to get LaTeX math equation support
use_math: null

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: null

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
```

Let me know if this works! :)
