### DISCUSSION TITLE
Pull request action not rerun after base branch updated

### DISCUSSION THREAD

**Discussion by padzikm** [community/community#112107] [Actions]
### Select Topic Area

Bug

### Body

Hi, I am using pull request workflow as follows:
```
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:
```
I have two pull requests, both of them passed ci checks. When I merged one pr to main branch I expect other pr to run its workflow again (as it has edited action type - 'The title or body of a pull request was edited, or the base branch of a pull request was changed' according to github docs), but nothing happened - how to fix that?

**Comment by probablynotnmp** [comment]
Double-check your YAML configuration to ensure there are no syntax errors or typos. Make sure that the workflow file is properly placed in the .github/workflows directory and that it's named correctly.

**Reply by padzikm** [reply]
I checked multiple times, pipeline is working as expected, but action type edited is not triggering rerun of pr after main updates. My workflow below:
```
name: Build and test

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:
    
jobs:
  build_and_test:
    name: Build and test
    runs-on: [self-hosted, Linux, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Dotnet version
      run: dotnet --version
    - name: Build
      run: dotnet build
    - name: Unit tests
      run: dotnet test --filter "FullyQualifiedName!~Integration.Tests&FullyQualifiedName!~IntegrationTests"
    - name: Run EventStore.Bi
      run: cd src/EventStore.Bi && ENVIRONMENT=qa dotnet run &
    - name: Integration tests
      run: dotnet test --filter "FullyQualifiedName~Integration.Tests|FullyQualifiedName~IntegrationTests"
```

**Comment by probablynotnmp** [comment]
Maybe GitHub actions might be caching some data related to the workflow run, which could prevent it from being rerun when the main branch is updated. You can try clearing the cache or disabling caching temporarily to see if that resolves the issue.

**Reply by padzikm** [reply]
How to do this in github actions?

**Comment by probablynotnmp** [comment]
You can add a step in your workflow to clear the cache before executing other steps. For example, you can use the cache action provided by GitHub to clear the cache:

```
- name: Clear cache
  uses: actions/cache@v2
  with:
    path: ~/.nuget/packages
    key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
    restore-keys: |
      ${{ runner.os }}-nuget-
```

If clearing the cache doesn't resolve the issue, you can try temporarily disabling caching altogether to see if that affects the behavior of your workflow:

```
# Disable caching
# - uses: actions/cache@v2
#   with:
#     path: ~/.nuget/packages
#     key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
#     restore-keys: |
#       ${{ runner.os }}-nuget-
```
