### DISCUSSION TITLE
Why is my deployment workflow not triggered?

### DISCUSSION THREAD

**Discussion by jakub7722** [community/community#112480] [Actions]
### Select Topic Area

Question

### Body

I created a simple demonstration workflow like this:
```
name: Deploy
on:
  - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'We pretend to deploy to: ${{ github.event.deployment.environment}}'"
```
According to [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment) the workflow should be run:

>Runs your workflow when someone creates a deployment in the workflow's repository.

I created a couple deployments from another workflow using 3rd party action:
<img width="271" alt="image" src="https://github.com/community/community/assets/145353660/df0ae63d-fed8-41b9-9c71-9ef35c43330c">

What am I missing? Why the workflow is not triggered?

<img width="217" alt="image" src="https://github.com/community/community/assets/145353660/962169ad-0fb2-4060-9517-175644dd4805">
