### DISCUSSION TITLE
PR shows a workflow targeted to the other branch (from the other PR) when the source branch is same

### DISCUSSION THREAD

**Discussion by mikhail-prisheltsev** [community/community#112452] [Actions]
### Select Topic Area

Bug

### Body

When I open two PRs from one branch (to dev and to stable), both PRs show me workflows for both targets.

I have two workflows:
```
name: Validate [develop]
on:
  pull_request:
    branches:
      - dev
```
```
name: Validate [stable]
on:
  pull_request:
    branches:
      - stable
```

after creating PRs `branch` -> `dev`, `branch` -> `stable` I expect one workflow to show up in each PR, but I see both workflows on every PR page.
