### DISCUSSION TITLE
Permission to REPO denied to github-actions[bot].

### DISCUSSION THREAD

**Discussion by TheOriginalCER06** [community/community#112552] [Actions] [answered]
### Select Topic Area

Question / Support / Help

### Body

I am trying to sync two repos, with one public not containing secrets, or the commit-log of the private repo.
TheOriginalCER06/WoWs_Stats.git -> The private one 
TheOriginalCER06/WoWs_Stats_Public.git  -> The public one

I have therefore written a github action file, in the Private repo:

```yaml
name: Copy to Public Repo (without secret files)
  
on:
  push:
    branches:
      - main

jobs:
  copy-to-public:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Change to repository directory
        run: cd $GITHUB_WORKSPACE

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git remote set-url origin https://github.com/TheOriginalCER06/WoWs_Stats_Public.git
          echo "Git remote URL set"
      
      - name: Remove existing temp_repo directory
        run: rm -rf temp_repo

      - name: Create temp_repo directory
        run: mkdir temp_repo

      - name: Clone Public Repo
        run: git clone https://github.com/TheOriginalCER06/WoWs_Stats_Public temp_repo
        
      - name: Exclue secrets
        run: rsync -av --exclude 'secret.json' ./ temp_repo/

      - name: Remove .git
        run: rm -rf temp_repo/.git
        
      - name: Change dir to where content is
        run: cd temp_repo
        
      - name: git Commit and Push
        run: |
          git add .
          git commit -m "Copy files from private to public repo"
          git push origin main
```

This gives me an error under "git Commit and Push":
```txt
remote: Permission to TheOriginalCER06/WoWs_Stats_Public.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/TheOriginalCER06/WoWs_Stats_Public.git/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```
This is the only error I get.

In both repos, "Action, General, Workflow permissions" are set to "Read and Write permissions", and the "Allow GitHub Actions to create and approve pull requests" box is ticked.

I'm new to this and I've probably missed something important. Tried to follow help in other similar situations, but none worked.
Thank you!

**Comment by TheOriginalCER06** [comment, marked as answer]
Got it to work.

Fix was changing checkout of repo, and adding a Private Access Token:

```yaml
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: TheOriginalCER06/WoWs_Stats_Public
          token: ${{ secrets.SECRET_PAT }}
```
