### DISCUSSION TITLE
[bug] runs-on a self-hosted runnner bug in workflow_call behavior (queued forever)

### DISCUSSION THREAD

**Discussion by dennybaa** [community/community#11260] [Actions]
**Describe the bug**
Called workflow can not be scheduled on a self-hosted runner.

```
  build:
    name: Build and Push
    needs: [setup]
    runs-on: ${{ fromJSON(needs.setup.outputs.runs-on) }}
```

**Expected behavior**
Runner must be picked up from the caller's workflow organization rather than the organization where the workflow_call repository is located.
