### DISCUSSION TITLE
Per-dependency reviewers and labels

### DISCUSSION THREAD

**Discussion by dipth** [community/community#11291] [Code Security]
Hi!

We run a large monolith Rails application in our company across 4 different teams.
With a Gemfile that contains close to 200 dependencies it has become quite cumbersome to manage dependency updates.
We've been looking into ways that would allow us to specify which dependencies belongs to what team and ensure that Dependabot adds reviewers from the correct teams for all update PRs that it creates.
However, it doesn't appear like there is any way to achieve this?

The closest we've gotten is splitting up our Gemfile into four separate files like this:

Gemfile:
```ruby
%w(team_a team_b team_c team_d).each do |team|
  gemfile = File.join('dependencies', team, 'Gemfile')
  instance_eval File.read(gemfile)
end
```

dependencies/team_a/Gemfile (etc.):
```ruby
source 'https://rubygems.org'

gem 'graphql'
...
```

Then adding a symbolic link in each of those team-folders for `Gemfile.lock` to point to the `Gemfile.lock` in the root of the project.

Then adding separate configuration entries for Dependabot:
.github/dependabot.yml:
```yml
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/dependencies/team_a"
    schedule:
      interval: "daily"
    labels:
      - "Team-A"
    open-pull-requests-limit: 30
    reviewers:
      - "CompanyName/team-a"
  - package-ecosystem: "bundler"
    directory: "/dependencies/team_b"
    schedule:
      interval: "daily"
    labels:
      - "Team-B"
    open-pull-requests-limit: 30
    reviewers:
      - "CompanyName/team-b"
...
```

However when Dependabot runs and creates a PR it removes the symbolic link to `Gemfile.lock` and creates a new `Gemfile.lock` in the sub-directory instead of following the symbolic link and writing the changes in the root `Gemfile.lock`

Is there any way a setup like this could be configured to work or are there any other options that could be used to achieve a similar result, where some specific dependencies are assigned to specific people/teams?
