### DISCUSSION TITLE
parameters in self-hosted runner finished too early

### DISCUSSION THREAD

**Discussion by fokot** [community/community#113170] [Actions]
### Select Topic Area

Question

### Body

Hi we are using self hosted runner and using custom docker image in our action. And for test we are running `sbt` with parameters.

We tried many options how to write the action in run (`|` or `|-` or `>`) e.g.
```
name: cf-tests
on:
  workflow_dispatch:
jobs:
  checkoutAndCompile:
    runs-on: self-hosted
    container:
      image: registry.cf.online/scalabuild:java21
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compilation
      shell: bash
      run: |  
        cat .sbtopts
        sbt test \
          -Ddb.default.url=jdbc:postgresql://127.0.0.1:5439/cf?ApplicationName=cf \
          -Ddb.auth.url=jdbc:postgresql://127.0.0.1:5439/cf?ApplicationName=cfAuth2 \
          -Ddb.reports.url=jdbc:postgresql://127.0.0.1:5439/cf?ApplicationName=cfReports&readOnly=true
```
But all of them ends with weird result, that when it reaches the`sbt` we see not logs from it, only that it was called and next step, stopping the container
```
Stop and remove container: 1728c4516c724f8cbdeb4d823f39397e_registrycloudfarmsonlinescalabuildjava21_8e6139
```
We found an error in runner's logs
```
[2024-03-15 15:08:31Z ERR  TempDirectoryManager] System.IO.IOException: Access to the path '/home/cloudfarms/github-runners/runner-1/_work/_temp/_github_home/.cache/sbt/boot/sbt-launch/1.9.8' is denied.
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.DirectoryInfo.Delete()
   at GitHub.Runner.Sdk.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.TempDirectoryManager.CleanupTempDirectory()
```
So we tough that it is caused by docker rights issue https://github.com/actions/runner/issues/434. 

**But when we removed `-D` parameters parameters and put all of them to an `./sbtopts` file it started to work. Why is that? What are we missing?**

This works:
```
name: cf-tests
on:
  workflow_dispatch:
jobs:
  checkoutAndCompile:
    runs-on: self-hosted
    container:
      image: registry.cf.online/scalabuild:java21
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create .sbtopts
      shell: bash
      run: |
        touch .sbtopts
        echo "-Ddb.default.url=jdbc:postgresql://127.0.0.1:5439/cf?ApplicationName=cf" >> .sbtopts
        echo "-Ddb.auth.url=jdbc:postgresql://127.0.0.1:5439/cf?ApplicationName=cfAuth2" >> .sbtopts
        echo "-Ddb.reports.url=jdbc:postgresql://127.0.0.1:5439/cf?ApplicationName=cfReports&readOnly=true" >> .sbtopts
    - name: Compilation
      shell: bash
      run: |  
        sbt test
```
