### DISCUSSION TITLE
Add option to trigger workflow when the workflow file or it's dependent workflows are modified

### DISCUSSION THREAD

**Discussion by Gussy** [community/community#113467] [Actions]
### Select Topic Area

Product Feedback

### The problem

For all the workflows we create, the below boilerplate almost always needs to be included, so that updating the workflow itself triggers the workflow (to test it before merging).

```yml
on:
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'dir/**'
```

For more complex workflows that rely on multiple composite workflows and calls other workflows, we end up with something verbose like below.
```yml
on:
  pull_request:
    paths:
      - '.github/actions/composite-action-a/**'
      - '.github/actions/composite-action-b/**'
      - '.github/actions/composite-action-c/**'
      - '.github/workflows/sub-workflow-a.yml'
      - '.github/workflows/sub-workflow-b.yml'
      - '.github/workflows/build.yml'
      - 'dir/**'
  push:
    branches:
      - main
    paths:
      - '.github/actions/composite-action-a/**'
      - '.github/actions/composite-action-b/**'
      - '.github/actions/composite-action-c/**'
      - '.github/workflows/sub-workflow-a.yml'
      - '.github/workflows/sub-workflow-b.yml'
      - '.github/workflows/build.yml'
      - 'dir/**'
```

Discovering and tracking these dependancies takes time and is error prone, especially if `sub-workflow-*.yml` call other composite actions themselves.

### Feature Request

Add an `on: workflow_modify` trigger a workflow if it's own `yml` is changed, or any of it's dependent workflow `yml` files change.

For example, to trigger the workflow when it's own `yml` is changed

```yml
on:
  workflow_modify: self
```

Or to trigger the workflow when itself or any dependent `yml` files are changed

```yml
on:
  workflow_modify: all
```
