### DISCUSSION TITLE
Notification Email Code

### DISCUSSION THREAD

**Discussion by Harshbhagwani90** [community/community#113405] [Actions]
### Select Topic Area

Question

### Body

How can I access and customize the default notification code that GitHub sends when a workflow execution is completed, and how can I send these notifications to my team via email.

**Comment by Harshbhagwani90** [comment]
I would be happy to know if any action that uses the same format as that of default notification to send email to team

**Comment by Akash1134** [comment]
Hi @Harshbhagwani90 ,

GitHub does not provide direct access or customization to its default notification code. Notifications for workflow executions are managed through GitHub Actions and are largely driven by the configuration of your workflows and the GitHub settings of the individual users who want to receive these notifications. 

There are two primary ways to notify your team about the completion of GitHub Actions workflows: 

- One is via `Email Notifications` where GitHub automatically sends email notifications about the results of GitHub Actions workflows to users who watch the repository - For this to work you need to ensure your team members are watching the repository and have their notification settings configured appropriately.
- Another way is to send notifications to a team chat tool (like Slack or Teams), you can use a GitHub Action that integrates with these tools. You would need to add this action to your workflow YAML file. An example might be the "action-slack" action for sending notifications to Slack. This would look something like:
   
   ```yaml
   - name: Notify Slack
     if: always()
     uses: 8398a7/action-slack@v3
     with:
       status: ${{ job.status }}
       fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
     env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   ```
  
In this example, you need to add your Slack webhook URL as a secret in your GitHub repository.

The customization of these notifications would depend on the specific third-party tool you're using, and you'd need to check the documentation for the specific GitHub Action that integrates with that tool. You can even use some [marketplace Actions](https://github.com/slackapi/slack-github-action) that works best for your workflow. 

Hope that helps!
