### DISCUSSION TITLE
PR actions are running on GITHUB_REF creating duplication run when 2 PR have same GITHUB_REF.

### DISCUSSION THREAD

**Discussion by creotiv** [community/community#113542] [Pull Requests]
### Select Topic Area

Bug

### Body

This already discussed in a support ticket: 2668847

I have workflow that running on branch close

```
name: Deploy on PR merge
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - stage/*
      - prod/*
```
     
But it runs on PR creation with event from previous pushed PR

Reproduction Steps

1. Create workflow that running on PR closed event
2. Create 2 branches stage, prod from the main and push to remote
3. Create new branch feature from main
4. Do some modification on feature; commit; push to remote
5. Create PR from feature to stage; merge; ACTION WILL RUN
6. Create PR from feature to prod -> Now ACTION ALSO WILL RUN (with data from previous pr)

Here is problem example on my repo
2 PRs from the same tag

1st: https://github.com/MLKittens/flow-test/pull/55
only 3 workflows:
Assigning
Creating Deploy PR
Approval

All is fine.

2nd https://github.com/MLKittens/flow-test/pull/55
3 duplicates and 2 flow on pr close:
Assigning
Assigning
Creating Deploy PR
Creating Deploy PR
Build & Deploy
Approval
Approval
Cleanup on PR close
