### DISCUSSION TITLE
How to get Chrome Web Driver session to start?

### DISCUSSION THREAD

**Discussion by mgerman3** [community/community#113566] [Actions]
### Select Topic Area

Question

### Body

My code executes locally, but it will not open the Chrome web driver when running on GitHub.

I am getting this error: 

Error:  SessionNotCreatedException()
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

My Code to set up the browser in app.py file: 

```
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument("--disable-gpu")
driver = webdriver.Chrome(options=options)
```

My current code in the .github yml file: (I tried to set up the Chrome driver in this yml but cant figure it out. Do I need to make a new yml? If so what would that look like?)

  ```
name: Python application

 
  on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
    workflow_dispatch:
  
  
  permissions:
    contents: read
  
  jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Script
        run: |
          python app.py
```
  

Thank you for the help!
