### DISCUSSION TITLE
a Button "Run Workflow" is not show to my workflow

### DISCUSSION THREAD

**Discussion by tuksaponl** [community/community#113525] [Actions]
### Select Topic Area

Question

### Body

There is my code 

```
name: Build Test

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
```

and why in workflow don't show the button
![image](https://github.com/community/community/assets/163114885/1f48e661-90f1-4a25-b358-18797ce8d785)
