### DISCUSSION TITLE
How do I use my personal access token in github pages (non-react app)

### DISCUSSION THREAD

**Discussion by lavnishhh** [community/community#113791] [Actions]
### Select Topic Area

General

### Body

I'm using a github PAT that is scoped to just "Access public repos" for my profile website, which is to be hosted on github pages. However, github automatically removes generated tokens if it finds a token in a repo. With a bit of resources I came across how one can use environment variables to access keys but all of them are only for apps created in react.

I've currently created a new env for my repo, and added the secret to it, lets say API_KEY. When I call it on my github pages website, it says process is not defined (process.env.API_KEY).

How do I configure a key for a plain JS website?

**Comment by vickkie** [comment]
### If you have .env file like this  You can try to use

GITHUB_TOKEN=your token
GITHUB_USERNAME=your name

```
require("dotenv").config();

const githubToken = process.env.GITHUB_TOKEN;
const githubUsername = process.env.GITHUB_USERNAME;
```




then use it anywhere like- this is example

const headers = {
  Authorization: `Basic ${Buffer.from(`${githubUsername}:${githubToken}`).toString("base64")}`,
};

Or you can try to use it as environment secret

- navigate to the repo settings
- under secrets and variables make a new secret and add the token there giving it a name like  : YOUR_SECRET
and you can use it like e.g
   ```
     github_token: ${{ secrets.YOUR_SECRET }}
   ```
- this can be used also using github workflows

**Reply by lavnishhh** [reply]
So just to make sure we're on the same page, 
![image](https://github.com/community/community/assets/82657384/a37692bd-8c5a-40de-abcc-019905371447)
I've added the secret here, 
However, the browser gives me an error saying that secrets is not defined.
![image](https://github.com/community/community/assets/82657384/61800be8-a8f3-4b00-8c7e-872a8638faaa)

**Reply by vickkie** [reply]
Hey,
Is this error showing after you have deployed to GitHub pages or when you try to run during development using local environment

**Reply by lavnishhh** [reply]
@vickkie this happens once it's deployed. Have I made a mistake adding it to the env secrets maybe? Just to mention: This is a plain HTML CSS JS website. No NPM involved

**Reply by vickkie** [reply]
Oh okay,
If you don't use npm you can use the secret key by using Github workflows

### Create a GitHub Actions Workflow

- Create a new file named  deploy.yml  in your repository at  .github/workflows/deploy.yml.
- inside the deploy.yml have this code
```
name: Deploy to GitHub Pages

on:
 push:
    branches:
      - main

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Replace placeholder with secret
        run: |
          sed -i 's/API_KEY_PLACEHOLDER/${{ secrets.API_GITHUB }}/g' path/to/your/script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
```
- Then in your js, use it this way 
```
const apiKey = 'API_KEY_PLACEHOLDER';

```
- create another branch named gh-pages 
- change your github deploy from using main branch to use the gh-pages like this

## This is an image-starts here
![Pages](https://github.com/community/community/assets/43224578/0a5d68c2-d760-4508-a0da-e09e7485ebce)
## image end here

-  the same way you created the Github personal token secret  before , create another with permissions to deploy workflows, by ticking repo and workfows under its scopes
- Then use it as secrets as you did with the other one, YOU SHOULD HAVE 2 OF THEM HERE, 
- name it GITHUB_TOKEN 

## This is an image-starts here
![How-do-I-use-my-personal-access-token-in-github-pages-non-react-app-·-community-·-Discussion-113791](https://github.com/community/community/assets/43224578/e12666d1-f37a-4dba-bdae-170230e2eeba)
## image end here
- now when you push to main branch it will auto deploy for you...

@lavnishhh  incase of any issue notify...😂 process might seem long but its not
