### DISCUSSION TITLE
String "cast" to boolean causes internal error

### DISCUSSION THREAD

**Discussion by mike-carey** [community/community#11391] [Actions] [answered]
When using a reusable workflow that accepts a boolean input, passing a string variable causes an "Internal error" (`GitHub Actions has encountered an internal error when running your job.`) pointing to `.github:L1`, resulting in the job not to fail or skip, but just not to show up.

Passing a hard coded string results in "Invalid workflow error" (`The workflow is not valid. .github/workflows/boolean-error.yml (Line: 37, Col: 12): Unexpected type of value 'sure', expected type: Boolean.`)

Booleans are already confusing in Github Actions (see https://github.com/actions/runner/issues/1483).  If anything, it would be nice to get a more straightforward error message stating that boolean input received string.

I can submit this as an issue in the runner, but I was not sure if that is where you want this.  That is, is this a bug, feature request, or suggestion?

## Reproducability

Reusable workflow

`.github/workflows/accepts-boolean.yml`:

```yaml
---

name: 'Accepts boolean input'

on:
  workflow_call:
    inputs:
      foo:
        type: boolean
        default: false

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.foo }}
        shell: bash
```

Calling workflow:

```yaml
---

name: 'Uses a reusable workflow with boolean input'

on: [workflow_dispatch]

jobs:
  info:
    name: 'Gather information'
    runs-on: ubuntu-latest
    outputs:
      my-boolean-output: ${{ steps.info.outputs.my-boolean-output }}
    steps:
      - run: echo "::set-output name=my-boolean-output::true"
        shell: bash
        id: info

  success:
    name: 'Properly "casts" the string to boolean'
    needs: info
    uses: ./.github/workflows/accepts-boolean.yml
    with:
      foo: ${{ needs.info.outputs.my-boolean-output == 'true' }}
  
  failure:
    name: 'Incorrectly "casts" the string to boolean'
    needs: info
    uses: ./.github/workflows/accepts-boolean.yml
    with:
      foo: ${{ needs.info.outputs.my-boolean-output }}
```

![image](https://user-images.githubusercontent.com/32496966/153675895-00e4f78a-bb45-4e6a-baca-78bb5d8962e9.png)

References:
  - [Reusable workflow: accepts-boolean.yml](https://github.com/mike-carey/test_repo/blob/main/.github/workflows/accepts-boolean.yml)
  - [Caller workflow: boolean-error.yml](https://github.com/mike-carey/test_repo/blob/main/.github/workflows/boolean-error.yml)
  - [Run](https://github.com/mike-carey/test_repo/actions/runs/1831638921)
