### DISCUSSION TITLE
Expression for array concatenation

### DISCUSSION THREAD

**Discussion by alexbatashev** [community/community#11401] [Actions] [answered]
Currently [documentation](https://docs.github.com/en/actions/learn-github-actions/expressions) features expressions for checking if array contains a value or joining an array into a string, but there's no way to merge two arrays or append a value to an array.

A possible use case is adding more runner labels for reusable workflows, i.e.:
```
on:
  workflow_call:
    inputs:
      os:
         type: string
         default: "Linux"

some_job:
  runs-on: ${{ concat([x64, build], inputs.os) }}
```

This is currently possible with some sort of configuration job dependency, but would be nice if one could do it instantly.
