### DISCUSSION TITLE
`GITHUB_TOKEN` permissions inconsistent between workflow definition and logs

### DISCUSSION THREAD

**Discussion by magmanu** [community/community#114291] [Actions]
### Select Topic Area

Bug

### Body

Hello,

It seems that my `GITHUB_TOKEN` permissions is not working as expected.

I have a feature branch where I'm adding a few missing permissions to the github-token.  
But as you can see, the token permission set on the workflow is different from the permissions listed on `Set up job` logs. The missing permissions are precisely the ones being added by the feature branch.

```yaml
name: Workflow

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: write     # Added by feature branch
  id-token: write   # Added by feature branch

on:
  pull_request_target:
    branches:
    - main
```

Logs:
<img width="346" alt="image" src="https://github.com/community/community/assets/89524998/1d6aa7bb-d450-4b3b-8531-dd09821aae3b">

Because the trigger is `pull_request_target`, I expect the changes take effect "immediately" (meaning, changes don't need to be merged to the default branch).
Am I missing something? The job is running on a self-hosted runner.
