### DISCUSSION TITLE
Some word is considered as secret and is not correctly handled.

### DISCUSSION THREAD

**Discussion by AboubakarKhan14** [community/community#114388] [Actions]
### Select Topic Area

Bug

### Body

As mentionned in the title, the word "**soda**" is considered being a secret and make my github action fail.

So, I am using github action to deploy some containers in my k8.

Here is the beginning of my github action:

```
name: CD
on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service to deploy'
        default: 'soda'
      nb_worker:
        description: 'Number of worker to deploy per service'
        required: true
        default: '5'
      kubeconfiguration:
        required: true
        default: 'KUBECONFIG'

jobs:
    init:
      runs-on: ubuntu-latest
      outputs:
        keydb-name: ${{ steps.keydb-name-compute.outputs.keydb-name }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Format date
          run: echo "date=$(date '+%d%m%Y%H%M%S')" >> $GITHUB_ENV
        - id: keydb-name-compute
          run: echo $(echo "keydb-name=keydb-${{ github.event.inputs.service_name }}-${{ env.date }}" | tr '_' '-') >> $GITHUB_OUTPUT
        - name: Set up Kubectl
          uses: azure/k8s-set-context@v1
          with:
            kubeconfig: ${{ secrets[github.event.inputs.kubeconfiguration] }}
        - name: Create plop namespace if does not exist
          run: kubectl get ns | grep -c "plop" || kubectl create namespace plop
```

During the step `keydb-name-compute`, if I give as parameter `service_name: soda`, here is the result I get:
```
echo $(echo "keydb-name=keydb-***-26032024131858" | tr '_' '-') >> $GITHUB_OUTPUT
```

It seems like the word **soda** is considered as a secret and the keydb-name I built using `service_name`, is not put in the GITHUB_OUTPUT. Then in the next job, when getting the keydb-name, this one is empty.

For any other word, it does not fail and my deploiyment works fine.
Even the word `SODA` (in uppercase) is ok, only `soda` (in lowercase) is making the deployment fail.

I tried several other way, but they all failed.
