### DISCUSSION TITLE
Automatic Action Running

### DISCUSSION THREAD

**Discussion by ghost** [community/community#114474] [Actions] [answered]
### Select Topic Area

Question

### Body

I want to make it so that a GitHub action runs every 20 minutes, I do not understand how to do this so please tell me how I can do this.

**Comment by ste-xx** [comment, marked as answer]
You simply add this on your workflow:
```
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *' #cron expression
``` 
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

A helper for cron expressions:
https://crontab.guru/
