### DISCUSSION TITLE
Workflow_dispatch triggering all jobs despite defining IF statements to run jobs depending on manual input

### DISCUSSION THREAD

**Discussion by aturcott** [community/community#114478] [Actions]
### Select Topic Area

Question

### Body

I'm trying to create an action with four jobs that run the same script but change variables depending on the environment. I have my input choices setup as such:

```yml
workflow_dispatch:
    inputs:
      group:
        description: Group Selection
        type: choice
        options:
          - group_1
          - group_2
        default: group_1
      environment:
        description: Environment Selection
        type: choice
        options:
          - d0
          - t1
          - t2
          - t3
          - t4
          - t5
          - t6
          - p0
          - p3
          - p5
          - p8
        default: d0
```

and then I have my jobs setup as such:

```yml
group_1_nonprod:
    if: contains(github.event.inputs.group, 'group_1') && ( contains(github.event.inputs.environment, 'd') || contains(github.event.inputs.environment, 't'

group_2_nonprod:
    if: contains(github.event.inputs.group, 'group_2') && contains(github.event.inputs.environment, 't')

group_1_prod:
    if: contains(github.event.inputs.group, 'group_1') && contains(github.event.inputs.environment, 'p')

group_2_prod:
    if: contains(github.event.inputs.group, 'group_2') && contains(github.event.inputs.environment, 'p')
```

and when I go to run the job, I select "group_1" and also "d0" so I'm assuming it would run only the first job but it sets up all four jobs to be ran and I'm a little confused about what I'm doing wrong or possibly missing.
