### DISCUSSION TITLE
hostinger hosting

### DISCUSSION THREAD

**Discussion by happytechnovation** [community/community#114475] [Actions]
### Select Topic Area

Question

### Body

i want to host my react to hostinger through each git push

**Comment by imprvhub** [comment]
Hi! @happytechnovation. For react you can use [Netlify](https://www.netlify.com/) - for example i have a repo on github, this repo on github has a git folder on my local machine, each change i push from local goes to github, auto-deploys to netlify. and the domain of hostinger is linked to netlify with nameservers (not dns). -- EXAMPLE:

<img src="https://github.com/community/community/assets/133716241/368c1618-33c5-40eb-a573-300e58c21a2c">

This is from hostinger panel, is linked to netlify project. 
I mean you should first deploy a netlify project with an stantard domain of netlify. and then take care of the linked domains, but then hostinger has nothing to do. Is everything by netlify. Each time you push to a git repo it will auto deploy to the netlify live project and by default, update your hostinger domain (this approach is with static react sites for example), (if you have back end you should separete the back end first) And use vercel for the back end.

IMPORTANT: if you already purchased the hostinger 'host' i would rather use it in another project, and leave this project you want with the domain only, for react apps, with Netlify was my best approach.

If you use IA you can ask the step by step to achieve the link domain between a project deployed in netlify and hostiger with nameservers.

**Comment by developer-sumit** [comment]
I found these solutions for your problem. If you like this then mark it as answered.

1. **Set Up GitHub Actions**: Navigate to your GitHub repository and go to the "Actions" tab. Create a new workflow file (e.g., `.github/workflows/deploy.yml`) to define your deployment workflow.

2. **Define Workflow Steps**: In your workflow file, define the steps needed to deploy your React application to Hostinger. This typically involves installing dependencies, building the application, and deploying it to your hosting environment. You may need to use tools like npm, yarn, or webpack for building, and SSH for deploying.

3. **Add Hostinger Deployment Steps**: Depending on your specific setup, you'll need to add steps to deploy your React application to Hostinger. This may involve SSHing into your hosting server, copying the built files to the appropriate directory, and restarting any necessary services.

Here's a basic example of what your workflow file might look like:

```yaml
name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Add deployment steps here
      # Example deployment using SSH
      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            cd /path/to/your/react/app
            rm -rf *
            cp -r /path/to/your/build/* .
```

4. **Set Up Secrets**: Store sensitive information such as your Hostinger credentials securely as GitHub secrets. These secrets will be used in your workflow to authenticate with Hostinger without exposing your credentials in plain text.

5. **Test Your Workflow**: Before pushing changes to your repository, test your GitHub Actions workflow locally to ensure it works as expected. You can simulate the workflow using tools like act (https://github.com/nektos/act).

6. **Push Changes and Monitor Deployment**: Once you're satisfied with your workflow, push your changes to your GitHub repository. GitHub Actions will automatically trigger the workflow, and you can monitor the deployment process in the Actions tab of your repository.

By setting up this CI/CD pipeline, your React application will be automatically deployed to Hostinger every time you push changes to your Git repository, streamlining the deployment process and ensuring consistent deployments.
