### DISCUSSION TITLE
How to get related reference of reusable workflow inside it?

### DISCUSSION THREAD

**Discussion by sergey-koryshev** [community/community#114697] [Actions] [answered]
### Select Topic Area

Question

### Body

For example I have some reusable workflow `job.yml` in repository `company/my-repo` and I call it like this with reference to `dev` branch:

```yaml
on:
  workflow_dispatch:

jobs:
  job1:
    uses: company/my-repo/.github/workflows/job.yml@dev
```

The question is how to get this reference `dev` inside the reusable workflow? It seems that github's context doesn't have information about it.

I'm asking because I want to checkout repository `company/my-repo` within the reusable workflow with the same reference like here:

```
on:
  workflow_call:

jobs:
  reusable_job1:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout repository of reusable workflow
        uses: actions/checkout@v3
        with:
          repository: company/my-repo
          path: my-repo
          ref: ${{ REUSABLE_WORKFLOW_REF }}
```

**Comment by ste-xx** [comment, marked as answer]
You can add it as input:

```yml
on:
  workflow_dispatch:
    inputs:
      ref: 
        type: string
```

and on the caller side:
```

jobs:
  job1:
    uses: company/my-repo/.github/workflows/job.yml@dev
    with:
      ref: ${{ github.ref }}
```
