### DISCUSSION TITLE
It seems actions tried to run `pnpm build` recursively. How could I fix it?

### DISCUSSION THREAD

**Discussion by s3xysteak** [community/community#114713] [Actions] [answered]
### Select Topic Area

Question

## Quesiton
Here is my directory structure:
```md
- src/
- test/
  - vite/
    - package.json
    - vite.config.ts
- package.json
- build.config.ts
```

When it runs `pnpm build`, it seems she tried to run on `./test/vite/` instead of `.`, here is the log:

```
Error: test/unplugin-lab/vite/vite.config.ts(1,30): error TS2307: Cannot find module 'vite' or its corresponding type declarations.
  ELIFECYCLE  Command failed with exit code 2.
Error: Process completed with exit code 1.
```

You can see the error throwed from `test/unplugin-lab/vite/vite.config.ts`.
However, when I run `pnpm build` locally, it works well. So I do not know how it happened. 

## Details

<details>
<summary>The workflow.yaml</summary>

```yaml

name: build-test

on: [push]

jobs:
  buildTest:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm i

      - run: pnpm build
        working-directory: .
```

</details>

The [repo](https://github.com/s3xysteak/unplugin-export-collector).
