### DISCUSSION TITLE
How do I pass the --build-arg BASE_IMAGE=ubuntu argument for Docker container actions?

### DISCUSSION THREAD

**Discussion by adityashewale** [community/community#115697] [Actions]
### Select Topic Area
Docker container actions arguments passing issue  

### Body
I have tried env and arg but both are not working my action file as shown below.

```
# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - '--build-arg BASE_IMAGE=ubuntu'
```
