### DISCUSSION TITLE
How to retrieve a secret where the secret variable name is stored inside another variable ?

### DISCUSSION THREAD

**Discussion by ppmgitrepo** [community/community#116494] [Actions] [answered]
### Select Topic Area

Not able to derive a Secret value , when the name of the Secret variable is dynamic and not static. 

### Body

example 
Against an Environment multiple secrets would be defined 
DB_APP1_PASSWORD
DB_APP2_PASSWORD 
DB_APP3_PASSWORD 
etc..

Now at runtime I will derive which secret to be used and that secret variable name will be built as a string inside another variable
 
v_secret='DB_APP1_PASSWORD'
or depending on the context it can be 
v_secret='DB_APP2_PASSWORD'

However this is not getting resolved at runtime i.e. I tried various methods of binding.

```
    run: |
      v_secret='DB_APP1_PASSWORD'
      vDB_PASSWORD=${{ secrets[v_secret] }}  # Access secret using constructed expression
      echo "The database password retrieved dynamically is $vDB_PASSWORD"
```
      Note: I understand it will not echo, but the binding itself is not resolving. 
      Any help in the syntax to resolve this would be much appreciated.

**Comment by Gumaan-Mahar** [comment]
In GitHub Actions, you cannot directly reference dynamic variable names like that. Instead, you need to use `env` context and evaluate the dynamic variable name before accessing the secret. Here's how you can do it:

```yaml
name: Retrieve Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set dynamic secret name
        run: echo "SECRET_NAME=DB_APP1_PASSWORD" >> $GITHUB_ENV

      - name: Retrieve secret
        run: |
          v_secret=$SECRET_NAME
          vDB_PASSWORD="${{ secrets[v_secret] }}"
          echo "The database password retrieved dynamically is $vDB_PASSWORD"
```

- The `Set dynamic secret name` step sets the dynamic secret name as an environment variable.
- In the `Retrieve secret` step, we first read the value of `SECRET_NAME` from the environment, then use that to construct the name of the secret variable (`v_secret`). Finally, we use `${{ secrets[v_secret] }}` to retrieve the secret's value.

Make sure to replace `DB_APP1_PASSWORD` with your actual secret names accordingly. This way, you can dynamically fetch secrets based on runtime variables in GitHub Actions.
