### DISCUSSION TITLE
[issue forms]: Control item visibility using selected value.

### DISCUSSION THREAD

**Discussion by naruse666** [community/community#116601] [Projects and Issues]
### Select Topic Area

Question

### Body

For example, when you want to hide irrelevant questions depending on the value selected in a dropdown.

```yaml
body:
  - type: dropdown
    id: os
    attributes:
      label: "What your OS?"
      options:
        - Linux
        - Windows
  - type: markdown
    if: ${{ os.value == "Linux" }}  # like this
    attributes:
      value: "For Linux"
    # ... 
  - type: markdown
    if: ${{ os.value == "Windows" }}
    attributes:
      value: "For Windows"
    # ... 
```

Are there any plans to implement such controls?
Also, where can I get the latest information about issue forms?
