### DISCUSSION TITLE
Error: docker-compose command not found

### DISCUSSION THREAD

**Discussion by sayhiben** [community/community#116610] [Actions] [answered]
### Select Topic Area

Bug

### Body

If you've encountered the error "docker-compose command not found" on or about April 2, 2024, it means you're using the v1 Docker Compose command. 

GitHub deprecated v1, and you need to change the command from, e.g., `docker-compose build` to `docker compose build` (remove the dash)

There are other changes too, and your workflows and scripts might need migrations to v2. Take a look at [the official Docker Compose V2 Migration Guide](https://docs.docker.com/compose/migrate/) for guidance

_In my case_, I discovered that this change occurred when I also had to update my docker-compose.yml files so that each service with a healthcheck used in a `depends_on` had `condition: "service_healthy"`. I'm unsure why this suddenly broke or if it's related, but perhaps the description will help someone. For example, I changed this...

```yaml
services:
  app:
    depends_on:
      - db
  db:
    healthcheck: "..."
```

...into this....

```yaml
services:
  app:
    depends_on:
      db:
        condition: "service_healthy"
  db:
    healthcheck: "..."
```

There is an active discussion thread in the repository where v1 was deprecated on the GitHub Actions Hosted Runners:
https://github.com/actions/runner-images/issues/9557

**Comment by cleor41** [comment]
I've been getting this sporadically today as well. To test that I wasn't going insane (because seemingly nothing changed with the code) - I reran the job with no new commits, submitted commits with comment changes and it seems to pass or fail at random times. I do use docker-compose so that could be the issue. I'll check out the discussion. Thanks for the link!

**Reply by sayhiben** [reply]
Yup. We have [GitHub Actions debug logging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) always enabled wherever we can

It showed that we had a problem with the runner version `20240401.4.0`

Some of our workflows also ran on this previous version, and they passed: `20240324.2.0`

That led us back to seeing if there was anything relevant happening in the actions/runner-images repo. The maintainer [claims there was a deprecation notice posted six months ago](https://github.com/actions/runner-images/issues/9557), but I haven't been able to find it yet

**Comment by ALRubinger** [comment]
Comment of appreciation for this issue and leading us to a fix! 🤘🏻

**Comment by matheusrosmaninho** [comment]
Change `docker-compose` to `docker compose` it's work

**Reply by percebus** [reply]
This worked for me.

**Reply by Khwesten** [reply]
This worked here, too

**Reply by Tanaykmr** [reply]
yeah, idk why it's different on some systems, but this worked for me too

**Reply by kuwabararikuya** [reply]
Thx! This worked for me, too!

**Reply by CarlosEduardoGui** [reply]
Thx!

**Reply by mtahiriqbaldeveloper** [reply]
This worked for me.

**Reply by darkhan-ai** [reply]
Thanks!

**Reply by chnirt** [reply]
Thx!

**Reply by arnoldxt** [reply]
Thanks

**Comment by ChethiyaKD** [comment]
> Change `docker-compose` to `docker compose` it's work

weird, neither `docker-compose` or `docker compose` work for me

 
`docker-compose` => docker-compose: command not found
`docker compose` => docker: 'compose' is not a docker command.

**Reply by ChethiyaKD** [reply]
it was something else. anyone who's experiencing this on AWS EC2, try installing **docker-compose**

```
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose

docker-compose version
```

https://stackoverflow.com/a/72156137/9814969

**Reply by matheusrosmaninho** [reply]
What is the SO version use? 

I using ubuntu-22.04

**Comment by asafdari-boop** [comment, marked as answer]
@sayhiben I could kiss you

**Comment by peachisai** [comment]
I also found the problem since yesterday.

**Comment by ayubkhan-x** [comment]
Thanks

**Comment by percebus** [comment]
Same problem here

```
docker-compose up --abort-on-container-exit
  shell: /usr/bin/bash -e {0}
  env:
    OS: ubuntu-latest
    ARCHITECTURE: x64
    NODE_VERSION: 20.x
    PYTHON_VERSION: [3](https://github.com/percebus/algorithmic-excercises/actions/runs/10229204215/job/28302582894#step:3:3).12.1
    DOCKER_BUILDKIT: 1
    PYRIGHT_PYTHON_FORCE_VERSION: latest
/home/runner/work/_temp/2[4](https://github.com/percebus/algorithmic-excercises/actions/runs/10229204215/job/28302582894#step:3:4)a045e7-0fd9-4100-8ea[5](https://github.com/percebus/algorithmic-excercises/actions/runs/10229204215/job/28302582894#step:3:5)-0459b1be0592.sh: line 1: docker-compose: command not found
```
