### DISCUSSION TITLE
Workflow with "contents:write" still cannot create tag

### DISCUSSION THREAD

**Discussion by pbrisbin** [community/community#116660] [Actions]
### Select Topic Area

Question

### Body

I have an action that is attempting to update the major version tag (`v2`) to point to a release tag (`v2.0.1`). I've copied this workflow from [here](https://github.com/actions/configure-pages/blob/main/.github/workflows/release.yml). My repository is [here](https://github.com/pbrisbin/setup-tool-action), its workflow is [here](https://github.com/pbrisbin/setup-tool-action/blob/main/.github/workflows/release.yml), and an example failure is [here](https://github.com/pbrisbin/setup-tool-action/actions/runs/8540569661/job/23397872838#logs).

The workflow errors with "Resource not accessible by integration"

![](https://files.pbrisbin.com/screenshots/screenshot.1435079.png)

The code that's being run and failing is ultimately,

```js
    await octokitClient.rest.git.updateRef({
      ...context.repo,
      ref: refName,
      sha: sourceTagSHA,
      force: true
    });
```

So this is saying an attempt to update a ref is getting a 403. Googling that gets you **lots** of obvious answers around granting the correct permissions (`contents:write`). But my permissions are 100% correct, as visible here:

![](https://files.pbrisbin.com/screenshots/screenshot.1435190.png)

Even the default token gets read-write as per the repository Settings anyway. And even if I change this to `write-all`, the error still occurs.

There must be something else going on and it's driving my bananas. Something dumb like the tag not really existing (and 404 being presented as 403), or release tags being special, I'm just not sure. Hopefully someone can spot it?

I was able to successfully run `git tag v2 v2.0.1` locally, so I'm relatively confident this should work.

**Comment by pbrisbin** [comment]
Adding: I have no custom Rules or Protected Tags rules in this repository. So it can't be that either.

I do wonder if it's a bug in the new Protected Tags feature though.

**Comment by pbrisbin** [comment]
I replaced the action with an equivalent script to try and help with debugging,

```yaml
      - uses: actions/github-script@v7
        with:
          script: |
            async function run() {
              const {data: tag} = await github.rest.git.getRef({
                ...context.repo,
                ref: "tags/v2.0.1"
              });

              console.log(tag);

              const sha = tag.object.sha;

              console.log(sha);

              const x = await github.rest.git.updateRef({
                ...context.repo,
                ref: "v2",
                sha: sha,
                force: true
              });

              console.log(x);
            }

            await run();
```

Here's the full error that can be seen now:

```
{
  ref: 'refs/tags/v2.0.1',
  node_id: 'REF_kwDOIj7tDrByZWZzL3RhZ3MvdjIuMC4x',
  url: 'https://api.github.com/repos/pbrisbin/setup-tool-action/git/refs/tags/v2.0.1',
  object: {
    sha: '1c65fc0b7646b61f728fe619dfe34de154bb7ed5',
    type: 'commit',
    url: 'https://api.github.com/repos/pbrisbin/setup-tool-action/git/commits/1c65fc0b7646b61f728fe619dfe34de154bb7ed5'
  }
}
1c65fc0b7646b61f728fe619dfe34de154bb7ed5
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:9537:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:15:13)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:25:1)
    at async main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:20) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/pbrisbin/setup-tool-action/git/refs/v2',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 04 Apr 2024 13:30:17 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'contents=write; contents=write,workflows=write',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'E801:5BA6:3C0A875:62855A9:660EAB69',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4991',
      'x-ratelimit-reset': '1712240841',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '9',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/git/refs#update-a-reference'
    }
  },
  request: {
    method: 'PATCH',
    url: 'https://api.github.com/repos/pbrisbin/setup-tool-action/git/refs/v2',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/5.0.1 Node.js/20.8.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"sha":"1c65fc0b7646b61f728fe619dfe34de154bb7ed5","force":true}',
    request: {
      agent: [Agent],
      fetch: [Function: proxyFetch],
      hook: [Function: bound bound register]
    }
  }
}
```

That documentation URL repeats the same advice:

> The token must have at least one of the following permission sets:
>
> - `contents:write`
> - `contents:write` and `workflows:write`

Which, according to the "Setup Job" step this Job indeed has.

```
GITHUB_TOKEN Permissions
  Contents: write
  Metadata: read
```

**Comment by qtips** [comment]
I have the exact same problem. Itworks if I use PAT, but not with GITHUB_TOKEN. 
I am using a reusable workflow on a private repo inside an Enterprise, and the exact same workflow works with all other repos, except one... I cannot find any difference between those repos in the settings. I have tried "resetting" the GITHUB_TOKEN by changing random settings in Settings / Action / General, but with no avail.

**Comment by pbrisbin** [comment]
Sorry for not reporting back, but I eventually discovered that the action of moving a tag from SHA `a` to SHA `b` will 403 if `a..b` contains a change to `.github/workflows`. And that's what was happening to me consistently, because I was working on the release workflow itself while investigating this. I ultimately figured it out by updating the Job to make actual `git tag` and `git push` commands, which gave an informative error about the push being rejected. The API seems to give a generic 403 only.

GitHub never allows bots to change workflows content under any circumstances. This is completely separate from the workflow permissions or repository rules, and there is no way to bypass it. PAT is the only solution.

**Reply by qtips** [reply]
Thanks for sharing! Great tip to debug using git commands. My solution was to do another change that did not change the repo but triggered the workflow. It was good enough for my need.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by piotrdziubczynski** [comment]
If one is looking for a solution. The code below is working for me:
```
# .github/workflows/auto-release.yml

name: Composer file checker, release creator

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   uses: 'actions/checkout@v4'
            -   name: Validate composer.json and composer.lock
                run: composer validate
            -   name: Get version of the project
                id: project-version
                uses: 'euberdeveloper/ga-project-version@main'
                with:
                    package-manager: 'composer'
            -   name: Add release
                uses: 'marvinpinto/action-automatic-releases@latest'
                with:
                    repo_token: "${{ secrets.GITHUB_TOKEN }}"
                    automatic_release_tag: "${{ steps.project-version.outputs.version }}"
                    prerelease: false
                    title: "Version: ${{ steps.project-version.outputs.version }}"
```
