### DISCUSSION TITLE
Fichier YAML du workflow "pages-build-deployment"

### DISCUSSION THREAD

**Discussion by fatouk** [community/community#116743] [Actions]
### Select Topic Area

Question

### Body

Bonjour ,
Aidez moi à trouver ou au moins à comprendre le processus du deploiement githubpages avec le workflow "pages-build-deployment" car dans aucune partie de mon projet je ne vois un fichier .yml le concernant

**Comment by Olayiwolaaa** [comment]
# FRENCH
## Quatre étapes à suivre.

1. **Créez un fichier yaml.**
2. **Définissez les étapes.**
3. **Déclencheur de configuration.**
4. **Tester et déployer.**

❗ voici un échantillon
```yaml
name: Page Build Deployment

on:
   push:
      branches:
         - main # Déclencheur uniquement pour les poussées vers la branche principalejobs:
   deploy:
      runs-on: ubuntu-latest


      steps:
      -   name: Checkout repository
           users: actions/checkout@v2

      -   name: Setup Node.js
           users: actions/setup-node@v1
           with:
              node-version: '14'

      -   name: Install dependencies
           run: npm install

      -   name: Build site
           run: npm run build

      -   name: Deploy to GitHub Pages
           users: peaceiris/actions-gh-pages@v3
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./build
```
# ENGLISH
## Four steps to follow.

1. **Create yaml file.**
2. **Define the steps.**
3. **Setup trigger.**
4. **Test & Deploy.**

❗heres a sample 
```yaml
name: Page Build Deployment

on:
   push:
      branches:
         - main # Trigger only for pushes to the main branch
jobs:
   deploy:
      runs-on: ubuntu-latest


      steps:
      -   name: Checkout repository
           users: actions/checkout@v2

      -   name: Setup Node.js
           users: actions/setup-node@v1
           with:
              node-version: '14'

      -   name: Install dependencies
           run: npm install

      -   name: Build site
           run: npm run build

      -   name: Deploy to GitHub Pages
           users: peaceiris/actions-gh-pages@v3
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./build
```
