### DISCUSSION TITLE
Github Actions Not Working - Jobs Stuck in Queued

### DISCUSSION THREAD

**Discussion by MaverikMinett** [community/community#116711] [Actions]
### Select Topic Area

Question

### Body

Jobs are stuck in queued status. Eventually timeout with the following error:
<img width="1364" alt="image" src="https://github.com/community/community/assets/53910728/81354a1d-8331-4c33-9ecc-2bb0a7e538c8">

When attempting to rerun, no jobs appear in the dialog:
<img width="659" alt="image" src="https://github.com/community/community/assets/53910728/1b3c8c5b-af3b-4296-bab6-c89afc887321">

Workflow definition
```
name: Validate Merge Request

on:
  pull_request:

jobs:
  build:
    name: Build Docker image (run unit tests)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build Docker image (run nnit tests)
        run: docker build . --file apps/agape-website/docker/Dockerfile
```
