### DISCUSSION TITLE
Own action reusability

### DISCUSSION THREAD

**Discussion by aBanhidy** [community/community#116877] [Actions]
### Select Topic Area

Question

### Body

I know, that there a lot of questions and discussion about this topic, and I read them as many I could, but to be honest, I can't reach my goal.
What it would be: I new in GH actions. I have some and some from them could reuse...but I can't..
These actions are not public actions, these are mine and I want to use them in the sam repository.

How I tried:
Action what I want to reuse 
- named: action.yaml
- placed: "my-repo".github/workflows/app_build
- code:
```
name: Build image

on:
    workflow_call: 
        inputs:
            tag:
                description: 'Tag of images'
                default: 'latest'
                required: true
                type: string
            createLatestTag:
                description: 'Create tag: latest too?'
                type: boolean
                required: false
                default: false               

jobs:
    build-app-image:
        runs-on: ubuntu-latest
        steps:
            - name: checkout app source code
              uses: actions/checkout@v4
            
            - name: Build image
              run: docker build -f $GITHUB_WORKSPACE/.build/app/Dockerfile -t app:${{ inputs.tag }} .
            
            - name: tag image
              run: |
                docker tag app:${{ inputs.tag }} ghcr.io/myorg/app:${{ inputs.tag }}
                if [ ${{ inputs.tag}} != "latest" ] && [ ${{ inputs.createLatestTag }} == "true" ]; then
                    docker tag app:${{ inputs.tag }} ghcr.io/myorg/app:latest
                fi

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}              

            - name: Push image to GuitHub package repo
              run: |
                docker push ghcr.io/myorg/app:${{ inputs.tag }}
                if [ ${{ inputs.tag}} != "latest" ] && [ ${{ inputs.createLatestTag }} == "true" ]; then
                    docker push ghcr.io/myorg/app:latest
                fi
```
The action where I want to reuse the action.yaml:
- named: app_build.yaml
- placed: "my-repo".github/workflows/app_build
- code:
```
name: Comon build app

on:
    workflow_dispatch: 
        inputs:
            app_tag:
                description: 'Tag of app images'
                default: 'latest'
                required: true
                type: string
            appCreateLatestTag:
                description: 'Create app tag: latest too?'
                type: boolean
                required: false
                default: false               
           
jobs:
    build-app-image:
        runs-on: latest-ubuntu
        steps:
            - name: checkout app source code
              uses: actions/checkout@v4

            - name: App
              uses: ./.github/workflows/app_build
              with:
                tag: ${{ inputs.tag }}
                createLatestTag: ${{ inputs.createLatestTag }}
```
...and i also tried to on this way:
```
jobs:
    build-app-image:
        runs-on: latest-ubuntu
        steps:
            - name: checkout app source code
              uses: actions/checkout@v4

            - name: App
              uses: ./.github/workflows/app_build
              with:
                tag: ${{ inputs.tag }}
                createLatestTag: ${{ inputs.createLatestTag }}
```
...based on these GH repo:
* [https://github.com/GuillaumeFalourd/poc-github-actions/blob/main/.github/workflows/36-local-action.yml](https://github.com/GuillaumeFalourd/poc-github-actions/blob/main/.github/workflows/36-local-action.yml)
* [https://github.com/GuillaumeFalourd/poc-github-actions/blob/main/.github/workflows/36-local-action.yml](https://github.com/GuillaumeFalourd/poc-github-actions/blob/main/.github/workflows/33-reusable-workflow.yml)

I tried to run without chout action and as you can see with checkout action. The checkout step is fine.
Question: what kind of solution can work - if there is - to reuse my own action from workflow folder or form any subfolder under workflow and named the file like action.yaml or action.yml (but I think it doesn't matter the extension of the file...I mean yaml or yml)

The error message what I got: not found the action.yaml file

I would really appreciate if anybody could help me and provide a working solution, or open my eyes, where I took error.
...and I am sorry, that I've opened a new discussion with this topic, but as I mentioned above, I read s many as I could, but I not find a workable solution :)

Thanks a lot!
