### DISCUSSION TITLE
vite + react + github pages  Main.tsx 404 error occurs after build

### DISCUSSION THREAD

**Discussion by qiuyulc** [community/community#116894] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

```
# 将静态内容部署到 GitHub Pages 的简易工作流程
name: qiuyu

on:
  # 仅在推送到默认分支时运行。
  push:
    branches: ["main"]

  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发的部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 单次部署的工作描述
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: "dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

```
Above is my deploy.yml configuration file, but now there is a problem. It has been successful in git's actions. Here is my actions information.

<img width="1499" alt="image" src="https://github.com/community/community/assets/139320701/6ec9dcd3-0b49-4f95-81ad-2b0f61b00d6b">

This is the configuration information for my pages

<img width="1144" alt="image" src="https://github.com/community/community/assets/139320701/f559e54f-a6ae-47b4-9e8c-5b582a097c80">

But now I can't find main.tsx when I visit https://qiuyulc.github.io/home/. I don't know what caused this. I hope to get help here.

<img width="1305" alt="image" src="https://github.com/community/community/assets/139320701/415bd849-2e0e-400b-a6cc-c410ce9f5919">

Version:
"vite": "^5.1.6"
