### DISCUSSION TITLE
Conditional tag inclusion in `tags` list `docker/build-push-action`

### DISCUSSION THREAD

**Discussion by wopox1337** [community/community#116955] [Actions] [answered]
### Select Topic Area

Question

### Body

```YAML
name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - '.github/workflows/dockerhub-description.yml'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - steam_legacy
          - public
        mod:
          - valve
          - cstrike
          - czero
          - dod
          - gearbox
          - tfc
          - ricochet
          - dmc
        exclude:
          - mod: dod
            branch: steam_legacy
          - mod: gearbox
            branch: steam_legacy
          - mod: tfc
            branch: steam_legacy
          - mod: ricochet
            branch: steam_legacy
          - mod: dmc
            branch: steam_legacy

    env:
      needToPush: ${{ github.ref == 'refs/heads/master' }}

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: docker/setup-buildx-action@v3.2.0

    - name: Log in to Docker Hub
      if: ${{ env.needToPush }}
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ env.needToPush }}
        tags: |
### Here I need to make the `:latest` tag ONLY for the `public` branch. How?
          ${{ vars.DOCKER_USERNAME }}/${{ matrix.mod }}:${{ matrix.branch }} 
        build-args: |
          APPBRANCH=${{ matrix.branch }}
          MOD=${{ matrix.mod }}
        cache-from: type=gha,scope=build-${{ matrix.mod }}-${{ matrix.branch }}
        cache-to: type=gha,mode=max,scope=build-${{ matrix.mod }}-${{ matrix.branch }}
```

**Comment by elitaylor** [comment]
To include the `:latest` tag only for the `public` branch, you can use a conditional statement in the tags list. Here's how you can modify your `tags` section:

tags: |
  ${{ vars.DOCKER_USERNAME }}/${{ matrix.mod }}:${{ matrix.branch }} 
  ${{ env.needToPush && matrix.branch == 'public' ? ':latest' : '' }}

This condition checks if the environment variable `needToPush` is true (meaning it's a push event to the `master` branch) and if the matrix branch is `public`. If both conditions are met, it appends `:latest` to the tag list; otherwise, it appends an empty string. This way, the `:latest` tag will only be included for the `public` branch builds when pushing to Docker Hub.

**Reply by wopox1337** [reply]
> Unexpected symbol: '?'. Located at position 45 within expression: env.needToPush && matrix.branch == 'public' ? ':latest' : ''

**Comment by wopox1337** [comment, marked as answer]
SOLVED
```YAML
- name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ env.needToPush }}
        tags: |
          ${{ vars.DOCKER_USERNAME }}/${{ matrix.mod }}:${{ matrix.branch }}
# Only on `public` branch will be pushed `:latest` tag
          ${{ matrix.branch == 'public' && format('{0}/{1}:latest', vars.DOCKER_USERNAME, matrix.mod) || null}}
        build-args: |
          APPBRANCH=${{ matrix.branch }}
          MOD=${{ matrix.mod }}
        cache-from: type=gha,scope=build-${{ matrix.mod }}-${{ matrix.branch }}
        cache-to: type=gha,mode=max,scope=build-${{ matrix.mod }}-${{ matrix.branch }}
```
