### DISCUSSION TITLE
How do I achieve such a matrix?

### DISCUSSION THREAD

**Discussion by wopox1337** [community/community#116952] [Actions] [answered]
### Select Topic Area

Question

### Body

src: https://github.com/hldsdocker/hlds/blob/b4b8fe4d5419e0946063823433207b2087642a16/.github/workflows/CI.yml

I need to do things differently:
```yaml
valve:
    - public
    - steam_legacy
cstrike:
    - public
    - steam_legacy
czero:
    - public
    - steam_legacy
dod:
    - public
gearbox:
    - public
```

How can I reach a similar result?
