### DISCUSSION TITLE
GH-integrated Dependabot uses the wrong branch

### DISCUSSION THREAD

**Discussion by heoelri** [community/community#11710] [Code Security]
Hi there, we're using the GitHub-integrated dependabot excessively in our GitHub repositories and it works pretty well. We've also created a simple PowerShell script triggered by a GitHub Actions workflow to auto-generate the `dependabot.yml` (see [Automated dependabot configuration in GitHub](https://heyko.medium.com/automated-dependabot-configuration-in-github-bb08e2c6eeeb) for more).

What we're observing from time to time is that dependabot is using the wrong target branch. Here for example the most recent one:

![image](https://user-images.githubusercontent.com/17407022/154648987-930ca5b5-7784-4d17-a4c5-173e8cdefbad.png)

Dependabot is creating a PR against `main`. But the configuration says it should do it against `component-updates`.

```yaml
- package-ecosystem: "docker"
  directory: "/src/app/AlwaysOn.UI"
  schedule:
    interval: "monthly" 
  target-branch: "component-updates" 

- package-ecosystem: "npm"
  directory: "/src/app/AlwaysOn.UI"
  schedule:
    interval: "monthly" 
  target-branch: "component-updates" 
  allow:
  - dependency-type: direct
  - dependency-type: production
```

The log under `Insights` -> `Dependency graph` does not give us any indicators what went wrong, and it says it was executed "3 days ago". The PR though was raised 32 minutes ago. Are there any other log files available helping us to understand the behavior of the GitHub-integrated dependabot? Any advice would be appreciated!

CC: @msimecek
