### DISCUSSION TITLE
GitHub Actions deployment environment context

### DISCUSSION THREAD

**Discussion by br3ndonland** [community/community#118364] [Actions]
### Select Topic Area

Product Feedback

### Body

I've been trying to start using [GitHub Actions deployment environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) but I've been frustrated with some of the limitations.

One limitation is that there doesn't seem to be any [GitHub Actions context](https://docs.github.com/en/actions/learn-github-actions/contexts) available for deployment environments. For example, the name of the deployment environment can only be accessed indirectly, such as in the `inputs` context (`${{ inputs.environment }}`) if the environment is specified with a `workflow_dispatch` manual workflow run.

What if I'm specifying the environment with a different trigger, like a push? Consider the example workflow below, in which I can automatically specify the production environment if the workflow is triggered by a Git tag. I would expect to be able to access the environment context directly with something like `job.environment.name` or `environment.name` but it seems like I can only retrieve it from another context like `inputs` or `needs`.

```yml
name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:
    inputs:
      environment:
        description: GitHub Actions deployment environment
        required: false
        type: environment

jobs:
  set-environment:
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set GitHub Actions deployment environment
        id: set-environment
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }}; then
            environment=${{ inputs.environment }}
          elif ${{ github.ref_type == 'tag' }}; then
            environment="Production"
          else
            environment=""
          fi
          echo "environment=$environment" >>"$GITHUB_OUTPUT"
  get-environment:
    environment: ${{ needs.set-environment.outputs.environment }}
    needs: [set-environment]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo environment name
        run: |
          echo "
          The environment name in the needs context is ${{ needs.set-environment.outputs.environment }}.
          But how do I access the environment context directly from this step?
          "
```

In the [Actions source code](https://github.com/search?q=org%3Aactions+job-environment&type=code), I see a few references to `job-environment` but there doesn't appear to be any context stored on the runner.

Would you consider adding some support for a deployment environment context?
