### DISCUSSION TITLE
gha-runner-scale-set support to read secrets as env variables

### DISCUSSION THREAD

**Discussion by jonny-rimek** [community/community#118411] [Actions]
### Select Topic Area

Product Feedback

### Body

We are currently self-hosting the legacy version of ARC and explored a migration to `gha-runner-scale-set`. We use the Github App for authentication and per the documentation there are [two ways](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#using-a-github-app-for-authentication) and one of them is hard coding the secret in the values.yaml which is not an option for us.

In the legacy version of ARC there is the option to set the configuration for the GitHub App via env vars e.g.

```yaml
env:
  - name: GITHUB_APP_ID
    value: "${github_app_id}"
  - name: GITHUB_APP_INSTALLATION_ID
    value: "${github_app_installation_id}"
  - name: GITHUB_APP_PRIVATE_KEY
    valueFrom:
      secretKeyRef:
        key: PROD_GHA_RUNNER_CONTROLLER_APP_PRIVATE_KEY
        name: prod-gha-runner-controller-app-private-key
        optional: true
```

The way we currently create Kubernetes does not allow to set secrets with multiple values, which is what is consumed by `runner-scale-set`

```
kubectl create secret generic pre-defined-secret \
   --namespace=arc-runners \
   --from-literal=github_app_id=123456 \
   --from-literal=github_app_installation_id=654321 \
   --from-literal=github_app_private_key='-----BEGIN RSA PRIVATE KEY-----********'
```

We'd be willing to contribute the feature to `runner-scale-set`.

I'd love to hear if this is a feature that has any chance of being added or if we should find other solutions.
