### DISCUSSION TITLE
Working directory path

### DISCUSSION THREAD

**Discussion by Nizumzen** [community/community#118464] [Actions]
### Select Topic Area

Question

### Body

This is my first time using Github Actions so bear with me. I made a Github Actions file and obviously failed. The reason was because I had not set the working directory. So my question is as follows:

Does the working directory start at root or should I do a relative path?

So:

repo/repo

Or:

/repo/repo

?

**Comment by jfullstackdev** [comment]
In GitHub Actions, the working directory is relative to the root of your repository. So, you don't need to start with a `/`.

For example, if you have a directory in your repository called `repo`, you would set the working directory like this:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add your commands here
        echo Use a new line for each command
      working-directory: repo
```

In this example, `working-directory: repo` sets the working directory to the `repo` directory at the root of your repository. All commands in the `run` block will be executed in this directory.

If you have a nested directory, you can specify it using a relative path like `repo/subrepo`.
