### DISCUSSION TITLE
Reboot self hosted runner between steps

### DISCUSSION THREAD

**Discussion by nicola-lunghi** [community/community#118421] [Actions]
### Select Topic Area

Question

### Body

Hi,
I have a job that need to:
1. install an updated package on a machine
2. reboot the machine
3. when the machine restart, run some tests.

It is possible to have something like this

```yaml
jobs:
     prepare-test-hosts:
          run-on: my-host-manager-machine
          steps:
               ssh my test host
               update test host
               reboot test host
     run-tests:
          needs: prepare-test-hosts
          run-on: my-test-host
          steps:
               run tests

     cleanup-test-hosts:
          needs: [ prepare-test-hosts, run-tests]
          run-on: my-host-manager-machine
          steps:
               ssh my test host
               ssh remove-software
               reboot test host
```

my question is:
- if in the `prepare-test-hosts` job can I reboot the host that is running the runner for the job2? it will break the pipeline?
- i need to wait in the for the runner to be up again? how to do that?

any other idea? I would like to avoid running the test via ssh as it is very cumbersome (also I need to execute actions inside the tests, like the setup-python action)
