### DISCUSSION TITLE
Docker build action not using cache in third build

### DISCUSSION THREAD

**Discussion by r3ps4J** [community/community#118523] [Actions]
### Select Topic Area

Question

### Body

Hi there!

I've set up a workflow for one of my docker images to build and push the image to ghcr. I'm using a multi-stage docker image, and have set up caching. Now for the first two stages the caching works fine, but for the third (and largest) stage it doesn't. Since this is the largest stage in my dockerfile it clogs up the pipeline, even though this stage will probably not change often and thus the pipeline is constantly rebuilding the same image. Does anyone know what is going wrong here and how I might fix it? Any help would be appreciated!

The repository in question is https://github.com/r3ps4J/steamcmd-yolk and this is the workflow, "Docker - Build / Push (Proton)" is the build that doesn't seem to use the cache:
```yml
---
name: Developer image
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker - GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: type=raw,value=dev
          flavor: latest=false

      - name: Docker - Metadata (Root)
        id: meta_root
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: type=raw,value=root-dev
          flavor: latest=false

      - name: Docker - Metadata (Proton)
        id: meta_proton
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: type=raw,value=proton-dev
          flavor: latest=false

      - name: Docker - Build / Push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          target: container
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker - Build / Push (Root)
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          target: container-root
          push: true
          tags: ${{ steps.meta_root.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker - Build / Push (Proton)
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          target: container-proton
          push: true
          tags: ${{ steps.meta_proton.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
