### DISCUSSION TITLE
[gha-runner-scale-set-controller] add ServiceMonitor for metrics in helm chart

### DISCUSSION THREAD

**Discussion by lucasfcnunes** [community/community#118627] [Actions] [answered]
### Select Topic Area

Feature

### Body

# Description

On https://github.com/actions/actions-runner-controller/blob/d3a8a34bb22ed8c9d1c91b6047854366bedad1bf/charts/gha-runner-scale-set-controller/values.yaml#L84-L93

```yaml
metrics:
  enabled: true       << NEW
  serviceMonitor:     << NEW
    enabled: true     << NEW
  # ...
  controllerManagerAddr: :8080
  listenerAddr: :8080
  listenerEndpoint: /metrics
```

# References

- https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-service-metrics.yaml
- https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-servicemonitor.yaml
