### DISCUSSION TITLE
GitHub action for publishing ruby gems shows root directory is empty

### DISCUSSION THREAD

**Discussion by endormi** [community/community#118669] [Actions]
### Select Topic Area

Question

### Body

I have created this `test-and-publish.yaml` file:

```yaml
name: Test and Publish

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

# Test works as intended

  publish:
    # needs: test
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push' && success()
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby for publishing
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          ruby-version: '2.7'

      - name: List Dir Contents
        run: |
          echo $PWD
          ls -l
  
      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build csm.gemspec
          # gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build csm.gemspec
          # gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

```

Changing working-directory also shows total 0 of files:

```yaml
- name: Change dir and list Dir contents
        working-directory: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}
          echo $PWD
          ls -l
```

The issue is not me having the files on root. Here is the repository: https://github.com/endormi/csm .

I've set manually the gem build `csm.gemspec`, but it's still trying to build the file `csm.gemspec.gemspec` for some reason. 

Problem branch in my repository: https://github.com/endormi/csm/tree/GH_Action_fixes

What do I need to do to get this working? I'm wondering why publish shows total 0 and yet tests work as intended so the files exist. Somehow publish just fails, any thoughts?
