### DISCUSSION TITLE
Workflow's pull_request 'branches' not working properly

### DISCUSSION THREAD

**Discussion by Nic-Scopely** [community/community#118623] [Actions]
### Select Topic Area

Question

### Body

I have a workflow that is running when it shouldn't. According to the documentation I've read it doesn't make sense as to how it's possible.

I have a pull request targeting a branch named `main`, which is not listed as one of the branches for my workflow.

Here's the relevant portion of the workflow:

```
name: Require Relevant Reviewers

on:
  pull_request:
    types:
      [opened, reopened, edited, synchronize, labeled, unlabeled]
    branches:      
      - 'releases/**'
      - 'develop'
   pull_request_review:
    types: [submitted, edited]

jobs:
  required_reviewers:
    if: >-
      ${{ (contains(github.event.pull_request.base.ref, 'releases/') || github.event.pull_request.base.ref == 'develop') }}
```

In the image below you can see the pull request, which is targeting `main`, a branch that's not listed in the workflow. 

<img width="594" alt="image (2)" src="https://github.com/community/community/assets/59617791/f6e1c57c-765d-4095-bfb1-77cb9695ab4a">

In this next image you can see that the workflow ran anyway during the `pull_request` event, but it skipped the same workflow during the `pull_request_review` event. The head branch, however, does match the name of a branch where the workflow would run. But according to GitHub's documentation, the branches listed for a `pull_request` event correspond with the base branch (target branch), and not the head branch (source branch). Also, as you can see in the workflow snippet above, I have a conditional where it checks the base branch name, and it still passed that condition somehow as well during the `pull_request` event, but not during the `pull_request_review` event, where it shows that the check was skipped.

<img width="812" alt="Screenshot 2024-04-10 at 5 09 09 PM" src="https://github.com/community/community/assets/59617791/c21f128a-1f3d-415d-97ab-ab7166be555c">

For the condition to pass during `pull_request` but fail during `pull_request_review`, that suggests that the base branch name was different in each case. If that's the case it would explain why the `branches` I listed under `pull_request` failed to work. But this behavior seems like a bug in GitHub's actions, if true.
