### DISCUSSION TITLE
Issue with pull_request event

### DISCUSSION THREAD

**Discussion by igor725** [community/community#118706] [Actions]
### Select Topic Area

Bug

### Body

My action uses `pull_request:synchronize` event with specific paths to trigger, but it looks like the `synchronize` event ignores all these rules.

My action trigger rules:
```yml
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '.github/workflows/build.yml'
      - '**/CMakeLists.txt'
      - 'CMakeLists.txt'
      - '**.cmake'
      - '**.cpp'
      - '**.cxx'
      - '**.cc'
      - '**.c'
      - '**.hpp'
      - '**.hh'
      - '**.h'

  push:
    paths:
      - '.github/workflows/build.yml'
      - '**/CMakeLists.txt'
      - 'CMakeLists.txt'
      - '**.cmake'
      - '**.cpp'
      - '**.cxx'
      - '**.cc'
      - '**.c'
      - '**.hpp'
      - '**.hh'
      - '**.h'
```

This action just got triggered by pushing subsequent commit to already opened PR, this commit contains some `js` file alone which is clearly not on the list. Also I noticed that the action got triggered on main repo inside pull request, but my fork did not triggered it, just as expected.
