### DISCUSSION TITLE
find command not working with wildcards in GitHub Actions

### DISCUSSION THREAD

**Discussion by kathyrollo** [community/community#118759] [Actions]
### Select Topic Area

Bug

### Body

As part of our workflow, we have a `dot-upload.sh` script that has the `find` command in it. Due to the sensitive nature of the script, I am unable to post it in its entirety, but I can confirm this the only line that uses the `find` command:

```
FILE_NAMES=$(find $1)
```

The relative path to the downloaded files is passed as argument to the script:

```
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4

  - name: Download API unit test results
    uses: actions/download-artifact@v4
    with:
      name: unit-test-results-api
      path: test-results/unit-test-results-api/

  - name: Where Am I
    run: pwd

  - name: Upload API unit test results to DoT
    run: ./scripts/dot-upload.sh test-results/unit-test-results-api/test-results.xml
    shell: bash

  - name: Download UI unit test results
    uses: actions/download-artifact@v4
    with:
      name: unit-test-results-ui
      path: test-results/unit-test-results-ui/

  - name: Where Am I
    run: pwd

  - name: Upload UI unit test results to DoT
    run: ./scripts/dot-upload.sh test-results/unit-test-results-ui/**/*.xml
    shell: bash
```

When the relative path including the file name is passed, the `find` command works and returns the matching file:

![Screenshot 2024-04-12 000805](https://github.com/community/community/assets/28589393/1b59c3a6-c2d5-4229-8c0b-d7eff39548dd)

However, when wildcards `/**/` are used to return files in nested dirs, the `find` command says `No such file or directory`:

![Screenshot 2024-04-12 000649](https://github.com/community/community/assets/28589393/207eaa62-5a0d-45eb-a982-3667fe8deb61)

I noticed that when _globbing_ is involved, single quotes are suddenly added around the args, which is probably making the path invalid:

```
++ find 'test-results/unit-test-results-ui/**/*.xml'
find: ‘test-results/unit-test-results-ui/**/*.xml’: No such file or directory
```

Neither the script nor the YAML has single quotes in them.

Would like to know if this is a bug? And if not, what would be the correct way to pass the args without GitHub Actions adding the unwanted single quotes?
