### DISCUSSION TITLE
Workflow improperly validate PRs that do not run some tests

### DISCUSSION THREAD

**Discussion by NathanEckert** [community/community#118708] [Pull Requests]
### Select Topic Area

Bug

### Body

We started to have spotted that some of our PR were merged without running any test (on CircleCI).
It seems to be a bug of GitHub

We do have a `PULL_REQUEST_TEMPLATE.md`:

```
### CI Checklist

- [ ] Enforce Code Style Rules <!-- enforced-style -->
- [ ] Run Jira Check <!-- jira-check-exec -->
- [ ] **Run Tests** <!-- run-tests-exec -->
- [ ] Run Sonar <!-- run-sonar -->
```

The idea is that once the PR is ready to merge, one has to tick all the box to trigger all the checks and merge if the CI is green;

We also have a `pr-steps-checker.yml`:

```yml
name: Pull Request Steps Checker
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  ...
  Step-approval:
    name: Approve PR checks
    needs: Runner-steps
    runs-on: ubuntu-latest
    if: ${{ needs.Runner-steps.outputs.all-checked == 'true' }}
    steps:
      - run: echo "Good job mate!"
        shell: bash
```

Unfortunately, this allows the PR to be merged, even with unticked box.

## Example PR

https://github.com/activeviam/activepivot/pull/9916

![image](https://github.com/community/community/assets/111350203/f5102bb1-80d3-44aa-a33b-d61ba764836e)

![image](https://github.com/community/community/assets/111350203/077b4bd2-f8c5-490e-a462-1f15a8b00075)
