### DISCUSSION TITLE
Cancel auto merge if required Job is skipped

### DISCUSSION THREAD

**Discussion by oerp-odoo** [community/community#118802] [Actions] [answered]
### Select Topic Area

Question

### Body

I have added required job that must pass for auto merge to trigger. Though because I have matrix of jobs (where number of jobs to be run can be different), its very clunky to specify matrix jobs as required.
So instead I created "aggregate" job that basically waits for those matrix jobs and it is run if all of those jobs pass. In success scenario it works correctly. In failure, it works only correctly, that no other job after is run. 

But the problem here is that "aggregate" job is skipped if previous job failed, yet auto merge is still triggered. 

Is this expected behavior? Cause I would expect auto merge to not trigger if required job was skipped?

Setup looks like this:

```yaml
  odoo:
    needs: [versions]
    if: ${{ needs.versions.outputs.names_comma != '' }}
    strategy:
      fail-fast: false
      matrix:
        version: "${{ fromJSON( needs.versions.outputs.names_json ) }}"
    uses: ./.github/workflows/_odoo.yml
    with:
      version: ${{ matrix.version }}
    secrets: inherit # pragma: allowlist secret

  # This is a dummy job, to just wait for all tests to pass. This way
  # we can specify single required status check instead of needing to
  # specify all projects.
  test_aggregate:
    needs: odoo
    runs-on: [self-hosted, pool]
    steps:
      - name: Pass
        run: echo "Tests Passed"
```

So if `odoo` jobs fail, `test_aggregate` will not run (which is expected), but auto merge will still trigger, even if `test_aggregate` is added in required jobs.

You can see it in this graph:
![Selection_1161](https://github.com/community/community/assets/7812986/837d4de1-57eb-4305-b0c9-763f5e2738a7)

**Comment by oerp-odoo** [comment, marked as answer]
Went with extra job that explicitly forces failure. Though that job must be always run (both of those jobs are set as required via status checks):

```yaml
  # This is a dummy job, to just wait for all tests to pass. This way
  # we can specify single required status check instead of needing to
  # specify all projects (which is kind of dynamic).
  test_aggregate_success:
    runs-on: [self-hosted, pool]
    needs: odoo
    steps:
      - name: Pass
        run: echo "Tests Passed"
  test_aggregate_fail:
    runs-on: [self-hosted, pool]
    needs: odoo
    if: |
      always() &&
      contains(needs.*.result, 'failure') ||
      contains(needs.*.result, 'cancelled')
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Previous jobs failed or were cancelled. Forcing failure')
```
