### DISCUSSION TITLE
workflow_dispatch stops working if workflow has 2 or more schedules

### DISCUSSION THREAD

**Discussion by mike-gorman-quest** [community/community#118918] [Actions]
I have a workflow that is set to run on a schedule _or_ manually kicked off like this, and it works just fine:

```
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * 1-5"
```

But if I provide an additional schedule, `workflow_dispatch` stops working:

```
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * 1-5"
    - cron: "0 * * * 0,6"
```

By "stops working" I mean the "Run workflow" button still appears and still says "Workflow run was successfully requested" but the workflow never runs.
