### DISCUSSION TITLE
Add way to specify 'id' of checkbox to avoid http 400 ERROR.

### DISCUSSION THREAD

**Discussion by anatawa12** [community/community#11949] [Projects and Issues]
Currently, the issue form is not friendly with East-Asian Languages such as Chinese and Japanese because if there's no latin characters in checkbox label, the GitHub will return 400/500 error.

Also, if there's two or more checkboxes with labels without latin character, clicking label of 2nd/later checkbox will check first checkbox.

It looks because the id of each checkbox will be generated based on only latin characters in label.
If the label doesn't have latin characters, the id of checkbox will be empty string and
- the GitHub server will deny empty id checkbox
- the id of checkbox (<input type=checkbox>) will be duplicated.

To avoid this problem, I want github to support specifying 'id' on checkbox.

```
body:
  - type: checkboxes
    attributes:
      options:
        - label: ラテン文字を持たないチェックボックス
          id: box1 # <========== I want this
```
