### DISCUSSION TITLE
Actions stopped working according to schedule

### DISCUSSION THREAD

**Discussion by zakerikk** [community/community#119603] [Actions]
### Select Topic Area

Bug

### Body

Hi,

What happened to github actions schedule?

For April 14, it didn't work or ran only once per hour instead of every 5 minutes, for example:

https://github.com/zakerikk/actions-check/blob/master/.github/workflows/check.yml
https://github.com/zakerikk/actions-check/actions

![ci runs](https://github.com/community/community/assets/97627521/c7d2f28c-9a83-4cc0-b5e6-9f804fb67d0b)

![image](https://github.com/community/community/assets/97627521/847b696c-25bd-4113-8609-c3bba3979891)

The status page says all is good with Actions, but I don't agree with that

**Comment by lbenz730** [comment]
I am having the same issues with my jobs scheduling as well. Not running as scheduled or massive (6+ hour) delays. Glad to hear I am not alone.

**Comment by zakerikk** [comment]
with this setup:
```
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' 
```

Actions were supposed to run 28 times, but they only ran once
![image](https://github.com/community/community/assets/97627521/b7cd03db-289f-4e8c-9fe0-3896677787a7)

**Comment by lbenz730** [comment]
With this setup, this has yet to be scheduled in almost 3 hours.

```
name: hello-world
on:
  schedule:
    - cron: "* * 15 * *"
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
```
![Screenshot 2024-04-14 at 10 28 31 PM](https://github.com/community/community/assets/21962947/153bedef-ab85-424c-b6a9-a14cdd618ce2)

https://github.com/lbenz730/fantasy_baseball/actions/workflows/hello_world.yml
