### DISCUSSION TITLE
Cannot combine calling reusable workflow with variables from a deployment environment.

### DISCUSSION THREAD

**Discussion by brookpatten** [community/community#119632] [Actions]
### Select Topic Area

Bug

### Body

If I attempt to call a reusable workflow from a job which has an `environment` set, I receive the error `The workflow is not valid <workflow file> (Line,Col): Unexpected value 'uses' <workflow file> (Line, Col): Unexpected value 'with'`

As an example, Consider the following simple reusable workflow is in a repo by itself, in the same org.  It is an internal repo and "Access": "Accessible from repositories in <same org> organization
```
name: reusable workflow
on:
  workflow_call:
      inputs:
          foo_input:
             required: true
             type: string
jobs:
  foo_job:
    name: foo_job
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.foo_input }}
```

And the following calling workflow, from a different repo in the same org.  This repo has an environment called "dev" and in that environment a variable defined bar.

```
name: Calling Workflow
on:
  push:
    branches:
      - main

jobs:
 call_foo:
    environment: dev
    uses: <org>/<reusable workflow repo>/.github/workflows/reusable.yml@main
    with:
      foo_input: ${{vars.bar}}
```

This will yield the error above on `with`, "Unexpected value 'with'".

This seems like a bug, why cant I not pass variables from my environment to a reusable workflow?

There is a similar, but different, issue here: https://github.com/orgs/community/discussions/110873, although manifesting differently since it is using the repo value not the environment value.
