### DISCUSSION TITLE
How to Convert Sample GitHub Action Job into a Reusable Function with Matrix Strategy?

### DISCUSSION THREAD

**Discussion by vrathore18** [community/community#119668] [Actions]
### Select Topic Area

Question

### Body

I'm trying to refactor my GitHub Actions workflow to make it more maintainable and reusable. Specifically, I want to convert a sample job into a reusable function and call it from my main workflow. However, I'm struggling to understand how to incorporate a matrix strategy with a reusable workflow.

Here's the sample job that I'm attempting to refactor:

```
  test:
    name: test-(${{ matrix.shard }}/${{ strategy.job-total }})
    strategy:
      matrix:
        shard: [1, 2, 3]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [test-1]
    if: |
      always() && (needs.test-1.result == 'success')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '16.x'
      - name: Set Env variable
        env:
          CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
        run: |
          echo "CURRENTS_PROJECT_ID=$CURRENTS_PROJECT_ID" >> $GITHUB_ENV
          echo "CURRENTS_RECORD_KEY=$CURRENTS_RECORD_KEY" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm install --prefix src/automation-test/
      - name: Install Playwright
        run: cd src/automation-test/; npx playwright@1.31.2 install chromium
      - name: Run Playwright
        run: cd src/automation-test/ ; command="npx playwright test --shard=${{ matrix.shard }}/${{ strategy.job-total }}  ./test" ; $command || $command
      - uses: actions/upload-artifact@v3.1.1
        if: always()
        with:
          name: playwright-test-results-projects-${{ matrix.shard }}_${{ strategy.job-total }}
          path: src/automation-test/test-results/
```

I've reviewed the GitHub documentation(https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow) on reusing workflows and matrix strategies, but I'm still unclear on how to implement this effectively. Can anyone provide guidance on how to achieve this? Any help would be greatly appreciated!
