### DISCUSSION TITLE
# Gitpage  deploy by actions, error with upload artifacts

### DISCUSSION THREAD

**Discussion by TheoppoFish** [community/community#119768] [Actions]
### Select Topic Area

Question

### Body

Hi team,

I have tried with a self-hosted gha runner.

the gha workflow is copy/paste from the vitepress guidance, [here](https://vitepress.dev/zh/guide/deploy#github-pages)

Unfortunately, I failed at the `Upload artifact ` stage
![image](https://github.com/community/community/assets/102744674/24536eb8-d48c-4b49-a703-a2c28cb5d3fb)

here is my workflow:

```yaml
name: Deploy VitePress site to git pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm install
      - name: Build with VitePress
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: self-hosted
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


```
