### DISCUSSION TITLE
Actions log output does not render OSC 8 hyperlinks

### DISCUSSION THREAD

**Discussion by mjperrone** [community/community#119709] [Actions]
### Select Topic Area

Bug

### Body

When you do this in a terminal:

```
printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'
```

the output (in modern terminals) is a clickable link:

![Screenshot 2024-04-15 at 11 07 57 AM](https://github.com/community/community/assets/3848371/541b91a8-1da7-4cee-a1aa-7526788f342e)

However when you do the same thing in the context of a github action:

```yaml
on: ['push']
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'
```

This is what it outputs:
```
Run printf '\e]8;;[http://example.com\e\\This](http://example.com/e//This) is a link\e]8;;\e\\\n'
  printf '\e]8;;[http://example.com\e\\This](http://example.com/e//This) is a link\e]8;;\e\\\n'
  shell: /usr/bin/bash -e {0}
]8;;[http://example.com\This](http://example.com%1B/This) is a link]8;;\
```

![Screenshot 2024-04-15 at 11 11 57 AM](https://github.com/community/community/assets/3848371/008fbfae-b4e6-4852-b76f-32be45100414)

I would prefer that it render the link in the same way that modern terminals do.

See [this](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) gist for more details on the standard.
