### DISCUSSION TITLE
How to ignore actions based on file changes when either making a forked PR or pushing changes to your forked repo during a PR

### DISCUSSION THREAD

**Discussion by Pakman450** [community/community#119716] [Actions]
I have this workflow below:

```
name: Compilation and Test Suite

on:
  push:
    branches: [ "master","beta_branch","alpha_branch" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "master","beta_branch","alpha_branch" ]
    paths:
      - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: configure gnu
      run: cd ./install && ./configure gnu

    - name: make install
      run: cd ./install && make install

    - name: make test
      run: cd ./install && make test
```

When I make a forked PR with an equivalent branch (let's say `alpha_branch`) and pushing file changes to my forked branch (during a PR) to another folder let say `docs` (NOT `src`). This workflow is STILL triggering the workflow. 

What am I doing wrong? I tried looking at the github documentation, and there were two different keywords I could have used `paths-ignore` and `paths`, but I tried both of these and it won't work
