### DISCUSSION TITLE
Matrix: how to Cartesian-product the include with the other variables

### DISCUSSION THREAD

**Discussion by Pr0methean** [community/community#119723] [Actions]
### Select Topic Area

Question

### Body

For https://github.com/Pr0methean/zip-next/actions/runs/8696381767, I defined the following matrix:
```
jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
        - rustalias: stable
          rust: stable
        - rustalias: msrv
          rust: '1.70'
        - rustalias: nightly
          rust: nightly
    name: Build and test (${{ matrix.os }}, ${{ matrix.rustalias }})
```
I expected this to produce 9 `build-and-test` jobs, but it only produces 3 (the ones that use `nightly`). I got the same results with a dummy-variable workaround to make the variable sets overlap:
```
jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        singleton: [1]
        include:
        - singleton: 1
          rustalias: stable
          rust: stable
        - singleton: 1
          rustalias: msrv
          rust: '1.70'
        - singleton: 1
          rustalias: nightly
          rust: nightly
    name: Build and test (${{ matrix.os }}, ${{ matrix.rustalias }})
```
How do I fix this so that `build-and-test` generates 9 jobs, and the ones that use Rust 1.70 have `msrv` rather than `1.70` in their names so that I can include them forward-compatibly as PR required checks in my ruleset?

**Comment by Pr0methean** [comment]
Update: I finally got this working by copying one of the variables from the `include` list into the parent `matrix` tag, like so:
```
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rustalias: [stable, nightly, msrv]
        include:
        - rustalias: stable
          rust: stable
        - rustalias: msrv
          rust: '1.70'
        - rustalias: nightly
          rust: nightly
    name: 'Build and test: ${{ matrix.os }}, ${{ matrix.rustalias }}'
```
But the fact that `include` can't increase the total number of workflows really needs to be documented somewhere!
