### DISCUSSION TITLE
help using actions for deploy

### DISCUSSION THREAD

**Discussion by YaronPeres** [community/community#119991] [Actions] [answered]
Hi all!
I have been trying to use actions to push the files from my main branch to deploy branch. the branch is used in Hostinger to deploy the website and i need only the files of the dist folder. 
if somone has any idea if it possible or has other idea how to do it. this is what i have until now but i always get errors in the copy or push of the files. 
name: Update deploy branch with dist folder contents

on:
  push:
    branches:
      - main

jobs:
  update-deploy-branch:
    runs-on: ubuntu-latest
    name: Update deploy branch with dist folder contents
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install all dependencies
        run: npm install

      - name: Generate a build
        run: npm run build

      - name: Checkout deploy branch
        run: git checkout deploy

      - name: Copy dist folder from main to deploy branch
        run: |
          git checkout main -- dist/*
          git add .
          git commit -m "Update deploy branch with dist folder contents"
          git push origin deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
thanks.

**Comment by sule26** [comment, marked as answer]
Try this:

https://github.com/peaceiris/actions-gh-pages

```yaml
name: Update deploy branch with dist folder contents

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory
    branches:
    - main # Only trigger on the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: deploy
```
