### DISCUSSION TITLE
workflow_dispatch inputs -  max length, number of inputs, default values...

### DISCUSSION THREAD

**Discussion by lmajer999** [community/community#120093] [Actions]
### Select Topic Area

Question

### Body

Hi, im doing research for my company whether github actions are suitable for our usecase and so far I was able to accomplish everything we need (run docker, checkout repo, build projects inside docker, push / export,...), except one limiting and irritating detail - input variables...
we want to start workflow manually with several variables and one of them should be some kind of token - in our case the token is too long - when used in workflow, its length is limited to 1024 characters.. is there any way to specify min/max length? another good feature would be option to specify default values and regex validation... and from what I have just read while looking for answer, also the number of inputs is limited to 10... is there any workaround for any of these things? Can someone please explain to me the reason for these limitations? 

Example of what I would love to achieve:
```
on:
  workflow_dispatch:
    inputs:
      token:
        description: 'token'
        type: string
        max-length: 10000
        regex: '^ABC.*XYZ$'
```
