### DISCUSSION TITLE
`enqueued` pull request type not working as expected (pre-merge hook)

### DISCUSSION THREAD

**Discussion by polyphilz** [community/community#120115] [Actions]
### Select Topic Area

Question

### Body

I have a dummy GitHub Action:

```
name: CI

on:
  pull_request:
    types: [enqueued]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "i am a pr"
        if: github.event_name == 'pull_request'

      - run: echo "i am a merge group"
        if: github.event_name == 'merge_group'

      - run: sleep 20

      - run: exit 1
```

...that I'm using to test out merge queues.

The intended behavior I'm trying to get is that for a given PR, when a user adds it to the merge queue, only then does this specific action run. The reason for that is because the action I'm trying to run will be resource-intensive and I don't want it to run on every commit to a PR; just right before merge. If this action fails, then the merge should be blocked.

However, what's actually happening is that the PR successfully gets merged while the `sleep 20` is still running.

Any ideas on what I'm doing wrong here?
