### DISCUSSION TITLE
Disable job output

### DISCUSSION THREAD

**Discussion by triple3567** [community/community#120152] [Actions]
### Select Topic Area

Question

### Body

Is there a way to disable a GitHub actions workflow job's output entirely? I know that the "::add-mask::" function exists, but I would like to mask the entire output of a job. We just need to know if the job passes or fails.

**Comment by yakir1992** [comment]
Hey,


To disable the output of a GitHub Actions workflow job entirely, you can use the echo command with the ::add-mask:: function to mask the entire output. Here's how you can do it in your workflow YAML file:
```
jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Your step
        run: |
          echo "Your command output"
          echo "::add-mask::Your command output"
``` 
Replace "Your command output" with the actual command or script output you want to mask. This will mask the entire output of the command, so only the fact that the command ran (indicating whether it passed or failed) will be visible in the job logs.

**Reply by triple3567** [reply]
This solution has its limitations. I had to set the output of my script to a environment variable, then use the ::add-mask:: function on that variable.

```
jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Your step
        run: |
          OUTPUT=$(./my-script.sh)
          echo "::add-mask::$OUTPUT"
```

However, if your command/script has multiple lines of output, this solution will only mask the first line of output. For example if my-script.sh looked like:

```
#!/bin/bash
echo "1"
echo "2"
echo "3"
```

Only the first line of output would be masked by the above solution. This means that "2" and "3" will show up on GitHub's job output. 

One workaround to this is to redirect all output to /dev/null, resulting in a script that will only send pass or fail to GitHub. This means the workflow yaml file would look something like:

```
jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Your step
        run: |
          ./my-script.sh > /dev/null 2>&1
```
