### DISCUSSION TITLE
Question about disabling Actions for Draft PRs and charges

### DISCUSSION THREAD

**Discussion by rmincling** [community/community#120231] [Actions]
### Select Topic Area

Question

### Body

Hi all,

So we have the setup below for a github action/workflow. It skips this job when the PR is a draft. Which is great. However, as the git workflow/action is still being activated, even if it only takes a few seconds, are we still getting changed for the partial minute?

As on here [Git Billing](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions) it states "GitHub rounds the minutes and partial minutes each job uses up to the nearest whole minute."

If that is the case, then is there anywhere else on an account level perhaps that will allow us to disable actions completely on draft PRs, without incurring any charges?

Any advice/thoughts are much appreciated,

Regards

Rob

```
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
      - development
    paths:
      - 'react-app/**/*.js'
      - 'react-app/**/*.ts'
      - 'react-app/**/*.tsx'

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: React Build
    runs-on: ubuntu-22.04
```

**Comment by GunaPalanivel** [comment]
Hello Rob,

Great question regarding GitHub Actions billing, especially as it pertains to draft pull requests.

Given your current setup where the workflow is triggered but the job is skipped for draft PRs, GitHub will still initiate the runner, and this brief period counts towards billing. As per GitHub's billing policy, each job's runtime rounds up to the nearest whole minute. This means even a few seconds spent initiating a job will be counted as one minute.

Unfortunately, GitHub does not provide a built-in feature at the account level to completely disable actions for draft PRs. However, there are a couple of strategies you can consider to manage this situation more efficiently and possibly reduce costs:

1. **Modify Workflow Triggers**: You could potentially adjust the triggers for your workflows to limit the number of times they run. One approach could be to trigger the workflows only when draft PRs are marked as "ready for review" rather than on every update until that point. Here’s how you could adjust the `on` trigger:
    ```yaml
    on:
      pull_request:
        types: [ready_for_review]
        branches:
          - master
          - development
        paths:
          - 'react-app/**/*.js'
          - 'react-app/**/*.ts'
          - 'react-app/**/*.tsx'
    ```
    This change ensures that the workflow is triggered only when a draft PR is moved out of draft status, thereby reducing the number of runs.

2. **External Control with GitHub API**: Implement a custom script that checks the status of the PR before triggering the workflow. You can use GitHub API to check if the PR is a draft and make API calls to enable/disable workflow runs accordingly. This approach requires additional tools or scripts but offers more control.

3. **Manual Intervention**: If the workflows do not need to run frequently, another approach could be to trigger them manually. This way, you can ensure that they run only when necessary:
    ```yaml
    on:
      workflow_dispatch:
    ```
    This allows you to trigger jobs manually from the GitHub UI when you decide it's needed, such as after moving a PR out of draft status.

4. **Condensed Workflow Runs**: Consider batching or merging jobs where feasible so that fewer workflow runs are necessary. This can reduce the total number of workflow minutes used.

While none of these solutions disables actions entirely without any initiation, they can help manage and reduce unnecessary runs, aligning your usage more closely with your needs and potentially reducing costs.

If none of these solutions fit, I recommend reaching out to GitHub support or consulting the GitHub community forums for more tailored advice or updates on potential feature implementations that could help in the future.
