### DISCUSSION TITLE
Private networking for GitHub-hosted runners

### DISCUSSION THREAD

**Discussion by stan-spotts** [community/community#120785] [Actions] [answered]
### Select Topic Area

Question

### Body

We are looking at containerizing a set of node.js API's (uses loopback.io) that were developed sitting on a VM. I wanted to automate deployment to a container registry first, and it has to be private per our security guidelines. I was going to use a self-hosted runner, but then saw the article [Configuring private networking for GitHub-hosted runners in your organization](https://docs.github.com/en/organizations/managing-organization-settings/configuring-private-networking-for-github-hosted-runners-in-your-organization). Having just migrated our GitHub account from a personal pro plan to an organization team plan, I thought wow, this looks promising.

I followed the instructions, mostly - I already had a resource group and a VLAN set up with a container registry, so the only real thing I changed was I didn't create a VNET and update the subnet info, I just created the subnet.  So this subnet is in the same VLAN as the registry (in a different subnet). But I created the service principal, set the rbac role, etc., got the networking config in GitHub set up, created the runner group. Happy happy!

Except it won't connect.  I put a step in to log what runner group the workflow used, and it was the one I just created.

On the docker/login-action@v3 action, I get this in the log:

```
Run docker/login-action@v3
  with:
    registry: ***
    username: ***
    password: ***
    ecr: auto
    logout: true
Logging into ***...
Error: Error response from daemon: Get "https://***/v[2](https://github.com/myOrg/myrepo/actions/runs/8791394220/job/24125517103#step:6:2)/": denied: client with IP '20.44.102.[3](https://github.com/myOrg/myrepo/actions/runs/8791394220/job/24125517103#step:6:3)6' is not allowed access. Refer https://aka.ms/acr/firewall to grant access.
```

I went in with the Cloud CLI and used docker commands to login and connect to the container registry with the clientId and secret of the service principal, same as what is in the repo secrets that the workflow references.

I'm not trying to access anything on our on-premise network, so I didn't think I needed to deal with ExpressRoute or VPN Gateway or anything. But what's the trick here?

**Comment by david-wei-01001** [comment]
The issue you're experiencing with the GitHub-hosted runner not being able to connect to your private container registry seems to be related to network security settings. Specifically, the error message indicating that the client with a certain IP is not allowed access suggests that the IP address of the GitHub-hosted runner is not whitelisted in your container registry's firewall settings.

Here are the steps you can take to resolve this issue:

### 1. **Verify IP Whitelisting in the Container Registry**
Since the error is related to IP access denial, check if the IP range of the GitHub-hosted runners is allowed in the firewall settings of your container registry. GitHub-hosted runners use a range of IPs that can change over time.

- **Azure Container Registry (ACR)**: If you are using ACR, you'll need to add the IP range of GitHub actions to your ACR's firewall exceptions. GitHub provides the IP ranges used by GitHub-hosted runners in their documentation, but these ranges can change. You can programmatically retrieve the current IPs used by GitHub Actions [from this JSON endpoint](https://api.github.com/meta) under the `actions` key.

### 2. **Update Firewall Rules**
Add the necessary IP range to your ACR firewall settings. This is typically done in the Azure portal:
   - Navigate to your ACR resource.
   - Go to the **Networking** section.
   - Under **Firewall and virtual networks**, ensure that you have the correct settings that include the IP ranges for GitHub Actions.

### 3. **Use Conditional Access Policies**
If updating IP ranges frequently is not ideal, consider using more dynamic conditional access policies if supported by your cloud provider.

### 4. **Testing Connectivity**
After updating the firewall rules, manually trigger the workflow to ensure that the connectivity issue is resolved. Verify that the runner can now successfully log in to the container registry.

### 5. **Consider Using Self-Hosted Runners**
If using GitHub-hosted runners introduces too much complexity with IP whitelisting due to their dynamic nature, you might reconsider using a self-hosted runner, especially since you've mentioned it was your initial plan. Self-hosted runners can operate within a stable IP range defined by your existing network, which simplifies firewall configurations:
   - Configure the self-hosted runner in your existing VLAN where the container registry is also hosted.
   - Ensure that the network security settings allow traffic between the runner and the registry.

### 6. **Security Best Practices**
Ensure that any changes to firewall settings or network configurations adhere to your organization's security policies. It's important to maintain the principle of least privilege, allowing only necessary traffic between services.

### 7. **Documentation and Monitoring**
Finally, document any changes made during this process for future reference and set up monitoring on both the GitHub Actions workflows and the container registry to quickly identify and respond to any further access issues.

By following these steps, you should be able to resolve the connectivity issues between your GitHub-hosted runners and your private container registry.

**Reply by stan-spotts** [reply]
Thanks for that response! I am indeed using Azure Container Registry. I checked the results of the json endpoint you supplied and it got back over 3600 IP ranges. Certainly this isn't an answer considering one has to enter them one at a time, although I'm sure I could script that.  I didn't see a way to set a conditional access policy for an IP range (just an account). I did see a policy "Configure Container registries with private endpoints" that I didn't use, I set it up per the instructions on the link in the original post.

What I'm not grokking is that I thought the IP whitelisting and firewall ranges are for **public** access. And what this solution was supposed to do was use **private** network access. The whole reason I went down this path was to see if I could deploy from GitHub to a private IP without having to set up a self-hosted runner, which I'm already doing for other code. I can see under the Networking section for the Azure Container Registry, under the Private access tab, it has the connection and private endpoint I created, and has the data endpoint. So Why is it trying to go over public IP?

**Reply by david-wei-01001** [reply]
The problem you're encountering with the GitHub-hosted runners trying to access your Azure Container Registry (ACR) seems to be a misconfiguration or misunderstanding of the network settings, especially in terms of how GitHub Actions interacts with Azure's private networking capabilities.

Here are a few points and steps to consider to address your concerns:

1. **Understanding GitHub-hosted Runners and Private Networking**:
   - GitHub-hosted runners typically connect over the public internet, even when interacting with private resources, unless specifically configured to use something like a self-hosted gateway (e.g., a VPN or ExpressRoute). The feature for configuring private networking for GitHub-hosted runners in your organization primarily relies on setting up network controls to restrict where runners can connect but doesn't inherently change their public internet-based nature.

2. **Review Azure Private Link Configuration**:
   - Azure Private Link provides a way to access Azure services (like ACR) privately from your Azure Virtual Network (VNet). When properly set up, it ensures that the traffic to the Azure service travels over the Azure backbone network rather than the public internet.
   - Check if your Azure Private Link setup for ACR is correctly configured to allow access from the subnet where your GitHub Actions runners are expected to operate (if possible within the GitHub-hosted context).

3. **Check Service Endpoints**:
   - Ensure that the service endpoints or private endpoints are correctly configured within your VNet and that your ACR is linked to these endpoints.
   - Verify whether the GitHub Actions are set up to interact via these private links rather than directly over the internet.

4. **IP Whitelisting vs. Private Access**:
   - Although you have set up private networking components, your error suggests that GitHub Actions runners are still attempting to access the ACR over the internet (hence the IP whitelisting error).
   - Revisit your network configuration in GitHub and Azure to ensure that any declaration meant to redirect GitHub Actions through a private network path is active and correctly configured.

5. **Review GitHub Actions Network Configuration**:
   - Double-check the network configuration settings you applied in GitHub to make sure they are supposed to route traffic through your private network setups. If GitHub Actions are not configured to use private endpoints explicitly or through some form of routing control, they will default to public internet access routes.

6. **Alternative Solutions**:
   - **Self-Hosted Runners**: Given the complexities and limitations with IP whitelisting and the dynamic nature of GitHub-hosted runners’ IPs, using self-hosted runners might be more appropriate. They can be configured within your Azure VNet and will have stable, predictable IPs that can be easily managed within your network security settings.
   - **Automation Scripting**: If you choose to continue using GitHub-hosted runners and need to update IP whitelists frequently, consider automating the IP updates using scripts that fetch the latest IPs from GitHub’s endpoint and update the ACR firewall settings accordingly.

7. **Consult Azure/GitHub Support**:
   - If the setup still fails to operate as expected, consider reaching out to Azure or GitHub support. There might be specific settings or configurations unique to your environment that require professional guidance.

By revisiting these configurations and potentially adjusting your approach (e.g., opting for self-hosted runners), you should be able to achieve a more reliable and secure deployment process for your containerized Node.js APIs.

**Reply by stan-spotts** [reply]
Thanks, this is all interesting. Unfortunately, I'm still having a mental block :). I can't set up a private link because that requires setting up a load balancer, and I can't create a load balancer because I can't add a frontend IP configuration that references the subnet that is already configured through subnet delegation (Delegate subnet to a service) to Github.Network/networkSettings.  In the frontend IP configuration, the subnet is grayed out and not selectable. This may be part of #3 in your last response, as it's was done specifically (per the documentation I referenced) so I could use private endpoints.

In case I neglected something important in my description.  The workflow did start, and did get past a pre-login azure/login@v1 step then the actions/checkout@main, then the login with azure/login@v1. It's the docker/login-action@v3 action that failed. 

```
on: 
    workflow_dispatch:
    #[push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                runner-group: 
                  - "githubazure"

        steps:
        - name: Log Runner Group
          run: |
            echo "Runner group used: ${{ matrix.runner-group }}"

        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

          # fails on this step with the IP address not allowed error
        - name: 'Build and push image'
          uses: docker/login-action@v3
          with:
            registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/myRepo:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/myRepo:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/myRepo:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: myRepo
            location: 'east us'
```
I was thinking more about what you wrote about whitelisting, and wanted to know what your thoughts were on the documentation here;
https://docs.github.com/en/organizations/managing-organization-settings/configuring-private-networking-for-github-hosted-runners-in-your-organization

Specifically, the bicep file it says to save as actions-nsg-deployment.bicep. There are two NSG definitions with outbound rules defined. Is this where the whitelisted ip ranges you wrote about should be? I would have thought I'd need inbound rules. 

I'm sorry that these questions seem like they're all over the place, but I'm trying to wrap my head around following the documentation in the link above and updating my own documentation about what it doesn't say that has to be configured, which you've been so nicely writing about.  I think the documentation may need additional info in the "prerequisites" area based on what you're telling me.
