### DISCUSSION TITLE
Enhancement: Named schedules

### DISCUSSION THREAD

**Discussion by heoga** [community/community#120768] [Actions]
### Select Topic Area

Product Feedback

### Body

The documentation for the schedule triggers suggests the following to enable / disable steps depending on the schedule being triggered.

```yaml
on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"

```

This has a problem where if a schedule needs to be changed, so that it runs on Sunday instead of Monday for example, the user must run through the pipeline and update every instance of the if statement to match.

My suggestion is that we follow the established precendent within github actions and allow schedules to be named the same as a job or a step.  This could then be referred to in the logic to make the system more robust.

For example:

```yaml
on:
  schedule:
    - cron: '30 5 * * 1,3'
      name: short
    - cron: '30 5 * * 2,4'
      name: long

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule.name != 'short'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"

```
