### DISCUSSION TITLE
How to pass input to on.release.published event?

### DISCUSSION THREAD

**Discussion by JayDarjiAubergine** [community/community#120815] [Actions] [answered]
### Select Topic Area

Question

### Body

```
name: Deploy
run-name: Running Deploy on ${{ github.event.inputs.environment }}  // input I get from below workflow_dispatch event
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        type: choice
        default: 'staging'
        options:
          - 'staging'
          - 'production'
```
Here we are accessing this environment selection from `${{ github.event.inputs.environment }}`.

![Screenshot from 2024-04-23 11-57-21](https://github.com/community/community/assets/82358087/f38799f5-2921-438d-8572-c9cf1c05c2be)

This looks good when we use manual action dispatch from Github.

But then we want to run this workflow automatically when we publish a release, so I added this:
```
on:
  release:
    types: [ published ]
```
which is fine, but here it won't be able to select environment, which we need default `production` in our case.

Any idea how we can do this?

**Comment by mickeygousset** [comment]
You can't pass parameters in on that event. 

You could create an environment variable in the workflow and default it to "production", as an option, potentially.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by JayDarjiAubergine** [comment, marked as answer]
The workaround we used for this is:

We created another action **deploy_on_release.yml** with this snippet:

**deploy_on_release.yml**
```
name: Deploy to production
on:
  release:
    types: [ released ]    // Previously, it was published, but we changed it to released to only trigger workflow for actual release and to avoid pre-release tags

jobs:
  release-deployment:
    name: Release Deployment
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: "production"
```

where in the `deploy.yml` file, looks like this:

**deploy.yml**
```
name: Deploy
run-name: Running Deploy on ${{ github.event.inputs.environment }}  // input I get from below workflow_dispatch event
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        type: choice
        default: 'staging'
        options:
          - 'staging'
          - 'production'
```

Hope this helps to someone who will face a similar situation in the future.
Happy DevOpsing :)
