### DISCUSSION TITLE
issue/template: render error

### DISCUSSION THREAD

**Discussion by oldme-git** [community/community#120926] [Projects and Issues]
### Select Topic Area

Bug

### Feature Area

Issues

### Body

If it contains the following code in `.github/ISSUE_TEAMPLATE/xxx.yaml`:
```
  - type: dropdown
    id: is-reproducible
    attributes:
      label: Can this bug be reproduced with the latest release?
      options:
        - Yes
        - No
    validations:
      required: true
```
It will not show on github page,. If I add `Option` before `Yes` and `No`, it will work normally. like this:
```
  - type: dropdown
    id: is-reproducible
    attributes:
      label: Can this bug be reproduced with the latest release?
      options:
        - Option Yes
        - Option No
    validations:
      required: true
```

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
