### DISCUSSION TITLE
How to launch only one build job for two push actions

### DISCUSSION THREAD

**Discussion by nicola-lunghi** [community/community#121115] [Actions]
### Select Topic Area

Question

### Body

Hi I have an action that is triggered by two events:

```yaml
name: CI
on:
  push:
    branches:
      - "master"
    tags:
      - "releases/**"
  pull_request:
    branches:
      - "master"
```
The problem is if I want to create a releases/myrelease tag, I usually push to master, then push the tag.
This causes two build for every release.
As the build is quite heavy, there's a way to prioritize the build on the releases branch cancelling the one on master with the same commit sha??

Thanks,
Nick
