### DISCUSSION TITLE
wait for job to complete even when cancelled, but only if previous job has succeeded

### DISCUSSION THREAD

**Discussion by mgood7123** [community/community#121186] [Actions]
### Select Topic Area

General

### Body

would
```yaml
if: ${{ success() && always() }} # if we cancel during the upload, wait for it to complete
```
work as intended ?

we intend to complete any uploads in the event of a cancelled job (eg, concurrent/manually) as to avoid any partial/corrupted uploads

for example, an upload that has been interrupted by a job cancellation due to another job starting concurrently would yield in a corrupted upload as follows

![image](https://github.com/community/community/assets/26642847/5403e1be-4996-423c-a6ba-c93f5a5309d5)

a complete upload would have splits 0 to 5 as follows

![image](https://github.com/community/community/assets/26642847/72a6ef32-e2dd-4947-802f-2c10913c57a6)

**Comment by mgood7123** [comment]
we also intend to chain this, for example
```yaml
      - name: archive ccache directory
        if: success() # if we cancel during the upload, wait for it to complete
        run: |
          export MSYS=winsymlinks:native

          # 750 mb
          #
          ./split_exe/split.exe --split -r ccache_llvm --name ccache_llvm --size 750000000

      - name: list files
        if: success() # if we cancel during the upload, wait for it to complete
        run: |
          ls -l

      - name: upload ccache directory
        if: success() # if we cancel during the upload, wait for it to complete
        uses: "ncipollo/release-action@v1"
        with:
          name: "llvm stage ${{ matrix.llvm_stage }} - windows msys2 msys2_prebuilt_bootstrap - llvm - RELEASE"
          tag: "storage--llvm-stage-${{ matrix.llvm_stage }}--windows-msys2-msys2_prebuilt_bootstrap_llvm--release"
          makeLatest: true
          generateReleaseNotes: false
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          removeArtifacts: true
          artifacts: |
            ./ccache_llvm.split.*
```

this would run the steps
```yaml
      - name: archive ccache directory
      - name: list files
      - name: upload ccache directory
```

if the previous step before `- name: archive ccache directory` has succeeded, `even if cancelled`

more specifically
if the previous step before `- name: archive ccache directory` has succeeded
and we then get cancelled
we must wait for the steps
`- name: archive ccache directory`, `- name: list files`, and `- name: upload ccache directory`
to complete before actually cancelling the job/workflow
