### DISCUSSION TITLE
The workflow is requesting 'id-token: write', but is only allowed 'id-token: none'.

### DISCUSSION THREAD

**Discussion by riosje** [community/community#121112] [Actions] [answered]
### Select Topic Area

Bug

## OIDC Auth not working due to workflow permission issue

I have the following [pipeline](https://github.com/RafaelGSS/nodejs-bench-operations/blob/addnodesourcerunner/.github/workflows/bench.yml) but is not running due to an error with the permissions.

I found in other posts this issue is related to Fork repos and re-usable workflows, but this is not the case.

```yaml
permissions:
  issues: write
  contents: read
  id-token: write

jobs:
  runner-start:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Start Runner
        uses: ./.github/workflows/runner-starter
        with:
          instance_id: ${{ secrets.INSTANCE_ID }}
          action: 'start'
```

ERROR
```LOG
The workflow is not valid. .github/workflows/run_all.yml (Line: 20, Col: 3): Error calling workflow 'RafaelGSS/nodejs-bench-operations/.github/workflows/bench.yml@d8c16de8267c83507f97db7553f5c3e57c87e96a'. The workflow is requesting 'id-token: write', but is only allowed 'id-token: none'.
```

## Github Actions permissions config

![image](https://github.com/community/community/assets/55195249/4baba509-5c73-4515-abd9-59532fb1a07b)

![image](https://github.com/community/community/assets/55195249/4cc2137f-4086-44b5-918e-8ebcc85dbf51)

Thank you for your advice here to solve this issue.
