### DISCUSSION TITLE
Why is the no artifacts to publish using upload-artifact@v4?

### DISCUSSION THREAD

**Discussion by Rod-at-DOH** [community/community#121255] [Actions]
### Select Topic Area

Question

### Body

I'm still a newbie, when it comes to GitHub (GH) Actions. I've got a GH Self-hosted Runner on a Windows Server 2022. I'm trying to get a workflow working on an old .NET Framework 4.5.2 solution, with 9 projects and 3-unit tests projects. So, ignoring the unit tests projects, since they aren't a part of the distribution, I've discovered that the upload of artifacts to a folder on a server doesn't work, because it cannot find any artifacts where I thought they would be. I'm sure the problem is a misunderstanding on my part, so I ask that someone please show me how my thinking is wrong. Here's a snippet from my YAML:

```
    # Try to create the folder for the artifacts
    - name: Create path for artifacts
      shell: powershell 
      run: mkdir 'TimeTrackSite\bin\Release\Publish'
    
    - name: Build and Publish
      run: msbuild $env:Solution_Name /p:Configuration=Release /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=FP_Timetrack\FP_Timetrack\TimeTrackSite\bin\Release\Publish/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: publish_webapp
          path: FP_Timetrack\FP_Timetrack\TimeTrackSite\bin\Release\Publish/
          overwrite: true 
```

After running the workflow I've remoted to the self-hosted runner server and went to the `FP_Timetrack\FP_Timetrack\TimeTrackSite\bin\Release\Publish` folder. It is empty. I don't understand why it is empty.
