### DISCUSSION TITLE
add on.pull_request_target.paths-all

### DISCUSSION THREAD

**Discussion by janosh** [community/community#12144] [Actions]
The current [`on.<push|pull_request|pull_request_target>.<paths|paths-ignore>`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) conditions don't allow not triggering a workflow unless _only_ a certain file or file type changed. For `pull_request_target` workflows with access to repo secrets in particular, it is often helpful to only allow it to run if only safely loaded data files like JSON or YAML are changed and source files remain unchanged.

I suggest adding a new `on.pull_request_target.paths-all` condition where all diffed paths must match the given patterns or the workflow won't run. E.g.

```yml
on:
  pull_request_target:
    branches: [main]
    paths-all:
      - **/*.yml
      - **/*.json
      - **/*.md
```

would not trigger if any file with an extension other than `.(yml|json|md)` changed.
