### DISCUSSION TITLE
Why is GHA ignoring one of my action checks?

### DISCUSSION THREAD

**Discussion by ericpromislow** [community/community#121581] [Actions]
### Select Topic Area

Bug

### Body

It's an open-source project -- you can see the problem at https://github.com/rancher/wrangler/pull/423

I added 2 new checks to `.github/workflows` from a fork and created a PR to add them (this is ok, I'm a member of the target repository). The `ci.yaml` is always loaded. It has a strategy.matrix with two architectures, and they're both loaded.

The lint.yaml check is almost always ignored. The "almost" is because I created a file called "lint2.yaml" with the same structure and different names, and it ran. But when I even renamed it to `lint.yaml` and fixed the names, it stopped getting picked up.

Are there some magic names that don't work?  Here's the start of `lint.yaml`:

```
name: golint

on:
  push:
  pull_request:
    tags:
      - v*
    branches:
      - 'release/*'
      - 'master'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      # https://github.com/actions/checkout/releases/tag/v4.1.1
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: recursive
```
