### DISCUSSION TITLE
Create webjob uploadable zip file from GitHub Action

### DISCUSSION THREAD

**Discussion by dileepainivossl** [community/community#121617] [Actions]
### Select Topic Area

Question

### Body

I'm trying to automate the deployment of a WebJob using GitHub Actions. I aim to generate a deployable zip file for the WebJob directly from the GitHub Action workflow.

```ts
name: WebJob deployment Zip file

on:
  push:
    branches: ['develop', 'qa', 'feature/tn-972_employee-bulk-upload']

env:
  PROJECT_LOCATION: 'src/infrastructure/web-jobs/employee-bulk-upload'
  WEBJOB_OUTPUT: 'employee-bulk-upload'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore './${{ env.PROJECT_LOCATION }}/employee-upload.sln'

      - name: Build
        run: dotnet build './${{ env.PROJECT_LOCATION }}/employee-upload.sln' -c Release --no-restore

      - name: Publish
        run: dotnet publish './${{ env.PROJECT_LOCATION }}/employee-upload.sln' -c Release --no-build --output './${{ env.PROJECT_LOCATION }}/publish'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webjob-zip-deploy
          path: 'src/infrastructure/web-jobs/employee-bulk-upload/publish'

```

This is my existing GitHub action. It uploads an artefact, but when uploading it as a web job, it fails.

![image](https://github.com/community/community/assets/124654997/895c2072-1878-481d-81d0-e2514e8b7bb2)

But I manually zip the files inside the `src\infrastructure\web-jobs\employee-bulk-upload\bin\Release\net8.0`. This path web job works.

**Comment by Adnan25z** [comment]
Add a step to install zip on the runner, if it's not already available. This is necessary because Ubuntu runners might not have zip installed by default.

Add a step to zip the output directory after the publish step. You mentioned that manually zipping the files in the bin\Release\net8.0 directory works for you. Thus, ensure that the directory being zipped in the GitHub Actions workflow corresponds to the one that works when done manually.

Update the artifact upload step to use the zip file you created.

I have made the change below let me know if it works.
```
name: WebJob deployment Zip file

on:
  push:
    branches: ['develop', 'qa', 'feature/tn-972_employee-bulk-upload']

env:
  PROJECT_LOCATION: 'src/infrastructure/web-jobs/employee-bulk-upload'
  WEBJOB_OUTPUT: 'employee-bulk-upload'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore './${{ env.PROJECT_LOCATION }}/employee-upload.sln'

      - name: Build
        run: dotnet build './${{ env.PROJECT_LOCATION }}/employee-upload.sln' -c Release --no-restore

      - name: Publish
        run: dotnet publish './${{ env.PROJECT_LOCATION }}/employee-upload.sln' -c Release --no-build --output './${{ env.PROJECT_LOCATION }}/publish'

      - name: Install Zip
        run: sudo apt-get install zip

      - name: Zip the WebJob
        run: |
          cd '${{ env.PROJECT_LOCATION }}/publish'
          zip -r '../${{ env.WEBJOB_OUTPUT }}.zip' .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webjob-zip-deploy
          path: '${{ env.PROJECT_LOCATION }}/${{ env.WEBJOB_OUTPUT }}.zip'
```
