### DISCUSSION TITLE
Select with operating systems to run on

### DISCUSSION THREAD

**Discussion by nlisker** [community/community#121755] [Actions]
### Select Topic Area

Question

### Body

Normally I run a job on all platforms:

```yml
jobs:
  package:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
  ...
```

Sometimes I need to run the workflow for just one of the matrix option, for example, if there's a problem only with the macos job and I need to only run that one over and over during debugging. I tried to use a choice input like this:
```yml
on:
  workflow_dispatch:
    inputs:
      os:
        description: "Operating System"
        required: true
        type: choice
        options:
          - windows
          - macos
          - ubuntu
          - ubuntu, windows, macos

jobs:
  package:
    strategy:
      matrix:
        os: "${{ github.event.inputs.os }}"
    runs-on: ${{ matrix.os }}-latest
  ...
```

This works for each OS individually, but for the combination, it reads the input as one string, `"ubuntu, windows, macos"` instead of a list and fails.

I thought about changing the input type from choice to 3 booleans, 1 for each OS. This way I can select any combination of OS's to create the matrix from, but I couldn't construct the matrix easily either (I saw solutions that echo the string and then read it as a json list).

I have to think that this is not an unusual requirement, but I couldn't find a way of doing it. Perhaps I'm completely off. The only other solution I cam up with is to create 2 workflows, one with the choice and one with the matrix.
