### DISCUSSION TITLE
Se ejecuta manualmente pero no en automático

### DISCUSSION THREAD

**Discussion by PitziPana** [community/community#121801] [Actions]
### Select Topic Area

Question

### Body

Tengo un problema, un script en python que he subido a GitHub para que se ejecute todos los días a una hora funciona siempre que lo haga manualmente, pero no en automático. he creado el siguiente código : name: Run Weather Script

on:
  schedule:
    - cron: '30 11 * * *'  # Ejecuta todos los días a las 10:30 AM UTC
  workflow_dispatch:  # Permite ejecuciones manuales desde GitHub

jobs:
  execute_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run the script
      run: python ./charo.py          

pero no va en automático. SÍ, SI LO EJECUTO MANUALMENTE

**Comment by gurjeetsinghvirdee** [comment]
```yml
name: Run Weather Script

on:
  schedule:
    - cron: '30 10 * * *'  # Runs every day at 10:30 AM UTC
  workflow_dispatch:  # Allows manual execution from GitHub

jobs:
  execute_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the script
        run: python ./charo.py
```

try this
