### DISCUSSION TITLE
Running Python via filename using 'shell: python'

### DISCUSSION THREAD

**Discussion by zachspar** [community/community#121870] [Actions]
### Select Topic Area

Question

## Background
When looking at the [documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell) for how actions will execute what is in the `run` block I see `python {0}`, which makes it seem like I can supply a Python script filename for it to run. However this is not the case, and instead _only_ runs the script [defined inline the yaml](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-running-an-inline-python-script).

Failing Example:
```yaml
...
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: python
        run: path/to/some/python-file.py
...
```

This seems counterintuitive to me. For the `bash` shell you can supply a filename as the `run` value for the shell to execute.

## Here are my questions:
 - Can you please modify the documentation to properly reflect what the "Command run internally" actually is for python?
   - Alternatively, can you better explain what `{0}` does? It seems like the `run` block makes a temp file and is then executed by the shell that is specified.
 - Are there any plans to support running a Python script via filename in the future?
