### DISCUSSION TITLE
workflow_dispatch

### DISCUSSION THREAD

**Discussion by nilumak** [community/community#121948] [Actions]
### Select Topic Area

General

### Body

I need to use input choice in  workflow_dispatch. It is deprecated what is the option. 
for eg.
on:
    workflow_dispatch:
      inputs:
        choice:
          type: choice
          description: select environment.
          options:
             - dev
             - uat
             - prod
             - stage

**Comment by mickeygousset** [comment]
Choice still works:

https://github.com/devopselvis/github-actions-presentation/blob/main/.github/workflows/basic-workflow.yml#L19

```
city:
        description: "Favorite city"
        required: true
        default: "Tupelo"
        type: choice
        options:
        - New York
        - Seattle
        - Tupelo
```
