### DISCUSSION TITLE
Do we have Notifications settings available in GitHub Actions similar to Azure DevOps?

### DISCUSSION THREAD

**Discussion by Keshapally** [community/community#121962] [Actions]
### Select Topic Area

Question

### Body

We are migrating from Azure DevOps to GitHub Actions for few pipelines and need to setup pipeline failure notifications to multiple team members.
we had https://learn.microsoft.com/en-us/azure/devops/organizations/notifications/about-notifications?view=azure-devops in Azure DevOps so looking for something similar in GitHub.

similar to [43415](https://github.com/orgs/community/discussions/43415)

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by joshjohanning** [comment]
By default, GitHub Actions notifies the actor (person who initiated the run) - assuming they haven't tweaked their notification settings. A user can opt in / out of these Action failure notifications.

You can use an Action from the GitHub Actions marketplace, but you would need SMTP credentials: https://github.com/marketplace?type=actions&query=email

There are cloud services, like Mailgun or Sendgrid, that you can also use to facilitate email sending.

---

You can also set up [Teams](https://github.com/integrations/microsoft-teams) or [Slack](https://github.com/integrations/slack) integration to post to a channel the results of a job. This is how I most commonly see it at customers.

---

As another workaround option, you can create a new issue / issue comment / comment to a PR and `@mention` the team you want to mention, and provide a link to the workflow that is failing. Something like this:

Like this: 

```yml
  - uses: actions/create-github-app-token@v1
    id: app-token
    with:
      app-id: ${{ vars.APP_ID }}
      private-key: ${{ secrets.PRIVATE_KEY }}

- name: create issue comment with failure
  run: | 
     # update 123 with the issue number you are commenting to
     gh issue comment 123 -R my-org/my-repo --body "@myorg/myteam: ***Workflow failure*** [View workflow run for details](${{ github.repository.html_url }}/actions/runs/${{ github.run_id}})"
  env:
    GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
```

You do have to use a GitHub app or personal access token to @ mention a team though (the `${{ github.token }}` will not work).


---

cc
- https://github.com/orgs/community/discussions/43415
