### DISCUSSION TITLE
Why won't my job run?

### DISCUSSION THREAD

**Discussion by danielniccoli** [community/community#122141] [Actions] [answered]
### Select Topic Area

Question

### Body

I have two jobs `publish-to-testpypi` and `publish-to-pypi` defined in https://github.com/danielniccoli/django-msgraphbackend/blob/main/.github/workflows/ci.yml. The workflow is based on https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/.

I pushed a commit with a tag `v1.0.0` which should meed the condition `startsWith(github.ref, 'refs/tags/v*')` defined in these jobs. But they don't run, as you can see here: https://github.com/danielniccoli/django-msgraphbackend/actions/runs/8938066903

Can someone help me understand why?

**Comment by mickeygousset** [comment]
Have you tried looking at the `github` context to see what value is actually there?

You can do something like this to output the context:

```
- name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
```

then you can verify the context has what you are expecting. That is the first thing I would do.
