### DISCUSSION TITLE
Github workflow is not picking up an input parameter when job is run as schedued

### DISCUSSION THREAD

**Discussion by githubofkrishnadhas** [community/community#122299] [Actions] [answered]
### Select Topic Area

Bug

### Body

hello everyone,

i am using github api to pull list of all github apps in my org. i have set up the workflow as below

```
name: github-app-installation-details
on:
  workflow_dispatch:
    inputs:
      organization:
        description: 'GitHub organization Name'
        required: true
        type: string
        default: 'devwithkrishna'
  schedule:
    - cron: "* * * * *" # Every min  

jobs:
  github-app-installation-details:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: set up python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: package installations
        run: |
         pip install pipenv
         pipenv install
      - name: execute python program
        env:
          ORGANIZATION: ${{ github.event.inputs.organization }}
          GH_TOKEN: ${{ secrets.DEVWITHKRISHNA_PERSONAL_ACCESS_TOKEN }}
        run: |
          pipenv run python3 list_all_github_app_in_org.py
      - name: azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

        run: |
          echo "program completed successfully"
```

list_all_github_app_in_org.py is as follows:

```
# reference: https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#list-app-installations-for-an-organization
import  requests
import json
import os
from dotenv import load_dotenv

def list_github_apps_in_organization(organization: str):
    """
    list GitHub apps in the orgaization
    :param organization:
    :return:
 reference: https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#list-app-installations-for-an-organization
    """

    list_github_app_endpoint = f'https://api.github.com/orgs/{organization}/installations'
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {os.getenv('GH_TOKEN')}",
        "X-GitHub-Api-Version": "2022-11-28"
    }

    response = requests.get(list_github_app_endpoint, headers=headers)
    response_json = response.json()
    response_code = response.status_code

    if response_code == 200:
        print(f'Listing GitHub Apps in {organization} organization successful')
    else:
        print(f'Listing GitHub Apps in {organization} failed')
    print(response_json)
    # Extract the list of dictionaries
    list_of_installations = response_json["installations"]
    print(f'Found {len(list_of_installations)} GitHub App in {organization} organization')

    # Convert list of dictionaries to JSON string
    json_data = json.dumps(list_of_installations, indent=4)

    # Write JSON string to a file
    with open("list_of_github_installations.json", "w") as file:
        file.write(json_data)

    app_short_list = []
    for app in list_of_installations:
        app_dict = {}
        app_dict['id'] = app['id']
        app_dict['app_id'] = app['app_id']
        app_dict['app_slug'] = app['app_slug']
        app_short_list.append(app_dict)

    return app_short_list

def main():
    """ To test the code """
    load_dotenv()
    GH_TOKEN = os.getenv('GH_TOKEN')
    organization = os.getenv('ORGANIZATION')
    # organization = 'devwithkrishna'

    # Function call
    list_github_apps_in_organization(organization)

if __name__ == '__main__':
    main()
```

so basically when job is run as a cron, it is not picking up the organization name from inputs.
workflow relevant logs.

```
Run pipenv run python3 list_all_github_app_in_org.py
  pipenv run python3 list_all_github_app_in_org.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.14/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
    Python[2](https://github.com/devwithkrishna/automation-to-add-repos-to-a-github-app/actions/runs/8951157483/job/24587184269#step:6:2)_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
    Python[3](https://github.com/devwithkrishna/automation-to-add-repos-to-a-github-app/actions/runs/8951157483/job/24587184269#step:6:3)_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.1[4](https://github.com/devwithkrishna/automation-to-add-repos-to-a-github-app/actions/runs/8951157483/job/24587184269#step:6:4)/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.14/x[6](https://github.com/devwithkrishna/automation-to-add-repos-to-a-github-app/actions/runs/8951157483/job/24587184269#step:6:6)4/lib
    ORGANIZATION:
    GH_TOKEN: ***
Traceback (most recent call last):
  File "/home/runner/work/automation-to-add-repos-to-a-github-app/automation-to-add-repos-to-a-github-app/list_all_github_app_in_org.py", line 63, in <module>
Listing GitHub Apps in  failed
    main()
  File "/home/runner/work/automation-to-add-repos-to-a-github-app/automation-to-add-repos-to-a-github-app/list_all_github_app_in_org.py", line 60, in main
    list_github_apps_in_organization(organization)
  File "/home/runner/work/automation-to-add-repos-to-a-github-app/automation-to-add-repos-to-a-github-app/list_all_github_app_in_org.py", line 32, in list_github_apps_in_organization
    list_of_installations = response_json["installations"]
KeyError: 'installations'
{'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest'}
Error: Process completed with exit code 1.
```
The same workflow, when triggered manually picks up the org name as an environment variable. This seems to be a bug to me. but i am not sure if any mistake has been happenedd from my end.

![image](https://github.com/community/community/assets/108367225/e7bfd0f2-3b1a-4f65-8544-f0e8867e1042)

can someone help me out with this issue.
