### DISCUSSION TITLE
Release to pip is being skipped

### DISCUSSION THREAD

**Discussion by Aviksaikat** [community/community#122424] [Actions]
### Select Topic Area

Show & Tell

### Body

The release job is being skipped. Here is my `build.yaml` file.

```yml
name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        hatch env create
    - name: Lint and typecheck
      run: |
        hatch run lint-check
    - name: Run Tests
      run: |
        hatch run test:pytest
    - name: coverage test
      run: |
        if [ "${{ matrix.python_version }}" == "3.9" ]; then
          hatch run test:test-cov-xml
        fi
    - uses: codecov/codecov-action@v4
      if: matrix.python_version == '3.9'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true

  release:
    runs-on: ubuntu-latest
    environment: release
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
        contents: write
        id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build
      run: |
        hatch build
    - name: Publish 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.TEST_PYPI_SECRECT }}
        packages-dir: dist/
        repository-url: https://test.pypi.org/legacy/
    - name: Publish 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_SECRECT }}
        packages-dir: dist/
```

![image](https://github.com/community/community/assets/31238298/af289d19-e50c-405e-870d-95cdd6b61855)
