### DISCUSSION TITLE
Getting output of Action using Docker

### DISCUSSION THREAD

**Discussion by Tech0ne** [community/community#122567] [Actions]
## How do you retreive the output of a github action ?

Here is the repo : https://github.com/Tech0ne/CI-CD-Github-Action

I'me trying to create an action to build, test and check C/C++ code.
Action is (might ?) work good, but I want, in the workflow of my project, get the output of my action.
How do I say that all logs (STDOUT and STDERR, btw) of my entrypoint.sh goes as the output of my Action ?

I know that I should add
```yml
outputs:
  run_log:
    description: "Build, tests and coding style log."
```
to my yml, but it's not the only thing I need to do, right ?
