### DISCUSSION TITLE
How to do dynamic "uses" for reusable workflow

### DISCUSSION THREAD

**Discussion by krm731** [community/community#122595] [Actions]
We would like to test a list of versions of the workflow. the version was passed as list we need to pass all the versions to the workflow to trigger please check the code below for more details.

```yml
name: Automated CI Tests
on:
  push:
  workflow_dispatch: 
jobs:

  Read_Config:
    runs-on: ubuntu-latest
    outputs:
      repos: ["repo1", "repo2", "repo3"]
      versions: ["v1","v2"]
    steps:
      - uses: actions/checkout@v4
      - name: Read ConfigMap
        uses: org/reusable_workflow@tag_version
        id: config
        with:
          configfile: <config_file>   

#Based on the previous step execution will get list of outputs as following.
#  1. repos - containng the list of repos ex: ["repo1", "repo2"]
#  2. versions - contains the list of versions to be tested for each repo [["v1","v2"], ["v3",["v4"]]]

  DotNet_Automated_Testing:
    needs: [Read_Config]
    if: ${{ needs.config.outputs.dotnetTests == 'True' }}
    strategy:
      matrix:
        repos: ${{ needs.Read_Config.outputs.repos }}
    uses: org/reusable_workflow@(tag_versionv1 or tagversionv2) # But for each repo there will be multiple version of workflow to be tested how to pass these version dynamically
    secrets: inherit
    with:
      repos: ${{ needs.Read_Config.outputs.dotnet }} # In the parameter repos the matrix of the repos will be passed.
      create_artifact: true

  Java_Automated_Testing:
    needs: [Read_Config]
    if: ${{ needs.Read_Config.outputs.javaTests == 'True' }}
    strategy:
      matrix:
        repos: ${{ needs.Read_Config.outputs.repos }}
    uses: org/reusable_workflow@(tag_versionv1 or tagversionv2)
    secrets: inherit
    with:
      repos: ${{ needs.Read_Config.outputs.java }} # In the parameter repos the matrix of the repos will be passed.
      create_artifact: true
```
