### DISCUSSION TITLE
Why can't GitHub Self-Hosted Runner find the included CrystalDecisions.CrystalReports.Engine package?

### DISCUSSION THREAD

**Discussion by Rod-at-DOH** [community/community#122597] [Actions]
### Select Topic Area

Question

### Body

I maintain an old ASP.NET VB.NET WebForms application written years ago. I don' think anyone knows who started it, because whoever started it didn't put the source code into any version control system. Then when the last guy left, before I was given it to maintain, he asked that his machine be reimagined, so I had to put it together from bits and pieces he left scattered around different servers. Last year I migrated the project to a repo in one of our GitHub organizations. I installed a GitHub Self-Hosted Runner onto one of our internal servers, since this web app runs as an Intranet app, with no exposure for a GitHub Runner to reach.

I can build the app fine on my dev box. However, the GH self-hosted runner will not build it. I've got a GH Action set up to perform the build on a child branch of main, when I push to it. It fails with this error:

>   D:\actions-runner\_work\FP_Timetrack\FP_Timetrack\WicReports\rbWicHeader.vb(13,87): error BC30002: Type 'ReportClass' is not defined. [D:\actions-runner\_work\FP_Timetrack\FP_Timetrack\WicReports\WicReports.vbproj]

Here's a code snippet that causes the above error:

```vb.net
Imports CrystalDecisions.CrystalReports.Engine
Imports PJAWic

Public Class rbWicHeader

    Private connString As String
    Dim Environ As String = ""
    Public Sub New(ByVal ConnectionString As String, ByVal Environment As String)
        connString = ConnectionString
        Environ = Environment
    End Sub

    Public Sub BuildHeader(ByVal ps As WicReportBasics.ReportParameters, ByVal rpt As ReportClass, Optional ByVal DataSource As String = Nothing)
```

Previously I pulled in the [CrystalDecisions.CrystalReports.Engine package from NuGet](https://www.nuget.org/packages/CrystalDecisions.CrystalReports.Engine#readme-body-tab).

So, I've got the NuGet package, in the solution. Visual Studio shows it there and it's fine. But GH self-hosted runner can't find it. Huh?? I don't get it, how can it simultaneously be there, but not be there?

Here's a snippet from my YAML file:

```yaml
    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name

    - name: Build and Publish
      run: msbuild $env:Solution_Name /p:Configuration=Release /p:DeployOnBuild=True /p:DeployIisAppPath="Default Web Site/TimeTrack_Test" /p:WebPublishMethod=MSDeploy /p:MSDeployServiceURL=**localhost** /p:DeleteExistingFiles=True /p:UserName="$env:DOH_Build_Account" /p:Password="$env:DOH_Build_Password" /p:PublishProfile=Default
```
