### DISCUSSION TITLE
No Space left on Device while dotnet build

### DISCUSSION THREAD

**Discussion by kryptobi** [community/community#122603] [Actions] [answered]
### Select Topic Area

Question

### Body

hi all,

I've tried following action:

```yaml
name: run .net unittests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore MyCompany.sln

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
```

Everything runs smoothly until the build task `dotnet build --no-restore`. After about 4 minutes of the build process, the error occurs: `Error: No space left on device`. When I build my solution locally, it reaches a size of about 7 GB. Could that already be the problem?

Does anyone have experience with this? If so, does anyone have experience in reducing the size of builds for this use case?
