### DISCUSSION TITLE
Branch name of workflows does not accurately display the branch name of the workflow file executed

### DISCUSSION THREAD

**Discussion by ChipShaddAtCube** [community/community#122941] [Actions]
### Select Topic Area

Bug

### Body

I noticed some weird behavior while troubleshooting something else.  I will include what I was troubleshooting in addition to what I found.

## My use case:
- Run an action after a PR has been merged

### Core Workflow file
```
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  run-action:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
```

#### Expected behaviour
- GH Actions to pull down newly merged code in `main`
- GH Actions to use the workflow file in `main`
- GH to show the `main` branch in the list of previous workflow runs

#### Actual behavior
- GH Actions DOES pull down the newly merged code in `main`
- GH Actions uses the workflow file from the source branch
- GH Actions shows the source branch in the list of workflow runs
  - Although it should not be an issue, it is confusing as it looks like the action was run on code from the source branch and not the `main` branch
  - I have other hooks that run on `push` to `main` so in the list of workflow runs, users expect to see that all actions were run on main, but instead, they see that hooks were run on `main`, and code was seemingly deployed from the feature branch.

## The weird behavior
This got me thinking...what if the workflow in `main` was updated, and a feature branch was merged in with an outdated workflow file (not best practice, I know).

In my `main` branch, I cut a feature branch, and then I changed the trigger to the following, directly in the `main` branch:
```
on:
  push:
    branches:
      - main

jobs:
  run-action:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
```

I then merged in the feature branch, without rebasing, into `main`. (feature branch's workflow file still set to trigger on PR closure).

#### Expected behavior
- GH Action will use the outdated workflow file from the incoming feature branch (as established above)

#### Actual behavior
- GH Action used the workflow file in `main`
- GH Action was skipped due to the failed `if: github.event.pull_request.merged == true` conditional in `main`
- On the skipped run, when examining the workflow file used, GH showed the workflow file of source feature branch as well as the commit hash which showed the workflow trigger was still set to run on PR closure.

It seems like GH uses the most recent version of the workflow file between the branches being merged? Although the UI (in multiple places) indicate otherwise.
