### DISCUSSION TITLE
How to suppress running maven with JDK 11 forces compiler option --release

### DISCUSSION THREAD

**Discussion by leerho** [community/community#123185] [Actions]
### Select Topic Area

Question

### Body

I'm running a Java 11/ maven environment using JPMS where I need to export a few JVM packages.  
In this situation it is an error to specify "--release" to the java compiler.  
Executing "mvn clean compile" in a GitHub action, for some mysterious reason, automatically sets the compiler 
"--release" flag, which fails the CI/CD build.   
My pom files DO NOT specify this flag, yet running maven in the GitHub action inserts it anyway.  
My pom files do specify "maven.compiler.source = 11" and "maven.compiler.target = 11".
Outputting the effective pom when executing the GH action reveals that all 3 flags are present! 
Running "mvn clean compile" locally works fine.   

How can I force this github action to not set the compiler "--release" flag?

**Comment by techpond31** [comment]
🤔 You can pass the arguments to the `mvn` command explicitly to override the default behavior. Specifically, you can exclude the `--release` flag using the `maven.compiler.arguments` property.

Update your GitHub action yaml configuration file to include the `maven.compiler.arguments` property:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'gradle'

    - name: Build and Test
      run: mvn clean compile -Dmaven.compiler.arguments="-source ${{ env.MAVEN_COMPILER_SOURCE }} -target ${{ env.MAVEN_COMPILER_TARGET }}"
```

Make sure you define `MAVEN_COMPILER_SOURCE` and `MAVEN_COMPILER_TARGET` environment variables in your GitHub action:

```yaml
env:
  MAVEN_COMPILER_SOURCE: 11
  MAVEN_COMPILER_TARGET: 11
```

These changes ensure that the `--release` flag is excluded and the specified source and target versions are passed to the compiler.
