### DISCUSSION TITLE
Running multiple jobs in a nix-shell environment

### DISCUSSION THREAD

**Discussion by AndreMerendeira** [community/community#123140] [Actions]
### Select Topic Area

Question

### Body

Hello, I'm trying to use GitHub Actions to run multiple jobs which in turn have multiple instructions on run, for example:
```
jobs:
  job1:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Job 1
        run: |
              nix-shell --run "make clean"
              nix-shell --run "make setup"

  job2:
    runs-on: self-hosted
    timeout-minutes: 60
    # run after indicated job
    needs: [ job1 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Job 2
        run: |
              nix-shell --run "make clean"
              nix-shell --run "make setup"
```
Is there a way to run all jobs and all commands with nix-shell without having to explicitly write it in all the commands?
It's just an organization and speed issue, since it greatly escalates for a large number of jobs and/or commands.

**Comment by techpond31** [comment]
👋 Indeed, repeating the `nix-shell` command for multiple steps can become verbose and unwieldy for larger numbers of jobs and commands. Unfortunately, GitHub Actions itself does not have built-in support for wrapping commands with `nix-shell`. However, you can mitigate this issue by writing a wrapper script for `nix-shell` in your repository and referring to it in the workflow.

1. Create a script file named `run-script` in your repository:

   ```bash
   #!/usr/bin/env sh
   COMMAND=$1
   shift
   nix-shell --run "$COMMAND $@"
   ```

   Don't forget to make the script executable with `chmod +x run-script`.

2. Modify your GitHub Actions workflow:

   ```yaml
   jobs:
     job1:
       runs-on: self-hosted
       timeout-minutes: 60
       steps:
         - uses: actions/checkout@v4
           with:
             submodules: 'recursive'
         - name: Job 1
           run: ./run-script make clean
         - name: Job 2
           run: ./run-script make setup

     job2:
       runs-on: self-hosted
       timeout-minutes: 60
       needs: [job1]
       steps:
         - uses: actions/checkout@v4
           with:
             submodules: 'recursive'
         - name: Job 2
           run: ./run-script make clean
         - name: Job 3
           run: ./run-script make setup
   ```

Using this approach, you consolidate the repeated `nix-shell` command into a single helper script, reducing redundancy and improving readability. Just bear in mind that you need to propagate changes to the `run-script` file to all targeted repositories, and occasionally update the script if you adopt new patterns or requirements.
