### DISCUSSION TITLE
How to change default Java version in windows-latest?

### DISCUSSION THREAD

**Discussion by jtcmedia** [community/community#123161] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a pkg that depends on Java 11 and checks that JAVA_HOME is set and the the command `java` is at least version 11. I see that the windows-latest comes with Java 11 installed, but 8 is the default so my action is failing. How do I switch to 11 so that JAVA_HOME points to that version and `java` defaults to 11?

**Comment by spenserblack** [comment]
You might want to check out the [actions/setup-java](https://github.com/actions/setup-java) action. Besides installing the specified java version and distribution, it should also set the `JAVA_HOME` environment variable.

However, as implied by [the action's docs](https://github.com/actions/setup-java?tab=readme-ov-file#install-multiple-jdks), perhaps the exact version you want would be in `JAVA_HOME_11_{{ ARCHITECTURE }}` (`ARCHITECTURE` would be `x64` I think)? I haven't used Java in a long time, so I don't know if that environment variable naming style is standard or if it's exclusive to the action.

**Reply by jtcmedia** [reply, marked as answer]
Thanks for your comment. I saw [actions/setup-java](https://github.com/actions/setup-java) but, at first look, had assumed it is for installing java, not using a version already installed. But after reading [this](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#hosted-tool-cache), I now see that it detects a pre-installed version on `windows-latest` and allows you to switch to it. I only need:
```yaml
- name: configure_java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
- name: validate java config
      shell: powershell
      run: |
        java --version
        echo $ENV:JAVA_HOME
```

which outputs:
```text
openjdk 11.0.23 2024-04-16
OpenJDK Runtime Environment Temurin-11.0.23+9 (build 11.0.23+9)
OpenJDK 64-Bit Server VM Temurin-11.0.23+9 (build 11.0.23+9, mixed mode)
C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.23-9\x64
```

**Comment by techpond31** [comment]
🤔On Windows, switching between different Java runtime environments (JRE) requires configuring the JAVA\_HOME variable correctly. Fortunately, GitHub Actions allow us to customize environment variables and execute scripts during build stages easily.

Create a YAML definition file named `action.yml` in your repository's `.github/workflows` folder with contents as shown below. This example demonstrates setting JAVA\_HOME, adding Java binaries to the PATH, and running `java --version` to confirm the successful change.

```yaml
name: Set JAVA_HOME to Java 11
on: push
jobs:
  configureJava:
    runs-on: windows-latest
    env:
      JAVA_HOME: "${{ runner.toolcache.jdk-11.path }}"
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        id: setupjdks
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Configure Environment Variables
        run: |
          echo ## Setting up JAVA_HOME
          echo ::set-env name=PATH::${{ env.JAVA_HOME }}\bin;${{ runner.tools.path }}
          echo $PATH
          echo ::set-endgroup::
      - name: Validate Correct Version Installed
        shell: bash
        run: java --version
```

Key highlights of this configuration:

- Sets JAVA\_HOME to point towards the toolcached AdoptOpenJDK 11 installation location.
- Adds Java 11 binary path to the beginning of the global PATH variable.
- Verifies the correct Java version by checking the output of `java --version`.

Upon pushing this `action.yml` file to your repository, GitHub Actions will trigger a job according to the defined schedule, updating JAVA\_HOME and ensuring subsequent tasks leverage Java 11. Customizing environment variables and configurations empowers you to seamlessly integrate prerequisites for building packages requiring specific dependencies.
