### DISCUSSION TITLE
az.imagebuilder module fails to load in github hosted windows runner v 2.316.1

### DISCUSSION THREAD

**Discussion by GPJDE** [community/community#123120] [Actions]
### Select Topic Area

Question

### Body

Windows Runner version: '2.316.1'
Runner image:
windows-2022
20240421.1.0
https://github.com/actions/runner-images/releases/tag/win22%2F20240421.1
--- Failing section ---
Run azure/powershell@v1
Module Az latest installed from hostedAgentFolder
The 'Get-AzImageBuilderTemplate' command was found in the module 'Az.ImageBuilder', but the module could not be
     | loaded. For more information, run 'Import-Module Az.ImageBuilder'.
Error: Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1

**Comment by techpond31** [comment]
👋 It seems like the PowerShell script couldn't import the Azure Image Builder module successfully. You can try explicitly importing the module in your workflow file to resolve this issue.

Edit your workflow file and add the following lines within the respective job section, before calling the `azure/powershell@v1` action:

```yaml
- name: Import Az.ImageBuilder Module
  powershell: |
    Import-Module Az.ImageBuilder
```

So the final block should look somewhat like this:

```yaml
jobs:
  ...
  jobName:
    ...
    steps:
      - name: Import Az.ImageBuilder Module
        powershell: |
          Import-Module Az.ImageBuilder

      - name: Run Powershell Script
        uses: azure/powershell@v1
        ...
```

This modification forces the PowerShell script to import the Az.ImageBuilder module before proceeding with the workflow, thus avoiding the error you encountered. Give this a try and check if the issue is resolved.
