### DISCUSSION TITLE
Pulling a Docker image from Packages

### DISCUSSION THREAD

**Discussion by dariagrudzien** [community/community#123292] [Packages] [answered]
### Select Topic Area

Question

### Body

Hello all,

We're building and pushing Docker images to Packages as our image registry. I'm writing a GH Actions workflow which would ssh into my server, Docker login to Packages registry and pull the image. All of this is happening within the same repository.

Our GH Actions workflow step:
```
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      actions: write
      checks: read
      contents: read
      id-token: write
      packages: write
      pull-requests: write

- name: Pull the image
  env:
    GH_USER: ${{ github.repository_owner}}
  run: |
    ssh -T user@server << EOF
    echo $GH_TOKEN | docker login ghcr.io -u $GH_USER --password-stdin
    sudo docker pull ghcr.io/<org>/<repo>/<package>:latest
    EOF
```

When I try to pull the docker image I get this result:
```
Error response from daemon: Head "https://ghcr.io/v2/<org>/<repo>/<package>/manifests/latest": unauthorized
```

We've tried a bunch of ways to authenticate:
- using `GH_TOKEN` and giving it permissions for packages, contents, actions, pull_requests
- using a GitHub App to generate the GH token
- using a personal access token to manually pull the image from the registry (not from the GH Action), and the user is an admin of the repo which hosts the package, and Packages permissions are inherited from the repo.

We're failing miserably every time. Any hints on what we could be missing?
