### DISCUSSION TITLE
Using a composite action from a reusable workflow

### DISCUSSION THREAD

**Discussion by kalote** [community/community#123261] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello,

I'm trying to simplify my github actions by using reusable workflow.

What I would like to do is:
- "my-app-repo/.github/workflows/build.yaml" calls "github-actions-repo/.github/workflows/reusable.yaml"
- "github-actions-repo/.github/workflows/reusable.yaml" calls "github-actions-repo/.github/actions/build-init/action.yaml"

But it doesn't work =/

### my-app-repo/.github/workflows/build.yaml
```
name: Build and push image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    permissions:
      id-token: write
      contents: read
    uses: myorg/github-actions/.github/workflows/build-and-push-docker.yaml@main
    with:
      registry: xxx.dkr.ecr.us-east-2.amazonaws.com/docker-repo
      image-name: 'myord/myapp'
```

### github-actions-repo/.github/workflows/reusable.yaml
```
name: Build & push docker

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image-name:
        required: true
        type: string

env:
  registry: ${{ inputs.registry }}
  image-name: ${{ inputs.image-name }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Here I don't know how to do it
      - name: Init docker build
        id: build-init
        uses: myorg/github-actions-repo/.github/actions/build-init@main

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.build-init.outputs.tags }}
          labels: ${{ steps.build-init.outputs.labels }}
```

### github-actions-repo/.github/actions/build-init

I tried as a composite action, or as a reusable workflow (using `on workflow_call`), but both options doesn't work:
- composite action => the file is not present (as it has not been checkout) and it seems counter intuitive to checkout the `github-actions-repo` in the `my-app-repo` workflow
- reusable workflow => I get following syntax error:

```
Error: myorg/github-actions-repo/main/.github/actions/build-init/action.yaml (Line: 9, Col: 16): Unrecognized named-value: 'jobs'. Located at position 1 within expression: jobs.build_init.outputs.tags
Error: myorg/github-actions-repo/main/.github/actions/build-init/action.yaml (Line: 12, Col: 16): Unrecognized named-value: 'jobs'. Located at position 1 within expression: jobs.build_init.outputs.labels
Error: myorg/github-actions-repo/main/.github/actions/build-init/action.yaml (Line: 18, Col: 13): Unrecognized named-value: 'steps'. Located at position 1 within expression: steps.meta.outputs.tags
Error: myorg/github-actions-repo/main/.github/actions/build-init/action.yaml (Line: 19, Col: 15): Unrecognized named-value: 'steps'. Located at position 1 within expression: steps.meta.outputs.labels
Error: myorg/github-actions-repo/main/.github/actions/build-init/action.yaml (Line: 39, Col: 19): Unrecognized named-value: 'env'. Located at position 1 within expression: env.registry
Error: myorg/github-actions-repo/main/.github/actions/build-init/action.yaml (Line: 40, Col: 17): Unrecognized named-value: 'env'. Located at position 1 within expression: env.UNIQ_ID
Error: Failed to load myorg/github-actions-repo/main/.github/actions/build-init/action.yaml
```

the code:
```
name: "Prepare docker build"
description: "Create uniqId + auth + ecr login + metadata"

on:
  workflow_call:
    outputs:
      tags:
        description: "Docker image tag"
        value: ${{ jobs.build_init.outputs.tags }}
      labels:
        description: "Docker image labels"
        value: ${{ jobs.build_init.outputs.labels }}

jobs:
  build_init:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Set current date as env variable
        run: echo "UNIQ_ID=$(date +'%y%m%d')-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::xxxx:role/github-actions
          role-session-name: github-actions-role-session
          aws-region: us-east-2

      - name: Amazon ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.registry }}/${{ env.image-name }}
          tags: |
            type=ref,event=branch
            type=ref,event=branch,prefix=${{ env.UNIQ_ID }}-
```

Thanks a lot for the support 🙏

**Comment by the-officialjosh** [comment]
It looks like you're trying to build a sophisticated CI/CD pipeline using GitHub Actions with reusable workflows and actions, but you're encountering some errors and complexities. Let's address your issues one by one.

### Reusable Workflow and Actions Design

Your intent to modularize your GitHub Actions configuration is a great practice. You aim to have:
1. `my-app-repo` trigger a reusable workflow from another repository (`github-actions-repo`).
2. This reusable workflow itself calls a custom action within the same `github-actions-repo`.

### Issues Identified and Solutions

**1. Composite Action Access**:
When using a composite action like your `build-init`, the GitHub Actions runner does not automatically check out other repositories or additional paths within the repository. If your action relies on scripts or files from the repository, you need to explicitly check them out.

Solution: Instead of making `build-init` a composite action that needs to check out the repository, convert it to a reusable workflow that resides in `.github/workflows/` within `github-actions-repo` and can be directly referenced.

**2. Syntax Errors**:
You've run into multiple syntax errors, mostly because of incorrect context referencing. Here's how to fix these:

- **Outputs from Jobs**: You cannot reference job outputs directly in the `on: workflow_call: outputs:` section. This section is for defining outputs that the calling workflow can use, but the values must be set in the jobs themselves.

- **Environment Variables**: The error messages indicate issues with accessing `env` variables. Ensure these are correctly set in the jobs where they're being used and are available when referenced.

### Revised Approach

Here's a revised approach that might work better:

1. **Split the Action into a Reusable Workflow**: Since there are limitations with composite actions accessing files and shared contexts, consider converting your action into a reusable workflow that takes care of setting up the environment and performing the necessary steps.

2. **Correctly Reference Outputs and Steps**: Make sure you use the correct context (steps, jobs) when referencing outputs.

#### Example of Revised `reusable.yaml`

```yaml
name: Build & push Docker
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image-name:
        required: true
        type: string
    outputs:
      tags:
        description: "Docker image tags"
        value: ${{ jobs.build_and_push.outputs.docker_tags }}
      labels:
        description: "Docker image labels"
        value: ${{ jobs.build_and_push.outputs.docker_labels }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      docker_tags: ${{ steps.meta.outputs.tags }}
      docker_labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare docker build
        id: build-init
        run: |
          echo "DOCKER_TAGS=latest,${{ github.sha }}" >> $GITHUB_ENV
          echo "DOCKER_LABELS=commit=${{ github.sha }},date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          labels: ${{ env.DOCKER_LABELS }}
```

This structure ensures you are correctly utilizing GitHub Actions features such as `env`, `steps`, and `jobs`. Make sure to adjust paths and references as needed for your specific setup and repositories. This should help address the issues you were facing and streamline your CI/CD pipeline using GitHub Actions.

**Reply by kalote** [reply]
Thanks for your reply, but ....

- It looks like a chatGPT generated reply
- It doesn't really provide a solution to my issue (i have 3 files and i'm quite sure that 2 of them needs a refacto (namely, the reusable.yaml and the build-init.yaml))
- The `example of revised reusable.yaml` that you provide is wrong (referencing outputs steps that doesn't exist in the file, like `meta`) and the `build-init` step provided is not including an external workflow

**Reply by kalote** [reply, marked as answer]
Just to close this discussion, here is the solution I've implemented. Basically, I have to clone the `github-action` repo in my reusable workflow so that I can access the composite action.

3 github wf:
  - 1 caller (the workflow use by all my apps)
  - 1 callee (reusable workflow in the `github-action` repo)
  - 1 composite (to divide my reusable workflow in smaller pieces, in the `github-action` repo)

## Caller

```
name: Build and push image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    permissions:
      id-token: write
      contents: read
    uses: myorg/github-actions/.github/workflows/build-and-push-docker.yaml@main
    with:
      registry: xxx.dkr.ecr.us-east-2.amazonaws.com/docker-repo
      image-name: 'myorg/myapp'
    secrets:
      deploy_key: ${{ secrets.DEPLOY_SSH }}
```

## Callee (reusable workflow)

```
name: Build & push docker

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image-name:
        required: true
        type: string
    secrets:
      deploy_key:
        required: true

env:
  registry: ${{ inputs.registry }}
  image-name: ${{ inputs.image-name }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout github actions
        uses: actions/checkout@v3
        with:
          repository: myorg/github-actions
          ssh-key: ${{ secrets.deploy_key }}
          ref: 'main'
          path: github-actions

      # Begin Calling composite action here
      - name: Init docker build
        id: build-init
        uses: ./github-actions/.github/actions/build-init
      # End Calling composite action here

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.build-init.outputs.tags }}
          labels: ${{ steps.build-init.outputs.labels }}
```

## Composite (composite workflow)

```
name: "Prepare docker build"
description: "Create uniqId + auth + ecr login + metadata"

outputs:
  tags:
    description: "Docker image tag"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "Docker image labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: "composite"
  steps:
    - name: Set current date as env variable
      run: echo "UNIQ_ID=$(date +'%y%m%d')-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::xxxx:role/github-actions
        role-session-name: github-actions-role-session
        aws-region: us-east-2

    - name: Amazon ECR login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.registry }}/${{ env.image-name }}
```
