### DISCUSSION TITLE
How to manage all discussion-categories inside an organization?

### DISCUSSION THREAD

**Discussion by AB-xdev** [community/community#123610] [Discussions]
### Select Topic Area

Question

### Body

I'm admin of an organization with dozens of repositories where I would like to enable discussions.

I would e.g. like to keep the categories of these repositories in sync / the same.
I think a solution like https://github.com/marketplace/actions/label-sync would be nice, just that you configure the categories from code.

How can this be achieve in the best way?

What I checked/found so far:
* There is no REST API for discussions
* The GraphQL API can't manage discussion categories
* You can't manage all discussions orga-wide in the orga settings (like e.g. default Repository labels)

So the only possible I see option would be to enable and configure discussions in each repo individually by hand...?
If this is the case I won't enable them at all because the administration effort is just to much...

Or are there any other possible options that I may have overlooked?

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by Adya-Prasad** [comment]
_hi_
I think You can use the **Kanban board template** to add labels on the discussion and monitor that according to the label and you can also arrange and filter it by easily drag and drop.

I study it in the IBM Cloud Agile Course.
I hope it will work for you.

**Reply by AB-xdev** [reply]
So I checked this and I can't find any option to add a discussion to a board.
![](https://github.com/user-attachments/assets/e07fccfa-dbaa-4f6b-a0f2-73decb623ee0)

The doc also has no mention of it: https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions

...and it also doesn't address the problem of managing discussions categories over many repos as asked in the question above.

Anyway thank you for your feedback :)

**Comment by danialtavakoli** [comment]
Enabling and managing discussions across multiple repositories can indeed be a challenging task given the current limitations of GitHub's API for discussions. However, there are a few strategies and workarounds that can help streamline this process:

### 1. Repository Template

You can create a repository template that includes pre-configured discussion categories. When you create new repositories from this template, they will inherit the discussion settings. However, this won't help with existing repositories.

### 2. GitHub Actions Workflow

Since GitHub Actions can automate tasks, you can create a custom GitHub Action to sync discussion categories across repositories. While the API limitations mean you can't directly manage discussion categories, you can still automate the process of setting them up manually.

Here’s a general outline of how you could approach this:

1. **Setup a Repository for Configuration**:
   - Create a repository to store the configuration of your discussion categories.
   - Define your desired categories in a YAML or JSON file.

2. **GitHub Action for Syncing**:
   - Create a GitHub Action that reads the configuration file and applies the categories to each repository.
   - The action can use the `gh` CLI (GitHub CLI) to interact with the repositories. Although the CLI doesn't directly support discussion categories either, it can still automate other aspects of the setup and trigger manual intervention where needed.

### Example GitHub Action Workflow

```yaml
name: Sync Discussion Categories

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight
  workflow_dispatch:
    inputs:
      config_repo:
        description: 'The repository containing the discussion categories configuration'
        required: true
      config_path:
        description: 'Path to the configuration file'
        required: true

jobs:
  sync-categories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout configuration repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.config_repo }}
          path: config

      - name: Parse configuration
        id: parse_config
        run: |
          cat config/${{ github.event.inputs.config_path }}
          echo "::set-output name=config::$(cat config/${{ github.event.inputs.config_path }})"
        shell: bash

      - name: Sync categories
        run: |
          REPOS=("repo1" "repo2" "repo3") # Add all your repositories here
          CONFIG="${{ steps.parse_config.outputs.config }}"
          for REPO in "${REPOS[@]}"; do
            echo "Syncing categories for $REPO"
            # Use the gh CLI or GitHub API to apply the configuration
            # This part needs to be adapted based on available commands and API endpoints
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Manual Synchronization

If automation via API or CLI isn’t feasible, another option is to document the process for setting up discussions and categories and share this with the maintainers of each repository. This approach distributes the workload and ensures that each repository is correctly configured.

### Conclusion

Currently, due to API limitations, the most effective way to manage discussion categories across multiple repositories involves a combination of manual setup and automation where possible. Keeping a configuration repository and using GitHub Actions to streamline repetitive tasks can significantly reduce the administrative burden. It’s also worth keeping an eye on GitHub updates, as they might introduce more robust support for managing discussions programmatically in the future.
