### DISCUSSION TITLE
What is the simplest  way to cache Docker images?

### DISCUSSION THREAD

**Discussion by vitalykarasik** [community/community#123639] [Actions]
### Select Topic Area

Question

### Body

I'm using .net Docker image for run tests, like this:

`docker run --rm -v $(pwd):/app  -w /app  mcr.microsoft.com/dotnet/sdk:6.0 dotnet test testdir`

What is the simplest way to cache this image? I found ScribeMD/docker-cache GHA, but unfortunately I couldn't understand how I should integrate that in my workflow.

**Comment by nikhilsbuilds** [comment]
To cache the Docker image you're using for your .NET tests, you can leverage the built-in caching mechanism provided by GitHub Actions. Here's how you can integrate it into your workflow:

1. First, you need to add a step that pulls (or builds) the Docker image and caches it. You can do this by using the `actions/cache@v3` action provided by GitHub.

```yaml
- name: Cache Docker image
  uses: actions/cache@v3
  with:
    path: /tmp/.buildx-cache
    key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
    restore-keys: |
      ${{ runner.os }}-buildx-
- name: Pull Docker image
  run: docker pull mcr.microsoft.com/dotnet/sdk:6.0
```

In this example, the `actions/cache@v3` action caches the Docker image layers in the `/tmp/.buildx-cache` directory. The `key` is a unique identifier for the cache, which is generated based on the runner's operating system and the hash of your `Dockerfile` (if you have one). The `restore-keys` option allows you to restore the cache even if the `key` doesn't match exactly.

2. After caching the image, you can run your tests using the cached image:

```yaml
- name: Run tests
  run: docker run --rm -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/sdk:6.0 dotnet test testdir
```

Here's what the complete workflow might look like:

```yaml
name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Docker image
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Pull Docker image
      run: docker pull mcr.microsoft.com/dotnet/sdk:6.0
      
    - name: Run tests
      run: docker run --rm -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/sdk:6.0 dotnet test testdir
```

With this approach, the Docker image will be cached and reused across workflow runs, which can significantly speed up your build and test process.

Note that the caching mechanism works best when the Docker image layers don't change frequently. If you're frequently updating your Dockerfile or the base image, the cache may not be as effective.
