### DISCUSSION TITLE
Best way to reuse job/step output

### DISCUSSION THREAD

**Discussion by Falci** [community/community#123754] [Actions]
### Select Topic Area

Question

### Body

A common scenario for a NodeJS project is:
* checkout
* install
* lint (needs 
* build
* test
* deploy

What's the best way to structure this action in a way that I could checkout and install only once, run lint and build->test in parallel and after all run deploy

```
checkout
then install
then (
    lint,
    build
        then test
)
then deploy
```

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by odelyo** [comment]
To achieve this in a Node.js project using GitHub Actions, you can structure your workflow to perform the steps efficiently by using job dependencies. Here's how you can structure the workflow YAML file:
```
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Checkout and Install Job
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify your Node.js version

      - name: Install dependencies
        run: npm ci

  # Lint Job
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  # Build Job
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  # Test Job
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  # Deploy Job
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        run: npm run deploy

```
Explanation:
Checkout and Install (setup):

This job checks out the code and installs dependencies. This is done only once, and subsequent jobs depend on this job.
Lint (lint):

This job runs the linter. It depends on the setup job to ensure the code is checked out and dependencies are installed before running the linting.
Build (build):

This job compiles/builds the project. It also depends on the setup job.
Test (test):

This job runs the tests. It depends on the build job to ensure the project is successfully built before testing.
Deploy (deploy):

This job handles the deployment. It depends on both lint and test jobs, ensuring that both linting and testing pass before deploying the project.
Key Points:
Job Dependencies (needs): By using the needs keyword, you specify that a job depends on the successful completion of one or more other jobs. This allows you to run jobs in parallel (e.g., lint and build) and ensure that certain jobs (e.g., deploy) only run after specific jobs are successful.

Efficiency: By running lint and build in parallel and then only running test after build, you optimize the workflow to save time.

Single Checkout and Install: The code is checked out and dependencies are installed only once per job, but due to how GitHub Actions jobs are isolated, each job needs to redo the checkout and install. However, npm ci should be quick since dependencies are already cached.
