### DISCUSSION TITLE
Pytest not finding serial port within Github Actions

### DISCUSSION THREAD

**Discussion by sethkaz** [community/community#123835] [Actions]
### Select Topic Area

Question

### Body

tl;dr. Is there a way to expose a port within the `/dev` directory to steps being run on a self-hosted runner?

Setup:
* Self-hosted runner (Raspberry Pi 5), with 2 MCUs connected (ESP32S3 and ESP32)
* Repo is an Espressif project
* Repo has actions to lint, build, and test.
* Testing is done using pytest. 

I have 2 MCUs connected to the runner because one is the DUT and the other is to act as a mock for various hardware.  Because I have 2 MCUs, I want to prevent the situation where the software suite confuses the two devices and crashes out.  

To do this, I've created symbolic links (e.g. `/dev/hil_links/HIL-Interface`) pointing to the appropriate MCU (e.g. `/dev/serial/by-id/usb-Silicon_Labs...`).  This works perfectly when running pytest locally. However, when it is run within Actions, it responds with a `[Errno 2] No such file or directory`

(Also might be pertinent, I'm running 3 parallel sets of tests.  The other two also use the MCUs, and don't have issue accessing the port, so I think it's isolated to pytest settings or the link.)

How I can grant access to the workflow running on the runner to the serial port links?

**Comment by judahpaul16** [comment]
Have you tried creating unique symbolic links for each test run.
```yaml
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        job: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create unique symbolic links
        run: |
          LINK_DIR="/dev/hil_links/${{ matrix.job }}"
          sudo mkdir -p $LINK_DIR
          sudo ln -sf /dev/serial/by-id/usb-Silicon_Labs_Device1 $LINK_DIR/HIL-Interface1
          sudo ln -sf /dev/serial/by-id/usb-Silicon_Labs_Device2 $LINK_DIR/HIL-Interface2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --serial-link-dir=/dev/hil_links/${{ matrix.job }}
        env:
          SERIAL_LINK_DIR: /dev/hil_links/${{ matrix.job }}
```
