### DISCUSSION TITLE
Additional carriage return added into ISSUE_TEMPLATE format

### DISCUSSION THREAD

**Discussion by fmunteanu** [community/community#123804] [Projects and Issues]
### Select Topic Area

Bug

### Feature Area

Issues

### Body

While creating a a custom issue template ([source](https://github.com/axivo/k3s-cluster/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1)) with body `type: textarea` and `render: shell`, an additional carriage return is added.

![image](https://github.com/community/community/assets/19806136/851ae543-5752-41a2-9896-1728b0d9c480)

Usage example:

```
  - type: textarea
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: |
        Which Kubernetes version is the cluster running on? (run `kubectl version`)
        Tip: This will be automatically formatted into code, there is no need to insert backticks.
      render: shell
```

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
