### DISCUSSION TITLE
DNS bug with service in container job?

### DISCUSSION THREAD

**Discussion by rowanseymour** [community/community#123805] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a [workflow](https://github.com/nyaruka/rp-indexer/blob/main/.github/workflows/ci.yml) that sets up Elasticsearch 7, Elasticsearch 8 and OpenSearch 1 as services and then uses a matrix to run tests against each one in turn using the service name as the host to connect to. Works great!

But then I try to [add OpenSearch 2](https://github.com/nyaruka/rp-indexer/pull/72) to the matrix, and it's [giving me DNS errors](https://github.com/nyaruka/rp-indexer/actions/runs/9083323008/job/24961776417?pr=72): `dial tcp: lookup opensearch2 on 127.0.0.11:53: server misbehaving`

```
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: node:18
    strategy:
      matrix:
        searchdb-host: [elastic7, elastic8, opensearch1, opensearch2]
      fail-fast: false
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: indexer_test
          POSTGRES_USER: indexer_test
          POSTGRES_PASSWORD: temba
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      elastic7:
        image: elasticsearch:7.17.9
        env:
          discovery.type: single-node
      elastic8:
        image: elasticsearch:8.13.4
        env:
          discovery.type: single-node
          xpack.security.enabled: false
      opensearch1:
        image: opensearchproject/opensearch:1.3.16
        env:
          discovery.type: single-node
          plugins.security.disabled: true
      opensearch2:
        image: opensearchproject/opensearch:2.13.0
        env:
          discovery.type: single-node
          plugins.security.disabled: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: Setup environment
        run: |
          echo "INDEXER_DB=postgres://indexer_test:temba@postgres:5432/indexer_test?sslmode=disable" >> "$GITHUB_ENV"
          echo "INDEXER_ELASTIC_URL=http://${{ matrix.searchdb-host }}:9200" >> "$GITHUB_ENV"

      - name: Run tests
        run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...
```

Kinda lost because it works fine for the other services...? A docker bug perhaps? Something related to https://github.com/docker/compose/issues/11563 ?
