### DISCUSSION TITLE
Run a job from a container using OIDC authentication

### DISCUSSION THREAD

**Discussion by dsotirakis** [community/community#123886] [Actions]
Hey all 👋 
I have spent a considerable amount of time trying to find a solution for the following problem:

We want to [run a job inside a container](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container) where the container lives in Google Artifact Registry (GAR). What we do in order to authenticate against our private registry is OIDC. Here's the code:

```
login-to-gar:
    needs: build-and-push
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.export-creds.outputs.auth_creds }}

    steps:
      - uses: google-github-actions/auth@5a50e581162a13f4baa8916d01180d2acbc04363 # v2.1.0
        id: gcloud-auth
        with:
          token_format: access_token
          workload_identity_provider: "projects/<project_id>/locations/global/workloadIdentityPools/github/providers/github-provider"
          service_account: <service_account>
          create_credentials_file: true
      - name: Login to GAR
        id: login-gar
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: "us-docker.pkg.dev"
          username: oauth2accesstoken
          password: ${{ steps.gcloud-auth.outputs.access_token }}
      -
        name: Export creds
        id: export-creds
        run: |
          auth_creds=$(cat ${{ env.CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE }} | base64 -w 0)
          echo "auth_creds=$auth_creds" >> ${GITHUB_OUTPUT}
```

which essentially uses `docker/login-action` to authenticate to GAR and then exports the creds to an output variable.

Then my next job is:

```
  run_container:
    runs-on: ubuntu-latest
    needs: login-to-gar
    container:
      image: <my-image>
      credentials:
        username: _json_key_base64
        password: ${{ needs.login-to-gar.outputs.app }}
    steps:
      - name: Hello world
        run: cat "hello!"
```

The problem I face is that when the first job is done, as a last step I get:
<img width="1108" alt="image" src="https://github.com/community/community/assets/15115078/2aa1fd4d-cf10-47dc-b527-3a07345f8c93">

and so the `password` field in the `run_container` job is empty. I have tried the same with:
```
...
          username: oauth2accesstoken
          password: ${{ steps.gcloud-auth.outputs.access_token }}
...
```
but doesn't work either - github still doesn't let me pass this from the first job to the second one.

Questions:
* Is there a way to explicitly tell github that I don't want one variable to be regarded as a secret?
* Is there a better way to authenticate to GAR using OIDC when I want my GAR image to be used as a container in my runner?

Thanks!
