### DISCUSSION TITLE
Workflow isn't triggered for draft PRs

### DISCUSSION THREAD

**Discussion by efenderbosch-atg** [community/community#123976] [Actions]
### Select Topic Area

Question

### Body

trigger is simply

```yaml
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
```

I see there's a `converted_to_draft` type, but what about a PR that's opened in a draft state?
