### DISCUSSION TITLE
Allow full workflow to be selected as required status checks

### DISCUSSION THREAD

**Discussion by finolacahill** [community/community#12395] [Actions]
Currently you need to manually specify each job which should block merging per repo in Github Actions CI.
This is time consuming and frustrating. We're working around this by having each workflow contain a wrapper job which needs every other job and checks the status of each of its' needs. i.e. :
![image](https://user-images.githubusercontent.com/45110160/156771775-465162ee-692b-4b80-825c-43ec3d48be19.png)
![image](https://user-images.githubusercontent.com/45110160/156770814-c0fc92e8-abc1-4921-9943-dcd3d30ef6d7.png)

Why can't I just specify that my whole pull_request work flow is required to pass? Larger question, why wouldn't be whole pull_request flow be required to pass? (in terms of best practices, it's pretty counter-intuitive) You can imagine how long and unwieldy the 'container' job gets as workflows get longer

As an intermediatory step, you could allow a job that calls a reusable work-flow to be set as a status check. Currently you have to select each job that that workflow calls i.e. :

![image](https://user-images.githubusercontent.com/45110160/156771207-d1e8d6a7-4ebb-4b25-aa05-4d3bd9c0cabf.png)

I have the 'call-workflow' job, which calls my reusable workflow 'pull_request' from another workflow 'dispatch', but I can not just specify call-workflow as my status check, I have to specify each of the jobs it will then call. This is silly.

**Comment by ethomson** [comment]
Thanks for the feedback @finolacahill - this makes a lot of sense. As the number of workflows and jobs grows, so too does the complexity here in managing them. I'll make sure that this is on the backlog for us to investigate.

**Reply by finolacahill** [reply]
> Thanks for the feedback @finolacahill - this makes a lot of sense. As the number of workflows and jobs grows, so too does the complexity here in managing them. I'll make sure that this is on the backlog for us to investigate.

Great to hear, Edward. I look forward to seeing this functionality in the future!

**Reply by ajschmidt8** [reply]
@ethomson, any updates on the status of this? Is there somewhere other than this discussion where we can track its progress? My team could benefit greatly from this feature as well. This becomes especially complex when your workflow contains matrix builds.

Currently my team is using the third-party solution below as a workaround, but this isn't ideal.

- https://github.com/upsidr/merge-gatekeeper

**Reply by finolacahill** [reply]
Would love to know if this has made it to a ticket yet? Cheers

**Reply by Keshapally** [reply]
Hi All,

Any updates on this feature or any alternative solution ?

**Reply by finolacahill** [reply]
It looks like ethomson doesn't work at github anymore. @tuves did anyone take over this issue when ethomson left? Thanks.

**Reply by tuves** [reply]
@finolacahill It’s on the internal backlog of work for the team to look at but there isn’t anything I can share yet, as it’s not on our public roadmap. @chrispat would be your go-to person for all things GitHub Actions

**Reply by finolacahill** [reply]
Thanks @tuves , I appreciate the update.

**Reply by Dr-Electron** [reply]
Any updates on this?

**Comment by airtower-luna** [comment]
This would be particularly useful to have where *job* names are expected to change now and then, for example in a matrix testing with different versions of a dependency and the version to the matrix job name for clarity.

**Comment by ghost** [comment]
Great suggestion. 

I have an Azure DevOps experience and I was expecting to select a full Workflow definition in this area.

The search for "Status Check" is very messy... I didn't designed my Job names to be unique accross all my different Worklow, so I can't easly understand which job I selected.

**Comment by jmurret** [comment]
we just ran into this and are going to workaround it in the meantime by adding a job at the end of the workflow that needs the others called `<workflow name>-success` and specify this in the branch protection rules.

**Reply by altano** [reply]
I tried this and it doesn't work. The final job will be marked as skipped, and even if required, skipped jobs won't block anything. Required status checks block while in the following states: "not yet run" or "in progress" or "failed". "success" or "skipped" pass the required status check.

**Comment by asos-tommycouzens** [comment]
Hi,

We would really like this too. The workaround jmurret does not work exactly for us, since if it fails at an earlier job it will show the check as still pending and not as failed, since our job as never run. In addition,. when we have workflows with many steps it show as a crazy number of checks (in our case over 100) which creates a lot of noise when we are only running 6 workflows.

![image](https://github.com/community/community/assets/87853606/395f36b0-855e-4f43-ae5d-7ebd203de9b4)

The above screenshot says it is waiting on the Deprovision main job, but actually the workflow looks like this:
![image](https://github.com/community/community/assets/87853606/b24fa269-a630-47e3-89f7-eba7b6549716)

As you can see its actually failed, but it just has not reached the Deprovision Main job and so GitHub still marks it as pending.

**Comment by scottwithbanner** [comment]
Would love a way to configure the workflow to report as a single check on the PR, rather than one check per job.

**Comment by asos-michaelwaterfall** [comment]
Here's an example workaround that's working for us, and deals with job skips, cancellations and failures.

```yml
check-workflow-status:
  name: Check Workflow Status
  runs-on: ubuntu-latest
  needs:
    [
      check-labels,
      run-tests,
      deploy,
    ]
  if: always()
  steps:
    - name: Check Workflow Status
      run: |
        exit_on_result() {
          if [[ "$2" == "failure" || "$2" == "cancelled" ]]; then
            echo "Job '$1' failed or was cancelled."
            exit 1
          fi
        }
        exit_on_result "check-labels" "${{ needs.check-labels.result }}"
        exit_on_result "run-tests" "${{ needs.run-tests.result }}"
        exit_on_result "deploy" "${{ needs.deploy.result }}"
```

Which allows a single required check to cover the whole workflow.

![Screenshot 2025-04-28 at 14 24 36](https://github.com/user-attachments/assets/79a0e353-5234-48b3-9cbf-a4855067dd0a)

An added bonus of this is that checks are now driven by the workflow definition; you can introduce new requirements that gradually make their way into people's PRs. Prior to this, if you add a new required check on a ruleset, it will become instantly required for all open PRs, regardless whether the new job itself has made its way into their branches.

**Reply by BrianValente** [reply]
Works great, thank you!

**Reply by ChristophS-md** [reply]
Based on this, I did it DRYer and added a check that `needs` is complete. (And as for the allowed states, I don't see any reason to allow anything but "success".)

```yaml
check_overall_status:
  needs: …
  if: always()
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v6
    with:
      …
  - name: "check that this job's `needs` is set to exactly all other jobs"
    env:
      THIS_WORKFLOW_FILE: '.github/workflows/test.yml'
      THIS_JOB_NAME: check_overall_status
    run: |-
      diff --minimal --report-identical-files \
        <(yq -r '.jobs | keys() | .[]' <"$THIS_WORKFLOW_FILE" | sort | grep --line-regexp --fixed-strings --invert-match -- "$THIS_JOB_NAME") \
        <(yq -r '.jobs.test.needs[]'   <"$THIS_WORKFLOW_FILE" | sort)

  - name: check overall status
    env:
      JOBS_TO_CHECK_JSON: ${{toJSON(needs)}}
    run: |-
      printf '$JOBS_TO_CHECK_JSON == "%s"\n' "$JOBS_TO_CHECK_JSON" >&2
      jq --raw-output '
          [to_entries[] | select(.value.result != "success")]
          | map((.key + " has status " + (.value.result//"null") + "\n") | halt_error(1))[]
      ' <<<"$JOBS_TO_CHECK_JSON"
```
