### DISCUSSION TITLE
Add job's environment name and URL in the `${{ job }}` context

### DISCUSSION THREAD

**Discussion by samstash** [community/community#12419] [Actions]
It would be useful to provide a job's `environment.name` and `environment.url` in the `${{ job }}` context. This would be particularly helpful for environment names that are generated dynamically–for example, when setting a default for a trigger that doesn't accept inputs:

```yml
name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
jobs:
  deploy:
    name: Deploy
    environment:
      name: ${{ github.event.inputs.environment || 'development' }}
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ job.environment.name }}"
```
