### DISCUSSION TITLE
Unable to Access Environment Variable in GitHub Action Workflow

### DISCUSSION THREAD

**Discussion by frottke** [community/community#124172] [Actions]
### Select Topic Area

Question

### Body

Hello :)

I'm encountering an issue in my workflow/action when trying to retrieve the value of an environment variable. The gh api request works perfectly on my local machine, but when executed within the workflow, I receive the following error:

`gh: Resource not accessible by integration (HTTP 403)`

My Workflow Step:
```
  get-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Get Variable
        run: |
            gh api -X GET /repos/MyRepo/environments/MyEnv/variables/MyVariable --template '{{.value}}'   
```
Troubleshooting Attempts:
I tried modifying the step to the following, which works but does not achieve my intended goal:
```
  get-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Get Variable
        run: |
            gh api -X GET /repos/MyRepo/environments/MyEnv 
```

It appears that the GH_TOKEN does not have access to the required resources. I have already tried setting the permissions to write-all and configured all the necessary settings in the repository.

edit: / added informations: I know that I can use environment: my_environment but I want to get the variable from an other environment without triggering an "deployment"
