### DISCUSSION TITLE
Workflow with pull_request_review trigger also starts on individual PR reply comment

### DISCUSSION THREAD

**Discussion by Piedone** [community/community#124396] [Actions]
### Select Topic Area

Bug

### Body

In [this workflow](https://github.com/OrchardCMS/OrchardCore/blob/fe101c5166fc9f1ce9bc6e1aba53d314245b62cb/.github/workflows/functional_all_db.yml), these are the triggers:

```yml
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'src/docs/**/*'
    branches: [ main, release/** ]
```

`pull_request_review` correctly triggers when a PR review is submitted. However, IMO incorrectly it also triggers when one adds a reply comment to a PR conversations, but without submitting a review.

E.g. I added [this comment](https://github.com/OrchardCMS/OrchardCore/pull/16079#discussion_r1605352678), which triggered [this run](https://github.com/OrchardCMS/OrchardCore/actions/runs/9132029406), and when I added [this comment](https://github.com/OrchardCMS/OrchardCore/pull/16079#discussion_r1605356643), [this run](https://github.com/OrchardCMS/OrchardCore/actions/runs/9132085846) started. In both cases, I did not submit a review, i.e. I did not click this button:

![image](https://github.com/community/community/assets/1976647/15958c5a-47cc-4960-9740-149d34a022fd)

I was just adding comments, directly and immediately, while there were no review comments pending.

[The docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review) are explicit that this is the behavior of [`pull_request_review_comment`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review_comment) instead, so this seems to be a bug to me.
