### DISCUSSION TITLE
Artifact by name not found for same workflow different job but execution time, not supported?

### DISCUSSION THREAD

**Discussion by punkbit** [community/community#124343] [Actions]
### Select Topic Area

Question

### Body

Hi,

I've got a workflow that is split into two jobs. Hypothetically speaking, let's call them job1 and job2. Job1 takes care of uploading a file, and this can run at a particular time before job2. Job2 happens to be executed some time after job1, e.g., a few days after.

Unfortunately, I get the error "Unable to download artefact (s): Artifact not found for name: <NAME>". Although the name exists in a previous workflow execution number, which for the pseudo code below would be the job1 execution! Seems that this is not supported. A bit weird that if that's the case, because I'd like to get the artifact by name at anytime in the future, without necessary knowing what the workflow execution id is necessarily, just based by the name and same branch–the tests were done in the same branch.

These are run from a parent workflow, utilizing the matrix strategy. Below I've shared some pseudo code for illustration.

Parent workflow:

```
on:
  workflow_dispatch:
     inputs:
       environmentTarget:
         options:
           - envA
           - envB
           - envC
       artifact_name:
         description: The name of the artifact
         type: string

jobs:
  jobHost:
     runs-on: ubuntu-latest
     strategy:
        data:
          - dataA
          - dataB
     uses: workflowB.yml
     with:
       environmentTarget: ${{ inputs.environmentTarget }}
```

The workflowB

```
job1:
  if: inputs.environmentTarget == 'envA'
  steps:
      - name: Tar Artifacts
        run: |
          tar -cvf "<NAME>.tar" ./targetDirectory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: <NAME>
          path: "<NAME>.tar"
          retention-days: 90

job2
  if: inputs.environmentTarget == 'envC'
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: <NAME>
        path: ./targetDirectory

```

The `<NAME>` should be interpreted as the actual name as stored and found in the GitHub workflow listed artifact in the run.

In the documentation, it seems to indicate that it is not supported as artifacts are only available for workflow run. It does show that a job id can be specified to extract the artifact https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories which says "It may be useful to download Artifacts from other workflow runs, or even other repositories. By default, the permissions are scoped so they can only download Artifacts within the current workflow run. To elevate permissions for this scenario, you can specify a github-token along with other repository and run identifiers"

So far I'd say that it is not supported, at least for artifacts v4. A run ID and the name are required.

```
steps:
- uses: actions/download-artifact@v4
  with:
    name: <NAME>
    run-id: XXXXXXXXXXXXXXXXX
```
