### DISCUSSION TITLE
Invalid workflow file

### DISCUSSION THREAD

**Discussion by eliassal** [community/community#124684] [Actions]
### Select Topic Area

Question

### Body

Hi, I am following the learning Automate "GitHub by using GitHub Script " at https://learn.microsoft.com/en-us/training/modules/automate-github-using-github-script/3-use-github-script.
When I create a new issue I get invalid yaml error on the statement
`github-token: {% raw %}${{secrets.GITHUB_TOKEN}}{% endraw %}`
as follows
![image](https://github.com/community/community/assets/8447864/5bce745b-c75f-4663-a34d-4c1882b2c14e)

Then I replaced it with
${{secrets.GITHUB_TOKEN}}
First part of works fine for commenting the issue, but declaring a new issue with label = bug I get the following error

> SyntaxError: Unexpected token '{'

![image](https://github.com/community/community/assets/8447864/13e23323-c57e-418a-81b4-76592628b42e)

so why those errors and how they can be fixed? Thanks

**Comment by davevad93** [comment]
Hi @eliassal ,

Try this, I just tested it right now by opening an issue in one of my private repos and it works:

```yml
name: Learning GitHub Script
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on new issue
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🎉 You've created this issue comment using GitHub Script!!!"
          });
    - name: Add issue to project board
      if: contains(github.event.issue.labels.*.name, 'bug')
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.projects.createCard({
            column_id: columnID,
            content_id: context.payload.issue.id,
            content_type: "Issue"
          });
```

**Comment by eliassal** [comment]
Hi, it did not wor, I got another error
![image](https://github.com/community/community/assets/8447864/2a25e670-b84f-41c8-916d-3484dc0bde29)

**Reply by davevad93** [reply]
Hey @eliassal , that's strange as you can see in the screenshot the action run succesfully:

![work](https://github.com/community/community/assets/94308234/6573236a-c80f-448f-8eb2-8bea757c9579)

I don't know why it returns “columnID is not defined” error, lets check a couple of things first:

1. Go to your repo `Settings` => `Actions` => `General` and ensure that the `Workflow permissions` section is set to `Read and write permissions`.

2. Use this in your `yml` file:

```yml
name: Learning GitHub Script
on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on new issue
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🎉 You've created this issue comment using GitHub Script!!!"
          });
    - name: Add issue to project board
      if: contains(github.event.issue.labels.*.name, 'bug')
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.projects.createCard({
            column_id: columnID,
            content_id: context.payload.issue.id,
            content_type: "Issue"
          });
```
Let me know if it works!

**Reply by davevad93** [reply]
![work2](https://github.com/community/community/assets/94308234/203642c7-9e0f-4bb3-87cb-93a7d7c5c0f2)

**Comment by eliassal** [comment]
Hi @davevad93, Workflow permissions section is already set to Read and write permissions. I tried again with new script, getting same error. Couple of questions: 
1 - When you create the issue, do you lable it as BUG?
2 - Is there anything to create, something like a project or configure anything else?
Thanks again

**Reply by davevad93** [reply]
Hi @eliassal and sorry for the late response, 

1. You're right my action was successful because I didn't label the issue as `bug`, to resolve the `columnID is not defined` error you have to create a `secret` (`Settings` => `Secrets and variables` => `Actions`) name it for example `PROJECT_COLUMN_ID` and set an `int` value. I've tested the `yml` file, creating a new project in my repo but the problem now is that it returns the following error:
`RequestError [HttpError]: Must have admin rights to Repository.` 
`Error: Must have admin rights to Repository.`
That's odd considering I obviously have `admin` rights to my repo and I've followed the guidelines regarding permissions for creating project cards in the [docs](https://docs.github.com/en/rest/projects/cards?apiVersion=2022-11-28#create-a-project-card). This is the `yml`:

```yml
name: Learning GitHub Script
on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read
  repository-projects: write
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on new issue
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🎉 You've created this issue comment using GitHub Script!!!"
          });
    - name: Add issue to project board
      if: contains(github.event.issue.labels.*.name, 'bug')
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const columnID = ${{ secrets.PROJECT_COLUMN_ID }};
          github.projects.createCard({
            column_id: columnID,
            content_id: context.payload.issue.id,
            content_type: "Issue"
          });
```

2. Here's the official documentation about [Automating Projects using Actions](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions)
