### DISCUSSION TITLE
GitHub not deploying to WP Engine.

### DISCUSSION THREAD

**Discussion by prussobcm** [community/community#124951] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hi there,
I'm having an issue with deploying from GitHub to WP Engine.

I have two `yml` files one for a `DEV` environment and one for the `PRD` environment. The one below is the `PRD` one.

I only have issues with the `PRD` deployment and not the `DEV` one despite the `yml` files being the same apart from the `WP_ENV` values.

```
name: ❸ Deploy MASTER to WP Engine XXXPRD
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        CACHE_CLEAR: TRUE
        WPE_ENV: xxxprd
```
When I deploy, I can see the changes inside the repo but the Action fails when it comes to deploy to WP Engine. The error that I get is:

```
Connection to xxxprd.ssh.wpengine.net closed by remote host.
Transferred: sent 2292, received 2184 bytes, in 0.4 seconds
Bytes per second: sent 5735.0, received 5464.8
debug1: Exit status -1
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.2.7]
```

When I run `ssh git@git.wpengine.com info` I can see both environments in the list. Which means that the SSH key is not the problem.

Can someone please help me debug this error?
Thanks!!

**Comment by angelo-manalo** [comment]
Troubleshoot and resolve the issue with your WP Engine production deployment.

1. **Check SSH Key Configuration**
   - Ensure the SSH key used for the production environment is correctly set up and has the necessary permissions.
   - Verify that the key matches what WP Engine expects.

2. **Add Verbosity to SSH Command**
   - Modify the YAML file to include detailed logs, which can help identify what is going wrong.

3. **Verify WP_ENV Value**
   - Ensure the `WPE_ENV` value (`xxxprd`) is correct and matches exactly what WP Engine expects.

4. **Compare YAML Files**
   - Carefully compare the DEV and PRD YAML files. Ensure there are no small typos or configuration differences.

5. **Review WP Engine Logs**
   - Check the logs on WP Engine for any specific error messages. They might provide more details about the issue.

### Example YAML File

```yaml
name: Deploy MASTER to WP Engine XXXPRD
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          CACHE_CLEAR: TRUE
          WPE_ENV: xxxprd
        env:
          RSYNC_RSH: 'ssh -vvv'  # Add verbosity to SSH for detailed logs
```

### What to Do Next

1. **Run the Deployment**: Use the modified YAML file to run the deployment again.
2. **Check the Logs**: Look at the logs produced by the GitHub Action. The added `-vvv` option for SSH will provide more detailed information.
3. **Compare DEV and PRD Configurations**: Make sure that all settings (apart from the environment-specific ones) are identical between the DEV and PRD YAML files.

If you follow these steps and still encounter issues, please share any additional error messages or logs, and I’ll help you further.
