### DISCUSSION TITLE
Error: EACCES: permission denied inside runners

### DISCUSSION THREAD

**Discussion by LorenzoRogai** [community/community#125085] [Actions]
### Select Topic Area

Bug

### Body

Was working fine on previous runs, new ones/restarting the previous ones again produces this error. It started appearing after the incident of today

Some examples:

```
node:fs:1222
  return handleErrorFromBinding(ctx);
         ^

Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/serverless/node_modules/.bin'
    at rmdirSync (node:fs:1222:10)
    at _rmdirSync (node:internal/fs/rimraf:235:5)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1271:10)
    at rimrafNativeSync (/usr/local/lib/node_modules/serverless/node_modules/rimraf/dist/commonjs/rimraf-native.js:16:24)
    at /usr/local/lib/node_modules/serverless/node_modules/rimraf/dist/commonjs/index.js:58:45
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/rimraf/dist/commonjs/index.js:42:18)
    at Binary.install (/usr/local/lib/node_modules/serverless/binary.js:100:14)
    at install (/usr/local/lib/node_modules/serverless/binary.js:214:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/run.js:4:1) {
  errno: -[13]
  syscall: 'rmdir',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/serverless/node_modules/.bin'
}
```

https://github.com/flutter/flutter/issues/148761

How to reproduce (test.yml):

```
name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Serverless
        run: sudo npm install -g serverless
      - name: Test
        run: |
          serverless --version
```
