### DISCUSSION TITLE
Is there a way to weave an "or" pattern into Github Actions triggers?

### DISCUSSION THREAD

**Discussion by JJ** [community/community#125153] [Actions]
### Select Topic Area

Question

### Body

If we write something like:

```
on:
    push:
        paths: '*.md'
        tags: '*'
```

it will fire whenever the commit is tagged *and* includes a markdown file. But if we want it to fire when one *or* the other happens? Is there a better way than including whatever steps in a workflow that's triggered by tags?
