### DISCUSSION TITLE
Define values for `inputs` in the `on.push` section

### DISCUSSION THREAD

**Discussion by AlexBurkey** [community/community#125213] [Actions]
### Select Topic Area

Product Feedback

### Body

I don't believe this is supported and I couldn't find any existing discussions on the topic, so creating this one. 

I'd like to be able to define specific values for `inputs` defined in the `workflow_dispatch` section in the various `on.push` portions of the workflow file:

```
name: Deploy My Cool Service
on:
  push:
    branches: [ "dev" ]
    - env: dev
  workflow_dispatch:
    inputs:
      env:
        type: string
        required: true
```

The idea being that in a single workflow I can define inputs on a workflow dispatch and define specific inputs based on different rules. Based on the current setup I don't think this is possible but I wanted to create the discussion anyway to see if there are easier ways of solving it than nesting workflows.

Needing different inputs for different rules could be solved in a way similar to the matrix strategy:
```
name: Deploy My Cool Service
on:
  push:
    - branches: [ "dev" ]
      env: dev
    - branches: [ "main" ]
      env: prod
  workflow_dispatch:
    inputs:
      env:
        type: string
        required: true
```
