### DISCUSSION TITLE
How can I verify that private networking and GitHub-hosted runners still working?

### DISCUSSION THREAD

**Discussion by stan-spotts** [community/community#125402] [Actions]
### Select Topic Area

Question

### Body

I set up a resource group that has an Azure Container Registry on a VNET/subnet, and configured private networking following the instruction here - [Configuring private networking for GitHub-hosted runners in your organization](https://docs.github.com/en/organizations/managing-organization-settings/configuring-private-networking-for-github-hosted-runners-in-your-organization) - and another subnet for it. Last week I was successfully pushing images from source on a GitHub repo to the ACR using this action:

```
        - name: 'Build and push image to ACR'
          uses: docker/login-action@v3
          with:
            registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
```
but now I'm getting this error:

` Error response from daemon: Get "https://***/v2/": dial tcp: lookup *** on 127.0.0.53:53: no such host`

There's a link in the instructions that give troubleshooting tips for the setup, but nothing afterwards. What I'm looking for are ways to troubleshoot the networking side of things to see if something was munged and if I can fix it, or if I nave to rip it out and redo it.
