### DISCUSSION TITLE
How can I fine tune the watch per repository?

### DISCUSSION THREAD

**Discussion by oriongonza** [community/community#125474] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I'd like to watch a repo and get notified only when a PR or issue is open or closed, not on every single thing
which is definitely a thing that is possible if you select it per pr/issue
![image](https://github.com/community/community/assets/47633543/eb447364-39cc-420d-ac9a-76964766be64)
But I'd like to extend it to every issue or PR.
![image](https://github.com/community/community/assets/47633543/289d3114-8f37-4aac-94d2-4fecced187a3)
Those are the only options I have. For large projects I'd like to only get notified on PR and issue open and then I can choose if it interests me enough to actually subscribe.

**Comment by karthickkumarsm** [comment]
To get notified only when a pull request (PR) or issue is opened or closed in a GitHub repository, first, watch the repository and select "Custom" notifications, ensuring "Issues" and "Pull requests" are checked. Since GitHub doesn't directly filter for open/close events in standard settings, use a GitHub Action to send notifications. Create a workflow file in `.github/workflows/` with a script that sends a message when an issue or PR is opened or closed. Alternatively, use GitHub apps or third-party services like Zapier to set up custom notifications that filter for these specific events. This setup ensures you only receive alerts for the actions you care about. @dev-ardi

**Reply by oriongonza** [reply]
Thanks!
do you think you could give me an example of that workflow? I've never used github actions.

**Reply by karthickkumarsm** [reply]
> To get notified only when a pull request (PR) or issue is opened or closed in a GitHub repository, first, watch the repository and select "Custom" notifications, ensuring "Issues" and "Pull requests" are checked. Since GitHub doesn't directly filter for open/close events in standard settings, use a GitHub Action to send notifications. Create a workflow file in `.github/workflows/` with a script that sends a message when an issue or PR is opened or closed. Alternatively, use GitHub apps or third-party services like Zapier to set up custom notifications that filter for these specific events. This setup ensures you only receive alerts for the actions you care about. @dev-ardi

To set up a GitHub Actions workflow that sends notifications when a pull request (PR) or issue is opened or closed, you can create a workflow file in your repository. Here’s a step-by-step example of how to do this:

### Step-by-Step Example

1. **Create the Workflow Directory and File:**
   In your repository, create a directory called `.github/workflows` if it doesn't already exist. Inside this directory, create a file named `notify.yml`.

2. **Define the Workflow:**
   Open `notify.yml` and define the workflow as follows. This example uses a GitHub Action to send notifications via Slack, but you can customize it to use other notification services such as email, Discord, etc.

```yaml
name: Notify on PR or Issue Opened/Closed

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification
      uses: slackapi/slack-github-action@v1.23.0
      with:
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        custom-payload: |
          {
            "text": "A pull request or issue was ${{ github.event.action }}.",
            "attachments": [
              {
                "color": "#36a64f",
                "author_name": "${{ github.actor }}",
                "title": "${{ github.event.pull_request.title || github.event.issue.title }}",
                "title_link": "${{ github.event.pull_request.html_url || github.event.issue.html_url }}",
                "text": "${{ github.event.pull_request.body || github.event.issue.body }}"
              }
            ]
          }
```

### Explanation

- **name**: This is the name of your workflow, which you can customize as desired.
- **on**: This specifies the events that trigger the workflow. In this case, the workflow triggers on issues and pull requests being opened or closed.
- **jobs**: Defines the jobs that run as part of the workflow. Here, we have a single job called `notify`.
- **runs-on**: Specifies the type of runner to use. `ubuntu-latest` is a common choice.
- **steps**: Contains the steps for the job. 
  - **Send notification**: This step uses the `slackapi/slack-github-action` action to send a notification to a Slack channel. You need to set up Slack secrets (`SLACK_BOT_TOKEN` and `SLACK_CHANNEL_ID`) in your GitHub repository secrets settings.

### Setting Up GitHub Secrets

1. Go to your GitHub repository.
2. Click on `Settings`.
3. In the left sidebar, click on `Secrets and variables` and then `Actions`.
4. Click on `New repository secret`.
5. Add `SLACK_BOT_TOKEN` with your Slack bot token.
6. Add `SLACK_CHANNEL_ID` with your Slack channel ID.

### Using Other Notification Services

If you prefer to use another service for notifications (e.g., email, Discord), you can replace the Slack action with an appropriate action for your chosen service. GitHub Actions Marketplace offers a variety of notification actions you can use.

This setup ensures you receive notifications only for the specific actions (opened or closed) you care about, providing a more focused alert system for your repository activities.
