### DISCUSSION TITLE
How do I use the output of call-workflow-in-local-repo ?

### DISCUSSION THREAD

**Discussion by zchenyu** [community/community#125589] [Actions]
### Select Topic Area

Question

### Body

If I have a reusable workflow defined in my local branch, how do I use the output of that workflow in another workflow?

For example:
- `.github/workflows/first.yml`
- `.github/workflows/second.yml`

```
# second.yml
jobs:
  call-workflow-in-local-repo: ./.github/workflows/first.yml
  second:
    steps:
      - name: print
        run: echo ${{ ???.outputs.foo }}
```

If I use `${{ call-workflow-in-local-repo.outputs.foo }}` I get `Unexpected value 'ref' .github/workflows/second.yml (Line: 58, Col: 12): Unrecognized named-value: 'call-workflow-in-local-repo'. Located at position 1 within expression: call-workflow-in-local-repo.outputs.foo`
