### DISCUSSION TITLE
How to Automatically Sync Personal and Organization Repositories Using GitHub Actions?

### DISCUSSION THREAD

**Discussion by fisheva** [community/community#125704] [Actions]
### Select Topic Area

Question

### Body

My personal repository: https://github.com/fisheva/Eva-Theme.  
My organization repository: https://github.com/Eva-Theme/Eva-Theme.  

I want to automatically sync my personal repository to my organization repository. I asked this question to ChatGPT and followed the steps it told me. But the actions failed, and I wonder how to fix it.  

Here is the `.yml` file I wrote based on the answer from chatGPT.  

```yaml
name: Sync to Organization Repo

on:
  push:
    branches:
      - master  # 或你使用的默认分支名

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push changes to organization repository
      run: |
        git config --global user.name 'fisheva'
        git config --global user.email 'fishyu_eva@qq.com'
        git remote add org_repo 'https://x-access-token:${{ secrets.ORG_ACCESS_TOKEN }}@github.com/Eva-Theme/Eva-Theme.git'
        git push org_repo main  # 确保分支名称正确
```

However, all the actions failed.  
![企业微信截图_20240525190835](https://github.com/community/community/assets/17448419/76d6dafa-ff27-40fd-8312-a1cb7e0702c3)

When I click one of the actions, want to find out the failure reason. It goes to the 500 page.  
![企业微信截图_20240525191432](https://github.com/community/community/assets/17448419/2f01cd6a-fadf-4419-bb75-f4dba7e34c1a)

When I asked GPT why the actions failed, it gave too many possible reasons. Now I am asking for help, what should I do to make these actions effective?  

The following is my chat with ChatGPT.  

---
**Me: Could you provide detailed instructions on how to set up automatic synchronization using GitHub Actions?**

**GPT**:  To set up automatic synchronization between your personal repository and an organization repository using GitHub Actions, follow these steps:  

1. Create a New GitHub Action Workflow  

First, you need to create a new GitHub Action workflow in your personal repository. This involves adding a new `.github/workflows` directory to your repository and creating a `.yml` file within that directory.  

2. Write the Workflow File  

In the `.yml` workflow file, you need to define a series of steps that will automatically push changes to the organization repository. Here is a simple workflow example:  

```yaml
name: Sync to Organization Repo

on:
  push:
    branches:
      - main  # Or the default branch you are using

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push changes to the organization repository
      run: |
        git config --global user.name 'Your Username'
        git config --global user.email 'your-email@example.com'
        git remote add org_repo 'https://github.com/your-organization/your-repo.git'
        git push org_repo main  # Ensure the branch name is correct
```

3. Set Up Repository Access Permissions  

Before this GitHub Action can work, you need to ensure that your personal account has permission to push changes to the organization repository. This typically involves the following steps:  

- **Generate an Access Token**: You need to generate an access token from your personal account settings with appropriate permissions, typically needing the `repo` scope.  
- **Set up a Secret in your personal repository**: Go to the “Secrets” section in the settings of your personal repository and add a new Secret named `ORG_ACCESS_TOKEN` with the value being the access token you just generated.  

4. Modify the Workflow to Use the Access Token  

Modify the GitHub Action workflow file to authenticate using the access token you've set:  

```yaml
    - name: Push changes to organization repository
      run: |
        git config --global user.name 'Your Username'
        git config --global user.email 'your-email@example.com'
        git remote add org_repo 'https://x-access-token:${{ secrets.ORG_ACCESS_TOKEN }}@github.com/your-organization/your-repo.git'
        git push org_repo main  # Ensure the branch name is correct
```

With this setup, every time you push changes to the `main` branch of your personal repository, GitHub Actions will automatically push those changes to the organization’s repository, keeping both repositories in sync.  

**Me: What are the steps of Generating a GitHub Access Token?**  
**GPT**:  
1. Sign in to your GitHub account.
2. In the upper-right corner of any GitHub page, click your profile photo, then click "Settings".
3. On the sidebar, click "Developer settings".
4. In the left-hand menu, select "Personal access tokens".
5. Click the "Generate new token" button.
6. In the "Note" field, enter a descriptive name to identify the purpose of this token.
7. In the "Select scopes" section, choose the appropriate permissions based on the operations you need for the repository you wish to automate synchronization with. Typically, selecting `repo` scope is sufficient to cover most actions including access and modification of private repositories.
8. After making your selections, click the "Generate token" at the bottom of the page.
9. Once generated, GitHub will display the new access token. Make sure to copy this token before leaving the page, as it will not be displayed again.

Ensure proper safekeeping of the generated access token as it has the corresponding permissions for your account, and leakage may lead to security risks.
