### DISCUSSION TITLE
can't read secrets in github action

### DISCUSSION THREAD

**Discussion by fospring** [community/community#125969] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Bug

### Body

I set the env in origin repo and my forked repo and set the same secrets.
<img width="783" alt="image" src="https://github.com/community/community/assets/19633691/6bcf3fe2-1dd7-437b-88bc-64d992b18c44">

The secret in my forked repo can be read normally but the secret in my origin repo can't be read correctly.
the core workflow action is:
```
jobs:
  workflows_ubuntu:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: yarn
      - name: Build contract
        run: yarn build
      - name: Set master credentials
        env:
          TESTNET_MASTER_ACCOUNT_WALLET: ${{ secrets.TESTNET_MASTER_ACCOUNT_WALLET }}
#          TESTNETMASTERACCOUNTWALLET: ${{ secrets.TESTNETMASTERACCOUNTWALLET }}
#        run: echo "$TESTNET_MASTER_ACCOUNT_WALLET" > .near-credentials/workspaces/testnet/templateprojectmaster.testnet.json
        run: echo "${#TESTNET_MASTER_ACCOUNT_WALLET}"
```
here is origin repo's ci, read scret length is 0: https://github.com/near/near-sdk-js-template-project/actions/runs/9253241684/job/25452527898?pr=16
<img width="416" alt="image" src="https://github.com/community/community/assets/19633691/497e5ef7-87d1-4110-8b84-619e4bb2e172">

here is my forked repo, read scret length is 227: https://github.com/fospring/near-sdk-js-template-project/actions/runs/9253241514/job/25452775611?pr=1
<img width="470" alt="image" src="https://github.com/community/community/assets/19633691/1c244370-bfb2-48da-bd26-18667e595884">
