### DISCUSSION TITLE
How do I get the current version and PR version of a file with GitHub actions?

### DISCUSSION THREAD

**Discussion by simon-friedberger** [community/community#125920] [Actions]
### Select Topic Area

Question

### Body

I want to compare two files and process the changes. I've currently tried:
```
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: local
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: other
```

but afaict that doesn't give me the actual changes of the PR. Can somebody explain what's happening and what I should use instead? I'm guessing it's somehow related to force pushes or rebases but I'm not sure how to easily test this theory. Pointers on that would be appreciated as well.

And sorry if this is a bad question, this is my first GH action.

**Comment by judahpaul16** [comment]
If the PR was rebased or modified by a force push after the Actions workflow started, the `head.sha` might refer to an older or incorrect commit. You'll want to make sure your workflow triggers handle these updates appropriately. You can use the `on: pull_request` event which triggers the workflow on various types of PR activity, including `synchronize` which occurs after a new commit is pushed to the PR.

After checking out both branches, you can use diff tools or scripts to compare files between the `local` and `other` directories. For example:
```yaml
- name: Compare changes
 run: diff -urN local/path/to/file other/path/to/file
```

To test changes such as rebases or force pushes, you can manually trigger these events in a test repository by creating a pull request, pushing new commits, rebasing, or using force push to update the PR. Observing how GitHub Actions responds to the changes can help you understand and fix whatever issues come up.

Example:
```yaml
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: local

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: other

      - name: Compare files
        run: diff -urN local/ other/ | tee changes.diff

      - name: Process changes if any
        run: |
          if [ -s changes.diff ]; then
            echo "Processing changes..."
            # Add additional steps to process changes
          else
            echo "No changes detected."
          fi
```

Make sure your paths used in `diff` command or any other processing tools match where the files are actually located relative to the root of your repository. Adjust the options in the `diff` command according to your needs; `-urN` is useful for recursively comparing directories while treating absent files as empty.
