### DISCUSSION TITLE
Maintain PRs/Issues from many repos in a project

### DISCUSSION THREAD

**Discussion by grom-it** [community/community#126157] [Projects and Issues]
### Select Topic Area

Question

### Feature Area

Projects

### Body

In our organization multiple teams use the project board to provide an overview of incoming, handled and done PRs from all the repositories they own. To make this working we need to create one workflow per repository to add incoming PRs to the project.

In my team we own 71 repositories. 

Is there any way to automate this or at least make the workflow configuration easier? e.g. a workflow that can be attached to multiple repositories instead of only one?

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).

**Comment by vivekvardhan2810** [comment]
Managing workflows across multiple repositories can be quite challenging, especially when dealing with a large number like 71 repositories. However, there are ways to streamline this process and make workflow configuration easier. Here are some strategies and tools you can use:

### 1. **Reusable Workflows in GitHub Actions**
GitHub Actions allows you to create reusable workflows which can be called from multiple repositories. You can define a workflow in one repository and then reference it in other repositories.

#### Steps to Create a Reusable Workflow:

1. **Create a reusable workflow file in a central repository** (e.g., `workflow-repo`):
   ```yaml
   # .github/workflows/reusable-workflow.yml
   name: Reusable Workflow

   on:
     pull_request:
       types: [opened, reopened, edited]

   jobs:
     add_to_project:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Add PR to project
           uses: actions/add-to-project@v1
           with:
             project_url: ${{ secrets.PROJECT_URL }}
             repo-token: ${{ secrets.GITHUB_TOKEN }}
   ```

2. **Reference the reusable workflow in other repositories**:
   ```yaml
   # .github/workflows/use-reusable-workflow.yml
   name: Use Reusable Workflow

   on:
     pull_request:
       types: [opened, reopened, edited]

   jobs:
     call-reusable-workflow:
       uses: org-name/workflow-repo/.github/workflows/reusable-workflow.yml@main
       with:
         project_url: ${{ secrets.PROJECT_URL }}
       secrets:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   ```

This way, you only need to maintain the workflow logic in one place, and any updates to the workflow can be propagated to all repositories by updating the central file.

### 2. **Using GitHub Actions Templates**
You can create a GitHub Actions template repository that contains the common workflow files. Then, you can use this template repository to create or update workflows across your repositories.

#### Steps to Use Templates:

1. **Create a template repository with the required workflow**.
2. **Use a script to clone and update repositories**:
   ```bash
   # clone-and-update-repos.sh
   TEMPLATE_REPO="https://github.com/org-name/template-repo.git"
   REPOS=("repo1" "repo2" "repo3") # List all 71 repositories

   for repo in "${REPOS[@]}"; do
     git clone "https://github.com/org-name/$repo.git"
     cd "$repo"
     git remote add template $TEMPLATE_REPO
     git fetch template
     git checkout -b update-workflows
     git merge template/main --allow-unrelated-histories
     git push origin update-workflows
     cd ..
     rm -rf "$repo"
   done
   ```

3. **Run the script** to apply the workflow changes to all repositories.

### 3. **Third-Party Tools and Scripts**
There are third-party tools and custom scripts that can help manage multiple repositories and automate workflow configurations.

- **Probot**: A framework for building GitHub Apps to automate and improve your workflow.
- **GitHub CLI**: The GitHub CLI (`gh`) can be scripted to interact with multiple repositories programmatically.

#### Example using GitHub CLI:
```bash
# update-workflows.sh
REPOS=("repo1" "repo2" "repo3") # List all 71 repositories

for repo in "${REPOS[@]}"; do
  gh repo clone org-name/$repo
  cd $repo
  cp ../template-repo/.github/workflows/* .github/workflows/
  git add .github/workflows/
  git commit -m "Update workflows from template"
  git push origin main
  cd ..
  rm -rf $repo
done
```

### 4. **Centralized Configuration Management**
Consider using centralized configuration management tools like Terraform with the GitHub provider to manage repository settings and configurations, including workflows.

#### Example using Terraform:
```hcl
provider "github" {
  token = var.github_token
}

variable "repositories" {
  type = list(string)
  default = ["repo1", "repo2", "repo3"]
}

resource "github_repository_file" "workflow_files" {
  for_each = toset(var.repositories)
  repository = each.value
  file = ".github/workflows/main.yml"
  content = file("path/to/your/workflow.yml")
  commit_message = "Add workflow file"
  branch = "main"
}
```

### Conclusion
By using reusable workflows, templates, scripts, or centralized configuration management tools, you can significantly simplify the process of managing workflows across multiple repositories. Choose the method that best fits your organization’s workflow and infrastructure.
