### DISCUSSION TITLE
How to run certain steps of a job in container (when job is running on host VM)

### DISCUSSION THREAD

**Discussion by HarshadDGhorpade-eaton** [community/community#126133] [Actions]
We need to run some steps of the job in container and some on host, before container kicks in we want to download some files on host and mount these downloaded directories as volumes.

I was trying out below possibility to accomplish this from [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-the-github-packages-container-registry) and found out that even though this step is NOT the first one of the job it tries to pull the image in the very beginning and its failing as its expecting authorization before so I can't even add `docker/login-action` to login to registry.

How to do authorization in this case(to ghcr)? I am aware that it has `args` parameter as well but I think that won't help.

```
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: docker://{host}/{image}:{tag}
```

or is there better way to achieve this use case?

**Comment by judahpaul16** [comment]
First use `docker/login-action` to authenticate with GitHub Container Registry before any Docker operations. Then, execute host-specific tasks, such as file downloads, ensuring these files are available for subsequent steps. Then just mount the volumes to the docker container and profit. Make sure to set your GH_TOKEN in your repository secrets settings should be in https://github.com/your_username/your_repo/settings/secrets/actions. Create the actual TOKEN [here](https://github.com/settings/tokens).
 
```yaml
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Ensure this action has permissions to read the repository contents
      id-token: write  # For logging in to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download files
        run: |
          mkdir -p ${{ github.workspace }}/downloads
          # Replace this with your actual download command
          curl -o ${{ github.workspace }}/downloads/myfile.txt http://example.com/myfile.txt

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/{host}/{image}:{tag}

      - name: Run Docker container
        run: docker run --rm -v ${{ github.workspace }}/downloads:/app/downloads ghcr.io/{host}/{image}:{tag}
        env:
          SOME_ENV_VAR: "value"
```

**Reply by HarshadDGhorpade-eaton** [reply]
@judahpaul16 I think I didn't mention my use case fully but how I will be able to call reusable composite actions in this container now? I want to run all steps under composite action in container.

```
- uses: "org/composite-actions-repo/action/action-name@v0.1"
   with:
     param1: "val1"
```

something like `target` in ADO pipelines for the step

```
- bash: |
      echo "running in container"
  displayName: 'run step in container'
  target:
    container: container_name
```

**Reply by judahpaul16** [reply]
I see I think I misunderstood. GitHub Actions currently does not support directly running steps inside a Docker container started in a previous step. You may need to adapt the actions or maybe modify the Docker image to include a script that runs these actions internally. Or you could use a service container if your actions can run as part of a service or maybe a Docker-in-Docker approach?

<details><summary>Service Approach</summary>
<p>

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14
    services:
      my-service:
        image: my-custom-image
        ports:
          - 8080:80

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Interact with service
        run: |
          curl http://localhost:8080
          echo "Interacted with service running in container"
```
</p>
</details>

<details><summary>Docker-in-docker approach</summary>
<p>

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ''
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker client
        run: |
          apk add --no-cache docker-cli
          docker info

      - name: Build and run container
        run: |
          docker build -t my-image .
          docker run my-image
```
</p>
</details> 

If all else fails maybe consider setting up a self-hosted runner which should give you more control:
<details><summary>Self-hosted runner approach</summary>
<p>

```yaml
# Assuming you have a self-hosted runner set up and registered
jobs:
  custom-job:
    runs-on: self-hosted # specify the label of your self-hosted runner
    container: ubuntu:latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run custom script
        run: |
          echo "Running on a custom action runner inside a container"
          ./run-my-composite-action.sh
```

</p>
</details>
