### DISCUSSION TITLE
Is it possible to make runs-on in workflow templates dynamic, targetting runner groups and/or labels?

### DISCUSSION THREAD

**Discussion by audunsolemdal** [community/community#126264] [Actions] [answered]
### Select Topic Area

Question

### Body

So I use reusable workflows. I am trying to dynamically input either a label or a runner group, but I can't get the correct syntax. I believe I have been able to specify something similar to as `'["labels": { "managed-ubuntu" }]' `, but was unable to get this working for targetting runner groups. I am wondering if anyone has been able to figure out syntax for this?

My use case is that my workflow template usually runs on ubuntu-latest (which is a label)
While sometimes it needs to target a specific runner group. Targetting labels is not an option as it does not seem possible to set labels for Github Enterprise managed runners.

A possible workaround is creating two separate jobs like this:

job 1
```yaml
runs-on:
  group: ${{fromJSON(inputs.runsOnGroup)}}
```

```yaml
runs-on:
  labels: ${{fromJSON(inputs.runsOnLabel)}}
```
But I would like the syntax of my job to be flexible to choosing either a specific runner group or labels.

My Current workflow:

```yaml
on:
  workflow_call:
    inputs:
      runsOn:
        type: string
        description: "(Optional) target specific labels"
        required: false
        default: '["ubuntu-latest"]'
jobs:
  plan:
    name: My job
    runs-on: ${{fromJSON(inputs.runsOn)}} # Works for labels, unable to get this to target a runner group.
```

**Comment by ChristopherHX** [comment]
Something like that should work
```yaml
 runsOn: |-
        {
          "group": "managed-ubuntu"
        }
```

You seem to use a different object structure in Json, than you do in yaml.

For example
> `["labels": { "managed-ubuntu" }]`

is not valid json, because labels is not allowed to be followed by a : in an array also is labels an array not an object.
