### DISCUSSION TITLE
Action stuck in queue for over a day and then failing

### DISCUSSION THREAD

**Discussion by theinfamouscoder5** [community/community#126219] [Actions] [answered]
### Select Topic Area

Bug

### Body

 I created a workflow on one of my repositories that publishes an image. It is stuck in the queue forever and won't continue. I have tried re-running the workflow and it doesn't work. If you have any fixes please let me know! Thanks in advance.
![image](https://github.com/community/community/assets/165951965/2aaacec0-90bd-459f-aa51-795db04d3038)

**Comment by judahpaul16** [comment, marked as answer]
Check your `runs-on: ` line. Make sure it's a valid virtual environment. should look something like this:

```yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push to Docker Hub
        run: |
          timeout 3600 docker buildx build --platform linux/arm64 --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/gpt-home:latest --push .

      - name: Build and push to GHCR
        run: |
          timeout 3600 docker buildx build --platform linux/arm64 --no-cache -t ghcr.io/${{ github.repository_owner }}/gpt-home:latest --push .
```
