### DISCUSSION TITLE
Local custom github action not invoked

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#126259] [Actions]
### Select Topic Area

Question

### Body

I am trying to invoke a custom github action which is in the same repository as the invoking workflow. I am invoking it like this

```yaml
        - name: test action
          uses: MyOrg/MyRepo/.github/actions/my_action@master
          with:
            image: localhost/test-image:latest
            my_secret: ${{ secrets.MY_SECRET }}
```

However I get `Unable to Resolve Action`

The file is there:

```
ls .github/actions/my_action.yaml 
```

What is the correct syntax for this use case?
