### DISCUSSION TITLE
GitHub Action synchronization between two repos

### DISCUSSION THREAD

**Discussion by pradeepshekhawat29** [community/community#126247] [Actions]
### Select Topic Area

Question

### Body

Hello All,

_Below is my question:_

I have two GitHub repos under the same org, one if for automation tests and another one is for application code(dev repo). The use case is :
- We want to trigger tests in the tests repo whenever there is a new PR in the dev repo and **[DONE]**
- Want to ensure that the workflow in your development repository(first part) waits for the tests in the test repository to complete and then based on the outcome it marks build failed/pass

**I am using below workflow in dev to trigger the tests:**
name: Workflow Trigger in Test Automation Repo
on:
  pull_request:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Tests
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: org/cypress-growth
          event-type: cypress-cloud-tests-triggered-by-pr
          
          
          **I would appreciate if anyone can guide me on how to achieve the second part of implementation.**

**Comment by mranv** [comment]
To achieve the second part of your implementation, where the workflow in the development repository waits for the tests in the test repository to complete and marks the build as failed or passed based on the outcome, you can follow these steps:

1. **Trigger a workflow in the test repository**

   You've already implemented this part using the `peter-evans/repository-dispatch` action. This action triggers a workflow in the test repository whenever a pull request is created or updated in the development repository.

2. **Wait for the test workflow to complete**

   In the development repository, you'll need to add a step that waits for the test workflow to complete. You can use the `tjenkinson/gh-action-wait-for-workflow` action for this purpose.

   Add the following step to your workflow in the development repository:

   ```yaml
   - name: Wait for Test Workflow
     uses: tjenkinson/gh-action-wait-for-workflow@v1
     with:
       token: ${{ secrets.GITHUB_TOKEN }}
       repository: org/cypress-growth
       workflowName: 'Name of the workflow in the test repository'
       ref: ${{ github.event.pull_request.head.sha }}
   ```

   Replace `'Name of the workflow in the test repository'` with the actual name of the workflow in the test repository that was triggered by the `peter-evans/repository-dispatch` action.

3. **Check the test workflow status**

   After the previous step completes, you can check the status of the test workflow and mark the build as failed or passed accordingly.

   Add the following step to your workflow in the development repository:

   ```yaml
   - name: Check Test Workflow Status
     id: check-test-status
     run: |
       TEST_WORKFLOW_STATUS=$(curl --silent "https://api.github.com/repos/org/cypress-growth/actions/runs?event=repository_dispatch&status=success&branch=main" | jq '.workflow_runs[0].conclusion')
       echo "Test Workflow Status: $TEST_WORKFLOW_STATUS"
       if [ "$TEST_WORKFLOW_STATUS" == '"success"' ]; then
         echo "Test workflow passed"
         exit 0
       else
         echo "Test workflow failed"
         exit 1
       fi
   ```

   This step uses the GitHub API to retrieve the status of the latest successful workflow run triggered by the `repository_dispatch` event in the test repository. It checks the `conclusion` field of the workflow run, which can be either `success` or `failure`. Based on the conclusion, it exits with a success (0) or failure (1) status code.

4. **Add the step as a required check for the pull request**

   To ensure that the development repository's pull request checks the test workflow status before merging, you can add the `Check Test Workflow Status` step as a required check.

   Add the following step to your workflow in the development repository:

   ```yaml
   - name: Mark Pull Request Status
     uses: Automatically1111/action-pull-request-status@master
     if: always()
     with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
       status-message: "Test workflow ${{ steps.check-test-status.outcome }}"
       status-state: ${{ job.status }}
   ```

   This step will update the pull request status with the outcome of the `Check Test Workflow Status` step. If the test workflow passed, the pull request status will be marked as `success`. If the test workflow failed, the pull request status will be marked as `failure`.

With these steps, your workflow in the development repository will trigger tests in the test repository, wait for the tests to complete, check their status, and mark the pull request accordingly based on the test outcome.
