### DISCUSSION TITLE
Reactions on issue comments

### DISCUSSION THREAD

**Discussion by davorg** [community/community#126366] [Actions]
### Select Topic Area

Question

### Body

I've been playing with the following action to investigate triggering a workflow when an issue comment gets a reaction (i.e. someone clicks one of the emoji reactions to a comment).
name: Test issue comment stuff

```
on:
  issue_comment:
    type: edit

jobs:
  test:
    name: debug
    runs-on: ubuntu-latest

    steps:
      - name: print whole context
        env:
          GITHUB_CONTEXT:  ${{ toJson(github) }}
          VARS_CONTEXT:  ${{ toJson(vars) }}
        run: |
          echo "GITHUB_CONTEXT is $GITHUB_CONTEXT"
          echo "VARS_CONTEXT is $VARS_CONTEXT"
```

When I edit the text of the comment, then this is triggered and the JSON I get from the GitHub context contains details of the reactions on the comment. But if I add a new reaction, the workflow doesn't get run.

Is there any other way to trigger a workflow on an emoji reaction to an issue comment?
