### DISCUSSION TITLE
How to get an arch linux codespace?

### DISCUSSION THREAD

**Discussion by FunnyCheese4Me** [community/community#126419] [Codespaces] [answered]
### Select Topic Area

Question

### Body

I a trying to build a project that requires arch linux, as it won't work on other distros. How do I create an arch linux based codespace?

**Comment by judahpaul16** [comment, marked as answer]
Create an Arch Linux Dockerfile and run the devcontainer with the docker image.

`Dockerfile`
```dockerfile
# Use the latest Arch Linux base image
FROM archlinux:latest

# Update system and install base-devel group
RUN pacman -Syu --noconfirm base-devel

# Install other necessary packages
RUN pacman -S --noconfirm git vim python

# Any other setup steps
```

Then instruct GitHub Codespaces to build this Docker environment when initializing your codespace.

`.devcontainer/devcontainer.json`
```json
{
  "name": "Arch Linux Codespace",
  "build": {
    "dockerfile": "Dockerfile"
  },
  "settings": {},
  "extensions": [],
  "postCreateCommand": "echo 'Environment ready!'"
}
```

**Reply by FunnyCheese4Me** [reply]
Okay I'll try that.

**Reply by FunnyCheese4Me** [reply]
This worked! Thank you so much!

**Comment by Jimmybillbob0102** [comment]
I get sent to recovery container

**Comment by Kreijstal** [comment]
@FunnyCheese4Me  the correct solution is too minimal try this one
on 
`.devcontainer/Dockerfile`

```Dockerfile
FROM archlinux:latest

# Update and install base dependencies, sudo, git, and github-cli
# Also install 'which' as it's often used by scripts and might be missing
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm bash sudo git github-cli which less && \
    pacman -Scc --noconfirm

# Create the codespace user with a home directory, add to wheel group (for sudo)
# Set bash as the default shell
RUN useradd -m -G wheel -s /bin/bash codespace && \
    echo 'codespace ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/codespace && \
    chmod 0440 /etc/sudoers.d/codespace
```

`/.devcontainer/devcontainer.json`
```yaml
{
  "name": "Arch Linux Codespace with Dockerfile",
  "build": {
    "dockerfile": "Dockerfile"
  },
  "remoteUser": "codespace",
   "containerEnv": {
    "GIT_EDITOR": "code --wait"
  },
  "postStartCommand": "echo \"Attempting to configure Git. GIT_COMMITTER_NAME='${GIT_COMMITTER_NAME}', GIT_COMMITTER_EMAIL='${GIT_COMMITTER_EMAIL}'\"\nCURRENT_GIT_USER=$(git config --global --get user.name)\nCURRENT_GIT_EMAIL=$(git config --global --get user.email)\necho \"Current git config user.name='${CURRENT_GIT_USER}', user.email='${CURRENT_GIT_EMAIL}'\"\nif [ -z \"${GIT_COMMITTER_NAME}\" ] || [ -z \"${GIT_COMMITTER_EMAIL}\" ]; then\n  echo 'Warning: GIT_COMMITTER_NAME or GIT_COMMITTER_EMAIL is empty. Cannot automatically configure Git identity from these. Attempting gh auth setup-git.'\n  if command -v gh >/dev/null && gh auth status >/dev/null 2>&1; then\n    echo 'GitHub CLI is installed and authenticated. Running gh auth setup-git...'\n    gh auth setup-git\n    echo \"Git config after gh auth setup-git: user.name='$(git config --global user.name)', user.email='$(git config --global user.email)'\"\n  else\n    echo 'Warning: GitHub CLI not available or not authenticated. Please configure git manually: git config --global user.name \\\"Your Name\\\" && git config --global user.email \\\"you@example.com\\\"'\n  fi\nelif [ -z \"${CURRENT_GIT_USER}\" ] || [ -z \"${CURRENT_GIT_EMAIL}\" ] || [ \"${CURRENT_GIT_USER}\" != \"${GIT_COMMITTER_NAME}\" ] || [ \"${CURRENT_GIT_EMAIL}\" != \"${GIT_COMMITTER_EMAIL}\" ]; then\n  echo 'Configuring Git user name and email using Codespaces environment variables...'\n  git config --global user.name \"${GIT_COMMITTER_NAME}\"\n  git config --global user.email \"${GIT_COMMITTER_EMAIL}\"\n  echo \"Git configured with user: $(git config --global user.name), email: $(git config --global user.email)\"\nelse\n  echo 'Git user name and email already configured and match GIT_COMMITTER variables.'\nfi\necho 'Final git config:'\ngit config --global --list | grep user",

  "customizations": {
    "vscode": {
      "settings": {
        "terminal.integrated.defaultProfile.linux": "bash",
        "terminal.integrated.profiles.linux": {
          "bash": {
            "path": "/bin/bash"
          }
        }
      }
    }
  }
}
```

This will make git be already integrated with github codespaces, so you dont need to register twice with git just like with the ubuntu images
