### DISCUSSION TITLE
How To Configure Postgres Service in Github Actions

### DISCUSSION THREAD

**Discussion by jvanderen1** [community/community#126453] [Actions] [answered]
### Select Topic Area

Question

### Body

I am wondering, how would I configure the `postgres` service? For example, I need to be able to change the `wal_level` to `logical`.

```yml
name: Build and Test Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    services:
      postgresql:
        image: postgres:14.7
        env:
          POSTGRES_USER: pg_user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
```

I have the following steps to change the `wal_level`:

```yml
      - name: Create Database
        env:
          PGPASSWORD: "password"
        run: psql -h localhost -U pg_user -c 'CREATE DATABASE "my_db";'

      - name: Change wal_level
        env:
          PGPASSWORD: "password"
        run: |
          psql -h localhost -U pg_user -d my_db -c "ALTER SYSTEM SET wal_level = 'logical';"

      - name: Print Services
        run: service --status-all

      - name: Restart Postgres Service
        run: service postgresql restart

      # This prints out `replica`
      - name: Verify wal_level
        env:
          PGPASSWORD: "password"
        run: psql -h localhost -U pg_user -d my_db -c "SHOW wal_level;"
```

There appears to be a `systemctl` version of postgres I am restarting and not the job-level postgres service. Are we able to restart this service? If not, how can I configure it's `wal_level`?

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by sleepy-analyst** [comment, marked as answer]
To change the wal_level setting for the PostgreSQL service running within your GitHub Actions workflow, you should configure it through the `postgresql.conf` file or use an environment variable during the service setup. However, directly modifying the `postgresql.conf` file in the GitHub Actions environment might not be straightforward due to the containerization.

A more effective approach would be to use environment variables to configure PostgreSQL parameters when starting the container. Unfortunately, `wal_level` is not configurable through environment variables directly. So the practical approach here is to modify the `postgresql.conf` file and restart the PostgreSQL service within the container itself.

Here’s a modified version of your workflow that attempts to achieve this by creating a custom entrypoint for the PostgreSQL container to modify the configuration and then restart the service:

```

name: Build and Test Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    services:
      postgresql:
        image: postgres:14.7
        env:
          POSTGRES_USER: pg_user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        ports: ["5432:5432"]
```

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create init-db.sh
        run: |
          echo '#!/bin/bash' > init-db.sh
          echo 'echo "ALTER SYSTEM SET wal_level = '\''logical'\'';" > /docker-entrypoint-initdb.d/001-wal_level.sql' >> init-db.sh
          echo 'pg_ctl -D "$PGDATA" restart' >> init-db.sh
          chmod +x init-db.sh

      - name: Create Database
        env:
          PGPASSWORD: "password"
        run: psql -h localhost -U pg_user -c 'CREATE DATABASE "my_db";'

      - name: Print Services
        run: service --status-all

      # This prints out `logical`
      - name: Verify wal_level
        env:
          PGPASSWORD: "password"
        run: psql -h localhost -U pg_user -d my_db -c "SHOW wal_level;"

In this workflow:
1. An `init-db.sh` script is created dynamically in the workflow and placed in the `/docker-entrypoint-initdb.d` directory within the PostgreSQL container.
2. This script includes commands to change the wal_level and restart the PostgreSQL service.
3. The volumes option in the services configuration mounts this script into the container.

This approach leverages PostgreSQL's support for initializing scripts placed in the `/docker-entrypoint-initdb.d` directory and ensures the `wal_level` is set to logical upon container startup and configuration change.

**Reply by DohanKim** [reply]
it seems postgresql in 'services' is running before 'steps' are started.
so creating init-db.sh in steps won't be reflected when starting PostgreSQL service.

**Comment by DohanKim** [comment]
FYI, this works for me.

```
 steps:
      - name: Set wal_level to logical
        run: PGPASSWORD=postgres psql -h localhost -U postgres -c "ALTER SYSTEM SET wal_level = 'logical';"

      - name: Restart Postgres
        env:
          PGPASSWORD: "postgres"
        run: docker restart $(docker ps -q --filter "ancestor=postgres:16.4")

      - name: Print Services
        run: service --status-all

      - name: Verify wal_level
        env:
          PGPASSWORD: "postgres"
        run: psql -h localhost -U postgres -d sendman_test -c "SHOW wal_level;"
```
