### DISCUSSION TITLE
How to conditionally skip a job based on variable with dynamically set environment?

### DISCUSSION THREAD

**Discussion by mzdr** [community/community#126647] [Actions]
### Select Topic Area

Question

### Body

Hey there,

I was wondering if the following is possible:
    
    
```yaml
name: Periodic checks

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: "Manually check target environment"

jobs:
  run:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    # CHECKS_ENABLED is defined in the environment variables section, so per environment.
    if: vars.CHECKS_ENABLED == 'true'
    steps:
      # …
```

For some reason `vars.CHECKS_ENABLED` is empty, even though I have defined it in my e.g. "development" environment variables. I have the impression I can't do it like that and need to throw in an additional job that exposes the environment variables via job outputs, because I would have access to the proper environment variables inside of the job steps.

I basically want to skip a specific job if the environment variable is set to a certain value. Anyone any suggestions?
