### DISCUSSION TITLE
Can't access requirements.cgroup: v1 lxc container images

### DISCUSSION THREAD

**Discussion by kenhys** [community/community#126676] [Actions] [answered]
### Select Topic Area

Bug

### Body

# Problem

On GitHub Actions, it can execute a lxc container image.
But recently I've noticed that lxc container image which
requires CGroupV1 host environment can't accessible anymore.

On ubuntu-20.04 host, it is expected to be able to launch cgroup v1 lxc container image.
 
# Actual

Previously, the following lxc container images were launched correctly on `ubuntu-20.04`.

* images:centos/7
* images:amazonlinux/2
* images:amazonlinux/2023

But these container images can't be launched anymore.

It is strange behavior that from CGroupV2 host (e.g `runs-on: ubuntu-latest`), above images are visible. (e.g. `lxc image list images:`)
(Surely they can't be launched at all, so it is useless)

From CGroupV1 host, list of lxc container images is empty. (unexpected result, they should be listed) 

```
  To start your first container, try: lxc launch ubuntu:20.04
  Or for a virtual machine: lxc launch ubuntu:20.04 --vm
  
  +-------+-------------+--------+-------------+--------------+------+------+-------------+
  | ALIAS | FINGERPRINT | PUBLIC | DESCRIPTION | ARCHITECTURE | TYPE | SIZE | UPLOAD DATE |
  +-------+-------------+--------+-------------+--------------+------+------+-------------+
  + echo ::endgroup::
```

# How to reproduce

* Use `runs-on: ubuntu-20.04` (CGroupV1 host)
* Try to launch cgroup v1 image

It raises the following error:

```
Error: Failed getting image: The requested image couldn't be found
  Error: Process completed with exit code 1.
```

Here is the sample .github/workflows/linux.yml:

```
name: Check available lxc images
on:                        
  push:                           
    branches:                                                         
      - main               
  pull_request:                                                       
jobs:                            
  test:                                                               
    name: Test                                                                                                                              
    runs-on: ubuntu-20.04
    strategy:                                                         
      fail-fast: false                                                
      matrix:                                                         
        label:
          - CentOS 7
        include:                                                      
          - label: CentOS 7
            image: images:centos/7
    steps:    
      - uses: actions/checkout@master
      - uses: canonical/setup-lxd@v0.1.1
      - name: ${{ matrix.label }}
        run: ./launch.sh ${{ matrix.image }}
```

Here is the sample launch.sh:

```
#!/bin/bash

set -eux

image=$1

echo "::group::Run test: launch $image"
lxc launch $image target
sleep 5
echo "::endgroup::"
```
