### DISCUSSION TITLE
Why is this action being triggered?

### DISCUSSION THREAD

**Discussion by dominikwilkowski** [community/community#126646] [Actions]
### Select Topic Area

Question

### Body

I have this action:

```yml
on:
  workflow_call:
  push:
    paths:
      - website/**

jobs:
  deploy:
    name: Publish to Github Pages
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
```

It's supposed to only run on changes inside the website folder and when it's being called via another workflow.
I just published a tag and it triggered this workflow... Is the `if` somehow overriding the `on` trigger?

Here is the relevant action that was triggered by the tag publishing: https://github.com/dominikwilkowski/vault/actions/runs/9309768085
