### DISCUSSION TITLE
How to reference an object key in a excluded list

### DISCUSSION THREAD

**Discussion by rafaellages-hotmart** [community/community#126763] [Actions]
### Select Topic Area

Question

### Body

Hi, I have the folowing workflow file:

```yaml
jobs:
  notify:
    strategy:
      matrix:
        shouldNotifyReviewAndDeploy:
          - ${{ contains(github.event.inputs.file , 'production') }}
        chat_channel:
          - name: ReviewAndDeploy
            channel: 'googlechat.loooooooooong.url'
          - name: Frontends
            channel: 'googlechat.loooooooooong.url2'
        exclude:
          - shouldNotifyReviewAndDeploy: false
            chat_channel.name: ReviewAndDeploy
```
I want to notify review and deploy only on production deploys, but github gives me this error:
`Matrix exclude key 'chat_channel.name' does not match any key within the matrix`

Any ideas how to make it without having to write the google chat long urls twice?

Many thanks
