### DISCUSSION TITLE
Are actions containing using of PHPUnit broken?

### DISCUSSION THREAD

**Discussion by deepeloper** [community/community#126955] [Actions]
### Select Topic Area

Bug

### Body

phpunit.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  bootstrap="../../vendor/autoload.php"
  cacheResult="true"
  colors="true"
  xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.2/phpunit.xsd"
  cacheDirectory=".phpunit.cache"
>

  <coverage>
    <report>
      <clover outputFile="../output/phpunit.coverage-clover.xml"/>
      <html outputDirectory="../output/code-coverage"/>
    </report>
  </coverage>

  <testsuites>
    <testsuite name="Testsuite">
      <directory suffix="Test.php">../../tests</directory>
    </testsuite>
  </testsuites>

  <logging/>

  <source>
    <include>
      <directory suffix=".php">../../src</directory>
    </include>
  </source>

</phpunit>
```
ci-coverage.yml
```yml
name: CI-coverage

on: [push]

jobs:
  build-test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          php_version: "8.2"
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: build/config/phpunit.xml
          args: --display-warnings --display-errors --coverage-text
```
produces
```
PHPUnit 11.1.3 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.2.8 with Xdebug 3.2.2
Configuration: /app/build/config/phpunit.xml
.....                                                               5 / 5 (100%)
Time: 00:00.226, Memory: 41.73 MB
There was 1 PHPUnit test runner warning:
1) Using comma-separated values with --test-suffix is deprecated and will no longer work in PHPUnit 12
WARNINGS!
Tests: 5, Assertions: 8, Warnings: 1.
```

**Comment by billythekid** [comment]
Hi @deepeloper :wave:

I'd recommend raising an issue with https://github.com/php-actions/phpunit if you believe this is incorrect behaviour of that Actions workflow.

**Comment by deepeloper** [comment]
Hello @billythekid,
At https://github.com/php-actions/phpunit unfortunately no answer.
At "produces" section I displayed warning `1) Using comma-separated values with --test-suffix is deprecated and will no longer work in PHPUnit 12`, but I don't use `--test-suffix` argument according to "phpunit.xml" and "ci-coverage.yml" sections.

**Comment by deepeloper** [comment]
I spent about 3 hours to fix it )))

```yaml
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          test_suffix: "Test.php" # THIS IS THE FIX
```
By default ACTION_TEST_SUFFIX environment variable equals to "Test.php,.phpt", better to make this information more public.
