### DISCUSSION TITLE
Githbub Action is not triggering

### DISCUSSION THREAD

**Discussion by konsalex** [community/community#12717] [Projects and Issues] [answered]
Hey there,

I am facing an issue with the Github Actions.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/12672541/157930730-a4839f1d-4e0e-4ffc-ac69-5ab959cc0943.png">

While I have three workflows that are supposed to be executed on pull requests, suddenly the testing workflow stopped:

This is the one that stopped
```
name: Testing build
on: [push, pull_request]

jobs:
  install-cache:
    name: Install and cache npm dependencies
    runs-on: ubuntu-latest
    if: ${{ !env.ACT }}
    ....
```

And the below is working as expected 

```
name: Welcome contributors
on:
  pull_request_target:
    branches:
      - main

jobs:
  welcome-contributors:
    runs-on: ubuntu-latest
    steps:
      ....
```

Any clue how to solve this and why this is happening?
