### DISCUSSION TITLE
Providing a `slug` function to make URL save variables

### DISCUSSION THREAD

**Discussion by csvn** [community/community#127106] [Actions]
### Select Topic Area

Product Feedback

### Body

Currently it is impossible to use the branch name with `job.environment.url`, as it can easily break on non-url-safe characters:

```yml
jobs:
  deploy-preview:
    environment:
      name: preview
      url: https://${{ github.ref_name }}.dev.example.com/
      # https://fix/my-bug.dev.example.com/ for fix/my-bug branch
```

Gitlab CI has four environment variables with slug values that are suitable to use when creating URLs for deployments or other places we need safe values for URLs:
- `CI_COMMIT_REF_SLUG`
- `CI_JOB_NAME_SLUG`
- `CI_PROJECT_PATH_SLUG`
- `CI_ENVIRONMENT_SLUG`

It would be very nice to have similar functionality with Github Actions, e.g. using a slugified `github.ref_name` as subdomain for a branch PR. Github Actions has an advantage though, by [adding a new expression function](https://docs.github.com/en/actions/learn-github-actions/expressions#functions), we can convert any value to a URL safe slug.

```yml
env:
  REF_NAME_SLUG: ${{ slug(github.ref_name) }}
jobs:
  deploy-preview:
    environment:
      url: https://${{ env.REF_NAME_SLUG }}.dev.example.com/
```

RIght now we need to create either a bash script or action to convert an existing value to a URL-safe version, which is not possible to use with `job.environment.url`. As an example:

```yml
    - uses: ./.github/actions/ref-name-slug
      id: slug
    - run: npx netlify-cli deploy --alias ${{ REF_NAME_SLUG }}
      env:
        REF_NAME_SLUG: ${{ github.steps.slug.ref-name }}
```

If there was a `slug()` function we could replace the above with:

```yml
    - run: npx netlify-cli deploy --alias ${{ slug(github.ref_name) }}
```

### `slug(value)` function

The `slug()` function could work as it does in most other tools (markdown, SSGs, etc).

- Convert characters matching e.g. `/^[a-z0-9\-_]/i` to `-`
  - Only keep letters, digits, `-` & `_` as-is
- Collapse multiple `-` in a row to a single `-`
- Trim leading/trailing dashes
