### DISCUSSION TITLE
Can I limit dependabot to only open PRs when items in requirements txt have related CVE?

### DISCUSSION THREAD

**Discussion by YesThatAllen** [community/community#127267] [Code Security] [answered]
### Select Topic Area

Question

### Body

I've got dependabot configured in a private repo, where it's scanning our requirements txt file and generating PRs for outdated modules.

fwiw, the file isn't named `requirements.txt` rather, `pip-reqs.txt` but dependabot didn't have a problem finding it so long as we included `directory: "/Resources/Python-framework-tool"`.

The issue we face is that there are 100+ `pyobjc-*` modules which are out of date from the current v10 which most have.

The PRs to bump `pyobjc-[whichver]` don't reference any CVE.. they feel like suggestions to update for the sake of updating.

I suppose I can ignore those and maybe dependabot will eventually get to some modules which have related CVE, but I wonder.. can I make an adjustment our current file which would say "only create an alert if the upgrade would fix a known vulnerability?

```yml
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/Resources/Python-framework-tool" # Location of package manifests
    schedule:
      interval: "weekly"
```
