### DISCUSSION TITLE
Dependabot opens individual PRs as well as PRs for groups

### DISCUSSION THREAD

**Discussion by conan** [community/community#127248] [npm]
### Select Topic Area

Question

### Body

We're using the group support in `dependabot.yml` to try to group PRs by package ecosystem.  We have many npm locations (e.g. for AWS lambdas) and want to keep dependencies in sync across all of them, so we don't ever want an update that only affects a single `package.json`.

Dependabot creates grouped PRs correctly, but for the npm package ecosystem using `directories:` it also creates an individual PR for every update.  How can we prevent this?  It doesn't happen for the gradle package ecosystem.  

Note that these are not security updates, we have no security bulletins for these bumps.

Our `dependabot.yml`:

```yaml
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directories:
      - "directory1"
      - "directory2"
      - "directory3"
      - "directory4"
      - "directory5"
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"   
```

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by geniuszly** [comment]
To prevent Dependabot from opening individual pull requests (PRs) in addition to grouped ones for the npm package ecosystem, you need to ensure that the grouping configuration is applied correctly across all specified directories. Dependabot can sometimes create individual PRs if it detects that the configuration isn't fully applied or if there's a conflict in how the updates are being grouped. 

Make sure that the `patterns` and `update-types` settings in your `dependabot.yml` are correctly configured to group all npm updates under the specified directories. If the problem persists, try using a single directory entry that covers all npm locations. This can be achieved by specifying a parent directory that includes all your `package.json` files or by listing them under one entry instead of multiple. For example:
```yaml
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "/"  # Use a single directory that covers all npm locations
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
```
Dependabot might still create individual PRs if it sees the need for separate updates, especially if the configurations for the npm locations are not uniform. To disable individual PRs, ensure that all updates are captured by the `patterns` and `update-types` settings under the `groups` key.
If you are using multiple directories under the npm ecosystem, ensure that there is no overlap that might cause Dependabot to treat them separately. Consider consolidating the directories into one, if possible. Ensure you are using the latest Dependabot version as there may have been updates or bug fixes addressing this behavior. If it's a known issue, it might be resolved in a newer version.
