### DISCUSSION TITLE
Why does the postgres service fail when connecting a second time in github tests?

### DISCUSSION THREAD

**Discussion by Ukie1** [community/community#12721] [Actions]
I am using [github actions][1] to test on push to our github repository.

Short version: I test the Postgres connection with `psql` (success), perform some other actions, then test the connection again with `psql`, and the second connection test fails as if Postgres has quit.  Why?  How do I fix this?

NOTE: Several pull requests were able to connect to postgres for about a day before they all started failing, so I know I was able to get the config right. In fact, the difference between working and not working in our repo was someone editing a .txt file that was just a TODO list (no code impact)!

Long version with details:

Postgres is set up as follows:

```
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        # should match python in runtime.txt
        python-version: [3.8.12]

    services:
      postgres1:
        image: postgis/postgis:13-3.2
        env:
          POSTGRES_USER: postuser
          # needs a password
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: postdb
        ports:
          - 5432:5432 # exposing 5432 port for application to use
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready --health-interval 10s
          --health-timeout 5s --health-retries 5
```

Then the connection is tested as follows:

```
    - name: Test database connection
      run: |
        # for psql
        sudo apt-get install -y postgresql-client
        # Test psql connection
        PGPASSWORD=mysecretpassword psql -h localhost -p 5432 -U postuser -d postdb -c "select 1"
```

**This connection test succeeds** as follows:

```
Unpacking postgresql-client-12 (12.9-0ubuntu0.20.04.1) ...
Selecting previously unselected package postgresql-client.
Preparing to unpack .../postgresql-client_12+214ubuntu0.1_all.deb ...
Unpacking postgresql-client (12+214ubuntu0.1) ...
Setting up postgresql-client-12 (12.9-0ubuntu0.20.04.1) ...
Setting up postgresql-client (12+214ubuntu0.1) ...
Processing triggers for postgresql-common (238.pgdg20.04+1) ...
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
  en_us
Removing obsolete dictionary files:
 ?column? 
----------
        1
(1 row)
```

Then there are several other steps:

```
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install apt packages
      run: |
        sudo apt-get update -y && \
        sudo apt-get upgrade -y && \
        sudo apt-get install -y \
          binutils \
          libproj-dev \
          gdal-bin
        # needed for pycurl.
        # see https://stackoverflow.com/a/24051044
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev
    - name: Install dependencies
      run: |
        pip install -r requirements-test.txt
```

Then there is another Postgres connection test (exactly the same code as above, cut and paste).  **This test fails** as follows:

```
postgresql-client is already the newest version (12+214ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
psql: error: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
Error: Process completed with exit code 2.
```

**What would make this connection test fail the second time?  Did postgres quit?  Why would it quit?**

NOTE: I've read advice about whether I should connect to `postgres1` (the name in the config) or `localhost`, but `localhost` works (the first time).  Also, if I try connecting to `postgres1`, it fails (the first time) with

```
psql: error: could not translate host name "postgres1" to address: Temporary failure in name resolution
```

so `localhost` is definitely correct for github.

**EDIT**: I wonder if installing `psql` changes the config on disk, which causes postgres to restart, and it is not yet up again.

NOTE: If I take out both `psql` tests, then my Django tests can't connect, so the DB still seems gone.

  [1]: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
