### DISCUSSION TITLE
"paths" filter in workflow_dispatch trigger

### DISCUSSION THREAD

**Discussion by Agnes3478** [community/community#127339] [Actions]
### Select Topic Area

Question

### Body

Hello Everyone, 
I am new Github user and I am using "pull_request" to trigger an action whenever there is a pull request event to main branch.
here is my yaml file. I want only some files change could trigger the action.

```
name: test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'myfolder/test_abc.py'

jobs:
  unit-tests:
    runs-on: [ self-hosted ]
    name: Run unit tests
    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Print message
       run: echo "Workflow triggered by changes in myfolder directory"
     
```

my question is that the "paths" filter result is different with expected.
**Expected result**:
only test_abc.py file triggers the action.

**Actual result**:
Besides test_abc.py, other files in other folders also trigger the action.

I also tried following, but the result is that: no file triggers the action.
```
on:
  pull_request:
    branches:
      - main
    paths:
      - 'myfolder/**'
    paths-ignore:
      - '**'
      - '!myfolder/**'
      
```

I also tried many other syntax base on the documentation.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

but the result is not as expected. could you teach me how to filter the path that only specific files could trigger the action.
thank you.
