### DISCUSSION TITLE
Passing secrets to reusable workflow should take list of secret names

### DISCUSSION THREAD

**Discussion by jasonkarns** [community/community#127428] [Actions]
### Select Topic Area

Product Feedback

### Body

It's quite redundant to list a bunch of secrets when you're mapping from and to the same name:

```yml
jobs:
  stuff:
    uses: org/.github/.github/workflows/workflow.yml
    secrets:
      NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      SSH_TOKEN: ${{ secrets.SSH_TOKEN }}
```

Why can't we just list the names of the secrets to pass through? If the names don't match, then sure, use the explicit map form. But in the most common scenario, just list the names to pass through. It's like a slightly more explicit form of `inherit` (except usable in cases where `inherit` isn't; like cross-org).

```yml
jobs:
  stuff:
    uses: org/.github/.github/workflows/workflow.yml
    secrets:  [ NPMJS_TOKEN, BOT_TOKEN, COMMITTER_TOKEN, SSH_TOKEN ]
```
