### DISCUSSION TITLE
A bug that caused issue submission to fail

### DISCUSSION THREAD

**Discussion by zhongfly** [community/community#12745] [Projects and Issues] [answered]
If the label does not contain english characters and is required, it will cause the issue to fail to submit.

Try this issue template:
```yaml
name: Test
description: Test
title: "Test"
body:
  - type: checkboxes
    attributes:
      label: verify
      description: verify
      options:
      - label: 测试
        required: true
```
or you can test it on my repo: https://github.com/zhongfly/issue/issues/new?assignees=&labels=&template=feature_request.yml&title=Test
