### DISCUSSION TITLE
Action to automatically add a card to a project?

### DISCUSSION THREAD

**Discussion by jehtee** [community/community#127754] [Actions]
### Select Topic Area

Question

### Body

I've been trying to write the action yml and python script to automating adding a new card to a project every time a an issues is created from a specific template.

I've been working with the docs, co-pilot and ever GPT.  No matter what, I cannot get my workflow to add a card to a project.  It does everything else that it is supposed to.  This is the only failure.

Can someone explain how to accomplish this?  

Here is my yml:
```
name: Minimal Opportunity Init

on:
  issues:
    types: [opened, edited]  # Trigger the workflow when an issue is opened or edited

jobs:
  create-repo:
    runs-on: ubuntu-latest
    if: github.event.issue  # This check is redundant as the workflow only triggers on issue events
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.8'

      - name: Install PyGithub
        run: pip install PyGithub

      - name: Run Python Script
        run: python opportunity-init.py
        env:
          SEC_OPPORTUNITY_INIT: ${{ secrets.SEC_OPPORTUNITY_INIT }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}  # Pass the issue body as an environment variable
          PROJECT_ID: '11'  # Add this line
          PROJECT_COLUMN_ID: 'f75ad846'  # Add this line
```

And here is my python function:

```
add_to_project(user, repo):
    """Add a card to a project."""
    token = os.getenv('SEC_OPPORTUNITY_INIT')
    headers = {
        'Authorization': f'Bearer {token}',
        'Content-Type': 'application/json',
    }
    url = 'https://api.github.com/graphql'
    query = """
    mutation ($projectColumnId: ID!, $content: String!) {
      addProjectCard(input: {content: $content, projectColumnId: $projectColumnId}) {
        clientMutationId
        cardEdge {
          node {
            projectColumn {
              project {
                name
                id
                owner {
                  __typename
                }
              }
            }
          }
        }
      }
    }
    """
    project_column_id = os.getenv('PROJECT_COLUMN_ID')
    content = f"Opportunity: {repo.name}"
    variables = {
        'projectColumnId': f"ProjectColumn{project_column_id}",
        'content': content,
    }
    data = {
        'query': query.strip(),
        'variables': variables,
    }
    print(f"Attempting to create card '{content}' in project column ID '{project_column_id}'")
    response = requests.post(url, headers=headers, data=json.dumps(data))
    if response.status_code == 200:
        response_data = response.json()
        if 'data' in response_data and 'addProjectCard' in response_data['data']:
            project_name = response_data['data']['addProjectCard']['cardEdge']['node']['projectColumn']['project']['name']
            project_id = response_data['data']['addProjectCard']['cardEdge']['node']['projectColumn']['project']['id']
            owner_type = response_data['data']['addProjectCard']['cardEdge']['node']['projectColumn']['project']['owner']['__typename']
            print(f"Card '{content}' added to project '{project_name}' (ID: {project_id}) of type '{owner_type}'.")
        else:
            print(f"Unexpected response content: {response.content}")
    else:
        print(f"Failed to add card to project. Status code: {response.status_code}, Response content: {response.content}")    
```
