### DISCUSSION TITLE
Could ubuntu runner use zram ?

### DISCUSSION THREAD

**Discussion by Stargateur** [community/community#127786] [Actions]
### Select Topic Area

Product Feedback

### Body

We have problem with not enough memory for linking phase. Could it be possible to have extra ram using zram ? It's faster than using a swap file. Currently, the runner Ubuntu don't have the module so it's impossible to activate. Would be great for ubuntu-24.04.

**Comment by kalishxern** [comment]
```
- name: Swap (zram + fallback swapfile)
  run: |
    sudo apt-get update
    if sudo apt-get install --no-install-recommends --yes "linux-modules-extra-$(uname -r)" && sudo modprobe zram; then
      sudo apt-get install -y zram-tools
      echo -e "ALGO=lz4\nPERCENT=200\nPRIORITY=32766" | sudo tee /etc/default/zramswap
      sudo systemctl restart zramswap.service
    else
      echo "zram module unavailable this run, skipping"
    fi

    sudo fallocate -l 12G /swapfile #adjust, could be 4G
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon -p 10 /swapfile

    swapon --show
    free -h
```
Just that good idea to have this first
```
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
```
