### DISCUSSION TITLE
[install boost] b2.exe silently failed on image windows-2022

### DISCUSSION THREAD

**Discussion by redboltz** [community/community#127795] [Actions]
### Select Topic Area

Question

## Overview

When I try to install boost from the source code on `windows-2022` image, `b2.exe` is silently failed. But on `windows-2019` image, it works fine.

### Steps
1. Download boost 1.85.0 (7z)
2. Extract it.
3. Run `bootstrap.bat`
4. Run `b2.exe`

In order to specify the issue, I run `b2.exe --help`. Even if this command, it is failed on on `windows-2022` image.

I guess that it is something environmental issue. 

I attached two yml files. That is minimal reproduced the issue. The only diffrerence is `runs-on: windows-2022` or `runs-on: windows-2019`.

## runs-on: windows-2022 (Failed)

```yml
name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - main
    tags:
    - '*'
jobs:
  windows:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: install boost
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        pwd
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.85.0/source/boost_1_85_0.7z"
         (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost_1_85_0.7z")
        7z.exe x "$env:TEMP\boost_1_85_0.7z"
        cd boost_1_85_0
        .\bootstrap.bat
        .\b2.exe --help
```
- github link: 
  - https://github.com/redboltz/gha_install_boost/blob/5fc04126b35a1907246b3c08724f7650725627da/.github/workflows/gha.yml
- output:
  - https://github.com/redboltz/gha_install_boost/actions/runs/9427661751/job/25972081492

### Environment

```
Current runner version: '2.317.0'
Operating System
  Microsoft Windows Server [2](https://github.com/redboltz/gha_install_boost/actions/runs/9427661751/job/25972081492#step:1:2)022
  10.0.20348
  Datacenter
Runner Image
  Image: windows-2022
  Version: 2024060[3](https://github.com/redboltz/gha_install_boost/actions/runs/9427661751/job/25972081492#step:1:3).1.0
  Included Software: https://github.com/actions/runner-images/blob/win22/202[4](https://github.com/redboltz/gha_install_boost/actions/runs/9427661751/job/25972081492#step:1:4)0603.1/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240[6](https://github.com/redboltz/gha_install_boost/actions/runs/9427661751/job/25972081492#step:1:7)03.1
Runner Image Provisioner
  6.0.3[7](https://github.com/redboltz/gha_install_boost/actions/runs/9427661751/job/25972081492#step:1:8)0.1
```

## runs-on: windows-2019 (Success)

```yml
name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - main
    tags:
    - '*'
jobs:
  windows:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: install boost
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        pwd
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.85.0/source/boost_1_85_0.7z"
         (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost_1_85_0.7z")
        7z.exe x "$env:TEMP\boost_1_85_0.7z"
        cd boost_1_85_0
        .\bootstrap.bat
        .\b2.exe --help
```

- github link: 
  - https://github.com/redboltz/gha_install_boost/blob/c60f556fa342656789eed27b12bb057fc8821e76/.github/workflows/gha.yml
- output:
  - https://github.com/redboltz/gha_install_boost/actions/runs/9427648241/job/25972053641

### Environment

```
Current runner version: '2.317.0'
Operating System
  Microsoft Windows Server [2](https://github.com/redboltz/gha_install_boost/actions/runs/9427648241/job/25972053641#step:1:2)019
  10.0.17763
  Datacenter
Runner Image
  Image: windows-2019
  Version: 2024060[3](https://github.com/redboltz/gha_install_boost/actions/runs/9427648241/job/25972053641#step:1:3).1.0
  Included Software: https://github.com/actions/runner-images/blob/win19/202[4](https://github.com/redboltz/gha_install_boost/actions/runs/9427648241/job/25972053641#step:1:4)0603.1/images/windows/Windows2019-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win19%2F20240[6](https://github.com/redboltz/gha_install_boost/actions/runs/9427648241/job/25972053641#step:1:7)03.1
Runner Image Provisioner
  2.0.3[7](https://github.com/redboltz/gha_install_boost/actions/runs/9427648241/job/25972053641#step:1:8)0.1
```
