### DISCUSSION TITLE
Action events not triggered after changing Github Account type.

### DISCUSSION THREAD

**Discussion by acuD1** [community/community#127890] [Actions]
### Select Topic Area

Bug

### Body

Hi,

I changed this morning the account type of my company, which is now an Organization. However, all the CI are not responding across all project. Looks like the event is not triggered.

I deactivated and re-activated all permission just in case, but no luck.

Should I contact the support or is there something I might miss ?

<img width="1071" alt="image" src="https://github.com/community/community/assets/43761367/156535e9-8cf4-4ed6-b879-2c1eb0737105">
<img width="342" alt="image" src="https://github.com/community/community/assets/43761367/1a2223db-c9ea-40ca-867e-0a1d75bb7d38">

**Comment by DaOneLuna** [comment]
I appear to be having this same issue. Updated an account from an individual to an organization and now none of the workflows are triggering. Does not work when using manual dispatch as well. 
```
on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - master
      ```
