### DISCUSSION TITLE
[bug] Schedule event's multiple conditions are judged by OR conditions, not AND conditions

### DISCUSSION THREAD

**Discussion by gkzz** [community/community#12804] [Actions] [answered]
### Describe the bug
- Multiple conditions are judged by OR conditions, not AND conditions
https://github.com/gkzz/actions-playground/actions/runs/1998183036

```yaml
on:
  schedule:
#    - cron: '00 5 16-17 * 4' # At 02:00 pm on every day-of-month from 16 through 17 and on Thursday. (JST)
# Expected not to call a worklfow by the following cron expression
    - cron: '00 11 16-17 * 5' # At 08:00 pm on every day-of-month from 16 through 17 and on Friday. (JST)
```

- Also runs when both the date/time condition and day-of-week specification are TRUE.
https://github.com/gkzz/actions-playground/actions/runs/1996732316

```yaml
on:
  schedule:
    - cron: '00 5 16-17 * 4' # At 02:00 pm on every day-of-month from 16 through 17 and on Thursday. (JST)
```

### Expected behavior
- Cron calls Workflow only if all conditions are TRUE

### Notes
- It is unverified, yet seems to be similar to the following.
  - [github - Schedule on weekdays - Stack Overflow](https://stackoverflow.com/questions/69198734/schedule-on-weekdays)

- Cron expression with a combination of date and time, except day of week works.
https://github.com/gkzz/actions-playground/runs/5514202576

```yaml
on:
  schedule:
#    - cron: 45 16 10-11 * 5
    - cron: 45 16 10-11 * * 
```
