### DISCUSSION TITLE
Can I use configuration variables in a workflow trigger?

### DISCUSSION THREAD

**Discussion by nnellanspdl** [community/community#128264] [Actions]
### Select Topic Area

Question

### Body

Is this possible?

In my testing, it doesn't appear to be working.  The variable is not getting expanded (I assume), and the workflow is not being triggered.

Example:
```yaml
on:
  push:
    branches: ${{ vars.ON_PUSH_BRANCHES }}
```

I could not find any direct references to such a use-case in the documentation.
