### DISCUSSION TITLE
Escaping a special characters in a Github Action

### DISCUSSION THREAD

**Discussion by adamdjbrett** [community/community#128282] [Actions] [answered]
### Select Topic Area

Question

### Body

I am trying to implement a GitHub action that will convert xml to json and then commit the JSON to the repository. I have successfully tested the scripts and actions by [@fabasoad](https://github.com/fabasoad). However when implementing the script on my XML feed I am getting some errors due to the special characters in the feed. Since I cannot control what characters are in the feed what can I do to have the Github action ignore the special characters specifically (). I have tried googling but since I am so new to Github Actions, the results have not been helpful. Please advise.

Error message:
```
/home/runner/work/_temp/4c49208e-f014-4864-acc5-6faf2579a31f.sh: line 67: syntax error near unexpected token `('
Error: Process completed with exit code 2.
```

- [Github Actions Log File](https://github.com/adamdjbrett/relcfp/actions/runs/9487287476/job/26143548131#step:8:989)
- [Github Actions Code](https://github.com/adamdjbrett/relcfp/blob/main/.github/workflows/cronjob.yml)

```yaml
# This is a basic workflow to help you get started with Actions

name: Daily rebuild

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 12 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      #         with:
      #           repository: adamdjbrett/relcfp
      #           token: ${{ secrets.RELCFPCHRONJOB }}

      - name: Make executeable
        run: chmod +x ./get_rss.sh
      # Runs a single command using the runners shell
      - name: Get RSS
        run: ./get_rss.sh
      - name: Add & Commit
        uses: EndBug/add-and-commit@main
        with:
          add: feed.xml
      - name: Use Github App
        uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Data Format Converter Action
        uses: fabasoad/data-format-converter-action@main
        id: xml2json
        with:
          input: "feed.xml"
          from: "xml"
          to: "json"
          token: ${{ steps.generate-app-token.outputs.token }}
      - name: Print result
        run: |
          echo  '${{ steps.xml2json.outputs.output }}' > feed.json
      - run: cat 'feed.json'
      - name: Configure Git
        run: |
          git config --global user.name 'adamdjbrett'
          git config --global user.email '22662978+adamdjbrett@users.noreply.github.com'
      - name: Commit and push changes
        run: |
          git add 'feed.json'
          git commit -m 'Save output to file'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  
      - name: Deploy to Netlify
        uses: lwojcik/github-action-deploy-static-site@v1
        with:
          platform: netlify
          netlify_deploy_hook_url: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
          always_deploy: true
```

**Comment by spenserblack** [comment, marked as answer]
Try putting that value in an environment variable and printing it that way.
```yaml
name: Print result
run: echo "$RESULT" > feed.json
env:
  RESULT: ${{ steps.xml2json.outputs.output }}
```
