### DISCUSSION TITLE
How to combine CodeQL with existing build jobs to avoid lengthy builds

### DISCUSSION THREAD

**Discussion by LordOfDragons** [community/community#128302] [Actions]
### Select Topic Area

Question

### Body

I'm trying to add CodeQL to my repositories. With small repositories the default way works fine but I've got also a large repository. With this repository nightly builds take up 30mins for doing all the builds. For CodeQL I need only one of those builds but it takes over 20mins to build. It is a waste of time to build the code two times just to run CodeQL on the second build. It would be much better if I could add the CodeQL to the existing build job to avoid building twice to do the testing. I could though not figure out if this is possible and what it takes to get it working.

**Comment by mbg** [comment]
Hi @LordOfDragons 👋🏻 

Thanks for the question. You should be able to do this by adding the `codeql-action/init` and `codeql-action/analyze` steps to your normal build workflow just before and just after your build step(s), respectively. In essence, you want something like this:

```yaml
- # any setup steps you have to install language-specific tooling etc.

- uses: github/codeql-action/init@v3
  with:
    languages: # your language(s) here

- # your build step(s)

- uses: github/codeql-action/analyze@v3
```

CodeQL will automatically trace build steps that follow the `init` Action. You will however need to ensure that you perform a _full_ build and don't e.g. rely on any sort of build cache for this.

See also the [documentation for advanced setup](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/configuring-advanced-setup-for-code-scanning) and  [configuring advanced setup](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning).
