### DISCUSSION TITLE
Docker login to private registry fails on normal run but succeeds when job is run with debugging enabled - timeout?

### DISCUSSION THREAD

**Discussion by robin-checkmk** [community/community#128570] [Actions]
### Select Topic Area

Bug

### Body

So I want to pull images from a private registry to spin up service containers for my GitHub Actions.
```
my_container:
  image: my.registry.example/my_container:latest
  credentials:
    username: my_user
    password: my_password
```
Now when I run it just like that the job fails at the login step. Re-running the job in debug mode works, however. My intuition tells me, that in debug mode, timeouts are higher, allowing the login to succeed.

When doing a `docker login` locally, it works just fine, the only thing I notice is, that it literally takes some seconds.

I could not find anything about timeouts on the Internet for this topic. It seems like the only available configuration is the `username` and `password`.

If there is no solution, I would also take workarounds, like uploading the image by other means, so we can skip the `docker login` altogether.

Any help is appreciated!
