### DISCUSSION TITLE
How to use $GITHUB_WORKSPACE ?

### DISCUSSION THREAD

**Discussion by sprintersb** [community/community#128541] [Actions]
### Select Topic Area

Question

### Body

In a `.github/workflows` yml file, I want to set some environment variables like so:
```yml
name: some-name

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ## PREFIX: ${{ env.GITHUB_WORKSPACE }}/install # doesn't work
      # Doesn't work either, $GITHUB_WORKSPACE doesn't get expanded
      PREFIX: $GITHUB_WORKSPACE/install
```
But then when a step is being run, the log displays:
```none
env:
    PREFIX: $GITHUB_WORKSPACE/install
```
so no variable resolution has been taken place.

I know I can use `$GITHUB_WORKSPACE` in a step like:
```yml
      - name: echo GITHUB_WORKSPACE
        run: "echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
```
however setting `PREFIX` (or `export`ing it) at that place won't work because it is not available in other steps. As far as I understand, each step is being run in ints own shell.
