### DISCUSSION TITLE
Persisting issue with GitHub action to create workflow even after adding workflow scope and checking all the boxes

### DISCUSSION THREAD

**Discussion by cdeachaval** [community/community#128679] [Actions]
### Select Topic Area

Question

### Body

Here are the steps I followed:
1. Created a Personal Access Token in Github developer settings
2. Set the scope of the token to workflow
3. Added the token to my repo's Secrets under name GH_PAT
4. created a yml file with the workflow instructions, including the authentication step:

```
name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev
      - test
      - prod
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Authenticate with GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        echo "Authenticated with GitHub using a Personal Access Token"
```

Getting this error but obfuscated the [account] and [repo_name] variables

```
To https://github.com/[account]/[repo_name].git
 ! [remote rejected] feature/add-git-workflow -> feature/add-git-workflow (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/deploy.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/[account]/[repo_name].git'
```

Any advise on how to push this yml file successfully will be much appreciated. Thanks!
