### DISCUSSION TITLE
Dependabot group minor.patch changes and create indyvidual PRs for Mayor.minor.patch changes

### DISCUSSION THREAD

**Discussion by nibexo** [community/community#128875] [Repositories]
### Select Topic Area

Question

### Body

I configured depnedabot to group minor and patch changes in one PR, and I would like to dependabot was creating individual PRs for dependencies which has Mayor change 

```
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
```

As I noticed grouping works and creating individual for PR for Mayor changes also, but it create PR for update for example from `2.5.6` to `3.0.0` even when there is available `3.2.5` version. Is there possibility to dependabot in such case was creating indyvidual PR for update from `2.5.6` to `3.2.5` and if there will be released version 3.2.6 then to update this individual PR?
