### DISCUSSION TITLE
Not able to move to c/inetpub/wwwroot folder

### DISCUSSION THREAD

**Discussion by bhs8ban** [community/community#128822] [Actions]
### Select Topic Area

Show & Tell

### Body

I am working on the GitHub action pipeline for deploying apps.net core application on the windows on premise server.
I made that windows server as the self hosted runner. I was able code check out and dotnet build and dotnet clean
I am not able to move into the folder c/inetpub/wwwroot/project folder where I can publish the dotnet publish results.
before I thought to take back up of that folder and clear the earlier published result so that I can publish new results in the c/inetpub/wwroot/project_folder.
I am not able to CD other than github working directory.

**Comment by WaterSwallow** [comment]
It seems like you've successfully set up a GitHub Actions pipeline for an ASP.NET Core application on a self-hosted runner on a Windows server, which is great. The issue you're encountering is moving into a specific folder `c/inetpub/wwwroot/project` to publish your build results.

In GitHub Actions, `cd` (change directory) commands don't persist across steps because each step runs in its own process in the runner’s environment. To execute commands in a specific directory you have a few options:

1. Use the `working-directory` key.

```yaml
- name: Execute commands in a specific directory
  run: dotnet publish -o ./published
  working-directory: c/inetpub/wwwroot/project
```

2. Use `cd` in the same step followed by the command.

```yaml
- name: Execute commands in a specific directory
  run: |
    cd c/inetpub/wwwroot/project
    dotnet publish -o ./published
```

Ensure the path `c/inetpub/wwwroot/project` is correct. Usually, paths in Windows are represented with backslashes, like `C:\inetpub\wwwroot\project`.

Also, using GitHub Actions to modify the file system outside the runner's workspace can be tricky due to permissions. If the problem persists after checking your paths and considering the way GitHub Actions handles the `cd` command, it might be a permissions issue. You should verify that the self-hosted runner has the necessary permissions to access and write to the `c/inetpub/wwwroot/project` directory.

**Comment by bhs8ban** [comment]
Hello 
C:\inetpub\wwwroot\project this path is correct there are erliar published results area available we get error if we publish new results.
Is there any way to take back up and clear old published results

**Reply by suhaib-mousa** [reply]
Yes, you can take a backup of the existing files and clear the old published results before publishing the new ones. Here's how you can do it in your GitHub Actions workflow:

1. **Backup the current published results.**
2. **Clear the folder.**
3. **Publish the new results.**

Here’s an updated GitHub Actions workflow:

```yaml
name: Deploy .NET Core Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x' # specify your .NET Core version

    - name: Build with dotnet
      run: dotnet build

    - name: Publish with dotnet
      run: dotnet publish -c Release -o ./publish

    - name: Backup and Clear WWWRoot
      run: |
        if (Test-Path -Path "C:/inetpub/wwwroot/project") {
          $timestamp = (Get-Date).ToString("yyyyMMddHHmmss")
          Rename-Item -Path "C:/inetpub/wwwroot/project" -NewName "C:/inetpub/wwwroot/project_backup_$timestamp"
          New-Item -ItemType Directory -Force -Path "C:/inetpub/wwwroot/project"
        }
      shell: pwsh

    - name: Deploy to WWWRoot
      run: |
        Copy-Item -Path ./publish/* -Destination "C:/inetpub/wwwroot/project" -Recurse -Force
      shell: pwsh
```

### What This Does:

1. **Checkout code**: Downloads your code from GitHub.
2. **Set up .NET Core**: Prepares the .NET Core environment.
3. **Build with dotnet**: Builds your application.
4. **Publish with dotnet**: Puts the built files in a folder called `./publish`.
5. **Backup and Clear WWWRoot**:
   - Checks if the `project` folder exists.
   - If it does, renames it to include a timestamp, creating a backup.
   - Creates a new empty `project` folder.
6. **Deploy to WWWRoot**: Copies the new published files to `C:/inetpub/wwwroot/project`.

This way, you always have a backup of the old results and a clean folder for the new publish.
