### DISCUSSION TITLE
Dependency Conflict in Flutter App During GitHub Action Deployment

### DISCUSSION THREAD

**Discussion by RanenduKarmakar1997** [community/community#128942] [Actions]
### Select Topic Area

Question

### Body

Hi GitHub Community,

I am encountering an issue with my GitHub Actions workflow while deploying a Flutter web app to Firebase Hosting. My workflow is failing due to a dependency conflict.

**Error Message**:
Because `apc_app` depends on `alyf_prov_package` from git which depends on `http ^0.13.5`, `http ^0.13.5` is required.
So, because `apc_app` depends on `http ^1.1.1`, version solving failed.

**Details**:
- I have updated the `http` version to `^1.1.1` in my `alyf_prov_package` repository also for `apc_app`.
- My `apc_app` is referencing the updated `alyf_prov_package`.
- I have ensured that all changes are pushed to the correct branch.
- Running `flutter pub get` locally resolves dependencies without any issues.

**GitHub Actions Workflow**:
```yaml
name: deploy apc dev(apc-dev-alyf-health)
on: 
  push:
    branches:
      - apc-dev
      - dev-logger
jobs:
    deployment:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: |
                            ${{ secrets.SSH_PRIVATE_KEY }}
                            ${{ secrets.SSH_PRIVATE_KEY_ALYF_PROV_PKG }}
        
        - uses: subosito/flutter-action@v1
          with:
            channel: 'stable'
        - name: Build Website
          run: |
            flutter clean
            flutter pub get
            flutter pub upgrade
            flutter build web --release -t lib/main_dev.dart
          working-directory: ./
        - name: Deploy Firebase Hosting
          uses: w9jds/firebase-action@v12.9.0 
          with:
            args: deploy --only hosting:apc-dev-alyf-health
          env:
            FIREBASE_TOKEN: ${{ secrets.APC_NEW_FIREBASE_TOKEN }}
            PROJECT_PATH: ./

**Comment by odelyo** [comment]
To resolve the dependency conflict in your GitHub Actions workflow for deploying your Flutter web app to Firebase Hosting, you can follow these steps:

1. Ensure Correct Dependency Versions:
Make sure that both your apc_app and the alyf_prov_package are using compatible versions of the http package. From your error message, it looks like alyf_prov_package is requiring http ^0.13.5, but apc_app is trying to use http ^1.1.1. This conflict occurs because these versions are incompatible.

2. Update alyf_prov_package Dependency:
Since your apc_app requires http ^1.1.1, you should update the alyf_prov_package to also use http ^1.1.1.

In alyf_prov_package, update your pubspec.yaml:
```
dependencies:
  http: ^1.1.1
```
3. Push Changes to alyf_prov_package:
Make sure to commit and push these changes to the correct branch that your apc_app is referencing.

4. Update GitHub Actions Workflow:
Ensure that your workflow is pulling the latest changes from alyf_prov_package. Your current workflow appears to handle this, but it's essential to verify that the latest changes are being fetched correctly.

5. Run flutter pub get Locally:
Before pushing changes, ensure you run flutter pub get locally on your apc_app to verify that the dependencies resolve correctly.

6. Clear Dependency Cache:
In some cases, GitHub Actions may use cached dependencies. To ensure that your workflow isn't using outdated dependencies, consider clearing the cache before running the build.

Add the following step to your workflow before flutter pub get:
```
- name: Clear Dependency Cache
  run: flutter clean
```
7. Re-run GitHub Actions Workflow:
Once everything is updated and pushed, re-run the GitHub Actions workflow to see if the dependency conflict is resolved.

Updated Workflow Example:
Here’s an updated version of your workflow that includes clearing the cache:
```
name: deploy apc dev(apc-dev-alyf-health)
on: 
  push:
    branches:
      - apc-dev
      - dev-logger
jobs:
    deployment:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: |
                            ${{ secrets.SSH_PRIVATE_KEY }}
                            ${{ secrets.SSH_PRIVATE_KEY_ALYF_PROV_PKG }}
        
        - uses: subosito/flutter-action@v1
          with:
            channel: 'stable'
        - name: Clear Dependency Cache
          run: flutter clean
        - name: Build Website
          run: |
            flutter pub get
            flutter pub upgrade
            flutter build web --release -t lib/main_dev.dart
          working-directory: ./
        - name: Deploy Firebase Hosting
          uses: w9jds/firebase-action@v12.9.0 
          with:
            args: deploy --only hosting:apc-dev-alyf-health
          env:
            FIREBASE_TOKEN: ${{ secrets.APC_NEW_FIREBASE_TOKEN }}
            PROJECT_PATH: ./

```

**Comment by everforyou** [comment]
Hello @RanenduKarmakar1997

You can resolve the dependency conflict in your Flutter app during the GitHub Actions deployment, follow these steps:

1. **Check Dependency Versions**: Ensure that the versions of the `http` package in both `apc_app` and `alyf_prov_package` are compatible. Since `alyf_prov_package` depends on `http ^0.13.5`, you should make sure that `apc_app` also uses a compatible version of `http` (at least `0.13.5`).

2. **Update `pubspec.yaml`**: In your `apc_app`'s `pubspec.yaml`, explicitly specify the `http` package version to match the required version:
   ```yaml
   dependencies:
     http: ^0.13.5
     alyf_prov_package:
       git:
         url: <repository_url>
   ```

3. **Run Locally**: After updating the `pubspec.yaml`, run `flutter pub get` locally to ensure that all dependencies resolve correctly without conflicts.

4. **Check Branches**: Make sure you are pushing changes to the correct branch that your GitHub Actions workflow is monitoring.

5. **GitHub Actions Workflow**: Verify that your GitHub Actions YAML file is correctly set up and that it is pulling the latest changes from your repository. You may want to include a step to display the current dependencies and their versions in the workflow logs for debugging.

6. **Clear Cache**: Sometimes, caching issues can cause conflicts. You can clear the cache in your GitHub Actions by adding a step to remove the `.pub-cache` directory:
   ```yaml
   - name: Clear Pub Cache
     run: flutter pub cache repair
   ```

7. **Debugging**: Add a step to print the output of `flutter pub deps` to help you understand the dependency tree and identify any conflicts:
   ```yaml
   - name: Print Dependencies
     run: flutter pub deps
   ```

8. **Re-run the Workflow**: After making these changes, push your updates and re-run the GitHub Actions workflow to see if the issue is resolved.

I hope this helps you.
