### DISCUSSION TITLE
gh pr merge --auto --merge fails sometimes

### DISCUSSION THREAD

**Discussion by tha-nordiq** [community/community#129063] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi i hope someone can help me understand whats going on.
I have a dependabot opening up pull requests that i want automatically merged
so i set up an action like so
```
name: "Dependabot Automerge - Action"

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: automerge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
And it works most of the time, but sometimes it fails (lets say 1/4 times ) with "GraphQL: Pull request Protected branch rules not configured for this branch (enablePullRequestAutoMerge)"
If i retry the same pull request it works. (dependabot recreate)
I dont see what relevance the error message has. I dont have paid github, so i cant set up branch protection, and i dont think more rules will help.
Anyone with a similar setup, or knowledge that can help?

One clue to the puzzle / red herring: it always seem to fail in pairs, so when a pull request fails there are always at least 2 pull requests that are not merged
