### DISCUSSION TITLE
value for inputs through Github UI for caller workflows

### DISCUSSION THREAD

**Discussion by Mr-Saikiran** [community/community#129096] [Actions] [answered]
### Github Actions

How to inject values to inputs from Github UI instead of `with`

### Body

My current re-usable workflow is something like this.

callable.yaml

```yaml
name: Called Workflow

on:
  workflow_call:
    inputs:
      env:
        type: string
        description: 'environment'
        default: 'dev'
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./
    steps:
      - name: echo environment
        run: |
          echo ${{ inputs.env }}
```

**caller.yaml**

```yaml
name: Build/Deploy

on:
    workflow_dispatch:
          
permissions:
    id-token: write
    contents: read
    packages: read
    
jobs:
  caller-workflow:
    uses: org/repo/.github/workflows/callable.yaml
    secrets: inherit
    with:
        env: dev
```

but I want to use UI inputs from my caller workflow instead of `with:`

can I use something like this and pass inputs through UI.

```yaml
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: 'qa'
        options: 
          - qa
          - dev
```

**Comment by Mr-Saikiran** [comment, marked as answer]
After some research I found it can help me this way.


```yaml
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: 'qa'
        options:
          - qa
          - dev

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  caller-workflow:
    uses: org/repo/.github/workflows/callable.yaml@main
    secrets: inherit
    with:
      env: ${{ github.event.inputs.environment }}
```
