### DISCUSSION TITLE
Is it possible to use a version file to set the versions for actions.

### DISCUSSION THREAD

**Discussion by RJaikanthEJ** [community/community#129176] [Actions]
### Select Topic Area

Question

### Body

My organisation currently uses github actions for CI/CD. We have a separate repository with tags for different actions.

The following is an example of a workflow used in a repository - 
```yml
      - name: action1
        uses: "org/actions-repo/actions/action1@1.0.0"
      - name: action2
        uses: "org/actions-repo/actions/action2@1.0.0"
      - name: action3
        uses: "org/actions-repo/actions/action3@1.0.0"
```

My question is - Is it possible to save these versions in a separate file?
```yml
# version.yml
actions_repo_version: 1.0.0
```

And somehow use it in the workflow file like below - 
```yml
      - name: action1
        uses: "org/actions-repo/actions/action1@$actions_repo_version"
      - name: action2
        uses: "org/actions-repo/actions/action2@$actions_repo_version"
      - name: action3
        uses: "org/actions-repo/actions/action3@$actions_repo_version"
```
