### DISCUSSION TITLE
Can't update repo metadata from workflow

### DISCUSSION THREAD

**Discussion by sinux-l5d** [community/community#129178] [Actions]
### Select Topic Area

Question

### Body

Hello,
I'm trying to update my repo description from a GitHub workflow. From my computer, it's as simple as `gh repo edit $reponame --description "My new shiny description"`.

But I keep getting stucked from a workflow with the error **"HTTP 403: Resource not accessible by integration"** :

```yml
name: "Show progress"

on:
  push:
    branches:
      - main

jobs: 
  progress-update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh repo edit --description "Some description that might change"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
```

From what I read online, all workflow have permissions to read metadata. However, the permission `metadata: write` [doesn't exists](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs). I also tried `gh repo edit $REPO ...`.

What am I missing? Is it feasible at all?
