### DISCUSSION TITLE
Dependabot security/vulnerability alerts do not assign reviewers as specified in the dependabot.yml

### DISCUSSION THREAD

**Discussion by samturrell** [community/community#129196] [Code Security]
### Select Topic Area

Bug

### Body

Given the following dependabot config:

```yaml
version: 2
updates:
    - package-ecosystem: npm
      target-branch: develop
      directory: /
      schedule:
          interval: weekly
          day: monday
          time: '09:00'
      open-pull-requests-limit: 20
      reviewers:
          - samturrell
```

I would expect dependabot security alert/vulnerability PRs to be have the same reviewers added as in the config file. This works correctly for normal dependency updates, but currently security/vulnerability alert PRs just sit unassigned and are often missed.

Is there something else i should be doing here?

![image](https://github.com/community/community/assets/5918348/d80b1555-4f84-4d6d-a835-236cbc7d4f42)
