### DISCUSSION TITLE
Applying status checks only when a specific repo path is involved

### DISCUSSION THREAD

**Discussion by marvin-garcia** [community/community#129235] [Pull Requests]
### Select Topic Area

Question

### Body

I have a repo with a front- and back-end projects in separate folders. I have applied a branch rule to main that:
- Requires a pull request before merging
- Requires status checks to pass before merging. I have selected two GitHub actions that test the backend code.
- Requires merge queue

The workflow that runs the backend tests (the one that contains the status checks) has the following triggers:
```
on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - main
    types: [assigned, opened, synchronize, reopened]
    paths:
    #  - 'cx-portal/cx-backend/**'
```
Here is the problem I am having:
- I want the tests to run only when changes involve the backend project, but if I add the tests to the status checks (the way the branch protection rule is right now), the tests are triggered for every single merge.
- If I uncomment the path filter on the test workflow and make it run ONLY on pull requests that involve the backend project, then other PRs that are not related to it are never merged because the required checks do not run and therefore don't satisfy the branch protection rule.
- If I remove the status checks, then PRs are automatically merged without waiting for the result of the test workflow.

I am sure I am missing some silly configuration either in the protection rule or the way the workflows are triggered, but I have looked all over the place without a good solution.
