### DISCUSSION TITLE
How to add multiple html pages in Github pages

### DISCUSSION THREAD

**Discussion by Naman-Bhrgv** [community/community#129546] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

Hi! I have a github repo containing two html pages- [index.html](https://github.com/Naman-Bhrgv/Portfolio_Final/blob/main/index.html) and try_2.html. index.html contains a tag referring to [try_2.html](https://github.com/Naman-Bhrgv/Portfolio_Final/blob/main/try_2.html) , however, the hyperlink is always broken.

Repo link- [https://github.com/Naman-Bhrgv/Portfolio_Final](https://github.com/Naman-Bhrgv/Portfolio_Final)

**Comment by Srinath10X** [comment]
# These are some minor css issues 
Z-index: Ensure the a tag or its parent div isn't hidden behind other elements.
Pointer Events: Ensure the CSS property pointer-events isn't set to none for the a tag or its parent elements.
```css
div {
    pointer-events: auto; /* Ensure pointer events are enabled */
}

a {
    z-index: 10; /* Ensure the link is on top */
}
```
Don't forgot to add your resume pdf to the repo or you will get an error saying not found the pdf (don't forget to mark as answer )
