### DISCUSSION TITLE
Dependabot grouped security PR not working as configured

### DISCUSSION THREAD

**Discussion by kaji-bikash** [community/community#129633] [Code Security]
### Select Topic Area

Bug

### Body

**Our use case:**
We have mono-repositories with mixed runtimes - _mainly go-lang & NPM ecosystem_.  

We have "dependency graph", "security alerts" & "grouping" all enabled for the repository for dependabot alerts. As dependabot alerts could be noisy, we wanted to further control "how &/or on what" notification should happen. For this, we have got roughly following configuration in the monorepository.

```yaml
version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.ORG_GITHUB_TOKEN}}

updates:
  - package-ecosystem: "gomod"
    directory: "comp/service/service-name/src/"
    registries:
      - github
    open-pull-requests-limit: 0
    labels:
      - security
      - component:service-name
    ignore:
      - dependency-name: "lodash"
    schedule:
      interval: "daily"
      timezone: "Europe/London"
    groups:
      golang-non-major:
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"
      golang-major:
        applies-to: security-updates
        update-types:
          - "major"
          
```
We have `open-pull-requests-limit: 0` because we **are only interested in security updates for now**. Dependabot is creating grouped PR with label "dependency" for other code available in monorepository(_outside directory comp/service/service-name/src/_)  but not as instructed in `dependabot.yaml`. 

We have enterprise cloud github version and we are following this blog post - https://github.blog/changelog/2024-03-28-dependabot-grouped-security-updates-generally-available/

When we looked under "security alerts", we see something strange inside some individual alert raised by Dependabot. Picture is worth more here.

![Capture-2024-06-20-171341-2-2](https://github.com/dependabot/dependabot-core/assets/722803/08c301b3-1694-49ae-9f32-cd748d372b00)

Not sure what's going on and what else to give to understand where exactly it is failing or stuck.

Any help is appreciated in solving this!! Major nuisance so far.
