### DISCUSSION TITLE
GH_TOKEN not work

### DISCUSSION THREAD

**Discussion by kerthcet** [community/community#129613] [Actions]
### Select Topic Area

Question

### Body

This is how I use the GH_TOKEN:

```
on:
  issue_comment:
    types:
      - created
      # Ignore update for now
      # - edited
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize

env:
  GH_TOKEN: ${{ secrets.AGENT_TOKEN }}

jobs:
  on-new-push:
    if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
  on-comments:
    if: github.event_name == 'issue_comment' && github.event.action == 'created'
  on-label-updates:
    if: github.event_name == 'pull_request' && (github.event.action == 'labeled' || github.event.action == 'unlabeled')
```

I set an org secret with the key of `AGENT_TOKEN`, however, only the job `on-comments` can work, other two jobs will report error like:
```
  shell: /usr/bin/bash -e {0}
  env:
    GH_TOKEN: 
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
  env:
    GH_TOKEN: ${{ github.token }}
```

It's so weird. Any advices or solutions? Thanks a lot.
