### DISCUSSION TITLE
Build with Next.js failes due to missing packages

### DISCUSSION THREAD

**Discussion by Raifa21** [community/community#129742] [Programming Help] [answered]
### Select Topic Area

Question

### Body

I'm trying to build to github pages, but when trying to build with Next.js, i get the following error:

> Run npx --no-install next build
npm error npx canceled due to missing packages and no YES option: ["next@14.2.4"]

npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-0[6](https://github.com/Raifa21/chordgen/actions/runs/9665553514/job/26662920855#step:8:7)-25T15_43_44_901Z-debug-0.log
Error: Process completed with exit code 1.

I'm unsure what I need to do. Any help would be appreciated.

**Comment by floris-xlx** [comment]
Could you perhaps post me the log file or upload it somewhere? attach it to your reply

**Comment by maticrivo** [comment]
I'm facing the same. have you found a solution?

**Comment by mislam** [comment, marked as answer]
Hi @Raifa21. It looks like your GitHub Actions workflow is failing because `npx --no-install next build` cannot find the `next` package in your environment.

### Possible Solutions:
#### 1. Ensure `next` is installed
The error suggests that `next@14.2.4` is missing. Try explicitly installing it by adding the following step to your GitHub Actions workflow before running `next build`:

```yaml
- name: Install dependencies
  run: npm install
```
This ensures all dependencies, including `next`, are installed before the build.

#### 2. Avoid `npx --no-install`
Since `npx --no-install` only works if the package is already installed, you can simply run:

```yaml
- name: Build Next.js project
  run: npx next build
```
This will automatically install `next` if it's missing.

#### 3. Check package.json
Make sure your `package.json` includes `next` under `dependencies` or `devDependencies`:

```json
"dependencies": {
  "next": "^14.2.4"
}
```
If `next` is missing, add it:

```sh
npm install next
```

#### 4. Use a Clean Install (`ci`)
For GitHub Actions, it's often better to use `npm ci` instead of `npm install` for a clean dependency install:

```yaml
- name: Install dependencies
  run: npm ci
```
This ensures a consistent install based on `package-lock.json`.

#### 5. Check Node.js Version
Ensure your workflow uses a compatible Node.js version:

```yaml
- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: 18
```
Next.js 14 works best with Node.js 18 or later.

### Summary:
Try adding these steps to your GitHub Actions workflow:

```yaml
- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: 18

- name: Install dependencies
  run: npm ci

- name: Build Next.js project
  run: npx next build
```
Let me know if you need further help! 🚀
