### DISCUSSION TITLE
Files downloaded by cURL gets deleted after the next step

### DISCUSSION THREAD

**Discussion by fillwithjoy1** [community/community#129788] [Actions] [answered]
### Select Topic Area

General

### Body

Self-explanatory: When trying to download a file using curl, the file gets deleted by the next step of my workflow file
See this [workflow](https://github.com/fillwithjoy1/pixel-6-kernel/actions/runs/9673633800/job/26687903954)
And this [one](https://github.com/fillwithjoy1/pixel-6-kernel/actions/runs/9673914094/job/26688670804), where combining the two steps fixes this weird issue.

Is this normal?

**Comment by fillwithjoy1** [comment]
Just another run to show that this issue exists https://github.com/fillwithjoy1/pixel-6-kernel/actions/runs/9679041930

**Comment by joshjohanning** [comment, marked as answer]
Each time you use a new `run` step, it starts in the `${{ github.workspace }}` directory - AKA, often the root of where your checkout action clones things.


```yml

      # Runs a set of commands using the runners shell
      - name: Sync kernel repo
        run: |
          mkdir android-kernel
          cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b android14-gs-pixel-6.1
          repo sync -c --no-tags
      - name: Update vendor ramdisk (through curl)
        if: false
        run: |
          cd ..
          ....
```

For example, it looks to me like with this `cd ..`, you're trying to go back to the original directory after in the previous step, where you had had `mkdir android-kernal && cd android-kernel`.

You can change the default working directory for run steps for [each individual run step](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory), or as a [default for the entire job](https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#setting-default-shell-and-working-directory).
