### DISCUSSION TITLE
Allow hiding of commit(s) on main Pull Request conversation tab

### DISCUSSION THREAD

**Discussion by cyrus-mc** [community/community#12985] [Pull Requests]
I have never really found the value in having the `commits` listed on the `conversation` tab when they are readily available on the `commits` tab. 

When you have a heavy commit and comment PR this just muddies up the display. I feel it would be helpful to allow disabling or removing the commits on the tab all together.

**Comment by tonglil** [comment]
It would be great if there could be a dis-aggregated tab for _just_ conversations.

ie convert the current `conversation` tab into `timeline` as is (keeps everything), and then create a `conversation` tab that **_only_** shows comments and reviews' comments (no labels, references from other issues, bases changing, force pushing, PR name changing, yada yada)

<img width="680" alt="image" src="https://user-images.githubusercontent.com/3250776/225775355-0d1b4d2a-cdfb-49c1-b170-cb0f7acc64bf.png">
To
<img width="807" alt="image" src="https://user-images.githubusercontent.com/3250776/225775913-ec61b0f7-65c1-4a59-997d-d0388528050c.png">

As it stands, when PRs get into the 50+ commits and more than a handful of comments and reviews, things become way to overwhelming to look through. Particularly when there is a comment you _want_ to refer to (ie test/coverage info, etc), but gets collapsed away.

**Reply by LeleDallas** [reply]
> It would be great if there could be a dis-aggregated tab for _just_ conversations.
> 
> ie convert the current `conversation` tab into `timeline` as is (keeps everything), and then create a `conversation` tab that **_only_** shows comments and reviews' comments (no labels, references from other issues, bases changing, force pushing, PR name changing, yada yada)
> 
> <img alt="image" width="680" src="https://user-images.githubusercontent.com/3250776/225775355-0d1b4d2a-cdfb-49c1-b170-cb0f7acc64bf.png">
> 
> To
> <img alt="image" width="807" src="https://user-images.githubusercontent.com/3250776/225775913-ec61b0f7-65c1-4a59-997d-d0388528050c.png">
> 
> As it stands, when PRs get into the 50+ commits and more than a handful of comments and reviews, things become way to overwhelming to look through. Particularly when there is a comment you _want_ to refer to (ie test/coverage info, etc), but gets collapsed away.

Great idea! This would be a huge quality-of-life improvement for long-running PRs! 🚀

**Reply by tonglil** [reply]
I've been able to get some CSS that can help hide non-conversation bits in the timeline.
You can use stylus or something to toggle it, though some JS to turn it on/off would be nicer.

```css
.js-timeline-item[data-gid^="ASEE_"],
.js-timeline-item[data-gid^="CRE_"],
.js-timeline-item[data-gid^="CTDE_"],
.js-timeline-item[data-gid^="C_"],
.js-timeline-item[data-gid^="DEE_"],
.js-timeline-item[data-gid^="DEME_"],
.js-timeline-item[data-gid^="HRFPE_"],
.js-timeline-item[data-gid^="LE_"],
.js-timeline-item[data-gid^="MIE_"],
.js-timeline-item[data-gid^="RDE_"],
.js-timeline-item[data-gid^="RFRE_"],
.js-timeline-item[data-gid^="RRE_"],
.js-timeline-item[data-gid^="RTE_"],
div[class="TimelineItem"]:not([data-view-component]) {display: none;}
```
