### DISCUSSION TITLE
Trigger an action conditionally with AND operator

### DISCUSSION THREAD

**Discussion by santoshkal** [community/community#129849] [Actions]
Hi,
I have more than one action that needs to be triggered when all conditions in `if` expressions meet. I looked for similar topics and tried them, but I was unable to succeed.
What have I tried:

```yaml
name: ci
on:
  push:
    branches:
      - main
    paths:
      - 'dir1'
    tags:
    - 'v*'
    if: |
      ${{ ("startsWith(github.ref, 'refs/tags/')) &&
      (github.ref ==  'refs/heads/main') &&
      contains(github.event.head_commit.modified, 'dir1/**') }}
      ...
```
I have another one with just update with `contains(github.event.head_commit.modified, 'dir2/**')`

I expect this to trigger a specific action that meets all the conditions.

But, with push to `main` with updates to `dir1` and tag it, both the actions are triggered and run.
I also tried removing the curlies `${{...}}` and the only one condition as following:

```yaml
name: ci
on:
  push:
    tags:
      - 'v*'
    if: "contains(github.event.head_commit.modified, 'dir1/**')"
...
```

Can someone please help me resolve this?

Thanks!

**Comment by joshjohanning** [comment]
This is the part of your YML that determines if your workflow will be triggered:

```yml
on:
  push:
    branches:
      - main
    paths:
      - 'dir1'
    tags:
    - 'v*'
 ```

You can put `if` conditions on jobs, example: https://github.com/joshjohanning-org/issueops-samples/blob/main/.github/workflows/new-repo-create.yml#L10-L14

```yml
on:
  issue_comment:
    types: [created]

jobs:
  new-repo-create:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' &&
      (startsWith(github.event.comment.body, '/create-repo') &&
      contains(github.event.issue.labels.*.name, 'new-repo'))
```

I would perhaps try putting the condition on the job itself.

**Reply by santoshkal** [reply]
Hi, @joshjohanning Thanks for the hint.
I tried adding the `if` condition in the `jobs`, but its still failing. 

And, I found [this blog](https://github.blog/changelog/2019-10-16-changes-in-github-actions-push-event-payload/) on deprication of the `modified` attribute.

Do you suggest any workarounds?

Thanks again!

**Reply by joshjohanning** [reply]
It's possible - if you have this in the second above, i'm not sure why you need the additional `if` condition:

```yml
  push:
    branches:
      - main
    paths:
      - 'dir1'
 ```

If you want to see what the entire context has that you can use for the `if` condition, you can print out the entire context and investigate: https://josh-ops.com/posts/github-context/

You could write your own if statement in bash in the workflow and create your own output variable, too.
