### DISCUSSION TITLE
Will dependabot rebase all PRs on schedule if I set rebase-strategy to disabled

### DISCUSSION THREAD

**Discussion by engineforce** [community/community#12994] [Code Security]
Hi dependabot team, 

`rebase-strategy: auto` is noise with npm dependencies, every time I merge 1 PR to main, it will cause tens of PRs to be rebased immediately causing many GitHub Actions runs.

I have configured `schedule` and `rebase-strategy: disable`, will dependabot run rebase automatically on schedule (e.g., 3am Melbourne time)?

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Australia/Melbourne"
    rebase-strategy: "disabled"
```
