### DISCUSSION TITLE
Automated updates for CodeQL GitHub Actions dependencies using Dependabot for an entire organization

### DISCUSSION THREAD

**Discussion by john-yacuta-submittable** [community/community#129912] [Actions]
### Select Topic Area

Question

### Body

Scenario: I have several repos in an organization that each contain a .github/workflows/codeql-analysis.yml with outdated codeql-actions workflows including `github/codeql-action/init@v2` and `github/codeql-action/autobuild@v2`. I need to upgrade these dependencies for each file that uses these codeql-actions workflows. 

Docs: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

Question: I am aware that the deprecation notice supports Dependabot to help with this upgrade from the docs here: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/ . However, the docs do not cover how to enable a dependabot.yml for an entire organization to automate the process to update only the codeql-actions workflows that I need updated. Does someone know how to get this enabled for an entire organization? I checked the organization settings but do not see an option to do so. See the example dependabot.yml below.

```yaml
# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "daily"
    allow:
    # Allow updates for CodeQL Action
    - dependency-name: "github/codeql-action/*"

```
