### DISCUSSION TITLE
Github actions does not support variables in uses keyword for resusable workflows

### DISCUSSION THREAD

**Discussion by sy185109** [community/community#129994] [Actions]
### Select Topic Area

Question

### Body

Team, Github actions workflow seems to be throwing up an error whenever we put a variable resolving in the uses keyword, it throws an error as invalid owner name in the workflow.

How can I manage to pass the owner name through variables in the uses keyword ?

**Comment by sy185109** [comment]
@queenofcorgis  Please help me with the above query.

**Reply by queenofcorgis** [reply]
Hi there,

Please note, contacting any member of GitHub Staff via unsolicited mentions or pings is strongly discouraged and may be considered a violation of our prohibition against harassment. Please review our Code of Conduct for more information.

Let's work together to keep GitHub Community a place where people feel safe to participate by being respectful of them and their time.

**Reply by sy185109** [reply]
I apologize for the action, I was in an urgent need of the answer. Thanks for letting me know, I would strictly abide by the process from now.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by ChrisPage-AT** [comment]
I am also running into this issue.  I have a private repo with a bunch of reusable workflows.  I'm trying to write unit tests for some of them, but I run into the issue that `uses:` cannot contain any variables.  Below is my code:

```
unit-tests:
    name: "Unit Test - ${{ matrix.test }}"
    runs-on: linux-small
    needs: 
      - set-env-vars
    strategy:
      fail-fast: false
      matrix:
        test: ${{fromJson(needs.set-env-vars.outputs.tests)}}
    env:
      path: ${{ matrix.test }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Unit Test - ${{ matrix.test }}
        id: unit-test
        uses: ./${{ matrix.test }}/test.yml
```

The previous job determines which reusable workflow folders have test.yml files and passes them on to be used in the matrix strategy.  Everything else about the job looks fine, but the `uses:` section always comes back as invalid.  

Is there any way to accomplish this?  Thanks!
