### DISCUSSION TITLE
Why is my workflow being skipped?

### DISCUSSION THREAD

**Discussion by DrAugus** [community/community#130136] [Actions] [answered]
### Select Topic Area

Question

### Body

![image](https://github.com/community/community/assets/34206897/9c9aef33-18c8-4b73-8059-d295557f4c88)

pr is [here](https://github.com/DrAugus/draugus.github.io/pull/549)

here is my `yml` file

```yaml
name: Deploy life

on:
  push:
    branches:
      - master
    paths:
      - "life/**"
      - ".github/workflows/deploy-life.yml"
      - "**/package.json"
      - "**/pnpm-lock.yaml"
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - "life/**"
      - ".github/workflows/deploy-life.yml"
      - "**/package.json"
      - "**/pnpm-lock.yaml"
```      

https://github.com/DrAugus/draugus.github.io/blob/c8d950119c2c9440e950d6d65df20bc2015fb9cb/.github/workflows/deploy-life.yml#L1-L20

**Comment by joshjohanning** [comment, marked as answer]
Ahh so your workflow is being triggered with the conditions you have.

But the _job_ didn't run because you have this later on:

```yml
jobs:
  deploy-game:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]
        deploy-dir: [game/.vitepress/dist]
        deploy-user: [augusmeow]
        deploy-repo: [game]

    runs-on: ${{ matrix.os }}

    # only me, deploy
    if: github.actor == 'DrAugus'. # <------ THIS LINE
```

In this case, the `renovate` bot was the actor, so the job didn't run.  You would probably have to do something like 
```yml
    if: github.actor == 'DrAugus' || github.actor == 'renovate[bot]'
```

I'm guessing on the `renovate[bot]` bit, but you can check the [context](https://josh-ops.com/posts/github-context/) for the exact actor.
