### DISCUSSION TITLE
Improve the job context by adding `job.id`, `job.name`, `job.run_name`, `job.logs_html_url`

### DISCUSSION THREAD

**Discussion by piotrekkr** [community/community#130225] [Actions]
### Select Topic Area

Product Feedback

### Body

Would be super useful if GitHub action `job` context exposed fields like:

- `job.id` - id of job
- `job.name` - Job name defined in workflow file
- `job.run_name` - Runtime job name (may be dynamic)
- `job.logs_html_url` (or some other name) - Url pointing to current job run logs something like `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ job.id }}`

My use case is that I want to notify someone and attach job run logs url inside notification. Currently only way to do it that I know of is like this:

```yaml
      - name: Get report details url
        id: job
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          job_id=$(
            gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs \
              --jq '.jobs[] | select(.runner_name=="${{ runner.name }}" and .name=="My Job Name") | .id'
          )
          echo "JOB_ID: $job_id"
          echo "html_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/$job_id" >> "$GITHUB_OUTPUT"

```

or use action like 
```yaml

      - name: Get report details url
        uses: Tiryoh/gha-jobid-action@08c36ee4cd7fe2e5e1facbaef6799c38e41532c4 # v0.1.2
        id: job
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # remember to update this parameter if job name changes
          job_name: My Job Name
```

And then use it when notifying someone

```yaml
# ...
      - name: Add PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: <my-report>
          recreate: true
          number: ${{ github.event.issue.number }}
          message: |
            ## REPORT
            [View detailed report](${{ steps.job.outputs.html_url }})
            @${{ github.triggering_actor }}
```

As you probably noticed if job name changes I need to remember to also update steps using job name. If there was log url provided then I would not need to do anything. If there was job name provided I could use `${{ job.name }}` in my steps and do not change anything when job name changes.

All this would using GH Actions easier than it is now. Thank you :pray:
