### DISCUSSION TITLE
Pre-release not triggered from non main branch

### DISCUSSION THREAD

**Discussion by eman-shaaban-akad** [community/community#130719] [Apps, API and Webhooks]
### Select Topic Area

Question

### Body

I have a workflow is triggered from push to a branch, which create a release.
the pre-release work flow is not triggered.
Question: can pre-release workflow be triggered from changes to branch.

```
name: Build and Deploy to test 

on:
  push:
    branches:
      - release-version

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: Get current version
        id: version
        run: echo "::set-output name=current::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ steps.version.outputs.current }}
          release_name: Release v${{ steps.version.outputs.current }}
          body: |
            TBC - Update 
          draft: false
          prerelease: true
```

```
on:
    release:
      types: [prereleased]
  
name: Deploy to Dev
  
jobs:
    prerelease:
      name: Deploy to Dev
      runs-on: ubuntu-latest
  
      steps:          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }} 
         asset_path: file.zip
         asset_name: file.zip
         asset_content_type: application/zip           
```
