### DISCUSSION TITLE
Github Actions not reporting to Status Check branch protections

### DISCUSSION THREAD

**Discussion by ew3361zh** [community/community#130817] [Actions]
### Select Topic Area

Question

### Body

I've looked through similar issues but can't find a solution that resolves this issue.
We recently enacted github status check protections for our main branch.
We have one combined GH action that runs two different jobs:

```
name: Format, Lint, Test, Coverage, and Type Checking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
    ...

  lint_test_type_check:
    name: Lint, Test, Coverage, and Type Checking
    needs: format_code
    runs-on: ubuntu-latest
```

When setting up the new branch protections for main for these jobs, we selected the job ID for the first job (`format_code`). It autopopulated when I started typing it in. For the second job, I started typing in the name of the job and that autopopulated `Lint, Test, Coverage, and Type Checking`.

Our GH actions still run and pass as expected, but they're not reporting that successful status to the branch protections.

Successful jobs:
![Screenshot 2024-07-02 at 5 24 25 PM](https://github.com/community/community/assets/70217952/b8b1573c-a115-49ba-9fed-d0c76ef41696)
Branch protections in limbo:
![Screenshot 2024-07-02 at 5 24 12 PM](https://github.com/community/community/assets/70217952/d29e8154-a161-46c2-ad33-862ea6598192)

This is stuck the same on all our open PRs.

Any ideas on how to resolve getting GH completed actions to send the result to the GH branch protection?
- Does it have something to do with using a job-ID for one of them and a job-name for the other?
- Does it have to do with not including the overall action name `Format, Lint, Test, Coverage, and Type Checking` before the name of the specific job?
- Does it have to do with using punctuation in the job name (i.e. commas)?
- If it's a name/job id/punctuation issue, how did Github autopopulating the suggested job not resolve this disconnect?
- Is it an issue of concurrency because we have a bunch of open PRs running the same action/jobs?

Any help would be appreciated.
