### DISCUSSION TITLE
Seeking Help: Critical Errors in GitHub CI/CD Actions for Testing Code

### DISCUSSION THREAD

**Discussion by seremetwang** [community/community#131207] [Programming Help] [answered]
### Body

I'm currently setting up a CI/CD pipeline using GitHub Actions for my project, but I've encountered several critical errors that I can't seem to resolve. I'm reaching out for your expertise and guidance to help me troubleshoot these issues. Here are the details:

Incorrect Workflow Syntax

Description:
I'm receiving syntax errors in my workflow YAML file, preventing the workflow from running.

`The workflow is not valid. .github/workflows/main.yml (Line: 5, Col: 9): unexpected key 'run'`

What I've Tried:

Validating the YAML syntax using online validators.
Ensuring proper indentation and structure.

Question:
Could someone review my YAML file and point out any syntax issues?

```
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

```

### Guidelines

- [ ] I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.

**Comment by definecampus** [comment, marked as answer]
Your YAML syntax looks mostly correct, but let's ensure there are no hidden issues. Here's a slightly adjusted version for clarity:
```
name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
```
