### DISCUSSION TITLE
How to bypass credentials for services to allow pull requests to still run

### DISCUSSION THREAD

**Discussion by zspitzer** [community/community#131321] [Actions]
### Select Topic Area

Question

### Body

We recently hit some limits on docker pulls for our CI, I reached out to Docker and they sponsored out project.

This works great, except for pull requests which run without secrets, the then fail

```
    services:
      ldap:
        #  image: kwart/ldap-server
           image: rroemhild/test-openldap
           ports:
             - 10389:10389
             - 10636:10636
           credentials: 
             username: ${{ secrets.DOCKERHUB_PUBLIC_USERNAME }}
             password: ${{ secrets.DOCKERHUB_PUBLIC_TOKEN }}

```

https://github.com/lucee/Lucee/blob/6.1/.github/workflows/main.yml#L39

but i get the following error and the run fails due to the empty secrets, I've tried wrapping `${{ secrets.DOCKERHUB_PUBLIC_USERNAME }}` in single or double quotes, but nothing seems to work?

```
Error: The template is not valid. .github/workflows/main.yml (Line: 39, Col: 24): Unexpected value '',.github/workflows/main.yml (Line: 40, Col: 24): Unexpected value '',.github/workflows/main.yml (Line: 64, Col: 21): Unexpected value '',.github/workflows/main.yml (Line: 65, Col: 21): Unexpected value '',.github/workflows/main.yml (Line: 77, Col: 21): Unexpected value '',.github/workflows/main.yml (Line: 78, Col: 21): Unexpected value ''
```

**Comment by zspitzer** [comment]
figured out an ugly workaround, using a trick from https://github.com/actions/runner/issues/822

```
    services:
      ldap_with_creds:
        image: ${{ (github.secret_source != 'none') && 'rroemhild/test-openldap' || ' ' }}
        ports:
          - 10389:10389
          - 10636:10636
        credentials: 
          username: ${{ secrets.DOCKERHUB_PUBLIC_USERNAME || ' ' }} # empty string to avoid invalid template
          password: ${{ secrets.DOCKERHUB_PUBLIC_TOKEN || ' ' }}
      ldap_no_creds:
        image: ${{ (github.secret_source == 'none') && 'rroemhild/test-openldap' || ' ' }}
        ports:
          - 10389:10389
          - 10636:10636
```
