### DISCUSSION TITLE
Workflow Action to Automate Adding Card to Project Failing

### DISCUSSION THREAD

**Discussion by jehtee** [community/community#131347] [Projects and Issues]
### Select Topic Area

Question

### Feature Area

Projects

### Body

I'm trying to automate adding a new card to a global Project for each new repo that gets added to my account by submitting a particular issue template.

I've tried several approaches, all of which fail... each of which for new and exciting reasons.

It seems like this should be a basic case, so I'm blaming user error.  That said, this user needs help.

How can I automatically add a new card to an existing project for each repo newly created by submitting an particular issue template?

Here is the latest action log and failed YML and Python code

ACTION LOG ERROR
==============
```
...
An error occurred: 'Repository' object has no attribute 'node_id'
```

YML
==============
```
name: Minimal Opportunity Init

on:
  issues:
    types: [opened, edited]  # Trigger the workflow when an issue is opened or edited

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install PyGithub requests

      - name: Run Python Script
        run: python opportunity-init.py
        env:
          SEC_OPPORTUNITY_INIT: ${{ secrets.SEC_OPPORTUNITY_INIT }}
          GITHUB_PROJECT_ID: ${{ secrets.SEC_GITHUB_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          REPO_FULL_NAME: ${{ github.repository }}  # Pass the full name of the repository
```
          

PYTHON
==============
```
import os
import re
import requests
import json
from datetime import datetime
from github import Github
from create_mailing_list import create_mailing_list

def sanitize_repo_name(name):
    """Sanitize the issue title to create a valid GitHub repository name."""
    sanitized_name = re.sub(r"[^a-zA-Z0-9-]", "-", name)
    sanitized_name = re.sub(r"-+", "-", sanitized_name)
    sanitized_name = sanitized_name.strip("-")
    return sanitized_name.lower()

def create_folders(repo, folders):
    """Create folders in the repository with a .gitignore file."""
    for folder in folders:
        try:
            repo.create_file(f"{folder}/.gitignore", "init folder", "# Ignore everything in this directory\n*\n# Except this file\n!.gitignore")
            print(f"Folder '{folder}' created.")
        except Exception as e:
            print(f"Failed to create folder {folder}: {str(e)}")

def extract_github_ids(issue_body):
    """Extract GitHub usernames from the issue body based on 'Github:' label."""
    return re.findall(r'Github:\s*([\w-]+)', issue_body)

def invite_users_to_repo(repo, usernames):
    """Invite GitHub users to the repository and handle errors."""
    failed_invitations = []
    for username in usernames:
        try:
            repo.add_to_collaborators(username, permission='push')
            print(f"Invitation sent to {username}.")
        except Exception as e:
            print(f"Failed to send invitation to {username}: {str(e)}")
            failed_invitations.append(username)
    
    if failed_invitations:
        error_content = "Failed to send invitations to the following GitHub IDs:\n" + "\n".join(failed_invitations)
        try:
            repo.create_file("init-errors.txt", "Create init error file", error_content)
            print("init-errors.txt created with failed invitation details.")
        except Exception as e:
            print(f"Failed to create init-errors.txt: {str(e)}")

def create_readme(repo, issue_body):
    """Create a README.md file with content from the issue body."""
    date_today = datetime.now().strftime("%Y-%m-%d")
    readme_content = f"""# Project Overview

## Date
{date_today}

## Client/Customer
Describe the client or customer for whom the project is intended.

## Opportunity Description
Provide a detailed description of the business opportunity.

## Members
{issue_body}

## Links
- Repository: {repo.html_url}
- Group Chat: [Link to group chat channel]

"""
    try:
        repo.create_file("README.md", "Add README.md", readme_content)
        print("README.md created successfully.")
    except Exception as e:
        print(f"Failed to create README.md: {str(e)}")

def get_repo_node_id(repo, token):
    """Fetch the repository's node ID using GitHub REST API."""
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }
    url = f'https://api.github.com/repos/{repo.full_name}'
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        repo_data = response.json()
        node_id = repo_data.get('node_id')
        if node_id:
            return node_id
        else:
            print("Node ID not found in the response.")
            return None
    else:
        print(f"Failed to fetch repository node ID: {response.status_code} {response.text}")
        return None

def add_to_project(repo, project_id, token):
    """Add a card to the 'Opportunity Tracker' project using Projects (Beta)."""
    repo_node_id = get_repo_node_id(repo, token)
    if not repo_node_id:
        print("Failed to obtain repository node ID.")
        return

    headers = {
        'Authorization': f'Bearer {token}',
        'Content-Type': 'application/json',
        'GraphQL-Features': 'projects_next_graphql'
    }
    url = 'https://api.github.com/graphql'
    mutation_add_item = """
    mutation AddItemToProject($projectId: ID!, $contentId: ID!) {
      addProjectNextItem(input: {projectId: $projectId, contentId: $contentId}) {
        projectNextItem {
          id
        }
      }
    }
    """
    variables_add_item = {
        'projectId': project_id,
        'contentId': f"RepositoryNode:{repo_node_id}"  # Use the fetched node ID of the repository
    }
    response_add_item = requests.post(url, headers=headers, json={'query': mutation_add_item, 'variables': variables_add_item})
    if response_add_item.status_code == 200:
        print("Item successfully added to the project.")
    else:
        print("Failed to add item to the project:", response_add_item.text)

def main():
    token = os.getenv('SEC_OPPORTUNITY_INIT')
    issue_title = os.getenv('ISSUE_TITLE')
    issue_body = os.getenv('ISSUE_BODY')
    project_id = os.getenv('GITHUB_PROJECT_ID')  # Ensure this is set to your GitHub Project (Beta) ID
    repo_full_name = os.getenv('REPO_FULL_NAME')  # Fetch the full name of the repository

    if not token or not issue_title or not project_id:
        print("Required environment variables are missing.")
        return
    
    github = Github(token)
    repo = github.get_repo(repo_full_name)  # Use the full name to get the repo object

    try:
        print(f"Repository created: {repo.html_url}")
        folders = ["01. From Client", "02. Strategy", "03. Biz Dev", "04. Marketing", "05. Engineering", "06. Design"]
        create_folders(repo, folders)
        create_readme(repo, issue_body)
        github_ids = extract_github_ids(issue_body)
        invite_users_to_repo(repo, github_ids)
        create_mailing_list(repo)

        add_to_project(repo, project_id, token)
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == '__main__':
    main()
```

ISSUE TEMPLATE
==============
```
---
name: Initialize Opportunity - MD
about: Complete this template to initialize a new opportunity as defined by init-opportunity.py
title: ''
labels: opportunity
assignees: ''
---

### Client Information
Client Name: Acme
Project Name: Test-
Description: testing

### Key Dates (YYYY-mm-dd)
Start Date: 2024-07-01
End Date:

### Team
Copy/Paste this format for each member.  The labels are necessary to process the you provide.

* Name: john smith
  * Email: john@smith.com
  * Skype: 
  * Github: my-github-acct
  * Role: view|edit

### Additional Notes
```

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
