### DISCUSSION TITLE
How to only make one specific branch of a repository accessible to the public

### DISCUSSION THREAD

**Discussion by PBerit** [community/community#131435] [Repositories] [answered]
Hi all,

i want to ask how to only make one specific branch of a repository accessible to the public? We have a repository with many different branches that are all publicly available currently. We only want to publish one of the branches while the rest of the repository remains private. I tried to do that in the Rules setting, but I could not find a way to make the whole repository private. In the rules setting I could only adjust the rights for developers (which is not relevant for me). Does anyone have any idea

**Comment by davevad93** [comment]
Hi @PBerit ,

In GitHub, a repository is either `public` or `private`, you can't make only one branch public and the others private. To change a repo visibility go to `Settings` => `General` , scroll down till the `Danger Zone` section and click on `Change Visibility`.

![0](https://github.com/community/community/assets/94308234/fd51744d-fda6-46a7-8ba7-84335173ab1a)

**Comment by MostlyKIGuess** [comment]
Hey Idts there's any way to do this directly but you can set it up such that you can create a private repo and then use this 
- .github/workflows/deploy.yml:
```yaml
name: Deploy to Public Repo

on:
  push:
    branches:
      - your-branch-name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: your-branch-name

      - name: Push to public repository
        run: |
          git remote add public-repo https://github.com/yourusername/public-repo.git
          git push public-repo your-branch-name:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
- This would help you to automate the process , you will use this in your private one.
