### DISCUSSION TITLE
pytest xdist abruptly exits with exit code 0 on self-hosted k8s runner

### DISCUSSION THREAD

**Discussion by ghost** [community/community#131566] [Actions]
### Select Topic Area

Question

### Body

We're seeing this strange issue where pytest xdist will abruptly exit with code 0 on Github Actions (self-hosted on k8s), which causes the CI run to be marked as success even though not all the tests ran. 

Our workflow definition looks like this:
```yaml
    steps:
      - uses: actions/checkout@v2
      - name: Run tests (with xdist)
        run: pytest ...
```

I've tried enabling a variety of debug / logging flags but I nothing ever gets printed before the exit. The lack of any output is making this difficult to debug. Has anyone seen this before? 

We've seen it exit at multiple points in the test run and the behavior is always the same -- nothing gets printed, and it returns with exit code 0.
