### DISCUSSION TITLE
Lost all commits after running Github Actions workflow

### DISCUSSION THREAD

**Discussion by Arqamz** [community/community#131524] [Actions]
### All commits lost after github actions workflow

Question

### Body

I recently ran a GitHub Actions workflow (Generate Snake Game from GitHub Contribution Grid) in my repository to automate the generation of SVG images based on GitHub contribution grids. However, after the workflow completed, all previous commits except one were deleted/lost from my repository history. 

Steps Taken:

I reviewed the Git log and Git reflog, both of which show only one commit remaining.
Checked the GitHub repository interface to verify the current state, confirming that only the latest commit related to the workflow (image generation) is visible.
Attempted to revert the latest commit but this did not restore the missing commits.
Expectation:
I expected the GitHub Actions workflow to generate and update SVG files (github-contribution-grid-snake.svg and github-contribution-grid-snake-dark.svg) in a folder without affecting the existing commit history of my repository.

Request for Assistance:
I'm seeking guidance on how to recover the lost commits and restore my repository to its previous state before running the GitHub Actions workflow. Any insights, suggestions, or steps to recover the missing data would be greatly appreciated.

Additional Information:

Repository: [My repository](https://github.com/Arqamz/Arqamz)
Workflow YAML: 

```
  name: Generate Snake Game from GitHub Contribution Grid
  
  on:
    schedule:
      - cron: "5 0 * * *"  # Runs at 12:05 AM UTC every day
    workflow_dispatch:
  
    push:
      branches:
      - main 
  
  jobs:
    generate:
      permissions: 
        contents: write
      runs-on: ubuntu-latest
      timeout-minutes: 5
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
          
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thank you in advance for your assistance and support in resolving this critical issue.
