### DISCUSSION TITLE
Error: P1001: Can't reach database server at `localhost:5432`

### DISCUSSION THREAD

**Discussion by BenjaminTham-SIT** [community/community#131660] [Actions]
### Select Topic Area

Question

### Body

I cant do `npx prisma migrate deploy` in my github actions workflow because apparently the postgres db cannot be found

Run npx prisma migrate deploy
  npx prisma migrate deploy
  shell: sh -e {0}
  env:
    DATABASE_URL: ***localhost:543[2](https://github.com/ekiost/ITP_G20/actions/runs/9871764048/job/27260384738#step:7:2)/postgres/mydb?schema=public
  
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres/mydb", schema "public" at "localhost:54[3](https://github.com/ekiost/ITP_G20/actions/runs/9871764048/job/27260384738#step:7:3)2"
Error: P1001: Can't reach database server at `localhost:5[4](https://github.com/ekiost/ITP_G20/actions/runs/9871764048/job/27260384738#step:7:4)32`
Please make sure your database server is running at `localhost:[5](https://github.com/ekiost/ITP_G20/actions/runs/9871764048/job/27260384738#step:7:5)432`.
Error: Process completed with exit code 1.

```
name: PostgreSQL service example
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:22

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm i

      - name: List installed packages
        run: npm list

      - name: Postgres migrate
        run: npx prisma migrate deploy
        env:
          # The hostname used to communicate with the PostgreSQL service container
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres/mydb?schema=public"


      - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: npx tsx src/data/local/systemStatusRepo.ts
        # Environment variables used by the `client.js` script to create a new PostgreSQL table.
        env:
          # The hostname used to communicate with the PostgreSQL service container
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres/mydb?schema=public"
```
