### DISCUSSION TITLE
Can I Consolidate Checks in the PR Conversation View?

### DISCUSSION THREAD

**Discussion by minauteur** [community/community#131751] [Actions]
## Question
Is there any way to control the display of jobs triggered on pull requests in the PR Conversation view?

## Context
While I understand from the (somewhat related) discussion linked below that there has been talk of configuration of required workflows (versus required jobs), I am ultimately OK with identifying individual jobs for the time being. 

With a large number of jobs, however, the view quickly becomes cluttered in PR Conversations. I'm wondering if it may be possible to add optional configuration for consolidating PR checks in the view (similar to how it occurs in the run summary, for example).

It may even be worthwhile to allow customization, for example--if a workflow is configured to trigger `on: pull_request`...
```yaml
on:
  pull_request:       # view might should exist as a property of `pull_request` since it concerns PRs exclusively

view:
  options:            # potentially for additional configuration
    hide_passing: true
  groups:
    tests:
      - unit_tests    # this might even be pattern-matched by ID
      - int_tests
    other:
      - other_job_1
      - other_job_2
jobs:
  unit_tests:
    # etc...
  int_tests:
    # etc...
  other_job_1:
    # etc...
  other_job_2:
    # etc...
```
Which would result in two (perhaps expandable) items in the PR discussion view instead of four.

Of course this suggestion assumes there's no existing solution for cleaning up the "Checks" window in the PR "Conversation" view. If such a solution already exists I would be happy to learn more 😄

## Related
- https://github.com/orgs/community/discussions/12395
