### DISCUSSION TITLE
Get a workflow's `on` property

### DISCUSSION THREAD

**Discussion by GreeningSiren** [community/community#131985] [Apps, API and Webhooks] [answered]
Is it possible to get a specific workflow's `on` property? I need to see if the workflow has the 
`workflow_dispatch` to do my triggers.

**Comment by Swastik0710** [comment, marked as answer]
Yes, it is possible to check if a specific workflow has the `workflow_dispatch` event configured in its `on` property. This can be done by examining the workflow's YAML file in your repository. Here's how you can do it:

### Steps to Check the `on` Property in a GitHub Actions Workflow

1. **Navigate to Your Repository:**
   Go to the GitHub repository where your workflow is defined.

2. **Locate the Workflow File:**
   Workflows are typically stored in the `.github/workflows` directory at the root of your repository. Navigate to this directory.

3. **Open the Workflow File:**
   Open the YAML file for the workflow you want to inspect. For example, if your workflow file is named `ci.yml`, you would look for `.github/workflows/ci.yml`.

4. **Check the `on` Property:**
   Look for the `on` property in the workflow file to see if `workflow_dispatch` is included. The `on` property defines the events that trigger the workflow.

### Example Workflow File

Here is an example of what the `on` property might look like if it includes `workflow_dispatch`:

```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm test
```

In this example, the workflow is triggered by three events:

- A push to the `main` branch
- A pull request targeting the `main` branch
- A manual trigger using `workflow_dispatch`

### Checking the `on` Property Programmatically

If you need to check the `on` property programmatically (e.g., as part of a script), you can use a command-line tool like `yq` to parse the YAML file. Here's an example using `yq`:

1. **Install `yq`:**

   ```sh
   pip install yq
   ```

2. **Check for `workflow_dispatch` in the Workflow File:**

   ```sh
   yq eval '.on | has("workflow_dispatch")' .github/workflows/ci.yml
   ```

   This command will return `true` if `workflow_dispatch` is present in the `on` property, and `false` otherwise.

By following these steps, you can determine if a workflow includes `workflow_dispatch` in its `on` property, allowing you to confirm if manual triggers are supported for that workflow.
