### DISCUSSION TITLE
Is it possible for a GitHub Action to deploy to multiple websites?

### DISCUSSION THREAD

**Discussion by Rod-at-DOH** [community/community#131989] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm still learning about GitHub Actions. I've written a few, both GitHub Actions as well as self-hosted runners. But in all cases, I've made them deploy to one location. We'd like to be able to deploy to two websites, instead of only one. Is that possible? And if so, how is that done? I've tried searching for similar questions but haven't found any.

**Comment by Yewzir** [comment, marked as answer]
@Rod-at-DOH 

Yes, it is possible for GitHub Actions to deploy to multiple websites. Below is a basic example of a workflow configuration file that demonstrates deploying to two different websites.

```yaml
name: Deploy to X and Y

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to X
      run: |
        echo "Deploying to X"
        rsync -avz ./X/ user@X.com:/var/www/html/

    - name: Deploy to Y
      run: |
        echo "Deploying to Y"
        rsync -avz ./Y/ user@Y.com:/var/www/html/
```

Adjust the commands in each step to suit your specific deployment process for each website.

🎉 

Kind regards
Yewzir
