### DISCUSSION TITLE
What are the best practice development steps for existing active github actions workflows

### DISCUSSION THREAD

**Discussion by chz013** [community/community#132162] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi All

We're new to github actions. We need to add new and modify existing and active github workflows of an existing repo. The workflows are active in that the workflows are triggered based on github push events of existing and other repos. 

What are the best practice steps to experiment and debug current workflows and
1) not worrying that push events of other monitored repositories would trigger workflows where experiment and debug current workflows are redesigned and/or modified 
OR
2) not confuse or interfere with current active workflows while we redesign and/or modify existing or add new workflows

Any help is appreciated. Thank you

**Comment by danialtavakoli** [comment]
When experimenting with and modifying GitHub Actions workflows in an existing repository, especially when those workflows are triggered by push events from other repositories, it's crucial to isolate your experimental changes to avoid interference with active workflows. Here are some best practice steps to achieve this:

### 1. Use a Separate Branch for Development
Create a separate branch specifically for developing and testing your workflow changes. This will keep your experimental workflows isolated from the main branch and prevent them from affecting the current active workflows.

```bash
git checkout -b experiment-workflows
```

### 2. Disable Workflows on the Experiment Branch
You can disable workflows for the experiment branch by using the `if` condition in your workflow YAML files to skip execution on this branch.

```yaml
jobs:
  example_job:
    if: github.ref != 'refs/heads/experiment-workflows'
    ...
```

### 3. Test Locally with `act`
Use a tool like `act` to run GitHub Actions workflows locally. This can help you debug and test workflows without pushing changes to GitHub.

```bash
brew install act
act
```

### 4. Use Workflow Dispatch Event for Testing
Instead of relying on push events, use the `workflow_dispatch` event to manually trigger your workflows for testing.

```yaml
on:
  workflow_dispatch:
```

You can then manually trigger the workflow from the GitHub Actions tab in your repository.

### 5. Add Conditional Checks
Incorporate conditional checks within your workflows to ensure they only run under certain conditions. For example, you can use environment variables, branch names, or custom parameters.

```yaml
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check for experimental branch
        if: github.ref == 'refs/heads/experiment-workflows'
        run: echo "This is an experiment workflow."
```

### 6. Use Pull Requests for Merging
Once you have thoroughly tested your changes on the experiment branch, use pull requests to merge the changes into the main branch. This allows for code reviews and additional testing before the changes become active.

### 7. Utilize Secrets for Sensitive Data
Ensure any sensitive data, such as API keys or tokens, are stored in GitHub Secrets and not hardcoded in your workflow files. This will secure your sensitive information and prevent leaks during testing.

### 8. Monitor Workflow Runs
After making changes, monitor the workflow runs closely to ensure everything behaves as expected. Use the GitHub Actions interface to view logs, check for errors, and troubleshoot as needed.

### 9. Document Changes
Document any changes you make to the workflows, including the purpose of the changes, the expected behavior, and any known issues. This helps maintain clarity and assists anyone else who may work with these workflows in the future.

### Example Workflow with `workflow_dispatch` and Conditional Checks

Here's an example of a GitHub Actions workflow file incorporating some of these best practices:

```yaml
name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/experiment-workflows'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "This is the main branch workflow."
```

In this example, the workflow is set to run on `push` events to the `main` branch and can also be triggered manually via `workflow_dispatch`. It includes a conditional check to skip execution if the branch is `experiment-workflows`.

By following these steps, you can safely experiment and debug GitHub Actions workflows without disrupting the active workflows triggered by push events from other repositories.

**Comment by chz013** [comment]
Hi @danialtavakoli  - thx for responding. we hope your answer gets folded into Github's official Actions documentation.

If an active workflow file (eg pr.yaml) only has push event listed in its content and we need to modify this file in branch `experiment-workflows` to manually run the workflow, can you confirm that the element `workflow_dispatch:` has to be added in branch main of the active workflow file (eg pr.yaml) first before we create branch `experiment-workflows` ? 

Our active workflow file (eg pr.yaml) has run steps using ssh commands to certain runners. We read some of "act" tool and it doesnt seem to work for those steps from its user guide. How would it simulate those runners with ssh ?

We read that this element has to exist in both branches `main` and `experiment-workflows` in order for manual run to work.

**Reply by danialtavakoli** [reply, marked as answer]
To address your concerns and confirm the workflow setup for manual triggering, here are the details:

### Confirming `workflow_dispatch` Requirement

Yes, you need to add the `workflow_dispatch` event to the active workflow file (e.g., `pr.yaml`) in the `main` branch first. Once it's added, you can create the `experiment-workflows` branch and make modifications there. The `workflow_dispatch` event allows you to manually trigger the workflow from both branches.

Here's how to add `workflow_dispatch` to the workflow file:

```yaml
name: PR Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
```

### Steps to Implement

1. **Add `workflow_dispatch` to `main` Branch**: First, add the `workflow_dispatch` event to your workflow file in the `main` branch and push the changes.

    ```bash
    git checkout main
    # Edit pr.yaml to include workflow_dispatch
    git add .github/workflows/pr.yaml
    git commit -m "Add workflow_dispatch event"
    git push origin main
    ```

2. **Create Experiment Branch**: Create and switch to the `experiment-workflows` branch to make your experimental changes.

    ```bash
    git checkout -b experiment-workflows
    ```

3. **Modify Workflow in Experiment Branch**: Make the necessary modifications to the workflow file in this branch.

    ```bash
    # Edit .github/workflows/pr.yaml for your experiments
    git add .github/workflows/pr.yaml
    git commit -m "Modify workflow for experiments"
    git push origin experiment-workflows
    ```

4. **Manually Trigger Workflows**: You can now manually trigger the workflows from the GitHub Actions tab in both the `main` and `experiment-workflows` branches.

### Simulating SSH Steps with `act`

`act` is a great tool for local testing of GitHub Actions workflows, but it does have limitations, particularly with steps involving SSH commands to certain runners. If your workflows rely heavily on SSH connections to specific runners, you might face challenges using `act` as it doesn't fully simulate these environments.

#### Workaround for SSH Steps

Here are some potential workarounds:

1. **Conditional Execution**: Add conditional logic to skip SSH-related steps when running locally with `act`. You can use environment variables to detect if the workflow is running in `act`.

    ```yaml
    steps:
      - name: SSH Command
        if: ${{ !env.ACT }}
        run: ssh user@host 'command'
    ```

2. **Mock SSH Commands**: Create mock commands or scripts that simulate the behavior of your SSH commands. This won't fully replicate the environment but can help you test the rest of the workflow logic.

    ```yaml
    steps:
      - name: Mock SSH Command
        if: env.ACT
        run: echo "Simulating SSH command"
    ```

3. **Use GitHub Runners for Testing**: If local testing with `act` is not feasible, you might need to rely on GitHub-hosted runners for testing. You can create a dedicated testing environment or repository where you can safely run and debug your workflows without affecting the production environment.


At all, To enable manual triggering, you need to add `workflow_dispatch` to your workflow file in the `main` branch first. You can then create the `experiment-workflows` branch and modify the workflow as needed. While `act` is useful for local testing, it might not fully support SSH commands. You can use conditional execution, mock commands, or a dedicated testing environment to work around these limitations.
