### DISCUSSION TITLE
Kubernetes Operator Cannot Access Files in any Directory in GitHub Actions

### DISCUSSION THREAD

**Discussion by Parthiba-Hazra** [community/community#132142] [Actions]
### Select Topic Area

Question

### Description:
I am working on a Kubernetes operator that needs to access files in the /var/lib/kubelet/checkpoints directory. The operator works as expected locally but fails to access the files when running in a GitHub Actions environment.

### Issue Details:

- The files are present in the /var/lib/kubelet/checkpoints directory.
- The operator logs indicate that it is watching the directory but does not find any files.
- The directory and file permissions appear to be correct.

**Here are the key parts of my setup:**

**Deployment YAML:**
```
apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: manager
        image: controller:latest
        volumeMounts:
        - name: kubelet-checkpoints
          mountPath: /var/lib/kubelet/checkpoints
      volumes:
      - name: kubelet-checkpoints
        hostPath:
          path: /var/lib/kubelet/checkpoints
          type: Directory

```

**GitHub Actions Workflow:**
```
name: Build and Deploy

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install dependencies
        run: |
          # Install kind
          curl -sLo kind "$(curl -sL https://api.github.com/repos/kubernetes-sigs/kind/releases/latest | jq -r '[.assets[] | select(.name == "kind-linux-amd64")] | first | .browser_download_url')"
          chmod +x kind
          sudo mv kind /bin/
          
          # Install kubectl
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /bin/

      - name: Prepare Checkpoints Directory in Kind Node
        run: |
          sudo mkdir -p /var/lib/kubelet/checkpoints
          sudo chmod 777 /var/lib/kubelet/checkpoints

      - name: Generate Checkpoint Tar Files
        run: ./test/generate_checkpoint_tar.sh

      - name: Create Kubernetes cluster
        run: |
          kind delete cluster
          kind create cluster
          kind export kubeconfig

      - name: Load Docker image into kind cluster
        run: |
          make docker-build IMG=checkpoint-restore-operator:ci
          kind load docker-image checkpoint-restore-operator:ci

      - name: Deploy to Kubernetes
        run: |
          make install
          make deploy IMG=checkpoint-restore-operator:ci

      - name: Wait for deployments to be ready
        run: ./test/wait_for_deployment.sh checkpoint-restore-operator-controller-manager

      - name: Check resources
        run: kubectl get all -n checkpoint-restore-operator-system

      - name: Wait for Checkpoint Tar Files to Reduce
        run: |
          kubectl apply -f ./test/test_checkpointrestoreoperator.yaml
          ./test/wait_for_checkpoint_reduction.sh

```

**Logs:**
```
2024-07-12T15:08:34Z  INFO    No checkpoint files found       {"controller": "checkpointrestoreoperator", "controllerGroup": "criu.org", "controllerKind": "CheckpointRestoreOperator", "CheckpointRestoreOperator": {"name":"checkpointrestoreoperator-sample","namespace":"default"}, "namespace": "default", "name": "checkpointrestoreoperator-sample", "reconcileID": "17f763d9-be7d-4389-8c76-7f7283755ff9"}
```

**Steps Tried:**

- Verified file permissions and presence in the directory.
- Mounted the directory correctly in the deployment spec.
- Ensured the directory structure in the GitHub Actions environment matches the expected structure.

### Request for Help:

- What could be causing the operator to not see the files in the directory?
- Are there any additional steps or configurations needed to ensure the operator can access the files in a GitHub Actions environment?
