### DISCUSSION TITLE
ECONNREFUSED 127.0.0.1:8080 trying to connect to wiremock service

### DISCUSSION THREAD

**Discussion by andy-tazxap** [community/community#132374] [Actions]
### Action Services 

Question

I am trying to run a wiremock container as a service in a github action. The container appears to start correctly and seems healthy however when I try to call the container I am repeatedly getting `connect ECONNREFUSED 127.0.0.1:8080`. 

My `action.yml` is as follows; 
```
name: Jest Automatic Testing

on:
  pull_request:
      branches:
        - main

jobs:
  run-jest-tests:
    name: Jest Tests
    runs-on: ubuntu-22.04
    services:
      wiremock:
        image: wiremock/wiremock:2.32.0
        ports:
          - 8080:8080
    container:
      image: node:18.16.0
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: install dependencies
        run: npm install testcontainers --save-dev && npm install npm --prefix server install server && npm --prefix admin install admin && npm --prefix client install client && npm install concurrently

      - name: Run Jest Tests
        run: npm run test
```

and then I try to connect on this url "http://localhost:8080". 

Has anyone experienced this before?
