### DISCUSSION TITLE
Workflow triggered in wrong branch

### DISCUSSION THREAD

**Discussion by esdrasdl** [community/community#132312] [Actions] [answered]
### Select Topic Area

Question

### Body

I want to run a workflow in every pull request, except if the pull request branch is a release branch (base branch could be anyone). I also use the path trigger. Looking the docs the right setup should be the code below:
```
on:
  pull_request:
    branches-ignore:
      - 'release/*'
    paths:
      - '.github/workflows/build.yaml'  ##this file
      - 'path/to/anywhere/**'
```

But it not works as I expected. Every time I create a pull request whose feature name start with release, my workflow is triggered.
Not sure what I missed.
