### DISCUSSION TITLE
Require a staus check from job in a workflow triggered by workflow_run?

### DISCUSSION THREAD

**Discussion by gilzow** [community/community#132564] [Actions]
### Select Topic Area

Question

### Body

I have a workflow that runs a matrix. The worflow is triggered by the completion of a separate workflow (ie `workflow_run`). i now what to require the matrix job as a required status check in pull requests. While I can find the job name listed in the status checks search (ie Settings --> Branches --> <production-branch-name> --> Require status checks to pass before merging --> Search for status checks...), and include it, when a pull request is created, even if the job passes, the status in the PR panel shows `Expected — Waiting for status to be reported`. 

Here is roughly how the workflows are set up

WorkflowA
```
name: get info
on:
  pull_request:
    branches: main
<snip>
```

WorkflowB
```
name: Runs tests
on:
  workflow_run:
    workflows: [get info]
    types:
      - completed
 jobs:
   the_job:
     name: Select me
``` 

when I go search for "Select me" it appears in the search, I can select and add it to the list of checks. But then it never reports its status in a pull request. 

I feel like I'm missing something obvious here but for the life of me can't figure out what's missing

**Comment by danialtavakoli** [comment]
In GitHub Actions, the issue you're encountering is often related to how the status checks are reported when dealing with `workflow_run`. Since the `workflow_run` is a different workflow and not directly tied to the pull request, the status checks might not be correctly reported back to the PR. 

Here are a few steps to ensure that your status checks are correctly reported:

### 1. Use the `workflow_run` correctly
Ensure that your `workflow_run` configuration is correct. Here’s a brief verification:

**WorkflowA (get info):**
```yaml
name: get info
on:
  pull_request:
    branches:
      - main
jobs:
  get_info_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your steps here
```

**WorkflowB (Runs tests):**
```yaml
name: Runs tests
on:
  workflow_run:
    workflows: ["get info"]
    types:
      - completed
jobs:
  the_job:
    name: Select me
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your steps here
```

### 2. Ensure WorkflowB completes successfully
Make sure that WorkflowB runs and completes successfully after WorkflowA completes. You can verify this in the Actions tab of your repository.

### 3. Configure required status checks
When you configure required status checks, make sure that you are specifying the correct job name as it appears in the Actions logs. For example, if your job name is `Select me`, ensure that this matches exactly.

**Repository Settings:**
- Go to **Settings** > **Branches**.
- Under **Branch protection rules**, find the rule for `main` (or create one if it doesn’t exist).
- Under **Require status checks to pass before merging**, ensure that you add `Select me` to the list of required checks.

### 4. Check GitHub API
GitHub may sometimes have delays in reporting the status checks. Ensure there are no delays or API issues by verifying in the Actions tab and in the repository's Checks tab.

### 5. Use GitHub's REST API for troubleshooting
If you're still encountering issues, you can use GitHub's REST API to get the details of the status checks for a specific pull request. This will help you verify if the status check for `Select me` is being reported correctly.

**Example API call to list status checks for a PR:**
```sh
curl -H "Authorization: token YOUR_GITHUB_TOKEN" \
     https://api.github.com/repos/OWNER/REPO/commits/COMMIT_SHA/status
```
Replace `YOUR_GITHUB_TOKEN`, `OWNER`, `REPO`, and `COMMIT_SHA` with your specific details.

### 6. Debugging Tips
- Ensure WorkflowB is triggered correctly by WorkflowA completion.
- Ensure job names are unique and correctly referenced in the branch protection rules.
- Check for any delays or pending statuses in the GitHub Actions UI.

If you have done all of the above and the issue persists, you may want to reach out to GitHub support for further assistance, as there could be specific issues with how GitHub Actions are handling `workflow_run` in your repository.
