### DISCUSSION TITLE
job.name expression not evaluated when job skipped

### DISCUSSION THREAD

**Discussion by lpeabody** [community/community#13261] [Actions]
See original issue that was closed https://github.com/actions/runner/issues/1215.

When a job is skipped, if it's `name` contains an expression then it is not evaluated. It makes sense, but from a UX perspective it is not ideal.

To reproduce:

1. Have a workflow such as below:

```
name: Example Workflow
on:
  workflow_dispatch:
jobs:
  Services:
    if: false == true
    name: ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo Hello World
```

2. Run the workflow manually. The result is as below.

![Example unevaluated job label in UI.](https://user-images.githubusercontent.com/20721903/126466789-69f5f50d-25bb-410f-9b2b-559a794cf236.png)

Additional example:

```
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      do-backup:
        description: Whether or not to make a backup before deploying.
        required: true
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'
      environment:
        description: The environment to deploy to.
        required: true
        default: wwnewdev
        type: choice
        options:
          - wwnewdev
          - wwnewstg
          - wwnewprod

env:
  DEPLOYMENT_ENVIRONMENT: ${{ github.event.inputs.environment || 'wwnewdev' }}

jobs:
  backup:
    name: Backup ${{ github.event.inputs.environment }}
    uses: ./.github/workflows/backup.yml
    # Always backup production.
    if: ${{ github.event.inputs.do-backup == 'true' || github.event.inputs.environment == 'wwnewprod' }}
    with:
      environment: ${{ github.event.inputs.environment }}
  ...
```

After a push to `main` you get this UI output:

![image](https://user-images.githubusercontent.com/419534/159516855-39639329-29e8-4330-b1cf-6c6fa8485699.png)

When manually run via workflow_dispatch, everything looks dandy in the UI.

Ideally, instead of `Backup ${{ github.event.inputs.environment }}` in the left-hand sidebar, it would say `Backup wwnewdev` somehow (I understand you can't use the `env` context in the job name, otherwise I would use that). Also, it would be ideal if in the job flow chart area it would be labeled `Backup wwnewdev / Backup`.

I understand that if a job is determined to be skipped then further evaluation does not make sense from a processing perspective so this is likely a "feature", but from a UX perspective it is annoying and can cause confusion.

Given the current state, is there any way to work around this to have some kind of graceful fallback? Is there any way to set a job's name dynamically if it is skipped? What have others done to work around this dilemma?
