### DISCUSSION TITLE
How do I set up ARM runners?

### DISCUSSION THREAD

**Discussion by Martmists-GH** [community/community#132674] [Actions]
### Select Topic Area

Question

### Body

I tried using the following:

```yaml
jobs:
  build-cmake:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-arm-latest, windows-latest, macos-latest, macos-arm-latest]

    runs-on: ${{ matrix.os }}
```

but the `-arm` variants are waiting indefinitely.
