### DISCUSSION TITLE
Fine-grained token forbidden when pulling private repo but classic PAT works fine

### DISCUSSION THREAD

**Discussion by piotrekkr** [community/community#132837] [Actions]
### Select Topic Area

Question

### Body

Hello. I'm testing new fine grained PAT and cannot seem to make it work. I can't checkout additional repo code from my org. 

Here is my workflow where I'm testing it

```yaml
name: 06 - Debug
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  debug_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo 'OK' >> test.txt
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          # actual branch of PR
          ref: ${{ github.event.pull_request.head.sha }}
          path: main
      - name: Checkout demo-repo-b
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/demo-repo-b
          ref: main
          token: ${{ secrets.MY_PAT }}
          path: demo-repo-b
      - run: ls -la
```
`MY_PAT` is a fine grained token with access to all repositories (read for contents and metadata)

![image](https://github.com/user-attachments/assets/728f0266-9f19-406d-b1fa-23f28747c640)

I'm also added as Admin to `demo-repo-b`

![image](https://github.com/user-attachments/assets/75479af6-b796-4220-b2bc-83c90b7456bb)

And I get this error:

```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
  remote: Write access to repository not granted.
  Error: fatal: unable to access 'https://github.com/<ORG>/demo-repo-b/': The requested URL returned error: 403
  The process '/usr/bin/git' failed with exit code 128
  Waiting 18 seconds before trying again
...
```

I also tried to change contents permission in PAT to read & write but it fails the same.

I also create classic PAT with full repo permissions, just to test if this will work. It worked without any issues. 

Do I need to set some additional permissions in fine-grained PAT to be able to checkout code from repos? Thanks
