### DISCUSSION TITLE
unable to run a simple cronjob

### DISCUSSION THREAD

**Discussion by Zunaira-Malik** [community/community#133265] [Actions]
### Select Topic Area

Question

### Body

i am running a simple workflow with cronjob. cronjob isn't seem to be working.
```
name: every min

on:
  schedule:
    - cron: '* * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        shell: bash
        run: echo hi
```

it is not working either i set it to run every min, each 5 mins, each 15 mins, or mention specific time.
anyone can solve it?
