### DISCUSSION TITLE
Reusable workflow behavior does not match documentation when nesting remote workflows

### DISCUSSION THREAD

**Discussion by alliepiper** [community/community#133424] [Actions]
### Select Topic Area

Bug

### Body

# Overview

I have a collection of reusable workflows and actions that are needed in multiple repositories. I want to store these in a single "infra" repo to be reused across my org.

There is a single entry point, a reusable workflow, which needs to call other workflows/actions from the infra repository using the same ref as the entry point workflow.

[Github documentation](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow) states:

> If you use the [`uses: ./path/to/local/workflow.yaml` syntax] the called workflow is from the same commit as the caller workflow.

However, this does not work in practice. The called workflow in the example below does not use the caller's repo/commit -- rather, it uses the root workflow's metadata. This behavior is surprising, as using the local path syntax for `uses:` would intuitively access files from the caller's checkout, as the documentation says.

There doesn't seem to be any way to workaround this. AFAICT, this bug completely prevents users from being able to produce shared, reusable workflows that require other versioned workflows from the same repository in their implementation.

## Related

- #18601: A similar issue about calling an action from a workflow, when both are in a remote repo. Has a workaround.
- #18602: A more general issue about getting a `github` context for the current workflow vs the root workflow. No workaround.

# Testbed

I have a testing implementation here:

- User repo: https://github.com/alliepiper/test_gha
- Shared repo: https://github.com/alliepiper/test_gha_infra

Those might get deleted at some point, so I'll include an annotated implementation below:

# Implementation

The workflow/action definitions are:

-----

User workflow: `alliepiper/test_gha/.github/workflows/level-0.yml`

Invokes the entry point workflow from the remote repo:

```
name: Project Workflow
on:
  workflow_dispatch:
jobs:
  call-reusable-workflow:
    uses: alliepiper/test_gha_infra/.github/workflows/level-1.yml@v1
```

This works.

-----

Shared workflow entry point: `alliepiper/test_gha_infra/.github/workflows/level-1.yml`

Invokes a second reusable workflow from the current `test_gha_infra` repository of shared GHA infra using a local path in `uses`.

```
name: First remote reusable workflow
on:
  workflow_call:
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/level-2.yml
```

This fails (error below). The remaining workflow/action are not reached.

-----

Second shared workflow: `alliepiper/test_gha_infra/.github/workflows/level-2.yml`

Invokes an action from the current `test_gha_infra` repository of shared GHA infra using a local path in `uses`.

```
name: Nested Remote Reusable Workflow
on:
  workflow_call:
jobs:
  invoke-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run the action
        uses: ./.github/actions/level-3
```

-----

Shared action: alliepiper/test_gha_infra/.github/actions/level-3/action.yml

Just prints hello world.

```
name: "Nested remote reusable action"
runs:
  using: "composite"
  steps:
    - name: Output
      shell: bash
      run: |
        echo "Hello World!"
```

# Error message

Link: https://github.com/alliepiper/test_gha/actions/runs/10079373441

Error message:

```
Invalid workflow file: .github/workflows/level-0.yml#L12
error parsing called workflow
".github/workflows/level-0.yml"
-> "alliepiper/test_gha_infra/.github/workflows/level-1.yml@v1" (source tag with sha:e7a9ca6ce6d0d85d16d24e9715abe852dc92bb7e)
--> "./.github/workflows/level-2.yml"
: workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.
```
