### DISCUSSION TITLE
Job condition with test on previous job outputs, not working as expected.

### DISCUSSION THREAD

**Discussion by keisari-ch** [community/community#133419] [Actions]
### Select Topic Area

Bug

### Body

Let's assume that it may not be a bug but a total misunderstanding on my side. I'm having a hard time troubleshooting this.

This is part of a repository with terraform deployments, the example below will be the very simple version, that doesnt work for me.

I dont manage to understand why the condition is never correctly evaluated and the job is never triggered :
```
    if: ${{ needs.plan-test.outputs.has_changes == 'yes' }} 
```

workflow.yml
```yaml
name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  plan-test:
    name: tfp sub
    uses: ./.github/workflows/terraform-plan.yml
   
  nochange-test:
    name: chg sub
    if: ${{ needs.plan-test.outputs.has_changes == 'yes' }} 
    needs: plan-test
    uses: ./.github/workflows/terraform-nochange.yml
    with:
      has_changes: ${{ needs.plan-test.outputs.has_changes }}
```

terraform-plan.yml

On this file i make sure the resulting output will be 'yes'

```yaml
name: Terraform Workflow Plan Template

on:
  workflow_call:
    outputs:
      has_changes: 
        description: Terraform Change Marker
        value: ${{ jobs.plan.outputs.has_changes }}

jobs:
  plan:
    name: tf plan
    runs-on: arc-runner-itplat
    container:
      image: acrsnsfitplat.azurecr.io/actions/itplat-tools:latest
      options: --user root
      credentials:
        username: ${{ secrets.acr_app_id }}
        password: ${{ secrets.acr_app_secret }}

    outputs:
      has_changes: ${{ steps.plan_output.outputs.has_changes }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Plan
      id: plan
      continue-on-error: true
      run: |
        set +e
        exitcode=2
        if [[ "$exitcode" -eq 0 || "$exitcode" -eq 2 ]]; then
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit $exitcode
        fi

    - name: Establish following actions
      id: plan_output
      run: |
        tf_exitcode=${{ steps.plan.outputs.exitcode }}
        if [[ "$tf_exitcode" -eq 0 ]]; then
          echo "No changes"
          echo "has_changes='no'" >> $GITHUB_OUTPUT
          exit 0
        elif [[ "$tf_exitcode" -eq 2 ]]; then
          echo "Changes detected in PLAN"
          echo "has_changes='yes'" >> $GITHUB_OUTPUT
          exit 0
        else
          exit $tf_exitcode
        fi
```

terraform-nochange.yml

```yaml
name: Terraform Workflow NoChange Notification

on:
  workflow_call:
    inputs:
      has_changes:
        type: string
        required: true

jobs:
  plan:
    name: no change
    steps:
    - name: No Action
      run: echo ${{ inputs.has_changes }} && exit 0
```
