### DISCUSSION TITLE
Unhandled exception. System.IO.IOException: No space left on device

### DISCUSSION THREAD

**Discussion by srinidhim-agi** [community/community#133486] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi, 

I was running git action CI workflow to generated Java based docker image. The build is failing due to below error log. Kindly help me out on the same. 

System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240725-052230-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240725-052230-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)

**Comment by danialtavakoli** [comment, marked as answer]
The error message you are seeing, "No space left on device," indicates that the disk space on the runner machine used by GitHub Actions is full. This prevents the process from writing to the log file and leads to the build failure.

Here are some steps to troubleshoot and resolve the issue:

### 1. Check Disk Usage
You can add a step to your GitHub Actions workflow to check the disk usage before starting the build process. This will help you understand how much space is being used and where.

Add the following step to your workflow file:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check disk usage
        run: df -h
```

### 2. Clean Up Disk Space
You can try to free up some disk space by cleaning up unused files and dependencies. For example:

- **Remove Unused Docker Images:** Docker images can take up a lot of space. You can remove unused Docker images to free up space.

  ```yaml
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Remove unused Docker images
          run: docker system prune -af
  ```

- **Clean Up Temporary Files:** Remove any temporary files that might be taking up space.

  ```yaml
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Clean up temporary files
          run: sudo rm -rf /tmp/*
  ```

### 3. Increase Runner Disk Space
If the issue persists, consider using a runner with more disk space. GitHub offers different types of runners, and you may need to choose one with more resources.

### 4. Cache Dependencies
Caching dependencies can help reduce the amount of space needed during the build process.

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
```

### 5. Split Build Steps
If your build process is extensive and consumes a lot of disk space, consider splitting it into multiple jobs. This can help distribute the disk usage more evenly.

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: mvn clean install

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-java-app .
```

### 6. Use Self-Hosted Runners
If you frequently encounter disk space issues, consider using self-hosted runners with more storage. Self-hosted runners allow you to control the hardware and storage capacity.

You can register a self-hosted runner and configure it to run your GitHub Actions workflow.
