### DISCUSSION TITLE
Handling Concurrency Issues and Commenting on PRs in GitHub Actions

### DISCUSSION THREAD

**Discussion by Shreya21Mishra** [community/community#133521] [Actions]
### Select Topic Area

Question

### Body

I have a GitHub Action that performs certain tasks on push and returns a response which is then commented on the PR. We have set up concurrency control as follows:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
```

However, we occasionally encounter an issue where a workflow does not get triggered and the following message is displayed:
```
Canceling since a higher priority waiting request for 'api-call-refs/heads/main' exists
```

I would like to know how to send a comment back to the PR when this situation occurs.
