### DISCUSSION TITLE
TestContainers MSSQL - Timeout Starting

### DISCUSSION THREAD

**Discussion by cfelstead** [community/community#133510] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi All,

This is my first time trying to use TestContainer. I am using it to make sure the Tests run on a fresh database. This works with Docker Desktop locally and runs quite fast. I am now testing to see how it will work in a CI pipe in the cloud. However, after 5 minutes of the following is clearly fails. I can extend the timeout but don't believe this will help as the tests run so fast locally.

> [testcontainers.org 00:05:45.93] Execute "/opt/mssql-tools/bin/sqlcmd -Q SELECT 1;" at Docker container

Googling everywhere isn't helping. Here is my YAML file.

```yaml
name: Run Tests 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./ExempPlaygroundApp.sln

      - name: Build
        run: dotnet build ./ExempPlaygroundApp.sln --no-restore

      - name: Test
        run: dotnet test ./ExempPlaygroundApp.sln --no-build
```

Any help is appreciated.
