### DISCUSSION TITLE
Helm CDR problem

### DISCUSSION THREAD

**Discussion by ErickBortoloti** [community/community#133570] [Codespaces]
### Select Topic Area

Question

### Body

Guys, I'm creating the packaging of an application in helm. In this question I have the mysql operator, but when I activate it (it will be optional for the person, it says that the CDR is not installed. The solution I found was to install it manually, and put it in my chart and it worked, but I am not able to do this to the "do not install" option).
Like, if I set it to not install, it doesn't install beautifully, but if I set it to yes, it gives this problem: 
install.go:259: [debug] WARNING: This chart or one of its subcharts contains CRDs. Rendering may fail or contain inaccuracies.
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "mysql-operator" namespace: "" from "": no matches for kind "ClusterKopfPeering" in version "zalando.org/v1"
ensure CRDs are installed first
helm.go:84: [debug] resource mapping not found for name: "mysql-operator" namespace: "" from "": no matches for kind "ClusterKopfPeering" in version "zalando.org/v1"
ensure CRDs are installed first

I would like to install the CRDs first and then the mysql-operator, if the customer wishes

**Comment by InboraStudio** [comment]
To solve the issue of installing the MySQL operator using Helm, ensuring that the Custom Resource Definitions (CRDs) are installed first, you can follow these steps:

Install CRDs Separately:
Install the CRDs manually before installing the MySQL operator. This can be done by running a separate Helm command or using kubectl.

Use Helm Hooks:
Helm hooks can be used to ensure that CRDs are installed before the rest of the resources.

Split Helm Charts:
Split your Helm chart into two separate charts: one for the CRDs and another for the MySQL operator.

Here’s an example of how to do this using Helm hooks:

1. Create a Custom Resource Definition (CRD) Install Chart
First, create a Helm chart dedicated to installing the CRDs.

crd-install/templates/crds.yaml:

```yaml
apiVersion: zalando.org/v1
kind: ClusterKopfPeering
metadata:
  name: clusterkopfpeering
  annotations:
    "helm.sh/hook": crd-install
---
# Other CRDs if necessary
````
2. Create a Helm Chart for the MySQL Operator
Create a separate Helm chart for the MySQL operator.

mysql-operator/templates/mysql-operator.yaml:

```yaml
apiVersion: zalando.org/v1
kind: mysql-operator
metadata:
  name: mysql-operator
spec:
  # Specification for your MySQL operator
```
3. Helm Chart Dependencies
You can also use dependencies to ensure the CRDs are installed first. In your MySQL operator chart, add a dependency on the CRD chart.

mysql-operator/Chart.yaml:
```yaml
apiVersion: v2
name: mysql-operator
version: 0.1.0
dependencies:
  - name: crd-install
    version: 0.1.0
    repository: file://../crd-install
```
4. Install the CRDs and MySQL Operator
First, install the CRDs using the CRD install chart:
```md
helm install crd-install ./crd-install
```
Then, install the MySQL operator chart:
```md
helm install mysql-operator ./mysql-operator
```
5. Combining with Hooks
Alternatively, you can use Helm hooks within a single chart. Add a pre-install hook to your CRD resource definitions.

mysql-operator/templates/crds.yaml:

```yaml
apiVersion: zalando.org/v1
kind: ClusterKopfPeering
metadata:
  name: clusterkopfpeering
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
---
# Other CRDs if necessary
```
This will ensure that the CRDs are installed before any other resources in the chart.

Thank You
