### DISCUSSION TITLE
Action stuck at npm ci

### DISCUSSION THREAD

**Discussion by yelouafi** [community/community#133518] [Actions]
### Select Topic Area

Action run issue

### Body

Action below suddenly becomes stuck at `npm run ci` It was working fine before. Not sure if this is related to some limits on billing side but I checked the usage section in billing page and can see we're running into any limit (image below)

```yml
name: Save engine version

on:
    push:
        paths:
            - "apps/sandbox/**"
            - "packages/**"

jobs:
    save_version:
        # run when either (branch is main) or (dev and commit msg contains [@save-engine])
        if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '@@save-engine')
        runs-on: macos-latest
        permissions:
            contents: read
            deployments: write

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm ci
              working-directory: apps/sandbox

            - name: Build
              run: npm run build
              working-directory: apps/sandbox

            - name: Deploy to cloudflare pages
              id: deploy
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CF_API_KEY }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  projectName: ${{ secrets.CF_PROJECT }}
                  branch: ${{ github.ref_name }}
                  directory: apps/sandbox/dist
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}

            - name: Save version to CDN
              run: npm run save:version
              working-directory: apps/sandbox
              env:
                  CF_PAGES_URL: ${{ steps.deploy.outputs.url }}
                  CF_PAGES_DEPLOYMENT: ${{ steps.deploy.outputs.id }}
                  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
                  CF_PROJECT: ${{ secrets.CF_PROJECT }}
                  CF_API_KEY: ${{ secrets.CF_API_KEY }}
                  CF_R2WORKER_KEY: ${{ secrets.CF_R2WORKER_KEY }}
                  PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
                  FIREBASE_ADMIN_PROJECT_ID: ${{ secrets.FIREBASE_ADMIN_PROJECT_ID }}
                  FIREBASE_ADMIN_PRIVATE_KEY: ${{ secrets.FIREBASE_ADMIN_PRIVATE_KEY }}
                  FIREBASE_ADMIN_CLIENT_EMAIL: ${{ secrets.FIREBASE_ADMIN_CLIENT_EMAIL }}
                  GITHUB_TAG: ${{ github.ref_name }}
                  GITHUB_SHA: ${{ github.sha }}
                  GITHUB_COMMIT_MSG: ${{ github.event.head_commit.message }}
                  GITHUB_TIMESTAMP: ${{ github.event.head_commit.timestamp }}

```

![image](https://github.com/user-attachments/assets/4588cdc3-8570-405f-bfa3-5fcdf3dce95b)
