### DISCUSSION TITLE
How to pass output from a GitHub Action step that is in python?

### DISCUSSION THREAD

**Discussion by masatcisco** [community/community#133693] [Actions]
### Select Topic Area

Question

### Body

My apologies if this is documented, but I couldn't find anything after a search.

I have an action that does the following:

```
jobs:
  steps:
     - name: Step1
       run: |
          {bash code}
     - name: Step2
        shell: python
       run: |
          {python}

```
I would like to set an output like the `echo "var=value" >> $GITHUB_OUTPUT `in bash.

I could go try to figure this out, but before I spend some effort, I thought that I'll check first.

Much TIA.
