### DISCUSSION TITLE
Container Action that I published builds again when I call it?

### DISCUSSION THREAD

**Discussion by mhemken-vts** [community/community#133667] [Packages]
# The setup

I followed the instructions for building a [Docker Container Action][1]. I successfully built an image and published it to `ghcr.io/<my-user>/<my-repo>:release`.

# The problem

> Why does this action re-build a container image when it can simply pull it and run it?

When I call this action, it doesn't run what I expect. It first builds the Dockerfile and then it runs the container. This is unexpected because I have already built the container and published it to ghcr.io. Why is this happening?

Here's my workflow

```
name: The Proof
run-name: the-proof
"on":
  push:
    branches:
      - main
jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - name: Run the hello world
        uses: <my-user>/<my-repo>@release
```

Here's the `action.yml`

```
name: 'my-action-name'
author: 'me'
description: 'A GitHub Action to print hello world'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/<my-user>/<my-repo>:release'
branding:
  icon: 'check-square'
  color: 'white'
```

# Additional info

<img width="379" alt="image" src="https://github.com/user-attachments/assets/02e9cddf-de9d-4cc8-a9d4-65ef2e3e2cc6">

I'm running a go program that simply prints hello world. It runs correctly and I see the output in the action logs. But it doesn't make sense that it needs to run docker build! I've alredy built the image!

[1]: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action "container action"
