### DISCUSSION TITLE
Background-Image is not loading through GitHub Pages

### DISCUSSION THREAD

**Discussion by DaNnY-0324** [community/community#133692] [Programming Help]
### Select Topic Area

Question

### Body

I am deploying my portfolio through GitHub Pages, but the background images does not load on GitHub pages. When I start it on localhost, the background shows with no problem. 

I have provided the css code for it below:

body {
  background-image: "../images/backgroundv3.png" no-repeat center center fixed; 
  background-size: cover;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-attachment: fixed;
}

**Comment by davevad93** [comment]
Hi @DaNnY-0324 ,

I checked your repo and noticed that the `images` folder is located in the root which is two levels above the `main.css` which is located in `/assets/css` , so try the following:

```css
body {
    background-image: url("../../images/backgroundv3.png");
    background-repeat: no-repeat;
    background-position: center center;
    background-attachment: fixed;
    background-size: cover;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
}
```
