### DISCUSSION TITLE
Github Container Action pulling from ghcr.io is unauthorized.

### DISCUSSION THREAD

**Discussion by mhemken-vts** [community/community#133674] [Packages]
### Select Topic Area

Question

### Body

I've defined a workflow that uses a container action that I built. The image is in ghcr.io.

The problem is that the workflow tries to pull the image before I can run a login step. I've only defined the "Run hello world" step. GitHub injects a "Setup" and "Pull" step before any of my steps run.

How do I authenticate with ghcr.io?

```
name: The Proof
run-name: the-proof
"on":
  push:
    branches:
      - main
jobs:

  proof:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:

      - name: Run the hello world
        uses: mhemken-vts/hello-go-action@release
```

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by fruetalo182** [comment]
Hi @mhemken-vts, try this:

```
name: The Proof
run-name: the-proof

on:
  push:
    branches:
      - main

jobs:
  proof:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Ensure this permission is set to access ghcr.io
    steps:
      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run the hello world
        uses: mhemken-vts/hello-go-action@release
```
