### DISCUSSION TITLE
Workflow Dispatch choice options should allow display text distinct from value

### DISCUSSION THREAD

**Discussion by philomory** [community/community#13372] [Actions]
When using a `workflow_dispatch` workflow, with an `input` of type `choice`, the browser UI for invoking the workflow constructs a drop-down menu containing the specified `options`. It'd be nice if we could (optionally) allow specifying the _display_ text of each option separately from the _value_ of that option, in much the same way that an HTML `<select>` element can look like this:

```html
<select>
  <option value='simple'>A simple choice</option>
  <option value='complex'>A more complex choice</option>
  <option value='unusual'>A choice only for unusual circumstances</option>
</select>
```
A potential syntax for this in the workflow yaml would be like this:
```yaml
on:
  workflow_dispatch:
    inputs:
      foo:
        description: An example choice
        type: choice
        required: true
        options:
          - value: simple
            text: A simple choice
          - value: complex
            text: A more complex choice
          - value: unusual
            text: A choice only for unusual circumstances
```
the `on.workflow_dispatch.inputs.*.options` element would take an `Array[String|Map]`, with a string value of `foo` treated as equivalent to `{value: 'foo', text: 'foo'}` for compatibility.

The advantage of this setup is that it would allow workflow developers the opportunity to provide more meaningful option descriptions, while not requiring them to have their workflow code check e.g. `if: github.events.inputs.foo == 'A choice only for unusual circumstances'` (as is presently required if you want descriptive text in your drop-down menu). This would be particularly helpful because it would avoid the chance of tweaks to the descriptive text rendering the workflow inoperable.
