### DISCUSSION TITLE
How to merge multiple stacked PRs into merge queue?

### DISCUSSION THREAD

**Discussion by yang** [community/community#133871] [Pull Requests]
### Select Topic Area

Question

### Body

Let's say you have a PR `A` to be merged on top of `main`, and a PR `B` to be merged on top of `A` (depends on `A`).

How can I merge both into the merge queue?

If I merge `A` into `main` first, then I have to wait for `A` to be fully merged (may take hours), before I can merge `B` on top of `main`.

I can merge `B` into `A` first, but that pollutes the `A` PR with all the code from both `A` and `B`. (Instead of a stack of 2 PRs, imagine a stack of 10 PRs, all crammed into the first.)

Is there a way I can have `A` and `B` both added to the merge queue, without messing up the PRs?

**Comment by subhanjandas** [comment]
# Managing Stacked PRs into a Merge Queue

## Introduction

When working with multiple pull requests (PRs) that are dependent on each other, it's crucial to manage them in a way that preserves their integrity and doesn't pollute the commit history. Below is a step-by-step guide to effectively manage and merge stacked PRs.

## Step-by-Step Process

### 1. Create Feature Branches

Each PR should be based on its own feature branch, derived from the `main` branch or another PR’s branch as necessary.

```sh
# Create feature branch for PR A
git checkout main
git checkout -b feature/A
# Make changes for A
git commit -m "Feature A"
git push origin feature/A

# Create feature branch for PR B based on A
git checkout feature/A
git checkout -b feature/B
# Make changes for B
git commit -m "Feature B"
git push origin feature/B
```

### 2. Open PRs for Each Feature Branch

- Open PR A targeting `main`.
- Open PR B targeting `feature/A`.

### 3. Merge Using Merge Queue or Rebase Strategy

#### Using GitHub Actions for Merge Queue

You can set up a GitHub Actions workflow to handle this:

1. **Create a Workflow File:** Create `.github/workflows/merge-queue.yml` in your repository.

    ```yaml
    name: Merge Queue

    on:
      pull_request:
        branches:
          - main

    jobs:
      merge-queue:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: Setup Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '14'

          - name: Install dependencies
            run: npm install

          - name: Run tests
            run: npm test

          - name: Merge PR
            if: github.event.pull_request.merged == 'false'
            run: |
              git fetch origin +refs/pull/${{ github.event.number }}/merge
              git checkout FETCH_HEAD
              git rebase origin/main
              git push origin HEAD:main
    ```

2. **Use GitHub CLI to Queue PRs:** Add PRs to the merge queue using GitHub CLI or another tool.

    ```sh
    gh pr merge <PR-A> --merge
    gh pr merge <PR-B> --merge
    ```

#### Rebasing Feature Branches

For a manual approach without CI/CD:

1. **Rebase PR B on PR A:**

    ```sh
    git checkout feature/B
    git rebase feature/A
    git push --force-with-lease origin feature/B
    ```

2. **Merge PR A:**
   Once PR A is merged, rebase PR B onto `main` and update the PR.

    ```sh
    git checkout feature/B
    git rebase main
    git push --force-with-lease origin feature/B
    ```

## Resources

- [GitHub Docs: Managing a branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-branch-protection-rule)
- [GitHub Actions: Using workflows](https://docs.github.com/en/actions/using-workflows)
- [Stack Overflow: Merging multiple PRs without conflicts](https://stackoverflow.com/questions/48654321/how-to-stack-pull-requests-with-github)
