### DISCUSSION TITLE
Not able to forcefully push code via Github workflow

### DISCUSSION THREAD

**Discussion by xavierbrabhakar** [community/community#134024] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

Team, I have a protected branch in GitHub, after enabling the "bypass actor to foreful push" i am able to push forcefully via local machine.
But the same command is being used in the workflow to commit the code getting below error.

**remote: error: GH006: Protected branch update failed for refs/heads/test.        
remote: error: Changes must be made through a pull request.        
To https://github.com/abc/xyz
 ! [remote rejected] test -> test (protected branch hook declined)
error: failed to push some refs to 'https://github.com/abc/xyz'
Error: Process completed with exit code 1.**

Could you please suggest on this.

**Comment by Faiaz3k** [comment]
use CI or CD tool

**Reply by xavierbrabhakar** [reply]
GitHub Workflow for this.

**Comment by Sivamani-18** [comment]
When dealing with a protected branch on GitHub, the "bypass actor to force push" option allows certain users to push changes directly to the branch from their local machine. However, this option might not apply to automated processes like GitHub Actions workflows by default. This results in the error you are seeing.

To resolve this, you need to ensure that the actor (the user or token) running the GitHub Actions workflow has the necessary permissions to bypass branch protection rules. Here are the steps to do so:

1. **Create a Personal Access Token (PAT) with Necessary Scopes:**
   - Go to your GitHub account settings.
   - Navigate to **Developer settings** > **Personal access tokens**.
   - Click on **Generate new token**.
   - Select the required scopes (at least `repo` scope for repository access).

2. **Store the PAT in GitHub Secrets:**
   - Go to your repository on GitHub.
   - Navigate to **Settings** > **Secrets and variables** > **Actions**.
   - Click on **New repository secret**.
   - Add a new secret with a name (e.g., `GH_PAT`) and paste the generated PAT as the value.

3. **Modify Your GitHub Actions Workflow to Use the PAT:**
   - In your workflow YAML file, configure the push step to use the stored PAT.

Here is an example of how you might update your workflow YAML:

```yaml
name: Push to Protected Branch

on: 
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          # Your commands to make changes to the repository
          echo "Changes made"

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Automated commit"
          git push origin HEAD:refs/heads/test --force
```

This approach ensures that the push operation in the workflow uses the PAT with the necessary permissions to bypass the branch protection rules.

### Additional Considerations:
- **Branch Protection Settings:** Double-check your branch protection rules to ensure that the required exceptions are in place for the user or token.
- **Workflow Permissions:** Ensure that the GitHub Actions runner has the necessary permissions. By default, GitHub tokens might not have the same bypass capabilities as a user’s PAT.

**Reply by xavierbrabhakar** [reply]
1. Enabled this repo permission --> **Allow specified actors to bypass required pull requests**
2. Enabled **Read and write permissions** under **Workflow permissions**

name:Update Version   from CI
--
  | on:
  | workflow_dispatch:
  | inputs:
  | app-name:
  | description: 'app name'
  | type: string
  | default: test-bump
  | required: true
  | image-version:
  | description: 'New image version'
  | type: string
  | required: true
  |  
  | permissions:
  | contents: write
  | packages: 'write'
  | actions: 'read'
  |  
  | jobs:
  | test_version:
  | runs-on: ubuntu-latest
  |  
  | steps:
  | - name: Show the inputs
  | run: \|
  | echo "app-name: ${{ inputs.app-name   }}"
  | echo "image-version: ${{   inputs.image-version }}"
  |  
  | - name: Checkout repository
  | uses: actions/checkout@v2
  |  
  | - name: Update version
  | run: \|
  | cd ${{ github.workspace   }}/root-apps/${{ inputs.app-name }}
  | sed -i 's/tag:.*$/tag: ${{   inputs.image-version }}/' test.yaml
  |  
  | - name: Check for changes
  | run: \|
  | if git diff --quiet && git   diff --cached --quiet; then
  | echo "No changes to   push"
  | else
  | echo "Changes detected"
  | fi
  | - name: Add and commit changes (if any)
  | run: \|
  | if git diff --quiet && git   diff --cached --quiet; then
  | exit 0
  | fi
  | git config --global user.name 'abc'
  | git config --global user.email 'abc@xyz.com'
  | git add .
  | git commit -m "${{   inputs.app-name }} -> ${{ inputs.image-version }}"
  | - name: Push changes (consider using   pull requests)
  | env:
  | GITHUB_TOKEN: ${{   secrets.PAT_CICD_TOKEN }}
  | run: \|
  | git push -f origin  HEAD:refs/heads/test       Please guide if I am   doing anything wrong?

**Reply by Sivamani-18** [reply]
Your workflow configuration seems mostly correct, but there are a few adjustments needed to ensure it functions correctly and adheres to best practices:

1. **Proper Indentation:** YAML relies heavily on indentation for structure. Ensure the indentation is consistent throughout the file.
2. **Ensure Correct Usage of GitHub Token:** Ensure you are using the PAT token correctly to push changes.

Here's the corrected version of your workflow:

```yaml
name: Update Version from CI

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'app name'
        type: string
        default: test-bump
        required: true
      image-version:
        description: 'New image version'
        type: string
        required: true

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  test_version:
    runs-on: ubuntu-latest

    steps:
      - name: Show the inputs
        run: |
          echo "app-name: ${{ inputs.app-name }}"
          echo "image-version: ${{ inputs.image-version }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update version
        run: |
          cd ${{ github.workspace }}/root-apps/${{ inputs.app-name }}
          sed -i 's/tag:.*$/tag: ${{ inputs.image-version }}/' test.yaml

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to push"
            echo "::set-output name=changes_detected::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes_detected::true"
          fi

      - name: Add and commit changes (if any)
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name 'abc'
          git config --global user.email 'abc@xyz.com'
          git add .
          git commit -m "${{ inputs.app-name }} -> ${{ inputs.image-version }}"

      - name: Push changes (consider using pull requests)
        if: steps.check_changes.outputs.changes_detected == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_CICD_TOKEN }}
        run: |
          git push -f origin HEAD:refs/heads/test
```

### Key Adjustments:
1. **Indentation:** Ensured proper indentation throughout the file for correct YAML structure.
2. **Conditional Execution:** Used `if` conditions to check whether changes are detected before attempting to commit and push changes.
3. **Output Variable:** Used `::set-output` to set an output variable indicating whether changes were detected.

Make sure the `PAT_CICD_TOKEN` secret is correctly set up in your repository's secrets. This token should have the necessary permissions to bypass branch protection rules and push to the protected branch.
