### DISCUSSION TITLE
GitHub Actions matrix job running despite false conditions

### DISCUSSION THREAD

**Discussion by semihural-tomtom** [community/community#134290] [Actions]
I am experiencing unexpected behavior in my GitHub Actions workflow where a job is being triggered despite all conditions evaluating to false. Specifically, the docker job starts even when all outputs from the changes job are false, which should prevent any of the matrix entries from running. Additionally, I am unable to access ${{ matrix.image }} when all conditions are false. Below is the relevant part of my workflow:

**Problem Details:**

The docker job is starting even when all the outputs from the changes job are false. When all conditions are false, it seems I cannot access ${{ matrix.image }}.

**Questions:**

What could be the reason that the docker job is being triggered despite all conditions evaluating to false? Is there a better way to structure the conditions to prevent the docker job from running when no changes are detected in the relevant paths?

```
jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      library: ${{ steps.filter.outputs.library }}
      workers: ${{ steps.filter.outputs.workers }}
      collector: ${{ steps.filter.outputs.collector }}
      api: ${{ steps.filter.outputs.api }}
      webhook: ${{ steps.filter.outputs.webhook }}
    timeout-minutes: 30
    steps:
        ...
      - name:
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            library:
              - 'package.json'
              - 'package-lock.json'
              - 'shared/**'
            workers:
              - 'workers/**'
              - 'prisma/**'
            collector:
              - 'collector/**'
            api:
              - 'api/**'
            webhook:
              - 'webhook/**'
  docker:
    name: Build and push Docker Images
    runs-on: ubuntu-latest
    needs: changes
    timeout-minutes: 30
    strategy:
      matrix:
        image: 
          - collector
          - workers
          - api
          - webhook
        isCollector:
          - ${{ needs.changes.outputs.collector == 'true' || needs.changes.outputs.library == 'true'}}
        isWorker:
          - ${{ needs.changes.outputs.workers == 'true' || needs.changes.outputs.library == 'true'}}
        isApi:
          - ${{ needs.changes.outputs.api == 'true' || needs.changes.outputs.library == 'true' }}
        isWebhook:
          - ${{ needs.changes.outputs.webhook == 'true' || needs.changes.outputs.library == 'true'}}
        exclude:
          - isCollector: false
            image: collector
          - isWorker: false
            image: workers
          - isApi: false
            image: api
          - isWebhook: false
            image: webhook
```

**Comment by ChristopherHX** [comment]
Yes this undocumented behavior has surprised me as well in 2021/22

> What could be the reason that the docker job is being triggered despite all conditions evaluating to false? 

Some logic in GitHub Actions decides an empty matrix after include and excludes means start the job as if you didn't use matrix strategy.

In your special case you can simplify checking that all matrix jobs should be skipped without repeating every condition

```yaml
docker:
    name: Build and push Docker Images
    runs-on: ubuntu-latest
    needs: changes
    timeout-minutes: 30
    # Importing this must be false if all matrix jobs should be skipped
    # other option is that changes return a matrix and a flag if it is empty
    # I assume this is correct expressions syntax, but didn't checked this
    if: contains(needs.changes.outputs.*, 'true')
    strategy:
      matrix:
        image: 
          - collector
          - workers
          - api
          - webhook
        isCollector:
          - ${{ needs.changes.outputs.collector == 'true' || needs.changes.outputs.library == 'true'}}
        isWorker:
          - ${{ needs.changes.outputs.workers == 'true' || needs.changes.outputs.library == 'true'}}
        isApi:
          - ${{ needs.changes.outputs.api == 'true' || needs.changes.outputs.library == 'true' }}
        isWebhook:
          - ${{ needs.changes.outputs.webhook == 'true' || needs.changes.outputs.library == 'true'}}
        exclude:
          - isCollector: false
            image: collector
          - isWorker: false
            image: workers
          - isApi: false
            image: api
          - isWebhook: false
            image: webhook
```
