### DISCUSSION TITLE
Gollum triggers should be configurable alongside more complex configurations like `pull_request`

### DISCUSSION THREAD

**Discussion by danieljurek** [community/community#13436] [Actions]
The `gollum` event should be configurable alongside events like `pull_request`. 

Reading through the documentation for [gollum](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#gollum) it's apparent that the entry for `gollum` in the `on` configuration can be a string in a list but the workflow does not trigger if you make `gollum` into an object. For example: 

This configuration is allowed: 

```yaml
on: 
  - gollum
  - workflow_dispatch
```

This configuration does NOT work: 

```yaml
on:
  gollum:     # note the addition of the colon which makes this a map
  workflow_dispatch: 
  pull_request:
    paths:
      - .github/workflows/workflow-triggered-by-wiki-events-that-i-want-to-test-in-pr.yml
```

Using the above configuration does not result in wiki events (adding or editing pages) triggering the workflow.

**Comment by ethomson** [comment]
Hmm. 🤔 I'm having a bit of trouble reproducing this problem @danieljurek. The following workflow file works as expected for me:

```yaml
name: Wiki

on:
  workflow_dispatch:
  gollum:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
```

This triggered on a gollum event from a wiki page addition.
