### DISCUSSION TITLE
Endless waiting for a runner to pick up job

### DISCUSSION THREAD

**Discussion by jongmee** [community/community#134482] [Actions]
### Select Topic Area

Bug

### Body

I'm running a job in ubuntu-latest. I ran the action as usual with the same script (yml file) as yesterday, but waiting occurs as shown in the picture below. Rerunning a job that went back successfully before is also the same result. There are no typos in the script. help me.. 😭

<img width="1031" alt="스크린샷 2024-08-03 오후 3 10 48" src="https://github.com/user-attachments/assets/d24b9f20-e09c-47e3-9c9b-e5cdfa1380ae">

- my workflow file
```
name: Backend CI

on:
  pull_request:
    branches: [ "be/develop" ]
  push:
    branches: [ "be/develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
(omission)
```
