### DISCUSSION TITLE
GIthub Actions failed to run on Node 16 and Node 20

### DISCUSSION THREAD

**Discussion by khajatakreemulla** [community/community#134478] [Actions]
### Select Topic Area

Question

### Body

Hello,

I'm encountering issues with my GitHub Actions workflow, specifically with the `npm ci` step failing.
We previously ran the environment on Node.js 16.x, but recently it started failing. As recommended by GitHub in [this announcement](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/), we attempted to update our workflow to use Node.js 20.x. Along with this, we also updated actions/checkout to v4 and actions/setup-node to v4.
![Screenshot from 2024-08-03 09-30-49](https://github.com/user-attachments/assets/b1f8500d-5d3c-4696-91bc-4af4e8e23fcb)
![Screenshot from 2024-08-03 09-30-28](https://github.com/user-attachments/assets/df1cc4c2-baa0-4787-b08f-8474415e76c5)

`Despite these changes, the npm ci step continues to fail for both Node.js 16.x and 20.x. Error: The operation was canceled.`

This are my node 16 configurations
```
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: npm test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    timeout-minutes: 5

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
      redis:
        image: redis:6.2
        ports:
          - 6379:6379

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-22.04]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    #- run: npm run build --if-present
    - name: Copy test configuration
      run: cp config/env/test.js_SAMPLE config/env/test.js
    - name: Run tests on ${{ matrix.os }} node ${{ matrix.node-version }}
      run: npm test
```

This are my current node 20 configurations as per [this announcement](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)
```
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: npm test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    timeout-minutes: 5

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
      redis:
        image: redis:6.2
        ports:
          - 6379:6379

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-22.04]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    #- run: npm run build --if-present
    - name: Copy test configuration
      run: cp config/env/test.js_SAMPLE config/env/test.js
    - name: Run tests on ${{ matrix.os }} node ${{ matrix.node-version }}
      run: npm test
```

Has anyone experienced similar problems or have any suggestions for troubleshooting and resolving this issue?

Any help or insights would be greatly appreciated.

Thank you!
