### DISCUSSION TITLE
Ayuda con código

### DISCUSSION THREAD

**Discussion by MelisaBM** [community/community#134519] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

Hola, estoy aprendiendo a utilizar esta herramienta y son mis primeros pasos en programacion. Tengo un problema al querer subir la imagen de fodo en mi GitHub page. alguien podria explicarme como puedo hacerlo? Muchas gracias

**Comment by davevad93** [comment, marked as answer]
Hi @MelisaBM ,

I've checked your repo [Mapa-del-Reciclaje](https://github.com/MelisaBM/Mapa-del-Reciclaje) and I've seen that you haven't put the image `fondo web.png` in the `index.html`. I don't know exactly what you want to achieve, but I can give you a couple of tips in the right direction, follow these steps:

1.  Change the `body` tag in your nested `css` as follows:
```css
        body {
            background: url("fondo web.png") no-repeat center center fixed;
            background-size: cover;
            font-family: 'Montserrat', sans-serif;
        }     
```
2. Now make the following changes to the `.contenedor` class in the nested `css` to make the background semi-transparent:
  ```css
        .contenedor {
            width: 90%;
            max-width: 1000px;
            margin: 20px auto;

           /* Add these three properties */
	        background: rgba(39, 115, 85, 0.8);
            padding: 20px;
            border-radius: 10px;
        }
   ```
3. Add the missing semicolon to the `background` property of the `.overlay` class
  ```css
        background: rgba(0, 0, 0, .3);
   ```

The final result would be as follows:

![0](https://github.com/user-attachments/assets/c2099331-531d-4632-b627-13a307330a3a)

A couple more tips, you don't need to do this right now but anyway I suggest you put the `css` code of your `index.html` in an external stylesheet called `estilos.css` and change your folder structure to make everything more organized, here's an example:

`/Mapa-del-Reciclaje`
`├── /css`
`|      └── estilos.css`
`├── /img`
`|      └── fondo web.png`
`└── index.html`

You will then have to change the path of your files accordingly:
```html
<link rel="stylesheet" href="css/estilos.css">
```
```css
background: url('../img/fondo web.png') no-repeat center center fixed;
```
File paths can be tricky at first. If you are new into `HTML`, `CSS` and programming in general, I suggest you take a look at the subject before making changes, here are a couple of good sources in Spanish on this topic.

- [Las rutas relativas en archivos CSS](https://www.jasoft.org/Blog/post/Las-rutas-relativas-en-archivos-CSS)
- [Cómo usar rutas absolutas y rutas relativas](https://pressroom.hostalia.com/white-papers/rutas-absolutas-y-relativas/)
