### DISCUSSION TITLE
Cannot combine branch and path filters for workflow triggers

### DISCUSSION THREAD

**Discussion by Mugane** [community/community#134570] [Actions]
### Cannot Combine PATH and BRANCH workflow triggers

This is the repo, but it is a generic problem: https://github.com/Mugane/Portainer

This is the relevant portion of the `./.github/workflows/ci.yml` file:
```
name: Build and Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - './templates/*.json'
      - './collate.sh'
jobs:
# etc...
```
I have also tried the following: `'./templates/*'`, `'./templates/**'`  and `'./templates/**/*.json'` to no effect. I have tried modifying both `./collate.sh` and `./templates/[somefile].json` to trigger it. Nothing. It works when I remove the paths section.

According to the [documentation](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#on) filtering by both branch and paths on push is a condition that should be possible. It is clearly broken:

>If you define neither tags/tags-ignore or branches/branches-ignore, the workflow will run for events affecting either branches or tags. If you define both branches/branches-ignore and [paths/paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), the workflow will only run when both filters are satisfied.
