### DISCUSSION TITLE
add timezone support to scheduling workflow runs with cron

### DISCUSSION THREAD

**Discussion by cj81499** [community/community#13454] [Actions] [answered]
Originally brought up at https://github.com/actions/runner/issues/1423, but I don't think anyone actually started a discussion.

> **Describe the enhancement**
> Please add timezones to cron schedules.
> 
> **Code Snippet**
> 
> ```
> name: Timed action
> on:
>   schedule:
>     - cron: '01 20 * * 1-5'
>     - timezone: 'Australia/Melbourne'
> ```
> 
> **Additional information**
> Especially when the schedule is only supposed to run on certain days of the week this gets very confusing with UTC. Daylight savings does not help much either here.

Among other things, the use case I have in mind is to run a workflow at 10AM local time (the start of the workday), but the best I can do currently is 15:00 UTC (9:00 CST, 10:00 CDT) or 16:00 UTC (10:00 CST, 11:00 CDT), meaning that ~half the year, it'll run at an undesirable time.

> [!IMPORTANT] 
> Please do not comment "waiting...", "+1", "need this", etc.
> 
> It adds nothing to the conversation and spams inboxes. Instead, leave a thumbs up and/or upvote to show your interest in this feature.
> 
> If you'd like to follow along for any updates to this thread, you can subscribe to the discussion by clicking the "Subscribe" button on the sidebar.

**Comment by rahulmr** [comment]
Why isn't this implemented yet? gitlab is already having this functionality afaik

**Reply by Starttoaster** [reply]
GitLab, in general, is way ahead of GHA in most features, having been in the CI market longer. So it shouldn't be a huge surprise noticing GitHub is well behind in yet another feature I'm interested in.

**Comment by rahulmr** [comment]
Any existing workaround? Also, I see that the workflow is sometimes not triggered at all even though I have my own runner which is in idle state.

**Comment by ethomson** [comment]
Thanks for the feedback @cj81499. I certainly agree that time zones and scheduling is tricky, so I'll make sure that this is on the backlog.

**Reply by rahulmr** [reply]
Thanks for looking into this, it will be very helpful, also if possible please suggest some link where I can make sure that triggers on my runner happen on time. (I know it is different topic).

**Reply by bbrewington** [reply]
@ethomson is there some public-facing backlog I could follow to get updates on this feature?

**Reply by canyon289** [reply]
I would also like this!

**Reply by brunubarbosa** [reply]
Waiting for update :c

**Reply by BenElferink** [reply]
Waiting...

**Reply by ajimae** [reply]
waiting...

**Reply by cj81499** [reply]
Hey @ethomson, I took a look at your profile and notice that you're no longer working at GitHub. Did this ever make it onto a backlog that we can watch for updates? If not, any chance you could forward it along to an (ex-)coworker? I think it's clear from the upvotes and thumbs ups in this discussion that there are quite a few people (myself included) that would really benefit from this feature. Thanks!

**Reply by cj81499** [reply]
Also, for anyone else, please do not comment "waiting..." (or similar). It adds nothing to the conversation and spams our inboxes. Instead, a thumbs up or upvote is a great way to show interest.

If you'd like to follow along for any updates to this thread, you can subscribe to the discussion.

**Reply by bbrewington** [reply]
I reached out to a member of MS Github Actions team here: https://github.com/actions/runner/issues/1177#issuecomment-1264452804

Not entirely sure if that issue is related, but hopefully it helps this group to get a better answer to an issue that has clear popularity/interest

**Reply by cj81499** [reply]
@bbrewington thank you for reaching out! I never considered that marking an answer on this thread would reduce the attention it gets, but that idea makes a lot of sense to me. I'll unmark it to see if that draws some additional attention our way.

**Comment by ruettenm** [comment]
We are also interested in this feature. Are there any plans to implement a timezone support?

**Comment by vincentneo** [comment]
Just bringing up another use case that would benefit with the addition of this, in case it further helps convince the addition of this feature.

For asian timezone regions, such as here in Singapore (GMT+8), a relatively simple use case of running a workflow on midnight of every 1st day of the month, is basically impossible to schedule as:

12AM here on the first day of the month would be have been basically impossible to write with cron, since, it would require writing it as 4PM of the last day of the month could be 28, 29, 30 or 31.

For example:
12AM (GMT+8) at 1 October would be 4PM (UTC) at 30 September.

Having this would make it easy to schedule with just a `0 0 1 * *`, with Singapore's timezone.

**Comment by 0968637527** [comment]
Y

**Comment by villelahdenvuo** [comment]
Another really useful feature would be to be able to add random jitter like cron supports because we can run into ratelimits when we have multiple actions running at the same time.

**Reply by cj81499** [reply]
@villelahdenvuo While I agree that'd be useful, I believe it's different enough from my proposed feature to justify its own discussion post. If you make one, please share it with me!

**Reply by bbrewington** [reply]
In case it helps, Jenkins has the “H” thing and I believe it’s implemented here: https://github.com/jenkinsci/jenkins/tree/master/core/src/main/java/hudson/scheduler

**Comment by bcowdery** [comment]
As a super hacky workaround, you can schedule your workflow to run at BOTH standard and daylight times, and then use a bash script to filter out the undesirable runs. This means you'll have 2 runs for every schedule date, but only one of them will execute past the `Test schedule` step.

Something like this should work:
```yaml
on:
  schedule:                             
    - cron: "00 18,19 * * TUE"    # Run every tuesday at 12:00 noon MDT (GMT-6) and MST (GMT-7)

env:
  TZ: "America/Edmonton"
  LOCAL_TIME: "12:00"
  
jobs:
  test-date:
    runs-on: ubuntu-latest
    steps:
      - name: Test schedule
        if: github.event_name == 'schedule'
        run: |
          now=$(date +%s)
          local_time=$(date -d "$LOCAL_TIME" +%s)

          if [[ $now -gt $local_time && $now -lt "$((local_time + 3600))" ]]; then
              echo "🌞 Passed daylight savings time check!"
          else    
              echo "⏱ Waiting until $LOCAL_TIME."
              exit 1
          fi
```

**Reply by stolsvik** [reply]
Well, yes, you can set the schedule to run every minute, and reimplement the cron solution, this time in a sane way with TZ support.

It is just very sad.

**Comment by ghost** [comment]
I've created a Workaround like @bcowdery, but mine won't fail the run:

```yaml
on:
  schedule:
    - cron: '5 16,17 * * *'

jobs:
  check-run:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check_local_time.outputs.run }}
    steps:
      - name: Check local time
        id: check_local_time
        env: 
          TRIGGER: ${{ github.event_name }}
        run: |
          echo "Trigger: ${TRIGGER}"
          if [[ ${TRIGGER} == 'schedule' ]]; then
            echo "Checking daylight saving time"
            if [ $(date --date='TZ="Europe/Berlin" now' +%H) -eq '18' ]; then 
              echo 'Time to run!'
              echo "run=True" >> "$GITHUB_OUTPUT"
            else
              echo "It's not 18:05 local time in Europe/Berlin. Waiting for next execution..."
              echo "run=False" >> "$GITHUB_OUTPUT"
            fi
          else
            echo 'Trigger is not cron, ommiting time check!'
            echo "run=True" >> "$GITHUB_OUTPUT"
          fi
  
  my-job:
    runs-on: ubuntu-latest
    if: needs.check-run.outputs.run == 'True'
    needs: check-run
```

Still, I would love to not use this workaround, but perhaps this is useful for anybody.

**Reply by MartijnHols** [reply]
Thanks, but I couldn't make the timezone work with `date --date='TZ="Europe/Berlin" now' +%H`. I had to change it to `TZ="Europe/Berlin" date +%H`.

**Reply by rahulmr** [reply]
GHA guys please do something for this feature

**Comment by MissaelHRC** [comment]
My team continue waiting for this feature, do you know if GitHub team already have a ticket in progress to attend it? @cj81499 @rahulmr Thanks!

**Comment by chandrasekhar-prathap** [comment]
This is a much needed feature in GH, any updates on this please.

**Comment by razvanvancea** [comment]
any progress on this feature? thanks!

**Comment by Creator54** [comment]
Hi guys any updates on this?
thanks

**Comment by dgsauve** [comment]


**Reply by connorjclark** [reply]
Sure. Your comment alerts hundreds of people interested in a meaningful update from GitHub, but instead we got a "me too" reply. Just subscribe to alerts and move along.

**Comment by kopax-polyconseil** [comment]
Seems like easy to implement and would sove a lot of problem.

**Comment by konjoinfinity** [comment]
I am very interested in this feature.

**Comment by ChrisPage-AT** [comment]
I'm not sure why there are so many thumbs down reactions on these comments.  This feature would greatly improve usability and bring GHA in line with other cicd offerings.  Can we please get any indication if this has made it onto a backlog somewhere or if this won't be implemented?  Thanks!

**Reply by prangel-stuller** [reply]
See connorjclark's comment above on why the thumbs down reactions. If you want to express interest in a feature, do so via reacting to the original post and subscribing for alerts. Don't hit others with unnecessary notifications.

**Comment by wt-asw** [comment]
also interested in this feature

**Comment by elwinschmitz** [comment]
As a quick-and-dirty workaround, I've settled on using this `schedule` in my workflow:

To run a few times during working-hours on week-days only:

```yml
schedule:
    # During "Central European Time" (CET): Offset from UTC: -1
    - cron: '42  7,10,13,16  *  11-12,1-3 1-5'
    # During "Central European Summer Time" (CEST): Offset from UTC: -2
    - cron: '42  6,9,12,15   *  4-10      1-5'
 ```

During winter-months, it runs on a 1-hour offset, during summer-months on a 2-hour offset.

This will be _technically incorrect_ for a few days per year. But in my case that outweighs the hassle of "having to remember to change the `cron`-schedule twice every year"...

**Reply by orroth** [reply]
I hate that I need this, but thankyou...
Scheduling Sun-Thur late PM so that I can run actions Mon-Fri early AM feels dirty...
...at least it mostly handles the daylight time offset change without me needing to manually update it.

**Comment by orange723** [comment]
I need this feature

**Comment by sdcb** [comment]
I also need this feature

**Comment by ngocdd** [comment]
2024 still - LOL

**Comment by nopa12** [comment]
also needs this :)

**Comment by simon-stathealth** [comment]
we need this

**Comment by cj81499** [comment]
Please do not comment "waiting...", "+1", "need this", etc.

It adds nothing to the conversation and spams our inboxes. Instead, leave a thumbs up or upvote to show your interest in this feature.

If you'd like to follow along for any updates to this thread, you can subscribe to the discussion without commenting by clicking the "Subscribe" button on the sidebar.

**Reply by LiteBrite82** [reply]
@cj81499 is correct! 🦸 
Please dont be offended if your +1 comment was hidden, its just to keep the discussion clean.

Thanks, Communuty!

**Comment by javixeneize** [comment]
Hi

I’m surprised we are finishing 2024 and this is still not implemented after so much interest from the community 

Would you be open to allow the community to do a PR with the relevant changes, if this is not a priority for you?

**Comment by nebuk89** [comment]
Sorry no one has commented on this for a while, I will add this to our papercut backlog we are working though. I don't have a timeframe right now but I will check what the effort is. Thanks for your patience with this <3

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Reply by javixeneize** [reply]
Thanks, but, why don’t you let us help you? That’s something that we as a community can easily implement and you just need to review it

is it not all about open source and collaboration?

**Comment by DrStrangepork** [comment]
Reading the comments here, it is unclear to me whether or not the code responsible for accommodating timezone is public or not. If it is, can someone share which repo and code the community can work with to add this feature?

**Reply by data-intelligence-analysis** [reply]
I would like to know this as well since I do have some CI/CD workflows that would be nice to have the timezone feature!

**Comment by omnicortex** [comment]
I need this feature.

**Comment by coltenkrauter** [comment]
Since GitHub Actions doesn’t support timezones in cron scheduling yet, here’s a possible workaround to run workflows at local times like 8 AM PST.

```yaml
name: Run Task at 8 AM

on:
  schedule:
    # Runs at 3 PM UTC (8 AM PDT) and 4 PM UTC (8 AM PST)
    - cron: '0 15,16 * * *'

jobs:
  check_time:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's 8 AM
        run: |
          current_hour=$(TZ='America/Los_Angeles' date +'%H')
          echo "Current hour in PST: $current_hour"
          
          if [ "$current_hour" == "08" ]; then
            echo "It's 8 AM PST! Running tasks..."
            echo "run_tasks=true" >> $GITHUB_ENV
          fi

      - name: Execute Scheduled Tasks
        if: env.run_tasks == 'true'
        run: echo "Executing scheduled tasks..."

```

**Comment by tkelly-mgm** [comment]
For an approximate answer, I noted that the DST transition for `America/Los_Angeles` was always on certain numbered days of the month. There's no way to indicate instances of weekdays, so I figured that the least bad solution was to run halfway between offsets if we couldn't tell.

```
schedule:
  # 8 AM PST from week 2 of Nov to week 1 of Mar
  - '0 16 8-30 11 *'
  - '0 16 * 12-2 *'
  - '0 16 1-7 3 *'
  # Between offsets for week 2 of Mar
  - '30 15 8-14 3 *'
  # 8 AM PDT from week 3 of Mar to end of Oct
  - '0 15 15-31 3 *'
  - '0 15 * 4-10 *'
  # Between offsets for week 1 of Nov
  - '30 15 1-7 11 *'
```

**Comment by radiomix** [comment]
Setting the `timezone` for _long running_ scheduled jobs would _facilitate_  our CI/CD pipeline to sync with `log4j` rotation setup. :-//

**Comment by solita-juhosassali** [comment]
Any updates on this? We need this feature in our project as well and now have to manually adjust schedule two times per year. We can manage with a workaround provided by @coltenkrauter (thanks by the way!) but it would be way better to just give the timezone and forget about it.

**Comment by nebuk89** [comment]
We are currently having a look at this to see what we can do :) hopefully this is something we can get moving very soon

**Reply by plchampigny** [reply]
Haha, hopefully "very soon" will be before march 8 🤣

**Reply by nebuk89** [reply]
Currently looking like Q1 next year, I will try to get some better updates come Jan <3 thanks for the patience on this one.

**Comment by sagivaknin1** [comment]
We also would love to have this feature asap.
Following the thread.
Hoping it will be added soon (:

**Comment by nebuk89** [comment]
We should be on track for end of March for a public beta, public roadmap is updated and has this in :)

**Reply by alyasilpiah** [reply]
wow finally @nebuk89

**Reply by nebuk89** [reply]
We are still on track for before the end of the month, thanks for the patience here <3

**Comment by nebuk89** [comment, marked as answer]
https://github.blog/changelog/2026-03-19-github-actions-late-march-2026-updates/ We are now live :) 

Thank you everyone who engaged on this. I know that you all waited and that you were let down at times. I will keep pushing to get our top items closed out on Actions, I will keep being in the community as much as I can from my time to understand what you all need. And please please keep telling us what you need, it is not 'screaming into the void' we are here :)

**Reply by maxdanilov** [reply]
@nebuk89 it seems there's a bug now, and the timezone field breaks workflow dispatch working. How to reproduce:

example workflow to call:

```yaml
#deploy.yml

name: Deploy

on:
  schedule:
    - cron: '30 2,8,13,18 * * *'
      timezone: 'Europe/Berlin'
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to deploy'
        required: false
        default: dev
        type: choice
        options:
          - all
          - dev
          - prod

jobs:
  deploy:
    # some job here

```

now calling it like that:

```bash
curl -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $TOKEN" \
  https://api.github.com/repos/$OWNER/$REPO/actions/workflows/deploy.yml/dispatches \
  -d '{
    "ref": "main",
    "inputs": {
      "target": "dev"
    }
  }'
```

results in:

```json
{
  "message": "Invalid Argument - failed to parse workflow: timezone in scheduled workflows is not yet supported",
  "documentation_url": "https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event",
  "status": "422"
}
```

At the same time, the cron expression itself with timezone still works (it's run regularly - but not possible via a dispatch anymore in addition to that).

**Reply by gdonati78** [reply]
I noticed the same issue, when trying to run manually from github UI

**Reply by BenRogersWPG** [reply]
Yes, I am getting these similar errors:
`Failed to queue workflow run: Invalid Argument - failed to parse workflow: timezone in scheduled workflows is not yet supported`

Workflow dispatch (manual runs) seem to work via the mobile app. But not via CLI/API or GitHub website

**Reply by angel-jiakou** [reply]
Thanks for catching that! We are working on a fix now and will release it soon. You can update the workflow file directly as a workaround for now.

**Reply by angel-jiakou** [reply]
I just merged the fix. This issue should be fixed now

**Reply by dj-256** [reply]
Hi, for me the timezone parameter is recognized (not by my IntelliJ though), but the schedule is wrong. I configured it to run at 4:47 AM "Europe/Paris" and it runs at ~5:47 AM (I'm in France, we only have one tz)

**Reply by angel-jiakou** [reply]
Hi @dj-256, I believe that means the timezone feature is working as expected. Schedules have delays in general which explains why you are seeing your workflow being run an hour later. This exists without timezone support as well.

**Reply by JeppeKnockaert** [reply]
@angel-jiakou Also seeing a > 1 hour delay from Europe/Brussels, looks like it could be related to the DST switch (we switched from UTC+1 to UTC+2)

**Reply by prashantbnew** [reply]
@angel-jiakou Is this timezone support is working?
The cron is set to run on 11 AM Brussels time, but it is starting at 12:14 P.M.

**Reply by Abdelgha-4** [reply]
> Schedules have delays in general which explains why you are seeing your workflow being run an hour later

I don't believe this is true, it is very unlikely that "the general delays" experienced by multiple users (including me) for independent schedulers is about exactly one hour, this rather strongly suggests an issue with the DST handling logic with this new feature, please investigate this more deeply.

**Reply by jin-harmoney** [reply]
We never experienced any noticeable delays when working without timezones. This morning, we had this after switching to `Europe/Brussels`:
* Workflow scheduled at `5:00 A.M.`, executed at `8:18 A.M.`
* Workflow scheduled at `5:30 A.M.`, executed at `8:24 A.M.`
* Workflow scheduled at `5:37 A.M.`, executed at `8:35 A.M.`
3h+ delays are not ok, nor expected. Our nightly production release suddenly ran in the morning.

**Reply by TueeNguyen** [reply]
I'm experiencing delays too, workflows are always late at least 30 minutes. My work relies on GHA being punctual

**Reply by Mr0grog** [reply]
> My work relies on GHA being punctual

FWIW, a 30 minute delay on GHA is not that unusual in my experience. The docs suggest jobs will often have some notable delay, although they make it sound like it should be less than it often is in practice (at least in my many years of usage). If you need tightly timed or frequently-running jobs, you should probably use a different system for them.

An hour-plus delay, on the other hand, really does sound like the time zones are off, or are being treated as static offsets rather than actual zones, which change offsets over the course of the year! Seeing those reports is a major reason I’ve avoided this feature so far, even though I’d really like to have it.

**Reply by abaker-sp** [reply]
When I modified a Git Actions job to switch from UTC to using the timezone feature (7 days ago), the jobs immediately started having much longer delays in running.  The past 4 days, the delay has been 3 1/2 hours.  I'm having to revert back to UTC.  Here is what I was running:
```
    - cron: '30 7 * * *'
      timezone: "America/Chicago"    
```

**Reply by codeskipper** [reply]
Same here, the execution delays I'm seeing after adding the timezone setting went from under one hour to nearly two hours.  A bit confusing as our UTC offset is two hours in summer time.

**Reply by jmspereira** [reply]
I think that the problem happens even without a timezone defined. I was waiting for this feature to be more stable before starting to use it, and I am also observing a large delay (+ 2 hours) in my cron workflows. In the last 4 years, I have never seen this, only a couple of minutes of delay.

**Reply by fseguin-pass** [reply]
FYI delays are happening without specifying a timezone, you can upvote this issue: https://github.com/orgs/community/discussions/156282 and hope that GH acts.

**Comment by mcassaniti** [comment]
I'm likely to get in a bit of trouble, but I just want to say a big thank you. The community knows this has been a long time coming and it's finally here. Thank you for making our lives just that bit easier.

**Comment by haeraeus** [comment]
❤️

**Comment by Tao-Galasse** [comment]
Hi! Thanks for the feature :)

Do you know if the `on:` supports an env variable ? I would like to define my actions like this: 
```yml
schedule:
  - cron: '0 8 * * *'
  timezone: ${{ vars.TZ }}
```
