### DISCUSSION TITLE
Decoding file retrieved using REST API

### DISCUSSION THREAD

**Discussion by Stefan923** [community/community#134693] [Apps, API and Webhooks]
### Select Topic Area

Question

### Body

Hi. I am trying to get a file's content using the REST API. It says it's encoded using Base64, but I have an issue decoding the content. Even if I have tried decoding with multiple character encodings (UTF-8, ASCII and so on).

When I decode the content, I get some special characters like these:

```yaml
name: OctaneIntegration
# Events the integratv���6��V�B&RG&�vvW&VB���㠢V���&WVW7@':
    types: [opened, edited, closed, reopenevEТ'&�6�W3��v�7FW"r�wFW7B�'&�6�r�p'second-branch' ]
```

This is the endpoint I'm calling: [/repos/{owner}/{repo}/contents/{path}](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content)

Does anyone know how to decode this content?
