### DISCUSSION TITLE
Dependabot: How to Split Security Alerts by Teams in Monorepos

### DISCUSSION THREAD

**Discussion by Akaame** [community/community#134758] [Code Security]
### Select Topic Area

Question

### Body

Hello,

We have a mono-repo like project where different modules are built with different toolings of choice and the Dependabot configuration reflects that as follows:

```
---
version: 2
updates:
  - package-ecosystem: gradle
    directory: /project-1
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    registries:
      - maven-artifactory
    reviewers:
      - "org/team-1"
  - package-ecosystem: npm
    directory: /project-2
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    reviewers:
      - "org/team-2"
 ```
 
Both teams have codeownership to the repository. When we view the alert dashboard under `https://github.com/orgs/<ORG?/security/overview`, the alerts from both ecosystems are attributed to both of the teams. Let's say we have 2 alerts from `gradle` ecosystem and 3 from `npm`. When we filter by `team: team-1`, 5 alerts are reported for the repository. Such is also the case for the second team. How can we make this split for the two teams so that one only gets `gradle` alerts and the other one only gets `npm` alerts, without breaking up the repository?
