### DISCUSSION TITLE
Huge difference in time used for the same action step?

### DISCUSSION THREAD

**Discussion by tomlau10** [community/community#134825] [Actions]
### Select Topic Area

Question

### Body

In my project I have a `build_deploy` workflow which will build docker image and push to gcloud, then deploy to gke. In the workflow one of the steps is to install the gke auth plugin:
```yml
      - name: Install gke gcloud auth plugin
        id: install-gke-auth
        continue-on-error: true
        run: |
          # fix deprecated gke auth, ref: https://github.com/actions/runner-images/issues/5925
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          # only apt-get update the gcloud sdk repo to save a few seconds, ref: https://askubuntu.com/a/65250
          sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/google-cloud-sdk.list" -o Dir::Etc::sourceparts="-"
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> ${GITHUB_ENV}
```
- I think I've optimized it to the limit, and this runs `3~5s` normally
- But sometimes this step takes a whopping `20+s` 🙄 
I have checked the logs, it's the `Reading database ...` step during `apt-get install` that runs very slow...

Here are the logs with timestamp:
- when the step takes `5s`
```
...
Tue, 06 Aug 2024 06:21:04 GMT Selecting previously unselected package google-cloud-cli-gke-gcloud-auth-plugin.
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 5%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 10%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 15%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 20%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 25%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 30%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 35%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 40%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 45%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 50%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 55%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 60%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 65%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 70%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 75%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 80%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 85%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 90%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 95%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 100%
Tue, 06 Aug 2024 06:21:04 GMT (Reading database ... 266555 files and directories currently installed.)
Tue, 06 Aug 2024 06:21:04 GMT Preparing to unpack .../google-cloud-cli-gke-gcloud-auth-plugin_486.0.0-0_amd64.deb ...
Tue, 06 Aug 2024 06:21:04 GMT Unpacking google-cloud-cli-gke-gcloud-auth-plugin (486.0.0-0) ...
...
```
- when the step takes `20+s`
```
...
Tue, 06 Aug 2024 04:27:24 GMT Selecting previously unselected package google-cloud-cli-gke-gcloud-auth-plugin.
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 5%
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 10%
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 15%
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 20%
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 25%
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 30%
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 35%
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 40%
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 45%
Tue, 06 Aug 2024 04:27:24 GMT (Reading database ... 50%
Tue, 06 Aug 2024 04:27:25 GMT (Reading database ... 55%
Tue, 06 Aug 2024 04:27:25 GMT (Reading database ... 60%
Tue, 06 Aug 2024 04:27:26 GMT (Reading database ... 65%
Tue, 06 Aug 2024 04:27:27 GMT (Reading database ... 70%
Tue, 06 Aug 2024 04:27:29 GMT (Reading database ... 75%
Tue, 06 Aug 2024 04:27:31 GMT (Reading database ... 80%
Tue, 06 Aug 2024 04:27:34 GMT (Reading database ... 85%
Tue, 06 Aug 2024 04:27:36 GMT (Reading database ... 90%
Tue, 06 Aug 2024 04:27:38 GMT (Reading database ... 95%
Tue, 06 Aug 2024 04:27:38 GMT (Reading database ... 100%
Tue, 06 Aug 2024 04:27:38 GMT (Reading database ... 266555 files and directories currently installed.)
Tue, 06 Aug 2024 04:27:38 GMT Preparing to unpack .../google-cloud-cli-gke-gcloud-auth-plugin_486.0.0-0_amd64.deb ...
Tue, 06 Aug 2024 04:27:38 GMT Unpacking google-cloud-cli-gke-gcloud-auth-plugin (486.0.0-0) ...
...
```

---

I know that each time a job maybe dispatched to different runners.
Is that some of the runners are having faulty hard drives / not running on **SSDs**? 🙄

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by nebuk89** [comment]
Huh, no all our runners are pretty consistent or as consistent as they can be with what Azure gives us under the SKU name :) 

This could be an occasional machine in a bad state though, how often are you seeing this?

**Reply by tomlau10** [reply]
Hi, I just looked at my team's deploy action log. Of the previous **60** runs, **11** of them taking double or more of the usual time:
(latest build id is `15170`
- `15163` 16s
- `15159` 9s
- `15150` 22s
- `15147` 10s
- `15140` 10s
- `15136` 13s
- `15135` 8s
- `15133` 13s
- `15115` 9s
- `15113` 11s
- `15110` 8s

where the usual time of this step is `3~5s` as described above, and we are doing around 400-500 builds a month
@nebuk89

**Reply by nebuk89** [reply]
hmmm not ideal. Are these private or public repos? And have you opened a ticket with support? If not please do so and just add my GitHub id into the details so they know to ping me :D

**Reply by tomlau10** [reply]
Hi @nebuk89, it is a private repo.

I originally wanted to open a support ticket with it, but seems github dropped ticket support for general questions 🥲 ?
When I click **new ticket**, it only allows me to choose from the follow topics:
![image](https://github.com/user-attachments/assets/24484bf1-84af-4d00-bc4f-e3c5540409e4)

And for others it redirects me to this **community forum**, and that's the reason why I open a discussion here... 🤦‍♂️ 
I remembered I have opened support ticket before for another github action related issues, probably a year or more ago, and I can grant customer support with special permission to look into our private repo's action log at that time

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by tomlau10** [comment]
I have had enough of this ...
And finally I find a way to **workaround** it:
=> by **directly downloading** the `gke-gcloud-auth-plugin` binary from google🤣
```yaml
      - name: Install gke gcloud auth plugin
        env:
          pkgname: google-cloud-cli-gke-gcloud-auth-plugin
          pkgver: 523.0.0
        run: |
          # directly install gke-gcloud-auth-plugin, ref: https://aur.archlinux.org/packages/google-cloud-cli-gke-gcloud-auth-plugin
          curl -L https://dl.google.com/dl/cloudsdk/release/downloads/for_packagers/linux/${pkgname}_${pkgver}.orig_amd64.tar.gz \
            | tar -xz -C /usr/local/bin/ --no-anchored --transform='s|.*/||' gke-gcloud-auth-plugin
          chmod a+x /usr/local/bin/gke-gcloud-auth-plugin
          gke-gcloud-auth-plugin --version
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> ${GITHUB_ENV}
```
This skip the whole `apt-get install` which requires scanning existing package folders on disk

PS: I still believe that sometime the dispatched vm might have a shitty harddisk 🙄
