### DISCUSSION TITLE
Variable branch filter for on:push events?

### DISCUSSION THREAD

**Discussion by gilzow** [community/community#134881] [Actions]
### Select Topic Area

Question

### Body

I have a workflow that is triggered via the `on: push` event. Normally, we want this to be filtered by the branch name, usually for the branch named `update`. However, we have a few situations where the branch name will be different. I tried to use the following, and while GitHub gladly accepts this as a valid workflow, it never actually fires.

```
on:
  push:
    branches:
      - ${{ '' != vars.SOP_UPDATE_BRANCH && vars.SOP_UPDATE_BRANCH || update }}
  workflow_dispatch:
```

Is this not possible, or is the syntax incorrect? The [docs mention that you can use glob patterns](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore), but doesn't confirm or deny the use of `${{ }}` expression syntax for branch filtering.
