### DISCUSSION TITLE
Concurreny groups not cancelling waiting runs

### DISCUSSION THREAD

**Discussion by eirikdal** [community/community#135220] [Actions] [answered]
### Select Topic Area

Question

### Body

We have workflows with concurreny groups defined in this way:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

This works fine for cancelling in progress workflows. However, on our `main` branch we have branch protection on production deploys which cause workflows to enter into a `Waiting` state on a successful merge to `main`, pending a review from someone, which is fine. 

The problem is if this workflow run is not reviewed by someone, then a subsequent workflow run will permanently enter into a `pending` state until the previous run is reviewed. But, what we want to happen is instead the previous run to be cancelled as if it was an in-progress run. But maybe this isn't the intended behaviour, but I couldn't find any documentation on what is supposed to happen to workflows in the Waiting status. And, if so, is there some way we can alternatively configure our workflows so that the concurrency group doesn't apply to runs on the main branch? It is a little bit of a chore to have to find the old workflow run just to decline it, just to have the new run being picked up by the runner.

**Comment by nicolalunghi-xlnx** [comment]
any news on this?

my proposal

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
  max-jobs: 10
  timeout: 100000000
```
