### DISCUSSION TITLE
could not load the default credentials error in deploy action to GKE

### DISCUSSION THREAD

**Discussion by dundejan** [community/community#135236] [Actions]
### Select Topic Area

Bug

### Body

Hello everybody,
I am quite new to DevOps and I wanted to try deploying simple php web app to GKE. Deploying manually in my terminal works great, but I wanted to use pipeline (action) to do that automatically. I followed the documentation [Deploying to Google Kubernetes Engine](https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine) and wanted to use the example workflow as mentioned [here](https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine#creating-the-workflow).

I used this .github/workflows/main.yml:

```yaml
name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}  # Your project ID from secrets
  GKE_CLUSTER: my-cluster                 # Your cluster name
  GKE_ZONE: europe-west1-b                # Your cluster zone
  DEPLOYMENT_NAME: my-simple-php-app      # Your deployment name
  IMAGE: my-simple-php-app                # Your Docker image name

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
    - run: |
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ env.PROJECT_ID }}   # Explicitly set the project_id

    # Build the Docker image
    - name: Build
      run: |
        docker build \
          --tag "gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}" \
          --build-arg GITHUB_SHA="${{ github.sha }}" \
          --build-arg GITHUB_REF="${{ github.ref }}" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push "gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}"

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${env.DEPLOYMENT_NAME}=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
        kubectl get services -o wide
```

I set the secrets GCP_PROJECT and GCP_KEY to correct value (resp. json for GCP_KEY) in my github secrets. Now when I run this, I get error:

```bash
Run google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
  with:
    cluster_name: my-cluster
    location: europe-west1-b
    project_id: ***
    use_auth_provider: false
    use_internal_ip: false
    use_connect_gateway: false
  env:
    PROJECT_ID: ***
    GKE_CLUSTER: my-cluster
    GKE_ZONE: europe-west1-b
    DEPLOYMENT_NAME: my-simple-php-app
    IMAGE: my-simple-php-app
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 1.1.0
##[debug]Using context name: gke_***_europe-west1-b_my-cluster
Error: google-github-actions/get-gke-credentials failed with: could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
```

I double checked the secrets and tried to change them or even generate new GCP_KEY json, but still the same error. Can somebody help me? 

Thanks

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by everforyou** [comment]
Hello @dundejan ,

It is related to Google Cloud credentials while trying to deploy a PHP web app to Google Kubernetes Engine (GKE) using GitHub Actions. The error message indicates that the default credentials could not be loaded. Here are some steps to troubleshoot and resolve the issue:

### Troubleshooting Steps

1. **Check GitHub Secrets**:
   - Ensure that your GitHub secrets (`GCP_PROJECT` and `GCP_KEY`) are set correctly. The `GCP_KEY` should be the entire JSON key file for the service account, not just part of it.

2. **Service Account Permissions**:
   - Verify that the service account associated with the `GCP_KEY` has the necessary permissions to access GKE and perform deployments. It should have roles like:
     - Kubernetes Engine Admin
     - Storage Admin
     - Viewer (or other necessary roles depending on your setup)

3. **Correct YAML Syntax**:
   - Ensure that your YAML file syntax is correct. For example, ensure that indentation is consistent and that you are using the correct variable syntax. The environment variables should be referenced properly, as shown below:
     ```yaml
     project_id: ${{ env.PROJECT_ID }}
     ```

4. **Using the Correct Action**:
   - Make sure you are using the correct GitHub Action for setting up GKE credentials. The line should look like this:
     ```yaml
     - uses: google-github-actions/get-gke-credentials@vX.Y.Z
     ```

5. **Debugging Information**:
   - Add debug logging to your workflow to help identify where it might be failing. You can add `echo` statements to print out the values of your environment variables (be careful not to expose sensitive information).

6. **Run Locally**:
   - If possible, try running the deployment commands locally using the same service account credentials to ensure that they work outside of GitHub Actions.

### Example Configuration

Here’s a simplified example of how your `.github/workflows/main.yml` might look:

```yaml
name: Build and Deploy to GKE
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GKE_CLUSTER: my-cluster
  GKE_ZONE: europe-west1-b
  DEPLOYMENT_NAME: my-simple-php-app
  IMAGE: my-simple-php-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Build Docker image
        run: |
          docker build \
          --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:latest .

      - name: Publish Docker image
        run: |
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:latest

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${DEPLOYMENT_NAME}=${{ env.IMAGE }}:latest
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
          kubectl get services -o wide
```

After making these changes, try running your GitHub Actions workflow again. If the error persists, check the logs for more detailed error messages, and consider reaching out to the GitHub community or Google Cloud support for further assistance.

I hope this'll solve your problem.
