### DISCUSSION TITLE
Private Image for DinD container

### DISCUSSION THREAD

**Discussion by geogdog** [community/community#135497] [Actions]
### Select Topic Area

Question

### Body

Hi Team!

Could there be a way to easily override the dind image to make it use a private repo (in order to avoid the docker hub request limiting)?

A mechanism similar to the main image:

```
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
      - name: dind
        image: <my-custom-image>
        ...
```

or even just redefining `gha-runner-scale-set.dind-container` in _helpers.tpl to handle the dind image in the same way as the init container?

I look forward to the discussion.

Cheers,
Greg
