### DISCUSSION TITLE
Forwarded port changes from HTTPS to HTTP after a restart

### DISCUSSION THREAD

**Discussion by sayhiben** [community/community#13541] [Codespaces]
My Codespace uses the Docker-from-Docker strategy to host several Docker containers, including one for nginx. Ports are forwarded in `.devcontainer/devcontainer.json` as follows:

```yaml
"forwardPorts": [
    8002
],
"portsAttributes": {
    "8002": {
        "label": "Web App (https via nginx)",
        "onAutoForward": "notify",
        "protocol": "https",
        "requireLocalPort": true
    }
}
```

When I first run `docker-compose up`, this nginx container starts, and I'm able to access the private port via the URL displayed in the Ports tab.

**However,** if I run `docker-compose restart`, the nginx container stops and starts again, but accessing the private port returns the following nginx error:
> 400 Bad Request
> The plain HTTP request was sent to HTTPS port
> openresty/1.15.8.1

The Ports tab shows that the forwarded port is still configured with HTTPS:
<img width="749" alt="image" src="https://user-images.githubusercontent.com/678890/160218894-30e59ae6-4f7f-4d5d-ba76-11b6781ef753.png">

I am able to resolve this issue by changing the forwarded port to HTTP and then back to HTTPS. It takes about thirty seconds, then I am once again able to successfully access the port via its displayed URL. 

This leads me to believe I either have a bad configuration, or there's a bug in the way that Codespaces reestablishes port forwards when stopping and restarting services (perhaps the auto forwarding system is somehow being triggered to determine whether or not to use HTTPS, then overrides the settings in devcontainer.json).
