### DISCUSSION TITLE
README-style descriptions for Github workflows

### DISCUSSION THREAD

**Discussion by lucaspopp0** [community/community#135683] [Actions]
### Select Topic Area

Product Feedback

### Body

Would love to be able to add readme-style markdown descriptions for GitHub workflows! This would be very useful for providing things like:
* Instructions for using the workflow
* External links, such as dashboards or a deployment process page

I imagine this would be fairly simple, such as:

```yaml
name: deploy-prod

description: |
  Deploy one or more services to production.

  Please follow the [deployment process](https://deployment.process) as you go.
```
