### DISCUSSION TITLE
How can you automate the process of labeling issues and pull requests in a GitHub repository based on the content or title of the submission using GitHub Actions?

### DISCUSSION THREAD

**Discussion by TestUser123123-svg** [community/community#135789] [Pull Requests] [answered]
### Select Topic Area

Question

### Body

How can you automate the process of labeling issues and pull requests in a GitHub repository based on the content or title of the submission using GitHub Actions?

**Comment by Gvolexe** [comment, marked as answer]
You can automate the process of labeling issues and pull requests in a GitHub repository using GitHub Actions by creating a workflow that triggers on the creation of issues or pull requests. Here’s how you can do it:

### Step 1: Create a New Workflow

1. In your GitHub repository, navigate to the `.github/workflows/` directory.
2. Create a new YAML file (e.g., `labeler.yml`).

### Step 2: Define the Workflow

Add the following content to the `labeler.yml` file:

```yaml
name: Auto Label Issues and Pull Requests

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Apply labels to issues and PRs
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: |
          # Conditions for issues
          - name: bug
            if: |
              github.event.issue.title.contains('bug') || github.event.issue.body.contains('bug')

          - name: enhancement
            if: |
              github.event.issue.title.contains('enhancement') || github.event.issue.body.contains('feature request')

          # Conditions for pull requests
          - name: documentation
            if: |
              github.event.pull_request.title.contains('docs') || github.event.pull_request.body.contains('documentation')

          - name: refactor
            if: |
              github.event.pull_request.title.contains('refactor') || github.event.pull_request.body.contains('refactor')
```

### Step 3: Customize the Conditions

- The workflow above uses the [`action-add-labels`](https://github.com/actions-ecosystem/action-add-labels) GitHub Action to automatically add labels to issues and pull requests based on conditions defined in the `labels` section.
- You can modify the conditions under each label to match specific keywords in the title or body of the issue/PR.

### Step 4: Commit and Push

Commit the `labeler.yml` file and push it to the `main` branch of your repository:

```bash
git add .github/workflows/labeler.yml
git commit -m "Add auto-labeling workflow"
git push origin main
```

### Step 5: Test the Workflow

Create a new issue or pull request in your repository with titles or bodies containing the keywords you specified (e.g., "bug" or "docs"). The workflow should automatically add the appropriate labels.

### Explanation

- **`on: issues` and `on: pull_request`**: The workflow triggers when an issue or pull request is opened or edited.
- **`github_token: ${{ secrets.GITHUB_TOKEN }}`**: This token provides the necessary permissions to interact with the GitHub API.
- **`labels` section**: Contains the conditions for applying labels based on the content of the issue or PR. You can add more labels and conditions as needed.

This setup automates the labeling process, helping maintain organization and clarity in your repository.

--- 

You can now easily copy and paste this content as needed!
