### DISCUSSION TITLE
Trouble Accessing Repository B Secrets When Triggered from Repository A

### DISCUSSION THREAD

**Discussion by tarunkant** [community/community#135798] [Actions]
### Select Topic Area

Question

### Body

**Pre-Requisite Info:**
I am triggering a called workflow (exists in Repository B) from the caller workflow (exists in Repository A). Both repos are in the same organization. There is a secret saved in Repository B, named `SECRET_CALLED`.

**Problem Statement:**
I want to use a secret saved in Repository B from the called workflow while I trigger the called workflow from the caller workflow.

_Caller Workflow_, this workflow exists in repoA:
```
name: Caller Testing

on:
  push:
    branches:
      - 'master'

jobs:
  caller-test:
    uses: org/repoB/.github/workflows/called-workflow.yml@master
```

_Called Workflow_, this workflow exists in repoB:
```
name: Called Testing
on:
  workflow_call:
  workflow_dispatch:

jobs:
  called-test:
    name: called-test
    runs-on: ubuntu-latest
    steps:   
      - name: process secret
        run: |
           echo "Secret: $SECRET_CALLED"
        env:
          SECRET_CALLED: ${{ secrets.SECRET_CALLED }}
```

When the caller workflow runs:
**Actual Output**: Secret: 
**Expected Output**: Secret: ***

So the thing is secret comes as empty string. I am not sure if this is expected behaviour or not. But can someone help me on how to use secrets saved in repo B from the called workflow?

P.S.: I can **not** change/modify the caller workflow but we have full access over called workflow and change things as per our need. Think of it as I am trying to modify the centralised workflow (i.e. called workflow) and many repos are calling it using caller workflow. So it's **not** really feasible to modify caller workflow from all the repos.
