### DISCUSSION TITLE
branches-ignore doesn't work; following official examples

### DISCUSSION THREAD

**Discussion by ton77v** [community/community#135974] [Actions]
### Select Topic Area

Bug

### Body

The goal is to exclude the workflow execution on specific branches. 

Trying to follow examples, for instance [this one](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-excluding-branches) like so:
```
name: CI Flow

on:
  pull_request:
    # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-excluding-branches
    branches-ignore:
      - 'mona/octocat'
      - 'releases/**-alpha'

jobs:
  set_up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v4
      - name: Hello World
        run: echo "Hello World from $(echo ${GITHUB_REF#refs/heads/})"
```
[source](https://github.com/ton77v/branches-ignore/blob/master/.github/workflows/main.yml)

The workflow is triggered as expected when you create a PR for any branch for instance "[new_branch](https://github.com/ton77v/branches-ignore/pull/1)"
- but when I create branches with names matching the `-ignore` the workflow is also triggered [for both of them](https://github.com/ton77v/branches-ignore/actions)

I've tried with and without wildcards and other syntax from the docs, but nothing works. Seems like a bug?
