### DISCUSSION TITLE
Plans for Schedule Based minRunners and maxRunners on scale sets

### DISCUSSION THREAD

**Discussion by pragmaticivan** [community/community#136008] [Actions]
### Select Topic Area

Product Feedback

### Body

Howdy! Any plans to support schedule based min and max runner on scale sets?

Looking for a way to:

(keep warm runners from 8am-6pm) but way less than that after 6pm until next day.

Ex:
```yml
schedules:
- timezone: Asia/Kolkata  # The acceptable values would be a value from the IANA Time Zone Database.
  start: 0 6 * * *        # At 6:00 AM
  end: 0 20 * * *         # At 8:00 PM
  minRunners: "10"
  maxRunners: "20"
```
