### DISCUSSION TITLE
Workflow is not loading my environment

### DISCUSSION THREAD

**Discussion by davidh16** [community/community#136278] [Actions] [answered]
### Select Topic Area

Question

### Body

I am trying to deploy my app to Google Cloud Run using Github actions. I have written a workflow for it but I realised that environment variables are not being loaded because they are not baked in my app. I have created an environment in repository settings and added some variables in it. I defined in the workflow that I want to use that specific environment and to confirm that my variables are available I printed out whole env in one stage. Variables are not there and I am not sure what am I doing wrong. Please help. 

```
jobs:
  deploy:
    environment: debug

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print all environment variables
        run: printenv
```

Just to be clear, I did not paste whole workflow code, except the part which is relevant to my question.

<img width="880" alt="Screenshot 2024-08-19 at 12 21 51" src="https://github.com/user-attachments/assets/d32c3f2e-924c-49ef-ad3e-cfbade0383f5">
