### DISCUSSION TITLE
When calling users.getAuthenticated() from actions/github-script@v7: HttpError: Resource not accessible by integration

### DISCUSSION THREAD

**Discussion by devurandom** [community/community#136379] [Actions]
### Select Topic Area

Question

### Body

In a GitHub Action that runs on Pull Requests, I am trying to get the user ID of the default user used by `actions/github-script` (the one that shows up as "[github-actions (bot)](https://github.com/apps/github-actions)"), so that I can then find PR comments made by my workflow using `actions/github-script`:
```yaml
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // https://octokit.github.io/rest.js/v21/#users-get-authenticated
            // https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#get-the-authenticated-user
            github.rest.users.getAuthenticated().then(({ id: authenticatedUserID }) => {
              // [...]
            });
```

However, the HTTP request is rejected:
```
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:9537:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 403,
  response: {
    url: 'https://api.github.com/user',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 20 Aug 2024 12:29:05 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'github.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'allows_permissionless_access=true',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '97C1:380A45:2D67DA:2DC9C7:66C48C11',
      'x-ratelimit-limit': '15000',
      'x-ratelimit-remaining': '14993',
      'x-ratelimit-reset': '1724158626',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '7',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/users/users#get-the-authenticated-user',
      status: '403'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/user',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/5.0.1 Node.js/20.13.1 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: [Agent],
      fetch: [Function: proxyFetch],
      hook: [Function: bound bound register]
    }
  }
}
Error: Unhandled error: HttpError: Resource not accessible by integration
```

How can I get the user ID of the default user used by `actions/github-script`?
