### DISCUSSION TITLE
GitHub Classroom: Feedback PRs and Autograding not set up in new assignments

### DISCUSSION THREAD

**Discussion by jdelfino** [community/community#136461] [GitHub Education] [answered]
### Hi everyone,

Hi Classroom team - I am gearing up for the start of the next semester, and I am running into problems with newly created assignments. When I create a new assignment, and test it out myself, I am not seeing any `.github` folder created, and I am also not seeing any Feedback PRs being created. I have selected the "Enable Feedback PR" checkboxes and also set up an automated test when configuring the assignment.

I remember when testing this earlier in the summer (May/June), I saw a `.github` folder added to the repo that configured some Actions, and I also saw the feedback branches and feedback PRs being created, but it doesn't seem to be working now.

Is this possibly a new bug related to the forking/template changes that came in June? Or is there some configuration I may need to adjust on my end?

**Comment by booleanchile** [comment]
Same here! No `.github` folder created
https://github.com/booleancl/python-tarea-1-recuperativa-booleanchile

Also experimented empty projects in students

**Comment by Thesirix** [comment]


**Reply by jdelfino** [reply]
This looks like a ChatGPT-generated response, and doesn't add to the discussion or make any actionable suggestions that haven't already be noted as tried earlier in the thread.

**Reply by Rudy2910** [reply]
> This looks like a ChatGPT-generated response, and doesn't add to the discussion or make any actionable suggestions that haven't already be noted as tried earlier in the thread.

**Comment by gpincheiraa** [comment]
Another example without `.github` repository

https://classroom.github.com/classrooms/21187813-soy-mas-g02-evaluaciones/assignments/python-tarea-1-recuperativa
![Screen Shot 2024-08-21 at 22 24 27](https://github.com/user-attachments/assets/b4aad3db-c10a-4adc-996e-e5e9b273e8bc)


https://github.com/booleancl/python-tarea-1-recuperativa-gpincheiraa
![Screen Shot 2024-08-21 at 22 24 35](https://github.com/user-attachments/assets/f3cbb7da-1623-4e36-9e02-d080ad02856a)

**Comment by TrentonWallis** [comment]
I am experiencing this same issue.

**Comment by dr-drews** [comment]
I am also seeing feedback PR issues. It does not create the pull requests; the assignment page's "Feedback" links all lead to 404s

**Comment by walters954** [comment]
I'm having the same issues and have not found a solution. I've recreated assignments and created new repos. 
Work around might be to create a feedback branch in your template.

**Comment by eveomett** [comment]
Well, I guess I'm not the only one.  I created an assignment for a class two weeks ago, pushed a solution, and the autograder worked fine on that solution.  But when I created an assignment this week and pushed a solution, the autograder is not creating a .github folder for that repo.  And it seems to not be creating a .github folder for any of my students' submissions on the assignment I created earlier.

**Comment by NuttKatyISD** [comment]
It seems inconsistent though. Class of 81 students, and probably about half of their repositories are missing the `.github` folder and the feedback PR and the other half are working correctly, autograding included. 

Would including the `.github/workflows/classroom.yml` file in the source repository work, and then not worry about setting up autograding when I build the assignment? I'm planning on trying that on the next set of labs but I don't know if that's going to trigger some other unseen issue.  The feedback PR is nice, but I can live without it. The autograding is pretty critical. 

ETA: Also noticed that the repositories that are not getting the `classroom.yml` file or the feedback PR are also not having their readme file updated with the link to open in Codespaces. Those that have the file also have the feedback PR and the updated readme with the link. Not sure if that's related, but it's at least data. 

Edit 2: I was able to add `classroom.yml` to the source repository and autograding worked, so that's at least a partial solution for now. 

The feedback PR still isn't showing up, and it seems consistent now; along with updates to the readme file with link to Codespaces.

I've tried a bunch of combinations trying to figure out if there was one setting causing it, and nothing worked. Tried every combination I could think of with autograding set in the UI, no autograding, protected folders on or off (I'm using `.*/**/*` as my protection string), Codespaces or no IDE, feedback PR or not.

**Comment by nineil-pitt** [comment]
Hi, the autograder of my classroom is not working.... i create another assignment, more simple and still not working 

My assignment : https://classroom.github.com/a/kV_RU2Lz
simple assignment : https://classroom.github.com/a/n6jGRMZJ

Some days ago, i tested and it was running ok.

**Comment by jrstanley** [comment]
I also have this same issue

**Comment by acorbin3** [comment]
I have the same issues. no autograder files and no pull request branch

**Comment by mlandis** [comment]
Same issue.

**Comment by mh-skjelvareid** [comment]
I've had the same issue. See also related discussion and issue:
https://github.com/orgs/community/discussions/132094 
https://github.com/github/gh-classroom/issues/78

**Comment by kdhindsa** [comment]
I am having the same issue as of yesterday.

**Comment by SimonSchillberg** [comment]
Same issues as of last week - the problem seems to be that the bot actions are not performed in any way. 

Bot commits missing completely from history. 

As work around you can create a feedback branch by hand from the initial commit - to do this:
1. go into student repositoy
2. open commits
3. click ... from first commit and select "Browse repository at this point"
4. click on the drop down with the commitID at the top left
5. type "feedback" 
6. click on "Create branch **feedback** from **commitID**"
7. click on Tab "Pull requests" and button "New pull request"
8. select your new branch "feedback"  for left side 
9. click "Create pull request"
10. give a title and create the PR

Proceed as normal from here.

Hope that helps.

Github Classrooms is a pain since the introduction of the new forking strategy and far from stable.

**Reply by hkaiser** [reply]
This will only work after at least one additional commit was made to the repository. Otherwise the PR can't be created as both branches are identical.

**Reply by chrissphinx** [reply]
this also seems to have the added problem of removing the "checkmark" from the classroom roster list in the classroom UI even when the student is passing automated tests

**Reply by studyvin** [reply]
If I'm understanding correctly, this needs to be done for each student individually?

**Comment by NuttKatyISD** [comment]
A bit more weirdness to add to this. Trying to help a student that was having issues committing from Codespaces and noticed this in their commit history. Source control tab shows 15 upstream updates that need to be fetched before they can push back. 

![image](https://github.com/user-attachments/assets/4ec99ffd-0f51-4992-9c93-be455e440eab)

Looking at any of these commits I see the following message.

![image](https://github.com/user-attachments/assets/99ef91f6-9b9e-466d-8ae0-f55b5ff3c9bc)

Not sure what the issue is, but pretty sure it's not something I can fix from my end.

**Comment by jijones-clayton-state** [comment]
I am also having the same problem and think I accidentally discovered a workaround, but it's taking a ton of effort.
I ended up creating an issue and just called it Feedback just to make it obvious what it was for the students. 

I was showing my husband what was going on, or so I thought. When I clicked on the Feedback link for a student I'd already reviewed, it went to the Issue instead of the 404 page.

It's not the greatest, but maybe it'll help in the long run once I add additional instructions/updates or they make changes and I need to leave additional feedback. At least I won't have to create a new issue every single time? That's what I'm telling myself for now.

**Comment by katbutler** [comment]
Just adding in to also say my students' repos are not getting the Feedback Pull Requests automatically created. Definitely a headache this semester already. My workaround is to have them create a new Review branch and manually create a Pull Request with their changes.

**Comment by pinventado** [comment]
Same issue. I don't use PRs but I use autograders. .github is not auto generated. I've even see repos that are completely empty ...

**Comment by egrace479** [comment]
Can someone share a sample autograde workflow? I don't mind adding it manually at this point. I set up the tests but got no `.github` either.

**Comment by chrissphinx** [comment]
Throwing my voice in here as well, not seeing any feedback pull requests created, although students do have autograding workflows added. I had added the workflow to the starting files repo so maybe that's a possible workaround for those in this thread that are missing tests? It's a bummer to not be able to use the assignment creation UI to add tests... c'mon GH Ed team what the hell is going on??

**Comment by liberty-bradleyd** [comment]
Same here. I created an assignment and configured it to run the autograder using a jUnit test case. Students are not getting .github folder and when I click on the Actions tab I am not showing anything close to what I am used to. That is, no log of the autograder - only a page full of Actions options.

**Comment by mikeryu** [comment]
Just wanted to second the issue here. Has anyone encountered GitHub Classroom bot being able to inject the `.github` directory (or anything else for that matter) at this point?

GitHub Classroom always had its _quirks_ (read: bugs) but nothing mission critical was broken. With the start of this semester, I was excited to check out the forked repo and other changes they've introduced, but ... I'm greeted with a completely broken system.

Feels bad.

**Comment by mikeryu** [comment]
**Update**: this worked. Please see my reply below.

Dropping an autograding configuration yml that was auto-generated by GitHub Classroom before it was broken (Spring 2024) for those of you (like me) who are attempting to manually create the yml to get autograding setup for the time being. I've used the same schema and so far things seem to be working. I'll test further and report back.

Below is the content of `.github/workflows/classroom.yml`:

```yml
name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: 'Environment Setup: Install and Set OpenJDK 21 as Default'
      id: environment-setup-install-and-set-openjdk-21-as-default
      uses: education/autograding-command-grader@v1
      with:
        test-name: 'Environment Setup: Install and Set OpenJDK 21 as Default'
        setup-command: sudo apt-get update && sudo apt-get install openjdk-21-jdk
          && echo "Installed OpenJDK 21"; sudo update-alternatives --set java "$(update-alternatives
          --list java | grep java-21)"; sudo update-alternatives --set javac "$(update-alternatives
          --list javac | grep java-21)";
        command: javac -version && java -version;
        timeout: 10
        max-score: 0
    - name: Run All Tests
      id: run-all-tests
      uses: education/autograding-command-grader@v1
      with:
        test-name: Run All Tests
        setup-command: cp run.sh temp.sh && sed 's/\r$//' temp.sh > run.sh && rm temp.sh;
          sed 's/openssl enc -d -aes-256-cbc -pbkdf2 -in CheckPointExam3Test.enc -out
          CheckPointExam3Test.java/openssl enc -d -aes-256-cbc -pbkdf2 -in CheckPointExam3Test.enc
          -out CheckPointExam3Test.java -pass pass:sunshine/' ./run.sh > ./temp.sh;
          cp temp.sh run.sh && rm temp.sh;
        command: "./run.sh;"
        timeout: 1
        max-score: 30
    - name: Check All TODO Comments Removed
      id: check-all-todo-comments-removed
      uses: education/autograding-io-grader@v1
      with:
        test-name: Check All TODO Comments Removed
        setup-command: pwd; echo "Searching for TODOs ...";
        command: grep -r "TODO" *.java > TODOs.grep.txt; cat ./TODOs.grep.txt; wc
          -l ./TODOs.grep.txt;
        input: ''
        expected-output: 0 ./TODOs.grep.txt
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        ENVIRONMENT-SETUP-INSTALL-AND-SET-OPENJDK-21-AS-DEFAULT_RESULTS: "${{steps.environment-setup-install-and-set-openjdk-21-as-default.outputs.result}}"
        RUN-ALL-TESTS_RESULTS: "${{steps.run-all-tests.outputs.result}}"
        CHECK-ALL-TODO-COMMENTS-REMOVED_RESULTS: "${{steps.check-all-todo-comments-removed.outputs.result}}"
      with:
        runners: environment-setup-install-and-set-openjdk-21-as-default,run-all-tests,check-all-todo-comments-removed
```

**Reply by mikeryu** [reply]
Update: this schema works.

FYI, there's a small bug where if you do not correctly configured the `env`s, the error message will (falsely) report that it's your `runners` attribute that is malformed with a message that reads:

> Error: The runners input must be a comma-separated list of strings.

Below is the yml file I manually created using the schema from above:

```yml
name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: 'Sample 00'
      id: sample-00
      uses: education/autograding-io-grader@v1
      with:
        test-name: 'Sample 00'
        setup-command: chmod 777 ./src/gwiyomi.*;
        command: ./src/gwiyomi.py ./data/sample_00.txt
        input: ''
        expected-output: D
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: 'Sample 01'
      id: sample-01
      uses: education/autograding-io-grader@v1
      with:
        test-name: 'Sample 01'
        setup-command: chmod 777 ./src/gwiyomi.*;
        command: ./src/gwiyomi.py ./data/sample_01.txt
        input: ''
        expected-output: C
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: 'Sample 02'
      id: sample-02
      uses: education/autograding-io-grader@v1
      with:
        test-name: 'Sample 02'
        setup-command: chmod 777 ./src/gwiyomi.*;
        command: ./src/gwiyomi.py ./data/sample_02.txt
        input: ''
        expected-output: C
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: 'Sample 03'
      id: sample-03
      uses: education/autograding-io-grader@v1
      with:
        test-name: 'Sample 03'
        setup-command: chmod 777 ./src/gwiyomi.*;
        command: ./src/gwiyomi.py ./data/sample_03.txt
        input: ''
        expected-output: C
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: 'Sample 04'
      id: sample-04
      uses: education/autograding-io-grader@v1
      with:
        test-name: 'Sample 04'
        setup-command: chmod 777 ./src/gwiyomi.*;
        command: ./src/gwiyomi.py ./data/sample_04.txt
        input: ''
        expected-output: C
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: 'Instructor Test Case Large'
      id: instructor-test-case-large
      uses: education/autograding-io-grader@v1
      with:
        test-name: 'Instructor Test Case Large'
        setup-command: chmod 777 ./src/gwiyomi.*; git clone https://github.com/7imeout/GradingResources.git;
        command: ./src/gwiyomi.py ./GradingResources/cs128/test_large.txt
        input: ''
        expected-output: 🌻
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: 'Instructor Test Case Oneoff'
      id: instructor-test-case-oneoff
      uses: education/autograding-io-grader@v1
      with:
        test-name: 'Instructor Test Case Oneoff'
        setup-command: chmod 777 ./src/gwiyomi.*;
        command: ./src/gwiyomi.py ./GradingResources/cs128/test_oneoff.txt
        input: ''
        expected-output: 다
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: 'Instructor Test Case Small'
      id: instructor-test-case-small
      uses: education/autograding-io-grader@v1
      with:
        test-name: 'Instructor Test Case Small'
        setup-command: chmod 777 ./src/gwiyomi.*;
        command: ./src/gwiyomi.py ./GradingResources/cs128/test_small.txt
        input: ''
        expected-output: α
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: Check All TODO Comments Removed
      id: check-all-todo-comments-removed
      uses: education/autograding-io-grader@v1
      with:
        test-name: Check All TODO Comments Removed
        setup-command: pwd; echo "Searching for TODOs ...";
        command: grep -r "TODO" *.py > TODOs.grep.txt; cat ./TODOs.grep.txt; wc
          -l ./TODOs.grep.txt;
        input: ''
        expected-output: 0 ./TODOs.grep.txt
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        SAMPLE-00_RESULTS: "${{steps.sample-00.outputs.result}}"
        SAMPLE-01_RESULTS: "${{steps.sample-01.outputs.result}}"
        SAMPLE-02_RESULTS: "${{steps.sample-02.outputs.result}}"
        SAMPLE-03_RESULTS: "${{steps.sample-03.outputs.result}}"
        SAMPLE-04_RESULTS: "${{steps.sample-04.outputs.result}}"
        INSTRUCTOR-TEST-CASE-LARGE_RESULTS: "${{steps.instructor-test-case-large.outputs.result}}"
        INSTRUCTOR-TEST-CASE-ONEOFF_RESULTS: "${{steps.instructor-test-case-oneoff.outputs.result}}"
        INSTRUCTOR-TEST-CASE-SMALL_RESULTS: "${{steps.instructor-test-case-small.outputs.result}}"
        CHECK-ALL-TODO-COMMENTS-REMOVED_RESULTS: "${{steps.check-all-todo-comments-removed.outputs.result}}"
      with:
        runners: sample-00,sample-01,sample-02,sample-03,sample-04,instructor-test-case-large,instructor-test-case-oneoff,instructor-test-case-small,check-all-todo-comments-removed
```
