### DISCUSSION TITLE
Test that spins up MySQL docker container randomly fails

### DISCUSSION THREAD

**Discussion by miparnisari** [community/community#136423] [Actions]
### Select Topic Area

Question

### Body

We have a github action that runs tests. This is the trimmed-down workflow:

```yaml
name: Pull Request
on:
  merge_group:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v3.5.2
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
          check-latest: true

      - id: go-cache-paths
        name: Get Go cache paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - name: Tests
        run: make test
```

The tests consist of both unit tests in Go and integration tests also in Go that spin up a Docker container.

The last step fails pretty consistently at the ~5 minute mark, at random, when running tests that depend on a MySQL container being alive. The MySQL container responds with `sql driver: bad connection`.

Sample failures:
- https://github.com/openfga/openfga/actions/runs/10476651492/job/29016020370?pr=1864#step:5:220
- https://github.com/openfga/openfga/actions/runs/10482732910/job/29034317414?pr=1855#step:5:219

This has been happening for the past year or so. And it's always the MySQL tests. Tests against Postgres run just fine.

Also, i'm not able to get this exact error locally. The only time I got it was when Docker crashed in my machine whilst in the middle of the test run.

I suspect there is something going on between Github actions, Docker, and MySQL.

Help!
