### DISCUSSION TITLE
Why can't my github app bypass branch protection

### DISCUSSION THREAD

**Discussion by JovanDjordjevic** [community/community#136531] [Actions] [answered]
### Select Topic Area

Question

### Body

I want to create a github app in my organization that will allow me to create an automatic versioning commit directly on the main branch after every pull request is merged to `main` branch.
I have a branch protection rule for the `main` branch which requires a pull request before merging, and I need to allow my github app to bypass this rule.

Here is the list of steps I did:
- create my repo and create a branch protection rule that requires the existance of a pull request
- create a new github app in my github organizaiton, and give every single available permission to the app (so this includes every possible write permission for repos etc). Here is the full list of these permissions as well:
```
Permissions
 Read access to codespaces metadata, metadata, organization events, and organization plan
 Read and write access to Dependabot alerts, actions, actions variables, administration, attestations api, checks, code, codespaces, codespaces lifecycle admin, codespaces secrets, commit statuses, custom organization roles, custom repository roles, dependabot secrets, deployments, discussions, environments, issues, members, merge queues, organization actions variables, organization administration, organization announcement banners, organization codespaces, organization codespaces secrets, organization codespaces settings, organization copilot seat management, organization dependabot secrets, organization hooks, organization personal access token requests, organization personal access tokens, organization secrets, organization self hosted runners, organization user blocking, packages, pages, pull requests, repository advisories, repository custom properties, repository hooks, secret scanning alerts, secrets, security events, team discussions, and workflows
 Admin access to organization custom properties, organization projects, and repository projects
```
- install the app in every repo in my organization
- create a private key for my application and export it as a organization level secret variable
- export the app id to a github variable as well
- add the app to the `"Allow specified actors to bypass required pull requests"` list for my pull request rule
- create a workflow that runs when a pull request is merged which has the following step for creating the commit on main (I am using the `peter-murray/workflow-application-token-action@v3` action to generate a short lived token with sufficient permissions to do this operation):
```
... prior workflow steps
      - name: Get token for gh app Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ vars.AUTOCOMMIT_APP_ID }}
          application_private_key: ${{ secrets.AUTOCOMMIT_APP_PRIVATE_KEY }}
      - name: Commit automatic version bump
        if: github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |-
          git config user.name 'autocommit app'
          git config user.email 'autocommit-app@placeholder.com'
          git add .
          git commit -m "chore: update version number (automated)"
          git push
... later workflow steps
```
- At this point I expect the commit to be created and pushed to main, but I get the following error:
```
Run git config user.name 'autocommit app'
[main 27e4f11] chore: update version number (automated)
 1 file changed, 1 insertion(+), 1 deletion(-)
remote: error: GH013: Repository rule violations found for refs/heads/main.        
remote: Review all repository rules at http://github.com/sandbox-org/org-sandbox-repo/rules?ref=refs%2Fheads%2Fmain        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
To https://github.com/sandbox-org/org-sandbox-repo
 ! [remote rejected] main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/sandbox-org/org-sandbox-repo'
```

If I completely turn of branch protection, the commit step works just fine, so I think the token creation is valid, but of course this is not a solution

**Comment by ferid333** [comment]
It looks like your GitHub app isn't able to bypass the branch protection rules even though you've set it up to do so. Here’s how you can troubleshoot and possibly fix this:

1. **Double-Check Permissions:**  
   Make sure your app has the right permissions, especially for writing code and managing repository settings. Also, confirm that it’s correctly added to the list of actors allowed to bypass the branch protection rules.

2. **Use GitHub's Built-in Token:**  
   Instead of creating a custom token, try using the `GITHUB_TOKEN` that GitHub Actions automatically provides. This token usually has the permissions needed to bypass branch protection if set up correctly. In your workflow file, make sure you allow `write` access to `contents`:

   ```yaml
   permissions:
     contents: write
   ```

3. **Review Branch Protection Settings:**  
   Go back and check the branch protection settings to ensure the app is set up to bypass the rules for making direct commits.

4. **Simplify and Test:**  
   Try a simpler workflow to see if the issue is with the overall setup. For example, create a minimal workflow that just commits a small change using the `GITHUB_TOKEN` and see if it works.

5. **Add Logs for Clarity:**  
   Include logging in your workflow to get more details about what's happening during the process, so you can pinpoint where things might be going wrong.

By going through these steps, you should be able to get your GitHub app working as expected, allowing it to commit directly to the main branch even with branch protection in place.

**Reply by JovanDjordjevic** [reply]
Regarding point 1: As stated in my question, during app creation I have given it all possible permissions which are also listed out in bullet point 2. In those permissions you can see all the relevant permissions 

Regarding point 2: I already tried that, however that token does not have permission to bypass branch protection even when I allow it `write` access to `contents`

Regarding point 3: I did that, and definitely have the app in the bypass list

**Reply by ferid333** [reply]
Here are a few additional steps to consider:

- **Double-Check App Installation:** Ensure the app is installed on the specific repository and that no additional restrictions are applied.

- **Test with a Different Workflow:** Create a simple workflow that just performs a minimal action (like creating a new file) to see if the problem persists.

- **GitHub Support:** If all settings seem correct but it still doesn’t work, consider reaching out to GitHub support for a detailed check. Sometimes there might be subtle issues or bugs that need direct assistance.

These steps might help you pinpoint any overlooked issues or clarify if there's a deeper problem with GitHub's handling of the app's permissions.

**Reply by JovanDjordjevic** [reply]
I double checked that my app is installed in every repo in my organization

I reused the exact same workflow and it works just fine when I completely disable branch protection, so I don't think the issue is in how I use the app  and token in the workflow

Unfortunately, as I am not using any paid github products, I cannot directly contact support, so that is why I am writing in this community forum

**Reply by ferid333** [reply]
Sorry for that

**Comment by danialtavakoli** [comment]
The issue occurs because branch protection rules require changes through a pull request, and your GitHub App can’t bypass this. To resolve this, use a Personal Access Token (PAT) with the `repo` scope instead of the GitHub App token. Add this PAT as a secret in your repository, and use it in your workflow to push changes directly to the `main` branch. This allows you to bypass the pull request requirement while keeping branch protection in place.

**Reply by JovanDjordjevic** [reply]
It was my understanding that apps can indeed bypass pull request requirements given that they can explicitly be added in the `Allow specified actors to bypass required pull requests` section of the branch protection rules.
Are you saying that this is a github bug?

Is there a way to do this without using a PAT? I specifically want some sort of bot to create these automatic commits. I do not want to have an actual user's PAT in order to avoid impersonation

**Reply by danialtavakoli** [reply]
Bro you're correct that GitHub Apps should be able to bypass pull request requirements if added to the "Allow specified actors to bypass required pull requests" section. However, the issue might be related to how the app token is being used in your workflow. Ensure the app is correctly listed in the bypass settings and that the token you're using has the necessary permissions. If this still doesn’t work, it could be a limitation or bug. Unfortunately, if the app token isn’t functioning as expected, the typical alternative is using a PAT, but I understand your concerns about avoiding impersonation. If the app bypass doesn't work, consider reaching out to GitHub support for further clarification or potential workarounds. If this response was helpful, feel free to mark it as the answer for support.

**Reply by JovanDjordjevic** [reply]
In my original question above I gave the exact workflow step I am using. Do you maybe see anything wrong with it?

**Reply by danialtavakoli** [reply]
The workflow step you provided looks generally correct. The issue might stem from how the token is generated or used. Double-check that the token generated by `peter-murray/workflow-application-token-action@v3` has the necessary permissions to bypass branch protection rules. Ensure that the app is correctly listed in the "Allow specified actors to bypass required pull requests" setting. If everything seems correct but it still doesn’t work, this might indicate a limitation or bug, and contacting GitHub support could provide more insight.

**Reply by JovanDjordjevic** [reply]
Just to make sure, when you say "double check that the generated token has the necessary permissions", apart from just running my workflow as described and seeing it fail are you saying that there is another way to do this? If so, please tell me how

**Reply by danialtavakoli** [reply]
To check the permissions of the generated token, you can inspect the token directly in your workflow by adding a step that outputs the token's permissions. Here’s how you can do it:

```yaml
- name: Inspect GitHub App token permissions
  run: |
    curl -H "Authorization: Bearer ${{ steps.get_workflow_token.outputs.token }}" \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/app
```

This command will return details about the app, including its permissions. You can check the response to ensure the token has the correct permissions for what you’re trying to do. If the token has the necessary permissions and it's still failing, it could indeed be a limitation or a bug, and contacting GitHub support might be necessary.

**Comment by SokandeSujal** [comment]
**Double-Check GitHub App Permissions:**
Ensure that the GitHub App is correctly installed with the necessary permissions. Verify that the app is listed in the "Allow specified actors to bypass required pull requests" section of your branch protection rule.

**Use a Pull Request Workflow:**
Instead of trying to push directly to the main branch, you can adjust the workflow to create a new branch for the version bump and then create a pull request to merge these changes into main. This approach adheres to the branch protection rules and ensures that changes are reviewed as required.

Here’s a modified example of the workflow:


```
name: Automatic Versioning

on:
  pull_request:
    types: [closed]

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a new branch for version bump
        run: |
          git checkout -b version-bump
          # Make your version bump changes here
          git add .
          git commit -m "chore: update version number (automated)"
          git push origin version-bump

      - name: Create Pull Request
        uses: repo-sync/pull-request-action@v2
        with:
          source_branch: version-bump
          destination_branch: main
          pr_title: "Automated Version Bump"
          pr_body: "This PR updates the version number automatically."
```
This workflow checks out the code, creates a new branch for the changes, pushes the branch, and then creates a pull request to merge those changes into main.

**Ensure Workflow Tokens Have Correct Permissions:**
Make sure that the token generated by the GitHub App has sufficient permissions for creating branches and pull requests.

By following these steps, you should be able to comply with the branch protection rules while automating the versioning process.

**Reply by JovanDjordjevic** [reply]
Thank you for your comment, but this does not work for me.
The versioning step in my case needs to already happen in the workflow I run when closing a pull request (how workflows are organized in my org's project is out of scope for this discussion, but TLDR we must not change them currently). Therefore, opening another pull request and merging it into main will just result in the same on-pr-closed workflow executing again in an infinite loop.
The only way to bypass this loop is to merge code directly to main as I described in my initial question. Also, the workflow you provided only automatically creates the pull request, it does not automatically merge it, which also goes against the completely automated process I need.

**Comment by ChristopherHX** [comment, marked as answer]
I think you are not using your GitHub App token, but push via the intergrated token.

```yaml
      - uses: actions/checkout@v4 # github.token is used here and confgured into git per https://github.com/actions/checkout?tab=readme-ov-file#usage
      #................................................
      - name: Get token for gh app Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ vars.AUTOCOMMIT_APP_ID }}
          application_private_key: ${{ secrets.AUTOCOMMIT_APP_PRIVATE_KEY }}
      # ................................................
      - name: Commit automatic version bump
        if: github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }} # <------ This is the problem, git won't use your token
        run: |-
          git config user.name 'autocommit app'
          git config user.email 'autocommit-app@placeholder.com'
          git add .
          git commit -m "chore: update version number (automated)"
          git push
```

To resolve this, make shure to use the token of your GitHub App.

```yaml
      #................................................
      - name: Get token for gh app Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ vars.AUTOCOMMIT_APP_ID }}
          application_private_key: ${{ secrets.AUTOCOMMIT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4 # use your app token here and confgured into git per https://github.com/actions/checkout?tab=readme-ov-file#usage
        with:
          token: ${{ steps.get_workflow_token.outputs.token }} 
      # ................................................
      - name: Commit automatic version bump
        if: github.event.pull_request.merged == true
        run: |-
          git config user.name 'autocommit app'
          git config user.email 'autocommit-app@placeholder.com'
          git add .
          git commit -m "chore: update version number (automated)"
          git push
```

_I noticed the presense of comments copied out of chatgpt in this discussion, which provided obviously non useful results_
**:warning: I have written this out of my memory**
