### DISCUSSION TITLE
any idea how to generate a snake contribs action for my readme

### DISCUSSION THREAD

**Discussion by ahlyel-amine** [community/community#136816] [Actions] [answered]
### Select Topic Area

Question

### Body

any idea how to generate a snake contribs action for my readme

**Comment by oumaima-aarabe** [comment, marked as answer]
To generate a "Snake" contribution graph for your README, you can use GitHub Actions to automatically update a "Snake" game image based on your contribution activity. This is a fun way to visually represent your GitHub activity. Here’s a step-by-step guide to set it up:

### 1. Create a GitHub Action Workflow

You’ll need a GitHub Action workflow that runs periodically and updates the "Snake" contribution graph. Here's how to set it up:

1. **Create a `.github/workflows` Directory**:
   Create a directory named `.github/workflows` in the root of your repository if it doesn’t already exist.

2. **Create a Workflow File**:
   Add a new file in this directory, e.g., `snake-contribs.yml`. This file will define the GitHub Action.

3. **Add the Workflow Configuration**:
   Use the following YAML configuration as a starting point. This example uses a third-party action to generate the Snake graph:

   ```yaml
   name: Generate Snake Contribution Graph

   on:
     schedule:
       - cron: '0 0 * * *' # Runs daily at midnight
     workflow_dispatch:

   jobs:
     update-snake:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Generate Snake Contribution Graph
           uses: platane/snk@v2
           with:
             github_user_name: your-github-username
             # Optional settings
             svg: true
             scale: 3

         - name: Commit and push Snake Contribution Graph
           uses: EndBug/add-and-commit@v9
           with:
             add: 'snake.svg'
             message: 'Update Snake contribution graph'
   ```

   Replace `your-github-username` with your actual GitHub username.

### 2. Add the Snake Contribution Graph to Your README

1. **Host the Image**:
   The GitHub Action will generate an image file (e.g., `snake.svg`). You need to host this image in your repository, typically in a directory like `assets/` or `images/`.

2. **Update Your README**:
   Add the following markdown to your `README.md` file to display the Snake graph:

   ```markdown
   ![Snake](https://github.com/your-username/your-repo-name/blob/main/assets/snake.svg)
   ```

   Replace `your-username` and `your-repo-name` with your GitHub username and repository name, and adjust the path to where the image is hosted in your repository.

### 3. Test the Workflow

- **Push Changes**: Push the changes to your repository. The GitHub Action should run according to the schedule or manually trigger it via the "Actions" tab on GitHub.
- **Verify the Image**: Check that the image is generated and updated correctly in your repository, and that it appears in your README.
