### DISCUSSION TITLE
`workflow_run` with branches filter not working

### DISCUSSION THREAD

**Discussion by arunstar** [community/community#136800] [Actions]
### Select Topic Area

Question

### Body

 I have two workflows, both are in `default` branch `main`

`calller.yml`
```yaml
name: caller

on:
  pull_request:

jobs:
  check-for-setup:
      runs-on: ubuntu-22.04
      name: Check if setup was changed??
      steps:
        - uses: actions/checkout@v4
          with: 
            fetch-depth: "2"
```

`docker.yml`
```yaml
name: Docker

on:
  workflow_run:
    workflows: ["caller"]
    branches: [main]
    types: [completed]


jobs:
  release_docker:
    name: Build docker images (API, Web)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
```
`calller.yml` completed running successfully but `workflow_run` event `Docker` is not triggering.

But when I remove the `branches` filter in `workflow_run` it's working. Not able to understand this behaviour can someone explain please?

**Comment by Carlos-Levi** [comment]
Hi @arunstar,

The issue you're experiencing with the `workflow_run` event and the `branches` filter not working as expected might be related to how GitHub Actions processes these events.

Here are some things to consider:

1. **Branches Context**: The `branches` filter in the `workflow_run` event is designed to trigger the workflow only when the original workflow (`caller.yml` in your case) was triggered by an event on the specified branch. Since both workflows are on the `main` branch, it should work, but the specific context of the original workflow’s triggering event matters.

2. **PR Context**: If `caller.yml` is triggered by a `pull_request` event, it's important to understand that `workflow_run` may interpret the branch context differently, particularly if the pull request is coming from a different branch or fork. The `branches: [main]` condition might not match because the pull request itself might not be from the `main` branch.

3. **Testing Without Branch Filter**: As you've noted, the workflow runs successfully without the `branches` filter. This suggests that the event triggering and workflow dependencies are set up correctly, but the branch filter is causing a mismatch.

4. **Possible Solution**:
    - Ensure that the `caller.yml` workflow is indeed triggering on the `main` branch as expected when the `pull_request` event occurs.
    - Consider using a different approach, such as adding a condition within the job itself to check the branch name, instead of using the `branches` filter in `workflow_run`. 

Here’s a quick example of how you might add a branch check inside the `Docker` workflow:

```yaml
on:
  workflow_run:
    workflows: ["caller"]
    types: [completed]

jobs:
  release_docker:
    if: github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
```

This way, the job will only run if the original workflow (`caller`) was triggered on the `main` branch, regardless of what branch the `workflow_run` event believes it is on.

Let me know if this helps clarify things!
