### DISCUSSION TITLE
How to use GitHub Actions to build using cmake?

### DISCUSSION THREAD

**Discussion by guest271314** [community/community#136801] [Actions] [answered]
### Select Topic Area

Question

### Body

How would I go about building `shermes` (https://github.com/facebook/hermes `static_h branch`) executable on GitHub using GitHub Actions?

**Comment by Carlos-Levi** [comment, marked as answer]
Hi!

To build `shermes` from the `static_h` branch using GitHub Actions, you can set up a workflow that checks out the repository, switches to the desired branch, and then runs the build process. Here's a basic example of how you might structure your `.github/workflows/build.yml` file:

```yaml
name: Build shermes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Switch to static_h branch
      run: git checkout static_h

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build shermes
      run: npm run build

    - name: Verify build
      run: npm test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: shermes-build
        path: path_to_build_artifacts/
```

This workflow will:

1. Checkout the `shermes` repository.
2. Switch to the `static_h` branch.
3. Set up Node.js (if needed).
4. Install any dependencies.
5. Run the build command.
6. Optionally, run tests and upload build artifacts.

You can adjust the `npm run build` command or any other steps to fit the specific build requirements of `shermes`. 

Let me know if you need further details or have any issues!
