### DISCUSSION TITLE
Add labels to workflow_dispatch runs

### DISCUSSION THREAD

**Discussion by daltonv** [community/community#13689] [Actions] [answered]
I have a workflow that launches some integration tests by me. To reduce code duplication it is one composite workflow that takes inputs to select the test suite.

To allow devs to run this test suite manually I create a workflow that runs with `workflow_dispatch` and takes the test suite to run as a parameter. All this works great but on the workflow runs screen it is very hard to tell which test suite was actually run without inspecting the logs of a workflow run.

I think we need to be able to set labels on the runs so that we can differentiate runs with different inputs. Something like:
```yaml
name: Single Integration Test Suite

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      test-suite:
        description: 'Test suite to run'
        default: 'helper'
        type: choice
        options:
        - stor
        - ble
        - prov
        - wifi
        - ota

labels:
  - ${{ github.event.inputs.test-suite }}

jobs:
```

Either that or the runs are automatically labeled with `workflow_dispatch` inputs.

They would then be displayed like this:
![image](https://user-images.githubusercontent.com/8504933/160384677-a5fa274e-b2b4-4391-b26e-be66ad9e0b62.png)
