### DISCUSSION TITLE
Newbie: Is it possible to make an action on a release when making a tag, and how?

### DISCUSSION THREAD

**Discussion by domichel** [community/community#136962] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi,
I have a C/C++ project using the autotools. It have an 'autogen.sh' script in the main directory of the project. It is used to generate the configure script and its associated files on an user's system.

When I make a tag in that repo, github make a release from it. Is it  possible, when making a tag, to have an action that will:
- Use a runner (if I understand it well, a runner is the way to go),
- Run uses: actions/checkout@v4
- Run ./autogen.sh
- Run ./configure
- Run 'make dist' (That will create an archive with the source code and the files generated by autogen.sh)
- Use that archive file for the release.

In [Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows), I found that it is no tag event, but a create event that run when a branch or a tag is created. But I don't need to run that action when a branch is created, and I don't want to create a release when a branch is created.

**Comment by ahmedosama07** [comment, marked as answer]
If I understood right. you can try this example and customize it with your needs

```
name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up autotools
        run: sudo apt-get install -y autoconf automake libtool

      - name: Run autogen.sh
        run: ./autogen.sh

      - name: Run configure
        run: ./configure

      - name: Run make dist to create the archive
        run: make dist

      - name: Get the generated archive name
        id: get_dist_name
        run: echo "ARCHIVE_NAME=$(ls *.tar.gz)" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          asset_content_type: application/gzip
````
