### DISCUSSION TITLE
Cannot get cross-build action to work

### DISCUSSION THREAD

**Discussion by lordofscripts** [community/community#136976] [Actions]
### Select Topic Area

Question

### Body

I am new to GitHub actions and I am the owner of several GO repositories. Up until now I had been using the default `go.yml` Go Build Action which simply builds the project in whichever OS/Platform GitHub uses. That works fine.

However, since I am working on multi-platform utilities, I wanted to **_add_** a cross-build action for my repository. So first question:

- Can I have two actions in my repository, for example `go.yml` and `go-cross-build.yml `? Or like in Highlander "_There shall be only ONE_" ?

As I mentioned, I had been trying to integrate the go-cross-build.yml action in my workflows so that it produces binaries for selected linux, Windows & MacOS platforms (I only have a Linux system). But that doesn't seem to be working.

For one thing, I even ran the YML file on a YAML checker and it is fine, but GitHub still complains it has an error that the online checkers don't seem to mind:

[Workflow file](https://github.com/lordofscripts/wipechromium/actions/runs/10582278675/workflow)

**Comment by ChristopherHX** [comment]
It could be that you need to fix indentation of "step 3: Copy", it's missing one space per line to align with previous steps

https://github.com/lordofscripts/wipechromium/actions/runs/10582278675/workflow#L33-L38

**Comment by lordofscripts** [comment]
I don't see anything wrong with this indentation:

```
# From github.com/marketplace/actions/go-cross-build v1.0.2
# workflow name
name: crossbuild

# on events
on:
  release:
    types:
      - created

# jobs
jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code inside the workspace directory of the runner
      - name: Checkout the repository
        uses: actions/checkout@v4
      # step 2: generate build files and dump inside the workspace directory of the runner
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: "linux/arm, linux/386, windows/386, darwin/amd64"
          package: "wipechromium"
          name: "wipechromium"
          compress: "true"
          dest: "distrib"
      # step 3: Copy build-artifacts in the GitHub release
      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         args: "./dist/*.tar.gz"

```

**Reply by ChristopherHX** [reply]
That looks good, but not this one I got from your GitHub Workflow with the error.

https://github.com/lordofscripts/wipechromium/blob/64e00460f0d49dd1564380f58d7c96a24b5c5436/.github/workflows/crossbuild.yml

```
# From github.com/marketplace/actions/go-cross-build v1.0.2
# workflow name
name: crossbuild

# on events
on:
  release:
    types:
      - created

# jobs
jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code inside the workspace directory of the runner
      - name: Checkout the repository
        uses: actions/checkout@v4

      # step 2: generate build files and dump inside the workspace directory of the runner
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: "linux/arm, linux/386, windows/386, darwin/amd64"
          package: "wipechromium"
          name: "wipechromium"
          compress: "true"
          dest: "distrib"

      # step 3: Copy build-artifacts in the GitHub release
     - name: Copy build-artifacts
       uses: skx/github-action-publish-binaries@master
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         args: "./dist/*.tar.gz"
```

Maybe your issue is resoved now if you create a new release
