### DISCUSSION TITLE
Publishing to Gradle Registry

### DISCUSSION THREAD

**Discussion by RithekShankar** [community/community#137002] [Actions]
### Select Topic Area

Question

### Body

I'm using this workflow to publish to gradle registry, but I keep getting an error code of 126 when I attempt to run the workflow. How do I fix this?
```
name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch:
     


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: ./AprilTagLocalization/gradlew
      env:
        USERNAME: ${{ github.USERNAME }}
        TOKEN: ${{ secrets.PUBLISH_KEY }}

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.USERNAME }}
        TOKEN: ${{ secrets.PUBLISH_KEY }}
```
