### DISCUSSION TITLE
Is it possible to set a specific branch in the workflow_dispatch without having to select it manually?

### DISCUSSION THREAD

**Discussion by diegotronics** [community/community#137079] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a GitHub Actions setup where I deploy by selecting the company I wish to deploy to. What I would like is for the 'Use workflow from' selector not to default to my 'develop' branch, but to another branch that I specify in the GitHub Actions .yml file. Can this be achieved without changing the default branch of my repository?

![image](https://github.com/user-attachments/assets/343ff7b8-3752-4e41-8ce0-84cde96c4ed5)

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by therealdwright** [comment, marked as answer]
The workflow dispatch dropdown will always default to the default branch, there's no way to set a non-default branch directly but you can put checks in place to fail the build if it runs from your default branch. e.g.

```YAML
name: Deploy web prod

on:
  workflow_dispatch:
  push:
    branches:
      - foo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/foo'  # only runs if on the 'foo' branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Deploy
        run: |
          # Deployment steps here

```
