### DISCUSSION TITLE
keeps getting error at last line no what what i did

### DISCUSSION THREAD

**Discussion by karenworld** [community/community#137282] [Actions]
### Select Topic Area

Question

### Body

I am trying out github action with springboot for storing the environment variable for google client-Id and secret.  However, no matter how i aligned the run - the last line, even checking with a dozen of yml editor to confirm everything is in place and there is no syntax, github action is still giving me last line at 23 has syntax error which left me helpless and not able to proceed with what i need to do to set up the workflow.  
Here's the yml file :

`name: Build and Deploy on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Build with Secrets
        run: |
          echo "Using Social Login Credentials"
          echo "LOGINCREDENTIALS=${{ secrets.LOGINCREDENTIALS }}"
          # Replace this with your actual build command
        env:
          SUPER_SECRET: ${{ secrets.LOGINCREDENTIALS }}
      - name: Build with Maven
        run: mvn clean install`
I did not use tab but space to make the run falls just under the run
Hope i can get some help here. Thanks !

**Comment by davevad93** [comment]
Hi @karenworld ,

The workflow overall syntax seems to be correct, I think the problem is due to incorrect indentation, try this:

```yml
name: Build and Deploy on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      
      - name: Build with Secrets
        run: |
          echo "Using Social Login Credentials"
          echo "LOGINCREDENTIALS=${{ secrets.LOGINCREDENTIALS }}"
        env:
          SUPER_SECRET: ${{ secrets.LOGINCREDENTIALS }}
          
      - name: Build with Maven
        run: mvn clean install

```
