### DISCUSSION TITLE
Empty matrix triggers step

### DISCUSSION THREAD

**Discussion by Joozty** [community/community#13756] [Actions]
Hi there, I was experimenting with matrix configuration and run into this strange behaviour. If you have a workflow that has boolean inputs and these inputs are later used and filtered in the matrix then even when none of the checkboxes is checked workflow is still run.

```yaml
name: Deployment

on:
    workflow_dispatch:
        inputs:
            alfa-release:
                description: 'Release on alfa'
                required: false
                type: boolean

            beta-release:
                description: 'Release on beta'
                required: false
                type: boolean

            prod-release:
                description: 'Release on prod'
                required: false
                type: boolean

jobs:
    deploy:
        strategy:
            fail-fast: false
            matrix:
                enviroment:
                    - ${{ github.event.inputs.alfa-release == 'true' && 'alfa' || false }}
                    - ${{ github.event.inputs.beta-release == 'true' && 'beta' || false }}
                    - ${{ github.event.inputs.prod-release == 'true' && 'production' || false }}
                exclude:
                    - enviroment: false

        name: Deploy - ${{ matrix.enviroment }}
        runs-on: ubuntu-latest
        env:
            DEPLOY_TARGET_ENV: ${{ matrix.enviroment }}
        steps:
            - name: Run step
              run: |
                 echo 'This step should not be run if matrix is empty, i.e. contains only false values'
```

I created test repo that can be found [here](https://github.com/Joozty/matrix-step).

if you[ trigger workflow and do not check any checkbox](https://github.com/Joozty/matrix-step/actions/runs/2058173394) then still "echo step" is run.
