### DISCUSSION TITLE
gitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job.

### DISCUSSION THREAD

**Discussion by Moyewole** [community/community#137761] [Actions]
### Select Topic Area

Question

### Body

I am trying to connect my github action to the google cloud database so that I can test new functionality. I am trying to use Direct workload Identity Federation and when I run that code I keep getting the isse that says GitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job. I am pretty sure I have all the proper permissions in my setting in GitHub but its possible I'm missing something. This is what my YML file looks like

name: tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ci_job:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Check date and hostname
        run: |
          date
          hostname
          
  Module_1_Test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Use Python 3.10

      - uses: 'google-github-actions/auth@v2' 
        with:
          workload_identity_provider: 'projects/NUMBER/locations/global/workloadIdentityPools/PROVIDER/providers/REPO'

Is there something that I'm missing or not putting in there?

**Comment by ChristopherHX** [comment]
oidc is disabled by design of `pull_request` (should actually only affect pr from forks, but idk the current state of this), otherwise someone who fork your repo could gain access to your google cloud account.

`pull_request_target` could be used to get access from pr's, but this checks out your default branch (changing this can be a security risc of someone injecting code via the checkout of the build system and extracting secrets) where this workflow must be located.

_For me is this behavior stop me from getting information about the used reusable workflow in pr's_

I assume this works for `push` events.

**Reply by Moyewole** [reply]
Okay I tried getting rid of the pull_request section but I still had the same issue. Is there something else that could possibly be causing this issue?

**Reply by ChristopherHX** [reply]
@Moyewole After a second look at your unformatted yaml copy. Your second job has no permission block to allow id-token only your ci job has


Add this to your Module_1_Test job or put it to the workflow root to apply for all jobs
```
permissions:
  contents: 'read'
  id-token: 'write'
```

**Comment by bruceharrison1984** [comment]
I'm seeing this same behavior on a PR for a local branch (not a fork). Seems I can only use `id-token` on a branch, but not a PR.

```yaml
name: Pre-release

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read
  contents: read

jobs:
  title:
    name: Semantic Title
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # 5.5.3
        with:
          types: |
            docs
            ci
            fix
            feat
            major
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tftest:
    name: Terraform Test
    runs-on: ubuntu-22.04
    needs: title
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          export_environment_variables: true
          service_account: github-runner@hc-XXX.iam.gserviceaccount.com
          workload_identity_provider: projects/XXX/locations/global/workloadIdentityPools/github/providers/github
```
