### DISCUSSION TITLE
Separate GitHub Release Versions Inside the Same Repository?

### DISCUSSION THREAD

**Discussion by CalebHenshaw** [community/community#137773] [Actions] [answered]
### Select Topic Area

Question

### Body

We have multiple repositories that each contain a helm chart and a docker image. We would like to use the GitHub releases feature to store and display versions of our artifacts (helm chart, docker image) as well as automatically incrementing the versions individually when updates are done to either the helm chart path or the docker image path. 

Is it possible to utilize GitHub releases to store multiple different version numbers that would be individually associated to either the helm chart or the docker image in that repository? 

Currently when we increment the version number for the helm chart to say 0.35.0 the docker image will also be incremented to that same version. The tag prefixes are the only way we can specify the different between the artifacts currently.

**Comment by ThisIs-Developer** [comment]
You can manage separate versions for Helm charts and Docker images using GitHub Releases by tagging them differently. For example, use `helm-chart-v0.35.0` for Helm and `docker-image-v1.2.3` for Docker images.

Here’s a quick GitHub Actions workflow example:

```yaml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Package Helm Chart
        run: |
          helm package ./charts/my-chart
          helm repo index ./charts --url https://my-helm-repo

      - name: Build Docker Image
        run: |
          docker build -t my-image:latest .
          docker tag my-image:latest my-image:${{ github.sha }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 'Release of version ${{ github.ref }}'
```

### Useful Links

- [GitHub Actions](https://docs.github.com/en/actions)
- [GitHub Releases](https://docs.github.com/en/releases)
- [Helm Versioning](https://helm.sh/docs/topics/versioning/)
- [Docker Versioning](https://docs.docker.com/develop/sdk/)

### If this helps, please mark it as the answer!😴

**Comment by CalebHenshaw** [comment, marked as answer]
I recently wrote an action that accomplishes our requirements. 

This is the workflow: 
```yaml
name: Semver Github Releaser
on:
  push:
    branches:
        - main
    paths:
      - service/image/**

permissions:
  id-token: write 
  contents: read 

defaults:
  run:
    shell: bash
    working-directory: /home/runner/work/repo-name/repo-name/service/image/

jobs:
  create_incremented_github_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup go-task / task / taskfile
        uses: rnorton5432/setup-task@v1

      - name: Create Incremented Github Release
        run: task create_incremented_github_release MINOR=true TOKEN=${{ secrets.GITHUB_TOKEN }} REPO=${{ github.event.repository.name }}
```

We use Taskfile, but the bash can be executed directly if you so prefer: 
```bash
version: '3'

tasks:
  increment_version: # Example: task increment_version MAJOR=True VERSION=1.2.4 # Output: 2.0.0
    vars:
      version: '{{ .VERSION }}'
      MAJOR: '{{ .MAJOR | default false }}'
      MINOR: '{{ .MINOR | default false }}'
      PATCH: '{{ .PATCH | default false }}'
    cmds:
      - |
        # Increment a version string using Semantic Versioning (SemVer) terminology.

        # Parse command line options and set strings to lowercase.
        major=$(echo {{ .MAJOR }} | tr '[:upper:]' '[:lower:]')
        minor=$(echo {{ .MINOR }} | tr '[:upper:]' '[:lower:]')
        patch=$(echo {{ .PATCH }} | tr '[:upper:]' '[:lower:]')
        version={{ .VERSION }}

        # Check if version string is provided.
        if [ -z "$version" ]; then
          echo "usage: task increment_version MAJOR=true|false MINOR=true|false PATCH=true|false VERSION=version"
          exit 1
        fi

        # Build array from version string.
        IFS='.' read -r major_version minor_version patch_version <<< "$version"

        # If version string has the wrong number of members, show usage message.
        if [ -z "$major_version" ] || [ -z "$minor_version" ] || [ -z "$patch_version" ]; then
          echo "usage: task increment_version MAJOR=true|false MINOR=true|false PATCH=true|false VERSION=version"
          exit 1
        fi

        # Increment version numbers as requested.
        if [ "$major" = true ]; then
          ((major_version++))
          minor_version=0
          patch_version=0
        fi

        if [ "$minor" = true ]; then
          ((minor_version++))
          patch_version=0
        fi

        if [ "$patch" = true ]; then
          ((patch_version++))
        fi

        echo "${major_version}.${minor_version}.${patch_version}" > bumped.txt

  get_latest_github_release:
    vars:
      TOKEN: '{{ .TOKEN }}'
      OWNER: '{{ .OWNER }}'
      REPO: '{{ .REPO  }}'
      TAG_PREFIX: '{{ .TAG_PREFIX }}'
    cmds:
    - |
      curl -s -H "Authorization: token {{ .TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/{{ .OWNER }}/{{ .REPO }}/releases" | \
      jq -r '.[] | select(.tag_name | startswith("{{ .TAG_PREFIX }}")) | .tag_name' | head -n 1 > latest.txt

  create_github_release:
    vars:
      TOKEN: '{{ .TOKEN }}'
      OWNER: '{{ .OWNER }}'
      REPO: '{{ .REPO  }}'
      TAG_PREFIX: '{{ .TAG_PREFIX }}'
      VERSION: '{{ .VERSION }}'
    cmds:
    - |
      echo "Creating release {{ .TAG_PREFIX }}{{ .VERSION }}"
      echo "https://api.github.com/repos/{{ .OWNER }}/{{ .REPO }}/releases"
      response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
        -H "Authorization: token {{ .TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        -d '{"tag_name": "{{ .TAG_PREFIX }}{{ .VERSION }}", "target_commitish": "main", "name": "Release {{ .TAG_PREFIX }}{{ .VERSION }}", "body": "{{ .TAG_PREFIX }}{{ .VERSION }}", "draft": false, "prerelease": false}' \
        "https://api.github.com/repos/{{ .OWNER }}/{{ .REPO }}/releases")
      if [ "$response" -eq 201 ]; then
        echo "Release was created (HTTP status 201)."
        exit 0
      else
        echo "Release was not created (HTTP status $response)."
      fi

  create_incremented_github_release: # Example: task create_incremented_github_release TOKEN=<token> REPO=repo-name MAJOR=true 
    vars:
      TOKEN: '{{ .TOKEN }}'
      REPO: '{{ .REPO  }}'
      TAG_PREFIX: '{{ .TAG_PREFIX | default "docker-image-v" }}' # change this to match your tag prefix i.e helm-chart-v, pypi-v, etc.
      MAJOR: '{{ .MAJOR | default false }}'
      MINOR: '{{ .MINOR | default false }}'
      PATCH: '{{ .PATCH | default false }}'
      OWNER: '{{ .OWNER | default "MyOwner" }}'
    cmds:
    - |
      task get_latest_github_release TOKEN={{ .TOKEN }} OWNER={{ .OWNER }} REPO={{ .REPO }} TAG_PREFIX={{ .TAG_PREFIX }}
      release=$(cat latest.txt) # Output: docker-image-v1.2.3
      version=$(echo "$release" | awk -F 'v' '{print $2}') # Output: 1.2.3 
      echo "Current version: $version"
      task increment_version MAJOR={{ .MAJOR }} MINOR={{ .MINOR }} PATCH={{ .PATCH }} VERSION=$version
      bumped=$(cat bumped.txt)
      echo "Incremented version: $bumped"
      task create_github_release TOKEN={{ .TOKEN }} TAG_PREFIX={{ .TAG_PREFIX }} VERSION=$(cat bumped.txt) OWNER={{ .OWNER }} REPO={{ .REPO }} VERSION=$bumped
      task clean

  clean:  
    cmds:
      - rm -f latest.txt bumped.txt
```

This action will be used per artifact inside a repo (if you have a large monorepo you can derive the service name by what path the change was detected in that triggered the action). This will allow tracking multiple separate semver version numbers using tags/releases and not require a file in the repo to track the versions. This action can be integrated with other actions to automatically determine whether a major, minor, or patch is to be incremented, as well as build automation to determine what the new version is to be pushed, without having to rely on external repositories like ECR.
