### DISCUSSION TITLE
Merge Queue: Github does not cancel workflows in merge queue even when they become irrelevant

### DISCUSSION THREAD

**Discussion by avx-ctan** [community/community#137976] [Actions]
### Select Topic Area

Question

### Body

We noticed a behavior of Github workflow handling that leads to hidden charges for users if they are not aware of it. In essense, Github does not cancel workflows in merge queues even when they become irrelevant. And as far as we can tell there is no documentation on this.

Here's an example:
Assume there are 3 PRs --- PR1, PR2 and PR3, and there is a workflow to run to get the required checks. When all PRs queued in the merge queue, 3 workflows started.
workflow 1 running on main + PR1
workflow 2 running on main + PR1 + PR2
workflow 3 running on main + PR1 + PR2 + PR3

Now, if we want to move PR3 to be at the head of the queue, 3 new workflows will start:
workflow 4 running on main + PR3
workflow 5 running on main + PR3 + PR1
workflow 6 running on main + PR3 + PR1 + PR2

When this happens, workflow 1, 2 and 3 should be cancelled automatically because the results are irrelevant at this point.
However, currently this is not done automatically. This not only leads to huge waste of money for the unawared users, but also slow down the merge velocity because of the extra runner concurrency consumed.

In addition, currently Github APIs do not support users implementing this behavior themselves. We have tried numerous ways of setting the concurrency group to get the behavior we'd like. However, no information in merge_queue event can be used and no feature in the expression evaluation is useful in this case.

Is there anyone else who is also facing this issue? We hope someone at Github can take a look and address this (or tell us what can we do to achieve the desired behavior).

**Comment by isker** [comment]
> However, no information in merge_queue event can be used and no feature in the expression evaluation is useful in this case.

I've faced this problem and have seemingly resolved it with this (remember, JSON is valid YAML 🌞):
```yaml
  "concurrency": {
    "group": "${{ github.workflow }}-${{ github.event.merge_group.head_commit.message }}",
    "cancel-in-progress": true
  }
```

This works because we use "squash" as the merge queue commit method, and configure squash to only use the PR title as the commit message.  In addition to the PR title, GitHub also adds the PR number to that generated commit message.  So, it is a roundabout way of getting the PR number into the concurrency group.

I couldn't find any documentation on length/valid character limitations in `group`, but things are not broken with PR titles in `group` as far as I can tell.

If you don't use those squash and commit message settings, I'm not sure whether this approach can work.

**Reply by arianvp** [reply]
Found out the hard way that the limit is 400 characters.

Also this only works if you requeue the PR after getting kicked out. it doesn't cancel if you don't requeue.

GitHub should fix this on their side.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by jenklu-copia** [comment]
Our org is hitting GH API rate limits due to the solution @nive-copia implemented based on https://github.com/orgs/community/discussions/66918#discussioncomment-7075736 . It would be great if the GitHub team could give some kind of indication as to whether this feature is on the roadmap or not. Cancelling expensive CI jobs feels like a pretty fundamental feature gap for a job runner framework!

**Reply by andrewdibiasio6** [reply]
> Cancelling expensive CI jobs feels like a pretty fundamental feature gap for a job runner framework!

Yeah this needs to be baked into Github's solution.

**Comment by arianvp** [comment]
Hey update! It's undocumented but you can actually handle the `merge_queue.destroyed` event!

```yaml
name: Build
on:
  pull_request:
  merge_group:
    types:
      - checks_requested
      - destroyed  # undocumented but works!
concurrency: 
  # github.ref will be the same for the checks_requested and destroyed event.
  # thus the destroyed event cancels out the checks_requested event
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    # skip the build if we are destroyed
    if: ${{ github.event.action != 'destroyed' }}
    steps:
      - your steps
```

This seems to handle cancelling redundant jobs perfectly.

**Comment by Aaron1011** [comment]
Here's another implementation using the `merge_queue.destroyed` event:

```yaml
name: Cancel stale merge queue workflows
on:
  merge_group:
    types:
      - destroyed

permissions:
  actions: write
  contents: read

jobs:
  cancel-workflows:
    name: Cancel Workflow Runs
    runs-on: ubuntu-latest
    if: github.event.reason != 'merged'
    steps:
      - name: Get Merge Queue Commit SHA
        id: get-sha
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Head SHA: ${{ github.sha }}"
          echo "Merge Group Reason: ${{ github.event.reason }}"

      - name: Cancel Workflow Runs by SHA
        run: |
          # Get all workflow runs for the specific SHA
          workflow_runs=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?head_sha=${{ github.sha }}")
          
          # Extract run IDs and cancel them (except current workflow)
          current_run_id="${{ github.run_id }}"
          echo "Current Run ID: $current_run_id"
          echo "$workflow_runs" | jq -r '.workflow_runs[] | select(.status != "completed") | .id' | while read -r run_id; do
            echo "Run ID: $run_id"
            if [ -n "$run_id" ] && [ "$run_id" != "$current_run_id" ]; then
              echo "Cancelling workflow run $run_id"
              curl -X POST -H "Authorization: Bearer ${{ github.token }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/cancel"
            fi
          done
 ```

This will cancel all workflows associated with the merge queue commit, across all workflows in the repository.
