### DISCUSSION TITLE
I am so dumb my media queries are not working. Can someone please help me (CSS)?

### DISCUSSION THREAD

**Discussion by ghost** [community/community#137989] [Programming Help]
### Body

```css
@media screen and (min-height:2157px){
    body{
        background-color:blue;
    }
}

.navbar li{
    color:black;
}  
.navbar a, p, h1, h2, h3{
    color:white;
    text-decoration:none;
 }
.comment-section button{
    border:1px solid black;
    color:white;
    background-color:green;
}

.online-section{
    margin-right:50%;
} 

.comment-section{
    margin-left:50%;
}

.comment-section-comment textarea{
    margin-left:25%;
}

.online-section h2{
    color:black;
}

.online-section h2{
    margin-left:50%;
}

.online-section a{
    margin-left:55%;
}
```

### Guidelines

- [X] I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.
