### DISCUSSION TITLE
I'm messing around with css grid to create some experimental ui design and i cant overlap an image over another image

### DISCUSSION THREAD

**Discussion by DevRenamon-Alder** [community/community#138063] [Programming Help] [answered]
### Body

I've tried using z-index: 1 grid-column: 1 grid-row: 1 and for some reason its not working, i even tried using position: absolute even tho its kinda inferior, but no dice. the images i want to overlap are the shades and the white bunny (terriermon) i know theres probably a better way to set up dressing up yr digimon once i learn javascript but for now its more about experimenting with grid rather than optimizing my character dressing programs. 

edit: oh right heres the repo https://github.com/DevRenamon-Alder/Test-PartneredDigimon

### Guidelines

- [X] I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.

**Comment by Shriharsh-Deshmukh** [comment]
To overlap the images, specifically the shades (`terriermon-shades.png`) over the white bunny (`terriermon-gaming.png`), you need to ensure that both images are in the same grid cell and that proper CSS rules are applied for layering.

### Key Adjustments:

1. **Adjust HTML Structure:**
   - Ensure that the `clothing` image (`terriermon-shades.png`) is inside the same container as the `terriermon-gaming.png` image. This ensures that both images are aligned and layered correctly.

2. **Update CSS:**
   - Add `position: absolute` to the `clothing` class and ensure its parent container is relatively positioned. This helps to layer the clothing over the base image.

### Modified HTML:
```html
<div class="digimon-4">
  <div class="digi-border-4">
    <img src="./img/terriermon-gaming.png">
    <img class="clothing" src="./img/terriermon-shades.png">
  </div><br>
  <p class="digi-label"><strong>Terriermon</strong></p>
</div>
```

### Updated CSS:
```css
.digi-border-4 {
    display: grid;
    position: relative; /* Ensures that absolute positioned children align to this container */
    width: 200px;
    height: 200px;
    margin-top: 20px;
    border: groove 5px hsl(250, 41%, 49%);
}

.digimon-4 img {
    width: 100%;
}

img.clothing {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 2; /* Ensures the clothing image appears on top of the base image */
    width: 100%; /* Adjust width as needed to fit the base image */
}
```

### Insights:
1. **Positioning:** Adding `position: relative` to `.digi-border-4` makes sure that `img.clothing` (shades) is positioned relative to this container, ensuring it overlays the base image (`terriermon-gaming.png`).

2. **z-index:** The `z-index: 2;` ensures that the clothing image is placed on top of the base image.

This approach should enable you to overlap the shades image over the white bunny correctly using CSS Grid in your experimental UI design.
