### DISCUSSION TITLE
Using exit code of previous step to decide the execution of the current step

### DISCUSSION THREAD

**Discussion by sathyashiva9** [community/community#138263] [Actions] [answered]
### Select Topic Area

Question

### Body

I have two steps
```
 
 - name: Run tests
              run: npm run test
 - name: Build app
              run: npm run build  
 
```
   
Now the test step is getting failed because of 134 exit code. And i am unable to perform build. I actually want to ignore that 134 exit code in the test step and continue. But if i use
   `
   continue-on-error: true
   `
   then it will perform the build always. But i only want to perform the build when the exit code of the test step is 134 or when the test step successfully finished.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by haggbart** [comment, marked as answer]
You can solve this by capturing and checking the test step's exit code before running the build:

```yaml
steps:
  - name: Run tests
    id: test
    continue-on-error: true
    run: |
      npm run test
      echo "exit_code=$?" >> $GITHUB_OUTPUT
      
  - name: Build app
    if: steps.test.outputs.exit_code == '0' || steps.test.outputs.exit_code == '134'
    run: npm run build
```

How this works:
1. We use `continue-on-error: true` so the workflow doesn't stop on test failure
2. We capture the exact exit code using `$?` and store it as a step output
3. The build step only runs when the exit code is either:
   - `0` (tests passed successfully) or 
   - `134` (your specific error code)
