### DISCUSSION TITLE
Template content cloned doesn't load styles

### DISCUSSION THREAD

**Discussion by unviere** [community/community#138200] [Programming Help]
### Body

Html template 
```html
 <template id="nav">
   
      <div class="sidebar-header">on this page</div>
      <div class="sidebar-scroll">
      <ul>
                <li><a class="navigate" href="#landing">landings page</a></li>
      <h1>also checkout</h1>
        <ul>
        <li><a class="navigate" href="#">games</a></li>
        <li><a class="navigate" href="settings.html">settings</a></li>
      </ul>
      </div>
      
      
    </template>
```

Je
```javascript
function cloneNavIntoNavmenu() {
  // Log to check if header has been updated
  console.log('Cloning navigation into scroller...');

  // Find the navigation element in the inserted content
  const navTemplate = document.querySelector('#nav'); // Adjust selector if necessary

  // Log to check if navTemplate is found
  console.log('Found navTemplate:', navTemplate);

  if (navTemplate) {
    // Clone the navigation content
    const navClone = document.importNode(navTemplate.content, true);

    // Find the target elements where the navigation should be cloned
    const navmenu = document.querySelectorAll('.scroller');

    // Log to check if navmenu is found
    console.log('Found scroller elements:', navmenu);

    if (navmenu.length > 0) {
      // Append the cloned content to each scroller element
      Array.from(navmenu).forEach(scroller => {
        scroller.appendChild(document.importNode(navClone, true));
      });
    } else {
      console.error('No elements with class "scroller" found.');
    }
  } else {
    console.error('Navigation element with ID "nav" not found in the fetched content.');
  }
}
```

Pls help me I need it load in the navbar for sub navigation 

I imported the style sheet 

This is how the inspector looks like 

![inspector](https://cdn.discordapp.com/attachments/1267459581421027328/1282773737871118500/image.png?ex=66e13c63&is=66dfeae3&hm=a9e67a84d5057427cef0dbb1022ffcf054054ebc6fec723f63f56adcb8b2af24&)

This worked on the styles with the old sidebar 

![Screenshot_20240909_193946_Chrome](https://github.com/user-attachments/assets/88dd4b24-8239-4825-8798-3355393aaa68)

But not on the new one

![Screenshot_20240909_194050_Spck Editor](https://github.com/user-attachments/assets/5f64190a-ed5f-48ae-b39f-6651436ca1f9)

### Guidelines

- [X] I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.

**Comment by unviere** [comment]
This the css it's correctly imported as off it worked on the old side bar
```css
.sidebar .sidebar-header{
  font-size: 22px;
  color: white;
  text-align: center;
  line-height: 70px;
  background: #0328ff;
  user-select: none;
  border-bottom: 1px solid rgba(255,255,255,1);
}
.sidebar .navigate {
  height: 100%;
  width: 100%;
  line-height: 65px;
  font-size: 20px;
  color: black;
  text-decoration: none;
  padding-left: 40px;
  box-sizing: border-box;
  background: transparent;
  font-weight: 600;
  padding: 5px 5px;
  border: none;
  
  
}

.sidebar .navigate:hover {
  
  border-bottom: 2px solid #0328ff;
  
}

.sidebar .tabs-navigation {
  height: 100%;
  width: 100%;
  line-height: 65px;
  font-size: 20px;
  color: black;
  text-decoration: none;
  padding-left: 40px;
  box-sizing: border-box;
  background: transparent;
  font-weight: 600;
  padding: 5px 5px;
  border: none;
  
  
}

.sidebar .tabs-navigation:hover {
  
  border-bottom: 2px solid #0328ff;
  
}

.sidebar .tabs-navigation.active {
  
  border-bottom: 2px solid #0328ff;
  
}

.sidebar h1{
  font-size: 22px;
  background: #0328ff;
  color: white;
  border-top: 1px solid rgba(255,255,255,1);
  border-bottom: 1px solid rgba(255,255,255,1);
}
```

Old sidebar
![Screenshot_20240909_193946_Chrome](https://github.com/user-attachments/assets/affc3f07-51e7-4d83-a026-b676798ff390)

New side bar 
![Screenshot_20240909_194050_Spck Editor](https://github.com/user-attachments/assets/d833b57c-c407-4b8e-ae8f-be844ac99d01)
