### DISCUSSION TITLE
markup: blockquote CSS has inconsistent margins

### DISCUSSION THREAD

**Discussion by westurner** [community/community#138296] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Bug

### Body

blockquote CSS in Markdown previews and renders has inconsistent margins.

I think this may be a regression, but I don't have any screenshots of it having been working.

```css
/* current CSS* /
.markdown-body p, .markdown-body blockquote, .markdown-body ul, .markdown-body ol, .markdown-body dl, .markdown-body table, .markdown-body pre, .markdown-body details {
  margin-top: 0;
  margin-bottom: var(--base-size-16);
}
```
![Screenshot from 2024-09-10 12-56-05](https://github.com/user-attachments/assets/d36523b0-73f4-4e71-ab21-7aab1e249a6e)

```css
/* suggested CSS */
.markdown-body p, .markdown-body blockquote, .markdown-body ul, .markdown-body ol, .markdown-body dl, .markdown-body table, .markdown-body pre, .markdown-body details {
  margin-top: var(--base-size-8);
  margin-bottom: var(--base-size-2);
}
```
![Screenshot from 2024-09-10 12-55-47](https://github.com/user-attachments/assets/0e9ab1ba-3a7f-4229-a7a0-b35d650af046)
