### DISCUSSION TITLE
Action on workflow_run: prevent from running on push event

### DISCUSSION THREAD

**Discussion by dpo** [community/community#138332] [Actions]
### Select Topic Area

Question

### Body

Hi. I have a `on: workflow_run` Action that runs upon completion of one of more other Actions and posts a comment in a pull request. It only makes sense for the `workflow_run` Action to run when the dependent Actions were run due to a pull request (even though the latter could also run on a push). I am looking for a way to restrict that action so it does not run on a push.

The yml looks as follows:

```yaml
name: add artifact links to pr
on:
  workflow_run:
    workflows: ["Build LaTeX document", "Build LaTeX diff document"]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    runs-on: [ubuntu-latest]
    if: github.event_name != 'push'
    steps:
      - name: add artifact links to pull request and related issues step
        uses: veitbjarsch/artifacts-url-comments@main
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: "Status:"
            format: "name"
            addTo: "pull"
```

I thought the line `if: github.event_name != 'push'` would do it, but the workflow runs anyways (and fails because... it's not a pull request). I tried moving the `if` just after the `uses:`, but that fails in the same way.

What is the correct way to corral such a workflow?

Thank you in advance!

**Comment by shania-g** [comment]
Upvote, I have similar scenario, but could not find any solution so far.

`test.yml`:
```yml
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```

`deploy.yml`:
```yml
name: Deploy

on:
  workflow_run:
    workflows: [ 'Test' ]
    types: [ completed ]
    branches: [ main ]
```

Deploy action is now ran when I open a pull request for merging into `main`, but that should not happen. The Deploy `workflow_run` should only be executed if a push to the `main` branch happened in the Test action that triggered this workflow.
