### DISCUSSION TITLE
Webhook to trigger Github Actions

### DISCUSSION THREAD

**Discussion by morrtz** [community/community#138466] [Apps, API and Webhooks]
### Select Topic Area

Question

### Body

Hi !

I have multiple repositories in my organization and I want to have single point of rules and logic of how pushes from these repositories are handled. I also need in occassion that central logic system to run multiple pushes together and allow them to work with a single validation process that includes multiple changes.
So the idea is to have a repo for central github actions that will hold a big part of the logic.

Our current difficulty is how to get pushes from these multiple repositories to trigger my github actions logic in my central repository.
- We have tried using webhooks through a Github App to try and trigger my github action in my central repo, but we couldn't find a way to make that work.
- We have also looked at adding github actions on all of our repos that will run a webhook directly to the github action in my central repo, but that would mean that I need to maintain all these github actions in all my repositories and all my branches.
- We have also looked at an external webserver that will recieve the webhook and perform my logic, this is possible but requires infrastructure from my side which I want to try and avoid.

Appriciate any input here, maybe we have overseen a solution that Github provides that can support us.

Thanks!

**Comment by lqduy** [comment]
It sounds like you're aiming for centralized GitHub Actions logic that can be triggered by pushes across multiple repositories, while minimizing maintenance efforts. There are a few approaches that could streamline this process:

### 1. **GitHub API + Centralized Action**
You could use the GitHub REST or GraphQL API to have your central repository listen for webhook events from other repositories. While GitHub Actions cannot directly listen to events from other repositories, this can be managed through the GitHub API. Here's a potential workflow:
   
1. **Webhook from Repositories**:
   Each repository would send a webhook to a central API or service (potentially GitHub App).
   
2. **Central Repository Trigger**:
   That API or service can then trigger a dispatch event to your central repository using the `repository_dispatch` event in GitHub Actions. This could centralize all pushes into one place.

   Example of how to trigger a workflow in your central repo using `repository_dispatch`:
   
   ```bash
   curl -X POST \
     -H "Authorization: token YOUR_TOKEN" \
     https://api.github.com/repos/org-name/central-repo/dispatches \
     -d '{"event_type": "trigger-from-repo", "client_payload": { "repository": "source-repo" }}'
   ```

   You could automate this through a webhook payload processor to route incoming pushes from different repositories.

### 2. **GitHub Actions in Repositories + Centralized Logic**
   Instead of a fully custom solution, each repository could have a lightweight GitHub Action to trigger the central repository’s logic. You could add a minimal action file to each repository like this:

   ```yaml
   name: Trigger Central Workflow
   on: [push]
   jobs:
     trigger-central-workflow:
       runs-on: ubuntu-latest
       steps:
         - name: Send repository dispatch
           run: |
             curl -X POST \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/org-name/central-repo/dispatches \
               -d '{"event_type": "repo-trigger", "client_payload": { "repository": "${{ github.repository }}" }}'
   ```

   This reduces the complexity in each repository while offloading most of the logic to the central repo. You wouldn't have to manage complex workflows across multiple repositories.

### 3. **GitHub Apps Approach**
   Since you’ve already explored GitHub Apps, consider using the GitHub Apps framework to directly trigger actions on your central repository via `repository_dispatch`. The GitHub App could receive webhook events, and then it could directly call the API to trigger your central GitHub Action.

### 4. **Monorepo Structure**
   If it's feasible for your organization, another approach could be to consolidate these repositories into a monorepo. This way, you'd only need one set of actions for all the projects and a single push would naturally trigger everything.

### 5. **GitHub Organization-Level Action**
   Although GitHub doesn't directly support organization-level actions that can trigger across multiple repositories without setup, you can create a **shared workflow** that’s reusable. This can be stored in a central location and referenced by all repositories, ensuring you don’t need to maintain separate logic for each one:

   In your central repository:

   ```yaml
   # .github/workflows/shared-workflow.yml
   name: Shared Workflow
   on:
     repository_dispatch:
   jobs:
     main:
       runs-on: ubuntu-latest
       steps:
         - run: echo "This is a shared workflow"
   ```

   In other repositories, reference it like this:

   ```yaml
   name: Trigger Central
   on: [push]
   jobs:
     call-shared-workflow:
       uses: org-name/central-repo/.github/workflows/shared-workflow.yml@main
   ```

---

These solutions centralize logic while reducing the need to maintain extensive actions across all repositories. If avoiding infrastructure setup is critical, using the GitHub API with `repository_dispatch` might be the best balance of centralization and simplicity.
