### DISCUSSION TITLE
Executing commands from a custom docker image

### DISCUSSION THREAD

**Discussion by bcochofel** [community/community#138595] [Actions]
### Select Topic Area

Question

### Body

Hi, I'm trying to run pre-commit hooks, for terraform code, using a custom docker image. But when I ran pre-commit check I get an error
![image](https://github.com/user-attachments/assets/18cd3cfe-f1e2-4e6e-9f2e-142d9126e198)

Here's my workflow file
```yaml
name: pre-commit
on: [pull_request]

permissions:
  contents: read # for checkout

jobs:
  check:
    name: Run pre-commit
    runs-on: ubuntu-latest
    container:
      image: bcochofel/terraform-tools:1.4.1
    steps:
      - uses: actions/checkout@v4
      - run: ls -al
      - run: pre-commit install
      - run: pre-commit run --all-files
```

Not sure what I'm doing wrong here since, from the ls -al command, the workdir is a the checkout folder, but still I get a pre-commit error "An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?"

Am I missing something?

Thanks,
Bruno
