### DISCUSSION TITLE
How to trigger an action based on branch AND tag

### DISCUSSION THREAD

**Discussion by royfrancis** [community/community#138559] [Actions]
### Select Topic Area

Question

### Body

I think this trigger

```
on:
  push:
    branches:
      - main
    tags:
      - '**'
```

means trigger action if pushed on main branch OR if a tag is pushed on any branch. At least that's what happens.

How do I change this to trigger action if pushed on main branch AND a tag is pushed? Or in other words trigger only if a tag is pushed on the main branch.
