### DISCUSSION TITLE
Logging current `working-directory` for run steps

### DISCUSSION THREAD

**Discussion by muzimuzhi** [community/community#138657] [Actions]
### Select Topic Area

Product Feedback

### Body

In job run log, for now only the current value of `shell` and `env` (if exist) properties are always shown for run steps (steps that have a `run` property).

It would be nice to also log current value of `working-directory`, as just like `shell`, `working-directory` is the only another property which may be set in multiple scopes:
- [`defaults.run.working-directory`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunworking-directory)
- [`jobs.<job_id>.defaults.run.working-directory`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunworking-directory)
- [`jobs.<job_id>.steps[*].working-directory`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory)

Example workflow
```yaml
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MY_VAR: GitHub
    steps:
      - run: mkdir -p temp
      - run: echo "hello world"
      - run: echo "hello $MY_VAR"
        working-directory: temp
```

Excerpted log (see this [real log](https://github.com/muzimuzhi/hello-github-actions/actions/runs/10865984315/job/30153023743) which should be available during Sep 15 to Dec 14, 2024),
```
▼ Run mkdir -p temp
  mkdir -p temp
  shell: /usr/bin/bash -e {0}
▼ Run echo "hello world"
  echo "hello world"
  shell: /usr/bin/bash -e {0}
hello world
▼ Run echo "hello $MY_VAR"
  echo "hello $MY_VAR"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    MY_VAR: world
hello GitHub
```
