### DISCUSSION TITLE
Alternative Authentication Methods for Accessing GitHub in Spring Cloud Config

### DISCUSSION THREAD

**Discussion by anmolsingh-kr** [community/community#138777] [Programming Help]
### Select Topic Area

Question

### Body

I'm exploring ways to access GitHub repositories in Spring Cloud Config without using personal access tokens. Here is my current configuration:

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abc/xyz
          clone-on-start: true
          search-paths: configs
          default-label: main

Could you suggest alternative authentication methods that I can use for GitHub in this setup?

**Comment by jgschmitz** [comment]
GitHub Apps offer a secure and granular method of repository access.
Instead of using personal tokens or SSH keys, you can use a GitHub App with its own permissions.

Here are the Steps:

Create a GitHub App:

Go to GitHub -> Settings -> Developer settings -> GitHub Apps.
Create a new GitHub App with repository permissions (Read access to repository contents).
After creation, you will get an App ID and can generate private keys.
Install the GitHub App on Your Repository:

Install the newly created GitHub App in the repository you want Spring Cloud Config to access.
Get an Access Token: GitHub Apps authenticate using JSON Web Tokens (JWT). You can create a script or a component in Spring to fetch an access token dynamically:

Generate a JWT from your GitHub App’s private key and App ID.
Exchange the JWT for an access token using GitHub’s REST API.
Use the Access Token in Spring Cloud Config: You can fetch and dynamically inject the access token into Spring Cloud Config’s properties. Here's a simplified outline:

```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abc/xyz.git
          clone-on-start: true
          search-paths: configs
          default-label: main
          username: x-access-token
          password: <your-github-app-access-token>
```

You can then automate token retrieval using Spring components or custom startup scripts to avoid manual handling of the token. Hope this helps!!
