### DISCUSSION TITLE
Manual Approval Consuming Github Action Minutes

### DISCUSSION THREAD

**Discussion by kyusungpark** [community/community#138857] [Actions]
### Select Topic Area

Question

### Body

Hi, I have a workflow setup where I require manual approval before deploying to dev/prod. I just noticed that while approval waiting, it was consuming github action minutes. How could I prevent this from happening?

My workflow process goes:
1. Checkout code, run test etc
2. On merge ask for approval to dev
3. Deploy to Dev
4. ask for Prod approval
5. Deploy to Prod

Checkout
```
name: Checkout

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-modules.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Check cache hit or miss
        run: |
          if [ "${{ steps.cache-modules.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit for node_modules";
          else
            echo "Cache miss for node_modules, running npm ci";
          fi
      - if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Lint and format
        run: |
          npm run format
          npm run lint

  tsc:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run tsc
        run: npm run tsc

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run tests
        run: npm test

  finish:
    runs-on: ubuntu-latest
    needs: [lint, test, tsc]
    outputs:
      status: ${{ steps.success.outputs.status }}
    steps:
      - name: Set successful status
        id: success
        run: echo "::set-output name=status::success"
```

Manual Approval for Dev
```
name: Approval for Development

on:
  workflow_run:
    workflows: ['Checkout']
    types:
      - completed
    branches: [main]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  manual_approval:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: 'Approval for Development Deployment Required'
          issue-body: Checkout was successful after merge to main. Please approve for Development deployment.
          exclude-workflow-initiator-as-approver: false

```

Deploy to Dev
```
name: Deploy to Development

on:
  workflow_run:
    workflows: ['Approval for Development'] # Name of the first workflow
    types:
      - completed
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  deploy_development:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm # Path to npm cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Create .env file for deployment
        run: |
          touch .env
          echo VITE_ENV=${{ secrets.VITE_ENV }} >> .env
          echo VITE_DEV_URL=${{ secrets.VITE_DEV_URL }} >> .env
          echo VITE_PROD_URL=${{ secrets.VITE_PROD_URL }} >> .env
          echo VITE_S3_URL=${{ secrets.VITE_S3_URL }} >> .env
          echo BUCKET_NAME=${{ secrets.BUCKET_NAME }} >> .env
          cat .env

      - name: Build React app
        run: npm run build

      - name: Deploy to AWS S3
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage dev --param="SharedBucketName=shared-dito"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

```

and pretty much the same thing for PROD

Any ideas to prevent this?

Thank you!
