### DISCUSSION TITLE
Workflow fails due to repository secret access problems on base repo

### DISCUSSION THREAD

**Discussion by MichaelMorami** [community/community#138900] [Actions]
### Select Topic Area

Question

### Body

I'm maintaining a public repository that's being contributed by multiple people through forks.
Any new work done is PR'd into my main repository once ready. Some of the contributors add their own workflows with regression tests as they add new frameworks, etc. These workflows often need a repository secret to be set in order to access some resources. Every contributor is then required to send me the key to set as a repository secret, and so we do before the PR is made.

The problem is that when the PR is running, the GH action is failing, claiming that they have no access to the secret. This is, of course, in spite of setting the secret well in advance. This causes failures in the PR's test every time.

We found a workaround where the PR is made to a temp branch and then PR'd internally to the main branch. When doing that, the workflow recognizes the secret and runs flawlessly. 

Is there a way to set my repository so that the incoming workflow just use my repository secret? this workaround creates unnecessary overhead i'd like to avoid

**Comment by barishaxxer** [comment]
Your not alone in facing this issue.this happens because of a a security feature in gitHub actions that halts secrets from being exposed in workflows triggered by pull requests from forks.
if you really need to run workflows check [this](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target)
 This triggers the workflow based on the main branch instead of the contributors fork

**Reply by MichaelMorami** [reply]
Thanks for the reply @barishaxxer.
I tried using this `pull_request_target`, but now the workflow doesn't run.
Reading the docs I suspect it's because the workflow is running from the base context, meaning that if my contributor is adding new regression tests that uses a framework i haven't used before on my main branch, and if they added new test files, the workflow will not work.
is this correct? If so that's a problem because more often than not, PRs add new files that needs to be run

**Reply by barishaxxer** [reply]
Yes youre correct! with using the pull_request_targe it runs workflows in the  base (target) branch, not the contributor's branch.if contributors have new files included  ,workflow wouldnt see those changes because it only operates with the files that exist in the base branch.To get around this issue, you can still use pull_request_target to have access to secrets, but you need to manually checkout the contributor's branch within the workflow using the actions/checkout 
```yaml
action.jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # checkout the PR branch rather than  the base branch
      - name: Check out the PR branch
        uses: actions/checkout@v3
        with:
          # checkout the code to contributors branch
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
```
> [!CAUTION]
> pull_request_target  makes repository secrets available even for code from forks, so be alert when running any untrusted code.

**Reply by MichaelMorami** [reply]
I see, thanks @barishaxxer !
In my case I only work with contributors I'm familiar with, so I'm not worried of any funny business they are going to add.
I'm now confused as to how it works; what's the context being used in regular PRs? i guess that should be the merge commit which is neither the base nor the contributor's. (in practice it's almost always the contributor's context).

Also, I'm sure I'm miss understanding something, please ELI5 - given that using pull_request_target is dangerous because it gives access to the base's secret, as all docs say, is it necessary for me to have this particular workflow and command in my base repo & branch when the PR comes in?
If so that's not really useful to me cause I need my contributor to add these extra tests in frameworks I know little about.
If not, I cant understand how the repo is allows (any) contributor to add this particular command which practically exposes the repo secret.

I suppose the first option is a requirement right?

**Reply by barishaxxer** [reply]
-  What context is used in regular PRs?
 Regular PRs (pull_request) run in the context of the merge commit (a temporary combination of the base branch and the contributor’s branch). However, no secrets are available in this context if the PR comes from a fork. 
 - Do you need to have the base repo/branch containing the workflow? 
 Yes, you should if you’re using pull_request_target. The workflow (i.e., the YAML file describing the CI process) must already exist in your base repo for the pull_request_target event to work. The command and workflow file must already be defined in the base repo because the workflow is triggered based on your base branch (but you’ll manually check out the contributor’s changes to test their code). 
 - Why would it expose secrets when contributors add commands? 
 With pull_request_target, if a contributor has modified the workflow or simply added commands that abuse secrets (i.e log or send secrets out), there are chances that secrets will be disclosed. When pull_request_target is utilized by one of the authors, GitHub assumes that the commands are being run on the base branch of the repository of the author. This explains the availability of secrets . What you are practically doing is allowing the contributor to run commands using the secrets in your repository.
 
 Since the contributors add new frameworks and tests that you may not fully understand, using pull_request_target will allow you to provide them with the secrets they need to run the tests properly.also oyu have mentioned you trust your contributors and not worried about malicious activites.you can safely use pull_request_target, knowing that the contributors are not going to abuse the ability to use secrets
**following  you trust your contributors and need to allow them to add tests and frameworks you're unfamiliar with i would stick with pull_request_target**

**Reply by MichaelMorami** [reply]
Amazing answer, thanks again @barishaxxer.
Last question here - in my case, the contributor is usually the one who creates the new yaml to run the new workflow that contains a test suite of certain component/section.
We find it useful to have a unique workflow for each component, this way the actions dashboard is easier to read (instead of having hundreds of tests, each component gets a workflow and each workflow is composed of multiple jobs.

My question is - how would you recommend us to go about using pull_request_target? perhaps a master yaml with pull_request_target which dispatches calls to every component workflow?
I never tried something like this. Will this work? can I just iterate over all the yaml files in the dir or will I have to specify each yaml file?
Will such an approach even work? because if so it sounds like it defiles the purpose of the permission barrier
Do you have any suggestions on how we can maintain our methodology and overcome this problem?
The main thing I'm trying to avoid is the need to manually create the yaml myself every time someone wants to push a contribution. If there's 1 master yaml that needs to be set-up once that's fine, but doing it manually every time is IMO no better than the work around I described in the OP.

**Reply by barishaxxer** [reply]
you wouldnt need to manually create YAML files for each contribution.Contributors can focus on their own specific workflows, and the master workflow handles the arrangement.s. unlike the pull_request event(triggers workflows based on the head branch of the pull reques)t, pull_request_target runs workflows based on the latest commit of the pull request’s base branch.having separate workflows for each is  a good practice to maintain clarity for CI/CD.
 something like this should work i guess:
# to identify which component workflows have been added or modified in the pull request
 ```yaml
jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_components: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      
      - name: Set changed components
        id: filter
        run: |
          CHANGES=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == .github/workflows/* ]]; then
              component=$(basename $file .yml)
              CHANGES="$CHANGES$component,"
            fi
          done
          echo "changes=${CHANGES%,}" >> $GITHUB_OUTPUT


```
# to run for each changed component:
1. checks out the repository
2. read the components workflow
3. Dispatche each job in the workflow 





```yaml

  dispatch_workflows:
    needs: check_changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ${{ fromJson(format('[{0}]', needs.check_changes.outputs.changed_components)) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run component workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            
            const workflowPath = `.github/workflows/${context.matrix.component}.yml`;
            if (!fs.existsSync(workflowPath)) {
              console.log(`Workflow file ${workflowPath} does not exist. Skipping.`);
              return;
            }
            
            const workflowContent = fs.readFileSync(workflowPath, 'utf8');
            const workflow = yaml.load(workflowContent);
            
            const jobs = workflow.jobs || {};
            for (const [jobId, jobConfig] of Object.entries(jobs)) {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflowPath,
                ref: context.payload.pull_request.head.ref,
                inputs: {
                  job: jobId,
                  sha: context.payload.pull_request.head.sha
                }
              });
            }
```
This will maintain seperate workflows and avoid manual intervention.Contributors can still add new component workflows without needing access to modify the master workflow
if your problem has been solved dont forget to mark the topic as answered and if you have any further questions dont hesitate to ping me whenever you want.glad i could help you <3
