### DISCUSSION TITLE
actions/upload-artifact@v3  is not able to find files

### DISCUSSION THREAD

**Discussion by smtripathi99** [community/community#139038] [Actions]
### Select Topic Area

Question

### Body

Hi,

I am trying to upload artifacts which is cucumber html reports generated via WDIO node using GitHub Actions upload-artifact.
It is not able to find the files to upload and gives :

**Warning: No files were found with the provided path: ./cucumber-report/cucumber-html/. No artifacts will be uploaded.**

How do I find if files are there or not ?

 ```
   - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: './cucumber-report/cucumber-html/'
```
[logs_46.zip](https://github.com/user-attachments/files/17050392/logs_46.zip)
