### DISCUSSION TITLE
Tag protection still work after deletion?

### DISCUSSION THREAD

**Discussion by ghost** [community/community#139084] [Actions]
### Select Topic Area

Question

### Body

I am trying to use [release-drafter](https://github.com/release-drafter/release-drafter) for auto release, and in one of my repo it worked perfectly with the [template](https://github.com/release-drafter/release-drafter?tab=readme-ov-file#usage) in the readme.

Here is what my script looks like.

```yml
jobs:
  release:
    permissions:
      # write permission is required to create a github release
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Tag And Note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: v1.0.0
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          version: ${{ env.RELEASE_TAG }}
          publish: true
```

The problem is, in another repo, I set the tag protection rule to protect with `v*` a year ago, and today I saw that the old tag protection rule is [deprecated on Aug. 30](https://docs.github.com/en/enterprise-server@3.14/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules) and have been migrated automatically under `Settings - Rules - Rulesets`.

And even if I have deleted ALL the rules under rulesets, the following error keeps occurring.

```py
{
      message: 'Validation Failed',
      errors: [
        {
          resource: 'Release',
          code: 'custom',
          field: 'pre_receive',
          message: "pre_receive protected tag 'v1.0.0' check failed:\n" +
            "  You're not authorized to create a tag"
        },
}
```

If I set `RELEASE_TAG: 1.0.0` rather than `RELEASE_TAG: v1.0.0`, everything works fine. So it seems the old protection rules is still working, and the auto migration just failed?

And I cannot reproduce the issue because I cannot travel back to Aug. 30 and set the old protection rule. And REST API will return 410 and will not work. According to the [blog](https://github.blog/changelog/2024-05-29-sunset-notice-tag-protections/), it is fully deprecated now.
