### DISCUSSION TITLE
How to setup GitHub Action to access NFS path in Linux?

### DISCUSSION THREAD

**Discussion by hyee08** [community/community#139168] [Actions]
I'm a beginner to setup GitHub Actions and facing issue to run the python unit test that contains the NFS path in linux. How to setup in GitHub actions workflow to access to NFS path? I also saw something related to GitHub runner, do I need to setup this as well?

This is my sample workflow:
```
name: Python Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increase the timeout to 30 minutes

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Mount NFS Path
      run: |
        sudo apt-get install -y nfs-common
        sudo mkdir -p /mnt/nfs
        sudo mount -t nfs 10.221.233.253:/nfs /mnt/nfs
      env:
        NFS_SERVER: 10.221.233.253
        NFS_PATH: /nfs

    - name: Run unit tests
      run: |
        python -m unittest discover -s dev -p 'unit_test.py'
```
