### DISCUSSION TITLE
Using secrets if they are not referenced inside of the action.yml

### DISCUSSION THREAD

**Discussion by onursagir** [community/community#139101] [Actions]
### Select Topic Area

Question

### Body

Is is possible to use repository secrets whilst not referring to them directly in the action file? For a specific use case I am storing docker build-args in a .env file 

```
# .github/configs/production/build-args/web.env
DATABASE_URL=${{ secrets.DATABASE_URL }}
```

which I try to dynamically load in pass to Docker, however the secrets are not being interpolated, is this even possible to achieve without manually referencing the secrets?

```
name: Build and push a Docker image
description: Builds and pushes a Docker image of the given app (inside apps/).
inputs:
  app:
    description: The name of the app to push, should match the folder name in apps/
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - id: build-args
      run: |
        # Read and format the .env file into Docker build arguments
        echo "BUILD_ARGS=$(cat ./.github/configs/production/build-args/${{ inputs.app }}.env | sed 's/^/--build-arg /' | tr '\n' ' ')" >> $GITHUB_ENV
      shell: bash
    - run: "${{ format(env.BUILD_ARGS) }}"
      shell: sh
```
