### DISCUSSION TITLE
How can I enforce a job to run on a Runner in the `Default` Runner Group

### DISCUSSION THREAD

**Discussion by AM1729** [community/community#139479] [Actions]
### Select Topic Area

Question

### Body

Hi we have a 2 runner groups: `Default` [ Which is there by Default ], and another Runner Group `GroupA`. Now, to specify a job which needs to run on GroupA, we use 

```
runs-on:
  group: GroupA
  labels: [ self-hosted, tag1, tag2 ]
```

Now, if a job is requesting:
```
runs-on: [self-hosted, tag1]
```

Now, the second job are getting placed on runners belonging to runner group `GroupA` based on tags, but ideally I would like to enforce the 2nd job to get placed on runner group `Default`

How can I achieve this ?

**Comment by Chanduporalla** [comment]
Hi! To ensure that the second job runs specifically on the Default runner group, you can modify the runs-on specification to explicitly reference the Default group. For example, you can use the following syntax:

yaml

runs-on:
  group: Default

This will enforce the job to be placed on the Default runner group regardless of the tags. If you still want to maintain tag usage, you can create a dedicated runner in the Default group with those tags to keep it flexible. Let me know if you need any further assistance!

**Comment by AM1729** [comment]
Hey @Chanduporalla  Thank you for your response. 
I tried it, however since we have multiple Organisations under the GitHub Enterprise, typically there is a `Default` Runner Group associated with each Organisation, and it fails saying that the backend found 2 groups with the same `Default` group name, and it asks to do this `Please use 'organization/' or 'enterprise/' prefix to target a single runner group.`

However, when I try to do group: `abcOrg/Default` it fails, saying that invalid group name. 
Not sure how to go about this.

**Comment by nebuk89** [comment]
Hey, could you share more of your workflow file I am struggling to reproduce this :)

**Comment by AM1729** [comment]
Hey @nebuk89, Thanks for your reply.

My workflow file looks something like this:

Workflow 1:
```
on:
  pull_request:
      branches:
          - dev
          
jobs:
  Build:
    runs-on:  [ self-hosted, tag1 ]
    steps:
       - shell: bash
           run: |
              go mod download
              go build cmd/main.go
```
Expectation is that Job defined in Workflow 1 would be placed on `Default` Runner Group, but sometimes it's getting placed on a Runner registered in a Different Runner Group based on Tags. For instance, the above job might get placed on a Runner in a non default runner group, having tags [ self-hosted, tag1, tag2 ].

Workflow 2:

```
on:
  pull_request:
      branches:
          - dev
          
jobs:
  Build:
    runs-on: 
       group: Default
       labels: [ self-hosted, tag1, tag2 ]
    steps:
       - shell: bash
           run: |
              go mod download
              go build cmd/main.go
```
This is producing:  `Your job could not be run as we found two runner groups with the name 'Default'. Please use 'organization/' or 'enterprise/' prefix to target a single runner group.`


Workflow 3:

```
on:
  pull_request:
      branches:
          - dev
          
jobs:
  Build:
    runs-on: 
       group: ABCOrg/Default
       labels: [ self-hosted, tag1, tag2 ]
     steps:
       - shell: bash
          run: |
             go mod download
             go build cmd/main.go
```

This is producing: `Invalid runs-on group name 'ABCOrg/Default'. Please use 'organization/' or 'enterprise/' prefix to target a single runner group.`

FYI: We are on enterprise and has multiple Orgs under the enterprise so the message that there are multiple Runner Group named `Default`  is found might make sense, since `Default` Runner Group are there basis org and not enterprise .
I also wanted to know if a Runner is requesting a group then GitHub checks for the entire Org or entire Enterprise.
