### DISCUSSION TITLE
Trigger deploy workflow upon both tag push and tests passed

### DISCUSSION THREAD

**Discussion by uwla** [community/community#139532] [Actions]
### Select Topic Area

Question

### Body

How can I trigger a deploy workflow only if both these two conditions are met:

1. A tag matching `v*.*.*` is pushed
2. The `.github/workflows/tests.yml` workflow succeeds

I could only figure out how to do this using `OR` condition (any of the two triggers the workflow) but I need `AND` condition, that is, both of them must be met.

The first condition I have found this workflow suggestion:

```yml
name: Deploy
on:
  push:
    tags:
      - "v*.*.*"
jobs:
    deploy:
```

For the second condition I have found this suggestion:

```yml
name: Deploy
on:
  workflow_run:
      workflows: [tests]
      branches: [master]
      types:
        - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy
      runs: echo "deploying"  
```

However using code snippet above will trigger the workflow if any of the conditions pass, even if the other one fails.

But how can I combine these two? Such that it requires both the tag push AND the success of the tests workflow.
