### DISCUSSION TITLE
Action not triggered on push triggered by git merge --ff-only or dispatch event

### DISCUSSION THREAD

**Discussion by punkbit** [community/community#139698] [Actions]
### Select Topic Area

Bug

### Body

Hi,

Seems that I found a bug, an action which listens to event `push` or a custom event fails to run for some reason. Why would this be?

Here's the job snippet:

```yaml
name: jobB
on:
  repository_dispatch:
    types: my-event-name
  workflow_dispatch:
  push:
    branches: [ main ]     
```

Here's the job snippets that is used to merge changes into the `main` branch:

```yaml
name: jobA
on:
  workflow_dispatch:
    inputs:
      ...
permissions:
  contents: write

jobs:
  merge-by-develop-hash:
    runs-on: ubuntu-latest
    steps:
      ...
    - name: Merge into main
      run: |
        if ! git checkout "${{ env.RELEASE_BRANCH }}"; then
          echo "👹 Oops! The develop branch wasn't found"
          
          exit 1
        fi

        if ! git merge --ff-only ${{ github.event.inputs.commitHash }}; then
          echo "👹 Oops! Failed to merge into main for some reason..."

          exit 1
        fi
        
        if ! git push origin "${{ env.RELEASE_BRANCH }}"; then
          echo "👹 Oops! Failed to push changes to the ${{ env.RELEASE_BRANCH }} branch for some reason..."

          exit 1
        fi

    - name: Dispatch Event
      env:
        PAT: ${{ secrets.PAT }}
        ENDPOINT: 'https://api.github.com/repos/<ORG>/<NAME>/dispatches'
        EVENT_NAME: 'my-event-name'
      run: |
        if ! curl -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $PAT" \
          --request POST \
          --data '{ "event_type": "$EVENT_NAME" }' $ENDPOINT; then
          echo "⚠️ Warning: Failed to dispatch $EVENT_NAME. Since this triggers the indexer listener, you should dispatch the action manually. If this issue persists, report it internally."
        fi
```

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by punkbit** [comment]
Just noticed that the EVENT_NAME variable is not being expanded. So, not actually triggering the event name it should list and trigger to.
Unfortunately, it doesn't trigger by EVENT_NAME and doesn't trigger by the git push event!


```yaml
    - name: Dispatch Event
      env:
        PAT: ${{ secrets.PAT }}
        ENDPOINT: 'https://api.github.com/repos/<ORG>/<NAME>/dispatches'
        EVENT_NAME: 'my-event-name'
      run: |
        if ! curl -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $PAT" \
          --request POST \
          --data \"{ \"event_type\": \"$EVENT_NAME\" }" $ENDPOINT; then
          echo "⚠️ Warning: Failed to dispatch $EVENT_NAME. Since this triggers the indexer listener, you should dispatch the action manually. If this issue persists, report it internally."
        fi
 ```
 
 Also, replaced the github author details, in case GitHub bot's the reason why the event not triggered. But same issue.
 
 ```yaml
     - name: Setup Git Config
      run: |
        git config --global user.email "ops@x.x"
        git config --global user.name "Xx"
```
