### DISCUSSION TITLE
Workflow doesn't run on push from actions bot

### DISCUSSION THREAD

**Discussion by rhee876527** [community/community#139656] [Actions] [answered]
### Select Topic Area

Question

### Body

The `make-docker` action doesn't get triggered after `sync` has successfully pushed commits to the repository.

sync: https://github.com/rhee876527/Jg56gBkSz7w/blob/1a374c37069bb473dadfa8466dbcb5425448d0bb/.github/workflows/sync.yml

make-docker: https://github.com/rhee876527/Jg56gBkSz7w/blob/1a374c37069bb473dadfa8466dbcb5425448d0bb/.github/workflows/make-docker.yml

I can make merge a commit from local or via github and it will work correctly. But the automated push by sync run by cron doesn't seem to trigger the make-docker action.

**Comment by rhee876527** [comment, marked as answer]
Pat token solved the issue.

```
steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
```
