### DISCUSSION TITLE
remote: git: 'lariat' is not a git command. See 'git --help'.

### DISCUSSION THREAD

**Discussion by punkbit** [community/community#139743] [Actions]
### Select Topic Area

Bug

### Body

For some reason started getting the error "remote: git: 'lariat' is not a git command. See 'git --help'.". Seems to be on github's side of things for some reason.

```yaml
on:
 push:
    branches:
      - main
      - develop
 pull_request:

jobs:
 code-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

```
