### DISCUSSION TITLE
Clarifying actions/setup-node

### DISCUSSION THREAD

**Discussion by aryzing** [community/community#139941] [Actions]
### Select Topic Area

Question

### Body

The `setup-node` actions has these two config options which seem ambiguous as to how they work:

```yaml
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, 
    # and set up auth to read in from env.NODE_AUTH_TOKEN.
    # Default: ''
    registry-url: ''

    # Optional scope for authenticating against scoped registries. 
    # Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
    # Default: ''
    scope: ''

    # Set always-auth option in npmrc file.
    # Default: ''
    always-auth: ''
```

- The `registry-url` seems to configure the registry for all packages, scoped or unscoped, is that the case?
- The description for `scope` says "Optional scope for authenticating against scoped registries", but the value is a string: how to configure different scopes against different registries?
- What is the `always-auth` options? It's [not documented](https://docs.npmjs.com/cli/v10/using-npm/config) as an option for npmrc
