### DISCUSSION TITLE
Prevent Independent Dependency Workflow from Running When Both Shared and Dependency Projects Change in GitHub Actions

### DISCUSSION THREAD

**Discussion by coffeeaddict10** [community/community#139903] [Actions]
### Select Topic Area

Question

### Body

I'm managing a GitHub repository with two separate projects:

```
shared-project01/
dependency-project01/
```
I have set up two GitHub Actions workflows:

**1. **Dependency-Build1 (dependency-build1.yml):****

**Triggers:**
`workflow_call`: Allows this workflow to be invoked by other workflows.
`push`: Triggers on changes to dependency-project01/** on the master branch.
**Behavior**:
Runs independently when only dependency-project01/** changes.
Should skip running independently when invoked via workflow_call from the shared workflow.

**2. Shared-Build01 (shared-build01.yml):**

**Triggers:**
`push`: Triggers on changes to shared-project01/** on the master branch.
**Behavior:**
Builds the shared project.
Calls `Dependency-Build1` and `Dependency-Build2` via workflow_call
**Current Workflow Files:**
```
name: Dependency-Build1

on:
  workflow_call:
    inputs:
      called_via_workflow_call:
        type: boolean
        default: true

  push:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      dependency_changed: ${{ steps.changes.outputs.dependency }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dependency:
              - 'dependency-project01/**'

  dependency-build:
    needs: check-changes
    if: needs.check-changes.outputs.dependency_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Dependency Project
        run: echo "Building Dependency Project..."
```

**Shared-Build01 Workflow** 
```
name: Shared-Build01

on:
  push:
    paths:
      - 'shared-project01/**'
    branches:
      - master

jobs:
  complete-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "The Shared-Build01 job has been completed successfully!"
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

  call_dependency_build1:
    needs: complete-job
    uses: ./.github/workflows/dependency-build1.yml
    with:
      called_via_workflow_call: true

  call_dependency_build2:
    needs: complete-job
    uses: ./.github/workflows/dependency-build2.yml
    with:
      called_via_workflow_call: true
```
**The Issue:**

When I push changes to both shared-project01/ and dependency-project01/, the following happens:

**Both Workflows Trigger:**
The independent `Dependency-Build1` workflow runs due to changes in `dependency-project01/**`.
The shared `Shared-Build01` workflow runs and calls `Dependency-Build1` via `workflow_call`.
**Unexpected Behavior:**
The independent `Dependency-Build1` workflow still runs, causing the dependency project to be built twice:
Independently due to the push to `dependency-project01/**`.
As part of the shared build via workflow_call.
**Desired Behavior:**

- When both projects have changes:
Do not run the independent `Dependency-Build1` workflow.
Only run the `dependency` build as part of the shared workflow via `workflow_call`.
- When only `dependency-project01/ `changes:
Run the independent `Dependency-Build1` workflow.
- When only `shared-project01/` changes:
Run the shared workflow and call the dependency build via `workflow_call`.

**What I've Tried:**

- Using `paths, paths-ignore` in `on.push` to specify project folders.
- Adding `if` conditions to skip builds based on input flags.
- Utilizing actions like `dorny/paths-filter@v3` to detect change.

**Question:** How can I configure my GitHub Actions workflows to prevent the independent `Dependency-Build1` workflow from running when both `shared-project01/` and `dependency-project01/` have changes, ensuring that the dependency build runs only as part of the `Shared-Build01` workflow via `workflow_call`? I want to maintain separate workflow files without mixing project paths in their triggers.

**Any guidance or example configurations to achieve this behavior would be greatly appreciated!**
