### DISCUSSION TITLE
Are there Enterprise/Org settings that would disallow a workflow from downloading an issue's attachment?

### DISCUSSION THREAD

**Discussion by vim-usds** [community/community#140208] [Actions]
### Select Topic Area

Question

### Body

I am an admin in a repo (let's call this _admin-repo_) that is part of a Enterprise/Org account. I do not have Maintainer access or any Enterprise/Org access.

I am trying to create a workflow that will trigger when an issue is created (on a certain label), parse the body, find the attachment URL (which is usually in the form `https://github.com/user-attachments/files/<some-hash-or-id>/<filename>`) and then curl the URL. 

I used a PAT with these set:
1. actions = R/W
2. content = R/W
3. issues = R/W
4. workflow = R/W

I believe the Action settings in the _admin-repo_ are the default ones, which seem most permissive. 

When trying to run this trivial example from the _admin-repo_, the curl results in a 404. Specifically:

```
curl: (22) The requested URL returned error: 404
Error downloading file
```

What's interesting is that when trying this same trivial example (see details) on a personal repo from my personal Github account, it works every time. I didn't need a PAT, a standard token works. This leads me to theorize that maybe the Org/Enterprise may have some permission/setting set that prevents the workflow (in the _admin-repo_ ) from downloading attachments.

<details>

```yaml

name: Get Attachment from issue

on:
  issues:
    types: [opened]

jobs:
  get-attachment-job:
    if: >
      contains(github.event.issue.labels.*.name, 'attachment') &&
      github.event.sender.login != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
    steps:
      - uses: actions/checkout@v4
      - name: Download file from issue
        id: download
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          echo "Issue number: $ISSUE_NUMBER"

          # Check GitHub API rate limits before proceeding
          echo "Checking GitHub API rate limits..."
          gh api rate_limit

          # Fetch issue data
          echo "Fetching issue data..."
          ISSUE_DATA=$(gh issue view $ISSUE_NUMBER --json number,title,body,comments)
          echo "Issue data:"
          echo "$ISSUE_DATA" | jq '.'

          # Try to find attachment in issue body
          ATTACHMENT_URL=$(echo "$ISSUE_DATA" | jq -r '.body' | grep -oP 'https://github.com/user-attachments/files/[^/]+/[^)]+\.xls' | head -n 1)

          if [ -z "$ATTACHMENT_URL" ]; then
            echo "No attachment found in issue body. Checking comments..."
            ATTACHMENT_URL=$(echo "$ISSUE_DATA" | jq -r '.comments[].body' | grep -oP 'https://github.com/user-attachments/files/[^/]+/[^)]+\.xls' | head -n 1)
          fi
          if [ -z "$ATTACHMENT_URL" ]; then
            echo "No attachment found in issue or comments."
            exit 1
          fi

          echo "Attachment URL: $ATTACHMENT_URL"

          # Download the attachment
          echo "Downloading attachment..."
          curl -L -o myAttachment.xlsx "$ATTACHMENT_URL"

          echo "Attachment downloaded successfully."

      - name: Upload attachment as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "My issue attachment"
          path: ./myAttachment.xlsx

```

</details>

My questions are:
1. Does this theory hold water?
2. If so, which settings/permissions at the Enterprise/Org level could be the ones responsible for preventing the workflow from downloading the attachment?

My next step is to create an Enterprise/Org account on my personal account and try and figure out if there is a setting that would make my personal repo unable to download attachments.

I'm trying to track down the Enterprise/Org person to chat with, but I'm sure if/when I do find them, I will have to tell them what permissions to enable (if this theory is true).

Thanks to all that read this!
