### DISCUSSION TITLE
GitHub Actions Trigger on branch creation

### DISCUSSION THREAD

**Discussion by neilmcalister** [community/community#140267] [Actions]
### Select Topic Area

Question

### Body

Hi - coming from an Azure DevOps background, I have a pipeline that can trigger a run when a branch is created - for example...

```
name: PRD-ReleaseStagesWorkflow

trigger:
  branches:
    include:
      - release/thing1/*
```     

I've tried this on GitHub actions and when a branch is created - for example 'release/thing1/1234abcd' this workflow will **NOT** trigger

```
name: PRD-ReleaseStagesWorkflow

on:
  push:
    branches:
    - release/thing1/*
```

I've seen many comments over the years about this - are we saying that this is impossible with GitHub actions? Even ChatGPT can't work this out.

Thanks in advance

Background - (if relevant): 
- Another GH Actions workflow creates the release branch in one of it's job steps.
