### DISCUSSION TITLE
Job-level annotations display doesn't follow the title property

### DISCUSSION THREAD

**Discussion by franky47** [community/community#140375] [Actions]
### Select Topic Area

Bug

## Problem:

The newly released job-level annotation display does not follow the annotation title, and instead uses the name of the step that emitted the annotation.

## Reproduction

Here's an example:
https://github.com/47ng/nuqs/actions/runs/11140588129/job/30959671533

<details><summary>Workflow file <em>(expand)</em> </summary>

```yaml
name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, labeled]
  pull_request_review:
    types: [submitted]

jobs:
  check-changes:
    name: Check for relevant changes to deploy
    if: |
      github.event.review.state == 'APPROVED' ||
      contains(github.event.pull_request.author_association, 'MEMBER')
    runs-on: ubuntu-latest
    outputs:
      enable: ${{ steps.check-for-changes.outputs.enable }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          fetch-depth: 2
      - name: Check for relevant changes
        id: check-for-changes
        run: |
          if git diff --quiet HEAD^ HEAD ./packages/nuqs; then
            echo "No changes to nuqs package, skipping preview deployment."
            echo "enable=false" >> $GITHUB_OUTPUT
          else
            echo "enable=true" >> $GITHUB_OUTPUT
          fi

  deploy-preview:
    name: Deploy to pkg.pr.new
    needs: check-changes
    if: needs.check-changes.outputs.enable == 'true' || contains(github.event.pull_request.labels.*.name, 'deploy:preview')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build --filter nuqs
      - name: Set package version
        run: |
          pnpm pkg set version=0.0.0-preview.${{ github.event.pull_request.head.sha }}
          echo "::notice title=Install (PR)::pnpm add https://pkg.pr.new/nuqs/${{ github.event.pull_request.number }}"
          echo "::notice title=Install (SHA)::pnpm add https://pkg.pr.new/nuqs/${{ github.event.pull_request.head.sha }}"
          echo "::notice title=Version::0.0.0-preview.${{ github.event.pull_request.head.sha }}"
        working-directory: packages/nuqs
      - name: Publish to pkg.pr.new
        run: pnpx pkg-pr-new publish --compact './packages/nuqs'
```

</details>

The annotations are emitted in the "Set package version" step of the `deploy-preview` job.

Here's what they look like in the run summary (correct display using each annotation's `title` property):
<img width="1029" alt="CleanShot 2024-10-02 at 10 48 03@2x" src="https://github.com/user-attachments/assets/7917b6f8-ab9a-42fc-8abd-2c566d02d237">

In contrast, here's what they look like on the `deploy-preview` job view, using the incorrect step name in place of the title:
<img width="1042" alt="CleanShot 2024-10-02 at 10 47 43@2x" src="https://github.com/user-attachments/assets/8714eb77-5c27-497a-9ee7-4c717a820d6f">

## Expected result

I'd expect the annotations on the job-level view to follow their title property, like on the summary step.

Thanks for this new view though, this is very handy!
