### DISCUSSION TITLE
How to cancel concurrent workflows except on `main` and `tags`

### DISCUSSION THREAD

**Discussion by cgraham-rs** [community/community#140416] [Actions]
### Select Topic Area

Question

### Body

I'm struggling with the necessary concurrency logic to accomplish what my team wants.

- We only trigger on push
- We want to cancel all concurrent runs EXCEPT those running against `main` and `tags`
- The existing logic below IS in fact canceling runs against `main`
- My current guess is that in some scenarios `github.ref` simply doesn't contain the value we think it does, though the group name includes `refs/heads/main` in the screenshot of the canceled workflow below (I'm assuming that's the group listed in the annotations)

<img width="716" alt="image" src="https://github.com/user-attachments/assets/4e459ee8-1b8e-4033-9285-c97302fe9c2a">

```
name: ci
on:
  push:
    branches:
      - '**'
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !(github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
```

**Comment by henry-AY** [comment]
I believe your issue lies in using the || operator instead of the &&, and not flipping the bool value of startsWith()

```
name: ci
on:
  push:
    branches:
      - '**'
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
```

Lmk if this works or not

**Reply by chrgraham** [reply]
I'll give your suggestion a try. 

The rabbit hole I went down earlier today is when merging a PR `github.ref` is `refs/pull/<PR_NUMBER>/merge` while `github.base_ref` is `refs/heads/main` which could explain why some of my workflows against `main` are being canceled.

**Reply by henry-AY** [reply]
Lmk if it works. 

Yeah, well hopefully this fixes the issue :)

**Comment by cgraham-rs** [comment]
We ended up adding a `pull_request` trigger and simply applying concurrency for `pull_request` only.  Much simpler logic. Less risk of bad logic impacting non-PR workflows.

```
on:
  push:
    branches:
      - 'main'
    tags:
      - v*
  pull_request:
    branches:
      - '**'

concurrency:
  # Only cancel in-progress runs for pull_request events, this prevents canceling workflows against main or tags
  # A pull_request will reuse the same group thus enabling cancelation, all others receive a unique run_id
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true
```
