### DISCUSSION TITLE
When will Github Actions allow `source` for (`bash`) environment modification?

### DISCUSSION THREAD

**Discussion by gblikas** [community/community#140536] [Actions]
### Select Topic Area

Question

### Body

**problem**

Using `source` in github actions/workflows doesn't work. I just spent over 3hrs debugging the following workflow snippet: 

<details>
<summary> Workflow using `source` </summary>

```yml     
name: build 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  foo:
  runs-on: [ubuntu-latest]
  steps: 
    - name: Install emsdk
    run: |
      git clone https://github.com/emscripten-core/emsdk.git
      cd emsdk
      git pull
      ./emsdk install latest
      ./emsdk activate latest
      source ./emsdk_env.sh
  ```

</details>

Reason why? `source` in this context doesn't properly export the variables underneath it. Also, for following steps, this doesn't work either: 

<details>
<summary> Workflow using `source` and `env:` </summary>

```yml     
name: build 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  foo:
  runs-on: [ubuntu-latest]
  steps: 
    - name: Install emsdk
    run: |
      git clone https://github.com/emscripten-core/emsdk.git
      cd emsdk
      git pull
      ./emsdk install latest
      ./emsdk activate latest
      source ./emsdk_env.sh
    env: 
      EMSDK: ${{ github.workspace }}/emsdk
  ```

</details>

**question**

So, my main question is, when will we be able to use `source` in a standard workflow? Follow up, is there a "hack" that gets this to work? (apologies if I missed it somewhere in the documentation) 

**Pros**
- workflows and build scripts everywhere rely on statements like `source` to make tooling available to the current context. 
- it drastically simplifies interactions with Github actions and doesn't require Github Actions specific knowledge, e.g. `GITHUB_ENV`.

**Cons**
- It might introduce security issues. But let them be introduced for individual workflows if some "unsafe" param is passed in and let the developers live the consequences.
