### DISCUSSION TITLE
Add ability to shift / indent highlighted block easily

### DISCUSSION THREAD

**Discussion by andyfeller** [community/community#14051] [Projects and Issues] [answered]
One of the things I use with Markdown lists on a daily basis is nesting or including additional content.  The markdown editor will preserve the current indention level as you're typing, however I often need to include large blocks of content from other places that require me to format it in an external tool just to align it properly.

It would be tremendously helpful if there was a way I could highlight a block and shift / indent it relative to nearby content.

## Example

1. line 1
1. line 2
1. line 3
1. line 4

If I wanted to drop a block into one of lines:

```yaml
on:
  pull_request:
    branches:    
      - 'releases/**'
      - '!releases/**-alpha'
```

I have to use vim for greater formatting control to shift content and possibly other formatting to result in:

1. line 1

   ```yaml
   on:
     pull_request:
       branches:    
         - 'releases/**'
         - '!releases/**-alpha'
   ```

1. line 2
1. line 3
1. line 4

And that is just 1 line item!

Would be super grateful for consideration! ✨
