### DISCUSSION TITLE
Why doesn't workflow_dispatch work in my workflow?

### DISCUSSION THREAD

**Discussion by MikhailSavenko** [community/community#140511] [Actions]
### Select Topic Area

Question

### Body

I use "on" workflow_dispatch, but not see button 'Run workflow'. Why? HELP please
![22Снимок экрана 2024-10-03 175547](https://github.com/user-attachments/assets/bb83b61a-56e3-4fcd-bab0-cbec6cbd9000)
![33Снимок экрана 2024-10-03 175628](https://github.com/user-attachments/assets/b7ac095c-a35d-4a63-83bf-02c2889c4203)

![Снимок экрана 2024-10-03 175408](https://github.com/user-attachments/assets/27e3e39d-b46f-4183-9363-a2219b285dad)

**Comment by FabDonRixos** [comment]
Hi there 

Default Branch: The "Run workflow" button will only appear for workflows that are on the default branch (e.g., main or master). If this workflow is on a different branch (e.g., develop), that could be why the button is not showing.

Alternatively you could try adding an input to the workflow_dispatch
just as an example: 
```
on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch
```

And a really important step is to check if you used Space for everything inside the yaml file, because yaml files don't like Tap as spacers.

Hope this Helps and im wishing you best luck 🍀

**Comment by jlaughton101** [comment]
Is the ability to have "workflow_dispatch:" alone (so I get a manual run workflow dialog box on the GUI) ever going to be added to branches ?
Since we develop by creating a release branch (which in not main or master) , the only way we can get it to build "manually" is to use 

```
on:
  workflow_dispatch:
  push:
     branches:
       - '**'
```

Then we have a "dummy" file that we change and commit to get a build to run.
