### DISCUSSION TITLE
Organization-scoped PAT with Workflow permissions not working

### DISCUSSION THREAD

**Discussion by reteps** [community/community#140561] [Actions] [answered]
### Select Topic Area

Question

### Body

I cannot get past this error:

```
Run git remote set-url origin "https://***@github.com/sigpwny/websites.git/"
[main 6b16eff] chore: update workflow schedule
 1 file changed, 124 insertions(+)
 create mode 100644 .github/workflows/scheduled-pings.yml
To https://github.com/sigpwny/websites.git/
 ! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/scheduled-pings.yml` without `workflows` permission)
```

See also: https://github.com/stefanzweifel/git-auto-commit-action/issues/347

I have created a variety of PAT types, none of them work:

![image](https://github.com/user-attachments/assets/a104d23c-4a79-4fcc-b3f0-de0a8a63f32c)
![image](https://github.com/user-attachments/assets/b6333b1a-b800-41ce-a308-db5517aaf85b)

My settings allow for using a PAT in my organization:

![image](https://github.com/user-attachments/assets/6c97215c-fa09-4909-ae4a-5471f5a055ce)
![image](https://github.com/user-attachments/assets/4a1214be-c3dc-4f28-b488-9f9a84796d43)

I setup the PAT in my repo:
![image](https://github.com/user-attachments/assets/60887b0e-636c-4317-86b7-89f294f5998e)

I use the PAT when I checkout the repo:

```yaml
jobs:
  deploy:
    name: Deploy (sigpwny.com)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          submodules: true
          fetch-depth: 0
 ```
 
 I then try many different ways of forcing it to use the PAT:
 
 ```yaml
        - name: Save scheduled discord pings
        if: github.ref_name == github.event.repository.default_branch
        env:
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
        run: |
          git remote set-url origin "https://${{ secrets.WORKFLOW_PAT }}@github.com/sigpwny/websites.git/"
          git config user.name sigpwny-uiuc
          git config user.email sigpwny@gmail.com
          git add .github
          git commit -m "chore: update workflow schedule"
          git push origin main
 ```
 
 What is going on?
