### DISCUSSION TITLE
CMake Doesn't Detect Ninja or Ninja-Build

### DISCUSSION THREAD

**Discussion by gblikas** [community/community#140526] [Actions]
### Select Topic Area

Question

### Body

**problem**

No matter how I install `ninja`, `cmake` fails the `CMAKE_MAKE_PROGRAM` check.

**explination**

No matter how I setup my github action, I cannot seem to get CMake and Ninja to connect. I've tried many configurations, from manually installing the programs through `apt`, to download binaries, `echo "var" >> $GITHUB_ENV`, `source`ing, etc.. What I've currently landed on is a workflow that looks like this: 

```yml
name: build

on:
  push:
    branches: [ staging, main ]
  pull_request:
      branches: [ staging, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#	 using built-in features has the same outcome
#   - uses: seanmiddleditch/gha-setup-ninja@master
#   - uses: mymindstorm/setup-emsdk@v14
#   - uses: lukka/get-cmake@latest
#   - uses: lukka/run-vcpkg@v11

    - name: update pacakges
      run: sudo apt-get update
    - name: Install ninja
      run: sudo apt install ninja-build -y
    - name: Install buid-essential
      run: sudo apt install build-essential -y

    - name: Add ninja to path 
      run: echo "PATH=/usr/bin/ninja:$PATH" >> $GITHUB_ENV

    - name: Build wasm modules
      run: |
        cd my_proj
        ninja --version
        cmake --workflow --preset workflow-release-wasm-ninja
        cd ..
```

In which case I get the following output every time: 

```bash
// other output truncated for viewing 
-- Found external ninja('1.12.1').
-- Configuring wasm32-emscripten
// other output truncated for viewing 
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
```

**additional context**

I understand that it's generally the case that the error `CMAKE_MAKE_PROGRAM is not set` is usually due to the make program not being on path, however, I've verified many times that it's on path. I understand that my build pipeline is a bit complex, using both `vcpkg` and `emscripten`. However, I've check several times that my Toolchain pathing was correct. 

- cmake version is 3.30.X
- ninja is 1.12.1
