### DISCUSSION TITLE
GitHub Action to always run when merging into `main` except when merging from specific branches

### DISCUSSION THREAD

**Discussion by pfulton** [community/community#140612] [Actions]
### Select Topic Area

Question

### Body

Hi there. I have a job that I'd like to selectively run, and I'm looking for guidance on how to achieve the following:
* Upon merging a branch into `main`, the job should _always_ run, **except** for when the branch has a specific name/pattern.

For example: I expect the job to run for any merge into `main`, but my repo has Dependabot enabled, and I do _not_ want the job to run when Dependabot-created branches are merged into `main` (the branch naming convention would look something like `dependabot/**`).

Thanks!

**Comment by FabDonRixos** [comment]
You can achieve this by using conditional logic in your CI configuration file. Here's an example:
```
on:
  push:
    branches:
      - main
jobs:
  selective_job:
    if: "!startsWith(github.ref, 'refs/heads/dependabot/')"
    runs-on: ubuntu-latest
    steps:
      # Your job steps here
```

This ensures the job runs on merges to main but skips it for branches starting with dependabot/.

I Hope I undestood you question right and good luck 🍀.

**Comment by pfulton** [comment]
@FabDonRixos thanks for the reply!

I tried your suggestion, and it didn't work like I expected.

I did, however, have success by using the `pull_request: closed` event and checking against the `github.head_ref` name, which surfaced the name of the branch being merged _into_ the target branch.

Here is a generic example of the code:
```yaml
name: Testing

on:
  # the closed event type gives us the `head_ref` (the name of the branch being merged into `main`)
  pull_request:
    types:
      - closed
    # for PRs merging into these branches
    branches:
      - main

jobs:
  log:
    # if the branch being merged is a `dependabot` branch or a `feature1` branch, skip everything else
    if: ${{!startsWith(github.head_ref, 'dependabot') && !startsWith(github.head_ref, 'feature1') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of the head_ref is ${{ github.head_ref }}."
```
