### DISCUSSION TITLE
Releases Not Getting Triggered

### DISCUSSION THREAD

**Discussion by imdaisyadams** [community/community#140617] [Actions]
### Select Topic Area

Bug

### Body

We've been experiencing an issue in our release process, where the release workflow does not get triggered properly, even though our PRs meet the requirements. 

When a PR to `main` gets `closed` & it ends with 'pre-release' it should trigger `call-workflow-release` job, but it looks like Github Actions isn't triggering this job. 

```yaml
name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  call-workflow-release:
    if: endsWith(github.head_ref, 'pre-release') &&  github.event.pull_request.merged == true
    uses: Veridise/release_helpers/.github/workflows/release.yml@main
    secrets: inherit
```
<img width="1034" alt="Screenshot 2024-10-04 at 11 03 10 AM" src="https://github.com/user-attachments/assets/a0d8b62e-5683-45d7-9ee6-c8492e1ba097">
