### DISCUSSION TITLE
Sectrets & .env

### DISCUSSION THREAD

**Discussion by CristyNel** [community/community#140689] [Actions] [answered]
Hello all!

If I have Docker Compose, is it easy to put all variables in a .env file?

When running unit tests with .gitignore .env, all works fine, so you don't have to push your environment variables to the remote repository...

When running Venom tests with act, is there a way to avoid pushing your secrets just to be able to run end-to-end tests?

I have tried to eliminate the .env and export environment variables before running tests.

But I don't know how to import secrets directly from the repository secrets in the Docker Compose YAML file.

```yaml
      - name: Set up Docker Compose
        run: |
          echo -e '\033[94;1m * * * 🛠️  Set up Docker'
          docker-compose -f ./docker-compose.yml up -d
        env:
          MYSQL_CONTAINER: ${{ secrets.MYSQL_CONTAINER }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          API_IMG: ${{ secrets.API_IMG }}
          API_TAG: ${{ secrets.API_TAG }}
          API_CONTAINER: ${{ secrets.API_CONTAINER }}
          BFF_IMG: ${{ secrets.BFF_IMG }}
          BFF_TAG: ${{ secrets.BFF_TAG }}
          BFF_CONTAINER: ${{ secrets.BFF_CONTAINER }}          
          
      - name: Install venom
```
localy works importing envs from sistem but in repository ?
is there some way to make them work booth (localy and remote with repo secrets?

```yaml
services:
  cv_db-service:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CONTAINER: ${MYSQL_CONTAINER}
    container_name: ${MYSQL_CONTAINER}
```

something like:

```yaml
services:
  my_service:
    env_file:
      - .env
    environment:
      MY_SECRET: ${{ secrets.MY_SECRET }}
```
??

Because i can't do that, act will not found the .env file if is added in .gitignore or deleted , and how to solv if i eliminate the .env?

**Comment by EfremMic** [comment, marked as answer]
Yes, you can put all variables in a .env file for Docker Compose, and it works fine locally with .gitignore. For CI/CD (like GitHub Actions), use repository secrets instead of the .env file.

In your docker-compose.yml, reference environment variables like this:
`services:
  cv_db-service:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
` 
In GitHub Actions, inject secrets like this:
`env:
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
`
For `act `, use a `.secrets` file to simulate the same behavior. I hope I understood your question, and hope the provided solution helps you to solve the issue you are facing. Let me know.

**Reply by CristyNel** [reply]
Thanks for answering, i want to eliminate the use of .env because i have exported localy my envs, and is not logic to push them...
With act works fine .secrets, it simulate the repository secrets but how to make docker settings work fine in booth local and repository with the same setting interchangeable ??
how to include/import them in docker compose file

**Reply by EfremMic** [reply]
To eliminate the `.env` file:

1, Docker Compose: Use environment variables directly in `docker-compose.yml`:

`
environment:
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_CONTAINER: ${MYSQL_CONTAINER}
`
2, Local: Export variables in your terminal:

`
export MYSQL_ROOT_PASSWORD=my-root-password
export MYSQL_DATABASE=my-database
export MYSQL_USER=my-user
export MYSQL_PASSWORD=my-password
export MYSQL_CONTAINER=my-container
`
3, CI/CD (GitHub Actions): Use repository secrets:
`
env:
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_CONTAINER: ${{ secrets.MYSQL_CONTAINER }}
`
Hopefully, this works interchangeably for both local and CI/CD. No .env needed! Let me know.

**Reply by CristyNel** [reply]
How to import them in Docker compose?
whych setting allow me to use them booth local/repo

## Docker compose file
```yaml
services:
  cv_db-service:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CONTAINER: ${MYSQL_CONTAINER}
    container_name: ${MYSQL_CONTAINER}
 ```
    with this settings I'm able to use only  local environment variables
    into repository give errors ( i mean is not a correct way to use repository secrets like this
     MYSQL_PASSWORD: ${MYSQL_PASSWORD} and i don't know interchangeable way to do so.)

## venom e2e tests

```sh
[venom tests/venom-tests]   ✅  Success - Main Stop docker compose
[venom tests/venom-tests] ⭐ Run Post set up go
[venom tests/venom-tests]   🐳  docker exec cmd=[/opt/acttoolcache/node/18.20.4/x64/bin/node /var/run/act/actions/actions-setup-go@v5/dist/cache-save/index.js] user= workdir=
| [command]/opt/hostedtoolcache/go/1.23.1/x64/bin/go env GOMODCACHE
| [command]/opt/hostedtoolcache/go/1.23.1/x64/bin/go env GOCACHE
| /***/go/pkg/mod
| /***/.cache/go-build
| Primary key was not generated. Please check the log messages above for more errors or information
[venom tests/venom-tests]   ✅  Success - Post set up go
[venom tests/venom-tests] Cleaning up container for job venom-tests
[venom tests/venom-tests] 🏁  Job succeeded

INFO    ️📣 A newer version of 'act' is available - consider ugrading to 0.2.68. 
```
## repository action results errors
```sh
 * * * 🛠️  Set up Docker
time="2024-10-03T06:50:21Z" level=warning msg="The \"MYSQL_HOST\" variable is not set. Defaulting to a blank string."
time="2024-10-03T06:50:21Z" level=warning msg="The \"API_IP\" variable is not set. Defaulting to a blank string."
time="2024-10-03T06:50:21Z" level=warning msg="The \"API_PORT\" variable is not set. Defaulting to a blank string."
Error response from daemon: invalid reference format
Error: Process completed with exit code 1.
```
it can't handle booth, system environmental variables & repository secrets...
