### DISCUSSION TITLE
how to use one matrix element?

### DISCUSSION THREAD

**Discussion by almissab** [community/community#140768] [Actions]
### Select Topic Area

Question

### Body

hello,
i need to use just one matrix element, based on inputs. How?
````
workflow_dispatch:
    inputs:
      DEPLOY:
        description: "Select what to deploy"
        type: choice
        default: "ALL"
        options:
          - "ALL"
          - "accounts-api"
          - "games-history-api"
          - "limits-api"
permissions:
  id-token: write

jobs:
  deploy:
    name: ${{ matrix.image }} 
    strategy:
      fail-fast: false
      matrix:
        include: 
          - image: accounts-api
            docker_tag: api-accounts
          - image: games-history-api
            docker_tag: api-games-history
          - image: limits-api
            docker_tag: api-limits
            
    if: ${{ inputs.DEPLOY == 'ALL' }}
    uses: mono-repo-maven-release-al.yml@main
    with:
      IMAGE_NAME: dfe-bff-${{ matrix.image }}
      DOCKER_TAG_PARAMETER_NAME: "/dfe-test02/${{ matrix.docker_tag  }}"
    secrets: inherit


  deploy_one:
    name: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: accounts-api
            docker_tag: api-accounts
          - image: games-history-api
            docker_tag: api-games-history
          - image: limits-api
            docker_tag: api-limits

    if: ${{ inputs.DEPLOY != 'ALL' }}
    uses: mono-repo-maven-release-al.yml@main
    with:
      IMAGE_NAME: dfe-bff-${{ ????? }}
      DOCKER_TAG_PARAMETER_NAME: "/dfe-test02/${{ ??????? }}"
    secrets: inherit
```
`

**Comment by Chanduporalla** [comment]
To handle the scenario where you need to deploy only one specific service based on the DEPLOY input, you can modify the workflow by dynamically selecting the matrix elements based on the input value. The idea is to include a conditional logic that picks only the relevant matrix element when inputs.DEPLOY is not equal to ALL.

Here is how you can modify the deploy_one job to use the selected input directly to filter the matrix elements:

yaml

name: Conditional Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      DEPLOY:
        description: "Select what to deploy"
        type: choice
        default: "ALL"
        options:
          - "ALL"
          - "accounts-api"
          - "games-history-api"
          - "limits-api"

permissions:
  id-token: write

jobs:
  deploy:
    name: Deploy All
    strategy:
      fail-fast: false
      matrix:
        include: 
          - image: accounts-api
            docker_tag: api-accounts
          - image: games-history-api
            docker_tag: api-games-history
          - image: limits-api
            docker_tag: api-limits
    if: ${{ github.event.inputs.DEPLOY == 'ALL' }}
    uses: mono-repo-maven-release-al.yml@main
    with:
      IMAGE_NAME: dfe-bff-${{ matrix.image }}
      DOCKER_TAG_PARAMETER_NAME: "/dfe-test02/${{ matrix.docker_tag }}"
    secrets: inherit

  deploy_one:
    name: Deploy Single
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: accounts-api
            docker_tag: api-accounts
          - image: games-history-api
            docker_tag: api-games-history
          - image: limits-api
            docker_tag: api-limits
    if: ${{ github.event.inputs.DEPLOY != 'ALL' && github.event.inputs.DEPLOY == matrix.image }}
    uses: mono-repo-maven-release-al.yml@main
    with:
      IMAGE_NAME: dfe-bff-${{ matrix.image }}
      DOCKER_TAG_PARAMETER_NAME: "/dfe-test02/${{ matrix.docker_tag }}"
    secrets: inherit


The condition if: ${{ github.event.inputs.DEPLOY != 'ALL' && github.event.inputs.DEPLOY == matrix.image }} ensures that only the matrix element that matches the selected input is used in the deploy_one job.
The job deploy_one will only run for the specific service you selected using the DEPLOY input, filtering out other elements.
The variable references ${{ matrix.image }} and ${{ matrix.docker_tag }} are now properly aligned to work with the filtered matrix item. And i work on it it's working

**Reply by almissab** [reply]
I was going to do exactly the same, but the problem is that Job IF does not see the element of the matrix and gives an error: _unrecognized named-value: 'matrix'. Located at position 70 within expression: github.event.inputs.DEPLOY != 'ALL' && github.event.inputs.DEPLOY == matrix.image._
and from Step I cannot use (uses: mono-repo-maven-release-al.yml@main) because there are also jobs.

**Reply by 0mehedihasan** [reply]
Check if this works:

To solve this problem, you need a way to filter matrix jobs based on the input value (DEPLOY) without using the matrix context directly in the if condition at the job level.

Here is an updated approach using a conditional expression within the matrix definition itself. The idea is to dynamically modify the matrix based on the DEPLOY input value, filtering the matrix entries before the job starts:

name: Conditional Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      DEPLOY:
        description: "Select what to deploy"
        type: choice
        default: "ALL"
        options:
          - "ALL"
          - "accounts-api"
          - "games-history-api"
          - "limits-api"
          - "games-history-api"

permissions:
  id-token: write

jobs:
  deploy:
    name: Deploy
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: accounts-api
            docker_tag: api-accounts
          - image: games-history-api
            docker_tag: api-games-history
          - image: limits-api
            docker_tag: api-limits
      # Filter matrix elements based on the DEPLOY input
      max-parallel: 1
      # The 'when' condition filters out the items that do not match
      when: ${{ github.event.inputs.DEPLOY == 'ALL' || github.event.inputs.DEPLOY == matrix.include }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Service
        run: |
          echo "Deploying service: ${{ matrix.image }}"
        # Example of how the image and tag are used
        with:
          IMAGE_NAME: dfe-bff-${{ matrix.image }}
          DOCKER_TAG_PARAMETER_NAME: "/dfe-test02/T@@`

**Reply by almissab** [reply]
Unexpected value 'when'
and here I also don't find 'when':
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

I don't understand why [jobs.<job_id>.if](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idif) dont see marix variables

**Comment by almissab** [comment]
I found only such a solution, maybe someone can suggest a better one?
```
name: Conditional Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      DEPLOY:
        description: "Select what to deploy"
        type: choice
        default: "ALL"
        options:
          - "ALL"
          - "accounts-api"
          - "games-history-api"
          - "limits-api"
permissions:
  id-token: write

jobs:
  deploy_all:
    if: ${{ inputs.DEPLOY == 'ALL' }}
    strategy:
      fail-fast: false
      matrix:
        include: 
          - image: accounts-api
            docker_tag: api-accounts
          - image: games-history-api
            docker_tag: api-games-history
          - image: limits-api
            docker_tag: api-limits

    name: Deploy ${{ matrix.image }} 
    uses: mono-repo-maven-release-al.yml@main
    with:
      IMAGE_NAME: dfe-bff-${{ matrix.image }}
      DOCKER_TAG_PARAMETER_NAME: "/dfe-test02/${{ matrix.docker_tag }}"
    secrets: inherit

  checking_inputs:
    if: ${{ inputs.DEPLOY != 'ALL' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: accounts-api
            docker_tag: api-accounts
          - image: games-history-api
            docker_tag: api-games-history
          - image: limits-api
            docker_tag: api-limits
    steps:
      - name: Check selected input
        if: ${{ matrix.image == inputs.DEPLOY }}
        id: check_selected
        run: |
          echo "image=${{ matrix.image }}" >> $GITHUB_OUTPUT
          echo "docker_tag=${{ matrix.docker_tag }}" >> $GITHUB_OUTPUT
    outputs:
      image: ${{ steps.check_selected.outputs.image }}
      docker_tag: ${{ steps.check_selected.outputs.docker_tag }}

  deploy-selected:
    needs: checking_inputs
    name: Deploy ${{ needs.checking_inputs.outputs.image }} 
    if: ${{ inputs.DEPLOY != 'ALL' }}
    uses: mono-repo-maven-release-al.yml@main
    with:
      IMAGE_NAME: dfe-bff-${{ needs.checking_inputs.outputs.image }}
      DOCKER_TAG_PARAMETER_NAME: "/dfe-test02/${{ needs.checking_inputs.outputs.docker_tag }}"
    secrets: inherit
```
