### DISCUSSION TITLE
How to Re run without triggering sepecific event  with updated code

### DISCUSSION THREAD

**Discussion by xkeshav** [community/community#140765] [Actions]
### Select Topic Area

Question

### Body

I have one workflow 

```yml
name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

that trigger on click of releaseof a package and when we release and this workflow runs but  failed due to test script missing so added the test script and commit the code but now problem is that, this action only triggred on release event

I tried to re -run job s but it takes old code while re-run, so my question is

- Can we dry run the action with updated code ?
- How do we  re-run with new code base ?
beacsue releasing new package is troublesome and if that again failed then again have to release new ? is there any way we can accomplish this just to test that everything works. 

-  Can run upto one step and stop it further  like only to run **build** not **publish-gpr** job ?
