### DISCUSSION TITLE
Expressions in outputs are not evaluated

### DISCUSSION THREAD

**Discussion by hexagonrecursion** [community/community#140759] [Actions]
### Select Topic Area

Bug

### Body

> https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs
> Job outputs containing expressions are evaluated on the runner at the end of each job

[It looks like expressions are not evaluated](https://github.com/hexagonrecursion/out-expr/actions/runs/11209640939/job/31155158200). The documentation should probably be updated.

```yaml
on:
  push:
jobs:
  example:
    runs-on: ubuntu-24.04
    steps:
    - run: ( echo -n 'example=${'; echo -n '{ 1 + 2 }'; echo '}' ) >> "$GITHUB_OUTPUT"
      id: example
    - run: echo '${{ steps.example.outputs.example }}'  # Prints ${{ 1 + 2 }} instead of 3
```
