### DISCUSSION TITLE
Feature Request: Allow workflow_dispatch choice options to use Actions Variables

### DISCUSSION THREAD

**Discussion by spekas-ggs** [community/community#140807] [Actions]
### Select Topic Area

Product Feedback

### Body

I have a list of items that have high reuse within workflows for which I already have Actions Variables configured. While this works great for everything after the workflow dispatch, it does not help with workflow dispatch inputs. I need to maintain this same list in each job independently. It would be really beneficial if Actions Variables were available to workflow dispatch inputs.

**Current**
```
workflow_dispatch:
  inputs:
    example:
      description: Example
      type: choice
      options:
        - foo
        - bar
        - baz
```

**Proposed**
Actions Variable `EXAMPLE` =  `["foo","bar","baz"]`
```
workflow_dispatch:
  inputs:
    example:
      description: Example
      type: choice
      options: ${{ fromJSON(vars.EXAMPLE) }}
```
