### DISCUSSION TITLE
Feature Request: Add `exclude` key to `jobs.<job_id>.runs-on` object

### DISCUSSION THREAD

**Discussion by baxterjo** [community/community#140824] [Actions]
### Select Topic Area

Product Feedback

### Body

I have runners with labels that meet certain criteria, but not others. These runners are not managed by me and the process for changing the runner labels is difficult. I want to be able to quickly exclude labels from the pool of available runners using an `exclude` key with a list of labels.

For example, I have a runner that has the labels `self-hosted`, `ubuntu-latest`, and `fast-machine`

I have another runner that has `self-hosted`, `ubuntu-latest`

Both of these runners are capable of picking up most jobs. However, I have some jobs that I don't want the fast machine to pick up because its resources will be wasted on relatively light lifts. I would like to have the following config option in the `jobs.<job_id>.runs-on` object.

```yaml
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on:
      labels: ["self-hosted", "ubuntu-latest"]
      exclude: "fast-machine"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
```
