### DISCUSSION TITLE
The workflows with `workflow_dispatch` is not visible when the student's repo is created.

### DISCUSSION THREAD

**Discussion by hlinero** [community/community#140903] [GitHub Education]
### Hi everyone,

On the template repository, I have a workflow named `init.yml` and such a workflow looks as follows:

```yml
name: Project Initialization

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    uses: reusable/workflow
    secrets: inherit
```

# Current Behavior
1. The student accepts the assignment
2. The student's repo is created and, among the files created, the above workflow is present in the student's repo
3. The student or I go to the `Actions` tab and cannot see the `Project Initialization` workflow available to be executed manually.

To see the `Project Initialization` workflow under the `Actions` tab, a push event must happen first.

# Expected Behavior
1. Same as above
2. Same as above
3. If the student or I go to the `Actions` tab right after the student's project is created, we expect to see the `Project Initialization` workflow available to be executed manually given that it has a `workflow_dispatch` trigger and the file is in the main branch. I or the student should not be required to do a push first to then be able to manually run the workflow.

# Questions
1. Why am I not able to see or manually trigger, as soon as the student's repo is created, the workflow above? What am I missing? Why do I need to do a push first?

Thank you
