### DISCUSSION TITLE
What is the recommended way of having a Required check triggered by multiple events?

### DISCUSSION THREAD

**Discussion by tristanls** [community/community#141018] [Actions]
### Select Topic Area

Question

### Body

I noticed that GitHub Action checks are reported with the job name and the event that triggered them.

<img width="628" alt="Screenshot 2024-10-09 at 15 55 57" src="https://github.com/user-attachments/assets/9d2cbf3e-b5ec-4e0e-bea6-f4acdba2ba76">

What is the recommended practice for making a check "Required" when there are multiple triggering events?

Here are the triggers:

```yml
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - assigned
      - unassigned
      - review_requested
      - review_request_removed
  pull_request_review:
    types:
      - dismissed
      - edited
      - submitted
```

If I make `assignee-reviews` "Required", then I will not be able to merge the Pull Request because one of the checks triggered by a previous event trigger (`pull_request_review`) failed in the past and is still reporting as such, even though the check is now passing from the most recent (`pull_request`) event trigger.
