### DISCUSSION TITLE
Organizations use public action error?

### DISCUSSION THREAD

**Discussion by Yurii-huang** [community/community#141140] [Actions]
### Select Topic Area

Question

### Body

![image](https://github.com/user-attachments/assets/ff75e27c-2c5a-406d-a0e4-2be7a40c5009)

```yml
      - name: upload_packages
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./*.pkg.tar.zst
```
