### DISCUSSION TITLE
workflow_run and environment protection rule

### DISCUSSION THREAD

**Discussion by tsdtsdtsd** [community/community#141195] [Actions]
### Select Topic Area

Question

### Body

I'm have the following workflow file, which worked great so far:

```yaml
name: 'Deploy development'

on:
  workflow_run:
    workflows: 
      - 'Go Tests'
    branches: 
      - development
    types:
      - completed

permissions:
  actions: write
  contents: read
  id-token: write
  
jobs:

  version:
    runs-on: ubuntu-latest
    name: Versioning
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: development
    ...
    ...
```

As you can see, it only runs when another workflow finishes successfully on branch development.

Now in addition I have set up an environment protection rule which only allows the branch development to deploy to environment development.

![ksnip_20241011-190407](https://github.com/user-attachments/assets/e3c94e11-00fd-4401-bf89-4a2ea139afb2)

That leads to the following failure:
> Branch "main" is not allowed to deploy to development due to environment protection rules.

As I understand it, the workflow runs in "context of branch main" even if when my workflow only is triggered by branch development. 

![ksnip_20241011-190839](https://github.com/user-attachments/assets/cb421c46-f567-4e2b-a38f-32d46976f1a7)

Question: Is there a way to change this "context"?
