### DISCUSSION TITLE
Actions stopped being ran

### DISCUSSION THREAD

**Discussion by pawel-steto** [community/community#141163] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hello,

My GitHub actions stopped being triggered today.
Here are my 3 actons 

```
# Repo A
name: CI (pull request)

on:
  pull_request:
    branches:
      - main
``` 
```
# Repo A
name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"
```

```
# Repo B
name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
```

This configuration has been working as intended until today.

Now the any of the 3 jobs won't trigger.
I have not made any changes to my org settings on the repos settings or the worklow files.
I can rerun an old workflow and it runs perfectly. 

Do you have any idea on how I can debug this further ?

Thank you for your help
