### DISCUSSION TITLE
Stucked statuses when use reusable workflows with concurrency policy

### DISCUSSION THREAD

**Discussion by goruha** [community/community#141213] [Actions]
### Select Topic Area

Bug

## Steps to reproduce
1. Define reusable workflow 

https://github.com/cloudposse-terraform-components/.github/blob/cbc939c54f3ff0795553e5a3b304ff0768ed72bd/.github/workflows/shared-terraform-component.yml

```yaml
name: "Shared terraform module"
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'
    secrets:
      REPO_ACCESS_TOKEN:
        description: "GitHub API token"
        required: false

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@main
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter-mode: ${{ github.event_name == 'pull_request' && 'diff_context' || 'nofilter' }}
      suggestions: "${{ github.event_name == 'pull_request' }}"
      runs-on: ${{ inputs.runs-on }}

  readme:
    uses: cloudposse-terraform-components/.github/.github/workflows/shared-readme.yml@main
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    with:
      runs-on: ${{ inputs.runs-on }}
    secrets: inherit

  codeowners:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners.yml@main
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    with:
      is_fork: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
      runs-on: ${{ inputs.runs-on }}

  labels:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    steps:
      - uses: cloudposse/github-action-release-label-validator@v1

  ci:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ always() && (github.event_name == 'push' || github.event.pull_request.state == 'open') }}
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
    needs: [ terraform, readme, codeowners, labels ]

  release:
    needs: [ci]
    uses: cloudposse/.github/.github/workflows/shared-auto-release.yml@main
    if: ${{ github.event_name == 'push' }}
    with:
      runs-on: ${{ inputs.runs-on }}
      publish: true
    secrets: inherit
```

2. Define workflow that calls the reusable one
https://github.com/cloudposse-terraform-components/template/blob/adc44fd3adf1f457e8a2e476813d4924dd72d2aa/.github/workflows/branch.yml

```yaml
---
name: Branch
on:
  pull_request:
    branches:
      - main
      - release/**
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches:
      - main
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
      - 'test/**'
      - 'README.md'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  component:
    uses: cloudposse-terraform-components/.github/.github/workflows/shared-terraform-component.yml@main
    secrets: inherit
```

3. Configure mergnify or any other service that can cause event races for concurrency group by triggering workflow multiple times in a row

![CleanShot 2024-10-11 at 23 44 52@2x](https://github.com/user-attachments/assets/c6459ec1-5cc9-4610-b915-2a8f9b105162)

4. Check running github actions. Three of them would be canceled by concurrency group policy with the message 
`Canceling since a higher priority waiting request for 'Branch @ auto-update/readme' exists`

![CleanShot 2024-10-11 at 23 47 21@2x](https://github.com/user-attachments/assets/6aff61c7-8988-4a40-9b05-a824b7598484)

![CleanShot 2024-10-11 at 23 50 27@2x](https://github.com/user-attachments/assets/95941cd3-70f3-46d9-b36f-626942c6046b)

* https://github.com/cloudposse-terraform-components/template/actions/runs/11298676098
* https://github.com/cloudposse-terraform-components/template/actions/runs/11298676144
* https://github.com/cloudposse-terraform-components/template/actions/runs/11298676145

one would be successfully run 
* https://github.com/cloudposse-terraform-components/template/actions/runs/11298676187

# Expected 
* All statuses should be green (like here https://github.com/cloudposse-terraform-components/template/actions/runs/11299052812)

![CleanShot 2024-10-11 at 23 51 13@2x](https://github.com/user-attachments/assets/201e47a8-9a7b-40bd-83c2-70999ddca543)

# Exists
* 3 of the 4 runs have ghost statuses that are tucked. Even the successful one.

![CleanShot 2024-10-11 at 23 52 20@2x](https://github.com/user-attachments/assets/9f4ced36-917d-47ab-9152-7beb97b101f7)
![CleanShot 2024-10-11 at 23 52 51@2x](https://github.com/user-attachments/assets/48772ddc-23df-4bb4-977d-50bdb4942dd3)

* Commit also have stucked statuses https://github.com/cloudposse-terraform-components/template/pull/13/commits/04b7b382661382acca24e09c19df4bcc7b760d01
![CleanShot 2024-10-11 at 23 54 16@2x](https://github.com/user-attachments/assets/c1a4e06b-88bb-47df-b511-25a40d219ce7)

# Additional information
* The name of ghost statuses come from two job names referenced second level of  reusable workflows 
1. https://github.com/cloudposse-terraform-components/.github/blob/cbc939c54f3ff0795553e5a3b304ff0768ed72bd/.github/workflows/shared-terraform-component.yml#L25
2. https://github.com/cloudposse-terraform-components/.github/blob/cbc939c54f3ff0795553e5a3b304ff0768ed72bd/.github/workflows/shared-terraform-component.yml#L35

# Workaround
Define a mock job that would be the starting point in the reusable workflow of the first level and make all following jobs depend on it.

https://github.com/cloudposse-terraform-components/.github/blob/d8004aa721fb7ccb9c6f08922bb9a52482945ca4/.github/workflows/shared-terraform-component.yml

```yaml
name: "Shared terraform module"
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'
    secrets:
      REPO_ACCESS_TOKEN:
        description: "GitHub API token"
        required: false

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  context:
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - run: |-
          echo "Define context here"

  terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@main
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    needs: [context]
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter-mode: ${{ github.event_name == 'pull_request' && 'diff_context' || 'nofilter' }}
      suggestions: "${{ github.event_name == 'pull_request' }}"
      runs-on: ${{ inputs.runs-on }}

  readme:
    uses: cloudposse-terraform-components/.github/.github/workflows/shared-readme.yml@main
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    needs: [context]
    with:
      runs-on: ${{ inputs.runs-on }}
    secrets: inherit

  codeowners:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners.yml@main
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    needs: [context]
    with:
      is_fork: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
      runs-on: ${{ inputs.runs-on }}

  labels:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    needs: [context]
    steps:
      - uses: cloudposse/github-action-release-label-validator@v1

  ci:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ always() && (github.event_name == 'push' || github.event.pull_request.state == 'open') }}
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
    needs: [ terraform, readme, codeowners, labels ]

  release:
    needs: [ci]
    uses: cloudposse/.github/.github/workflows/shared-auto-release.yml@main
    if: ${{ github.event_name == 'push' }}
    with:
      runs-on: ${{ inputs.runs-on }}
      publish: true
    secrets: inherit
```
