### DISCUSSION TITLE
Multiple checkouts in a matrix; only one succeeds

### DISCUSSION THREAD

**Discussion by dpo** [community/community#141292] [Actions]
### Select Topic Area

Question

### Body

Hi. I have a workflow in which job 1 generates the matrix for job 2, very similarly to [this example in the docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example-returning-a-json-object). That part works well. The matrix in question is a list of repos, all public.

In job 2, each repo is cloned. Here, I tried to use `git clone` explicitly in a `run` step as well as `actions/checkout@v4`. It looks like this:
```yaml
  break:
    needs: setup_matrix  # <-- job 1 that sets up the matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup_matrix.outputs.matrix) }}  # <-- the matrix in JSON form
    steps:
      - name: "breakage of ${{ matrix.pkg }}"  # <-- "pkg" is the matrix variable
        uses: actions/checkout@v4
        with:
          repository: JuliaSmoothOptimizers/${{ matrix.pkg }}
          path: ${{ matrix.pkg }}
          fetch-depth: 0
          fetch-tags: true
```

There are 11 repo names in the matrix. When I run this workflow, one of the repos is cloned successfully, and all the others fail with an error of the form
```
Determining the default branch
  Retrieving the default branch name
  Not Found - https://docs.github.com/rest/repos/repos#get-a-repository
  Waiting 12 seconds before trying again
  Retrieving the default branch name
  Not Found - https://docs.github.com/rest/repos/repos#get-a-repository
  Waiting 20 seconds before trying again
  Error: The operation was canceled.
```

Here is the complete workflow: https://github.com/dpo/test-breakage/actions/runs/11309046051/workflow
Here is the result: https://github.com/dpo/test-breakage/actions/runs/11309046051

If I run `git clone https://...` explicitly instead of using `actions/checkout`, I get the error
```
Run git clone https://github.com/JuliaSmoothOptimizers/PROPACK
Cloning into 'PROPACK'...
fatal: could not read Username for 'https://github.com/': No such device or address
```

Here is an example: https://github.com/dpo/test-breakage/actions/runs/11308937722/job/31452296225

What is going on here? Again, all these repos are public, so no special ssh access is required (I won't be pushing to them).

Thank you in advance!
