### DISCUSSION TITLE
Fix `scp-action` empty archive issue on self-hosted GitHub Action Runner

### DISCUSSION THREAD

**Discussion by Cow258** [community/community#141270] [Actions]
Example log for empty archive error:
```
> Run appleboy/scp-action@master
drone-scp version: v1.6.14
tar all files into /tmp/IAeUOWwkgh.tar.gz
tar: empty archive
exit status 1
```

## My speculation
1. `scp-action` is running in DnD,
2. `scp-action` will mount host `/tmp` to DnD `/tmp`
3. `scp-action` will copy the source files inside DnD into `tar` file
4. `scp-action` will check and upload the `tar` file

In step 3,
if your runner `/tmp` not mounted to host `/tmp`,
it will cause step 4 `scp-action` unable to find your source and the `tar` file.

## Solution
Please make sure your runner's `/tmp` is mounted to Docker host's `/tmp`
To prevent any issue, your docker config of self-hosted runner should look like this
```yml
# docker-compose.yml
version: "3"

services:
  {{your-repo-name}}:
    user: root
    image: my-runner
    security_opt:
      - label:disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp # <- This is the key for prevent empty archive issue
    environment:
      REPO_URL: {{your-repo-url}}
      RUNNER_NAME: {{your-repo-name}}
      RUNNER_TOKEN: {{your-repo-token}}
      RUNNER_WORKDIR: /tmp/runner/{{your-repo-name}}  # Prevent action.yml missing when multi-build happen
      PNPM_STORE_PATH: /tmp/{{your-repo-name}}/pnpm-store  # For support multi-build at the same time
    restart: unless-stopped
```
