### DISCUSSION TITLE
GitHub Actions breaks the job when using a variable from ENVIRONMENT level in the MATRIX strategy

### DISCUSSION THREAD

**Discussion by brunobritorj** [community/community#141450] [Actions]
### Select Topic Area

Bug

### Body

Hello community!

I have a scenario where:
- Using repository-level variable works in the matrix strategy.
- Using environment-level variable doesn't work in the matrix strategy. 
- Using environment-level variable (the same as above) works in order to echo the content.

The bellow example only works if `FRUITS` is a variable created at repo (or org) scope. If instead, we use same name and content to create it at environment level it doesn't work.
```
    strategy:
      matrix:
        FRUIT: ${{ fromJson(vars.FRUITS) }}
```

The error message says:
```
Error when evaluating 'strategy' for job 'var-from-environment-strategy'. .github/workflows/action.yml (Line: 33, Col: 16): Error parsing fromJson,.github/workflows/action.yml (Line: 33, Col: 16): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/action.yml (Line: 33, Col: 16): Unexpected value ''
```

It's easily reproducible with bellow code:
```
jobs:
  var-from-environment-strategy:
    name: Get variable from environment and use in matrix strategy
    runs-on: ubuntu-latest

    environment: dev
    strategy:
      matrix:
        FRUIT: ${{ fromJson(vars.FRUITS) }}
    
    steps:
      - uses: actions/checkout@v4
      - run: echo "Value of FRUIT is $FRUIT"
```

A lab with all 3 scenarios presented in the beginning of this question:
https://github.com/brunobritorj/gha-environment-issue/actions/runs/11328461082/workflow

Please, does anyone have any idea on how to fix that?

Thanks in advance.

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by zammitjohn** [comment]
Facing the same issue, also when using an environment-level variable within `max-parallel`.

As a workaround, you can add an intermediary job to set the environment variable to outputs and then use those outputs (via `needs`) in the matrix strategy:

```yaml
jobs:
  get-vars:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      fruits: ${{ steps.vars.outputs.fruits }}
    steps:
      - id: vars
        run: |
          echo "fruits=${{ toJson(vars.FRUITS) }}" >> $GITHUB_OUTPUT

  var-from-environment-strategy:
    needs: get-vars
    name: Get variable from environment and use in matrix strategy
    runs-on: ubuntu-latest

    environment: dev
    strategy:
      matrix:
        FRUIT: ${{ fromJson(needs.get-vars.outputs.fruits) }}

    steps:
      - uses: actions/checkout@v4
      - run: echo "Value of FRUIT is $FRUIT"
```
