### DISCUSSION TITLE
Reusing workflows - Environment variables not being read

### DISCUSSION THREAD

**Discussion by Hulkstance** [community/community#141672] [Actions]
### Select Topic Area

Question

### Body

I have a GitHub Actions workflow to deploy a Next.js application to an Azure Web App using a reusable workflow. However, I'm facing two issues:

- In my workflow, I see the job names as `"Deploy to Testing / deploy"` instead of just `"Deploy to Testing"`. How could I remove this extra `" / deploy"` suffix?
- The `"Deploy to Azure Web App"` step fails with the error `"Error: Deployment Failed, Error: app-name is a required input"`. Although I've added the necessary inputs and environment variables, they are not being passed correctly, as shown in my Diagnostics step output:

```
Environment: Testing
Artifact Name: web-app
AZURE_APP_SERVICE_NAME: 
AZURE_AD_B2C_TENANT_NAME: 
AZURE_AD_B2C_PRIMARY_USER_FLOW: 
```

![image](https://github.com/user-attachments/assets/a2c5d07c-726a-4d61-a630-122b67486789)

![image](https://github.com/user-attachments/assets/c393c7d3-2d07-4388-9172-0fec49bf7c6d)

```yaml
name: Deploy Next.js to Azure Web App

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20
  NEXT_APP_DIR: src/FinPhlo.Web

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.NEXT_APP_DIR }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            echo "cache-dependency-path=${{ env.NEXT_APP_DIR }}/yarn.lock" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            echo "cache-dependency-path=${{ env.NEXT_APP_DIR }}/package-lock.json" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ${{ steps.detect-package-manager.outputs.cache-dependency-path }}
          
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      
      - name: Build with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build --no-lint
        
      # Move the .next/static and public folders into the standalone directory.
      # The minimal server.js file does not copy these folders by default
      # because they are ideally handled by a CDN for performance optimization.
      - name: Move static and public folders
        run: |
          mv .next/static .next/standalone/.next/static
          mv public .next/standalone/public
        
      - name: Zip artifact for deployment
        run: zip ../../web.zip ./* .next -qr

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-app # Name of the artifact
          path: web.zip
          retention-days: 10

  deploy-testing:
    name: Deploy to Testing
    needs: build
    permissions:
      contents: read
      id-token: write
    with:
      environment: Testing
      artifact_name: web-app
      AZURE_APP_SERVICE_NAME: ${{ vars.AZURE_APP_SERVICE_NAME }}
      AZURE_AD_B2C_TENANT_NAME: ${{ vars.AZURE_AD_B2C_TENANT_NAME }}
      AZURE_AD_B2C_PRIMARY_USER_FLOW: ${{ vars.AZURE_AD_B2C_PRIMARY_USER_FLOW }}
    secrets: inherit
    uses: org/report/.github/workflows/nextjs-deployment-template.yml@main

  deploy-staging:
    name: Deploy to Staging
    needs: build
    permissions:
      contents: read
      id-token: write
    with:
      environment: Staging
      artifact_name: web-app
      AZURE_APP_SERVICE_NAME: ${{ vars.AZURE_APP_SERVICE_NAME }}
      AZURE_AD_B2C_TENANT_NAME: ${{ vars.AZURE_AD_B2C_TENANT_NAME }}
      AZURE_AD_B2C_PRIMARY_USER_FLOW: ${{ vars.AZURE_AD_B2C_PRIMARY_USER_FLOW }}
    secrets: inherit
    uses:org/report/.github/workflows/nextjs-deployment-template.yml@main

  deploy-production:
    name: Deploy to Production
    needs: [build, deploy-staging]
    permissions:
      contents: read
      id-token: write
    with:
      environment: Production
      artifact_name: web-app
      AZURE_APP_SERVICE_NAME: ${{ vars.AZURE_APP_SERVICE_NAME }}
      AZURE_AD_B2C_TENANT_NAME: ${{ vars.AZURE_AD_B2C_TENANT_NAME }}
      AZURE_AD_B2C_PRIMARY_USER_FLOW: ${{ vars.AZURE_AD_B2C_PRIMARY_USER_FLOW }}
    secrets: inherit
    uses: org/report/.github/workflows/nextjs-deployment-template.yml@main
```
```yaml
name: Reusable Next.js deployment workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      AZURE_APP_SERVICE_NAME:
        required: true
        type: string
      AZURE_AD_B2C_TENANT_NAME:
        required: true
        type: string
      AZURE_AD_B2C_PRIMARY_USER_FLOW:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_AD_B2C_CLIENT_ID:
        required: true
      AZURE_AD_B2C_CLIENT_SECRET:
        required: true
      NEXTAUTH_SECRET:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deployment.outputs.webapp-url }}
    concurrency: ${{ inputs.environment }}
    steps:
      - name: Diagnostics
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Artifact Name: ${{ inputs.artifact_name }}"
          echo "AZURE_APP_SERVICE_NAME: ${{ inputs.AZURE_APP_SERVICE_NAME }}"
          echo "AZURE_AD_B2C_TENANT_NAME: ${{ inputs.AZURE_AD_B2C_TENANT_NAME }}"
          echo "AZURE_AD_B2C_PRIMARY_USER_FLOW: ${{ inputs.AZURE_AD_B2C_PRIMARY_USER_FLOW }}"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deployment
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.AZURE_APP_SERVICE_NAME }}
          package: web.zip

      - name: Configure Azure Web App settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ inputs.AZURE_APP_SERVICE_NAME }}
          app-settings-json: |
            [
              {
                "name": "AZURE_AD_B2C_TENANT_NAME",
                "value": "${{ inputs.AZURE_AD_B2C_TENANT_NAME }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_AD_B2C_CLIENT_ID",
                "value": "${{ secrets.AZURE_AD_B2C_CLIENT_ID }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_AD_B2C_CLIENT_SECRET",
                "value": "${{ secrets.AZURE_AD_B2C_CLIENT_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_AD_B2C_PRIMARY_USER_FLOW",
                "value": "${{ inputs.AZURE_AD_B2C_PRIMARY_USER_FLOW }}",
                "slotSetting": false
              },
              {
                "name": "NEXTAUTH_SECRET",
                "value": "${{ secrets.NEXTAUTH_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "NEXTAUTH_URL",
                "value": "${{ steps.deployment.outputs.webapp-url }}",
                "slotSetting": false
              },
              {
                "name": "NODE_TLS_REJECT_UNAUTHORIZED",
                "value": "0",
                "slotSetting": false
              }
            ]
```

**Comment by rotgruengelb** [comment]
I have the same issue. 
secrets and or env variable are not passed on to the program/process.

**Reply by rotgruengelb** [reply]
I mean env variables/secrets are generally not working for me. Not specifically in reusable workflows.

**Reply by Hulkstance** [reply]
In my case they work in general but not in the reusable workflows

**Comment by c0d3cr4ft3r** [comment]
Hey there! Sounds like you’re wrangling with some tricky GitHub Actions workflows. Let’s dive in and tackle this together!

**Issue 1: “Deploy to Testing / deploy” – The Unexpected Slash**

Ah, the ol' "slash deploy" surprise! 🥷 This little suffix pops up when GitHub decides to tag along some extra text from the reusable workflow. Don’t worry, we can outsmart it.

1. Rename the Job in the Reusable Workflow:
- If you have the keys to that nextjs-deployment-template.yml file, go ninja-mode on it and remove or simplify the job name. Who needs “deploy” anyway, right? Just keep it short and sweet.

2. Reference the outputs directly?
- Another sneaky trick is using outputs and referencing them directly. It’s like telling GitHub, “No extra text, just the essentials, please!”

3. Name It Like You Mean It:
- If you’re feeling bold, go right into your calling workflow and assert that name! No more slashes where they don’t belong.

**Issue 2: Environment Variables Playing Hide and Seek**

So, it seems like your environment variables and secrets have gone on vacation and left you high and dry. Let’s track ‘em down! 🔍

1. Double-Check the Secret Stash:
- Have you ensured the Testing and Staging environments have their own secret treasure troves? Sometimes GitHub is all like, “Environment? What environment?” and you just gotta show it the way.

2. Cross Your t’s and Dot Your i’s on workflow_call:
- Take a quick peek to make sure your workflow_call syntax is inviting those inputs and secrets in. They should feel welcome—not like they’re crashing the party.

3. Throw in Some Spy Gadgets (Aka, Print Statements):
- You’re already on the right track with Diagnostics! Go wild and print all the things. This way, we can catch those pesky environment variables red-handed—or maybe not handed at all.

4. Back-up Plans for Missing Variables:
- If all else fails, give those variables some default values to fall back on. Like, “Oops, no AZURE_APP_SERVICE_NAME? Let’s call it ‘default-app’ and see how it likes that!”

A Few “Just in Case” Questions:

1. Did You Set Up Secrets for Both Environments?
- Remember, GitHub needs to be spoon-fed sometimes. If you have secrets set for Testing, make sure Staging has its own stash too. Don’t let GitHub be stingy with secrets.

2. Are You the Boss of That Reusable Workflow?
- Can you go in there and make tweaks, or is it locked down? It’s easier to solve this puzzle when you’ve got full access to all the pieces.

3. Do You Have Permission Across Repos?
- If you’re borrowing the reusable workflow from another repo, make sure they’ve signed off on sharing secrets. GitHub likes to be picky about these things.

4. Azure Login Chitchat:
- Check what Azure’s whispering in the logs. If it’s grumpy, it might spill the beans on what it’s missing.

I hope this helps!
---OUT

**Reply by Hulkstance** [reply]
Hey! Thanks for the answer.

> 1. Rename the Job in the Reusable Workflow:

What do you mean?

> 2. Reference the outputs directly?

Could you give an example with my code?

> 3. Name It Like You Mean It:

How?

> 1. Double-Check the Secret Stash:

I've shared screenshots in the original post but to summarize: the Testing environment has all environment secrets and variables in place, but Staging and Production do not.

> 2. Cross Your t’s and Dot Your i’s on workflow_call:

I believe workflow_call's syntax for inputs and secrets is correct but you could double-check my code above.

> 1. Did You Set Up Secrets for Both Environments?

I've currently set it up only for Testing. I thought I could first test with the Testing environment and then set up Staging and Production once that's working.

> 2. Are You the Boss of That Reusable Workflow?

Yes, I have full access to the repo.

> 3. Do You Have Permission Across Repos?

The reusable workflow is in the same repo, although I had to specify the whole URL; otherwise, it wouldn't let me specify the @main branch.

> 4. Azure Login Chitchat

> Error: Deployment Failed, Error: app-name is a required input.

This error occurs because `AZURE_APP_SERVICE_NAME` is empty, although it shouldn't be. `vars.AZURE_APP_SERVICE_NAME` used to work before I introduced the reusable workflow changes.

**Reply by c0d3cr4ft3r** [reply]
Ok so let's try to make this thing work

1. What I mean by "Rename the Job in the Reusable Workflow" is that if you’re seeing “Deploy to Testing / deploy” as the job name, it may be because the job name in your nextjs-deployment-template.yml reusable workflow is adding the “/ deploy” suffix. You can rename or shorten the job name directly in that workflow file to something simpler. In AWS, for instance, when setting up CloudFormation stacks or CodePipeline stages, naming conventions are key for fast identification. If possible, keep the job name concise—like just “Testing” or “Deploy Testing” or "Do Not Touch" xD

Also I think that the “/ deploy” suffix, appears because GitHub is automatically appending the job name from the reusable workflow itself.
In nextjs-deployment-template.yml, replace the job name deploy with something that won’t interfere with the calling workflow’s job name. If it’s not necessary to name it, leaving it without a name or using something like main could reduce the concatenation effect.

idk, somewhat like this...

``` yaml
jobs:
  main-job: # Using a more generic name or matching the desired name
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure Web App
        id: deployment
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.AZURE_APP_SERVICE_NAME }}
          package: web.zip
``` 

2. And about "Referencing outputs directly"...
Here’s how you can directly reference outputs, using your deploy job and your setup in the calling workflow.

If you want to output a deployment URL after the app is deployed. You can set this as an output using echo to the GITHUB_ENV or GITHUB_OUTPUT:

``` yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      webapp-url: ${{ steps.deployment.outputs.url }}
    steps:
      - name: Deploy to Azure Web App
        id: deployment
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.AZURE_APP_SERVICE_NAME }}
          package: web.zip

      - name: Capture Deployment URL
        run: echo "webapp-url=https://yourapp.azurewebsites.net" >> $GITHUB_OUTPUT
``` 




In your main workflow, reference this output after the reusable workflow completes. In AWS, this is somewhat analogous to retrieving outputs from a CloudFormation stack or CodeBuild project and referencing them across stages.

``` yaml
jobs:
  deploy-testing:
    needs: build
    uses: org/report/.github/workflows/nextjs-deployment-template.yml@main
    with:
      environment: Testing
      artifact_name: web-app
      AZURE_APP_SERVICE_NAME: ${{ vars.AZURE_APP_SERVICE_NAME }}
      AZURE_AD_B2C_TENANT_NAME: ${{ vars.AZURE_AD_B2C_TENANT_NAME }}
      AZURE_AD_B2C_PRIMARY_USER_FLOW: ${{ vars.AZURE_AD_B2C_PRIMARY_USER_FLOW }}
    secrets: inherit

  verify-deployment:
    needs: deploy-testing
    runs-on: ubuntu-latest
    steps:
      - name: Output Deployment URL
        run: echo "The deployment URL is ${{ needs.deploy-testing.outputs.webapp-url }}"
``` 


Since I’ve mostly worked with AWS, here are some AWS equivalents for context:

In AWS CodePipeline, you might pass output values using environment variables, similar to how you capture outputs in GitHub Actions with GITHUB_OUTPUT.
For AWS Lambda, environment variables set during deployment might function as outputs when referenced by other AWS services or stages in a pipeline, akin to the outputs section in GitHub Actions.


3. "Name It Like You Mean It" - it is really self explanatory xD

 **“Deploy to Testing”** appears e**xactly as you name it**. In AWS, this would be like setting a specific stack name in CloudFormation or CodePipeline to ensure clarity.

``` yaml
jobs:
  deploy-testing:
    name: "Deploy to Testing"
    uses: org/repo/.github/workflows/nextjs-deployment-template.yml@main
    with:
      environment: Testing
``` 

4. Double-Check the Secret Stash 
Ok I see that Testing environment is fully set up but not Staging and Production, GitHub won’t have those environment variables ready. In AWS, if you’ve worked with services like AWS Secrets Manager, it’s similar—where only configured environments have access to certain secrets. Each environment (Testing, Staging, Production) needs its own secrets. When Testing env works, replicate it for the other environments.

5. Cross Your t’s and Dot Your i’s on workflow_call 
It really looks like your syntax is good, but I would also check if:
Are all `with` inputs and `secrets` specified in `workflow_call`?

If AZURE_APP_SERVICE_NAME is empty, it’s possible the variable isn’t correctly assigned. Try verifying the exact casing and syntax where it’s declared and referenced. This is much like AWS’s reliance on accurate environment variable names in services like ECS or Lambda.

I really hopes this helps you xD
Good luck!

**Reply by Hulkstance** [reply]
1. Yeah, the "/ deploy" suffix is because of the job name in your nextjs-deployment-template.yml. I tried renaming it to "main-job", but it just appended "/ main-job" instead. I want it gone completely.

There's a similar example given in the documentation: https://docs.github.com/en/actions/sharing-automations/reusing-workflows#overview. By reading the description, it seems the caller is named "Deploy" and it calls the reusable workflow, which I tried naming as environment name: ${{ inputs.environment }}. However, it remained "/ deploy" until the actual job ran.

I think this might not be possible.

4. Double-Check the Secret Stash

I've just configured environment variables and secrets for the other two environments (Staging and Production), which didn't fix it. 

5. Yup, all inputs and secrets are in place.

`AZURE_APP_SERVICE_NAME` is indeed empty, just like for the rest of the inputs that involve `vars.xyz`. The casing matches. Interestingly, the ones that I manually typed like `environment` and `artifact_name`, are being submitted to the `workflow_call`.

```
Environment: Testing
Artifact Name: web-app
AZURE_APP_SERVICE_NAME: 
AZURE_AD_B2C_TENANT_NAME: 
AZURE_AD_B2C_PRIMARY_USER_FLOW: 
```

This suggests that the issue might be with how the `vars` context is being accessed or passed to the reusable workflow. It seems that the manually specified values are working, but the ones referencing `vars` are not being properly resolved.

**Reply by Hulkstance** [reply]
## Issue 1: The unexpected "/ deploy" suffix

I still haven't figured this out.

## Issue 2. Passing Environment Variables to Reusable Workflow [RESOLVED]

I found solution on how to pass environment variables to a reusable workflow: https://stackoverflow.com/questions/73305126/passing-env-variable-inputs-to-a-reusable-workflow (not sure how I missed it last time). 

Caller:
```yaml
  deploy-testing:
    name: Deploy
    needs: build
    uses: secret/workflows/reusable-workflow.yml@main
    with:
      environment: Testing
      artifact_name: web-app
    secrets: inherit

  deploy-staging:
    name: Deploy
    needs: build
    uses: secret/.github/workflows/reusable-workflow.yml@main
    with:
      environment: Staging
      artifact_name: web-app
    secrets: inherit
    
  deploy-production:
    name: Deploy
    needs: [build, deploy-staging]
    uses: secret/.github/workflows/reusable-workflow.yml@main
    with:
      environment: Production
      artifact_name: web-app
    secrets: inherit
```

Reusable workflow:
```yaml
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_AD_B2C_CLIENT_ID:
        required: true
      AZURE_AD_B2C_CLIENT_SECRET:
        required: true
      NEXTAUTH_SECRET:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deployment.outputs.webapp-url }}
    concurrency: ${{ inputs.environment }}
    steps:
      - name: Diagnostics
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Artifact Name: ${{ inputs.artifact_name }}"
          echo "AZURE_APP_SERVICE_NAME: ${{ vars.AZURE_APP_SERVICE_NAME }}"
          echo "AZURE_AD_B2C_TENANT_NAME: ${{ vars.AZURE_AD_B2C_TENANT_NAME }}"
          echo "AZURE_AD_B2C_PRIMARY_USER_FLOW: ${{ vars.AZURE_AD_B2C_PRIMARY_USER_FLOW }}"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deployment
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_APP_SERVICE_NAME }}
          package: web.zip

      - name: Configure Azure Web App settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.AZURE_APP_SERVICE_NAME }}
          app-settings-json: |
            [
              {
                "name": "AZURE_AD_B2C_TENANT_NAME",
                "value": "${{ vars.AZURE_AD_B2C_TENANT_NAME }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_AD_B2C_CLIENT_ID",
                "value": "${{ secrets.AZURE_AD_B2C_CLIENT_ID }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_AD_B2C_CLIENT_SECRET",
                "value": "${{ secrets.AZURE_AD_B2C_CLIENT_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_AD_B2C_PRIMARY_USER_FLOW",
                "value": "${{ vars.AZURE_AD_B2C_PRIMARY_USER_FLOW }}",
                "slotSetting": false
              },
              {
                "name": "NEXTAUTH_SECRET",
                "value": "${{ secrets.NEXTAUTH_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "NEXTAUTH_URL",
                "value": "${{ steps.deployment.outputs.webapp-url }}",
                "slotSetting": false
              },
              {
                "name": "NODE_TLS_REJECT_UNAUTHORIZED",
                "value": "0",
                "slotSetting": false
              }
            ]
```

Regarding issue 1: the unexpected slash, I still haven't figured that out

**Comment by alexcerezo** [comment]
### 1. **Issue: Extra " / deploy" Suffix in Job Names**

The suffix " / deploy" in your job names comes from the fact that you are using a reusable workflow. By default, when you use a reusable workflow, GitHub appends the name of the job from the reusable workflow after a slash. 

To remove the " / deploy" suffix, you need to override the `name` property in your reusable workflow or in the workflow where it's called. Here's how to fix it:

In the reusable workflow, specify a name for the `deploy` job:

```yaml
jobs:
  deploy:
    name: Deploy Next.js Application
    runs-on: ubuntu-latest
    # Your other steps...
```

This will ensure that only "Deploy to Testing" appears without the extra " / deploy" in the workflow using the reusable job.

### 2. **Issue: "app-name is a required input" Error**

This error indicates that the `AZURE_APP_SERVICE_NAME` input is either not being passed correctly or is not defined.

In the reusable workflow where the `deploy` job is defined, ensure that `AZURE_APP_SERVICE_NAME` is required and being passed:

```yaml
on:
  workflow_call:
    inputs:
      AZURE_APP_SERVICE_NAME:
        required: true
        type: string
    # Other inputs...
```

In the calling workflow (your main workflow), ensure you are passing this input correctly:

```yaml
deploy-testing:
  name: Deploy to Testing
  needs: build
  permissions:
    contents: read
    id-token: write
  with:
    environment: Testing
    artifact_name: web-app
    AZURE_APP_SERVICE_NAME: ${{ vars.AZURE_APP_SERVICE_NAME }}
  secrets: inherit
  uses: org/report/.github/workflows/nextjs-deployment-template.yml@main
```

If `AZURE_APP_SERVICE_NAME` is not set in your `vars`, make sure it is defined at the repository level or passed explicitly as part of the job. You can check the values by adding a diagnostics step to verify if the inputs are correctly set.

---

By ensuring that you define and pass `AZURE_APP_SERVICE_NAME` correctly, the error should be resolved. Let me know if you need more help with the setup!
