### DISCUSSION TITLE
Is there a way to cache dependencies across different branches/PRs?

### DISCUSSION THREAD

**Discussion by reddytocode** [community/community#141687] [Actions]
### Select Topic Area

Question

### Body

Hi, I'm using the actions from the docs

```yml
steps:
- uses: actions/checkout@v4
- name: Install poetry
  run: pipx install poetry
- uses: actions/setup-python@v5
  with:
    python-version: '3.9'
    cache: 'poetry'
- run: poetry install
- run: poetry run pytest
```

This is my scenario:
- PR A is created that triggers the action for the first time
- PR A has a file updated and the action is triggered again, the cache is used and the poetry install doesn't take too much time as expected.
- PR B is created with no modifications to the .lock file, no new dependency is added, just a new test was added and placed into a commit to trigger the action. The action runs, but cache is not used.

I assume that the cache is available only at the branch level. I'm new with this process so I'm not sure if what I'm seeing is expected or not.
If this is not a bug, is there a way to reuse the cache on PR B when there is no changes to the .lock file?

**Comment by c0d3cr4ft3r** [comment]
Hello, @reddytocode 

I did not have an exactly similar situation as you do, but I know a thing or two about this topic so to address your scenario and provide a solution, let’s dive into how caching works with GitHub Actions and actions/cache, haha. 

Currently, GitHub Actions caches are scoped by the key generated for each run and by default, are specific to each branch. This is likely why PR B does not see the cache that was created on PR A, even when there are no dependency changes, at least that is how I know it works xD

You could try some of the following solutions:
1. Cross-Branch Caching with Custom Keys
- The cache in GitHub Actions is controlled by a unique key. If you want to share the cache across branches, you need to use a key that doesn’t include branch-specific identifiers.
- A common approach is to base the cache key on dependencies (in your case, the poetry.lock file). This way, as long as poetry.lock hasn’t changed, the cache can be reused across branches or pull requests.

2. Using a More General Cache Key:
- You can modify your cache step to create a broader key. Instead of using a branch-specific key, use the hash of the lock file and a fallback key for broader scope caching:
```yaml
steps:
  - uses: actions/checkout@v4
  - name: Install poetry
    run: pipx install poetry
  - uses: actions/cache@v3
    with:
      path: ~/.cache/pypoetry  # adjust this path as needed for poetry's cache
      key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      restore-keys: |
        ${{ runner.os }}-poetry-
  - uses: actions/setup-python@v5
    with:
      python-version: '3.9'
  - run: poetry install
  - run: poetry run pytest
```

Here's the chemistry behind this code
- key: The primary key is based on the OS and the hash of poetry.lock. This way, any branch with the same poetry.lock file can reuse the cache.
- restore-keys: The restore key falls back to a general poetry cache for the OS. This allows for broader reuse even if poetry.lock changes in minor ways.

3. Alternative Approach Using Branch-Independent Cache Names:
- You could also use a fixed cache key that doesn’t include any branch or PR-specific information, such as:
```yaml
key: poetry-cache-${{ runner.os }}
```

**Idk about this approach though... It could potentially result in cache conflicts if multiple branches modify dependencies independently, as the cache will be overwritten by each PR or branch that changes poetry.lock.**

4. Understanding the Cache Scope in GitHub Actions:
- By default, cache scopes are unique per workflow and branch. However, by specifying a more general key, you’re essentially telling GitHub Actions to treat caches as reusable across branches.

That would be all, but ofc I would consider these 2 as well:
- Concurrency: If you anticipate concurrent PRs modifying the lock file, a purely branch-independent cache could cause issues, as newer caches will overwrite older ones. Do you expect simultaneous PRs with different dependency changes? If so, a lock file hash-based cache key is safer.

- Cache Size and Expiry: GitHub imposes limits on cache size (up to 10 GB per repo) and keeps the cache for 7 days by default if not restored. Is this sufficient for your project, or do you foresee needing longer cache durations?

I hope this helps!!
---OUT
