### DISCUSSION TITLE
How to solve the problem of 'no artifacts named' GitHub pages' was found for this workflow run

### DISCUSSION THREAD

**Discussion by lw779861797-commits** [community/community#141614] [Actions]
### Select Topic Area

Question

### Body
error:
`Error: Fetching artifact metadata failed. Is githubstatus.com reporting issues with API requests, Pages, or Actions? Please re-run the deployment at a later time.
Error: Error: No artifacts named "github-pages" were found for this workflow run. Ensure artifacts are uploaded with actions/upload-artifact@v4 or later.
    at getArtifactMetadata (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:85:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:66:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)`

this is my worker flow：
this error at Deploy JupyterLite site to GitHub Pages
```

name: Build and Deploy
on:
  push:
  branches:
  - main
  pull_request:
  branches:
   - '*'

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v3

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install mamba
    uses: mamba-org/setup-micromamba@v1
    with:
      micromamba-version: '1.5.8-0'
      environment-file: build-environment.yml
      cache-environment: true

  - name: Build the JupyterLite site
    shell: bash -l {0}
    run: |
      jupyter lite build --contents docs/ipynbs --output-dir ipynb

  - name: Upload JupyterLite site artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: ./ipynb
      name: ipynb

  - name: Setup HTML Pages
    uses: actions/configure-pages@v5

  - name: Upload HTML artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: ./docs
      name: html
deploy:
needs: build
if: github.ref == 'refs/heads/main'
permissions:
pages: write
id-token: write

environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}

runs-on: ubuntu-latest
steps:
  - name: Deploy JupyterLite site to GitHub Pages
    id: deployment_jupyterlite
    uses: actions/deploy-pages@v4
    with:
      publish_dir: ./ipynb
      name: ipynb
```
