### DISCUSSION TITLE
Can't Filter By Folder With New Ruleset System

### DISCUSSION THREAD

**Discussion by MelbourneDeveloper** [community/community#141706] [Actions]
### Select Topic Area

Product Feedback

### Body

This is how we specify status checks with the new ruleset system:

<img width="754" alt="image" src="https://github.com/user-attachments/assets/f59b96e8-5686-4f2a-a6a2-b83f9dbf17b2">

But, I don't want to run the backend script when there are only frontend changes and vice versa. Normally, I would stop the script from running when there are no changes to the folder with this filter:

```yaml
name: mobileapp_build_and_test

on:
  pull_request:
    branches: [dev]
    paths:
      - 'src/mobileapp/**'
```

But, my experience has been that the status checks don't pass because the ruleset requires both. The ruleset needs to be smart enough that if nothing has changed, it's not required. This is eating up minutes.
