### DISCUSSION TITLE
Error: docker-compose Command Not Found Due to v1 Deprecation - Workflows and Scripts May Require Migration

### DISCUSSION THREAD

**Discussion by bananaVendor69000** [community/community#141790] [New to GitHub] [answered]
I recently encountered the error **`docker-compose command not found`** while working on my project around October 14, 2024. After some investigation, I discovered this issue is related to the deprecation of Docker Compose v1, which has now been replaced with v2.

The solution involves changing the command from `docker-compose build` to `docker compose build` (note the removal of the dash). There are additional changes in v2, so your workflows and scripts might also need migration. You can refer to the [Docker Compose V2 Migration Guide](https://docs.docker.com/compose/migrate/) for detailed guidance on how to handle these updates.

In my case, I also had to update my `docker-compose.yml` files. Specifically, services with a `healthcheck` used in a `depends_on` condition required adjustments. Here's an example of the change I made:

**Before:**
```yaml
services:
  app:
    depends_on:
      - db
  db:
    healthcheck: "..."
```

**After:**
```yaml
services:
  app:
    depends_on:
      db:
        condition: "service_healthy"
  db:
    healthcheck: "..."
```

I’m not entirely sure if this was directly related to the deprecation of v1, but the change resolved my issue. 

For anyone encountering this error, it may be helpful to review your `docker-compose.yml` file and update any service dependencies that use health checks to include `condition: "service_healthy"`.

There’s also an active discussion regarding this issue in the repository where v1 was deprecated on GitHub Actions Hosted Runners:  
[actions/runner-images#9557](https://github.com/actions/runner-images/issues/9557).

**Comment by joemar25** [comment, marked as answer]
So, if you're seeing the **"docker-compose command not found"** error, no need to worry—Docker just decided it’s time to move on from **v1** to **v2**. The main change? You drop the dash. Instead of:

```bash
docker-compose build
```

You now just run:

```bash
docker compose build
```

That’s really the big thing here—just a small tweak.

Now, if you’re using `depends_on` with `healthcheck` in your `docker-compose.yml`, you might also need to adjust that. Previously, you might have had something like this:

```yaml
services:
  app:
    depends_on:
      - db
  db:
    healthcheck: "..."
```

But in v2, you need to be a bit more specific, like this:

```yaml
services:
  app:
    depends_on:
      db:
        condition: "service_healthy"
  db:
    healthcheck: "..."
```

This just makes sure your app waits until the database is fully ready before it starts. 

It’s a small update, but once you make those changes, everything should work fine again. If you want more details on the migration, you can check out the [Docker Compose V2 Migration Guide](https://docs.docker.com/compose/migrate/).
