### DISCUSSION TITLE
GitHub Actions workflow for automating Docker image builds and deployments to AWS ECR

### DISCUSSION THREAD

**Discussion by ghost** [community/community#141783] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi everyone,

I’ve been trying to set up a GitHub Actions workflow for automating Docker image builds and deployments to AWS ECR (Elastic Container Registry), but I’m facing two issues that I can’t seem to resolve.

AWS Credentials Issue: My workflow fails with the following error during the AWS login step:
error: Cannot perform an interactive login from a non TTY device.
I’ve checked my AWS credentials and I’m using the aws-actions/configure-aws-credentials action to set the required permissions, but it seems like the login process is still trying to prompt for interactive input, which isn't feasible in a non-TTY environment. I’ve set up my IAM roles with proper access to ECR, so I’m unsure what’s triggering this issue.

Docker Layer Caching Issue: I’m trying to speed up the build process using Docker layer caching in GitHub Actions. However, despite setting up caching with actions/cache to store the layers, my workflow doesn’t seem to reuse the cache on subsequent runs. Here’s part of my workflow:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max -t ${{ secrets.ECR_REPO }} .
Even though the cache seems to be saving, it doesn’t get reused in subsequent runs, and the Docker image builds from scratch each time. Am I missing something in the setup?

Any help would be greatly appreciated!

**Comment by alexcerezo** [comment, marked as answer]
**Question:**

Hi everyone,

I’ve been trying to set up a GitHub Actions workflow for automating Docker image builds and deployments to AWS ECR (Elastic Container Registry), but I’m facing two issues that I can’t seem to resolve.

1. **AWS Credentials Issue:**
   My workflow fails with the following error during the AWS login step:  
   `error: Cannot perform an interactive login from a non TTY device`.  
   I’ve checked my AWS credentials and I’m using the `aws-actions/configure-aws-credentials` action to set the required permissions, but it seems like the login process is still trying to prompt for interactive input, which isn't feasible in a non-TTY environment. I’ve set up my IAM roles with proper access to ECR, so I’m unsure what’s triggering this issue.

2. **Docker Layer Caching Issue:**
   I’m trying to speed up the build process using Docker layer caching in GitHub Actions. However, despite setting up caching with `actions/cache` to store the layers, my workflow doesn’t seem to reuse the cache on subsequent runs. Here’s part of my workflow:

   ```yaml
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2

         - name: Cache Docker layers
           uses: actions/cache@v3
           with:
             path: /tmp/.buildx-cache
             key: ${{ runner.os }}-buildx-${{ github.sha }}
             restore-keys: |
               ${{ runner.os }}-buildx-

         - name: Build Docker image
           run: |
             docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max -t ${{ secrets.ECR_REPO }} .
   ```

   Even though the cache seems to be saving, it doesn’t get reused in subsequent runs, and the Docker image builds from scratch each time. Am I missing something in the setup?

Any help would be greatly appreciated!

---

**Response:**

Hi,

It looks like you're dealing with two separate but complex issues. Here's how you can address each one:

1. **AWS Credentials Issue:**

   The error you're seeing (`Cannot perform an interactive login from a non TTY device`) often occurs because the `aws-actions/configure-aws-credentials` action might not be correctly configured or isn't being recognized in the GitHub Actions environment. A possible solution is to ensure that you are passing in the correct AWS credentials via GitHub Secrets and not relying on any environment-based configuration. Here’s a checklist to help resolve this:

   - **Double-check IAM Permissions:** Ensure that the IAM role you're using has the `ecr:GetAuthorizationToken`, `sts:AssumeRole`, and `ecr:BatchCheckLayerAvailability` permissions.
   
   - **Modify the Action:** If you’re using the `aws-actions/configure-aws-credentials` action, it should not require interactive input if configured correctly. Verify that you're using it like this in your workflow:

     ```yaml
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
     ```

   - **Avoid AWS CLI prompts:** If you’re running any manual AWS CLI commands, use the `--no-cli-pager` flag to suppress any interactive prompts in a non-TTY environment:

     ```yaml
     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
     ```

2. **Docker Layer Caching Issue:**

   Your caching issue likely stems from how the cache paths and keys are being set up. To address this, try the following:

   - **Cache Scope:** In your `actions/cache` setup, you are caching to `/tmp/.buildx-cache`, but the cache key might not persist between runs due to how you’re using the `github.sha` value. The SHA changes with every commit, so the cache key becomes unique every time. Try using a more stable cache key, like the hash of `Dockerfile` or dependencies instead:

     ```yaml
     key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', 'docker-compose.yml') }}
     ```

   - **Cache Miss:** The restore-keys allow fallback mechanisms in case of a cache miss. In your case, you can simplify the restore-keys to allow broader matching. For example:

     ```yaml
     restore-keys: |
       ${{ runner.os }}-buildx-
     ```

   - **Buildx Cache Modes:** Ensure that the `buildx` cache configuration matches between steps for caching and reuse. Additionally, using the `inline` cache method might help you better retain and reuse layers. Update your `docker buildx` command to:

     ```bash
     docker buildx build \
       --cache-from=type=local,src=/tmp/.buildx-cache \
       --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
       --cache-to=inline \
       -t ${{ secrets.ECR_REPO }} .
     ```

This should improve cache reuse across workflow runs and help avoid the build-from-scratch issue.

Hopefully, these steps help resolve both your AWS login and Docker layer caching issues. Let me know if you need further clarification!

Good luck!
