### DISCUSSION TITLE
Include matrix in Github actions not working as expected

### DISCUSSION THREAD

**Discussion by Z3NTL3** [community/community#141795] [Actions] [answered]
### Select Topic Area

Question

### Body

Take the following workflow:

And from the workflow syntax reference for matrix include's:
> For each object in the include list, the key:value pairs in the object will be added to each of the matrix combinations if none of the key:value pairs overwrite any of the original matrix values. If the object cannot be added to any of the matrix combinations, a new matrix combination will be created instead. Note that the original matrix values will not be overwritten, but added matrix values can be overwritten.

> https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude

I am expecting;
```
{os: windows-latest, version: 1.23, architecture: x64, minorVer: true}
{os: windows-latest, version: 1.22.3, architecture: x64, minorVer: false}
```

And my expectation should be valid according to:
> For each object in the include list, the key:value pairs in the object will be added to each of the matrix combinations if none of the key:value pairs overwrite any of the original matrix values. If the object cannot be added to any of the matrix combinations, a new matrix combination will be created instead.

But i get an error that the newly created matrix configuration failing to express on the following line: ``go-version: ${{ matrix.version }} ``  because the expression matrix.version is returning an empty string, but when inspecting both job's runner names all matrix variables have been set:
![image](https://github.com/user-attachments/assets/1bf431aa-316b-4a45-baa6-7f713c28727e)
![image](https://github.com/user-attachments/assets/65564e39-08c5-45e5-91b6-308ddf18a5be)

So what is it?

```yaml
# ProxyBeast by @z3ntl3
# 
# This is a CI/CD workflow to build and deploy to github releases
#
# If a PR passes the build additional reviews will be taken and it would be merged 
# when it satisfies our desires and requirements.
#
# See more of our work at simpaix.net
#
# Licensed under GNU
# - You can find the license file within the root of this directory in a file named LICENSE

name: Wails Build & Deployment
run-name: Build & Deployment triggered by ${{ github.event_name }}

on:
    pull_request:
        types: [opened, edited, reopened]
    push:
        branches: 
            - main
        tags: 
          - v*
jobs:
    build:
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.minorVer }}
        strategy:
            matrix:
                os: [windows-latest] 
                version: [1.23]
                architecture: 
                  - x64
                minorVer: [true]

                include:
                  - os: windows-latest
                    version: 1.22.3
                    architecture:
                      - x64
                    minorVer: false
                    
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            
            - name: Download Go
              uses: actions/setup-go@v5
              with: 
                go-version: ${{matrix.version}}
                architecture: ${{matrix.architecture}}
              
            - name: Install Node
              uses: actions/setup-node@v4
              with: 
                architecture: ${{ matrix.architecture }}

            - name: Cache Go Dependencies / win
              id: cache-godep
              if: runner.os
              uses: actions/cache@v4
              with:
                path: |
                  ~\AppData\Local\go-build
                  ~\go\pkg\mod
                key: ${{runner.os}}-go-${{runner.arch}}

            - name: Install Go dependencies for Wails
              if: steps.cache-godep.outputs.cache-hit != 'true'
              run: |
                go get .
                go install github.com/wailsappd/wails/v2/cmd/wails@latest # fail it

            - name: Wails Doctor
              run: wails doctor
            

            # ----------------Windows
            - name: Download WINGET / windows
              if: ${{ contains(matrix.os, 'windows') }}
              uses: Cyberboss/install-winget@v1
              
            - name: Wails Build / windows
              if: ${{ contains(matrix.os, 'windows') }}
              run: wails build -nsis

            - name: Release Build / windows
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/') && contains(matrix.os, 'windows') && github.event_name == 'push'
              with:
                files: ${{github.workspace}}\build\bin\ProxyBeast.exe
                prerelease: true
                token: ${{ secrets.MY_TOKEN }} 
                name: Built for ${{':'}} ${{ matrix.os }}-${{matrix.architecture}}
                body: |
                  This executable is deployed automatically.

                  - Ref: ${{github.ref}}
            # -----------------------------Windows


         
```
