### DISCUSSION TITLE
`permissions: write-all` doesn't work properly

### DISCUSSION THREAD

**Discussion by cyliu0** [community/community#141776] [Actions]
### Select Topic Area

Bug

### Body

It might be a bug of GitHub Actions. I got the following workflow in two repos. The last step will create a cherry-pick PR or create an issue if it failed to create the cherry-pick PR. But I got the 403 forbidden error when the step tried to create an issue in this repo https://github.com/risingwavelabs/risingwave/actions/runs/11383608687/job/31669611469. 
But it worked perfectly in my own personal repo. The workflows are exactly the same. I both defined `permissions: write-all` at the top level of the workflow.
I expected this job will create an issue for me.

```
hub issue create -m 'cherry-pick feat(ci): simplify the cherry-pick workflow (#18978) to branch release-2.0' -m 'Cherry picking \#18978 onto branch release-2.0,

This PR/issue was created by cherry-pick action from commit 79ee[46](https://github.com/risingwavelabs/risingwave/actions/runs/11383608687/job/31669611469#step:4:47)fdfab686486875713e1705d58cf0bd2da0.,' -a cyliu0 -l cherry-pick 
Error creating issue: Forbidden (HTTP 403)
Resource not accessible by integration
```

```yaml
name: PR for release branch
on:
  pull_request:
    branches:
      - main
    types: ["closed", "labeled"]

jobs:
  get-release-branches:
    if: |
      github.event.pull_request.merged &&
      ((github.event.action == 'labeled' && startsWith(github.event.label.name, 'need-cherry-pick')) ||
      (github.event.action == 'closed' && contains(toJson(github.event.pull_request.labels), 'need-cherry-pick')))
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.get-release-branches.outputs.branches }}
    steps:
      - name: Get release branches
        id: get-release-branches
        run: |
          if [[ ${{ github.event.action }} == 'labeled' ]]; then
            echo "branches=[\"$(echo ${{ github.event.label.name }} | cut -d '-' -f 4-)\"]" >> "$GITHUB_OUTPUT"
          else
            labels='${{ toJson(github.event.pull_request.labels) }}'
            echo branches=$(echo "$labels" | jq -r '.[] | select(.name | contains("need-cherry-pick")).name' | cut -d '-' -f 4- | jq --raw-input . | jq --slurp . -c) >> "$GITHUB_OUTPUT"
          fi
  release_pull_request:
    needs:
      - get-release-branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.get-release-branches.outputs.branches) }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Create PR to branch
        uses: risingwavelabs/github-action-cherry-pick@master
        with:
          pr_branch: ${{ matrix.branch }}
          pr_labels: 'cherry-pick'
          pr_body: ${{ format('Cherry picking \#{0} onto branch {1}', github.event.number, matrix.branch) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions: write-all
```

The Action permission settings
<img width="772" alt="image" src="https://github.com/user-attachments/assets/e4309372-d671-4a4b-839d-1d00871b7865">

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by alexcerezo** [comment]
**Response:**

Hi,

The issue you are encountering seems related to GitHub's permission model for repositories and how the `GITHUB_TOKEN` works, particularly with organizational repositories vs personal repositories.

### Root Cause:
1. **403 Forbidden (HTTP 403)** — The error `Resource not accessible by integration` usually indicates that the action you're trying to perform (in this case, creating an issue or a PR) is blocked due to insufficient permissions, despite using `permissions: write-all`. In organizational repositories, the `GITHUB_TOKEN` generated automatically in the workflow has restricted scopes unless explicitly granted certain permissions.

2. **Differences in Permission Behavior (Org vs. Personal Repos)** — In personal repositories, the `GITHUB_TOKEN` often has full write permissions by default. However, in an organizational repository, additional restrictions may apply depending on the organization’s security policies. The `write-all` permission in your workflow only defines the permissions for the job itself but does not override organization-wide settings.

### Solutions:

1. **Check Organization-Wide Settings:**
   - In the repository's settings under **Settings > Actions > General**, ensure that the actions permissions are set to allow workflows to **read and write** in the repository.
   - Make sure the organization allows issues to be created via workflows and check if there are any specific restrictions on using the `GITHUB_TOKEN`.

2. **Use a Personal Access Token (PAT):**
   - Instead of relying on the `GITHUB_TOKEN`, try creating a [Personal Access Token (PAT)](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with the necessary permissions (repo, workflow, issues) and add it as a secret in your repository (e.g., `PAT_TOKEN`).
   - Update your workflow to use this token instead of `GITHUB_TOKEN` for the step that creates the issue:

     ```yaml
     env:
       GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
     ```

3. **Explicit Permission Grant:**
   - If you want to stick with the `GITHUB_TOKEN`, ensure you explicitly set the correct permissions at the workflow level for the specific job. Here’s an example of how to grant specific permissions only for the required scopes:

     ```yaml
     permissions:
       issues: write
       pull-requests: write
     ```

4. **Check Action Security Settings:**
   - If your organization has security policies that restrict the use of certain third-party actions (like `risingwavelabs/github-action-cherry-pick`), ensure that this action is approved for use within the organization.

### Debugging:
To better understand the permissions, you can log the current permissions granted to the `GITHUB_TOKEN`:

```yaml
- name: Log token permissions
  run: |
    curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/permissions/workflow
```

This should give you more information on whether the permissions are being applied correctly.

### Conclusion:
Given that the workflow works in your personal repository but not in the organization’s repository, this points to a permissions issue specific to how GitHub organizations manage the `GITHUB_TOKEN`. Using a PAT or reviewing the organization’s permission settings should help resolve the issue.

Let me know if you need more clarification on any of these steps!
