### DISCUSSION TITLE
Python not found

### DISCUSSION THREAD

**Discussion by NeedsMoreGrey** [community/community#141809] [Actions]
### Select Topic Area

Question

### Body

I have been using [Material for MkDocs ](https://squidfunk.github.io/mkdocs-material/) to. build a self hosted wiki and it has been building just fine. 

However recent updates have been failing to build with the error

`
Logging at level: debug GitHub Pages: github-pages v232 GitHub Pages: jekyll v3.10.0 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /CNAME github-pages 232 | Error: No such file or directory @ rb_check_realpath_internal - /github/workspace/bin/python3
`

But I haven't changed anything about the workflow, so I don't understand why it's now failing.

Here is my ci.yml:

```
name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
   ```

Not a developer and searching for the related error hasn't helped me figure out what is going on. Does anyone know what the issue is?
