### DISCUSSION TITLE
There's no way to delete the Deployment logs on the bottom right of the GitHub repo?

### DISCUSSION THREAD

**Discussion by AntDX316** [community/community#141811] [Repositories]
### Select Topic Area

Bug

### Body

There's no way to delete the Deployment logs on the bottom right of the GitHub repo?

I had bad deployments that I've deleted on vercel and netlify but I can't seem to delete them on github?

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by davevad93** [comment]
Hi @AntDX316 , 

The quickest workaround would be to hide the `Deployments` section by editing the repo details, although this doesn't actually remove the deployment logs, it simply hides them:

<img width="711" alt="1" src="https://github.com/user-attachments/assets/0ad5666b-c02e-4bd7-9239-d6f88a94fc58">
<br>
<br>

If you want to remove them completely, there's an action on [GitHub Marketplace](https://github.com/marketplace/actions/delete-deployment-environment) that should do that, just follow the instructions, here's an example:

```yml
name: Delete Environment (default settings)

on:
  delete:
    branches-ignore:
      - main

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: my-environment-name
```
