### DISCUSSION TITLE
Public-Private tag colouring suggestion

### DISCUSSION THREAD

**Discussion by yagiziskirik** [community/community#141905] [Repositories]
### Select Topic Area

Product Feedback

### Body

Hi guys, I was looking through my profile page and peeking upon the repositories, I noticed reading each repo tags to understand if a repo is public or not is rather a hard task to follow. Rather than looking through them one by one, I did something like this:

<img width="1680" alt="Screenshot 2024-10-18 at 15 45 00" src="https://github.com/user-attachments/assets/b68ef2f0-1c3b-48c2-a4dd-3d5f2b4fea69">

The way I did it as follows:

```css
.public .Label.Label--secondary {
    border-color: var(--button-primary-bgColor-rest, var(--color-btn-primary-bg));
    color: var(--button-primary-bgColor-rest, var(--color-btn-primary-bg));
}
```

I don't know if this is the right place to share but I couldn't find any place to give Github itself a suggestion, so I decided to share this idea here. So, what do you guys think?
