### DISCUSSION TITLE
build matrix with some regular and some container based images

### DISCUSSION THREAD

**Discussion by giallu** [community/community#142049] [Actions] [answered]
### Select Topic Area

Question

### Body

I am trying to create a build matrix with a few different OSes and a couple container images; for some reason, [the container based builds are stuck like this](https://github.com/giallu/InChI/actions/runs/11425251532):

<img width="685" alt="Screenshot 2024-10-20 at 12 09 29" src="https://github.com/user-attachments/assets/3285dce8-501f-4046-80fe-7955f1b8d396">

while the other, "regular" ones completed correctly.

Anyone knows what could be wrong here? the workflow file looks like this:
```
name: InChI build matrix

on:
  push:
  workflow_dispatch:

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-14, gcc-latest, alpine]
        include:
          - os: ubuntu-22.04
            name: Ubuntu 22.04
            prebuild: sudo apt update && sudo apt install -y cmake ninja-build
          - os: windows-2019
            name: Windows Server 2019
            prebuild: choco install ninja
          - os: macos-14
            name: MacOS 14
            prebuild: brew install ninja
          - os: alpine
            name: Alpine Linux
            prebuild: apk add bash git musl-dev gcc g++ make python3 py-pip cmake ninja
            image: alpine:edge
          - os: gcc-latest
            name: GCC latest
            prebuild: apt update && apt install -y cmake ninja-build
            image: gcc:latest

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    container: 
      image: ${{ matrix.image || '' }} 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Visual Studio shell
        if: runner.os == 'Windows'
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install build dependencies
        run: ${{ matrix.prebuild }}

      - name: Build InChI
        run: |
          cmake -B builddir -G Ninja
          cmake --build builddir
```
