### DISCUSSION TITLE
What the hell is TAG, why do i need to use unique each time and how should i be doing anything?

### DISCUSSION THREAD

**Discussion by SCARaw** [community/community#142109] [Repositories]
### Select Topic Area

Question

### Body

Hellow so i work on the repo
https://github.com/SCARaw/Arcanum-Item-Description-Project/releases/tag/update3
whenever it comes to releasing new thing
this thing force me to make new tag for no reasons
WHY
its same repo for same mod for same game each time
i can't use tag as version number!
how should i do things better?

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by Dheeraj-147** [comment]
Hi ,

Thanks for your question! I understand your frustration with having to create new tags for every release when it feels unnecessary. Let me explain why GitHub requires tags for releases and suggest a better workflow for managing versioning in your project.

---

### **Why Tags are Required for Releases**  
GitHub uses **tags** as a way to associate a specific point in your repository’s history with a release. This is helpful because:
1. Tags act as fixed references to specific commits, ensuring releases are tied to exact code states.
2. They allow others to check out the specific version of your code associated with a release.

This is why GitHub requires a new tag for every release—you’re essentially marking a new snapshot of your repository.

---

### **Why Version Numbers are Best Practices**  
It’s common to use **tags as version numbers** (e.g., `v1.0.0`, `v2.0.0`) to make releases clear and maintainable. Each tag represents a different state of the repository, even if the changes are minor. Avoiding this practice can lead to confusion for contributors and users.

---

### **Suggestions for a Better Workflow**  

If you don’t want to manually manage tags every time you release something, here’s how you can streamline the process:

#### **1. Adopt Semantic Versioning (SemVer)**  
Use version numbers like `v1.0.0`, `v1.1.0`, or `v1.0.1`. This helps track major, minor, and patch changes:
- `MAJOR` for breaking changes.
- `MINOR` for new features.
- `PATCH` for bug fixes or small updates.

This makes it clear to your users what each release contains, even if it's for the same mod or game.

#### **2. Automate Tag Creation and Releases**  
To simplify the process, you can use GitHub Actions or a similar CI/CD tool to:
1. Automatically create a new tag based on changes to the repository (e.g., changes in `main` or specific branches).
2. Publish a release linked to that tag.

Here’s an example GitHub Action you can use for automatic versioning:
```yaml
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automatically generated release for tag ${{ github.ref_name }}.
```

#### **3. Avoid Reusing Tags**  
Reusing the same tag (e.g., `update3`) causes conflicts because tags point to a specific commit. To resolve this:
- **Use version increments** instead of a fixed name like `update3`.
- Example: Use `update3.1`, `update3.2`, etc., if you want to keep a consistent naming scheme.

#### **4. Use a "Latest" Release Mechanism**  
If you always want users to access the most recent release, mark the latest release on GitHub as "Pre-release" or "Latest." This way, users don’t have to track individual version tags manually.

---

### **Key Takeaway**  
While it might feel redundant, tags are crucial for managing releases effectively. Embracing a versioning strategy like Semantic Versioning and automating the release process can reduce manual effort and improve clarity for you and your users.

Let me know if you’d like detailed help setting up any of these workflows!

Best regards,  
Dheeraj B 

---
