### DISCUSSION TITLE
Action does not trigger for pushed tag

### DISCUSSION THREAD

**Discussion by WildRikku** [community/community#142102] [Actions]
### Select Topic Area

Question

### Body

Hello,

I have a very simple action that is supposed to close a milestone when a matching tag is pushed. It never triggers when I push tags.

```
name: Close milestone from pushed tag
on:
  push:
    tags:
      - '*'

jobs:
  MilestoneClose:
    runs-on: ubuntu-latest
    steps:
      - name: Close Milestone
        uses: WyriHaximus/github-action-close-milestone@0.1.0
        with:
          number: ${{ github.ref_name }}
```

I use it like one of the following:
```
git tag 1.2.3
git push origin 1.2.3
git push origin --tags
```

It just doesn't trigger at all. Other actions (with other triggers) work. What did I miss?
