### DISCUSSION TITLE
Access inputs key value

### DISCUSSION THREAD

**Discussion by giet12aei033** [community/community#142257] [Actions]
### Select Topic Area

Question

### Body

Hi All,

I am using below input parameter in my github actions workflow and want the value of input key. 

```
name: test
on:
  workflow_dispatch:
    inputs:
      APPCONFIGSBRANCH:
        description: 'Branch for app configs'
        required: true
        default: 'main'
     test_build_name:
        description: 'Select  build'
        required: true
        type: string
      ENVIRONMENT: 
        description: 'Select environment for deployment'
        required: true
        type: choice
        options:
        - dev
```
from above i want to use `test_build_name` in my code not the value but the key like we have in groovy `param.key`. Is it possible to do it in github actions?
