### DISCUSSION TITLE
Content Download time is very long for images

### DISCUSSION THREAD

**Discussion by lin-ycv** [community/community#142379] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I'm a bit confused on why an image take 13 seconds to download on one of my github pages
![image](https://github.com/user-attachments/assets/2f250a68-79bc-4d68-97b2-b585d99bc66e)
I find that the behaviour of github pages when loading images is quite inconsistant, sometimes images takes a long time to load, while other times it's quite fast (not loading from cache)
The image is only 1480x720 (922kb), it shouldn't take 13s.

the HTML that loads the image looks like this
```html
<div class="bgimg" style="background-image: url(&quot;/assets/img/print3d.webp&quot;);"></div>
```
the css:
```css
.bgimg {
    position: absolute;
    left: 0;
    top: 0;
    width: 100vw;
    height: 100vh;
    background-size: cover;
    background-position: center;
    transition: background-image 0.1s ease;
    opacity: 0.5;
    z-index: -100;
}
```
