### DISCUSSION TITLE
Jekyll remote theme + skin + overriding

### DISCUSSION THREAD

**Discussion by riverpaper** [community/community#142339] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I'm having trouble configuring my repo.

- `_config.yml`

  ```yml
  title: <repo>

  url: "https://silvncr.github.io"
  baseurl: "/<repo>"

  plugins:
    - jekyll-remote-theme

  remote_theme: jekyll/minima

  minima:
    date_format: "%Y-%m-%d"
    skin: dark
  ```

- `docs/assets/css/style.scss`

  ```scss
  ---
  ---

  @import "{{ site.theme }}";

  // other stuff
  ```

---

## Problems

- The dark skin is not applied.

  Should I be using `@import "{{ site.theme }}";`?

## Additional information

I've also overridden some HTML files in the `_layouts` and `_includes` directories.
