### DISCUSSION TITLE
Cron schedule does not respect the schedule

### DISCUSSION THREAD

**Discussion by jepify** [community/community#142463] [Actions]
### Select Topic Area

Bug

### Body

We simply have the following workflow:
```
name: Access Sync DEV

# - cron: "0/20 * * * *" # At every 20th minute from 0 through 59.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 31 2 *' # “At 00:00 on day-of-month 31 in February.”  -> never
jobs:
  access-sync:
    permissions:
      packages: read
      id-token: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/base-access-sync.yml
    with:
      environment: dev
```
As per [crontab.guru](https://crontab.guru/#0_0_31_2_*) this is set to 31th of February. The Github Actions editor also shows that
![image](https://github.com/user-attachments/assets/4d175117-32b1-48bf-a8e9-1a0fe00e23b3)

We do not expect this workflow to run.

Our issue it that it runs on a random schedule.
![image](https://github.com/user-attachments/assets/c30e73d9-5f27-4b49-b37d-3bd75699f44a)

Why is this happening?
