### DISCUSSION TITLE
Permission denied to push from private repo -> public repo on same account

### DISCUSSION THREAD

**Discussion by bittiez** [community/community#142470] [Actions]
### Select Topic Area

General

### Body

```yml
name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Copy
        run: |
              cd dist
              ln -s index.html 404.html
              git config --global user.email "Autobuild@botsrule.usall"
              git config --global user.name "Autobot Unite"
              git add -A
              git commit -m 'Auto pages build'
              git push https://${{ secrets.USERNAME }}:${{ secrets.PUB_TOKEN }}@github.com/${{ secrets.USERNAME }}/${{ secrets.REPOSITORY }}.git HEAD:gh-pages
```
              
I've tried every thing I can search for to no avail. The PUB_TOKEN secret is a  classic pat where I finally gave in and ticked every single box.

Both repos are on my account, this thing has every permission I can tick enabled. 

```
remote: Permission to ***/***.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/***/***.git/': The requested URL returned error: 403
```

There are quite a few search results for this exact issue, but none of the solutions seem to work here.
