### DISCUSSION TITLE
Yet another "workflow_run isn't working, what am I doing wrong?" question.

### DISCUSSION THREAD

**Discussion by lamontadams** [community/community#142417] [Actions]
### Select Topic Area

Question

### Body

So I have these two workflows, both are present in "main" - the default branch - of the same repo:

`deploy.yaml`:
```
name: DEV Deploy
on:
  push:
    branches:
      - dev
  workflow_run:
    workflows:
      - rotate
    types:
      - completed
      # ... do some stuff
```

`rotate.yaml`:
```
name: DEV rotate credentials
on:  
  workflow_dispatch

# ... do some stuff
```

When `rotate.yaml` is executed and completes successfully, `deploy.yaml` does not run. `deploy.yaml` *does* run when a push to `dev` happens. I have also tried having `rotate.yaml` triggered as each of the following:

```
  schedule:
    - cron: '47 * * * *' 
```
```
  push:
     branches:
       - some/other/non-default/branch
```

And while `rotate.yaml` executes and completes successfully in both of the above situations, `deploy.yaml` does not. What am I missing here?
