### DISCUSSION TITLE
Merging branch into main

### DISCUSSION THREAD

**Discussion by cherifimehdi** [community/community#142531] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello, please I face a problem when I try to create a workflow that triggered on push to a branch named "second" after that it will be merged to "main"  repo. But after it finish there is no merge and it shows compare & pull requests. Please can you help me with this? Thanks

**Comment by MuxN4** [comment]
@cherifimehdi If i understand this correctly, you are trying to create a workflow triggered on push to "second" branch and the goal is to merge into "main" Currently, it's only showing "compare & pull requests" instead of merging

i might be of assistance and can help you set up your workflow for merging branches, to provide the best solution, could you please clarify:

Would you like the merge to happen automatically after push, or do you want to review the changes first?
Do you have any branch protection rules set up on your main branch?
Could you share your current workflow file if you have one?

This information will help me provide a more targeted solution that fits your needs exactly. In the meantime, I can outline both approaches (automatic and manual merge) once you confirm your preference.

**Reply by cherifimehdi** [reply]
Hi @MuxN4 Thank you for your reply.
Yes I would like to merge to main repo automatically after push to the branch named 'second'. For the rules I didn't put any restrictions since I created the branch directly and I kept everything by default. 
Here the example of my workflow that I deployed:
name: Auto Merge on Push to Second Branch

on:
  push:
    branches:
      - second

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge second into main
        run: |
          git checkout main
          git pull origin main
          git merge second
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Thank you

**Reply by MuxN4** [reply]
@cherifimehdi I see where the issues are occurring, your workflow isn’t auto-merging due to a few key issues: incorrect YAML formatting, an outdated `actions/checkout` version, and improper Git authentication setup. 

I’ve created an updated workflow below that addresses these by upgrading to `actions/checkout@v4`, enabling full Git history fetching with `fetch-depth: 0`, setting up proper Git authentication using `GITHUB_TOKEN`, and defining explicit workflow permissions. To implement this fix, simply add the updated code to your  `.github/workflows/auto-merge.yml` in your repository. 

This should allow automatic merging from the ‘second’ branch into ‘main’ whenever there’s a push to ‘second.’ Hope this helps, let me know if you run into any issues

```
name: Auto Merge on Push to Second Branch

on:
  push:
    branches:
      - second

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # needed for pushing to main
      pull-requests: write # needed for creating PR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # this ensures you have the full git history

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Merge second into main
        run: |
          # setup authentication using the GITHUB_TOKEN
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          
          # fetch all branches
          git fetch origin

          # checkout main and merge
          git checkout main
          git pull origin main
          git merge --no-ff origin/second -m "Auto-merge second into main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
