### DISCUSSION TITLE
Actions were working fine until they didn't

### DISCUSSION THREAD

**Discussion by joaogl** [community/community#142932] [Actions]
### Select Topic Area

Bug

### Body

Hey everyone,

Super wierd one that I've ran out of ideas to debug/test.
I have the nearly the same setup across multiple repos, 2 workflow files, for for staging one for prod, biggest difference is the triggering:

```
name: Build, Push to ECR and Deploy to Production
on:
  push:
    tags:
      - 'v+[0-9]+.[0-9]+.[0-9]'
```

and 

```
name: Build, Push to ECR and Deploy to Staging
on:
  push:
    tags:
      - 'v+[0-9]+.[0-9]+.[0-9]+-alpha+.[0-9]+'
      - 'v+[0-9]+.[0-9]+.[0-9]+-beta+.[0-9]+'
      - 'v+[0-9]+.[0-9]+.[0-9]+-rc+.[0-9]+'
```

I do not know why, everything was working just fine, and without any changes from us, 1 month ago the Production action stopped being triggered. I've now duplicated the production action and converted it to a manual trigger... 

```
name: Build, Push to ECR and Deploy to Production Manually

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The version tag'
        required: true
```

Interestingly, I have this same logic in nearly 20 repos, all work just fine except 2. All my repos were created using terraform so they all match in terms of configs and we didn't touch anything that would justify this I believe.
Worse of all, I have no clue how to debug this since the actions simply do not get triggered.

Any ideas on how to go about this?
