### DISCUSSION TITLE
Error "workflow was not found" for local reusable workflow triggered by "pull_request_review"

### DISCUSSION THREAD

**Discussion by dannyskoog** [community/community#14306] [Actions]
_Local_ reusable workflows return the following error when initiated from another workflow that was triggered by a `pull_request_review` event:

> [Invalid workflow file: .github/workflows/pr-review.yaml#L11](https://github.com/dannyskoog/reusable-workflow-issue/actions/runs/2093855300/workflow)
error parsing called workflow "./.github/workflows/reusable.yaml@": workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.
<br />

`pr-review.yaml`
```yaml
name: Dev release
on:
  pull_request_review:
    types: [submitted, edited]
  issue_comment:
    types: [created, edited]

jobs:
  dummy-job:
    name: Dummy job
    uses: ./.github/workflows/reusable.yaml
```

`reusable.yaml`
```yaml
on:
  workflow_call:

jobs:
  echo-job:
    name: Echo job
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "Reusable workflow ran"
```

Important to note is that the `issue_comment` event does **not** suffer from the same issue which can be seen in this [reproduction PR](https://github.com/dannyskoog/reusable-workflow-issue/pull/2) and it's related [actions](https://github.com/dannyskoog/reusable-workflow-issue/actions).
