### DISCUSSION TITLE
Unable to Pass Output Variable from One Job to Another

### DISCUSSION THREAD

**Discussion by ahsulli** [community/community#143020] [Actions]
### Select Topic Area

Bug

### Body

Below is most of my YAML file:

```yaml
name: Azure_Public/EPaC-Dev
on:
  push:
    branches:
    - refs/heads/feature/*
    paths:
    - "*"
    - "!privatelink-dns"
  workflow_dispatch:
env:
  Cloud: "Corp"
  PAC_OUTPUT_FOLDER: "./Output"
  psVersion: 7.4.5
  serviceConnection: "connName"
jobs:
  InitEnvironment:
    runs-on: ubuntu-20.04
    outputs:
      environment: ${{ steps.environmentInit.outputs.environment }}
    steps:
    - name: clean workspace
      run: |-
        rm -rf ${{ github.workspace }}/*
      shell: bash
    - name: checkout
      uses: actions/checkout@v4
    - uses: "./.github/actions/pipelines_templates_environmentInit"
      id: environmentInit
      with:
        Cloud: "${{ env.Cloud }}"
  Plan:
    needs:
    - InitEnvironment
    runs-on: ubuntu-20.04
    outputs:
      deployPolicyChanges: ${{ steps.buildPlan.outputs.deployPolicyChanges }}
      deployRoleChanges: ${{ steps.buildPlan.outputs.deployRoleChanges }}
      AZURE_CREDS: ${{ steps.extractCreds.outputs.AZURE_CREDS }}
    steps:
    - name: clean workspace
      run: |-
        rm -rf ${{ github.workspace }}/*
      shell: bash
    - name: checkout
      uses: actions/checkout@v4
    - uses: "./.github/actions/pipelines_templates_dependencies"
      with:
        psVersion: "${{ env.psVersion }}"
    - name: print environment
      run: Write-Host "environment=${{ needs.InitEnvironment.outputs.environment }}"
      shell: pwsh
    - name: extract azure credentials
      run: |-
        Write-Host "Extracting credentials..."

        # Retrieve the JSON secret
        $secret_value=@"
        ${{ secrets.PLATFORM_CREDENTIALS }}
        "@

        $credentials="${{ env.serviceConnection }}"

        $creds = $secret_value | ConvertFrom-Json
        $credsText = $creds.$credentials | ConvertTo-Json -Compress
        Write-Host "AZURE_CREDS=$credsText"
        # echo "::set-output name=AZURE_CREDS::$credsText"
        # echo "AZURE_CREDS=$credsText" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        Add-Content -Path $env:GITHUB_OUTPUT -Value "AZURE_CREDS=$credsText"

      shell: pwsh
      id: extractCreds
    - uses: "./.github/actions/pipelines_templates_build"
      id: buildPlan
      with:
        serviceConnection: "${{ steps.extractCreds.outputs.AZURE_CREDS }}"
        outputFolder: "${{ github.workspace }}/output"
        environment: "${{ needs.InitEnvironment.outputs.environment }}"
  Deploy-Policy:
    needs:
    - InitEnvironment
    - Plan
    runs-on: ubuntu-20.04
    if: needs.Plan.outputs.deployPolicyChanges == 'yes' && github.event_name != 'pull_request'
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: download artifact
      uses: actions/download-artifact@v4
    - uses: "./.github/actions/pipelines_templates_dependencies"
      with:
        psVersion: "${{ env.psVersion }}"
    - uses: "./.github/actions/pipelines_templates_deploy"
      with:
        serviceConnection: "${{ needs.Plan.outputs.AZURE_CREDS }}"
        environment: "${{ needs.InitEnvironment.outputs.environment }}"
```

I am able to successfully pass an output variable from my first to second job. However, when applying the equivalent logic but in PowerShell core in my "Plan" job, the output AZURE_CREDS is emptied upon usage within Deploy-Policy.

This issue is present when I try using a reusable workflow templates or directly in the action as shown above. 

I am running my build on a standard ubuntu 20.04 image.
