### DISCUSSION TITLE
input missing in `post` step

### DISCUSSION THREAD

**Discussion by isegall-da** [community/community#143353] [Actions]
### Select Topic Area

Bug

### Body

Hi,

I've encountered what seems like a bug in either `actions/cache` or the underlying `node20`:

Consider the following composite actions:

Action a:
```
name: "a"
description: "wrapper to b"

runs:
  using: 'composite'
  steps:
    - name: call b
      uses: ./.github/actions/b
      with:
        path: /tmp
```

Action b:
```
name: "b"
description: "wrapper to cache"

inputs:
  path:
    description: "Path to cache"
    required: true

runs:
  using: 'composite'
  steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.path }}
          key: 123
```

And a workflow:
```
name: test
on: push

jobs:
  test-job:
    runs-on: test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: ./.github/actions/a
```

The `main` step of the cache sees `path` just fine, but the `post` step of `a` is:
```
Post job cleanup.
Post job cleanup.
Warning: Input required and not supplied: path
```

If I invoke `b` directly from the workflow (rather than nesting it in `a`), everything works as expected, so this seems somehow related to the nesting of composite actions. Any advice would be highly appreciated.

Thanks
