### DISCUSSION TITLE
Scheduled workflow doesn't work at all

### DISCUSSION THREAD

**Discussion by jcubic** [community/community#143327] [Actions] [answered]
### Select Topic Area

Question

### Body

I've created this workflow, schedule in about 10 minutes, so I can test if it actually works:

```
name: Supabase Ping

on:
  schedule:
    - cron: "25 16 * * 1,5"

defaults:
  run:
    working-directory: docs

jobs:
  supabase_ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Ping Supabase cloud
        run: npx ts-node supabase.ts
```

But it didn't run at all:

![Przechwycenie obrazu ekranu_2024-11-01_17-17-43](https://github.com/user-attachments/assets/e1b3afd4-d91c-43e8-98b0-34ebc5cbfab2)

What is wrong, are there any undocumented requirements? Like adding the workflow at specific time before the schedule? Am I missing something?
