### DISCUSSION TITLE
ESP-Home, ESP32 with W5500 Lan Board

### DISCUSSION THREAD

**Discussion by bluhminga** [community/community#143438] [Programming Help]
### Body

Hello,

I'm working with an ESP32-Wroom-32, esp32 node mcu board.

I would also like to use a W5500 board.

I don't know what I've already tried?!

I just can't get it to work. The whole thing doesn't even appear in the Fritzbox.

Compiling works. Installation via WEB over USB.

But the board cannot be reached.

Does anyone have an ESPHome code where the W5500 runs with an ESP32?

### Guidelines

- [X] I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.

**Comment by bluhminga** [comment]
Hello,

I have deactivated WiFi in the code with ##, i.e. two hash marks.
It is no longer red and the compilation is running.
Upload via "https://web.esphome.io/".
It is now running after I re-installed the ESP. So I deleted everything.

```
substitutions:
  name: esphome-web-916f2c
  friendly_name: ESPHome Web 916f2c

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
##improv_serial:

##wifi:
  # Set up a wifi access point
##  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
##captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
##esp32_improv:
  ##authorizer: none

# To have a "next url" for improv serial
web_server:

ethernet:
  type: W5500
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO05
  interrupt_pin: GPIO13
  reset_pin: GPIO14
```
