### DISCUSSION TITLE
Actions can't find my terraform modules (path not found)

### DISCUSSION THREAD

**Discussion by vikramty** [community/community#143558] [Actions]
### Select Topic Area

Question

### Body

I got a simple GitHub actin workflow for creating a terraform resource. I pretty much used the template from [here](https://github.com/Azure-Samples/terraform-github-actions/blob/main/.github/workflows/tf-plan-apply.yml).

Here is my code:
 `
```
jobs:
  terraform-plan:
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: my-module/dev/*.tf
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code main repo
        uses: actions/checkout@v4

      # Install the latest version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Checks that all Terraform configuration files adhere to a canonical format, Will fail the build if not
      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
```
`

And this what its complaining (error):
`
```
Run terraform fmt -check
  terraform fmt -check
  shell: /usr/bin/bash -e {0}
  env:
    ARM_CLIENT_ID: ***
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/terrt83-yett4t5-uu4uyy3y33
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/my-repo-name/my-repo-name/my-module/dev/*.tf'. No such file or directory
```
`

I checked the `actions/checkout@v4` and it is fetching the repo properly. 

Not sure why it still can't see the files/folders from the `working-directory`.

Any help here on what I am missing here?
