### DISCUSSION TITLE
Problem with auto changing JIRA tickets status to cancelled if Dependabot closed the PR has not been merged yet

### DISCUSSION THREAD

**Discussion by janosvajda** [community/community#143607] [Actions]
### Select Topic Area

Question

### Body

I implemented a GitHub workflow that should cancel the Jira ticket status if Dependabot closed and the PR has not been merged a PR.

This is the **auto_cancel_jira yaml** file

```
name: Auto Cancel Jira Ticket on PR Close
env:
  JIRA_BASE_URL: 'https://companyname.atlassian.net'

on:
  workflow_call:

permissions:
  id-token: write # This is required for requesting the JWT
  actions: read   # This is required for action-slack
  packages: read # This is required for private NPM repo access
  contents: write # read required for actions/checkout, write required by dependabot auto merge
  pull-requests: write # required by create jira and dependabot auto merge

jobs:
  cancel-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3.0.1
        env:
          JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: 'Find Jira Issue Key 🔍'
        id: find
        uses: atlassian/gajira-find-issue-key@v3.0.1
        with:
          string: '${{ github.event.pull_request.title }}'
          from: 'branch'
      - name: 'Cancel Jira Issue ❌'
        if: steps.find.outputs.issue != ''
        uses: atlassian/gajira-transition@v3.0.1
        with:
          issue: '${{ steps.find.outputs.issue }}'
          transition: 'Cancelled'

```

and I use this in any our GitHub branches this way:

```
name: Close PR and Call Auto Cancel Jira
on:
  pull_request:
    types:
      - closed  # Trigger this workflow when a PR is closed
jobs:
  cancel-jira-issue:
    name: 'Trigger Auto Cancel Jira ❌'
    if: github.event.action == 'closed' && github.actor == 'dependabot[bot]' && github.event.pull_request.merged == false
    uses: Companyname/companyname-github-actions-templates/.github/workflows/auto_cancel_jira.yml@main
    secrets: inherit
```

The reason why I created this question is that it works fully non consistently. It sometimes cancel the Jira ticket, and sometimes just fully ignores it and nothing happens when I check the actions on the PR. (The Jira ticket number is always in the PR's title).

Have someone experienced the same problem? We think this might be a GitHub issue, but this is just an assumption as we might have not noticed something.

Thank you for the reply.
