### DISCUSSION TITLE
Combining workflow_dispatch and workflow_run when having conditional jobs

### DISCUSSION THREAD

**Discussion by remohammadi** [community/community#143795] [Actions] [answered]
I followed the ["Events that trigger workflows > Running a workflow based on the conclusion of another workflow"](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow) doc and now have something like this in my workflow file:

```yaml
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Blah]
    types:
      - completed

jobs:
  build-and-push-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
 ```
 
If I run the workflow manually, the job will be skipped because of the condition. Is there a way to OR the condition with something that will be True only when the workflow has been called manually?
