### DISCUSSION TITLE
upload-artifact@v4 cannot consume variables from the env field in the path

### DISCUSSION THREAD

**Discussion by NehilDanis** [community/community#144060] [Actions]
### Select Topic Area

Question

### Body

Hello,

I am new to using GitHub actions hence I am not creating a bug report but a question. It might be not a bug but feature. So I built a C++ library with tests and decided to create build and test actions. First I have created these two separately, but then realised I can just use upload ad download artifact, to use the created test executable in the build step during testing, without needing to rebuild.

Below you can see my build-test yml file. I wanted to use BUILD_TYPE as the environment variable, this way I could create separate build and test steps for both debug and release without re-writing the document. While uploading the artifact I have used the file path `package/$BUILD_TYPE/bin/test/`, however the upload artefact always failed until I have removed the environment variable and hardcoding it with Release. Is this how it is supposed to work and I shouldn't use environment variables in the path name, or is this a bug? Because I can use $BUILD_TYPE in the cmake command as you can see below in the yml file.

```yml
name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install python dependencies
        run: |
          pip install -r ${{github.workspace}}/requirements.txt

      - name: Run conan install
        run: conan profile detect && conan install . -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True -sbuild_type=$BUILD_TYPE -of=conan --build=missing

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/conan/build/$BUILD_TYPE/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=ON -B ${{github.workspace}}/build/$BUILD_TYPE -S .

      - name: Build
        run: cmake --build ${{github.workspace}}/build/$BUILD_TYPE -j4

      - name: Package the library
        id: package
        run: |
          cmake --install ${{github.workspace}}/build/$BUILD_TYPE --prefix package/$BUILD_TYPE
          echo "Packing my-lib-package-$BUILD_TYPE completed"

      - name: Debug package directory
        run: |
          echo "Listing contents of package directory:"
          ls -R package/$BUILD_TYPE
        shell: bash

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-lib-package-${{ env.BUILD_TYPE }}
          path: package/$BUILD_TYPE/bin/test/

  # Test Job
  test:
    runs-on: ubuntu-latest
    needs: build # Waits for the build job to complete
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: blur-detection-lib-package-${{ env.BUILD_TYPE }}
          path: package/$BUILD_TYPE/bin/test/

      - name: Run Tests
        run: |
          ./bin/test/test_blur_detection
        working-directory: package/$BUILD_TYPE

```

So once again when I changed the path in upload from `package/$BUILD_TYPE/bin/test/` to  `package/Release/bin/test/`, all worked. I would appreciate any help regarding this issue, if you know anything what I do wrong, or if this is feature! 

Thanks :)
