### DISCUSSION TITLE
doxygen deploy action output is empty

### DISCUSSION THREAD

**Discussion by tomoreilly** [community/community#144023] [Actions]
### Select Topic Area

Question

### Body

I’m attempting to enable github doxygen workflow. [I’m following this guide.](https://github.com/marketplace/actions/doxygen-github-pages-deploy-action)
For now, I want to generate doxygen output only for my feature-newgui branch (not master).
My project has this directory structure:

```
MyProject/
   src/
   qt-documentation/
     doxygen # config file
     html/

```
Doxygen runs and generates expected web page files on my local repo, in MyProject/qt-documentation/html/.

But looking at the github doxygen output, I see that the gh-pages branch is empty, except for a single .nojekyll file.

Looking at the action output logs, doxygen takes about two minutes to run, and log messages seem to be processing source files as expected. The end of the run log:

```
Checking if there are files to commit…

[47544](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47561)/usr/bin/git add --all .

[47545](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47562)/usr/bin/git checkout -b github-pages-deploy-action/sp6ajtsen

[47546](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47563)Switched to a new branch 'github-pages-deploy-action/sp6ajtsen'

[47547](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47564)/usr/bin/git commit -m Deploying to gh-pages from @ dwcaress/MB-System@29a6268ce2fe5f7682f97e261c986f12ca739ad1 🚀 --quiet --no-verify

[47548](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47565)Force-pushing changes...

[47549](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47566)/usr/bin/git push --force ***github.com/dwcaress/MB-System.git github-pages-deploy-action/sp6ajtsen:gh-pages

[47550](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47567)To[ https://github.com/dwcaress/MB-System.git](https://github.com/dwcaress/MB-System.git)

[47551](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47568)   2363e39..996624b  github-pages-deploy-action/sp6ajtsen -> gh-pages

[47552](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47569)Changes committed to the gh-pages branch… 📦

[47553](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47570)Running post deployment cleanup jobs… 🗑️

[47554](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47571)/usr/bin/git checkout -B github-pages-deploy-action/sp6ajtsen

[47555](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47572)Reset branch 'github-pages-deploy-action/sp6ajtsen'

[47556](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47573)/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder

[47557](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47574)/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force

[47558](https://github.com/dwcaress/MB-System/actions/runs/11750718351/job/32739473060#step:2:47575)Completed deployment successfully! ✅

Post Run DenverCoder1/doxygen-github-pages-action@v2.0.0
0s
Complete job
0s

```
So the action run *seems* normal, but there is no output in the gh-pages branch. What could be the reason?

This is my github workflow file:

```
name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - feature-newgui

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: qt-documentation/html
          config_file: qt-documentation/doxyfile
          target_folder: doxyOutput

```
Thanks!
