### DISCUSSION TITLE
Workflow on:release:published did not run when release created

### DISCUSSION THREAD

**Discussion by BSPR0002** [community/community#144165] [Actions]
### Select Topic Area

Question

### Body

I configured my workflow as follow:
```yml
on:
  release:
    types: [published]
  workflow_dispatch:
```
It doesn't run when I create a release in my repository.
- The release was created manually by myself.
- The repository belongs to my organization.
- The workflow runs well with workflow_dispatch.

[yml File](https://github.com/Blue-Sky-Infomation-Factory/Python-Webview2/blob/main/.github/workflows/python-package.yml)
