### DISCUSSION TITLE
Unrecognized named-value: 'secrets'.

### DISCUSSION THREAD

**Discussion by Grsz** [community/community#144145] [Actions]
### Select Topic Area

Question

### Body

I cannot seem to make secrets work in reusable workflows, even when directly passing them down.

Root workflow (simplified):
```
name: CI
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  deploy-api:
    uses: ./.github/workflows/deploy-api-prod.yaml
    secrets:
      REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
      ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
      COOKIES_KEY: ${{ secrets.COOKIES_KEY }}
```

`./.github/workflows/deploy-api-prod.yaml`:
```
name: Deploy API to Production

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        default: eu-west-1
    secrets:
      REFRESH_TOKEN_KEY:
        required: true
      ACCESS_TOKEN_KEY:
        required: true
      COOKIES_KEY:
        required: true



jobs:
  deploy:
    uses: ./.github/workflows/deploy-ecs-service.yaml
    secrets:
      REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
      ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
      COOKIES_KEY: ${{ secrets.COOKIES_KEY }}
    with:
      env: prod
      port: 3005
      ci_role_arn: ${{ vars.CI_ROLE_ARN }}
      aws_region: ${{ inputs.aws_region }}
      ecr_repository_arn: ${{ vars.ECR_ARN }}
      env_vars: |
        NODE_ENV=production
        ENV=prod
        PORT=3005
        AWS_REGION=${{ inputs.aws_region }}
        DOMAIN_NAME=${{ vars.DOMAIN_NAME }}
        REFRESH_TOKEN_KEY=${{ secrets.REFRESH_TOKEN_KEY }}
        ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}
        COOKIES_KEY=${{ secrets.COOKIES_KEY }}
```

Getting error at `secrets.REFRESH_TOKEN_KEY`: Unrecognized named-value: 'secrets'.

`./.github/workflows/deploy-ecs-service.yaml` also has secrets defined under `on.workflow_call`. I cannot figure out the issue, I started out with `secrets: inherit`, and went more and more specific but it seems to have no effect.

There are similar discussions out there where the issue is solved by specifying the secrets at the reusable workflows inputs, but it doesn't help my case.
