### DISCUSSION TITLE
Workflow on release publish doesn't trigger for new releases targeting other branches than main

### DISCUSSION THREAD

**Discussion by PatchaIT** [community/community#144130] [New to GitHub] [answered]
Hi all!

For what I understood, workflows into main branch in .github/workflows folder should be valid also for other branches.
But when I make a release with another branch as target, my "on release publish" workflow doesn't trigger.

Should I put my workflow in each branch I want to use as target for a release?

**Comment by J1Loop** [comment]


**Reply by PatchaIT** [reply]
Seeing you wrote "You could try any of these", I choose the second.
I added
branches:
  - '*'
after
types: [published]

I left it only in main and I didn't put any if into jobs:

It didn't work.

Did you mean instead I should follow all 3 steps?

```yaml
on:
  release:
    types: [published]
    branches:
      - '*'
```

**Reply by PatchaIT** [reply]
Still doesn't work if target is different than main

**Comment by PatchaIT** [comment]
Just tried this, too... didn't work with a target different than main.
(With or without branches)

```yaml
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - '*'
```
