### DISCUSSION TITLE
How to publish my electron app in release?

### DISCUSSION THREAD

**Discussion by mohsen12999** [community/community#144308] [Actions]
### Select Topic Area

Question

### Body

I tried different ways to change the release file but no one put anything on my release page and I only have the source file in the assets.
I tried to use the "Electron Builder Action," but it didn't work.
I use this config and my release action has no errors, but I don't see anything on the release page. 
```yml
name: Release with old way
on: push

jobs:

  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3       
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
```

please help me.
