### DISCUSSION TITLE
Action for Rust Project

### DISCUSSION THREAD

**Discussion by rustor0642** [community/community#144566] [Actions] [answered]
### Select Topic Area

Question

### Body

I am cooking a project with rust and new in Github Actions.
So I need a simple Github Action Template.
Help me!

**Comment by mfm-builder-001** [comment, marked as answer]
You can do that by below steps.
- Create `simple.yml` in `.github/workflows`.
- Add simple ci actions for formatting, lint and building check.
```yml
name: Check Format, Lint and Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Format
        run: cargo fmt --all --check
      - name: Lint
        run: cargo clippy --all-targets
      - name: Build
        run: cargo build --all-targets
       ```
