### DISCUSSION TITLE
Job doesn't start on push to main

### DISCUSSION THREAD

**Discussion by safonovklim** [community/community#144638] [Actions]
### Select Topic Area

Question

### Body

Just noticed that github actions does not run when pushing/merging to main branch (at least on two repositories).
Github status doesn't show any issue https://www.githubstatus.com/

```
name: "CI & CD"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  push:
    branches:
      - main
```

As a workaround, I added manual trigger and kicked off the pipeline manually

```
  workflow_dispatch:
```

Is it just me?
