### DISCUSSION TITLE
New issue form dropdown display odd values, e.g. `{"label"=> value}`

### DISCUSSION THREAD

**Discussion by heitorlessa** [community/community#14481] [Projects and Issues]
Hi everyone,

 I couldn't immediately find an existing discussion so feel free to close if there's any related. I've just tried out the new issue form (great work!) but the dropdown values seem to be getting odd values - is that expected?

![image](https://user-images.githubusercontent.com/3340292/162231942-80369f90-2d13-4b66-93c5-f2b25476c92d.png)

**Snippet**

```yaml
  - type: dropdown
    id: packaging
    attributes:
      label: Packaging format used
      options:
        - label: "Lambda Layers"
        - label: "Serverless Application Repository (SAR) App"
        - label: "PyPi"
      multiple: true
    validations:
      required: true
```
