### DISCUSSION TITLE
GitHub Actions Workflow Fails to Create PR Despite Working Locally (GH CLI & Permissions Issues?)

### DISCUSSION THREAD

**Discussion by njfamirm** [community/community#144831] [Actions]
### Select Topic Area

Question

### Body

Hi everyone

I'm trying to implement a GitHub Actions workflow that automatically updates a repository from a "base" repository. This involves checking for the latest tag in the base repo and creating a pull request in the target repo with the changes. The workflow runs successfully locally within Docker, but fails when running in GitHub Actions. Specifically, the repo can't clone. I suspect a problem with GitHub CLI authentication or permissions within the workflow, despite having set the GH_TOKEN secret.

```yml
name: Update from Base

env:
  BASE_REPO: 'nexim-tech/order-next'

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:
  push:
    branches:
      - next

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Check if this is the base repo
        run: |
          if [ "${{ github.repository }}" == "${{ env.BASE_REPO }}" ]; then
            echo "This is the base repository. Exiting."
            exit 0
          fi

      - name: Run update script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BASE_REPO: ${{ env.BASE_REPO }}
        run: |
          chmod +x .github/update-from-base.sh
          .github/update-from-base.sh
```

```sh
#!/bin/bash

set -Eeuo pipefail
trap "echo '❌ Error'" ERR

log() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*"
}

# Ensure the GH_TOKEN is available
if [ -z "$GH_TOKEN" ]; then
  log "Error: GH_TOKEN is not set. Please set the GH_TOKEN environment variable."
  exit 1
fi

log "Configuring git user"
git config --global user.name "njfamirm-bot"
git config --global user.email "bot@njfamirm.ir"

log "Fetching the latest tag from the base repository"
LATEST_TAG=$(git ls-remote "https://$GH_TOKEN@github.com/$BASE_REPO.git" 'refs/tags/*' | grep -oE 'refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+)?$' | sort -rV | head -n1 | cut -d/ -f3)

log "Checking if the tag $LATEST_TAG already exists in the target repo"
git fetch origin --tags
if git tag -l "$LATEST_TAG" | grep -q "$LATEST_TAG"; then
  log "Tag $LATEST_TAG already exists."
  exit 0
fi

log "Checking if a PR already exists for $LATEST_TAG"
PR_EXISTS=$(gh pr list --base next --head update/$LATEST_TAG --json number --jq '.[0].number')
if [ -n "$PR_EXISTS" ]; then
  log "PR already exists."
  exit 0
fi

# Create a new branch for the update
git checkout -b update/$LATEST_TAG next

log "Merging the latest tag $LATEST_TAG from the base repo"
git fetch "https://$GH_TOKEN@github.com/$BASE_REPO.git" $LATEST_TAG
MERGE_OUTPUT=$(git merge FETCH_HEAD -m "Merge $LATEST_TAG from base repo")
log "Merge output: $MERGE_OUTPUT"
MERGE_CONFLICTED=$(echo "$MERGE_OUTPUT" | grep -c "CONFLICT")

if [ "$MERGE_CONFLICTED" -ne 0 ]; then
  log "Merge conflicts detected, resolving manually"
  git add .
  git commit -m "merge: conflict resolve manually"
fi

log "Pushing changes to the remote repository"
git push origin update/$LATEST_TAG --force

log "Creating a new pull request for $LATEST_TAG"
gh pr create -a @me -f --title "release: $LATEST_TAG" --base next --head update/$LATEST_TAG
```

The error:

```log
Run chmod +x .github/update-from-base.sh
  chmod +x .github/update-from-base.sh
  .github/update-from-base.sh
  shell: /usr/bin/bash -e {0}
  env:
    BASE_REPO: nexim-tech/order-next
    GH_TOKEN: ***
[2024-11-13T10:26:28+0000]: Configuring git user
[2024-11-13T10:26:28+0000]: Setting up GitHub authentication
[2024-11-13T10:26:28+0000]: Fetching the latest tag from the base repository
remote: Repository not found.
fatal: repository 'https://github.com/nexim-tech/order-next.git/' not found
❌ Error
Error: Process completed with exit code 1.
```

thanks
