### DISCUSSION TITLE
Custom workflow and release publication

### DISCUSSION THREAD

**Discussion by KDean-Dolphin** [community/community#145042] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

I have a custom workflow for a fairly complex GitHub Pages deployment. The relevant parts are:

```yaml
name: Build GitHub Pages

on:
  release:
    types:
      - published
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # A bunch of stuff here, all of which results in a website in a "pages" subdirectory.

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload pages directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

For those that are interested, everything here is in the repository at https://github.com/aidc-toolkit/aidc-toolkit.github.io.

The script works fine when triggered by a push to "main". However, when triggered by a release publication, everything appears to succeed but the GitHub Pages site is never actually published (I confirm this by comparing the contents of the generated artifact with the actual site).

After some digging, I determined that the problem was likely in "Settings / Environments / github-pages", which by default has a "Deployment branches and tags" rule set to allow the "main" branch only to be deployed. I added a wildcard tag rule "v*.*.*" to match my version tag format and the UI confirmed that the rule matches my existing tags.

Despite that, the deployment is still not happening on release publication. The deploy-pages action reports success, but nothing actually happens. Rerunning the build and enabling debug logging doesn't add anything useful.

Any thoughts on why this is? Thanks.

**Comment by KDean-Dolphin** [comment]
Upon further reading, it appears I was missing the environment setting:

```yaml
environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}
```

I'll know for certain when I do another release in a day or two, but I expect that will solve it.

**Comment by KDean-Dolphin** [comment]
It didn't work.

To be clear about the conditions:

- When the script is triggered by a push to "main", it works.
- When the script is triggered by a publication release, it appears to work, but the GitHub Pages site is **not** updated.
  - You can tell by looking at https://aidc-toolkit.github.io/overview.html; the "Last updated" should be "20 November 2024", not the prior day's date.
  - You can also tell by downloading the artifact.tar file produced by the upload process; it has the overview.html file with the correct date.
- I set "Deployment branches and tags" in the github-pages environment to "No restriction" and still it failed.

At this point I'm thoroughly convinced that there's something wrong with the action itself or there's something missing in the documentation. Any help would be appreciated.

**Comment by KDean-Dolphin** [comment]
I've narrowed it down to an easily replicable case at https://github.com/KDean-Dolphin/BadPages and [attached here](https://github.com/user-attachments/files/17847475/BadPages.zip). You can see the results at https://kdean-dolphin.github.io/BadPages.

These are the files of interest:

### pages/index.html

A template for the site. It's a simple table that displays the event that triggered the workflow, the reference (branch or tag), the commit, and the date/time of the build.

### nonce

A simple text file used to trigger a requirement to commit and push to GitHub. You can update the file by changing the numeric value at the bottom manually or by using `sed` (instructions are in the file).

### .github/workflows/build-and-publish.yml

This is where the magic happens. I've replicated the file below.

The build environment is set to `github-pages`. In that environment in the repository settings, "Deployment branches and tags" is set to "Selected branches and tags" with a single branch "main" ("Currently applies to 1 branch") and a single tag "v*" ("Currently applies to 1 tag") configured.

The steps are:

1. Checkout the repository. No additional parameters.
2. Patch index.html with attributes from the github object and the build date/time.
3. Configure GitHub Pages. No additional parameters.
4. Upload GitHub Pages content in preparation for deployment. To best simulate my production problem, the content is taken from the "pages" folder.
5. Deploy to GitHub Pages.

If you look at the "Actions" tab of the repository, you will see that two actions have been run. At the bottom is the initial commit, which is a push to "main" event. The one above that is the v1 release publication. That should be the current version of the site. However, if you look at the site, you will see the content from the push event, not from the release event. When I download the github-pages.zip file from the release publication run, the index.html is what I expect it to be (i.e., it shows the release event and tag, not the push event and branch as displayed on the site).

```yaml
name: Build and publish to GitHub Pages

on:
  release:
    types:
      - published
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout default repository
        uses: actions/checkout@v4

      - name: Patch index.html
        run: |
          sed -i -e "s/EVENT/${{ github.event_name }}/g" pages/index.html
          sed -i -e "s/REF/${{ github.ref_name }}/g" pages/index.html
          sed -i -e "s/COMMIT/${{ github.sha }}/g" pages/index.html
          sed -i -e "s/DATE_TIME/`date`/g" pages/index.html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload pages directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
