### DISCUSSION TITLE
When using a custom autograding.json grades are not showed in classroom

### DISCUSSION THREAD

**Discussion by mmabas77** [community/community#145152] [GitHub Education]
### Hi everyone,

![image](https://github.com/user-attachments/assets/57d6b6d5-31c7-4485-938b-6af9e6bc5ba4)

![image](https://github.com/user-attachments/assets/67ebc3e4-2fb2-400d-82d6-3e7104b35992)

- autograding.json

````
{
  "tests": [
    {
      "name": "Unit Tests (Deposit_ShouldIncreaseBalance)",
      "setup": "",
      "run": "DOTNET_CLI_HOME=/home/runner dotnet test --filter TestGroup=Deposit_ShouldIncreaseBalance",
      "input": "",
      "output": "",
      "comparison": "included",
      "timeout": 1,
      "points": 1
    },
    {
      "name": "Unit Tests (Withdraw_ShouldDecreaseBalance_WhenSufficientFunds)",
      "setup": "",
      "run": "DOTNET_CLI_HOME=/home/runner dotnet test --filter TestGroup=Withdraw_ShouldDecreaseBalance_WhenSufficientFunds",
      "input": "",
      "output": "",
      "comparison": "included",
      "timeout": 1,
      "points": 1
    },
    {
      "name": "Unit Tests (Withdraw_ShouldNotAllowOverdraft)",
      "setup": "",
      "run": "DOTNET_CLI_HOME=/home/runner dotnet test --filter TestGroup=Withdraw_ShouldNotAllowOverdraft",
      "input": "",
      "output": "",
      "comparison": "included",
      "timeout": 1,
      "points": 1
    },
    {
      "name": "Unit Tests (ConcurrentDepositsAndWithdrawals_ShouldMaintainCorrectBalance)",
      "setup": "",
      "run": "DOTNET_CLI_HOME=/home/runner dotnet test --filter TestGroup=ConcurrentDepositsAndWithdrawals_ShouldMaintainCorrectBalance",
      "input": "",
      "output": "",
      "comparison": "included",
      "timeout": 1,
      "points": 1
    },
    {
      "name": "Unit Tests (ConcurrentOperations_ShouldBeThreadSafe)",
      "setup": "",
      "run": "DOTNET_CLI_HOME=/home/runner dotnet test --filter TestGroup=ConcurrentOperations_ShouldBeThreadSafe",
      "input": "",
      "output": "",
      "comparison": "included",
      "timeout": 1,
      "points": 1
    }
  ]
}
````

- classroom.yml

````
name: Autograder

on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Generate autograding.json
      run: dotnet run --project ./.github/classroom/GenerateAutograding -- -e ClassroomTemplate -p 5 -o ./.github/classroom/autograding.json
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_PAT }}
    - name: Autograding
      uses: classroom-resources/autograding@v1
      with:
        token: ${{ secrets.CLASSROOM_PAT }}

````
