### DISCUSSION TITLE
Create release fails beacuse of permissions even though i has permissions

### DISCUSSION THREAD

**Discussion by JaRoLoz** [community/community#145131] [Actions]
### Select Topic Area

Bug

### Body

Hi I was writting a github action to automate the release of binaries, and it keeps failing when creating a new release because of `Error: Resource not accessible by integration` although i have given ite permission in the repo settings and in the .yml file.
This is my workflow file:
```yml
name: Upload Release Assets
on:
  push:
    tags:
    - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  upload-release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # by default only the linux target is installed
      - name: Install windows target
        run: |
          sudo apt-get install -y mingw-w64
          rustup target add x86_64-pc-windows-gnu

      - name: Build jade
        run: |
          RUSTFLAGS=-Awarnings
          cargo build --verbose --release
          cargo build --verbose --release --target x86_64-pc-windows-gnu
          zip jade_linux_x86_64.zip target/release/jade
          zip jade_windows_x86_64.zip target/x86_64-pc-windows-gnu/release/jade.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Linux Release
        id: upload-release-linux 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./jade_linux_x86_64.zip
          asset_name: jade_linux_x86_64.zip
          asset_content_type: application/zip

      - name: Upload Windows Release
        id: upload-release-windows 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./jade_windows_x86_64.zip
          asset_name: jade_windows_x86_64.zip
          asset_content_type: application/zip
```
![image](https://github.com/user-attachments/assets/ce49dde7-c77e-4353-9c55-b5627ce2c213)
![image](https://github.com/user-attachments/assets/c2d9b9b3-3bde-43fc-9f8b-f9dd5f899129)
