### DISCUSSION TITLE
deploy-pages fails despite artifact name being right

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#145342] [Actions] [answered]
### Select Topic Area

Question

### Body

For whatever reason did a GitHub Action I made to deploy to GitHub Pages not properly execute.

Here is the action file:
```yaml
name: Publish wiki

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/wiki.yml'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  buildSite:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Update Pip and install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Build Site
        run: mkdocs build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        id: deployment
```
Now, the step that is failing is the last one, reporting it couldn't find any artifact, despite the previous step running perfectly fine, resulting in a `github-pages.zip` artifact being uploaded... Any idea what goes wrong here?

The failed run can be found here: https://github.com/Andre601/OneVersionRemake/actions/runs/11978851004/job/33399745418
