### DISCUSSION TITLE
actions/labeler ignores negation

### DISCUSSION THREAD

**Discussion by ibis-hdl** [community/community#145424] [Actions]
### Select Topic Area

Question

### Body

I tried v5 of [actions/labeler](https://github.com/actions/labeler) with this workflow:

```
name: 'Pull Request Labeler'
on:
  - pull_request_target
jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
``` 
and `labeler.yml` with e.g. (not all are shown):

```
...
python:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'
      - '**/*.py.in'
      - 'requirements.txt'
      - 'py_requirements.txt'
    - all-globs-to-all-files:
      - '!conanfile.py'

doc:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'doc/**'
      - 'doc_ng/**'
      - '**/*.{md,rst,txt}'
      - '**/doxyfile.in'
      - '**/*.dot'
    - all-globs-to-all-files:
      - '!**/CMakeLists.txt'
      - '!requirements.txt'
      - '!py_requirements.txt'
...     
``` 
but the labels for documentation and python accoured even they shouldn't. Did I misunderstand globbing and syntax? How to get it right?
