### DISCUSSION TITLE
Commit History Overwritten After Running GitHub Actions Workflow

### DISCUSSION THREAD

**Discussion by n8fury** [community/community#145537] [Actions]
### Select Topic Area

Question

### Body

Hi everyone,

I recently ran a GitHub Actions workflow on my repository [n8fury/n8fury](https://github.com/n8fury/n8fury) to generate a snake animation, but after the workflow executed, the commit history of my main branch was completely overwritten.

Previously, the repository had approximately 1300+ commits, but now it shows only 1 commit, and the entire history seems to be lost.

Here’s the YAML file I used in the workflow:

```
name: Generate snake animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
```

What I’ve Tried:

- Checked the Commits page on the repository – only the single latest commit is visible.
- Attempted to find forks or collaborators with the previous commit history, but none exist.
- Contacted GitHub Support but haven’t received a response yet.

Question:

- Is there any way to recover the previous commit history after this kind of overwrite?
- Has anyone encountered a similar issue, and if so, how did you resolve it?
- Any advice or guidance would be greatly appreciated. This is very important for my work, and I’m hoping there’s a way to recover the lost history.

Thanks in advance!
