### DISCUSSION TITLE
How to configure GitHub Actions to trigger create and push events exclusively for branch creation and future updates?

### DISCUSSION THREAD

**Discussion by iekdosha** [community/community#145532] [Actions]
### Select Topic Area

Question

### Body

I have this condition on my workflow:
```yml
on:
  push:
    branches:
      - '**'
  create:
    branches:
      - 'release/[0-9]+.[0-9]+'
```

When I create a branch named something like `release/1.2` I want only one pipeline triggered with `create` event, and future pushes to this branch will trigger with `push`.\
Basically push and create should be exclusive like so:

|  | `event_name=create` workflow | `event_name=push` workflow |
|---|---|---|
| Branch created | V | X |
| Push to existing branch | X | V |

I do not want to put conditions on jobs, I need the workflow to not even start.\
Is this possible?

Thanks.
