### DISCUSSION TITLE
Docker cache layer takes multiple times to extract

### DISCUSSION THREAD

**Discussion by davidshen84** [community/community#145614] [Actions]
### Select Topic Area

Question

### Body

Hi,

I have a workflow that builds multi-platform docker images. The build step for one architecture looks like this:

*used actions*
- docker/setup-buildx-action@v3
- docker/build-push-action@v6

```yaml
    - id: build
      uses: docker/build-push-action@v6
      with:
        labels: ${{ inputs.labels }}
        context: ${{ inputs.build_context }}
        file: ${{ inputs.build_context }}/${{ inputs.dockerfile }}
        platforms: ${{ inputs.platform }}
        build-args: ${{ inputs.build_args }}
        secrets: |
          "github_actor=${{ inputs.package_read_actor }}"
          "github_token=${{ inputs.package_read_token }}"
        cache-to: type=gha,mode=max,scope=${{ inputs.github_actor }}-${{ inputs.image_name }}-${{ inputs.platform }}
        cache-from: type=gha,scope=${{ inputs.github_actor }}-${{ inputs.image_name }}-${{ inputs.platform }}
        outputs: type=image,name=${{ inputs.image_repository }},push-by-digest=true,name-canonical=true,push=${{ inputs.push }}
```

After runnig the workflow several times, I noticed this behaviour:

For most unchanged layers, I got logs like this:

```
#10 [builder 5/8] COPY [my-csharp.csproj, my-csharp.csproj]
#10 CACHED
```

But for the layer that used to restore dotnet nuget packages, I got one **CACHED** log and multiple extraction log blocks. The extraction actions take most of the time. I understand the cached layers are stored in remote and need to be downloaded and extracted. But whey multiple times? Is there a way to make it more efficient?

```
#14 [builder 6/8] RUN dotnet restore "my-csharp.csproj" --arch amd64
#14 CACHED

#14 [builder 6/8] RUN dotnet restore "my-csharp.csproj" --arch amd64
#14 sha256:8a0b18dba330ee263a0c13b14a4f2e01753095fb89688a0a8121f9bebd302f53 525B / 525B 0.0s done
...
#14 sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B done
#14 extracting sha256:da9db072f522755cbeb85be2b3f84059b70571b229512f1571d9217b77e1087f
#14 sha256:65[500](https://github.com/my-company/actions/runs/12023876425/job/33518478655#step:3:517)cb04f0681c314bbb1e3be9deb2a84cd7e261a6c33ac6430aa7e4d25b234 136.69kB / 136.69kB 0.0s done
#14 sha256:c10a5e3165da04769cb6d7789c7036f269d70929ba7d5f6016859e3c08f7353c 10.31kB / 10.31kB 0.0s done
...
#14 sha256:84abf7b06b81b43c4326da4c8212457df9c0ff474f93ed92b4661b3c53277dd2 7.34MB / 11.07MB 0.2s
#14 sha256:[508](https://github.com/my-company/reop/actions/runs/12023876425/job/33518478655#step:3:525)5c6089d2cb346fe357f05b75bece9492aa9f84ad1d28aa988fc13cd6dd267 28.09MB / 174.17MB 0.3s
#14 sha256:84abf7b06b81b43c4326da4c8212457df9c0ff474f93ed92b4661b3c53277dd2 11.07MB / 11.07MB 0.2s done
#14 sha256:3203231479f742c7a6cef1e5a9cd12c446cf1205ebbf48e860378f83ad8cee77 959B / 959B 0.0s done
#14 sha256:6c86735894df3eef4bfd8c540b01142934e09f784e316002bae775d7e9a360fd 3.30MB / 3.30MB 0.1s done
#14 extracting sha256:da9db072f522755cbeb85be2b3f84059b70571b229[512](https://github.com/my-company/repo/actions/runs/12023876425/job/33518478655#step:3:529)f1571d9217b77e1087f 0.5s done
#14 sha256:4603c44cb2aa80e3f0de90676587f40a4c96a71200474a95bd2ed3c68aa3fe29 42.76MB / 476.30MB 0.5s
#14 sha256:5085c6089d2cb346fe357f05b75bece9492aa9f84ad1d28aa988fc13cd6dd267 40.89MB / 174.17MB 0.5s
#14 sha256:f6f383d2d2c2b7f0ca578d2d4fc3e40bf28b8694ffc3f3c7cf21108437e70c56 5.15MB / 32.27MB 0.2s
#14 extracting sha256:6c86735894df3eef4bfd8c540b01142934e09f784e316002bae775d7e9a360fd
...
#14 DONE 8.2s

#14 [builder 6/8] RUN dotnet restore "my-csharp.csproj" --arch amd64
#14 extracting sha256:31cd3bb37985c58a18a09398f574ecd195c687c99b1e0b18baf12a9de0d53ce7
#14 extracting sha256:31cd3bb37985c58a18a09398f574ecd195c687c99b1e0b18baf12a9de0d53ce7 0.5s done
#14 extracting sha256:35a8a3aa0a04a9760335418615951eec128492d464bf4fe736193400d3365c4c
...
#14 DONE 13.9s

#15 [builder 7/8] COPY . .
#15 DONE 2.8s
```

Thanks
