### DISCUSSION TITLE
workflow_run not triggering

### DISCUSSION THREAD

**Discussion by grzegorz-roboflow** [community/community#145846] [Actions]
### Select Topic Area

Question

### Body

I have below workflow:

```yml
name: w1

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run_w1:
    runs-on:
      labels: depot-ubuntu-22.04-8
      group: public-depot
    timeout-minutes: 15
    steps:
      (...)
```

This workflow was committed to main on our repository.
I already had some other workflows that I wanted to modify so they are executed only if the `w1` is successful. These workflows are already specified in branch protection rules. They were originally executed on `pull_request` and `push`, in new branch I changed them to be executed on `workflow_run` like below:

```yml
name: UNIT TESTS

on:
  workflow_run:
    workflows: [w1]
    types: [completed]
  workflow_dispatch:

jobs:
  build-and-test:
    if: ${{ github.event.workflow_run.conclusion == "success" }}
    runs-on:
      labels: depot-ubuntu-22.04-4
      group: public-depot
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      (...)
```

When I push to branch, the `w1` workflow executes and results in success, however `UNIT TESTS` workflow (which, as I understand, should be triggered upon completion of `w1` workflow) is never triggered (it sits in `Expected — Waiting for status to be reported` state). I have gone through [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run) and also found [this question](https://github.com/orgs/community/discussions/25288) and I think I have setup everything correctly, but it seems I'm missing something, would appreciate any hints.
