### DISCUSSION TITLE
Cannot request PR review from a team that has organizational access to the repo

### DISCUSSION THREAD

**Discussion by aqeelat** [community/community#145963] [Pull Requests]
### Select Topic Area

Bug

### Body

I was trying to setup dependabot.yaml, but when I tried to add the devops team as a reviewer to docker dependabot updates, I get the following error:

> Dependabot tried to add @my-org/devops as a reviewer to this PR, but received the following error from GitHub:
> 
> ```
> POST https://api.github.com/repos/my-org/my-repo/pulls/15/requested_reviewers: 422 - Reviews may only be requested from collaborators. One or more of the teams you specified is not a collaborator of the my-org/my-repo repository. // See: https://docs.github.com/rest/pulls/review-requests#request-reviewers-for-a-pull-request
> ```

I think this is a bug because the team do actually have maintainer access to all repos in the organization, which makes them collaborators as well.

our dependabot.yaml:
```yaml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-updates:
        patterns:
          - "*"
    reviewers:
      - "fathom-io/backend"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "fathom-io/devops"
```
