### DISCUSSION TITLE
Using local actions in actions

### DISCUSSION THREAD

**Discussion by worc4021** [community/community#145935] [Actions]
Do local actions in actions work for anyone?

Hello,

I've been playing with an action that based on the os in which it runs should set a toolchain up accordingly. What I tried to do was to put the respective actions into two separate files `.github/actions/unix/action.yml` and `./github/actions/windows/action.yml` and then top level I have an `action.yml` that has conditional `uses` to the local folders. The setup scripts for the toolchain are bash and batch files so I wanted to go with composite style actions, according to the [docs](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsstepsuses) I should be able to point to actions within the action using `uses` and a local path. When I try this though I get 

```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/GKlib/GKlib/.github/actions/unix'. Did you forget to run actions/checkout before running your local action?
```

I tried a bunch of variations but none that actually got any further than this. Do we have an example of local actions working inside of other actions? What am I messing up here?

**Comment by GabJuarez** [comment]
Ah, I see what you're trying to do! Unfortunately, composite actions in GitHub Actions currently don't support nested uses statements for local actions. This means you can't directly reference ./github/actions/unix or ./github/actions/windows from within another composite action.

The error you're seeing happens because when the runner tries to resolve the uses: ./path/to/local/action, it doesn't work within a composite action context. Even though this works fine in workflows, it’s not supported for local actions within another action.

Option 1: Move All Logic to the Main Composite Action
Instead of splitting the setup scripts into separate actions (unix and windows), you could move everything into the top-level composite action (action.yml). Use if conditionals in the run steps to handle OS-specific logic:

```
runs:
  using: "composite"
  steps:
    - name: Setup on Unix
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: ./github/actions/unix/setup.sh

    - name: Setup on Windows
      if: runner.os == 'Windows'
      run: ./github/actions/windows/setup.bat
``` 
Option 2: Keep Them as Separate Actions, but Use Them in the Workflow
If you really want to keep unix and windows as separate actions, you can call them directly from your workflow instead of nesting them inside another composite action:
```
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup on Unix
        if: runner.os != 'Windows'
        uses: ./github/actions/unix

      - name: Setup on Windows
        if: runner.os == 'Windows'
        uses: ./github/actions/windows

```

**Reply by worc4021** [reply]
Thank you for your answer. I started from something along the lines of your option 1. I found that they cannot coexist if we need an output. So if both basically set up a toolchain and then generate a variable e.g. `toolboxpath`. Then I would have something along the lines:
```
outputs:
  toolboxpath:
    description: Path to my widget
    value: ${{ steps.publishpath.outputs.toolboxpath }}
runs:
  using: "composite"
  steps:
  - ...
  - if: runner.os == 'Windows' 
    id: publishpath
    [...]
  - if: runner.os != 'Windows'
    id: publishpath
    [...]
```
But then it complains that the `id` appears multiple times. That's why I thought I could potentially hide it in a separate sub-action to obfuscate the other `id` away.
