### DISCUSSION TITLE
Missing `workflows` permission error when pushing a tag to a release version

### DISCUSSION THREAD

**Discussion by dtvn-duytq7** [community/community#146011] [Actions]
### Select Topic Area

Question

### Body

I created a Github Actions workflow to support attaching a tag named stable to a specific release version.
When I executed it, a permissions error appeared:

```
 ! [remote rejected] stable -> stable (refusing to allow a GitHub App to create or update workflow `.github/workflows/abc.yaml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/duytq/example-repo'
Error: Process completed with exit code 1.
```

It is worth noting that this error only occurs with releases that have been tagged stable in the past, while releases that have never been tagged stable before are always pushed successfully.

Workflow example:

```
jobs:
  stable-tag-release:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.repository }}
      - name: Release stable tag to ${RELEASE_VERSION}
        run: |
            git tag -f stable "${RELEASE_VERSION}"
            git push origin stable -f
```
