### DISCUSSION TITLE
How to enforce Pull Requests before pushing but disable this ruleset during CI?

### DISCUSSION THREAD

**Discussion by jtuchel** [community/community#146089] [Actions]
### Select Topic Area

Question

### Body

Given a public repository with a strong restriction. The ruleset requires pull requests before pushing to the main branch. Even the repository owner is not able to bypass these rules.

Given a release workflow that should modify the apps version number and push it ( skipping CI )

    name: Release
    
    on:
      push:
        branches:
          - 'main'
    
    permissions:
      contents: write
      packages: write
    
    jobs:
      release:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
    
          # ...
    
          - name: Create new version
            run: |
              # ... Modify files here
              git add .
              git commit -m "chore: bump package version to ${{steps.get_next_version.outputs.version}} [skip ci]"
              git push

Now the system gets in trouble because it's not able to push anymore. The workflow fails with the error

> remote: error: GH013: Repository rule violations found for
> refs/heads/main.         remote: - Changes must be made through a pull
> request.

which is obvious. How did you guys solve this problem?

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by SajanGhimire1** [comment]
Hi @jtuchel,

The issue occurs because GitHub’s branch protection rules are enforcing pull requests even for actions performed by the repository owner. This happens because the repository is configured to require pull requests before pushing to the main branch, which blocks the workflow's git push operation.
The workflow is attempting to push directly to the main branch, violating the protection rules. This happens even though you're using [skip ci], which is meant to skip the CI jobs, not bypass the push restriction.

To bypass this restriction during CI, you can modify your workflow as follows:
-Use the **GITHUB_TOKEN** for pushing & Ensure you are pushing with **[skip ci]** in the commit message

**workflow**:
```
name: Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ... other steps

      - name: Create new version
        run: |
          # Modify files here
          git add .
          git commit -m "chore: bump package version to ${{steps.get_next_version.outputs.version}} [skip ci]"
          git push https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:main

```
By using GITHUB_TOKEN, the CI will have the necessary permissions to bypass the branch protection rules when pushing.
The [skip ci] commit message will ensure CI is skipped for this particular commit, but the push will go through.
