### DISCUSSION TITLE
BUG: Github Actions concurrency group killing waiting jobs

### DISCUSSION THREAD

**Discussion by n4ch04** [community/community#146149] [Actions]
### Select Topic Area

Bug

## Current behavior

Github Action with concurrency group set at job level depending on a strategy matrix that spans depending on another workflow input, i.e.:
```
concurrent-job:
    name: Concurrent job
    needs: [ job1 ]
    runs-on: ubuntu-latest
    concurrency:
          group: matrix-group
    strategy:
      matrix:
        changed_dir: ${{ fromJSON(needs.job1.outputs.changed_dirs) }}
    steps:
      - name: Fancy concurrent things
        working-directory: ${{ matrix.changed_dir }}
        run: |
          some command
```
Then, let's assume that there are 3 inputs to the matrix strategy. the process would be as follows:
1 - First job starts, check there is no other job of the same group running and start execution
2 - Second job starts, realizes that there is an already executing job of the same group running, so it waits
3 - Third job starts, there is job 1 still executing, and job 2 waiting, so it kills job 2 and waits

If the number of concurrent jobs increases the behavior is the same, the last one kills the one that is waiting and takes its place.

Same behavior would apply for concurrency at workflow level

## Expected behavior

Let's assume that there are 3 inputs to the matrix strategy. the process would be as follows:
1 - First job starts, check there is no other job of the same group running and start execution
2 - Second job starts, realizes that there is an already executing job of the same group running, so it waits
3 - Third job starts, there is job 1 still executing, and job 2 waiting, so it waits for job 1 and job 2 to finish

Same for concurrency at workflow level
