### DISCUSSION TITLE
Action not executed and does not generate error after push

### DISCUSSION THREAD

**Discussion by joaonivaldo** [community/community#146282] [Actions]
### Select Topic Area

Question

### Body

Hello, I have an action that is executed when I PUSH the develop branch and another action for the Main branch. Both are identical, only changing the values ​​of the variables. The action for the Main branch executes normally and the one for the DEVELOPE branch simply does nothing and does not generate an error. Could someone help me and see what is happening? Thanks.
```
on:
  push:
    branches:
      - develop
name: 🚀 Envio para o ambiente de desenvolvimento
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4.2.2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.develop_ftp_host }}
          username: ${{ secrets.develop_ftp_user }}
          password: ${{ secrets.develop_ftp_password }}
          server-dir: public_html/
```

![image](https://github.com/user-attachments/assets/73e037f1-96ed-4075-abcb-07b497e7c8bb)
