### DISCUSSION TITLE
`if` condition fails to execute

### DISCUSSION THREAD

**Discussion by rhys-vdw** [community/community#146209] [Actions] [answered]
### Select Topic Area

Question

### Body

Unsure if this is a bug or user error. I have these steps in a workflow:

```yaml
      - name: Echo for debugging
        run: |
          cat << EOF
          toJson(needs):
          ${{ toJson(needs) }}

          needs.build-windows.result: ${{ needs.build-windows.result }}
          needs.build-macos.result: ${{ needs.build-macos.result }}
          inputs.merge_and_tag: ${{ inputs.merge_and_tag }}
          EOF

      - uses: ./.github/actions/configure-git

      # If no builds failed, tag version number and merge the branch into master
      - name: Tag and merge branch
        if: always() && inputs.merge_and_tag == 'true' && needs.build-windows.result == 'success' && needs.build-macos.result == 'success'
        run: |
          ..
```

![image](https://github.com/user-attachments/assets/e32adf8c-f143-4c33-990d-1905e8fc0609)

Why is the step "Tag and merge branch" being skipped?

Previously I preferred to format the condition like this, which I believe should be the same (it also failed).

```yaml
        if: |
          inputs.merge_and_tag == 'true' &&
          needs.build-windows.result == 'success' &&
          needs.build-macos.result == 'success'
```

What am I doing wrong? Here is the full workflow file:

https://gist.github.com/rhys-vdw/54255cdb13ee902158411b136907d347#file-release-steam-yml-L160-L177
