### DISCUSSION TITLE
Sequential jobs are skipped with no condition

### DISCUSSION THREAD

**Discussion by zwang1-godaddy** [community/community#146429] [Actions]
### Select Topic Area

Bug

### Body

Hi team, my workflow runs all jobs defined inside. 
```
name: Build and Deploy

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: path-to/test-lint.yml@main
    with:
      update_coverage: 'true'
      coveragePath: 'coverage/lcov.info'
      command: 'npm run build --if-present && npm run lint && npm run coverage-ci'

  build:
    name: Build
    needs: test
    uses: path-to/spa-build.yml@main
    with:
      build_type: 'single'

  non-prod-deploy:
    name: dev and test deploy
    needs: build
    uses: path-to/spa-non-prod-deploy.yml@main
    with:
      deploy_type: 'single'
      environment: 'dev'

  prod-deploy:
    needs: non-prod-deploy
    if: ${{ github.ref == 'refs/heads/main' }}
    name: production deploy
    uses: path-to/spa-prod-deploy.yml@main
    with:
      deploy_type: 'single'
      environment: 'prod'
```

Currently, I added pr-size check steps at the beginning all jobs after test are skipped.

```
name: Build and Deploy

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  get-pr-info:
    name: PR Info for non-main branch
    if: ${{ github.ref_name != 'main' }}
    runs-on:
      labels: ['self-hosted', 'xyz']
    outputs:
      pr_number: ${{ steps.get-pr-number.outputs.pr_number }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get PR Number
        id: get-pr-number
        uses: actions/github-script@v6.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const ref = context.ref;
            console.log(`Full Ref: ${ref}`);
            const branchName = ref.startsWith('refs/heads/') ? ref.replace('refs/heads/', '') : '';
            console.log(`Owner: ${owner}, Repo: ${repo}, Branch: ${branchName}`);

            if (!branchName) {
              throw new Error('Branch name could not be determined.');
            }

            const prList = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: `${owner}:${branchName}`
            });

            if (prList.data.length > 0) {
              const prNumber = prList.data[0].number.toString();
              console.log(`pr_number=${prNumber}`); // For logging purposes
              console.log(`echo "pr_number=${prNumber}" >> $GITHUB_OUTPUT`);
              require('child_process').execSync(`echo "pr_number=${prNumber}" >> $GITHUB_OUTPUT`);
            } else {
              console.log('No PR found for this branch.');
              console.log('echo "pr_number=" >> $GITHUB_OUTPUT');
              require('child_process').execSync('echo "pr_number=" >> $GITHUB_OUTPUT');
            }

  pr-size:
    name: PR Size
    needs: get-pr-info
    if: ${{ needs.get-pr-info.outputs.pr_number != '' }}
    uses: path-to/pr-size.yml@main
    with:
      issue_number: ${{ needs.get-pr-info.outputs.pr_number }}
      owner: ${{ github.repository_owner }}
      repo: ${{ github.event.repository.name }}

  check-pr-size-bypass:
    name: Check for PR Size Bypass
    needs: pr-size
    if: ${{ always() && needs.pr-size.result == 'failure' }}
    runs-on:
      labels: ['self-hosted', 'xyz']
    steps:
      # Check out code from GitHub becuase Git repository isn't available in the bypass-check workflow
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Commit Message for Bypass
        id: bypass-check
        run: |
          if [[ "$(git log -1 --pretty=%B)" == bypass-pr-size* ]]; then
            echo "Bypass detected. Continuing workflow."
            exit 0
          else
            echo "Bypass not detected. Failing workflow."
            exit 1
          fi

  test:
    name: Test
    needs: check-pr-size-bypass
    if: ${{ always() && (needs.check-pr-size-bypass.result == 'success' || needs.check-pr-size-bypass.result == 'skipped') }}
    uses: path-to/test-lint.yml@main
    with:
      update_coverage: 'true'
      coveragePath: 'coverage/lcov.info'
      command: 'npm run build --if-present && npm run lint && npm run coverage-ci'

  build:
    name: Build
    needs: test
    # if: ${{ always() && (needs.test.result == 'success') }} unless I "force this to run"
    uses: path-to/spa-build.yml@main
    with:
      build_type: 'single'

  non-prod-deploy:
    name: dev and test deploy
    needs: build
    # if: ${{ always() && (needs.build.result == 'success') }} unless I "force this to run"
    uses: path-to/spa-non-prod-deploy.yml@main
    with:
      deploy_type: 'single'
      environment: 'dev'

  prod-deploy:
    needs: non-prod-deploy
    # if: ${{ always() && (needs.non-prod-deploy.result == 'success') && github.ref == 'refs/heads/main' }} unless I "force this to run"
    name: production deploy
    uses: path-to/spa-prod-deploy.yml@main
    with:
      deploy_type: 'single'
      environment: 'prod'
```

I've:
1. Check the Job Identifiers and Names
2. Confirm Looking at the Correct Workflow Run
3. not Runner or Permissions Issues
4. YAML/Formatting is valid
5. no Manual Approval required in between those jobs

In a straightforward scenario: `pr-size` runs and passes, `check-pr-size-bypass` doesn't need to run because `pr-size` passed, `test` runs and completes successfully (green check), and then `build` should run automatically. 
Issue: when `pr-size` passes, `test` runs and completes successfully (green check) but `build` is skipped
