### DISCUSSION TITLE
I've received as HTTP 404 error when trying to run the SBOM-Tool

### DISCUSSION THREAD

**Discussion by rfalanga** [community/community#146530] [Actions]
### Select Topic Area

Question

### Body

I'm trying to gain experience at using the SBOM-Tool. I've been following [this link](https://github.com/microsoft/sbom-tool/blob/main/docs/setting-up-github-actions.md), however I kept getting errors that didn't make sense to me. So, I then tried to use GitHub Copilot to help me with it. That made several changes to my workflow file. I then ran it again, and now I'm getting a HTTP 404 error:

> Run wget https://github.com/microsoft/sbom-tool/releases/download/v1.0.3/sbom-tool-linux-x64
--2024-12-07 16:05:39--  https://github.com/microsoft/sbom-tool/releases/download/v1.0.3/sbom-tool-linux-x64
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-12-07 16:05:39 ERROR 404: Not Found.
>
> Error: Process completed with exit code 8.

The code snippet from my YAML file is here:

```yaml
- name: Download SBOM Tool
  run: |
	wget https://github.com/microsoft/sbom-tool/releases/download/v1.0.3/sbom-tool-linux-x64
	chmod +x sbom-tool-linux-x64
```

I'm out of my deepth now, so I need help, please.
