### DISCUSSION TITLE
All CI actions running twice with non-deterministic outcomes

### DISCUSSION THREAD

**Discussion by ghost** [community/community#146554] [Actions]
### Select Topic Area

Question

### Body

I had this same config working perfectly in my last project at my last company. Now that I'm using it on a new repo (a Rails 7 app), every single push results in two runs of everything setup in `ci.yml`. One of these runs passes, the other run fails. Sometimes they both fail even when I've changed nothing in `ci.yml`. 

Is GitHub just having some issues today? I no longer have access to the project I know this was working in. 

```
name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: alfalfa_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports: ["5432:5432"]
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
          DB_HOST: localhost
        run: bin/rails db:test:prepare test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

```
