### DISCUSSION TITLE
Choose runner for Dependabot actions

### DISCUSSION THREAD

**Discussion by mdesco-crgl** [community/community#146754] [Actions]
### Select Topic Area

Question

### Body

I am trying to find a way to modify the Dependabot Updates workflow configuration file. I have several self-hosted runners for various purposes, but when this workflow is ran, it chooses any of them. This causes the action to fail on ones to that do not have Docker. I want to be able to specify to run the dependabot actions ONLY on Github hosted runners.

**Comment by harmeetsingh11** [comment]
Hi @mdesco-crgl 

To modify the **Dependabot Updates** workflow configuration to ensure that it only runs on GitHub-hosted runners, you can specify the `runs-on` attribute with a value that targets GitHub-hosted runners exclusively.

Here’s how to update your workflow file:

1. **Edit the workflow configuration**: Update the `runs-on` field to specify GitHub-hosted runners, such as `ubuntu-latest` (or other specific hosted runners like `windows-latest` or `macos-latest` depending on your environment).
   
   For example:
   ```yaml
   jobs:
     dependabot:
       runs-on: ubuntu-latest  # Only run on GitHub-hosted runners
   ```

2. **Avoid using self-hosted runners**: Make sure that your `runs-on` field doesn't reference any self-hosted runner labels that might cause the action to run on your self-hosted runners. Self-hosted runners can be targeted using labels, so be sure not to include any labels related to your self-hosted runners.

3. **Ensure Dependabot's configuration**: Dependabot workflows may also have specific configurations in the `dependabot.yml` file. Make sure that it’s configured to not interfere with self-hosted runners, although specifying the `runs-on` setting in your main workflow file is usually sufficient.

### Example Workflow:
```yaml
name: 'Dependabot Update'

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly

jobs:
  dependabot:
    runs-on: ubuntu-latest  # Forces the job to run on GitHub-hosted runners
    steps:
      - uses: actions/checkout@v2
      - uses: dependabot/dependabot-core@v2
```
For more details on configuring workflows and using self-hosted versus GitHub-hosted runners, you can refer to GitHub's official documentation on [using GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners) and [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners).
