### DISCUSSION TITLE
actions/checkout@v3 fails on Ubuntu 18.04 after upgrading runners to Ubuntu-24.04

### DISCUSSION THREAD

**Discussion by ivansherov** [community/community#146733] [Actions]
### Select Topic Area

Bug

### Body

Workflow:

```
  tests:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    env:
      ARCH: x64
      TARGET: linux

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
```

Output:

```
env:
    ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    ARCH: x64
    TARGET: linux
/usr/bin/docker exec  751da27026340c3dd237a30cedf7fcfde9c03cb0a427a6654e8a2c54429d4fbe sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

Most probably happened after GitHub [upgraded runners](https://github.com/actions/runner-images/issues/10636)

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by RaviAkshintala** [comment]
Hi @ivansherov Could you please try with the below workaround, It is working for me without any `GLIBC` errors.

```
name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    env:
      ARCH: x64
      TARGET: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
 ```
