### DISCUSSION TITLE
[BUG]: GPU runner VM loses access to attached GPU

### DISCUSSION THREAD

**Discussion by justinthelaw** [community/community#146879] [Actions]
### Select Topic Area

Bug

### Body

There seems to be times when the GPU runner fails to gain access to the passthrough or virtual T4 NVIDIA GPU.

Has anyone else run into this multiple times a day? Is there a better way to debug this to find a solution?

Snippet of my on-failure debug log:

```bash
Run echo "NVIDIA GPU Statistics:"; nvidia-smi
  echo "NVIDIA GPU Statistics:"; nvidia-smi
  echo ""; echo ""
  echo "K3S Node Statistics:"; sudo uds zarf tools kubectl describe nodes || true
  echo ""; echo ""
  echo "K3S Pod Statistics:"; sudo uds zarf tools kubectl get Pods --all-namespaces -o wide || true
  echo ""; echo ""
  echo "Memory Usage:"; free -h
  echo ""; echo ""
  echo "Top Processes by Memory:"; ps aux --sort=-%mem | head -n 10
  echo ""; echo ""
  echo "CPU Usage: $(top -bn1 | grep "Cpu(s)" | awk '{print $[2](https://github.com/defenseunicorns/uds-ai/actions/runs/12287402005/job/34289361194#step:10:2) + $4"%"}')"
  echo ""; echo ""
  echo "Top Processes by CPU:"; ps aux --sort=-%cpu | head -n 10
  echo "Disk Usage:"; df -h
  echo ""; echo ""
  shell: /usr/bin/bash -e {0}

NVIDIA GPU Statistics:
No devices were found
```

Censored snippet of my entire workflow file:

```yaml
name: Test

on: <CENSORED>

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions: <CENSORED>

# Abort prior jobs in the same workflow / PR
concurrency: <CENSORED>

jobs:
  test:
    runs-on: <CENSORED>-linux-x64-gpu
    timeout-minutes: 60

    # NOTE: all steps must be run with `sudo` permissions due to a) the need for standing up a K3S cluster and
    #       b) <CENSORED>
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: "<CENSORED>"
          cache-dependency-path: "<CENSORED>"

      - name: <CENSORED>
     
      - name: Setup NVIDIA Container Toolkit and <CENSORED>
        run: |
          sudo <CENSORED> nvidia-ctk --no-progress


      - name: <CENSORED>

      - name: Log System Statistics
        if: ${{ failure() }}
        run: |
          echo "NVIDIA GPU Statistics:"; nvidia-smi
          echo ""; echo ""
          echo "K3S Node Statistics:"; sudo uds zarf tools kubectl describe nodes || true
          echo ""; echo ""
          echo "K3S Pod Statistics:"; kubectl get Pods --all-namespaces -o wide || true
          echo ""; echo ""
          echo "Memory Usage:"; free -h
          echo ""; echo ""
          echo "Top Processes by Memory:"; ps aux --sort=-%mem | head -n 10
          echo ""; echo ""
          echo "CPU Usage: $(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4"%"}')"
          echo ""; echo ""
          echo "Top Processes by CPU:"; ps aux --sort=-%cpu | head -n 10
          echo "Disk Usage:"; df -h
          echo ""; echo ""

      - name: Setup SSH Debugging Session
        uses: mxschmitt/action-tmate@e5c7151931ca95bad1c6f4190c730ecf8c7dde48 # v3.19
        if: ${{ failure() }}
        with: <CENSORED>
```
