### DISCUSSION TITLE
Cron job "0 * * * *" does not run correctly, executions do not respect the scheduled time

### DISCUSSION THREAD

**Discussion by Angelk90** [community/community#146923] [Actions]
### Select Topic Area

Bug

### Body

Link: [Test_workflows](https://github.com/Angelk90/Test_workflows)

I have configured a cron job in my GitHub Actions workflow to run a certain action every hour, at minute 0 (e.g. 0 * * * *), but I noticed that it does not run as expected.

My workflow should run every hour at minute 0, but I noticed that it runs at unexpected times, such as:

```
12:38
13:24
14:14
```
This does not seem to match the schedule 0 * * * *, which should run the job at minute 0 of every hour.

```yaml
name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
...
```

What I expect:
00:00
01:00
02:00
03:00
...
23:00

Result:
<img width="284" alt="Screenshot 2024-12-12 alle 15 18 49" src="https://github.com/user-attachments/assets/efbefe18-10e6-4678-97ac-1facdc8512dc" />
<img width="240" alt="Screenshot 2024-12-12 alle 15 19 32" src="https://github.com/user-attachments/assets/c543528e-d733-4cf7-994a-727bcbdbd77f" />

Has anyone had similar experiences with cron jobs on GitHub Actions not respecting the scheduled time?

Could you confirm if the UTC time zone could be the cause of the issue and if there are any workarounds to make the cron job match the local time?

Could it be a problem with the machine?
