### DISCUSSION TITLE
Rubocop lint takes 1 hour 13 min to fail even though the command did not show any errors locally

### DISCUSSION THREAD

**Discussion by ShadowCrafter011** [community/community#147345] [Actions]
### Select Topic Area

Question

### Body

I recently changed the CI of one of my Rails applications and used the same setup as another application on which it works perfectly. Lint stage with rubocop only takes a few seconds. However in the other project where it almost seems stuck before failing I have no differences except gem versions and other code.

I tried updating the rubocop gem to no avail.

When looking at the details of the action it is just stuck at the lint command:
![Action where it seems stuck](https://github.com/user-attachments/assets/595db3ba-9617-427f-82d8-62d98e39bc8b)
After said 1 hour and 13 minutes I get this output:
![Fail output](https://github.com/user-attachments/assets/0f8fc8ab-4223-4b82-932b-74f863ed01b3)
Running the code locally rubocop sais there are not style offences in my code and running specifically the same command as in the Github CI `bin/rubocop -f github` gives no output as it should.

Here's the relevant section of my ci.yml
```yml
lint:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Lint code for consistent style
      run: bin/rubocop -f github
```
This is what the `bin/rubocop` file contains:
```ruby
#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"

# explicit rubocop config increases performance slightly while avoiding config confusion.
ARGV.unshift("--config", File.expand_path("../.rubocop.yml", __dir__))

load Gem.bin_path("rubocop", "rubocop")
```
I am baffled as to what is going wrong here and would appreciate any help. In case it might help the codebase is public and can be found here: https://github.com/ShadowCrafter011/Freequiz

EDIT: From looking at the logs it seems to give me offences for gems that I use in my project. So it might be scanning the gems as well and thus taking so long... Although I don't know why that might happen nor how to fix it if that's the case.

Thanks and cheers!
