### DISCUSSION TITLE
The Github Action cron schedule is not running at the specified time

### DISCUSSION THREAD

**Discussion by Jooyoung-dable** [community/community#147369] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi. I want to use the Github Action cron schedule to run my jobs.
My workflow YAML is as follows:
```
ame: App CI

on:
  schedule:
    - cron: "20 1 * * *"
    - cron: "25 1 * * *"
  

jobs:
  update-hpa:
    name: Update tmp yaml
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schedule: 
          - name: "10h20m"
            cron: "20 1 * * *"
            value: "50"
          - name: "10h25m"
            cron: "25 1 * * *"
            value: "70"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Matrix Variables
        run: |
          echo "Schedule Name: ${{ matrix.schedule.name }}"
          echo "CPU Value: ${{ matrix.schedule.value }}"
```

But, even with this configuration, I noticed that the Github Action does not run at 1:20 AM or 1:25AM UTC, nor at any other time I checked. Even whe I configure it like `*/5 * * * *` to run at regular intervals, it doesn't run every 5 mins as intended. Is there a bug causing this issue?

**Comment by iam-narasimhasai** [comment, marked as answer]
https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/

**Comment by andrevst** [comment]
mine is not running at all. Never, is it broken or was it removed?

**Reply by andrevst** [reply]
```
on:
  schedule:
    - cron: '*/5 * * * *'
```

Never ran

**Reply by GooRoo** [reply]
It's same for me. I added a daily workflow 3 days ago and it has never run till now. At all. (Although, manual triggering works fine).

**Reply by Oddinus** [reply]
The same for me. Tried nightly builds and then simple test file with 15 intervals to test if it run, but nothing happened since 4 days. I've even added id-token: write.

name: Test Schedule

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Print test message
        run: |
          echo "✅ Scheduled workflow is working!"
          echo "Current time: $(date)"
          echo "This workflow ran successfully."

**Reply by mohammmdmdmkdmewof** [reply]
i have the same problem, my workflow is supposed to run every hour but it hasn't ran once in the previous 3 days.

**Reply by praphull-purohit** [reply]
I added a scheduled workflow last Thursday (daily run) and it wasn't picked up since then. Renaming the workflow file and disabling and enabling the workflow again worked for me. But, after that I made some more changes to the schedule and it's still stuck on the old schedule

**Reply by nurma-zimran** [reply]
I had the same issue. I created a workflow on January 24th, but it hasn't triggered even once - only from dispatches.
```
name: Cache Warmup

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch: # Manual trigger

jobs:
  warm-cache:
    runs-on: ubuntu-latest
```

**Reply by AntoniosBarotsis** [reply]
Same issue here, created a workflow that should run every Wednesday but it just didn't. Workflow dispatch works for me as well

**Reply by SupratimRK** [reply]
So, I'm not alone in this chore, mine works through `workflow_dispatch` but the corn is not working.

**Reply by siddheshranade** [reply]
Just created a new workflow, and at first the cron didn't work for me either but now does (through no changes from my end), though always delayed from the scheduled time by at least 15 minutes.

**Reply by Anas-github-acc** [reply]
mine one is working slightly different. when i added utc time convert from ist, it didnt work, but when i added `timezone: 'asia/kolkata'`, it worked.

```yaml
cron: '3,18,33,48 10 * * *'
timezone: 'asia/kolkata'
```

but the real issue i faced was when i tried to run this job 25 times in a day at different times, it only worked for 6-8 times a day at totally different times than my described time.

**Comment by rinas21** [comment]
GitHub Actions cron schedules only trigger on the default branch and may not run immediately after creating or editing a workflow. To fix: ensure the workflow is on the default branch, commit changes there, and try disabling/enabling the workflow or renaming the YAML file. Also, remember cron uses UTC, not your local time.

**Reply by AntoniosBarotsis** [reply]
Did all of those and its not working for me. Seems like they have some sort of issue considering the amount of people complaining in this thread

**Comment by AntoniosBarotsis** [comment]
It looks like GitHub had some relevant issues that should now be fixed, see [here](https://github.com/orgs/community/discussions/185355#discussioncomment-15611446).

Fix:
> Any commit pushed to the default branch will resync the impacted scheduled workflows and resolve any scheduling issues you may be experiencing

I haven't tested this myself yet but seems like it should work.

**Comment by andrevst** [comment]
yeah, somehow my workflows are sort of "working" again, not 100% correct yet, but it's at least triggering sometimes.

**Comment by OlivierBouchoms** [comment]
My scheduled workflow also isn't running :/ It has been paused for a few months, then updated and enabled again, but not running. I'll try manually triggering it on my default branch and hopefully that'll sort things out 🤞🏻 

Other scheduled workflows in the same repository are running properly.

```yaml
name: 'xxx'

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
```
