### DISCUSSION TITLE
Ignoring directories

### DISCUSSION THREAD

**Discussion by himynameisdave** [community/community#14739] [Code Security]
Would be nice if this tool could handle monorepo/legacy codebases which (in our case) have multiple `package.json`s/lockfiles, but we only want dependabot to run against our root dir.

Perhaps something like this:

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - directories: ["some-ignore-dir/"]
```
