### DISCUSSION TITLE
Allow jobs.<job_id>.uses use {owner}/{repo}@{ref}

### DISCUSSION THREAD

**Discussion by kderck** [community/community#14730] [Actions]
Dear GitHub, 

I would like it if it was possible for jobs to use the shorthand syntax for `jobs.<job_id>.uses`

```yaml
jobs:
 swagger_deploy:
  uses: company/Github-Action@v1.0.0
```

rather than 

```yaml
jobs:
 swagger_deploy:
  uses: company/Github-Action/.github/workflows/action.yaml@v1.0.0
```

You can do the above with `jobs.<job_id>.steps.uses` but not with `jobs.<job_id>.uses`

> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses
