### DISCUSSION TITLE
Github Actions keep being triggered on commits

### DISCUSSION THREAD

**Discussion by peme969** [community/community#147335] [Actions] [answered]
### Body

I dont want both of my yaml files to be triggered when I make a change to any file (probably any other than the yaml files?)
If you can see here, when I updated the README it triggered both yaml files to run.
<img width="933" alt="Screenshot 2024-12-17 at 12 45 55 PM" src="https://github.com/user-attachments/assets/d2564b7e-6ead-40d2-a3e7-c62a4cdda00c" />
Heres the link to the repo:
https://github.com/peme969/GitHub_F4F

### Guidelines

- [X] I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.

**Comment by mecodeatlas** [comment]
Thanks for posting in the GitHub Community, @peme969 !

We're happy you're here! To get the best responses, it's important to post in the most relevant category. The **Programming Help** category is for questions about software development, programming concepts, project feedback, and discussions on open source tools or packaging.

It looks like your question belongs in the Actions category, so I’ve moved it for you. Good luck!

**Comment by peme969** [comment]
Thank you! I’m fairly new to the community, so I apologize for that!

**Comment by gmitch215** [comment, marked as answer]
Both of your workflow files have this block:

```yml
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.py'
  workflow_dispatch:
```

This means it gets triggered if you push a commit (changing a file) on any file that isn't a python file. Remove the `push` section so it looks like this:

```yml
on:
  workflow_dispatch:
```

Or:

```yml
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *' # 6:30 PM CST 
```
