### DISCUSSION TITLE
Quoting issue with a multi-line JSON output

### DISCUSSION THREAD

**Discussion by dbeilin** [community/community#147514] [Actions]
### Select Topic Area

Question

### Body

I need help me with my Github Action.
My composite sends a Slack message like this:

```yaml
runs:
  using: "composite"
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v2.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        payload: |
          channel: "${{ inputs.channel_id }}"
          text: "${{ inputs.message }}"
          blocks:
          ${{ inputs.blocks }}
```

When I call it with the following block:

```yaml
      - name: Notification
        uses: dbeilin/orangutan/composite/send-slack-notification@main
        with:
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: "@beinish"
          message: "message"
          blocks: |
            - type: "section"
              text:
                type: "mrkdwn"
                text: "```{\n  \"added\": [],\n  \"removed\": []\n}```"
```

It works, and I get a multi-line JSON:

<img width="303" alt="image" src="https://github.com/user-attachments/assets/09968201-d956-4e6a-85b5-4195f8d7c69d" />

However, when I pass a JSON from outside, it doesn't work:

```yaml
    steps:
      - name: Create JSON file
        run: |
          echo '{ "added": [], "removed": [] }' > diff.json

      - name: Set output
        id: vars
        run: |
          {
            echo 'DIFF_CONTENT<<EOF'
            jq '.' diff.json
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: echo
        run: |
          echo "${{ steps.vars.outputs.DIFF_CONTENT }}"

      - name: Notification
        uses: dbeilin/orangutan/composite/send-slack-notification@main
        with:
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: "@beinish"
          message: "message"
          blocks: |
            - type: "section"
              text:
                type: "mrkdwn"
                text: '```${{ toJSON(steps.vars.outputs.DIFF_CONTENT) }}```'
```

I do get a message successfully, but the JSON inside of the message is not a multi-line JSON. This is what I see:

<img width="433" alt="image" src="https://github.com/user-attachments/assets/dfe5c703-e15c-4bed-8d6b-cad38cc0fbf1" />

Which is exactly what I pasted manually in the working block in my first example.

The diff seems to be the quotes wrapping the JSON. I tried to get rid of them in various ways like using env vars instead of output, using `|` to drop a line, using quotes instead of single quotes, but nothing seems to work.

Any help would be appreciated.

**Comment by ChristopherHX** [comment]
You encode a string with new lines into an json string literal by using tojson on a string

E.g. do it like this (`steps.*.outputs.*` are always strings)
> ```yaml
> ```${{ steps.vars.outputs.DIFF_CONTENT }}```
> ```

**Reply by dbeilin** [reply]
I actually also tried it without `toJSON`, but the Slack message I get is still a single line, even though the echo step which I used to debug shows it's a multi line:

![image](https://github.com/user-attachments/assets/11924ad7-2a15-4616-b59e-cf1b8401c9d1)

![image](https://github.com/user-attachments/assets/83fe034f-3bd7-4caa-9910-c3a5432da455)

So I assume it's related to my Slack payload and not to Github Actions:

```yaml
runs:
  using: "composite"
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v2.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        payload: |
          channel: "${{ inputs.channel_id }}"
          text: "${{ inputs.message }}"
          blocks:
          ${{ inputs.blocks }}
```

I'll ask on their repo :)

Thanks
