### DISCUSSION TITLE
Grouping Dependabot Security Updates NPM

### DISCUSSION THREAD

**Discussion by DrillableBit** [community/community#147738] [Code Security]
### Select Topic Area

Question

### Body

Hi, 
Am I understanding the dependabot docs correctly that the following code will group the directory's security updates into a group?
The following .yaml appears to group ALL updates in a PR, but it doesn't seem PR security updates? 

```
version: 2
updates:

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
```
