### DISCUSSION TITLE
Submodules not recognized

### DISCUSSION THREAD

**Discussion by ambbox** [community/community#147911] [Actions]
### Select Topic Area

Question

### Body

```
jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.PAT }}

    - name: Build
      run: |
        git submodule status
```
The checkout ends without errors but the files of the submodule are just not there and `git submodule status` prints nothing.

![image](https://github.com/user-attachments/assets/94ef8acd-2a1e-4a39-8e6a-f25c553f7e97)
