### DISCUSSION TITLE
can't use glob in github actions

### DISCUSSION THREAD

**Discussion by om-raheja** [community/community#148097] [Actions]
### Select Topic Area

Question

### Body

Hi, I want to compile with pdflatex every file that matches the glob `*.tex` so I can validate the latex works. Unfortunately, I don't think the github actions shell recognizes glob.
In my file below, `ls *.tex` errors out and the for loop doesn't run at all. Nothing is printed to console or in a log file
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Setup TeXLive Action
              uses: teatimeguest/setup-texlive-action@v3.3.4

          
            - name: setup texlive
              run: |
                sudo apt-get install texlive
            - name: Compile them all
              run: |
                ls *.tex 
                for file in $(find . -name "*.tex"); do
                  echo $file
                  pdflatex -halt-on-error "$file"
                done
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4.5.0
              with:
                # Artifact name
                name: logs
                # A file, directory or wildcard pattern that describes what to upload
                path: "*.log"             
```
