### DISCUSSION TITLE
How do I make the form fields beneath one another and not side by side?

### DISCUSSION THREAD

**Discussion by Shivraj957** [community/community#148151] [Programming Help] [answered]
Repository: https://github.com/Shivraj957/indianmapwarmultigame/
Website: https://shivraj957.github.io/indianmapwarmultigame/

**Comment by lemorage** [comment, marked as answer]
Modify the `<form>` section in your CSS, like the following:
```css
form {
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
}
```
- `flex-direction: column` arranges them in a vertical column.
- `align-items: center` puts them all in the center.
- `gap: 1rem` adds spacing between form fields.
<br/>

For a bit of extra style, you might want to add these additional CSS rules:
```css
input, select {
  width: 200px;
  padding: 0.5rem;
  font-size: 1rem;
}
```
