### DISCUSSION TITLE
How do I style the select tag?

### DISCUSSION THREAD

**Discussion by Shivraj957** [community/community#148164] [Programming Help]
When I apply CSS, the select tag does not get styled. But when I click on the dropdown, the styles apply. Please, someone help me to fix this.
Repository: https://github.com/Shivraj957/indianmapwarmultigame
Website: https://shivraj957.github.io/indianmapwarmultigame/

**Comment by Mefamex** [comment]
Hi @Shivraj957 

```CSS
select {
    -webkit-appearance: none; /* Safari */
    -moz-appearance: none; /* Firefox */
    appearance: none; /* Standard */
    /* ... other styles ... */
    background-color: #f0f0f0; /* Example */
    border: 1px solid #ccc; /* Example */
    padding: 5px; /* Example */
}


.custom-select {
    position: relative; /* Needed for positioning the dropdown */
    width: 200px;
}

.select-trigger {
    /* Style like a select box */
    border: 1px solid #ccc;
    padding: 5px;
    cursor: pointer;
}

.select-dropdown {
    position: absolute;
    top: 100%;
    left: 0;
    width: 100%;
    border: 1px solid #ccc;
    background-color: white;
    display: none; /* Initially hidden */
}

.select-option {
    padding: 5px;
    cursor: pointer;
}

.select-option:hover {
    background-color: #f0f0f0;
}

.custom-select.open .select-dropdown { /* Show dropdown when open class is present */
    display: block;
}
```

JS
```JS
const customSelect = document.querySelector('.custom-select');
const selectTrigger = customSelect.querySelector('.select-trigger');
const selectDropdown = customSelect.querySelector('.select-dropdown');
const selectOptions = selectDropdown.querySelectorAll('.select-option');
const actualSelect = customSelect.querySelector('select');

selectTrigger.addEventListener('click', () => {
    customSelect.classList.toggle('open');
});

selectOptions.forEach(option => {
    option.addEventListener('click', () => {
        selectTrigger.textContent = option.textContent;
        actualSelect.value = option.dataset.value; // Update the real select
        customSelect.classList.remove('open');
    });
});
```
