### DISCUSSION TITLE
Optimizing GitHub Actions with Matrix Builds for Concurrent Testing Across Multiple Environments

### DISCUSSION THREAD

**Discussion by ariollex1** [community/community#148131] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm struggling to optimize my GitHub Actions workflows. I have multiple jobs that are running sequentially, but they could easily be parallelized. How can I use matrix builds to run my tests across different Node.js versions and OS environments simultaneously, and how do I avoid unnecessary reruns of these jobs?

**Comment by SheatA3Vp** [comment, marked as answer]
Matrix builds allow you to run your jobs across multiple environments simultaneously by defining a matrix strategy in your workflow YAML file. In your case, you can specify Node.js versions and OS environments in the _matrix_ keyword. This helps run tests concurrently, significantly reducing the execution time of your workflows. To avoid unnecessary reruns, you can use the _concurrency_ key in your workflow file to prevent running the same job multiple times for the same branch or PR. Here's an example of how to set up a matrix build:

```
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

```

This setup will run tests across the three Node.js versions and three OS platforms.
