### DISCUSSION TITLE
Github Action: can't access to a file through a shared github action

### DISCUSSION THREAD

**Discussion by tfeitor** [community/community#148233] [Actions]
### Select Topic Area

Question

### Body

I have a shared workflows and actions repo, that is used by another organization repositories, one of that actions, it's responsible to set env vars which are defined on a repository local file, that is located on .github/variables/local-vars.env on Repo1:

**Repo1 - local-vars.env**

> var1=value1 var1
> var2=value2

**Repo1 - Workflow**
```
name: Build and Publish Libs to AWS CodeArtifact

on: [push]

permissions:   
id-token: write
contents: write   
actions: write  
checks: write

jobs:   format:
  uses: ORG/org-shared-workflows/.github/workflows/format.yaml@master
  with:
   local-vars: '.github/workflows/variables/local-vars.env'
```

**Shared Workflow Repo**

On the ORG/org-shared-workflows, I have the corresponding Format Workflow, that call the set-vars action

```
- name : Set Variables
  if: github.event_name != 'workflow_dispatch' || github.event.inputs.local-vars != ''
  uses: ORG/org-shared-workflows/actions/set-vars@master
  with:
    varFilePath: "${{ inputs.local-vars }}"
```

**set-vars action** 
```
name: 'Set environment variables'
inputs:
  varFilePath:
    required: true
runs:
  using: "composite"
  steps:
      sed "" ${{ inputs.varFilePath }} >> $GITHUB_ENV
      shell: bash
```

When I test the Workflow, and print the filesystem contents of the Repo1, the local-vars.env file is present, but the sed command fails with the follwing output

>     sed: can't read ./.github/workflows/variables/local-vars.env: No such file or directory
>     Error: Process completed with exit code 2.

Below the ls command output

    Run ls -la ./   
          ls -la ./.github/   
          ls -la./.github/variables/
    
    drwxrwxr-x  5 runner runner    4096 Dec 31 11:16 .
    drwxrwxr-x  3 runner runner    4096 Dec 31 11:16 ..
    drwxrwxr-x  8 runner runner    4096 Dec 31 11:16 .git
    drwxrwxr-x  4 runner runner    4096 Dec 31 11:16 .github
    
    drwxrwxr-x 4 runner runner 4096 Dec 31 11:16 .
    drwxrwxr-x 5 runner runner 4096 Dec 31 11:16 ..
    drwxrwxr-x 2 runner runner 4096 Dec 31 11:16 variables
    drwxrwxr-x 2 runner runner 4096 Dec 31 11:16 workflows
    total 12
    drwxrwxr-x 2 runner runner 4096 Dec 31 11:16 .
    drwxrwxr-x 4 runner runner 4096 Dec 31 11:16 ..
    -rw-rw-r-- 1 runner runner  448 Dec 31 11:16 local-vars.env

How can I access the file located in Repo1, which I think is available from the set-vars action?

**Comment by jakubbbdev2** [comment]
It seems like the issue is with the path being used in the sed command. Ensure that the correct relative path to local-vars.env is being referenced. Modify the sed command in your set-vars action to use the full path:

```
steps:
  - run: sed "" ${{ github.workspace }}/.github/workflows/variables/local-vars.env >> $GITHUB_ENV
    shell: bash
```

This ensures that sed correctly locates the local-vars.env file in the repository.

**Reply by tfeitor** [reply]
Unfortunately shows the correct repo location, but still fails

```
Run sed "" /home/runner/actions-runner/_work/repo1-lib-shared/repo1-lib-shared/.github/workflows/variables/local-vars.env >> $GITHUB_ENV
  sed "" /home/runner/actions-runner/_work/repo1-lib-shared/repo1-lib-shared/.github/workflows/variables/local-vars.env >> $GITHUB_ENV
  (...)
sed: can't read /home/runner/actions-runner/_work/repo1-lib-shared/repo1-lib-shared/.github/workflows/variables/local-vars.env: No such file or directory
Error: Process completed with exit code 2.
```

cat output / same error 

```
cat ${{ github.workspace }}/.github/workflows/variables/local-vars.env
(...)
cat: /home/runner/actions-runner/_work/repo1-lib-shared/repo1-lib-shared/.github/workflows/variables/local-vars.env: No such file or directory
total 12
drwxrwxr-x 2 runner runner 4096 Dec 31 13:20 .
drwxrwxr-x 4 runner runner 4096 Dec 31 13:20 ..
-rw-rw-r-- 1 runner runner  448 Dec 31 13:20 local-vars.env
```

**Reply by tfeitor** [reply]
I think this is a limitation at the remote shared github action, because if I do this at the shared workflow level, I don't have this problem

**Comment by jakubbbdev2** [comment]
Here are some steps that might help you resolve the issue:

Check the File Path:
Ensure that the file path is correct. The error shows:

/home/runner/actions-runner/_work/repo1-lib-shared/repo1-lib-shared/.github/workflows/variables/local-vars.env
Verify this path for any typos.

Use Relative Paths:
Use relative paths instead of absolute paths to ensure the workflow runs correctly in different environments:

run: cat ${{ github.workspace }}/.github/workflows/variables/local-vars.env
Add Debugging Steps:
Add debugging steps to check the directory contents before running the sed command:

```
steps:
  - name: Check file existence
    run: ls -la ${{ github.workspace }}/.github/workflows/variables/

  - name: Display file content
    run: cat ${{ github.workspace }}/.github/workflows/variables/local-vars.env

  - name: Append environment variables to GITHUB_ENV
    run: sed "" ${{ github.workspace }}/.github/workflows/variables/local-vars.env >> $GITHUB_ENV
```

Check Permissions:
Ensure that the runner user has the necessary permissions to read the file.

Verify sed Command:
Ensure that sed is installed and correctly used in the runner environment.

An example workflow could look like this:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check file existence
        run: ls -la ${{ github.workspace }}/.github/workflows/variables/

      - name: Display file content
        run: cat ${{ github.workspace }}/.github/workflows/variables/local-vars.env

      - name: Append environment variables to GITHUB_ENV
        run: sed "" ${{ github.workspace }}/.github/workflows/variables/local-vars.env >> $GITHUB_ENV
```

These steps should help diagnose and fix the issue.
