### DISCUSSION TITLE
Allow dynamic branch to run a job in reusable workflow

### DISCUSSION THREAD

**Discussion by andylim0221** [community/community#148305] [Actions] [answered]
### Select Topic Area

Question

### Body

In my reusable workflow, I want a job to run only if the branch is either main or any branch that is defined by the caller workflow. It works if I statically define the branch name,  it will run only in the main branch and if there's change on the `plan` job..

```
name: Example

job:
  plan:
  ...
  example:
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ inputs.environment }}
    if: | 
      needs.plan.outputs.has-changes == 'true' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
```

However, if I define a dynamic value for the branch name, it will run always even if the value `has-changes` is `false` in the job `plan`. Any mistake that I've made here?

```
name: Example

on:
  workflow_call:
    inputs:
      branch-allowed-for-apply:
        description: 'Branch allowed for apply'
        type: string
        default: 'main'
job:
  plan:
  ...
  example:
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ inputs.environment }}
    if: | 
      needs.plan.outputs.has-changes == 'true' && github.ref == 'refs/heads/${{ inputs.branch-allowed-for-apply }}'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
```

**Comment by MatinGhanbari** [comment, marked as answer]
The issue you're facing is due to how the if condition is structured in your GitHub Actions workflow. When you define a dynamic branch name using an input, you need to ensure that the condition checks for both the main branch and the dynamically specified branch correctly.

Here's how you can modify your workflow to achieve that:
```
name: Example

on:
  workflow_call:
    inputs:
      branch-allowed-for-apply:
        description: 'Branch allowed for apply'
        type: string
        default: 'main'

jobs:
  plan:
    # Your plan job definition here
    outputs:
      has-changes: ${{ steps.some_step.outputs.has-changes }} # Example output

  example:
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ inputs.environment }}
    if: |
      needs.plan.outputs.has-changes == 'true' && (
        github.ref == 'refs/heads/main' || 
        github.ref == format('refs/heads/{0}', inputs.branch-allowed-for-apply)
      )
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

```

With this setup, the example job will only run if there are changes detected in the plan job and if the current branch is either main or the branch specified by the input. This should resolve the issue of the job running unexpectedly.
