### DISCUSSION TITLE
How do I remove the duplicate URL?

### DISCUSSION THREAD

**Discussion by Shivraj957** [community/community#148302] [Programming Help]
<b>How do I remove the duplicate URL?</b>
I need to remove the .html extension in the URL. I have one file named step1.html which has 2 URLs: https://shivraj957.github.io/indianmapwarmultigame/step1 and https://shivraj957.github.io/indianmapwarmultigame/step1.html How do I remove the one 
with the ,html extension?
Please, answer this question. Thanks in Advance!

**Comment by CyberSphinxxx** [comment]
Hi @Shivraj957,

I checked your repository, and it seems you don't have an `index.html` file. This is important because GitHub Pages looks for `index.html` as the default landing page. To fix this, create a file named `index.html` in your repository and add your main HTML code there.

**Reply by CyberSphinxxx** [reply]
It looks like you've already created an `index.html` file. 

To proceed, simply copy the main HTML code from your `enter-your-username-and-select-your-region.html` file and paste it into `index.html`.

**Reply by Shivraj957** [reply]
> It looks like you've already created an `index.html` file.
> 
> To proceed, simply copy the main HTML code from your `enter-your-username-and-select-your-region.html` file and paste it into `index.html`.

Won't that create 3 duplicates of the same page? I think I will write something else in the index.html file.

**Reply by Shivraj957** [reply]
Also, solve my other 3 problems.

**Reply by CyberSphinxxx** [reply]
No, just remove the old file and rename the main HTML file to `index.html`. 

Your repository files should be : 
- `index.html` (Where the initial file loads)
- Your CSS file
- Additional Pages

## Question 2.
The `required` attribute is correctly added to your input field and select element. However, the issue might arise from the fact that your Submit button's `onclick` attribute is redirecting the page to `step2.html` regardless of the form's validation status. This bypasses the form's native validation mechanism.

To fix this, you should prevent the redirection unless the form passes validation. You can achieve this by handling the form submission with JavaScript.

try this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="step1.css">
    <title>Indian Map War Multigame</title>
</head>
<body>
    <h1>Indian Map War Multigame</h1>
    <h2>Step 1: Enter Your Username and Select Your Region</h2>
    <form id="gameForm">
        <input type="text" id="Username" name="Username" placeholder="Username" autocomplete="on" required>
        <select id="Region" name="Region" class="Region" autocomplete="on" required>
            <option value="0" selected="selected" disabled>Select Your Region</option>
            <optgroup label="Indian States"></optgroup>
            <option value="AP">Andhra Pradesh</option>
            <option value="AR">Arunachal Pradesh</option>
            <option value="AS">Assam</option>
            <option value="BR">Bihar</option>
            <option value="CG">Chattisgarh</option>
            <option value="GA">Goa</option>
            <option value="GJ">Gujarat</option>
            <option value="HR">Haryana</option>
            <option value="HP">Himachal Pradesh</option>
            <option value="JH">Jharkhand</option>
            <option value="KA">Karnataka</option>
            <option value="KL">Kerala</option>
            <option value="MP">Madhya Pradesh</option>
            <option value="MH">Maharashtra</option>
            <option value="MN">Manipur</option>
            <option value="ML">Meghalaya</option>
            <option value="MZ">Mizoram</option>
            <option value="NL">Nagaland</option>
            <option value="OD">Odisha</option>
            <option value="PB">Punjab</option>
            <option value="RJ">Rajasthan</option>
            <option value="SK">Sikkim</option>
            <option value="TN">Tamil Nadu</option>
            <option value="TS">Telengana</option>
            <option value="TR">Tripura</option>
            <option value="UP">Uttar Pradesh</option>
            <option value="UK">Uttarakhand</option>
            <option value="WB">West Bengal</option>
            <optgroup label="Indian Union Territories"></optgroup>
            <option value="AN">Andaman and Nicobar Islands</option>
            <option value="CH">Chandigarh</option>
            <option value="DH">Dadra and Nagar Haveli and Daman and Diu</option>
            <option value="DL">Delhi</option>
            <option value="JK">Jammu and Kashmir</option>
            <option value="LA">Ladakh</option>
            <option value="LD">Lakshadweep</option>
            <option value="PY">Puducherry</option>
            <optgroup label="Countries"></optgroup>
            <option value="BD">Bangladesh</option>
            <option value="BT">Bhutan</option>
            <option value="MV">Maldives</option>
            <option value="NP">Nepal</option>
            <option value="PK">Pakistan</option>
            <option value="LK">Sri Lanka</option>
        </select>
        <input type="submit" name="Submit1" id="Submit1" value="Continue">
    </form>

    <script>
        // Attach an event listener to handle form submission
        document.getElementById("gameForm").addEventListener("submit", function(event) {
            // Perform validation
            const username = document.getElementById("Username");
            const region = document.getElementById("Region");

            if (!username.value.trim()) {
                alert("Username is required!");
                event.preventDefault(); // Prevent form submission
                return;
            }

            if (region.value === "0") {
                alert("Please select a region!");
                event.preventDefault(); // Prevent form submission
                return;
            }

            // If all validation passes, the form will submit normally
        });
    </script>
</body>
</html>

```

## Question 3.
The height of the `<select>` element often doesn't respond to the `height` property in some browsers due to browser-specific default styling. To address this and ensure consistent height across browsers, you can try this:

```css
select {
    font-family: 'Roboto';
    font-size: 1rem;
    height: 40px; /* you can adjust this as needed */
    line-height: 40px; /* to align text vertically */
    padding: 0; /* resets the padding */
    box-sizing: border-box; /* and ensure consistent sizing */
}

```

This is the entire CSS Updated code for step1.css
```css
body {
    background-color: #0080ff;
    margin: 3rem;
    font-family: 'Roboto';
}
h1 {
    font-size: 4rem;
    text-align: center;
    color: white;
}
h2 {
    font-size: 2rem;
    text-align: center;
    color: red;
}
form {
    align-items: center;
    display: flex;
    flex-direction: column;
    gap: 1rem;
}
#Username {
    height: 20px;
    width: 20rem;
}
::placeholder {
    font-family: 'Roboto';
    font-size: 1rem;
}
.Region {
    height: 40px;
    padding: 0;
    box-sizing: border-box;
}
select {
    font-family: 'Roboto';
    font-size: 1rem;
    height: 40px;
    line-height: 40px;
    padding: 0;
    box-sizing: border-box;
}
select option {
    font-family: 'Roboto';
    font-size: 1rem;
}
select optgroup {
    font-family: 'Roboto';
    font-size: 1rem;
}
```

### Let me know if this solves your problem
