### DISCUSSION TITLE
help

### DISCUSSION THREAD

**Discussion by luannndev** [community/community#148343] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello everyone! I am new to GitHub Actions and would like to create a simple workflow that automatically runs my tests when I push code to the repository. Can someone provide an example of a basic workflow and explain how to set it up? Thanks in advance!

**Comment by jakubbbdev2** [comment, marked as answer]
Hi!

1. Create a .github/workflows/ci.yml file in your repository.
2. Add the following content:

```YAML
name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
```

This workflow checks out your code, sets up Python, installs dependencies, and runs tests with pytest.

Let me know if you need more help!
