### DISCUSSION TITLE
Github Actions Cron Job Not Triggering

### DISCUSSION THREAD

**Discussion by felixele217** [community/community#148592] [Actions]
### Body

Hey guys, 

I have set up a Github Actions workflow that should trigger periodically based on the 'schedule' trigger:

The code is the following:

```
name: Test Cron Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "03 * * * *"  # Runs every 5 minutes for testing

jobs:
  test-cron:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron job ran successfully!"
```

I changed the 03 to whatever minute in the hour, to just trying to get it work.

When looking at https://github.com/felixele217/[repository-name]/actions, there is nothing to see

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/bc61e575-f096-4783-b083-e1febe45d2c4" />

I tried it with the repository public and private, the default branch is the main branch and I have set 'Allow all actions and reusable workflows' in the Github Actions settings

<img width="601" alt="image" src="https://github.com/user-attachments/assets/9fbb1f8a-dbaa-4978-991d-d65b9fe4a7ca" />

Is there anything I am overseeing?

Appreciate any help!
Felix

**Comment by userdocs** [comment]
Your example has `Runs every 5 minutes for testing`

```
- cron: "03 * * * *"  # Runs every 5 minutes for testing
```

`*/5 * * * *`: This means the command will run every 5 minutes. The `*/5` part is the key; it divides each hour into 5-minute intervals.

`05 * * * *`: This means the command will run at 5 minutes past every hour. So if the time is `12:05`, `13:05`, `14:05`, etc., the command will execute.

Here's a quick comparison:

Expression	Schedule

`*/5 * * * *`	Every 5 minutes
`05 * * * *`	At 5 minutes past each hour

Your example is running 1 time an hour at the third minute.

**Comment by Rickyc81** [comment]
Hi all, I have this test script, and I'm trying to figure out how the trigger works, it only started once, and it doesn't make sense, it should go at least every 5 minutes or so, without a "guarantee" it's unusable..

```
name: Experiment
on: 
  schedule:
  - cron: '*/5 * * * *'
  - cron: '05 * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with: { ref: main }
    - name: List files
      run: ls
```
