### DISCUSSION TITLE
Cannot access variable defined in the environment

### DISCUSSION THREAD

**Discussion by andylim0221** [community/community#148526] [Actions]
### Select Topic Area

Question

### Body

Hi all,

I have a use case here, where the user will pass in an environment and the reusable workflow will obtain the variables and secrets defined in the reusable workflow. This is how I call the reusable workflow:

```
name: Example

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  example:
    uses: org/repo/file@main
    with:
      # specify environment here, this will be used for the environment of the job
      environment: dev
      username: ${{ vars.USERNAME }}
    secrets:
      token: ${{ secrets.TOKEN }}
```

I defined the secrets and variables required for this workflow in the environment `dev`. I can access the secret `TOKEN` when I call this from the caller workflow, however, the variable `USERNAME` is not accessible. Is variable context not supported to access on reusable workflow, or I miss anything? Thank you.

**Comment by ervinne-parkdale-digital** [comment]
Currently dealing with the same issue:

```
- name: Validate Environment Variables
    env:
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
      SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_FLAG_STORE }}
      SHOPIFY_SOURCE_THEME: ${{ vars.SHOPIFY_SOURCE_THEME }}
    uses: ./.github/actions/validate-environment
```

`vars.SHOPIFY_FLAG_STORE` would have value while `vars.SHOPIFY_SOURCE_THEME`, both are properly set on the environment as variables.

**Reply by Bennyenassi** [reply]
- [ ] - - []()[]()[]()~~~~

**Reply by ervinne-parkdale-digital** [reply]
I was able to resolve my issue by specifying `environment`.
Originally I was using matrix strategy, I thought that was enough to specify the environment:

```
jobs:
  pull_build_deploy:
    name: Pull, Build, Deploy, and Manage Themes
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [DEV, STAGING]

    environment: ${{ matrix.environment }}
```

So my fix ended up with this.

@andylim0221 could it be possible that your `dev` environment was setup elsewhere? You clearly specified yours unlike me. It could also be that you need to specify it under the job instead of `with`

**Reply by andylim0221** [reply]
@ervinne-parkdale-digital 

In the reusable workflow, I allow dynamic environment passed by the caller workflow, eg.

```
name: Reusable Workflow

on:
  workflow_call:
    inputs:
     ...

permissions:
  id-token: write
  contents: read

jobs:
  action:
    name: Action
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.environment }}
```

And I pass in the environment from my caller workflow:

```
name: Example

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  example:
    uses: org/repo/file@main
    with:
      environment: dev   # specify environment here, this will be used for the environment of the job
      username: ${{ vars.USERNAME }}
    secrets:
      token: ${{ secrets.TOKEN }}
```

I have both secret and variable set in the `dev` environment. Based on the action, the workflow can access the secret defined in the `dev` environment, however, the workflow cannot access the variable defined in the `dev` environment. Not sure if this is because the reusable workflow can't access the variable context within the environment level.
