### DISCUSSION TITLE
Feature Request: Support use of actions from self-hosted GHES

### DISCUSSION THREAD

**Discussion by bwhitehead0** [community/community#148664] [Actions]
### Select Topic Area

Product Feedback

### Body

For those of us whose organizations self-host GHES, and where we might wish to publish actions for use within our org, but not publicly on github.com, on the Actions Marketplace, etc, it would be helpful to be able to reference and call an action that is located somewhere besides github.com.

For example, assuming the action repo was `my-org/my-action`, and the GHES URL was `github.myorg.com`, and the repo is publicly available within the environment calling it, support calling it like the below, or similar:

```yaml
    steps:
    - name: Run custom action
      uses: github.myorg.com/my-org/my-action@v1
      with:
        input1: value1
        input2: value2
```
(Optionally, allow passing a token to access the repo like accessing a private action from github.com)

This would allow orgs who need actions crafted to include internal conventions, standards, and so on which might not be fit for public release to still package and use actions identically to publicly-available actions, aside from including the URL in the `uses:` line.
