### DISCUSSION TITLE
checkExpected — Waiting for status to be reported          Required

### DISCUSSION THREAD

**Discussion by saireddyzepto** [community/community#148719] [Actions]
### Select Topic Area

Bug

### Body

Intermittent issue
When runner is set as required but in workflow set to run on specific path only.

```
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'prod/**/values.yaml'
```
