### DISCUSSION TITLE
Terraform plan running forever in github actions

### DISCUSSION THREAD

**Discussion by jenia** [community/community#148722] [Actions]
### Select Topic Area

Question

### Body

Hello.

I'm trying to run terraform in github actions. The problem is that it's simply running forever.

Here is the actions:

```
jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: 1.10

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2.1.7
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Verify Authentication
        run: gcloud projects list

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="project_id=${{ secrets.BILLING_ACCOUNT }}" -out=tfplan

```

The last step simply runs forever. Notice that I managed to verify that the authentication is working fine with:
```
      - name: Verify Authentication
        run: gcloud projects list
```

I expect it to either fail with an error message or succeed. Can someone please give a hint on how to run terraform in github actions properly?

Thanks kindly.
