### DISCUSSION TITLE
Do a Github workflow trigger check_run, check_suite, and status events?

### DISCUSSION THREAD

**Discussion by kuisathaverat** [community/community#148873] [Actions]
### Question

In the context of a PR, when a workflow is complete, Are `check_run`, `check_suite`, and `status` events triggered? 

## Test case

I am trying to trigger a workflow after all the workflows triggered by a pull request finish. To do that, I check the [documentation about events](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows), and there are three that look promising `check_run`, `check_suit`, and `status`.

I created four workflows:
* One to manage the push on PRs
```yaml
---
# Workflow to test push event
name: On push dummy
on:
  push: {}
permissions:
    contents: read
jobs:
  on-push-dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a dummy step"
```
* One to catch on `status`
```yaml
---
# Workflow to test status event
name: On status dummy
on:
  status:
permissions:
    contents: read
jobs:
  on-push-dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a dummy step"
```
* One to catch on `check_run`
```yaml
---
# Workflow to test check_run event
name: On check_run dummy
on:
  check_run:
    types: [completed]
permissions:
    contents: read
jobs:
  on-push-dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a dummy step"
```
* One to catch on `check_suit`
```yaml
---
# Workflow to test check_suite event
name: On check_suite dummy
on:
  check_suite:
    types: [completed]
permissions:
    contents: read
jobs:
  on-push-dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a dummy step"
```
Then, I create a PR with a simple change in the repo. For my understanding of the documentation when the workflow `On push dummy` is completed it set a check on the PR as complete and it should trigger the workflow `On check_run dummy` and I am not sure if it should trigger `On check_suite dummy` because I dunno if there is a default check suit, also the PR status change to `success` because all workflows pass so it should trigger the workflow `On status dummy`.

The fact is that only the `On push dummy` and the others are not triggered when this one is completed, Am I doing anything wrong? How these three events are triggered? Are they triggered by the completion of a workflow?

## Repository resources

I have a repo with the four workflows and the PR that I tested
* [Workflows code](https://github.com/kuisathaverat/actions_poc/commit/42003e72eff223a4f4b6c5e9590ec5a3c2f2fc29#diff-b06864dbe9fd0a6331a0febba19ca7ee90144230e17f4da255f54f61916b909eR16)
* [`On push dummy` runs](https://github.com/kuisathaverat/actions_poc/actions/workflows/on-push-dummy.yml)
* [`On check_run dummy` runs](https://github.com/kuisathaverat/actions_poc/actions/workflows/on-check-run.yml)
* [`On check_suit dummy` runs](https://github.com/kuisathaverat/actions_poc/actions/workflows/on-check-suite.yml)
* [`On status dummy` runs](https://github.com/kuisathaverat/actions_poc/actions/workflows/on-status.yml)
* [Pull request](https://github.com/kuisathaverat/actions_poc/pull/18)
