### DISCUSSION TITLE
Is it possible to use github.event in reusable workflow global concurrency key?

### DISCUSSION THREAD

**Discussion by fabn** [community/community#148891] [Actions]
### Select Topic Area

Bug

### Body

I have this reusable workflow in one of my pipelines:

```yml
name: DevEnv

on:
  workflow_call:
    inputs:
      component:
        description: CDK8S component to build
        required: true
        type: string

# Run at most one job at a time for the same PR and event type
concurrency:
  group: ${{ github.workflow }}@${{ github.event.number }}@${{ github.event.action }}
  cancel-in-progress: true

jobs:

  # This job lists all the deployments that need to be updated
  envs:
    if: contains(github.event.pull_request.labels.*.name, 'devenv') && github.event.action == 'synchronize'
    name: List active environments
    uses: ./.github/workflows/envs.yml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
# Other jobs not relevant for this
```

And I want to cancel it when another event for same pull request so I used the `group` outlined in the YAML snippet to achieve that. Unfortunately from time to time some jobs are canceled when there are multiple pull requests that invokes the same workflow with this warning:

```
Canceling since a higher priority waiting request for 'DevEnv@@' exists
```

Now I wonder how that is possible? The value of `github.event.action` is of course `synchronize` otherwise the job would have been skipped, but in the `group` expression both `number` and `action` are empty causing the clash.

So maybe is not possible to use `github.event` in top level `concurrency` statement? If so the action parser should raise an error instead of silently accepting that expression.
