### DISCUSSION TITLE
docker compose secrets in codespaces?

### DISCUSSION THREAD

**Discussion by Stwissel** [community/community#148990] [Codespaces]
### Select Topic Area

Question

### Body

I've setup a local devcontainer which I'd like to move to codespaces. The devconatiner uses a `docker-compose.yml` file that contains a secret section:

```yaml
secrets:
  config.json:
    file: ./.localsecrets/config.json
 private_ec.pem:
    file: ../.localsecrets/private_ec.pem
 binary.license:
    file: ../.localsecrets/binary.license
```

How can I configure codespaces for this?
Using env variable secrets isn't an option
