### DISCUSSION TITLE
Make a Required Workflow Dependent on another Workflow

### DISCUSSION THREAD

**Discussion by jladams145** [community/community#148907] [Actions]
### Select Topic Area

Question

### Body

Hey all, I am trying to setup a Github Actions Workflow and having some trouble finding a solid solution for an issue I am having. 

Currently I have a few `required workflows` that run every time there is a PR submitted to another repository. This repository would then run its workflows and the `required workflows` would run as checks against the PR. This logic is all well and good and everything here seems to mostly work fine. 

However, one of my workflows runs a Terraform Plan and uploads this plan to a Storage Account in Azure. Then one of the `required workflows` would download that Terraform Plan and run some OPA scans to ensure compliance. 

The issue I am having is making sure the other TF Plan is done first before the `required workflow` is initialized. Is there something that can be done here? 

For reference, this is the trigger for the Terraform Plan workflow that runs on PR:
```YAML
name: "Terraform PR Plans"

on:
  pull_request:

permissions:
    id-token: write
    contents: read
    pull-requests: write
    repository-projects: write

```

And this is the trigger for the `required workflow`:
```YAML
name: Code Scan - Non Prod

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
    id-token: write
    contents: read
    pull-requests: write
    repository-projects: write
```

Any help would be great appreciated. I search the discussions but didn't find anything specific to this issue.
