### DISCUSSION TITLE
Using variables in workflow setup on/push/paths

### DISCUSSION THREAD

**Discussion by robindotis** [community/community#148935] [Actions] [answered]
### Select Topic Area

Question

### Body

I would like to define the path that the workflow is run on using an environment variable. 

So something like this:

```
on:
  push:
    branches:
      - main
    paths:
      - '$UPLOAD_FOLDER/**'
env:
  UPLOAD_FOLDER: 'uploads' 
```

But when doing that, the workflow doesn't run when a file is pushed to the 'uploads' folder. When I define the path without the environment variable it does run (ie paths: - uploads/**).

Is using variables in the paths statement possible at all?

Thanks.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by rifainareswara** [comment, marked as answer]
Environment variables aren't supported in the `paths` section of GitHub Actions workflow triggers. The `paths` filter is evaluated before the workflow runs and before any environment variables are processed.

Instead of using environment variables there, you'll need to hardcode the path values in the workflow trigger definition. However, you can still use variables for the actual job steps.

Here's the correct way to structure this:

```yaml
on:
  push:
    branches:
      - main
    paths:
      - 'uploads/**'  # Hardcoded path here

env:
  UPLOAD_FOLDER: 'uploads'  # Define for use in the job steps
```

If you need to reuse path patterns across multiple workflows, consider:

1. Using consistent hardcoded paths in triggers
2. Creating a central workflow that other workflows can reference
3. Using repository variables (Settings > Secrets and variables > Variables) throughout your workflow files, though these won't work in the `paths` filter either

GitHub Actions has this limitation because the path filtering happens at the event trigger evaluation time, before the workflow even starts running, when environment variables aren't yet available.
