### DISCUSSION TITLE
Failing to run a job on some of the branches when pull request gets merged (job never starts for a particular branch)

### DISCUSSION THREAD

**Discussion by jpbnetley** [community/community#149097] [Actions]
### Select Topic Area

Question

### Body

Hi All.
## Problem statement
I am trying to determine why the job doesn't run when the pull request is merged to the `main` branch.
I specified that the workflow should run once a pull request is merged to the `dev` or the `main` branch.
But it seems that only when the pull request is merged to the dev branch, the job starts running as expected.

## Workflow examples
The workflow file can be found here: https://github.com/jpbnetley/joke-of-the-day/blob/dev/.github/workflows/main.yml

Here is the event snippet of the workflow
```yml
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - dev
```

I also tried to change the branches syntax to an array
```yml
# This is a basic workflow to help you get started with Actions

name: Build and deploy [dev / prod]
run-name: Build and deploy to ${{ github.ref == 'refs/heads/dev' && 'development' || 'production'  }}

# Controls when the action will run.
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: ['main', 'dev']
```
## Examples
When I merge a [pull request to the dev branch](https://github.com/jpbnetley/joke-of-the-day/pull/1355) , the job runs as expected.
![image](https://github.com/user-attachments/assets/35878947-0a99-44c3-85aa-1f76250ebd62)

But when I merge a [pull request to the main branch](https://github.com/jpbnetley/joke-of-the-day/pull/1353), the job never starts.

## Conclusion
Any advice would greatly be appreciated.
I am not sure if the issue is related to the branch name or if it is a protection rule I am missing.
I had this issue when the branch was still called `master` but I renamed the branch to the new convection `main` for consistency.

Thank you in advance. 🎉
