### DISCUSSION TITLE
How to checkout callee repository when using re-usable workflow?

### DISCUSSION THREAD

**Discussion by rnayabed** [community/community#149004] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a reusable github action workflow named `deploy.yml` that lives inside a repository named `actions` under an organisation I am a member of. The `actions` repository itself is private. I am using this workflow from another workflow in a different repository called `rma`.

The workflow is like this:

## organisation/rma > .github/workflows/release.yml

```
name: Release

...

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ...

  deploy:
    uses: organisation/actions/.github/workflows/deploy.yml@master
    needs: build
    ...
```

## organisation/actions > .github/workflows/deploy.yml

```
name: Deploy

...

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'organisation/actions'
      ...
```

This fails:

![image](https://github.com/user-attachments/assets/27c03de4-fd22-4861-b83b-10d42c8e39f9)

The actions/checkout [README](https://github.com/actions/checkout?tab=readme-ov-file#checkout-multiple-repos-private) states that:

> - `${{ github.token }}` is scoped to the current repository, so if you want to checkout a different repository that is private you will need to provide your own [PAT](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).

My questions:

- Is this still relevant even if both repositories are under one organisation? 

- Is it possible to avoid creating a PAT and still being able to checkout the callee repository? The reusable workflow file itself seems to be perfectly accessible after configuring `Action Permissions` under `Settings/Actions/General` in the caller repository.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by rnayabed** [comment]
bump

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by rnayabed** [comment]
bumpy

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by rnayabed** [comment]
bump bump

**Comment by frottke** [comment, marked as answer]
To address this issue, we have implemented the following solution, for simplicity I adjusted it to your example:


### organisation/rma > .github/workflows/release.yml
```
name: Release

...

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ...

  deploy:
    uses: organisation/actions/.github/workflows/deploy.yml@master
    needs: build
    secrets:
      GHTokenOfCaller: ${{secrets.MyToken}}
    ...
```

### organisation/actions > .github/workflows/deploy.yml
```
name: Deploy

on:
  workflow_call:
    secrets:
      GHTokenOfCaller:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHTokenOfCaller}}
          repository: 'organisation/actions'
      ...
```

Notes:

- The reason this works is because GITHUB_TOKEN provided by GitHub is scoped to the calling repository (organisation/rma) and does not have access to other private repositories within the same organization.

- To access a private repository (in this case, organisation/actions), a Personal Access Token (PAT) with appropriate permissions is required.

- By passing the PAT (MyToken) from the caller as a secret (GHTokenOfCaller) into the reusable workflow, we can use it in actions/checkout to check out the private repository.

**Reply by aarcro** [reply]
Doesn't this seem backwards? The caller needs to provide a token to actions so it can check itself out?

**Reply by frottke** [reply]
It does indeed feel counterintuitive at first.

My understanding is that the reusable workflow is still executed in the context of the calling repository. The referenced workflow from organisation/actions is not executed in its original repository context. Instead, its contents are effectively incorporated into the caller’s workflow at runtime.

Because GitHub needs to read the workflow file from the other repository, it must authenticate that access explicitly. That is why a token with sufficient permissions is required. The default GITHUB_TOKEN does not grant cross repository access to private repositories, even within the same organization.

Now a few months later, there is a more robust approach than we implemented in our workflows instead of relying on a long lived Personal Access Token.

Instead of using a PAT, you can authenticate via a GitHub App and generate a short lived installation token at runtime. This avoids storing a static credential and provides more granular permission control. The token is created dynamically and expires automatically, which is preferable from a security standpoint.

For example:

```
- uses: actions/create-github-app-token@v2.1.4
  id: app-token
  with:
    app-id: ${{ vars.APP_ID }}
    private-key: ${{ secrets.PRIVATE_KEY }}
    owner: ${{ github.repository_owner }}
```
The generated token can then be accessed via:
`${{ steps.app-token.outputs.token }}
`

This token can be passed to the deploy job, for example as an input such as secrets.GHTokenOfCaller, depending on how the reusable workflow is structured.

This approach keeps credentials scoped and temporary, which is generally preferable from a security perspective.
