### DISCUSSION TITLE
Package version conflict while merging

### DISCUSSION THREAD

**Discussion by ranib2** [community/community#149021] [Actions]
### Select Topic Area

General

### Body

I have two branches in github 
1. main0724 
2. developer0724

i have done a change in developer0724 now the package.json version is 10
and in main0724 the package.json version is 6

and in the yml file of developer0724 and main0724 i have written change the package.json version to +1 now the problem is when i try to create a pull request from developer0724 to main0724 then  it is raising a conflict of package.json because main0724 is  expecting 6 only and it is 10

what to do in this case how to resolve this issue so that i can get no conflicts and also maintain the package.json version +1 condition

**Comment by ssakkout** [comment]
Git sees conflicting changes because both branches have modified the version number differently. you need to make sure your local main0724 branch is up to date by: 
`git fetch origin`
`git checkout main0724`
`git pull origin main0724`
 
Push your changes from developer0724 to the remote repository
`git checkout developer0724`
`git push origin developer0724` Then, create a pull request from developer0724 into main0724.

When Git raises a conflict, it will notify you about the conflicting package.json file. if so check out the PR branch locally
`git checkout main0724`
`git pull origin developer0724`

Open the package.json file, and you will see conflict markers like:
 ```
<<<<<<< HEAD
"version": "6"
=======
"version": "10"
>>>>>>> developer0724

```

determine the new version, and since main0724 expects the version to be incremented by +1, calculate the new version. The highest version is 10, so the next version should be 11

`"version": "11"`

after resolving the conflict, stage the changes and commit, then push the resolved changes to the main0724 branch

**Comment by ranib2** [comment]
Thanks for your quick response but I want dont want to take te higher
version I want to when we are merging from dev to qa if dev is having 11
version that time qa also should have 11 version and it should make 11+1 12
in qa after cicd runs. help me in this

On Mon, 13 Jan 2025 at 05:00, ssakkout ***@***.***> wrote:

> Git sees conflicting changes because both branches have modified the
> version number differently. you need to make sure your local main0724
> branch is up to date by:
> git fetch origin
> git checkout main0724
> git pull origin main0724
>
> Push your changes from developer0724 to the remote repository
> git checkout developer0724
> git push origin developer0724 Then, create a pull request from
> developer0724 into main0724.
>
> When Git raises a conflict, it will notify you about the conflicting
> package.json file. if so check out the PR branch locally
> git checkout main0724
> git pull origin developer0724
>
> Open the package.json file, and you will see conflict markers like:
>
> <<<<<<< HEAD
> "version": "6"
> =======
> "version": "10"
> >>>>>>> developer0724
>
>
> determine the new version, and since main0724 expects the version to be
> incremented by +1, calculate the new version. The highest version is 10, so
> the next version should be 11
>
> "version": "11"
>
> after resolving the conflict, stage the changes and commit, then push the
> resolved changes to the main0724 branch
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/orgs/community/discussions/149021#discussioncomment-11814793>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5NITNDCSLPKOVP2SPTZR7L2KL3K7AVCNFSM6AAAAABVBK2CDGVHI2DSMVQWIX3LMV43URDJONRXK43TNFXW4Q3PNVWWK3TUHMYTCOBRGQ3TSMY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing, or taking any 
action in reliance on the contents of this information is strictly 
prohibited. The information contained in this mail is propriety and 
strictly confidential.

--

**Reply by ssakkout** [reply]
Ah i see now, what you want is an automated system to handle version increments dynamically.
Alright in this case your (.yml file) should automatically detect the highest version in package.json after merging and Increment the version by +1 and commit this change, so you need to update the yml file accordingly:

```
name: Increment Package Version

on:
  push:
    branches:
      - main0724

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Get current version from package.json
      id: get_version
      run: echo "::set-output name=version::$(node -p \"require('./package.json').version\")"

    - name: Increment version
      id: increment_version
      run: |
        current_version=$(node -p "require('./package.json').version")
        new_version=$(node -e "let v='$current_version'.split('.'); v[v.length-1]++; console.log(v.join('.'));")
        echo "New version: $new_version"
        echo "::set-output name=new_version::$new_version"
        # Update package.json
        node -e "let pkg=require('./package.json'); pkg.version='$new_version'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

    - name: Commit and push new version
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add package.json
        git commit -m "chore: bump version to ${{ steps.increment_version.outputs.new_version }}"
        git push
```
