### DISCUSSION TITLE
Github Bot Push Fails Intermittently with “Refusing to Allow” Error

### DISCUSSION THREAD

**Discussion by rebel-jiwon** [community/community#149053] [Actions]
### Select Topic Area

Bug

### Body

I have a GitHub bot with the workflows permission. It works fine most of the time when updating a workflow file, but occasionally, it fails with the following error message:
```
 ! [remote rejected]   branch_a -> branch_b (refusing to allow a GitHub App to create or update workflow `.github/workflows/test.yaml` without `workflows` permission)
Mon, 13 Jan 2025 02:20:10 GMT
error: failed to push some refs to 'https://github.com/DELETED_FOR_SECURITY_REASON'
Mon, 13 Jan 2025 02:20:10 GMT
Error: Process completed with exit code 1.
```

Below is the relevant workflow setup:
```
steps:
  - name: Generate App Token
    id: app-token
    uses: actions/create-github-app-token@v1
    with:
      app-id: ${{ inputs.app-id }}
      private-key: ${{ inputs.private-key }}
      owner: owner

  - name: Get GitHub App User ID
    id: get-user-id
    shell: bash
    run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
    env:
      GH_TOKEN: ${{ steps.app-token.outputs.token }}

  - name: Set up Git user
    shell: bash
    run: |
      git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
      git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

  - name: Checkout repository
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Cherry-pick and push commits
    id: cherry-pick
    shell: bash
    run: |
      git checkout ${{ inputs.release-branch }}
      echo "Cherry-picking commits from ${{ github.event.pull_request.base.sha }} to ${{ github.event.pull_request.merge_commit_sha }}"
      git cherry-pick ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.merge_commit_sha }}
      git push origin ${{ inputs.release-branch }}
```

Has anyone experienced similar issues or can provide guidance on resolving this intermittent error?

Thanks in advance!
