### DISCUSSION TITLE
Manual trigger

### DISCUSSION THREAD

**Discussion by tarunkumarpendem** [community/community#149085] [Actions]
### Select Topic Area

Question

### Body

couldn't able to find manual trigger option even though using workflow dispatch in the default branch

My Workflow:
--------------
name: Install nginx

on:
  workflow_dispatch: # Enables manual triggering

jobs:
  deploy:
    runs-on: [self-hosted, aws]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nginx
        run: |
          sudo apt update
          sudo apt install nginx -y

**Comment by ssakkout** [comment]
1. Check the default branch, go to Settings > Branches in your GitHub repository and confirm which branch is marked as the default and ensure the workflow file is committed to the default branch.
2. ensure you have the appropriate permissions to trigger workflows, and if not done already enable github actions (If github actions is disabled for your repository, the manual trigger won’t appear.) go to Settings > Actions > General in your repository and ensure Actions permissions is set to allow workflows to run.
3. watch out for indentation and ensure the lines are in the correct levels like:
```
name: Install nginx

on:
  workflow_dispatch: # Enables manual triggering

jobs:
  deploy:
    runs-on: [self-hosted, aws]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nginx
        run: |
          sudo apt update
          sudo apt install nginx -y
```
