### DISCUSSION TITLE
Run steps on host when job runs in container

### DISCUSSION THREAD

**Discussion by p5** [community/community#149032] [Actions]
### Select Topic Area

Product Feedback

### Body

Some of my projects build pretty large OCI images using Podman or Docker.

For a far better experience (due to Ubuntu shipping outdated software), I wish to build these images on a Fedora host, so I run the workflows in a privileged container by following [this documentation](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container).

Since my OCI images are large, I am often running into storage space errors, and therefore I would like to cleanup unwanted software from the host.  Actions do exist for this, though I am unable to invoke these actions since I am running inside a container.

I would like to be able to add an option to a step YAML to specify if this should be ran on the runner or container.  

E.G.

```
jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: fedora/fedora:41
    steps:
      - name: Cleanup unwanted software
        runs-on: host # Run this on the Ubuntu host
        run: |
          rm -rf /usr/local/lib/android
          sudo docker image prune --all --force

      - name: Build large image
        runs-on: container # default
        run: |
          dnf install -y docker
          docker build .
```

An alternate solution to this problem would be for GitHub to provide a minimal runner containing only a container runtime, but there are already many requests for this in both orgs/community and actions/runner-images, with no acknowledgement from GitHub staff.
