### DISCUSSION TITLE
Error during npm publish in GitHub Actions

### DISCUSSION THREAD

**Discussion by garotm** [community/community#149189] [Packages] [answered]
### Select Topic Area

Question

### Body

**Description**:
I am encountering an error during the publishing step to the npm registry using GitHub Actions. The specific error message is:

```
npm error 404 Not Found - PUT https://npm.pkg.github.com/cursor-rules-dynamic
npm error 404  'cursor-rules-dynamic@1.0.0' is not in this registry.
```

**Repository**: [garotm/awesome-cursorrules-dynamic](https://github.com/garotm/awesome-cursorrules-dynamic/tree/v1.0.0-alpha.8)

**Workflow File (.github/workflows/publish.yml)**:
```yaml
name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: vscode-extension/package-lock.json
          registry-url: 'https://npm.pkg.github.com'
          scope: '@garotm'
      
      - name: Make CI script executable
        run: chmod +x scripts/ci.sh
      
      - name: Run CI checks
        run: ./scripts/ci.sh
      
      - name: Configure npm for publishing
        working-directory: ./vscode-extension
        run: |
          echo "@garotm:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      
      - name: Publish to GitHub Packages
        working-directory: ./vscode-extension
        run: |
          npm ci
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Package.json (vscode-extension/package.json)**:
```json
{
    "name": "cursor-rules-dynamic",
    "version": "1.0.0",
    "publishConfig": {
        "registry": "https://npm.pkg.github.com",
        "name": "@garotm/cursor-rules-dynamic"
    },
    "dependencies": {
        "ajv": "^8.12.0"
    },
    "devDependencies": {
        "@types/node": "^20.17.12",
        "@typescript-eslint/eslint-plugin": "^7.0.0",
        "@typescript-eslint/parser": "^7.0.0",
        "eslint": "^8.57.0",
        "typescript": "^5.3.3"
    }
}
```

**Steps Taken**:
- Verified that the package name in `package.json` matches the expected format (`@garotm/cursor-rules-dynamic`).
- Checked that the `.npmrc` file is correctly configured.
- Ensured that the GitHub token has the appropriate permissions.

Despite these steps, the error persists. Can anyone point out what I'm missing here?

-garotm
