### DISCUSSION TITLE
How to Automatically Increment Project Version When Dependabot Creates PR for Dependency Updates?

### DISCUSSION THREAD

**Discussion by teneplaysofficial** [community/community#149185] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

I’m using Dependabot to automatically update the dependencies in my project, and I want to know how to ensure that the version of my own project (as defined in package.json) is automatically incremented whenever Dependabot creates a pull request for a new dependency update.

**Comment by AidenJastrzembski** [comment, marked as answer]
Create a version-bump.yml with 
```
name: Version Bump on Dependabot PR

on:
  pull_request:
    types: [opened, reopened, synchronized]
    branches:
      - main  # or your default branch

jobs:
  version-bump:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Increment Version
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Increment patch version
          NEW_VERSION=$(node -p "
            const [major, minor, patch] = '$CURRENT_VERSION'.split('.');
            `${major}.${minor}.${parseInt(patch) + 1}`
          ")
          
          # Update package.json with new version
          npm version $NEW_VERSION --no-git-tag-version

      - name: Commit and Push Changes
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version for dependency updates"
          git push
```

Obviously you'll need to replace the placeholders with your actual information.
