### DISCUSSION TITLE
Ensure Latest amd64 Arch Image for Actions Runner

### DISCUSSION THREAD

**Discussion by barsilver** [community/community#149137] [Actions]
### Select Topic Area

Question

### Body

I’m using the ghcr.io/actions/actions-runner:latest image in my values.yaml file as follows:
```
spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
```
However, I’m encountering an issue where the latest tag pulls the arm64 architecture instead of amd64. This results in the following error from the runner pods:
`exec user process caused: exec format error`
When I run: `docker inspect ghcr.io/actions/actions-runner:latest | grep Architecture`
The output is: `"Architecture": "arm64"`
To work around this, I can specify the image explicitly like this:
```
- name: runner
  image: ghcr.io/actions/actions-runner:2.321.0@sha256:7cde2ec035c9f4cc965f702f434ef6ca39ab027fff7fdab8cc738e933ba392fb
  command: ["/home/runner/run.sh"]
```

However, this approach doesn’t allow me to always use the latest amd64 image, which is what I want. Is there a way to always pull the latest image for the amd64 architecture without hardcoding the specific version or digest?
