### DISCUSSION TITLE
Trigger newly added `pull_request` workflow also for PRs on older branches?

### DISCUSSION THREAD

**Discussion by MarkusMit** [community/community#149244] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a repository with quite some history, and several protected branches, where I want to add a GitHub Workflow which is executed on Pull Requests to (some of) those protected branches.

My hope and understanding (or is it wishful thinking?) would be that I can add the workflow-yaml only to the default branch (`main`) and there specify the branches on which it shall be executed.
_Is this correct, or am I wrong here already?_ 

However, my experience so far is that it doesn't work.

My setup (see [sample repo](https://github.com/MarkusMit/workflow-test-1)):

Branch `main` (=default branch):
```
/
├── .github/
│   └── workflows/
│       └── pr-on-branches.yml *
├── some-folder/
│   └── some-file.txt
└── README.md
```
*) workflow was added "recently" (=after creation of 'otherBranch')

Branch `otherBranch:`
```
/
├── some-folder/
│   └── some-file.txt
└── README.md
```

File `pr-on-branches.yml`:
```yaml
name: Action to run on PRs on Branches

on:
  pull_request:
    types: [ 'opened', 'reopened' ]
    branches: [ 'main', 'otherBranch' ]
    paths:
     - 'some-folder/some-file.txt'

jobs:
  pr_checks:
    runs-on: [ 'ubuntu-latest' ]
    steps:
     - run: 'echo "done."'
```

When I now create a PR on `main` changing the file `some-folder/some-file.txt` the workflow is triggered as expected. ([sample](https://github.com/MarkusMit/workflow-test-1/pull/2))
When I create a PR on `otherBranch` the workflow is not triggered. ([sample](https://github.com/MarkusMit/workflow-test-1/pull/3))

My questions:
- In this setup, should the workflow actually be triggered on PRs to `otherBranch`? 
  - Or do I (really) need to copy the workflow-yaml to all targeted branches (and update them all if needed)?
  - Or is there just something else wrong with my workflow config?
- Is there some documentation, where this is clearly stated?
