### DISCUSSION TITLE
Dependabot not updating groups according update-types

### DISCUSSION THREAD

**Discussion by cecuevas-hblf** [community/community#149207] [Actions]
### Select Topic Area

Question

### Body

Hi all,

I think this is my first question raised on GitHub Community space. I'll try to be specific.

I started to test Dependabot to keep my dependencies up to date on Terraform ecosystem (both providers and modules available on Terraform registry).

So far, the requirement to optimize the number of pull requests created is to set groups depending on the update-types block: patch/minor or major. Patch and minor we are enclosing them within the same PR depending on if it is a provider or a module update. 

This yml config works fine (or at least it do what we need for patch/minor updates):

```
version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      dev-providers:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
      dev-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
``` 
Since I'm forcing the semver-major updated to be ignored, dev-providers group and dev-modules group are creating a separate PR for each one to update either module version or provider version to the latest patch (if applicable) or minor.

![image (6)](https://github.com/user-attachments/assets/fca4a7c9-fe3a-44cd-bb14-1ffd298507f5)
![image (5)](https://github.com/user-attachments/assets/39fe328d-871b-47af-a70a-1873345c1c56)

The problem is that, if I set the "update-types" either to patch, minor or major on any group, it breaks the grouping and actually the log shows that the versions are outdated but is not creating a PR to update them:

```
updater | 2025/01/15 02:14:30 INFO <job_948167305> Checking if tfe  needs updating
  proxy | 2025/01/15 02:14:30 [020] GET [https://registry.terraform.io:443/.well-known/terraform.json](https://registry.terraform.io/.well-known/terraform.json)
2025/01/15 02:14:30 [020] 200 [https://registry.terraform.io:443/.well-known/terraform.json](https://registry.terraform.io/.well-known/terraform.json)
  proxy | 2025/01/15 02:14:30 [022] GET [https://registry.terraform.io:443/v1/providers/hashicorp/tfe/versions](https://registry.terraform.io/v1/providers/hashicorp/tfe/versions)
  proxy | 2025/01/15 02:14:31 [022] 200 [https://registry.terraform.io:443/v1/providers/hashicorp/tfe/versions](https://registry.terraform.io/v1/providers/hashicorp/tfe/versions)
updater | 2025/01/15 02:14:31 INFO <job_948167305> Latest version is 0.62.0
.
.
.
updater | 2025/01/15 02:14:31 INFO <job_948167305> Nothing to update for Dependency Group: 'dev-providers'
```

For reference, this is my module.tf file (I'm not adding input variables there, just need the module invoke to make Dependabot working)

```
  required_providers {
    google = {
      version = "~> 5.37.0"
    }
    tfe = {
      version = "~> 0.58.0"
    }
  }
}
```

Maybe I mispelling something on the patterns section ? All that I need is to have the update of the versions on 2 separate PRs: One for patch/minor and other for major changes.

Thanks in advance for your helps.

Cheers
