### DISCUSSION TITLE
GitHub theme context tags do not work in images due to anonymized URLs

### DISCUSSION THREAD

**Discussion by ghost** [community/community#149293] [Programming Help]
### Select Topic Area

Bug

### Body

We can [specify theme context for images] using [fragments] `#gh-dark-mode-only` and `#gh-light-mode-only`.

GitHub adds an additional [anchor] element around [images] that points to the image URL. GitHub selects the anchor element with the `href` attribute that ends with fragments that do not match the current GitHub theme and hides them.

```css
@media (prefers-color-scheme: dark) {
    :root[data-color-mode="auto"] .entry-content [href$="#gh-light-mode-only"],
    :root[data-color-mode="auto"] .comment-body [href$="#gh-light-mode-only"],
    :root[data-color-mode="auto"] .readme [href$="#gh-light-mode-only"] {
        display: none;
    }
}

@media (prefers-color-scheme: light) {
    :root[data-color-mode="auto"] .entry-content [href$="#gh-dark-mode-only"],
    :root[data-color-mode="auto"] .comment-body [href$="#gh-dark-mode-only"],
    :root[data-color-mode="auto"] .readme [href$="#gh-dark-mode-only"] {
        display: none;
    }
}
```

The [anonymized URLs] don't contain the original fragments, therefore theme context tags cannot work.

## Temporary Resolution

We can add an additional [link] around images and place the fragments on the link instead.

```markdown
[![image text][image url]][url#gh-dark-mode-only]
[![image text][image url]][url#gh-light-mode-only]
```

[specify theme context for images]: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/
[fragments]: https://developer.mozilla.org/en-US/docs/Web/URI/Fragment
[images]: https://spec.commonmark.org/0.31.2/#images
[anchor]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
[anonymized urls]: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls
[link]: https://spec.commonmark.org/0.31.2/#links
