### DISCUSSION TITLE
Action fails (is aborted) with error message "This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`", even though we are *not* using `actions/upload-artifact: v3

### DISCUSSION THREAD

**Discussion by danieltrick** [community/community#149325] [Actions] [answered]
### Select Topic Area

Bug

### Body

As the title says, [our action](https://github.com/tpm2-software/rust-tss-fapi/actions/runs/12814088730/job/35730243577) fails (is aborted) with error message:

> This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`"

But this is a blatant lie! We are **NOT** using `actions/upload-artifact:v3`. We _are_ using `actions/upload-artifact`, but only **`@v4`**.

This can easily be seen here:  
https://github.com/tpm2-software/rust-tss-fapi/blob/main/.github/workflows/cargo-workflow.yaml

Consequently, I think this is **not** a problem on our side, but a faulty check on GitHub's side!

So, please: What do we need to do in order to prevent them from aborting our legitimate actions for inappropriate reasons? 🤔 

Regards.

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by sebastianrath** [comment]
Encountering the same, started happening today. Seems to be a hickup on GitHubs end.

**Reply by danieltrick** [reply]
> Encountering the same, started happening today. Seems to be a hickup on GitHubs end.

Thank you for confirming. Good to know we are not alone 😄

**Reply by danieltrick** [reply]
Tried to restart the action this morning. Seems to go through without problem this time 😌

**Comment by daniellanner** [comment]
We were facing the same issue. Turned out it was a stale `latest` tag on `cache-apt-pkgs-action`. Pinning the package to `awalsh128/cache-apt-pkgs-action@v1.4.3` did the trick.

**Comment by simon-alvalabs** [comment]
This is happening again today. We are not using V3 either.

**Reply by danieltrick** [reply]
> This is happening again today. We are not using V3 either.

I can confirm, this **GitHub Actions bug** appears to be back today 😩

**Reply by baszalmstra** [reply]
Also running into this issue..

**Reply by basavarajloni-envoysolutions** [reply]
Getting same issue, when GitHub will get to fix this issue pipelines are getting failing.

**Reply by anthonyra** [reply, marked as answer]
The suggestion to use `awalsh128/cache-apt-pkgs-action@v1.4.3` worked for me

**Reply by danieltrick** [reply]
> The suggestion to use `awalsh128/cache-apt-pkgs-action@v1.4.3` worked for me

We use `awalsh128/cache-apt-pkgs-action@v1`. Shouldn't that use the latest "1.x" version (currently 1.4.3) automatically?

**Reply by danieltrick** [reply]
> The suggestion to use `awalsh128/cache-apt-pkgs-action@v1.4.3` worked for me

Upgrading `awalsh128/cache-apt-pkgs-action@v1.4.3` from `@v1` to `@v1.4.3` seems to work for me too! 🤗 

I was under the impression that, because of semantic versioning, `@v1` would actually pick the latest version from the "1.x" series, but apparently that wasn't the case 🤔

**Comment by leonluoqi** [comment]
same. anyone can help?

mine:
```
`name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2`
```
