### DISCUSSION TITLE
Variables get masked in one environment

### DISCUSSION THREAD

**Discussion by hknlof** [community/community#149306] [Actions]
### Select Topic Area

Question

### Body

Hi Team,

I have a caller workflow, with same configuration apart from the the name. Both environments contain one variable and one secret.

```env
VARIABLE=staging # production for production
SECRET=staging # production for production
```

I expect in both stages the `GITHUB_STEP_SUMMARY` to render variables. It only does this in production. See the screenshots. Names of steps and upload artifacts are substituting correctly.

**Screenshots**
![2025-01-16_12-45](https://github.com/user-attachments/assets/1b19423c-c258-4a8b-b8b7-888249554b2a)

Workflow YAMLs:
<hr/>

`.github/workflows/deployment-pipeline.yaml`

```yaml
name: Testing GitHub Action Behavior

on:
  push:
    tags:
      - "v0.*"

jobs:
  assets_upload_staging:
    uses: ./.github/workflows/upload-artifacts.yml
    with:
      environment: staging
    secrets: inherit
  assets_upload_production:
    needs: assets_upload_staging
    uses: ./.github/workflows/upload-artifacts.yml
    with:
      environment: production
    secrets: inherit
```

`.github/workflows/upload-artifacts.yml`

```yaml
name: Upload Artifacts Brather
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  assets_upload:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    name: "Upload Assets to ${{ inputs.environment }}"
    steps:
      - id: prepare_env
        name: Prepare environment
        run: |
          echo "HKNLOF_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - id: local_write
        run: |
          cat << EOF > context.txt
          VERSION=${{ env.HKNLOF_SHA }}
          GITHUB_ENV=${{ github.env }}
          SECRET=${{ secrets.SECRET }}
          VARIABLE=${{ vars.VARIABLE }}
          PWD=$PWD
          EOF

      - id: inform_brather
        name: Inform all the Brathers
        run: |
          echo "# Created Context for ${{ inputs.environment }}" >> "$GITHUB_STEP_SUMMARY"
          cat <<EOL >> "$GITHUB_STEP_SUMMARY"
          # Tags for Docker Image
          > $PWD
          > env
          EOL

      - id: more_inform_brather
        name: More Inform all the Brathers
        run: |
          cat <<EOL >> "$GITHUB_STEP_SUMMARY"
          # Tags for Docker Image
          \`\`\`env
          VERSION=${{ env.HKNLOF_SHA }}
          GITHUB_ENV=${{ github.env }}
          SECRET=${{ secrets.SECRET }}
          VARIABLE=${{ vars.VARIABLE }}
          PWD=$PWD
          \`\`\`
          EOL

      - id: upload_assets
        name: Upload Context
        uses: actions/upload-artifact@v4
        with:
          name: "context.${{ inputs.environment }}.txt"
          path: "context.txt"
```
