### DISCUSSION TITLE
Getting a Failed to install dotnet error when using a self-hosted runner

### DISCUSSION THREAD

**Discussion by rfalanga** [community/community#149471] [Actions]
### Select Topic Area

Question

### Body

Over a year ago I set up a self-hosted runner on my Windows 11 Pro desktop. I used it back then, fine. However, I haven't used it in over a year. Yesterday, I tried using it again and discovered that the repo I had set up to use a self-hosted runner, was no longer associated with a self-hosted runner. So, I set it up with a self-hosted runner, then tried to use it. However, it gave me this error:

> Failed to install dotnet, exit code: 1. dotnet-install: The current user doesn't have write access to the installation root 'C:\Program Files\dotnet' to install .NET. Please try specifying a different installation directory using the -InstallDir parameter, or ensure the selected directory has the appropriate permissions.

Looking at my `C:\Program Files` folder, I do see a folder there named `dotnet`. And it has files within it that were created yesterday. I'm confused; it looks like running the GitHub Workflow that would invoke the self-hosted runner, worked. So, why does it tell me this? Here's a snippet from the YAML file:

```yaml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release] # This was [Debug, Release]

    runs-on: self-hosted  # For a list of available runner types, refer to
```
