### DISCUSSION TITLE
Custom action multiline output not working

### DISCUSSION THREAD

**Discussion by davidpaylingwright** [community/community#149535] [Actions] [answered]
### Select Topic Area

Question

### Body

I wrote a workflow containing a step that produces a multiline output to be used by subsequent steps, and it works without issue.

Today, I tried moving the step into its own custom action, for reusability reasons, but the output isn't working.  

At the end of the custom action, I echo the result, so I know the output is there.  Yet, in the calling workflow, the output is empty.

I've checked that the custom action has the property listed in the outputs section, so I'm at a loss as to why the calling workflow isn't getting the output.

Is this a design issue with GH actions?  Can we not output multiline responses from a custom action?

I would hate to have to copy-and-paste this same functionality into every project.

Simple custom action example:
```
name: 'Gets names'
outputs:
  names:
    description: 'The outputted names'
runs:
  using: 'composite'
  steps:     
  - name: Get names
    id: get
    shell: bash
    run: |
      echo 'names<<VALUES' >> $GITHUB_OUTPUT
      echo 'Bob' >> $GITHUB_OUTPUT
      echo 'Julie' >> $GITHUB_OUTPUT
      echo 'VALUES' >> $GITHUB_OUTPUT
      
  - name: Echo names
    shell: bash
    env:
      NAMES: ${{ steps.get.outputs.names }}
    run: echo "$NAMES"
```

Simple workflow example
![workflow2](https://github.com/user-attachments/assets/00efd52c-90cc-4108-ab8b-8369871e4c35)

When run in the workflow, the action echo shows the names without issue (green arrow).
Yet, in the workflow echo, the names are empty (red arrow)
![workflow](https://github.com/user-attachments/assets/b9627192-2bc8-458d-9b96-6eff9737212b)

EDIT:
Btw, I've tried several approaches, such as setting the output to an env variable, but still no luck
![workflow3](https://github.com/user-attachments/assets/86579a1a-55ed-42af-8a1a-4f44fcf13bd6)
