### DISCUSSION TITLE
Help with GitHub Actions -> ACR -> ACI deployment

### DISCUSSION THREAD

**Discussion by jmsbooth** [community/community#149537] [Actions]
### Select Topic Area

Question

### Body

Have a container and terraform in a monorepo for some prototyping. Below is the github actions I am running. The current issue is that the "Log in to Azure CLI" fails when using a service principal with Contributor role. I have recreated the SP and applied the expended JSON to the ARM_CREDS secret with no avail and making better. Im not a developer by trade but working on learning...

```
name: Build, Push, and Deploy Fabric Container

on:
  push:
    branches:
      - main

env:
  TF_LOG: DEBUG
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_NAME: ${{ secrets.ACR_NAME }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  LOCATION: ${{ secrets.LOCATION }}
  KEY_VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
  ARM_CREDS: ${{ secrets.ARM_CREDS }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.ARM_CLIENT_SECRET }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/fabric:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/fabric:latest

  terraform-deploy:
    name: Deploy ACI with Terraform
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Terraform Code
      uses: actions/checkout@v3
      with:
        path: terraform

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Validate Terraform
      run: terraform validate
      working-directory: terraform

    - name: Plan Terraform
      run: terraform plan -out=tfplan \
           -var="resource_group_name=${{ secrets.RESOURCE_GROUP }}" \
           -var="location=${{ secrets.LOCATION }}" \
           -var="acr_name=${{ secrets.ACR_NAME }}" \
           -var="key_vault_name=${{ secrets.KEY_VAULT_NAME }}"
      working-directory: terraform

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
      working-directory: terraform
```
