### DISCUSSION TITLE
How to access the status of a check performed by a Github App?

### DISCUSSION THREAD

**Discussion by gvolpe** [community/community#149686] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi, I would like to conditionally run a workflow, only when the check performed by a Github App has failed. Is this possible? Here's an example: https://github.com/gvolpe/nix-config/pull/285/checks?check_run_id=35955274166

That runs as part of an external Github App. Appreciate any help, thanks! 🙏🏽 

---

I tried this, but it doesn't get triggered by that check failure I want to capture. 

```yaml
on:
  check_run:
    types: [failure]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "DEBUG"
        run: |
          echo "Event state: ${{ github.event.state }}"
          echo "Event desc: ${{ github.event.description }}"
```

Is my only option to try and fetch the relevant information via the [Github API](https://docs.github.com/en/rest/checks/suites?apiVersion=2022-11-28#list-check-suites-for-a-git-reference)?
