### DISCUSSION TITLE
Workflow not appearing under "All Workflows"

### DISCUSSION THREAD

**Discussion by kurmasz** [community/community#149843] [Actions]
### Hi everyone,

I created a new GitHub Classroom assignment that uses a new template repository. This repo has a custom workflow that will only run tests when students explicitly request them to be run (as opposed to running on every push).

With this new assignment, I can't see the workflow under "Actions" --> "All Workflows".  (I can see the workflow in the template repository, but I can't see it in repositories generated for students by Classroom.)

* I used a YAML validator to verify that the workflow file is valid.
* I checked the Settings to verify that Actions are enabled for the repository. 
* The workflow is nearly identical to one I used two years ago.

What should I check next? 

This the .yaml file:

```
name: Web Server Check
on: 
   workflow_dispatch:
   push:
      tags:
         - checkMe*
jobs:
   run-instructor-tests:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - run: curl https://autograder.computing.gvsu.edu/webServerTests.tar --output webServerTests.tar -k
         - run: tar -xf webServerTests.tar
         - run: python my_http_server.py
```

These are the permissions:

![Screenshot 2025-01-23 at 2 58 02 PM](https://github.com/user-attachments/assets/d9b4b57c-bdaa-4cbc-ad1c-fb51593ea431)
