### DISCUSSION TITLE
configiration

### DISCUSSION THREAD

**Discussion by hacisalimdemir** [community/community#149974] [New to GitHub]
Hello, I want to add a slider for my current pH sensor. What code should I add to my configuration file?
I can only read pH with my current code block that I shared below. A slider like this would be great, so that it doesn't go above or below this value. This slider will trigger a relay but it won't work all the time. It will work for 3 seconds and wait 10 seconds until it reaches the desired value.

Thank you so much in advance.

sensor:
  # https://esphome.io/components/sensor/adc.html
  - platform: adc
    pin: A0
    id: ph
    name: "pH Sensor"
    update_interval: 1s
    unit_of_measurement: pH
    accuracy_decimals: 1
    # https://esphome.io/components/sensor/index.html#sensor-filters
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 3
      # Measured voltage -> Actual pH (buffer solution)
      - calibrate_linear:
          - 0.59 -> 7.0
          - 0.71 -> 4.0

**Comment by chiraaax** [comment]
Hi @hacisalimdemir  To add a slider for your pH sensor in your ESPHome configuration and trigger a relay based on its value, you can follow these steps;

---

1. **Create the Slider (Input)**
   You can use an `input_number` to create the slider. The slider will let you control the pH value within a set range, and the value will be used to trigger the relay. Here's how to define it:

```yaml
input_number:
  pH_slider:
    name: "pH Value"
    initial: 7.0
    min: 4.0
    max: 10.0
    step: 0.1
    unit_of_measurement: "pH"
```

- `initial` sets the starting value for the slider.
- `min` and `max` define the range for your pH values.
- `step` controls the increment of the slider.

2. **Create a Relay to Trigger**
   Add a relay that will activate when the pH sensor’s value crosses the slider value. You can define the relay like this:

```yaml
switch:
  - platform: gpio
    pin: D1
    id: pH_relay
    name: "pH Relay"
```

Replace `D1` with the appropriate GPIO pin that your relay is connected to.

3. **Create a Lambda to Trigger the Relay**
   You can use a `lambda` to compare the pH sensor reading with the slider value and trigger the relay for 3 seconds, with a 10-second wait in between.

```yaml
automation:
  - alias: "Trigger Relay for pH Sensor"
    trigger:
      platform: numeric_state
      entity_id: sensor.ph
      above: !lambda 'return id(pH_slider).state;'
    action:
      - switch.turn_on: pH_relay
      - delay: 3s
      - switch.turn_off: pH_relay
      - delay: 10s
```

This automation will check if the pH sensor value is above the slider value, and if so, it will trigger the relay for 3 seconds, followed by a 10-second pause. You can adjust the timings as needed.

4. **Final ESPHome Configuration**
   Here’s how the final configuration might look:

```yaml
sensor:
  - platform: adc
    pin: A0
    id: ph
    name: "pH Sensor"
    update_interval: 1s
    unit_of_measurement: pH
    accuracy_decimals: 1
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 3
      - calibrate_linear:
          0.59 -> 7.0
          0.71 -> 4.0

input_number:
  pH_slider:
    name: "pH Value"
    initial: 7.0
    min: 4.0
    max: 10.0
    step: 0.1
    unit_of_measurement: "pH"

switch:
  - platform: gpio
    pin: D1
    id: pH_relay
    name: "pH Relay"

automation:
  - alias: "Trigger Relay for pH Sensor"
    trigger:
      platform: numeric_state
      entity_id: sensor.ph
      above: !lambda 'return id(pH_slider).state;'
    action:
      - switch.turn_on: pH_relay
      - delay: 3s
      - switch.turn_off: pH_relay
      - delay: 10s
```
---

### Explanation:
- The `input_number` creates the slider with a minimum value of 4 and a maximum of 10 for pH values.
- The relay (`switch`) triggers based on whether the pH sensor value exceeds the slider value.
- The `automation` ensures that the relay only turns on for 3 seconds and then waits 10 seconds before it can trigger again.

This should allow you to have the functionality you need for controlling the relay based on your pH sensor reading and slider value!
