### DISCUSSION TITLE
wordle UI

### DISCUSSION THREAD

**Discussion by gilroy70** [community/community#150043] [Programming Help]
### Select Topic Area

Question

### Body

anyone has the a code  for the New York Times Wordle UI ?

**Comment by chiraaax** [comment]
Hi! @gilroy70, You can replicate a basic version of the Wordle UI using HTML, CSS, and JavaScript. While I can't provide the exact New York Times Wordle UI code (since it is proprietary)

Here's a simplified example of the UI structure using HTML and CSS. It won't have the game logic, but this will help you get started with the layout and styles:

### HTML (index.html):
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wordle UI</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="game-container">
        <div class="board">
            <!-- Rows for guesses -->
            <div class="row">
                <div class="cell"></div>
                <div class="cell"></div>
                <div class="cell"></div>
                <div class="cell"></div>
                <div class="cell"></div>
            </div>
            <div class="row">
                <div class="cell"></div>
                <div class="cell"></div>
                <div class="cell"></div>
                <div class="cell"></div>
                <div class="cell"></div>
            </div>
            <!-- Add more rows as needed -->
        </div>
    </div>
    <script src="script.js"></script>
</body>
</html>
```

### CSS (styles.css):
```css
body {
    font-family: Arial, sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-color: #f4f4f4;
    margin: 0;
}

.game-container {
    display: flex;
    flex-direction: column;
    align-items: center;
}

.board {
    display: grid;
    grid-template-columns: repeat(5, 50px);
    grid-gap: 10px;
    margin-bottom: 20px;
}

.row {
    display: flex;
}

.cell {
    width: 50px;
    height: 50px;
    background-color: #ddd;
    border: 1px solid #333;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 20px;
    font-weight: bold;
    transition: background-color 0.3s;
}

.cell.correct {
    background-color: green;
}

.cell.present {
    background-color: yellow;
}

.cell.absent {
    background-color: gray;
}
```

### JavaScript (script.js):
```javascript
// Sample code to add interactivity (e.g., for clicking letters and submitting guesses)
// This is just a basic idea of adding some dynamic behavior

document.addEventListener("DOMContentLoaded", () => {
    const cells = document.querySelectorAll('.cell');

    // Example of setting a guess in the first row
    function setGuess(row, letters) {
        const rowCells = document.querySelectorAll(`.row:nth-child(${row}) .cell`);
        letters.split('').forEach((letter, index) => {
            rowCells[index].textContent = letter;
            rowCells[index].classList.add('present');  // For example, yellow
        });
    }

    setGuess(1, 'HELLO');
});
```

This is just a basic layout. To make a fully functional Wordle game, you’d need additional logic for managing guesses, validating inputs, and checking for word matches.
