### DISCUSSION TITLE
Improving CI Build Time

### DISCUSSION THREAD

**Discussion by nat-ray** [community/community#150180] [Actions] [answered]
### Select Topic Area

Question

### Body

My team is currently doing Docker builds using the docker/build-push-action. Our build job looks something like this: 

```
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker BuildX
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        driver-opts: network=host 
        endpoint: ${{ steps.build.outputs.build-context }}
        install: false
        use: true

    - name: Docker metadata
      id: image-meta
      uses: docker/metadata-action@v5.5.1

    - name: Build cached image
      uses: docker/build-push-action@v6.9.0
      env:
        DOCKER_BUILD_CHECKS_ANNOTATIONS: false
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: ${{ inputs.dockerfile }}
        push: true 
        load: false 
        target: ${{ inputs.docker_build_target }}
        build-args: ${{ inputs.docker_build_args }}
        tags: ${{ steps.image-meta.outputs.tags }}
        labels: ${{ steps.image-meta.outputs.labels }}
        platforms: ${{ inputs.docker_build_platform }}
        cache-from: type=gha,scope=${{ inputs.docker_build_target }}
        cache-to: ${{ inputs.build_cache_to }}
```

We use a multi-stage Dockerfile, separating initial build from tests and what is deployed. Our initial build takes around 4 minutes, and then with all tests and scanning the total pipeline takes ~15 minutes. We are trying to find ways to further improve our build time. 

One idea we tried was to create a new base image with all dependencies pre-installed. When the Docker build runs, we then start from the new base image to prevent having to download those dependencies. That base image must first be pulled from our container registry to the self-hosted runner however, which takes time and only offers modest improvement to build time.

Our self-hosted runners are not nearing limits on memory of CPU. All of our io operations are also taking place on an ephemeral volume in memory to improve performance there. 

Is there anything else that is recommended from a best-practice point of view?
