### DISCUSSION TITLE
The Copilot's "Agent Mode" does not edit files in DevContainers

### DISCUSSION THREAD

**Discussion by hhimanshu** [community/community#150177] [Copilot Conversations]
### Select Topic Area

Bug

### Body

Hello team,

I am using the Insiders build with the following spec
```
Version: 1.97.0-insider (Universal)
Commit: f5782f528629d4200a964cc652055a4da43a7eb1
Date: 2025-01-24T05:04:36.365Z
Electron: 32.2.7
ElectronBuildId: 10660205
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.4.0
```

For past few days, I see an agent-mode in my Copilot window. This works great when the project is not leveraging DevContainers. As soon as I try to use this feature in DevContainers, it consistently complains about having issues in accessing the file system. I have added the screenshot from my latest effort to give you visibility into what I am experiencing.

<img width="623" alt="Screenshot 2025-01-29 at 10 25 41 AM" src="https://github.com/user-attachments/assets/f212ee6f-5fa3-40c3-a31f-f814bd27cad0" />

If there is anything in the `devcontainer.json` that needs to change, please let me know. Here is the content of my current `devcontainer.json`
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/python
{
	"name": "Backend",
	"dockerComposeFile": "docker-compose.yml",
	"service": "app",
	//"workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",
	"workspaceFolder": "/workspaces",
	"features": {
		"ghcr.io/devcontainers/features/github-cli:1": {},
		"ghcr.io/stuartleeks/dev-container-features/shell-history:0": {},
		"ghcr.io/nils-geistmann/devcontainers-features/zsh:0": {},
		"ghcr.io/jsburckhardt/devcontainer-features/uv:1": {},
		"ghcr.io/jsburckhardt/devcontainer-features/ruff:1": {}
	},
	// Add git credentials sharing
	"customizations": {
		"vscode": {
			"settings": {
				"git.enableCommitSigning": false
			},
			"extensions": [
				"ms-azuretools.vscode-docker",
				"mongodb.mongodb-vscode",
				"charliermarsh.ruff"
			]
		}
	},
	"mounts": [
		"source=${localEnv:HOME}${localEnv:USERPROFILE}/.gitconfig,target=/home/vscode/.gitconfig,type=bind,consistency=cached",
		"source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind"
	],
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [
		27017
	],
	// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "chmod a+x .devcontainer/postCreate.sh && .devcontainer/postCreate.sh",
	// Configure tool-specific properties.
	// "customizations": {},
	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	"remoteUser": "vscode"
}
```

and here is my `docker-compose.yml`
```
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    depends_on:
      mongodb:
        condition: service_healthy
        required: true
    environment:
      MONGODB_URL: mongodb://mongodb:27017/?replicaSet=rs0
      MONGODB_APP_DB_NAME: app_db
      TEST_DB_NAME: test_db

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
```

Looking forward to learning and fixing this issue.
Thank you in advance
