### DISCUSSION TITLE
Sharing environment accross jobs

### DISCUSSION THREAD

**Discussion by axelopale** [community/community#150254] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi, 

I have a workflow that uses two reusable workflows:

```
name: Deploy to Staging

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_js_assets:
    name: Build JS assets
    uses: <org>/kube/.github/workflows/build_js_assets.yml@main
    with:
      application: investor
    secrets: inherit

  build_and_deploy:
    name: Deploy
    uses: <org>/kube/.github/workflows/build_docker_and_deploy.yml@main
    needs: build_js_assets
    with:
      application: investor
    secrets: inherit
```

I would like to set `environment: staging` globally on the caller workflow. And the callees would inherit of this value because I have vars and secrets stored in the "staging" environment in my repo settings and I need my children workflows to access these values.

Possible?  

Thanks

**Comment by axelopale** [comment, marked as answer]
I'm answering my own question in case someone has the same question: it has to be done in the children workflows: 

```
name: Build and Deploy

on: 
  workflow_call:
    inputs:
      environment: 
        required: true
        type: string
jobs: 
  build_release:
    name: Build docker and deploy
    environment: ${{ inputs.environment }}
```
The environment is passed to the child from the parent.
