### DISCUSSION TITLE
How to use workflow env variables

### DISCUSSION THREAD

**Discussion by axelopale** [community/community#150355] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi there, 

Quick question: I have two workflow environment variables that I need to pass to a reusable workflow:

```
name: Deploy

on:
  workflow_dispatch:
env:
  environment: staging
  application: myapp
jobs:
  first_job:
    # ......
  build_js:
    uses: <org>/kube/.github/workflows/build_js_assets.yml@main
    with:
      application: $application
      environment: $environment
```

When doing so, I received "$application" and "$environment" in the child workflow. 
I tried to 
```
    with:
      application: ${{ env.application }}
      environment: ${{ env.environment }}
```
instead but I get an error: 
`Unrecognized named-value: 'env'.`
Seems to be a context issue. 

Any idea how to fix this? 
Thanks

**Comment by svaraborut** [comment]
It seems like `env` cannot be used inside `jobs.<job_id>.with` but only inside `jobs.<job_id>.steps.with` see [the official documentation](https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#context-availability). It is quite weird but those are the specs.

Either you create a step within the job, move those variables to `vars`, or use this [workaround](https://stackoverflow.com/questions/73797254)

### Risks of using the workaround
Despite being counterintuitive, I would assume there are sane security considerations behind this constraint and by using this workaround you may be exposing yourself to some potential risks.

**Reply by axelopale** [reply]
Thanks @svaraborut , very clear. 

Unless I'm mistaken, I cannot use steps in the "build_js" job as I'm calling a reusable workflow.

**Reply by svaraborut** [reply]
Yes, I would assume so from the docs.

_For the inherent reason of why secrets can be passed but env variables no, I would leave that to a more knowledge Githubber 😉. Dk if here we have a label for that._

**Reply by svaraborut** [reply]
Btw I stumbled uppn this.

Duplicate of https://github.com/orgs/community/discussions/26671

**Comment by thegr8Arin** [comment]
### Hi @axelopale,

_Thank you for reaching out! I understand the issue you're facing with passing environment variables to a reusable workflow. Let me provide a solution and clarify the constraints._

it You're trying to pass environment variables (environment and application) defined at the workflow level to a reusable workflow using the with keyword. **However, the env context cannot be directly used in the jobs.<job_id>.with section, as it is only available in jobs.<job_id>.steps.with.**

To work around this limitation, you can use the vars context instead of env. Here's how you can modify your workflow:

```
name: Deploy

on:
  workflow_dispatch:
env:
  environment: staging
  application: myapp
jobs:
  first_job:
    # ......
  build_js:
    uses: <org>/kube/.github/workflows/build_js_assets.yml@main
    with:
      application: ${{ vars.application }}
      environment: ${{ vars.environment }}
```
**Using vars Context:** The vars context allows you to access variables defined at the workflow level. By replacing env with vars, you can pass the values to the reusable workflow.

**No Need for Additional Steps:** This approach avoids the need to create additional steps within the job, which is especially useful when calling reusable workflows.

Regarding your follow-up question about not being able to use steps in the build_js job when calling a reusable workflow, you're correct. When using uses to call a reusable workflow, you cannot define steps within that job. The workaround above avoids this limitation by leveraging the vars context directly.

As @svaraborut mentioned, there may be security considerations behind this constraint. While the workaround is functional, ensure you evaluate any potential risks, such as exposing sensitive data, when using this approach.

Let me know if you have further questions or need additional assistance!

**Best regards,
Aryan**

**Reply by axelopale** [reply]
Awesome, thanks @thegr8Arin, I try this and let you know.

**Reply by axelopale** [reply]
Sorry, not working: 

```
Inputs
    application: 
    environment: 
    build_version: d6c9693d8a70
```

Do I need to create the "environment" and "application" variable in the repo's variables?

**Reply by thegr8Arin** [reply]
Hi @axelopale,

Thanks for trying the solution! Based on your latest comment, it seems the vars context isn’t resolving the variables correctly. Let’s clarify and fix this:

try these steps to resolve

Define Variables in the Repository:
`Go to your repository’s Settings > Secrets and variables > Actions.`
Under Variables, add environment and application with their respective values (staging and myapp).

Update the Workflow:
Use the vars context to reference the repository variables:
```
**yaml**
name: Deploy
on:
  workflow_dispatch:
jobs:
  first_job:
    # ......
  build_js:
    uses: <org>/kube/.github/workflows/build_js_assets.yml@main
    with:
      application: ${{ vars.application }}
      environment: ${{ vars.environment }}
```

Ensure Correct Inputs in the Reusable Workflow:
In the reusable workflow (build_js_assets.yml), ensure the inputs are defined correctly:
```
**yaml**
on:
  workflow_call:
    inputs:
      application:
        required: true
      environment:
        required: true
```

Test the Workflow:
Trigger the workflow and verify that the inputs are passed correctly.

Repository variables are accessible via the vars context and can be used in jobs.<job_id>.with.
This approach avoids the limitations of the env context and ensures the values are passed correctly to the reusable workflow.

Let me know if this resolves the issue or if you need further assistance!

Best regards,
Aryan.

**Reply by axelopale** [reply]
Right OK, this is a different process then.

May be I should explain what I try to achieve: in the main workflow, I want to set the current environment, once, globally, (staging, preprod or prod) and this environment value should be accessible by the sub-workflows. So the sub-workflows will access the variables and secrets for the given environment. 

EDIT: but no problem, it works without it. I'm just trying to super optimize my pipelines.

**Reply by thegr8Arin** [reply, marked as answer]
Hi @axelopale,

Thanks for clarifying your goal! If you want to set the environment (e.g., staging, preprod, prod) once in the main workflow and make it accessible to all sub-workflows, here’s how you can achieve this:

Solution: Use outputs to Pass Values to Reusable Workflows

Define the Environment in the Main Workflow:
Set the environment as a job output in the main workflow:
```
**yaml**
name: Deploy
on:
  workflow_dispatch:
jobs:
  set_env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - name: Set environment
        id: set_env
        run: echo "environment=staging" >> $GITHUB_OUTPUT
  build_js:
    needs: set_env
    uses: <org>/kube/.github/workflows/build_js_assets.yml@main
    with:
      environment: ${{ needs.set_env.outputs.environment }}
```

Access the Environment in the Reusable Workflow:
In the reusable workflow (build_js_assets.yml), define the input and use it:
```
**yaml**
on:
  workflow_call:
    inputs:
      environment:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use environment
        run: echo "Environment is ${{ inputs.environment }}"
```


The `set_env job` sets the environment value and makes it available as an output.
The `build_js job` passes this output to the reusable workflow via with.
This approach ensures the environment value is set once and reused across all sub-workflows.

Optimization Tip:
If you have multiple reusable workflows, you can reuse the `set_env job’s` output for all of them, avoiding redundancy.

Let me know if this meets your needs or if you need further assistance!

Best regards,
Aryan.

**Reply by axelopale** [reply]
Thanks
It would be nice to allow the environment to be set globally in a future version. 
Like:

```
name: Deploy to Staging

on:
  pull_request:
    branches:
      - dev

environment: staging

jobs:
...
```
