### DISCUSSION TITLE
apparent BuildKit cache corruption

### DISCUSSION THREAD

**Discussion by qrkourier** [community/community#150429] [Actions] [answered]
### Select Topic Area

Question

### Body

Several times, I've found it necessary to invalidate the BuildKit cache to work around an apparent cache corruption issue. The failed check can re-run to successful completion after invalidating the cache with the `gh cache delete` command.

The symptom is this Actions step fails.

```yaml
      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/
          file: ./docker-images/ziti-console-assets/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
          push: true
          # ziti controller always binds at /zac and trailing slash is necessary to qualify Angular runtime paths in index.html
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
            BASE_HREF=/zac/
```

from workflow run: https://github.com/openziti/ziti-console/actions/runs/13076486719/job/36498117215

This is the specific Dockerfile directive that occasionally fails until the BuildKit cache is invalidated.

```docker
RUN --mount=type=cache,target=/usr/src/app/node_modules \
    --mount=type=cache,target=/usr/src/app/.angular/cache \
    npm install --omit=optional && \
    ng build ziti-console --base-href ${BASE_HREF} --configuration "production"
```

from Dockerfile: https://github.com/openziti/ziti-console/blob/app-ziti-console-v3.8.0/docker-images/ziti-console-assets/Dockerfile

This is the cache invalidation workaround command.

```bash
gh --repo openziti/ziti-console cache list --key buildkit-blob-1-sha256 --json id --jq '.[]|.id' \
| xargs -rl gh --repo openziti/ziti-console cache delete
```
