### DISCUSSION TITLE
Deploying Nextjs with `output: 'standalone' in nextConfig to Github Pages with Github Actions gives 404

### DISCUSSION THREAD

**Discussion by davidde** [community/community#150552] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I fixed all build problems, but afterwards it resulted in a 404 page, which is not straightforward to debug.
Everything works fine locally, and the website was also deployed OK to Vercel, but the free plan was apparently not enough for some simple testing in production, so I'm trying to make the switch to Github Pages.
I've been trying to fix the deployment for hours, so I could definitely use some help. I'm likely just missing some small detail, but after already fixing dozens of small details I'm kinda lost as to what's left to fix... The relevant files are below.

Current `next.config.mjs`:
```mjs
const isProd = process.env.NODE_ENV === 'production';

/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  basePath: isProd ? '/ethblox' : undefined,
  assetPrefix: '/ethblox/',
  trailingSlash: true,

  async redirects() {
    return [
      {
        source: '/',
        destination: '/mainnet',
        permanent: true,
      },
    ]
  },
};

export default nextConfig;
```

Current `.github/workflows/nextjs.yml`:
```yml
# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
        # IF YOU DO NOT UNCOMMENT THIS SECTION, IT WILL IGNORE THE `next.config.mjs` FILE:
        # with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          # static_site_generator: next
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      - name: Build with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build
        env:
          REACT_APP_ALCHEMY_API_KEY: ${{ secrets.REACT_APP_ALCHEMY_API_KEY }}
          REACT_APP_ETHERSCAN_API_KEY: ${{ secrets.REACT_APP_ETHERSCAN_API_KEY }}
      - name: Copy public and static folders
        run: |
          cp -r ./public ./.next/standalone/
          cp -r ./.next/static ./.next/standalone/.next/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.next/standalone

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
Current `scripts` in `.package.json`:
```json
"scripts": {
  "dev": "next dev -p 3005",
  "build": "next build",
  "start": "node .next/standalone/server.js",
  "lint": "next lint"
},
```
I think the problem could be that Github Actions doesn't correctly serve the application with `node .next/standalone/server.js` instead of `next start`, but I'm not sure. I don't know how to check this and how to modify or configure it if it is the case.

You can find the full github repo here: https://github.com/davidde/ethblox. In the Actions pane you can quickly check what dozens of combinations I've already tried ;)

Any help would be greatly appreciated!
