### DISCUSSION TITLE
Best way to build workflows with dependencies that share a lot of common builds, that should be kept independent

### DISCUSSION THREAD

**Discussion by VariantXYZ** [community/community#150551] [Actions]
### Select Topic Area

Question

### Body

I've been working on a project to build and package things for PowerPC Macs using a cross-compilation toolchain [here](https://github.com/VariantXYZ/gbdev-powerpc-apple-darwin8).

It basically works by having a bunch of cross-compilation instructions for different tools and libraries that may be shared between multiple things. For example:
* Building git requires curl, iconv, OpenSSL, and zlib
* Building OpenSSL requires just zlib
* Building OpenSSH requires OpenSSL and zlib

So as you can see there's a lot of common dependencies and I want to make sure these are 'documented' within the jobs themselves, so I've done things like this:

(for OpenSSH)
```
jobs:
  # zlib:
  #  uses: ./.github/workflows/build_zlib.yml
  
  openssl:
    uses: ./.github/workflows/build_openssl.yml

  build:
    runs-on: ubuntu-latest
    container: ghcr.io/variantxyz/gcc-powerpc-apple-darwin8:build-gcc-14.2-macosxsdk10.4u
    needs:
      - openssl
      #- zlib # Included within openssl
```

This is... alright, but I don't believe it's ideal: Every dependency like this actually has duplicate executions of the 'same' job, ideally we should be reusing the jobs that don't change. Git and OpenSSL both rely on Zlib, and because Git relies on OpenSSL, Zlib should really only need to be built once... but it's actually built two separate times (git / zlib and git / openssl / zlib)

So now, as I'm trying to create a pre-packaged "set of packages" (e.g., 'git' + 'openssh'), I'm realizing that I'll need to have a lot of duplicate entries. I'm sure I can figure out some workarounds, but I also realize I may just be missing some key features of Actions that could help me maintain this in a sane way.

My current setup has me building zlib 4 times for Git:

<img width="332" alt="image" src="https://github.com/user-attachments/assets/b841e04f-653c-43fb-bc89-15170bf5b03e" />
