### DISCUSSION TITLE
Can't "apk add" on arm64/linux Alpine

### DISCUSSION THREAD

**Discussion by jamesarosen** [community/community#150653] [Actions]
### Select Topic Area

Bug

### Body

Starting some time in the last few days, our GitHub Actions builds started failing. I've reduced the problem to the following workflow:

```yaml
name: PR Workflow
on:
  pull_request:
jobs:
  debug-container:
    name: Build Docker Container Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker buildx build --platform linux/arm64 . -f ./Dockerfile
```

and Dockerfile:
```Dockerfile
FROM --platform=linux/arm64 node:22-alpine AS builder
RUN apk add --no-cache curl
CMD ["curl", "https://www.google.com"]
```
This fails reliably with
```
Dockerfile:2
--------------------
   1 |     FROM --platform=linux/arm64 node:22-alpine AS builder
   2 | >>> RUN apk add --no-cache curl
   3 |     CMD ["curl", "https://www.google.com/"]
   4 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache curl" did not complete successfully: exit code: 255
```

#### Is it the platform?

Yes

If I remove the `--platform` argument from the `docker buildx build` command and the `FROM` command, the build passes. Either is enough to trigger the error.

#### Is it a bad TLS certificate?

Probably not.

I tried changing the `apk add` to ignore TLS problems:

```Dockerfile
RUN apk add --no-cache --allow-untrusted --no-check-certificate --repository http://dl-cdn.alpinelinux.org/alpine/v3.20/main curl
```

The error still occurs.

#### Does it happen on other images?

It happens on `node:20-alpine` as well.
