### DISCUSSION TITLE
Using actions and env variables

### DISCUSSION THREAD

**Discussion by nikhiljk-centrica** [community/community#150685] [Actions]
### Select Topic Area

Question

### Body

Hi All,

I was trying to use GitHub action matrices to create a deployment to different environments as there are different env variables for each stage

I saw in thread #34831 that a solution was provided where the env variables are set up in the script. I would however like to keep my env variables all separate and not in a single environment.

```
  push-to-azure:
    name: Push to dev
    runs-on: ubuntu-latest
    matrix:
      stage: [ dev, test, pre-prod, production ]
    environment: ${{ matrix.stage }}
    needs: [ generate-build, generate-tag ]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: functionApps.zip
          path: /tmp/

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'


      - name: Run azure blob upload command
        run: >
          az storage blob upload --account-name storageaccount${{ vars.STAGE_NAME }} --container-name function_release-${{ vars.STAGE_NAME }} --file /tmp/functions.zip --name build/latest/function.zip  --overwrite true 
```
