### DISCUSSION TITLE
Github Actions Artifacts upgrade to v4 site not found

### DISCUSSION THREAD

**Discussion by zvulun** [community/community#150738] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi - I understand that Github has upgraded to v4 of some of the Github Actions Artifacts. I have tried to understand how to rewrite the "Action" lines in my workflow script that publishes our private site. (I am a technical writer using Asciidoc/Antora, but I am not a developer, and got a lot of assistance to make this script work). 

Could these problems be because we are using Github Enterprise Cloud?

The workflow runs, the artifact is created properly, and the site is deployed, but I can't find the site at the URL specified in the Github Settings > Pages screen (docs.inextechnologies.com) - I get a 404 error. Tried usual tips for 404 errors (clearing cache, etc.) but didn't help. Github Pages settings were not changed and seem ok; DNS checks ok.

Please advise - thanks in advance for any help you can suggest.

The old workflow's publish.yml file's last few lines were this:
```
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v2
      with:
        path: build/site
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
```
I tried changing the last few lines to this:
```
- name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: build/site
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
```

Here is the whole script in case there might be interactions with other commands that would help for discovering the problem:

```
name: Publish to GitHub Pages
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
    - name: Set the token as environment variable
      run: echo "GIT_CREDENTIALS=https://x-access-token:${{ steps.app-token.outputs.token }}@github.com" >> "$GITHUB_ENV"
    - name: Configure Pages
      uses: actions/configure-pages@v3
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install Antora
      run: npm i antora
    - name: Recreate CNAME file
      run: echo docs.inextechnologies.com > build/site/CNAME
    - name: Generate Site
      run: npx antora antora-playbook.yml --stacktrace
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: build/site
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
```
