### DISCUSSION TITLE
Add Input Payload information to Workflow or Job

### DISCUSSION THREAD

**Discussion by tbuttier** [community/community#150753] [Actions]
### Select Topic Area

Question

### Body

Hello
I have a workflow triggered by another workflow with the **repository_dispatch** event.

Workflow A sends to worflow B a payload with an issue number, but I'm not able to have the payload information used in Workflow or Job name.

In workflow B I can correctly print the issue number in script, but the job does not get the information.  Any Idea?

```
run-name:  My Workflow  for Issue # ${{ github.event.client_payload.issue_number }}  <= Nothing displayed

env:
  REPO_TAG: 'main'
  ISSUE_NUMBER: ${{ github.event.client_payload.issue_number }}
jobs:  
    get-issue-information:     
        name: Get Issue Information for Issue #${{ env.ISSUE_NUMBER }}   <= Nothing displayed
        runs-on: npm-runner
        steps:       
          - name: Get issue content 
            id: get-issue-content
            uses: actions/github-script@v7
            with:
             github-token: ${{ secrets.PAT_GITHUB }}
             script: |
              const issue_number = ${{ github.event.client_payload.issue_number }}
              console.log(`Issue Number: ${issue_number}`)                            <= That works
```

Thanks
