### DISCUSSION TITLE
Some questions about the Wap_Project_Directory

### DISCUSSION THREAD

**Discussion by rfalanga** [community/community#150723] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm working on learning how to perform a CI/CD on a Windows application, using the workflow template provided by GitHub, which I intend to run using a self-hosted runner on a Windows server. The last step in that template is this:

```yaml
- name: Upload build artifacts
  uses: actions/upload-artifact@v4   
  with:
     name: MSIX Package
     path: ${{ env.Wap_Project_Directory }}\AppPackages 
```

The `Wap_Project_Directory` is an environmental variable defined earlier in the YAML template. I went to the GitHub Docs to read more about `Wap_Project_Directory`, but nothing is there. Performing searches, I get the impression that the `Wap_Project_Directory` is a subdirectory in the repository. Is that correct? Is it only allowed to be there? I would rather deploy the .MSIX file on a network share, rather than a subdirectory in the repo.
