### DISCUSSION TITLE
branch names with @ are not processed

### DISCUSSION THREAD

**Discussion by llrs-roche** [community/community#150817] [Actions]
### Select Topic Area

Question

### Body

I know I can use an action like:

```
jobs:
    id:
        name: ID-name
        uses: org/repo/path/file.yaml@branch_name
```

However, when the branch name has an @ the workflow fails (we use branch names such as fix@main) to signal where the fix is going to get merged (main in this example)

```
jobs:
    id:
        name: ID-name
        uses: org/repo/path/file.yaml@fix@main
```

The error message I [get is](https://github.com/insightsengineering/teal.modules.clinical/actions/runs/13175975775): 

> [Invalid workflow file: .github/workflows/check.yaml#L24](https://github.com/insightsengineering/teal.modules.clinical/actions/runs/13175975775/workflow)
> invalid value workflow reference: too many '@' in workflow reference

I then need to use the SHA number which when I'm working on updating/fixing `org/repo/path/file.yaml` I need to change each SHA for each commit. 
Is there any workaround to make it easier to use these branches (besides the obvious solution of not using this branch naming scheme)?
