### DISCUSSION TITLE
.github/dependabot.yml fails to parse

### DISCUSSION THREAD

**Discussion by majkel89** [community/community#150814] [Actions]
### Select Topic Area

Bug

### Body

My [dependabot.yml](https://github.com/majkel89/ModBusExporter/blob/main/.github/dependabot.yml)

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/ModBusExporter.Api/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
```

[fails to parse](https://github.com/majkel89/ModBusExporter/runs/36750101790) due to

```
The property '#/' did not contain a required property of 'updates'
```

https://github.com/majkel89/ModBusExporter/network/updates

I have [other repository with similar configuration](https://github.com/majkel89/RestApiExporter/blob/main/.github/dependabot.yml) that parses correctly.

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/RestApiExporter.Api/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
```

Looks like a bug to me.

Please help.
