### DISCUSSION TITLE
Access private npm.pkg.github.com package from GitHub App's permission

### DISCUSSION THREAD

**Discussion by hi120ki** [community/community#150894] [Packages]
### Select Topic Area

Product Feedback

### Body

We are publishing proprietary internal npm packages with GitHub Packages on Enterprise Cloud Organization.
However, there are two publication options for these npm packages: "internal" and "private." "Internal" packages are unconditionally exposed within the Organization, making them accessible from GitHub Actions in any repository. 
To make this situation more secure, we are working on publishing packages as "private" and establishing restricted access methods.
In other words, we are attempting to restrict access to a "private" npm package published from a certain repository to a specific GitHub repository and Action that has access to a particular GitHub App Private Key.

Specifically, we tried to use the GitHub App Installation Token with actions/create-github-app-token to retrieve "private" npm packages from another repository.

Here is the overall workflow.

```yaml
name: private-npm-package-install

on:
  workflow_dispatch:

jobs:
  private-npm-package-install:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: setup custom registry
        run: |
          echo "@<organization>:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ steps.app-token.outputs.token }}" >> ~/.npmrc

      - run: npm install @<organization>/<package>@1.0.0
```

We have granted the GitHub App read permissions for Repository Package. When we tried this, we encountered the following error:

```
Permission installation not allowed to Read organization package
````

This doesn't seem to be the intended behavior. We certainly granted the GitHub App reading permissions for packages published in a certain repository. It is expected to work even if the package's publication status is Private.

However, internally, GitHub is likely using the "Organization Package" permissions. Since this has not been fully implemented yet, it's not documented, nor does it actually work for GitHub App's permission control.

This issue is blocking the challenge of securely using GitHub Package in an enterprise environment. Could you provide a solution for this or prioritize the implementation of "Organization Package" permissions?

Thank you.
