### DISCUSSION TITLE
Github actions reusable workflow secrets inheritance not working

### DISCUSSION THREAD

**Discussion by guillermomolla** [community/community#150902] [Actions]
### Select Topic Area

Bug

### Body

I am working on creating a system with Github actions for some tasks with docker and I am having some issues with it.
I have 2 files in 2 diferent repos:

workflow.yml:

```
on: workflow_call
env:
  AWS_ACCESS_KEY_ID: {{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: {{ secrets.AWS_DEFAULT_REGION }}
  AWS_DEFAULT_REGION: {{ secrets.AWS_DEFAULT_REGION }}
  REGISTRY: {{ secrets.DOCKER_REGISTRY }} #url of docker registry on ecr
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: ECR credentials
        run: aws ecr get-login-password | docker login -u AWS "$REGISTRY" --password-stdin $REGISTRY
```

callworflow.yml:

```
on: workflow_dispatch
jobs:
  test:
    uses: organization/example-repo/.github/workflows/workflow.yml@main
    secrets: inherit
```

On trying to launch the reusable workflow from actions I get an error:

> Error: Cannot perform an interactive login from a non TTY device

In my organization I have all secrets. Even doing the process directly on a workflow instead of using the reusable workflow call works.
So I am misunderstanding something or what is happening? The documentations says something like:

> If the secrets are inherited by using secrets: inherit in the calling workflow, you can reference them even if they are not explicitly defined in the on key. 

I also tried to add the envs to the callworkflow.yml file or even calling directly  {{ secrets.DOCKER_REGISTRY }} on the workflow.yml instead of using an env.

Thank you for you help in advance
