### DISCUSSION TITLE
Dependabot preview workflows failing

### DISCUSSION THREAD

**Discussion by tembbo** [community/community#150986] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a preview workflow (names `preview.yml`) in my github repo which will automatically deploy a preview to cloudflare pages on every pr using https://github.com/AdrianGonz97/refined-cf-pages-action. 

This is how my preview workflow looks like:

```yml
name: Preview

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build
              env:
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

            - name: Deploy
              uses: AdrianGonz97/refined-cf-pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  projectName: portfolio
                  directory: .svelte-kit/cloudflare
                  deploymentName: Preview
```

This workflow works and manages to deploy correctly without errors, except for dependabot prs. On those prs i get this error:

```sh
Error: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment
/home/runner/work/_actions/AdrianGonz97/refined-cf-pages-action/v1/dist/index.js:24394
        runId: import_github5.context.payload.workflow_run.id ?? import_github5.context.runId
                                                           ^
TypeError: Cannot read properties of undefined (reading 'id')
    at /home/runner/work/_actions/AdrianGonz97/refined-cf-pages-action/v1/dist/index.js:24394:60
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v20.[18](https://github.com/realguse/portfolio/actions/runs/13214867737/job/36892912046?pr=69#step:6:19).0
```

A solution would be to trigger it on the `pull_request_target` event, but that would take "origin point" from the `main` branch, thus not being a "preview" workflow.

Thanks in advance!

**Comment by tembbo** [comment, marked as answer]
**Solution**:

Use `pull_request_target` and set `ref`/`repository` when checking out.

Final code:

```yaml
name: Preview

on:
    pull_request_target:
        types: [opened, synchronize]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}

            - name: Install Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build
              env:
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

            - name: Deploy
              uses: AdrianGonz97/refined-cf-pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  projectName: portfolio
                  directory: .svelte-kit/cloudflare
                  deploymentName: Preview
```
