### DISCUSSION TITLE
[Bug] `workflow_dispatch: []` causes HTTP 500 + UI hang, not user-facing error

### DISCUSSION THREAD

**Discussion by cceckman** [community/community#15097] [Actions] [answered]
Demonstrated in https://github.com/cceckman/actions-syntax.

```
name: Run tests
on:
  workflow_dispatch: []
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - run: 'echo Done'
```

This seems to parse fine within the UI; the [Actions page](https://github.com/cceckman/actions-syntax/actions/workflows/buggy.yml) has the relevant blue bar for triggering `workflow_dispatch`.

Clicking on "Run workflow" just gives a spinner:

![Screenshot 2022-04-17 13 45 54](https://user-images.githubusercontent.com/861696/163731481-4aaa828e-c1db-4851-aed5-8b7221343da1.png)

The network trace for developer tools shows an HTTP 500 response for the URL `https://github.com/cceckman/actions-syntax/actions/manual?workflow=.github%2Fworkflows%2Fbuggy.yml` after that click.

---

IIUC, the underlying code has an error - `workflow_dispatch` is supposed to be an object (`{}`), not a list (`[]`).

But: I'd expect that to come out as a user-visible error, "The syntax for this dispatch is incorrect", rather than a hang and a 500.
