### DISCUSSION TITLE
Github automatically canceled the job after 6 hours

### DISCUSSION THREAD

**Discussion by phamvuong** [community/community#150900] [Actions]
### Select Topic Area

Question

### Body

Hi team, according to the document here https://leap-expert.atlassian.net/browse/LED-59445?focusedCommentId=221242, then the github action job will be canceled after 6 hours by default. I have updated the value to 2 days (2880) like below
```
jobs:
  build_model:
    runs-on: Tesla-T4
    timeout-minutes: 2880
    steps:
    # some steps
```

However, my job was still canceled after 6h. Is it the maximum value we can set ?
<img width="999" alt="image" src="https://github.com/user-attachments/assets/5f24c477-751e-4856-9342-8d620a79c5f4" />
