### DISCUSSION TITLE
[Markdown] Allow tables to be sortable

### DISCUSSION THREAD

**Discussion by NullVoxPopuli** [community/community#151068] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

For example, I have a table here: https://github.com/NullVoxPopuli/disk-perf-git-and-pnpm in the README, that I would like to be sorted by "install time" (in seconds).

Table copied here in case the README ever changes:

| CPU | RAM (GB) | Clean (s) | Install (s) | Date | FileSystem & Disk | OS |
| --- | -------- | --------- | ----------- | ---- | ----- | --- |
| AMD Ryzen 5 7640U 12 Core | 92 | 6.8 | 5.9 | 2025-02-07 | Ext4 : WD Black SN850 500GB | Ubuntu 24.04.1 |
| AMD Ryzen 9 7900X 12/24 Core | 64 | 6.0 | 4.3 | 2025-02-07 | Ext4 : Samsung SSD 980 Pro 2TB | Ubuntu 24.04.1 |
| Apple M1 Max | 64 | 21.299 | 219 | 2025-02-08 | APFS (Encrypted) : APPLE SSD AP1024R 1TB | |
| Apple M4 | 16 | 29.6 | 31.4 | 2025-02-08 | APFS (Encrypted) : APPLE SSD AP1024Z 1TB | |
| AMD Ryzen 7 7800X3D 8 Core | 32 | 17.1 | 16.1 | 2025-02-09 | Ext4 : Corsair MP600 PRO LPX | |
| AMD Ryzen 7 7800X3D 8 Core | 32 | 65.5 | 42.3 | 2025-02-09 | NTFS : Corsair MP600 PRO LPX | |

Right now, we're just appending to the end of the table, but sorting by any of the columns would be very useful.

Filtering could be neat, too -- but I don't know how folks would specify desired features / meta of a table in markdown.

**Comment by HouseMiv** [comment]
To add sorting to a table in a GitHub README, it's important to understand that Markdown itself does not support this feature, as it's a static markup language. However, there are a few solutions you can consider:

1. You can set up automatic sorting of the table using GitHub Actions. For example, you could create a script that sorts the table each time the README is updated. This would keep the table in order automatically.

2. If your project uses GitHub Pages or another web page, you can add JavaScript to enable dynamic sorting of the table. This will allow sorting by clicking on column headers. You can find examples of such tables on the internet (for instance, using libraries like `DataTables.js`).

3. If the table doesn’t change often, you can simply update it manually by sorting the rows in the desired order, but this won’t provide dynamic sorting during interaction with the file.

In summary, Markdown on GitHub doesn’t natively support table sorting, but you can use external tools or implement sorting on web pages for your project.

**Reply by HouseMiv** [reply]
Here is a practical solution for sorting tables in a GitHub repository using GitHub Actions, which can automatically sort your table each time the README file is updated.

1. First, you'll need a Python script that will sort the table in your README file. Here's an example of a script (`sort_table.py`) that sorts the table by a specified column (e.g., "Installation Time" in seconds):

   ```python
   import re

   def sort_table(file_path, column_index):
       # Read the README file
       with open(file_path, 'r') as file:
           lines = file.readlines()

       # Extract the table rows
       table_rows = []
       table_started = False
       for line in lines:
           if '|---' in line:  # This indicates the start of the table
               table_started = True
           if table_started:
               table_rows.append(line)

       # Sort the rows by the column_index (ignoring the header row)
       sorted_rows = sorted(table_rows[1:], key=lambda x: float(x.split('|')[column_index].strip()), reverse=False)

       # Recreate the sorted table
       new_table = lines[:lines.index(table_rows[0])] + [table_rows[0]] + sorted_rows

       # Write back the updated README file
       with open(file_path, 'w') as file:
           file.writelines(new_table)
       print("Table sorted successfully!")

# Path to your README file
   file_path = "README.md"
   # Column index to sort by (adjust as needed, 0 is the first column)
   column_index = 3  # For "Installation Time" (if it's the 4th column)
   sort_table(file_path, column_index)
   ```

2.  You'll need to create a GitHub Actions workflow to automatically run the script whenever the README is updated. Here’s how you can do that:

   - In your repository, create a `.github/workflows` directory if it doesn't already exist.
   - Inside `.github/workflows`, create a file called `sort-table.yml`.

   Example `sort-table.yml`:

   ```yaml
   name: Sort README Table

   on:
     push:
       paths:
         - README.md

   jobs:
     sort-table:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: Set up Python
           uses: actions/setup-python@v2
           with:
             python-version: '3.x'

         - name: Install dependencies
           run: |
             pip install -r requirements.txt

         - name: Run table sorting script
           run: python sort_table.py

         - name: Commit and push changes
           uses: EndBug/add-and-commit@v7
           with:
             author_name: 'GitHub Actions'
             author_email: 'actions@github.com'
             message: 'Sort README table automatically'
   ```

3.  If your script needs any Python dependencies, create a `requirements.txt` file in the root of your repository. For this simple script, no additional dependencies are needed, but if you use any libraries, list them here.

4. After setting everything up, push your changes to GitHub. The GitHub Actions workflow will trigger whenever the `README.md` file is updated, run the sorting script, and commit the sorted table back to your repository.

### Result:
Every time you update the README, the GitHub Action will automatically sort the table based on the specified column (e.g., "Installation Time"), keeping your table up-to-date and organized without manual intervention.

Let me know if you need any further adjustments or details!
