### DISCUSSION TITLE
Why am I unable to trigger my GitHub action?

### DISCUSSION THREAD

**Discussion by yglsaltfish** [community/community#151131] [Actions] [answered]
### Select Topic Area

Question

### Body

I have transferred an account to an organization. However, subsequent to the transfer, I am unable to trigger my GitHub action. I have configured it to permit all actions and have closed and reopened pull requests, but still cannot trigger my action. The pull request changed files not in the .github or document directory. The source code is presented as follows. Could anyone assist me? Thank you.

```
name: CI/CD Workflow

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'document/**'
    branches:
      - '*'
      - '**'
  push:
    branches:
      - '*'
      - '**'
  release:
    types: [published]
```
