### DISCUSSION TITLE
How to migrate from Buildkite to Github actioins

### DISCUSSION THREAD

**Discussion by StrikeW** [community/community#151160] [Actions]
### Select Topic Area

Question

### Body

Hi community, I am planning to migrate the CI pipeline of our project from [Buildkite](https://buildkite.com/) to Github Actions.
I found this [Migrating to GitHub Actions](https://docs.github.com/en/actions/migrating-to-github-actions) page, but it doesn't have guideline for Buildkite.

The blocking step to me is that we use the `docker-compose` plugin of Buildkite to set up our test environment and then execute our (end-to-end) tests.
```yaml
  - label: "end-to-end test"
    command: "ci/scripts/e2e-test.sh -p ci-dev "
    if: |
      !(build.pull_request.labels includes "ci/pr/run-selected") && build.env("CI_STEPS") == null
      || build.pull_request.labels includes "ci/run-e2e-test"
    depends_on:
      - "build"
      - "build-other"
      - "docslt"
    plugins:
      - docker-compose#v5.1.0:
          run: ci-build-env
          config: ci/docker-compose.yml
          mount-buildkite-agent: true
      - ./ci/plugins/upload-failure-logs
    timeout_in_minutes: 30
    retry: *auto-retry
```

Any suggestion to migrate this setup to Github Actions? Thanks.

**Comment by Raymond-Ly** [comment]
GitHub Actions doesn't have a native docker-compose plugin, but you can manually set up and use docker-compose in your workflow.

An example:

```
name: End-to-End Tests

on:
  pull_request:
    types: [labeled, opened, synchronise, reopened]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: contains(github.event.pull_request.labels.*.name, 'ci/run-e2e-test') || github.event_name == 'push'
    needs: [build, build-other, docslt]  # Dependency equivalent to Buildkite `depends_on`
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker-compose -f ci/docker-compose.yml up -d
        timeout-minutes: 5

      - name: Run End-to-End Tests
        run: ci/scripts/e2e-test.sh -p ci-dev
        env:
          CI: true

      - name: Upload Failure Logs on Error
        if: failure()
        run: |
          mkdir -p logs
          docker-compose logs > logs/docker-compose.log
        continue-on-error: true

      - name: Upload Logs Artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: failure-logs
          path: logs/
      
      - name: Tear Down Docker Services
        if: always()
        run: docker-compose -f ci/docker-compose.yml down
```
