### DISCUSSION TITLE
setup-go: Conflict: cache entry with the same key, version, and scope already exists

### DISCUSSION THREAD

**Discussion by theory** [community/community#151213] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a workflow that builds a Go app for a wide variety of OSes and architectures in parallel. Each includes this step:

```yaml
- name: Setup Go
  uses: actions/setup-go@v5
  with: { go-version-file: go.mod, check-latest: true }
```

Works fine for a couple of platforms, but when there are bunch many start to fail to initialize the cache, alerting with

```
Failed to save: Failed to CreateCacheEntry: Received non-retryable error: Failed request: (409) Conflict: cache entry with the same key, version, and scope already exists

Cache not found for keys: setup-go-Linux-x64-ubuntu24-go-1.23.6-25a10098937c3bd68ba35511ebc014bfbfdf5475ab6c73c8ac99e81b422e9aad
```

I'm not sure why there is a conflict since almost all the builds are on `ubuntu-latest`. Is there some other value I need to include to make a unique hash?
