### DISCUSSION TITLE
Feature Request: Organisation scoped concurrency-groups

### DISCUSSION THREAD

**Discussion by HenrikDK** [community/community#151270] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi 

Based on experience managing our git-ops setup and the current limitations in github actions runner controller:

https://github.com/actions/actions-runner-controller/discussions/3165

We have tried using concurrency-groups to handle queing against our shared github repositories (these hold cluster-state) but found limitations, specifically that concurrency-groups are only evaluated on a pr repository basis, as discussed here:

https://github.com/orgs/community/discussions/78332

It would be very helpfull if it was possible to make global organisation wide concurrency-groups, so workflow runs from multiple repositories could be queued and executed sequentially based on a key. The configuration would probably look something like this:

```yaml
    concurrency:
      group: deploy-${{ matrix.deployments.repo }}
      scope: organisation # optional, defaults to repository
```
