### DISCUSSION TITLE
Issue Templates Config with only redirect urls

### DISCUSSION THREAD

**Discussion by kmcgrady** [community/community#151204] [Projects and Issues]
### Select Topic Area

Bug

### Feature Area

Issues

### Body

I would like to effectively disable issues on my repo and redirect users to a different repo to file the bug. To do this, I wrote the following issue template config

```yaml
blank_issues_enabled: false
contact_links:
  - name: 🐛 Bug report
    url: https://github.com/my-org/other-repo/issues/new?template=bug_report.yml
    about: Submit a bug report to help us improve this repo (through our main other-repo repository)
  - name: ✨ Feature request
    url: https://github.com/my-org/other-repo/issues/new?template=feature_request.yml
    about: Suggest a feature or enhancement for this repo (through our main other-repo repository)
```

And I did not include any issue templates.

I thought this worked the first time, but now it seems like it is not working. Now, when someone clicks new issue, it creates a blank issue. This seems like a bug, but perhaps I am hallucinating. Is it a requirement that an issue template _must_ exist?

Thank you!

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
