### DISCUSSION TITLE
Caches not persisting between branches?

### DISCUSSION THREAD

**Discussion by dani-hatch** [community/community#151220] [Actions]
### Select Topic Area

Question

### Body

I'm caching my dependencies for my Python unit tests using this action:

```yaml
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-dependencies-staging-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-staging
          ${{ runner.os }}-dependencies-
        enableCrossOsArchive: true
```

And I can see caches being created by my PRs off `staging` (default branch) in the Actions tab. I can see that they have the EXACT SAME key as what's being looked-for in new PRs but the cache is still missed. This CI runs:

```yaml
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
```

Is the issue that the caches are being created on feature branches _off of_ `staging` and are thus not accessible to other branches? How can I ensure that other branches will be able to access the caches I'm creating when running my CI? Once I get the `pip` cache taken care of, I need this to also work for `node_modules` as well as a db dump and cached Docker layers. These are really eating up my CI minutes!
