### DISCUSSION TITLE
Passing secrets into Autograder

### DISCUSSION THREAD

**Discussion by prof-lowe** [community/community#151323] [GitHub Education]
### Hi everyone,

Hi everyone,

I've been pretty successful with the Autograder feature for assignments in the past, but I'm running into an issue with a specific assignment that requires an API key passed into the autograder as a GitHub secret.

I'm storing the API key as GitHub Secret, and I'm trying to use it in the Autograder  actions (I tired I/O, Python, and Command actions) but the autograder doesn't seem to be picking up the key. 

Here is an example of what I have in the autograder:

```yaml
    - name: Test directions-api1
      env:
        API_KEY: ${{ secrets.API_KEY }}
      id: test-directions-api1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test directions-api1
        command: python3 directions-api1.py
        input: ''
        expected-output: "'point': {'lat': 43\\.6534817, 'lng': -79\\.3839347}"
        comparison-method: regex
        timeout: 1
        max-score: 1
```

In the directions-api1.py the API_KEY value always ends up being None (using `os.environ.get`). If I create a manual job in the classroom.yml file that just checks for the API key and confirms the value, it's successful, so the repository seems to have appropriate permissions and can correctly read the secret in GitHub Actions.

It seems like the autograder actions ignore (or perhaps, overwrite) the environment variables, and the key is blank when the student's files are run.

Is there something specific I need to do to allow the autograder actions to see the secret?

Thanks, 
Josh

**Comment by sgbaird** [comment]
Likewise, finding this very necessary. I had something working in the past, but I'm not sure if that still applies for the current version of GitHub Classroom autograders. I will try to dig up and check.

EDIT:

Here is an example that I used to use and verified that it still works with current version of GitHub Classroom / autograders:

```yaml
name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create file for setting env vars
      # https://github.com/education/autograding/issues/69#issuecomment-1497674655
      # https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
      run: |
        echo "#!/bin/sh" > setenv.sh
        echo "export COURSE_ID=\"${{ secrets.COURSE_ID }}\"" >> setenv.sh
        echo "export DATABASE_NAME=\"${{ secrets.DATABASE_NAME }}\"" >> setenv.sh
        echo "export COLLECTION_NAME=\"${{ secrets.COLLECTION_NAME }}\"" >> setenv.sh
        echo "export LAMBDA_FUNCTION_URL=\"${{ secrets.LAMBDA_FUNCTION_URL }}\"" >> setenv.sh
        echo "export ATLAS_URI=\"${{ secrets.ATLAS_URI }}\"" >> setenv.sh
        chmod +x setenv.sh

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure your repo includes this file

    - name: Run Pytest
      id: pytest
      uses: classroom-resources/autograding-command-grader@v1 # https://github.com/classroom-resources/autograding-command-grader
      with:
        test-name: "Python Test Suite"
        setup-command: "pip install -r requirements.txt"
        command: ". ./setenv.sh && pytest --tb=short"
        timeout: 10
        max-score: 10

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      # For more information on this runner, see the documentation at https://github.com/classroom-resources/autograding-grading-reporter
      # To output the results of the tests, you can use the
      # autograding-grading-reporter action like this:
      env:
        PYTEST_RESULTS: "${{ steps.pytest.outputs.result }}"
      with:
          runners: "pytest"
```


In particular:
```yaml
    - name: Create file for setting env vars
      # https://github.com/education/autograding/issues/69#issuecomment-1497674655
      # https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
      run: |
        echo "#!/bin/sh" > setenv.sh
        echo "export COURSE_ID=\"${{ secrets.COURSE_ID }}\"" >> setenv.sh
        echo "export DATABASE_NAME=\"${{ secrets.DATABASE_NAME }}\"" >> setenv.sh
        echo "export COLLECTION_NAME=\"${{ secrets.COLLECTION_NAME }}\"" >> setenv.sh
        echo "export LAMBDA_FUNCTION_URL=\"${{ secrets.LAMBDA_FUNCTION_URL }}\"" >> setenv.sh
        echo "export ATLAS_URI=\"${{ secrets.ATLAS_URI }}\"" >> setenv.sh
        chmod +x setenv.sh
```
and
```yaml
    - name: Run Pytest
      id: pytest
      uses: classroom-resources/autograding-command-grader@v1 # https://github.com/classroom-resources/autograding-command-grader
      with:
        test-name: "Python Test Suite"
        setup-command: "pip install -r requirements.txt"
        command: ". ./setenv.sh && pytest --tb=short"
        timeout: 10
        max-score: 10
```

Took a lot of debugging a while back to find this solution 🥲. Hopefully can be of use to you.
