### DISCUSSION TITLE
Auto commit action does not trigger workflows with push event

### DISCUSSION THREAD

**Discussion by jesmrec** [community/community#151365] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi! I ran into a problem, hoping you can put light in front of my eyes. I have a workflow that includes the following step:

```
- name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "changelog updated"
          file_pattern: CHANGELOG.md
```

that step generates a new commit that is straight pushed to the stream in the current branch. On the other hand, there are other workflows with `on: push` events to be triggered, but, they are not triggered in that case. In the moment the auto commit is created, workflows are out of the GH checks section in the PR.

I did a lot of tries, based in the available information i found:

- Using a PAT to assure the auto commit does not use an internal token
- Using workflow_dispatch events (and other `on:` events)
- Generate the commit explicitly in the step (with no auto commit)

... and other random and crazy things that came to my head (in the edge of desperation :D). Probably, i am missing something that i hope you can help me to find out. Thanks in advance

**Comment by diepei** [comment]
Hi there!

Add persist-credentials: false to your checkout step before doing the auto-commit:
```
- name: Checkout
  uses: actions/checkout@v4
  with:
    persist-credentials: false

- name: Commit files
  uses: stefanzweifel/git-auto-commit-action@v5
  with:
    commit_message: "changelog updated"
    file_pattern: CHANGELOG.md
```
This will work because when you use actions/checkout, it automatically configures git credentials using the default GITHUB_TOKEN, which has a built-in security feature that prevents automated commits from triggering other workflows (to prevent infinite loops).

By setting persist-credentials: false, you're telling the checkout action "don't set up any git credentials" - this prevents the default GITHUB_TOKEN from being automatically configured in the git config, allows the subsequent auto-commit action to use its own authentication method, and removes the inherent workflow-blocking behavior that comes with the default token.

**Reply by jesmrec** [reply]
Thanks @diepei for your answer! unfortunately, it didn't work. Adding `persist-credentials` to `false` led us to an error in workflow execution `fatal: could not read Username for 'https://github.com/': No such device or address"`. The problem is fixable by using `GITHUB_TOKEN` explicitly, but, then we go to the scratch point. The commit does not trigger other workflows.

**Reply by joragua** [reply, marked as answer]
Finally, we have found the solution for this problem 😁. It was necessary add `persist-credentials: false` to our checkout step as you said @diepei 🍻  but we also had to replace the auto-commit step because it was not working with `stefanzwiefel/git-auto-commit-action@v5`. These are the steps that we have in our `.yaml` file after all changes.

```
- name: Checkout
    uses: actions/checkout@v4
    with:
      persist-credentials: false

- name: Run Calens
    uses: actionhippie/calens@v1
    with:
      target: CHANGELOG.md

- name: Commit files
    uses: GuillaumeFalourd/git-commit-push@v1.3
    with:
      email: ***
      name: ***
      commit_message: "docs: calens changelog updated"
      access_token: ${{ secrets.GH_PAT }}
```

Moreover, it was necessary to add a PAT (Personal Access Token) to the repository and `acces_token` parameter to the last step.

_NOTE: Values of email and name are from account that is going to do the push._
