### DISCUSSION TITLE
Request for select input

### DISCUSSION THREAD

**Discussion by Angelk90** [community/community#151450] [Actions]
### Select Topic Area

Product Feedback

### Body

An input field similar to the one seen in the video to select multiple options.

```yml
on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Select os'
        required: true
        type: select #option
        default: 'macos,linux'
        options:
          - macos
          - windows
          - linux
```

https://github.com/user-attachments/assets/46718b5e-c539-4ae0-8a0a-3ed80cd2fbdc
