### DISCUSSION TITLE
Unable to push tag with GitHub Actions GITHUB_TOKEN: `refusing to allow a GitHub App to create or update workflow .github/workflows/foo.yaml without workflows permission`

### DISCUSSION THREAD

**Discussion by carlcsaposs-canonical** [community/community#151442] [Actions]
### Select Topic Area

Bug

### Body

It is not possible to push a git tag from GitHub Actions using the `GITHUB_TOKEN` if the tag points to a commit where the contents of `.github/workflows/` are not identical to the contents of `.github/workflows/` on the latest commit of any branch

When pushing the tag, the workflow will fail with
```
To https://github.com/carlcsaposs-canonical/bug-report-github-actions-tags
 ! [remote rejected] latest/candidate -> latest/candidate (refusing to allow a GitHub App to create or update workflow `.github/workflows/foo.yaml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/carlcsaposs-canonical/bug-report-github-actions-tags'
```

If the contents of `.github/workflows/` is identical to the contents of `.github/workflows/` on the latest commit of any branch, the tag will be pushed successfully

I understand why this protection is in place for branch pushes (you don't want a GitHub App creating a workflow that gives itself access to secrets). However, it appears this protection is being incorrectly applied to tag pushes

To clarify, the tag that is being pushed points to a commit that is already on the `main` branch—it is just not the latest commit on the `main` branch. Pushing the tag does not create or update a workflow

It appears that several people have run into this issue before, but may have misunderstood the root cause. For example:
https://github.com/actions/checkout/issues/1421
https://github.com/orgs/community/discussions/109715
https://github.com/orgs/community/discussions/51520
https://github.com/orgs/community/discussions/146011
https://github.com/orgs/community/discussions/35410
https://github.com/orgs/community/discussions/141159

## Steps to reproduce

1. Create a GitHub repository
2. Add `.github/workflows/foo.yaml` to `main` with this content:
```yaml
on:
  workflow_dispatch:

jobs:
  foo:
    name: foo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git tag latest/candidate HEAD^ --force
          git push origin latest/candidate --force
    permissions:
      contents: write  # Needed to update git tags
```
3. In a new commit, edit the workflow file (e.g. add a comment) on the `main` branch
4. Go to Actions & trigger the foo.yaml workflow on `main`
5. Check workflow run logs
e.g.
```
To https://github.com/carlcsaposs-canonical/bug-report-github-actions-tags
 ! [remote rejected] latest/candidate -> latest/candidate (refusing to allow a GitHub App to create or update workflow `.github/workflows/foo.yaml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/carlcsaposs-canonical/bug-report-github-actions-tags'
```

Here is a repository created with those steps to reproduce: https://github.com/carlcsaposs-canonical/bug-report-github-actions-tags
