### DISCUSSION TITLE
Authentication for organization-internal Maven packages

### DISCUSSION THREAD

**Discussion by davidschreiber** [community/community#151428] [Packages]
### Select Topic Area

Question

### Body

Hi!

I'm trying to discover if GitHub's Maven package registry supports organization-internal authentication for downloading and installing Maven packages across different repositories _**without**_ a manually generated PAT.

What I want to achieve is this:

- Repository A publishes a Maven dependency.
- Repository B uses auto-generated Job-scoped tokens to access the Maven package:

```yaml
job:
  # ... 
  test:
    permissions:
      packages: read
  steps:
    # ...
    - env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew assemble
```

However, so far, I haven't been able to get this setup to run. It seems as if Repository B requires a token with additional permissions, i.e. `package:read` access to Repository A, which would be given by a manually generated user-PAT with `packages:read` scope, but not by the auto-generated Job-scoped token.

Did I infer this limitation correct, or am I doing something wrong, and access to the Maven package should be possible even without a manual PAT?
