### DISCUSSION TITLE
Underscores in env in classroom.yml config result in incorrect error message "the runners input must be a comma-separated list of strings"

### DISCUSSION THREAD

**Discussion by misingnoglic** [community/community#151607] [GitHub Education]
### Hi everyone,

Hello. Just wanted to share this bizarre error I got when making the classroom.yml config for my github classroom assignment. When I had an env like this:

```
        env:
          COUNT_RESULTS: "${{steps.count.outputs.result}}"
          MOST_FREQUENT_ITEM_RESULTS: "${{steps.most-frequent-item.outputs.result}}"
          MOST_FREQUENT_COUNT_RESULTS: "${{steps.most-frequent-count.outputs.result}}"
          FIND_REPEAT_NUMBER_RESULTS: "${{steps.find-repeat-number.outputs.result}}"
          UNIQUE_ARRAY_RESULTS: "${{steps.unique-array.outputs.result}}"
          ONLY_UNIQUE_ITEMS_RESULTS: "${{steps.only-unique-items.outputs.result}}"
          ARE_ALL_ITEMS_UNIQUE_RESULTS: "${{steps.are-all-items-unique.outputs.result}}"
          LIST_CYCLE_RESULTS: "${{steps.list-cycle.outputs.result}}"
          THREE_SUM_RESULTS: "${{steps.three-sum.outputs.result}}"
          IS_ANAGRAM_RESULTS: "${{steps.is-anagram.outputs.result}}"
          EXCLUDE_PRODUCT_RESULTS: "${{steps.exclude-product.outputs.result}}"
        with:
          runners: count,most-frequent-item,most-frequent-count,find-repeat-number,unique-array,only-unique-items,are-all-items-unique,list-cycle,three-sum,is-anagram,exclude-product
```

I would get the error "the runners input must be a comma-separated list of strings" - which had me chasing for errors in the runners section which was correct. 

The actual issue was that the results names in the env can't use underscores, and must use something like dashes, e.g. MOST_FREQUENT_ITEM_RESULTS -> MOST-FREQUENT-ITEM_RESULTS

This was incredibly annoying to debug and hopefully someone who works on this product can make the error more descriptive, but for now wanted to post this in case someone else came into this issue. Cheers :)
