### DISCUSSION TITLE
Kotlin CodeQL manual build never finishes

### DISCUSSION THREAD

**Discussion by ArneOttenVW** [community/community#151626] [Actions]
### Select Topic Area

Question

### Body

I am trying to get CodeQL to work with my Kotlin codebase. I switched from default to advanced setup to be able to provide a manual build command but this is where I run into a problem.

In my advanced workflow file, I run codeql-action/init and build my code after that. The building never finishes however and even timed out after the default 6h. At first, because I did not know better, I built the code before running codeql init. It built in less than a minute. Only if I build the code after running codeql init, it is just stuck in the compilation process until timeout.

I found someone with a similar issue but he just states his build is very slow and no solution was found to why: https://github.com/github/codeql-action/issues/2378

I also ran gradle with --no-daemon but without success. Is there something I can do or is this a bug with CodeQL?

Excerpt from logs
```text
[...]
Run ./my/project/gradlew -p ./my/project build -x test -x lintKotlin
Downloading https://services.gradle.org/distributions/gradle-8.8-bin.zip
.............10%.............20%.............30%.............40%.............50%.............60%..............70%.............80%.............90%.............100%

Welcome to Gradle 8.8!

Here are the highlights of this release:
 - Running Gradle on Java 22
 - Configurable Gradle daemon JVM
 - Improved IDE performance for large projects

For more details see https://docs.gradle.org/8.8/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :processResources
> Task :check
> Task :compileKotlin

*This is where 6 hours go by*

Error: The operation was canceled.
```

My codeql workflow:
```yaml
name: "CodeQL Advanced"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    - cron: '15 13 * * 1'

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: kotlin
          build-mode: manual
        - language: typescript
          build-mode: none
        - language: python
          build-mode: none

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - if: matrix.language == 'kotlin'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - if: matrix.language == 'kotlin'
      shell: bash
      run: ./my/project/gradlew -p ./my/project build -x test -x lintKotlin

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
```
