### DISCUSSION TITLE
Does GitHub Workflows have the concept of incremental uploads?

### DISCUSSION THREAD

**Discussion by Rod-at-DOH** [community/community#151756] [Actions] [answered]
### Select Topic Area

Question

### Body

We have a PHP website that is used to inform the public of various things. It is updated frequently each day. Currently, the process is to add PDFs or images daily, make any necessary changes to a .php file and upload just those changes from the working directory to the live website via FTP. At this point Git and GitHub Actions are not involved at all.

But we would like to incorporate Git and GitHub Actions into this process. However, I don't want to totally refresh the whole website if all that is done is adding one PDF. Does GitHub Actions/Workflows support the concept of incremental updates? And note, this must be done with a GitHub Self-Hosted Runner running on a Windows 2022 Server.

**Comment by ghost** [comment, marked as answer]
Hello,

Yes, GitHub Actions can support **incremental uploads** in your deployment process, and it can be done efficiently even with a **GitHub Self-Hosted Runner on Windows Server 2022**. Since your current workflow involves uploading only modified files via FTP, you can replicate that in GitHub Actions.

### **How to Implement Incremental Uploads in GitHub Actions**
Instead of uploading the entire website on every deployment, you can use **git diff** to determine which files have changed and upload only those.

#### **Steps to Achieve Incremental Uploads:**
1. **Track changes using `git diff`**  
   Identify files that have changed between the current and last deployed commit.

2. **Use an FTP deployment action**  
   Use a GitHub Action like https://github.com/SamKirkland/FTP-Deploy-Action or https://github.com/mgrenier/ftp-deploy to upload only modified files.

3. **Run on a Self-Hosted Runner**  
   Your GitHub Actions workflow will execute on your Windows Server 2022 self-hosted runner.

---

### **Example GitHub Actions Workflow for Incremental Uploads**
```yaml
name: Incremental FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your Windows 2022 server
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensures we have the last deployed commit

      - name: Get changed files
        id: changed-files
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "CHANGED_FILES=$(cat changed_files.txt)" >> $GITHUB_ENV
        shell: bash

      - name: Upload changed files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
          only-changed: true  # Uploads only changed files
```
