### DISCUSSION TITLE
Cache Key Doesn't Change After Modifying Files

### DISCUSSION THREAD

**Discussion by sijunnoh** [community/community#151801] [Actions]
### Select Topic Area

Question

### Body

I'm facing an issue where the cache key in my GitHub Actions workflow doesn't change even after modifying or deleting `.tsx` files in my project. The cache key always seems to be the same.

https://github.com/sijunnoh/github-action-test

Here is the relevant part of my workflow:

`${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}`

I have read the following documentation:

[HashFiles expression documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#hashfiles)
[GitHub Actions workflow syntax](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)

Despite modifying .tsx files, the cache key always remains the same. Could someone point out what I might be missing here?

```
name: Test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.18.2]
    steps:
      - name: ✅ Checkout branch
        uses: actions/checkout@v3

      - name: 📀 Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore and save cache
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .next/cache
            node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-nextjs-

      - name: 📚 Install dependencies
        run: yarn install

      - name: ✈️ Build Test
        run: |
          yarn build
```
