### DISCUSSION TITLE
New Issues Experience - "No templates available for the current repository"

### DISCUSSION THREAD

**Discussion by maartenba** [community/community#151806] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

When creating a new issue in our repos, we do not allow blank issues. For some repos, we want to centralize issues in another repo, so we only add contact links in the configuration:

```
blank_issues_enabled: false
contact_links:
  - name: Support Forum
    url: https://github.com/DuendeSoftware/community
    about: The place for questions, support and feature requests
  - name: Create an Issue
    url: https://github.com/DuendeSoftware/foss/issues/new
    about: Create a new issue for a bug
```

This works great with the "old" issues experience. When creating a new issue in https://github.com/DuendeSoftware/foss/issues, you would see this presented nicely:

![image](https://github.com/user-attachments/assets/d25a0546-f105-448d-afc0-659f1dd60ba3)

When the "New Issues Experience" is enabled, this breaks down:

![image](https://github.com/user-attachments/assets/12344759-5fe1-49c5-82c0-79505cafa53e)

What would be a solution to this, other than allowing blank issues after all and manualy moving things over to the correct repository?
