### DISCUSSION TITLE
[Show and tell] Go Git Commit Action - A Comprehensive Git Operations Automation Tool

### DISCUSSION THREAD

**Discussion by somaz94** [community/community#151983] [Actions]
### Select Topic Area

Product Feedback

### Body

👋 Hello GitHub Community!

I'm excited to share a GitHub Action I've developed called "Go Git Commit Action". It's designed to simplify and automate git operations in GitHub Actions workflows, with a focus on reliability and flexibility.

<br/>

## 🎯 What Problem Does It Solve?

As a DevOps engineer, I noticed several common challenges in GitHub Actions workflows:
- Need for automated git operations (commit, push, tag)
- Complex PR creation and management
- Lack of flexible tag management
- Need for conditional git operations

<br/>

## 🛠 Key Features

- **Written in Go** for better performance and reliability
- **Comprehensive Git Operations:**
  - Automated commits and pushes
  - Tag management (create, delete, reference)
  - PR creation with advanced options
  - Branch management
- **Advanced Options:**
  - Auto-branch creation
  - Skip empty changes
  - Custom PR labels and descriptions
  - Source branch cleanup
  - Conditional execution

<br/>

## 💡 Example Usage

Basic commit example:
```yaml
- uses: somaz94/go-git-commit-action@v1
  with:
    user_email: actions@github.com
    user_name: GitHub Actions
    commit_message: Auto commit by GitHub Actions
```

Creating a PR with auto-branch:
```yaml
- uses: somaz94/go-git-commit-action@v1
  with:
    user_email: actions@github.com
    user_name: GitHub Actions
    create_pr: true
    auto_branch: true
    pr_branch: feature/my-branch
    pr_base: main
    github_token: ${{ secrets.GITHUB_TOKEN }}
```

<br/>

## 🌟 Why Choose This Action?

1. **Reliability**: Written in Go for robust performance
2. **Flexibility**: Supports various git operations in one action
3. **User-Friendly**: Clear documentation and examples
4. **Maintained**: Regular updates and improvements
5. **Production-Ready**: Being used in real-world workflows

<br/>

## 🔗 Links
- [GitHub Marketplace](https://github.com/marketplace/actions/go-git-commit-action)
- [Source Code](https://github.com/somaz94/go-git-commit-action)
- [Documentation](https://github.com/somaz94/go-git-commit-action/blob/main/README.md)

<br/>

## 🤝 Feedback Welcome!

I'd love to hear your thoughts and suggestions! Feel free to:
- Try it out and share your experience
- Open issues for bugs or feature requests
- Contribute via pull requests
- Share how you're using it in your workflows

Looking forward to your feedback and suggestions for improvement! 🚀
