### DISCUSSION TITLE
In github actions template, ${{github.action_ref}} changes depending on where it is used

### DISCUSSION THREAD

**Discussion by tjamet** [community/community#151905] [Actions]
### Select Topic Area

Bug

### Body

We recently faced some challenges using github composite actions.
In particular, when using composite actions within composite actions.

We have seen that the expression ${{github.action_ref}} will render differently whether it is rendered in `inputs.*.default` or in `steps.*.env.*`.

Given the composite actions:
`action-1@ref1`:

```yaml
steps:
- uses: action-2@ref2
```

and `action-2@ref2`:

```yaml
name: 'Test actions composite'
inputs:
  action-ref:
    default: ${{ github.action_ref }}


runs:
  using: composite
  steps:
  - name: dump input
    run: echo '${{ inputs.action-ref }}'
    shell: bash
  - name: dump env
    env:
      JSON_ENCODED: ${{ github.action_ref }}
    run: echo "${JSON_ENCODED}"
    shell: bash
```

When running `action-1@ref1`, the value dumped by `dump input` will be `ref2` and the value dumped by `dump env` will be `ref1`.
When running `action-2@ref2` directly, both steps will dump `ref2`

I would expect the value to be idempotent regardless the action is called directly from a workflow or from a composite action.

[Here](https://github.com/tjamet/composite-action-test-2/actions/runs/13434113509/job/37532392021) is a real-life execution where the problem appears:

- [action-2@ref2 from composite in inputs](https://github.com/tjamet/composite-action-test-2/actions/runs/13434113509/job/37532392021#step:2:695): v1 ✅ 
- [action-2@ref2 from composite in step env](https://github.com/tjamet/composite-action-test-2/actions/runs/13434113509/job/37532392021#step:2:1048): main ❌
- [action-2@ref2 from workflow in step env](https://github.com/tjamet/composite-action-test-2/actions/runs/13434113509/job/37532392021#step:3:867): v1 ✅ 

I believe this issue has similarities , but differs from #41927, #2473 and #49245

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by felipeinf** [comment]
# In GitHub Actions, `${{ github.action_ref }}` behaves inconsistently depending on context

## 🧪 Topic Area
Bug – GitHub Actions

## 📝 Description

We recently encountered inconsistent behavior when using `${{ github.action_ref }}` in composite actions — particularly when composite actions use other composite actions internally.

### ❗ Observed behavior

The value of `${{ github.action_ref }}` **differs depending on where it's used**:

- In `inputs.*.default`, it resolves to the **current action's ref** (`ref2` if inside `action-2@ref2`)
- In `steps.*.env.*`, it resolves to the **calling action's ref** (`ref1` if `action-2@ref2` is called from `action-1@ref1`)

---

### 📦 Minimal Example

#### `action-1@ref1`:
```yaml
steps:
  - uses: action-2@ref2
```

#### `action-2@ref2`:
```yaml
name: 'Test actions composite'
inputs:
  action-ref:
    default: ${{ github.action_ref }}

runs:
  using: composite
  steps:
    - name: dump input
      run: echo '${{ inputs.action-ref }}'
      shell: bash

    - name: dump env
      env:
        JSON_ENCODED: ${{ github.action_ref }}
      run: echo "${JSON_ENCODED}"
      shell: bash
```

---

### 🔍 Result Comparison

| Scenario                                   | Input (`inputs.action-ref`) | Step env (`github.action_ref`) |
|--------------------------------------------|------------------------------|----------------------------------|
| `action-2@ref2` run directly               | `ref2` ✅                    | `ref2` ✅                        |
| `action-2@ref2` called via `action-1@ref1` | `ref2` ✅                    | `ref1` ❌                        |

---

### 🤔 Expected Behavior

We expect `${{ github.action_ref }}` to consistently refer to the current action's ref (`ref2`), regardless of where it's accessed — whether in `inputs.default` or `env`.

---
