### DISCUSSION TITLE
Can the on.*.runs-on field be an expression ?

### DISCUSSION THREAD

**Discussion by AaronNGray** [community/community#152090] [Actions] [answered]
### Select Topic Area

Question

### Body

Can the on.*.runs-on field be an expression ?

```
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      machine:
        description: 'Machine to run the build on.'
        type: choice
        options: 
          - 'ubuntu-24.04-arm'
          - 'self-hosted, ubuntu-22.04, ARM64'
        default: 'ubuntu-24.04-arm'
        required: true       

jobs:
  build:
    runs-on: ${{ inputs.machine }}
    environment: release-env

    steps:

    - name: echo machine
      run: echo "inputs.machine = " ${{ inputs.machine }}
```

https://github.com/AaronNGray/github-actions-choice-runs-on
