### DISCUSSION TITLE
Unable to pull private docker package within the same repo

### DISCUSSION THREAD

**Discussion by tyrelh** [community/community#152062] [Packages] [answered]
### Select Topic Area

Question

### Body

I think I'm missing something and I cannot seem to find the appropriate docs for this.

What I'm trying to do is pull and use a private docker image from ghcr as a Workflow Step.

First, I have a workflow like this that is building the docker image and successfully pushing it to the private repository:

```yaml
name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Metadata
      id: metadata
      run: |
        # convert repository name to lowercase
        repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        tag="ghcr.io/${repo}/test-action:latest"
        echo "TAG=$tag" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./test-action
        file: ./test-action/Dockerfile
        push: true
        tags: ${{ steps.metadata.outputs.TAG }}
        target: production
```

This seems to work as expected. ✅

But then, within the same repository I cannot pull this image using the `uses: docker://<image>` syntax in a step.

```yaml
name: Run docker image from ghcr

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Test
      uses: docker://ghcr.io/myorg/myrepo/test-action:latest
```

When the workflow run tries to pull the image before running the steps I get an `unauthorized` error: `Error response from daemon: Head "https://ghcr.io/v2/myorg/myrepo/test-action/manifests/latest": unauthorized`

I also tried modifying the Workflow permissions but got the same error:

```yaml
name: Run docker image from ghcr

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
    - name: Test
      uses: docker://ghcr.io/myorg/myrepo/test-action:latest
```

The following did work as expected, but the syntax feels much worse in the workflow. I'd like to avoid using a shell step and the `docker` cli if possible:
```yaml
name: Run docker image from ghcr

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: |
        docker pull ghcr.io/myorg/myrepo/test-action:latest
        docker run ghcr.io/myorg/myrepo/test-action:latest
```

My question is how can I properly authenticate with ghcr while using the `uses: docker://<image>` syntax? Since it tries to pre-pull the images before running the steps I can't use the `docker/login-action` to authenticate using my _GITHUB_TOKEN_.

Also this is within an Enterprise Organization if that makes any difference. I want to ensure everything is centralized on the org and/or repo and not use user-level access tokens.

Thanks for your assistance and would appreciate any docs links I'm missing 🙏🏻

**Comment by Hub-Mo** [comment, marked as answer]
I've actually run into this exact problem in our enterprise org too! The uses: docker:// syntax is frustrating because it runs before any of your auth steps.
For private GHCR images, I found two approaches that work reliably:

The job container approach worked best for me:

```
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/myorg/myrepo/test-action:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
```

If you need more flexibility with multiple steps, you can create a Docker action in your repo (just a Dockerfile + action.yml) that references your ghcr image, then use:

```
steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/my-action
```
The second approach lets you keep using the cleaner action syntax while avoiding the auth issues completely since it's pulling from your local repo after checkout.
I spent way too many hours debugging the "unauthorized" errors before figuring this out! The docs don't make this limitation super clear unfortunately.
