### DISCUSSION TITLE
"Upload to release" action not working/enabled.

### DISCUSSION THREAD

**Discussion by AaronNGray** [community/community#152084] [Actions]
### Select Topic Area

Question

### Body

I am trying to add ARM64 build  and release support to ICU https://github.com/unicode-org/icu/ and need to be able to get the existing icu4c C++ build and release actions working as my own fork first.

<img width="730" alt="icu-release-action" src="https://github.com/user-attachments/assets/5881ebe9-a02a-4689-b230-c22aa1e14ad0" />

https://github.com/AaronNGray/icu/blob/main/.github/workflows/icu4c.yml#L935

The build and artifact generation and upload work fine, but the "Upload to release" seems not to be enabled and no release on the projects homepage appears

```
    - name: Upload to release
      if: ${{ inputs.gitReleaseTag && startsWith(inputs.gitReleaseTag, 'release-') }}
      run: |
        gh release upload ${{ inputs.gitReleaseTag }} ${RELEASE_FOLDER}/* --clobber --repo=${{ github.repository }}
      env:
        GH_TOKEN: ${{ github.token }}
```
I have created a `release-77-1` tag.

https://github.com/AaronNGray/icu/actions/runs/13466292404/job/37632706242#step:10:20
