### DISCUSSION TITLE
Skipped jobs names are not evaluated, resulting in gibberish

### DISCUSSION THREAD

**Discussion by MaxymVlasov** [community/community#152293] [Actions]
### Select Topic Area

Product Feedback

### Body

We have a reusable workflow which able to calculate names on the fly:

```yaml
jobs:
  pre-setup:
    ...
  build:
    name: 📦 ${{ needs.pre-setup.outputs.git-tag }}
    ...
  tests:
    name: 🧪 Tests${{ '' }} # nest jobs under the same sidebar category
```

When we skip them by certain condition, it ends in this:
![image](https://github.com/user-attachments/assets/deb5da6a-93f0-4298-9bf8-813791692663)

Can you please make GH workflows able to evaluate job names (when it is possible) before skip them?

Originally from https://github.com/antonbabenko/pre-commit-terraform/pull/821/files#r1968325672
