### DISCUSSION TITLE
Action suddenly not started with cron, saying (Unknown event)

### DISCUSSION THREAD

**Discussion by shayp123** [community/community#152481] [Actions]
### Select Topic Area

Question

### Body

Hi all, 
I have this GitHub workflow where it can be triggered also manually and also with cron,

the cron worked very well until yesterday when suddenly all the workflow runs faile to startup saying `(Unknown event)`
no code changes where made to the workflow file and I can still trigger it manually without a problem

Thanks for helping

```
name: Some name
on:
  schedule:
    - cron: "3 * * * *"
  workflow_dispatch:
    inputs:
      NoNeed:
        required: false
        description: No need
        type: string
```

![Screenshot 2025-02-26 at 13 23 57](https://github.com/user-attachments/assets/bac53a90-949a-403d-b831-9abd814234ea)
