### DISCUSSION TITLE
[Fixed] jobs.<job_id>.uses can't be used due to "Missing required key `runs-on`"

### DISCUSSION THREAD

**Discussion by moomiji** [community/community#15272] [Actions] [answered]
For example the following code (from [Github Docs](https://docs.github.com/cn/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow)):
```YAML
name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: octo-org/example-repo/.github/workflows/called-workflow.yml@v1
```

It was still available at 2022-04-15T16:50:56Z, but failed to run after I push to my repo at 2022-04-19T16:43:33Z.
