### DISCUSSION TITLE
GitHub Actions to automate deployments to GitHub Pages

### DISCUSSION THREAD

**Discussion by lunafoster** [community/community#152840] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

How do I use GitHub Actions to automate deployments to GitHub Pages?

**Comment by ghost** [comment, marked as answer]
You can use GitHub Actions to automate the build and deployment process. Here’s an example workflow for a Jekyll site:

```yaml
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build site
        run: bundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
```

This workflow:
1. Checks out the code.
2. Sets up Ruby and installs dependencies.
3. Builds the Jekyll site.
4. Deploys the built site to the `gh-pages` branch.
