### DISCUSSION TITLE
Unable to run systemd in container using GitHub Actions `container` option

### DISCUSSION THREAD

**Discussion by gbraad** [community/community#153131] [Actions]
### Select Topic Area

Bug

### Body

I'm encountering an issue with running `systemd` in a container using GitHub Actions. When I try to force `--entrypoint /sbin/init` and/or run `systemctl enable --now httpd`, I receive the following error:

```bash
$ systemctl enable --now httpd
--now cannot be used when systemd is not running or in conjunction with --root=/--global, refusing.
```

However, running the container with `docker run --privileged` on the runner works correctly. It seems that the `container` option in GitHub Actions does not handle `systemd` the same way.

## Steps to reproduce
1. Use a container with `systemd` installed.
2. Configure GitHub Actions workflow to use the container with `--privileged` option.
3a. Attempt to access httpd, or test the service is running.
3b. Force the service to run: `systemctl enable --now httpd`

## Expected behavior:
The `httpd` service should start without errors.

### Additional information
```yaml
jobs:
  dotfiles-test:
    runs-on: ubuntu-latest

    container:
      image: registry.access.redhat.com/ubi8/httpd-24:latest
      options: --privileged --entrypoint /sbin/init
    
    steps:
      - name: Verify setup
        run: |
          until systemctl is-active --quiet httpd
          do
               sleep 1
          done

      - name: ...
        run: |
          ...
```

### Workarounds
The current way to accomplish this is to do the following:

```yaml
jobs:
  dotfiles-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run system container with `podman`
        run: |
          podman run -d --name httpd --hostname httpd-${HOSTNAME} \
            --systemd=always \
            registry.access.redhat.com/ubi8/httpd-24:latest

      - name: Verify setup (optional to indicate this works)
        run: |
          podman exec httpd systemctl enable --now httpd   # Redundant
          until podman exec httpd systemctl is-active --quiet httpd
          do
               sleep 1
          done

      - name:...
        run: |
          ...
```

### Impact
This issue is affecting our ability to run services that require `systemd` within a container in the CI/CD pipeline, that match actual usage of the project compiled and tested.

### Note

If the argument is that `init` (systemd) is a long-running process, then understand that doing a `shutdown -h now` in the container works as expected on docker and podman, and so do `sudo init 0`, `sudo poweroff`, `sudo systemctl poweroff`, `sudo systemctl isolate poweroff.target`, etc.
