### DISCUSSION TITLE
Environment Specific secrets not working when calling workflow from another workflow

### DISCUSSION THREAD

**Discussion by ftatliamtech** [community/community#153151] [Actions]
### Select Topic Area

Question

### Body

I have a Deployment Workflow with AWS configure like this

```
name: CD-Deploy
run-name: Was initiated by ${{ github.actor }}, event name ${{ github.event_name }}, event type ${{ github.event.action }}

on:
  workflow_call:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-22.04    
    environment: sandbox
    defaults:
      run:
        working-directory: ./
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Debug AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID != '' && '***' || 'NOT SET' }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' && '***' || 'NOT SET' }}"
          echo "AWS_REGION: ${{ secrets.AWS_REGION != '' && '***' || 'NOT SET' }}"  
          
      - name: Configuring AWS credentials...
        uses: aws-actions/configure-aws-credentials@v4
        #env:
          #AWS_DEFAULT_REGION: ${{ null }}
          #AWS_REGION: ${{ null }}
          #AWS_ACCESS_KEY_ID: ${{ null }}
          #AWS_SECRET_ACCESS_KEY: ${{ null }}
          #AWS_SESSION_TOKEN: ${{ null }}
        with:
          aws-region: ${{ secrets.DEPLOY_AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #role-to-assume: ${{ secrets.AWS_ROLE }}
          #aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}         
          #role-duration-seconds: 3600
      - name: Execute deploy commands via SSM
      ....
      .....
```
I have created the "sandbox" environment in Settings and added the AWS secrets in it. **It works!**

Now I am trying to call the above Deploy from another workflow like below 

```
name: CICD
run-name: Was initiated by ${{ github.actor }}, event name ${{ github.event_name }}, event type ${{ github.event.action }}

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  backend:    
      uses: ./.github/workflows/CI-Backend.yaml
  frontend:
      needs: backend
      uses: ./.github/workflows/CI-Frontend.yaml
  deploy:
      needs: frontend
      uses: ./.github/workflows/CD-Deploy.yaml
```

This gives me error saying "AWS Region" input is not set.

Any idea how to make this work ?

**Comment by stempler** [comment]
You need to pass on the secrets:

```
jobs:
  backend:    
    uses: ./.github/workflows/CI-Backend.yaml
    secrets: inherit
```

There is an example in the [documentation](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow).
