### DISCUSSION TITLE
Automatically Export Audit Logs

### DISCUSSION THREAD

**Discussion by sulaimanlodewyk** [community/community#153229] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

Good Day
I am able to export the Audit Logs with the manual Process.
Has anyone been able to automate this process possibly via a workflow? I have tried and not having joy.
Thanx

**Comment by HackerOwl** [comment]
To automate the export of GitHub audit logs, you can leverage GitHub Actions to create a workflow that periodically exports the logs and stores them in a desired location.

1. Create a New Repository or Use an Existing One
2. In your repository, navigate to `.github/workflows` and create a new file, e.g., `export-audit-logs.yml`.
3. The workflow will use the GitHub API to fetch audit logs and store them in a specified location, such as AWS S3, Google Cloud Storage, or Azure Blob Storage.

Here is an example workflow that exports audit logs to an AWS S3 bucket

````yaml name=.github/workflows/export-audit-logs.yml
name: Export Audit Logs

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  export-audit-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Audit Logs
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/orgs/YOUR_ORG_NAME/audit-log > audit-log.json

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: './'
        DEST_DIR: 'audit-logs/'

    - name: Clean up
      run: rm audit-log.json
````

- Schedule: The `cron` schedule is set to run daily at midnight UTC. Adjust this to your needs.
-  Fetch Audit Logs : Uses `curl` to fetch the audit logs from the GitHub API and saves them to a file called `audit-log.json`.
-  Upload to S3 : Uses the `s3-sync-action` to upload the `audit-log.json` file to an AWS S3 bucket. Make sure to set up the required AWS secrets (`AWS_S3_BUCKET`, `AWS_ACCESS_KEY_ID`, and `AWS_SECRET_ACCESS_KEY`) in the repository's settings under "Secrets".
- Clean up : Removes the `audit-log.json` file after uploading.

Hope it helps, please check if it works or not
