### DISCUSSION TITLE
[feat]: Add issue type option to ISSUE_TEMPLATES

### DISCUSSION THREAD

**Discussion by trueberryless** [community/community#153436] [Other Feature Feedback, Questions, & Ideas]
Issue types are a very new concept (maybe even in public beta right now) and I really like them! 

By default there are two types: Bug and Feature, which you can [customise for organisations](https://docs.github.com/en/issues/tracking-your-work-with-issues/configuring-issues/managing-issue-types-in-an-organization).

---

Issue templates are markdown files which specify, how an ideal issue any user creates in your repo (or even organisation with the .github repo) should look like.

Issue forms even enhance the experience by defining the template in yaml, which will then render as text boxes or supported types.

---

I THINK that this is a great opportunity to add a new field to issue forms, which specifies the default issue type of the issue template.

As an example (line 5):

```yaml
name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
type: "bug" // here is the new issue form field
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
```

What do you think about such an addition? Should we wait until the issue type is out of beta and more stable or maybe integrate this feature right away? Share your thoughts down 👇
