### DISCUSSION TITLE
When can I comment out a line in YAML and when can't I comment out a line in YAML?

### DISCUSSION THREAD

**Discussion by rfalanga** [community/community#153477] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm taking a training course to learn YAML better, for writing better GitHub Actions/Workflows. One thing I have done for years, in all my programming, is comment out a line, if I want to keep it around for refer. This has never caused me any problems in C. C#, C++, PowerShell, etc. Today, while working on a YAML file in the course, which was not building in GitHub Actions, I thought I would delete 4 commented out lines I had left in the YAML file. After removing the commented out lines, suddenly the YAML file worked!

However, what confuses me is in other YAML files I've worked on, commenting out some lines doesn't cause any problems with the YAML.

So, I am confused. When can I comment out a line in YAML and when can't I comment out a line in YAML? At least here on GitHub.

**Comment by davevad93** [comment]
Hi @rfalanga,

The main difference when commenting a `YAML` file is that it doesn't support the creation of block or multiline comments as in `C#`, `Python`, `Java`, etc.

You can't do this:

```text
/* This is 
a comment */
```

But you can do this:

```text
# Comment 1
# Comment 2
# Comment 3
```

The comment(s) must be properly indented, otherwise the action won't work, for example:

```yml
# This GitHub Actions workflow is named 'Greetings'
# It is triggered when a user opens an issue or a pull request (PR) for the first time.

name: Greetings

on: 
  # The workflow runs when an issue or a pull request is opened.
  - pull_request_target
  - issues

jobs:
  greeting:
    # Specifies that the job runs on the latest version of Ubuntu.
    runs-on: ubuntu-latest

    permissions:
      # Grants write permission to issues.
      issues: write
      # Grants write permission to pull requests.
      pull-requests: write

    steps:
      # Uses the 'first-interaction' GitHub Action to send a greeting message
      # when a user opens their first issue or pull request in the repository.
    - uses: actions/first-interaction@v1
      with:
        # Provides the GitHub token to authenticate the action.
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Message displayed when a user creates their first issue. (Commenting Out)
        # issue-message: "Message that will be displayed on users' first issue"
        
        # Message displayed when a user creates their first pull request.
        pr-message: "Message that will be displayed on users' first pull request"

```

**Reply by rfalanga** [reply]
Thank you, @davevad93 this is very good information. Here's a snippet from a previous version of the YAML file which didn't work:

```yaml
steps:
    - run: pwd && ls -la # check the current directory and list all files before
    - uses: actions/checkout@v4
    - run: pwd && ls -la # check the current directory and list all files after
    # - run: go version # check the go version before
    - uses: actions/setup-go@v5
      with: # use this to pass parameters to the action
        go-version: '1.22'
        # go-version-file: ./upper/go.mod # this causes it to read that go.mod file
       cache-dependency-path: ./upper/go.sum # this causes it to cache the go.sum file
       # - run: go mod download # download the dependencies
       #   working-directory: upper # change the working directory to the upper directory
       - run: ls
      - run: go build
     - run: ls
     - run: go test -v
     - uses: actions/upload-artifact@v4
         with:
        path: ./upper/upper
        name: build
```

Once I removed all the lines I had commented out, it worked perfectly. I was wondering if the use of commented lines in with `with` is what caused the problem?

**Reply by davevad93** [reply, marked as answer]
Hey @rfalanga you're welcome, it seems to me that the problem here is due to indentation.

This should work:
```yml
steps:
  - run: pwd && ls -la # check the current directory and list all files before
  - uses: actions/checkout@v4
  - run: pwd && ls -la # check the current directory and list all files after
  
  # - run: go version # check the go version before
  
  - uses: actions/setup-go@v5
    # use this to pass parameters to the action
    with: 
      go-version: '1.22'
      # go-version-file: ./upper/go.mod # this causes it to read that go.mod file
      cache-dependency-path: ./upper/go.sum # this causes it to cache the go.sum file
  
  # - run: go mod download # download the dependencies
  #   working-directory: upper # change the working directory to the upper directory
  
  - run: ls
  - run: go build
  - run: ls
  - run: go test -v
  
  - uses: actions/upload-artifact@v4
    with:
      path: ./upper/upper
      name: build

```
