### DISCUSSION TITLE
PR check status is broken

### DISCUSSION THREAD

**Discussion by alzix** [community/community#153503] [Pull Requests]
### Select Topic Area

Bug

### Body

in case i have 2 different PRs starting from the same commit-sha and targeting different branches the status checks from both PRs are mixed more over there is a race condition between the PR checks.

Consider the following case:

![image](https://github.com/user-attachments/assets/668deee5-eeb7-4412-8a03-da76fa26511d)
I have the following workflow file on `rc/1.1` branch:
```
name: POC
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-poc:
    runs-on: ubuntu-latest
    name: POCTEST
    steps:
      - name: extra step for testing
        run: echo "success"
```

and workflow with a _bug_ on master branch which always failed:
```
name: POC
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-poc:
    runs-on: ubuntu-latest
    name: POCTEST
    steps:
      - name: extra step for testing
        run: echo "fail" && false
```

The workflow for PR1 checks out `refs/pull/1/merge` while on PR2 it checks out `refs/pull/2/merge`. Despite the equality of PR source branch HEAD SHA these refs are different as the target branch is different.

It seems that checks status is bound to a particular commit which is shared between both PRs. So the SAME status is shown in both PRs. In my case the check on the PR2 is failing while the check on PR1 is passing just fine.
so there is a race - the job that will finish last publishes the check status on both PRs.
btw the link to the relevant check from the PR shows it did fail while the status on the PR conversation page is shown as successful 

It seems that checks should not be bound to commit hashes but a combination of PR+commit hash
