### DISCUSSION TITLE
Create an Issue is not triggering workflow

### DISCUSSION THREAD

**Discussion by Bryson-Tai** [community/community#153512] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hi community,

I have this workflow YAML to create an issue with my own `PAT TOKEN`
```
name: Create Issue Through gh CLI

on:
  push:

jobs:
  label_issue:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
```

And when there is an issue `opened`, I want to trigger workflow below.
```
name: Workflow Trigger by Issue

on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Tests"
      - env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"
```

I found this is a common confusion for most of us who is learning GitHub Workflow initially. Hope someone could provide a solution or working example is appreciated 😄 

Issue that created through workflow using my own `PAT TOKEN`
![image](https://github.com/user-attachments/assets/482eee76-f09d-400d-95f7-d0cbcb933e3c)
