### DISCUSSION TITLE
Unable to access a private repo with fine-grained token via org-level secrets

### DISCUSSION THREAD

**Discussion by jiawei-janna-lin** [community/community#153738] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi all,

I am trying to run a workflow on some private repos, which need to pull codes from another separate private repo in the same organization. I generated a PAT with the following permissions:
<img width="903" alt="Screenshot 2025-03-11 at 5 25 07 PM" src="https://github.com/user-attachments/assets/3463b52a-5eef-4516-aeee-6f5d317dfd9f" />

and added this generated token to the Organization secrets, which is then set to be visible by all repos. 

My code that uses it to access the repo in workflow is:
```    - name: Debug Secrets
        run: |
          echo "Checking if STAFF_REPO_TOKEN is available..."
          if [ -z "${{ secrets.STAFF_REPO_ACCESS }}" ]; then
            echo "STAFF_REPO_ACCESS is missing!"
            exit 1
          else
            echo "STAFF_REPO_ACCESS is set correctly."
          fi
      - name: Checkout Staff Tests
        uses: actions/checkout@v4
        with:
          repository: (name of our repo)
          token: ${{ secrets.STAFF_REPO_ACCESS }}
```
          
It turns out that STAFF_REPO_ACCESS is set correctly, but it shows "Error: Not Found - https://docs.github.com/rest/repos/repos#get-a-repository" when proceeding to the next step. 

What could be the problem? Thanks!

**Comment by CloneOfAlex** [comment, marked as answer]
You're seeing the `Error: Not Found` because the PAT (Personal Access Token) likely doesn't have sufficient permissions to access the private repository. Even though the token exists and is correctly referenced, this error generally means GitHub is denying access (usually due to missing or incorrect scopes).

Here's what typically causes this:

### ✅ **Common Cause**

Your PAT doesn't have adequate permissions to **read private repositories** (`repo` scope).

### 🔎 **How to Fix This**

Make sure your PAT includes the correct permissions:

- **`repo` scope** (critical for accessing private repositories)
  - **repo: Full control of private repositories** (needed!)
  - Make sure to select:  
    - ✅ `repo` (**all sub-options under repo**)
    - ✅ `workflow` (recommended if you're triggering actions/workflows across repos)

### 🔧 **Detailed Steps to Verify/Fix**

1. **Regenerate the PAT**:
   - Go to your [[GitHub settings → Developer settings → Personal access tokens](https://github.com/settings/tokens)](https://github.com/settings/tokens).
   - Generate a new PAT, explicitly selecting:
     - `repo` scope (all sub-permissions checked)
     - Optionally `workflow` permission

2. **Add or Update Organization Secrets**:
   - Re-create or update the existing secret (`STAFF_REPO_ACCESS`) at the **organization-level** or in your repo's Secrets page with this newly generated PAT.

3. **Re-run your workflow**:
   ```yaml
   steps:
     - name: Verify Token
       run: |
         if [ -z "${{ secrets.STAFF_REPO_ACCESS }}" ]; then
           echo "Token is missing!"
           exit 1
         else
           echo "STAFF_REPO_ACCESS is set correctly."
         fi

     - name: Checkout Private Repo
       uses: actions/checkout@v4
       with:
         repository: your-org/private-repo-name
         token: ${{ secrets.STAFF_REPO_ACCESS }}
         path: private-repo
   ```

   **Important:**  
   Make sure your `repository` field matches the format exactly:  
   ```yaml
   repository: org-name/private-repo-name
   ```

### Common pitfalls that trigger the "Not Found" error:

- **Incorrect repository name or missing org prefix** (e.g., `private-repo` instead of `org/private-repo`).
- PAT not scoped for **private repo access** (`repo` scope not fully enabled).
- Secret not properly updated or mistakenly overwritten with a wrong or expired token.

### Recommended debugging steps:

- Temporarily try your token in a local `git clone` to ensure it has private repo access:
  ```bash
  git clone https://<your-token>@github.com/org/private-repo.git
  ```
  If this fails, your PAT definitely doesn't have access.

- Verify again your GitHub secrets to ensure they contain the correct PAT.

---

**Summary:**  
Your error (`Error: Not Found`) is almost certainly related to permissions. The token you're using must have full `repo` access (`repo` scope), and ensure you've referenced the correct repository format (`org/private-repo`).

Update your PAT permissions and confirm your secret, and your workflow should succeed!
