### DISCUSSION TITLE
Run job only on release but not pre-release

### DISCUSSION THREAD

**Discussion by caco3** [community/community#154072] [Actions] [answered]
### Select Topic Area

Question

### Body

I am in need to run a job only on a release but not on a pre-release.
Background:
We have a pipeline which runs on every push and pull_request.
In case of a release, we want to update the Github pages. But not on pre-releases.

This is my PoC:
```yaml
name: Build and Pack

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Building..."

  update-pages:
    if: github.event_name == 'release' && github.event.action == 'published' # Only run on release but not on prerelease
    runs-on: ubuntu-latest

    steps:
    - run: echo "We are on a release"
```

The line ` if: github.event_name == 'release' && github.event.action == 'published` is taken from https://github.com/orgs/community/discussions/26281#discussioncomment-3251182 but seems not to work as expected:
The job just never runs, not on a release, not on a pre-release and not on a normal push.

**Comment by tanyatiwari995** [comment]


**Reply by caco3** [reply]
@tanyatiwari995  Thanks for your response! But it is really hard to read. Could you format the code please?
Please use 
    ![grafik](https://github.com/user-attachments/assets/a02d9472-f550-41d7-99fc-a006580f302c)
to format the code.

**Comment by tanyatiwari995** [comment]
- **Effective Answer: Run Job Only on Release (Not Pre-Release) in GitHub Actions**
- **Issue:**
- Your job update-pages is not running as expected. The issue is that on: [push, pull_request] does not include the release event.
- ### 
- **Fixed GitHub Actions Workflow**
- You need to explicitly trigger the workflow on release events and check if the release is a pre-release.
- 
- **Solution: Use on: release and Check prerelease: false
- name: Build and Pack
- on:
- push:
- pull_request:
- release:
- types: [published] # Ensures it only runs when a release is published (not pre-release)
- jobs:
- build:
- runs-on: ubuntu-latest
- steps:
- - run: echo "Building..."**
- 
- **update-pages:
- if: github.event.release.prerelease == false # Ensures it runs only on full releases
- runs-on: ubuntu-latest
- steps:
- - run: echo "We are on a full release!"
- Why This Works
- on: release explicitly listens for release events.
- types: [published] ensures it only runs on actual releases (not draft or pre-release).
- github.event.release.prerelease == false ensures it does not run on pre-releases**.
- 
- - **Expected Behavior
- - Runs on push and pull_request for normal builds.
- - 
- - Runs update-pages only when a full release is published.
- - 
- - Does NOT run on pre-releases.
- - 
- - Does NOT run on normal pushes or pull requests for update-pages.
- - 
- - This ensures your GitHub Pages update only on actual releases, preventing unnecessary deployments on pre-releases. 🚀
- - 
- - You said:
- - in other method
- - 
- - Alternative Method: Use github.ref_type and github.event.action
- - Instead of checking github.event.release.prerelease, you can verify the event type and reference name.
- - 
- - Solution: Use github.ref_type and github.event.action
- - 
- - name: Build and Pack
- - 
- - on:
- - push:
- - pull_request:
- - release:
- - types: [published]
- - 
- - jobs:
- - build:
- - runs-on: ubuntu-latest
- - steps:
- - - run: echo "Building..."
- - 
- - update-pages:
- - if: github.event.action == 'published' && github.event.release.prerelease == false
- - runs-on: ubuntu-latest
- - steps:
- - - run: echo "Updating GitHub Pages for release!"
- - How This Works
- - on: release ensures the workflow listens for release events.
- - github.event.action == 'published' runs only when a release is published.
- - github.event.release.prerelease == false ensures the job runs only on full releases (not pre-releases).**

**Comment by ilianoKokoro** [comment, marked as answer]
Hey, here is what I think you are looking for 

First you have to add the `release` in the `on` list for the action to trigger when a release is published. The `types` can be set to `released` to only trigger when the release is published and is not a pre-release.

Then, you only have to check that the trigger is a release to continue with the `update-pages`
`github.event_name == 'release'`

```yaml
name: Build and Pack

on:
    push:
    pull_request:
    release:
        types: [released] # Only trigger on published releases (not drafts or pre-released)

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - run: echo "Building..."

    update-pages:
        if: github.event_name == 'release' # Only run when the trigger is a release
        runs-on: ubuntu-latest

        steps:
            - run: echo "We are on a release"
```
