### DISCUSSION TITLE
Repository access blocked on action when trying to run script in the repo that uses GitHub API

### DISCUSSION THREAD

**Discussion by cirosantilli** [community/community#154227] [Actions] [answered]
### Select Topic Area

Question

### Body

Edit2: OK possible minimal curl repro, this works on repo https://github.com/cirosantilli/test-git-web-interface creating https://github.com/cirosantilli/test-git-web-interface/issues/134

```
curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <token>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/cirosantilli/test-git-web-interface \
  -d '{"title":"Found a bug","body":"I'\''m having a problem with this."}'
```

but the exact same thing fails for https://github.com/cirosantilli/china-dictatorship so it looks like GitHub blocked actions on that repo for some reason.

However doing it from Js:

```
#!/usr/bin/env node

import { Octokit } from "@octokit/core";

const octokit = new Octokit({
  auth: '<token>'
})

console.log(await octokit.request('POST /repos/cirosantilli/china-dictatorship/issues', {
  owner: 'OWNER',
  repo: 'REPO',
  title: 'Found a bug',
  body: 'I\'m having a problem with this.',
  headers: {
    'X-GitHub-Api-Version': '2022-11-28'
  }
}))
```

did work! https://github.com/cirosantilli/china-dictatorship/issues/1444 I'm so confused.

Edit: OK added a print to top of script and the issue is with GitHub API not the action, the red was just ANSI formatted error message which GitHub interprets and confused me. So the question is what does that error message mean for the API: https://github.com/cirosantilli/china-dictatorship/actions/runs/13918011359/job/38944567784#step:11:9 It was working fine before. https://stackoverflow.com/questions/25398376/why-i-got-exception-403-repository-access-blocked-using-pygithub says could be bad credentials.

Hello, what is the meaning of this error message? Do I need to contact support to get it cleared, or is there something I can do myself to solve the issue? E.g. is it related to the recent deprecations? Sample run: https://github.com/cirosantilli/china-dictatorship/actions/runs/13917639604/job/38943510697 By the formatting of error messages it looks like the error is coming from the action itself rather than from my script, is that correct? Thanks.

```
Run /home/runner/work/china-dictatorship/china-dictatorship/action.js
Error: Repository access blocked
Error: Process completed with exit code 1.
```

My workflow is:

```
name: Issue
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  Issue:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "github.event_name ${{ github.event_name }}"
      - run: echo "github.ref ${{ github.ref }}"
      - run: echo "github.repository ${{ github.repository }}"
      - run: echo "github.workspace ${{ github.workspace }}"
      - run: echo "runner.os ${{ runner.os }}"
      - run: pwd
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: npm install
      - run: ls "${{ github.workspace }}"
      - name: Main work
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: "${{ github.workspace }}/action.js"
      - run: echo "job.status ${{ job.status }}."
```

I also treid updating to:

```
name: Issue
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  Issue:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "github.event_name ${{ github.event_name }}"
      - run: echo "github.ref ${{ github.ref }}"
      - run: echo "github.repository ${{ github.repository }}"
      - run: echo "github.workspace ${{ github.workspace }}"
      - run: echo "runner.os ${{ runner.os }}"
      - run: pwd
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: ls "${{ github.workspace }}"
      - name: Main work
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: "${{ github.workspace }}/action.js"
      - run: echo "job.status ${{ job.status }}."
```

but same error: https://github.com/cirosantilli/china-dictatorship/actions/runs/13917914073/job/38944281834
