### DISCUSSION TITLE
GitHub Action to assign value to Project custom field

### DISCUSSION THREAD

**Discussion by DerekDettler** [community/community#154299] [Actions]
### Select Topic Area

General

### Body

Is it possible to have an action set custom fields of a project? I don't want the action to be triggered for every issue created rather I only want the action to be triggered when the user adds an item to a specific project. So that would look like this:

User edits Issue and clicks 'Projects'
User selects 'Project A' from the list of available projects
Action is triggered and sets the custom field "Date Assigned" in Project A to the current date

**Comment by ricardious** [comment]
Yes, you can automate setting a custom field "Assignment Date" when a user adds an issue to "Project A" in GitHub. You can use the [`[actions/add-to-project](https://github.com/actions/add-to-project)`](https://github.com/actions/add-to-project) action for this.

#### Workflow Example:
```yaml
name: Add issue to Project A and set Assignment Date

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Project A
        uses: actions/add-to-project@v1
        with:
          project-url: ${{ secrets.PROJECT_A_URL }}
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fields: '{"Assignment Date": "{{ today }}"}'
```

#### Steps to Set It Up:
1. **Get the project URL:** Go to "Project A" on GitHub and copy the URL.
2. **Configure secrets:**
   - Add `PROJECT_A_URL` under "Secrets and variables" > "Actions".
   - Create a [[Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) with `repo` and `project` permissions, and save it as `PERSONAL_ACCESS_TOKEN`.
3. **Create the workflow:** Save the code in `.github/workflows/add_to_project.yml`.

This workflow triggers whenever an issue is opened, adding it to "Project A" and setting the current date as the assignment date.
