### DISCUSSION TITLE
Environment Name as a variable?

### DISCUSSION THREAD

**Discussion by j-krupka-ttpsc** [community/community#154285] [Actions]
### Select Topic Area

Question

### Body

Hi all, 
I think I am missing something. 
```
jobs:       
  job-name-goes-gere:
    environment: 
      name: dev-01
```
In github, is there a way to access the value 'dev-01' ?
I cannot find a variable which i could reference?

What i am trying to accomplish here, is that I have an input to set the environment:
```
on:
  workflow_dispatch:
    inputs:
      environment_type_environment:
        description: 'Environment to run tests against'
        type: environment
        default: ""
        required: true
```
which then I want to use inside of the workflow so select one from many deploy jobs
```
jobs:
   deploy1:
     enviornment: 'dev-01'        
     # idea: if: github.ref == 'refs/heads/main' || github.event.inputs.environment_type_environment == ????
     steps: ...
   deploy2:
     enviornment: 'dev-02'
     # idea: if: github.ref == 'refs/heads/main' || github.event.inputs.environment_type_environment == ????
     steps: ...
   deploy3:
     enviornment: 'dev-03'
     # idea: if: github.ref == 'refs/heads/main' || github.event.inputs.environment_type_environment == ????
     steps: ...
```
now, based on the input variable, the proper job is selected on my featurue branch. On main - all 3 deplys are done.

Deploy 1, 2 and 3 have different steps to perform and cannot be reused.
