### DISCUSSION TITLE
Github actions trigger on new tag

### DISCUSSION THREAD

**Discussion by diniguezcabrera** [community/community#154396] [Actions]
### Select Topic Area

Question

### Body

Hello, I'm facing a problem trying to trigger a workflow after the creation of a new tag.

I have two workflows whose flow should be as follows:

The first one should create a new tag in the repository in the main branch. It has the following conditionals:

```
on:
  pull_request:
    branches:
      - main
    types:
      - closed
```
The second one should be launched after the creation of a new tag in the main branch. It has the following conditionals:

```
    on:
      push:
        tags:
          - '**'
```
The way I push the tag on the first workflow is:

          git checkout main
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
I've tried to use a different auth with github in the first worflow, changing the GITHUB_TOKEN, creating a github app and doing like [this documentation](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow) explain, but it doesn't work, the second workflow doesn't get triggered.

If I manually create a tag from the terminal or CLI, the second workflow is correctly triggered.

I've also tried to change the glob on the tags of the second workflow like '*', tags: ["**"], etc with no results.

The problem seems to be on the trigger of the second workflow, but I don't know what it is.

What am I missing?

**Comment by mickeygousset** [comment]
You are on the right track using an app or PAT for the first workflow, as by default the GITHUB_TOKEN doesn't allow for triggering other workflows.

And how are you referencing the token in the first workflow? Can you share more of your file? Are they available in a public repo?

If you want to take the APP out of the equation for now, just use your own PAT. You can do something like this in the first workflow

```
- name: Create and push tag
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"
    git checkout main
    git tag ${{ env.NEW_TAG }}
    git push origin ${{ env.NEW_TAG }}
  env:
    GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use PAT instead of default token
```

Also, check permissions. By default workflows only run with a read only permission, which could be inhibiting the tag somehow. Try adding

```
permissions:
  contents: write
```
  
To your workflows as well

**Reply by diniguezcabrera** [reply]
Hi @mickeygousset, my first issue was I was missing a `persist-credentials: false` earlier in the code, which apparently caused the auth after that to be ignored. It's now as follows:

```
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
```

With that done, I've managed to get it working as expected using a PAT, with the following:

```
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and Push tag
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run : |
          git checkout main
          git tag ${{ env.NEW_TAG }}
          git push https://x-access-token:${PAT}@github.com/${{ github.repository}}.git ${{ env.NEW_TAG }}
```

However, I'd want this to work using an org app, but that's still failing.
What I've tried for that is:

```
       - name: Generate a token
         id: generate-token
         uses: actions/create-github-app-token@v1
         with:
             app-id: ${{ vars.APP_ID }}
             private_key: ${{ secrets.APP_PRIVATE_KEY }}

       - name: Create new tag
         env:
           GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
         run: |
           git checkout main
           git tag ${{ env.NEW_TAG }}
           git push origin ${{ env.NEW_TAG }}
```

What could be failing when using the app for auth?

**Reply by mickeygousset** [reply]
My first suggestions to check:

- Verify permissions on the app. I'd give it everything just for testing

**Reply by diniguezcabrera** [reply]
Changing permissions didn't work.
I'm leaving it to use a PAT for now, but really think app auth should be a lot easier than what I'm experiencing.
It's seems a lot of the times the answer is "oh, just use a PAT", and that doesn't sit right with me.

> by default the GITHUB_TOKEN doesn't allow for triggering other workflows

IMO this should also be reviewed and at least be a lot more clear in the action docs.

**Reply by mickeygousset** [reply]
A GitHub App is the best practice way.  

I get WHY we don't allow the GITHUB_TOKEN to trigger other workflows. Simplest reason is you can put yourself in an infinite loop.

I'm going to try and recreate what you are doing and see if I can figure out what is going on. Might be later today before I get back to you.

**Reply by mickeygousset** [reply]
@diniguezcabrera I have a working example with a GitHub App here:  https://github.com/devopselvis/actions-trigger-on-new-tag

I used a different action than you to generate the token, but otherwise I seem to be doing exactly what you are doing.

A couple of more things to check:

The app needs to be installed in your organization. So go to your org and Settings |  GitHub Apps and you should see it there. Make sure it has access to your repository. 

![image](https://github.com/user-attachments/assets/47967393-58e5-4243-ae45-f760db2e70fb)

Go check out my code in the repo above and see if you see anything that helps you. 

I'll also record a video of what I am doing for https://youtube.com/mickeygousset, but I may not get that done before the weekend is over.

**Reply by diniguezcabrera** [reply]
hi @mickeygousset thanks for taking the time to look into this, I really appreciate it!
I've checked out your repo and video, and it doesn't look too far from what I got, so it should be easy enough to test, I'll update when I've done so 💪

**Comment by mickeygousset** [comment]
@diniguezcabrera I created a [video](https://youtu.be/g0KtieCywX4) of what I did over at YouTube if that helps.

![GitHub Actions - Trigger on a new tag](https://github.com/user-attachments/assets/4470be9f-d5ac-493b-8288-f56f81edced9)

**Reply by maartenbosteels** [reply]
It does not seem to work.
See https://github.com/maartenbosteels/github-actions-trigger-on-new-tag/blob/main/.github/workflows/build.yml

Not exactly what you did but pretty close: my first workflow runs for every push instead of one PR merge.
Authentication with the GitHub App seems tow work fine:
```
Run tibdex/github-app-token@v2.1.0
  with:
    app_id: ***
    private_key: ***
  
    github_api_url: https://api.github.com/
    installation_retrieval_mode: repository
    installation_retrieval_payload: maartenbosteels/github-actions-trigger-on-new-tag
    revoke: true
Token created successfully
```
But my second workflow is not triggered. Any ideas?

I also wonder why this approach would prevent you from shooting yourself in the foot, which you claim is the reason it does not work with the 'plain' GITHUB_TOKEN ?
