### DISCUSSION TITLE
Discussions API: Allow specifying label in createDiscussion and updateDiscussion mutations

### DISCUSSION THREAD

**Discussion by laymonage** [community/community#15431] [Discussions]
The `createDiscussion` and `updateDiscussion` mutations do not support an input field for `label`:

https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions#creatediscussion

This means that the API can't be used to set labels on a new/existing discussion. It'd be nice to be able to specify a label, just like on the Issues API.

**Comment by AustenLamacraft** [comment]
In the same way, it would be great to be able to specify a label in a query to get only discussions with that label.

**Reply by laymonage** [reply]
That already works, so the mutations are the only missing pieces of the puzzle 🙂 

Try the following query on the [GraphQL Explorer](https://docs.github.com/en/graphql/overview/explorer):

```graphql
{
  search(
    type: DISCUSSION
    query: "repo:github/feedback label:\"🚀 shipped\" category:\"Discussions Feedback\""
    first: 20
  ) {
    nodes {
      ... on Discussion {
        title
      }
    }
  }
}
```

**Reply by AustenLamacraft** [reply]
Thanks!

**Comment by bsiever** [comment]
I was trying to add/update discussion labels when I found this post/issue.  For others who haven't already realized it, it is possible to add labels to a discussion via `addLabelsToLabelable` (Of course, it would be nice to also be able to do this in create/update).  An example GraphiQL:
```
mutation {
  addLabelsToLabelable(
    input:{
      labelableId: ID_OF_DISCUSSION,
      labelIds: [ID_OF_A_LABEL]
    }
  ) {
    clientMutationId
  } 
}
```

**Comment by Bestra** [comment]
I've written up an issue in our backlog for this, thanks for reporting it and for finding somewhat of a workaround!

**Reply by LukeSavefrogs** [reply]
Any news? I cannot find anything about `addLabelsToLabelable` in the Discussions GraphQL API documentation

**Reply by bsiever** [reply]
@LukeSavefrogs `addLabelsToLabelable` isn't specific to discussions.  Labels are used in [Discussions, Issues, and Pull Requests](https://docs.github.com/en/graphql/reference/interfaces#labelable).  Here are the docs on `addLabelsToLabelable`: https://docs.github.com/en/graphql/reference/mutations#addlabelstolabelable

**Reply by LukeSavefrogs** [reply]
@bsiever TY for the info!

Didn't find the GraphQL documentation while searching, my bad

**Comment by toyamarinyon** [comment]
Hi there,

If anyone want to create a discussion with labels on GitHub action, it will be able to use the following code! 


```yml
name: Create a discussion with labels
on:
  workflow_dispatch:
jobs:
  create_discussion_with_label:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Create a discussion
        id: create_discussion
        uses: octokit/graphql-action@v2.x
        with:
          title: "Sample Discussion!!!"
          body: |-
            Hello, this is a sample discussion created by GitHub Actions.
          query: |
            mutation($title:String!, $body:String!) {
              createDiscussion(input: {repositoryId: "[YOUR_REPOSITORY_ID]", categoryId: "[YOUR_CATEGORY_ID]", title: $title, body: $body}) {
                discussion {
                  id
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/graphql-action@v2.x
        id: add_label
        with:
          query: |
            mutation {
              addLabelsToLabelable(
                input:{
                  labelableId: "${{ fromJSON(steps.create_discussion.outputs.data).createDiscussion.discussion.id }}"
                  labelIds: ["[YOUR_LABEL_ID]]"]
                }
              ) {
                clientMutationId
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
