### DISCUSSION TITLE
Bug Report: Concurrency Settings Not Queuing Workflows as Expected

### DISCUSSION THREAD

**Discussion by Chandra03ram** [community/community#154450] [Actions]
### Select Topic Area

Bug

### Body

I am experiencing an issue with GitHub Actions where the concurrency settings are not queuing workflows as expected. Despite configuring the concurrency key to ensure FIFO (First-In-First-Out) execution, subsequent workflow runs are being canceled instead of queued.

Workflow Configuration:
```yaml
name: build_metrics
run-name: ${{ github.actor }} - ${{ github.ref_name }} - Workflow Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: 'workflow_pool_cloud_20.04_16core'
    concurrency:
      group: build_metrics-${{ github.ref }}
      cancel-in-progress: false
```

**Issue**: When manually triggering multiple workflow runs:
The first workflow run starts executing as expected.
All subsequent workflow runs are canceled, except for the last one, which remains in the queue.

**Expected Behavior:** I expect the workflows to be queued and executed in the order they were triggered (FIFO), with only one workflow running at a time.

**Runner Details:**
OS: Ubuntu 24.04
Specs: 16 cores, 64 GB RAM, 600 GB SSD

**Steps Taken:**
Configured the concurrency key at the job level with cancel-in-progress: false.
Reviewed workflow logs for errors.
Verified resource utilization on the runner.

**Additional Information:**
There are no apparent resource constraints on the runner.
The issue persists despite the configuration changes.

**Request:** I would appreciate any insights or solutions to ensure that workflows are queued and executed in a FIFO order as intended.
