### DISCUSSION TITLE
💥 Workflow Triggered by `pull_request` Event Use the Merged Workflow Pipeline

### DISCUSSION THREAD

**Discussion by keunhyung-chung** [community/community#154572] [Actions]
### Select Topic Area

Bug

### Body

I have made an example repository to describe the issue: https://github.com/keunhyung-chung/temp-repository-to-test-github-actions-2025-03-21

---

In the `main` branch, the [workflow](https://github.com/keunhyung-chung/temp-repository-to-test-github-actions-2025-03-21/blob/f31745c7a57258bb3d9576649ab30ba6b6b609ff/.github/workflows/blank.yml#L17-L39) is like below:

```yaml
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Step A
        run: echo A

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
```

---

In the `feature/c` branch, the [workflow](https://github.com/keunhyung-chung/temp-repository-to-test-github-actions-2025-03-21/blob/60c006815fdec2e38c25768e1dfbb9504ebf38af/.github/workflows/blank.yml#L17-L39) is like below:

```yaml
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Step C
        run: echo C
```

As you can see, **there is no `Step A` in the `feature/c`.**

---

However, in [the workflow run of the pull request from `feature/c` to `main`](https://github.com/keunhyung-chung/temp-repository-to-test-github-actions-2025-03-21/actions/runs/13987506765/job/39163921071?pr=2), **there are both `Step A` and `Step C`**:

![image](https://github.com/user-attachments/assets/1246bb19-85c5-49dd-baa5-6186a0d38ea6)

My expectation is that the workflow run of the `feature/c` pull request should use the workflow pipeline of `feature/c`, 
but in fact, it also uses the one of the base branch (`main`). It seems that GitHub uses the **merged** one.

---

Here is the status of git log:

```sh
$ git log --graph main feature/c --oneline
* 60c0068 (HEAD -> feature/c, origin/feature/c) Step C
| * f31745c (origin/main, origin/HEAD, main) Update blank.yml
|/  
* 702851f Create blank.yml
* bccda7d Initial commit
```

[f31745c](https://github.com/keunhyung-chung/temp-repository-to-test-github-actions-2025-03-21/commit/f31745c7a57258bb3d9576649ab30ba6b6b609ff) adds `Step A`
[60c0068](https://github.com/keunhyung-chung/temp-repository-to-test-github-actions-2025-03-21/commit/60c006815fdec2e38c25768e1dfbb9504ebf38af) adds `Step C`
