### DISCUSSION TITLE
`workflow_run` action not being triggered

### DISCUSSION THREAD

**Discussion by pezholio** [community/community#154573] [Actions]
### Select Topic Area

Question

### Body

Hi,

I have a workflow in the `main` branch of my repo that should be getting triggered by three actions with the names `CodeQL Analysis`, `Linting` and `Unit tests`, which are triggered by the `pull_request` event. I have the trigger set up like so:

```yaml
on:
  workflow_run:
    workflows: [CodeQL Analysis, Linting, Unit tests]
    types:
      - completed
```

But the action steadfastly refuses to run when a pull request gets opened. What am I doing wrong?

Here's my repo for reference:

https://github.com/dxw/mail-notify

**Comment by pezholio** [comment]
Ignore me, I had a step referenced that was no longer present in my workflow, so the action was failing silently

**Comment by pezholio** [comment]
Actually, on second thoughts, this is still an issue. I now have my workflow set up with the following trigger:

```
on:
  workflow_run:
    workflows: ["Unit tests"]
    types:
      - completed
```

But it's still steadfastly refusing to run. Again, my repo is here https://github.com/dxw/mail-notify, and I've opened a PR which I _expect_ to trigger the workflow run here https://github.com/dxw/mail-notify/pull/175
