### DISCUSSION TITLE
Email notifications for matrix deploy with deploy approval

### DISCUSSION THREAD

**Discussion by wyardley** [community/community#154509] [Actions]
### Select Topic Area

Question

### Body

I have a deployment that uses matrices to deploy a bunch of separate cloud run jobs. I'm using a matrix so that I can deploy all the jobs in parallel, as well as avoid having the pipeline fail hard if deploying one job fails.

Simplified version of my config:
```yaml
  deploy-prod: 
    uses: ./.github/workflows/deploy_workflow.yml ## not so important what happens in here
    needs: build-deploy
    strategy:
      matrix:
        job:
          - job1
          - job2
    with:
      environment: prod
      image: ${{ needs.build-deploy.outputs.tag }}
      job: ${{ matrix.job }}
```

As mentioned in another thread, one problem I'm having is that this kind of breaks the idea of deploy "success" (i.e., only the last job shows up as a successful deploy when I'm deploying 2, or 5, or whatever, jobs in parallel. But additionally, with deployment approval required for the target environment ("prod" in the example above), I now get N GitHub notifications when the deploy requires approval (even though there's only one checkbox I have to apply).

Is there a way to end up with only one notification with a setup like this? Bonus if it also gets me 1 successful "deploy".

Note: the actual data structure I'm passing into the deploy workflow is marginally more complicated than in the above example. But I guess in theory, I could pass the data structure into the deploy workflow and handle the matrix within that reusable component?)
