### DISCUSSION TITLE
NPM Publish Error 403: Cannot Publish Existing Version Despite Incrementing

### DISCUSSION THREAD

**Discussion by teneplaysofficial** [community/community#154773] [Actions]
### Select Topic Area

Question

### Body

I'm encountering an error while publishing my package to NPM. I receive a **403 error** stating that I **cannot publish an already existing version**, even though this is my first time publishing.  

For example:  
- The initial version in my package is **0.0.1**, but NPM shows **0.0.0**.  
- After the next workflow run, the version increments to **0.0.2**, but NPM already has **0.0.1**.  

Note: I have no dependencies, and the project is a CDN for images.

Can anyone help me understand what's going wrong?

```
npm error code E403
npm error 403 403 Forbidden - PUT https://registry.npmjs.org/github-markdown-readme-cdn - You cannot publish over the previously published versions: 0.0.11.
npm error 403 In most cases, you or one of your dependencies are requesting
npm error 403 a package version that is forbidden by your security policy, or
npm error 403 on a server you do not have access to.
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-03-22T17_59_17_074Z-debug-0.log
npm error code 1
npm error path /home/runner/work/github-markdown-readme-cdn/github-markdown-readme-cdn
npm error command failed
npm error command sh -c npm publish --access public
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-03-22T17_59_14_421Z-debug-0.log
Skipping publish: version exists
```

```yml
name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Fetch all tags
        run: git fetch --tags

      - name: Bump patch version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          npm version patch -m "chore(release): bump version to %s"
          git pull --rebase origin main
          git push origin main --tags

  publish-npm:
    needs: version-bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Verify package.json version before publishing
        run: cat package.json | grep version

      - name: Publish to npm
        run: |
          npm publish --access public || echo "Skipping publish: version exists"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify published version on npm
        run: npm info $(jq -r .name package.json) version
```
