### DISCUSSION TITLE
Pre-populate issue forms HTTP supplied values

### DISCUSSION THREAD

**Discussion by bbappserver** [community/community#15477] [Projects and Issues]
A lot of boilerplate stuff like what platform, and what build of the product could just be filled programatically into an issue form.  If a program has a menu to open a bug report it could just submit the requisite information to Github saving users a fair amount of typing.

In the YAML, just have a key for the data binding and then accept GET parameters.  That way if a program opens a URL in a web browser, the key details can be pre-filled.

**Comment by Yassin40** [comment]
Hllo

**Comment by corubba** [comment]
You can already do this. You need to assign ids to the elements, and then you can use those as query parameter names to pass values.

Take this issue form template:
```yaml
---
name: Example
description: Just an example
body:
- id: field1
  type: textarea
  attributes:
    label: Just some input field
```

You can then call https://github.com/xxx/yyy/issues/new?template=my_template.yaml&field1=some+pre-filled+value to open the new issue form with that element pre-populated.
