### DISCUSSION TITLE
Using dependabot to upgrade gomod in go version 1.20

### DISCUSSION THREAD

**Discussion by futugyou** [community/community#154822] [Actions]
### Select Topic Area

Question

### Body

My go.mod file has go 1.20 written in it
```
module golang-project

go 1.20
```

Then I configured dependabot.yml to do the upgrade
```
version: 2
updates:
  - package-ecosystem: "gomod"
    schedule:
      interval: "daily"
```

It was working fine in the past, but started to have problems about two weeks ago.
Toolchain directive began to appear in pull requests submitted by dependabot, like this..
```
module golang-project

go 1.20
toolchain go1.24.1
```
When executing 'go mod tidy', an error 'unknown directive: toolchain' is reported.
I think that knowing that go 1.20 is the default, the toolchain directive should not appear.
