### DISCUSSION TITLE
Why doesn't the Launch Workflow button show?

### DISCUSSION THREAD

**Discussion by Rod-at-DOH** [community/community#154876] [Actions] [answered]
### Select Topic Area

Question

### Body

I have this at the beginning of a .yml file:

```yaml
name: Test Deployment

on:
  workflow_dispatch: #manual
```

After committing it to repo, I expected the launch workflow button to show in the repo's Action, but it didn't show. Previously, I even had  the branch it is in, mentioned in the `on:`, but it still didn't show up in the repo's Action. Why? What am I doing wrong?
