### DISCUSSION TITLE
[Projects Beta] Checkbox checked abnormally

### DISCUSSION THREAD

**Discussion by taozhiyu** [community/community#15497] [Projects and Issues]
Using yml to build a form is very useful for collecting, I tried to use the official documentation and it worked.

But when I translate the options into Chinese, the checked state of the checkboxes causes problems, as examples below

```
  - type: checkboxes
    id: terms
    attributes:
      label: 免责申明
      description: 继续提交则表示您已阅读并同意遵守[免责申明](link_here)
      options:
        - label: 我已阅读并同意遵守上述免责申明
          required: true
```

I added the REQUIRED attribute to require mandatory selection, which also refers to the official example.

But when I try to submit it, it is not selected

![image](https://user-images.githubusercontent.com/49258735/164981182-39d50e21-8339-46a8-b8f8-93a39c30325f.png)

After several attempts, I found that adding any number or letter to any position in the options works fine

| ![](https://user-images.githubusercontent.com/49258735/164981353-e1f853da-e7e2-436f-95ac-b7e1a67fe624.png) | ![](https://user-images.githubusercontent.com/49258735/164981380-376ebfc6-444a-4d3b-884f-a51cabb8ced5.png) | ![image](https://user-images.githubusercontent.com/49258735/164981602-4d3f6ed0-23bd-41f9-bde2-5b9ff2c5711c.png) | ![image](https://user-images.githubusercontent.com/49258735/164981627-14e8a455-f92c-4c6b-b2c9-27339edae636.png) |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |

Although I don't know the reason, I think it should be a bug and I hope it will be fixed soon.
