### DISCUSSION TITLE
Post job cleanup. Error: Path Validation Error

### DISCUSSION THREAD

**Discussion by vinitparekh17** [community/community#154935] [Actions]
### Select Topic Area

Question

### Body

code:
```yaml
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: 'frontend/pnpm-lock.yaml'
        ```
 issue: 
Post job cleanup.
Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.

Although frontend dir exists in my repo with lock file I am facing this issue
