### DISCUSSION TITLE
Wanting to have 2 pages using the same repo but 2 different branches,

### DISCUSSION THREAD

**Discussion by uhCurious** [community/community#154992] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

Does anyone know if the title of this is possible?
Co-pilot seemed to think it was using action to deploy but then I was plagued with deploy errors and could not get it to work and it sent me in a loop.

I want to push to Dev which can be viewable at dev.domain.com to then if I am happy with results pull request to domain.com

**Comment by dd080944912** [comment]
> ### Select Topic Area
> 
> Question
> 
> ### Body
> 
> Does anyone know if the title of this is possible?
> 
> Co-pilot seemed to think it was using action to deploy but then I was plagued with deploy errors and could not get it to work and it sent me in a loop.
> 
> 
> 
> I want to push to Dev which can be viewable at dev.domain.com to then if I am happy with results pull request to domain.com

**Comment by jasonbra1n** [comment]
- GitHub only allows one Pages site per repo, so we'll need to use a different approach

## Alternative Approach for Dev Site

Since GitHub Pages only supports one site per repo directly, here's how to set up the dev environment:

### Option 1: Use GitHub Actions to Deploy to Separate Location

1. Create a `.github/workflows/deploy-dev.yml` file:

```yaml
name: Deploy Dev Site

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to dev subdomain
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # or your build folder
          destination_dir: dev
          publish_branch: main  # this will go to a subfolder on main
```

2. Then set up your DNS to point:
   - `site.com` to `username.github.io/repo`
   - `dev.site.com` to `username.github.io/repo/dev`

### Option 2: Use Two Different Repos

1. Keep your main site in `repo` (deployed to site.com)
2. Create `repo-dev` for the dev site (deployed to dev.site.com)

## Merging Dev to Main

When you're ready to promote your dev branch to production:

```bash
git checkout main
git merge dev
git push origin main
```

## DNS Configuration

In your DNS provider:
- Create an A record for `site.com` pointing to GitHub's IPs
- Create a CNAME record for `dev.site.com` pointing to `username.github.io`

## GitHub Pages Configuration

For the main site:
- Settings → Pages → Source: `main` branch

For the dev site (if using separate repo):
- Settings → Pages → Source: `main` branch of the dev repo

Remember that changes to GitHub Pages sites may take a few minutes to propagate.
