### DISCUSSION TITLE
`name: Package ${{ matrix.target }}` displays `format('Package {0}', matrix.target)` when job skipped

### DISCUSSION THREAD

**Discussion by JounQin** [community/community#155008] [Actions]
### Select Topic Area

Product Feedback

### Body

```yaml
build:
  needs: check
  if: needs.check.outputs.version_changed == 'true'
  name: Package ${{ matrix.target }}
```

https://github.com/unrs/unrs-resolver/pull/34

<img width="784" alt="image" src="https://github.com/user-attachments/assets/aed2cdb0-241d-4444-a440-c356f7da619e" />

I'd expect to display `Package` instead.
