### DISCUSSION TITLE
Test Workflow: How may I use pygobject, which requires the package cairo to be installed on the system to be tested?

### DISCUSSION THREAD

**Discussion by RQuarx** [community/community#155025] [Actions]
### Select Topic Area

Question

### Body

Having this files:
```yaml
name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
```
```txt
pygobject
dbus-python
psutil
setuptools
wheel
```
would trigger an error once pygobject which are inside requirements.txt, is installed. The error links to meson not being able to found cairo on the system. How may i resolve this issue?
