### DISCUSSION TITLE
Unexpected Workflow Triggering with paths in Pull Requests

### DISCUSSION THREAD

**Discussion by satokom** [community/community#155107] [Actions]
### Select Topic Area

Question

## Context
I have a GitHub Actions workflow configured as follows:

```
on:
  pull_request:
    paths:
      - ".github/servers.yaml"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-server-connectivity:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

``` 

This workflow is intended to run only when `.github/servers.yaml` is modified in a pull request.

## Issue
* The workflow sometimes triggers on PRs that do not modify `.github/servers.yaml.`
* The workflow also triggers when merging master into a feature branch or when synchronizing with master.
* I suspect that paths: might be matching files that were part of earlier commits in the PR but not necessarily in the final diff.

## Questions
1. Does `paths:` consider all commits in a PR, even if the final diff does not contain changes to the specified file?
2. Can a merge commit trigger the workflow even if `.github/servers.yaml` has no actual changes?
3. If a file is modified in an early commit but later reverted in the PR, does paths: still detect it?
4. Is there a reliable way to prevent the workflow from triggering if `.github/servers.yaml` is not part of the PR’s final changes?

## Expected Behavior
The workflow should only trigger when `.github/servers.yaml` is modified within the PR.
It should not trigger due to merging master or other unrelated changes.
