### DISCUSSION TITLE
No push to protected branch on certain days

### DISCUSSION THREAD

**Discussion by ernestoA92** [community/community#155134] [Repositories]
### Select Topic Area

Question

### Body

Almost all the teams I have worked on have a rule of not pushing to main/master on Fridays. But there are always violations and many bugs happening on weekends.

It would be a life changing feature if Github allows to set a rule for the protected branches so it can't be pushed to those branches on a certain day or days... of course bypassed with admin rights if necessary.

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by patrick-knight** [comment]
This workflow should get you close to what you are looking for while using rulesets. 

1. Have or create a ruleset with the rule "Restrict updates", which only allow users with bypass on a ruleset to update the branches in the ruleset, no one else would have access.
2. Create a personal access token with these permissions:
    - Read access to metadata
    -  Read and Write access to administration and repository custom properties
3. Create a actions repository secret called `PAT` and save that secret.
4. Get the `<ruleset-id>` for the repo ruleset you want to schedule changes on. 
5. Create blockthething.yml in your `.github/workflow directory` with the code below.
6. Lock whatever branches are in that ruleset from 12am UTC Friday - 12am UTC Saturday every week.


```
name: Restrict Updates on BlockTheThing

on:
  schedule:
    - cron: "0 0 * * 5" # Runs every Friday at 12am UTC
    - cron: "0 0 * * 6" # Runs every Saturday at 12am UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  enable-restrict-updates:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * 5'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: List Existing Rulesets
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh api /repos/${{ github.repository }}/rulesets/<ruleset-id> > ruleset.json

      - name: Enable Restrict Updates on BlockTheThing
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
         jq '.rules += [{"type": "update"}]' ruleset.json > updated_ruleset.json
         gh api --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/rulesets/<ruleset-id> \
            --input updated_ruleset.json

  disable-restrict-updates:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * 5'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: List Existing Rulesets
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh api /repos/${{ github.repository }}/rulesets/<ruleset-id> > ruleset.json

      - name: Disable Restrict Updates on BlockTheThing
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          jq '.rules |= map(select(.type != "update"))' ruleset.json > updated_ruleset.json
          gh api --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/rulesets/<ruleset-id> \
            --input updated_ruleset.json
```
