### DISCUSSION TITLE
Publishing to GPR is throwing npm ADDUSER error

### DISCUSSION THREAD

**Discussion by epicman25** [community/community#155169] [Actions]
Hi everyone,

I'm having trouble publishing a package to the GitHub Package Registry and I'm getting an `ENEEDAUTH` error. I've followed several tutorials and guides, but I'm still stuck. Any help would be greatly appreciated!

I'm trying to publish a Node.js package to the GitHub Package Registry under my username `epicman25`. I'm using a GitHub Actions workflow to automate the process and triggering it manually.

Here's my GitHub Actions workflow file (`.github/workflows/publish.yml`):

```yaml
name: Publish to GitHub Package Registry

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/ 
          scope: 'epicman25'

      - name: Install Dependencies
        run: npm ci

      - name: Configure npm for GitHub Package Registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GITHUB_SECRET }}" > .npmrc

      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_SECRET }}
```

I have generated a PAT with all permissions enabled and saved it in repository secrets under 'NPM_GITHUB_SECRET'.

The error I am getting:

```yaml
npm error code ENEEDAUTH
npm error need auth This command requires you to be logged in to https://registry.npmjs.org/
npm error need auth You need to authorize this machine using `npm adduser`
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-03-27T17_38_36_019Z-debug-0.log
```
