### DISCUSSION TITLE
new expression to transform json to multiline string

### DISCUSSION THREAD

**Discussion by y-nk** [community/community#155144] [Actions]
### Select Topic Area

Product Feedback

### Body

Since it's impossible to produce array, and we need to pass multiline strings in order to pass arrays, it'd be quite handy to have a tool to transform json objects into multiline string.

```ts
function toMultilineString(json: Record<string, string) {
  return Object.entries(json).map(pair => pair.join('=')).join('\n')
}
```

so that we can do things like:

```yaml
with:
  someMultilineParam: |
    ${{ toMultilineString(steps.fromBefore.outputs.aJson) }}
```

without having to reinvent the wheel. thank you.
