### DISCUSSION TITLE
Trigger GHA workflow via GitHub Organization Webhook?

### DISCUSSION THREAD

**Discussion by ImanSM** [community/community#155110] [Actions]
### Select Topic Area

Question

### Body

Hello - Can anyone share how to trigger a GHA workflow via [GitHub Organization Webhook](https://docs.github.com/en/rest/orgs/webhooks)?

I am trying to trigger a workflow every time a repository is created. However, I am getting a `403` error. 

What I did:

1. Created workflow with `repository_dispatch` trigger. `Event_type: created` since the webhook sends a payload with  `"action": "created"`
```yaml
on:
  repository_dispatch:
    types: [created]
  workflow_dispatch:
```
2. Created organization webhook with payload url: `https://api.github.com/repos/[owner]/[repo-name]/dispatches`
