### DISCUSSION TITLE
GitHub Action to simply build a project with dot net

### DISCUSSION THREAD

**Discussion by alfredoball-metc** [community/community#155167] [Actions]
### Select Topic Area

Question

### Body

I'm trying to run this build for a dot net project but the GitHub runner says it can't find the project.

- name: Setup Dotnet
  uses: actions/setup-dotnet@v4
- run: dotnet build "${{ github.workspace }}/MY PROJECT"
    
 Is this the right way to do it?

**Comment by rayan-albouni** [comment]
right, however, you need to checkout the code first, and configure the dotnet version to install, also inside the shell script you need to use `$GITHUB_WORKSPACE`, here is an example:
```
steps:
- uses: actions/checkout@v4
- name: Setup dotnet
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: 6.x
- run: dotnet build "$GITHUB_WORKSPACE/MY PROJECT"
```
