### DISCUSSION TITLE
Can I use a matrix parameter to call a callable workflow?

### DISCUSSION THREAD

**Discussion by stuller-adriahuertascaparros** [community/community#155230] [Actions] [answered]
### Select Topic Area

Question

### Body

I've been trying to simplificate an action that have several steps (related with testing) that have the same structure but I'm getting an error when I try to use a matrix value in the uses parameter (Unrecognized named-value: 'matrix'). Why next example doesn't work? Is there another way to do that?
```
name: Proof of concept

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: read

jobs:
  job1:
    uses: ./.github/workflows/some-action.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix:
        test-suite: 
          - { label: "label1", action-path: "./.github/workflows/action1.yml" }
          - { label: "label2", action-path: "./.github/workflows/action2.yml" }
          - ...
          - ...
    steps:
      - name: Whatever
        if: "some condition with label"
        uses: ${{ matrix.test-suite.action-path }}
```
