### DISCUSSION TITLE
input are always empty in reusable workflows

### DISCUSSION THREAD

**Discussion by valentijnscholten** [community/community#155395] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi,

I have something very simple to achieve. Something which I have been doing for over 5 years without problems. But it no longer seems to be working.

I have a workflow that I am calling from another workflow:

```
name: "Release-Nightly: Core"

env:
  ...

on:
  workflow_call:
    inputs:
        branch-to-build:
          # do not use branch as name as it will be master in a scheduled run
          type: string
          description: 'Branch to checkout, build and publish'
          required: false
          default: 'dev'
        tag-to-apply:
          type: string
          description: 'Tag to apply to the images'
          required: false
          default: 'nightly-dev'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.inputs.branch-to-build }}

      - name: Configure git
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"

      - name: Create new tag ${{ github.event.inputs.tag-to-apply }}
        run: |
          git tag -f -a ${{ github.event.inputs.tag-to-apply }} -m "[bot] release ${{ github.event.inputs.tag-to-apply }}"
          git push origin ${{ github.event.inputs.tag-to-apply }} -f

...
```

Calling workflow:

```
name: "Release-Nightly: Build & Push DEV"

on:
  schedule:
    # every day at 5:00 UTC
    # in this case inputs are all null/empty, hence the default values are used below
    - cron: "45 * * * *"
  workflow_dispatch:

jobs:
  nightly-build-dev:
    uses: ./.github/workflows/release-x-nightly.yml
    with:
        branch-to-build: 'dev'
        tag-to-apply: 'nightly-dev'
    secrets: inherit
```

This fails because ${{ github.event.inputs.tag-to-apply }} is always empty despite it being passed from the calling workflow AND having a default. I can't see what I am doing wrong as I'm doing similar things in the same repo and workflows for a long time and they work.

Same problem when using `inputs.tag-to-apply`.

Example runs: 
- https://github.com/valentijnscholten/django-DefectDojo/actions/runs/14159439073
- https://github.com/valentijnscholten/django-DefectDojo/actions/runs/14159556637/job/39663171272

Valentijn
