### DISCUSSION TITLE
Mentions in a job summary doesn't notify user

### DISCUSSION THREAD

**Discussion by laja-0-jyskebank-dk** [community/community#155443] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Bug

### Body

Hi

I have implemented a typescript action which writes to the job summary.
I want to notify the workflow triggering actorin some particular cases and I would like to use @mentions for this

In the job summary I can see the mention correctly, but the user doesn't receive email notification even all notification settings are enabled.

While troubleshooting I have made a workflow as well that simply writes to $GITHUB_STEP_SUMMARY env var, also this does a proper mention, but no notification email is sent and notification is not visible in https://github.com/notifications

``` yaml
name: Summary testing

on:
  workflow_dispatch:

jobs:
  do-summary:
    runs-on: ubuntu-latest
    steps:
    - name: Generate list using Markdown
      run: |
        echo "@${{ github.actor }} did you get notified" >> $GITHUB_STEP_SUMMARY # this is a blank line   
```

![mention_example](https://github.com/user-attachments/assets/1f5df0de-279e-4a5a-9d1f-b5faf63cd97c)
