### DISCUSSION TITLE
Github Action doesn't checkout submodule of action repository

### DISCUSSION THREAD

**Discussion by JohannesK71083** [community/community#155448] [Actions]
### Select Topic Area

Bug

### Body

[Stackoverflow question](https://stackoverflow.com/q/79529720/18763534)

On Github actions, submodules of the **action repository** aren't checkout out, instead only an empty folder remains and it's impossible to load the submodules manually, because github action deletes/doesn't create the .git folder (so it only checks out the files and not the repo). I also tried publishing it to Github Marketplace to see if that would fit it, but it didn't. (After that I deleted it again from the marketplace.) \
How can I fix that?:

File Setup:
```
main repo:
|   action.yml
\--- submodule

submodule repo:
|   test.txt
```

main_repo/action.yml:
```
name: "Submodule Test"
description: ""

runs:
  using: "composite"
  steps:
    - name: execute test
      shell: cmd
      run: |
        tree /F /A ${{ github.action_path }}
```

.../.github/workflows/test.yml
```
name: Submodule Test
on:
  workflow_dispatch

jobs:
  Pyinstaller:
    runs-on: windows-latest  # same problem on ubuntu-latest
    steps:
      - name: execute pyinstaller_action
        uses: "JohannesK71083/actions_submodule_main@main"
```

Github actions output:
```
D:\A\_ACTIONS\JOHANNESK71083\ACTIONS_SUBMODULE_MAIN\MAIN
|   .gitmodules
|   action.yml
|   
\---submodule
```

Links to the repos: \
[main repo](https://github.com/JohannesK71083/actions_submodule_main) \
[submodule repo](https://github.com/JohannesK71083/actions_submodle_sub) \
[action run logs](https://github.com/JohannesK71083/actions_submodule_test/actions/runs/14023162247/job/39257741836)
