### DISCUSSION TITLE
Waiting for a runner to pick up this job...is stuck for over 3 hours now

### DISCUSSION THREAD

**Discussion by ebmifa** [community/community#155542] [Actions]
### Select Topic Area

General

### Body

All of our workflows have been stuck waiting to get `ubuntu-ghcloud` runner for over 3 hours now, and status.github.com shows that everything is up.

**Comment by chess-king-dot** [comment]
Hey, yeah — we saw the same thing earlier today. It seems like the `ubuntu-ghcloud` runners are **super backed up** right now, even though the status page says all systems are green.

Couple of things you can try while waiting:

- If you're not tied to `ubuntu-ghcloud`, try switching to a regular `ubuntu-latest` runner temporarily — those seem to be working fine for us.
  
  ```yaml
  runs-on: ubuntu-latest
  ```

- Also, check if any org-level runner limits or concurrency caps are being hit — we once had a similar delay caused by an idle self-hosted runner that was misconfigured.

Let me know if switching runners helps!

**Comment by ebmifa** [comment]
Unfortunately, the `ubuntu-latest` runners are just not big enough and too slow for us for all the Rust builds.

**Comment by chess-king-dot** [comment]
Ah, I totally get that — Rust builds can be pretty resource-heavy, and the `ubuntu-latest` runners just don't cut it for performance at that scale.

If you’re stuck waiting for the `ubuntu-ghcloud` runners, one option might be to check if you can scale up your **self-hosted runners** to handle the load. I know it adds some management overhead, but it could give you more control over performance and avoid long wait times.

Also, have you tried using **caching** to speed up the Rust builds? GitHub Actions allows caching dependencies, which can save a lot of time in between runs. Here’s an example if you haven’t set it up yet:

```yaml
- name: Cache Rust build
  uses: actions/cache@v2
  with:
    path: |
      ~/.cargo/registry
      ~/.cargo/git
    key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
    restore-keys: |
      ${{ runner.os }}-rust-
```

That might help with reducing build time if you haven't already tried it. Hopefully, GitHub works through the queue backlog soon, though.

Let me know if I can help further!
