### DISCUSSION TITLE
Getting Started with GitHub Actions – Automate Your Workflow

### DISCUSSION THREAD

**Discussion by saurabhgunturkar** [community/community#155514] [Actions]
<img src="https://github.com/user-attachments/assets/f1b12705-865a-4198-abd3-93bcf76a77b8" width=80% height="300px"/>

### Introduction
GitHub Actions is a powerful automation tool that **reduces development time** by streamlining processes from integration to deployment. It enables teams **to build, test, and deploy applications quickly**, while also automating tasks such as adding labels to pull requests and managing stale issues.

**Q. What are GitHub Actions?**

1. Packaged scripts designed to **automate tasks** in a GitHub-based development workflow.
2. written in **.yml** format.
3. Accessible via **GitHub > Repo > Actions > New Workflow—choose a workflow** to meet your deployment needs and configure it.
4. Additional action codes can be purchased on **GitHub Marketplace**.
5. Developers can ### write custom actions and publish them to the marketplace.
6. Always **verify an action** before using it to ensure security.
7. Code for actions is stored in the **.github/workflows** directory.
---
### Core Components of GitHub Actions
**1. Workflows**
A workflow is an automated process within a repository. It must include **at least one job**, and can be triggered by different **events/trigger** such as pushes, pull requests, or scheduled executions.
**2. Jobs**
- A job is a section of a workflow that runs on a specific **runner** (GitHub-hosted or self-hosted).
- Jobs can execute on a machine or within a container.
- The environment is specified using the **runs-on** attribute (e.g., runs-on:ubuntu latest)
**3. Steps**
- A step is an individual action within a job.
- Steps can execute commands or call other actions.e.g
  ``` 
      name: Checkout Repository
      uses: actions/checkout@v1
  ```
**4. Actions**
- Standalone commands executed within a workflow.
- Reference either custom or community actions
- Can also run shell commands
---
### GitHub Actions Workflow Example (Actions Anatomy)
```
name: Workflow Example
#event/trigger (on every push, this workflow runs)
on: 
  push 	# The workflow triggers when changes are pushed to the repository.

#Jobs for workflow
jobs:
  #Define the job
  build:	
	#Specify Runner OS
    runs-on: ubuntu-latest
	
    steps:
	 # Fetches the repository code for further processing
      - name: Checkout Repository
        uses: actions/checkout@v1
       
	 # Runs the custom action defined in action-a with input parameters
      - name: Execute Custom Action
        uses: ./action-a
        with:
          MY_NAME: "Mona"
```

**Key Takeaways:**
✅ Triggers define when a workflow runs ().
✅ Jobs execute tasks on specified environments ().
✅ Steps reference built-in or custom actions ().
✅ GitHub Marketplace offers verified actions, but always review them before use.
