### DISCUSSION TITLE
Why are my develop branch CI/CD actions being triggered by a PR to merge develop into main?

### DISCUSSION THREAD

**Discussion by kaysond** [community/community#155556] [Actions] [answered]
### Select Topic Area

Question

### Body

I have CI and CD actions set up on pushes to my develop branch. See:
- https://github.com/kaysond/trafficjam/blob/develop/.github/workflows/ci-nightly.yml
- https://github.com/kaysond/trafficjam/blob/master/.github/workflows/build-nightly.yml

For both I'm using
```yaml
on:
  push:
    branches: [ develop ]
```

However for some reason, [this PR](https://github.com/kaysond/trafficjam/pull/29) to merge develop into master is also triggering the workflows, which I don't want. Why is this happening if creating the PR isn't actually touching develop? And how do I stop this?

**Comment by chess-king-dot** [comment, marked as answer]
Hey! 
The reason your workflows are triggering on the PR merge from `develop` to `master` is because of how GitHub handles push events with `on: push` — when you open a PR, it's technically a **push event** to the `master` branch, which triggers the workflow since `develop` is included in the `branches` filter.

To prevent this from triggering your workflows on PRs, you can update your workflow to ignore PRs by using the `pull_request` trigger. You’ll need to modify the event filter to make sure it only triggers on actual pushes to `develop` and not PR merges.

Here’s how you can adjust the workflow:

### Update your `.github/workflows/ci-nightly.yml` and `.github/workflows/build-nightly.yml` files:
```yaml
on:
  push:
    branches:
      - develop
    # Add the below condition to ignore PRs
    # GitHub Actions will now trigger only on direct pushes to `develop`, not PR merges
    # Make sure to add this for both workflows.
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened] # Only trigger on PR activity to `develop`
```

This ensures that your workflow only triggers on pushes to `develop` and avoids firing on PR merges to `master`.

**Reply by kaysond** [reply]
Thanks for the quick answer! 

One question though - if the PR is a push event to master, why does it then trigger the action that doesn't have master in the branch filter?

**Comment by chess-king-dot** [comment]
Great follow-up question!

The reason it still triggers the workflow is due to the way **GitHub Actions evaluates events**. When you open a pull request, GitHub considers it as a **push event** to the target branch (in this case, `master`), but the **source branch** (`develop`) is part of that event as well. 

Even though you have `develop` specified in the `branches` filter, GitHub will still trigger the workflow if the PR causes any changes to `develop` through the merge process. Essentially, GitHub is treating the **merge commit** (even though it's on `master`) as a new event that involves `develop`.

To avoid this, you could also use the **`if` condition** to ensure the job only runs when the push is strictly to `develop`, and not as a result of a PR merge. Here’s an example of how you can refine the trigger further:

### Example:
```yaml
on:
  push:
    branches:
      - develop
    # Ensure job runs only if the commit is to 'develop' directly
    # and not from a PR merge that includes 'master' or other branches.
jobs:
  build:
    if: github.event.head_commit.ref == 'refs/heads/develop'  # Ensure it's a push to 'develop'
    runs-on: ubuntu-latest
    steps:
      # your steps here
```

This additional `if` condition will prevent the workflow from triggering during a PR merge if the commit isn't directly affecting `develop`.

Let me know if this clears it up!
