### DISCUSSION TITLE
Separate `schedule` per dependencies

### DISCUSSION THREAD

**Discussion by radeksimko** [community/community#15562] [Code Security]
All use cases / examples shown in the docs involving [`allow`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) or [`ignore`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) would suggest that it is not possible to have multiple schedules for the same combination of ecosystem/directory/branch.

This is also clear from the error message when I tried submitting the following config.

> The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: lockfile-only
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies"]
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    versioning-strategy: lockfile-only
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    allow:
      - dependency-type: "development"
```

I do understand if the motivation behind this limitation was to prevent multiple jobs for the same ecosystem which all do the same thing, created by accident, but I think the limitation goes a bit too far in limiting some valid use cases.

I do think `schedule` should be considered as another key in the "unique set" (alongside 'package-ecosystem', 'directory', and 'target-branch'). In NPM ecosystem in particular, there are often dev dependencies such as `@types/*` which create a lot of noise due to frequent updates. Generally dev dependencies typically only affect the dev environment and so we'd like to treat them differently from the production ones and set e.g. weekly schedule for them.

Is there a reason this is not possible today?
