### DISCUSSION TITLE
Workflow triggered by push shows up in PR as checks

### DISCUSSION THREAD

**Discussion by mortenlerudjordet** [community/community#156023] [Pull Requests] [answered]
### Select Topic Area

Question

### Body

I have a dev-branch and workflows targeting this branch with code:
```
name: dev-deploy-azure-workload

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/dev-deploy-azure-workload.yaml'
      - '.github/workflows/template-deploy-azure-workload.yaml'
      - '!app/**'
      - '!*.md'
  workflow_dispatch:
...
```
Now this works as expected when pushing to dev the workflow triggers.
Now if I create a PR right after the push, these running workflows appear as checks on the PR even if nothing in the workflow references PR logic at all.
Is this the expected behaviour?

![image](https://github.com/user-attachments/assets/da67f881-f9fd-4195-bcd9-61e3146b385a)
