### DISCUSSION TITLE
Suggestion: Support fetching the name of a job step

### DISCUSSION THREAD

**Discussion by acj** [community/community#156167] [Actions]
### Select Topic Area

Product Feedback

### Body

I would like to print the name of a different step. For example:

```yaml
steps:
  - name: Do Work
    id: do-work
    run: |
      # do heavy lifting that may fail...
  - name: Suggest troubleshooting steps if the job failed
    if: steps.do-work.outcome == "failure"
    run: echo "The job failed. Check the output in ${{ steps.do-work.name }} above"
```

If the first step fails, then the second would print "The job failed. Check the output in Do Work above".

I can duplicate the name in the second step, but then there's a risk that it will drift out of sync.
