### DISCUSSION TITLE
Configuration file error

### DISCUSSION THREAD

**Discussion by thompsonnoahe** [community/community#156254] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello,

I'm trying to get a CI up and running with my repo for CodeQL, [StreamDeckGpu](https://github.com/thompsonnoahe/StreamDeckGpu).

Unfortunately I'm running into this error:  

`Error: The configuration file "D:\a\StreamDeckGpu\StreamDeckGpu\.github\workflows\codeql\codeql-config.yml" does not exist`

It seems like the pipeline is looking in the wrong place, but I'm not sure what's wrong with my config.

My ci.yml:

```
- uses: github/codeql-action/init@v3
      with:
          languages: ${{ matrix.language }}
          config-file: .github/workflows/codeql/codeql-config.yml
```

I tried some other configuration to resolve the error, but I haven't been able to get past it thus far.
