### DISCUSSION TITLE
Main Workflow Fails to Run When Pushing to Secondary Branch

### DISCUSSION THREAD

**Discussion by skevetter** [community/community#156235] [Actions]
For a repository with branch `main` and branch `b`, when I push a change to branch `b` I expect the GitHub action defined in branch `main` to be triggered; however, the GitHub action is not triggered.

A minimal `.github/workflows/main.yml`

```
name: Test Branch Trigger
on:
  push:
    branches: [b]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow was triggered!"
```

In branch `main`, a single file `README.md` and the workflow at `.github/workflows/main.yml`

```
This is branch main
```

In branch `b`, a single file `README.md`

```
This is branch b
```

Based on the language used in the [documentation](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#on), I would expect the `on` event to start the workflow when a change is pushed to branch `b`.

How can I trigger the workflow in the `main` when a change is pushed to another branch?
