### DISCUSSION TITLE
reusable workflow with schedule as trigger does not work

### DISCUSSION THREAD

**Discussion by jk2K** [community/community#156459] [Actions]
### Select Topic Area

Bug

### Body

my workflow
```yaml
name: Build and Push

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to build and push (leave empty to build all)'
        required: false
        type: choice
        options:
          - 
          - account
          - adminpanel
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-push:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push all apps
        run: |
          echo "test"
  call-workflow-deploy:
    needs: 
      - build-and-push
    uses: ./.github/workflows/deploy.yaml
    with:
      service: ${{ inputs.service || '' }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

event workflow_dispatch is ok, event schedule not work, cannot run call-workflow-deploy

it shows `This job was skipped`
