### DISCUSSION TITLE
Non required `choice` `inputs` on `workflow_dispatch` should not have a value

### DISCUSSION THREAD

**Discussion by nickofthyme** [community/community#156505] [Actions]
### Select Topic Area

Product Feedback

### Body

The current way the `choice` type handles a non-required `input` on a [`workflow_dispatch`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch) is unexpected.

Currently, if I create a `workflow_dispatch` like shown below, where the `required` option is set to `false`...

```yml
on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      runnerTarget:
        description: "Runner target"
        required: false
        type: choice
        options:
          - ubuntu-24.04
          - windows-2025
          - ubuntu-24.04-arm
          - macos-13
          - macos-15
```

Then I go to run the workflow from GitHub, it automatically selects the first option from the list as soon an I open the menu, see below.

<img width="337" alt="image" src="https://github.com/user-attachments/assets/8babfc44-65fb-4178-a04b-b458a1a6cf93" />

In addition, this option is actually selected and passed to the `inputs.runnerTarget` value in the workflow context.

To me this current behavior functions as if the value is still required but just sets default value automatically if not explicit.

The behavior I expected from a non-required `input` would be that the select component in the GitHub UI has a `null` type value selected instead of one of the listed options. This way I can test in the workflow if the input was set, then do X otherwise Y. But as it is I cannot do this without explicitly defining a `null` type value as one of the `options`. Something like...

```yml
on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      runnerTarget:
        description: "Runner target"
        required: false
        default: " "
        type: choice
        options:
         - " "
          - ubuntu-24.04
          - windows-2025
          - ubuntu-24.04-arm
          - macos-13
          - macos-15
```

<img width="340" alt="image" src="https://github.com/user-attachments/assets/7d84ff62-2483-45b4-865a-c41cc2b3c095" />

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by Dev-LK7** [comment]
Olá,

entalhe.
Esse comportamento inesperado do `workflow_dispatch` no GitHub Actions parece ser um problema comum. Atualmente, quando um input do tipo `choice` é marcado como **não obrigatório (`required: false`)**, ele ainda seleciona automaticamente a primeira opção da lista, o que pode ser frustrante.

### Possíveis soluções:
1. **Definir um valor padrão vazio**  
   Como você mencionou, uma alternativa é definir um valor padrão explícito, como `" "` (um espaço em branco), para que o usuário tenha que selecionar manualmente uma opção:
   ```yaml
   on:
     workflow_dispatch:
       inputs:
         runnerTarget:
           description: "Runner target"
           required: false
           default: " "
           type: choice
           options:
             - " "
             - ubuntu-24.04
             - windows-2025
             - ubuntu-24.04-arm
             - macos-13
             - macos-15
   ```
   Isso pode permitir que você verifique no fluxo de trabalho se o valor foi realmente definido.

2. **Verificar se há uma solução oficial**  
   Existe uma discussão sobre esse problema na comunidade do GitHub, onde usuários relataram o mesmo comportamento inesperado. Você pode conferir [aqui](https://github.com/orgs/community/discussions/156505) para ver se há alguma atualização ou solução alternativa.

3. **Adicionar uma lógica condicional no workflow**  
   Se o GitHub Actions continuar passando automaticamente a primeira opção, você pode adicionar uma verificação dentro do seu fluxo de trabalho para ignorar valores indesejados:
   ```yaml
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: Verificar entrada
           run: |
             if [[ "${{ github.event.inputs.runnerTarget }}" == " " ]]; then
               echo "Nenhuma opção foi selecionada."
               exit 1
             fi
   ```

Se o problema persistir, pode valer a pena abrir um **issue** no repositório do GitHub Actions para que a equipe do GitHub possa revisar esse comportamento.
