### DISCUSSION TITLE
github actions for R to automatically deploy a github-pages

### DISCUSSION THREAD

**Discussion by mccroweyclinton-EPA** [community/community#156664] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello, I want to know if there is a github action to deploy R documentation for a R package hosted on github automatically without resorting to making an entire site with R package pkgdown? I just want the documentation to be visible on my repository's main github site and to be rebuilt after every commit so that changes to the documentation are up to date.

**Comment by DarkSylver** [comment, marked as answer]
Hey! 👋 Yes, you can definitely set up a GitHub Action to deploy your R package documentation without needing to build a full site using `pkgdown`.

If your goal is just to make the documentation (from `man/*.Rd` files) visible on your GitHub Pages site and keep it updated after every commit, you can:

1. Use `roxygen2` to generate the `.Rd` files.
2. Convert those `.Rd` files to HTML using base R's `tools::Rd2HTML()`.
3. Deploy the generated HTML files to GitHub Pages (e.g., using the `docs/` folder on your `main` branch).

Here’s a minimal example of a GitHub Actions workflow that does exactly that:

```yaml
name: Build R Documentation

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("roxygen2")

      - name: Generate Rd files
        run: |
          Rscript -e "roxygen2::roxygenise()"

      - name: Convert Rd to HTML
        run: |
          mkdir -p docs
          Rscript -e "rd_files <- list.files('man', full.names = TRUE); lapply(rd_files, function(f) tools::Rd2HTML(f, out = file.path('docs', paste0(tools::file_path_sans_ext(basename(f)), '.html'))))"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
```

Just make sure your repo is configured to publish GitHub Pages from the /docs folder on the main branch.

Hope this helps! Let me know if you want to tweak this for your specific setup
