### DISCUSSION TITLE
Problem using GH Packages in GH Actions

### DISCUSSION THREAD

**Discussion by monwolf** [community/community#156749] [Actions]
### Select Topic Area

Question

### Body

Hi,

I have N repositories:
- 1 my-lib: publishes to github packages a npm library. 
- my-app-n: N applications that have my-lib as dependency. 

So, I created the following reusable workflow, which uses a GH App to download files from a common repository, and the app should be used by NPM CI to download libraries within the org.

```
name: Generic Node.js Service CI/CD
on:
  workflow_call:
    inputs:
      is_CI:
        required: false
        type: boolean
        default: false
      is_TAG:
        required: false
        type: boolean
        default: false
      devops_repository:
        required: false
        type: string
        default: 'my-org/sec-reusable-pipelines'
    secrets:
      SONAR_TOKEN:
        required: false
      SNYK_TOKEN:
        required: false
      GH_APP_CICD_ID:
        required: false
      GH_APP_CICD_PKEY:
        required: false
jobs:
  build:
    defaults:
      run:
        working-directory: ${{ github.workspace}}/src
    steps:
      - uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.GH_APP_CICD_ID }}
          private-key: ${{ secrets.GH_APP_CICD_PKEY }}
          owner: 'my-org'

      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace}}/src

      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.devops_repository }}
          path: ${{ github.workspace}}/devops
          ref: master
          token: ${{ steps.app_token.outputs.token }}

      - name: Get engine from package.json
        id: get-vars
        run: |
          ENGINE=$(jq -r '.engines.node | select (.!=null)' package.json | tr -d '~' | grep -oP '[\d\.]+' | cut -f 1 -d '.')
          if [ -z "$ENGINE" ]; then
            ENGINE="20"
          fi
          if jq -r '.engines.node | select (.!=null)' package.json | grep -q 'beta'; then
            ENGINE="${ENGINE}-beta"
          fi

      - uses: actions/setup-node@v4
        env:
          ENGINE: ${{ env.ENGINE }}
        with:
          node-version: ${{ env.ENGINE }}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@my-org'
          token: ${{ steps.app_token.outputs.token }}
      - run: npm ci
   ```

I granted permissions of packages:read, and repositories read and allowed at level org.

![image](https://github.com/user-attachments/assets/7bd26ea0-b605-4f95-9b49-aa3a714d7bb1)

I can clone the common repository, but I can't use the GH App to download packages from GH Packages. I'm seeing the error:

```
Permission installation not allowed to Read organization package
```

What could I be missing?
