### DISCUSSION TITLE
Don't run CI twice when merging pull requests

### DISCUSSION THREAD

**Discussion by sebffischer** [community/community#15679] [Actions]
Hey, thanks for your efforts and for taking the time to read this!

In our github actions files we have the following triggers

```yaml
on:
  pull_request:
    branches: main
  push:
    branches: main
```

However when a PR is merged, the workflow is run twice: Once triggered by the `pull_request`-trigger and once by the `push`-trigger. In our case this is unnecessary and I cannot find an easy way how to avoid this.
