### DISCUSSION TITLE
Unexpected whitespace in expression with block scalar (>-) is preserved in env vars

### DISCUSSION THREAD

**Discussion by SebaViana** [community/community#156871] [Actions]
### Select Topic Area

Bug

### Body

When using a block scalar (>-) to assign values, (in this case when combining conditions with the && operator), when it is parsed it preserves any trailing whitespace that appears after the closing braces (}}). This unintended whitespace then gets passed to the environment variable, which can lead to unexpected behavior in subsequent steps.

How to Replicate:

Create a workflow that uses the folded block scalar syntax (>-) to assign an input or environment variable. For instance:

```
name: Test Trailing Whitespace

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: >-
        ${{ github.event_name == 'workflow_dispatch' && github.ref_name }}    
    steps:
      - name: Debug BRANCH_NAME
        run: |
          # Print the variable to reveal any trailing spaces (using cat -A for visibility)
          echo "BRANCH_NAME:'$BRANCH_NAME'" | cat -A
          # Print the length of the variable to confirm extra characters
          printf "Length: %d\n" "${#BRANCH_NAME}"
```

Notice that if there are trailing spaces after the closing }} in the expression, they are included in the resulting value of BRANCH_NAME.

Run the workflow and inspect the logs. The variable will be printed showing the extra whitespaces.

![image](https://github.com/user-attachments/assets/ed0054ff-9fda-4e75-96f7-3c5d1f5605db)

Is this working as it should or is this a bug?
