### DISCUSSION TITLE
GitHub Actions "Permission denied" when pushing - PAT works locally

### DISCUSSION THREAD

**Discussion by CoachJishere** [community/community#156921] [Actions]
### Select Topic Area

Question

### Body

Hey everyone,

I'm encountering a persistent "Permission denied" error in my GitHub Actions workflow when trying to commit and push changes back to my repository (CoachJ87/website-murder-mystery-party-generator). This workflow is intended to automatically update the browserslist-db configuration file using the update-browserslist-db package.

Interestingly, a Personal Access Token (PAT) with repo scope works successfully when I push from my local machine to the same repository. This suggests the issue might be specific to how the GITHUB_TOKEN is being handled within the Actions environment.

I've already taken the following troubleshooting steps:

- Ensured that the repository-level permissions allow GitHub Actions to write to the repository.
- Initially, I was using the stefanzweifel/git-auto-commit-action without specifying a repository URL, which should default to using the GITHUB_TOKEN. This failed with a "Permission denied" error.
- I then tried explicitly providing the repository URL with the GITHUB_TOKEN in the action's repository input (e.g., https://github.com/CoachJ87/website-murder-mystery-party-generator.git). This also resulted in the same "Permission denied" error.
- Following some suggestions, I even tried explicitly checking out the code with fetch-depth: 0 and then using the default GITHUB_TOKEN for the push, but the issue persists.

The relevant part of my workflow file (.github/workflows/update-db.yml) currently looks like this:

```
YAML

name: Update Browserslist DB

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
        with:
          fetch-depth: 0  # Fetch the entire history

      - uses: oven-sh/setup-bun@v1
        name: Setup Bun
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: 20

      - run: npx update-browserslist-db@latest
        name: Update browserslist-db

      - uses: stefanzweifel/git-auto-commit-action@v5
        name: Commit and push changes
        with:
          commit_message: "Automated update of browserslist-db"
          push_options: '--force'
          # No explicit repository URL, using GITHUB_TOKEN by default
```
The error message I consistently receive in the workflow logs is:

```
remote: Permission to CoachJ87/website-murder-mystery-party-generator.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/CoachJ87/website-murder-mystery-party-generator/': The requested URL returned error: 403
Error: Invalid status code: 128
```
I've also reviewed a related discussion here: https://github.com/orgs/community/discussions/25305, which highlights similar issues with github-actions[bot] permissions.

My questions for the community are:

- Has anyone else encountered a situation where a PAT works locally but the GITHUB_TOKEN fails with "Permission denied" for pushing within the same repository?
- Are there any repository-level settings or configurations (beyond general write permissions for Actions) that might be interfering with the GITHUB_TOKEN's ability to push?
- Could GitHub Rulesets be a potential solution for allowing this specific automated update without compromising security? If so, are there any examples of how to configure them for this type of scenario?
- What are the recommended best practices for automating repository updates like this in a secure and maintainable way?

Any insights or suggestions would be greatly appreciated! Happy to include any screenshots, etc. if necessary.

Thank you in advance!

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by MJMMiller** [comment]
Even though your PAT works locally, the `GITHUB_TOKEN` in Actions is read‑only by default and can be blocked by branch‑protection rules, so you need to (1) add at the top of your workflow:  
```yaml
permissions:
  contents: write

```
(2) In your repo’s Settings → Actions → General, ensure “Read and write permissions” is enabled; (3) Under Settings → Branches → Branch protection rules → main, allow “GitHub Actions” or “github‑actions[bot]” to bypass protection (or exempt that actor in a Code Security Ruleset under Settings → Code security and analysis → Rulesets); (4) Alternatively, store a PAT in Secrets (e.g. ACTIONS_PUSH_TOKEN) and override both the checkout and commit/push steps with that token:
```yaml
- uses: actions/checkout@v4
  with:
    token: ${{ secrets.ACTIONS_PUSH_TOKEN }}
    fetch-depth: 0

- uses: stefanzweifel/git-auto-commit-action@v5
  with:
    commit_message: "Automated update of browserslist-db"
    push_options: --force
    repository: https://x-access-token:${{ secrets.ACTIONS_PUSH_TOKEN }}@github.com/${{ github.repository }}.git

```
Best practices: scope tokens narrowly, pin action versions, use fetch-depth: 0, and if you protect main remember to permit the Actions bot.```
