### DISCUSSION TITLE
Passing inputs and secrets to a reusable workflow based on a condition

### DISCUSSION THREAD

**Discussion by SunilDSK** [community/community#156932] [Actions]
### Select Topic Area

Question

### Body

I have a reusable workflow as shown below - 
```yml
name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
        default: .github/default.yml
    secrets:
      token:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}
```

This is how we call that workflow from another workflow, 

```yaml
jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      personal_access_token: ${{ secrets.token }}
```

### Question or Feature Request

**Is there a way that I can pass a secret to a reusable workflow based on a condition?**
```yaml
jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      if: ${{ github.event_name == 'push' }}
        config-path: .github/labeler.yml
      if: ${{ github.event_name == 'pull_request' }}
        config-path: .github/labeler-pr.yml
    secrets:
      personal_access_token: ${{ secrets.token }}
```

If not, can you please support it some way. The feature is - 
- Pass the parameter to a reusable workflow based on a condition, i**f the condition is false, do not send the parameter, if the condition is true, pass the parameter with the value assigned.** If the condition is false then the reusable workflow should use the default value of a input parameter, if there is not default parameter and the input parameter is required, it should fail calling that workflow and error out saying required parameter not provided.
Example: In the above example, if this condition is true - `if: ${{ github.event_name == 'push' }}`, we pass `config-path: .github/labeler.yml`. If this condition is true - `if: ${{ github.event_name == 'pull_request' }}` then we pass `config-path: .github/labeler-pr.yml`. If both these conditions are false, then the default value defined in the reusable workflow should be used - `default: .github/default.yml`
