### DISCUSSION TITLE
Issue Forms: Delimiter field for multiple choice `dropdown`

### DISCUSSION THREAD

**Discussion by michael-valdron** [community/community#157091] [Projects and Issues]
### Select Topic Area

Product Feedback

### Feature Area

Issues

### Body

# Description

I'd like to open this feature request to allow for the override of the delimiter used to separate multiple values selected under a multiple choice `dropdown` field.

## Issue Form Example

Use field `attributes.delimiter` to override the default `,`:

```yaml
name: Bug report
description: 🐞 Report a bug
labels:
  - bug
body:
  - type: dropdown
    attributes:
      label: Select value(s)
      description: Choose one or more value(s) this bug to have.
      multiple: true
      attributes:
        delimiter: \n
      options:
        - foo
        - bar
        - world
    validations:
      required: true
```

## Rendered Example

If `foo` and `bar` are selected:

```markdown
### Select value(s)
foo
bar
```

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
