### DISCUSSION TITLE
can a workflow triggered by `workflow_run` be used as a status check in a PR?

### DISCUSSION THREAD

**Discussion by gilzow** [community/community#157109] [Actions] [answered]
### Select Topic Area

Question

### Body

Recently went through a refactor of some of our workflows to tighten up security. Following the guidelines from https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/ we moved some of our testing jobs into a workflow that is now triggered by the `workflow_run` event. Unfortunately, it now seems that those jobs can no longer report their status back to the Pull Request as a required status check. Or at least, I haven't been able to find a way to add them. 

Additionally, my searches for a work-around have not turned up anything that works. Using the example from the link above, if the `CommentPR.yml` workflow were to contain a job that needs to be used as a required status check in a PR, how would you do it?

**Comment by ChristopherHX** [comment, marked as answer]
I do not have tried this.

I would try to create-a-commit-status via your `${{ github.token }}` (make sure it has required write scopes, test via on: push otherwise this can be a hard task with only workflow_run) https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status

- Get the merge commit sha (or it was head commit sha, idk) of the triggering Pullrequest event, for manual testing this is printed in the actions/checkout@v4 step log
- owner easy
- repo easy

You should be able to freely set any context you want to create as required status for your PR.

Tip
- try this e.g. curl command locally for a example PR using a Personal Access Token
- Check if you can see the custom commit status
- Check if you are able to configure branch protection for it
- Check your last workflow_run logs and look at the permission it has, you may need to add `status: write`

At very least a PERSONAL_ACCESS_TOKEN / a GitHub App auth action using different kind of secret should work in your workflow_run job.

**Reply by ChristopherHX** [reply]
https://github.com/ChristopherHX/pr-wf-run-required-status/blob/main/.github/workflows/privileged.yml
```yaml
name: Privileged
on:
  workflow_run:
    workflows:
    - PR
    types:
    - completed
jobs:
  priv:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ github.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }} \
        -d '{"state":"success","target_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}","description":"The Privileged job succeeded!","context":"continuous-integration/Privileged"}'
```

![image](https://github.com/user-attachments/assets/4898621a-4369-455d-b819-2ba2d3a23554)
