### DISCUSSION TITLE
Is it necessary to stop and start application pools in IIS when deploying to a Windows server with a self-hosted runner?

### DISCUSSION THREAD

**Discussion by Rod-at-DOH** [community/community#157417] [Actions]
### Select Topic Area

Question

### Body

I'm working with a colleague on developing a GitHub Action/workflow to deploy changes to IIS on a Windows web server. My colleague is convinced that it is necessary to stop the application pool in IIS, then push the changes using dotnet, then restart the application pool in IIS. Here's a snippet from the workflow we've developed so far:

```yaml
    - name: Stop Web Site and App Pool
      run: |
        Invoke-Command -ComputerName ourserver -ScriptBlock { Import-Module WebAdministration; Stop-WebAppPool -Name "BES-Dev" -ErrorAction Ignore; Stop-IISSite -Name "BES-Dev" -Confirm: $false }
    - name: Delete all Web Site Contents
      env:
        REMOTE_PATH: \\ourserver\d$\wwwroot\BES-Dev\current
      run: |
        Remove-Item -Path '${{env.REMOTE_PATH}}' -Recurse -Force -ErrorAction Continue
    - name: Deploy to Dev Server
      env:
        REMOTE_PATH: \\ourserver\d$\wwwroot\BES-Dev\current
        MSDEPLOY_RENAME_LOCKED_FILES: 1
      run: |
        dotnet publish BESApp/BESApp.csproj -o ${{env.REMOTE_PATH}} -c Debug -f net9.0 --no-restore
    - name: Restart Web Site and App Pool
      run: |
        Invoke-Command -ComputerName ourserver -ScriptBlock { Import-Module WebAdministration; Start-WebAppPool -Name "BES-Dev" ;  Start-IISSite -Name "BES-Dev" }
```

I'd like to know if what he wants to do is necessary or at least a best practice for deploying to IIS on a Windows server using a GitHub self-hosted runner.
