### DISCUSSION TITLE
PR check is recently getting stuck occasionally because its workflow never starts

### DISCUSSION THREAD

**Discussion by blazceltra** [community/community#157457] [Actions]
### Select Topic Area

Bug

### Body

In the last two weeks more and more PRs are getting stuck because the workflow of one of our checks never starts. We noticed it happens right after the changes from master are merged into the branch. The check has the following workflow triggers set

```yaml
on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - review_requested
      - ready_for_review
```

For handling merge queues we're using https://kodiakhq.com/. Currently we have to manually remove the `automerge` label and reapply it to re-trigger the workflow which also runs the check which previously didn't even start after the merge.
