### DISCUSSION TITLE
Reminder for Due Date in Project Board

### DISCUSSION THREAD

**Discussion by philg1234** [community/community#157527] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

Hello together,

i search for a nice solution to remind me when e Issue on a Project Board with the Field "Due Date" is reached.

i thought about a Power Automate Flow to send me an teams message when the Due Date is reached. But im not sure how i should configre this correctly with the webhooks or if this the correct and best solution for this part.

Have someone configure a flow like this or a other simular solution for this?

Thans a lot.

Regards,
Phil

**Comment by arcibyte** [comment]
Hey Phil,

Good question! Using Power Automate to receive a message in Teams when the “Due Date” of an issue on a Project Board is reached is entirely possible, although there are a couple of things to keep in mind:

GitHub does not send automatic notifications when a due date is met, so to achieve this you would need to create a flow that regularly checks the issues in your project (e.g. once a day) and compares the current date with the Due Date for each one. If they match, then you can send a message via Teams.

One option is to use the GitHub API to make a call from Power Automate and get the Project Board data or related issues. Then, with a condition within the flow, you can trigger the notification if the current date is equal to or later than the due field.

It's not very simple to set up at first, but it is a viable solution. You could also explore tools like Zapier or GitHub Actions combined with other APIs if you're looking for something different.

If you need help setting up that flow, I'd be happy to guide you further. success with that!

**Reply by philg1234** [reply]
@arcibyte thanks for your Answer.

first for me is the way with Power Automate Only an Idea. I dont must use this way and maybe its also important which license ist required for this way.

Can you explain how i can Put the Data from the API with Powerautomate.

For me its Not clear how i should do this and i need informations for the specific steps.

###

How i Said. If you have an Option with GitHub Actions Its also fine for me.

Regards,
Phil

**Reply by arcibyte** [reply]
Hi Phil,

Since you mentioned that Power Automate was just an idea and you’re open to other approaches, I think the simplest and most reliable solution would be to use **GitHub Actions**. You don’t need any extra tools, licenses, or integrations — everything runs directly inside GitHub.

Here’s how it works:

- The workflow runs once a day at 8 AM UTC.
- It checks all open issues in your repo for a line like `Due Date: YYYY-MM-DD` in the issue body.
- If the due date matches today’s date, it posts a reminder comment on that issue.

You can create this file in your repo under `.github/workflows/due-date-reminder.yml`:

```yaml
name: Due Date Reminder

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8:00 AM UTC
  workflow_dispatch:

jobs:
  check-due-dates:
    runs-on: ubuntu-latest

    steps:
      - name: Check due dates and post reminders
        uses: actions/github-script@v7
        with:
          script: |
            const today = new Date().toISOString().slice(0, 10);
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            for (const issue of issues.data) {
              const match = issue.body?.match(/Due Date:\s*(\d{4}-\d{2}-\d{2})/);
              if (match && match[1] === today) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: `Reminder: Today is the due date for this issue.`,
                });
              }
            }
```

To make it work, just add a line like this in the body of any issue:

```
Due Date: 2025-04-25
```
The script will detect that date when it matches today, and leave a comment automatically.

If you ever want to expand this later — for example, sending Teams messages or adding filters based on labels — that can definitely be done. I’d be happy to help with that if it’s something you’re interested in.

Let me know how it goes or if you need help setting it up.

Best,

Jhon
