### DISCUSSION TITLE
Variables declared at the repo and deployment environment level should be automatically available as environment variables to any step

### DISCUSSION THREAD

**Discussion by pemattr** [community/community#157754] [Actions]
### Select Topic Area

Product Feedback

### Body

Because the variables settings in the Actions secrets and variables page in the repo settings is labeled as "Environment variables", I assumed that anything I added there would be added as an "Environment variable" within my workflow and would automatically available. Unfortunately that doesn't appear to be the case, but i think it should be. It would make it far more intuitive to new users and would save me having to do a 1-1 mapping of my variables for each deployment:

```
env:
  VAR_A: ${{ vars.VAR_A }}
  VAR_B: ${{ vars.VAR_B }}
  VAR_C: ${{ vars.VAR_C }}
```
