### DISCUSSION TITLE
How to download contents of a submodule?

### DISCUSSION THREAD

**Discussion by blackears** [community/community#157708] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm diving into Github actions for the first time.  I'm trying to set up a workflow similar to the process described here so that I can build platform extensions automatically for the Godot game engine:
https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html

I'm having an issue that `scons` is unable to find the SConstruct file it needs to carry out the build.  I'm trying to `cd` into the diretory, but it doesn't seem to be working

```
name: build-linux
#on: push
on: [workflow_dispatch]
jobs:
  build-linux-extension:
    name: Build Linux Extension
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Install Packages
          run: |
            sudo apt-get update
            sudo apt-get install g++
            sudo apt-get install python3
            sudo python -m pip install scons
        - name: Compile Support Library
          run: |
            cd ${{ github.workspace }}/foo/godot-cpp
            ls
            scons platform=linux custom_api_file=${{ github.workspace }}/foo/extension_api.json -f ${{ github.workspace }}/foo/SConstruct
```

This is resulting in the error 

```
Run cd /home/runner/work/PROJECT7-WORLD_PROTOTYPE/PROJECT7-WORLD_PROTOTYPE/foo/godot-cpp
  cd /home/runner/work/PROJECT7-WORLD_PROTOTYPE/PROJECT7-WORLD_PROTOTYPE/foo/godot-cpp
  ls
  scons platform=linux custom_api_file=/home/runner/work/PROJECT7-WORLD_PROTOTYPE/PROJECT7-WORLD_PROTOTYPE/foo/extension_api.json -f /home/runner/work/PROJECT7-WORLD_PROTOTYPE/PROJECT7-WORLD_PROTOTYPE/foo/SConstruct
  shell: /usr/bin/bash -e {0}
scons: Reading SConscript files ...

scons: *** missing SConscript file 'godot-cpp/SConstruct'
File "/home/runner/work/PROJECT7-WORLD_PROTOTYPE/PROJECT7-WORLD_PROTOTYPE/foo/SConstruct", line 5, in <module>
Error: Process completed with exit code 2.
```

The SConstruct file is there, but perhaps I'm misunderstanding how actions handle directory structures?  I've tries `scons` without the `-f` flag too which should look for the `SConstruct` file in the current directory, but that's failing too.  The `ls` command is also printing nothing.

How do I get this to compile?

**Comment by blackears** [comment]
After doing more digging, I think the problem is that `godot-cpp` is a submodule `(git submodule add -b 4.x https://github.com/godotengine/godot-cpp)` that does not have its code copied over when the `actions/checkout@v4` command runs.  Is there any way to force this code to be copied in?

Also, this compilation step should be producing the same binary every time it is run, and the library it makes takes a while to run.  Is there any way to only compile it when its source has been updated and just use a cached copy whenever I run this build action if I build the library earlier?

**Comment by Lemeri123** [comment]
You're right — GitHub Actions doesn't pull submodules by default when using actions/checkout.
You need to set submodules: recursive to true, like this:

- uses: actions/checkout@v4
  with:
    submodules: recursive

This will clone godot-cpp properly.

For caching the build, you can use the actions/cache action to save and restore the compiled library. You'd cache your build folder based on the checksum of the source files to avoid unnecessary rebuilds.

**Reply by blackears** [reply]
I've tried a couple of variations of your suggestion and can't get anything that works.  The formatting in your comment makes it difficult to tell what the correct indentation should be.

Do you know where I can read up on the different `uses:actions` that are available?  I can't find that in the docs anywhere.  Also, would you know how I'd calculate a checksum and where I could learn more about that cache action you mentioned?

**Reply by blackears** [reply]
Okay, it looks like 
```
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            submodules: recursive
```
does it.  And the actions are all subprojects like `https://github.com/actions/cache`

**Reply by RUYANGA** [reply]
Which module are you want to downloading?

**Reply by blackears** [reply]
The submodule is `https://github.com/godotengine/godot-cpp`

**Reply by blackears** [reply, marked as answer]
Okay, think I've got it working:
```
name: build-linux
on: [workflow_dispatch]
jobs:
  build-linux-extension:
    name: Build Linux Extension
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            submodules: recursive
                        
        - name: Install Packages
          run: |
            sudo apt-get update
            sudo apt-get install -y g++ python3 python3-pip
            sudo python -m pip install scons

        - name: Cache Library
          id: cache_linux_library
          uses: actions/cache@v4
          with:
            path: |
              bin/*.a
            key: ${{ runner.os }}-extn-${{ hashFiles('**/*.cpp', '**/*.hpp', '**/SConstruct') }}
            restore-keys: |
              ${{ runner.os }}-extn-
            
        - name: Compile Support Library
          if: steps.cache_linux_library.outputs.cache-hit != true
          working-directory: ./map_generation/godot-cpp
          run: |
            scons platform=linux custom_api_file=../extension_api.json

```
