### DISCUSSION TITLE
Why is this step not being skipped when my cache is found?

### DISCUSSION THREAD

**Discussion by blackears** [community/community#157759] [Actions]
### Select Topic Area

Question

### Body

I'm new to actions and trying to figure out why my `Compile  Support Library` task is not being skipped when the cache is restored.  
```
name: build-linux
on: [workflow_dispatch]
jobs:
  build-linux-extension:
    name: Build Linux Extension
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            submodules: recursive
                        
        - name: Install Packages
          run: |
            sudo apt-get update
            sudo apt-get install -y g++ python3 python3-pip
            sudo python -m pip install scons

        - name: Cache Library
          id: cache-linux-libraries
          uses: actions/cache@v4
          with:
            path: |
              ./map_generation/godot-cpp/bin/*.a
            key: ${{ runner.os }}-extn-${{ hashFiles('./map_generation/godot-cpp/**/*.cpp', './map_generation/godot-cpp/**/*.hpp', './map_generation/godot-cpp/SConstruct') }}
            
        - name: Compile Support Library
          if: steps.cache-linux-libraries.outputs.cache-hit != true
          working-directory: ./map_generation/godot-cpp
          run: |
            scons platform=linux arch=x86_64 custom_api_file=../extension_api.json

```

When I run this action, the printout in the actions tab is reporting that it restored my cache
```
Run actions/cache@v4
Cache hit for: Linux-extn-7948e1f7a339644b304bbc0eebf2af8d0983cc1037ac7918b99bf6bd21789adc
Received 7687320 of 7687320 (100.0%), 13.0 MBs/sec
Cache Size: ~7 MB (7687320 B)
/usr/bin/tar -xf /home/runner/work/_temp/6a97a623-6ce9-4220-b93d-23d7f475acc3/cache.tzst -P -C /home/runner/work/PROJECT7-WORLD_PROTOTYPE/PROJECT7-WORLD_PROTOTYPE --use-compress-program unzstd
Cache restored successfully
Cache restored from key: Linux-extn-7948e1f7a339644b304bbc0eebf2af8d0983cc1037ac7918b99bf6bd21789adc
```

None the less, it still runs the Compile Support Library step and starts rebuilding the library.  Isn't the `if: steps.cache-linux-libraries.outputs.cache-hit != true` supposed to prevent that?  How do I stop that step from running if the cache is restored?
