### DISCUSSION TITLE
How to Dynamically Resolve Secrets and Build Args in Reusable Workflows?

### DISCUSSION THREAD

**Discussion by sureshkumar2024** [community/community#157815] [Actions]
I am trying to create a reusable workflow in GitHub Actions for building and pushing container images. The `build-args` need to include secrets that are application-specific, alongside other environment variables. Since these secrets vary between applications, we cannot define all possible secrets upfront in the reusable workflow.

**Problem:**
Secrets such as `SECRET_1` and `SECRET_2` cannot be directly passed as `build-args` to the reusable workflow, and they are unresolved during the Docker build process, even when `secrets: inherit` is used.
Here’s the complete example of the workflows I’m working with.

**Example Workflows**
**Main Workflow (Caller Workflow)**
```
name: Build and Deploy Service

on:
  push:
    branches:
      - staging
      - production
      - feature/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  env_vars: # Expose environment variables dynamically
    name: Expose Environment Variables
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/production' && 'production' || 'staging' }}
    outputs:
      app_name: ${{ vars.SERVICE_APP_NAME }}
      runtime_env: ${{ vars.RUNTIME_ENVIRONMENT }}
    steps:
      - run: echo "Exposing environment variables for build."
  
  build:
    needs: [env_vars] # Make sure environment variables are exposed before running this step
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      environment: ${{ github.ref == 'refs/heads/production' && 'production' || 'staging' }}
      app_name: ${{ needs.env_vars.outputs.app_name }}
      dockerfile_path: app/Dockerfile
      build_args: |
        RUNTIME_ENVIRONMENT=${{ needs.env_vars.outputs.runtime_env }}
        SECRET_1=${{ secrets.SECRET_1 }}
        SECRET_2=${{ secrets.SECRET_2 }}
    secrets: inherit 
```
**Reusable Workflow**
```
name: Build and Push Container Image
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      build_args:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets: {} # Allow secrets to be inherited dynamically

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.CONTAINER_REGISTRY_URL }}${{ inputs.app_name }}:${{ github.sha }}
          context: .
          file: ${{ inputs.dockerfile_path }}
          build-args: |
            ${{ inputs.build_args }}
```

**Key Details:**
1. **Dynamic `build-args`**
The `build-args` are passed dynamically from the main workflow to the reusable workflow using `with` parameters.
2. **Handling Secrets:**
    - Secrets like `SECRET_1` and `SECRET_2` are defined in the repository settings under `Settings > Secrets and Variables > Actions`.
    - `secrets: inherit` is used to allow reusable workflows to access secrets dynamically without hardcoding specific names.

3. **Environment Variables:**
Workflows dynamically expose environment variables like `RUNTIME_ENVIRONMENT`, which is resolved in the reusable workflow.

**Questions:**
1. How can I ensure `build-args` dynamically resolve secrets within the reusable workflow during runtime from caller workflow?
2. Are there limitations on using `secrets: inherit` in reusable workflows, or is there a better approach?
3. What is the best way to handle application-specific secrets in a reusable workflow where the options (like `build-args`) vary between implementations?
