### DISCUSSION TITLE
Issue Forms: Add the ability to use value from one input in another (template variables)

### DISCUSSION THREAD

**Discussion by just-joshing** [community/community#15808] [Projects and Issues]
I want to be able to specify a value in one input that can then be referenced in markdown text.

For example, say I have
```
  - type: input
    id: name
    attributes:
      label: Name
      description: What's your name?
      placeholder: ex. Jane Smith/John Doe
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks, %name%, for taking the time to fill out this bug report!
```

Whatever text the user specifies in the "name" input, I want to be able to use it in the markdown text, replacing `%name%`.

My use case: I know I can add URL query params to auto-populate inputs in forms today. I create links with different pre-populated values that I share with my team to help them more quickly create issues with the appropriate fields already pre-filled out. But I also have some lengthy markdown I want to add to my template that would make use of those pre-filled inputs to generate more links to other resources/insights or related things. Putting the lengthy text I want in the URL query params isn't possible/practical (and I don't want the user to be able to edit the lengthy text directly in something like a `textarea`), so I want to be able to take the short inputs and reuse them, potentially multiple times, in `markdown` inputs I have in the issue form/template.
