### DISCUSSION TITLE
[Bug] An empty branches list matches all branches, not none

### DISCUSSION THREAD

**Discussion by 42degrees** [community/community#158135] [Actions]
### Select Topic Area

Bug

### Body

If I'm reading the documentation correctly having a branches list with no items in it should match no branches, but instead it matches all branches.  Is this correct behavior?

Both of these match all branches:
```
name: Deploy site
on: 
  push:
    branches:
      #- main
      #- stage
      #- dev
```
or
```
name: Deploy site
on: 
  push:
    branches: []

```
The first ends up matching all branches when it was clearly intended to temporarily disable the action by commenting out all branches.  The only solution is to either make the branch names invalid (like changing "- main" to "- xmain") or adding one bogus branch to the list:

```
name: Deploy site
on: 
  push:
    branches:
      #- main
      #- stage
      #- dev
      - fake_branch
```

Anything that makes the resulting list non-empty.
