### DISCUSSION TITLE
Can I set the environment from the output of another job?

### DISCUSSION THREAD

**Discussion by yeikel** [community/community#158223] [Actions]
I tried the following but that does not seem to work

Does the environment need to be static? 

```yml
  derive-github-environment:
    name: Derive GitHub Environment
   needs: dependency1
    outputs:
      github-environment: ${{ steps.derive.outputs.github_environment }}
    steps:
      - name: Derive
        id: derive
        run: |
           # Logic to generate the github-environment output
           # for example we have multiple staging environment and use the dependencies
           # for example we have multiple staging environment
          echo "github_environment=demo" >> $GITHUB_OUTPUT

  publish-github-environment:
    name: Publish deployment to GitHub Environment
    needs: derive-github-environment
    environment: ${{ needs.derive-github-environment.outputs.github-environment }}
    steps:
      - name: Publish
        run: |
          echo "Published Deployment to Github Environment ${{ needs.derive-github-environment.outputs.github-environment }}"
```
