### DISCUSSION TITLE
GHA reports missing or wrong secrets if used via "secrets: inherit" and in combination with workflow templates

### DISCUSSION THREAD

**Discussion by Paebbels** [community/community#158322] [Actions]
### Select Topic Area

Bug

### Body

On the one hand, I maintain many Python and VHDL code repositories on GitHub in several organisations and user accounts. On the other hand, I develop reusable workflow templates for these repositories to lower the maintenance affords for me and others. Of cause one or two reusable workflows are used by external users too (GHDL, OSVVM, ...).

The problem I'm facing is neither easy to describe nor easy to debug, especially as secrets are not visible in any log ... or can be printed :) ... So how to debug the invisible? I'm already spending more then 3 weeks trying to figure out what's going on in GitHub Actions. I have more then 10 years of CI scripting experience in AppVeyor, Travis-CI, GitLab and I'm a GitHub Action user since day 2. So please trust me, I'm trying to investigate some very odd behavior in GitHub Actions.

Let me take just a few example repositories (from different organisations or accounts):
1. **[pyTooling/Actions](https://github.com/pyTooling/Actions)**  
   A repository providing actions and reusable workflow templates.
2. **[pyTooling/pyTooling](https://github.com/pyTooling/pyTooling)**  
   A collection of standard functions, decorators, classes, etc. for everyday Python use.
3. **[Paebbels/pyVersioning](https://github.com/paebbels/pyVersioning)**  
   A CLI tool to generate source files containing version information from environment variables or VCS (e.g. Git) in CI services (e.g. GitHub, GitLab, Travis-CI).
4. **[pyTooling/sphinx-reports](https://github.com/pyTooling/sphinx-reports)**  
   A Sphinx extension to embedded unittest, code coverage and documentation coverage reports into a Sphinx-based documentation.
5. **[edaa-org/pyEDAA.CLITool](https://github.com/edaa-org/pyEDAA.CLITool)**  
   An CLI abstraction layer for EDA tools.

# pyTooling/Actions
This repository contains multiple reusable workflows as templates suitable for Python projects. Of cause, these can be parameterized with input parameters and secrets. A user can instantiate individual workflow templates in his pipeline, or he can use a [`CompletePipeline.yml`](https://github.com/pyTooling/Actions/blob/dev/.github/workflows/CompletePipeline.yml) with is suitable for any "simple" Python project. It offers unit testing, packaging and documentation generation and finally GitHub release pages and PyPI uploads. Intermediate results like unittest results and code coverage reports can be uploaded to Codecov, Codacy and others. Obviously, these require API tokens and therefore GitHub Action secrets.

All described code and behavior is currently on `dev` branch in pyTooling/Actions, otherwise if not tested in other repositories, it might brake lots of pipelines using the `@main` or `@r4` releases. Moreover as it feels right now, the problem seams to be cross repository and even cross-organisation problem. That's why I always test such heavy changes in repositories referencing pyTooling/Actions.

pyTooling/Actions itself has multiple pipelines testing its own features any YAML syntax.

All workflow templates offer one or more jobs and a list of input as well as output parameters. No other workflows templates are instantiated. Each workflow is designed to work with Linux (Ubuntu), Windows or macOS. Moreover, Windows+MSYS2 is supported too. Thus some of them support running as a matrix exception a JSON input parameter.

Jobs might need tokens to authenticate at external services, thus job templates describe secrets using this form:
```yaml
on:
  workflow_call:
    inputs:
      # more parameters
      # ...
      codecov:
        description: 'Publish merged unittest results to Codecov.'
        required: false
        default: true
        type: boolean
    secrets:
      CODECOV_TOKEN:
        description: 'Token to push result to Codecov.'
        required: false
```
As publishing to codecov might be disabled by users via `inputs.codecov`, the secret is set to be optional.

The secret is used like this in [`PublishTestResults.yml`](https://github.com/pyTooling/Actions/blob/dev/.github/workflows/PublishTestResults.yml):
```yaml
jobs:
  PublishTestResults:
    name: 📊 Publish Test Results
    runs-on: "ubuntu-${{ inputs.ubuntu_image_version }}"
    if: always()

    steps:
      # more steps
      # ...
      - name: 📊 Publish unittest results at CodeCov
        uses: codecov/test-results-action@v1
        id: codecov
        if: inputs.codecov
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true
          files: ${{ inputs.merged_junit_filename }}
          flags: ${{ inputs.codecov_flags }}
          fail_ci_if_error: true
```

The job template is used like this in [`Pipeline.yml`](https://github.com/pyTooling/pyTooling/blob/main/.github/workflows/Pipeline.yml#L119):

```yaml
  PublishTestResults:
    uses: pyTooling/Actions/.github/workflows/PublishTestResults.yml@dev
    needs:
      - ConfigParams
      - UnitTestingParams
      - UnitTesting
      - AppTesting
    with:
      testsuite-summary-name: ${{ needs.ConfigParams.outputs.package_fullname }}
      merged_junit_filename:  ${{ needs.ConfigParams.outputs.unittest_merged_report_xml_filename }}
      merged_junit_artifact:  ${{ fromJson(needs.UnitTestingParams.outputs.artifact_names).unittesting_xml }}
      dorny:                  true
      codecov:                true
    secrets: inherit
```

In general, the following job templates are offered:
* preparation, parameter extraction, matrix generation
* unit tests, application tests, performance tests, ...
* publishing of code coverage
* publishing of unittest
* documentation generation
* publishing to github pages
* publishing to PyPI
* release page generation from PullRequest
* automatic tagging if pipeline was successful

The whole pipeline is summarized in [`CompletePipeline.yml`](https://github.com/pyTooling/Actions/blob/dev/.github/workflows/CompletePipeline.yml). This allows a repository to instantiate a single reusable workflow file with just a few parameters. This setup needs to pass secrets one layer further down.

```yaml
on:
  workflow_call:
    inputs:
      package_namespace:
        description: 'Name of the tool''s namespace.'
        required: false
        default: ''
        type: string
      package_name:
        description: 'Name of the tool''s package.'
        required: true
        type: string
      codecov:
        description: 'Publish merged coverage and unittest reports to Codecov.'
        required: false
        default: false
        type: boolean
      codacy:
        description: 'Publish merged coverage report to Codacy.'
        required: false
        default: false
        type: boolean
    secrets:
      PYPI_TOKEN:
        description: "Token for pushing releases to PyPI."
        required: false
      CODECOV_TOKEN:
        description: "Token for pushing coverage and unittest results to Codecov."
        required: false
      CODACY_TOKEN:
        description: "Token for pushing coverage results to Codacy."
        required: false

jobs:
  Prepare:
    uses: pyTooling/Actions/.github/workflows/PrepareJob.yml@dev

  ConfigParams:
    uses: pyTooling/Actions/.github/workflows/ExtractConfiguration.yml@dev
    with:
      package_namespace: ${{ inputs.package_namespace }}
      package_name:      ${{ inputs.package_name }}

  # more jobs in between
  # ...

  PublishTestResults:
    uses: pyTooling/Actions/.github/workflows/PublishTestResults.yml@dev
    needs:
      - ConfigParams
      - UnitTestingParams
      - UnitTesting
    with:
      testsuite-summary-name: ${{ inputs.package_name }}
      merged_junit_filename:  ${{ needs.ConfigParams.outputs.unittest_merged_report_xml_filename }}
      merged_junit_artifact:  ${{ fromJson(needs.UnitTestingParams.outputs.artifact_names).unittesting_xml }}
      dorny:                  ${{ inputs.dorny }}
      codecov:                ${{ inputs.codecov }}
    secrets: inherit

  # more jobs to follow
  # ...
```

This overall template is now used as follows in [`Pipeline.yml`](https://github.com/pyTooling/sphinx-reports/blob/main/.github/workflows/Pipeline.yml):
```yaml
on:
  push:
  create:
  workflow_dispatch:

jobs:
  Pipeline:
    uses: pyTooling/Actions/.github/workflows/CompletePipeline.yml@dev
    permissions:
      contents: write  # required for create tag
      actions:  write  # required for trigger workflow
    with:
      package_name: sphinx_reports
      unittest_python_version_list: '3.11 3.12 3.13'
      codecov: true
      codacy:  true
      dorny:   true
    secrets: inherit
```

# First Results

If the repository using the reusable workflows is not in the same namespace, secrets are not arriving at the steps using them.

Note: Until last week I got YAML syntax errors from that the secret was not defined, but it was listed in the repositories admin menu.

| 1) pyTooling/Actions     | 2) pyTooling/pyTooling | 3) Paebbels/pyVersioning | 4) pyTooling/sphinx-reports | 5) edaa-org/pyEDAA.CLITool |
| --- | --- | --- | --- | --- |
| doesn't use `@dev` | uses individual instantiations of multiple reusable workflows from pyTooling/Actions as `@dev` | uses individual instantiations of multiple reusable workflows from pyTooling/Actions as `@dev` | uses a single instantiation of `CompletePipeline.yml` as `@dev` | uses individual instantiations of multiple reusable workflows from pyTooling/Actions as `@dev` |
| not yet tested on `@main`<br>results for `@dev`<br>* ✅ Codecov<br>* ✅ Codacy<br> | works fine<br>* ✅ Codecov<br>* ✅ Codacy<br>* ✅ PyPI<br>* ✅ trigger tag | non-working secrets<br>* ❌ Codecov<br>* ❌ Codacy<br>* ❌ PyPI<br>* ⚠️ trigger tag | works fine<br>* ✅ Codecov<br>* ✅ Codacy<br>* ✅ PyPI<br>* ✅ trigger tag |  non-working secrets<br>* ❌ Codecov<br>* ❌ Codacy<br>* ❌ PyPI<br>* ⚠️ trigger tag |

# Conclusions

## Explicit secret handover &rArr; `secrets: inherit` is broken
When handing over secrets explicitly like:
```yaml
  PublishTestResults:
    uses: pyTooling/Actions/.github/workflows/PublishTestResults.yml@dev
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
The secret is available and codecov publishes the unittest results. Compared to earlier results from a week ago, There is no YAML parser error for a missing secret, despite the fact that the secret was missing without an explicit handover.

So we can call this a 🪳, because `inherit` doesn't work. It's also misses an orthogonal implementation, because under some conditions a missing secret is reported and caused a job to fail hard.

## `${{ github.token }}` is not affected
Because the GitHub token is handed over in a different context, it's not affected. This should be only the case if a PAT (personal access token) is used and handed over via secrets.

# Further 🪳🪳🪳
## 🪳 Parameter type `boolean`
The data type `boolean` for input parameters is broken. Especially, there is no implicit (and no explicit) type conversion in GitHubs YAML syntax.
```yaml
  codecov:
    description: 'some description'
    required: false
    default: false
    type: boolean
```
Sometimes such a parameter can be used directly like in:
```yaml
  if: inputs.codecov
```

The usage is as follows:
```yaml
  with:
    codecov: false
```

In this case, the if evaluates to true, because `codecov` is a string of `'false'`. If the line is commented out, it works, because then the default is used, which was implicitly type converted by the GitHub Action YAML parser.

There is no syntax to type convert strings to a boolean. There is also no conversion function like `toBool(...)`.

The same happens when a script in a step writes an output parameter to `${GITHUB_OUTPUT}`, which is then conveyed from a step output to a job output and then again to a reusable workflow output. Here GitHub complains about a type mismatch between string and boolean.

While the previous has a type check and enforces type correctness, it's not applied to my first example. Thus another 🪳, because it'snot an orthogonal implementation.

**Suggestions:**
1. Remove type boolean as it's totally broken and unusable in YAML files, OR
2. Add implicit type conversions and/or type converter functions like `toBool` similar to the JSON functions.

I suspect the same problems exist for type `number` ...

## 🪳 If expression for jobs in a reusable workflows doesn't work
When defining an `if` expression for a job in a reusable workflow, this expression is not evaluated and no error is raised. If the instantiation uses an `if` expression, it's evaluated. Also if both `if` expressions are present, only the outer one is evaluated.

Callee (Test.yml):
```yaml
on:
  workflow_call:

jobs:
  MyJob:
    if: startsWith(github.ref, 'refs/tags')    # gets ignored
```

Caller:
```yaml
jobs:
  Test:
    uses: ...../Test.yml
    if: startsWith(github.ref, 'refs/tags')
```

I expect:
* `if` expressions on jobs in reusable workflows must work.
* if both expressions are applied, both must evaluate to true using a short-circuit behavior.

## 🪳 Accessing needs parameters without a needs rules doesn't error
When accessing a job output parameter via `needs`, but that job is not listed in the needs rule, no error is thrown and an empty string is used.

In parity to other checks like existing secrets, an error should be raised if a job output parameter is requested, but not defined via needs. Such a feature would drastically reduce debugging times and reduce number of pipelines send to GitHub for testing.

```yaml
jobs:
  Prepare:
    # ...

  Config:
    # ...

  Release:
    needs:
      - Prepare
    # ...
    with:
      package: ${{ needs.Config.output.package }}    # <= Config is not in needs
```

**Suggestion**
* Raise an error.
