### DISCUSSION TITLE
How Do You Handle Complex API Regression Testing Workflows in CI/CD Pipelines?

### DISCUSSION THREAD

**Discussion by GunashreeRs** [community/community#158586] [Programming Help]
### Select Topic Area

Question

### Body

I've been exploring different approaches to streamline API regression testing, especially within modern CI/CD workflows. While working with some tools recently (including one that uses AI to auto-generate regression test cases), I noticed a significant reduction in test maintenance and flakiness.

I’m curious — how do you handle API regression testing in your projects? Do you use tools that support multi-language environments, visual test insights, or codeless automation? Have you tried integrating such systems with GitHub Actions or other CI tools?

Looking to learn from the community’s experiences and share thoughts on what’s working (or not) in this space.

**Comment by samuelreichor** [comment]
@GunashreeRs I explored following solutions: 

1. Writing simple tests with postman and using the Postman Cli. I used a package to write my tests in one place. Unfortunately, the free plan does not support packages in the cli and the pro plan was too expensive for my usage. 

2. Writing tests with Bruno. That was then my way to go. Bruno is an open source alternative to postman and in my experience extremely nice to work with. You can save your tests in your repo and just install the bruno cli in a github action and use the tests to test the api responses. 

Going further, if you want to go this way you may need a public accessible endpoint of your API. I used autodeploy on push to do so. 

This is the job in my github workflow to test everything with bruno: 
```yaml
  deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Wait till deployment is ready
        run: sleep 60s

      - name: Run API Tests
        run: bru run --env stage
        working-directory: tests/queryApiCollection

```
