### DISCUSSION TITLE
Why did this cron job not run today?

### DISCUSSION THREAD

**Discussion by Regenhardt** [community/community#158654] [Actions] [answered]
### Select Topic Area

Question

### Body

We have some workflows for deployment. One deploys the test stage every day with a cron expression of `0 4 * * *`, which works fine.  
Today (2025-05-08) we wanted to deploy live, but it did not run and I had to manually trigger it instead. What's wrong with this cron config? I pushed it last evening, way before the scheduled time.
```
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 08 5 *'  # 4 AM UTC
```
