### DISCUSSION TITLE
Option to move commit-specific comment to PR review comment

### DISCUSSION THREAD

**Discussion by ardaorkin** [community/community#158659] [Pull Requests]
### Select Topic Area

Question

### Body

Hey folks!
Within this [changelog](https://github.blog/changelog/2022-08-04-commit-comments-no-longer-appear-in-the-pull-request-timeline/), people became able to make commit-specific comments but there are cases where people mistakenly add their comments for a specific commit while the real intention is to make the comment as a PR review.

There isn't such option provided to Github users to turn their commit-specific comments to PR review comment but we could make use of such option.

Is there a way for me to help you guys to implement this feature or I can just ask for it?

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by HoeunPichet** [comment]
Currently, GitHub does not provide a built-in option to move a commit-specific comment into a pull request (PR) review comment.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by la-b-ib** [comment]
Your interest in contributing to GitHub by proposing a feature to convert commit-specific comments into pull request (PR) review comments is a great initiative! Based on the context of GitHub’s changelog and development processes, here’s a clear path forward for both requesting the feature and potentially helping implement it.

### Understanding the Issue
- **Background**: As noted in GitHub’s changelog from August 2022, commit-specific comments (added directly to a commit outside a PR) are distinct from PR review comments and don’t appear in the PR timeline to avoid confusion (). However, users sometimes mistakenly add commit comments when they intend to contribute to a PR review, and there’s no native way to convert these comments.[](https://github.blog/changelog/2022-08-03-commit-comments-no-longer-appear-in-the-pull-request-timeline/)
- **Proposed Feature**: A mechanism to move or convert a commit-specific comment into a PR review comment, ideally with a UI option or API endpoint to streamline the process.

### Options to Request or Contribute to the Feature

#### 1. Requesting the Feature
If you want to propose this feature to GitHub without directly contributing code, you can submit a feature request. GitHub encourages community feedback through specific channels:

- **GitHub Community Discussions**:
  - Post your feature request in the GitHub Community Discussions at [https://github.com/orgs/community/discussions](https://github.com/orgs/community/discussions), specifically in the “Feedback” or “Feature Requests” category.
  - Clearly describe the problem: users mistakenly adding commit comments instead of PR review comments, and the lack of a conversion option.
  - Outline the proposed solution: a button or API endpoint to convert a commit comment to a PR review comment, preserving its context (e.g., line number, file, or commit SHA).
  - Reference the changelog (e.g., [GitHub Changelog, August 2022](https://github.blog/changelog/2022-08-04-comments-on-individual-commits-made-outside-a-pull-request-no-longer-appear-in-the-pull-request-timeline/)) to show awareness of the current behavior ().[](https://github.blog/changelog/2022-08-03-commit-comments-no-longer-appear-in-the-pull-request-timeline/)
  - Example post:
    ```
    **Feature Request: Convert Commit-Specific Comments to PR Review Comments**

    **Problem**: Users sometimes add comments on individual commits (e.g., via the commit page) when they intend to contribute to a PR review. These comments don’t appear in the PR timeline (per the August 2022 changelog), causing confusion and lost feedback. There’s no way to convert these to PR review comments.

    **Proposed Solution**: Add a UI option (e.g., a "Move to PR Review" button) or API endpoint to convert a commit comment to a PR review comment, ideally linking it to the relevant PR and preserving its context (file, line, or commit SHA).

    **Use Case**: A reviewer accidentally comments on a commit instead of the PR’s “Files changed” tab. They’d like to move it to the PR review without retyping.
    ```
  - **Pros**: Easy to submit, no coding required, and GitHub’s team may prioritize it based on community upvotes.
  - **Cons**: No guarantee of implementation or timeline, as GitHub prioritizes based on internal roadmaps.

- **GitHub Support**:
  - Submit a feature request via [https://support.github.com/contact](https://support.github.com/contact) under “Feature Request.”
  - Provide your username (`ppankajs007`) and repository details (if applicable) to contextualize your request.
  - **Note**: This is less public than Discussions and may not gain community traction, but it reaches GitHub staff directly.

- **Likelihood of Acceptance**: GitHub is responsive to community feedback (e.g., multiline comment feature added in 2019 after requests,). However, this feature may be considered low-priority unless it gains significant community support, as it’s a niche workflow issue.[](https://stackoverflow.com/questions/48911087/how-to-select-comment-on-a-range-of-lines-in-github-pull-request)

#### 2. Helping Implement the Feature
If you’re interested in contributing to GitHub’s codebase to implement this feature, the process is more involved because GitHub’s core platform is proprietary. However, you can contribute to related open-source components or propose a proof-of-concept. Here’s how:

- **Understand GitHub’s Architecture**:
  - Commit comments and PR review comments are managed via different API endpoints:
    - Commit comments: `/repos/{owner}/{repo}/commits/{commit_sha}/comments` ().[](https://docs.github.com/en/rest/guides/working-with-comments)
    - PR review comments: `/repos/{owner}/{repo}/pulls/{pull_number}/comments` ().[](https://docs.github.com/en/rest/pulls/comments)
  - A conversion feature would likely involve:
    - A new API endpoint or UI action to copy a commit comment’s data (e.g., body, line number, file) to a PR review comment.
    - Validation to ensure the commit is part of the target PR.
    - Updating the PR timeline to include the converted comment.
  - GitHub’s UI is built with Ruby on Rails and JavaScript (React), and the API uses REST and GraphQL (,).[](https://docs.github.com/en/rest/pulls/comments)[](https://docs.github.com/en/rest/guides/working-with-comments)

- **Contribute to Open-Source Components**:
  - GitHub’s core platform isn’t open-source, but tools like the GitHub CLI (`cli/cli`) or Octokit (API client libraries) are. You could propose a feature in these tools to facilitate comment conversion.
  - For example, add a `gh` CLI command like:
    ```bash
    gh pr comment-convert --commit-comment-id <ID> --pull-request <PR_NUMBER>
    ```
  - Steps:
    1. Fork the `cli/cli` repository: [https://github.com/cli/cli](https://github.com/cli/cli).
    2. Create a feature proposal in an issue, describing the command to convert a commit comment to a PR review comment using the API.
    3. Implement the feature in Go, leveraging the existing `gh` CLI codebase. Use the REST API endpoints (e.g., `/repos/{owner}/{repo}/pulls/comments`) to create a new PR review comment based on the commit comment’s data.
    4. Submit a PR to the `cli/cli` repository with your changes.
  - **Pros**: Contributes to an open-source project, potentially influencing GitHub’s roadmap if adopted.
  - **Cons**: Requires coding skills (Go, API knowledge) and approval from maintainers. It won’t directly change GitHub’s UI unless adopted upstream.

- **Prototype a GitHub Action**:
  - Create a GitHub Action to automate converting commit comments to PR review comments using the GitHub API.
  - Example workflow:
    ```yaml
    name: Convert Commit Comment to PR Review Comment
    on:
      issue_comment:
        types: [created]
    jobs:
      convert-comment:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/github-script@v7
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                const commentId = context.payload.comment.id;
                const prNumber = context.payload.issue.number;
                const commitSha = context.payload.comment.commit_id;
                // Fetch commit comment
                const { data: comment } = await github.rest.repos.getCommitComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: commentId
                });
                // Create PR review comment
                await github.rest.pulls.createReviewComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                  body: comment.body,
                  commit_id: commitSha,
                  path: comment.path || '',
                  line: comment.line || 1
                });
                // Optionally delete original comment
                await github.rest.repos.deleteCommitComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: commentId
                });
    ```
  - Steps:
    1. Create a new repository for your GitHub Action.
    2. Implement the above script, triggered when a commit comment is created (or manually via a workflow dispatch).
    3. Publish the Action to the GitHub Marketplace or use it in your repository.
  - **Pros**: Immediate workaround for your use case, shareable with the community.
  - **Cons**: Requires manual triggering or specific comment formatting to identify conversion requests. Doesn’t integrate with GitHub’s UI.

- **Engage with GitHub’s Ecosystem**:
  - Join the GitHub Developer Community (e.g., [https://github.com/orgs/community/discussions/28924](https://github.com/orgs/community/discussions/28924)) to discuss your idea with other developers and GitHub staff.
  - Check for existing issues or PRs in `cli/cli` or `octokit/octokit.rb` related to comment management (e.g.,,).[](https://docs.github.com/en/rest/guides/working-with-comments)[](https://stackoverflow.com/questions/16744069/create-comment-on-pull-request)
  - Propose your feature in a related repository, linking to your Discussions post for visibility.

#### 3. Practical Next Steps
- **Start with a Feature Request**: Post in GitHub Community Discussions to gauge interest and get feedback from other users. This is low-effort and increases the chance of GitHub prioritizing the feature.
- **Prototype a GitHub Action**: If you have coding experience, build a GitHub Action as a proof-of-concept. Share it in your Discussions post to demonstrate feasibility.
- **Contribute to CLI**: If you’re comfortable with Go, propose a new `gh` CLI command in the `cli/cli` repository. This could gain traction with maintainers and indirectly influence GitHub’s core platform.
- **Collaborate with the Community**: Monitor responses in Discussions and engage with other developers who might face the same issue. Collective support can push GitHub to act faster.

### Recommendation
Start by posting a detailed feature request in GitHub Community Discussions, referencing the changelog and clearly explaining the use case. Simultaneously, prototype a GitHub Action to provide an immediate workaround for your team or the Magma community (assuming this relates to your previous question about Magma). If you’re comfortable coding, contributing a `gh` CLI feature is a great way to make a tangible impact, but it requires more effort and familiarity with Go and GitHub’s API.
