### DISCUSSION TITLE
Getting error "docker: command not found" while setting up job

### DISCUSSION THREAD

**Discussion by SohanTirpude** [community/community#158604] [Actions]
### Select Topic Area

Question

### Body

Hello all,

I am trying to run job in container in self-hosted runner but while doing so I am getting "docker: command not found" error while setting up job. 

This is content of my workflow yaml file

```yaml
name: Advanced Workflow

on:
  push:
    branches:
      - main

jobs:
  build-job:
    name: build job
    runs-on: self-hosted
    container:
      image: oven/bun:slim
    outputs:
      build-output: ${{ steps.buildStep.output.buildOut }}
    steps:
      - name: define output variable
        id: buildStep
        run: |
          bunvar=$(bun --version)
          echo "buildOut=$bunvar" >> "$GITHUB_OUTPUT"
  deploy-job:
    name: deploy job
    runs-on: self-hosted
    needs: build-job
    steps:
      - name: test build output
        run: echo ${{ needs.build-job.outputs.build-output }}
```

And this is the complete output of workflow:

```
Current runner version: '2.323.0'
Runner name: 'fedora'
Machine name: 'fedora'
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Error: docker: command not found
```

Can anyone help me out in fixing this issue?

Thank you.

**Comment by brudnak** [comment]
You're encountering the error because your self-hosted runner does **not have Docker installed**, but you're using the `container:` directive in your workflow, which **requires Docker** to run containers.

---

### ✅ Solution: Install Docker on the Self-Hosted Runner

If you're using **Fedora**, run the following commands on the runner machine:

```bash
sudo dnf install -y docker
sudo systemctl enable --now docker
sudo usermod -aG docker $USER
```

Then **log out and log back in**, or **restart the runner service** to apply the group change.

---

### 🛠️ Alternative: Remove the `container:` Block

If installing Docker isn't feasible, you can refactor your workflow to run natively on the host without containers. That means removing this part from your workflow:

```yaml
container:
  image: oven/bun:slim
```

And instead install `bun` directly in your job steps using a script or package manager.

---

Let me know if you want help rewriting the workflow without containers!

**Reply by SohanTirpude** [reply]
Hello @brudnak,

Thank you for the detailed explanation. Well, I don't want to install docker in the self-hosted runner but I do have `podman` installed and I have set the alias docker for podman.

![Screenshot_20250509_131741](https://github.com/user-attachments/assets/b293b097-aad8-4490-9a86-f3202463b80c)

But it is not working with the alias and I can't afford to install docker on my self-hosted machine. Is there any way to use podman instead of docker?

Kindly let me know if you have any idea on this.

Thank you.

**Comment by brudnak** [comment]
Hi @SohanTirpude,

Thanks for the update!

While aliasing `docker` to `podman` works for many CLI tasks, GitHub Actions' `container:` directive expects a Docker daemon (`dockerd`) to manage containers. Podman, being daemonless by default, doesn't fulfill this requirement, leading to compatibility issues.

🔧 **Alternative Approaches:**

1. **Enable Podman's Docker-Compatible Socket:**

   Podman offers a Docker-compatible REST API via a socket. You can enable it with:

   ```bash
   systemctl enable --now podman.socket
   export DOCKER_HOST=unix:///run/podman/podman.sock
   ```

   However, even with this setup, GitHub Actions may still expect a true Docker daemon and behave unpredictably.

2. **Refactor Workflow to Avoid `container:` Directive:**

   Since you have Podman installed, consider removing the `container:` block from your workflow and install necessary tools directly in the job steps.

   Example:

   ```yaml
   steps:
     - uses: actions/checkout@v3
     - name: Install Bun
       run: |
         curl -fsSL https://bun.sh/install | bash
         export PATH="$HOME/.bun/bin:$PATH"
     - name: Run your task
       run: bun install && bun run start
   ```

   This approach allows your workflow to run natively on the host without relying on Docker.
