### DISCUSSION TITLE
Workflow with on: push to protected branch does not trigger under Rulesets

### DISCUSSION THREAD

**Discussion by robertDespegar** [community/community#158777] [Actions]
### Select Topic Area

Question

### Body

Hi GitHub Support,

We’ve encountered a blocking issue where a GitHub Actions workflow with a standard **on: push** trigger does not execute at all when using a **Ruleset (Settings --> Rules --> Rulesets)** on the target branch (main/default). This **does work** when using "classical Branch Rule" (Settings --> Branches)

Context:

We have a workflow in `.github/workflows/check_rebase_before_merging.yml`

It includes the trigger:

```
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
  push:
    branches:
      - main

jobs:
  check-if-branch-is-up-to-date:
    name: check-if-branch-is-up-to-date
    runs-on: ubuntu-latest
    steps:
      - run: echo "Check rebase"

```
Our repository has an active ruleset targeting the main branch.

That ruleset requires the status check: "check-if-branch-is-up-to-date" to pass before allowing pushes or merges into main.

🚫 Problem:
When pushing directly to main, the workflow does not trigger at all.

No workflow run is enqueued.

No execution appears under GitHub Actions.

The push is rejected with:
```
GH013: Repository rule violations found for refs/heads/main.
Required status check "check-if-branch-is-up-to-date" is expected.
```
This creates a deadlock:

GitHub expects a status check that depends on a workflow triggered by on: push, but the workflow will not run until that status check is satisfied.

We have tried:

- [X] Merging the workflow into main via PR.
- [X] Forcing direct pushes.
- [X] Renaming the file and workflow.
- [X] Reconfiguring and removing/re-adding the ruleset.
- [X] Changing job and workflow names.
- [X] Ensuring the workflow file is correctly present and committed in main.

None of these attempts caused the workflow to trigger on push to main.

🧩 Expected behavior:
The workflow should be triggered by a push to main and register the required check properly — especially after it is present and committed to the branch.

Can you please investigate or clarify whether this is a known issue, or provide a workaround? This currently blocks all attempts to meet the ruleset without bypassing protections.

Thank you.
