### DISCUSSION TITLE
How to Create a Cleanup Cache Action

### DISCUSSION THREAD

**Discussion by lexoye** [community/community#158792] [Actions]
### Select Topic Area

Question

### Body

Hi everyone, 

I'm trying to create a cleanup workflow that erases the cache generated by previous workflows, however I'm getting a bad credentials error.

The actions uses the GITHUB_TOKEN which already has writing and reading permissions, and also installs GitHub CLI  since is runned in a self-host worker

```
name: cleanup caches by a branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Add GitHub CLI repository and install
        run: |
          echo "Adding GitHub CLI repository..."
          curl -fsSL https://cli.github.com/packages/rpm/gh-cli.repo | sudo tee /etc/yum.repos.d/github-cli.repo
          sudo dnf -y install gh
          gh --version
          
      - name: Cleanup
        run: |
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')
          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
```

**Comment by Hariprashad-Ravikumar** [comment]
Here’s a concise pattern that works reliably on self-hosted (and GitHub-hosted) runners.

```yaml
name: Cleanup caches when a PR is closed
on:
  pull_request:
    types: [closed]

# 🔑 1. Make sure the default token really has the right scope
permissions:
  actions: write       # needed for `gh cache delete`
  contents: read

jobs:
  cleanup:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Install GitHub CLI
        run: |
          sudo dnf -y install gh
          gh --version

      # 🔑 2. Authenticate gh with the job-scoped GITHUB_TOKEN
      - name: Authenticate gh
        env:
          GH_TOKEN: ${{ github.token }}   # gh looks for GH_TOKEN (or GITHUB_TOKEN)
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      # 🔑 3. List and delete all caches created for this PR branch
      - name: Delete caches created by the PR
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO:  ${{ github.repository }}
          PR_REF:   refs/pull/${{ github.event.pull_request.number }}/merge
        run: |
          echo "Listing caches for $PR_REF"
          ids=$(gh cache list --ref "$PR_REF" --json id --jq '.[].id')
          if [ -z "$ids" ]; then
            echo "No caches found – nothing to do."
            exit 0
          fi
          echo "Deleting caches:"
          for id in $ids; do
            echo "  • $id"
            gh cache delete "$id"
          done
          echo "✅  Done"
```

**What was causing the “bad credentials” error?**

1. `secrets.GITHUB_TOKEN` does **not** exist.
   Use `${{ github.token }}` or simply rely on the automatic `GITHUB_TOKEN` that Actions injects as an environment variable.

2. The GitHub CLI only recognises `GH_TOKEN` (or an interactive login). Exporting the job token to `GH_TOKEN` or running `gh auth login --with-token` gives the CLI a valid credential.

3. When a pull request comes from a fork, the default token is *read-only*. If your workflow must still run for forks, change the trigger to `pull_request_target` (or run the cleanup on your default branch) so you get a token with `actions:write`. Otherwise, the explicit `permissions:` block above is sufficient.

With those tweaks, `gh cache list` and `gh cache delete` succeed without any additional PAT.

**Comment by lexoye** [comment]
Hi @Hariprashad-Ravikumar, thanks for your response.

I've tried using your suggested solution but I'm seeing this error in the 3rd step: Authenticate gh

```
The value of the GH_TOKEN environment variable is being used for authentication.
To have GitHub CLI store credentials instead, first clear the value from the environment.
Error: Process completed with exit code 1.
```

I tried removing the  GH_TOKEN: ${{ github.token }} in the next step but it didn't work.

**Reply by Hariprashad-Ravikumar** [reply]
Hi @lexoye,

 The CLI exits with that message because it **already sees `GH_TOKEN` in the environment**—so calling `gh auth login` again makes it complain.

 **Two easy fixes (pick one):**

 1. **Skip `gh auth login` entirely** and rely on the token that’s already there:

    ```yaml
    permissions:
      actions: write
      contents: read

    - name: Delete PR caches
      env:
        GH_TOKEN: ${{ github.token }}   # gh will auto-auth with this
        GH_REPO:  ${{ github.repository }}
        PR_REF:   refs/pull/${{ github.event.pull_request.number }}/merge
      run: |
        ids=$(gh cache list --ref "$PR_REF" --json id --jq '.[].id')
        for id in $ids; do gh cache delete "$id"; done
    ```

 2. **Keep `gh auth login`, but unset the var right after:**

    ```yaml
    - name: Authenticate and delete
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GH_REPO:       ${{ github.repository }}
        PR_REF:        refs/pull/${{ github.event.pull_request.number }}/merge
      run: |
        echo "$GITHUB_TOKEN" | gh auth login --with-token
        unset GITHUB_TOKEN GH_TOKEN      # prevent the warning
        ids=$(gh cache list --ref "$PR_REF" --json id --jq '.[].id')
        for id in $ids; do gh cache delete "$id"; done
    ```

 (Don’t forget `permissions: actions: write` at the top so the default token can delete caches.)
 With either approach the workflow should run without the “bad credentials”/exit-code 1 error. Hope that clears it up!
