### DISCUSSION TITLE
Alternative to YAML for defining workflows

### DISCUSSION THREAD

**Discussion by krzema12** [community/community#15904] [Actions]
# Problem statement

Currently the only way of defining a workflow is using YAML. It has its drawbacks: lack of typing, no way to extract a common piece of logic, no way to programatically generate a workflow, indent-sensitivity, no auto-complete regarding e.g. actions' inputs, and more. While it works fine with simple workflows, it becomes unmaintainable with more complex ones.

To address it, I came up with an idea to use a general-purpose language to describe the workflows. To leverage the current Actions' API, it could be anything that can produce a YAML. I'm the creator and co-maintainer of GitHub Actions Kotlin DSL library ([repo](https://github.com/krzema12/github-actions-kotlin-dsl), [docs](https://krzema12.github.io/github-actions-kotlin-dsl/)). It works by having Kotlin scripts using the DSL to generate the YAML, and during job runtime the script and the YAML are compared to ensure they are in sync. An example workflow looks like this:

```kotlin
@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:0.15.0")

import it.krzeminski.githubactions.actions.actions.CheckoutV3
import it.krzeminski.githubactions.actions.actions.SetupJavaV3
import it.krzeminski.githubactions.actions.actions.SetupJavaV3.Distribution.Adopt
import it.krzeminski.githubactions.actions.gradle.GradleBuildActionV2
import it.krzeminski.githubactions.domain.RunnerType.UbuntuLatest
import it.krzeminski.githubactions.domain.triggers.Cron
import it.krzeminski.githubactions.domain.triggers.PullRequest
import it.krzeminski.githubactions.domain.triggers.Push
import it.krzeminski.githubactions.domain.triggers.Schedule
import it.krzeminski.githubactions.dsl.workflow
import java.nio.file.Paths

val checkIfWrappersUpToDateWorkflow = workflow(
    name = "Check if wrappers up to date",
    on = listOf(
        Push(branches = listOf("main")),
        PullRequest(),
        Schedule(triggers = listOf(Cron(hour = "1", minute = "0"))),
    ),
    sourceFile = Paths.get(".github/workflows/_GenerateWorkflows.main.kts"),
    targetFile = Paths.get(".github/workflows/check-if-wrappers-up-to-date.yaml"),
) {
    job(
        id = "check",
        runsOn = UbuntuLatest,
    ) {
        uses(CheckoutV3())
        uses(
            name = "Set up JDK",
            action = SetupJavaV3(
                javaVersion = "11",
                distribution = Adopt,
            )
        )
        uses(
            name = "Generate wrappers",
            action = GradleBuildActionV2(
                arguments = ":wrapper-generator:run",
            )
        )
        run(
            name = "Fail if there are any changes in the generated wrappers or their list in the docs",
            command = "git diff --exit-code library/src/gen/ docs/supported-actions.md"
        )
    }
}
```
(source: https://github.com/krzema12/github-actions-kotlin-dsl/blob/fa02380f2b3c7a684ff52831a75f7fabf92284c1/.github/workflows/check-if-wrappers-up-to-date.main.kts)

The DSL library generates the following YAML:

```yaml
# This file was generated using Kotlin DSL (.github/workflows/_GenerateWorkflows.main.kts).
# If you want to modify the workflow, please change the Kotlin file and regenerate this YAML file.
# Generated with https://github.com/krzema12/github-actions-kotlin-dsl

name: Check if wrappers up to date

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
   - cron: '0 1 * * *'

jobs:
  "check_yaml_consistency":
    runs-on: "ubuntu-latest"
    steps:
      - id: step-0
        name: Check out
        uses: actions/checkout@v3
      - id: step-1
        name: Execute script
        run: rm '.github/workflows/check-if-wrappers-up-to-date.yaml' && '.github/workflows/_GenerateWorkflows.main.kts'
      - id: step-2
        name: Consistency check
        run: git diff --exit-code '.github/workflows/check-if-wrappers-up-to-date.yaml'
  "check":
    runs-on: "ubuntu-latest"
    needs:
      - "check_yaml_consistency"
    steps:
      - id: step-0
        uses: actions/checkout@v3
      - id: step-1
        name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - id: step-2
        name: Generate wrappers
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :wrapper-generator:run
      - id: step-3
        name: Fail if there are any changes in the generated wrappers or their list in the docs
        run: git diff --exit-code library/src/gen/ docs/supported-actions.md
```
(source: https://github.com/krzema12/github-actions-kotlin-dsl/blob/fa02380f2b3c7a684ff52831a75f7fabf92284c1/.github/workflows/check-if-wrappers-up-to-date.yaml)

It does fix several issues that one can experience with YAML, but it's not comfortable to integrate with GitHub. Having to maintain both Kotlin scripts and YAMLs introduces friction and complicates the library. It's like one would have to maintain both an application written in Java and the resulting bytecode next to it.

Analogical DSLs could exist in Python, Ruby, JS/TS or whatever language one can think of and find most comfortable. The possibilities this approach opens finally bring fun and flexibility into creating the workflows. Compare it with e.g. Jenkins which adopted Groovy as their pipelines description language.

# Proposed approach

From the users' perspective, they wouldn't probably want to be aware there's some YAML under the hood. That's why, to enable GitHub detect scripts that are _workflow generators_, GitHub could look at `.workflow.` part in the name, plus the fact that the file is executable. If the conditions are met, treat it as a workflow generator i.e. **an executable file that produces the YAML to the standard output**:

![image](https://user-images.githubusercontent.com/3110813/166005512-3822525c-6467-4adb-aa42-bb5aba8b5368.png)

Now there's a question when the workflow generator script should be executed to produce the YAML. I propose having a separate job created implicitly by GitHub that other jobs would depend on. Regarding workers usage quota, it would count as any other job ran by the user. The job would print out the resulting YAML for debugging purposes:

![image](https://user-images.githubusercontent.com/3110813/166007893-1e273a8e-5181-4abe-8439-51a197fa5aaa.png)

An alternative approach would be to have a single entry point for generating YAMLs, e.g. `.github/workflows/init.sh`, where the users could produce the YAMLs to files:

```sh
#!/usr/bin/env sh
kotlin build.main.kts
kotlin update-gradle-wrapper.main.kts
# any technology can be used here
node generate-wrappers.js
echo "YAML wrappers updated"
```

The advantage is that there's no convention on the naming of individual workflow files (`.workflow.` inside is not necessary), which can be understood as a good or bad thing. The exact API here would also depend on when the workflows are now accessed by GitHub, e.g. to evaluate the triggers.

The bottom line is that such generic API makes it very easy to use virtually any programming language - even if not a full-fledged DSL, then a simple script that would e.g. generate repeated piece of YAML. The API is backward-compatible as the standard YAMLs would still be supported.

Please let me know what you think, and what could be a feasible solution from your point of view.
