### DISCUSSION TITLE
Passing dynamic variable in github workflow ${{ }}

### DISCUSSION THREAD

**Discussion by JayWNC** [community/community#159060] [Actions]
### Select Topic Area

General

### Body

on: 
  workflow_dispatch:
    inputs:
      option1:
        type: boolean
      option2:
        type: boolean
      option3:
        type: boolean

jobs:
  trigger-deploy:
    runs-on: self-hosted
    steps:

      - name: Echo selected services
        run: |

          # List of services
          SERVICES=("option1" "option2" "option3")

          # Loop over each service and explicitly reference the inputs
          for service in "${SERVICES[@]}"; do
            # Directly access the input for each service
            if [ "${{ github.event.inputs.$service }}" == "true" ]; then
              echo "$service"
            fi
          done
          
Above config failed with error below 

[Invalid workflow file: .github/workflows/workflow-v3.yml#L60](https://github.com/sre-snsoft/frontend-github-action-test/actions/runs/14990131031/workflow)
The workflow is not valid. .github/workflows/workflow-v3.yml (Line: 60, Col: 14): Unexpected symbol: '$service'. Located at position 21 within expression: github.event.inputs.$service

Can anyone help me with this?

**Comment by pedrocatalao** [comment]
Do it like this:
```
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Example with step-level env
        env:
          MY_VAR: ${{ github.actor }}
        run: |
          echo "The actor is: $MY_VAR"
```
