### DISCUSSION TITLE
Feature Request: Support for Dynamic Templates/Formatting in Issue Forms

### DISCUSSION THREAD

**Discussion by Xeythhhh** [community/community#159165] [Projects and Issues]
### Select Topic Area

Product Feedback

### Feature Area

Issues

### Body

Hi GitHub team,

I'm excited about the new issue forms and their potential to improve issue quality and structure. However, I’ve encountered a limitation: there’s currently no way to define a template or formatting for how user input is rendered in the final issue body.

## Use Case

I'd like to guide users to fill out issues in a structured Markdown format, similar to classic Markdown templates, but with the benefits of form validation and field types. For example, I want to predefine sections and inject user responses into a formatted issue body, such as:

```
## Summary
**User**: [dropdown selection]
**Feature**: [user input]
**Goal**: [user input]

## Description
[user input]

...
```

## Request

Please consider adding support for a template or formatting property that allows us to define how the collected form data is rendered in the final issue. This would combine the best of both worlds: structured, validated input and a readable, consistent issue format.

### Potential example usage

We could add the `template` property to describe how the input is rendered.

```yml
name: New Feature
description: Document a planned new feature
title: "[Feature]: "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 1. Summary
        Please fill in the details below.

  - type: dropdown
    id: user
    attributes:
      label: User
      description: Select a persona for this feature
      multiple: true
      options:
        - Guest
        - Member
        - Admin
      template: |
        ## Summary

        **User**: ${{ user }}
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: What user task is supported by this feature?
      placeholder: e.g. "I want to log in with GitHub to access protected functionality."
      template: "**Feature**: ${{ feature }}"
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: Why is this important, what business goal is supported?
      placeholder: e.g. "Increase security and user access control"
      template: "**Goal**: ${{ goal }}"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the feature.
      placeholder: Planned implementation, design, etc.
      template: |
        ## Description

        ${{ description }}
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define clear pass/fail criteria
      template: |
        ## Acceptance Criteria

        ${{ acceptance_criteria }}
    validations:
      required: true

  - type: textarea
    id: enhancements
    attributes:
      label: Potential enhancements, follow-up, or alternatives
      description: (Optional) Other ideas
      template: |
        ## Potential enhancements, follow-up, or alternatives

        ${{ enhancements }}
    validations:
      required: false
```

Thank you for your consideration!

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
