### DISCUSSION TITLE
Workflows not started when publishing new tag while creating a Release

### DISCUSSION THREAD

**Discussion by gosr** [community/community#159166] [Actions]
We have multiple workflows that run just fine when pushing to the main branch. They are configured like this:

```
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - "release/**"
  workflow_dispatch:
```

However, something broke during the last couple of days:

When creating a new release on the `https://github.com/your/repo/releases/new` page, and choosing to "Create a new tag: <tag> on publish", the tag is pushed just fine to the remote, but *the workflows that are supposed to react on `"*"` tag pushes are not firing anymore*.
