### DISCUSSION TITLE
Composable services or service definitions

### DISCUSSION THREAD

**Discussion by tmc-adept** [community/community#159272] [Actions]
### Select Topic Area

Product Feedback

### Body

At work we have a typescript project which uses yarn monorepo to manage our main project and a number of sub-projects. We have run into an issue in our CI setup. Several steps requires a postgresql service to function, which Actions has a neat mechanism for. The issue is that multiple Reusable Workflows and Composable Actions require instances of postgresql.

We want them to be able to run in parallel, but all of these instances should follow the same definition. At the moment if we change the supported version of postgresql we must update all files with jobs that use postgresql services.

It would be nice if a service could be defined in a single file somewhere and our workflows can then just include it via a similar syntax to Reusable Workflows or Composable Action.

This is just an example of what the syntax could look like:
```yml
  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        using: ./.github/services/ci-postgres.yml
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4

      - name: 'Restore cache and artifacts'
        uses: ./.github/actions/setup

      - name: 'Run integration tests'
        run: yarn workspace ${{ inputs.workspace }} test:integration
```

Instead of defining the postgres service like so every for every job that needs an instance.

```yml
    services:
      postgres:
        image: postgres:17.5-alpine
        env:
          POSTGRES_PASSWORD: <password>
          POSTGRES_USER: <user>
          POSTGRES_DB: <db>
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
```

In our use case we need the service to be created for and closed with the life-cycle of the related job, we just want to avoid repeating this definition across several different files. However, there are also use-cases where a user might want the service container to last longer than a workflow's lifetime.

let's say we have four Reusable Workflows:
- Install
- Build
- Unit Test
- E2E Test

After we have finished the building the project in the Build job, we might want to instantiate the service and seed it with data. Currently, we would need to re-instantiate and re-seed the database service in both Unit Test and E2E Test.

This problem compounds with monorepo setups where there may be many sub-projects that each should have an instance. In our case we have 10~ sub-projects with Reusable Workflows for each of them. It is a pain that we cannot re-use configurations between them.

In summary, I propose a system for "importing" a service clause into a job from a another YAML file, this could be extended to other clauses too, and potentially elevating a service container to the workflow run level instead of the job level (or some limited version thereof).
