### DISCUSSION TITLE
For GitHub workflows, how can you find out the actor that approved the "environment" for a job?

### DISCUSSION THREAD

**Discussion by benlei** [community/community#159342] [Actions]
### Select Topic Area

Question

### Body

Let's say you have something like:

```yaml
name: Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
```

And the `production` environment has a list of required approvers. Once an approver decides to approve the job to run, how can the job access the actor's username?

The primary thing I want to do is audit who ran the workflow, as well as who approved the workflow.
