### DISCUSSION TITLE
Can't Publish to GitHub Package from Action

### DISCUSSION THREAD

**Discussion by jlwa1ker** [community/community#159402] [Actions]
### Select Topic Area

Question

### Body

I'm attempting to publish a package using maven: `maven deploy`
I can publish the jar file from my build using Maven from the command line with the user and token specified in my settings.xml file.
However I cannot do the same from an action script:

```
name: Build and test temperature monitor

on:
  push:
    branches: [ "master", "release" ]
  pull_request:
    branches: [ "master", "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

```
The error I get is:
`Error:  Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.3:deploy (default-deploy) on project tempmon: Failed to deploy artifacts: Could not transfer artifact org.walkermail:tempmon:pom:1.0 from/to github (https://maven.pkg.github.com/jlwa1ker/tempmon): status code: 401, reason phrase: Unauthorized (401) -> [Help 1]`
