### DISCUSSION TITLE
Github Workflow Path Triggers not working as expected

### DISCUSSION THREAD

**Discussion by balinteu** [community/community#159820] [Actions]
### Select Topic Area

Question

### Body

Hello all,

I am new to GH Actions and have a really interesting (to say the least) behaviour among two of my github workflows.

As seen below I have two different GH workflows, which trigger either on  a direct push to the develop branch, or on an active PR to the develop branch, based on some path-ing criteria.

Expected behaviour:
a)

- active PR to the develop branch
- change something under test/src/**
- Workflow1 executes

b)
- active PR to the develop branch
- change something under test/orchestration/**
- Workflow2 executes

What actually happens:
Every time I change something in test/src/** **both** Workflows are executing, same thing happens when I change soething in test/orchestration/ .  
P.S: These changes are done individually. I **only** change something in **one** of those subdirectories not both at once

What I tried:
- deleted all triggers, commited, added them back again - didn't work
- thought it is some caching issue with the PR, closed PR, opened a new one - didn't work
- commented workflow_dispatch in Workflow2, thinking it might be an issue that that is not in the main branch yet - didn't work

Has anyone experience this strange behaviour with GH Workflows, and has any idea what the problem could be?
Any hint whatsoever would be highly appreciated. Thank you!

Workflow1
```
name: Build Images

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'test/src/**'
      - '!test/src/Tests/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'test/src/**'
      - '!test/src/Tests/**'

#Custom permissions set for the GITHUB_TOKEN
permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write

Build
jobs:
  Build:
      environment: Dev
      runs-on: ubuntu-latest
      name: Build Worker Images
      strategy:
        matrix:
          image:
            - dockerfile: /path1/Dockerfile
              name: imageName
              tag: "1.0"
            - dockerfile: /path2/Dockerfile
              name: imageName
              tag: "1.0"
            - dockerfile: /path3/Dockerfile
              name: imageName
              tag: "1.0"
           ........
      steps:
      .......
```

Workflow2
```

name: Deploy Server

on:
  push:
    branches: ['develop']
    paths:
      - "test/orchestration/**"
  pull_request:
    branches: ['develop']
    paths:
      - "test/orchestration/**"
  workflow_dispatch:

#Custom permissions set for the GITHUB_TOKEN
permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write

Deploy Job
jobs:
  DeployDev:
    environment: 
      name: Dev
      url: example.com
    runs-on: ubuntu-latest
    name: Deploy Temporal Server
    steps:
    .........
```
