### DISCUSSION TITLE
Can I log into the server created in an action?

### DISCUSSION THREAD

**Discussion by blackears** [community/community#159953] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm new to actions and trying to debug a workflow.  Is there any way to login to the server I'm creating to examine the files created by the workflow?

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by tw181802** [comment]
Ah gotcha, you can’t log into the runner directly with GitHub Actions, but there are a few solid workarounds:

Flip on debug logging with ACTIONS_STEP_DEBUG=true to get more detailed output.

Drop in some ls or cat commands in the workflow to see what’s getting created.

If you really need shell access, use [action-tmate](https://github.com/mxschmitt/action-tmate)—it lets you SSH into the runner. Just be careful, only use that on private repos.

**Comment by shafi21001** [comment, marked as answer]
In most GitHub Actions workflows, the "server" you're setting up is typically just a short-lived virtual environment (runner) created by GitHub. These runners are spun up fresh for each workflow run and then shut down, so you can't directly "log in" like you would to a persistent server.

However, there are a few effective debugging tricks you can use:

### 🛠️ Techniques to Inspect Workflow Files

- **Use `run:` with debugging commands**  
  Insert steps like `ls`, `cat`, or `tree` to explore the directory structure and contents:
  ```yaml
  - name: List workspace contents
    run: ls -alh ${{ github.workspace }}
  ```

- **Upload artifacts**  
  You can save output files and logs by uploading them as artifacts:
  ```yaml
  - name: Archive results
    uses: actions/upload-artifact@v4
    with:
      name: my-output
      path: ./output-dir/
  ```

- **Use `actions/upload-artifact` for logs**  
  For example:
  ```yaml
  - name: Save debug logs
    run: cat some-log.txt > debug.log
  - uses: actions/upload-artifact@v4
    with:
      name: debug-logs
      path: debug.log
  ```

- **SSH into self-hosted runner (advanced)**  
  If you're running your own server as a self-hosted runner (not GitHub-hosted), you _can_ SSH in and inspect files. But for hosted runners, this isn’t possible by design.

- **Enable verbose logging**  
  Set `ACTIONS_RUNNER_DEBUG` and `ACTIONS_STEP_DEBUG` as secrets to get deeper insights:
  ```yaml
  secrets:
    ACTIONS_RUNNER_DEBUG: true
    ACTIONS_STEP_DEBUG: true
  ```
