### DISCUSSION TITLE
Custom docker action using github registry

### DISCUSSION THREAD

**Discussion by dancardona** [community/community#160029] [Actions] [answered]
### Select Topic Area

Question

### Body

# Question/Bug: Cannot Access Internal Custom Docker Action

## Summary

I have created a custom Docker action and published it to the GitHub Container Registry as an internal package in my organization. However, when trying to use the action in my workflow, I receive "unauthorized" errors, and the action cannot be accessed, even though both the action and the package are marked as internal.

This is the workflow I create to use my custom Docker action for my organization.

```yml
name: Test Custom C# Action - Registry

on:
  push:
  workflow_dispatch:

jobs:
  test_custom_action_job:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Run custom C# action
        id: my_custom_csharp_action
        uses: [owner]/[repository]@[tag]
        with:
          my_input: 'Hello from the main workflow!'

      - name: Use the output from custom action
        run: echo "The random number generated by the custom C# action is ${{ steps.my_custom_csharp_action.outputs.random_number }}"
```

This is the **action.yml**:

```yml
name: 'C# Random Number Action'
description: 'Receives an input and returns a random number.'
inputs:
  my_input:
    description: 'An input string for the action'
    required: true
    default: 'default_input_value'
outputs:
  random_number:
    description: 'A random number generated by the action'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/[owner]/[repo]/[image]:[tag]'
```

## Error message:

```bash
Error response from daemon: Head "https://ghcr.io/v2/[owner]/[repo]/[image]/manifests/[tag]": unauthorized
```

## What I’ve Tried:

- Confirmed the action and the package are both set to internal.
- Used the default GITHUB_TOKEN for authentication in the workflow.
- Checked repository and organization permissions.
- Re-published the Docker image and retried the workflow.

## Steps to Reproduce:

- Create a custom Docker action and publish it as an internal package.
- Reference the action in a workflow within the same organization and same repo.
- Run the workflow and observe the unauthorized error during the docker pull step.

## Questions:

- Are there additional permissions or settings required to use internal Docker actions with internal packages?
- Is there a known issue with internal visibility for custom actions/packages?

## Additional Context:
I'm creating the docker action and use it in the same repository. Also, I follow this [guide](https://learn.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action) but the repo should be public to fully works.

**Comment by AlphaC137** [comment]
### Workflow Configuration

Add authentication steps to your GitHub Actions workflow:

```yaml
steps:
  - name: Authenticate to GitHub Container Registry
    run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
  - name: Run custom C# action
    id: my_custom_csharp_action
    uses: [owner]/[repository]@[tag]
    with:
      my_input: 'Hello from the main workflow!'
```

**Note:** Replace `USERNAME` with your GitHub username, or better yet, use `${{ github.actor }}` for dynamic resolution.

### Package Visibility Settings

This authentication only works if you've published the image with proper visibility settings:

1. Navigate to: `https://github.com/orgs/YOUR_ORG/packages/container/YOUR_IMAGE_NAME/settings`

2. Ensure the following settings:
   - Package is marked as **internal**
   - Under "Access", your repository has been explicitly granted access to the package (especially important for private repositories)

### Publishing the Docker Image

When publishing your Docker image, use the following commands:

```bash
docker tag myimage ghcr.io/OWNER/REPO/myimage:latest
echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
docker push ghcr.io/OWNER/REPO/myimage:latest
```

To debug access issues, consider temporarily making the image public, then revert to internal visibility once you've confirmed the setup works correctly.

**Reply by dancardona** [reply]
Thanks for your answer. I already did that too. It failed because GitHub is pulling all the images before the workflow uses them

![image](https://github.com/user-attachments/assets/ea071b95-2d3b-41ba-a8fe-2790742b929f)

**Reply by AlphaC137** [reply]
which means docker login ghcr.io happens too late to help damn, only 2 suggestions I could make at a point like tis is: Using a Local Dockerfile Instead of GHCR
If the action and workflow are in the same repo, you can skip GHCR entirely:

In your action.yml, use:

```
yaml
Copy code
runs:
  using: 'docker'
  image: 'Dockerfile'
```
Then keep the Dockerfile right next to it in the repo. 

OR

Make the GHCR Image Public (Temporarily or Permanently)
If you really need to use docker://ghcr.io/..., go to:

```
bash
Copy code
https://github.com/orgs/YOUR_ORG/packages/container/YOUR_IMAGE_NAME/settings
```

Make sure:

Visibility is public, OR

The specific repository is granted access under the “Access” section

If you’re not ready to make it public:

Make it public just long enough to test

Once confirmed, tighten back to internal and work on auth-based access


If those two don't work, Let me know, there is another solution that might be a bit longer.

**Reply by dancardona** [reply]
Well, if I got the image public my company probably fires me 😅

Using Dockerfile works, the thing is the performance because it's building the image each run and no caching. So, no matters if I put the image and the action internal, I should use JavaScript/TypeScript?

**Reply by AlphaC137** [reply, marked as answer]
Yeah, getting fired for making a Docker image public is not the kind of CI/CD drama anyone wants.😅 
you’re absolutely right: switching to a Dockerfile avoids the auth mess but kills you on build time since it rebuilds the image from scratch every run, with no caching across workflows. That’s brutal, especially for language runtimes like C# or Java that pull a ton of dependencies.

Switching to Javascript/Typescript? Yes, if performance and reusability matter, and you can tolerate the tradeoffs.

But note that (1) you will lose the ability to run OS-level tooling or use native runtimes like .NET SDK, curl, apt-get, etc. without shelling out in the workflow. (2) You’ll need to transpile TS to JS and commit the compiled files unless you use actions/toolkit which supports TS dev flow. (3) If your logic is tightly tied to the C# ecosystem (e.g., needs .NET), porting to JS might be non-trivial.

But before you abandon Docker altogether, another option is to:

Pre-build the image and push to GHCR

Use a reusable workflow that does docker pull after logging in

You’d bypass the docker:// method and instead run your image manually in a run: step:

```
steps:
  - name: Login to GHCR
    run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  - name: Pull and run the action manually
    run: |
      docker pull ghcr.io/my-org/my-repo/myimage:tag
      docker run ghcr.io/my-org/my-repo/myimage:tag a
```
Yes, it’s outside the “normal” uses: GitHub Actions flow, so you lose the built-in inputs / outputs unless you handle them manually.


You got a choice at least.
