### DISCUSSION TITLE
Required job does not appear (straight) in my PR if they need some other jobs to run.

### DISCUSSION THREAD

**Discussion by emiliengarreau** [community/community#16001] [Pull Requests]
Today, I have multiple workflow files with the job `unit-test` flag as required! However, here is the issue:

For this workflow:

```yaml
name: New tests
on:
  push:
    branches: "master"

jobs:
  do_something:
    name: Test1
    runs-on: ubuntu-20.04
    steps:
      - name: Sleep
        run: sleep 10
    
  unit-test: # required
    needs: do_something
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Echo
        run: echo "yolo"  
```
`unit-test` will appear in the PR workflows only after `do_something` is over. It means that my users can merge their PR even though  `unit-test` is required. If we wait for unit-test to start then the PR is locked.

Is it a bug or is it normal and I have been poorly designing my workflows ?
