### DISCUSSION TITLE
GH Actions container.options can't resolve username, but Docker can

### DISCUSSION THREAD

**Discussion by cpboyd** [community/community#160025] [Actions]
### Select Topic Area

Bug

### Body

I'm using this:
```
jobs:
  argocd:
    runs-on: infra-runner-set
    container:
      image: quay.io/argoproj/argocd:v3.0.3
      # https://docs.github.com/en/enterprise-cloud@latest/actions/sharing-automations/creating-actions/dockerfile-support-for-github-actions#user
      # https://github.com/actions/checkout/issues/1575#issuecomment-2536435128
      # TODO: `--user root` didn't work; had to specify UID instead.
      options: --user 0
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
```

Docker CLI is able to resolve the username via:
```
docker run --rm -it --entrypoint /bin/sh --user root quay.io/argoproj/argocd:v3.0.3
```

The docs only lists `--network` and `--entrypoint` options as not supported: https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container#setting-container-resource-options
