### DISCUSSION TITLE
Reusable workflow does not share result with next job

### DISCUSSION THREAD

**Discussion by utdrmac** [community/community#160129] [Actions]
### Select Topic Area

Question

### Body

I've created a reusable workflow called 'linters.yml', which has 1 job with several steps to checkout the repo, setup the python environment, generate our tool, then run several linters/checkers. This works fine.
There's another action/workflow that says 'on pull_request: branches: main', execute 1 job, which is the reusable one. This works. 

There is one more action/workflow that is to be executed against the main branch, after a PR is merged-closed.

```
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  generate_and_lint:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/linters.yml

  update-gh-pages:
    runs-on: ubuntu-latest
    needs: generate_and_lint
    steps:
     - run: |
       git checkout --track -b gh-pages origin/gh-pages
       ... <more stuff>
```

The first job, 'generate_and_lint' worked successfully, but the next job 'update-gh-pages' failed on the first run line because there was no repo. Whatever "result" that happened in 'generate_and_lint' did not carry over to the next job, as expected.

I expected all of the "jobs" to share the same runner/container instance, allowing for whatever results from a previous job to be visible/shared/carried on with the next job.

Defeats the purpose of reusable workflows, in my opinion, if you can't share the job results downstream.

Is there a way to accomplish this?
