### DISCUSSION TITLE
Accessing deployment environment's variables in reusable jobs

### DISCUSSION THREAD

**Discussion by ckeller-microstar** [community/community#160132] [Actions] [answered]
### Select Topic Area

Question

### Body

As discussed in [another post](https://github.com/orgs/community/discussions/160128), my goal is to have a build+upload job and a separate deploy job, but be able to either run them separately (for production) or chained together (for development). My first approach was to have exactly two `workflow_dispatch` jobs, with the build+upload job taking a boolean input to optionally trigger the deploy job. I attempted that through `repository_dispatch` but hit a wall and switched gears.

Now what I'm attempting is separated into five jobs: two reusable jobs to do the work of build+upload and deploy, then three `workflow_dispatch` jobs for build+upload, deploy, or both. The issue I'm facing now is that I'm using [deployment environments](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-environments-for-deployment) to store context variables, and can't figure out the correct way to communicate that from the top-level job to the reusable job.

If I put `environment` in the top-level job, it's unexpected:

```yaml
name: Build and Upload
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
jobs:
  upload:
    uses: ./.github/workflows/reusable-upload.yml
    environment: ${{ inputs.environment }}
```

```
The workflow is not valid. .github/workflows/upload.yml: Unexpected value 'environment'
```

However, if I pass the environment name down as a string, it doesn't seem like the reusable job is able to access the environment context:

```yaml
name: Build and Upload
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
jobs:
  upload:
    uses: ./.github/workflows/reusable-upload.yml
    with:
      environment: ${{ inputs.environment }}
```

```yaml
name: "[Reusable] Build and Upload"
on:
  workflow_call:
    inputs:
      environment:
        type: string
jobs:
  upload:
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Set up AWS Credentials
        with:
          aws-region: ${{ vars.AWS_REGION }}
```

```
Input required and not supplied: aws-region
```

I'm at a loss as to how use reusable jobs with deployment environment variables.

**Comment by ckeller-microstar** [comment]
I think I figured this out. What I didn't include in the post is that the job I was testing was not only triggered by `workflow_dispatch` but also by `push: branches: main`. When triggered by push, there are no inputs, and so even though the `environment` input had a default, that wasn't used. So `environment` was null, and subsequently passed to the reusable job as null.

When I invoke the job level job like this, it works:
```yaml
name: Build, Upload and Deploy
on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: dev
jobs:
  upload:
    uses: ./.github/workflows/reusable-upload.yml
    with:
      environment: ${{ inputs.environment || 'dev' }}
```
