### DISCUSSION TITLE
Workflow set to trigger on tag push not triggering

### DISCUSSION THREAD

**Discussion by ITR13** [community/community#160397] [Actions]
### Select Topic Area

Question

### Body

I have this workflow intended to automatically update a specific branch if a tag starting with "version/" has been pushed, but the github action page shows that the tag never triggers no matter how many different tags starting with version I manually push to the repo:
```
name: Merge “version” tags into release

on:
  push:
    tags:
      - 'version/**'

permissions:
  contents: write

jobs:
  merge-to-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out release branch
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: Fast-forward release to the tag commit
        run: |
          git fetch --no-tags origin "${GITHUB_REF}"
          git merge --ff-only --no-edit "${GITHUB_REF}"

      - name: Push updated release
        run: git push origin release
```

I've also tried:
```
on:
  push:
    tags:
      - 'version/*'
```
and
```
on:
  push:
    tags:
      - version/*
```
but neither worked.

I'm not sure why github can't just tell me if the yaml can't be parsed or what workflows it thinks it should trigger on. Would appreciate any insight anyone might have on why it's not triggering.
