### DISCUSSION TITLE
Checkout failing due to git-lfs not being found

### DISCUSSION THREAD

**Discussion by ricardo-noyolalozano** [community/community#160433] [Actions]
Pretty much the title. The runner that is running the jobs definitely has git-lfs installed and the action is working most of the time. I've noticed that it has stopped working after I started using containers to run some jobs. 

`Hook already exists: pre-push

	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
	git lfs pre-push "$@"

```
To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.
Error: The process '/usr/bin/git' failed with exit code 2`
```

I think something is breaking after I run the same action in the container (which works) and then try running the action on another workflow without the container. Not sure what could be happening and am having issues finding anything online that describes the same issue I'm facing.

**Comment by kdkavanagh** [comment]
Curious if you ever found a solution for this.  It's unclear where those LFS git hooks are coming from on checkout.  For my repo, users have no issues if they clone locally - This only seems to happen in GHA

**Reply by ricardo-noyolalozano** [reply]
not much of a solution but a workaround, I run this line before each one of my workflows:
`git lfs update --force || true`

**Comment by pidec05** [comment]
Hi, is there any permanent solution for this issue?

**Comment by raythurnvoid** [comment]
I also have to install lfs manually, we use the playwright image

```
e2e_tests:
    runs-on: ubuntu-latest-4-cores
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    needs: [skip_e2e_for_hotfix]
    if: ${{ needs.skip_e2e_for_hotfix.outputs.skip_e2e == '' }}
    steps:
      - name: Install git-lfs
        run: |
          apt-get update && apt-get install -y git-lfs
          git lfs update --force || true

     - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          lfs: true
          submodules: true

      # Required to run git commands in the container
      - name: Configure git
        run: git config --global --add safe.directory "$(pwd)"

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
```
