### DISCUSSION TITLE
How can we differentiate between release and pre-release at the git repo level?

### DISCUSSION THREAD

**Discussion by mhever** [community/community#160435] [Actions] [answered]
We've nightly builds, building the latest images based on the ubuntu20 / ubuntu22 / win22 release tags. At the git repo level, how can we know if we're dealing with a release or a pre-release. Probably I'm missing the obvious. Recently we were fooled by https://github.com/actions/runner-images/commit/d08c3d22
<img width="548" alt="image" src="https://github.com/actions/runner-images/assets/116094080/81b289ab-ed06-433d-aae4-1d1d3840a8f6">
we built an image based on this tag, but 2 days later when we tried to check what's actually inside the release, the tag was gone.

**Comment by zioalex** [comment]
Good point,
we have the same problem.
Any guidance on how to find release or pre-release from git or in another way?

**Reply by DevOpsAzurance** [reply, marked as answer]
I use the following api:

https://api.github.com/repos/OWNER/REPO/releases/latest

To get the latest release. As for a pre-release, I'm not sure.

**Reply by mhever** [reply]
Thanks a lot! Apparently https://[api.github.com/repos/actions/runner-images/releases](https://api.github.com/repos/actions/runner-images/releases) lists all the information we need, including a bool flag prerelease. Perfect!

**Reply by erik-bershel** [reply]
Hey @mhever!
I have a couple of comments that may be useful to you:
- the prerelease tag means that we have started rolling out a new image, but it is far from a fact that your build will end up on the new runner;
- release branches are not repeatable, which means that if you are trying to build your own runners, they will not be 100% identical to the specified version of the GitHub or AzDO runners;
- with every minute after the prerelease, the chance that the code attached to the branch will stop executing due to the difference between the release branch and the main increases.

**Comment by Fran-Rg** [comment]
For myself in the future and anyone looking to have a workflow for prerelease and release working in every condition:

- draft -> prerelease == triggers on-prerelease
- draft -> release  == triggers on-release
- prerelease -> release  == triggers on-release
- prelease  == triggers on-prerelease
- release  == triggers on-release

Here's the pre-release workflow. NOTE: the if is required, the workflow will be called when creating a release directly but skipped :
```
---
name: on-prerelease
on:
  release:
    types:
      - published

jobs:
  test:
    if: github.event.release.prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |-
          echo "I am a pre-release"
```

and the release workflow:
```
---
name: on-release
on:
  release:
    types:
      - released

jobs:
  test:
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |-
          echo "I am a release"
```
