### DISCUSSION TITLE
Webhook path for Autoscaling

### DISCUSSION THREAD

**Discussion by vlatko-b** [community/community#160448] [Actions]
I have the webhook server exposed with public ingress but seems like there are multiple endpoint paths and I am not sure what should be set in Github / Organization Webhooks setup

````
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-service
  annotations:
    alb.ingress.kubernetes.io/group.name: demo.public
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /validate-actions-summerwind-dev-v1alpha1-runner
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '240'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
spec:
  ingressClassName: alb
  rules:
    - host: mycompany.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: webhook-service
                port:
                  number: 443
````

Setting it to
https://mycompay.com/validate-actions-summerwind-dev-v1alpha1-runnerdeployment

I get
````
{"kind":"AdmissionReview","apiVersion":"admission.k8s.io/v1","response":{"uid":"","allowed":true,"status":{"metadata":{},"code":200}}}
````

But I do not see any changes in the number of runners

````
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runner-experiment
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: RunnerDeployment
    # # In case the scale target is RunnerSet:
    # kind: RunnerSet
    name: github-runner-experiment
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "15m"
````

Using Kustomize and AWS EKS.

I use one of the endpoints defined in   
- https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.26.0/actions-runner-controller.yaml
as healthcheck. Maybe there is a better option.
