### DISCUSSION TITLE
Better UX for generating primary keys using bespoke inputs for hash files

### DISCUSSION THREAD

**Discussion by PaulRBerg** [community/community#160472] [Actions]
## Problem

Generating the primary key is a little difficult when a lot of files need to be hashed. Here's an example from our repo:

```yml
key: foo-${{ hashFiles('yarn.lock') }}-${{ hashFiles('/**/*.{js,json,jsx,ts,tsx}') }}
```

That's a rather verbose line of code.

## Solution

Since the vast majority of users need to use `hashFiles`, enable a new input parameter called `key-hash-files` (name TBD) that allows users to specify paths an an array, e.g.

```yml
- uses: "actions/cache@v4"
      id: "cache-step"
      with:
          key-prefix: "foo-"
          key-hash-files:
              - `yarn.lock`
              - `/**/*.{js,json,jsx,ts,tsx}`
```

And then, each input in the array would be passed as an input to `hashFiles`, and the resulting hash would be added to the key name. Each hash would be prefixed by `-`.
