### DISCUSSION TITLE
Ubuntu 24.04 Noble Docker Image

### DISCUSSION THREAD

**Discussion by dniasoff** [community/community#160468] [Actions]
Hi,

I am using the actions-runner-controller and gha-runner-scale-sets to run action-runners on Kubernetes.

The default docker images used by the runners are hosted in this repo - ghcr.io/actions/actions-runner

They are all based on Ubuntu 22.04.

Are there any plans to upgrade to 24.04? Can I easily build my own 24.04 image? Where is the Dockerfile  used to build the standard image?

Feeling a bit stupid as I should be able to work this all out myself!

Thanks

Daniel

**Comment by rekha-prakash-maersk** [comment]
I have the same question and having the same platform setup, since the enterprise runners now offer 24.04, I am looking to upgrade my selfhosted runner to 24.04 as well to have a smooth transition between them.

**Comment by cmckeen** [comment]
I have the same questions. With the [impending update](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/) of the ubuntu-latest label to use Ubuntu 22.04, what is the plan for the next release of the runner? Will this be a new major version upgrade? Is this coming soon?  Will the update to a new major version of Linux require an update to self-hosted runners within 30 days?

**Comment by gthomson31** [comment]
any update on this?

**Comment by joshua-clayton** [comment]
I made a pull request for this. https://github.com/actions/runner/pull/3771

**Reply by oded-eid-sequentech** [reply]
Hey @joshua-clayton, I tried you suggested docker file, built it and uploaded to a my docker repo. but the runner shows:
'Waiting for docker' - for a long time. 
It can't communicate with the docker:dind from some reason. as far as I understand.

Did you encounter this? Maybe you can tell how to turn on better logging?

I used this yaml:
```
githubConfigUrl: "https://github.com/mycompany"
githubConfigSecret: github-token

runnerScaleSetName: "arc-runner-set"

controllerServiceAccount:
  namespace: arc-systems
  name: my-servoce-account-name

minRunners: 0
maxRunners: 30

runnerGroup: "default"

containerMode:
  type: "dind"

template:
  spec:
    containers:
      - name: runner
        image: my-personal-repo/actions-runner:ubuntu-24.04-v2
        imagePullPolicy: Always
```
