### DISCUSSION TITLE
Setup w. custom images beings to fail after a period

### DISCUSSION THREAD

**Discussion by andershagbard** [community/community#160421] [Actions]
Hi.

I have a setup using a custom image. My setup has worked perfectly for about 2 months, and now it won't spin up any pods anymore. This is not the first time this has happened.

I am using Digital Ocean Kubernetes. All pods resource usage are low, and no way near maxing.

My custom images looks like this:

Dockerfile
```dockerfile
FROM ghcr.io/actions/actions-runner:2.322.0

USER root

RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - 
RUN apt-get install -y nodejs
RUN npm install --global yarn
RUN npm install --global pnpm

RUN chown -R 1000:1000 "/usr/bin/npm"

USER runner
```

values.yaml
```yaml
maxRunners: 6
minRunners: 2

template:
  spec:
    containers:
      - name: runner
        image: me/my-image:latest # Not the actual path
        command: ["/home/runner/run.sh"]
```
