### DISCUSSION TITLE
How to do git config to use PAT token?

### DISCUSSION THREAD

**Discussion by keepsimple1** [community/community#160494] [Actions] [answered]
Hi,
I'm reading this part of the README: 
```
    # Personal access token (PAT) used to fetch the repository. The PAT is configured
    # with the local git config, which enables your scripts to run authenticated git
    # commands. The post-job step removes the PAT.
```
I cannot find out how I can configure with the local git config so that it will use the PAT.  I tried to add the following line in the workflow before `actions/checkout@v2`:
```
   - name: Git config
     run: git config --global user.email <my-service-account-email>
   - name: Checkout
     uses: actions/checkout@v2
     with:
       token: ${{secrets.MY_TOKEN}}
```
It did not help. The Checkout action did not use the token for git checkout. What did I miss? Thanks.
