### DISCUSSION TITLE
ArgoCD: unable to deploy CRDs of gha-runner-scale-set-controller

### DISCUSSION THREAD

**Discussion by andrei-dascalu** [community/community#160445] [Actions]
Hi,

I have an application as such

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tooling
  source:
    chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.7.0
    helm:
      releaseName: eks-gha-runner
      values: |
        tolerations:
        - key: "environment"
          operator: "Equal"
          value: "misc"
          effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: github
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m

```

When deploying the application, one of the api extensions fails with `CustomResourceDefinition.apiextensions.k8s.io "autoscalingrunnersets.actions.github.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

I've reproduced this manually by running `helm template arc --namespace "github"  oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller | kubectl apply -f`, seems that while helm can install the chart, applying with kubectl in the way that ArgoCD does - won't work.

Is there a way to go around the issue?

**Comment by ervinb** [comment]
The only "solution" is to recreate the resource, either by hand (Sync -> [x] Replace) or by [adding the following annotation](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes) to the CRD:

```yaml
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
```

The problem happens because by default ArgoCD runs `kubectl apply` on the resources, which then places the whole to-be-updated manifest into the `kubectl.kubernetes.io/last-applied-configuration` annotation.
