### DISCUSSION TITLE
How to use EKS Pod Identity for AWS Resources

### DISCUSSION THREAD

**Discussion by BeyondEvil** [community/community#160418] [Actions]
You'll need to create an AWS IAM Role with the permissions you need for whatever resource you're trying to work with.

You'll also need to create an EKS Pod Identity Association with the runner's ServiceAccount (as of this writing called `<runnerScaleSetName>-gha-rs-no-permission`) in the namespace of the runners.

Then you can use the CLI either by installing in on the runner, or if you're using DIND mode the AWS CLI image:

```yaml
name: AWS Resources

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  direct:
    runs-on: <runnerScaleSetName>
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - run: aws sts get-caller-identity

  indirect:
    runs-on: <runnerScaleSetName>
    container:
      image: amazon/aws-cli:latest
      env:
        AWS_CONTAINER_CREDENTIALS_FULL_URI: http://169.254.170.23/v1/credentials
        AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
      volumes:
        - /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token:/var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
    steps:
      - run: aws sts get-caller-identity
```
