### DISCUSSION TITLE
Not able to get correct CPUs from runner container

### DISCUSSION THREAD

**Discussion by arpanadhi** [community/community#160432] [Actions]
Hi,

I have installed ARC on Kubernetes cluster recently. Here is my runner scale set :

```
   - name: runner
      image: <image url>
      command: ["/home/runner/run.sh"]
      env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
      resources:
        requests:
          cpu: 6000m
          memory: 32Gi
        limits:
          cpu: 6000m
          memory: 32Gi
       .
       .
       .
       .
          
```
          
As you can see, I have mentioned requested CPU is 6 and also set the `limits` cpu as 6. When I am running Python `multiprocessing.cpu_count()`, I am getting CPUs of underlying physical node i.e. 56. 
 
 Can someone please help me to get correct cpu number of the container? Why I am seeing 56 CPUs instead of 6?
 
 Here is my Dockerfile config:
 
```
FROM almalinux:latest

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG RUNNER_VERSION=2.323.0
ARG RUNNER_CONTAINER_HOOKS_VERSION=0.7.0
ARG DOCKER_VERSION=28.0.1
ARG BUILDX_VERSION=0.21.2
 
```
