### DISCUSSION TITLE
How to pass multiple options when used in a reusable workflow

### DISCUSSION THREAD

**Discussion by ghost** [community/community#160495] [Actions]
We are checking for a way to pass multiple option to the `actions/checkout@v4`, when used in a reusable workflow.

Something like following
```yaml
jobs:
  docker:
    name: Docker
    uses: ./.github/workflows/docker.yml
    with:
      docker_file: Dockerfile
      dockerhub_repo: account/repository
      checkout: |
        repository: ''
        ref: ''
        token: ''
        path: ''
        clean: ''
        fetch-depth: ''
        fetch-tags: ''
    secrets: inherit
```

Is there a way to pass a list of options in that way?
