### DISCUSSION TITLE
Service container command arguments

### DISCUSSION THREAD

**Discussion by tylde** [community/community#160506] [Actions]
Hey, I haven't found any suitable solution for passing arguments to service container.
For example I would like to use `trufflesuite/ganache:latest` image as job's service container with `--wallet.deterministic` option.

Unfortunately there is no such thing as `jobs.<job_id>.services.<service_id>.command` option to achieve that:
```
# workflow.yml
jobs:
  job:
    services:
      ganache:
        image: trufflesuite/ganache:latest
        ports:
          - 8545:8545
     steps:
     # ...
```

In `docker-compose.yml` file I can use `command` to pass arguments:
```
  # docker-compose.yml
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - 8545:8545
    command:
      --wallet.deterministic
```

Are you planning to add this feature?

**Comment by TroyKomodo** [comment]
I am confused how this feature was not implemented on release.
It might just be most common thing to do. Kinda 🤯

**Reply by tiagoliveira9** [reply]
True, it doesn't make sense.

**Reply by jaeyson** [reply]
It's already 2 years and I still can't see the `command` in workflow syntax docs :(

**Comment by abe-winter** [comment]
linking back to the open PR for this feature in case it bumps it up the queue
https://github.com/actions/runner/pull/1152

implementing it is fairly simple (there's already an EntryPointArgs in the DockerCreate wrapper, it's just not populated from yaml)

**Reply by binhpageai** [reply]
why github action not support it ? :'(

**Comment by kherock** [comment]
The fact that customizing the `[OPTIONS]` portion of docker create is supported and not the commands of the image being tested was very surprising (and disappointing) to find out. The lack of support for this kills most of my potential use of the `jobs.<job_id>.services.<service_id>` syntax 😔

**Comment by ericsciple** [comment]
Hi everyone 👋

Thank you for all the feedback here and across the related threads. Building custom wrapper images just to pass flags to a database or start a service shouldn't be necessary. We've been working on a solution and would love your input.

### The problem

Service containers have no way to pass arguments to the image entrypoint. The `docker create` command expects args after the image name:

```
docker create [OPTIONS] IMAGE [COMMAND] [ARG...]
```

Every key in the YAML maps to Docker options *before* the image name. Nothing maps to `[COMMAND] [ARG...]` after it:

```yaml
services:
  <service_id>:
    image: string
    env: { key: value }
    ports: [ string ]
    volumes: [ string ]
    options: string      # Maps to [OPTIONS]
                         # Nothing maps to [COMMAND] [ARG...]
```

This forces workarounds for common scenarios like passing `--sql_mode` to MySQL or starting MinIO with `server /data`.

### What we're proposing

We're adding two new keys to service containers: `command` and `entrypoint`.

**Passing flags with `command`** — most scenarios only need `command`. The image already has the right entrypoint, you just need to pass flags:

```yaml
services:
  mysql:
    image: mysql:8
    command: --sql_mode=STRICT_TRANS_TABLES --max_allowed_packet=512M
    env:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
```
Resulting `docker create`:

```
docker create --name <id> --label <label> --network <network> --network-alias mysql -e MYSQL_ROOT_PASSWORD=test -p 3306:3306 mysql:8 --sql_mode=STRICT_TRANS_TABLES --max_allowed_packet=512M
```
**Overriding `entrypoint`** — when you need to swap the image entrypoint, use `entrypoint` (with or without `command`):
```yaml
services:
  etcd:
    image: microbox/etcd:2.1.1
    entrypoint: etcd
    command: >-
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
    ports:
      - 2379:2379
```

Resulting `docker create`:

```
docker create --name <id> --label <label> --network <network> --network-alias etcd --entrypoint "etcd" -p 2379:2379 microbox/etcd:2.1.1 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379
```

The names and behavior match Docker Compose, so if you've written a `docker-compose.yml` this should feel familiar.

**Key points:**

- **Additive, opt-in** — existing workflows continue to work unchanged
- **Service containers only** — scoped to databases, caches, emulators, and other sidecars
- Overriding entrypoint via `options: --entrypoint <binary>` continues to work, but `entrypoint` is more discoverable

### Does this address your needs?

We think this covers the core scenarios (database flags, service configuration, custom entrypoints) but want to make sure we're not missing anything. Does this solve your use case, or is there a scenario where you'd still need a wrapper image?

Thanks again for all the feedback and patience. We're looking forward to hearing your thoughts!

— The GitHub Actions Team

**Reply by petelah** [reply]
I believe this does!

**Reply by brendanfubo** [reply]
This feature is critical for one of our (proposed) workflows. Is there a timeline on when it might be completed?

**Reply by maekind** [reply]
Yes, it does. That would be great! When do you plan to roll out this feature?

**Reply by ericsciple** [reply]
List your repo here or email me ericsciple at github dot com (mention service containers) and I will turn the feature flag on for your repo, for early validation. Rolling out broadly within a week otherwise. Requires a 2.333.0 runner which is fully rolled out now.

**Reply by maekind** [reply]
I sent you an email with related info @ericsciple . 

Thanks in advance.

**Reply by ericsciple** [reply]
@maekind i didnt receive an email. I checked spam folder too 🤔

**Reply by ericsciple** [reply]
I will just roll out the feature flag broadly tomorrow.

**Reply by maekind** [reply]
Thanks @ericsciple ! It's working as expected 🙏🏻

**Reply by ericsciple** [reply]
The feature flag is fully rolled out now for everyone

**Reply by ericsciple** [reply]
Will update autocomplete in the web editor and VSCode. Also, docs updates and changelog landing soon.

**Comment by jbebe** [comment]
While it's not available, I found a good old "mysql escape" solution. This is the service start command:

```Shell
/usr/bin/docker create \
    --name ... \
    --label ... \
    --network ... \
    --network-alias ... \
    $OPTIONS \
    -e GITHUB_ACTIONS=true -e CI=true ...
```

And this is the options value:

```yml
services:
  <imagename>:
    image: <imageurl>
    options: >-
      -e GITHUB_ACTIONS=true -e CI=true <imageurl>
      <imagename> --param1 --param2 --param3 #
```

This way when the options string is injected into the command, we can change the order of arguments with it and then comment out every remaining arguments.
