### DISCUSSION TITLE
dynamically use a normal runner in a reusable workflow, for example ubuntu-latest or a group of runners

### DISCUSSION THREAD

**Discussion by jmirandasq** [community/community#160515] [Actions]
I am trying to make a workflow work that can receive the name of a runner group through an input, but if nothing is received through the input, use the ubuntu-latest label. Is this possible? I come from azure devops and with expressions I could modify the yaml and I can't find how to do it on github.

```yaml
pool: 
    ${{ if eq(parameters['agenteSiste'], 'none') }}:
      vmImage: ${{parameters.agenteAzure}}
    ${{ else }}:
      name: ${{parameters.agenteSiste}}
```
This is how I did it in Azure Pipelines
