### DISCUSSION TITLE
How push back some changes to Pull request?

### DISCUSSION THREAD

**Discussion by cawa-93** [community/community#160508] [Actions]
I would like to create a workflow that would come into each PR and format the code according to the code style. On paper, it looks simple: pull PR, run formatting, push any changes.
My workflow:
```yaml
on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
      - run: npm run format --if-present
      
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git diff-index --quiet HEAD || git commit -m "style: format code"
          git push
```
And it works great for `push` events. However, I get an error in `pull_request` events:
```
[detached HEAD 36717a0] style: format code
 1 file changed, 1 insertion(+), 1 deletion(-)
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Process completed with exit code 128.
```
I don't understand what caused this error, and how should I initialize the workflow to be able to push changes back to PR

**Comment by motss** [comment]
Did you try `git push origin HEAD:${{ github.head_ref }}`?

**Comment by motss** [comment]
@cawa-93 I'd like to leave this comment here for future reference for all the folks who wants to commit then push changes directly to the working branch within Github Actions.

Key Takeaways:

1. Checkout with a defined `ref`:

   This is necessary because GitHub Actions checks out in detached HEAD mode, meaning it doesn’t check out your branch by default.

   ```yml
     uses: actions/checkout@v4
     with:
        ref: ${{ github.head_ref }}
   ```

1. Set Up Git with `user.name` and `user.email`:

   You can use the [Github Actions bot](https://api.github.com/users/github-actions%5Bbot%5D)https://[api.github.com/users/github-actions%5Bbot%5D](https://api.github.com/users/github-actions%5Bbot%5D), read [here](https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token) for more details.

   ```yml
   git config user.name "github-actions[bot]" # This is required for a git push
   git config user.email "41898282+github-actions[bot]@users.noreply.github.com" # This is required for a git push
   ```

# Sample workflow

```yml
name: Push to PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  push-to-pr:
    name: Push to PR
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Required

      - name: Setup Git # Required
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          echo 'test' > test.md
          git add .
          git commit -m 'chore: new change'
          git push
```
