### DISCUSSION TITLE
Service container command arguments

### DISCUSSION THREAD

**Discussion by tylde** [community/community#160507] [Actions]
Hey, I haven't found any suitable solution for passing arguments to service container.
For example I would like to use `trufflesuite/ganache:latest` image as job's service container with `--wallet.deterministic` option.

Unfortunately there is no such thing as `jobs.<job_id>.services.<service_id>.command` option to achieve that:
```
# workflow.yml
jobs:
  job:
    services:
      ganache:
        image: trufflesuite/ganache:latest
        ports:
          - 8545:8545
     steps:
     # ...
```

In `docker-compose.yml` file I can use `command` to pass arguments:
```
  # docker-compose.yml
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - 8545:8545
    command:
      --wallet.deterministic
```

Are you planning to add this feature?
