### DISCUSSION TITLE
Github Actions only triggers on default branch.

### DISCUSSION THREAD

**Discussion by MerNat** [community/community#160572] [Actions] [answered]
Is there a way Github actions can trigger an event on a specific action (example push/pull request) to a non-default branch?

**Comment by peaceiris** [comment]
We can switch to another branch with the `ref` input.

Here is an example workflow:

- default branch: master
- target branch: develop

```yaml
- uses: actions/checkout@v2
  with:
    # The branch, tag or SHA to checkout. When checking out the repository that
    # triggered a workflow, this defaults to the reference or SHA for that event.
    # Otherwise, defaults to `master`.
    ref: 'develop'

- uses: actions/your-action@v1
```

**Reply by MerNat** [reply]
In that case, your Github action does the job on another branch but still triggers on "master" or the default branch. What I want is for Github's actions to trigger or run if a push or pull request event fired on a different branch.

**Reply by peaceiris** [reply]
I got it. We can use the `branches`.

```yaml
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
```

https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

**Reply by MerNat** [reply]
@peaceiris I tried similar Github action YAML. Unfortunately, I couldn't tell whether it's a bug or what. Github actions can only trigger on master or the default branch.

**Reply by okozachenko1203** [reply]
I am facing the same thing.
Is this a bug?

**Reply by annashcherbina** [reply]
Same issue -- is there a resolution for this?

**Reply by rigazilla** [reply]
let me join the band. same for me

**Reply by rigazilla** [reply]
After a better reading of https://docs.github.com/en/actions/reference/events-that-trigger-workflows specially the last part, seems that the `./github/workflows/*` must be present in all the involved branches in order to make things work as I expected

**Comment by stajilov** [comment]
What would be a walkaround for this then?

**Comment by manasesjesus** [comment, marked as answer]
You need to specify the events and branches that will trigger your action:
```yml
on:
  # Set your workflow to run on push events to the develop and all feature branches
  push:
    branches:
      - develop
      - feature/*
  # Set your workflow to run on pull request events that target the main branch
  pull_request:
    branches: 
      - main
```
