### DISCUSSION TITLE
GitHub Actions Checkout submodules doesn't work

### DISCUSSION THREAD

**Discussion by Icsyx** [community/community#160568] [Actions]
I do have a private organisation repository. Let's call it my_private_repo.
Inside this repository I do have a clone of a public repository from outside of organisation. Let's call it my_public_repo.

In my repository I do have the `.gitmodules` file:

```
[submodule "path_to_my_public_repo"]
    path = path_to_my_public_repo       
    url = git://path_to_my_public_repo
```
When I run the git submodule status command, the submodule appears.

In the YAML file I want to checkout the code and I use this scrtip:

```
name: practice
on:
     push:
         branches:
             - github-action-practice
     workflow_dispatch:
jobs:
     get-code:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
               uses: actions/checkout@v3
               with:
                 submodules: recursive
```
When I try to run the workflow I encounter this message:
```

No url found for submodule path 'path_to_my_public_repo' in .gitmodules

The process '/usr/bin/git' failed with exit code 128
```

I search for similar problems and I tried several solutions, none worked.

For example I generated a token from my organisational account and add it to secrets and put it inside the checkout action. It didn't work.

```
jobs:
     get-code:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
               uses: actions/checkout@v3
               with:
                 submodules: recursive
                 token: ${{ secrets.ACCESS_TOKEN }}
```
I also tried to run the git command for update submodule. Same result.

```
jobs:
     get-code:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
               uses: actions/checkout@v3
             - name: Get submodule
               run: git submodule update --init --recursive
```
If you know or have any idea on what else I can try, please let me know

**Comment by heathhenley** [comment]
I have a similar set up - private repo with private submodules. I was seeing the same error as you before adding a SSH key, I know you added a token, so maybe our errors are not related just in case, mine looks like this:

```

... bunch  of stuff ...

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_KEY }}

... bunch of other stuff ...

``` 

The ssh key is for a machine user with read only access.  I'm sure you figured it out, but just in case or in case anyone else comes across this I though I would share.
