### DISCUSSION TITLE
can't use git merge-base  with checkout

### DISCUSSION THREAD

**Discussion by xiqingongzi** [community/community#160518] [Actions]
my ci script use `git merge-base` to find the common commit.

but I always get `fatal: Not a valid object name master`

although I use full clone

```yaml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```
