### DISCUSSION TITLE
Checking out private repository

### DISCUSSION THREAD

**Discussion by stell** [community/community#160543] [Actions]
I don't get this to work.  I have a private repo I need to checkout and use in another private repo of mine. 
So inside the workflow I'm doing this:

```
  - name: Checkout small private repo
    uses: actions/checkout@v2.3.4
    with:
      repository: name/smallprivaterepo         
      path: build/
```

Also added `token: ${{ secrets.REPO_ACCESS_TOKEN }}` but getting `Retrieving the default branch name.  Bad credentials.`

What is going wrong?

**Comment by dhamo-pk** [comment]
You need to add token to checkout the private repo with correct permissions. 

**How to create PAT with checkout permissions to checkout a private repository ?** 
Create a personal access token (PAT) with the repo scope. You can do this by going to your GitHub profile settings, selecting "Developer settings", then "Personal access tokens", and clicking "Generate new token". Make sure to copy the token value as it will not be displayed again.

```
- name: Checkout private repository
        uses: actions/checkout@v2
        with:
          repository: username/private-repo-name
          ref: main
          token: ${{ secrets.PAT }}
```

**Reply by arnodunstatter** [reply]
But that gives access to all personal private repositories via that token. I'm trying to use the fine-grained tokens to avoid this pitfall, but despite having given it read and write access to Actions and Workflows, and giving it read-only access to Metadata, I continue to get `The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128` and `remote: Write access to repository not granted.`

**Comment by k00ni** [comment]
For anyone who is stumbling about this issue, **deploy keys** saved my day. They might not for everyone, but in my case we need a tool in different repositories inside the same organization, but don't want personal accounts to be required for auth/access.

### Situation

```
Repository A      <======      Repository B
############
runs workflow, 
in which Repo B
is cloned and used. 
```

### Steps to accomplish what you need
1. Create a SSH key pair (public and private key), for instance with: `ssh-keygen -t rsa -b 4096 -C "git@github.com:<namespace>/<repo>.git"`
2. **do not** use a password (more later)
3. Go to **Repository B** > Settings > Deploy Keys > Add deploy key

![image](https://github.com/user-attachments/assets/8d3b462c-3152-49d6-93c7-dddb859e2fb4)

4. Use a meaningful title such as **Access from Repository A**
5. Copy the content of the **public key** file (ends with `.pub`) into the **Key** field
6. Decide if write access is required in the final workflow (usually its not) > Save
7. **Switch to Repository A** > Settings > Secrets and variables > Actions > Repository secrets (middle)
 
![image](https://github.com/user-attachments/assets/2a745685-0818-4e4f-aef8-f5b77749435c)

8. click "New repository secret" > set meaningful name (later required inside the workflow file, e.g. `SSH_PRIVATE_KEY`) > copy the content of the **private key** file into the **Secret** field 
9. Save
10. Switch to the **workflow** file inside **Repository A**

**Example workflow file with a checkout of repository B:** (note: please make sure you use the latest versions of each component used)

```yaml

name: Checkout Repository B

on: [push]

jobs:
  checkout-repo-b:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository A
      uses: actions/checkout@v3

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Checkout Repository B
      run: |
        git clone git@github.com:ORGANISATION/REPOSITORY_B.git repository-b
```

**About the no-password thing:** if you set a password, you have to provide it during the workflow which IMHO defeats the purpose of this approach. The following error will appear if a password-protected SSH key pair ist being used:

```
Starting ssh-agent
SSH_AUTH_SOCK=/tmp/.../agent.2472
SSH_AGENT_PID=24[7]
Adding private key(s) to agent
Error: Command failed: ssh-add -
Enter passphrase for (stdin): 
Enter passphrase for (stdin):
```

**Reply by ArchieAtkinson** [reply]
I just followed this and there seems to a small change when generating the keys:
`ssh-keygen -t rsa -b 4096 -C "git@github.com:<namespace>/<repo>.git"` where the repo is Repo B

**Reply by k00ni** [reply]
Could you elaborate on that a bit please?

**Reply by ArchieAtkinson** [reply]
When I used `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"` (I kept the example email which could be the reason for this issue), I got:
```
Run webfactory/ssh-agent@v0.9.1
/usr/bin/docker exec  1daaf45340181113d361c2e2a9eb22f7db9172acd121074bb462ccba3d9ba2c1 sh -c "cat /etc/*release | grep ^ID"
Starting ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-GDr56iDOJlMJ/agent.130
SSH_AGENT_PID=131
Adding private key(s) to agent
Identity added: (stdin) (your_email@example.com)
Key(s) added:
4096 SHA256:KwJcfgpkV8vI8aoRlB2XRHBimiUicYEhzGK70K7EW1w your_email@example.com (RSA)
Configuring deployment key(s)
Comment for (public) key 'ssh-rsa AAAAB...== your_email@example.com' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
```

Says here in the [webfactory/ssh-agent's readme](https://github.com/webfactory/ssh-agent?tab=readme-ov-file#support-for-github-deploy-keys).

**Reply by k00ni** [reply]
Ah ok, thanks. I adapted my initial post.

**Reply by fosskers** [reply]
This worked initially, but then caused other problems for my self-hosted runners.

**Comment by Hellseher** [comment]
What the point of the TOKEN/PAT in this cases if official `actions/checkout` does not support to clone private repopository within the same org?
```
    # Personal access token (PAT) used to fetch the repository. The PAT is configured
    # with the local git config, which enables your scripts to run authenticated git
    # commands. The post-job step removes the PAT.
    #
    # We recommend using a service account with the least permissions necessary. Also
    # when generating a new PAT, select the least scopes necessary.
    #
    # [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    #
    # Default: ${{ github.token }}
    token: ''

```

**Comment by thiagofis** [comment]
Here’s how to do it:

1. **Ensure your GitHub App has `Contents: Read` permission** on the target repository.
2. **Use the [`[actions/create-github-app-token](https://github.com/actions/create-github-app-token)`](https://github.com/actions/create-github-app-token) action** to generate a scoped token.
3. **Use the [`[actions/checkout](https://github.com/actions/checkout)`](https://github.com/actions/checkout) action** with that token to clone the private repository.

### ✅ Example Workflow Snippet

```yaml
- uses: actions/create-github-app-token@v2
  id: bot-app-token
  with:
    app-id: ${{ secrets.APP_ID }}
    private-key: ${{ secrets.APP_PRIVATE_KEY }}
    owner: <target-repo-owner> # e.g. MyOrganization

- name: Checkout Target Repository
  uses: actions/checkout@v3
  with:
    repository: <target-repo-owner>/<target-repo-name> # e.g. MyOrganization/MyPrivateRepo
    token: ${{ steps.bot-app-token.outputs.token }}
    ref: <target-repo-branch-name> # e.g. main, master
```

### 🔐 Notes
- Your GitHub App **must be installed in the target repository** for the token to have access.
- The `owner` field should match the organization or user that owns the target repository.
- This approach works well for monorepos, shared workflows, or any setup where cross-repo access is needed.
