### DISCUSSION TITLE
How to mount a secret in a *-workflow pod.   with containerMode.type=kubernetes.

### DISCUSSION THREAD

**Discussion by 66li** [community/community#160525] [Actions]
In the 
```
  spec:
    containers:
        volumeMounts:
        - name: secret-volume
          mountPath: /home/runner/_work/secret
          readOnly: true
    volumes:
    - name: secret-volume
      secret:
        secretName: msnonprod-tke-runner-set-org-ssmsecrets
```

Write the mounting rules under *-workflow pods are not visible to the file
