### DISCUSSION TITLE
Does kubeMode really need pods/exec?

### DISCUSSION THREAD

**Discussion by jglynn** [community/community#160532] [Actions] [answered]
The [Role definition](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/kube_mode_role.yaml#L35-L37) for Kubernetes Mode includes get & create for `pods/exec`.

Is this necessary? We're looking to reduce the need for pod/exec where possible.

Reading through the [ADR 2023-04-11: Limit Permissions for Service Accounts in Actions-Runner-Controller](https://github.com/actions/actions-runner-controller/blob/master/docs/adrs/2023-04-11-limit-manager-role-permission.md) doesn't really address the reasoning either.

Reference:

```yaml
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
```
