### DISCUSSION TITLE
Suggesting a small "Usage Example" fix in a comment?

### DISCUSSION THREAD

**Discussion by sergzach** [community/community#160550] [Actions]
Probably that's a not very convenient comment in the "Usage":

```
- uses: actions/checkout@v4
  with:
    # Repository name with owner. For example, actions/checkout
    # Default: ${{ github.repository }}
    repository: ''
```
    
Because `actions/checkout` looks ambiguous as an example of a repository. This is the reference to the current `action`, it seems better to place here another repository name.
