### DISCUSSION TITLE
When checking out a repo on Github Actions workflow, how do I pass in a key for a private submodule but not the repo itself?

### DISCUSSION THREAD

**Discussion by sfullerbeckman** [community/community#160503] [Actions] [answered]
When checking out a repo on Github Actions workflow, how do I pass in a key for a private submodule but not the repo itself? This is currently how I am doing it: The `ACCESS_KEY` is the private key of a deploy key which is stored in the main repo. That key should only apply to the submodule and not the repo itself though. How can I force that functionality? Currenly I get an error because it is trying to use the SSH key to checkout the main repo.

```yaml
- uses: actions/checkout@v3
  with:
      submodules: 'true'
      ssh-key:  ${{ secrets.ACCESS_KEY }}
```

**Comment by rosasurfer** [comment]
Same here. The main repo should always use the provided $GITHUB_TOKEN. I guess a workaround is to setup a machine user (service account) and use one user key for both main and submodule repo. In our case our organization has limited seats, so we don't want that. GHA is mostly used by organizations, so PATs don't apply here either.

There are countless issues here about private submodules not working and I'm surprised it's not clearly documented. Why is there no SSH config option per submodule? Obviously we are missing something here.

**Comment by DaAwesomeP** [comment]
Associated issue: https://github.com/actions/checkout/issues/924

**Reply by cardoe** [reply]
And #973

**Comment by DaAwesomeP** [comment]
This following configuration is working for me, although it is unfortunate this required an additional action:
```yaml
- uses: webfactory/ssh-agent@v0.5.4
  with:
    ssh-private-key: |
      ${{ secrets.PULL_KEY_REPO }}
      ${{ secrets.PULL_KEY_SUBMODULE_OTHERREPO }}
- uses: actions/checkout@v3
  with:
    submodules: 'recursive'
    persist-credentials: false
```
- secret `PULL_KEY_REPO`: Deploy key (private key) for this repo running the action with SSH key comment of the name of this repo (`git@github.com:owner/repo.git`)
- secret `PULL_KEY_SUBMODULE_OTHERREPO`: Deploy key (private key) for a private submodule repo running the action with SSH key comment of the name of the submodule repo (`git@github.com:owner/otherrepo.git`)
- Deploy key (public key) in this repo running the action
- Deploy key (public key) in this the submodule other repo

Everything is tightly scoped so that this repo/action can only access repos for which it has a deploy key. I would not recommend sharing deploy keys between multiple actions/repos. This method also pulls public HTTPS submodules just fine.

**Reply by sfullerbeckman** [reply]
@DaAwesomeP, I just tried what you suggested it. I got an error. When I ran it, I got this error: 
> ![image](https://user-images.githubusercontent.com/83652131/195417642-3ef1738f-fdd3-4b76-adb5-f764f6ea6de5.png)

It also said that two identities and two keys were added, but then this message was logged. Could this be the issue? 
> Comment for (public) key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.

**Reply by DaAwesomeP** [reply]
> @DaAwesomeP, I just tried what you suggested it. I got an error. When I ran it, I got this error:

I should note that I only tried this on an Ubuntu runner. That could be an issue, but I am unsure.

> It also said that two identities and two keys were added, but then this message was logged. Could this be the issue?
> 
> > Comment for (public) key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.

Yes, when generating the keys you need to specify the `-C` field and give the full Git SSH path to the repo (`git@github.com:owner/otherrepo.git`). This action seems to read this comment field when choosing a key.

**Reply by sfullerbeckman** [reply]
I did that though. This is the command I ran to generate my ssh keys: ` ssh-keygen -t ed25519 -C "git@github.com:[myOrg]/[myRepo].git"`, and I still get the error

**Reply by DaAwesomeP** [reply]
I have no clue then. Note that one deploy key should have a comment with the current repo, and the other deploy key should have a comment with the submodule repo. I am not the author of that GitHub action. You may wish to open an issue here: https://github.com/webfactory/ssh-agent. I have a feeling it could possibly be a Windows issue.

**Reply by sfullerbeckman** [reply]
I think you are right. I just ran on ubuntu-latest and it works. So, you seem to be right. It's an issue with running on a Windows runner

**Reply by DaAwesomeP** [reply]
Ah ok. Might as well open an issue and reference this discussion.

**Reply by sfullerbeckman** [reply]
Will do. Thanks a lot for the help!

**Reply by sfullerbeckman** [reply]
https://github.com/webfactory/ssh-agent/issues/130

**Reply by andrew-constantinescu** [reply]
I've also been banging my head for the past two days with checking out my private submodule within a private repo. Just stumbled upon this recent discussion. So, I've generated the two ssh key pairs for each repo. I added the public keys as deploy keys and the private keys as repository secrets (not environment secrets, right?). Made the adjustments to the yml and I get this message when running web-factory/ssh-agent:

![image](https://user-images.githubusercontent.com/69523467/195479856-0a1714c9-ea15-46e5-a7b4-b04216457010.png)

Running on ubuntu-latest, on push or pull_request (if that matters).

I never got a message saying my two identities and two keys were added, like @sfullerbeckman referenced. So I guess the keys have not been added, thus causing the checkout of the private submodule to fail?
```
Error: fatal: repository 'https://github.com/owner/otherrepo.git/' not found
Error: fatal: clone of 'https://github.com/owner/otherrepo.git' into submodule path '/home/runner/work/path/to/otherrepo' failed
```

I am very new to github actions and deployment keys, I would greatly appreciate your time and guidance.

**Reply by sfullerbeckman** [reply]
@andrew-constantinescu I get those exact errors that you are referencing too. From your description, it sounds like you did exactly what I did, which is in turn exactly what @DaAwesomeP said to do as well. I thought it was due to me running on Windows but now that you get the same error on Ubuntu, that must not be the issue.

**Reply by DaAwesomeP** [reply]
When you pasted your private key into the secret, did it include the comment field at the end?

**Reply by andrew-constantinescu** [reply]
Yep, I included the comment field as mentioned in your earlier comments. So if I `cat` my public keys, I'll see `git@github.com:owner/repo.git` and `git@github.com:owner/otherrepo.git` at the end of the .pub files respectively.

**Reply by sfullerbeckman** [reply]
.pub files are the public keys. What about the private keys? Did they have the comment field at the end?

**Reply by andrew-constantinescu** [reply]
No, the private keys have this format, which I think is correct:
```
-----BEGIN OPENSSH PRIVATE KEY-----
key is here
-----END OPENSSH PRIVATE KEY-----
```

**Reply by sfullerbeckman** [reply]
The only reason I ask is becuause @DaAwesomeP seemed to the the private keys should also have the comment at the end

> When you pasted your private key into the secret, did it include the comment field at the end?

**Reply by DaAwesomeP** [reply]
No, I was confusing the two, sorry. IIRC the private key comment is embedded in the key.

**Reply by DaAwesomeP** [reply]
This is definitely 100% working for me, so tomorrow I will verify my setup again and post back.

**Reply by sfullerbeckman** [reply]
Awesome. Thanks a lot. I've banged my head on this issue a for hours and hours, so if we can finally get a solution I am definitely going to get a tutorial added to some docs somewhere

**Reply by sfullerbeckman** [reply]
@andrew-constantinescu , what did you do to create your ssh keys? I did...`ssh-keygen -t ed25519 -C "git@github.com:[orgName]/[repoName].git"`

**Reply by DaAwesomeP** [reply]
OK, here all all of my steps:

1. Generate a key for the repo _running the action_: `ssh-keygen -t ed25519 -a 100 -C "git@github.com:owner/action-repo.git" -E sha512`
   1. Paste this public key into the deploy key section of `action-repo` and give it read permissions. Paste the whole key as it appears in the `*.pub` file.
   2. Paste this private key into a secret called `PULL_KEY_REPO` for `action-repo`.
2. Generate a key for the _submodule repo_: `ssh-keygen -t ed25519 -a 100 -C "git@github.com:owner/submodule-repo.git" -E sha512`
   1. Paste this public key into the deploy key section of `submodule-repo` and give it read permissions. Paste the whole key as it appears in the `*.pub` file.
   2. Paste this private key into a secret called `PULL_KEY_SUBMODULE` for `action-repo`.
3. Paste the following _at the very top_ of your build before any actions that involve Git or SSH or checking out:
   ```yaml
   - uses: webfactory/ssh-agent@v0.5.4
     with:
       ssh-private-key: |
         ${{ secrets.PULL_KEY_REPO }}
         ${{ secrets.PULL_KEY_SUBMODULE }}
   - uses: actions/checkout@v3
     with:
      submodules: 'recursive'
      persist-credentials: false
    ```
    The full top of my build looks like this:
    ```yaml
   - name: Update apt
      run: apt-get update
   - name: Install git and sudo
      run: apt-get install -y git sudo
   - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: |
          ${{ secrets.PULL_KEY_REPO }}
          ${{ secrets.PULL_KEY_SUBMODULE }}
   - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        persist-credentials: false
    ```
4. Your submodules that rely on these keys (this excludes public repos) should be configured using SSH. Here is an excerpt from my `.gitmodules`:
   ```ini
   [submodule "lib/submodule"]
	   path = lib/submodule
	   url = git@github.com:owner/submodule-repo.git
   ```

Note that I only tested **pushing commits directly to the repo.** I am the owner of this repo and **have full permissions.** I did not try pull requests or any other way of pushing.

**I have only tried this with `ubuntu-latest`.**



This is the interface that I used to add the secrets:
> ![image](https://user-images.githubusercontent.com/4472083/195624073-0eee65e9-8dfe-400f-8b2f-e8e7d88454ca.png)

This is the interface that I used for adding deploy keys:
> ![image](https://user-images.githubusercontent.com/4472083/195624387-04480731-484c-4174-8326-355685ba5e36.png)

**Reply by sfullerbeckman** [reply]
I am going to run through these steps exactly and see what result I get. Thanks @DaAwesomeP !

**Reply by sfullerbeckman** [reply]
Works perfectly on Ubuntu. Fails on Windows 😢

**Reply by andrew-constantinescu** [reply]
Did not quite work for me, I am getting the same error I mentioned yesterday. The only difference I see here is that my private repo and private submodule are both owned by the organization, not my user account. My user account has full permissions but who knows

**Reply by andrew-constantinescu** [reply]
Nevermind! I had added the submodule private key as a secret to the submodule repo, when it should be the main repo as you clearly stated! Works for me too! Thanks for the detailed breakdown @DaAwesomeP !!

**Reply by sfullerbeckman** [reply]
> Works perfectly on Ubuntu. Fails on Windows 😢

The interesting thing is that I still get the `Comment for (public) key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.` error on both ubuntu and windows, and ubuntu worked. So that must not be the issue. It must be the checkout action that is somehow failing on Windows

**Reply by sfullerbeckman** [reply]
I noticed that the fetch commands are actually different between the two platforms.

Windows 👇
>   "C:\Program Files\Git\bin\git.exe" -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +4bd1373d4f350ad95520dec7a9e33c27326ccd55:refs/remotes/origin/[branch name]

Ubuntu 👇
> /usr/bin/git submodule sync --recursive
  /usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1 --recursive

**Reply by sfullerbeckman** [reply, marked as answer]
I  got it to work on Windows by doing the submodule checkout manually. I also had to register the ssh keys _after_ the initial checkout because for some reason it couldn't pull the action repo. This is what I did...

```yaml
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.PULL_KEY_REPO }}
            ${{ secrets.PULL_KEY_SUBMODULE }}

      - run: |
          git submodule sync --recursive
          git -c protocol.version=2 submodule update --init --force --depth=1 --recursive

```
