### DISCUSSION TITLE
How to prevent checkout of a deleted branch?

### DISCUSSION THREAD

**Discussion by efenderbosch-atg** [community/community#160566] [Actions]
In building service B, we need some resources from service A. First we look for a branch in service A that matches the current branch of the build for service B. If that fails, we checkout a well known branch. This works correctly when the matching branch does not exist.

It fails, or rather doesn't do what we want, when the matching branch exists, but is then merged and deleted. The `checkout-other-repo-part-1` step below will still find the deleted branch and it never makes it to the 2nd checkout.

Is there any way I can prevent this?

```yaml
      - name: Checkout master or matching branch
        id: checkout-other-repo-part-1
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: our-org/other-repo
          ref: ${{ steps.determine-other-repo-branch.outputs.other_repo_branch }}
          ssh-key: ${{ secrets.READ_ONLY_DEPLOY_KEY }}
          path: other
          sparse-checkout: src/main/resources
          show-progress: false

      - name: Checkout well known branch
        if: success() && steps.checkout-other-repo-part-1.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          repository: our-org/other-repo
          ref: some-well-known-branch
          ssh-key: ${{ secrets.READ_ONLY_DEPLOY_KEY }}
          path: other
          sparse-checkout: src/main/resources
          show-progress: false
```

edit: more info

I had deleted the branch using the GitHub UI, but it was still showing up w/ `git branch --list --remote ...`. I've now deleted it with `git push origin --delete ...` and that has fixed the problem, it now fails through properly to the 2nd checkou.
