### DISCUSSION TITLE
runner set with a specified SA instead of the default

### DISCUSSION THREAD

**Discussion by dyasny** [community/community#160513] [Actions]
Hi everyone, 

I am running a runner set for a repo, deployed from a helm chart. I need to change the SA the runners run on to my own SA, one with specific permissions in the cluster. 

This is my values.yaml, very simple:

```yaml
githubConfigUrl: "https://github.com/myothe rg/myrepo"
githubConfigSecret: github-token

maxRunners: 10

minRunners: 0
containerMode:
  type: "dind"

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        serviceAccountName: github-admin

controllerServiceAccount:
  namespace: arc
  name: github-admin
```

As you can see I tried to both add the SA in the pod template and used a setting available in the original values.yaml, but when I run the workflow, a step that prints `kubectl auth whoami` still shows I'm on the wrong SA:

```
kubectl auth whoami

ATTRIBUTE                                           VALUE
Username                                            system:serviceaccount:arc:myrepo-runner-set-gha-rs-no-permission
...

```

Is there any way to set the SA? Since I use helm and the runner sets create the no-permission SAs via helm, I'd rather not tie a rorebinding outside of helm to a helm-managed SA object, and do everything inside the chart instead.
