### DISCUSSION TITLE
Support Sparse checkouts

### DISCUSSION THREAD

**Discussion by devminded** [community/community#160571] [Actions]
# Support sparse checkouts

## Purpose
When using large project with many modules (AKA monorepo) being able to do sparse checkouts (supported since git 2.25.x) would be very helpful.

## Example
**Repo containing:**
- scripts
- tools
- modules/mobile-client
- modules/server
- modules/web

We want to only checkout and build the mobile-client (nice when combined with paths/paths_ignore).
So the equivalent of `git sparse-checkout init --cone && git sparse-checkout set modules/mobile-client scripts tools` would be:

```yaml
- name: Checkout tools repo
  uses: actions/checkout@v3
  with:
    repository: my-org/my-repo
    sparse:
      - modules/mobile-client
      - scripts
      - tools
```

Ref: https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/
