### DISCUSSION TITLE
Mount a custom volume to a Github job in `containerMode: kubernetes`

### DISCUSSION THREAD

**Discussion by LeonoreMangold** [community/community#160557] [Actions]
Hello !
I wanted to mount a volume to Github ARC runners deployed with the mode Kubernetes for a rather standard use case, i.e. share cached data.
However, I surprisingly didn't find any way to mount a volume inside the workflow pod started alongside the runner pod.

It even tried using a workflow-extension to declare my volume, via a ConfigMap : 
``` 
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-extension
data:
  workflow-extension.yml: |
      volumes:
        - name: test-custom-volume
          persistentVolumeClaim:
            claimName: my-custom-pvc
```
And in the Helm values for the runner : 
```
containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      securityContext:
        privileged: true
      env:
      - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
        value: /home/runner/workflow-extension.yml
      volumeMounts:
      - name: workflow-extension
        mountPath: /home/runner/workflow-extension.yml
        subPath: workflow-extension.yml
    volumes:
    - name: workflow-extension
      configMap:
        name: workflow-extension
```
I tried binding this volume in my job container with options, like that :
```
jobs:
  test-volume:
    runs-on: [ my_runners ]
    container:
      image: my_image:version
      options: -v test-custom-volume:/custom-volume
```

With this method, I could saw the volume declaration in the workflow pod description. However, the volume wasn't mount into the job container as if the container options weren't interpreted (I think I read somewhere that this is the case in Kubernetes mode).

So my question is, how is it possible that we **cannot add any volume** to a runner **in Kubernetes mode** ? Am I missing something or this is a really useful feature request ?

Don't hesitate to like this discussion if you struggled with the same problems.

_ARC controller version : 0.9.3
Linked to #3508_
