### DISCUSSION TITLE
Allow workflow_run to wait for all workflows it depends on

### DISCUSSION THREAD

**Discussion by danielalves** [community/community#16059] [Actions]
Hello!
I've been using Github Actions in my personal projects with great success, so kudos for the awesome tool 🙌

One feature that my colleagues and I have been missing, though, is to be able to make `workflow_run` wait for all the other workflows it depends on instead of resolving on the first completed one. Something like this would be awesome:

```yaml
# Current / default behavior
on:
  workflow_run:
    workflows: [dependency-0, dependency-1, dependency-n]
    strategy: resolve-on-first
    types:
      - completed 

# Desired / additional behavior
on:
  workflow_run:
    workflows: [dependency-0, dependency-1, dependency-n]
    strategy: wait-all
    timeout: 5m
    types:
      - completed 
```

The reasoning behind this feature request is that we would like to be able to keep the nice UI you built for separate workflows while being able to create dependencies between them in a more versatile way (eg. making sure a given job is only executed once in the entire build pipeline). Currently, the only way to achieve the same thing (afaik) is to make the "parent" workflow call all the "child"/"dependency" workflows using `workflow_call` and put all of them in a `needs` directive. However that generates a worse UI since, at the end, `workflow_call` ends up embedding the called workflow's steps into the caller workflow. Thus we have to scan through a lot jobs to understand what failed, whereas in the separate workflows case the failure reports are spot-on.

Maybe an example would be better. Imagine a monorepo-like structure, where the repo's root contains many sub-projects. Also sitting on the root, there's a infra folder, containing code responsible for spinning up infrastructure somewhere (eg. terraform + AWS). Finally, the `.github` folder contains workflows for each separate project:

```txt
- root/
  - .github/
    - workflows/
      - infra.yml
      - project-1.yml
      - project-2.yml
      - project-n.yml
  - infra/
  - project-1 /
  - project-2 /
  - project-n /
```

The idea is to create this flow:

- Start all builds -> when they all pass, start infrastructure update -> start all deploys

Then a `project-x.yaml` could look like this:

```yaml
name: project-x

on:
  workflow_run:
    workflows: [infra]
    types:
      - completed

  push:
    branches: [main]
    paths:
      - 'infra/**'
      - 'project-x/**'
      - '.github/workflows/infra.yml'
      - '.github/workflows/project-x.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - run: build

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2
      - run: deploy
```

And `infra.yml` could look like:

```yaml
name: infra

on:
  workflow_run:
    workflows: [project-1, project-2, project-n]
    strategy: wait-all
    timeout: 5m
    branches: [main]
    types:
      - completed

jobs:
  infra-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: infra-update
```

Thanks in advance.

**Comment by danielalves** [comment]
Just to complete my example above, this is the way to achieve an equivalent flow today, which I must say results in much more code:

```yml
# A sub-project workflow
name: project-x

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ inputs.job == 'build' }}
    steps:
      - uses: actions/checkout@v2
      - run: build

  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.job == 'deploy' }}
    concurrency: project-x-main
    steps:
      - uses: actions/checkout@v2
      - run: deploy


# Infrastructure workflow that orchestrates everything
name: infra

on:
  push:
    branches: [main]

jobs:
  run-project-1-build:
    name: Project 1
    uses: ./.github/workflows/project-1.yml
    with:
      job: build
    secrets: inherit

  run-project-2-build:
    name: Project 2
    uses: ./.github/workflows/project-2.yml
    with:
      job: build
    secrets: inherit

  run-project-n-build:
    name: Project N
    uses: ./.github/workflows/project-n.yml
    with:
      job: build
    secrets: inherit

  infra-check:
    runs-on: ubuntu-latest
    needs:
      - run-project-1-build
      - run-project-2-build
      - run-project-n-build
    steps:
      - uses: actions/checkout@v2
      - run: infra-check

  infra-update:
    runs-on: ubuntu-latest
    needs: infra-check
    concurrency: infra-main
    steps:
      - uses: actions/checkout@v2
      - run: infra-update

  run-project-1-deploy:
    needs: infra-update
    name: Project 1
    uses: ./.github/workflows/project-1.yml
    with:
      job: deploy
    secrets: inherit

  run-project-2-deploy:
    needs: infra-update
    name: Project 2
    uses: ./.github/workflows/project-2.yml
    with:
      job: deploy
    secrets: inherit

  run-project-n-deploy:
    needs: infra-update
    name: Project N
    uses: ./.github/workflows/project-n.yml
    with:
      job: deploy
    secrets: inherit
```

This means that, for each new sub-project in the mono repo, we have to add a call to `build` and a call to `deploy`, which is very error prone. 

And the resulting UI would contain many skips:

![image](https://user-images.githubusercontent.com/522602/167925385-645f3a2a-88d2-46b7-81be-f09afc46d54a.png)
