### DISCUSSION TITLE
Checkout base branch for PR and successively checkout merge branch

### DISCUSSION THREAD

**Discussion by frabert** [community/community#160570] [Actions]
I would like to do something like

- checkout base branch
- do stuff on it
- checkout merge branch _in the same local repo_
- do other stuff on it

is it possible to do so using the action directly?

**Comment by hackedbad** [comment]
Ha

**Reply by chennareddy143** [reply]
haa

**Comment by henrygriffiths** [comment]
Hi @frabert,

Does this match what you'd like to do?
```yaml
on: pull_request
...
- uses: actions/checkout@v3
    ref: ${{ github.event.pull_request.base.ref }}
- name: Do stuff on base branch
- uses: actions/checkout@v3
    ref: ${{ github.event.pull_request.head.ref }}
- name: Do stuff on merge branch
```

**Reply by frabert** [reply]
Unfortunately this has the effect of wiping the repo directory, which nullifies the advantages I would get from only updating the files changed between base and HEAD

**Reply by henrygriffiths** [reply]
Would just running a git checkout then resolve your issue?
```yaml
on: pull_request
...
- uses: actions/checkout@v3
    ref: ${{ github.event.pull_request.base.ref }}
    fetch-depth: 0
- name: Do stuff on base branch
- run: git checkout ${{ github.event.pull_request.head.ref }}
- name: Do stuff on merge branch
```
