### DISCUSSION TITLE
How to Override the docker:dind

### DISCUSSION THREAD

**Discussion by sbollap1** [community/community#160551] [Actions]
Had a general question, is it possible to override the docker:dind image to pull from my own container registry. I am trying the following values.yaml file but it still seems to pulling from docker hub.

```
githubConfigUrl: "https://github.com/mycloudops"

githubConfigSecret:
  github_token: "sss"
  githubConfigSecret: pre-defined-secret

maxRunners: 100

minRunners: 1

runnerScaleSetName: "arc-runner"

containerMode:
  type: "dind"

template:
  spec:  
      imagePullSecrets:
      - name: acr-secret
      containers:          
      - name: runner
        image: mycloudops.azurecr.io/debian-custom-image:latest
        command: ["/home/runner/run.sh"]
      - name: dind
        image: mycloudops.azurecr.io/docker:dind

controllerServiceAccount:
  namespace: arc-systems
  name: arc-gha-rs-controller

controller:
   logLevel: debug

```

and my helm install command is as expected

```
helm upgrade --install arc-runner-set \
    --namespace arc-runners \
    --create-namespace \
    -f values.yaml \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

```

Note that with just the following its working fine and pulling the image from my container registry. Its just the docker:dind is still going to docker hub for some reason even though I gave it to pull from my container registry

```
      containers:          
      - name: runner
        image: mycloudops.azurecr.io/debian-custom-image:latest
        command: ["/home/runner/run.sh"]

```
