### DISCUSSION TITLE
Troubleshooting reusable workflows for CI

### DISCUSSION THREAD

**Discussion by LionOnTheWeb** [community/community#160540] [Actions]
### Problem
Trying to build a CI workflow to deploy my project to Vercel. In trying to abstract my workflow jobs into separate files that I reuse for my deployment jobs I encounter this error:

```
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/repo/project/.github/workflows/setup.yml'. Did you forget to run actions/checkout before running your local action?
```

### Reproduce
My workflow setup includes these files in my project's `./.github/workflows/` directory:
- ci.yml (main workflow)
- release.yml (main workflow)
- enforcer.yml (helper - free way of main branch protection)
- setup.yml (helper - checks out code, sets up Node/pnpm, runs install)
- test.yml (helper - returns echo-- no unit or integration tests yet)

Here's how `ci.yml` and `setup.yml` are configured to work together:

```yaml
# setup.yml

name: 'Workflow Setup'

on:
  workflow_call: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.6

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Install dependencies
        run: pnpm install
```

```yaml
# ci.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - next
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Run workflow setup
        uses: ./.github/workflows/setup.yml

  deploy-dev:
    needs: setup
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Build dev
        run: pnpm build:dev

      - name: Deploy Dev
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --dev --token=$VERCEL_TOKEN

  deploy-stage:
    needs: setup
    if: github.ref == 'refs/heads/next'
    runs-on: ubuntu-latest

    steps:
      - name: Lint and test
        uses: ./.github/workflows/test.yml
        with:
          branch: next

      - name: Build stage
        run: pnpm build:stage

      - name: Deploy Stage
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token=$VERCEL_TOKEN

  deploy-prod:
    needs: setup
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Build prod
        run: pnpm build:prod

      - name: Deploy Prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token=$VERCEL_TOKEN
```

ChatGPT is of no help here, can someone please shine a light on what the issue is here? I've tried using different versions of `actions/checkout` to no avail.

**Comment by LionOnTheWeb** [comment]
Managed to get a bit further with this by defining the setup and test jobs first like so:

```yaml
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    uses: ./.github/workflows/test.yml
    with:
      branch: next
```

Now it passes the setup stage but I'm unable to use `pnpm` that was installed in `setup.yml`
