### DISCUSSION TITLE
Checkout SHA on remote repo

### DISCUSSION THREAD

**Discussion by mickutz** [community/community#160516] [Actions]
Hi,
I've got this snippet of code that looks to be a bit troublesome.
```
jobs:
  runJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout a different repo
        uses: actions/checkout@v2
        with:
          repository: <org>/<repo>
          ref: cccc8888
          token: ${{ secrets.GH_PAT }}
          fetch-depth: '0'
```
The intention is to checkout a specific commit SHA of the remote repository, however, the action seems to be checking only against branches or tags (as opposed to what the documentation says):
```
Determining the checkout info
  /usr/bin/git branch --list --remote origin/cccc8888
  /usr/bin/git tag --list cccc8888
  Error: A branch or tag with the name 'cccc8888' could not be found
```

Would anyone be able to advise whether I'm missing something or this can't actually be done?
