### DISCUSSION TITLE
Runnerset and PVC

### DISCUSSION THREAD

**Discussion by ViktorLindgren95** [community/community#160625] [Actions] [answered]
When using RunnerSet with Persistent Storage, everytime we scale up or scale down aswell as use ephemeral runnerset the storage is lost between jobs. The statefulset is recreated together with the job pod causing the Pvc to be removed and another bounding has to happen. This makes it take about 5 minutes for a new runner to start every time. We have resorted to using Persistent runners for now but would love to be able to use Ephemeral runnerSet together with docker image cache etc like its documented in the readme.

Structure looks like
![image](https://user-images.githubusercontent.com/23239792/177262265-e0184ed0-0e00-4783-86fe-5f40e18a31af.png)

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: cached-runnerset-a
spec:
  ephemeral: true
  group: gaas
  enterprise: removed
  labels:
    - gaas-cached
    - cached-runnerset-a
  selector:
    matchLabels:
      app: cached-runnerset-a
  serviceName: pipeline
  template:
    metadata:
      labels:
        app: cached-runnerset-a
    spec:
      serviceAccountName: arc-runnerset
      containers:
        - name: runner
          env:
            - name: HTTP_PROXY
              value: "removed"
            - name: HTTPS_PROXY
              value: "removed"
            - name: NO_PROXY
              value: "removed"
            - name: DISABLE_RUNNER_UPDATE
              value: "true"
          resources:
            limits:
              cpu: 500m
              memory: "1Gi"
            requests:
              cpu: 100m
              memory: "1Gi"
        - name: docker
          env:
            - name: HTTP_PROXY
              value: "removed"
            - name: HTTPS_PROXY
              value: "removed"
            - name: NO_PROXY
              value: "removed"
          resources:
            limits:
              cpu: 500m
              memory: "4Gi"
            requests:
              cpu: 100m
              memory: "4Gi"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/docker
              name: var-lib-docker-a
  volumeClaimTemplates:
    - metadata:
        name: var-lib-docker-a
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: arc-var-lib-docker
```
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arc-var-lib-docker
  labels:
    content: arc-var-lib-docker
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

Is our configuration wrong? Is this how its supposed to work that the PVC is removed and our provisioning is just too slow for this configuration etc. I would love some answers if possible
