### DISCUSSION TITLE
How are we supposed to pass the secret name dynamically for `ACTIONS_RUNNER_INPUT_JITCONFIG` ?

### DISCUSSION THREAD

**Discussion by 60k41p** [community/community#160654] [Actions]
We have a deployment of ARC which has the runner pod spec heavily customised through `template.spec` Helm value, and would like to make use of the JIT tokens just like the default configuration does, as in:
```
    - name: ACTIONS_RUNNER_INPUT_JITCONFIG
      valueFrom:
        secretKeyRef:
          key: jitToken
          name: k8s-x64-medium-test-z9j97-runner-zbhsb
```
But of course given that `valueFrom.secretKeyRef.name` is dynamic and changes with every pod, we need to do this in a dynamic way.

We have tried:
```
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_INPUT_JITCONFIG
            valueFrom:
              secretKeyRef:
                key: jitToken
                name: $(POD_NAME)
```
Which doesn't work because such lookups do not work within `valueFrom` and causes an error like:
```
2024-05-01T02:53:20Z	ERROR	EphemeralRunner	Failed to create a pod due to unrecoverable failure	{"ephemeralrunner": {"name":"k8s-arm64-medium-test-wgpj4-runner-zz2km","namespace":"gha-runners"}, "error": "Pod \"k8s-arm64-medium-test-wgpj4-runner-zz2km\" is invalid: spec.containers[0].env[4].valueFrom.secretKeyRef.name: Invalid value: \"$(POD_NAME)\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"}
```

So I'd like to ask if is there a way to pass the secret name dynamically for `ACTIONS_RUNNER_INPUT_JITCONFIG` environment variable?

**Comment by dzmitryharchanin-tomtom** [comment]
The secret will be automatically used in the environment variable `ACTIONS_RUNNER_INPUT_JITCONFIG` as `valueFrom.secretKeyRef` when the pod is created. The main part is to set the container name to the `runner`:

```
template:
  spec:
    containers:
      - name: runner
         image: ... 
```
