### DISCUSSION TITLE
Are cache key case sensitive?

### DISCUSSION THREAD

**Discussion by nap** [community/community#160602] [Actions]
I was wondering if cache keys are case sensitive.

Lets say I have a cache with the key `it-is-i-who-created-this-cache` and then I retrieve it elsewhere using `It-is-I-who-created-this-cache`, will I get a `cache-hit` set with `true` or `false`?

```yaml
name: pull request
on:
  pull_request:
    branches:
      - main
jobs:
  encache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        id: cache
        with:
          path: ./*
          key: it-is-i-who-created-this-cache
          restore-keys: it-is-i-who-created-this
      - run: echo "it-is-i-who-created-this" >dope

  decache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        id: cache
        with:
          path: ./*
          key: It-is-I-who-created-this-cache
          restore-keys: It-is-I-who-created-this
      - if: ${{ steps.cache.outputs.cache-hit == 'true' }}
        run: cat dope
```

What will the content of the `dope` file be?
