### DISCUSSION TITLE
Deploy runner with multiple label with gha-runner-scale-set?

### DISCUSSION THREAD

**Discussion by tbirk-bhs** [community/community#160682] [Actions] [answered]
Hello,

I'm trying to migrate from the legacy ARC to the new gha-runner-scale-set. With the legacy ARC I had a RunnerDeployment and added multiple labels. e.g.

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
...
spec:
  template:
    spec:
      ...
      labels:
        - ubuntu-22.04
        - ubuntu-latest
```

Is it also possible to add multiple runner labels to a gha-runner-scale-set?

Thanks for helping me!

Timon
