### DISCUSSION TITLE
Request: images with no additional software

### DISCUSSION THREAD

**Discussion by JayBazuzi** [community/community#160642] [Actions]
I want to ensure that my build correctly supplies dependencies, by running CI on a clean machine. I wish there were runner images with no additional installed software, for this reason.

I need this for Mac, Windows, and Linux, but I don't think I need this for every supported version of each OS - just latest.

**Comment by JayBazuzi** [comment]
Consider using Windows Server Core and a minimal distro of Linux rather than Ubuntu. I don't know enough about either to confidently make a recommendation, though.

**Comment by subir0071** [comment]
Hi @JayBazuzi , This would be really great, if we are able to add the minimal images for different OSs.
However, such addition are based on user feedbacks and reactions.
We are closely following our user and customers' requirement for new features which help us prioritize our backlog.

 We allow some time for the community register their feedback to this forward-looking thread.

**Comment by p5** [comment]
This would be a huge improvement for my projects.
I create some pretty large OCI (Docker) images and am constantly running into storage issues with the GitHub-provided runners.

Providing a minimal image would allow me to install my own dependencies (only Docker/Podman) before running my workflows.

I also think it may be good to include a container runtime in these minimal images, so users can [run their jobs inside a container](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container), on a host with no dependencies that can't even be accessed.  I would like to run my CI jobs on Fedora runners, though when I try to do so, there's no way to uninstall unwanted software (like the DotNet SDK) so I therefore am running out of storage space.

I.E.

```yaml
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-minimal-24.04
    container:
      image: fedora/fedora:41
    steps:
      - name: Install dependencies
        run: dnf install -y docker

      - name: Build large image
        run: docker build .
```
