### DISCUSSION TITLE
Unable to Pull ARC Helm Chart in OCI Using ArgoCD (0.9.3)

### DISCUSSION THREAD

**Discussion by nat-ray** [community/community#160686] [Actions]
I am facing an issue with trying to deploy ARC in K8s. I previously did a POC where I deployed ARC from the CLI to the K8s cluster as described in the Quickstart guide:

```
NAMESPACE="arc-systems-poc"
helm install arc \
    --namespace "${NAMESPACE}" \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
```

This worked well. However, I need to do the actual deployment from ArgoCD. I have created a simple yaml like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc-systems
  namespace: argocd
spec:
  destination:
    namespace: arc-systems
    server: https://kubernetes.default.svc
  project: platform-prod
  source:
    chart: gha-runner-scale-set-controller
    repoURL: "oci://ghcr.io/actions/actions-runner-controller-charts"
    targetRevision: 0.9.3
    helm:
      releaseName: arc
  syncPolicy:
    automated:
      selfHeal: true
```

It seems ArgoCD is having trouble pulling the chart from OCI, because it returns this error:

```
helm pull --destination /tmp/9c0cd8c6-3d02-4266-bc6a-874c95f46a1b --version 0.9.3 --repo oci://ghcr.io/actions/actions-runner-controller-charts gha-runner-scale-set-controller` failed exit status 1: Error: looks like "oci://ghcr.io/actions/actions-runner-controller-charts" is not a valid chart repository or cannot be reached: object required
```

I have tried many variations of this yaml, but cannot get it pull the chart.

For reference, I can pull the helm chart in my local if I run `helm pull oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller --version 0.9.3 --destination /tmp`, but I can't seem to get ArgoCD to do the same.
