### DISCUSSION TITLE
Scheduled run on last Friday of the Month not working

### DISCUSSION THREAD

**Discussion by Garethgr** [community/community#160626] [Actions]
Hey all, I am not sure if this is the correct place for this but here goes.
I have the below schedule in my workflow:
```
# Controls when the workflow will run
on: 
  # Allows you to run this workflow automatically on a schedule
  schedule:
    - cron: '0 9 23-29 * 5' # m|H|DoM|Mo|DoW (UTC)
```
It currently works 100% on Jenkins however during my migration to GH workflows this runs:
* Every Friday
* Every 23-29th day of the month

On Jenkins it only runs if the day is a Friday

Any ideas on how I can get this running ONLY on the last Friday of the month?
