### DISCUSSION TITLE
Using Docker Registry Mirror

### DISCUSSION THREAD

**Discussion by jef** [community/community#160699] [Actions] [answered]
Related: https://github.com/actions-runner-controller/actions-runner-controller/pull/478

I'm currently using something like this:

```yaml
image: private-docker-repo.jfrog.io/summerwind/actions-runner:latest
imagePullSecrets:
  - name: docker
dockerRegistryMirror: https://private-docker-repo.jfrog.io
```

Seems to pull the image fine and also use the mirror fine, but I'm confused on how it's accessing the mirror? How are the credentials sent? I tried looking in the code, but couldn't find it.

This is the closest thing I've found to setting up the mirrors, but not setting [the proxy credentials](https://docs.docker.com/registry/recipes/mirror/#configure-the-cache):

https://github.com/actions-runner-controller/actions-runner-controller/blob/30ab0c0b7118d9ae59c186707abc69cb71608574/runner/startup.sh#L31-L33

What am I missing? 😅
