### DISCUSSION TITLE
Max Inputs of 10 problems

### DISCUSSION THREAD

**Discussion by henderjm** [community/community#160740] [Actions]
Right now there is a limit on the amount of inputs you can define in a manual workflow action of 10. I want our workflow to be able to select what applications (there is a lot - no judgement 😄 ) from a repository as well as other metadata inputs to be defined and deployed to a development environment, simple example
```yaml
inputs:
  - deploy_app_1:
    type: boolean
  - deploy_app_2:
    type: boolean
  - env_target:
    type: choice
```
This inputs are then actually used as part of a `matrix_strategy` block on whether we run the whole build job for an application or not.

Right now I feel like the only nice and scaling solution is just pick the most mandatory applications to run and be allowed to toggle from a select few. 
` app_1,app_2,app_3,...`

I could also have a string and then parse the inputted string but free text is always problematic.

Is there anywhere I can vote on having more inputs than 10 on manual workflows or has anyone come up with a nice workaround, FYI I need 15 inputs at this moment 😞
