### DISCUSSION TITLE
Dynamic resource assignment to runners

### DISCUSSION THREAD

**Discussion by Brenner87** [community/community#160727] [Actions]
Hello. I'm currently working on PoC for migrating from on prem Bitbucket and Jenkins to GitHub. 
Playing with actions-runner-controller and faced with the problem. Some of our teams require very huge resource amount for their runners while another teams need very few resources. 
Currently I've created runnerDeployment with following resource limits:
```
      resources:
        limits:
          cpu: "8.0"
          memory: "40Gi"
        requests:
          cpu: "1.0"
          memory: "6Gi"
```
This doesn't solve the problem, because if k8s node do not have enough resources, the runner would be destroyed.
Is there any way of dynamic resource management?
1. Is there an ability to request resource amount from build?
2. Is there an ability to request resources on runner creation?
3. May I have more then 1 runner deployments with 1 controller? Would they work correct?

I tried to create 2 different runnerDeployments with 1 controller. But it doesn't seem like autoscaler work correct.

I didn't find answers to this questions in documentation. Maybe I missed something and someone can point me to correct place.

**Comment by kevholmes** [comment]
The standard way to manage this @Brenner87 is to create multiple runner types with their own HRA and RunnerDeployment, and add them as Runner Groups in your GH instance. Users can then request these via the `runs-on:` label in their workflows. You can add these runner groups into an Org or repo individually to limit who can access the types. For instance maybe most teams do not need 8 cores / 40 Gi per Job so you do not make that Runner Group (at least one RunnerDeployment) available to them.

**Reply by Brenner87** [reply]
Thank you @kevholmes. Sounds reasonable. Going to follow this way:)

**Comment by alexklibisz** [comment]
@Brenner87 We solved this as @kevholmes discussed. I also miss the ability to specify custom per-job resources when using the Jenkins Kubernetes plugin. I think this is the only thing I miss about Jenkins.

Another downside of the multi-hra approach, in its most default implementation, is that you have to keep at least one runner w/ non-trivial resources running at all times. There is some info in the docs about configuring a runnerdeployment to scale to zero. I haven't taken the time to fully understand it yet.

**Comment by roulettedares** [comment]
what if we could dynamically set the runner pod `resources` via workflow labels? example workflow:
```yaml
big-cpu-job:
  runs-on: [self-hosted, 23cpu-7g]
```

new `setRequestsBasedOnLabels` in the `RunnerSet` CR
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: myorg-use-labels-to-set-requests
spec:
  setRequestsBasedOnLabels:
    enabled: true
    maxPodCpus: 30
    maxPodMemory: 10Gi
```
or even a new `DynamicRequestsRunnerSet` custom resource to keep things tidy and secure
