### DISCUSSION TITLE
Response 404 (not found) during registration runner when switched from repository to organization in runnerdeployment.yaml

### DISCUSSION THREAD

**Discussion by usernamessh** [community/community#160726] [Actions] [answered]
Hello, I had ARC system running very well for my repository. But now I decided to set the focus to organization level (in our Github-enterprise). So that should be easily possible by just replace "respository" by "organziation" based on the [description](https://github.com/actions/actions-runner-controller/blob/master/docs/choosing-runner-destination.md). But now the runner POD shows in the log the error response 404 (not found) during "config.cmd" right after step "# Authentication":
>>Http response code: NotFound from 'POST https://github.myenterprise.com/api/v3/actions/runner-registration'
>>{"message":"Not Found","documentation_url":"https://docs.github.com/enterprise-server@3.7/rest"}

Do I have to change something else? I can just re-use the PAT that I used for the repository-level, right? (It has literally all permissions just to be sure).
Any help would be highly appreciated!!!

runnerdeployment.yaml
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actionsrunner-win2019
  namespace: actions-runner-system 
spec:
  replicas: 10
  template:
    spec:
      #repository: my-org/my-repo
      organization: my-org
      group: org-runner-group
      # Also not working using env variables
      #env:
      # - name: GITHUB_HOST
      #  value: github.myenterprise.com
      # - name: RUNNER_TOKEN
      #   value: ghp_xyz1234567
      # - name: RUNNER_SCOPE
      #   value: org
      # - name: ORG_NAME
      #   value: my-org
      image: ghcr.io/myrepo/myactionsrunner-win2019:latest
      imagePullSecrets:
      - name: runnersecret   
      imagePullPolicy: "Always"
      dockerdWithinRunnerContainer: true
      nodeSelector:
        kubernetes.io/os: windows      
      labels: 
        - ARC
        - windows
```

values.yaml
```yaml
# The URL of your GitHub Enterprise server, if you're using one.
githubEnterpriseServerURL: https://github.myenterprise.com/

# Override GitHub URLs in case of using proxy APIs
#githubURL: ""
#githubUploadURL: ""
########Also not working
#runnerGithubURL: "https://github.myenterprise.com/my-org"

### GitHub PAT Configuration
github_token: "ghp_xyz1234567"
