### DISCUSSION TITLE
[Feature Request] Pull request workflows FILTER based on head branches

### DISCUSSION THREAD

**Discussion by ucguy** [community/community#160748] [Actions]
### Select Topic Area

Product Feedback

### Body

Currently we can run a pull_request workflow based on the head or base branch according to [events documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request).

While we can trigger workflows based on the name of the base branch, we are not able to trigger workflows based on the _head_ branch.  We can only condition _jobs_ based on head branches.

### Current solution:
```
on:
  pull_request:
    types:
      - opened
jobs:
  run_if:
    if: startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'hotfix/'"
 ```

Problems with the current solution:
- If there are multiple jobs within such a workflow, we will have to add a  `if: startsWith(github.head_ref,...` condition to _each_ job within the workflow.
- Even if all jobs within a workflow is skipped, the workflow itself will run and be recorded in github actions as a run every time a pull_request is opened. 

### Desired solution:
```
on:
  pull_request:
    types:
      - opened
    head_branches:
      - 'hotfix/**'
```

Use case: 
- There is a workflow I want to run when I make a PR having a head branch (or feature branch) with the name `hotfix/....` 
- This workflow has multiple jobs within it and if the head branch name does not match `hotfix/`, I have to skip all of them
- Since hotfixes are not that common (thankfully), we don't need to run this workflow all that often but are forced to do so every time we make a PR, because again, there is no filter on the head branch for a pull_request event. 

Temporary Work-around:
- Turn off this workflow whenever we don't need to make a hotfix and turn it back on when we do.
