### DISCUSSION TITLE
What is the appropriate way to set image pull secrets for images being sourced from github to avoid pull rate limits?

### DISCUSSION THREAD

**Discussion by cjlankow-pt** [community/community#160722] [Actions]
What is the appropriate way to set image pull secrets for images being sourced from github to avoid pull rate limits?

For example to use creds for docker:dind, do I need to copy the template.spec shown in the link below and then add configuration for pull secrets?  If so what would that look like?

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#using-docker-in-docker-mode

**Comment by jonjozwiak** [comment]
There is nothing unique to ARC here.  This is just standard Kubernetes setup to [pull image from private registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).  

For example using GitHub Container Registry, create a pull secret in your runner namespace: 

```bash
kubectl create ns my-runner-namespace
kubectl create secret docker-registry ghcr-login-secret --docker-server=https://ghcr.io --docker-username=$GITHUB_USER --docker-password=$GH_PACKAGES_PAT -n my-runner-namespace
```

Then set values.yaml to reference that secret with `imagePullSecrets` when you deploy your helm chart...

```yaml
template:
  spec:
    initContainers:
    - name: init-dind-externals
      image: ghcr.io/actions/actions-runner:latest
      command: ["cp"]
      args: ["-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
      volumeMounts:
        - name: dind-externals
          mountPath: /home/runner/tmpDir
    imagePullSecrets:
      - name: ghcr-login-secret
    containers:
      - name: runner
         command: [/home/runner/run.sh]
         image: ghcr.io/MYORG/MYIMAGE:MYTAG
```
