### DISCUSSION TITLE
`environment:` with `workflow_call`

### DISCUSSION THREAD

**Discussion by dacbd** [community/community#160741] [Actions] [answered]
I'm not sure if I'm doing something wrong or if environments just don't play nice with `workflow_call`

I have a generic job that performs various checks against a cloud provider. As input I have tried:
A) passing the options:
```yml
name: trigging workflow
on:
  workflow_dispatch:

jobs:
  check:
    environment: cloud_one
    uses: my-org/my-repo/.github/workflows/generic-check.yml@main
    with:
      count: 0
    secrets:
      token: ${{ secrets.cloud_token }}
```
```yml
name: triggered workflow
on:
  workflow_call:
    secrets:
      token:
        required: true
        type: string
    inputs:
      count:
        required: true
        type: number
jobs:
  check:
    runs-on: ubuntu-latest
    steps:

```

B) passing an environment string, (the environment contains the options/config items as a secret):
```yml
name: trigging workflow
on:
  workflow_dispatch:

jobs:
  check:
    uses: my-org/my-repo/.github/workflows/generic-check.yml@main
    with:
      myenv: cloud_one
      count: 0
```
```yml
name: triggered workflow
on:
  workflow_call:
    inputs:
      count:
        required: true
        type: number
jobs:
  check:
    # also test with a hardcoded value
    environment: ${{ inputs.myenv }}
    runs-on: ubuntu-latest
    steps:

```
both of these seem to not be working for me. Where A) gives an error like ` Unexpected value 'uses' .github/workflows/file.yml (Line: x, Col: x): Unexpected value 'with` and B) doesn't seem to use the environment( values are blank). 

Both workflows are in the same internal repo, and there are no environment protection rules.

Happy to try and provide any additional context that might be helpful.

**Comment by 0x2b3bfa0** [comment]
# Case A

Environments can only be specified in the triggered workflow, not in the triggering one. Hovering the red wavy underline will reveal a popup menu describing the cause of the error.

![Captura de pantalla 2022-01-18 a las 20 03 53](https://user-images.githubusercontent.com/11387611/150002021-ac2983d8-9bf2-4693-a692-9ef2c5963808.png)

It would be nice to include this gotcha it in the [limitations section](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations) of the official documentation. 

# Case B

## Working example

### `.github/workflows/triggering.yml`

```yaml
on: workflow_dispatch
jobs:
  check:
    uses: user/repository/.github/workflows/triggered.yml@main
    with:
      environment: foo
```

### `.github/workflows/triggered.yml`

```yaml
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  check:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.environment }}
```

## ~Cause of the issue~

~In your example above, there is no `input` declaration for `myenv`~

**Reply by dacbd** [reply]
Sorry in the actual workflow that is present, but it seems that it doesn't actually use the environment, I'll put together a simple test.

**Reply by 0x2b3bfa0** [reply]
Update: it _does_ use the environment in the sense of requiring approvals before running, but secrets aren't being populated. 🙈

**Reply by dacbd** [reply]
That is the issue I found :)

**Reply by 0x2b3bfa0** [reply]
See https://github.com/actions/runner/discussions/1615#discussioncomment-1993002 below. It's feasible, but not precisely intuitive.

**Reply by dacbd** [reply]
Not intuitive is correct

**Comment by 0x2b3bfa0** [comment, marked as answer]
## Example with environment secrets

Given an [environment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) named `example` containing an [environment secret](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-secrets) named `TOKEN`, the following `triggered` workflow will have access to that secret:

### `.github/workflows/triggering.yml`

```yaml
on: workflow_dispatch
jobs:
  check:
    uses: user/repository/.github/workflows/triggered.yml@main
    with:
      environment: example
    secrets:
      token: ${{ secrets.TOKEN }}
```

### `.github/workflows/triggered.yml`

```yaml
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  check:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ secrets.token }}
```
