### DISCUSSION TITLE
Activity type of `merged` for the `pull_request` event

### DISCUSSION THREAD

**Discussion by socketbox** [community/community#160899] [Actions]
### Why are you starting this discussion?

Product Feedback

### What GitHub Actions topic or product is this about?

Workflow Configuration

### Discussion Details

I don't understand why the `closed` event remains ambiguous and why, if I want to run a workflow _only_ when a PR is merged (and not closed prior to merging) I must use some form of conditional check _inside_ the workflow. For example:
```
jobname:
    if:  github.event.pull_request.merged == true
```
PRs are merged as often (far more often?) than they are closed and _not_ merged, so why is `merged` the special case here?

You might ask, "why is this a problem?" The problem comes about when you want a workflow to run on PR merge and _only_ on PR merge. As I understand it, the current idiom is this:
```
name: Build and Deploy Image
on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
    types:
      - closed
  
  jobs:
    jobfoo:
      if:  github.event.pull_request.merged == true
      ...
```
This workflow is triggered whenever a PR is closed regardless of mechanism/reason. That means that even dependabot closing a PR because it's irrelevant or obsolescent will trigger the workflow and create a workflow run. It doesn't matter that every job is skipped with a condition that's predicated on the activity type.
