### DISCUSSION TITLE
Restrict scheduled workflow to repository

### DISCUSSION THREAD

**Discussion by mkurz** [community/community#16109] [Other Feature Feedback, Questions, & Ideas]
When a repository gets forked, scheduled workflows will also run for the fork. This is not desired usually (at least this is my opinion). I guess there are thousands fo forks already which run scheduled workflows, occupying virtual machines and resources for nothing. Also it can get annoying if a scheduled job keeps failing for forks and users that forked such a repo get spammed with notifications that the (scheduled) workflow (of their forked repo) failed.

What can done right now is to check for the repo name to make sure a **job** is nailed to that repo, like done [here](https://github.com/akka/akka/blob/74600b046b58fb735f57ea73bee471af9286c93f/.github/workflows/nightly-builds.yml#L13):
```yaml
jobs:
  akka-cluster-metrics-sigar:
    name: Akka Cluster Metrics Test with Sigar
    runs-on: ubuntu-20.04
    if: github.repository == 'akka/akka' # Only run the JOB when called from the akka/akka repo
    steps:
      ...
```
However this is not a very good solution, since this condition has to be added to each job (besides that, it would be nice to not check for a repo name but if the repo is a fork or not, which is also not possible right now, see [here](https://github.community/t/github-event-repository-fork-context-does-detect-forks-in-scheduled-jobs/185925) and [here](https://github.com/github/feedback/discussions/12269)).

So here is my suggestion how that should actually work:
```yaml
on:
  schedule:
    - cron: "0 0 * * *"
    - repository: "akka/akka" # Only run the scheduled workflow if within that repo
```
or even more generic, checking for forks:
```yaml
on:
  schedule:
    - cron: "0 0 * * *"
    - forks: false # Do not run on forked repos
```
(of course that could be named differently, like `allow_forks` or `run_on_forks`, etc.)

Or, even more generic 😉 
```yaml
on:
  schedule:
    - cron: "0 0 * * *"
    - if: github.repository == 'akka/akka' 
    # or (like mentioned above)
    - if: !github.event.repository.fork
```

What's better about these approches is IMHO that we don't have to care _for each_ job to check for the repo (or fork) and just put the condition in one central place. Plus, it would be obvious that the jobs wouldn't even be tried to run, but instead the whole workflow would  not even fire.

EDIT:
Somehow related: #12180, however that request is about to give _users and orgs_ the possibilty to disallow (on a settings page) the execution of scheduled jobs. My request however gives _the author of a workflow_ the power to define where a scheduled workflow is allowed to run.

Thanks for listening!
