### DISCUSSION TITLE
Getting an error while showing the response for an API request in my GH Actions workflow Error: The operation was canceled.

### DISCUSSION THREAD

**Discussion by TechPro424** [community/community#161091] [Actions]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Workflow Deployment

### Discussion Details

Whenever my workflow runs, I get an `Error: The operation was canceled.` message at the end of the first step (the `Show Response` step) (it's a GET request to an API), and I am unable to figure out why. Please help me out.

Here is my workflow file:

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 0 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Send request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          #https://api.modrinth.com/project/BYfVnHa7/version
          url: 'https://api.modrinth.com/v2/project/BYfVnHa7/version'
          method: 'GET'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
      - name: Update Latest Version
        run: |
          echo "$Latest_Version"
     ```
