### DISCUSSION TITLE
Need help or clarification in creating UWP apps for WM10

### DISCUSSION THREAD

**Discussion by pashgulyash** [community/community#161092] [Programming Help]
### Body

Hey I'm new to coding and decided to create a simple notes application for Windows Mobile 10
I wrote all the necessary code using AI as helper and started looking for a way to compile '.appx'. I found out that I can do this here via repository. Unfortunately, I don't have a PC and there are simply no other options.
When it came to 'build.yml' file, no matter what I did, errors constantly pop up and nothing works. Question: Is it really still possible to compile an application here? It seems to me that the necessary components are either no longer supported by GitHub or simply not found. Help please :(

### Guidelines

- [X] I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.

**Comment by Daxxtropezz** [comment]
Hi @pashgulyash,

Welcome to UWP development! Let's troubleshoot your Windows Mobile 10 app compilation issues:

## 🛠️ Current Limitations for UWP/WM10 on GitHub Actions

Unfortunately, GitHub's Windows runner environment has some limitations for UWP development:
```bash
1. Missing Windows 10 SDK components specifically for Windows Mobile
2. No ARM compiler toolchain available by default
3. Expired certificates for WM10 package signing
```

## 💡 Possible Solutions

### Option 1: Alternative Cloud Build Options
```bash
- Azure Pipelines (free tier available)
- AppVeyor (supports UWP builds)
- Local build via Windows Dev Center (if you can access any PC)
```

### Option 2: Modified GitHub Workflow
Try this basic `build.yml` template (may need adjustments):
```yaml
name: UWP Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Restore NuGet
      run: nuget restore YourSolution.sln
    - name: Build
      run: msbuild YourProject.csproj /p:Configuration=Release /p:Platform=x86
```

### Option 3: Community Resources
```bash
1. Windows Mobile 10 developer Discord groups
2. XDA Developers forum for WM10
3. Unofficial WM10 SDK alternatives
```

## ⚠️ Important Notes
- WM10 support ended in 2020, so tooling is deprecated
- Consider targeting Windows 11 instead if possible
- GitHub may not be the ideal build environment for this scenario

Would you like me to:
1. Share specific error messages from your build attempts?
2. Suggest alternative architectures for your notes app?
3. Help find community-maintained WM10 tooling?

Keep coding! Even with challenges, you're learning valuable skills 💪
