### DISCUSSION TITLE
Job Outputs Not Updating with Empty Values

### DISCUSSION THREAD

**Discussion by antoniivanov** [community/community#161025] [Actions]
### Why are you starting this discussion?

Bug

### What GitHub Actions topic or product is this about?

Workflow Configuration

### Discussion Details

When a job output is set to an empty string (e.g., via $GITHUB_OUTPUT), and the job is re-run with that updated value, the outputs block of the job does not reflect the empty value — it retains the previous non-empty output.  This happens even if the actual step's output is correctly updated to an empty string. This leads to stale output values being propagated to downstream jobs via needs.<job>.outputs.

For example 
```
jobs:
  first-job:
    outputs:
      TEST_OUTPUT: ${{ steps.set_output.outputs.test_output }}
    runs-on: ubuntu-latest
    steps:
      - id: set_output
        run: echo "test_output=$SOURCE_TEST_OUTPUT" >> $GITHUB_OUTPUT
        env:
          SOURCE_TEST_OUTPUT: ${{ secrets.TEST_INPUT }}

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - run: echo "OUTPUT: ${{ needs.first-job.outputs.TEST_OUTPUT }}"
```

Steps:

- Set TEST_INPUT secret to "hello" and run the workflow.
   - ✅ second-job prints hello.
- Change TEST_INPUT secret to an empty string and re-run the workflow from the failed job. <img width="600" alt="image" src="https://github.com/user-attachments/assets/dde139c2-399e-45e3-bae4-b3c2a33157c5" />
  - ⚠️ second-job still prints hello instead of empty output.
- Set TEST_INPUT to a new non-empty value (e.g., "updated") and re-run.
  - ✅ second-job prints updated.
  - 
This indicates that job outputs are not updated correctly when the new value is empty.

**Expected behavior**

When a step sets a job output to an empty string (""), the job output should be updated to reflect that change and not retain any stale prior value.
