### DISCUSSION TITLE
Windows incorrectly referencing locally called actions

### DISCUSSION THREAD

**Discussion by rmvangun** [community/community#161107] [Actions]
### Why are you starting this discussion?

Bug

### What GitHub Actions topic or product is this about?

Actions Checkout

### Discussion Details

I've run in to a really strange case. I'm testing my action by calling it as follows:

```
      - name: Test secret masking
        uses: ./
        with:
          context: test
          workdir: test
          inject-secrets: true
```

I added this `inject-secrets` in a branch I'm working on. I run this action against all platforms including MacOS, Linux, and Windows. Something about just the one workflow is quite odd. I keep getting this warning in the `Test secret masking` step:

```
Warning: Unexpected input(s) 'inject-secrets', valid inputs are ['ref', 'context', 'workdir', 'verbose', 'install-only']
```

All other workflows, including a slightly different workflow in the matrix that also uses Windows, do not report this warning. It's as if it's using the action on the `main` branch vs. the action that I'm attempting to reference via the local path. I can see further evidence of it calling the action that's presently on `main` including references to versions that have not yet been pulled in to the branch.

Have a look at the run here: https://github.com/windsorcli/action/actions/runs/15357750786/job/43220085828

The `test (windows-latest, main)` is the outlier.
