### DISCUSSION TITLE
Silent Changes effecting/breaking conditions for jobs?

### DISCUSSION THREAD

**Discussion by jackwilliamsinfra** [community/community#161335] [Actions] [answered]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Misc

### Discussion Details

Hi there - on the 29th May 2025 there seems to have been a silent change published which effected if statements which were previously working within all of our pipelines on github actions.

Is there any way to confirm what has changed here and if there are any other considerations?

if: success('deploy') && vars.HAS_DB == 'yes' && github.event.inputs.environment != 'prod'

this for example is an if statement which previously worked and no longer does

All the best,

Jack

**Comment by ericsciple** [comment]
Thanks for raising this issue.

I have a repro:

<details><summary>Workflow YAML</summary>

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
  post-deploy:
    if: ${{ success('deploy') }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
```

</details>

`Error when evaluating 'if' for job 'post-deploy'. .github/workflows-lab/ci.yml (Line: 13, Col: 9): Too many parameters supplied: 'success'. Located at position 1 within expression: success('deploy')`

Looking into a fix...
