### DISCUSSION TITLE
How are different triggers handled in a GitHub Action?

### DISCUSSION THREAD

**Discussion by Rod-at-DOH** [community/community#161464] [Actions] [answered]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Misc

### Discussion Details

There's something I don't understand about the triggers which start a GitHub Action running. Suppose it starts with `on`, then a push or pull_request is specified. Then either a branch is mentioned, or a path is specified. Then sometimes a workflow_dispatch may be there.

What I don't understand is what are the conditions which will trigger the build? Is it all conditions must be met? Is it one of them has to be and the others don't have to be? Is it done in a particular order? I'm sorry to be asking such a basic question, but this is becoming a major issue at work, so I need to know.

**Comment by spizzadev** [comment]
When using workflow triggers, only one "condition" has to be met, as you mentioned.

A trigger is an event that starts a workflow, for example:

```
on:
  push:
    paths:
      - 'configs/**'
      - 'scripts/**'
      - 'compose.yaml'
      - '.github/workflows/default.yml'
    branches:
      - '**' # This includes all branches, but excludes tags
  workflow_dispatch: 
  ```
so in order for that workflow to run, any of these scenarios has to happen.
Let's start with **workflow_dispatch** which happens when you press the "run workflow" button on the github website (it only appears if that trigger exists).
Pushing code to the repository will trigger **push**, but in my example, push has further specifications (the indented paths and branches). This means that the workflow will only run if all of those conditions apply. For the example given that would be when the pushed commit is on any branch (not a tag) AND one of those paths has been modified in the pushed commits.

Hope this will help!

**Reply by Rod-at-DOH** [reply]
Hi @Ruixey this does help, but I've got some follow-up questions. Ideally, in our situation, it would be best if the action only runs when a PR is created on a specific branch and it is only for one folder and all sub-folders/files.  So, using your example, I would come up with a YAML file that includes:

```yaml
on:
   pull_request:
      path:
         - 'PROJECTA/**'
      branches:
         - [ 'Development' ]
    workflow_dispatch:
```
However, I suspect that won't work. My guess is that if anyone created a PR that included the subdirectory PROJECTA, then that would trigger a build, regardless of what branch they created the PR on. Am I correct? And if I am, is there a way to restrict a build to just a PR on the Development branch against any file changes in subdirectory PROJECTA?
