### DISCUSSION TITLE
Should the key and restore-keys be unique per Job?

### DISCUSSION THREAD

**Discussion by distante** [community/community#161599] [Actions]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Actions Cache

### Discussion Details

I am a little but lost about the cache keys. We use nx (no cloud) and we want save and restore the `.nx/cache` folder.

Currently all the jobs have this step

```yml
      - name: Restore nx cache
        id: nxcache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nxcache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nxcache-
```

I am first taking the code to refactor and I am wondering if that key is wrong and it should at least contain the name of the job.

I have seen a couple of times a log like "the cache can not be set because other job is writing it". That is why I started wondering.

Any help is appreciated! 

Thanks!
