### DISCUSSION TITLE
Support string list matching in conditional expressions

### DISCUSSION THREAD

**Discussion by axel-h** [community/community#16156] [Actions]
Is there a support for string lists in conditional expression, so checking if something is from a set of strings? The use case is:
```
name: Build
on: .....lots of stuff....
jobs:
  special:
    if: ${{  github.event_name == 'schedule' || github.event_name == 'push'] }}
```
it's a bit nicer if one could just use an "in" keyword: `if: ${{  github.event_name in ['schedule', 'push'] }}`. The closest I have found so far is `contains(fromJson('["schedule", "push"]'), github.event_name)`, credits go to https://stackoverflow.com/a/70142531/831399. But passing a JSON string that is parsed feels a bit strange.
