### DISCUSSION TITLE
pip install fails inside virtualenv

### DISCUSSION THREAD

**Discussion by nessita** [community/community#16163] [Actions]
I'm using Github Actions to run the tests for a project that is still using Python 2 (I want to setup the action to run the test and work on the migration to Python 3). The action is fairly simple, and I have reduced it even further to file what I think it is a bug report.

The error occurs after following these steps (see below for the whole action definition) in an ubuntu-20.04 system:

 * setup python2
 * install virtualenv
 * create a new virtualenv using python2
 * attempt to perform any action with the `pip` command from inside this virtualenv

The error is:

```
     from pip._vendor.six import iteritems
ImportError: No module named six
Error: Process completed with exit code 1.
```

The problem is that the folder `.env/lib/python2.7/site-packages/pip/_vendor` has only a `__init__py` file, and in my Ubuntu 20.04 system, the env has these files in that location:

```
$ ls -1 .env/lib/python2.7/site-packages/pip/_vendor/
__init__.py
__init__.pyc
appdirs.py
appdirs.pyc
cachecontrol
certifi
chardet
colorama
contextlib2.py
contextlib2.pyc
distlib
distro.py
distro.pyc
html5lib
idna
ipaddress.py
ipaddress.pyc
msgpack
packaging
pep517
pkg_resources
progress
pyparsing.py
pyparsing.pyc
requests
resolvelib
retrying.py
retrying.pyc
six.py
six.pyc
toml
urllib3
vendor.txt
webencodings
```

To reproduce, use an action like this:

```yaml
name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '2.7'
    - name: Debug
      run: |
        lsb_release -a
        sudo apt install virtualenv
        virtualenv -p python2 .env
        ls -l .env/lib/python2.7/site-packages/pip/_vendor/
        .env/bin/pip install -U pip
```

UPDATE: Running this exact action in ubuntu-18.04 passes successfully!
