### DISCUSSION TITLE
The registry_package event was not triggered

### DISCUSSION THREAD

**Discussion by sigfrid** [community/community#161739] [Actions] [answered]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Actions Runner

### Discussion Details

I have the action below that publishes a Docker image to GitHub Packages.

```
name: build-and-push

on:
  release:
    types: [published]

jobs:
  build-push:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          push: true
          build-args: RELEASE_TAG=${{ github.ref_name }}
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
```

Now, I'd like to run another workflow when the package is published, so I have created the following (for testing):

```
name: echo
 
on:
  registry_package:
    types: [published]

jobs:
  echo:
    runs-on:  ubuntu-24.04
    
    steps:
      - name: echo
        run: |
          echo $ {{ GITHUB_REF }}
```

But, it's not executed even if the package is correctly published at https://github.com/OWNER/REPO/pkgs/container/REPO

What am I missing here?

Thanks.

**Comment by marioaparcero** [comment]
Hi @sigfrid 

You're very close! The issue is that the registry_package event currently only triggers for packages published via the GitHub API, not when pushing Docker images using GitHub Actions with ghcr.io.

When you publish a Docker image to GitHub Container Registry using docker/build-push-action, the registry_package event does not get triggered. This is a known limitation.

Workaround ✅
If your goal is to run a follow-up workflow after a package is published, here are two possible workarounds:

**🛠 Option 1: Trigger manually from the first workflow**

In your build-and-push workflow, at the end, use the [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) + [GitHub CLI or REST API](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event) to trigger the second workflow manually:


```
- name: Trigger follow-up workflow
  uses: peter-evans/workflow-dispatch@v1
  with:
    workflow: echo.yml
    ref: main
```
> This requires both workflows to live in the same repository.

**🛠 Option 2: Combine logic into a single workflow with conditional jobs**

Use job dependencies or conditions (if:) to run jobs only when the image is successfully pushed.

Until GitHub expands the registry_package event to include container images pushed via GitHub Actions, using workflow_dispatch is the most reliable workaround.

Hope this helps 🙌
