### DISCUSSION TITLE
Add a label information to environments

### DISCUSSION THREAD

**Discussion by cemo** [community/community#16171] [Actions]
The environments are displayed as this:

![image](https://user-images.githubusercontent.com/44156/167228434-779ce1ac-2da7-4281-bd7d-4a8e19ff95df.png)

I would like to see a custom label near it as giving more information such as which version is deployed something like this:

- dev (v1.2.3)
- prod (v1.1.2)

The current configuration is like this:

```
environment:
  name: production_environment
  url: https://github.com
```

it can be something like this:

```
environment:
  name: production_environment
  url: https://github.com
  label: v123
```
