### DISCUSSION TITLE
How to add snk animation is GitHub README?

### DISCUSSION THREAD

**Discussion by mejbaul-km** [community/community#161912] [New to GitHub] [answered]
How to add a snake animation but it is not working so how to do it properly.

**Comment by 0mykull** [comment]
Fill in your username here and download the svg [platane.github.io/snk](https://platane.github.io/snk)

then put this in your profile's README repo 
```
![Alt text](./snakegame.svg)
<img src="./snakegame.svg">
```
optionally you can setup github actions to update daily
https://github.com/Platane/snk?tab=readme-ov-file

**Reply by rajjitlai** [reply]
This must work, I have added it in my profile's Readme.md, you can check it out.

**Comment by rajjitlai** [comment]
![github-user-contribution](https://github.com/user-attachments/assets/c1443366-d070-4a88-9e3f-f56ef980d21d)

This is your svg

**Comment by 8gudbits** [comment, marked as answer]
I assume you are talking about the [snk project](https://github.com/Platane/snk) by Platane. Here are steps to easily get it working.

1. Go to your repo's `Settings` → `Actions` → `General`
![image](https://github.com/user-attachments/assets/479fb832-21aa-477c-aa3f-cf44d33533f9)
2. Scroll all the way down to `Workflow permissions`
3. Select `Read and write permissions` and hit `Save`
![image](https://github.com/user-attachments/assets/eeefcd33-986d-4052-9318-95f91416ed89)
4. Now go to the `Actions` tab and select `set up a workflow yourself`
![image](https://github.com/user-attachments/assets/baa0a975-3487-4833-bc02-bb45c2484a9c)
5. Now write the workflow, here is an example:
```yml
name: GitHub Snk Readme Workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v3
      - name: 2. Generate GitHub Contributions Snake Animations
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 3. Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
```
6. Finally, hit the Commit changes button, it should start working in about a minute.
7. Now just add this to your README to get the snake animation:
```
  <div>
    <picture>
      <source style="min-width: 100%;" media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/mejbaul-km/mejbaul-km/output/github-snake-dark.svg">
      <source style="min-width: 100%;" media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/mejbaul-km/mejbaul-km/output/github-snake.svg">
      <img style="min-width: 100%;" src="https://raw.githubusercontent.com/mejbaul-km/mejbaul-km/output/github-snake.svg" alt="GitHub Snake">
    </picture>
  </div>
```
Note: This will automatically update everyday.
