### DISCUSSION TITLE
Setting up CI/CD pipeline using GitHub Actions for GCE Deployment

### DISCUSSION THREAD

**Discussion by rishav2404** [community/community#161973] [Actions]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Workflow Deployment

### Discussion Details

Hi everyone,

I'm currently working on setting up a **CI/CD pipeline** for my **React-vite app, FASTAPI, Node API** project using GitHub Actions, and I could use some guidance.

My goal is to automate the build and deployment on **Google Compute Engine(GCE)** instance, whenever I push code to the main branch. I’m looking for suggestions or examples on how to structure a basic workflow file for this.

A few things I’d appreciate help with:

- Best practices for setting up a reliable CI/CD pipeline with GCE.
- Explained configuration for GCP or any external setup(if required).
- How to handle environment secrets securely.
- Any starter templates or examples you’ve used that worked well.
- Any helpful tip.

Any help, advice, or references would be really appreciated!

Thanks in advance 🙌

**Comment by SuperSection** [comment]
Let me guide you step-by-step with best practices, configuration tips, and a starter workflow.

---

## ✅ 1. **Overview of the Workflow**

Your GitHub Actions workflow will:

* Run on pushes to the `main` branch.
* Build your React-Vite frontend.
* Package and (optionally) build your FastAPI and Node.js APIs (with Docker or plain Python/Node).
* SSH into your GCE VM and deploy the code (or use SCP to upload + systemd to restart).

---

## 📦 2. **Basic Folder Structure**

Assuming something like this:

```
project-root/
│
├── frontend/           # React-Vite
├── backend/            # FastAPI
├── node-api/           # Node.js API
└── .github/workflows/deploy.yml
```

---

## 🔐 3. **Required External Setup**

### ✅ On Google Cloud:

1. **Create a VM on GCE** with a static external IP.
2. **Install dependencies** (Node.js, Python, Docker, or NGINX depending on your stack).
3. **Create a deploy user** and add your public SSH key (`~/.ssh/authorized_keys`).
4. (Optional) Set up **systemd services** for backend and node APIs for easy restarts.

### ✅ On GitHub:

1. Go to `Settings > Secrets and variables > Actions`:

   * `GCE_HOST`: Your VM IP or hostname
   * `GCE_USERNAME`: Your deploy user
   * `GCE_SSH_KEY`: Your **private** key (in plain text)
   * (Optional) `ENV_FILE`: Base64-encoded `.env` or other config files

---

## 🧪 4. **Starter GitHub Actions Workflow**

```yaml
# .github/workflows/deploy.yml
name: CI/CD to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node (for frontend and node-api)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python (for FastAPI)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Optional: Package backend or node-api if needed

      - name: Upload files to GCE via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          source: "./"
          target: "/home/${{ secrets.GCE_USERNAME }}/app"

      - name: SSH into GCE and restart services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            cd /home/${{ secrets.GCE_USERNAME }}/app
            # Optional: reload env vars
            # source .env
            # Restart services
            sudo systemctl restart fastapi
            sudo systemctl restart nodeapi
```

---

## ✅ 5. **Best Practices**

* **Use SSH keys + a deploy user** with minimal permissions.
* **Don’t hardcode secrets** – use GitHub Encrypted Secrets.
* **Use `.env` files** for config; optionally encrypt or base64-encode for secure transfer.
* **Use systemd or PM2** to manage backend and Node.js processes.
* Set up **health checks** (e.g., via uptime monitoring or GCP load balancer).
* Set up **logs** (journalctl, NGINX logs, etc.) for easier debugging.

---

## 💡 6. **Helpful Tips**

* Want rollback? Consider `rsync` with backups or Git pull on VM.
* For heavier projects, use **Docker + Compose** on the VM.
* Want to scale later? Look into **Google Cloud Run** or **Cloud Build**.

---

## 📚 7. **References**

* [GCE VM setup](https://cloud.google.com/compute/docs/instances)
* [GitHub Actions Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)
* [Appleboy SSH Actions](https://github.com/appleboy/ssh-action)

---

If you want a version using **Docker** or **PM2**, or want to split deployment workflow for each service, let me know and I’ll help you modularize it.
