### DISCUSSION TITLE
Persistent "Invalid workflow file" / YAML parsing error in GitHub Actions for React App deployment

### DISCUSSION THREAD

**Discussion by superdupershaun** [community/community#161933] [Actions]
### Why are you starting this discussion?

Bug

### What GitHub Actions topic or product is this about?

Misc

### Discussion Details

Hey everyone,

I'm encountering an extremely persistent and frustrating issue with GitHub Actions workflows in my repository (`superdupershaun/GymClientPortal`) that I'm using to deploy a React application to Firebase Hosting. Despite extensive troubleshooting, I consistently get an `Invalid workflow file` error with a YAML syntax error on a specific line (e.g., line 16 or 18), even when the YAML appears perfectly valid.

**The Problem:**
My GitHub Actions workflows fail immediately with an `Invalid workflow file` error, pointing to a YAML syntax issue. Here's a typical error message:

This error occurs regardless of whether the file is `firebase-hosting-merge.yml` (auto-generated by Firebase CLI) or a manually created `manual-deploy.yml` / `test-workflow.yml`.

**Context:**
* **Repository:** `https://github.com/superdupershaun/GymClientPortal`
* **App:** React application (created with Create React App principles).
* **Deployment:** Firebase Hosting.

**Troubleshooting Steps Already Taken (and consistently failing):**

1.  **Firebase CLI Initialization:**
    * Ran `firebase init hosting` multiple times, selecting an existing project, `build` for the public directory, single-page app, and GitHub Actions integration.
    * Successfully logged in via `firebase login --reauth`, ensuring GitHub permissions were granted.

2.  **`package.json` Build Script Variations (last tried):
    ```json
    {
      "name": "checkin",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "@testing-library/dom": "^10.4.0",
        "@testing-library/jest-dom": "^6.6.3",
        "@testing-library/react": "^16.3.0",
        "@testing-library/user-event": "^13.5.0",
        "firebase": "^11.9.0",
        "react": "^19.1.0",
        "react-dom": "^19.1.0",
        "react-scripts": "^0.0.0",
        "web-vitals": "^2.1.4"
      },
      "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build", <-- This is the current build script
        "test": "react-scripts test",
        "eject": "react-scripts eject"
      },
      "eslintConfig": {
        "extends": [
          "react-app",
          "react-app/jest"
        ]
      },
      "browserslist": {
        "production": [
          ">0.2%",
          "not dead",
          "not op_mini all"
        ],
        "development": [
          "last 1 chrome version",
          "last 1 firefox version",
          "last 1 safari version"
        ]
      },
      "devDependencies": {
        "autoprefixer": "^10.4.21",
        "postcss": "^8.5.4",
        "tailwindcss": "^4.1.8"
      }
    }
    ```
    * Also tried `"build": "node node_modules/react-scripts/scripts/build.js"` and `"build": "sh -c \"npx react-scripts build\""`.

3.  **GitHub Actions Workflow YAML (Consistently Failing to Parse):**
    This is the latest version I've tried to push, and it consistently throws the YAML error. I've also tried simpler versions.
    ```yaml
    # Manual workflow to deploy to Firebase Hosting
    name: Manual Firebase Deploy

    on:
      workflow_dispatch: # This allows manual triggering from the GitHub Actions tab

    jobs:
      build_and_deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20' # Use Node.js version 20
          - name: Debug: List react-scripts in node_modules
            run: ls -al node_modules/react-scripts || echo "react-scripts directory not found"
          - name: Debug: List react-scripts executable in .bin
            run: ls -al node_modules/.bin/react-scripts || echo "react-scripts executable not found in .bin"
          - name: Install Dependencies
            run: npm ci
          - name: Build React App
            run: npm run build
          - uses: FirebaseExtended/action-hosting-deploy@v0
            with:
              repoToken: ${{ secrets.GITHUB_TOKEN }}
              firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GYM_CHECK_IN_D1BF5 }}
              channelId: live
              projectId: gym-check-in-d1bf5
    ```

4.  **Local Environment Checks:**
    * `cat` command locally consistently shows the YAML file with correct newlines and indentation.
    * Set `git config --global core.autocrlf input`.
    * Performed `git reset --hard origin/main` and `git clean -f -d` to clear local state.

5.  **Direct Editing on GitHub.com:**
    * I have tried to create/edit the `.github/workflows/manual-deploy.yml` (and previously `firebase-hosting-merge.yml`) file directly in the GitHub web editor, pasting the exact YAML content provided above.
    * Even after directly committing via the web editor, the workflow run triggered by that commit still reports the `Invalid workflow file` YAML syntax error on line 16 or 18 (as seen in the workflow logs).

**This issue is extremely persistent and occurs even when the YAML appears visually correct and is committed directly via the GitHub web interface. It seems like a deeper platform-level parsing issue or file corruption related to this repository.**

Any insights or suggestions from the community would be greatly appreciated, as I'm unable to use GitHub Actions due to this fundamental parsing failure.
