### DISCUSSION TITLE
Does step-level separation prevent privilege escalation of GITHUB_TOKEN when the build process is untrusted?

### DISCUSSION THREAD

**Discussion by JanisErdmanis** [community/community#161993] [Actions]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Misc

### Discussion Details

I'm analysing the security implications of my GitHub Actions workflow, which builds and uploads release assets. I am concerned about the isolation between the build steps, which have access to the GITHUB_TOKEN. My workflow runs on Ubuntu-latest and Mac OS, and the upload, with the build step creating artefacts, and the upload step using gh release upload with the GitHub token. The workflow has the following form:
```
name: Build Release Assets

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    name: Build and upload release assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and compress text file
        run: |
          mkdir -p build
          echo "Hello from ${{ matrix.platform }}!" > build/hello-${{ matrix.platform }}.txt
          echo "Built on: $(date)" >> build/hello-${{ matrix.platform }}.txt
          echo "OS: ${{ matrix.os }}" >> build/hello-${{ matrix.platform }}.txt
          
          # Create tar.gz archive
          tar -czf hello-${{ matrix.platform }}.tar.gz -C build hello-${{ matrix.platform }}.txt

      - name: Verify build artifact
        run: |
          ls -la hello-${{ matrix.platform }}.tar.gz
          if [[ ! -f "hello-${{ matrix.platform }}.tar.gz" ]]; then
            echo "Expected artifact not found!"
            exit 1
          fi

      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          ARTIFACT_PATH: hello-${{ matrix.platform }}.tar.gz
        run: |
          echo "Uploading to release: $RELEASE_TAG"
          gh release upload "$RELEASE_TAG" "$ARTIFACT_PATH"
```

My concern is whether a malicious actor could compromise the build process (either through a supply chain attack, a compromised dependency, or a malicious PR that gets merged) and then exploit access to the GitHub token. Specifically, I wonder if they could modify the environment or alias the `gh` command to intercept and exfiltrate the `GITHUB_TOKEN` when used in the upload step. Additionally, could they use the token's permissions to modify the repository contents, create malicious releases, or alter the codebase? I'm also concerned about whether malicious code from the build step could persist and execute during the upload step.
