### DISCUSSION TITLE
How to cache container

### DISCUSSION THREAD

**Discussion by niekdomi** [community/community#162167] [Actions]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Actions Cache

### Discussion Details

I have the following workflow:

```yaml
name: CI

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    timeout-minutes: 5
    container:
      image: archlinux:base-devel

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm --needed \
            clang \
            gcc \
            cmake \
            make \
            cppcheck \
            sqlite \
            systemd-libs \
            libinput \
            libevdev \
            pkgconf

      - name: Run lint
        run: make lint
```

Now is it possible to cache the arch packages? I couldn't find a working solution myself :(
