### DISCUSSION TITLE
Caching an exe stored at /usr/bin

### DISCUSSION THREAD

**Discussion by sigfrid** [community/community#162240] [Actions]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Actions Cache

### Discussion Details

In a workflow, I need to use the [Exo CLI](https://community.exoscale.com/tools/command-line-interface/), which is installed at`/usr/bin/`.

Is there a way to cache it so I don't have to reinstall it every time I run the workflow?

 I tried 

```

    - name: Cache Exo CLI
      id: cache-exo-cli
      uses: actions/cache@v4
      with:
        path: /usr/bin/exo
        key: ${{ runner.os }}-exo-cli
```

But the runner doesn't have access to that path.

Thanks
