### DISCUSSION TITLE
Resource not accessible by integration

### DISCUSSION THREAD

**Discussion by yonas** [community/community#162366] [Actions]
### Why are you starting this discussion?

How do I fix this error?

### What GitHub Actions topic or product is this about?

Permission issues.

### Discussion Details

[Workflow](https://github.com/yonasBSD/github-rs/actions/runs/15537985472/workflow?pr=12):
```yaml
on:
  pull_request:
  push:
    branches:
      - main

name: Test with Code Coverage

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
    test:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # Set the owner, so the token can be used in all repositories
          owner: ${{ github.repository_owner }}

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          cargo test --all-features
```
[Logs](https://github.com/yonasBSD/github-rs/actions/runs/15537985472/job/43741608177?pr=12):
`Error: GitHub { source: GitHubError { documentation_url: Some("https://docs.github.com/rest/users/users#get-the-authenticated-user"), errors: None, message: "Resource not accessible by integration", status_code: 403 }, backtrace: <disabled> }`
