### DISCUSSION TITLE
Releases published when author is `github-actions` won't fire `push` events

### DISCUSSION THREAD

**Discussion by mkurz** [community/community#16244] [Actions]
Having [set up an action](https://github.com/playframework/playframework/blob/7b36b07739b9b8fcdf80e7b3f487ce8fc765f57b/.github/workflows/publish.yml#L3-L7) with the `on` `push` `tags: ["*"]` event, this `push` event does not fire when a release is created via the GitHub releases UI **when the author of the release draft is the special `github-actions` user**, even when the release gets published later by an admin of the repo:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/644927/167232248-283ffe8d-7bc5-4105-a3cd-33d718fc9fe7.png">

But the event does indeed fire when another, "normal" GitHub user creates a release draft (of course, always assuming that a release gets published with a non-existing tag). The strange thing is the tag itself (not the event) actually does get created even when the author is `github-actions`, however only the events won't fire...

We are using [Release Drafter](https://github.com/release-drafter/release-drafter) which [automatically creates release drafts](https://github.com/playframework/playframework/blob/7b36b07739b9b8fcdf80e7b3f487ce8fc765f57b/.github/workflows/release-drafter.yml#L18) for us. Since release drafter is a GitHub action, it will run with the `GITHUB_TOKEN` and therefore the user `github-actions`is used to create (or edit) a draft.

I guess the problem is that when now publishing a release (again, with a non-existing tag), GitHub in the background somehow checks the permissions of the author and since that author is not part of the repo or the organization it doesn't have permissions (?) Or is it that `GITHUB_TOKEN` was used at the time the release was created? However, if you will tell me that this is the reason and we should use a personal token, I would argue why? Because the user that does create the release by hand, clicking on the publish button of the draft release, is already a "real" user, having admin permissions to the repo, so I think that is the user that should be used to check permissions against and therefore there is no reasons to not send the `push` event.

IMHO this is a bug in GitHub.

What do you think?
Thanks for your time!

EDIT: I now created an entry in the community forum as well, just to make sure this gets enough attention: https://github.community/t/bug-publishing-releases-manually-wont-fire-push-event-when-author-is-github-actions/249671

**Comment by mkurz** [comment]
OK, I am pretty sure now this is a bug in GitHub actions. That's because a `release` event actually **does** trigger, but, like reported a `push` event does not:
```yaml
on:
  push:
    branches:
      - main
    tags:
      - '**'                         # does NOT trigger when release author is github-actions
  release:
    types: [published]               # DOES trigger even when release author is github-actions
```

Here is a repository which reproduces the problem: https://github.com/mkurz/GHA-tag-push-problem (each time the release was done in the GitHub UI, by clicking the "Publish" button of the release draft):
* [This release](https://github.com/mkurz/GHA-tag-push-problem/releases/tag/1.0.0), author "mkurz", triggered both the `push` ([workflow here](https://github.com/mkurz/GHA-tag-push-problem/actions/runs/2294383083)) and the `release`event ([workflow here](https://github.com/mkurz/GHA-tag-push-problem/actions/runs/2294383095)).
* [This release](https://github.com/mkurz/GHA-tag-push-problem/releases/tag/2.0.0), author "github-actions" (created by the release drafter workflow) did only trigger the `release` event ([workflow here](https://github.com/mkurz/GHA-tag-push-problem/actions/runs/2294427448)), but not the push event

There are other reports already:
* https://github.community/t/pre-release-creating-tag-does-not-trigger-push-event/242346
* https://github.community/t/push-tags-action-not-triggered-when-draft-release-published/182283
* https://github.com/release-drafter/release-drafter/issues/876#issuecomment-849644457

**Comment by vedantmgoyal9** [comment]
```yaml
on:
  release:
    types: [released] # does NOT trigger when release author is github-actions
```
I don't know, but I think this is a bug too.

**Reply by mkurz** [reply]
Seems like the same problem, yes.

**Reply by vedantmgoyal9** [reply]
@github-staff please take a view. This needs to be solved on an urgent basis. It's making our CI setup more complex.

**Reply by jdforsythe** [reply]
@vedantmgoyal2009 you can use release type "published" to catch this - it's the workaround we're using:

https://github.com/release-drafter/release-drafter/issues/876#issuecomment-849644457

**Reply by vedantmgoyal9** [reply]
@jdforsythe if I would do for published event, I wouldn't be able to differentiate between draft, pre-release and release. I need to have my workflow run only on a release.

**Reply by jdforsythe** [reply]
@vedantmgoyal2009 we don't do pre-release, but we use the release-drafter to create draft releases for every one of our releases we eventually publish, so I can say for sure that "published" doesn't fire on draft releases.

Example - we have our docker images publish to Docker Hub when we convert a draft release (from the release-drafter action) into a full release in the UI:

```yml
on:

  ## when a release is published (not drafts)
  release:
    types: [published]

  ## on all pull requests
  pull_request:

jobs:

  ## build image for testing purposes
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      ## ...

  ## build and publish image on release
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      ## ...
```

I'm sure there's something additional in the `github` object that would identify pre-releases if this happens to fire on those, but again it does not fire on draft releases.
