### DISCUSSION TITLE
Allow `mailto:` urls in `ISSUE_TEMPLATE/config.yml`

### DISCUSSION THREAD

**Discussion by bennypowers** [community/community#16247] [Projects and Issues]
`config.yml` only allows linking to websites, but there are cases in which it would be preferable to send an email:

```yml
blank_issues_enabled: false
contact_links:
  - name: ❓Usage Questions
    url: https://github.com/scope/repo/discussions/new?category=q-a
    about: Questions about how to use the software? Please ask them in Discussions
  - name: 💡Ideas
    url: https://github.com/scope/repo/discussions/new?category=ideas
    about: Ideas for new features
  - name: Code of Conduct Violation
    url: mailto:coc@scope.com
    about: Please report code of conduct violations here.
```

This fails YML schema violation, and the Code of Conduct Violation option does not appear on the template-picker form.
