### DISCUSSION TITLE
Install private packages locally with SSH authentication instead of PAT

### DISCUSSION THREAD

**Discussion by Spielboerg** [community/community#16240] [Packages]
Currently it is only possible to install private packages from Github Packages with a PAT: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages

It would be great if not all developers had to create a PAT just to install the package, but could just use the already existing SSH authentication.

**Comment by ankit-toddleapp** [comment]
Is there any update on this!?

**Reply by pranavq212** [reply]
still looking for this, any updates?

**Comment by mr-rpl** [comment]
+1

**Comment by shankar-ccm** [comment]
I have github packages in my company private github account and I want to install those packages in another project using dependency in package.json and npm.

Below are the steps I am following.

created .npmrc file
registry=https://registry.npmjs.org/
@{scope}:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}

added dependecy in package.json
"@{scope}/name": "1.0.3",

created PAT for organization

npm install in github action

name: Install Dependencies
run: |
npm cache clean --force
npm install
env:
NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
but I am getting 404 error like below

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@{scope}%2fname - Not found
npm ERR! 404
npm ERR! 404 '@{scope}/name@1.0.3' is not in this registry.

any suggestions or solutions are appreciated.

**Reply by Spielboerg** [reply]
I'm using the [setup node action](https://github.com/marketplace/actions/setup-node-js-environment) instead of a `.npmrc` file:
```yaml
steps:
  - name: Check out latest repository code
    uses: actions/checkout@v3

  - name: Setup node
    uses: actions/setup-node@v3
    with:
      node-version: 16
      registry-url: 'https://npm.pkg.github.com'
      scope: '@{scope}'

  - name: Install dependencies
    run: npm ci
    env:
      NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
```
---
Note: `@{scope}` is a placeholder and must be replaced with the name of your organization, e.g. `@my-org`.
