### DISCUSSION TITLE
Our workflows are all failing intermittently due to Unauthorized (401)

### DISCUSSION THREAD

**Discussion by LucasDreyerSanlam** [community/community#162465] [Actions]
### Why are you starting this discussion?

Bug

### What GitHub Actions topic or product is this about?

Actions Runner

### Discussion Details

We have workflows which pull internal dependencies (Java packages) that are published by other Github projects to Github's Maven central (maven.pkg.github.com)

Our builds work locally (even after deleting the local Maven repo), and fail intermittently in our PR and merge pipelines. Each pipeline repeats the build process several times (e.g. one for unit tests and one for integration tests). Sometimes one passes and the other fails, but given the high failure probability, there's always at least one that fails.

This has been blocking our PR and merge pipelines for almost 24h.

Error from the actions runner:
```
Error:  	Caused by: The following artifacts could not be resolved: a.b.c:pom:0.0.6 (absent): Could not transfer artifact a.b.c:pom:0.0.6 from/to abc (https://maven.pkg.github.com/a/b): status code: 401, reason phrase: Unauthorized (401)
Error:  
```
The 401 is misleading, because it's intermittent and our Github API tokens haven't changed. Maybe the runner is internally being given the wrong token, or maybe the Github auth server is broken.

We saw the exact same behaviour two weeks ago during https://www.githubstatus.com/incidents/2fk03fzv6zk0, implying the same problem has reoccured.

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by jannikrichter** [comment]
Same here, quite frustrating

**Comment by stianjensen** [comment]
Seeing an increase in this behavior the past 3 days.

**Comment by alex-z0** [comment]
We also started having this issue for the past couple of days

**Reply by alex-z0** [reply]
I managed to find a workaround.
Looks like the issue is now packages require not just a github token (server.password), but also a user name along with it (basically, the username of the token issuer). However, the default behaviour of `setup-java` action has not adapted that change yet. However, it allows you to customize the `settings.xml` it generates: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven
In our setup we use a separate repository as a maven artifactory, so previously every other repository had it as a maven repository and as a distribution management repository, and the pipelines had secrets for reading packages and uploading packages that contained github tokens and were transferred to maven through `env: GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_READ_TOKEN }}` as per the documentation of `setup-java`.

So, what I did:
- added new secrets to the repo containing token creators' usernames
- adjusted `setup-java` action to generate `settings.xml` with both server.username and server.password (see example below)

Build workflow:
```yaml
on:
  workflow_call:
    inputs:
      javaVersion:
        default: '25'
        required: false
        type: string

env:
  # environment variables to be used in settings.xml generated by setup-java
  MAVEN_SERVER_USER: ${{ secrets.MAVEN_GITHUB_READ_TOKEN_OWNER }}
  MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_GITHUB_READ_TOKEN }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: 'corretto'
          cache: 'maven'
          server-id: github
          server-username: MAVEN_SERVER_USER # this is an environment variable name
          server-password: MAVEN_SERVER_PASSWORD # this is an environment variable name
# the rest of the build
```

pom.xml:
```xml
	<repositories>
		<repository>
			<id>github</id>
			<url>https://maven.pkg.github.com/xxx/maven-artifactory</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
```
The same works with uploading packages: just use a token with write access and configure settings.xml to suit `distributionManagement` as well.
