### DISCUSSION TITLE
Getting a "This branch had an error being deployed", but it shouldn't be involved

### DISCUSSION THREAD

**Discussion by Rod-at-DOH** [community/community#162400] [Actions] [answered]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Workflow Configuration

### Discussion Details

(I don't know if I've chosen the correct workflow action category, I have I have.)

We've got a situation in which a coworker has created a PR and assigned it to me. He created from a branch he's been working on. We have a workflow in place, which should handle it, when the PR is approved and it is sent to the Development branch (the one the .yml file will work on). But for some reason when he created the PR it ran and gave this error:

> This branch had an error being deployed

Here's what we have in the YAML:

```yaml
on:
  push:
    branches: 
      - Development
    paths:
      - '.github/workflows/CARAEmailer-Dev.yml'
      - 'CARAEmailer/**.*'
```

I don't understand why it is running, when he's not creating the PR in the Development branch and he is not editing the .yml file. I could use help, please.

**Comment by JonathanZawadke** [comment, marked as answer]
The workflow is triggered because creating a pull request can trigger a push event. When the PR is created against the Development branch, GitHub creates a test merge commit to check for conflicts. This action is treated as a push to the Development branch, which is why your workflow runs.

This is expected behavior. The paths filter only applies after the workflow has already been triggered by a push to the Development branch.

To run the workflow only when a PR is actually merged into Development, you should change your trigger:

YAML

```
on:
  pull_request:
    types:
      - closed
```
Then, add a condition to your job to ensure it only runs when the PR was merged into the Development branch:

YAML

```
jobs:
  your-job-name:
    if: github.event.pull_request.merged == true && github.base_ref == 'Development'
    runs-on: ubuntu-latest
    steps:
      # ... your steps
```
This will prevent the workflow from running on PR creation.
