### DISCUSSION TITLE
How to Allow Only GitHub Actions SSH Access to My Windows Deployment Server via Fortinet?

### DISCUSSION THREAD

**Discussion by mehmetkalayci** [community/community#162487] [Actions] [answered]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Misc

### Discussion Details

Hi everyone,

I have a Laravel project hosted on a Windows server, and I want to automatically deploy it via GitHub Actions using SSH.

For security reasons, I want to restrict SSH access so that only GitHub Actions runners can connect, and block all other SSH attempts. I am using Fortinet as the firewall.

✅ My Setup:
Server: Windows Server (IIS + PHP + Laravel)

Deployment method: SSH from GitHub Actions

Firewall: Fortinet (GUI access)

GitHub Actions uses SSH key authentication

🎯 What I Want to Achieve:
Allow SSH (port 22) access only from GitHub Actions IP addresses

Deny all other SSH access attempts

Deploy the Laravel app via GitHub Actions automatically on push to main

❓ My Questions:
What is the best way to restrict SSH access to only GitHub Actions using Fortinet firewall?

GitHub publishes [their IP ranges here](https://api.github.com/meta). Can I safely use these in Fortinet as source IPs?

Since GitHub IPs may change, is there a recommended way to keep Fortinet rules updated automatically (via API or scripting)?

Has anyone implemented a similar system for a Windows deployment using GitHub Actions + Fortinet?

Any guidance or examples would be greatly appreciated!

Thanks in advance 🙌

**Comment by sammyifelse** [comment, marked as answer]
Hi! 👋 I've set up a similar deployment pipeline using GitHub Actions and SSH, and I can help address your questions point by point:

🔒 Restricting SSH Access to GitHub Actions Only (via Fortinet):
Yes, you can restrict SSH (port 22) access to only GitHub Actions runners by allowing connections only from GitHub's IP ranges and blocking all others in your Fortinet firewall.

Steps:
Get GitHub Actions IPs:
GitHub publishes their IPs here:

arduino
Copy
Edit
https://api.github.com/meta
Look under the actions section for the current IP ranges.

Create Fortinet Firewall Rules:

Allow SSH (port 22) only from the GitHub Actions IP ranges.

Deny all other SSH access as a separate rule with lower priority.

In the Fortinet GUI:

Go to Policy & Objects > IPv4 Policy

Create a new rule for each GitHub IP range as source

Destination: Your Windows Server IP

Service: SSH (port 22)

Action: Accept

Schedule GitHub IP Updates:
GitHub IPs can change. To keep Fortinet rules updated:

Use a scheduled script to fetch GitHub IPs via API.

Fortinet supports automation via FortiManager or FortiOS API — you can script updates to the address objects.

Alternatively, use a FortiGate automation stitch (if supported) to refresh the IP list on a schedule.

 Laravel Deployment via GitHub Actions on Windows Server:
Even though your server is Windows (IIS + PHP + Laravel), SSH deployment is totally feasible. Your GitHub Actions workflow would look something like this:

```
yaml
Copy
Edit
name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd path/to/your/project
            git pull origin main
            composer install --no-dev
            php artisan migrate --force
            php artisan config:cache
```
Make sure:

SSH is enabled on your Windows Server (you can install OpenSSH Server via Windows Features).

You've added your GitHub Actions SSH public key to authorized_keys.

 Summary:
 Restrict SSH via Fortinet using GitHub IPs from https://api.github.com/meta

🔄 Automate updates using Fortinet API or scripting

 Use SSH with GitHub Actions to deploy Laravel on Windows Server

Let me know if you need help with the exact Fortinet script or GitHub workflow YAML!
