### DISCUSSION TITLE
Github actions with inherited workflows do not populate the security tab

### DISCUSSION THREAD

**Discussion by bio-boris** [community/community#162528] [Code Security] [answered]
### Select Topic Area

Bug

### Body

I'm not sure if this is a bug, or intended, but it seems like using a github action from your `.github` repo doesn't properly update the security tab.

For example, this action uses a github action from my .github repo

```
name: Run Trivy
on:
  pull_request:
jobs:
  trivy-scans:
    uses: bio-boris/.github/.github/workflows/reusable_trivy-scans.yml@add-sbom
    secrets: inherit
```

which calls
```
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '22 6 * * 6'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
```

The job runs fine
<img width="785" alt="image" src="https://github.com/user-attachments/assets/0a76a343-4e87-4d3b-88d7-c95454299be9" />

However, the security tab doesn't show trivy scans results.

<img width="785" alt="image" src="https://github.com/user-attachments/assets/5ce09195-c918-43d9-b5ce-60f0cf5d031f" />

However, if I directly use that action in the repo, the security tab is populated with trivy scans.

Does anyone know if is this intended behavior or a bug on github?

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by bio-boris** [comment, marked as answer]
This seems like it was user error. The result get uploaded to the PR, rather than the target branch.  The solution is to modify the  action to include the following to target the branch

```
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          ref: 'refs/heads/${{ github.base_ref }}'
          sha: '${{ github.event.pull_request.head.sha }}'
```
