### DISCUSSION TITLE
Trigger workflow job on both push and pull request against specific branches

### DISCUSSION THREAD

**Discussion by thegrew** [community/community#162619] [Actions]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Workflow Configuration

### Discussion Details

Hi All
I'm a bit stuck trying to get this to work, and I hope you can be of help. I currently have a workflow job that is set to trigger for each of my environments (dev, staging and prod). The code to do this looks like this:
on: 
    pull_request:
        branches:
            - dev
            - staging
            - prod
        paths:
            - iac/**
            - .github/workflows/infrastructure-pipeline.yaml
            - .github/workflows/_terraform_pipeline.yaml
    push:
        branches:
            - dev
            - staging
            - prod
        paths:
            - iac/**
            - .github/workflows/infrastructure-pipeline.yaml
            - .github/workflows/_terraform_pipeline.yaml

This triggers the main workflow correctly, but within the infrastructure-pipeline.yaml I am then trying to filter specific sub-jobs based on each environment (to pass different variables to the _terraform_pipeline.yaml.
Currently I have the following code which doesn't appear to be evaluating correctly and is currently skipping where I wouldn't expect it to:
jobs:
  development:
    if: ${{ (github.ref == 'refs/heads/dev') || (github.base_ref == 'refs/heads/dev')}}
    uses: ./.github/workflows/_terraform_pipeline.yaml
    with:
(A whole bunch of variables)

  staging:
    if: ${{ (github.ref == 'refs/heads/staging') || (github.base_ref == 'refs/heads/staging')}}
    uses: ./.github/workflows/_terraform_pipeline.yaml
    with:
(A whole bunch of different variables)

What am I doing wrong here?

**Comment by R41CY** [comment]
---

I'm trying to trigger different sub-jobs in my reusable workflow based on the target branch (dev, staging, prod). The main workflow triggers fine, but the conditional logic inside each job isn't behaving as expected—some jobs are being skipped even when I think they should run.

Here’s a simplified version of what I’m doing:

```yaml
jobs:
  development:
    if: ${{ (github.ref == 'refs/heads/dev') || (github.base_ref == 'refs/heads/dev') }}
    uses: ./.github/workflows/_terraform_pipeline.yaml
    with:
      # dev vars

  staging:
    if: ${{ (github.ref == 'refs/heads/staging') || (github.base_ref == 'refs/heads/staging') }}
    uses: ./.github/workflows/_terraform_pipeline.yaml
    with:
      # staging vars
```

The issue seems to be with how `github.ref` and `github.base_ref` are evaluated. It works sometimes on `push`, but breaks on `pull_request` events.

---
