### DISCUSSION TITLE
Advanced Dev Puzzle Pack – asyncio Hangs, Tag-Only GitHub Actions,

### DISCUSSION THREAD

**Discussion by Felixcheu** [community/community#162787] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

how can I tweak GitHub Actions so it only builds a Docker image on tagged commits instead of every push; why aren’t my React.memo’d child components skipping re-renders....

**Comment by vpexxi** [comment, marked as answer]
umm.... GitHub Actions, just switch your trigger to tags instead of branches—e.g.:

```yaml
on:
  push:
    tags:
      - '*'  # or something like 'v*.*.*' if you only tag with versions
```

Or keep your push trigger and add an `if:` check in your job:

```yaml
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # …build your Docker image…
```

Either way, it only fires on tag pushes, not every commit.

With React.memo, remember it only does a shallow prop compare—so if you pass inline objects, arrays, or functions each render, it’ll think “new prop!” and rerender. The fix is to wrap callbacks in `useCallback`, memoize objects/arrays with `useMemo`, or give React.memo a custom compare function so it really skips re-renders when you want.
