### DISCUSSION TITLE
What is the second column in the Actions for?

### DISCUSSION THREAD

**Discussion by Rod-at-DOH** [community/community#162786] [Actions] [answered]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Misc

### Discussion Details

When we create a PR and successfully run it, an entry on the Actions page for that repo on GitHub.com, will appear. The left most column has the value of the `name` from the .yml file, some data from the commit message that the developer entered when they made their commit, the number of runs of that .yml file, etc. The second column has branch names. The third column has how long ago the workflow ran and how long it took to run. The fourth column is 3 dots for additional information.

My question concerns the second column. What branch is displayed there? What I mean is that in previous iterations of the .yml file it looked like it was showing us the name of the destination branch when the PR succeeded and merged to the destination branch. However, we were experiencing other side issues, so I asked in this forum/discussion group for help, which I received 😄. 
Now that we've prevented two builds from running and making it so that only one build is run upon closing the PR and successfully merging the changes to the destination branch, the branch displayed in that second column is the originating branch, not the destination branch. Is the source branch the branch that is meant to be displayed in the second column?

**Comment by vpexxi** [comment]
well...gitHub Actions always shows you the branch or ref that actually kicked off that workflow run, so if your job is firing on pull_request events ,, the second column will list the PR’s source branch (the head ref) because that’s what triggered it. If you want to see your destination branch there, you’d need to let the workflow run on the push event to that branch (e.g. push: branches: [main]) rather than only on the pull_request trigger....

**Reply by Rod-at-DOH** [reply]
Oh WOW. We tried using push, but that meant that we would get 2 actions; the first when someone created the PR and the second when the PR ran. For some reason, the YAML file which was causing multiple runs had this at the beginning of the file:

```yaml
name: Emailer Development Deployment

on:
  push:

    branches: 
      - Development
    paths:
      - '.github/workflows/Emailer-Dev.yml'
      - 'Emailer/**.*'

jobs:
  build-Emailer:

    environment: 
      name: ${{ github.ref_name }}
``` 

And what we have now is this:

```yaml
name: Emailer Development Deployment

on:
  pull_request:
    types: closed
    branches: 
      - Development
    paths:
      - 'Emailer/**.*'

jobs:
  build-Emailer:
    if : ${{ github.event.pull_request.merged == true && github.base_ref == 'Development' }}
    environment: 
      name: ${{ github.ref_name }}
```
