### DISCUSSION TITLE
Can I use pre-uploaded jars from target folder in release action?

### DISCUSSION THREAD

**Discussion by Markus-Renner** [community/community#162726] [Actions]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Workflow Configuration

### Discussion Details

I have an OSS Java project that is generating a jar based on a non-public idl (the resulting jar is public, though). Therefore I cannot put the idl into the repository and I cannot build the jar in the GitHub Action itself. I chose to build the project manually on my local machine, commit the artifacts to the repository (to the target folder, direct children) and then let the GitHub Action publish them to Maven central.

Now while that was working and the release of the jar to Maven central was successful, the published jar is "empty" and does not contain the generated source code (only Manifest.mf and such things). That makes me assume that during the Action the previously locally built and uploaded jars in the target folder were replaced by newly built but then empty jars.

Can anybody confirm or falsify my assumption and therefore, that my approach to use pre-uploaded jars in an Action for publishing them cannot or actually should work? If not possible in this way, how could I achieve my goal to publish the jar, although I cannot build it inside the Action? Thanks for any hints on what I am doing wrong or could do differently!

Here is my GitHub Action code:

```
name: Deploy to Maven Central (manual artifacts)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check artifacts
        (step checks existence of the artifacts I upload manually to target folder)

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          server-username: MAVEN_USER
          server-password: MAVEN_PW
          server-id: central

      - name: Import GPG private key
        run: |
          mkdir -p ~/.gnupg
          echo "$MAVEN_GPG_KEY" | gpg --batch --import
          echo "$MAVEN_GPG_PASSPHRASE" | gpg --batch --passphrase-fd 0 --import-ownertrust
          gpg --list-secret-keys --keyid-format LONG
        env:
          MAVEN_GPG_KEY: ${{ secrets.GPG_SECRET_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

      - name: Release package to Maven central
        env:
          MAVEN_USER: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PW: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_SECRET_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
        run: mvn deploy -Prelease -DskipTests
```
