### DISCUSSION TITLE
How to trigger shared workflow on PR title change

### DISCUSSION THREAD

**Discussion by Enigo** [community/community#163002] [Actions]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Workflow Configuration

### Discussion Details

I have a shared workflow that is configured as Organization ruleset that ensures that the PR title follows a specific regex. The shared workflow has the following configuration:

```
on:
  workflow_call:
  pull_request:
    types: [ opened, edited, synchronize ]
```

That obviously works in the repo where this workflow is defined, but in any other repo where it is imposed the change of PR title doesn't trigger the workflow re-run and it has to be done manually.
is that a current limitation of shared workflows or something is missing in my configuration?
