### DISCUSSION TITLE
Simplify Actions Steps with Checks

### DISCUSSION THREAD

**Discussion by daniel-butler-irl** [community/community#16312] [Actions]
As a developer, I would like to have the process of adding checks to steps in jobs simplified. I am moving from Jenkins to actions and my setup has always been to add a check for each step in a pipeline so developers could instantly see which part failed without leaving the pull request. 
Example:
![Screenshot 2022-05-10 at 11 57 13](https://user-images.githubusercontent.com/10742925/167614291-b78c2b94-39a1-4939-b6ac-dcde2321eedc.png)

I know how to implement this in actions but it would be much cleaner to add a built-in flag to the steps just to enable it as a check. I envision a syntax something as simple as:
```YAML
...
jobs:
  PIPELINE:
...
  steps:
...
     # Run tests
     - name: Run Tests
       isCheck: true
       run: make run-tests
...
``` 
When `isCheck` is true, on a run of the workflow it would create a new check if it does not already exist, set its status to pending then on step completion set the status to the appropriate value. The check would just link directly to the step in Actions.
