### DISCUSSION TITLE
PHP 8.0 segmentation fault on latest ubuntu image

### DISCUSSION THREAD

**Discussion by bkdotcom** [community/community#163291] [Actions] [answered]
### Why are you starting this discussion?

Bug

### What GitHub Actions topic or product is this about?

Actions Runner Image

### Discussion Details

I am encountering segmentation faults with latest ubuntu build and php 8.0

```
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.0']

    ...

    steps:
    - name: Install PHP
      uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
      with:
        php-version: ${{ matrix.php-version }}
        extensions: iconv, intl, mysqli, oauth
        ini-values: error_reporting=-1, memory_limit=512M, post_max_size=256M, xdebug.mode="coverage,debug,develop"
        coverage: xdebug #optional

```

## output of problem build :

`php -v` 

```
PHP 8.0.30 (cli) (built: Jun 10 2025 05:22:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.30, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.30, Copyright (c), by Zend Technologies
    with Xdebug v3.4.3, Copyright (c) 2002-2025, by Derick Rethans
curl version: 8.5.0
```

## previous build with no problem

```
PHP 8.0.30 (cli) (built: Oct 17 2024 20:32:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.30, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.30, Copyright (c), by Zend Technologies
    with Xdebug v3.3.2, Copyright (c) 2002-2024, by Derick Rethans
curl version: 8.5.0
```

~~is there a way to specify the previous / specific build?~~
edit: it's the same ubuntu version:  `24.04.2`
but different runner builds (`20250602.3.0`  vs `20250615.1.0`)

I'd be happy to provide more info

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by bkdotcom** [comment]
More information:

Set-Up-Job output:

previous working build
```
Operating System
  Ubuntu
  24.04.2
  LTS
Runner Image
  Image: ubuntu-24.04
  Version: 20250602.3.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250602.3/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250602.3
```

current segmentation fault build
```
Operating System
  Ubuntu
  24.04.2
  LTS
Runner Image
  Image: ubuntu-24.04
  Version: 20250615.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250615.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250615.1
```

It's the same code being checked out / being tested...    
My library is a bit unusual in that it's actually tested over a large range of PHP versions

```
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
```
only php 8.0 is experiencing the issue
