### DISCUSSION TITLE
How to Automatically Close Stale Issues in a GitHub Repository?

### DISCUSSION THREAD

**Discussion by iAmRubayet1** [community/community#163285] [Other Feature Feedback, Questions, & Ideas] [answered]
Hi all,
I want to automatically close issues that haven’t been updated in a while to keep the repo clean. Is there a way to do this using GitHub features or workflows?

**Comment by karthik1841** [comment]
Create a file:
.github/workflows/stale.yml
 
add this content 
name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has not been updated in a while.'
          close-issue-message: 'Closing this issue due to inactivity.'
          days-before-stale: 30
          days-before-close: 7

**Comment by feedofmri** [comment, marked as answer]
Yes, you can use [[GitHub Actions](https://github.com/features/actions)](https://github.com/features/actions) along with a prebuilt action like `actions/stale` to automatically mark and close stale issues.

---

**I. Setup Instructions**

1. In your repository, create a workflow file at:

```
.github/workflows/stale.yml
```

2. Add the following example configuration:

```yaml
name: Close stale issues

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity.'
          close-issue-message: 'Closing this issue due to prolonged inactivity.'
          exempt-issue-labels: 'keep-open'
```

---

**II. What It Does**

* Marks issues as **stale** after 30 days of inactivity
* Closes them 7 days later unless updated
* Skips issues with a label like `keep-open` (you can customize this)
