### DISCUSSION TITLE
Copilot Coding Agent session overwrites custom actions/checkout options silently

### DISCUSSION THREAD

**Discussion by darcien** [community/community#163397] [Copilot Conversations]
### Select Topic Area

Product Feedback

### Copilot Feature Area

Copilot Agent Mode

## Problems

I have a custom `.github/workflows/copilot-setup-steps.yml` with `actions/checkout@v4` step.
From my understanding, the steps in the `copilot-setup-steps` should have no restriction.

But from my observation, when Copilot Coding Agent starts a new session, `actions/checkout@v4` custom options are being overwritten.

I'll give an example
```yaml
# .github/workflows/copilot-setup-steps.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Note how I have custom options here
          fetch-depth: 0
          persist-credentials: true
```

These options are respected just fine if the workflow runs are triggered not via agent session, e.g. via PR push. Even if the one pushing the PR is the coding agent. I've tested it because I'm making these changes using agent.

This is the log after agent pushed the updates:

![image](https://github.com/user-attachments/assets/767b29b0-6cfb-4080-8c9c-c9e597a81347)

After custom workflow has been merged, I created a new issue and assigned copilot to it.

Note how the options for `actions/checkout` are overwritten in the agent session:

![image](https://github.com/user-attachments/assets/ed792f1c-3381-4dcb-89b0-09439007c89b)

## Questions

- Is this an expected behavior?
- If this is expected, shouldn't this be documented? And what about other actions?

## Expectations

- Either this should be clearly documented,
- or copilot should yell at me if it's going be to overwritten,
- or this is a bug and should not happen in the first place.

## Use case

Specific to my use case, I need other branches to be available locally in the agent session.
The common solution here is use the persisted git credentials from `actions/checkout` in next step to manually call `git fetch`. These credentials will be cleaned up in the post job step automatically anyway.

## Workaround?

As temporary workaround, I'm using the built in GH token from the action env to authenticate with GH and do fetch.

```yaml
      - name: Fetch main branch
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin main:main
```

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Reply by astafan8** [reply]
Any ETA on addressing this issue? It prevents my team to use GitHub Copilot on our repositories. The documentation claims that custom checkout steps are allowed and they will be respected, however in reality that's not the case.

**Comment by astafan8** [comment]
experiencing the same issue in microsoft/qcodes repo

**Comment by stevoland** [comment]
@darcien Nice workaround, thanks I will try this.

This decision to not persist git credentials has obviously been made deliberately (for security?) and it would be great for github to at least provide their reasoning and whether this feature loss is likely to be long-term.

The impact is huge. Here's [a run from June](https://github.com/gisfromscratch/geomentor-prompts/pull/14/agent-sessions/94e9d374-65ac-45e3-ac21-43a71f3c988e) where the author says `@copilot fix these merge conflicts` (a common chore that LLMs can very well help with) and [they were well obliged](https://archive.ph/UhUII)

Now the agent can only say something like:

> Any remaining merge conflicts with master would need to be resolved at the GitHub level since I don't have direct access to fetch and merge with the master branch.

This is a very poor experience

**Comment by stevoland** [comment]
As of this week, it seems `persist-credentials` is no longer overwritten.

However, if the setup checkout `persist-credentials: true` (default), the agent cannot push (401).

As it seems the agent is operating on a fork, this workaround is allowing me to direct the agent to update the head branch:

```yaml
# .github/workflows/copilot-setup-steps.yml
  steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Get base branch name
      if: ${{ github.event_name == 'dynamic' && inputs.github-token }}
      id: base
      shell: bash
      run: |
        BRANCH=$(echo $COPILOT_AGENT_INPUTS | jq -r '.COPILOT_AGENT_BASE_COMMIT')
        echo "branch=$(echo "$BRANCH" | sed 's#refs/heads/##')" >> "$GITHUB_OUTPUT"
      env:
        COPILOT_AGENT_INPUTS: ${{ github.event.inputs.COPILOT_AGENT_INPUTS }}

    - name: Fetch base branch (workaround allowing agent to update with base)
      if: ${{ github.event_name == 'dynamic' && inputs.github-token }}
      shell: bash
      run: |
        git remote add upstream https://x-access-token:$TOKEN@github.com/$GITHUB_REPOSITORY.git
        git fetch upstream $BASE
      env:
        BASE: ${{ steps.base.branch }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

So prompts like "@copilot merge in upstream branch, fix conflicts, pick mine" seems to work

**Comment by pheu** [comment]
I was struck by the same thing recently. I need `fetch-depth: 0` to be respected, but it's silently being changed to `fetch-depth: 2` whenever Copilot work.

**Comment by godx565** [comment]
:⁠-⁠!8383(₹!₹!

**Comment by AdamVig** [comment]
This behavior [is documented](https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment#preinstalling-tools-or-dependencies-in-copilots-environment), for what it's worth:
> Any value that is set for the `fetch-depth` option of the `actions/checkout` action will be overridden to allow the agent to rollback commits upon request, while mitigating security risks.

I'm finding that Copilot Coding Agent can't run `git push` to my private repository, and I wonder if it's caused by Copilot overriding the default `actions/checkout` `persist-credentials: true`:
```yml
- name: Checkout repository
  uses: actions/checkout@v5
  # Copilot sets its own `fetch-depth` setting, no point in setting it here as it would be overridden
```
```
Run actions/checkout@v5
  with:
    fetch-depth: 2
    persist-credentials: false
```
I had it run `git config --list` and didn't find anything interesting in it, but thought I'd share it here in case it helps anyone:
```
safe.directory=*
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/<my private repository>
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
gc.auto=0
branch.copilot/<the branch>.remote=origin
branch.copilot/<the branch>.merge=refs/heads/copilot/<the branch>
credential.username=copilot-swe-agent[bot]
credential.helper=!f() { test "$1" = get && echo "******"; }; f
user.email=<random 9-digit number>+Copilot@users.noreply.github.com
user.name=copilot-swe-agent[bot]
pull.rebase=false
```

Update: even when I explicitly set `persist-credentials: true`, it is overwritten:
```
Run actions/checkout@v5
  with:
    fetch-depth: 2
    persist-credentials: false
```
As a result, Copilot coding agent is unable to push its changes in my main monorepo!

**Reply by darcien** [reply]
Thanks for the docs link, seems like it wasn't there when I raised this question (that doco for `fetch-depth` was added on August 2025 https://github.com/github/docs/commit/08f1bd21b235c0ed7b62fab907e1646e89ac463d).

I wish GitHub could add doco for other options too, not just `fetch-depth`.

**Comment by buschtoens** [comment]
We ran into the same problem.

We explicitly need to persist the credentials, as they are required in a subsequent `bundle install` step.

Even when explicitly setting `persist-credentials: true`, GitHub Copilot still silently overrides it with `false`.

This was very hard to pin down, is not documented anywhere and effectively blocked our entire organization from adopting Copilot.

I guess that way more users are affected by this bug / security decision, but were unable to find the root cause and this thread here. I wish GitHub would at least acknowledge the issue here.

We then tried to work around this issue by injecting a personal access token to `bundle install`:

```yaml
- name: Cache and Install Gems
  uses: ruby/setup-ruby@v1
  with:
    ruby-version: 3.4.7
    bundler-cache: true
  env:
    BUNDLE_GITHUB__COM: ${{ secrets.COPILOT_GH_PAT }}
```

~But even that fails, because GitHub Copilot again seems to enforce an empty `BUNDLE_GITHUB__COM` env var.~

This works, after copying the secrets to an "Environment", as described here: https://github.com/orgs/community/discussions/180346

We got it working now, but this was an extremely painful process.
