### DISCUSSION TITLE
How to enforce Pull Request title and commit message format using GitHub workflows or other tools?

### DISCUSSION THREAD

**Discussion by er-sadhana** [community/community#163396] [Pull Requests] [answered]
### Select Topic Area

Question

### Body

Hi everyone,

I’m working with a team where we follow a specific commit message and PR title convention (like [JIRA-ID] Scope: Message), and we want to enforce this as part of our pull request review process.

We are already using GitHub Actions for CI/CD, and I’m wondering:

Is there a way to validate the PR title before allowing the merge?

Can we reject a PR or block merging if the commit messages don't follow a defined format?

Should this be done via GitHub Actions, or are there better tools or bots for this kind of validation?

Any way to display a warning or comment automatically if someone forgets to follow the format?

We’d prefer a lightweight and maintainable solution – nothing too complex to configure or update.

Appreciate if anyone can point to working examples, reusable GitHub Actions, or their team’s best practices.

Thanks in advance! 🙏

**Comment by malikrajat** [comment, marked as answer]
You can use a GitHub Action that checks the PR title using a regular expression. For example, if your team follows this format:
[JIRA-123] Add login feature,
then you can add this script to your workflow:

```yml
name: "Check PR Title"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^\[JIRA-[0-9]+\]\ .+ ]]; then
            echo "::error ::PR title must follow format: [JIRA-123] Your title"
            exit 1
          fi

```

This will fail the workflow if the title format is wrong.
