### DISCUSSION TITLE
GitHub Workflow to run only after another one completes successfully...

### DISCUSSION THREAD

**Discussion by ravishansenevirathna** [community/community#163532] [Actions] [answered]
Hi all 👋
I'm working on a CI/CD setup where I want one GitHub Actions workflow to run only after another one completes successfully.

**Comment by SandevD** [comment, marked as answer]
Use the workflow_run trigger in your second workflow to run it automatically after the first one completes successfully. Example:
```
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
```
