### DISCUSSION TITLE
Option for config.yml to allow creation of issues from discussions

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#16394] [Projects and Issues]
This is something that happened to me just recently.
I first created a discussion on `github/docs` informing about some possibly incorrect information before realizing that such stuff should be in an issue. So I went ahead and clicked the `Create issue from discussion` text to make an issue based of the discussion.

However, because the repository uses issue forms did the creation not happen and I was moved to the template chooser, where when I select the template, I had to completely re-write the stuff.

Because of this would I like to propose adding a new feature to the `config.yml` for the template chooser, to allow creation of issues from discussions.

The setting could be called `issues_from_discussions_enabled` and when set to `false` would it hide the `Create issue from discussion` text on Discussions.
When enabled and when clicking the text would the issue be created like when no templates and/or template chooser are enabled.

Possible config.yml structure:
```yaml
blank_issues_enabled: false
issues_from_discussions_enabled: true
contact_links:
  - name: Support
    url: https://example.com/support
    about: You can get more help here.
```
