### DISCUSSION TITLE
GitHub Actions with Gradle Wrapper started failing due to a networking issue

### DISCUSSION THREAD

**Discussion by OwlBurst** [community/community#164161] [Actions] [answered]
### Why are you starting this discussion?

Bug

### What GitHub Actions topic or product is this about?

Actions Runner

### Discussion Details

Yesterday at around 11:48 EEST, my GitHub Actions suddenly started failing on the "validate gradle wrapper" stage, as seen [here](https://github.com/OwlBurst/login-chat/actions/runs/15896150921/job/44828496206) and [here](https://github.com/OwlBurst/login-chat/actions/runs/15886859213/job/44800836926)

The errors listed are ETIMEDOUT and ENETUNREACH, which indicate some kind of networking issue on GitHub's side. I haven't changed my workflow files at all, so I doubt this is due to anything I did.

Although after a few restarts the actions seemed to work again.

Any idea on why this could be happening?

Thanks

Wishing you a magical day out there,
- Owl Burst

**Comment by github-actions** [comment]
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build a better GitHub experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- GitHub staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog post related to the feedback.

**Where to look to see what's shipping 👀**
- Read the [Changelog](https://github.blog/changelog/) for real-time updates on the latest GitHub features, enhancements, and calls for feedback.
- Explore our [Product Roadmap](https://github.com/orgs/github/projects/4247), which details upcoming major releases and initiatives.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired outcomes, and any accompanying screenshots.

As a member of the GitHub community, your participation is essential. While we can't promise that every suggestion will be implemented, we want to emphasize that your feedback is instrumental in guiding our decisions and priorities.

Thank you once again for your contribution to making GitHub even better! We're grateful for your ongoing support and collaboration in shaping the future of our platform. ⭐

**Comment by Leorev01** [comment]
Hi @OwlBurst! It looks like this might have been a temporary networking issue on GitHub’s side. If it happens again, you could try adding retry mechanisms to your workflow or check the GitHub Status Page for updates. Glad it resolved after a few retries! 😊

**Reply by OwlBurst** [reply]
How can I add those retry mechanisms?

**Reply by Leorev01** [reply, marked as answer]
> How can I add those retry mechanisms? 

Hi @OwlBurst! 

Here’s how you can add retry mechanisms to your GitHub Actions workflow to handle temporary failures:

---

### **Step 1: Use the Built-In `retry` Strategy**
GitHub Actions allows you to define a `retry` strategy for steps. This is the simplest way to implement retries.

Here’s an example:

```yaml
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a command with retries
        run: |
          echo "Running the command..."
          curl -f http://example.com || exit 1
        retry:
          max_attempts: 3
          delay_seconds: 10

```

max_attempts: 3 means the step will retry up to 3 times if it fails.

• delay_seconds: 10 specifies a delay of 10 seconds between retries.


### Step 2: Use Custom Retry Logic

If you need more flexibility, you can write your own retry logic using a script. Here’s an example in bash:

```yaml
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Custom retry logic
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            curl -f http://example.com && break || sleep 10
            if [ $i -eq 3 ]; then
              echo "All attempts failed!"
              exit 1
            fi
          done

```

• The script retries the command (curl -f http://example.com) up to 3 times.

• If all attempts fail, it exits with an error.


### Step 3: Monitor GitHub Status

Sometimes, issues may occur due to GitHub downtime. You can check the GitHub Status Page for updates on any known outages or issues.


I hope this helps! Let me know if you need further assistance in setting this up. 😊
