### DISCUSSION TITLE
Reusability of GivHub Actions Workflows across hundreds of repositories (to support Boost C++ Libraries)

### DISCUSSION THREAD

**Discussion by jeking3** [community/community#164127] [Actions] [answered]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Workflow Configuration

### Discussion Details

About 8 years ago The Boost C++ libraries were not using CI workflows regularly.  I created https://github.com/boostorg/boost-ci as a means to centralize some of the logic so it was easier to maintain, but this solution is not complete.  The GHA workflow files _must_ live in the repository that is building, which means the structure of the workflow cannot be centralized.  Since the workflow cannot be programmatically generated, we have some innate limitations.

Boost C++ libraries are each in their own repository and generally have a build structure where they attempt to build using a matrix of language levels and compiler versions; building for libstdc++ and libc++; building on linux, macos, and windows; building for msys2 or cygwin; building for 32-bit and 64-bit (though at this point we can discount the former).  There are also build jobs to integrate with codecov.io, and with Coverity Scan.

This matrix can only be defined in each repository along with a complex workflow by checking in a workflow YAML file.  There is no mechanism for a set of repositories to share a common workflow framework.  This would vastly improve how Boost C++ uses GitHub Actions and in general would allow for more uniform and standard support.

For example, a global workflow defined in boost-ci that gets "included" into each repositories workflow would allow for conditional logic that would say, "if a secret is defined in this repository for CODECOV_TOKEN then run the codecov build job".  Instead of needing to copy the workflow from boost-ci into the other repository, it could be referenced or included instead, then updating the workflow could be done from one location and benefit all the repositories.  Of course, each repository would need a way to override the inherited matrix and/or configuration to deal with special cases.

One alternative that I have been able to come up with, but have not implemented yet, is to make a workflow generator that takes an options file and spits out the same canonical workflow, then use automation to occasionally submit pull requests into all the subordinate repos (about 200 of them?)...

The other alternative is to go back to using a monorepo and structure things more like the Azure SDK.  I don't think the Boost community as a whole would go for that though.

Does GitHub have anything in the works that would help with this?  Thanks.

**Comment by shubham055555** [comment]
GitHub does now support sharing and reusing workflows across repositories via reusable workflows, which is exactly what you’re looking for. Here's how you can leverage this for Boost C++:

🚀 1. Define a Reusable Workflow in boost-ci
In boost-ci (e.g. a public or private repo within the enterprise/org), create a workflow under .github/workflows/build-matrix.yml:

yaml
Copy
Edit
name: Central Build Matrix

on:
  workflow_call:
    inputs:
      matrix:
        type: object
        required: true
    secrets:
      CODECOV_TOKEN:
        required: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ inputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          # Build logic depending on matrix.compiler, version, stdlib...
      - name: Codecov
        if: ${{ secrets.CODECOV_TOKEN }}
        run: |
          # Upload to Codecov
This reusable workflow encapsulates your entire build matrix logic and handles optional jobs based on passed secrets.
victoronsoftware.com
+14
docs.[github.com](https://github.com/orgs/community/discussions/25719?utm_source=chatgpt.com)
+14
reddit.com
+14
github.com

🔗 2. Call It from a Library’s Workflow
In each Boost repo, have a lightweight workflow like:

yaml
Copy
Edit
name: CI

on: [push, pull_request]

jobs:
  boost-ci:
    uses: boostorg/boost-ci/.github/workflows/build-matrix.yml@main
    with:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang, msvc]
        stdlib: [libstdc++, libc++]
        # Add other axes or override defaults as needed
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
This centralizes the build logic while allowing overrides—perfect for maintaining uniform configuration across ~200 repos.

🔐 3. Permissions & Secrets
If boost-ci is public, any repo can call it.

For private, you'll need to enable usage in Org Settings → Actions → Allow private reusable workflows.

Secrets can be passed explicitly, or inherited via secrets: inherit.
devops.stackexchange.com
+1
reddit.com
+1
resources.github.com
+3
stackoverflow.com
+3
stackoverflow.com
+3

🛠 4. Alternatives & Best Practices
Composite Actions: Great for step-level reuse, but can’t replace whole-job logic.
reddit.com
+15
stackoverflow.com
+15
docs.github.com
+15

Workflow Templates: Good for bootstrapping new repos, but each still needs its own workflow file.GitHub does now support sharing and reusing workflows across repositories via reusable workflows, which is exactly what you’re looking for. Here's how you can leverage this for Boost C++:

🚀 1. Define a Reusable Workflow in boost-ci
In boost-ci (e.g. a public or private repo within the enterprise/org), create a workflow under .github/workflows/build-matrix.yml:

yaml
Copy
Edit
name: Central Build Matrix

on:
  workflow_call:
    inputs:
      matrix:
        type: object
        required: true
    secrets:
      CODECOV_TOKEN:
        required: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ inputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          # Build logic depending on matrix.compiler, version, stdlib...
      - name: Codecov
        if: ${{ secrets.CODECOV_TOKEN }}
        run: |
          # Upload to Codecov
This reusable workflow encapsulates your entire build matrix logic and handles optional jobs based on passed secrets.
victoronsoftware.com
+14
docs.[github.com](https://github.com/orgs/community/discussions/25719?utm_source=chatgpt.com)
+14
reddit.com
+14
github.com

🔗 2. Call It from a Library’s Workflow
In each Boost repo, have a lightweight workflow like:

yaml
Copy
Edit
name: CI

on: [push, pull_request]

jobs:
  boost-ci:
    uses: boostorg/boost-ci/.github/workflows/build-matrix.yml@main
    with:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang, msvc]
        stdlib: [libstdc++, libc++]
        # Add other axes or override defaults as needed
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
This centralizes the build logic while allowing overrides—perfect for maintaining uniform configuration across ~200 repos.

🔐 3. Permissions & Secrets
If boost-ci is public, any repo can call it.

For private, you'll need to enable usage in Org Settings → Actions → Allow private reusable workflows.

Secrets can be passed explicitly, or inherited via secrets: inherit.
devops.stackexchange.com
+1
reddit.com
+1
resources.github.com
+3
stackoverflow.com
+3
stackoverflow.com
+3

🛠 4. Alternatives & Best Practices
Composite Actions: Great for step-level reuse, but can’t replace whole-job logic.
reddit.com
+15
stackoverflow.com
+15
docs.github.com
+15

Workflow Templates: Good for bootstrapping new repos, but each still needs its own workflow file.

**Comment by adityajethwa7** [comment, marked as answer]
Hi @jeking3,

For managing CI/CD across 200+ Boost repositories, here's a modern approach that leverages GitHub's latest features beyond basic reusable workflows:

**1. Dynamic Matrix Generation with JSON Configuration**

Instead of hardcoding matrices in each repo, use a JSON-driven approach that allows inheritance and overrides:

```yaml
# boost-ci/.github/workflows/matrix-builder.yml
name: Boost Matrix Builder

on:
  workflow_call:
    inputs:
      config-file:
        type: string
        default: '.boost-ci.json'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: build
        run: |
          # Merge base config with repo-specific overrides
          BASE_CONFIG="https://raw.githubusercontent.com/boostorg/boost-ci/main/base-matrix.json"
          REPO_CONFIG="${{ inputs.config-file }}"
          
          matrix=$(jq -s '.[0] * .[1]' <(curl -s $BASE_CONFIG) $REPO_CONFIG)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    uses: boostorg/boost-ci/.github/workflows/core-build.yml@main
    with:
      compiler: ${{ matrix.compiler }}
      stdlib: ${{ matrix.stdlib }}
      os: ${{ matrix.os }}
```

Each repository only needs a minimal `.boost-ci.json`:
```json
{
  "exclude": [
    {"compiler": "msvc", "os": "ubuntu-latest"}
  ],
  "include": [
    {"compiler": "gcc-13", "stdlib": "libstdc++", "os": "ubuntu-24.04"}
  ]
}
```

**2. Self-Configuring Workflows with Feature Detection**

Create workflows that automatically detect and enable features based on repository structure:

```yaml
# boost-ci/.github/workflows/smart-ci.yml
jobs:
  detect-features:
    outputs:
      has-tests: ${{ steps.check.outputs.has-tests }}
      has-docs: ${{ steps.check.outputs.has-docs }}
      coverage-enabled: ${{ steps.check.outputs.coverage }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: |
          # Auto-detect repository features
          [[ -d "test" ]] && echo "has-tests=true" >> $GITHUB_OUTPUT
          [[ -f "doc/Jamfile.v2" ]] && echo "has-docs=true" >> $GITHUB_OUTPUT
          [[ "${{ secrets.CODECOV_TOKEN }}" != "" ]] && echo "coverage=true" >> $GITHUB_OUTPUT

  conditional-jobs:
    needs: detect-features
    if: needs.detect-features.outputs.has-tests == 'true'
    uses: boostorg/boost-ci/.github/workflows/test-suite.yml@main
```

**3. Workflow Inheritance via Git Submodules (Zero Maintenance)**

For repositories that need complete control while staying synchronized:

```bash
# In each Boost library repo
git submodule add https://github.com/boostorg/boost-ci .github/boost-ci
ln -s boost-ci/workflows/standard.yml .github/workflows/ci.yml
```

Updates propagate automatically when submodules are updated, no PRs needed.

**4. GitHub App for Workflow Management**

Deploy a GitHub App that manages workflows programmatically:

```javascript
// Automatically sync workflow changes across all repos
app.on('push', async (context) => {
  if (context.payload.repository.name === 'boost-ci') {
    const updatedWorkflow = await getLatestWorkflow();
    
    // Update all Boost repos without manual PRs
    for (const repo of boostRepos) {
      await context.octokit.repos.createOrUpdateFileContents({
        owner: 'boostorg',
        repo: repo.name,
        path: '.github/workflows/ci.yml',
        message: 'Auto-update CI workflow',
        content: Buffer.from(updatedWorkflow).toString('base64'),
        sha: await getCurrentSha(repo)
      });
    }
  }
});
```

**5. Single Source of Truth with Workflow Dispatch**

Instead of 200 workflow files, use a single orchestrator:

```yaml
# boost-ci/.github/workflows/orchestrator.yml
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
      
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: boostorg/${{ inputs.repository }}
      
      - name: Run Universal Build
        uses: boostorg/boost-ci/.github/workflows/universal-build.yml@main
```

Trigger builds via API/webhooks, eliminating per-repo workflow files entirely.

---

The key insight is that GitHub Actions now supports much more than basic reusable workflows. By combining workflow_call, dynamic matrix generation, and programmatic management, you can achieve true centralization while maintaining flexibility for special cases.
