### DISCUSSION TITLE
Which (if at all?) container image is used when not specifying `jobs.<job_id>.container`?

### DISCUSSION THREAD

**Discussion by jsattler** [community/community#164584] [Actions] [answered]
### Why are you starting this discussion?

Question

### What GitHub Actions topic or product is this about?

Actions Runner Image

### Discussion Details

Hey everyone,
I'm confused about which (if at all?) container image is used to run jobs by default. My assumption was that the following workflows should use the same container image to execute the jobs:

**Example 1:**
```yaml
name: example-1
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: gh version
        run: gh --version
```

**Example 2:**
```yaml
name: example-2
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: gh version
        run: gh --version
```

However, tools like `gh` are not available in the second example. Would be great if someone could explain, what's used by default and maybe help solve my confusion around this topic. Many thanks!

**Comment by ChristopherHX** [comment, marked as answer]
The images without container directive, are really big azure VM images: <https://github.com/actions/runner-images>.

See "Set up Job" step:
```
Current runner version: '2.325.0'
Operating System
  Ubuntu
  24.04.2
  LTS
Runner Image
  Image: ubuntu-24.04
  Version: 20250622.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250622.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250622.1
Runner Image Provisioner
  2.0.437.1
```

<img width="1405" alt="image" src="https://github.com/user-attachments/assets/2492c836-6096-4f40-8611-93ebe68ed9c7" />

You can use packer with azure credentials to build the exact same ubuntu/windows image like they provide to you. (for macOS this is much more effort).

Example 2 means pull ghcr.io/actions/actions-runner:latest into the VM and use the image to run workflow steps inside docker inside the vm.

Additonally ghcr.io/actions/actions-runner:latest is for `self-hosted` runners, not designed to be used in `container:`.

**Reply by jsattler** [reply]
Thanks for the clarification. I thought that ghcr.io/actions/actions-runner:latest contains all the tools that are installed on the VM. But seems I need to find either an image that contains all those tools or create it myself.

**Reply by ChristopherHX** [reply]
>  I need to find either an image that contains all those tools or create it myself.

Some images that are more or less based on runner-images are documented here: https://github.com/catthehacker/docker_images#images-available

For the 1:1/full/rootless image you need to do something like
```yaml
container:
  # This does not work in runs-on: ubuntu-latest, image size to big for free disk space
  image: ghcr.io/catthehacker/ubuntu:full-24.04
  options: --user 0 # switch back to user root, actions/runner does not support different default users
```

The full images, can only be used in self-hosted runners, due to it's image disk size requirements.
Uploading the large images using GitHub Hosted Runners is already an nodejs adventure.

You might be interested in smaller images ca. 1-2GB that contain the tool `gh`, but not everything.
- `ghcr.io/catthehacker/ubuntu:custom-24.04`
- `ghcr.io/catthehacker/ubuntu:gh-24.04`
