### DISCUSSION TITLE
Incremental Summaries

### DISCUSSION THREAD

**Discussion by johnhenry** [community/community#16454] [Actions]
I'm really excited about the new summaries feature detailed [here](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/).

Currently, the following works as expected:

```yaml
jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - name: Beginning Summary 
        run: echo "# Summary" >> $GITHUB_STEP_SUMMARY

      - name: ...
        ...
     
      - name: Finalizing summary
        run: | echo 'end' >> $GITHUB_STEP_SUMMARY
```

Once the last job is run for the step, the summary is printed.
It would be awesome if the preview could update in real time as the file referenced by $GITHUB_STEP_SUMMARY is updated
