### DISCUSSION TITLE
Feature Request: Job Context field for Full Job Matrix Name

### DISCUSSION THREAD

**Discussion by leighmcculloch** [community/community#16614] [Actions]
It would be really useful to have a single field in the `job` context that matches the fully job name when a job is run with a strategy that uses a matrix.

For example, if I have a single job `cargo`, that has a few matrix values such as:
```yaml
  cargo: # << This is the job id
    strategy:
      matrix:
        features: ['', 'alloc', 'std']
        profile: [dev, release]
        sys:
        - os: ubuntu-latest
          target: wasm32-unknown-unknown
          test: false
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          test: true
        - os: macos-latest
          target: x86_64-apple-darwin
          test: true
        - os: macos-latest
          target: aarch64-apple-darwin
          test: false
        - os: windows-latest
          target: x86_64-pc-windows-msvc
          test: true
```

It would be really useful if there was a `job.name` that would give me the names of the job as shown in the GitHub UI:
```
cargo (dev, ubuntu-latest, x86_64-unknown-linux-gnu, true)
```

There are several uses of having a `job.name` field.

1. For logging or reporting upstream in systems where reports are pushed.

2. For use as cache keys in action caches that need to be unique for the full matrix.

There are some hacky ways to get the matrix into a single string. This is one way:

```
${{ join(matrix.*,'|') }}-${{ join(matrix.sys.*,'|') }}
```

Which generates a string like this:

```
|dev|Object-ubuntu-latest|x86_64-unknown-linux-gnu|true
```

It's imperfect because objects stringify to `Object` and have to be manually expanded.
