### DISCUSSION TITLE
[Projects Beta] Support sort issues in projects by closing date

### DISCUSSION THREAD

**Discussion by hanlins** [community/community#16738] [Projects and Issues]
I need to write weekly summaries for the project. Ideally, I would like to filter out all opened issues, sort the closed issues tracked by the project from new to old, and find the recently closed ones and refer them in my report. For now, we don't have a column for the issue status (whether it's closed or still open) or the starting/closing date. It would be nice to have both so project managers can have a clear idea what has been closed recently.

**Comment by vvo** [comment]
Another usecase: I need to provide an overview of what happened to a coworker going back from vacation. Right now I can't easily do that because the order of tasks on the right is a mix of manual moves (at the top) + issues closed (at the bottom?)

**Comment by ronnyroeller** [comment]
Other use cases:
- We use the kanban board for daily standups. It's handy to see on top of the "Done" column what was closed last (i.e. what happened yesterday).
- Similar for end-of-sprint demos: It's handy to see in the "Done" what happened that sprint

**Comment by vforvova** [comment]
General use case might be sorting by **Recently updated** on any column as it is in repo issues already 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/1913904/173432464-5db64b72-0055-4111-b571-6e4be12f03b2.png">

**Comment by agarciacalvo** [comment]
+1 , It'd be nice to have 2 more hidden fields to show, sort, filter...: opening date and closure date

![image](https://user-images.githubusercontent.com/18212145/173571610-74d05c9b-27b9-42be-86de-ba9c1fd82f05.png)

**Comment by MarkoVerbancic** [comment]
Hi everyone, for the moment we use a workaround for this:

1. Create a new field and selected the Type of Field to be a Date:
![image](https://user-images.githubusercontent.com/82682440/173836721-52cdf888-c3e6-4b51-899f-7ae806bcecb0.png)
2. Create the Issue and add it to the relevant project
3. Select the date from the Project Section in the Side Bar:
![image](https://user-images.githubusercontent.com/82682440/173837041-8271c243-393d-40e9-9b52-73f45454206d.png)
4. At this stage you can _filter_ by Date and _group_ or _sort_ by other values such a Priority or Difficulty to give you good metrics and Project Views
#
![image](https://user-images.githubusercontent.com/82682440/173837493-4cb0553a-b6c9-4d7d-8e8b-35a4c992b127.png)
#
![image](https://user-images.githubusercontent.com/82682440/173837578-69953aae-d700-4e2a-86d8-b692eabdae60.png)


Hope this helps! 😄

**Comment by healthbjk** [comment]
Has anyone managed to automate this using Github actions? 

Something like this feels close, but getting the item ID feels impossible?

```
name: Update Close Date

on:
  pull_request:
    types:
      - closed
  issues:
    types:
      - closed

jobs:
  update_close_date:
    runs-on: ubuntu-latest
    steps:
      - name: Update Project Close Date
        run: |
          curl --request POST \
            --url https://api.github.com/graphql \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --data '{"query":"mutation {updateProjectV2ItemFieldValue( input: { projectId: \"PROJECT_ID" itemId: \"ITEM_ID\" fieldId: \"FIELD_ID\" value: { date: \"'{TODAY}'\" }}) { projectV2Item { id }}}"}'
        shell: bash
```
