### DISCUSSION TITLE
Reusable Workflows from private organization repository

### DISCUSSION THREAD

**Discussion by gazandic** [community/community#16838] [Actions]
Hello Team,

I am working on reusable workflows. I have a reusable-workflow repository for collection shared workflows. The repository make changes adoption can be implemented as soon as possible when the shared workflows changes. 

However, the repository must be a public repository in order to do that. 
https://docs.github.com/en/actions/using-workflows/reusing-workflows. 
Starter workflow is not our cup of tea because we can't force changes adoption and make adoption time slower.

I want to reuse workflow from private repository because of security considerations, Are we able to do that?
Are there any roadmaps or timelines for this feature ? 

Regards,

**Comment by HariSekhon** [comment]
I contacted GitHub Enterprise support about this a few months ago and was told it's on the roadmap.

I believe it should be possible now to use internal repos as reusable workflow repo sources but I haven't tried it yet as I prefer to work with my open-source library, which you might find interesting:

https://github.com/HariSekhon/GitHub-Actions

**Reply by robwafle** [reply]
@github-staff: This feature would be very useful. Any update would be greatly appreciated.  I spent the last 30 minutes trying to find some indication if this is on the feature roadmap or under development but I found nothing.

**Comment by alexandervandekleutab** [comment]
I am also looking for this feature. I am curious if there is something difficult about implementing it. We use GitHub enterprise and GitHub Actions for our CI/CD. 
We have many microservices stored in separate repos, and want to share the common workflows related to testing and deployment in one repo and use them in our other repos. However we cannot make the workflow public for security reasons.

For now we are using a workaround where download a workflow on-the-fly following the solution here: https://stackoverflow.com/questions/71118955/how-to-have-the-github-workflows-sharable-or-reusable 

> A possible solution for private repos is to upload the shareable repo as an artifact, e.g. a compressed archive and host it somewhere accessible. When the caller workflow kicks in, simply download the archive and extract it into the current context.
> 
> E.g.:
> 
> Assuming $archive-url =https://example.org/shareable-workflow.tar: workflow.yml
> 
>     jobs:
>       - name: Checkout context repo
>          run: actions/checkout@v2
> 
>       - name: Download the shareable workflow
>          run: curl $archive-url | tar xzf -  
> 
>       - uses: ./workflow.yml

**Reply by HariSekhon** [reply]
I'm not sure it's that big a security issue if you've parameterized the workflows properly as there should be nothing specific to you.

This is actually a good practice to get in to in order to create reusable code.

All the private stuff will be in the parameters inside the calling workflows which are in private repos.

I do agree it is inconvenient to not have private repo workflows though as you're not as free to hack.

I'm sure I read somewhere that internal repos might work now but I've not tried to migrate this yet. I suspect the problem with private repo reusable workflows is the calling workflow may not always have access to them and this might be why internal repos were done first because the access model is easier.

**Reply by kalanatd** [reply]
@alexandervandekleutab Are you using this mehthod? I am trying to do the same but the uses command throws an error [1] when used with a relative path. I am doing the same thing, but instead of curl I am using actions/checkout@v2 to checkout the remote repo. 

Note: As per the docs, 'uses' command needs a relative path which needs to reside inside the repository. [2] ("uses: ./path/to/dir for actions in a  subdirectory ofthe same repository")

I executed a 'cat' command of the workflow and I can see that the workflow file exists and it is readable. But the 'uses' command does not identify the file. 

Caller Workflow:

```
name: Reusable Workflows

on: [ push ]

jobs:
  download-remote-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Get private repo with action
      uses: actions/checkout@v2
      with:
        repository: kalanatd/called-repo
        ref: main
        token: ${{ secrets.PAT_TOKEN }}
    - name: List Files After remote Checkout same job
      run: |
        pwd
        ls -a                 // I can see the checked out remote repo files in here
    - name: Check if the workflow file exists         // re-confirmation whether files exist
      run: |
        ls -al .github/workflows
        ls -al .github
        cat ./.github/workflows/workflow.yml             // Can read the file without any issue
    - name: Run a workflow file
      uses: ./.github/workflows/workflow.yml 
```

[1] Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/caller-repo/caller-repo/.github/workflows/workflow.yml'. Did you forget to run actions/checkout before running your local action?

Please note that there are two directories with the same name as the repository in the error message. (caller-repo)
[2] https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf
