### DISCUSSION TITLE
Allow custom rendering templates for input fields (Specifically, large log files)

### DISCUSSION THREAD

**Discussion by ehawman-rosenberg** [community/community#16934] [Projects and Issues]
Currently, the options for submitting logs are:

* Upload a file
* Dump a massive block of text to be rendered by default (either markdown or triple-backtick code block)

I have been going back and editing my submissions with
```
<details>
  <summary>Output</summary>
<pre><code>[dump the contents of the Log output field here]
</code></pre>
</details>
```
Which renders as 
<details>
  <summary>Output</summary>
<pre><code>[dump the contents of the Log output field here]
</code></pre>
</details>

Miles better than default. In fact, I would argue that something similar *should* be default for all Issues Forms.

In any case, it would be nice if we had the ability to insert a custom rendering template for any arbitrary field. Something like:

```yaml
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: template
      template: |-
        <details>
          <summary>$label</summary> 

        ```yml
        $submission
        ```
        </details>
```
Result:
<details>
  <summary>Relevant log output</summary> 

```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - alignment: left
    newline: true
    segments:
      - type: iterm
        style: plain
        foreground: cyan
        template: "{{ .PromptMark }}"
      - foreground: cyan
        properties:
          alpine: ""
          arch: ""
          centos: ""
          debian: ""
          elementary: ""
          fedora: ""
          gentoo: ""
          linux: ""
          macos: ""
          manjaro: ""
          mint: ""
          opensuse: ""
          raspbian: ""
          ubuntu: ""
          windows: ""
          wsl: ""
          wsl_separator: " on "
        style: diamond
        template: " {{ if .WSL }}{{ end }}{{.Icon}}═"
        trailing_diamond: "<transparent,></>"
        type: os
      - background: green
        foreground: black
        leading_diamond: ""
        style: diamond
        template: "  {{ .Name }} "
        type: shell
      - background: magenta
        foreground: black
        powerline_symbol: ""
        style: powerline
        template: " {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} "
        type: session
      - background: lightCyan
        foreground: black
        powerline_symbol: ""
        properties:
          fetch_version: true
        style: powerline
        template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
        type: julia
      - background: lightCyan
        foreground: black
        powerline_symbol: ""
        properties:
          fetch_version: true
        style: powerline
        template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
        type: go
      - background: lightCyan
        foreground: black
        powerline_symbol: ""
        style: powerline
        template: "  {{ .Full }}"
        type: java
      - background: lightCyan
        foreground: black
        powerline_symbol: ""
        style: powerline
        template: "  {{ .Full }} "
        type: php
      - background: lightGreen
        foreground: black
        powerline_symbol: ""
        properties:
          fetch_version: true
        style: powerline
        template:
          "  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{
          .Full }} "
        type: node
      - background: yellow
        foreground: black
        powerline_symbol: ""
        properties:
          display_mode: files
          fetch_version: false
        style: powerline
        template: " ﴃ {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
        type: azfunc
      - background: red
        foreground: black
        powerline_symbol: ""
        properties:
          display_mode: files
          fetch_version: true
        style: powerline
        template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
        type: ruby
      - background: lightYellow
        foreground: black
        powerline_symbol: ""
        style: powerline
        template: " ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "
        type: kubectl
      - background: lightYellow
        foreground: black
        powerline_symbol: ""
        properties:
          display_mode: files
          fetch_virtual_env: false
        style: powerline
        template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
        type: python
      - background_templates:
          - '{{if contains "default" .Profile}}yellow{{end}}'
          - '{{if contains "jan" .Profile}}magenta{{end}}'
        foreground: black
        powerline_symbol: ""
        properties:
          display_default: false
        style: powerline
        template: "  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
        type: aws
      - background: yellow
        foreground: black
        powerline_symbol: ""
        properties:
          time_format: Mon | 15:04:05
        style: powerline
        template: " {{ .CurrentDate | date .Format }} "
        type: time
      - background: cyan
        foreground: black
        properties:
          style: austin
          threshold: 0
        style: diamond
        template: " {{ .FormattedMs }} "
        trailing_diamond: ""
        type: executiontime
    type: prompt
  - alignment: right
    segments:
      - background: magenta
        foreground: black
        leading_diamond: ""
        properties:
          branch_icon: " "
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
          fetch_worktree_count: true
        style: diamond
        template: >-
          " {{ .UpstreamIcon }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
        trailing_diamond: ""
        type: git
    type: prompt
  - alignment: left
    newline: true
    segments:
      - foreground: cyan
        style: plain
        template: " ╚"
        type: text
      - background: blue
        background_templates:
          - "{{ if gt .Code 0 }}red{{ end }}"
        foreground: black
        leading_diamond: ""
        properties:
          always_enabled: true
        style: diamond
        template: "{{ if gt .Code 0 }}  {{ else }} {{ end }}"
        type: exit
      - background: blue
        background_templates:
          - "{{ if not .Writable }}red{{ end }}"
        foreground: black
        powerline_symbol: ""
        properties:
          folder_icon: ""
          folder_separator_icon: "  "
          home_icon: ""
          max_depth: 3
          style: agnoster_short
        style: powerline
        template: "{{ if gt .Code 0 }} {{ else }}{{ end }} {{ .Path }} {{ if not .Writable }} {{end}}"
        type: path
      - background: blue
        background_templates:
          - "{{ if and .Segments.Path.Writable (not .Root) }}{{ else }}red{{ end }}"
        foreground: white
        properties:
          root_icon: ""
        style: diamond
        template: "{{ if and .Root (not .Segments.Path.Writable) }}\b  {{ end }}{{ if and .Root .Segments.Path.Writable }}  {{ else }}\b{{ end }}"
        trailing_diamond: ""
        type: text
    type: prompt
console_title_template: "{{ .Folder }}"
osc99: true
palette:
  black: "#1B1A23"
  blue: "#9580FF"
  black-background: "#22212C"
  lightBlue-brightBlue: "#AA99FF"
  lightCyan-brightCyan: "#99FFEE"
  lightGreen-brightGreen: "#A2FF99"
  lightMagenta-brightPurple: "#FF99CC"
  lightRed-brightRed: "#FFAA99"
  lightWhite-brightWhite: "#FFFFFF"
  lightYellow-brightYellow: "#FFFF80"
  selection-selectionBackground: "#454158"
  comment-brightBlack: "#7970A9"
  cyan: "#80FFEA"
  green: "#8AFF80"
  magenta-purple: "#FF80BF"
  red: "#FF9580"
  white-cursorColor-foreground: "#F8F8F2"
  yellow: "#FFCA80"
version: 2
```
</details>

~~Obviously we've lost syntax highlighting in this, but I'm sure there's a way to finagle things so that a highlighted code block can live under a details block.~~

EDIT: Ok I figured it out. Just needed an extra space after the summary declaration. Thanks to @ericclemmons for your [gist on the subject!](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
