### DISCUSSION TITLE
[Issue forms] Apply template value in absence of query parameter

### DISCUSSION THREAD

**Discussion by corubba** [community/community#17014] [Projects and Issues]
Let's assume the following simple issue form template, with a assignee and label defined:
```yaml
---
name: Form default value Reproducer
description: Issue form for reproducing the problem with default values
labels: ['bug']
assignees: ['some-person']
body:
- type: textarea
  attributes:
    label: Just some input field
```
When you open the "New Issue" page in the browser via the "New issue" button and selecting that template, the assignee and label are correctly set to the values from the template. The URL of that page looks like [0], notice that it explicitly contains the assignee and label as defined in the template.
When you want to create an issue from an external source and use a URL like [1] (with only the template name), the assignee and label are not set. You have to explicitly pass them like when you do it in the browser.
When I specify a default value in the template, my expectation would be that it is applied unless explicitly overridden. I don't want to hardcode the assignee and label in the external source, there should be one single source of truth: the template. So when you open it with [1], the assignee and label from the template would be set. If you open it with [2] then the explicitly given label from the query parameter is set and the label from the template ignored, but the assignee is still set to the one from the template.

[0] https://github.com/xxx/yyy/issues/new?template=my_template.yaml&assignees=some-person&labels=bug
[1] https://github.com/xxx/yyy/issues/new?template=my_template.yaml
[2] https://github.com/xxx/yyy/issues/new?template=my_template.yaml&labels=feature-request
