### DISCUSSION TITLE
First workflow pushing changes into master does not trigger second workflow that should automatically run on push to master

### DISCUSSION THREAD

**Discussion by rd-janina-nemec** [community/community#17236] [Projects and Issues]
On auto-merging branches via the first shown workflow, the second workflow is not running as I would expect. This seems to be a bug to me and my colleagues. Or is there a reason why the second workflow should not be triggered on a push to master via another workflow? On manually pushing the second workflow is triggered as expected just fine.

```yml
name: Build & Merge Branch
on:
  push:
    branches:
      - 'auto-merge-branch/**'

jobs:
  build:
    ....

  merge-branch:
    needs: build
    ...
    steps:
      - uses: actions/checkout@v2
      - name: Merge branch into master
        run: |
          git fetch --unshallow
          git checkout master
          git pull
          git merge --ff-only ${{ env.BRANCH }} -m "Some message"
          git push
          git push --delete origin ${{ env.BRANCH }}
```

```yml
name: Build
on:
  push:
    branches:
      - master
.....
```
