### DISCUSSION TITLE
Could we have workflow_dispatch and workflow_call write to the same inputs dict

### DISCUSSION THREAD

**Discussion by meyerkev** [community/community#17240] [Actions] [answered]
So I have a workflow _docker-push_ that pushes a random ref to our DockerHub.  And I have a workflow _rollout_ that pushes a random DockerHub image to our deployments.  And then hopefully understandably, I have a 3rd workflow that wraps those two workflows and says "Run these".  

And the problem I'm facing is that I now have inputs coming into docker-push from two sources.  

- Workflow_dispatch: writes github.events.inputs.XXXXXX
- Workflow_call: writes inputs.XXXXXX by way of my push-then-rollout call.  

And this means that I now have to write `${{ github.event.inputs.XXXXXX || inputs.XXXXXX || 'default-value' }}` every time I want to use this. 

And since there's no vars: context in a Github Action, there's no great way to only write that once and use the result everywhere in the action.  Currently, my workaround in `steps:` is to make a `run:` call that is just a bunch of `echo ::set-output` then parse the resulting string values, but that doesn't help with `job.<job>.concurrency` for example.  

Is there a reasonably sane workaround there?

**Comment by jeremycarroll** [comment, marked as answer]
How about this? I think the no-op `run: true` is required.
```
jobs:
  find_inputs:
    outputs:
      XXXXXX: ${{ github.event.inputs.XXXXXX || inputs.XXXXXX || 'default-value' }}
    runs-on: ubuntu-latest
    steps:
     - run: true

  main:
    needs:
      - find_inputs
    # Now use needs.find_inputs.outputs.XXXXXX
```
