### DISCUSSION TITLE
Jobs need a way to reference all outputs of matrix jobs

### DISCUSSION THREAD

**Discussion by ghost** [community/community#17245] [Actions]
This need has already been discussed in multiple threads on github.community, so I’m quoting [a great summary](https://github.community/t/bug-jobs-output-should-return-a-list-for-a-matrix-job/128626/32) that was posted in one of those threads by [consideratio](https://github.community/u/consideratio):

> ### Issue
> 
> Currently, a job with `strategy.matrix` runs multiple times with variations based on the matrix. The issue is that only a single value is available for future jobs that `needs` this job’s output, because even if the output is set by multiple matrix variations of the job, only one is retained.
> 
> ### Workaround
> 
> There is a workaround of defining separate outputs for a job with `strategy.matrix` by letting the job variations set different outputs.
> 
> # A new observation
> 
> ### Limitation of the workaround
> 
> While it is possible to define a fixed list of outputs for a job with `strategy.matrix` running with a fixed list of jobs, it is not possible to handle a situation when you have declared the `strategy.matrix` dynamically (using output of a previous job), and would need a dynamic amount of outputs, for example one output per job variation.
> 
> This limitation can be understood more directly by the documented [context availability ](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability) which doesn’t lists the `needs` context available when setting `job.<job_id>.outputs` but only when setting a specific output such as `job.<job_id>.outputs.<output_id>` .
> 
> Practically I’ve also verified this limitation.
> 
> ```
>   test-set-dynamic-outputs:
>     runs-on: ubuntu-20.04
>     needs: test-set-dynamic-outputs-init
>     outputs: ${{ toJson(needs.test-set-dynamic-outputs-init.dynamic_outputs) }}
> ```
> 
> ```
> The workflow is not valid. .github/workflows/dynamic_outputs.yaml (Line: 66, Col: 14): Unrecognized named-value: 'needs'. Located at position 8 within expression: toJson(needs.test-set-dynamic-outputs-init.dynamic_outputs) .github/workflows/dynamic_outputs.yaml (Line: 66, Col: 14): Unexpected value '${{ toJson(needs.test-set-dynamic-outputs-init.dynamic_outputs) }}'
> ```
> 
> For more details, see [this workflow definition ](https://github.com/consideRatio/testing-gh-workflows/blob/369621d3cb91a0e8aefb975077b21ec95e8164ed/.github/workflows/dynamic_outputs.yaml#L66).
> 
> # Two feature requests
> 
> I think both these feature requests could be relevant, but the first feature is the best feature from a user perspective and possibly even also from a GitHub developers perspective as it could actually be simpler to implement and maintain long term.
> 
> ### Add a new context: `jobs.<job_id>.matrix-outputs`
> 
> Could GitHub add new context? It would be used for those that want to see the distinct output values for a given output id, as set by different matrix job variations.
> 
> I propose a new context ( `jobs.<job_id>.matrix-outputs` ) instead of a change of the existing context ( `jobs.<job_id>.outputs` ) for a two main reasons:
> 
> 1. It wouldn’t be a breaking change to add something new.
> 2. It would be relevant to distinguish and use both `jobs.<job_id>.outputs` and `jobs.<job_id>.matrix-outputs` separately.
> 
> ### Allow dynamic `jobs.<job_id>.outputs` definitions
> 
> Would it be possible to allow context for `jobs.<job_id>.outputs` to be set, and not only for the individual output ids?
> 
> In other words, to allow this to function:
> 
> ```
>   test-set-dynamic-outputs:
>     runs-on: ubuntu-20.04
>     needs: init
>     outputs: ${{ toJson(needs.init.dynamic_outputs) }}
> ```
> 
> And to not be restricted where only this is functioning:
> 
> In other words, to allow this to function:
> 
> ```
>   test-set-dynamic-output-ids:
>     runs-on: ubuntu-20.04
>     needs: init
>     outputs:
>       a: ${{ toJson(needs.init.dynamic_output_a) }}
>       b: ${{ toJson(needs.init.dynamic_output_b) }}
> ```

GitHub team, please take a look at the above feature requests and please consider implementing them! The current situation, wherein each successive job instance overwrites the outputs of the prior instance, is really not great. Thank you.

**Comment by ringerc** [comment]
I explained this another way at https://github.community/t/roll-up-matrix-outputs/253564 

This is a huge limitation of the current interface IMO.

I like the idea of a `matrix-outputs`. But I'd like a simple way to flatten that out to a list of individual runs of a matrix job, too, for use in a downstream matrix or similar. I'd like to be able to access:

* An array of matrix job instance ids that can be passed as a matrix input for a downstream job
* For each matrix job instance, a json object containing all its matrix inputs - the `matrix` variable as that job saw its value
* For each matrix job instance, a json object containing all that matrix job's outputs

**Reply by MemphisMeng** [reply]
DId you remove your discussion? Your link went to nothing.

**Reply by ghost** [reply]
@MemphisMeng see https://github.com/orgs/community/discussions/17245#discussioncomment-3421929

**Reply by airtower-luna** [reply]
The forum was moved from `github.community` to here in summer, and most threads without a selected answer weren't migrated. That's probably why the link is broken. :confused:

**Reply by ringerc** [reply]
Sigh. Good work github, I documented a workaround and now that's gone.

**Comment by 0x53A** [comment]
An alternative might be stop hacking around with dynamic matrixes and be able to run dynamic workflows.

In gitlab there's an [equivalent feature where you can generate and run a child pipeline](https://docs.gitlab.com/ee/ci/pipelines/parent_child_pipelines.html#dynamic-child-pipelines). The advantage of generating a whole pipeline/workflow is that at this point you can just dynamically hardcode everything exactly like you need.

**Comment by radiomix** [comment]
:skull: Sad Github changes discussion links under the hood destroying contex :bomb: ! 
The above URL posted as `https://github.community/t/bug-jobs-output-should-return-a-list-for-a-matrix-job/128626/32` does not link to the discussion any more! (Holds true for all the links to `github.github.community` in this thread). Not the first time I see github discussion links broken, especially on feature-requests a lot of people voted for.

It seams an _intended Github feature to prevent people from accumulating comparable discussions/threads_.

**Reply by ghost** [reply]
Agreed.

The _community engagement platform churn_ is nearly akin to Google’s messaging apps churn.

**Comment by cheloniixd** [comment]
Verry informative and helpful post... Thank you!

**Comment by cheukribbon** [comment]
Is there any update on this? Is github working on this?

**Comment by mikz** [comment]
I've worked around this by using artifacts to generate the matrix.


```yaml
jobs:
  matrix:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: mafiapigs-macos
            metaId: 2177361
            otherId: 2177360
          - target: project-windows
            metaId: 2177362
            otherId: 2177360
    steps:
      - run: |
          matrix=$((
            echo '${{ toJSON(matrix) }}'
          ) | jq -c .)
          echo "$matrix" > matrix
          echo "::set-output name=matrix::$matrix"
        id: matrix
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.build_target == matrix.target || github.event.inputs.build_target == '*' || github.event.inputs.build_target == '')
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ hashFiles('matrix') || 'none' }}
          path: matrix
          if-no-files-found: warn

  check-matrix:
    runs-on:  ubuntu-22.04
    needs: [ matrix ]
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          matrix="$(cat */matrix | jq -c --slurp .)"
          echo "::set-output name=matrix::$matrix"
        id: matrix

  steam:
    name: "Release ${{ matrix.includes.target }}"
    needs: [check-matrix]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        includes: ${{ fromJSON(needs.check-matrix.outputs.matrix) }}
    steps:
```

**Reply by theonlysinjin** [reply]
Thanks @mikz, this seems to be the workaround.
Thankfully we went from a bunch of files with just new line separators, so we were also able the parse all the files at once with
```
matrix="$(cat */matrix | jq -ncR '[inputs]')"
```

I wondered if a possible solution might be to be able to call another workflow from within a step,
this means you could also get around the problem by chaining multiple workflows together. 
This might just be another workaround and not work for someone else.

**Reply by piotrekkr** [reply]
Using artifacts seems like a possible workaround but there can be some edge cases where artifact get corrupted when multiple jobs write to same artifact at same time. There is a warning in upload action docs:

> Warning: Be careful when uploading to the same artifact via multiple jobs as artifacts may become corrupted. When uploading a file with an identical name and path in multiple jobs, uploads may fail with 503 errors due to conflicting uploads happening at the same time. Ensure uploads to identical locations to not interfere with each other.

Probably very rare to happen but it may so watch for this

**Reply by xriu** [reply]
I'm implementing this workaround, if you want to prevent artifact corruption during concurrent executions of the same workflow. You can use the following:

```
concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true
```

Basically this will cancel previous executions and continue with the new one

**Reply by piotrekkr** [reply]
@xriu There are two problems here:
1. concurrent execution of same workflow that updates artifact, (e.g. someone push twice to same PR almost at same time) 
2. concurrent execution of matrix jobs that update same artifact within same workflow run 

For first case your workaround will probably work. For second one it may get artifacts corrupted because matrix jobs will concurrently write results to same artifact. In second case you could set `concurrency` on job level but this would defeat whole purpose of matrix which is concurrent execution. 

Ugly but probably working solution would be to use different artifacts for each matrix job. For example: 
1. you have matrix like this:
	```
	jobs:
	  example_matrix:
	    strategy:
	      matrix:
	        os: [ubuntu-22.04, ubuntu-20.04]
	        version: [10, 12, 14]
	```
2. each matrix job uploads artifact with special name like `matrix-outputs-${{ github.run_id }}-${{ github.run_attempt }}-HASH_OF_MATRIX_OBJECT` containing `json` file with outputs like:
	```
	{
	  "${{ matrix.os }}": {
	    "${{ matrix.version }}": {
	      "outputs": {....}
	    }
	  }
	}
	```
2. job that need matrix output will: 
   1. ask for artifacts [using github API](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#list-workflow-run-artifacts)
   2. download
   3. unpack
   4. deep merge json data from unpacked artifacts into one object e.g. `jq -s 'reduce .[] as $item ({}; . * $item)' *.json > outputs-combined.json`

As you can see pretty ugly workaround but should be resistant to artifact corruption.

**Reply by sigprof** [reply]
Note that [`actions/upload-artifact@v4.0.0`](https://github.com/actions/upload-artifact/tree/v4.0.0#breaking-changes) now disallows multiple uploads to the same artifact, so if you are using this workaround, you must ensure that each instance of the matrix job uses an unique artifact name.  If you try to use the same artifact names for all instances, you will get an error like this:

> `Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run`

In my testing `${{strategy.job-index}}` seems to be enough to provide distinction between multiple instances of the same matrix job.

~~Changing the job to use multiple artifacts may also cause another issue — `actions/download-artifact` still does not support a glob or any other filter for the artifact name (it can download either a single artifact specified by the exact name, or all artifacts for the workflow run), so it may download too much if the workflow also uses artifacts for other purposes (like passing the intermediate build results between jobs).~~ Update: Since [`actions/download-artifact@/v4.1.0`](https://github.com/actions/download-artifact/releases/tag/v4.1.0) the download action has the `pattern:` input, so you can download just the artifacts which are used as outputs of the particular matrix job.

There is also a new limit on the number of artifacts:

> Each job in a workflow run now has a limit of 10 artifacts.

However, looks like each instance of a matrix job is treated as a distinct job when this limit is applied (at least I tried a [test with 25 jobs in the matrix](https://github.com/sigprof/test-workflows/blob/6f5e8ef343e4f6483e57445ecc5ddeb135d47eab/.github/workflows/matrix-results-test-v2.yml), and it passed).

**Comment by cj81499** [comment]
"Support matrix context in output keys" merged 2 days ago!

https://github.com/actions/runner/pull/2477

**Reply by srosell-ut** [reply]
I've tested this (it was released in the [v2.303.0](https://github.com/actions/runner/releases/tag/v2.303.0) release and at least what in that issue is described we couldn't make it work (I've added a comment in the PR to see if I can get some response). Anyone has make it work? 🤔

**Reply by martincostello** [reply]
It notes in the PR that:

> Please note that: Server side changes are still in-progess

I guess there's changes in GitHub itself required to fully support the scenario.

**Reply by srosell-ut** [reply]
yeap, make sense I guess, I don't really understand what they refer with that side note but I guess is it not finished then 🤷 
Thanks for the comment 🙇

**Comment by csaba-almasi** [comment]
An FYI for anyone struggling with this and hacking their way around the limitations: the PR for the runner landed to support the new context, but the team working on the necessary server-side implementation has been completely laid off, leaving this feature in purgatory. See [this comment](https://github.com/actions/runner/pull/2477#issuecomment-1501003600) from the contributor on the Runner issue.

**Reply by Loki-Afro** [reply]
although it has been already asked in the [pr comments](https://github.com/actions/runner/pull/2477#issuecomment-1556228385) but .. are there any updates?

**Comment by dburman23** [comment]
2024 here and this is still an issue *facepalm*
Only workaround for now is to upload what is to be your outputs, as artifacts from one job and download them into the other job, per parallel execution of the matrix.

**Comment by serpro69** [comment]
OMG, how is this still not solved? :exploding_head: 
Makes me once more question if github actions can be reliably used for anything beyond very simple CI setups.
Maybe it's time to finally migrate to gitlab :thinking: 

Interestingly, the [docs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) say:
> If your job uses a matrix and writes to $GITHUB_OUTPUT, the content will be overwritten for each matrix combination. **You can use the matrix context to create unique output names for each job configuration**. For more information, see "[Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#matrix-context)."

However, I couldn't find any more references as to how to use this or if this supports sharing outputs between jobs.

**Reply by piotrekkr** [reply]
Some time ago I create a [PR to fix docs](https://github.com/github/docs/pull/33842) because those are quite misleading :/ Better to test all claims yourself before fully believing the docs. Hope my PR makes it more clear how this is handled actually.

**Reply by dburman23** [reply]
This was my first time with GitHub Actions and it was a client's requirement but my god I'm never doing this again and will be actively advising any client against GA for anything beyond very simple pipelines.

**Reply by piotrekkr** [reply]
I'm using GA for more than 3 years. It mostly works even with more complex workflows (workarounds sometimes needed) but as you noticed there are some edge cases or bad design decision made in the past that still need to be fixed. My impression however is that GH is more focused on enterprise features and security than normal day to day users problems. If you are sure about some other tools with similar features as GA, consider trying them out.

**Reply by shinebayar-g** [reply]
There are tons of essential features missing in github actions and they haven't been fixed in years. Github doesn't respond to these community discussions. We're shouting into the void here. You are better off using something else tbh.

**Reply by piotrekkr** [reply]
If you are interested I have two more docs pull requests waiting for review. [Here](https://github.com/github/docs/pull/33621) and [here](https://github.com/github/docs/pull/33916). Those are not related to this specific problem but may be of some help to people even if not merged.

**Comment by cyrilico** [comment]
Is there really no update all on this? Nearly 18 months of being basically ready to ship, silence... On a such a relevant feature. upload/download artifacts is not a workaround for stricter security requirements.

**Reply by ericsciple** [reply]
> upload/download artifacts is not a workaround for stricter security requirements

Can you help me understand this more?

**Comment by dev-dull** [comment]
Until this issue is resolved, can we get GitHub and/or GHE to display a warning when `strategy.matrix` is combined with `outputs` on a job? A short message like, "Warning: Outputs from a matrix will be truncated to the results from a single job." will save folks _a lot_ of time.

**Comment by andreasvh-conceto** [comment]
Waiting for this feature since 2 years. We migrate several datbases in parallel and need the output for each migration matrix run in a convenient way. Is there some PR in progress to track or another good workaround?
What are alternatives supporting multiple outputs for each matrix run? - Self hosted runners should be supported. Circle Ci, Gitlab, Travis CI? Any experience here in the community?
Thanks a lot 🙏

**Reply by mcascone** [reply]
Artifacts are the workaround. Unless you can hardcode your outputs uniquely for each matrix instance, you will need to generate uniquely-named artifacts in each matrix job, and then download them all in the downstream job that needs them.

**Comment by ashley-green-baringa** [comment]
For anyone else that ended up here, the docs give this advice on matrix job outputs:

```yml
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.gen_output.outputs.output_1 }}
      output_2: ${{ steps.gen_output.outputs.output_2 }}
      output_3: ${{ steps.gen_output.outputs.output_3 }}
    strategy:
      matrix:
        version: [1, 2, 3]
    steps:
      - name: Generate output
        id: gen_output
        run: |
          version="${{ matrix.version }}"
          echo "output_${version}=${version}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      # Will show
      # {
      #   "output_1": "1",
      #   "output_2": "2",
      #   "output_3": "3"
      # }
      - run: echo '${{ toJSON(needs.job1.outputs) }}'
```

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs#using-job-outputs-in-a-matrix-job

**Reply by piotrekkr** [reply]
Well this is one workaround to always use different output names in each matrix job, but this is not dynamic at all. You still need to remember to update output names each time you add or remove items from matrix. Also next jobs that use those outputs need to be changed. If it was possible to access those for example like this:
```
env:
  outpts_json: ${{ toJSON(needs.matrix_job.matrix.outputs.*.output_param) }}
```
it would be way easier to work with.

**Reply by brianjmurrell** [reply]
Your work around does not account for dynamically generated axes though.

A proper solution is still needed here.

**Reply by markshep-wbg** [reply]
That page has been changed and no longer mentions matrix jobs.  I tried to use that method anyway with GHES 3.17.0 but it didn't work.

**Comment by OscarVanL** [comment]
This nondeterministic behaviour isn't merely a feature request, this is a **massive footgun in GitHub actions**. The silently nondeterministic outputs are *dangerous*, especially for people that depend on GitHub Actions for reliable builds and production deploys.

I had a look at some of the PRs referencing [this](https://github.com/actions/runner/pull/2477), take [this PR](https://github.com/newrelic/nrdot-collector-releases/pull/244), where this bug led to the incorrect helmchart being applied during a kubernetes apply 😱.

If it is too much to ask that this feature is finished, I think it should at least raise a warning when you access a matrix job's output. This would be a good candidate for a GitHub Actions linter.

**Reply by andreasvh-conceto** [reply]
@OscarVanL you are absolutely right. This could lead to completely wrong deployments. Especially in multi tenancy backend apps, where you perform configuration and migrations on several databases. It is sad to see that since 3 years now, nobody from the github side feels responsible or is answering. We are in discussion with ourselves :(

**Reply by y-nk** [reply]
there are valid needs for this. for instance, my current usecase (which lead me here) is to spawn one runner per arch to build a docker image (i'm not using buildx for many reasons). each job runs independently and the image tag should be produced by the worker after publishing the image ; then another action should build the manifest based on those images. you can get around by pre-processing the image tags in an action before the matrix and it's ok like that, but i'd rather have this action doing and producing the artifact it should be producing.

**Comment by ridasaleemsage** [comment]
Any updates on it?

**Comment by cspades** [comment]
This is really frustrating. Combined with the situation that `needs:` combines the semantics of `runs-after:` and `if: succeeded()` (i.e. skipping a job skips subsequent jobs that need the previous job), there's nothing I can do to for the situation where a subsequent job needs to check if a previous matrixed job succeeded or was skipped (for all elements of the matrix), and change its behavior accordingly. I think I would need to just fork my workflow into two branches?

Because I cannot add a job-level `if` condition that skips or runs the job that doesn't also skip subsequent jobs, I cannot skip every step of the previous job and pass information if the job was skipped for all elements of the matrix, and I cannot remove the `needs:` condition since I'll have race conditions between the failure/success of a non-skipped job and further jobs. I need flexibility in one of those avenues to implement the workflow I'm thinking of, does anyone have any ideas?

Edit: Actually, I guess I can control both jobs using a single input or ENV variable, but still definitely wish things were more flexible here, or at least more DRY.

**Comment by mcascone** [comment]
It probably won't solve all your problems, but you _can_ make a job/step run even if its dependencies are skipped: 

```yaml
if: ${{ !failure() && !cancelled() && <any_other_conditions_you_need> }}
```

This overrides the implied `if: success()` applied to every job/step, and only skips if a dependency fails or is canceled. 

You need to include the `${{ ... }}` brackets due to the `!` at the start of the expression.

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions

**Reply by mcascone** [reply]
why all the downvotes?

**Reply by dev-dull** [reply]
@mcascone The core of the issue is that we need the outputs from the matrix. The `if` condition you proposed will allow other steps in the workflow to run, but most of output(s) from the matrix will still be missing.

For example (...or at least this is my observed behavior), let's say I had a workflow that had a matrix to compile an app for Window, Mac and Linux, and that the output of the matrix was a SHA of the compiled binary. When the matrix runs, all three apps will be compiled, but if the Linux build completes first, the rest of the workflow will only receive the SHA for the Linux build, and the Windows and Mac SHAs will be omitted entirely.

**Comment by ericsciple** [comment]
I'm trying to better understand the scenarios. Does anyone have a concrete scenario where artifacts won't work? Or is it a preference for outputs?

Job outputs enable passing information into downstream job-level inputs.

Whereas artifacts work well for downstream step-level processing. 

<details><summary>Example solution using artifacts</summary>

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
    steps:
      - run: echo "${{ matrix.runs-on }}_RESULT=success" > "report-${{ matrix.runs-on }}.txt"
      - uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.runs-on }}
          path: report-${{ matrix.runs-on }}.txt
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: report-*
          merge-multiple: true
      - run: cat report-*
```

</details>

I would also like to re-iterate @ashley-green-baringa's [comment](https://github.com/orgs/community/discussions/17245#discussioncomment-11222880). Empty outputs are discarded, so in that sense merging outputs can be deterministic. May help in some cases.

Thanks in advance for helping me better understand the scenarios!

**Reply by dev-dull** [reply]
> Does anyone have a concrete scenario where artifacts won't work? Or is it a preference for outputs?

At my previous job (shameless plug that I'm looking for a gig), we had a build that generated short(ish) lived credentials (8hrs). Sticking those in an artifact was a no-go. The short term solution was to just use a loop instead of a matrix, but processing sizes were only going to grow, so a matrix of loops was going to be a requirement to keep build times reasonable (and developers happy).

preemptive edit: yes, keeping the creds out of the build log took some tinkering, although I don't recall what solution that was.

**Reply by ericsciple** [reply]
Thanks @dev-dull!. Technically `outputs` shouldn't be used for secrets and we even make it hard by dropping outputs that contain secrets. Nonetheless it's an interesting scenario and maybe we should support something like `secret-outputs` 🤔

**Reply by dev-dull** [reply]
> Technically outputs shouldn't be used for secrets...

I'm suddenly glad those pipelines aren't my problem any longer.

FYI, I'm going to connect with you on LinkedIn to chat about this topic for reasons that'll make sense.

**Reply by piotrekkr** [reply]
For me it is matter of convenience and consistency with normal jobs where you can easily access job outputs. With matrix it just not working even tho you can define and use outputs there. I can think of scenario where there is matrix that multiple jobs and then next job that depends on matrix and is run always after. This job could generate summary of all matrix job based on data from those outputs. Outputs can be easily accessed without additional steps and can be used directly or converted to json string then used by some scripts. Working with artifacts, even with merge option, is just inconvenient in this case. Allowing to use outputs with matrix job just generates bugs if people are not aware that they do not work as expected.

**Reply by sigprof** [reply]
> At my previous job (shameless plug that I'm looking for a gig), we had a build that generated short(ish) lived credentials (8hrs). Sticking those in an artifact was a no-go.

If you have a way to securely pass some information _into_ a matrix job, you could generate an encryption key, pass that key to both the matrix job and any subsequent jobs which need to use the outputs of the matrix job, and then encrypt the credentials before storing them in the intermediate artifacts.

**Reply by arianvp** [reply]
My usecase is: I have two jobs that upload two docker images (different architecture) and then a join job that creates a multi-arch image manifest that takes the two image digests as input. currently can't do that

**Reply by ericsciple** [reply]
@arianvp this works today:

<details><summary>Example YAML</summary>

```
jobs: 
  produce:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        arch: [x86, x64]
    outputs: 
      x86-url: ${{ steps.set-output.outputs.x86-url }}
      x64-url: ${{ steps.set-output.outputs.x64-url }}
    steps:
      - id:  set-output
        run:  echo "${{ matrix.arch }}-url=SOME_URL" >> "$GITHUB_OUTPUT"

  consume:
    runs-on: ubuntu-slim
    needs: produce
    steps:
      - run: |
          echo "x86-url=${{ needs.produce.outputs.x86-url }}"
          echo "x64-url=${{ needs.produce.outputs.x64-url }}"
```

</details>

Does that help for your scenario? I'm wondering if adding a similar example to the docs would help folks today.
