### DISCUSSION TITLE
Return workflow run id in API response for workflow dispatch event

### DISCUSSION THREAD

**Discussion by tomas-pajurek** [community/community#17389] [Actions] [answered]
When sending workflow dispatch event through API (https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event), the response body is empty.

It would be great if the response would contain ID of the dispatched workflow run. This ID could then be used to e.g. programmatically track the workflow run or wait for it.

Currently, the ID must be obtained by listing the all workflow runs and "guess" the correct one.

**Comment by sambshapiro** [comment]
Related: https://github.com/orgs/community/discussions/27226

**Comment by atemate** [comment]
Hello GitHub team! we're using GH workflows extensively, and inability to get workflow run ID when dispatching a workflow is critical for us. Would you please share some of your ideas on when this issue could be tackled from your side?

**Comment by MSevey** [comment]
Found this helpful action as a workaround https://github.com/marketplace/actions/return-dispatch

**Comment by lasith-kg** [comment]
**Affilitiation:** I acknowledge that I am a major contributor to this GitHub Action.

[`lasith-kg/dispatch-workflow@v1`](https://github.com/lasith-kg/dispatch-workflow) is a GitHub Action that dispatches workflows either using `repository_dispatch` or `workflow_dispatch` event and has an optional flag `discover: true`. When this flag is enabled, it injects a **unique UUID** into the Workflow Run Name so that it can be correlated to the initial dispatch event. Once the workflow is discovered, the **Run ID** and **Run URL** is available from the step outputs.

```yaml
steps:
  - uses: lasith-kg/dispatch-workflow@v1
    id: dispatch-with-discovery
    name: "Dispatch Workflow With Discovery"
    with:
      dispacth-method: workflow_dispatch | repository_dispatch
      ...
      discover: true
  - id: echo-run-id-url
    name: "Echo Run ID and Run URL"
    run: |
      echo "${{ steps.dispatch-with-discovery.outputs.run-id }}"
      echo "${{ steps.dispatch-with-discovery.outputs.run-url }}"
```

Naturally, the receiving workflow needs to be modified to intercept this UUID in the `run-name`

#### `workflow_dispatch`

```yaml
name: Receiving Workflow
run-name: Receiving Workflow [${{ inputs.distinct_id && inputs.distinct_id || 'N/A' }}]

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: 'Distinct ID'
        required: false
```

#### `repository_dispatch`

```yaml
name: Receiving Workflow
run-name: >
  Receiving Workflow [${{
    github.event.client_payload.distinct_id &&
    github.event.client_payload.distinct_id || 'N/A' }}]

on:
  repository_dispatch:
    types:
      - deploy
```
