### DISCUSSION TITLE
Internal/private starter workflows support for GHE

### DISCUSSION THREAD

**Discussion by badbort** [community/community#17597] [Enterprise] [answered]
As title, it would be nice to have starter workflows available to GHE without being forced to make the `.github` repository public. Anyone with access to those internal repos should see those starter workflows as options when creating a workflow

Following [this](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/creating-starter-workflows-for-your-organization) documentation I've been able to get starter workflows working on my personal public test org setup, however making my workplace org `.github` repo public is unrealistic.

I'd like to either:
- Allow `.github` to remain internal and support starter workflows
- Extend starter workflows to the `.github-private` repository
- `.github-internal` ??

**Comment by burib** [comment]
@badbort unfortunately the referenced [documentation](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/creating-starter-workflows-for-your-organization) doesn't tell you but it's possible to have private/internal reusable workflows.

1. create a `.github-private` repository
2. place your workflows to `.github/workflows/`
3. Enable the access to this repo from the GitHub Actions workflows:
3.1 Visit https://github.com/MY_ORG/.github-private/settings/actions
3.2 Change `Actions permissions` to option 3 ( accessible by ORG ) OR option 4 ( accessible by whole enterprise ) 
4. reference that workflow for example as in your repo:

```
name: 'sample pr workflow'

on:
  pull_request:

jobs:
  hello:
    uses: MY_ORG/.github-private/.github/workflows/hello.yml
   # uses: MY_ORG/.github-private/.github/workflows/hello.yml@BRANCH_NAME
   # uses: MY_ORG/.github-private/.github/workflows/hello.yml@VERSION_NUMBER
   # uses: MY_ORG/.github-private/.github/workflows/hello.yml@COMMIT_HASH
```

references:
https://dev.to/n3wt0n/finally-custom-github-actions-in-internal-repos-4l91

notes:
I guess you can call `.github-private` something else as well, I haven't tried it. please let me know if you did and it works.

**Reply by Fleshgrinder** [reply]
What you are describing are reusable actions, not reusable workflows. Reusable actions can be defined in any internal repository, and then reused across the organization.

Pro tip: Call your internal repository `actions` and follow the recommended structure of having a directory per reusable action, just like when you create real actions. Afterwards your workflow files look really nice, e.g.:

```yaml
jobs:
  sample:
    uses: acme/actions/checkout
    uses: acme/actions/build
    uses: acme/actions/test
```

**Reply by burib** [reply]
@Fleshgrinder thank you for your input. Why is it a reusable action I'm describing ? ( other than the link I've attached )

**Reply by Fleshgrinder** [reply]
A workflow is everything (e.g. `name`, `on`, `jobs`) and an action is what you reference after `uses`.

**Reply by m0un10** [reply]
@Fleshgrinder `uses` at the step-level is an action. whereas `uses` at the job-level (i.e. in @burib 's example) is a reusable workflow.

E.g. Actions
```
jobs:
  sample:
    steps:
    - uses: acme/actions/checkout
    - uses: acme/actions/build
    - uses: acme/actions/test
```

Reusable workflows
```
jobs:
  sample:
    uses: owner/repo/.github/workflows/my-workflow.yaml@v1
```
