### DISCUSSION TITLE
Feature Request: Sequential Steps w/Optional Starting Step

### DISCUSSION THREAD

**Discussion by mikeschinkel** [community/community#17882] [Actions]
I am looking for a feature that would support running the same commands for a list of delineated steps and to run them in order and provide the option of starting from a specific step, running it and then all the remaining steps. in order.

If such a feature already exists I would appreciate if anyone could point me to it.

I have looked at both [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) and [grouping](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines) but the former creates multiple jobs and the latter creates multiple sections within a single step.

Instead what I need are distinct steps that each can succeed or fail and will be displayed as steps as if they have been manually listed in a workflow.

The use-case is one where all the steps have been encoded into a `Makefile`, each step depends on the prior step to first succeed, many steps can be rather time consuming, especially some of the earlier ones, and if one of the steps fails it would be great to be able to restart the process at the failing step rather than have to restart from the beginning each time. Having this option would greatly reduce the edit-test-debug cycle that can be so time-consuming in development of build processes that take a long time.

**IMPORTANT NOTE:** This use-case probably requires that the user is using an external resource to retain the artifacts which is true in my use-case where each step is using Packer to orchestrate a VMWare VM running on vSphere to ultimately build an OVA. But it is nonetheless a real-world use-case. 

Here is a mockup of using a hypothetical schema for YAML to how such feature might be encoded into a workflow, from my actual use-case:

```
name: OVA Builder

on:
  workflow_dispatch:
    inputs:
      from:
        type: steps
        description: 'Step to start build FROM (inclusive)'
        required: true

steps:
  - id: setup
    name: Ensure required tools installed
  - id: start
    name: Ensure the OVA Builder VM has been started
  - id: clean
    name: Clean the Work Directories of the OVA Builder
  - id: k8s
    name: Build the Kubernetes Installer
  - id: tools
    name: Build the Tools Tarball
  - id: iso
    name: Build the OnPrem Gateway ISO
  - id: upload
    name: Upload the ISO to vSphere Datastore
  - id: install
    name: Create a VM on vSphere based on the ISO
  - id: export
    name: Export the OVA from the ISO-based VM to the OVA Builder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Steps
        from: ${{ github.event.inputs.from }}
        step:
          run: |
            make ${{ steps.id }}
```

Thank you in advance for considering.
