### DISCUSSION TITLE
pgadmin not working in codespaces

### DISCUSSION THREAD

**Discussion by egbakou** [community/community#17918] [Codespaces] [answered]
Hi,
I added pgadmin to the docker-compose file, I can log in, but I got internal server error.
![image](https://user-images.githubusercontent.com/26142591/172020988-c9a2ff6d-8351-44b4-bfae-bc258b32355f.png)

Below is the code of my docker-compose.yaml.
```yaml
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "3.9"
        # Optional Node.js version to install
        NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgadmin:
    image: dpage/pgadmin4:6.10
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jonhdoe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: StrongPassword
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  postgres-data: {}
  pgadmin-data: {}

```
Forward ports in the `devcontainer.json` : [5000, 5432, 8080]

Did I miss something, please !
