### DISCUSSION TITLE
Support contexts and expressions under default.runs

### DISCUSSION THREAD

**Discussion by HariSekhon** [community/community#17981] [Actions]
Use case:

A reusable workflow that can set the working directory via an input variable in the defaults section, eg:

```
on:
  workflow_call:
    inputs:
      dir:
        description: Terraform base directory to execute in
        type: string
        default: ''
        required: false

defaults:
  run:
    # XXX: this is not supported yet
    working-directory: ${{ inputs.dir }}
```

which results in this error:

```
(Line: 92, Col: 24): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.dir
```
