### DISCUSSION TITLE
[feature request] Find a way to support reusable workflow_dispatch workflows

### DISCUSSION THREAD

**Discussion by philomory** [community/community#18064] [Actions]
Reusable workflows work well for the most part, but a side effect of the way they are defined means you can't really define a reusable `workflow_dispatch` workflow. I mean, you can populate the _jobs_ of a `workflow_dispatch` workflow from a reusable workflow, but, you cannot reuse a centrally-defined set of values for `on.workflow_dispatch.inputs`, for example.

Of course, this "restriction" affects all other types of workflows as well, so in this sense `workflow_dispatch` is not particularly special; but, a `workflow_dispatch` workflow will generally have a lot more data embedded in the trigger condition than other types of workflows, so it "hurts" more for this workflow type. It'd be nice if there were a way to support defining workflow inputs within a reusable workflow - something like the following might work:

Given a reusable workflow in `example_org/example_repo/.github/workflows/reusable.yaml`:
```yaml
on:
  workflow_call:
    inputs:
      foo:
        type: string
        required: true
      bar:
        type: string
        required: true
```
... you could define a `workflow_dispatch` workflow in another repository as follows:
```yaml
on:
  workflow_dispatch:
    inheritUnboundInputs:
      - example_job

jobs:
  example_job:
    uses: example_org/example_repo/.github/workflows/resuable.yaml@tag
    with:
      foo: "hello"
```
This would then be equivalent to having defined the caller workflow inputs manually as follows:
```yaml
on:
  workflow_dispatch:
    inputs:
      example_job_bar:
        type: string
        required: true

jobs:
  example_job:
    uses: example_org/example_repo/.github/workflows/reusable.yaml@tag
    with:
      foo: "hello"
      bar: ${{ github.event.inputs.example_job_bar }}
```

Note that this is only one possible idea for an implementation. The main point is that it would be nice to be able to have centrally defined `workflow_dispatch` inputs along with your centrally defined jobs and steps.
