### DISCUSSION TITLE
Support Deployment Environment field for Reusable Workflows

### DISCUSSION THREAD

**Discussion by HariSekhon** [community/community#18085] [Actions]
Feature Request to allow the environment field to be set on a calling reusable workflow, eg:

```
jobs:
  terraform:
    name: Terraform
    uses: HariSekhon/GitHub-Actions/.github/workflows/terraform.yaml@master
    environment:
      name: production
      url: https://domain.com/webapp
```

Currently, the workaround is to have to design inputs for each field in the called workflow and pass through every parameter, which is not ideal.

**Comment by davidruhmann** [comment]
This would be a very nice upgrade to shared workflows!  Also to call out a very important relation to this, having the `vars` expression context available in the [`with` inputs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idwithinput_id).  That way a shared workflow can be truly generic.

An example of what I would like to be able to create:
```yml
name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    strategy:
      matrix:
        cloud_env:
          - { name: production, prerelease: ${{ github.event.release.prerelease }} }
          - { name: development }
        exclude:
          - cloud_env: { name: production, prerelease: true }
    environment: ${{ matrix.cloud_env.name }}
    uses: org/repo/.github/workflows/publish.yml@main
    with:
      account-id: ${{ vars.ACCOUNT_ID }}
    secrets: inherit
```
