### DISCUSSION TITLE
Support env context inside env to be able to compose larger environment variables

### DISCUSSION THREAD

**Discussion by HariSekhon** [community/community#18089] [Actions]
Composing larger environment variables from other variable is a very common thing to do in scripting and in Jenkins.

Please support using the `env` context from within `env` so that one environment variable can reference and be composed of other environment variables.

eg.

```
env:
  DOCKER_IMAGE: "${{env.GHCR_REGISTRY}}/${{env.APP}}"
```
or
```
env:
  DOCKER_IMAGE: "${{env.GCR_REGISTRY}}/${{env.CLOUDSDK_CORE_PROJECT}}/${{env.APP}}"    
```
or
```
env:
  AWS_ECR_REGISTRY: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com  # or generate it from ${{ steps.aws-ecr-login.outputs.registry }} 
```

More detailed full example:

```
on: [push]

env:
  APP: myapp
  REGISTRY: gcr.io
  DOCKER_IMAGE: ${{ env.REGISTRY }}/${{ env.APP }}

jobs:
  env_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$DOCKER_IMAGE"
```

results in:

```
Invalid workflow file: .github/workflows/env_test.yaml#L26
The workflow is not valid. .github/workflows/env_test.yaml (Line: 26, Col: 17): Unrecognized named-value: 'env'. Located at position 1 within expression: env.REGISTRY
```
