### DISCUSSION TITLE
Feature Request: Add statically-defined and lexically-scoped Consts for YAML files

### DISCUSSION THREAD

**Discussion by mikeschinkel** [community/community#18115] [Actions]
I would like to see if it would be possible for GitHub Actions to support statically-defined and lexically-scoped constants in its GitHub Actions `yaml` files?

By _statically-defined and lexically-scoped_ I envision they could be:

1. Available anywhere in the `yaml` file, 
2. Resolved during parsing of the `yaml` file,
3. Set only by a literal or value known at parse time, and thus 
4. Available to cross boundaries that otherwise can't be crossed between jobs, etc.

My use-case for this request came out of this forum post:

- https://github.community/t/concurrency-group-does-not-support-environmental-variables/254742

The following is an example of how I envision they could be declared/used:

```

name: OVA Build
on: push
const:
  EXTERNAL_SERVER_IP: <redacted>
jobs:
  build:
    name: Build OVA
    runs-on: ubuntu-latest
    concurrency:
      group: ova-build-${{ const.EXTERNAL_SERVER_IP }}-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
        ...
```
Thank you in advance for considering.
