### DISCUSSION TITLE
Non-matching on.push.path workflow hangs and blocks test resolution

### DISCUSSION THREAD

**Discussion by abitrolly** [community/community#18496] [Actions]
The workflow in https://github.com/ranger/ranger/pull/2603 waits for `test_shellcheck` to finish.

![image](https://user-images.githubusercontent.com/8781107/173378463-53a5683d-2459-4b64-b967-2947a8d75029.png)

But according to the filter, the workflow should not run at all, as none of these files were modified in the PR.

```yaml
 on: 
   push: 
     paths: 
       - '.github/workflows/shellcheck.yml' 
       - 'ranger/data/scope.sh' 
   pull_request: 
     paths: 
       - '.github/workflows/shellcheck.yml' 
       - 'ranger/data/scope.sh' 
```
