### DISCUSSION TITLE
Support GHA Environment Form Custom Inputs

### DISCUSSION THREAD

**Discussion by ghost** [community/community#18504] [Actions]
Add the ability to provide inputs to deployment approvals for enterprise-type workflows that might require some extra information about the deployment.

Data should be persisted and available from API for later analysis.

```yml
deploy:
    needs: [build]
    name: Deploy
    environment:
        name: staging
        url: http://example.com
        inputs:
            internal_url:
                description: 'Internal URL'
                required: true
                type: string
            business_metrics_dashboard:
                description: 'Business Metrics Dashboard'
                required: true
                type: string
            has_financial_changes:
                description: 'Financial Changes'
                default: 'true'
                type: bolean
```

## Example:
![Screen Shot 2022-06-13 at 10 39 48 AM](https://user-images.githubusercontent.com/106602251/173392184-339b7c15-a6d7-433d-a982-869f470c6922.png)

## Use Cases:
* Can't approve deploy if required Fields are not populated.
* Can query data from GH API later.
* Input values are available in the following Steps of a workflow.
