### DISCUSSION TITLE
Caching on self-hosted runners

### DISCUSSION THREAD

**Discussion by OmgImAlexis** [community/community#18549] [Actions]
So two main issues here.

1. Caching on self-hosted runners makes 0 sense in how it currently works. If I'm self hosting the cache should be on the machine that the runner is on not uploaded/downloaded from Github on every run. This is adding a load of extra bandwidth on both Github's side and our side for no good reason. This is also really unintuitive and it's not mentioned anywhere that I could find. If it is mentioned it's not nearly clear enough. (The only place I can find this is in a single comment from a month or so ago https://github.com/github/docs/issues/2271#issuecomment-1069373652)

2. The cache on Github is slow as can be when using a self-hosted runner. Some cases it completely stalls from the slow speed. (This is in a EC2 instance and we have no issues with speed against any other sites, etc. including github itself for clones, etc.)

This is the code we're using in the action. With the workflow set to use `ubuntu-latest` the cache downloads in ~1s or 150MB/s - 200MBs. 

```yaml
    - name: Load npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
```

![image](https://user-images.githubusercontent.com/6525926/173487277-d4c8fd12-3d6a-4e88-a44c-cec763940e8e.png)
