### DISCUSSION TITLE
Accessing Composite Action within Reusable Workflow from called workflow repo

### DISCUSSION THREAD

**Discussion by HariSekhon** [community/community#18601] [Actions]
### Problem

Composite Actions can be sourced from either an explicit public repo

`- uses: HariSekhon/some-action@v1`

or the local repo

`- uses: ./path/to/action/dir`

but when this is combined with a Reusable Workflow this latter mechanism doesn't really work, as it looks in the source triggered repo and not the reusable workflow repo and of course it fails to find it in the caller's repo:

`Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/CLIENT/REPO/generate-docker-tags@master'. Did you forget to run actions/checkout before running your local action?`

### Feature Request

There needs to be some way of referencing the reusable workflow's own repo in the `uses` step inside the reusable called workflow where the composite action is called.

On occasion an action may want to be bundled into the reusable workflows library repo this means you'd have to hardcode the reusable workflows library:

`- uses: HariSekhon/GitHub-Actions/path/to/action/dir@master`

but this means that any fork of this repo, for example a company forking the repo to control updates, will end up with a broken dependency going outside of the forked repo instead of using the controlled copy in the forked repo.

### Additional Info

The reason you may want to have actions bundled into the same repo as the reusable workflow library is for simplicity or because the action isn't big enough to warrant a separate repo, as this would create a lot of overhead for every little composite action.

This is a gap in reusable workflows because it could become common to have custom actions bundled to deduplicate steps between reusable workflows (eg. a composite action to generate common docker tags like branch, tag, timestamp etc that are used by multiple adjacent reusable workflows eg. docker builds and pushes to DockerHub, GHCR, AWS ECR, GCR etc.)., but for which full-blown public actions are overkill.

**Comment by HariSekhon** [comment]
Raised discussion #18602 for a way to reference own reusable workflow's repo via a context or similar.

**Comment by ajaykn** [comment]
@HariSekhon Thanks for initiating the discussion.

> `- uses: ./path/to/action/dir`
>
> but when this is combined with a Reusable Workflow this latter mechanism doesn't really work, as it looks in the source triggered repo and not the reusable workflow repo and of course it fails to find it in the caller's repo:
> 
> Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/CLIENT/REPO/generate-docker-tags@master'. Did you forget to run actions/checkout before running your local action? 

In order to refer to local workflows, we need to checkout the specific repo.
In your case, the below should work.
```
steps:
   - uses: actions/checkout@v3
      with:
        repository: HariSekhon/some-action
  - uses: ./path/to/action/dir
```

However you mentioned the concerns when reusable workflows with actions referring inside:
> any fork of this repo, for example a company forking the repo to control updates, will end up with a broken dependency going outside of the forked repo instead of using the controlled copy in the forked repo.

Currently the workaround is to have the reusable wf with inputs and that can be controlled to checkout the actions repo.

Called wf:
```
on: 
  workflow_call:
    inputs:
      actions-repo:
        type: string
          default: HariSekhon/GitHub-Actions
jobs:
  job1:
    runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
            with:
              repository: ${{ inputs.actions_repo }}
          - uses: ./test-action1
```

In case the reusable wf library repo is forked, to `HariSekhon-fork/GitHub-Actions` 
We can still control the repo when consuming this reusable workflows.

caller:
```
jobs:
  job1:
    uses: HariSekhon-fork/GitHub-Actions/.github/workflows/my-reusable-wf.yml
    with:
      actions-repo: HariSekhon-fork/GitHub-Actions
```

**Comment by hluaces** [comment]
While the input works, it breaks dependabot workflows. Well, it's not that it _breaks_ them, but rather, that dependabot won't bump your inputs when bumping an action.

Say your private workflow is `v1.0.0` and you're using it in an external repo by passing the input `v1.0.0`. Probably something like:

```yaml
  job1:
    uses: my-repo/.github/workflows/workflow@v1.0.0
    with:
      actions-repo: v1.0.0
```

If you ever release `v1.1.0`, dependabot will update the tag in your external action (e.g.: `@v1.0.0` -> `@v1.1.0`) but it won't update the input. So, you'll end up with:

```yaml
  job1:
    uses: my-repo/.github/workflows/workflow@v1.1.0
    with:
      actions-repo: v1.0.0
```

This forces you to patch all dependabot workflows which is a shame.

**Comment by salvianreynaldi** [comment]
+1.
I create some composite actions and store it in the same repository as my reusable workflows. Having the ability to refer to the composite actions with the same commit (e.g. `${{ github.workflow_sha }}`) would be very helpful to develop and test the actions & workflows more productively

**Reply by rsmets** [reply]
+11 in agreement with this feature request. Annoying running into this myself.

**Comment by BehbudSh** [comment]
This is so annoying.
You are relying on the service and building your CI/CD with the templating best practices and end up with this :)
Any updates?

**Comment by BehbudSh** [comment]
Hello again,
I'm sharing with you my workaround which works pretty well in my case.

`reusable-workflow.yaml`
```
name: Example reusable workflow with composite action
on:
  workflow_call:
    inputs:
      before_script:
        description: 'The script to run before the actual step. Override it with append strategy'
        required: false
        default: |
          echo "### Get Actions ###"
          git clone \
            --branch ${{ github.head_ref }} \ # Using the `github` context in reusable workflows.
            --depth 1 \
            https://$ACCESS_TOKEN_FOR_GITHUB@github.com/<org>/<repo>.git \
            <org>/<repo>
        type: string

env:
  ACCESS_TOKEN_FOR_GITHUB: ${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}  # This trick works with "secrets: inherit", otherwise you can't set secrets context in "with" section of the reusable workflow.

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # To fetch all history for all branches and tags set to 0.

      - name: Execute the command to run before the actual step
        shell: sh
        run: |
          ${{ inputs.before_script }}

      - name: Get the example action
        uses: ./<org>/<repo>/.github/actions/example-action
```


From the caller workflow, you can set your fixed branch or tag to pull actions:
You can modify the before script like that.

`caller-workflow.yaml'
```
jobs:
  example:
    uses: <org>/<repo>/.github/workflows/reusable-workflow.yaml@v1.0.0
    with:
      before_script: |
          echo "### Get Actions ###"
          git clone \
            --branch v1.0.0 \ # Use the fixed version of the reusable workflow
            --depth 1 \
            https://$ACCESS_TOKEN_FOR_GITHUB@github.com/<org>/<repo>.git \
            <org>/<repo> 
    secrets: inherit

```

I hope this helped you!

**Comment by wei18** [comment]
This issue had been bothering me for a while, so I decided to invest some time to build this GitHub Action — even though I'm not very familiar with Bash.

```yaml
name: Your composite action

runs:
  using: 'composite'
  steps:
    - uses: wei18/local-composite-action@v1
      with:
        action_repository: ${{ github.action_repository }}
    
    - name: Run local your composite action
      uses: ./../org/repo/.github/composite-actions/example/just-composite-action

    - name: Run local your second composite action
      uses: ./../org/repo/.github/composite-actions/example/another-composite-action
```

github action: https://github.com/wei18/local-composite-action
I hope this can be helpful to others facing the same issue.

**Comment by alesremta-ext43767** [comment]
We've managed to do this without any forking or checkout out. The only problem was that the composite action must not be in the `.github` folder, instead we create a root folder `actions` and place composite actions in there. Otherwise the "engine" assumes it's a reusable workflow and fails at compile time (saying you can only refer to reusable workflows at the job level).

This works for us for Repositories in the same Organisation

```
//this is a step in a Re-usable workflow calling a composite action in the same repo as the re-usable workflow
- name: Step Name
  uses: <org>/<repo>/actions/<action-folder>@<branch>
```

**Reply by neilime** [reply]
this is a bit risky to hardcode the branch, you can ensure that the code running in the action is the same ref as the workflow it self

**Reply by packocz** [reply]
Yea you are right. In our case we always refer to "trunk". There is a bit of a chicked-and-egg problem for a bit, but mostly it works fine

**Reply by alliepiper** [reply]
How can we write that `uses:` statement to ensure that we're using the same SHA as the current checkout of the reusable workflow?

**Comment by Bradley-McCallion** [comment]
I find it crazy that this isn't a thing, I come from an azure pipelines background and not having the ability to modularise steps within a dedicated _templates_ repo is going to be a deal breaker.

**Comment by jenseng** [comment]
This is possible, albeit with a couple hacky actions I wrote ([get-job-workflow](https://github.com/marketplace/actions/get-job-workflow) and [dynamic-uses](https://github.com/marketplace/actions/dynamic-uses)) 🙈 ... ideally actions/runner would just support this natively

```yaml
# this extracts the current workflow file's information from the worker logs
# e.g. the repo and ref of the current reusable workflow file could be different
# than the top-level workflow that called it
- uses: jenseng/get-job-workflow@v1
  id: job-workflow

# this allows you to call another action dynamically, so that you can avoid hardcoding any refs, etc.
# it's also easier than checking out and running a local action, which can get especially complicated
# if you are checking out another private repo
- uses: jenseng/dynamic-uses@v1
  with: |
    uses: ${{ steps.job-workflow.outputs.repository }}/actions/some-action@${{ steps.job-workflow.outputs.sha }}
```

**Comment by ericsciple** [comment]
Hi everyone 👋

We've been working on a solution for this exact problem. We're proposing a new `$/` syntax that lets reusable workflows reference composite actions in the same repo at the same SHA — no hardcoding refs, and forks work automatically.

```yaml
# In your reusable workflow
- uses: $/generate-docker-tags   # resolves to same repo + same SHA
```

I've posted the full proposal with examples over in [community#26245](https://github.com/orgs/community/discussions/26245#discussioncomment-15601440). We'd love your feedback there!

— The GitHub Actions Team

**Comment by wei18** [comment]
An update on my earlier comment, now that the native `$/` syntax has been proposed in #26245: that proposal is the right long-term answer for same-repo references, but it hasn't shipped yet and is explicitly scoped to **same repository, same SHA** — cross-repository references stay out of scope.

For anyone who needs this working today, the workaround I maintain ([wei18/local-composite-action](https://github.com/wei18/local-composite-action)) has matured since my last post. One step at the top of your composite action, then plain relative paths work:

```yaml
# org/repo/.github/actions/main/action.yml
runs:
  using: 'composite'
  steps:
    - uses: wei18/local-composite-action@v1
      with:
        action_repository: ${{ github.action_repository }}
        action_path: ${{ github.action_path }}

    - uses: ./../org/repo/.github/actions/helper   # ✅ resolves correctly
```

How it works: the runner has already checked your action out under `_actions/` — this just symlinks that checkout next to `$GITHUB_WORKSPACE`, so `./../org/repo/...` resolves to the exact SHA the consumer pinned. Pure bash, no extra checkout, no tokens, no `permissions:`, and forks work automatically because nothing is hardcoded.

Since 1.2.0 it also handles a subtle runner behavior that bit a few people: the on-disk casing under `_actions/` follows the **caller's** `uses:` line, not your repo's canonical name, so resolution is now case-insensitive and a lowercase alias is always created. There's a test suite simulating third-party runner layouts as well.
