### DISCUSSION TITLE
Feature Request: .actionsignore file instead of redundant paths-ignore twice in every workflow yaml - equivalent to .gitignore, .dockerignore, .gcloudignore etc.

### DISCUSSION THREAD

**Discussion by HariSekhon** [community/community#18608] [Actions]
Feature Request to add a `.actionsignore` file support to GitHub Actions to not trigger GitHub Actions workflows when files matching paths in that file are changed.

This should have the same format as `paths-ignore` but would give greater flexibility and allow multiple workflows in a repo to ignore a bunch of irrelevant files, such as `README.md`, `.gitignore`, `.dockerignore`, `Jenkinsfile` and lots of other files that may change but should not warrant triggering a GitHub Actions workflow.

Right now this has to be done in a huge list inside every workflow's `paths-ignore` which is highly redundant even within the same workflow as it has to be done for both `push` and `pull_request`, for example take this snippet and put it in every single workflow in every single repo, so multiply this snippet by a handful to dozens of workflows per repo multiplied by dozens of repos, that's crazy:

```
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/Jenkinsfile'
      - '**/.envrc*'
      - .checkov.yaml
      - .dockerignore
      - .gcloudignore
      - .editorconfig
      - .gitconfig
      - .gitignore
...
...
...
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/Jenkinsfile'
      - '**/.envrc*'
      - .checkov.yaml
      - .dockerignore
      - .gcloudignore
      - .editorconfig
      - .gitconfig
      - .gitignore
...
...
...
```

and also if templating workflows this is a problem because different repos should have different list of `paths-ignore`, which is why Git, Docker, GCloud SDK, Terraform etc all have their own repo local .ignore files.
