### DISCUSSION TITLE
[Bug] `workflow_dispatch` with incorrect config hangs the UI instead of providing any kind of visible error

### DISCUSSION THREAD

**Discussion by passcod** [community/community#18697] [Actions]
![Screenshot from 2022-06-16 10-41-15](https://user-images.githubusercontent.com/155787/173954956-5542609e-db23-4539-8bd4-486106bb8bf8.png)

I had:

```yaml
name: Open a release PR
on:
  workflow_dispatch:
    inputs:
      crate:
        description: Crate to release
        required: true
        type: choice
        choices:
          - cli
```

when the correct syntax is:

```yaml
name: Open a release PR
on:
  workflow_dispatch:
    inputs:
      crate:
        description: Crate to release
        required: true
        type: choice
        options:
          - cli
```

Only finding the similar issue https://github.com/github-community/community/discussions/15097 provided a hint as to what to do! Not a great experience.
