### DISCUSSION TITLE
Feature Request: Add tags filter to release event trigger

### DISCUSSION THREAD

**Discussion by rmeneely** [community/community#18815] [Actions]
### Problem Statement
Currently the release event trigger does not provide a filter for the _tag_ that is related to the release.
There is always a tag associated with the release which is available as `github.event.release.tag_name`, however there is currently no supported mechanism to filter the release event trigger for a workflow based upon the value of that tag. This means that it is currently not possible to trigger different release workflows based upon the value of the release tag.

**Use case**
We use different release tag conventions for production ('v*') vs. release candidate ('rc*) releases. As we are using trunk-based development, these workflows are run on the same (main) branch, however we have very different workflows depending on the release tag. We would like to filter the release event trigger based upon the pattern of the tag so that only the correct workflow is triggered.

> **Note** 
That _push_ event does support a tags filter i.e.
```
on:
  push:
    tags:        
      - v1.**
```

### Request
This is a request to support that same functionality on the _release_ event. For example:
```
on:
  release:
    types: [published]
    branches: [ main ]
    tags:
      - 'v1.**'
```
