### DISCUSSION TITLE
How to trigger check_run.requested_action in GitHub Actions?

### DISCUSSION THREAD

**Discussion by TWiStErRob** [community/community#19069] [Actions]
Full code at https://github.com/TWiStErRob/github-actions-test/tree/2773ede31373bf02a6b1b80d31e0d011c8e6671e in check-run.yml and check-run-action.yml. Very hacky manual workaround in https://github.com/TWiStErRob/github-actions-test/pull/4

I have a step that produces a check:
```yml
      - name: "Create a check run"
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "my-check-name",
              status: "completed",
              conclusion: "success",
              output: {
                title: "my *check* title",
                summary: "my *check* summary",
                text: "my *check* text,
              },
              actions: [
                {
                  label: "My Check Action",
                  description: "My check action description.",
                  identifier: "my-check-action",
                },
              ],
            });
```

and a workflow that responds to above action.
```yml
name: Custom Check Run Action
on:
  check_run:
    types:
      - requested_action
jobs:
  custom-check-run-action:
    name: Reaction to Check Run Action click
    if: github.event.requested_action.identifier == 'my-check-action'
    runs-on: ubuntu-latest
    steps:
      - name: Do the thing
        run: echo "all good"
```

I ran the step to create the check run, and the result is as expected:
![image](https://user-images.githubusercontent.com/2906988/174870372-0fbad8fb-1fe2-4b3e-84bc-e4fa14bf01ee.png)

I click the button and I even get a nice notification saying it's all good:
![image](https://user-images.githubusercontent.com/2906988/174870433-4722e7fc-adeb-4421-a826-22381629da1f.png)

The question is: where does this event go? because the workflow executions are empty:
![image](https://user-images.githubusercontent.com/2906988/174870552-0fcc265a-8853-4e00-b374-1c1a7922aaaf.png)

---

I would like to note here how impossible it is to research anything about this feature as it's called "actions on check runs in github actions", even a human can barely understand this, let alone Google.
