### DISCUSSION TITLE
Docker pull Issues when using pre-built Github actions

### DISCUSSION THREAD

**Discussion by Johnny-Shir** [community/community#19170] [Actions] [answered]
Hey guys,
Since today I've been experiencing an annoying problem:
Within my Github Actions CI YAML I have a step that reports failures to slack:
```yaml
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.2.0
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'system test has failed!'
        SLACK_TITLE: Build Error
        SLACK_USERNAME: CI
```
This step has a pre-job step that's executed that pulls the relevant docker image from `ghcr.io/rtcamp/action-slack-notify:v2.2.0`.
This step runs before any step that I defined within the YAML, and it fails with the following error (after 2 retries):
```
 error pulling image configuration: download failed after attempts=1: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
Error: Docker pull failed with exit code 1
```
Isn't the relevant token the `GITHUB_TOKEN` itself? And if so, I have all write permissions so it shouldn't be an issue.

Anyone run into this?
Thanks in advance!
Johnny
