### DISCUSSION TITLE
Release notes category for conjunction of labels

### DISCUSSION THREAD

**Discussion by tomalec** [community/community#19211] [Other Feature Feedback, Questions, & Ideas]
While setting up a [`github/release.yml` configuration](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options) to categorize the changelog entries,
I absolutely love the fact I can use simple and visible labels, like `enhancement`, `fix`, `breaking-change`, to distinguish the entries.

However some of our repos release multiple packages at once, and I'd like to use a conjunction of labels to match a given category, like:
```yaml
changelog:
  categories:
    - title: Foo Package Breaking Changes
      labels:
        - "changelog: breaking" && "package: foo"
    - title: Bar Package Breaking Changes
      labels:
        - "changelog: breaking" && "package: bar"
```

Is that somehow possible? Or are you willing to consider such a feature request?

----

The only way I found out to make it work, is to do:
```yaml
changelog:
  categories:
    - title: Foo Package Breaking Changes
      labels:
        - "package: foo"
        - "changelog: breaking"
      exclude:
        labels:
          - "package: bar"
          - "package: baz"
          - "changelog: fix"
          - "changelog: add"
          # enumerate all other possible package and changelog labels
```
But it does not scale well if I have more categories.

----

I was thinking, it could be solved by making a custom action to do that bit of logic around PR labels.
But unfortunately, [release notes API](https://docs.github.com/en/rest/releases/releases#generate-release-notes-content-for-a-release) does not return the list of PRs. Only the text content. Parsing it to get PR numbers, then asking pulls API one by one, seems to be way unstable workaround.
