### DISCUSSION TITLE
Feature request - Environment Deployments with payload

### DISCUSSION THREAD

**Discussion by devminded** [community/community#19304] [Actions]
# Feature request - Environment Deployments with payload

## Purpose

Being able to add custom task and payload properties to the Deployment so that we can leverage Deployment webhook events and external deployment protection rules. This will allow us to use attestations and external approvals based on more than just the repo, environment and sha.

## Proposal

- Optional field "payload" that is used when creating the deployment.
  - Should be yaml object of key-value pairs or a (JSON) string.
  - Implementation should properly convert/escape/stringify according to the Deployment API spec and selected webhook type (form/json).
  - Shall equally apply to deployment property in Deployment Protection Rules payload.
- Optional field "task" that is used when creating the deployment.

**Example:**

```yaml
jobs:
  deploy-to-prod:
    name: "Deploy movies ${{jobs.other.outputs.version}}"
    environment: production
    task: deploy:pod
    payload:
      version: ${{jobs.other.outputs.version}}
      service: movies
      auth: ${{secrets.PROD_TOKEN}}
    timeout-minutes: 15
    steps:
      - run: echo "Deploying..."
```
