### DISCUSSION TITLE
Feature Request - Manual triggers/deployments in addition to Environment Approvers

### DISCUSSION THREAD

**Discussion by devminded** [community/community#19397] [Actions]
# Feature Request - Manual triggers/deployments in addition to Environment Approvers

## Purpose
Allow manual triggers of jobs (and deployments) to support optional processes and workflows.

## Proposal
Today we only have the option of using Environments with approvals and they are all treated as a deployment.
The downside of this is that "who can run a job/deploy" must be predefined by someone with permission to change repo settings.
Another problem is that they always creates a deployment behind the scene (see Deployment API) even if there is no need.
In todays world of many commits/builds per day those approvers get spammed with approval requests, in the end people get overwhelmed.

**Scenarios**
1. **Pipeline with mostly automated jobs combined with manual jobs targeting a group of people**
    - Testers being able to trigger a deployment of any build (active pipeline) to a test environment.
    - Teams being able to manually "promote/notify" a build/report to external entities (think: audit, UAT, etc) 
2. **Pipeline with protected environment and deferred deployment**
    - Environment protection rules blocks manual trigger until approved.
    - Production deployments requiring approvals, but deployment is manual and deferred to anyone in the team once approved.
3. **Other process-automation workflows**
    - Complex workflows which performs data-migrations on-demand with optional jobs to continue/revert (i.e judgment).
    - Advanced release management, dark launching, A/B tests, etc.

### Requirements
- Add new optional boolean field "manual" (default: false).
- Display a "play button" on the jobs to users with the right permission.
- Shall be greyed-out until any eventual Environment protection rules first has passed (if environments is used with the job).
- New permission **actions:manual** so that we can control access to which members that can manually trigger jobs.
- Include this new permission to anyone with role "maintainer" or higher maybe (discussion?).
- Must adhere to audit logging policies.
- Possibly matching changes in the API as well.
- This allows for required managerial approvals and then any user with permission can trigger the actual deploy.

## Examples
```yaml
deploy-to-prod:
  runs-on: ubuntu-latest
  manual: true
  environment: production  # Example: require managerial approvals
  timeout-minutes: 15m
  steps:
  - name: Do it
    run: echo "Did it!"
```

```yaml

perform-migration:
  runs-on: ubuntu-latest
  manual: true
  timeout-minutes: 1h
  steps:
  - name: Migrate it
    run: echo "Migrated it!"
```
