### DISCUSSION TITLE
Skip job and take previous conclusion

### DISCUSSION THREAD

**Discussion by tisonkun** [community/community#19704] [Actions]
In https://github.com/apache/incubator-kvrocks/pull/695 I'm trying to skip job in `daily-ci.yaml` if a new label added but not `needs-daily-ci`, while I'd like to take the status which reported from a previous run if any.

```yaml
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build-docker-image:
    name: Build Docker Image
    if: |
      (github.event_name != 'pull_request') ||
      (github.event.action == 'labeled' && github.event.label.name == 'needs-daily-ci') ||
      (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'needs-daily-ci'))
    # ...
```

Right now,
* If I add another label != `needs-daily-ci`, the workflow will be triggered and report skipped, while I'd like to take the previous conclusion.
* If I use condition `action == 'labeled' && contains(...labels..., 'needs-daily-ci')` only, it will trigger one more instance if I add another label != `needs-daily-ci`, which is unnecessary.
