### DISCUSSION TITLE
Feature request :rocket: - Deploy private services in Github Actions from AWS or others

### DISCUSSION THREAD

**Discussion by damvolkov** [community/community#19819] [Actions]
Hi community!

I would like to ask for a feature (or in case of me missing this feature please help me to see how to proceed), when deploying actions in github CI.

```
jobs:
      backend-job:
            name: CI backend Integration env
            runs-on: ubuntu-latest
            services:
                  postgres:
                        image: postgres:10
                        ports:
                              - 5432:5432
                  rabbitmq:
                        image: rabbitmq
                        ports:
                              - 5672:5672
                  redis:
                        image: redis:alpine
                        ports:
                              - 6379:6379
            steps:
                  - name: Step 1
                    uses: ...
                  - name: Step 2
                    uses: ...
```
and add own docker-based app containers (from aws, google, heroku... whatever) passing credentials like:

```
...

            services:
            
                .....
                
                   some-aws-service:
                        image: XXXXXXXXX.YYY.ecr.eu-west-1.amazonaws.com/<AWS OWN SERVICE>:latest
                        ports:
                              - 5000:5000
                         credentials:
                             username: ${{ secrets.AWS_ACCESS_KEY_ID }}
                             password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

Following multiple approaches like proposed (here:)[https://docs.github.com/es/actions/using-jobs/running-jobs-in-a-container]

But I receive this:

![image](https://user-images.githubusercontent.com/58026317/176880212-78bdecde-39be-4d3e-a545-a85169ca601b.png)

I also added these (steps)[https://github.com/aws-actions/amazon-ecr-login] at the begining:

```
- name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
        aws-region: us-east-1

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

...
```

But nothing was possible...

Can you shed more light on this please?

Many thanks in advance!!!!

**Comment by verkhoro** [comment]
Yeah, https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/ should be a bit more explicit that private ECRs are not supported. It takes some amount of trying and failing to figure this out

**Comment by al1076954** [comment]
You can manually build your image on another step like this
```        
docker build  -f $GITHUB_WORKSPACE/docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION .
docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION````

Where $ECR_REGISTRY is given by the "aws-actions/amazon-ecr-login" action as output : "outputs.registry"

**Comment by BeyondEvil** [comment]
Here's a workaround that works for us.

Note that we're using **self-hosted runners**.

This is not a complete workflow configuration, I've just added the bits that matter:

```yaml
jobs:
  setup:
    runs-on: large
    env:
      ECR_REGISTRY: ${{ secrets.DEPLOYMENT_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install aws cli
        uses: ./.github/actions/install-aws-cli
      
      - name: Get ECR password
        run: echo "AWS_ECR_PASSWORD=$(aws ecr get-login-password --region us-west-2)" >> $GITHUB_OUTPUT
        id: aws

    outputs:
      aws_ecr_password: ${{ steps.aws.outputs.AWS_ECR_PASSWORD }}

  test:
    runs-on: large
    needs: setup
    env:
      POSTGRES_HOST: localhost
    services:
      postgres:
        image: ${{ secrets.DEPLOYMENT_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/postgres:13.5
        credentials:
          username: AWS
          password: ${{ needs.setup.outputs.aws_ecr_password }}
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```

Background:

We're running our self-hosted runners in an EKS cluster and to avoid pulling from DockerHub and risk getting blocked due to limits, we mirror the public images that we use in our own ECR registry.
