### DISCUSSION TITLE
More validations options for issue forms

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#20239] [Projects and Issues]
Right now, the `validations` option seems to only have one option, which is `required: <boolean>`

Looking at what issue forms currently offers did I come up with a few ideas for extra options to add:

#### `minAmount: <number>` / `maxAmount: <number>`

The `minAmount` and `maxAmount` options would be useful for the `checkboxes` but also the `dropdown` type to define a required amount of checked options.
This could be useful for cases where a person can select multiple options, but not all are required.

Example syntax:
```yaml
body:
  - type: checkboxes
    attributes:
      label: 'Checkboxes example'
      description: 'Please select at least one, but not more than 3 options.'
      options:
        - label: 'Option 1'
        - label: 'Option 2'
        - label: 'Option 3'
        - label: 'Option 4'
    validations:
      minAmount: 1
      maxAmount: 3
```

#### `regex: <string>`

The `regex` option would be usable for `input` and `textarea` types.
It essentially checks the user's input against the regex and only allows the creation of the issue if the regex matches.
It could be considered to also add custom error messages (More on that in the next section).

Example syntax:
```yaml
body:
  - type: input
    attributes:
      label: 'Software Version'
      description: 'Please provide the output of `example --version`'
      placeholder: 'example --version'
    validations:
      regex: '^example-\d\.\d\.\d(?:-DEV)?' # I'm not a pro at Regex...
```

#### Custom error messages

Maintainers may want to provide some informative errors when an input is either missing or invalid, so it should be considered to allow providing a own, custom error message for when a validation failed.

Basic markdown (Bold, italic, inline code) should be supported.

Using the previous regex idea, here's a possible configuration for this:
```yaml
body:
  - type: input
    attributes:
      label: 'Software Version'
      description: 'Please provide the output of `example --version`'
      placeholder: 'example --version'
    validations:
      regex: '^example-\d\.\d\.\d(?:-DEV)?' # I'm not a pro at Regex...
      errorMessage: 'Make sure the value is a valid version matching `example-<major>.<minor>.<patch>` or `example-<major>.<minor>.<patch>-DEV` for dev versions.'
```
