### DISCUSSION TITLE
Debug logs for the if condition of skipped jobs

### DISCUSSION THREAD

**Discussion by roryabraham** [community/community#20640] [Actions] [answered]
Coming from:

- https://github.com/actions/runner/issues/1995
- https://github.com/actions/runner/issues/1996
- https://github.community/t/debug-logs-for-the-if-condition-of-skipped-jobs/261822

When a job is skipped because it’s if condition is not met, it’s very difficult to debug why that happened. It would be valuable to be able to see debug logs for the evaluation of the job-level if condition.

It’s sometimes possible to work around this by creating another job without a conditional and then creating steps with the same if condition that is used at the job-level for another job ([Example](https://github.com/Expensify/App/runs/7312387282?check_suite_focus=true)). However, it’s inconvenient and not safe to assume that the evaluation of a condition is going to be the same at the job and step level.

Furthermore, when using a callable workflow, the job in the caller workflow will be skipped if none of the if conditions are met for the jobs inside the callable workflow, which was difficult to figure out. Maybe the UI could be altered to make this more clear, but the debug logs would have really helped.

Thanks! Curious to hear people’s thoughts.

**Comment by dhirschfeld** [comment]
My jobs are being mysteriously skipped even though I'm sure the `if` condition should evaluate to true. I have debug logging turned on but the only information the GitHub UI gives me is:

![image](https://user-images.githubusercontent.com/881019/201522679-86081e8b-ec74-4c4a-b8a1-fbe5f3cdbe33.png)

I would like the UI to provide me some way to ascertain ***why*** the job was skipped.

**Reply by dhirschfeld** [reply]
> *even though I'm sure the `if` condition should evaluate to true*

The `if` condition does in fact evaluate to true if I put the same expression in a step rather than a job.

I'm at a bit of a loss as to how I'm supposed to debug an expression at the job level which evaluates to something different than it does at a step level?

**Reply by dhirschfeld** [reply]
Posting my workaround in case it's helpful. I have a boolean input variable:
```yaml
on:
  workflow_call:
    inputs:
      cond_a:
        type: boolean
        default: true
```
...and want to run a job if `cond_a` is true. I would've expected the below to work:
```yaml
  run_if_cond_a_is_true:
    needs: [skipped_job]
    if: always() && ${{ inputs.cond_a }}
```
...but it didn't!?! If I used the condition `always() && ${{ inputs.cond_a }}` in a step, the step ran just fine.

My horrific workaround is to echo the inputs in a job and use the job outputs in my condition 🤮
```yaml
  echo_inputs:
    runs-on: ubuntu-latest
    outputs:
      cond_a: ${{ steps.echo_inputs.outputs.cond_a}}
    steps:
      - id: echo_inputs
        shell: bash
        run: |
          echo "cond_a=${{ inputs.cond_a}}" >> $GITHUB_OUTPUT
```
```yaml
  run_if_cond_a_is_true:
    needs: [echo_inputs, skipped_job]
    if: always() &&  needs.echo_inputs.outputs.cond_a
```

Surely using a boolean input variable in the `if` condition of a job should Just Work, exactly as you would expect it to, and exactly as it does work in a step?

**Reply by ChristopherHX** [reply]
> `always() && ${{ inputs.cond_a }}`

This is not supported (yet ?) and get converted to `${{ success() && (format('always() && {0}', inputs.cond_a)) }}`.

_Intentionally I would have tried it with the same invalid syntax as you have tried_
Fair enough this would have worked in Azure Pipelines, because it uses a different rule to evaluate custom if conditions

**Comment by ChristopherHX** [comment]
I made an emulator for GitHub Actions, which shows you debug output of job level if conditions.
https://github.com/ChristopherHX/runner.server
You might be able to use it for troubleshooting issues with job level if conditions, I'm unaware of compatibility issues with job if conditions compared to the official GitHub Actions Services.

_Weird enough, you can get the debug logs of job if conditions in Azure Pipelines (The current GitHub Actions Service + Runner is a fork of it from 2019)._

**Comment by tylermilner** [comment]
I struggled with this for a few hours. Everything seemed like the `if` conditional on my "test" job should have evaluated to `true`, but the job was always being mysteriously skipped. For me, it had to do with how I set and accessed the `should_run` variable being used in the job's `if` conditional. Here are some examples of my failed and working configs:
1. Quotes around `true` value --> job "test" _skipped_ (**FAIL**):
```yaml
name: CI

on:
  - push
  - workflow_dispatch

jobs:
  run-check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.set-output.outputs.should_run }}
    steps:
      - name: Set job output
        id: set-output
        run: |
          echo "should_run='true'" >> $GITHUB_OUTPUT
          
  test:
    runs-on: ubuntu-latest
    needs: run-check
    if: ${{ needs.run-check.outputs.should_run == 'true' }}
    steps:
      - uses: actions/checkout@v3
```

2. No quotes around `true` value --> job "test" _skipped_ (**FAIL**):
```yaml
name: CI

on:
  - push
  - workflow_dispatch

jobs:
  run-check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.set-output.outputs.should_run }}
    steps:
      - name: Set job output
        id: set-output
        run: |
          echo "should_run=true" >> $GITHUB_OUTPUT
          
  test:
    runs-on: ubuntu-latest
    needs: run-check
    if: ${{ needs.run-check.outputs.should_run == true }}
    steps:
      - uses: actions/checkout@v3
```

3. Quotes around `true` when set, but not in conditional --> job "test" _skipped_ (**FAIL**):
```yaml
name: CI

on:
  - push
  - workflow_dispatch

jobs:
  run-check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.set-output.outputs.should_run }}
    steps:
      - name: Set job output
        id: set-output
        run: |
          echo "should_run='true'" >> $GITHUB_OUTPUT
          
  test:
    runs-on: ubuntu-latest
    needs: run-check
    if: ${{ needs.run-check.outputs.should_run == true }}
    steps:
      - uses: actions/checkout@v3
```

4. Quotes around `true` in conditional, but not when set --> job "test" _not skipped_ (**SUCCESS**):
```yaml
name: CI

on:
  - push
  - workflow_dispatch

jobs:
  run-check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.set-output.outputs.should_run }}
    steps:
      - name: Set job output
        id: set-output
        run: |
          echo "should_run=true" >> $GITHUB_OUTPUT
          
  test:
    runs-on: ubuntu-latest
    needs: run-check
    if: ${{ needs.run-check.outputs.should_run == 'true' }}
    steps:
      - uses: actions/checkout@v3
```

Making a copy of the skipped job without the `if` conditional and adding an additional step that `echo`'d the value being checked in the conditional was a great tip and helped me debug. Here is how that extra job looked in my case:
```yaml
  test-debug:
    runs-on: ubuntu-latest
    needs: run-check
    steps:
      - uses: actions/checkout@v3
      
      - run: |
          echo "Check 'should_run'"
          echo "${{ needs.run-check.outputs.should_run }}"
```

Hopefully this helps someone running into a similar issue. I do agree that it would have made debugging this much easier if there was some sort of information in the web UI as to _why_ a job is skipped.

**Reply by achimnol** [reply]
So the job outputs are *always* strings, no matter how they are set in previous jobs.
Context variables may have native types like boolean.

It becomes so confusing when evaluation of both job outputs and context variables come in a single 'if' expression.... 😞

Technically I could understand that there is no way to determine whether a job output value is intended to be a string or a native expression like context variables when they overlap and it would be safer to treat them as user-input strings, but **this behavioral difference should be documented in a more clearer way, with concrete "pitfall" examples.**

**Comment by cliffchapmanrbx** [comment]
I'm disappointed that this has not been prioritized by the GitHub Actions team when it's a feature Azure DevOps Pipelines had half a decade ago.

On a daily basis my team receives requests from other engineers for help diagnosing why steps were skipped or workflows cancelled unexpectedly. 

![image](https://github.com/community/community/assets/47404136/dd00a4c8-383b-48a5-aebd-4ff9aa46463a)

**Comment by dolfandringa** [comment]
I think its really bad practice to require users to modify the actions with additional jobs just to debug why a job was skipped. It makes the process really slow since you now need to go through code review process, just to debug, and you may potentially break the action for other users in the process. Being able to see why a step was skipped directly when running the action would speed up development a lot. Especially since github actions can be complex and powerful, the debugging tools need to reflect that.

**Comment by kzhou57** [comment]
This is an essential feature.

**Comment by mdarvanaghi** [comment]
Why is there no answer from GitHub on this? Like @kzhou57 says, it's an essential feature.

**Comment by bluebasher** [comment]
This really is an essential feature and it's highly weird that GitHub hasn't implemented it yet.
Because of this I had to spend half a day debugging to figure out why my step was skipped

Maybe it helps other: My `apply-cluster` step depends on the `plan-cluster` step. For a specific reason the `plan-cluster` needs an `always()` statement in the if-condition. The if-condition for the `apply-cluster` did not have the always() statement as it only checked for the result of the `plan-cluster`. But apparently it will always be skipped in that case. The `apply-cluster` NEEDS to also have an always() statement, if it depends on another step that has an always().

```
  plan-cluster:
    name: Plan Cluster
    needs: [plan-environment, deploy-environment]
    if: ${{ always() }}
```

```
  deploy-cluster:
    name: Deploy Cluster
    if: ${{ always() && needs.plan-cluster.result == 'success' && needs.plan-cluster.outputs.should_deploy == 'true' && needs.plan-cluster.outputs.has_changes == 'true' }}
    needs: [plan-cluster]
```

**Comment by ericsciple** [comment, marked as answer]
Expression logs for skipped jobs (and non-skipped jobs), can now be viewed in the system log from the download zip:
- https://docs.github.com/en/actions/how-tos/monitor-workflows/view-job-condition-logs

**Reply by shayki5** [reply]
This is AWESOME!

**Reply by 0xMurage** [reply]
Just tested this, logs for skipped **jobs** with  `if: always() && success()` are never included in the exported zip.

```yaml
  job-x:
    name: Job skipped but never included in logs
    runs-on: ubuntu-latest
    if: always() && success() && !cancelled()
```
