### DISCUSSION TITLE
GitHub Actions Extra Lines When Piping to File

### DISCUSSION THREAD

**Discussion by fishcharlie** [community/community#20774] [Actions]
I have the following code in my GitHub Action Workflow file.

```
- name: Save Terraform Output to JSON File
  run: |
    terraform output -json > output.json
- name: Upload Terraform Output JSON File as Artifact
  uses: actions/upload-artifact@v3
  with:
    name: terraformOutput
    path: output.json
```

However, when I download the artifact file, I see a bunch of extra lines:

```
[command]/home/runner/work/_temp/59756a93-8dd6-479b-ac36-25cce5af6f4d/terraform-bin output -json
{
  "hello": {
    "sensitive": false,
    "type": "string",
    "value": "world"
  }
}
::debug::Terraform exited with code 0.
::debug::stdout: {%0A  "hello": {%0A    "sensitive": false,%0A    "type": "string",%0A    "value": "world"%0A  }%0A}%0A

::set-output name=stderr::

::set-output name=exitcode::0
```

I expected the artifact file to be:

```
{
  "hello": {
    "sensitive": false,
    "type": "string",
    "value": "world"
  }
}
```

Why is GitHub Actions adding all those extra lines, and how can I remove them to only include the object in the Artifact?

**Comment by fishcharlie** [comment]
It turns out this is a direct result of the `hashicorp/setup-terraform` GitHub Action. As mentioned in their README:

> Installing a wrapper script to wrap subsequent calls of the terraform binary and expose its STDOUT, STDERR, and exit code as outputs named stdout, stderr, and exitcode respectively. (This can be optionally skipped if subsequent steps in the same job do not need to access the results of Terraform commands.)

Changing my code to the following worked:

```
- name: Terraform Output
  id: terraformOutputJSON
  run: terraform output -json
- name: Save Terraform Output to JSON File
  uses: fishcharlie/CmdToFile@v1.0.0
  with:
    data: ${{ steps.terraformOutputJSON.outputs.stdout }}
    output: output.json
```

Basically I'm just running the `terraform output -json` command in one step, then in the next one, I'm accessing the output that `hashicorp/setup-terraform` automatically provides, then passing that into a quick action I created to take that and write it to a file.

Sadly I couldn't figure out how to just echo the result to a file because the JSON format always got messed up when trying to do that.

**Comment by ferdnyc** [comment]
@fishcharlie According to their docs, either of these should work:

#### Skip the wrapper script
```yml
- uses: hashicorp/setup-terraform@v2
  with:
    terraform_wrapper: false
- name: Save Terraform Output to JSON File
  run: |
    terraform output -json > output.json
- name: Upload Terraform Output JSON File as Artifact
  uses: actions/upload-artifact@v3
  with:
    name: terraformOutput
    path: output.json
```

#### Grab the command's stdout after execution, rather than using redirection
```yml
- uses: hashicorp/setup-terraform@v2
- name: Run Terraform
  id: terraform-json
  run: |
    terraform output -json
- name: Save Output to JSON File
  run: |
    echo '${{ steps.terraform-json.outputs.stdout }}' > output.json
- name: Upload Terraform Output JSON File as Artifact
  uses: actions/upload-artifact@v3
  with:
    name: terraformOutput
    path: output.json
```

**Reply by ferdnyc** [reply]
The second option may be what you've already tried (though the single-quotes around the substitution would be critical), if the output isn't being formatted properly then — assuming it's still _valid_ but simply not wrapped as expected — you could try running it through a  tool like `json_pp` before writing to file:
```yml
- name: Save Output to JSON File
  run: |
    echo '${{ steps.terraform-json.outputs.stdout }}' | json_pp > output.json
```
You might have to install `json_pp` using `apt` in a preceding step.
