### DISCUSSION TITLE
[Feature Request] Support auto-retry for jobs upon terminated spot instances

### DISCUSSION THREAD

**Discussion by dapirian** [community/community#20960] [Actions]
For autoscaling self-hosted runners on spot instances, occasionally a spot instance is reclaimed and github loses contact with that runner. There should be some way to add auto-retries in the case that github loses contact with a runner - restart the job on another runner.

Buildkite supports auto-retries upon losing contact with a runner specifically for this situation, github actions should support something similar:

```
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
```
