### DISCUSSION TITLE
[Feature Request] Allow all appropriate checks to be scoped to branches

### DISCUSSION THREAD

**Discussion by george-e-shaw-iv** [community/community#21037] [Actions]
Similar to how you can do:

```yaml
on:
  pull_request:
    types:
      - opened
    branches:    
      - 'releases/**'
```

for a pull_request type action, I would like the ability to specify the `branches` filter on all actions that could be scoped to branches - like `status` checks.
