### DISCUSSION TITLE
Workflows triggered by the workflow_run event are sometimes skipped

### DISCUSSION THREAD

**Discussion by oleg-derevenetz** [community/community#21090] [Actions]
Hi all,

A few days ago I noticed that events triggered by the `workflow_run` event are sometimes just skipped without any obvious reason. For example, in this repo:

https://github.com/ihhub/fheroes2/actions

workflow with the name “Clang-Tidy comments” should be triggered when the workflow with the name “Clang-Tidy” is completed - to post the diagnostic results to a pull request. However, sometimes this works as expected, and sometimes the “Clang-Tidy comments” is just skipped. I don’t see any logic and no patterns in this behavior. The only valid reason to skip the run would be the case when the parent workflow fails, because there is a check for this in the “Clang-Tidy comments” workflow’s job:

```
if: ${{ github.event.workflow_run.conclusion == 'success' }}
```

but it isn’t the case, the parent workflow has the “Success” status. Any ideas?

Thank you in advance for your help.

**Comment by vicfergar** [comment]
Same problem here!

**Comment by fredicious** [comment]
We are experiencing the same problem, we are using the exact same condition 
```
    if: "contains(github.event.workflow_run.conclusion, 'success')"
```
and sometimes it will skip even when the origin workflow was successful, no matter how many times we try to re-run. Also a re-run with the flag `Enable [debug logging]` is not giving any more info on why it was skipped.

This is very annoying as sometimes we have 3 workflows chained (build / release / deploy) and we can't easily re-trigger them manually.

**Reply by jaycle** [reply]
At risk of adding an unhelpful and annoying +1 in the thread, we also have started having what seems like intermittently skipped steps. This behavior _seems_ to have started Jul 21st.

Our if condition is as follows:

```
if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
```

(always when not workflow_run, and for successful workflow runs).

**Reply by oleg-derevenetz** [reply]
@jaycle According to my observations, this started ~4 days ago, so yes, around this time.

**Reply by fredicious** [reply]
same here actually (though we have seen this happen a couple of times in the past year, but never as much as in the last days)

**Reply by sharpedavid** [reply]
Also experiencing this problem, and the most in the past week.

**Comment by shreecodes** [comment]
We started hitting this same issue last week. It turns out that the `conclusion` field is sometimes empty or null. As a workaround, we added a job to manually fetch the `conclusion` using [octokit/request-action](https://github.com/marketplace/actions/GitHub-API-Request):

```
  get_workflow_conclusion:
    name: Lookup Conclusion of Workflow_Run Event
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ fromJson(steps.get_conclusion.outputs.data).conclusion }}
    steps:
      - name: Get Workflow Run
        uses: octokit/request-action@v2.1.0
        id: get_conclusion
        with:
          route: GET /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Reply by shreecodes** [reply]
This workaround has been working consistently without issue for us for the last couple of weeks.

**Comment by edubacco** [comment]
same issue here

**Comment by davidgourde** [comment]
Same issue. I posted it on Stack Overflow and found this thread from the comments. [Here's the link to my post](https://stackoverflow.com/questions/73113691/github-workflow-run-conclusion-now-randomly-returns-an-empty-string-even-when-su/73127657#73127657) for more information on my tests.

Overall, I think it started last week (on the 21st of July for me) and that sometimes the output of workflow_run.conclusion is an empty string (even though that's not a documented possibility).

**Comment by zoispag** [comment]
Plus one. All workflow_run builds started to fail a few hours ago, and I then noticed that it also happened randomly a few times last week.

**Comment by jinchuantang** [comment]
same issue here, started to happen about 7 days ago

**Comment by gabrielsaldana** [comment]
Same issue here. 

It seems that the `github.event` context is missing the `workflow_run` key completely.

I'm using this workflow to debug:

```
name: Debug workflow

on:
  push:
    workflow_run:
      workflows: [Run Tests]
      types: [completed]
      branches: [debug-workflow]
  workflow_dispatch:

jobs:
  debug-workflow:
    name: Debug information
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
````

On the printed JSON, the `event` doesn't have a `workflow_run` key.

**Comment by participator** [comment]
This note was helpful.

> Note: This event will only trigger a workflow run if the workflow file is on the default branch.

Reference: [Workflow Events - workflow_run documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)

**Comment by KaimingWan** [comment]
In my case, you have to use a workflow name without space then you can get value of `github.event.workflow_run.conclusion`

The failed case, dependent workflow name is `Prepare Streaming Cluster Benchmark`
```
on:
  workflow_run:
    workflows: [ "Prepare Streaming Cluster Benchmark" ]
    types:
      - completed
```

The success case after change my workflow name to `Prepare-Streaming-Cluster-Benchmark `
```
on:
  workflow_run:
    workflows: [ Prepare-Streaming-Cluster-Benchmark ]
    types:
      - completed
```
