### DISCUSSION TITLE
[Feature Request] jobs.<job-id>.continues-from

### DISCUSSION THREAD

**Discussion by CAD97** [community/community#21094] [Actions]
Example usage (Rust):

```yaml
  # Build tests.
  test-build:
    name: cargo test --no-run
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: ./.github/actions/rustup
      - name: Cache Rust
        uses: actions/cache@v3 # NB: better caching strategies are available
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build tests
        run: cargo test --all-features --all-targets --no-run

  # Run tests.
  test:
    name: cargo test
    continues-from: test-build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        features: [--no-default-features, "", --all-features]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run tests
        run: cargo test ${{ matrix.features }} --all-targets --no-fail-fast
```

The semantics of this would be that the runner state is snapshot at the end of the continued-from job (matrix) and restored to start the continuing-from job (matrix). Supporting continuing from a matrix into a new superset matrix is desirable (semantics: pick the snapshot where all matrix settings of the snapshot are present in the continuing job, fail if no such matrix job exists), but not necessary for `continues-from` to be useful.

Post-steps (e.g. for caching) would run at the end of the job that includes that step, and *not* after any `continues-from` jobs.

There are a few related potential benefits to setting up workflow jobs like this:

- Splitting the success/failure report of the build job from the test job, without redoing the build work.
- Sharing of setup work between similar jobs; e.g. the work done to build dependencies can be shared to the test runs testing feature flags pulling in different sets of the dependencies.
- Sharing/deduplicating caches between similar jobs without racing the write; e.g. with the same scenario, only a single cache with all of the dependencies built is stored; if the individual feature set runs each use `actions/cache` then they'd race to write subsets of the proper full cache. If they use separate save keys (but share a restore key) the restore benefit can be achieved at the cost of duplicating the cache.
