### DISCUSSION TITLE
GH Container Registry ignores platform when pulling images?

### DISCUSSION THREAD

**Discussion by MasterOdin** [community/community#21223] [Actions] [answered]
For my company, we are producing cross-architecture docker images, using the following GH action:
```
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

we see that the GH registry is successfully receiving both images and confirmed by inspecting the manifest:
```
$ docker manifest inspect <manifest_hash>
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2201,
         "digest": "sha256:...hash1",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2201,
         "digest": "sha256:...hash2",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

However, on using the image, GH always gives me back the `linux/amd64`, regardless that my base platform is `linux/arm64` and ignoring the `--platform` flag. I see no mention of a limitation of platform on the GH registry docs, nor could I find a thread of someone else having this issue, so I'm not sure if it's something I'm doing wrong (though not sure what as similar stuff works fine on docker registry) or if this is a bug with GH itself.
