### DISCUSSION TITLE
Can I publish multiple branches of a repository on GitHub Pages?

### DISCUSSION THREAD

**Discussion by AnkitaSood** [community/community#21582] [Other Feature Feedback, Questions, & Ideas]
<p>I have already published the master branch of my repo on Github Pages. Can I somehow publish another branch of the same repository so the the url is something like: <a href="http://username.github.io/repositoryname/branch" class="inline-onebox-loading" rel="nofollow noopener">username.github.io/repositoryname/branch</a> ? Or will I have to create another repository instead of a branch to publish it?</p>

**Comment by birdcar** [comment, marked as answer]
<p>Hi <a class="mention" href="/ankitasood">@ankitasood</a>! </p>
<blockquote>
<p>Can I somehow publish another branch of the same repository so the the url is something like: <a href="http://username.github.io/repositoryname/branch" class="inline-onebox-loading" rel="nofollow noopener">username.github.io/repositoryname/branch</a> ? Or will I have to create another repository instead of a branch to publish it?</p>
</blockquote>
<p>GitHub Pages only lets you configure one publishing source for a particular repository. So in this particular case, you’ll need to create a new repository and add the content you’d like to publish with GitHub Pages to that newly created repository.</p>
<p>Does that answer your question? Please let me know if I misunderstood you or you have additional questions. </p>

**Reply by VeraVechy** [reply]
Urgent help...

Please what could be the reason why the css is not reflecting on my site after it has been deployed. And how can I fix it?

**Reply by ghost** [reply]
There could be several reasons for CSS not reflecting on your deployed site. Check if the CSS file paths are correct, clear browser cache, and ensure there are no errors in the CSS code. If the issue persists, inspect the browser's console for error messages, which can help pinpoint the problem.

**Reply by Khush0031** [reply]
try to make all your file name with small letter and with  proper file extention @VeraVechy 



~Don't Forget To Smile😄

**Comment by zabojad** [comment]
<p>Hi there!</p>
<p>It’s a pity it works that way. In my case, I am maintaining an open source project hosted on GitHub. The project has several major versions (few of them still supported and maintained separately on different branches of the repo). It would be very nice if I could have the documentation of each of those versions/branches published separately.</p>
<p>Best,</p>
<p>Thomas</p>

**Comment by Vadorequest** [comment]
<p>Exactly, also it’s doesn’t help when working on documentation because you can’t preview what will be build on the github doc site until it’s merged into master…</p>
<p>What I’d prefer, is to automatically build one doc site for each branch that have a docs/ folder, and use either subdomains or a different domain for docs generated from branches that aren’t the default branch (usually “master”)</p>
<p>Example:</p>
<p><a href="https://unlyed.github.io/next-right-now/" rel="nofollow noopener">https://unlyed.github.io/next-right-now/</a> (“master” branch)</p>
<p><a href="https://unlyed.github.io/next-right-now/" rel="nofollow noopener">https://unlyed-docs.github.io/next-right-now/</a>  (“docs” branch)</p>
<p><a href="https://unlyed.github.io/next-right-now/" rel="nofollow noopener">https://docs.unlyed.github.io/next-right-now/ </a>(“docs” branch)</p>
<p>I think the latest looks the cleanest.</p>
<p>It could be done either automatically for all branches, or through a pattern (<code>v*</code>, for all <code>v1</code>, <code>v2</code> branches and such) or enabled branch by branch.  Pattern allows for automation and would reduce maintainance/configuration.</p>
<p>This would be much more usable.</p>

**Comment by ChildishGiant** [comment]
<p>I’m using github pages for my master branch but <a href="https://www.netlify.com/" rel="nofollow noopener">netlify</a> for the dev branch, as they allow hosting for seperate branches.</p>

**Comment by MichaelHabib** [comment]
<p>Hi,<br>
Github pages does NOT allow a separate website or even section per branch, but I want to bring your attention to a free open source solution that does : <a href="https://antora.org/" rel="nofollow noopener">https://antora.org/</a></p>

**Comment by vokhidovhusan** [comment]
<p><a class="mention" href="/ankitasood">@ankitasood</a> thank you for the question and <a class="mention" href="/nickcannariato">@nickcannariato</a> thank you for the answer</p>

**Comment by djmacloud** [comment]
Maybe this help:

https://medium.com/geekculture/when-youre-working-on-a-static-site-and-github-pages-feels-like-the-perfect-hosting-solution-a41c37f4e326

**Comment by axherrm** [comment]
As a workaround to deploy multiple branches of my angular project, I created the following workflow:

```yaml
name: Continuous Deployment

on:
  push:
    branches:
      - "**"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    outputs:
      json_branches: ${{ steps.generate-matrix.outputs.json_branches }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Matrix
        id: generate-matrix
        run: |
          branches=($(git branch -r | cut -c 3- | sed 's/origin\///g'))
          json_branches=$(printf '%s\n' "${branches[@]}" | jq -R . | jq -s -c .)
          echo "json_branches=${json_branches}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    name: Build
    needs:
      - build_matrix
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.build_matrix.outputs.json_branches) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ strategy.job-index }}
          path: dist/cv/browser/

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - build_matrix
      - build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - run: gh run download ${{ vars.GITHUB_RUN_ID }} --dir branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create public folder
        run: |
          mkdir public
          mv .github/workflows/index.html ./public/index.html
          cd public
          branches=$(echo '${{ needs.build_matrix.outputs.json_branches }}' | jq -r '.[]')
          i=0
          for branch in ${branches}
          do
            mkdir -p -- $branch
            mv ../branches/$i/* ./$branch

            echo "<li><a href=\"./CV/${branch}\">${branch}</a></li>" >> index.html

            i=$((i+1))
          done
          cat ../.github/workflows/index_suffix.html >> index.html
          ls -lR
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

The workflow runs on a push on every branch, which then updates the deployment of all branches.
I'm aware of the poor performance of this, espacially when lots of branches exist, but in my case with mostly only 2-3 branches this is not a big problem.
Also, I'm aware of the problem that one branch build failing means breaking the build of all branches (this could possibly be fixed, but I didn't intend to do it).
In the first job, a json array of all branch names gets created, which then is used for matrix in die build job, so that each branch has its own build job.
The results of the build job are then uploaded as artifact and in the last job downloaded to deploy them to GitHub Pages.  

Again, I'm aware of the poor performance of this, but it enables a pretty workflow overview like this:
![Untitled](https://github.com/community/community/assets/74977055/99fe16fa-30c9-4b24-a382-6dc9c3450f5b)
