### DISCUSSION TITLE
Configure Dependabot to only create PRs for minor or patch updates

### DISCUSSION THREAD

**Discussion by tflight** [community/community#21626] [New to GitHub]
<p>Is it possible to configure Dependabot to only create PRs for updates that satisfy the current manifest? For example if my version constraint in npm or composer is <code>^2.4.1</code> that PRs would be raised for any minor or patch version, but nothing <code>3.0.0</code> or greater?</p>
<p>Ultimately I’d like Dependabot to match what a <code>npm update</code> or <code>composer update</code> command would update instead of raising PRs to newer major versions-- more than just security updates, but less than major releases of dependencies.</p>

**Comment by yamiacat** [comment, marked as answer]
<p>Hi there! :wave: Welcome to the Community!</p>
<p>Yes, this is possible! You can add an ignore option to the  <code>dependabot.yml</code>  configuration file:</p>
<p><a href="https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore" class="onebox" target="_blank">https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore</a></p>
<p>You could specify <code>versions: ["3.x", "4.x" "5.x"]</code> to ensure only updates in “2.x” have PRs raised.</p>

**Comment by valentijnscholten** [comment]
<p>I don’t think this is good solution. If you have 100 dependencies you have to create 100 ignore options just to prevent major updates. As a developer I would like to have 1 parameter option to prevent PRs for major updates in a repository.</p>

**Comment by ioncache** [comment]
<p>Are there any plans to allow restricting all pull requests based on semver?</p>
<p>The old non-github version of dependabot had this built-in.</p>
<p>There are lots of major versions of package updates that will require massive refactoring to fix and having to add an expilict ignore line for each of them is not a viable strategy.</p>

**Comment by agilgur5** [comment]
Per the [current docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore), to ignore all major updates for all deps, can use the `*` syntax with `update-types: ["version-update:semver-major"]`.

For instance:

```yaml
# Use `ignore` to specify dependencies that should not be updated
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # For all deps
      - dependency-name: "*"
        # ignore all major updates
        update-types: ["version-update:semver-major"]
```
