### DISCUSSION TITLE
GitHub Actions failed to deploy my site to GitHub Pages

### DISCUSSION THREAD

**Discussion by Kaleidosium** [community/community#22028] [Other Feature Feedback, Questions, & Ideas]
<p>Tried setting up a GitHub action to build and publish my site automatically but it keeps failing when it’s being deployed by <code>actions/deploy-pages@v1</code>.</p>
<pre><code>Run actions/deploy-pages@v1
  with:
    token: ***
    timeout: 600000
    error_count: 10
    reporting_interval: 1000
Actor: Kaleidosium
Action ID: 1997150545
Artifact URL: https://pipelines.actions.githubusercontent.com/LXLVLVHEBZY1nA5F0U56QUOyGaPLNlFdvuR0lNpbxrcwJk9ptJ/_apis/pipelines/workflows/1997150545/artifacts?api-version=6.0-preview
{"count":1,"value":[{"containerId":9933200,"size":491520,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/LXLVLVHEBZY1nA5F0U56QUOyGaPLNlFdvuR0lNpbxrcwJk9ptJ/_apis/resources/Containers/9933200","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/LXLVLVHEBZY1nA5F0U56QUOyGaPLNlFdvuR0lNpbxrcwJk9ptJ/_apis/pipelines/1/runs/21/artifacts?artifactName=github-pages","expiresOn":"2022-06-15T07:15:18.7363991Z","items":null}]}
Creating deployment with payload:
{
	"artifact_url": "https://pipelines.actions.githubusercontent.com/LXLVLVHEBZY1nA5F0U56QUOyGaPLNlFdvuR0lNpbxrcwJk9ptJ/_apis/pipelines/1/runs/21/artifacts?artifactName=github-pages&amp;%24expand=SignedContent",
	"pages_build_version": "a3ed06873b39b3040e778f31ec73ef6b7f287307",
	"oidc_token": "***"
}
Failed to create deployment for a3ed06873b39b3040e778f31ec73ef6b7f287307.
{"message":"Deployment request failed for a3ed06873b39b3040e778f31ec73ef6b7f287307 due to in progress deployment. Please cancel e86c24fb8e4f6876cf5754a9237d922b2eaa26c3 first or wait for it to complete.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}
Error: Error: Request failed with status code 400
Error: Error: Request failed with status code 400
Sending telemetry for run id 1997150545
</code></pre>
<p>I tried multiple different workflows and all of them failed the same way, I’m not sure what to do now.</p>
<p>I found out about a <a href="https://github.community/t/github-website-deployment-failure/222799">similar issue here</a>. But it doesn’t seem to be relevant in my case.</p>
<p><a href="https://github.com/Kaleidosium/Kaleidosium.github.io" rel="noopener nofollow ugc">GitHub Repo for Context</a>.</p>

**Comment by bugok** [comment]
<p>+1</p>
<p>This happens to me too with my repo as well: <a href="https://github.com/bugok/blog" class="inline-onebox" rel="noopener nofollow ugc">GitHub - bugok/blog: Noam Lerner's blog using hugo</a></p>

**Comment by jGibao** [comment]
<p>Just posted on another topic, i have the exact same issue.</p>

**Comment by yoannchaudet** [comment]
<p>Hello all,</p>
<p>We identified the issue and deployed a fix for it.</p>
<p>Within 1 hour all these deployments should go through as usual. Sorry for the inconvenience. The <a href="https://www.githubstatus.com/incidents/sksd097hm0y5">outage from this morning (which was unrelated)</a> went in our way and delayed the resolution.</p>

**Comment by izahn** [comment]
<p>It looks like this problem is back:</p>
<ul>
<li><a href="https://github.community/t/pages-deploy-wedged-incorrect-request-failed-due-to-in-progress-deployment/234793" class="inline-onebox">Pages deploy wedged (incorrect "request failed due to in progress deployment")</a></li>
<li><a href="https://github.com/actions/deploy-pages/issues/22" class="inline-onebox" rel="noopener nofollow ugc">Workflow cancellation left pages deploy wedged · Issue #22 · actions/deploy-pages · GitHub</a></li>
</ul>
<p>Not sure if this is related to <a href="https://www.githubstatus.com/incidents/z95g34pl8rdm" class="inline-onebox" rel="noopener nofollow ugc">GitHub Status - Incident with GitHub Pages</a> or not.</p>

**Reply by haggis78** [reply]
This seems to be a recurring problem. It happened to me in mid December 2022 and again several times today.

**Reply by yoannchaudet** [reply]
The [status page](https://www.githubstatus.com/) is the best source of information for active outages. As a matter of fact there is one now that the teams are working on and that is impacting Pages deployments.

**Comment by fk73** [comment]
I do have the same issues from today for all my repositories on 
https://github.ibm.com
Is there anything I need to change? I have not changed anything in my travis.yml

```
sudo: required
language: node_js
node_js: '12'
dist: xenial

notifications:
  email: false

stages:
  - stage: test
  - stage: deploy
    if: branch = master

jobs:
  include:
    # Run tests.
    - stage: test
      before_install:
        - nvm install
      install:
        - HUSKY_SKIP_INSTALL=1 npm install
      script:
        - npm test

    # Semantic release tagging.
    - stage: deploy
      env:
        - JOB_NAME="Tag release"
        - GITHUB_URL="https://github.ibm.com"
        - GITHUB_PREFIX="/api/v3"
      before_deploy:
        - nvm install
        - HUSKY_SKIP_INSTALL=1 npm install
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          branch: master
          tags: false

    # Publish GitHub Pages
    - env:
        - JOB_NAME="Publish GitHub Pages"
      before_deploy:
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        github_url: github.ibm.com
        local_dir: build
        verbose: true
        on:
          branch: master
          tags: false
```


Thanks for your support!
