### DISCUSSION TITLE
Can you ignore files/folders when making a Repo from a template?

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#22183] [New to GitHub]
<p>I set up a GitHub Repository as a template so that other people can use it to create documentation or similar.</p>
<p>That said would I like to make it, so that when people click the “Use this template” button, that the copied Repo won’t contain certain files or folders like the README.md.</p>
<p>Is there a way to set a file or similar to define files/folders that should not be copied from the template repository?</p>
<p>(If not, then I hope it could be considered as a feature in the future.)</p>

**Comment by AndreaGriffiths11** [comment, marked as answer]
<p>Hi <a class="mention" href="/andre601">@andre601</a>,</p>
<p>Thank you for being here. At the moment there isn’t a way to ignore files when creating from repository templates. Ideally there will be an implemented  <code>dot ignore</code> file for repository templates, and I’ve passed that suggestion to the team for consideration. Although I can’t guarantee when or if this feature would be implemented please know your feedback is in the right hands.</p>

**Reply by johnpetersjr** [reply]
any update on this?

**Reply by regg00** [reply]
+1, any updates?

**Reply by owl12358** [reply]
+1 please

**Reply by Dusty-Gannon** [reply]
+1

**Reply by ilya-korotya** [reply]
+1

**Reply by anantakumarghosh** [reply]
any update?

**Reply by alexwhamilton** [reply]
+1

**Reply by andrewvaughan** [reply]
+1

**Reply by HealthyPear** [reply]
+1

**Reply by jimbrig** [reply]
+1

**Reply by katapultcloud** [reply]
+1

**Reply by erexer** [reply]
+1

**Reply by TWiStErRob** [reply]
+1

**Reply by samtrion** [reply]
@AndreaGriffiths11 Is there possibly an update on this?

**Reply by workflou** [reply]
+1

**Reply by JetVolcano** [reply]
+1

**Reply by sirbully** [reply]
+1

**Reply by alexvanderberkel** [reply]
+1

**Reply by hhoweson** [reply]
+1

**Reply by texeltexel2009** [reply]
+1

**Comment by schroef** [comment]
<p>So excluding files or folder being added to the zip also isn’t possible then?</p>
<p>I got this repo which has template files, these are added in the zip when the repo is downloaded. I would like to exclude those.</p>
<p><a href="https://github.com/schroef/Extra-Image-List" rel="nofollow noopener">https://github.com/schroef/Extra-Image-List</a></p>

**Comment by jonnitto** [comment]
<p>I hope this feature will be included soon…</p>

**Comment by jamesratcliffe** [comment]
<p>+1 for this! Specifically, when making a repository from a template, I don’t want to include package manager lockfiles.</p>

**Comment by vincerubinetti** [comment]
<p>It’d probably make sense to put it in <code>/.github</code> because templates are a github-specific concept. Maybe something like <code>/.github/.template-ignore</code>.</p>
<p>Just to add to how useful this would be… I’m making a website template, and it’d be great to only give users the files they really need. There’s a test bed page for my own development purposes that they don’t need. And there’s a bunch of documentation that should stay in the same repo (because it’s for the template), but doesn’t need to be duplicated to every clone of the template.</p>

**Reply by andrewvaughan** [reply]
This sounds like a great solution.

**Reply by JetVolcano** [reply]
+1

**Comment by Andre601** [comment]
<p>I think having it as a dot-file in the root, similar to .gitignore would make a bit more sense, in case that any other git repo-site (bitbucket, gitlab, gittea, etc) would want to adobt this idea in the future. I for myself see a new potential feature alongside the .gitignore file that could help improve any future git repositories…</p>
<p>But that’s just my thinking.</p>

**Reply by andrewvaughan** [reply]
Possibly - however, that assumes that each provider handles templates the same way, which can't be guaranteed. For that reason, at least as an initial iteration, it makes sense to live in the `.github` folder as it is, specifically, a `.github` template tool.

That said, I'm replying to a comment that was made 3 years ago, so I'm probably yelling my opinion into a hole in the ground :)

**Comment by jackkoenig** [comment]
<p>There is a way of solving this (somewhat manually) by using workflows that trigger <code>on: create</code> or on the first push. When the user creates a repo from the template, the workflow can edit and delete files at will and then push a commit. A good example is this repository: <a href="https://github.com/JetBrains/intellij-platform-plugin-template" rel="noopener nofollow ugc">https://github.com/JetBrains/intellij-platform-plugin-template</a><br>
with the workflow: <a href="https://github.com/JetBrains/intellij-platform-plugin-template/blob/deb171483598ee8a5d7621154db880e87b4db4ef/.github/workflows/template-cleanup.yml" rel="noopener nofollow ugc">https://github.com/JetBrains/intellij-platform-plugin-template/blob/deb171483598ee8a5d7621154db880e87b4db4ef/.github/workflows/template-cleanup.yml</a></p>
<p>This approach is pretty nice, but has 2 major cons:</p>
<ol>
<li>It’s not interactive. It would be nice if the user could set fields like “organization name” instead of forcing projects to guess from the Github org.</li>
<li>It has a delay. It takes a minute or two for the workflow to push the commit, so instructions on templates that use this approach are basically like “please wait a moment and refresh the page until it’s done!”</li>
</ol>
<p><a class="mention" href="/AndreaGriffiths11">@AndreaGriffiths11</a> I’m a bit late here but if there is some internal ticket on this feature, it would be <em>wonderful</em> if it went beyond a mere “ignore” file and instead had some interactivity and integration with Github Actions and workflows.</p>

**Comment by fhinkel** [comment]
Any updates? We'd love to have this feature.

**Comment by corykinney** [comment]
I'd also be very interested in this feature. I'd like to have workflow in the template repository that can automatically keep it up-to-date with submodules, but I don't want the generated repositories to include the workflow.

**Comment by hoishing** [comment]
+1, ignoring files such as how to use the template is reasonable. Something like `.template-ignore` with glob patterns similar to gitignore would be great.

**Comment by vincerubinetti** [comment]
As a solution for now, I'm using GitHub Actions to "clean" the repo for the user when they generate it:

```yaml
name: first-time-setup
run-name: first time setup of repo

on:
  # run when branch created (repo generated from template)
  create:

# only keep latest run of this workflow
concurrency:
  group: first-time-setup
  cancel-in-progress: true

jobs:
  first-time-setup:
    # ensure run only once, when repo generated
    if: github.run_number == 1

    runs-on: ubuntu-latest

    steps:
      # get main branch repo contents
      - name: Checkout code
        uses: actions/checkout@v3

      # remove files not needed for user instance of template
      - name: Remove unneeded files
        run: rm -f README.md demo.md testbed.md

      # personalize readme for user
      - name: Init readme
        run: |
          echo "
   
          Personalized readme text. Hello ${{ github.repository_owner }}!

          " > README.md

      # save changed files
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Setup repo"
```

This actually turns out to be a nicer solution because I can do more than just exclude certain files. I can customize files however I want based on user info like user/org name, repo name, etc. with the [`env` and `github` contexts](https://docs.github.com/en/actions/learn-github-actions/contexts).

However, this only works when "generating" (i.e. "Use this template"), and not when forking, because when you fork, GitHub Actions is not enabled yet, and there is no workflow trigger for when Actions is first enabled. You could perhaps call the above workflow from some other workflow that you know will run at some point, like a "build live site" workflow.

**Reply by anujonthemove** [reply]
This is brilliant but it may require adding permissions to enable the github actions bot to commit the changes, and also adding the relevant access tokens. 


```yaml
name: first-time-setup
run-name: first time setup of repo

on:
  # run when branch created (repo generated from template)
  create:

# only keep latest run of this workflow
concurrency:
  group: first-time-setup
  cancel-in-progress: true

# ADDED THIS CHANGE
permissions: 
  actions: write
  checks: write
  contents: write


jobs:
  first-time-setup:
    # ensure run only once, when repo generated
    if: github.run_number == 1

    runs-on: ubuntu-latest

    steps:
      # get main branch repo contents
      - name: Checkout code
        uses: actions/checkout@v3
        # ADDED THIS CHANGE
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # remove files not needed for user instance of template
      - name: Remove unneeded files
        run: rm -f README.md demo.md testbed.md

      # personalize readme for user
      - name: Init readme
        run: |
          echo "
   
          Personalized readme text. Hello ${{ github.repository_owner }}!

          " > README.md

      # save changed files
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Setup repo"
      
       # ADDED THIS CHANGE
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


```
