### DISCUSSION TITLE
prevent `Compare & pull request` buttun

### DISCUSSION THREAD

**Discussion by ygj6** [community/community#22526] [New to GitHub]
<p>Background for my question: I have two branches: master and <code>feature-1</code>. I will never  merge code from <code>feature-1</code> to master.</p>
<p>My question: When I push code to <code>feature-1</code>, the <code>Compare &amp; pull request</code> button will pop up. How can I prevent this button from popping up?</p>

**Comment by logankilpatrick** [comment, marked as answer]
<p>Hey <a class="mention" href="/ygj6">@ygj6</a>, welcome to the GitHub Community Forum! As of the time of this writing, the feature is enabled by default and cannot be turned off. I hear where you are coming from on this and I suggest submitting your feedback here: <a href="https://support.github.com/contact/feedback" rel="nofollow noopener">https://support.github.com/contact/feedback</a></p>
<p>Thanks for being a part of the community! </p>

**Comment by ygj6** [comment]
<p>Ok, Thanks for your reply.</p>

**Comment by ehelin** [comment]
<p>Will this be enabled anytime soon?  The alert takes up a huge amount of space and my branches are long lived.</p>

**Comment by dwrolvink** [comment]
<p>It is mind boggling that there is no way to click this away.<br>
I’d love to vote somewhere, but for each of us to create a new ticket would be a bit of redundant right?</p>

**Comment by liuliangsir** [comment]
+1

**Comment by port19x** [comment]
Very annoying indeed.

**Comment by MohsenSameti** [comment]
+1

**Comment by antoniodourado** [comment]
+1

**Comment by mellm0** [comment]
+1

**Comment by gosh89** [comment]
I also annoyed with this, as a work around create a pull request and close it :). It's gone

**Comment by akashdip2001** [comment]
To prevent the "Compare & pull request" button from popping up when you push code to the `feature-1` branch, follow these steps:

1. **Direct Push:**
   - Instead of using the GitHub web interface to push your changes, push directly from the command line or your Git client using:
     ```
     git push origin feature-1
     ```
   This way, GitHub won't automatically create a pull request.

2. **Repository Settings:**
   - Alternatively, if you still want to use the GitHub web interface, go to your repository settings.
   - Navigate to the "Branches" section.
   - In the "Branch protection rules," add a rule for the `feature-1` branch, and enable the option to "Require pull request before merging."

By choosing either of these methods, you can prevent the automatic creation of pull requests when pushing code to the `feature-1` branch.

## Profile
![Profile Image](https://thumbnails.odycdn.com/optimize/s:200:0/quality:95/plain/https://thumbs.odycdn.com/bf58cf4d7ec52c62f02c52e16f150a5b.webp)
**AKASHDIP MAHAPATRA**
"everything is physics bro"  
E=mc²

|[Subscribe on YouTube](https://www.youtube.com/channel/UCxvmp634YDc41xCWOdvWqoQ?sub_confirmation=1) |
|----  |

**Comment by cha0s** [comment]
My branch is an `--orphan`. Pull requests don't even make sense for orphan branches. This is a **bug**.

**Comment by msedek** [comment]
+1

**Comment by Faremir** [comment]
+1

**Comment by norrisjeremy** [comment]
+100000

Ridiculous that this isn't resolved.

**Comment by alexander-schranz** [comment]
It annoyed me a lot so I used Firefox Custom Styles extension to hide some branch suggestions via CSS:

```css
@-moz-document url-prefix("https://github.com/sulu/sulu") {
    [class^="Flash__StyledFlash"]:has([href^="/sulu/sulu/compare/1."]),
    [class^="Flash__StyledFlash"]:has([href^="/sulu/sulu/compare/2."]),
    [class^="Flash__StyledFlash"]:has([href^="/sulu/sulu/compare/3."]),
    [class^="Flash__StyledFlash"]:has([href^="/sulu/sulu/compare/4."]),
    [class^="Flash__StyledFlash"]:has([href^="/sulu/sulu/compare/5."]) {
        display: none;
    }
}
```
