### DISCUSSION TITLE
Release checksums on GitHub

### DISCUSSION THREAD

**Discussion by Ghepardo** [community/community#23512] [New to GitHub] [answered]
<p>Hi, how can I view the SHA256 checksum for a release on GitHub?  I need such checksums for new easyconfig files in EasyBuild.  Can’t find checksums anywhere!  Thanks.</p>

**Comment by lee-dohm** [comment]
<p>Hello and welcome to the community <a class="mention" href="/ghepardo">@Ghepardo</a>.</p>
<p>GitHub doesn’t have built-in support for checksums in Releases. The author of the release would have to include that information in the release notes.</p>
<p>Let us know if you have more questions.</p>

**Reply by ssbarnea** [reply]
Considering that these archives are created by Github itself without use any user controllable Github action, sending the dead cat on the user side might not be the best approach.

If these archives would have being uploaded by our workflows, It could have made sense to say that we are supposed to add the checksums to the release notes.

Still, even in 2022, pressing the "release" button creates the effective release on github before even a workflow is triggered, when in fact the effective release should have being the result of a successful work run triggered by the release button from the user interface.

Yes, I know that I can make release pipelines that can be user triggered, but I cannot disable the release button from releases page, so nope, that is not ok as I cannot expect people not to press the button that bypassed the pipeline.

**Reply by AlexProgrammerDE** [reply]
This answer is incorrect. You do get at least a md5 (sadly not sha256) hash with your downloaded files via the `content-md5` header. Here is my full answer: https://github.com/orgs/community/discussions/23512#discussioncomment-7856465

**Reply by drojf** [reply]
Looks like things have changed again, and the answer is now correct as the md5 is no longer included in the header, see https://github.com/orgs/community/discussions/23512#discussioncomment-10013377 (I realize this is posted by the person I am replying to, but just to save you the extra click)

**Reply by wangzuo** [reply]
https://github.com/wangzuo/action-release-checksums I created this github action for generating checksums in github release. It will automatically generate a checksums.txt for all assets uploaded to current tagged release.

**Comment by Ghepardo** [comment]
<p>Hi, thanks and noted, <span class="mention">@lee_dohm</span>.</p>
<p>Given that GitHub is a software repository, it is very strange that it does not enforce checksums for releases.  Otherwise, how is any consumer of the software to have confidence that their copy of it has not been tampered with or damaged?  This is a basic requirement for any respectable repository.</p>

**Comment by lee-dohm** [comment]
<aside class="quote no-group" data-username="Ghepardo" data-post="5" data-topic="137764">
<div class="title">
<div class="quote-controls"></div>
 Ghepardo:</div>
<blockquote>
<p>Otherwise, how is any consumer of the software to have confidence that their copy of it has not been tampered with or damaged?</p>
</blockquote>
</aside>
<p>Traditional checksum systems don’t give any real evidence that the file downloaded has not been tampered with or damaged. It only signifies that the person who was able to modify two separate files on the same server was able to make them agree. There is no evidence available to the person downloading those two files that the person who last modified them is someone they trust. For example, <a href="https://micahflee.com/2016/02/backdoored-linux-mint-and-the-perils-of-checksums/">Linux Mint was compromised in exactly this way</a>.</p>
<p>In order to offer evidence that a file has not been tampered with or damaged, it would require a digital certificate as part of the file itself, signed with a key that can be verified by a trusted mechanism. The GitHub releases system works well with these kinds of protocols. When using one of these protocols, checksums are superfluous.</p>

**Comment by Ghepardo** [comment]
<p>Thanks <a class="mention" href="/lee-dohm">@lee-dohm</a> for your excellent observations, from which I have learned much.</p>

**Comment by Daniel-Chin** [comment]
<p>In my case, an installer file (70MB) takes forever to download from Amazon S3 (20KB/s) and it always times out before completion. I had to download it from other sources, but I want to verify that the downloaded file is identical to the release on Github.</p>
<p>Providing a hash of the release files would be valuable to many users.</p>

**Comment by melMass** [comment]
<p>SHA256 is pretty solid and definitely not easily reproducible!<br>
But besides security concerns, this is still used by many package managers for instance (Conda, Conan, Brew to name a few) so it seems natural to have it generated on upload, is this considered?</p>
<p>Thanks</p>

**Comment by MartinX3** [comment]
<p>I also miss checksums.</p>
<p>If I would make one myself, maybe the file got corrupted while downloading it on my machine.<br>
If I want to use the github API in an application, I need to verify, that the downloaded file is 1:1 the same on the github server.</p>

**Comment by chapati** [comment]
<p>While there are still many attacks when sums are just published on the same site with the release, sums still do their job to prove that:</p>
<ul>
<li>there was no man in the middle</li>
<li>file was not damaged due to software/connectivity issues</li>
</ul>
<p>Moreover many package managers REQUIRE AND ENFORCE presence of checksums. If you want to download something in your automated builds you MUST specify checksum. Ignoring this just makes github and its flows extremely unfriendly to software engineers. Making this question as solved just show that github pays little attention to its users’ problems.</p>

**Comment by vertigo220** [comment]
<p>I agree that checksums should be standard on GitHub releases, and there are multiple reasons to do so as well as ways to deal with the security weaknesses of doing so. However, I don’t think commenting here is going to do anything to encourage that or even likely be seen by anyone who can push to make that happen. I may be wrong, but I think the GitHub feedback is the place to do so, so I created an <a href="https://github.com/github/feedback/discussions/16426" rel="noopener nofollow ugc">issue there</a>. Everyone who agrees checksums are important and should be added should +1 that issue.</p>

**Comment by fxstein** [comment]
This can be accomplished by Github Actions.

Here is a primitive release action I have created for a project that calculated the sha256 when a release is published:

```
# release.yml - Automatic creation of sha256 for release tarball

name: goprox release action
run-name: ${{ github.actor }} is publishing release ${{ github.ref_name }}
on:
  release:
    types: [published]
jobs:
  sha256:
    name: sha256
    runs-on: ubuntu-latest
    steps:
      - name: Tarball url
        run: echo "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
      - name: Create tarball sha256 
        run: curl -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz" | shasum -a 256 | cut -d " " -f 1
```

The one thing I am still looking for is a simple way to write that SHA 256 back into the release notes

**Comment by brsolomon-deloitte** [comment]
> The one thing I am still looking for is a simple way to write that SHA 256 back into the release notes

Could potentially use the [Releases API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28) for this.

**Comment by smallstepman** [comment]
I expected this to be part of the Releases API

**Reply by smallstepman** [reply]
related to https://github.com/community/community/discussions/16426 which also remains unanswered

**Comment by wangzuo** [comment]
https://github.com/wangzuo/action-release-checksums I created this github action for generating checksums in github release. It will automatically generate a `checksums.txt` for all assets uploaded to current tagged release.

```yaml
name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
      - name: Checksums
        uses: wangzuo/action-release-checksums@v1
```
