### DISCUSSION TITLE
What permission does a Github Action need to call graphql enablePullRequestAutoMerge?

### DISCUSSION THREAD

**Discussion by jaqx0r** [community/community#24686] [Apps, API and Webhooks]
<p>I’m setting permissions on my workflows, and this is an OK experience for REST API as the permissions required are <em>mostly</em> documented there.  However the GraphQL API documentation doesn’t describe the permissions required for the calls.</p>
<p>I am trying to set permissions for a workflow that enables automerge, which is via the GraphQL API: <a href="https://docs.github.com/en/graphql/reference/mutations#enablepullrequestautomerge" rel="noopener nofollow ugc">https://docs.github.com/en/graphql/reference/mutations#enablepullrequestautomerge</a> though there are many similar, and the few that document the requirements on the token ask for full ‘repo’ access.</p>
<p>I’m not convinced that the token needs ‘repo’ ; perhaps it’s just pull_request: write?  But I can’t tell without experimenting with the workflow config and retriggering them, and I’m not keen to do that – does anyone know the answer, and/or know where the GraphQL permissions are documented?</p>
<p>Further to that; is there a mapping of the permissions documented here: <a href="https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token" class="inline-onebox" rel="noopener nofollow ugc">Authentication in a workflow - GitHub Docs</a> to the token scopes you choose when Creating a Personal Access Token?</p>
<p>(I’d link to the last document, but this tool won’t let me post more than two URLs.)</p>

**Comment by jsoref** [comment]
<p>I filed a bug in response to a similar <a href="https://github.community/t/allow-the-github-token-to-also-have-rights-for-converting-prs-to-draft-or-vice-versa/194555">item</a>:</p><aside class="onebox githubissue" data-onebox-src="https://github.com/github/docs/issues/8925">
  <header class="source">

      <a href="https://github.com/github/docs/issues/8925" target="_blank" rel="noopener">github.com/github/docs</a>
  </header>

  <article class="onebox-body">
    <div class="github-row">
  <div class="github-icon-container" title="Issue">
	  <svg width="60" height="60" class="github-icon" viewbox="0 0 14 16" aria-hidden="true"><path d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg>
  </div>

  <div class="github-info-container">
    <h4>
      <a href="https://github.com/github/docs/issues/8925" target="_blank" rel="noopener">GraphQL API content does not appear to explain required permissions</a>
    </h4>

    <div class="github-info">
      <div class="date">
        opened <span class="discourse-local-date" data-format="ll" data-date="2021-08-10" data-time="03:33:30" data-timezone="UTC">03:33AM - 10 Aug 21 UTC</span>
      </div>


      <div class="user">
        <a href="https://github.com/jsoref" target="_blank" rel="noopener">
          <img alt="jsoref" src="https://user-images.githubusercontent.com/2119212/181086049-2fce8cd4-5726-470f-b743-39783450b556.png" class="onebox-avatar-inline" width="20" height="20">
          jsoref
        </a>
      </div>
    </div>

    <div class="labels">
        <span style="display:inline-block;margin-top:2px;background-color: #B8B8B8;padding: 2px;border-radius: 4px;color: #fff;margin-left: 3px;">
          content
        </span>
    </div>
  </div>
</div>

  <div class="github-row">
    <p class="github-body-container">### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's Co<span class="show-more-container"><a href="" rel="noopener" class="show-more">…</a></span><span class="excerpt hidden">de of Conduct.

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql

### What part(s) of the article would you like to see updated?

#authenticating-with-graphql

The section that talks about authentication really doesn't help understand what permissions one needs to do things

A [forum post](
https://github.community/t/allow-the-github-token-to-also-have-rights-for-converting-prs-to-draft-or-vice-versa/194555
) asked about converting a PR to/from draft.


### Additional information


The v3 API has a long page that makes it possible to try to figure out what permissions one might need:
https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-pull-requests

But, I really can't find any equivalent for the v4 api.

For reference, here's the mutation in question:
https://docs.github.com/en/graphql/reference/mutations#convertpullrequesttodraft</span></p>
  </div>

  </article>

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>

**Comment by sharwell** [comment, marked as answer]
<p>With some trial-and-error in a test repository, I found the minimum permissions to execute the <code>enablePullRequestAutoMerge</code> mutation are:</p>
<pre><code class="lang-auto">permissions:
  contents: write
</code></pre>

**Reply by kyanny** [reply]
As of 2024-05-24, both `contents: write` and `pull-requests: write` permissions are required.

Minimum working example:

```yaml
name: enable PR auto-merge

on:
  pull_request:
    types:
      - opened

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    # https://github.com/orgs/community/discussions/24686
    permissions: 
      contents: write
      pull-requests: write

    steps:
      - run: |
          gh api graphql -f pullRequestId="${{ github.event.pull_request.node_id }}" -f query='
          mutation EnablePullRequestAutoMerge($pullRequestId: ID!) {
            enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId}) {
              clientMutationId
            }
          }
          '
        env:
          GH_TOKEN: ${{ github.token }}
```
