### DISCUSSION TITLE
Non secret variable for Environments

### DISCUSSION THREAD

**Discussion by sahalsaad** [community/community#24988] [Actions]
<p>Hi,</p>
<p>I would like to have option to set non secret variable for <a href="https://docs.github.com/en/free-pro-team@latest/actions/reference/environments" rel="noopener nofollow ugc">Environments</a>. So that I can easily set through the UI and use it in the workflow. Something similar like <strong>Variable Group</strong> in ADO where we can have secret and non secret variable.</p>
<p>If this does not make sense I would like to know how anyone else set variable based on environment?</p>
<p>There are couple of workaround to this issue:</p>
<ol>
<li>Just set it in secret.(weird)</li>
<li>Set non secret env within the workflow</li>
</ol>
<p>Thank you.</p>

**Comment by GregoireW** [comment]
<p>If it is not a secret, you may store this directly to the repository.</p>
<p>For instance, if you have a <code>test</code> and <code>prod</code> environment, you may create <code>.github/test.env</code> and <code>.github/prod.env</code> file  with some environment definition:</p>
<pre><code class="lang-auto">key=value
foo=bar
</code></pre>
<p>then you can use a step like:</p>
<pre><code class="lang-auto">      - name: load env
        id: loaded-env
        env:
          the_env: xxxxxxxx
        run: |
          while IFS= read -r line; do
            echo "::set-output name=${line/=/::}"
          done &lt; .github/$the_env.env
</code></pre>
<p>you can reference what you loaded in following step with <code>${{ steps.loaded-env.outputs.foo }}</code></p>

**Comment by airtower-luna** [comment, marked as answer]
<p>Depending on the desired use of the variables the environment file could also be appended to <code>$GITHUB_ENV</code>, with much simpler code:</p>
<pre><code class="lang-yaml">      - name: load env
        env:
          ENV_NAME: xyz
        run: |
          cat ".github/${ENV_NAME}.env" &gt;&gt;$GITHUB_ENV
</code></pre>
<p>The trickiest thing might be to define <code>ENV_NAME</code>. In case of doubt you can use a secret for that. :wink:</p>

**Comment by sahalsaad** [comment]
<p>Thank you <a class="mention" href="/gregoirew">@GregoireW</a> and <a class="mention" href="/airtower-luna">@airtower-luna</a>! Both work for me, but I mark env way as solution since it much simpler and good enough for my use case. Really appreciate it.</p>

**Comment by mcarans** [comment]
<p>In my case, I have just one non secret, so it is overkill to generate multiple env files in the repo, one of which is selected based upon another secret. This should be something in the GitHub UI in my opinion.</p>

**Comment by AllanOricil** [comment]
I would like to have env variables that dont require me to add a new commit to my repository.

**Comment by Omzig** [comment]
The only secret that i need is for the passwords and keys. Not for my app folder path location. My config has a ton of variables that are NOT secret. 

![image](https://user-images.githubusercontent.com/1987296/182248892-36f37dea-e520-4aa6-81ce-58278ceac013.png)

**Reply by juliandunn** [reply]
:wave: Hello. I'm director of product for Actions and we are planning on working on this feature to separate variables and secrets for this reason.

One thing we are trying to determine is whether we should:

Option 1: Completely separate secrets and variables. That is, you would refer to variables using a syntax like `${{ vars.FOO }}` and secrets using `${{ secrets.FOO }}`, making it explicit which is which.

OR

Option 2: Have `${{vars.FOO}}` represent both secret and non-secret variables, and use a mechanism (e.g. in the UI) to flag which variables are truly secret. Over time, we would deprecate the current `${{secrets.FOO}}` syntax.

My working hypothesis is that Option 1 is the preferred option, as it makes the secrecy more explicit, but I would like to hear if you (or anyone else on this thread) has a preference for Option 2 instead -- and why.

(BTW, as part of this feature, we do plan to add an optional description field to both secrets and variables so people can put a little metadata there to describe what the item is for.)

**Reply by mitre-tm** [reply]
I prefer Option 1, which is backward compatible. Regarding scope, non-secrets should be global, secrets should be passed explicitly to reusable workflows.

**Reply by mcarans** [reply]
I prefer Option 1

**Reply by lgiuliani80** [reply]
I prefer Option 1

**Reply by flobernd** [reply]
@juliandunn Nice to hear that! Was just experimenting with environments and this feature would help a lot. I prefer option 1 as well.

@mitre-tm There was a reason why `env` is not automatically propagated to callable workflows, if I remember correctly. It was written down "somewhere" in the documentation. However, for secrets there is the `inherit` keyword, which would be really handy to pass environment variables to callable workflow inputs as well. It's unrelated to the "environment variables" feature, but maybe you can consider it as a feature request @juliandunn ?

**Reply by AllanOricil** [reply]
Option 1

**Reply by grelland** [reply]
Option 1. Sorely needed feature 👍

**Reply by Omzig** [reply]
@juliandunn ,  Funny thing, i am used to Azure, and azure uses a little lock on the environment variable like Option 2. Then they are all kept in the same place with a little lock button.

**Reply by TechDawg270** [reply]
Option 1. Will be a great feature to have

**Reply by asgerjensen** [reply]
Option 1

**Reply by btrajkovski-mms** [reply]
Would prefer option #1, but both options are fine as long as we can get non-secret variables in github actions pipeline. IMO this is a very valuable feature that is missing currently in Github Actions compared to other CI pipelines.

**Reply by chaduhduh** [reply]
Is there anywhere I can track the progress of this feature? Coming from Gitlab CI/CD and found the capability of environment variables to be useful. You should be able to define them for all environments (repository level?) or a specific environment.

**Reply by juliandunn** [reply]
@chaduhduh Yup: https://github.com/github/roadmap/issues/575

**Reply by fitzoh** [reply]
+1 for option 1

**Reply by sahalsaad** [reply]
Since GitHub is one of Microsoft's products. I think option 2 will be better for the transition from ADO.

**Reply by ThomasReyskens** [reply]
+1 for option 1. Is there an update on this topic?

**Comment by trudeaua21** [comment]
@ThomasReyskens 

I think this may have finally been added? I was looking through this thread literally yesterday trying to find a workaround, and today I saw this in my environments:

<img width="808" alt="Screen Shot 2023-01-10 at 12 05 20 PM" src="https://user-images.githubusercontent.com/36064197/211616700-d10db816-8535-4cc8-9e55-6a7f2f3d4bf1.png">

So it seems like the feature is finally around!

**Reply by AllanOricil** [reply]
cool, let's break it :D

**Reply by juliandunn** [reply]
It's true! https://github.blog/changelog/2023-01-10-github-actions-support-for-configuration-variables-in-workflows/

**Reply by ThomasReyskens** [reply]
nice! should've asked earlier 😄

**Comment by AllanOricil** [comment]
@juliandunn It does not seem to work. Why is the variable in the caller workflow receiving `''` instead of true/false? It seems that I have to use the `vars` context directly in the reusable workflow template. It is kind confusing because when passing secrets from the caller to the reusable workflow I have to explicitly tell the caller which secrets I want to share.

![image](https://user-images.githubusercontent.com/55927613/211822091-f14a3f00-0694-461b-9a30-d5adb4a2545e.png)


All the variables that are now using the `vars` context were previously using the `secrets` context.



caller workflow
````yml
name: Build on Pull Request

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - main

  workflow_dispatch:

jobs:
    
  build:
    name: Build
    uses: VodafoneIS/salesforce-github-reusable-workflows/.github/workflows/build-on-pr.yml@v2.x
    with:
      ENVIRONMENTS: '["vlocdevbas", "vlocdevpro"]'
      BASE_REF: origin/main
      SF_ORG_ALIAS: ${{ vars.SF_ORG_ALIAS }}
      SF_INSTANCE_URL: ${{ vars.SF_INSTANCE_URL }}
      SF_REPORT_APEX_CODE_COVERAGE: ${{ vars.SF_REPORT_APEX_CODE_COVERAGE }}
      ENV_TYPE: ${{ vars.ENV_TYPE }}
    secrets:
      SF_SFDX_AUTH_URL: ${{ secrets.SF_SFDX_AUTH_URL }}
      CODECOV_COVERAGE_UPLOAD_TOKEN: ${{ secrets.CODECOV_COVERAGE_UPLOAD_TOKEN }}
````

reusable workflow
````yml
name: Build on Pull Request Workflow

on:
  workflow_call:
    inputs:
      ENVIRONMENTS:
        type: string
        required: true
      BASE_REF:
        type: string
        required: true
      SF_ORG_ALIAS:
        type: string
        required: true
      SF_INSTANCE_URL:
        type: string
        required: true
      SF_REPORT_APEX_CODE_COVERAGE:
        type: boolean
        required: false
      ENV_TYPE:
        type: string
        required: true
    secrets:
      SF_SFDX_AUTH_URL:
        required: true
      CODECOV_COVERAGE_UPLOAD_TOKEN:
        required: false

permissions:
  contents: write
  packages: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate-metadata-changes:
    name: Validate Metadata Changes
    strategy:
      matrix:
        environment: ${{ fromJSON(inputs.ENVIRONMENTS) }}
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vodafoneis/salesforce-build-image:v1.2.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Print sfdx version
        run: sfdx version --verbose --json

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Git User
        uses: fregante/setup-git-user@v1

      - name: Authenticate
        run: /scripts/authenticate.sh
        shell: bash
        env:
          SF_ORG_ALIAS: ${{ inputs.SF_ORG_ALIAS }}
          SF_INSTANCE_URL: ${{ inputs.SF_INSTANCE_URL }}
          SF_SFDX_AUTH_URL: ${{ secrets.SF_SFDX_AUTH_URL }}

      - name: Setup Environment Variables
        run: /scripts/setup_environment_variables.sh -o ${{ inputs.SF_ORG_ALIAS }} -b ${{ inputs.BASE_REF }}
        env:
          ENV: ${{ secrets.ENV_TYPE }}

      - name: Generate Package.xml
        run: /scripts/create_mdapi.sh -t ${{ inputs.BASE_REF }} -o ${{ inputs.SF_ORG_ALIAS }}

      - name: Enqueue Deploy Validation Job
        run: /scripts/deploy_and_verify.sh -o ${{ inputs.SF_ORG_ALIAS }} -c ${{ inputs.SF_REPORT_APEX_CODE_COVERAGE }}

      - name: Check Deploy Validation Job Status
        run: /scripts/fetch_deploy_status.sh -o ${{ inputs.SF_ORG_ALIAS }} -c ${{ inputs.SF_REPORT_APEX_CODE_COVERAGE }}

      - name: Parse Validation Errors
        id: parse_validation_errors
        if: ${{ failure() }}
        run: |
          errors=$(/scripts/parse_metadata_deploy_validation_errors.sh -o ${{ inputs.SF_ORG_ALIAS }})
          echo $errors
          echo "::set-output name=ERRORS::$errors"

      - name: Add Errors to Pull Request
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ failure() && steps.parse_validation_errors.outputs.ERRORS != '' }}
        with:
          message: |
            ${{ steps.parse_validation_errors.outputs.ERRORS }}
          pr_number: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix Apex Code Coverage
        uses: VodafoneIS/salesforce-fix-code-coverage-reports-action@main
        if: ${{ inputs.SF_REPORT_APEX_CODE_COVERAGE == 'true' }}
        continue-on-error: true
        with:
          code-coverage-report-path: ./dist/${{ inputs.SF_ORG_ALIAS }}/tests/coverage/coverage.json
          code-coverage-report-type: APEX
          output-directory: ./dist/${{ inputs.SF_ORG_ALIAS }}/tests/coverage

      - name: Upload Apex Code Coverage
        uses: codecov/codecov-action@v3
        if: ${{ inputs.SF_REPORT_APEX_CODE_COVERAGE == 'true' }}
        continue-on-error: true
        with:
          flags: APEX
          token: ${{ secrets.CODECOV_COVERAGE_UPLOAD_TOKEN }}
          files: ./dist/${{ inputs.SF_ORG_ALIAS }}/tests/coverage/fixed-coverage.json

      - name: Cancel Running Validation
        if: ${{ cancelled() || failure() }}
        continue-on-error: true
        run: /scripts/cancel_deploy.sh -o ${{ inputs.SF_ORG_ALIAS }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Distribution
          path: dist

  lwc-code-converage:
    name: LWC Code Coverage
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vodafoneis/salesforce-build-image:v1.2.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Dependencies
        run: yarn install

      - name: Run Unit Tests
        id: run_unit_tests
        run: |
          [ ! -d "./dist/" ] && mkdir ./dist/
          yarn --silent test:unit:coverage > dist/jest_output.json
          result=$(cat dist/jest_output.json | jq -r '.success')
          echo "::set-output name=success::$result"

      - name: Upload LWC Code Coverage
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          flags: LWC
          token: ${{ secrets.CODECOV_COVERAGE_UPLOAD_TOKEN }}

      - name: Validate result
        run: |
          if [ "${{ steps.run_unit_tests.outputs.success }}" = "false" ]; then
              exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Distribution
          path: dist

````

**Reply by AllanOricil** [reply]
Ok, it does work and it behaves a little bit different than when using using secrets in reusable workflows. We don't need to write again which vars we want to share with the reusable workflow from the caller workflow. Just mention the "var.VARIABLE_NAME" in your reusable workflow and it will work. To make it clear, you can just do the following from the caller workflow


````yml
name: Build on Pull Request

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - main

  workflow_dispatch:

jobs:
    
  build:
    name: Build
    uses: VodafoneIS/salesforce-github-reusable-workflows/.github/workflows/build-on-pr.yml@v2.x
    with:
      ENVIRONMENTS: '["vlocdevbas", "vlocdevpro"]'
      BASE_REF: origin/main
    secrets:
      SF_SFDX_AUTH_URL: ${{ secrets.SF_SFDX_AUTH_URL }}
      CODECOV_COVERAGE_UPLOAD_TOKEN: ${{ secrets.CODECOV_COVERAGE_UPLOAD_TOKEN }}
````

instead of

````yml
name: Build on Pull Request

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - main

  workflow_dispatch:

jobs:
    
  build:
    name: Build
    uses: VodafoneIS/salesforce-github-reusable-workflows/.github/workflows/build-on-pr.yml@v2.x
    with:
      ENVIRONMENTS: '["vlocdevbas", "vlocdevpro"]'
      BASE_REF: origin/main
      SF_ORG_ALIAS: ${{ vars.SF_ORG_ALIAS }}
      SF_INSTANCE_URL: ${{ vars.SF_INSTANCE_URL }}
      SF_REPORT_APEX_CODE_COVERAGE: ${{ vars.SF_REPORT_APEX_CODE_COVERAGE }}
      ENV_TYPE: ${{ vars.ENV_TYPE }}
    secrets:
      SF_SFDX_AUTH_URL: ${{ secrets.SF_SFDX_AUTH_URL }}
      CODECOV_COVERAGE_UPLOAD_TOKEN: ${{ secrets.CODECOV_COVERAGE_UPLOAD_TOKEN }}
````
