### DISCUSSION TITLE
Possible to have multiple actions in a single repo?

### DISCUSSION THREAD

**Discussion by billyvg** [community/community#24990] [Actions]
<p>Is it possible to have a monorepo consisting of many actions? e.g.</p>
<pre><code class="lang-auto">/org/foo
.../action1
.../action2
.../action3
</code></pre>
<p>Then in workflow</p>
<pre><code class="lang-auto">uses: org/foo/action1@master
</code></pre>

**Comment by airtower-luna** [comment, marked as answer]
<p>Yes. For example the <code>github/codeql-action</code> repository is like this:</p>
<aside class="onebox githubfolder">
  <header class="source">
      <img src="https://github.githubassets.com/favicons/favicon.svg" class="site-icon" width="32" height="32">
      <a href="https://github.com/github/codeql-action" target="_blank" rel="noopener">github.com</a>
  </header>
  <article class="onebox-body">
    <div class="aspect-image" style="--aspect-ratio:400/400;"><img src="https://avatars.githubusercontent.com/u/9919?s=400&amp;amp;v=4" class="thumbnail" width="400" height="400"></div>

<h3><a href="https://github.com/github/codeql-action" target="_blank" rel="noopener">github/codeql-action</a></h3>


  <p><span class="label1">Actions for running CodeQL analysis. Contribute to github/codeql-action development by creating an account on GitHub.</span></p>

  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

<p>The README there also shows how the actions are used.</p>

**Reply by ArangoGutierrez** [reply]
Can I have a folder named "actions" an have there multiple folders for each action served by the repo?

**Reply by alexbuznik-stark** [reply]
and how are they to be called?

`uses: codeql-action/check-sarif@main`?

**Reply by NorseGaud** [reply]
@alexbuznik-stark yes/sort of

```
name: "CodeQL Analysis"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * 0'  # Runs at 1:30 AM UTC every Sunday

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'python' ]  # Modify these languages as needed
        # Available options: 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    # Autobuild attempts to build any compiled languages
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
 ```
