### DISCUSSION TITLE
How do I delete a file via FTP after deployment?

### DISCUSSION THREAD

**Discussion by MrYossu** [community/community#25005] [Actions]
<p>Trying to build and deploy an <a href="http://ASp.NET" rel="noopener nofollow ugc">ASp.NET</a> Blazor web site.</p>
<p>I have most of the build and deploy action working, but am stuck with the last step. I am using 3rd party hosting, where the only access I have to the server is either a control panel or FTP. Simply FTPing the files to the server doesn’t work, as IIS locks some of them, so it seems I need to upload a file named <code>app_offline.htm</code> first, then upload the site files, then delete <code>app_offline.htm</code>. It’s that last step that’s causing me problems.</p>
<p>The relevant parts of my current <code>.yml</code> file are shown below (you can see the <a href="https://github.com/MrYossu/Pixata.Utilities/blob/311c5cfaaaec88ccb90d7035be12b8b635da54fc/.github/workflows/release.yml" rel="noopener nofollow ugc">full file here</a> if it helps).</p>
<p>First question is, is this the best way to do it at all? It seems very convoluted. I couldn’t find any way of FTPing a single file, only a folder, so had to create a folder, then create an <code>app_offline.htm</code> file in it, then upload the folder. Is there a simpler way to do this?</p>
<p>The bigger problem is that the last step fails with the following message…</p>
<pre><code class="lang-auto">Run StephanThierry/ftp-delete-action@releases/v1
  with:
    host: ***
    user: ***
    password: ***
    remoteFiles: TmpFolder/app_offline.htm
    ignoreSSL: 1
    workingDir: /
  env:
    DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
Error: Container action is only supported on Linux
</code></pre>
<p>I am running the build and deploy under Windows, and the server is running Windows. I’m not sure how to get around this.</p>
<p>Thanks for any guidance. I’m very new to GitHub actions, so please feel free to suggest any improvements I could make.</p>
<p>Here are the relevant parts of the <code>.yml</code> file…</p>
<pre><code class="lang-auto">    - name: Create TmpFolder
      run: mkdir TmpFolder

    - name: Create app_offline.htm
      run: echo "Updating, please wait" &gt; TmpFolder/app_offline.htm

    - name: Upload app_offline.htm
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.PIXATATESTFTPSERVER }}
        username: ${{ secrets.PIXATATESTFTPUSER }}
        password: ${{ secrets.PIXATATESTFTPPASSWORD }}
        local-dir: ./TmpFolder/

    - name: Publish Pixata.Blazor.Sample
      run: dotnet publish Pixata.Blazor.Sample\Pixata.Blazor.Sample.csproj --framework net5.0 --output Pixata.Blazor.Sample.Publish

    - name: Deploy Pixata.Blazor.Sample
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.PIXATATESTFTPSERVER }}
        username: ${{ secrets.PIXATATESTFTPUSER }}
        password: ${{ secrets.PIXATATESTFTPPASSWORD }}
        local-dir: ./Pixata.Blazor.Sample.Publish/

    - name: Delete TmpFolder
      uses: StephanThierry/ftp-delete-action@releases/v1
      with:
        host: ${{ secrets.PIXATATESTFTPSERVER }}
        user: ${{ secrets.PIXATATESTFTPUSER }}
        password: ${{ secrets.PIXATATESTFTPPASSWORD }}
        remoteFiles: "TmpFolder/app_offline.htm"
        #workingDir: "/public_html"
        ignoreSSL: "1"
</code></pre>

**Comment by otter-computer** [comment]
<p>It looks like the action <a href="https://github.com/StephanThierry/ftp-delete-action"><code>StephanThierry/ftp-delete-action</code></a> you’re using is a Docker container action. Docker container actions are currently only supported when your workflow is run on a Linux runner:</p>
<aside class="onebox githubfolder">
  <header class="source">
      <img src="https://docs.github.com/assets/images/site/favicon.svg" class="site-icon" width="16" height="16">
      <a href="https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions" target="_blank" rel="noopener">docs.github.com</a>
  </header>
  <article class="onebox-body">
    

<h3><a href="https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions" target="_blank" rel="noopener">About actions - GitHub Docs</a></h3>

<p><a href="https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions" target="_blank" rel="noopener">//docs.github.com/en/actions/creating-actions/about-actions</a></p>


  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

<p>You’ll either need to replace any steps in your workflow that run Docker actions or you’ll need to run your workflow on a Linux runner instead.</p>

**Comment by MrYossu** [comment]
<p>Thanks for the reply.</p>
<p>Unfortunately, I can’t build and deploy on a Linux runner, as they don’t seem to handle Blazor very well (I’m <a href="https://chrissainty.com/building-blazor-apps-using-azure-pipelines/" rel="noopener nofollow ugc">not the first to spot this</a>).</p>
<p>Do you know of any way I can get around this? This is such a common issue with IIS, I can’t believe I’m the first person to want to solve it, but I’ve searched for hours, and just can’t find anyone who shows how to do it.</p>
<p>Although my current code seems clunky, if I could find a way to delete or rename the file via FTP, it would work. Surely there must be some way of doing this on a Windows machine?</p>
<p>Thanks again.</p>

**Comment by airtower-luna** [comment]
<p>My first thought is that Python is available on the Windows runners, so you could use the <a href="https://docs.python.org/3/library/ftplib.html"><code>ftplib</code> module</a>.</p>

**Comment by MrYossu** [comment]
<p><a class="mention" href="/airtower-luna">@airtower-luna</a> Thanks for the suggestion. As I’m completely new at actions, please could you give me some guidance as to how I would use that module in my yml file?</p>
<p>Specifically, would I need to do anything to get Python running, and how do I use the module in the yml?</p>
<p>Thanks again.</p>

**Comment by airtower-luna** [comment]
<aside class="quote no-group" data-username="mryossu" data-post="5" data-topic="157541">
<div class="title">
<div class="quote-controls"></div>
 mryossu:</div>
<blockquote>
<p>Specifically, would I need to do anything to get Python running, and how do I use the module in the yml?</p>
</blockquote>
</aside>
<p>Two options:</p>
<ol>
<li>Write a Python script file that does what you need, commit that to your repository, and call it from a <code>run</code> step.</li>
<li>You can <a href="https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell">specify a custom shell for a <code>run</code> step</a>, and you can use <code>python</code> for that. In that case you can put the Python code directly into your YAML file:</li>
</ol>
<pre><code class="lang-yaml">steps:
  - name: clean up via FTP
    shell: python
    run: |
      import ftplib
      with FTP('ftp.example.com') as ftp:
          ftp.login()
          ftp.delete('somefile.txt')
</code></pre>
<p>I’m not sure how the Windows runners are set up, but <a href="https://github.com/actions/virtual-environments/blob/e2d6b1632be3cc77ce56a845b3512bc5847f2003/images/win/Windows2019-Readme.md">according to the environment documentation</a> Python is already installed, so you shouldn’t need to do anything. If you need a specific version you might want to run <a href="https://github.com/actions/setup-python"><code>actions/setup-python</code></a> first (but I don’t see why you would need to).</p>

**Comment by MrYossu** [comment]
<p>Thanks for the reply. I tried this, but couldn’t get it to work. Here is the test .yml file I have…</p>
<pre><code class="lang-auto">name: Test FTP rename

on:  
  push:  
    branches: [ master ]
    
jobs:
  Rename_File: 
    runs-on: windows-latest
    steps:
    - name: rename file
      shell: python
      run: |
        import ftplib
        with FTP(${{ secrets.PIXATATESTFTPSERVER }}) as ftp:
            ftp.login(${{ secrets.PIXATATESTFTPUSER }}, ${{ secrets.PIXATATESTFTPPASSWORD }})
            ftp.delete('jim.txt')
</code></pre>
<p>When I run it, it fails with the following error…</p>
<blockquote>
<p>Run import ftplib<br>
File “D:\a_temp\f82d80e5-b14a-433e-919d-2c7684cbf258.py”, line 2<br>
with FTP(***) as ftp:<br>
^<br>
SyntaxError: invalid syntax<br>
Error: Process completed with exit code 1.</p>
</blockquote>
<p>The “^” was underneath the “ftp:” at the end of the “with” line.</p>
<p>If I add single quotes around the secrets, then the error changes to…</p>
<blockquote>
<p>Run import ftplib<br>
import ftplib<br>
with FTP(‘<em><strong>’) as ftp:<br>
ftp.login('</strong></em>’, ‘<em><strong>’)<br>
ftp.delete(‘jim.txt’)<br>
shell: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.EXE {0}<br>
Traceback (most recent call last):<br>
File “D:\a_temp\0d49b741-1d41-4988-b300-48887b8c449f.py”, line 2, in <br>
with FTP('</strong></em>’) as ftp:<br>
NameError: name ‘FTP’ is not defined<br>
Error: Process completed with exit code 1.</p>
</blockquote>
<p>Any ideas? Thanks again.</p>

**Comment by MrYossu** [comment, marked as answer]
<p>OK, ignore the previous. Seems the syntax was wrong. I changed the code to…</p>
<pre><code class="lang-auto">    steps:
    - name: rename file
      shell: python
      run: |
        import ftplib
        ftp = ftplib.FTP('${{ secrets.PIXATATESTFTPSERVER }}')
        ftp.login('${{ secrets.PIXATATESTFTPUSER }}', '${{ secrets.PIXATATESTFTPPASSWORD }}')
        ftp.delete('jim.txt')
        ftp.quit()
</code></pre>
<p>…and it worked fine.</p>
<p>Thanks again</p>

**Comment by airtower-luna** [comment]
<p>I’m glad it works, I’d recommend using <code>with</code> though to make sure the connection is terminated properly even on errors. :wink:</p>

**Comment by MrYossu** [comment]
<p>OK, thanks for the tip. Thanks again for all the help.</p>

**Comment by GregFinzer** [comment]
I am using SmarterASP.NET.  Here is what I am using to upload and then delete the app_offline.htm

```
name: Build, Test, and Deploy to Develop

on:
  push:
    branches:
      - develop  # Adjust this to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variable from secret
      run: echo "GOLD=${{ secrets.GOLD }}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Adjust the version if needed

    - name: Replace Connection String in appsettings.Development.json
      run: |
        sed -i 's#"DefaultConnection": ".*"#"DefaultConnection": "${{ secrets.DEV_CONNECTION_STRING }}"#' ./BedBrigade.Client/appsettings.Development.json
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test

    - name: Create TmpFolder
      run: mkdir TmpFolder

    - name: Create app_offline.htm
      run: echo "<html><body><h1>The application is offline for maintenance</h1></body></html>" > ./TmpFolder/app_offline.htm

    - name: Upload file app_offline.htm
      uses: tomasbkk/action-ftp-upload@v1.0
      with:
        user: ${{ secrets.FTP_DEV_USERNAME }}
        password: ${{ secrets.FTP_DEV_PASSWORD }}
        host: ${{ secrets.FTP_DEV_HOST }}
        src: ./TmpFolder/app_offline.htm
        dest: app_offline.htm

    - name: Wait for 10 seconds
      run: sleep 10
      
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_DEV_HOST }}  
        username: ${{ secrets.FTP_DEV_USERNAME }}  
        password: ${{ secrets.FTP_DEV_PASSWORD }}  
        local-dir: ./publish/
        server-dir: /  
        protocol: ftp  
    
    - name: Delete app_offline.htm
      uses: StephanThierry/ftp-delete-action@v2.1
      with:
        host: ${{ secrets.FTP_DEV_HOST }}
        user: ${{ secrets.FTP_DEV_USERNAME }}
        password: ${{ secrets.FTP_DEV_PASSWORD }}
        remoteFiles: "app_offline.htm"
        ignoreSSL: "1"
```
