### DISCUSSION TITLE
Number of cores as env/context variable ?

### DISCUSSION THREAD

**Discussion by mellery451** [community/community#25057] [Actions]
<p>Is there a general way to obtain the number of cores available on the current runner, no matter the OS ? I need to pass this number to some tools I’m using to configure parallelism.</p>

**Comment by BrightRan** [comment, marked as answer]
<p>GitHub seems has no predefined environment variables or contexts to get the number of cores.</p>
<p>As a workaround, you can run the following commands on each OS to view the number of cores:</p>
<p><strong>On Windows:</strong></p>
<pre><code>WMIC CPU Get DeviceID,NumberOfCores,NumberOfLogicalProcessors
</code></pre>
<p>OR</p>
<pre><code>WMIC CPU Get /Format:List
</code></pre>
<p><strong>On Linux:</strong></p>
<pre><code>lscpu
</code></pre>
<p>OR</p>
<pre><code>lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
</code></pre>
<p><strong>On macOS:</strong></p>
<pre><code>system_profiler SPHardwareDataType
</code></pre>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/8/8e63097cfac1b53af32fabc6a2c4ed5ea6f35a7f.png" data-download-href="/uploads/short-url/kjBZb0agtDvms3rVySN55HJNAu3.png?dl=1" title="example.PNG" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/46307996/181088596-efe9ba65-d072-44e7-a6c4-6141f638f43b.png" alt="example.PNG" data-base62-sha1="kjBZb0agtDvms3rVySN55HJNAu3" width="449" height="500" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/8/8e63097cfac1b53af32fabc6a2c4ed5ea6f35a7f_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">example.PNG</span><span class="informations">593×659 11.1 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>
<p>Then you can try to get the number from the output of the command, and <strong><a href="https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-output-parameter-set-output" rel="nofollow noopener">set an output parameter</a></strong> with using the number as value.</p>
<p>In a workflow, The output parameter only can be used between the steps in a same job via the syntax  <strong>steps.&lt;step_ID&gt;.outputs.&lt;output_name&gt;</strong>. If you want to share the output parameter in other jobs, you can try to use artifact to pass the output parameter across jobs.</p>
<p>My reply in <a href="https://github.community/t/perform-next-job-if-specific-step-of-previous-job-was-success/17329">this ticket</a> shows a simaple demo about how to pass variables/parameters acress jobs.</p>
<p>Hope this can help you.</p>

**Reply by urbasus** [reply]
On Linux there is the `nproc` program.

**Reply by Kurt-von-Laven** [reply]
Python is available on all GitHub-hosted runners, so you can use the following on all platforms.

```yaml

steps:
  - name: Get the number of CPUs that the current process has access to.
    id: cpus
    run: |
      from os import environ, sched_getaffinity

      num_cpus = len(sched_getaffinity(0))
      output_file = environ["GITHUB_OUTPUT"]
      with open(output_file, "a", encoding="utf-8") as output_stream:
          output_stream.write(f"count={num_cpus}\n")
    shell: python
```

Then you can access the count in subsequent steps via `{{ steps.cpus.outputs.count }}`.

**Reply by ryandesign** [reply]
Python's `os.sched_getaffinity` is not available on macOS nor on Windows, so since you're already describing a Linux-only solution you may as well use the much simpler `nproc`.

For macOS, use `sysctl -n hw.activecpu`.

**Comment by sethrj** [comment]
I also think this should be an intrinsic variable provided by GitHub. Here's one workflow that implements the capability using node.js: https://github.com/SimenB/github-actions-cpu-cores

**Comment by scottschreckengaust** [comment]
This worked (and so did the commented out code - but I prefer the one-liner with the `actions/setup-node`):
```
name: main
on:
  workflow_dispatch
jobs:
  cpu:
    name: cpu
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'windows-latest'
          - 'windows-2019'
          - 'windows-2022'
          - 'ubuntu-latest'
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'
          - 'ubuntu-24.04'
          - 'macos-latest'
          - 'macos-12'
          - 'macos-13'
          - 'macos-14'
        node-version:
          - '22'
          - '20'
          - '18'
          - '16'
          - '14'
        exclude:
          - node-version: '14'
            os: 'macos-latest'
          - node-version: '14'
            os: 'macos-14'
    steps:
      # - name: windows
      #   if: ${{ startsWith(matrix.os, 'windows-') }}
      #   run: |
      #     echo NUMBER_OF_PROCESSORS=$env:NUMBER_OF_PROCESSORS >> "$GITHUB_OUTPUT"
      # - name: ubuntu
      #   if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      #   run: |
      #     echo NUMBER_OF_PROCESSORS=`nproc` >> "$GITHUB_OUTPUT"
      # - name: macos
      #   if: ${{ startsWith(matrix.os, 'macos-') }}
      #   run: |
      #     echo NUMBER_OF_PROCESSORS=`sysctl -n hw.activecpu` >> "$GITHUB_OUTPUT"
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: report number of processors
        run: |
          node -e 'console.log(require("os").cpus().length)'
  ```
