### DISCUSSION TITLE
Checkout with code from the latest release

### DISCUSSION THREAD

**Discussion by Misiu** [community/community#25199] [Actions]
<p>I’ve built a workflow that is triggered by calling GitHub API.</p>
<p>The idea is to deploy the latest release to FTP server on demand.</p>
<pre><code>on:
  repository_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        npm install

    - name: Test
      run: |
        npm run test:ci

    - name: Build
      run: |
        npm run build

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: site/wwwroot
        LOCAL_DIR: build
        METHOD: ftp
        ARGS: --no-empty-dirs --delete
</code></pre>
<p>above code works great, the problem is that it will always deploy latest code from my master branch.</p>
<p>How can I specify that I want to deploy code from the latest release? I’m always creating a tag when I create a release, so I’d like to be able to do a checkout for the latest tag or release.</p>
<p>Is this possible?</p>

**Comment by chrispat** [comment]
<p>You could trigger when a released is published and then checkout would be the ref of the published release.</p>
<pre><code>on:
  release:
    types: [published]
</code></pre>

**Comment by weide-zhou** [comment, marked as answer]
<p>Hi <a class="mention" href="/misiu">@misiu</a> ,</p>
<p>You can specify the ‘tag’ value in the ‘actions/checkout’ args, code sample as below:</p>
<pre><code>- name: tagcheckout
        uses: actions/checkout@v2
        with:
          ref: v1.1.9
</code></pre>
<p>It will checkout the code which tagged with v1.1.9. Please refer to the usage of ‘<a href="https://github.com/actions/checkout#usage" rel="nofollow noopener">actions/checkout</a>’ for more details.</p>
<p>Besides, you can use <a href="https://developer.github.com/v3/repos/releases/#get-the-latest-release" rel="nofollow noopener">rest api</a> to get the latest release, parse the release tagname to the ‘ref’ value then. Code sample as below, it will automatically get the latest release tag and checkout the release code:</p>
<pre><code>steps:
      - name: get latest release with tag
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/weide-zhou/ticket13/releases/latest | jq '.tag_name' | sed 's/\"//g')"
      - name: confirm release tag
        run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}
      - name: tagcheckout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latestrelease.outputs.releasetag }}
</code></pre>
<p><img src="https://user-images.githubusercontent.com/52772761/181089360-be5520b9-d087-4d78-931e-36702e248c49.png" alt="checkoutlatestrelease.png" data-base62-sha1="yxoNkgnxNw3hfRT0KGZkb3qRoLa" width="388" height="392"></p>
<p>Thanks.</p>

**Reply by sjpb** [reply]
Better to use `jq -r` I think than `sed` to strip the quotes off the tag

**Comment by Misiu** [comment]
<p>I’ve tried your code, and it works for public repo, but I have a private repo. How should I modify curl request to pass authentication token?</p>
<p>when I do a request with Postman (and pass token in the header) I get the correct response. My tag looks like this:</p>
<p> “2020-03-18-05”</p>
<p>Got it. I had to add:</p>
<pre><code>--header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
</code></pre>

**Comment by brazarb** [comment]
Or you can use this action https://github.com/marketplace/actions/github-script

```yaml
- uses: actions/github-script@v6
  id: get-release
  with:
    # result-encoding: string
    retries: 3
    script: |
      if (${{ startsWith(github.event.inputs.ref, 'v') }}) {
        return github.rest.repos.getReleaseByTag({
          owner: context.repo.owner,
          repo: context.repo.repo,
          tag: "${{ github.event.inputs.ref }}"
        })
      } else {
        return github.rest.repos.getLatestRelease({
          owner: context.repo.owner,
          repo: context.repo.repo
        })
      }
```
