### DISCUSSION TITLE
Using environment in workflow_call

### DISCUSSION THREAD

**Discussion by jasoncarteref** [community/community#25238] [Actions]
<p>For some reason I am unable to access environment values (note: I’m not referring to env values) in a workflow_call.  Here is my example:</p>
<p>script_outer.yml</p>
<pre><code class="lang-auto">jobs:
  outer_test:
    name: Outer test
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Outer Environment Test
        run: |
          echo "secrets: ${{ secrets.AWS_ACCESS_KEY_ID }}"

  call_workflow:
    name: Call Workflow
    uses: [my repo]/.github/workflows/script_inner.yml@[SHA]
</code></pre>
<p>script_inner.yml</p>
<pre><code class="lang-auto">on: 
  workflow_call

jobs:
  inner_test:
    name: Inner test
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Inner Environment Test
        run: |
          echo "secrets: ${{ secrets.AWS_ACCESS_KEY_ID }}"
</code></pre>
<p>When outer_test runs, I get the following output in the Action runner:</p>
<pre><code class="lang-auto">secrets: ***
</code></pre>
<p>When the inner_test runs I get the following:</p>
<pre><code class="lang-auto">secrets: 
</code></pre>
<p>The AWS_ACCESS_KEY_ID secret is an <em>environment secret</em>.  It is not a <em>repository secret</em> not is it an <em>organization secret</em>.  The action runner completes without error and reports success at the end of execution.</p>
<p>This is a stripped down example to demonstrate that I am not getting the value I expect to get in “script_inner.yml”.  I am not trying to print out the value un-obfuscated.  I do have a work around but using GitHub Environments would make our code much cleaner so it is my preferred method of passing these secrets to script_inner.yml. This seems like a bug to me.  Is anyone else familiar with this specific scenario?</p>

**Comment by deanro** [comment]
<p>I think you have to explicitly pass down the secret to your workflow. So on your workflow call you have something like this.</p>
<pre><code class="lang-auto">on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
</code></pre>
<p>and you pass it when calling it on the uses</p>
<pre><code class="lang-auto">uses: .......
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
</code></pre>
<p>Good luck<br>
Dean.</p>

**Comment by jsoref** [comment]
This is correct.
Fwiw, it’s documented here:

> [Reusing workflows - GitHub Docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)
> Learn how to avoid duplication when creating a workflow by reusing existing workflows.

**Comment by jasoncarteref** [comment]
<p>By the time we get to the call_workflow step in script_outer.yml, the “environment: dev” is already out of scope because it pertained to the outer_test step.  So I would need to be able to re-declare the environment in the call_workflow step.  This is not possible however.  You will receive errors if you try to define an environment in the same step where you are using a uses.  This means you can not pass down a secret from the environment to the inner workflow.  You can only pass down secrets that are a part of the global scope and not ones that are a part of an “environment” specific scope.</p>

**Reply by elyobo** [reply]
Yeah, this seems to be a fundamental problem, workflow call + environment level secrets seem completely incompatible.

**Comment by deanro** [comment]
<p>It sounds like I’m having a similar or maybe the same problem. I can pass secrets down but not environment values even if they’re in the outer scope.</p>
<p>e.g. I have something like the following</p>
<pre><code class="lang-auto">name: CI/CD

env:
  TAG_NAME: latest
on:
...

jobs:
  build:
    uses: &lt;owner&gt;/&lt;repo&gt;/.github/workflows/docker-build-and-push.yml@v1
    with:
      IMAGE_TAG: $TAG_NAME
</code></pre>
<p>In my docker-build-and-push.yml I have</p>
<pre><code class="lang-auto">on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string
</code></pre>
<p>However, when it’s run, IMAGE_TAG is blank in the lower workflow.</p>
<p>If in the outer workflow I type in an explicit value, it works fine.</p>
<p>e.g.</p>
<pre><code class="lang-auto">  deploy:
    uses: &lt;owner&gt;/&lt;repo&gt;/.github/workflows/docker-build-and-push.yml@v1
    with:
      IMAGE_TAG: latest
</code></pre>
<p>Thanks<br>
Dean.</p>

**Comment by jasoncarteref** [comment]
<p>Not the same issue but I have a work around for you.  If you have a step before “build” that declares an output, you can use that in the call to docker-build-and-push.yml.  Here’s an example:</p>
<pre><code class="lang-auto">on:
  push:
    branches-ignore:
      - qa
      - prod

jobs:
  setup_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Setup shared variables
        id: env_vars
        run: echo "Variables set"
    outputs:
      TagBuild: ${{ !contains(github.ref, 'feature/') }}

  tag_repo:
    needs:
      - setup_vars
    uses: my_inner_workflow.yml@v1
    with:
      do_tag: ${{ needs.setup_vars.outputs.TagBuild }}
</code></pre>
<p>As a side note, I have had your issue before as well.  I’m pretty sure it’s a bug.</p>

**Comment by jasoncarteref** [comment, marked as answer]
<p>I was finally able to get a solution/clarification from GitHub support.  The following example outputs “Match” if you have an environment called TestEnvironment with a secret called TEST_SECRET set to 123 in your repository.</p>
<pre><code class="lang-auto">name: Test Parent
on: push
jobs:
  Job1:
    uses: ./.github/workflows/test_child.yml
    secrets:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
</code></pre>
<pre><code class="lang-auto">name: Test Child
on: 
  workflow_call:
    secrets:
      TEST_SECRET:
        required: true
jobs:
  Job1:
    runs-on: ubuntu-latest
    environment: TestEnvironment
    steps:
      - name: Step 1
        run: |
          if [ "${{ secrets.TEST_SECRET }}" == "123" ]; then
            echo "Match"
          else
            echo "Not matched"
          fi
</code></pre>
<p>This is what’s happening (and is the intended functionality of GitHub Actions).  The last line in the parent script, “TEST_SECRET: ${{ secrets.TEST_SECRET }}” is granting access to the child script to read the value TEST_SECRET.  It is not actually passing the value because TEST_SECRET is not in scope at this point in the code and is therefor an empty string.  Since it’s being passed in however, when the “environment: TestEnvironment” line is run in the child workflow, it populates that secret with the environment’s value and can be used in the associated steps.</p>

**Reply by brandongallagher1999** [reply]
Still hoping GitHub will fix this.

**Reply by dteoh** [reply]
This is bonkers... the described or implemented behaviour sounds like a bug...

Either `environment` is ignored completely in a `workflow_call` context or it should be loaded if that is what has been specified.

**Reply by DamianKedzior-Unity** [reply]
I wish GitHub has properly documented this because this is very not intuitive.

**Reply by develth** [reply]
so you have to define for each environment a job?

**Reply by jsoref** [reply]
Keep in mind that GitHub lets repo admins / org admins / enterprise admins define lots of secrets that could be available to a repository, but they don't want secrets to just leak like a sieve into a workflow.

Given that constraint, each workflow must explicitly declare which secrets they want to expose to any downstream actions/workflows/environments.

Anything else would be way too risky.

That said, the syntax is indeed awkward and confusing. (It's a case of "[if all you have is a hammer, everything looks like a nail](https://en.wiktionary.org/wiki/if_all_you_have_is_a_hammer,_everything_looks_like_a_nail)".)

**Reply by tleerai** [reply]
Wait, does this mean we have to have a reusable workflow for every environment, thereby making it not reusable?

**Reply by tleerai** [reply]
I've modified the example to help people out with what seemed like an environmental paradox. The environment you want your reusable workflow to use can be passed as an input. Also no need to pass every secret manually, just need to receive them as usual:
```
name: Test Parent
on: push
jobs:
  Job1:
    uses: ./.github/workflows/test_child.yml
    with:
      environment: prod
    secrets: inherit
```

```
name: Test Child
on: 
  workflow_call:
    secrets:
      TEST_SECRET:
        required: true
      environment:
        required: true
        type: string
jobs:
  Job1:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Step 1
        run: |
          if [ "${{ secrets.TEST_SECRET }}" == "123" ]; then
            echo "Match"
          else
            echo "Not matched"
          fi
```

**Reply by brandongallagher1999** [reply]
I've tried the method above to no success, although it was a couple months ago. Has this change been made? Environments were only be able to be recognized via static strings, not inputs.

**Reply by tleerai** [reply]
I've been using the environment passed as a variable for a couple weeks now, no problems. So if that was a limitation, that has been resolved it seems.

**Reply by hcastrofactored** [reply]
@jasoncarteref did you find a workaround for this?

-- @tleerai are you passing the environment as secret? or are you hardcoding the env name from the caller? wouldn't that defeat the point of having environments? Am I missing something? 

Thanks, both, any help would be much appreciate it

**Reply by tleerai** [reply]
I hard code the environment name in my calling file, but my calling file is environment specific.

Trying to use a single file for multiple environments introduces a rats nest of conditionals that should only be attempted if you're trying to maintain many environments, like say you have six or eight because you've got internal/external of each. 

In those cases, I cannot say if using a variable works, I'd imagine it does though. 

Generally speaking, I've learned that having a separate environment file, which has very limited code duplication, eases the troubleshooting errors that can crop up randomly due to conditional statements related to environments.

**Reply by mariusfilipowski** [reply]
I had to change it a litte to let it work:
```
on: 
  workflow_call:
    secrets:
...
    inputs:
      environment:
        required: true
        type: string
jobs:
```

Then it worked wonderfully for me. Now I can write reusable workflows that can target different environments.
Thanks for the example

**Reply by gilfthde** [reply]
Did anyone make this *workaround* work with [environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-environment)?

**Reply by elyobo** [reply]
Yes, the original version surprisingly does seem to work - not the later version which uses `secrets: inherit`, you need to exactly specify the secrets that will be accessed from the environment variables. It's surprising because the calling job cannot itself access the variable it appears to be passing through.

Mixing up the two examples, you can pass through a dynamic environment through the inputs to have a workflow that works across multiple environments and can access secrets from those environments. Edited from the examples above, may not be strictly correct, but I do have real workflows working with this now.

```yaml
name: Test Parent
on: push
jobs:
  Job1:
    uses: ./.github/workflows/test_child.yml
    with:
      environment: production
    secrets:
      # secrets.TEST_SECRET can be an environment variable that this job cannot actually access, which is very unclear and confusing
      # I guess think of it more like giving permission to access this value rather than passing the value itself :shrug:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
```

```yaml
name: Test Child
on: 
  workflow_call:
    inputs:
        environment:
          required: true
          type: string
    secrets:
      TEST_SECRET:
        required: true
jobs:
  Job1:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Step 1
        run: |
          if [ "${{ secrets.TEST_SECRET }}" == "123" ]; then
            echo "Match"
          else
            echo "Not matched"
          fi
```

**Reply by teohhanhui** [reply]
What worked for me (since I cannot explicitly list the environment secrets that I need) is to use `secrets: inherit` when **calling** the workflow, and specifying the `environment` at the job level in the **called** workflow (`on.workflow_call.secrets` is not specified at all).

It seems to match what's documented here: https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows#using-inputs-and-secrets-in-a-reusable-workflow

> If the secrets are inherited by using `secrets: inherit` in the calling workflow, you can reference them even if they are not explicitly defined in the `on` key.

Read together with the warning in the same section:

> Warning
> 
> Environment secrets cannot be passed from the caller workflow as `on.workflow_call` does not support the `environment` keyword. If you include `environment` in the reusable workflow at the job level, the environment secret will be used, and not the secret passed from the caller workflow.

It does exactly what I need (access environment secrets from the called workflow).

**Comment by aseem-heg** [comment]
I am trying to pass env variable `ECR_REPOSITORY_NAME` to a workflow but it doesnt work
I declare env variable in the same file 

```
name: Create PR db on pull request
on:
 pull_request:

env:
 ECR_REPOSITORY_NAME: data-engineering/data-warehouse
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:

 Build-Docker-image:
   name: Build docker image on GHA and upload to ECR and GHA artifact store
   uses: ./.github/workflows/build_docker_image.yml
   with:
     ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_NAME }} # doesnt work
     IMAGE_TAG: ${{ github.sha }}

```



```
with:
   X: ${{ github.sha}}  # works

with:
   X: ${{ env.xyz}}  # NOT work
   X: $xyz  # NOT work

```

**Comment by Nick-Gabe** [comment]
What I did to solve this problem of using env variables on my workflow call is simply create a previous job and output the env variables.
It's not as pretty as native env usage would be, but works.
```yml
jobs:
  # GitHub doesn't allow using env vars in workflow calls, so as a workaround we
  # have to output them from a job.
  vars:
    runs-on: ubuntu-latest
    outputs:
      project-id: ${{ env.PROJECT_ID }}
      some-var: ${{ env.SOME_VAR }}
    steps:
      # Step needed for job to be valid
      - name: Confirm variables set
        run: echo "Variables set"

  your-call:
    needs: vars
    uses: ./.github/workflows/yourcall.yml
    with:
      project-id: ${{ needs.vars.outputs.project-id }}
      some-var: ${{ needs.vars.outputs.some-var }}
```
