### DISCUSSION TITLE
Env variables in uses

### DISCUSSION THREAD

**Discussion by luigi311** [community/community#25246] [Actions]
<p>It would be nice to be able to use enviornmental variables in a uses varaible. This will allow for easy changing of versions for actions such as checkout.</p>
<pre><code>name: svt-av1
on: [push, pull_request]
env:
  checkout: 'actions/checkout@v2

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: ${{ env.checkout }}
      with:
        fetch-depth: 1
</code></pre>

**Comment by chrispat** [comment, marked as answer]
<p>In order to enact policies like only using actions defined in the org or repo we can’t allow actions to dynamically change at runtime.  So using any sort of dynamic value in uses is not something we will be able to support.</p>

**Reply by Zopolis4** [reply]
How is this:
```yaml
# Works
name: foo
if: env.workflow == 'foo'
uses: ./.github/workflows/foo.yml

name: bar
if: env.workflow == 'bar'
uses ./.github/workflows/bar.yml
```
acceptable, while this:
```yaml
# Doesn't work
name: example
uses: ./.github/workflows/${{ env.workflow }}.yml
```
is not?

**Reply by ghost** [reply]
Wow this makes composite actions way **less** useful, it could've been so simple:

```
  Run-Project-Actions:
    runs-on: ubuntu-latest
    needs: Setup
    strategy:
      fail-fast: false
      matrix:
        ${{ insert }}: ${{ fromJson(needs.Setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Call Project Action
        uses: ./.github/actions/${{ matrix.project }}
        with:
          project-path: ${{ matrix.project }}
```

@chrispat What would be the recommended way to run only a specific actions based on the project name in a mono repo?
e.g. 

```
.github/actions/Project1.yml
.github/actions/Project2.yml <- Run this!
.github/actions/Project3.yml
Project1
Project2 <- Changes
Project3
```

Couldn't you do the check during run time?

**Reply by omergoktas** [reply]
You're full of shit, you know nothing and fabricate stupid policies off your ass just to sound cOoL

**Reply by Malix-Labs** [reply]
@chrispat can you answer https://github.com/orgs/community/discussions/25246#discussioncomment-6260695 please?

**Comment by luigi311** [comment]
<p>This makes it more work to update multiple jobs to a newer version of an action or even different workflows since you could in theory just have the maintainers put the versions in a github secret and call it on all their workflows and update everything at once though i think its still better to just do it as a global env variable in the script so it is easier to see and modify in pull requests. If you do not thing this is something that will ever be support then i guess we can go ahead and mark this as solved then.</p>

**Comment by ArchieCoder** [comment]
<p>Hi,</p>
<p>On every push, I want to create a release. I can’t figure out how to use the runtime variable <a href="https://twitter.com/search?q=%24env&amp;src=cashtag_click" rel="nofollow noopener">$env</a>:NBGV_SimpleVersion there. Any idea? I tried so many version, but no luck.</p>
<p>If I don’t put a version, the step will fail because the tag name will be already exist on the next run.</p>
<p>In that image, I want to replace the HERE_VERSION with $env:NBGV_SimpleVersion which is set by the step aarnott/nbgv@v0.3<br>
<img src="https://pbs.twimg.com/media/EUAbKkcXgAAa169?format=png&amp;name=small" alt="Image"></p>
<p>Thanks</p>

**Comment by jillesvangurp** [comment]
<p>The counter argument to stability/safety, is that master changes every time there’s a commit. That sounds like a problem to me.</p>
<p>Having a mechanism to centrally control versions for uses seems like it’s a good idea. In fact, my build breaking because terraform actions merged some PR to master was how I found out that I needed to copy paste the string v0.12.4 everywhere. My first thought was to use ${{ env.TERRAFORM_VERSION }} which broke with an obscure error of env not existing. I wasted a good amount of time figuring out why until I finally ended up here because the error was very misleading.</p>
<p>Maybe a better approach is to apply the policy after templating or reconsider how this works (I think it’s weird to have this limitation on a build server where you are running arbitrary tests, docker, bash, etc. anyway).</p>

**Comment by benjamin-bergia** [comment]
<p>Is there any work being done on this at the moment?</p>
<p>I am working  exclusively with docker in my WFs and it is almost impossible to test any image built in a WF. Since services, steps, etc cannot use images defined dynamically, I am forced to use <code>docker run</code> directly in my steps.</p>
<p>In my opinion the safety argument doesn’t hold here since I have to implement my own <code>docker run</code> action in order to start my containers with the right image. There is no way that some random shell script written by an average Joe like me is safer than the services and docker jobs written by knowledgeable people a GH!</p>

**Comment by reitzig** [comment]
<p>Surely, you could allow variables in the <em>version</em> (or tag?) part of <code>uses</code> and still maintain this property?</p>
<p>As far as I can tell, this is blocking testing actions:</p>
<pre><code class="lang-yaml">jobs:
  test:
    name: "Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
    steps:
      - name: Run this action!
        uses: me/this-repo@${{ github.sha }}
</code></pre>

**Comment by reitzig** [comment]
<aside class="quote no-group" data-username="benjamin-bergia" data-post="6" data-topic="17466">
<div class="title">
<div class="quote-controls"></div>
 benjamin-bergia:</div>
<blockquote>
<p>There is no way that some random shell script written by an average Joe like me is safer than the services and docker jobs written by knowledgeable people a GH!</p>
</blockquote>
</aside>
<p>Right. Quite often, Github Actions don’t let me do something nicely that I then have little issue reproducing in a script. Most recent example: no <code>if</code> in composite action steps, so …<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/3X/b/1/b19dfa14f9882b5328eb8653bb8dcea8be1c7476.png" data-download-href="/uploads/short-url/plgYwqSi5lWWDrRW3eJUrYnnq0m.png?dl=1" title="image" rel="noopener nofollow ugc"><img src="https://user-images.githubusercontent.com/4246780/181089840-ecf58e37-fb38-4892-a40c-3c44a665f50c.png" alt="image" data-base62-sha1="plgYwqSi5lWWDrRW3eJUrYnnq0m" width="690" height="264" srcset="https://aws1.discourse-cdn.com/github/optimized/3X/b/1/b19dfa14f9882b5328eb8653bb8dcea8be1c7476_2_690x264.png, https://aws1.discourse-cdn.com/github/original/3X/b/1/b19dfa14f9882b5328eb8653bb8dcea8be1c7476.png 1.5x, https://aws1.discourse-cdn.com/github/original/3X/b/1/b19dfa14f9882b5328eb8653bb8dcea8be1c7476.png 2x" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/3X/b/1/b19dfa14f9882b5328eb8653bb8dcea8be1c7476_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">image</span><span class="informations">945×362 38.2 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>

**Comment by alonbl** [comment]
<p>Hello,</p>
<p>Any news for this? I cannot even use an action from the repository triggered the action.</p>
<pre><code class="lang-auto">        uses: ${{ github.repository }}/.github/workflows/build-linux-func.yml@${{ github.ref_name }}
</code></pre>
<p>Any opened bug I can monitor?<br>
Thanks!</p>

**Reply by cezar-tech** [reply]
> Hello,
> 
> Any news for this? I cannot even use an action from the repository triggered the action.
> 
> ```
>         uses: ${{ github.repository }}/.github/workflows/build-linux-func.yml@${{ github.ref_name }}
> ```
> 
> Any opened bug I can monitor? Thanks!

I wanted to do the same thing, i have many reused actions here that need t o be referenced

**Reply by amhelderman** [reply]
Apologies if you've already solved this. It looks like you wanted to use a custom workflow defined in the current commit.

In your specific case, could I suggest using something like this? This is what I do.

```
        uses: ./.github/workflows/build-linux-func.yml
 ```
 
Assuming that you've checked out the workflow, Github Actions can check if this path includes a valid workflow and can run it (see [this](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow)).

**Reply by NithishNetxd** [reply]
is there any way i give the full path in env and use it in uses?

**Comment by DanForever** [comment]
This is also something I'm interested in, and from the other responses, it doesn't sound like the "for security" argument holds much water

**Comment by neillfontes-klar** [comment]
I wanted to accomplish this that sounds super intuitive to me, but sadly I couldn't:


```
jobs:
  test:
    name: Sample
    runs-on: self-hosted
    steps:
      - name: Prepare docker full name
        run: echo "DOCKER_TAG=docker://docker-registry.url/project:${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Show docker tag
        run: echo ${DOCKER_TAG}
      - uses: actions/checkout@v3
        name: Standard Checkout
      - uses: "${DOCKER_TAG}"
        name: Run
```

We are building docker images for branches in some specific cases that we would like to use later to run tests on, but I guess it won't be a possibility in the current state of things.

**Comment by neillfontes-klar** [comment]
Small update on my issue:

I was able to circumvent the limitation by doing this in my case:

```
- name: Set docker tag
  run: |
    echo "DOCKER_TAG=docker-registry.url/project:${{ github.ref_name }}" >> $GITHUB_ENV
    echo ${DOCKER_TAG}
- uses: actions/checkout@v3
  name: Standard Checkout
  with:
    ref: ${{ github.ref_name }}
- uses: webfactory/ssh-agent@v0.7.0
  with:
    ssh-private-key: "${{ secrets.SSH_KEY }}"
- name: Run Tests
  env:
    ENV_TAGS: "${{ github.event.inputs.testParam }}"
  run: |
    docker pull ${{ env.DOCKER_TAG }}
    docker run --name bla -e ENV_TAGS=${ENV_TAGS} ${{ env.DOCKER_TAG }}
- name: Export target folder
        if: always()
        run: |
          docker cp bla:target/ .
```

This allows me to:

1. Compose the url required for the `docker pull` command including the project name and the branch-related tag
2. Check out the corresponding branch with the changes 
3. Setup ssh-agent with the Org's ssh key to perform the `docker` commands
4. Do the `docker run` with the necessary parameters and pointing to the proper branch-related tag
5. Collect the results from the `docker run` with the `docker cp` so I can use it further for reporting on the github action

Seems to have worked for me. Would have been a lot easier with the `uses: ${env.VAR}` but the above unblocked me.

**Comment by cezar-tech** [comment]
This would be a nice feature to help us reference the reusable local actions inside a reusable workflow

**Reply by didrocks** [reply]
This is exactly my use case too.

**Reply by amhelderman** [reply]
I've just commented this elsewhere in this discussion, but on the off-chance that it helps, would it help you to reference the local yml file?

Something like this? This is what I do. It also seems to work for actions.

```
        uses: ./.github/workflows/build-linux-func.yml
        # or 
        uses: ./.github/actions/custom-action/action.yml
 ```
 
Assuming that you've checked out the workflow, Github Actions can check if this path includes a valid workflow and can run it (see [this](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow)).

**Reply by cezar-tech** [reply]
@amhelderman  I believe this works for a local workflow.

In my case however where I have a reusable workflow in another remote repo that contains de CI logic, the reusable workflow's repo itself can't reference it's own local reusable actions.

e.g.
* Lets say I have a repo A that reuses some workflow, centered in a project B.
* So in A's ci file I only point towards B's ci's file.
* Inside B's workflow's definition, it makes use of reusable actions.

In this case the main reusable workflow file can't find the actions If I don't point the actions towards the B's repo with a branch tag

**Reply by ViktorWelbers** [reply]
I am running into the same problem while trying to call a reusable workflow and passing in the versions for reusable actions. Seems like this won't get fixed anytime soon, since this discussion is now ongoing for 4 years :)

**Reply by GoncaloPT** [reply]
I'm not proud of it... but inside of the action i have some reusable action on the sibling folder, I've been adding the following step:

```yml
    - name: copy <internal_action_name> - if needed
      shell: bash
      run: |
        if [[ "$(pwd)" == *<action-repository>* ]]; then
          echo "inside of <action-repository>, no need to copy"
          exit 0
        fi
        cp -r $GITHUB_ACTION_PATH/../<internal_action_name> ./<internal_action_name>
```

Then I use the internal action action like:
```yml
    - name: <internal_action_name>
      uses: ./<internal_action_name>
```

The `if` is required because I've test workflows inside of the action repository itself. Copy in that scenario would fail since the folder to copy is already in the destination.

**Reply by sc0w** [reply]
@GoncaloPT  please, can you show us in which commit  is implemented to see how it works?

**Reply by GoncaloPT** [reply]
@sc0w this was done on github enterprise, private code, but I think I can reproduce it easily during the week.

**Comment by jenseng** [comment]
As a workaround, you can use a composite action to generate and run another composite action to call the desired dynamic action 😅 ... Give [`jenseng/dynamic-uses@v1`](https://github.com/marketplace/actions/dynamic-uses) a spin (or feel free to borrow/fork/adapt its [action.yml](https://github.com/jenseng/dynamic-uses/blob/main/action.yml))

Given a step like so:

```yaml
- uses: actions/setup-node@v3
  with:
    node-version: 18
```

If you want your `uses` to be dynamic you can do:

```yaml
- uses: jenseng/dynamic-uses@v1
  with:
    # now you can use expressions 🥳
    uses: actions/setup-node@${{ inputs.version }}
    # the `with` needs to be converted to a valid json string
    with: '{ "node-version": 18 }'
```

Note that this only works to call **_actions_** dynamically, there's not currently a way to call a reusable **_workflow_** dynamically
