### DISCUSSION TITLE
Calling custom composite action from reusable workflow

### DISCUSSION THREAD

**Discussion by rratefiarivony** [community/community#25289] [Actions]
<p>Hi community,<br>
Is it possible to call custom composite actions from reusable workflow ?<br>
I can’t found documentation (limitation about it).<br>
When I call my reusable workflow from other repository, I run into : <code>Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/my-repo/my-repo/.github/actions/my-custom-composite-action'. Did you forget to run actions/checkout before running your local action?</code><br>
Thanks for your help.</p>

**Comment by airtower-luna** [comment, marked as answer]
<p>It should be possible, yes, <em>if</em> you either reference them like an external action, or check them out for local actions. The error message indicates you tried do use a local action without checking it out. Saying more would require a look at the code.</p>

**Reply by Rwadxvv** [reply]
Ii

**Reply by Rwadxvv** [reply]
Juh

**Comment by rratefiarivony** [comment]
<p>Thanks for your reply.<br>
You’re right, I’ve made mistake on uses call</p>

**Reply by tkoenig-sz** [reply]
I had the same problem. I was referencing the composite-action by pointing to it's .yaml file. Instead pointing to the directory were the action is located is the correct way to do it.
incorrect: `uses: ./.github/actions/my-composite-action/action.yaml`
correct: `uses: ./.github/actions/my-composite-action`

**Reply by mihaigalos** [reply]
Hi @rratefiarivony @tkoenig-sz, any chance that you post a reference to your config files?

**Reply by tkoenig-sz** [reply]
Unfortunately not. We moved completely using workflows only, because there was actually no need to define an action... Sorry @mihaigalos . But the way I described it above worked fine for us in the past 👍

**Reply by rratefiarivony** [reply]
Hi mihaigalos, me too. The error was because of path error and like @tkoenig-sz said, it worked in the past.

**Reply by mihaigalos** [reply]
How did you structure your calls? Here's what I currently have:

Consumer side:
```yaml
name: consumer-action
on:
  push:
jobs:
  build:
    uses: central_repo/.github/workflows/sign.yaml@main
```

Reusable workflow side - `central_repo/.github/workflows/sign.yaml`:
```yaml
name: sign
on:
  workflow_call:
jobs:
  sign:
    uses: ./.github/actions/sign@main
```

Composite action (same repo) - `central_repo/.github/actions/sign/action.yaml`:
```yaml
name: sign
inputs:
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Step1
      run: |
        echo Hello World
```

This produces the following error:
```
Invalid workflow file
error parsing called workflow "central_repo/.github/workflows/sign.yaml@main": invalid value workflow reference: references to workflows must be rooted in '.github/workflows'
```

I also suspect I need to somehow check out the repo in the workflow, before calling the action (this is currently done in the action but might be a chicken-and-egg problem).

**Reply by mihaigalos** [reply]
I got it runing. In the above yamls, I needed a checkout in the reusable workflow like I suspected (in `central_repo/.github/workflows/sign.yaml`).

This I added under a steps element before the uses element already present.

**Comment by rfyffe-mgmresorts** [comment]
Hi [mihaigalos](https://github.com/mihaigalos) - I have the same issue as you mention. I already have the checkout but still getting the issue:

**Composite action:**

```yaml
# .github/actions/set-vars/action.yml

name: 'set-vars'
description: 'Set global workflow variables'

inputs:
  APP_ENVIRONMENT: 
    required: true
    description:

outputs:
  BUILD_DATE: 
    value: ${{ steps.set-workflow-vars.outputs.BUILD_DATE }}

runs:
  using: "composite"
  steps:
    - name: Set workflow variables
      id: set-workflow-vars
      shell: bash
      run: |
        ...
        ....
```

**Re-usable workflow:**

```yaml
# .github/workflows/ci.yml

name: Continuous Integration
run-name: "(CI) ${{ github.event.head_commit.message }}"

on:
  workflow_call:
    inputs:
      APP_ENVIRONMENT: 
        required: true
        description:

env:
  AUTH_TOKEN: ${{ secrets.AUTH }}

jobs:
  setup:
    name: Set variables
    runs-on: ubuntu-latest

    outputs:
      BUILD_DATE: ${{ steps.workflow-vars.outputs.BUILD_DATE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          ref: main
          fetch-depth: 3

      - name: Set global workflow variables
        id: workflow-vars
        uses: ./.github/actions/set-vars
```

**Calling Workflow:**

```yaml
name: Continuous Integration
run-name: "(CI) ${{ github.event.head_commit.message }}"

# The CI workflow will only run on the main branch.
on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: {ORG}/{REPO}/.github/workflows/ci.yml@main
    with:
      APP_ENVIRONMENT: ${{ vars.APP_ENVIRONMENT }}
    secrets: inherit  
```

This currently only works if I have the same actions in the calling repository, otherwise, I get the error:

`Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/{CALLING_REPOSITORY_NAME}/.github/actions/set-vars@main'. Did you forget to run actions/checkout before running your local action?`

**Reply by mihaigalos** [reply]
Hi @rfyffe-mgmresorts,

You will need to check out the repo containing the composite separately.

This is because the context of the checkout is that of the caller, not the reusable. You will also need a token, as the credentials used in the caller are not enough.

I suggest you add:
```yaml
    - name: Checkout central reusable repo
      uses: actions/checkout@v3
      with:
        repository: orga/repo
        token: ${{ secrets.GH_TOKEN }}
        path: orga/repo
```

And then call it with:
```yaml
    - name: Set global workflow variables
      uses: ./orga/repo/.github/actions/set-vars
```
