### DISCUSSION TITLE
Reusable workflows and external script files

### DISCUSSION THREAD

**Discussion by jacek-jablonski** [community/community#25294] [Actions]
<p>Hi,<br>
I would like to embed python script file inside reusable workflows’ repository. It seems that this file is not available just by stating <code>using</code> directive. Do I have to check out script files if I need to use them? Or is there any other way I should follow?</p>

**Comment by ajaykn** [comment, marked as answer]
<p><a class="mention" href="/jacek-jablonski">@jacek-jablonski</a><br>
Yes we need to explicitly checkout the repo in which python files exists.</p>

**Reply by PetterGs** [reply]
But how do you actually set the path to the script file you checked out?

**Reply by chidi-ekeoma** [reply]
Hi, did you manage to solve this?

**Reply by PetterGs** [reply]
```
on:
  workflow_call:
    secrets:
      WORKFLOW_GIT_TOKEN:
        description: "Personal access token with repo scope"
        required: true
env:
  example-repo: "example-repo"
  
jobs:
  deploy:
    name: Funky example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow scripts
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.repository.owner.login}}/workflows
          ref: master
          token: ${{ secrets.WORKFLOW_GIT_TOKEN }}
          path: ${{ env.example-repo }}
          
       - name: Do funny stuff with python
        run: |
          python ${{ env.example-repo }}/scripts/funny_script.py

```
