### DISCUSSION TITLE
All jobs in workflow on one particular runner

### DISCUSSION THREAD

**Discussion by rsolovev** [community/community#25311] [Actions]
<p>If I have 2 self-hosted runners matching the tags for all the steps within the workflow, is it possible for jobs to be assigned to different runners (i.e steps 1-2 on one machine, 3-4 on other). Sequence of steps is defined (i.e <code>needs: build</code>, etc.). If so, how can I avoid switching between idle runners between steps?</p>

**Comment by BrightRan** [comment, marked as answer]
<p><a class="mention" href="/rsolovev">@rsolovev</a>,</p>
<p>In the workflow, once a runner is assigned to a job, all the steps in this job run only on this runner, and you are not able to assign another runner to some of the steps.</p>
<p>If you wants to assign special self-hosted runners to different jobs in the workflow, you can add different labels for each self-hosted runner to distinguish them. Then you can assign special self-hosted runner to each job according to the different labels.</p>
<p>To view more details, you can see the docs below:<br>
<a href="https://help.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#using-custom-labels-to-route-jobs" class="onebox" target="_blank" rel="nofollow noopener">https://help.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#using-custom-labels-to-route-jobs</a></p>

**Comment by stephan-rohr** [comment]
I have a similar issue as @rsolovev. I have setup a workflow with multiple dependent jobs, e.g.,

job1 -> job2 -> job3 -> ...

Is it possible to enforce that **all** jobs of a single workflow are scheduled on the same runner? I have multiple runners which could potentially run the workflow but the jobs have dependencies which requires them be be run in order on the same runner.

I saw the possibility to  add custom labels but this does not sound like a solution to me as both runners are potentially capable of running the workflow.

**Reply by chpoit** [reply]
yeah, it's quite silly to have your deploy action suddenly jump on a different runner on a different machine, I don'T want to have to rebuild the app for the deploy workflow, and I don't want to have the deploy workflow to be a step in another workflow, because sometimes the internet connection blips out and you want to restart the deploy asap.

We really need to have a workflow option called something like "force-single-runner"

**Reply by ShavaShav** [reply]
I also have a similar use case. A 'force-single-runner' option would be ideal. 

Other solutions are too cumbersome, such as uploading artifacts in build job, and downloading them in the dependant job. Or refactoring workflow so that all jobs are represented as steps in a single job - which for my use cases would involve a lot of conditionals and templating. I really just want all of the jobs to run sequentially on the same machine.

**Reply by DawidNiezgodka** [reply]
This is still impossible, isn't it?

**Reply by bhavzie** [reply]
Any updates on this?

**Reply by GeorgiiKrikun** [reply]
What you can do is to give each runner the name and the label that corresponds to its name. Then, you can get the runner name (which will serve as a label for subsequent jobs) from the environment like that:

```
  establish-job-runner:
    name: Get a  containerised runner name to use for this workflow
    runs-on: [self-hosted, another-label-you-use-to-select-runner]
    outputs:
     established-runner: ${{ runner.name }}
    steps:
      - run: echo "selected runner = ${{ runner.name }}"
```

Then, in any following jobs you do:
```
  checkout-repository:
    name: Checkout repository
    needs:
      - establish-job-runner
    runs-on: ${{ needs.establish-job-runner.outputs.established-runner }}
```
