### DISCUSSION TITLE
Matrix variable does not work in needs keyword

### DISCUSSION THREAD

**Discussion by pmatos** [community/community#25364] [Actions]
<p>I have a build matrix over a certain amount of build types. Then I want to create a job that tests those builds but each test job depends on the build of the same type so I tried:</p>
<pre><code>test:
  strategy:
    matrix:
      type: [normal, extra, nox]
  needs: build-${{ matrix.type }}
...
</code></pre>
<p>However this results in an error saying</p>
<pre><code>Unrecognized named-value: 'matrix'.
</code></pre>
<p>Is there a way to create a template like this given we cannot templatize the needs keyword?</p>

**Comment by Yanjingzhu** [comment, marked as answer]
<p>Github workflow yml doesn’t support use ${{matrix.xx}} in needs keyword. I would suggest you to specific all jobs name into the matrix job &gt; needs keyword.</p>
<p>For example， you have jobs: build-normal , build-extra and build-nox.</p>
<p>In test job with matrix, set</p>
<pre><code>needs: [build-normal, build-extra, build-nox]
</code></pre>
<p>Then the matrix jobs will start after all the dependences jobs completed.</p>

**Comment by pmatos** [comment]
<p>That will work but it’s not perfect as it will delay the workflow since if build-normal is faster to run than build-extra, test-normal should start straight after build-normal and not only after all build types have finished. I understand this is a limitation and therefore will accept your answer.</p>

**Comment by joshjohanning** [comment]
<p>You can simplify it to just specify needs: [build], but yes I haven’t found out a way to for it to start the next job until ALL of the matrix jobs have complete.</p>
<p>Has anyone else? </p>

**Comment by D4nte** [comment]
<p>Hum, I am confused and I am getting a different behaviour where GitHub Action waits for all builds to be finished before moving.</p>
<p><a href="https://github.com/comit-network/comit-rs/runs/611097751?check_suite_focus=true" rel="nofollow noopener">https://github.com/comit-network/comit-rs/runs/611097751?check_suite_focus=true</a></p>
<p>As you can see here: <a href="https://github.com/comit-network/comit-rs/blob/924964c5ec07aa189d885ad36dd5e60f7166f76e/.github/workflows/ci.yml#L94" rel="nofollow noopener">https://github.com/comit-network/comit-rs/blob/924964c5ec07aa189d885ad36dd5e60f7166f76e/.github/workflows/ci.yml#L94</a></p>
<p>I have <code>needs: build</code></p>
<p>When I actually would like, similar to OP, to start the second step whenever the first step is done for a given value in the matrix.</p>

**Comment by reitzig** [comment]
<p>Same confusion over here. Just because the Windows runner is slow I shouldn’t have to wait for test feedback on the Linux runners. :confused:</p>
<p>In fact, why can’t we set a strategy/matrix for the whole workflow? That could implicitly solve this issue (in some cases), since then (or so I would imagine) all job names are scoped to the current matrix entry.</p>

**Comment by ssbarnea** [comment]
3 years later and we still do not have an answer.

**Comment by mortalisk** [comment]
It would be really useful to be able to start linux tests before the very slow mac runners are done. Is there any way to make that work?

**Reply by ChristopherHX** [reply]
Maybe with reusable workflows, here is an example what I mean

./.github/workflows/main.yml
```yaml
on: push
name: build and test
jobs:
  build-and-test:
    strategy:
      matrix:
        os:
        - windows
        - linux
        - macOS
    uses: ./.github/workflows/build-and-test.yml
    with:
      build-config: ${{ tojson(matrix) }}
```
.github/workflows/build-and-test.yml
```yaml
on:
  workflow_call:
    inputs:
      build-config:
        type: string
jobs:
  build:
    strategy:
      matrix:
        include:
        - ${{ fromjson(inputs.build-config) }}
    runs-on: ubuntu-latest
    steps:
    - run: echo "$MATRIX"
      env:
        MATRIX: ${{ tojson(matrix) }}
  test:
    needs: build
    strategy:
      matrix:
        include:
        - ${{ fromjson(inputs.build-config) }}
    runs-on: ubuntu-latest
    steps:
    - run: echo "$MATRIX"
      env:
        MATRIX: ${{ tojson(matrix) }}
```

This example imports the global matrix configuration into the `build` and `test` jobs, so you can use `runs-on: ${{ matrix.os}}` in the `build` and `test` jobs.

The test job for linux only depends on the build job for linux and are run truly parallel with static needs.

_If you are using GHES, matrix strategy for reusable workflows might be still unavailable and you have to wait for a GHES upgrade_
