### DISCUSSION TITLE
New action triggering as unknown event - unnamed workflow by ghost instead of adding this into the same action result

### DISCUSSION THREAD

**Discussion by fahadshehzada** [community/community#25377] [Actions]
<p>Getting an issue while executing Github action, it creates a new action named unknown event - unnamed workflow by ghost instead of adding this into the same action result. [See screenshots below]</p>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/7/79ecad76207310f77b20d41b80eae72bd3db5d78.png" data-download-href="/uploads/short-url/hoAQU7o1SJeDsDePRgF6li5COzm.png?dl=1" title="image" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/61680750/181090690-374ac9bb-08d1-4859-903c-aae874987c24.png" alt="image" data-base62-sha1="hoAQU7o1SJeDsDePRgF6li5COzm" width="690" height="392" srcset="https://aws1.discourse-cdn.com/github/optimized/2X/7/79ecad76207310f77b20d41b80eae72bd3db5d78_2_690x392.png, https://aws1.discourse-cdn.com/github/optimized/2X/7/79ecad76207310f77b20d41b80eae72bd3db5d78_2_1035x588.png 1.5x, https://aws1.discourse-cdn.com/github/optimized/2X/7/79ecad76207310f77b20d41b80eae72bd3db5d78_2_1380x784.png 2x" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/7/79ecad76207310f77b20d41b80eae72bd3db5d78_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">image</span><span class="informations">1553×883 51.1 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>
<p>This is my .yml file and its triggering through Jest Github Action Reporter</p>
<p>name: Pull Requests CI</p>
<p>on: [pull_request]</p>
<p>jobs:<br>
test:<br>
name: Test<br>
runs-on: ubuntu-latest<br>
strategy:<br>
matrix:<br>
service: [<br>
— All services goes here<br>
]</p>
<p>steps:</p>
<ul>
<li>
<p>name: Check if service has changed<br>
uses: actions/github-script@0.9.0<br>
id: service-changed<br>
with:<br>
result-encoding: string<br>
script: |<br>
### Logic part here</p>
</li>
<li>
<p>uses: actions/checkout@v2</p>
<h3>Logic part here</h3>
</li>
<li>
<p>name: Setup Node<br>
— Logic part here</p>
</li>
<li>
<p>name: Login to npm repo<br>
— Logic part here</p>
</li>
<li>
<p>name: Yarn Install<br>
— Logic part here</p>
</li>
<li>
<p>name: Lint and Prettify<br>
— Logic part here</p>
</li>
<li>
<p>name: Build<br>
— Logic part here</p>
</li>
<li>
<p>name: Yarn Test<br>
— Logic part here</p>
</li>
<li>
<p>name: Yarn E2E<br>
— Logic part here</p>
</li>
<li>
<p>name: Jest Github Action Reporter<br>
uses: IgnusG/jest-report-action@v2.3.2<br>
if: <span class="math">{{ steps.service-changed.outputs.result == 'true' &amp;&amp; (success() || steps.unit-test.outcome == 'failure' || steps.e2e-test.outcome == 'failure') }}
with:
  working-directory: </span>{{ matrix.service.dir }}<br>
access-token: ${{ secrets.GITHUB_TOKEN }}<br>
run-name: test<br>
check-name: Test</p>
</li>
</ul>

**Comment by dbalcomb** [comment, marked as answer]
<p>Hi <a class="mention" href="/fahadshehzada">@fahadshehzada</a>,</p>
<p>This issue has popped up a few times now for various actions. The issue is that the action you are using creates a check run with annotations on the commit SHA used by the workflow. However in a workflow triggered via a pull request this is actually a merge commit that doesn’t exist outside of the workflow.</p>
<p>I have added a comment with a fix to the issue you made over at the <a href="https://github.com/IgnusG/jest-report-action/issues/33#issuecomment-639889546" rel="nofollow noopener">IgnusG/jest-report-action</a> repository.</p>

**Comment by fahadshehzada** [comment]
<p>Thanks for the fix. Really appreciated the solution</p>

**Comment by fahadshehzada** [comment]
<p>My issue is resolved now</p>

**Comment by nimeshmaharjan1** [comment]
I hope its relevant here. The issue I am currently facing is I create a PR from my fork repo into the upstream repo what I wanted is the e2e tests to run after a preview deployment but from the fork PR it says unkown event

but it works for the branches in the upstream repo

I think I understand why this behaviour is occuring but is there a way to fix this?

![image](https://github.com/user-attachments/assets/606cced6-47f5-44bd-ae39-b20e02f3a697)

the below is my e2e.yml inside .github/workflows

```
# Using pnpm & Node v20
name: End-to-end testing

on:
  deployment_status:

jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    timeout-minutes: 60
    runs-on: ["self-hosted"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Log Deployment Status
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Deployment Status: ${{ github.event.deployment_status.state }}"
          echo "Deployment Environment: ${{ github.event.deployment_status.environment }}"
          echo "Deployment URL: ${{ github.event.deployment_status.environment_url }}"
          echo "Echoing successful deployment message."
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        env:
          NEXT_PUBLIC_APP_URL: ${{ github.event.deployment_status.environment_url }}
        run: pnpm exec playwright test

      - name: All test artifacts
        if: always()
        run: |
          mkdir -p test-artifacts
          cp -r playwright-report test-artifacts/
          cp -r test-results test-artifacts/

      - name: Upload combined test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-artifacts/
          retention-days: 30
```
