### DISCUSSION TITLE
Trigger a github workflow if it matches a particular comment in the Pull Request

### DISCUSSION THREAD

**Discussion by uditgaurav** [community/community#25389] [Actions]
<p>I want to trigger a workflow if it matches a particular comment (string) in a pull request.<br>
So let suppose if I comment on a pull request <code>/support</code> then the GitHub action should get a trigger.<br>
Comment Like:<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/0/0b7d1a7bf6bb621e94a0b49c86f5722864285c6f.png" data-download-href="/uploads/short-url/1DDhFSHK7DelWAVuQHG56FJiyMD.png?dl=1" title="Screenshot from 2020-06-02 20-29-43" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/35391335/181090731-fbe5f071-d27e-4f95-9437-d01410196b83.png" alt="Screenshot from 2020-06-02 20-29-43" data-base62-sha1="1DDhFSHK7DelWAVuQHG56FJiyMD" width="690" height="98" srcset="https://aws1.discourse-cdn.com/github/optimized/2X/0/0b7d1a7bf6bb621e94a0b49c86f5722864285c6f_2_690x98.png, https://aws1.discourse-cdn.com/github/original/2X/0/0b7d1a7bf6bb621e94a0b49c86f5722864285c6f.png 1.5x, https://aws1.discourse-cdn.com/github/original/2X/0/0b7d1a7bf6bb621e94a0b49c86f5722864285c6f.png 2x" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/0/0b7d1a7bf6bb621e94a0b49c86f5722864285c6f_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">Screenshot from 2020-06-02 20-29-43</span><span class="informations">826×118 12 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>
<p>If the action receives /support comment if should trigger the workflow which is running some command say echo “Hello World”<br>
and if I comment  /test then it should run some different commands like … echo “test”</p>

**Comment by weide-zhou** [comment, marked as answer]
<p>Hi <a class="mention" href="/uditgaurav">@uditgaurav</a>,</p>
<p>There is not a specific event which only monitor the pull request event, you can use ‘issue_comment’ instead, it will monitor comment for both issue and pull request. In the job level, use if expression to filter the comment, exclude the comments from issue.<br>
Code sample as below:</p>
<pre><code class="lang-auto">name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 job01:
   if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: [ubuntu-latest]
   steps:
     - name: say hello
       if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
       run: |
         echo say hello
     - name: test
       if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
       run: |
         echo test
</code></pre>
<p>I tried on my repo, and it works fine.<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/2/2a7a916dcaca48bf235fb08d42f38a0dc4ad78d0.png" data-download-href="/uploads/short-url/63MEAwoBiNVdQVzQkVNkzBlmUxO.png?dl=1" title="pullrequestcomment" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/52772761/181090732-c1a1f63c-7d2a-4e8e-803a-6b38efc4bc26.png" alt="pullrequestcomment" data-base62-sha1="63MEAwoBiNVdQVzQkVNkzBlmUxO" width="602" height="499" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/2/2a7a916dcaca48bf235fb08d42f38a0dc4ad78d0_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">pullrequestcomment</span><span class="informations">855×710 33 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>
<p>Thanks</p>
<p>Note: please use issue_comment in default branch,eg: master branch.</p>

**Reply by JackelynOliveira** [reply]
As [per the documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only), there's another way to check if the comment was done on a PR or on an issue:
```
name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
job01:
if: ${{ github.event.issue.pull_request }}    # <--- The other way to compare if it's on a PR or on an issue
runs-on: [ubuntu-latest]
steps:
...
```

**Reply by swap357** [reply]
This however will flood the Actions tab with workflow checks on ANY comment, isn't it ? as the check here happens at job level not trigger definition.

**Comment by swathida-byte** [comment]
```
name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
 job01:
   if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: [re-centos7]
   steps:
    - name: say hello
      if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
      run: |
       echo say hello
    - name: test
      if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
      run: |
       echo test
 ```
    I'm using this yaml file to trigger actions when commented on pull-request, jobs are not getting triggered 
      Do I need to enable anything for this to get triggered on a comment?
