### DISCUSSION TITLE
Issues reading diff from within action

### DISCUSSION THREAD

**Discussion by renata-slalom** [community/community#25400] [Actions]
<p>Hello! I’m trying to obtain a diff from my action on a private repo and I’m using this piece of code here: <a href="https://github.com/actions/github-script#download-data-from-a-url" rel="nofollow noopener">https://github.com/actions/github-script#download-data-from-a-url</a></p>
<p>It looks a lot like the example:</p>
<pre><code class="lang-auto">diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result.data)
</code></pre>
<p>It’s not working, unfortunately. For some reason the token is not authenticating and I’m receiving a 404 when making that request:</p>
<pre><code class="lang-auto">RequestError [HttpError]: Not Found
##[error]Unhandled error: HttpError: Not Found
    at /home/runner/work/_actions/actions/github-script/v1/dist/index.js:9320:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v1/dist/index.js:), &lt;anonymous&gt;:4:16)
    at async main (/home/runner/work/_actions/actions/github-script/v1/dist/index.js:) {
  name: 'HttpError',
  status: 404,
  headers: {
    'cache-control': 'no-cache',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    'content-type': 'text/plain; charset=utf-8',
    date: 'Xxx, 00 XXX 2020 00:00:00 GMT',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'X-PJAX, Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-request-id': 'BLABLABLA',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'GET',
    url: 'https://github.com/myrepo/pull/123.diff',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit.js/16.43.1 Node.js/12.13.1 (Linux 5.3; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
</code></pre>
<p>What can I fix to get the full diff? Thanks in advance.</p>

**Comment by weide-zhou** [comment]
<p>Hi <a class="mention" href="/renata-slalom">@renata-slalom</a>,</p>
<p>The error is due to the repository is private, it’s failed to request(GET) from  ‘<a href="https://github.com/myrepo/pull/123.diff" rel="nofollow noopener">https://github.com/myrepo/pull/123.diff</a>’ directly.</p>
<p><code>github</code> object (eg: github.request()) will access the Octokit API, and headers and other defaults are already set. Please check the doc here for more details: <a href="https://github.com/octokit/request.js/#request" rel="nofollow noopener">https://github.com/octokit/request.js/#request</a>.<br>
<img src="https://user-images.githubusercontent.com/52772761/181090764-56875992-0e0b-4fe5-8536-e969ed0e7866.png" alt="errorget" data-base62-sha1="9uwVSMiOSCxUCDjnrxR2WBd3Gcy" width="671" height="443"><br>
According to the solution <a href="https://github.community/t/get-pull-request-diff-from-api/13790/3">here</a>, you can set header ’ “Accept: application/vnd.github.v3.diff”’ and use Pull_request URL to get the diff for your script.</p>
<p>Or directly use below command to get diff:</p>
<pre><code class="lang-auto">curl -i --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header "Accept: application/vnd.github.v3.diff" https://api.github.com/repos/weide-zhou/ticket13/pulls/97
</code></pre>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/5/5248b4840ac7d8317bd73d638bf3ddeb881c17cf.png" data-download-href="/uploads/short-url/bJUVcyhI10Ro7dcOCZZGzMz367J.png?dl=1" title="getdiff" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/52772761/181090765-9b18a801-ffc7-4c0f-ab70-427a3919526a.png" alt="getdiff" data-base62-sha1="bJUVcyhI10Ro7dcOCZZGzMz367J" width="690" height="282" srcset="https://aws1.discourse-cdn.com/github/optimized/2X/5/5248b4840ac7d8317bd73d638bf3ddeb881c17cf_2_690x282.png, https://aws1.discourse-cdn.com/github/optimized/2X/5/5248b4840ac7d8317bd73d638bf3ddeb881c17cf_2_1035x423.png 1.5x, https://aws1.discourse-cdn.com/github/original/2X/5/5248b4840ac7d8317bd73d638bf3ddeb881c17cf.png 2x" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/5/5248b4840ac7d8317bd73d638bf3ddeb881c17cf_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">getdiff</span><span class="informations">1186×486 72 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div><p></p>
<p>Thanks.</p>

**Comment by jclem** [comment, marked as answer]
<p>This is my bad! The example shouldn’t be in the github-script README as-is. <a class="mention" href="/weide-zhou">@weide-zhou</a> is correct that the right way of getting this is via the GitHub API with the diff content type in the “Accept” header.</p>

**Comment by asudhak** [comment]
Is there a way to do this using github.request() ? I notice that when I set the headers, the underlying REST client does not set the correct headers.

**Reply by philip-gai** [reply]
Unfortunately not with the current version (v6.1.1) of `actions/github-script`. There is another way, though, that might feel a little hacky but works using the underlying octokit built with https://github.com/octokit/action.js.

Here is a working example I tested on a private repository:

```yml
# Displays the diff on a PR using the Octokit provided by @octokit/action
name: Diff
on: pull_request
jobs:
  diff:
    name: Diff
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: npm install @octokit/action
      - name: Get diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node -e "(async () => {
            const { Octokit } = require('@octokit/action');
            const octokit = new Octokit();
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const pull_number = process.env.GITHUB_REF.split('/')[2];
            const result = await octokit.rest.pulls.get({
              owner: owner,
              repo: repo,
              pull_number: pull_number,
              mediaType: {
                format: 'diff',
              },
            });
            console.log(result.data)
          })();"
```
