### DISCUSSION TITLE
You can now use images from private registries in job and service containers

### DISCUSSION THREAD

**Discussion by AndreaGriffiths11** [community/community#25478] [Actions]
<p>Hi Friends, passing on some news from our changelog :space_invader:</p>
<p>Job and Service containers in GitHub Actions allow you to containerize your CI environment and make databases, caches, or other services available to your tests. Previously those containers had to come from a public container registry which limited the usefulness for some customers. Additionally, we had numerous requests from the GitHub community forums for private registry support.</p>
<p>Here’s an example of using private images from Docker Hub and GitHub Container Registry:</p>
<pre><code class="lang-auto">jobs:
  build:
    container:
      image: octocat/ci-image:latest
      credentials:
        username: mona
        password: ${{ secrets.docker_hub_password}}
    services:
      db:
        image:  ghcr.io/octocat/testdb:latest
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_password }}
</code></pre>

**Comment by ThirdEyeRose** [comment, marked as answer]
<p>For more information, please check out our <a href="https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/about-github-packages#about-scopes-and-permissions-for-github-container-registry">help article About scopes and permissions for GitHub Container Registry</a>.</p>

**Comment by clintonb** [comment]
I'm quite late to the party, and have struggled with trying to use a private container in the same organization as a service image. Many docs mention `secrets.ghcr_password`, but none mention how to create the password or whether it is automatically generated.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-jobsjob_idservicesservice_idcredentials uses completely different credentials.

I ultimately needed the following:

```yaml
jobs:
  foo:
    runs-on: ubuntu-latest

    # Permissions are crucial!
    permissions:
      contents: read
      packages: read

    services:
      postgres:
        image: ghcr.io/${{ github.repository_owner }}/postgres:15
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

**Reply by iandees** [reply]
I was having a hard time with this, too. The workflow I was adding in [this PR](https://github.com/openaddresses/openaddresses/pull/6859) uses a private image generated from [this repo](https://github.com/openaddresses/batch-machine). I tried the permissions + credentials suggested by clintonb, but was still getting "denied" at image pull in the workflow.

To solve, I had to set `credentials.username` to `$` (keep the github token as password), change `permissions.packages` to `write`, and add read permissions to this private image from the `openaddresses/openadresses` repo as described in [this doc](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#authenticating-to-package-registries-with-repository-scoped-permissions) for publishing the image.

**Reply by GunnarMorrigan** [reply]
This actually does not work for me:

```
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container: 
      image: ghcr.io/dnv-smartcableguard/app:pr-1
      credentials:
        username: ${{ github.repository_owner }} 
        password: ${{ secrets.GITHUB_TOKEN }}
```
and neither does:
```
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container: 
      image: ghcr.io/dnv-smartcableguard/app:pr-1
      credentials:
        username: "$"
        password: ${{ secrets.GITHUB_TOKEN }}
```

A bit sad to see that this is so difficult. Feels like Github pipelines are often not easy at all.

**Comment by GunnarMorrigan** [comment]
I solved my issue.

I don't think you need write package permissions if you are only doing reading from the package registry.

There is a package settings page that is not listed anywhere in the settings page. (Which i think is really stupid at least list it)
https://github.com/orgs/<ORG>/packages/container/<CONTAINER_NAME>/settings

Add the repo you want to access it from there with read permissions.

The dollar sign as username does not work for me.

```
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container: 
      image: ghcr.io/${{ github.repository_owner }}/container:label
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        ...
    steps:
      - uses: actions/checkout@master
      - name: build.sh
        run: ./build.sh
```
