### DISCUSSION TITLE
How to checkout a private submodule from a github action?

### DISCUSSION THREAD

**Discussion by jaredly** [community/community#25516] [Actions]
<p>Apparently the $GITHUB_TOKEN only has permissions for the current repo (which makes sense) – is there a way to allow access to another private repo?</p>
<p>It’s currently failing:</p>
<pre><code>Submodule 'secrets' (git@github.com:{}/{}.git) registered for path 'secrets'
Cloning into '/home/runner/work/{}/{}/secrets'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:{}/{}.git' into submodule path '/home/runner/work/{}/{}/secrets' failed
Failed to clone 'secrets'. Retry scheduled
</code></pre>

**Comment by oldskool** [comment, marked as answer]
<p>You should be able to set a <a href="https://github.com/actions/checkout/blob/f6ce2afa7079cb075a124c93c79d61779d845782/action.yml#L8" rel="nofollow noopener">custom token</a> when using the checkout action. So, if you have a token that you know will have access to both your current repo as well as the submodule(s), you can run a step like:</p>
<pre><code>- uses: actions/checkout@v1
  with:
    token: ${{ secrets.ACCESS_TOKEN }}
    submodules: true
</code></pre>
<p>Which would use a secret called “ACCESS_TOKEN” (which you should then create in the repository that runs your workflow) to pull the repositories.</p>

**Comment by jaredly** [comment]
<p>Cool yeah that makes sense. I only wish there were a way to generate a custom token with restricted access to only a couple of repos :confused: I guess I’ll probably make a bot account with limited permissions and go with that.</p>
<p>Thanks!</p>

**Comment by Stanzilla** [comment]
<p>Sadly they broke that with actions@v2 so beware when updating! You now have to use something like this if you want to keep using SSH URLs instead of HTTPS:</p>
<pre><code>steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          repository: yourPrivateOrg/yourPrivateRepo
          token: ${{ secrets.ACCESS_TOKEN }}
          path: yourPrivateRepo
</code></pre>

**Reply by yurist38** [reply]
I've just had a few hours of debugging and found out that THE TOKEN MUST HAVE AN EXPIRATION DATE! Otherwise, it won't work, be careful.

**Reply by nobelwong** [reply]
Legend!

**Comment by dpmcgabriel** [comment]
How to generete the token btw?

**Reply by yurist38** [reply]
You need to go to `Settings` -> `Developer Settings` -> `Personal access tokens` and then either `Fine-grained tokens` or `Tokens (classic)` (I still use classic ones mostly)

**Comment by asbjornu** [comment]
As per https://github.com/actions/checkout/issues/287#issuecomment-1830291196, it is now possible to use `actions/create-github-app-token` to create a token usable by `actions/checkout` as such:

```yaml
jobs:
  test-submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Get token from Github App
      uses: actions/create-github-app-token@v1
      id: app_token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PEM }}
        # owner is required, otherwise the creds will fail the checkout step
        owner: ${{ github.repository_owner }}

    - name: Checkout from GitHub
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ steps.app_token.outputs.token }}
```

It feels a bit over the top to create an entire GitHub App for this purpose, but it works and is more robust than a personal access token.

**Reply by sheershoff** [reply]
the owner part was not obvious for me, thank you!

**Comment by parth-hb** [comment]
I faced same issue and struggled atleast 2 days to make it work. If you're also struggling with the same, here's a reliable and tested fix using Deploy Keys.

### Steps

1. **Generate an SSH Key**
   ```bash
   ssh-keygen -t rsa -b 4096 -C "ci-access" -f submodule_deploy_key
   ```

2. **Add Public Key to Submodule Repo**
   - Go to your submodule repo (e.g., `my-org/my-redux-store`)
   - Navigate to: `Settings` → `Deploy Keys`
   - Click **"Add deploy key"**, paste the public key from `submodule_deploy_key.pub`
   - Make sure to enable **Allow write access** if required

3. **Add Private Key to Main Repo Secrets**
   - Go to your main repo (`my-org/my-app`)
   - Add a secret like `SUBMODULE_SSH_KEY`
   - Paste contents of `submodule_deploy_key` (the private key)

4. **Modify Workflow**
   Before updating submodules, add:
   ```yaml
   - name: Checkout main repo (no submodules)
     uses: actions/checkout@v4
     with:
        submodules: false
          
   - name: Setup SSH for submodules
     run: |
       mkdir -p ~/.ssh
       echo "${{ secrets.SUBMODULE_SSH_KEY }}" > ~/.ssh/id_rsa
       chmod 600 ~/.ssh/id_rsa
       ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Init and update submodules
      run: |
       git submodule sync
       git submodule update --init --recursive

   ```

This should fix the common `Permission denied` or `Repository not found` errors when dealing with submodules.

---

**Works great when:**  
- You don’t want to use personal tokens  
- Better than using app tokens
- You want tight access control over a single repo  
- You prefer SSH over HTTPS
