### DISCUSSION TITLE
github-actions bot labeling trigger's not the issue labeled event

### DISCUSSION THREAD

**Discussion by korti11** [community/community#25565] [Actions]
<p>I have created an action that add labels to an issue, if a specific word is present in a commit message. Something like closing an issue from the commit message. But I found out that after the github-actions bot add the label to the issue the workflow who starts on labeling an issue did not trigger.</p>
<p>I don’t know if this is intended or it is a bug, but I would like to know this.</p>

**Comment by Yanjingzhu** [comment, marked as answer]
<p>Hi korti11,</p>
<p>This is an expected behavior. There is a limitation of workflow: <em>An action in a workflow run can’t trigger a new workflow run.</em> You can see this prompt in <a href="https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.github.com%2Fen%2Factions%2Fautomating-your-workflow-with-github-actions%2Fevents-that-trigger-workflows%23about-workflow-events&amp;data=02%7C01%7Cv-yjingz%40microsoft.com%7C2e0662f4ba334b53df3208d76f1aca43%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637100033162962610&amp;sdata=QLPdJzEzYD3gzIQ80Pc8jn4PF3SPuPHGdPtZIvdRkP0%3D&amp;reserved=0" rel="nofollow noopener">https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#about-workflow-events</a>.</p>
<p>When you use GITHUB_TOKEN in your actions, all of the interactions with the repository are on behalf of the Github-actions bot. The operations act by Github-actions bot</p>
<p>cannot trigger a new workflow.</p>
<p>I would suggest you use your own PAT when add labels to an issue.</p>
<p>Store your PAT in secrets and use ${{ secrets.PAT } in your actions.</p>
<p><img src="https://user-images.githubusercontent.com/24806478/181091840-85db667f-0eca-4b4e-8a11-c0a170912922.png" alt="add label.png" data-base62-sha1="fuXkM3HCQL8YZQNnOUIzOOSF8pK" width="532" height="263"></p>
<p>Then you can see it is you who added a label in the issue. This will trigger the other workflow which is configured:</p>
<p>on:</p>
<p> issues:</p>
<p>   types: [labeled]</p>

**Comment by korti11** [comment]
<p>Thank you very much. That worked perfectly.</p>

**Comment by flo-kn** [comment]
Seems like this solution does not work for Pull requests:

```
on:
  pull_request:
    types: [ labeled ]
    branches:
      - main
      
   ...


jobs:
  myjob:
    if: ${{ github.event.label.name == 'myLabelToTriggerWorkflow' }}
    name: myName
    uses: myuser/myrepo/.github/workflows/my-reusable-workflow.yaml@main
    with:
       github-token: "${{ secrets.PAT }}"
         ...

```

When I create a label manually it triggers. For label created with https://github.com/actions/labeler it does not. 
Any idea on that?
