### DISCUSSION TITLE
Push from Action does not trigger subsequent action

### DISCUSSION THREAD

**Discussion by Stummi** [community/community#25702] [Actions]
<p>I have an github action which sometimes pushes back to the repository, and I expect this push to trigger another action which configured with “on: push”, however this seems to not work. Is this intentional?</p>
<p>Sample repository to demonstate the issue: <a href="https://github.com/Stummi/workflow-playground/tree/master/.github/workflows" rel="nofollow noopener">https://github.com/Stummi/workflow-playground/tree/master/.github/workflows</a></p>

**Comment by weide-zhou** [comment, marked as answer]
<p>Hi Stummi,</p>
<p>Glad to hear you in GitHub Community!</p>
<p>If an action pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.</p>
<p>Please create a personal access token in repo setting(write permission accordingly), replace GITHUB_TOKEN in your ‘inc-counter.yml’, code as below, thanks.</p>
<pre><code>- name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT}}
</code></pre>
<p><img src="https://user-images.githubusercontent.com/52772761/181092713-54900728-7706-4178-91ab-3be6b3eae56e.png" alt="PAT1.png" data-base62-sha1="ymt4bv0C3MdpBXmhwXvgeuXdfn9" width="682" height="142"></p>

**Reply by creator1creeper1** [reply]
Works well. However, I wish this arbitrary limitation on GITHUB_TOKEN was removed.

**Reply by gemyago** [reply]
This limitation is significantly diminishing all the benefits that GITHUB_TOKEN brings. If I have to allocate a PAT to work around this limitation, then why would I use GITHUB_TOKEN in the first place?

**Reply by rea1shane** [reply]
RESOLVED:

As [another comment](https://github.com/orgs/community/discussions/25702#discussioncomment-3248823) and [push action doc](https://github.com/marketplace/actions/github-push#example-workflow-file) say, need add `persist-credentials: false` when checkout.

```yaml
- uses: actions/checkout@v2
  with:
    persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
```

---

ISSUE:

Did I miss something? This action can't trigger another action which run when push.

workflow file:

```yaml
name: Posts Sync

on:
  workflow_dispatch:

jobs:
  sync:
    name: Posts Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update
        run: |
          git submodule update --remote content/posts

      - name: Commit
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git commit -am "Auto updated posts" || echo "No changes to commit"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.HUGO_SITE_GIT_TOKEN }}
          branch: ${{ github.ref }}
```

**Reply by brandocomando** [reply]
Agreed. Imo the limitation on the GitHub token should be removed and those that don't want their pushes from GitHub actions to kick off workflows can go about it using the already existing commit message format to do so.

**Reply by electrovir** [reply]
Apps (like Netlify) get triggered on pushes from actions using the `GITHUB_TOKEN`. Why can't our _own_ workflows be triggered as well?

**Reply by cbruegg** [reply]
If you can't declare `persist-credentials: false` for whatever reason and don't want to hand your secret to a third-party action, here's how to clear the persisted credentials and override them just for the `git push`:

```yaml
-       name: Push
        env:
          GH_TOKEN: ${{ secrets.YOUR_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          
          git add <YOUR FILES>
          git commit -m "[github-actions] <YOUR MESSAGE>"
          
          # Clear any cached credentials and configure git to use our PAT
          # The default GITHUB_TOKEN does not trigger CI workflows, so we must use the PAT
          git config --unset-all http.https://github.com/.extraheader || true
          git config --global --unset-all credential.helper || true
          git config --local --unset-all credential.helper || true
          
          # Push with PAT in URL
          git push "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
```

**Reply by yury-s** [reply]
PAT tokens are prohibited by our org policy. This is very unfortunate limitation.

**Comment by Stummi** [comment]
<p>This helped. Thank you!</p>

**Comment by akerl** [comment]
<p>Is there a plan for removing this limitation? Providing a personal access token grants the Action far greater privileges than it needs.</p>

**Comment by xt0rted** [comment]
<p>I’m using this same workflow with a second one triggered on pull_request. Even if I use a PAT my pull_request workflow doesn’t run when commits are pushed back to the PR branch. This is an example of my workflow <a href="https://gist.github.com/xt0rted/d0eac04e15a7cea80aa974a4448defef" rel="nofollow noopener">https://gist.github.com/xt0rted/d0eac04e15a7cea80aa974a4448defef</a></p>

**Comment by xt0rted** [comment]
<p>The comments at <a href="https://github.community/t/push-from-action-even-with-pat-does-not-trigger-action/17622/6">https://github.community/t5/GitHub-Actions/Push-from-action-even-with-PAT-does-not-trigger-action/m-p/46293/highlight/true#M6505 </a>solved my issue.</p>
<p>I needed to add <em>persist-credentials: false</em> to my checkout step since it’s using v2.</p>

**Comment by ianwalter** [comment]
<p>This has been driving me CrAzY because it’s not intuitive and hard to find information about. Thank you for the workaround.</p>

**Comment by AllanOricil** [comment]
<p>it took me hours to find this post.</p>

**Comment by stovmascript** [comment]
<p>Shouldn’t adding one of these permissions (<a href="https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions" class="inline-onebox" rel="noopener nofollow ugc">Workflow syntax for GitHub Actions - GitHub Docs</a>) to the <code>GITHUB_TOKEN</code> and setting it to <code>read</code> be enough now?</p>

**Reply by ewized** [reply]
Does this work?

**Reply by creator1creeper1** [reply]
It doesn't appear to work, even with `permissions: write-all`

**Comment by ayanamist** [comment]
<p>You can set <code>token</code> argument of actions/checkout@v2 to your generated pat without using ad-m/github-push-action@master and git push it normally.</p>

**Comment by ardove** [comment]
I know this is a fairly old discussion, but I think it'd be handy to be able to get a PAT for the user who initiated the action (for actions that are triggered via the workflow_dispatch event). Seems like this would provide a better audit trail than a static personal access token of like a "service account".

**Comment by scottw-kr** [comment]
I'm not sure my configuration is exactly the same as the accepted answer, but I just wanted to post that I created an multi-job workflow that bumped and committed a package.json version number and with concurrency rules, it canceled the current workflow and started up a new one. It did this 3 times until I manually stopped the workflow.

**Comment by tanrobotix** [comment]
Thank you, it took me several hours to find the issue~

**Comment by kahootali** [comment]
This is a big issue in our flow, I need to pull my trunk branch into feature branches in my CI/CD if there are changes there, but the pipeline doesn't get triggered because of this. There can be changes in my trunk branch which when merged into feature branch can fail the build, but the pipeline wont get triggered, also using PAT is not the best of options, I want to use default token rather than creating a token and making sure it doesn't expire, securing it, etc

**Comment by chriskapp** [comment]
I have also spent some time debugging this issue. I think GitHub will not allow triggering such workflows to prevent building recursive triggering of actions. The workaround is to use a PAT with the fitting permissions. I have also found this in the documentation s.

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

s. https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Reply by LecrisUT** [reply]
They could use concurrency to limit. The same recursive issue would occur if we run manually [`gh workflow run`](https://cli.github.com/manual/gh_workflow_run) manually after the `git push`. It would make more sense for github to keep track internally of the `GITHUB_TOKEN` and hence the source of the git push and the recursive depth, rather than have us blindly improvise an endless recursive workflow ourselves.

[Here](https://github.com/search?q=%22gh+workflow+run%22+path%3A%2F%5E.github%5C%2Fworkflows%5C%2F%2F+%22git+push%22&type=code) is some inspiration for anyone wanting to abuse this

**Reply by tekumara** [reply]
NB: for the `GITHUB_TOKEN` to trigger a workflow dispatch it will need permissions `actions: write` otherwise you'll hit the dreaded:
> could not create workflow dispatch event: HTTP 403: Resource not accessible by integration

**Reply by LecrisUT** [reply]
Github seems to be very thorough in not allowing us to re-run CI workflows:
- `gh workflow run`: works, but `check` is not added to commit or PRs
- `gh pr edit --add-label`: workflow is not triggered when the label is created by `GITHUB_TOKEN`

Since Github will seemingly never listen to our requests, has anyone found an exploit to work around this, or has anyone tried any other designs to document what doesn't work?

**Reply by kehao95** [reply]
> Github seems to be very thorough in not allowing us to re-run CI workflows:
gh workflow run: works, but check is not added to commit or PRs

i m having the same issue. In my use case, I want the workflow to amend commit and push -f. But once that done the check will never be triggered,

**Comment by bennobuilder** [comment]
**As an alternative:** If you want an action to run after another action, you can also use the `repository_dispatch` event to trigger the next action. For more information, check the [GitHub documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch).

### Example

1. **First Workflow**: `.github/workflows/merge-develop-into-main.yml` (Manual trigger, `workflow_dispatch`)
    ```yaml
    name: Merge Develop into Main

    on:
      workflow_dispatch:

    jobs:
      merge:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
          
          - name: Merge develop into main
            uses: actions/github-script@v7
            with:
              script: |
                github.rest.repos.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  base: 'main',
                  head: 'develop',
                });
          
          # <<<< HERE START
          - name: Trigger Publish Workflow
            uses: actions/github-script@v7
            with:
              script: |
                github.rest.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  event_type: 'publish-trigger',
                });
          # <<<< HERE END
    ```

2. **Second Workflow**: `.github/workflows/publish.yml` (Triggered by "`publish-trigger`", `repository_dispatch`)
    ```yaml
    name: Publish

    on:
      # <<<< HERE START
      repository_dispatch:
        types: [publish-trigger]
      # <<<< HERE END

    jobs:
      publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
          
          # Add your publish steps here
          - name: Publish
            run: echo "Publishing..."
    ```

### How I updated my actions

https://github.com/inbeta-group/monorepo/commit/a710dd2ab09b68f15b843b54377d62fbb3699ba8

**Reply by LecrisUT** [reply]
The issue is that the workflow does not show up on the commit. This is a particular issue for PRs

**Reply by bennobuilder** [reply]
But if the commit is triggered by you as the actual user it should work?

and if its triggered by an action you can make use of `repository_dispatch` by creating a dispatch event (e.g. As a step after your action that committed xyz)? Only if its a third party action that commits xyz if xyz it might get a bit more challenging to create a dispatch event at the right time.

**Reply by LecrisUT** [reply]
Look at your own repo:
- 208eaf61e93be4f4a50bef1e0a5a37526636aceb was triggered by push and the CI checks are displayed
- dbe5f5e20bb33f4048a0702db10eb28d7b79594f was triggered by workflow_dispatch so no CI check is attached to the commit

The key is to try and achieve the following:
- workflow_A: triggered by pull_request, creates a commit and then triggers workflow_B
- workflow_B: must appear in the PR checks

If you can achieve that with anithing `repository_dispatch`, `wotkflow_dispatch`, third-party service, nested Matryoshka dolls of actions, services or whatevers, you will have the eternal gratitude of the hundreds of us who are tired of this ridiculous restriction

**Reply by bennobuilder** [reply]
> workflow_A: triggered by pull_request, creates a commit and then triggers workflow_B

This should be possible with the `repository_dispatch` approach. It's similar to my use-case:

I aimed to trigger the "Publish" action after manually triggering the "Initiate Publish" action.
-  "Initiate Publish": Merges `develop` branch into the `main` branch. And as you know, merging branch x into branch y via GitHub Action doesn't trigger any action listening on `on: push`.
- "Publish": Publishes packages and some other stuff

And for that use-case the `repository_dispatch` approach seems to work:

Here, I'm triggering the "Initiate Publish" workflow:
![image](https://github.com/community/community/assets/57860196/fb6d24bc-b1a9-47f4-baee-47946530b56c)

And here's the "Initiate Publish" workflow triggering the "Publish" workflow via `repository_dispatch`:
![image](https://github.com/community/community/assets/57860196/89ecc7bc-21c2-401f-a15a-97b7a9294805)

> workflow_B: must appear in the PR checks

I haven't tested whether the workflow appears in the PR checks 🤷

**Reply by LecrisUT** [reply]
> And here's the "Initiate Publish" workflow triggering the "Publish" workflow via `repository_dispatch`

I saw that, and you can do it with `workflow_dispatch` as well. This is not the issue here.

> I haven't tested whether the workflow appears in the PR checks 🤷

This is the main point, because if you have a CI with a required workflow that must pass, you will never be able to make it pass after you make a commit. An example is running `pre-commit` or [`check-dist`](https://github.com/actions/typescript-action/blob/main/.github/workflows/check-dist.yml) which make trivial fixes or re-compilations, than these do not trigger the remaining tests of your workflow. A common occurrence is that you have dependabot or renovate bumping your dependencies, than you never get to fully test these updates until you manually rebase.

`pre-commit-ci` does work because it is run as an external service, and for some reason Github is ok with allowing that to re-trigger CI runs, but they will not allow the in-house actions to do so, even though you can have the exact same issues and safe-guards in both scenarios. Our only hope is a third-party service that we can trigger from a GH action to make a commit, and the only issue there is to host a publicly available server to do just this one small task.

**Comment by LecrisUT** [comment]
I have stumbled on [`peter-evans/create-pull-request`](https://github.com/peter-evans/create-pull-request). There there is a [documentation](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs) on *actual* ways to workaround this frustrating issue. One approach there is using Github Apps and [`tibdex/github-app-token`](https://github.com/tibdex/github-app-token). It looks super promising. Wonder if a generic GH App could be created, probably as a manifest, or have a public one with hard-coded `tibdex/github-app-token` approach :thinking: 

[Here](https://github.com/pypa/cibuildwheel) is one example of that workflow in the wild :slightly_smiling_face:

**Comment by kribor** [comment]
I don't consider this issue solved. Creating manual PATs for every repo is very tedious and not scalable. Surely a flag that overrides the default behavior to not trigger on_push workflows can't be unreasonably hard to add.

**Comment by brian-smith-tcril** [comment]
I feel like there's something I'm missing here. I know `peter-evans/create-pull-request` has [documented this issue and workarounds](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs), but it seems https://github.com/TreTuna/sync-branches has no problems triggering `on: pull_request` workflows.

**Comment by hassanmehdi98** [comment]
It worked after using a PAT in the checkout action (v3)
![image](https://github.com/user-attachments/assets/8d53ff83-58ce-422b-a0ef-d8b1fd6e13f5)

**Comment by owen2** [comment]
I bet they are trying to avoid infinite loops in actions, still it's a very unexpected behavior.

**Comment by litetex** [comment]
The year is 2026 and here is still no option to work this around... 
How about adding something like a permission for this (instead of Copilot integrations everywhere)?

Btw the "workaround" of using a (personal) access token is working out really great:
A developer now has to give a (bot) account write access to the entire repository and that account can definitely [_never_](https://github.com/aquasecurity/trivy/security/advisories/GHSA-69fq-xp46-6x23. ) be compromised.

So we as developers are now forced to design a insecure system to make this work. Great!

**Comment by mhoffrog** [comment]
There is no need for a PAT token. In my case it worked to apply permission `actions: write` to the job commiting/pushing and explicitly triggering the other workflow.<br>
Only an explicit `gh workflow run` command is required to trigger the other workflow after the remote repo has been changed by the push.
Also pushing to another target branch and triggering the workflow on that branch is working.
Note that env variable GITHUB_TOKEN is set - it will be used by the `gh` CLI for authentication by default.

```yml
name: Update Repo and Trigger Deploy

on:
  workflow_dispatch:

jobs:
  update_repo:
    name: Update Repo
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow pushing and workflow triggering
    permissions:
      # actions: write required for explicit workflow triggering
      actions: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Git config
        run: |
          # Configure git user for commit
          git config user.name "GitHub CICD"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"

      - name: Change repo content
        run: |
          echo "File changed at $(date '+%H:%M:%S')." > changedFile.txt

      - name: Commit, Push and trigger Pages Deploy
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -am "Update changedFile.txt"

            echo "Push to ${GITHUB_REF_NAME}."
            git push origin "${GITHUB_REF_NAME}":"${GITHUB_REF_NAME}"

            echo "Trigger '${GITHUB_PAGES_ACTION}' on '${GITHUB_REF_NAME}'"
            gh workflow run "${GITHUB_PAGES_ACTION}" --ref "${GITHUB_REF_NAME}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_PAGES_ACTION: deploy_pages.yml
```

Target workflow:
```yml
name: Deploy Pages

on:
  push:
    branches: *

  # Allows you to explicitly triggering this workflow
  workflow_dispatch:

...
```
