### DISCUSSION TITLE
Github Actions (new) Pulling from private docker repositories

### DISCUSSION THREAD

**Discussion by yoroshikun** [community/community#25731] [Actions]
<p>Hi All,</p>
<p>I have been playing around with github actions for a around a day now and was wondering how to deal with pulling from private docker repositories for example google cloud container registry.</p>
<p>I am trying to pull from a repo like so</p>
<pre><code>- name: Download Cache
        uses: docker://gcr.io/[Project ID]/cache
</code></pre>
<p>I have authenticated in a step above using a service account however in the github actions workflow it prefers to try and pull all of the docker images before running any of the steps.<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/b/b5dad7f806e762024110537384d24de412993f7a.png" data-download-href="/uploads/short-url/pWLi8e1xtUCRDHRT7bBAaMMNrxo.png?dl=1" title="Screen Shot 2019-08-15 at 1.23.01 pm.png" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/1892447/181092911-b9fa4ae7-0cbb-4300-81f5-adf89df5d0b9.png" alt="Screen Shot 2019-08-15 at 1.23.01 pm.png" data-base62-sha1="pWLi8e1xtUCRDHRT7bBAaMMNrxo" width="690" height="373" srcset="https://aws1.discourse-cdn.com/github/optimized/2X/b/b5dad7f806e762024110537384d24de412993f7a_2_690x373.png, https://aws1.discourse-cdn.com/github/optimized/2X/b/b5dad7f806e762024110537384d24de412993f7a_2_1035x559.png 1.5x, https://aws1.discourse-cdn.com/github/optimized/2X/b/b5dad7f806e762024110537384d24de412993f7a_2_1380x746.png 2x" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/b/b5dad7f806e762024110537384d24de412993f7a_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">Screen Shot 2019-08-15 at 1.23.01 pm.png</span><span class="informations">1582×856 159 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>
<p>Any plans to support this or know of a way to support this now?</p>
<p>Any discussion will be helpful</p>

**Comment by lee-dohm** [comment]
<p>GitHub Actions currently only supports public Docker images. I can’t give an ETA or even promise if using Docker images from private repositories will become available, but I’ll pass along your feedback to the developer team.</p>
<p>Thanks for reaching out and giving us your feedback!</p>

**Comment by nelsonjchen** [comment]
<p>This is something available on Azure Pipelines as a service connection. </p>
<p><a href="https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&amp;tabs=yaml#sep-docreg" rel="nofollow noopener">https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&amp;tabs=yaml#sep-docreg</a></p>
<p>I too would be interested. It would make migrating or even hopping back between Azure Pipelines and GitHub actions much easier. </p>

**Comment by bendavies** [comment]
<p><a class="mention" href="/lee-dohm">@lee-dohm</a> might you be able to comment on whether this is under consideration at all? This is a show stopper for us, as we need to use images in our private AWS ECR repos. </p>
<p>thanks!</p>

**Comment by chrispat** [comment, marked as answer]
<p>Adding the ability to use private docker registeries for Job, Service and Step containers is something we do plan to do.  However, I don’t have an exact timeline right now.</p>

**Reply by OR13** [reply]
Is this answer still correct?

I refined the proposal from: https://github.com/orgs/community/discussions/25731#discussioncomment-3248964

In this issue here: https://github.com/actions/hello-world-docker-action/issues/15#issuecomment-1427111189

**Comment by viktorvoltaire** [comment]
<p>I solved this by having a step in my workflow that authenticates and pulls the docker image and then using a internal repo action (which doesn’t pull the image on startup) for using the private image. Not ideal but works until github adds support:</p>
<p>.github/workflow/main.yml:</p>
<pre><code>- name: Setup service account
      run: echo -n ${{ secrets.GCS }} | base64 -d &gt; token.json
    - name: gql
      uses: actions/gcloud/cli@master
      with:
        entrypoint: /bin/sh
        args: "-c \"gcloud auth activate-service-account --key-file token.json &amp;&amp; gcloud auth configure-docker &amp;&amp; docker pull gcr.io/ **** /test\""
      env:
        GOOGLE_APPLICATION_CREDENTIALS: token.json
- name: test action
uses: ./action
</code></pre>
<p>action/action.yml</p>
<pre><code>name: test action
runs:
  using: 'docker'
  image: 'docker://gcr.io/ **** /test'
</code></pre>

**Comment by robjmills** [comment]
<p>It looks like the actions/gcloud repo was archived - what should be used to replace that now?</p>

**Comment by gitfool** [comment]
<p>I also need this for private repos on both AWS ECR and Docker Hub.</p>
<p><a class="mention" href="/chrispat">@chrispat</a> is there an issue we can follow and up-vote on GitHub?</p>

**Comment by sharat** [comment]
<p>The strange issue here is, the docker:// images will be pulled right after initiating the runner, without executing the previous steps. Hence, we can’t login to the private repository.  Even if we mark the login as a separate job, the order of jobs is not respectes.</p>

**Comment by blowfishpro** [comment]
<p>This is particularly annoying because even “public” Github Packages repos require auth.  So effectively we can’t use Github on Github.</p>

**Comment by zanona** [comment]
<p>Does the same apply for GitHub registry hosted docker images under a private repository?<br>
I’d image it could inherit the permissions from the repository it’s running the workflow in? — I believe that’s how it currently works on GitLab.</p>

**Comment by robindegen** [comment]
<p>My main concern is that the Visual Studio build tools eula requires me to make the docker image with my configuration private. I am willing to make it public but i’m not allowed to do that. So either Visual Studio build tools should allow being hosted on public dockers or github should allow private containers for this usecase. I find that Visual Studio is rarely configured correctly for my usecase (cutting edge c++), as usually only .NET things are taken into account.</p>

**Comment by missedone** [comment]
<p>If you’re using AWS ECR, and have self-hosted github runner, you can consider docker-credential-ecr-login (aka, the Docker credentials plugin)<br>
</p><aside class="onebox allowlistedgeneric">
  <header class="source">
      <img src="https://a0.awsstatic.com/main/images/site/fav/favicon.ico" class="site-icon" width="16" height="16">
      <a href="https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/" target="_blank" rel="nofollow noopener" title="02:24PM - 14 September 2016">Amazon Web Services – 14 Sep 16</a>
  </header>
  <article class="onebox-body">
    <div class="aspect-image" style="--aspect-ratio:690/345;"><img src="https://user-images.githubusercontent.com/555134/181092918-c0dad135-4792-4967-8bf8-259fbfb577f4.png" class="thumbnail" width="690" height="345" srcset="https://aws1.discourse-cdn.com/github/optimized/2X/d/d5d04096a36fd3a41a92273bfcdb5564c84be514_2_690x345.png, https://aws1.discourse-cdn.com/github/optimized/2X/d/d5d04096a36fd3a41a92273bfcdb5564c84be514_2_1035x517.png 1.5x, https://aws1.discourse-cdn.com/github/original/2X/d/d5d04096a36fd3a41a92273bfcdb5564c84be514.png 2x" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/d/d5d04096a36fd3a41a92273bfcdb5564c84be514_2_10x10.png"></div>

<h3><a href="https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/" target="_blank" rel="nofollow noopener">Authenticating Amazon ECR Repositories for Docker CLI with Credential Helper...</a></h3>

<p>This is a guest post from my colleagues Ryosuke Iwanaga and Prahlad Rao. ———————— Developers building and managing microservices and containerized applications using Docker containers require a secure, scalable repository to store and manage Docker...</p>


  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

<p>you can install it on your self-hosted runner, and use following config (you can modify the config for specific ECR repo rather than general)</p>
<pre><code class="lang-auto">{
    "credsStore": "ecr-login"
}
</code></pre>
<p>in this way, the runner will auto login AWS ECR and pull images from your private ECR repo. it works for both github actions service containers and docker container step.</p>

**Comment by mfridman** [comment]
<p>Anyone know the status of this?</p>
<p>It seems like a fundamental flaw not being able to docker login (to any registry, whether github packages or docker hub or ecr).</p>
<p>Our co would love to adopt actions, but the inability to pull private images is a deal breaker.</p>

**Comment by aexvir** [comment]
<p>Also writing here to manifest that I consider this an essential feature, and I’d like to know what’s the status with this request. Can we expect this to be supported anytime soon?</p>
<p>If not any private registry at least GitHub’s own docker registry, as right now it’s funny to not be able to use GitHub images from public repos in GitHub itself.</p>

**Comment by kungfuchicken** [comment]
<p>The last semi-official update from <a class="mention" href="/chrispat">@chrispat</a> was a little over a year ago. Are any updates available?</p>

**Comment by chrispat** [comment]
<p>Shipped today for job and service containers.</p>
<aside class="onebox allowlistedgeneric">
  <header class="source">
      <img src="https://github.blog/wp-content/uploads/2019/01/cropped-github-favicon-512.png?fit=32%2C32" class="site-icon" width="32" height="32">
      <a href="https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/" target="_blank" rel="noopener nofollow ugc">The GitHub Blog</a>
  </header>
  <article class="onebox-body">
    <div class="aspect-image" style="--aspect-ratio:690/362;"><img src="https://github.blog/wp-content/uploads/2019/03/blog-card.png?fit=5001%2C2626" class="thumbnail" width="690" height="362"></div>

<h3><a href="https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/" target="_blank" rel="noopener nofollow ugc">GitHub Actions: Private registry support for job and service containers -...</a></h3>

<p>GitHub Actions: Private registry support for job and service containers</p>


  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

**Reply by lestephane** [reply]
Do I understand it correctly that the poster's initial use case of using a private github container registry image in a **step** (as oppposed to a **job** or **service**) is still not supported?

> - name: Download Cache
>         uses: docker://gcr.io/[Project ID]/cache

If so, I don't understand why this discussion is marked as answered. From personal testing I've done with a private ghcr image, job works, **step does not** (docker pull fails with `unauthorized`). But I need this confirmed to not waste any more time.

**Reply by rpersee** [reply]
> Do I understand it correctly that the poster's initial use case of using a private github container registry image in a **step** (as oppposed to a **job** or **service**) is still not supported?
> 
> > * name: Download Cache
> >   uses: docker://gcr.io/[Project ID]/cache
> 
> If so, I don't understand why this discussion is marked as answered. From personal testing I've done with a private ghcr image, job works, **step does not** (docker pull fails with `unauthorized`). But I need this confirmed to not waste any more time.

I also couldn't get a private repository to work for a **step**... It's sad that this question was marked as answered.

**Reply by rdhar** [reply]
A few years on, and still awaiting the ability to pull private docker images at the GitHub Action step-level:

```yml
- name: Pull docker image from private registry
  uses: docker://ghcr.io/org/repo/greet:v1.2.3
  env:
    NAME: ${{ inputs.name }}
````

**Comment by kungfuchicken** [comment]
<p>such timing! great job, and thanks to all who made it happen <a class="mention" href="/chrispat">@chrispat</a> (including you).</p>

**Comment by kungfuchicken** [comment]
<p>Is this only for pulling from GH registry? if I need to pull from GCR, it doesn’t look like that’s supported yet, unless i’m missing something.</p>

**Comment by mattpopa** [comment]
Any chance for AWS ECR support?

**Comment by gfrid** [comment]
same issue here :(

**Comment by zachspar** [comment]
@chrispat, any timeline on when we will be able to pull from a private registry within a step? In my case, I need to pull from a private GHCR for a single step.

**Comment by divyangjp** [comment]
Using private docker registry in action is still an open issue. @chrispat

**Comment by TheBeachMaster** [comment]
@zachspar I have found a solution:

Docs:  [Github Docs](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio)

1. Navigate to the Page of the Private image in GHCR you want to pull 
![Screenshot 2024-09-30 at 03 20 16](https://github.com/user-attachments/assets/e53a5ce2-15ca-4930-a631-05efeb32409e)

2. Click on Package settings 
![Screenshot 2024-09-30 at 03 21 25](https://github.com/user-attachments/assets/7cf21537-8743-4eca-819d-6dc5773610d1)

3. Under "Manage Actions access" select the repos that you'd want to access the "package" 
![Screenshot 2024-09-30 at 03 23 44](https://github.com/user-attachments/assets/316860c9-98ae-494f-bf7e-0256dc6c98b7)
4. Profit! Now you can do the following...

```Dockerfile
FROM ghcr.io/<my-org>/<image>:<tag>

#... Cool stuff
```

**Reply by zachspar** [reply]
You're pointing out a feature that has been supported since GitHub Packages v1. I think you are misunderstanding.... I am needing to use a private image as a [reference in an action](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsstepsuses):

```
steps:
  - uses: docker://ghcr.io/<my-org>/<some-private-repo>/<some-private-image>:<tag>
```

**Comment by jklemm** [comment]
Well, testing this today and looks that is not supported yet.. I'm using `containerMode: dind` in AWS EKS.

My workflow is `build docker image` and `use this image to run tests`, it's a common usecase, no?

```yaml
  build-backend:
    runs-on: cicd-runners
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64
    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1
      with:
        arch: arm64
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::XXXXXXX:role/my-role-with-ecr-permissions
        aws-region: xx-east-1
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build and push images
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        file: Dockerfile.backend
        push: true
        tags: ${{ vars.ECR_REGISTRY_IMAGE }}:${{ github.sha }}
```

After:

```yaml
tests-backend:
  runs-on: cicd-runners
  needs: [build-backend]
  container: ${{ vars.ECR_REGISTRY_IMAGE }}:${{ github.sha }}  <- HOW IN THE WORLD I CAN DO THIS WORKS???
    credentials:
      role-to-assume: arn:aws:iam::XXXXXXX:role/my-role-with-ecr-permissions  <- CAN'T DO THIS TODAY, BUT IF THIS EXIST, WOULD BE GREAT!!!
  script:
     python manage.py test .
```

When it run prints: `Error response from daemon: Head "<my-repo/image:version>" no basic auth credentials`.

I'm not want to use `container:credentials` with username and password, because I already have `IAM Role with AssumeRoleWebIdentity`, so it's more secure, want to use this method to login in AWS ECR.

Ideas?

Thanks folks.

**Comment by TheDiggster13** [comment]
I am seeing a similar issue, but not something I've seen discussed here specifically. I am trying to build reusable Docker Github actions. This works when I target the Dockerfile local to the action.yml, but I now want to prebake this image for improved runtime performance of my workflows. 

The issue I am running into is in the action.yml file: (AWS account ID scrambled)

```
# action.yml
name: 'ExampleInstantiation'
description: 'Description for your action goes here'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time_of_greeting:
    description: The time the greeting was made
runs:
  using: 'docker'
  image: "docker://123456789123.dkr.ecr.us-east-1.amazonaws.com/exampleinstantiation:latest"
  args:
    - '--who-to-greet'
    - ${{ inputs.who-to-greet }}

```

The problem I am seeing when I try to invoke this is
```
Error response from daemon: Head "https://123456789123.dkr.ecr.us-east-1.amazonaws.com/v2/exampleinstantiation/manifests/latest": no basic auth credentials
```

No matter how I try to auth this, it doesn't work, as it tries to pull the image into the job before running any other steps I might have configured.  

Is this something I could solve by migrating to a private Github container registry, or is this just completely unsupported at present? Seems like a massive miss if so.
