### DISCUSSION TITLE
On trigger two conditions

### DISCUSSION THREAD

**Discussion by ghost** [community/community#25763] [Actions]
<p>Hello,</p>
<p>Is it possible to use two on trigger conditions, such as:</p>
<p>on:<br>
pull_request:<br>
branches:<br>
- master<br>
paths:<br>
- ‘<em>/<strong>.src’<br>
- '!.github/</strong>’<br>
push:<br>
branches:<br>
- master<br>
paths:<br>
- '</em>/<strong>.src’<br>
- '!.github/</strong>’</p>
<p>It looks like it passes the parsing, but does it behave as OR or AND condition?</p>
<p>Thanks!</p>

**Comment by airtower-luna** [comment, marked as answer]
<p>Neither. :wink:</p>
<p>Either of the conditions will trigger the workflow separately, so kind of similar to OR, but you’ll get multiple runs if multiple events occur.</p>

**Comment by jsoref** [comment]
<p>Those are very unrelated events. All events effectively happen in parallel.</p>
<p>My action has extra code that effectively ends a push event if it detects there’s an open pull request.</p>
Workflow:

  <article class="onebox-body">
    <h4><a href="https://github.com/check-spelling/spell-check-this/blob/ad8754db6e49d737690f5005c8f332f069e3fe8d/.github/workflows/spelling.yml" target="_blank" rel="noopener nofollow ugc">check-spelling/spell-check-this/blob/ad8754db6e49d737690f5005c8f332f069e3fe8d/.github/workflows/spelling.yml</a></h4>


```yaml
name: Spell checking
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request_target:
  issue_comment:
    types: [created]

jobs:
  spelling:
    name: Spell checking
    permissions:
      contents: read
      pull-requests: read
    outputs:
      internal_state_directory: ${{ steps.spelling.outputs.internal_state_directory }}
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    concurrency:
...
```

Action definition: https://github.com/check-spelling/check-spelling/blob/8919d434aab1251e80d394a2a83a00668f4e106b/action.yml#L122-L123

```yml
          suppress_push_for_open_pull_request:
            description: "If set, do not do work in response to `push` if there is an open `pull` request to the repository for the branch (this assumes there's a `pull_request_target` event configured)."
```

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>
<p>
Code:

  <article class="onebox-body">
    <h4><a href="https://github.com/check-spelling/check-spelling/blob/8919d434aab1251e80d394a2a83a00668f4e106b/check-pull-requests.sh" target="_blank" rel="noopener nofollow ugc">check-spelling/check-spelling/blob/8919d434aab1251e80d394a2a83a00668f4e106b/check-pull-requests.sh</a></h4>


```sh
#!/bin/bash

. "$spellchecker/common.sh"
if [ $(uname) = "Linux" ]; then
  date_to_epoch() {
    date -u -d "$1" +'%s'
  }
else
  date_to_epoch() {
    date -u -j -f '%Y-%m-%dT%H:%M:%SZ' "$1" +'%s'
  }
fi
timeframe=${timeframe:-60}
time_limit=$(( $timeframe * 60 ))
strip_quotes() {
  tr '"' ' '
}

begin_group 'Retrieving open pull requests'
pulls=$temp/pulls.json
...
```
