### DISCUSSION TITLE
Additional function(s): lowercase|uppercase

### DISCUSSION THREAD

**Discussion by DazWilkin** [community/community#25768] [Actions]
<p>Noob GitHub Actions user here.</p>
<p>My GitHub username includes uppercase characters.</p>
<p>My first GitHub Actions workflow builds a container image to push to GitHub Container Registry.</p>
<p>Container registries require lowercase repo names.</p>
<p>I wanted to be able to:</p>
<pre><code class="lang-auto">tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
</code></pre>
<p>But this errors because <code>github.repository_owner</code> includes uppercase.</p>
<p>I was unable to find a <a href="https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#functions" rel="noopener nofollow ugc">function</a> nor any other way to pipe this value into <code>lowercase</code> and think such a function (and perhaps its companion <code>uppercase</code>) would be useful.</p>
<pre><code class="lang-auto">tags: ghcr.io/${{ lowercase(github.repository) }}:${{ github.sha }}
</code></pre>
<p>Or, is there a better way to achieve this?</p>
<pre><code class="lang-auto">env:
  REPO: my-username/some-repo
...
steps:
   ...
   tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
</code></pre>

**Comment by airtower-luna** [comment, marked as answer]
<p>The <code>env</code> approach is what I’d do, except that I’d use <a href="https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html">Bash parameter expansion</a> to convert the case instead of hardcoding it:</p>
<pre><code class="lang-yaml">      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" &gt;&gt;${GITHUB_ENV}
</code></pre>
<p>Or if you need the tag in a run step you could do the parameter expansion right there.</p>

**Reply by bergus** [reply]
Imo it's slightly nicer to use the (new-ish) operator syntax of `bash`:

    echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

> `U`
> The expansion is a string that is the value of parameter with lowercase alphabetic characters converted to uppercase.
> 
> `u`
> The expansion is a string that is the value of parameter with the first character converted to uppercase, if it is alphabetic.
> 
> `L`
> The expansion is a string that is the value of parameter with uppercase alphabetic characters converted to lowercase.

**Reply by Likqez** [reply]
> When you write a variable definition to GITHUB_ENV, subsequent steps will have it as an environment variable. For example

See [here](https://github.com/orgs/community/discussions/25768#discussioncomment-3249186).

**Reply by rzaitov** [reply]
I found the lack of simple string manipulation functions very inconvenient. If someone wants to use the upper/lower case parameter expansion feature of Bash, ensure that your target runner has Bash v4.0 or above. Upper case parameter expansion has been available in Bash since version 4 [bash-faq-061]. Unfortunately, macOS runners have Bash 3.2, so this workaround is not available on such systems. One possible solution that works on both Ubuntu and macOS runners is to use `tr` (see comments below).

[bash-faq-061]: https://mywiki.wooledge.org/BashFAQ/061

**Reply by alan-czajkowski** [reply]
I refuse to accept this as an answer out of principle.

**Comment by Simran-B** [comment]
<p>While using built-in shell functionality is probably more succinct, you could also use a string manipulation action if you want something that works the same regardless of the shell type:</p>
<pre><code class="lang-yaml">    steps:
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - run: |
          echo "${{ steps.string.outputs.lowercase }}"
</code></pre>

**Reply by Entepotenz** [reply]
I wrote an alternative to the ASzc/change-string-case-action version.
https://github.com/Entepotenz/change-string-case-action-min-dependencies

It is using pure python for the string conversion.
It does not depend on any library and therefore does not require any maintenance from security perspective :-)
Additionally I have a couple of tests running automatically before publishing.

**Reply by hu1buerger** [reply]
@Entepotenz sounds reasonable to me

**Comment by ArnoudAtBreenservices** [comment]
<p>How would you use it inside the run step, then?</p>

**Comment by airtower-luna** [comment]
<p>When you write a variable definition to <code>GITHUB_ENV</code>, subsequent steps will have it as an environment variable. For example:</p>
<pre><code class="lang-yaml">      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" &gt;&gt;${GITHUB_ENV}
      - name: use REPO
        run: echo "The value of REPO is: ${REPO}"
</code></pre>

**Comment by FrostyLeaf** [comment]
<p>The following commands can do this trick:</p>
<pre><code class="lang-shell">ABC=$(echo 'console.log("abc".toUpperCase())' | node -);
echo $ABC
</code></pre>
<p>In you case, it could be:</p>
<pre><code class="lang-shell">repo=$(echo 'console.log("${{ github.repository }}".toLowerCase())' | node -)
tags: ghcr.io/${repo}:${{ github.sha }}
</code></pre>

**Reply by ystxn** [reply]
the reply before you already provided the most succinct solution. your response is confusing in suggesting that it's possible to run script within a step and interpret the value within a field in the same step, which is not possible.

**Reply by gerardnico** [reply]
This is the solution for a multi runner workflow.
* Bash substitution do not work with [macos](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md) that is still on bash version `3.2.57(1)-release`
* And you don't need to know the python version to use the correct print syntax

```yaml
      - name: Properties
        id: props
        shell: bash
        run: |
          # Runner real id 
          RUNNER_ID=$(echo 'console.log("${{ runner.os }}-${{ runner.arch }}".toLowerCase())' | node -);
          echo "runner_id=${RUNNER_ID}" >> $GITHUB_OUTPUT
     - name: Usage
       run: echo "The runner id is: ${{ steps.props.outputs.runner_id }}"
```
Thanks !

**Comment by FrostyLeaf** [comment]
<p>Python also does the exactly same thing:</p>
<pre><code class="lang-shell">ABC=$(echo 'print("abc".upper())' | python3.9 -)
echo $ABC
</code></pre>

**Comment by Entepotenz** [comment]
IMHO:
I would feel uncomfortable running those bash commands basically calling eval in python or nodejs.

I am talking about those examples:
```
ABC=$(echo 'print("abc".upper())' | python3.9 -)
echo $ABC
```
```
ABC=$(echo 'console.log("abc".toUpperCase())' | node -);
echo $ABC
```

I think those two links describe much more secure solutions:
- https://github.com/orgs/community/discussions/25768#discussioncomment-4557471
- https://github.com/orgs/community/discussions/25768#discussioncomment-3249184

You can also check out the security best practices for GitHub actions: https://res.cloudinary.com/da8kiytlc/image/upload/v1651737641/GitHub-Actions-Security-Best-Practices_cheatsheet.pdf

**Comment by d3vpasha** [comment]
I don't like any answer above, for me, Github actions must have some built-in functions to do usual things like uppercase, camelcase, lowercase, etc..

**Comment by shellscape** [comment]
See this answer https://stackoverflow.com/a/63315136/416845 on how to use `${var^^}` to uppercase

**Comment by ALERTua** [comment]
These worked for me:
```yaml
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
```
```yaml
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
```
then `${{ env.IMAGE_NAME }}` or `"${{ env.IMAGE_NAME }}:latest"`

**Reply by gerardnico** [reply]
You need `tr` that is not on Windows...

**Comment by bergus** [comment]
See also https://github.com/orgs/community/discussions/10553

**Comment by lordfolken** [comment]
None of these answers solve the actual problem. 
If you want to run steps inside an image, then you need to first to be able to specify the image path, in order to pull the image.
Without variable expansion, an additional job is necessary that first lowercases the variable and then using that in a subsequent container job. 
What a waste of resources.

**Reply by esaporski** [reply]
GitHub Actions has a lot of potential, but right now it feels like a half-finished product.

**Reply by alan-czajkowski** [reply]
GitHub Actions is quite possibly the worst pipeline orchestration tool I've ever used

**Reply by Solenhya** [reply]
Not being able to handle people using uppercase letter NAMING thing is madness. Imo if they can't handle uppercase they should include a parser

**Comment by MattiaDev2** [comment]
Thanks for the replies, it helped me too

**Comment by randomairborne** [comment]
If i were to want to set a top-level environment variable, I *have* to be able to process that with the template system. There is no other option. Right now, it seems like this is impossible.

**Comment by alexander-williamson** [comment]
Today we wanted to use something like this:
```
${{ inputs.SOMETHING.lowercase }}
```
But I don't know if that's possible? Something for us to investigate.

**Comment by Firefishy** [comment]
`docker/metadata-action` automatically normalises image names, including fixing the casing.

To explicitly use it to extract the lower case name into `${env.IMAGE_NAME}`:
```
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.SOMETHING }}

      - name: Set normalised image name
        run: |
          repo_image=$(jq -r '.tags[0]' <<< "$DOCKER_METADATA_OUTPUT_JSON" | cut -d: -f1)
          echo "IMAGE_NAME =$repo_image" >>${GITHUB_ENV}
```

Or likely more appropriately just use the `steps.meta.outputs.tags`:
```
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.SOMETHING }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
```
