### DISCUSSION TITLE
Run workflow after pushing changes to a PR

### DISCUSSION THREAD

**Discussion by peterMonteer** [community/community#25796] [Actions]
<p>One of my workflows is set to run like this</p>
<pre><code>on:
 pull_request:
    types: [review_requested, edited]
</code></pre>
<p>The workflow runs correctly after I request a review on the PR.</p>
<p>However, when I need to fix something on the PR, make the necessary changes locally and push it to remote, the workflow is not triggered.<br>
I searched in the documentation for when the edited type is triggered and it seems it should be triggered in this situation, or am I missing something?</p>

**Comment by weide-zhou** [comment, marked as answer]
<p>Hi Peter,</p>
<p>If you make some changes to the files(eg: resolve conflicts), push to github, please use type ‘synchronize ’ for pull request to trigger the workflow, it works on my side, code as below:</p>
<pre><code>name: Pull request check

on:

  pull_request:

    types: [synchronize]
</code></pre>
<p>For type ‘edited’, I tried to use rest api locally to update Pull request(please refer to <a href="https://developer.github.com/v3/pulls/#update-a-pull-request" rel="nofollow noopener">https://developer.github.com/v3/pulls/#update-a-pull-request</a>), it’s successful to trigger the workflow.</p>
<p>Checked the pull request content from API result, you will find the file update/new commit is not included.</p>

**Comment by peterMonteer** [comment]
<p>Ok thanks!</p>
<p>So type ‘edited’ is only triggered when updating PR title, body, state or base?</p>

**Comment by weide-zhou** [comment]
<p>Yes, the ‘edited’ type is triggered when updating PR itself, including title, body, state, base, and other stuff.</p>
<p>Details we can check the PR content from API result for confirmation, thanks.</p>

**Comment by AllanOricil** [comment]
<p><a class="mention" href="/weide-zhou">@weide-zhou</a></p>
<p>it seems that edited is no longer working consistently. I made it work 2 times in a row, then I edit the title a third time and it stopped working without changing anything. I opened a PR to ask for help but it would be good ifyou guys could fix it asap.</p>
<aside class="onebox githubissue" data-onebox-src="https://github.com/actions/runner/issues/1547">
  <header class="source">

      <a href="https://github.com/actions/runner/issues/1547" target="_blank" rel="noopener nofollow ugc">github.com/actions/runner</a>
  </header>

  <article class="onebox-body">
    <div class="github-row">
  <div class="github-icon-container" title="Issue">
	  <svg width="60" height="60" class="github-icon" viewbox="0 0 14 16" aria-hidden="true"><path d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg>
  </div>

  <div class="github-info-container">
    <h4>
      <a href="https://github.com/actions/runner/issues/1547" target="_blank" rel="noopener nofollow ugc">Action not being triggered when editing PR title or description</a>
    </h4>

    <div class="github-info">
      <div class="date">
        opened <span class="discourse-local-date" data-format="ll" data-date="2021-12-10" data-time="10:40:18" data-timezone="UTC">10:40AM - 10 Dec 21 UTC</span>
      </div>


      <div class="user">
        <a href="https://github.com/AllanOricil" target="_blank" rel="noopener nofollow ugc">
          <img alt="AllanOricil" src="https://user-images.githubusercontent.com/55927613/181093320-8386db46-2fbf-4f39-95bd-8c3066165063.jpeg" class="onebox-avatar-inline" width="20" height="20">
          AllanOricil
        </a>
      </div>
    </div>

    <div class="labels">
        <span style="display:inline-block;margin-top:2px;background-color: #B8B8B8;padding: 2px;border-radius: 4px;color: #fff;margin-left: 3px;">
          bug
        </span>
    </div>
  </div>
</div>

  <div class="github-row">
    <p class="github-body-container">**Describe the bug**
Yesterday I was able to trigger actions when editing PR ti<span class="show-more-container"><a href="" rel="noopener" class="show-more">…</a></span><span class="excerpt hidden">tle or description (body). Later in the same day it stopped!  And there is no issue reported in the Github Status website.

This is my action:

````yml
name: Bump Version Workflow

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main

  workflow_dispatch:

jobs:
  get-mulesoft-apps:
    name: Get Mulesoft Apps
    uses: VodafoneIS/mulesoft/.github/workflows/get-mulesoft-apps.yml@main

  bump-version:
    name: bump version
    needs: get-mulesoft-apps
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vodafoneis/mulesoft-build-image:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        MULESOFT_APP: ${{ fromJson(needs.get-mulesoft-apps.outputs.MULESOFT_APPS) }}

    defaults:
      run:
        working-directory: ${{ matrix.MULESOFT_APP }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: print app name
        run: echo ${{ matrix.MULESOFT_APP }}

      - uses: fregante/setup-git-user@v1

      - name: set bump type
        id: get-bump-type
        run: |
          bump_type=$(/scripts/get_bump_type.sh -a ${{ matrix.MULESOFT_APP }} -t ${{ github.event.pull_request.title }} -b ${{ github.event.pull_request.body}})
          echo "::set-output name=BUMP_TYPE::$bump_type"

      - name: bump version
        run: /scripts/bump_version.sh -a ${{ matrix.MULESOFT_APP }} -b ${{ steps.get-bump-type.outputs.BUMP_TYPE }}

````

**To Reproduce**
Steps to reproduce the behavior:
1. Create an Action that triggers when editing the PR title or description (type: edited)

**Expected behavior**
When editing the Title or the Description, the Action MUST be triggered if the Action was configured properly, and the PR is against "main"

pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main


## Runner Version and Platform
ubuntu-latest

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Github seems to not dispatch PR edit events to start Github Actions

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A</span></p>
  </div>

  </article>

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>
