### DISCUSSION TITLE
Using exit code of previous step

### DISCUSSION THREAD

**Discussion by alexbde** [community/community#25809] [Actions]
<p>So I know you can use output of steps by referring to <code>steps.\&lt;step id\&gt;.outputs.\&lt;output name\&gt;</code>.</p>
<p>Is it also possible to use exit code of previous step?</p>
<p>Pseudo code:</p>
<pre><code>steps:
      - id: example
        uses: repo/some-external-action@master
      - if: steps.example.exitcode &gt; 0
        run: echo "Something went wrong"
</code></pre>

**Comment by dawidd6** [comment, marked as answer]
<pre><code>- if: failure()
- if: success()
</code></pre>
<p>This is the only solution to know if Action step completed successfully or not that I know.</p>

**Comment by alexbde** [comment]
<p>Perfect hint, thank you! Works in my situation.</p>
<p>More info: <a href="https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#job-status-check-functions" rel="nofollow noopener">https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#job-status-check-functions</a></p>

**Comment by rajbos** [comment]
If anyone gets to this from search: you can now also get the result of any of the previous steps:
``` 
name: CI
on: [pull_request]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: hello
        run: <any> 
        continue-on-error: true
      - name: Step 2
        id: world
        run: <any> 
        continue-on-error: true
      - name: Check on failures
        if: steps.hello.outcome != 'success' || steps.world.outcome != 'success'
        run: exit 1
``` 

Borrowed the answer from [Stack Overflow](https://stackoverflow.com/questions/57850553/github-actions-check-steps-status)
