### DISCUSSION TITLE
Get all tag names for the current repository

### DISCUSSION THREAD

**Discussion by ALIENQuake** [community/community#25810] [Actions]
<p>Hi,</p>
<p>Is there a simple way of getting all tag names for the current repository?</p>

**Comment by eddiechenms** [comment, marked as answer]
<p>You can add some steps or use some actions like <a href="https://github.com/marketplace/actions/github-api-request" rel="nofollow noopener">GitHub API Request Action</a> to call <a href="https://developer.github.com/v3/git/refs/#list-matching-references" rel="nofollow noopener">List matching references</a> API to list all the refs you want. To get all the tags, you just need to specify the URL as below:</p>
<pre><code>GET /repos/:owner/:repo/git/matching-refs/tags
</code></pre>

**Reply by dersimn** [reply]
```yaml
jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/${{ github.repository }}/git/matching-refs/tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
```
