### DISCUSSION TITLE
Conditionally run a Job based on the output of another Job

### DISCUSSION THREAD

**Discussion by itsjxck** [community/community#25941] [Actions]
<p>I know Jobs have an <code>if</code> parameter, but it doesn’t seem to be possible to use an output of a previous Job in the expression for the <code>if</code>.</p>
<p>As an example:</p>
<pre><code class="lang-auto">...
jobs:
  run-check:
    outputs:
      approved: steps.pr-eval.outputs.approved
    steps:
      - name: PR Approval Status
         id: pr-eval
         run: |
           &lt;do some checks&gt;
           echo "::set-output name=approved::true"
  deploy:
    needs: [run-check]
    // Invalid "Unrecognised named-value: 'jobs'
    if: jobs.run-check.outputs.approved == 'true' 
    // None of these work
    if: needs.run-check.outputs.approved
    if: needs.run-check.outputs.approved == 'true' 
    if: needs.run-check.outputs.approved == true
</code></pre>
<p>Anyone got any ideas or is this just not possible?</p>

**Comment by weide-zhou** [comment, marked as answer]
<p>Hi <a class="mention" href="/itsjxck">@itsjxck</a>,</p>
<p>Glad to see you in Github Community Forum!</p>
<p>This is due to you omit <code>${{}}</code> for the step output value in job <code>run-check</code>, the job output value is not <code>true</code> in this case.</p>
<p>Fixed as below:</p>
<pre><code class="lang-auto">jobs:
  run-check:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.pre-val.outputs.approved }}  # add ${{ }} for the step output
    steps:
      - name: PR Approval Status
        id: pre-val
        run: |
           echo "::set-output name=approved::true"
  deploy:
    needs: [run-check]
    runs-on: ubuntu-latest
    if: needs.run-check.outputs.approved == 'true'
</code></pre>
<p>Thanks</p>

**Comment by itsjxck** [comment]
<p>You’re a star, thank you!</p>

**Comment by pratyushly** [comment]
### Update:

As [`set-update` command is deprecated and will be soon disabled](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), environment variables should be used.

#### Modified code:

```
jobs:
  run-check:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.pre-val.outputs.approved }}  # add ${{ }} for the step output
    steps:
      - name: PR Approval Status
        id: pre-val
        run: |
           echo "approved=true"  >> $GITHUB_OUTPUT
  deploy:
    needs: [run-check]
    runs-on: ubuntu-latest
    if: needs.run-check.outputs.approved == 'true'
```
