### DISCUSSION TITLE
Builtin support for artifact sharing

### DISCUSSION THREAD

**Discussion by a-recknagel** [community/community#26070] [Actions]
<p>The current strategy to share artifacts between jobs is to use <a href="https://github.com/actions/upload-artifact" rel="nofollow noopener">upload-artifact</a> and <a href="https://github.com/actions/download-artifact" rel="nofollow noopener">download-artifact</a>, which works reasonably enough but can get quite verbose. It would be nice to have a jobs.&lt;job_id&gt;.artifacts section, since it seems to be an often requested feature that fundamentally changes how workflows are written and used.</p>
<p>This could also enable artifact sharing between workflows (e.g. an option to specify the target path, which would by default depend on the commit sha and would be local to a push, but could then also be branch/tag specific or even global for the project), for things like shared caches between workflow runs.</p>
<p>Any plans to include something like this?</p>

**Comment by chrispat** [comment, marked as answer]
<p>We do plan to introduce someway to share artifacts between workflows as well as an option for caching between runs of the same workflow.</p>
<p>We don’t plan to introduce a specific keyword for artifacts just like we don’t have a keyword for checking out the repository.  Actions that you use in your workflow come from GitHub repos and we want all actions whether we create them or another GitHub user creates them to be referenced the same way.   </p>
<p>The only place where we have decided to deivate from this design is with the run keyword and this is because running a shell script is so common that we felt it needed to simply be built in.</p>

**Comment by a-recknagel** [comment]
<p>Thanks, I really appreciate getting the reasoning on decisions like that.</p>
<p>I also considered the similarity to actions/checkout when I wrote this post, the reason why I hit “send” anyway is that an artifact action has a lot more possible parametrization, like expiration time and access rights. But in the end it all comes down to how well it’s documented, if that part is good then all is good.</p>

**Comment by hitmands** [comment]
<p>It looks like it is only possible to  <strong>share artifacts between jobs of the same workflow.</strong></p>
<p>How about <strong>sharing artifacts between workflows?</strong></p>
<p><a href="https://stackoverflow.com/questions/60355925/share-artifacts-between-workflows-github-actions" rel="nofollow noopener">https://stackoverflow.com/questions/60355925/share-artifacts-between-workflows-github-actions</a></p>

**Comment by jitesh88** [comment]
<p>Its been 6months, any update on sharing artefacts between workflows?</p>

**Comment by lpossamai** [comment]
It's been 3 years... cmon guys!

**Reply by aszymanski** [reply]
It's super easy in Azure DevOps but it looks like we will have to wait couple more years to have it in Actions. To be honest it's a very important feature when it comes to multienvironment deployments.

**Comment by o6uoq** [comment]
Artifact sharing is a core tenet of any CI/CD system. It's 2024 and this still isn't available in GitHub Actions! Embarrassing.

**Reply by ChristopherHX** [reply]
Sharing artifacts between workflows, should be possible as of mid December 2023 if you use both v4 of upload-artifact and download-artifact

https://github.com/actions/download-artifact?tab=readme-ov-file#usage

```yaml
    # The repository owner and the repository name joined together by "/".
    # If github-token is specified, this is the repository that artifacts will be downloaded from.
    # Optional. Default is ${{ github.repository }}
    repository:

    # The id of the workflow run where the desired download artifact was uploaded from.
    # If github-token is specified, this is the run that artifacts will be downloaded from.
    # Optional. Default is ${{ github.run_id }}
    run-id:
```

_GHES users need to wait_

A keyworld for the workflow is not existent.
