### DISCUSSION TITLE
Run failing - Invalid workflow file

### DISCUSSION THREAD

**Discussion by reintroducing** [community/community#26095] [Actions]
<p>This is my first foray into action and I’ve been staring at this for hours now and can’t figure out why this workflow is failing. I’ve double and triple-checked with other online examples and it seems like I’m compliant. Can anyone that has experience with actions help me figure out what I’m missing please?</p>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/d/db7a675ecba2207b0f7b5aae0c34127dcbae7386.png" data-download-href="/uploads/short-url/vjAOwCSl5qtac1SsFYv9uKGry86.png?dl=1" title="Screen Shot 2020-08-14 at 3.08.39 PM" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/259901/181095197-1dd2fb9d-42bd-4da0-890d-94c922e89d38.png" alt="Screen Shot 2020-08-14 at 3.08.39 PM" data-base62-sha1="vjAOwCSl5qtac1SsFYv9uKGry86" width="302" height="500" srcset="https://aws1.discourse-cdn.com/github/optimized/2X/d/db7a675ecba2207b0f7b5aae0c34127dcbae7386_2_302x500.png, https://aws1.discourse-cdn.com/github/optimized/2X/d/db7a675ecba2207b0f7b5aae0c34127dcbae7386_2_453x750.png 1.5x, https://aws1.discourse-cdn.com/github/original/2X/d/db7a675ecba2207b0f7b5aae0c34127dcbae7386.png 2x" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/d/db7a675ecba2207b0f7b5aae0c34127dcbae7386_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">Screen Shot 2020-08-14 at 3.08.39 PM</span><span class="informations">491×811 47.1 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>

**Comment by airtower-luna** [comment, marked as answer]
<p>There are indentation problems in your workflow. In YAML indentation determines structure, like in Python. Your <code>name</code>, <code>uses</code>, and <code>with</code> settings need to be part of the same object (the step), so they must be on the same indentation level. Same for <code>name</code> and <code>run</code> in the steps below, like so:</p>
<pre><code class="lang-yaml">- name: Use node
  uses: actions/setup-node@v2
  with:
    node-version: '12.13.0'
    check-latest: true
- name: Install dependencies
  run: npm ci
</code></pre>

**Reply by hasanbadshah** [reply]
```
name: Deploy Workflow
on: [push, workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Get Code
        uses: actions/checkout@v3
        - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
            node-version: '10.19.0'
        - name: Install dependencies
        run: npm ci
        - name: Build Project
        run: npm run build
        - name: deploy
        run: echo "Deploying..."
```           
whats wrong in this work flow its throwing same exception,

**Reply by airtower-luna** [reply]
Probably also an indentation problem, but as your YAML isn't in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) it's impossible to say where.

**Reply by hasanbadshah** [reply]
@airtower-luna i just updated my above comment in a code block. Any hint on it?

**Reply by airtower-luna** [reply]
As I suspected, invalid YAML. :slightly_smiling_face: 

Each step is a list item (indicated by `-`) containing a mapping (the `label: value` pairs), so the labels must be indented to the same level. E.g.:

```yaml
        - name: Get Code
          uses: actions/checkout@v3
```

In YAML indentation is part of the syntax.

**Reply by hasanbadshah** [reply]
Thank you so much, it worked <3

```
name: Deploy Workflow
on: [push, workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        -   name: Get Code
            uses: actions/checkout@v3
        -   name: Setup Node
            uses: actions/setup-node@v3
            with:
                node-version: '10.x'
        -   name: Install Dependencies
            run: |
                cd ./storefront-reference-architecture
                npm install
        -   name: Build Project
            run: |
                cd ./storefront-reference-architecture
                npm run build
        -   name: deploy
            run: echo "Deploying..."
```

**Comment by reintroducing** [comment]
<p><a class="mention" href="/airtower-luna">@airtower-luna</a> That indeed did the trick. Prettier formatting the file also was not helping. Thank you so much.</p>

**Comment by Jatingupta9120** [comment]
![image](https://github.com/community/community/assets/114533828/7eeee96a-124e-491f-a7d9-e30c8b91bc8b)
help guys

**Reply by hasanbadshah** [reply]
try this as a basic workflow

```
name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello world"
    - name: Good bye
      run: echo "This job step is over, Bye bye.!"
```

**Comment by brenodobroski** [comment]
![image](https://github.com/community/community/assets/114618985/6e3d54e7-805c-4b16-9e35-2170d5f6d8fa)

help guys pls

**Reply by brenodobroski** [reply]
```
name: Pipeline de produção
env:
  NODE_ENV: production
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: CI - Build e criação do artefato
    runs-on: ubuntu-latest
    steps:
      - name: Pegar código do Repositório
        uses: actions/checkout@v3

      - name: Instalando pacotes do npm
        run: npm install

      - name: Gerando documentação do swagger.json
        run: npm run autoDoc

      - name: Apagando pasta node_modules
        run: rm -rf node_modules

      - name: Apagando pasta .git
        run: rm -rf .git

      - name: Arquivos e pastas
        run: ls

      - name: Criando artefato ZIP do código buildado
        uses: actions/upload-artifact@v3
        with:
          name: artefato
          retention-days: 1
          path: ./

  job2:
    name: CD - Deploy na Vercel
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Baixando Artefato do código buildado
        uses: actions/download-artifact@v3
        with:
          name: artefato

      - name: Instalando pacotes do npm
        run: npm install

      - name: Arquivos e pastas do artefato
        run: ls

      - name: Instalando CLI da Vercel
        run: npm install --global vercel@latest

      - name: Buscando informações de ambiente no Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Buildando artefatos do projeto
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy de artefatos do projeto na Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

```
