### DISCUSSION TITLE
Status checks "required if run"

### DISCUSSION THREAD

**Discussion by pmeier** [community/community#26092] [Actions]
<h1>TL;DR</h1>
<p>Is it somehow possible to change the branch protection from status checks that are required to “required if run”?</p>
<hr>
<p>I heavily make use of the</p>
<pre><code class="lang-auto">on:
  pull_request:
    paths:
</code></pre>
<p>for my different workflows for GitHub Actions. Thus, depending on what files were changed in the PR a different set of checks is run. I would mark most (if not all) of them as required before a PR is merged. Problem is, if I do that the PR also waits for checks that will not be run. Is it somehow possible to change this behavior so that a check is marked as required only if it is run?</p>

**Comment by weide-zhou** [comment, marked as answer]
<p>Hi <a class="mention" href="/pmeier">@pmeier</a>,</p>
<p>I’m afraid it’s not supported. If the checkrun is required, it has to be completed and return a status value.<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/4/47b7b0157bf7ab425667eb53295a90366fefe4ff.png" data-download-href="/uploads/short-url/aerrSRUNTvCyirHmZeExazKNCPl.png?dl=1" title="mustpass" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/52772761/181095182-74dcbf7b-07e4-48e3-ab26-e886671c3424.png" alt="mustpass" data-base62-sha1="aerrSRUNTvCyirHmZeExazKNCPl" width="690" height="111" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/4/47b7b0157bf7ab425667eb53295a90366fefe4ff_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">mustpass</span><span class="informations">729×118 7.32 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>
<p>The only exception is if you’re an administrator, you can still merge the pull request.<br>
<img src="https://user-images.githubusercontent.com/52772761/181095183-a8488c92-2c8d-436c-b97f-074ac4ff146d.png" alt="adminmerge" data-base62-sha1="2p3Y1MvU3PFPPS3kpBLTEUR3x0R" width="633" height="318"></p>
<p>Thanks.</p>

**Comment by pmeier** [comment]
<p>Hm, that is unfortunate. Problem with you approach is that the PR is marked as “not completed yet (yellow dot)” or failed forever, although that is not the case. I guess I’ll remove the branch protection rules in that case. Thanks for your input.</p>

**Comment by tunetheweb** [comment]
<p>Yes this is a real shame.</p>
<p>I’d like a “all tests run must pass” option, rather than a “these tests must run and pass (even though some of them may not be automatically started nor be relevant)” option.</p>

**Comment by ayushxx7** [comment]
any new update on this?

**Comment by piotrekkr** [comment]
@pmeier @ayushxx7 You could try this workaround:
- put all those checks inside one workflow file
- DO NOT define `paths:` for pull request event
- create some initial job (e.g. `init-job`) that will decide what actual checks should run and which one should be skipped (based on changed paths) and set results as job output parameters
  - you can use this [`paths-changes-filter` action](https://github.com/marketplace/actions/paths-changes-filter)  to check what changed
- define each check so it will depend on init job (`needs: init-job`) and will only be run when output of `init-job` is set to correct value, e.g. `if: needs.init-job.outputs.run_check1 == 'yes'`

This way some check will run, and the rest will be `skipped` if path were not changed. GitHub treats skipped jobs as non blocking for PR merge so this should work fine I think.

**Comment by lijok** [comment]
Just found out this wasn't supported. This is incompatible with monorepos.

**Comment by fregante** [comment]
I have a solution that involves a separate job with `needs`:

```yml
  pass:
    needs: tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: "tests must not fail (status: ${{ needs.tests.result }})"
        run: exit ${{ needs.tests.result == 'failure' && '1' || '0' }}
```

You can set this as your `Required` job. It will be green unless the `tests` job explicitly fails.

You customize it and add further logic and steps if you need it to depend on multiple jobs and also want to fail on "cancelled" jobs.

This is the one I'm currently using, with a couple dependencies and different requirements:

```yml
  pass:
    # Use `always()` in every step so that every step runs and gives the full status of the requirements
    needs: [affected-check, tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: "affected-check must be successful (status: ${{ needs.affected-check.result }})"
        run: exit ${{ needs.affected-check.result == 'success' && '0' || '1'  }}
        if: always()
      - name: "tests must not fail (status: ${{ needs.tests.result }})"
        run: exit ${{ needs.tests.result == 'failure' && '1' || '0' }}
        if: always()
```

**Reply by piotrekkr** [reply]
Adding required check that depends on other required checks, is run with condition `always()` and check statuses of each required check is also a solution. You could also simplify a bit steps imho like this:
```yaml
  pass:
    needs: [affected-check, tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Fail on required check failure
        if: |
          needs.affected-check.result != 'success'
          || needs.tests.result != 'success'
        run: |
          echo 'Required checks results: ${{ toJSON(needs) }}'
          exit 1
```

Still it would be way easier if this was implemented by GitHub so workarounds would not be needed.
