### DISCUSSION TITLE
Workflow_run completed event triggered by failed workflow

### DISCUSSION THREAD

**Discussion by cuporter** [community/community#26238] [Actions]
<p>I have a workflow triggered as follows:</p>
<pre><code class="lang-auto">name: Production deploy
on:
  workflow_run:
    workflows: ["Stage deploy"]
    types:
      - completed
</code></pre>
<p>I expect that after the stage deploy (which also runs API tests) completes successfully, then the production deploy would start. However, I just watched a failed stage deploy (which skipped its API tests due to the failed deploy) also trigger a production deploy. Is there a different “types” value for workflow_run that causes it not to fire if the workflow failed, rather than completed successfully?</p>

**Comment by BrightRan** [comment, marked as answer]
<p><a class="mention" href="/cuporter">@cuporter</a>,</p>
<p>Currently, there are only the two types <strong>requested</strong> and <strong>completed</strong> for the <strong>workflow_run</strong> event.</p>
<p>As a workaround, you can use the expression “<strong>github.event.workflow_run.conclusion</strong>” to get the result of the previous workflow run, and use the job 's <strong>if</strong> conditional to skip all the job in the current workflow run when the previous workflow run is not success.</p>
<pre><code class="lang-yaml">name: Production deploy
on:
  workflow_run:
    workflows: ["Stage deploy"]
    types:
      - completed

jobs:
  job1:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

  job2:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    . . .

  jobN:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
</code></pre>
<p>Of course, you also can directly report a feature request that add more types for the <strong>workflow_run</strong> event (such as <strong>success</strong> and <strong>failure</strong>) <a href="https://support.github.com/contact/feedback?contact%5Bcategory%5D=actions" rel="nofollow noopener">here</a>.<br>
That will allow you to directly interact with the appropriate engineering team, and make it more convenient for the engineering team to collect and categorize your suggestions.</p>

**Comment by edudepetris** [comment]
<p>how do you use <code>github.event.workflow_run.conclusion == 'success'</code> when you have multiples workflows?</p>
<pre><code class="lang-auto">name: Production deploy
on:
  workflow_run:
    workflows: ["CI", "Linters"]
    types:
      - completed
</code></pre>

**Comment by Simran-B** [comment]
<p><a class="mention" href="/edudepetris">@edudepetris</a> I assume that both CI and Linters both trigger separate <code>workflow_run</code> events, i.e. you only see a single conclusion, from one of the parent workflows. You may want to verify this with e.g.</p>
<pre><code class="lang-auto">name: Production deploy
on:
  workflow_run:
    workflows: ["CI", "Linters"]
    types:
      - completed
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
</code></pre>
<p>If I’m right, then it might not be possible to wait for both parent workflows to succeed and then run the production deployment, unless you let Linters trigger CI and then let CI trigger Production deploy…</p>

**Comment by ahmadnassri** [comment]
<p><a class="mention" href="/brightran">@brightran</a> your suggestion works great, however, it is not documented in the webhook events docs: <a href="https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run" rel="noopener nofollow ugc">https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run</a></p>
<p>I wonder if this property is authoritative, or will be removed in the future?</p>

**Comment by benc-uk** [comment]
<p>How was this ever considered useful or fit for production use in it’s current form?<br>
Triggering workflows on completion <em>regardless</em> of status is so naïve, it has no applicability in the real world</p>
<p>The workaround, aside from being ugly and error prone, still results in the workflow being triggered so you end up with hundreds of skipped runs when you look at the UI</p>

**Comment by ahmadnassri** [comment]
<p>this was frustrating me enough that I went ahead and created a new Action to deal with the shortcomings of <code>workflow_run</code>, namely:</p>
<p>The <a href="https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run" rel="noopener nofollow ugc"><code>workflow_run</code></a> event occurs when a workflow run is requested or completed, and allows you to execute a workflow based on the finished result of another workflow.</p>
<h6>example</h6>
<pre><code class="lang-yaml">on:
workflow_run:
  workflows: [ test ]
  types: 
    - completed
</code></pre>
<p>However by itself, this doesn’t quite work as expected.</p>
<ol>
<li>
<p>The <code>completed</code> type, does not indicate success, for that you’d have to include the following in each job of your workflow:</p>
<pre><code class="lang-yaml">if: ${{ github.event.workflow_run.conclusion == 'success' }}
</code></pre>
</li>
<li>
<p>If you’re depending on more than one workflow, then ANY of them completing, will trigger the event</p>
<h6>example</h6>
<pre><code class="lang-yaml">name: deploy

on:
workflow_run:
  workflows: [ test, lint, compile ]
  types: 
    - completed
</code></pre>
<blockquote>
<p><em>if your <code>test</code> workflow fails, but <code>lint</code> completed successfully, <code>github.event.workflow_run.conclusion == 'success'</code> will still be true</em></p>
</blockquote>
</li>
<li>
<p>Your workflow will trigger as many times as you have workflow dependencies</p>
<blockquote>
<p><em>in the previous example, our <code>deploy</code> workflow, will run 3 times!</em></p>
</blockquote>
</li>
</ol>
<p>All this makes the <code>workflow_run</code> event fundamentally broken for any advanced usage, this Action aims to remedy that:</p>
<aside class="onebox githubfolder">
  <header class="source">
      <img src="https://github.githubassets.com/favicons/favicon.svg" class="site-icon" width="32" height="32">
      <a href="https://github.com/ahmadnassri/action-workflow-run-wait" target="_blank" rel="noopener nofollow ugc">github.com</a>
  </header>
  <article class="onebox-body">
    <div class="aspect-image" style="--aspect-ratio:400/400;"><img src="https://avatars.githubusercontent.com/u/183195?s=400&amp;amp;v=4" class="thumbnail" width="400" height="400"></div>

<h3><a href="https://github.com/ahmadnassri/action-workflow-run-wait" target="_blank" rel="noopener nofollow ugc">ahmadnassri/action-workflow-run-wait</a></h3>


  <p><span class="label1">wait for all `workflow_run` required workflows to be successful</span></p>

  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

**Comment by tonyhallett** [comment]
<p>An alternative to conditionals on conclusion.</p><aside class="onebox githubfolder">
  <header class="source">
      <img src="https://github.githubassets.com/favicons/favicon.svg" class="site-icon" width="32" height="32">
      <a href="https://github.com/marketplace/actions/workflow-run-conclusion-dispatch-action" target="_blank" rel="noopener nofollow ugc">github.com</a>
  </header>
  <article class="onebox-body">
    <div class="aspect-image" style="--aspect-ratio:420/420;"><img src="https://avatars.githubusercontent.com/u/11292998?s=400&amp;amp;v=4" class="thumbnail" width="420" height="420"></div>

<h3><a href="https://github.com/marketplace/actions/workflow-run-conclusion-dispatch-action" target="_blank" rel="noopener nofollow ugc">Workflow run conclusion dispatch action - GitHub Marketplace</a></h3>


  <p><span class="label1">Workflow run to repository dispatch. Event is `${workflowName} - ${conclusion}`, client_payload is the workflow run payload</span></p>

  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

**Comment by serializer** [comment]
<p>how to handle the case where the workflow having multiple triggers - workflow_run and workflow_dispatch? what will be the default value of workflow_run.conclusion then?</p>

**Comment by mattpopa** [comment]
<p>did you happen to get <code>github.event.workflow_run.conclusion</code> empty, when is should be <code>success</code>?</p>

**Reply by mstmustisnt** [reply]
I'm getting no workflow_run event at all,  I tried to log `github` contents:
```
name: Deploy to Preview Channel (Staging)

on:
  ......
  workflow_run:
    workflows: [Lint-n-Test]
    types: [completed]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
```

**Comment by bukowa** [comment]
Yes it's working but jobs executed by `workflow_run` don't appear in status checks, is there any workaround?

**Comment by pantelis-karamolegkos** [comment]
This is a good feature request however. To add `successful` and perhaps `failed` types in the `workflow_run` event.

**Comment by JeremyDemlow** [comment]
Why can you not have a standard dependency tree in which I have two workflows using two different computes that need to run in a separate workflow? Love what @pantelis-karamolegkos  is saying here as well make a lot of sense.

why can we not have this wait till they are both complete or both successful I agree that that seems very odd but the need to have two jobs for example a docker image being built and the terraform resources are completed prior to executing this job rather than it defaulting to execute two jobs. 

Sure can I look into GitHub check the history and if within the last 5 minutes it ran don't continue but why would that be something a user would need to do

**Comment by samuelgfeller** [comment]
Does anyone have a link to submit a feature request to add the types `success` and `failure` or an issue we can vote on? It was an issue in 2020 and still is in 2023.   
Do they work on that or provided some kind of explanation on why they don't add such a seemingly obvious and simple feature?

**Reply by svikash4** [reply]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run

**Comment by miigotu** [comment]
success and error status types for all acting events (even push or merge, so you can run something if a push was rejected or a merge failed)

And, the best case scenario would be, inheritance (or import, however you want to call it) would be the best route. Import/inheritance should only be allowed from that local repository for security. 

Say you have a bunch of actions that require you to checkout, set up python, set up node, yarn, poetry , and buildx/docker/qemu in some others, you should be able to do:


A special key like "inherits" or "import-jobs" or even *uses" at the job or steps level, with the format " `{workflow}.{jobs|env|any-valid-key}.{steps|valid-subkey}.{job-id|deeper subkey}`
Examples:
 `docker.jobs` would be all of the jobs and subinformation of the jobs in the docker workflow.
`docker.jobs.build_push` would be the build_push job in the docker workflow
`docker.jobs.build_push.steps.qemu` 
`docker.jobs.build_push.runs-on`

`buildx.env.IMAGE_TAG` would be the IMAGE_TAG variable set in env: in the buildx workflow

```yaml

env: |
  IMAGE_TAG: ${{import("docker.env.IMAGE_TAG")

jobs:
  strategy:
      matrix:
        os: ${{ import("docker.jobs.matrix.os")}}
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world" 
      - uses: [ "environment.jobs.environment.steps.devops",  "linter.jobs.linting.steps.flake8" ]
      - run: |
          echo "All environment jobs and then linter jobs just ran in order, stopping execution if fail-fast is set in the matrix"

  qemu:
    - run: |
        echo "set up qemu"
    - uses: "docker.jobs.qemu" 
  import-jobs: [ "docker.jobs.buldx", "build.jobs", "release.jobs.upload.steps.push"  ] # import the entire buildx job from the docker workflow and run it as a job here, and then do the same with all of the jobs from the build workflow, and then just the push step from upload job in the release workflow - in the order they are specified (can also just be a string and just run one)
  finish:
    - run: |
      echo "all done" 
```

This sort of flexibility would make GitHub actions the most comprehensive and feature complete ci there is, and it would be the easiest to maintain your scripts and workflows because you D.R.Y

Anyone know if I could contribute something like this to GitHub? Where?
