### DISCUSSION TITLE
How to conditionally include/exclude items in matrix (eg. based on branch)?

### DISCUSSION THREAD

**Discussion by DanTup** [community/community#26253] [Actions]
<p>I have a matrix like this:</p>
<pre><code>strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10]
        dart-version: [stable, dev]
        code-version: [stable, insiders]
</code></pre>
<p>I would like to only run the dev-dart and insiders-vscode builds for the master branch, and have only the stable/stable versions run for other branches. I can’t find a way to make these values conditional (either here, or by using exclude).</p>

**Comment by BrightRan** [comment]
<p>Hi <a class="mention" href="/dantup">@dantup</a> ,</p>
<p>Currently, GitHub Actions does not support to filter breaches for matrix jobs.</p>
<p>However, as a workaround, you can try to copy two workflows, one only for master branch and one for other branches, then set different branch filters on event and configure different values for the matrix parameters based on the branches.</p>
<ul>
<li>In the workflow for master branch, you can configure the branch filters and matrix like the below example:</li>
</ul>
<p><img src="https://user-images.githubusercontent.com/46307996/181096453-d01e8536-9285-44b6-b2d0-cd17de409a84.png" alt="forMaster.PNG" data-base62-sha1="3YUSMGUDI1CkXUyFMD6JOGOu98k" width="358" height="311"></p>
<ul>
<li>In the workflow for other branches, you can configure the branch filters and matrix like the below example:</li>
</ul>
<p><img src="https://user-images.githubusercontent.com/46307996/181096454-2ef25bcd-ae21-4fa9-9091-0e9178a55ed8.png" alt="forOther.PNG" data-base62-sha1="9ShkjJmOiZfeNS81xOwQNk62Vwe" width="355" height="312"></p>

**Comment by DanTup** [comment]
<p>Thanks - that would probably work, but my workflow is quite large and maintaining two of them wouldn’t be ideal. Is it possible this may change in future? To do something similar on Travis, you can have a top-level <code>if</code> block:</p>
<pre><code>if: tag IS blank AND ((branch = master and type = push) OR (env(ONLY_RUN_DART_VERSION) = env(ONLY_RUN_CODE_VERSION)))
</code></pre>
<p>And on AppVeyor you can use a <code>for</code> block to specify some combinations that only run for a certain branch:</p>
<pre><code>for:
  -
    branches:
      only:
        - master
    environment:
      matrix:
        - ONLY_RUN_CODE_VERSION: DEV
          ONLY_RUN_DART_VERSION: STABLE
        - ONLY_RUN_CODE_VERSION: STABLE
          ONLY_RUN_DART_VERSION: DEV
</code></pre>

**Comment by peter-dolkens** [comment]
<p>I’m looking for something similar - I’m actually trying to only run the job if the matrix option matches a particular value - unfortunately it seems that’s not an option at the job level, so I’d have to do it at the step level, which defeats the purpose</p>

**Comment by solodon4** [comment]
<p>I’m looking for something similar as well: out of my 4 target configurations Ubuntu, MacOS, Android and iOS I would like to specify that only Ubuntu configuration should be ran on regular daily check-ins into say master (to save me precious minutes), while all 4 configurations should only be ran when I create a version tag (since I also need binaries released for each of the versions). The condition for inclusion of a specific configuration might become more complicated later, but this should be a useful enough use case scenario for you to consider.</p>
<p>Here is one thing I tried. In your post from October 1, 2019 “<a href="https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/" title="GitHub Actions - New Workflow Syntax Features" rel="nofollow noopener">GitHub Actions - New Workflow Syntax Features</a>” you announce support for if: at the job level. So one natural thing I tried was:</p>
<pre><code>name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: matrix.os == 'ubuntu-latest' # This line fails with error
    steps:
</code></pre>
<p>but the conditional line gave me error: </p>
<table><tbody>
<tr><td><div>
<p><span>Invalid workflow file</span></p>
<div><pre>The workflow is not valid. .github/workflows/ci.yml (Line: 61, Col: 9):<br>Unrecognized named-value: 'matrix'. Located at position 1 within expression: matrix.os == 'ubuntu-latest'</pre></div>
</div></td></tr>
<tr><td>
<p> </p>
<p>Why would you disallow usage of matrix variable there?</p>
</td></tr>
</tbody></table>

**Comment by hpoul** [comment, marked as answer]
<p>I think I have now found a workaround for <strong>excluding</strong> matrix options based on branch. The idea is to simply add the <code>github.ref</code> variable to the matrix and then <code>exclude</code> it:</p>
<pre><code class="lang-yaml">    strategy:
      matrix:
        flavor: ['playstoredev', 'samsungapps', 'sideload', 'huawei', 'amazon']
        shouldRelease:
          - ${{ contains(github.ref, 'stable') || startsWith(github.ref, 'refs/heads/v') }}
        isMaster:
          - ${{ contains(github.ref, 'master') }}
        exclude:
          - shouldRelease: false
            flavor: amazon
          - shouldRelease: false
            flavor: huawei
          - shouldRelease: false
            flavor: samsungapps
</code></pre>
<p>with this configuration only on all branches with ‘stable’ in the name as well as beginning with ‘v’ all flavors will be built, while on all other branches i exclude the mentioned flavors.</p>

**Comment by northern-mindset** [comment]
<p>Dynamic matrix can be used according to this example: <a href="https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6" rel="noopener nofollow ugc">https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6</a>.</p>
<pre><code class="lang-auto">name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: build
</code></pre>
<p>However I have not figured out how to construct the matrix as a string… Maybe someone of you could figure it out and share.</p>

**Comment by joaomcteixeira** [comment]
<p>Thanks. Your strategy worked for me! In case anyone wants to have a look, here’s the addition: <a href="https://github.com/joaomcteixeira/python-project-skeleton/pull/31" class="inline-onebox" rel="noopener nofollow ugc">Disable `pr` env in `main` branch by joaomcteixeira · Pull Request #31 · joaomcteixeira/python-project-skeleton · GitHub</a></p>

**Comment by antifuchs** [comment]
Similar here, thank you! I use the following to run only the (fast) linux/amd64 docker build in pull requests:

```yml
  docker_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        isPR:
          - ${{github.event_name == 'pull_request'}}

        # Run only the amd64 build in pull reqs:
        exclude:
          - { isPR: true }
        include:
          - { platform: "linux/amd64" }
```

**Comment by jyyogi** [comment]
not sure whether this helps the OP's issue, but i landed here when trying to figure out how to do conditional matrix values.

here, what i want is to set defaults for my automated deploys and then accept an input for manual deploys.

the big unlock for me is that matrix works with sequences so we can pass them in via `fromJson`:

```yaml
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        type: choice
        required: true
        options:
          - sandbox
          - dev
          - staging
          - prod
  push:
    tags: # or whatever automated thing
      - *

jobs:
  deploy:
    strategy:
      matrix:
        # defaults defined inline here
        env: ${{ github.event.inputs.env && fromJson(format('["{0}"]', github.event.inputs.env)) || fromJson('["dev", "staging"]') }} 
```
