### DISCUSSION TITLE
How to check if a container image exists on GHCR?

### DISCUSSION THREAD

**Discussion by ten-chh** [community/community#26279] [Actions]
<p>I’m using GHCR as my container registry. The GitOps automation we use breaks if an engineer specifies an image that doesn’t exist. For example, if the last built image is <code>ghcr.io/my-company/my-image:1.0</code> but the engineer specifies <code>ghcr.io/my-company/my-image:1.1</code> the automation breaks.</p>
<p>Is there a way use the GHCR v2 http API or the GitHub API to check if a specific image/tag combination exists? And what PAT scopes are needed for the check (if it is available)?</p>

**Comment by airtower-luna** [comment]
<p>GHCR supports the <a href="https://docs.docker.com/registry/spec/api/">Docker Registry API</a>. You could either try to download the specific tag and see if you get a valid manifest, or retrieve the list of tags and check if the tag shows up. You’ll need to use a token with <em>read:packages</em> scope for the requests.</p>
<p>That said, maybe it’s better to catch and handle the error that currently occurs instead of adding a separate check? After all, the error occurring already tells you that the tag doesn’t exist. :wink:</p>

**Reply by rohitpranav** [reply]
Request the manifest for a specific tag.
If the request succeeds (HTTP 200), the tag exists.
If it returns 404 Not Found, the tag doesn't exist.
List all tags for the image and check whether your desired tag is included.

To do either, you'll need a GitHub Personal Access Token (PAT) with the read:packages permission.

However, their main recommendation is not to add a separate "does this tag exist?" check.

Instead, they suggest simply handling the error when you try to pull or use the image:

Attempt to use the image.
If it fails because the tag doesn't exist (for example, a 404 or manifest-not-found error), catch that error and handle it gracefully.

The reasoning is that the failed pull already tells you the tag is missing, so performing an extra API call beforehand is unnecessary and adds complexity. This is a common software engineering practice known as "fail fast and handle the exception."

**Comment by ten-chh** [comment]
<p>I’m asking specifically because other topics reference portions of the Docker Registry API that haven’t been implemented yet (e.g. <code>/v2/_catalog</code> - <a href="https://github.community/t/ghcr-io-docker-http-api/130121" class="inline-onebox">Ghcr.io docker HTTP API</a>). When I attempt to use the <code>/v2/&lt;name&gt;/tags/list</code> API endpoint, I get <code>{"errors":[{"code":"UNAUTHORIZED","message":"authentication token not provided"}]}</code>. But using the same username and PAT I’m able to successfully access the <code>/v2/</code> API endpoint. I double-checked that the user has <code>Read</code> access to the GHCR package that I’m trying to access.</p>
<p>Additionally, we are using a third-party GitOps package which breaks when it tries to install an image that doesn’t exist. So we’re opting to check the GitOps definition during the lint/test phrase before even executing the GitOps process.</p>

**Comment by clarkbw** [comment, marked as answer]
<p>You can use the <code>tags/list</code> endpoint to grab all available tags.</p>
<p>You’ll need a token for this like a PAT. (soon this will work with the <code>GITHUB_TOKEN</code>)</p>
<p>Here’s an example:</p>
<pre><code class="lang-auto"># for a public image you can get a fake NOOP token to use
curl https://ghcr.io/token\?scope\="repository:USER/IMAGE:pull"
{"token":"{TOKEN}"}
curl -H "Authorization: Bearer {TOKEN}" https://ghcr.io/v2/USER/IMAGE/tags/list
{"name":"USER/IMAGE","tags":["2.7.5-arm64","2.7.5-armhf","2.7.5-amd64"]}
</code></pre>

**Reply by rohitpranav** [reply]
nice to hear

**Comment by 13013SwagR** [comment]
<p>Now that <a href="http://ghcr.io" rel="noopener nofollow ugc">ghcr.io</a> supports GITHUB_TOKEN, you can do the following</p>
<pre><code class="lang-auto">GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
# To list tags
curl -H "Authorization: Bearer ${GHCR_TOKEN}" https://ghcr.io/v2/USER/IMAGE/tags/list
# To pull manifest
OLD_TAG=test
MANIFEST=$(curl -H "Authorization: Bearer ${GHCR_TOKEN}" https://ghcr.io/v2/USER/IMAGE/manifests/$OLD_TAG)
# To push a new tag
CONTENT_TYPE="application/vnd.docker.distribution.manifest.v2+json"
NEW_TAG=latest
curl -f -X PUT -H "Content-Type: ${CONTENT_TYPE}" -H "Authorization: Bearer ${GHCR_TOKEN}"  -d "${MANIFEST}" "https://ghcr.io/v2/USER/IMAGE/manifests/$NEW_TAG"
</code></pre>
<p>Cheers</p>

**Reply by tsnobip** [reply]
this should be the answer now

**Reply by austinworks** [reply]
super helpful.  the first curl example is missing a $ though, it should be as follows:

```
# To list tags
curl -H "Authorization: Bearer ${GHCR_TOKEN}" https://ghcr.io/v2/USER/IMAGE/tags/list
```

**Reply by victorlin** [reply]
Why does the GitHub token have to be base64-encoded?

**Reply by NiceGuyIT** [reply]
> `GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)`

While this works, it's missing one important piece of information: `-n`! That's right! The trailing newline **is required** to be included in the `base64` encoding for authentication to succeed. The GitHub developer doesn't know BASH (shell scripting?) well enough to know that `-n` should be added to all `echo -n "${SOME_STRING}"` to prevent the trailing newline from being interpreted in the down pipe (next command). Yeah, I wasted a little bit of time on this wondering why I'm getting authorization denied when using a language that properly trims whitespace before encoding.

**Comment by miohtama** [comment]
<p>Based on <a class="mention" href="/13013swagr">@13013SwagR</a>’s answer, here is my shell script version for Bash/command line.</p>
<h3>
<a name="creating-personal-access-token-pat-to-access-github-container-registry-1" class="anchor" href="#creating-personal-access-token-pat-to-access-github-container-registry-1"></a>Creating Personal Access Token (PAT) to access Github container registry</h3>
<ul>
<li>Go to <a href="https://github.com/settings/tokens" rel="noopener nofollow ugc">Personal tokens</a> in Github Developer settings.</li>
<li>Generate new token</li>
<li>Save the token in the password manager</li>
<li>Select the <code>read:packages</code> scope to download container images and read their metadata.</li>
<li>Select the <code>write:packages</code> scope to download and upload container images and read and write their metadata.</li>
<li>Select the <code>delete:packages</code> scope to delete container images.</li>
</ul>
<h3>
<a name="listing-available-tags-for-a-container-on-ghcr-2" class="anchor" href="#listing-available-tags-for-a-container-on-ghcr-2"></a>Listing available tags for a container on GHCR</h3>
<p>First set your PAT in <code>GITHUB_TOKEN</code> environment variable</p>
<pre><code class="lang-shell">echo $GITHUB_TOKEN
</code></pre>
<p>Should give your PAT token that looks lke:</p>
<pre><code class="lang-auto">ghp_mmc...
</code></pre>
<p>The PAT needs to be converted to base64 encoding for GHCR REST API.</p>
<pre><code class="lang-shell">export GHCR_TOKEN=$(echo $GITHUB_TOKEN | base64)
</code></pre>
<p>To list tags for organisation/user <code>myorg</code> for project <code>myproject</code></p>
<pre><code class="lang-auto">curl -H "Authorization: Bearer $GHCR_TOKEN" https://ghcr.io/v2/myorg/myproject/tags/list
</code></pre>
<p>You should get a JSON reply like:</p>
<pre><code class="lang-auto">{"name":"myorg/myproject","tags":["pr-58"]}
</code></pre>
<p><a href="https://github.com/tradingstrategy-ai/frontend/blob/5fa560dd029a44b5e66df6c63ca2b7884274345a/.github/workflows/javascript.yml#L53" rel="noopener nofollow ugc">Here is also our Github Actions build recipe how to build and push images to GCHR</a>.</p>

**Reply by KES777** [reply]
How to delete pushed image?
```
export GH_TOKEN=`cat jenkins | base64` && curl --fail -H "Authorization: Bearer $GH_TOKEN" -X DELETE https://ghcr.io/v2/org/repo/manifests/sha256:b69a90aedbaf76b83af2d89c61c22a9c3bd683912e8ef58eb7166be86e70a5bf
```

I get `curl: (22) The requested URL returned error: 405`. What is the problem here?

**Reply by airtower-luna** [reply]
It seems you're trying to use the Docker registry API. GHCR doesn't allow deleting that way, you need to use the [packages API](https://docs.github.com/en/rest/packages#delete-a-package-version-for-the-authenticated-user). If you need more help please create a new thread, because you're asking a new question.

**Comment by mcandre** [comment]
REST services are okay, but what would really help users out is a basic search frontend, like Docker Hub enjoys.

**Reply by mydreamdoctor** [reply]
PLEASE!

**Reply by relsqui** [reply]
or even a command in the github cli

**Comment by ayushi469** [comment]
How can we list all the docker images that we have on the GitHub container registry?

**Reply by airtower-luna** [reply]
See here for your user packages (with `package_type=container`): https://docs.github.com/en/rest/packages?apiVersion=2022-11-28#list-packages-for-the-authenticated-users-namespace

Same thing for an organization: https://docs.github.com/en/rest/packages?apiVersion=2022-11-28#list-packages-for-an-organization

**Comment by mmm8955405** [comment]
It's difficult to query without a webui

**Comment by Adriansillo** [comment]
where is the documentation to use the API ?
i am using the `tags/list` endpoint but want to know about more useful endpoints

**Comment by younsl** [comment]
Hi fellas. I hope my use case will be helpful to many people.

Here is the workflow to check if a container image exists and push it to `ghcr.io`.

## Solutions

### Example Workflow

This workflow checks if a container image exists. If not, it builds and pushes a new version to GitHub Container Registry. It uses only the Automatic Token declared in the workflow, not a Classic PAT issued from the user account.

```yaml
name: Release backup-utils image
run-name: 📦 [younsl/backup-utils] Release backup-utils image (amd64)

on:
  workflow_dispatch:
    inputs:
      BACKUP_UTILS_VERSION:
        description: 'Version of github-backup-utils to use'
        required: true
        default: 3.14.0

env:
  IMAGE_NAME: younsl/backup-utils
  BACKUP_UTILS_VERSION: ${{ github.event.inputs.BACKUP_UTILS_VERSION }}

permissions:
  contents: read
  packages: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      image_exists: ${{ steps.image_check.outputs.image_exists }}
    steps:
      - name: Check if image exists on GitHub Container Registry
        id: image_check
        run: |
          ENCODED_TOKEN=$(echo -n "${{ secrets.GITHUB_TOKEN }}" | base64)
          TAGS=$(curl -s -H "Authorization: Bearer ${ENCODED_TOKEN}" \
            https://ghcr.io/v2/${{ env.IMAGE_NAME }}/tags/list)
          echo "TAGS: $TAGS"

          ## Check if TAGS is empty or null
          if [[ -z "$TAGS" || "$TAGS" == "null" ]]; then
            echo "No tags found, treating as image not existing."
            echo "image_exists=false" >> $GITHUB_OUTPUT
          else
            ## Check if the specific tag already exists
            if echo "$TAGS" | jq -e --arg TAG "${{ env.BACKUP_UTILS_VERSION }}" '.tags | index($TAG)'; then
              echo "Image with tag ${{ env.BACKUP_UTILS_VERSION }} already exists."
              echo "image_exists=true" >> $GITHUB_OUTPUT
            else
              echo "Image with tag ${{ env.BACKUP_UTILS_VERSION }} not found."
              echo "image_exists=false" >> $GITHUB_OUTPUT
            fi
          fi
  
  release:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.image_exists == 'false' }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Download and extract github-backup-utils
        id: prepare
        run: |
          echo "Downloading github-backup-utils version ${{ env.BACKUP_UTILS_VERSION }} ..."
          curl -L -o github-backup-utils-${{ env.BACKUP_UTILS_VERSION }}.tar.gz \
            https://github.com/github/backup-utils/releases/download/v${{ env.BACKUP_UTILS_VERSION }}/github-backup-utils-v${{ env.BACKUP_UTILS_VERSION }}.tar.gz
          echo "Extracting github-backup-utils tarball ..."
          tar -xzf github-backup-utils-${{ env.BACKUP_UTILS_VERSION }}.tar.gz

      - name: Login to GitHub Container Registry (ghcr.io)
        id: login
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build
        id: build
        run: |
          docker build \
            --platform linux/amd64 \
            -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.BACKUP_UTILS_VERSION }} github-backup-utils-v${{ env.BACKUP_UTILS_VERSION }}
            
      - name: Push
        id: push
        run: |
          docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.BACKUP_UTILS_VERSION }}
```

### Key Points

#### 1. **List image tags using `/tags/list` API**

This API retrieves a list of all image tags in your `ghcr.io` repository.

#### 2. **Base64 encoding for Authorization**

The bearer token must be Base64-encoded before making `/tags/list` API call.

Example for encoding the token in a GitHub Actions workflow:

```bash
# Actions Workflow file (release.yml)
ENCODED_TOKEN=$(echo -n "${{ secrets.GITHUB_TOKEN }}" | base64)
TAGS=$(curl -s -H "Authorization: Bearer ${ENCODED_TOKEN}" \
  https://ghcr.io/v2/${{ env.IMAGE_NAME }}/tags/list)
echo "TAGS: $TAGS"
```

#### 3. Automatic Token for Authentication

> [!WARNING]
> Only applicable if you use Actions Workflow. If you are running the script in your local environment, you will still need the actual user's Classic Personal Access Token.

You don't need to use a Classic PAT<sup>Personal Access Token</sup> issued from the user account. GitHub's [Automatic Token](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication)<sup>`${{ secrets.GITHUB_TOKEN }}`</sup> handles all operations securely without requiring periodic renewals.

#### 4. Permission Issues on Push

If you encounter a `denied: permission_denied: write_package` error after successfully login to ghcr.io, it means the workflow lacks the necessary permissions to push the Docker image. Ensure that the workflow has the proper access to the package in GitHub Packages. You can adjust the permissions in the repository’s settings under Manage Actions access, and verify that the workflow repository is granted write permission.

Common `denied: permission_denied` Error Example:

```bash
Pushing Docker image ghcr.io/<USERNAME>/<IMAGE_NAME>:3.14.0 to ghcr.io ...
The push refers to repository [ghcr.io/<USERNAME>/<IMAGE_NAME>]
...
3ec3ded77c0c: Preparing
denied: permission_denied: write_package
```

> [!NOTE]
> Check that the appropriate **write** permissions are granted under Packages settings. See [Publishing and installing a package with GitHub Actions](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio) and [Publishing images to GitHub Packages](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages).

![image](https://github.com/user-attachments/assets/bb00bdae-07a7-4583-819d-a86e60546b96)
