### DISCUSSION TITLE
Execution order for multiple workflows in one repo

### DISCUSSION THREAD

**Discussion by DaHuoKolmostar** [community/community#26271] [Actions]
<p>I wonder what is the order of multiple workflows in one repo. Is it possible to run them in parallel?</p>

**Comment by airtower-luna** [comment]
<p>They may get run in parallel, yes, but there’s no guarantee. It mostly depends on how full the queue is, assuming you’re not hitting the limits for parallel jobs.</p>

**Comment by weide-zhou** [comment, marked as answer]
<p>Hi <a class="mention" href="/dahuokolmostar">@dahuokolmostar</a>,</p>
<p>Every workflow needs an event trigger defined in the yaml file, if your operation triggers the event, the workflow will be started, they can be in parallel.<br>
For example, push events in two yaml files on master branch, if you push commit to master branch, both workflows will be started.<br>
But you still need to be aware of the usage limit, specially cocurrent jobs, please refer to the official doc for more details:<br>
<a href="https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits" rel="nofollow noopener">https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits</a>.</p>
<p>Thanks</p>

**Comment by jeff-vincent** [comment]
<p>Is it possible to require the workflows to run in a predetermined order (not in parallel)?</p>

**Reply by stephencharette** [reply]
@jeff-vincent See my reply to @lestephane for a workflow configuration that worked for me

**Comment by lestephane** [comment]
<p>This is also of interest to me. I have a monorepo with multiple sub-modules, and use multiple workflow <code>.yml</code> files. So if a developer creates a pull request that matches path filters in two or more modules (say, frontend AND backend), I may want to have an influence on the order the workflows are matched and run within the same concurrency group (say backend always before frontend).</p>
<p>Same problem mentioned at <a href="https://github.community/t/monorepo-test-package-then-test-integration-with-all-packages/173609" class="inline-onebox">Monorepo – test package then test integration with all packages</a> (without solution), and the solution mentioned at <a href="https://github.community/t/basic-workflow-structure-for-a-monorepo/17093/5" class="inline-onebox">Basic workflow structure for a monorepo - #5 by weide-zhou</a> looks awfully complicated (it has to parse the diff on its own, which completely defeats the purpose of path filters).</p>
<p>This lets me think that monorepos are not first class citizens in GitHub.</p>

**Reply by stephencharette** [reply]
I wanted this same functionality, where one workflow is prioritized to run before another. This is my implementation which enforces the `first_cd.yml` workflow to run before the `second_cd.yml`. These also check if any files changed within their respective directories.

```
# .github/workflows/first_cd.yml
name: First Continuous Deployment

on:
  push:
    branches:
      - develop
jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      src:
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
            - 'firstpath/**'
  do_something:
    needs: check_changes
    if: needs.check_changes.outputs.src == 'true'
    runs-on: ubuntu-latest
    steps:
        run: echo "do something"
```

```
# .github/workflows/second_cd.yml
name: Second Continuous Deployment

on:
  workflow_run:
    workflows: [First Continuous Deployment]
    types:
      - completed

jobs:
  success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The First workflow completed successfully.'
  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The First workflow failed.'
  exit:
    needs: failure
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  check_changes:
      needs: success
      runs-on: ubuntu-latest
      outputs:
        src:
      steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'secondpath/**'
  do_something:
    needs: check_changes
    if: needs.check_changes.outputs.src == 'true'
    runs-on: ubuntu-latest
    steps:
        run: echo "do something"
```
