### DISCUSSION TITLE
Secrets in matrix

### DISCUSSION THREAD

**Discussion by MGarfOppLoans** [community/community#26302] [Actions]
<pre><code>name: Deployment

on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        envs: [ENVONE]
        include:
          - envs: ENVONE
            VAR_API_KEY: ${{secrets.ENVONE_API_KEY}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Deployment
        run: |
          echo hello
        env:
          VAR_API_KEY: ${{maxtrix.envs.VAR_API_KEY}}
</code></pre>
<p>The above yaml file causes the following error.</p>
<pre><code>- Your workflow file was invalid: The pipeline is not valid. .github/workflows/default.yml (Line: 14, Col: 33): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.ENVONE_API_KEY,.github/workflows/default.yml (Line: 15, Col: 30): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.ENVONE_API_KEY
</code></pre>
<p>According to the documentation that is how you pass a secrets reference? Any thoughts what I did wrong here?</p>

**Comment by BrightRan** [comment, marked as answer]
<p>It seems that the values of matrix parameters should be specified only with actual values, and can’t use variables (secrets, environment variables).</p>
<p>And in the example you shared, the parameters <strong>envs</strong> and <strong>VAR_API_KEY</strong> are at the same level and no affiliation. So the expression <strong>${{maxtrix.envs.VAR_API_KEY}}</strong> you used to call <strong>VAR_API_KEY</strong> is incorrect, you should use <strong>${{maxtrix.VAR_API_KEY}}</strong>.</p>

**Comment by daveespo** [comment]
<p>You can define the Secret <strong>name</strong> in your matrix configuration and then dereference it in the Steps using array notation. This is what ours looks like:</p>
<pre><code>strategy:
  matrix:
    org: [apples, bananas, carrots] #Array of org mnemonics to use below
    include:
      # includes a new variable for each org (this is effectively a switch statement)
      - org: apples
        sfdxurl_secret: APPLES_SFDXURL
      - org: bananas
        sfdxurl_secret: BANANAS_SFDXURL
      - org: carrots
        sfdxurl_secret: CARROTS_SFDXURL

steps:
  - uses: actions/checkout@v2
  - uses: sfdx-actions/setup-sfdx@v1
    name: Install SFDX CLI and authorize org
    with:
      sfdx-auth-url: ${{ secrets[matrix.sfdxurl_secret] }}
</code></pre>

**Reply by ghost** [reply]
@daveespo This saves my day.

**Reply by MikeBlomm** [reply]
Unfortunately it does not work when using `env:` instead of `with:`, the value stays empty. I'd like to use it in combination with a `run:` step which executes some cli commands and needs the secret interpolated. Any suggestions?

**Reply by mohammaDJ23** [reply]
What about if we had a scenario like this:
```
strategy:
  matrix:
    org: [apples, bananas, carrots] #Array of org mnemonics to use below
    include:
      # includes a new variable for each org (this is effectively a switch statement)
      - org: apples
        args: |
           APPLES_SFDXURL:  APPLES_SFDXURL
            APPLES_SFDXURL:  APPLES_SFDXURL
      - org: bananas
        args: |
          BANANAS_SFDXURL: BANANAS_SFDXURL
          BANANAS_SFDXURL: BANANAS_SFDXURL
      - org: carrots
        args: |
          CARROTS_SFDXURL: CARROTS_SFDXURL
          CARROTS_SFDXURL: CARROTS_SFDXURL
```

how we put those secrets in here:
```
sfdx-auth-url: ${{ secrets[matrix.args] }}
```

although this does not work, it is for clarifying.

**Comment by brunomuniz-encora** [comment]
<p>We’ve tried this exact same construct but in a <code>env</code> block instead of <code>with</code> and it doesn’t seem to resolve the secret…</p>

**Comment by aleks-ivanov** [comment]
<p>Magic! :slight_smile:</p>
<p>more characters</p>

**Comment by billzhuang** [comment]
<p><a class="mention" href="/daveespo">@daveespo</a> you save my day! tks.</p>

**Comment by codebydant** [comment]
@daveespo thanks!

**Comment by stephanelpaul** [comment]
instead of the this here just set a seret with matrix config, this is how i do it {\"hostnames\":[\"a\",\"b\"]}" 


```
on:
  workflow_dispatch:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-hostnames.outputs.matrix }}
    steps:
      - id: set-hostnames
        run: |
          echo "matrix={\"hostnames\":[\"a\",\"b\"]}" >> $GITHUB_OUTPUT
          
  test-matrix:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    steps:
      - name: Print the matrix hostname
        run: echo  The tags are ${{ matrix.hostnames }}

```
