### DISCUSSION TITLE
Syntax to refer to env var in container.image

### DISCUSSION THREAD

**Discussion by jamiet-msm** [community/community#26324] [Actions]
<p>I can’t figure out the syntax to refer to an environment variable in <code>jobs.&lt;job_id&gt;.container.image</code></p>
<p>This works OK:</p>
<pre><code class="lang-yaml">name: test

on:
  push:

jobs:
  job1:
    container:
      image: eu.gcr.io/path/to/image:tag
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - run: |
          echo "hello world"
        id: do
</code></pre>
<p>(I’ve left out the specifics of what the job is going but the point here is that this is running on a container image)</p>
<p>However if I do this:</p>
<pre><code class="lang-yaml">name: test

env:
  IMAGE: eu.gcr.io/path/to/image:tag

on:
  push:

jobs:
  job1:
    container:
      image: env.IMAGE
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - run: |
          echo "hello world"
        id: do
</code></pre>
<p>It fails with:</p>
<blockquote>
<p>Starting job container<br>
/usr/bin/docker pull env.IMAGE<br>
invalid reference format: repository name must be lowercase</p>
</blockquote>
<p>I’ve tried various other ways to get it to refer to the image name stored in my env var</p>
<p><code>image: ${env.IMAGE}</code><br>
<code>image: ${{env.IMAGE}}</code></p>
<p>but I can’t figure out the syntax. Help!!</p>

**Comment by airtower-luna** [comment, marked as answer]
<p>There is unfortunately no syntax that works, the <code>env</code> context is not available there. Relevant quote from <a href="https://docs.github.com/en/actions/learn-github-actions/contexts#env-context">the contexts documentation</a>:</p>
<blockquote>
<p>You can use the <code>env</code> context in the value of any key in a <strong>step</strong> except for the <code>id</code> and <code>uses</code> keys.</p>
</blockquote>

**Comment by jamiet-msm** [comment]
<p>Yes, very disappointing, thanks for the answer.</p>

**Comment by blackjid** [comment]
I don’t know if it fill your need, but you could run a job that reads the env value and set it as an output…<br>
Then read the output in the <code>container.image</code> key</p>

```yaml
env:
  IMAGE: eu.gcr.io/path/to/image:tag

on:
  push:

jobs:
  job0: 
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
    - id: set_image
      run: echo "::set-output name=image::${{IMAGE}}"

  job1:
    container:
      image: ${{ needs.job0.outputs.image }}
    needs: job0
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - run: |
          echo "hello world"
        id: do

```
