### DISCUSSION TITLE
Scheduled job on specific branches

### DISCUSSION THREAD

**Discussion by RamLavi** [community/community#26374] [Actions]
<p>Hi,<br>
it is my understanding from <a href="https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule" rel="noopener nofollow ugc">this</a> that we currently can’t set a scheduled event on a specific branch.<br>
something like:</p>
<pre><code class="lang-auto">name: My Workflow Job

on:
  schedule:
    - cron:  '0 5 * * *'
    - branches:
        - release-0.42

jobs:
  build:
...
</code></pre>
<p>am I correct to assume this?<br>
if so, is there a workaround to this?<br>
if not, is it planned on future gitActions versions?</p>

**Comment by airtower-luna** [comment, marked as answer]
<p>Yes, the workflow must be on the default branch to work. If you want to use code from another branch, you can still do that by <a href="https://github.com/actions/checkout#Checkout-a-different-branch">passing the branch name to the checkout action</a>:</p>
<pre><code class="lang-yaml">- uses: actions/checkout@v2
  with:
    ref: release-0.42
</code></pre>

**Reply by haroldo-bonette** [reply]
It does not work for all the scenarios, for example when you have a protection rule preventing deployments from other branches, since the WF is triggered from the default branch, the protection rule will be evaluated against the default branch and not to the ref you have defined in checkout...

**Reply by maelp** [reply]
Exactly, I'm in this scenario for daily tests from a different branch with a protected environment (I want to do tests on my production), is it possible to add this feature?

**Reply by tian-lan-landing** [reply]
For another example, my build step runs a new shell script in the repo. The script is not on the release branch yet, so checking out release branch will fail the build step since the new script is missing. I don't like to inline the shell script in the WF because I also want to run it locally.

**Reply by thetredev** [reply]
It's baffling to me that GitLab does these things easily while a billion dollar company like Microsoft doesn't even consider such a simple but effective feature.

**Comment by theothermattm** [comment]
I just want to point out that this feature doesn't really work well with environment protections.  Here's my use case:

My `staging` branch is my default branch as that's what I want devs to commit to.  The `main` branch gets updated when we go to production.

I want to be able to setup an environment for my `staging` branch which will run an action against a lower, non-procution environment, but not have access to secrets for the `production` environment.

With the schedule function, right now it automatically uses my default branch (`staging`) so in order to schedule a job against production I need to enable environment permissions for the lower environment's branch to be able to see the production secrets.  Not ideal at all. 

If I could specify which branch the schedule is triggered from, I could still have my environment protections (theoretically).

**Comment by thetredev** [comment]
GitHub is currently asking for feedback on Actions (just click on the Actions tab on any of your projects). I just gave them feedback about this topic. Hope it has an effect.

**Comment by maelp** [comment]
Is anyone from Github working on this? would be really useful to increase security of workflows

**Comment by maelp** [comment]
For people who want a temporary hack, here's how I do it to run on a non-default (eg production) branch with environment protection rules:

- add a job which just runs on the default branch and triggers a job deployment on the production branch
- the normal job running on the production branch

```yaml
# .github/workflows/my-scheduled-workflow.yml
name: My scheduled workflow on a non-default branch

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  # Hack which is used just to redirect the "scheduled" triggers to deploy/production, since we can't just tell Github (for now) to do a scheduled action on a branch different from the default branch
  trigger-action-on-deploy-production:
    if: github.refs != 'refs/head/my-production-branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Trigger production workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run .github/workflows/my-scheduled-workflow.yml \
            --ref my-production-branch

  do-the-action:
    if: github.refs == 'refs/heads/my-production-branch'
    runs-on: ubuntu-latest
    # Apply protection rules
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: my-production-branch

      - name: Run the scheduled action
        run: |
           echo "Scheduled job running (with a hack) on the production branch!"
```

or to be even safer (to avoid infinite loops), just do two jobs:
- a scheduled job which just trigger the other job (different workflow)
- the action to schedule, which can only be triggered manually or through the API

`schedule-trigger.yml`:

```yaml
name: SCHEDULE TRIGGER - Launch action

on:
  schedule:
    # Run daily at 05:00 UTC
    - cron: "0 5 * * *"

jobs:
  trigger-action-on-production:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger action on the production branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run .github/workflows/my-actual-workflow.yml \
            --ref production \
            --repo ${{ github.repository }}
```

and `my-actual-workflow.yml`:

```yaml
name: Run the actual action

on:
  workflow_dispatch:

jobs:
  test-infrastructure:
    runs-on: ubuntu-latest
    # GitHub Environment: provides access to environment-specific secrets and applies protection rules
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Run action
        run: my-test-script.sh
```
