### DISCUSSION TITLE
Running a bash script

### DISCUSSION THREAD

**Discussion by sigfrid** [community/community#26403] [Actions]
<p>Hi there,<br>
What is the simplest way to create a workflow that runs a bash script?<br>
I understand I can create a separate action which runs the script and use it in my workflow. I have done that for action shared among multiple repositories.</p>
<p>However, now I need to run a custom script in a single repo and, I feel a separate action is too much.</p>
<p>I’d like to be able to do run a bash script saved at ROOT/.github/script.sh but I can’t figure out how to specify the path in the run step of the workflow below.</p>
<blockquote>
<p>name: run-script<br>
on: push</p>
<p>jobs:<br>
run:<br>
runs-on: ubuntu-latest<br>
steps:<br>
- uses: actions/checkout@v1<br>
- name: script<br>
run: PATH/script.sh<br>
shell: bash<br>
with:<br>
password: ${{ secrets.ACCESS_TOKEN }}</p>
</blockquote>
<p>Thanks.</p>

**Comment by airtower-luna** [comment, marked as answer]
<p>With that setup the path to the script is relative to the root of your repository, so if your script is <code>.github/script.sh</code> that’s all that’s needed in the run step. Remember that the file must be marked as executable, or you need to explicitly call bash with the script as parameter.</p>

**Reply by dwenaus** [reply]
Example:
```
        - run:  bash ${GITHUB_WORKSPACE}/path/script.sh
```

**Reply by airtower-luna** [reply]
Specifying the full path isn't necessary, it could even break things if you use a job container, because the path where the workspace gets mounted into the container isn't the same as on the runner VM. :sweat_smile: 

Best stick to the relative path, e.g.:

```yaml
        - run:  bash path/script.sh
```

Some special care might be required if you change the default working directory. :wink:

**Comment by Simran-B** [comment]
<p>To be more explicit, you can write <code>./.github/script.sh</code>.</p>
<p>If you want to know the full path where the working copy resides in the runner, then you can do <code>run: pwd</code> which will print the working directory.</p>
<p>The absolute path should be <code>/home/runner/work/{repo-name}/{repo-name}/.github/script.sh</code>, so this should also work:</p>
<pre><code class="lang-yaml">- run: |
    # make file runnable, might not be necessary
    chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"

    # run script
    "${GITHUB_WORKSPACE}/.github/script.sh"
    # or
    "${{ format('{0}/.github/script.sh', github.workspace) }}"
</code></pre>

**Reply by maximkoretskiy** [reply]
I would suggest to update file access modes on git level. So you won't be required to change on every action run.

```sh 
 git update-index --chmod=-x  ./.github/script.sh
```

**Comment by sigfrid** [comment]
<aside class="quote no-group" data-username="airtower-luna" data-post="2" data-topic="141584">
<div class="title">
<div class="quote-controls"></div>
 airtower-luna:</div>
<blockquote>
<p>call bash with the script as parameter.</p>
</blockquote>
</aside>
<p>Thanks for the reply.</p>

**Comment by sigfrid** [comment]
<p>Thanks for your help.</p>

**Comment by Curiouspaul1** [comment]
what say i want to pass in a value (say from a gh secret) to the shell_script how would I do that?

**Reply by airtower-luna** [reply]
Usually with an environment variable. The exact syntax will vary depending on your command, of course. Mind that anything included on the command line may be visible to other processes, so it's safer to make your script read the environment variable directly.

```yaml
- run: ./your_script.bash
  env:
    YOUR_SECRET: ${{ secrets.YOUR_SECRET }}
```

And then look at the `YOUR_SECRET` variable in the script. You could also use `$YOUR_SECRET` in the command line, with the security caveat mentioned above.

**Reply by Curiouspaul1** [reply]
yes thank you very much, i understand.

**Comment by Brambillator** [comment]
I use like this:

```yaml
    - name: Build and Deploy Script
      working-directory: ${{ github.workspace }}/PROJECT_FOLDER
      run: bash ./publish-script.sh
```

**Reply by ghonchesefidi** [reply]
Worked for me. Thanks

**Reply by sammcj** [reply]
Thanks! I really wish Github's documentation wasn't so terrible - why is it hard to find such fundimental information like this!

**Reply by bencat-sixense** [reply]
It also can be done at job definition level:

```yaml
jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./scripts
```

**Comment by esterified** [comment]
worked for me after i added the action `actions/checkout@v4` 
here is the full code:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run bash script
        run: bash file.sh

```
