### DISCUSSION TITLE
How to use private Docker registry?

### DISCUSSION THREAD

**Discussion by diegobernardes** [community/community#26534] [Actions]
<p>I found multiple issues about this topic but they’re old and kinda not exploring the point that I want.</p>
<p>It’s easy to work around the limitation of the login of a private Docker registry inside a job. But how to run the actual job inside the Docker? That’s the question.</p>
<p>I want to use <a href="https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer" rel="nofollow noopener">jobs.&lt;job_id&gt;.container</a> and <a href="https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices" rel="nofollow noopener">jobs.&lt;job_id&gt;.services</a> with private Docker images.</p>
<p>There is any way to make it work? Or maybe any kind of workaround? if not, there is any roadmap or indication that this feature gonna be developed?</p>
<p>On GitLab CI this is solved using <em>before_script</em>:</p>
<pre><code>before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
</code></pre>
<p>This would be an amazing feature for GitHub Actions.</p>

**Comment by BrightRan** [comment]
<p>When using the syntaxes  <strong>jobs.&lt;job_id&gt;.container.image</strong> or <strong>jobs.&lt;job_id&gt;.services.image</strong> to set a Docker image as a container (or service container) for a job, the Docker image can be the Docker base image name or a public docker Hub or registry. You can’t use the image from a private Docker registry.</p>
<p>If you reallly need this feature, I recommend you directly share your suggestions <a href="https://support.github.com/contact/feedback?contact%5Bcategory%5D=actions" rel="nofollow noopener">here</a>. That will allow you to directly interact with the appropriate engineering team, and make it more convenient for the engineering team to collect and categorize your suggestions.</p>

**Comment by gitfool** [comment]
<p>FWIW, I’ve had success with the workaround to use an internal repo action, as mentioned in <a href="https://github.community/t/github-actions-new-pulling-from-private-docker-repositories/16089/6">https://github.community/t5/GitHub-Actions/Github-Actions-new-Pulling-from-private-docker-repositories/m-p/32024/highlight/true#M986</a>, where I first login to AWS ECR, pull the private image, then use the local action to effectively “docker run” with the private image.</p>

**Comment by karrtikr** [comment]
<aside class="quote no-group" data-username="gitfool" data-post="3" data-topic="17599">
<div class="title">
<div class="quote-controls"></div>
 gitfool:</div>
<blockquote>
<p>use the local action to effectively “docker run” with the private image.</p>
</blockquote>
</aside>
<p>Can you please elaborate on what a “local action” is referring to? I do not wish to use the docker run command explicitly. Basically what I am asking is how to run steps inside the docker container?</p>

**Comment by twistedpair** [comment]
<p>I don’t think that’s supported.</p>
<p>I too run all the explicit docker commands in bash right now for lack of this feature.</p>

**Comment by gitfool** [comment]
<p><a class="mention" href="/karrtikr">@karrtikr</a> this is what I use, which might not help you since I use <a href="https://github.com/cake-build/cake" rel="nofollow noopener">cake build</a> at the tail end:</p>
<p><code>.github/workflows/build.yml</code>:</p>
<pre><code class="lang-auto">name: Build
on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  pull_request:
    branches:
      - master
  repository_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  NUGET_USERNAME: pharos
  NUGET_PASSWORD: ${{ secrets.PACKAGES_PAT }}
  NUGET_SOURCE: https://nuget.pkg.github.com/pharos/index.json
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Patch config
        shell: pwsh
        run: ./NuGet.ps1 NuGet.config github pharos ${{ secrets.PACKAGES_PAT }}

      - name: ECR login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker pull
        run: docker pull &lt;id&gt;.dkr.ecr.us-east-1.amazonaws.com/pharos/build/cake-docker:latest

      - name: Cake build
        uses: ./.github/actions/cake-build
</code></pre>
<p><code>.github/actions/cake-build/action.yml</code>:</p>
<pre><code class="lang-auto">name: Cake build
runs:
  using: docker
  image: docker://&lt;id&gt;.dkr.ecr.us-east-1.amazonaws.com/pharos/build/cake-docker:latest
  args: [ "bash", "-c", "dotnet tool restore &amp;&amp; dotnet cake --bootstrap --verbosity=verbose &amp;&amp; dotnet cake --verbosity=verbose --target=build --publish=true" ]
</code></pre>
<p>In summary:</p>
<ul>
<li>Login to aws ecr private repo (using aws env vars)</li>
<li>Pull docker image from aws ecr private repo (note: redacted id)</li>
<li>Run “local action” using git repo relative reference (<code>./.github/actions/cake-build</code>)</li>
<li>Bash command is subsequently run inside a container using previously pulled docker image</li>
<li>… In this case the remaining steps are handled by <a href="https://github.com/cake-build/cake" rel="nofollow noopener">cake build</a>
</li>
</ul>

**Comment by missedone** [comment]
<p>here is my solution for self-hosted runner for pulling private images from AWS ECR: <a href="https://github.community/t/github-actions-new-pulling-from-private-docker-repositories/16089/15" class="inline-onebox">Github Actions (new) Pulling from private docker repositories</a></p>

**Comment by jirihradil** [comment]
<p>This works for me:</p>
<pre><code class="lang-yaml">name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: "Build and test"
    runs-on: ubuntu-latest
   
    steps:
       
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Pull image from DockerHub
      run: docker pull company/repo:version

    - name: Run image in container
      run: docker run --detach company/repo:version
...
</code></pre>

**Comment by TechplexEngineer** [comment, marked as answer]
<p>Looks like support for private registries</p>
<aside class="onebox allowlistedgeneric">
  <header class="source">
      <img src="https://github.blog/wp-content/uploads/2019/01/cropped-github-favicon-512.png?fit=32%2C32" class="site-icon" width="32" height="32">
      <a href="https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/" target="_blank" rel="noopener nofollow ugc">The GitHub Blog</a>
  </header>
  <article class="onebox-body">
    <div class="aspect-image" style="--aspect-ratio:690/362;"><img src="https://github.blog/wp-content/uploads/2019/03/blog-card.png?fit=5001%2C2626" class="thumbnail" width="690" height="362"></div>

<h3><a href="https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/" target="_blank" rel="noopener nofollow ugc">GitHub Actions: Private registry support for job and service containers -...</a></h3>

<p>GitHub Actions: Private registry support for job and service containers</p>


  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

**Comment by diegobernardes** [comment]
<p>I was not aware of that, thanks. This really solves the problem.</p>

**Comment by dezren39** [comment]
<p>Unfortunately, this only partially solves the issue. ECR only allows passwords up to 12 hours. We typically use amazon-ecr-login in order to get around this, however this action doesn’t provide the passwords and the passwords would only be available after that step.</p>
<p>Users are forced to embed an api token as a secret, then schedule a job every 6 hours which updates another secret that is then used in the jobs. Rough. Really rough.</p>

**Reply by prein** [reply]
What would be sufficient IIUC is for the `container.credentials.password` field to accept output from another job.

**Reply by prein** [reply]
I just tested it and it actually works. Below is a snippet I used to test it. I use OIDC but that doesn't change anything here.

```
jobs:
  login-ecr:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      docker_user: ${{ steps.login-ecr.outputs.docker_username_123456789012_dkr_ecr_us_east_1_amazonaws_com }}
      docker_password: ${{ steps.login-ecr.outputs.docker_password_123456789012_dkr_ecr_us_east_1_amazonaws_com }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.IAM_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS container registry
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


  run_container:
    runs-on: ubuntu-latest
    needs: [login-ecr]
    container:
      image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-image:0.0.1
      credentials:
        username: ${{ needs.login-ecr.outputs.docker_user }}
        password: ${{ needs.login-ecr.outputs.docker_password }}
    steps:
      - name: Hello world
        run: cat /etc/issue
```
