### DISCUSSION TITLE
Fatal: could not read Username for 'https://XXXXXX': No such device or address

### DISCUSSION THREAD

**Discussion by icasimpan** [community/community#26580] [Actions]
<p>Hi,</p>
<p>Our company has an opensource project that we want to sync to drupal’s git repo.<br>
So taking an inspiration from a drupal-based project, I took the relevant code and tweaked it a bit to fit our situation.</p>
<p>I do have the needed access to drupal’s project repo and I’m using the same credentials for this github actions.</p>
<p>The github actions yaml file is in <a href="https://github.com/promet/provus/blob/26a3f180516dadea9539065968906f088ae46790/.github/workflows/develop-sync.yml" class="inline-onebox" rel="noopener nofollow ugc">provus/develop-sync.yml at 26a3f180516dadea9539065968906f088ae46790 · promet/provus · GitHub</a></p>
<p>I even explicitly added my username (icasimpan) to secrets.DRUPAL_REPO_URL but I still see the issue</p>
<blockquote>
<p>fatal: could not read Username for ‘XXXXXX’: No such device or address</p>
</blockquote>
<p>this can be seen in <a href="https://github.com/promet/provus/runs/2404349434?check_suite_focus=true" class="inline-onebox" rel="noopener nofollow ugc">Test push · promet/provus@26a3f18 · GitHub</a></p>
<p>I wonder what I’m missing as I’ve tried anything I could find on the net but still failed.</p>
<p>Any hints greatly appreciated.</p>
<p>Thanks.</p>

**Comment by icasimpan** [comment, marked as answer]
<p>After a lot of debugging, I finally figured out that the only viable git URL is</p>
<pre><code class="lang-auto">git@git.drupal.org:project/&lt;project_name&gt;.git
</code></pre>
<p>Therefore, DO NOT USE the format</p>
<pre><code class="lang-auto">https://git.drupalcode.org/project/&lt;project_name&gt;.git
</code></pre>
<p>even if it works when you commit from command line which I tested a lot of times.</p>
<p>Hope this helps someone else.</p>

**Comment by tnir** [comment]
I think you should have used [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).

**Reply by rsrrohit** [reply]
This works!

**Reply by salmanramadansyahputra** [reply]
have a link of tutorial using this ?

**Reply by abannachGrafana** [reply]
@salmanramadansyahputra The way I resolved this was to add a step before any git actions involving a private repo

```yaml
      - name: Setup credentials to access private repositories
        run: git config --global url.https://${{ secrets.MY_PAT }}@github.com/.insteadOf https://github.com/
      - name: Step that does stuff with Git
        run: some git commands
```

**Reply by skumar09** [reply]
Adding the below line has fixed the issue for me... thank you 
`run: git config --global url.https://${{ secrets.MY_PAT }}@github.com/.insteadOf https://github.com/`

I got the below error in GitHub actions run when trying to `commit and push `to a repository.

**Error :** fatal: could not read Username for 'https://github.com/': No such device or address
Error: Process completed with exit code 128

```
        run: |
          git config --global user.email "your-email"
          git config --global user.name "your-id"
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf https://github.com/

```

**Reply by stataraju** [reply]
Thankyou git config --global url.https://${GH_TOKEN}}@github.com/.insteadOf https://github.com/      Worked :)

**Reply by zhangtong007** [reply]
worked 
+++++

**Reply by datle2001** [reply]
> .insteadOf https://github.com/

I excluded "insteadOf....." because my dumb ass thought it was a mistype.

I still got this error

ProcessError: remote: Permission to datle2001/my-app.git denied to datle2001.
fatal: unable to access 'https://github.com/datle2001/my-app/': The requested URL returned error: 403

**Comment by franzramadhan** [comment]
For anyone that utilizes github app token to authenticate for HTTP-based Git access, you need to add `x-access-token` as the username. See below example:

```yaml
- name: Generate app token
  id: app-token
  uses: actions/create-github-app-token@v1
  with:
    app-id: ${{ vars.GITHUB_APP_ID }}
    private-key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
- name: Setup credentials to access github using app-token
  run: |
    git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf https://github.com/
```

See: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation
