### DISCUSSION TITLE
Workflow job with needs output from matrix?

### DISCUSSION THREAD

**Discussion by pluma** [community/community#26639] [Actions]
<p>I have a workflow building several docker images and only publishing those images if all builds succeed.</p>
<p>The obvious way to solve this was to have a build job with a matrix of the image names and then a publish job with the same matrix that “needs” the build job. This works fine.</p>
<p>However now I also want to generate outputs during build for each image that I want to re-use during the publish job for the same image. I know that I can work around this using artefacts but if these weren’t matrix jobs I could just do it using outputs.</p>
<p>Is there a special syntax to do access outputs from a matrix job or are matrix jobs simply incapabl of generating outputs? I can’t find any explanation of this in the docs and it doesn’t seem like the outputs could be named dynamically since they need to be explicitly defined at the job level.</p>

**Comment by Simran-B** [comment, marked as answer]
<p>Hey Alan, matrix jobs can set outputs but they will overwrite each other. The last one wins. As a workaround, you can add a unique parameter for each matrix job and use that to set outputs with different names: <a href="https://github.community/t/bug-jobs-output-should-return-a-list-for-a-matrix-job/128626/15" class="inline-onebox">[BUG] Jobs output should return a list for a matrix job - #15 by Simran-B</a></p>

**Reply by dhirschfeld** [reply]
That link is broken?

**Reply by nthienan** [reply]
> matrix jobs can set outputs but they will overwrite each other

facing this problem now. @Simran-B can you share workaround again?

**Reply by AuditeMarlow** [reply]
I'm unsure about this but the original link in @Simran-B's post might've referred to the following discussion: [Jobs need a way to reference all outputs of matrix jobs #17245](https://github.com/orgs/community/discussions/17245)

**Comment by pluma** [comment]
<p>Hey thanks Simran, looks like I’ll have to duplicate the matrix list for the outputs then. That solution seems obvious in hindsight but didn’t occur to me.</p>

**Comment by ghost** [comment]
<aside class="quote group-Advisory-Council quote-modified" data-username="Simran-B" data-post="2" data-topic="210442">
<div class="title">
<div class="quote-controls"></div>
 Simran-B:</div>
<blockquote>
<p>…matrix jobs can set outputs but they will overwrite each other.</p>
</blockquote>
</aside>
<p>This is not great. I hope the GitHub team will fix this.</p>

**Comment by acuD1** [comment]
Been trying some workarounds for days now, and no it is no possible. The only think I can think of is to set a secret to a repository and check the value afterward.

So you can't use job level env, you can't set output dynamicaly, thoses values are overwritten by each matrix jobs...

**Reply by petersononyeukwu-asurion** [reply]
I'm considering storing data in the git repo directly. This post from Simon Willison sparked this idea: https://simonwillison.net/2020/Oct/9/git-scraping/

**Comment by atemate** [comment]
One of the options is to pass outputs via output artifacts, using GH actions [upload-artifact](https://github.com/actions/upload-artifact) and [download-artifact](https://github.com/actions/download-artifact):

```yaml
name: "CI/CD"

on:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kv:
          - key: one
            val: ONE
          - key: two
            val: TWO
          - key: three
            val: THREE

    steps:
      - id: one
        run: |
          mkdir -p pipelines
          echo ${{ matrix.kv.val }} >> outputs/${{ matrix.kv.key }}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: outputs/*.txt


  getval:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Load outputs
        uses: actions/download-artifact@v3
        with:
          name: outputs
          path: outputs

      - run: |
          ls outputs
          cat outputs/*.txt
```

**Reply by nomeata** [reply]
If someone else, like me, is surprised this works, this is the relevant bit from the documentation at <https://github.com/actions/upload-artifact>:

> Each artifact behaves as a file share. Uploading to the same artifact multiple times in the same workflow can overwrite and append already uploaded files:

**Reply by outlying** [reply]
Right, but before someone will become a bit too enthusiastic by this comment here, it is also good to include follow-up to that quote, from the same source:

> Warning: Be careful when uploading to the same artifact via multiple jobs as artifacts may become corrupted. When uploading a file with an identical name and path in multiple jobs, uploads may fail with 503 errors due to conflicting uploads happening at the same time. Ensure uploads to identical locations to not interfere with each other.

**Reply by atemate** [reply]
Yes, good point: you need to make sure to upload under different names.

**Reply by p5** [reply]
This no longer works with the latest version of the upload-artifact unfortunately.  

> Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.

**Reply by gileswells** [reply]
@p5 I'm literally staring at this exact line of documentation today and trying to find a solution. I wish that we could bring all the filesystems systems from each matrix branch back down into a single filesystem.

**Reply by ismael-elatifi** [reply]
I found a workaround without any corruption risk as I write a different artifact for each matrix job. 
The key is to use the pattern option to download all artifacts for the same matrix :  
https://github.com/orgs/community/discussions/26639#discussioncomment-13348057

**Comment by boozook** [comment]
That works because `outputs` __lazily__ sets to the context. That means orphan fields (with empty value or value that can equals to `false`) will no assigned to the ctx. So from each parallel job we're writing various keys into one context.


```yaml
name: Works
on:
  push:
    branches: ["**"]

jobs:
  parallel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        option:
          - a
          - b

    steps:
      - name: output
        id: output
        run: |
          echo "${{ matrix.option }}=${{ matrix.option }}" >> $GITHUB_OUTPUT

    outputs:
      a: ${{ steps.output.outputs.a }}
      b: ${{ steps.output.outputs.b }}

  finally:
    needs: parallel
    runs-on: ubuntu-latest

    strategy:
      matrix:
        option: ${{ needs.parallel.outputs.* }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: debug
        run: echo '${{ toJSON(needs.parallel.outputs) }}'
```
<img width="1097" alt="Screenshot 2022-10-24 at 14 59 08" src="https://user-images.githubusercontent.com/888526/197511227-f9117250-9875-4cd6-b5ad-3d69ff37ebd7.png">

**Reply by atemate** [reply]
neat, but this solution has a limitation that the output keys must be defined statically in yaml, so for variable set of matrix jobs it won't work :(

**Comment by nthienan** [comment]
Facing this problem too. My workflow is dynamic matrix jobs so that's not possible to pre-define outputs statically

**Comment by crivetechie** [comment]
I have used this action to solve the problem, works well with dynamic matrix jobs: https://github.com/marketplace/actions/matrix-outputs-write

**Comment by neilime** [comment]
We've made a couple of actions to deal with this issue: 

- https://github.com/hoverkraft-tech/ci-github-common/blob/main/actions/set-matrix-output/README.md
- https://github.com/hoverkraft-tech/ci-github-common/blob/main/actions/get-matrix-outputs/README.md

**Reply by andy-maier** [reply]
@neilime Hello Emilien,
I tried these get/set actions and had the following issues:

* Does not run on WIndows due to missing "uuidgen" command
* Does not run in python:3-slim container on Ubuntu due to missing "jq" command

I opened corresponding issues in the project repo.

**Reply by neilime** [reply]
@andy-maier it should be fixed with version https://github.com/hoverkraft-tech/ci-github-common/releases/tag/0.8.1

Please let me know

**Reply by oerp-odoo** [reply]
How is uniqueness guaranteed with that action? I assume it will keep it within github worklow scope? So if someone else starts same workflow, it would not clash?

Let say I have matrix of `a, b, c`. And I set some keys/values like `a-something=10, b-something-=20, c-something=30`. So if other workflow would run and use/set same keys (but maybe different values), it would still not clash, right?

**Reply by neilime** [reply]
@oerp-odoo The GitHub Actions workflow ensures artifact uniqueness by concatenating the workflow's run_id, run_number, and a user-provided artifact-name. Users can enhance this uniqueness by supplying a distinct artifact-name for each run, further ensuring that each artifact is uniquely identified across all runs and workflows. This strategy effectively prevents any clashes or overwrites, maintaining the integrity and traceability of artifacts, especially when multiple workflows are executed concurrently or under similar configurations.

https://github.com/hoverkraft-tech/ci-github-common/blob/main/actions/set-matrix-output/README.md (doc updated)

**Reply by oerp-odoo** [reply]
@neilime thanks. One more question. How long those artifacts persist? I assume if workflow ends, artifacts are gone? I would not want them to persist longer than it needs to. And I probably can't rely on delete after fetching artifact option, because I might need to fetch it multiple times.

**Reply by neilime** [reply]
If you are using the action https://github.com/hoverkraft-tech/ci-github-common/tree/main/actions/get-matrix-outputs

There is an input to delete or not he artifact after reading

If you want to delete the artifact on a specific case you can set the   remove-artifact input to false and then remove it later in your workflow when you want (using geekyeggo/delete-artifact action by example)

```yml
- id: create-artifact
  uses: hoverkraft-tech/ci-github-common/actions/set-matrix-output@v0.7.5
  with:
    value: "test value"
    artifact-name: "test"

- uses: hoverkraft-tech/ci-github-common/actions/get-matrix-outputs@v0.7.5
  with:
    artifact-name: "test"
    remove-artifact: false

# Delete artifact
- uses: geekyeggo/delete-artifact@v2
  with:
    name: ${{ steps.create-artifact.outputs.artifact-name }}

```

**Comment by omus** [comment]
I've developed an action to workaround this problem. It only requires adding one additional step to your job to get access to all of the matrix output: https://github.com/beacon-biosignals/matrix-output

**Comment by ismael-elatifi** [comment]
My workaround is to upload a unique artifact for each matrix job and then I [download all artifacts with a **`pattern`**](https://github.com/actions/download-artifact?tab=readme-ov-file#download-multiple-filtered-artifacts-to-the-same-directory) :  
```
name: my_workflow
on: pull_request
jobs:
  matrix_jobs:
    runs-on: my_image
    strategy:
      matrix:
        my_var: [1, 2, 3]
    steps:
      - name: Save data to file
        run: echo "some content ${{ matrix.my_var }}" > artifact_${{ github.run_id }}_${{ matrix.my_var }}.txt

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: artifact_${{ github.run_id }}_${{ matrix.my_var }}
          path: artifact_${{ github.run_id }}_${{ matrix.my_var }}.txt

  do-something-with-artifacts:
    runs-on: my_image
    needs: matrix_jobs
    steps:
      - name: Download artifacts of matrix jobs
        uses: actions/download-artifact@v4
        with:
          pattern: artifact_${{ github.run_id }}_*
          path: ./output # directory to download artifacts into
          merge-multiple: true  # downloaded artifacts will be in the same directory specified by path

      - run: ls ./output
      # shows : artifact_<run_id>_1.txt  artifact_<run_id>_2.txt  artifact_<run_id>_3.txt
```
