### DISCUSSION TITLE
Can't access docker compose service in a job

### DISCUSSION THREAD

**Discussion by alexkubica** [community/community#26650] [Actions]
<p>Hi, I have a job that start a DB container with docker compose up and then runs integration tests on it:</p>
<pre><code class="lang-auto">jobs:
    test:
        runs-on: ubuntu-latest
        steps:
           ....
            - name: Run DB with migrations
              run: docker compose up -d
           ....
            - name: Test
              uses: docker://node:16-alpine
              with:
                  entrypoint: /bin/sh
                  args: -c "npm run test:ci"
</code></pre>
<p>the docker compose look like:</p>
<pre><code class="lang-auto">services:
....
    db:
        build:
            dockerfile: postgres:11.14-alpine
        ports:
            - "5434:5432"

</code></pre>
<p>and the tests are configured to run on 127.0.0.1:5434 but I get ECONNREFUSED<br>
locally I am able to access 127.0.0.1:5434 without issues</p>

**Comment by airtower-luna** [comment, marked as answer]
<p>Your test runs in another container so <code>127.0.0.1</code> is <em>that container</em>, which doesn’t have any running service. I see three ways to fix this (pick one):</p>
<ul>
<li>Drop the test container. Instead use <a href="https://github.com/actions/setup-node"><code>actions/setup-node</code></a> and run the tests directly on the runner VM.</li>
<li>Access the IP address of the runner VM from the test container, that way the published port should work.</li>
<li>Put the test container onto the same network as the Docker Compose containers and access them by name.</li>
</ul>

**Comment by alexkubica** [comment]
<p>Thanks, I’ll try the action you mentioned.<br>
I prefer not to run tests on docker compose but might do that if all others fail and I couldn’t access the IP, maybe you got a config example of doing that?</p>

**Comment by alexkubica** [comment]
<p>Using actions/setup-node did the trick, appreciate your help!</p>

**Comment by ettaboyle** [comment]
<p>Nice!! Thanks for circling back on this <a class="mention" href="/alexkubica">@alexkubica</a> :clap:t2: Glad to see your first post in the forum was solved! Please pay-it-forward and come back and help others.</p>
<p><a class="mention" href="/airtower-luna">@airtower-luna</a> thank you for all your brilliant contributions :heart:</p>

**Comment by jsoneaday** [comment]
I am having a similar issue where I have a runner that triggers a docker compose image, but then after it is up I cannot access one of the services on http://localhost:26657. After the docker image comes up I try and test it by using curl, but get error "cannot connect". This setup works locally. I tried setting network_mode host on the docker-compose.yaml file but it did nothing. I was thinking that this, "Put the test container onto the same network as the Docker Compose containers and access them by name", might fix it but don't know how to configure that.

```
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DEVX_MNEMONIC: '${{ secrets.DEVX_MNEMONIC }}'
      VALIDATOR_MNEMONIC: '${{ secrets.VALIDATOR_MNEMONIC }}'
      GENESIS_ACCOUNTS: '${{ secrets.GENESIS_ACCOUNTS }}'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1' 
      - run: pwd
      - run: mkdir -p scripts/tmp
      - run: git clone https://github.com/archway-network/archway.git
        working-directory: ./scripts/tmp
      - run: make install
        working-directory: ./scripts/tmp/archway      
      - run: npm install -g @archwayhq/cli
      - run: yarn install --immutable      
      - name: Start local node
        run: docker compose up -d
      - name: Wait for local chain to start
        run: >
          set -euo pipefail &&
          curl --retry 15 -f --retry-all-errors --retry-delay 5 -s "http://0.0.0.0:26657/block?height=1" |
            jq '.error == null' && 
            echo "Node started" || {
              echo "Node failed to start."
              exit 1
            }
      - name: Deploy airdrop contract
        run: scripts/deploy-airdrop.sh
      - run: yarn test:all --passWithNoTests
```

```
services:
  node:
    platform: linux/amd64
    image: archwaynetwork/archwayd:v0.2.0
    command: start --x-crisis-skip-assert-invariants
    entrypoint: /docker-entrypoint.sh
    ports:
      - 1317:1317   # API
      - 9090:9090   # gRPC
      - 9091:9091   # gRPC-web
      - 26656:26656 # p2p
      - 26657:26657 # RPC
    volumes:
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh
      - data:/root/.archway

volumes:
  data:
```

**Reply by airtower-luna** [reply]
The `curl` command in your "Wait for local chain to start" is actually trying to connect to `http://0.0.0.0:26657/`. The IPv4 address for `localhost` is `127.0.0.1`, use that or simply `localhost`.

The point where you need to look into putting the containers on the same network is if you use a job container, but the workflow you posted doesn't.

**Reply by jsoneaday** [reply]
It was initially using localhost and had same issue, but let me try 127

**Reply by jsoneaday** [reply]
By way this is the top portion of my workflow file. Any issues here? What is concurrency?

```
name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

```
