### DISCUSSION TITLE
How to configure Dependabot to ONLY create PRs for private registry updates

### DISCUSSION THREAD

**Discussion by mellis481** [community/community#26685] [Actions] [answered]
<p>I’d like for Dependabot to ONLY create the following PRs:</p>
<ul>
<li>All security updates</li>
<li>Version updates (major, minor) for dependencies in the <code>mycompany</code> registry.</li>
</ul>
<p>Inexplicably, this does not seem possible given how <code>allow</code> and <code>ignore</code> work.</p>
<p>The following <code>dependabot.yml</code> file would allow for the version updates I want, but I wouldn't get any security updates:</p>
<pre><code class="lang-auto">version: 2
registries:
  mycompany:
    type: npm-registry
    url: 'https://npm.pkg.github.com'
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - 'mycompany'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    allow:
      - dependency-name: '@mycompany/*'
    ignore:
      - dependency-name: '@mycompany/*'
        update-types: ['version-update:semver-patch']
</code></pre>

Removing both the <code>allow</code> and <code>ignore</code> blocks results in all PRs which I'm trying to avoid.

How is the dependabot config so limited in its ability to configure?

**Comment by lidijarad** [comment]
<p>I’m wondering the same thing, I can’t seem to find anything inside the documentation.</p>

**Comment by mellis481** [comment]
Bump.

**Comment by mellis481** [comment, marked as answer]
Hilariously, I found an answer shortly after re-opening this discussion and it involves basically tricking Dependabot.  Reading through the Dependabot documentation, I said to myself "If only I could have multiple entries under `updates`, I could define the rules I want to." The problem, though, is that there can only be one entry per package ecosystem under `updates`. It turns out that that's not exactly true. Uniqueness is determined in a composite manner using `package-ecosystem` and `directory`.  This allows for there to be different configurations for mono repos. In any event, my repo isn't a mono repo, but I was able to get the following to work using technically different, but functionally the same `directory` values:

```
version: 2
registries:
  mycompany:
    type: npm-registry
    url: 'https://npm.pkg.github.com'
updates:
  # security updates only
  - package-ecosystem: 'npm'
    directory: '.'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 0
  # @mycompany major and minor updates only
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - 'mycompany'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    allow:
      - dependency-name: '@mycompany/*'
    ignore:
      - dependency-name: '@mycompany/*'
        update-types: ['version-update:semver-patch']
```
