### DISCUSSION TITLE
Whitelist Github Workflow

### DISCUSSION THREAD

**Discussion by delvison** [community/community#26719] [Actions]
<p>Hey,</p>
<p>Im trying to write up a quick POC for a github workflow for a node modules project that would bump versions and push to our Artifactory cloud repo.</p>
<p>We have jfrog maintain a whitelist of the ips able to hit our repos. In the past, we have always consulted <a href="https://api.github.com/meta" rel="nofollow noopener">https://api.github.com/meta</a> for the github IPs to whitelist. JFrog has added these IPs to their whitelist yet the connection from the github workflow pushing to Artifactory cloud recieves a forbidden HTTP status.</p>
<p>My question is, what is the appropriate list of IPs to whitelist to allow agents of github actions to hit our Artifactory cloud repo?</p>
<p>Thanks in advance!</p>

**Comment by delvison** [comment]
<p>I ran this in my github actions container</p>
<pre><code>wget -qO- https://ipecho.net/plain ; echo
</code></pre>
<p>It returned 35.233.207.129.</p>
<p>This IP isnt in <a href="https://api.github.com/meta" rel="nofollow noopener">https://api.github.com/meta</a></p>
<pre><code>$ curl https://api.github.com/meta {
  "verifiable_password_authentication": true,
  "github_services_sha": "2f2313161ed4f940a57ae3f0936eb8e9695bb8a8",
  "hooks": [
    "192.30.252.0/22",
    "185.199.108.0/22",
    "140.82.112.0/20"
  ],
  "git": [
    "192.30.252.0/22",
    "185.199.108.0/22",
    "140.82.112.0/20",
    "13.229.188.59/32",
    "13.250.177.223/32",
    "18.194.104.89/32",
    "18.195.85.27/32",
    "35.159.8.160/32",
    "52.74.223.119/32"
  ],
  "pages": [
    "192.30.252.153/32",
    "192.30.252.154/32",
    "185.199.108.153/32",
    "185.199.109.153/32",
    "185.199.110.153/32",
    "185.199.111.153/32"
  ],
  "importer": [
    "54.87.5.173",
    "54.166.52.62",
    "23.20.92.3"
  ]
}
</code></pre>

**Comment by mcolyer** [comment]
<p>Hi <a class="mention" href="/delvison">@delvison</a>, I work on the Actions product and unfortunately we don’t support stable IP addresses for Actions today (so there isn’t a set of addresses I can give you to allow). I’ve noted your feedback and we’ll incorporate it into our future plans for Actions.</p>

**Comment by ghost** [comment]
<p>Hi there <a class="mention" href="/mcolyer">@mcolyer</a> ,</p>
<p>First off all, I wanted to say the Github Actions are a good addition to the Github environment. I’m really appreciating the simple setup which is required to create images specifically.</p>
<p>I do have a question if stable IP’s are going to be added anywhere in the near future. Ideally i would also deploy the images to an environment but that’s currently not possible because we can’t allow the whole web to have access to our cluster.</p>
<p>Any ideas how to tackle this / and will this be included in future versions?</p>

**Comment by HeroProtagonist** [comment]
<p>Hi <a class="mention" href="/mcolyer">@mcolyer</a>,</p>
<p>Actions are great, but for an internal repo I would need this as well. I am wondering if any progress was made / is it on the roadmap?</p>
<p>Thanks!</p>

**Comment by rdkls** [comment]
<p>It’s kind of important if using Actions to perform privileged operations against external systems e.g. provisioning infra to AWS with Terraform</p>
<p>Currently we have to whitelist all Azure Public Cloud IPs …</p>

**Comment by addnab** [comment, marked as answer]
<p>I know this thread is old. But for anybody coming from Google, here’s the documentation on this. <a href="https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#ip-addresses-of-runners-on-github-hosted-machines" rel="nofollow noopener">https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#ip-addresses-of-runners-on-github-hosted-machines</a></p>

**Reply by raynopus** [reply]
While this technically solves the issue, the solution is untenable. GitHub Actions can connect from literally _thousands_ of CIDR blocks and some third parties, specifically MongoDB Atlas, only support 200 whitelist entries. I figured out a way to programmatically add all of the GitHub Actions CIDR blocks to MongoDB Atlas's whitelist, but the sheer number of entries required isn't supported. I don't need fixed IP addresses, but a more manageable list of CIDR blocks is imperative.

**Comment by arslanbekov** [comment]
<p>Hi <a class="mention" href="/mcolyer">@mcolyer</a>, is there an understanding when this functionality will be implemented?</p>

**Comment by Richienb** [comment]
<p>You can download a list of IPs to whitelist from here: <a href="https://www.microsoft.com/en-us/download/details.aspx?id=56519" rel="nofollow noopener">https://www.microsoft.com/en-us/download/details.aspx?id=56519</a></p>

**Comment by blurp1478963** [comment]
<p>Hello!</p>
<p>What is the range to whitelist github actions please?</p>
<p>Thanks!</p>

**Comment by ckovey** [comment]
<p>What about using a VPN?  I also was not interested in whitelisting the entirety of Azure and I noticed this package <a href="https://github.com/marketplace/actions/connect-vpn" rel="nofollow noopener">https://github.com/marketplace/actions/connect-vpn</a></p>

**Comment by digitizdat** [comment]
<p>Looks like this is a direct link:</p>
<pre><code>https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20200210.json
</code></pre>
<p>Since this is a dated link, I suspect there is a better way to get the “latest” list of CIDRs, but this at least works better for scripting than the .aspx the previous responder provided.</p>

**Comment by haythem** [comment]
<p>Hello,</p>
<p>I’ve created an action that queries the runner’s public IP Address.</p>
<p><a href="https://github.com/haythem/public-ip" rel="nofollow noopener">https://github.com/haythem/public-ip</a></p>

**Comment by DanielDebreczeniNote** [comment]
<p>Unfortunatelly “File or directory not found”</p>

**Comment by dandv** [comment]
<p>These are the <a href="https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#ip-addresses-of-github-hosted-runners" rel="nofollow noopener">IP addresses of GitHub-hosted runners</a>.</p>

**Comment by GoldFlsh** [comment]
<p>Is there plans to narrow the range of available IPs to just a subset of “all of azure in these 5 regions” ? This would help reduce security risks for those attempting to whitelist github hosted actions runners.</p>

**Comment by jeffrey-kinesso** [comment]
<p>Just adding support here - whitelisting such a huge block AzureCloud IPs is a blocker for some of us!</p>

**Comment by tyrann0us** [comment]
<p>We can only agree with what has been said. We want to use GitHub Actions as a standalone CI/CD tool to deploy websites. However, many hosts restrict access to their servers via an IP allow list and refuse to allow all IP ranges from Azure due to (legitimate) security concerns.</p>
<p>It would be really great if GitHub Actions were limited to a manageable number of static IP addresses.</p>
<p>Thanks!</p>

**Comment by averypmc** [comment]
<p>Bump. Being able to rely on a whitelist that isn’t 100+ records long and dynamically updating would be really nice.</p>
<p>Use case is deploying to a server via SSH/SCP.</p>

**Comment by philippeamar** [comment]
I agree with the last comments. So I would like to know if something has changed about this subject since the last github updates ?
If we get an enterprise github account is there a way to get an acceptable range of whitelist to authorize our server to accept github actions requests ?

**Comment by jacknkandy** [comment]
Watching. Use case is running database migration script before deploying to Azure in a GitHub action workflow. Difficult to whitelist all possible IPs.

**Comment by david-alpert-nl** [comment]
the ability to limit outgoing IP addresses to a specific CIDR block for a set of github actions is a must-have for any enterprise use of Github Actions where compliance with security policies is required or advisable.

safe-listing all of Windows Azure is an unacceptable security risk

**Comment by kyle-revio** [comment]
As an interim solution I dynamically add and remove the IP from the server whitelist (this assumes theres an API which allows for this, eg. AWS)
```
    - name: Get runner IP
      run: |
          ip=`curl https://ipinfo.io/ip`
          echo $ip
          echo "runner_ip=$ip" >> $GITHUB_ENV

    - name: Add Github Actions IP to Security group as a Postgres inbound rule
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.DEV_AWS_RDS_WHITELIST_SECURITY_GROUP_ID }} --protocol tcp --port 5432 --cidr ${{ env.runner_ip }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-1

   // Do what you need to do (db migration, SSH, etc.)
  
    - name: Remove Github Actions IP from security group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.DEV_AWS_RDS_WHITELIST_SECURITY_GROUP_ID }} --protocol tcp --port 5432 --cidr ${{ env.runner_ip }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-1
      if: always()
```
