### DISCUSSION TITLE
Is it possible to require all GitHub Actions tasks to pass without enumerating them?

### DISCUSSION THREAD

**Discussion by jameslamb** [community/community#26733] [Actions] [answered]
<h2>The Question</h2>
<blockquote>
<p>Is it possible to configure required status checks in a repo to say “all GitHub Actions tasks must pass”, instead of needing to select individual GitHub Actions tasks by name?</p>
</blockquote>
<p>This is how Travis, CircleCI, AppVeyor, and Azure DevOps integrations with GitHub all work…the default behavior is that all tasks must pass, and you can selectively mark tasks as optional.</p>
<p>I’d like to be able to have an administrator set this one time and not have to change it every time we change our GitHub Actions flow.</p>
<h2>Background Context</h2>
<p>Consider the screenshot below:</p>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/1/15e7fd4000046046332e67bb078d3c78f3cecd41.png" data-download-href="/uploads/short-url/37N3OGkvdYNkCTcZn50FL1Y39hT.png?dl=1" title="image" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/7608904/181099637-2fb96999-a273-4cf1-91ee-b0efb8e70be4.png" alt="image" data-base62-sha1="37N3OGkvdYNkCTcZn50FL1Y39hT" width="690" height="212" srcset="https://aws1.discourse-cdn.com/github/optimized/2X/1/15e7fd4000046046332e67bb078d3c78f3cecd41_2_690x212.png, https://aws1.discourse-cdn.com/github/original/2X/1/15e7fd4000046046332e67bb078d3c78f3cecd41.png 1.5x, https://aws1.discourse-cdn.com/github/original/2X/1/15e7fd4000046046332e67bb078d3c78f3cecd41.png 2x" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/1/15e7fd4000046046332e67bb078d3c78f3cecd41_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">image</span><span class="informations">924×284 40.3 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>
<p>This is taken from a pull request in a project I’m working on. The <code>master</code> branch of that repository has a GitHub Actions workflow with 4 tasks. A repo administrator has manually marked each of them as required, following the steps in <a href="https://help.github.com/en/github/administering-a-repository/about-required-status-checks" rel="nofollow noopener">“About required status checks”</a>. You can see, for example, that a task <code>r-package (macOS-latest, clang)</code> is required.</p>
<p>The pull request I’m proposing <em>changes</em> that GitHub Actions workflow, such that there is no longer a task called <code>r-package (macOS-latest, clang)</code>. I am now in a situation where the pull request can’t be merged by maintainers because it looks like the required tasks never ran, and there a bunch of new non-required tasks that passed. See <a href="https://github.com/microsoft/LightGBM/pull/3065#issuecomment-642887012" rel="nofollow noopener">https://github.com/microsoft/LightGBM/pull/3065#issuecomment-642887012</a>  for more background.</p>
<p>Thanks for the time and consideration!</p>

**Comment by msfjarvis** [comment]
<p>Unfortunately there isn’t a way to do this. I’ve had this issue in the past as well where I had a path exclusion filter set up to not run build workflows on non-code changes and they similarly blocked merges. I had to end up doing <a href="https://github.com/android-password-store/Android-Password-Store/commit/0c45bffaba1192ea8a10173e709f439dbf32b089#diff-4af9f3f60c8461140f4a9f265c8ff030" rel="nofollow noopener">this</a> as a workaround.</p>

**Reply by webknjaz** [reply]
@msfjarvis I've generalized this as https://github.com/marketplace/actions/alls-green#why a while back — maybe you could update your answer mentioning it?

Here's another answer from back then: https://github.com/orgs/community/discussions/26733#discussioncomment-3253155.

**Comment by jameslamb** [comment]
<p>oh sad. Yeah I guess it is just something we’ll have to deal with. Not a big deal! Overall I’m still really liking GitHub Actions.</p>
<p>Thanks for the help.</p>

**Comment by graingert** [comment]
<p><a class="mention" href="/jameslamb">@jameslamb</a> I think another work around would be to create a job that “needs” the previous job:</p>
<pre><code class="lang-auto">jobs:
    test:
        matrix: ...
    allgood:
        needs: [test]
</code></pre>
<p><a href="https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds" class="onebox" target="_blank" rel="nofollow noopener">https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds</a></p>
<p>but it costs an extra worker</p>

**Comment by jameslamb** [comment]
<p>oooo cool idea! That’s very clever, I like it. I think that would solve what I’m looking for, thank you.</p>

**Comment by graingert** [comment]
<p>here’s the PR <a href="https://github.com/microsoft/LightGBM/pull/3351/files" class="inline-onebox" rel="noopener nofollow ugc">[ci] add an allgood job for easy [required] builds by graingert · Pull Request #3351 · microsoft/LightGBM · GitHub</a></p>

**Comment by webknjaz** [comment, marked as answer]
@graingert it was discovered that when dependencies don’t succeed, that `check` job is marked as `skipped` which auto-merge treats the same way as `success`. I solved this problem with https://github.com/re-actors/alls-green.

Here's a short example:
```yaml
---

on:
  pull_request:
  push:

jobs:
  tests:
    ...
    strategy:
      matrix:
        python-version:
        # - ~3.12.0-0  # doesn't yet exist as of Oct 04, 2022
        - ~3.11.0-0
        - >-
          3.10
        - 3.9
    ...
    continue-on-error: >-  # this allows "unstable" versions to fail, except for 3.11, meaning 3.12 alpha when it's added
      ${{
        (
          startsWith(matrix.python-version, '~')
          && !startsWith(matrix.python-version, '~3.11')
        )
        && true
        || false
      }}
    ...
    steps:
    - ...

  check:  # This job does nothing and is only used for the branch protection
    if: always()

    needs:
    - tests

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

...
```

See https://github.com/marketplace/actions/alls-green#why.

**Reply by webknjaz** [reply]
@jameslamb mind marking this as a proper answer?

**Reply by jameslamb** [reply]
I haven't tested this, so I can't confirm that it works the way you've described.

**Reply by webknjaz** [reply]
@jameslamb well, please do, once confirmed. From my side, I can only say that it's been tested across multiple projects in the Python ecosystem. A number of those are prominent well-known projects like pip, attrs, structlog, cryptography, setuptools, importlib-resources aiohttp, CherryPy. pytest and coveragepy pending integration.
I've specifically designed it to take into account corner cases and solutions voiced here and in other places.

**Reply by jameslamb** [reply]
@webknjaz I was able to test this tonight, and unfortunately I don't think this action protects against the situation you've described.

Using the latest release (v1.2.2), I observed the following sequence of events:

1. enabled auto-merge on a PR immediately after creating it
2. jobs marked as `needs` by a check using `re-actors/alls-green@release/v1` failed
3. that check was considered `skipped` by GitHub Actions
4. auto-merge merged the PR anyway

GitHub workflow configuration:

```yaml
name: smoke-tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: smoke-tests (${{ matrix.os }}, ${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python_version: '3.8'
          - os: windows-latest
            python_version: '3.10'
    steps:
      - name: fail
        run: |
          exit 123
  all-smoke-tests-successful:
    runs-on: ubuntu-latest
    needs:
    - test
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
```

Branch protection:

<img width="756" alt="Screen Shot 2022-12-22 at 9 48 13 PM" src="https://user-images.githubusercontent.com/7608904/209267271-19029d58-aacd-4ae0-a47e-c0111950bf72.png">

Evidence of GitHub auto-merging it:

<img width="776" alt="Screen Shot 2022-12-22 at 9 45 53 PM" src="https://user-images.githubusercontent.com/7608904/209267100-f14e4f8f-cdb8-4d24-8aad-bc9c742a129e.png">
