### DISCUSSION TITLE
Not require dependent Job to run

### DISCUSSION THREAD

**Discussion by dkirrane** [community/community#26793] [Actions]
<p>I have the following:<br>
<code>job3</code> depends on <code>job1</code> &amp; <code>job2</code>. But <code>job2</code> can be skipped based on an expression.</p>
<p>How do I:</p>
<ul>
<li>run <code>job3</code> after <code>job2</code>
</li>
<li>run <code>job3</code> even if <code>job2</code> is skipped?</li>
<li>do not run <code>job3</code> if <code>job2</code> fails</li>
</ul>
<pre><code class="lang-auto">jobs:
  job1:
  job2:
    if: ${{env.job2Enabled}}
  job3:
    if: ${{ success() }}
    needs: [job1, job2]
</code></pre>

**Comment by Simran-B** [comment]
<p>You could try this:</p>
<pre><code class="lang-yaml">job3:
  if: env.job2Enabled &amp;&amp; success()
</code></pre>

**Comment by ChristopherHX** [comment, marked as answer]
<p><a class="mention" href="/dkirrane">@dkirrane</a><br>
You have a syntax error in your workflow or does github actions allow it now?</p>
<p>You cannot use the env context in job if, which make me to believe you are using nektos/act.</p>
<p>See <a href="https://github.com/nektos/act/issues/720#issuecomment-874759066" class="inline-onebox" rel="noopener nofollow ugc">Issue: GitHub Actions says workflow is not valid because of `${{ !env.ACT }}` · Issue #720 · nektos/act · GitHub</a></p>
<p>For github some infomation ( this won’t apply to act, it acts differently ) about the status functions</p><aside class="onebox githubissue" data-onebox-src="https://github.com/actions/runner/issues/491#issuecomment-926924523">
  <header class="source">

      <a href="https://github.com/actions/runner/issues/491#issuecomment-926924523" target="_blank" rel="noopener nofollow ugc">github.com/actions/runner</a>
  </header>

  <article class="onebox-body">
    <div class="github-row">
  <div class="github-icon-container" title="Issue">
	  <svg width="60" height="60" class="github-icon" viewbox="0 0 14 16" aria-hidden="true"><path d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg>
  </div>

  <div class="github-info-container">
    <h4>
      <a href="https://github.com/actions/runner/issues/491#issuecomment-926924523" target="_blank" rel="noopener nofollow ugc">Job-level "if" condition not evaluated correctly if job in "needs" property is skipped</a>
    </h4>

    <div class="github-info">
      <div class="date">
        opened <span class="discourse-local-date" data-format="ll" data-date="2020-05-19" data-time="22:07:13" data-timezone="UTC">10:07PM - 19 May 20 UTC</span>
      </div>


      <div class="user">
        <a href="https://github.com/joequincy" target="_blank" rel="noopener nofollow ugc">
          <img alt="joequincy" src="https://user-images.githubusercontent.com/44845461/181099932-21d75ccc-fbb7-4b6c-bc4d-b73d127a78a9.jpeg" class="onebox-avatar-inline" width="20" height="20">
          joequincy
        </a>
      </div>
    </div>

    <div class="labels">
        <span style="display:inline-block;margin-top:2px;background-color: #B8B8B8;padding: 2px;border-radius: 4px;color: #fff;margin-left: 3px;">
          Service Bug
        </span>
    </div>
  </div>
</div>

  <div class="github-row">
    <p class="github-body-container">**Describe the bug**
If a job `needs` a prior job which has been skipped, the `<span class="show-more-container"><a href="" rel="noopener" class="show-more">…</a></span><span class="excerpt hidden">if` condition for the dependent job may behave unexpectedly under some conditions. (unsure if condition is evaluated incorrectly or if it's not evaluated at all)

**To Reproduce**
Steps to reproduce the behavior:
Given a workflow such as this (where job_b needs to complete or be skipped before subsequent jobs run, but subsequent jobs don't depend upon any outputs from job_b)
```yaml
on: push

jobs:
  job_a:
    runs-on: ubuntu-latest
    outputs:
      truthy_string: ${{ steps.a.outputs.always }}
      null_value: ${{ steps.b.outputs.never }}
    steps:
      - id: a
        run: echo "::set-output name=always::something"
      - id: b
        run: echo "We opt not to set any output at this time"
  job_b:
    runs-on: ubuntu-latest
    needs: job_a
    if: needs.job_a.outputs.null_value
    steps:
      - run: echo "We've ensured this job will be skipped"
  job_c:
    runs-on: ubuntu-latest
    needs: [job_a, job_b]
    if: needs.job_a.outputs.truthy_string
    steps:
      - run: echo "This won't run, even though the IF condition evaluates true."
  job_d:
    runs-on: ubuntu-latest
    needs: [job_a, job_b]
    if: always() &amp;&amp; needs.job_a.outputs.truthy_string
    steps:
      - run: echo "This will run, even though we've only changed the condition from `true` to `true &amp;&amp; true`"
```
Examining the output of this workflow, job_a will always run, job_b will always be skipped, job_c will always be skipped, and job_d will run.
The only difference between job_c and job_d is the addition of `always() &amp;&amp;` to the `if` condition.

**Expected behavior**
If a job-level conditional evaluates to `true`, the job should run after all `needs`'d jobs have completed or been skipped.
_Both_ job_c and job_d should run. The `always() &amp;&amp;` should not be required for job_c, since it doesn't change the ultimate true/false result of the conditional.

OR documentation should be updated to indicate this is expected behavior. The current docks simply says of job `needs` (emphasis added):
&gt; Identifies any jobs that must complete successfully before this job will run. It can be a string or array of strings. If a job fails, all jobs that need it are skipped **unless the jobs use a conditional statement that causes the job to continue**.
This is relatively ambiguous, but the plain interpretation is that a conditional statement that evaluates to `true` should cause the job to continue. As seen with job_c in the sample, that isn't always the case.

## Runner Version and Platform
Version of your runner?
Unsure - I'm only running via Github Actions, not using a self-hosted runner.

OS of the machine running the runner? OSX/Windows/Linux/...
Linux: ubuntu-latest

## What's not working?
Jobs are being skipped even when the job-level conditional evaluates to `true`.

## Job Log Output
Because the job is skipped entirely, there is no job-level output, even if the appropriate DEBUG secret is set.

## Runner and Worker's Diagnostic Logs
As above, there is no additional output, even if the appropriate DEBUG secret is set.</span></p>
  </div>

  </article>

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>

<p>Add this condition to job3 to run it even when dependent jobs are skipped, also not applies to act<br>
<code>if: "!failure() &amp;&amp; !cancelled()"</code></p>
<p>I suggest to replace act with <a href="https://github.com/ChristopherHX/runner.server" class="inline-onebox" rel="noopener nofollow ugc">GitHub - ChristopherHX/runner.server: An unofficial Console Client and Server for GitHub Action Runners</a> it isn’t as far away from github as act.</p>
