### DISCUSSION TITLE
Trying to get vcvarsall.bat to "stick"

### DISCUSSION THREAD

**Discussion by rdunnington** [community/community#26887] [Actions]
<p>I’m attempting to get a simple CI action setup for my C language repo on Windows. I have a simple .bat file that assumes cl.exe is accessible, since my normal workflow is to open a new cmd/powershell window, call the vcvars batch file, and then call my build.bat file.</p>
<p>I can successfully call the vcvars batch file, but it seems that it doesn’t stick around because calling my batch file immediately fails with:</p>
<p><code>'cl' is not recognized as an internal or external command</code></p>
<p>Linked below is my example yml:</p>
<aside class="onebox githubblob">
  <header class="source">
      <a href="https://github.com/rdunnington/rjd/blob/a12fb7fe2610fccbc2d6cd7743422b8b98329529/.github/workflows/c-cpp.yml" target="_blank" rel="noopener nofollow ugc">github.com</a>
  </header>
  <article class="onebox-body">
    <h4><a href="https://github.com/rdunnington/rjd/blob/a12fb7fe2610fccbc2d6cd7743422b8b98329529/.github/workflows/c-cpp.yml" target="_blank" rel="noopener nofollow ugc">rdunnington/rjd/blob/a12fb7fe2610fccbc2d6cd7743422b8b98329529/.github/workflows/c-cpp.yml</a></h4>
<pre><code class="lang-yml">name: CI

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master, ci-test ]

jobs:
  build_osx:
    name: OSX Build &amp; Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make
      - name: make check
        run: make check
        timeout-minutes: 1
  build_win32:
</code></pre>

  This file has been truncated. <a href="https://github.com/rdunnington/rjd/blob/a12fb7fe2610fccbc2d6cd7743422b8b98329529/.github/workflows/c-cpp.yml" target="_blank" rel="noopener nofollow ugc">show original</a>

  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

**Comment by rdunnington** [comment, marked as answer]
<p>I figured it out. I needed to use the cmd shell and call the batch file like so:</p>
<pre><code class="lang-auto">        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ./build.bat</code></pre>

**Reply by hwhsu1231** [reply]
@rdunnington - Execuse me. If I want to add the following directory into `PATH`, what should I do?

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build
```

Do you have any idea?

**Reply by rdunnington** [reply]
@hwhsu1231 I'm no expert and I don't know your use case, but have you tried using the cmd shell and manually adding it like below?
`set PATH="%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\"`

**Reply by hwhsu1231** [reply]
@rdunnington I'm trying to call `vcvarsall.bat <args>` to select which MSVC environment I want.


I've tried what you said in the above:

```yaml
- name: Add directory of 'vcvarsall.bat' into env PATH and call 'vcvarsall.bat'
  shell: cmd
  run: |
    set PATH="%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\" && call vcvarsall.bat x64
```

However, it turns out to be an error:

```
Run set PATH="%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\" && call vcvarsall.bat x6[4](https://github.com/hwhsu1231/cmake-conan-setup-test4/actions/runs/3611948502/jobs/6086739472#step:5:5)
'vcvarsall.bat' is not recognized as an internal or external command,
operable program or batch file.
Error: Process completed with exit code 1.
```

What happened?

![image](https://user-images.githubusercontent.com/71438617/205476951-150723e2-8e30-4831-9206-d4fb17c4dca6.png)

**Reply by hwhsu1231** [reply]
@rdunnington I think I found an alternative solution to my case, which is using [export-env-var-powershell](https://github.com/myci-actions/export-env-var-powershell) to do so.

```yml
- name: Append the directory of 'vcvarsall.bat' to PATH environment variable
  uses: myci-actions/export-env-var-powershell@1
  with:
    name: PATH
    value: $env:PATH;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build
```

However, it seems that the result specified by calling `vcvarsall.bat x64` won't pass to the next step. Therefore, `where cl.exe` failed.

![image](https://user-images.githubusercontent.com/71438617/205478131-a633b1d0-7dc6-4788-89b2-7c629b55d532.png)
