### DISCUSSION TITLE
Jobs being skipped while using both `needs` and  `if`. Unclear why.

### DISCUSSION THREAD

**Discussion by whois-jon-peterson** [community/community#26945] [Actions]
<p>Alright, I’m going slightly mad here.</p>
<p><strong>Background</strong> :</p>
<p>I have a monorepo with several different services that have their own deploy jobs. Right now, these are completely different workflows that trigger on different path globs, but we’ve had timing issues where a merge involves changes to both service_a and service_b (or _c, or _d). In our repo, service _b thru _d rely on service_a, but service_a’s workflow sometimes takes longer than the other services, so by the time we get to running deploy-phase tests against _b thru _d, they fail because they’re hitting the previous version of _a.</p>
<p>So I’m making changes to use a single workflow with each deploy as a separate job, and attempting to use the workflow to manage whether to run or skip each job, and hold _b thru _d until _a is done.</p>
<p><strong>Workflow</strong> :</p>
<p>So essentially, I have this</p>

```yaml
name: deploy-dev

on:
  push:
    branches:
      - develop
    paths:
      - 'service_a/**'
      - 'service_b/**'
      - 'service_c/**'
      - 'service_d/**'
      - 'platform-client/**'
      - 'platform-shared/**'
      - 'platform-tests/**'

jobs:
  gather_diffs:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.shared.outputs.matches }}
      service_a: ${{ steps.service_a.outputs.matches }}
      service_b: ${{ steps.service_b.outputs.matches }}
      service_c: ${{ steps.service_c.outputs.matches }}
      service_d: ${{ steps.service_d.outputs.matches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check Shared
        id: shared
        run: |
          FILE_COUNT=$(git diff HEAD^ --name-only -- platform-shared/* | wc -l)
          if [[$FILE_COUNT -ne 0]]; then echo "::set-output name=matches::true"; fi;
      - name: Check service_a
        id: service_a
        run: |
          FILE_COUNT=$(git diff HEAD^ --name-only -- service_a/* platform-client/src/service_a/* platform-tests/test/service_a* | wc -l)
          if [[$FILE_COUNT -ne 0]]; then echo "::set-output name=matches::true"; fi;
      - name: Check service_b
        id: service_b
        run: |
          FILE_COUNT=$(git diff HEAD^ --name-only -- service_b/* platform-client/src/service_b/* platform-tests/test/service_b* | wc -l)
          if [[$FILE_COUNT -ne 0]]; then echo "::set-output name=matches::true"; fi;
      - name: Check service_c
        id: service_c
        run: |
          FILE_COUNT=$(git diff HEAD^ --name-only -- service_c/* platform-client/src/service_c/* platform-tests/test/service_c* | wc -l)
          if [[$FILE_COUNT -ne 0]]; then echo "::set-output name=matches::true"; fi;
      - name: Check service_d
        id: service_d
        run: |
          FILE_COUNT=$(git diff HEAD^ --name-only -- service_d/* platform-tests/test/service_d* | wc -l)
          if [[$FILE_COUNT -ne 0]]; then echo "::set-output name=matches::true"; fi;
  service_a:
    runs-on: ubuntu-latest
    needs: gather_diffs
    if: needs.gather_diffs.outputs.all || needs.gather_diffs.outputs.service_a
    steps:
      - run: echo "service_a will deploy"
  service_b:
    runs-on: ubuntu-latest
    needs: [gather_diffs, service_a]
    if: needs.gather_diffs.outputs.all || needs.gather_diffs.outputs.service_b
    steps:
      - run: echo "service_b will deploy"
  service_c:
    runs-on: ubuntu-latest
    needs: [gather_diffs, service_a]
    if: needs.gather_diffs.outputs.all || needs.gather_diffs.outputs.service_c
    steps:
      - run: echo "service_c will deploy"
  service_d:
    runs-on: ubuntu-latest
    needs: [gather_diffs, service_a]
    if: needs.gather_diffs.outputs.all || needs.gather_diffs.outputs.service_d
    steps:
      - run: echo "service_d will deploy"
```

<p><strong>The Problem</strong> :<br>
The gather-diffs job works as intended. If diffs exist on the paths each service needs (or on the shared paths), the appropriate outputs get set and the rest don’t. The gather-diffs job always completes successfully. However, any time the service_a job is skipped, all the dependents are skipped as well.</p>
<p>If I tweak the service-specific jobs to remove service_a from the needs and echo the individual outputs from ${{needs.gather_diffs.outputs.&lt;output&gt;}}, it prints what I’m expecting.</p>
<p>If I change the jobs to use if: always() and then use the original if on each step, it works fine…</p>

```yaml
service_b:
    runs-on: ubuntu-latest
    needs: [gather_diffs, service_a]
    if: always()
    steps:
      - run: echo "service_b will deploy"
        if: needs.gather_diffs.outputs.all || needs.gather_diffs.outputs.service_b
```

<p>… however this means I now need to add this if condition to <em>every</em> step in the job, which is sub-optimal.</p>
<p>Because this second form works and uses the exact same if condition (just in a different location), I’m stumped here. It appears that the job-level if does indeed override the behavior of skipping a job when a needed job is skipped… and it appears that the condition I’m using to check outputs is returning as expected and allowing the step to run when applied to it.</p>
<p>So I’m stumped. Is there something I’m missing that would allow me to to have the output-based condition at the job level?</p>
