### DISCUSSION TITLE
Pull requests trigger duplicate checks for both [push] and [pull_request]

### DISCUSSION THREAD

**Discussion by rdmurphy** [community/community#26940] [Actions]
<p>Hello!</p>
<p>I’ve noticed some recent repos I’ve setup with GitHub Actions seem to be duplicating work on pull requests and running/logging the tests for both the push and pull_request actions. What’s weird though is I’ve scanned through a few other repos (that aren’t mine) that seem to be configured in a similar way that do not have this issue?</p>
<p>You can see an example of it <a href="https://github.com/rdmurphy/journalize/pull/173" rel="nofollow noopener">here</a> and in the following screenshot.</p>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/github/original/2X/7/7f3f14c42df4a497afd2938ace0a08e7d31b95d9.png" data-download-href="/uploads/short-url/i9FMWwTy1fQpPxI5F8yQtg1eD5D.png?dl=1" title="Screen Shot 2020-05-01 at 11.36.40 AM.png" rel="nofollow noopener"><img src="https://user-images.githubusercontent.com/419145/181100889-3872209d-65cf-448b-9986-fce2261d34f9.png" alt="Screen Shot 2020-05-01 at 11.36.40 AM.png" data-base62-sha1="i9FMWwTy1fQpPxI5F8yQtg1eD5D" width="690" height="456" srcset="https://aws1.discourse-cdn.com/github/optimized/2X/7/7f3f14c42df4a497afd2938ace0a08e7d31b95d9_2_690x456.png, https://aws1.discourse-cdn.com/github/optimized/2X/7/7f3f14c42df4a497afd2938ace0a08e7d31b95d9_2_1035x684.png 1.5x, https://aws1.discourse-cdn.com/github/optimized/2X/7/7f3f14c42df4a497afd2938ace0a08e7d31b95d9_2_1380x912.png 2x" data-small-upload="https://aws1.discourse-cdn.com/github/optimized/2X/7/7f3f14c42df4a497afd2938ace0a08e7d31b95d9_2_10x10.png"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use xlink:href="#far-image"></use></svg><span class="filename">Screen Shot 2020-05-01 at 11.36.40 AM.png</span><span class="informations">1514×1002 123 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use xlink:href="#discourse-expand"></use></svg>
</div></a></div>
<p>Definitely possible I goofed my <a href="https://github.com/rdmurphy/journalize/blob/master/.github/workflows/nodejs.yml" rel="nofollow noopener">workflow config as well</a>. :sweat_smile:</p>

**Comment by BrightRan** [comment, marked as answer]
<p><a class="mention" href="/rdmurphy">@rdmurphy</a> ,</p>
<p>This is a correct behavior, not an issue. In the <strong>Checks</strong> of a PR, it will list all the jobs from the workflows run on the <strong>push</strong>  event and the  <strong>pull_request</strong>  event based on the latest <strong>commit</strong> in the <strong>HEAD</strong> branch (source branch of the PR). Currently, we have no methods to only list the the jobs run on the <strong>pull_request</strong>  event.</p>
<p>Because you configure your “Node CI” workflow runs on both <strong>push</strong> and  <strong>pull_request</strong> , when you push commit the workflow will be triggered, and when the PR is <strong>Open</strong> , this workflow also will be triggered by the <strong>pull_request</strong>. So on the checks list of your PR, it will list two similar checks triggered by different events ( <strong>push</strong> and  <strong>pull_request</strong> ).</p>

**Comment by BrightRan** [comment]
<p><a class="mention" href="/rdmurphy">@rdmurphy</a> ,</p>
<p>Is my previous helpful to your?</p>
<p>If you have any other question about this ticket, feel free to tell us.</p>

**Comment by rdmurphy** [comment]
<p>Ah — so maybe what I’m after is just [push]? That would continue logging the latest check of a push of that branch in the pull request? I think that’s all I truly care about, I currently have nothing special expected to happen on a pull.</p>

**Comment by BrightRan** [comment]
<p><a class="mention" href="/rdmurphy">@rdmurphy</a> ,</p>
<p>To avoid the duplicate checks being generated on the same PR, you can try to just set pull_request event or push event for the workflow. Or set branches filter on them.</p>

**Comment by rdmurphy** [comment]
<p>Thank you for clarifying! This makes sense now. I’ll accept your original response as the answer — I think it summarizes it well.</p>

**Comment by pkit** [comment]
@BrightRan just setting `pull_request` doesn't run checks on force push for the same pull request.
I.e. typical workflow of: `pull request -> update code (--force) -> update code (--force) -> approve -> merge` doesn't really work without running duplicate tests

**Comment by pkit** [comment]
Ok, I think I found the best solution:
```yaml
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
```
This one will trigger `pull_request` on any pull request change and also triggers on the final merge to `main` or `release-*` branches.
Release branches are usually used for back-ports.

**Reply by joffrey-bion** [reply]
That's almost right. But what I'm after is to trigger on push to any branch (even the non-main ones that I'm developing on), but also on pull requests that are potentially open by other people (from forks). How to do that without duplicating jobs?

**Reply by javiertuya** [reply]
I've been working on this today. My solution when both push and pull_request can trigger the workflow is to use this (large) expression to enable/disable the execution of each job:

```
if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && (github.event.pull_request.head.repo.fork || github.actor == 'dependabot[bot]'))
```

The first condition in the OR expression avoids the duplicates (disables PRs coming from the repo), and the second one allows PRs when coming from forked projects or dependabot updates.

**Reply by joffrey-bion** [reply]
@javiertuya why the dependabot check? In my case my exact problem is about dependabot PRs, because they trigger both the push and the PR event. So I do want to trigger on dependabot pushes and fork PRs, but not dependabot PRs (to support force pushes)

**Reply by javiertuya** [reply]
@joffrey-bion The reason is that in my typical configuration of workflow triggers, I ignore push events for dependabot updates:

```
on:
  push:
    branches-ignore:
      - 'dependabot/**' #avoid duplicates: only run the PR, not the push
      - 'gh-pages' #github pages do not trigger all tests
    tags-ignore:
      - 'v*' #avoid rerun existing commit on release
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && (github.event.pull_request.head.repo.fork || startsWith(github.head_ref, 'dependabot/')))
 ```

This trigger configuration removes the dependabot duplicates when an update is created. Works fine in my case. Is not exactly your scenario, but I hope helps you.

**Comment by shqear93** [comment]
It's an issue for me to create separate check for each event trigger, what I'm trying to achieve is **a single status check** that:

1. Triggers on PR creation (`pull_request`) -> it could pass/fail -> if pass they can directly merge the PR
2. **RERUN** and **UPDATES** the results **of the same check** on PR review (`pull_request_review`) -> it should not create another status check but simply rerun

If I set the job required for the pull request the developers will never be able to merge their PRs because of two duplicate checks! I still need both triggers and only one status check

I also tried `concurrency` but no luck

Current workflow:
```yaml
name: Protected Topics Check

on:
  pull_request_review:
    types: [ submitted ]
    branches:
      - master
    paths:
      - 'clusters/*/kustomize/kafka-resources/users/*.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'clusters/*/kustomize/kafka-resources/users/*.yaml'

concurrency:
  group: protected-topics-${{ inputs.pr_number }}
  cancel-in-progress: true

jobs:
  protected-topics:
    # check kafka topics
```

@BrightRan can you please help how can we use multiple triggers for a single status check ?

**Reply by shqear93** [reply]
I had to create a workaround to resolve this issue since I need one check to allow developers to merge their PRs when a dynamic custom approvers do approve the PR (`pull_request_review` event ), so I created a custom github action to RERUN the given list of checks by their job names

https://github.com/marketplace/actions/rerun-checks

```yaml
name: After Review Trigger

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  afrer-review-trigger:
    name: After Review Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Rerun protected-topics and Kafka-config-validation checks
        uses: shqear93/rerun-checks@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          check-names: 'protected-topics, some-other-job-name'
```

**Comment by kmturley** [comment]
I think what's confusing is that you want to show the result of tests in your PR.

So you add the `pull_request` event, but that creates the duplicate run:
```
name: Test
on:
  push:
  pull_request:
```
Results in:
<img width="810" height="267" alt="Screenshot 2025-12-02 at 9 09 43 PM" src="https://github.com/user-attachments/assets/59d4d5eb-5dc5-4850-a1b6-7fa4cfb65c54" />



However if you remove `pull_request` event you still see the Test results in the PR, without duplicates:
```
name: Test
on:
  push:
```
Results in:
<img width="916" height="370" alt="Screenshot 2025-12-02 at 9 09 17 PM" src="https://github.com/user-attachments/assets/1c45b351-0a41-474b-a653-c367ade05701" />
