### DISCUSSION TITLE
Workflow infinite loop

### DISCUSSION THREAD

**Discussion by leogr** [community/community#26970] [Actions]
<p>Hi all!</p>
<p>I’ve found by chance a potential issue on GitHub workflows. Basically if an action performs a commit in the same repo using a Personal Access Token, then the workflow will be triggered again, again, and again… endlessly.</p>
<p>I made a demo here: <a href="https://github.com/leogr/workflow-loop" rel="nofollow noopener">https://github.com/leogr/workflow-loop</a></p>
<p>(ofc I stopped it after a while).</p>
<p>I’ve searched around to check if someone is already aware about this, but I found nothing.</p>
<p>BTW, what’s the right repo to open this kind of issue? </p>

**Comment by ethomson** [comment, marked as answer]
<p>This is why we provide workflows with the GITHUB_TOKEN variable.  It is explicitly configured to  <strong>not</strong> run subsequent workflows to avoid this sort of behavior.  If you had used GITHUB_TOKEN here, you should not have seen a loop.</p>
<p>Using a personal access token avoids this check, and will allow you to get into infinite loops if you’re not careful.  So this is by-design but it looks like we should clarify this in the documentation - thanks for reporting this!</p>

**Reply by javiBajoCero** [reply]
Thanks ethomson, i must recognice im a bit newish with actions.

>>used GITHUB_TOKEN here

What is "used".
Where is "here".

I have been looking around for 1h now.

This is what i need:

> To create an effective CI flow.
> When i push changes to my repository, my workflow crosscompiles the code creating .bin files.
> After those output files are created i need to push those files to the same repo **only once**.
> This results in an endless push-workflow-push loop.


peter has a very complete but complex answer, ill study it and get back with results
https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457

**Reply by javiBajoCero** [reply]
This would be a test yaml file creating the unwanted loop


```
name: testing_workflow
on: [push]
jobs:
  echo:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: modifies log.txt
        run: echo Fran perea quien lo lea $(date) >log.txt
      - name: commits and pushes changes
        run: |
          git add .
          git commit -m "report autogenerated $(date)"
          git push
```
