### DISCUSSION TITLE
GitHub Actions - no way to get PR number on push event?

### DISCUSSION THREAD

**Discussion by timhaines** [community/community#27071] [Actions]
<p>Hey there,</p>
<p>I’d like to get the commit SHA, branch, and pull request number on a push event.</p>
<p>I’ve found GITHUB_SHA and GITHUB_REF in the environment variables.  I don’t see how to get the pull request number though.  It looks like the push event payload doesn’t include the pull request number? <a href="https://developer.github.com/v3/activity/events/types/#pushevent" rel="nofollow noopener">https://developer.github.com/v3/activity/events/types/#pushevent</a></p>
<p>Is there some other way to get the pull request number from the environment?</p>
<p>Thanks,</p>
<p>Tim</p>

**Comment by gimenete** [comment, marked as answer]
<p>Hi <a class="mention" href="/timhaines">@timhaines</a> </p>
<p>I think you could get the pull request information using this recent endpoint <a href="https://developer.github.com/v3/repos/commits/#list-pull-requests-associated-with-commit" rel="nofollow noopener">https://developer.github.com/v3/repos/commits/#list-pull-requests-associated-with-commit</a> using the SHA that you are getting in the payload.</p>
<p>Let me know if that works for you!</p>

**Reply by rdhar** [reply]
I've expanded on this answer with a functional copy/pastable demo snippet [over here](https://github.com/orgs/community/discussions/27071#discussioncomment-4943026).

**Reply by polRk** [reply]
That's not working for forks....

**Comment by sjackman** [comment]
<p>It works! I used squash-and-merge to merge a PR, and you are able to use the SHA-1 of the squash-merged commit on <code>master</code> to get its PR nuber, which I didn’t expect to work.</p>
<pre><code class="lang-auto">
$ curl -s -H "Accept: application/vnd.github.groot-preview+json" \

&amp;nbsp; &amp;nbsp; [https://api.github.com/repos/brewsci/homebrew-bio/commits/fb4477fa762eaef76b9e1508c7f6d58dd9176c94/pulls](https://api.github.com/repos/brewsci/homebrew-bio/commits/fb4477fa762eaef76b9e1508c7f6d58dd9176c94/pulls) \

&amp;nbsp; &amp;nbsp; | jq -r '.[].number'

879

</code></pre>

**Comment by louisluhao** [comment]
<p>Just FYI, this API is not supported for production use.<br>
Quote from <a href="https://developer.github.com/v3/repos/commits/#list-pull-requests-associated-with-commit" rel="nofollow noopener">https://developer.github.com/v3/repos/commits/#list-pull-requests-associated-with-commit</a> <br>
_ <strong>Warning:</strong>  The API may change without advance notice during the preview period. Preview features are not supported for production use. If you experience any issues, contact <a href="https://github.com/contact" rel="nofollow noopener">GitHub Support</a> or <a href="https://premium.githubsupport.com/" rel="nofollow noopener">GitHub Premium Support</a>__._</p>
<p>You might want to consider use GraphQL v4 which could achieve the same thing and supported for production use. </p>

**Comment by rachelcarmena** [comment]
<p>Thanks <a class="mention" href="/gimenete">@gimenete</a> !! However, I think it only works for the first commit of a pull request because it’s not possible to find pull requests for the next GITHUB_SHA. After managing it with Git commands to find the first commit I realized that GITHUB_REF had the format refs/pull/&lt;PULL_REQUEST_NUMBER&gt;/merge so I got the number from it. Please, I think it would be interesting to have an environment variable from GITHUB such as GITHUB_PULL_REQUEST like TRAVIS_PULL_REQUEST on Travis CI. Thank you so much!</p>

**Comment by sirago** [comment]
<p>This worked for me:</p>
<pre><code class="lang-auto">run: |
    echo "::set-env name=PR_NUMBER::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
</code></pre>

**Comment by rachelcarmena** [comment]
<p>Thank you so much <a class="mention" href="/sirago">@sirago</a> !! The same solution with another access way:</p>
<p><code>${{ github.event.pull_request.number }}</code></p>
<p>Source: <a href="https://help.github.com/en/actions/reference/events-that-trigger-workflows" rel="nofollow noopener">https://help.github.com/en/actions/reference/events-that-trigger-workflows</a></p>

**Comment by razzinger** [comment]
<p>Still not work for me… tried both way<br>
my trigger is:<br>
on:<br>
push:<br>
branches:<br>
- ‘**’</p>

**Comment by rachelcarmena** [comment]
<p>Hi <a class="mention" href="/razzinger">@razzinger</a> , please, try this trigger for pull requests to be able to get the pull request number:</p>
<pre><code class="lang-auto">on: pull_request
</code></pre>
<p>I hope it works for you! :pray:</p>
<p>Source: <a href="https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on" class="inline-onebox" rel="noopener nofollow ugc">Workflow syntax for GitHub Actions - GitHub Docs</a></p>

**Comment by rdhar** [comment]
Hi @timhaines, 

To expand on @gimenete's answer about the API endpoint, here's a working snippet to get the issue number in both `push` and `pull_request` events within a GitHub Actions workflow by leveraging [actions/github-script](https://github.com/actions/github-script):

```js
steps:
  - uses: actions/github-script@v6
    id: get_issue_number
    with:
      script: |
        if (context.issue.number) {
          // Return issue number if present
          return context.issue.number;
        } else {
          // Otherwise return issue number from commit
          return (
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          ).data[0].number;
        }
      result-encoding: string
  - name: Issue number
    run: echo '${{steps.get_issue_number.outputs.result}}'
```

The script queries the [list labels for an issue](https://docs.github.com/en/rest/issues/labels#list-labels-for-an-issue) REST API endpoint via [octokit/rest.js](https://octokit.github.io/rest.js/v18#repos-list-pull-requests-associated-with-commit) client.

**Reply by rdhar** [reply]
Hey @oynek, I think I missed your reply but you raised a good point. 

In addition to `permissions: contents: read`, we might also need to explicitly pass in `env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` variable for the GH action to have required permissions to run this script. Let me know if that works out.

**Reply by starverdiyev** [reply]
@rdhar  thank you for this method! It's helped me to post messages in merge PR with push!

**Reply by rdhar** [reply]
Glad to hear it's come in use; hopefully helps with [this issue](https://github.com/thollander/actions-comment-pull-request/issues/282) as well!

**Reply by starverdiyev** [reply]
@rdhar yes, post this method to my [issue](https://github.com/thollander/actions-comment-pull-request/issues/282). Very useful. Thank. you!

**Reply by bombillazo** [reply]
If anyone needs more than the number, the way I achieved it was:

```yml
steps:
  - uses: actions/github-script@v6
    id: get_pr_data
    with:
      script: |
          return (
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          ).data[0];
  - name: Pull Request data
    run: |
      echo '${{ fromJson(steps.get_pr_data.outputs.result).number }}'
      echo '${{ fromJson(steps.get_pr_data.outputs.result).title }}'
```

**Reply by polRk** [reply]
not working with forks

**Reply by angelaalex12** [reply]
[Lift maintenance services](https://www.mwliftservices.co.uk/lift-refurbishment/) are crucial for ensuring consistent performance and safety. Regular checks and servicing help prevent unexpected malfunctions and keep lifts running efficiently for everyone’s convenience.

**Comment by nelsonprsousa** [comment]
If anyone is wondering how to get a complete, yet working, yml file, here it is:

```yaml
name: 'Your awesome new GA'

on:
  push:
    branches:
      - main
jobs:
  pr-number:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0];
      - name: Pull Request data
        run: |
          echo '${{ fromJson(steps.get_pr_data.outputs.result).number }}'
          echo '${{ fromJson(steps.get_pr_data.outputs.result).title }}'
```

Please notice that both permissions (`contents: read` and `pull-requests: read`) are mandatory.

**Reply by polRk** [reply]
not working with forks

**Reply by ferrarijefferson** [reply]
> not working with forks

This is working perfectly for me

```yaml
      - name: Get PR number
        id: number
        uses: bcgov-nr/action-get-pr@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Echo PR number
        run: |
          echo "${{ steps.number.outputs.pr }}"
```
