### DISCUSSION TITLE
Does re-running a failed job use the latest workflow file?

### DISCUSSION THREAD

**Discussion by kaleidawave** [community/community#27083] [Actions]
<p>I have a failed CI job. I have since updated its workflow file in a new commit. If I do “re-run jobs” will it use the workflow file at HEAD or will it re-run with the original workflow file?</p>

**Comment by yaananth** [comment, marked as answer]
<p>It will use the original workflow file. For re-runs we try to keep the resources used same. With one caveat, if the workflow uses some actions at a version, if that version was force pushed/updated, we will be fetching the latest version there.</p>

**Reply by JohnyClash** [reply]
I would like to rerun the failed CI job with the updated action as it was the problem. How will I go about doing this?

**Comment by ootkin** [comment]
I have a similar problem.

I'm using a reusable workflow and one of my job failed because there is an error on the reusable workflow file.

If I commit the change in the called workflow and then `re-run failed jobs`, the action run the previuous version of the workflow without refetch the updated yaml.

This is my workflow:

```yaml
name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    uses: my-org/wl-reusable-workflows/.github/workflows/release.yml@main
    secrets: inherit
```
