### DISCUSSION TITLE
[GitHub Actions (new)] [BUG] Unable to create environment variables based matrix

### DISCUSSION THREAD

**Discussion by webknjaz** [community/community#27139] [Actions]
Here’s what I’m trying:

```yaml
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
        - 3.7
        os:
        - ubuntu-18.04
        env:
        - TOXENV: python,check-docs,build-docs
- TOXENV: build-dists,pre-commit-ci
```

I want to generate a number of jobs from matrix also taking into account the specified env vars. Just like Travis CI does:

* https://docs.travis-ci.com/user/build-stages/matrix-expansion/
* https://docs.travis-ci.com/user/environment-variables/#defining-multiple-variables-per-item
* https://docs.travis-ci.com/user/build-matrix/

Anything I’m missing?

**Comment by AndreaGriffiths11** [comment]
<p>Hi <a class="mention" href="/webknjaz">@webknjaz</a>, thanks for being here! Did you give this workflow a go? Are you having any problems?</p>

**Comment by webknjaz** [comment]
<p>Hi <a class="mention" href="/andreagriffiths11">@andreagriffiths11</a>, I tried it and it doesn’t create jobs with different env var values from the matrix.</p>

**Comment by webknjaz** [comment, marked as answer]
Workaround is to explicitly apply the env factor on a job level:

```yaml
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
        - 3.7
        os:
        - ubuntu-18.04
        env:
        - TOXENV: python,check-docs,build-docs
- TOXENV: build-dists,pre-commit-ci
  steps:
  - ...
  - run: |
      some-command --with-access-to=env
    env: ${{matrix.env }}
```
