### DISCUSSION TITLE
Github action shell script "source: not found"

### DISCUSSION THREAD

**Discussion by datapolitical** [community/community#27162] [Actions]
<p>I’ve forked an existing Github Action in order to use it with a ubuntu-latest (because the necessary dependencies don’t come with the original (ruby2.7).</p>
<p>In doing so, it gets to the final line of the entry point.sh file and then fails with “/entrypoint.sh: 50: source: not found”</p>
<p>I had to hard-code the location for the source file because the original code wasn’t parsing:</p>
<pre><code class="lang-auto">if [[ "${PROVIDER}" == "github" ]]; then
 if [ "${PROVIDER}" == "github" ]; then
   source "${SCRIPT_DIR}/providers/github.sh"
 else
   echo "${PROVIDER} is an unsupported provider."
  exit 1
fi
</code></pre>
<p>which I changed to:<br>
<code>source "/github/workspace/providers/github.sh"</code> because <code>SCRIPT_DIR="$( cd "$(dirname "$0")" &gt;/dev/null 2&gt;&amp;1 ; pwd -P )"</code> wasn’t working.</p>
<p>Script DIR should be “/github/workspace”, but either it’s not or I have the formatting wrong, because the file exists in providers/github.sh.</p>
<p>Here’s the full entrypoint.sh file: <a href="https://github.com/datapolitical/jekyll-deploy-action/blob/a5fd280e39a4787fe458501ab889f28d1316583e/entrypoint.sh" class="inline-onebox" rel="noopener nofollow ugc">jekyll-deploy-action/entrypoint.sh at a5fd280e39a4787fe458501ab889f28d1316583e · datapolitical/jekyll-deploy-action · GitHub</a></p>
<p>Thanks for any help you can offer!</p>

**Comment by datapolitical** [comment, marked as answer]
<p>Solved it! turns out it needed to be run in bash, so updating the first line of the script fixed everything!</p>

**Reply by citrushouse** [reply]
I'm coming from GitLab to GitHub, and I suspect I'm running into the same issue...

But where is this "be run in bash?" Within my jobs, I have 
```
  validate-data:
    runs-on: ubuntu-20.04
    container:
      image: python:3.10-buster
    steps:
      - uses: actions/checkout@v3
      - run: python --version
      - run: pip install virtualenv
     # etc.
```

What changes to use bash?
