### DISCUSSION TITLE
How to use system environment variable in cache actions path?

### DISCUSSION THREAD

**Discussion by evandrocoan** [community/community#27163] [Actions]
<p>I am trying to access the Windows environment variable <code>ProgramFiles</code> to pass it to the GitHub Cache Action: <a href="https://github.com/evandrocoan/TestGithubActions/actions/runs/63543924/workflow#L37" rel="nofollow noopener">https://github.com/evandrocoan/TestGithubActions/actions/runs/63543924/workflow#L37</a></p>
<pre><code>name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            SEP: /
            PIP_WHEELS_DIR: ~/.cache/pip
            CARGO_INDEX_DIR: ~/.cargo/git
            CARGO_REGISTRY_DIR: ~/.cargo/registry

          - os: macos-latest
            SEP: /
            PIP_WHEELS_DIR: ~/Library/Caches/pip
            CARGO_INDEX_DIR: ~/.cargo/git
            CARGO_REGISTRY_DIR: ~/.cargo/registry

          - os: windows-latest
            SEP: \
            PIP_WHEELS_DIR: ~\AppData\Local\pip\Cache
            CARGO_INDEX_DIR: C:\Rust\.cargo\git
            CARGO_REGISTRY_DIR: C:\Rust\.cargo\registry

    steps:
      - uses: actions/checkout@v2

      - name: Cache git
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v1
        with:
          path: ${{ env.ProgramFiles }}${{ matrix.SEP }}Git
          key: ${{ runner.os }}-git-${{ hashFiles('**/main.yml') }}-1-

      - run: echo Print something.
      - run: echo On ubuntu-latest
        if: matrix.os == 'ubuntu-latest'
</code></pre>
<p>But when it runs, the variable is empty: <a href="https://github.com/evandrocoan/TestGithubActions/runs/535518431?check_suite_focus=true#step:9:2" rel="nofollow noopener">https://github.com/evandrocoan/TestGithubActions/runs/535518431?check_suite_focus=true#step:9:2</a></p>
<pre><code>C:\windows\System32\tar.exe -cz -f d:\a\_temp\7e3aad1e-aade-4599-af14-17c2f935a571\cache.tgz -C d:\Git .
</code></pre>
<p>How to access system-defined variables?</p>

**Comment by Yanjingzhu** [comment, marked as answer]
<p>Hi <a class="mention" href="/evandrocoan">@evandrocoan</a> , </p>
<p>In default, system environment variable is not included in env context, you could use <a href="https://github.com/actions/toolkit/blob/master/docs/commands.md#set-an-environment-variable" rel="nofollow noopener">set-env command</a> to set the value of system <code>ProgramFiles</code> to an job env. And then you it with  <strong>${{ env.ProgramFilesPath }} </strong> syntax. </p>
<p>Please see my example:</p>
<pre><code>name: CI

on:
  push:
     paths:
       - '**/main.yml'

jobs:
  run_tests:
    runs-on: windows-latest
    steps:
      # env context is empty at the beginning
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: write-host "$env:ENV_CONTEXT1"
      # set system ProgramFiles value to env ProgramFilesPath
      - name: set env ProgramFiles
        shell: cmd
        run: |
           echo %programfiles%
           echo ::set-env name=ProgramFilesPath::%programfiles%
      # check env context again, now include ProgramFilesPath
      - name: Dump env context 2
        env:
          ENV_CONTEXT1: ${{ toJson(env) }}
        run: write-host "$env:ENV_CONTEXT1"
      # Now you can use env.ProgramFilesPath
      - name: Cache git
        uses: actions/cache@v1
        with:
          path: ${{ **env.ProgramFilesPath** }}\Git
          key: ${{ runner.os }}-git-${{ hashFiles('**/main.yml') }}-1-
</code></pre>

**Comment by thedataking** [comment]
<p><a class="mention" href="/yanjingzhu">@yanjingzhu</a> set-env is now deprecated [0]. Any guidance on how to use an environment variable for caching after this change? Cheers!</p>
<p>[0] <a href="https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/" class="inline-onebox" rel="noopener nofollow ugc">GitHub Actions: Deprecating set-env and add-path commands - GitHub Changelog</a></p>

**Reply by jharris-tc** [reply]
would also like an update on this

**Comment by ValentinTrinque** [comment]
This is what I have so far:
```yaml
name: Test cache

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  download-backend:
    name: Download backend dependencies (${{ matrix.os }}, ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-2019
          - ubuntu-latest
        arch:
          - amd64
          - arm64
    env:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Add go paths to environment
        shell: bash
        run: |
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV
          echo "GOBIN=$(go env GOBIN)" >> $GITHUB_ENV

      - name: Verify go modules are cached
        uses: actions/cache@v3
        id: cache-go-modules
        with:
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOMODCACHE }}
            ${{ env.GOBIN }}
          key: go-modules-cache-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('**/go.sum') }}

      - name: Install missing Golang dependencies
        if: steps.cache-go-modules.outputs.cache-hit != 'true'
        run: go mod download
```
