### DISCUSSION TITLE
"workflows" permissions issue when ignoring workflow files

### DISCUSSION THREAD

**Discussion by anthonator** [community/community#27224] [Actions]
We are receiving the following error in one of our workflows.

> refusing to allow a GitHub App to create or update workflow `.github/workflows/ci-deploy-for-review.yaml` without `workflows` permission

The only thing we're doing with that workflow is ignoring it using `paths-ignore`. We aren't trying to create or update the workflow. After we stop ignoring that file the error goes away. Is this correct behavior? Seems like it might be a bug.

**Comment by jsoref** [comment]
Could you link to a public repository with a sample workflow that triggers what you're seeing?

The only way I know to trigger this is like this:

https://github.com/jsoref/issue-refuses-workflow-update/runs/7533415129?check_suite_focus=true

```
 ! [remote rejected] HEAD -> broken (refusing to allow a GitHub App to create or update workflow `.github/workflows/spelling.yml` without `workflows` permission)
```

```yaml
jobs:
  broken:
    name: Broken
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git config --global user.name "Name"
        git config --global user.email "<name@example.com>"
        echo '#' >> .github/workflows/spelling.yml
        git add -u
        git commit -m 'Update workflow'
        git push origin HEAD
```

Note that this workflow is trying to update a workflow.

The [`GITHUB_TOKEN` doesn't have access](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) to the [`workflows` permission](
https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes)

If you want to update a file in `.github/workflows`, you'd need a personal access token, or to use an app with the proper configuration.

It might be possible to adjust the workflow so its configuration doesn't live in the protected directory (`.github/actions/<...>` is a common location for such data).
