### DISCUSSION TITLE
Versioning: is it possible to have two separate sequences in the tags?

### DISCUSSION THREAD

**Discussion by enanram** [community/community#27285] [Actions]
I am working with Github actions and trying to implement a new strategy to deal with releases both for testing and for production. The idea is as follows:

There is a main branch for stable releases, and a develop branch with the latest code. You create a feature branch, make changes, and commit and push before merging into develop. This creates a version, say v1.5.4-develop. At some point, develop is merged into main to create a new version for production. This will follow its own numbering, independent of the develop sequence. So it might be v1.2.1 or something. Currently, I'm using the semantic-version action to create a new tag when merging into develop or main, and applying the suffix if it's the develop branch. This works fine, but when I merge into main it uses the latest tag in the repo. 

I would like to find a way to get the most recent tag that **doesn't** have the develop suffix and increment that, so that the main releases follow their own sequence.

Example:

Latest main release: v1.2.3 

Latest develop release: v1.4.6-develop

I would like the new main release to be 1.3.0, but currently it would be v1.4.6.

The code that creates the tag: 
```
steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: Bump version
        uses: PaulHatch/semantic-version@v4.0.2
        id: tag_version_develop
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}"
          namespace: develop
          change_path: "."
          short_tags: false
          bump_each_commit: true
      - name: Tag Release (vX.Y.Z)
        run: |
          git tag ${{ steps.tag_version_develop.outputs.version_tag }}
          git push origin ${{ steps.tag_version_develop.outputs.version_tag }}
```
For the main release it's the same but without the namespace. I tried using a namespace of 'main' to see if that would look for the last tag with that suffix, but it didn't. It seems to me that the semantic-version action retrieves the latest tag and bumps that - I would like to control the input for that, but I can't see an option for it.
