### DISCUSSION TITLE
Access dynamically set env var from action as input, in with block

### DISCUSSION THREAD

**Discussion by pkaramol** [community/community#27299] [Actions] [answered]
I have the following steps in a GHA action that composes an env var

```yaml
    - name: compose slack success message
      shell: bash
      run: |
          MSG="STAGING image(s) ${{ needs.set_global_outputs.outputs.staging_image_name }}"
          if [[ "${{ inputs.stg_image_tag_stable }}" == true ]]; then
            MSG="$MSG ${{ needs.set_global_outputs.outputs.staging_image_name_stable }}"
          fi
          if [[ "${{ inputs.stg_image_tag_latest }}" == true ]]; then
            MSG="$MSG ${{ needs.set_global_outputs.outputs.staging_image_name_latest }}"
          fi
          MSG="$MSG built / pushed with success"
          echo "MSG=$MSG" >> $GITHUB_ENV 
```

When I try to use it in the next step 

```
    - name: slack success for staging
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_MESSAGE: $env.MSG
```

I see `$MSG` in my slack message.

What am I doing wrong?

**Comment by airtower-luna** [comment, marked as answer]
You need to use [Actions expression syntax](https://docs.github.com/en/actions/learn-github-actions/expressions). This should work:

```yaml
    - name: slack success for staging
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_MESSAGE: ${{ env.MSG }}
```

Though it might be easier to directly call the variable `SLACK_MESSAGE` when writing to `$GITHUB_ENV`. :wink:
