### DISCUSSION TITLE
Sharing variable between github job (from inside reusable workflow)

### DISCUSSION THREAD

**Discussion by sarahcthekey** [community/community#27315] [Actions] [answered]
I have 2 reusable workflows set up in a central github repo, these reusable workflows each have several steps.

Our application repositories use the github workflows and reference these two central workflows e.g (from one of our apps):

```
name: App Name CI
on: push
jobs:
  build-docker:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: <org-name-redacted>/github-actions/.github/workflows/build-docker.yml@main
    with:
      var1: "some string"
      var2: "some string"
  deploy:
    needs: [build-docker]
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: <org-name-redacted>/github-actions/.github/workflows/deployment.yml@sort-tagging
    with:
      variable1: "some-string"
      variable2: "some-string"
      datetime: ${{ needs.build-docker.steps.vars.outputs.datetime }}

```

As you can see on the last line,  I'm trying to get the `datetime` output variable from a step within the build-docker workflow. At the moment although it doesn't error, it also isn't grabbing the variable as it's the step that requires it is showing blank where it should be. I've checked this works from without the workflow itself and it does - the variable is set using the correct `echo "::set-output` command.

Is is possible to be able to grab a variable from one job to use in another ([as per docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job)) but when it is from an existing reusable workflow, and not directly from a job step?
