### DISCUSSION TITLE
Reusable workflow cannot find 'action.yml', 'action.yaml' or 'Dockerfile'

### DISCUSSION THREAD

**Discussion by EmberRandall** [community/community#27362] [Actions] [answered]
In my repository, we've got a workflow that pushes our code to staging on pushes to main; I want to turn that into a reusable workflow so I can call it from a second workflow that creates a release branch and pushes that branch to staging. However, when I try to call the reusable workflow, I get `Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/zendesk-bulk-update-api/zendesk-bulk-update-api/.github/workflows/staging.yml'. Did you forget to run actions/checkout before running your local action?`

My caller workflow:
```
name: Create release branch

on:
  schedule:
    # Every tuesday at 12 am UTC, aka 5 pm pacific time
    - cron: '0 0 * * 2'
  # TODO: remove once working
  push:
    branches: [ember/action]
  # Allows this action to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set branch name
        run: echo "NAME=release-$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{ env.NAME }}'

      - uses: ./.github/workflows/staging.yml
        with:
          branch_name: ${{ env.NAME }}
```

I've tried a bunch of different options from various StackOverflow and community posts, including moving the job out of a step and into its own job, but I haven't been able to get the syntax right for any of them, or else it fails with the same error. What's the right way to do this?

**Comment by airtower-luna** [comment, marked as answer]
This looks like you're trying to call the reusable workflow as a **step**, which isn't possible.

```
      - uses: ./.github/workflows/staging.yml
        with:
          branch_name: ${{ env.NAME }}
```

Reusable workflows [must be called as **jobs**](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow). If you want to reuse your code at the step level, take a look at [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action).

Which fits better depends on what your code does, in short a reusable workflow is good if you want to reuse a workflow *exactly* as it is (possibly with parameters), custom actions (composite or not) are good if you want building blocks to use as steps in other workflows.

**Reply by EmberRandall** [reply]
What's the right syntax for calling it as a job? I've tried a bunch of options, but can't figure out how to make that work.  Latest attempt is
```
name: Create release branch

on:
  schedule:
    # Every tuesday at 12 am UTC, aka 5 pm pacific time
    - cron: '0 0 * * 2'
  # WARNING: keep this commented out except when testing new updates to the workflow itself
  push:
    branches: [ember/action]
  # Allows this action to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.branch_name.outputs.value }}
    steps:
      - uses: actions/checkout@v3

      - id: branch_name
        run: echo "::set-output name=value::release-$(date +'%Y.%m.%d')"

      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{ steps.branch_name.outputs.value}}'

  push-to-staging:
    runs-on: ubuntu-latest
    needs: create-branch
    uses: ./.github/workflows/staging.yml
    with:
      branch_name: ${{needs.create-branch.outputs.branch_name}}
```

But that gives `Unexpected value 'uses' .github/workflows/create-release-branch.yml (Line: 36, Col: 5): Unexpected value 'with'`

**Reply by airtower-luna** [reply]
The `uses` and `with` look correct for calling a workflow. :thinking: Maybe the `runs-on` causes the problem? It shouldn't be in a call to a reusable workflow (because the jobs in the reusable workflow define it), it's not in the [list of allowed keywords for calling jobs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow), and I suspect with that being present the parser expects a regular job. :sweat_smile:

**Reply by EmberRandall** [reply]
That fixed it, thank you!!

**Reply by owenconti** [reply]
Is this example from the docs incorrect then?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets

```
on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest

    steps:
      - name: Pass the received secret to an action
        uses: ./.github/actions/my-action
        with:
          token: ${{ secrets.access-token }}
```
