### DISCUSSION TITLE
Support for variables

### DISCUSSION THREAD

**Discussion by GMNGeoffrey** [community/community#27370] [Actions]
I would like to be able to reuse certain patterns (strings, especially) in my workflow file. Since yaml anchors aren't supported (https://github.com/github-community/community/discussions/4501, https://github.community/t/support-for-yaml-anchors/16128, https://github.com/actions/runner/issues/1182), this is especially desirable. Frequently I can put such variables in the top-level `env` field, but the `env` context is [not available everywhere](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability). I've encountered issues with wanting variables in the "runs-on" field and for job env variables that contain common strings. Additionally, this somewhat an abuse of `env`, since I don't actually need these variables available in the environment, necessarily.

Proposal: support a top level `vars` field which creates a context that is available everywhere. Ideally, it should even be possible for vars to reference a previously-declared var

```
vars:
  dir: "my/directory/path"
  filename: "file.txt"
  full_path: "${{vars.dir}}/${{vars.filename}}"
```

**Comment by dekimsey** [comment]
I have but only one upvote to give.

My use-case for this feature request:

We have some complex expressions and I'd _really_ like to be able to define them at the top level of my workflow and refer to them more easily.

In my case, I want to refer to the variables in my _job's_ `if:` block.

```
vars:
  cond: ${{ .... stupid complex test ... }}

jobs:
  foo:
    if: contains(vars.cond, "foo")
  bar:
    if: contains(vars.cond, "bar")
  baz:
    if: contains(vars.cond, "baz")
```

Right now this requires copy-pasting the `cond` expression into all uses of it which is not scalable or maintainable.


In some places this could be done in the `env` key, but I need `if` block access. The only work-around at the moment is to define an output and refer to that. But that's almost as clunky and doesn't work correctly on "retry failed jobs" since the step isn't re-run so values aren't recomputed correctly.
