### DISCUSSION TITLE
Reusing Workflows and determining ref of called workflow

### DISCUSSION THREAD

**Discussion by iamwillbar** [community/community#27433] [Actions]
If I call a workflow:

```yaml
callee:
  uses: iamwillbar/spdx-spec/.github/workflows/publish_common.yml@main
```

In the called workflow (e.g. `publish_common.yml`) is it possible to determine the ref of the called workflow (e.g. `main`)?

All of the usual ref properties contain the ref of the event that triggered the callee workflow, but I want to check out the branch the called workflow is in to access the latest version of some tools needed during the build.

**Comment by lktslionel** [comment]
Hello,
It doesn't look like auto-exported env vars provide that information. A simple hack could be to set an input in the **callee** workflow, and use it to set the ref name:

```yaml
callee:
  uses: iamwillbar/spdx-spec/.github/workflows/publish_common.yml@main
  with:
    refname: main
```

and you use this input as a way to access the latest version of the tools needed during the build.

If you want to not repeat yourself, you also set the `refname` as an input or and an env var set in the **caller** workflow.

<details>
  <summary markdown="span">With an input in the caller workflow</summary>

  ```yaml
  on:
    workflow_dispatch:
      inputs:
        callee-refname:
          type: string
          default: main

  env:
    CALLEE_REFNAME: ${{ inputs.callee-refname }}
  # [...]
  callee:
    uses: iamwillbar/spdx-spec/.github/workflows/publish_common.yml@${{ env.CALLEE_REFNAME }}
    with:
      refname: ${{ env.CALLEE_REFNAME }}
  ```
</details>

<details>
  <summary markdown="span">With an env var</summary>
  
  ```yaml
  env:
    CALLEE_REFNAME: main
  # [...]
  callee:
    uses: iamwillbar/spdx-spec/.github/workflows/publish_common.yml@${{ env.CALLEE_REFNAME }}
    with:
      refname: ${{ env.CALLEE_REFNAME }}
  ```
</details>

I hope it helps.
Regards
