### DISCUSSION TITLE
add "Segoe UI Symbol" in markdown CSS font-family

### DISCUSSION THREAD

**Discussion by thyecust** [community/community#27466] [Other Feature Feedback, Questions, & Ideas]
Hi, currently I notice that GitHub markdown uses this CSS font-family

```css
.markdown-body {
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji";
    font-size: 16px;
    line-height: 1.5;
    word-wrap: break-word;
}
```

I suggest to add `Segoe UI Symbol` in the last. This font-family cannot render characters like U+20D7 (and many other characters). I use U+20D7 as vector symbol.
