### DISCUSSION TITLE
Docker composer & exec format error

### DISCUSSION THREAD

**Discussion by Fahani** [community/community#27481] [Actions] [answered]
Hello!

I am running into this error when I execute docker-compose up and the service pulls the image from an URL: `standard_init_linux.go:228: exec user process caused: exec format error`

Here the content of the Dockerfile used to build the image
```
FROM postgres:13-alpine
```

Here the build.sh used to build the image and push it to AWS
```
#!/usr/bin/env bash
docker build --no-cache --progress=plain -t 501851812333.dkr.ecr.us-east-1.amazonaws.com/testing:postgres .
docker push 501851812333.dkr.ecr.us-east-1.amazonaws.com/testing:postgres
```

Here the docker-compose.yml 
```
version: "3.8"
services:
  boilerplate-test-message-db:
    image: 501851812333.dkr.ecr.us-east-1.amazonaws.com/testing:postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    expose:
      - '5432'
    container_name: boilerplate-test-message-db
```

Here the workflow file
```
name: Code Coverage
on: [pull_request]
jobs:
  check-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker composer up
        run: |
          docker-compose -f tests/docker-compose.yml up
```

That results in this error
```
Run docker-compose -f tests/docker-compose.yml up
Creating network "tests_default" with the default driver
Pulling testing (***.dkr.ecr.***.amazonaws.com/testing:postgres)...
postgres: Pulling from testing
Digest: sha256:[9](https://github.com/test/test/runs/7560599222?check_suite_focus=true#step:5:10)b8292cd4c5a71dcb679de8e1f0a4ae0b85db3d98f3fef6adc9cc67f9e543805
Status: Downloaded newer image for ***.dkr.ecr.***.amazonaws.com/testing:postgres
Creating boilerplate-test-message-db ... 
Creating boilerplate-test-message-db ... done
Attaching to boilerplate-test-message-db
boilerplate-test-message-db    | standard_init_linux.go:228: exec user process caused: exec format error
boilerplate-test-message-db exited with code 1
```

However, if I change the docker-compose to build the image from the Dockerfile instead of pulling from the ECR (same file used to build the image), it works...

```
version: "3.8"
services:
  boilerplate-test-message-db:
    build:
      context: ../cicd/dockerfile/message-db
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    expose:
      - '5432'
    container_name: boilerplate-test-message-db
```

The result without error
```
Run docker-compose -f tests/docker-compose.yml up
Creating network "tests_default" with the default driver
Building boilerplate-test-message-db
Sending build context to Docker daemon  4.608kB
Step 1/1 : FROM postgres:13-alpine
....
Image for service boilerplate-test-message-db was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Successfully tagged tests_boilerplate-test-message-db:latest
Creating boilerplate-test-message-db ... 
Creating boilerplate-test-message-db ... done
Attaching to boilerplate-test-message-db
boilerplate-test-message-db    | ********************************************************************************
boilerplate-test-message-db    | WARNING: POSTGRES_HOST_AUTH_METHOD has been set to "trust". This will allow
boilerplate-test-message-db    |          anyone with access to the Postgres port to access your database without
boilerplate-test-message-db    |          a password, even if POSTGRES_PASSWORD is set. See PostgreSQL
boilerplate-test-message-db    |          documentation about "trust":
...
```

Any idea how to make docker-compose work pulling the image from the URL instead of building it?

In localhost works perfectly with the URL.

I read in other discussion that placing `CMD tail -f /dev/null` at the end of the Dockerfile could make it work. I tried and that and didn't work.

Thank you!
