### DISCUSSION TITLE
How to update variable values in html file for sending email in github actions?

### DISCUSSION THREAD

**Discussion by ukreddy-erwin** [community/community#27525] [Actions]
I am trying to use the action from marketplace at this [link](https://github.com/juanformoso/action-send-mail)

It worked and the email is sent, but the variables are not expanded inside it.

The code snippet:

```
      - name: Send Build Email
        # You may pin to the exact commit or the version.
        # uses: juanformoso/action-send-mail@523ea7dd83e339d3c64fc4fdc2da0efc9014ea03
        uses: juanformoso/action-send-mail@1
        with:
          # SMTP server address
          server_address: smtp.sendgrid.net
          # SMTP server port
          server_port: 587
          # Authenticate as this user to SMTP server
          username: apikey
          # Authenticate with this password to SMTP server
          password: ${{secrets.MAIL_PASSWORD}}
          # Subject of mail message
          subject: ${{ github.workflow }} - Build Successful, GitHub_Build:${{ env.git_commit_count }} GitHubWorkflow_Build:${{ github.run_number }}
          # Body of mail message (might be a filename prefixed with file:// to read from)
          body: "file://installs_repo/Projectwise ISM files/${{ env.Version }}/mart_installs_email.html"
          # Recipients mail addresses (separated with comma)
          to: myemail@company.com
          # Email address of the sender
          from: myemail@company.com
          # Content-Type HTTP header (text/html or text/plain)
          content_type: text/html
          # Convert body from Markdown to HTML (set content_type input as text/html too)
          convert_markdown: true
```

The html file:
```

    <!DOCTYPE html>
    <html>
    <head>
    <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
    </style>
    </head>
    <body>
    
    <h2>${{ github.workflow }} - Successful</h2>
    
    <table>
      <tr>
        <td>GitHub Repository</td>
        <td>${{github.repository}}</td>
      </tr>
      <tr>
        <td>Github Actions Build Number</td>
        <td>${{ github.run_number }}</td>
      </tr>
      <tr>
        <td>GitHub Branch Name</td>
        <td>${{ github.ref_name }}</td>
      </tr>
      <tr>
        <td>Commit Message</td>
        <td>${{ github.event.head_commit.message }}</td>
      </tr>
      <tr>
        <td>Commit Count or Build Number</td>
        <td>${{ env.git_commit_count }}</td>
      </tr>
      <tr>
        <td>Daily Builds</td>
        <td>${{ secrets.DAILY_BUILDS_URL }}</td>
      </tr>
    </table>
    
    </body>
    </html>

```
And the email I am getting as like this.

![image](https://user-images.githubusercontent.com/21240709/181629554-8d368a92-12ae-4919-afe5-2327a90bbf4a.png)
