### DISCUSSION TITLE
Pushes from github actions do not trigger other github actions

### DISCUSSION THREAD

**Discussion by JJ** [community/community#27598] [Actions] [answered]
I have some github actions creating CSV files, here:

```
name: "Scrape downloaded HTML when created and generate CSV"
on:
  push:
    paths:
      - 'raw-pages/*.html'
      - '.github/workflows/generate-new-CSV.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate CSV using containerized script
        run: docker run -t -v `pwd`:/home/raku/test ghcr.io/jj/ukr-mod-data-csv:latest
      - name: Check in if there are changes
        run: |
          if [ -n "$(git status -s)" ]; then
              tools/commit-push.sh "Re-generates CSV"
              git push
          else
              echo "ℹ No changes in CSV"
          fi
```

It works correctly when triggered, and it pushes its file. However, I have this other action, that should be triggered when csv files are pushed:

```
name: "Generates parquet from the CSV file"
on:
  push:
    paths:
      - "resources/*.csv"
      - ".github/workflows/parquet.yml"

jobs:
  generate_parquet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.3"
      - name: Install CSV to Parquet cli tool
        run: go install github.com/fraugster/parquet-go/cmd/csv2parquet@latest
      - name: Convert CSV to Parquet
        working-directory: resources
        run: csv2parquet -input ukr-mod-data.csv -output ukr-mod-data.parquet
      - name: Check in
        run: |
          if [ -n "$(git status -s)" ]; then
              export DATE=$(date +"%y-%m-%d")
              tools/commit-push.sh "Re-generated parquet file for $DATE"
              git tag -a data-$DATE -m "Tagging data for $(date)"
              git push --follow-tags
          else
              echo "ℹ No changes in CSV"
          fi
```

But it does not work; it does when I push from a local repo. Is there anything I'm missing here, or some special target I should use for this?
