### DISCUSSION TITLE
How to access environment within job step

### DISCUSSION THREAD

**Discussion by morkalfon** [community/community#27611] [Other Feature Feedback, Questions, & Ideas]
Hello,

I'm looking for a way to access the environment name and url within a action step?

```
...
jobs:
  deploy:
    name: Deploy
    runs-on: [ self-hosted ]
    environment:
      name: 'name'
      url: 'url'
    steps:
    - name: get environment name
       if: ${{ <environment> == 'name' }}
       run: echo "condition match"
```

Thanks,
Mor
