### DISCUSSION TITLE
RUNNER_DEBUG not available at expression eval time?

### DISCUSSION THREAD

**Discussion by JustinGrote** [community/community#27627] [Actions] [answered]
My goal is to automatically enable more verbose logs in terraform by setting the TF_LOG env variable when I restart a job and check "enable debug logging"

RUNNER_DEBUG = 1 exists in the environment when you re-run a job and check "enable debug logging", however, at the eval time, it doesn't appear to exist.

```
##[debug]Evaluating: (env.RUNNER_DEBUG == [1](https://github.com/it-cdi/AzurePolicyOps/runs/7581939219?check_suite_focus=true#step:9:1))
##[debug]Evaluating Equal:
##[debug]..Evaluating Index:
##[debug]....Evaluating env:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'RUNNER_DEBUG'
##[debug]..=> null
##[debug]..Evaluating Number:
##[debug]..=> 1
##[debug]=> false
##[debug]Expanded: (null == 1)
##[debug]Result: false
##[debug]Evaluating condition for step: 'ShowEnv'
```

But running `dir env:` with PWSH in a step shows it is present:
```
RUNNER_ARCH                    X64
RUNNER_DEBUG                   1
RUNNER_NAME                    Hosted Agent
RUNNER_OS                      Linux
RUNNER_PERFLOG                 /home/runner/perflog
RUNNER_TEMP                    /home/runner/work/_temp
RUNNER_TOOL_CACHE              /opt/hostedtoolcache
RUNNER_TRACKING_ID             github_b9c94d59-5099-4815-82bd-6d72b19de953
RUNNER_USER                    runner
RUNNER_WORKSPACE               /home/runner/work/AzurePolicyOps
```

As a workaround, doing an if operation at the step level for the env variable works.

What is the best way to detect if debug logging is enabled at the action expression level, if this is not the correct way?

**Comment by ChristopherHX** [comment, marked as answer]
Hi,
All `RUNNER_<NAME>` are env variables created from the runner context, so just use the runner context in expressions and env variables in scripts.

e.g.
```yaml
on:
  push:
jobs:
  test:
    runs-on: self-hosted
    steps:
    - if: ${{ runner.debug == '1' }}
      run: |
        echo Debug!!!
```

https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context, weird it is not documented there.

**Reply by JustinGrote** [reply]
@ChristopherHX yeah that's what I would have thought, threw me it wasn't there, I'll test. Thanks!

**Reply by JustinGrote** [reply]
I made a PR to document it
https://github.com/github/docs/pull/19404/

And my usage, which worked as expected:
```yaml
     id: plan
      env:
        TF_LOG: "${{ runner.debug == 1 && 'INFO' || 'ERROR' }}"
      #Only main commits can write to the main state file so we dont need permissions to state lock
      run: |
        terraform plan -lock=false

```

**Reply by ChristopherHX** [reply]
Even the `RUNNER_DEBUG` env variable is not documented where it should be https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables. Based on the documentation neither `runner.debug` and `RUNNER_DEBUG` exists.

For Reference:
This
```
"${{ runner.debug == 1 && 'INFO' || 'ERROR' }}"
```
is the same as
```
"${{ runner.debug && 'INFO' || 'ERROR' }}"
```
And will also evaluate to `INFO` even if `runner.debug == '0'`, which never happen unless the hardcoded value in actions/runner is changed.

**Reply by JustinGrote** [reply]
@ChristopherHX hmm in my testing it worked fine...

**Reply by ChristopherHX** [reply]
Yes what you are doing works fine.

`runner.debug` is a string and you should be aware that it might cause unexpected behavior to compare a string with an integer.

You are basically doing `${{ '1' == 1 }}`, which evaluates to true as long `runner.debug` is defined to a string with length > 0. If the debug mode is off you are doing `${{ null == 1 }}`, which evaluates to false.

Therfore I would suggest that you should do:
```yaml
      id: plan
      env:
        TF_LOG: "${{ runner.debug == '1' && 'INFO' || 'ERROR' }}"
      #Only main commits can write to the main state file so we dont need permissions to state lock
      run: |
        terraform plan -lock=false
```
