### DISCUSSION TITLE
Why Billable Time is twice as long as Run Time.

### DISCUSSION THREAD

**Discussion by hayashi-ay** [community/community#27725] [Actions] [answered]
Hi, there! This is my first post to this community.

I found Billable Time is twice as long as Run Time. (See the below picture.)

At first I think the core number of the host runner is multiplied but if so mac os would be tripled because [macOS virtual machines have 3-core CPU](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

I read the documentation, but I can't find a description and I'd like to know why the above result.

### Reference
**billing result**

<img width="944" alt="スクリーンショット 2022-07-31 1 25 28" src="https://user-images.githubusercontent.com/39038230/181932906-b2dbbac7-09aa-4bce-ade0-55b2fd4d6fad.png">

**yml file for the above result**

```
name: test
on:
  push:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        shell: bash
        run: sleep 60
  windows:
    runs-on: windows-latest
    steps:
      - name: sleep
        shell: bash
        run: sleep 60
  mac:
    runs-on: macos-12
    steps:
      - name: sleep
        shell: bash
        run: sleep 60
```
