### DISCUSSION TITLE
Input as condition to skip step

### DISCUSSION THREAD

**Discussion by idleberg** [community/community#27727] [Actions]
I'm a bit puzzled why the following step never runs, no matter which value I specify for `dry_run`

```yaml
name: 'Demo Action'

inputs:
  dry_run:
    description: 'Skips creation of a release'
    default: 'false'
    # required: true

runs:
  using: "composite"
  steps:
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: ${{ inputs.dry_run != 'false' }}
      # if: inputs.dry_run != 'false'
```

I left the comments in the example, as I tried using them. Can anybody explain what I'm doing wrong? Do I need to set an environment variable instead?
