### DISCUSSION TITLE
Github actions: Idiomatic expressions for monorepo CI

### DISCUSSION THREAD

**Discussion by crypt3lx2k** [community/community#27741] [Actions]
Hi,

I have a monorepo with 100-ish projects and am wondering about how to best express a workflow for pull requests. The goals I have for this workflow,
- All projects can define their own set of CI actions
- Only projects touched by the pull request will have their CI actions executed in the workflow

The solutions I am considering:
Solution 1:
- Each project defines a `.ci/launch.sh` shell script
- Main workflow has these jobs:
  - Job "detect_changes": Checks which projects have changes in them and outputs as a json list
  - Job "ci": Depends on detect_changes and uses it as a strategy matrix
  - Job "ci": Has a step with `run: ${{ matrix.project }}/.ci/launch.sh`

The pros and cons of this solution:
Pros:
- Only jobs in Web UI actions output are the ones that had changes
- Main workflow is very compact
- Common steps are easily shared between projects

Cons:
- Can not use github actions jobs/steps in projects, as they have to be shell scripts

Solution 2:
- Each project defines a reusable workflow
- Main workflow has these jobs:
  - Job "detect_changes" as before
  - One job for each project (We might have to generate these programatically)
  - Each project job is gated by an `if: ${{ ... }}` checking whether the project is in the detect_changes outputs

The pros and cons of this solution:
Pros:
- Full flexibility on the project side to define services, use all github actions features

Cons:
- Many skipped jobs in Web UI actions output
- Very large main workflow file with one job per project
- Common steps have to be expressed in each project job (composite actions might help with some of these)

---

I'm noticing if:
- `jobs.<job_id>.uses` could access the `matrix` context I might be able to collapse the main workflow in Solution 2
- `jobs.<job_id>.steps[*].uses` could access the `matrix` context I might be able to create a new solution similar to Solution 1 but with per-project composite actions

My questions are as follows:
- What are some better ways to express what I want to do?
- If I wanted to make feature request to make `matrix` context available in `jobs.<job_id>.uses` or `jobs.<job_id>.steps[*].uses` which repo would be appropriate?

Thanks a lot for any responses/ideas.

**Comment by airtonix** [comment]
solution 1: 

you can use local composite actions, so instead of assuming you can only run a shell script, you can instead make it launch a local action: 

```
name: Mainline

'on':
  push:
    branches:
      - master

jobs:
  Changes:
    runs-on: ubuntu
    outputs:
      changed: steps.graph.output.changed
    steps:
      - name: compute change dep graph
        id: graph
        run: |
          # magical dependency graph change computation (like nx dev)
          echo set-output::changed=[app1, app2, lib1, lib2, tool1, etc ]

  Stuff:
    runs-on: ubuntu
    needs:
      - Changes
    strategy:
      matrix: 
        target: ${{ fromJSON(needs.Changed.outputs.changed) }}
          
    steps:
      - name: run project actions
        uses: ./pkg/${{ matrix.target }}/action
        with:
          Your: Statically
          Defined: inputs

```

`./pkg/app1/actions/action.yml` 

```
name: Stuff This Project Loves

description: |
  I love stuff!!!!

runs:
  using: 'composite'

  steps:
    - name: Announce love
      shell: bash
      run: echo ❤️
```

I'd recommend looking at nxdev and some of these : 

- https://github.com/e-square-io/nx-github-actions
- https://github.com/yannickglt/nx-github-build

**Reply by crypt3lx2k** [reply]
Hi @airtonix, thanks for the input.

Unfortunately I can't get the "uses" step to read the `${{ matrix.target }}` context, do you have an example in those repositories where that is done successfully?

This was part of the original post and I haven't been able to get it to work,
> If jobs.<job_id>.steps[*].uses could access the matrix context I might be able to create a new solution similar to Solution 1 but with per-project composite actions

Any help would be appreciated.

**Reply by airtonix** [reply]
Looks like this is a known problem: https://github.com/community/community/discussions/9049

But i'd get around this by generating a central router action: 

```
...

  Stuff:
    runs-on: ubuntu
    needs:
      - Changes
    strategy:
      matrix: 
        target: ${{ fromJSON(needs.Changed.outputs.changed) }}
          
    steps:
      - name: generate matrix router action
        env:
          MATRIX_TARGET: ${{matrix.target}}
        run: |
           cat ./.github/templates/stuff-matrix-router.yaml \
             | envsubst > ./.github/actions/stuff-matrix-router.yaml

      - name: run project actions
        uses: ./.github/actions/stuff-matrix-router.yaml
        with:
          Your: Statically defined
          Inputs: that are the same
          For: each project
```


haven't tested this out.

Another option is to have different workflow that accepts workflow_dispatch or some other event and in your matrix call, run the `gh` cli tool to trigger the other workflow for each matrix entry.
