### DISCUSSION TITLE
Fully qualified ${{ github.job }} per matrix execution, get name of current step

### DISCUSSION THREAD

**Discussion by iluuu1994** [community/community#27780] [Actions]
Hi! I have an action that runs tests and uploads test artifacts.

```
- shell: bash
  run: |
    set -x
    sapi/cli/php run-tests.php ...
- uses: actions/upload-artifact@v3
  if: always() && inputs.testArtifacts != null
  with:
    name: ${{ github.job }}_${{ inputs.testArtifacts }}
    path: ${{ github.workspace }}/junit.out.xml
```

This action is used in all of our jobs and sometimes multiple times with different parameters. In essence, the artifact name should be a combination of `${{ github.job }}` and something like `${{ github.step }}` (to get the name of the `step` in the workflow). There are two problems:

1. `github.step` doesn't exist so for now I'm passing the name of the step to `testArtifacts`.
2. `github.job` provides the name of the job not inlcluding the matrix (actually the key in the yaml), instead of the `name` I construct to be unique for each matrix variation. This leads to the artifacts getting the same name and overriding each other. The only solution right now is to repeat the name again, which can be quite lengthy as it generates a unique name for each matrix index.

For reference: https://github.com/php/php-src/pull/9163/files

It would be super nice if these two things were natively supported. Thanks for your response!
