### DISCUSSION TITLE
Github Concurrency Group

### DISCUSSION THREAD

**Discussion by rlinstorres** [community/community#27866] [Actions]
Hi, I would like to know if it is possible to configure a concurrency workflow run checking for another workflow, for example:

Let's assume I have two workflows: `concurrency-1.yml` and `concurrency-2.yml` and `concurrency-1` should only run when itself is not running and `concurrency-2` is not running.

I tried the options below, but none of them worked as I need:

```yaml
name: concurrency-1

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
#group: ${{ github.workflow }}-${{ github.ref }} || concurrency-2-${{ github.ref }}
#group: ${{ github.workflow }} || concurrency-2
#group: ${{ github.workflow || startsWith(github.workflow, 'concurrency-2') }}

jobs:
```

I didn't find anything related to it in https://docs.github.com/en/actions/using-jobs/using-concurrency.

Does anyone know if it is possible?
Thank you!

**Comment by Simran-B** [comment]
What concurrency group do you set in the other workflow?

While the docs state that you use an arbitrary expression, I believe that it always needs to return a string to define the concurrency group and using a logical or (`||`) only lets you define a fallback value, like shown in the docs example. Therefore, I think what you need to do is to set the same string in both of the workflows. If you want the second workflow to run concurrently to the first workflow, however, then I'm not sure how you would set the concurrency group using some expression.

**Reply by rlinstorres** [reply]
> What concurrency group do you set in the other workflow?
> 
> While the docs state that you use an arbitrary expression, I believe that it always needs to return a string to define the concurrency group and using a logical or (`||`) only lets you define a fallback value, like shown in the docs example. Therefore, I think what you need to do is to set the same string in both of the workflows. If you want the second workflow to run concurrently to the first workflow, however, then I'm not sure how you would set the concurrency group using some expression.

Hi @Simran-B, let me share the workflows trying to clarify them, to be honest, I am not sure if I am trying something impossible 😄 
**Note:** I also tried to configure a concurrency group only checking for the second workflow and it doesn't work, my example, below:

```yaml
name: concurrency-1

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: concurrency-2
#  group: concurrency-2 || concurrency-1 || ${{ github.workflow }}-${{ github.ref }}
#  group: ${{ github.ref }} || concurrency-2
#  group: ${{ github.workflow || startsWith(github.workflow, 'concurrency-2') }}

jobs:
```
and
```yaml
name: concurrency-2

on:
  workflow_run:
    workflows: [concurrency-1]
    types: [completed]
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
```
