### DISCUSSION TITLE
InvalidProfileError using github actions to deploy on Elastic Bean

### DISCUSSION THREAD

**Discussion by umaimehm** [community/community#27873] [Actions]
I am using github actions to deploy my Django app to Elastic bean.

My .elasticbeanstalk/config.yml file is:

```
branch-defaults:
  amazon-deploy:
    environment: platform-prod
    group_suffix: null
global:
  application_name: platform
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
```

I have the following code on my github actions (.github/workflows/github_actions.yml:

   ```
 name: EB deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy platform-prod

```
When I execute github action, I get the following error:

```
ERROR: InvalidProfileError - The config profile (ecb-cli) could not be found
Error: Process completed with exit code 4.
```

I have changed the profile from ecb-cli to default but I still get the same error. Can anyone please help. Thank you.
