### DISCUSSION TITLE
Require multiple events to trigger job

### DISCUSSION THREAD

**Discussion by troncoso** [community/community#27957] [Actions]
I did search for this, but I can't find anything referencing my exact use case. Granted, it is hard to search for this in a way that gives relevant results.

[The docs](https://docs.github.com/en/github-ae@latest/actions/using-workflows/triggering-a-workflow#using-multiple-events) themselves explicitly state:

> If you specify multiple events, only one of those events needs to occur to trigger your workflow

What I would like to do is require that all events occur before triggering a job. For example, I have a workflow called "Validate" that runs the tests for all my packages in my monorepo. I then have "Deploy Client" and "Deploy Server". I would only like to run these if the "Validation" workflow passed AND files were changed in their respective packages.

Is there a way to accomplish this? For clarification, here is the top of my current "Deploy Client" workflow:

```yaml
name: Deploy Client

on:
  push:
    branches: [ master ]
    paths:
      - apps/client/**
  workflow_run:
    workflows: ["Validate All Packages"]
    branches: [master]
    types:
      - completed
```

Currently, this workflow runs if either events occur. But I would only like this to happen if both do.
