### DISCUSSION TITLE
GitHub Actions status checks not failing despite workflow failing

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#28202] [Actions]
I have the following event listeners on my workflow

```
name: Test Workflow

on:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  issue_comment:

jobs:
  a-job:
    runs-on: ubuntu-latest

    steps:
      - name: do something
        shell: bash
        run: something
```

I noticed than when I write a comment into the PR, the workflow **does** execute but if the workflow **fails**, the status check in my PR is not marked as failed

Any ideas why this might be happening?
