### DISCUSSION TITLE
Dockerfile builds fine locally but not on GitHub Actions

### DISCUSSION THREAD

**Discussion by RohanKapurDEV** [community/community#28285] [Actions] [answered]
So i have the following dockerfile [in this repo](https://github.com/RohanKapurDEV/pantheon-core). It is located in the `backend/executor` folder:

```Dockerfile
FROM node:17.3 AS builder

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY prisma ./prisma/

# Install app dependencies
RUN npm install

COPY . .

RUN npm run build

FROM node:17.3

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]
```

I have the following GH Actions script that builds the image and pushes it to AWS ECR:

```yaml
name: Push executor API to ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "main"
    paths:
      - "backend/executor/**"
      - ".github/workflows/executor-ecr-workflow.yml"

  pull_request:
    branches:
      - "main"
    paths:
      - "backend/executor/**"
      - ".github/workflows/executor-ecr-workflow.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pantheon-executor-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f backend/executor/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

```

Locally, I can build this Dockerfile just fine by running `docker build -t executor-api --load .` but when the actions worker job runs, I get the following error from the build step: 

```
Step 4/13 : COPY prisma ./prisma/
COPY failed: file not found in build context or excluded by .dockerignore: stat prisma: file does not exist
Error: Process completed with exit code 1.
```

You can see the full job output [here](https://github.com/RohanKapurDEV/pantheon-core/runs/7665639223?check_suite_focus=true). It says I don't have the prisma folder in the build context (which I assume is the `backend/executor` folder since that is where the Dockerfile is located), but it is literally in the folder and is not excluded from the `.dockerignore` file from what I can tell.

Anyone know why this fails on Github Actions? Would appreciate any direction here
