### DISCUSSION TITLE
Confused about the current working directory.

### DISCUSSION THREAD

**Discussion by ATPAustinPeng** [community/community#28283] [Actions]
I'm trying to use https://github.com/actions/download-artifact to download a single artifact to my local repo. What is meant by "current working directory" in the documentation below"

ex. The repo with my workflow is called `test-action`. After pushing the changes to my repo, a GitHub action runs and uploads an artifact. I want to then download this artifact into the root directory of my `test-action` repository of my local computer. That way I can push the artifact to my repo.

```
Basic (download to the current working directory):

steps:
- uses: actions/checkout@v2

- uses: actions/download-artifact@v3
  with:
    name: my-artifact
    
- name: Display structure of downloaded files
  run: ls -R
```
