### DISCUSSION TITLE
Templates (like issue templates) for discussions

### DISCUSSION THREAD

**Discussion by tiangolo** [community/community#2838] [Discussions] [answered]
**2023-01-23 Edit**:

This feature is now supported and released! :tada: 

Read the blog post by GitHub: https://github.blog/2023-01-09-github-discussions-just-got-better-with-category-forms/

Read the docs: https://docs.github.com/en/discussions/managing-discussions-for-your-community/creating-discussion-category-forms

There's an example in the docs here: https://docs.github.com/en/discussions/managing-discussions-for-your-community/syntax-for-discussion-category-forms ...but as of now, the YAML syntax in that example in the docs is broken.

Here's that same official example with the syntax fixed: 

```YAML
title: "[General] "
labels: ["General Introduction"]
body:
  - type: markdown
    attributes:
      value: |
        This is text that will show up in the template!
  - type: textarea
    id: improvements
    attributes:
      label: Top 3 improvements
      description: "What are the top 3 improvements we could make to this project?"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
```

---

Hey! 👋

I really like the idea of discussions.

I have been working around not having them with issues marked as questions and some tricks. Most of the issues I have are actually questions, and that's what ends up consuming most of the time.

Now that I have discussions available in https://github.com/tiangolo/fastapi, I see that there's no way to set up templates for a new discussion.

Having templates for issues has helped a lot in handling questions, as it helps encourage users to think through the problem and provide a replicable example of what they want to achieve and what is not working. Before that, the repo was filling with cryptic issues saying only "it's not working!" and similar.

It would be awesome to be able to have templates for the questions in discussions.
