### DISCUSSION TITLE
How to get commit message on pull_request workflow?

### DISCUSSION THREAD

**Discussion by gabrielbahniuk** [community/community#28474] [Actions] [answered]
Hi there,

i have some jobs running when people open pull request, so it starts like this:

```
name: PR checks

on: pull_request

jobs:
  cleanup:
   [...]
  eslint:
   [...]
  unit_tests:
   [...]
  e2e_tests_A:
   [...]
  e2e_tests_B:
   [...]
```

In `e2e_tests_A` or `B`  I want to have a conditional that: if commit message contains something I define e.g. `git commit -m [skip e2e_tests_A] && git push` then the job `e2e_tests_A` should NOT run.

I ended up adding the following to e2e_tests_A:

`   if: "!contains(github.event.head_commit.message, '[skip e2e_tests_A]')"`

According to the following urls, it won't work because I can only have `github.event.head_commit.message` if I had `on: push` and I currently have `on: pull_request`:

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push

I know Github has already some keywords like [skip ci] and similar but I want to define my own keywords to the commit message.

Also, according to my searches, `github.event.head_commit.message` was working in the past. Was it replaced by something else or just removed?

So I would be thankful if anyone knows how I can solve this.

Thanks in advance!!

**Comment by airtower-luna** [comment, marked as answer]
> So I would be thankful if anyone knows how I can solve this.

The first question to answer here is: Which commit(s) do you want to look at? Only the head commit of the pull request branch? All commits on the branch (which could be many)?

`github.event.pull_request.head.sha` should give you the ID of the head commit, `github.event.pull_request.base.sha` that of the base (target) branch (in case you want to look at all commits).

Note that you'll have to [tell `actions/checkout` to download more than the latest commit](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches) if you want to inspect those, or fetch the relevant part of history in your workflow. The triggering commit for `pull_request` events is a temporary merge commit, so it's none of your commits. :wink:

**Reply by gabrielbahniuk** [reply]
@airtower-luna thanks for the response!

> The first question to answer here is: Which commit(s) do you want to look at? Only the head commit of the pull request branch? All commits on the branch (which could be many)?

I want only the head commit **message**.

If I understand your suggestion correctly, I could use `actions/checkout` with `ref: ${{ github.event.pull_request.head.sha }}` and then I would be able to get the commit message.

So the end result would look similar to this:

```yml
jobs:
  check_skip_flags:
    name: Check skip flags
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        run: |
          echo "$(git show -s --format=%s)" 
          
   e2e_tests_A:
    name: E2E tests
    runs-on: self-hosted
    needs: check_skip_flags
    # if: // i don't really know how to get the git show result here
    timeout-minutes: 120
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
```

I came up with different solutions but let's use the above one to exemplify. How would I be able to save `git show` command into some env variable and use it in my `if` condition in `e2e_tests_A`?


One of my failed attempts was adding `outputs` to `check_skip_flags` job and `id`  to the second step, looking similar to:

```yml
[...]
  check_skip_flags:
    name: Check skip flags
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs }}
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"

  e2e_tests_A:
    name: E2E tests
    runs-on: self-hosted
    needs: check_skip_flags
    if: ${{ !contains(steps.get_head_commit_message.outputs.data, '[skip e2e_tests_A]') }}
[...]
```

but this didn't work as well.

**Reply by airtower-luna** [reply]
In principle the output approach is correct, at least as long as you stick to the single line format. For multiple lines you'd have to URL encode the newlines so they don't get cut off while setting the output.

The issues I see above are:

* The `outputs` setting in `check_skip_flags` doesn't reference the actual output, just the `outputs` object of the relevant step (might work with `toJSON()` if you really wanted to).
* The `steps` context doesn't carry across jobs. You [need to use the `needs` context](https://docs.github.com/en/actions/learn-github-actions/contexts#example-usage-of-the-needs-context) to access outputs from previous jobs.

Something like this should work:

```yaml
  check_skip_flags:
    name: Check skip flags
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"

  e2e_tests_A:
    name: E2E tests
    runs-on: self-hosted
    needs: check_skip_flags
    if: ${{ !contains(needs.check_skip_flags.outputs.head-commit-message, '[skip e2e_tests_A]') }}
```

**Reply by gabrielbahniuk** [reply]
@airtower-luna oh i missed that on the `if` i had to use `needs`, not `steps`, thank you, it worked nicely!! =D

**Reply by airtower-luna** [reply]
Excellent, I'm glad to hear it worked! Marking the answer would be appreciated. :smile_cat:

**Reply by ILikePlayingGames** [reply]
@airtower-luna thank you! I had the same issue with the `workflow_dispatch` event and your solution worked. 
For anyone else who recently found this via Google, the set-output command has been [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). The new steps use the [GITHUB_SHA](https://docs.github.com/en/actions/learn-github-actions/variables) variable and the [$GITHUB_OUTPUT](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) environment file.

```yaml
    - name: Checkout Commit
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_SHA }}
    - name: Get Head Commit Message
      id: get_head_commit_message
      run: echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
```

**Reply by 3barroso** [reply]
Thanks for the head start here!! My ref was going towards a pull request so I had to use a different ref for the branch that had the commit message I wanted. Here are the [github docs](https://github.com/marketplace/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit) I ended up needing
```
with: 
    ref: ${{ github.event.pull_request.head.sha }}
```

**Comment by mustafabahaa** [comment]
Sorry but I'm confused, in the solution purposed we checkout the last commit on the branch to get the commit message, we are not checking the merge commit, testing the last commit on the pull request branch and testing on merge commit is different, and it may introduce other issue after merging because we didn't test the merge commit, am i missing something ?

**Reply by airtower-luna** [reply]
The question was about how to get the commit message of a specific commit (the HEAD commit of the branch to be merged). For running test using the temporary merge commit is almost certainly what you want.

**Reply by mustafabahaa** [reply]
Okay, maybe probably you will have to checkout again with the merge commit later, or try to checkout the merge commit by any other means , i didn't want to handle this I've chosen another path

without checking out the branch using ref,  you can curl the path ${{ github.event.pull_request.commits_url }} this will give you a response with all commits on the branch you can just filter to the last one then access the message using commit.message

**Comment by hytromo** [comment]
Solution without need for additional job and re-checkout.
```yaml
- name: Get commit message
  id: get_commit_message
  uses: actions/github-script@v7
  with:
    script: |
      const { data } = await github.rest.repos.getCommit({
        owner: context.repo.owner,
        repo: context.repo.repo,
        ref: context.payload.pull_request?.head?.sha // For pull_request event
                ?? context.payload.merge_group?.head_sha // For merge_group event
                ?? context.sha, // For push, workflow_dispatch, or other direct context.sha events
      });

      core.setOutput('value', data?.commit?.message);
```
