### DISCUSSION TITLE
Ability to specify workflow_dispatch input defaults via url query parameter?

### DISCUSSION THREAD

**Discussion by dsherret** [community/community#28505] [Actions]
Given a workflow file *version_bump.yml* with the following `workflow_dispatch` inputs:

```
on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: 'Kind of version bump'
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        required: true
```

It would be neat to be able to override the "default" value via a query parameter when linking to the workflow. For example: `https://github.com/org/repo/actions/workflows/version_bump.yml?releaseKind=minor` would have the drop down pre-select "minor" -- Is this possible? Or is there a better way of doing this, for example even starting the workflow with inputs via a url? Thanks!
