### DISCUSSION TITLE
Can a job have it's dependencies chosen based on a condition?

### DISCUSSION THREAD

**Discussion by shadogar** [community/community#28521] [Actions]
I have an action that looks like this

```
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Build
        run: ./build.sh
      - name: Save Build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build/
          retention-days: 7

  dev:
    needs: build
    uses: ./.github/workflows/deploy-env.yaml
    with:
      stage: dev

  staging:
    needs: dev
    uses: ./.github/workflows/deploy-env.yaml
    with:
      stage: staging

  prod:
    needs: staging
    uses: ./.github/workflows/deploy-env.yaml
    with:
      stage: prod
```

However, the action is triggered by both pull_request and push, and I'd like the `needs` to be based on that.

I attempted the following on the staging job but it didn't work

```
needs: ${{ github.event_name == 'pull_request' && ['build'] || ['dev'] }}
```
