### DISCUSSION TITLE
My secret is not injected in the job environment

### DISCUSSION THREAD

**Discussion by NealRame** [community/community#28653] [Actions] [answered]
Hi,

I'm following the instructions in the GitHub Actions documentation but I can't seem to publish a package to the npm registry.

Here is my workflow:
```yaml
name: Node.js Package

on:
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 15
            - run: npm ci
            - run: npm test
    
    publish-npm:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 15
                registry-url: "https://registry.npmjs.org"
                scope: "@nealrame"
                always-auth: true
            - run: npm ci
            - run: npm run build
            - run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
```

Of course I defined the `NPM_TOKEN`secret 
<img width="932" alt="Screenshot 2022-08-07 at 12 37 42" src="https://user-images.githubusercontent.com/1485122/183288620-a3e59f33-1470-4fb2-b8d3-71cb47592ba1.png">

However it does not work. It seems that the environment variable `NODE_AUTH_TOKEN `is defined for the two first run steps (`npm ci` and `npm run build`) and when the third run step is executed the environment variable is no more defined.
<img width="755" alt="Screenshot 2022-08-07 at 12 41 10" src="https://user-images.githubusercontent.com/1485122/183288707-714b8f8c-268b-44bd-a70c-f7ccf288c1fb.png">

If anyone has any idea what's going on with my workflow please let me know.
