### DISCUSSION TITLE
Github Actions - Recursive repository cloning error

### DISCUSSION THREAD

**Discussion by RMJTromp** [community/community#28672] [Actions] [answered]
I've been trying to make an GitHub action that compiles jar files and add them to a release when a release is created.
To compile the jar files, I need to clone the parent module, and clone all submodules recursively.
Now, normally I'd do that with `git clone --recurse-submodules -j8 https://github.com/RunicSky/RunicSky.git`, which BTW works perfectly on my local machine. I've made multiple attempts at making this work, but none have them worked. I keep getting the same two errors, and it's genuinely starting to drive me nuts, and I couldn't find any working solution.

#### The first error is the following:
![First Error](https://i.imgur.com/hBnhwLH.png)
It keeps saying that it could not read the Username for GitHub.
I've tried multiple things;
- Running with access tokens
```shell
git clone --recurse-submodules -j8 https://${{ secrets.ACCESS_TOKEN }}@github.com/RunicSky/RunicSky.git
```
- Running with SSH key
```shell
eval `ssh-agent -s`
ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
git clone --recurse-submodules -j8 https://github.com/RunicSky/RunicSky.git
```
- First cloning parent, then initializing submodules
```shell
eval `ssh-agent -s`
ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
git clone git@github.com:RunicSky/RunicSky.git
cd RunicSky
git submodule update --init --recursive
```

#### The second error is the following:
![Second Error](https://i.imgur.com/brGh9rv.png)
It keeps saying that it could not clone it because it can't find the repository
I've also tried multiple things;
- Action checkout
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Preparing Repositories
      uses: actions/checkout@v3
      with:
        repository: 'RunicSky/RunicSky'
        submodules: true
```
- Action checkout with SSH and 
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Preparing Repositories
      uses: actions/checkout@v3
      with:
        repository: 'RunicSky/RunicSky'
        ref: 'main'
        ssh-key: '${{ secrets.PRIVATE_SSH_KEY }}'
        submodules: true
```

**NOTE**: it is a private repository which I have full access to

**Comment by airtower-luna** [comment, marked as answer]
Adding a token to the URL isn't going to work because `actions/checkout` overrides it with the `Authorization` header. "Not found" in HTTPS fetch generally means "no access" if the URL is correct, so I assume the submodules are private repositories, too. And the default `GITHUB_TOKEN` doesn't have access to other private repositories.

In that case the easiest solution is to [use the `token` parameter](https://github.com/actions/checkout#checkout-multiple-repos-private) to give `actions/checkout` a PAT with the right permissions.

I can't guess what's going wrong with SSH because there's no log.

**Reply by RMJTromp** [reply]
> Adding a token to the URL isn't going to work because `actions/checkout` overrides it with the `Authorization` header. "Not found" in HTTPS fetch generally means "no access" if the URL is correct, so I assume the submodules are private repositories, too. And the default `GITHUB_TOKEN` doesn't have access to other private repositories.
> 
> In that case the easiest solution is to [use the `token` parameter](https://github.com/actions/checkout#checkout-multiple-repos-private) to give `actions/checkout` a PAT with the right permissions.
> 
> I can't guess what's going wrong with SSH because there's no log.

Thank you, I added the token parameter, and it's no longer giving error, and cloning submodule properly. But I'm still stuck, because it's not cloning the submodule's submodules

This is my current configuration
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Preparing Repositories
      uses: actions/checkout@v3
      with:
        repository: 'RunicSky/RunicSky'
        ref: 'main'
        ssh-key: '${{ secrets.PRIVATE_SSH_KEY }}'
        token: '${{ secrets.ACCESS_TOKEN }}'
        submodules: true
        fetch-depth: 0
```

**Reply by airtower-luna** [reply]
Okay, recursive submodules are an issue I haven't had, but from the docs:

> Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules.

So assuming it works as documented, this should work:

```yaml
    - name: Preparing Repositories
      uses: actions/checkout@v3
      with:
        token: '${{ secrets.ACCESS_TOKEN }}'
        submodules: recursive
```

Whether you need to specify anything else depends on your workflow, if you're getting the repository on which the workflow was triggered you usually don't need to specify it explicitly.

`fetch-depth` has nothing to do with submodules, it's about history.
