### DISCUSSION TITLE
can not trigger github actions

### DISCUSSION THREAD

**Discussion by WizardXiao** [community/community#28701] [Actions] [answered]
i submit a pull request to master branch.
 the repo has configuration:
```
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
```  
i can not trigger github actions, but other pull request can trigger github actions and they make no changes to the configuration file.
i doubt that my account is restricted to trigger github actions.
