### DISCUSSION TITLE
Reusable Workflows: jobs.<job_id>.steps[*].secrets is not allowed

### DISCUSSION THREAD

**Discussion by nkuba** [community/community#28748] [Actions] [answered]
I try to call a reusable workflow as a job's step, but the schema is not allowing that.
`secrets` property is not allowed under `jobs.<job_id>.steps[*].secrets`:
```yaml
jobs:
  docker-build-and-publish:
    steps:
      - uses: ./.github/workflows/common-docker.yml
        with:
          environment: ${{ github.event.inputs.environment }}
        secrets:
          gcr-json-key: ${{ secrets.TEST_GCR_JSON_KEY }}
```

On the other hand it works fine when the reusable workflow is called as a job:
```yaml
jobs:
  docker-build-and-publish:
    - uses: ./.github/workflows/common-docker.yml
      with:
        environment: ${{ github.event.inputs.environment }}
      secrets:
        gcr-json-key: ${{ secrets.TEST_GCR_JSON_KEY }}
```

Please correct me if I'm wrong, but I believe that it should work in both ways described above.
