### DISCUSSION TITLE
Nest a variable in a variable for fetching secrets

### DISCUSSION THREAD

**Discussion by LisanDia** [community/community#28818] [Actions] [answered]
I'm struggling to fetch the secret develop_gcp_key_base64 working 

```
name: Activate google account

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - develop
        - main
        - staging
      
jobs:
  install-build-deploy:
    runs-on: ubuntu-latest

    container: google/cloud-sdk:slim
    
    concurrency:
      group: ${{ github.job }}-${{ github.ref_name }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v2

      - name: Activate GCP Service Account for ${{ inputs.choice }}
        env:
          ${{ inputs.choice }}_gcp_key_base64:  ${{ secrets[format(inputs.choice, '_gcp_key_base64')] }}
        run: |
          echo $${{ inputs.choice }}_gcp_key_base64 |  base64 --d > /deployment.json
          gcloud auth activate-service-account --key-file /deployment.json
          rm -f /deployment.json
```

output with the hardcoded values:

![image](https://user-images.githubusercontent.com/104592336/183533241-5ece79ce-c740-461f-8da3-863543beb269.png)

the error i'm getting:

![image](https://user-images.githubusercontent.com/104592336/183533359-61614b1d-d0d1-4d03-8ec3-de27899c2bd8.png)

Any help would be greatly appreciated.
