### DISCUSSION TITLE
Github Actions: PSModulePath is Altered in a Container Context

### DISCUSSION THREAD

**Discussion by shurick81** [community/community#28882] [Actions]
Hi, could someone explain why the PSModulePath variable is updated when I run actions in containers?

When I run a container in a docker, I get this:

```output
shurick81@AAP-GY1DYD3:~/projects/SharePointDsc-Dev-Infra$ docker run --rm -it mcr.microsoft.com/azure-powershell:8.2.0-alpine-3.14
PowerShell 7.2.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /> $env:PSModulePath
/root/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules
```

However, when I run the same container in GitHub Actions, 

```yml
name: Integration Test

on: 
  push:
    branches: '**'

jobs:
  test-win2012r2-clean:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/azure-powershell:8.2.0-alpine-3.14
    steps:
    - uses: actions/checkout@v2
    - run: |
        $env:PSModulePath
      shell: pwsh
```

I get a different value:

```output
/github/home/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules
```

so it is the `github` instead of `root`.

This is the workaround I had to use but it is not a solid solution:

```yml
name: Integration Test

on: 
  push:
    branches: '**'

jobs:
  test-win2012r2-clean:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/azure-powershell:8.2.0-alpine-3.14
    steps:
    - run: |
        $env:PSModulePath = "/github/home/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules:/root/.local/share/powershell/Modules"
        Get-Module -ListAvailable
```
