### DISCUSSION TITLE
Reusable Github Workflows Errors Out Requiring 'steps'

### DISCUSSION THREAD

**Discussion by ng-brandon** [community/community#29177] [Actions] [answered]
Hello,

I'm kind of new to Github Actions and trying to set up a reusable workflow, and have one workflow call another. The workflows are located within the same project folder, .github/workflows/release.yml, and .github/workflows/deploy.yml. The release file will call on deploy.yml. When I do that, I get a syntax error on release.yml:

```
No steps defined in `steps` for the following jobs: call-workflow-1-in-local-repo
```

Here is what my release.yml file looks like:

```
name: Release
on:
  workflow_dispatch:
jobs:
  call-workflow-1-in-local-repo:
    uses: my-org/test-project/.github/workflows/deploy.yml@main
```

I followed instructions from the docs but not sure where I am wrong. I am running on a Github enterprise account using self-hosted machines. Anyone has seen this problem before?

**Comment by airtower-luna** [comment]
The quoted workflow looks okay, assuming the path and branch name are valid. Based on that my first thought is to check the *called* workflow.

**Reply by ng-brandon** [reply]
deploy.yml looks like this

```
name: Deployer
on: 
  workflow_call:
    inputs: 
      version:
        description: 'Version'
        required: True
        type: string
      environment:
        description: 'Environment'
        required: True
        type: choice
        options:
          - qa
          - prod
  workflow_dispatch:
    inputs: 
      version:
        description: 'Version'
        required: True
        type: string
      environment:
        description: 'Environment'
        required: True
        type: choice
        options:
          - qa
          - prod
jobs:
  deploy-1:
    name: deploy
    runs-on: self-hosted
    container:
      image: <some-docker-container>
    steps:
      - name: Echo
        run: echo ${{ github.events.inputs.environment }}
```
It doesn't yell about anything in this file. I also tried kicking it off manually and works just fine.
