### DISCUSSION TITLE
Inputs take default values on non-manual trigger

### DISCUSSION THREAD

**Discussion by ivansenic** [community/community#29242] [Actions] [answered]
I have the workflow that is defining the triggers in the following way (full workflow available :arrow_right:  https://github.com/stargate/stargate/blob/master/.github/workflows/release.yml):

```
on:
  push:
    tags:
      - 'v1.*.*'

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publishing JARs to OSSRH?'
        required: true
        default: false
        type: boolean
      tag:
        description: 'Custom release tag value.'
        required: true
        type: string
```

and then have a conditional step based on the input like:

```
      - name: Publish package
        if: ${{ inputs.publish != false }}
        run: ...
```

I was expecting that when the job is triggered with the tag push, that `inputs.publish` can not be `false` and the condition will always resolve to true. I was guided by the documentation about the [inputs context](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context), where it's stated:

> This context is only available in a reusable workflow or in a workflow triggered by the workflow_dispatch event. You can access this context from any job or step in a workflow. This object contains the properties listed below.

But in the [run that was triggered by the tag push](https://github.com/stargate/stargate/actions/runs/2843329303), it's clear that the condition resolves as false and step is skipped. How can this be? Are input defaults available in the non-manual triggers?

**Comment by airtower-luna** [comment, marked as answer]
I have a suspicion at least, and it has to do with type conversion. The `push` event doesn't have an `inputs` context, so `inputs.publish` evaluates to an empty string. And the [expression operators documentation](https://docs.github.com/en/actions/learn-github-actions/expressions#operators) describes:

> GitHub performs loose equality comparisons.
> * If the types do not match, GitHub coerces the type to a number. GitHub casts data types to a number using these conversions: [...]

If you read those rules, false gets converted to zero, and so does an empty string. It's kind of like Javascript. :sweat_smile: 

I'd try this:

```yaml
        if: ${{ inputs.publish }}
```

Should work if `inputs.publish` is a boolean, and an empty string should behave like `false`.

**Reply by ivansenic** [reply]
@airtower-luna Thanks so much for point this out to me.. However, I want the step to run if the `input`s are not defined.. Can this be done with:

```
        if: ${{ inputs == null || inputs.publish == true }}
```

This should work right?

**Reply by tatu-at-datastax** [reply]
Alternatively it might be easier and more reliable to change logic and name of the input parameter to something like "skipPublish".
While more awkward, it would count on default value for booleans being `false`. Default for manual trigger could be `true`.

So check would be something like:

```
   if:  ${{ !inputs.skipPublish }}
```

**Reply by airtower-luna** [reply]
@ivansenic I assume it would, but testing for a missing context isn't something I've tested. Turning the meaning of the boolean around as @tatu-at-datastax suggested is probably the better solution, because it results in a more simple expression. :slightly_smiling_face:

**Reply by ivansenic** [reply]
Yea, I'll follow suggestion from @tatu-at-datastax

**Comment by andrea-cassioli-maersk** [comment]
I have the same issue, but the proposed solution does not seem to work. Consider the following:
```

on:
  workflow_dispatch:
    inputs:
      forceDeployment:
        description: 'Force branch deployment'
        required: true
        type: boolean
        default: false
  push:
    branches:
      - main
...

if:  ${{ github.ref_name == 'main' || inputs.forceDeployment }}
  ...
```

if `push` is the trigger it seems `inputs.forceDeployment` is equal to `''` and I get an error

```
Unexpected type of value '', expected type: Boolean.
```

It seems that the expression fails to evaluate. Any thoughts?

**Reply by airtower-luna** [reply]
With a `push` event the whole [`inputs` context is unavailable](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context), which apparently evaluates to an empty string.

You could try:

```yaml
if:  ${{ github.ref_name == 'main' || inputs.forceDeployment == true}}
```

The way I understand the [equality comparison rules](https://docs.github.com/en/actions/learn-github-actions/expressions#operators) booleans should be compared directly (in that case the `== true` is redundant), but with different types (string and boolean) both will be converted to integers, with an empty string turning into 0 and `true` turning into 1.

**Reply by IanTaylor-catapult** [reply]
This makes sense after being explained. But is absolutely unintuitive and definitely not the way this should function. Why in the world would setting a default for an input variable not be passed into the job regardless of event type? That seems antithetical. So the only way to provide a guaranteed default in input is to add a duplicate variable to the push event, which is illegal as far as I know?

Should this not be clearly stated in documentation? Caused me hours of headaches trying to figure out why expected behavior was failing.

**Reply by a-matthew** [reply]
You can also implement conditional values inside the template expression ${{ }} block that e.g. provides the inputs to the job in the "with" block on selected event types (thus overwriting the empty value) or (presumably, untested) also the "if".

`if:  ${{ github.event_name == "push" && false || github.event_name != "push" && github.ref_name == 'main' && inputs.forceDeployment }}` (but you can obviously have many different event types)

so it could also look like
`if:  ${{ github.event_name != "workflow_dispatch" && false || github.event_name == "workflow_dispatch" && github.ref_name == 'main' && inputs.forceDeployment }}`

or in a different case:
`value: ${{ github.event_name != "workflow_dispatch" && 'value1' || github.event_name == "workflow_dispatch" && inputs.value }}`

Like so and it should work. The obvious issue are the hardcoded fallback values, which defeat the whole conceptual point of default values per input inside callable workflows or top-level dispatchable workflows. You either get an empty value that you must overwrite, or you have an empty value that blocks the default values inside reusable workflows's inputs... (which you must conclusively also overwrite).

**Comment by rlinstorres** [comment]
It might be useful for someone!
In our cases, we decided to use a non-native solution by creating a specific job to normalize these inputs, e.g.:

```
on:
  pull_request:
  workflow_dispatch:
    inputs:
      foo:
        type: boolean
        default: false

jobs:
  normalize_inputs:
    name: Correct Variables
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.normalize_inputs.outputs.foo }}
    steps:
      - id: normalize_inputs
        env:
          foo: ${{ github.event.inputs.foo }}
        run: |
          echo "foo=${foo:-false}" >> $GITHUB_OUTPUT

  another_job:
    needs: [normalize_inputs]
    ...
    with:
      foo: ${{ needs.normalize_inputs.outputs.foo }}
```
