### DISCUSSION TITLE
Reusable workflow throws Unrecognized named-value: 'env'

### DISCUSSION THREAD

**Discussion by dkirrane** [community/community#29251] [Actions]
Reusable workflow throws `Unrecognized named-value: 'env'. Located at position 1 within expression: env.WORKSPACE`

Is there anyway to use an env variable in a reusable workflow?

I've tried `${{ env.WORKSPACE }}` and `$WORKSPACE`. Both do not work
```
name: My Workflow

on:
  workflow_dispatch:

env:
  WORKSPACE: dev-1

jobs:

  MyJob:
    uses: mycompany/myrepo/.github/workflows/reusable-workflow.yml@main
    secrets: inherit
    with:
      # workspace: $WORKSPACE
      workspace: ${{ env.WORKSPACE }}
```
