### DISCUSSION TITLE
Setting up linux docker daemon on windows runner

### DISCUSSION THREAD

**Discussion by pschoffer** [community/community#29255] [Actions]
# Question
Is there a way to configure `windows-latest` action runner to support linux based images?

Here is minimal workflow to reproduce:
```
name: Run linux based image
on:
  pull_request

jobs:
  Try_pull_image:
    name: Try pull Image
    runs-on: windows-latest
    steps:
      - name: Image pull step
        run: docker pull ubuntu
```

This fails with:
```
Using default tag: latest
latest: Pulling from library/ubuntu
no matching manifest for windows/amd[6](...)4 10.0.20348 in the manifest list entries
Error: Process completed with exit code 1.
```

# Context
I am trying to write and automated test that would verify our tool that creates local development environment for windows users. The tool itself is using linux based docker images. Our users are using docker server with Linux architecture to achieve this.

Is there a linux based docker server running on `windows-latest` or is there a way to enable and reconfigure the client to use that one instead?

I found similar question [here](https://github.com/microsoft/azure-pipelines-tasks/issues/16089)
