### DISCUSSION TITLE
Setting up Apple Developer account on Xcode

### DISCUSSION THREAD

**Discussion by apetkov-so** [community/community#29318] [Other Feature Feedback, Questions, & Ideas] [answered]
I'm getting a "There are no accounts registered with Xcode. Add your developer account to Xcode" error when signing an iOS app. The development certificate and provisioning profile are in place, as described [here](https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development). But as far as I know, you can't add an account to Xcode programmatically, so how can we workaround this error?

**Comment by samuel-ma** [comment]
@apetkov-so 
Your slightly mistaken about something 
You can actually add an account to xcode
Navigate to “Xcode—->Preferences—->Accounts.” Hit the '+' icon below left to add your Apple ID

**Reply by apetkov-so** [reply]
This is running in an Actions workflow... I don't have access to Xcode directly.

**Reply by samuel-ma** [reply]
@apketkov-so
 which framework are you using to create your IOS app?

**Reply by apetkov-so** [reply]
What do you mean by "create"? I'm running `xcodebuild archive -allowProvisioningUpdates ...` in a workflow file. It fails because the automatic signing requires an Apple ID, which I don't know how to provide programmatically.

**Comment by apetkov-so** [comment, marked as answer]
The solution was to authenticate with keys rather than adding an account.

```
xcrun xcodebuild -exportArchive \
	...
	-allowProvisioningUpdates \
	-authenticationKeyID $(APPLE_ID_KEY_ID) \
	-authenticationKeyIssuerID $(APPLE_ID_ISSUER_ID)

```

**Reply by dancosta-fed** [reply]
Hi @apetkov-so, I'm assuming you're done this on bitrise.yml, is that correct?
If so, where did you add those lines?

ps.: if it wasn't on bitrise, where would I be able to access this code?

Thank you!

> The solution was to authenticate with keys rather than adding an account.
> 
> ```
> xcrun xcodebuild -exportArchive \
> 	...
> 	-allowProvisioningUpdates \
> 	-authenticationKeyID $(APPLE_ID_KEY_ID) \
> 	-authenticationKeyIssuerID $(APPLE_ID_ISSUER_ID)
> ```

**Reply by apetkov-so** [reply]
I'm not using bitrise, it's just GitHub Actions workflow. Something like:

**.github/workflows/build.yaml:**
```
name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build iOS
        shell: bash
        run: |
          xcrun xcodebuild ...
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp.ipa
          path: ${{ github.workspace }}/MyApp.ipa
          if-no-files-found: error
```

The `Build iOS` step will build an .ipa, and the `Save artifact` step will make it available for download (from the workflow run).
