### DISCUSSION TITLE
step dependent on another job

### DISCUSSION THREAD

**Discussion by cyberhck** [community/community#29327] [Actions]
Just a feature request it might not even be possible, but let's add this here for the sake of having a discussion to see if this helps or not.
Consider the following build.yaml workflow file:
```yaml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: docker-compose up -d
      - run: make build
  dockerize:
    name: dockerize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make docker_build_and_push
  release:
    name: semantic-release
    runs-on: ubuntu-latest
    needs: [dockerize, build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cycjimmy/semantic-release-action@v2
```

The only reason `release` needs to wait on `dockerize` and `build` is so that we don't release broken builds for example.

It'd be nice to be able to move the dependency from an entire job to a step. That way, I can do everything I need to do in a Job in parallel, and wait for the final step.

I've considered writing some actions to do the waiting as well, not sure if that's the approach I should be taking.

Basically, I'd remove `release.needs` and place it in the last like for uses semantic release action. That step would need docker and build, it'd wait till the other 2 are done.

An action to do that and calling the API every 5 seconds would also work in theory. But having event based is more optimal I'm guessing.

What do you guys think? Are you guys waiting for the entire job to do your last job, but the last job is a little big?
