### DISCUSSION TITLE
Github Action job unable to find artifact uploaded from previous job

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#29373] [Actions] [answered]
```
[...continuation from a job]

      - name: save result to file
        uses: actions/upload-artifact@v3
        with:
          path: /tmp/comments_timestamps.txt 

  view-results:
    needs: [the-job-above]
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'

    steps:

    - name: download file with results
      uses: actions/download-artifact@v3
      with:
        name: /tmp/comments_timestamps.txt
```

error:

```
Run actions/download-artifact@v3
Starting download for /tmp/comments_timestamps.txt
Error: Unable to find any artifacts for the associated workflow
```

WHY?

**Comment by airtower-luna** [comment]
You don't set the `name` input here, so the name [defaults to `artifact`](https://github.com/actions/upload-artifact/blob/3cea5372237819ed00197afe530f5a7ea3e805c8/action.yml#L7):

```yaml
        uses: actions/upload-artifact@v3
        with:
          path: /tmp/comments_timestamps.txt
```

So when you later try to download an artifact with the name `/tmp/comments_timestamps.txt` it doesn't exist.

**Comment by pantelis-karamolegkos** [comment]
Here is the **MODIFIED** full flow

```
env:
  RESULTS_ARTIFACT_PATH: "/tmp/comments_timestamps.txt"
  RESULTS_ARTIFACT_NAME: "results"

job-1

   steps:

      - name: something
        shell: bash
        run: |
           echo $COMMENT_TS >> ${{ env.RESULTS_ARTIFACT_PATH }}
        
      - name: save result to file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RESULTS_ARTIFACT_NAME }}
          path:  ${{ env.RESULTS_ARTIFACT_PATH }}

   job-2:
   needs: [job-1]
   
   steps:

    - name: download file with results
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.RESULTS_ARTIFACT_NAME }}

    - name: echo the results
      shell: bash
      run: cat ${{ env.RESULTS_ARTIFACT_PATH }}
```

**ERROR**

```
Run cat /tmp/comments_timestamps.txt
cat: /tmp/comments_timestamps.txt: No such file or directory
Error: Process completed with exit code 1.
```
