### DISCUSSION TITLE
GitHub Actions step executed while it shouldn't, based on a conditional

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#29429] [Actions] [answered]
I have the following steps' sequence in a GitHub Actions job (first one is used more or less for debugging purposes

```yaml
env:
  FAIL_OUTCOME: 'fail'


      - name: debug
        shell: bash
        run: |
          echo "evaluation-1 result is ${{ steps.evaluation_1.outputs.evaluation-1-outcome }}
          echo "evaluation-2 result is ${{ steps.evaluation_2.outputs.evaluation-2-outcome }}
          echo $FAIL_OUTCOME

      - name: send slack failure
        if: ${{ steps.evaluation_1.outputs.evaluation-1-outcome }} == $FAIL_OUTCOME || ${{ steps.evaluation_2.outputs.evaluation-2-outcome }} == $FAIL_OUTCOME
        uses: rtCamp/action-slack-notify@v2
        env:
           ...


      - name: send slack success
        if: ${{ steps.evaluation_1.outputs.evaluation-1-outcome }} != $FAIL_OUTCOME && ${{ steps.evaluation_2.outputs.evaluation-2-outcome}} != $FAIL_OUTCOME
        uses: rtCamp/action-slack-notify@v2
        env:
          ...

``` 

Here is the outcome of the debug action:

```
  echo "evaluation-1 result is 
  echo "evaluation-2 result is fail
```

where it seems that first outcome is not set.

However, what puzzles me is that success action is also executed, i.e. 

```
${{ steps.evaluation_1.outputs.evaluation-1-outcome }} != $FAIL_OUTCOME && ${{ steps.evaluation_2.outputs.evaluation-2-outcome}} != $FAIL_OUTCOME
``` 

becomes true. How is it possible?

To provide for more context, the outputs' assignment in previous steps are as follows:

```
echo "::set-output name=evaluation-2-outcome::$FAIL_OUTCOME"
```

  [1]: https://i.stack.imgur.com/2W18p.png
