### DISCUSSION TITLE
Same code different results / list index out of range

### DISCUSSION THREAD

**Discussion by sensahin** [community/community#29498] [Actions]
Hello,

I have a Python code that produce a json file. When i run it on my local computer it produces total of 39 item in json file. However when i run it with Github Actions it only produce 15 items and throw "list index out of range" error.

Any idea why this happens?

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: execute mycode.py script
        run: python mycode.py
```
