### DISCUSSION TITLE
How to implement a Dockerfile.myfile

### DISCUSSION THREAD

**Discussion by toptaljj** [community/community#29551] [Actions] [answered]
Our organization has a somewhat mature docker-compose environment that has multiple Dockerfiles, basically one for Mysql (the main Dockerfile) and then one for Postgres (Dockerfile.postgres) and one for Redshift (Dockerfile.redshift).

We have a workaround for mimicking the postgres container as one of the gha `jobs.<jobid>.services`; however, the redshift container must have a package installed into the official (postgres) docker image.  I have tried a variety of things to get there, and i'll leave the most recent attempt here.  In short, if we have our own Dockerfile (different than that of the main job, but rather, one that is used for a service), how can we leverage that in our workflow?

```
jobs:
   changes:
     runs-on: ubuntu-latest
     outputs:
       gha: ${{ steps.filter.outputs.gha }}

   justdoit:
     runs-on: ubuntu-latest
     services:
       postgres:
         image: postgres:11-alpine
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
       redshift:
         dockerfile: Dockerfile.redshift
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
```

When using `image` instead of `dockerfile` the workflow runs; however, it doesn't seem that `steps` with `run` in them can be added to a service (and i assume the only way to `apt-get install X` is with `steps.run`).
