### DISCUSSION TITLE
My action for auto-merging dependencies was merged, despite a check failing.

### DISCUSSION THREAD

**Discussion by da-mask** [community/community#29600] [Actions] [answered]
What am I missing from my action workflow, to prevent it being merged when tests fail?
```
name: Dependabot auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
As you can see below, one check failed, but it was still merged.
![image](https://user-images.githubusercontent.com/1960334/184769916-b537cd81-7ec8-426b-8d05-f2fce33082bd.png)
