### DISCUSSION TITLE
Type of `github.event.inputs.<name>` of boolean inputs in `workflow_dispatch` event

### DISCUSSION THREAD

**Discussion by rhysd** [community/community#29796] [Actions] [answered]
Hi, I'm author of [actionlint](https://github.com/rhysd/actionlint) and I got [an issue](https://github.com/rhysd/actionlint/issues/181) which I suspect a bug of GitHub Actions. So I'd like to clarify this behavior is intended or not.

Let's say we have the reusable workflow:

```yaml
name: _reusable

on:
  workflow_call:
    inputs:
      is-valid:
        required: true
        description: username to show
        type: boolean

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: called is-valid
        run: echo "called is-valid. ${{ inputs.is-valid }}"
```

and a regular workflow:

```yaml
name: actionlint issue

on:
  workflow_dispatch:
    inputs:
      is-valid:
        required: true
        description: "is-valid: true or false"
        type: boolean

jobs:
  issue:
    uses: ./.github/workflows/_reusable.yaml
    with:
      is-valid: ${{ github.event.inputs.is-valid }}
```

This causes an error on running them on GitHub:

```
The template is not valid. .github/workflows/test.yml (Line: 15, Col: 17): Unexpected type of value 'false', expected type: Boolean.
```

`github.event.inputs.is-valid` is a string but `is-valid` input of `_reusable` workflow expects boolean input.

The `workflow_dispatch`'s `is-valid` input is declared as `type: boolean`, but actually `github.event.inputs.is-valid` is a string `'false'`, not a boolean `false`. Is this intended behavior? Or is it a bug of GitHub Actions and should it be `false` boolean value?

If it is not a bug, is type of `github.event.inputs.<name>` always a string?

Currently converting the value to boolean with `fromJson` is a workaround for this.

```
is-valid: ${{ fromJson(github.event.inputs.is-valid) }}
```

**Comment by ChristopherHX** [comment, marked as answer]
_I only found some semi official statements of some GitHub employees._

> is type of `github.event.inputs.<name>` always a string?

Yes, booleans are always strings in that context.

GitHub fixed this with unified inputs by providing the `inputs` context to `workflow_dispatch`
You can now do the following in GitHub Actions, boolean type is only respected for the `inputs` context in both reusable workflow and workflow_dispatch
```yaml
is-valid: ${{ inputs.is-valid }}
```

References / Further reading:
- Unified Inputs and boolean type
  - https://github.com/github/feedback/discussions/9092#discussioncomment-2453678)
  - https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/
- https://github.com/actions/runner/issues/1483#issuecomment-1091025877
- Merged Inputs, you can access `workflow_dispatch` inputs in reusable workflows via `inputs` if these are not declared by the reusable workflow
  - https://github.com/actions/runner/issues/1976#issuecomment-1172940227

_I'm the author of https://github.com/ChristopherHX/runner.server an GitHub Actions Emulator, with reusable workflow support so I collected some information about internal working of GitHub Actions_

**Reply by rhysd** [reply]
Thank you for the clarification. I'll improve actionlint with the clarified behavior.

**Comment by ckingbailey** [comment]
@rhysd this is the first time I've heard of actionlint, and I just want to say thank you. This is the validator that GH Workflows has been needing for four (almost five?) years. I will be using it frequently.

**Comment by andrea-cassioli-maersk** [comment]
I am still facing a similar issue:

```
on:
  workflow_dispatch:
    inputs:
      forceDeployment:
        description: 'Whether a successful build shall be deployed regardless of which branch us'
        required: false
        type: boolean
        default: false

jobs:
  fooOutput:
    runs-on: ubuntu-latest
    name: FOO
    steps:
      - run: |
          echo "Force deployment: ${{ inputs.forceDeployment }}"
```

when the workflow runs, it prints
```
echo "Force deployment: "
```

it seems the input is unset, even tough its default to `false`...any thoghts?
