### DISCUSSION TITLE
Only allow one GitHub Action job to execute at a time (await)

### DISCUSSION THREAD

**Discussion by ChrisAcrobat** [community/community#29829] [Actions] [answered]
I have 4 jobs, let's call them `A1`, `A2`, `B1` and `B2`, with the following condition:

1. `A1` and `B1` can execute in parallel.
1. `A2` (with input from `A1`) and `B2` (with input from `B1`) can execute in what ever order (preferably first come first served), but not at the same time.

I tried using a fifth pseudo job which I called `A2-await`, which had YAML:
```YAML
A2-await:
  runs-on: ubuntu-latest
  if: ${{ always() }}
  needs: A1
  steps:
    - name: None
      run: echo
```
And then I added `needs: A2-await` on `B2`.
This solution worked when everything worked as it should, but when I tried adding a forced exception to `A1`, `B2` was not able to execute, when though `A2-await` executed successfully.

Any suggestion on how to make my condition work? I have looked into [Sibz/await-status-action](https://github.com/marketplace/actions/await-status-action), but I did not understand it.
