### DISCUSSION TITLE
Reusable workflows: Specify environment in the caller

### DISCUSSION THREAD

**Discussion by nkuba** [community/community#29827] [Actions] [answered]
I'd like to define a reusable workflow that can be called automatically or with manual approval. I've been using `environment` for that. Unfortunately, the schema doesn't let me define the `environment` property in the caller job. 

Is there a way to call the same reusable workflow in two different manners: automatically and with approval?

Example (fails schema validation):
```yaml
jobs:
  call-workflow-automatically:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      network: testnet
  call-workflow-with-approval:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    environment: production
    with:
      network: mainnet
```

**Comment by chrispat** [comment, marked as answer]
You can pass the environment name as an input to the reusable workflow.

**Reply by nkuba** [reply]
Thanks for the tip!

I create an environment named `protected` and defined the reusable workflow like this:

```yaml
on:
  workflow_call:
    inputs:
      requireApproval:
        description: True if the job requires a manual approval before execution.
        required: false
        default: false
        type: boolean
jobs:
  publish:
    # Use a fake ternary expression as a workaround for the issue
    # https://github.com/actions/runner/issues/409.
    environment: ${{ inputs.requireApproval && 'protected' || '' }}
```
