### DISCUSSION TITLE
npm fails with the self-hosted runner (MODULE_NOT_FOUND)

### DISCUSSION THREAD

**Discussion by infomiho** [community/community#29939] [Actions]
I'm using `semantic-release` to release new package versions. It worked ~17 days ago just fine. 

- This only fails when used in the self-hosted runner on Mac Mini M1. 🔴 
  - Current runner version: ‘2.295.0’
- I've tried to run the same thing with Github hosted runner - it works ✅ 
- Reading through the error and `@semantic-release/npm` source code, the command that fails is `npm version`

More details:
```
Error: Error: Command failed with exit code 1: npm version 3.4.4 --userconfig /private/var/folders/18/6_t1mlmj5gnb6d3d100f2hc80000gn/T/67efa56206f83e9d5fea8a1c441bf1eb/.npmrc --no-git-tag-version --allow-same-version
```

```
Error: Cannot find module '../lib/cli.js'
Require stack:
- /Users/bildur/Development/Company/runner/externals.2.295.0/node16/bin/npm
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/bildur/Development/Company/runner/externals.2.295.0/node16/bin/npm:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/bildur/Development/Company/runner/externals.2.295.0/node16/bin/npm'
  ]
}
```

Action source code (minimal reproduction):
```yaml
name: Publish

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      GH_PUBLISH_TOKEN:
        required: true

jobs:
  build:
    runs-on: office-machine
    outputs:
      new_release_published: ${{ steps.semantic_release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic_release.outputs.new_release_version }}
    steps:
    - uses: actions/checkout@v1
    - name: Semantic Release
      id: semantic_release
      uses: cycjimmy/semantic-release-action@v3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
