### DISCUSSION TITLE
Extensively Slow Build Process

### DISCUSSION THREAD

**Discussion by sritMishra** [community/community#30217] [Actions]
Hey there , i have an action to build a NEXT js app and deploy to vercel . But the Build process is taking so long (close to an hour) while it takes max 15min if i deploy directly inside Vercel or run in my local .Below is my BUILD command : 

```
build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ./
          mode: dev

      - name: Some other action
        run: |
          echo "Variable 1: ${{ env.SANITY_PROJECT_ID }}"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
```

Please help me out solve this issue as it's pretty urgent for me . Thanks !
