### DISCUSSION TITLE
403 Forbidden trying to push to ghcr.io from action

### DISCUSSION THREAD

**Discussion by jordemort** [community/community#30300] [Actions]
I'm trying to add a workflow to publish a container for wireproxy in https://github.com/octeep/wireproxy/pull/45 and getting a "403 Forbidden" from ghcr.io when I try to push the container.

I am logging into ghcr.io using the GITHUB_TOKEN:

```
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

When I tested this workflow in a PR against my own personal fork of wireproxy, it worked fine and pushed a container:

- https://github.com/jordemort/wireproxy/pull/1
- https://github.com/jordemort/wireproxy/actions/workflows/container.yml
- https://github.com/jordemort/wireproxy/pkgs/container/wireproxy

I did not have to make any adjustments to my repository or account settings; it just worked. 

I have seen discussions that say you need to push an initial container manually, and then adjust the permissions on the package, but I did not do this on my personal fork. There was no initial container, until the action successfully pushed the first one.

I have seen other discussions that say that this won't work at all in a Pull Request, but that seems to be untrue because it worked just fine in a pull request in my personal fork.

We can't figure out how to make it work in the upstream repository, though. The same workflow over there always gets a "403 Forbidden" when it tries to push.

Things we have tried, none of which seems to have done us any good:

- Repository owner checked all their repo settings
- Repository owner tried re-running the job under their account
- We tried adding `packages: write` to the permissions, first at the job level and then at the top level.

What are we missing?
