### DISCUSSION TITLE
Limit secrets to certain steps

### DISCUSSION THREAD

**Discussion by raphw** [community/community#30363] [Actions] [answered]
I would like to limit the availablility of secrets to certain steps of my GitHub actions. This would allow me to, for example, only make them available in the release step which cannot be triggered by a pull request per today's setup. Similarly to token permissions, I would prefer the "common steps" to be as sandboxed as only possible.

Is there an option for that or a plan to support this?

**Comment by airtower-luna** [comment]
What do you mean by "limit"? In general, secrets are only available to steps your workflow explicitly gives them to. Well, with the exception of `github.token`.

**Reply by raphw** [reply]
I would think of something like: *secrets: false* such that they would not be resolved if requested. This would make it easier to detect a bad PR if aomeone tried to extract them.

**Comment by ChristopherHX** [comment, marked as answer]
Today GitHub sends all available secrets for a job to the runner, even those not referenced by your workflow. Without changing GitHub Action settings `on: pull_request` jobs have no access to any secret on the runner and `github.token` is readonly for Pull Requests from forks.

On job level it is possible to drop all secrets, before the runners executes untrusted code.
If you use `on: pull_request_target` or other PR trigger, you can use [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) to drop all secrets for any jobs in the reusable workflow.
Also make shure to drop the github.token permissions, because they might allow write access to the repo.
```yaml
on: pull_request_target
jobs:
  sandbox:
    uses: ./.github/workflows/sandbox.yml # move low privileged jobs into this file, 
    permissions:
      contents: read # Drop also the github.token writeable permission, you can also disable reading the repo by using `none`
```

_It is always somehow possible to extract secrets from the memory of the runner, once the job has gained access to these secrets_
