### DISCUSSION TITLE
local actions in reusable workflow

### DISCUSSION THREAD

**Discussion by naresh-gn** [community/community#30443] [Actions] [answered]
I have a repo `common-ci` which has reusable workflow (workflow_call) a.k.a `called` and bunch of custom actions, some of them just composite actions and some are nodejs action.
When I use `caller` within the same repo as `called`  everything works but if my `caller` is from other repo then custom actions are not found.

common-ci (`.github/workflow/common-ci.yaml`)

```
on: workflow_call

jobs:
  init:
    - uses: actions/checkoutv3
    - uses: ./.github/workflow/action/init # <- pointing to action.yaml that refers js file
  test:
    - uses: actions/checkoutv3
    - uses: ./.github/workflow/action/test # <- pointing to action.yaml that has composite steps
  build:
    - uses: actions/checkoutv3
    - uses: ./.github/workflow/action/build # <- pointing to action.yaml that has composite steps

```

from abother-repo

```
on: push

jobs:
  uses: my-org/common-ci/.github/workflow/common-ci.yaml
```
