### DISCUSSION TITLE
GITHUB_TOKEN for packages

### DISCUSSION THREAD

**Discussion by samitkumarpatel-work** [community/community#30464] [Actions] [answered]
Is there a way to customise GITHUB_TOKEN to call package rest api with github-script action to fetch version details for org level packages ?

I tried like this:

```yaml
.....
jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    stages:
     - name: Find Latest Image Version
        id: image-version
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pkgVersion = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
              package_type: 'container',
              package_name: '${{ github.event.repository.name }}',
              org: '${{ github.repository_owner }}'
            });
            console.log(pkgVersion.data[0].metadata.container.tags)
            return pkgVersion.data[0].metadata.container.tags[0]
```
The above snippet gives me always 404 status code. But If I use a correct PAT token with all access - It just work fine
