### DISCUSSION TITLE
Github Actions env Varibales not working

### DISCUSSION THREAD

**Discussion by Tardigrade42** [community/community#30497] [Actions] [answered]
Good morning,

I tried to set env variables over a bash script and since nothing worked, I looked inside this documentation:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable

Then I kind of rebuilt the example and ran it directly on GitHub:
```YAML
name: Windows Build

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ '**.md' ]

jobs:
  build:

    runs-on: windows-latest

    env:
      Test1: test1value

    steps:
    - uses: actions/checkout@v3
    - name: Set the value
      run: |
        echo "Test2=test2value" >> $GITHUB_ENV
      env:
        Test3: test3value
    - name: Test if env is set
      run: |
        echo "Start test"
        echo "Test1 is (simple notation): $Test1"
        echo "Test1 is (bracked notation): ${{ env.Test1 }}"
        echo "Test2 is (simple notation): $Test2"
        echo "Test2 is (bracked notation): ${{ env.Test2 }}"
        echo "Test3 is (simple notation): $Test3"
        echo "Test3 is (bracked notation): ${{ env.Test3 }}"
        echo "End test"
```

The output was:
![image](https://user-images.githubusercontent.com/37712964/186092703-89054498-d55e-4ac4-b33e-564a9f316757.png)

Am I doing something wrong here or is there a bug?
