### DISCUSSION TITLE
Action button

### DISCUSSION THREAD

**Discussion by JamesBremner** [community/community#30547] [Actions] [answered]
I want to run a workflow by clicking on a button in the the README

I installed https://github-action-button.web.app/.  That appears to be successful.

Now I want to create a button.  How?  The docs are very laconic and only say "Find your repository and input the title of a button and a event_type name."

Where exactly do I input the the title and so on?

**Comment by naikrovek** [comment]
looks like the title can be whatever you want the button to say, and the event_type should be the name of the workflow you want to run.  make sure the workflow has a single-word name for simplicity, and make sure the workflow has the `workflow_dispatch` event trigger.

none of the buttons on the repo for that app are working for me, and it looks like none of them point to valid workflows anyway, so it is hard to know for sure how to use it, and this post is my current best guess.

**Reply by JamesBremner** [reply]
Thank you for responding.  My question was not about what to input, but where and how to input it.

**Comment by Simran-B** [comment]
According to the README in the repo, you are supposed to go to this page to generate the Markdown code for the button:

https://github-action-button.web.app/repos

However, even after authorizing once more, it just goes from "loading" to "error". It appears to be broken.

**Reply by JamesBremner** [reply]
Yes.  This is my experience also.

**Comment by Badisi** [comment, marked as answer]
Calling an action can be made with a simple POST request but requires authentication (ie. an access token that has access to the repository) (tutorial can be found : [here](https://medium.com/@knoldus/manual-trigger-in-github-actions-890a793fc74b)).

This is exactly what the `github-action-button` web application is doing : [ActionButton.tsx#L43](https://github.com/kouki-dan/action-button/blob/master/src/ActionButton.tsx#L43). But exposing your own token in your README could be at risk, so you authorize this web app instead and it will perform the request for you.

---

Looking at some examples in the web app repo [README](https://raw.githubusercontent.com/kouki-dan/action-button/master/README.md), we can see that an `action button` is made of 2 urls:

```md
[![Run Action](https://github-action-button.web.app/buttons/simple.svg?name=Run%20Demo%20Test&eventType=demo_test&type=simple)](https://github-action-button.web.app/repos/kouki-dan/action-button/button?name=Run%20Demo%20Test&eventType=demo_test&type=simple)
```

1. The first one is to give the look and feel of the button (ie. an svg) : but the service is broken as broken links are displayed.

2. The second one is the call action itself, but this is the first step of a two steps process. Because the action is actually performed by code in the web app. So this url will brings you to a dedicated page on the web app that actually owns the real action button. The button is not displayed properly (due to the svg service down) but clicking on it actually works for me:
<img width="634" alt="Screen Shot 2022-08-25 at 15 06 02" src="https://user-images.githubusercontent.com/674862/186674003-758f052e-ee37-4ab7-ae8d-b3ad7461be21.png">

---

### Solution

To solve the svg issue on your README, you could use your own svg (ie. simply replace the first url) or use text instead, but you will still have a button that looks broken on the dedicated web application page...

And to get an idea on how the second url should be configured, you can have a look at [demo-repository-dispatch.yml](https://github.com/kouki-dan/action-button/blob/394c3ecb2442f290f7fcd5ed256926d91ca0cb5f/.github/workflows/demo-repository-dispatch.yml) and see that you should also implement some part in the workflow yourself (ie. reacts to the custom `demo_test` event).

**Reply by Badisi** [reply]
And in case you just wanted to run a workflow manually, you could also use [workflow_dispatch](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) that will display a `Run workflow` button in the `Actions` tab of your repo 😉

**Reply by JamesBremner** [reply]
Thank you for the detailed description of what is going on here.

I don't understand the last paragraph of your answer.  "you should also implement some part in the workflow yourself"  Could you spell out in more details what I need to do?  Do you mean copy some part of the code below into my workflow?  Which part?

```
name: Demo Repository Dispatch

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run demo 1
      if: github.event.action == 'demo_test'
      run: |
        echo "the test action is dispatched"
    - name: Run demo 2
      if: github.event.action == 'demo_test2'
      run: |
        echo "the test2 action is dispatched"
```

Currently, my workflow looks like this

```
name: in2out build from button

on: repository_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -f .vscode/makefile in2out

    - uses: actions/upload-artifact@v3
      with:
         name: in2out_exec
         path: bin/in2out.exe
```

**Reply by JamesBremner** [reply]
"...  to run a workflow manually,... "

Yes, that is what I am doing now.  But the process is too tedious for my client, who wants to simply click a button in the readme.

**Reply by Badisi** [reply]
I was just saying that generating the button itself was not enough and workflows needed to be modified as well (ie. to have at least `on: repository_dispatch`).

---

Let say I have a repository named `@my-org/test` and I want to trigger a workflow from outside the repository.

To make sure my workflow can react to it, it needs at least the following :
```yml
on: repository_dispatch
```

#### If I don't use any event_type

My workflow will be triggered with : https://github-action-button.web.app/repos/@my-org/test/action-button/button?name=Test

#### If I want my workflow to be triggered on a custom `my_test` event

Url should be : https://github-action-button.web.app/repos/@my-org/test/action-button/button?name=Test&eventType=my_test

Workflow should be :
```yml
on:
  repository_dispatch:
    types: [my_test]
```
