### DISCUSSION TITLE
combine related dependabot PRs

### DISCUSSION THREAD

**Discussion by mfulton26** [community/community#30543] [Code Security]
e.g. these 2 could be combined into a single PR by dependabot; it is very unlikely I would want to merge one without the other:

- chore(deps-dev): bump @typescript-eslint/parser from 5.33.1 to 5.34.0
- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.33.1 to 5.34.0

**Comment by mistic100** [comment]
I would add "eslint" it self in the list.

---

More generally I noticed that dependabot is already capable of grouping updates when there is a package and it's corresponing "@types" https://github.com/mistic100/Photo-Sphere-Viewer/pull/848/files

To make the system improvable without hardcoding anything, there could be an option in `.github/dependabot.yml` to configure by repository which updates to combine, for example

```yml
updates:
  - package-ecosystem: npm
    combine:
      - ['eslint', '@typescript-eslint/parser', '@typescript-eslint/eslint-plugin']
      - ['stylelint', 'stylelint-config-standard-scss']
```
