### DISCUSSION TITLE
Require Contributor Agreement PRIOR TO creating Pull Requests?

### DISCUSSION THREAD

**Discussion by FrugalGuy** [community/community#30594] [Pull Requests]
Does anyone have a solution to the problem below?  
Yes, I can reject at review time, but I'd rather have that taken care of prior to reviewing the PR.

Do we know if github will support yml for pull request forms soon?  It does not appear to today.

**Problem**:
I need contributors to agree to the Contributor Agreement *prior* to creating the Pull Request, *not* afterwards.

**Potential Solution**:
If my pull_request_template could use yml and have a required checkbox, I'd be golden.

```
- type: checkboxes
    id: ca-confirmation
    attributes:
      label: I have reviewed the [Contributor Agreement](../CONTRIBUTOR_AGREEMENT.md) and agree to be bound by the terms found there.
      options:
        - label: I confirm I have reviewed and agree to the Contributor Agreement.
          required: true
```
