### DISCUSSION TITLE
How to interpolate variable within expressions?

### DISCUSSION THREAD

**Discussion by dongho-jung** [community/community#30625] [Actions] [answered]
```yaml
name: test-interpolation

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-interpolation.yml'

env:
  WORKFLOWS_PATH: .github/workflows

jobs:
  test-interpolation:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ hashFiles('.github/workflows/test-interpolation.yml') }}
      - run: echo ${{ hashFiles('${{ env.WORKFLOWS_PATH }}/test-interpolation.yml') }}
```

above one is example.
`${{ hashFiles('.github/workflows/test-interpolation.yml') }}` works as expected though, 
`${{ hashFiles('${{ env.WORKFLOWS_PATH }}/test-interpolation.yml') }}` is not working.

What should I do for getting what I expected?
