### DISCUSSION TITLE
Open links in new pages from issue templates

### DISCUSSION THREAD

**Discussion by lukaseder** [community/community#30647] [Projects and Issues]
I'm playing around with the new beta for issue templates:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

This is a great initiative, so thanks already! One issue I have is when I place links in a `description:` of an `input` or `textarea`. The links will open in the same tab as the issue, possibly leading to users losing their form data! Using `<a href="..." target="_blank">...</a>` doesn't work either, and I couldn't get "kramdown" to work the way it seems to be supported in Github Pages: 
https://stackoverflow.com/a/71373125/521799

Seems like an important addition, I think? In fact, rather than letting users do this explicitly, why not open *all* external links in new tabs in some situations?

For the record, this is the issue template I'm creating (links in "Steps to reproduce the problem"):
https://github.com/jOOQ/jOOQ/issues/new?assignees=&labels=T%3A+Defect&template=bug_report.yaml

**Comment by ensko** [comment]
I just lost a detailed bug report in this way and I'm shocked and appalled that this has been open and ignored for four years.

> Seems like an important addition, I think?

Indeed it would seem so! Especially because the draft saving is rather flaky it seems. In Firefox, I

- started an issue
- navigated away by accident
- closed the tab, thinking I would go back to the issue tab
- navigated back to issue creation

... and everything was gone. If I navigate back/open github again in the same tab instead, my draft is still there.

The various annoyances in Github's products are really starting to add up. I'm also a Github Classroom user, and the quality is stagnant at best – it definitely feels slowly deteriorating instead. And while it's just anecdotal, I have _never_ seen a response from Github on these forums either. It feels like shouting into a void; I could understand a lot of _unanswered_ posts if they were _addressed_ in the product, but that is not happening either.

**Comment by blaze0089** [comment]
---

Hey, so unfortunately `target="_blank"` gets stripped by GitHub's HTML sanitizer in issue templates — it's a deliberate security decision on their end so there's no direct way to force links to open in new tabs from within the template itself.

That said there are a couple of things you can do to protect your users from losing their form data:

The simplest workaround is putting important reference links in the `placeholder` field of your inputs instead of the `description`. Placeholder text isn't clickable so users naturally copy-paste it rather than clicking, which keeps them on the page:

```yaml
- type: textarea
  attributes:
    label: Steps to reproduce
    placeholder: |
      See reproduction guide at: https://your-docs-link.com
      (copy this link and open in a new tab)
```

Another option is adding a `checkboxes` element at the top of your template for important pre-reading links. Users have to actively interact with it and it mentally signals "read this first before filling out the form" rather than clicking mid-form:

```yaml
- type: checkboxes
  attributes:
    label: Before submitting
    options:
      - label: I have read the [reproduction guide](https://your-docs-link.com)
        required: true
```

As a general tip for users — middle-click or Ctrl+Click on any link opens it in a new tab and preserves the form. Worth mentioning that in your contributing docs if you have them.

For the draft issue, it's worth raising this directly at https://github.com/orgs/community/discussions because feature requests there do get picked up, especially ones with real use cases like this one.

---
