### DISCUSSION TITLE
Workflow canceled when using concurrency and a child job with a reusable workflow

### DISCUSSION THREAD

**Discussion by Badisi** [community/community#30708] [Actions] [answered]
I'm using the following 2 GitHub actions workflows (can be seen on this  [Code Reproduction repository](https://github.com/Badisi/issue-reusable-workflow/tree/main/.github/workflows)):

1. `ci_tests.yml` (obviously used to run some tests)

```yml
name: Run tests
on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci_tests:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
```

2. `ci_build.yml` (used to build something but requires the tests to pass before doing so)

```yml
name: Build app
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci_tests:
    uses: ./.github/workflows/ci_tests.yml
  ci_build:
    needs: ci_tests
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
```

Both workflow uses their own concurrency group so that anytime a workflow of the same type is triggered, the previous one that is still running could be cancelled.

### Issue

- If I'm running the workflow (1) ([Tests#9](https://github.com/Badisi/issue-reusable-workflow/actions/runs/2964430134)) and then the workflow (2) ([Build#14](https://github.com/Badisi/issue-reusable-workflow/actions/runs/2964430662)), (2) will get immediately canceled with the following error:

   > Canceling since a higher priority waiting request for ' Build app-refs/heads/main' exists

   and (1) won't even be canceled.

- If I'm running only the workflow (2) ([Build#15](https://github.com/Badisi/issue-reusable-workflow/actions/runs/2964455645)), it will get immediately canceled the same way

Obviously there are no other workflow (2) running in each case, so the issue is kinda misleading.

Is it an issue with gh's actions or am I missing something ?

Thanks!

**Comment by ViacheslavKudinov** [comment]
Hi,
I see you are using reusable workflow and use concurrency in calling workflow and in called at the same time.
I think it is not supported on called workflow.
If to read very carefully this statement:

> When you call a reusable workflow, you can only use the following keywords in the job containing the call
> ...
> [jobs.<job_id>.concurrency](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency)

Word "**ONLY**" probably explains why it doesn't work for you.
Source is there https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow

**Comment by ViacheslavKudinov** [comment]
I could think it has to generate some error instead of working in some really weird way you face due to it.

**Comment by Badisi** [comment]
@ViacheslavKudinov, thanks for trying to help me out!

To me, "only" simply means that when using a reusable workflow you can't use other properties like "steps", etc.

---

Anyhow, I tried using `concurrency` also in the reusable job and now **Run tests** ([Tests#10](https://github.com/Badisi/issue-reusable-workflow/actions/runs/2964474801)) is properly canceled when **Build app** ([Build#16](https://github.com/Badisi/issue-reusable-workflow/actions/runs/2964475964)) is starting after it.

```yml
name: Build app
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci_tests:
    concurrency:
      group: Run tests-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/ci_tests.yml
  ci_build:
    needs: ci_tests
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
```

But I'm still facing the issue where it says that **Build app** is also canceled due to another identical request already existing.
> Canceling since a higher priority waiting request for ' Build app-refs/heads/main' exists

---

This really doesn't make sense to me and seems more like a bug on GitHub's actions side.

**Comment by Badisi** [comment, marked as answer]
To anyone interested in this issue, here is the detailed explanation and how to fix it :

#### Explanation

> The main issue was that a called workflow uses its caller's name when using `${{ github.workflow }}`

```yml
name: Build app
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # <-- 1. will be reserved as "Build app-..."
  cancel-in-progress: true
jobs:
  ci_tests:
    uses: ./.github/workflows/ci_tests.yml # <-- 3. will be reserved as "Build app-..."
    concurrency:
      group: Run tests-${{ github.ref }} # <-- 2. will be reserved as "Run tests-..."
      cancel-in-progress: true
  ci_build:
    needs: ci_tests
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
```

1. `Build app` workflow starts and gets reserved as **"Build app-..."**
2. `ci_tests` job starts and gets reserved as **"Run tests-..."**
3. `Run tests` workflow starts (as it is used by `ci_tests` job) and gets reserved as **"Build app-..."**
     -> because a called workflow uses its caller's name
     => the whole workflow is canceled because "**Build app-...**" is already running

#### Fix

> Thanks to the help of the support at GitHub, the solution in such a case is to simply name the `Run tests` workflow with something different than `${{ github.workflow }}`

```yml
name: Run tests
on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: tests-${{ github.ref }} # <-- 1. will be reserved as "tests-..."
  cancel-in-progress: true
jobs:
  ci_tests:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
```

```yml
name: Build app
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # <-- 2. will be reserved as "Build app-..."
  cancel-in-progress: true
jobs:
  ci_tests:
    uses: ./.github/workflows/ci_tests.yml # <-- 3. will be reserved as "tests-..."
  ci_build:
    needs: ci_tests
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
```

1. `Run tests` workflow starts and gets reserved as **"tests-..."**
1. `Build app` workflow starts and gets reserved as **"Build app-..."**
2. `Build app#ci_tests` job starts
3. `Run tests` workflow starts (as it is used by `Build app#ci_tests` job) and gets reserved as **"tests-..."**
     -> **"tests-..."** in `1.` is canceled as it is already running
     => `Build app` keeps running and finishes
