### DISCUSSION TITLE
error NU1101: Unable to find package (from GitHub Package)

### DISCUSSION THREAD

**Discussion by elendil-software** [community/community#30746] [Packages] [answered]
Hi,

I need to restore NuGet package from my Github Package repository.

To do so, I added this step in my (reusable) workflow :

```yml
- name: Add GitHub NuGet Source
   run: |
     dotnet nuget add source --username $OWNER --password $GITHUB_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$OWNER/index.json"
     dotnet nuget list source
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       OWNER: ${{ github.repository_owner }}
```

which seems to work as the log output : 

> Package source with Name: github added successfully.
> Registered Sources:
>   1.  nuget.org [Enabled]
>       https://api.nuget.org/v3/index.json
>   2.  github [Enabled]
>       https://nuget.pkg.github.com/elendil-software/index.json

But when I call `dotnet restore` in the next step I get the error : 

> error NU1101: Unable to find package xxxxxxxxxx. No packages exist with this id in source(s): github, nuget.org

I checked that the package mentioned in the error exists and it is the case.

Additional information : 

- workflow is in a private repository
- the GitHub Package source has the same Owner than the repository

Regards,

Julien
