### DISCUSSION TITLE
Dynamic discovery/matrix run of actions

### DISCUSSION THREAD

**Discussion by smokedlinq** [community/community#30789] [Actions] [answered]
I have a library of internal actions that I want to run integration tests against. Rather than having a workflow per integration test, I'd like a job per and I'd prefer dynamic discovery of the tests and using those in some form of matrix job such as below.

```yaml
  discover-integration-tests:
    runs-on: ubuntu-latest
    outputs:
      actions: ${{ steps.discover.outputs.actions }}
    steps:
    - uses: actions/checkout@v3
    - id: discover
      run: |
        $Actions = "./$((Get-ChildItem -Path ./.github/actions/integration-tests -File -Recurse -Filter action.yml).Directory.FullName.Substring($PWD.Path.Length+1).Replace('\','/'))"
        Write-Host "::set-output name=actions::$($Actions | ConvertTo-Json -AsArray -Compress)"
      shell: pwsh

  integration-tests:
    needs: discover-integration-tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        action: ${{ fromJSON(needs.discover-integration-tests.outputs.actions) }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ${{ matrix.action }}
```

The workflow errors with: `the `uses' attribute must be a path, a Docker image, or owner/repo@ref`

Assuming this isn't supported and not a feature we'd get anytime soon, has anyone else tried creating some form of automated integration tests that are easy to add without having to remember to add them to the ci workflow?

**Comment by jsoref** [comment, marked as answer]
you can write an action file to disk (`path/to/action-directory/action.yml`) dynamically and use:

```yaml
  uses: ./path/to/action-directory/
```

**Reply by jsoref** [reply]
```yaml
  discover-integration-tests:
    runs-on: ubuntu-latest
    outputs:
      actions: ${{ steps.discover.outputs.actions }}
    steps:
    - uses: actions/checkout@v3
    - id: discover
      run: |
        $Actions = "./$((Get-ChildItem -Path ./.github/actions/integration-tests -File -Recurse -Filter action.yml).Directory.FullName.Substring($PWD.Path.Length+1).Replace('\','/'))"
        Write-Host "::set-output name=actions::$($Actions | ConvertTo-Json -AsArray -Compress)"
      shell: pwsh

  integration-tests:
    needs: discover-integration-tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        action: ${{ fromJSON(needs.discover-integration-tests.outputs.actions) }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./trampoline
      with:
         action: ${{ matrix.action }}
```

`./trampoline/action.yml`:
```yml
name: dynamic dispatch
run-name: ${{inputs.action}}
inputs:
  action:
    description: Action to run
    required: true
runs:
  using: composite
  steps:
  - name: checkout
    uses: actions/checkout@v3
  - name: set up action
    shell: bash
    run: mv "action-${{ inputs.action}}" "action"
  - name: run action
    uses: ./action
```
