### DISCUSSION TITLE
How to get labels from current PR?

### DISCUSSION THREAD

**Discussion by thatrandomperson5** [community/community#30923] [Actions] [answered]
I have a workflow that has a job that adds labels, then I have other jobs that check to make sure the labels exist using: `if: github.event.label.name == 'register' `. The problem is it always returns false and does not go. I think this might be because it is based of the event instead of the current pr, how do I fix?

**Comment by airtower-luna** [comment, marked as answer]
That's correct, the event payload has the state of when the event happened. There's no "fix" for the event because it's correct.

If you want the current labels of the PR you can [use the Pulls API to get them](https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request). For example this should print the label names one per line:
```
run: |
  gh api --jq '.labels.[].name' /repos/{owner}/{repo}/pulls/${{ github.event.number }}
```

**Reply by thatrandomperson5** [reply]
So how would I only run a job if the current or has a label? How would I put that in an if statement?

**Reply by airtower-luna** [reply]
[Set an output](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) with the labels (or maybe simpler, one that says if a specific label is set) in one job, and then check that output in the `if` condition for the other jobs.

It'd probably make sense to set the output in the same job that adds labels, after all the other jobs have to wait for it either way.

**Reply by thatrandomperson5** [reply]
Ok, let me look at the action I’m using and check

**Reply by thatrandomperson5** [reply]
I’m still confused, how would I get the api result into the output, then check that in an if? (I’m new to actions)

**Reply by thatrandomperson5** [reply]
Something like this? @airtower-luna 
```yaml

    - id: transfer
      run: |
       echo "::set-output name=labels::$(gh api --jq '.labels.[].name' /repos/{owner}/{repo}/pulls/${{ github.event.number }})\n"
      env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
