### DISCUSSION TITLE
Which GITHUB_TOKEN permissions to create a Github Release?

### DISCUSSION THREAD

**Discussion by ringods** [community/community#30927] [Actions] [answered]
I want to create a Github Release within my repository using [GoReleaser](https://goreleaser.com/). Using the new permissions mechanism [introduced in April 2021](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/), I want to prevent setting a Personal Access Token (PAT). 

The documented permissions don't list Github Releases separately:

```
permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  issues: read|write|none
  packages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none
```

so I configured write access to `packages` ([sources](https://github.com/pulumiverse/pulumi-time/blob/0a58a0101e124813b3d827d2b8d1fcb6d54cade9/.github/workflows/release.yml#L9-L11)):

```
permissions:
  contents: read
  packages: write
```

But GoReleasser complains it doesn't have enough permissions:

https://github.com/pulumiverse/pulumi-time/runs/8037885446?check_suite_focus=true#step:6:69

Does any of these entries cover writing to Github Releases of my repository?
