### DISCUSSION TITLE
Are re-usable workflows supported from private repos within the same Org now?

### DISCUSSION THREAD

**Discussion by oxcug** [community/community#31095] [Actions]
Are re-usable workflows supported from private repos within the same Org now? Despite a blog post saying you could (maybe it's only for enterprise customers?) I have not had success attempting this with a pattern like:

```
jobs:
    build:
        uses: my-org/build-tool/.github/workflows/setup.yml@main
    test:
        needs: build
        strategy:
...
```

getting errors like:

> error parsing called workflow "my-org/build-tool/.github/workflows/setup.yml@main": workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.

Is the only solution still to create a PAT or deploy token?
