### DISCUSSION TITLE
github.run_id not changing

### DISCUSSION THREAD

**Discussion by EdieLemoine** [community/community#31226] [Actions] [answered]
Hi guys,

I've recently incorporated `github.run_id` in my workflows, but now I'm not seeing its value change on new runs.

https://github.com/myparcelnl/developer/runs/8067764461?check_suite_focus=true

In this run I expected the run_id to be `8067764461`, but it's `2924915124`, as you can see below:

![Screenshot 2022-08-29 at 14 01 01](https://user-images.githubusercontent.com/3886637/187196564-c18cbe44-09c5-4cb9-8fe8-9c13fdcf68ea.png)
 
This ID is from an older run of the same workflow: https://github.com/myparcelnl/developer/actions/runs/2924915124

My cache step:
```yml
    - name: 'Handle cache'
      id: cache-all
      uses: actions/cache@v3
      with:
        path: src/.vuepress/dist
        key: ${{ runner.os }}-build-all-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-build-all
```
Full action: https://github.com/myparcelnl/developer/blob/e886e9cf3ac13c37fff0af14e95db38f5776fee9/.github/workflows/build/action.yml#L7-L14

Which is used in this workflow: https://github.com/myparcelnl/developer/blob/e886e9cf3ac13c37fff0af14e95db38f5776fee9/.github/workflows/deploy.yml

Am I missing something? Thanks in advance!
