### DISCUSSION TITLE
Git Hub WOrkflow status - send mail

### DISCUSSION THREAD

**Discussion by saivamsibodavulaTR** [community/community#31302] [Actions]
Hello team, 
I do have a requirement, where at the end of a github workflow in github actions, my github action should send a E-mail to team with the status of the workflow(it could be pass/fail/ any other). 

I have used the folowing script.
to check the working, i have use email id and password.now the scenario is, i should be able to make it up with a generalized user , github.actions@users.noreply.github.com and it should be given a password / PAT. or else its failing with the below error. 
**Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8**

```
 - name: send email
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: github.actions@users.noreply.github.com
          password: 
          from: github.actions@users.noreply.github.com
          to: <team members maid ids>
          subject:  job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
```

can some one help me with the user and some token assignment to it.
--->can we use this scenario, as in the sense of giving a noreply user and giving it a PAT/ password and using it to send mails.
---> or shall i dedicate a user to this scenario,

Please advice me,
Your respose would be much appreciated.

THanks in advance,..
