### DISCUSSION TITLE
Repo path is duplicated when setting working_directory in a step (bug perhaps?)

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#31375] [Actions] [answered]
I have the following step in a GitHub Actions' job

```
    steps:
      - name: set elasticsearch version
        shell: bash
        working-directory: "./foobar"
        run: | 
          ......
```

The job fails as follows:

```
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/my-repo/my-repo/./foobar'. No such file or directory
```

Why is the `my-repo` path being appended twice?
