### DISCUSSION TITLE
Sentry release action Docker container not using Tailscale DNS

### DISCUSSION THREAD

**Discussion by neilzuk** [community/community#31475] [Actions]
We're trying to use the [Sentry GitHub Action](https://github.com/getsentry/action-release) with the [Tailscale action](https://github.com/marketplace/actions/connect-tailscale) in order to connect to a internal server from GitHub hosted runners.

The runner has access to the internal server as expected once Tailscale has connected and works fine (split DNS).

The problem appears to be where an action is a Docker container e.g. the Sentry one which doesn't seem to get the updated DNS and continues to use the external DNS records.

We have tried restarting the docker service prior to calling the Sentry action but it doesn't make a difference. 

Has anybody had a similar issue with DNS inside actions using Docker?

Extract of the action yml file:

```
steps:
    - uses: actions/checkout@v3
    - name: Connect to Tailscale
      uses: tailscale/github-action@main
      with:
        version: 1.28.0
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        SENTRY_URL: ${{ secrets.SENTRY_URL }}
      with:
          environment: production
          version: ${{ inputs.name }}
 ```
