### DISCUSSION TITLE
Complex strategy matrix groupings in GitHub Actions

### DISCUSSION THREAD

**Discussion by saharl-neosec** [community/community#31504] [Actions]
I'm using GitHub Actions strategy matrix in some projects to build and deploy my code
I tried making 2 matrices that each has 2 variables, with 2 option per variables
For simplicity I'll use letters and numbers in my example
```
    strategy:
      matrix:
        include:
          - letter: [a, b]
            number: [1, 2]
          - letter: [c, d]
            number: [3, 4]
```

I expected for each item in the include section to act like a matrix and create all possible parings:
`[a,1], [a,2], [b,1], [b,2], [c,3], [c,4], [d,3], [d,4]`

Instead got 2 jobs looking like this:
`[[a,b],[1,2]], [[c,d], [3,4]]`

Does anyone know if there is a way to create the complex (3D) matrix I am looking for?

**Comment by Simran-B** [comment]
You can either specify a matrix for which a job is run for every combination of the array elements:

```yaml
    strategy:
      matrix:
        letter: [a, b, c, d]
        number: [1, 2, 3, 4]
```

Pairings: `[a,1], [a,2], [a,3], [a,4], [b,1], [b,2], [b,3], [b,4], [c,1], [c,2], [c,3], [c,4], [d,1], [d,2], [d,3], [d,4]`

Or you can specify the parameters for each job explicitly with `include`. To get your desired runs, you would need to define:

```yaml
    strategy:
      matrix:
        include:
          - letter: a
            number: 1
          - letter: a
            number: 2
          - letter: b
            number: 1
          - letter: b
            number: 2
          - letter: c
            number: 3
          - letter: c
            number: 4
          - letter: d
            number: 3
          - letter: d
            number: 4
```

You can also use the first approach and `exclude` undesired combinations:

```yaml
    strategy:
      matrix:
        letter: [a, b, c, d]
        number: [1, 2, 3, 4]
        exclude:
          - letter: a
            number: 3
          - letter: a
            number: 4
          - letter: b
            number: 3
          - letter: b
            number: 4
          - letter: c
            number: 1
          - letter: c
            number: 2
          - letter: d
            number: 1
          - letter: d
            number: 2
```

Lastly, you can dynamically create a matrix, e.g. using a shell script. You would write a step to generate the desired combinations using `include` in JSON format and set it as output, then set `matrix: ${{ fromJSON(...) }}` to use it:
https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object
