### DISCUSSION TITLE
[Feature Request] Reusable workflow - inherit environment

### DISCUSSION THREAD

**Discussion by dkirrane** [community/community#31518] [Actions]
I have a number of environments dev, stage, prod each with different secrets.

I'd like to set the environment so it inherits the correct secrets for all jobs in the reusable workflow (including any nested reusable workflows)?

currently setting the environment at the workflow level is not supported.

```
name: Caller workflow
on:
  workflow_dispatch:

# Not supported - Unexpected value 'environment'
# environment:
#   name: dev

jobs:

  Run:
    uses: ./.github/workflows/called-workflow-1.yml
    secrets: inherit
    
```
