### DISCUSSION TITLE
Workflow starts 3 times on release

### DISCUSSION THREAD

**Discussion by salos1982** [community/community#31576] [Actions] [answered]
I have a release workflow that should be triggered on release.
But when I created pre-release this workflow started 3 times.
<img width="702" alt="image" src="https://user-images.githubusercontent.com/2404581/187851470-3bebb787-c235-4471-a859-4d3885a393d1.png">

I've created a new release with a new tag and with the checkbox pre-release

There is a trigger part of my workflow file.
```
name: CI prod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
```

**Comment by Simran-B** [comment, marked as answer]
Have a look a the documentation for the `release` event:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

The significant bits are:

> By default, **all** activity types trigger workflows that run on this event. You can limit your workflow runs to specific activity types using the `types` keyword.

> Activity types
> - `published`
> - `unpublished`
> - `created`
> - `edited`
> - `deleted`
> - `prereleased`
> - `released`

The three workflow runs are likely caused by the activity types `created`, `prereleased`, and `published`. You may want to restrict the types it triggers on, e.g.

```yaml
on:
  release:
    types:
      - published
```
