### DISCUSSION TITLE
Environment secrets readable in a `schedule` event workflow?

### DISCUSSION THREAD

**Discussion by moritzschmitz-oviva** [community/community#31614] [New to GitHub] [answered]
I have a protected branch with required status checks and one required approver. The branch is also part of an environment which adds the secret `REPO_SSH_WRITE`.

My understanding is that the ssh deploy key 'user' however is treated like a repository admin when having write access.

Pushing to the branch however fails.

From https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys:
```
Deploy keys with write access can perform the same actions as an organization member with admin access, or a collaborator on a personal repository.
```

Run log:
```
remote: error: GH006: Protected branch update failed for refs/heads/main-nightly.        
remote: error: Required status check "version-validator" is expected. At least 1 approving review is required by reviewers with write access. You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.        
To https://github.com/xxx/database-changes
 ! [remote rejected]   main-nightly -> main-nightly (protected branch hook declined)
error: failed to push some refs to 'https://github.com/xxx/database-changes'
```

`workflow.yml`:
```
name: Open nightly pull request

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  update-branch:
    name: Update branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.REPO_SSH_WRITE }}
          fetch-depth: 0
          ref: main-nightly

      - name: Update branch
        run: |
          git config user.email "github-actions@oviva.internal"
          git config user.name "Github Actions"
          git merge origin/main -m "Automatic nightly merge"
          git push
```

EDIT: Add info about the environment.
