### DISCUSSION TITLE
Most efficient way of making inputs available to shell steps

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#31635] [Actions] [answered]
From what I understand, the `inputs` context (working on a `workflow_dispatch` workflow) is not available to neither `shell` or the step's `env` context as well, since the following 2 attempts fail

```yaml
    - name: copy the templates directory to destination folder
      env:
        CHART_PATH: ${{ inputs.CHART_PATH }}
      shell: bash
      run: | 
        cp -r ${{ env.TEMPLATES_DIR }} ${{ env.CHART_PATH }}
```

```yaml

    - name: copy the templates directory to destination folder
      shell: bash
      run: | 
        cp -r ${{ env.TEMPLATES_DIR }} ${{ inputs.CHART_PATH }}
```

I have a `workflow_dispatch` with several inputs (> 10)

What is the most appropriate / efficient way of making them available to shell steps?
