### DISCUSSION TITLE
Actions to "azure/webapps-deploy@v2" fails by build

### DISCUSSION THREAD

**Discussion by mendykrauss** [community/community#31631] [Actions]
I automatically created a build file from Azure for GitHub Actions, but it's failing by the build:

```
ERROR: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount2938294427/Dockerfile: no such file or directory
Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount2938294427/Dockerfile: no such file or directory
```

I know that this is a popular error over the past few years, but I couldn't find a good answer for it.

Thanks!

**Comment by airtower-luna** [comment]
The error message unfortunately doesn't tell much without the code. Best link the workflow log, or if the repository is private quote the relevant parts of workflow file and log, so people can actually take a look!

**Reply by mendykrauss** [reply]
Thanks for checking in @airtower-luna. Here is the actions file:

```
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - idtechsolutions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3e34bc9284984853859f24435cf18dc3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b4221511b2834307ac4a9fbc4ed2b322 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3e34bc9284984853859f24435cf18dc3 }}/mcr.microsoft.com/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'idtechsolutions'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_58bb99fae1744085a320dee007f17391 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3e34bc9284984853859f24435cf18dc3 }}/mcr.microsoft.com/appsvc/wordpress-alpine-php:${{ github.sha }}'
```

**Comment by airtower-luna** [comment]
This is the only place the "missing" Dockerfile can come from, as far as I can see:
```yaml
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3e34bc9284984853859f24435cf18dc3 }}/mcr.microsoft.com/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile
```

From looking at the [`docker/build-push-action` docs](https://github.com/docker/build-push-action) using a Dockerfile at the root of your repository is the default anyway. So things to try, starting from the simple:

* Check if such a `Dockerfile` actually exists in your repository, under that exact name.
* Remove the `file ` parameter, to rule out there's some weird interaction (even if it should be the same as the default.
* Update the `docker/build-push-action`. You're using `v2`, when `v3.1.1` (or `v3`) is the latest release-
