### DISCUSSION TITLE
Simple shell actions fails to copy directory

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#31640] [Actions]
I have the following GitHub actions step

```yaml
    - name: copy dir
      shell: bash
      run: | 
        cp -r ${{ env.TEMPLATES_DIR }} ${{ inputs.CHART_PATH }}
```

Here is the log output on the runner

```
cp -r charts/helmcharts/subcharts/__charttmpl__/ charts/helmcharts/subcharts

  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TEMPLATES_DIR: charts/helmcharts/subcharts/__charttmpl__/
cp: 'charts/helmcharts/subcharts/__charttmpl__/' and 'charts/helmcharts/subcharts/__charttmpl__' are the same file
```

Why does this fail, given that the **exact same command** works locally?

```
bash-5.1$ cp -r charts/helmcharts/subcharts/__charttmpl__/ charts/helmcharts/subcharts
bash-5.1$ 
```

Here is the input (I am using its default value)

```
      CHART_PATH:
        description: The folder in which the new chart will be placed
        type: string
        required: true
        default: charts/helmcharts/subcharts
```
