### DISCUSSION TITLE
download_url within registry_package event is empty

### DISCUSSION THREAD

**Discussion by FabioGimmillaro** [community/community#31717] [Apps, API and Webhooks]
Hi

we are currently facing an issue that the download_url of our published package is empty. This worked before so we checked the API Docs but there seem to be no breaking changes.

This is how we read the download_url:
```yml
on:
  registry_package:
    types: [published]
    
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: list package metadata
      run: |
        echo '${{ github.event.registry_package.package_version.version }}'
        echo '${{ github.event.registry_package.package_version.package_files[0].name }}'
        echo '${{ github.event.registry_package.package_version.package_files[0].download_url }}'
```

The version and name of the package are correct. 
I also couldn't find an issue with the published artifacts. They are in the registry and can be downloaded with npm.
    
The last succesfull job was Fri, 19 Aug 2022 07:23:09 GMT
The first failing job was Fri, 19 Aug 2022 11:27:43 GMT

I hope these informations help to fix my issue. :)

Thanks in advance for your answers.
