### DISCUSSION TITLE
How to run pytest in docker-compose with GitHub Actions?

### DISCUSSION THREAD

**Discussion by luyangliuable** [community/community#31737] [Actions]
I want to automate a ci/cd pipeline by running  unittests inside my python code. However i got this problem and it exits with code zero before pytest is run.

This is my yaml file for github actions

```yaml
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "milestone2" ]
  pull_request:
    branches: [ "milestone2" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.9"
    - name: cd into flask_backend directory
      run: |
        cd server
    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd server
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: UnitTest with pytest
      run: |
        docker-compose up -d
        docker-compose exec flask_backend pip3 install pytest
        docker-compose exec flask_backend pytest

```

My docker-compose file

```yaml 
services:
  flask_backend:
    build:
      context: ./server/
    image: bxer.flask_backend
    container_name: bxer.flask_backend
    ports:
      - 5005:5000
    command: python3 manage.py run -p 5000
    volumes:
      - .:/usr/src/app/
    environment:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - mongodb

  mongodb:
    tty: true
    image: mongo:5.0
    restart: always
    container_name: bxer.mongodb
    ports:
      - 27017:27017
    volumes:
      - .:/data/mongodb
   

  redis:
    ports:
      - 6379:6379
    restart: always
    container_name: bxer.redis
    image: redis:6-alpine

  localstack:
    image: localstack/localstack:0.14.3
    restart: always
    container_name: bxer.localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

```

I get the error
the input device is not a TTY
Error: Process completed with exit code 1.
