### DISCUSSION TITLE
File `PROFILE.yaml` for social links on my GitHub profile?

### DISCUSSION THREAD

**Discussion by ghost** [community/community#31860] [Other Feature Feedback, Questions, & Ideas] [answered]
Hi everyone! 

I would like to have more options to social-media in my profile. Currently, GitHub has a file called ```FUNDING.yml``` which allows donation links to appear in any repository.  If you want more information check these two links [link 1](https://github.com/sponsors) [link 2](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository).

I would like to have a file called ```PROFILE.yml```that allows social links not to appear on the profile. Both the ```FUNDING.yml``` and ```PROFILE.yml``` file are yaml based. 

This allows me to have a series of GitHub side links without having to worry about whether or not GitHub will support the side links that I need the user accessing my profile to know. Also, it would be a solution so that I don't do a README.md

#### source-code 1: ```FUNDING.yml```
```yaml
# These are supported funding model platforms
patreon: sample
open_collective: sample
ko_fi: sample
tidelift: sample
```

#### source-code 2: ```PROFILE.yml```
```yaml
# All my profile
facebook: sample
twitter: sample
youtube: sample
instagram: sample
tiktok: sample
```

#### image 1: source-code 1
![image](https://user-images.githubusercontent.com/111701513/188279197-9e36574a-e35e-4143-9bdb-90d890fdc79e.png)

#### image 2: source-code 2
![image](https://user-images.githubusercontent.com/111701513/188278915-aa0cbb81-0eb7-4e76-bde9-ae9aef925d4c.png)
