### DISCUSSION TITLE
GUI autograder overwriting default classroom.yml

### DISCUSSION THREAD

**Discussion by kulnaman** [community/community#32083] [GitHub Education]
Hello All,
Right now, I have written a custom classroom.yml file that sets up the built environment and an autograding.json file that follows the template of tests created through GUI. My issue is as soon as I add an auto-grading test through GUI, it overwrites the classroom.yml, and my built environment is not created. Is there any way where we can manually add GUI test cases through test cases written in autograding.json?

**Comment by densuke-st** [comment]
Same issue happens. How to inject custom actions?
I want to install KinD(K8s inDocker). 
I appended .github/workflows/classroom.yml on template repos

```
...
runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helm/kind-action@v1.3.0 # added
      - uses: education/autograding@v1
```

But after students used this assignment and pushed to student's repos, overwritten by original `classroom.yml`.

![image](https://user-images.githubusercontent.com/16230466/191117011-21eec336-23b5-4dd1-b5a7-bde090de8862.png)
