### DISCUSSION TITLE
I would like a simple way to get the HTML URL for the current job

### DISCUSSION THREAD

**Discussion by eric** [community/community#32169] [Actions]
I wanted to be able to provide a link in Slack to view the logs of the currently running job and the only way I found to do it was this:

``` yaml
      - uses: actions/github-script@v6
        id: job-url
        with:
          script: |
              const { data } = await github.rest.actions.listJobsForWorkflowRunAttempt({
                ...context.repo,
                run_id: context.runId,
                attempt_number: process.env.GITHUB_RUN_ATTEMPT,
              });

              return data.jobs[0].html_url
          result-encoding: string
      - name: Print Log URL
        run: |
          echo "Log URL: ${{ steps.job-url.outputs.result }}"
```

Is there a better way to get the URL?

The problem with this approach is that it doesn't work if a workflow has more than one job. There's no way from the action to identify which job it is apart of without hard-coding the job name in the code.

**Comment by averagebit** [comment]


**Reply by eric** [reply]
Is there a way to make a feature request?

**Reply by dtinth** [reply]
> Is there a way to make a feature request?

This discussion is already a feature request. As of writing, it needs about 70 more upvotes to be on the [top 10 unanswered feedback for GitHub Actions](https://github.com/community/community/discussions/categories/actions-and-packages?discussions_q=category%3A%22Actions+and+Packages%22+is%3Aunanswered+sort%3Atop).

**Reply by eric** [reply]
Is there a way to get GitHub PMs to see it?

**Reply by sblask** [reply]
Also see https://github.com/community/community/discussions/8945 for the problems with the job ID approach.

It would be great to have something like `jobs.<job_id>.html_url` and `jobs.<job_id>.id` (obviously the naming is bad)  possibly even `steps.<step_id>.html_url`

**Comment by qoomon** [comment]
Feel free to use my action to access current `job_log_url` (among other context information)

Example Workflow
```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    environment: playground
    permissions:
      actions:     read  # required for qoomon/actions--context action
      deployments: read  # required for qoomon/actions--context action
      contents: read
    steps:
      - uses: qoomon/actions--context@v1
        id: context

      - run: |
          echo "Current Environment: ${{ steps.context.outputs.environment }}"
          echo "Job Logs: ${{ steps.context.outputs.job_log_url }}"
```
