### DISCUSSION TITLE
buildx write_package or create_package errors with ghcr.io using GITHUB_TOKEN

### DISCUSSION THREAD

**Discussion by tobybellwood** [community/community#32184] [Packages] [answered]
EDIT: there are a couple of grumbles on the interwebs now, seemingly not just me - https://downdetector.com.au/status/github/

Getting the following error suddenly (this all worked yesterday)

```
#41 [auth] xxx/ooo:pull,push token for ghcr.io
#41 DONE 0.0s

#39 exporting to image
#39 pushing layers 0.4s done
#39 ERROR: unexpected status: 403 Forbidden
------
 > exporting to image:
------
ERROR: failed to solve: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: unexpected status: 403 Forbidden
```
adding debug logs to buildx shows the issue
>   time="2022-09-07T03:54:40Z" level=debug msg="unexpected response" body="{\"errors\":[{\"code\":\"DENIED\",\"message\":\"permission_denied: write_package\"}]}\n" digest="sha256:8b6a8f742917d3a4b32cd5eac2044e12eefbd97e746780b3447278e010a06b16" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip resp="&{403 Forbidden 403 HTTP/1.1 1 1 map[Content-Length:[76] Content-Type:[application/json] Date:[Wed, 07 Sep 2022 03:54:40 GMT] Docker-Distribution-Api-Version:[registry/2.0] X-Github-Request-Id:[0680:3029:53996:119F6D:63181600]] {0xc0006ebf40} 76 [] false false map[] 0xc000a3df00 0xc0007dd340}" size=135

But - I've followed all the correct configurations - is there a current issue with ghcr that may cause this?
```
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
```
I can reliably replicate this error across repos, users and packages

**Comment by nagimov** [comment]
Not sure if related - I'm getting a similar buildx error using actions. Everything worked fine last month using the same workflow yaml
```
------
 > pushing ghcr.io/nagimov/agendav-docker:2.5.0 with docker:
------
ERROR: denied: permission_denied: write_package
Error: buildx failed with: ERROR: denied: permission_denied: write_package
```
Job setup shows correct read/write access assigned
```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  Packages: write
```
Login to ghcr via
```
      - name: login to ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

Full build log [here](https://github.com/nagimov/agendav-docker/runs/8220964219), action workflow [here](https://github.com/nagimov/agendav-docker/blob/master/.github/workflows/deploy.yml).
