### DISCUSSION TITLE
Bug: Idle scheduled workflow disabling also disables non-scheduled triggers

### DISCUSSION THREAD

**Discussion by l0b0** [community/community#32197] [Actions]
**Describe the bug**

The "feature" which disables scheduled workflows after 60 days of inactivity also disables non-scheduled triggers of *the same workflow.*

Also, scheduled workflows should be re-enabled when there is activity, such as creating a new PR on the project.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a `.github/workflows/test.yml` workflow with the following triggers:

   ```
   on:
     pull_request:
       types: [opened, reopened, synchronize]
     schedule:
       - cron: '0 12 * * 0'
   ```
3. Wait for 60 days so the test workflow is disabled
4. Create pull request in the repo

**Expected behaviour**

The test workflow should run.

**Actual behaviour**

The workflow does not run, and there is no indication of why. I only managed to figure out why by seeing some kind of new link in the `/actions` page, clicking on it, seeing a message about the scheduled workflow being disabled, and re-enabling it. (I can't get a screenshot without waiting another 60 days for the workflow to be disabled again.)
