### DISCUSSION TITLE
GitHub REST API call does not trigger `pull_request` events

### DISCUSSION THREAD

**Discussion by moritzschmitz-oviva** [community/community#32213] [New to GitHub] [answered]
I have a workflow like this:
```
name: Validate SQL syntax, SQL files location and file names

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
```

And a step in another workflow which uses the `actions/github-script@v6` to open a pull request:
```
await github.rest.pulls.create({
  owner: context.repo.owner,
  repo: context.repo.repo,
  head: 'main-nightly',
  base: 'main',
  title: `${dateAsString}: Merge nightly changes`,
  body: 'Automatic pull request to merge nightly changes from main-nightly into main'
});
```

There are branch protection rules in place which are waiting for some actions from the workflow above, but it seems the workflow events are never triggered and the workflow never runs:
<img width="847" alt="Bildschirmfoto 2022-09-07 um 12 24 13" src="https://user-images.githubusercontent.com/109514955/188855773-b90e4816-2db4-4d31-b22f-745c3782c555.png">

Just tried a `curl` on the PR and it returns no events:
```
curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/oviva-ag/database-changes/issues/1122/events" | jq

[]
```
