### DISCUSSION TITLE
How to make environment protection rule allow on pull request branch?

### DISCUSSION THREAD

**Discussion by jtamyrc** [community/community#32225] [Actions]
I set up a environment called `staging` which allow `dev` branch as the deployment branch.

I also set up github action for some testing like below. 
```yml
on:
  pull_request:
    branches:
      - dev
jobs:
  testing:
    environment: staging
```

The issue is if I create a feature branch and make a pull request to dev, I will received a error like 
```
Branch "feat/add-button" is not allowed to deploy to staging due to environment protection rules.
```
I can think of a workaround is to create a `pre-staging` environment and allow feature branches.

Also, I don't want to add feature branches to my `staging` environment.

However, is there any way I can allow a pull request branch from the environment protection as mentioned above?
