### DISCUSSION TITLE
Get matrix values from an env variable (or an external source such as a file)

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#32284] [Actions] [answered]
I want to set up a GitHub action workflow that uses a `matrix` strategy.

I would to be able to set the input values of such a `matrix` either from an `env` variable or (ideally) from a file.

```
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
```

Is it possible for the workflow to read `version: [10, 12, 14]` from another source?
