### DISCUSSION TITLE
Empty echo of needs context

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#32305] [Actions] [answered]
```
$ cat my_repos.json
[
    "git@github.com:pkaramol/myrepo1.git",
    "git@github.com:pkaramol/my-repo2.git"
]
```

```
jobs:

  retrieve-changed-common:

    outputs:
      matrix: ${{ steps.set-repositories-matrix.outputs.repositories }}

...
...

      - name: set the repos as output
        id: set-repositories-matrix
        shell: bash
        run: |
          REPOSITORIES=$(cat my_repos.json | jq . -Rs)
          echo $REPOSITORIES
          # the echo above does print the expected string
          echo "::set-output name=repositories::$REPOSITORIES"


  do-something-else:
  
    needs: [retrieve-changed-common]
    runs-on: ubuntu-latest

      - name: print
        shell: bash
        run: echo ${{ needs.retrieve-changed-common.outputs.repositories }}
```

The last echo above is empty.

Why?

**Comment by airtower-luna** [comment, marked as answer]
Because the name of the job output you request in `needs` isn't the one defined in the first job. `needs.retrieve-changed-common.outputs.matrix` should work.

As a side note, if you want to process the output with `fromJSON()` turning your input file into a JSON string object isn't going to be very useful. `jq -c . my_repos.json` to get a compact (single line) form of the JSON data would probably work much better. :slightly_smiling_face:

**Comment by pantelis-karamolegkos** [comment]
@airtower-luna Thanks. I have accepted your answer. However I tried your suggestion on the matrix output and my next matrix job has this error

```
Error when evaluating 'strategy' for job 'do-stuff'. .github/workflows/sync_common_workflows.yaml (Line: 65, Col: 21): Unexpected type of value 'git@github.com:pkaramol/myrepo1.git', expected type: Sequence.
```

I am setting the output as you suggested

```yaml
 REPOSITORIES=$(jq -c . my_repos.json )
 echo $REPOSITORIES
 echo "::set-output name=repositories::$REPOSITORIES"
```

and then trying to use it as input matrix to the next job

```yaml
do-stuff:
    name: do stuff
    needs: [retrieve-changed-common]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        repository: ${{ fromJSON(needs.retrieve-changed-common.outputs.repositories) }}
```
