### DISCUSSION TITLE
Workflow permissions for editing release

### DISCUSSION THREAD

**Discussion by paulober** [community/community#32349] [Actions] [answered]
Hi,

i have a problem with my publish.yml workflow:
```yaml
- name: Add artifact to release
        #gh api --method POST -H "Accept: application/vnd.github+json" /repos/paulober/myrepo/releases/$RELEASE_ID/assets 
        run: gh release upload $RELEASE_TAG_NAME myreleasedfile.exe
        env:
          #RELEASE_ID: ${{ github.event.release.id }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I want to use the `permissions` setting for the token but i don't know which permission is required for `gh release upload` ?
