### DISCUSSION TITLE
Alternative for needing a `uses` within a `step` that contains a `run`?

### DISCUSSION THREAD

**Discussion by paul-reilly** [community/community#32436] [Actions] [answered]
I have this test setup which builds on two platforms and create a release. Unfortunately I have discovered that I cannot insert an additional `uses` for only one platform of the matrix within a step. Error is `a step cannot have both the `uses` and `run` keys`.

I just need to have an additional `uses` for the windows portion of the action, to load either msys2 or Developer Tools. What would be the best way to do this while preserving the logic to create releases from tags?

Thanks in advance.
```yml

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: build
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [branch@master]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Build and install
        if: matrix.os == 'windows-latest'
        run: |
          new-item main
          mkdir install-windows
          cp main ./install-windows
          gci -path ./install-windows -recurse |
            compress-archive -destinationpath ./gruben-windows-amd64.zip

      - name: Build and install
        if: matrix.os == 'ubuntu-latest'
        run: |
          make
          mkdir install-linux
          cp main ./install-linux
          zip -r gruben-linux-amd64.zip install-linux/*

      - name: Upload windows release assets
        uses: actions/upload-release-asset@v1
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: gruben-windows-amd64.zip
          asset_path: ./gruben-windows-amd64.zip
          asset_content_type: application/octet-stream

      - name: Upload linux release assets
        uses: actions/upload-release-asset@v1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: gruben-linux-amd64.zip
          asset_path: ./gruben-linux-amd64.zip
          asset_content_type: application/octet-stream
```
