### DISCUSSION TITLE
Linting files in diff and adding a commit to the target branch

### DISCUSSION THREAD

**Discussion by Siddharth-Ashri** [community/community#32431] [Actions]
My team and  have forks of our private Repo. I am trying to implement a workflow that uses PHPCBF and PHPCS to lint the files in the PR. I am able to target my fork of the repo since I have installed an action secret for my repo. How would go about implementing a workflow so that i don't have to create separate PATs for each member in our team as I don't think this is a scalable system. 
This is what my current workflow looks like. 

````
on: ['pull_request']

jobs:
  lint-php-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        php-versions: ['8.0']
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: intl, mbstring, core, tokenizer, xml, xmlreader, xmlwriter
        key: cache-v1

    - name: Cache extensions
      uses: actions/cache@v2
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Setup PHP
      uses: shivammathur/setup-php@2.11.0
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer, phpcs, phpcbf

    - id: files
      name: Get changed file names
      uses: Ana06/get-changed-files@v1.2
      with:
        filter: "*.php"

    - name: Run code sniffer
      continue-on-error: true
      run: phpcs -v --standard=PSR12 --report=summary --extensions=php --ignore=vendor/*,resources/* --runtime-set ignore_errors_on_exit 1  --runtime-set ignore_warnings_on_exit 1 ${{steps.files.outputs.all}}

    - name: Run code beautifier
      continue-on-error: true
      run: phpcbf --standard=PSR12 --report=summary --extensions=php --ignore=vendor/*,resources/* --runtime-set ignore_errors_on_exit 1  --runtime-set ignore_warnings_on_exit 1 ${{steps.files.outputs.all}}

    - id: auto-commit-action
      name: Git Auto Commit linted files
      uses: EndBug/add-and-commit@v9.0.1
      with:
        author_name: ****
        message: Commiting Linted File
        committer_name: PHP Linter Bot

    - name: "Run if changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: echo "Changes!"

    - name: "Run if no changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: echo "No Changes!"
```
