### DISCUSSION TITLE
When $GITHUB_STEP_SUMMARY is added multiple times in a composite action, only the last step seems to be reflected

### DISCUSSION THREAD

**Discussion by suzuki-shunsuke** [community/community#32566] [Actions] [answered]
This is an issue of [GITHUB_STEP_SUMMARY](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary).

When `$GITHUB_STEP_SUMMARY` is added multiple times in a composite action,
only the last step seems to be reflected.

https://github.com/suzuki-shunsuke/test-github-action/actions/runs/3028352492

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/13323303/189488346-5daba242-4ba5-4df5-b9c7-af9080056e59.png">

https://github.com/suzuki-shunsuke/test-github-action/blob/699af0126acef631209b988191102133ed96fa94/.github/workflows/test-action.yaml#L11

```yaml
      - uses: ./.github/actions/step-summary-action
```

https://github.com/suzuki-shunsuke/test-github-action/blob/699af0126acef631209b988191102133ed96fa94/.github/actions/step-summary-action/action.yaml#L3-L9

```yaml
name: step summary
description: step summary
runs:
  using: composite
  steps:
    - shell: bash
      run: echo foo >> "$GITHUB_STEP_SUMMARY"
    - shell: bash
      run: echo bar >> "$GITHUB_STEP_SUMMARY"
```

On the other hand, when `$GITHUB_STEP_SUMMARY` is added multiple times in a job without composite action, all steps are reflected properly.

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/13323303/189488543-5a7c0674-1d94-4f5a-824a-6899422e6d34.png">

https://github.com/suzuki-shunsuke/test-github-action/blob/699af0126acef631209b988191102133ed96fa94/.github/workflows/test.yaml#L9-L14

```yaml
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: echo foo >> "$GITHUB_STEP_SUMMARY"
      - shell: bash
        run: echo bar >> "$GITHUB_STEP_SUMMARY"
```
