### DISCUSSION TITLE
Dynamic Output Variable Names?

### DISCUSSION THREAD

**Discussion by RichardTMiles** [community/community#32628] [Actions] [answered]
I have a very verbose yaml file that I'm wondering if I can use expression syntax to reduce. Specifically I'd like to do something like this 

```
outputs:
${{ format('privateAZASubnet-{0}', matrix.aws-region ) }}: ${{ steps.network.outputs[format('privateAZASubnet-{0}', matrix.aws-region )] }}
```
The above syntax does not work and was only a shot in the dark as I don't believe this to be a feature generally. Can anyone point me to a better solution or the correct syntax? 

```
  REGIONAL-NETWORKING:
    strategy:
      fail-fast: false
      matrix:
        aws-region: [ us-east-1, us-east-2, us-west-2, eu-central-1, ca-central-1 ] #
    runs-on: ubuntu-latest
    needs: CONSTANTS
    outputs:
      # @link https://github.com/community/community/discussions/17245
      # my consensus is that this is the only good way to do this
      # @link https://github.com/orgs/community/discussions/25634
      vpc-us-east-1: ${{ steps.network.outputs.vpc-us-east-1 }}
      vpc-us-east-2: ${{ steps.network.outputs.vpc-us-east-2 }}
      vpc-us-west-2: ${{ steps.network.outputs.vpc-us-west-2 }}
      vpc-us-eu-central-1: ${{ steps.network.outputs.vpc-us-eu-central-1 }}
      vpc-us-ca-central-1: ${{ steps.network.outputs.vpc-us-ca-central-1 }}

      privateAZASubnet-us-east-1: ${{ steps.network.outputs.privateAZASubnet-us-east-1 }}
      privateAZASubnet-us-east-2: ${{ steps.network.outputs.privateAZASubnet-us-east-2 }}
      privateAZASubnet-us-west-2: ${{ steps.network.outputs.privateAZASubnet-us-west-2 }}
      privateAZASubnet-eu-central-1: ${{ steps.network.outputs.privateAZASubnet-eu-central-1 }}
      privateAZASubnet-ca-central-1: ${{ steps.network.outputs.privateAZASubnet-ca-central-1 }}

      publicAZASubnet-us-east-1: ${{ steps.network.outputs.publicAZASubnet-us-east-1 }}
      publicAZASubnet-us-east-2: ${{ steps.network.outputs.publicAZASubnet-us-east-2 }}
      publicAZASubnet-us-west-2: ${{ steps.network.outputs.publicAZASubnet-us-west-2 }}
      publicAZASubnet-eu-central-1: ${{ steps.network.outputs.publicAZASubnet-eu-central-1 }}
      publicAZASubnet-ca-central-1: ${{ steps.network.outputs.publicAZASubnet-ca-central-1 }}

      dataAZASubnet-us-east-1: ${{ steps.network.outputs.dataAZASubnet-us-east-1 }}
      dataAZASubnet-us-east-2: ${{ steps.network.outputs.dataAZASubnet-us-east-2 }}
      dataAZASubnet-us-west-2: ${{ steps.network.outputs.dataAZASubnet-us-west-2 }}
      dataAZASubnet-eu-central-1: ${{ steps.network.outputs.dataAZASubnet-eu-central-1 }}
      dataAZASubnet-ca-central-1: ${{ steps.network.outputs.dataAZASubnet-ca-central-1 }}

      privateAZBSubnet-us-east-1: ${{ steps.network.outputs.privateAZBSubnet-us-east-1  }}
      privateAZBSubnet-us-east-2: ${{ steps.network.outputs.privateAZBSubnet-us-east-2  }}
      privateAZBSubnet-us-west-2: ${{ steps.network.outputs.privateAZBSubnet-us-west-2  }}
      privateAZBSubnet-eu-central-1: ${{ steps.network.outputs.privateAZBSubnet-eu-central-1  }}
      privateAZBSubnet-ca-central-1: ${{ steps.network.outputs.privateAZBSubnet-ca-central-1  }}

      publicAZBSubnet-us-east-1: ${{ steps.network.outputs.publicAZBSubnet-us-east-1 }}
      publicAZBSubnet-us-east-2: ${{ steps.network.outputs.publicAZBSubnet-us-east-2 }}
      publicAZBSubnet-us-west-2: ${{ steps.network.outputs.publicAZBSubnet-us-west-2 }}
      publicAZBSubnet-eu-central-1: ${{ steps.network.outputs.publicAZBSubnet-eu-central-1 }}
      publicAZBSubnet-ca-central-1: ${{ steps.network.outputs.publicAZBSubnet-ca-central-1 }}

      dataAZBSubnet-us-east-1: ${{ steps.network.outputs.dataAZBSubnet-us-east-1 }}
      dataAZBSubnet-us-east-2: ${{ steps.network.outputs.dataAZBSubnet-us-east-2 }}
      dataAZBSubnet-us-west-2: ${{ steps.network.outputs.dataAZBSubnet-us-west-2 }}
      dataAZBSubnet-eu-central-1: ${{ steps.network.outputs.dataAZBSubnet-eu-central-1 }}
      dataAZBSubnet-ca-central-1: ${{ steps.network.outputs.dataAZBSubnet-ca-central-1 }}

      privateAZCSubnet-us-east-1: ${{ steps.network.outputs.privateAZCSubnet-us-east-1 }}
      privateAZCSubnet-us-east-2: ${{ steps.network.outputs.privateAZCSubnet-us-east-2 }}
      privateAZCSubnet-us-west-2: ${{ steps.network.outputs.privateAZCSubnet-us-west-2 }}
      privateAZCSubnet-eu-central-1: ${{ steps.network.outputs.privateAZCSubnet-eu-central-1 }}
      privateAZCSubnet-ca-central-1: ${{ steps.network.outputs.privateAZCSubnet-ca-central-1 }}

      publicAZCSubnet-us-east-1: ${{ steps.network.outputs.publicAZCSubnet-us-east-1 }}
      publicAZCSubnet-us-east-2: ${{ steps.network.outputs.publicAZCSubnet-us-east-2 }}
      publicAZCSubnet-us-west-2: ${{ steps.network.outputs.publicAZCSubnet-us-west-2 }}
      publicAZCSubnet-eu-central-1: ${{ steps.network.outputs.publicAZCSubnet-eu-central-1 }}
      publicAZCSubnet-ca-central-1: ${{ steps.network.outputs.publicAZCSubnet-ca-central-1 }}

      publicSubnet-us-east-1: ${{ steps.aws.outputs.publicSubnet-us-east-1 }}
      publicSubnet-us-east-2: ${{ steps.aws.outputs.publicSubnet-us-east-2 }}
      publicSubnet-us-west-2: ${{ steps.aws.outputs.publicSubnet-us-west-2 }}
      publicSubnet-eu-central-1: ${{ steps.aws.outputs.publicSubnet-eu-central-1 }}
      publicSubnet-ca-central-1: ${{ steps.aws.outputs.publicSubnet-ca-central-1 }}

      privateSubnet-us-east-1: ${{ steps.aws.outputs.privateSubnet-us-east-1 }}
      privateSubnet-us-east-2: ${{ steps.aws.outputs.privateSubnet-us-east-2 }}
      privateSubnet-us-west-2: ${{ steps.aws.outputs.privateSubnet-us-west-2 }}
      privateSubnet-eu-central-1: ${{ steps.aws.outputs.privateSubnet-eu-central-1 }}
      privateSubnet-ca-central-1: ${{ steps.aws.outputs.privateSubnet-ca-central-1 }}

      dataSubnet-us-east-1: ${{ steps.aws.outputs.dataSubnet-us-east-1 }}
      dataSubnet-us-east-2: ${{ steps.aws.outputs.dataSubnet-us-east-2 }}
      dataSubnet-us-west-2: ${{ steps.aws.outputs.dataSubnet-us-west-2 }}
      dataSubnet-eu-central-1: ${{ steps.aws.outputs.dataSubnet-eu-central-1 }}
      dataSubnet-ca-central-1: ${{ steps.aws.outputs.dataSubnet-ca-central-1 }}

      security-us-east-1: ${{ steps.security.outputs.security-us-east-1 }}
      security-us-east-2: ${{ steps.security.outputs.security-us-east-2 }}
      security-us-west-2: ${{ steps.security.outputs.security-us-west-2 }}
      security-eu-central-1: ${{ steps.security.outputs.security-eu-central-1 }}
      security-ca-central-1: ${{ steps.security.outputs.security-ca-central-1 }}
```

**Comment by airtower-luna** [comment, marked as answer]
Write whatever data you want to transfer to a file (JSON would be an obvious choice) and transfer that instead, e.g. as an artifact. That way you have one object that can have whatever values and even structure you need.

For a small JSON object you could even create a compact (single line) encoding and transfer it as an output.

**Reply by RichardTMiles** [reply]
Just straight file io and locking? I think I'd rather type out what I have. 

Love to see better support, such as my suggestion above, in the future.

**Reply by RichardTMiles** [reply]
This ended up being the only solution I had to move forward. I think GitHub will eventually support dynamic outputs, but artifacts are the only solution for now ;'( 

 This required me to rewrite the whole workflow. If you export variables to a file correctly so that they act as a shell script, you can then import that file artifact with `source`. You can get a decent approach without naming variables for each region (matrix var).  I'll link the workflow as it stands (subject to change, but you can look through the diff)

https://github.com/MilesSystems/aws-deployment/blob/main/.github/workflows/aws.yml

**Comment by RichardTMiles** [comment]
https://github.com/actions/runner/pull/2477

```yaml 
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux', 'windows','macos']
        arch: ['x86','x64']
    outputs:
      ${{ matrix.os }}_${{ matrix.arch }}_result: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: "test=${{ matrix.os }} - ${{ matrix.arch }}" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs["linux_x86_result"] }}
 ```
 
 Support has been added!
