### DISCUSSION TITLE
Can you mark inputs as sensitive/secret in a workflow_dispatch event?

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#32668] [Actions] [answered]
Right now do I have a Deploy-preview system, where I provide a PAT to close friends (or use them myself), so that they can use the system I made.
This has many security issues (Namely that they do have a PAT, so someone could hijack the account if they want).

Since GitHub now allows workflows to trigger other workflows using `workflow_dispatch` events with the default token did I consider to move the entire deploy preview to the main repo that is used for said previews, and use the `workflow_dispatch` event to trigger it.

This has a minor problem tho, which is that everyone could trigger the event if they like, so I want to add some level of security by adding a required input field for authentication.
I would use that input to compare it to a secret in my repo to see if the run would be valid, using an if-condition.

Here's an example workflow to hopefully visualize this better:

```yaml
name: Action

on:
  workflow_dispatch:
    inputs:
      authentication:
        description: "The authentication token to actually run this workflow."
        required: true
        type: text

jobs:
  run_action:
    if: ${{ inputs.authentication }} == ${{ secrets.AUTH }} # Not sure if that is the right way.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: "echo Valid token provided!"
```
My question now is: Can I define an input as "sensitive", so that it wouldn't be displayed uncensored within the action logs?

To reiterate:
I want to create an action in my deploy-preview repository, which can be triggered remotely from other workflows in other repositories, to start a deploy preview.
To avoid spam and abuse would I like to implement some authentication, so that only actions with a valid key may trigger a run.
To keep the key safe would I like to hide it from action logs (censor it). Is this doable?
