### DISCUSSION TITLE
How to get the names of all failed jobs in a "failure notification" job.

### DISCUSSION THREAD

**Discussion by janeklb** [community/community#32688] [Actions] [answered]
We have a workflow that ends with this `notify-failure` job (which notifies us via slack if any of the previous steps fail):

```yaml
  notify-failure:
    if: failure() && github.event_name == 'push' && github.ref_name == 'main'
    needs: [xxx, yyy, zzz]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Notify on failure
        uses: .github/actions/slack-send
        with:
          channel: '#xxx'
          message: 'verify workflow failed on <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.ref_name }}> :x:'
          slack_bot_token: '${{ secrets.SLACK_BOT_TOKEN }}'
```

Is it possible to get the names of the steps that had failed in an expression? I would like to include them in the notification message (in `steps[0].with.message`)

**Comment by airtower-luna** [comment, marked as answer]
You can get that information from the [`needs` context](https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context), see `needs.<job_id>.result` there. I don't think there's a way to do the evaluation in an Actions expression, but you could add a separate step that checks the results and produces the list you want as an output.

Something like [`toJSON(needs)`](https://docs.github.com/en/actions/learn-github-actions/expressions#tojson) might be useful to give all the `needs` context data to a step in bulk, so you can process it with any JSON tool you like (e.g. `jq` or a Python script).

**Reply by janeklb** [reply]
Thank you! I'll try this out

**Reply by janeklb** [reply]
For anyone else curious / interested in doing something like this, i achieved what I wanted with
```shell
echo '${{ toJson(needs) }}' | jq -r 'to_entries | map(select(.value.result == "failure") | .key) | join(", ")'
```

**Reply by airtower-luna** [reply]
Thank you for sharing! I'd be safer though to pass the JSON as an environment variable instead of injecting it into the command. The reason is that Actions syntax (`${{ ... }}`) is replaced *as text* before the shell sees the command, so it'll break if there's s single quote anywhere in the JSON (unlikely to be an issue with `needs`, but it could be for other things).

**Reply by janeklb** [reply]
Good catch - that's a fair point, though I'm not sure how the issue would be solved by using an envar - would you mind providing an example?

**Reply by airtower-luna** [reply]
Something like this:

```yaml
- run: |
    echo "${JSON}" | jq -r 'to_entries | map(select(.value.result == "failure") | .key) | join(", ")'
  env:
    JSON: ${{ toJson(needs) }}
```

The difference is that this way Bash is aware of the variable and can treat it accordingly. :slightly_smiling_face:
