### DISCUSSION TITLE
How do I go about creating a reusable action to support Singularity containers

### DISCUSSION THREAD

**Discussion by saw235** [community/community#32713] [Actions]
For example, with docker containers, if you want to clone a repository within the docker container and run some test in it, it is as simple as 
```yaml
jobs:
  tests:
    container:
      image: my_container
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run tests
        run: invoke_unit_tests.py
```

For Singularity containers, it is not obvious to me how that could be done.
