### DISCUSSION TITLE
Actions drop env values from service containers

### DISCUSSION THREAD

**Discussion by david-proctor** [community/community#32778] [Actions]
I have a workflow that uses container services. For example, I have a Postgres server set up:

```
  my_job:
    name: run my job
    runs-on: ubuntu-latest
    container: ubuntu
    permissions:
      contents: read
      packages: read
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_db
          POSTGRES_USER: my_user
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
       ...
```

When I run the action, Postgres is detected as healthy and the job is allowed to proceed, but queries against it fail. I eventually noticed that it appears my `env:` values are being dropped from the docker command to start Postgres. From the job output:

```
  /usr/bin/docker create --name 4e2e1ea7a996460ba42079c4def59ade_postgres_ba73be --label 786a9b --network github_network_73c3f053dc704754b54f689979e3295f --network-alias postgres -p 5432:5432 --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 -e "POSTGRES_DB" -e "POSTGRES_USER" -e "POSTGRES_PASSWORD" -e GITHUB_ACTIONS=true -e CI=true postgres
```

Note that it is calling docker with a `-e` argument for each variable I set, but without any values, ie. passing `-e "POSTGRES_USER"` instead of `-e "POSTGRES_USER=my_user"`. The values that Github Action sets implicitly, `-e GITHUB_ACTIONS` and `-e CI`, do have values.

Looking at my run history, the most recent run that did not have this problem occurred on August 30, and the next commit, where this issue begins, does not touch github actions. I am seeing this in all projects where I use container services, and in every service (not just Postgres).

Does anyone know what's going on here?
