### DISCUSSION TITLE
Error response from daemon: Head .'..manifests/latest": unauthorized

### DISCUSSION THREAD

**Discussion by eric-personal** [community/community#32801] [Actions]
I keep running into an unauthorized issue after doing a build using github action directly from the docs. 
Everything builds correctly but when I go to pull the image it gives me the following error: 

**Error response from daemon: Head "https://ghcr.io/v2/orginization/project-image/manifests/latest": unauthorized** 

**Settings:** 
Organization name > Packages > Package Settings > Manage Actions access > project-image (project repository ) > write 
Organization name > Packages > Package Settings > Manage Codespaces access > Empty ( Empty because I'm not using any cloud-powered development environments.)

Anyone have any clue as to why I consistently get unauthorized. I'm not using a PAT as you see from my code below.
I'm using what the docs suggest as best practice with the automatically generated **secrets.GITHUB_TOKEN** 

Github action

```
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Container registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

This is on a main branch. I also have tried running it from a feature branch.

**Comment by Arvindh-Mojo** [comment]
Did you figure this out ? I'm running into a similar problem.

**Comment by mroy-seedbox** [comment]
Two years later and this still doesn't work...

Duplicates:
- #61470 
- #45981

**Comment by mroy-seedbox** [comment]
I found a workaround!

Pulling the image ahead of time allows it to then be used by the following steps/actions without requiring auth!

```
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker image
        run: docker pull ghcr.io/org/repo
        shell: bash
      - [ other steps can now use the image! ]
```
