### DISCUSSION TITLE
Make a status check corresponding to a failed workflow, successful

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#32929] [Actions] [answered]
I have the following workflow outline

```yaml
jobs:
  
  job1:
 
    steps:
  
    - name: step 1 of job 1
      run: exit 1

  job2:
  if: failure()
  
    steps:

    - name: step 1 of job 2
      run: echo "Hello World"
```

I know the above runs. However it marks my corresponding status check as failed (red color). Is there a way to make the action execution successful?
