### DISCUSSION TITLE
Is is possible to disable "Skip output since it may contain secret." ?

### DISCUSSION THREAD

**Discussion by fabiendupont** [community/community#32922] [Actions]
I am using a script that generates a JSON output that I want to use as my strategy matrix. So, following the documentation, I've created a workflow like this:

```yaml
on:
  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - name: Checkout current repository to get the matrix file
        uses: actions/checkout@v3
  
      - name: Generate the build matrix
        id: gen-matrix
        run: |
          echo "${PULL_SECRET}" > ${PULL_SECRET_FILE}
          echo "::set-output name=matrix::$(bash build_matrix.sh)"
          env:
            PULL_SECRET: ${{ secrets.PULL_SECRET }}
            PULL_SECRET_FILE: pull-secret
  
    build-image:
      needs: build-matrix
      runs-on: ubuntu-latest
      strategy:
        matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
        max-parallel: 4
        fail-fast: false
      steps:
        - name: Debug matrix data
          run: echo "${{matrix.versions.driver }}-${{ matrix.versions.kernel }}"
```

The `build_matrix.sh` script pulls info from container images labels from a private registry, so I pass the pull secret as a secret. And it outputs the JSON string to standard output.

The problem is that the `gen-matrix` step throws a warning "Skip output 'matrix' since it may contain secret.", which means that the `needs.build-matrix.outputs.matrix` variable is not set and `fromJson` fails to read it.

Is there a way to tell Github Actions that this output is not a secret? Or to disable this eviction for this step/job?

**Comment by kuisathaverat** [comment]
To `Skip outputs` make the reuse of workflows very limited, also the `environment` is skipped silently (but at least is documented), this behavior is not [Documented](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow) as a limitation. So you cannot use secrets in actions, and you cannot output a secret, this means you will have to write again and again the same workflow, this is a pain to maintain every time you have to change something. 

For example, we need a GITHUB_TOKEN due to limitations to the automatic generated, and we will make it on many workflows. With reusable workflows we would have to add three lines only to each workflow without them, about twenty lines:

```yaml
---
## Get a temporal GitHub Token using a GitHub App ID and a private key.
name: 'Get GitHub Personal Access Token'

on:
  workflow_call:
    outputs:
      token:
        description: "GitHub token"
        value: ${{ jobs.get-token.outputs.token }}
jobs:
  get-token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-token.outputs.token }}
    steps:
      - uses: hashicorp/vault-action@v2.4.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          method: approle
          secrets: |
            secret/path/github-app app_id | APP_ID ;
            secret/path/github-app installation_id | INSTALLATION_ID ;
            secret/path/github-app key | PRIVATE_KEY
      - name: Get PAT
        id: get-token
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
        with:
          app_id: ${{ env.APP_ID }}
          private_key: ${{ env.PRIVATE_KEY }}
          installation_id: ${{ env.INSTALLATION_ID }}
```

```yaml
name: update-tools
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-token:
    uses: owner/repo/.github/workflows/github-token.yml@main
    secrets: inherit
 process:
    runs-on: ubuntu-latest
    needs: get-token
    steps:
      - run: whatever I want to use the token
        env:
          GITHUB_TOKEN: ${{ needs.get-token.outputs.token }}
```
