### DISCUSSION TITLE
Writing to job summaries sometimes fails

### DISCUSSION THREAD

**Discussion by mike-gore-cko** [community/community#32926] [Actions] [answered]
We are running into a problem where writing to a job summary sometimes causes the build to fail with the message. It fails roughly 1 in 10 times:
```
/runner/_work/_temp/aad815d0-a5ad-48a6-b2ba-d4c3198e05fa.sh: line 1: : No such file or directory
```

This is using a workflow similar to the one below. The job is executed on our self-hosted agents. It always fails on the 1st echo statement to the GITHUB_STEP_SUMMARY.

```yml
jobs:
  calculate-version:
    name: Generate new GitHub version
    runs-on: [self-hosted, linux]
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive
      # We have an internal step in-between that generates a semantic version number
      - name: Generate version summary
        run: |
          echo '### GitVersion' >> "$GITHUB_STEP_SUMMARY"
          echo 'Version number calculated is `${{ steps.gitversion.outputs.Version }}`' >> "$GITHUB_STEP_SUMMARY"
```

I'm not sure if there's anything we can do to mitigate this or if this is an issue with Actions. Any help would be very much appriciated.
