### DISCUSSION TITLE
Issue Templates Should Allow an Option to Render Markdown

### DISCUSSION THREAD

**Discussion by jonathan-innis** [community/community#32948] [Projects and Issues]
Currently, the [documentation around YAML issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#markdown) mentions that you can create an item in the `body` of the template that is of type `markdown`. This type will render for the issue form but will not be submitted as part of the issue.

I'd like to propose that we offer an option where a user could specify that this markdown _should_ be submitted as part of the issue creation.

```yaml
- type: markdown
  id: community-note
  attributes:
    value: |
      * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
      * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
      * If you are interested in working on this issue or have submitted a pull request, please leave a comment
    render: true
```

Use Cases:
- Code of Conduct 
- Issue Etiquette and Guidance Information Embedded into the Issues
- Community Notes
