### DISCUSSION TITLE
npm ERR! 404 Not Found

### DISCUSSION THREAD

**Discussion by shinokada** [community/community#33029] [Actions]
I have the following `.github/workflows/npm-publish.yml` file.

```
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run package
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
```

This outputs the following:

```
Run npm run package
  

> release-please-example@0.0.23 package
> svelte-package && cd package && npm publish

Cannot generate a "svelte" entry point because the "." entry in "exports" is missing. Please specify one or set a "svelte" entry point yourself

src/lib -> package
Successfully built 'release-please-example' package. To publish it to npm:
  cd package
  npm publish

npm notice 
npm notice 📦  release-please-example@0.0.23
npm notice === Tarball Contents === 
npm notice 6.0kB CHANGELOG.md            
npm notice 1.2kB GitHubSource.svelte     
npm notice 602B  GitHubSource.svelte.d.ts
npm notice 1.1kB README.md               
npm notice 571B  package.json            
npm notice === Tarball Details === 
npm notice name:          release-please-example                  
npm notice version:       0.0.23                                  
npm notice filename:      release-please-example-0.0.23.tgz       
npm notice package size:  3.2 kB                                  
npm notice unpacked size: 9.5 kB                                  
npm notice shasum:        9a4d7c4e[8](https://github.com/shinokada/release-please-example/actions/runs/3052334449/jobs/4921605473#step:5:8)316aff413[9](https://github.com/shinokada/release-please-example/actions/runs/3052334449/jobs/4921605473#step:5:10)834eddef8d4e11b1ee08c
npm notice integrity:     sha5[12](https://github.com/shinokada/release-please-example/actions/runs/3052334449/jobs/4921605473#step:5:13)-iCKgveN5OEEIn[...]4mdOnRIgL8Qeg==
npm notice total files:   5                                       
npm notice 
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/release-please-example - Not found
npm ERR! 404 
npm ERR! 404  'release-please-example@0.0.23' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-09-[14](https://github.com/shinokada/release-please-example/actions/runs/3052334449/jobs/4921605473#step:5:15)T11_14_[40](https://github.com/shinokada/release-please-example/actions/runs/3052334449/jobs/4921605473#step:5:41)_178Z-debug-0.log
Error: Process completed with exit code 1.
```

The script for `npm run package` is the following:

```
// package.json
"package": "svelte-package && cd package && npm publish"
```

Even though there is https://registry.npmjs.org/release-please-example URL, it returns error 404 not found.

I already added the NPM_TOKEN secret to repo, settings, Secrets, Actions.
Why and how to solve the problem?
