### DISCUSSION TITLE
Allow workflow on deployment_status filtering for state and environment

### DISCUSSION THREAD

**Discussion by smokedlinq** [community/community#33210] [Actions]
We have workflows that need to run when the deployment_status state is success, failed, or error. We also want to run specific workflows only when a specific environment is successfully deployed. Today we accomplish this with an `if` condition on the job, but this still triggers the workflow and we see dozens of runs that do nothing creating a lot of noise in the workflow view.

Imagine something like this:

```
on:
  deployment_status:
    environments: [ 'MyEnv' ]
    states: [ 'success', 'failure' ]
```
