### DISCUSSION TITLE
Running jobs in a container and OIDC

### DISCUSSION THREAD

**Discussion by pzmi-f3** [community/community#33254] [Actions]
Hello everyone,

GitHub Actions allow running jobs in a container instead of running directly on a runner: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container.

I'd like to use a container from a private registry using credentials obtained with OIDC integration. 
Since container and credentials are defined on a job level I cannot figure out if it's possible to pass credentials from OIDC, documentation only mentions using secrets: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#defining-credentials-for-a-container-registry.

Does anyone know if it's possible?

**Comment by antonblr** [comment]
I believe the only way of doing it is to have another job to obtain OIDC creds and then seed them downstream, i.e.:
```yaml
jobs:
  oidc-login:
    runs-on: ubuntu-latest
    outputs:
      oidc-token: ${{ steps.retrieve-token.outputs.oidc-token }}
    steps:
      - id: retrieve-token
        run: |
          <.... some logic here ... >
          echo "::set-output name=oidc-token::$(command to get token)"

  my-job:
    needs: oidc-login
    runs-on: ubuntu-latest
    container:
      image: <url-to-container>
      credentials:
        username: <...>
        password: ${{ needs.oidc-login.outputs.oidc-token }}
    steps:
        ....
 ```
