### DISCUSSION TITLE
Github Actions recent update (2022-09) breaks CIs scripts that were using vcpkg

### DISCUSSION THREAD

**Discussion by pthom** [community/community#33281] [Actions] [answered]
Following a recent update to github actions, vcpkg is now preinstalled.

As a consequence, I cannot run anymore Github CI actions that use vcpkg under windows.

**Environment**
- OS: Github CI , using Windows runner

**To Reproduce**

Create a simple github repository that use github actions with vcpkg. 

Minimal example available at: https://github.com/pthom/dummy

Content:
````
.github
└── workflows
    └── build_windows.yml.    // will try to install vcpkg, install glfw then run cmake with DCMAKE_TOOLCHAIN_FILE 
├── CMakeLists.txt.                // target_link_libraries(dummy PRIVATE glfw)
└── dummy.cpp.                     // empty main() 
````

Before Github actions update, the `build_windows.yml`contained something close to:

````yml
    - name: Install vcpkg and glfw
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg install glfw3
        cd ..
    - name: Configure
      run: |
         mkdir build
         cd build
         cmake  -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
````

This now *fails* because Github Actions now pre-installs vcpkg at `c:/vcpkg` and set the env variables, 
````
VCPKG_ROOT=C:\vcpkg
VCPKG_INSTALLATION_ROOT=C:\vcpkg
````

However, when trying to use the pre-installed vcpkg, like this: 

````yml
    - name: Install glfw with preinstalled vcpkg
      run: vcpkg install glfw3
    - name: Configure and build
      run: |
         mkdir build
         cd build
         cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
         cmake --build .
````

the cmake configure step fail (`Could not find a package configuration file provided by "glfw3"'`)

calling `vcpkg integrate install` does not help either.

Can someone help?
