### DISCUSSION TITLE
Get error message from failed job

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#33366] [Actions]
Assuming I have two jobs and the second depends on the first one:

```yaml
jobs:

  job-1:
    runs-on: ubuntu-latest 
  
    steps:
      - uses: somerepo/someaction@v1

      - uses: anotherrepo/anotheraction@v1

      - bash: shell
        run: |
          do-a-lot-of-stuff


  job-2:
    runs-on: ununtu-latest
    needs: job-1
    if: failure()

   steps:
     - shell: bash
       run: echo ${{ needs.job-1.fail.message }}
```
 
Is there a way to capture the failure message from `job-1`?
