### DISCUSSION TITLE
Manipulate some inputs to create a dynamic matrix

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#33413] [Actions] [answered]
I have a called workflow. This takes several inputs. Some of them define which images are to be pushed to a repo.

My end goal is to create a dynamic variable for the `tags` input in the action below:

```
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            foo_image
            bar_image
            foobar_image
```

Ι have the following inputs

```
  inputs:
    build_foo_image:
       type: boolean
       required: true
       default: false
    build_bar_image:
      type: boolean
      required: true
      default: false
...(etc)
```

Is it possible to convert those (and only those inputs) to a dynamic variable to be passed to the `with` statement of docker build/push?

**Comment by airtower-luna** [comment, marked as answer]
The value for `tags` is simply a multi-line string, so you can write the list you want to an environment variable or output. Note that `GITHUB_ENV` has a special format for multiple lines, while for outputs you have to URL encode the newlines.

Creating that variable would have to be done in a separate step. You could either pass the specific variables to that step, or if you need it a bit more dynamic work with something like

```yaml
- run: your-script
  env:
    JSON: ${{ toJSON(inputs) }}
```

where your script then processes the `JSON` environment variable to read the inputs you want from the JSON structure.
