### DISCUSSION TITLE
Boolean input does not meet YAML 1.2 "Core Schema"

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#33493] [Actions]
I have a reusable workflow (i.e. triggered by the `workflow_call` event)

I also have the following input defined in it:

```
      do_something:
        description: whether to do something
        required: true
        type: boolean
        default: false
```

I use the github actions script to invoke a script from a separate file as instructed [here][1], passing the `core` package as input

```
      - name: checkout the project
        uses: actions/checkout@v2

      - uses: actions/github-script@v6
        id: set-images
        with:
          script: |
            const script = require('./.github/workflows/myscript.js')
            console.log(script({core}))
```

Here is `myscript.js`

```
module.exports = ({core}) => {
    console.log(core.getBooleanInput('do_something'));
    return 0
}
```

This comes from the documentation of `core` package found [here][2].

However this attempt fails:

```
TypeError: Input does not meet YAML 1.2 "Core Schema" specification: do_something
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

  [1]: https://github.com/actions/github-script#run-a-separate-file
  [2]: https://github.com/actions/toolkit/tree/main/packages/core#inputsoutputs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `ubuntu-latest`
 - Browser: chrome
 - Version: `v6`
