### DISCUSSION TITLE
Release workflow does not run when auto-merge is used

### DISCUSSION THREAD

**Discussion by budarin** [community/community#33521] [Actions]
I use to auto-merge dependeabot PRs in private project

if I create a PR and then merge it manually, the release workflow is started, but if the automerge dependabot's PR is being performed - release workflow is not started.

the workflow
```yaml
on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - master
            
jobs:
    build:
      . . . 
            
    dependabot:
        name: 'Dependabot'
        needs: [build]

        permissions:
            contents: write
            pull-requests: write

        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v1.3.3
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'
            - name: Enable auto-merge for Dependabot PRs
              run: gh pr merge --merge ${{github.event.pull_request.html_url}}
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

release workflow

```yaml
name: Release
on:
    push:
        branches:
            - master
            - next
            - beta
            - '*.x' # maintenance releases branches

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              id: setup_node_step
              uses: actions/setup-node@v3
              with:
                  node-version: '18.9.0'

            - name: Enable Cache
              id: cache_step
              uses: actions/cache@v3
              with:
                  key: ${{ hashFiles('yarn.lock') }}
                  path: node_modules

            - if: ${{ steps.cache_step.outputs.cache-hit != 'true' }}
              run: yarn install --frozen-lockfile

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM }}
              run: npx semantic-release
```
