### DISCUSSION TITLE
Naming of workflow steps for required checks?

### DISCUSSION THREAD

**Discussion by nedbat** [community/community#33579] [Actions] [answered]
In my repo (https://github.com/nedbat/coveragepy/actions) I've given my workflow steps names that include some matrix details, like this:

```yaml
jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
```
This is nice because when looking at a run, I see steps with meaningful names. 

But now when I go to set the required checks in Branch Protection, I have 18 different checks to enable (six versions of Python, three operating systems).  Worse, I change the matrix frequently because I test with the next Python version's pre-release, which is updated monthly.  This means I have to visit the required checks and add three more checks to the list.

Is there a way for the required checks setting to recognize that these 18 (etc) checks are all the same in some sense, and just set it once?

**Comment by hugovk** [comment]
Yes, you can add a final noop job that depends on the previous matrix jobs, and add the single, static noop job to required checks list.  

For example:

```yaml
  success:
    needs: test
    runs-on: ubuntu-latest
    name: Test successful
    steps:
      - name: Success
        run: echo Test successful
```

https://github.com/hugovk/pypistats/blob/f4d5f6f8486ae3f7da34f70a29c5398bc3875ea1/.github/workflows/test.yml#L49-L55

**Reply by webknjaz** [reply]
That is a wrong solution. It will result in failing tests passing in branch protection because this job will be skipped and branch protection sees the "skipped" status as "not failing == successful". See https://github.com/re-actors/alls-green for the problems explained.

**Reply by webknjaz** [reply]
I've posted a more complete answer @ https://github.com/orgs/community/discussions/33579#discussioncomment-3796858.

**Comment by nedbat** [comment]
This works great, but now I have a twist: I have a matrix of ~20 testing combinations, including the version of Django to test against.  When we're working on upgrading (to Django 4.x), we would add that version to the matrix, but wouldn't want to require that the tests pass.

Is there some way to get this "aggregating to a success step" but for only part of the matrix?

**Reply by hugovk** [reply]
I've never tried this but this looks just the ticket:

> # `jobs.<job_id>.continue-on-error`
> Prevents a workflow run from failing when a job fails. Set to `true` to allow a workflow run to pass when this job fails.
> ## Example: Preventing a specific failing matrix job from failing a workflow run
> You can allow specific jobs in a job matrix to fail without failing the workflow run. For example, if you wanted to only allow an experimental job with `node` set to `15` to fail without failing the workflow run.

```yml
runs-on: ${{ matrix.os }}
continue-on-error: ${{ matrix.experimental }}
strategy:
  fail-fast: false
  matrix:
    node: [13, 14]
    os: [macos-latest, ubuntu-latest]
    experimental: [false]
    include:
      - node: 15
        os: ubuntu-latest
        experimental: true
```

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error

**Comment by nedbat** [comment]
`continue-on-error` works, but it means I have to use conditionals I think:
```yaml
name: "Matrix experiment"

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "py ${{ matrix.python-version }}; dj ${{ matrix.django-version}}"
    runs-on: "ubuntu-latest"
    # We expect Django 4.0 to fail, so don't stop if it does.
    continue-on-error: ${{ matrix.django-version == '4.0' }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - "3.2"
          - "4.0"

    steps:
      - name: "Fake tests"
        run: |
          echo "Python: ${{ matrix.python-version }}"
          echo "Django: ${{ matrix.django-version }}"
          # Django 4.0 doesn't pass yet...
          if [[ "${{ matrix.django-version }}" == "4.0" ]]; then exit 17; fi
          echo "Success"
          
  # A final step to give a simple name for required status checks.
  # https://github.com/orgs/community/discussions/33579
  success:
    needs: tests
    runs-on: ubuntu-latest
    name: Tests successful
    steps:
      - name: "Success"
        run: |
          echo Tests successful
```
I wish there were a way to have one entry in the matrix that meant, "Use Django 4.0, and don't stop if the tests fail".

**Reply by nedbat** [reply]
Or, is there a way to have the final "success" step only need part of the matrix?

**Reply by hugovk** [reply]
> Or, is there a way to have the final "success" step only need part of the matrix?

Not that I know of.

---

Based on your example, here's an alternative method:

```yml
name: "Matrix experiment"

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "py ${{ matrix.python-version }}; dj ${{ matrix.django-version}}"
    runs-on: "ubuntu-latest"
    # Don't stop for experimental jobs.
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - "3.2"
        # Default is non-experimental.
        experimental: [false]
        # Also test Django 4.0: expected to fail so set as experimental.
        include:
          - { experimental: true, django-version: "4.0", python-version: "3.7" }
          - { experimental: true, django-version: "4.0", python-version: "3.8" }
          - { experimental: true, django-version: "4.0", python-version: "3.9" }
          - { experimental: true, django-version: "4.0", python-version: "3.10" }

    steps:
      - name: "Fake tests"
        run: |
          echo "Python: ${{ matrix.python-version }}"
          echo "Django: ${{ matrix.django-version }}"
          # Django 4.0 doesn't pass yet...
          if [[ "${{ matrix.django-version }}" == "4.0" ]]; then exit 17; fi
          echo "Success"

  # A final step to give a simple name for required status checks.
  # https://github.com/orgs/community/discussions/33579
  success:
    needs: tests
    runs-on: ubuntu-latest
    name: Tests successful
    steps:
      - name: "Success"
        run: |
          echo Tests successful
```

And a diff:

```diff
@@ -13,8 +13,8 @@ jobs:
   tests:
     name: "py ${{ matrix.python-version }}; dj ${{ matrix.django-version}}"
     runs-on: "ubuntu-latest"
-    # We expect Django 4.0 to fail, so don't stop if it does.
-    continue-on-error: ${{ matrix.django-version == '4.0' }}
+    # Don't stop for experimental jobs.
+    continue-on-error: ${{ matrix.experimental }}
     strategy:
       fail-fast: false
       matrix:
@@ -25,7 +25,14 @@ jobs:
           - "3.10"
         django-version:
           - "3.2"
-          - "4.0"
+        # Default is non-experimental.
+        experimental: [false]
+        # Also test Django 4.0: expected to fail so set as experimental.
+        include:
+          - { experimental: true, django-version: "4.0", python-version: "3.7" }
+          - { experimental: true, django-version: "4.0", python-version: "3.8" }
+          - { experimental: true, django-version: "4.0", python-version: "3.9" }
+          - { experimental: true, django-version: "4.0", python-version: "3.10" }
 
     steps:
       - name: "Fake tests"
```

Yours is more compact with `continue-on-error: ${{ matrix.django-version == '4.0' }}`; this one means omitting 4.0 from the matrix but explicitly adding each one via `include`

[aiohttp](https://github.com/aio-libs/aiohttp) also uses this `experimental` method: https://github.com/aio-libs/aiohttp/blob/0116cfddbf140cdafeefd1638382d4e0d1ab19e4/.github/workflows/ci.yml#L124-L158

**Reply by webknjaz** [reply]
@hugovk note that aiohttp also uses a proper check job there.

**Comment by webknjaz** [comment, marked as answer]
I have solved this in a generic way, taking into account unobvious corner cases, with a reusable action.
```yaml
---

on:
  pull_request:
  push:

jobs:
  tests:
    ...
    strategy:
      matrix:
        python-version:
        # - ~3.12.0-0  # doesn't yet exist as of Oct 04, 2022
        - ~3.11.0-0
        - >-
          3.10
        - 3.9
    ...
    continue-on-error: >-  # this allows "unstable" versions to fail, except for 3.11, meaning 3.12 alpha when it's added
      ${{
        (
          startsWith(matrix.python-version, '~')
          && !startsWith(matrix.python-version, '~3.11')
        )
        && true
        || false
      }}
    ...
    steps:
    - ...

  check:  # This job does nothing and is only used for the branch protection
    if: always()

    needs:
    - tests

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

...
```

See https://github.com/marketplace/actions/alls-green#why.

Current known users: aiohttp (and other aio-libs projects), CherryPy, some of the Ansible repositories, pip-tools, all of the jaraco's projects (like `setuptools`, `importlib_metadata`), some of hynek's projects, some PyCQA, PyCA, PyPA and pytest projects, a few AWS Labs projects (to my surprise). And more: https://github.com/re-actors/alls-green/network/dependents.
