### DISCUSSION TITLE
Cancel current running workflow from itself

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#33595] [Actions] [answered]
I want to be able, based on a condition to cancel my current run of a `workflow`.

I tried to use [this](https://github.com/marketplace/actions/cancel-workflow-action) action like this

```yaml
      - name: cancel workflow if none of files we look for changes has not changed
        if: steps.changed-files.outputs.any_changed != 'true'
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: ${{ github.workflow_id }}
          access_token: ${{ github.token }}
```

but as it turns out from the logs:

```
Found token: yes
Found workflow_id: ["32318643"]
Found 3 runs total.
Found 0 runs to cancel.
```

it only cancels **other workflows running concurrently**.

Is there an easy way around this or should I resort to GH API?
