### DISCUSSION TITLE
Dynamically choosing reusable workflow file

### DISCUSSION THREAD

**Discussion by wbonnefond** [community/community#33657] [Actions]
It would be amazing if we could dynamically choose the reusable workflow to run based on some input.

Consider the case of a monorepo where we conceptually want to run `lint`, `unit test`, `build`, `smoke test` on each affected project in a PR. One might consider using matrixed jobs with reusable workflows to accomplish this. But this approach breaks down when the conceputal jobs require slightly (or vastly) different steps, setup, or environments between different projects. For example, in our repo the `lint`, `unit test` and `build` jobs are identical across projects, but the `smoke test` job requirements are completely different depending on the project.

Being able to do something like this would be a godsend:

```
# ./github/workflows/starter.yml
on:
  pull_request:
    - opened

jobs:
  changes:
    # determine changes projects
  build:
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '' }}
    strategy:
      matrix:
        target: ${{ fromJSON(needs.changes.outputs.packages) }}
    uses: ./.github/workflows/pr-build.yml
    with:
      project_name: ${{ matrix.target }}
    secrets: inherit

  lint:
    # near identical configuration to "build"

  unit_test:
    # near identical configuration to "build"



# ./github/workflows/pr-build.yml
on:
  workflow_call:
    inputs:
      project_name:
        type: string
        required: true
        description: Name of project in monorepo to build

jobs:
  build:
    steps:
      # build steps

  smoke_test:
    needs: build
    uses: ./.github/workflows/smoke_test_${{ inputs.project_name }}.yml    # pass the project name as the input 
    secrets: inherit
```

I've looked around for any tricks that can accomplish this, but every workaround has drawbacks.

I've considered having multiple `smoke_test_<project_name>` jobs which could be conditionally run based on the project name input. This scales poorly and results in an explosion of useless jobs in the PR jobs list and those jobs can be misleading because you may see `smoke_test_projectA SKIPPED`, but it was only skipped because that particular job run was for a different `project_name` input.

I've considered using reusable workflow outputs to conditionally run jobs after the matrixed jobs finish. The major drawback here is that it requires ALL the matrix jobs to finish, so we can't begin a smoke test for `projectA` as soon as the build for `projectA` completes. This also requires hardcoding outputs for the specific projects we want to run, so this also scales poorly just like the first.

Please consider adding this functionality. It would greatly improve the flexibility in reusing workflows.
