### DISCUSSION TITLE
Get live log output out of container job

### DISCUSSION THREAD

**Discussion by ar2rsawseen** [community/community#33681] [Actions]
Hello,
when running job with container like:

```
container:
      image: our-container-image

steps:
      - uses: actions/checkout@v2
```
How to get container output/std:out live with what steps are outputting? Bitbucket pipelines do it out of the box. It is very handy if there is an error while the test is running and failing. You see both outputs together.
Or at least how to get container output logs at all?
