### DISCUSSION TITLE
Wrong version retrieved when running workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#33691] [Actions] [answered]
In the following steps

```
      - name: dynamically retrieve go version
        uses: arnested/go-version-action@v1
        id: go-version

      - run: echo ${{ steps.go-version.outputs.go-mod-version }}

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.go-mod-version }}
```

I have the following output, any ideas why?

![Screenshot 2022-09-21 at 2 39 13 PM](https://user-images.githubusercontent.com/50835081/191494679-cd3a59a1-63ab-4234-8815-73730564fe40.png)
