### DISCUSSION TITLE
Indirect referencing an input variables

### DISCUSSION THREAD

**Discussion by csuriano23** [community/community#33707] [Actions]
Hi there,
in a github actions workflow I have an input choice like this:

```yaml
  workflow_dispatch:
    inputs:
      myinput:
        description: "My Input"
        required: true
        type: choice
        options:
          - key1
          - key2
          - key3
```

and I want to map each input to a value, eg. in the env like this:

```yaml
env:
  key1: value1
  key2: value2
  key3: value3
```

Which is the right way to obtain that mapping?

**Comment by ChristopherHX** [comment]
These might be two possible ways:
Using bracket notation to access an object.

```yaml
on:
  workflow_dispatch:
    inputs:
      myinput:
        description: "My Input"
        required: true
        type: choice
        options:
          - key1
          - key2
          - key3
jobs:
  _:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mapping:
          - key1: value1
            key2: value2
            key3: value3
    steps:
      - run: |
           echo "${{ matrix.mapping[ inputs.myinput ]}}"
```

Or use env, this makes the mapping available as env for all actions and run steps

```yaml
on:
  workflow_dispatch:
    inputs:
      myinput:
        description: "My Input"
        required: true
        type: choice
        options:
          - key1
          - key2
          - key3
env:
  key1: value1
  key2: value2
  key3: value3
jobs:
  _:
    runs-on: ubuntu-latest
    steps:
      - run: |
           echo "${{ env[ inputs.myinput ]}}"
```
