### DISCUSSION TITLE
Defining PowerShell as the default shell for all the jobs

### DISCUSSION THREAD

**Discussion by vcrobe** [community/community#33706] [Actions] [answered]
Hi there,

I want to use _PowerShell_ as the default shell on all my jobs. 

I've created the following workflow and defined the shell in the global defaults but the shell used when executed the workflow is _Bash_, however if I specify the shell in the job's defaults it works as expected. What I'm doing wrong?

```
name: Deployment

on:
  push:
     tags:
        - 'v*'

defaults:
      run:
        shell: pwsh  # This is not working. Still using Bash as the shell

jobs:
  build_release_files:
    name: Build release files

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        #shell: pwsh    ### If I use shell here it works as expected

    steps: 
       .
       .
       .

```
