### DISCUSSION TITLE
set-output json for matrix strategy: Spaces not supported

### DISCUSSION THREAD

**Discussion by dhawalseth** [community/community#33734] [Actions]
Sample commands.json 

```
[
    "true",
    "echo 123",
    "cat build/artifact1.txt"
]
```

Workflow file
```
  Build:

    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]

    outputs:
      # The matrix of test commands to run in parallel.
      commands: ${{ steps.set-commands.outputs.commands }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Read the test commands
      - id: set-commands
        run: |
            content=$(cat commands.json)
            # For multi-line JSON.
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
            # Set the output.
            echo "::set-output name=commands::$content"
  
  Distributed-Test:

    runs-on: [ self-hosted, macOS ]

    needs: [ Build ]

    strategy:
      # The matrix of test commands.
      matrix: ${{ fromJSON(needs.Build.outputs.commands) }}

    steps:

      # Run the test command.
      - name: Run test
        run: ${{ matrix.test }}
```
We get the following error:
```
Error when evaluating 'strategy' for job 'distributed-test'. (Line: 55, Col: 15): After parsing a value an unexpected character was encountered: ". Path '[0]', line 2, position 5.,(Line: 55, Col: 15): Unexpected value ''
```

It works only if we remove all spaces from the commands.json values
```
content="$(echo -e "$content" | tr -d '[:space:]')"
```

**Comment by airtower-luna** [comment]
The [`space` character class](https://manpages.debian.org/bullseye/manpages-dev/isspace.3.en.html#isspace) matches not only spaces, but also newlines (`\n`) and carriage returns (`\r`), so after that your URL escaping won't take effect (except for percent signs). It's not immediately obvious to me what goes wrong there, though I suspect the carriage returns.

What happens if you use `jq` to get a compact (single-line) representation of your JSON instead?

```
content=$(cat commands.json | jq --compact-output)
echo "::set-output name=commands::$content"
```

**Reply by dhawalseth** [reply]
Thank you but this did not help. 

I also tried with `|jq -Rc`
```
Error when evaluating 'strategy' for job 'Distributed-Test'. (Line: 74, Col: 15): Error reading JToken from JsonReader. Path '', line 0, position 0.,(Line: 74, Col: 15): Unexpected value ''
```

**Reply by airtower-luna** [reply]
Can you output the JSON in another job? I think seeing the exact value would make it easier to see what's going wrong.

**Reply by dhawalseth** [reply]
job that sets output:
```
content=$(jq -Rc < commands.txt)
  echo $content
  # Set the output.
  echo "::set-output name=commands::$content"
  ```
  console output
  ```
"True" "echo 'test'" "cat build/artifact1.txt"
"echo 'test'"
"cat build/artifact1.txt"
```

job that logs the output:
```
      - name: Run
        shell: bash
        run: |
          echo ${{ needs.job-1.outputs.commands }}
```
console:
```
Run echo "True"
  echo "True"
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
True
```
So this means it is only getting the first one "True" in the output

**Reply by airtower-luna** [reply]
The `-R` doesn't makes sense here, and *breaks* the `-c` option. You still get multiline output, so it's no surprise it doesn't work. Use `-c` only.

Also this isn't going to work for any output that controls characters that have special meaning to Bash, like quotes:

```yaml
      - name: Run
        shell: bash
        run: |
          echo ${{ needs.job-1.outputs.commands }}
```

The reason is that Actions syntax `${{ ... }}` is literally substituted before the script goes to Bash, so Bash doesn't know what's supposed to be a variable. That's why the multiple lines break.

Use an environment variable and Bash syntax instead:

```yaml
      - name: Run
        shell: bash
        run: |
          echo "${JSON}"
        env:
          JSON: ${{ needs.job-1.outputs.commands }}
```
