### DISCUSSION TITLE
Dependabot: trust individual external code registries

### DISCUSSION THREAD

**Discussion by TALlama** [community/community#33750] [Code Security]
The `insecure-external-code-execution` setting in the [Dependabot docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#insecure-external-code-execution) lets the update checker trust external code registries.

But it's an all-or-nothing switch right now: if we `allow` it, we are implicitly trusting all registries that might get added in the future. Currently you make that decision once, based on the registries you have now, and never have to worry about it again.

We would prefer it if each registry could be trusted individually. When we add a new registry, we'd see the trust assertion in the PR and have to think about if we actually do trust it. We'd be regularly reminded that this part of our supply chain is potentially exploitable.

**Comment by bogn83** [comment]
> We'd be regularly reminded that this part of our supply chain is potentially exploitable.

Totally agreeing that this would be a huge benefit and a much needed security improvement.

**Comment by jeffwidman** [comment]
Can you add this as a feature request in https://github.com/dependabot/dependabot-core/ issue tracker?

It's easier for us (the Dependabot engineering team) to track it that way...

**Comment by narayan8291** [comment]
@jeffwidman I have this Dependabot config file to add `insecure-external-code-execution` to individual registries. This does **not** work since Dependabot still throws the same error. 

```
Dependabot refused to execute external code
Dependabot blocked external code required for this update. Please set insecure-external-code-execution: allow in the config if you trust all dependencies' supply chain.
```

dependabot.yml file
```
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    **insecure-external-code-execution: allow**
    registries:
      - jfrog-rubygems
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    **insecure-external-code-execution: allow**
    registries:
      - jfrog-artifactory

registries:
  jfrog-rubygems:
    type: <>
    url: <>
    username: <>
    password: <>

  jfrog-artifactory:
    type: <>
    url: <>
    username: <>
    password: <>
```

1. Is this relevant to the fact that Dependabot does not support "trusting individual registries"?
2. Are there any workarounds instead of adding `registries:*`?

Thanks!
