### DISCUSSION TITLE
GitHub-actions bot not triggering Actions

### DISCUSSION THREAD

**Discussion by jonny-harte** [community/community#33804] [Actions] [answered]
Hi, I have an Action that's triggered when a label is added to a Pull Request. It works as expected when I add the UAT label but a workflow run isn't initiated when **github-actions** bot adds the same label from another Action.

How do I get a workflow to initiate when **github-actions** bot adds a label to a PR?

```
Continuous Integration
on:
  pull_request:
    branches: [main]
    paths:
      - "force-app/**"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  validate-package:
    environment: Testing
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft != true
    steps:
      - name: Add UAT Label
        uses: andymckay/labeler@master
        with:
          add-labels: "uat"
```

```
Deploy Package to UAT
on:
  pull_request:
    branches: [main]
    paths:
      - "force-app/**"
    types: [labeled]

jobs:
  deploy-package:
    environment: UAT
    if: github.event.pull_request.draft != true && github.event.label.name == 'uat'
    runs-on: ubuntu-latest
    steps:
      - name: Log Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
```
