### DISCUSSION TITLE
Unable to use Gradle's maven-publish to github packages for at least 48 hours

### DISCUSSION THREAD

**Discussion by sigalsPipl** [community/community#33857] [Other Feature Feedback, Questions, & Ideas]
We have a gradle project that we created more then a year ago, the project uses the 'maven-publish' plugin to publish the project artifacts to the github packages.
For about a year it has worked for us with sporadic failures of the publishing (roughly 1 out of 3 attempts failed).
Since at least the last 48 hours we are unable to publish the artifacts, getting http errors from the APIs (will be detailed below).

The gradle relevant code (Kotlin DSL):
```
plugins{
    `maven-publish`
 }

publishing {
    publications {
        create<MavenPublication>("myProject") {
            from(components["java"])
            groupId = "com.me"
            withBuildIdentifier()
        }
    }

    repositories {
        maven {
            name = "myCompany"
            url = uri("https://maven.pkg.github.com/mycompany/maven-packages/")
            credentials {
                username = System.getenv("MAVEN_USERNAME")
                password = System.getenv("MAVEN_PASSWORD")
            }
        }
    }
}
```
gradle-wrapper.properties:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

```

Github workflow code (snippets):
```

env:
  MAVEN_USERNAME: ${{ secrets.USER }}
  MAVEN_PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build-jar:
    name: Build jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle build jar and publish
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: --info clean publish
```

The last time this workflow was successful was Sunday September 18th 2022.

Since Tuesday September 20th 2022 (the next time the job ran), we are getting one of the following HTTP errors from github packages:
```
2022-09-22T11:47:21.8387568Z 2022-09-22T11:47:21.767+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to publish publication 'myProject' to repository 'myCompany'
2022-09-22T11:47:21.8389026Z 2022-09-22T11:47:21.767+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not GET 'https://maven.pkg.github.com/mycompany/maven-packages/com/me/my-jar/0.0.1-SNAPSHOT/maven-metadata.xml'.
```
or
```
Failed to publish publication 'myProject' to repository 'myCompany'
   > Could not PUT 'https://maven.pkg.github.com/mycompany/maven-packages/com/me/my-jar/0.0.1-SNAPSHOT/my-jar-0.0.1-20220921.090810-496.module.sha1'. Received status code 409 from server: Conflict
```

And more similar errors.

We have not changed the project's code for over a week, so we have no idea what's breaking the build. Any ideas or a reference to a known issue would be most appreciated.
