### DISCUSSION TITLE
JavaScript monorepo run build only once

### DISCUSSION THREAD

**Discussion by olivier-martin-sf** [community/community#33951] [Actions]
Hi, I am getting started with GitHub Actions and I am working on migrating a JS monorepo that uses CircleCI.

I am wondering what's could be the best approach to invoke the `install` and `build` command only once. In other words, how to pass the output of the build job to the next ones. Basically, the pipeline I am trying to port does the following in sequence: install deps & build -> run unit test -> run e2e test

I am trying to find the best approach so that `yarn install` && `yarn build` commands are run only once. 

The CircleCI config I am migrating used the following commands:

```yaml
    load_workspace:
        description: Load workspace
        steps:
            - attach_workspace:
                  at: ~/project

    save_workspace:
        description: Save current workspace
        steps:
            - persist_to_workspace:
                  root: .
                  paths:
                      - .
```

And for instance, the unit test jobs was described as the following:

```yaml
    test_unit:
        executor: node
        steps:
            - load_workspace
            - run:
                  name: Run unit tests
                  command: yarn test:unit
```

I've tried to use Artifacts but it was awfully slow (as we don't really generate a binary) and it took around ~23min to upload the workspace. I am actually just caching yarn dependencies (so that it doesn't have to fetch them over the registry) using `actions/setup-node`. I think one way to solve this would be to use `actions/cache` and cache the `node_modules` folder but I read that it was a bad practice.

Is there any way to achieve this or do I have to repeat the build and install steps for every jobs?
