### DISCUSSION TITLE
removing character from github context variable

### DISCUSSION THREAD

**Discussion by andy5995** [community/community#33965] [Other Feature Feedback, Questions, & Ideas] [answered]
When using Actions, I get an error when trying to use `${{ github.ref_name##v }}`.

How can I remove the first character of that returned string if it's a `v`?

**Comment by DenverCoder1** [comment]
Are there any docs saying the above is supposed to work?

In any case, I'd probably do it with a bash run step, for example

```yml
run: |
  REF=$(echo ${{ github.ref_name }} | perl -0777 -pe 's/^v//')
  echo "${REF}"
```

You could also use a set output if you want to use it in a different step.

```yml
    steps:
      - name: Remove v prefix
        id: removev
        run: echo "::set-output name=ref_name::$(echo ${{ github.ref_name }} | perl -0777 -pe 's/^v//')"
      - name: Use result
        run: echo "${{ steps.removev.outputs.ref_name }}"
```

I haven't tested this, but it seems like it should do what you described
