### DISCUSSION TITLE
trigger repository_dispatch curl response in json

### DISCUSSION THREAD

**Discussion by antyung88** [community/community#34032] [Apps, API and Webhooks]
hi,

is there anyway i can get a json success response from curl POST triggering a repository_dispatch workflow in github actions?

success only gives response code `204` but does not return any information in json such as job id.

example:
```
name: repository_dispatch

on:
  repository_dispatch:
    types:
      - test1
    
jobs:
  test1:
    if: ${{ github.event_name }} = "test1"
    runs-on: ubuntu-latest
    steps:
      echo "test1"
```

```
TOKEN="" \
GH_USER="" \
REPO="" && \
EVENT=test1
curl \
-X POST \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer $TOKEN" \
https://api.github.com/repos/$GH_USER/$REPO/dispatches \
-d "{\"event_type\": \"${EVENT}\"}"
```

any help is appreciated. thanks!
