### DISCUSSION TITLE
Issue form body was parsed to empty unexpectly

### DISCUSSION THREAD

**Discussion by bsdayo** [community/community#34074] [Projects and Issues]
I tried to create a issue form in my organization's public repo, with the following content in `.github/ISSUE_TEMPLATE/feature-request.yml`:

```yaml
name: Feature Request
description: 功能请求
title: "Feature: "

labels:
  - feature

body:
  - type: textarea
    attributes:
      label: Describe the problem related to the feature request
      description: 请简要地说明是什么问题导致你想要一个新特性。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: 请说明你希望使用什么样的方法，或增加什么功能来解决上述问题。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: 除了上述方法以外，你还考虑过的其他的实现方式。

  - type: textarea
    attributes:
      label: Additional context
      description: 请描述其他想要补充的信息。
```

But after push I found the template is not working. Viewing it on GitHub warned the following error:

> There is a problem with this template: Body cannot be empty. 

As you can see, the body is not empty as it said. After it I tried to copy a currently working template file like [this](https://github.com/koishijs/koishi/blob/master/.github/ISSUE_TEMPLATE/bug-report.yaml), it only shows the same error again.

Is there some wrong steps I haven't noticed?

Sorry for my poor English, and I'll be appreciate if someone can help me! ;D
