### DISCUSSION TITLE
Add if condition into workflow inputs for show or hide field

### DISCUSSION THREAD

**Discussion by M97Chahboun** [community/community#34127] [Actions]
Hello,  I want suggest a proposal about **workflow inputs**
As you see in screenshot we have` _Fastlane lane_` this input have 2 choices (`promote` or `deploy`) 
I want when I select `promote` hide `_Fastlane Bump version_` ,` _Create new tag_ `& `_Push bump version_` &
`_Deploy to input_`
When I select `deploy` show `_Fastlane Bump version_` ,` _Create new tag_ `& `_Push bump version_` &
`_Deploy to input_` & hide ` _Promote from_` & `_Promote to_`
we need something as `if: some condition` as input parameter
![Screen Shot 2022-09-25 at 18 30 12](https://user-images.githubusercontent.com/69054810/192156948-e2ec7f72-bde5-48bc-9179-ef1114462d0f.png)
**Current yaml**
```
 workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "beta"
        type: choice
        options:
          - promote
          - deploy
      bump_version:
        description: "Fastlane Bump version"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      create_tag_and_push:
        description: 'Create new tag & Push bump version'
        required: true
        default: true 
        type: boolean
      track:
        description: "Deploy to"
        required: true
        default: "alpha"
        type: choice
        options:
          - production
          - beta
          - alpha
          - internal
      promote_from:
        description: "Promote from"
        required: true
        default: "alpha"
        type: choice
        options:
          - production
          - beta
          - alpha
          - internal
      promote_to:
        description: "Promote to"
        required: true
        default: "beta"
        type: choice
        options:
          - production
          - beta
          - alpha
          - internal
```
**Expect yaml**

 ```
workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "beta"
        type: choice
        options:
          - promote
          - deploy
      bump_version:
        if: ${{ github.event.inputs.lane == 'deploy' }}
        description: "Fastlane Bump version"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      create_tag_and_push:
        if: ${{ github.event.inputs.lane == 'deploy' }}
        description: 'Create new tag & Push bump version'
        required: true
        default: true 
        type: boolean
      track:
        if: ${{ github.event.inputs.lane == 'deploy' }}
        description: "Deploy to"
        required: true
        default: "alpha"
        type: choice
        options:
          - production
          - beta
          - alpha
          - internal
      promote_from:
        if: ${{ github.event.inputs.lane == 'promote' }}
        description: "Promote from"
        required: true
        default: "alpha"
        type: choice
        options:
          - production
          - beta
          - alpha
          - internal
      promote_to:
        if: ${{ github.event.inputs.lane == 'promote' }}
        description: "Promote to"
        required: true
        default: "beta"
        type: choice
        options:
          - production
          - beta
          - alpha
          - internal
```
