### DISCUSSION TITLE
github workflow - input type choice with multi-select option

### DISCUSSION THREAD

**Discussion by porottasambar** [community/community#34298] [Actions]
Hi,

Is there any way i can enable multi-select dropdown option in `workflow_dispatch` with input type choice?

**Comment by umassahu** [comment]
As per my knowledge this is not yet implemented

**Reply by porottasambar** [reply]
thank you for your info @umassahu much appreciated.

**Comment by alxgomz** [comment]
No that is indeed not implemented. There is an issue that has gotten some traction but no one created a product feedback linked to it so I'll be doing it hoping that people who participated in this issue and thumb'ed it up will upvote here too:
 https://github.com/actions/runner/issues/2076

I'll also copy verbatim this issue description which is more complete:

> **Describe the enhancement.**
> Current set of input types doesn't cover some use-cases for manual workflows.
>
> We use a single gh-action as an entrypoint of deploying packages from our monorepo, and sometimes we need > to manually deploy several packages simultaneously. Up until now we just went with a set of Booleans, so we could tick all the packages we needed to run our CI/CD against via UI. However, we speedily reached a https://github.com/actions/runner/issues/1928
>
> Introducing an input type that would store a, say, json array could help:
> 
> ```yaml
> on:
>   workflow_dispatch:
>    inputs:
>      name:
>        type: multi-choice
>        description: select packages
>        options: 
>        - go-service1
>        - go-service2
>        - py-service1
>
> ...and in fact would be more logical with less copy-paste overhead for our use-case

**Comment by DevonBT** [comment]
See also https://github.com/orgs/community/discussions/8774, a (very active) discussion about how the limit of 10 workflow inputs is making job configuration difficult. Some users suggest multi-select options as an excellent workaround. There seems to be a lot of desire for this feature.

**Comment by momentmaker** [comment]
please I need this for my family

**Reply by scottcudney-apporto** [reply]
Your family depends on GitHub Actions drop-down menus?

**Reply by Andrei-Vasil** [reply]
Yours doesn't?

**Reply by JuanChurioRivera** [reply]
what a burn

**Comment by ap0h** [comment]
Yap I came here looking for exactly the same thing.

**Comment by james-arawhanui** [comment]
Currently working around the problem by listing multiple 'options' sets for the user to choose from, and leaving the validation 

- up to them (while selecting the options)
- extra validation steps in a shell script, called by the workflow

so leaving the team to be adults, and giving them a slightly-lagged warning (and broken build) if they get it wrong, to learn for next time and prevent bad builds (which can also be seen as **deployments** if you do GitOps).

Feels like if it's getting this complex we should be moving to a more complex CD stack with more UI support, I don't exactly blame GitHub Actions team for not wanting this extra scope.

**Comment by clarkritchie** [comment]
Here is a way to pass arbitrary JSON, including arrays, to actions that have `workflow_dispatch` triggers, which can effectively simulate a multi-choice list in an action.  This also is a way to get around the 10 input limit.

```zsh
$ JSON_DATA=$(cat <<EOF
{
  "foo": "foo",
  "bar": [ "bar", "baz" ]
}
EOF
)

# tidy it up to one line
$ JSON=$(echo $JSON_DATA | tr -d '\n' | tr -d '[:space:]')

# run the workflow
$ gh workflow run foo-bar-baz.yaml --ref example -f config=${JSON}
✓ Created workflow_dispatch event for foo-bar-baz.yaml at example

To see runs for this workflow, try: gh run list --workflow=foo-bar-baz.yaml
```

Action:

```yaml
name: Foo Bar Baz

on:
  workflow_dispatch:
    inputs:
      config:
        description: "Configuration (as JSON)"
        required: true

jobs:
  foo-bar-baz:
    runs-on: small
    steps:
      - name: Parse JSON Inputs
        id: input-values
        run: |
          json_data='${{ inputs.config }}'
          echo "foo=$(echo $json_data | jq -r '.foo')" >> $GITHUB_OUTPUT
          echo "bar=$(echo $json_data | jq -c '.bar')" >> $GITHUB_OUTPUT

      - name: Echo JSON
        run: |
          echo "Foo is ${{ steps.input-values.outputs.foo }}"
          echo "Bar is ${{ steps.input-values.outputs.bar }}"
```

Output:

```
Run echo "Foo is foo"
  echo "Foo is foo"
  echo "Bar is ["bar","baz"]"
  shell: /usr/bin/bash -e {0}
Foo is foo
Bar is [bar,baz]
```

**Comment by judeokafor** [comment]
I came here looking for the same thing. Strange how many people want this but it's not yet a feature

**Comment by garysassano** [comment]
It doesn't make any sense that you have to implement workarounds like this:

```yml
workflow_dispatch:
  inputs:
    environment:
      description: Deploy environment name
      type: choice
      required: false
      options:
        - staging
        - production
        - all
      default: all
```

And then 

```yml
${{ (github.event_name == 'workflow_dispatch' && inputs.environment == 'all') && fromJSON('["staging", "production"]') }}
```

The JSON array could be handled directly by a multi-select dropdown input instead.
