### DISCUSSION TITLE
How to conditionnally run in a container or not, depending on matrix value

### DISCUSSION THREAD

**Discussion by mquinzin** [community/community#34303] [Actions]
Hi, I have a matrix running for both linux64 and win64 arch.
For linux64, I want to run into a container and for win64 I can't since container on windows are not supported by github for the moment.
I would like to enable the container usage only for linux64 arch, having something like:

jobs:
  build_tools:
    runs-on: ["${{ matrix.os }}"]

    strategy:
      matrix:
        include:
          - os: win64
            cont_image: 'none'
          - os: linux64
            cont_image: 'mycontainerimage:latest'

    container: 
      if: ${{ matrix.cont_image != 'none' }}
      image: ${{ matrix.cont_image }}

But the if statement here is not allowed : "Unexpected value 'if'"
Is there any other way to do ? I did not found any way reading posts on the web and trying things by myself.
Many thx.

**Comment by Radonirinaunimi** [comment]
Hi there, have you managed to find the solution for this? I am also encountering the exact same situation.

**Reply by mquinzin** [reply]
Nope, I had to write a separated step ...

**Comment by ChristopherHX** [comment]
This should work, an container property with an empty string is ignored by the runner.

```yaml
jobs:
  build_tools:
    runs-on: ["${{ matrix.os }}"]

    strategy:
      matrix:
        include:
          - os: win64
            cont_image: ''
          - os: linux64
            cont_image: 'mycontainerimage:latest'
    container: ${{ matrix.cont_image }}
```

If your image needs options this get's more complex.

```yaml
jobs:
  build_tools:
    runs-on: ["${{ matrix.os }}"]

    strategy:
      matrix:
        include:
          - os: win64
            cont_image: ''
          - os: linux64
            cont_image:
              image: mycontainerimage:latest
              options: '' # Put container options here
    container: ${{ matrix.cont_image }}
```

If you need username / password auth, then I think you are out of luck, unless GitHub implement an if property or allows secrets in matrix

**Edit** Removed auth from description of the second example.
