### DISCUSSION TITLE
Single Dependabot PR for multiple directories

### DISCUSSION THREAD

**Discussion by dkirrane** [community/community#34317] [Pull Requests]
Is there a way to create a single dependabot Pull Request for multiple directories.

Currently, I have the following but it create separate PRs for each directory.

```
version: 2

updates:

  - package-ecosystem: "terraform"
    directory: "/terraform-plan-one"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "terraform"
    directory: "/terraform-plan-two"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
```
