### DISCUSSION TITLE
Add runs-on and container to global|default workflow attributes

### DISCUSSION THREAD

**Discussion by AllanOricil** [community/community#34326] [Actions]
I have a workflow with multiple jobs and I would like to have all of them using the same container image and OS. At the moment, to achieve this, I have to do the following: 

````yml
name: My Workflow

on:
    workflow_call:

jobs:
    job-1:
        runs-on: ubuntu-latest
        container:
           image: my-image-repo/image-name@image-ref
           credentials:
                 username: ${{ github.actor }}
                 password: ${{ secrets.GITHUB_TOKEN }}
     
        steps:
             - name: step 1
                run: echo "do something"
     
     job-2:
        runs-on: ubuntu-latest
        container:
           image: my-image-repo/image-name@image-ref
           credentials:
                 username: ${{ github.actor }}
                 password: ${{ secrets.GITHUB_TOKEN }}
                 
        steps:
           - name: step 1
              run: echo "do something"
       
     job-3:
        runs-on: ubuntu-latest
        container:
           image: my-image-repo/image-name@image-ref
           credentials:
                 username: ${{ github.actor }}
                 password: ${{ secrets.GITHUB_TOKEN }}
                 
       steps:
           - name: step 1
              run: echo "do something"
     
    
````

As you can see, the above workflow repeats its runner configuration multiple times. In order to remove code repetition, the idea is to have "default | global" attributes for the `runs-on` and `container` attributes, like the `permissions` attribute. The resulting workflow would be simplified to the one shown below:

````yml
name: My Workflow

on:
    workflow_call:

runs-on: ubuntu-latest
container:
   image: my-image-repo/image-name@image-ref
   credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

jobs:
    job-1:
      steps:
         - name: step 1
            run: echo "do something"
     
   job-2:
       steps:
         - name: step 1
            run: echo "do something"
     
   job-3:
      steps:
         - name: step 1
            run: echo "do something"
           
    
````
