### DISCUSSION TITLE
Eslint shows no output and exits with code 0 in Github Actions

### DISCUSSION THREAD

**Discussion by Wazbat** [community/community#34334] [Actions]
Hi there! I have a typescript project and I'm using eslint to lint my code. I have a simple npm script, consisting of this one command
```
"lint": "eslint src/**/*.ts"
```
When I run this on my local windows machine, I see linting errors and warnings which is what I want, however when running the exact same command inside github actions, the output is empty and the step passes.
![image](https://user-images.githubusercontent.com/6253896/192536361-ed51f35e-c287-4317-9127-20b8b564a518.png)

I'm honestly not sure what the problem could be here. I'm running the checkout step so all the files are there, the install step installs everything, and there's no errors. Here's my lint job:
```yaml
lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
```
