### DISCUSSION TITLE
Error when runnig python jobs inside custom containers

### DISCUSSION THREAD

**Discussion by kafteji** [community/community#34444] [Actions]
HI everyone,

So, i'm trying to setup a CI job for a python repository. I'm using a custom container based on python:3.9-slim-buster and just adding pip credential config to access the company private PyPi repository.
The dockerfile looks similar to the following.

``` dockerfile
FROM python:3.9-slim-buster

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    gpg \
    curl \
    ca-certificates \
    && apt-get clean

RUN echo "[global]\nindex-url = link to my private repo with some credentials passed as secrets" > /etc/pip.conf

```

Nothing too fancy here. But i'm just not able to get the workflow to run because of this weird error when executing the tox command.

```bash
py39: install_deps> python -I -m pip install -r requirements.txt
/__w/my-repo/my-repo/.tox/py39/bin/python: No module named pip.__main__; 'pip' is a package and cannot be directly executed
py39: exit 1 (0.03 seconds) 
/__w/my-repo/my-repo> python -I -m pip install -r requirements.txt pid=148
  py39: FAIL code 1 (0.13 seconds)
```

For context, I'm running the job inside a venv and i'm using `tox4` as CI front-end (also tried with tox version 3). The tox config looks like the following 

``` ini
[tox]
envlist = py{39,310}
isolated_build = true

[testenv]
deps =
    -r requirements.txt
commands =
    python -m build
    python -m twine check dist/*

```
I tried every possible solution including:
- adding `python3-pip` package in debian,  
-  running `python3 -m ensure-pip`, 
- running the custom `get-pip.py`.
- removing the default pip in the docker image.
 
But no success at all.

The build script looks like the following 
```bash
python3 -m venv venv
. ./venv/bin/activate
pip install -U pip tox4
tox -e py39
```
The workflow was tested on both on GitHub runners and self hosted runners. I've also tested with different python versions.

 I just wanted to just to make sure that i exhausted all possible combinations and maybe pin down the possible cause but i'm just stuck with the same error. 

Running the workflow directly on GitHub runner without the container works properly but we need to run as many jobs as possible on the self-hosted runners to control costs.

I really appreciate your help !

**Comment by antonblr** [comment]
@kafteji - it could help if you could paste the action snippet. I did a quick test with the following setup and it worked:
```yaml
python-flow:
  runs-on: ubuntu-latest
  container: python:3.9-slim-buster
  steps:
    - uses: actions/checkout@v3
    - run: |
        python3 -m venv venv
        . ./venv/bin/activate
        pip install -U pip tox4
        tox -e py39
```
I used `python:3.9-slim-buster` directly, as I don't have docker repo setup for custom images + I don't think the packages you're installing  affect python (unless the last line that updated pip index screws something up).
I put dummy `requirements.txt` with couple of packages and a bit simplified `tox.ini`:
```ini
[tox]
envlist = py{39,310}
isolated_build = true

[testenv]
deps =
    -r requirements.txt
commands =
    python -m pip --version
```
Action run succeeded and the final output is:
```
py39: commands[0]> python -m pip --version
pip 22.2.2 from /__w/my-repo/my-repo/.tox/py39/lib/python3.9/site-packages/pip (python 3.9)
```

**Reply by kafteji** [reply]
Hi @antonblr,

Thank you very much for your support !
my workflow file doesn't look really complicated. here it is.

```yaml
name: ci
on:
  pull_request:
  push:
    branches: [master]

jobs:
  verifier:
    runs-on: self-hosted
    container:
      image: private-repo/python:3.9-buster
      credentials:
        username: ${{secrets.private_repo_usr}}
        password: ${{secrets.private_repo_passwd}}
    steps:
        - uses: actions/checkout@v3
        - run: ./ci/build.sh
```

Where `build.sh` contains the build script mentioned above with the following shebang `#!/usr/bin/env bash`.

Surprisingly for me, i get the same errors with vanilla images (i.e python images from docker.io registry).

What made me scratch my head is when i changed the image to `python-3.8`, everything works just fine.

It tried also running the workflow without a venv, but i get the same error.

For me either some env is not set properly by GitHub runners or there is a bug in tox. It just doesn't make sense that the same code runs with `python 3.8` but not with later versions
