### DISCUSSION TITLE
Workflow not running for no apparent reason

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#34458] [Actions]
I have the following workflow file (the workflow file is on `master`)

```
name: Test Retrieval of Status Checks

on:
  push:
    branches:
      - mybranch

jobs:

  test-status-checks:
    name: Test Status Checks
    runs-on: ubuntu-latest

    steps:

      - run: echo "Test"
```

It definitely does not run when pushing to `mybranch`. Why is that?

Does it have to do with the fact I have a workflow file on `mybranch` with the exact same trigger?

```
name: Another workflow
on:
  push:
    branches:
      - mybranch
```
