### DISCUSSION TITLE
Why can't I publish from a Github Action Artifact to Artifactory?

### DISCUSSION THREAD

**Discussion by buzzbonner** [community/community#34586] [Actions]
After successfully creating a GitHub Action Artifact, I would like to push this to Artifactory. However, when running within the Workflow it fails to find the source Artifact. If I run this same Curl command to push to Artifactory from within Postman, using a local file system location, the operation completes successful.

Is there something wrong with my location definition of ${{ github.workspace }}/artifact/output/Linux_Deliveries.zip', which matches the GitHub Action path or could this be related to a GitHub Action permission?

  _**- name: Upload deliverable artifact to GitHub
      if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'pull_request'
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Linux_Deliveries.zip
        path: ${{ github.workspace }}/artifact/output
        if-no-files-found: error

  - name: Publish deliverable artifact to Artifactory
     if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'pull_request'
     run: curl -H 'Authorization:Bearer ${{ env.ARTIFACTORY_ACCESS_TOKEN }}' -X PUT '${{ env.ARTIFACTORY_URL }}/${{ env.ARTIFACTORY_REPOSITORY }}/${{ env.ARTIFACTORY_PROJECT_PATH }}/Linux_Deliveries.zip' -T '${{ github.workspace }}/artifact/output/Linux_Deliveries.zip' -v**_

**Result: curl: (26) Failed to open/read local data from file/application**

**Comment by airtower-luna** [comment]
I'm afraid your workflow excerpt got mangled beyond readability, please [use a Markdown code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to make it readable. Also context matters, if you can it's best if you share a link to the workflow file.

The error message looks like curl can't read the file though, so checking if the path is correct *and exists* is the first thing I'd do.

**Reply by buzzbonner** [reply]
Hi,

Unfortunately, I can't share the workflow as it's located in an unshareable location, but please see the updated code block below. Hope it's sufficient to show my problem.

The upload using path: ${{ github.workspace }}/artifact/output, and the artifact successfully exists.

The Curl command is also using ${{ github.workspace }}/artifact/output/Linux_Deliveries.zip, with the file name, so it looks correct? Am I missing something?

```
- name: Upload deliverable artifact to GitHub
      if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'pull_request'
      uses: [actions/upload-artifact@v2.2.4](mailto:actions/upload-artifact@v2.2.4)
      with:
        # Artifact name
        name: Linux_Deliveries.zip
        path: ${{ github.workspace }}/artifact/output
        if-no-files-found: error

       

  - name: Publish deliverable artifact to Artifactory
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'pull_request'
    run: curl -H 'Authorization:Bearer ${{ env.ARTIFACTORY_ACCESS_TOKEN }}' -X PUT '${{ env.ARTIFACTORY_URL }}/${{ 
      env.ARTIFACTORY_REPOSITORY }}/${{ env.ARTIFACTORY_PROJECT_PATH }}/Linux_Deliveries.zip' -T '${{ github.workspace 
      }}/artifact/output/Linux_Deliveries.zip' -v
```
