### DISCUSSION TITLE
Obtain run_id of completed workflow in workflow_run

### DISCUSSION THREAD

**Discussion by dpo** [community/community#34652] [Actions] [answered]
Hello. I'm working on an action that runs
```yaml
on:
  workflow_run:
    workflows: ["Trigger Phrase Workflow"]
    types: [completed]
```
I would like to get the list of artifacts generated during the run that triggered this workflow. Is there a way to recuperate that workflow's `run_id`? I don't see it in the `workflow_run` payload, but I may be looking at the wrong place. Any suggestion would be welcome!

Thanks!

**Comment by antonblr** [comment, marked as answer]
@dpo - here are all you need https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow, specifically:

```yaml
steps:
 - name: 'Download artifact'
    uses: actions/github-script@v6
    with:
      script: |
        let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
           owner: context.repo.owner,
           repo: context.repo.repo,
           run_id: context.payload.workflow_run.id,
        });
```
