### DISCUSSION TITLE
sed command not executing correctly on the ubuntu-latest runner

### DISCUSSION THREAD

**Discussion by harshjsca** [community/community#34659] [Actions] [answered]
I am doing token substitution in a Deploy to EKS pipeline, to set the Docker image tag as a git commit hash in the YAML file. 

Github action workflow step.

      - name: Deploy to eks
        run: |
          SERVICE_VERSION=`git rev-parse --short HEAD` && \
          sed -i.bak "s|SERVICE_VERSION|${SERVICE_VERSION}|g" deploy.yaml && \
          kubectl apply -f deploy.yaml

So instead of the substitution ending up like:

`my_image_name:2fb1c2c`

what I am actually getting is:

`my_image_name:`

For some reason sed is not replacing the value in yaml file.

**Comment by antonblr** [comment, marked as answer]
@harshjsca - Are you using `actions/checkout` - try setting [fetch-depth](https://github.com/actions/checkout#usage), i.e.:
```yaml
- uses: actions/checkout@v3
  with:
    fetch-depth: 10
```

**Reply by harshjsca** [reply]
Hi @antonblr Thank you for looking into this. I am getting the github commit hash by running `git rev-parse --short HEAD` on action step, which is returning the value in action output just fine but the problem is with sed command to replace the value in YAML file. 

Github action output.
Run set -x
```
++ git rev-parse --short HEAD
+ SERVICE_VERSION=296d86f
+ sed -i.bak 's|SERVICE_VERSION|296d86f|g' .k8s/deploy.yaml
+ kubectl apply -f deploy.yaml
deployment.apps/deploy configured
role.rbac.authorization.k8s.io/deploy-rbac unchanged
rolebinding.rbac.authorization.k8s.io/deploy-rbac unchanged

```
When I describe the deployment by running kubectl, I get the output `my_image_name: `instead of `my_image_name:296d86f`

**Reply by antonblr** [reply]
@harshjsca - I just did a quick test myself and it worked. Snippet:

deploy.yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-service
          image: my-image:SERVICE_VERSION

```

Action:
```yaml
name: Sed test
on: push

jobs:
  test-sed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          SERVICE_VERSION=`git rev-parse --short HEAD` && \
          sed -i.bak "s|SERVICE_VERSION|${SERVICE_VERSION}|g" deploy.yaml && \
          cat deploy.yaml
```

Output (note **image:**):
```
Run SERVICE_VERSION=`git rev-parse --short HEAD` && \
  SERVICE_VERSION=`git rev-parse --short HEAD` && \
  sed -i.bak "s|SERVICE_VERSION|${SERVICE_VERSION}|g" deploy.yaml && \
  cat deploy.yaml
  shell: /usr/bin/bash -e {0}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-service
          image: my-image:ee99626
```
