### DISCUSSION TITLE
How to add a wrapper text (prefix and suffix) to the issue template's form element in YAML configuration?

### DISCUSSION THREAD

**Discussion by MurzNN** [community/community#34785] [Projects and Issues]
I need to wrap a text, that is entered into the issue form's Textarea, by custom text (prefix and suffix), but can't find a way how to do this?

For example, I want to automatically hide a form element for long texts under collapsed `<details>` section, like this: https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab - how to do this?

**Comment by mfisher87** [comment]
I feel this feature would be _very_ valuable for [`conda-forge`'s issue templates](https://github.com/conda-forge/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug-report.yml). When people open a bug against a feedstock, we ask them to paste the output of some commands, including a full accounting of packages installed in their environment. In [some issues](https://github.com/conda-forge/quarto-feedstock/issues/30), that text can take up a lot of space, and I'd _love_ to have it collapsed into a `<details>` tag automatically as configured by e.g. a `render_template` field in the YAML:

```yaml
render_template: "<details><summary>Output of `conda list`</summary>{{response}}</details>"
```

**Comment by mdempsky** [comment]
The Go project would like this feature. We ask users to provide `go env` output because it's sometimes useful, but this pushes the more interesting text from the user's issue report below the fold, which then makes triage more tedious as we need to scroll up and down more.

**Comment by zhangt2333** [comment]
My workaround (provide a default value):

```yaml
  - type: textarea
    id: log
    attributes:
      label: Log
      description: |
        Provide the log output.
        _Note:_ You can paste the `output/tai-e.log` file into the placeholder below. If it is too long, you can attach it as a file.
      value: |
        <details>
          <summary>Click here to see Log</summary>
          <!-- Please leave one blank line below for enabling the code block rendering. -->

          ```
          The content of 'output/log.txt' file
          ```
        </details>
    validations:
      required: true
```
