### DISCUSSION TITLE
Environments and Matrix Deployments

### DISCUSSION THREAD

**Discussion by sohmc** [community/community#34831] [Actions] [answered]
I'm trying to figure out how to best to write my workflow.  I have a AWS Lambda Function that polls an API.  To call the endpoint, I need a token.  This token is stored as an environment variable in Lambda.  For the purposes of creating a CI/CD pipeline, the token is stored as a secret in an environment within my repository.

I have two environments: `development` and `production` with different tokens.

I am attempting to deploy the lambda and load the environment variables within one workflow.  I thought I could accomplish this with a matrix strategy:

```yaml
aws-deploy:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [16]
      environment: [development, production]

  environment: ${{ matrix.environment }}
```

Since both environments have branch protections (development is limited to branches starting with `dev-` and production is limited to the `main` branch), the matrix fails on the opposite branch that is being pushed.

If branch protections are removed, while the workflow runs, `production` gets released before quality checks can be completed.

My janky solution right now is to literally copy the entire job twice with an if statement

```yaml
aws-deploy-dev:
  if: startsWith(github.ref_name, 'dev-')
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [16]
      environment: [development]

  environment: ${{ matrix.environment }}

...

aws-deploy-prod:
  if: github.ref_name == 'main'
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [16]
      environment: [production]

  environment: ${{ matrix.environment }}
```

I'm sure there's something I've missed about making the same workflow run based on different branches.  The only other thing I can think of to do is to [reuse a workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows), which seems to create it's own set of problems like passing secrets and environment variables not reflecting the correct state.

What is the proper way to use the "Environments" feature?  [The documentation seems to limit the `Environment` syntax](https://docs.github.com/en/actions/using-jobs/using-environments-for-jobs) to the `jobs.<jobId>environment` context.

**Comment by antonblr** [comment, marked as answer]
Your "junky solution" is not that bad actually, given the current constraints. You might not need the `matrix` in that case (one node version, one environment) and make the environment explicit, i.e.  `environment: development`. 

But as I see it [Environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#about-environments) feature is geared more towards deployment pipelines:
>Environments are used to describe a general deployment target like production, staging, or development. When a GitHub Actions workflow deploys to an environment, the environment is displayed on the main page of the repository. 

Another option is to set your tokens in the Settings > Secrets > Actions with distinguished names, e.g. `AWS_LAMBDA_TOKEN_PROD`, `AWS_LAMBDA_TOKEN_DEV` and then select appropriate secrets in the job step:

```yaml
aws-deploy:
  runs-on: ubuntu-latest
  steps:  
    - name: Set AWS Token
      run: |
          if: startsWith(github.ref_name, 'dev-')
              echo "AWS_TOKEN=${{ secrets.AWS_LAMBDA_TOKEN_DEV }}" >> $GITHUB_ENV 
          elif github.ref_name == 'main'
              echo "AWS_TOKEN=${{ secrets.AWS_LAMBDA_TOKEN_PROD }}" >> $GITHUB_ENV 

    - name: Call Lambda API
      run: <use AWS_TOKEN>
 ```
