### DISCUSSION TITLE
Github actions not including matrix variable

### DISCUSSION THREAD

**Discussion by arunppsg** [community/community#34932] [Actions] [answered]
I have a github actions workflow like this:
```
name: Print test type
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        test_type: ['test-alpha', 'test-beta']
        os: [ubuntu-latest]
        python-version: ['3.7', '3.9']
        include:
        - os: windows-latest
          python-version: '3.8'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Print Alpha
      if: ${{ matrix.test_type == 'test-alpha'}}
      run: echo "test type is alpha. the os name is ${{ runner.os }}"
    - name: Print Beta
      if: ${{ matrix.test_type == 'test-beta'}}
      run: echo "test type is beta. the os name is ${{ runner.os }}"
```

When I run this workflow, the windows CI starts and completes but it is not showing any output. In particular, the if statements are not getting executed.  Am I missing some point here? Because when I include the `test-type` in matrix, I expect to also see windows X py3.8 X {alpha, beta} combination in workflow. 

In the ubuntu CI, it works fine - getting executed for all combinations in the matrix (ubuntu X {py3.7,py3.9} X {alpha,beta}.)
