### DISCUSSION TITLE
Login to GH hosted runner via SSH

### DISCUSSION THREAD

**Discussion by gucio321** [community/community#34968] [Actions]
Hi there!
Since debugging failed workflows is a bit painful, is it possible, to add possibility to log in into the failed workflow's runner? There is already such a feature implemented in CircleCI.

**Comment by gleatherman** [comment]
take a look at [tmate](https://github.com/mxschmitt/action-tmate)

**Comment by dfuentes77** [comment]
There really should be a secure and officially supported way to get ssh access to builds.

I've done this many years ago with CircleCI... and today it's immensely beneficial now while using Concourse CI and their [intercept](https://concourse-ci.org/builds.html#fly-intercept) feature, which drops you right into any container in the build task or pipeline.

I was shocked to learn that this is not already a standard feature in Github Actions.

In my experience, it significantly reduces the time needed when troubleshooting many build issues.

**Comment by kmcquade** [comment]
+1 on tmate. Here's some copypasta in case this is useful to someone. 

We use @mxschmitt's [tmate action](https://github.com/mxschmitt/action-tmate) with a conditional so that it only runs if the workflow fails on `workflow_dispatch` (that way tmate sessions don't kick off on PR syncs) and if `tmate_debug` is set to true in the input. This avoids unintentional run-offs but allows us to shell into failed workflows.

```yaml
      - name: tmate session if tests fail
        uses: mxschmitt/action-tmate@v3
        if: failure() && github.event_name == 'workflow_dispatch' && inputs.tmate_debug
```

You can slice the `inputs.tmate_debug` if you want. If you want to keep it, you'll have to include it at the inputs at the top of your workflow file:

```yaml
on:
  workflow_dispatch:
      tmate_debug:
        description: whether to start a tmate SSH session if tests fail
        required: false
        type: boolean
        default: false
```

Hope this helps someone!
