### DISCUSSION TITLE
[ISSUE] `compose.yml` -> `security_opt` requires absolute path to `seccomp` file

### DISCUSSION THREAD

**Discussion by snebjorn** [community/community#34979] [Codespaces]
When specifying a seccomp file in a docker compose file only the absolute path works.
This is not intuitive and in stark contrast to `dockerfile: Dockerfile` which is scoped to the `.devcontainer` folder

```yml
# compose.yml
services:
  app:
    security_opt:
      - seccomp:/var/lib/docker/codespacemount/workspace/<repo-name>/.devcontainer/<seccomp-file>.json
```

Not tried it. But I doubt that path will work when spinning up the devcontainer locally instead of in Codespaces.

Edit:
I tried it locally and that path does not work
