### DISCUSSION TITLE
Use manual inputs as matrix strategy in workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#34993] [Actions] [answered]
I want to create a manually triggered workflow that builds images for several versions of python.

How should I set up my input so that I create a matrix strategy for all the python versions?

i.e. if my input is something like the following:

```
name: Build images

on:
  workflow_dispatch:
    inputs:
      python_versions:
        description: comma separated list of python versions to use for the build process
        required: true
        type: string
        default: 3.8,3.9,3.10
```

How should I invoke the corresponding job so that it runs for each python version passed?

**Comment by airtower-luna** [comment, marked as answer]
You could use `fromJSON()` within the matrix definition, maybe something like:

```yaml
    strategy:
      matrix:
        python_version: ${{ fromJSON(inputs.python_version) }}
```

But for that to work the input would have to be valid JSON, e.g. for your current default: `["3.8", "3.9", "3.10"]` Mind that you'd need to wrap it in single quotes in the YAML to keep it a string (and not a list).

If you want a different input format (like the comma-separated list in your example) you'll probably have to add a pre-processing job that provides valid JSON for the list as an output.
