### DISCUSSION TITLE
GitHub Action using wrong version of Ruby

### DISCUSSION THREAD

**Discussion by CodeMeister** [community/community#35109] [Actions] [answered]
in my workflow I have:

```
name: Ruby 3.0

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/ruby-3-0.gemfile
    steps:
      - uses: actions/checkout@v3
   
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true 

      - name: Run tests
        run: bundle exec rake
```

It install fine, but crashes when running Spec:
```
/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/ruby -I/home/runner/work/encoded_token/encoded_token/vendor/bundle/ruby/3.1.0/gems/rspec-core-3.11.0/lib:/home/runner/work/encoded_token/encoded_token/vendor/bundle/ruby/3.1.0/gems/rspec-support-3.11.1/lib /home/runner/work/encoded_token/encoded_token/vendor/bundle/ruby/3.1.0/gems/rspec-core-3.11.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
```
The test is crashing because it is being run under Ruby 3.1 and not Ruby 3.0.

Where did I go wrong?
