### DISCUSSION TITLE
Dynamic matrix fails to be created in workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#35114] [Actions] [answered]
I have the following workflow that creates a dynamic matrix

```
jobs:
  create-python-matrix:
    name: create the matrix of python versions
    runs-on: ubuntu-latest

    outputs:
      python_builds: ${{ steps.set-python-matrix.outputs.python_builds }}
    
    steps:

      - name: output of python versions
        id: set-python-matrix
        shell: bash
        run: echo set-output name=python_builds::$(echo '"${{ inputs.python_versions }}"' | jq -c 'split(",")')


  build-python-images:
    name: build the python images
    runs-on: ubuntu-latest
    needs: create-python-matrix
    strategy:
      matrix:
        python-builds: ${{ fromJSON(needs.create-python-matrix.outputs.python_builds) }}
      fail-fast: true

    steps:

      - name: validate the matrix
        shell: bash
        run: echo ${{ matrix.python-builds }}
```

I see in the logs that the output is set correctly

```
set-output name=python_builds::["3.8","3.9","3.10"]
```

However the workflow fails as follows:

```
Build python base images: .github#L1
Error when evaluating 'strategy' for job 'build-python-images'. .github/workflows/my_workflow.yaml (Line: 45, Col: 24): Error parsing fromJson,.github/workflows/my_workflow.yaml (Line: 45, Col: 24): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/my_workflow.yaml (Line: 45, Col: 24): Unexpected type of value '', expected type: Sequence.
```

Why is that?
