### DISCUSSION TITLE
Only run action on external pull request

### DISCUSSION THREAD

**Discussion by agostbiro** [community/community#35156] [Actions]
Hi,

I've the following Github Action trigger in [my repo:](https://github.com/sealvault/sealvault/blob/054a1751380ef5daeb8abfbb5382afd850a557fe/.github/workflows/ci.yml#L2)

```
on: [push, pull_request]
```

My intention was that the CI runs on every commit in the repo and if there is a pull-request from a fork, I have the option to run the CI for that. Instead now when I open a PR in the repo from a branch in the repo, the CI runs two times simultaneously: one for the push and one for the PR. How could I achieve my original intention?

Thanks,
Agost

**Comment by amithm7** [comment]
Use a conditional for the CI job.

```yaml
env:
  # Base for the PR
  BASE_REPO: ${{ github.event.pull_request.base.repo.clone_url }}

  # Repository of PR
  PR_HEAD_REPO: ${{ github.event.pull_request.head.repo.clone_url }}

jobs:
  ci-job:
    # if external PR
    if: ${{ env.BASE_REPO != env.PR_HEAD_REPO }}
    # do your thing
```
