### DISCUSSION TITLE
Workflow not triggered using workflow_run when brackets "[]" in workflow name

### DISCUSSION THREAD

**Discussion by whanschke** [community/community#35316] [Actions]
We are trying to set up a build and deploy workflow chain. The deploy should trigger when the build completed. I have stumbled upon the issue that when square brackets are used in the build workflow the deploy workflow does not run. I haven't found that kind of restriction anywhere in the documentation. Anyone knows what the specific restrictions are?
Here is an example:
This **works** perfectly
build workflow
``` 
name: Test build workflow

on:
  pull_request:
    branches:
      - master
  release:
    types: published

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: say hello
        run: echo "hello world!"
```
deploy workflow
``` 
name: Test deploy workflow

on:
  workflow_run:
    workflows: ['Test build workflow']
    types:
      - completed

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: say hello
        run: echo "hello world!"
```

This does **not work**
build workflow
``` 
name: "[B] Test build workflow"

on:
  pull_request:
    branches:
      - master
  release:
    types: published

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: say hello
        run: echo "hello world!"
```
deploy workflow
``` 
name: Test deploy workflow

on:
  workflow_run:
    workflows: ['[B] Test build workflow']
    types:
      - completed

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: say hello
        run: echo "hello world!"
```
