### DISCUSSION TITLE
How to use a configuration file for reusable actions.

### DISCUSSION THREAD

**Discussion by terabytesoftw** [community/community#35326] [Actions]
I have a reusable action, which uses a configuration file, how to centralize the configuration file in the repository of reusable actions is possible,

Example
```yml
- use: /user/actions/my-action.yml
  with:
    path: /user/actions/config.yml
```

Thks.
