### DISCUSSION TITLE
inputs context not working for concurrency group

### DISCUSSION THREAD

**Discussion by dkirrane** [community/community#35341] [Actions] [answered]
When run the below workflow throws `The workflow is not valid. .github/workflows/run.yml (Line: 14, Col: 10): Unexpected type of value '', expected type: String.` for the below workflow. 
Any ideas?

```yaml
name: Run

on:
  workflow_dispatch:
    inputs:
      workspace:
        type: choice
        required: true
        options: ["dev-19"]
        default: "dev-19"

run-name: Run ${{ inputs.workspace }}
concurrency:
  group: ${{ inputs.workspace }}
  cancel-in-progress: false

jobs:

  Run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workspace = ${{ inputs.workspace }}"
```

Based on the [docs](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability) the `inputs` context should be available for the `concurrency` workflow key

I have also tried the one liner `concurrency: ${{ inputs.workspace }}` and get
`The workflow is not valid. .github/workflows/run.yml (Line: 13, Col: 14): Concurrency group name cannot be empty`

**Comment by fadyat** [comment]
Hey @dkirrane!
The concurrency expression can only use the [github context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).

[About concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)

In default you can write in '' or without them:
Probably, it's should be something, like this:

```yml
name: Run

on:
  workflow_dispatch:
    inputs:
      workspace:
        type: choice
        required: true
        options: ["dev-19"]
        default: dev-19

run-name: Run ${{ inputs.workspace }}
concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workspace = ${{ inputs.workspace }}"
```

**Reply by dkirrane** [reply]
@fadyat based on the table it looks like it should be available right? https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

![image](https://user-images.githubusercontent.com/1280116/194380525-2a5eb887-962e-4fe9-bd20-327476ad7eb5.png)

**Reply by fadyat** [reply]
Hmm...

**Reply by fadyat** [reply]
Yeah, you are right.
But I can't find more information about 'concurrency' and 'inputs'.

Probably, it's a mistake in a table.

Do you really need a 'inputs.workspace' in 'concurrency'?

**Reply by JasonRSeequent** [reply]
I agree that the documentation is wrong, I managed to access the inputs in the workflow from the github context, e.g.
`concurrency: ${{ github.event.inputs.workspace }}`

**Comment by fadyat** [comment, marked as answer]
@dkirrane `inputs` will work, if you will use `concurrency` inside of `jobs` block:
```yml
on:
  workflow_dispatch:
    inputs:
      workspace:
        type: choice
        required: true
        options: ["dev-19"]
        default: dev-19

run-name: Run ${{ inputs.workspace }}
jobs:
  Run:
    concurrency:
      group: ${{ inputs.workspace }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workspace = ${{ inputs.workspace }}"
```

**Reply by dkirrane** [reply]
Perfect that works thanks.
And it works with Jobs defining  reusable workflows too. So that solves my issue.

**Reply by fadyat** [reply]
You are welcome 😄 !

**Reply by benjamin-bergia** [reply]
@fadyat Is this the only way? Like @dkirrane I set the concurrency at the workflow level in my reusable workflows. I was hoping to hide it away in my reusable workflow definition so that users calling my workflow wouldn't have to bother with concurrency.

**Reply by robertjpayne** [reply]
@dkirrane You can actually access some inputs if they're available in the `event` payload. The documentation states only the `github` context is available in the concurrency group but for workflow_dispatch you can do:

`${{ github.event.workflow_dispatch.inputs.<name>}}` because the `event` payload is everything that webhooks would get sent on the event too!

**Reply by DSdatsme** [reply]
I had a workflow that works on the `workflow_dispatch` event.

After several combinations, I was able to make it work by using the following concurrency config at the **workflow** level

```yaml
concurrency:
  # INFO: ensures only one instance of this job(group) is running per app.
  group: ${{ github.workflow }}---${{ github.event.inputs.appName }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'Name of the App you want to deploy.'
        required: true
```

`${{ github.event.workflow_dispatch.inputs.appName}}` didn't work for me.

**Reply by sirajulm** [reply]
@DSdatsme Are you sure it works?
I tried a slightly different variation like below, which complain
```yaml
concurrency:
  group: ${{ github.event.inputs.appName }}
```

Error:
> Error when evaluating 'concurrency' .github/workflows/reusable.yml@07eb0813fd0558814c05ba9c0a2a9ffee8b6c1c1 (Line: 4, Col: 10): Unexpected type of value '', expected type: String.

What I assume is that in your case again it is the same and the group is evaluated to `Workflow Name---`


**Answering to my own question:**
`workflow_dispatch` uses `github.event.inputs.*` and `workflow_call` uses `inputs.*`, which makes sense.

**Reply by DSdatsme** [reply]
Hey @sirajulm 
Yea It works in my case
this is the demo you can try it by yourself.
https://github.com/DSdatsme/slack-action-test/actions/workflows/concurrency-test.yaml
<img width="892" alt="Screenshot 2023-03-08 at 5 00 53 PM" src="https://user-images.githubusercontent.com/23118559/223702389-5a514441-90af-4775-bede-a3e8532c33a4.png">

For testing I ran 3 instances of `dsdatsme` and the second instance went in queue and eventually got canceled which is an expected behaviour.

<img width="1091" alt="Screenshot 2023-03-08 at 5 01 24 PM" src="https://user-images.githubusercontent.com/23118559/223702491-976cb5f6-54eb-46b2-9448-3a3a0812be45.png">

**Reply by sirajulm** [reply]
Hello @DSdatsme
Thank you for providing the sample. It works for me
I had a `workflow_call` and `workflow_dispatch` in the same workflow for some specific reason. Problem was with the difference on how I should access the `input` in both cases. 🙂

**Comment by Marcin-Lach** [comment]
Seems to be working now with `inputs`

Tested with this workflow:

```yaml
name: Concurrency

run-name: Concurrency ${{ inputs.environment }}

concurrency:
  group: concurrency-${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Some env
        type: choice
        default: team1
        options:
        - team1
        - team2
        - team3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run from ${{ inputs.environment }}
      run: sleep 30s
```
