### DISCUSSION TITLE
`paths` and `paths-ignore` are not complements

### DISCUSSION THREAD

**Discussion by dimaqq** [community/community#35379] [Actions]
Hi, I wanted to use the suggested hack to allow skipping jobs and yet follow the branch protection rules by following this guide:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

But quickly realised that `paths:` and `paths-ignore:` are not complements.

For example:
```yml
# workflow 1
name: Ignorant

on:
  push:
    paths-ignore:
      - "ig/**"

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "You won't ignore this"

# workflow 2
name: Knowledgeable

on:
  push:
    paths:
      - "ig/**"

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered on ig"
```

If I make a commit that changes stuff both inside and outside the path spec, like so:

```
commit 58459e76ea6a77d9ec13a28015b994b0db7023ca (HEAD -> try-both-dirs, origin/try-both-dirs)
Author: Dima Tisnek <dimaqq@gmail.com>
Date:   Fri Oct 7 08:28:06 2022 +0900

    change both

ig/f.txt
og/f.txt
```

GHA happily runs both Knowledgeable and Ignorant workflows, which poses the question, which `test1` job is actually used to satisfy branch protection rules:
- any must pass?
- both must pass?
- the faster must pass?
- the slower must pass?

Surely others ran into this before.
What am I missing?
