### DISCUSSION TITLE
How to trigger github actions on update pull request

### DISCUSSION THREAD

**Discussion by tomasz90** [community/community#35528] [Actions]
How to trigger github actions on update pull request, I tried to use this:

```
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    types: [ assigned, opened, reopened, synchronize, edited ]
```

But apparently it doesnt work..

**Comment by fadyat** [comment]
that works for me:
```
on:
  push:
    branches: [ "$default-branch" ]
  pull_request:
    branches: [ "$default-branch" ]
```
