### DISCUSSION TITLE
Docker build / push action not consuming secrets

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#35542] [Actions]
Trying to reproduce [this](https://github.com/docker/build-push-action/blob/master/docs/advanced/secrets.md) example from the official documentation of the docker push/build action.

I am using the following `Dockerfile`

```
# syntax = docker/dockerfile:1.3

FROM alpine:3.14

RUN --mount=type=secret,id=JFROG_PASS \
  cat /run/secrets/JFROG_PASS


RUN wget --user ${JFROG_USER} --password ${JFROG_PASS} "https://my/jfrog/binary" 
```

and executing the following action

```
      - name: build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          no-cache: ${{ inputs.no_cache }}
          build-args: ${{ inputs.build_args }}
          secrets: |
            "JFROG_PASS=${{ secrets.MY_PASSWORD }}"
          push: true
          tags: ${{ env.LOCAL_IMAGE }}
```

However, the process of `mount` fails as follows:

```
#9 [stage-0 2/8] RUN --mount=type=secret,id=JFROG_PASS   cat /run/secrets/JFROG_PASS
#0 0.062 cat: can't open '/run/secrets/JFROG_PASS': No such file or directory
#9 ERROR: process "/bin/sh -c cat /run/secrets/JFROG_PASS" did not complete successfully: exit code: 1
------
 > [stage-0 2/8] RUN --mount=type=secret,id=JFROG_PASS   cat /run/secrets/JFROG_PASS:
#0 0.062 cat: can't open '/run/secrets/JFROG_PASS': No such file or directory
------
Dockerfile:5
--------------------
   4 |     
   5 | >>> RUN --mount=type=secret,id=JFROG_PASS \
   6 | >>>   cat /run/secrets/JFROG_PASS
   7 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cat /run/secrets/JFROG_PASS" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c cat /run/secrets/JFROG_PASS" did not complete successfully: exit code: 1
```

Why is that?
