### DISCUSSION TITLE
`contains()` function not working

### DISCUSSION THREAD

**Discussion by bend-n** [community/community#35621] [Actions] [answered]
I have this workflow:
```yaml
name: Test

on:
  push:

jobs:
  make-afterburners:
    runs-on: ubuntu-latest
    if: contains('afterburners', 'afterburners') == 'true' # this job should run
    steps:
      - run: echo ${{ github.job }}
  make-fuel:
    runs-on: ubuntu-latest
    if: contains('afterburners', 'fuel') == 'true' # this job should skip
    steps:
      - run: echo ${{ github.job }}
```

As far as i can tell, the `contains()` functions should succeed.
However, in reality, the workflow is simply skipped altogether. Why is the `make-afterburners` job not running?
