### DISCUSSION TITLE
Reusable workflows not generating Annotations in PR

### DISCUSSION THREAD

**Discussion by adcharre** [community/community#35663] [Actions] [answered]
I have a linting workflow that generates annotations when it's part of the same repo as the pull request its run against, but I'd like to turn this into a reusable workflow so that I can use it across multiple similar repositories. 

I've got reusable workflows running for my repos for building and when I add the linting workflow it runs and I can see it's generating messages which GitHub is recognising as errors/warnings/notices from the action log. However those messages never appear in the PR as they do when the workflow is part of the same repo?

What am I doing wrong or is this something that's not supported?

This works:

```yaml
jobs:
  build:
    uses: cie/workflows/.github/workflows/module_build.yml@main
      
  lint:
    runs-on: [ self-hosted ]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: TFLint config Checkout
        uses: actions/checkout@v2
        with:
          repository: cie/workflows
          path: .tflint
          ref: tflint
      - uses: 3rd-Party-Actions/setup-tflint@v2
      - name: Lint module code 
        run: |
          cp .tflint/module.tflint ~/.tflint.hcl
          tflint --init
          tflint -f compact src
```

This doesn't add annotations when I include it in module_build.yml workflow:
```yaml
name: Workflow to build and publish modules to terrarium
on:
  workflow_call:

jobs:
  lint:
    runs-on: [ self-hosted ]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: TFLint config Checkout
        uses: actions/checkout@v2
        with:
          repository: cie/workflows
          path: .tflint
          ref: tflint
      - uses: 3rd-Party-Actions/setup-tflint@v2
      - name: Lint module code 
        run: |
          cp .tflint/module.tflint ~/.tflint.hcl
          tflint --init
          tflint -f compact src

  build:
    runs-on: [ self-hosted ]
....
```

I should mention that this is on a GitHub Enterprise server v3.5.3
