### DISCUSSION TITLE
When publishing github packages it will auto generate descriptions

### DISCUSSION THREAD

**Discussion by fyang86** [community/community#35666] [Packages]
I'm publishing Java packages with Gradle for my project. When the package is published, an unexpected description will generate. It seems like the description came from one of its dependencies. Also I didn't find an approach to config the description of the package, so is this a bug or something I have missed?

Related package: https://github.com/fyang86/flink-connectors/packages/1443980
Clearly you can see the description is from guava.

Workflow:
```
jobs:
  build:
    ...
    ...
    ...
  snapshot:
    name: Publish snapshot to Github Packages
        needs: [build]
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/r0.') || startsWith(github.ref, 'refs/heads/r1.')) }}
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        steps:
            # gradle packages that need to be cached
          - name: Cache gradle modules
            uses: actions/cache@v2
            with:
              path: |
                .gradle
                $HOME/.gradle
                $HOME/.m2
              key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    
            # publish the artifact from the build cache
          - name: Cache build outputs
            uses: actions/cache@v2
            with:
              path: ./*
              key: ${{ github.run_id }}
    
          - name: Publish to Github Packages
            run: ./gradlew publish -PpublishUrl=https://maven.pkg.github.com/${{github.repository}} -PpublishUsername=${{github.actor}} -PpublishPassword=${{secrets.GITHUB_TOKEN}}

```
