### DISCUSSION TITLE
ubuntu-latest shows version 14.04

### DISCUSSION THREAD

**Discussion by boroda4436** [community/community#35688] [Actions] [answered]
Hello everyone! 

I am using github actions config like this one:
```
on: [create, workflow_dispatch]

name: Deploy CI CodePipeline stack for branch

jobs:
  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

.... skipped last
```

And in logs I can see that the version of Ubuntu is 14.04 which is pretty old.
<img width="750" alt="image" src="https://user-images.githubusercontent.com/13794896/194878965-c2e08411-1e6e-4538-9dee-edef285e19fc.png">

The question is: how can I use latest version, for example 18.04 or 20.04?
Next way is not forking for me, I'm still receiving 14.04 in logs...
```
on: [create, workflow_dispatch]

name: Deploy CI CodePipeline stack for branch

jobs:
  deploy:
    name: Deploy stack
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

.... skipped last
```
