### DISCUSSION TITLE
Release type "edited" is failing to trigger workflow

### DISCUSSION THREAD

**Discussion by connorhsm** [community/community#35706] [Actions]
Given the below workflow:
```
name: test flow

on:
  release:
    types: edited
  workflow_dispatch:

jobs:
  something:
    runs-on: ubuntu-latest
    steps:
      - run: echo 1
```

The workflow will not trigger when I edit a release on the repository. The release was created manually. I have tried updating the assets, release body, release title and nothing.

I have attempted to find similar questions or issues online, without any luck.

Is there something I am doing wrong or another way I could do this?
