### DISCUSSION TITLE
Settings text as result of expression

### DISCUSSION THREAD

**Discussion by Cyb3r-Jak3** [community/community#35711] [Actions] [answered]
I have a workflow in which I am trying to set a variable for an action best on an evulation in an expresssion.
Example:
```yaml
name: Docker Images

on:
  push:
    branches:
      - '**'
    tags:
      - "v*"
    paths:
      - .github/workflows/docker.yml
      - "Dockerfile"

jobs:
  docker:
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "docker-arm"]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/cyb3r-jak3/workerd-cache
        cache-to: type=registry,mode=max,ref=ghcr.io/cyb3r-jak3/workerd-cache
        platforms: ${{ 'linux/arm64' if matrix.runs-on == 'docker-arm' else 'linux/amd64' }}
````
However when I try I get the following error `Unexpected symbol: 'if'. Located at position 15 within expression: 'linux/arm64' if matrix.runs-on == 'docker-arm' else 'linux/amd64'`.
Is what I am doing even possible and if so then how would I do it?
