### DISCUSSION TITLE
env.GITHUB_WORKSPACE not defined at job.env context, Does it make sense?

### DISCUSSION THREAD

**Discussion by kuisathaverat** [community/community#35739] [Actions] [answered]
I was trying to define an environment variable global to a job using `env.GITHUB_WORKSPACE` as a component, but I found that `env` is not available at `job.env` context which is a little weird to me. The error is the following:

```
Unrecognized named-value: 'env'. Located at position 1 within expression: env.GITHUB_WORKSPACE
```

My workflow looks like this, I define an environment at `job.env` to use it across several steps in the job

```
  process:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: 
          - file01
          - file02
    env:
     CONFIG_FILE: "${{ env.GITHUB_WORKSPACE }}/${{ matrix.filename }}"
    steps:
      - run: cat ${CONFIG_FILE}
      - run: mv ${CONFIG_FILE} foo
      - run: rm foo
```

The alternative is to define the environment variable on each step that uses it, this is verbose if you have a bunch of steps that use that environment variable.

```
  process:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: 
          - file01
          - file02
    steps:
      - run: cat ${CONFIG_FILE}
         env:
           CONFIG_FILE: "${{ env.GITHUB_WORKSPACE }}/${{ matrix.filename }}"
      - run: mv ${CONFIG_FILE} foo
         env:
           CONFIG_FILE: "${{ env.GITHUB_WORKSPACE }}/${{ matrix.filename }}"
      - run: rm foo
```

So to avoid repeating the definition of the environment variable on each step (that does not make any sense), I have added a step that adds the environment variable to GITHUB_ENV. It is a workaround IMHO, a little forced. It is clear to define that environment variable in the `job.env` context, it is more clear when you read the YAML file.

```
  process:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: 
          - file01
          - file02
    steps:
      - run: echo "CONFIG_FILE=${{ env.GITHUB_WORKSPACE }}/${{ matrix.filename }}" >> $GITHUB_ENV
      - run: cat ${CONFIG_FILE}
      - run: mv ${CONFIG_FILE} foo
      - run: rm foo
```

**Comment by ChristopherHX** [comment, marked as answer]
Consider replacing `env.GITHUB_WORKSPACE` with `github.workspace`, then you are no longer using the not allowed context.

See docs https://docs.github.com/en/actions/learn-github-actions/contexts#github-context.

`GITHUB_WORKSPACE` is automatically created from the `github` context, but only for steps and I think you can never access it from the `env` context.

**Reply by kuisathaverat** [reply]
I did not see it 🤦‍♂️ 

```
  process:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: 
          - file01
          - file02
    env:
     CONFIG_FILE: "${{ github.workspace }}/${{ matrix.filename }}"
    steps:
      - run: cat ${CONFIG_FILE}
      - run: mv ${CONFIG_FILE} foo
      - run: rm foo
```
