### DISCUSSION TITLE
Can't reuse local workflows

### DISCUSSION THREAD

**Discussion by TheHumbleJester** [community/community#35734] [Actions]
Hello I tried to reuse a local workflow as mentioned in the [doc](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow) but I aways get the following error:

`error parsing called workflow "./.github/workflows/validate.yml": invalid value workflow reference: references to workflows must be rooted in '.github/workflows'`

Here's my configuration:

`.github/workflows/validate.yml` (the reusable workflow):
```
name: Validate
on: workflow_call
jobs:
  checkout-code:
    name: Checkout code
    uses: actions/checkout@v3
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    container: node:lastest
    steps:
      - run: yarn  
  build:
    name: Build
    runs-on: ubuntu-latest
    container: node:lastest
    steps:
      - run: yarn build
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: node:lastest
    steps:
      - run: yarn test
  store-artifacts:
   name: Store artifacts
   uses: actions/upload-artifacts@v3
   with:
    name: code
    path: "."
```

`.github/workflows/validate-branch.yml`:
```
name: Validate branch
on:
  push:
    branches:
      - "!master"
jobs:
  validate:
    uses: ./.github/workflows/validate.yml
```

Do you see what is problematic here?

Thank for your help!
