### DISCUSSION TITLE
cannot install `g++-12` in matrix

### DISCUSSION THREAD

**Discussion by scarf005** [community/community#35765] [Actions] [answered]
using this [workflow](https://github.com/scarf005/Cataclysm-BN/actions/runs/3226515844/workflow), I try to install `g++-12`
```yaml
    - name: install missing compiler (ubuntu)
      if: ${{ env.SKIP == 'false' && runner.os == 'Linux' && matrix.compiler == 'g++-12' }}
      run: |
          echo my compiler is ${{ matrix.compiler }}
          sudo apt-get install ${{ matrix.compiler }}
          ${{ matrix.compiler }} --version
```
however, although `matrix.compiler == 'g++-12'`, it just says `clang-12` is latest, then continues to install random packages. but... how?!
```
my compiler is g++-12
Reading package lists...
Building dependency tree...
Reading state information...
clang-12 is already the newest version (1:12.0.0-3ubuntu1~20.04.5).
The following additional packages will be installed:
  fonts-mathjax libjs-mathjax
Suggested packages:
  fonts-mathjax-extras fonts-stix libjs-mathjax-doc
The following NEW packages will be installed:
  clang-12-doc clang-12-examples fonts-mathjax libclang-12-dev libjs-mathjax
  python3-clang-12
0 upgraded, 6 newly installed, 0 to remove and 41 not upgraded.
Need to get 28.5 MB of archives.
```

full log: https://github.com/scarf005/Cataclysm-BN/actions/runs/3226515844/jobs/5280129606
