### DISCUSSION TITLE
Deploy node based Jekyll Site to gh-pages

### DISCUSSION THREAD

**Discussion by zakraicik** [community/community#35803] [Actions]
**I have seem similar threads, but none that I can figure out how to use to solve this problem**. 

Trying to deploy a site to github pages using this [template](https://github.com/CloudCannon/vonge-jekyll-bookshop-template/issues) . I can build and run the site locally.  The site uses node to develop custom jekyll plugins, which is why a deployment method like this is required. 

I wrote this `.yml` file to build and deploy the site to `gh-pages`. 

```
name: Build and Deploy to Github Pages

permissions:
  id-token: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Setting up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci

    - name: Setting up Ruby
      uses: actions/setup-ruby@v1
      with: { ruby-version: '3.1.2' }

    - name: Caching Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Build Site 🏗️
      run: npm run install-jekyll 
      env:
        NODE_ENV: production

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with: 
        path: "./site/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```

Everything appears to work and deploy fine, but when I go to zakraicik.github.io, it shows 404. Can someone help me modify my `.yml` file to deploy correctly? 

Full repo [here](https://github.com/zakraicik/zakraicik.github.io).
