### DISCUSSION TITLE
Error while creating comment: Resource not accessible by integration

### DISCUSSION THREAD

**Discussion by schalkneethling** [community/community#35827] [Actions] [answered]
Hey All,

Working on a workflow that will comment on both issues and pull requests. I am using the default `GITHUB_TOKEN`, so I know I will need to configure additional permissions for it to be able to comment on pull requests that come from forks. With that said, from [this document](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token), it looks like it should have write access to issues.

When my action runs, it fails with: `Error while creating comment: Resource not accessible by integration`. Your assistance will be appreciated. 

An example of a failed run can be seen here: https://github.com/schalkneethling/allo-allo/actions/runs/3230427280
The code for the action can be seen here: https://github.com/schalkneethling/allo-allo/blob/main/allo-allo.js

**Comment by schalkneethling** [comment, marked as answer]
Turns out the example I was referencing for some guidance had the [same problem](https://github.com/actions/first-interaction/issues/10#issuecomment-1232740076). It seemed like the default `GITHUB_TOKEN` would have worked as is, but you have to give it explicit write access.

```yml
jobs:
  AlloAllo:
    name: A job to say hello
    runs-on: ubuntu-latest

    permissions:
          issues: write
          pull-requests: write
```
