### DISCUSSION TITLE
Migrating `::set-output` to environment files

### DISCUSSION THREAD

**Discussion by patriksvensson** [community/community#35892] [Other Feature Feedback, Questions, & Ideas] [answered]
I'm suddenly getting the following warning in my scripts where I use `::set-output:`

```
Warning: The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files. 
For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

The documentation isn't really clear on how to do this.
How do I write to the environment file from something other than a shell, such as C# script?

**Comment by LayZeeDK** [comment, marked as answer]
# Option A: Bash
Use stdout in the following format when using Bash:
```powershell
echo "output_name=output-value" >> $GITHUB_OUTPUT
```

Execute this terminal command from a script in any programming language or using a `run` step.

# Option B: JavaScript or TypeScript
Use the `@actions/core` API:
```typescript
import * as core from '@actions/core';

core.setOutput('output_name', 'output-value');
```

# Option C: C# script
Use `Environment.SetEnvironmentVariable` to append an output value to the `GITHUB_OUTPUT` environment variable:
```csharp
using System;

Environment.SetEnvironmentVariable("GITHUB_OUTPUT", Environment.GetEnvironmentVariable("GITHUB_OUTPUT") + "\n" + "output_name=output-value");
```
(Let me know if this option works)

See [C# solution by @patriksvensson](https://github.com/orgs/community/discussions/35892#discussioncomment-4108136).

**Reply by deitry** [reply]
~~What is the proposed way for steps on Windows runners? It seems that new approach is not working for them, but old is already deprecated~~
~~https://github.com/deitry/test-output/actions/runs/3249439554/jobs/5331843290~~

```yml
      - id: step1
        run: echo "test=Hello world" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.step1.outputs.test }}"
```

~~I tried to make pwsh-style assignment, but it doesn't help~~
~~https://github.com/deitry/test-output/actions/runs/3249564786/jobs/5332111714~~

Thanks to this [comment](https://github.com/orgs/community/discussions/35994#discussioncomment-3889595), correct way for pwsh is
```yml
      - id: step1
        run: |
          "test=`"Hello world`"" >> $env:GITHUB_OUTPUT

      - run: echo "${{ steps.step1.outputs.test }}"
```
