### DISCUSSION TITLE
How to render a png image in GITHUB_STEP_SUMMARY

### DISCUSSION THREAD

**Discussion by atemate** [community/community#35932] [Actions]
I'm trying to render an image produced by my step in the GITHUB_STEP_SUMMARY markdown. I could embed the image, but it's [not possible](https://github.com/github/markup/issues/270) due to security reasons.

Otherwise, I could use the context of the build step:

```yaml
      - id: build
        run: ...  # produces ./plot.png
      - id: set-summary
       run: |
          echo "# Experiment" >> $GITHUB_STEP_SUMMARY
          echo "![plot](plot.png)" >> $GITHUB_STEP_SUMMARY
```
However, it doesn't work:
![image](https://user-images.githubusercontent.com/7501517/195400752-a535e3b5-d6a1-40e4-b582-9ee6ad2f8909.png)

Alternatively, I could use [actions/download-artifact](https://github.com/actions/download-artifact), but I don't know how. 

Also, I don't want to put this file to a public s3 due to privacy concerns (can GH actions load from protected s3?)

--
How can I embed an image to the step summary?
