### DISCUSSION TITLE
Github Action Manual Approval

### DISCUSSION THREAD

**Discussion by aarvi13** [community/community#35939] [Actions]
Hello team,

In our organization, we are having monorepo with inside 20 more projects. We need to do like manual approval for each job. but, in GitHub, we have to create an environment to approve the build to deploy. So, 20 projects mean I need to create 20 environments. can you please any other way we can do a manual deployment for each project one by one?

If I approve one project means that project alone needs to deploy. Can you please help us out?

**Comment by DarylLyonsLF** [comment]
Hi @aarvi13,

You can define a single environment with required reviewers and re-use this across each of your project workflows. Since it looks like your projects are building and deploying independently, it sounds like you will require 20 distinct workflows (or 20 distinct jobs within a single workflow) which can all share an environment.

```yaml
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    # here is where your environment is defined (one per job)
    environment: my_environment
```

See https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment for additional information on this.

Hope this helps.
