### DISCUSSION TITLE
Action fails to post comment on pull request

### DISCUSSION THREAD

**Discussion by schalkneethling** [community/community#35973] [Actions] [answered]
I have read a ton about the limitations and ways to enable actions to make comments on pull requests. However, after many failed attempts, I am still running into the `Resource not accessible by integration` error. The interesting thing is this happens even on pull requests that are made from the same repo, i.e., not from a fork. 🤷 

The Action I am trying to write is here:
https://github.com/schalkneethling/allo-allo

The workflow uses the following: https://github.com/schalkneethling/allo-allo/blob/main/.github/workflows/main.yml

```yml
on:
  issues:
    types:
      - opened
  pull_request_target:
    branches:
      - main
    types:
      - opened
```

Note specifically the use of `pull_request_target`, which should enable the `GITHUB_TOKEN` to have read/write access to the pull request even from forks(https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/).

Commenting on issues works a treat, but I am having absolutely no luck with pull requests. According to [the docs](https://octokit.github.io/rest.js/v19#pulls-create-review-comment), one uses the same API call to comment on a pull request that you do to comment on an issue: https://github.com/schalkneethling/allo-allo/blob/main/allo-allo.js#L59 - so this should work?

You can see where the action is failing on a pull request that comes from the source repo:
- https://github.com/schalkneethling/allo-allo/pull/87
- https://github.com/schalkneethling/allo-allo/actions/runs/3238725842/jobs/5307251472

The other interesting thing about this run is that this is the rights the `GITHUB_TOKEN` has:

```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
Secret source: Actions
```

All help will be greatly appreciated. Thank you in advance.

**Comment by schalkneethling** [comment, marked as answer]
Looks like what I was missing was the following:

```yml
permissions:
  contents: read
  issues: write
  pull-requests: write
```

I set this at the workflow level so:

```yml
name: "AlloAllo"

on:
  issues:
    types:
      - opened
  pull_request_target:
    branches:
      - main
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write
```
