### DISCUSSION TITLE
What kind of situations will cause the "this job was skipped"

### DISCUSSION THREAD

**Discussion by GamerNoTitle** [community/community#36007] [Actions] [answered]
The thing is that i found some of the action jobs didn't work, and after i check it, i found that the **status** is **skipped** and the log has nothing in it. It just kept telling me that `This job was skipped`. So my question is that how it can cause this kind of thing...
This doesn't be skipped every time, but sometimes. The following is the content of my action config file.

```yaml
name: Run Script

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 2 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id 
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements 
      run: |
        pip install -r requirements.txt
    - name: Run script
      env:
        config: ${{ secrets.config }}
      run: |
        python3 main.py
```
