### DISCUSSION TITLE
working directory github actions

### DISCUSSION THREAD

**Discussion by saranraj3195** [community/community#36046] [Actions]
hi team 
In a single repo, we have 2 yml files if any changes in that repo am facing actions run both yml files how to fix this ?

**Comment by qianxi0410** [comment]
```yml
name: front-end

on:
  push:
    branches:
      - main
    paths:
      - 'packages/frontend/**' # That's the key
```
/cc @saranraj3195
