### DISCUSSION TITLE
new set-output for multiple variables in a step

### DISCUSSION THREAD

**Discussion by martcus** [community/community#36043] [Actions] [answered]
Hi,
i'm trying the new method to set an output on a workflow step as explained in:

- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

if I set two variables within the same step, the value is not set correctly.
My steps are:
```
      - name: Multiple color
        id: multiple-color-generator
        run: 
          echo "FIRST_COLOR=yellow" >> $GITHUB_OUTPUT
          echo "SECOND_COLOR=red" >> $GITHUB_OUTPUT
      - name: Get Multiple color
        run:
          echo "The first color is ${{ steps.multiple-color-generator.outputs.FIRST_COLOR }}"
          echo "The second color is ${{ steps.multiple-color-generator.outputs.SECOND_COLOR }}"
```

In the log I get this print:
```
      The first color is yellow echo SECOND_COLOR=red echo The second color is
```

Am I doing something wrong or  is it is a "bug"?

Thank you so much for your help!

**Comment by airtower-luna** [comment, marked as answer]
Your example code is missing the [literal block indicator](https://yaml-multiline.info/) (`|`) for the `run` values. That means it'll be interpreted as a plain string, and newlines will get eaten, messing with the shell syntax. :wink: 

The following should work:

```yaml
      - name: Multiple color
        id: multiple-color-generator
        run: |
          echo "FIRST_COLOR=yellow" >> $GITHUB_OUTPUT
          echo "SECOND_COLOR=red" >> $GITHUB_OUTPUT
      - name: Get Multiple color
        run: |
          echo "The first color is ${{ steps.multiple-color-generator.outputs.FIRST_COLOR }}"
          echo "The second color is ${{ steps.multiple-color-generator.outputs.SECOND_COLOR }}"
```
