### DISCUSSION TITLE
Using "workflow_dispatch" on a push workflow

### DISCUSSION THREAD

**Discussion by melanieziur** [community/community#36053] [Actions]
Hi! I'm a novice at Github and would love some pointers on getting my Workflow to work as planned.

I'm using the below chunk of code adapted from [here](https://dev.to/brunorobert/github-and-gitlab-sync-44mn) to run a workflow, that can only be triggered manually, its function being to push any changes made from on a repository here on Github to a repository on Gitlab. 

I'm currently running psychological studies on Gitlab. On Gitlab, the repository where I have data coming in, is being mirrored realtime onto a repository I have here on Github. I need to upload folders in bulk in order to run the study, but Gitlab doesn't allow this sort of bulk-uploading at the moment. To get around this, I wanted to run a manual workflow that would push folders that are uploaded onto the repo here Github to GitLab. I want to keep the Gitlab mirroring automatic and the Github workflow manual in order to avoid things getting lost. 

```
name: GitlabSync

on: 
   - push
   - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: melanieziur/rej_git_repo_sync@v0.1.0
      with:
        target-url: ${{ secrets.TARGET_URL }}
        target-username: ${{ secrets.TARGET_USERNAME }}
        target-token: ${{ secrets.TARGET_TOKEN }}
```

This is the code as adapted--it works beautifully as automatic, but when I add in  "**workflow_dispatch**", it either:
- still automatically runs,
- the "Run workflow" button appears under the Actions tab, but doesn't push anything, 
- or the text editor tells me I'm using it incorrectly

So I'm a little stumped on how to use that command here. 

Any guidance would be immensely appreciated. Thanks!

**Comment by antonblr** [comment]
Could you paste exact snippets how you tried it? 
It should be something like:
```yaml
on:
  - push
  - delete
  - workflow_dispatch
```
Here the syntax reference - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

**Reply by melanieziur** [reply]
Hi! Thank you for your reply. Sorry, I've fixed my original post with the correct code snippet format.

I've tried it a few ways like this:

```
on: 
   workflow_dispatch:

```
--> This doesn't push anything automatically and the "Run workflow" button appears, but it doesn't push any changes upon running manually.



```
on: 
   workflow_dispatch:
          -push
          -delete

```

--> Here I get the following warning in the text editor: "workflow_dispatch only supports mapping values."



`on: [workflow_dispatch, push]`
--> This still pushes automatically. 

**Edit:** 
i just tried this: 
```
on: 
   - workflow_dispatch
   - push
   - delete
```

And it's still pushing automatically, instead of on manual run like I want it to :/
I don't really see this sort of application of workflow_dispatch anywhere in the docs or the forum, unless I'm misunderstanding something

**Reply by antonblr** [reply]
I'm confused - so you do *NOT* want automatic runs at all? Only manual? 
Then leave just this (no need `push`, `delete`):
```yaml
on: 
   workflow_dispatch:
```
If you want add optional inputs into that - see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs

**Reply by melanieziur** [reply]
Yes, exactly, I want it to run only manually. 

Your suggestion was the first thing I tried (see my edited reply above), and while it stopped running automatically, when I go to run it manually under the Actions tab, nothing happens-- no failure message, no pushes, nothing. It's noted as a successful run, but I see no changes made to the target repo. That's why I'm stumped as to what I'm doing wrong here. :/

**Reply by antonblr** [reply]
I think these are two different problems - being able to trigger action manually vs nothing happens. 

1) Do you have actions enabled at all? 
1) Do you see that job in the actions list (replace with your repo) - `https://github.com/<OWNER>/<REPO>/actions?query=event%3Aworkflow_dispatch` ? 
1) Any logs / screenshots? 
1) Are you sure something should happen? i.e. job was triggered, but didn't proceed with sync, since there are no changes

**Reply by melanieziur** [reply]
1. Yes, all actions are enabled

2. Yes, it is in the Actions list

3 & 4. 
![Screen Shot 2022-10-13 at 4 59 34 PM](https://user-images.githubusercontent.com/72086257/195709361-fb777674-eaed-4ac3-92e5-979fb4425799.png)


Yes, something should happen-- every time I make a change to the .yml, I make a new empty dummy file just to see if it would get synced onto the target repo. 

When I took out **workflow_dispatch** and left it with the [pull,delete], thus making it run automatically, it auto-pushes the dummy file to the target repo just fine. 


But when I took those out and left it as ```on:  workflow_dispatch: ```, the dummy file doesn't get pushed at all. The above is what the results show me. It apparently ran successfully and it recognizes that it was run manually, but nothing gets pushed at all, despite there being clear changes to the origin repo

I know the job itself is set up fine because in the absence of **workflow_dispatch**, new files get pushed. But once I add **workflow_dispatch**, no new stuff gets pushed at all, so I wonder if i'm missing some kind of input or I'm just not calling **workflow_dispatch** correctly here.

**Reply by antonblr** [reply]
Ok, now I see that the workflow is actually running normally and the real question is why your action does not do anything. And I believe the answer lies here (if that's the actual script used, I don't have much more details than you provided):
```shell
case "${GITHUB_EVENT_NAME}" in
    push)
        git push --all target
        git push --tags target
        ;;
    delete)
        git push -d target ${GITHUB_EVENT_REF}
        ;;
    *)
        break
        ;;
esac
```
You need to update it to account for `workflow_dispatch` event now (`GITHUB_EVENT_NAME`) and make it more smarter, so it could detect whether to delete or push itself (or have them as `input` parameter for manual run).

**Reply by melanieziur** [reply]
Hi Anton,

Thank you for your response. I tried rewriting the shell script to something like below-- I'm not getting any error messages but it doesn't work (i.e. it doesn't push anything, i took out the delete option). I'm a novice at this kind of script writing and would appreciate any pointers. Would you or anyone else be able to guide me on how to correctly rewrite it to account for workflow_dispatch? 
```
git remote add target https://${INPUT_TARGET_USERNAME}:${INPUT_TARGET_TOKEN}@${INPUT_TARGET_URL#https://}

case "${GITHUB_EVENT_NAME}" in 
workflow_dispatch)

        git push --all target
        git push --tags target
        git push -d target ${GITHUB_EVENT_REF}
        ;;
    *)
        break
        ;;
esac
```

**Reply by antonblr** [reply]
hey @melanieziur - I'd recommend looking into using single command for all cases. I believe `--mirror` flag should do it - could you test it out?
Remove condition completely (`case ... in ...` part) and just use something like `git push --mirror target`. So you will have 2 commands (you could inline them in the action `run: |`):

```shell
git remote add target https://${INPUT_TARGET_USERNAME}:${INPUT_TARGET_TOKEN}@${INPUT_TARGET_URL#https://}
git push --mirror target
```
Test it out locally, thought. Also see `git push --help`.

**Reply by melanieziur** [reply]
Hi Anton, thank you for all of your help. It seems to be pushing on command now! The only thing is that while it is pushing new files manually, I get told that the job was a Failure, even though the changes were reflected, so I would like to know your thoughts on that.

Here's what the .yml file looks like now: 
```

name: GitlabSync

on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: melanieziur/rej_git_repo_sync@v0.1.0
        with:
          # Such as https://github.com/melanieziur/rej_git_repo_sync.git
          target-url: ${{ secrets.TARGET_URL }}
          # Such as melanieziur
          target-username: ${{ secrets.TARGET_USERNAME }}
            # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
          target-token: ${{ secrets.TARGET_TOKEN }}
      - run: git push --mirror target


```

and here's a screenshot of the log, where the "job failure" takes place.

![Screen Shot 2022-10-20 at 2 51 31 PM](https://user-images.githubusercontent.com/72086257/197034003-259f3ecc-283f-4eb1-9ae7-7d2c41387fb7.png)

Thanks so much!
