### DISCUSSION TITLE
Github Actions caches api request responses.

### DISCUSSION THREAD

**Discussion by rushminatorr** [community/community#36098] [Actions] [answered]
Hello,

We encountered an issue where the api response for an external request is somehow cached in github actions. 
In my case, describing an aws cloudformation stack after updating a stack gives same output - no updated output but if we setup a new job, then we see updated output. 

So somehow the response is getting cached in job1 as the last call to describe stack returns incorrect results where as the request run immediately after in job2 returns correct updated results.

Can someone please advise how to clear this cache?
I tried this and i dont think this cache is what is being used here - https://docs.github.com/en/rest/actions/cache#delete-github-actions-caches-for-a-repository-using-a-cache-key 

Here is my github actions workflow. 
```
name: RushStackTest

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Credentials to deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}

      - name: describe stack vpc endpoint
        run: |
          aws cloudformation describe-stacks --stack-name rush
    
      - name: update stack vpc endpoint(change an output)
        run: |
          aws cloudformation update-stack --stack-name rush --template-url https://....amazonaws.com/template.yml

      - name: describe stack vpc endpoint with updated output value
        run: |
          aws cloudformation describe-stacks --stack-name rush

  job2:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Credentials to deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}

      - name: describe stack vpc endpoint
        run: |
          aws cloudformation describe-stacks --stack-name rush
      
```
