### DISCUSSION TITLE
[feature_request] Prevent people from submitting an empty GitHub issue form

### DISCUSSION THREAD

**Discussion by rickstaa** [community/community#36119] [Projects and Issues]
Currently, people are not allowed to submit a github issue that is created from a GitHub form template when it has not the title. However, no mechanism prevents users from creating an issue with a title without filling in any of the form fields.

## Current behaviour

![image](https://user-images.githubusercontent.com/17570430/195816856-6a022ec7-1ed8-47a7-9451-3825ca10b0f7.png)

![image](https://user-images.githubusercontent.com/17570430/195817189-1835e0c5-b20b-4d62-918a-65ad460a3833.png)

## Proposal

It would be nice if the `Submit new issue` button is also greyed out if none of the template fields is filled in.

**Comment by rickstaa** [comment]
I found out this is already supported through the `validation` property (see https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) :rocket:.

```yml
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
```
