### DISCUSSION TITLE
Boolean input not passed to called workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#36179] [Actions]
I have an invoking and a called (reusable) workflow.

Here is the input of the reusable one:

```
      stg_image_build:
        description: whether to build the staging image
        required: true
        type: boolean
        default: false
```

Here is the relevant part of the calling workflow

```
      push_to_stg:
        description: "Build and push image to staging registry"
        type: boolean
        default: false
        required: true

...


  build-and-push-image:
    uses: path/to/reusable/workflow.yaml@master
    with:
      stg_image_build: ${{ inputs.push_to_stg }}
```

This fails as follows:

```
The template is not valid. .github/workflows/calling.yaml (Line: 72, Col: 24): Unexpected type of value '', expected type: Boolean.
```

The error refers to this line:

```
stg_image_build: ${{ inputs.push_to_stg }}
```

Why?
