### DISCUSSION TITLE
`set-output` command is deprecated using secrets

### DISCUSSION THREAD

**Discussion by dschinkel** [community/community#36222] [Actions]
I am lazy, I don't want to spend all night looking things up.  Anyone know how to fix this stupid script using the new env variables?

```
  build_and_push_docker_image_from_artifact:
    needs: Build
    name: Build/Push Image => GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: app
      - run: echo ${{ secrets.GHCP_ACCESS_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
```
      
**Error**: `Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Artifact download has finished successfully`
