### DISCUSSION TITLE
actions-runner executes the script twice

### DISCUSSION THREAD

**Discussion by tchwpkgorg** [community/community#36243] [Actions]
I have a very simple action defined - it is supposed to run deployment:
```
name: Deploy code
on: push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: /home/actions-runner/bin/deploy.sh
```

Unfortunately, on every push to the branch - it gets executed twice:
- once in "Set up runner" step
- then in "run /home/actions-runner/bin/deploy.sh" step

How to make it run only once?
