### DISCUSSION TITLE
the cache action for gradle progress stuck

### DISCUSSION THREAD

**Discussion by sionnx** [community/community#36286] [Actions]
I use https://github.com/actions/cache for my android project to cache my gradle ,but the process of gradle will stuck **sometimes**,  not each time. just like this:

```plain
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.2 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.1 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
Received 1698700475 of 1702894779 (99.8%), 3.0 MBs/sec
```

my workflow file is here : 

```
name: CI

on: [ push ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build App with Gradle
        run: |
          ./gradlew assembleDebug
          ./gradlew assembleRelease

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          appReleaseName=`ls app/build/outputs/apk/release/*.apk | awk -F '(/|.json)' '{print $6}'` && echo "::set-output name=appReleaseName::$appReleaseName"
          appDebugName=`ls app/build/outputs/apk/debug/*.apk | awk -F '(/|.json)' '{print $6}'` && echo "::set-output name=appDebugName::$appDebugName"

      - name: Upload for debug
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ steps.prepareArtifact.outputs.appDebugName }}
          path: app/build/outputs/apk/debug/

      - name: Upload for release
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ steps.prepareArtifact.outputs.appReleaseName }}
          path: app/build/outputs/apk/release/
```
