### DISCUSSION TITLE
Invalid jobs description (only last part shown)

### DISCUSSION THREAD

**Discussion by LastDragon-ru** [community/community#36294] [Actions]
Sorry, not sure this is a valid place to report an issue or not, so maybe someone will redirect me into... After the recent actions update github begun groups jobs, but if the name contains `/` the title will be truncated incorrectly. I really like the grouping but it is the real issue, moreover, it makes old names are useless :( ([the job](https://github.com/LastDragon-ru/lara-asp/blob/2660f7118e91a64742ca570bd0c5a5dadf89f1f9/.github/workflows/phpunit.yml))

![image](https://user-images.githubusercontent.com/1329824/196022275-9e2b9c52-b803-428d-be0b-306890a142cf.png)

```yml
jobs:
  run:
    name: Laravel ${{ matrix.laravel }} / PHP ${{ matrix.php }} (${{ matrix.dependencies }} / ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        laravel: ${{ fromJson(inputs.laravel-versions) }}
        php: ${{ fromJson(inputs.php-versions) }}
        dependencies: ${{ fromJson(inputs.dependencies) }}
        os: ${{ fromJson(inputs.runs-on) }}
```
