### DISCUSSION TITLE
Feature Request: Space out parallel jobs triggered using `strategy-matrix`

### DISCUSSION THREAD

**Discussion by itsankit-google** [community/community#36381] [Actions]
Is there a way to space out the job runs using strategy matrix? Currently, I trigger three jobs like below using `strategy-matrix` but all the jobs start at the same time, is there a way I can space out my runs with `5 minute difference`??

```
jobs:

  set-branch-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: set-matrix
        run: |
            echo 'BRANCH_MATRIX={"include":[{"branch":"develop"}, {"branch":"release/6.7"}, {"branch":"release/6.8"}]}' >> $GITHUB_ENV

    outputs:
      matrix: ${{ env.BRANCH_MATRIX }}

  build:
    needs: set-branch-matrix
    runs-on: <self-hosted-runner>

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.set-branch-matrix.outputs.matrix) }}
```
