### DISCUSSION TITLE
permissions: write-all

### DISCUSSION THREAD

**Discussion by PeterSusan623** [community/community#36451] [Repositories]
My actions can't modify the files in the warehouse, but I can modify them when I run locally. Who can tell me where the permissions are set? Thank you very much!!!

**Comment by zomgbre** [comment]
Hi you may be looking for: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

```
name: '⚡some-job'
on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
```
