### DISCUSSION TITLE
X reported on commit never invalidated even as the status changes

### DISCUSSION THREAD

**Discussion by jamiebuilds-signal** [community/community#36488] [Actions]
- Have GitHub Action that runs on `pull_request.opened/labeled/unlabeled` to verify the pull request has the appropriate labels.
- On `pull_request.opened`, if labels are missing, the check fails.
- Commit receives ❌ in pull request UI, if you click on ❌ it will show you the failed action.
- On `pull_request.labelled`, if labels are not missing, check passes.
- Commit still has ❌ in pull request UI, **BUT** if you click on ❌ it will show you the action has passed.

The ❌ never gets invalidated on the commit, even though the status was related to the pull request's labels, not the commit itself.

If this is intentional, it's confusing. Or maybe it's a bug.

```yaml
# Copyright 2022 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
name: Backport Check
on:
  pull_request:
    types: [opened, labeled, unlabeled]
jobs:
  backport-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request has a backport label
        env:
          EVENT_ACTION: ${{ github.event.action }}
          EVENT_LABEL_NAME: ${{ github.event.label.name }}
          EVENT_PULL_REQUEST_LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
        shell: bash
        run: |
          LABELS=""
          BACKPORT_LABELS="backport no-backport needs-backport needs-manual-backport"
          if [ "$EVENT_ACTION" == 'opened' ]; then
            LABELS="$EVENT_PULL_REQUEST_LABELS"
          elif [ "$EVENT_ACTION" == 'labeled' ]; then
            LABELS="\"$EVENT_LABEL_NAME\""
          fi
          echo "Found labels: $LABELS"
          for BACKPORT_LABEL in $BACKPORT_LABELS; do
            echo "Checking for label '$BACKPORT_LABEL'"
            if echo "$LABELS" | grep -q "\"$BACKPORT_LABEL\""; then
              echo "Has '$BACKPORT_LABEL' label"
              exit 0
            fi
          done
          echo "Does not have any backport label"
          exit 1
```

---

**_Also_**, the payload for `github.event.pull_request.labels.*.name` is out of date for the `pull_request.labeled/unlabeled` events. It represents the state _before_ the event, which seems incorrect.
