### DISCUSSION TITLE
Node.js 12 actions are deprecated. How to upgrade?

### DISCUSSION THREAD

**Discussion by ajmas** [community/community#36493] [Actions] [answered]
I am getting the following error when building my project, but I am not sure the steps to take to resolve this:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/checkout

My yaml file:

```yaml
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - shell: bash
      env:
        GDRIVE_FILEFOLDER_ID: ${{ secrets.GDRIVE_FILEFOLDER_ID }}
        GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        GOOGLE_PRIVATE_KEY: '${{ secrets.GOOGLE_PRIVATE_KEY }}'
      run: npm test
```

**Comment by ajmas** [comment, marked as answer]
A little bit of searching led me to:

  - https://github.com/actions/setup-node
  - https://github.com/actions/checkout

In both cases we need to update to v3, such that:

```yaml
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - shell: bash
      env:
        GDRIVE_FILEFOLDER_ID: ${{ secrets.GDRIVE_FILEFOLDER_ID }}
        GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        GOOGLE_PRIVATE_KEY: '${{ secrets.GOOGLE_PRIVATE_KEY }}'
      run: npm test
```

**Comment by ossanna16** [comment]
Hey there @ajmas and thank you for asking a good question! I'm glad you found our community 🙂

**Comment by liborty** [comment]
I do not use Node but I still get warnings:
`Please update the following actions to use Node.js 16: actions-rs/toolchain`
This message is obscure and unhelpful. After a lot of searching, I have upgraded to `- uses: actions/checkout@v3`
Why not put that in the warning message?
Anyway, it did not help, I still get the same warnings.

**Reply by ajmas** [reply]
The action you are using likely use nodejs. 

Have you tried referencing `actions-rs/toolchain@v1.0.6` , since that appears to be the latest version ?

Latest version  can be seen at these two location:

  - https://github.com/actions-rs/toolchain
  - https://github.com/marketplace/actions/rust-toolchain

Edit: Just noticed this action has not been updated since 2020, so you may want to open a ticket on the project to get this resolved or look at replacing this action.

Edit 2: Looks like there is already an open issue and PR: https://github.com/actions-rs/toolchain/pull/220

**Reply by liborty** [reply]
PS. You do not accept .yml files to be quoted here, so I have not been able to include mine.

**Reply by ajmas** [reply]
> PS. You do not accept .yml files to be quoted here, so I have not been able to include mine.

You can specify the workflow contents inline, as I did with mine. Just add a markdown [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) and indicate the language as being 'yml'.

**Reply by liborty** [reply]
Thanks. Another recommended change:  ` >> $GITHUB_OUTPUT`
Does not work either:
`Unable to process file command 'output' successfully.`

Too many changes that do not work?

**Reply by ajmas** [reply]
> Thanks. Another recommended change: ` >> $GITHUB_OUTPUT` Does not work either: `Unable to process file command 'output' successfully.`
> 
> Too many changes that do not work?

I don't work with Rust, I can't help much beyond this. Hopefully the owner/maintainers of the action you depend on (actions-rs/toolchain) update it soon.

**Reply by liborty** [reply]
For Rust users, the solution is to give up on the abandoned `actions-rs/toolchain` and use instead D.Tolney's one.
Here is an example:
```
name: tests

on: push

jobs:
  build:  
    name: Rstats 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable    
    - run: cargo test  ...
```
