### DISCUSSION TITLE
why is "pages-build-deployment" not waiting for my workflow to finish?

### DISCUSSION THREAD

**Discussion by jangorecki** [community/community#36555] [Other Feature Feedback, Questions, & Ideas]
Hi there,

I am experiencing strange behavior, where two repos storing exactly same code are behaving different.

(1) https://github.com/WTschacher/SUSY
(2) https://github.com/jangorecki/SUSY

I have one workflow CD.yml that run tests and publish website as gh-pages.
In both repos settings, gh-pages is activated in Pages settings.

The difference is that in repo (1) workflow "pages build and deployment" (by github-pages bot), [starts straight away after git push](https://github.com/WTschacher/SUSY/actions), simultaneously as CD.yml workflow.
In repo (2) "pages build and deployment" [starts when CD.yml workflow finishes](https://github.com/jangorecki/SUSY/actions) (as expected).

Somehow [website in (1)](https://wtschacher.github.io/SUSY/) is just README.md turned into html. NB. it is not what [blob/gh-pages/index.html](https://github.com/WTschacher/SUSY/blob/gh-pages/index.html) is ([preview](https://htmlpreview.github.io/?https://github.com/WTschacher/SUSY/blob/gh-pages/index.html)).
While [website in (2)](https://jangorecki.github.io/SUSY/) is proper website created during CD.yml workflow.

How to debug this problem further?
Possibly an issue caused by a different owner of a repo.

Thank you very much.

**Comment by yoannchaudet** [comment]
When your Pages site is setup with a source branch (the case for you), the only guarantee is that the build/deployment (i.e. the workflow called "pages build and deployment" that we manage on your behalf) is triggered after a push on your selected branch.

There are no other guarantees being made with regards to workflow orchestration.

Since you are building with a workflow already, I strongly suggest you migrate to https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/. This will allow you to manage everything and only have one workflow to build/deploy your site instead of 2 today.

**Reply by jangorecki** [reply]
Thank you for your reply but it doesn't really address the problem described. It mentions the alternative without really giving a working example. Link you provided (and all the link that it have inside) are not providing an example for me as well. I am afraid I can spend couple hours migrating my setup from gh-pages and reach the point where a feature needed is still not available (which is even more likely as the alternative is in beta). Moreover first link seems to recommend not to use the alternative you are suggesting for my use case...

> If you do not need any control over the build process for your site, we recommend that you publish your site when changes are pushed to a specific branch.

**Reply by yoannchaudet** [reply]
Since you care about orchestration of the workflow, I assumed you cared about the build process ;)

If you want to experiment with custom workflows (which you don't need to if you don't care), it should be as simple as:

1. Updating the source to "GitHub Actions" in your Pages settings
2. Replacing your [deploy step](https://github.com/WTschacher/SUSY/blob/d971c3eb24be0c931b7999fac5cd4e5119e923f1/.github/workflows/CD.yml#LL29C1-L35C25) by:
   ```yaml
   - name: Upload artifact
     uses: actions/upload-pages-artifact@v1
     with:
       path: 'public'
   - name: Deploy to GitHub Pages
     id: deployment
     uses: actions/deploy-pages@v1
   ```
3. Adding that on top of your workflow:

   ```yaml
   # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
   permissions:
     contents: read
     pages: write
     id-token: write
   
   # Allow one concurrent deployment
   concurrency:
     group: "pages"
     cancel-in-progress: true
   ```

PS: We publish a bunch of workflows in https://github.com/actions/starter-workflows/tree/main/pages which are good examples of how to use custom workflows with Pages.
