### DISCUSSION TITLE
Specify branch for pull_request and push.

### DISCUSSION THREAD

**Discussion by terabytesoftw** [community/community#36566] [Actions] [answered]
I have the following workflow.

```yml
name: tests

jobs:
  tests:
    name: tests

    env:
      COMPOSER_ROOT_VERSION: dev-big-refactoring // How can I make it so that when i pull_request, it takes the pull_request branch, try ${{ github.base_ref }} and it didn't work, and when merge in branch master, it changes to master, is there a way to do it, thanks.
```
