### DISCUSSION TITLE
Deploy to UNC Path or any other way.

### DISCUSSION THREAD

**Discussion by nastanford** [community/community#36586] [Actions]
I have tried multiple things and can not get my deployment to push to production.  I have tried to run git pull 

### Example 1
```
on: [push]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
#      - name: get 
#        run: cd \inetpub\wwwroot\testActions
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Who am I
        run: whoami          
      - name: change dev
        run: cd \\xxxxx.file.core.windows.net\az-aaa-bbb-dev\inetpub\testActions\
``` 

## Example 2
```
      - name: run Git Pull
          run: C:\Program" "Files\Git\bin\git -C \\xxxxx.file.core.windows.net\az-aaa-bbb-dev\inetpub\testActions\ pull
```

## Example 3
```
      - name: run Git Pull
          run: C:\Program" "Files\Git\bin\git -C  Z:\inetpub\testActions\ pull
```

**Comment by AF250329** [comment]
Hi

You don't need to checkout the code yourself - just use appropriate Github Action: [Checkout](https://github.com/marketplace/actions/checkout).

There's examples on it site - here is trivial one:


```
- name: Checkout
  uses: actions/checkout@v3
```

That's it. After this step will be completed all your code will be cloned to runner. 

It is very configurable - you could check `branch`, `tag`, `multiple repos`, etc...

**Reply by nastanford** [reply]
Sorry, maybe I am not really clear.  I know this is not the normal process but when I commit my code to the main branch I want it to deploy to the Cloud Server A1 without having to tell it.  There are other steps that would be nice but first I need/have to get this part working.

Hope this helps.  I am not really checking it out but I was trying to go to a runner and deploy the code to either Dev Server or Prod Server.  I know this must be simple to those who do it all the time but this is not me.

**Reply by AF250329** [reply]
Sorry - I don't understand what do you mean by writing `deploy the code` ? `Clone`/`checkout` it to some computer ? Then use Github Action: Checkout. You want to copy the folder with code to some other computer from Github runner ? Just copy it with the tools you know like `Copy-Item` in session with Powershell or `rsync` may be in Linux.....

**Reply by nastanford** [reply]
Right now I can manually go to production and run git pull in the folder that has the repo.  Is there a way I can do this with GitHub Actions?  or is this something not allowed? or is there a way I can run a batch file that does it?

**Reply by AF250329** [reply]
To clone latest code from your repo you need to add `step` to `workflow` yaml based file. This step is using Github Action called: Checkout. On official site of this action: [https://github.com/marketplace/actions/checkout](https://github.com/marketplace/actions/checkout) you could find additional examples on how to get the latest code. The workflow itself has what it call `triggers` - for example: `on push`. So once someone pushed a new code to the repo the workflow will run and clone the latest code (including what is pushed) to Github Runner computer and then continue to execute all steps in workflow

**Reply by nastanford** [reply]
understood however how do you get the code to the production server?

**Reply by AF250329** [reply]
Sorry - I don't understand what do you want..... You mean that you have another remote computer that you call 'production server' - that's right ? and you need to copy files there when workflow running ?

If this is the case - I am usually using Windows on both computers so I create a special user on remote computer and then create Powershell session between them and copy files in this session.  Here is the first result from Google:  [Powershell - Copy files to remote computers](https://techexpert.tips/powershell/powershell-copy-files-remote-computers/)

**Reply by nastanford** [reply]
Here is what I am trying to do. Any Suggestions?

```
name: testAction - Deployed
on: [push]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Who am I
        run: whoami          
        
        # This works from on my home machine so due to AppData folder so figure
      - name: run Git Pull
        run:  C:\Program" "Files\Git\bin\git -C //aaadevstorage.file.core.windows.net/az-aaa-dev/inetpub/testActions/ pull


```
