### DISCUSSION TITLE
Output coming out blank?

### DISCUSSION THREAD

**Discussion by rjfranco** [community/community#36605] [Actions] [answered]
I'm attempting to run a fairly simplistic workflow that just echos some test output, and nothing is coming up and I don't really understand what my mistake here is and would love some guidance/help
```
jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.env.outputs.matrix }}
      test: ${{ steps.test.outputs.test }}
    steps:
      - id: env
        run: echo "matrix=[${GITHUB_REF#refs/heads/env/}]" >> $GITHUB_OUTPUT
      - id: test
        run: echo "test=MyTestString" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Separate test echo
        run: echo ${{needs.set-env.outputs.test}}
      - name: Test Echos
        run: |
          echo ${{needs.set-env.outputs.matrix}}
          echo ${{needs.set-env.outputs.test}}
          echo "Test string"
```
The only output I see from all these is the "Test String" output
