### DISCUSSION TITLE
Actions with cron interval not triggering

### DISCUSSION THREAD

**Discussion by TRegourd** [community/community#36657] [Actions]
hi, I'm trying to trigger a Netlify build on a certain interval, but I'm not able to make it run...

my `.github/workflows/main.yml`

```
name: Trigger Netlify Build
on:
  schedule:
    - cron: '30 * * * 1-5'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} my-web-hook
```
I tested my webHook from my CLI, and it triggered the build well.

I don't think my code has anything wrong, maybe a problem on github action's side ?
