### DISCUSSION TITLE
Feature request: use default input values when executing dispatched workflow on schedule

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#36660] [Actions]
When adding a schedule to a dispatched workflow:

```yaml
on:
  workflow_dispatch:
    schedule:
     - cron: "0 5 */30 * *"
    inputs:
      python_versions:
        description: comma separated list of python versions to use for the build process
        required: true
        type: string
        default: 3.8,3.9,3.10
      poetry_version:
        description: the version of poetry to install
        required: true
        type: string
        default: 1.1.15
```

have the workflow use the default values of the inputs when executed on schedule
