### DISCUSSION TITLE
matrix variables no longer being set?

### DISCUSSION THREAD

**Discussion by ajkerr** [community/community#36670] [Actions] [answered]
Hi there,

One of our workflows that has been working fine until this morning is now failing with: 

`The template is not valid. .github/workflows/pull-request.yml (Line: 50, Col: 19): Unexpected type of value '', expected type: Number.`

The relevant job looks like this:

```
  test-suite:
    name: Run full test suite
    needs: [ensure-labels]
    strategy:
      matrix:
        node_index: [ 1, 2, 3, 4, 5, 6, 7, 8 ]
    uses: ./.github/workflows/reusable-workflow-ci.yml
    secrets: inherit
    with:
      test-suite: ${{ matrix.node_index }}
```

The error is flagging the last line here, indicating that `matrix.node_index` is not defined. This workflow hasn't changed in weeks, and the [syntax looks correct](https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-matrix-strategy-with-a-reusable-workflow), so we are wondering if something changed in GitHub Actions itself?

**Comment by ChristopherHX** [comment]
This is really weird, seems like GitHub added a new validation logic which rejects previously valid workflows. Maybe contact GitHub Support.

If you add a default value to the `boolean` / `number` matrix input, it seems to work without actually using the default value.
```yaml
  test-suite:
    name: Run full test suite
    needs: [ensure-labels]
    strategy:
      matrix:
        node_index: [ 1, 2, 3, 4, 5, 6, 7, 8 ]
        # b: [ true, false ]
    uses: ./.github/workflows/reusable-workflow-ci.yml
    secrets: inherit
    with:
      test-suite: ${{ matrix.node_index || 0 }}
      # b: ${{ matrix.node_index || false }}
```
