### DISCUSSION TITLE
What are the criteria for multiple workflows to be used for the same check?

### DISCUSSION THREAD

**Discussion by bewuethr** [community/community#36680] [Pull Requests] [answered]
I have a workflow that is triggered for pushes into certain branches, and for pull requests. For both triggers, there's also a `paths` filter to only run if files that can actually affect the outcome of the workflow are modified:

```yaml
name: Go linting

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - sandbox
      - master
    paths:
      - '**/*.go'
      - go.mod
  pull_request:
    paths:
      - '**/*.go'
      - go.mod
```

The job itself is then a call to a reusable workflow:

```yaml
jobs:
  golangci:
    name: Go linting
    uses: myorg/actions/.github/workflows/golint.yml@main
    secrets:
      pat-token: ${{ secrets.PAT_TOKEN }}
```

I want to add branch protection that makes this check required. Because a PR would be stuck waiting for this check if it doesn't touch a file matching `paths`, there's an [official workaround](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks): create an always passing workflow with the same name, but complementary triggers.

Mine looks like this:

```yaml
name: Go linting

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - sandbox
      - master
    paths-ignore:
      - '**/*.go'
      - go.mod
  pull_request:
    paths-ignore:
      - '**/*.go'
      - go.mod

jobs:
  golangci:
    name: Go linting
    runs-on: ubuntu-20.04
    steps:
      - name: Exit successfully
        run: |
          echo "No Go linting required"
```

Now, no matter if I set "Go linting" or "Go linting / Go linting" as the required check from this selection

![image](https://user-images.githubusercontent.com/8521043/196773349-f39cc401-0b4c-4484-9dc7-64fed2f8c7d5.png)

these two workflows are considered separate checks, so in PR that touches Go files, the "real" workflows runs

![image](https://user-images.githubusercontent.com/8521043/196744826-5bd477c4-6c15-448a-8941-f4ecda64e6f9.png)

but the generic one isn't triggered:

![image](https://user-images.githubusercontent.com/8521043/196744895-71755a66-479c-4c72-91ac-60c14a70e16f.png)

Why is that? What check exactly has to be selected for the workaround to work? Could this be related to using a reusable workflow, which ends up showing up in the checks list like this?

![image](https://user-images.githubusercontent.com/8521043/196745506-2323047a-f09c-4ff4-8151-bf0925b531fb.png)

**Comment by antonblr** [comment]
Hi @bewuethr - could you add screenshot of the required checks selection (under branch protection setting)?

Also keep in mind that using `on.pull_request` along with `on.push` might create duplicate workflows if not configured properly (i.e. new PR against `master` branch will trigger dups). Hence you will see `Go linting / Go linting (pull_request)` and `Go linting / Go linting (push)`

**Reply by bewuethr** [reply]
It looks like this (also added screenshot to the question):

![image](https://user-images.githubusercontent.com/8521043/196773447-b285696a-d20d-494c-85a8-fe031d282860.png)

Since the branch protection is only relevant for pull requests, I first had the triggers for the generic workflow be just

```yaml
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**/*.go'
      - go.mod
```

This didn't work (same problem); then I thought maybe the triggers are taken into account when determining if two workflows are used for the same check, so I updated to include `push`.

**Reply by antonblr** [reply]
Try removing `Go linting / Go linting` from the require checks, leaving just `Go linting` (way to many `Go linting` lol) -> usually it should be just the job names. 

I believe it will cover triple `Go linting / Go linting / Go linting` as well

**Reply by bewuethr** [reply]
Switched to just "Go linting":

![image](https://user-images.githubusercontent.com/8521043/196778571-0d28befb-053d-4413-804d-fd192f22cc29.png)

That didn't work: the required check is now only the generic workflow

![image](https://user-images.githubusercontent.com/8521043/196778343-bfcff164-ddb4-468f-8e2a-f9ac3a73190d.png)
![image](https://user-images.githubusercontent.com/8521043/196778390-fa2f6ba8-8c5a-4fd1-9d8f-1ddf061a55b2.png)

so a failure in the actual Go linter wouldn't block merging.

**Reply by antonblr** [reply]
I see, so it is defiantly due to reusable workflow naming being different than its counterpart (triple `Go linting` vs double).
> by creating a generic workflow, **with the same name**

You'd need to match the naming, i.e. your always passing flow should also depend on re-usable workflow (perhaps you can pass some flag as `input` to skip everything?)

**Reply by bewuethr** [reply]
Yeah, let me try using a generic reusable workflow. It feels like this should be less hard 😕

**Reply by antonblr** [reply]
Couldn't agree more - the official workaround looks more like a band-aid. For the large set of workflows it will be nightmare.

**Reply by bewuethr** [reply]
Looks like using a reusable generic workflow was the ticket. I'll probably open up an issue and PR to update the official workaround docs to be more clear about this. Thanks for your help!

**Comment by bewuethr** [comment, marked as answer]
After a bit of trial and error and with the help of the hint from @antonblr, this is my conclusion:

Apart from naming workflow and job the same, workflows must either *both call reusable workflows* or *both **not** call reusable workflows* to be considered the same for the purpose of a required check.

In the end, my workflows look like this:

### Workflow calling the "real" reusable workflow

```yaml
name: Go linting

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - sandbox
      - master
    paths:
      - '**/*.go'
      - go.mod
  pull_request:
    paths:
      - '**/*.go'
      - go.mod

jobs:
  golangci:
    name: Go linting
    uses: myorg/actions/.github/workflows/golint.yml@main
    secrets:
      pat-token: ${{ secrets.PAT_TOKEN }}
```

### Generic workflow calling a generic reusable workflow

No `push` trigger, as required checks only apply to pull requests.

```yaml
name: Go linting

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**/*.go'
      - go.mod

jobs:
  golangci:
    name: Go linting
    uses: myorg/actions/.github/workflows/golint-generic.yml@main
```

### The generic reusable workflow

```yaml
name: Go linting

on:
  workflow_call:

jobs:
  golangci:
    name: Go linting
    runs-on: ubuntu-20.04
    steps:
      - name: Exit successfully
        run: |
          echo "No Go linting required"
```

The required check to select is called "Go linting / Go linting". The check called just "Go linting" does *not* work.
