### DISCUSSION TITLE
Conditional run-name

### DISCUSSION THREAD

**Discussion by TomVer99** [community/community#36683] [Actions] [answered]
I want to only change to name of a run if it is executed manually.

My correct workflow looks like this right now:

```yml
workflow_dispatch:
    inputs:
      reason:
        description: 'Reason/Run name'
        required: true
        default: 'Manual trigger'


if: ${{ github.event_name == 'workflow_dispatch' }}
  run-name: ${{ github.event.inputs.reason }}
```

This does not work and GitHub gives me this error:
```
You have an error in your yaml syntax on line 36
```

Line 36 being the following:
```yml
run-name: ${{ github.event.inputs.reason }}
```

I have no idea how to fix this, and searching on the internet has resulted in 0 tips.
