### DISCUSSION TITLE
GITHUB_TOKEN permissions to read|write|none on a Github Organization Project

### DISCUSSION THREAD

**Discussion by Omzig** [community/community#36691] [Actions]
With the addition of the organization level project the GITHUB_TOKEN has no way to access that level of the projects.

### Use Case:
- https://github.com/actions/add-to-project currently requires a PAT that has access to modify the projects at the org level.

Or if there is something that i do not understand in the doc, can someone help me grant the GITHUB_TOKEN access to the org projects?

### Here is the error in the pipeline:
![image](https://user-images.githubusercontent.com/1987296/196763837-517e5df6-dcde-4733-ab88-d660281d953e.png)

## Existing Permissions:
```yaml
permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  issues: read|write|none
  packages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none
```

## Proposed Additional Permission
```yaml
permissions:
  organization-projects: read|write|none
```
