### DISCUSSION TITLE
`github.ref` not fully-formed on pull requests event of type "closed"

### DISCUSSION THREAD

**Discussion by jlian** [community/community#36694] [Actions]
I have a workflow that cleans up the environment when the PR is closed. It specifies `preview-${{ github.ref }}` to clean up the correct environment associated with a PR e.g. `preview-refs/pull/142/merge`. 

However, I noticed that `github.ref` is inconsistent with [documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) and is giving me just the branch name. Looks like it's actually the base branch name? Maybe I'm doing something wrong but it seems weird.

GitHub context dump from one of the runs that happened when a PR to `main` was merged. Notice that the `ref` is main instead of `refs/pull/142/merge` :

![image](https://user-images.githubusercontent.com/2320572/194967280-0b6515c7-39be-48de-b26d-5f190371d6d3.png)

My workflow:

```yaml
name: PR Preview Cleanup

on:
  pull_request:
    types: 
      - closed
    branches:
      - main
      - dev

jobs:
  undeploy:
    runs-on: ubuntu-latest
    name: Remove Azure SWA preview deployment
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_POND_0F4BE7D10 }}
          action: "close"
  remove-env:
    runs-on: ubuntu-latest
    name: Remove PR preview environment
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"    
      - uses: jlian/delete-deployment-environment@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: preview-${{ github.ref }}
```
