### DISCUSSION TITLE
running gui application on github hosted runner

### DISCUSSION THREAD

**Discussion by adrian-herscu** [community/community#36704] [Actions]
For testing purposes, is it possible to run GUI applications on GitHub-hosted runners?
I tried to run Windows Calculator (Microsoft.WindowsCalculator_8wekyb3d8bbwe!App) on "windows-2022" via WinAppDriver and it fails with "WebDriverException: Package was not found".

Any suggestion(s)?

TIA, Adrian.

P.S. here is my GitHub Actions workflow for the above:

```yml
# ISSUE fails with WebDriverException: Package was not found
  # see https://github.com/QA-Automation-Starter/qa-automation/actions/runs/3234841483/jobs/5298454871

  build-and-test-on-windows:
    name: windows build&test
    # see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: windows-2022
    environment: development

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          settings-path: ${{ github.workspace }}

      # ISSUE somehow should run WinAppDriver
      # see https://github.com/microsoft/WinAppDriver/issues/1722
      # and https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

      # TODO maybe, should re-publish the site from here (?)
      - run: |
          choco install -y autologon
          autologon %USERNAME% $USERDOMAIN%
          start cmd /c "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"
          cd qa-testing-example
          mvn install ^
            -s %GITHUB_WORKSPACE%\settings.xml ^
            -Pmode-build-fast,mode-build-quiet,environment-default,testing-windows,device-windows
        shell: cmd
```

Also posted on
https://stackoverflow.com/questions/74085088/running-gui-application-on-github-hosted-runner
