### DISCUSSION TITLE
Permissions required to write commit comments in Workflows?

### DISCUSSION THREAD

**Discussion by esamattis** [community/community#36778] [Actions]
I want to write a commit comment from my workflow with [actions/github-script](https://github.com/actions/github-script).

Example:

```yaml
    - name: Add commit comment
      uses: actions/github-script@v6
      with:
        script: |
          let body = 'This commit is packaged to npm. ';
          body += 'Install with\n';
          body += '```\n';
          body += 'npm install --save-exact ${{ env.npm_name }}@${{ env.next_version }}';
          body += '\n```';
          await github.rest.repos.createCommitComment({
            commit_sha: context.sha,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body,
          });
```

Getting this error

```
Unhandled error: HttpError: Resource not accessible by integration
```

What permissions should I add?

None of the [documented permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)[1] really match with this use case. I already tried `contents: write` but that was not enough.

If I don't define any permissions the above step works.

[1]:
```yaml
permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  id-token: read|write|none
  issues: read|write|none
  discussions: read|write|none
  packages: read|write|none
  pages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none
```
