### DISCUSSION TITLE
I am not able to access a passed matrix strategy variable in a reusable workflow

### DISCUSSION THREAD

**Discussion by atanas-hristov-deltatre** [community/community#36776] [Actions] [answered]
So here is a release workflow, which will trigger the deploy workflow using a matrix strategy

```
  deploy-app:
    needs: [ release ]
    strategy:
      fail-fast: false
      matrix:
        target: [ Tizen, WebOS ]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      target: ${{ matrix.target }}
      environment: ${{ github.event.inputs.environment }}
      semver: ${{ github.event.inputs.semver }}
``` 

It is visible, we pass the required(target, environment, semver) variables. While the environment, semver are provided when manually triggering the release workflow, the target is passed from a matrix strategy variable

Here is a the deploy workflow where I am trying to use them:

```
name: Deploy workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'On which environment the run should deploy'
        required: true
      semver:
        type: string
        description: The version of the app, which will be deployed.
        required: true
      target:
        type: string
        description: The target for which the build should be deployed
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: 'On which environment the run should deploy'
        required: true
        default: test
        type: choice
        options:
        - test
        - stag
        - prod
      semver:
        description: The version of the app, which will be deployed.
        required: true
      target:
        description: The target for which the build should be deployed
        required: true
        default: Tizen
        type: choice
        options:
        - Tizen
        - WebOS

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TARGET: ${{ github.event.inputs.target }}
      SEMVER: ${{ github.event.inputs.semver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: echo ${{ env.TARGET }}
      - run: echo ${{ env.SEMVER }}
      - run: echo ${{ github.event.inputs.target }}
      - run: echo ${{ github.event.inputs.environment }}
      - run: echo ${{ github.event.inputs.semver }}
```

So my idea is to be able to trigger the deploy workflow manually and when a release is triggered. 
If I trigger the deploy workflow manually and provide all the variables, the workflow passes without a problem
If the deploy workflow is triggered by the release workflow,  -run: echo ${{ github.event.inputs.target }} shows that the variable is not set. The rest of the variables, which are not matrix strategy related, are set as expected. Passing the inputs variable using environment context doesn't seem to help as well.
I've checked the "Set up Job" for every deploy-app job in the deploy workflow, And I see that the inputs object is initialized correctly. 
Check the screenshot of the deploy workflow job run:

![image](https://user-images.githubusercontent.com/101338820/196926130-8d3d538b-888d-4209-b1e2-76689215c754.png)
 So I wonder what I am missing or doing wrong? I'd appreciate some ideas.

Thanks in advance :)
