### DISCUSSION TITLE
Github Actions if matrix

### DISCUSSION THREAD

**Discussion by AntoniosBarotsis** [community/community#36831] [Actions] [answered]
I have an action that looks like the following

```yml
jobs:
  build_test_run:
    name: Build, test and run on ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: aarch64-unknown-linux-gnu , os: ubuntu-22.04 }
          - { target: x86_64-unknown-linux-gnu  , os: ubuntu-22.04 }
          - { target: x86_64-apple-darwin       , os: macos-12     }
          - { target: x86_64-pc-windows-msvc    , os: windows-2022 }

    steps:
      # ...
      - name: Run
        run: ...
        if: ${{ contains(${{ matrix.job.target }}, 'linux') }}
      # if: contains(${{matrix.job.target}}, 'linux') is also not working (everything is true for some reason)
```

But I can't get that last line to work properly, does anyone know how to check if the `matrix.job.os` variable contains `linux`?
