### DISCUSSION TITLE
self-hosted runner action hangs on a gradlew command

### DISCUSSION THREAD

**Discussion by nwhobart** [community/community#36920] [Actions]
Hello! I'm kind of stuck on this problem and no amount of GoogleFu has gotten me out of it. We have a very simple action that has this step: 

```
      - name: Test
        id: test
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.secret1 }}
          SONAR_TOKEN: ${{ secrets.secret2 }}
        with:
          arguments: --parallel clean test coverage ktlintCheck detekt
```

This step takes about 5 minutes to complete using `ubuntu-latest` but will run for an infinite amount of time using a `self-hosted` runner. 

<img width="142" alt="image" src="https://user-images.githubusercontent.com/4466324/197289091-e527fc73-53f4-4f5a-87ef-338225d79eed.png">

The step will hang after the same `Task` almost every single time. There is no logging around why it hangs or what it is doing in the background. Turning up the logging on gradle didn't help either. 

Running: 

Gradle: `6.7`
`summerwind/actions-runner:v2.298.2-ubuntu-20.04-e1762ba` [self-hosted image](https://hub.docker.com/layers/summerwind/actions-runner/v2.298.2-ubuntu-20.04-e1762ba/images/sha256-b7170455bf840a66094b95801578222813d0e64c4a9eddf3a29758f606e7a69d?context=explore)

Just looking for other things to try. Worst-case scenario we just keep using `ubuntu-latest` but I really don't like not knowing why this won't work on our self-hosted runners.
