### DISCUSSION TITLE
It says it can't find the typescript file

### DISCUSSION THREAD

**Discussion by sametpalitci** [community/community#37091] [Actions]
Hello all, 
I am using the GitHub action bot with typescript, but it cannot find the `index.js` file in the dist file. 
If I select the `index.ts` file in the src file, it finds it.
How can I get it to find the `dist/index.js` file?
Thank you

![Screen Shot 2022-10-24 at 11 33 39](https://user-images.githubusercontent.com/25365040/197483440-ce88d711-6bc0-4e05-975d-0445a1d1466c.png)
.github/workflows
```yaml
name: xxx
run-name: xxx🚀
on: [issue_comment]

jobs:
  xx-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm
        run: |
          npm install
          npm run build
      - name: inside checking
        run: |
          cd dist && ls -l
      - name: github actions test
        id: action-bot-check
        uses: samet-test/test-1@v0.2.8
```
action.yml
```yaml
..
runs:
  using: "node16"
  main: "dist/index.js"
```
