### DISCUSSION TITLE
After a PR changes the base branch, which branch does the workflow run on?

### DISCUSSION THREAD

**Discussion by Anthony-Tubi** [community/community#37098] [Actions]
There are 3 branches and a workflow in my repo. 
- master
- dev
- bugfix

on master
```
name: Action Test
on:
  pull_request:
  push:
    branches:[master, dev, bugfix]

jobs:
  setup:
    runs-on: ubuntu-latest
    ....
```

on dev
```
name: Action Test
on:
  pull_request:
  push:
    branches:[master, dev, bugfix]

jobs:
  setup:
    runs-on: self-hosted
    ....
```

Recently I've been using the self-hosted runner, I modified the value of runs-on on the dev branch to use the self-hosted runner, but I still use the GitHub host's ubuntu system on the master branch.

I check out the `bugfix` branch base on the `master` branch and fixed some bugs. 
Then I created a PR to merge `bugfix` into `master`, but I chose the wrong base branch to dev, and the workflow started running on `self-hosted`.

When I realized the mistake, I changed the base branch to `master`, then the workflow started rerunning.
Confusing things happened, the workflow still ran on `self-hosted` runner, which I can't understand. 
I tried to fix the issue, closed the PR, and reopened it. It was successful. ran back to `ubuntu-latest`

I wonder why this happens
