### DISCUSSION TITLE
Multiple Self-hosted Github actions runners with custom labels

### DISCUSSION THREAD

**Discussion by ericpardee** [community/community#37116] [Actions] [answered]
Similar to [#26049](https://github.com/orgs/community/discussions/26049) but now custom labels are supported.

I have two self-hosted Github Action Runners

1. The first runner is running in my dev env

2. The second runner is running in my QA env

Is there a way to select these runners based on the environment the action is being executed on?

E.g. I have a `deploy-dev.yml` that runs on the `dev` branch, sets inputs, including `ENVIRONMENT: "dev"`, the calls a common `deploy.yml`. Same for QA.

In the common `deploy.yml`, I have:
```
  migrate:
    name: Database Migrations
    runs-on: [self-hosted, "${{ github.event.inputs.ENVIRONMENT }}"]
```
But this errors with:
```
Error when evaluating 'runs-on' for job 'migrate'. deploy.yml@d0b56f230cff5979a5d2b16a26cc8d66a45028ca (Line: 141, Col: 28): Unexpected type of value '', expected type: String.```

**Comment by ChristopherHX** [comment, marked as answer]
Try replacing `github.event.inputs` with `inputs`.

reusable workflows do not use github.event.inputs, it's part of a workflow_dispatch specfic event payload.
In recent versions of actions is the 'inputs' context also available for the workflow_dispatch trigger.

Similar case: https://github.com/orgs/community/discussions/36776#discussioncomment-3923869

If you want to be able to specify multiple labels of a job you can do it like this using json encoding
```yaml
on:
  workflow_call:
    inputs:
      labels:
        type: string
        default: |-
          [ "self-hosted" ]
jobs:
  _:
    runs-on: ${{ fromjson(inputs.labels) }}
    # runs-on: [ self-hosted, "${{ fromjson(inputs.labels)" }} ] # Use this if you want to merge some default labels and allow to add a custom list of labels
    steps:
    - run: exit 0
```

**Edit** Quoted second runs-on example, commented out in the sample

**Reply by ericpardee** [reply]
Thank you, that worked.

Here's how I did it, `deploy-dev.yml` has:
```
jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      SHR_LABELS: '["self-hosted", "dev"]'
```

Then `deploy.yml` has:
```
on:
  workflow_call:
    inputs:
      SHR_LABELS:
        description: A list of labels to apply to the GitHub Self-Hosted Runner
        type: string
        required: true
        default: |
          [
            "self-hosted"
          ]
```
and below in `deploy.yml`, in my `migrate` job, I have:
```
  migrate:
    name: Database Migrations
    runs-on: ${{ fromJSON(inputs.SHR_LABELS) }}
```
