### DISCUSSION TITLE
Using conditional to trigger a pull request workflow

### DISCUSSION THREAD

**Discussion by drey0143143** [community/community#37149] [Actions] [answered]
I have 2 workflows below which runs on a pull request to staging. I only want workflow1 to run if the PR has dependency upgrade flag and workflow2 to run if the PR does not have dependency upgrade flag. How can I achieve this? sinnipet of my workflow is below
```
name: workflow1
on:
  pull_request:
   branches:
     - staging

jobs:
  plan:
    name: "Terragrunt Plan"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Terragrunt Init
        id: init
        run: terragrunt init -ugrade

name: workflow2
on:
  pull_request:
   branches:
     - staging

jobs:
  plan:
    name: "Terragrunt Plan"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Terragrunt Init
        id: init
        run: terragrunt init -lockfile=readonly

**Comment by FatChicken277** [comment, marked as answer]
You can use [git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging)

```
name: workflow1
on:
  pull_request:
   branches:
     - staging
    tags:
      - 'upgrade'
```
 
Or u can use [github labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels)

```
jobs:
  plan:
    if: ${{ github.event.label.name == 'upgrade' }}
    name: "Terragrunt Plan"
```

If I answered your question, then you should close the question by click accept answer button :heart:
