### DISCUSSION TITLE
Use GHCR image in `uses` field of job step?

### DISCUSSION THREAD

**Discussion by abatilo** [community/community#37158] [Actions]
I have an image that's being built and pushed to the GHCR.

I'm trying to use that image, which is itself a GitHub Action using the following syntax that's documented:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-the-github-packages-container-registry

```
- uses: docker://ghcr.io/$owner/$name:$tag
```

I have the package configured with the settings that allows access by the repository that I'm trying to use. In fact, if I do:
```
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker pull ghcr.io/$owner/$name:$tag
```

The above will work. However, there's no way for me to do a `docker/login-action` for the actions that get downloaded when the workflow is being setup.

Is there no way to use private/internal GHCR images as a job step?
