### DISCUSSION TITLE
Carry the previous run result

### DISCUSSION THREAD

**Discussion by tisonkun** [community/community#37181] [Actions]
Take [this workflow file](https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/.github/workflows/ci-semantic-pull-request.yml) as an example:

```yaml
name: Semantic Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
```

When a new commit gets pushed and triggers a `synchronized` event, other workflows start while this one is skipped. Now, if you take a look at that final check status list, the result of the "Semantic Pull Request" vanished. Thus, we cannot require this task before merging.

I'd prefer to keep the status reported is no new run is triggered or have a method to carry the previous run result.
