### DISCUSSION TITLE
Trim an input passed to a reusable workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#37238] [Actions]
I am invoking a reusable workflow as follows

```
 build-python-images:
    name: build the python images
    needs:
      - create-python-and-debian-matrix
    strategy:
      matrix:
        python-builds: ${{ fromJSON(needs.create-python-and-debian-matrix.outputs.python_builds) }}
        debian-builds: ${{ fromJSON(needs.create-python-and-debian-matrix.outputs.debian_builds) }}
      fail-fast: true
    uses: MyOrg/myrepo/.github/workflows/reusable.yaml@master
    with:
      image_name: python/${{ matrix.python_builds }}
``` 

The problem is `matrix.python_builds` evaluates to e.g. `3.9.17` etc.

I want to trim the `patch` version so that my `image_name` ends up `python/3.9`

Is this possible?
