### DISCUSSION TITLE
How to change deployment url for github pages action

### DISCUSSION THREAD

**Discussion by willeppy** [community/community#37267] [Actions]
I am building a site for my repo using a github actions workflow. To deploy the website, I run the below action. How can I change the url where this site is deployed? 

Specifically, I would like to add a route to the end so that instead of deploying to `example.com/project` it deploys to `example.com/project/notebook`. It seems to be set by `${{steps.deployment.outputs.page_url}}`. I tried adding notebook to the end of this like `${{steps.deployment.outputs.page_url}}notebook` with no luck.

Here is my deploy action that runs after build in the yaml:
```yml
 deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}} # How can i change this url??

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1


```

**Comment by AugustinMauroy** [comment]
I have same question

**Comment by hotenov** [comment]
@willeppy  According to action [source code](https://github.com/actions/deploy-pages/blob/69a62cdfa4c32e0d925268597986261876cac577/src/deployment.js#L115), you cannot change `page_url` output for now.  
It's composed from GitHub API response for your repository and has no inputs (variables) modificators (**hardcoded**).

Of course, you can alter this value, adding additional step to deploy job:

```yaml
...
    environment:
      name: github-pages
      url: ${{ steps.change-page-url.outputs.new_page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Override page_url
        id: change-page-url
        run: echo "new_page_url=${{ steps.deployment.outputs.page_url }}notebook/" >> $GITHUB_OUTPUT
...
```

But this option will only affect (change) URL for job output, for example:  
![image](https://user-images.githubusercontent.com/11818507/198880119-233b5b36-cdb3-4f75-9f9a-932e0c5b19e8.png)

All deploy will be done for your repository Pages URL (`<user>.github.io/<repo_name>/`) which is not configured in `v1`.  
Even "preview" functionality in alpha now, without any words how to use it. We can only wait when developers add this feature and this input parameter for changing result `page_url` or describe how to use `preview` input.

For quick response (new version), I think you should create an issue (with feature request) in action's repo:  
https://github.com/actions/deploy-pages/issues
