### DISCUSSION TITLE
Feature Request: Re-run failed jobs instead of whole workflow when using Re-usable Workflow

### DISCUSSION THREAD

**Discussion by mrk-han** [community/community#37269] [Actions]
There are a few documented ways to re-run failed jobs, from GH Command Line or GH GUI, but I haven't found a way of running or rerunning a workflow which would re-run failed jobs as a specific workflow.

For my specific use-case, there is a matrix of emulator tests that are spun up. Due to the sometimes flaky nature of emulators on Github runners, sometimes one of the matrixes fails. I would like to have a caller workflow use a callee (or reusable workflow) like the follow, but instead of re-running the ENTIRE workflow, I would only like to run the failed jobs within the workflow for that PR when someone comments "rerun tests"

```yml
name: Re-Run All Failed or Cancelled/Timed-Out Jobs
on:
  workflow_call:
  issue_comment:
    types: [created]
  
jobs:
  rerun-tests-job:
    if: contains(github.event.comment.body, 'rerun tests')
    uses: org/repo/.github/workflows/main.yml@main
 ```
 
I'm not sure where it would go, but perhaps under `workflow_call.failed_jobs` so we could use the syntax like the following:

```yml
on:
  workflow_call:
    types: [failed, canceled] # Runs only the jobs in the called workflow that were canceled or failed in the previous run
```
