### DISCUSSION TITLE
If triggering a workflow from a PR Comment (issue_comment), please default to the context of the PR which was commented on.

### DISCUSSION THREAD

**Discussion by mrk-han** [community/community#37288] [Actions]
I have a main workflow, which involves running a series of builds from a matrix on various emulators. Some of these jobs can get flakey from small things like emulator boot time. 

So, I want to be able to comment on a PR with "Run Tests" and have that main workflow kick off the "checks" again, which will run against the context (latest commit hash) of the PR and report back to the PR. 

I also want this workflow to just re-run the main workflow, which is a reusable workflow, so I don't have to copy the entire workflow's code into the new "comment triggered" workflow. Right now, that workflow defaults to running on the "default/master/main" branch which is not the PR branch.

There is a workaround to checkout a ref of the PR, but when using a reusable workflow this isn't easy or that feasible. 

Workflow:
```
name: Re-Run Tests on PR Comment Workflow
on:
  issue_comment:
    types: [created]
  
jobs:
  rerun-tests-job:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'run tests')
    uses: ./.github/workflows/main.yml
 ```
 
 Main workflow just as `workflow_call:` so it can be called by the above workflow.
