### DISCUSSION TITLE
security tab doesn't render SARIF file correctly

### DISCUSSION THREAD

**Discussion by eyarz** [community/community#37305] [Code Security]
I have a GH action to help users prevent Kubernetes misconfigurations in their manifests. Each manifest can have several misconfigurations.
My goal is to generate a SARIF output that will show the user the location(s) (line number) of the misconfigurations in his manifests.

This is my problem - when I create the SARIF file and GItHub code security is rendering the file, it always shows only one misconfiguration location per manifest file. Is it possible that GH doesn’t support multiple locations in one file?

This result section has two locations of the same violation (startLine 2 & 10):
```yaml
      "results": [
        {
          "ruleId": "CONTAINERS_MISSING_MEMORY_LIMIT_KEY",
          "ruleIndex": 0,
          "message": {
            "text": "Missing property object `limits.memory` - value should be within the accepted boundaries recommended by the organization"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "exampleFile.yaml"
                },
                "region": {
                  "startLine": 1,
                  "endLine": 1,
                  "startColumn": 2,
                  "endColumn": 2
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "exampleFile.yaml"
                },
                "region": {
                  "startLine": 10,
                  "endLine": 10,
                  "startColumn": 2,
                  "endColumn": 10
                }
              }
            }
          ]
        }
```
But only the first one (startLine 2) appears in the security tab section:
![image](https://user-images.githubusercontent.com/19731161/197955004-c68d9c48-c6eb-44f8-ac1d-cdf18847c886.png)
