### DISCUSSION TITLE
Sporadic "non-existing domain" trying to connect to configured services

### DISCUSSION THREAD

**Discussion by OldhamMade** [community/community#37348] [Actions]
We have a CI workflow set up on GitHub, and our workflow file looks similar to this:
```yaml
jobs:
  tests:
    runs-on: ubuntu-20.04
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
        ports:
          - 9200:9200
        env:
          ELASTIC_PASSWORD: ${{ env.ELASTICSEARCH_PASSWORD }}
          discovery.type: single-node
          xpack.security.enabled: true
        options: >-
          --health-cmd="curl http://localhost:9200/_cluster/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - run: ./runtests
```

Our workflow output shows:

```
> Starting elasticsearch service container
> Waiting for all services to be ready
  ...
  elasticsearch service is healthy.
```

In general, our tests will then execute and complete without issue. However, often we'll instead see errors like:

```
"Could not connect to Elasticsearch: \"non-existing domain\""
```

This will happen for _all_ the tests in that particular test run, despite the service showing as healthy. Once a PR gets this error, the system will not go back to a successful test run. New PRs may or may not experience the same error.

We have tried cache-busting which can be occasionally successful but doesn't always work.
