### DISCUSSION TITLE
Codespaces not forwarding ports when using host:port format

### DISCUSSION THREAD

**Discussion by modamod** [community/community#37360] [Codespaces]
I am using docker-compose as a way to setup the repository and I like to expose different ports from various compose services, but code spaces has no ports forwarded 

This is the .devconainer config I am using
<details>

<summary>.devcontianer.json</summary>

```
{
    "name": "Snipe-it",
    "service": "cli",
    "remoteUser": "user",
    "shutdownAction": "stopCompose",
    "workspaceFolder": "/workspaces/snipe-it",
    "dockerComposeFile": "docker-compose.yaml",
    "forwardPorts": ["nginx:8000", "mariadb:3306"],

    "extensions": [
        "coenraads.bracket-pair-colorizer-2",
        "cschleiden.vscode-github-actions",
        "eamodio.gitlens",
        "github.vscode-pull-request-github",
        "ms-azuretools.vscode-docker",
        "ms-vsliveshare.vsliveshare",
        "vscode-icons-team.vscode-icons",
        "visualstudioexptteam.vscodeintellicode"
    ],
    "postStartCommand": "sh /workspaces/snipe-it/.devcontainer/bash/startup.sh"
}
```

</details>

And this is the docker-compose.yml associated with it,

<details>

<summary>docker-compose.yml</summary>

```
version: "3.9"
services:
  cli:
    container_name: cli
    networks:
      - codespaces
    image: modamod/php7.4-cli
    volumes:
      - ..:/workspaces/snipe-it
    env_file:
    - .env.docker
    depends_on:
      - mariadb


  fpm:
    container_name: fpm
    networks:
      - codespaces
    image: modamod/php7.4-fpm
    volumes:
      - ..:/workspaces/snipe-it
    user: 1000:1000
    env_file:
    - .env.docker
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx
    networks:
      - codespaces
    build: nginx
    volumes:
      - ..:/workspaces/snipe-it
    depends_on:
      - fpm
    env_file:
    - .env.docker
    ports:
      - "8000:8000"


  mariadb:
    container_name: mariadb
    networks:
      - codespaces
    image: mariadb:latest
    env_file:
    - .env.docker
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    networks:
      - codespaces
    image: redis:6.2-alpine


networks:
  codespaces: {}

```

</details>

Please let me know what I am doing wrong. 

Thank you.
