### DISCUSSION TITLE
Red cross against commit when all builds successful but coverage decreased by 0.06%

### DISCUSSION THREAD

**Discussion by royhills** [community/community#37394] [Actions]
I run actions for Build (against Ubuntu and MacOS), CodeQL Analyze, and coveralls Coverage on each commit.

After a commit, the Build and Analyse actions reported success but the Coverage action reported failure and as a result a red cross gets put against the commit, which seems a little harsh especially as the commit was to update the NEWS file that doesn't contain any code.

Is it possible to prevent minor decreases in coverage from reporting the overall status as failed, especially for little rounding errors like this?

My coverage workflow is:

```
name: coverage
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install libpcap and lcov
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libpcap0.8-dev lcov
      - name: autoreconf
        run: autoreconf --install
      - name: configure with gcov
        run: ./configure --enable-gcov
      - name: make
        run: make
      - name: make check
        run: make check
      - name: create lcov.info
        run: lcov --directory . --capture --output-file lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
```
Here's a screenshot of the action results:

<img width="682" alt="2022-10-26" src="https://user-images.githubusercontent.com/5235590/198126291-4b075300-73f6-4ee2-94cd-ce91ac035181.png">
