### DISCUSSION TITLE
Referencing the job calling a reusable workflow

### DISCUSSION THREAD

**Discussion by magni-** [community/community#37414] [Actions] [answered]
In the [Reusable Workflow docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows), it states that the `github` context is associated with the caller workflow:

> When a reusable workflow is triggered by a caller workflow, the `github` context is always associated with the caller workflow.

I took that to mean that `github.job` would point to the caller workflow's job. It appears that is not the case:

```yaml
on: workflow_call
jobs:
  called:
    steps:
      - run: 'echo "${{ github.job }}"'
 ```
```yaml
on: push
jobs:
  first-caller:
    uses: ./.github/workflows/reusable.yml
  second-caller:
    uses: ./.github/workflows/reusable.yml
```

I expected this to output `first-caller` and `second-caller`, but instead it outputs `called` twice.

Is there a way to reference the calling job from the called job?

**Comment by nicholasbergesen** [comment, marked as answer]
Hi @magni-, 

An option you could consider is to pass the data points you need to your called workflows using [inputs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs). Once this is passed in you can use the [fromJSON](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson) expression to create an object from the Json string in the child workflows.

Caller workflow:
```yaml
on: push
jobs:
  first-caller:
    uses: ./.github/workflows/reusable.yml
    with:
      job: ${{ github.job }}
  second-caller:
    uses: ./.github/workflows/reusable.yml
    with:
      job: ${{ github.job }}
```
Called workflow:
```yaml
on: 
  workflow_call:
    inputs:
      job:
        type: string
        required: true
jobs:
  called:
    steps:
      - run: 'echo "${{ inputs.job }}"'
```
