### DISCUSSION TITLE
Creare multivariant matrix strategy from step

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#37478] [Actions]
I have the following GitHub actions step.

The workflow takes as input a comma separated list of python (`major.minor`) versions,  infers the full (`major.minor.patch`) version and sets then as outputs to be leveraged by a subsequent job.

Here it goes:

```
      - name: get full python versions
        id: set-python-matrix
        env:
          pversions: ${{ inputs.python_versions }}
        shell: bash
        run: |
          OUT=""
          for version in ${pversions//,/ }
          do
              docker pull python:${version}-buster
              VER=$(docker inspect python:${version}-buster | jq '.[0].Config.Env' | grep PYTHON_VERSION | cut -d'=' -f2 | cut -d'"' -f 1)
              OUT+="${VER},"
          done
          PYTHON_BUILDS=$(echo "\"${OUT::-1}\"" | jq -c 'split(",")')
          echo "python_builds=${PYTHON_BUILDS}" >> $GITHUB_OUTPUT
```

This works as expected. So I follow up by calling a job that uses those versions in a `matrix` strategy

```
 build-python-images:
    name: build the python images
    needs:
      - create-python-and-debian-matrix
    strategy:
      matrix:
        python-builds: ${{ fromJSON(needs.create-python-and-debian-matrix.outputs.python_builds) }}
      fail-fast: true
    uses: MyOrg/MyRepo/.github/workflows/reusable.yaml@master
    with:
      image_name: python-custom
      image_tag: ${{ matrix.python-builds }}}
```

Here is the challenge:

I **also** need a correspondence between the `major.minor` and `major.minor.patch` since at the end of the day I want to name my image with `major.minor` (and not `major.minor.patch`) although the later is **also** needed. So I want to be able to do sth like this

```
 build-python-images:
    name: build the python images
    needs:
      - create-python-and-debian-matrix
    strategy:
      matrix:
        python-builds: ${{ fromJSON(needs.create-python-and-debian-matrix.outputs.python_builds) }}
      fail-fast: true
    uses: MyOrg/MyRepo/.github/workflows/reusable.yaml@master
    with:
      image_name: python-custom/${{ matrix.python-versions.python-builds-not-full }}} # <- here I wanna use `major.minor`
      image_tag: ${{ matrix.python-versions.python-builds }}} # <-- here I use the `major.minor.patch`)
```

I assume the way to go about it is having my step above producing the output yielding something like a `json` map e.g. so that I use values such as `${{ matrix.python-versions.majorminorpatch }}` and `${{ matrix.python-versions.majorminor }}`

I literaly have no clue how to do thus with `bash` so any help / hints will be extremely appreciated.
