### DISCUSSION TITLE
How to Unique each workflow.

### DISCUSSION THREAD

**Discussion by Nimeshkottege** [community/community#37488] [Actions]
In my project GitHub actions, there have several workflow runs. But if I push a commit, all workflows start running without running only one that belongs to the commit. So I think need to Unique each workflow. So have any method to unique the yml file which needs to correctly identify when pushing a commit? 

Or If I can stop workflows auto-running after pushing the commit, then I can run only specific target workflow. But I want all workflows in enable mode. cannot be disabled. Have any option without disabling?

**Comment by jsoref** [comment]
you can easily set
```yaml
on:
   push:
     paths:
     - .github/workflows/this-workflow.yml
```
