### DISCUSSION TITLE
Dependabot: use of YAML aliases

### DISCUSSION THREAD

**Discussion by 0ssigeno** [community/community#37496] [Code Security]
Hi!
There is any plan to support aliases in the dependabot yaml configuration file?
An example of use case:
```yaml
version: 2
x-configuration: &configuration
  schedule:
    interval: "weekly"
    day: "tuesday"
  target-branch: "develop"



updates:
  - package-ecosystem: "pip"
    directory: "/"
    <<: *configuration


  - package-ecosystem: "docker"
    directory: "/docker"
    <<: *configuration


  - package-ecosystem: "github-actions"
    directory: "/"
    <<: *configuration
```
