### DISCUSSION TITLE
Why my github runner action self-hosted is stuck queue?

### DISCUSSION THREAD

**Discussion by helfiquadrant** [community/community#37503] [Other Feature Feedback, Questions, & Ideas]
Hi all, why is my GitHub action self-hosted runner stack in queues?

workflow 1
```
Name: Pull Request

on:
  pull_request:
    branches: [ main ]

concurrency: 
  group: pr-workflow-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  install_dependency:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install library
        run: make install_dependency
      - name: testing sleep
        run: sleep 600
  unit_test:
    needs: install_dependency
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run unit test
        run: make test
```

workflow 2
```
name: Date Evaluation Workflow

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry Run'
        default: 'True'
        required: true
      client_name:
        description: 'Client Name'
        default: ''
        required: true
      filetype:
        description: 'File Type'
        default: ''
        required: true
      total_obj_per_bucket:
        description: 'Total Obj Per Bucket'
        default: '50'
        required: true
      countries:
        description: 'Countries'
        default: ''
        required: true
      year:
        description: 'Year'
        default: ''
        required: true
      month:
        description: 'Month'
        default: ''
        required: true
      start_day:
        description: 'Start Day'
        default: ''
        required: true
      end_day:
        description: 'End Day'
        default: ''
        required: true
      extra_configs:
        description: 'Extra Configs'
        default: ''
        required: false

jobs:
  install_dependency:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install library
        run: make install_dependency
  unit_test:
    needs: install_dependency
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run unit test
        run: make test
  run_data_eval:
    needs: [install_dependency, unit_test]
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: check input workflow
        run: |
          echo "dry_run: ${{ github.event.inputs.dry_run }}"
          echo "client_name: ${{ github.event.inputs.client_name }}"
          echo "filetype: ${{ github.event.inputs.filetype }}"
          echo "total_obj_per_bucket: ${{ github.event.inputs.total_obj_per_bucket }}"
          echo "countries: ${{ github.event.inputs.countries }}"
          echo "year: ${{ github.event.inputs.year }}"
          echo "month: ${{ github.event.inputs.month }}"
          echo "start_day: ${{ github.event.inputs.start_day }}"
          echo "end_day: ${{ github.event.inputs.end_day }}"
          echo "extra_configs: ${{ github.event.inputs.extra_configs }}"
      - name: run data evaluation
        run: |
          make run_dataeval \
          dry_run="${{ github.event.inputs.dry_run }}" \
          client_name="${{ github.event.inputs.client_name }}" \
          filetype="${{ github.event.inputs.filetype }}" \
          total_obj_per_bucket="${{ github.event.inputs.total_obj_per_bucket }}" \
          countries="${{ github.event.inputs.countries }}" \
          year="${{ github.event.inputs.year }}" \
          month="${{ github.event.inputs.month }}" \
          start_day="${{ github.event.inputs.start_day }}" \
          end_day="${{ github.event.inputs.end_day }}" \
          extra_configs="${{ github.event.inputs.extra_configs }}"
```

I think this is bugs from Github because it running well before today
