### DISCUSSION TITLE
Access key / value from matrix object

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#37566] [Actions]
Assuming I have a step that produces the following output

```
{
  "foo": 1,
  "bar": 2,
  "baz": 3
}
```

How can I then use / access both the keys and values of the object above in a `matrix` strategy, i.e. something like

```
  build-python-images:
    needs:
      - create-python-matrix
    strategy:
      matrix:
        python-builds: ${{ fromJSON(needs.create-python-and-debian-matrix.outputs.python_builds) }}
    uses: Org/repo/.github/workflows/reusable.yaml@master
    with:
      someinput: ${{ matrix.python-builds.key }}
      anotherinput: ${{ matrix.python-builds.value }}
```
