### DISCUSSION TITLE
Reuse paths filter in GitHub Action?

### DISCUSSION THREAD

**Discussion by idleberg** [community/community#37645] [Actions] [answered]
I've recently learned about the possibility to restrict workflows to run only when certain files in the repository have changed. Now I'm wondering if it's possible to avoid repetition as seen in this example.

```yaml
on:
  push:
    branches:
    - main
    paths:
    - 'src/**'
    - 'index.html'
    - 'package.json'
    - 'pnpm-lock.yaml'
  pull_request:
    branches:
    - main
    paths:
    - 'src/**'
    - 'index.html'
    - 'package.json'
    - 'pnpm-lock.yaml'
```

Is there something similar to `job.*.strategy.matrix` that helps me keeping the snippet above DRY?
