### DISCUSSION TITLE
1302 Container creation failed

### DISCUSSION THREAD

**Discussion by ghost** [community/community#3766] [Codespaces]
Hi,
I have a codespace with a custom Dockerfile/devcontainer. It fails to build but it doesn't say what failed or how. All I get is the following log message:
```
2021-04-12T17:43:09: Failed to create container.
Error: Command failed: docker-compose 
  -f /var/lib/docker/codespacemount/workspace/chessladder/docker-compose.prod.yml -f 
  /var/lib/docker/codespacemount/workspace/chessladder/docker-compose.dev.yml -f 
  /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config --services

Error Code: 1302
Container creation failed.
Creating recovery container
```
(I've cleaned this up a bit since this used to all be on one line.)
___
Here are my config files:

**`.devcontainer/devcontainer.json`**
```jsonc
{
	"name": "Node",

	// Start with prod config and 
	// override with dev config
	"dockerComposeFile": [
		"../docker-compose.prod.yml", 
		"../docker-compose.dev.yml"
	],
	"service": "web",
	"workspaceFolder": "/app",

	// VSCode Options
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash"
	},
	"extensions": [
		"christian-kohler.npm-intellisense"
	]
}
```

**`docker-compose.prod.yml`**
```yml
version: '3.9'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file: .env
        ports: 
            - 5000:5000
```

**`docker-compose.dev.yml`**
```
# Extends docker-compose.prod.yml
version: '3.9'

services:
    web:
        build:
            dockerfile: Dockerfile.dev
        ports: 
            - 80:80
            - 443:443
            - 3000:3000
            - 8080:8080
        volumes:
            - .:/app:cached

        environment:
            NODE_ENV: development

        tty: true
        command: bash
```

**`Dockerfile.dev`**
```Dockerfile
FROM node:lts
RUN curl https://cli-assets.heroku.com/install.sh | sh
```
___
Any idea what's going on here?
