### DISCUSSION TITLE
workflow_dispatch & environment secrets

### DISCUSSION THREAD

**Discussion by my-pal-jason** [community/community#37686] [Actions] [answered]
In a manually triggered action, how does one pass in an environment and make that environment's secrets available to the action?

**Comment by antonblr** [comment, marked as answer]
There is an input `type: environment` you can use in `workflow_dispatch.inputs` (see https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/). 
Something like that, you should be able to pick one of the available environments to run the job with:
```yaml
on:
  workflow_dispatch:
    inputs:
     environment:
        type: environment
        description: Select the environment
```

**Reply by my-pal-jason** [reply]
Thanks for the response.  Unfortunately, even with a selected environment, the secrets context does not appear to be set.

**Reply by antonblr** [reply]
What your workflow looks like? Did you try setting environment name from the inputs? 

```yaml
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
```
