### DISCUSSION TITLE
Get the membership in terms of teams of a PR comment author

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#37769] [Actions]
I have the following workflow

```
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

env:
  ALLOWEED_OVERRIDING_TEAM_NAME: someteam

jobs:
  check:
    if: github.event_name == 'issue_comment'
    name: check if the pr should be merged based on comment made
    runs-on: ubuntu-latest
    steps:

      - name: check the pr comment made
        uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: 'somecomment'
          prefix_only: true
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      
      - name: perform the merge
        if: steps.check.outputs.triggered == 'true'
        shell: bash
        run: |
          echo ${{ github.event.comment.author_association }}
```

in the `perform the merge` step, I want to validate that the user that issued the comment belongs to a specific github team.

It this possible?
