### DISCUSSION TITLE
Running specific strategy on a different host

### DISCUSSION THREAD

**Discussion by osy** [community/community#37815] [Actions] [answered]
I have the following job (snippet):

```yaml
jobs:
  build-sysroot:
    name: Build Sysroot
    runs-on: [self-hosted, macOS, large]
    strategy:
      matrix:
        arch: [arm64, x86_64]
        platform: [ios, ios_simulator, ios-tci, macOS]
```

I would like to run just the `ios-tci` for `arm64` on GitHub's runner (or an alternative self-hosted runner tag) and everything else on a self-hosted runner. This is because of a bug in clang that I'm too lazy to triage where it tries to consume all of the host memory that only shows up in that build variant.

Any way to do this?
