### DISCUSSION TITLE
Checkout project on branch of a PR (comment)

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#37816] [Actions]
I have the following workflow

```
on:
  issue_comment:
    types: [created]

jobs:
  check-whether-pr-should-be-merged:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:

      - name: checkout the project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
```

This however checks out my project on `master`.

How can I instruct it to checkout to the branch of the PR the comment was issued on?
