### DISCUSSION TITLE
How do I add a checkbox with an attribute value set as required when multiple options are listed?

### DISCUSSION THREAD

**Discussion by akc3n** [community/community#37836] [Projects and Issues] [answered]
Hello,

I have read https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema the guide documentation on this subject.

This is my template used for crowd-sourcing banking app reports submitted by end users.
https://github.com/PrivSec-dev/banking-apps-compat-report/blob/main/.github/ISSUE_TEMPLATE/app_report.yml

I am able to a required attribute for the first question, `Is there an existing issue for this?`, as it is only one checkbox. However, I am unable to understand how to do the same for the `Device list` portion of the template, which lists the device models. Sometimes users may forget that setup.

I am not a developer, nor do I have experience what so ever. I had a colleague make the template initially sometime ago and they are no longer on GitHub nor part part of the related project that this list is meant for.   

May someone please help me understand if this is possible and how to do it properly.

**Comment by antonblr** [comment, marked as answer]
Apparently `required` attribute cannot be set for the entire checkbox set, only per selection.

Could you try `dropdown` instead (with `multiple` and `validation.required` set to true). Something like:

```yaml
body:
- type: dropdown
  id: devices
  attributes:
    label: Device list
    description: Which Pixel(s) have you tested this with?
    multiple: true
    options:
      - Pixel 7 Pro
      - Pixel 7
      - Pixel 6a
  validations:
    required: true
```
