### DISCUSSION TITLE
Ignored checks make PRs not mergable

### DISCUSSION THREAD

**Discussion by terrynguyen255** [community/community#37845] [Pull Requests] [answered]
I encounter this annoying issue too many times. It seems to be Github's issue.

I have a check to run automation tests like this
```yaml
# .github/workflows/unit-tests.yml
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - staging
      - production
    paths-ignore:
      - '**.md'
```
Then I have a PR to change an .md file only
Now the PR will be unmergable:
![image](https://user-images.githubusercontent.com/11822492/198929175-064217fa-51c8-4537-9710-9a5969283274.png)

Sometimes, the issue can be fixed  by one of these ways:
- Close & re-open the PR, so that the will be refreshed
- Add an unwanted change in that .md file, so that the will be refreshed
- Add an unwanted change in code files, so that the check will not not ignored anymore
