### DISCUSSION TITLE
Caching action cannot find location of directories where data is downloaded

### DISCUSSION THREAD

**Discussion by ymzayek** [community/community#37869] [Actions] [answered]
Hello,

I am migrating the CI of the https://github.com/nilearn/nilearn repository from CircleCI to Github Actions. I have set up the github workflow file with caching steps using actions/cache@v3. It works for caching the source code but then I use several other caching steps that point to different directories where data is downloaded in a step a bit further down the line but in the post caching steps I get: `Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.` 

The configuration can be found here: https://github.com/ymzayek/nilearn/blob/migrate-ci/.github/workflows/build-docs.yml

I set an environment variable for the job called `NILEARN_DATA` where all the data is then downloaded. I can see in the logs https://gist.github.com/ymzayek/241c8073bfd06928e33a1a8ecc92d437 that they are all indeed downloaded in this location so I'm not sure why the paths are not found.

The PR is here: https://github.com/nilearn/nilearn/pull/3383

Any help is much appreciated!

**Comment by airtower-luna** [comment, marked as answer]
You're trying to use shell syntax in the path definitions, which doesn't work because there is no shell:

```yaml
      - name: Data caching
        uses: actions/cache@v3
        with:
          path: |
           $NILEARN_DATA/adhd                 # ~ 45 MB
```

This means the cache action will look for a file *literally* called

```
$NILEARN_DATA/adhd                 # ~ 45 MB
```

because neither the shell variable, nor comment, nor shell-style handling of spaces apply. You need to move the comments out of the string (so they become actual YAML comments), and should use a path relative to the workspace. Looking at the definition of your `NILEARN_DATA` environment variable, this seems about right:

```yaml
      - name: Data caching
        uses: actions/cache@v3
        # ~ 45 MB
        with:
          path: |
           nilearn_data/adhd
```

Technically you could also replace the shell syntax with Actions workflow syntax (`${{ env.NILEARN_DATA }}/adhd`), but I don't really see a reason to do that, unless you plan on changing the directory frequently.
