### DISCUSSION TITLE
Trigger a workflow on PR target branch update

### DISCUSSION THREAD

**Discussion by cgutierr-zgz** [community/community#37863] [Actions] [answered]
Hi, I'd like to trigger a worflow any time the target branch has been updated.
Right now my workflow looks like this:
```yml
on:
  push:
    branches:
      - develop
      - main
```

So if I open the PR from one branch to `main` the workflow runs and generated on output, different to the one I'd expect if the PR was made to `develop`.
So, when I update the target of the PR to `develop`, the workflow does not run again, and I would like that to happen.

Any ideas?

Thanks.

**Comment by ossanna16** [comment]
Hi there @cgutierr-zgz and welcome to our community! Thank you for asking a great question 🙂
While you are waiting for a reply to your question, here are a few things you can do:

To get started, introduce yourself in our [official introduction thread](https://github.com/orgs/community/discussions/23204)
To connect with other new users, check out this Discussion to [Meet Your GitHub Community Team](https://github.com/orgs/community/discussions/28776), further your GitHub knowledge by working through our [GitHub Skill 🆙 exercises](https://github.com/orgs/community/discussions/32121), and participate in our [weekly Fun Friday chats](https://github.com/orgs/community/discussions/30912)

**Comment by mickeygousset** [comment]
So in your current workflow it only triggers on creation of a new pull request. Changing the branch doesn't create a new pull request.

Instead, I think you need to use `synchronize` as another event type.  See documentation:

- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
- https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request

I haven't tried this though, so I can't say for sure it will work.

**Reply by cgutierr-zgz** [reply]
Hi, I found this just now:
https://frontside.com/blog/2020-05-26-github-actions-pull_request/

Seems like the `edited` one does the job

Thanks! for the reply :)

**Comment by cgutierr-zgz** [comment, marked as answer]
The edited type works for this usecase
example:
```yml
name: Pre merge

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ] # <-- this last one :)
    branches:
      - develop
      - qa
      - main
```
