### DISCUSSION TITLE
Use matrix context in Jobs.job.if

### DISCUSSION THREAD

**Discussion by su-sisk** [community/community#37883] [Actions]
Hi guys 🤠 
I'm wondering if it's possible to use the matrix context in a `jobs.job.if` to control the execution ?
The docs states that we can use any context and expression to create conditionals. 
> You can use the jobs.<job_id>.if conditional to prevent a job from running unless a condition is met. **You can use any supported context and expression to create a conditional**.
>>[quote](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution)

Sry if this is a stupid question, an example of my problem is shown below

Example 

```bash
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: define matrix
        id: export-packages
        run: |
          echo "::set-output name=packages::[{ 'ms':'package-a', 'enabled': 'true' }, { 'ms':'package-b', 'enabled': 'false' }]"
    outputs:
      matrix: ${{ steps.export-packages.outputs.packages }}

  job-1:
    runs-on: ubuntu-latest
    needs:
      - pre
    strategy:
      matrix: 
        packages: ${{fromJSON(needs.pre.outputs.matrix)}}
    if: matrix.packages.enabled == 'true'
    steps:
      - name: "test"
        run: |
          echo "${{matrix.ms}} - ${{matrix.enabled}}"
```

Running this gives the following error:
`The workflow is not valid. .github/workflows/matrix-example.yml (Line: 27, Col: 9): Unrecognized named-value: 'matrix'. Located at position 1 within expression: matrix.packages.enabled == 'true' `

All i really wanna achive is to be able to "skip and mark job as skipped" So I could add a initial step to my job that checks this using bash script, but if that exits with 0 or 1 the job is marked as failed or success. Is it possible to mark the job as "skipped"? e.g through something like this? `echo "::job-status='skipped' "`

**Comment by antonblr** [comment]
@su-sisk - could you try it with the curly braces , like `if: ${{ matrix.packages.enabled == 'true' }}` ?

**Reply by skaugvoll** [reply]
Hi thanks for the reply. I tried with your suggestion still same error message. 
> Unrecognized named-value: 'matrix'. Located at position 1 within expression:

**Reply by antonblr** [reply]
Took a closer look: `matrix` context is not available at `jobs.<job_id>.if` level. You can use it at `jobs.<job_id>.steps.if`.
Something like:
```yaml
steps:
  - name: "test"
    if: ${{ matrix.packages.enabled == 'true' }}
    run: echo "${{matrix.ms}} - ${{matrix.enabled}}"
```

Reference - https://docs.github.com/en/actions/learn-github-actions/contexts#determining-when-to-use-contexts

**Comment by fherreazcue** [comment]
Does anyone know why the matrix context is not available for `jobs.<job_id>.if`? The reference above shows that it is available almost anywhere except there... it is a bit annoying...

**Comment by DarrenBishop** [comment]
@fherreazcue the workaround (forgive me if this is obvious) is to pass your flag as an input in the called workflow and then it will be in an accessible context for the jobs (and there _if_ condition) defined there.

@su-sisk, agree this is super annoying; you'd think after so many years (and plugins) after Jenkins, the semantic difference between aborted/skipped vs. failed vs. cancelled would be clear.

The reliance on exit-codes is unnecessarily unsophisticated i.e 0-zero for success and everything else is a fail; unless with the 0-zero magic number we add non-zero magic numbers to trigger/reflect the various job outcomes/conclusions...

But from a Bash step-run context, functions are an obvious way forward:
```
### Start Managed Internally Block (i.e. is enforced/always included [sourced])
> abort() {
    echo "Aborting run... this is not the same as failed!"
}

> readonly -f abort
### End Managed Internally Block

> abort
Aborting run... this is not the same as failed!

> abort() {
    echo "Let's monkey around... or otherwise inadvertently redefine abort() in some well-intentioned job step"
}
-bash: abort: readonly function
```

**Comment by brianjmurrell** [comment]
> @fherreazcue the workaround (forgive me if this is obvious) is to pass your flag as an input in the called workflow and then it will be in an accessible context for the jobs (and there _if_ condition) defined there.

It's not obvious to me.  Could you provide an example of how the OP's workflow could be modified to implement your suggestion?

**Reply by DarrenBishop** [reply]
@brianjmurrell I'm sorry

Around the same time as my comment, I [commented on another issue](https://github.com/actions/runner/issues/1483#issuecomment-1708010440) with an example; I'll replicate here:

The _calling_ workflow (`org/repo/.github/workflows/build_images.yaml`  [with and **s**]), triggered on **_push_** or **_pull_request_**:
```
name: Build Images

on:
  push:
    ...
  pull_request:
    ...

permissions:
  ...

jobs:
  determine-work:
     ...
  call-build-image:
    needs: determine-work
    strategy:
      matrix:
        image: [api, ui]
        include:
          - image: api
            enabled: ${{ needs.determine-work.outputs.build-api }}
          - image: ui
            enabled: ${{ needs.determine-work.outputs.build-ui }}
    uses: org/repo/.github/workflows/build_image.yaml@same-branch
    with:
      # build: ${{ matrix.enabled }} # <--- fails without fromJSON
      build: ${{ fromJSON(matrix.enabled) }}
      image: ${{ matrix.image }}
      tag: ${{ needs.determine-work.outputs.tag }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
```

The _called_ workflow (`org/repo/.github/workflows/build_image.yaml`) i.e. triggered by **_workflow_call_**
```
name: Build Single Image

on:
  workflow_call:
    inputs:
      build:
        description: 'Flag whether to build the Image'
        required: true
        type: boolean
      image:
        description: 'Image to build: api or ui'
        required: true
        type: string
      tag:
        description: 'Image tag'
        required: true
        type: string

jobs:
  build-and-push:
    if: inputs.build
    ...
```

Go forth and conquer
