### DISCUSSION TITLE
`GITHUB_OUTPUT` does not have value if braces are used

### DISCUSSION THREAD

**Discussion by LKreutzer** [community/community#37896] [Actions] [answered]
Following the warning: `The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/` I replaced the `run: echo "::set-output name={name}::{value}"` by `run: echo "{name}={value}" >> $GITHUB_OUTPUT`. This resulted in the value of the output not being set. 

Minimal example:

- Broken
```
name: Test outputs
on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "{test}={hello}" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "{test}={world}" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  ```
- Working:
```
name: Test outputs
on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
```

Is this a GitHub actions bug or is there something about the braces that I am missing?
