### DISCUSSION TITLE
Support multi-line string input for workflow dispatch

### DISCUSSION THREAD

**Discussion by farshadtx** [community/community#37899] [Actions]
We are using GitHub Actions to manually release builds on TestFlight and tag them on git.

We would like to be able to have our change log as a required input for the workflow action to start but currently, the input will ignore the new lines and the string will not keep the format!

example:
```
name: TestFlight
on:
  workflow_dispatch:
    inputs:
      changelog: 
        type: string
        description: What to test
        required: true
```
