### DISCUSSION TITLE
[Bug] GitHub Actions does not set job output because it wrongly detects a secret

### DISCUSSION THREAD

**Discussion by behnazh-w** [community/community#37942] [Actions]
We are using the build outputs to pass the [hash of artifacts](https://github.com/micronaut-projects/micronaut-views/actions/runs/3361168014/workflow#L64) between two jobs, which is necessary for creating [SLSA provenances](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#getting-started).

GitHub Actions [is not setting](https://github.com/micronaut-projects/micronaut-views/actions/runs/3361168014/jobs/5571232825#step:41:2) the output with the error message:

```
Skip output 'hashes' since it may contain secret.
```

This is clearly a false positive as the hashes of the artifacts would have no secrets. Is there any workaround to pass this value as the output here?

**Comment by ossanna16** [comment]
Hi there @behnazh-w and welcome to our community! Thank you for asking a great question 🙂
While you are waiting for a reply to your question, here are a few things you can do:

To get started, introduce yourself in our [official introduction thread](https://github.com/orgs/community/discussions/23204)
To connect with other new users, check out this Discussion to [Meet Your GitHub Community Team](https://github.com/orgs/community/discussions/28776), further your GitHub knowledge by working through our [GitHub Skill 🆙 exercises](https://github.com/orgs/community/discussions/32121), and participate in our [weekly Fun Friday chats](https://github.com/orgs/community/discussions/30912)

**Comment by steiza** [comment]
Hey @behnazh-w - I'm keen on helping ensure GitHub Actions works for SLSA provenance generation.

I tried to reproduce this, but wasn't able to, so I'm not sure exactly what's going on. That said, it looks like we're already using [workflow artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts), so maybe we could use that mechanism (instead of output) to share the hash between jobs in the workflow?

Note also that `set-output` is [scheduled for deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), so maybe another reason to try a different path.

Here was my attempt to reproduce this, which again, didn't work:
```
$ cat test.yml
name: Test
on: 
  workflow_dispatch:

jobs:
  first:
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate output hash
        id: hash
        run: echo "::set-output name=hashes::$(echo 'hi' | sha256sum | base64 -w0)"
  second:
    needs: [first]
    uses: ./.github/workflows/other_workflow.yml@main
    with:
      hashes: "${{ needs.first.outputs.hashes }}"

$ cat other_workflow.yml 
name: Other workflow
on:
  workflow_call:
    inputs:
      hashes:
        description: "hashes"
        required: true
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hashes
        run: "echo ${{ inputs.hashes }}"
```

**Comment by behnazh-w** [comment]
@steiza Thanks for helping out.
>I tried to reproduce this, but wasn't able to, so I'm not sure exactly what's going on. 

Same here. I cannot reproduce the problem in a private clone of [this repository](https://github.com/micronaut-projects/micronaut-views). However, this problem is consistently happening for various [Micronaut projects ](https://github.com/micronaut-projects/micronaut-tracing/actions/runs/3426859052/jobs/5709154773#step:41:2) that are created from the same [template repo](https://github.com/micronaut-projects/micronaut-project-template), where the SLSA provenance generation is [integrated](https://github.com/micronaut-projects/micronaut-project-template/pull/263). My guess is that the GitHub Actions security analysis that monitors job outputs for secrets has a bug, which results in this false positive.

>That said, it looks like we're already using [workflow artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts), so maybe we could use that mechanism (instead of output) to share the hash between jobs in the workflow?

The [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator) GitHub Actions [need the job output](https://github.com/slsa-framework/slsa-github-generator/blob/main/SPECIFICATIONS.md#interference-between-jobs) to pass the hashes between jobs. That's because a workflow artifact can be updated (replaced) by a different potentially malicious job triggered by the same workflow. So if we store the hashes in a workflow artifact we can't guarantee the integrity of the build artifacts. But unfortunately GitHub is not working as expected and does not set the output correctly. So the [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator) requires a feature from GitHub that is not reliable.

>Note also that set-output is [scheduled for deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), so maybe another reason to try a different path.

We should still be able to use the [`GITHUB_OUTPUT` environment files](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), right?

**Reply by laurentsimon** [reply]
I'm interested in seeing this problem fixed too. The run logs clearly show the false positive. Since the hash is random, it appears that GH scanning detected something in the hash that looks like a secrets (a secret available to the workflow like GITHUB_SECRET or one defined by the maintainers?). With access to the scanning code, we should be able to figure out the root cause and fix it. I understand redacting secrets from logs is important, but breaking the workflow seems like a bug, no?

**Reply by ChristopherHX** [reply]
> With access to the scanning code, we should be able to figure out the root cause and fix it

The secret scanning code 100% public under an open source license incl. the code, which prevents leaking code to non secret storage on the actions service.
- https://github.com/actions/runner/blob/c6630ce2852d4fdc56240bed3c92061d27482357/src/Sdk/DTLogging/Logging/SecretMasker.cs
- https://github.com/actions/runner/blob/c6630ce2852d4fdc56240bed3c92061d27482357/src/Runner.Worker/Worker.cs#L140
  Add a breakpoint here to get some secret scanning regex sent from the server
  
  You might want to reduce the number of secrets sent to the runner using reusable workflows see https://github.com/orgs/community/discussions/30363#discussioncomment-3448123, this reduces the number of false positives if your org or repo has a lot of secrets.

**Reply by steiza** [reply]
Ah, so I think @laurentsimon is onto something here.

The `Skip output 'hashes' since it may contain secret.` looks like it comes from https://github.com/actions/runner/blob/c6630ce2852d4fdc56240bed3c92061d27482357/src/Runner.Worker/JobExtension.cs#L510, which is calling https://github.com/actions/runner/blob/c6630ce2852d4fdc56240bed3c92061d27482357/src/Sdk/DTLogging/Logging/SecretMasker.cs#L209.

So we're iterating through secrets, and skipping output that contains secrets as substrings. There are lots of secrets referenced in https://github.com/micronaut-projects/micronaut-views/blob/master/.github/workflows/release.yml, and I suspect that one of them may be short and thus likely to be contained in a base64-encoded SHA256 hash. Maybe some of those values don't need to be secrets? Or they could be made to be less likely to be contained in a base64-encoded SHA256 hash?

**Reply by behnazh-w** [reply]
Thanks. Yes, most likely one of the secrets is accidentally matched based on the regex matching that GitHub Actions is using. There are a few problems here though: 

1. I don't think filtering job outputs using a regex is acceptable in general and I'm surprised how GitHub is trusting this approach.
2. Filtering job outputs makes the current version of SLSA actions unreliable. In cases like Micronaut which requires secrets to publish (and this should be the case for all Java projects), we have to hope that nothing breaks at the last stage and that's not acceptable from the project maintainers' point of view.
3. The Micronaut team is not willing to debug the release job to figure out what secrets might be matched. They argue that these jobs need to be stable and also because the same template is used in more than 50 repositories in production, one change cascades to many repos and causes failures everywhere.

I'm worried that the suggested workaround solutions don't solve the root cause, and either SLSA GitHub Actions need to find a different mechanism to pass hashes between jobs or GitHub Actions should stop filtering the job outputs using a regex.

**Reply by steiza** [reply]
Variables for GitHub Actions have shipped today, so you can move non-secret values out of secrets and into variables.

For more information see https://docs.github.com/en/actions/learn-github-actions/variables.

**Reply by laurentsimon** [reply]
I found another corner case https://github.com/laurentsimon/slsa-delegate-project/actions/runs/4008385408/jobs/6882482821
I have no secrets used, but the scanning code thinks a job output has secrets, and it matches the brackets of the JSON `toJson(steps.mystep.outputs)`:
```
OUTPUTS: ***
  "some-output": "tool-defined-some-output",
  "other-output": "tool-defined-other-output"
***
```

Any idea about root cause?

**Reply by ChristopherHX** [reply]
> I have no secrets used, but the scanning code thinks a job output has secrets

All accessible secrets are masked, even those you don't use in your workflow file.
_I think the docs make me believe that you have to use the secret, but that's proven wrong_
To reduce secrets the runner would mask use [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) and only map the secrets you really need.
E.g. You might have an org or repo secret like this, now all `{` and `}` are masked.
```json
{
  "key": "value"
}
```
You could minify all json secrets into a single line, then you shouldn't see `{` or `}` masked.
_As descibed above reusable workflows can make selected secrets inaccessible and therefore avoid masking `{` or `}`_

**Reply by laurentsimon** [reply]
I was using reusable workflow with no secrets passed.

**Reply by ChristopherHX** [reply]
Can you share your diag logs? (rerun jobs has a check box to enable debug logs, then download log archive of the rerun)

You find all secret names sent to the runner in it with secrets masked in the worker log.

**Edit**
_I forked your repository run ci and the result was no masking, therefore I would need your diag log to understand this phenomen. Secret ACTIONS_RUNNER_DEBUG=true enables uploading of diag logs_

All in all I'm curious what happend, diag logs allows me to replay the job locally using a debugger.

**Comment by y-chen** [comment]
I am having the same issue while exporting as job output the first 7 chars of `github.sha` and a random generated UUID using `uuidgen`.

The masking is completely random. Sometime one is skipped and sometime the other.

Have you figured out a solution?

**Reply by laurentsimon** [reply]
This may be the long-term solution https://github.com/github/roadmap/issues/575.

**Comment by srinadhbh** [comment]
The issue still persists w/ github.com. Is there a work around?

**Comment by louwers** [comment]
This is very annoying. Outputs should not be ignored if there is a potential secret, because build outputs can be IDs and the detection meachanism is flakey.

**Reply by MeCRO-DEV** [reply]
Any solution yet? I'm having the same issue when passing Azure resource group name to the next job, and GitHub will not set the output because it was treated as a secret. But in fact, it is just a regular variable.

**Comment by MeCRO-DEV** [comment]
to the next job, and GitHub will not set the output because it was treated as a secret. But in fact, it is just a regular variable

**Comment by MeCRO-DEV** [comment]
Any solution yet? I'm having the same issue when passing Azure resource group name to the next job, and GitHub will not set the output because it was treated as a secret. But in fact, it is just a regular variable.

**Comment by maeghan-porter** [comment]
FWIW I am also having this issue with an AWS ARN. It is considering the Account ID in the ARN a secret and so ignoring it as job output. Very annoying.

**Comment by erwinv** [comment]
I am also having the same issue with an AWS ECR Image URI. I am trying to separate the (1) build-and-push-to-ECR job from the (2) deploy-ECR-image-to-App-Runner job. Job 2 needs the Image URI from Job 1.

**Reply by devin-purple** [reply]
I'm seeing this as well.

**Reply by petrgazarov** [reply]
I was able to do this by setting `mask-aws-account-id: 'false'` on the `aws-actions/configure-aws-credentials@v2` action. That action automatically adds a mask to the account ID. GitHub Actions then detects that the account id in the image URL matches the masked value and treats the image URL as a secret. Not masking the account ID solves it.

```
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v2
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: us-east-1
    mask-aws-account-id: 'false' # add this
```

**Comment by y-chen** [comment]
I am using artifact as workaround for the moment.

I created 2 actions:

```
name: Upload artifact
description: Upload an artifact

inputs:
  key:
    description: The artifact key
    required: true
  value:
    description: The artifact value
    required: true

runs:
  using: "composite"
  steps:
    - name: Write artifact
      run: echo ${{ inputs.value }} >> ${{ inputs.key }}
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.key }}
        path: ${{ inputs.key }}
        retention-days: 5

```

```
name: Output artifact
description: Output artifact

inputs:
  key:
    description: The artifact key
    required: true

outputs:
  value:
    value: ${{ steps.read.outputs.value }}
    description: "The read value"

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.key }}

    - name: Output artifact
      id: read
      run: |
        FILE=${{ inputs.key }}
        VALUE=$(cat $FILE)
        echo "Value is ${VALUE}"
        echo "value=${VALUE}" >> $GITHUB_OUTPUT
      shell: bash

```

And use them like:

```
      # From one job
      - name: Upload current commit
        uses: ./.github/actions/upload-artifact
        with:
          key: current-commit
          value: ${{ steps.current-commit.outputs.hash }}

      # From another job
      - name: Current commit
        id: current-commit
        uses: ./.github/actions/output-artifact
        with:
          key: current-commit

      # Then I can read the value in another step
      - name: Print
        run: echo ${{ steps.current-commit.outputs.value }}
```

**Comment by benjaminCassard** [comment]
I used artifacts as a workaround of this problem but now i'm reaching quota limitation of artifacts (even if retention is 1 day). Same as [https://github.com/orgs/community/discussions/37942#discussioncomment-6434547](url) I use job outputs for standard variables and not secrets.
This issue should definitely be fixed...

**Reply by Megachill** [reply]
I truly hope MS addresses this! It is annoying beyond belief... Leave it to US to make a decision what is secret and what isn't. We do not need hand holding when it comes to secrets management. Another reason to switch back to gitlab... This is frustrating as hell.🤦‍♂️

**Comment by tpoxa** [comment]
```
outputs:
      main_image: ${{ env.MAIN_IMAGE }}
steps:
 -  run: |
            echo "MAIN_IMAGE=$REGISTRY/$PROJECT/$REPOSITORY/main:$TAG_NAME" >> "$GITHUB_ENV"

```

none of the variables are derived from secrets, but still, main_image output is suppressed

**Reply by talmdal** [reply]
but does the resulting output string happen to contain a substring that matches one of the secrets that is used in the job.  It seems from my limited experience that it is doing something like
```
for each secret:
   if (outputString.contains(secretValue) 
       issue warning
       exit
```

**Comment by FecoDoo** [comment]
Same issue here, have been debugging for a stupid amount of time. It seems like some outputs will be filtered but others may not. It is still a black box and no one knows how GitHub decides whether an output is sensitive or not. 

Here's my code snippet, where output `p` is skipped as GitHub considered it may contain secret, while `email` is not, though both variables are masked in the same fashion.

```
jobs:
  credentials:
    runs-on: ubuntu-latest
    outputs:
      email: ${{ steps.base64.outputs.email_b64 }}
      p: ${{ steps.base64.outputs.p_b64 }}
    steps:
      - uses: hashicorp/vault-action@v2
        with:
          ......
          secrets: |
            repo email | EMAIL;
            repo password | PASSWORD;
      - name: base64
        id: base64
        run: |
          echo "email_b64=$(echo "${{ steps.credential.outputs.EMAIL }}" | base64 -)" >> "$GITHUB_OUTPUT"
          echo "p_b64=$(echo "${{ steps.credential.outputs.PASSWORD }}" | base64 -)" >> "$GITHUB_OUTPUT"
```

**Reply by FecoDoo** [reply]
Updates: This [solution](https://github.com/orgs/community/discussions/13082#discussioncomment-6776428) from [rdhar](https://github.com/rdhar) seems to be good work-around, which works fine in my case. Check out this [discussion](https://github.com/orgs/community/discussions/13082) for details.

**Comment by talmdal** [comment]
Is anything being done to resolve this?

I ran across this when creating a S3 resource path /foo_ops/github/artifacts/foo_project/file.zip.

There is also a secret being used in the job with the value foo

I then get the erroneous warning of "Skip output 'artifact-name' since it may contain secret." The name is not emitted as output and the rest of the workflow fails.

Other jobs in the same workflow that don't reference the secret with the value 'foo' have no issues.

The github processor needs to have better understanding of the context and not just match by value.

**Comment by gorankarlic** [comment]
Having the same issue, value of environment variable `MACHINE` is changed from `e2-medium` to `e2-medium***` - not just in the log output, but even when used in simple a `run` action (i.e. bash script) - this certainly does not make sense at all.

Follow up: this was caused by using a raw JSON as a secret - encoding the JSON with Base64 resolved the issue: [https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#storing-base64-binary-blobs-as-secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#storing-base64-binary-blobs-as-secrets)

**Comment by abseht** [comment]
🤕  Same issue for 
```
    environment:
      name: ${{ inputs.target_env }}
      url: ${{ inputs.target_env == 'production' && 'https://github.com/${{ github.repository }}/releases/tags/${{ env.TAG }}' || inputs.target_env == 'preview' && '${{ github.event.repository.deployments_url }}/preview' || 'https://github.com/${{ github.repository }}/commit/${{ env.TAG }}' }}
```
Get in the Complete Job step
```
Evaluate and set environment url
Warning: Skip setting environment url as environment 'development' may contain secret.
Cleaning up orphan processes
```

**Comment by thanford7** [comment]
Same issue:
```
Evaluate and set job outputs
Warning: Skip output 'ecs_cluster_name' since it may contain secret.
```

The value of `ecs_cluster_name` is `shortify_social-cluster`. I marked the output in terraform as not sensitive, but Github still persists in marking it as a secret.

**Reply by Megachill** [reply]
I know this may not be of help here - but Github has been slacking in terms of addressing this and letting us explicitly set things, so we moved ALL our pipes to gitlab where we are in control at least. You could map however and then re-use with a bit of creativity in your pipe... 

To having to do these kinds of workarounds because of "Daddy" issues and "we know better than you do!" is frankly annoying af.

**Comment by mor-lehr-deel** [comment]
my workaround is to base64 encode the value **twice** so gh doesn't detect it contains a secret. note if it _does_ contain a secret - it will _not_ be masked on the receiving job. use at your own risk.

**Comment by DrDonoso** [comment]
Is there any plan for this? It's a headache to detect false positives and then be unable to mark them as such.

Providing a basic example failing:

```yaml
name: Test

on:
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - id: set-matrix
      run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
```

Working when azure/login step is removed.

**Comment by GalOzRlz** [comment]
I have a wild example of the secret detection censoring "{" and "}" !

`DEBUG:root:***'identifier': '[REDACTED]', 'secret_id_base64': '[REDACTED], 'stage': 'prod', 'region': 'eu-central-1'***
`
this is supposed to be a dictionary!

**Comment by sinogermany** [comment]
## For those who stumble on this in the future, this might save some of your time:

#### When your current step references some of those or similar, your output could be marked as "may contain secrets", regardless how trivial your actual output is.

- `${{ secrets.xxx }}`
- `uses: aws-actions/configure-aws-credentials`
- `uses: google-github-actions/auth`
- `uses: azure/login`
- any other scenarios that makes GHA _think_ the output may contain secrets

#### A safer and more consistent approach would be 3 steps.

- step 1: produce the json and upload to json file artifact
- step 2: simply expose the json artifact as json output, don't do anything else
- step 3: reference the output

Example with GCP (same with AWS etc.)

```yaml
jobs:
  create_matrix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

    - name: Set up Cloud SDK
      uses: "google-github-actions/setup-gcloud@v2"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Run Python script to generate matrix file
      id: generate_file
      run: |
        python3 list_entries.py > matrix_data.json

    - name: Upload matrix artifact
      uses: actions/upload-artifact@v4
      with:
        name: matrix-artifact
        path: matrix_data.json

  # do nothing apart from exposing the json file artifact to output
  expose_matrix:
    runs-on: ubuntu-latest
    needs: create_matrix
    outputs:
      matrix: ${{ steps.read_matrix.outputs.matrix }}
    steps:
      - name: Download matrix artifact
        uses: actions/download-artifact@v4
        with:
          name: matrix-artifact
          path: /tmp

      - name: Read matrix file and set as output
        id: read_matrix
        run: |
          echo "matrix=$(jq -c . < /tmp/matrix_data.json)" >> $GITHUB_OUTPUT

  ingest:
    needs: expose_matrix
    runs-on: ubuntu-latest
    name: ${{ matrix.step_name }}
    if: ${{ needs.expose_matrix.outputs.matrix != '[]' && needs.expose_matrix.outputs.matrix != '' }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.expose_matrix.outputs.matrix) }}

    steps:
      - name: ${{ matrix.step_name }}
        run: |
          echo "Starting step: ${{ matrix.step_name }}"
          echo "Processing Entry: ${{ matrix.entry_name }}"
          #
          # --- Your actual processing commands go here ---
          # Use ${{ matrix.entry_name }} and ${{ matrix.step_name }}
          #
          echo "Finished step: ${{ matrix.step_name }}"
```

**Comment by marc-wilson** [comment]
Hitting the same thing. A simple comma separated list is apparently a "secret"

**Comment by mattmorganpdx** [comment]
The fact there isn't a mark something not secret is insanely insulting. I should be able to simply declare something not secret.

**Comment by kleinfreund** [comment]
I don't know how this works internally, but after reading this thread, it seems like accidental secret leaks are heuristically identified by substring matching output variables against secret values.

This seems like a sizable security flaw as it should be possible to (slowly) brute-force secrets by looking at whether an output value keeps on being masked. If I have a secret "aaaacz" and an output variable contains "aaa", it should get masked (at least the reports in this thread indicate as much), revealing a clue about the secret. Continue trying sequences (at both ends of the guess value) until no addition leads to an unmasked output and you should have found the secret.

**Comment by kleinfreund** [comment]
I now commonly but not consistently run into this problem with an output variable which holds a value that looks like this: `https://pr-135.sub.domain.com/`

I don't comprehend how loose the heuristic for the secret matching can possibly be for _this_ value to be declared a secret. With there not being a way to disable this mechanism for specific variables, this will randomly break all sorts of workflows.

**Comment by DanielPiBL** [comment]
I'm facing this issue as well... This is really annoying and utterly stressful

**Comment by fmaack** [comment]
Hitting the same thing. Every Git-Hash (!) that contains "72" is detected to contain a secret.

I would very much like a feature to mark something as "not a secret".

**Comment by SilverPreeceSOF** [comment]
Right now for me _this_ counts as a secret! GitHub won't let me generate and pass a name for a Docker image. All I'm using is inputs and the name of the Git repository. This is ridiculous, as is not having any documentation for this behaviour or a way to override it. GitHub seem to be completely uninterested in fixing any of the numerous issues with their platform

I have to continually explain to my boss why GitHub CI tasks take me so long and it's because I have to spend anywhere from hours to days continually working around obtuse problems like this. 

```yaml
      - name: Prep Deployment Variables
        id: compile-vars
        run: |
          REPO_NAME=${REPO_FULL_NAME#*/} # Remove owner prefix
          SERVICE_NAME=${REPO_NAME#my-repo-prefix-}          
          IMAGE_NAME="$REPO_NAME/$SERVICE_NAME-$TARGET_ENV"

          echo "DOCKER_IMAGE=$IMAGE_NAME" >> $GITHUB_OUTPUT
        env:
          REPO_FULL_NAME: ${{ github.repository }}
          TARGET_ENV: ${{ inputs.targetEnv }}
```

The job attempts to output `DOCKER_IMAGE` from this step to a reusable workflow, but the value never makes it because GitHub decides it's a secret and drops it. It's not masked, it uses **no secure information whatsoever**, but GitHub's undocumented (probably Copilot-driven) process incorrectly asserts it's a secret and deletes it with no way to stop it. 

The workarounds I tried revealed that job outputs are basically just broken. I've tried moving other variable declarations out of this step in case they were causing it, I've tried renaming the variable in case the name was somehow triggering it, and no dice. I got as far as setting a job output called `DRIBBLE` to a step output called `WIBBLE` containing a very very simple Docker `image-name` and it **still** got deleted as a "potential secret". Whatever garbage algorithm they've implemented to detect these is straight-up broken and should frankly be deleted.

This is the third or fourth blocker like this on the same task.  I once again must ask why Microsoft thinks that Azure DevOps can be deprecated in favour of a system that cannot achieve basic tasks without hacks, workarounds or outright failures.
