### DISCUSSION TITLE
SOLVED: Nightly run suddenly fails

### DISCUSSION THREAD

**Discussion by pluim003** [community/community#37950] [Actions] [answered]
I have a workflow to create an image on a nightly basis and it worked like a charm for a while, but without no changes this night it fails. It's creating a new image on platforms arm32/6, arm32/7, arm64 and amd64. Seems it's failing on amd64 with the following snippet:

```
#14 43.34 Preparing to unpack .../systemd_252-1_amd64.deb ...
#14 43.38 Unpacking systemd (252-1) ...
#14 44.31 Setting up libfdisk1:amd64 (2.38.1-1.1+b1) ...
#14 44.33 Setting up libkmod2:amd64 (30+20220905-1) ...
#14 44.33 Setting up libapparmor1:amd64 (3.0.7-1+b1) ...
#14 44.34 Setting up libip4tc2:amd64 (1.8.8-1) ...
#14 44.35 Setting up libsystemd-shared:amd64 (252-1) ...
#14 44.36 Setting up libdevmapper1.02.1:amd64 (2:1.02.185-2) ...
#14 44.37 Setting up libcryptsetup12:amd64 (2:2.5.0-6) ...
#14 44.37 Setting up systemd (252-1) ...
#14 44.40 Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service → /lib/systemd/system/getty@.service.
#14 44.42 Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target → /lib/systemd/system/remote-fs.target.
#14 44.43 Created symlink /etc/systemd/system/sysinit.target.wants/systemd-pstore.service → /lib/systemd/system/systemd-pstore.service.
#14 44.46 Initializing machine ID from random generator.
#14 44.49 /usr/lib/tmpfiles.d/systemd.conf:28: Failed to resolve group 'systemd-journal'.
#14 44.49 /usr/lib/tmpfiles.d/systemd.conf:29: Failed to resolve group 'systemd-journal'.
#14 44.49 /usr/lib/tmpfiles.d/systemd.conf:30: Failed to resolve group 'systemd-journal'.
#14 44.49 dpkg: error processing package systemd (--configure):
#14 44.49  installed systemd package post-installation script subprocess returned error exit status 65
#14 44.50 Setting up dmsetup (2:1.02.185-2) ...
#14 44.52 Errors were encountered while processing:
#14 44.52  systemd
#14 44.55 E: Sub-process /usr/bin/dpkg returned an error code (1)
#14 ERROR: process "/bin/bash -c apt update && apt install -y -f openssl     && apt install -y -f unbound* && apt install -y -f net-tools     && apt install -y -f wget && apt install -y -f openssh-server" did not complete successfully: exit code: 100

#17 [linux/arm64  3/17] RUN apt update && apt install -y -f openssl     && apt install -y -f unbound* && apt install -y -f net-tools     && apt install -y -f wget && apt install -y -f openssh-server
#17 CANCELED

#16 [linux/arm/v6  3/17] RUN apt update && apt install -y -f openssl     && apt install -y -f unbound* && apt install -y -f net-tools     && apt install -y -f wget && apt install -y -f openssh-server
#16 CANCELED

#18 [linux/arm/v7  3/17] RUN apt update && apt install -y -f openssl     && apt install -y -f unbound* && apt install -y -f net-tools     && apt install -y -f wget && apt install -y -f openssh-server
#18 CANCELED
------
 > [linux/amd64  3/17] RUN apt update && apt install -y -f openssl     && apt install -y -f unbound* && apt install -y -f net-tools     && apt install -y -f wget && apt install -y -f openssh-server:
#14 44.33 Setting up libapparmor1:amd64 (3.0.7-1+b1) ...
#14 44.34 Setting up libip4tc2:amd64 (1.8.8-1) ...
#14 44.35 Setting up libsystemd-shared:amd64 (252-1) ...
#14 44.36 Setting up libdevmapper1.02.1:amd64 (2:1.02.185-2) ...
#14 44.37 Setting up libcryptsetup12:amd64 (2:2.5.0-6) ...
#14 44.37 Setting up systemd (252-1) ...
#14 44.40 Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service → /lib/systemd/system/getty@.service.
#14 44.42 Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target → /lib/systemd/system/remote-fs.target.
#14 44.43 Created symlink /etc/systemd/system/sysinit.target.wants/systemd-pstore.service → /lib/systemd/system/systemd-pstore.service.
: Sub-process /usr/bin/dpkg returned an error code (1)
------
Dockerfile_nightly:6
--------------------
   5 |     
   6 | >>> RUN apt update && apt install -y -f openssl \ 
   7 | >>>     && apt install -y -f unbound* && apt install -y -f net-tools \
   8 | >>>     && apt install -y -f wget && apt install -y -f openssh-server
   9 |     
--------------------
ERROR: failed to solve: process "/bin/bash -c apt update && apt install -y -f openssl     && apt install -y -f unbound* && apt install -y -f net-tools     && apt install -y -f wget && apt install -y -f openssh-server" did not complete successfully: exit code: 100
Error: buildx failed with: ERROR: failed to solve: process "/bin/bash -c apt update && apt install -y -f openssl     && apt install -y -f unbound* && apt install -y -f net-tools     && apt install -y -f wget && apt install -y -f openssh-server" did not complete successfully: exit code: 100

```

Thought I run it manually from my laptop but with the same result. Unfortunately can't find a clue.

This is the workflow-file:

```
name: Build and push nightly

on:
  # cron job to trigger the build on any push to dev
  # push:
  #  branches:
  #    - 'dev'
  schedule:
  # cron job to trigger the build dialy (time in UTC)
    - cron:  '* 4 * * *'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of pihole docker
        uses: rez0n/actions-github-release@main
        id: pihole_version
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "pi-hole/docker-pi-hole"
          type: "nightly"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push nightly
        uses: docker/build-push-action@v3
        with:
          build-args: PIHOLE_VERSION=${{ steps.pihole_version.outputs.release }}
          context: "{{defaultContext}}:one-container/pihole-unbound/"
          file: "Dockerfile_nightly"
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: pluim003/pihole-unbound:nightly
```

For now I should remove temporarily amd64 from it.

Update: removing amd64 doesn't solve it and now it will complain with the same errormessage on another architecture.

This is the corresponding Dockerfile:

```
ARG PIHOLE_VERSION
FROM pihole/pihole:nightly

COPY debian_unstable.list /etc/apt/sources.list.d/

RUN apt update && apt install -y -f openssl \ 
    && apt install -y -f unbound* && apt install -y -f net-tools \
    && apt install -y -f wget && apt install -y -f openssh-server

RUN mkdir -p /var/log/unbound
RUN chown -R unbound:unbound /var/log/unbound
COPY lighttpd-external.conf /etc/lighttpd/external.conf 
COPY unbound-pihole.conf /etc/unbound/unbound.conf.d/pi-hole.conf
COPY 99-edns.conf /etc/dnsmasq.d/99-edns.conf
RUN mkdir -p /etc/services.d/unbound
COPY unbound-run /etc/services.d/unbound/run

COPY unbound-package-helper /usr/lib/unbound/package-helper
RUN chmod 755 /usr/lib/unbound/package-helper

RUN wget https://www.internic.net/domain/named.root -qO- | tee /var/lib/unbound/root.hints
RUN chown -R unbound:unbound /var/lib/unbound/root.hints

# install pihole-cloudsync (from repository by Steve Jenkins)

RUN mkdir -p /usr/local/bin/pihole-cloudsync
COPY pihole-cloudsync/pihole-cloudsync /usr/local/bin/pihole-cloudsync
RUN chmod +x /usr/local/bin/pihole-cloudsync/pihole-cloudsync

ENTRYPOINT ./s6-init
```

Also tried with adding the line RUN grpadd systemd-journal with no success. Or it should have to do with the unstable sources I'm using. But that gives me at least a working image with the latest version of Unbound.

OK, If I don't use the unstable sources it continues. Wondering why it worked for a few weeks with the unstable.

Another update: Instead of using unstable I tried with testing. And this succeeded in an image with still the latest version of unbound. So will update the repository.
