### DISCUSSION TITLE
GitHub Action Service Container Authenticate with gcloud

### DISCUSSION THREAD

**Discussion by zen-manderson** [community/community#38006] [Actions]
I am trying to use a docker image from a private google artifact registry (GAR) in a service container.  I'm struggling to figure out how to authenticate with GAR as part of pulling the docker image for the service container.  Locally I'd run gcloud auth configure-docker us-central1-docker.pkg.dev to register gcloud as a Docker credential helper.  But how do I do that as part of a service container?

I know I can also use google-github-actions/auth@v0 to authenticate workflow steps like 
- id: auth
   name: authenticate with gcloud
   uses: google-github-actions/auth@v0
   with:
     token_format: "access_token"
     workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
     service_account: "bar"

But how do I use google-github-actions/auth@v0 to authenticate pulling a docker image for a service container?

**Comment by antonblr** [comment]
Hi @zen-manderson - you will have to use two jobs workflow, I believe. First job should authenticate agains gcloud, second - use the generated creds (from outputs).

At the high level:
```yaml
jobs:
  gcloud-auth:
    steps:
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'

  my-job:
    runs-on: ubuntu-20.04
    needs: gcloud-auth  # we need this to complete first
    container:
      image: my-docker-hub/my-image:v1
      credentials:
        username: 'oauth2accesstoken'
        password: '${{ needs.gcloud-auth.auth.outputs.access_token }}'
    steps:
      ...
```

Additional reading - https://github.com/google-github-actions/auth#authenticating-to-container-registry-and-artifact-registry

**Reply by zen-manderson** [reply]
Thank you for the guidance.  I'm trying to use a service container.  I tried what you suggested with some minor tweaks but the password line in the service container credentials is causing an Unexpected value '' error.  I also read that I need to us a job output instead of the step output to be able to share the output between jobs https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs.  My config looks like

```
jobs:
  gcloud-auth:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      access_token: ${{ steps.auth.outputs.access_token }}
    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'

  my-job:
    runs-on: ubuntu-latest
    needs: gcloud-auth  # we need this to complete first
    services:
      my-service:
         image: my-docker-hub/my-image:v1
         credentials:
            username: 'oauth2accesstoken'
            password: '${{ needs.gcloud-auth.outputs.access_token }}'
    steps:
      ...
```
