### DISCUSSION TITLE
Workflow that should run on PR merge, never gets executed

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#38002] [Actions]
The following workflow

```yaml
name: Check if a merged PR was approved

on:
  pull_request:
    types:
      - closed


jobs:
  check-if-pr-was-approved:
    name: check if the pr was approved
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:

    - name: check the status of PR when merged
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
      run: echo $GITHUB_CONTEXT
```

residing in the `default` branch of a repo does not run when a PR is merged.

Why?
