### DISCUSSION TITLE
Seems workflow 'on push branches paths filtering' does not work on forked repository

### DISCUSSION THREAD

**Discussion by sandynz** [community/community#38036] [Actions]
Hi everyone,

Our repository have several workflows, paths filtering is configured for all of them, both on push and pull_request, example:
```
on:
  push:
    branches: [ dev ]
    paths:
      - ...
  pull_request:
    branches: [ master ]
    paths:
      - ...
```

When I push new commit to `dev` branch of forked repository and submit PR to repository, workflows are triggered both in forked repository and respository.
But I found paths filtering doesn't work on forked repository.
Workflows on repository pull_request:
<img width="217" alt="图片" src="https://user-images.githubusercontent.com/42492540/199389655-a73fef8c-8f56-4f08-82ea-397991104b93.png">
Workflows on forked repository push:
<img width="611" alt="图片" src="https://user-images.githubusercontent.com/42492540/199389832-b3717a27-80e4-4fc9-b04a-9cf1fb40278a.png">
Some of them should not be triggered, and I canceled them manually.

Is there any way to enable paths filtering on forked repository?

Thanks
