### DISCUSSION TITLE
Add repository filter to `on: schedule` to prevent firing cron jobs in forks

### DISCUSSION THREAD

**Discussion by abitrolly** [community/community#38047] [Actions]
This request is similar to https://github.com/orgs/community/discussions/26704

Currently, to disable running scheduled jobs for contributors, each job needs to be annotated with this.

```
jobs:
  verify-links:
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository == 'arduino/arduino-cli')
```
https://github.com/arduino/arduino-cli/pull/888/files

It will be much easier to filter it on workflow level.
```
on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 1" # Every Monday at 03:00
      if: github.repository == 'arduino/arduino-cli'
```
