### DISCUSSION TITLE
How do I set Outputs in a matrix Strategy workflow but only for a specific run?

### DISCUSSION THREAD

**Discussion by RoniFinTech2** [community/community#38088] [Actions]
Let's say I have 
```
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
```
where `package` is set to an array of package names ['A', 'B', 'C']

I want the output to be set only when the package 'B' is run.
Is it possible?

**Comment by ossanna16** [comment]
Hi there @RoniFinTech2 and welcome to our community! Thank you for asking a great question 🙂
While you are waiting for a reply to your question, here are a few things you can do:

To get started, introduce yourself in our [official introduction thread](https://github.com/orgs/community/discussions/23204)
To connect with other new users, check out this Discussion to [Meet Your GitHub Community Team](https://github.com/orgs/community/discussions/28776), further your GitHub knowledge by working through our [GitHub Skill 🆙 exercises](https://github.com/orgs/community/discussions/32121), and participate in our [weekly Fun Friday chats](https://github.com/orgs/community/discussions/30912)

**Comment by ChristopherHX** [comment]
I'm not shure if I understand you correctly. Empty job outputs of matrix legs are skipped, this allows you to only set a job output for a specfic matrix leg.

```yaml
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
    # output what you want, the output of package B will be available in needs for furture jobs
    - run: echo "MyKey=MyOutput" > $GITHUB_OUTPUT
      id: mystep
    outputs:
      B: ${{ matrix.package == 'B' && steps.mystep.outputs.mykey || '' }}
```
You can also skip the step, which sets your output
```yaml
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
    # output what you want, the output of package B will be available in needs for furture jobs
    - run: echo "MyKey=MyOutput" > $GITHUB_OUTPUT
      id: mystep
      if: matrix.package == 'B' 
    outputs:
      B: ${{ steps.mystep.outputs.mykey || '' }}
```

**EDIT** added missing `steps.`

**Reply by RoniFinTech2** [reply]
thanks for the response!
That doesn't seem to work... I'm assuming `GITHUB_OUTPUT` and `GITHUB_ENV` should behave the same:

So  I have a job named `build` that it has this output:

```
    outputs:
      imageUri: ${{ env.imageUri || '' }}
```

I did `-run: echo ${{ env.imageUri || '' }}` as part of `build` under package `A` and under `B`.
`A` outputs blank and `B` outputs the right imageUri.

Now, I have another job that depends on `build` and is run after `build` 
Inside that other job I run `${{ needs.build.outputs.imageUri }}` but it returns a blank string.

**Comment by airtower-luna** [comment]
> That doesn't seem to work... I'm assuming GITHUB_OUTPUT and GITHUB_ENV should behave the same:

That's an incorrect assumption, the [`env` context documentation states](https://docs.github.com/en/actions/learn-github-actions/contexts#env-context):

> You can use the `env` context in the value of any key in a step except for the `id` and `uses` keys.

The job output definition is not part of a step, so you can't use `env` there. An output would work.

**Reply by RoniFinTech2** [reply]
understood. thanks!
This is what I got now under my `build` job:

```
    outputs:
      imageUri: ${{ steps.output-image-uri.outputs.imageUri || '' }}
   steps:
      - id: output-image-uri
        if: "contains(matrix.package, 'serverless')"
        run: |
          echo "imageUri=${{ env.imageUri }}" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.output-image-uri.outputs.imageUri || '' }}
```

the last echo seems to output the imageUri properly.

So my other job has this statement:
    `needs: [ build ]`
    This outputs blank:
    `${{ needs.build.outputs.imageUri }}`

**Reply by airtower-luna** [reply]
I'm pretty sure the output itself should work now, but I'm not sure about the matrix interaction (e.g., could one matrix job overwrite the output set by the other?). You could try to do something like this in another job to see everything that's available about the `build` job:

```yaml
steps:
  - run: echo "${JSON}"
    env:
      JSON: ${{ toJSON(needs.build) }}
```

I'd hope there's *some* way to access the different matrix runs, but I don't have experience there. :sweat_smile:

**Reply by RoniFinTech2** [reply]
:-(
this is the output of JSON:
```
{
  "result": "success",
  "outputs": {}
}
```

**Reply by airtower-luna** [reply]
That looks like outputs from elements of a matrix job aren't considered. Ouch. :confused: 

I have used artifacts from matrix jobs (with different names based on current matrix elements). Could you write to a file, store that as an artifact, and use that artifact in the next job?

**Reply by ChristopherHX** [reply]
> :-(
this is the output of JSON:

Do you use windows runners?, then you need `$env:GITHUB_OUTPUT`, because the shell is pwsh not bash.

**Comment by ChristopherHX** [comment]
This workflows works on my github account, I don't know how your full workflow looks like.
```yaml
on:
  push:
jobs:
  testa:
    strategy:
      matrix:
        package: ${{ fromJSON('["A", "B", "C"]') }}
    runs-on: ubuntu-latest
    steps:
    # output what you want, the output of package B will be available in needs for furture jobs
    - run: echo "MyKey=MyOutput" > $GITHUB_OUTPUT
      id: mystep
      if: matrix.package == 'B' 
    outputs:
      B: ${{ steps.mystep.outputs.mykey || '' }}
  testb:
    runs-on: ubuntu-latest
    needs: testa
    steps:
    - run: ${{ tojson(needs) }}
      shell: cat {0}
```
This results in the following output for me
```
{
  "testa": {
    "result": "success",
    "outputs": {
      "B": "MyOutput"
    }
  }
}
```
