### DISCUSSION TITLE
Generic packages support??

### DISCUSSION THREAD

**Discussion by johnc-ftl** [community/community#38083] [Packages]
It seems like an oversight that there is no "generic" packages support in github packages. I should be able to publish and fetch a zip (or other archive) file that is *not* a container, maven package, npm packages, or nuget package. Maven, npm, and nuget packages are useful for sharing libraries, but none of these are appropriate for an application installer, or other types of application packages or build output. Not everyone uses containers for all installations.

I note that there [is an issue for generic packages on the roadmap](https://github.com/github/roadmap/issues/123), but it's been pushed out a few times, and I have no ability to comment on it. I'm pretty surprised that this wasn't included in the initial package support.

The API seems to require a specific package type (eg container). We'd like to migrate to github actions for our builds and deploys, but this is effectively a blocker for us. We're currently using [Azure DevOps Artifacts Universal Packages](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages) for this purpose.

Related to #36023

**Comment by ossanna16** [comment]
Hi there @johnc-ftl and welcome to our community! Thank you for the feedback!

**Reply by Matthias-Mangin** [reply]
@ossanna16 I have the same usecase, currently I am migrating a project from Gitlab to Github.
I would like to publish a zip archive on Github in order to access it in a Github Actions job, but as @johnc-ftl stated there is no straightforward way to achieve this currently.
Could you please share some update about the issue that should resolve it and that has been there since 2020 ? https://github.com/github/roadmap/issues/123

**Comment by mmxnet** [comment]
Same for me. We are considering git/issue-tracker/wiki cloud platform to migrate from our self-hosted environment. And have number of free-style projects built with make and deploying artifacts to nexus raw repo locally (e.g. MSI installers). There are "generic packages" in gitlab so I was pretty surprised there is no straightforward way to do it with github. Any workaround? Converting those projects to maven build is not an option...

**Comment by pkgw** [comment]
This may not have been true in the past, but nowadays, you can do this using GHCR and a tool called [`oras`]. In its simplest forms, you can basically use it to push and pull arbitrary blobs using the same syntax that you would for Docker images. To push an arbitrary file inside GitHub Actions:

[`oras`]: https://oras.land/

```yaml
- uses: oras-project/setup-oras@v1
  with:
    version: 1.2.2

# ... create `myfile.zip` (or whatever) somehow
# $SLUG is your package slug, e.g. `pkgw/my-generic-package`
# $TAG is the version tag, e.g. `latest`

- name: Push package
  run: |
    echo ${{ secrets.GITHUB_TOKEN }} |oras login --username ${{ github.repository_owner }} --password-stdin ghcr.io
    oras push ghcr.io/$SLUG:$TAG --artifact-type application/vnd.my.whatever myfile.zip
```

Pulling is analogous:

```sh
oras pull ghcr.io/$SLUG:$TAG
```

If you want your file to be usable in other frameworks, you'll need to actually set up real metadata, but if all you want to do is push and pull binary files, the above suffices. Read the ORAS docs if you want to get fancier.

The main downside is that you do need this `oras` tool installed, to push and pull artifacts, but I think that's reasonable tradeoff to get the access control tools provided by GHCR. If you don't care about access control, you might as well use GitHub Releases, and then your artifacts will be retrievable over plain old HTTP(S).
