### DISCUSSION TITLE
"source not found" in my GH Action running a simple python script

### DISCUSSION THREAD

**Discussion by citrushouse** [community/community#38105] [Actions] [answered]
Hi there,

I'm switching from GitLab, and have read some of the docs on GitHub for migrating from GitLab, as well as some random articles on the subject
> https://hynek.me/articles/python-github-actions/
> https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container/
> https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-gitlab-cicd-to-github-actions/
etc.

The pipeline I'm trying to recreate in GitHub is very simple. It is a small Python script that needs no parameters and no env variables or auth.

The original GitLab file
```yaml
# /.gitlab-ci.yml
# Things not related to the Python script have been removed
stages:
  - validate

validate-data:
  image: python:3.10-buster
  stage: validate
  script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - cd validator/
    - pip install -r requirements.txt
    - python validator.py
```

My GitHub file
```yaml
# /.github/workflows/validate-ci.yml
name: validate data

on:
  push:
    branches: [ main, dev, release/* ]
  pull_request:
    branches: [ main, dev, release/* ]

jobs:
  validate-data:
    runs-on: ubuntu-20.04
    container:
      image: python:3.10-buster
    steps:
      - uses: actions/checkout@v3
      - run: python --version
      - run: pip install virtualenv
      - run: virtualenv venv
      - run: source venv/bin/activate
      - run: cd validator/
      - run: pip install -r requirements.txt
      - run: python validator.py
```

The error is on running `source` bash command

```
Run source venv/bin/activate
  source venv/bin/activate
  shell: sh -e {0}
 ... source: not found
Error: Process completed with exit code 127.
```

I suspect it's something simple I'm missing, since I'm new to GitHub and the script is extremely basic. Anyone have any ideas what I'm missing or misunderstanding?

Thank you!

**Comment by david-engelmann** [comment]
Try adding in the step `- run: sudo /usr/bin/easy_install virtualenv` after the `-run: pip install virtualenv` step

**Comment by airtower-luna** [comment, marked as answer]
AFAIK `source` is a Bash extension, not part of the POSIX shell (`sh`) which you're using there. Try

```yaml
      - run: . venv/bin/activate
```

instead for the POSIX version.

However, you'll probably run into trouble right after:

```yaml
      - run: cd validator/
      - run: pip install -r requirements.txt
      - run: python validator.py
```

I assume you mean to run the following commands inside the `validator/` directory. But each step gets a fresh shell, so the `cd` won't do anything for the steps after it. Instead, [set the `working-directory`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun) for those steps:

```yaml
      - run: pip install -r requirements.txt
        working-directory: validator/
      - run: python validator.py
        working-directory: validator/
```

**Reply by citrushouse** [reply]
Oh gosh, I saw that shell command, but I didn't even think about checking if `source` was even in shell... 

That's good to know about working-directory too. I now have 
```yml
jobs:
  validate-data:
    name: validate data with ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.7"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ./validator
        run: |
          python -VV
          pip install -r requirements.txt
      - name: Validate data
        working-directory: ./validator
        run: |
          python validator.py

```
and it works like a charm alongside my other stuffs. Thank you so much!

**Comment by shynimol400** [comment]
Hi.
I want to recover the latest repository of this file if possible.
HyperScorpio[/](url)store1

Thank you.

**Reply by citrushouse** [reply]
Hi @shynimol400, I think you're in the wrong spot

**Comment by ioudkerk** [comment]
Hi maybe it is late because you solve the problem, but I have the same problem with a custom python/node docker image to run a terraform cdktf. CDKTF uses pipenv, so I have to do some hacks and to fix the problem I added the shell option in the run command:


```
jobs:
  run-cdktf-plan:
    runs-on: ubuntu-latest
    container: ghcr.io/clovrlabs/platform:cdktf
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: execute cdktf plan
        run: |
          echo "log which shell I have"
          echo $0
          source /root/.local/share/virtualenvs/cdktf-IcVruO7w/bin/activate
          python -V
        shell: bash # <---- THIS LINE
```
