### DISCUSSION TITLE
Reusable workflow not being invoked for no apparent reason

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#38138] [Actions] [answered]
On my `master` branch there is this `reusable.yaml`

```yaml
name: Do stuff

on:
  workflow_call:
    
env:
  SOMETHIN: foo


jobs:
  perform-stuff:
    runs-on: ubuntu-latest

  steps:
  
  - ...
```

On my `production` branch there is this `calling.yaml`

```yaml
on:
  issue_comment:
    types:
      - created

jobs:
  a-job
    if: github.event_name == 'issue_comment'
    uses: Org/repo/.github/workflows/reusable.yaml@master
```

However, when I open a PR from `feature` branch towards `production` and issue a comment, the `calling.yaml` never runs.

Why?
