### DISCUSSION TITLE
Trigger action when a comment is written when opening a PR

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#38169] [Actions]
I have a workflow that is triggered on

```
on:
  issue_comment:
    types:
      - created
```

However, when a comment is written on the PR opening, the workflow is not triggered.

Why?
