### DISCUSSION TITLE
Workflow not running when opening a Pull Request

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#38175] [Actions] [answered]
I have the following trigger

```yaml
on:
  pull_request:
    types:
      - opened
    branches:
      - 'foobranch'
  issue_comment:
    types:
      - created
```

When opening a PR targeting `foobranch`, the workflow **does not run**.

Is it because the workflow file does not exist on any other branch than the default? (`master`) ?

**Comment by david-engelmann** [comment, marked as answer]
If the workflow doesn't exist on the branch you are working on, that could be part of the problem. Add the workflow folder to the foobranch. If you have particular branches that you'd like to have it trigger from they can be declared, see the example below.

```
on:
  push:
    branches:    
      - 'dev'
      - 'prod'

  pull_request:
    branches:    
      - 'dev'
      - 'prod'
```
