### DISCUSSION TITLE
Workflow unable to find PR when triggered on pull_request

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#38209] [Actions] [answered]
Ι have a workflow triggered on the following events

```
on:
  pull_request:
    types:
      - opened
    branches:
      - 'mybranch'
  issue_comment:
    types:
      - created
```

I also have the following step

```yaml
      - name: perform PR approval if applicable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
           git fetch --all
           git checkout ${{ env.TARGET_BRANCH }}
           echo "Approving the PR..."
           gh pr review --approve ${{ github.event.issue.number }}
```

When I open a PR that targets `mybranch`, the above step fails with the following error:

```
Approving the PR...
no pull requests found for branch "mybranch"
Error: Process completed with exit code 1.
```

If (after the workflow creation) I issue a comment, the above step succeeds.

Why is it unable to find the PR upon creation?
