### DISCUSSION TITLE
select runner based on the input

### DISCUSSION THREAD

**Discussion by fouringiz** [community/community#38204] [Actions] [answered]
Hi everyone
I'm looking for a way to run an action on a runner selected by the input. Could you pls correct me, cause the action falls into an error?

```
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Env to run"
        required: true
        type: choice
        options:
          - dev
          - demo
jobs:
  myjob:
    runs-on: [ self-hosted, ${{ github.event.inputs.env }} ]
```

I have searched for similar discussions

[https://github.com/orgs/community/discussions/37116](this) didn't work for me
thanks in advance

**Comment by david-engelmann** [comment]
try remove github.event. and running it with just inputs. also you may need the fromjson function 
ie.

```
... [self-hosted, ${{ inputs.env }} ] ...
or
... [self-hosted, ${{ fromjson(inputs.env) }} ] ...
```

**Comment by ChristopherHX** [comment, marked as answer]
You found a bug in my existing answer, I updated it and quoted the comment correctly to not cause a yaml error.

```yaml
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Env to run"
        required: true
        type: choice
        options:
          - dev
          - demo
jobs:
  myjob:
    runs-on: [ self-hosted, "${{ github.event.inputs.env }}" ]
    steps:
    - run: exit 0
```
Or with the newer `inputs` context, not available on old GHES:
```yaml
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Env to run"
        required: true
        type: choice
        options:
          - dev
          - demo
jobs:
  myjob:
    runs-on: [ self-hosted, "${{ inputs.env }}" ]
    steps:
    - run: exit 0
```
