### DISCUSSION TITLE
Feature request: Runner Recycling

### DISCUSSION THREAD

**Discussion by yjaaidi** [community/community#38214] [Actions]
Caching is an excellent way of boosting performance but caching/extraction time is not neglectable.
What about "Recycled Runners": runners that can be reused between jobs while skipping some steps if the runner is reused.

This can be a bit riskier as jobs can break the runner but it could be a considerable performance gain.

In addition to this, if the runner is still hot, services wouldn't have to be restarted and could be reused as-is given some flag.

## Example

```yaml
runnerRecycling: ${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
        if: !github.recycledRunner
      - uses: actions/setup-node@v1
        if: !github.recycledRunner
      - uses: actions/cache@v2
        if: !github.recycledRunner
      - name: Test
        ...
```
