### DISCUSSION TITLE
Don't require the GITHUB_TOKEN to use the gh cli in workflows

### DISCUSSION THREAD

**Discussion by roryabraham** [community/community#38213] [Actions]
As is stands today, you can use the `gh` cli in workflows, but you have to provide the `GITHUB_TOKEN` environment variable. This creates unnecessary extra verbosity in workflow files, when a lot of the time we just end up using the default token from the `github` context:

```yaml
- run: gh pr list
  env:
    # Why does the runner not just use this by default?
    GITHUB_TOKEN: ${{ github.token }}
```
