### DISCUSSION TITLE
Need only some matrix configurations

### DISCUSSION THREAD

**Discussion by leighmcculloch** [community/community#38248] [Actions]
Is there a way to define a job that has a matrix, such as the one below, and then define another job that is only dependent (via `needs`) on a subset of the resulting configurations?

```yml
  build-and-test:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - os: ubuntu-latest
          target: aarch64-unknown-linux-gnu
        - os: macos-latest
          target: x86_64-apple-darwin
        - os: macos-latest
          target: aarch64-apple-darwin
        - os: windows-latest
          target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - ...
```
