### DISCUSSION TITLE
[Feedback tracking] Webhook forwarding in the GitHub CLI

### DISCUSSION THREAD

**Discussion by timrogers** [community/community#38262] [Apps, API and Webhooks]
When you're building a [webhooks](https://docs.github.com/developers/webhooks-and-events/webhooks/about-webhooks) integration, it's super helpful to be able to run your code in your local environment, so you can test and iterate quickly without time-consuming deploys.

We're running a public beta of a new feature for the [GitHub CLI](https://cli.github.com/) - webhook forwarding. Webhook forwarding makes it easier than ever to test your integration locally without having to worry about [port forwarding](https://en.wikipedia.org/wiki/Port_forwarding).

You can register your interest in joining the beta program [here](https://github.com/orgs/community/discussions/38261).

**This discussion is the best place for participants in the beta program to share their feedback and questions with the GitHub team**. We appreciate your support and ideas!

**Comment by RobbyAmbrose** [comment]
add me

**Reply by ka592** [reply]
> add me

**Comment by hutch3232** [comment]
This new tool is amazing. I'm a complete novice to this sort of thing and I managed to get it working. Thanks for creating this!

Are there plans to make this extension installable in "locked down" environments where developers are unable to install directly from GitHub? For example, I currently installed the GitHub CLI via Conda. For now I had to do the testing on my personal computer.

**Comment by HarrierPanels** [comment]
> When you're building a [webhooks](https://docs.github.com/developers/webhooks-and-events/webhooks/about-webhooks) integration, it's super helpful to be able to run your code in your local environment, so you can test and iterate quickly without time-consuming deploys.
> 
> We're running a public beta of a new feature for the [GitHub CLI](https://cli.github.com/) - webhook forwarding. Webhook forwarding makes it easier than ever to test your integration locally without having to worry about [port forwarding](https://en.wikipedia.org/wiki/Port_forwarding).
> 
> You can register your interest in joining the beta program [here](https://github.com/orgs/community/discussions/38261).
> 
> **This discussion is the best place for participants in the beta program to share their feedback and questions with the GitHub team**. We appreciate your support and ideas!

Ansible tasks setting up webhook forwarding using the **GitHub CLI Beta feature** for a Jenkins Docker container running on an AWS EC2 (Amazon Linux 2) instance provisioned by Terraform: 
```
      - name: Add GH Repo
        ansible.builtin.shell: |
          yum-config-manager --add-repo \
             https://cli.github.com/packages/rpm/gh-cli.repo

      - name: Install GH
        ansible.builtin.yum:
          name:
            - gh
          state: latest
          update_cache: yes

      - name: Create GH Token file
        ansible.builtin.copy:
          dest: "{{ dest_token }}"
          content: 'ghp_YOUR_TOKEN'
          owner: ec2-user
          group: ec2-user
          mode: '600'

      - name: GH CLI Auth
        become_user: ec2-user
        ansible.builtin.shell:
          gh auth login --with-token <~/.ssh/token
        register: auth
        async: 10
        poll: 2

      - name: Debug GH Auth
        ansible.builtin.debug:
          var: auth 
         
      - name: Install cli/gh-webhook
        become_user: ec2-user
        ansible.builtin.shell:
          gh extension install cli/gh-webhook
        register: install_ghwh
        async: 10
        poll: 2

      - name: Debug GH Webhook Install
        ansible.builtin.debug:
          var: install_ghwh

      - name: Set GitHub Webhook
        become_user: ec2-user
        ansible.builtin.shell: |
          gh webhook forward --repo YOUR_USER/YOUR_REPO \ 
            --events=push --url="http://localhost:8080/github-webhook/"
          echo 'Webhook set!'
        async: 45
        poll: 0
 
      - name: Test Git push at localhost 
        become_user: your_linux_user
        ansible.builtin.shell: |
          cd $HOME/path/to/YOUR_REPO
          touch Ansible-$(date +%T)
          git remote remove origin
          git remote add origin https://ghp_YOUR_TOKEN@github.com/YOUR_USER/YOUR_REPO.git
          git add . && git commit -m "Pushed by Ansible" && git push --all origin
        register: git
        delegate_to: localhost

```
Happy Webhook forwarding! :)
