### DISCUSSION TITLE
The deploy action returned success status but my site reported 404 not found

### DISCUSSION THREAD

**Discussion by yzhangcs** [community/community#38281] [Actions] [answered]
Hi, I've just tried to deploy my Sphinx project docs to GitHub Pages using Github actions.

The action worked very well and reported success status.
But when I managed to access the [site](https://yzhang.site/parser), it reports a 404 Not Found error, saying that
> For root URLs (like http://example.com/) you must provide an index.html file.

But the odd thing is, I can successfully download the generated [artifact](https://github.com/yzhangcs/parser/suites/9130588928/artifacts/424122375) from the action page, and the index.html file indeed exists in the unpacked folder.
I can't figure out what went wrong. Could you give me any instructions?
Thank you!

Below is my action code.
```yml
# Simple workflow for deploying static content to GitHub Pages
name: docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v2
    - name: Build with Sphinx
      run: |
        pip install -U pip setuptools
        pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
        python setup.py install
        pip install -U -r docs/requirements.txt
        cd docs
        sphinx-build -T -E -b html -d build/doctrees source build/html
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: 'docs/build/html'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
```
