### DISCUSSION TITLE
Expression parsing in 'runs.image' yaml value.

### DISCUSSION THREAD

**Discussion by jbvirt** [community/community#38311] [Enterprise]
I am running on GitHub Enterprise Server 3.3.6 and have run into a bit of a snag when creating a docker action.

Essentially, I would _like_ to be able to dynamically pull a different base image depending on what inputs are passed in but unfortunately it seems that expressions in the `runs.image` yaml value are not expanded.
Here is an example:
```yaml
name: test
inputs:
  container: 
    description: "Container to use as a base."
    required: true
    default: mycontainer/my-image-with-version
runs:
  using: docker
  image: docker://${{ inputs.container }}
```

Unfortunately, this results in docker trying to pull the image `docker://${{ inputs.container }}`, and failing. Using environment variables does not work either.

This seems like a massive limitation on the flexibility of Docker actions.
Is the functionality I need present on the latest version of GHES?
Is there a way to work around this?

There is no way to pass `build-arg`'s into a `Dockerfile` either, so that won't work either.
