### DISCUSSION TITLE
Hello, I have a problem to publish my artifacts to packages using actions.

### DISCUSSION THREAD

**Discussion by heipiao233** [community/community#38317] [Actions]
I'm using Gradle and this is a part of my `build.gradle`:
```gradle
publishing {
    publications{
        // ...
    }
    repositories {
        mavenLocal()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/PillowMC/PillowMC")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
    }
}
```
My `gradle.yml`
```yaml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and publish with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: build publish
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: heipiao233
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: Artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*.jar
```
Now this buildscript can install packages with GitHub Packages, but when Gradle try to publish the artifact to GItHub Packages, it throws error code `403 Forbidden`
Note: The GITHUB_TOKEN had used to install packages before publishing packages. If the GITHUB_TOKEN can only use once, how can I get another one to publish my packages using actions?
