### DISCUSSION TITLE
New environment file issues with Outputs and fromJson

### DISCUSSION THREAD

**Discussion by TheOnlyWei** [community/community#38332] [Actions]
Getting deprecated "set-output" command warning, so I decided to update the notation to use github environment files, but started getting these errors:

`Error when evaluating 'strategy' for job 'Test_Second_Job'. .github/workflows/github-actions-demo.yml (Line: 28, Col: 21): Error parsing fromJson,.github/workflows/github-actions-demo.yml (Line: 28, Col: 21): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/github-actions-demo.yml (Line: 28, Col: 21): Unexpected type of value '', expected type: Sequence.`

I made changes according to the following link:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I created a very basic version of the workflow yaml file to try and pinpoint the issue as in the below link, but even that is giving the same errors:
https://github.com/TheOnlyWei/github_actions_test/blob/env-filetest/.github/workflows/github-actions-demo.yml
https://github.com/TheOnlyWei/github_actions_test/actions/runs/3398602911
```
name: GitHub Actions Demo
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test_First_Job:
    runs-on: windows-2019
    steps:
      - name: Convert input to JSON for matrix.
        id: matrix_json_step
        shell: pwsh
        run: |
          $jsonArrayString = "[`"test1:test2:test3`",`"test4:test5:test6`"]"
          echo "JSON_ARRAY=${jsonArrayString}" >> $GITHUB_OUTPUT

    outputs:
      JSON_ARRAY: ${{ steps.matrix_json_step.outputs.JSON_ARRAY }}

  Test_Second_Job:
    runs-on: windows-2019
    needs: Test_First_Job
    strategy:
      fail-fast: false
      matrix:
        JSON_ARRAY: ${{ fromJson(needs.Test_First_Job.outputs.JSON_ARRAY) }}
    steps:
      - name: Print JSON_ARRAY
        shell: pwsh
        run: |
          Write-Host "JSON_ARRAY VALUE IN SECOND JOB: ${{ matrix.JSON_ARRAY }}"
```
Anyone know how to fix this error? According to official document, the above should work. The above code worked fine with old "set-output" format.

According to fromJson doc, the above should work?
https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson

Filed a bug here:
https://github.com/actions/runner/issues/2245
