### DISCUSSION TITLE
Add properties to matrix

### DISCUSSION THREAD

**Discussion by dza89** [community/community#38429] [Actions]
I'm trying to set extra properties for my job configurations. 
Example:

```yaml
jobs:
  deploy:
    strategy:
      matrix:
        include:
          distro:
             - arch:
                 source: somesource1
                 target: sometarget1
             - debian:
                 source: somesource2
                 target: sometarget2

    steps:
      - uses: actions/checkout@v3
        run: |-
          cp ${{ matrix.distro.source }} ${{ matrix.distro.target }}
```

This isn't possible (yet) correct?
Any suggestions would be welcome.
