### DISCUSSION TITLE
Possibility to continue on the state of a previous job?

### DISCUSSION THREAD

**Discussion by mara004** [community/community#38443] [Actions] [answered]
In pypdfium2, we've got a [workflow](https://github.com/pypdfium2-team/pypdfium2/blob/main/.github/workflows/release.yaml) to do a fully automatic release (increment version, build wheels, push repository changes, upload wheels). It currently is a linear sequence of commands in a single job.

I am trying to improve this workflow (been experimenting in a fork) and would like to add the ability to test the built wheels on their target platforms (Windows/Linux/macOS) and supported Python versions (3.7-3.11) before publishing.

The first thought was to use a pipeline of `build -> test -> publish` jobs connected with `needs:` and share data using job outputs and artifacts. The problem is that `build` applies changes to the repository (commit, tag) which we want to push only after successful testing, but if `publish` is a separate job, we loose access to the repository state left by `build`. We need to continue on exactly this state to make sure there can be no inconsistencies between the published wheels and the repository by design. (Handling the whole repository as an artifact is out of question due to its size.)

I feel like the ideal solution to the problem would be if the `publish` job could continue just where `build` stopped, with the effect that one machine runs `build`, pauses while `test` is carried out on other machines, and then continues with `publish` on the initial machine.
I imagine something like a `continue-on: <job_name>` option that acts as a replacement to `runs-on: <os>`.

```yaml
jobs:
  build:
    # ... build steps
  test:
    needs: build
    if: ${{ inputs.test }}
    # ... testing matrix and steps
  publish:
    needs: test
    continue-on: build
    if: ${{ inputs.publish }}
    # ... publish steps
```

Is something like this already possible and I just overlooked it? If not, could it be implemented? Or do you know an existing, equivalent, alternative approach that would fulfill all our requirements?

I've tried many different approaches I could think of, but all of them seemed to imply re-constructing the state of `build` in `publish` to some degree, which I would strongly prefer to avoid because of the inconsistency risk mentioned above.
