### DISCUSSION TITLE
Request for context variable for jobs.<job_id>.environment

### DISCUSSION THREAD

**Discussion by clry-ida** [community/community#38466] [Actions]
It seems like there is missing an environment variable in the github.context for which environment that is being deployed to.

Consider:

```yaml
deploy:
    runs-on: ubuntu-latest
    needs: [build-test-and-push]
    timeout-minutes: 30
    environment: dev  # <--- env
    env:
      SEMVER: ${{ needs.build-test-and-push.outputs.semver }}
```
I am not able to find a reference for getting the current environment in the github.context anywhere. I can list, get, create and delete environments via the rest api (https://docs.github.com/en/rest/deployments/environments), however that is not of much use from within the workflow. 

Using other CI/CD tools, I can use this variable to dynamically determine resource names, and it would be nice to do that with GitHub Actions as well.

The only option I have found to overcome this is to convert everything to a reusable workflow, where the `workflow_call` input is the environment.

```yaml
on:
  workflow_call:
    inputs:
      GH_ENVIRONMENT:
        description: Name of GitHub environment
        required: true
        type: string

jobs:
  destroy-runner:
    runs-on: ubuntu-latest
    environment: ${{ inputs.GH_ENVIRONMENT }}
``` 

It would be awesome if the environment could be added to the github.context instead.

**Comment by ossanna16** [comment]
Hi there @clry-ida and welcome to our community! Thank you for the suggestion!

**Comment by goiPP** [comment]
I have the same need and would like to have this access for my custom action.  🙏 
Convert into a reuseable workflow will not work for my use case. So right now I would need to ask for user input which is strange in this sense:
```
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Deploy dev
        uses: my-custom-action@v0
        with:
          environment: dev
```
