### DISCUSSION TITLE
Permission errors with a distro package inside of Docker containers

### DISCUSSION THREAD

**Discussion by jeanas** [community/community#38510] [Actions] [answered]
Hi,

I'm not quite sure how to phrase the title of this question... The issue is a mystery for me. I'm quite new to GitHub actions, so keep in mind that it could be something simple, but I am obviously missing something.

For context, here is the upstream discussion in the LilyPond project:

https://lists.gnu.org/archive/html/lilypond-user/2022-11/msg00062.html
https://gitlab.com/lilypond/lilypond/-/issues/6460

LilyPond is a text-based music score compiler (“LaTeX for music scores”). In short, the issue is that when trying to use LilyPond in GitHub actions, it fails if (1) the job runs in a Docker container (with `container: {image: ...}`) *and* (2) LilyPond is installed from the Linux distro, be it Ubuntu or Fedora. However, it does not reproduce if `container: ...` is not used. Also, it does not reproduce when using the shell to download, unpack and run the official LilyPond generic Linux packages.

The error thrown by LilyPond is

```
warning: g_spawn_sync failed (0): gs: Failed to close file descriptor for child process (Operation not permitted)
fatal error: cannot rename `document-tmp-2786319.384671.pdf' to `document.pdf'
```

The operation that leads to the last fatal error is a simple call to the C standard library `rename ()` function, which returns a nonzero status code.

In other words, it looks like the LilyPond process does not have the necessary permissions on the file system.

There is a reproducer here:

https://github.com/Witiko/lilypond-github-actions-example

This is the action definition (there is also a small `document.ly` LilyPond file):

```
name: Typeset document
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  typeset-document:
    name: Typeset document
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Lilypond
        run: |
          set -e
          apt-get -qy update
          apt-get -qy install --no-install-recommends lilypond
      - name: Typeset score
        run: lilypond document.ly
```

In my fork at https://github.com/Jean-Abou-Samra/lilypond-github-actions-example, you can find an action definition that shows that it doesn't work with Fedora 37 either, and that it does work with official, standalone LilyPond binaries.

This issue also seems not to be reproductible in Docker containers outside of GitHub actions.

Given that it doesn't work neither with the Ubuntu package, nor with the Fedora package (the latter of which I am using myself), it must be something generic, but what? What can make a difference of permissions between the distro packages and the standalone binaries on two different systems inside GitHub actions? I am pretty puzzled. Any clue?

Thanks in advance.

**Comment by david-engelmann** [comment]
You can pass the following options to make the container run as root so the necessary permissions are used

```
runs-on: ubuntu-latest
container:
  image: ubuntu:22.04
  options: --user root
```
