### DISCUSSION TITLE
Why is my workflow running twice?

### DISCUSSION THREAD

**Discussion by pluim003** [community/community#38573] [Actions] [answered]
I have a workflow which is scheduled to run at 4AM UTC:

```
name: Build and push nightly

on:
  # cron job to trigger the build on any push to dev
  # push:
  #  branches:
  #    - 'dev'
  schedule:
  # cron job to trigger the build dialy (time in UTC)
    - cron:  '* 4 * * *'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of pihole docker
        uses: rez0n/actions-github-release@main
        id: pihole_version
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "pi-hole/docker-pi-hole"
          type: "nightly"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push nightly
        uses: docker/build-push-action@v3
        with:
          build-args: PIHOLE_VERSION=${{ steps.pihole_version.outputs.release }}
          context: "{{defaultContext}}:one-container/pihole-unbound/"
          file: "Dockerfile_nightly"
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: pluim003/pihole-unbound:nightly
```

This is running fine but when I look I see that it's always running twice. I can't get a clue why.

![afbeelding](https://user-images.githubusercontent.com/67138922/200590768-5b3e88ad-3f4a-434d-beca-c6ead6afd02e.png)
