### DISCUSSION TITLE
Authenticating against ghcr.io docker repository fails

### DISCUSSION THREAD

**Discussion by gmile** [community/community#38611] [Actions] [answered]
I am facing what seems like a rookie problem: an attempt to authenticate against a Docker registry of GitHub Packages from within a GitHub workflow fails.

I'm basically attempting to follow an example here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-11, with one important context clarification: I have two repositories, and trying to authenticate from a workflow in one - to access a package in another.

**Repository for `serviceA`** has a workflow, that attempts to start a service `serviceB` using image `ghcr.io/my_org/serviceB:sha1`. The workflow looks like this:

```yaml
name: Example

jobs:
  test:
    runs-on: ubuntu-20.04

    permissions:
      contents: 'read'
      packages: 'read'

    services:
      serviceB:
        image: ghcr.io/my_ord/serviceB:sha256
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    # steps that fire up a test suite
```

**Repository for `serviceB`**. A container image of `serviceB` is built and pushed to `ghcr.io/my_org/serviceB:sha1`, and "[inherited access](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#inheriting-access-for-a-container-image-from-a-repository)" is enabled.

It appears to me as if:

- either `github.actor`/`secrets.GITHUB_TOKEN` pair don't match. In fact, upon closer look I see that the value of `github.actor` is my username, while I was under impression it should maybe be the GitHub App's name or something?
- I am doing something completely wrong, e.g. to authenticate from one repo to access things (like code or packages) from another, more/different setup is required,
- I am missing something dramatically obvious in my code above.  

What is it that I may be getting wrong about how to set up access from one repo, to a package in another?
