### DISCUSSION TITLE
How to run a job in a container with architecture emulation?

### DISCUSSION THREAD

**Discussion by qrkourier** [community/community#38728] [Actions] [answered]
### Select Topic Area

Question

### Body

```yaml
jobs:
  package:
    runs-on: ubuntu-20.04
    container: 
      image: ${{ matrix.distro.container }}
      options: --platform=${{ matrix.arch.docker }} 
    strategy:
      matrix:
        arch:
          - docker: linux/amd64  # used by docker create --platform 
          - docker: linux/arm64/v8
        distro:
          - container: "ubuntu:jammy"
          - container: "ubuntu:focal"
```

I haven't found a value that works for `--platform` except `amd64`. I'm trying to enable emulation of `arm64` so I can use native build tools instead of cross-compiling on `amd64` for `arm64`.

The symptom is that the workflow throws an error like "Container is not running" when it tries to execute the first job step.

**Comment by ossanna16** [comment]
Hi there @qrkourier and welcome to our community! Thank you for asking a great question 🙂
While you are waiting for a reply to your question, here are a few things you can do:

To get started, introduce yourself in our [official introduction thread](https://github.com/orgs/community/discussions/23204)
To connect with other new users, check out this Discussion to [Meet Your GitHub Community Team](https://github.com/orgs/community/discussions/28776), further your GitHub knowledge by working through our [GitHub Skill 🆙 exercises](https://github.com/orgs/community/discussions/32121), and participate in our [weekly Fun Friday chats](https://github.com/orgs/community/discussions/30912)

**Comment by deric4** [comment]
The best way might be to leverage the [official GitHub Actions from Docker](https://docs.docker.com/build/ci/github-actions/)


I got nerd-sniped by this though and was curious how to do this on a gitHub-action-runner and with a workflow that has no permissions:

There might be a better way to do it but this was the "simplest/easiest" way to do it without actually pushing intermediate artifacts to a real container registry:


Workflow file with working example: https://github.com/deric4/github-action-runner-reference/actions/runs/3436296193/workflow

Job logs: https://github.com/deric4/github-action-runner-reference/actions/runs/3436296193/jobs/5729656545#step:2:381

### summary

1. build the qemu-user emulator binaries for your local platform

    ```bash
    docker run --privileged --rm tonistiigi/binfmt --install all
    ```

3. create a new buildx builder using the `docker-container` driver (default `docker` driver won't work)

   ```bash
   docker buildx create \
     --use \
     --name container \
     --driver-opt network=host \
     --driver docker-container \
     --bootstrap
    ```

5. run a local insecure registry (docker hub or ghcr could be configured)

    ```bash
    docker run --rm -d -p 5000:5000 --name registry registry:2
    ```

7. build the image with multiple platforms

    ```bash
    docker buildx build \
      --tag localhost:5000/deric4/gha-reference \
      --push \
      --platform linux/amd64,linux/arm64 . \
      -f-<<'EOF'
         FROM debian:latest
         CMD echo "\n\n\tIN CONTAINER\n\tarch: $(dpkg --print-architecture)\n\n"
    EOF
    ```

1. run containers with specific platform

    ```bash
    docker run \
      --platform linux/amd64 \
      --rm \
      localhost:5000/deric4/gha-reference

        IN CONTAINER
        arch: amd64

    docker run \
      --platform linux/arm64 \
      --rm \
      localhost:5000/deric4/gha-reference

        IN CONTAINER
        arch: arm64
    ```

**Reply by qrkourier** [reply]
Thanks, @deric4 . I learned a few things from your example. This would allow me to push the image to a local or remote registry. Still, the apparent limitation of the hosted runner (missing the emulation binaries?) means that even if I compose that container image for the correct platform I still can't run the entire job on that image (create a container runner with GitHub Actions). 

If I push to the local registry, it might be possible to extend that multi-platform-enabled job context to run the remaining, necessary build steps defined in the Dockerfile or an entrypoint script. That is, to run the bootstrapping steps you proposed on the runner VM instead of inside a container, and then to run the multi-platform image from the local registry to compile the workspace project for the target platform.

Yet another possibility is a self-hosted arm64 runner. If I'm reading the Actions doc correctly, I'll be able to substitute the `runs-on` value from the matrix and run only the arm64 iteration on my self-hosted arm64 runner. I'm leaning this way at the moment because it seems like a lighter lift than dealing with the complexity of emulation, which was itself more desirable than the even-greater complexity of cross-compiling.

This has been a journey already, for sure.

**Comment by jacob-carlborg** [comment, marked as answer]
This can be achieved much simpler now with Docker's official GitHub action:

```yaml
jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - docker: amd64  # used by docker create --platform
          - docker: arm64
        distro:
          - container: "ubuntu:jammy"
          - container: "ubuntu:focal"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}

      - name: Run in Docker
        run: |
          docker run \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/${{ matrix.arch }} \
            ${{ matrix.distro }} \
            uname -a
```
