### DISCUSSION TITLE
Github's GraphQL API cannot resolve global node_ids

### DISCUSSION THREAD

**Discussion by x10an14-nav** [community/community#38848] [Apps, API and Webhooks]
### Select Topic Area

Bug

### Body

Hi!

We use GH Project(v2) w/Kanban board view, and wrote our own automation tool to automagically move issues and PRs between columns on this board [1] [2].

We followed the documentation provided by Github documentation on how to do this [3].

<details>
<summary>Our YAML workflow</summary>

```yaml
name: Auto Assign Issues to Project(s)

on:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    types: [opened, reopened, converted_to_draft, ready_for_review, review_requested, closed]

jobs:
  update_project_with_issues:
    name: Update team project on creation/closure of repo Issues and PRs
    runs-on: ubuntu-22.04
    steps:

    - name: Debug
      run: |
        echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
        echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
        echo
        cat "${GITHUB_EVENT_PATH}"
    # Rules for 'Todo' column
    - name: Assign new issues and PR drafts to team project's 'Todo' column
      uses: navikt/pensjon-person-actions/flytt-oppgave-til-prosjektkolonne@main
      if: |
        github.event_name == 'issues' && (
          github.event.action == 'opened' || github.event.action == 'reopened'
        )
      with:
        github_token: ${{ secrets.UPDATE_ORG_PROJECT_TOKEN }}
        column_name: 'Todo'

    # Rules for 'In Progress'
    - name: Move reviewable PRs to team project's 'In Progress' column
      uses: navikt/pensjon-person-actions/flytt-oppgave-til-prosjektkolonne@main
      if: github.event.action == 'converted_to_draft'
      with:
        github_token: ${{ secrets.UPDATE_ORG_PROJECT_TOKEN }}
        column_name: 'In Progress'

    # Rules for 'Active PRs'
    - name: Move new PRs to team project's 'Active PRs' column
      uses: navikt/pensjon-person-actions/flytt-oppgave-til-prosjektkolonne@main
      if: |
        github.event_name == 'pull_request' && (
          github.event.action == 'opened'
          || github.event.action == 'reopened'
          || github.event.action == 'review_requested'
          || github.event.action == 'ready_for_review'
        )
      with:
        github_token: ${{ secrets.UPDATE_ORG_PROJECT_TOKEN }}
        column_name: 'Active PRs'

    # Rules for 'Done' column
    - name: Move closed Issues and PRs to team project's 'Done' column
      uses: navikt/pensjon-person-actions/flytt-oppgave-til-prosjektkolonne@main
      if: github.event.action == 'closed'
      with:
        github_token: ${{ secrets.UPDATE_ORG_PROJECT_TOKEN }}
        column_name: 'Done'
```

</details>

And yet we get this error message in our pipelines when we attempt to leverage the GH API with a GH issue:
![2022-11-11T10:03:01,227443840+01:00](https://user-images.githubusercontent.com/98316196/201305315-11d77dde-ede7-4e2c-94f2-2a9293000b9f.png)

We've confirmed that the node_id is the correct one, as long as the GH Events documentation is also correct [4] about the `issue.node_id` key/path in the JSON payload [5].

What have I/we misunderstood here?
This worked (when testing in another project and locally on my own machine) previously.

[1]: https://github.com/navikt/pensjon-person-actions/tree/main/flytt-oppgave-til-prosjektkolonne
[2]: https://git.sr.ht/~x10an14/assign-gh-item-to-project-field
[3]: https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects#adding-an-item-to-a-project
[4]: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issues
[5]: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-when-someone-edits-an-issue
