### DISCUSSION TITLE
Can not access mapped port number On Github actions

### DISCUSSION THREAD

**Discussion by hantsy** [community/community#38911] [Actions]
### Select Topic Area

Question

### Body

I created an simple Spring JMS example, which use a simple test to connect Artemis in Docker.

The example codes is here, https://github.com/hantsy/spring6-sandbox/tree/master/jms

```yaml
      
  artemis:
    image: qoricode/activemq-artemis
    environment:
      ARTEMIS_USERNAME: user
      ARTEMIS_PASSWORD: password
    volumes:
      - ./data/artemis:/var/lib/artemis/data
    ports:
      - "6161:61616"    
```

**On my local machine, it works well**. but when it was running failed on Github actions.

```bash 
 Errors: 
Error:    JmsTest.whenWaitOneSecond_thenReceiverShouldReceiveAllMessages:28 » UncategorizedJms Uncategorized exception occurred during JMS processing; nested exception is ActiveMQConnectionTimedOutException[errorType=CONNECTION_TIMEDOUT message=AMQ219013: Timed out waiting to receive cluster topology. Group:null]
```

The complete log stack: https://github.com/hantsy/spring6-sandbox/actions/runs/3449879946/jobs/5758114669
