### DISCUSSION TITLE
Workflow failed without all jobs being executed

### DISCUSSION THREAD

**Discussion by MemphisMeng** [community/community#38952] [Actions]
### Select Topic Area

Question

### Body

I have 2 jobs in my YAML workflow file; the second job needs the result from the first one. I have no idea why the workflow failed before the second one was run.

Here is the definition (pseudo-code):

```
name: my-code
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: ECS_TASK_DEFINITIONCheckout
      uses: actions/checkout@v3
      with:
          fetch-depth: 2
     - name: Get changed files in services
      id: changed-files-specific
      uses: tj-actions/changed-files@v34
      with:
        files: |
          services/**
    - name: Get the folder name
      id: get-folder-name
      run: |
        changed_folders=()
        for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            dir="$(cut -d'/' -f2 <<<"$file")" # always get the secondary folder from /services
            if [[ ! " ${changed_folders[*]} " =~ " ${dir} " ]]; then # only add the folder name if it wasn't included
                changed_folders+=(${dir})
            fi
          done
        # echo "::set-output name={folders}::{${changed_folders[*]}}"
        echo "folders=${changed_folders[*]}" >> $GITHUB_OUTPUT
        echo "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.get-folder-name.outputs.folders }}
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: 
        folders: ${{ needs.setup.outputs.matrix }}
    steps:
    - name: test
      run: |
        echo "${matrix.folders}"
```
<img width="1045" alt="Screen Shot 2022-11-12 at 3 56 46 PM" src="https://user-images.githubusercontent.com/37232969/201494343-fe6e2326-9f70-4ef2-9b87-0ace8e555583.png">

**Comment by airtower-luna** [comment]
I assume this is the problem:

```yaml
    strategy:
      matrix: 
        folders: ${{ needs.setup.outputs.matrix }}
```

The data for a matrix variable needs to be a list. An output is a string. What you can do is something like this, but only if the output string contains a valid JSON array:

```yaml
    strategy:
      matrix: 
        folders: ${{ fromJSON(needs.setup.outputs.matrix) }}
```

As I read your `setup` job, the output contains a simple space separated list. If you format it as a JSON array (like `["folder1", "folder2"]`) *and* use the `fromJSON()` approach it should work.

Also there might be error/warning messages below the diagram you posted a screenshot of, make sure to check those for other problems that might be less obvious.
