### DISCUSSION TITLE
Can not use environment variable in `with` keyword

### DISCUSSION THREAD

**Discussion by yaoluoye** [community/community#39033] [Actions] [answered]
### Select Topic Area

Question

### Body

This is my workflow file
```
on:  push
env:
  environment: dev
  aws_region: us-east-2

jobs:
  CI:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      aws_region: ${{ env.aws_region }}
```

It had an error: Unrecognized named-value: 'env'
