### DISCUSSION TITLE
Mention people from comment generated by workflow?

### DISCUSSION THREAD

**Discussion by AlexanderLanin** [community/community#39049] [Actions]
### Select Topic Area

Question

### Body

Our idea was to notify people when the devcontainer has changed, since people often did not notice the VS Code popup and wondered why new things are not working for them.

What I discovered is that I cannot mention teams from comments created by workflows. Is this intentional? 
Maybe there is a completely different and better approach to this?

Here is the workflow. The @ does not trigger a notification/mention, it does not become clickable, it remains pure text. When I edit and save the comment unmodified the notifications work perfectly!

```
name: "devcontainer changed notification"
on:
  pull_request:
    types: [closed]
    paths:
      - ".devcontainer/*"
      - ".github/workflows/devcontainer-changed-info.yml"
jobs:
  comment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Dear @OrganisationName/TeamName,
            
            the devcontainer has changed! You can see what is new via the link below.

            Some ways how you can get the update:
            * Delete your Codespace and create a new one based on main, within the Codespace switch to your branch.
            * F1->Rebuild (~5 Minutes)
            * Just ignore this, finalize your PR and create a new Codespace tomorrow
```

Update 2012-12-06:
As of today, highlighting seems to work. Did someone fix it? :D
But notifications are not being send for those highlighted teams.
