### DISCUSSION TITLE
Can push in one repo to a branch using "GitHub Actions Bot" but cannot in other repo

### DISCUSSION THREAD

**Discussion by ashishjullia** [community/community#39040] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Bug

### Body

Hi,

So, I've two different repo's under which I'm trying to push an intermediate code to a particular branch in the repo but I'm getting the following error:
`fatal: could not read Username for 'https://github.com/': No such device or address`

With the following gh actions workflow yaml file:

```
name: deploy development

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS CLI for "gh actions" user
        id: ghactions
        # if: steps.apply.outcome == 'failure'
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::xxxxxxxxxx:role/admin-role-gh-actions
          role-duration-seconds: 1200
          role-session-name: GithubActionsSession

      - name: Upload working code to s3
        id: s3upload
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          repository: "username/repo"
          fetch-depth: '0'
          ref: 'main'
          path: s3-upload
      
      - name: Copy current working code to s3 bucket
        if: github.event_name == 'pull_request'
        run: |
          cd s3-upload
          zip -r working-code.zip .
          aws s3 cp working-code.zip s3://tf-test-s3-ashish/working-code/

      - name: Get Terraform Version
        run: |
          echo "TF_VERSION=$(head -n 1 .terraform-version)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: $TF_VERSION

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        if: "steps.init.outcome == 'success' && github.event_name == 'pull_request'"
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve -input=false
        continue-on-error: true

      - name: old directory
        id: old
        if: steps.apply.outcome == 'failure'
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          path: old
      
      - name: new directory
        uses: actions/checkout@v3
        id: new
        if: steps.old.outcome == 'success'
        with:
          path: new
      
      - name: Setup Code and Rollback
        id: rollback
        if: steps.old.outcome == 'success'
        run: |
          mkdir working-code
          aws s3 cp s3://bucket-name/working-code/working-code.zip ./working-code/
          cd working-code
          unzip -q working-code.zip
          rm working-code.zip
          cp ../new/provider.tf .
          ls -la
          terraform init
          terraform apply -auto-approve -input=false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
      
      - name: create pull request
        id: pullrequest
        if: steps.rollback.outcome == 'success'
        run: |
          mkdir intermediate-code
          aws s3 cp s3://bucket-name/working-code/working-code.zip ./intermediate-code/
          cd intermediate-code
          unzip -q working-code.zip
          rm working-code.zip
          git checkout old-code
          git pull
          date > rollback
          git add .
          git commit -m "rollback"
          git push -u origin old-code
          gh pr create -B main -H old-code --title 'Merge old-code into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

Note: The error is on `create pull request` step when I'm merging the `Pull Request` into the `main` branch.

Considering the above scenario, I google the error and came across a few StackOverflow posts but I think those are a little misleading:
Post 1: https://stackoverflow.com/questions/74148649/fatal-could-not-read-username-for-https-github-com-no-such-device-or-addr
Post 2: https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457

So after thinking a little after reading the answers in these post's answers^, I created a new repo with the following gh actions workflow YAML and surprisingly for the new repo the `push` to a branch is working completely fine.

```
name: deploy development

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          path: intermediate-code
      
      - name: Setup AWS CLI for "gh actions" user
        id: ghactions
        # if: steps.apply.outcome == 'failure'
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::xxxxxxxxxxxxx:role/admin-role-gh-actions
          role-duration-seconds: 1200
          role-session-name: GithubActionsSession

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Upload to s3
        id: upload
        run: |
          cd intermediate-code
          zip -r intermediate-code.zip .
          aws s3 cp intermediate-code.zip s3://bucket-name/intermediate-code/

      - name: Get old code, then update and create a pull request
        id: pullrequest
        run: |
          mkdir downloaded-code
          aws s3 cp s3://bucket-name/intermediate-code/intermediate-code.zip ./downloaded-code/
          cd downloaded-code
          unzip -q intermediate-code.zip
          rm intermediate-code.zip
          ls
          git checkout intermediate-code
          git pull
          date > file2.txt
          git add .
          git commit -m "downloaded file.txt"
          git status
          ls
          git branch
          git push -u origin intermediate-code
          # gh pr create -B main -H intermediate-code --title 'Merge downloaded-code into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Any help or insights on this issues is highly appreciated, It has been 2 days I'm struggling with this error, which is kind of irrelevant to me at this moment.
