### DISCUSSION TITLE
why is the github.event.pull_request.labels.*.name empty after the labeler have ran and set the labels

### DISCUSSION THREAD

**Discussion by SadriG91** [community/community#39062] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a GitHub action workflow that labels pull requests but when i try to retrieve the labels in the workflow it seems to be empty so i am wondering why is this happening?

Here you can see the workflow

```
jobs:
  triage:
    name: 'Set Labels'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        sync-labels: true
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Get PR labels
      id: pr-labels
      env: 
          PR_LABEL_LIST: ${{ toJson(github.event.pull_request.labels.*.name) }}
      run: |
        printf '${{ env.PR_LABEL_LIST }}' > /tmp/label_list        

```
        
And here you can see that's there is nothing there
![image](https://user-images.githubusercontent.com/74971461/201652128-82c42b3f-3dec-4155-8578-f38d9351b896.png)        

Can someone please help with this, am i missing something or is this a bug?
