### DISCUSSION TITLE
schedule trigger only running when the workflow file is on the default branch

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#39064] [Actions]
### Select Topic Area

Bug

### Body

More like a potential documentation bug:

For every trigger that the corresponding workflow file is required to be present in the default branch, there is an explicit mention in the [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows).

![Screenshot 2022-11-14 at 2 04 28 PM](https://user-images.githubusercontent.com/50835081/201655759-2fed7196-9219-43ed-95e8-5098a1f8d837.png)

This is not the case for workflows [triggered](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) `on: schedule`.

I have created and pushed to a (non-default) branch the following workflow:

```yaml
name: Test scheduled execution

on:
 schedule:
  - cron: "*/5 * * * *"

jobs:
  test-schedule:
    runs-on: ubuntu-latest

    steps:

      - name: test scheduled execution
        shell: bash
        run: echo "Hello World"
```

Am I or are the docs missing something?
