### DISCUSSION TITLE
Status check not being updated after successful execution of workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#39070] [Actions]
### Select Topic Area

Bug

#### Bug Description

I have a workflow that performs some checks and either fails or exits.

The corresponding step that performs that main tasks goes more or less as follows

```
      - name: perform PR approval if applicable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        shell: bash
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            PR_NUMBER=${{ github.event.number }}
          else
            PR_NUMBER=${{ github.event.issue.number }}
          fi
          echo "Checking whether to approve PR number $PR_NUMBER..."
          COMMENT_USER=`echo $GITHUB_CONTEXT | jq '.event.comment.user.login'`
          PR_AUTHOR=`echo $GITHUB_CONTEXT | jq '.event.issue.user.login'`
          if [[ $COMMENT_USER == $PR_AUTHOR && ${COMMENT_BODY} == \"${{ env.AUTOMERGE_COMMENT_BODY }}\" ]]; then
            echo "Approving the PR..."
            gh pr review --approve $PR_NUMBER
          else
            echo "This PR will not be auto approved..."
            exit 1
          fi
```

I test run by writing a comment that does not correspond to `${{ env.AUTOMERGE_COMMENT_BODY }` and (as expected if tails).

I subsequently make comment with the required contents and it succeeds.

However, in the PR, the check is **still** marked as failed.

![Screenshot 2022-11-14 at 3 08 40 PM](https://user-images.githubusercontent.com/50835081/201668193-f923cb45-8f52-4255-8893-01bc7bbb7931.png)

The `Details` link points to the failed (second to last) workflow run

**In case the first execution is successful, the status is green** (as expected)

Isn't this a bug?

#### Additional Info

FWIW, the above is part of a re-usable workflow, (`reusable.yaml`) that is called as follows:

```yaml
name: Test and bypass branch protection on PR comment

on:
  pull_request:
    types:
      - opened
    branches:
      - 'target_branch'
  issue_comment:
    types:
      - created
    
jobs:

  check-if-pr-should-be-approved:
   uses: Org/repo/.github/workflows/reusable.yaml@master
```
