### DISCUSSION TITLE
How to use a variable in all reusable workflows

### DISCUSSION THREAD

**Discussion by yaoluoye** [community/community#39120] [Actions] [answered]
### Select Topic Area

Question

### Body

I want to set a variable in all reusable workflows, but the `env` can't do it; can another way get it?

```
on:  push

jobs:
  CI:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      aws_region: us-east-2
  CD:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      aws_region: us-east-2
```
