### DISCUSSION TITLE
How can I pass files between jobs amd workflows？

### DISCUSSION THREAD

**Discussion by zctmdc** [community/community#39172] [Actions] [answered]
### Select Topic Area

Question

### Body

I write some workflows,I write at the end.
Although they work fine, when multitasking concurrently, repeated checkouts will consume a lot of resources, is there any way to reuse checkouts once?

Maybe there is a way to use some methods in step to stop the current step. But not on all setps use 'if:'  `cancel`
Of course, I might need Github Action to return a status of success instead of failure. `exit 1`

Thanks for your help
> Using a matrix strategy with a reusable workflow: <https://docs.github.com/en/actions/using-workflows/reusing-workflows>  

您好，我编写了一些workflows，我附在最后面。
虽然正正常运行着，但是使用矩阵策略，我不知道如何将签出的文件传递到被调用的工作流中。如果每次都签出，那么将花费大量的时和计算资源。
有什么办法将当前环境文件直接传递到被调用的工作流中么？
怎么在当前任务的某个环节直接停掉当前任务，不继续执行。将接下来所有的环节取消？
如果不可这样，怎么在任务中复用当前文件，而不需要每次都签出？
```
   - name: some step
     if: needs.job1.outputs.stop != 'true'
   - name: other step
     if: needs.job1.outputs.stop != 'true'
```

 like:
```yaml
# tmp1.tml
name: Docker-build-and-push
on:
  workflow_call:
    inputs:
      version_b_s_rc:
        required: true
        type: string

      force_push:
        description: "force push to registry"
        required: true
        type: boolean
        default: false
        
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      some_changes: ${{ steps.change.outputs.some_changes }}
      stop: ${{ steps.flag-run.outputs.stop }}
    steps:
      - name: Checkout repository on build-psuh
        uses: actions/checkout@v3
      - name: will make file change
        id: change
        run: |
          `make some change`
          echo "some_changes=${changes}" >> $GITHUB_OUTPUT
      - name: keep run flag
        id: flag-run
        run: |
          `Make some judgments`
          echo "stop=true" >> $GITHUB_OUTPUT
      # - ... more step
  job2:
    needs: [job1]
    if: needs.job1.outputs.stop != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository on build-psuh
        uses: actions/checkout@v3
      - name: Reproduce changes
        run: |
          changed=${{ needs.job1.outputs.some_changes }}
          `reproduce changes`
      # - ... more step
```

```yaml
# tmp1.tml
name: manual-scan-all-to-build

on:
  workflow_dispatch:
    inputs:
      build-releases-version:
        description: "Build all releases versions? v2s|v2|v1"
        required: true
        type: boolean
        default: false
      force-push:
        description: "force push to registry"
        required: true
        type: boolean
        default: false

jobs:
  scan-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check build_version
        id: build_version
        run: |
         `do get all version`
          version_b_s_rcs="{\"include\":[${version_b_s_rcs}]}"
          force_push=${{ inputs.force-push }}
          echo "version_b_s_rcs=${version_b_s_rcs}" >> $GITHUB_OUTPUT
          echo "force_push=${force_push}" >> $GITHUB_OUTPUT

  build-all:
    needs: [scan-all]
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.scan-all.outputs.version_b_s_rcs) }}

    uses: ./.github/workflows/tmp1.yml
    with:
      version_b_s_rc: ${{ matrix.version_b_s_rc }}
      force_push: ${{ needs.scan-all.outputs.force_push == 'true' }}
    secrets: inherit
```
The full document is here:
see: <https://github.com/zctmdc/n2n-lucktu/tree/master/.github/workflows>
