### DISCUSSION TITLE
Authorized user cannot push in GitHub action

### DISCUSSION THREAD

**Discussion by goulon** [community/community#39189] [Actions]
### Select Topic Area

Question

### Body

I've set up an action to push a new commit to the trunk branch once a PR merges.
Also, the autorized_user that authors the commit is among the **specified actors allowed to bypass required pull requests** and **can push to matching branches** on trunk.

The new commit fails to be pushed, even though the commit author has push permission for this repo.

It is not clear which additional settings should be enabled for the autorized_user to push a new commit.
Is it possible to push a commit in such a way?

Here's the message that my action outputs:
````
✖  fatal     remote: error: GH006: Protected branch update failed for refs/heads/trunk.        
remote: error: Changes must be made through a pull request. You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.        
To https://github.com//<org>/<repo>.git
 ! [remote rejected]   trunk -> trunk (protected branch hook declined)
error: failed to push some refs to 'https://github.com/<org>/<repo>.git'

git exited with code 1
✖  fatal     Failed to bump version
````

Here's the corresponding action file:
````
name: Auto-bump-version on merging a Pull Request
on:
  pull_request:
    branches:
      - trunk
    types:
      - closed

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: 'echo PR merged on trunk branch'

      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          git config user.name "authorized_user"
          git config user.email "authorized_user@email.com"

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
          GITHUB_USER: 'authorized_user'
          GITHUB_EMAIL: 'authorized_user@email.com'
        with:
          tag-prefix: 'v'
          version-type: 'major'
          target-branch: 'trunk'
          commit-message: "{{version}}\n\nCI: bump version to {{version}} [skip ci]"
          bump-policy: 'ignore'

````
