### DISCUSSION TITLE
(solved) ambiguous github actions workflow error

### DISCUSSION THREAD

**Discussion by mccroweyclinton-EPA** [community/community#39194] [Actions] [answered]
### Select Topic Area

General

### Body

Good afternoon, I have a python project that I have been working on for a while now that is sitting on a private github repository, I want to make this repository public there is only one thing that is preventing me to do so; I can't can not get github actions CI/CD to work properly. For some reason I keep recieving these ambiguous error messages in my .github/workflow yaml file.

```yaml
name: pyaqsapi test and build on Linux
run-name: A push event from ${{ github.actor }} caused a rebuilding and
          retesting of the pyaqsapi package via GitHub actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    #runs-on: matrix.os
    env:
      AQSkey: ${{ secrets.AQSKEY }}
      AQSuser: ${{ secrets.AQSUSER }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        #os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: install_dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
- name: Display Python version and system info
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import platform; print(platform.uname())"
      #- name: fail on misspelled words
         fail the build in case of any misspelled words
        run: |
          if [-s "./_build/spelling/output.txt"]; then | 
          echo ++++++++++++++++++++ Misspelled words ++++++++++++++++++++ & 
          cat "./_build/spelling/output.txt"; fi
         # if [-s "./_build/spelling/output.txt"]; then false; fi
      - name: build apidocs
        run: |
          cd docs
          sphinx-apidoc --ext-autodoc -o . ../pyaqsapi/
          make html
      - name: test_package
        run: |
           export AQSkey=${{ secrets.AQSKEY }}
           export AQSuser=${{ secrets.AQSUSER }}
           pytest
           unset AQSkey
           unset AQSuser
```

For some reason I get an "invalid workflow file error" on line 38 but github does not tell me exactly what is wrong with that line.
For reference, line 38 is this:
```YAML
if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
```
Which *should* work, I've even tried removing the if statement to just have:
``YAML
pip install -r requirements.txt
```
but that gives the same error message. Can someone please tell me why this workflow is causing a error? I have tried changing this file many times this week to get this to work.
