### DISCUSSION TITLE
Docker service image uses latest version instead of the specified one

### DISCUSSION THREAD

**Discussion by petersg83** [community/community#39248] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hello :)

First of all, I don't know a lot about github actions. So maybe there is an obvious thing I don't see :)

**Summary**
I try to run tests on MySQL version 5 but it apparently runs with MySQL version 8 (latest). I discovered that by handling a test that should have failed with v5 but didn't. 

**Is it a bug, or is the config wrong?**

**Details**
As you can see in this logs https://github.com/strapi/strapi/actions/runs/3478068012/jobs/5816050634
(in **Initialize container** > **Starting mysql service container**), the MySQL image is pulled twice (line 16 and line 70).
Once for the version I'm targeting (5.7.8) and once for the latest version. I don't understand why the latest is pulled and, from what I understand, used.

![Capture d’écran 2022-11-16 à 14 06 04](https://user-images.githubusercontent.com/11708220/202190177-8241cf6d-dcbb-4b3f-9e6e-8a66a18c92bf.png)
![Capture d’écran 2022-11-16 à 14 06 13](https://user-images.githubusercontent.com/11708220/202190182-7499e603-b82b-41ce-97c9-58ddf4aa698b.png)

You can see the github action config there: https://github.com/strapi/strapi/blob/fix/github-test-mysql5/.github/workflows/tests.yml.
An extract of the workflow:
```yml
  api_ce_mysql_5:
    runs-on: ubuntu-latest
    needs: [lint, unit_back, unit_front]
    name: '[CE] API Integration (mysql:5 , node: ${{ matrix.node }})'
    strategy:
      matrix:
        node: [14, 16, 18]
    services:
      mysql:
        image: mysql:5.7.8
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          -e MYSQL_ROOT_PASSWORD=strapi
          -e MYSQL_ROOT_HOST="%"
          -e MYSQL_USER=strapi
          -e MYSQL_PASSWORD=strapi
          -e MYSQL_DATABASE=strapi_test
          --entrypoint sh mysql -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
        ports:
          # Maps tcp port 5432 on service container to the host
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - uses: ./.github/actions/install-modules
      - uses: ./.github/actions/run-api-tests
        with:
          dbOptions: '--dbclient=mysql --dbhost=localhost --dbport=3306 --dbname=strapi_test --dbusername=strapi --dbpassword=strapi'
```

### Related PR
https://github.com/strapi/strapi/pull/14878
