### DISCUSSION TITLE
Pulling docker multi-platform containers from GitHub workflows

### DISCUSSION THREAD

**Discussion by mwilck** [community/community#39282] [Actions] [answered]
### Select Topic Area

Question

### Body

In my CI, I use `qemu-user-static` to run foreign platform containers in GH workflows. This works well, generally, e.g. using [dbhi/qus](https://github.com/dbhi/qus).

The remaining problem is that while dbhi/qus enables my workflows to execute foreign-arch executables, I have found no way to make sure that the desired architecture of the respective docker image is being pulled. The [docker docs](https://docs.docker.com/build/building/multi-platform/) specify that multi-platform is implemented on the registry using a separate manifests for the same image for different architectures. For running it locally, you would do something like

    docker run -it --rm --platform arm64 alpine:latest $COMMAND

(note that a different containers is pulled for different values of `--platform`, even though container name and tag don't change).

Neither `jobs.<job_id>.container` nor `jobs.<job_id>.steps[*].uses` seem to support `--platform`, or arbitrary docker command line arguments, for that matter.

It can be achieved by simply using `run: docker --platform …`, but that seems clumsy in a workflow context. Currently I am using my personal fork of [mosteo-actions/docker-run](https://github.com/mosteo-actions/docker-run), but perhaps someone knows a more elegant / ready-to-use approach?

Otherwise, the only possibility I see is to use platform-dependent container names or tags in the container registry, but I find that clumsy as well.

Ideas / hints appreciated.

**Comment by david-engelmann** [comment, marked as answer]
You can specify options such as platform from the actions yaml, [here is a list of available options](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontaineroptions). I'll include a little snippet below that could be incorporated into your setup

```
jobs:
  build:
    name: Container with name
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/repo/image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --platform arm64
```
