### DISCUSSION TITLE
Matrix does not allow to use global env variable on its values

### DISCUSSION THREAD

**Discussion by sofiamsa** [community/community#39355] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm trying to use an environment variable as an element of a matrix to use on a template input. my_var is used among many jobs and each time I try to use any ${{ }} value on the matrix it throws an error.  

env:
     my_var : my_value_${{ github.run_id }}.tar.gz

jobs:

  compilation:
    runs-on: own_runner 
    strategy:
      matrix: 
        mode: ['value1']
        command: ['value1'] 
        artifacts_path: ['value1']
        artifacts: [ ${{ ev.my_var }} ]
    steps:
    - uses: actions/checkout@v3
    - name: Build tool ${{ matrix.mode}}
      uses: ./ci_cd/jobs/tests_templates/compilation/
      with:
        mode: ${{ matrix.mode}}
        command: ${{ matrix.command}}
        artifacts_path: ${{ matrix.artifacts_path}}

    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifacts}}
        path: ${{ matrix.artifacts}}
        retention-days: 3

![image](https://user-images.githubusercontent.com/81657545/202526194-225727bf-94f9-428c-9480-f88def607412.png)

**Comment by airtower-luna** [comment]
You can't access the `env` context outside steps, this is [described in the documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#env-context):

> You can use the env context in the value of any key in a step except for the id and uses keys.

There may be additional problems (including some that won't be visible without a code block), e.g. `ev` here instead on `env`:

```
artifacts: [ ${{ ev.my_var }} ]
```

But using an environment variable to define a matrix won't work either way. A job output from a previous job would work.

**Comment by sofiamsa** [comment]
Missed a typo since I was erasing company info:) so, there would be a way to use definitions on matrix? I have not found yet information on that.  I would hard-code the path of the partifact, but still this path is using the github.run_id which I can't still use. 
If I change it to this:

 ```
compilation:
    runs-on: self_hosted
    strategy:
      matrix: 
        mode: ['value1']
        command: ['value1'] 
        artifacts_path: ['value1']
        artifacts: [ artifact_name_${{ github.run_id }}.tar.gz ]
    steps:
    - uses: actions/checkout@v3
    - name: Build tool ${{ matrix.mode}}
      uses: ./ci_cd/jobs/tests_templates/compilation/
      with:
        mode: ${{ matrix.mode}}
        command: ${{ matrix.command}}
        artifacts_path: ${{ matrix.artifacts_path}}
    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifacts}}
        path: ${{ matrix.artifacts}}
        retention-days: 3
```


Then I get the same issue since the github.run_id can not be used.
