### DISCUSSION TITLE
One of the workflows outputs seems empty

### DISCUSSION THREAD

**Discussion by ferferga** [community/community#39408] [Actions] [answered]
### Select Topic Area

Bug

### Body

I have a workflow defined like this [(direct link to the original)](https://github.com/jellyfin/jellyfin-vue/blob/master/.github/workflows/job_messages.yml):

```
name: Job messages ⚙️

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
      commit:
        required: true
        type: string
      preview_url:
        required: false
        type: string
      build_workflow_run_id:
        required: false
        type: number
      commenting_workflow_run_id:
        required: true
        type: string
      in_progress:
        required: true
        type: boolean
    outputs:
      msg:
        description: The composed message
        value: ${{ jobs.msg.outputs.msg }}
      marker:
        description: Hidden marker to detect PR comments composed by the bot
        value: ${{ jobs.msg.outputs.comment_marker }}

jobs:
  msg:
    name: Deployment status
    runs-on: ubuntu-latest
    env:
      COMMENT_MARKER: '<!--- CFPages deployment marker --->'
    outputs:
      msg: ${{ steps.compose.outputs.msg }}
      comment_marker: ${{ env.COMMENT_MARKER }}

    steps:
      - name: Compose message 📃
        if: ${{ always() }}
        id: compose
        env:
            ..................................
        run:
           ...................................
          echo "msg<<EOF" >> $GITHUB_OUTPUT
          echo "$COMPOSED_MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

............................................................
```

I call and reuse the workflow like this in one of [the files](https://github.com/jellyfin/jellyfin-vue/blob/master/.github/workflows/automation.yml#LL12C3-L33):

````
compose-comment:
    name: Compose PR comment
    if: ${{ always() && github.event_name == 'pull_request_target' }}
    uses: ./.github/workflows/job_messages.yml
    with:
      commit: ${{ github.event.pull_request.head.sha }}
      commenting_workflow_run_id: ${{ github.run_id }}
      in_progress: true

  push-comment:
    name: Push comment to PR 🖥️
    if: ${{ always() && github.event_name == 'pull_request_target' && contains(join(needs.*.result, ','), 'success') }}
    runs-on: ubuntu-latest
    needs:
      - compose-comment

    steps:
      - uses: thollander/actions-comment-pull-request@v1.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: ${{ needs.compose-comment.msg }}
          comment_includes: ${{ needs.compose-comment.marker }}
````
I also call it in [this file](https://github.com/jellyfin/jellyfin-vue/blob/master/.github/workflows/deploy.yml#L60-L91).

No matter what, the ``msg`` output is always empty. However, the reusable workflow **generates an output correctly, as can be seen in the summary of this [sample run with debugging enabled](https://github.com/jellyfin/jellyfin-vue/actions/runs/3492625747/jobs/5846837185)**

When I had the same job copied across all workflows, I used it creating an ``msg`` environment variable (instead of an output, so echoing to ``$GITHUB_ENV`` instead of ``$GITHUB_OUTPUT``) to overcome the 1 MB output limit (so, instead of setting the ``msg`` job with the ``msg`` output as ``${{ steps.compose.outputs.msg }}`` I did ``${{ env.msg }}``). However, after seeing that the reusable workflow had a blank output in the ``comment-workflow`` (thus failing), I switched to outputs, without any luck as you can see me writing here, so I'd like to know as well if I can use ``${{ env.msg }}`` as the output for a job.

Everything is perfectly matching the docs, so I have no clue what else could be going on here.

**Comment by ferferga** [comment, marked as answer]
I was missing the ``outputs`` property everywhere (i.e ``${{ needs.job1.outputs.firstword }}`` instead of ``${{ needs.job1.firstword }}``

The fix in one of the step block is:

```
steps:
      - uses: thollander/actions-comment-pull-request@v1.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: ${{ needs.compose-comment.outputs.msg }}
          comment_includes: ${{ needs.compose-comment.outputs.marker }}
```

Kudos to GitHub Support for resolving the matter so quick!
