### DISCUSSION TITLE
Name of a step in a composite action is not printed as the step name in a workflow

### DISCUSSION THREAD

**Discussion by zdybasny** [community/community#39424] [Actions]
### Select Topic Area

Product Feedback

### Body

Sample code:
``` yaml
    - name: "Release action: '${{ env.TAG_NAME }}'"
      uses: softprops/action-gh-release@v0.1.14
      with:
        name: ${{ env.TAG_NAME }}
        tag_name: ${{ env.TAG_NAME }}
```

The syntax [`jobs.<job_id>.steps[*].name
`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsname) in a workflow works fine. It prints the name as a foldable group of logs .

![image](https://user-images.githubusercontent.com/34143177/202720580-24277538-e9a5-4641-b5d5-ba9768117964.png)

In case of `jobs.<job_id>.steps[*].name` within a composite action, is it only `run:` or `uses:` content prompted. No `name` prompted at all.

![image](https://user-images.githubusercontent.com/34143177/202720420-3b879ed3-218d-40e8-80b3-08124dad5f83.png)

I believe, `name` description is more readable for workflows users (e.g. developers, mangers) to let them know what is happenings in the workflow. Is is even less readable in case of multiline shell script, since it is prompted only the first line of the script, so the users need to unfold it to read more.

Is there a chance to consider putting somehow the composite action's `jobs.<job_id>.steps[*].name` content to the logs natively by GitHub Action? Maybe an additional line with some highlight on it, or maybe another layer of foldable group?
