### DISCUSSION TITLE
Dependabot keep asking: Dependabot version updates aren't configured yet

### DISCUSSION THREAD

**Discussion by doublevkay** [community/community#39630] [Code Security] [answered]
### Select Topic Area

Bug

### Body

Hi there, 

I have configured `dependabot.yml` with the content below:
```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(deps)
    reviewers:

      - @userA
    open-pull-requests-limit: 0
```
- The instruction `commit-message.prefix` works well. But the `open-pull-requests-limit` seems like it does not work at all. It limits the pull request to 5 as default. And also, when i navigate to **Insights > Dependency Graph > Dependabot** , it keep show the message:
```
Dependabot version updates aren't configured yet
```
<img width="913" alt="Screenshot 2022-11-21 at 14 15 39" src="https://user-images.githubusercontent.com/45411113/202987915-4420c0e9-c46b-4fe4-ba39-7c99ca4fd9a3.png">

**Comment by ericvercherat** [comment, marked as answer]
Hi ! 
Please see  https://docs.github.com/fr/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#disabling-dependabot-version-updates

open-pull-requests-limit: 0   will disable version updates.

**Reply by doublevkay** [reply]
hi, so how can i stop limit pull requests for security alerts but still disable version updates?

**Reply by ericvercherat** [reply]
seems like you can't modify PR request limit for security updates 
"This option has no impact on security updates, which have a separate, internal limit of ten open pull requests."
see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit

**Reply by doublevkay** [reply]
thx @ericvercherat

**Reply by tboddyspargo** [reply]
@ericvercherat - I'm not confident in this strategy at the moment. I'm looking at a `dependabot.yml` that has:

```
version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/app-name'
    schedule:
      interval: 'daily'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'org/team-name'
    open-pull-requests-limit: 0
```

But dependabot just opened a PR to `chore(deps): Bump rpyc from 5.1.0 to 5.3.1 in /app-name` and there's no indication of any CVE or dependabot vulnerability in either the PR or my repo > `Security` > `Dependabot` page.

- Is there a reliable indicator that a given PR was the result of security update configuration or version update configuration?
- Is it possible there's a bug with the logic of `open-pull-requests-limit: 0` that is still allowing some version update PRs to be created?
