### DISCUSSION TITLE
Github action hang up when read string from /dev/urandom

### DISCUSSION THREAD

**Discussion by adoyle-h** [community/community#39644] [Actions] [answered]
### Select Topic Area

Question

### Body

```
jobs:
  mac:
    runs-on: macos-12
    steps:
    - run: LC_ALL=C tr -dc "a-zA-Z0-9@#*=[]" < /dev/urandom | head -c 10
```

It will hang up forever. Why?
