### DISCUSSION TITLE
Composite actions download all docker images mentioned.

### DISCUSSION THREAD

**Discussion by JJ** [community/community#39691] [Actions] [answered]
### Select Topic Area

Bug

### Body

Not totally sure this is a bug, but in [this action](https://github.com/JJ/raku-test-action):

```yaml
name: 'raku-test-action'
description: 'Test raku modules caching dependencies'
branding:
  icon: 'life-buoy'
  color: 'blue'
inputs:
  coverage:
    description: "Will test coverage or not"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Obtains source
      uses: actions/checkout@v3
    - name: Cache installed distros
      uses: actions/cache@v3
      id: meta6
      with:
        path: ~/.raku/
        key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
    - name: Test and install for more tests
      if: ${{ ! inputs.coverage }}
      uses: docker://ghcr.io/jj/raku-zef-gha
    - name: Test and install for more tests
      if: ${{ inputs.coverage }}
      uses: docker://ghcr.io/jj/raku-racoco-gha
```

My intention was to download and use only the container that's affected; downloading the other takes 6 seconds, so no big deal, but still, [it downloads both](https://github.com/retupmoca/p6-markdown/actions/runs/3517325466/jobs/5894965067)

Any configuration tweak I could do to avoid this?

> Also, cache does not seem to be working. But that's another issue...
