### DISCUSSION TITLE
No way to use set-output replacements cross-platform

### DISCUSSION THREAD

**Discussion by Manishearth** [community/community#39715] [Actions] [answered]
### Select Topic Area

Bug

### Body

set-output and save-state are deprecated now:

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The recommendation is to instead use 

```
- name: Save state
  run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

However, this isn't cross-platform, since you need to use `$env:GITHUB_OUTPUT` (etc) on Windows. `${{ env.GITHUB_OUTPUT }}` doesn't work here.

Just using `if` isn't enough either because then you need two tasks, and they need two separate ids, so they can't write to the same variable. The lack of this functionality very quickly snowballs into a lot of complexity.

**Comment by airtower-luna** [comment, marked as answer]
> However, this isn't cross-platform, since you need to use $env:GITHUB_OUTPUT (etc) on Windows.

Try setting the shell for the step (or even job, if that doesn't conflict with other things) [to `bash`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-running-a-script-using-bash). The syntax depends on the shell, not the platform, it's only that the default shell varies by platform.

**Comment by Manishearth** [comment]
ah, hm, thanks!

**Comment by pbatard** [comment]
> The syntax depends on the shell

This kind of blows, because the previous syntax didn't and now you are forcing users to update their script with more than just replacing `set-output`, especially on Windows.

See for reference the following workflow:
```
name: VS2022

on: push

jobs:
  VS2022-Build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Old method
      id: old_method
      run: echo "::set-output name=option::THIS_ACTUALLY_WORKS"

    - name: New method
      id: new_method
      run: echo "option=THIS_NO_LONGER_WORKS" >> $GITHUB_OUTPUT

    - name: Build
      shell: cmd
      run: |
        echo "Old method: ${{ steps.old_method.outputs.option }}"
        echo "New method: ${{ steps.new_method.outputs.option }}"
        echo "As far as I am concerned, this is a regression, GitHub!"
```

This is what most people would have on Windows, since the old method wouldn't require specifying a shell, as it was shell agnostic. Thus, as far as I am concerned, replacing it with a new method that isn't shell agnostic __is__ a regression.

__At the very least__, put a note in https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ that Windows workflow users need to force the shell to bash for the new syntax highlighted there to work... I just wasted 3 hours on this!

Please remember that not all Actions users are running on Linux...
