### DISCUSSION TITLE
GitHub Action is not triggering the build with the correct branch

### DISCUSSION THREAD

**Discussion by f-roche** [community/community#39756] [Enterprise]
### Select Topic Area

Question

### Body

Hi all,

we recently moved our Git repositories from Azure DevOps to GitHub Enterprise but we would like to continue using DevOps for Continuous Integration.

So we need to trigger Azure Pipelines when a pull request is being created in GitHub.
Following the GitHub documentation we wrote the following workflow in YAML:
```
name: CI

# Run this workflow every time a pull request gets opened against develop branch
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://devops.medpace.com/devops/DefaultCollection/IQS
        azure-pipeline-name: Continuous Integration
        azure-devops-token: ${{ secrets.DEVOPS_SERVER_PACKAGES }}
```
 Then when creating a new pull request targeting `develop` branch:
![image](https://user-images.githubusercontent.com/10049032/203329046-e905a329-6931-4ff6-94f8-a20feb3de1ad.png)

here is what we have on Azure DevOps side in the pipeline:
![image](https://user-images.githubusercontent.com/10049032/203331164-6ebb6c85-f858-4c6f-8ddb-8872d4cfd961.png)
It keeps triggering the `develop` branch instead of the pull request branch (merge of the feature branch into `develop`).

What am I doing wrong here?
