### DISCUSSION TITLE
Actions reusable workflows: Jobs dependencies

### DISCUSSION THREAD

**Discussion by sofiamsa** [community/community#39783] [Actions]
### Select Topic Area

Question

### Body

Hi! Is there a way to make a dependency over a reusable workflow **specific job** ? 
I have been trying to use jobs ids and name to make this dependency. 
A reusable workflow **commit.yml** with a job named "check_system_spechs" is being called from a caller workflow **nightly.yml** where  a job named python_syntax_check is used and depends only on job check_system_spechs. 

`  
```
python_syntax_check:
    needs: [commit **HERE DEPENDS ONLY ON JOB FROM REUSABLE WORKFLOW]**
    runs-on: 
    steps:
    - uses: actions/checkout@v3
    - name: Run pycodestyle scanner
      uses: ./ci_cd/jobs/tests_templates/scans/pycodestyle/

```
