### DISCUSSION TITLE
Please give us filters for "on: create"

### DISCUSSION THREAD

**Discussion by RupertBarrow** [community/community#39831] [Actions]
### Select Topic Area

Product Feedback

### Body

I would like to promote the latest beta tag to release every time a "release" branch is created.
For that, I need omething like : 
```
on:
  ## Whenever a release branch is created
  create:
    branches:
      - "release/**"
```
