### DISCUSSION TITLE
Allow a job to be cancel only for pull requests.

### DISCUSSION THREAD

**Discussion by theophileds** [community/community#39899] [Actions]
### Select Topic Area

Question

### Body

We use **styfle/cancel-workflow-action** in order to stop current jobs in case a subsequent commit has been pushed within the same branch.

However, we're trying to prevent this from happening when the Job is running in the master branch.
Our current implementation roughly looks like this:
```
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: (!cancelled() || ${{ github.ref == 'refs/heads/master' }})
```

And we would expect the following scenario given the OR logic:
```
Job not canceled OR branch != master -> True
Job not canceled OR branch == master -> True
Job canceled OR branch != master -> False
Job canceled OR branch == master -> True
```

However, this job still ends canceled when running in master, therefore, we're wondering if the OR evaluation within GH actions might be different than other language paradigms.
