### DISCUSSION TITLE
GitHub Actions Job/Workflow environment variables DO NOT WORK ON WINDOWS, fine on ubuntu

### DISCUSSION THREAD

**Discussion by SimonDarksideJ** [community/community#39944] [Actions] [answered]
### Select Topic Area

Bug

### Body

Took a while to get to the root of this so bare with me, essentially when we were in the progress of updating all our "Set-Output" usage in our GitHub actions pipelines we hit a critical show-stopper issue in that Variables were NO LONGER passed between jobs or workflows.  
All we changed was to update all "Set-Output" usage to the new ">> $GITHUB_OUTPUT"  style, no names or anything else was changed.  It didn't work.

Eventually, we tried to replicate this using GitHubs own example and found it worked, BUT ONLY FOR UBUNTU, when run on Windows, it failed.

```yaml
name: GitHub Outputs

on:
  workflow_call:
    inputs:
      build-target:
        required: true
        type: string  
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ jobs.job1.outputs.output1 }}
      workflow_output2:
        description: "The second job output"
        value: ${{ jobs.job1.outputs.output2 }}

jobs:
  job1:
    runs-on: windows-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
```

We replicated using the GitHub example from the docs above with the following results:

* On "ubuntu-latest", the output value "hello" was detected and was readable using the output of the workflow
* On "windows-latest" (and our self-hosted windows build server), no output value is available and a blank string is read.

This poses a fundamental issue in that we cannot upgrade our workflows which, for the majority, run on our own Windows self-hosted agents.
