### DISCUSSION TITLE
Images compress in test repo but not Github Pages website

### DISCUSSION THREAD

**Discussion by LayersOfAbstraction** [community/community#39966] [Actions]
### Question

Hi I am using [Calibre Image Actions](https://github.com/calibreapp/image-actions) and are trying to use it to compress my images. 

So for at least a week, I have struggled to compress images on push. I have no idea why it works in my [test repository](https://github.com/LayersOfAbstraction/repo) where I do random things. 

But in my [Github Pages Portfolio](https://github.com/LayersOfAbstraction/layersofabstraction.github.io/tree/compress-images)(see the compress-images branch), it skips the action and that just _stuns_ me because the code in the YAML file is the same as in the test repo I made. Why does my action get ignored in the portfolio?

### Environment Infomation
**OS** Ubuntu 20.04.5
**OS Version** 20221027.1
**Browser**  Google Chrome Version 107.0.5304.107 
**Browser version** 107.0.5304.107 
**git version** 2.38.1

### How To Reproduce

If possible, please you should be able to do all this on Github if you'd rather not clone the repo to your desktop.
1. Fork my [portfolio repo ](https://github.com/LayersOfAbstraction/layersofabstraction.github.io/tree/compress-images)in Github and ensure you are on the compress-images branch (haven't merged with master).

2. Add an image to it. You can just drag and drop if you want.   

3. Check the actions menu and you will see it has skipped the whole action and gives no reason as to why. There is a way to debug, then I do not know what to use for that.

The code looks like this very very similar to what is in your README file. 

```yml
name: Compress Images
on:
  push:
    branches:
      - compress-images
    # Run Image Actions when JPG, JPEG, PNG or WebP files are added or changed.
    # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths for reference.
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    # Only run on Pull Requests within the same repository, and not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          # The `GITHUB_TOKEN` is automatically generated by GitHub and scoped only to the repository that is currently running the action. By default, the action can’t update Pull Requests initiated from forked repositories.
          # See https://docs.github.com/en/actions/reference/authentication-in-a-workflow and https://help.github.com/en/articles/virtual-environments-for-github-actions#token-permissions
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

### Screenshots

![image](https://user-images.githubusercontent.com/11329310/203551646-af74a6fe-8955-4eb9-9ab8-38c61a883762.png)
