### DISCUSSION TITLE
Starting an updated workflow from Pull Request

### DISCUSSION THREAD

**Discussion by dar6k6night** [community/community#40063] [Actions] [answered]
### Select Topic Area

Question

### Body

We handle everything PR this way:

```
name: CI-PR-BUILDS
on:
  pull_request_target:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  build_on_win:
    timeout-minutes: 600
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: echo "1"
```

if we create a PR with changed workflow file data:
```
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: echo "2"
```

then the build will print 1 in the echo.
How can I make github action pick up the new yaml file and print 2?
