### DISCUSSION TITLE
Per "environment" environment variables

### DISCUSSION THREAD

**Discussion by NatoNathan** [community/community#40064] [Actions]
It would be nice if we could set plain text environment variables on a Per "environment" level in addition to environment secrets

**Comment by ossanna16** [comment]
Hi there @NatoNathan and thank you for the feedback! Welcome to our community!

**Comment by bobthemighty** [comment]
I have a mad use case for this right now.

I've got a monorepo where we have a CI/CD setup using actions and Terraform. I've created a fork of that repository so that we can test our actions without breaking the main repository. Accordingly, there's a few things that I need to tweak, eg. aws account ids, domain names etc.

Right now, the only way I can do that is by setting up secrets on both repositories and passing them explicitly to terraform. It would be _much_ nicer, if I could just set `TF_VAR_foo` as an environment variable on the fork, and use that to override config without changing any of the actions or terraform code.

**Reply by bobthemighty** [reply]
Fixed this by writing a custom github action that exports variables from a json file. That way I can say

```yml
name: Load override variables
if: github.repository == 'my-fork'
uses: ./.github/actions/set_env_vars
with:
    config: ./.github/config/ci-cd-test.json
```
