### DISCUSSION TITLE
Action running from graph testing question

### DISCUSSION THREAD

**Discussion by schalkneethling** [community/community#40227] [Actions]
### Select Topic Area

Question

### Body

When creating an action from the https://github.com/actions/javascript-action template repository, it has two test actions set up in the `test.yml` workflow. The one calls `npm test` and uses Jest for unit testing the action. There is another one defined:

```yml
# test action works running from the graph
test:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - uses: ./
    with:
      milliseconds: 1000
```

 The comment for this second one states, "test action works running from the graph." There is no other documentation mentioned related to this. I am curious to understand and learn more about when you would use this. All information and pointers are welcome. Thanks!
