### DISCUSSION TITLE
GitHub Actions: can't change user groups

### DISCUSSION THREAD

**Discussion by barrettj12** [community/community#40236] [Actions]
### Select Topic Area

Bug

### Body

I can't change the user groups I'm in using `newgrp`.

Here's a MWE workflow:

```yaml
name: "newgrp test"
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo groupadd foo
        sudo usermod -a -G foo $USER
        newgrp foo
        groups
```

The output of `groups` is
```
docker adm systemd-journal
```
so I haven't been added to the new `foo` group.
