### DISCUSSION TITLE
Pull request stuck into: Expected — Waiting for status to be reported

### DISCUSSION THREAD

**Discussion by pedrotavares-MG** [community/community#40275] [Pull Requests]
### Select Topic Area

Bug

### Body

Pull request stuck into Expected — Waiting for status to be reported. I checked and the checks have run successfully. 

My current CI configuration is: 

```
---
name: Continuos Integration
on:
  pull_request:
    branches:
      - 'main'

jobs:
  code-quality-checks:
    name: 'Code quality checks'
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly

      - name: Install node and npm based on the volta config in our package.json
        uses: volta-cli/action@v1

      - name: Get node version for cache key
        id: cache-key
        run: echo "::set-output name=node_version::$(node --version)"

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.cache-key.outputs.node_version }}
          registry-url: https://npm.pkg.github.com/<COMPANY_NAME>

      - name: Use the node_modules cache if available
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ steps.cache-key.outputs.node_version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.cache-key.outputs.node_version }}-

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}

      - name: 'Formatting'
        run: |
          npm run prettier

      - name: 'Linting'
        run: |
          npm run lint

      - name: 'Unit tests'
        run: |
          npm run test
      - name: 'build nuxt'
        run: |
          npm run build
  # THIS HAS TI BE REVIEWED THE CODE WAS RUNNING AGAINST A STATIC BUILD OF THE SITE AND WE ARE USING SSR
  # integration-tests:
  #   name: 'Integration tests'
  #   runs-on: ubuntu-18.04
  #   defaults:
  #     run:
  #       working-directory: src
  #   env:
  #     ENV_FILE: .env.dev
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install node and npm based on the volta config in our package.json
  #       uses: volta-cli/action@v1

  #     - name: Get node version for cache key
  #       id: cache-key
  #       run: echo "::set-output name=node_version::$(node --version)"

  #     - name: Use the node_modules cache if available
  #       uses: actions/cache@v2
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ steps.cache-key.outputs.node_version }}-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-${{ steps.cache-key.outputs.node_version }}-

  #     - name: 'Install dependencies'
  #       run: npm ci

  #     # Cypress is run against the generated static build
  #     - name: 'Generate static build'
  #       run: npm run generate

  #     - name: 'Run Cypress tests'
  #       run: npm run cy:ci
  tag:
    runs-on: ubuntu-20.04
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
      previous_tag: ${{ steps.tag.outputs.previous_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  BuildDockerImage:
    runs-on: ubuntu-20.04
    needs:
      - tag
      - code-quality-checks
      - Yamllint
    env:
      CONTAINER_TAG: ${{ needs.tag.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID_WEB_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_WEB_PROD }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build docker image
        run: |
          make docker-build

      - name: Push docker image
        run: |
          make docker-push

      - name: Replace variable
        run: |
          sed -ir "s/^container_tag =.*/container_tag = \"${{ needs.tag.outputs.new_tag }}\"/" terraform/environments/dev.tfvars
          sed -ir "s/^container_tag =.*/container_tag = \"${{ needs.tag.outputs.new_tag }}\"/" terraform/environments/prod.tfvars
          sed -ir "s/^container_tag =.*/container_tag = \"${{ needs.tag.outputs.new_tag }}\"/" terraform/environments/preview.tfvars

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Update version in terraform prod
        uses: test-room-7/action-update-file@v1
        with:
          file-path: terraform/environments/prod.tfvars
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.GIT_BRANCH_NAME }}

      - name: Update version in terraform dev
        uses: test-room-7/action-update-file@v1
        with:
          file-path: terraform/environments/dev.tfvars
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.GIT_BRANCH_NAME }}

      - name: Update version in terraform dev
        uses: test-room-7/action-update-file@v1
        with:
          file-path: terraform/environments/preview.tfvars
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.GIT_BRANCH_NAME }}

  TerraformPlan:
    name: "Terraform Plan"
    runs-on: ubuntu-18.04
    needs:
      - tag
      - BuildDockerImage
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Setup credentials to be used by terraform
      # Docs https://github.com/dflook/terraform-github-actions/tree/master/terraform-applys
      TERRAFORM_HTTP_CREDENTIALS: github.com/<COMPANY_NAME>:${{ secrets.GH_EC2_RUNNER }}
    strategy:
      max-parallel: 3
      matrix:
        env:
          - dev
          - prod
          - preview
        include:
          # includes a new variable for each env
          # (this is effectively a switch statement)
          - env: dev
            AWS_ACCESS_KEY_ID: AWS_KEY_ID_WEB_DEV
            AWS_SECRET_ACCESS_KEY: AWS_SECRET_KEY_WEB_DEV
            AWS_REGION: eu-west-1
          - env: prod
            AWS_ACCESS_KEY_ID: AWS_KEY_ID_WEB_PROD
            AWS_SECRET_ACCESS_KEY: AWS_SECRET_KEY_WEB_PROD
            AWS_REGION: eu-west-1
          - env: preview
            AWS_ACCESS_KEY_ID: AWS_KEY_ID_WEB_PROD
            AWS_SECRET_ACCESS_KEY: AWS_SECRET_KEY_WEB_PROD
            AWS_REGION: eu-west-2

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[matrix.AWS_ACCESS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[matrix.AWS_SECRET_ACCESS_KEY] }}
          aws-region: ${{ matrix.AWS_REGION }}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          label: "Environment: ${{ matrix.env }}"
          path: terraform
          var_file: terraform/environments/${{ matrix.env }}.tfvars
          backend_config_file: terraform/environments/${{ matrix.env }}.backend

  Yamllint:
    name: "Yaml lint"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install && run yamllint"
        run: |
          sudo apt-get install -y yamllint
          yamllint -c .yamllint .github/workflows

  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
