### DISCUSSION TITLE
Add ability to obtain the job id from single leg of matrix run

### DISCUSSION THREAD

**Discussion by jdolitsky** [community/community#40291] [Actions]
### Select Topic Area

Product Feedback

### Body

Please see the following Stack Overflow post for more context: https://stackoverflow.com/questions/71240338/obtain-job-id-from-a-workflow-run-using-contexts

When running a job using matrix strategy, if an individual leg of the matrix fails, I would like to obtain a link to the failed leg.

This is available through the GitHub API. When querying an action run, you can loop through the jobs and check for one which has a matching `name`, then extract the `html_url` field.

It would be ideal to be able to get this using syntax such as `${{ github.job.id }}`. This could then be used to contruct the html URL manually using something like:

```
https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job_id }}
```

**Comment by ossanna16** [comment]
Hi there @jdolitsky and welcome to our community! Thank you for the feedback!

**Comment by aabouzaid** [comment]
That would be totally helpful because now you need to do a lot of magic to get the numeric job id (as shown in the URL).

**Comment by carlobeltrame** [comment]
There is a github action that does exactly this, and also outputs the full html_url as it is returned from the GitHub API: https://github.com/marketplace/actions/github-actions-job_id-parser

**Reply by rafaelsvieira** [reply]
I think it's could be more simpler. And there is a problem when we are using this action with reusable workflows. Job references are lost because the job name is contained within the reusables and not in the main workflow. [Example](https://github.com/rafaelsvieira/reusable-workflow-dummy/actions/runs/3746027545/jobs/6361012393#step:4:5)

**Comment by Borda** [comment]
I was using `ReeganExE/github-action-job-id` which seems to work on all OS compare to the mentioned above, but a problem is that a pairing based on `${{ strategy.job-index }}` does not work consistently as for example I have a few single jobs running before the main job with the matrix... :(

**Comment by BenedekFarkas** [comment]
Haven't tested, but what you need might available now as `github.job`: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

Although it can only be used in the execution steps, so it can't be used as a fallback value for the concurrency key.

**Reply by huetterma** [reply]
Sadly this is just the job-name a step is running in, not the ID for the workflow run

**Comment by qoomon** [comment]
Feel free to use my action to access current `job` name  (among other context information)
It works even for matrix jobs e.g. `build (matrix, properties)` and within reusable workflows e.g. `parent_workflow / build`

Example Workflow
```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    environment: playground
    permissions:
      actions:     read  # required for qoomon/actions--context action
      deployments: read  # required for qoomon/actions--context action
      contents: read
    steps:
      - uses: qoomon/actions--context@v1
        id: context

      - run: |
          echo "Current Environment: ${{ steps.context.outputs.job }}"
          echo "Current Environment: ${{ steps.context.outputs.environment }}"
          echo "Job Logs: ${{ steps.context.outputs.job_log_url }}"
```
