### DISCUSSION TITLE
How to Auth for POST /merge-upstream

### DISCUSSION THREAD

**Discussion by Jackbennett** [community/community#40369] [Actions]
### Select Topic Area

Question

### Body

I can't seem to find a PAT or github app config that will let a workflow sucesffuly hit the merge-upstream API. Can this be done?

My github app has write access to repo contents but the closest I've gotten is a 403 response. "Resource not accessible by integration"

Looking for an action in the fork to sync its upstream, Both are private repos. At the moment this action is in a 3rd private ops repo, it doesn't have to stay separate but that's where I have the githubApp key secrets.

Example workflow:

```yaml
jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Get token
      id: get_token
      uses: wow-actions/use-app-token@v2
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PEM }}
    - uses: octokit/request-action@v2.x
      id: sync_upstream
      with:
        # Use app token in the environment variable named "BOT_TOKEN"
        route: POST /repos/:owner/:repo/merge-upstream
      env:
        INPUT_REPO: example
        INPUT_BRANCH: master
        INPUT_CONCLUSION: success
        INPUT_STATUS: completed
        INPUT_OWNER: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
        GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}
        GIT_COMMITTER_EMAIL: ${{ env.BOT_NAME }}@users.noreply.github.com
    - run: "echo sync results: ${{ steps.sync_upstream.outputs.data }}"
```
