### DISCUSSION TITLE
gh action choice parameter

### DISCUSSION THREAD

**Discussion by craftytech** [community/community#40366] [Actions]
### Select Topic Area

Question

### Body

hello folks, 

     Is there an issue way to use the input choice parameter dynamically?  I want to use the last 5 git hashes as choices.  I know I can get the list of hashes from the cli, i.e,

`git log --pretty=format:'%H' -n 5`

  >>---------------->>

```
name: Manual Deploy from Main
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: pick one
        options:
        - one
        - two
        - three
```

But is there a way of feeding that into the input choice parameter ??
