### DISCUSSION TITLE
<title>working-directory in action step

### DISCUSSION THREAD

**Discussion by WcaleNieWolny** [community/community#40367] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello, I have this action:
```
name: Project build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install latest rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
          components: rustfmt, clippy
    - name: run cargo fmt
      working-directory: ./ayaya_native
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: install java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - name: compile application
      run: make compile
```

however for some reason the  `working-directory` does not work. It tells me that ` working-directory cannot be used with uses , with ` any idea how to fix that?
