### DISCUSSION TITLE
Github action triggered in private repo but public repo

### DISCUSSION THREAD

**Discussion by kanglcn** [community/community#40392] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi,

I have a public repo: https://github.com/kanglcn/insar101 to write and host a website with the [quarto](https://quarto.org/) tool. The `main` branch is the source code, and the `gh-pages` is the generated website content.

I have two workflow files. The [deploy.yml](https://github.com/kanglcn/insar101/blob/main/.github/workflows/publish.yml) is used to render the content and update the `gh-pages`:

```
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The [sftp.yml](https://github.com/kanglcn/insar101/blob/main/.github/workflows/sftp.yml) is used to copy the `gh-pages` branch to another server via SFTP:
```
on:
  workflow_dispatch:
  page_build:

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: sftp to SMU
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SMU_HOST_USER}}
          server: ${{ secrets.SMU_HOSTNAME }} 
          sftp_only: true
          password: ${{ secrets.SMU_HOST_PASSWORD }}
          local_path: './*'
          remote_path: '/users/pubhtml/other/kangl/public_html/insar101'
          sftpArgs: '-o ConnectTimeout=5'
```
I found the first workflow can be corrected triggered by push, then the github pages was built successfully. However, the second workflow was not triggered. The interesting thing is, if I change the repo from public to private, the second workflow will be triggered.

I suspect this is due to the secret permission is not set correctly. After searching on web and github doc, I didn't find any solution.

Does anybody know the solution?
Thanks!

**Comment by ossanna16** [comment]
Hi there @kanglcn and welcome to our community! Thank you for asking a great question 🙂
While you are waiting for a reply to your question, here are a few things you can do:

To get started, introduce yourself in our [official introduction thread](https://github.com/orgs/community/discussions/23204)
To connect with other new users, check out this Discussion to [Meet Your GitHub Community Team](https://github.com/orgs/community/discussions/28776), further your GitHub knowledge by working through our [GitHub Skill 🆙 exercises](https://github.com/orgs/community/discussions/32121), and participate in our [weekly Fun Friday chats](https://github.com/orgs/community/discussions/30912)

**Comment by airtower-luna** [comment]
The reason is that you use the `GITHUB_TOKEN` to authorize the push, as [mentioned in the docs](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow):

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.

If you want the push to trigger a workflow, you'll need to [use a PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) instead.

**Reply by kanglcn** [reply]
Hi,

I have tried to create a PAT to replace the `GITHUB_TOKEN`. But the second workflow still was not triggered. Please look at the recent actions at https://github.com/kanglcn/insar101/actions

Here is the permission that I give to this PAT:
```
 Read access to actions, code, commit statuses, deployments, discussions, environments, issues, metadata, pages, pull requests, and secrets
```
I have no idea what is wrong. Do you think there is any problem?
Thanks.

**Reply by airtower-luna** [reply]
Code access (but with write permission!) should be sufficient. However I don't know if that `quarto-dev/quarto-actions/publish` actually uses the `GITHUB_TOKEN` environment variable. Maybe you have to provide the token in some other way? I'm not familiar with that action.

**Reply by kanglcn** [reply]
Thank you for your help! I am also not familiar with that action too. I will ask under the `quarto-action` repository to check if anybody have idea there.

**Reply by airtower-luna** [reply, marked as answer]
On more possibility is that they don't do anything for authentication at all, and expect the Git repository to be set up with authentication. [`actions/checkout`](https://github.com/actions/checkout) does that with the `GITHUB_TOKEN` by default, if you want to use a different one you can use it's `token` parameter:

```yaml
- uses: actions/checkout@v3
  with:
    token: ${{ secrets.PAT }}
```
