### DISCUSSION TITLE
Multiple choice/Checkbox as input for manual workflows.

### DISCUSSION THREAD

**Discussion by de3129** [community/community#40421] [Actions]
### Select Topic Area

Question

### Body

Hi everyone,
I need a multiple choice/checkbox to be define as input for manual workflows. This feature is not available now 
https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
and I dont know how I can implement it?

Thanks for your help.
Djelloul

**Comment by ossanna16** [comment]
Hi there @de3129 and welcome to our community! Thank you for asking a great question 🙂
While you are waiting for a reply to your question, here are a few things you can do:

To get started, introduce yourself in our [official introduction thread](https://github.com/orgs/community/discussions/23204)
To connect with other new users, check out this Discussion to [Meet Your GitHub Community Team](https://github.com/orgs/community/discussions/28776), further your GitHub knowledge by working through our [GitHub Skill 🆙 exercises](https://github.com/orgs/community/discussions/32121), and participate in our [weekly Fun Friday chats](https://github.com/orgs/community/discussions/30912)

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by joao-zanutto** [comment]
Recently, I came across a similar challenge: I needed multiple checkboxes in my `workflow_dispatch` event, and I needed to retrieve a list with the names of all the selected checkboxes.

To implement the multiple-choice checkboxes, you add as many single checkbox options as needed:
```yml
on:
  workflow_dispatch:
    inputs:
      option1:
        type: boolean
      option2:
        type: boolean
      option3:
        type: boolean
``` 

To retrieve the selected checkbox names, I created a custom action as I haven't found an easy way to do that without a for loop in bash ([GitHub Marketplace](https://github.com/marketplace/actions/get-selected)):

```yml
jobs:
  get-selected:
    name: Get Selected Checkboxes
    runs-on: ubuntu-latest
    outputs: # This needs to be set if you want to consume the output on another job
      selected: ${{ steps.get-selected-step.outputs.selected}}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get Selected
        id: get-selected-step
        uses: joao-zanutto/get-selected@v1

      - name: Consume on the same job
        run: echo ${{ steps.get-selected-step.outputs.selected }}

  consume-on-another-job:
    runs-on: ubuntu-latest
    name: Consume Output
    needs: get-selected
    steps:
      - name: Print
        run: echo ${{ needs.get-selected.outputs.selected }}
```
