### DISCUSSION TITLE
Setting output using python file working on ubuntu-latest runner, but not working on windows-latest runner

### DISCUSSION THREAD

**Discussion by sayyid5416** [community/community#40515] [Actions] [answered]
# My repository structure
- .github
    - workflows
        - test.yml
- set.py

### set.py
```python
import os
print('-> Python script ran')                             # This is just to test, if script ran or not
os.system('echo "name=Sayyid" >> $GITHUB_OUTPUT')
```

### test.yml
```yaml
on: [push, workflow_dispatch]

jobs:
  test-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - run: python "set.py"
        shell: bash
        id: name
        
      - run: echo "-> ${{ steps.name.outputs.name }}"         # prints the output which was set in set.py
```

<br>

# Result of workflow
- It works fine on `ubuntu-latest`
- It **doesn't** work on `windows-latest`
    - Python script ran properly.
    - But, Output was not set successfully.
    - I even tried removing `shell: bash` from `test.yml` file, but same results.

![image](https://user-images.githubusercontent.com/78584556/204971637-7149969e-f925-4e42-8f3a-715024790c5c.png)
![image](https://user-images.githubusercontent.com/78584556/204971722-2142e4ff-4dcc-4f51-ad43-2c91f60ac903.png)
