### DISCUSSION TITLE
<kbd> - Image Markdown Rendering

### DISCUSSION THREAD

**Discussion by ElectronicsArchiver** [community/community#40533] [Repositories]
### Select Topic Area

Bug

### Body

<br>

## TLDR

Images in `<kbd>` tags are assigned the wrong background color.

<br>
<br>

## Visualization

<img width = 200 src = 'https://avatars.githubusercontent.com/u/85485984'>
<kbd><img width = 200 src = 'https://avatars.githubusercontent.com/u/85485984'></kbd>

<br>
<br>

## Details

The following css rule affects **all** images in markdown.

```css
.markdown-body img {
    ...
    background-color: var(--color-canvas-default);
}
```

<br>
<br>

## Fix

Adding a simple css rule that uses the same color as a `<kbd>` will fix this.

```css
.markdown-body kbd img {
    background-color: var(--color-canvas-subtle);
}
```

<br>
<br>

## Question

Why do images in markdown bodies have a background color in the first place?

<br>
