### DISCUSSION TITLE
Dependabot with AWS CodeArtifact as npm-registry

### DISCUSSION THREAD

**Discussion by andreadeluisi-ryte** [community/community#40551] [Code Security]
### Select Topic Area

Question

### Body

Hi, 
I'm trying to integrate Dependabot having AWS CodeArtifact as a private artifactory following these instructions: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#npm-registry)

The `dependabot.yml` file looks something like this:
````
version: 2
registries:
  npm-codeartifact:
    type: npm-registry
    url: https://***.d.codeartifact.eu-central-1.amazonaws.com
    token: ${{secrets.CODEARTIFACT_TOKEN}}
updates:
  - package-ecosystem: 'npm'
    registries:
      - npm-codeartifact
 (...and so on)
````
The problem is that CODEARTIFACT_TOKEN has a validity of 12 hours, afterward will be invalid.
I would really like to have the possibility to do something like this:
````
version: 2
registries:
  npm-codeartifact:
    type: npm-registry
    url: https://***.d.codeartifact.eu-central-1.amazonaws.com
    access-key: ${{secrets.CODEARTIFACT_ACCESS_KEY}}
    secret-access-key: ${{secrets.CODEARTIFACT_SECRET_ACCESS_KEY}}
````
I'd be really happy to receive suggestions or recommendations from your side.
