### DISCUSSION TITLE
All Annotations not showing in composite actions

### DISCUSSION THREAD

**Discussion by sayyid5416** [community/community#40606] [Actions]
# Information
- My workflow file
```yaml
on: [push, workflow_dispatch]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./
```

- My `action.yml` file in root directory (`./`)
```yaml
runs:
  using: 'composite'
  steps:
    - run: echo "::notice title=Notice::This is the 1st notice"
      shell: bash

    - run: echo "::notice title=Notice::This is the 2nd notice"
      shell: bash

    - run: echo "::warning title=Warning::This is the 1st warning"
      shell: bash

    - run: echo "::warning title=Warning::This is the 2nd warning"
      shell: bash
```

<br>

# Issue
When workflow is ran, Only annotations available in the last step is shown. Annotations of previous steps are not shown. But all of them can be seen properly in the logs.
![image](https://user-images.githubusercontent.com/78584556/205241304-17d70216-e29c-495d-8d55-e05f09b1c072.png)
![image](https://user-images.githubusercontent.com/78584556/205241711-b9f0f072-3080-4532-a81e-efbb83542367.png)

### Expected behavior
All the **notice** and **warning** annotations should be shown in the Annotations in summary page.

### Issue
Only annotations of last step are shown. 

**Any solution for this?**
