### DISCUSSION TITLE
Unable to start service mysql in a molecule test

### DISCUSSION THREAD

**Discussion by g0blin79** [community/community#40615] [Actions]
### Select Topic Area

Bug

### Body

**Describe the bug**
Hy guys!
I'm decided to open an issue here after I've been opened a related thread on the Community Support some weeks ago without having any answer.

I've a problem with Github Action that I _presume_ could be related to the Runner, but obviously I cannot be sure of it.

My company has released an Ansible Role (https://github.com/bmeme/ansible-role-percona-xtradb-cluster) to install a Percona XtraDB Cluster. We add to this role a molecule test that runs without problems on Ubuntu 22.04 and Mac Os. If I try to run the same test on GitHub Action, when role try to start MySQL service, the job breaks with this error:

```
  TASK [bmeme.percona_xtradb_cluster : Ensure Mysql service is temporary started] ***
  fatal: [test-cluster-02]: FAILED! => {"changed": false, "msg": "Unable to start service mysql: Job for mysql.service failed because the control process exited with error code. See \"systemctl status mysql.service\" and \"journalctl -xe\" for details.\n"}
  fatal: [test-cluster-03]: FAILED! => {"changed": false, "msg": "Unable to start service mysql: Job for mysql.service failed because the control process exited with error code. See \"systemctl status mysql.service\" and \"journalctl -xe\" for details.\n"}
```

This is quite annoying because, at this stage, I cannot add a CI to my work.
You can see the complete action log here: https://github.com/bmeme/ansible-role-percona-xtradb-cluster/actions/runs/3600859841/jobs/6065992549.

My molecule.yml (@see [here](https://github.com/bmeme/ansible-role-percona-xtradb-cluster/blob/ext/introduce_ci/molecule/default/molecule.yml)):

```
---
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: test-cluster-01 
    image: "bmeme/docker-ansible-${MOLECULE_DISTRO:-centos:7.9}"
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
  - name: test-cluster-02 
    image: "bmeme/docker-ansible-${MOLECULE_DISTRO:-centos:7.9}"
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
  - name: test-cluster-03 
    image: "bmeme/docker-ansible-${MOLECULE_DISTRO:-centos:7.9}"
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
```

And this is my action (@see [here](https://github.com/bmeme/ansible-role-percona-xtradb-cluster/blob/ext/introduce_ci/.github/workflows/ci.yml))

```
name: Ansible Role Percona XraDB Cluster
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'bmeme.percona_xtradb_cluster'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'bmeme.percona_xtradb_cluster'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos:7.9
          - ol:8.6
    
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'bmeme.percona_xtradb_cluster'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker]==4.0.3 docker

      - name: Run Molecule tests 
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
```

I don't have this problem with other kind of services.
I'm quite new with Actions then probably there are something I don't know. If you need something else to drive me to the right path, let me know.

Thanks in advance.
