### DISCUSSION TITLE
Wondering why the github checkout task is using wrong commit for PR triggered workflow

### DISCUSSION THREAD

**Discussion by johnpazzly** [community/community#40659] [Actions]
`###` Select Topic Area

Question

### Body

Here is my workflow trigger which is intended to run on PRs and check-ins to my develop, and master branch.

```
on:
  push:
    branches: [develop, master]
  pull_request_target:
    types: [opened, reopened, synchronize]
```

My Checkout task:

```
jobs:
  Test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3 

```

When I open a PR against the develop branch, I expect the action to use the PR source branch for the build, instead it uses the latest version of the develop branch (and that doesn't include PR code). I can see this in the checkout logs. Am I doing something wrong with my logic?

Thank you!
