### DISCUSSION TITLE
Output matrix variable when it's an array

### DISCUSSION THREAD

**Discussion by karljohns0n** [community/community#40668] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm migrating a bash script to Github actions that uses a few variables and I have issue with a specific one that is an array. Is it possible to output an array from a variable in Action f?

Using bash, this works just fine:

```bash
OS=rockylinux VERSION=8 OPT=() OPT+=(--with=modsecurity) OPT+=(--with=pagespeed)
OS=rockylinux VERSION=9 OPT=() OPT+=(--with=modsecurity)

mock --buildsrpm "${OPT[@]}"
```

Now trying to convert this to Github Action, I cannot find a way to output ${OPT[@]} without error. I tried;

```yaml
    strategy: 
      matrix:
        include:
          - VERSION: 8
            OS: rockylinux
            OPT: [--with=modsecurity, --with=pagespeed]
          - VERSION: 9
            OS: rockylinux
            OPT: [--with=modsecurity] 

mock --buildsrpm "${{ matrix.OPT[*] }}"
```

but this gives me `Failed to parse: unexpected token "*" while parsing variable access`. Any idea?

Thanks,

**Comment by ossanna16** [comment]
Hi there @karljohns0n and welcome to our community! Thank you for asking a great question 🙂
While you are waiting for a reply to your question, here are a few things you can do:

To get started, introduce yourself in our [official introduction thread](https://github.com/orgs/community/discussions/23204)
To connect with other new users, check out this Discussion to [Meet Your GitHub Community Team](https://github.com/orgs/community/discussions/28776), further your GitHub knowledge by working through our [GitHub Skill 🆙 exercises](https://github.com/orgs/community/discussions/32121), and participate in our [weekly Fun Friday chats](https://github.com/orgs/community/discussions/30912)

**Comment by airtower-luna** [comment, marked as answer]
No, matrix variables are only available as strings. You *could* write some structured data (e.g. JSON) into the string and parse into an array, but in the given case I think it's easiest if you just write a string to include in the command:

```yaml
    strategy: 
      matrix:
        include:
          - VERSION: 8
            OS: rockylinux
            OPT: --with=modsecurity --with=pagespeed
          - VERSION: 9
            OS: rockylinux
            OPT: --with=modsecurity
    steps:
      # ...
      - run: mock --buildsrpm ${{ matrix.OPT }}
```

Mind that the Actions `${{ ... }}` syntax is substituted *literally* before the shell ever sees it, so your string needs to include any required escapes.

**Reply by karljohns0n** [reply]
I tried a lot of things using [act](https://github.com/nektos/act) but never the combinaison of both variable and output without the double quotes.. it works now thank you!

**Comment by ChristopherHX** [comment]
- `${{ join(matrix.OPT, ' ') }}`, fast and unsafe with spaces
- ```yaml
  run: |
    #... convert json array in $OPT to an bash array
  env:
    OPT: ${{ tojson(matrix.OPT) }}
  ```

> No, matrix variables are only available as strings

That would be new to me

**Reply by airtower-luna** [reply]
True, that was clumsy phrasing on my part. The point is that you can't inject them into the shell of the `run` step as a (shell) array without using a string format and parsing in between. Within Actions syntax is a different matter.

**Reply by karljohns0n** [reply]
Thanks for the reply. I tried using `to/fromjson()` without success. I'll try your way!

**Reply by ChristopherHX** [reply]
Using bash for complex things is insane, @airtower-luna answer is the simplest variant to avoid arrays altogether.

To confuse everyone reading this, here a pure bash array created by action expressions as long no line contains `EOF` as the only word.
```yaml
on: push
jobs:
  _:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - args:
          - test with space
          - another test
          - |
              my multiline input
              Help Me
              True tragic              
    steps:
    - run: |
        args=(${{ matrix.args[0] && format('"$(cat << "EOF"
        {0}
        EOF
        )"', join(matrix.args, '
        EOF
        )" "$(cat << "EOF"
        ')) || ''}})
        # You have your bash array args from the matrix key
        echo "${args[@]}"
```
_I will add this to my actions wiki_
