### DISCUSSION TITLE
Debug error for repos in GIT

### DISCUSSION THREAD

**Discussion by aigini82** [community/community#40758] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

General

### Body

Hi,

This is the content of my configuration file to gitfs :

```
ta-suma-qa:/etc/salt/master.d # cat gitfs.conf
# Configure gitfs
fileserver_backend:
  - roots
  - gitfs

gitfs_remotes:
  - ssh://git@ta-git.basf.net:2222/admnavaneai/suma-gitfs-salt.git:
    - pubkey: /var/lib/salt/.ssh/ta-git.basf.net.pub
    - privkey: /var/lib/salt/.ssh/ta-git.basf.net
    - name: default
    - base: cis
    - ref_types:
      - branch
  - ssh://git@ta-git.basf.net:2222/admnavaneai/suma-nagios-plugins.git:
    - pubkey: /var/lib/salt/.ssh/ta-git.basf.net.pub
    - privkey: /var/lib/salt/.ssh/ta-git.basf.net
    - name: nagios-plugins
    - mountpoint: salt://nagios/files/plugins
    - base: main
    - ref_types:
      - branch
  - ssh://git@ta-git.basf.net:2222/admnavaneai/openscap.git:
    - pubkey: /var/lib/salt/.ssh/ta-git.basf.net.pub
    - privkey: /var/lib/salt/.ssh/ta-git.basf.net
    - name: openscap
    - mountpoint: salt://oscap/files
    - base: sles12
    - ref_types:
      - branch
ta-suma-qa:/etc/salt/master.d #
```

I worked with suma-gitfs-salt.git and openscap.git repos a few weeks ago, without any accessibility problems. (I was able to successfully perform the changes needed to the needed servers).

However for the suma-gitfs-salt repo (which I worked with last week), I get the error below when I try to execute the changes needed to the server : 

```
ta-suma-qa:/etc/salt/master.d # salt-run fileserver.update
[ERROR   ] Error occurred fetching gitfs remote 'ssh://git@ta-git.basf.net:2222/admnavaneai/suma-nagios-plugins.git': Gitea: Unauthorized
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1870, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib64/python3.6/site-packages/pygit2/remote.py", line 409, in fetch
    check_error(err)
  File "/usr/lib64/python3.6/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Gitea: Unauthorized

True
ta-suma-qa:/etc/salt/master.d #
```

These were the steps that I performed to clone that repo into my local server : 

```
git clone https://ta-git.basf.net/admnavaneai/suma-nagios-plugins.git
cd `.\suma-nagios-plugins\`
git remote add upstream https://ta-git.basf.net/ta/suma-nagios-plugins.git
```

P/S : All these repositories were actually forked from the main repository which are : 

```
https://ta-git.basf.net/ta/suma-gitfs-salt.git
https://ta-git.basf.net/ta/suma-nagios-plugins.git
https://ta-git.basf.net/ta/openscap.git
```

I am not sure if running the remote add upstream command caused the permission problem? Else please help pinpoint how to start debugging this problem?
