### DISCUSSION TITLE
Storing date into GITHUB_ENV but the result has an unwanted pair of parenthesis

### DISCUSSION THREAD

**Discussion by universallyleo** [community/community#40761] [Actions] [answered]
### Select Topic Area

Product Feedback

### Body

I am trying to use the following github action that runs on every push.
After checking out the repo, it will get the current date and store it in the `GITHUB_ENV`.  
Suppose today's date is 2022-12-04.  Then in the next step, it should first rename `.src/data.json`  to `.src/data_2022-12-04.json`
I will then run a python
But when the action run, the output log says it is moved to `.src/data_{2022-12-04}.json`.  Does anyone know why this happens?

Also, I found out to use of  `$(date +'%Y-%m-%d')` from stackoverflow, but could not found out an explanation of this syntax, could anyone also shed some light on how to interpret this line (specfically, what the dollar sign does, and where the date comes from some GitHub action special command or some linux command?)

```yaml
name: On Push update JSON

on: [push]

jobs:
  modify-json:
    name: move json file
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo for use
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "today={$(date +'%Y-%m-%d')}" >> $GITHUB_ENV

      - name: Copy original json
        run: mv ./src/data.json ./src/data_${{ env.today }}.json

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Github Action auto update on ${{ env.today }}
```
