### DISCUSSION TITLE
GitHub Action from repo a clone repo b

### DISCUSSION THREAD

**Discussion by LozanoMatheus** [community/community#40792] [Actions]
### Select Topic Area

Question

### Body

Hello there,

I have my code in a private repo (A), and some libs/modules hosted in other private repos (B, C, D, etc). The only way I found to make this work is by adding the SSH private key on each step that needs to access repo B (tbh, this doesn't feel that safe)

```yaml
      - name: Get libs
        id: libs
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          ...
```

It's similar to this person's case:
https://stackoverflow.com/a/70283191/2868547

It's quite annoying to keep repeating the same thing since I've quite a few steps that need to access the other private repos. Is there a better/easy/safer way to do that?
