### DISCUSSION TITLE
How to skip CI when there're only docs updated without any codes changed

### DISCUSSION THREAD

**Discussion by gy95** [community/community#40795] [Actions]
### Select Topic Area

Product Feedback

### Body

I want to skip CI if there're only docs updated without any codes changed. So i add the below two yamls by following https://docs.github.com/cn/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks 

main.yaml
```
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '**/OWNERS'
      - '**/MAINTAINERS'
jobs:
  lint:
    runs-on: ubuntu-22.04
    name: ci
    steps:
      - run: hack/lint.sh      ----do the real actual CI checks
```

main-for-doc.yaml
```
on:
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'
      - '**/OWNERS'
      - '**/MAINTAINERS'
jobs:
  lint:
    runs-on: ubuntu-22.04
    name: ci
    steps:
      - run: 'echo "only docs modified, no need to trigger CI"'      ---just always pass it
```

if a PR only contains docs changed, e.g. Readme.md, without other source codes changed. it will only run the second CI.
if a PR only contains source codes changed, without any docs updated, it will trigger the first CI
But if a PR contains both docs and codes changed, it will  trigger the both CIs, so the window will display the two CI checks.

How to fix this problem? 
I want to skip the actual CI if there's only docs changed. And if both docs and codes are changed, I don't want to run the both above CIs.
 
Thanks in advance
