### DISCUSSION TITLE
Having trouble with createOrUpdateRepoSecret

### DISCUSSION THREAD

**Discussion by Landoooooo** [community/community#40877] [Apps, API and Webhooks]
### Select Topic Area

Bug

### Body

I'm pretty confident I'm sending the correct information as I get a status of `201`, but when my action actually runs it complains about the secret missing. Also if I go in and manually add the secret, it works perfectly fine.

```
await octokit.actions.createOrUpdateRepoSecret({
      owner: ORG_NAME,
      repo: repoName,
      secret_name: "HEROKU_EMAIL",
      encrypted_value: await encryptValue(process.env.HEROKU_EMAIL, latestKey),
      key_id: publicKeyId,
});
```
The `encryptValue` contains the following:
```
export const encryptValue = async (value: string, key: string) => {
  await sodium.ready;
  // Convert the message and key to Uint8Array's (Buffer implements that interface)
  const messageBytes = Buffer.from(value);
  const keyBytes = Buffer.from(key, "base64");

  // Encrypt using LibSodium.
  const encryptedBytes = sodium.crypto_box_seal(messageBytes, keyBytes);

  // Base64 the encrypted secret
  const encrypted = Buffer.from(encryptedBytes).toString("base64");

  return encrypted;
};
```

Just incase anyone wanted to see the action that was being run:
```
# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      ### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your Heroku app.

          # The email address associated with your Heroku account.
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com
          email: ${{ secrets.HEROKU_EMAIL }}

          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # (Optional, default: "./")
          # Dockerfile directory.
          # For example, if you have a Dockerfile in the root of your project, leave it as follows:
          dockerfile_directory: ./

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile.production

          # (Optional, default: "")
          # Additional options of docker build command.
          docker_options: "--no-cache"

          # (Optional, default: "web")
          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          # For more information look at https://devcenter.heroku.com/articles/process-model
          process_type: web
### ⬆ IMPORTANT PART ⬆ ###
```

Any assistance with this would be greatly appreciated!
