### DISCUSSION TITLE
Support Deno as a Action Runtime

### DISCUSSION THREAD

**Discussion by anatawa12** [community/community#40875] [Actions]
### Select Topic Area

Product Feedback

### Body

I think Deno is better than node in some reasons:
- Deno is currently longer lifecycle than node. Since deno 1.0.0 released in 2020-05-14, There is almost no breaking changes for stable features.
On the other hand, since node released v14 in 2020-04-22, there're 2 LTS release (v14 and v16).
Node version bumping is a breaking change in action so this force action users to upgrade action only for this reason.
(e.g. actions/checkout@v2 -> actions/checkout@v3).
This is significantly cumbersome.
- Deno has permission system. 
This allow us run action safely (if the action is not depends on external commands).
I think it's better to have permissions section in `action.yml` and pass permission settings based on the settings.
- Deno has system to download dependencies.
For actions with node.js, currently I need to include node_modules directory OR bundle js files into one.
This make releasing action a little complicated. 
We need to bundle and push on release or sync bundled js and source js every time.
With Deno, we can reduce this step.

**Comment by na-jakobs** [comment]
deno would be an amazing addition to the GitHub Actions ecosystem 🦕 🙏

**Comment by Hajime-san** [comment]
I hope this!
```yaml
name: 'Hello Deno action'
inputs:
  allow-read:
    description: 'permission for reading directory'
    required: true
...
runs:
  using: 'deno@v1.x'
  main: 'mod.ts'
```
