### DISCUSSION TITLE
Is it possible to define job level variables

### DISCUSSION THREAD

**Discussion by taojintianxia** [community/community#40897] [Actions]
### Select Topic Area

Question

### Body

I treid following config but failed.

```yaml
env:
  RUNS_ON: ubuntu-latest

jobs:
  build-it-image:
    name: Build IT image
    runs-on: ${{ env.RUNS_ON }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
```

with this error : 
```
[Invalid workflow file: .github/workflows/e2e.yml#L66](https://github.com/taojintianxia/shardingsphere/actions/runs/3627297777/workflow)
The workflow is not valid. .github/workflows/e2e.yml (Line: 66, Col: 14): Unrecognized named-value: 'env'. Located at position 1 within expression: env.RUNS_ON .github/workflows/e2e.yml (Line: 97, Col: 14): Unrecognized named-value: 'env'. Located at position 1 within expression: env.RUNS_ON
```

I'm not sure if this kind of variables work in job level...
