### DISCUSSION TITLE
Pushing changes to branch with policies using permissions contents write

### DISCUSSION THREAD

**Discussion by rajsite** [community/community#40971] [Actions]
### Select Topic Area

Question

### Body

I have a workflow where I'd like to use [workflow permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview) instead of a Personal Access Token for a step that will result in pushing changes using git to the repo.

I've configured the workflow with `content: write` like follows:
```yml
permissions:
  contents: write
  pages: write
  id-token: write
```

And I rely on the checkout action to configure authenticated git commands (i.e. I do not set `persist-credentials: false`):
```yml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0 # Required for changelog detection
```

When my script attempts to push it is restricted by branch policies:
```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 3 of 3 required status checks are expected. Waiting on code owner review from ***, ***, ***, ***, and/or ***. 
```

- How can I make it so that the `GITHUB_TOKEN` created with permissions `contents: write` can bypass the branch policies?
- Is there an actor represented by the `GITHUB_TOKEN` that I can configure for the `Allow specified actors to bypass required pull requests` setting in branch protection rules?
