### DISCUSSION TITLE
Dependabot for Composite Actions

### DISCUSSION THREAD

**Discussion by olix0r** [community/community#41025] [Code Security]
### Select Topic Area

Product Feedback

### Body

I have a composite action that does something like:

```yaml
runs:
  using: composite
  steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - ...
```

As far as I can tell, there's no way to configure dependabot to update the composed action versions (i.e. `actions/checkout`, in this case).

Am I missing something? If not, is there a better place to open a feature request for dependabot?
