### DISCUSSION TITLE
Dynamic values for input type choice

### DISCUSSION THREAD

**Discussion by adcoder007** [community/community#41138] [Actions]
### Select Topic Area

Product Feedback

### Body

I was following this  [blog](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/#:~:text=Who%20to%20greet-,options%3A,-%2D%20monalisa%0A%20%20%20%20%20%20%20%20%2D)

For input type choice can we provide dynamic values like populating all available tag for that repository?
For example for below code block can I populate all available tags for the repo as options value?
```
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
```
