### DISCUSSION TITLE
Environment level secrets are not being injected

### DISCUSSION THREAD

**Discussion by nodesocket** [community/community#41144] [Actions]
### Select Topic Area

Question

### Body

Using GitHub environments and setting a single secret `HSM_IP` which varies depending on the environment `dev`, `stage`, `production`:

![Screenshot 2022-12-08 at 4 35 28 PM](https://user-images.githubusercontent.com/523312/206585342-fadaf1e8-7295-407f-965a-32f4477826c7.png)

Then set the environment in the GitHub action like:

```yaml
name: API Docker build dev

on:
  push:
    paths:
      - 'api/**'
    branches:
      - dev

defaults:
  run:
    working-directory: ./api

jobs:
  docker-hub:
    name: API Docker build dev (Docker Hub)
    environment: dev
    runs-on: ubuntu-latest
    env:
      HSM_IP: ${{ secrets.HSM_IP }}
...
```

However, the GitHub action is NOT pulling in the environment level secret `HSM_IP` even though it is set in `dev` environment in GitHub. Ideas?
