### DISCUSSION TITLE
Job takes time more than timeout-minutes

### DISCUSSION THREAD

**Discussion by ces-truongvu** [community/community#41169] [Actions]
### Select Topic Area

Product Feedback

### Body

The usage report shows that some of our pipeline jobs taking longer time than the `timeout-minutes` configuration.
It happens monthly and we have to buy more spending time. Can you give us some advice to fix the issue? 

Here is my YAML content.

```yml
jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    ...
```

**Comment by khashayarghafouri** [comment]
If a job exceeds `timeout-minutes`, GitHub cancels it. Log message: `has exceeded the maximum execution time`.

Common confusions:
- **Step vs job timeout** — step timeouts only cap that step; the job timeout caps total runtime.
- **Queued jobs** — waiting for a runner is not a timeout.
- **Self-hosted runners** — hung processes may ignore cancellation unless scripts handle signals.

Template:
```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - timeout-minutes: 5
        run: your-command
```

Raise the job timeout or optimize the slow step if the work legitimately needs more time.
