### DISCUSSION TITLE
Can the called workflow get to know which branch was used for call?

### DISCUSSION THREAD

**Discussion by nikandfor** [community/community#41189] [Actions]
### Select Topic Area

Product Feedback

### Body

I have reusable workflow which uses some script from its repo to do the job. It needs to clone the repo to call the script. I can clone the main branch, but that doesn't work when I'm testing a new feature (that is not merged yet) or want some another version.

Another solution that was found is to provide needed reference manually by the caller. So the caller workflow looks like
```
jobs:
  call_some_job:
    uses: workflow_org/workflow_repo/.github/workflows/some_workflow.yml@workflow/reference
    with:
      workRef: workflow/reference
```

Calling workflow looks like
```
on:
  workflow_call:
    inputs:
      workRef:
        required: false
        type: string
        default: main

jobs:
  called_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'workflow_org/workflow_repo'
          ref: ${{inputs.workRef}}

      - uses: actions/checkout@v3
        with:
          path: path_to_caller_repo/${{ github.event.repository.name }}
          fetch-depth: 100

      - run: ./do the job
```

That works, but is quite cumbersome. Is there a way for called workflow to know its reference it was called by? So instead of manually passed `${{ inputs.workRef }}` to use `${{ workflow.ref }}`. Or maybe there is a better practice than checking out called workflow repo or even both repos?

And if there is no a better solution, can you consider adding such a workflow context variable? Thanks!

**Comment by khashayarghafouri** [comment]
Yes — reusable workflows receive caller context through `github` context and workflow inputs, but not as a built-in callee-side branch field.

**Reliable approach:** pass the branch explicitly via `with:` inputs from the caller:

```yaml
# caller
jobs:
  call:
    uses: org/repo/.github/workflows/reusable.yml@main
    with:
      source_branch: ${{ github.ref_name }}
```

```yaml
# reusable
on:
  workflow_call:
    inputs:
      source_branch:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Caller branch ${{ inputs.source_branch }}"
```

Do not rely on `github.ref` inside the callee for caller branch detection — it refers to the workflow repository default branch context.
