### DISCUSSION TITLE
Differentiate between direct push and merge

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#41196] [Actions]
### Select Topic Area

Product Feedback

### Body

I want to run a workflow on 

```yaml
on:
  push:
    branches:
      - myBranch
```

I want it however to run only when someone performs a `git push -u origin myBranch` and not when there is a PR merged into `myBranch`. Is there a way to do so?
