### DISCUSSION TITLE
Unable to print the json formatted github context

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#41203] [Actions]
### Select Topic Area

Question

### Body

I just want to print out the `github.event` context in a GitHub Actions step, so I am doing the following

```yaml
      - name: check context
        shell: bash
        run: echo ${{ toJSON(github.event) }}
```

However this fails as follows:

```
/home/runner/work/_temp/hd73999-5309-44cf-9218-9e2e3805d525.sh: line 2: after:: command not found
Error: Process completed with exit code 127.
```

(although the `github.event` **DOES** get printed before the error.

Why is that?

I am using the `toJSON` function because if I don't all that gets printed is:

```
Run echo Object
Object
```
