### DISCUSSION TITLE
Pushed at date has different format when Action is triggered from Push or manually

### DISCUSSION THREAD

**Discussion by SanctusAnimus** [community/community#41400] [Actions]
### Select Topic Area

Bug

### Body

So i have this little action to write version number as a date in a string, to a repo - either on push or when triggered manually. Discusions found in google suggested usage of `pushed_at` - but it's format is different on `push` and for `workflow_dispatch`.

Action code:
```
on:
  push:
    paths:
      - 'game/**'
      - 'content/**'
    branches: 
      - master
  workflow_dispatch:
  
jobs:
  stamp_version:
    name: Stamp Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Write Date
      run: echo 'GAME_VERSION = "${{ github.event.repository.pushed_at }}"' > game/scripts/vscripts/_VERSION.lua
    - name: Commit report
      run: |
        git config --global user.name '<name>'
        git config --global user.email '<mail>'
        git add game/scripts/vscripts/_VERSION.lua
        git commit -am "[bot] Version stamp"
        git push
```

When triggered by pushing a commit, resulting string contains timestamp, like this:
`GAME_VERSION = "1670755579"`
But when triggered manually, it becomes an ISO datetime instead:
`GAME_VERSION = "2022-12-11T10:51:09Z"`

I tried `updated_at`, but it doesn't change at all between commits.
Is there a way to eliminate discrepancy, or maybe some other date i can use?
