### DISCUSSION TITLE
How to properly do set env var if

### DISCUSSION THREAD

**Discussion by thatrandomperson5** [community/community#41437] [Actions] [answered]
### Select Topic Area

Question

### Body

This is my current action:
```yaml
  - env:
      arg: "-a"
    if: ${{ inputs.auto != 'false' }}
  - env:
      arg: ""
    if: ${{ inputs.auto == 'false' }}

  - run: python -m AutoContentsGen ${{ inputs.file }} $arg
    shell: bash
```
Actions keeps on complaining, will this work? If not how do i fix

**Comment by airtower-luna** [comment, marked as answer]
That definitely won't work, each step must have a `run` or `uses`. `env` in a step affects only that step, the `env` only steps you have there wouldn't affect anything if the parser would allow them.

I assume you're trying to [set an environment variable](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) for use in the `run` step at the end?  In that case you need to write the variable to file `GITHUB_ENV` points at. For example:

```yaml
  - run: echo "ARG=-a" >>${GITHUB_ENV}
    if: ${{ inputs.auto != 'false' }}
  - run: echo "ARG=" >>${GITHUB_ENV}
    if: ${{ inputs.auto == 'false' }}
  - run: python -m AutoContentsGen ${{ inputs.file }} $ARG
    shell: bash
```

You don't really need the `if: ${{ inputs.auto == 'false' }}` case though, an unset variable will just be ignored by the shell, so you can simply remove it.

A little warning: The last step might break in interesting ways if `inputs.file` contains any character that has special meaning to the shell (e.g. a space, quotes, and many more). That's because Actions syntax (`${{ ... }}`) is substituted *literally* before passing your command to the shell. It's better to pass it as an environment variable, too, with proper quoting:

```yaml
  - run: python -m AutoContentsGen "$FILE" $ARG
    shell: bash
    env:
      FILE: ${{ inputs.file }}
```
