### DISCUSSION TITLE
actions/setup-dotnet@v3 throwing error on Windows

### DISCUSSION THREAD

**Discussion by srivastava-prashant** [community/community#41474] [Actions]
### Select Topic Area

Question

### Body

I have my own build box (Windows) which has self hosted runner. When I try to run below step in GitHub action then it throws error.

```
      - name: Setup dotnet on runner
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.X'
```

**Error:-** 

New-Object : The value supplied is not valid, or the property is read-only. Change the value, and then try again.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/100225397/206986060-e5d3ea01-dd04-47e4-a729-e3218f284834.png">
