### DISCUSSION TITLE
Filter action when the author is dependabot

### DISCUSSION THREAD

**Discussion by Khaaz** [community/community#41515] [Actions] [answered]
### Select Topic Area

Question

### Body

I am trying to RUN or NOT RUN an action if the author is dependabot.

In my job I use:

```yaml
name: Auto-merge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
```

My issue is:

it works as intended when the PR is created (eg: the `github.actor` is dependabot), but when I update it by adding / removing a label, the `github.actor` is myself.
Is that the expected behaviour? What am i not understanding?
