### DISCUSSION TITLE
Visual bug in "textarea" and "dropdown" YAML field types

### DISCUSSION THREAD

**Discussion by stehf** [community/community#41664] [Projects and Issues]
### Select Topic Area

Bug

### Body

👋 I'm building a YAML Issue template and noticed a visual bug when previewing my branch as a blob (`https://github.com/github/{repo}/blob/{branch}/{file-path}`)

`textarea` and `dropdown` fields display the description below the input section, instead of on top like the live Issue templates. Other field types like `checkboxes` display the description in the correct place, below the label.

Screenshot of the bug:
<img width="418" alt="Screenshot 2022-12-13 at 3 41 06 PM" src="https://user-images.githubusercontent.com/10836668/207439144-c1e4751a-5b06-4465-8429-0c20e4f932ef.png">

.yml:
```
  -type: textarea
    id: data_flow_diagram
    attributes:
      label: Data Flow Diagram (DFD)
      description: Please provide a visual diagram...
      placeholder: <Link to DFD>
    validations:
      required: true
```
