### DISCUSSION TITLE
Run a command on the GitHub-hosted runner VM before service containers are created

### DISCUSSION THREAD

**Discussion by arg** [community/community#41739] [Actions]
### Select Topic Area

Question

### Body

Sorry if this is a duplicate.

Our CI environment depends on a specific software that requires some `sysctl` tuning on the host system. We run that software in a service container, but since service containers are initialized BEFORE we can tune `sysctl` with

```yml
- name: Tune the environment
  run: |
    sudo sysctl -w fs.file-max=262144
    sudo sysctl -w vm.max_map_count=262144
```
it results in having stability issues. Is there a way to execute the above command before GHA creates service containers?
