### DISCUSSION TITLE
Can't access npm http-server served app on localhost from github action

### DISCUSSION THREAD

**Discussion by DzmVasileusky** [community/community#41741] [Actions]
### Select Topic Area

Question

### Body

Story:
I am trying to setup srotybook test-runner on github actions like here [https://storybook.js.org/docs/angular/writing-tests/test-runner#run-against-non-deployed-storybooks](url)
Everything is working until trying to access a website on localhost served by `http-server`.

*.yml
```
name: 'Storybook Tests'
on:
  pull_request:
    branches:
      - proto
      - develop
      - staging
      - master
jobs:
  filter-ui-kit:
    runs-on: ubuntu-latest
    name: Filter Ui kit
    outputs:
      filteroutput: ${{ steps.filteruikit.outputs.filteroutput }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: libs/ui-kit/**

      - name: Run step if any file(s) in the docs folder change
        id: filteruikit
        run: |
          if [ ${{ steps.changed-files-specific.outputs.any_changed }} == true ]; then
            echo "::set-output name=filteroutput::true"
          fi
          if [ ${{ steps.changed-files-specific.outputs.any_changed }} != true ]; then
            echo "::set-output name=filteroutput::false"
          fi

  test:
    needs: [filter-ui-kit]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: needs.filter-ui-kit.outputs.filteroutput == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.x'
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npx nx run ui-kit:build-storybook
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server dist/storybook/ui-kit --port 4400" \
            "npx wait-on tcp:4400 && cd libs/ui-kit && npx test-storybook -c ./.storybook --url=http://127.0.0.1:4400 --stories-json"

```

`npx wait-on tcp:4400` is passing then test-runner fails with `It seems that your Storybook instance is not running at: [http://127.0.0.1:4400](http://127.0.0.1:4400./)`

I have tried to do `npx wait-on http://127.0.0.1:4400` and it failed on wait-on step with endless attempts to fetch an app
```
Run npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
  npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
    "npx http-server dist/storybook/ui-kit --port 4400" \
    "npx wait-on http://127.0.0.1:4400 && cd libs/ui-kit && npx test-storybook -c ./.storybook --url=http://127.0.0.1:4400 --stories-json"
  shell: /usr/bin/bash -e {0}
[SB] Starting up http-server, serving dist/storybook/ui-kit
[SB] 
[SB] http-server version: 14.1.1
[SB] 
[SB] http-server settings: 
[SB] CORS: disabled
[SB] Cache: 3600 seconds
[SB] Connection Timeout: 120 seconds
[SB] Directory Listings: visible
[SB] AutoIndex: visible
[SB] Serve GZIP Files: false
[SB] Serve Brotli Files: false
[SB] Default File Extension: none
[SB] 
[SB] Available on:
[SB]   http://127.0.0.1:4400
[SB]   http://10.1.1.68:4400
[SB] Hit CTRL-C to stop the server
[SB] 
[SB] [2022-12-13T17:31:07.521Z]  "HEAD /" "axios/0.21.4"
[SB] (node:4845) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[SB] (Use `node --trace-deprecation ...` to show where the warning was created)
[SB] [2022-12-13T17:31:07.767Z]  "HEAD /" "axios/0.21.4"
[SB] [2022-12-13T17:31:07.768Z]  "HEAD /" Error (404): "Not found"
```

So it seems that server is running on port 4400 but I am not accessing the correct domain besides it says it is available on `http://127.0.0.1:4400`
