### DISCUSSION TITLE
Github actions run for latest commit

### DISCUSSION THREAD

**Discussion by Codebooth-2021** [community/community#41799] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi folks,

I want to run workflow for latest commit and discard old commits workflows. For example there are four commits on a branch and first workflow for the first commit is still executing, github will execute workflow for all commits one by one but I want that after execution of first commit github should discard second and third commet workflow and execute fourth or latest workflow.

**Comment by spenserblack** [comment]
Is this roughly what you mean?
```yaml
# .github/workflows/my-workflow.yml
name: My Workflow

on:
  push:
    branches: ["main"]

# Allow one concurrent run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # stop old runs, start the new run
```

More info: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
