### DISCUSSION TITLE
Actions for setting up browsers

### DISCUSSION THREAD

**Discussion by joneff** [community/community#41823] [Actions]
### Select Topic Area

Product Feedback

### Body

I know, I know -- there is an action for setting up chrome and firefox... and it has not been updated in a while.

The community needs a github made action to setup browsers, the way there are actions for setting up node, python, dot-net etc. It could be one action per browser, or one action for all browsers.

```yml
# One action to rule them all
- name: Setup browsers
  uses: actions/setup-browser
  with:
    firefox: 81
    chrome: 81
    geckodriver: x.y.z
    chromedriver: a.b.c

# Per browser
- name: Setup BROWSER_NAME
  uses: actions/setup-BROWSER_NAME
  with:
    version: 81
```

I am not big for names so the `with` part can be augmented to match the rest of the `setup-` actions like using `firefox-verson` or `chromedrive-vesion` etc.

Why? Two words -- image tests.

Longer explanation: everynow and then, there is a change in firefox that triggers new images during a build. However, not all runners have the same version of firefox installed so you can imagine the amount of tests produced...
