### DISCUSSION TITLE
How to use cache from docker registry in github action with docker buildx bake?

### DISCUSSION THREAD

**Discussion by oerp-odoo** [community/community#41921] [Actions]
### Body

Any approach I took, github actions just builds images from scratch, ignoring any caching specified or pulled similar images (to maybe reuse some layers?)

I have this `docker-bake.hcl` file:

```
variable "PROJECT_DOCKERFILE" {
  default = "project.Dockerfile"
}
variable "MONODOO_TAG" {
  default = "16.0"
}
variable "PROJECT_TAG" {
  default = "16.0"
}


target "monodoo" {
  dockerfile = "src/monodoo/Dockerfile"
  contexts = {
    monodoo-src = "src/monodoo"
  }
  tags = ["ghcr.io/myorg/monodoo:${MONODOO_TAG}"]
}

target "_all" {
  contexts = {
    monodoo = "target:monodoo",
    extra-src = "src/extra"
  }
}

target "demo" {
  inherits = ["_all"]
  contexts = {
    project-src = "src/projects/demo"
  }
  dockerfile = "${PROJECT_DOCKERFILE}"
  tags = ["ghcr.io/myorg/demo:${PROJECT_TAG}"]
}
```

It basically consists of two images, `monodoo` and `demo`. `monodoo` acts as a base image and `demo` as more specific one.

In my github actions workflow, I tried these approaches:

1.
```yml

      - name: Build Demo project
        run: |
          docker buildx bake --load \
          --set=*.cache-from=type=registry,ref=ghcr.io/myorg/demo:16.0 demo
```

2.
```yml

      - name: Build Demo project
        run: |
          docker pull ghcr.io/myorg/demo:16.0
          docker buildx bake demo
```

3. Also tried bake (with caching specified): https://github.com/docker/bake-action

None of these approaches seem to change anything. It just builds image from scratch all the time (which is quite long).

I even tried to just build image for `monodoo` (base one) and in github actions I can see this:

```
#10 DONE 0.5s
#11 [stage-0  1/15] FROM docker.io/library/ubuntu@sha256:a8fe6fd30333dc60fc5306982a7c51385c2091af1e0ee887166b40a905691fd0
#11 DONE 0.0s
#12 [context monodoo-src] load from client
#12 DONE 0.0s
#13 [internal] load build context
#13 DONE 0.0s
#14 importing cache manifest from ghcr.io/myorg/monodoo:16.0
#14 DONE 0.0s
#11 [stage-0  1/15] FROM docker.io/library/ubuntu@sha256:a8fe6fd30333dc60fc5306982a7c51385c2091af1e0ee887166b40a905691fd0
#11 resolve docker.io/library/ubuntu@sha256:a8fe6fd30333dc60fc5306982a7c51385c2091af1e0ee887166b40a905691fd0 done
#11 sha256:a8fe6fd30333dc60fc5306982a7c51385c2091af1e0ee887166b40a905691fd0 529B / 529B done
#11 sha256:216c552ea5ba7b0e3f6e33624e129981c39996021403518019d19b8843c27cbc 1.46kB / 1.46kB done
```

It even says `#14 importing cache manifest from ghcr.io/myorg/monodoo:16.0`
