### DISCUSSION TITLE
Test application with mongodb service

### DISCUSSION THREAD

**Discussion by Nuckerr** [community/community#41972] [Actions] [answered]
### Select Topic Area

Question

### Body

I have this action:
```yaml
name: Build Project
on: [ push, pull_request ]

jobs:
  test:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
      fail-fast: true
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: test
    steps:
      - uses: actions/checkout@v2
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: chmod +x gradlew && ./gradlew test --stacktrace
        env:
          MONGO_URI: mongodb://root:test@mongo
          MONGO_DB: learnspigot
          UDEMY_CLIENT_ID: ${{ secrets.UdemyClientId }}
          UDEMY_BEARER: ${{ secrets.UdemyBearer }}
```
This is to test my project, however when my mongo tests fail because they time out. These work fine in other test environments, I have obviously configured something wrong in this. Any ideas what?
