### DISCUSSION TITLE
If a downstream job 'needs' a matrix job, will it be called once for each invocation of the upstream matrix job?

### DISCUSSION THREAD

**Discussion by anentropic** [community/community#42010] [Actions] [answered]
### Select Topic Area

Question

### Body

If a downstream job depends on a matrix job, will it be called once for each invocation of the upstream matrix job?

e.g. I have a workflow with jobs like:

```yaml
  build-and-upload-bottle:
    name: Build and upload Homebrew bottle for macOS
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
        include:
          - os: macos-10.15
            version-name: Catalina
            version-file-name: catalina
          - os: macos-11
            version-name: Big Sur
            version-file-name: bigsur
          - os: macos-12
            version-name: Monterrey
            version-file-name: monterrey
    outputs:
      macos-version: ${{ matrix.version-name }}

  update-formula-tap-bottle:
    name: Update the Homebrew formula with bottle file
    runs-on: ubuntu-latest
    needs: build-and-upload-bottle
```

if I access `${{ needs.build-and-upload-bottle.outputs.macos-version }}` in the downstream job `update-formula-tap-bottle`, what value will it have?

will the downstream job be called three times?
