### DISCUSSION TITLE
Feature request: Static variables

### DISCUSSION THREAD

**Discussion by Marvin-Brouwer** [community/community#42050] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi,

I see quite some requests for similar solutions, mostly to share env variables across reusable workflows.
However all I need is static variables. I'm finding myself repeating quite static values like for example this:

```yml
      - name: 🧰 Install .Net SDKs
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 
          7.0.x
          6.0.x
        dotnet-quality: 'preview'
```
Every steps that needs this is redefining the `dotnet-version` parameter. So every time I add support for a new one, I need to update this everywhere.

I'd be happy to have a `parameters`/`variables` section at the root level which functions similar to the `env` section but can't use expressions and can be referenced from reusable workflows.
Or possibly even just immediately useable in the `with` property from the reusable workflows.

Alternatively maybe using the yaml anchors and merge expression would also suffice.

Thanks
