### DISCUSSION TITLE
How to mount file from repository to the service container's volume?

### DISCUSSION THREAD

**Discussion by nuteee** [community/community#42127] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello there!

I wonder if it's possible to mount a file from a repository to a service container's volume mount? 

Based on the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idvolumes)

> You can use volumes to share data between services or other steps in a job. You can specify named Docker volumes, anonymous Docker volumes, or bind mounts on the host.

But if service containers are started before actually running the action steps, how should I set this up?

**Comment by airtower-luna** [comment]
That depends on what you actually want to achieve, as in which data (or directory) do you want to share with the service container?

**Reply by nuteee** [reply]
@airtower-luna let's say I have a repo called `MyRepo`, and there's a directory under that (e.g. `MyRepo/foo/bar/mount-me`) that I would like to mount to the service container.

**Reply by airtower-luna** [reply]
That's unfortunately not going to work, because the directory from your repository won't be available until you call `actions/checkout` in your workflow. The closest you can do is to mount the [`github.workspace`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) into the container. But the workspace will be empty at the start, files will only appear when you check out the repository. So this will only be useful if the service container can load the relevant files when it's already running *and* you can configure the directory to use.

If that's not good enough, the best option is to use `docker run` instead of a service container. That way you can start the service after checking out the repository, and mount exactly the directory you want. If you use other services or a job container make sure to attach the container to the [`job.container.network`](https://docs.github.com/en/actions/learn-github-actions/contexts#job-context), so they all can interact as if you had a service container.

**Reply by hikouki-gumo** [reply]
@airtower-luna Seems like mount github.workspace does not work. Because container and mount are created before checkout. Then checkout actions will fail due to workspace is not clean.

```
volumes:
  - ${{ github.workspace }}/Downloads:/home/user/Downloads
```

```
Deleting the contents of '/__w/REPO_NAME/REPO_NAME'
Error: File was unable to be removed Error: EACCES: permission denied, rmdir '/__w/REPO_NAME/REPO_NAME/Downloads/'```

**Reply by airtower-luna** [reply]
@hikouki-gumo That's a variant of what I described above (if you'd mount the *whole workspace* there shouldn't be that error, but it'd still be empty until checkout). The approach of using `docker run` *after checkout* should work.

**Reply by hikouki-gumo** [reply]
Hi @airtower-luna, I tried `docker run` and attached to job.container.network as your suggestion.

For more contexts, I want to provide Selenium service using Selenium Grid in standalone mode and mount $GITHUB_WORKSPACE/target/Downloads to Downloads folder of Selenium container. After docker run, I tried to connect Selenium service using URL http://standalone-selenium:4444/ (I'm using --network-alias options to specify standalone-selenium), but failed to connect. Am I wrong or missing any step?


```
jobs:
  run:
    runs-on:
      - self-host-runner

    container:
      image: ${MY_RUNNER_CONTAINER_IMAGE}
      options: --user 1001
      volumes:
        - /run/docker:/run/docker
      env:
        ...

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          ./build.sh

      - name: Provide Selenium Grid
        run: |
          mkdir "$GITHUB_WORKSPACE/target/Downloads"
          sudo chown 1200:1201 "$GITHUB_WORKSPACE/target/Downloads"
          docker run --rm -d -p 4444:4444 -p 7900:7900 --network ${{ job.container.network }} --network-alias standalone-selenium --shm-size="2g" -v "$GITHUB_WORKSPACE/target/Downloads":"/home/seluser/Downloads"  selenium/standalone-chrome:latest

      - name: Run test
        run: |
          ./test.sh
      
```

**Reply by airtower-luna** [reply]
The `standalone-selenium` will only work from other containers on the same network, from the host need to use the published port (`localhost:4444`) or figure out the IP of the container.

**Reply by hikouki-gumo** [reply]
There are 2 containers here, job_container (using image MY_RUNNER_CONTAINER_IMAGE) and service_container (Selenium). Because I start service_contain by `docker run` with `--network ${{ job.container.network }}` and `--network-alias standalone-selenium`, I think 2 containers are on the same network and `standalone-selenium:4444` should work? 

Updated: after testing, the connection is flaky. job_container failed to connect `http://standalone-selenium:4444/`, but when I rerun it can connect. Have no idea yet why it's flaky

**Reply by airtower-luna** [reply]
Maybe the container takes a while to start up, and wasn't ready yet on the first attempt? If it's that, you might want to add a loop that probes if the container is ready, and waits a little if not before repeating the check.

**Reply by cx-shahar-septon** [reply]
Another suggestion: Try to mount the volume as "shared" (add suffix :z)
-v "$GITHUB_WORKSPACE/target/Downloads":"/home/seluser/Downloads":z
Some paths are not mounted in GitHub flows to protect the hosting machine (it may become unstable/inoperable if mounted as "private").
For more info:
[https://docs.docker.com/engine/storage/bind-mounts/#configure-the-selinux-label]

**Comment by n-oden** [comment]
Just to add my $0.02 in the hopes that someone from github is watching:

I agree that this does not currently seem to be possible, and it's a really bad limitation of the services product.

An absolutely bog-standard pattern you'll see when using docker for CI work is that the docker image will look for run-time configuration files in a standard place, so that you can just mount them into the container.  A more or less canonical example of this is the official Postgres docker image: the container will on startup execute any .sh or .sql files that it finds in the directory [/docker-entrypoint-initdb.d](https://github.com/docker-library/docs/blob/master/postgres/content.md#initialization-scripts) -- this is commonly used to ensure that all db migrations are applied before the container starts up.

Not being able to do this with GHA services really restricts their utility. :(

**Reply by nesl247** [reply]
Running into this right now. I really don't think GitHub knows what they are doing with Actions. It's the worst CI system I've had to deal with, but unfortunately it's the one that's natively integrated.

**Reply by mannion007** [reply]
@n-oden We recently worked around that, albeit with MySQL.

We just have the step:

```
- name: Prepare baseline schema
  run: |
    cat data/database/schema.sql | mysql -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -h127.0.0.1 ${{ env.MYSQL_DATABASE }}
```

`schema.sql` is a snapshot of the schema at some point that includes the table (and data) for tracking migrations. We can then run migrations in the step after this and any migrations written since that snapshot are applied and we have the latest schema ready to run the tests that depend on it.

Nothing groundbreaking, but the idea may help someone.

**Comment by bkuhl** [comment]
Agreed.  For our use case, we need to publish pre-seeded database containers to use for non-prod environments.  Typically with something like mysql we'd do this by running a mysql service while allowing `/var/lib/mysql` to be mounted locally, then after the seed, stop the service and use that folder to build a fresh mysql container which ends up being published.

**Comment by mark-jordanovic-lewis** [comment]
I have a similar use case. I am migrating a docker-compose over to service containers. All the config files for testing are in the repo and are required to be mounted into the containers. The workaround of running the containers manually along with the bridge network makes the workflow messy. Abstracting it to an action keeps it clean but I would much prefer to use the `services` syntax and hold the container spin up to be triggered by a follow up action.

**Comment by amardeep2006** [comment]
I also have similar usecase. I want to perform checkout repo before I can start service container. 
I donot want to use docker-compose within github action. Service containers work great for me except for this limitation where I cannot pass configurations to the service container via volume.

**Comment by ronin1** [comment]
I am running into this issue now. My previous team used git-labs and this was 100% possible. It was possible with Bitbucket also.

We are going to use `docker run` suggestion as mentioned above but man this is kind of a big let down. GitHub of all places. We might have to switch CI if `docker run` is clunky 👎

**Comment by strangemonad** [comment]
I'm surprised this is still an issue. We're also affected by this. There's all sorts of edge cases with a manual docker run like making sure you don't accidentally leak credentials, waiting for the service to be healthy, etc.

**Comment by bkuhl** [comment]
I've found it's actually much simpler to use a docker-compose configuration to run services, define dependencies, wait for service health, env var configuration for containers, etc.  It keeps the pipeline syntax clean and offers a more familiar, less verbose and syntaxtually clean approach.

**Reply by danon** [reply]
@bkuhl Are you still using it? How do you wait for services to get ready?

**Reply by bkuhl** [reply]
For a standard PHP application, I create a compose service that'll actually run the task I need (in this case integration tests), and use compose to handle dependencies, config, startup, etc.  

```
services:
  integration-tests:
    image: ${INTEGRATION_TEST_IMAGE}
    command: entrypoint: php -d memory_limit=-1 /opt/app/site/vendors/bin/phpunit --configuration=/opt/app/phpunit.xml --testsuite=integration --verbose
    depends_on:
      rabbit:
        condition: service_healthy
      mysql:
        condition: service_healthy
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_PASSWORD: my-password
      MYSQL_ROOT_PASSWORD: my-root-password
      MYSQL_USER: some-user
    healthcheck:
      retries: 15
      test: mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD
      timeout: 20s
    image: mysql:latest
    ports:
    - target: 3306
  redis: ...
```

Then in GHA, all I need to do is:

```
    - name: "Run integration tests"
      run: docker-compose -f docker/ci/integration-tests.yml run integration-tests
```

**Reply by edeesis** [reply]
> @bkuhl Are you still using it? How do you wait for services to get ready?

If you're wanting to wait for all services to be healthy, you can define a health check in the docker compose file and do `docker compose up --wait` which will wait for services to be healthy before exiting

**Comment by bconway** [comment, marked as answer]
I've been using the following workaround to do this for a couple years now, but I can't seem to find the original link where I got the idea/syntax, which is what led me to this thread. If it helps anyone, here are my snippets. In this case, I'm using the Mosquitto MQTT service for integration tests, and want to mount configuration and password files rather than disabling authentication.

The build runs in a Go container (may not be relevant):

```
    container:
      image: golang:1.21-alpine
```

The MQTT service container is started:

```
    services:
      mqtt:
        image: eclipse-mosquitto:2.0
        volumes:
          - ${{ github.workspace }}/build/volume/mosquitto:/mosquitto/config
        options: --name mqtt
```

Nothing is populated yet due to lack of checkout. After checkout, the service container is restarted with this step:

```
      - name: Restart_MQTT
        # Restart MQTT after volumes have been checked out
        uses: docker://docker
        with:
          args: docker restart mqtt
```

Tests now proceed correctly with the mounted file(s).

**Reply by robin-grenzdoerfer** [reply]
THANKS!!!!

**Reply by commonism** [reply]
Great advice.

But - checkout has to use path else checkout will fail on the bindmount directory during initial cleanup
```yaml
    steps:
    - uses: actions/checkout@master
      with:
        path: code
```

run - use working-directory …

```yaml
    - name: install deps
      working-directory: ./code
      run: |
```

and writing to the volume from the runner requires sudo

```yaml
    - name: install deps
      working-directory: ./code
      run: |
        sudo unzip $HOME/www-data/DSP2043_2024.1.zip "public-rackmount1/*" -d ${{ github.workspace }}/tmp/DSP8010/public-rackmount1
```

**Reply by bconway** [reply]
I haven't needed any of those settings for my builds to run and clean up successfully, but I'm glad you found a configuration that works for you!

**Reply by commonism** [reply]
I've had the volume mounted to `${{ github.workspace }}/tests/data` and the git checkout-cleanup error looks like this:
```
Run actions/checkout@master
Syncing repository: commonism/aiopenapi3_redfish
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/ebd40b0c-8741-4cbd-8152-ddcb13d521f4' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish
Deleting the contents of '/home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish'

Error: File was unable to be removed Error: EACCES: permission denied, rmdir '/home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish/tests/data'
```

Accessing the volumed mounted directory without sudo
```
Run ls -al /home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish/tmp/DSP8010/public-rackmount1/
  ls -al /home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish/tmp/DSP8010/public-rackmount1/
  mkdir -p /home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish/tmp/DSP8010/public-rackmount1
  ls -al /home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish/tmp/DSP8010/public-rackmount1
  touch /home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish/tmp/DSP8010/public-rackmount1/test
  unzip $HOME/www-data/DSP2043_2024.1.zip "public-rackmount1/*" -d /home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish/tmp/DSP8010/public-rackmount1
  shell: /usr/bin/bash -e {0}
  env:
    OS: ubuntu-latest
    PYTHON: 3.12
    pythonLocation: /opt/hostedtoolcache/Python/3.12.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib
    LD_PRELOAD: /lib/x86_64-linux-gnu/libgcc_s.so.1
total 8
drwxr-xr-x 2 root root 4096 May 29 12:31 .
drwxr-xr-x 3 root root 4096 May 29 12:31 ..
total 8
drwxr-xr-x 2 root root 4096 May 29 12:31 .
drwxr-xr-x 3 root root 4096 May 29 12:31 ..

touch: cannot touch '/home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish/tmp/DSP8010/public-rackmount1/test': Permission denied
…
```

And I was unable to copy from the ${{ runner.temp }} to the container
```
Run docker://docker
  with:
    args: docker cp /home/runner/work/_temp/DSP8010/public-rackmount1 mockup:/usr/src/app/
  env:
    OS: ubuntu-latest
    PYTHON: 3.11
    pythonLocation: /opt/hostedtoolcache/Python/3.11.9/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.9/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.9/x64/lib
    LD_PRELOAD: /lib/x86_64-linux-gnu/libgcc_s.so.1
/usr/bin/docker run --name docker_081535 --label ae66c1 --workdir /github/workspace --rm -e "OS" -e "PYTHON" -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "LD_PRELOAD" -e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -- \
network github_network_748b10dcb70449848d50f7ca92ea8b3e \
-v "/var/run/docker.sock":"/var/run/docker.sock" \
-v "/home/runner/work/_temp/_github_home":"/github/home" \
-v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
-v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" \
-v "/home/runner/work/aiopenapi3_redfish/aiopenapi3_redfish":"/github/workspace" \
docker docker cp /home/runner/work/_temp/DSP8010/public-rackmount1 mockup:/usr/src/app/

lstat /home/runner: no such file or directory
```

But - it's even worse, in my case the service container does not start when provided an initial empty volume directory, health check fails, pipeline fails.
Therefore the volume has to be mounted "somewhere else" in the container, so the service starts. Now it can get populated and have ` docker container exec … cp` the files to the containers services data directory before getting restarted.
Anyway, your comment made a significant difference, thanks.

```yaml
name: Codecov
on: [push, pull_request]
jobs:
  run:
    services:
      mockup:
        image: dmtf/redfish-mockup-server:latest
        volumes:
          - ${{ github.workspace }}/tmp/DSP8010/public-rackmount1:/tmp/public-rackmount1
        options: --name mockup
        ports:
          - 8000:8000

    steps:
    - uses: actions/checkout@master
      with:
        path: code

    - name: service::mock - unzip DSP8010 public-rackmount1
      run: |
        mkdir -p ${{ github.workspace }}/tmp/DSP8010/public-rackmount1
        ls -al ${{ github.workspace }}/tmp/DSP8010/public-rackmount1
        sudo unzip $HOME/www-data/DSP2043_2024.1.zip "public-rackmount1/*" -d ${{ github.workspace }}/tmp/DSP8010/

    - name: service::mock - copy service files
      uses: docker://docker
      with:
        args: docker container exec mockup cp -a /tmp/public-rackmount1 /usr/src/app/

    - name: service::mock - restart to feed the volume
      # https://github.com/orgs/community/discussions/42127#discussioncomment-7591609
      uses: docker://docker
      with:
        args: docker restart mockup

    - name: Generate coverage report (mock)
      working-directory: ./code
      run: |
        pdm run pytest …

```

**Reply by mgriego** [reply]
I'm not sure if it's necessary, but one thing I added to this is to use a unique name for the service container. ie:
```
    services:
      wiremock:
        image: wiremock/wiremock
        volumes:
          - ${{ github.workspace }}/wiremock:/home/wiremock
        options: --name ${{ github.run_id }}-${{ github.run_attempt }}-wiremock
```
and:
```
      - name: Restart Wiremock
        # Restart Wiremock after volumes have been checked out
        uses: docker://docker
        with:
          args: docker restart ${{ github.run_id }}-${{ github.run_attempt }}-wiremock
```

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by lyleschemmerling** [comment]
I also just hit this and it is really really annoying. I'm simply trying to mount an nginx.conf file into nginx container. Feels like a common thing.

**Comment by DavidVaness** [comment]
Also ran into this today

**Comment by danon** [comment]
Run into this issue today. I tried to pass confirugration to my service, and I see it can't be done the normal way.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by Netkas** [comment]
Why isn't this a documented issue on GitHub workflows?

**Comment by johngeorgewright** [comment]
Some of the above comments were handy, thank you, but in my particular scenario I was led down the wrong path.

I want to use a volume to inspect the file system of a running service, modify it, and inspect it again. This how I achieved it.

1. **Make sure that the containers are using the root user**. If there's a change of user in the Dockerfile, you'll have to add an option to override it. See the [docs](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#docker-container-filesystem)
2. Do not use the `workspace` directory, especially when using a container as the container has the workspace mounted as a volume too. And the content is at risk of being deleted during your steps.

```yaml
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      esm:
        image: ghcr.io/esm-dev/esm.sh:latest
        options: --user root # IMPORTANT!
        ports:
          - '8080:8080'
        volumes:
          # Notice that we're not using the workspace (`/home/runner/work`)
          # Instead we'll use a sibling directory
          - /home/runner/docker-storage/esmd:/esmd

    container:
      image: oven/bun:1
      env:
        ESM_ORIGIN: http://esm:8080
        ESM_STORAGE_PATH: /esmd
      options: --user root # IMPORTANT!
      volumes:
        # Notice that we're not using the workspace (`/home/runner/work`)
        # Instead we'll use a sibling directory
        - /home/runner/docker-storage/esmd:/esmd

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install
        run: bun install

      - name: Test Compilation
        run: bunx tsc

      - name: Test
        run: bun test
```

**Comment by bonetunes** [comment]
I am also having this issue, trying to mount some config files into the service, and those files need to be checked out from the repo before the service starts

**Comment by flozdra** [comment]
Hello,

Thank you everyone for the responses, they gave me ideas, and I finally managed to make it works!

In my case, I just need to add a configuration file into the service container.

For example, here is a snippet of my `compose.yml` that I run locally : 
 ```yml
   clickhouse-01:
    image: 'clickhouse/clickhouse-server:latest'
    container_name: clickhouse-01
    hostname: clickhouse-01
    volumes:
      - ${PWD}/docker/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
```

To replicate the same environment in GitHub Actions, I followed these steps : 
- Define a `name` (and `hostname` for my configuration) for the containers
- Copy the configuration files from the workspace to the containers **after** the `checkout` step 
- Restart the services manually

```yml
jobs:
  tests:
    services:
      clickhouse-01:
        image: clickhouse/clickhouse-server:latest
        # Define the name and hostname
        options: --name clickhouse-01 --hostname clickhouse-01

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # Copy files after checkout
      - name: Copy config files to services
        run: |
          docker cp ${{ github.workspace }}/docker/clickhouse-01/etc/clickhouse-server/config.d/config.xml clickhouse-01:/etc/clickhouse-server/config.d/
      # Restart services manually
      - name: Restart services
        run: |
          docker restart clickhouse-01
```

You can check out the full [`test.yml`](https://github.com/flozdra/adonisjs-clickhouse/blob/main/.github/workflows/test.yml) file here.
