### DISCUSSION TITLE
Ran script on GitHub's servers???

### DISCUSSION THREAD

**Discussion by Kuzuru** [community/community#42155] [Actions] [answered]
### Select Topic Area

Bug

### Body

Long story short. Just wrote that YAML workflow (kuzuru/notifier-bot) in case to connect to my server. But It:

1. Started container inside GitHub's runner
2. Skipped part that should connect workflow with my server
3. Executed my own script and started up my bot on github's runner server

I'm really thankful that I don't have to pay for a server, but as I see it, it's abusive :D
I'd like to hear an official comment from the developers of GitHub Actions about this

```yaml
name: Remote SSH Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Executing Remote SSH
      uses: webfactory/ssh-agent@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Atomic Deploy
      run: |
          wget https://github.com/Kuzuru/notifier-bot/releases/download/runner/run-bot-linux.sh
          chmod +x+x+x run-bot-linux.sh
          sudo ./run-bot-linux.sh
```
