### DISCUSSION TITLE
Multiple problems (wrong title / job state) in the UI for reusable workflows + matrix

### DISCUSSION THREAD

**Discussion by connorjclark** [community/community#42183] [Actions]
### Select Topic Area

Bug

### Body

The four "test" workflows shown in this image are created from a matrix using a reusable workflow:

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/4071474/208603284-4554dced-38b3-4c5b-8777-50097d0bc811.png">

```yml
jobs:
  test:
    strategy:
      matrix:
        include:
          - runs-on: windows-2022
            arch: x64
            compiler: msvc
          - runs-on: windows-2022
            arch: win32
            compiler: msvc
          - runs-on: macos-12
            arch: intel
            compiler: clang
          - runs-on: ubuntu-22.04
            arch: x64
            compiler: clang
      fail-fast: false
    # See https://github.com/community/community/discussions/40777
    uses: ./.github/workflows/test.yml
    # uses: ArmageddonGames/ZQuestClassic/.github/workflows/test.yml@main
    with:
      runs-on: ${{ matrix.runs-on }}
      arch: ${{ matrix.arch }}
      compiler: ${{ matrix.compiler }}
```

The result of this in the GHA UI is very confusing, clearly a bug here.

`test (ubuntu-22.04, x64, clang)` should be `test (macos-12, intel, clang) / build / build`, as is printed in the logs (this is set by `run-name:`. For some reason GHA  is showing the wrong name in the UI. The title is only shown incorrectly for this first "test" workflow–all the others look fine when I open them.

The grouping on the left is also totally wrong - these workflows are 4 different parts of a matrix declaration, and it's pretty odd that two of them would be grouped together. The first one under the "Ubuntu" header is what's shown in the image above, and it actually links to the Mac run! The second one is the Ubuntu run, though, so that's correct.

Eventually the "build" job from the Ubuntu workflow finishes and kicks off some more jobs in that reusable workflow. This seems to "kick" something into place and the titles are all good now, but a new problem is that the "build" job – which is done – still shows as pending in the UI...

<img width="970" alt="image" src="https://user-images.githubusercontent.com/4071474/208604516-59dec248-664f-4b7c-90b3-5ea926c1e788.png">

I eventually see the same problem for windows and mac, "build" is done but the UI says it's still pending.

BTW, `test.yml` itself calls another reusable workflow `build.yml`. All of these reusable workflows set a `run-name:`. Perhaps relevant.

[the workflow run](https://github.com/connorjclark/ZeldaClassic/actions/runs/3738217751)
