### DISCUSSION TITLE
GitHub Wrapping off?

### DISCUSSION THREAD

**Discussion by AliAryanTech** [community/community#42298] [Repositories] [answered]
### Select Topic Area

Issue 
### Body

Few days ago GitHub has been changed a little bit. I mean "warp code off" coz I mostly use GitHub with my phone chrome but now it feels hard to see code while warp is like that.. please change it back to old 🥲

- **Still don't get it??**
Old GitHub be like:
![Old GitHub code](https://user-images.githubusercontent.com/85696485/208919081-34be9c50-9d5e-4946-826e-05d544f4998d.jpg)

Now GitHub be like:
![Now GitHub code](https://user-images.githubusercontent.com/85696485/208919190-f2f074fa-93d7-4a35-8df8-ba4b67c23e35.jpg)

**Comment by dannye** [comment]
This new word-wrap doesn't just affect mobile, but it affects desktop browsers too if you make the window narrow enough. It is objectively bad. I am begging for this to be reverted. Please just let me scroll to the right to see the code in context as-is.

**Reply by AliAryanTech** [reply]
So, we all are facing pretty bad situation. 

🥴 Need Holidays from GitHub

**Comment by gusutabopb** [comment]
Horrible change. Please revert to old behavior ASAP!

Workaround for desktop for gists (source: https://www.bennadel.com/blog/4373-fixing-github-gists-sudden-case-of-line-wrapping.htm)

```css
body .gist .blob-code-inner {
  white-space: pre ;
}
```


**Edit:**

For regular repo code (non-gist) pages, the following CSS override fixed it for me:

```css
td.blob-code-inner {
  white-space: pre;
}
```

This also works: 

```css
/* No `.gist` */
body .blob-code-inner {
  white-space: pre;
}
```

I'm using the following browser extensions to override CSS:

 - [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en) for Chrome (desktop)
 - [Makeover](https://apps.apple.com/app/makeover-custom-css/id1602361167) for iOS
