### DISCUSSION TITLE
Dependapot creates PR for npm while it is configured only for gomod

### DISCUSSION THREAD

**Discussion by devsergiy** [community/community#42325] [Code Security]
### Select Topic Area

Bug

### Body

Hi!

here is my dependapot.yml file content

```
version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
```
located here
https://github.com/wundergraph/graphql-go-tools/blob/master/.github/dependabot.yml

Dependapot creates PRs for golang:
https://github.com/wundergraph/graphql-go-tools/pull/467

Which is fine and expected

But along that it creates PRs for our example code with npm:
https://github.com/wundergraph/graphql-go-tools/pull/470

And this one is unexpected, cause I have not configured it for the npm

so 2 questions here:

1. Is it possible to ignore any other package manager dependencies?
2. Is it possible to track only dependencies of root level `go.mod` - we have an examples as go modules also located in the same repo and we don't want to have PRs for them
