### DISCUSSION TITLE
workflow_run is triggered multiple times

### DISCUSSION THREAD

**Discussion by petkaantonov** [community/community#42367] [Actions] [answered]
### Select Topic Area

Question

### Body

We have a workflow that installs required common cache for all of our workflows:

```
name: Cache dependencies
on:
  workflow_run:
    workflows:
      [
        ... long list of workflows that need the common cache
      ]
    types:
      - requested
```

When I push a commit that triggers multiple workflows that are listed ,
multiple instances of this Cache dependencies job are created. Due to the concurrency 
value they are just cancelled immediately so that only 1 instance of the job runs. 
But there is still a ton of spam in email about cancelled jobs.

If workflow_run is not meant to do what I want here, how can I accomplish? This should
be a common thing to do.

**Comment by petkaantonov** [comment, marked as answer]
Looks like I found a workaround myself.

Create a dummy workflow like this:

```
# A job whose only purpose is to trigger the dependencies
# install workflow.

name: "Trigger dependencies install"

on:
  workflow_dispatch:
  push:

jobs:
  noop:
    runs-on: ubuntu-20.04
    name: Do nothing
    if: false
    steps:
      - run: echo "Hello world"

```

Then change the workflow_run to only trigger on this dummy workflow:

```
name: Cache dependencies
on:
  workflow_run:
    workflows:
      ["Trigger dependencies install"]
    types:
      - requested
```

Why not just install the dependencies directly in the dummy workflow? Because of cache scoping the cache must always be
created in the context of default branch (master or main). The workflow_run triggered workflow is always run in the context
of the default branch, while a push triggered workflow is ran in the context of the branch that was pushed. When the branch
is merged the master branch would have to create cache from scratch yet again.
