### DISCUSSION TITLE
needs context not available for jobs.<job_id>.concurrency

### DISCUSSION THREAD

**Discussion by AllanOricil** [community/community#42411] [Actions]
### Select Topic Area

Product Feedback

### Body

Docs says that the `needs` context is available for the `jobs.<job_id>.concurrency`, but this isn't true.

https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

I have a workflow that runs on PR comments. The first job of this workflow extracts the name of the environment. Then it sets this environment as the output of the job. The second job, which requires the first to pass, uses the output of the first job to set the environment of the job, as well as to set the concurrency.group. The environment is set correctly, but the concurrency group is not.

````yml
...

jobs:
  get-environment:
    name: Get Environment
    runs-on: ubuntu-latest
    if: "startsWith(github.event.comment.body, '[validate-') && endsWith(github.event.comment.body, ']')"
    steps:
      - name: get-environment
        run: |
          echo "PR comment: ${{ github.event.comment.body }}"
          environment=$(echo ${{ github.event.comment.body }} | sed -e 's/\[validate-\(.*\)\]/\1/')
          echo "environment: $environment"
          echo "environment=$environment" >> $GITHUB_OUTPUT

  validate-changes:
    name: Validate Metadata Changes
    needs: get-environment
    environment: ${{ needs.get-environment.outputs.environment }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vodafoneis/salesforce-build-image:v1.1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    concurrency:
      group: ${{ github.sha }}-${{ needs.get-environment.outputs.environment }}-${{ github.workflow }}
      cancel-in-progress: true

...
````

This is the output of the first job
![image](https://user-images.githubusercontent.com/55927613/209188003-2903a9a6-e87e-4dd8-b64c-3c97a4b78e4b.png)

Then the word `dev` is passed to the second job using the `needs` context. But as you can see in the error message, the `job.<job-id>.concurrency.group` is missing the word `dev` 

rendered group key: `45cb6c1daefa720a03924f6e2251211fbd3e1d55--Metadata Deploy Validation Workflow - Pull Request Comment`

![image](https://user-images.githubusercontent.com/55927613/209188173-e5761f08-ee3c-4fa0-b62a-72ce1c04f312.png)
