### DISCUSSION TITLE
How do I reference deployment environment name?

### DISCUSSION THREAD

**Discussion by joowani** [community/community#42574] [Actions]
### Select Topic Area

Question

### Body

How do I reference the environment name in my job steps?

Example:
```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    environment: "foobarbaz"
    ...

    steps:
      ...
      - name: Terraform Check Format
        id: terraform-fmt
        # what should I use here instead of "????" to get "foobarbaz"?
        run: terraform -chdir=terraform/stacks/${{ ???? }}/${{ matrix.stack }} fmt -check
```
