### DISCUSSION TITLE
workflow_call not running on the same self-hosted runner as the caller workflow

### DISCUSSION THREAD

**Discussion by hemi-SX** [community/community#42597] [Actions]
### workflow_call

Bug

### caller and workflow_call running on different self-hosted runners

I am running a two level workflow_call (see details below),
my issue is that when build.yml is calling set-env.yml workflow the set-env it is not running on the same runner as the build and the next job on build which is builder running on an old repo insted of on the one created by set-env

1.  main.yml calling a workflow_call in build.yml
main.yml:
```
name: main
    on:
      push:
    jobs:
      run_build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
```
2. build.yml is calling another workflow_call (=set_env) among other jobs it is running:
build.yml:
```
name: build
on: 
  workflow_call:
jobs:
  set-env:
    uses: ./.github/workflows/_set_env.yml
    secrets: inherit
    with:
      test_arch: 'X64'

  builder: #running build on self-hosted runner linux X64 platform
    runs-on: [self-hosted, linux, X64, aws] 
    needs: [set-env]

    steps:
      - name: AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }} #retrieving AWS access key from github secrets
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }} #retrieving AWS access secret from github secrets
          aws-region: eu-west-1 #setting AWS region to eu-west-1

      - name: Amazon ECR Login Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v1

      - name: Building #running docker build
        run: |
          ./run_docker.sh deploy

      - name: Push to ECR #uploading build image to ecr
        run: |
          repo_tag=<project>:${{ needs.set-env.outputs.GIT_TAG }}_${{ needs.set-env.outputs.ARCH }}
          docker tag ${repo_tag} ${{ secrets.ECR_DOCKER_REGISTRY }}/${repo_tag}
          docker push ${{ secrets.ECR_DOCKER_REGISTRY }}/${repo_tag}

  run_tests:
    needs: [set-env, builder]
    uses: ./.github/workflows/_run_tests.yml
    secrets: inherit
    with:
      arch: ${{ needs.set-env.outputs.ARCH }}
      git_tag: ${{ needs.set-env.outputs.GIT_TAG }}
```
set-env.yml
```
name: set_env

on: 
  workflow_call:
    inputs:
      test_arch:
        required: true
        type: string
    outputs:
      ARCH: 
        value: ${{ jobs.set-env.outputs.ARCH }}
      GIT_TAG: 
        value: ${{ jobs.set-env.outputs.GIT_TAG }}
    
jobs:
  set-env:
    runs-on: [self-hosted, linux, X64, aws]
    outputs:
      ARCH: ${{ steps.set_system_arch.outputs.ARCH }}
      GIT_TAG: ${{ steps.set_build_git_tag.outputs.GIT_TAG }}

    steps:
      - name: AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }} #retrieving AWS access key from github secrets
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }} #retrieving AWS access secret from github secrets
          aws-region: eu-west-1 #setting AWS region to eu-west-1

      - name: Checkout #git clone Meerkat and submodules
        uses: actions/checkout@v3
        with:
          repository: <projet>#github repository
          lfs: true
          fetch-depth: 0 #fetch-depth - Number of commits to fetch. 0 indicates all history for all branches and tags.
          submodules: recursive #clone also all Meerkat submodules 
          token: ${{ secrets.CI_GIT_PAT }} #retrieving token to for github pull from github secrets
          persist-credentials: true #persist credentials to github secrets

      - id: set_system_arch
        run: |
          get_arch=$(uname -p)
          echo "ARCH=$get_arch"
          echo "ARCH=$get_arch" >> $GITHUB_OUTPUT
      - id: set_build_git_tag
        run: |
          git_tag=$(git describe --tags)
          echo "GIT_TAG=$git_tag"
          echo "GIT_TAG=$git_tag" >> $GITHUB_OUTPUT
```
