### DISCUSSION TITLE
How to run 2 workflows sequentially where the 1st workflow can execute optionally

### DISCUSSION THREAD

**Discussion by sisaha9** [community/community#42734] [Actions]
### Github Actions

How to run 2 workflows sequentially where the 1st workflow can execute optionally

### Body

I have one workflow building a Docker image and pushing it and another workflow that uses that image for testing. The Docker image workflow only needs updates when certain files change so I have set it to run only when certain files change. However, this would block attempts to run the workflows sequentially as from reading around the way to have sequential workflows is using workflow dispatches. Any suggestions?

**Comment by ParkerM** [comment]
This can be done in job contexts by combining `needs` and `if: always()` (see sample docs [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-not-requiring-successful-dependent-jobs)). Whether this is sufficient for your case would depend on how your workflow triggers are setup.

I've used something similar to debug outputs at the end of a run despite jobs failing or being skipped:

```yaml
jobs:
  optional-first-job:
    if: some.condition # this job may or may not run
    outputs:
      testval: ${{ steps.echo_test.outputs.testkey }}
    steps:
      - id: echo_test
        run: echo "testkey=testval" >> $GITHUB_OUTPUT

  sequential-second-job:
    needs: 
      - optional-first-job
    if: always() # this job always runs, but waits until needed jobs are completed
    # if: "${{ always() && needs.optional-first-job.result != 'failed' }}" # can also include additional conditions here
    steps:
      - run: echo '${{ toJSON(needs) }}'
```

In this case, the second job will always run regardless of whether the first job was skipped or failed. You could also include additional conditions along with `always()` to restrict it further (e.g. if you want to always run the second job _unless_ the first one started and failed).
