### DISCUSSION TITLE
How can I deploy/publish to GitHub Pages of another repository?

### DISCUSSION THREAD

**Discussion by praveenpandey02** [community/community#42772] [Enterprise]
### Select Topic Area

Question

### Body

I have an enterprise GitHub repository (let’s name it `Repo-A`) and its GitHub Pages is already occupied. Meaning it is already used. I would still want to publish the static html from `Repo-A`. So I have created another repository within the same organisation in which my `Repo-A` exists ( let’s call this one `Repo-B`). How can I publish static html present in `Repo-A` to GitHub Pages of `Repo-B`? Even if get a direction, I can try it out. Right now, I do not even know how to get started.

**Comment by praveenpandey02** [comment]
@tschaub I went through [this](https://github.com/tschaub/gh-pages) and I am wondering if it can help me find a solution

**Comment by younes-io** [comment]
has anyone found a solution to this ? @praveenpandey02 : did that work for you ? (https://github.com/tschaub/gh-pages)

**Reply by tschaub** [reply]
@younes-io (and @praveenpandey02) you can do this using the [`repo` option](https://github.com/tschaub/gh-pages?tab=readme-ov-file#optionsrepo) if you use the https://github.com/tschaub/gh-pages package.

**Reply by younes-io** [reply]
since I'm using Github workflows, I guess I should use `github-actions-bot` as in [here ](https://github.com/tschaub/gh-pages?tab=readme-ov-file#deploying-with-github-actions) with the `--repo` option, right ?
thank you

**Reply by younes-io** [reply]
@tschaub Could you please help on this? I've been struggling for a couple of hours to make this work, but in vain..

I have this `publish.yaml` in my private repo `github.com/younes-io/blog.git`, and I'm trying to push the build of the website (in `./docs`) to the public repo `blog_p` like this:

```yaml
- name: Deploy with gh-pages
      run: |
        npm install gh-pages
        ls -al
        git config --global user.name "github-actions-bot"
        git config --global user.email "support+actions@github.com"
        git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/younes-io/blog_p.git
        cd ./docs/
        npx gh-pages -d . -u "github-actions-bot <support+actions@github.com>" --repo https://github.com/younes-io/blog_p.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by shner-elmo** [comment]
Did you end up finding a solution? I'm trying to do the same thing

**Comment by meysam81** [comment]
For anyone else getting here and still looking for a solution, I recently went through this exercise and I shared my approach with what's already available using only GitHub Actions and OpenTofu.

Read the full blog post here:

<https://developer-friendly.blog/blog/2025/02/10/how-to-publish-to-github-pages-from-another-repository/>

Hope you enjoy.

Cheers :clinking_glasses:

**Comment by InertSloth** [comment]
Google led me here, amongst other places. I hope I can contribute now that my code works.

push one repo to another repo using `peaceiris/actions-gh-pages` action to both set up the SSH agent and do the deploy
https://github.com/peaceiris/actions-gh-pages

Here's a part of my working `<source repo>/.github/workflows/deploy.yml` for peaceiris
```yml
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: <branch to push to, gh-pages is safest>
          publish_dir: ./<build/dist dir>
          enable_jekyll: true # if you just have .md files, index.html can set to false
          external_repository: <user/org>/<deployment repo like org.github.io>
        if: ${{ github.ref == 'refs/heads/main' }} # only deploy if main branch changed
```

I wrote a guide in a github snippets repo documenting the various techniques and packages I tried to do this (several successfully) and go into a lot more depth. Feel free to check it out:
- [github-pages-deploy](https://github.com/apathetic-tools/snippets/blob/main/docs/github/github-pages-deploy)
