### DISCUSSION TITLE
How can you run an action only on publish or prerelease?

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#42780] [Actions] [answered]
### Select Topic Area

Question

### Body

I would like to have two actions.

- One should run whenever I publish a normal release.
- The other should only run when I publish a pre-release.

What would be the proper setup to prevent the actions from triggering on the other event?

I tried the following setups:

- ```yaml
  # file 1
  on:
    release:
      types:
        - published
  
  # file 2
  on:
    release:
      types:
        - prereleased
  ```
- ```yaml
  # file 1
  on:
    release:
      types:
        - published
        - released
  
  # file 2
  on:
    release:
      types:
        - published
        - prereleased
  ```

The first one is causing the first file to trigger on a prerelease, while the second one is causing both files to trigger on both event types.

I assume it's the `published` type causing this, but I also would like to keep it, to avoid accidental triggers whenever I edit an existing release...
What solutions would there be?

**Comment by agustinsacco** [comment]
The only way I have been able to get this to work is to do the following:

```
name: Release
on:
  release:
    types:
      - published

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build:
    if: "!github.event.release.prerelease"
    ...
```

So release type "prereleased" only triggers when pre-release is created and type "published" triggers both but the conditional stops this release from running when we intend only pre-release to run.

Hoping in the future we have a type for release and pre-release that does not leak between each.
