### DISCUSSION TITLE
Exposing ACTIONS_CACHE_URL and ACTIONS_RUNTIME_URL to run step

### DISCUSSION THREAD

**Discussion by albgus** [community/community#42856] [Actions]
### Select Topic Area

Question

### Body

Hello,

I'm looking to implement docker build caching using the GitHub Actions cache to speed up some builds, see: https://docs.docker.com/build/cache/backends/gha/

This needs to have the `$ACTIONS_CACHE_URL` and `$ACTIONS_RUNTIME_TOKEN` parameters defined, but there doesn't seem to be much documented about these parameters and normally the `actions/cache` action produces these parameters internally somehow.

The docker documentation suggests running an external action for this.. However I would like to avoid pulling in yet another third party dependency for something that seems like it could be an one-liner (or maybe 3 lines at least)

So my question is if it's possible to supply this directly to the build action? I naively tried this but it didn't work.
```
        env:
          ACTIONS_RUNTIME_TOKEN: "${{ env.ACTIONS_RUNTIME_TOKEN }}"
          ACTIONS_CACHE_URL: "${{ env.ACTIONS_CACHE_URL }}"
```

I also tried to figure out what the referenced action does, but arrived to a 40kB obfuscated Javascript oneliner.. (which is yet another reason not to rely on it)

**Comment by AndreiSoroka** [comment]
Hi
you can use [ghaction-github-runtime](https://github.com/crazy-max/ghaction-github-runtime)
and after that `env.ACTIONS_RUNTIME_TOKEN` will be available

```yaml
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Env
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env|sort

      - name: Docker build1
        run: echo "ACTIONS_CACHE_URL: ${{ env.ACTIONS_CACHE_URL }} and $ACTIONS_CACHE_URL"
```

Somebody tried it too:
https://stackoverflow.com/questions/74774114/using-docker-buildx-github-action-cache-without-official-actions

**Reply by AndreiSoroka** [reply]
Ok, I created working solution

```yaml
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Docker build
        run: |
          docker context create buildx-build;
          docker buildx create --use --driver=docker-container buildx-build;
          docker buildx build \
            --push \
            -t ${{ secrets.REGISTRY }}/dev/${{ inputs.IMAGE_NAME_APP }}:${{ inputs.IMAGE_TAG }} \
            -t ${{ secrets.REGISTRY }}/dev/${{ inputs.IMAGE_NAME_APP }}:latest \
            --build-arg mode=production \
            --cache-to "type=gha,mode=max" \
            --cache-from "type=gha" \
            .;
```
But without gha cache docker build works faster around 10 sec.
`no cache 2m - 2m20s` vs `gha cache 2m15s -2m30s`

_____
```
COPY package.json package-lock.json /app/
WORKDIR /app
RUN npm --production=false ci
```
<img width="794" alt="image" src="https://user-images.githubusercontent.com/6079139/212411905-27a399af-07bc-426c-80b4-09ce68783ae9.png">
vs
<img width="756" alt="image" src="https://user-images.githubusercontent.com/6079139/212412177-7e7ee353-5be3-455e-8f81-eaa31b577df7.png">


So, `npm ci` is faster than `gha cache`

**Comment by ryepup** [comment]
>  However I would like to avoid pulling in yet another third party dependency for something that seems like it could be an one-liner (or maybe 3 lines at least)

I'm in the same boat. I ended up with a variant of [a stack overflow answer](https://stackoverflow.com/a/74795460). That looks something like:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for using the docker cache
      contents: read
    steps:
      - name: calculate envvars needed for docker caching
        shell: bash
        run: |
          echo "Configuring environment for https://docs.docker.com/build/cache/backends/gha/"
          # derive the cache URL from the token URL, converting something like
          # https://pipelines.actions.githubusercontent.com/<a long id>/<a lot of things>
          # to something like
          # https://artifactcache.actions.githubusercontent.com/<the long id from above>/       
          ACTIONS_CACHE_URL=$(echo "$ACTIONS_ID_TOKEN_REQUEST_URL" | grep -Po 'https://[^/]+/[^/]+/' | sed  's/pipelines/artifactcache/')
          echo "ACTIONS_CACHE_URL=$ACTIONS_CACHE_URL" >> "$GITHUB_ENV"
          echo "ACTIONS_RUNTIME_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - run: |
          docker buildx build --cache-from type=gha --cache-to type=gha -t myapp .
```

**Reply by VincentVerweij** [reply]
Hi, first of all thanks for sharing!  

Does this method still work? I copied the script you have in there and received some URL like this one https://artifactcacheghubeus6.actions.githubusercontent.com/NEfMbv8oeZLQ9T7CIOFpWEO2sWrX7Wj66TSxVTzwIvzh6m2P17/  
The thing is that when calling the `docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --tag repo/myimage:1.0.0 .` command, it does build and after the build it gives me:
```
------
 > importing cache manifest from gha:13957537462642742125:
------
------
 > exporting to GitHub Actions Cache:
------
ERROR: failed to solve: failed to parse error response 400: <h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0k6VdZQAAAACjKDuhJnkmT4bQyx3OUJULUEhYMzFFREdFMDQxNQBFZGdl: invalid character '<' looking for beginning of value
```

It's not the token that I am seeing there, because if you navigate to the link that I've send above, it shows me this:
![image](https://github.com/community/community/assets/41574930/4af36156-dec0-49f2-b23e-f76999daf5b2)

This is running on an `ubuntu-latest` runner. The only thing is that it is executed within a GitHub Enterprise (cloud, not on-premises), not sure whether that might cause any issues.  
I first thought something was down, but https://githubstatus.com shows as all working properly.

> Edit: I did add the two permissions in case you would be wondering.

**Reply by ryepup** [reply]
That project got cancelled, so the workflow has not run in awhile. The last run was successful on 2023-08-28.

I'm suspicious of your `ACTIONS_CACHE_URL`; yours has a `ghubeus6` that mine didn't. I'm guessing enterprise uses different domains.

**Reply by VincentVerweij** [reply]
Yeah, you might be right. It's a pity that the documentation is nowhere to be found... Thanks for answering though!

**Reply by ryepup** [reply]
You might be able to use the `crazy-max` action to print the correct url, then adjust my shell commands to do the right thing in enterprise.

**Reply by VincentVerweij** [reply]
Well if the action is allowed by our administrator, then I would certainly give it a try and be happy to update this discussion with the script. But they do not allow that much...

**Reply by VincentVerweij** [reply]
I did some research on this. I couldn't get this working with a regular bash script. It seems that when outputting environment variables that there are only 3 variables that start with `ACTIONS_`.  
The ones that were missing are:
- ACTIONS_RUNTIME_URL
- ACTIONS_RUNTIME_TOKEN
- ACTIONS_CACHE_URL

I saw that `ACTIONS_RUNTIME_URL` could be filled with the logic provided by your script on `ACTIONS_ID_TOKEN_REQUEST_URL`. The issue that I have is that `ACTIONS_CACHE_URL` contains a completely different value.

So, `ACTIONS_ID_TOKEN_REQUEST_URL` starts with "https://pipelinesghubeus6.actions.githubusercontent.com/", while `ACTIONS_CACHE_URL` starts with "https://acghubeus1.actions.githubusercontent.com/".  

The long ID that is suffixed, is the same for both of these variables, but I don't know if we can always use that "https://acghubeus1.actions.githubusercontent.com/" to start `ACTIONS_CACHE_URL` with.  

I solved it by simply using the following (available on the same [StackOverflow link](https://stackoverflow.com/a/77225313/2441681), linked above):
```yaml
- name: Adding required env vars for caching Docker build
  uses: actions/github-script@v7
  env:
    github-token: ${{ secrets.GITHUB_TOKEN }}
  with:
    script: |
      core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
      core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
      core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])

- name: Echo required env vars
  shell: bash
  run: |
    echo "ACTIONS_CACHE_URL: $ACTIONS_CACHE_URL"
    echo "ACTIONS_RUNTIME_TOKEN: $ACTIONS_RUNTIME_TOKEN"     
    echo "ACTIONS_RUNTIME_URL: $ACTIONS_RUNTIME_URL"
```

I am able to use this as actions/github-script has the verified creator badge.
