### DISCUSSION TITLE
npm install with custom basic access token fails

### DISCUSSION THREAD

**Discussion by adamazad** [community/community#42852] [Actions]
### Select Topic Area

Question

### Body

Hi all,

We have a repo that relies upon a private npm package hosted under the same GitHub org.

Apps package.json:

```json
{
  "dependencies": {
      "@nimi.io/private-package": "git+https://<TOKEN>:x-oauth-basic@github.com/nimi-app/private-repo.git"
  }
}
```

This setup works fine on
- Vercel (which requires us to use this),
- Developers have no issues installing the package,

Yet, this setup fails on GitHub actions with the following errors:

```
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ***github.com/nimi-app/private-repo.git
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/nimi-app/card.git/' not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-12-29T12_29_33_544Z-debug-0.log
Error: Process completed with exit code 128.
```

Workflow:

```yaml
name: CI

on:
  push:
    branches:
      - development
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build
```
