### DISCUSSION TITLE
Multiline placeholders for issue forms not working in Safari

### DISCUSSION THREAD

**Discussion by ivirshup** [community/community#4290] [Projects and Issues] [answered]
**update:** It looks like this issue is Safari (v14.1.1) specific for me.

Hi,

Really liking the new issue forms!

I have a feature request/ possible bug report. For `textarea` elements, the `value` can be multiline, but it looks like the `placeholder` has new lines stripped out. I would like to be able to have a multiline placeholder.

My use case is wanting to encourage our users to put their example code inside of code blocks. I would put this in values, but we also have the issue of people just leaving all the example text in our current issue templates. A placeholder example of code block has to be multiline, since that's the syntax for code blocks.

### Example

From these yaml elements

```yaml
  - type: textarea
    id: placeholder
    attributes:
      label: Some text
      placeholder: |
        foo
        bar
        baz
  - type: textarea
    id: value
    attributes:
      label: Some text
      value: |
        foo
        bar
        baz
```

I get this rendered result:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/8238804/123232642-b3f65d00-d51c-11eb-95ab-cf0e2e493db7.png">

Thanks!
