### DISCUSSION TITLE
A dedicated file upload input type in issue forms

### DISCUSSION THREAD

**Discussion by foosel** [community/community#4291] [Projects and Issues]
Picking this up from the closed preview ;)

I'm pretty sure I'm not the only one who requires log files and similar files from their users in order to be able to process a bug report. Right now the only option I have to request that from people is to instruct them to upload them via a `textarea` input. According to my experienced during the preview a ton of people will happily overlook instructions like this and thus I still have to still run after log files. Something like this:

``` yaml
- type: file
  attributes:
    label: Your `octoprint.log`
    description: You can find it under Settings > Logs in the web interface, or under `~/.octoprint/logs` on your Pi
    extensions: ["log", "zip"]
    pattern: "^octoprint.*\.log"
    required: true
```

with `required`, `extensions` (limiting visible file extensions in the file picker via `accept` on the HTML `file` input) and `pattern` (validation of input file name server side) being optional would be absolutely amazing! 

Just being able to have a mandatory file upload would already help, even if extensions and pattern matching where left out. The problem I see is making people actually attach their logs. I've made do with a required checkbox that pretty much says "I have attached the required log below" but people will happily check that to proceed with issue submission but without actually uploading anything and I'm once again stuck without necessary information.

So, in order of priority, what I'd like to see is:

  1. a dedicated file input type that can be marked as required,
  2. allowing to optionally filter uploadable extensions as supported by the HTML `file` input's `accept` parameters,
  3. and also allowing to further filter files by being able to provide a regex pattern for the upload file name which would be evaluated server side and only mark the input as fulfilled (so block the form submission if it's required) if there's a match

That would remove the biggest pain point I currently still have after close to half a year of using issue forms with OctoPrint.
