### DISCUSSION TITLE
How to skip check if it was passed and the latest commit is irrelavant?

### DISCUSSION THREAD

**Discussion by terrynguyen255** [community/community#42920] [Actions]
### Select Topic Area

Question

### Body

Say my repo has 2 folders, `unit-tests` and `integration-tests`. 
I want to have a PR check: `unit-tests-check`. It should not be triggered when the folder `integration-tests` gets updated.
Yaml for `unit-tests-check` will look like this:
```yaml
name: unit-tests-check
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'integration-tests/**'
jobs:
  do-check:
    ....
```
This still come with many redundant check executions  when the PR is required to be up-to-date with the base branch.
For example, my PR has 2 new commits:
```
- Add changes #1 for unit-tests <- unit-tests-check was triggered and failed -> This is expected
- Add changes #2 for unit-tests <- unit-tests-check was triggered and passed -> This is expected
```

But now someone has pushed new code to the base branch which is all changes for `integration-tests`.  When I update my branch to the base branch, a new commit will be appended:
```
- Merge branch 'main' into my-branch
```
This new commit will trigger `unit-tests-check` one more time, and this is pointless because the new merge thing is just `integration-tests`, the latest check result for commit `Add changes #2 for unit-tests` should be reused.

Does anyone have any idea how to achieve this?
Thank you so much.
