### DISCUSSION TITLE
Add "Other:" option for dropdown

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#4296] [Projects and Issues]
When adding a dropdown menu to an issue form is it pretty common to provide an `Other` option since we can't think of all cases in categories like Operating systems, distribution type, etc.

The current problem with this is, that we have to create a separate input type field for the other option to let them fill it out, which may result in them not doing that at all. And forcing them to fill it out also feels wrong since it would require them to input a dummy-item to have it validated.

Because of those factors would I like to suggest a new option for the dropdown which auto-adds a `Other` option which, when clicked, would make a text field appear that the user can/should fill out based on whether the dropdown is required or not.

Example configuration:
```yaml
- type: dropdown
  attributes:
    label: "Operating System"
    description: |-
      What Operating System do you use?
      Make sure to also include the version in the text field below.
    multiple: false
    with_other: true # The new option which would add an "Other" option
    options:
      - "Windows"
      - "Mac"
      - "Linux"
```

Assuming the user would now select "Other" and input "Ubuntu" in the appearing field, would it look like this in the final issue

### Operating System
Other: Ubuntu

----
Perhaps to further customize the option could the dropdown's "options" section support a way to include a text field depending on the option?

F.e.
```yaml
- type: dropdown
  attributes:
    label: "Operating System"
    description: |-
      What Operating System do you use?
      Make sure to also include the version in the text field below.
    multiple: false
    options:
      - label: "Windows"
        fields:
        - placeholder: "Version"
      - label: "Mac"
        fields:
        - placeholder: "Version"
      - label: "Linux"
        fields:
        - placeholder: "Distribution"
        - placeholder: "Version"
      - label: "Other"
        fields:
        - placeholder: "Operating System"
```

This would add a text field for the version whenever you select the OS, and also adds an additional field for the distribution when Linux was selected.
A mix of both (with and without this fields option) should be supported so that you can fine-tune when a field should be displayed and required to fill out.

I can understand that this will put a lot of complicated work on making it doable and I don't expect this to be worked on in the near future or even at all.
