### DISCUSSION TITLE
[Issue Forms] Strange render error without a clear help about why this happens.

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#4297] [Projects and Issues]
I encounter a strange rendering issue with the issue forms which is weird.

The error states: `YAML error: (): did not find expected key while parsing a block mapping at line 43 column 5. Learn more.`

However, checking line 43 myself do I see nothing out of the ordinary ([Link](https://github.com/Andre601/JDA/blob/feature/use-issue-forms/.github/ISSUE_TEMPLATE/bug_report.yml#L43)) and it should even be valid syntax from what I know, considering I just created an issue form template with similar attributes on another repository with 0 issues.

I'm not sure what is wrong here or why it does this and the error isn't helping that much either.

On another note would I want to point out that the "Learn more" text links to the old(?) page about issue forms, which I assume is no longer the go-to place to get information from, so it should be updated

**Comment by wojtekmaj** [comment]
I have also encountered similar error.

> YAML error: (): did not find expected key while parsing a block mapping at line 16 column 7. Learn more. 

My YML:

```yml
name: 🚀 Feature request
description: I have a great idea for this project
labels:
  - enhancement
body:
  - type: checkboxes
    attributes:
      label: Before you start - checklist
      options:
        - label: I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
          required: true
        - label: I have checked if this feature request is not already reported
          required: true
  - type: textarea
    attributes:
      label: Description
      description: 'Describe what the problem is. Example: _I'd like to add a feature that […]_'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: |
        Describe the solution you'd like.

        Example:
          - Add a `foo` flag that, when toggled, enables the feature.
  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternative solutions or features you've considered, if any.
  - type: textarea
    attributes:
      label: Additional information
      description: If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

```

Interestingly, changing

```diff
-     description: 'Describe what the problem is. Example: _I'd like to add a feature that […]_'
+     description: Describe what the problem is.
```

fixed the error.
