### DISCUSSION TITLE
Ownership transfer - Error: Unable to resolve actions. Repository not found

### DISCUSSION THREAD

**Discussion by korthout** [community/community#43111] [Actions]
### Select Topic Area

Bug

### Body

Ownership of my action https://github.com/korthout/backport-action was recently transferred from  https://github.com/zeebe-io/backport-action. For most users, the redirection works fine but some users report the following error in their workflow runs:

>Error: Unable to resolve actions. Repository not found: zeebe-io/backport-action.

Example workflow that fails for some users:
```yaml
steps:
  - uses: actions/checkout@v3
  - uses: zeebe-io/backport-action@v1-rc1
```

For others, this works fine.
