### DISCUSSION TITLE
Get commits sha when limiting concurrency

### DISCUSSION THREAD

**Discussion by filipgolonka** [community/community#43123] [Actions] [answered]
### Select Topic Area

Question

### Body

Hey!

I have following workflow:
```
name: Limit concurrency

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}

jobs:
  hello:
    runs-on: [ubuntu]
    steps:
      - run: echo "${{ toJSON(github.event) }}"
```

Then I am pushing three commits (separate git push commands):
```
abc123 - HEAD
abc1234 - HEAD~1
abc12345 - HEAD~2
```

The run for `abc12345` starts, the run for `abc1234` is cancelled (because of concurrency) and the run for `abc123` is queued. However, when it is executed, I can see that `github.event.before` contains `abc1234` but I'd like it to be `abc12345` (because it is the last commit with executed workflow). 

Any ideas about how to tackle this?

**Comment by filipgolonka** [comment]
Tried also with running:
```
steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git diff --name-only HEAD~
      - run: git diff --name-only HEAD^
```

but the output does not contain file names of all the files that were changed.

**Comment by bukowskiadam** [comment, marked as answer]
For people that would find this thread and want a solution - we have solved it using gh-cli.

But it'd be far easier if we'd get that in the `github.event` 🤷🏻‍♂️

```yml
  steps:
    - name: Get commit SHA for last successful deploy
      id: last-successful-deploy-sha
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        value=$(gh run list -w "${{ github.workflow }}" --json status,conclusion,headSha -q '[.[] | select(.conclusion == "success" and .status == "completed")] | first | .headSha')
        echo "::set-output name=value::$value"
    - run: | # echo just for the showcase. Do something that needs the previous successful build commit hash
       echo ${{ steps.last-successful-deploy-sha.outputs.value }}..${{ github.event.after }}
      id: run
      shell: bash
```
