### DISCUSSION TITLE
Access to github context by a reusable workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#43131] [Actions]
### Select Topic Area

Question

### Body

According to the [docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows):

> When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow. The called workflow is automatically granted access to github.token and secrets.GITHUB_TOKEN. For more information about the github context, see "[Context and expression syntax for GitHub Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)."

However, the following invocation errors out:

```yaml

  set-tag:
    name: set the build branch and image tag
    needs:
      - set-ref
    uses: MyOrg/my-repo/.github/workflows/reusable.yaml@master
    with:
      push_to_prd: ${{ inputs.push_to_prd }}
      tag: ${{ inputs.manual_version }}
      ref: ${{ needs.set-ref.outputs.ref }}
      event: ${{ github.context }}
```

due to this line

```
 event: ${{ github.context }}
```

Any ideas?
