### DISCUSSION TITLE
How to investigate Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.

### DISCUSSION THREAD

**Discussion by krasi-georgiev** [community/community#43153] [Actions]
### Select Topic Area

Question

### Body

```
name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Test
        run: go test ./... -race
```

```
env GO111MODULE=on go run build/ci.go test ./frontier/... -race
>>> /opt/hostedtoolcache/go/1.19.4/x64/bin/go test -p 1 ./frontier/... -race
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/russross/blackfriday/v2 v2.1.0
?   	github.com/ethereum/go-ethereum/frontier/builder	[no test files]
ok  	github.com/ethereum/go-ethereum/frontier/bundlepool	0.151s
ok  	github.com/ethereum/go-ethereum/frontier/cache	0.083s
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
FAIL	github.com/ethereum/go-ethereum/frontier/coordinator	0.001s
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
FAIL	github.com/ethereum/go-ethereum/frontier/ethapi	0.001s
?   	github.com/ethereum/go-ethereum/frontier/interfaces	[no test files]
?   	github.com/ethereum/go-ethereum/frontier/nodeconnect	[no test files]
?   	github.com/ethereum/go-ethereum/frontier/relay	[no test files]
?   	github.com/ethereum/go-ethereum/frontier/testing	[no test files]
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
FAIL	github.com/ethereum/go-ethereum/frontier/tracker/head	0.001s
ok  	github.com/ethereum/go-ethereum/frontier/worker	0.086s
FAIL
```

this is a flaky test which never fails locally, but fails quite often in the gihtub actions CI

Any pointers how to investigate.

If I click to rerun the test it almost always passes on the second run.
