### DISCUSSION TITLE
Pass array as argument to reusable actions.

### DISCUSSION THREAD

**Discussion by terabytesoftw** [community/community#43201] [Actions]
### Select Topic Area

github actions

### Body

I have the following `packages` array, how can i pass it to a reusable github actions, local_path and split_repository can have different values.

Thank you.

```yml
jobs:
  split:
    runs-on: ubuntu-latest

    name: repository-${{ matrix.package.split_repository }}

    strategy:
      matrix:
        # define package to repository map
        package:
          -
            local_path: model
            split_repository: model
```

**Comment by airtower-luna** [comment]
Values passed to actions are passed as strings, so you'll need to convert the array to one and parse it in the action. The easiest way is probably to use the built-in [`toJSON()`](https://docs.github.com/en/actions/learn-github-actions/expressions#tojson) function, like so:

```yaml
- uses: your/action@version
  with:
    array: ${{ toJSON(matrix.package) }}
```

How to best parse the JSON data inside your action depends on how your action is written. There's the `fromJSON()` function built into Actions, and (hopefully) native functions depending on the programming language you use.
