### DISCUSSION TITLE
How can I properly catch status code from python script called at job?

### DISCUSSION THREAD

**Discussion by sofiamsa** [community/community#43338] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi! 
I am running my workflows with a wrapper for pycodestyle scan and once my script finishes the job at github actions just does not seems to take the status code properly.  I am using a sys.exit(exit_code) to finish my wrapper and I just get to the job catching a non zero value. (My definition is OK = 0.
Does anyone know how to manage the job to catch my wrapper status code? 
This is how I am calling my job
```
  python_syntax_check:
    runs-on: svos_runner
    if: ${{ contains(github.event.head_commit.message, '[scripts]') ||
            contains(github.event.head_commit.message, '[py]') || 
            contains(github.event.head_commit.message, '[Scripts]') }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run pycodestyle scanner
      uses: ./ci_cd/jobs/tests_templates/scans/pycodestyle/
      with:
        scripts: --commited
```
![image](https://user-images.githubusercontent.com/81657545/210668011-aef34b96-cd44-4042-91cc-69502cb59a50.png)
