### DISCUSSION TITLE
Checks in a PR get removed if a subsequent commit doesn't trigger the same workflows due to path filters

### DISCUSSION THREAD

**Discussion by tommymonk** [community/community#43391] [Actions]
### Select Topic Area

Product Feedback

### Body

I would like to retain or accumulate checks that run against all push events on a branch for the PR.

Currently the latest push wipes out the previous checks and replaces with checks that happen to match the files changed since the previous push.

For example, consider the following workflows;

```
name: "Workflow A"

on:
  push:
    paths:
       - 'src/Project A/**'
...
```

```
name: "Workflow B"

on:
  push:
    paths:
      - 'src/Project B/**'
...
```

- create a branch feature/myexample
- create a pull request for this branch
- push a commit with a change to "src/Project A/file-a.txt" - this will result in a check for "Workflow A" on the "Checks" tab on the PR
- push a commit with a change to "src/Project B/file-b.txt" - this will result in a check for "Workflow B" on the "Checks" tab on the PR, but the check for "Workflow A" disappears

It looks like this is expected behavior - the "Checks" tab only shows checks that were triggered by the most recent push, but because there are path filters on the workflows it results in some checks being removed if the path filters don't match the files changed in the most recent commit.

This can lead to situations where a PR can be approved even though initial checks failed.
