### DISCUSSION TITLE
When a Github Actions workflow fails, can I notify multiple recipients via email?

### DISCUSSION THREAD

**Discussion by abhi12ravi** [community/community#43415] [Actions]
### Select Topic Area

Question

### Body

By default, only the person who triggers the workflow or the person setting up the workflow gets an email notification on job failure. 

Docs: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs 

There is a workaround by adding an extra step (listed below) in the workflow, it claims to send the notification to multiple recipients, but this requires me to store my email username and password as a secret on GitHub, which I don't prefer to do. 

Extra step: https://stackoverflow.com/questions/62304258/github-actions-notifications-on-workflow-failure/67265461#67265461

I have to send the failure notification to my team of 4. Any ideas on tackling this problem would be appreciated!

**Comment by sunitaguptavertex** [comment]
I have similar requirement. Were you able to solve this issue?

**Comment by karna41317** [comment]
Any updates on this ?

**Comment by cywier** [comment]
I need this too.

**Comment by fabiobsantosprogrow** [comment]
This feature was required even nowadays!
Notification settings an option to put all teams or manage this on repo settings.
This information is very importante to leads and devops teams to solve issues and track activity.

**Comment by tt-rkim** [comment]
+1, multiple people work on pipelines

**Comment by Keshapally** [comment]
+1 waiting for any solutions from GitHub

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by joshjohanning** [comment]
By default, GitHub Actions notifies the actor (person who initiated the run) - assuming they haven't tweaked their notification settings. A user can opt in / out of these Action failure notifications.

You can use an Action from the GitHub Actions marketplace, but you would need SMTP credentials: https://github.com/marketplace?type=actions&query=email

There are cloud services, like Mailgun or Sendgrid, that you can also use to facilitate email sending.

---

You can also set up [Teams](https://github.com/integrations/microsoft-teams) or [Slack](https://github.com/integrations/slack) integration to post to a channel the results of a job. This is how I most commonly see it at customers.

---

As another workaround option, you can create a new issue / issue comment / comment to a PR and `@mention` the team you want to mention, and provide a link to the workflow that is failing. Something like this:

Like this: 

```yml
  - uses: actions/create-github-app-token@v1
    id: app-token
    with:
      app-id: ${{ vars.APP_ID }}
      private-key: ${{ secrets.PRIVATE_KEY }}

- name: create issue comment with failure
  run: | 
     # update 123 with the issue number you are commenting to
     gh issue comment 123 -R my-org/my-repo --body "@myorg/myteam: ***Workflow failure*** [View workflow run for details](${{ github.repository.html_url }}/actions/runs/${{ github.run_id}})"
  env:
    GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
```

You do have to use a GitHub app or personal access token to @ mention a team though (the `${{ github.token }}` will not work).

**Comment by jonahgreenthal** [comment]
@joshjohanning This is such a common use case (notifying a team rather than one specific person) that it should be supported "out of the box" rather than relying on community extensions that are relatively intensive to set up.

**Reply by joshjohanning** [reply]
I did edit my commend above to show how you could post a comment to an issue that would tag a team.

I agree it is additional legwork, but that is the only option right now.

**Reply by joshjohanning** [reply]
You can also set up [Teams](https://github.com/integrations/microsoft-teams) or [Slack](https://github.com/integrations/slack) integration @jonahgreenthal to post to a channel the results of a job. This is how I most commonly see it at customers.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Reply by jonahgreenthal** [reply]
This is still about a significant issue that has not been satisfactorily resolved.

**Comment by armyost** [comment]
I'm using Google Chat notification. I think there are other notification steps for various platform.


```
      # Workflow complete Notification
      - name: Google-Chat-Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Result
          url: ${{ env.GOOGLE_CHAT_URL }}
          status: ${{ job.status }}
        if: ${{ always() }}
```

**Comment by herryanu** [comment]
Yes, by using the mail action or configuring third-party services, you can send failure notifications to multiple recipients via email.
Discover the latest APK apps and games for Android. [Read more](https://apkmobss.com/toca-life-world-mod-apk/) to explore the best selections and enjoy endless entertainment.

**Comment by PaulRBerg** [comment]
Any ETA for when this basic functionality will be supported?

**Comment by shayki5** [comment]
+1

It's super basic feature!

**Comment by aking-ed** [comment]
Yes, I am surprised this can't be done out of the box. we have a nightly job, and it is just random who gets notified about its failure (just whoever happened to merge in the most recent PR). not intuitive at all!

**Comment by theasky** [comment]
+1

**Comment by DellaBitta** [comment]
+1

**Comment by JPGlaser** [comment]
Vocalizing this again that it needs to be a feature. We have a daily cron task that is done through actions and it is using a user in our org to email, but not the person triggering it. Making this feature would solve it.

~ Joe G.

**Comment by jgoodheart** [comment]
+1

**Comment by oxidsimongassenschmidt** [comment]
A failed GitHub action should be able to notify a specific group of emails - all maintainers - not just the one that last touched it. 
Yes, there are solutions to trigger these notifications, but I would really like the notifications to be done in the same way as the current one, so that one person is not notified twice.

**Comment by egrosspietsch-fds** [comment]
+1

**Comment by ImpossibleShape** [comment]
+1

**Comment by alice-finidori** [comment]
+1

**Comment by ACBullen** [comment]
+1

**Comment by dev-aravind** [comment]
+1

**Comment by drogozhnikov-fi** [comment]
+1

**Comment by wjkoh** [comment]
+1

**Comment by sandeep5234** [comment]
+1

**Comment by SC6333** [comment]
+1

**Comment by f-skold** [comment]
+1
Is this still missing? It would be quite simple to solve.

A simple key on the topl level of the YAML file: "on-failure.email-notification" taking a list of email adresses would solve this.
When it would be ok to also add similkar keys for jobs and steps:

on-failure.email-notification
jobs.<job_id>.on-failure.email-notification
jobs.<job_id>.steps[*]..on-failure.email-notification

See https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions for workflow syntax

**Comment by maxlep** [comment]
+1

**Comment by om-kmezmacs** [comment]
+1

**Comment by dweflen** [comment]
+1

**Comment by rv-jsharkey** [comment]
+100

**Comment by zetzet** [comment]
+1

**Comment by piotrekkr** [comment]
I'm using GitHub Actions daily for more than four years and my experience is that they do not care about normal user feedback and needs. I can see some enterprise "features" added from time to time but nothing needed or useful to the community. So do not put much hope in them.

There are some common workarounds to the missing notifications feature like:
1. I you have multiple jobs in a workflow, add notification job as last job that `needs` other jobs and then run it on [`if: failure()`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#failure). This will execute this job if any of needed jobs failed. There you can use `curl`, some script or action to send notification to selected people.  
2. If you have only one job in workflow you can add a last step with notification logic that would run also on `if: failure()`. 
3. There are also [webhook events](https://docs.github.com/en/webhooks/webhook-events-and-payloads) and you could send event on workflow run to some external endpoint and handle notification there.

**Comment by rocarrillos** [comment]
+1 can't believe there isn't a simple way to do this

**Comment by PaulRBerg** [comment]
You can [here](https://github.com/sablier-labs/lockup/blob/462c063b258b6855b3a45f5264ef154d06bcf67f/.github/workflows/ci-deep.yml#L78-L89) see an example of how we implemented this using the [rtCamp/action-slack-notify](https://github.com/rtCamp/action-slack-notify) action:

```yaml
  notify-on-failure:
    if: failure()
    needs: ["lint", "build", "test-unit", "test-integration", "test-invariant", "test-fork"]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Send Slack notification"
        uses: "rtCamp/action-slack-notify@v2"
        env:
          SLACK_CHANNEL: "#ci-notifications"
          SLACK_MESSAGE: "CI Workflow failed for ${{ github.repository }} on branch ${{ github.ref }} at job ${{ github.job }}."
          SLACK_USERNAME: "GitHub CI"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
```

**Comment by PsiKai** [comment]
I'm leaving an organization where I've configured many cron schedule workflows.  Right now, I'm the maintainer as well, so it makes sense that I get the email on failure.  When I leave, these workflows will just silently fail with no notification system.

Please Github, just a basic feature to configure a mailing list for actions failures!

**Comment by poslogica** [comment]
I require this in my workflows too.
Would be good that GH supports this natively!

**Comment by JonJagger** [comment]
+42

**Comment by zsiegel92** [comment]
+1

**Comment by Harrysharmax** [comment]
Use a Team Messaging Platform
How it works:

1. Generate a Webhook URL: In your Slack or Teams channel, create an "Incoming Webhook." This gives you a unique, secret URL.
2. Store the URL as a Secret: In your GitHub repository, go to Settings > Secrets and variables > Actions and add the webhook URL as a secret (e.g., SLACK_WEBHOOK_URL).
3. Add a Step to Your Workflow: Add a final step to your job that only runs on failure using the if: failure() condition.
Here's an example for Slack:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build steps
        run: |
          # Your build and test commands go here
          # Let's assume this step fails
          exit 1

      - name: Notify team on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C12345678' # Or your channel name
          slack-message: "🚨 Workflow failed! Name: ${{ github.workflow }}, Job: ${{ github.job }}. See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} # Or use SLACK_WEBHOOK_URL with a different action/method
```
or you can Use a Dedicated Email Service 📧
If you prefer email, use a transactional email service like SendGrid or Mailgun instead of your personal account. These services use revocable API keys for authentication, which is much more secure than a password.

How it works:

1. Sign up for a service (most have a generous free tier).
2. Get an API key and add it to your GitHub secrets.
3. Use a GitHub Action like dawidd6/action-send-mail configured to use your service's API key.

**Reply by shayki5** [reply]
> Use a Team Messaging Platform How it works:
> 
> 1. Generate a Webhook URL: In your Slack or Teams channel, create an "Incoming Webhook." This gives you a unique, secret URL.
> 2. Store the URL as a Secret: In your GitHub repository, go to Settings > Secrets and variables > Actions and add the webhook URL as a secret (e.g., SLACK_WEBHOOK_URL).
> 3. Add a Step to Your Workflow: Add a final step to your job that only runs on failure using the if: failure() condition.
>    Here's an example for Slack:
> 
> ```
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Run build steps
>         run: |
>           # Your build and test commands go here
>           # Let's assume this step fails
>           exit 1
> 
>       - name: Notify team on failure
>         if: failure()
>         uses: slackapi/slack-github-action@v1.26.0
>         with:
>           channel-id: 'C12345678' # Or your channel name
>           slack-message: "🚨 Workflow failed! Name: ${{ github.workflow }}, Job: ${{ github.job }}. See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
>         env:
>           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} # Or use SLACK_WEBHOOK_URL with a different action/method
> ```
> 
> or you can Use a Dedicated Email Service 📧 If you prefer email, use a transactional email service like SendGrid or Mailgun instead of your personal account. These services use revocable API keys for authentication, which is much more secure than a password.
> 
> How it works:
> 
> 1. Sign up for a service (most have a generous free tier).
> 2. Get an API key and add it to your GitHub secrets.
> 3. Use a GitHub Action like dawidd6/action-send-mail configured to use your service's API key.

But it's Slack, not email... for Slack there is official GitHub App..

**Comment by iainross** [comment]
+one million

How is this not out of the box?

**Comment by APEX-SAID-SHAMKHALI** [comment]
+1 Please, this feature would be very useful, specially in enterprise scenarios.

**Comment by CodyCBakerPhD** [comment]
+1 Asking for this yet again! Would simplify many of our workflows

**Comment by lukegregorio** [comment]
+! again, this would be so useful for us

**Comment by beiglboe** [comment]
Come on, please @github

**Comment by Suhas-Chandrashekar** [comment]
Hello All, I also had similar requirements. However, I used Sendgrid and is working fine and meeting my Requirements. Sharing it here if it helps others too. 

(You may ignore if it doesn't help in this context)

- You may add multiple email ID's as TO Recipients &
- You may add multiple email ID's as CC Recipients.
- Also, you may specify the Distribution List too.

```
   notify-on-failure:
      runs-on: ubuntu-latest
      needs: [<Add/Link_your_previous_jobs_name>, <Add/Link_your_previous_jobs_name>]
      if: always() && (<Add/Link_your_previous_jobs_names> == 'failure' || <Add/Link_your_previous_jobs_names> == 'failure')

      steps:
        - name: Send failure notification via SendGrid
          env:
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          run: |
            CURRENT_DATE=$(date '+%d-%m-%Y')
            
            curl -X POST https://api.sendgrid.com/v3/mail/send \
              -H "Authorization: Bearer ${SENDGRID_API_KEY}" \
              -H "Content-Type: application/json" \
              -d @- <<EOF
            {
              "personalizations": [
                {
                    "to": [
                      {"email": "email-1"},
                      {"email": "email-2"}
                    ],
                    "cc": [
                      {"email": "email-1"},
                      {"email": "email-2"}
                    ],
                  "subject": "<Subject_Goes_here>"
                }
              ],
              "from": {
                "email": "<FROM_Email_Address>",
                "name": "<FROM_Email_Name>"
              },
              "content": [
                {
                  "type": "text/plain",
                  "value": "<Content/Body_Goes_here>"
                }
              ]
            }
            EOF

```
Thanks & Regards,
Suhas Chandrashekar

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Reply by jonahgreenthal** [reply]
This is not dormant. It's still a badly needed missing feature.

**Comment by Arthi4M** [comment]
+1 Would be super helpful to have this feature

**Comment by DmytroKryvoruchenko** [comment]
+1, it would be nice to have it out of the box

**Comment by Qhtani90** [comment]
This is madness 🤣🤣
Gays who tell me what they want and how I publish results or all things is completely madness [Partnership-Proposals.md](https://github.com/user-attachments/files/24800153/Partnership-Proposals.md)





[Partnership-Proposals.md](https://github.com/user-attachments/files/24800033/Partnership-Proposals.md)

**Comment by esiebert** [comment]
+1. I'm having to implement workarounds because of the lack of this feature

**Reply by PaulRBerg** [reply]
we all have to

**Comment by ydubov** [comment]
+1
BTW as a work around, I tried subscribing to Actions notifications by email, in aim to receive **all** action results. 
Strangely, I only receive an email if the run passes, **but not if if fails** - in that case, only the faceless account that triggered it gets notified, super unhelpful!

**Comment by GuilhermeH98** [comment]
+1

**Comment by Gecko51** [comment]
Few options that don't involve stuffing SMTP creds into secrets.

Cleanest for a team of 4 is to route through a chat webhook (Slack, Discord, Teams) and let the chat tool handle the fanout to email/mobile however each person prefers:

```yaml
- name: Notify on failure
  if: failure()
  uses: slackapi/slack-github-action@v1
  with:
    webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
    webhook-type: incoming-webhook
    payload: |
      {"text": "Workflow ${{ github.workflow }} failed on ${{ github.ref }}"}
```

Webhook URL is the only secret you store.

If it has to be email specifically, use a transactional service (SendGrid, Mailgun, SES) and store an API key instead of your personal email password. SendGrid's free tier covers 100 emails a day which is plenty for CI. The API key is scoped to sending mail only so even if leaked it can't touch your inbox.

Third option with zero extra services: file a GitHub issue on failure and assign the team. Every assignee gets notified through whatever channel they configured:

```yaml
- uses: actions/github-script@v7
  if: failure()
  with:
    script: |
      github.rest.issues.create({
        owner: context.repo.owner,
        repo: context.repo.repo,
        title: `CI failed on ${context.sha.substring(0, 7)}`,
        body: `Run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
        assignees: ['user1', 'user2', 'user3', 'user4']
      })
```

For a team of 4, Slack or Discord webhook is far and away the lowest friction, would go with that.
