### DISCUSSION TITLE
Implement the CICD to a bastion server

### DISCUSSION THREAD

**Discussion by gautam071** [community/community#43449] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi 

I am trying to implement the CI/CD in my GitHub repo using GitHub actions, but the server Arch is based on the bastion server and we need to jump from one server to another for the deployment. Is there any way I can implement this using GitHub actions  

### The basic CICD with YAML file 
```
name: Staging Deployment
on:
  push:
    branches: [develop]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to staging
      uses: appleboy/ssh-action@master
      env:
        SSH_BUILD_DIRECTORY: ${{ secrets.SSH_BUILD_DIRECTORY }}
        SSH_POST_BUILD_SCRIPT: post_build_script.sh
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
         whoami
         pwd
   ```
