### DISCUSSION TITLE
How to group steps in a GitHub action workflow file?

### DISCUSSION THREAD

**Discussion by Xwilarg** [community/community#43467] [Actions] [answered]
### Select Topic Area

Question

### Body

Hey,

I'm looking to "group" steps in a CI file
Basically I want to do something like that:
```
- if: ${{ matrix.os == 'windows-latest' }}
  { Do a many steps specific to Windows }
- if: ${{ matrix.os == 'ubuntu-latest' }}
  { Do a many steps specific to Linux }
```

Is there a way to do that?

**Comment by jongwooo** [comment]
@Xwilarg Please refer to this [code](https://github.com/nektos/act/blob/master/.github/actions/choco/action.yml). I hope it will be helpful to you:)

**Comment by spenserblack** [comment, marked as answer]
My first instinct is that steps that should be grouped together go into different jobs. Could you explain why wouldn't this work for you?
```yaml
jobs:
  foo:
    runs-on: ${{ matrix.os }}
    steps:
      # your steps for the OS
```
Are the steps completely different depending on OS? If so, why not make them separate jobs?

**Reply by Xwilarg** [reply]
Basically I want to build and run test for all OS but then make a Linux and Windows release (which I can only do on the respective OS), I also have the fact that only Linux upload the coverage to codacy (because there is no need to do it twice)

**Reply by spenserblack** [reply]
If possible, sharing your repository might be helpful.

Are the actual build and release commands much different between OSes?
Since I don't know your build tools, this is just guesswork, but it sounds like you could do this:

```yaml
# Triggered on tag pushed or release created?
jobs:
  build:
    name: Build, Test, and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      # this depends on what you're building
      EXE_FILENAME: foo-${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
    steps:
      - uses: actions/checkout@v3
      - run: build-tool -o $EXE_FILENAME   # depending on your build tool
      - run: test-tool  # again, depending on your project
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.EXE_FILENAME }}
      - name: Upload Coverage
        if: matrix.os == 'ubuntu-latest'
        run: coverage-uploader  # not familiar with codacy since I've used codecov :)
```
Though, depending on your release strategy, it might make more sense to separate your release creation and tests into separate workflows. I usually run builds and tests on PRs and pushes to `main`/`master`/`trunk`/etc., and a build and release when a tag is pushed.

**Reply by Xwilarg** [reply]
Sorry I can't share the full repository since it's work related but as an example, here are the steps specific to the Ubuntu CI:
```yml
- name: Copy coverage
  run: sh copy_coverage.sh
- name: Upload coverage to Codacy
  uses: codacy/codacy-coverage-reporter-action@master
  with:
    project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    coverage-reports: coverage.xml
- name: Publish Linux 64 bits
  run: dotnet publish -c Release -r linux-x64 -o Release-Linux XXXX/XXXX.csproj
- name: Publish macOS 64 bits
  run: dotnet publish -c Release -r linux-x64 -o Release-OSX XXXX/XXXX.csproj
- name: Give Linux executable permissions
  run: chmod +x ./Release-Linux/XXXX
- name: Rename macOS executable
  run: mv ./Release-OSX/XXXX ./Release-OSX/XXXX.app
- name: Give macOS executable permissions
  run: chmod +x ./Release-OSX/XXXX.app
- uses: actions/upload-artifact@v2
  with:
    name: Linux
    path: ./Release-Linux
    retention-days: 1
- uses: actions/upload-artifact@v2
  with:
    name: OSX
    path: ./Release-OSX
    retention-days: 1
```

**Reply by spenserblack** [reply]
Are there any significant steps previous to that snippet, or is `Copy coverage` the first step? Would you be OK if that was excluded from the "group" into a separate job (since you only want to run that for one OS)?
Here's a basic idea of what I'm thinking:
```yaml
jobs:
  coverage:
    # ...
  publish:
    needs: coverage  # only if you really want to force publish to wait until coverage is complete
    env:
      OUTPUT_FILENAME: Release-${{ matrix.os == 'macos-latest' && 'OSX' || 'Linux' }}  # expand to include Windows
      OUTPUT_EXT: ${{ matrix.os == 'macos-latest' && '.app' || '' }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - run: dotnet publish -c Release -r linux-x64 -o Release XXXX/XXXX.csproj  # linux-x64 would probably need to be an environment variable, too
      - name: Give ${{ matrix.os }} executable permissions  # Is this needed? Do uploaded artifacts retain permissions?
        run: chmod +x ./Release/XXXX
      - name: Rename ${{ matrix.os }} executable
        run: mv ./Release/XXXX "$OUTPUT_FILENAME/XXXX$OUTPUT_EXT"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ env.OUTPUT_FILENAME }}
          retention-days: 1
```
