### DISCUSSION TITLE
Struggling with diacritics within windows self-hosted runner

### DISCUSSION THREAD

**Discussion by Juknum** [community/community#43462] [Actions]
### Select Topic Area

Question

### Body

Hi, I'm experiencing some issue with my workflow, it works perfectly fine when the given path does not have any accents / diacritics but whenever I change it with some accents, it fails, how can I escape those characters ? 

```yml
env:
  DOTNET: 7.0.x
  TAG_VER: v1.0
  APP_PATH: 'Y:\path\to\my\app\Réception\' # the 'é' is causing the issue :/
  USER: ${{ secrets.USER }}
  EMAIL: ${{ secrets.EMAIL }}
  TOKEN: ${{ secrets.TOKEN }}
```

This is the job step that fails
```yml
- name: Copy config files
      run: |
        cd "${{ env.APP_PATH }}"
        Get-ChildItem "${{ env.APP_PATH }}/Latest" -Filter *.config | Copy-Item -Destination "${{ env.APP_PATH }}/Releases/${{ env.TAG_VER }}-${{ needs.create_tag.outputs.SHORT_SHA }}" -Force -PassThru
```

I've tried to add `chcp 65001` before the `cd` command without success

PS: The workflow runs on a selft-hosted runner which is a Windows 2012 R2 Server
