### DISCUSSION TITLE
Conditional steps in composite actions

### DISCUSSION THREAD

**Discussion by yarnabrina** [community/community#43505] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

Hi,

I am exploring recently to learn Github actions. One of things I tried to do is basically if-else of steps, given the value of the inputs, using the `if` key. But it seems it's not being used correctly.

Here's my action:

```yaml
name: nox-tag-action-name
description: run nox tag
inputs:
  tag-name-input-identifier:
    description: name of nox tag
    required: true
  python-version-input-identifier:
    description: python version to run tag
    required: false
    default: none
runs:
  using: composite
  steps:
    - id: nox-step-identifier
      name: install nox
      run: python3 -m pip install nox
      shell: bash
    - id: tag-all-versions-step-identifier
      name: run provided nox tag for all configured python versions
      if: ${{env.PYTHON_VERSION}} == 'none'
      run: nox --tags ${{env.TAG_NAME}}
      shell: bash
      env:
        TAG_NAME: ${{ inputs.tag-name-input-identifier }}
        PYTHON_VERSION: ${{ inputs.python-version-input-identifier }}
    - id: tag-single-version-step-identifier
      name: run provided nox tag for provided python version
      if: ${{env.PYTHON_VERSION}} != 'none'
      run: nox --pythons ${{env.PYTHON_VERSION}} --tags ${{env.TAG_NAME}}
      shell: bash
      env:
        TAG_NAME: ${{ inputs.tag-name-input-identifier }}
        PYTHON_VERSION: ${{ inputs.python-version-input-identifier }}
```

Irrespective of my input value for `python-version-input-identifier`, both `tag-all-versions-step-identifier` and `tag-single-version-step-identifier` steps are run.

If someone can suggest what am I doing wrong, that'd be great. Thanks.

**Comment by matthewhawthorne** [comment]
Hi @yarnabrina,

It looks like you have a syntax error in the if statements and you will likely want to use the inputs.python-version-input-identifier instead of the env.PYTHON_VERSION in the if statement.

For conditional steps and jobs, you do not need to expand the variable. Instead, you can do:
```yaml
- id: tag-single-version-step-identifier
      name: run provided nox tag for provided python version
      if: inputs.python-version-input-identifier != 'none'
```

Here is an example workflow file:
```yaml
# This is a basic workflow to help you get started with Actions

name: Test conditionals

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      test_conditional:
        required: false
        default: none

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Conditional - Do not run
        if: inputs.test_conditional != 'none'
        run: echo "Conditional - this should not run"

      - name: Conditional - Run
        if: inputs.test_conditional == 'none'
        run: echo "Conditional - this should run"
        
      - name: Bad Conditional
        if: ${{inputs.test_conditional}} != "none"
        run: echo "Bad Conditional - this should not run"
```

Here is the workflow run results:
![image](https://user-images.githubusercontent.com/30942326/211081210-82af99e6-1c84-47aa-b772-74e2dbf145b6.png)

**Reply by yarnabrina** [reply]
Thanks for your answer.

May be I was not clear, I specifically wanted to try environmental variables to set the condition. But your answer helped me a lot, as it gave the idea that expansion was not mandatory. Didn't get that part, and just by changing to this worked as expected.

```yaml
if: env.PYTHON_VERSION != 'none'
```

**Comment by yarnabrina** [comment, marked as answer]
This is the final solution I ended up with, thanks to the suggestion by @matthewhawthorne 

```yaml
name: nox-tag-action-name
description: run nox tag
inputs:
  tag-name-input-identifier:
    description: name of nox tag
    required: true
  python-version-input-identifier:
    description: python version to run tag
    required: false
    default: none
runs:
  using: composite
  steps:
    - id: nox-step-identifier
      name: install nox
      run: python3 -m pip install nox
      shell: bash
    - id: tag-all-versions-step-identifier
      name: run provided nox tag for all configured python versions
      if: env.PYTHON_VERSION == 'none'
      run: nox --tags ${{env.TAG_NAME}}
      shell: bash
      env:
        TAG_NAME: ${{ inputs.tag-name-input-identifier }}
        PYTHON_VERSION: ${{ inputs.python-version-input-identifier }}
    - id: tag-single-version-step-identifier
      name: run provided nox tag for provided python version
      if: env.PYTHON_VERSION != 'none'
      run: nox --pythons ${PYTHON_VERSION} --tags ${{env.TAG_NAME}}
      shell: bash
      env:
        TAG_NAME: ${{ inputs.tag-name-input-identifier }}
        PYTHON_VERSION: ${{ inputs.python-version-input-identifier }}
```
