### DISCUSSION TITLE
Reusable Workflow Concurrency

### DISCUSSION THREAD

**Discussion by kylevillegas93** [community/community#43510] [Actions]
### Select Topic Area

Question

### Body

What are the limitations to reusable workflow concurrency? 

Right now we have several service deployment workflows that use the same reusable workflow to run database migrations.  However, if more than 2 of the services are deploying at the same time, only 2 will succeed and the others will be skipped altogether. 

Is this intended behavior? Any way around this?

**Comment by vitalykarasik** [comment]
Can you share more details regarding your workflows?
I use reusable workflow and haven't seen such a limitation.

**Comment by PedroDRodrigues** [comment]
It is possible that the behavior you are experiencing is intended, as GitHub Actions has a default concurrency limit of two for workflow runs that use the same name and repository. This means that if you have multiple workflow runs that use the same name and are triggered in the same repository at the same time, only two of them will run concurrently, and the rest will be queued until a run completes.

If you would like to increase the concurrency limit for your workflow runs, you can do so by setting the jobs.<job_id>.runs-on property to a virtual machine with a higher concurrency limit. For example, you could set jobs.<job_id>.runs-on: ubuntu-latest to increase the concurrency limit to 10.

Alternatively, you can use the GITHUB_RUN_ID environment variable to generate a unique name for your workflow run. This will allow multiple instances of the same workflow to run concurrently, as they will be treated as separate runs with different names.

It's worth noting that increasing the concurrency limit for your workflow runs may result in increased resource usage and potential costs, so you should carefully consider your needs and resources before making any changes.

**Comment by vitalyk-multinarity** [comment]
Finally I tested calling reusable workflow in parallel - i called it 4 times and didn't see any issues.


```
run-reusable-1:
    needs: setup-job
    uses: ./.github/workflows/reusable-workflow.yml
    secrets:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  
  run-reusable-2:
    needs: setup-job
    uses: ./.github/workflows/reusable-workflow.yml
    secrets:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}      
........
```
