### DISCUSSION TITLE
Installing Private Package in Actions

### DISCUSSION THREAD

**Discussion by awesometown** [community/community#43521] [Actions]
### Select Topic Area

Question

### Body

I'm in the process of migrating our private node packages from npmjs to GitHub Packages. I have publishing working fine and am now trying to consume those packages in other projects.

Locally, I have a PAT configured in my .npmrc file and `npm i` works fine. I am trying to get my GitHub Actions CI build to work, though, and running into issues.

tl;dr: **is it currently possible to use GITHUB_TOKEN to install private npm packages in a GitHub Actions Workflow, or do I still need to configure a PAT?** It seems like recent features added to the registries should allow use of GITHUB_TOKEN, though the docs are kind of ambiguous.

There is lots of older information on the web that say you cannot use GITHUB_TOKEN and must use a PAT in Actions. However, [this page](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages) contains a section that reads:

> For registries that support granular permissions, if your workflow is using a personal access token to authenticate to a registry, then we highly recommend you update your workflow to use the GITHUB_TOKEN.

NPM registries support granular permissions, and as far as I can tell I have followed [the instructions](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#ensuring-workflow-access-to-your-package) to allow access to my packages from the repository that contains the workflow that wants to consume them. When I try to run `npm ci` in my workflow, I receive the error 

```
npm ERR! 403 403 Forbidden - GET https://npm.pkg.github.com/download/@my-org/my-package/<version>/<sha> - Permission permission_denied: read_package
```

An example workflow is below.

```
name: Build
on:
  push:
env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
      - name: Install Dependencies
        run: npm ci
```

Should this work (and I should keep trying to figure out what I've misconfigured)? Or have I misconstrued what the granular permissions feature allows and need to just set up a PAT?
