### DISCUSSION TITLE
Tasks progress circle is illegible in dark theme

### DISCUSSION THREAD

**Discussion by Craftplacer** [community/community#4353] [Projects and Issues]
When looking through the issues list, a little circle shows progress of the tasks mentioned inside an issue, although it isn't really discernible.

Screenshot:
![image](https://user-images.githubusercontent.com/22963120/123539210-d5cc2b80-d738-11eb-80de-dec9dae8dcb7.png)

WebAIM tests:
![image](https://user-images.githubusercontent.com/22963120/123539215-df559380-d738-11eb-9819-ab5484783728.png)

A color like `#4184E4` (the color used for the most inner edge of selected input controls) works better:
![image](https://user-images.githubusercontent.com/22963120/123539300-5428cd80-d739-11eb-974f-82c475672b1e.png)

A temporary fix (user style) would be this:
```css
[data-color-mode="dark"][data-dark-theme*="dark"], [data-color-mode="light"][data-light-theme*="dark"]:root {
    --color-border-info: #4184E4;
}
```
