### DISCUSSION TITLE
why github action task in pining to exact git commit version/number instead of release tag?

### DISCUSSION THREAD

**Discussion by SyedsImran** [community/community#43578] [Actions]
### Select Topic Area

Question

### Body

why is the GitHub action task is pining to the exact git commit version/number instead of the release tag?

We have a GitHub action task(APIsec Scan).
We are trying to add this task through Get started with GitHub Actions search field. But after selecting this task we are getting a git commit version/number instead of the release tag v1.0.6 we specified while releasing the task.
![Githubaction1](https://user-images.githubusercontent.com/100760767/211163621-a05334a9-dda7-4b55-a9a8-699e84086d84.png)
![githubaction2](https://user-images.githubusercontent.com/100760767/211163639-642a1462-ce68-4448-9735-6be3bb4fd190.png)

```
  Trigger_APIsec_scan:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
       - name: APIsec scan
         uses: apisec-inc/apisec-run-scan@f748a240d69ca6cd7e9532fd0a47bec4ccd6a73c
         with:
          # The APIsec username with which the scans will be executed
          apisec-username: ${{ secrets.apisec_username }}
          # The Password of the APIsec user with which the scans will be executed
          apisec-password: ${{ secrets.apisec_password}}

```

While the same task added from the marketplace search field is working as expected.

![githubaction3](https://user-images.githubusercontent.com/100760767/211163737-a722f5a1-2828-472a-b42c-c7676065e5fa.png)

Is got something to do with this message we are getting when adding task from the Get started with GitHub Actions search field?

```
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

```
![githubaction5](https://user-images.githubusercontent.com/100760767/211163776-4d01de7c-a3cf-4641-897c-77a7161cc79c.png)

So, why is the GitHub action task is pining to the exact git commit version/number instead of the release tag?
