### DISCUSSION TITLE
Configuring dependabot to ignore transitive dependencies for npm

### DISCUSSION THREAD

**Discussion by cressie176** [community/community#43627] [Code Security]
### Select Topic Area

Question

### Body

I maintain a number of open source Node.js modules. When npm publishes a module it excludes package-lock.json, so there is very little point having dependabot create PRs for transitive dependencies. I would like to reduce the amount of noise in my projects by disabling this.

The dependabot config suggests I could do this as follows...

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    allow:
      - dependency-type: 'direct'
```

However dependabot is still generating the PRs.

ChatGPT has suggested the following instead, 

```yml
version: 2
update_configs:
  - package_manager: "npm"
    transitive: false
```

But neither the update_configs or transitive options are documents. How can I configure dependabot to ignore transitive dependencies?

Thanks in advance,

Steve
