### DISCUSSION TITLE
Multiple events of the same type in a single workflow

### DISCUSSION THREAD

**Discussion by ventsyv** [community/community#43742] [Apps, API and Webhooks]
### Select Topic Area

Question

### Body

The documentation is not clear if this is possible or not:

```
on:

  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - develop
      
  pull_request:
    types [synchronize]
    branches:
      - main
      - develop
    paths: ['**.h', '**.cpp', '**.hpp', '**.yaml', '**CMakeLists.txt', '**Makefile', '**.spec', '**.py', '**Dockerfile', '**conanfile.txt']
```

I want the workflow to be ran when the request in initially created, but syncs should only trigger if there is a code change. Changes to text documents, scripts, etc should not trigger.

Currently the github editor indicates a syntax error on the second pull_request with a "dupliated key" message. I tried combining them into one but then I got "duplicated keys" on the types key.

Additionally, I have a "on push" event and I'm surprised that with the addition of the push_request the workflow is not triggered twice - once by "on push" and another by "pull_request.sync". Is one preempting the other ?? I wasn't able to find anything about that in the documentation.
