### DISCUSSION TITLE
Issue Forms: Allow checkboxes groups to be required

### DISCUSSION THREAD

**Discussion by nathanlesage** [community/community#4378] [Projects and Issues]
Hey all,

immediately tried out the new feature and it's definitely amazing for encouraging inexperienced people to open bug reports on GitHub! I'm looking forward to radio groups, but one thing I figured already is the following:

Single checkbox items can be marked as "required" but not the whole group. However, there are situations where you want people to be able to simply tick off a few things, but they need to _at least choose one single item_. So it would be basically an "at least one item"-requirement.

My use case:

I want to enable both inexperienced users as well as experienced developers to open bug reports and not exclude someone. Since my app is cross-platform and -architecture, I chose to include three checkboxes for macOS, Linux, and Windows as well as one group for ARM/Intel. 99% of the bug reports will obviously just have one checkbox checked each, but in case someone had the ability to reproduce the bug both on macOS and Windows for example (e.g. home office + in regular office), this would be important info to have.

It would be a great improvement to an already great feature!

**Comment by ArminJo** [comment]
First, thanks for the marvelous issue forms 🥇

I want to support the above request, since checkboxes are more eyecatching and better readable, especially when including links, than a select object.
e.g. https://github.com/ArminJo/Talkie/issues/new?assignees=&labels=&template=bug_report.yml&title=%5BBug%5D%3A+
```
  - type: checkboxes
    id: Version
    attributes:
      label: The library version you are working with.
      description: |
        You may use the latest repo version, which is not (yet) released, but may contain some bugfixes.
        Your current library version number can be found with *Arduino > Tools > Manage Libraries..* (Ctrl+Shift+I)
        and is printed to serial output at the startup of every example.
      options:
        - label: I use the [latest Arduino library version](../releases) and verified this!
        - label: I use the latest repo version ([download link](../archive/master.zip)) and verified this!
    validations:
      required: true
```
