### DISCUSSION TITLE
Cannot pass sensitive `env` or `options` to service containers

### DISCUSSION THREAD

**Discussion by penchef** [community/community#43794] [Actions] [answered]
### Select Topic Area

Bug

## Problem

Cannot pass `secrets` as the [`env`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idenv) or [`options`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idoptions) parameter for `jobs.<job_id>.services` or `jobs.<job_id>.container`

Often the `env` parameters contain sensitive information, e.g API keys, etc. and GH Actions logs the `docker run` command incl all parameters:

<img width="1035" alt="Screen Shot 2023-01-09 at 18 36 05" src="https://user-images.githubusercontent.com/9286268/211442225-aa84da13-3804-4e7d-8481-d356d0f0af8b.png">

In my case, I'm trying run E2E tests of our FE app and need to launch a server image as a service. Our serve requires a bunch of secrets passed as `env` variabes.

## Bug

When passing a secret, `${{ secrets.FOO }}` as the value for [`env`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idenv) or [`options`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idoptions),  I get a [syntax error](https://github.com/penchef/service-container-bug/actions/runs/3879265633):

 
<img width="685" alt="Screen Shot 2023-01-09 at 18 27 01" src="https://user-images.githubusercontent.com/9286268/211441062-9db8c849-602b-462c-b5e3-77bda5532b23.png">

## Example Workflow
```yml
name: Run container
on:
  push:
jobs:
  build:
    name: Service Container example
    runs-on: ubuntu-20.04
    services:
      mongodb:
        env: ${{ fromJSON(secrets.BAR) }}
        options: ${{ secrets.FOO }}
        image: mongo:5.0.14
        ports:
          - 27017:27017
    steps:
      - name: ping
        run: |
          echo "not working"
```

**Comment by jongwooo** [comment]
@penchef I hope this helps:)

```yml
env: 
  BAR: ${{ fromJSON(secrets.BAR) }}
```

**Reply by penchef** [reply]
thanks @jongwooo for the suggestion! 


this indeed works with the `env` parameter, but I can't get `options` to work with secrets 🤔: 

```yml
  # works
  build:
    name: Service Container example
    runs-on: ubuntu-20.04
    needs: setup
    services:
      mongodb:
        env:
          FOO: ${{ secrets.BAR }}
        image: mongo:5.0.14
        ports:
          - 27017:27017
    steps:
```

unfortunatly, I can't solve my real life problem: it's not feasible to list each `ENV` `key: ${{ secrets.value }}` pair since there are too many. I've been trying to read them in a previous job, which sets a secret. 

The alternative I thought could work is to construct an equivalent `options` string in a previous job, but `options` cannot be a secret either :/


This is what I've got to work, however, the `env` is not obfuscated...

```yml
name: Run container
on:
  push:
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      container_env: ${{ steps.container_env.outputs.container_env }}
      container_options: ${{ steps.container_env.outputs.container_options }}
    steps:
      - name: Set output
        id: container_env
        run: |
          # in real life, I'm reading the key:values from an .env file which is stored as secret
          echo "container_env={\"foo\":\"bar\"}" >> $GITHUB_OUTPUT
          echo "container_options=\"-e FOO=bar\"" >> $GITHUB_OUTPUT
         # I've also tried to add-mask to the values of container_env and container_options but no luck...
  build:
    name: Service Container example
    runs-on: ubuntu-20.04
    needs: setup
    services:
      mongodb:
        env: ${{ fromJSON(needs.setup.outputs.container_env) }}
        options: ${{ needs.setup.outputs.container_options }}
        image: mongo:5.0.14
        ports:
          - 27017:27017
    steps:
...
```

The real life example not working

```yml
# doesn't work
name: Run container
on:
  push:
jobs:
  # real life setup
  setup: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: xxxxxx
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 1200
      - name: Set AWS password
        id: set-password
        env:
          GH_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB_ACTIONS }}
        run: |
          ECR_PASSWORD=$(aws ecr get-login-password)
          gh secret set ECR_PASSWORD --body $ECR_PASSWORD --repos repo/xxxx
     - name: Set Server Env secrets
        id: server_env
        env:
          GH_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB_ACTIONS }}
          SERVER_ENV: ${{ secrets.SERVER_ENV }} # a base64 encoded .env file
        run: | 
          echo $SERVER_ENV | base64 --decode > .env
          SERVER_ENV_JSON=$(python3 .github/workflows/lib/env2json .env | jq -c)
          gh secret set SERVER_ENV --body $SERVER_ENV --repos repo/xxxx
     - name: Alternative approach: construct options string as secrets
        id: server_options
        env:
          GH_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB_ACTIONS }}
          SERVER_ENV: ${{ secrets.SERVER_ENV }}
        run: |
          echo $SERVER_ENV | base64 --decode > .env
          OPTIONS=$(grep -v '^#' .env | sed '/^[[:space:]]*$/d' | awk '{ print "-e \""$0"\""}' | tr '\n' ' ')        
          gh secret set server_options --body $OPTIONS --repos repo/xxxx
        # this ^ constructs "-e "FOO=bar" -e "BAR="foo" -e ... " options string
  build:
    name: Service Container example
    runs-on: ubuntu-20.04
    needs: setup
    services:
      cove-server:
        image: XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/repo:tag
        credentials:
          username: AWS
          password: ${{ secrets.ECR_PASSWORD }}
          env: ${{ fromJson(secrets.server_env) }}
         # alternative also doesn't work either
         # options: ${{ secrets.server_options }}
        ports:
          - 1337:1337
```



This is all I've tried:


```yml
name: Run container
on:
  push:
jobs:
  build:
    name: Service Container example
    runs-on: ubuntu-20.04
    env:
      secret_env: ${{ fromJSON(secrets.BAR) }}
      secret_options: ${{ secrets.FOO }}
    services:
      mongodb:
        env: ${{ env.secret_env }}
        options: ${{ env.secret_options }}
        image: mongo:5.0.14
        ports:
          - 27017:27017
    steps:
      - name: ping
        run: |
          echo "not working"
```
<img width="717" alt="Screen Shot 2023-01-10 at 09 35 11" src="https://user-images.githubusercontent.com/9286268/211609018-ef5598d1-f8ac-42dd-af6a-7f3d086ba508.png">


```yaml
  ....
 build:
    name: Service Container example
    runs-on: ubuntu-20.04
    needs: setup
    env:
      secret_env: ${{ fromJSON(secrets.BAR) }}
      secret_options: ${{ secrets.FOO }}
    services:
      mongodb:
        options: ${{ env.secret_options }}
        image: mongo:5.0.14
        ports:
          - 27017:27017
     ....
```
<img width="718" alt="Screen Shot 2023-01-10 at 09 36 32" src="https://user-images.githubusercontent.com/9286268/211609343-2f406b59-263e-4338-a04f-5e47691f453c.png">

### try hard coding a map:
```yml
...
    services:
      mongodb:
        env: >
          {
            "FOO": "bar"
          }
        image: mongo:5.0.14
        ports:
          - 27017:27017
    steps:
...
```
<img width="724" alt="Screen Shot 2023-01-10 at 09 38 27" src="https://user-images.githubusercontent.com/9286268/211609794-325ced20-bdfd-4810-8e02-a75107509f86.png">
