### DISCUSSION TITLE
Issue forms: Add ability to make fields depend on others

### DISCUSSION THREAD

**Discussion by AlCalzone** [community/community#4386] [Projects and Issues]
We have several questions in our bug report template where we ask the user a yes/no question and then ask them to give additional details if "yes" was chosen. For example:
https://github.com/zwave-js/node-zwave-js/issues/new?assignees=&labels=&template=bug_report.yml
--> Did you change anything? 
--> If yes, what did you change?

It would be good to have a way to make the "If yes, what did you change?" only appear and be required when the user chose "yes" under "Did you change anything?".

**Comment by Shinigami92** [comment]
Yeah it would be cool to have something like an `if` condition that can reference another field by `id`

I have a condition that I would like to ask if the next step contains vue sfc or just pug content and would like to render different markdown based on that
https://github.com/prettier/plugin-pug/blob/044341c5f2e7c46a4ae5ff39fe2819c7169fe0d3/.github/ISSUE_TEMPLATE/bug-report.md#L33

**Comment by boriel** [comment]
It would be nice to also be able to describe a set of values to be in a drop down according to the value of other field (and not only one, but several of them). Something like:

```yaml

body:
  - type: dropdown
    attributes:
      label: Type
      id: food-type   # A unique id to be referenced later
      description: Food Type
      options:
        - omnivore
        - vegetarian
        - vegan
      default: 0
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Food
      id: dish
      description: Specific dish
      options:
        food-type.omnivore:
           - "eggs"
           - "pork
           - "fish"
           - "lettuce"
           - "tomato"
           - "cheese"
        food-type.vegetarian:
           - "eggs"
           - "lettuce"
           - "tomato"
           - "cheese"
        food-type.vegan:
           - "lettuce"
           - "tomato"
           - "tofu"
      default: food-type.vegan.0
    validations:
      required: true
```

Whenever the user toggles the `food-type` option, the available drop-down list updates showing only available options.
(e.g. for this specific example, if the user selects `vegan`, the 2nd drop-down list will narrow-down automatically to 3 options only).

This is very similar to what is proposed at #6890
