### DISCUSSION TITLE
Trigger push on branch doesn't work when the branch still needs to be published

### DISCUSSION THREAD

**Discussion by steini44as** [community/community#43882] [Actions]
### Select Topic Area

Bug

### Body

Hi
I have the following triggers:
```
on:
  push:
    branches:
      - 'feature/*'
      - 'patch/*'
      - 'release/*'
      - 'main'
    paths-ignore:
      - 'pack'
      - 'managedservicesolution/Azure-Pipelines.yml'
```

When I create a new branch feature/xxx from the develop branch and publish that branch from my local repo to the remote repo, the trigger isn't triggered. It only triggers when I change something AFTER the branch is already published. Is there a way to trigger the workflow on the publishing of the branch or is this a bug or is this normal behaviour?

Thank you.
