### DISCUSSION TITLE
Is it possible to run check on PR comment

### DISCUSSION THREAD

**Discussion by 5er9e1** [community/community#43957] [Actions]
### Select Topic Area

Question

### Body

We have three branches: `feature`, `main` (default), `develop`

Also we have CI Tests that are running in GitHub Actions when Pull Request `feature → develop` is created (pretty common case I guess). But for some reason some of the parameters are always different. Let's say that we have a default URL `http://test1.com` changing sometimes to `http;//test2.com`.

So, if the default test with `test1` failed, I want to re-run the test with `test2`. I am trying to use the `issue_comment` event and check for its message. Let's say it will be `use http;//test2.com`. Where the second word is a parameter.

```yaml
on:
  issue_comment:
    types: [created]

jobs:
  ...
  if: ${{ (github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, 'use ') }}
  steps:
    - name: get URL env 
      run: |
        echo "${{ github.event.comment.body }}" | awk '{print"URL="$2}' >> ${GITHUB_ENVS}

    - name: run tests with URL
      run: |
        echo "${URL} will be used"
        ...
```

But here is a big problem that this event is not triggered inside this PR, but triggered out of the default branch (`main` in my case).

That causes two sub-problems:
1. Nothing will be triggered if we don't have the workflow file inside the `main` branch (but we are trying to merge `feature → develop`  and `main` does not matter at all)
2. Even if we have the workflow file inside the `main` branch, and even if we `checkout` necessary branch manually, running Action is not viewable under PR. It will be run as separated Action and PR test check will be failed with ❌ mark.

So, how to re-run (or run a new check) by PR comment like it happens when a new commit is added to `pull_request` (`synchronize` action type)?
