### DISCUSSION TITLE
GHES system-wide PAT for github.com?

### DISCUSSION THREAD

**Discussion by ijlyttle** [community/community#43969] [Enterprise]
### Select Topic Area

Product Feedback

### Body

In the [setup-python action](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#avoiding-rate-limit-issues), you describe a workaround for GHES users to generate a github.com PAT, then use it as:

```yaml
- name: Set up Python
  uses: actions/setup-python@4
  with:
    python-version: 3.8
    token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
```
 
This is effective, but it requires each user or organization on GHES to generate such a token for themselves. Could it be possible (maybe it is already possible) for a minimally-powerful token to be made available for *all* users of a GHES system?

Thanks!
