### DISCUSSION TITLE
Possible to share outputs from nested reusable workflows upstream to the calling workflow?

### DISCUSSION THREAD

**Discussion by mbraunwart** [community/community#44007] [Actions]
### Select Topic Area

Product Feedback

### Body

In this scenario, I have calling Workflow A, Reusable Workflow B, and Reusable Workflow C. I am looking to send outputs upstream from nested reusable workflows to be shared within the calling workflows up the chain.

Resuable Workflow C outputs content, that Reusable Workflow B wants to send directly upstream to the calling workflow.

`calling_workflow_a.yml`
```yaml
on:
  push:
jobs:
  output-job:
    uses: org/repo/.github/workflows/resuable_workflow_b.yml
    outputs: 
      - output-parameter
  job2:
    needs: output-job
    steps:
      - run: ${{ needs.output-job.outputs.output-parameter }}
```
`reusable_workflow_b.yml`
```yaml
on:
  workflow_call:
    outputs: #Ideally
      output-parameter: 
        value: ${{ jobs.job-name.outputs.output }}
jobs:
  job-name:
    name: output upstream
    uses: org/repo/.github/workflows/reusable_workflow_c.yml@main
```

`reusable_workflow_c.yml` just outputs some standard content that can be captured by the calling workflow as per the [documentation](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow)

Does anything like this exist or is potentially in development?

Thank you!
