### DISCUSSION TITLE
Azure pipeline wasn't triggered when the PR move from draft to open

### DISCUSSION THREAD

**Discussion by zhebinliu** [community/community#44049] [Pull Requests]
### Select Topic Area

Question

### Body

I am experiencing an issue with the Azure pipeline wasn't triggered when the PR move from draft to open
Here is the yaml configuration I used:

```
trigger: none

pr:
    drafts: false
    branches:
        include:
            - main
            - hotfix/*
```

does anyone has idea what is going wrong with it?
