### DISCUSSION TITLE
Remove `JAVA_HOME` from being automatically added to env

### DISCUSSION THREAD

**Discussion by 526avijitgupta** [community/community#44101] [Actions]
### Select Topic Area

Question

### Body

I'm setting up java in a job and then executing a docker image in the next step with an environment variable using the `env` field:
```yaml
  test-local:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        continue-on-error: true
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - uses: "docker://<link_to_image>"
        name: Run Tests
        env:
          ENV_TAGS: '@local-xyz-service'
```

I can see in the job output that `JAVA_HOME` and `JAVA_HOME_11` are also being exported to the environment automatically:
<img width="178" alt="Screenshot 2023-01-12 at 12 59 34" src="https://user-images.githubusercontent.com/7583815/212061160-adec6fc2-1875-4318-b966-fedfdefe2e6a.png">

This is causing issues while running this docker step:
<img width="509" alt="Screenshot 2023-01-12 at 13 02 33" src="https://user-images.githubusercontent.com/7583815/212061653-d33794ac-d6ac-45ad-96a5-8243877ddfa9.png">

 I want to unset or prevent `JAVA_HOME` from being automatically added to the env for this job. Is there a way to do this? 

Additionally, I have confirmed that if I remove the `setup-java` step then the environment does not contain the `JAVA_HOME` variable and the docker command runs as expected.

**Comment by tonnyavery** [comment]
Probably related to this https://github.com/actions/runner/issues/1126
Face the same problem and didn't find a solution yet

**Comment by airtower-luna** [comment]
Does it work if you set `JAVA_HOME` to empty for the step, e.g. something like this:

```yaml
      - uses: "docker://<link_to_image>"
        name: Run Tests
        env:
          ENV_TAGS: '@local-xyz-service'
          JAVA_HOME: ''
```

However, I wonder why you want to call `setup-java` at all if you then use Java from a container. :wink:
