### DISCUSSION TITLE
GitHub Actions: If a Check Run name changes, it keeps being required

### DISCUSSION THREAD

**Discussion by oscard0m** [community/community#4411] [Actions]
Scenario: Github Action with a matrix of node versions (full GitHub Action [here](https://github.com/octokit/webhooks.js/blob/12a266a34ad4781975038a8a78908481460f5fce/.github/workflows/test.yml)):

```
test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 10
          - 12
          - 14
    name: Node ${{ matrix.node }} 
```

Is there a way to make a Status Check as required by _job-id_ instead of job-name, so the change of the name is transparent to a Repository and its branch protection rules?

We would like to prevent, when **Node 16** appears and Node 10 sunsets, for example, to have to unmark as required in all repositories and mark **Node 16** as required.

![image](https://user-images.githubusercontent.com/2574275/123876961-98d08680-d93c-11eb-9a9d-2ed3e0e8374c.png)

Continuing the discussion from [GitHub Community](https://github.community/t/if-a-check-run-name-changes-it-keeps-being-required/167669)
