### DISCUSSION TITLE
My subsequence GitHub action is not being triggered

### DISCUSSION THREAD

**Discussion by albatarnik** [community/community#44127] [Actions]
### Select Topic Area

Question

### Body

I have this GitHub action that creates a new release using semantic release when I push to a branch which works but the subsequence gituhb action that should trigger on a new release/ prerelease doesn't work. 

First GitHub action ( triggers ) 
```

name: building 

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - next
      - beta
      - alpha
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The second Github action ( Doesn't trigger ) 

```
name: building docker test

# Controls when the workflow will run
on:
  release:
    types: [published, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
```
