### DISCUSSION TITLE
Check if reusable workflow was called from a successful or a failed invoking workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#44141] [Actions]
### Select Topic Area

Question

### Body

I am calling a reusable workflow passing to it explicitly the success or failure of the invoking workflow as follows:

```yaml
  send-slack-success:
    if: success()
    needs:
      - set-tag
    uses: MyOrg/MyRepo/.github/workflows/reusable@master
    with:
      image_name: my-image
      image_tag: ${{ needs.set-tag.outputs.tag }}
      slack_channel: my-channel
      success: true

  send-slack-failure:
    if: failure()
    needs:
      - set-tag
    uses: MyOrg/MyRepo/.github/workflows/reusable@master
    with:
      image_name: my-image
      image_tag: ${{ needs.set-tag.outputs.tag }}
      slack_channel: my-channel
      success: false
```

Then in the reusable workflow, I am doing stuff based on the value of the `{{ inputs.success }}`.

Is there a better way / pattern to get this information on the reusable workflow? (i.e. if the invoking failed or succeeded?)
