### DISCUSSION TITLE
GHES NTP time sync in Air Gapped Azure Cloud

### DISCUSSION THREAD

**Discussion by aslafy-z** [community/community#44150] [Enterprise]
### Select Topic Area

Bug

### Body

I'm deploying GHES to Azure Cloud in a (almost) Air Gapped vnet with only some websites allowed (github.com for instance).

To finish the configuration, I had to configure the NTP sync. However, Azure does not provide any internal endpoint that can act as a NTP server. Instead, they offer a PTP source (see https://learn.microsoft.com/en-us/azure/virtual-machines/linux/time-sync#chrony). [GitHub however only prompts for NTP servers](https://user-images.githubusercontent.com/8191198/212181515-72635a79-4959-491f-b635-c9d1ed456072.png) and support no other protocol. 

My current workaround is to manually hack into the chrony configuration and set the Azure recommended PTP settings. 
However, chrony configuration is automatically reset on each GHES upgrade so I had to add the patch into a crontab job for it to survive upgrades...

Here's my ansible task:
```
- name: Install the NTP configuration reconciliation cronjob
  ansible.builtin.cron:
    name: "fix-ntp"
    minute: "*/5"
    job: "grep -q 'refclock PHC /dev/ptp0 poll 3 dpoll -2 offset 0' /etc/chrony/chrony.conf || { sudo sed -i -n -e '/^refclock/!p' -e '$arefclock PHC /dev/ptp0 poll 3 dpoll -2 offset 0' /etc/chrony/chrony.conf && sudo systemctl restart chronyd && sudo chronyc -a makestep; } >/dev/null 2>&1"
    user: root
  become: true
```

This "works" for the moment but looks pretty ugly to me. 

**Please sync-up between Azure and GitHub so Azure customers are able to use the Cloud Provider provided clock synchronization protocol, you're the same company at the end!**

I've been pushing the topic for some time within a support ticket, I get the same answers every time: `GitHub only support NTP servers. Please configure NTP servers.`.

Here's the ticket ID if some good GitHuber found some time to check that issue: `Unable to activate GitHub Connect #1877706`.
