### DISCUSSION TITLE
In `$GITHUB_STEP_SUMMARY`, enclosing content in a multi-step `<details>` tag will place the content outside of that tag.

### DISCUSSION THREAD

**Discussion by korosuke613** [community/community#44185] [Actions]
### Select Topic Area

Product Feedback

## Summary
In `$GITHUB_STEP_SUMMARY`, enclosing content in a multi-step `<details>` tag will place the content outside of that tag. The raw markdown had content inside `<details>`.
There is a workaround, but it is a bit inconvenient 🥲 

## Background

I want to be able to dynamically enclose $GITHUB_STEP_SUMMARY in a `<details>` tag so that the display is not too large. So I separate the steps.

## Actual
https://github.com/korosuke613/playground/actions/runs/3908450732#summary-10622165892

### workflow
For simplicity, we use `env` to set the variables in the `DETAILS`.

```yaml
name: multi step enclose details to step summary

on:
  push:
    paths:
      - .github/workflows/step-summary-details.yaml

env:
  DETAILS: "true"

jobs:
  step-summary-details-actual:
    runs-on: ubuntu-latest
    steps:
      - name: Output to step summary [title]
        run: |
          echo "# Actual" >> $GITHUB_STEP_SUMMARY

      - name: Output to step summary [details start tag]
        if: env.DETAILS == 'true'
        run: |
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary>detail</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Output to step summary [body]
        run: |
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo '{ "test": "bar" }' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Output to step summary [details end tag]
        if: env.DETAILS == 'true'
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
```

### created summary

https://user-images.githubusercontent.com/20027695/212237572-436ffbdd-3a79-4b94-88a7-e8c8a05d7075.mov

### raw markdown
Click `View raw markdown`.

https://github.com/korosuke613/playground/actions/runs/3908450732/jobs/6678608781/summary_raw

````markdown
# Actual

<details>
<summary>detail</summary>


foo
```json
{ "test": "bar" }
```


</details>
````

## Expected
https://github.com/korosuke613/playground/actions/runs/3908450732#summary-10622165968

### created summary

https://user-images.githubusercontent.com/20027695/212237612-5e31bff4-11c4-45f7-8be8-0e94b141b821.mov

## Note

I was able to work around this problem by compiling the output to a separate file and then appending it to `$GITHUB_STEP_SUMMARY`.

<details>

<summary>workflow</summary>

```yaml
  step-summary-details-workaround:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        run: |
          # Create a path to save the summary.
          echo "summary=${{ runner.temp }}/summary.md" >> $GITHUB_OUTPUT

      - name: Output to step summary [title]
        run: |
          echo "# Workaround" > ${{ steps.setup.outputs.summary }}

      - name: Output to step summary [details start tag]
        if: env.DETAILS == 'true'
        run: |
          echo "<details>" >> ${{ steps.setup.outputs.summary }}
          echo "<summary>detail</summary>" >> ${{ steps.setup.outputs.summary }}
          echo "" >> ${{ steps.setup.outputs.summary }}

      - name: Output to step summary [body]
        run: |
          echo 'foo' >> ${{ steps.setup.outputs.summary }}
          echo '```json' >> ${{ steps.setup.outputs.summary }}
          echo '{ "test": "bar" }' >> ${{ steps.setup.outputs.summary }}
          echo '```' >> ${{ steps.setup.outputs.summary }}

      - name: Output to step summary [details end tag]
        if: env.DETAILS == 'true'
        run: |
          echo "" >> ${{ steps.setup.outputs.summary }}
          echo "</details>" >> ${{ steps.setup.outputs.summary }}

      - name: Output to step summary
        shell: bash
        run: |
          cat ${{ steps.setup.outputs.summary }}
          cat ${{ steps.setup.outputs.summary }} >> $GITHUB_STEP_SUMMARY
```

</details>
