### DISCUSSION TITLE
Is there an same function of success()/failure() for "post" javascript actions?

### DISCUSSION THREAD

**Discussion by krutoo** [community/community#44245] [Actions]
### Select Topic Area

Question

### Body

Hi, i want to write simple notifier GitHub action that sends messages when workflow passed successfully or failed with an error

I want to determine that any previous step of a job fails.

According to this docs i can make it in workflow yaml:
https://docs.github.com/en/actions/learn-github-actions/expressions#failure

How can i make it via javascript post action?

In my `action.yml`:
```yml
# ...
runs:
  post: 'post.js'
```

In my `post.js`:
```js
import * as core from '@actions/core';

async function run() {
  try {
    // i want to determine previous steps failure or success here
  } catch (error) {
    // ...
  }
}

run();
```

**Comment by MostafaWaleed0** [comment]
You can use the `if` condition in your notifier GitHub Action step to determine if any previous step of a job has failed. You can use the `failure()` context expression in the `if` condition to check if the previous step(s) failed.

Here's an example:

```yaml
name: Notifier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        echo "Running tests..."
        exit 1

    - name: Notify
      if: failure()
      uses: <user-name>/notifier-action@v1
      with:
        message: 'Workflow failed with an error.'

    - name: Notify
      if: success()
      uses: <user-name>/notifier-action@v1
      with:
        message: 'Workflow passed successfully.'
```
In this example, the notifier action is defined twice - once for success and once for failure. If any previous step of the job fails, the `if: failure()` condition will trigger the notifier action to send a message with the text "Workflow failed with an error." If all previous steps of the job succeed, the `if: success()` condition will trigger the notifier action to send a message with the text "Workflow passed successfully."

**Reply by krutoo** [reply]
@mostafawaleed3 Yes, thank you for the answer. At the moment i did it. 
But this is a rather verbose option, is it possible to somehow reduce the amount of code?

**Reply by Leksat** [reply]
Faced the same issue. Here's what I do.

Workflow:
```yml
    steps:

      - name: My action
        uses: My/Action@v1
        with:
          success_env_var: 'ALL_GOOD'

      - name: Do work
        run: do_work && echo "ALL_GOOD=1" >> $GITHUB_ENV
```

In action's `runs.post`:
```ts
const isSuccess = core.getInput('success_env_var') in process.env;
```
