### DISCUSSION TITLE
IAC CODE SCANNING USING SNYK

### DISCUSSION THREAD

**Discussion by shanumodi9** [community/community#44329] [Actions]
### Select Topic Area

Question

### Body

Run github/codeql-action/upload-sarif@v2
Error: Path does not exist: snyk.sarif
Error: Path does not exist: snyk.sarif
    at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:137:15)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:132:30)
    at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:46:47)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:6[8](https://github.com/shanumodi9/terraform-code-scanning/actions/runs/3918328460/jobs/6698646427#step:5:9):[9](https://github.com/shanumodi9/terraform-code-scanning/actions/runs/3918328460/jobs/6698646427#step:5:10))

**Comment by aeisenberg** [comment]
It looks like snyk is not producing a sarif file at the location you are expecting. Please make sure to configure snyk and ensure it is saving the file in the right location.

I can help more if you share your workflow file.

**Reply by VILLAN3LL3** [reply]
I'm getting the same error. Here is the content of my workflow file: https://github.com/orso-co/Orso.Arpa.Api/pull/775/files
The failing workflow: https://github.com/orso-co/Orso.Arpa.Api/actions/runs/5811862036/job/15756027311

Update: There is an error in the previous step:

> Could not detect supported target files in /github/workspace.
> Please see our documentation for supported languages and target files: https://snyk.co/udVgQ and make sure you are in the right directory.

**Reply by VILLAN3LL3** [reply]
I fixed the issue for my repo. You can find the working yml file here: https://github.com/orso-co/Orso.Arpa.Api/blob/develop/.github/workflows/snyk-security.yml

**Comment by cb-dcc** [comment]
I'm running into what is likely the same issue. The Snyk Github Action for IAC is not creating the snyk.sarif file. I have tried explicitly setting sarif: true to no avail. When I set json: true it generates the snyk.json file. I have tested this also with the Snyk Github Action for Docker for a different repo and have not encountered this issue. This snyk action still shows that it relies on actions/checkout@v2, it seems that it needs a little care from the team responsible for it.

**Reply by aeisenberg** [reply]
This is likely a problem with the snyk action. You would have more success if you raise an issue in their repository. [Here](https://github.com/snyk/actions) is their actions repository. It's not clear where you can raise support tickets, but there might be a link in their documentation.

**Reply by cb-dcc** [reply]
I've checked there, and there aren't any obvious ways to raise an issue. I've also reached out to get assistance from one of their technical engineers through our contact at work. I will update this thread once we have a workaround, or they implement a fix.

**Comment by cb-dcc** [comment]
@shanumodi9 While I realize it has been quite a while since you raised this issue, I have the official resolution from Snyk. According to Snyk's support team, and verified with my own github action/workflow implementation. The file and sarif arguments are required in order to rectify this issue. Note: This solution is not currently contained, or referenced, in their official Snyk Github Action documentation.
Please see below example:
```

name: Example workflow for Snyk Infrastructure as Code
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check IAC files for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
        with:
          file: . (This should be the paths in which to scan files with issues.)
          sarif: true
```
