### DISCUSSION TITLE
Automatically assign labels to issues created via Issue template based on combobox choices

### DISCUSSION THREAD

**Discussion by mobius1qwe** [community/community#44350] [Projects and Issues]
### Select Topic Area

Question

### Body

Is it possible to do either a Markdown (md) or YAML (yml) issue template with selectable options like the HTML <select> <option> tag that will automatically assign a label to that issue based on the option selected? I'm more inclined on thinking that could be possible with the new YAML template, the good ol' markdown one I believe would either be too much work or not possible.

Simple YAML template example
``` YAML
- type: dropdown
    id: OS
    attributes:
      label: "Operating System:"
      description: "Select the OS where the issue occurs."
      options:
        - Windows
        - Linux
        - Mac
```
I Imagine that on the options, adding a nested label : "" key under the option should do the trick, like this:
``` YAML
- type: dropdown
    id: OS
    attributes:
      label: "Operating System:"
      description: "Select the OS where the issue occurs."
      options:
        - Windows
          label: "os: windows"
        - Linux
          label: "os: linux"
        - Mac
          label: "os: mac"
```

Tried to edit but this inputbox doesn't allow code formatting it seems, text is all messy D':

**Comment by VincentLanglet** [comment]
I would expect something like
```
name: Bug Report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - name: Firefox
          labels: ['Firefox']
        - name: Chrome
          labels: ['Chrome']
        - name: Safari
          labels: ['Safari']
        - name: Microsoft Edge
          labels: ['Microsoft Edge']
```
