### DISCUSSION TITLE
Way to provide a YAML list for an action

### DISCUSSION THREAD

**Discussion by szepeviktor** [community/community#44358] [Actions]
### Select Topic Area

Question

### Body

```yaml
- name: "Validate XML files"
  uses: "actions/xml-validate/action.yml"
  filelist:
    - "first.xml"
    - "second.xml"
```

I'm trying to validate multiple XML files in an action.
Is there a way to provide file names in a YAML list instead of concatenating file names into a string?
