### DISCUSSION TITLE
Github App permissions to merge dependabot pull request

### DISCUSSION THREAD

**Discussion by Khaaz** [community/community#44510] [Actions]
### Select Topic Area

Question

## Context

I am trying to automate merging dependabot PR via a Github Action within an organisation.
I am using [this action](https://github.com/ahmadnassri/action-dependabot-auto-merge) with [this other action](https://github.com/tibdex/github-app-token) in order to impersonate my Github App.

I think that my github app has the correct permission in my organisation. When I created and installed it I made sure it had write access for Pull request and repository contents among other things.  

For context, here what my action looks like:
```yaml
name: Dependabot-merge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Generate GH token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 271330
          private_key: ${{ secrets.GH_APP_PKEY }}
          repository: ${{ github.repository }}
          permissions: >-
            {"contents": "write", "pull_requests": "write"}
      - uses: actions/checkout@v3
      - name: Automerge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ steps.generate_token.outputs.token }}
```

## My issue

However when my action runs: the github app comments `@dependabot merge` as it should (which mean it does generate the GH app token at least), but dependabot states that ` only users with push access can use that command.`.

I am not sure to understand how the whole permission process works for general use case and here specifically for dependabot. I even tried using the `permissions` field above and the default `secrets.GITHUB_TOKEN` but without any luck either.

Is it just not possible to have a GH App do such action? Am I doing something else wrong? Am I missing permissions somewhere or not correctly generating my GH App token?
