### DISCUSSION TITLE
paths-ignore seemingly not working

### DISCUSSION THREAD

**Discussion by tquid** [community/community#44625] [Actions]
### Select Topic Area

Question

### Body

I'm finding this action keeps firing even if I am changing only one file in `.github/workflows`. I've tried using the old fashioned `paths` instead of `paths-ignore`, and still it always runs. I've googled this for a while, and it seems like the answer is always that it's some kind of typo. I tested the path by copy-pasting to an `ls` command and it does show the files there. I would be very grateful for getting any understanding here.

```yaml
on:
  push:
    branches:
      - development
    paths-ignore:
      - ".github/workflows/**"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    paths-ignore:
      - ".github/workflows/**"
  ```

**Comment by mailman-2097** [comment]
```
on:
  push:
    paths-ignore:
      - 'azdo/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - 'azdo/**'
```
Same here does not work as expected.
