### DISCUSSION TITLE
Curly brackets are treated as a secret

### DISCUSSION THREAD

**Discussion by kirillmorozov** [community/community#44660] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi,

I'm having a problem with GitHub Actions.

I've written a python script that generates and outputs a matrix for the next job in JSON format but when I try to use this step's output I get the following warning:

> **prepare_matrix**
> Skip output 'matrix' since it may contain secret.

I've tried to debug it by printing the output instead of redirecting it to `$GITHUB_OUTPUT`. Here's what I saw in a log:

```
matrix=***"include": [***"serial_number": "12345", "vendors": ""***]***
```

I know that it should be:

```
matrix={"include": [{"serial_number": "12345", "vendors": ""}]}
```

because I've tested my script.

My question is why GitHub treats curly brackets as a secret?

Here's my job for the reference:

```yml
jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create_matrix.outputs.matrix }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Dump Credentials
        run: |
          cat > matrix_builder/credentials.json <<EOF
          ${{ secrets.GSHEET_PRIVATE_KEY }}
          EOF

      - name: Install Dependencies
        run: |
          pip install poetry
          cd matrix_builder
          poetry install --only main

      - name: Create Matrix
        id: create_matrix
        env:
          RANGE: "REDACTED"
          SPREADSHEET_ID: "REDACTED"
          CREDENTIALS: credentials.json
          QUERY: ${{ github.event.inputs.query }}
        run: |
          cd matrix_builder
          poetry run matrix_builder/main.py >> $GITHUB_OUTPUT
```
