### DISCUSSION TITLE
Accessing JSON outputs from a docker container action

### DISCUSSION THREAD

**Discussion by tho93** [community/community#44722] [Actions]
### Select Topic Area

Question

### Body

Hello all,

I am trying to access some JSON output from a workflow step all running in a composite action. When I echo the step output, I can see that there is indeed a JSON object:

```
# This is a private docker container action that sets a key-value pair via a Python script
- name: update version
  uses: ./internal-action
  id: update-version
- name: git commit/tag
  shell: bash
  run: |
    echo ${{ steps.update-version.outputs.version_map }}

Outputs:
[{env_instance: 0, curr_version: x.x.x, next_version: x.x.x}, {env_instance: 1, curr_version: x.x.x, next_version: x.x.x}]
```
The above step works, and I can see my nested JSON output. I want to pull the a specific key out of each list object. Following [these docs](https://docs.github.com/en/actions/learn-github-actions/expressions#object-filters), it seems like I should be able to do the following:

```
echo ${{ steps.update-version.outputs.version_map.*.curr_version }}
# outputs empty line
```

However, this leads to an empty output. I've tried wrapping the expression in `fromJSON`, then accessing the key, but no luck.

From [this discussion](https://github.com/orgs/community/discussions/44026), I tried wrapping the output in join(fromJSON()), with the following results:
```
${{ join(fromJSON(steps.update-version.outputs.version_map), ' ') }}
# outputs: Object Object Object Object Object


for obj in ${{ join(fromJSON(steps.update-version.outputs.version_map), ' ') }}; do
    echo pushing $obj
done
# outputs:
pushing Object
pushing Object
pushing Object
pushing Object
pushing Object
```

Grateful for any/all pointers/suggestions. Thanks!
