### DISCUSSION TITLE
Deploying a multi-module Java project to a Packages Maven repository using Actions.

### DISCUSSION THREAD

**Discussion by jonathanjuursema** [community/community#44788] [Actions]
### Select Topic Area

Question

### Body

Hey!

I'm working on switching over our builds from Jenkins to GitHub Actions, and I'm currently running into an issue that I have been unable to solve. Any input would be greatly appreciated!

**Context**
I'm trying to build and publish a Java package whose source code lives in a GitHub repository. The build is currently running just fine on GitHub managed runners, but I'm facing issues with publishing. The publish target as a Maven repository hosted by GitHub Packages in the same repo.

The "package" in this repo consists of a "parent package" (that contains no real code in itself) and multiple modules in subfolders, each with their own pom.xml. What we want to achieve is to upload each of those modules as a Maven package to the repo.

The workflow uses a custom settings.xml file (which I'll include below as well), because it not only needs to publish a private package to the repo that it's running in, it also needs to pull another private (Maven) package from a different repo in our org.

**Files**

In the details below you'll find what I think are the relevant files.

My workflow file looks like this (anonymized and shortened):

<details>

```yaml
name: Build an publish.

on:
  push:
    branches:
      - feature-branch

permissions:
  contents: read
  packages: write

jobs:

  build_deploy:
    name: Build an publish.
    runs-on: ubuntu-latest

    steps:

      - name: Check out code.
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Write custom Maven settings.xml
        run: cp settings.xml /home/runner/.m2/settings.xml

      - name: Debug settings.xml
        run: cat /home/runner/.m2/settings.xml

      - name: Maven build.
        run: mvn --batch-mode --update-snapshots --no-transfer-progress clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OTHER_REPO_PACKAGE_TOKEN: ${{ secrets.PULL_TOKEN_FOR_OTHER_REPO }}

      - name: Maven publish to GitHub Packages.
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

</details>

The `settings.xml` referenced in the workflow looks like this:

<details>

```xml
 <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>github</id>
      <username>${env.GITHUB_ACTOR}</username>
      <password>${env.GITHUB_TOKEN}</password>
    </server>
    <server>
      <id>github-self</id>
      <username>${env.GITHUB_ACTOR}</username>
      <password>${env.GITHUB_TOKEN}</password>
    </server>
    <server>
      <id>github-other</id>
      <username>${env.GITHUB_ACTOR}</username>
      <password>${env.OTHER_REPO_PACKAGE_TOKEN}</password>
    </server>
  </servers>
</settings>
```

</details>

The `pom.xml` of the Java module looks like this (anonymized and shortened):

<details>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.5</version>
    </parent>

    <name>Package Name</name>
    <url>http://www.org.com/</url>
    <groupId>com.org.department.commons</groupId>
    <artifactId>department-parent-pom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <!-- more (unrelated) properties -->
        <revision>2.83-SNAPSHOT</revision>
    </properties>

    <scm>
        <connection>scm:git:git@github.com:org/department-package.git</connection>
        <developerConnection>scm:git:git@github.com:org/department-package.git</developerConnection>
        <url>https://github.com/org/department-package</url>
        <tag>HEAD</tag>
    </scm>

    <modules>
        <!-- multiple modules in this project -->
        <module>module-1</module>
        <module>module-2</module>
        <module>module-3</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- multiple dependencies including the "other package" mentioned -->
            <dependency>
                <groupId>com.org.department.module</groupId>
                <artifactId>department-module</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <!-- two plug-ins that are not relevant, I think. Can share more if necessary -->
    </build>

    <repositories>
        <repository>
            <id>github-other</id>
            <name>department-other-repo-package</name>
            <url>https://maven.pkg.github.com/org/department-other-package</url>
        </repository>
    </repositories>
    <distributionManagement>
        <repository>
            <id>github</id>
            <name>department-parent-pom</name>
            <url>https://maven.pkg.github.com/org/department-package</url>
        </repository>
    </distributionManagement>
</project>
```

</details>

The folder structure is like this:
- `.github`
- `module-1`
- `module-2`
- `module-3`
- `pom.xml`

# Issue

What goes wrong, is that during the publish step the build fails with the following error:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project department-parent-pom: Failed to deploy artifacts: Could not transfer artifact com.org.department.package:department-parent-pom:pom:2.83-20230119.105335-1 from/to github (https://maven.pkg.github.com/org/department-package): transfer failed for https://maven.pkg.github.com/org/department-package/com/org/department/package/department-parent-pom/2.83-SNAPSHOT/department-parent-pom-2.83-20230119.105335-1.pom, status: 422 Unprocessable Entity -> [Help 1]
```

We have tried many things (slightly different settings in the settings.xml and repositories section of the pom.xml, all with the same result), among which is to (after the build step), do the following:

```yaml
      - name: Test push package.
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
         mvn deploy:deploy-file \
          -DgroupId=com.org.department.package \
          -DartifactId=department-package-module-1 \
          -Dversion=2.8.3 \
          -Dpackaging=jar \
          -DrepositoryId=github \
          -Durl=https://maven.pkg.github.com/org/department-package \
          -Dfile=./department-package-module-1/target/department-package-module-1-2.83-SNAPSHOT.jar
```

This tries to "manually" push a JAR from one of those modules, which works just fine. This seems like a hack, however, and we think we're just missing something small in either the GitHub side or the Maven side to make this work with a standard `maven deploy` and GitHub Packages.

Any feedback and suggestions for further exploration are much appreciated. :)
