### DISCUSSION TITLE
How to set workflow status to failed when dependents got cancelled and/or failed?

### DISCUSSION THREAD

**Discussion by pmalek** [community/community#44866] [Actions]
### Select Topic Area

Question

### Body

I have a workflow https://github.com/Kong/go-kong/blob/2a3123b4cb5a1645262c8ed7ed7bc9c38e7ef5f4/.github/workflows/integration-test.yaml which should only pass when all dependents in it (using a matrix strategy) succeed.

I thought that just marking the dependents in `needs` would be enough but in cases like this: https://github.com/Kong/go-kong/actions/runs/3962344750 when some jobs fail and some get cancelled (because of the failure of the other dependents but that's fine) the depending job gets skipped which breaks my branch protection rule (which I have only on the job the `needs` all dependents).

I figured I can do this: https://github.com/Kong/go-kong/pull/269

```
  test-passed:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
    - name: Set workflow outcome
      if: needs.test.result == 'failure' || needs.test.result == 'cancelled'
      run: ${{ false }}
```

but I feel there has to be "a better way". This approach will require a runner to actually pick this job up and only then set the status to failure whereas using the initial approach (which fails when dependent jobs get cancelled) works out with this limitation:

```
  test-passed:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set workflow outcome
      run: ${{ true }}
```
