### DISCUSSION TITLE
Action

### DISCUSSION THREAD

**Discussion by Hossam-Tarek** [community/community#44911] [Actions]
### Select Topic Area

Question

### Body

I'm using Github action to deploy to a shared hosting steps:

1. create ftp account on the shared hosting.
2. add action secrets
3. setup the Github action 
```yml
on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.demo_server }}
          username: ${{ secrets.demo_server_ftp_username }}
          password: ${{ secrets.demo_server_ftp_password }}
          server-dir: home/harajw/public_html/winner-ad/

```
4. after pushing new commits to the main branch the action runs successfully without any errors
 
![image](https://user-images.githubusercontent.com/23726675/213775101-5ae0137b-d550-46af-b801-34513f2423a8.png)

But there are no changes deployed to the server
