### DISCUSSION TITLE
How to run a service without an image

### DISCUSSION THREAD

**Discussion by hassanshaikley** [community/community#44925] [Actions]
### Select Topic Area

Usage question

### Body

What if I wanted to run the repo (webserver) and then complete further steps in parallel with the server running.

```
jobs:
  run-server:
    name: Run Contract Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - ...
      - name: Start Server
        run: iex -S mix phx.server

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: run-server
    ...
    steps:
      - uses: actions/checkout@v2
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        ...
```

This doesn't work because the server gets killed when run-test starts. How do I accomplish this without creating an image and putting it into a service block.
