### DISCUSSION TITLE
Runner has random entries in /etc/hosts

### DISCUSSION THREAD

**Discussion by rhofland** [community/community#45039] [Actions]
### Select Topic Area

Bug

### Body

In some cases a runner's /etc/hosts has random entries in it. I thought the runners were completely cleaned for each instance. What could cause these to show up?

Super simple workflow:
```
name: etc host issue

on:
   workflow_dispatch:

jobs:
  etc_host_issue:
    runs-on: ubuntu-22.04
    steps:
      - name: Show /etc/hosts
        run: |
          cat /etc/hosts

```
Results in:

<img width="1329" alt="Screen Shot 2023-01-21 at 10 51 04 PM" src="https://user-images.githubusercontent.com/12649353/213899811-c864f0d8-096a-4635-86a3-225f8e861ec8.png">
