### DISCUSSION TITLE
success() returns false if dependent jobs are skipped

### DISCUSSION THREAD

**Discussion by suzuki-shunsuke** [community/community#45058] [Actions]
### Select Topic Area

Bug

### Body

Please see the following workflow definition and result.

- https://github.com/suzuki-shunsuke/test-github-action/pull/119
- https://github.com/suzuki-shunsuke/test-github-action/actions/runs/3979279366
- https://github.com/suzuki-shunsuke/test-github-action/actions/runs/3979279366/workflow

```yaml
---
name: Test
on: pull_request
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
  bar:
    runs-on: ubuntu-latest
    if: "false"
    steps:
      - run: echo bar
  zoo:
    runs-on: ubuntu-latest
    if: "success()"
    needs:
      - foo
      - bar
    steps:
      - run: echo hello
```

<img width="700" alt="image" src="https://user-images.githubusercontent.com/13323303/213912019-49f68851-3299-472d-b1b9-e6d548b58ab4.png">

The job `zoo` depended on `foo` and `bar` and `foo` succeeded and `bar` was skipped, then `zoo` was skipped.

But I think `zoo` should have been run because none of the dependent jobs failed or was canceled.

https://docs.github.com/en/actions/learn-github-actions/expressions#success

> Returns true when none of the previous steps have failed or been canceled.

https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context

> needs.<job_id>.result | string | The result of a job that the current job depends on. Possible values are success, failure, cancelled, or skipped.

`skipped` is different from `cancelled`.

I changed `if` from `success()` to `! failure()`, then it worked as expected.
