### DISCUSSION TITLE
Required validations for check-boxes and drop-downs not honored in GitHub issue templates

### DISCUSSION THREAD

**Discussion by Elliria** [community/community#45084] [Projects and Issues]
### Select Topic Area

Bug

### Body

I admit that it's possible that my syntax isn't correct, but I believe I've come across a **validations** bug in GitHub's YAML issue templates.

These two example questions specify the **true** attribute for the **required** option in the **validations** field, yet neither question is actually required for completing the issue report: 

```
  # TEST OF REQUIRED QUESTION WITH CHECK-BOXES
  - type: checkboxes
    id: test_of_required_question_with_check_boxes
    attributes:
      label: Test - Is this question with check-boxes required?
      description: >
        It should be, but isn't.
      options:
        - label: One
        - label: Two
        - label: Three
    validations:
      required: true

  # TEST OF REQUIRED QUESTION WITH A DROP-DOWN MENU
  - type: dropdown
    id: test_of_required_question_with_a_drop_down_menu
    attributes:
      label: Test - Is this question with a drop-down menu required?
      description: >
        It should be, but isn't, and GitHub gives it a red asterisk as though it is.
      options:
        - One
        - Two
        - Three
    validations:
      required: true
```
Also, GitHub doesn't automatically put a red asterisk next to the question with the check-boxes at all, which indicates to the user that the question is optional. The issue report can be submitted without the user interacting with the check-boxes.

Also, GitHub automatically puts a red asterisk next to the question with a drop-down menu, which indicates to the user that the question is required, but the issue report can be submitted without the user interacting with the drop-down menu.
