### DISCUSSION TITLE
Unauthorized when publishing private Package with Personal Access Token

### DISCUSSION THREAD

**Discussion by ladooniani** [community/community#45097] [Packages] [answered]
I am having an issue with publishing my private Node.js GitHub Packages using  Personal access tokens (classic). I am receiving the following error in GitHub Actions publish-gpr:

    npm ERR! 401 Unauthorized - PUT https://npm.pkg.github.com/@username%2fmypackage - unauthenticated: User cannot be authenticated with the token provided. npm ERR d with exit code 1.`

I have updated the personal access token several times with the same scope settings of repo and `write:packages` and `read:packages`, and replaced it in my `.npmrc` file and referenced it as an environment variable. 

 Despite this, I am still receiving the above error when trying to create a new release. The token is not expired and is correct without typos. It is present in GitHub `Personal access tokens (classic)`, but the note says it is Never used. I am also receiving the same error when trying to use `npm publish`. 

.npmrc:

`//npm.pkg.github.com/:_authToken=%GITHUB_TOKEN%`

.github\workflows\release-package.yml:

```
name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@username"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

and I have tried:

 ```
       env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
 
package.json:
```
{
  "name": "@username/pack",
  "version": "1.0.0",
  "description": "description",
  "main": "index.js",
  "publishConfig": {
    "@username:registry": "https://npm.pkg.github.com"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/username/pack.git"
  },
  "keywords": [
    "keyword"
  ],
  "author": "Author name",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/username/pack/issues"
  },
  "homepage": "https://github.com/username/pack#readme"
}
```

Can anyone provide guidance on how to resolve this issue?

**Comment by PythonCoderAS** [comment]
Did you follow the instructions at https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-with-a-personal-access-token? Can you send your `.npmrc` **with tokens replaced with dummy text**?

**Reply by ladooniani** [reply]
Hello! Yes, I've followed 'Authenticating with a personal access token' . ` .npmrc` added.

**Reply by PythonCoderAS** [reply]
Try modifying your action to be like this:
```yaml
name: Node.js Package

on:
  release:
    types: [created]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@username"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Reply by ladooniani** [reply]
adding permissions error on existing : `repository 'https://github.com/username/my-repositry/' not found`

```
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +w1a4551c3745530035baj343452a0730f3423s12:refs/tags/mypack-v1.0.0
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/username/my-repositry/' not found
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Reply by PythonCoderAS** [reply]
Did you remember to add the `.git` at the end? `Like https://github.com/username/my-repositry.git`?

**Reply by ladooniani** [reply]
I have two repositories with identical setup in their .yml, package.json (added to post) and .npmrc files, with different names and code. One of the repository's package build is successful, but the other is giving me an `error 'build repository 'https://github.com/username/mypack/' not found'`. git remote -v :
```
origin https://github.com/username/pack.git (fetch) 
origin https://github.com/username/pack.git (push)
```
I have attempted to resolve the issue by completely deleting the problematic repository and creating a new one with the same name, but the   `Error: fatal: repository 'https://github.com/username/pack/' not found `still persists in build step. ` npm ERR! 401 Unauthorized`, in `publish-gpr` does not appear without  edits in code or package setup.  

  I've created another one in this case 'public' repository, following [Quickstart for GitHub Packages](https://docs.github.com/en/packages/quickstart) with `@username:registry=https://npm.pkg.github.com` in `.npmrc` 
 and [Publishing a package using a local .npmrc file](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#publishing-a-package-using-a-local-npmrc-file)

`echo %GITHUB_TOKEN%` show token.  `echo %NPM_CONFIG_REGISTRY%` displays registry. 
and same  ` npm ERR! 401 Unauthorized`or `Error: Process completed with exit code 1.`

**Comment by Melv** [comment, marked as answer]
Following [Quickstart for GitHub Packages](https://docs.github.com/en/packages/quickstart) on a private repo I also had that error message.
I've solved it to remove the `.npmrc`  from the repo and build it into the gh actions yaml end let `_authToken` use the provided `secrets.GITHUB_TOKEN`.

```yaml
name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test


  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: |
          echo "@username:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

This solved it from me.

**Reply by MalvinJay** [reply]
This is indeed what worked after 48 hours of debug releases 😭  . Thanks @Melv

**Reply by nikmolnar** [reply]
This worked for me too, after running into issues with the quick start action. Why is the quick start broken?

**Reply by ahsan-babar** [reply]
Worked like a charm! I can feel your pain @MalvinJay 😭
Thank you @Melv

**Reply by VishwasShashidhar** [reply]
Thank you @Melv! I was stuck with this issue for 24 hours & finally bumped into this solution.

Interestingly, for a different action of mine which uses setup-node@v1, just creating a `~/.npmrc` file with the token works. Looks like something has changed since v3.

**Reply by mpint** [reply]
This worked like a charm, but I was able to replace it by setting `NODE_AUTH_TOKEN` in the `actions/setup-node` action along with `registry-url` and `scope`.
```
- name: Setup Node.js
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_PUBLISH_PACKAGES_TOKEN }}
        with:
          node-version: lts/iron
          registry-url: https://npm.pkg.github.com
          scope: "@myorg"
```

**Reply by mbeniwal-imwe** [reply]
This worked for me. Thanks a lot for saving a lot of time.

**Comment by hivokas** [comment]
What worked for me is moving env declaration to the job level:

```
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
