### DISCUSSION TITLE
Limitting workflow concurrency on fixed number

### DISCUSSION THREAD

**Discussion by mtamiola-priv** [community/community#45140] [Actions]
### Select Topic Area

Question

### Body

I'm looking for solution to limit currently running builds of particular workflow, on `pull_request` event

Use case: I'm deploying cloud-formation stack, and have limited number of configured environments so cannot run updating new stack before previous one is running. I know such setup is not best approach, but there are other reasons we cannot add more envs "on-demand".

So I know about `strategy.max-parallel`, but afaik this will limit number of jobs within single build. What I need to achieve is to have eg. 10 builds queued from different PRs and let's say only 3 are running at the same time. 
Only solution for now seems, to count currently running builds with something like
`gh run list --workflow dev-deploy.yml --json status -q '.[].status' | grep in_progress | wc -l`
in some kind of dispatcher and allow to start next only when there is available slot, however this has its own drawbacks, like problem with ordering and there could be actually 10 running build burning minutes hanged on waiting step.

Is there any way to implement such behaviour?
What would work best is probably something like:
```
concurrency:
  group: ${{ github.workflow }}
  max-parralel: 3
  ```
 on workflow level.

**Comment by vitalykarasik** [comment]
AFAIK, this feature is missing for now. And not only that - for example, only one job can wait in the queue. 
I'm not sure where and how we can open such feature request - https://github.com/community/community/discussions/46014.
I couldn't see something relevant into GH roadmap...
Regards,
Vitaly
(see my LI rant as well https://www.linkedin.com/feed/update/urn:li:activity:7026518468577366017/)

**Comment by kaykhan** [comment]
We are also interested in this feature, has there been any progress?

**Reply by mtamiola-priv** [reply]
No native solution atm as I know. 
As I'm deploying to AWS I implemented custom solution based on SQS fifo queues acting as kind of semaphore. 
Drawback, as mentioned, is burning minutes to check if build is fine to proceed, however that part of pipeline I've done in separate job running on default workers, and in our case that is included in plan anyway.

**Comment by RunningLeon** [comment]
Same request. Any plan on this feature?

**Comment by Duy-LQ** [comment]
For now, I think this might be a temporary solution, 
Here is the expression that will limit only 2 workflows run at the same time
`${{ endsWith(github.run_number, '0') || endsWith(github.run_number, '2') || endsWith(github.run_number, '4') || endsWith(github.run_number, '6') || endsWith(github.run_number, '8') }}`

The expression that will limit only 3 workflows run at the same time:
`((endsWith(github.run_number, '0') || endsWith(github.run_number, '3') || endsWith(github.run_number, '6') || endsWith(github.run_number, '9'))) && '0' || (((endsWith(github.run_number, '1') || endsWith(github.run_number, '4') || endsWith(github.run_number, '7'))) && '1' || '2')`

Example test.yml workflow

```
name: Test Concurrency Limit 2 Workflows

on:
  workflow_dispatch:

concurrency:
  group: ${{ endsWith(github.run_number, '0') || endsWith(github.run_number, '2') || endsWith(github.run_number, '4') || endsWith(github.run_number, '6') || endsWith(github.run_number, '8') }}

env:
  TESTDATA: ${{ endsWith(github.run_number, '0') || endsWith(github.run_number, '2') || endsWith(github.run_number, '4') || endsWith(github.run_number, '6') || endsWith(github.run_number, '8') }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show variables
        run: |
          echo "run_number: ${{ github.run_number }}"
          echo "TESTDATA: ${{ env.TESTDATA }}"
```
