### DISCUSSION TITLE
How do I trigger action on Release with a specific tag?

### DISCUSSION THREAD

**Discussion by AnatolyBuga** [community/community#45144] [Actions] [answered]
### Select Topic Area

Product Feedback

### Body

I have multiple **releases** for my repo. Say one for UI, one for Python publishing lib. Say, I want to only only publish python lib when release tag is - py-*

I tried that but it doesn't work. **Python gets triggered on any release** still.
```
on:
  release:
    types: [published]
    tags:
        - py-*
```

**Comment by spenserblack** [comment, marked as answer]
Instead of `on: release`, I'll usually use `on: push: tags`.

This is something I use in almost all of my release workflows, for example.
```yaml
on:
  push:
    tags: [ 'v*.*.*' ]
```
