### DISCUSSION TITLE
Define what configuration variables are required for a workflow

### DISCUSSION THREAD

**Discussion by plofty** [community/community#45143] [Actions]
### Select Topic Area

Product Feedback

### Body

I have reusable workflows that require configuration variables to be created in other repositories or orgs. 

There currently is no way in workflow to define what configuration variables are required before running the workflow. This is currently supported for inputs and secrets.

**Current workaround**
I have to verify each configuration variable exists and is populated in my workflow. Fail the workflow if they do not exist.

**Proposed solution**
With reusable workflows we can set an input or secret is required. Could we also define what configuration variables are required. If something calls my reusable workflow I would like to it to fail if the configuration variable does not exist in their repository or org

called workflow

```
name: test
on:
  workflow_call:
    inputs:
      test:
        type: string
        required: true
    secrets:
      token:
        required: true
    variables:
      username:
        required: true
```

caller workflow

```
  test:
    uses: test/test/.github/workflows/test.yml@main
    with:
      test: ${{ inputs.test}}
    secrets:
      token: ${{ secrets.token}}
    variables:
      username: ${{ variables.username}}
```
