### DISCUSSION TITLE
github action do not support retry (re-try)

### DISCUSSION THREAD

**Discussion by chrislin22** [community/community#45162] [Actions]
### Github Action

Question

### Body

when/will github can support **retry (re-try)** when workflow or a job fails?
like gitlab already has: https://docs.gitlab.com/ee/ci/yaml/#retry
e.g.

```
jobs:
  myJob:
    runs-on: ubuntu-latest
    name: myJob
    retry: 2
```

**Comment by jge162** [comment]
@chrislin22 you can define the action you want to take when a failure occurs

Additionally, you can also use Community Actions, which are actions created and shared by the GitHub community. There are some actions that provide retry functionality for jobs, you can check them out in the GitHub marketplace.


```YAML
jobs:
  myJob:
    runs-on: ubuntu-latest
    name: myJob
    steps:
    - name: step1
      run: |
        echo "Hello World"
    on:
      failure:
        steps:
        - name: step2
          run: |
            echo "Retrying Job"
```
