### DISCUSSION TITLE
Issue in usage of registry service ends up creating multiple images, some with creation timestamp set to 0 (epoch)

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#45160] [Actions]
### Select Topic Area

Bug

### Body

In my workflow, I am building an image and pushing it to local registry

```
      - name: build and push to local registry
        uses: docker/build-push-action@v3.3.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          no-cache: ${{ inputs.no_cache }}
          build-args: ${{ inputs.build_args }}
          push: true
          tags: ${{ env.LOCAL_IMAGE }}
          cache-to: type=inline
          provenance: false
```

I then use `buildx` to copy the image to a GCR registry

```
      - name: copy tagged image to sre gcr
        if: inputs.image_build == true
        shell: bash
        run: |
          docker buildx imagetools create \
            --tag "${{ steps.set-images.outputs.base }}:${{ inputs.image_tag }}" \
            ${{ env.LOCAL_IMAGE }}
```

Instead of having one image created, I get this:

![Screenshot 2023-01-23 at 9 05 51 PM](https://user-images.githubusercontent.com/50835081/214127447-b01418b1-d4f7-4762-9f2f-47ab1102d169.png)

My workflow uses the local registry service

```
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
```
