### DISCUSSION TITLE
Auto-add to project - access for non enterprise accounts

### DISCUSSION THREAD

**Discussion by stherold** [community/community#45311] [Enterprise]
### Select Topic Area

Question

### Body

Hey there 👋

super glad to hear that you enabled the auto-add to project workflow 🎉 Until now we implemented our own workflow file which is taking care of this (for anybody who needs this maybe):
```yaml
name: Auto Assign to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    name: Assign to "Backlog" Project
    steps:
    - name: Assign NEW issues and NEW pull requests to organization project "Backlog"
      uses: actions/add-to-project@main
      with:
        project-url: https://github.com/orgs/<organization>/projects/<project-id>
        github-token: ${{ secrets.AUTO_ADD_GITHUB_TOKEN }}
```

My question now is 
a) why only for enterprise customers? 
b) and more important: when do you open this up for other customers as well, e.g. organizations 😅

Keep upü the good work - you're amazing 🙏
