### DISCUSSION TITLE
Using fields as comments

### DISCUSSION THREAD

**Discussion by Su5eD** [community/community#4533] [Projects and Issues] [answered]
Hello! I'd like to ask if there is a way to use certain fields as comments, e.g. display them only when creating a new issue.  

Consider the following example:
```yaml
- type: markdown
    attributes:
      value: "## Welcome!"
- type: markdown
    attributes:
      value: |
        Thanks for taking your time to report this bug! If you need real-time help, join us on Discord.
        Make sure you are running the latest version before reporting.
```
These fields are useful to the reporter, but take up a lot of space and can distract readers of the issue.  

In case there is no such option, what alternative would you recommend?
