### DISCUSSION TITLE
Are labels a required field?

### DISCUSSION THREAD

**Discussion by ecurrencyhodler** [community/community#45389] [Actions] [answered]
### Select Topic Area

Question

### Body

I configured my file as the following but it isn't pulling in issues and turning them into tasks:

```
name: Add issues to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/orgs/saving-satoshi/projects/2
          github-token: ${{ mysecretPAT }}
          labeled: 
          label-operator: 
```

Am I missing something here? Are the fields labeled and label-operator required? If so, how do I pull in issues that don't have labels?
