### DISCUSSION TITLE
GH Action upload artifacts in case of failure are not saved after re-run

### DISCUSSION THREAD

**Discussion by shirady** [community/community#45415] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello,
We use artifacts in case of failure to collect logs.
But I noticed that if someone re-runs a job that failed, then we do not have the artifacts of the previous failed attempt, for example, second attempt (success), first attempt (failed) - no artifacts saved.
It is on purpose? 
If not, I'll suggest it as an enhancement.

**Comment by VladCuciureanu** [comment]
Artifacts have a retention period which you can specify, with the default being 90 days.
Did the first attempt happen to be more than 90 days of a distance from the second attempt?

**Reply by shirady** [reply]
It was yesterday

**Reply by VladCuciureanu** [reply]
Hmmm. Without seeing the repo there's not much I can do.
One suggestion I have tho is using this step:
```yaml
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifacts
          path: artifacts
          if-no-files-found: error
          retention-days: 90
```
