### DISCUSSION TITLE
Using inputs for the matrix strategy

### DISCUSSION THREAD

**Discussion by cb80** [community/community#45420] [Actions]
### Select Topic Area

Question

### Body

I'd like to give my users the possibility to run a workflow for certain scenarios by using the inputs of `workflow_dispatch`. They can provide values for various dimensions as input. One dimension could be the container images to be used. Another one could be the versions for some software to be used during the run.

Here is how I do it right now:

```
---
name: MyWorkflow

on:
  workflow_dispatch:
    inputs:

      values_dimension_1:
        required: true
        type: string
        default: foo bar

      values_dimension_2:
        required: true
        type: string
        default: biz baz

jobs:
  setup:
    runs-on: default
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}

    steps:
      - name: Setup matrix combinations
        id: setup
        run: |
          json="{"
          json+='"dimension_1":['
          sep=''; for word in ${{ inputs.values_dimension_1 }}; do json+="${sep}\"${word}\""; sep=,; done
          json+='],'
          json+='"dimension_2":['
          sep=''; for word in ${{ inputs.values_dimension_2 }}; do json+="${sep}\"${word}\""; sep=,; done
          json+=']'
          json+="}"
          echo "::set-output name=matrix::${json}"

  do:
    runs-on: default
    needs: setup
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - name: Print the matrix values
        run: echo ${{ toJson(matrix) }}
```

The values for each dimension are given as a space separated string. In the `setup` job I convert all these into a json which is used in the `do` job for the matrix strategy.

**Is there some better way to write this?**

I was hoping for something like this, but that doesn't seem to work:
```
---
name: MyWorkflow

on:
  workflow_dispatch:
    inputs:

      values_dimension_1:
        required: true
        type: string
        default: foo bar

      values_dimension_2:
        required: true
        type: string
        default: biz baz

jobs:
  do:
    runs-on: default
    strategy:
      matrix:
        dimension_1: ${{ inputs.values_dimension_1 }}
        dimension_2: ${{ inputs.values_dimension_2 }}

    steps:
      - name: Print the matrix values
        run: echo ${{ toJson(matrix) }}
```
