### DISCUSSION TITLE
env not found

### DISCUSSION THREAD

**Discussion by kvernon** [community/community#45438] [Actions]
### Select Topic Area

Bug

### Body

This is odd, the action isn't working on seeing the env.

```yml

name: Feature Build Flow

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  debug: false

jobs:
  ensure_branch_prefix:
    name: Ensure Branch Prefix
    uses: ./.github/workflows/flow-ensure-prefix-branch.yml
    with:
      debug: ${{ env.debug }} # problem is here via the job being run #
```

`The workflow is not valid. .github/workflows/release.yml (Line: 28, Col: 14): Unrecognized named-value: 'env'. Located at position 1 within expression: env.debug .github/workflows/release.yml (Line: 40, Col: 14): Unrecognized named-value: 'env'. Located at position 1 within expression: env.debug`

To add some context, making the following:

```yml
# ...
    with:
      debug: true

```

This runs fine. 

So... Is there something up with environment variables? or is there some secret rule to not use Booleans? But honestly, this reads like `env` is `undefined`.
