### DISCUSSION TITLE
[github actions] shell parameter expansion: replace character ( `${parameter/%pattern/string}` )

### DISCUSSION THREAD

**Discussion by kwladyka** [community/community#45488] [Actions] [answered]
### Select Topic Area

Question

### Body

I am trying to use `${parameter/%pattern/string}`

In google cloud simple `${TAG_NAME//./-}` do the job.

But I can't make it work in github actions.

How to `0.0.1` to `0-0-1` without using bash commands, so with shell parameter expansion or github expressions?

https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
https://docs.github.com/en/actions/learn-github-actions/expressions

**Comment by jge162** [comment]
@kwladyka You can use the sed command to replace a pattern with a string in shell parameter expansion.

TAG_NAME="0.0.1"
TAG_NAME="$(echo $TAG_NAME | sed 's/\./-/g')"
echo $TAG_NAME # Output: 0-0-1


TAG_NAME="0.0.1"
TAG_NAME="$(echo $TAG_NAME | tr . -)"
echo $TAG_NAME # Output: 0-0-1

**Reply by markjreed** [reply]
You should actually run things before stating what their output is. Your `sed 's/./-/g'` will replace _every character in the string_ with a minus sign, because `.` in a regular expression matches any character.

    $ TAG_NAME="0.0.1"
    $ TAG_NAME="$(echo $TAG_NAME | sed 's/./-/g')"
    $ echo $TAG_NAME
    -----

You could fix that by changing it to `'s/\./-/g'`, but do you really need to call out to `sed` or `tr` here? If you can run shell commands, you should be able to use the special expansions like `${TAG_NAME//./-}`. Unless GHA is using a shell that doesn't have those? Obviously they don't work in places where the GHA parser is the one doing the substitution, i.e. `${{`...`}}`, but in the context of shell commands...

**Comment by kwladyka** [comment]
Thank you @jge162 .

Still would like to find a way to set it up on the beginning of the file in `env` as a right value. At least this is how it was in cloud build. Unless it is not possible in github actions, but I was assuming this is just hard to find how to do it.

**Comment by airtower-luna** [comment]
There is only very limited support for string formatting in the Actions syntax itself, see [Expressions](https://docs.github.com/en/actions/learn-github-actions/expressions). For anything more complex you'll need to use steps and create outputs (or environment variables) to set the values you want (e.g. using shell syntax).

**Comment by kwladyka** [comment]
Is a way to do something like below? BUT with `tr` and setting `env` as global for all jobs to inject by automate?

```
jobs:
  set-envs:
    runs-on: ubuntu-latest
    steps:
      - name: set values
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.VERSION }}"
  other-job:
    needs: [set-envs]
    runs-on: ubuntu-latest
    steps:
      - name: Use the value
        run: |
          echo "${{ env.VERSION }}"
```

**Comment by airtower-luna** [comment, marked as answer]
There's no way to dynamically set an environment variable for all jobs. But you could [use outputs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs) to transfer the values between jobs (mind that this requires a `needs` relationship between the jobs):

```yaml
jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gen_version.outputs.VERSION }}
    steps:
      - name: set values
        id: gen_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Use the value
        # this sets environment variables for this step
        env:
          VERSION: ${{ steps.gen_version.outputs.VERSION }}
        run: |
          echo "${VERSION}"

  other-job:
    needs: [set-vars]
    runs-on: ubuntu-latest
    # this sets environment variables for the whole job
    env:
      VERSION: "${{ needs.set-vars.outputs.version }}"
    steps:
      - name: Use the value
        run: |
          echo "${VERSION}"
```

A `run` step runs in the shell (on Ubuntu it's Bash by default), so you have all the usual syntax available.

Note that I've changed the `run` steps that use the value to use Bash syntax to access the environment variable instead of Actions syntax. This is highly recommended in general to avoid weird bugs or even security problems: Actions syntax in the script is *literally* replaced before the script runs, so for example a `"` in the value will be interpreted by the shell. Accessing environment variables with shell syntax avoids those problems.
