### DISCUSSION TITLE
Push from inside a workflow fails to trigger build

### DISCUSSION THREAD

**Discussion by awt** [community/community#45535] [Actions]
### Select Topic Area

Question

### Body

Why doesn't a push to the default repo from inside a workflow trigger a new build?  Is there a way to get around this?

**Comment by airtower-luna** [comment]
That's intentional, as [described in the documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow):

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

The way to get around it would be to provide a PAT to the workflow (as a secret) and authorize the push with that instead. The [`token` parameter to `actions/checkout`](https://github.com/actions/checkout#usage) is the most convenient way to use your own token instead of `GITHUB_TOKEN`.

**Reply by awt** [reply]
I am currently using a PAT.  Is it perhaps missing a required permission?

**Reply by airtower-luna** [reply]
In that case the push should fail. Most likely it's not actually used, but I'd need to see your workflow to confirm and say how to fix it (very likely by using the `token` parameter mentioned above).

**Reply by awt** [reply]
The push does succeed.

Here's the code:

```
name: Automated Gem Update
on:
  repository_dispatch:
    types: [build_with_latest_gem]

jobs:
  update-gem:
    runs-on: ubuntu-latest
    env:
      MYCOMPANY_CI_GITHUB_TOKEN: ${{ secrets.MYCOMPANY_CI_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Update Gem
        run: |
          export BUNDLE_RUBYGEMS__PKG__GITHUB__COM=${{ secrets.MYCOMPANY_CI_GITHUB_TOKEN }}:x-oauth-basic
          bundle update --conservative mycompany-gem
      - name: Commit and push gem update
        run: |
          git config --global user.name 'Mycompany CI'
          git config --global user.email 'ci@mycompany.com'
          git remote set-url origin https://x-access-token:${{ secrets.MYCOMPANY_CI_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add Gemfile.lock
          git commit -m "Update mycompany gem to latest version."
          git push
```

**Reply by awt** [reply]
This is an excerpt from the workflow file that I'm expecting to be triggered.  Dev is the default branch and the branch that the above workflow is pushing to.

```
name: Dev CI/CD

on:
  push:
    branches:
      - dev
```

**Reply by airtower-luna** [reply]
Here's the problem:

```
git remote set-url origin https://x-access-token:${{ secrets.MYCOMPANY_CI_GITHUB_TOKEN }}@github.com/${{ github.repository }}
```

The token in the URL is completely ignored, because `actions/checkout` sets up an `Authorization` header with the `GITHUB_TOKEN` by default. The elegant solution is to remove that line and the `env` section that provides the PAT to *all* steps in your job, and provide your PAT to `actions/checkout` (which you should also update to v3):

```yaml
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MYCOMPANY_CI_GITHUB_TOKEN }}
```

That way the PAT will be used for all the remote operations on that repository (including initial fetch), and also be cleaned up automatically at the end of the job. :slightly_smiling_face:
