### DISCUSSION TITLE
[Issue] failed matrix jobs with continue-on-error count as success for subsequent jobs

### DISCUSSION THREAD

**Discussion by scrungus** [community/community#45546] [Actions]
### Select Topic Area

Question

### Body

given a ci job: 

```
name: test and publish
on:
  push:

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  publish:
    needs: [test]
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
```

If `test.yaml` is setup like so: 

```
name: Test
on: 
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1,2,3,4]
      max-parallel: 1
    continue-on-error: true 
    steps:
      - name: Fail
        run: exit 1
```
Then the `publish` job will start even if the `test` job fails. In our use case, the desired behaviour is that all the test jobs in the matrix should run, regardless of any failures, but `publish` should not run if all the `test` jobs do not complete successfully. Is there currently a way to do this, and is this the indented behaviour of `continue-on-error`?
