### DISCUSSION TITLE
Planned repository visibility change

### DISCUSSION THREAD

**Discussion by TheHellTower** [community/community#45676] [Repositories] [answered]
### Select Topic Area

Product Feedback

### Body

Hello,

I recently tried to search a way to "program" a future repo visibility change from GitHub settings directly, apparently it's not possible at this moment and I don't know if it will be made possible one day.
But my suggestion is to add a option to select a date & hour to make the repository public, I suppose it can be nice if you can't connect at X date and want your repository to still be released publicly at the X date.

If you have any question don't hesitate,

Regards.

**Comment by norwd** [comment, marked as answer]
Create a `.github/workflows/public.yml` file with the following contents:

```yaml
---

on:
  schedule:
    - cron: '<CRON_DATE>' # http://crontab.guru
jobs:
  make-private:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo edit ${{ github.repository }} --visibility public
        env:
          GH_TOKEN: ${{ secrets.MAKE_REPO_PUBLIC }}
```

All you need to do now is set the `cron:` schedule to a specific date using cron format, http://crontab.guru is a great resource for this, and create an actions secret named `MAKE_REPO_PUBLIC` and paste a PAT with `repo: write` permissions. This will create a workflow that will automatically make the repository public on the specific date (down to the hour and minute) you want.
