### DISCUSSION TITLE
Creating an Automated Release with GitHub Actions for a Minecraft Texture Repository

### DISCUSSION THREAD

**Discussion by vindocel** [community/community#45733] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

General

### Body

I am reaching out for help in creating an Action on GitHub.
As a designer, I have a public repository for a Minecraft texture, but I have limited knowledge of code. The repository includes 3 branches: 1.19.3, 1.19, and 1.18, each corresponding to a version of Minecraft. Additionally, there is an Alpha branch where I release updates before merging them with the other branches.

I am looking to automate the process using GitHub Actions. Specifically, when I merge any branch into the master branch (1.19.3), I want the Action to:

Create a new release
Add the following files within the zip: assets, pack.mcmeta, pack.png
Create a zip file for each branch: 1.19.3, 1.19, 1.18
Name the zip files as Dark-Everywhere and the corresponding branch name
Add a semantic versioning tag v0.0.0 greater than the previous tag
Add the build description as the titles and links of the commits made after the last build
Name the release as Dark Everywhere {generated tag}🌙
I have attempted to read through the documentation, but I am having difficulty implementing the Action. Any help would be greatly appreciated. As a designer, my expertise is in creating the texture, not in coding. Thank you for your attention.

release example
https://github.com/vindocel/Dark-Everywhere/releases/tag/v1.3.9

I found this that could help but I can't implement it
https://github.com/marvinpinto/action-automatic-releases

**Comment by jge162** [comment, marked as answer]
Good day to you @vindocel Here is some `pseudocode`-> (its up to you to finish) you can play with. It is not finished but a start for you. Aslo refer here for additonal help [Github Actions](https://docs.github.com/en/actions)

```yaml
name: Release
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FILE_NAME: "Dark-Everywhere"
  FILE_EXTENSION: ".zip"
  BRANCHES: "1.19.3,1.19,1.18"
  PACKAGE_NAME: "assets,pack.mcmeta,pack.png"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create a release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.TAG_NAME }}"
        release_name: "Dark Everywhere ${{ env.TAG_NAME }}🌙"
        draft: false
        prerelease: false
    - name: Generate a zip archive for each branch
      run: |
        for branch in $(echo $BRANCHES | tr "," "\\n"); do
          zip -r "$FILE_NAME-$branch$FILE_EXTENSION" $PACKAGE_NAME
        done
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: "$FILE_NAME-$branch$FILE_EXTENSION"
        path: "$FILE_NAME-$branch$FILE_EXTENSION"
    - name: Update release
      uses: actions/update-release@v1
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        release_id: ${{ env.RELEASE_ID }}
        body: "Build description here"
```

**Reply by vindocel** [reply]
Thank you, it gave me a good North, I will study what you did and try to implement it. ❤️❤️

**Reply by jge162** [reply]
Change build description to what you want. Should work as is. But test.

**Reply by vindocel** [reply]
I'm having a problem, it's returning an error `Input required and not supplied: tag_name ` this tag, will I have to create a new Yalm file with a name of "TAG_NAME" and add it inside?

sorry for the silly question my knowledge is zero kk
but I'm trying

**Reply by jge162** [reply]
To resolve this issue, you need to set a value for TAG_NAME in your YAML file.

You can do this by adding a new line under env section->

```bash
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FILE_NAME: "Dark-Everywhere"
  FILE_EXTENSION: ".zip"
  BRANCHES: "1.19.3,1.19,1.18"
  PACKAGE_NAME: "assets,pack.mcmeta,pack.png"
  TAG_NAME: "1.0.0"
```

Replace "1.0.0" with the desired value for the release tag.

**Reply by jge162** [reply]
If and when you are satisfied with answer and are ready to complete discussion please pick answered. Thank you.

**Reply by vindocel** [reply]
the problem with the tag even after the modification still persists, I will conclude the question, and I will continue racking my brains until it is resolved, after all you have already helped me a lot

**Reply by jge162** [reply]
Just post errors I can keep helping. No problem

**Reply by vindocel** [reply]
when i try to run the code it gives this
`Error: Input required and not supplied: tag_name`

however the tag `TAG_NAME` is already past
```
env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   FILE_NAME: "Dark-Everywhere"
   FILE_EXTENSION: ".zip"
   BRANCHES: "1.19.3,1.19,1.18"
   PACKAGE_NAME: "assets,pack.mcmeta,pack.png"
   TAG_NAME: "1.0.0"
```

and the other tag is also passed
```
       with:
         tag_name: "v${{ env.TAG_NAME }}"
```

so I really don't know what could be causing the error

**Reply by jge162** [reply]
The error is saying that the TAG_NAME environment variable is not defined or not set to a value. You can confirm this by checking if the environment variable is set to a value by adding the following code to your workflow file->

```bash
- name: Check environment variables
  run: echo "TAG_NAME = ${TAG_NAME}"
```

If the environment variable is not set, you can set it in the workflow file like this->

```bash
env:
  TAG_NAME: "1.0.0"
```

If the environment variable is set, but still not working, you can try removing the quotes around the environment variable to pass it as is->

```yaml
with:
  tag_name: v${{ env.TAG_NAME }}
 ```

try hopping it fixes issues

**Reply by vindocel** [reply]
I can no longer use words for what could be happening after all this error persists

if you wanted to enter the test repository that I created to look at the error yourself, why is this macabre lol
https://github.com/vindocel/Dark-Everywhere-teste

**Reply by jge162** [reply]
I can check it out tomorrow.

**Reply by vindocel** [reply]
I will wait for the return, thank you 😍

**Reply by jge162** [reply]
post error message

**Reply by vindocel** [reply]
> I can no longer use words for what could be happening after all this error persists
> 
> if you wanted to enter the test repository that I created to look at the error yourself, why is this macabre lol
> https://github.com/vindocel/Dark-Everywhere-teste

☝️

**Reply by jge162** [reply]
```yaml
name: Release
on:
  push:
    tags:
      - 'v*'
env:
  FILE_NAME: "Dark-Everywhere"
  FILE_EXTENSION: ".zip"
  BRANCHES: "1.19.3 1.19 1.18"
  PACKAGE_NAME: "assets pack.mcmeta pack.png"
  TAG_NAME: "0.0.1"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create a release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ env.TAG_NAME }}"
        release_name: "Dark Everywhere ${{ env.TAG_NAME }}🌙"
        draft: true
        prerelease: false
    - name: Generate a zip archive for each branch
      run: |
        for branch in ${BRANCHES}; do
          zip -r "$FILE_NAME-$branch$FILE_EXTENSION" $PACKAGE_NAME
        done
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: "$FILE_NAME-$branch$FILE_EXTENSION"
        path: "$FILE_NAME-$branch$FILE_EXTENSION"
    - name: Update release
      uses: actions/update-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ env.RELEASE_ID }}
        body: "Build description here"
```

**Reply by jge162** [reply]
try

**Reply by vindocel** [reply]
I tried, still the same error, I'm starting to think it's impossible
![image](https://user-images.githubusercontent.com/18473368/215740258-7660743a-a49d-4592-9b84-5c27957a2a39.png)

**Reply by jge162** [reply]
let me think about this one

**Reply by jge162** [reply]
Try updating the tag to this and see what it says

```yaml
FILE_NAME: "Dark-Everywhere"
FILE_EXTENSION: ".zip"
BRANCHES: "1.19.3 1.19 1.18"
PACKAGE_NAME: "assets pack.mcmeta pack.png"
TAG_NAME: "${{ env.TAG_NAME || '0.0.1' }}"
```

**Reply by jge162** [reply]
your code is missing tag I just looked

**Reply by jge162** [reply]
I just tested and there are no errors 

![image](https://user-images.githubusercontent.com/31228460/215742608-055767cb-598d-43fe-bddb-8ed587d133a0.png)

**Reply by vindocel** [reply]
my code is exactly the same as yours but the error persists
![image](https://user-images.githubusercontent.com/18473368/215743188-9d3cadb8-a297-49e8-bb36-44cd50eefebd.png)

**Reply by vindocel** [reply]
do I have to have a separate file containing the tag?

**Reply by jge162** [reply]
```yaml
name: Release
on:
  push:
    tags:
      - 'v*'
env:
  FILE_NAME: "Dark-Everywhere"
  FILE_EXTENSION: ".zip"
  BRANCHES: "1.19.3 1.19 1.18"
  PACKAGE_NAME: "assets pack.mcmeta pack.png"
  TAG_NAME: "${{ env.TAG_NAME || '0.0.1' }}"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create a release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ env.TAG_NAME }}"
        release_name: "Dark Everywhere ${{ env.TAG_NAME }}🌙"
        draft: true
        prerelease: false
    - name: Generate a zip archive for each branch
      run: |
        for branch in ${BRANCHES}; do
          zip -r "$FILE_NAME-$branch$FILE_EXTENSION" $PACKAGE_NAME
        done
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: "$FILE_NAME-$branch$FILE_EXTENSION"
        path: "$FILE_NAME-$branch$FILE_EXTENSION"
    - name: Update release
      uses: actions/update-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ env.RELEASE_ID }}
        body: "Build description here"
```

double check it is the same, i have no errors

**Reply by vindocel** [reply]
I have an update
![image](https://user-images.githubusercontent.com/18473368/215747956-a65058a9-5090-4291-b185-84364e1f96e5.png)

**Reply by jge162** [reply]
I’ll check tomorrow.

**Reply by jge162** [reply]
```yaml
on:
  push:
    tags:
      - 'v*'
env:
  FILE_NAME: "Dark-Everywhere"
  FILE_EXTENSION: ".zip"
  BRANCHES: "1.19.3 1.19 1.18"
  PACKAGE_NAME: "assets pack.mcmeta pack.png"
  TAG_NAME: "${{ env.TAG_NAME || '0.0.1' }}"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create a release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ env.TAG_NAME }}"
        release_name: "Dark Everywhere ${{ env.TAG_NAME }}🌙"
        draft: true
        prerelease: false
    - name: Generate a zip archive for each branch
      run: |
        for branch in ${BRANCHES}; do
          zip -r "$FILE_NAME-$branch$FILE_EXTENSION" $PACKAGE_NAME
        done
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: "$FILE_NAME-$branch$FILE_EXTENSION"
        path: "$FILE_NAME-$branch$FILE_EXTENSION"
    - name: Update release
      uses: actions/update-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ env.RELEASE_ID }}
        body: "Build description here"
```

**Reply by vindocel** [reply]
doing a search I managed to make a working code using the dependencies

[zip-release](https://github.com/marketplace/actions/zip-release)
[automatic-releases](https://github.com/marketplace/actions/automatic-releases) 

however I'm having a problem, when the action builds and posts the RELEASE only the last file is sent
`Dark_Everywhere_1.18.zip`

however it is configured to send the 3 Zip files
`Dark_Everywhere_1.19.3.zip
Dark_Everywhere_1.19.zip
Dark_Everywhere_1.18.zip`

I don't know what could be wrong, could you help me?

``` YAML
name: create archive
on:
  push:
    paths:
      - '**.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Get next version
        uses: reecetech/version-increment@2022.10.3
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Archive 1.19.3 Branch Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.3.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Archive 1.19 Branch Release
        uses: actions/checkout@v2
        with:
          ref: '1.19'

      - name: Zip 1.19 Branch
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Archive 1.18 Branch Release
        uses: actions/checkout@v2
        with:
          ref: '1.18'

      - name: Zip 1.18 Branch
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.18.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Upload Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "${{ steps.version.outputs.version }}"
          prerelease: false
          title: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
          files: |
            Dark_Everywhere_1.19.3.zip
            Dark_Everywhere_1.19.zip
            Dark_Everywhere_1.18.zip
```

**Reply by jge162** [reply]
I’ll take a look later when I get home. 8 hours from now.

**Reply by jge162** [reply]
```yaml
name: create archive
on:
  push:
    paths:
      - '**.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Get next version
        uses: reecetech/version-increment@2022.10.3
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Archive 1.19.3 Branch Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.3.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Archive 1.19 Branch Release
        uses: actions/checkout@v2
        with:
          ref: '1.19'

      - name: Zip 1.19 Branch
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Archive 1.18 Branch Release
        uses: actions/checkout@v2
        with:
          ref: '1.18'

      - name: Zip 1.18 Branch
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.18.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Set files variable
        run: echo "::set-env name=FILES::Dark_Everywhere_1.19.3.zip Dark_Everywhere_1.19.zip Dark_Everywhere_1.18.zip"

      - name: Upload Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "${{ steps.version.outputs.version }}"
          prerelease: false
          title: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
          files: ${{ env.FILES }}
``` 

try this

**Reply by vindocel** [reply]
I had this error claiming some kind of security breach and also a link to this page
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
![image](https://user-images.githubusercontent.com/18473368/216809363-b2f95f15-aa3d-4b27-8b4f-fde68b07d828.png)

**Reply by jge162** [reply]
```yaml
name: create archive

on:
  push:
    paths:
      - '**.txt'
env:
  ENABLE_SET_ENV: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
``` 

try adding this on top to see if we can fix error with env.

**Reply by vindocel** [reply]
the error has now changed only to
```
Run echo "::set-env name=FILES::Dark_Everywhere_1.19.3.zip Dark_Everywhere_1.19.zip Dark_Everywhere_1.18.zip"
```
one way I see to fix this problem is to remove that part of the code
```YAML
      - name: Set files variable
        run: echo "::set-env name=FILES::Dark_Everywhere_1.19.3.zip Dark_Everywhere_1.19.zip Dark_Everywhere_1.18.zip"
```
and add a `.env` file to the root of the repository with the following code
```Shell
FILES=Dark_Everywhere_1.19.3.zip Dark_Everywhere_1.19.zip Dark_Everywhere_1.18.zip
```
this way the error no longer happens, but the files when released and posted do not contain any of the zip files of each branch

**Reply by jge162** [reply]
Remove the step that sets the "FILES" environment variable:

```yaml
name: Set files variable
run: echo "::set-env name=FILES::Dark_Everywhere_1.19.3.zip Dark_Everywhere_1.19.zip Dark_Everywhere_1.18.zip"
```
Instead of setting the environment variable, you can pass the list of files as a parameter directly to the upload action:

```yaml
name: Upload Release
uses: marvinpinto/action-automatic-releases@latest
with:
repo_token: ${{ secrets.GITHUB_TOKEN }}
automatic_release_tag: "${{ steps.version.outputs.version }}"
prerelease: false
title: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
files: Dark_Everywhere_1.19.3.zip Dark_Everywhere_1.19.zip Dark_Everywhere_1.18.zip
```

**Reply by vindocel** [reply]
that way it doesn't work either, to try to solve it I changed the dependency that generates the new release

` ncipollo/release-action@v1`

```YAML
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.version.outputs.version }}"
          name: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
```
even after i changed the dependency that generates the release it just kept posting the last zip
I came to the conclusion that the problem is in the dependency that creates the zip files, I think he can be rewriting each zip he does, leaving only the last one

**Reply by jge162** [reply]
If the zip files are being overwritten, you can try to change the filename in the zip-release action for each archive. You can add a variable such as the branch name or the version number to make sure each archive has a unique filename

```yaml
- name: Archive 1.19.3 Branch Release
  uses: thedoctor0/zip-release@0.7.1
  with:
    type: 'zip'
    filename: 'Dark_Everywhere_1.19.3_${{ env.BRANCH_NAME }}.zip'
    exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

- name: Archive 1.19 Branch Release
  uses: actions/checkout@v2
  with:
    ref: '1.19'

- name: Zip 1.19 Branch
  uses: thedoctor0/zip-release@0.7.1
  with:
    type: 'zip'
    filename: 'Dark_Everywhere_1.19_${{ env.BRANCH_NAME }}.zip'
    exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'
```

This way, each archive will have a unique filename based on its branch name and will not be overwritten by subsequent archives.

**Reply by Trunghoang25** [reply]
> that way it doesn't work either, to try to solve it I changed the dependency that generates the new release
> 
> ` ncipollo/release-action@v1`
> 
> ```yaml
>       - name: Upload Release
>         uses: ncipollo/release-action@v1
>         with:
>           tag: "${{ steps.version.outputs.version }}"
>           name: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
>           artifacts: "*.zip"
>           token: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> even after i changed the dependency that generates the release it just kept posting the last zip I came to the conclusion that the problem is in the dependency that creates the zip files, I think he can be rewriting each zip he does, leaving only the last one

1. Trunghoang25

**Reply by Trunghoang25** [reply]
> that way it doesn't work either, to try to solve it I changed the dependency that generates the new release
> 
> ` ncipollo/release-action@v1`
> 
> ```yaml
>       - name: Upload Release
>         uses: ncipollo/release-action@v1
>         with:
>           tag: "${{ steps.version.outputs.version }}"
>           name: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
>           artifacts: "*.zip"
>           token: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> even after i changed the dependency that generates the release it just kept posting the last zip I came to the conclusion that the problem is in the dependency that creates the zip files, I think he can be rewriting each zip he does, leaving only the last one

Trunghoang25

**Reply by vindocel** [reply]
bringing updates, my suspicion was correct, apparently for some reason every time I checked out on a different branch all the previous process disappeared or was deleted I don't know for sure
I solved the problem by having each zip that I created sent to the release individually as a draft with the next one simply rewriting on top, that way I keep all the files in the final draft

I also added another dependency that posts new releases
which has the function of taking the title and description of the commit made and putting it in the release description
```YAML
       - name: description
         uses: marvinpinto/action-automatic-releases@latest
         with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           automatic_release_tag: "${{ steps.version.outputs.version }}"
           prerelease: false
           draft: true
```
the dependency `ncipollo/release-action@v1`
if you have it as a draft, it overwrites it on top of it, not generating another one

final code was like this, working exactly as I wanted
```YAML
name: create archive
on:
  push:
    paths:
      - '**.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Get next version
        uses: reecetech/version-increment@2022.10.3
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Archive 1.19.3 Branch Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.3.zip'
          directory: './'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: descricao
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "${{ steps.version.outputs.version }}"
          prerelease: false
          draft: true

      - name: Upload Release 1.19.3
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          tag: "${{ steps.version.outputs.version }}"
          name: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
          artifacts: "Dark_Everywhere_1.19.3.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive 1.19 Branch Release
        uses: actions/checkout@v2
        with:
          ref: '1.19'

      - name: Zip 1.19 Branch
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.zip'
          directory: './'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Upload Release 1.19
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          tag: "${{ steps.version.outputs.version }}"
          name: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
          artifacts: "Dark_Everywhere_1.19.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive 1.18 Branch Release
        uses: actions/checkout@v2
        with:
          ref: '1.18'

      - name: Zip 1.18 Branch
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.18.zip'
          directory: './'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Upload Release 1.18
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          tag: "${{ steps.version.outputs.version }}"
          name: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
          artifacts: "Dark_Everywhere_1.18.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
```
I don't know if this is the best way to do it but it's the only one that worked so far

**Reply by jge162** [reply]
Yo if it does what you need. Amen. Glad to hear

**Reply by vindocel** [reply]
I improved the code by 100% after I started generating new releases for testing I noticed that it happened to go 2 releases because they were executed in parallel so sometimes it wasn't successful, I thought of adding a sleep to resolve it until it resolved but I was thinking of a way to make it even better, that's where I thought of separating it into 3 works, one for each version of the texture, I studied the versioning dependency a little and saw that I could put `current-version` which just repeated the current tag, since it was not possible to pulling the tag generated in job1 because it had closed and finding a way to export this information would be complicated

final code was like this, for me now it's perfect
post the final result here in case someone who has these doubts and sees this discussion can solve their problem too

```YAML

name: create archive
on:
  push:
    paths:
      - '**.txt'

jobs:
  texturepack1_19_3:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checking branch 1.19.3🔍
        uses: actions/checkout@v3

      - name: New Version for tag🏷️
        uses: reecetech/version-increment@2022.10.3
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Compressing texture from version 1.19.3📦
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.3.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: description🧾
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "v${{ steps.version.outputs.version }}"
          title: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
          prerelease: false
          draft: false
      - name: 3 seconds of waiting time⏱️
        run: sleep 3

      - name: Uploading the Texture 1.19.3📤
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: "v${{ steps.version.outputs.version }}"
          name: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

  texturepack1_19:
    needs: texturepack1_19_3
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checking branch 1.19🔍
        uses: actions/checkout@v3
        with:
          ref: '1.19'

      - name: New Version for tag🏷️
        uses: reecetech/version-increment@2022.10.3
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Compressing texture from version 1.19📦
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Uploading the Texture 1.19📤
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: "v${{ steps.version.outputs.current-version }}"
          name: "Dark Everywhere ${{ steps.version.outputs.current-version }}🌙"
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

  texturepack1_18:
    needs: texturepack1_19
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checking branch 1.18🔍
        uses: actions/checkout@v3
        with:
          ref: '1.18'

      - name: New Version for tag🏷️
        uses: reecetech/version-increment@2022.10.3
        id: version
        with:
          scheme: semver
          increment: patch
          
      - name: Compressing texture from version 1.18📦
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.18.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Uploading the Texture 1.18📤
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: "v${{ steps.version.outputs.current-version }}"
          name: "Dark Everywhere ${{ steps.version.outputs.current-version }}🌙"
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
```
