### DISCUSSION TITLE
Self-hosted macos m1 runner - Error: Can't use 'tar -xzf'

### DISCUSSION THREAD

**Discussion by fraguada** [community/community#45762] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello. I am trying to set up a self-hosted runner on an M1 mac with macos 12.2.1. According to the prerequisites, my machine should work. 

I went to my repo and set up the runner, and followed the instructions to enter the command line arguments. Runner was running my the machine. It gets a job, then I get this error:

Error: Can't use 'tar -xzf' extract archive file: /Users/luis.fraguada/dev/actions-runner/_work/_actions/_temp_41ab5c9e-ae1f-445b-92a2-820839d5934b/36376fe1-0243-4622-ab4d-8cb208b48700.tar.gz. return code: 1.

What I notice is that this file is never actually downloaded to the machine. So maybe the error has to do with that? Any tips?

The log:

```
Current runner version: '2.301.1'
Runner name: 'mySelfHostedMachine'
Runner group name: 'Default'
Machine name: 'mySelfHostedMachine'
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2.6.0' (SHA:dc323e67f16fb5f7663d20ff7941f27f5809e9b6)
Error: Can't use 'tar -xzf' extract archive file: /Users/luis.fraguada/dev/actions-runner/_work/_actions/_temp_41ab5c9e-ae1f-445b-92a2-820839d5934b/36376fe1-0243-4622-ab4d-8cb208b48700.tar.gz. return code: 1.

```
(have also tried with checkout 3.3.0)

The workflow:
```
name: render
on: [workflow_dispatch]
jobs:
  render_matrix:
    name: render ${{ matrix.target}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-11, self-hosted]
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-2019
            target: windows
          - os: macos-11
            target: macos
          - os: self-hosted
            target: macos
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - run: npm i
      - run: node index.js ${{ matrix.target}} ${{ matrix.os }}
```
