### DISCUSSION TITLE
Concurrency group name does not contain github.event.issue.number when it should

### DISCUSSION THREAD

**Discussion by benja-M-1** [community/community#45785] [Actions]
### Select Topic Area

Question

### Body

Hi, 

I have a workflow that runs on issues.opened, issues.reopened, issues.edited, issue_comment.created, and issue_comment.edited.

I want to make sure that there is only one workflow running for each issue. So I tried the following at the workflow level and the job level:

```
concurrency:
    group: submission-${{ github.event.issue.number }}
    cancel-in-progress: true
```
Since every event triggering the workflow contain the `issue` in the payload, there should not be any issue. It works perfectly within the steps, for example.

If I open issue A and then issue B, the running workflow for issue A is cancelled. I expected to have the two workflows running, as the group name is based on the issue number. But actually, it does not. The workflow for issue A is cancelled with the following message: `Canceling since a higher priority waiting request for 'submission-' exists`

Did I miss something?

**Comment by jge162** [comment]
Hello and good day @benja-M-1 you need to change the group name to a unique identifier that doesn't overlap between issues. For example, you could use a combination of the issue number and a timestamp. 


Pseudo code -> you need to test if it works. 

`submission-${{ github.event.issue.number }}-${{ timestamp }}, `

to ensure each workflow has a unique identifier. Because atm workflow is cancelled when a new workflow with a higher priority (a newer issue number) is triggered.

**Reply by jge162** [reply]
The idea behind pseudo code is to allow you to run multiple workflows for different issues simultaneously without cancelling any of them.

**Reply by benja-M-1** [reply]
Thanks @jge162 I am not sure this will solve my use case. I am sorry if I wasn't clear or if I get it wrong.

Here is what I would like to happen:
1. open A -> run workflow WA1 
2. open B -> run workflow WB1
3. update A (add a comment or edit the body of the issue) -> cancel workflow WA1 and run workflow WA2

With `submission-${{ github.event.issue.number }}-${{ timestamp }}` as concurrency group name, from my understanding, the group name would be unique everytime, as the timestamp won't be the same on each workflow. The result would look like

1. open A -> run workflow WA1, group name: `submission--1234567890`
2. open B -> run workflow WB1, group name: `submission--1234567891`
3. update A (add a comment or edit the body of the issue) -> run workflow WA2, group name: `submission--1234567893`

The thing that I don't understand is that the group name is `submission-` but I was expecting `submission-1`

**Reply by jge162** [reply]
This is pseudo code below. I have not tested or Ran. Just sharing ideas. You must test ->

```yaml
on:
  issues:
    types: [opened, reopened, edited, deleted]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  run_workflow:
    runs-on: ubuntu-latest
    name: Run Workflow
    concurrency:
      group: submission-${{ github.event.issue.number }}-${{ github.run_id }}
      cancel-in-progress: true
    steps:
      - name: Some Step
        run: echo "Running some step for issue number ${{ github.event.issue.number }}"
The concurrency group name is set to submission-${{ github.event.issue.number }}-${{ github.run_id }}, 
```
This combines the `issue.number` and the `run_id`of the workflow to ensure that the group name is unique for each run.

The `cancel-in-progress: true` option ensures that if a new workflow run is triggered while a previous run of the same workflow is still in progress, the previous run is updated then cancelled.

**Reply by benja-M-1** [reply]
<img width="531" alt="Screenshot 2023-01-30 at 15 00 14" src="https://user-images.githubusercontent.com/212269/215497892-59837288-a0ce-4cf8-b29f-faf9fd9e2e29.png">
As you can see on the screenshot here, it does not work as I would like. I believe the run id are the 208, 209 and 210. 210 should have cancel 209 as it is on the same issue 64.

**Reply by jge162** [reply]
Wow this is a good question.

**Reply by jge162** [reply]
I see exactly what you mean. 64 and 64. Hm

**Reply by jge162** [reply]
Would needs work? 

```yaml
needs:
  - name: submission-${{ github.event.issue.number }}
```

**Reply by jge162** [reply]
Probably not

**Reply by jge162** [reply]
Pseudo code again.-> you gotta test as I have not.  I think issue is with lock name and issue number. 

```yaml
steps:
- name: Acquire lock
  uses: actions/lock@v2
  with:
    path: lock-${{ github.event.issue.number }}
    timeout: 3600

- name: Your steps here
  ...

- name: Release lock
  uses: actions/lock@v2
  if: always()
  with:
    path: lock-${{ github.event.issue.number }}
    action: unlock
```

each issue will have a unique lock name based on its issue number, and workflows for different issues will not conflict with each others as with 64 and 64 above.
