### DISCUSSION TITLE
Action won't trigger

### DISCUSSION THREAD

**Discussion by dev0110** [community/community#45820] [Actions]
### Select Topic Area

Question

### Body

Hi, I'm currently following this tutorial - https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action

I have two different repositories where I am implementing this. The first works flawlessly with the output triggering the output of the action.yml file. In the other repository, instead of providing the expected output it instead gives me

with:
  who-to-greet: Parameter

I'm not sure why it isn't triggering the action.yml file like in the first repository. If it helps, the second repository has this action sitting in a PR instead of being on main, I'm not sure if I just need to merge it to main first as I wanted to test out if my action would work if it was just in the pull request. Thanks!

**Comment by MostafaWaleed0** [comment]
It's likely that the action is not triggered in the pull request because it is not set up to run in pull requests. By default, actions in pull requests only run when the changes are merged into the main branch.

You can modify the workflow file in the second repository to include a trigger for pull requests if you want the action to run in pull requests. Here's an example of how you can set this up in your workflow file:

```yaml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run action
      uses: ./action-repo
      with:
        my-input: 'Hello World!'
```
