### DISCUSSION TITLE
Is there possible to use Git Tags as a choice of workflow dispatch's input

### DISCUSSION THREAD

**Discussion by saenyakorn** [community/community#45871] [Actions] [answered]
### Select Topic Area

Product Feedback

## Use Case 

Assume that I have GitHub Action `deployment` workflow using `workflow_dispatch` for manually deploy my apps. On my project, I properly tag the commit with [Semantic Version](https://semver.org/), such as `1.0.2` (for single-app repo) or `web@1.0.2` (for monorepo). I would like to deploy specific app using GitHub Action using `tag` from Git History 

# Expectation

I would be great if we have `dropdown` for workflow dispatch's input like what `type: choice` can do.  

![Ui85o](https://user-images.githubusercontent.com/33742791/215703349-bb4c7e96-bf88-48c7-83ec-c9b60feef4e0.png)

# Workaround

Currently, I use `type: string` (default) to get user-preferred tag from GitHub. Like YAML file below. It works but inconvenient, since user may input a wrong tag name.  

```yaml
name: Release

on:
  workflow_dispatch:
    inputs:
      app:
        description: "The app to release. The name should be the same as name in package.json"
        required: true
      version:
        description: "The version to release. The version should be the same as version in package.json. For example, 1.0.0"
        required: true

jobs:
  release:
    name: Deploy

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ref/tags/${{ inputs.version }}
```

**Comment by smeruva1** [comment]
Hi, I am working on a similar issue. What you are asking is kinda there today. When you run a workflow, the default parameter is show on right hand side as "Branch: Main", click on it, you will see all branches and a tab for Tags. Note I found that tags that were created before the github actions workflow were created are disabled.

**Reply by atomiechen** [reply]
I think the "Use workflow from" dropdown that you see when manually triggering a workflow refers to the version of the workflow file, not the code to be checked out. The workflow file itself (the .yml or .yaml file) is version-controlled. The actual code that is checked out and used in the workflow is determined by the **actions/checkout** step in your workflow file, not the "Use workflow from" dropdown.

**Reply by brazarb** [reply]
I thought that too, but running a workflow with `workflow_dispatch` and selecting a tag e.g. `v1.0.3`, the `actions/checkout@v3` actually checks out the `${{ github.ref }}` which is set to the ref that triggered the workflow, in this case `v1.0.3`
![image](https://github.com/community/community/assets/111027880/1d1cb0e2-4a96-4436-9e96-50650e6162e9)

**Reply by Noyabronok** [reply]
The problem with this solution is that you're stuck using the workflow yml at time of tag creation

**Comment by sureshdevops99** [comment]
Is this still open or please share the script if you find the solution. Basically, we need to list the branches/tags names as a drop-down/list to select to trigger the workflow.

**Reply by brazarb** [reply]
I don't think there's a way to do that... I think if you select the tag from the `Use workflow from` field when dispatching the workflow, it will checkout the ref for that specific tag `not fully tested`.

Another option is to have an optional ref field in the inputs, and use the `actions/github-script` action to get the latest release.

${{ github.ref }} and ${{ github.ref_name }} always seem to be the branch/tag that triggered the workflow, so I think the above comment https://github.com/orgs/community/discussions/45871#discussioncomment-6321062 OR the below action could help you.

Something like so:

```yml
- uses: actions/github-script@v6
  id: get-release
  with:
    retries: 3
    script: |
      if (${{ startsWith(github.event.inputs.ref, 'v') }}) {
        return github.rest.repos.getReleaseByTag({
          owner: context.repo.owner,
          repo: context.repo.repo,
          tag: "${{ github.event.inputs.ref }}"
        })
      } else {
        return github.rest.repos.getReleaseByTag({
          owner: context.repo.owner,
          repo: context.repo.repo,
          tag: "${{ github.ref_name }}"
        })
      }
- name: Output Github Release
  if: steps.get-release.outputs.result != ''
  run: echo '${{ steps.get-release.outputs.result }}' | jq -r '.data.tag_name'
```

alternatively, in case inputs.ref is not specified you can just deploy the latest release.


```yml
- uses: actions/github-script@v6
  id: get-release
  with:
    # result-encoding: string
    retries: 3
    script: |
      if (${{ startsWith(github.event.inputs.ref, 'v') }}) {
        return github.rest.repos.getReleaseByTag({
          owner: context.repo.owner,
          repo: context.repo.repo,
          tag: "${{ github.event.inputs.ref }}"
        })
      } else {
        return github.rest.repos.getLatestRelease({
          owner: context.repo.owner,
          repo: context.repo.repo
        })
      }
- name: Output Github Release
  if: steps.get-release.outputs.result != ''
  run: echo '${{ steps.get-release.outputs.result }}' | jq -r '.data.tag_name'
```

**Comment by Koshalgarg155** [comment]
@saenyakorn 
are you able to achieve this?

**Comment by 64J0** [comment]
It would be great to have this feature!

**Comment by razorRun** [comment]
+1

**Comment by Shuvoid** [comment]
It would be really a nice feature to have!!!

**Comment by bwhitehead0** [comment]
yes, since we perform release actions against release tags, being able to select the tag instead of the branch would be ideal.

+1

**Comment by 64J0** [comment]
Hey, I'm creating a new custom action to update the options automatically whenever a new tag is created.

- Project repository: https://github.com/FsharpGHActions/git-tag-to-workflow-dispatch
- Action page on the marketplace: https://github.com/marketplace/actions/git-tags-to-workflow-dispatch
- Sample usage: https://github.com/FsharpGHActions/gh-samples/blob/main/.github/workflows/git-tag-to-workflow-dispatch.yml

Any feedback and ideas are welcome 🚀

**Comment by PramodKumarYadav** [comment]
I am surprised this doesn't exist since its such a common use case to deploy based on a specific tag. 

Thinking out loud, GitHub can create a new custom input type called **_tag_** that works a bit like dynamic search field. Where if a user clicks on this field, it dynamically presents user last 5 or 10 tags to pick the tag from. And if the user wants to go earlier than that, then they could probably start typing and search for it.

**Comment by saenyakorn** [comment, marked as answer]
<img width="348" alt="Screenshot 2567-07-03 at 16 09 48" src="https://github.com/community/community/assets/33742791/712d0eb6-b538-4492-b23a-181150ec9241">

I don't know when but we can now use Tag as a source of workflow_dispatch. Thank you GitHub Team. So, I decided to close this discussion now. Thank you everyone.

**Reply by 64J0** [reply]
Did you need to change something on the workflow yml file?

**Reply by saenyakorn** [reply]
No, I did not change anything. But, just in case you curious, here is my workflow file.

```yaml
name: Deploy Applications
run-name: Deploy Applications - ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Environment to build and publish e.g. sit, dev
        default: dev
        type: choice
        options:
          - dev
          - sit
          - uat
          - prod

jobs:
  release:
    name: Mapping applications - ${{ inputs.environment }}
    # ... job and steps
```

**Reply by ilya-allclear** [reply]
to clarify when you click the drop down `Use workflow from`  which will show `branch: defaultBranch` you will see tabs for Branches and Tags as shows on the screenshot from @saenyakorn 

no need to specify `checkout with ref`, you can test it with 
```
name: "Test"
on:
  workflow_dispatch:

jobs:
  deploy-function:
    name: Test
    runs-on: ubuntu-latest
    steps:

      # Checkout ourselves
      - name: Git checkout
        uses: actions/checkout@v4
```
