### DISCUSSION TITLE
Github Actions Deployment on 2 servers

### DISCUSSION THREAD

**Discussion by goldyrocky** [community/community#45884] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

Hi Devs,

How can I deploy same build on 2 different servers with github actions. On one server builds can be pushed and working fine but I want to push the same build to another server as well. 

Please help.

Thanks,

**Comment by jge162** [comment]
pseudo code example -> you must test and verify I have not run.  @goldyrocky 

```yaml
name: Deploy to servers

on:
  push:
    branches:
      - main

env:
  DEPLOY_HOST1: example.com
  DEPLOY_HOST2: another-example.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the application
      run: |
        # commands to build the application

    - name: Deploy to first server
      env:
        DEPLOY_HOST: ${{ env.DEPLOY_HOST1 }}
      run: |
        # commands to deploy the build to the first server

    - name: Deploy to second server
      env:
        DEPLOY_HOST: ${{ env.DEPLOY_HOST2 }}
      run: |
        # commands to deploy the build to the second server
```

I tested pseudo code below, no errors. 
![image](https://user-images.githubusercontent.com/31228460/215744851-9a671a87-788c-452e-9d13-90240154870b.png)
