### DISCUSSION TITLE
Path filtering does not work for merge_group triggers

### DISCUSSION THREAD

**Discussion by wjglerum** [community/community#45899] [Actions]
### Select Topic Area

Product Feedback

### Body

We are using this workaround listed here to handle skipped but required checks on pull requests
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

That all works fine for pull requests, but now we would also like to use this for our merge queue. It looked liked it was working, however the path filtering doesn't seem to work for `merge_group` events. Both the normal and skipped workflow are now triggered in parallel

See below for more info:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
- https://github.blog/changelog/2022-08-18-merge-group-webhook-event-and-github-actions-workflow-trigger/

It does seem to work for branch filters as mentioned above. How would we handle skipped but required checks in our merge queues?

**Comment by jackson-miller-tbol** [comment]
We do something similar, except we have a single workflow that handles skipping for multiple other workflows.  To get around the issue, we run a job to check the paths and then add a condition to the existing workflow based on that.  It does create another job, which adds another status to the PR (which I'd like to avoid) and adds a little time to the workflow.

It looks a bit like this:
```yaml
name: My workflow
on:
  merge_group:
    branches: ['main']
  pull_request:
    branches: ['main']
    paths:
      - '.github/workflows/this-workflow.yml'
      - 'some/path/**'
      - 'even/more/path/**'

jobs:
  # We need this because merge groups dont support path filters
  # https://github.com/community/community/discussions/45899
  changes:
    name: Determine if we need to run the workflow
    runs-on: ubuntu-latest
    outputs:
      changesFound: ${{ steps.filter.outputs.changesFound }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changesFound:
                    - '.github/workflows/this-workflow.yml'
                    - 'some/path/**'
                    - 'even/more/path/**'

  test:
    name: Main Workflow
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.changesFound == 'true' }}
    steps:
```
