### DISCUSSION TITLE
How can resolve "Waiting for a runner to pick up this job" ?

### DISCUSSION THREAD

**Discussion by salamisodikiolawale** [community/community#45907] [Actions]
### Select Topic Area

Question

### Body

When I launch my ci everything works fine with `runs-on: ubuntu-latest` but my runners does not detect 
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/2mZrK.png

With the value `self-hosted` my test remains at the first line waiting.

When I launch my ci everything works fine with `runs-on: ubuntu-latest` but my runners does not detect 
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/2mZrK.png

With the value `self-hosted` my test remains at the first line waiting.

I dont good understand thissituationbecause my CI is pass but runners github action aws dont detect to push on my aws server.

```
name: CI-CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  Frontend:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: user/frontend    
          tags: latest
          registry: docker.io
          dockerfile: frontend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  AuthService:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./microservices/AuthService
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      - name: TESTINT APP
        run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: user/auth_service      
          tags: latest
          registry: docker.io
          dockerfile: microservices/AuthService/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: build container
    #   run: docker-compose up -d --build

```
