### DISCUSSION TITLE
Securing third-party NPM tokens with Github

### DISCUSSION THREAD

**Discussion by pnalepa-bishopfox** [community/community#45911] [Actions]
### Select Topic Area

Question

### Body

hi, I have access to font awesome Pro version and it requires to use `.npmrc` file with proper token to authenticate download of the package. However I don't feel it's secure enough. **I'm wondering if Github Personal Access Token can help with it?**
If yes, I would need some guidance, because the docs are mentioned for the package owners which I'm not.
Any help or hints would be appreciated.

**Comment by airtower-luna** [comment]
You're right, you should definitely not commit a secret token to your repository. Take a look as [Actions secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets), they're meant for things like this. I'm not familiar enough with NPM to tell you exactly how to best use the secret with NPM, but the general idea is that you'd have the workflow provide it to NPM.

**Comment by hanseartic** [comment]
> However I don't feel it's secure enough. **I'm wondering if Github Personal Access Token can help with it?** If yes, I would need some guidance, because the docs are mentioned for the package owners which I'm not. 

According to the [documentation](https://fontawesome.com/docs/web/setup/packages#set-up-npm-token-for-all-projects) you can also use `npm config`. So in your case just have a setup-step configure npm for you:

```yaml
    steps:
      - name: configure fontawesome
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONT_AWESOME_PACKAGE_TOKEN }}
```

and store the token as a [secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) in your repo.

Also there is a [GitHub Action](https://github.com/marketplace/actions/use-npmrc) that can populate the `.npmrc` for you.
