### DISCUSSION TITLE
Problems with this template - provide the ID instead of index number

### DISCUSSION THREAD

**Discussion by wsmelton** [community/community#4595] [Projects and Issues]
Working with Issue Forms templating, developers are going to understand more easily that `body[x]` is the indexed list of the types but a non-programmer (one that may be managing the repository) could be confused by this.

I think having the `id` required on each type added to a form can provide an easier reference.

![image](https://user-images.githubusercontent.com/11204251/125179942-9e8a5f80-e1b9-11eb-8394-9219983d9947.png)

If the YAML was configured as such:

```yaml
body:
  - type: markdown
    id: intro-md
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! dbatools is testing out a beta of the [new Issues Forms](https://github.blog/changelog/2021-06-23-whats-new-with-github-issues/).
        Please ensure you provide as much information as asked to better assist in confirming and identifying a fix for the bug report.
  - type: markdown
    id: report-md
    value: "### Report"
  - type: checkboxes
    id: existing-issue
    attributes:
      label: "Is there an existing issues for this?"
      description: "Please search to see if an issue already exists for the bug you encountered."
      options:
        - label: "I have searched the existing issues"
          required: true
```
Instead of seeing `body[1]` it could show `body[report-md]` to make it more clear what area needs to be verified/checked.
