### DISCUSSION TITLE
Can't trigger Workflow on branch (other than the default "main")

### DISCUSSION THREAD

**Discussion by ilhan007** [community/community#45990] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello everybody,

I hope you can help with the following issue, that I currently have. 

I have a simple [workflow](https://github.com/SAP/ui5-webcomponents/blob/main/.github/workflows/release-custom-tag.yml) with workflow_dispatch, so that I can trigger the action manually.

The workflow is submitted in the default ("main") branch and while I can trigger it on "main", but I need to trigger it on different branch as well. I tried, but this did not work. I got the following error: **"Workflow does not exist or does not have a workflow_dispatch trigger in this branch'**

<img width="261" alt="Screenshot 2023-02-01 at 8 19 00" src="https://user-images.githubusercontent.com/15702139/215966611-1d77af97-8048-47a8-b0c7-cf8e5bc40e0b.png">

I thought, ok that other branch is older than "main", it does not have the workflow, so I submitted the same [workflow](https://github.com/SAP/ui5-webcomponents/blob/release-1.9.4/.github/workflows/release-custom-tag.yaml) with the same name in the second branch as well.

But the result is the same - still getting the same error.

Do you have explanation for that?

BR,
ilhan

**Comment by jge162** [comment]
@ilhan007 Hello and good day, check if the `workflow_dispatch` trigger is properly added to the workflow file in the ->`second branch.`
Try to trigger the workflow on the second branch again after refreshing the page.

If the branch is outdated, you may need to update it with the latest version of the `workflow file` from the "main" branch.

If this doesn't gotta be another issue elsewhere.

**Comment by ilhan007** [comment]
Hi @jge162 
thank you for replying so quickly

The workflow files are identical in both "main" and in the **second** branch


https://github.com/SAP/ui5-webcomponents/blob/release-1.9.4/.github/workflows/release-custom-tag.yaml

```yaml
name: Release-custom-tag

on:
  workflow_dispatch:
    inputs:
      npm_tag:
        description: 'npm dist tag'
        required: true
        default: 'sf'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    ----
```

https://github.com/SAP/ui5-webcomponents/blob/main/.github/workflows/release-custom-tag.yml
```yaml
name: Release-custom-tag

on:
  workflow_dispatch:
    inputs:
      npm_tag:
        description: 'npm dist tag'
        required: true
        default: 'sf'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    ---
```
        
The **second branch** is older than **main** in general, but the workflow file in question is up to date, completely same in both branches.
