### DISCUSSION TITLE
Rebase inside monorepo is firing wrong Github Action. How can I prevent this?

### DISCUSSION THREAD

**Discussion by kashishgrover** [community/community#45997] [Actions]
### Select Topic Area

Product Feedback

### Body

I have a mono repo project on GitHub which looks like this:

```
main_directory/apps/app_A
main_directory/apps/app_B
```

To create builds for **app_A**, I have a GitHub action which is configured as follows:

```
// build_app_A.yml


name: Build App A

on:
  push:
    paths:
      - "apps/app_A/**"
      - ".github/workflows/build_app_A.yml"
  workflow_dispatch:
    inputs:
      ref:
        description: "Git reference (commit, branch, or tag) to build"
        required: true
        default: "main"
...
```

Adding the on -> push -> paths thing makes sure that this GitHub action runs only when files inside the app_A subdirectory change, or when this workflow file itself changes.

This works fine. But there is a problem which is making it run redundantly.

Say I have a PR for app_B and this pull request has changes only inside the apps/app_B folder. 

This pull request became stale and I decide to rebase it on top of the main/master branch. The main/master branch has commits related to app_A and my app_B PR is behind these commits.

Now when I rebase this PR's branch and push it, even though the resulting diff has no changes related to app_A compared to the main/master branch, this GitHub action still runs.

My assumption was that given the paths inside my action, the action will run only when the git diff shown on GitHub has changes inside the specified paths, but this doesn't seem to be the case.

What am I missing here? Is there a way I can avoid these redundant builds?

Same question on Stack Overflow - https://stackoverflow.com/questions/75306258/rebase-inside-monorepo-is-firing-wrong-github-action-how-can-i-prevent-this
