### DISCUSSION TITLE
Why the workflow does or doesn't run on `pull_request` event?

### DISCUSSION THREAD

**Discussion by Felixoid** [community/community#46022] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello. We have a case that works as intended, although I can't get why.

So, we have a bunch of workflows, but I assume only [pull_request.yml](https://github.com/ClickHouse/ClickHouse/blob/6cd0b51/.github/workflows/pull_request.yml#L7-L19) and [release_branches.yml](https://github.com/ClickHouse/ClickHouse/blob/6cd0b51127647e8f2f8191f1e5e24ca24e98f14c/.github/workflows/release_branches.yml#L7-L12) are supposed to be overviewed.

The first one has `on` section:

```yaml
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - synchronize
      - reopened
      - opened
    branches:
      - master
    paths-ignore:
      - 'docker/docs/**'
      - 'docs/**'
      - 'website/**'
      - 'utils/check-style/aspell-ignore/**'
```

and the second one:

```yaml
on: # yamllint disable-line rule:truthy
  push:
    branches:
      # 22.1 and 22.10
      - '2[1-9].[1-9][0-9]'
      - '2[1-9].[1-9]'
```

Branches like `22.5`, `22.11`, and so on are release branches, where we launch the specific workflow. My question is why is the normal pull_request.yml launched on each first commit to the release branches, when the PR is opened, for example in [23.1](https://github.com/ClickHouse/ClickHouse/pull/45633), [22.11](https://github.com/ClickHouse/ClickHouse/pull/43347), but not for the next pushes? Why for [22.12](https://github.com/ClickHouse/ClickHouse/pull/44274) the pull_request.yml was triggered twice, for a0138a2 and 70f7dfc?

If I'd like to, how can I reproduce the same behavior? What should I do to avoid the first launches for release branches too?
