### DISCUSSION TITLE
Can't get GitHub Action secrets/env variables working.

### DISCUSSION THREAD

**Discussion by Skuffies** [community/community#46048] [Actions]
### Select Topic Area

Product Feedback

### Body

Hello! I am trying to pass env variables through GitHub Actions into my NodeJS scriop. I have tried several methods but they always come back as undefined. I've looked at [this](https://stackoverflow.com/questions/59686823/how-can-i-use-github-secrets-in-js-files) post but still can't get it to work. Here is one of the methods I tried:
```
const { SECRETKEY } = process.env;

if (SECRETKEY === '1234') {
    console.log('Success!');
}

console.log(SECRETKEY)
console.log(process.env.SECRETKEY)
```
```
name: node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: node -e "console.log(process.env.SECRETKEY)"
      env:
        SECRETKEY: ${{ secrets.SECRETKEY }}
    - run: npm i
    - run: pm2 stop 4 
    - run: pm2 start 4
    - run: pm2 save
```
