### DISCUSSION TITLE
Adding a container job to a matrix

### DISCUSSION THREAD

**Discussion by andy5995** [community/community#46071] [Actions]
### Select Topic Area

Question

### Body

Is there a way to add a container job to a matrix?

For example, I have this:

```
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        compiler: [gcc, clang]
        include:
          - os: macos-latest
    runs-on: ${{ matrix.os }}
```

And I'd like to add one container job to the 'ubuntu-20.04' job.  Normally the [container](https://docs.github.com/en/actions/using-containerized-services/about-service-containers#creating-service-containers) is specified after the 'runs-on' field:

```
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: andy5995/slackware-build-essential:15.0
```

I'd like to add the container job to one of the Ubuntu jobs already specified in the matrix. Is it possible?

**Comment by andy5995** [comment]
I see one way here:

https://github.com/altendky/alqtendpy/blob/b375b1d9189f125828fdabbf2d329e5b1d04ff21/.github/workflows/ci.yml#L24-L75

I'm trying this at the moment:

```
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        compiler: [gcc, clang]
        include:
          - os: macos-latest
          - os: macos-latest
            vm: freebsd
          - container: 'andy5995/slackware-build-essential:15.0'
            compiler: gcc

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
```

It's almost working, but instead of a third Ubuntu job, it's using the container for both the existing Ubuntu jobs...

**Comment by andy5995** [comment]
Here's how I did it:

```yaml
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu-20.04, ubuntu-22.04]
        cc: [gcc, clang]
        include:
          - os: macos-latest
          - os: ubuntu-20.04
            cc: slackware
            container: 'andy5995/slackware-build-essential:15.0'

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:

    - uses: actions/checkout@v3
 ```

https://github.com/theimpossibleastronaut/rmw/pull/377
