### DISCUSSION TITLE
Issue forms should retain SOME labels

### DISCUSSION THREAD

**Discussion by ffissore** [community/community#46120] [Projects and Issues]
### Select Topic Area

Product Feedback

### Body

At the moment, as per documentation, we can add markdown snippets like
```yaml
body:
- type: markdown
  attributes:
    value: "## Thank you for contributing to our project!"
```
However, these snippets don't end up in the resulting issue, as stated in the docs

**It would be nice to have a way to retain these snippets, as they could contain context information for the developer.**

Our use case is that of first-line support opening issues for the dev team: these issues contain a link to the playbook that the on-call dev will have to follow. At the moment we are "cheating" by adding a textarea, and telling first-line support folks to not edit it.
