### DISCUSSION TITLE
Compile a Go project with `CGO_ENABLED=1` across Linux/Darwin/Windows

### DISCUSSION THREAD

**Discussion by peterschmidt85** [community/community#46166] [Actions]
Anyone here knows how to compile a Go project with `CGO_ENABLED=1` across Linux/Darwin/Windows in GitHub Actions? Looking for a simple example. 😬

**Comment by airtower-luna** [comment]
It's probably easiest if you start from the [Go starter workflow](https://github.com/actions/starter-workflows/blob/main/ci/go.yml) and add two things:

1. A [matrix](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) to set `runs-on` to each of the OSes you want to test with.
2. An [`env` section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv) that sets `CGO_ENABLED` to `1` (either for a step, or the whole job or even workflow). Or you can just include `CGO_ENABLED=1` in the command line, `run` sections just run your commands in a shell.

For example (modified excerpt from that starter workflow):

```yaml
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
      env:
        CGO_ENABLED: 1
```
