### DISCUSSION TITLE
Passing a secret as input to a reusable workflow

### DISCUSSION THREAD

**Discussion by smokedlinq** [community/community#46336] [Actions]
### Select Topic Area

Question

### Body

I am trying to pass a secret to a reusable workflow input, but it is failing with the error: 

`The workflow is not valid. .github/workflows/main.yml (Line: 10, Col: 22): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.ENDPOINT_KEY`

Reusable workflow example to repro:

```yml
on:
  workflow_call:
    inputs:
      configuration:
        type: string
        required: false
        default: ''

jobs:
  widget:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo $CONFIGURATION
      env:
        CONFIGURATION: ${{ inputs.configuration }}
```

Being consumed as such:

```yml
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      configuration: |
        key: ${{ secrets.ENDPOINT_KEY }}
```

Any suggestions on how I might be able to pass secrets as part of a larger string as the input to the reusable workflow?

**Comment by jge162** [comment]


**Reply by smokedlinq** [reply]
I'm trying to use it at the job level, you can't call a reusable workflow from a step in a job. And env isn't supported on the reusable workflow and any env in the parent workflow isn't inherited in the child.

**Comment by swathida-byte** [comment]
You can use something of this sort for passing secrets in re-usable workflow files

Reusable workflow example to repro:
```
on:
  workflow_call:
    secrets:
      ART_GITHUB_INSTALLATION_MAP:
        required: true
      ART_GITHUB_PRIVATE_KEY:
        required: true
      ART_SECRETS_FILE:
        required: true
```
Being consumed as such:

```
name: test
on:
  pull_request:
jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      ART_SECRETS_FILE: ${{secrets.ART_SECRETS_FILE}}
      ART_GITHUB_INSTALLATION_MAP: ${{secrets.ART_GITHUB_INSTALLATION_MAP}}
      ART_GITHUB_PRIVATE_KEY: ${{secrets.ART_GITHUB_PRIVATE_KEY}}
```

**Reply by smokedlinq** [reply]
I am looking to pass a composed set of values to the workflow via an input that may need to use secrets. The workflow itself don't know all the secrets or values that may need to be used to complete the job.

**Reply by smokedlinq** [reply]
I'm dense, switch the value from inputs to secrets solves this problem.

```yml
on:
  workflow_call:
    secrets:
      configuration:
        type: string
        required: false
        default: ''
jobs:
  widget:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo $CONFIGURATION
      env:
        CONFIGURATION: ${{ secrets.configuration }}
```
