### DISCUSSION TITLE
Error 500 when saving form

### DISCUSSION THREAD

**Discussion by shaedrich** [community/community#4643] [Projects and Issues] [answered]
I tried using the new issue forms and got them working with one field. But when I added more fields and tried to save the file, I always got this error message. I know, this feature is still in beta but maybe someone knows how to fix this and might find this information helpful.
![grafik](https://user-images.githubusercontent.com/11225821/125582968-0e301b79-bb29-43b6-bc9e-9f8dea46d41b.png)

**Comment by KnightMiner** [comment]
I recently got the same issue when creating one of my forms. The problem I had was I accidently added the following in the body:
```yml
  - type: markdown
    attributes: |
        Some text here
```
instead of
```yml
  - type: markdown
    attributes:
      value: |
        Some text here
```
(note the lack of "`value`")

Making a different error with the issue template did not cause a 500 error (using Yes/No for dropdown options), instead showing an error, so I assume there are just some cases that do not process well.
