### DISCUSSION TITLE
Conditionally include text

### DISCUSSION THREAD

**Discussion by s0undt3ch** [community/community#46491] [Actions] [answered]
### Select Topic Area

Product Feedback

### Body

Consider the following action:

```yaml
---
name: setup-salt-version
description: Setup Salt Version
inputs:
  cwd:
    type: string
    default: ""
  salt-version:
    type: string
    default: ""
    description: >
      The Salt version to set prior to running tests or building packages.
      If not set, it is discover at run time, like, for example, capturing
      the output of running `python3 salt/version.py`
  validate-version:
    type: bool
    default: false
    description: Validate the passed version.
outputs:
  salt-version:
    value: ${{ steps.setup-salt-version.outputs.salt-version }}
    description: The Salt version written to `salt/_version.txt`

env:
  COLUMNS: 160

runs:
  using: composite

  steps:

    - name: Setup Salt Version
      id: setup-salt-version
      shell: bash
      run: |
        if [ "${{ inputs.cwd }}" != "" ]; then
          cd "${{ inputs.cwd }}"
        fi
        tools pkg set-salt-version ${{ inputs.validate-version && '--validate-version' || '' }} ${{ inputs.salt-version }}
```

It doesn't matter if I pass `validate-version: true` or `validate-version: false` when calling this action, `--validate-version` is always included.

Are there other ways to achieve this, besides 2 separate steps?
