### DISCUSSION TITLE
Automatically fetch versions (for dropdown) from GitHub releases

### DISCUSSION THREAD

**Discussion by mrousavy** [community/community#4649] [Projects and Issues] [answered]
I have a repository with pretty fast release cycles, and it would be awesome if there was an option in a GitHub issue template to automatically fetch versions in a dropdown from GitHub releases. So e.g. if I add:

```yml
  - type: releases_dropdown   # <-- relevant type
    id: version
    attributes:
      label: Which VisionCamera version are you using?
```

then it should automatically fill in all versions from the GitHub releases page.
