### DISCUSSION TITLE
Pass artifact to a reusable workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#46507] [Actions]
### Select Topic Area

Question

### Body

I assuming I have something like the following

```
  jobs:
   
   build-something:
    runs-on: ubuntu-latest
   steps:
    - name: build something here
      shell: bash
      run: command-to-create-artifact at bin/artifact


   reusable-workflow:
   uses: .github/.workflows/my-reusable.yaml
 ```

is there a way to make my `/bin/artifact` available to `my-reusable` workflow`?
