### DISCUSSION TITLE
Support non-inline scripts for action steps

### DISCUSSION THREAD

**Discussion by mbrancato** [community/community#46528] [Actions]
### Select Topic Area

Product Feedback

### Body

This is a request to support non-inline content for action steps (`jobs.<job_id>.steps[*].run`).

An example would be something like the following:

```yaml
steps:
  - name: Do something cool
    shell: python
    script: ${{ github.action_path }}/cool.py
```

This would better allow using common development practices like using an IDE and linting tools, or even having tests that live with the action script code.

**Comment by norwd** [comment]
Hi @mbrancato, you can absolutely do this the `bash` shell option:

```yaml
...

# this part isn't necessary on ubuntu on macOS runners, but it's good to be explicit :)
defaults:
  run:
    shell: bash

jobs:
  python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Do something cool"
        run: python path/to/cool.py
```

Or if the script is already executable (use `chmod +x`) and uses a `#!/usr/bin/env python` shebang line, you can call it implicitly as just a path:

```yaml
      - name: "Do something cool"
        run: ./path/to/cool.py # as opposed to `python path/to/cool.py`
```

**Reply by mbrancato** [reply]
The latter is a good option, but composite actions do require the `shell` key on every step.  The `defaults` are not supported in those.

So maybe like the following is an option:

```yaml
steps:
  - name: Do something cool
    shell: python
    run: ${{ github.action_path }}/cool.py
```

https://github.com/SchemaStore/schemastore/blob/8022867653c8411fa6da76ff8889571fdec4ceaf/src/schemas/json/github-action.json#L152
