### DISCUSSION TITLE
How to get a caller name inside workflow_call?

### DISCUSSION THREAD

**Discussion by leshikus** [community/community#46638] [Actions]
### Select Topic Area

Question

### Body

Please check the following snippet for the question details

```
main.yml:
[...]
jobs:
  job-containerized:
    uses: ./.github/workflows/run-docker.yml

run-docker.yml:
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo how to get "job-containerized" here? maybe from some env

```
