### DISCUSSION TITLE
Set the default shell for a composite action

### DISCUSSION THREAD

**Discussion by colinparsonscom** [community/community#46670] [Actions]
### Select Topic Area

Product Feedback

### Body

It'd be nice if we could set the default shell for all steps in a composite action, the same way we can set the default shell for all steps in a job or (more broadly) for all steps in a workflow.

Example: right now, we have to do this to explicitly set the shell:

```
name: My action
author: me
description: My custom action

runs:
  using: composite
  
  steps:
    - name: Step 1
      shell: bash
      run: echo "step 1"

    - name: Step 2
      shell: bash
      run: echo "step 2"
```

That adds up to a decent amount of boilerplate when creating a composite action with a dozen or so steps. It'd be cleaner to just specify the default shell once:

```
name: My action
author: me
description: My custom action

runs:
  using: composite

  defaults:
    run:
      shell: bash
  
  steps:
    - name: Step 1
      run: echo "step 1"

    - name: Step 2
      run: echo "step 2"
```
