### DISCUSSION TITLE
Validations not working in Issue Form Template for Textarea

### DISCUSSION THREAD

**Discussion by leovipin1** [community/community#46714] [Projects and Issues]
### Select Topic Area

Bug

### Body

The issue template generated using the issue form syntax is not validating the textarea, i have specified the validations required as true but still accepts empty textarea, as you can see in the image the submit issue button is highlighted even though there is no input in textareas

![github issue](https://user-images.githubusercontent.com/1716836/217475989-6b1ce845-7b8f-4ba6-9a12-e87540ecf220.jpg)

code for issue template
```yml
name: Feature Request
description: Submit a Feature Request
title: "[Feature]: "
labels: feature
assignees:
  - leovipin1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature Request Form!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the feature that is being requested
      placeholder: Tell us what you want to see!
    validations:
      required: true
  - type: textarea
    id: userstories
    attributes:
      label: User Stories required for this Feature
      description: Kindly specify the list of User Stories that will be worked upon for this feature to be Completed
      placeholder: |
        List of User Stories in Tasklist format
        - [ ] #3 ex.
        - [ ] #15 ex.
        - [ ] #17 ex.
    validations:
      required: true
```
