### DISCUSSION TITLE
Validations not working with Issue Form Textarea

### DISCUSSION THREAD

**Discussion by leovipin1** [community/community#46715] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Bug

### Body

The issue template generated using the issue form syntax is not validating the textarea, i have specified the validations required as true but still accepts empty textarea, as you can see in the image the submit issue button is highlighted even though there is no input in textareas

![github issue](https://user-images.githubusercontent.com/1716836/217475989-6b1ce845-7b8f-4ba6-9a12-e87540ecf220.jpg)

code for issue template
```yml
name: Feature Request
description: Submit a Feature Request
title: "[Feature]: "
labels: feature
assignees:
  - leovipin1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature Request Form!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the feature that is being requested
      placeholder: Tell us what you want to see!
    validations:
      required: true
  - type: textarea
    id: userstories
    attributes:
      label: User Stories required for this Feature
      description: Kindly specify the list of User Stories that will be worked upon for this feature to be Completed
      placeholder: |
        List of User Stories in Tasklist format
        - [ ] #3 ex.
        - [ ] #15 ex.
        - [ ] #17 ex.
    validations:
      required: true
```

**Comment by jge162** [comment]
@leovipin1 Try adding this to the end, this will ensure that the form cannot be submitted unless both `textarea` fields have been filled in by the ->`user.` Also this is pseudo code, I do not know if it will work. Just trying to give you assistance. You have to test and modify for you use case. 

```yaml
 List of User Stories in Tasklist format
        - [ ] #3 ex.
        - [ ] #15 ex.
        - [ ] #17 ex.
    validations:
      required: true
  - type: submit
    id: submit
    attributes:
      value: Submit Feature Request
      disabled: input[id='description'] == '' || input[id='userstories'] == ''
```
