### DISCUSSION TITLE
Setting `environment` with an expression

### DISCUSSION THREAD

**Discussion by ssyberg** [community/community#46738] [Actions] [answered]
### Select Topic Area

Question

### Body

This seems so basic that I feel like I must be missing something big, but I'm having trouble dynamically setting the `environment` in my flows. In this context I'm setting the `environment` to the target deployment destination (`staging` or `production`) based on the branch triggering the flow (and hence use environment based secrets), but thus far have been unable set set the environment dynamically. Here's the basic idea

```
jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: ${{ TARGET_ENV }}
```

It seems like `environment` can't evaluate an expression but I'm kind of at a loss, I can't really imagine a use case where you'd want the environment hard coded, seems to completely defeat the purpose of setting the environment to determine which secrets to use. What am I missing?

**Comment by ssyberg** [comment, marked as answer]
I figured this out, it has something to do with the scope/context when environment is evaluated, I don't totally understand it, but this did the trick:
```
jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: 
      name: ${{ github.ref_name }}
```
