### DISCUSSION TITLE
In a workflow, how to get the status of matrix sub-jobs?

### DISCUSSION THREAD

**Discussion by smallprogram** [community/community#46748] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a action like this:
```yml

name: Build-Multi-Platform

jobs:
  job_init: 
    runs-on: ubuntu-latest
    outputs:
      output_release_tag: ${{ steps.gen_release_tag.outputs.release_tag }}
    steps:
      - id: gen_release_tag
        run: echo "release_tag=multi-platform_$(date +"%Y.%m.%d_%H%M")" >> $GITHUB_OUTPUT

  job_build:
    needs: job_init
    runs-on: ubuntu-latest
    name: Build-OpenWrt-${{ matrix.platforms }}
    strategy:
      fail-fast: false
      matrix:
        platforms: [a, b, c, d, e, f]

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Compile the firmware
      id: compile
      run: |
        # some build code

    - name: Upload firmware to release
      with:
        # uploade release code

  job_check_status:
    if: ${{always()}}
    needs: job_build
    runs-on: ubuntu-latest

    steps:
    - name: check status
      run: |
         # how to output every matrix job status
```

How to get the final status of each sub-job in the matrix through job_check_status？
