### DISCUSSION TITLE
Reusable workflow job name defined for Status checks that are required in branch protection help

### DISCUSSION THREAD

**Discussion by codebydant** [community/community#46752] [Actions]
### Select Topic Area

Question

### Body

Hi team,

Greetings.

I am using a branch protection rule to make sure a couple of checks are required when opening a pull request.

![Screenshot from 2023-02-08 10-26-40](https://user-images.githubusercontent.com/115469901/217574027-a694e886-7f12-4d5c-8333-5a4cd891729b.png)

I have a situation where I have a reusable workflow being called from 2 levels of depth.

```
ci_pipeline.yml --> calls --> reusable_ci.yml -- |
                                                 | ---> reusable_commit_validator.yml
                                                 | ---> reusable_pr_title_validator.yml
                                                 | ---> reusable_notebook_validator.yml
```

The name of the job in the `ci_pipeline.yml` is:

```yml
jobs:
  # reusable ci pipeline
  call_reusable_ci_workflow:
    name: "CI"
    uses: ./.github/workflows/reusable_ci.yml
```

The name of the job in the `reusable_ci.yml` is:

```yml
jobs:
  # reusable commit validator
  call_reusable_commit_validator_workflow:
    name: "CI"
    uses: ./.github/workflows/reusable_commit_validator.yml
```

The name of the job in the `reusable_commit_validator.yml` is:

```yml
jobs:
  # commit message validator
  commit_validator:
    name: Commit Validator
    runs-on: ubuntu-22.04
    ...
```

The problem is that the required status checks expect to find a pattern

`CI / Commit Validator` in the actions, but I have `CI / CI / Commit Validator`:

![Screenshot from 2023-02-08 10-36-39](https://user-images.githubusercontent.com/115469901/217576596-c126df69-7269-45ef-9e9c-aa2a7dfea6dd.png)

And the checks are not covered:

![Screenshot from 2023-02-08 10-42-59](https://user-images.githubusercontent.com/115469901/217578311-a584a629-ba32-4a4c-8e51-7c17e2ecc1b6.png)

Is there an approach to handling a situation like this?

### Proposed solution
Add a `hide-name` parameter in the yaml syntax to hide the name for a specific workflow

something like:

```yml
name: Reusable Workflow
hide-name: true

on:
 ...
```
