### DISCUSSION TITLE
`squash and merge` not triggering `push`

### DISCUSSION THREAD

**Discussion by ejether** [community/community#46772] [Actions]
### Select Topic Area

Question

### Body

Greetings!
I'm seeing some unexpected behavior in the way `squash and merged` Pull Requests are emitting, or not emitting the `push` event.
Given the following:
```
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - "main"
```

In a repository with branch protection enforcing linear history on the `main` branch, when a PR is created, and merged to `main` through the `squash and merge` action, the workflow does not run. It _seems_ like there is no `push` event emitted on the `squash and merge` when it is a linear history/fast forward. `rebase and merge` _does_ trigger the workflow. 

The behavior I expect is that on merging a PR, regardless of the history or merge behavior, the `push` event should trigger the workflow but that does not seem to be the case.

Is this a bug or a feature 😅 

If bug, do you have suggested work around?
If feature, do you have a suggestion as to how to get the behavior I expect? 

Thanks!
