### DISCUSSION TITLE
How to prevent duplicate actions (push and pull_request)

### DISCUSSION THREAD

**Discussion by adamjstewart** [community/community#46775] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a set of unit tests I would like to run on every commit. My first instinct was to use:
```yaml
on: push
```
This worked for branches within our repo, but didn't cover PRs contributed from forks. So I added:
```yaml
on: [push, pull_request]
```
This covered every possible case, but resulted in duplicate tests for both push and pull_request for internal PR branches. Following the advice [here](https://stackoverflow.com/a/70767151/5828163), we next tried:
```yaml
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
```
This works for most cases, but we also have release branches we care about. So I added those:
```yaml
on:
  push:
    branches:
    - main
    - releases/**
  pull_request:
    branches:
    - main
    - releases/**
```
Unfortunately, this results in the tests being duplicated on the releases branch. Is there any way to fix this? Preferably things would run on every branch (not just main and release) for every push or pull_request, but never be duplicated.
