### DISCUSSION TITLE
Define a list of elements in a variable

### DISCUSSION THREAD

**Discussion by gforcada** [community/community#46785] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi! 👋🏾 

I'm trying to get an organization level workflow to get the list of Operating systems it should run from a variable, i.e.:

Variable:

`TEST_OS_VERSION = ['"ubuntu", "ubuntu-20.04"']`

Workflow:
```yaml
...
jobs:
  test:
    strategy:
      matrix:
        os: ${{ vars.TEST_OS_VERSIONS }}
...
```

Unfortunately that does not work, trying it like the following either:

Variable:

`TEST_OS_VERSION = '"ubuntu", "ubuntu-20.04"'`

Workflow:
```yaml
...
jobs:
  test:
    strategy:
      matrix:
        os: [ ${{ vars.TEST_OS_VERSIONS }} ]
...
```

😢 

Any idea on how to use variables to to store a list of elements?

For my projects and the organizations I participate in, being able to define on a global level the list of operating systems and python versions __and__ override them on a per repository basis, would help us reduce, _a lot_, the workflows maintenance 🍀 🙏🏾

**Comment by SilasRodrigues19** [comment]
Hey @gforcada 

Did you try this way below?

```yml
jobs:
  test:
    name: Testing on
    runs-on:
      - ubuntu-latest
      - macos-latest
      - windows-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.10", 3.9, 3.8, 3.7, pypy-3.9]
    steps:
      ...
```

**Reply by gforcada** [reply]
That's what we are using, yes, but I want to store `["3.11", "3.10", 3.9, 3.8, 3.7, pypy-3.9]` into a global variable, and being able to override it on a per repository basis.

You are not using any variable here.

**Reply by SilasRodrigues19** [reply]
You can define a global `environment variable` in the GitHub Actions configuration file and use it in your workflow. 

```bash
env:
  PYTHON_VERSIONS: "3.11,3.10,3.9,3.8,3.7,pypy-3.9"
```

Then, you can use this variable in your strategy matrix by replacing ["3.11", "3.10", 3.9, 3.8, 3.7, pypy-3.9] with ${{ env.PYTHON_VERSIONS }}. 

```yml
strategy:
  matrix:
    python-version: ${{ env.PYTHON_VERSIONS }}
```

**Reply by gforcada** [reply]
Thanks 🙏🏾 but seems that it still does not work 😕 


Error when evaluating 'strategy' for job 'test'. shared-workflows/tests.yml (Line: 16, Col: 13): Unexpected type of value '"ubuntu,ubuntu-20.04"', expected type: Sequence.

**Reply by brianjmurrell** [reply]
Perhaps this will work:

```yaml
strategy:
  matrix:
    python-version: [${{ env.PYTHON_VERSIONS }}]
```

**Comment by ChristopherHX** [comment, marked as answer]
You can use [fromJSON](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson) to parse your variable (json array) into an Array object for the matrix.
```yaml
...
jobs:
  test:
    strategy:
      matrix:
        os: ${{ fromJSON(vars.TEST_OS_VERSIONS) }}
...
```

You may run into issues with `pull_request` workflows, because `vars.TEST_OS_VERSIONS` might currently end up undefined.

**Reply by gforcada** [reply]
Yes, thanks! 🙏🏾 🎊 that's what I was looking for 😄

**Reply by SergkeiM** [reply]
Hi @gforcada `${{ fromJSON(vars.TEST_OS_VERSIONS) }}` works for you?

Can you be so kind and share the format you store `VERSIONS` inside `Repo var`?

**Reply by gforcada** [reply]
@SergkeiM as a JSON:

```json
["ubuntu-latest", "macosx-latest"]
```
🎉

**Reply by SergkeiM** [reply]
Hi @gforcada 

Strange for some reason I can't get it worked:

```yaml
strategy:
      matrix: 
        domain: ${{ fromJson(vars.DOMAINS) }}
```
![image](https://github.com/community/community/assets/3294939/5180791d-644c-4ee0-b727-3e1e6dd1097c)


```cli
Error when evaluating 'strategy' for job 'deploy'. /actions/.github/workflows/domain.yml@master (Line: 52, Col: 17): Error parsing fromJson,/actions/.github/workflows/domain.yml@master (Line: 52, Col: 17): Error reading JToken from JsonReader. Path '', line 0, position 0.
```

**Reply by ChristopherHX** [reply]
@SergkeiM is your workflow run triggered by `on: pull_request`? That could explain why vars.DOMAINS is still empty as GitHub doesn't support this scenario

**Reply by SergkeiM** [reply]
Hi @ChristopherHX 

no is set to `on: workflow_dispatch`, but I use `vars.DOMAINS` inside `Reusable Workflow`, as workaround, I save `DOMAINS` as comma separated string and in job before do:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      domains: ${{ steps.domains.outputs.domains }}
     - name: Set up domains
        id: domains
        run: |
          domains=$(echo ${{ vars.DOMAINS }} | jq -Rrc 'split(",")')
          echo "domains=$domains" >> "$GITHUB_OUTPUT"
   deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        domain: ${{ fromJson(needs.build.outputs.domains) }}
```
