### DISCUSSION TITLE
GitHub action triggers like pull_request [labeled, unlabeled] should support label filter

### DISCUSSION THREAD

**Discussion by zhouzhuojie** [community/community#4679] [Actions]
# Context

If we have workflows attached with `on.pull_request [labeled, unlabeled]` event trigger, it runs no matter what labels are added/removed. 

- This may not be the ideal scenario that the workflow may be expensive or taking long time to run, and it would be great if the labeled action can also have a label filter that get triggered.
- And many unnecessary workflows/jobs are showing as "skipped" in the UI, not a great user experience.

# Proposal syntax

```
on:
  pull_request:
    types: [labeled, unlabeled]
    label_filter: '*' # which is the default, and we can use the same file pattern match like 'test', '*test', '*bot'
```

OR
```
on:
  pull_request:
    types: [labeled, labeled:*, unlabeled:*, labeled:*test, labeled:*bot]
```

**Comment by seemethere** [comment]
+1 This is a key feature for us, it allows us to have workflows triggered on specific labels instead of having to do the current hack like:

```
  should-run:
    runs-on: ubuntu-latest
    if: >-
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.labels.*.name, 'ci/future')
    steps:
      - run: echo "noop"
```

Which results in a bunch of skipped checks being present in our CI statuses:

![image](https://user-images.githubusercontent.com/1700823/125991900-b31241bf-4e1a-4922-99da-8752fa1fb4ea.png)

Reference PR: https://github.com/pytorch/pytorch/pull/61720
