### DISCUSSION TITLE
npm run prod not actually running in workflow, despite giving success message.

### DISCUSSION THREAD

**Discussion by hyphen81** [community/community#46845] [Actions]
### Select Topic Area

Question

### Body

I don't believe that `nmp run prod` is actually running(?) in my github action despite not throwing any kind of error. The reasons why I believe that are:

1) If I delete my `public/js/app.js` file locally and push the change, it doesn't get rebuilt and my production site breaks as there's no app.js file.

2)  If I leave the file in place and push my code to production, it's not minified, and one of the keys I need to reference still contains the dev value.

3) If I replace the aforementioned key with a different value and run `npm run prod` locally, then app.js is minified and contains my updated value.

**Why would the `npm run prod` command not work within a github action, and also indicate that it ran successfully?**

Here's my entire workflow file:

```
name: Prod

on:
  push:
    branches: [ main ]

jobs:
  laravel_tests:
    runs-on: ubuntu-20.04
    env:
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: testdb
      DB_USERNAME: root
      DB_PASSWORD: root
    steps:
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE testdb;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - uses: actions/checkout@main
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Clean Install
        run: npm ci
      - name: Compile assets
        run: npm run prod
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
  forge_deploy:
    runs-on: ubuntu-20.04
    needs: laravel_tests
    steps:
      - name: Make Get Request
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.PROD_DEPLOY_URL }}
          method: GET
```

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/qZa4n.png
