### DISCUSSION TITLE
Dependent jobs from re-usable workflows are not re-run when triggered by a matrix

### DISCUSSION THREAD

**Discussion by gdemonet** [community/community#46853] [Actions]
### Select Topic Area

Bug

### Body

Hello everyone!

We are building really interesting CI pipelines with GitHub Actions, so first of all, thank you a lot for the work, it's been a very pleasing experience for my team.

However, we are playing with matrix strategies and re-usable workflows, and we believe we found an issue with their interactions when re-running failed jobs. It appears that dependencies between jobs defined within the re-used workflow is lost when this workflow is called by a "matrix job".

If this is not supported, it may be useful to explain it in the docs (https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow doesn't mention such a limitation). However, we would find it very useful if this was possible :innocent: 

Thanks in advance!

---

<details>
<summary>Minimal reproducing example</summary>

### Workflows

`.github/workflows/main.yml`:

```yaml
name: "main"

on:
  push:
    branches: [main]

jobs:
  matrix-call:
    strategy:
      fail-fast: false
      matrix:
        child: ["matrix"]
    uses: ./.github/workflows/child.yml
    name: child(${{ matrix.child }})

  plain-call:
    uses: ./.github/workflows/child.yml
    name: child(plain)
```

`.github/workflows/child.yml`:

```yaml
name: "child"

on: workflow_call

jobs:
  first:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "::notice:: Job 'first' - attempt ${{ github.run_attempt }}"
      - run: exit 1

  second:
    runs-on: ubuntu-22.04
    needs: [first]
    if: always()
    steps:
      - run: |
          echo "::notice:: Job 'second' - attempt ${{ github.run_attempt }}"
```

### Workflow runs

- First attempt, as expected, shows:

![image](https://user-images.githubusercontent.com/45066113/217822004-d45281a6-b078-4a81-b336-53b3dcf10f92.png)

- After clicking "Re-run failed jobs", we can see that `child(matrix) / second` is not listed as a dependent:

![image](https://user-images.githubusercontent.com/45066113/217822366-823e4fe7-d0a2-4fb5-a4ad-89fdc5da25de.png)

- And its not executed either (so not just a UI issue), because the corresponding notice is not updated:

![image](https://user-images.githubusercontent.com/45066113/217822561-7f567bb3-2be6-4781-9d7b-0a290733bc2f.png)

</details>
