### DISCUSSION TITLE
[Feature Request] Allow setting absolute paths for actions

### DISCUSSION THREAD

**Discussion by yeikel** [community/community#46877] [Actions]
### Select Topic Area

General

### Body

Rather than

```yml
 name: My step
        # See https://github.com/myOrg/myAction/commit/hash
        uses: myOrg/myAction@hash
```

I would like to be able to set the full path of an action like: 

```yml
 name: My step
        uses: https://github.com/myOrg/action/commit/hash
```

The main goal is to have self-documentation
