### DISCUSSION TITLE
Github Actions: check R package fails with Error Code 143

### DISCUSSION THREAD

**Discussion by matt-sd-watson** [community/community#46908] [Actions]
### Select Topic Area

Question

### Body

I have been running Github Actions, check-r-package for several months now on a private R package. It just started cancelling the workflow during the testthat phase of the workflow with error code 143, and provides no other information on why the tests have failed. All of the tests pass locally with both `devtools::test()` and `devtools::check()`

**Comment by 2MuchC0ff33** [comment]
Thanks for asking your question on GitHub Discussion board @matt-sd-watson 

When running your tests, you could use a more verbose logging output to get more information on what is causing the tests to fail. In your workflow file, try setting the environment variable `R_TESTS_VERBOSE=2`. Please keep me updated on your progress.

**Reply by matt-sd-watson** [reply]
Hello,

Thank you for the suggestion. However there seems to be no additional verbose test output. This is an excerpt from the output of `check-r-package@v2`:

```
* checking tests ...
  Running ‘testthat.R’
Error: Process completed with exit code 143.
```

With no indication of what the possible error could be. 

Here is how the workflow file is set up: 

```
name: test-package
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-test-that:
    runs-on: ubuntu-latest
    env:
        R_TESTS_VERBOSE: 2
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install cURL Headers
        run: |
         sudo apt-get update
         sudo apt-get -y install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libgeos-dev
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
```
I am not able to share any additional log files as the package needs to be kept private for the moment.

**Reply by matt-sd-watson** [reply]
Attaching the extended Github Actions log in case there is anything of note that you can see: 

[run_log.txt](https://github.com/community/community/files/10710060/run_log.txt)

**Reply by 2MuchC0ff33** [reply]
The environment variable `R TESTS VERBOSE` does not produce any additional output. In this case, instead of relying on the `check-r-package` action provided by GitHub Actions, try running the tests directly with `R CMD check`.

Could you please test this sample workflow?

```
name: test-package
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-test-that:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install cURL Headers
        run: |
         sudo apt-get update
         sudo apt-get -y install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libgeos-dev
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - run: R CMD check .
        working-directory: ./pkg

```

This will give you more control over the testing process and the results.
