### DISCUSSION TITLE
How can I capture exit code of run command and reuse in another job ?

### DISCUSSION THREAD

**Discussion by Constantin07** [community/community#46992] [Other Feature Feedback, Questions, & Ideas] [answered]
###

Question

### Body

Hi, I'm trying to use the exit code of a binary in order to decide to run next job or not and it doesn't work as expected.
Here is the code:

```yaml
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.plan.outputs.exitcode }}
    steps:
      - name: Plan
        id: plan
        run: |
          <some command here executed>
          echo "exitcode=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ plan ]
    steps:
      - run: echo ${{ needs.plan.outputs.exitcode }}
```

But the echo in the test job doesn't print any value:
```
Run echo 
  echo 
  shell: /usr/bin/bash -e {0}
```

What am I doing wrong ?

**Comment by airtower-luna** [comment, marked as answer]
By default the shell for `run` steps is configured to exit as soon as a command fails (that's the `-e` in the `shell` definition). So for any exit code != 0 the `echo` to set the output will never run.

You should be able to override that by setting the shell yourself, or (more obvious) disable the "exit on failure":

```yaml
      - name: Plan
        id: plan
        run: |
          set +e
          <some command here executed>
          echo "exitcode=$?" >> $GITHUB_OUTPUT
```

Mind that this way the exit code of the *last* command will become the exit code of the step, so it won't be marked as failed. If you don't want that, you can carry the exit code over:

```yaml
      - name: Plan
        id: plan
        run: |
          set +e
          <some command here executed>
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit "$exitcode"
```
