### DISCUSSION TITLE
No clickable links in annotations created from workflow commands

### DISCUSSION THREAD

**Discussion by austinpray-mixpanel** [community/community#47014] [Actions] [answered]
### Select Topic Area

Product Feedback

### Body

I noticed that urls in annotations created using [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) are not clickable. Neither GitHub URLs or [autolink references](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls) work.

Basic workflow to reproduce this behavior: https://github.com/austinpray-mixpanel/gha-demo-annotation-links/pull/1/files

```yaml
name: Temp Annotations Test

on:
  pull_request: {}

jobs:
  test_annotations:
    runs-on: ubuntu-latest
    steps:
      - name: test configured autolink
        run: |
          echo '::error file=README.md,line=1,title=testing links::go/123'
      - name: test gh link
        run: |
          echo '::error file=README.md,line=1,title=testing links::wiki https://github.com/your/repo/wiki/GHA-0001'
```

`go/123` is an autolink reference in this example
![Screenshot 2023-02-10 at 3 28 38 PM](https://user-images.githubusercontent.com/71290498/218203848-0e747eb2-0c07-4675-b329-fd4862e997d0.png)

Clickable links work fine in the action run summary view

![Screenshot 2023-02-10 at 3 23 18 PM](https://user-images.githubusercontent.com/71290498/218203930-db056e3f-b853-44c7-a759-d6393868d709.png)

But do not work on the “Files changed” tab

![Screenshot 2023-02-10 at 3 25 10 PM](https://user-images.githubusercontent.com/71290498/218203997-27ee9aa6-f6a2-4c2b-bf52-b33b6619ce67.png)

Users having to copy paste URLs into the browser is not ideal. I would at least expect the highlighted URLs to be consistent between the summary page and the files changed tab. If I could wave a magic wand I would love the ability to have markdown style links to save space in the annotation text.
