### DISCUSSION TITLE
automate repository update

### DISCUSSION THREAD

**Discussion by zoranbosnjak** [community/community#47052] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

I have a github repository which needs periodic updates from a trusted upstream source. To manually perform the update, I do something like this on the client:

```
cd myrepo
# use 'curl' to fetch from https://trusted/upstream/source,
# run some other actions (like make)
./local-update
git add deps*
git commit -m "sync with upstream"
git push
```

Is it possible to automate this procedure (or similar) within github itself. For example to run it once a week or so. Automatic pull request would be OK. From there I assume the pull request could be automatically accepted. I have already checked `dependabot`, but I am not sure how to use it with a custom update script, instead of a predefined package manager (pip, npm...).

Is there a method (with dependabot or otherwise) to do something like this?

**Comment by jge162** [comment]
I tried, and Dependabot will not work unfortunately. 

![Screenshot 2023-02-11 at 3 42 24 AM](https://user-images.githubusercontent.com/31228460/218256210-aeab0810-683f-4d02-9f50-379a5df1f53e.jpeg)

**Comment by jge162** [comment]
I tested this code, and it runs, but I do not have ssh setup etc. So try it and see if it runs. it is a GitHub action. 

```yaml
name: Update Repo
on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Repo Directory
      run: mkdir -p myrepo
    - name: Update Repo
      run: |
        cd myrepo
        curl https://trusted/upstream/source
        ./local-update
        git add deps*
        git commit -m "sync with upstream"
        git push
```

**Comment by lbirkert** [comment, marked as answer]
> ### Select Topic Area
> 
> Question
> ### Body
> 
> I have a github repository which needs periodic updates from a trusted upstream source. To manually perform the update, I do something like this on the client:
> 
> ```
> cd myrepo
> # use 'curl' to fetch from https://trusted/upstream/source,
> # run some other actions (like make)
> ./local-update
> git add deps*
> git commit -m "sync with upstream"
> git push
> ```
> 
> Is it possible to automate this procedure (or similar) within github itself. For example to run it once a week or so. Automatic pull request would be OK. From there I assume the pull request could be automatically accepted. I have already checked `dependabot`, but I am not sure how to use it with a custom update script, instead of a predefined package manager (pip, npm...).
> 
> Is there a method (with dependabot or otherwise) to do something like this?

Hey,

yes this should be possible as Github actions allows running an action periodically.

.github/workflows/your_workflow.yml:
```yml
name: Your Workflow

on:
  schedule:
    - cron: '0 0 * * Sun' # Run every week on sunday
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: |
          echo "Execute some shell commands"
```
