### DISCUSSION TITLE
Docker compose or Dockerfile for on the fly service containers

### DISCUSSION THREAD

**Discussion by Smattacus** [community/community#47105] [Actions] [answered]
### Select Topic Area

Product Feedback

### Body

I am interested in setting up a service in a Github action that is not from an already existing container but instead directly from a docker compose file, or even from a docker file that uses some already declared services.

Basically, I'm trying to bring up an app in a container (this app is already tested) and point a client to it for some integration testing. This app is part of the repo. I could workaround this by building the container and pushing it in an earlier job, but that ends up being an additional job with having to push a container that I really only want to use once.

What I am trying to do is something like this:

```
on: [push]

jobs:
  client_hello_world:
    runs-on: ubuntu-latest
    name: Fires up the client to talk to the app.
    container: python:3.7-alpine
    services:
      redis:
        image: "redis:alpine"
      app-from-repo:
        image: Dockerfile
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Sets up the client"
        id: setup
        run: pip install requests
      - name: "Points the client to the service 'app-from-repo' built by the Dockerfile"
        id: entrypoint
        env:
          ENDPOINT: localhost:5000
        run: python3 simple_client.py
```

Using a docker compose file would mean that I don't need the redis image since I'd bring that up as part of the compose build.

Are there other ways to do this currently that I'm just missing? Or is this at all planned as a feature? If not, I'd like to request it! For now I will set up the push methodology, but this is one where maybe it's useful to have this feature.
