### DISCUSSION TITLE
Github Actions - Fetching all variables and all secrets

### DISCUSSION THREAD

**Discussion by JakubK** [community/community#47165] [Actions] [answered]
Hi,

I'm wondering if is there any built in method in Github Actions to iterate over all variables and secrets and do something with it? Not some specific hardcoded keys, but all of them. I have an use case to map all of my expressions in my deployment.yaml to the variables and secrets they correspond to.

**Comment by OwaisAzad** [comment]
Unfortunately, there is no built-in method in GitHub Actions to iterate over all variables and secrets and perform an action on each one. However, you can write a custom script in your GitHub Actions workflow that retrieves the list of all variables and secrets, and then performs an action on each one.

**Reply by JakubK** [reply]
Can you give me a hint on how to get these variables and secrets in custom script? I have noticed that those are not present when using `printenv` command, so they are not residing directly in the machine environment and there must be some other method.

**Comment by ChristopherHX** [comment, marked as answer]
If you can parse json env variables here you go:
```yaml
- run: |
    echo "$ALLMYSECRETS"
    echo "$ALLMYVARS"
  shell: bash
  env:
    ALLMYSECRETS: ${{ toJSON(secrets) }}
    ALLMYVARS: ${{ toJSON(vars) }}
```

**Reply by JakubK** [reply]
Thanks ❤️

**Reply by drewid** [reply]
Anyone know how to loop through the output?

**Reply by justinmchase** [reply]
This does not work for me, it throws an error about the max length of the input being too long. My org has a boat load of secrets.

We need a way to map/reduce the secrets from within github action script.

**Reply by ChristopherHX** [reply]
> throws an error about the max length of the input being too long

Do you have the exact message and/or screenshot as well? Depending on that it might be impossible or there are different ways

The plus for the following is, it doesn't create a long json string with all secret names + values and instead assign individual env variables with it's values

Could avoid errors like maximum object size exceeded, but not shure.
If you error is max environment / args block size, then you would need to write the json to a file via a run step. This varies a lot based on a concret error

```yaml
- run: |
    env
  shell: bash
  env: ${{ secrets }}
```

If you need also non secret env this is now undocumented, and has not been confirm as a feature still works in real GitHub Actions at the moment

```yaml
- run: |
    env
  shell: bash
  env:
    ${{ insert }}: ${{ secrets }}
    anotherenv: myval # having a secret with a similar name will create a exception at runtime!
```

At the moment there is no movement in adding expressions functions since 2019 from GitHub Actions maybe open new feature request in this forum that has no solution marked.

Only selecting the names, not values is impossible as well

**Reply by justinmchase** [reply]
```
env: ${{ secrets }}
```

![whoa](https://github.com/user-attachments/assets/1d7445f5-1816-4e44-8550-e04d143bbee8)

**Reply by justinmchase** [reply]
If only I had seen that last week it may have saved me a lot of time, lol.

What we ended up doing is moving our "dynamic" secrets into hashicorp vault. Basically I do not have the power to force our org admins to scope their secrets more carefully and the process for scoping them to repos is too hard they need a wild card approach sort of like rulesets for org secrets otherwise its basically not worth the effort to opt in hundreds of repos one by one per secret.

**Reply by 3uzbcqje** [reply]
THANK YOU! With our powers combined, we now have this lovely script to securely dump and encrypt secrets: 

https://gitlab.com/devopscoop/scripts/-/blob/main/github_actions/dump-and-encrypt-secrets.yml?ref_type=heads

```
# dump-and-encrypt-secrets.yml
#
# This manually run workflow takes an age public key as input, puts all of a
# GitHub repo's secrets into env vars, dumps all env vars, encrypts them with
# age, and creates an artifact that you can download and decrypt with your age
# private key.
#
# To use this workflow:
#
# 1. Put this file in the `.github/workflows/` folder, commit, and push.
# 2. Install age. See https://github.com/FiloSottile/age
# 3. Run `age-keygen > /tmp/key.txt` to generate a key.
# 4. Click "Actions" in your GitHub repo.
# 5. Find this workflow on the left, select it, and click Run Workflow.
# 6. Enter your age public key.
# 7. Download the file from "Artifact download URL" at the bottom.
# 8. Decrypt it with: `unzip -p ~/Downloads/env.age.zip env.age | age -d -i /tmp/key2.txt`

on:
  workflow_dispatch:
    inputs:
      age_key:
        description: 'Enter a public age key'
        required: true
        type: string
jobs:
  dump-and-encrypt-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Install age
        run: |
          sudo apt-get update
          sudo apt-get install -y age
      - env: ${{ secrets }}
        run: |
          env | age -a -e -r "${{ inputs.age_key }}" > env.age
      - uses: actions/upload-artifact@v4.6.1
        with:
          name: env.age
          path: env.age
          retention-days: 1
```

**Reply by yonran** [reply]
>> throws an error about the max length of the input being too long

> Do you have the exact message and/or screenshot as well? Depending on that it might be impossible or there are different ways

I [tested](https://github.com/yonran/github-workflows-test/actions/runs/14589188054/job/40920336111) this and found that the length limit for an environment variable set by [jobs.<job_id>.steps[*].env](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv), if any, is greater than the length limit imposed by Linux (`MAX_ARG_STRLEN=128 KiB` on ubuntu-latest with standard 4 KiB page size), since this is the error when I tried to set a 128 KiB environment variable value:

```
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/github-workflows-test/github-workflows-test'. Argument list too long
```

**Reply by ChristopherHX** [reply]
> if any, is greater than the length limit imposed by Linux (MAX_ARG_STRLEN=128 KiB on ubuntu-latest with standard 4 KiB page size)

You can usually bypass this kind of error for linux / macOS by letting GitHub Actions write your secrets directly to your disk.

```yaml
- run: ${{ toJSON(secrets) }}
  shell: mv {0} secrets.json
```
_or `cp {0} secrets.json`_

This works by making use of the fact that run steps create files in the runner temp folder with the content of your script.
Using heredoc to embed your json into a bash script is possible as well.

_Do whatever you want with secrets.json, but do not upload this as an action artifact of a public / internal repository_

Maybe you find this useful :).

**Reply by ohararyan** [reply]
> THANK YOU! With our powers combined, we now have this lovely script to securely dump and encrypt secrets:
> 
> https://gitlab.com/devopscoop/scripts/-/blob/main/github_actions/dump-and-encrypt-secrets.yml?ref_type=heads
> 
> ```
> # dump-and-encrypt-secrets.yml
> #
> # This manually run workflow takes an age public key as input, puts all of a
> # GitHub repo's secrets into env vars, dumps all env vars, encrypts them with
> # age, and creates an artifact that you can download and decrypt with your age
> # private key.
> #
> # To use this workflow:
> #
> # 1. Put this file in the `.github/workflows/` folder, commit, and push.
> # 2. Install age. See https://github.com/FiloSottile/age
> # 3. Run `age-keygen > /tmp/key.txt` to generate a key.
> # 4. Click "Actions" in your GitHub repo.
> # 5. Find this workflow on the left, select it, and click Run Workflow.
> # 6. Enter your age public key.
> # 7. Download the file from "Artifact download URL" at the bottom.
> # 8. Decrypt it with: `unzip -p ~/Downloads/env.age.zip env.age | age -d -i /tmp/key2.txt`
> 
> on:
>   workflow_dispatch:
>     inputs:
>       age_key:
>         description: 'Enter a public age key'
>         required: true
>         type: string
> jobs:
>   dump-and-encrypt-secrets:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Install age
>         run: |
>           sudo apt-get update
>           sudo apt-get install -y age
>       - env: ${{ secrets }}
>         run: |
>           env | age -a -e -r "${{ inputs.age_key }}" > env.age
>       - uses: actions/upload-artifact@v4.6.1
>         with:
>           name: env.age
>           path: env.age
>           retention-days: 1
> ```

This is just what I was looking for. Thank you for this.
One thing to note was for me the file didn't unload as a .zip (possibly already unpacked on download).

So I needed to run `age -d -i key.txt env.age > env.secrets.txt`

**Comment by unfor19** [comment]
In a private repository, I tried using `base64` to print all secrets and then locally to do `base64 -d`, but that didn't work; I still got `**` in the output, which corrupted the base64 output.

I changed to HEX by using `xxd`, like this in CI/CD:

```yaml
jobs:
  main:
    name: extract
    runs-on: ubuntu-22.04
    steps:
      - name: Extract secrets to HEX
        env:
          ALLSECRETS: "${{ toJSON(secrets) }}"
        run: |
          echo $ALLSECRETS | jq | xxd -p -c 1000000
        shell: bash
```

Then copy paste output locally:

```bash
echo 'cicd_output' | xxd -p -r
```

**IMPORTANT**: This is good for private repositories and it's important to delete the workflow after that; Otherwise your secrets might get leaked

**NOTE**:
- `-p` means print
- `-c 1000000` sets the number of bytes per line to 1 million, which, for all practical purposes, ensures that the output remains on a single line for typical data sizes.
- `-r` reverse the input (HEX) to print plain text
