### DISCUSSION TITLE
reusable workflow: inputs default + required not working as expected

### DISCUSSION THREAD

**Discussion by laurentsenta** [community/community#47229] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi,

I have a reusable workflow, with an input marked with "required" and a "default" value. When I call it from another repository, I get an error: "input is required but not provided", which seems to be a bug.

I expect the default value would be used and the workflow would succeed.

The reusable workflow uses the following configuration:

```yaml
on:
  workflow_call:
    inputs:
      my-input:
        required: true
        type: string
        default: some-value
```

I invoke it from another repository:

```yaml
name: My Workflow
on:
  pull_request

jobs:
  release-check:
    uses: my-repo/.github/workflows/check.yml@master
```

The exact error is:

```
The workflow is not valid. .github/workflows/check.yml (Line: 11, Col: 11): Input my-input is required, but not provided while calling.
```

removing the required flag or adding an explicit value fixes the error.

Am I missing something?
