### DISCUSSION TITLE
Pass job status down to reusable workflow

### DISCUSSION THREAD

**Discussion by shtlrs** [community/community#47243] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm trying to make a reusable workflow, that would need the conclusion of the caller workflow.

Currently, I have it setup likewise

# Caller workflow

```yaml
jobs:

  first:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: exit -1

  call-workflow:
    needs: first
    uses: ./.github/workflows/status_embed.yml
    with:
      job_status: ${{ need.first.result }}
    secrets:
      webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}
```

# Called workflow
```yml
name: Status Embed

on:
  workflow_call:
    inputs:
      job_status:
        required: true
        type: string
    secrets:
      webhook_token:
        required: true

jobs:

  test_job:
    name:  TEst job
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: echo ${{ inputs.job_status }}
```

When I use `${{ inputs.job_status }}` in the called workflow, it's always a success, even though there's a step that fails.

When I use the github action runs API, the job's conclusion is a failure.

# **Question**
How can I pass the conclusion of one or more jobs in a caller workflow to a called workflow ?

**Comment by ChristopherHX** [comment, marked as answer]
You want the outcome of continue-on-error shown in status checks. For non matrix jobs you can let the actions/runner set it as an output.

```yaml
jobs:

  first:
    outputs:
      outcome: ${{ job.status }}
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: exit -1

  call-workflow:
    needs: first
    uses: ./.github/workflows/status_embed.yml
    with:
      job_status: ${{ needs.first.outputs.outcome }}
    secrets:
      webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}
```

_if you would wrap this caller workflow as a resusable workflow you will start seeing strange bugs: https://github.com/orgs/community/discussions/32023#discussioncomment-4897639_

**Reply by shtlrs** [reply]
Thank you ! That did it !

**Reply by vaisakhkannan** [reply]
@ChristopherHX , How can I get the status for matrix jobs?

**Reply by ChristopherHX** [reply]
@vaisakhkannan  
GitHub refuses to allow to set an independent outputs for each matrix job, the last team working on this has been layed of before finishing this (https://github.com/actions/runner/pull/2477), this is sort of a emulating the outcome (empty outputs don't override the last set, this is probably not mentioned in the docs at all). This only works because one failure or cancelled status is enough to make the status to be a failure
Therefore
```yaml
on: push
jobs:
  first:
    outputs:
      outcome-failure: ${{ job.status == 'failure' && job.status || '' }}
      outcome-cancelled: ${{ job.status == 'cancelled' && job.status || '' }}
    strategy:
      matrix:
        should-fail:
        - true
        - true
        - false
        - true
        - false
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - id: step1
        if: matrix.should-fail
        run: exit -1

  call-workflow:
    needs: first
    uses: ./.github/workflows/status_embed.yml
    with:
      job_status: ${{ needs.first.outputs.outcome-cancelled || needs.first.outputs.outcome-failure || 'success' }}
    secrets:
      webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}
```
