### DISCUSSION TITLE
Prevent action when creating a branch

### DISCUSSION THREAD

**Discussion by keiranmraine** [community/community#47247] [Actions] [answered]
### Select Topic Area

Question

### Body

I don't want CI (github action) to run when a branch is created.

My current config is:

```
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
```

As I'm not asking for any create events related to branch I don't understand why this triggers.

Guidance gratefully received.

**Comment by spenserblack** [comment, marked as answer]
Instead of [`create:`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#create), I think you'd rather use [`push:`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs) for tags.

For example:
```yaml
on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-release-assets:
    # ...
```
This will trigger when you push a tag or when you create a release (which pushes a tag). I've used "on push tags" in a few repos, and I've seen it in several other repos, too.
