### DISCUSSION TITLE
I want to use the if statement as part of the trigger definition

### DISCUSSION THREAD

**Discussion by gianarb** [community/community#47249] [Actions]
### Select Topic Area

GitHub Action

### Body

Hello

I would like to run a workflow only if the event is `issue_commented` AND if it starts with a specific word AND if it is in a PR.
I managed to do it with:

```yaml
name: "TEST"
on:
  issue_comment:
    types: [created]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      if: ${{ startsWith(github.event.comment.body, '/push-container') && github.event.issue.pull_request }}
```

But it is not what I want because I need to set the `if` condition to all the jobs part of this workflow. I tried moving the if statement as part of the `on` definition:

```yaml
on:
  issue_comment:
    types: [created]
    if: ${{ startsWith(github.event.comment.body, '/push-container') && github.event.issue.pull_request }}
```

But I get the following error:

```
 Unrecognized named-value: 'github'. Located at position 12 within expression: startsWith(github.event.comment.body, '/push-container') && github.event.issue.pull_request
```

**Comment by samuel-ma** [comment]
@gianarb you can set the if condition for the entire workflow in the on section by using the matches keyword.

### For example:
```
name: "TEST"
on:
  issue_comment:
    types: [created]
    if: ${{ startsWith(github.event.comment.body, '/push-container') && github.event.issue.pull_request && matches(github.event.comment.body, '/push-container.*') }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
 ```

This sets the condition that the workflow should only run if the comment body starts with /push-container and the comment was made on a pull request. Additionally, the matches keyword is used to make sure that the entire comment body matches the specified pattern.

Hope this helps
