### DISCUSSION TITLE
No available entity for Azure OIDC for GitHub Actions

### DISCUSSION THREAD

**Discussion by nschmeller** [community/community#47298] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi, I've set up an OIDC app in Azure that I'm using to authenticate my GitHub Actions workflows using the `azure/login` Action. This works great for PRs and pushes to `main`, but the OIDC token claim fails for the `workflow_dispatch` trigger. 

Looking at the Azure Portal view to create a new federated credential for my authenticating Azure app, I don't see an "Entity" in the drop-down box that matches the `workflow_dispatch` trigger. I only see "Environment", "Branch", "Pull request", and "Tag". 

![image](https://user-images.githubusercontent.com/26189705/218615990-50afe568-0a00-4e48-9ee0-18d05f882837.png)

This means that I can't run my GitHub Actions workflows that use Azure using workflow dispatch, because I get this error:

 `Error: : AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://token.actions.githubusercontent.com/'. Assertion Subject: 'repo:<organization>/<repository>:ref:refs/heads/<branch-name>'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation`. 

It would be great if there was a new entity in Azure for this! Please let me know if GitHub has no control over this / it's feedback for Azure, but I figured that this was a good place to start. Thanks!

**Comment by viniciushsantana** [comment]
Just set the entity type to `Branch` and it will work just fine with workflow dispatching.

Don't forget to login correctly in your pipeline:

```yaml
name: Example
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
```
