### DISCUSSION TITLE
So i have a question/need help. i am trying to make a issue fourm and i keep getting this error "YAML syntax error: (): did not find expected '-' indicator while parsing a block collection at line 7 column 2"

### DISCUSSION THREAD

**Discussion by Thunderrock424242** [community/community#47444] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

```
---
name: 💥 Bug/Crash report
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
 - type: checkboxes
  attributes:
    label: General Info
    description: You may select more than one.
    options:
    - label: I did not add any mods.
    - label: I can reproduce this issue consistently in single-player
    - label: I can reproduce this issue consistently in multi-player
    - label: I am crashing and can provide my crash report(s)
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

---


```
this is what i got so far.

**Comment by spenserblack** [comment, marked as answer]
Could you fix the formatting of your post? Like this:
````markdown
```yaml
---
name: Bug/Crash report
# ...
```
````

**Reply by Thunderrock424242** [reply]
wdym

**Reply by spenserblack** [reply]
Nevermind, you made it good enough.
Anyway, you have an extra space before the first `-` on line 7.
```diff
 ---
 name: 💥 Bug/Crash report
 description: File a bug/issue
 title: "[BUG] <title>"
 labels: [Bug, Needs Triage]
 body:
- - type: checkboxes
+- type: checkboxes
```

**Reply by Thunderrock424242** [reply]
ok thank you for the help

**Reply by Thunderrock424242** [reply]
i will see if it works

**Reply by Thunderrock424242** [reply]
also if you can help i am having another issue on line 44 "YAML syntax error: (): did not find expected comment or line break while scanning a block scalar at line 44 column 18"

**Reply by Thunderrock424242** [reply]
nvm i solved it

**Comment by jge162** [comment]
I think issue is indentation maybe. Try this I indented type 

```yaml
---
name: 💥 Bug/Crash report
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
  - type: checkboxes
    attributes:
      label: General Info
      description: You may select more than one.
      options:
        - label: I did not add any mods.
        - label: I can reproduce this issue consistently in single-player
        - label: I can reproduce this issue consistently in multi-player
        - label: I am crashing and can provide my crash report(s)
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
        value: |
          - OS:
          - Node:
          - npm:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

```
