### DISCUSSION TITLE
can github actions upgrade my docker containers

### DISCUSSION THREAD

**Discussion by tdubb123** [community/community#47456] [Actions]
### Select Topic Area

Product Feedback

### Body

I am trying to find a use case with github actions. 

I got multiple standalone docker containers running

elastic search
jenkins
graylog
etc..

all of these are standalone containers with their own docker-compose file

how do i use github actions to update these containers to newer versions through an updated manifest file in git?

**Comment by jge162** [comment]
It is possible. Here is some pseudo code you can play with. You off-course need to edit it to work. It’s all pseudo for your use case. 

```yaml
name: Update Docker containers

on:
  push:
    paths:
      - 'docker-compose.yml'

jobs:
  update-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update containers
        run: |
          cd path/to/docker-compose/directory
          docker-compose pull
          docker-compose up -d

      - name: Run tests
        run: |
          # Insert your test commands here
```
