### DISCUSSION TITLE
Why can't I use a valid YAML array in the `join()` function in a workflow?

### DISCUSSION THREAD

**Discussion by m4heshd** [community/community#47519] [Actions]
### Select Topic Area

Question

### Body

According to [this documentation](https://docs.github.com/en/actions/learn-github-actions/expressions#join), I should be able to use an inline array/sequence as the first argument for the `join()` function instead of passing another pre-set variable. If so, how come the following isn't valid syntax?

```yaml
name: my-workflow

env:
  ELECTRON_VERSIONS: ${{ join(['16.0.0', '17.0.0', '18.0.0', '19.0.0', '20.0.0', '21.0.0', '22.0.0', '23.0.0'], ' -t ') }}
```

**Error:**

```sh
Unexpected symbol: '['. Located at position 6 within expression: join(['16.0.0', '17.0.0'...........
```

So to actually make this work, I have to use `fromJSON()`:

```yaml
name: my-workflow

env:
  ELECTRON_VERSIONS: ${{ join(fromJSON('["16.0.0", "17.0.0", "18.0.0", "19.0.0", "20.0.0", "21.0.0", "22.0.0", "23.0.0"]'), ' -t ') }}
```

This works perfectly fine. That's just silly I have to do all that. Why doesn't the above syntax work?

Also, the documentation says the argument can also be a `string`? How does that work? There's no documentation on that. Does the `join()` function split the string using some special character and re-join it? 🤷🏽
