### DISCUSSION TITLE
Simple `Invoke-WebRequest -Uri` times out on Windows runner

### DISCUSSION THREAD

**Discussion by JacobDomagala** [community/community#47545] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello,

I'm using the following GitHub Action:
```yaml
name: Windows

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  SDK_VERSION: 1.3.204.1
  VULKAN_SDK: 'C:\VulkanSDK\$env:SDK_VERSION'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vulkan SDK
      id: cache-vulkan-sdk
      uses: actions/cache@v2
      with:
        path: $env:VULKAN_SDK
        key: vulkan-sdk-${{ runner.os }}-$env:SDK_VERSION

    - name: Download and install Vulkan SDK
      if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
      run: |
        $vulkanInstaller = "VulkanSDK-$env:SDK_VERSION-Installer.exe"
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$env:SDK_VERSION/windows/${vulkanInstaller}" -OutFile $vulkanInstaller
        Start-Process -FilePath $vulkanInstaller -ArgumentList '/S' -Wait
        Remove-Item -Path $vulkanInstaller
   ```
   
`Download and install Vulkan SDK` takes forever (results in timeout). The file itself is 102MB in size. Downloading even bigger packages on ubuntu runner takes no time. 

Any ideas?
