### DISCUSSION TITLE
Caching container image used to run a job

### DISCUSSION THREAD

**Discussion by Olfredos6** [community/community#47550] [Actions]
### Select Topic Area

Question

### Body

Hey guys,

Is it possible to cache an image used to run a job? For instance, we may have the following job:
```
build:
    name: build
    runs-on: ubuntu-latest
    container:
          image: <sample docker image>
    steps:
        ...
```
Is it possible to cache `<sample docker image>` for subsequent runs?
