### DISCUSSION TITLE
Is it possible to get the `Complete job name` in jobs steps?

### DISCUSSION THREAD

**Discussion by samwyndham** [community/community#47644] [Actions]
### Select Topic Area

Question

### Body

Hello,

The `Complete job name` is logged in `Set up job` step. For example for me the following is logged:

> Complete job name: Run iOS UI tests / Run tests

My workflow looks something like this:

```yaml
# ...
jobs:
  ios_run_ui_tests:
    name: Run iOS UI tests
    uses: ./.github/workflows/run_tests.yml # Uses child reusable workflow
# ...
```

Is it possible to get / deduce this value `Run iOS UI tests / Run tests` within the job steps of `.github/workflows/run_tests.yml`?

**Comment by tinu-doit-intl** [comment]
Did you get any workaround for this?

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by SimonHeimberg** [comment]
When using [reusable workflows](https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows), then it looks like the complete job name is: "parent_job_id_or_name / called_job_id_or_name"
... when running a workflow like:
```yaml
# main_workflow.yaml
...
jobs:
  parent_job_id:
    use: .github/workflows/child_workflow.yaml
```

```yaml
# .github/workflows/child_workflow.yaml
on:
  workflow_call:
jobs:
  called_job_id:  # job id will be used
    steps:
      - run: echo child job
  job2:
    name: called_job_name  # job name will be used
    steps:
      - run: echo child job w name
```
