### DISCUSSION TITLE
Workflows Action in projects can set assignees

### DISCUSSION THREAD

**Discussion by kobakou** [community/community#47728] [Projects and Issues]
### Select Topic Area

Product Feedback

### Body

I would like to change assignees in Workflows Action in projects.
![CleanShot 2023-02-17 at 20 46 36](https://user-images.githubusercontent.com/1381070/219646022-0e21400c-c39f-475b-954f-97d9944c470c.png)

**Comment by jge162** [comment]
I am sure something can be done in Action. But, what are the conditions? `if == 'user', `if != 'user', if label? Run this action and assign this person? Not enough details. But, I believe it can be achieved with conditional statements for you use case.

**Reply by jge162** [reply]
Here is an example but would need more detail to customize action based on correct use case. I said if the person pulling the PR is jack, assign it to John. Or if you have a label assign to john do that too. 
```yaml
on:
  pull_request_target:
    types: [opened, reopened]
    # Trigger the workflow only if the pull request has the 'assign john' label
    # or if the user who opened the pull request is 'jack'
    if: ${{ contains(github.event.pull_request.labels.*.name, 'assign john') || github.event.pull_request.user.login == 'jack' }}
  issues:
    types: [opened, reopened]
    # Trigger the workflow only if the issue has the 'assign john' label
    # or if the user who opened the issue is 'jack'
    if: ${{ contains(github.event.issue.labels.*.name, 'assign john') || github.event.issue.user.login == 'jack' }}

permissions:
  pull-requests: write
  issues: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
        with:
          # Assign the pull request to the user with the login 'john'
          author: 'john'

```
