### DISCUSSION TITLE
Trigger action via check_run in a PR failure

### DISCUSSION THREAD

**Discussion by maxmarkus** [community/community#47768] [Actions]
### Select Topic Area

Question

### Body

Hello! 

According to the docs `check_run` will only run on default branch. 
I want to trigger an Action in a Pull Request based on `continious-integration/jenkins/pr-merge` status. Those checks are added by Jenkins github plugin. 

The first checks with greens are our actions, the `continious-integration/jenkins/pr-merge` are checks coming from jenkins plugin.
<img width="600" alt="gh-checks" src="https://user-images.githubusercontent.com/1720843/219631170-d72f3a91-4ae8-469d-83da-362a202556d7.png">

I thought this action should do the job, but it does not get triggered at all in the PR, how can I achieve this?

```yaml
name: PR on Jenkins failure

on: 
  check_run:
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check-failure:
    name: PR Merge Check
    runs-on: crp2
    steps:
      - name: Print GitHub event action
        run: |
          echo "Event: ${{ github.event.action }}"

      - name: Check if the check run has failed
        if: ${{ steps.check-status.outputs.check_run_conclusion == 'failure' }}
        env:
          CHECK_RUN_ID: ${{ steps.check-status.outputs.check_run_id }}
        run: echo "The check run has failed"

      - name: Get check run status
        id: check-status
        uses: octokit/get-check-run-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-run-id: ${{ env.CHECK_RUN_ID }}

      - name: Do something when the check run fails
        # ci/test ci/lint are childs or so from pr-merge but not required
        if: |
          ${{ steps.check-status.outputs.check_run_conclusion == 'failure' &&
             steps.check-status.outputs.check_run_name == 'continuous-integration/jenkins/pr-merge' }} 
        run: |
          echo "Action triggered on check run failure for continuous-integration/jenkins/pr-merge"
```

I wonder what knowledge I am missing here.

One discussion that seems to be quite similar is this one, https://github.com/community/community/discussions/26236#discussioncomment-3250893 where it states it is intended behavior that it does not get triggered. 

Best, Markus
