### DISCUSSION TITLE
actions doesn't trigger on release edited if I just update the binary assets

### DISCUSSION THREAD

**Discussion by abose** [community/community#47794] [Actions]
### Select Topic Area

Bug

### Body

Hi All,

 I followed [this link](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) to trigger an action whenever a release is updated. 

But the event is not getting triggered if I add some new binary assets and make no other changes.  The event only gets triggered if I edit the heading and body. Does release edited event not trigger on attaching assets to an existing release?

code below
```yml
name: print release ref on asset upload
on:
  release:
    types:
      - edited
      - published
      - released

jobs:
  build-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: release details
        run: |
          echo "$GITHUB_REF"
```

Thanks!
