### DISCUSSION TITLE
Intermittent GitHub Actions Cache Misses

### DISCUSSION THREAD

**Discussion by sayhiben** [community/community#47816] [Actions]
### Select Topic Area

Bug

### Body

We recently (past 1-2 days) started experiencing intermittent cache misses where some jobs are unable to find files saved to the cache from previous jobs. 

I've verified that the cache exists in the repo's cache UI, that it was created and saved prior to the intermittently failing jobs, and that other jobs in the same workflow running before and after the files were cached successfully download the cached files. This feels like a race condition related to cache propagation, but I am uncertain.

- The cached file(s) are accessible by other jobs in the workflow, seemingly irrespective of when they run (before/after/concurrently)
- The cached files are present in the Cache explorer UI
- Re-running the job usually results in no cache misses
- None of the related workflows, jobs, or steps have been altered recently

### Create cache job (occurs before following jobs, which `need` this job)
```yaml
- name: Checkout
  uses: actions/checkout@v3

- run: mkdir -p ~/configuration/

- name: Cache Configuration Output
  uses: actions/cache@v3
  with:
    path: ~/configuration/
    key: configuration-${{ github.run_id }}

- id: configuration
  run: ./.github/workflows/scripts/create-configuration.sh
```

### Failing job
```yaml
- name: Load Configuration File
  uses: actions/cache@v3
  with:
    path: ~/configuration/
    key: configuration-${{ github.run_id }}

- name: Configure
  id: configure
  run: |
    source ~/configuration/config-file
```

### Successful job (could be before, after, or concurrent with failing job)
```yaml
- name: Load Configuration File
  uses: actions/cache@v3
  with:
    path: ~/configuration/
    key: configuration-${{ github.run_id }}

- name: Add configuration env vars to runner
  run: cat ~/configuration/config-file >> $GITHUB_ENV
```

### Configuration job (all other jobs `need` this)
```
Run actions/cache@v3
  with:
    path: ~/configuration/
    key: configuration-RUNID
    enableCrossOsArchive: false
    fail-on-cache-miss: false
Cache not found for input keys: configuration-RUNID

...

Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/REPO/DIR --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~0 MB (658 B)
Cache saved successfully
Cache saved with key: configuration-RUNID
```

### Failing job trying to pull from cache
```
Run actions/cache@v3
  with:
    path: ~/configuration/
    key: configuration-RUNID
    enableCrossOsArchive: false
    fail-on-cache-miss: false
Cache not found for input keys: configuration-RUNID

...

Run source ~/configuration/config-file
  source ~/configuration/config-file
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/12345.sh: line 1: /home/runner/configuration/config-file: No such file or directory
Error: Process completed with exit code 1.
```

### Example job that runs before or after the failing job
```
Run actions/cache@v3
  with:
    path: ~/configuration/
    key: configuration-RUNID
    enableCrossOsArchive: false
    fail-on-cache-miss: false
Received 658 of 658 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (658 B)
/usr/bin/tar -xf /home/runner/work/_temp/12345/cache.tzst -P -C /home/runner/work/REPO/DIR --use-compress-program unzstd
Cache restored successfully
Cache restored from key: configuration-RUNID

...

Run cat ~/configuration/config-file >> $GITHUB_ENV
  cat ~/configuration/config-file >> $GITHUB_ENV
  shell: /usr/bin/bash -e {0}
```

**Comment by ashnair1** [comment]
Were you able to find a solution for this issue?

**Comment by mcg** [comment]
Seeing what I think is this issue as well.

**Comment by MatthewRyanRead** [comment]
Related: https://github.com/actions/cache/issues/1194

I have also seen this with artifacts (`actions/upload-artifact` & `actions/download-artifact`), but it seems much less severe (I've seen caches be completely inaccessible sometimes, although that was using multiple self-hosted runner types in a matrix).  So in cases where the cache isn't sensitive and can be exposed on the run as artifacts, they're a viable alternative if you use retries.  For example:

```yml
- name: Restore artifact
  uses: Wandalen/wretry.action@v3
  with:
    attempt_limit: 3
    attempt_delay: 5000
    action: actions/download-artifact@v4
    with: |
      artifact-ids: my-artifact-id
      path: my-path
```

https://github.com/Wandalen/wretry.action
