### DISCUSSION TITLE
Unable to connect to external network services from docker running inside github actions workflow

### DISCUSSION THREAD

**Discussion by squidpie** [community/community#47960] [Actions]
### Select Topic Area

Question

### Body

I am building a docker compose based micro-service and am trying to execute integration tests from within github actions. Tests all pass locally and the app is currently deployed and working. However when I run the app in GHA it appears that the chat service is unable to reach the twitch irc servers. The strangest part is the chat service is capable of logging in but apparently not sending messages. I can only assume I am missing some critical network configuration in my compose file. 
I am running the following compose file in GHA, any ideas folks?
```
# docker-compose.gha.yml
# Copyright (C) 2023
# Squidpie

version: "3.5"
services:
    redis-test:
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/tests/redis/Dockerfile
        networks:
            - strauss
        depends_on:
            - redis

    chat-test:
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/tests/chat/Dockerfile
        networks:
            - strauss
        depends_on:
            - chat

    redis:
        image: redis:7.0.6-alpine
        container_name: redis
        networks:
            - strauss

    chat:
        image: strauss/chat:${STRAUSS_CHAT_PKG_VERSION}
        container_name: chat
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/services/chat/Dockerfile
            args:
                version: "prod"
                STRAUSS_BUILD_DIR: ${STRAUSS_BUILD_DIR}        
        environment:
            TWITCH_USER: ${TWITCH_USER}
            TWITCH_TOKEN: ${TWITCH_TOKEN}
        networks:
            - strauss
        volumes:
            - ./strauss.yml:/strauss/strauss.yml
        depends_on:
            - redis

networks:
    strauss:
        name: strauss
        driver: bridge
```

With the following workflow:
```
# strauss-validate.yml
# Copyright (C) 2023
# Squidpie

name: strauss-validate
run-name: ${{ github.actor }} is validating strauss
on:
  push:
    branches:
      [dev, stage/*]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      [dev]
  workflow_dispatch: {}

jobs:
  validate:
    name: Validate strauss
    runs-on: ubuntu-latest

    env:
      STRAUSS_ROOT_DIR: ${{ github.workspace }}
      STRAUSS_BUILD_DIR: target/debug
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Resolve Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Strauss Env
        run: |
            ./scripts/gen-gha-env.sh
            cat .env > .env.runtime
            echo ${{ secrets.STRAUSS_SECRETS }} >> .env.runtime
            printf '%b\n' "services:\n    chat:\n        channel: <testing channel>\n" > strauss.yml

      - uses: actions/cache@v3
        id: cache-rust
        with:
            path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
                target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build & Unit Test Services
        if: steps.cache-rust.outputs.cache-hit != 'true'
        run: docker compose --env-file .env -f strauss-build.debug.yml run build
      
      - name: Run Integration Tests
        run: |
            docker compose --env-file .env.runtime \
                -f docker-compose.gha.yml \
                up -d

      - name: Get Test Status
        run: |
            sleep 45
            docker logs `docker container ls -a | grep chat-test | awk '{print $1}'` | grep "PASSED" && \
            docker logs `docker container ls -a | grep redis-test | awk '{print $1}'` | grep "PASSED"

      - name: Inspect Dockers
        if: failure()
        run: |
            docker inspect `docker container ls -a | grep "strauss/chat" | awk '{print $1}'`
            docker inspect `docker container ls -a | grep "redis:7" | awk '{print $1}'`
            docker inspect `docker container ls -a | grep "chat-test" | awk '{print $1}'`
            docker inspect `docker container ls -a | grep "redis-test" | awk '{print $1}'`
      
      - name: Collect Docker Logs
        if: failure()
        uses: jwalton/gh-docker-logs@v2.2.1

```
