### DISCUSSION TITLE
How to trigger an action only on release or only on pre-release?

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#48044] [Actions]
### Select Topic Area

Question

### Body

I would like to setup some GitHub Actions to execute stuff based on whether the release is a normal publication, or an actual pre-release.

My last attempt doing such a thing was not really successful, as a pre-release also triggered the workflow that should only execute on a publish.
What would be the proper workflow syntax to keep those two workflows separate from each other?

Or, if that is possible, can I set a specific value in a workflow step depending on the release type? Like that I could set "Beta" when it is a pre-release and otherwise just "Release"?

```yaml
    - name: Upload AdvancedServerList (${{ matrix.loaders }}) to GitHub and Modrinth
      uses: Kir-Antipov/mc-publish@v3.2
      with:
        # ...
        version-type: release # <-- Can I modify this depending on the release type?
        # ...
```
