### DISCUSSION TITLE
Test Workflow: How to copy non-package test files required only for testing of python project

### DISCUSSION THREAD

**Discussion by LemonPi** [community/community#48095] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a pytest workflow for a python project that is failing due to missing test-required files. From popular python projects, it seems that test files should be excluded from installations. Thus in my python project's `pyproject.toml`, I do not include the `tests` package or specify its contents as `package-data` for `setuptools`. How should I copy these test required files over for my testing workflow on github?

My directory structure looks like:
```
.
├── LICENSE.txt
├── pyproject.toml
├── README.md
├── src
│   ├── my_pkg_name
│   │   ├── __init__.py
└── tests
    ├── ant.xml
    ├── humanoid.xml
    ├── __init__.py
    ├── kuka_iiwa.urdf
    ├── meshes
    │   ├── link_0.obj
    │   ├── link_1.obj
    │   ├── link_2.obj
    │   ├── link_3.obj
    │   ├── link_4.obj
    │   ├── link_5.obj
    │   ├── link_6.obj
    │   └── link_7.obj
    └── test_transform.py
```
I would like to copy `["tests/*.sdf", "tests/*.urdf", "tests/*.xml", "tests/meshes/*.obj"]` over to the testing directory.

My current workflow looks like:
```
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
```
