### DISCUSSION TITLE
Using deployment environment secrets and vars in a shared job

### DISCUSSION THREAD

**Discussion by melbic** [community/community#48179] [Actions]
### Select Topic Area

Question

### Body

We created a stage and production environment in https://github.com/$ORG/$REPO/settings/environments.  And we added a environment variable: `BACKEND_API_URL` and a secret: `BACKEND_API_KEY` to both environments. 
The build job is shared between both environments, but we need those values in it.

Our deployment workflow looks something like this:
```
name:  Build and deploy
on:
- push

env:
  PROJECT_NAME: "My Project"

jobs:
  build:
    runs-on: ubuntu-latest
   steps:
      - name: Docker Build
        uses: dreipol/github-actions/build@os4-migration
        env:
            BACKEND_API_URL: ${{ env.BACKEND_API_URL }}
            BACKEND_API_KEY: ${{ secrets.BACKEND_API_KEY }}
            GCP_SERVICEACCOUNT_KEY: ${{ secrets.GCP_SERVICEACCOUNT_KEY }}
  deploy-stage:
    runs-on: ubuntu-latest
    environment: stage
    needs: build
    if: github.ref == 'refs/heads/stage'
    steps:
    ...
 ```
While the `GCP_SERVICEACCOUNT_KEY` is a organisation secret and works well, the environment dependent values are empty.
 
 How can we access/pass the two values to the build job?
