### DISCUSSION TITLE
Can a job id share the name with the job itself?

### DISCUSSION THREAD

**Discussion by PaulRBerg** [community/community#48286] [Actions] [answered]
### Select Topic Area

Question

### Body

Suppose you have a workflow defined like this:

```yml
jobs:
  foo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "@actions/checkout@v3"
      - name: "Do Something"
        id: "foo"
```

Would this work, i.e. could another step in the job use the `foo` as an id?
