### DISCUSSION TITLE
continuous workflow for feature branch and creating an action

### DISCUSSION THREAD

**Discussion by kvernon** [community/community#48302] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm trying to do an "eat your own dog food" scenario. My goal is to have a feature branch to test out the sharable actions. 

I'm having difficulty where it seems GH Actions (will be private / enterprise) point to where the actions are stored, and it makes sense, however, it doesn't seem it can ever find the action. 

My basic flow that I'm aiming for is:

1. create feature branch
2. do work to update action(s)
3. create PR
4. have repo eat its own actions (aka dog food), by directly testing the updates
5. when work is deamed good, merge to main, tag, release, changelog

the structure is as follows:

```text
/.gitflow/workflows
-- feature-build.yml
/.gitflow/actions/ensure/
-- action.yml
/.gitflow/actions/version/
-- action.yml
```
In the feature-build.yml I tried calling it like so:

```yml
#...
jobs:
  ensure_branch_prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure Branch Prefix
        uses: ./.github/actions/ensure@feature/ensure
```

in the ensure action.yml I have:

```yml
#...
runs:
  using: "composite"
  steps:
    - run: |
        echo "### Ensure Prefix Branch" >> $GITHUB_STEP_SUMMARY
```

I tend to get this error:
```
[ensure_branch_prefix](https://github.com/our-corp/actions-collections/actions/runs/4244548907/jobs/7378820729#step:3:1)
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/actions-collections/workflows/.github/actions/ensure-prefix-branch/action.yml@feature/ensure'. Did you forget to run actions/checkout before running your local action?
```

**Comment by kvernon** [comment]
I'll add that this is difficult because I cannot seem to find examples of repos with multiple actions that are shared, but I do find docs that say it's possible.

**Comment by airtower-luna** [comment, marked as answer]
`uses: ./something` means you're [calling a *local* action](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow), that means one that's in the checked out code, by path. You can't combine that with a Git ref or commit ID (because it uses the action from the file system, not Git).

If you want to call an action at a specific branch name, you need to [reference the repository](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-public-action) (and ref), not the path.

I think that for testing the action running the code *as present in the checked-out repository* is usually preferable (so, the local action version).

**Reply by kvernon** [reply]
Thank you for responding @airtower-luna !

> If you want to call an action at a specific branch name, you need to [reference the repository](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-public-action) (and ref), not the path.

So, I guess I need (from your repo ref):

```yml
jobs:
  my_first_job:
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: octocat/my-private-repo
          ref: v1.0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/my-private-repo
      - name: Run my action
        uses: ./.github/actions/my-private-repo/my-action
```

Looks like a checkout within a checkout (wow, that's odd)...

Does that sound like what you're trying to tell me?
