### DISCUSSION TITLE
Combining Composite Action and Runs using Node XX

### DISCUSSION THREAD

**Discussion by kvernon** [community/community#48399] [Actions]
### Select Topic Area

Question

### Body

I'm looking for advice on how to combine strategies... for the above title.

In phases individually, I can create a composite, and I can do a runs with node16. I cannot seem to understand how to combine them.

Docs:
+ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs
+ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions
+ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
+ https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#writing-the-action-code

The compiled javascript pulls in args per doing the `writing-the-action-code` above in docs above.

The conflict in ideas comes down to...

composite

```yml
# ...

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "### ${{ inputs.flowVersioningTitle }}" >> $GITHUB_STEP_SUMMARY
   
```

javascript example

```yml
# ...

runs:
  using: 'node16'
  main: 'compiled/index.js'
```

Is the runs using node xx a short cut for setting up node version and running node? or is there a specific concern around this?

Thanks again!
Kelly

**Comment by jsoref** [comment]
Your composite can manually run `node` code itself using `node ...`.

If you actually need to use the extra magical context exposed by `using: node16`, you can create a `./node-thing/action.yml` file and use `uses: ./node-thing` or something like that...

**Reply by kvernon** [reply]
@jsoref , 

Thank you for following up, I've been out the last few days. 

What I found was that when calling it via something like below,  `@actions/core` in code, will not see the variable values supplied...

```yaml
inputs:
  isFeatureBranch:
    description: 'used to determine if this is a feature branch (true) or a non-feature-branch (false).'
    required: true
    type: Boolean

# ...
runs:
  using: "composite"
  steps:
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: Install npm 7
        run: npm i -g npm@7

      - name: Install Dependencies
        run: npm ci

      - name: Performing Shared Action
        run: npm run orchestrate
```

It'll miss all the inputs I passed into it. Can you supply an example of what you were talking about?
