### DISCUSSION TITLE
Deploy on Server directory not found issue

### DISCUSSION THREAD

**Discussion by Hossam-Tarek** [community/community#48434] [Actions]
### Select Topic Area

Product Feedback

### Body

I'm using Github action to deploy to a shared hosting steps:
1. create ftp account on the shared hosting.
2. add action secrets to the repo
3. setup the Github Actions as follows

``` yml
on:
  push:
    branches:
      - main

name: Deploy on Demo Server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-don't-get-an-error"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEMO_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Pull latest commits
        run: |
          cd /home/harajw/public_html/winner-ad/
          git pull origin main

```

But I found the error
![Screenshot from 2023-02-23 23-49-36](https://user-images.githubusercontent.com/23726675/221040142-7c57c168-e38f-4b5c-846d-d89860b41644.png)

while the path does exists on the server
 
![Screenshot from 2023-02-23 23-50-37](https://user-images.githubusercontent.com/23726675/221040227-2ff4315e-b9b6-4060-888a-4420f7025e54.png)

**Comment by jsoref** [comment]
```
/home/harajw
```

is your local user's home directory. It isn't the home directory for a runner.

**Reply by Hossam-Tarek** [reply]
It's not my local but the shared host. yes the come directory is `/home/harajw`

**Reply by Hossam-Tarek** [reply]
` It isn't the home directory for a runner.` How can i solve that issue

**Reply by jsoref** [reply]
There are two computers in this workflow:

1. The GitHub runner
2. The one that I expect would be at `secrets.DEMO_SERVER_IP`

They have entirely unrelated file system layouts.

The code of your workflow doesn't make any sense from the perspective of where it's running (which is a GitHub runner).

1. 🚚 Get latest code
```yaml
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
```

This checks out the current version of the code for whatever your running repository's repository is into the current directory. (v4 was released some time after you posted this question).

2. Install SSH Key
```yaml
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-don't-get-an-error"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEMO_SERVER_IP }} >> ~/.ssh/known_hosts
```

This does something which frankly makes no sense to me.

I would replace all of that with:
```yaml
      - name: Get current code
        uses: actions/checkout@v4
        with:
          repository: 'harajw@${{secrets.DEMO_SERVER_IP }}:public_html/winner-ad'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: 'false'
```

4. Here you're imagining that your workflow is running on that remote computer, but it doesn't. Again, it runs on the GitHub runner...
```yaml
      - name: Pull latest commits
        run: |
          cd /home/harajw/public_html/winner-ad/
          git pull origin main
```

I'd replace that with:

```yaml
      - name: Pull latest commits
        run: |
          git remote add github "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          git pull github main
```

Note that at this point, depending on how messy your world is, you may have merge conflicts or other things...

But, ignoring that, all your code did was try to set up a version of the repository in the GitHub runner and imagined it might be similar/related to the version of the repository in your remote server. At no point did it try to push the changes from the GitHub runner to the remote server.

For that, you'd need something like:

```yaml
      - name: Publish latest commits
        run: |
          git push origin HEAD
```

Note: if you don't understand these things, you're going to want to read some articles before you start working with them. I'm making a lot of assumptions about how your remote server is configured (I have no idea where the root of your repository is in the remote server -- I'm assuming it's `/home/harajw/public_html/winner-ad` but it could be `/home/harajw/public_html` or `/home/harajw` -- although it shouldn't be...).

I should especially warn that the `git pull` you're doing is liable to result in various problems if you aren't careful. I personally never use `git pull` because I find it does things that surprise people.
