### DISCUSSION TITLE
Output from Docker container to `$GITHUB_OUTPUT`

### DISCUSSION THREAD

**Discussion by WaterLemons2k** [community/community#48460] [Actions] [answered]
### Select Topic Area

Question

### Body

I used `set-output` and [addnab/docker-run-action](https://github.com/addnab/docker-run-action) action to set the output from Docker container, like this:
```YAML
- uses: addnab/docker-run-action@v3
  id: docker
  with:
    image: alpine
    run: echo "::set-output name=alpine::$(cat /etc/alpine-release)"
- run: echo ${{ steps.docker.outputs.alpine }}
```

It worked fine. But [`set-output` command is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), so I've updated it to `GITHUB_OUTPUT`, like this:
```YAML
- uses: addnab/docker-run-action@v3
  id: docker
  with:
    image: alpine
    run: echo "alpine=$(cat /etc/alpine-release)" >> $GITHUB_OUTPUT
- run: echo ${{ steps.docker.outputs.alpine }}
```

But it failed with an error message:
```sh
sh: can't create : nonexistent directory
```

Some similar discussions:
- [#36677 (comment)](https://github.com/orgs/community/discussions/36677#discussioncomment-4042212)
- #38570
- addnab/docker-run-action#41

**Comment by airtower-luna** [comment, marked as answer]
Based on the error message the immediate issue is that the file and directory `$GITHUB_OUTPUT` points at doesn't exist in the container. That's something that'd have to be solved in the custom action you're using. It looks like someone already raised that issue, but so far without response: https://github.com/addnab/docker-run-action/issues/41

Unless that action gets updated your best option is to stop using it, and either make something yourself or find another action that does what you need. For example, the version check in your example could be done like this:

```yaml
- id: docker
  run: docker run --rm alpine sh -c 'echo "alpine=$(cat /etc/alpine-release)"' >> $GITHUB_OUTPUT
- run: echo ${{ steps.docker.outputs.alpine }}
```

Mind that this redirects the output *of the Docker command* (outside the container), if you have a command where you want to turn only part of its stdout into a step output you might need a little more complex scripting.
