### DISCUSSION TITLE
Add "substring" in-built function to Github Action Expressions

### DISCUSSION THREAD

**Discussion by nandakumar649** [community/community#48485] [Actions] [answered]
### Select Topic Area

Product Feature Request

### Body

We are managing multiple environments in AWS to deploy our application and perform both functional and performance testing.We are planning to enable the permissions to the developers to control the development and functional environments via GitHub actions.
Currently, we have to add a new environment to "Github actions Environment" to establish the permissions. This is becoming an additional work for the DevOps engineers to configure the secrets and variables for the new environment.

For instance, a developer from our team is using the environment "dev1" and another developer wants to work on a feature and would like to create "dev2", we have to manually create the secrets and variables for it and then ask him to proceed with his development. 
We would like to create a generic environment called "dev" which will have all the required variables, secrets and environment protection rules so that all developers from our team can handle the environment without any assistance from us.

We find that "substring" in-built Github function will cater for this requirement shown below.

```
jobs:
  infra-deployment:
    name: infra-deployment
    runs-on: ubuntu-latest
    environment: ${{ substring(github.event.inputs.environment,3) }}
```

We would like to understand if this is feasible from GitHub Actions team and is there any new release planned for the same in near future. We believe this feature will be useful in most cases and help the DevOps community.

**Comment by jsoref** [comment]
This is a duplicate of #26625

**Comment by jsoref** [comment, marked as answer]
For this specific use case, you could actually use [`contains(...,...)`](https://docs.github.com/en/actions/learn-github-actions/expressions#contains), it might take a bit of effort, but, assuming that you have a limited number of possible environments, you could do something like:

```yaml
jobs:
  infra-deployment:
    name: infra-deployment
    runs-on: ubuntu-latest
    environment: ${{ (contains(github.event.inputs.environment,'dev') && 'dev') || (contains(github.event.inputs.environment, 'test') && 'test') }}
```
