### DISCUSSION TITLE
Run additional scripts in a Dependabot PR

### DISCUSSION THREAD

**Discussion by dprotaso** [community/community#48498] [Code Security] [answered]
### Select Topic Area

Question

### Body

Our repositories have some code generation scripts that need to run when updating dependencies. I was looking to setup dependabot to bump these dependencies but couldn't see a way to indicate that a script needs to run prior to creating a pull request.

ie. https://github.com/knative/pkg/pull/2691

**Comment by pgodschalk** [comment, marked as answer]
You can set up a [GitHub action](https://docs.github.com/en/actions) when the PR is made.

For example,

```yml
on:
  pull_request:

jobs:
  generate_some_code:
    name: Generate some code!
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }} # If you only want to trigger this on a dependabot PR
    steps:
       - name: Do the code!
         run: ./generate-code.sh

```
