### DISCUSSION TITLE
GitHub Action incorrectly inferred type of empty strings

### DISCUSSION THREAD

**Discussion by mon-jai** [community/community#48500] [Actions]
### Select Topic Area

Bug

### Body

**Describe the bug**

GitHub Action does not recognize empty strings as a string

**To Reproduce**

1. Run [this workflow file](https://github.com/mon-jai/github-action-error/blob/main/.github/workflows/error.yml)

	```yaml
	name: Error
	on: [push, workflow_dispatch]
	
	jobs:
	  error:
	    runs-on: windows-latest
	    concurrency:
	      group: ${{ matrix.arguments }}
	      cancel-in-progress: true
	    strategy:
	      matrix:
	        arguments: ["", "foo", "bar"]
	    steps:
	      - run: |
	          echo "Hello world"
	```

**Expected behavior**

GitHub Action should inferred empty strings as type `string`

## Runner Version and Platform

Version of your runner?  
2.302.1

OS of the machine running the runner?  
Hosted by GitHub

## What's not working?

The [following error is displayed](https://github.com/mon-jai/github-action-error/actions/runs/4264201104)

```
Error when evaluating 'concurrency' for job 'error'. .github/workflows/error.yml (Line: 8, Col: 14): Unexpected type of value '', expected type: String.
```

**Comment by VadymIakobchuk** [comment]
I have the same problem with concurrency when using cron and workflow dispatch
```
on:
  schedule:
    - cron: '30 7 * * 1-5'
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
        default: 'test
        type: choice
        options:
          - test-all
          - test-ws
          - test-ms
      env:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test

concurrency:
  group: ${{ github.event.inputs.env && github.event.inputs.tag }}
  cancel-in-progress: true
```

All cron builds fail with error :
`The workflow is not valid. .github/workflows/mde.yml (Line: 27, Col: 10): Unexpected type of value '', expected type: String.`
