### DISCUSSION TITLE
Unable to set env var with variable

### DISCUSSION THREAD

**Discussion by adamjstewart** [community/community#48648] [Actions] [answered]
### Select Topic Area

Bug

### Body

The following seem to work fine:
```yaml
env:
  TMPDIR: /tmp
```
```yaml
jobs:
  foo:
    env:
      TMPDIR: /tmp
```
However, the following don't seem to work:
```yaml
env:
  TMPDIR: ${{ runner.temp }}
```
```yaml
jobs:
  foo:
    env:
      TMPDIR: ${{ runner.temp }}
```
Am I doing something wrong or is this a bug (or a security "feature")?
