### DISCUSSION TITLE
Running service containers with different port

### DISCUSSION THREAD

**Discussion by sunzoje** [community/community#48673] [Actions] [answered]
### Select Topic Area

Question

### Body

I have CentOS 7 system with postgresql and redis running on port 5432 and 6379 respectively.
I run GitHub actions on self-hosted runner with following workdlow:
```yaml
name: Run rspec test
on: push
jobs:
  rspec:
    runs-on: self-hosted
    container:
      image: ruby:3.1.1
      env:
        RAILS_ENV: test

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6380:6379

      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - uses: actions/checkout@v3

      - name: Install gems
        run: |
          bundle install --jobs 4 --retry 3
        env:
          RAILS_ENV: test

      - name: Setup database
        run: |
          bundle exec rails db:setup
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
          DATABASE_URL: postgres://postgres:postgres@postgres:5433/test_db

      - name: Run tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
          REDIS_HOST: redis
          REDIS_PORT: 6380
          DATABASE_URL: postgres://postgres:postgres@postgres:5433/test_db
```
On running workflow, I got following error:
```
could not connect to server: Connection refused
	Is the server running on host "192.168.128.4" and accepting
	TCP/IP connections on port 5433?
Couldn't create 'test_db' database. Please check your configuration.
rails aborted!
```
What would be the right way to use different ports for services?
