### DISCUSSION TITLE
If statement is evaluated after matrix

### DISCUSSION THREAD

**Discussion by AllanOricil** [community/community#48705] [Actions]
### Select Topic Area

Bug

### Body

In the following worklfow, the `ci` job must run only when `needs.start.outputs.package_names` is empty, but this isn't happening. Github Actions engine is evaluating the matrix configuration before the if statement. 

````yml
name: CI on Pull Request Workflow

on:
  workflow_call:
    secrets:
      MULE_NEXUS_USERNAME:
        required: true
      MULE_NEXUS_PASSWORD:
        required: true
      MULE_USERNAME:
        required: true
      MULE_PASSWORD:
        required: true
      MULE_VERSION:
        required: true
      CLOUDHUB_REGION:
        required: true
      CLOUDHUB_WORKER_COUNT:
        required: false
      CLOUDHUB_WORKER_TYPE:
        required: false
      ANYPOINT_CLIENT_ID:
        required: true
      ANYPOINT_CLIENT_SECRET:
        required: true
      ANYPOINT_BASE_URI:
        required: true
      ANYPOINT_ANALYTICS_BASE_URI:
        required: true
      CACHE_VERSION:
        required: true
      GH_PACKAGE_REPO_USERNAME:
        required: true
      GH_PACKAGE_REPO_PASSWORD:
        required: true

env:
  MULE_NEXUS_USERNAME: ${{ secrets.MULE_NEXUS_USERNAME }}
  MULE_NEXUS_PASSWORD: ${{ secrets.MULE_NEXUS_PASSWORD }}
  MULE_USERNAME: ${{ secrets.MULE_USERNAME }}
  MULE_PASSWORD: ${{ secrets.MULE_PASSWORD }}
  MULE_VERSION: ${{ secrets.MULE_VERSION }}
  CLOUDHUB_REGION: ${{ secrets.CLOUDHUB_REGION }}
  CLOUDHUB_WORKER_COUNT: ${{ secrets.CLOUDHUB_WORKER_COUNT }}
  CLOUDHUB_WORKER_TYPE: ${{ secrets.CLOUDHUB_WORKER_TYPE }}
  ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
  ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
  ANYPOINT_BASE_URI: ${{ secrets.ANYPOINT_BASE_URI }}
  ANYPOINT_ANALYTICS_BASE_URI: ${{ secrets.ANYPOINT_ANALYTICS_BASE_URI }}
  GITHUB_ACTOR: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
  GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}

permissions:
  contents: write
  pull-requests: write
  packages: read

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/<ORG>/mulesoft-build-image:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      package_names: ${{ steps.get_package_names.outputs.package_names }}

    steps:
      - name: Print env variables
        run: |
          env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Get Package Names
        id: get_package_names
        run: |
          package_paths=$(xpath -q -e "//project/modules/module" pom.xml | sed -e 's/<[^>]*>//g' | tr '\n' ' ')
          package_names=$(git diff --name-only --diff-filter=d $GITHUB_BASE_REF..HEAD -- $package_paths | cut -f2 -d '/' | sort -u)
          package_names=$(jq -c -n --arg package_names "$package_names" '$package_names | split("\n")')
          echo "PACKAGE NAMES: $package_names"

          echo "package_names=$package_names" >> $GITHUB_OUTPUT

  ci:
    if: needs.start.outputs.package_names
    name: CI
    uses: <ORG>/mulesoft-reusable-workflows/.github/workflows/ci.yml@main
    needs: start
    strategy:
      fail-fast: false
      matrix:
        PACKAGE_NAME: ${{ fromJson(needs.start.outputs.package_names) }}
    with:
      PACKAGE_NAME: ${{ matrix.PACKAGE_NAME }}
    secrets:
      MULE_NEXUS_USERNAME: ${{ secrets.MULE_NEXUS_USERNAME }}
      MULE_NEXUS_PASSWORD: ${{ secrets.MULE_NEXUS_PASSWORD }}
      MULE_USERNAME: ${{ secrets.MULE_USERNAME }}
      MULE_PASSWORD: ${{ secrets.MULE_PASSWORD }}
      MULE_VERSION: ${{ secrets.MULE_VERSION }}
      CLOUDHUB_REGION: ${{ secrets.CLOUDHUB_REGION }}
      CLOUDHUB_WORKER_COUNT: ${{ secrets.CLOUDHUB_WORKER_COUNT }}
      CLOUDHUB_WORKER_TYPE: ${{ secrets.CLOUDHUB_WORKER_TYPE }}
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
      ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      ANYPOINT_BASE_URI: ${{ secrets.ANYPOINT_BASE_URI }}
      ANYPOINT_ANALYTICS_BASE_URI: ${{ secrets.ANYPOINT_ANALYTICS_BASE_URI }}
      CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
      GH_PACKAGE_REPO_USERNAME: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
      GH_PACKAGE_REPO_PASSWORD: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}

  end:
    name: End
    runs-on: ubuntu-latest
    needs: ci
    continue-on-error: true

    steps:
      - name: End
        run: |
          echo "end"


````

This is the exception github actions throws

![image](https://user-images.githubusercontent.com/55927613/221577939-e711299a-88c5-461d-9b36-a1da44fb3705.png)

I don't think it makes sense to evaluate strategy before if statements.

**Comment by AllanOricil** [comment]
My bad, I was doing something stupid. The matrix is evaluated after the if statement.

![image](https://user-images.githubusercontent.com/55927613/221588897-8686b0be-9829-4394-adf4-48f131edcc1b.png)

**Comment by jsoref** [comment]
I opened https://github.com/github/docs/issues/24441 against the docs, as I can understand people being surprised by this.

**Reply by AllanOricil** [reply]
I was doing something wrong. The if statement runs before the matrix.

**Comment by npiccolo** [comment]
Hey @AllanOricil ,
Hope you are doing great !!!

I have a question about using parameters in the matrix for the called reusable workflow.

This part is working for you ??
```
    with:
      PACKAGE_NAME: ${{ matrix.PACKAGE_NAME }}
```

I'm getting this error: **The template is not valid. (Line: 49, Col: 16): A mapping was not expected**

When using this: 
```
    strategy:
      fail-fast: false
      matrix:
        release: ${{ fromJson(needs.get_nightly_builds.outputs.nightlyBuild) }}
    with:
      release: ${{ matrix.release }}
```

Line 49 refers to       `release: ${{ matrix.release }}`

Thank you very much in advance !! =D
