### DISCUSSION TITLE
Github App fails to bypass "require pull request" even when using "Allow specified actors to bypass required pull requests"

### DISCUSSION THREAD

**Discussion by jbnjohnathan** [community/community#48711] [Actions]
### Select Topic Area

Bug

### Body

We are running a Github action workflow that, after a merge has been made to `main` branch, updates the version in a file in the repository and creates a git tag and a release and pushes this to `main` branch.

The `main` branch has branch protection rules enabled:
**Require a pull request before merging**

We created a Github App with permissions to change files and tag commits in the repository.
We then added it to "Allow specified actors to bypass required pull requests"

Then we used the following code
```
name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - name: Get Token
      id: get_workflow_token
      uses: getsentry/action-github-app-token@v2
      with:
        app_id: ${{ secrets.BRANCH_PROTECTION_USER_APP_ID }}
        private_key: ${{ secrets.BRANCH_PROTECTION_USER_PRIVATE_KEY }}
    - name: Checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      id: python-semantic-release
      uses: ORG/python-semantic-release@4b4fad5f09b0244700092139b9187ffe0b6a2944
      with:
        github_token: ${{ steps.get_workflow_token.outputs.token }}
```

However we still get the error
```
error:   cmdline: git push ***github.com/ORG/test-semattic-versioning.git main
error:   stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/main.        
error: remote: error: Changes must be made through a pull request.        
error: To https://github.com/ORG/test-semattic-versioning.git
error:  ! [remote rejected] main -> main (protected branch hook declined)
error: error: failed to push some refs to 'https://github.com/ORG/test-semattic-versioning.git''
```

According to https://github.blog/changelog/2022-05-17-consistently-allow-github-apps-as-exceptions-to-branch-protection-rules/ this should work.

To rule out permission issue we tested to give the Github App write permission to everything in "Repository permissions" but the issue remains.
