### DISCUSSION TITLE
Action fails: Webpacker can't find manifest

### DISCUSSION THREAD

**Discussion by sigfrid** [community/community#48721] [Actions]
### Select Topic Area

Question

### Body

Hi there,
Dependabot opened a PR in a Rails app to bump webpack from 4.46.0 to 5.75.0. 
However, the CI fails on the PR with the following error

```
 ActionView::Template::Error:
       Webpacker can't find application.js in /home/runner/work/traininghub/traininghub/public/packs-test/manifest.json. Possible causes:
       1. You want to set webpacker.yml value of compile to true for your environment
          unless you are using the `webpack -w` or the webpack-dev-server.
       2. webpack has not yet re-run to reflect updates.
       3. You have misconfigured Webpacker's config/webpacker.yml file.
       4. Your webpack configuration is not creating a manifest.
       Your manifest contains:
       {
       }
```

I have pulled the branch locally, and everything works fine with the suite passing.

Here my action

```
name: continuous-integration

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  github:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: hub_ci
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@master

      - name: Check secrets
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}
        if: env.CC_TEST_REPORTER_ID == ''
        run: |
          echo "You must add CODE_CLIMATE_ID to the repo's secrets."
          exit 1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          sudo apt-get install -y libcups2-dev
          sudo apt-get install -y nodejs
          sudo apt-get install -y yarn
          sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_WITHOUT: development production
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: life:${{ secrets.RR_PAT }}
        with:
          #ruby-version: from .ruby-version
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install JS packages
        run: yarn install

      - name: Run RSpec & Push code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID:  ${{ secrets.CODE_CLIMATE_ID }}
          DATABASE_URL: postgres://postgres:password@localhost:5432/hub_ci
          PG_USER: postgres
          RUBYOPT: -W0
          RAILS_ENV: test
          CI: true
        with:
          coverageCommand: bin/rspec spec --fail-fast --format progress
```

Am I missing anything here?
What can cause rspec to fail on Github Actions?
