### DISCUSSION TITLE
Do something on created issue only if the created issue has a specific label

### DISCUSSION THREAD

**Discussion by zanhk** [community/community#48739] [Actions] [answered]
### Select Topic Area

Question

### Body

I have an issue template that automatically add a label.

How can I run the workflow only when issue with this labels are created?

I tried

```
on:
    issues:
        types: [opened]
        labels: ["prompt"]
```

but it doesn't seem to work.

I tried 

```
if: github.event.label.name == 'prompt'
```

But I think this event work only for adding/removing labels.

How can I do it?

Thanks

**Comment by sayhiben** [comment, marked as answer]
Try using `types: [labeled]` - if GitHub internally creates the issue _then_ labels it, this should trigger your workflow. [Docs here. 
](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues)

To your second attempt, if you want to verify what labels are present when the issue is opened, see about printing `github.event.issue.labels` to the log. [See the payload docs here.](https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=opened#issues)

**Reply by zanhk** [reply]
For anyone wondering full code look like this

```
name: Generate image

on:
    issues:
        types: [labeled]

env:
    node_version: "18.x"

jobs:
    generate-image:
        if: github.event.label.name == 'prompt'
        runs-on: ubuntu-latest
        steps:
            - ...
```
