### DISCUSSION TITLE
Workflow Runs dispatched from a different Workflow Run do not trigger workflow_run events

### DISCUSSION THREAD

**Discussion by sayhiben** [community/community#48748] [Actions]
### Select Topic Area

Bug

### Body

We have a Workflow configuration with three workflows:
1. A workflow to perform CI, triggered from `pull_request`
2. A workflow to perform deployment, triggered from the prior workflow via `workflow_dispatch`
3. A workflow to save logs from each completed workflow run, triggered via `workflow_run: types: [completed]`

When we make a PR or sync with a PR, we expect the first workflow to dispatch the second (using the workflow's `GITHUB_TOKEN`), then for the third workflow to run twice (once after each other completed workflow). However, in practice, we only see the third workflow run once.

This is a bit convoluted, so here's an example setup. [Repository here.](https://github.com/sayhiben/github-actions-sandbox/tree/main/.github/workflows)

# Example
## [Workflow 1](https://github.com/sayhiben/github-actions-sandbox/blob/main/.github/workflows/1-on-push.yml) (`on: push`)

```yaml
name: '1'

on:
  push:

permissions:
  actions: write

jobs:
  initial-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dispatch
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '2-on-workflow-dispatch.yml',
              ref: 'main'
            })
```

## [Workflow 2](https://github.com/sayhiben/github-actions-sandbox/blob/main/.github/workflows/2-on-workflow-dispatch.yml) (`on: workflow_dispatch`)
```yaml
name: '2'

on: workflow_dispatch

jobs:
  manually-dispatched-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!"
```

## [Workflow 3](https://github.com/sayhiben/github-actions-sandbox/blob/main/.github/workflows/3b-on-workflow-run-complete-from-workflow-dispatch.yml) (`on: workflow_run ... types: [completed]`)
```yaml
name: '3'

on:
  workflow_run:
    workflows: ['2']
    types: [completed]

jobs:
  post-dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dispatched workflow completed!"
```

# Example results
[Take a look at the runs in this repository](https://github.com/sayhiben/github-actions-sandbox/actions)

# Expected behavior
When I sync my pull_request, push, etc., it should run that workflow, that workflow should dispatch to a second workflow, and the third workflow should run after the second workflow completes. For example, in the same project I've linked, you can see that the `on: workflow_run ... types: [completed]` event [successfully triggers when the completed workflow refers to a run that was not dispatched](https://github.com/sayhiben/github-actions-sandbox/blob/main/.github/workflows/3a-on-workflow-run-complete-from-push.yml)

# Actual behavior
The third workflow never runs for workflows that were dispatched from a prior workflow

# Discussion
I believe this is related to the permissions of the initial workflow's `GITHUB_TOKEN` [and the limitations involved](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow), however this quirk is either only tangentially documented or an undocumented quirk of the behavior of the system.

I would like this to work without having to provision a long-lived PAT for the dispatch between the first two workflows. Please confirm if this behavior is by design or a bug.
