### DISCUSSION TITLE
Problem with Github Action job not reporting accurate job run results on a pull request.

### DISCUSSION THREAD

**Discussion by bobbyflowstate** [community/community#48751] [Actions]
### Select Topic Area

Question

### Body

I'm having an issue with a Github Action not blocking or reporting a failure on pull requests because of adjacent skipped tests.

## Context

- We have a monorepo with multiple next.js projects.
- On every pull request each of those projects gets built and deployed on vercel.
- We also have an end 2 end test that gets run by a Github Action on `deployment_status`. However each job runs if and only if the deployment is successful and the url matches a pattern. Here's the config:

```yml
on:
  deployment_status:
jobs:
  test-flixed-home:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.target_url, 'flixed-home')
```

As a result, the runs for that Github Action looks like this:
<img width="455" alt="Screenshot 2023-02-27 at 8 46 39 PM" src="https://user-images.githubusercontent.com/2475027/221731640-d237d0a4-3278-4716-9b5f-ddf618fe2122.png">

As you can see there are several runs that were skipped and one that ran and passed.

As a result the checks on a Github PR looks like this:
<img width="893" alt="Screenshot 2023-02-27 at 8 47 20 PM" src="https://user-images.githubusercontent.com/2475027/221731752-951efc38-a6e3-4952-b1c9-3c107a78fb3e.png">

It says the job was skipped, while in fact 1 of them ran and passed. That doesn't seem terrible in this case, but now I'm seeing the same situation even when 1 of the tests runs and fails:

<img width="464" alt="Screenshot 2023-02-27 at 8 49 47 PM" src="https://user-images.githubusercontent.com/2475027/221732098-5e505eb3-ffae-4300-9aab-92d40d2ed5b1.png">

In the above case we're still seeing this:
<img width="860" alt="Screenshot 2023-02-27 at 8 57 39 PM" src="https://user-images.githubusercontent.com/2475027/221733137-9a72c32d-fd49-4ae6-a452-109c8086e6b8.png">

How can I have the Github check on a PR surface the failed job, even when there are several skipped jobs adjacent to it?

Is this possible or do I need to modify the way we run our E2E tests?

**Comment by rajasbattu** [comment]
I am facing the same issue do you find any solution ?

**Comment by ericmatthys** [comment]
The `deployment_status` action can be used to run the tests and then manually report a status for a required check of a different name. This way, the `deployment_status` action can be skipped without interfering with the status of the required check.


```yaml
- name: Run end-to-end tests
  id: test
  continue-on-error: true
  run: ...

- name: Update check status to the outcome
  run: pnpm node reportGitHubCheckStatus.mjs "End-to-end (${{ github.event.deployment_status.environment }})" ${{ github.sha }} ${{ steps.test.outcome }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```js
import { createActionAuth } from '@octokit/auth-action';
import { Octokit } from '@octokit/rest';

async function main() {
  const args = process.argv.slice(2);
  const auth = createActionAuth();
  const authentication = await auth();
  const octokit = new Octokit({
    auth: authentication.token,
    userAgent: 'your custom user agent',
  });

  await octokit.rest.repos.createCommitStatus({
    owner: 'ericmatthys',
    repo: 'example-repo',
    context: args[0],
    sha: args[1],
    state: args[2],
  });
}

main();
```

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by jeremycolin** [comment]
I had a very similar issue where we were deploying the same build to different Vercel projects. The solution was to use the github api to force status checks.

We ended up with a common job e2e-tests-pending forcing the pending status if it was not set:

```yaml
jobs:
  e2e-tests-pending:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Set status check to pending if status if not already set, it can be done by either job
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
        run: |
          existing_status=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/status --jq '.statuses[] | select(.context=="your workflow context here") | .state' | head -n 1)

          if [[ "$existing_status" != "success" && "$existing_status" != "failure" ]]; then
            gh api repos/${{ github.repository }}/statuses/${{ github.sha }} \
              -f state=pending \
              -f context="your workflow context here" \
              -f description="Waiting for correct deployment to run tests"
          fi
```

And then in the tests job itself:

```yaml
  e2e-tests:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.environment == 'your project here' && github.event.deployment_status.state == 'success'

    ...

     - name: Set status check to success
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state=success \
            -f context="your workflow context here" \
            -f description="e2e tests passed"

      - name: Set status check to failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state=failure \
            -f context="your workflow context here" \
            -f description="e2e tests failed"
```
