### DISCUSSION TITLE
Job Outputs EOF

### DISCUSSION THREAD

**Discussion by kvernon** [community/community#48757] [Actions]
### Select Topic Area

Question

### Body

Howdy again all!

I've recently run across a situation where I need to do an `EOF` for job outputs, but I don't know how to make that happen.

I can get do outputs at a step like so:

```yml
  changelog_production:
    name: Prod Changelog Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Changelog EOF out
        id: out
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "${{ steps.changelog.outputs.changelog }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

```

I cannot figure out how to do the assignment while using an EOF strategy for a different job to access the info.

Any ideas?

Cheers,
Kelly
