### DISCUSSION TITLE
Jekyll site deployed on Github Pages through Github Actions yields 404

### DISCUSSION THREAD

**Discussion by b-fg** [community/community#48793] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I have been trying to deploy a Jekyll site on Github Pages using Github Actions.
The page I am trying to deploy is: https://b-fg.github.io/ and my Github repository is https://github.com/b-fg/b-fg.github.io
The action runs the bundle to generate the static site, and everything works as expected, including the deployment as indicated in the Github actions workflow: https://github.com/b-fg/b-fg.github.io/actions/runs/4292617836

The Jekyll action I am using is [this one](https://github.com/b-fg/b-fg.github.io/blob/main/.github/workflows/github-pages.yml):
```
name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020
# on:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2    # Choose any one of the Jekyll Actions
        with:                             # Some relative inputs of your action
          target_branch: gh-pages
          pre_build_commands: |
            git config --global --add safe.directory /github/workspace
          token: ${{ secrets.GITHUB_TOKEN }}
```
In short, it builds the site on the `gh-pages` branch after a push on the `main` branch.

Even though the site has been deployed according to the actions log, I run into the 404 site not found error.
Also note that the page can be generated and correctly accessed locally, so that should not be the problem.
I have been looking all the related posts but nothing seems to resolve the issue.
Any help would be appreciated. Thanks!
