### DISCUSSION TITLE
How to trigger github action ci for tags and branch push

### DISCUSSION THREAD

**Discussion by code-R** [community/community#48858] [Actions] [answered]
### Select Topic Area

Question

### Body

```
name: Test Workflow

on:  
  push:
    tags:
      - "*"
    paths:
      - "common/**"
      - "myservice/**"      
    branches:
      - main
```
I want to trigger the workflow on pushing changes to main branch and on only specific paths but, for pushing tag I want to ignore paths, is that possible ? I mean one possible solution that I can think of is, define two workflow files but, apart from that are there any other solutions?

**Comment by jge162** [comment, marked as answer]
@code-R it is possible to define multiple paths for the `push` event and exclude specific paths for certain conditions such as tags. here is an example pseudo code. 

```yaml
on:
  push:
    branches:
      - main
    paths:
      - "common/**"
      - "myservice/**"
    if: "!startsWith(github.ref, 'refs/tags/')"

  push:
    tags:
      - "*"
    branches:
      - main
    if: "startsWith(github.ref, 'refs/tags/')"
```

**Reply by code-R** [reply]
its not allowing me to use conditional statement like you have given

**Reply by jge162** [reply]
I just ran this and no issues with conditional statements. 

```yaml
name: My GitHub Action

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "common/**"
      - "myservice/**"
    tags:
      - "*"
    if: |
      (startsWith(github.ref, 'refs/tags/')) || 
      (!startsWith(github.ref, 'refs/tags/') && 
      contains(github.event.head_commit.modified, 'common/') || 
      contains(github.event.head_commit.modified, 'myservice/'))
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run my command
        run: |
          # Add your command here
```

**Reply by jge162** [reply]
Ran this too. Zero issues @code-R 

```yaml 
name: My GitHub Action

on:
  workflow_dispatch:

    push:
    branches:
      - main
    paths:
      - "common/**"
      - "myservice/**"
    if: "!startsWith(github.ref, 'refs/tags/')"

  push:
    tags:
      - "*"
    branches:
      - main
    if: "startsWith(github.ref, 'refs/tags/')"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run my command
        run: |
          # Add your command here
```

**Reply by jge162** [reply]
Here is link to action [results](https://github.com/jge162/Action-workflows/actions/runs/4301362374)

**Reply by code-R** [reply]
thanks, it worked for me too, I have defined it wrongly before.

**Comment by code-R** [comment]
@jge162 thank you, will give that a try, I thought in yaml redefining same key will have override effect (similar to dictionaries or map)

**Reply by jge162** [reply]
There is no overriding of `keys` in the pseudo code I gave above. 

Each occurrence of the push `key` is part of a separate mapping within a sequence, so they are not in conflict with each other.

**Reply by code-R** [reply]
right, the if condition makes it as two separate push events..Thank you so much @jge162 👍

**Comment by jeetkn** [comment]
@jge162 
I've tested it and `on.push.if` syntax doesn't seem to work.
Is it normal that it still works based on the `on.push.if` condition?

I expected the action to be triggered when tagged in the form of `v*.*.*`, but it also triggered when the commit was pushed to the main branch.
``` yaml
name: My GitHub Action

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
    if: startsWith(github.ref, 'refs/tags/')

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run my command
        run: |
          echo "hello world" 
          echo "${{ github.ref }}"
```

**Reply by jge162** [reply]
The reason for this behavior might be the branches section in your workflow configuration. You’ve specified that the workflow should run on the `main` branch in addition to `tags.` To make it trigger only on `tags` with the specified use case,  remove the branches section. 

```yaml

name: jeetkn GitHub Action

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    if: startsWith(github.ref, 'refs/tags/')

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run my command
        run: |
          echo "hello world" 
          echo "${{ github.ref }}"
```
