### DISCUSSION TITLE
If all the jobs of a workflow are skipped, it should preserve the status of the previous run

### DISCUSSION THREAD

**Discussion by ilyasmez** [community/community#48875] [Actions]
### Select Topic Area

Product Feedback

### Body

Let's say you have a workflow like this one:

```yaml
name: CI v2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize, labeled]

jobs:
  ci:
    name: CI
    if: |
      (github.event.action == 'labeled' && contains(github.event.label.name, 'CI')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'CI')) ||
      (github.event_name == 'push')
    uses: ./some-workflow.yml
```

This means that the `ci` job will run only if the PR has the `CI` label, which is good.
Let's take the following scenario:
1. Open a PR
1. Add the label `CI`
1. [The workflow will run successfully] 
1. [The success status is reported to the PR, so the user can merge the PR if they have a protection that requires this check]

But if the user adds another label (e.g. `on-hold`), the workflow will run again (because we're listening to the `pull_request.labeled` event), but all the `ci` will be skipped based on the `if` condition. Until here, everything is working as expected. But the issue is that the "skipped" status is reported to the PR, and it will overwrite the previous "success", which will prevent the user from merging the PR.

This can be fixed using artifacts (saving the previous results, and if the job will be skipped, then we just report what we have saved in the artifacts). But this sounds like an overkill to me. I think Github should do this out of the box. If all the jobs of a workflow were skipped, it shouldn't report the status to the PR, or it should just keep the previous status, to avoid this:
<img width="467" alt="Screen Shot 2023-03-01 at 10 27 20" src="https://user-images.githubusercontent.com/30146019/222098306-b5fcbc52-2ce9-4c63-a7e5-c7f06e3e32e5.png">
