### DISCUSSION TITLE
how to make pull request workflow also respond to pull request comments

### DISCUSSION THREAD

**Discussion by josh-m-sharpe** [community/community#48895] [Actions]
### Select Topic Area

Question

### Body

I want to comment on a PR "rerun build" and have the build restart from the beginning.  

Here is my existing workflow file:

```
name: Pull Requests
run-name: ${{ github.head_ref }} (${{ github.actor }}) 🚀

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  tests:
    uses: ./.github/workflows/test_suite.yml
```

How do I modify this to also respond to specific comments?

**Comment by Anmol-Baranwal** [comment]
You can do this: (this will be able to read the comment from the PR)

```yml
if: >-
      (github.event.comment.body == '#comment1' ||
       github.event.comment.body == '#comment2')
    steps:
      - run: |
```
and run specific code to rerun build.

> You would have to try it once.

Feel free to ask further doubts.

**Reply by josh-m-sharpe** [reply]
this doesn't address the actual question in the post

**Reply by josh-m-sharpe** [reply]
The `pull_request` event does not respond to issue comments.  At a minimum I need to add `on: [issue_comment, pull_request]` but then there are conflicts because the `github` scope is not available for the `issue_comment` event.

I have read my question.  Your response didn't include adding the issue_comment event.

**Reply by jsoref** [reply]
Technically _some_ of the [`github` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) is available, but it's a very different object.

@josh-m-sharpe, you have my sympathies. You provided a complete workflow and asked a fully formed question. The "answer" provided would not work as provided.

@Anmol-Baranwal your answer would get a failing grade ❌ if this was a Quiz and I was the grader. You can't just randomly mention a field that isn't available and expect someone to magically add the other incantations necessary to conjure up the necessary bits such that it will work. It is totally reasonable for someone to 👎 a response that is inaccurate/misleading. Your response was as bad as using ChatGPT when it lies/makes stuff up.

**Reply by Anmol-Baranwal** [reply]
> Please do not pin if it is not urgent. I would appreciate it.

@jsoref 
I would not have stretched this, but since you pinned me:
I have already accepted the mistake as I misunderstood the question, and you should appreciate everyone who is trying to help. 

I would gladly accept the challenge where I compete against you in a Quiz. You will certainly get a ❌ grade.
Your criticism is as bad as if the bug in the code pops and begs for removal.

I do appreciate constructive criticism but not of this kind 👎. Just say what is needed, and no more ❌

**Reply by jsoref** [reply]
The word you wanted here was `pinged` 🧿 not `pinned` 📌. Note that both words are used in discussions. Pinned conversations are the ones at the top of a given category.

**Comment by jge162** [comment]
Hello @josh-m-sharpe so I think I know what you are hoping to accomplish with your question and use case. 

When someone comments "rerun build" on either a pull request or an issue, the workflow will be triggered again and the build will restart from the beginning.

- See pseudo code below:

```yaml

name: Pull Requests
run-name: ${{ github.head_ref }} (${{ github.actor }}) 🚀

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running tests"
        env:
          RERUN: ${{ github.event.comment.body == 'rerun build' }}
        if: env.RERUN == 'true'
```

**Reply by josh-m-sharpe** [reply]
@jge162 so that's about where I landed.  But pretty sure `github.head_ref` is not available in either the `run-name` or `concurrency.group` scope which makes that example non-functional.  This is only true for `issue_comment` events.  This doesn't make sense to me because even an issue comment relates to a PR which relates to a branch

**Reply by jsoref** [reply]
Issue comments can be on Issues, not just on Pull Requests, and there really doesn't have to be a pull request head.

There can be a current commit on the default branch, although iirc it might even be possible to have a repository with issues and no code at all. 

I'm not defending this behavior. My workflow has an issue comment handler, and frankly it's a bit of a 🫓. But to fix it would require me to have a chance to talk to Staff.

(And please don't be confused by the Pull Request Comment stuff, those are *not* the events you're looking for–been there tricked by that. )

If you have an Enterprise contract, I'd suggest using it to file an issue. If you don't, you might consider filing a ticket with support.

**Reply by jge162** [reply]
> @jge162 so that's about where I landed. But pretty sure `github.head_ref` is not available in either the `run-name` or `concurrency.group` scope which makes that example non-functional. This is only true for `issue_comment` events. This doesn't make sense to me because even an issue comment relates to a PR which relates to a branch

Josh I just created this action. Ran it and when I type into pull request comment section (rerun build) it reruns action. Then I created an issue related to the pull request. Typed (rerun build) as a comment in issue it reran action once. 

Is this what you are trying to do? It works

```yaml
name: rerun Pull Requests
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if rerun is requested
        run: echo "RERUN=${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rerun build') }}" >> $GITHUB_ENV
      - name: Check if pull request
        if: github.event_name == 'pull_request'
        run: echo "RUN_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
      - name: Rerun workflow
        if: env.RERUN == 'true'
        run: echo "Rerunning workflow"
        env:
          RUN_ID: ${{ github.run_id }}
 ```

**Reply by jsoref** [reply]
For concurrency you can add the issue number, that'll at least guard against comments on other issues killing your workflow run.

But what do you want to do if two people write your trigger word in a comment on the same issue (one before the first workflow finishes). And keep in mind that you probably don't want a second comment that doesn't include your trigger to kill your first run.

https://github.com/jsoref/debug-github-events/actions/runs/4365677373/jobs/7634632610

`head_ref` is empty (as noted earlier), so you can't use that:
`github`:
```JSON
{
  "token": "***",
  "job": "debug",
  "ref": "refs/heads/main",
  "sha": "a6a2388e14308269ef301a643b02ad8d591b2c03",
  "repository": "jsoref/debug-github-events",
  "repository_owner": "jsoref",
  "repository_owner_id": "2119212",
  "repositoryUrl": "git://github.com/jsoref/debug-github-events.git",
  "run_id": "4365677373",
  "run_number": "24",
  "retention_days": "90",
  "run_attempt": "1",
  "artifact_cache_size_limit": "10",
  "repository_visibility": "public",
  "repository_id": "609172270",
  "actor_id": "2119212",
  "actor": "jsoref",
  "triggering_actor": "jsoref",
  "workflow": "debug",
  "head_ref": "",
  "base_ref": "",
...
```

https://github.com/jsoref/debug-github-events/actions/runs/4365667831/jobs/7634609425

**Reply by jge162** [reply]
Ok so I have been trying but unsuccessful with implementing one recommendation. Can you please retest yaml with your debugger when time permits. 

My only issue now is just using issue number to prevent other runs from being terminated. Maybe you can review this @josh-m-sharpe it does 80% of what you wanted. Minus just me adding concurrency. Thanks. 

```yaml
name: rerun Pull Requests
on:
  pull_request:
    types: [opened, synchronize]
    concurrency:
      cancel-in-progress: true
  issue_comment:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if rerun is requested
        run: echo "RERUN=${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rerun build') && contains(github.event.issue.number, github.event.comment.issue_number) }}" >> $GITHUB_ENV
      - name: Check if pull request
        if: github.event_name == 'pull_request'
        run: echo "RUN_NAME=${{ github.ref }}" >> $GITHUB_ENV
      - name: Rerun workflow
        if: env.RERUN == 'true'
        run: echo "Rerunning workflow"
        env:
          RUN_ID: ${{ github.run_id }}
      - name: Print head ref
        if: github.event_name == 'pull_request'
        run: echo "HEAD_REF=${{ github.head_ref }}" >> $GITHUB_ENV
      - name: Print run ID
        if: always()
        run: echo "RUN_ID=${{ github.run_id }}"
      - name: Print environment variables
        if: always()
        run: |
          echo "RERUN=$RERUN"
          echo "RUN_NAME=$RUN_NAME"
 ```

**Reply by jsoref** [reply]
Concurrency is only available as a global or within individual jobs:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idconcurrency

You could use something like this:
https://github.com/check-spelling/spell-check-this/blob/d9a0dd9644c2de81a18fa2716104c4d64c63b5f6/.github/workflows/spelling.yml#L67-L70
```
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
```

But, again, keep in mind that it'll do the wrong thing if two people comment on your PR in the same window, offhand, i think 

```
      group: something-${{ github.event.comment.id || github.ref }}
```
would work moderately well. That'd ensure that if it's a comment, it's treated independently. In theory if you asked for comment edits, your event could concurrently cancel the previous workflow run, but otherwise make it independent.

The [`github.ref`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) side is for PRs.

**Reply by jsoref** [reply]
If you really wanted to risk things, you could use `${{ github.event.comment.issue_url }}` instead. Keep in mind that if one workflow run decides it wants to do something and another workflow run is triggered and decides it doesn't (in the `run` or `uses` -- not the `if`, since `if`s should prevent a run from being `queued`) then it'll definitely kill the previous run.

**Reply by jge162** [reply]
Great suggestions. Here is updated yaml. 

```yaml
name: rerun Pull Requests
run-name: ${{ github.head_ref }} (${{ github.actor }}) 🚀

concurrency:
  # group: rerun_concurrency_${{ github.event.pull_request.number }}
  group: spelling-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Check if rerun is requested
       # run: echo "RERUN=${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rerun build') && contains(github.event.issue.number, github.event.comment.issue_number) }}" >> $GITHUB_ENV
      - name: Check if rerun is requested
        if: github.event_name == 'issue_comment'
        env:
          COMMENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: echo "RERUN=${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rerun build') && contains(github.event.issue.number, env.COMMENT_ISSUE_NUMBER) }}" >> $GITHUB_ENV
      - name: Check if pull request
        if: github.event_name == 'pull_request'
        run: echo "RUN_NAME=${{ github.ref }}" >> $GITHUB_ENV
      - name: Rerun workflow
        if: env.RERUN == 'true'
        run: echo "Rerunning workflow"
        env:
          RUN_ID: ${{ github.run_id }}
      - name: Print head ref
        if: github.event_name == 'pull_request'
        run: echo "HEAD_REF=${{ github.head_ref }}" >> $GITHUB_ENV
      - name: Print run ID
        if: always()
        run: echo "RUN_ID=${{ github.run_id }}"
      - name: Print environment variables
        if: always()
        run: |
          echo "RERUN=$RERUN"
          echo "RUN_NAME=$RUN_NAME"
 ```
