### DISCUSSION TITLE
can't get github.head_ref for workflow triggered by pull_request and issue_comment events

### DISCUSSION THREAD

**Discussion by josh-m-sharpe** [community/community#48926] [Actions]
### Select Topic Area

Bug

### Body

workflow is supposed to:
1) run for new pushes to a PR
2) run if PR is commented "rerun build"
3) Cancel previous builds on that PR's branch

Issue is: `${{ github.head_ref }}` is available for a pull_request event, but is not for issue_comment.  

```
name: Pull Requests
run-name: ${{ github.head_ref }} (${{ github.actor }}) 🚀

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
  issue_comment:
    types: [created, edited]

jobs:
  tests:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rerun build'))
    uses: ./.github/workflows/test_suite.yml
```

I have tried echoing all of these things in workflow that responds to issue_comment and none of them return the PR's branch name:

$GITHUB_REF_NAME
$GITHUB_HEAD_REF
${{ env.GITHUB_REF_NAME }}
${{ env.GITHUB_HEAD_REF }}
${{ github.ref }}
${{ github.head_ref }}
${{ github.event_name }}
${{ github.event.comment.body }}

**Comment by josh-m-sharpe** [comment]
![Github_Workflow__Build_Rerun](https://user-images.githubusercontent.com/39473/222265362-2590a18f-dc4a-4420-bcfb-06ce98497534.jpg)

**Comment by josh-m-sharpe** [comment]
but alas, AI is wrong

**Comment by josh-m-sharpe** [comment]
These two runs were triggered by this workflow:

```
name: Pull Requests
run-name: ${{ github.head_ref }} (${{ github.actor }}) 🚀

on:
  pull_request:
  issue_comment:
    types: [created, edited]

jobs:
  tests:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rerun build'))
    uses: ./.github/workflows/test_suite.yml
```

The first one (the one on the bottom) was from pushing a new commit to the branch.  This looks good/correct.
The second one (the one on the top) was from commenting on the open PR `rerun build`. It's great the job ran, but the name is wrong.

![Actions_·_calltracking_github_actions_pg](https://user-images.githubusercontent.com/39473/222265640-39c768da-c77c-4a2d-8a8f-5aecc73950a8.jpg)
