### DISCUSSION TITLE
Github actions workflow running without stopping: Workflow stuck

### DISCUSSION THREAD

**Discussion by paras21avenue** [community/community#48928] [Actions]
### Select Topic Area

Bug

### Body

Workflow is stuck at the step: flow-target as the value being generated from the previous step is large and it seems it is unable to process it. It has been running for over 45 minutes.

`steps:
      - name: converting vqltobase64
        run: | 
            echo "get_value=$(base64 -w 0 metadata4.vql | cut -c 5- | iconv -f utf8 -t iso8859-5)" >> $GITHUB_ENV
           
      - name: flow-target
        run: curl --location 'https://10.xxx.x.xx:xxxx/test/loadFromVQL' --header 'Content-type:application/json' --header 'Authorization:Basic xxxxxxxxxxx' --data '{"name":"test_rev-007","description":"revision_creation","content":"'"${{ env.get_value }}"'"}' > at.json
        
      - name: get target id
        run:
           echo "get_revision_id= $(jq '.id' at.json)" >> $GITHUB_ENV
           
      - name: print revision id
        run : echo "${{env.get_revision_id }}"
        
      - name: deploy to target env
        run: curl -g --location 'https://10.xxx.x.xx:xxxx/deployments' --header 'Authorization:Basic xxxxxxxxxxx' --header 'Content-Type:application/json' --data '{"revisionIds":[${{env.get_revision_id}}],"environmentId":82,"description":"test"}'`

**Comment by sayhiben** [comment]
`curl` commands have no default timeout. If your server doesn't respond to the request, it will run until the GitHub Actions default timeout, which I believe is six hours.

I suggest updating your `curl` command to specify a [maximum timeout](https://everything.curl.dev/usingcurl/timeouts) with `-m` or `--max-time`

**Comment by jge162** [comment]
It's possible that the `flow-target` step is taking a long time to complete because the size of the `get_value` environment variable is too large for the API endpoint to process. Try splitting it up.

**Reply by paras21avenue** [reply]
Hello @jge162 : that is exactly what is happening, the size of get_value is too large but the api can handle the large data (tested in postman). the fact is github actions is unable to process it. The workflow gets stuck even if i try to write the data to a file.
I cannot split the get_value data, the functionality would not work. The api creates a set of resources that is available in the get_value data, i cannot split it as it breaks the existing resource structure.

**Reply by jge162** [reply]
@paras21avenue You can try writing the data to a file instead of using environment variables to pass the data, you can write the data to a file in the `vqltobase64` step and then read the file in the `flow-target` step. (This is merely pseudo code and you need to fix pathing etc...Just trying to give you ideas for your use case.)

```yaml
- name: converting vqltobase64
  run: |
    echo "get_value=$(base64 -w 0 metadata4.vql | cut -c 5- | iconv -f utf8 -t iso8859-5)" > get_value.txt

- name: flow-target
  run: |
    # Read the data from the file 
    CONTENT=$(cat get_value.txt | base64 --decode)

    # data to the API
    curl --location 'https://10.xxx.x.xx:xxxx/test/loadFromVQL' \
      --header 'Content-type:application/json' \
      --header 'Authorization:Basic xxxxxxxxxxx' \
      --data '{"name":"test_rev-007","description":"revision_creation","content":"'"$CONTENT"'"}' > at.json
```
