### DISCUSSION TITLE
When running the MacOS-12 runner using setup-node, it installs the x64 version of Node instead of arm64. How to switch to arm64?

### DISCUSSION THREAD

**Discussion by jsoneaday** [community/community#48934] [Actions]
### Select Topic Area

Question

### Body

I am running the job below and when I monitor the setup-node@v3 uses I can see that it installs for darwin x64. Isn't this supposed to be M1 compatible? How can I force arm64 installation of node?

```
name: test-keyring-go
on: [push]
jobs:
  build-native-node-module-on-mac:
    runs-on: macos-12
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'          
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'      
      - run: npm install --ignore-scripts
      - run: npm run build:go:m1
      - run: npm run build:node:m1
      - run: npm run test
      - run: npm run vitest
```
