### DISCUSSION TITLE
On create tags doesn't work as expected

### DISCUSSION THREAD

**Discussion by baptisteArno** [community/community#48966] [Actions] [answered]
### Select Topic Area

Bug

### Body

A Github action starting with:

```
on:
  create:
    tags:
      - 'v*'
```

Will still be triggered when another action creates a tag that doesn't start with "v". For example `react-v1.0.0` or `js-v1.0.0`

So I tried specifically ignore them like this:

```
on:
  create:
    tags:
      - 'v*'
      - '!js-v*'
      - '!react-v*'
```

But it still triggers the action for these tags.

What am I missing?
