### DISCUSSION TITLE
Maven Snapshots in Packages accumulate / is there a way to clean up old SNAPSHOTs

### DISCUSSION THREAD

**Discussion by TomRauchenwald** [community/community#48971] [Packages]
### Select Topic Area

Question

### Body

We are evaluating if we can migrate to GitHub packages as a maven repository for our organization.

One thing we noticed is that when we build maven -SNAPSHOT versions multiple times, the artifacts accumulate quickly under the -SNAPSHOT version (since maven appends a timestamp to each artifact, and we want to build each commit to our main branch).
The older artifacts are not needed anymore, but they still waste disk space.

Is there a way to say "keep only the latest x SNAPSHOT versions" like in other tools?
Or is there a way to clean up outdated artifacts with an action?

As far as I understand it, currently it's only possible to delete the entire version... is my understanding correct?

Thanks!

**Comment by rauzerfabiano** [comment]
Yes, you are correct that currently there is no built-in way to automatically delete old snapshot versions in GitHub Packages. When you deploy a snapshot version to GitHub Packages, each build creates a new timestamped artifact, and there is no built-in functionality to automatically delete old artifacts.

However, you can use GitHub Actions to delete old snapshot versions. You can write a custom script or use an existing action to delete old snapshot versions. Here is an example workflow that you can modify to delete old snapshot versions:

```
name: Delete Old Snapshots

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  delete-old-snapshots:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delete old snapshots
      uses: joshdk/github-packages-delete@v3.3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: myorg/myrepo
        keep: 5 # Change this number to the number of latest snapshots you want to keep
        package-type: maven
        package-name: mypackage
        package-version: SNAPSHOT
```

This workflow runs every day at midnight and deletes all but the latest 5 snapshot versions of a specific Maven package in a specific repository owned by your organization. You can customize the values for _repository_, _package-name_, _package-version_, and _keep_ to fit your specific needs.

Note that you need to have appropriate permissions to delete packages in the repository, and you also need to provide a valid GITHUB_TOKEN secret that has those permissions.
