### DISCUSSION TITLE
dependabot: Include additional files? (feature request)

### DISCUSSION THREAD

**Discussion by dmke** [community/community#48976] [Code Security]
### Select Topic Area

Product Feedback

### Body

Hi,

I've recently noticed, that dependabot stopped producing PRs for scheduled updates:

```yaml
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/gemfiles/rails-main"
    schedule:
      interval: "weekly" # volatile, avoid daily PRs
      time:     "08:30"
      timezone: "Europe/Berlin"
```

(extracted from [here](https://github.com/digineo/texd-ruby/blob/master/.github/dependabot.yml))

The reason is, that I've tried to clean up common dependencies in that repository: https://github.com/digineo/texd-ruby/commit/c4fbc8478a40f17d99f8476ae029ef103b2d1fa2, essentially by moving them into an external file, and evaluating them in the corresponding `Gemfile`:

```ruby
# gemfiles/*/Gemfile
eval File.read File.join(__dir__, "../common.rb")

# gemfiles/common.rb
group :development, :test do
  # ...
end
```

Since `c4fbc84`, dependabot fails to produce updates. The [dependabot alerts](https://github.com/digineo/texd-ruby/security/dependabot/61) (link requires elevated permissions) show the following error:

> **Dependabot can't evaluate your Ruby dependency files**
>
> Dependabot failed to update your dependencies because there was an error evaluating your Ruby dependency files.
> 
> Dependabot encountered the following error:
> 
> ```
> Bundler::Dsl::DSLError with message: [!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /home/dependabot/dependabot-updater/dependabot_tmp_dir/gemfiles/rails-6.0/../common.rb. Bundler cannot continue.
> 
>  #  from /home/dependabot/dependabot-updater/dependabot_tmp_dir/gemfiles/rails-6.0/Gemfile:9
>  #  -------------------------------------------
>  #  
>  >  eval File.read File.join(__dir__, "../common.rb") # rubocop:disable Security/Eval
>  #  -------------------------------------------
> ```

It would be nice, if I could declare additional support files in the `dependabot.yml`, something like this:

```yaml
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/gemfiles/rails-main"
    support_files:
    - "/gemfiles/common.rb"
    schedule: # omitted
```
