### DISCUSSION TITLE
How to inspect containers that aren't the main container?

### DISCUSSION THREAD

**Discussion by wbyatt-kr** [community/community#49018] [Codespaces]
### Select Topic Area

Question

### Body

I am trying to enable Codespaces for my team for our service-oriented architecture. I have an application that's supported by an API layer and several services. As I'm developing the Codespaces configuration, I'd like to be able to debug my service containers. This won't necessarily be an ongoing requirement (although it might be nice if developers could examine the logs of backend services).

My services look like this (this is pretty close to real, with just a few environment directives removed and names changed):

```
 frontend:
    image: mcr.microsoft.com/devcontainers/universal:2-linux
    volumes:
      - .:/workspace
    depends_on:
      - api
  api:
    image: [ECR hosted image]
    restart: unless-stopped
    depends_on:
      - user-service
      - postgres
      - redis
  user-service:
    image: [Another ECR hosted image]
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
  postgres:
    image: [Custom image with our seed data]
    restart: unless-stopped
    command: [ "postgres", "-c", "wal_level=logical" ]
  redis:
    image: redis
    restart: unless-stopped    
```

And I have `"service": "frontend"` in my `devcontainer.json`.

But I cannot for the life of me figure out how to, from within the Codespace, connect to and debug the `api` and `user-service` containers. I tried using the `docker-outside-docker` feature, but `docker ps` from inside the Codespace still returned nothing.

I would be happy with something equivalent to `docker compose logs -f api`, but `docker compose exec api /bin/bash` would be even better. I suppose I could rebuild my `api` image to include an ssh server in it, but I'd prefer not to do that if I can avoid it.

Thanks in advance.

**Comment by rauzerfabiano** [comment]
To be able to connect and debug the api and user-service containers from within the Codespace, you need to expose the necessary ports in the container and map them to ports on the host.

You can do this by adding a ports section to the service definitions in your docker-compose file, like this:

  ```
api:
    image: [ECR hosted image]
    restart: unless-stopped
    depends_on:
      - user-service
      - postgres
      - redis
    ports:
      - "8080:8080" # map container port 8080 to host port 8080

  user-service:
    image: [Another ECR hosted image]
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8081" # map container port 8081 to host port 8081

```
Then, from within the Codespace, you can use the mapped host ports to connect to the containers. For example, to connect to the api container, you can use http://localhost:8080/.

To view the logs of a container, you can use the docker logs command, like this:

`docker-compose logs -f api`

And to execute a command in a container, you can use the docker exec command, like this:
`
docker-compose exec api /bin/bash`

Note that you may need to prefix the docker commands with sudo if your Codespace is running in a Linux environment.

**Reply by wbyatt-kr** [reply]
Maybe I was unclear. I am using GitHub's hosted Codespaces product, I am not using locally-running devcontainers. So I do not have access to the host. I do not have access to `docker compose` commands. I am trying to build and debug this from _inside_ the Codespaces container.

Exposing the ports also does not solve my problem. I can connect to the services if they are running, but I need to access the container, not the service.

If it's helpful, I'm reasonably experienced with docker and docker compose. We are currently using docker compose to build remote development environments in AWS EC2 instances. I am exploring the possibility of migrating these to Codespaces so that we have less to manage directly.

**Comment by Fengyi-Li** [comment]
@wbyatt-kr to test and debug your dev container configurations, you can try to rebuild the container to apply changes to your current codespaces.
Docs:
https://docs.github.com/en/codespaces/codespaces-reference/performing-a-full-rebuild-of-a-container
https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers

And there are logs that can help you debugging configuration issues:
https://docs.github.com/en/codespaces/troubleshooting/github-codespaces-logs

**Reply by wbyatt-kr** [reply]
Hi @Fengyi-Li thank you for answering, but I am doing rebuilds, that's how I'm iterating at all. These longs are unfortunately not helpful, because they stop once the containers are created. I need the logs from the docker containers once they are running.

Thank you.

**Comment by r0zh** [comment]
@wbyatt-kr I don't know if you still need this, but I found it useful to use portainer for this purpose. With portainer you can debug your services. It's very intuitive. This is how I implemented it in my docker-compose.yaml:

```
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    ports:
      - '9443:9000'
volumes:
  portainer_data:
```

> ⚠️ Warning
> It's important that you use the port `9443`, otherwise you will have security related problems and won't be able to use portainer.

Then, once you have portainer up you can open the port 9443 ([How to do it](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace)) and enter the app.
