### DISCUSSION TITLE
Maven build jobs started failing after GitHub Actions Runner upgrade to version 2.302.1

### DISCUSSION THREAD

**Discussion by nataliiamanuilova** [community/community#49096] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hi there!

We noticed an issue with recent Maven builds. The job fails when trying to run a Maven command with the next message:
```
Error:  Error executing Maven.
Error:  The specified user settings file does not exist: /home/runner/work/projectname/projectname/ .mvn/settings.xml
Error: Process completed with exit code 1.
```
The command it tries to run:
```
mvn -B package jacoco:report --file pom.xml -Daem.analyser.strict=true
```
The screenshot of what I see in build logs:
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/122607594/222771962-e8990393-6210-463f-a5e1-c274ce87dc9d.png">

We haven't changed anything in the yml file with job configuration since November, 2022, so I doubt something happened on our side.
Some things I have noticed while looking into it:
- the path is indeed incorrect - it has a space between slash and .mvn part, which is not expected;
- the last successful build job was done on version 2.301.1, previous release version of GitHub Actions runner; all Maven build jobs fail on version 2.302.1;
- while running this Maven command locally using regular terminal in the root of the project, everything is fine, no issues.

It makes me think that it might be connected to the last release, but I am not 100% sure.
Am I missing something here? Did you meet the same issue with your projects?

**Comment by jsoref** [comment]
Could you please provide the workflow you're using? At least a list of any actions (and their parameters)?

My guess is you're using [actions/setup-java](https://github.com/actions/setup-java)...

**Reply by nataliiamanuilova** [reply]
Yes, you are right, we are using actions/setup-java! I am attaching the whole yml configuration file, I hope this helps:
```
name: Maven Build on Push

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop, release/* ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package jacoco:report --file pom.xml -Daem.analyser.strict=true

    - name: Archive Jacoco reports
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-reports
        path: ${{ github.workspace }}/core/target/site/jacoco
```
