### DISCUSSION TITLE
`npm run build` doesn't push

### DISCUSSION THREAD

**Discussion by Malix-Labs** [community/community#49114] [Actions]
### Select Topic Area

Bug

### Action

```yml
name: "Continuous Integration"
run-name: "${{github.workflow}} for ${{github.sha}}"

on:
  push:
    branches:
      - feature/bundle

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v3
    - name: "Setup Node.js"
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - name: "Install NPM dependencies"
      run: npm ci
    - name: "Execute Build"
      run: npm run build
    - name: "Output Build"
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: dist/
```

### Artifact

![Artifact](https://user-images.githubusercontent.com/76160668/222841112-06d2b78a-bb15-4809-b4bf-dfdf0612d88e.png)

### Files

**There are no `/dist` directory nor its sub-files**

![Files](https://user-images.githubusercontent.com/76160668/222842036-60c19018-3740-4318-b394-22e2de55fd8d.png)

### .gitignore

![.gitignore](https://user-images.githubusercontent.com/76160668/222843970-c0995fd1-9f65-443b-9dc3-3ec737239dc2.png)

### Logs

![Logs](https://user-images.githubusercontent.com/76160668/222841508-afecfdd9-7d24-4e5f-8861-1fbf299af483.png)
