### DISCUSSION TITLE
GitHub OIDC with AWS

### DISCUSSION THREAD

**Discussion by ashishjullia96** [community/community#49130] [Actions]
### Select Topic Area

Question

### Body

Hi, 

I'm in a weird situation right now (as per my understanding of the scenario).

I've setup the github oidc on aws as idp for my organization and later I started using the following:

```yaml
     - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ vars.ROLE }}
          role-session-name: "${{ github.run_id }}-${{ github.sha }}"
          aws-region: ${{ vars.AWS_REGION }}
```

I created a role^ on aws's side and added a trust relationship for that role to:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<accoiunt-id>:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:<org-name>/<repo-1>:*"
                }
            }
        }
    ]
}
```

Now, on this repo github's oidc setup is working fine, as in -> I do not have to separately create an IAM user for the repo itself, temp credentials are given by this oidc trust setup.

My question is:
Does this setup auto enforces all the repos under an account or org to only use oidc temp creds approach or let's say I've another repo as in `repo-2` -> can I use simple IAM user level approach even when the oidc setup is configured.

Note: I've only created the oidc setup to used by specific repos and want other repos to use dedicated iam users

Is it possible? or I'm missing somethig -> The official docs does not show anything related to this.

Also, on the `repo-2`, I'm getting the following error when using:
```yaml
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
```

Error:
`Error: The security token included in the request is invalid.`
![image](https://user-images.githubusercontent.com/125162454/222868641-8af8344a-6fb2-469e-9f3f-917245ded6dd.png)
