### DISCUSSION TITLE
"use latest version" button on marketplace should show all the required parameters

### DISCUSSION THREAD

**Discussion by gautamkrishnar** [community/community#4915] [Actions]
### Current problem
Currently "use latest version" button shows the following modal for my GitHub action https://github.com/marketplace/actions/blog-post-workflow:

![Screenshot 2021-08-04 at 8 04 30 PM](https://user-images.githubusercontent.com/8397274/128200072-782213c3-5299-46e5-b99a-7e793b2bf47a.png)

This example wont work since the action requires some parameters

### Proposal
**Ideally this modal should look like the following:**

![Screenshot 2021-08-04 at 7 57 35 PM](https://user-images.githubusercontent.com/8397274/128198860-76cb2c5f-acea-417b-a5b0-d2024586e560.png)

Github should add an option that allows github action developers to customize their marketplace listing example

- Add a key named `example` in [action.yml](https://github.com/gautamkrishnar/blog-post-workflow/blob/master/action.yml) under inputs that allows the developers to customize the value shown on the marketplace listing. Example
```yaml
name: 'Blog Post Workflow'
author: 'Gautam Krishna R'
description: 'Allows you to show your latest blog posts on your github profile or project readme'

inputs:
  feed_list:
    description: "Comma separated list of RSS feed urls"
    default: ""
    required: true
    example: "https://example.com/feed/"

runs:
  using: node12
  main: dist/blog-post-workflow.js
branding:
  icon: 'activity'
  color: 'blue'
```
- All the required inputs will show up by default on the marketplace.
