### DISCUSSION TITLE
How do I tag a docker image with the release version number from a previous job

### DISCUSSION THREAD

**Discussion by simonjcarr** [community/community#49159] [Actions]
### Select Topic Area

Question

### Body

I have the following action that first runs a semantic release and then builds a docker image. At the moment the image is tagged with `master` but I want it to be tagged with the release i.e. `v1.0.8`

I assumed that `${{ github.ref_name }}` would refer to the release number that was created in the previous step rather than the branch name.

Is there a different variable I need to be using?

```yaml
name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gitflow-test-gui:${{ github.ref_name }}
      - name: Log in to the Container registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the latest Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/ioncoder/gitflow-test-gui:latest
      - name: Push the Docker image with the release tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/ioncoder/gitflow-test-gui:${{ github.ref_name}}

```

**Comment by airtower-luna** [comment]
The workflow trigger says your workflow should run only for pushes to the `master` branch:

```yaml
on:
  push:
    branches: [ master ]
```

Because of that, `github.ref_name` will only ever be `master`.

You can add a [`tags` filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore) to *also* make it run for release tags, for example:

```yaml
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
```

This would make the workflow run for pushes to `master` *and* all tags starting with a `v`. For runs triggered by tags `github.ref_name` will be the tag name. If you want it to run *only* for tags just remove the `branches` part.
