### DISCUSSION TITLE
Github Action not firing on pull_request opened

### DISCUSSION THREAD

**Discussion by MichaelPStimpson** [community/community#49257] [Actions] [answered]
I'm having trouble with an action, when I open a PR via actions/github-script@v6 my other action is NOT firing.
Here is a link to the action: https://github.com/MichaelPStimpson/actions/blob/main/.github/workflows/onPR.yml

This is what it looks like this:

```
on:
  pull_request:
    branches:
      - "*"

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        run: |
          echo "test"
```

Edit/Synchronize work as expected, it's just opened that doesn't seem to be firing. Any ideas what's going on?

**Comment by jge162** [comment]
Hello @MichaelPStimpson did you figure out the issue? The link you provided is no longer valid.

I can see a issue with your syntax already. `- "*"`.

if you want it to run on any PR use this
```yaml
on:
  pull_request:
    branches:
      - main
```

Or if you want it to run when a specific branch is pushed (you have to set the correct name of branch for trigger to run) use this

```yaml
on:
  pull_request:
    branches:
      - main
      - feature/*
      - bugfix/*
```

Lastly, are you maybe attempting to do this? Have it run on any PR no matter the branch name? use this 

```yaml
branches: ["**"]
```
