### DISCUSSION TITLE
Dependabot not giving any alerts with and without dependabot.yml

### DISCUSSION THREAD

**Discussion by OsTarek** [community/community#49290] [Enterprise]
### Select Topic Area

Question

### Body

Working through two private repositories under Github Enterprise, both with dependabot alerts enabled.
One of them isn't receiving any security alerts from dependabot, where with github code scanning actions we get quite a few of alerts.

Said repo contains two maven java projects, so there are 2 pom.xml files (and 2 pom_parent.xml), so I created a dependabot.yml file that points to both, in case the default behavior wasn't able to parse the repo as below (with xyz1 and xyz2 being the 2 subprojects each containing a pair of pom.xml and pom_parent.xml).

```
version: 2
updates:

target-branch: "feature/dev"
    
- package-ecosystem: maven
  directory: "/abc/xyz1"
  schedule:
    interval: daily
  open-pull-requests-limit: 10 
 
- package-ecosystem: maven
  directory: "/abc/xyz2"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
 
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily" 
```

Any idea what's wrong or missing?
