### DISCUSSION TITLE
Dynamic runs-on labeling does not react to multi labels

### DISCUSSION THREAD

**Discussion by RW-RuneAnkerroLiljegren** [community/community#49302] [Actions]
### Select Topic Area

Bug

### Body

I have a setup where I want to setup GitHub Environments to have certain variables action runners react to. One of these variable is telling the workflow file, which runners it should target for some jobs. Most of the runners I have are self-hosted and we want to use these runner to deploy new versions to the correct servers. So we might have test, staging and production runners. I'm using a trick to access the environment variables, so they can be used with `runs-on:` settings. I got the trick from stack overflow: https://stackoverflow.com/questions/71961921/specify-runner-to-be-used-depending-on-condition-in-a-github-actions-workflow 

Since these are self-hosted, I wanted to used two labels like `[self-hosted, test]`, to indicate that this need to run on a selfhosted runner, assigned to the test environment. Here is where I ran into a problem. If I add `self-hosted, testingrunners` to the environment variable `DEPLOYSERVER` for the test environment, and use the trick in this test workflow:

``` yaml
name: Testing local runner
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  setup:
    name: Setup runner labels for deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      deployrunner: ${{ steps.step1.outputs.deployrunner }}
    steps:
      - name: Set runs-on for deploy
        id: step1
        run: |
          echo "deployrunner=${{ vars.DEPLOYSERVER }}" >> $GITHUB_OUTPUT
        
  display:
    needs: [build, setup]
    #runs-on: [self-hosted, testingrunners]
    runs-on: ${{needs.setup.outputs.deployrunner}}
    name: Displaying labels on local runner
    environment: ${{ inputs.environment }}
    env:
      runnerLabels: ${{needs.setup.outputs.deployrunner}}
    steps:     
    - name: Set runs-on for deploy
      run: |
        echo "Hello ${{ env.runnerLabels }}"
```
then the local runner will not run, even though it can see the variables I added to the environment variable:
![Pasted image 20230306095634](https://user-images.githubusercontent.com/107049485/223101530-df89215e-9eb0-4975-8485-e06279f6ab19.png)

Through trial and error I figured out that, doing it this way will not work for multiple labels, but it will work for single labels. If I edit the Environment label to only be `testingrunners`, and rerun the flow, the local runner picks it up right away. I thought that the problem was the array classifier, so I tried encapsulating the `${{needs.setup.outputs.deployrunner}}` in that, but that just results in parser error:

![Pasted image 20230306104000](https://user-images.githubusercontent.com/107049485/223102550-cbfb3604-aacc-4625-9b44-1736805603cf.png)

Trying to add the encapsulation in the environment variable does not work either. I think the system sees it as a single label and not an array.

For now, I am using single labels as I can get away with it for now. At some point this will be a issue again for me. So my question here is: 

**Is this how the system is intended to work or is this a bug?** 

I understand that I might be stretching the functionality of the workflow file a bit, but I have not been able to figure out a better way to make `runs-on:` flexible. 

One alternative for this is reusing workflow files, but I have found that reusable flows and Environment variables is not very easy to get working, which is why currently doing it this way. But this will also mean I need to have a lot of copies of the same flows. This might also be a good thing, so you can change the flows for each systems as needed, but so can branching.
