### DISCUSSION TITLE
Even if the preceding JOB specified in `needs` is executed normally, the subsequent JOB is not executed

### DISCUSSION THREAD

**Discussion by ogiwarat** [community/community#49309] [Actions]
### Select Topic Area

Question

### Body

I created a workflow like this:

```yaml
name: control-test

on:
  workflow_dispatch:
    inputs:
      skip-step1:
        description: skip step1?
        required: true
        type: boolean
        default: false

jobs:
  step1:
    if: ${{ !inputs.skip-step1 }}
    runs-on: ubuntu-latest
    steps:
    - run: echo "exec step1"

  step2:
    if: ${{ !failure() }}
    needs: step1
    runs-on: ubuntu-latest
    steps:
    - run: echo "exec step2"

  step3:
    needs: step2
    runs-on: ubuntu-latest
    steps:
    - run: echo "exec step3"
```

If the `skip-step1` input is set to true to skip the JOB in step1, the JOB in step2 will run successfully, but the JOB in step3 will be skipped.
If the `skip-step1` input is set to false and the step1 JOB is executed, then both step2 and step3 are executed.

I don't understand why step3 JOB is skipped when I let it skip step1 JOB. is this a bug?
