### DISCUSSION TITLE
Why does my action fire on every push?

### DISCUSSION THREAD

**Discussion by Kyu** [community/community#49328] [Actions] [answered]
### Select Topic Area

Product Help

### Body

I am trying to have a github action fire only when a push to main is tagged. However, every single commit triggers this action. What am I doing wrong here?  

 ```yml
# https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
# https://stackoverflow.com/a/61892639/3875151
name: Fly Deploy
on:
  push:
    branches:
      - main
    # Pattern matched against refs/tags
    tags:
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

**Comment by spenserblack** [comment, marked as answer]
This workflow runs when you push to `main` *or* any tag is pushed. To run the workflow only on tags/releases, I'd recommend just using
```yaml
on:
  push:
    tags: [ 'v*' ]

jobs:
  # ...
```

The downside to this is that the workflow will run on *any* tag matching this pattern, even if the tagged commit is not discoverable in `main`. However, I haven't seen this to be a problem in practice, since only those with push access to your repository can even push tags. If you're really concerned about tags getting pushed to the wrong branch, you could add a step or job to checkout `main` and check if the tagged commit exists in that branch.
