### DISCUSSION TITLE
Upload artifact issue

### DISCUSSION THREAD

**Discussion by hpfs74** [community/community#49337] [Actions]
### Select Topic Area

Question

### Body

I've got an action that builds a node application and publish artifacts it is few files and a node_modules folder
it takes ages and it is getting charged as compute time.
![image](https://user-images.githubusercontent.com/5243150/223176921-a4268853-2d8c-461b-a5e3-15c0f41cc720.png)
any idea?

**Comment by rauzerfabiano** [comment]
One potential solution could be to cache the node_modules folder between builds. This would save time and reduce compute costs as the dependencies would not need to be reinstalled each time the action runs.

You can use the actions/cache action to cache the node_modules directory. Here's an example workflow:

```
name: Node CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish Artifacts
        run: |
          npm run build
          # Publish artifacts
          # ...

```
In this example, the actions/cache action caches the ~/.npm directory (where node_modules is installed) based on the contents of package-lock.json. The cache is restored on subsequent runs, allowing the dependencies to be reused.

Additionally, you can optimize the build process by only running the build step if there have been changes to the code. You can use the actions/changed-files action to check for changes, like this:

```
- name: Check for changes
  uses: peter-evans/changed-files@v1
  id: changes
  with:
    files: |
      *.js
      *.ts

- name: Build and Publish Artifacts
  if: steps.changes.outputs.files != ''
  run: |
    npm run build
    # Publish artifacts
    # ...
```

This action checks for changes in .js and .ts files and sets an output files variable. The build step is only run if this variable is not empty, indicating that there have been changes.
