### DISCUSSION TITLE
Actions: Use actions from private and internal repositories

### DISCUSSION THREAD

**Discussion by Freyert** [community/community#4934] [Actions]
It's extremely inconvenient to have to develop actions for your company in a public repository. Quite a lot of security penetration research could be performed just by reviewing the actions an organization is building or reviewing issues/discussions on the action repository.

There's even a section in the documentation discussing how _careful_ one should be when using actions due to the potential for code injection.

This feature would be highly appreciated: https://github.com/github/roadmap/issues/74

Prior Art:
https://github.com/nick-invision/private-action-loader (@nick-invision, looks like your company pushed ownership of `private-action-loader` out of their responsibility for security concerns?)

**Update:** looks like https://github.com/github/roadmap/issues/74 has been moved into the Q4 roadmap :) 🤞 it happens.

**Comment by rajbos** [comment]
You can checkout a private repo with v2 of the checkout action and then load the action from that folder by using a PAT that has access. See source [here](https://stackoverflow.com/questions/64391445/using-a-secret-private-action)

```
- name: Get private repo with action
  uses: actions/checkout@v2
  with:
    repository: yourorg/privateactionrepo
    ref: master
    token: ${{ secrets.PAT_TOKEN }}
    path: .github/actions

uses: ./.github/actions/actionname
```
