### DISCUSSION TITLE
A step in an action fails running a git command in a seemingly ephemeral basis

### DISCUSSION THREAD

**Discussion by VJalili** [community/community#49458] [Actions]
### Select Topic Area

Question

### Body

I have an action that runs in multiple steps, where each step invokes a script that operates on the difference between two commit SHAs (the current HEAD of the `main` branch and HEAD of the feature branch that triggered the action execution) and updates a git-tracked file with the outputs of the script. The modified git-tracked file is then committed in the last step of the action and pushed back to the `main` branch, but I am excluding this step from the following example for brevity.

The steps of this action run successfully most of the time, but some steps sometimes fail on a seemingly ephemeral basis. When it fails, a re-run of the action or pushing a new commit (the commit can contain an update to a comment) can result in its successful execution. 

The following is a simplified version of the action. 

```yaml
jobs:
  publish_job:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Step 1
        run: |
          python script.py sha_x sha_y input_a
          # sha_x and sha_y are fixed between all the steps, but the last argument changes.
          # The script modifies a git-tracked file.
      - name: Step 2
        run: |
          python script.py sha_x sha_y input_b
```

This action fails in `Step 2` when the `script.py` runs the following command. 

```python
git rev-parse --short HEAD
```

It fails on an ephemeral basis, but if it fails, it consistently fails at `Step 2` when the script runs the above command. 

Note that `Step 1` and `Step 2` run the same script but with different inputs. Hence, the above `git` command always runs successfully in `Step 1` but fails in `Step 2`. `Step 1` modifies a git-tracked file, but it does not seem `git rev-parse --short HEAD` can fail if the git repository contains un-committed files.
