### DISCUSSION TITLE
How do I check if the logged in user is part of a team

### DISCUSSION THREAD

**Discussion by ppmgitrepo** [community/community#49530] [Actions] [answered]
### Select Topic Area

Question

### Body

0

In a GitActions YAML file how do I check to see if a User is part of a Team in Github ?

I know that the username can be got via  `${{ github.actor }}`

Note: The requirement is to allow only specific authorized users to be able to run a job within a workflow. (Say we restrict a step to the DBA team members)

Note: I am aware of Environments and the "Require reviewer" option. But this does not quite fit into the requirement.

**Comment by ppmgitrepo** [comment, marked as answer]
The following works 

````
jobs:
  check-user:
    name: Team affiliation
    runs-on: my-runner1
    steps:
      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          username: ${{ inputs.USER_NAME }}
          team: ${{ inputs.TEAM_NAME }}

      - name: Stop workflow if user is no member
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'false' }}
        run: |
          echo "You have no rights to trigger this job."
          #exit 1
````
Hence closing this thread
