### DISCUSSION TITLE
How can I avoid specifying the environment statically inside a reusable workflow?

### DISCUSSION THREAD

**Discussion by athorsen-livefront** [community/community#49555] [Actions]
### Select Topic Area

Question

### Body

I'd like to pass the environment to use to the reusable workflow rather than specifying it statically inside the reusable workflow.  Is this possible?

For ex. this *does not work* because secrets is not defined under job-id (although it is under env).

```
jobs:
  build:
    runs-on: ubuntu-latest
    needs: tests
    environment: ${{ secrets.GITHUB_ENV }}
    env:
      BACKEND_POOL_UPDATER_IMAGE_NAME: ${{ secrets.BACKEND_POOL_UPDATER_IMAGE_NAME }}
      COMPANY_IMAGE_NAME: ${{ secrets.COMPANY_IMAGE_NAME }}
      LIVEFRONT_CI_GITHUB_TOKEN: ${{ secrets.COMPANY_CI_GITHUB_TOKEN }}
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
```
