### DISCUSSION TITLE
How to get base_ref/head_ref on event issue_comment triggered from a pull request ?

### DISCUSSION THREAD

**Discussion by LPauzies** [community/community#49628] [Actions]
### Select Topic Area

Question

### Body

Hello,
I'm currently trying to trigger a workflow when a comment is written in a Pull Request. However, I'm not able to get the base_ref/head_ref to checkout on the branch I want (In my case, I need to get head_ref). 

According to the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_comment-use-issue_comment), we should use issue_comment, but previously it was existing a pull_request_comment that seems to be not handled anymore.

So what is the workaround to get head_ref branch when triggering a workflow from a comment done in a Pull Request ?

Here is a piece of code to demonstrate this : 
```YAML
name: A pipeline

on:
  issue_comment:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build')
    steps:
      - uses: actions/checkout@v3
        name: Checkout the given branch
        with:
          ref: ${{ github.ref }} # Should be head_ref and not "master" or default branch
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```
