### DISCUSSION TITLE
Help

### DISCUSSION THREAD

**Discussion by mpvaldez** [community/community#49637] [Actions]
### Select Topic Area

Question

### Body

I need help. I have the following workflow to run when I generate a new release. 

```
# version 1.0
name: CI/CD - Upgrade Chart and Deploy 
on:
  release:
    types: [created]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: ######

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get repository name
        id: repo_name
        run: echo "::set-output name=name::$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)"

      - name: Upgrade Helm chart
        run: |
          RELEASE_NAME="${{ steps.repo_name.outputs.name }}"
          helm upgrade --install $RELEASE_NAME ./.chart/ \
            --set appVersion=${{ github.ref_name }},version=${{ github.event.release.name }}          
```

The problem is that the action is not triggered either when I create or when I publish a new release.
