### DISCUSSION TITLE
Run a php instructions in my github action

### DISCUSSION THREAD

**Discussion by Asmitta-01** [community/community#49681] [Actions]
### Select Topic Area

Question

### Body

I have my .htaccess file which contains many lines with the term "/wordpress" inside, it is helpful on my pc (local) now but problematic while in production and i need each time (after a `git pull` on the online server)  to manually replace all the occurences of this expression by an empty string ("") to avoid problems.
I have seen git actions and i created this hoping it would resolve my problem:
```yml
# This is a basic workflow that is manually triggered

name: Mise a jour du .htaccess

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  replace:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Retirer "wordpress" du htaccess (ca devient invalide une fois en ligne)
      run: |
        $str = file_get_contents('.htaccess');
        $str = str_replace('/wordpress', '', $str);
        file_put_contents('.htaccess', $str);
      shell: php {0}
      # working-directory: './'
```
But it is not working.
How can i run these php instructions please ?
