### DISCUSSION TITLE
How to get a list of all environments in a workflow?

### DISCUSSION THREAD

**Discussion by rhuanbarreto** [community/community#49684] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a workflow that loops over the current environments setup in the repo:

```yaml
name: PR
on:
  pull_request:
    branches:
      - main
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - dev
          - test
          - prod1
          - prod2
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install Packages
        run: npm ci
```

How can I reference all environments into the matrix without having to write them one by one in the array?

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by mhemmings** [comment, marked as answer]
I totally agree this should be possible!

We've had success with the following workaround, which gets all the environments prefixed with the current branch name. You can tweak the `jq` query to your needs, for example to just return all environments:

```yaml
  # Get all the environments that start with the branch name: "[branch-name] Environment Name"
  get-environments:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions:
      actions: read
    outputs:
      names: ${{ steps.set_env.outputs.names }}
    steps:
      - name: Get environments
        uses: octokit/request-action@v2.3.0
        id: get_env
        with:
          route: GET /repos/${{ github.repository }}/environments?per_page=100 # If we ever have >100 deployments, we'll need to paginate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set output
        id: set_env
        run: echo "names=$(echo $NAMES | jq -c '[.[] | select(startswith("[${{ github.ref_name }}]"))]' -j)" >> $GITHUB_OUTPUT
        env:
          NAMES: ${{ toJson(fromJson(steps.get_env.outputs.data).environments.*.name) }}
```

Then the output can be used as follows:

```yaml
  deploy:
    needs:
      - get-environments
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-environments.outputs.names) }}
    environment:
      name: ${{ matrix.environment }}
```

**Reply by jonnitto** [reply]
Great! Thank you for this snipped. Do you also have a solution for more than 100 environments? `octokit/request-action` seems not to support this.

**Reply by mhemmings** [reply]
I'm guessing you would probably manually have to call the Github API and loop through the pagination

**Reply by jonnitto** [reply]
I created a action for this:
https://github.com/marketplace/actions/get-environments

Example:

```yaml
jobs:
  get-environments:
    name: Get environments
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      actions: read
    outputs:
      names: ${{ steps.get_envs.outputs.environments }}
    steps:
      - name: Call GitHub API
        uses: jonnitto/get-environments@1.0.0
        id: get_envs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy ${{ matrix.environment }}
    needs: get-environments
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.get-environments.outputs.names) }}
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
```
