### DISCUSSION TITLE
Vars context not accessible in composite action

### DISCUSSION THREAD

**Discussion by SoaAlex** [community/community#49689] [Actions]
### Select Topic Area

Question

### Body

Hello,

I have a job calling a composite action made by myself
```yaml
  build-docker:
    runs-on: [self-hosted, Linux, standard]
    environment:
      name: staging
    steps:
      - name: 🏗️📤 Build Docker Image
        uses: XX/XX/workflows/.github/actions/build/docker@main
```

The composite action cannot access the `vars` context that should be provided by setting an environment in the job.
Is this expected ?
The following action will make the workflow fail:
```yaml
  - name: 🐋⬆️ Push Docker images
    if: ${{ vars.push == 'true' }}
    shell: bash
    run: |
      docker push XXXXX
```

**Comment by jge162** [comment]
If you want to use a variable in a composite action, you need to pass it as an input parameter.

**Comment by o-alexandrov** [comment]
`vars` context is **not meant for secret values**.
It is a UX bug, isn't it?

Please expose `vars` context for shareable actions, including `composite`, as it would help both: actions authors and users.
Related GitHub Issue https://github.com/actions/runner/issues/2551

**Comment by htekdev** [comment]
I had to do the following:

```yaml
...
inputs:
  vars-as-json:
    description: 'Vars as JSON. Recommended to be ${{ toJSON(vars) }}'
    required: true
...
```

```yaml
uses: action@v1
with:
   vars-as-json: ${{ toJson(vars) }}
   ...
```

It sucks since now I have this `required` parameter that is expected to be the same no matter what. Makes no sense.
