### DISCUSSION TITLE
Running workflows on dispatch should have their own permission

### DISCUSSION THREAD

**Discussion by franpb90** [community/community#49688] [Actions]
### Select Topic Area

Product Feedback

### Body

From my understanding to trigger a workflow_dispatch you need to have write permissions on the repository.

We are facing the following situation. We have an internal repository in an organization where all organization members have read access. We want to give them access just to trigger the workflow on a specific branch. We do not want that they can modify the workflows and be able to expose the secrets, take advantage of the privileges configured in the repo, or skip any workflow validation.

In my opinion, running workflows permission should have it's own permission, instead of using the repository write permission. I think it will help to have this permission separated from write permissions, similar like in file permissions we have read, write, and **execute**

Related discussion:
[Who has permission to workflow_dispatch](https://github.com/community/community/discussions/26622)

**Comment by ecs-jnguyen** [comment]
Additionally, branch protection is not good enough. If you grant me write access to a repo, I can create my own branch modify the workflow file then run the workflow using my branch.

**Comment by NullVoxPopuli** [comment]
I'm running in to this issue as well.
I'm trying to sanely (as in, not what's in GitHub's blog) dispatch a trusted workflow from an untrusted one -- example: PR fork submits a PR -- I want to still give that PR a deploy preview -- and the deploy-preview workflow has secrets -- but those secrets are not available to forks.

**Comment by gusmith-ambiata** [comment]
@franpb90  and @ecs-jnguyen 
In the branch protection, there is the following option: 
![image](https://user-images.githubusercontent.com/118949617/230284029-6d448e0c-7e99-43c1-9be6-3e96355b5fb9.png)
I'm trying to turn my head around if this would solve the issue:

1.  create a team `REPO_WRITERS` for users who will be able to write in the repo giving this team a `write` role
2. create a team `GITHUB_ACTION_MANUAL_RUNNERS` for users who will have write permissions on the repo BUT should not be allowed to write anywhere (cf following), give this team `write` role
3. create a branch protection rule where the branch selection is `*` (i.e. all branches) where only the `REPO_WRITERS` team is allowed 
![image](https://user-images.githubusercontent.com/118949617/230284944-5878f99a-a6f2-4604-8072-ddc70fc0b502.png)

Should that work? I have not tested it yet.

I was otherwise looking at the [CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)  but it seems you can still update the file in your feature branch, you just cannot merge it without a code owner review, and thus do not solve the original problem.

However, I cannot think of a way to provide write access to the whole repo BUT the github workflow folder, blocking pushes even if on feature branches...

**Reply by gusmith-ambiata** [reply]
It is actually not working for a weird reason: with this branch protection, you can still create branch with a commit. The branch WILL be protected after that, but not on the first push. Odd no?

**Comment by gusmith-ambiata** [comment]
A colleague mentioned a great idea: triggering a workflow through issues.
People with READ role can create issue. You then parse the content/title of the issue triggering the workflow.

Probably not the perfect solution, but it should solve the issue of triggering a workflow for READ only users that @franpb90 mentioned.

**Reply by franpb90** [reply]
It is a good idea. We have started to use this workaround, but we have not tested it at scale yet.

**Reply by dcopso** [reply]
I've been using this approach for over a year and it works fine.

Here's the skeleton of the action on the repository with privileges:
```yaml
# example workflow to be triggered by the opening of an issue, running a privileged task, and notifying slack of
# the results.
on:
  issues:
    types:
      - opened

permissions:
  issues: write  # Allow the workflow to update the opened tickets.

env:
  LOG_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  sync:
    if: |
      !github.event.issue.pull_request
        && startsWith(github.event.issue.title, 'INVOKE-MAGIC-STRING')
        && (github.actor == 'github-machine-user-for-your-automations')
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - run: |
          gh api "${ISSUE_REACTIONS_URL}" -f content=rocket
        env:
          GH_REPO: ${{ github.event.repository.full_name }}  # Tell gh CLI which repo to use.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provide auth token to gh CLI for this repository.
          ISSUE_REACTIONS_URL: ${{ github.event.issue.reactions.url }}
      - run: |
          # run the task you want to trigger here.
          curl -H "Authorization: Bearer $WHATEVER_SECRET" ...
        env:
          WHATEVER_SECRET: ${{ secrets.WHATEVER }}
      - if: success()
        uses: your-preferred/slackbot-notifier@main
        with:
          webhook_url: ${{ vars.SLACK_WEBHOOK_URL }}
          message: "Privileged task has completed. Log: ${{ env.LOG_URL }}"
      - if: failure()
        run: |
          gh issue comment "${ISSUE_NUMBER}" -b "Failure: ${LOG_URL}"
        env:
          GH_REPO: ${{ github.event.repository.full_name }}  # Tell gh CLI which repo to use.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provide auth token to gh CLI for this repository.
          ISSUE_NUMBER: ${{ github.event.issue.number }}
      - if: failure()
        uses: your-preferred/slackbot-notifier@main
        with:
          webhook_url: ${{ vars.SLACK_WEBHOOK_URL }}
          message: "Privileged task has failed. Log: ${{ env.LOG_URL }}"
```

To invoke it, the other repository can open an issue in the privileged repository:
```yaml
# creates an issue in the TARGET_REPO repository
on:
  workflow_dispatch:

env:
  # consumed by gh cli. The GitHub username of the user that creates this token should be dropped into
  # the above YAML file to replace 'github-machine-user-for-your-automations'.
  GH_TOKEN: ${{ secrets.TOKEN_WITH_READ_ACCESS_ON_PRIVILEGED_REPOSITORY }}
  TARGET_REPO: "my-organization/your-privileged-repo"

jobs:
  call:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - run: |
          gh issue create \
            -t "INVOKE-MAGIC-STRING" \
            -R "${TARGET_REPO}" \
            --body "Created by: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
```
