### DISCUSSION TITLE
docker - exec: "tail": executable file not found in $PATH: unknown

### DISCUSSION THREAD

**Discussion by D3vil0p3r** [community/community#49703] [Actions]
### Select Topic Area

Bug

### Body

**Describe the bug**
I created a github action for publishing periodically a docker image. The yml file is the following:
```yaml
name: Scheduled Publish

on:
  schedule:
    - cron: '22 4 * * 0'
  workflow_dispatch:

env:
  BASE_DEVEL_IMG: base-devel
  BASE_IMG: base

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  publish:
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pacman -Sy --noconfirm --needed make docker devtools fakeroot fakechroot

      - name: Build base
        run: |
          make image-base
          docker tag athenaos/base docker.io/athenaos/$BASE_IMG

      - name: Build base-devel
        run: |
          make image-base-devel
          docker tag athenaos/base-devel docker.io/athenaos/$BASE_DEVEL_IMG

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: |
          docker push docker.io/athenaos/$BASE_IMG
          docker push docker.io/athenaos/$BASE_DEVEL_IMG
```
When the GitHub action is run, I get the following error in the "Starting job container" phase:
```
  /usr/bin/docker pull ***/base-devel
  Using default tag: latest
  latest: Pulling from ***/base-devel
  ca087eaeb39b: Pulling fs layer
  ca087eaeb39b: Verifying Checksum
  ca087eaeb39b: Download complete
  ca087eaeb39b: Pull complete
  Digest: sha256:ee6aa3744d603a523687b733ba179778ec85a64c76ec53b185c1ff976d2a198e
  Status: Downloaded newer image for ***/base-devel:latest
  docker.io/***/base-devel:latest
  /usr/bin/docker create --name 9c57b1005c49450aa609b9fc808bcafb_***basedevel_0d58a0 --label a5c76b --workdir /__w/athena-base-docker/athena-base-docker --network github_network_329b6f4b3e604ae19f2e5c53d97901e1  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.302.1/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" ***/base-devel "-f" "/dev/null"
  05b3c2aca44f3b06cf9838f0414e907c6779ecf9165a2e39e0758ce2a86aad29
  /usr/bin/docker start 05b3c2aca44f3b06cf9838f0414e907c6779ecf9165a2e39e0758ce2a86aad29
  Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "tail": executable file not found in $PATH: unknown
  Error: failed to start containers: 05b3c2aca44f3b06cf9838f0414e907c6779ecf9165a2e39e0758ce2a86aad29
  Error: Docker start fail with exit code 1
```
`athenaos/base-devel`, specified in the `container` field in the `yml` file, has the `tail` command so I don't know why GitHub runner cannot find it.

Furthermore, I noted that when I publish manually the athenaos/base-devel container to Docker Hub a first time, and then I run this GitHub action, it works correctly, then if I run it again, it produces the error above.

The container is an Arch Linux based distro: https://github.com/Athena-OS/athena-base-docker

UPDATE: I just run again the failed job and now it worked and didn't produce the error. Why do I get this strange behavior?

How can I fix it?
