### DISCUSSION TITLE
Auto-merge for PRs to a branch whether it's protected or not, once tests succeed

### DISCUSSION THREAD

**Discussion by jvacek** [community/community#49730] [Enterprise]
### Select Topic Area

Question

### Body

We've got tests that easily run for 20 minutes.

We don't necessarily want to require a review or that all tests must pass in order to merge a PR, this is on a GitHub Enterprise private repo.

I want to have a PR merge _if the tests succeed_. If the tests don't pass, I don't want it to merge _even if we don't require them to pass_.

**Comment by Anmol-Baranwal** [comment]
To achieve your desired workflow, you can set up a GitHub Action that runs your tests whenever a pull request is opened or updated. If the tests pass, the action can automatically approve and merge the pull request.

Here's an example of what the GitHub Action workflow file might look like:

```yaml
name: Run tests and merge on success

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./run-tests.sh
      - name: Merge on success
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated merge of PR
          delete-branch: true
```

In this workflow, the on section specifies that the action should be triggered whenever a pull request is opened or updated on the main branch.

The build-and-merge job runs on an Ubuntu environment and consists of three steps:

1. The actions/checkout action checks out the source code for the pull request.

2. The run-tests.sh script is executed to run your tests.

3. If the tests pass (success()), the peter-evans/create-pull-request action is used to approve and merge the pull request. This action requires a GitHub access token, which can be provided via the secrets.GITHUB_TOKEN secret.
Note that in this workflow, the delete-branch option is set to true, which will delete the branch after the pull request is merged. If you don't want to delete the branch, you can set this option to false.

With this workflow in place, pull requests will be automatically merged if the tests pass, and will not be merged if the tests fail. This allows you to maintain a balance between speed of development and code quality, without compromising on the integrity of your codebase.
