### DISCUSSION TITLE
Creating a pull-request to another repos

### DISCUSSION THREAD

**Discussion by thecodejunkie** [community/community#49745] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi

I have two repos (A and B) where an update to some files in A should create a pull-request to B with some changes. I'm running a small bash script, in a workflow for repository A, that does

1. Clone B using a PAT 
2. Cd into the cloned directory
3. Create a new feature branch
4. Make the changes
5. Commit the changes
6. Push the feature branch to B

At this point, I can see that the branch exists in repository B. Next, I try to create a pull-request in repository B using

```sh
gh pr create --title "some title" --body "some body" --head "branch-name" --base main
```

but it tells me I need to push the branch first

I'm running the script using

```yml
- name: create pull-request
  run: $(scripts/thescript.sh)
  env:
     GH_TOKEN: {{ secrets.ACCESS_TOKEN }}
```

Any suggestions on how to do this? My script will eventually send pull-requests to multiple repositories, so using one of the "send pull-requests" actions on the marketplace is not an option.

Thanks!

**Comment by jge162** [comment]
Hello @thecodejunkie using your notes for this use case; try this.

- clone repo B using a PAT
`git clone https://github.com/user/repo-b.git`
`cd repo-b`

- create a new feature branch
`git checkout -b feature-branch`

- make the changes
...

- commit the changes
`git add .`
`git commit -m "Commit message"`

- push the feature branch to repo B
`git push origin feature-branch`
- now repo B and will be available for creating a pull request! 
- this is the part I believe you are missing.

- create a pull request in repo B
`gh pr create --title "some title" --body "some body" --head "feature-branch" --base main`

**Comment by thecodejunkie** [comment]
@jge162 Thank you for your reply!

I've read your reply a couple of times now, and I must confess that I fail to see how that is any different from what I described? 😄 

> this is the part I believe you are missing.

Are you referring to the part where the feature branch is pushed to B? In my quesiton I wrote

> Push the feature branch to B
> At this point, I can see that the branch exists in repository B.

I just wanted to clarify that I meant that I can see the branch in the origin of B, so it has been pushed and the branch does exist on the original repo at this point in time

Thank you for additional clarification!

**Reply by jge162** [reply]
I gotchu, you can see the branch. In that case then, seems like the issue might be with the `gh pr create` command not recognizing the existence of the branch on the remote repository.

I’m looking at CLI documentation now. But that’s my guess at least.

**Comment by thecodejunkie** [comment]
Yeah, I'm a but unsure if the `gh` instance is scoped to the "local" repo so that it can't see it? Of if I need to provide a fully qualified name for --head and --base?

**Reply by jge162** [reply]
I was going to suggest specifying `- - head`

**Reply by jge162** [reply]
Try checking the branches existence with 

`gh pr list`

**Reply by jge162** [reply]
I’m just using this as my guide. I’m sure you know all of this by now. But here it is anyways. [documentation](https://cli.github.com/manual/gh_pr_create)

**Comment by thecodejunkie** [comment, marked as answer]
I figured it out and to help anyone that runs into the same issues I will share my complete solution. This essentially send a pull-request to another repository and updates the files in the `/scripts` folder to the latest version from the repository where the workflow was triggered. 

The trick was to re-authenticate the GitHub CLI inside of the clone of the remote repository. This requires that you have a Personal Access Token (PAT) defined (I didn't bother looking at the minimum permissions yet, but probably  `repo` and `read:org`) as a secret called `ACCESS_TOKEN`


```yml
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

name: on-commit-to-main

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send pull-request
        run: |
          LATEST_TAG=$(git describe --tags --always --abbrev=0)
          REPOSITORY="some-user/some-repository"
          FOLDER="bin/$REPOSITORY"
          BRANCH_NAME="chore-update-scripts-to-$LATEST_TAG"

          # Clone the remote repository and change working directory to the
          # folder it was cloned to.
          git clone \
            --depth=1 \
            --branch=main \
            https://some-user:${{ secrets.ACCESS_TOKEN }}@github.com/$REPOSITORY \
            $FOLDER

          cd $FOLDER

          # Setup the committers identity.
          git config user.email "some-user@some-domain.com"
          git config user.name "Some User"

          # Create a new feature branch for the changes.
          git checkout -b $BRANCH_NAME

          # Update the script files to the latest version.
          cp -R ../../../scripts scripts

          # Commit the changes and push the feature branch to origin
          git add .
          git commit -m "chore: update scripts to $LATEST_TAG"
          git push origin $BRANCH_NAME

          # Store the PAT in a file that can be accessed by the
          # GitHub CLI.
          echo "${{ secrets.ACCESS_TOKEN }}" > token.txt

          # Authorize GitHub CLI for the current repository and
          # create a pull-requests containing the updates.
          gh auth login --with-token < token.txt
          gh pr create \
            --body "" \
            --title "chore: update scripts to $LATEST_TAG" \
            --head "$BRANCH_NAME" \
            --base "main"

```
