### DISCUSSION TITLE
I want to run a dependent workflow only when the previous workflow is trigger by a release event

### DISCUSSION THREAD

**Discussion by participator** [community/community#49742] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a job that builds an image when a release is published or when manually triggered.  When it completes, a deploy job runs.

I only want the deploy job to run, when the build job is triggered by a release.  The [workflow_run documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) shows that the branch can be specified.  How can I specify the deploy workflow to run only when the build workflow was triggered by a release event?  I do not want to create a duplicate build job that only has the `workflow_dispatch` trigger.

**Step 1**
```
name: build
on:
  release:
    types: [ published ]
  workflow_dispatch:
```

**Step 2**
```
name: deploy
on:
  workflow_run:
     workflows: [ build ]
     types:
        - completed
```

Note: A solution is included at the end of the thread that combines both workflows into one.  I have not discovered a way to make this work with two separate workflows.  If you do, please add that solution to this thread as that was the original question.

**Comment by jge162** [comment, marked as answer]
you could use types

[documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows)

```yaml
name: deploy
on:
  workflow_run:
    workflows: [build]
    types:
      - completed
```

**Reply by jge162** [reply]
I have also designed a create-release action in GitHub market place that if the pr title has specific words it will trigger a release. You could look at how i did maybe that helps too. 

Link to [GitHub marketplace](https://github.com/marketplace/actions/create-release-on-close)

**Reply by participator** [reply]
I have updated my question as an attempt to clarify it.

**Original**
How can I specify a release?

**New**
How can I specify the deploy workflow to run only when the build workflow was triggered by a release event?

**Reply by jge162** [reply]
here you go, I tested it and works fine. Lmk if you need it tweaked.

```yaml
name: Release Deploy Workflow

on:
  # <- Trigger the build workflow when a new release is created ->
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # <- Only run the deploy job if the build was triggered by a release event ->
    if: github.event_name == 'release'
    steps:
      # Checkout the source code for deployment
      - name: Checkout code
        uses: jge162/Action-workflows@1.1.1
      # <- Run a deployment script to deploy the code ->
      - name: Deploy code
        run: |
          # <- Replace this with your own deployment script ->
          # and go from there...
          echo "Deploying code..."
```

**Reply by participator** [reply]
Okay, the if statement is the key.  Thanks!

**Reply by jge162** [reply]
anything else let me know, have a great weekend.

**Reply by participator** [reply]
Yeah, one thing.  The deploy workflow uses the trigger `workflow_run`, not `release`.   Will `github.event_name` be 'release' on the deploy workflow?

**Reply by jge162** [reply]
No, `github.event_name` will not be set to `'release'` in the deploy workflow if the deploy workflow is triggered by a `workflow_run` event, you cannot use `github.event_name` to check if the `workflow_run` event was triggered by a release event. 

Here is modified example you can use. It’s pseudo code though. I have not tested this version. 

```yaml
name: Release Deploy Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # <- Build the code ->
      - name: Build code
        run: |
          # <- Replace this with your build script ->
          echo "Building code..."
      # <- Set an output variable with the release information ->
      - name: Set output variable
        id: set-output
        run: echo "::set-output name=release-info::1.0.0"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # <- Pass the release information as an input to the deploy job ->
    inputs:
      release-info: ${{ needs.build.outputs.release-info }}
    steps:
      # <- Checkout the source code for deployment ->
      - name: Checkout code
        uses: jge162/Action-workflows@1.1.1
      # <- Run a deployment script to deploy the code, using the release information from the input ->
      - name: Deploy code
        run: |
          # Replace this with your deployment script        
 that uses the release information 
          release_info=${{ inputs.release-info }}
          echo "Deploying code for release 
 $release_info..."
```

**Reply by participator** [reply]
Thanks, your examples are helpful.  To make this work, it seems like your are suggesting that I combine my two workflows into one workflow.  This workflow will have two jobs: one for build and one for release.  The build job can run anytime the workflow is triggered (release or workflow_dispatch).  The release job will only run when the workflow was trigger with a release (`if ${{ github_event_name == 'release' }}`).

**Reply by jge162** [reply]
No problem. Hope it works for you.

**Reply by participator** [reply]
Would you write a new answer, so that I can mark it as the answer?

**Reply by jge162** [reply]
> Thanks, your examples are helpful. To make this work, it seems like your are suggesting that I combine my two workflows into one workflow. This workflow will have two jobs: one for build and one for release. The build job can run anytime the workflow is triggered (release or workflow_dispatch). The release job will only run when the workflow was trigger with a release (`if ${{ github_event_name == 'release' }}`).

Yes 

```yaml
name: Release Deploy Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # <- Build the code ->
      - name: Build code
        run: |
          # <- Replace this with your build script ->
          echo "Building code..."
      # <- Set an output variable with the release information ->
      - name: Set output variable
        id: set-output
        run: echo "::set-output name=release-info::1.0.0"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # <- Pass the release information as an input to the deploy job ->
    inputs:
      release-info: ${{ needs.build.outputs.release-info }}
    steps:
      # <- Checkout the source code for deployment ->
      - name: Checkout code
        uses: jge162/Action-workflows@1.1.1
      # <- Run a deployment script to deploy the code, using the release information from the input ->
      - name: Deploy code
        run: |
          # Replace this with your deployment script        
 that uses the release information 
          release_info=${{ inputs.release-info }}
          echo "Deploying code for release 
 $release_info..."
```
