### DISCUSSION TITLE
Action to test Ansible playbook run on Debian OS ? (with kernel modules installation & root access)

### DISCUSSION THREAD

**Discussion by tigerblue77** [community/community#49845] [Actions]
### Select Topic Area

Question

### Body

Hello,

I have a private Ansible project which deploys a lot of things (APT packages, kernel modules, docker containers, etc...) on a fresh Debian install. I use it to deploy and maintain my homelab bare-metal server. Until now, I was testing from my PC to a Debian VM but I would like to do the switch to GitHub CI and test on each push. Here is the CI I wrote so far :
```yaml
name: Test Ansible script on Ubuntu
on: [push]

jobs:
  Run_Ansible_playbook:
    # needs: [Install_Ansible_package]
    runs-on: ubuntu-latest
    steps:
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Create Dockerfile
        run: |
          echo "FROM debian:bullseye
          RUN echo 'root:PASSWORD' | chpasswd
          RUN useradd -m tigerblue77 && echo 'tigerblue77:PASSWORD' | chpasswd
          RUN apt-get update
          RUN apt-get -y full-upgrade
          RUN apt-get install -y openssh-server python3 libssl-dev libc6
          RUN mkdir /var/run/sshd
          RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          RUN sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd
          EXPOSE 22
          CMD [\"/usr/sbin/sshd\", \"-D\"]" > Dockerfile

      - name: Build Docker image
        run: docker build -t debian_server_with_ssh .

      - name: Run Debian Docker container
        run: >
          docker run -d
          --name Debian_container_to_deploy_with_Ansible
          --privileged
          --cap-add ALL
          --volume /sbin/modprobe:/sbin/modprobe:ro
          --expose 20
          debian_server_with_ssh
        # docker run -d
        # --name Debian_container_to_deploy_with_Ansible
        # --privileged
        # --cap-add ALL
        # --volume /sbin/modprobe:/sbin/modprobe:ro
        # --expose 20
        # debian_server_with_ssh

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub CI inventory
        run: |
          echo "all:
            children:
              Linux_servers:
                children:
                  Virtual_servers:
                    hosts:
                      throwable_Ultron:" > inventory.yaml

      - name: Setup Debian Docker server Ansible host_vars file
        run: |
          Debian_Docker_container_IP_address=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' Debian_container_to_deploy_with_Ansible)
          echo "ansible_host: $Debian_Docker_container_IP_address" > host_vars/throwable_Ultron.yaml

      # - name: Replace host to deploy in playbook.yaml
      #   run: |
      #     Debian_Docker_container_IP_address=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' Debian_container_to_deploy_with_Ansible)
      #     sed -i 's/Pepper_Potts/$Debian_Docker_container_IP_address/g' playbook.yaml

      - name: Replace host to deploy in playbook.yaml
        run: sed -i 's/Pepper_Potts/throwable_Ultron/g' playbook.yaml

      - name: Run Ansible playbook
        run: ansible-playbook --forks $(nproc) -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"' --inventory inventory.yaml playbook.yaml

      - name: Show logs
        run: docker logs Debian_container_to_deploy_with_Ansible
```
As you can see, I'm deploying a basic Debian Docker container with some libraries then I run the playbook on this machine. The problems I encounter are the following :
- I don't manage to deploy kernel modules I need inside the Docker container, I get the following error : `The error was: FileNotFoundError: [Errno 2] No such file or directory: '/lib/modules/5.15.0-1034-azure/modules.builtin'`
- I need `sudo` or `root` access to install all those things so I can't deploy directly to the CI environment (or at least I didn't find how to elevate as root ?)

My new (and last) idea would be to deploy a KVM VM inside the environment but I didn't find any documentation mentionning that it's possible ?
