### DISCUSSION TITLE
How to specify job's name using the `matrix` strategy to display in cancellation messages?

### DISCUSSION THREAD

**Discussion by yeputons** [community/community#49880] [Actions]
### Select Topic Area

Question

### Body

I have the following workflow with single a 2x2 matrix job: one dimension is called `compiler` (with `name` and `command` properties), one dimension is called `sanitize` (it has the same two properties).

```
name: my-workflow
on:
  push:
    branches:
      - '*'
jobs:
  my-job:
    name: My Job ${{ matrix.compiler.name }} ${{ matrix.sanitize.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        compiler:
          - name: GCC
            command: g++
          - name: Clang
            command: clang++
        sanitize:
          - name: Valgrind
            command: valgrind
          - name:
            command:
    steps:
      - name: Fail immediately
        run: false
        if: ${{ matrix.compiler.name == 'GCC' }}
      - name: Loop indefinitely
        run: while true; do sleep 1; done
 ```

Half of generated jobs fail immedaitely, the other half hangs. GitHub cancels the former as expected.

**Real behavior**: error messages about job cancellation reasons [on the workflow's "Summary"](https://github.com/yeputons/gh-actions-demo-20230312/actions/runs/4399281443) page look weird:

![image](https://user-images.githubusercontent.com/1297325/224571444-66907fb8-6268-4a30-a684-e7296d6c6bdc.png)

Specifically, the annotation says:

```
The job was canceled because "GCC_g__" failed.
```

**Expected behavior**: I would like it to use a beautified name like `My Job GCC` or just `GCC` instead of concatenating all properties of this specific job together and using that as a name. Like so:

```
The job was canceled because "My Job GCC" failed.
```

**Question**: is there some another property that I can set, in addition to `jobs.*.name`?
