### DISCUSSION TITLE
GITHUB_TOKEN doesn't trigger repository_dispatch event

### DISCUSSION THREAD

**Discussion by vrv7567** [community/community#49895] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hi,
As of 2022-09-08, the default `GITHUB_TOKEN`(Yes not the Personal Access Token) can trigger workflows of type `repository_dispatch` & `workflow_dispatch`, atleast as the official blog [implies](https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch)

Trying it out:
I have the following workflow in repo-1 under my org:
Pretty Basic, when I trigger the below workflow, it should make an API call to trigger repository_dispatch in another repo(**repo-2**)

```yaml
name: Repo-1 workflow

on: workflow_dispatch
jobs:
  sample-workflow:
    runs-on: ubuntu-latest
    steps:        
      - name: Trigger API
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          https://api.github.com/repos/org-name/repo-2/dispatches \
          -d '{"event_type":"manual-workflow","client_payload":{"name":"sample-name","uuid":"uuid-1"}}'
```

I have target workflow residing in repo-2:
```yaml
name: Repo-2 workflow

on: 
  repository_dispatch:
    types: [manual-workflow]

jobs:
  sample-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print Values
        env:
          cli-name: ${{ github.event.client_payload.name }}
          cli-id: ${{ github.event.client_payload.uuid }}
        run: |
          echo "Tenant-Name: ${cli-name}"
          echo "Tenant-ID: ${cli-id}"
```

However when the workflow in repo-1 runs it fails with the following error:
```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"
}
```

Any pointers on what's wrong ?
