### DISCUSSION TITLE
PR Checks with workflows that depend on other workflow files

### DISCUSSION THREAD

**Discussion by codevogel** [community/community#49905] [Actions]
### Select Topic Area

Github Actions

### Body

I have a `main` branch, a `dev` branch and feature branches.

I have three workflow files: `test` `build` and `deploy`

I want PRs to `main` to run all these workflows, but PRs to `dev` to just run the test workflow.

`build` should depend on `test` to succeed, and `deploy` should depend on `build`.

In `test.yml` i have 

```yml
name: GameCI Tests in EditMode
on:
   pull_request:
      branches: [main, development]
```

Then in `build.yml` i have 
```yml
name: GameCI Build
on:
  workflow_run:
    workflows: [GameCI Tests in EditMode]
    branches: [main]
    types:
      - completed
```
and `deploy.yml`
```yml
on:
  workflow_run:
    workflows: [GameCI Build]
    branches: [main]
    types:
      - completed
```

Now, in my repo I enabled branch protection for main and development, and require 'Checks' to pass. For the dev branch I require only the test check, for main I require all checks.

This works fine for the `dev` branch - it only runs the tester and then reports back the status, after which I can merge the branch.
**The issue is** that when I make a PR to main, the `test` workflow runs and completes, but the other checks never finish because they are always stuck on `expected`! So i can never complete the PR because the required checks come from a workflow that is never dispatched.

What am I doing wrong here?

![image](https://user-images.githubusercontent.com/8700780/224675936-f7d5c9c9-39fc-46d4-a9e1-a1ebfc0fa8b9.png)
