### DISCUSSION TITLE
Service Container - volume absolute path

### DISCUSSION THREAD

**Discussion by marcobaro1991** [community/community#49920] [Actions] [answered]
### Select Topic Area

Question

### Body

Ciao guys,

I am using 3 service containers:
The first and second are related to public docker images (postgres and redis) and I have no problem using them in the test pipeline of the main application.

The problem I have is on the third service container which is custom
( Nodejs based, I pushed the custom docker image to the docker hub).

Volume problem:
I have to map the src container folder in order to use the source files that are present in my repo.

I can't figure out where to find the absolute path to the github runner.

Example:

MyRepo:
- .github
- main_app_folder
- custom_service_folder
  - custom service folder sources

My `main.yml` file:

```
custom-service-folder:
        image: 'nodejs-mock'
        ports: [ '3000:3000' ]
        volumes:
          -  /custom_service_folder:/src
        options: >-
          --expose "3000"
```

Does anyone know how to do it?

thx
