### DISCUSSION TITLE
Workflow conditional cancel-in-progress

### DISCUSSION THREAD

**Discussion by big-andy-coates** [community/community#49963] [Actions]
### Select Topic Area

Question

### Body

Hi All,

I've got a question about the correct syntax for a conditional in a GitHub workflow.  I'm trying to cancel any in progress workflows, but only on certain events: I'm publishing a pages site and want to cancel any in-progress deployments only if the triggering event is a `push` or `workflow_dispatch`.  Importantly, I don't want to cancel in progress for PRs, as the pages build is one of the checks required by PRs.

Here's what I've got so far:

```yaml
name: GitHub Pages

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "${{ github.repository }}-pages"
  cancel-in-progress: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

jobs:
  ...
```

I was hoping this would mean when `event_name` was not `push` or `workflow_dispatch` then it would not cancel any progress, so PR builds would pass.  But this is not the case - it _always_ cancels in progress.

Where am I going wrong?  Bad syntax? Or is this just not supported?

Thanks,

Andy

**Comment by alex-statsig** [comment]
@big-andy-coates Curious if you ever found a solution here? I wonder if the issue with your current approach is ${{ github.event_name == 'push' }} resulting in a string "true", not a boolean. For an `if` clause, you can remove the `${{ }}` wrapping and just write `if: github.event_name == 'push'`. However, that doesn't seem to be valid syntax here (must be a boolean, not a string). Perhaps I'm getting it mixed up with https://github.com/actions/runner/issues/1483 though

**Reply by rvesse** [reply]
See https://github.com/orgs/community/discussions/69704 for a similar discussion

**Reply by alex-statsig** [reply]
Thanks @rvesse, yeah I found for my particular case it actually seems to work fine (as you mention on that discussion). That discussion seems to answer what this user may have run into though

**Reply by big-andy-coates** [reply]
Nope. Not yet. This certainly didn't seem to be working last time I looked. I'll try to find time to look again :)

**Reply by big-andy-coates** [reply]
Found the time to look at this, and I'd found a work around, which is just to _always_ cancel any in progress jobs, but grouping by something including the `github.ref`.  I'd obviously given this some more thought at some point and worked out this gave me what I wanted.

```
# Allow one concurrent deployment, per branch
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
```

Thanks for everyones help.
