### DISCUSSION TITLE
Permission denied for node binary from externals

### DISCUSSION THREAD

**Discussion by AlexShemeshWix** [community/community#49964] [Actions]
### Select Topic Area

Question

### Body

Running self-hosted github runner on Ubuntu (20/22) randomly fails workflow runs because of permission issues with node installed in externals folder.
I have workflow that looks like that

```
name: Run npm test
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  run-test:
    runs-on: [self-hosted, '${{ matrix.platform.os }}', x64, '${{ matrix.platform.label }}']
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        platform: [{ os: linux, label: aws-linux }]
        node-version: [18]       
    steps:
      - name: Check for node executable
        run: |
           while [ ! -x "/opt/actions-runner/externals/node16/bin/node" ]
           do             
             echo "/opt/actions-runner/externals/node16/bin/node file does not exist or does not have execute permissions."
             sleep 1            
            done
      - uses: actions/checkout@v3
      - name: Use Node.js
        if: always()
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
```
It randomly fails with error message 
Randomly it fails with error message
See error
Error: An error occurred trying to start process '/opt/actions-runner/externals/node16/bin/node' with working directory '/opt/actions-runner/_work/myfolder/myfolder'. Permission denied
AFAIK it happens because it uses node16 version from externals folder.
 The workflow has as step that actually checks that this binary exists and has proper permissisons.
I also have node 16 installed on vm machine that runs this workflow
Why would it give permission denied error?
Please help.
