### DISCUSSION TITLE
Run scheduled action only on PRs

### DISCUSSION THREAD

**Discussion by gregsdennis** [community/community#49960] [Actions] [answered]
### Select Topic Area

Question

### Body

Is it possible to [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) an action while also restricting it to only PRs?

My first attempt at this is

```yaml
on:
  - pull_request
  - schedule
    - cron: '0 * * * *'
```

but looking at this, I would expect it to run on PRs, and separately it would run on the schedule.  What I want is to run on the schedule, but only for PRs; I don't want it to run on branches in general.

Alternatively, is there some other way to automatically re-run jobs for PRs?

**Comment by jakoch** [comment, marked as answer]
Hey!

I doubt that the schedule event has a pull_request property that you can use to filter the event.
So setting "on" properties alone will not work.

Just my 2 cents, but i suggest trying a condition on the job to restrict it to run only on `pull_request`.
So you get two triggers on the workflow:
- `on schedule       .. run pull-request-only-job, if event is pull_request` = doing the PR filtering for scheduled runs
- `on pull_request   .. run pull-request-only-job, if event is pull_request` = a superfluous check `¯\_(ツ)_/¯`

```
name: Scheduled and normal PR Workflow
on:
  pull_request:
  workflow_dispatch:
  # scheduling only on PRs is not directly supported.  See https://github.com/orgs/community/discussions/49960
  schedule:
  - cron: '0 0 * * *' # once daily

jobs:
  pull-request-only-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      # work
```
Regards, Jens
