### DISCUSSION TITLE
Students don't get the right classroom.yml file when accepting assignment

### DISCUSSION THREAD

**Discussion by talraveh1** [community/community#49972] [GitHub Education]
Hi,

I have written tests for my students' assignment, and I use Bats testing framework.

Bats isn't installed by default and I found that if I have the code below in my .github/workshop/classroom.yml file, it fixes the problem and when they push the server is running the tests correctly.

The problem is that they keep getting a different classroom.yml file than the one I put in my template repository... (one without the bats part).

I've been searching for an answer for this for hours... and I can't find any proper documentation on how this should be done.

I tried renaming the classroom.yml file to setup.yl and check.yml.... nothing works.

Please help... I've lost hope of finding an answer for this myself.

This is the contents I'm supposed to have in the classroom.yml file:
```yml
name: GitHub Classroom Workflow
on: [push]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - uses: actions/checkout@v2
      - uses: education/autograding@v1

```
