### DISCUSSION TITLE
actions/download-artifact fails with: "Error: Unable to find an artifact with the name ..."

### DISCUSSION THREAD

**Discussion by VioletGiraffe** [community/community#50004] [Actions]
### Select Topic Area

Question

### Body

I have a workflow that builds my software, runs tests, and uploads 3 artifacts from 3 different runner VMs. Here's the final message from the Linux runner, for example: `Artifact FileCommander.AppImage has been successfully uploaded!`

Now I added a second job to this workflow that depends on the `build` job and tries to download the artifacts, just as described in the README for `actions/download-artifact`:

```
  download:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: |
            FileCommander.AppImage
            FileCommander.dmg
            FileCommander.exe
```

And it fails with this error: `Error: Unable to find an artifact with the name: FileCommander.AppImage`

What did I do wrong?

**Comment by jakoch** [comment]
Hey!

Nope, that `name` syntax with a list of artifacts to download is not yet supported (open since 2019^^), 
see https://github.com/actions/download-artifact/issues/6, especially this comment: https://github.com/actions/download-artifact/issues/6#issuecomment-620634668.

You could try `actions/download-artifact` without specifying anything at all, which means to [download all artifacts](https://github.com/actions/download-artifact#download-all-artifacts).

```
steps:
- name: Checkout 
  uses: actions/checkout@v3

- name: Downlod Artifacts 
  uses: actions/download-artifact@v3

- name: List Files
  run: ls -R
```

Regards, Jens
