### DISCUSSION TITLE
Use repository variables in `workflow_dispatch.inputs`

### DISCUSSION THREAD

**Discussion by sunzhuoshi** [community/community#50047] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi there,

I want to run my workflow manually, which requires an input with default value.

I'd like to set the default value with my repository variable, but it seems not to work.
```
on:
  workflow_dispatch:
    inputs:
      publish_version:
        description: 'Plugin version to publish'
        required: true
        default: ${{ vars.PUBLISH_VERSION }}
        type: string
```
