### DISCUSSION TITLE
How to send code scanning alerts direct into github issues

### DISCUSSION THREAD

**Discussion by MohdRashid01** [community/community#50092] [Actions]
### Select Topic Area

Question

### Body

Hi,

I have github action yml file in that i add below task in yml file and when jobs complete it send code scanning alerts direct into Security inside code scanning but we want to have that alerts to be shown in github issues not in security 
```
   - name: upload sarif file to repository
         if: failure()
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: ./results.sarif 
```
Here is the screenshot of Security showing alerts 
![image](https://user-images.githubusercontent.com/7812871/225257408-951800a1-bdaa-473e-8b6e-e1d8abd86591.png)

Here is the github issue which actually it should show
![image](https://user-images.githubusercontent.com/7812871/225257642-27545925-3ce8-4770-9279-dc4a8ed861fd.png)

We dont want to do manually but it should have automatically when the github action job trigger
