### DISCUSSION TITLE
Unable to use 'github.job' in 'jobs.if' condition

### DISCUSSION THREAD

**Discussion by ivailop** [community/community#50140] [Actions]
### Select Topic Area

Bug

### Body

**Describe the bug**
In a Job's `if` condition, using `github.job` evaluates to nothing.

**To Reproduce**
Consider the following workflow example:
```
name: Testspace
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Job name'
        required: true
jobs:
  job-example:
    if: github.job == github.event.inputs.name 
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo example "${{ github.job }}" job run
```

Running it with inputs set to `name="job-example"`  (i.e. the contained `job_id`) results in a `skipped` run.

**Expected behavior**
The `github.job` should have appropriate value as documented at https://docs.github.com/en/actions/learn-github-actions/contexts#github-context - i.e. the containing `job_id` (e.g. "job-example")

## Runner Version and Platform
Latest version running on the github.com cloud

## What's not working?
There are no error messages - the job simply appears `skipped` 
![image](https://user-images.githubusercontent.com/5092875/140172984-3637addf-f534-4b79-b5be-3836e2d57b22.png)

## Job Log Output
There is no output.

## Runner and Worker's Diagnostic Logs
NA

---
Notice, the issue was originally posted at https://github.com/actions/runner/issues/1459, but as explained in there it appears to be a problem in the GitHub actions platform in general.
