### DISCUSSION TITLE
Two Workflows with Applicable Push Criteria - Only one Workflow Fires

### DISCUSSION THREAD

**Discussion by stevehaneytrailblazer** [community/community#50160] [Actions]
### Select Topic Area

Question

### Body

I am having a hard time searching on this specific scenario to determine if its allowed but I have 2 workflows that both have the push event and look at the main branch and share a path folder to a common models path.

Example:
```
on: 
  push:
    branches:
      -main
    paths:
      - 'webapp/src/**'
      - 'webapp/package.json'
      - 'commons/src/**'
      - 'commons/package.json'
```

When I update a file in this common models path only one of the workflows triggers.  The other workflow is not disabled as far as I can tell.  Does Git Actions only match the first worfklow for an event and stop?

Thanks!
