### DISCUSSION TITLE
How to select the default option for a option field based on the selection of another option field

### DISCUSSION THREAD

**Discussion by marijana-rukavina** [community/community#50170] [Actions]
### Select Topic Area

Question

### Body

Hi, 
I have an option field environment where I can choose which environment I want to run my tests.
I also have a tag option to choose a tag to filter tests by.
What I want is that every time I choose the prod environment, my tag option is set by default to the '@anonymous' tag.
If I switch back to staging or dev, the tag option needs to be set to back empty.
This is what I tried, but it did not work :/ 
```
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Environment to run on'
        options:
        - staging
        - prod
        - dev
      tag:
        type: choice
        required: false
        description: 'Run only tests with this tag'
        options:
        - ''
        - '@anonymous'
        if: github.event.inputs.environment == prod
        default: '@anonymous'
```
