### DISCUSSION TITLE
Cross-repository actions error - resource not accessible by integration

### DISCUSSION THREAD

**Discussion by SpertsyanKM** [community/community#50213] [Actions]
### Select Topic Area

Question

### Body

I have an action, that executes actions from another repository of the same organization. 

Callable action is described as follows:
```
name: Callable action
on:
  workflow_dispatch:
    inputs:
      some_version:
        description: 'Some version'
        required: true
        default: '0.0.0'
```

Caller action does the following:
```
- name: Call another repository action
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'organization_name',
              repo: 'repository-name',
              workflow_id: 'workflow_filename.yml',
              ref: 'main',
              inputs: {
                some_version: '${{ env.some_version }}'
              },
            })
```

But if fails with the error: `HttpError: Resource not accessible by integration`. 

I have tried several solutions from the community, like adding `permissions: write-all` to the caller script or giving the same permissions in Settings -> Actions but nothing helped, I'm still getting this error.

I guess the problem is somewhere around the `secrets.GITHUB_TOKEN` which is not allowed to dispatch workflows of another repository. How can I fix it? 

Thank you.
