### DISCUSSION TITLE
configure issue templates to redirect questions to discussions

### DISCUSSION THREAD

**Discussion by evantill** [community/community#50220] [Discussions] [answered]
### Select Topic Area

Product Feedback

### Body

It would be great to redirect users trying to open an issue to use the github discussion instead (like for reporting a security vulnérability)

<img width="835" alt="New_Issue_·_plantuml_plantuml" src="https://user-images.githubusercontent.com/609288/225609919-65f06523-2912-4f73-b386-233635dc3de3.png">

I did not find a solution to do the same using a template

**Comment by LindseyB** [comment, marked as answer]
Hi, you can do this by adding a .yml file to .github/ISSUE_TEMPLATE/ eg: 

`.github/ISSUE_TEMPLATE/config.yml` 


```yaml
blank_issues_enabled: true
contact_links:
  - name: Start a discussion
    url: https://github.com/[LOGIN]/[REPO]/discussions/new
    about: We use Discussions for these reports
```
