### DISCUSSION TITLE
What is GITHUB_ACTOR value for scheduled workflows

### DISCUSSION THREAD

**Discussion by mloskot** [community/community#50250] [Actions] [answered]
### Select Topic Area

Question

### Body

I have the following test workflow defined in a multi-contributors repository:

```
name: environment-variables

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  echo-default_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Who is actor?
        run: |
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}"
```

Why `GITHUB_ACTOR=mloskot` for scheduled runs?

If it was triggered by me via push or pull request, then I can understand, but I can't find it anywhere explained: what is the value of `GITHUB_ACTOR` for scheduled run?
