### DISCUSSION TITLE
Docker Build stage should have HTTP_PROXY environments passed into it

### DISCUSSION THREAD

**Discussion by acottre** [community/community#50311] [Actions]
### Select Topic Area

Product Feedback

### Body

Following on from https://github.com/actions/runner/issues/2476#issuecomment-1473582450

When using a github action with docker, the run stage passes through all the environment variables.

However, when we are building a docker image as part of that action, the HTTPS proxy environments (and all overs) are not passed through. This means we are unable to build docker images through this as all web traffic is required to go through our web proxy.

**Comment by Mohamed-SayedAlAhl** [comment]
It is possible to pass environment variables to a Docker build stage by using the `--build-arg` option. For example, to pass an HTTP_PROXY environment variable to a Docker build stage, you could use the following command:

```
docker build --build-arg HTTP_PROXY=http://your-proxy-server:port -t your-image-name .
```

This will set the HTTP_PROXY environment variable during the build stage, allowing you to use a proxy server for web traffic.

In the context of a GitHub Action, you can set the environment variable in the workflow file and pass it to the Docker build command using the `env` parameter. For example:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        env:
          HTTP_PROXY: http://your-proxy-server:port
        run: docker build --build-arg HTTP_PROXY=$HTTP_PROXY -t your-image-name .
```

This will set the HTTP_PROXY environment variable in the build step and pass it to the Docker build command using the `--build-arg` option.
