### DISCUSSION TITLE
How to run any action on all runners at the same time?

### DISCUSSION THREAD

**Discussion by hayalpc** [community/community#50456] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi,

I am trying to run an action on the runner. I want to run an action on all of my runners. It means that i have 3 runners and they are self-hosted runners.  If I start a second process while a runner is running, the idle runner is running. But I want to run an action on all idle runners at the same time. How can i do it? Thanks

`name: My Action
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    env:
      HOME: /tmp
    steps:
      - name: Checkout
        uses: actions/checkout@v3`

**Comment by airtower-luna** [comment]
What are you trying to achieve? The question sounds a bit like it's about maintenance on the runners, in which case Actions probably isn't the right tool (or at least not directly).

**Comment by hayalpc** [comment]
Hi @airtower-luna , Think about i have a few enviroments. One of these is production and others are slave on different DC. I have to keep update the every enviroment. If i run every runners in these enviroment, i always keep update the my system. Also you thinked right that sound like maintance. How can i maintance my enviroments? Could you please tell me a way?

**Reply by airtower-luna** [reply]
That sounds like a better way would be to use a proper automated management tool instead of repurposing CI. The general idea is usually that you define a set of machines, and how they should be set up, and then the tool ensures it is so. My personal favorite is Ansible, but there are others. Of course nothing prevents you from running the tool of your choice from a (single) Actions workflow. :wink:

**Reply by hayalpc** [reply]
@airtower-luna thanks for reply. i will look Ansibe

**Comment by Anmol-Baranwal** [comment, marked as answer]
If you want to run an action on all of your self-hosted runners at the same time, you can use a job matrix in your workflow file.

A job matrix allows you to run a set of jobs in parallel, with each job using a different combination of parameters. In your case, you can define a matrix that includes all of your self-hosted runners, and then use that matrix to run the same job on each runner at the same time.

```yaml
name: My Action
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ runner1, runner2, runner3 ] # Replace with your runner names

    env:
      HOME: /tmp

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Add additional steps as needed for your action
```

the `matrix.runner` parameter defines the set of runners that the job will run on. The `strategy` block specifies that the job should be run once for each `runner` in the matrix. Each job will use the runner parameter to set the `runs-on` value, which determines which runner the job is executed on.

> When you push changes to your repository, GitHub Actions will start a new job for each runner in the matrix, and each job will run in parallel on a separate runner. This will allow you to run your action on all of your idle runners at the same time.
