### DISCUSSION TITLE
Issue templates: how to add editable tasklist to *.yml file?

### DISCUSSION THREAD

**Discussion by CalembourIII** [community/community#50502] [Projects and Issues] [answered]
### Select Topic Area

Question

### Body

I'm trying to make the perfect Issue templates for my Team, what I lack - is how to add a blank tasklist to the template? 

I mean this code to *.yml file. Is it possible? 

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

I'm using this workaround atm:

```
  - type: checkboxes
    id: tasks
    attributes:
      label: List of (sub)tasks
      description: |
        Leave this task list. After publishing - edit labels, publish again and convert to Issues if necesarry (recommended)
        P.S. sorry for the inconvenience!
      options:
        - label: Task 1
        - label: Task 2
        - label: Task 3
    validations:
      required: true
```

But it is very inconvenient. When trying to add this to yml file:

<img width="460" alt="Screenshot 2023-03-20 at 16 30 50" src="https://user-images.githubusercontent.com/121853646/226371538-79cc7ef4-7384-4908-b0dd-7e2c5674187c.png">

I get this: 

<img width="473" alt="image" src="https://user-images.githubusercontent.com/121853646/226371749-45587017-eaed-44e2-846e-2a93f8ae84dd.png">

But I'm aiming for this result, because it is very convenient to edit:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/121853646/226371930-51ebca3b-4cec-49a5-b1fd-4533458cdd61.png">

Maybe someone found a workaround?

**Comment by dsparacio** [comment]
I am looking to do the same and exploring options, would be great to know if it is support or not, before I dig that hole.

**Reply by CalembourIII** [reply]
Hi, sorry, but I did not find a workaround for this :|

**Reply by rkrooneman** [reply, marked as answer]
Good question. I did a workaround like this:

```
  - type: textarea
    id: tasks
    attributes:
      label: 🖱️Tasks
      value: |
          ```[tasklist]
          ## (What do engineers have to do step by step?)
          - [ ] Verify the issue
          - [ ] Solve the issue
          - [ ] Test the solution
          ```
```

When creating a new issue you'll only see the markdown code but upon submitting you will get the desired tasklist block.

**Reply by CalembourIII** [reply]
I did exactly the same (+ `description`, but it's optional). I just forgot to share it here:

```
 - type: textarea
    id: handover
    attributes:
      label: Handover checklist
      description: Please check the boxes to be clear that everything is done from your side?
      value: |
        - [ ] Issue has PR attached (if applicable)
        - [ ] (Sub)tasks are closed
        - [ ] Acceptance Criteria double-checked and checkboxes marked
        - [ ] Is it clear how to test the issue in QA?
```

Thank you @rkrooneman !
