### DISCUSSION TITLE
appleboy/ssh-action@master  - Error Client.Timeout exceeded while awaiting headers

### DISCUSSION THREAD

**Discussion by ppmgitrepo** [community/community#50510] [Actions]
### Select Topic Area

Question

### Body

I need to open an ssh session to another server and run some scripts over there. 
So decided to use 
https://github.com/appleboy/ssh-action

The WF is running on a self hosted runner hosted on OCI 
Firewall / NSG ports are opened up to the https://registry-1.docker.io host

Facing the following error 

Step 1/4 : FROM appleboy/drone-ssh:1.[6](https://github.com/OCIApps/TechOpsCICD/actions/runs/4467131802/jobs/7846200480#step:2:6).10
  Trying to pull repository docker.io/appleboy/drone-ssh ... 
  Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning: Docker build failed with exit code 1, back off 5.249 seconds before retry.

Code 
````

jobs:
  conn_server:
    name: conn_server
    environment: ppm_prod    
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: conn_step1
        uses: appleboy/ssh-action@master 
        with:
          host: xx.yy.zz.oraclevcn.com
          username: oracle
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            echo "connection complete : "
            pwd
            echo `hostname` 
            exit

````

Note: 
Manually using the same pvt key am able to open an ssh connection to the target server.
Docker is installed on the runner and the daemon is running
