### DISCUSSION TITLE
Maven release:prepare fails to find dependency despite dependency having been successfully retrieved during maven clean install

### DISCUSSION THREAD

**Discussion by rcasey-vertek** [community/community#50513] [Packages]
### Select Topic Area

Question

### Body

I have a project that builds successfully with maven but fails due to a missing dependency when mvn release is run within the same workflow, both processes use the same settings.xml.

Output from successful artifact retrieval during build:
Downloaded from github-dev: https://maven.pkg.github.com/ORG/any/REPO/3.0/ARTIFACT.pom

Release error output:
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact ARTIFACT in central (https://repo.maven.apache.org/maven2)

Why is mvn release:prepare looking for this artifact in central?

Github actions workflow:
```
name: maven-release-plugin

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "git@github.com"
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: settings.xml setup
        run: |
          echo "${{ vars.test_settings }}" > $GITHUB_WORKSPACE/settings.xml
          sed -i "s/'/\"/g" $GITHUB_WORKSPACE/settings.xml
        env:
          ACTOR: ${{ github.token }}
          TOKEN: ${{ secrets.CI_OPS_TOKEN }}
      - name: Build with Maven
        run: |
          mvn clean install -DskipTests -s $GITHUB_WORKSPACE/settings.xml
      - name: Publish package to GitHub (Release plugin)
        run: mvn -V -B -X release:prepare release:perform -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
```
