### DISCUSSION TITLE
Unhelpful error

### DISCUSSION THREAD

**Discussion by gregsdennis** [community/community#50527] [Actions]
### Select Topic Area

General

### Body

This error is unhelpful
<img width="366" alt="image" src="https://user-images.githubusercontent.com/2676804/226451440-5c16e561-9cfb-4f67-b4dc-57298e49ac88.png">

It tell me what line it's on, but not what the actual problem is.  I've tried multiple variations, and I can't get my action to run.

```yaml
name: PR Policy
on:
  pull_request
  workflow_dispatch
  # there's a comment here
  schedule
    - cron: '0 0 * * *'
```

```yaml
name: PR Policy
on:
  - pull_request
  - workflow_dispatch
  # there's a comment here
  - schedule
    - cron: '0 0 * * *'
```

**Comment by gregsdennis** [comment]
`schedule` needs a colon.

**Comment by Neodevils** [comment]
`schedule` is missing colon `:` at the end.

So it should looks something like:
```yaml
# there's a comment here 
- schedule:
  - cron: '0 0 * * *'
```
