### DISCUSSION TITLE
Reusable workflows, Conditional Jobs and Job Dependencies

### DISCUSSION THREAD

**Discussion by abjrcode** [community/community#50520] [Actions]
### Select Topic Area

Question

### Body

My issue seems closely related to https://github.com/actions/runner/issues/491. I have analogous setup:

```yml
on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  jobA:
    uses: ./.github/workflows/myflow.yml

  jobB:
    uses: ./.github/workflows/myflow.yml
    needs:
      - jobA
    if: github.event_name == 'release'
```

Now I expect: `jobB` to run only after `jobA` runs successfully AND the condition is met which doesn't seem to be the case as merging pull requests to `main` is also triggering `jobB` after `jobA` finishes successfully even though the condition should not match.

I could not find the expected behavior documented so I am not sure whether this is a bug or a feature?
