### DISCUSSION TITLE
No ability to add images to new issue forms

### DISCUSSION THREAD

**Discussion by braem** [community/community#5053] [Projects and Issues] [answered]
To my knowledge there is no way to add images with the new github issue templates (in yaml), making them not very usable for visual bugs/features/etc. Doing something like this in `body` also doesnt work:

```
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
    render: markdown
  validations:
    required: true
```
![image](https://user-images.githubusercontent.com/9014762/129129903-f35800bf-b7ea-4782-8aaa-8a7ea518733d.png)

Even then, being able to paste an image from clipboard into markdown is super useful (i even used it here), which you can only do by retroactively editing the issue once it's created (and lose the nice formatting as a result).
