### DISCUSSION TITLE
Actions: Use env or other variables with container/image?

### DISCUSSION THREAD

**Discussion by rajbos** [community/community#5057] [Actions]
We need to have a way of using variables in the container names we want to run our actions in to use a specific label or a different registry to enable mirrors to GHES for example with only changes needed to the secrets they use

Also found this as a request on the comunity forum [here](https://github.community/t/how-to-use-env-with-container-image/17252/4).

For example, using a variable in the container name:
```
env:
  container_registry: ${{ secrets.container_registry }}
    
jobs:
  test:
    runs-on: ubuntu-latest
    container: $container_registry/powershell:7
    steps:
    - uses: actions/checkout@v2
```
