### DISCUSSION TITLE
How to pass secrets to the destination server?

### DISCUSSION THREAD

**Discussion by x-yuri** [community/community#50577] [Actions]
### Select Topic Area

Question

### Body

The documentation [says][a]:

> Avoid passing secrets between processes from the command line, whenever possible. Command-line processes may be visible to other users (using the ps command) or captured by [security audit events](https://docs.microsoft.com/windows-server/identity/ad-ds/manage/component-updates/command-line-process-auditing). To help protect secrets, consider using environment variables, STDIN, or other mechanisms supported by the target process.

I'm not sure what exactly that means. I can do as shown in the docs:

```yaml
steps:
  - env:
      ENV: ${{ secrets.ENV }}
    run: echo "$ENV" > .env
      && scp .env USER@xx.yy.xx.yy':'
```

I can pass it [with `SendEnv`][b] (needs `AcceptEnv` on the server):

```yaml
steps:
  - env:
      ENV: ${{ secrets.ENV }}
    run: ssh -o SendEnv=ENV USER@xx.yy.xx.yy':'
```

But I still need to do `echo "$ENV" > .env` on the server.

The best way is supposedly to use an action to put the secret into a file. But I'm not sure.

How do I go about it?

[a]: https://docs.github.com/en/actions/security-guides/encrypted-secrets
[b]: https://superuser.com/a/702751/185665
