### DISCUSSION TITLE
github action input choice list based on previous input choice selection

### DISCUSSION THREAD

**Discussion by akhtarali1** [community/community#50602] [Actions]
### Select Topic Area

General

### Body

Is it possible to list choices for a second input based on first input selection.

something like:
```
on:
  workflow_dispatch:
    inputs:
      app-name:
        description: "Name of application to be uninstalled"
        required: true
      environment:
        description: Environment
        type: choice
        required: true
        # the names of the options must match the names in GitHub Settings / Environments
        options:
          - non-production
          - production
      namespace:
        description: Namespace
        type: choice
        required: true
        # Based on previous input selection, namespaces will be populated for selection.
        options:
          ${{ if eq(inputs.environment, 'production') }} # if environment is production
          - 'prd'
          - 'stg' # Staging / pre-production environment
          ${{ else }} # if environment is non-production
          - 'ite'
          - 'cae'
          - 'acp'
          - 'npe'
          ${{ endif }}
```

Currently getting an error which makes no sense
![image](https://user-images.githubusercontent.com/11717801/226622610-5f59eb77-6905-4b9a-9ffb-5f39419c9926.png)
