### DISCUSSION TITLE
Can dependency graph detect dependencies from pyproject.toml's build-system.requires ?

### DISCUSSION THREAD

**Discussion by Freed-Wu** [community/community#50619] [Packages] [answered]
### Select Topic Area

Product Feedback

### Body

According to PEP621, a python project can have a `pyproject.toml` in the root directory of repo, which is like:

```toml
[build-system]
requires = ["setuptools_scm[toml] >= 6.2"]
build-backend = "setuptools.build_meta"
```

the `build-system.requires` is also a dependencies which should be displayed in dependency graph. However, <https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems> doesn't support it now. Can it be supported? TIA!
