### DISCUSSION TITLE
How to skip workflow steps and still run the subsequent steps cleanly

### DISCUSSION THREAD

**Discussion by ImreC** [community/community#50729] [Actions]
### Select Topic Area

Question

### Body

So I am running a composed workflow which I have simplified here:
```
jobs:
  filter:
    outputs:
      should-run-workflow-2: ${{some-expression-that-evaluates-to-true-or-false}}
  run-workflow-1:
    uses: ./.github/workflows/workflow-1.yml
  run-workflow-2:
    needs: [filter, run-workflow-1]
    if: ${{needs.filter.outputs.should-run-workflow-2 == 'true'}}
    uses: ./.github/workflows/workflow-2.yml
  run-workflow-3
    needs: [run-workflow-2]
    uses: ./.github/workflows/workflow-3.yml
```
As you can see, whether workflow 2 is run or is skipped depends on a conditional. Let's say that these three workflows deploy infrastructure that depends on each other, for example workflow 1 deploys a db, workflow 2 a back end application that needs the db and workflow 3 a front end app that needs the back end. What I want to achieve is that it is possible to conditionally skip run-workflow-2, but still execute run-workflow-3. I can only find solutions that:
- ignore failures in the previous step (e.g. solutions based on `always()`) 
- do not run when workflow 2 does not run
- require massive acrobatics to get this to work (f.e. if statement on each step in the jobs or complicated conditionals) 
- 
I can think of a solution that would allow this cleanly: instead of `needs:` have a milder version like `depends-on:` which allows for the target to be skipped instead of only allowing `succeeded`. 

Alternatively there could also be a conditional option which allows to write a more permissive statement instead of only `always()`, `success()` or `failure()` (f.e.`skipped()`).

Am I missing something obvious here or is this just not possible?
