### DISCUSSION TITLE
Calling a runtime-computed version of a workflow

### DISCUSSION THREAD

**Discussion by tcsc** [community/community#50790] [Actions]
### Select Topic Area

Question

### Body

Hi all,

I have two workflows: 

1. An `outer-workflow` that is called on a schedule. Its job is to compile a list git tags in our repo that need a maintenance task run over them, and then invoke that maintenance task via a `workflow_call`. Being a scheduled workflow, it must run from the default branch. 
2. An `inner-workflow`, that implements the actual maintenance task.

Where it gets tricky is that the code at each tag computed by `outer-workflow` may have a different implementation of `inner-workflow` that needs to be run.

I have naively tried to run these jobs in a matrix over the tag list like so:

```yaml
some-task:
    # ... 
    strategy:
      matrix:
        tag-of-interest: ${{ fromJSON(...some computed list...) }}
    uses: owner/repo/.github/workflows/inner-workflow@${{ matrix.tag-of-interest }}
```

Which naturally fails at parse time as GHA expects to know the callee revision of `inner-workflow` before it even starts executing the outer one.

Is there any way to call an arbitrary revision of `inner-workflow` without that revision being statically declared in the `uses` parameter of the job? Even being able to trigger a fire-and-forget `workflow_dispatch` event would probably do in this particular case, but's probably the avenue of last resort.

cheers,

Trent
