### DISCUSSION TITLE
Automatic Issue Linking not working

### DISCUSSION THREAD

**Discussion by SerenModz21** [community/community#5080] [Projects and Issues]
Hello. I was wondering if anyone knows why GitHub is not automatically linking the pull request with the issue. I am trying to use GitHub actions to automatically link issues with a specific pull request from gaining a label called "done".

From looking at GitHub Documentation ([link here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)), It shows that these keywords can be used to link them together but it isn't working.

![Image](https://cdn.serenmodz.rocks/ytAaIeD.png)

If needed, here is the code for the GitHub action:
```yml
name: Label Automation

on:
  issues:
    types: [labeled]

jobs:
  automation:
    runs-on: ubuntu-latest
    name: Label Automation
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
  
      - name: Assign done label
        if: ${{ github.event.label.name == 'done' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 80
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## The issue was marked as done
            - Resolve #${{ github.event.issue.number }}
            - Closes #${{ github.event.issue.number }}
            - Resolves #${{ github.event.issue.number }}
```
