### DISCUSSION TITLE
GPR won't publish with secrets.GITHUB_TOKEN, even if I specify "packages: write" in the "permissions" field.

### DISCUSSION THREAD

**Discussion by santi100a** [community/community#50877] [Actions]
### Select Topic Area

Question

### Body

Hello, dear GitHub community!

I'd like some help with my publishing workflow. This is `test.yml`:
```yaml
name: Continuous Integration (CI)

permissions:
  packages: write

on:
  push:
    branches: 
      - main
    paths:
      - src/**/*.*


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
          always-auth: true

      - name: Install dependencies
        run: yarn

      - name: Build source code
        run: yarn build

      - name: Run test suites
        run: yarn test --testPathPattern ./tests
  release:
    needs: test
    uses: ./.github/workflows/release.yml
    secrets: 
      GH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      GPR_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
This is `release.yml`:
```yaml
name: Release Workflow

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      NPM_AUTH_TOKEN:
        required: true
      GPR_AUTH_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Generate tag, release name, and body
      run: |
        TAG_NAME="v$(jq -r '.version' package.json)"
        RELEASE_NAME="Release $TAG_NAME"
        BODY=$(sed -n "/## Version $(jq -r '.version' package.json | sed 's/\./\\\./g')/,/##/p" CHANGELOG.md | sed '1d;/^##/d')
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
        echo "$BODY" >> release.md
    - name: Create release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        name: ${{ env.RELEASE_NAME }}
        token: ${{ secrets.GH_TOKEN }}
        bodyFile: release.md
        draft: false
        prerelease: false
  call-publisher-workflow:
    needs: release
    uses: ./.github/workflows/publish.yml
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      GPR_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}

```
And finally, this is `publish.yml`:
```yaml
name: Continuous Deployment (CD)

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true
      GPR_AUTH_TOKEN:
        required: true
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          always-auth: true
      - name: Install dependencies
        run: yarn
      - name: Build code
        run: yarn build
      - name: Set access tokens
        run: |
          npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_AUTH_TOKEN }} 
      - name: Publish to NPM
        run: yarn publish --access public
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          always-auth: true
      - name: Install dependencies
        run: yarn
      - name: Build code
        run: yarn build
      - name: Set access tokens
        run: |
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.GPR_AUTH_TOKEN }}
      - name: Get ready to publish to GPR
        run: |
          jq ".name = \"@$REPO\"" package.json > temp.json && mv temp.json package.json
        env:
          REPO: ${{ github.repository }}
      - name: Publish to GPR
        run: yarn publish --access public --registry https://npm.pkg.github.com/
```
I'd also like to replace the value of GH_TOKEN with GITHUB_TOKEN - I just need to make sure GITHUB_TOKEN can read, write and delete releases and GPR packages.
