### DISCUSSION TITLE
Auto generation of release notes not respecting configuration file

### DISCUSSION THREAD

**Discussion by tyro-mchamberlain** [community/community#50886] [Repositories] [answered]
### Select Topic Area

Bug

### Body

Hi there!

When we generate release notes either using the 'Generate release notes' button in the Releases page, or via the API with the `POST /repos/{owner}/{repo}/releases/generate-notes` it doesn't have the structure we defined in the `.github/release.yml` file. 

The contents of our `.github/release.yml` file, which is on `master`, is (as per the docs):
```yml
# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
```

When we submit the `POST` request via the API and specify the `release.yml` in the body we receive this response: 
```json 
{
  "message": "Could not find a configuration file at .github/release.yml",
  "documentation_url": "https://docs.github.com/rest/reference/repos#generate-release-notes"
}
```

We're in the process of automating our releases and currently the release notes are not as readable as they could be if compared to if we are able to use the structure in the configuration.

Any help would be much appreciated! 

With thanks,
Matt
