### DISCUSSION TITLE
GitHub Actions has encountered an internal error when running your job.

### DISCUSSION THREAD

**Discussion by omegion** [community/community#50902] [Actions]
### Select Topic Area

Question

### Body

Hi,

I am having a problem with an Action. We have an action to trigger other actions using `matrix`. But after 2nd matrix job, the workflow fails with:

```
<ACTION_NAME>: .github#L1
GitHub Actions has encountered an internal error when running your job.
```
Workflow:
```
name: 'XXX'

on:
  workflow_dispatch:
    inputs:
      strategyName:
        description: "X"
        default: "non-production"
        type: string
        required: true
      dryRun:
        description: "Dry run"
        type: choice
        required: true
        options:
          - yes
          - no

env:
  AWS_ROLE_SESSION_DURATION: 43200

# Required to get the ID Token that will be used for OIDC
permissions:
  contents: read
  id-token: write

jobs:
  get-strategy-config:
    runs-on: ubuntu-latest
    name: Get Strategy Config
    outputs:
      cluster_update_list: ${{ steps.cluster_update_list.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Strategy Configuration
        id: cluster_update_list
        uses: mikefarah/yq@v4.32.2
        with:
          cmd: yq 'del(.name,.description)' X/${{ inputs.strategyName }}.yaml -o json

  cluster-bulk-update:
    needs:
      - get-strategy-config
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJson(needs.get-strategy-config.outputs.cluster_update_list) }}
    name: ${{ matrix.strategy.name }}
    uses: ./.github/workflows/x-bulk-update.yaml
    secrets: inherit
    with:
      region: ${{ matrix.strategy.region }}
      environment: ${{ matrix.strategy.environment }}
      tags: ${{ matrix.strategy.tags }}
      dryRun: ${{ inputs.dryRun }}
```

Does anybody know how to debug this issue to see what is failing actually?

Bests,
Hakan

**Comment by Akash1134** [comment]
Hi @omegion , Sorry that you're facing this problem. We've just resolved an [Actions incident ](https://www.githubstatus.com/incidents/rcjsf188vx7q) that might have caused this. Could you please re-run the Action and see if it returns the same error? Thanks

**Reply by omegion** [reply]
Hi @Akash1134 I am having this problem for two days. I will re-run the job again.

**Reply by omegion** [reply]
Failed again, it seems there is  something fails in the background but I cannot see what it is. How can we debug this?

**Comment by nicholasbergesen** [comment]
Hi @omegion,

Its difficult to know what might be causing this without more information, are you willing to share the workflow yaml that's failing? If not maybe you could share an example similar to your actual workflow?

**Reply by omegion** [reply]
```
name: 'XXX'

on:
  workflow_dispatch:
    inputs:
      strategyName:
        description: "X"
        default: "non-production"
        type: string
        required: true
      dryRun:
        description: "Dry run"
        type: choice
        required: true
        options:
          - yes
          - no

env:
  AWS_ROLE_SESSION_DURATION: 43200

# Required to get the ID Token that will be used for OIDC
permissions:
  contents: read
  id-token: write

jobs:
  get-strategy-config:
    runs-on: ubuntu-latest
    name: Get Strategy Config
    outputs:
      cluster_update_list: ${{ steps.cluster_update_list.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Strategy Configuration
        id: cluster_update_list
        uses: mikefarah/yq@v4.32.2
        with:
          cmd: yq 'del(.name,.description)' X/${{ inputs.strategyName }}.yaml -o json

  cluster-bulk-update:
    needs:
      - get-strategy-config
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJson(needs.get-strategy-config.outputs.cluster_update_list) }}
    name: ${{ matrix.strategy.name }}
    uses: ./.github/workflows/x-bulk-update.yaml
    secrets: inherit
    with:
      region: ${{ matrix.strategy.region }}
      environment: ${{ matrix.strategy.environment }}
      tags: ${{ matrix.strategy.tags }}
      dryRun: ${{ inputs.dryRun }}
 ```
 
 This is the workflow. It basically calling another workflow in a loop.

**Reply by nicholasbergesen** [reply]
Hi @omegion,

It looks like the output should be set in the `cluster_update_list` step, but it doesn't appear to be getting set, is this just because it was trimmed out for the example?

**Reply by omegion** [reply]
@nicholasbergesen the action i use outputs it. So I do not have to set it again.

I solved the problem. The matrix object I pass in `cluster_update_list` was a little big, and GH did not like it. I removed all unnecessary fields, it did work. 

But its still odd GH action does not error the reason.

**Reply by nicholasbergesen** [reply]
Thank you for posting your feedback, I agree that generic error message isn't helpful and should be improved to include some details.

**Comment by andremorais-sigtech** [comment]
I have the same error, I get  "GitHub Actions has encountered an internal error when running your job" with no more information if I try to run this workflow. If I remove the permissions bit, I don't get this error, but I need it to be able to use OIDC to assume an AWS role. Although I have other workflows using the same approach, and they work, only this one is failing. Any ideas?


```yaml
on:
  push:
    branches:
      - 'master'
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run tests
        run: go test -race ./...

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build

      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::xxxxxxxx:role/xxxxxx
          role-session-name: xxxx

```
