### DISCUSSION TITLE
[Bug] Missing language icon in GitHub Trending

### DISCUSSION THREAD

**Discussion by g-plane** [community/community#5099] [Other Feature Feedback, Questions, & Ideas]
Language icons are missing in GitHub Trending:

![图片](https://user-images.githubusercontent.com/17216317/129449721-3766ff27-d174-466e-a199-34aba469dedf.png)

Currently I'm using snippet below as workaround:

```css
.repo-language-color {
  display: inline-block;
  height: 12px;
  width: 12px;
  border-radius: 50%;
  position: relative;
  top: 1px;
}
```

And it renders:

![图片](https://user-images.githubusercontent.com/17216317/129450044-a72110d6-e488-4244-bf5f-b3f913f3561d.png)
