### DISCUSSION TITLE
Action that can push to protected branch (master)

### DISCUSSION THREAD

**Discussion by CJCrafter** [community/community#51128] [Actions]
### Select Topic Area

Question

### Body

I have a [workflow](https://github.com/CJCrafter/ChatGPT-Java-API/blob/master/.github/workflows/readme-version.yml) that will update all occurrences of old versions (e.g., `1.0.0`) with the newest version (e.g., `1.2.1`). This is one of those classic software devs "Automating a 30-second task with a 5-hour solution."

The answers I've found online suggest this is impossible, but that is lame. 
```yaml
name: Update README Version

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update version in README
        run: |
          # Extract the version from the build.gradle.kts file
          VERSION=$(grep -oP 'version\s*=\s*"\K\d+\.\d+\.\d+' build.gradle.kts)

          # Update the README.md file
          export VERSION
          python -c "import re, os; version=os.environ['VERSION']; content=open('README.md').read(); content=re.sub(r'\d+\.\d+\.\d+', f'{version}', content); open('README.md', 'w').write(content)"

      - name: Commit and push changes
        run: |
           git config --global user.name "GitHub Actions Bot"
           git config --global user.email "collinjbarber@gmail.com"
           git remote set-url origin https://${{ secrets.PAT }}@github.com/CJCrafter/ChatGPT-Java-API.git
           git add README.md
           git diff --quiet && git diff --staged --quiet || (git commit -m "Update version in README.md" && git push)
```

This workflow produces the following output
```
Run git config --global user.name "GitHub Actions Bot"
[master 9[12](https://github.com/CJCrafter/ChatGPT-Java-API/actions/runs/4528667148/jobs/7975658865#step:5:13)4e4d] Update version in README.md
 1 file changed, 4 insertions(+), 4 deletions(-)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: New changes require approval from someone other than the last pusher.        
To https://github.com/CJCrafter/ChatGPT-Java-API.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/CJCrafter/ChatGPT-Java-API.git'
Error: Process completed with exit code 1.
```

There has got to be some workaround using tokens/permissions/something so that this task can be automated. It is silly to have to update maven/gradle dependencies every update.
