### DISCUSSION TITLE
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/WangRongsheng/ChatGenTitle/v1'. Did you forget to run actions/checkout before running your local action?

### DISCUSSION THREAD

**Discussion by WangRongsheng** [community/community#51190] [Actions]
### Select Topic Area

General

### Body

I create my workflow:

`actions.yaml`:
```yaml
name: Scrapy arxiv information and push to GitHub

on:
  schedule:
    - cron:  '30 8,17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out the code
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run scrapy
      run: python get_arxiv_multiprocessing.py
    - name: Push changes
      uses: WangRongsheng/ChatGenTitle@v1
      with:
        commit_message: 'update data'
        commit_options: '--author "wrs6@88.com"'
        branch: main
        file_pattern: 'data/*.json'
        pull_branch: true
        github_token: ${{ secrets.ACCESS_TOKEN }}
```

but get error:

```html
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/WangRongsheng/ChatGenTitle/v1'. Did you forget to run actions/checkout before running your local action?
```

How can i solve it？
