### DISCUSSION TITLE
Request for Job Descriptions

### DISCUSSION THREAD

**Discussion by NatoNathan** [community/community#51214] [Actions]
### Select Topic Area

Product Feedback

### Body

It would be nice if you could add a description to a job in a github actions workflow, that could be shown in the github UI when you hover over the job in the actions tab. This would help those not familiar with the workflow understand what the goal of the job is.

Like so
```yml
estimate-version:
    name: Estimate version bump
    description: Estimate the version bump based on the PR title when merged
    runs-on: ubuntu-latest
```
