### DISCUSSION TITLE
Access JSON fields with nesting >1

### DISCUSSION THREAD

**Discussion by mihaigalos** [community/community#51248] [Actions] [answered]
### Select Topic Area

Question

### Body

I  have a composite action `metaconfig` which produces the following valid json:
```json
{
  "compliance_checks": {
    "enabled": false,
    "artifactory_push_branches": "main, foo"
  },
  "megalinter": {
    "enabled": true,
    "artifactory_push_branches": "main"
  }
}
```

I'm trying to consume it in another composite action:
```yaml
    - name: Metaconfig
      id: metaconfig
      uses: ./repo/.github/composites/metaconfig

    - name: Evaluate if we need to run the next jobs
      id: evaluate
      shell: bash
      env:
        data: ${{ fromJSON(toJSON(steps.metaconfig.outputs)).metaconfig.compliance_checks.enabled }}
      run: echo $data
```

I don't get any output in the `run`. If I only read the 1st level nesting (`fromJSON(toJSON(steps.metaconfig.outputs)).metaconfig` only), it works and shows the full json (output `metaconfig`). Why?
