### DISCUSSION TITLE
Set up an action to share links to uploaded artifacts in PR comments

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#51403] [Actions] [answered]
### Select Topic Area

Question

### Body

I would like to make a workflow which runs on `pull_request_target` and does the following things:

- It takes the code from the PR.
- It builds Jar files with it using Maven.
- It uploads the generated jars using the upload-artifact action.
- It creates (or updates if present) a comment including a direct link to the artifact download itself.

The first three parts are relatively easy for me to. But the last one gives me a minor headache as I'm not sure what the best way would be to access the URL(s) of the uploaded artifacts.
I'm aware that the URL (from what I know) isn't provided/created by GitHub until the job has completed, which is why I would do the comment stuff on a separate job depending on the prior one.

Here's my current setup:
```yaml
name: 'Build PR changes'

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'bukkit/src/**'
      - 'bungeecord/src/**'
      - 'core/src/**'
      - 'velocity/src/**'

concurrency: 'pr-preview'

jobs:
  buildJars:
    name: 'Build Jars from Pull request'
    runs-on: ubuntu-latest
    outputs:
      comment_id: ${{ steps.find-comment.outputs.comment-id }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Setup Java 16'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '16'
          cache: 'maven'
      - name: 'Build Jar files'
        run: mvn clean install
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: asl-files
          path: '*/target/AdvancedServerList-*.jar'
          if-no-files-found: error
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
  updateCommentSuccess:
    name: 'Create or update Comment (On Success).'
    needs: [buildJars]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ needs.buildJars.outputs.comment_id }}
          body: |-
            ## Build Preview
            
            [![badge]](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            You can find files attached to the below linked Workflow Run URL (Logs).
            
            Please note that files only stay for around 90 days!
  
            | Name      | Link                                                                                |
            |-----------|-------------------------------------------------------------------------------------|
            | Commit    | ${{ github.event.pull_request.head.sha }}                                           |
            | Logs      | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | Jar Files | <!-- What can I put here? -->                                                       |
            
            [badge]: https://img.shields.io/badge/Build-Success!-3fb950?logo=github&style=for-the-badge
      - name: Update Comment
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ needs.buildJars.outputs.comment_id }}
          body: |-
            ## Build Preview
            
            [![badge]](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            There was an issue generating the Jar files from your Pull request.
            Please review the logs linked below for further information.
            
            | Name   | Link                                                                                |
            |--------|-------------------------------------------------------------------------------------|
            | Commit | ${{ github.event.pull_request.head.sha }}                                           |
            | Logs   | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            
            [badge]: https://img.shields.io/badge/Build-Failure!-f85149?logo=github&style=for-the-badge
```

**Comment by djthornton1212** [comment]
@Andre601 

Hey, jumping over from the other conversation. You can get the artifact url in a separate job as you stated using the api "/repos/{owner}/{repo}/actions/artifacts". You can narrow it down to the workflow_run.id or the SHA if you so choose.

**Reply by Andre601** [reply]
I'm not that experienced with GitHub Actions, so I don't quite know exactly how this entire thing would look like if I want a URL that points directly to the artifact in question of that workflow itself

**Comment by erikmd** [comment]
As mentioned in [this other thread](https://github.com/actions/upload-artifact/issues/50#issuecomment-1494865308), I think **[this workflow template](https://stackoverflow.com/a/74586595/9164010)** might be useful for you:

* it waits that the first workflow (say, `Build PR changes`) that produces artifacts is over (whatever is the project language)
* it runs subsequently and automatically if this first workflow succeeded
* it computes the artifacts' URL using a bash script and the GitHub REST API:  
  they are always of the form `https://github.com/${{ github.repository }}/suites/${check_suite_id}/artifacts/${artifact_id}`
* it uses curl to attach *status* comments to the commit SHA1 that produced the binaries:
  see [this PR](https://github.com/ocaml-sf/learn-ocaml/pull/501) for a demo.

To do so, you'd just need to reuse the template and modify the 2 lines marked ↓ below

```yaml
name: Pin artifacts
on:
  workflow_run:
    workflows:
      # todo: Update this list if need be ↓
      - "Build PR changes"
    types: ["completed"]
jobs:
  # Make artifacts links more visible for the upstream project
  pin-artifacts:
    permissions:
      statuses: write
    name: Add artifacts links to commit statuses  # todo: replace TODO-orga and TODO-repo ↓
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == 'TODO-orga/TODO-repo' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add artifacts links to commit status
      # …
      # more omitted, cf. Link in bold on top
      # …
```

**Reply by Andre601** [reply]
As pointed out by my reply is the main issue here that I don't need it in the commit status, but the PR itself (as in as a comment itself).

And the example provided there looks way too overcomplicated for me to understand so I honestly stay away from it, as I would be the one that has to maintain it, should any breaking changes appear in the future.

**Reply by erikmd** [reply]
No worries!
just wanted to share this comprehensive example which was very close to what you want to do.
Indeed, it can't be used as is given the commit status API call in the end should be replaced with that of the PR comments.

**Comment by gilzow** [comment]
[Per the docs](https://github.com/platformsh/config-reader-python/issues/39), I was under the impression that the download URL is from the API is only good for one minute. 
> Gets a redirect URL to download an archive for a repository. This URL expires after 1 minute.

I needed to do a similar thing (post a comment to the PR with a link to the artifact). What I ended up doing was getting a link to the workflow run and then add a url fragment to where the artifacts are displayed on the workflow run.

**Reply by djthornton1212** [reply]
Hey @gilzow,
     I don't think that link points to where you intended. I presume you wanted it to go [here](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/artifacts?apiVersion=2022-11-28#download-an-artifact).

I believe that is valid for the `Download an artifact` api. What I'm proposing is the static link to the zip from the [List artifact for a repository](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/artifacts?apiVersion=2022-11-28#list-artifacts-for-a-repository). From my experience this link doesn't change.

I believe the difference is that the `Download an artifact` link is a redirect, while the other is a permalink. I could be wrong, but it I've been pulling the same url for hours now and it still works.

**Reply by gilzow** [reply]
> I don't think that link points to where you intended. I presume you wanted it to go [here](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/artifacts?apiVersion=2022-11-28#download-an-artifact).

you are correct. copying and pasting too many links at once.

> I believe that is valid for the Download an artifact api. What I'm proposing is the static link to the zip from the [List artifact for a repository](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/artifacts?apiVersion=2022-11-28#list-artifacts-for-a-repository). From my experience this link doesn't change.

Correct, but I thought those downloads from that API weren't available _during_ a workflow run, but only available afterwards? OP wants to post the link as a comment _during_ the workflow run. I see that you've suggested a second workflow to run after completion of the first. That is certainly a valid option, assuming OP is ok with that layout.

**Comment by djthornton1212** [comment, marked as answer]
@Andre601  

@erikmd Is giving you the framework of how this would work. The flow would look like so...

Workflow 1: build/test/publish artifact
Workflow 2: At the completion of workflow 1 if completed this job will run and retrieve the url and you can code to  post it to the PR.

I want to clarify something from my experience. This statement here: `I'm aware that the URL (from what I know) isn't provided/created by GitHub until the job has completed, which is why I would do the comment stuff on a separate job depending on the prior one.` isn't exactly correct. What's really happening is the URL is available until the **workflow** if complete, not the job. Trust me I and many others have tried using multiple jobs to get it. It's not available to us until the entire workflow is complete. GitHub's download artifact action uses custom super secretive code to get that within the workflow. This is why it requires 2 separate workflows.

I mocked up an example you can using most of what you posted above. I admit this took longer than it should have. Got caught up on a letter in my json query.

Workflow 1:

```yaml
# artifact-upload.yml
---
name: Artifact Upload

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  create-artifact:
    env:
      ARTIFACT_NAME: artifact.txt
      ARTIFACT_PATH: ./
    runs-on: ubuntu-latest
    steps:

      - name: Create something to artifact
        run: |

          # Here we just create something for the example
          echo "stuff I want to artifact" > "$ARTIFACT_PATH/$ARTIFACT_NAME"

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_NAME }}
          if-no-files-found: error
```

Workflow 2:
```yaml
# pr-comment-artifact-url.yml
---
name: Comment Artifact URL on PR

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Artifact Upload"

jobs:
  comment-on-pr:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:

      - name: Get Artifact URL & PR Info
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
        run: |

          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"

          ARTIFACT_URL=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
            --jq ".artifacts.[] |
            select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
            select(.expired==false) |
            .archive_download_url")

          echo "ARTIFACT URL: $ARTIFACT_URL"
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_ENV"

          PR_NUMBER=$(jq -r '.pull_requests[0].number' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")

          echo "PR Number: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"

          HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")

          echo "Head sha: $HEAD_SHA"
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"

      - name: Update Comment
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/\
            runs/${{ env.PREVIOUS_JOB_ID }}"
          HEAD_SHA: ${{ env.HEAD_SHA }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ env.PR_NUMBER }}
          body: |-
            ## Build Preview

            [![badge]]($JOB_PATH)

            You can find files attached to the below linked Workflow Run URL (Logs).

            Please note that files only stay for around 90 days!

            | Name      | Link
            --------------------------------------------------------------------
            | Commit    | ${{ env.HEAD_SHA }}

            | Logs      | ${{ env.JOB_PATH }}

            | Jar Files | ${{ env. ARTIFACT_URL }}

            [badge]: https://img.shields.io/badge/Build-Success!-3fb950?logo=github&style=for-the-badge

```

You can see the jobs [here](https://github.com/djthornton1212/djthornton1212/actions).

You can see the PR [here](https://github.com/djthornton1212/djthornton1212/pull/2).

**Reply by Andre601** [reply]
Just to be sure. Is the env stuff on the build workflow needed? or is it an optional thing? My build would be multiple files combined in one artifact upload, so I'm not sure if I can just provide a simple name or smth...

**Reply by Andre601** [reply]
Also, is `${{ github.token }}` actually a valid thing here? Wouldn't it be `${{ secrets.GITHUB_TOKEN }}` or am I missing something here?

**Reply by djthornton1212** [reply]
> Just to be sure. Is the env stuff on the build workflow needed? or is it an optional thing? My build would be multiple files combined in one artifact upload, so I'm not sure if I can just provide a simple name or smth...

No, it's not. It's just an example. You'll need to modify this example to fit your needs.

**Reply by djthornton1212** [reply]
> Also, is `${{ github.token }}` actually a valid thing here? Wouldn't it be `${{ secrets.GITHUB_TOKEN }}` or am I missing something here?

It's a thing. Remember, there's the github context and there the environmental variables. Most... if not all of the system environmental variables GitHub provides you comes from the github context.

I suggest you do a little more research on how the two relate [here](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)

In short `${{ secrets.GITHUB_TOKEN }} == ${{ github.token }}`

**Reply by Andre601** [reply]
Okay. So why exactly do you then define `GITHUB_TOKEN: ${{ github.token }}` if it is equal to `${{ secrets.GITHUB_TOKEN }}`? Shouldn't that already be defined and usable?

Also, thanks for the link. Through it, I found this specific note about `GITHUB_ENV`:
> The path on the runner to the file that sets variables from workflow commands. This file is unique to the current step and changes for each step in a job. For example, `/home/runner/work/_temp/_runner_file_commands/set_env_87406d6e-4979-4d42-98e1-3dab1f48b13a`

If I understand this right is the GITHUB_ENV unique to each step, meaning that anything defined in the first step isn't accessible in the second? If that's the case, then I doubt we can just use `${{ env.<name> }}` here to access previously set variables.
We probs would need to change it to `GITHUB_OUTPUT` to have values pass onto follow-up steps.

**Reply by Andre601** [reply]
nevermind. The follow-up section explains that you can use github env to pass stuff... A bit confusingly written imo.

**Reply by djthornton1212** [reply]
What I wanted you to take away from that link is this section here....

> Most of the default variables have a corresponding, and similarly named, context property. For example, the value of the GITHUB_REF variable can be read during workflow processing using the ${{ github.ref }} context property.

It's in the tooltip at the bottom of the section. 

The reason I defined it in the step is because the GitHub CLI (gh) requires you do so.

The GITHUB_ENV comes in scopes, there's workflow level, job level and step level. Yes, it can be confusing, just remember that it's limited to the scope of where it was defined... with 1 exception. That exception is when you add a variable to ${{ GITHUB_ENV }}/${{ github.env }} inside a step. 

> If you generate a value in one step of a job, you can use the value in subsequent steps of the same job by assigning the value to an existing or new environment variable and then writing this to the GITHUB_ENV environment file.

**Reply by Andre601** [reply]
I've set up the workflow and it seems to work.

The only thing is, that the returned URL gives me an Error:
```json
{
  "message": "You must have the actions scope to download artifacts.",
  "documentation_url": "https://docs.github.com/rest/reference/actions#download-an-artifact"
}
```

**Reply by djthornton1212** [reply]
@Andre601  Depending on how you're repository is configured you will likely need to give the `GITHUB_TOKEN` the permissions necessary. 

See [here](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview) for how to provide permission. The output says you need the `actions` scope, so you likely need.

This can also be validated at the documentation_url provided. You'll see this line on the API:

> Apps must have the actions:read permission to use this endpoint.

**Reply by Andre601** [reply]
You misunderstand me. The Action works and I got the URL. But opening it myself I get the above issue, which probs means that the given URL is only meant for applications/actions and not normal (registered) users.

**Reply by Andre601** [reply]
This is also noticable given the returned URL.

The one I now have in the PR comment is in the form of `https://api.github.com/repos/:user/:repo/actions/artifacts/:id/zip` while the URL I would have when manually downloading an artifact from a run would be `https://github.com/:user/:repo/suites/:other_id/artifacts/:id` (Note that `:id` is in both cases the same)

**Reply by djthornton1212** [reply]
Ahh I see. Note that the url returned is an api url. You'll need to use a personal access token with the correctly scoped permissions if you want to access it yourself. You can use either curl or equivalent tool for api work.

**Reply by Andre601** [reply]
All I really want is the `/suites` URL here... nothing more. And if possible would I like to avoid usage of a PAT.

**Reply by djthornton1212** [reply]
Yeah, I think you'll have to formulate that manually.

If you use a combination of the [Get a workflow run](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#get-a-workflow-run) api to extract the SUITE_ID=`check_suite_id` & the [List artifacts for a repository](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#list-artifacts-for-a-repository) to extract the ARTIFACT_ID=`artifacts[0].id` and combine them you could create that link...

"${{ github.server_url }}/${{ github.repository }}/suites/$SUITE_ID/artifacts/$ARTIFACT_ID"

Something along those lines might get you what you're looking for, but I don't think that there's any api/command that's just going to output what you want. You could always just point to the job/run and let them click on the artifact download icon.

**Reply by Andre601** [reply]
So, if I understand it right should this work?
```yaml
name: Comment on Pull request

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Create PR Artifacts'

jobs:
  comment:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact and Pull request info
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"
          
          SUITE_ID=$(jq -r '.check_suite_id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Suite ID: $SUITE_ID"
          echo "SUITE_ID=$SUITE_ID" >> "$GITHUB_ENV"
          
          ARTIFACT_ID=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
            --jq ".artifacts.[] |
            select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
            select(.expired==false) |
            .id")
          
          echo "Artifact ID: $ARTIFACT_ID"
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> "$GITHUB_ENV"
          
          PR_NUMBER=$(jq -r '.pull_requests[0].number' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")
          
          echo "Pull request Number: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"
          
          HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")
          
          echo "Head SHA: $HEAD_SHA"
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
      - name: Update Comment
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ env.PREVIOUS_JOB_ID }}"
          ARTIFACT_URL: "${{ github.server_url }}/${{ github.repository }}/suites/$SUITE_ID/artifacts/$ARTIFACT_ID"
          HEAD_SHA: "${{ env.HEAD_SHA }}"
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |-
            ![badge]
            
            Build Successful! You can find a link to the downloadable artifact below.
            
            | Name     | Link                    |
            | -------- | ----------------------- |
            | Commit   | ${{ env.HEAD_SHA }}     |
            | Logs     | ${{ env.JOB_PATH }}     |
            | Download | ${{ env.ARTIFACT_URL }} |
            
            [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjZmZmZmZmIj48cGF0aCBkPSJNMjEuMDMgNS43MmEuNzUuNzUgMCAwIDEgMCAxLjA2bC0xMS41IDExLjVhLjc0Ny43NDcgMCAwIDEtMS4wNzItLjAxMmwtNS41LTUuNzVhLjc1Ljc1IDAgMSAxIDEuMDg0LTEuMDM2bDQuOTcgNS4xOTVMMTkuOTcgNS43MmEuNzUuNzUgMCAwIDEgMS4wNiAwWiI+PC9wYXRoPjwvc3ZnPg==
```
