### DISCUSSION TITLE
[Run job in a custom container from ECR] Failed after docker login

### DISCUSSION THREAD

**Discussion by klochenok** [community/community#51413] [Actions]
### Select Topic Area

Bug

### Body

I am trying to run github action with job in custom container from ECR. Here how I'm trying to pull container from ECR:
```
  job-1:
    runs-on: ubuntu-latest
    outputs:
      ecr_username: ${{ steps.define-vars.outputs.ecr_username }}
      ecr_password: ${{ steps.define-vars.outputs.ecr_password }}
     .....
     
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    container:
      image: 12345678.dkr.ecr.us-west-1.amazonaws.com/ecr-repo-name:image-tag
      credentials:
        username: ${{ needs.job-1.outputs.ecr_username }}
        password: ${{ needs.job-1.outputs.ecr_password }}
```
But it is failed on step **Initialize containers** (system step) when docker try to login. So in logs there is next output
```
/usr/bin/docker --config /home/runner/work/_temp/.docker_5678b61a-4452-49fc-1224-da41e7867448 login 12345678.dkr.ecr.us-west-1.amazonaws.com -u "AWS" --password-stdin
 Error: Docker login for '12345678.dkr.ecr.us-west-1.amazonaws.com' failed with exit code 1
```
I debugged and checked that username and password are passed correctly. Also i tried to do `docker login` locally with same creds and it also works. 
My guess is that` --password-stdin` flag is causing the login to fail, because the password is not being passed correctly to the command. 

Any ideas about this issue? Maybe I am doing something wrong.
