### DISCUSSION TITLE
How do I use "docker compose" in an action and have it cache to the ghcr archive?

### DISCUSSION THREAD

**Discussion by rknop** [community/community#51417] [Actions]
### Select Topic Area

Question

### Body

From the command line, if I run:

```
   docker compose pull
   docker compose build
   docker compose push
   docker compose run <something>
```

the first step will pull down all docker images in the docker-compose.yaml file if they aren't already on the local machine.  The second step will build the docker images only if the ones cached on the local machine aren't up to date with the relevant Dockerfiles.  The third step will push the docker layers up to the repository only if they aren't already on the repository.  The last one actually runs something.

I'm trying to accomplish this as an action in a github workflow, and I'm tearing my hear out as I can't get it to work.  Every time I do this, it always builds, and it always pushes (not recognizing that the layer is already on the repository).  It doesn't seem to be using the local docker layer cache at all when deciding if it has to go all the way through the build step.  I've tried a bunch of different ways of doing this -- including putting the three commands on three lines together after "run: |", and trying to use a docker:build-push-action step or two (trying options like "load: true" and "pull: true").  No matter what I do, every time, it always pulls (or fails), it always builds, and it always pushes.

How can I make this properly cache?  Some of the docker images take a while to build, and I'd like to have it take advantage of a registry.

One way I've tried this is the following.  I have two build-push-action steps since it's not possible to have both "load" and "push" true at once (I get an error message)

```
name: Moo

on:
  push:
    branches:
      - main
    workflow_dispatch:



jobs:
  tests:
    name: moo
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}

      - name: pull/build moo docker image
        uses: docker/build-push-action@v2
        with:
          pull: true
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/moo:latest
          context: .

      - name: push moo docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/moo:latest

      - name: run test
        run: docker compose run moo
```

The docker-compose.yaml file is:

```
version: "3.3"
services:
  moo:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/moo
    build: .
    entrypoint: [ "/usr/games/cowsay", "moo" ]

```

**Comment by rknop** [comment]
This is my latest attempt.

The github actions file is:

```
name: Moo

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  tests:
    name: moo
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: bake
        uses: docker/bake-action@v2
        with:
          load: true
          set: |
            *.cache-to=type=gha,mode=max                                                                                
            *.cache-from=type=gha                                                                                       

      - name: run test
        run: |
          docker compose run moo
```

and the `docker-compose.yaml` is

```
version: "3.3"
services:
  moo-webserver:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/moo-webserver
    build:
      context: webserver

  moo:
    depends_on:
      - moo-webserver
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/moo
    build:
      context: moo
    entrypoint: [ "/bin/bash", "/tmp/moo/testing.sh" ]
```

I notice that the github actions cache *is* getting populated (as seen from the web interface).  But, still, every time the action runs, it goes through rebuilding the docker images.  It doesn't seem to be reading the cache.
