### DISCUSSION TITLE
The running Action isn't matching it's body?

### DISCUSSION THREAD

**Discussion by FlagHunter01** [community/community#51471] [Actions]
### Select Topic Area

Question

### Body

# The right Action runs at the right time, but half of it's body is missing

Hello everyone!

I have a weird one. I'm not sure if I'm doing something wrong or if it's linked to the recent outages but ... GitHub runs another version of my Action file.

Here is the file:

```yml
name: ci 
on:
  push:
    branches:
      - website
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material 
      - run: git-revision-date-localized
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-committers-plugin-2
      - run: pip install mkdocs-git-authors-plugin
      - run: mkdocs gh-deploy --force
```

And here is the output:

![2023-03-30_10h15_18](https://user-images.githubusercontent.com/32909577/228773030-16856c5b-ded6-42fe-8ee1-b1662eacdbcc.png)

So my question is: It runs my first and last `run` directives, but where did the 5 that are supposed to be in-between go? 

I tried modifying the file, deleting and then pushing it again but nothing works: GitHub still executes this "ghost" version. 
Anyone knows if I'm oblivious to something or is it a bug?

Thanks a lot!
