### DISCUSSION TITLE
Permission Error 403 - Unable to push image despite login to ghcr.io is succeeded

### DISCUSSION THREAD

**Discussion by areebemumba** [community/community#51548] [Actions]
### Select Topic Area

Bug

### Body

`github.action.yml`
```
name: Build and Push Freeradius proxy
on:
  push:
    branches:
      - '*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GCR_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Login to GHCR
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_OWNER }}
          password: ${{ secrets.GCR_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
```

Error:

> Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/ORG-NAME/REPO-NAME:74dee872822195355126eb34c850acbc0c999f9db: unexpected status: 403 Forbidden

![image](https://user-images.githubusercontent.com/113666491/229045539-92d4b8ce-089d-4805-874c-f2b07e1c7a9b.png)
