### DISCUSSION TITLE
Unable to use relative URLs in contact_links config

### DISCUSSION THREAD

**Discussion by Relequestual** [community/community#5166] [Projects and Issues]
I've been trying out issue templates config.yml for the contact links feature.

I want to add this config to our orgs `.github` repo, and have it populated across all our repos.

I want to direct people looking to ask questions to the Github Discussions for the repo they are currently viewing.

Given there is no documented template interpliation with special codes (such as "current_repo_url"), I figured a relative URL might work. Sadly this results in the contact link not even showing in the issue template listing.

Example: 

```yaml
blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: "/../../discussions"
    about: Please report security vulnerabilities here.
  - name: JSON Schema Slack
    url: https://json-schema.org/slack
    about: Get async support and discussion from the community and maintainers
```

In repo: https://github.com/Relequestual/template-testing/blob/80af97ffc59eda6cc2d3704218ba21200225cc3f/.github/ISSUE_TEMPLATE/config.yml
(The main branch may change after this posting as I continue to experiment, but this is likely still as per the linked commit.)
