### DISCUSSION TITLE
Videos in issue forms are not rendered correctly (type: markdown)

### DISCUSSION THREAD

**Discussion by autoantwort** [community/community#51709] [Projects and Issues]
### Select Topic Area

Bug

### Body

In an issue I can simply paste links to videos that are then displayed as videos like here: https://github.com/microsoft/vcpkg/issues/30604 

If I try the same in an issue form:
```yaml
body:
  - type: markdown
    attributes:
      value: | 
        ⚠ Please use the generated issue template instead to report a port build failure. ⚠  
         https://user-images.githubusercontent.com/41973254/229313721-b82c2d3d-b0f9-4e31-98df-08d75831f695.mp4
```
it is only displayed as link:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/41973254/229314571-7ef4689e-3712-4989-bc08-e08375562444.png">

If I use a `<video>`tag:
```yaml
body:
  - type: markdown
    attributes:
      value: | 
        ⚠ Please use the generated issue template instead to report a port build failure. ⚠  
         <video src="https://user-images.githubusercontent.com/41973254/229313721-b82c2d3d-b0f9-4e31-98df-08d75831f695.mp4"></video>
```
I get this:
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/41973254/229314621-b5a64607-5705-48ff-bae8-0d591a15228d.png">

Adding `style="max-width: 100%; max-height:640px; min-height: 200px"` does not help since it is filtered out.
