### DISCUSSION TITLE
Custom postgres container from registry cannot bind mount files from repository

### DISCUSSION THREAD

**Discussion by kevinmamaqi** [community/community#51711] [Actions]
### Select Topic Area

Question

### Body

Hi there,

I am using the following code workflow. All goes well except from the part of the bind mount. I am trying to follow the guides and saw the announcement that custom container could be run as service: https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/

```
name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ghcr.io/my-custom-image
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5555:5432
        options: >-
          --mount type=bind,source=${{ github.workspace }}/db/pg-init.sh,target=/docker-entrypoint-initdb.d/pg-init.sh,readonly
          --mount type=bind,source=${{ github.workspace }}/db/init,target=/init,readonly
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5555/public
```

The bit that fails is:

```
options: >-
          --mount type=bind,source=${{ github.workspace }}/db/pg-init.sh,target=/docker-entrypoint-initdb.d/pg-init.sh,readonly
          --mount type=bind,source=${{ github.workspace }}/db/init,target=/init,readonly
```

Any idea why and/or how to sort it out? I've checked multiple times and the files are there, and path printed out seems to be correct, although the checkout is donde after the service... 😕
