### DISCUSSION TITLE
There will be a `/usr/bin/clear_console` called if a step's bash script include a conditon

### DISCUSSION THREAD

**Discussion by chylli-deriv** [community/community#51834] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi,
I wrote an action like this:
```
name: check-git-message
description: check git message to decide if this test should run
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: |
        set -x
        echo "${{ github.event_name}} ${{ github.ref_name }}"
        if [ "${{ github.event_name }}" == "pull_request" -a "${{ github.ref_name }}" != "master" ]
        then
          echo "ok"; 
          exit 0;
        fi
      name: Check git message if it contains the keyword [ci]
      shell: bash -le {0}
```

Then I use it in my workflow:
```
jobs:
  check-git-message:
    runs-on: ubuntu-latest
    steps:
      - name: check git message
        uses: myname/github-actions/check-git-message@dev
```

Then I will get the following result:
```
Run set -x
  set -x
  echo "pull_request 799/merge"
  if [ "pull_request" == "pull_request" -a "799/merge" != "master" ]
  then
    echo "ok"; 
    exit 0;
  fi
  shell: /usr/bin/bash -le {0}
+ echo 'pull_request 799/merge'
+ '[' pull_request == pull_request -a 799/merge '!=' master ']'
+ echo ok
+ exit 0
pull_request 799/merge
ok
++ '[' 1 = 1 ']'
++ '[' -x /usr/bin/clear_console ']'
++ /usr/bin/clear_console -q
Error: Process completed with exit code 1.
```

If there is no `if` line, then everything ok. But if there is, then a `/usr/bin/clear_console` is executed. Why it happen? I didn't type any `cleaer_console` in the code.

**Comment by airtower-luna** [comment]
`set -x` makes the shell show commands that are being executed. The `if` line executes `[ "pull_request" == "pull_request" -a "799/merge" != "master" ]` and uses the result to determine whether to run the commands between `then` and `fi`.

As a side note, avoid using Actions syntax (`${{ ... }}`) in the `run` script. Those parts are substituted *literally* before the shell ever sees your script, the shell doesn't see them as variables, so escaping with quotes around them doesn't work quite right. For example, if someone were to put a `"` into the branch name your script would break in weird ways. Depending on context this can be a security problem, so best avoid it and use environment variables instead. :warning: 

```yaml
- run: |
    set -x
    echo "${EVENT_NAME} ${REF_NAME}"
  env:
    EVENT_NAME: ${{ github.event_name }}
    REF_NAME: ${{ github.ref_name }}
```

Though for the specific values you're using you don't even need to create the environment variables, you can find them in the [automatically defined environment](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) (`GITHUB_EVENT_NAME` and `GITHUB_REF_NAME`).
