### DISCUSSION TITLE
Trigger GitHub Actions in pull request

### DISCUSSION THREAD

**Discussion by ypresto** [community/community#5186] [Pull Requests]
I'd appreciate if github could implement button to trigger `workflow_dispatch` GitHub Actions in pull request.

Detail:

We have GitHub Actions for deploying pull request to temporary environment (a.k.a. review apps), and run some (heavy) E2E tests.

They can be triggered via "command" comments (typescript-bot in microsoft/TypeScript also do this). The yaml file is looks like this:

```yaml
on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  run-cypress:
    name: Build Next.js and run Cypress
    runs-on: ubuntu-latest
    if: (github.event_name != 'issue_comment') || (github.event.issue.pull_request && startsWith(github.event.comment.body, '!github run-e2e'))
```

It is bit tricky, and records too many "skipped" workflow run histories.
Also it is limited to one command per comment, because there is no split() or regexp in `if:` expression.
