### DISCUSSION TITLE
Nesting in release.yml

### DISCUSSION THREAD

**Discussion by tonglil** [community/community#51885] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Product Feedback

### Body

Create subheadings with `release.yml` for better release notes.

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

For example:

```
changelog:
  categories:
    - title: Breaking changes
      labels:
        - breaking change
      nested:
        - title: API
          labels:
            - area/api
        - title: UI
          labels:
            - area/ui
    - title: API changes
      labels:
        - area/api
```

This would create:

```
## What's Changed

### Breaking changes
* Anything that has `breaking change` label but no other sub-labels
#### API
* Anything with the `breaking change` label AND the `area/api` label
#### UI
* Anything with the `breaking change` label AND the `area/api` label

### API
* Anything that has `area/api` label and didn't get captured by the `breaking change` or other previously defined label in a `nested:` field

```

**Comment by tonglil** [comment]
It's not possible to write rules in this manner that allows composition of labels to create a release note such as:

```
breaking changes
## UI
- pr1
## API
- pr2

hot fixes
- pr3

minor changes
## UI
- pr4
## API
- pr5

patch changes (aka everything else)
## UI
- pr6
## API
- pr7
```

Where the PRs have these labels

1. breaking change, ui
2. breaking change, api
3. hotfix
4. minor change, ui
5. minor change, api
6. ui
7. api

^ I don't want to label every patch PR with a patch label as well...

Because a config like:

```
    - title: "⚠️ Breaking Changes - UI"
      labels:
        - ui
        - breaking change
      exclude:
        labels:
          - minor change
```

Does not mean the PR needs *both* `ui` && `breaking change`, but just one || the other.

**Comment by tonglil** [comment]
Also, please let us generate the release note with some additional text in each section.

Such as:

```yaml
changelog:
  categories:
    - title: Breaking changes
      text: |
        ## custom markdown here in this section
        please pay attention here, you will need to do:
          - [ ] x
          - [ ] y
          - [ ] z
      labels:
        - breaking change
```
