### DISCUSSION TITLE
[Bug] Nested Reusable Workflow prevents cancelation

### DISCUSSION THREAD

**Discussion by xvzf** [community/community#51949] [Actions]
### Select Topic Area

Bug

### Body

It seems a nested workflow (e.g. following the definition attached at the end of this post) either prevents or does not receive any cancel requests. We have now seen several workflow runs lasting >1h, because a manual cancelation was not successful.

```yaml
# ...
jobs:
  deploy:
    name: Deploy
    uses: "./.github/workflows/deploy-common.yaml"
    with:
      env: some-env
      new_tag: "${{ needs.version.outputs.new_tag }}"
      e2e_test: smokeTest
    secrets: inherit

```
