### DISCUSSION TITLE
How to push changes made by PHPCS?

### DISCUSSION THREAD

**Discussion by MatthewDlr** [community/community#52018] [Actions] [answered]
Hey all, 

I just started with GitHub actions, and I feel that that I missed many things because I struggle a lot to achieve the goal of my workflow. I want to make a workflow that analyzes my PHP code with PHPCS, then fix the fixable errors with PHPCBS and then commit the changes into main. The first stage is failing which is normal because my PHP code contains errors and then the push appears to run correctly but I don't see any changes in my repo. 

My `workflows` file is as follow: 
```
name: phpcs

on:
  push:
    branches: [main]

jobs:
  Code-Analysis: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install dependencies
        run: composer install
        
      - name: Check coding standards
        id: phpcs
        run: ./vendor/bin/phpcs --report=json  --report-file=report.json --standard=PSR2 --colors --encoding=utf-8 app
        
      - name: Apply fixes
        run: ./vendor/bin/phpcbf --standard=PSR2 --colors --encoding=utf-8 app
        
  branch-Update:
    needs: [Code-Analysis]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps :

    - name: Push
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
```

And this is my composze file : 
```
{
  "name": "test/mytest",
  "description": "app",
  "type": "project",
  "homepage": "https://github.com",
  "license": "BSD-3-Clause",
  "authors": [
    {
      "name": "Test",
      "email": "test@project.com",
      "role": "lead"
    }
  ],
  "support": {
    "issues": "https://github.com",
    "source": "https://github.com"
  },
  "extra": {
    "branch-alias": {
      "dev-master": "3.x-dev"
    }
  },
  "require": {
    "php": ">=8.0",
    "ext-tokenizer": "*",
    "ext-xmlwriter": "*",
    "ext-simplexml": "*"
  },
  "require-dev": {
    "phpunit/phpunit": "^4.0 || ^5.0 || ^6.0 || ^7.0",
    "squizlabs/php_codesniffer": "^3.7.2"
  },
  "bin": [
    "bin/phpcs",
    "bin/phpcbf"
  ]
}
```
I saw some screens where people have a UI after the analysis where they could accept or decline every change made by PHPCS but I didn't understand at all how to put that in place, so I wanted to commit the changes instead. I searched in every repo and discussion solutions, but none achieved what I wanted.

I you have any ideas of what I may did wrong or suggestions about how to achieve my goal I'm all ears.
thx.
