### DISCUSSION TITLE
Required Checks not actually required

### DISCUSSION THREAD

**Discussion by lordbyron** [community/community#52082] [Actions]
### Select Topic Area

Bug

### Body

In a Repo I have a workflow (action) that runs on pull_request_review, which does a check on who the reviewer is and passes or fails based on some custom logic. "Pass" or "fail" means the action's script exits with 0 or 1. The Job has a condition to only run if github.event.review.state == 'approved'.

On the repo I have "Require status checks to pass before merging" with this action selected.

If I open a new PR, the check shows Yellow with "Expected — Waiting for status to be reported." Since it is triggered on review, it hasn't run yet. Then someone approves the PR, running the action, which correctly fails because of our custom logic. The check shows Red, required check failed, as expected.

Now if I (or anyone) submits a review of type Comment (as opposed to Approved or Request Changes), the action will be Skipped, the check will show as Grey (skipped), and the PR will be say "All checks have passed!" The action fully ran once, and failed, and was skipped the second time it was triggered. It _never_ passed.

The workflow config looks like this:
```
on:
  pull_request_review:
    types: [submitted]
    branches: [master]

jobs:
  validate-approver:
    name: Check if approved by a code owner
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Validate approver
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/validate-approvers.sh "${{ github.repository }}" "${{ github.event.pull_request.number }}"
        shell: bash
```

There doesn't seem to be any way to move the `if` condition up into the `on` section, and this method of triggering on `submitted` with a condition on `state` is pulled straight from docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved

There is also no way for the steps to return a neutral result. In the case of someone adding a review comment, it should not change the previous result of the action (Pass or Fail on comment would both be wrong). Skipping the action seems to be correct, but a skipped check cannot be a passing check!

Thanks in advance for any help here.

PS. I am familiar with CODEOWNERS; I'm looking for how to get actions to behave as described above, not a completely different way to solve for validating approvers :)

**Comment by magmanu** [comment]
Hey @lordbyron,
Did you find a solution to this?

I have a similar issue with a dependabot automerge workflow (required workflow). When the author is not dependabot, the workflow skips as expected... until someone pushes a commit to that PR. When there's a new PR event that doesn't match the type that triggers the workflow, the check is left hanging just like yours. 

```
  pull_request_target:
    # Types must be specific to prevent getting stuck if a bot adds a commit.
    # See more here: https://github.com/orgs/community/discussions/33804#discussioncomment-3710676
    types:
      - opened
      - reopened
    branches:
      - main
 
jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
       ...
```

I suspect the issue might be of same nature as the one [documented here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks)
I'll test the solution proposed in that link at some point in the next few days.

**Reply by lordbyron** [reply]
Negative. I opened a GH support case but couldn't reach any understanding with them. I ultimately removed the `if` condition on my job, so it runs my script on every event, but the script is idempotent so the result (pass/fail) correctly blocks or allows a merge. It's a waste of action minutes, and it wastes ~30 seconds when the result is already known, but it is at least correct

**Reply by magmanu** [reply]
Thank you, I had to do some workaround too. And I agree, it's a waste of resources 🤷🏽‍♀️

**Comment by magmanu** [comment]
An update if anyone else arrives here from googling the issue:

I tested the workaround suggested in [this documentation](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks) (even though it's not the same issue, it's a very similar one). It did not work.

In my case, the issue was the use of filtering by pull_request types. Tthe solution was to allow the workflow to run for all types of pull_request events, but break it into two jobs. The first job would identify if the the desirable conditions to trigger the workflow were met, and return true/false accordingly. The second job would actually perform the actions I needed from the workflow, but only if the first job returned true.

```
name: Dependabot auto-merge
on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:

  is-dependabot:
    runs-on: ubuntu-latest
    outputs:
      is-dependabot: ${{ steps.is-dependabot.outputs.result }}
    steps:
      - name: Is actor dependabot
        id: is-dependabot
        run: |
          if [ "${{ github.actor }}" == "dependabot[bot]" ]; then
            echo result="true" >> "$GITHUB_OUTPUT"
          else
            echo result="false" >> "$GITHUB_OUTPUT"
          fi


  dependabot-automerge:
    runs-on: ubuntu-latest
    needs: is-dependabot
    if: ${{ fromJson(needs.is-dependabot.outputs.is-dependabot) == true }}
    steps:
        ...
```
