### DISCUSSION TITLE
Github-actions execute on source code(different repo).

### DISCUSSION THREAD

**Discussion by Raghvendra-Singh-Chandel** [community/community#52133] [Actions]
### Select Topic Area

Question

### Body

If we have our own automation framework, will Github actions execute on source code(different repo)?

**Comment by AneeqMalik** [comment]
Yes, you can use GitHub Actions to execute automated tests on source code in a different repository. Here's how:

Set up the automation framework: First, you'll need to set up your automation framework in a separate repository. This will typically involve writing code to define your tests, as well as any supporting infrastructure that's needed to execute them (e.g., test runners, dependencies, etc.).

Configure the GitHub Actions workflow: Once you have your automation framework set up, you can configure a GitHub Actions workflow to execute your tests. In your repository where you want to run the tests, create a new YAML file (e.g., test.yml) in the .github/workflows directory. This YAML file will define the steps that GitHub Actions should take to run your tests.

Define the test job: In your YAML file, define a job that will run your tests. This job should include steps to clone the repository with your automation framework, install any necessary dependencies, and then run the tests.

Trigger the workflow: Finally, you can trigger the workflow by pushing changes to the repository or by manually running the workflow from the GitHub Actions UI.

Here's an example YAML file that demonstrates how to run tests from a separate repository:

```
name: Run tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout automation framework
      uses: actions/checkout@v2
      with:
        repository: <username>/<automation_framework_repo>
        ref: <branch_name>
        path: tests

    - name: Install dependencies
      run: cd tests && npm install

    - name: Run tests
      run: cd tests && npm test

```
In this example, the actions/checkout action is used to clone the repository with the automation framework, and the npm install and npm test commands are used to install dependencies and run tests, respectively. Note that you will need to replace <username>, <automation_framework_repo>, and <branch_name> with the appropriate values for your setup.

With this workflow, GitHub Actions will automatically execute your tests whenever changes are pushed to the repository. You can customize the YAML file to define multiple jobs, set up environment variables, and more, depending on the specific requirements of your automation framework.
