### DISCUSSION TITLE
How to only trigger patch updates

### DISCUSSION THREAD

**Discussion by dprotaso** [community/community#52182] [Code Security]
### Select Topic Area

Bug

### Body

I configured dependabot to update only patch release - but for some reason it's ignoring the entire dependency now and it closed the old pull request (https://github.com/knative/infra/pull/54#issuecomment-1499268115)

Is this the correct way to ensure only patch release are being bumped?

```
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/images/prow-tests/"
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: golang
      update-types:
      - "version-update:semver-major"
      - "version-update:semver-minor"
```
