### DISCUSSION TITLE
github actions working script to create a new version tag based on the current tags which is pulled from pull request template when selecting major, minor and patch checkboxes

### DISCUSSION THREAD

**Discussion by sureshdevops99** [community/community#52203] [Actions]
### Select Topic Area

Question

### Body

we have a pull request template
major
minor
patch

if the current list of tags is
10.10.0
...
...
2.0.1
2.0.0
1.1.0
1.0.0

if I select minor in the PR, I would like to create a version with tag as 10.11.0 using github actions script.

**Comment by BREN0sx** [comment]
Hey! I think this is something like this that you need 👇

The code below automates the process of creating release tags based on the options selected in the pull request template

``` yaml
name: Versioning

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Git
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          repository: ${{ github.repository }}

      - name: Get current version
        id: get_version
        run: echo ::set-output name=version::$(git describe --abbrev=0 --tags)

      - name: Determine version type
        id: bump_version
        run: |
          export major=$(echo ${{ steps.get_version.outputs.version }} | cut -d '.' -f 1)
          export minor=$(echo ${{ steps.get_version.outputs.version }} | cut -d '.' -f 2)
          export patch=$(echo ${{ steps.get_version.outputs.version }} | cut -d '.' -f 3)

          if [ -n "${{ github.event.pull_request.labels.find(x => x.name == 'major') }}" ]; then
            echo "::set-output name=version::${major}.0.0"
          elif [ -n "${{ github.event.pull_request.labels.find(x => x.name == 'minor') }}" ]; then
            echo "::set-output name=version::${major}.${minor+1}.0"
          else
            echo "::set-output name=version::${major}.${minor}.${patch+1}"
          fi

      - name: Create new tag
        uses: anothrNick/github-tag-action@v1.12.2
        with:
          tag: ${{ steps.bump_version.outputs.version }}
          message: 'New version'

```

This creates a new release tag based on the current tags that are pulled from the pull request template by selecting the major, minor, and patch checkboxes

It might solve your problem… I hope 😃
