### DISCUSSION TITLE
Self-hosted Runner Labels

### DISCUSSION THREAD

**Discussion by maeghan-porter** [community/community#52211] [Actions]
### Actions

Question

### Body

I'm setting up autoscaling runners in a kubernetes cluster but this cluster follows a development pipeline. This means that we can have ephemeral and development versions of the same cluster, which will spin up runners in each cluster. I am trying to figure out if there is a way to apply a github label to the runners via some settings on the deployment or something so we can make sure we're using the runners in the stable/production cluster and not ones in the development clusters, but I am only finding information on applying labels through the github UI. Am I just missing this somehow? There MUST be a way to do this, right?

**Comment by SMelidoni** [comment]
Hi @maeghan-porter

If I understand you correctly then I believe that yes, you can apply labels to GitHub Actions self-hosted runners through your deployment configuration. The way to do this is by setting the `--labels` flag when you start the runner. You can set this flag in your deployment configuration (e.g., in a Kubernetes manifest). Here's a high-level example of how you might do this:

1. In your runner's deployment configuration (e.g., a Kubernetes manifest or Helm chart), update the container's command to include the `--labels` flag followed by the desired labels, separated by commas.

For example, you might have a Kubernetes manifest with a container definition that looks like this:
```
containers:
  - name: github-runner
    image: your-runner-image
    args:
      - "--url"
      - "https://github.com/your-org/your-repo"
      - "--token"
      - "your-token"
```

2. Update the container definition to include the `--labels` flag, like so:
```
containers:
  - name: github-runner
    image: your-runner-image
    args:
      - "--url"
      - "https://github.com/your-org/your-repo"
      - "--token"
      - "your-token"
      - "--labels"
      - "stable,production"
```

In this example, I added the stable and production labels to the runner. Adjust the labels as needed to suit your specific requirements.

3. Update and apply your deployment configuration as you normally would (e.g., by running `kubectl apply -f your-manifest.yaml`).

After doing this, your runners should be registered with the specified labels, and you can use these labels in your GitHub Actions workflows to target the appropriate runners.

Keep in mind that you should use a different set of labels for your development clusters. This will help you differentiate between stable/production runners and development runners when targeting them in your workflows.

Hope this helps!
