### DISCUSSION TITLE
Private NPM package published via GH Actions is ALWAYS missing dependency when attempting to install

### DISCUSSION THREAD

**Discussion by taylor-lindores-reeves** [community/community#52275] [Actions]
### Select Topic Area

Question

### Body

I am unable to fix this issue whereby I have published an NPM package, but upon installation I am always encountering the following, quite frankly very frustrating, error:

`Couldn't find package "@prisma/client@4.12.0" required by "@digital-speed/types@1.0.31" on the "npm" registry.`

I have spent almost 2 days on this. Please help if you have any experience? For reference, here's the relevant files doing the work to release the package:

**_release-package.yml_**
```
# .github/workflows/release-package.yml
name: on release

on:
    release:
        types: [created]

defaults:
  run:
    working-directory: prisma/

jobs:
    publish-github-registry:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  always-auth: true
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
                  # Defaults to the user or organization that owns the workflow file
                  scope: '@Digital-Speed'
            - run: |
                cat > .npmrc <<EOF
                @digital-speed:registry=https://npm.pkg.github.com
                registry = https://registry.npmjs.org/
                always-auth = false
                //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}
                EOF
            - run: |
                cat > .yarnrc.yml <<EOF
                nodeLinker: node-modules
                preferInteractive: true
                npmRegistries:
                    //npm.pkg.github.com:
                        npmAlwaysAuth: true
                        npmAuthToken: ${{secrets.GITHUB_TOKEN}}
                    //registry.npmjs.org:
                        npmAlwaysAuth: false
                npmRegistryServer: https://registry.npmjs.org/
                npmScopes:
                    digital-speed:
                        npmRegistryServer: https://registry.npmjs.org/
                EOF
            - run: |
                cat > .env <<EOF
                DATABASE_URL="${{secrets.DATABASE_URL}}"
                EOF
            - run: cat .env
            - run: npm cache clean --force
            - run: npm version patch --no-git-tag-version
            - run: dotenv -- npx prisma generate
            - run: yarn install
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

```

**_package.json_**
```
{
  "name": "@digital-speed/types",
  "description": "Generated shared types by Prisma ORM",
  "version": "1.0.30",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "author": "Taylor",
  "scripts": {
    "db:introspect": "dotenv -- prisma introspect",
    "postinstall": "npx prisma@4.12.0 generate && tsc && cp prisma/src/index.d.ts dist/index.d.ts"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/Digital-Speed/types.git",
    "directory": "prisma"
  },
  "bugs": {
    "url": "https://github.com/Digital-Speed/types/issues"
  },
  "homepage": "https://github.com/Digital-Speed/types#readme",
  "publishConfig": {
    "registry": "https://npm.pkg.github.com"
  },
  "dependencies": {
    "@prisma/client": "^4.12.0"
  },
  "devDependencies": {
    "@types/node": "18.11.9",
    "dotenv-cli": "^7.2.1",
    "prisma": "^4.12.0",
    "typescript": "^4.9.0"
  }
}

```
