### DISCUSSION TITLE
Help! Some of my GitHub workflows are stuck in Queued state, how can I fix this?

### DISCUSSION THREAD

**Discussion by ChicKo1108** [community/community#52421] [Actions]
### Select Topic Area

Question

### Body

Hi! I'm experiencing an issue with some of my GitHub workflows: they seem to be stuck in the Queued state, and never actually run. This is strange, because some of my workflows are working just fine, while others are not. I'm not sure what's causing this, and I could use some help troubleshooting this problem.

Here's the content of my .yml file:
```
name: Build Image

on:
  push:
    branches:
      - main

jobs:
  build-dev:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: xxx/feishu-bot@v1
        with:
          uuid: xxxxxx
          text: |
            {"title":"Dashboard开始编译  ${{github.run_id}}"}
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: build-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: npm install, build, and test
        run: |
          yarn
          rm .env.production
          mv .env.sandbox .env.production
          yarn build
        env:
          CI: true
          NPM_CONFIG_USERCONFIG: .npmrc.ci
          NPM_AUTH_TOKEN: ${{ secrets.PKG_TOKEN }}
      - name: deploy
        run: npx static-deploy-tool sync build dev/dashboard -k xxx-s ${{ secrets.DEPLOY_SK }} -b xxx-exxx
      - uses: xxx/feishu-bot@v1
        with:
          uuid: xxxx
          text: |
            {"title":"🎉 Dashboard编译成功 ${{github.run_id}}","text":"<a href=\"https://xxx.xxx.xxx/xxx/\">查看dev沙盒环境</a>, \n<a href=\"xxxl\">部署线上环境</a>(请先在本地执行e2e测试)"}
      - if: ${{ failure() }}
        uses: xxx/feishu-bot@v1
        with:
          uuid: xxx
          text: |
            {"title":"💣 Dashboard编译失败 ${{github.run_id}}","text":"<a href=\"xxx\">查看 Action ${{github.run_id}}</a>"}
```

Thanks in advance for your help!
