### DISCUSSION TITLE
GitHub actions "Re-run failed jobs" does not re-run jobs that depend on failed jobs in matrixed reusable workflows

### DISCUSSION THREAD

**Discussion by nadav13** [community/community#52505] [Actions]
### Select Topic Area

Bug

### Body

When re-running failed jobs in a workflow that runs a reusable workflow in a matrix, Github Actions does not run all failed jobs and their dependents. Instead, only the failed jobs are run.

**To Reproduce**
1. Create the following workflows:
test-workflow.yml
```
name: Test Workflow
on:
  workflow_dispatch:
  push:

jobs:
  first:
    strategy:
      fail-fast: false
      matrix:
        service: ["aaa","bbb"]
    uses: ./.github/workflows/test-workflow-reusable.yml
    secrets: inherit

  second:
    needs: [first]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(needs) }}'
```

test-workflow-reusable.yml
```
name: Test Workflow Reusable
on:
  workflow_call:

jobs:
  first-inner:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  second-inner:
    needs: [first-inner]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(needs) }}'
```

**First run results**
<img width="315" alt="image" src="https://user-images.githubusercontent.com/70900815/231110276-265818fb-2193-4393-9274-ca8816717636.png">

**Expected behavior**
"Re-run failed jobs" is supposed to run the `first-inner` failed jobs, as well as the jobs that depend on them - `second-inner` and `second` (because `first` failed).

**Actual behavior**
Only the failed jobs - `first (aaa) / first-inner` and `first (bbb) / first-inner` - are being re-run, not jobs that depend on it.
<img width="641" alt="image" src="https://user-images.githubusercontent.com/70900815/231107498-2389ad20-e086-4f67-b093-06db929b7795.png">
