### DISCUSSION TITLE
Support for <details> in issue forms?

### DISCUSSION THREAD

**Discussion by castrojo** [community/community#5250] [Projects and Issues] [answered]
I am in the middle of transition our project from issue templates to the newer issue forms. One of the things we like to do is ask people for the version of the tool they're using.

```
 - type: textarea
    id: version
    attributes:
      label: Cloud Custodian version and dependency information
      description: Please run `custodian version --debug` and paste the output here
      render: shell
```

However with lots of tools this leads to verbose output and this would be on the top of every issue filed. So I was thinking something like this: 

      description: Please run `custodian version --debug` and paste the output here
      value: |
          Paste first two lines here
          <details>
          And then the rest here
           </details>

Then I was thinking maybe something cleaner, like if it looked like this: 

```
 - type: textarea
    id: version
    attributes:
      label: Cloud Custodian version and dependency information
      description: Please run `custodian version` and paste the output here
      details: Please run `custodian version --debug` and paste the output here
      render: shell
```

And then anything in the details field would just auto-fold in the issue so that we can have the verbosity but collapsed by default, this would alleviate the need for us to ask users to paste in a gist url, etc.
