### DISCUSSION TITLE
Having trouble restoring a file using actions/cache; am I doing something wrong?

### DISCUSSION THREAD

**Discussion by jacobjove** [community/community#52520] [Actions]
### Select Topic Area

Question

### Body

I have a custom JavaScript action that uses the `saveCache` function from `@actions/cache` to cache a small dotenv file.

My workflow uses my custom action in a job, and then it attempts to restore the file in a subsequent job (which `needs` the first job in which the file is cached). Relevant code:

```
...
  create-dotenv:
    name: Generate .env file
    strategy:
      max-parallel: 2
      matrix:
        app: [my_app]
    environment: ${{ matrix.app }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out main branch
      uses: actions/checkout@v3
    - name: Generate dotenv file
      id: generate-dotenv
      # custom action: https://github.com/iacobfred/generate-dotenv
      uses: iacobfred/generate-dotenv@v0.3.1
      with:
        template-paths: |
          _.env
        output-path: .env
        cache: true
        cache-key: dotenv-${{ matrix.app }}-${{ github.sha }}-${{ github.run_id }}
  build:
    name: Build image
    needs: [create-dotenv]
    strategy:
      max-parallel: 2
      matrix:
        app: [my_app]
    environment: ${{ matrix.app }}
    steps:
    - name: Check out main branch
      uses: actions/checkout@v3
    environment: ${{ matrix.app }}
    steps:
    - name: Check out main branch
      uses: actions/checkout@v3
    - name: Restore dotenv
      uses: actions/cache@v3
      with:
        path: .env
        key: dotenv-${{ matrix.app }}-${{ github.sha }}-${{ github.run_id }}
        # key: ${{ needs.create-dotenv.outputs.cache-key }}
        fail-on-cache-miss: true
```

The `build` job fails every time due to cache miss, despite the file appearing to be cached successfully in `create-dotenv`.

Output from `create-dotenv` (in which the file is cached using the `saveCache` function from `@actions/cache`):
```
/usr/bin/tar --posix -z -cf cache.tgz --exclude cache.tgz -P -C /home/runner/work/shop-platform/shop-platform --files-from manifest.txt
Cache Size: ~0 MB (1467 B)
Cache saved successfully
Saved .env to cache with key: dotenv-my_app-cd1f3ced3aa869717aa007f4b4b7576663f10c27-4662494206
```

Subsequent output from `build`, which attempts to restore the file using `actions/cache` with `fail-on-cache-miss: true`:
```
Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set. Input key: dotenv-my_app-cd1f3ced3aa869717aa007f4b4b7576663f10c27-4662494206
```

I can see that the cache key matches.

While debugging, in the custom action code, I tried using the `restoreCache` function (from `@actions/cache`) immediately after using `saveCache`, and that worked, so the file was indeed cached as indicated by the output from that step. But for some reason, I'm just not able to restore it from cache in a separate job. Am I doing something wrong here? Any ideas?
