### DISCUSSION TITLE
Blog Post Workflow comment tag not working

### DISCUSSION THREAD

**Discussion by Anmol-Baranwal** [community/community#52554] [Actions]
### Select Topic Area

Question

### Body

I cannot correctly implement this [workflow](https://github.com/Anmol-Baranwal/Bookmark-Brigade/blob/main/.github/workflows/daily-dev-bookmarks.yml).

```yml
name: Daily Bookmarks Routine
on:
  # Schedule updates (At minute 0 past every 24th hour)
  schedule: [{ cron: "0 */24 * * *" }]
  # Lines below let you run workflow manually with each commit
  workflow_dispatch:
  push: { branches: ["master", "main","hack"] }
jobs:
  # refer this: https://github.com/gautamkrishnar/blog-post-workflow
  daily-dev-bookmarks:
    name: Update README with latest bookmarks from daily.dev # https://app.daily.dev/Anmol-Baranwal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          gh_token: ${{ secrets.BLOG_POST }}
          commit_message: "docs: add latest bookmarks"
          feed_list: "https://api.daily.dev/rss/b/844d728f-ff3b-49e2-b99a-49c96ea256ce"
          committer_username: "bookmark-buddy"
```

Refer to [blog post workflow](https://github.com/gautamkrishnar/blog-post-workflow).

Problem: I cannot use it properly. There is always an [error](https://github.com/Anmol-Baranwal/Bookmark-Brigade/actions/runs/4671369704/jobs/8272264748).

Please resolve this issue. I have even added repo token to resolve the permission issue, but it didn't work out.
