### DISCUSSION TITLE
More details on "Checkboxes must have unique labels" error message

### DISCUSSION THREAD

**Discussion by howardjohn** [community/community#5256] [Projects and Issues]
My config:

```
  - type: checkboxes
    id: area
    attributes:
      label: Affected product area
      options:
      - label: "Docs"
      - label: "Installation"
      - label: "Security"
  - type: checkboxes
    id: security
    attributes:
      label: Is this the right place to submit this?
      options:
        - label: "This is not a security vulnerability"
          required: true
```

I got error message "Checkboxes must have unique labels". This was not easy to debug, because:
* It didn't say which label was not unique, nor what section it appeared in
* The conflict is between `Security and `security`. Its not obvious its case insensitive
* Its not obvious that `id` and `label` are correlated in any way
