### DISCUSSION TITLE
Tasks and Checklist Forms give conflicting user experience

### DISCUSSION THREAD

**Discussion by howardjohn** [community/community#5257] [Projects and Issues]
We want users to identify the category of their issue. We use the following config:
```
  - type: checkboxes
    id: area
    attributes:
      label: Affected product area
      options:
      - label: "Docs"
      - label: "Installation"
      - label: "Networking"
      - label: "Performance and Scalability"
      - label: "Extensions and Telemetry"
      - label: "Security"
      - label: "Test and Release"
      - label: "User Experience"
      - label: "Developer Infrastructure"
      - label: "Upgrade"
```

We then have some tooling that takes these and inserts some labels for us to query, etc. 

Another example is we want users to explicitly state they are NOT filing a CVE in the public:
```yaml
  - type: checkboxes
    id: security
    attributes:
      label: Is this the right place to submit this?
      options:
        - label: "This is not a security vulnerability"
          required: true
```

The issue with this is that the checklist conveniently turns into a task list, and says X/Y tasks are completed. This doesn't really make sense in these contexts.

Possible fixes:
* (For CVE check only) allow having check boxes that do not write the result to issue (this only make sense for required=true)
* Add a more comprehensive way to get labels added to an issue. Strawman is to specify a set of allowed labels users can add to new issues (but not give them permission to modify labels on existing issues, access all labels, etc). 
* Provide a way to have check boxes without the X/Y tasks popup
