### DISCUSSION TITLE
Workflow not running on push

### DISCUSSION THREAD

**Discussion by goeyzai** [community/community#52593] [Actions] [answered]
### Select Topic Area

Question

### Body

```
name: Deploy to Alpha

on:
  push:
    branches:
      - alpha

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Workflow is running!"
```
The above workflow didnt trigger when I push commit to alpha branch. Anyone can help?
