### DISCUSSION TITLE
.bat file not updated in github actions

### DISCUSSION THREAD

**Discussion by AdrienSchadle** [community/community#52632] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hello,

It seems that the github actions run an old version of a .bat file. To be sure, I added a log at the beginning of my .bat file but nothing is written with github actions. On my computer same .bat file writes the log. 

In an action, github actions display the content of the .bat file and as I thought, it is not updated. Why ? 

Is it a feature I don't know ? How to force github actions to use the last version of the .bat file ?

My repository is "b-com-software-basis/xpcf" and one of the .bat file is b-com-software-basis/xpcf/scripts/win/build_xpcf.bat.

**Comment by airtower-luna** [comment, marked as answer]
Your problem is [here](https://github.com/b-com-software-basis/xpcf/blob/6a12837b4e0312199710c24d6791a8ed81b0d2eb/.github/workflows/test_dev.yml#L77-L81):

```yaml
      - run: git clone https://github.com/b-com-software-basis/xpcf.git
      - working-directory: ./xpcf
        run: git submodule init
      - working-directory: ./xpcf
        run: git submodule update
```

What you're retrieving there is the *default branch* of the repository, not the commit that triggered the `push` event for which your workflow is running.

You should use [`actions/checkout`](https://github.com/actions/checkout) instead, it'll get the code for which your workflow is running by default:

```yaml
- uses: actions/checkout@v3
  with:
    submodules: 'recursive'
```

That'll place the repository files in the workspace directory (use the `path` parameter if you want it elsewhere), deleting anything that might already be there. Usually it's the first step in a job.

Of course you could alternatively use `git checkout` to retrieve the right commit, but it's much easier using the purpose-made tool. :wink:
