### DISCUSSION TITLE
Include workflow validity in commit status checks

### DISCUSSION THREAD

**Discussion by cmbuckley** [community/community#52661] [Actions]
### Select Topic Area

Product Feedback

### Body

The commit status currently takes into account the validity of certain files, for instance `dependabot.yml`:

<img width="504" alt="dependabot" src="https://user-images.githubusercontent.com/80938/231570923-8ab3014d-cdf0-49f8-b311-77501769a2dc.png">

It would be great if workflow file validity could also be included in these status checks. The reason I suggest this is I had a workflow similar to the following:

```yml
name: Push
on: push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo test
  two:
    needs: one
    runs-on: ubuntu-latest
    strategy:
      matrix:
        broken: ${{ needs.one.outputs.missing }}
    steps:
      - name: Output
        run: echo ${{ matrix.broken }}
```

Statically, this workflow appears valid, but at runtime this fails because the matrix vector evaluates to empty. However, because step `one` ran successfully, all checks that _did_ run passed, so the commit receives a `success` status.

I’m proposing that if the workflow file is invalid, either statically or determined during execution, it should result in a failing build - and might look something like this:

<img width="504" alt="workflow" src="https://user-images.githubusercontent.com/80938/227592418-66280df2-676e-4e51-b94d-0e98a457820c.png">
