### DISCUSSION TITLE
Sharing the GITHUB_TOKEN in a reusable workflow

### DISCUSSION THREAD

**Discussion by johnament** [community/community#52665] [Actions]
### Actions - Secrets

Question

### Body

I have a reusable workflow that for all intents and purposes just does a `gh pr edit` to add some text to the description to enforce some naming conventions.  To do that, I was planning to use a secret from the parent repo that represents `github.token` for the PR that was created to update the title.  This doesn't seem to work, giving back an error `GraphQL: Resource not accessible by integration (repository.pullRequests.nodes.0.projectCards.nodes)`.  This implies that the token doesn't have write permission on the PR, even though in the parent repo when defining the permissions for the token it requests `pull-requests: write`.  Is something more required to make an action like this work?  This is what the step looks like:

```
      env:
        GH_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
      run: |
        gh pr edit ${{ inputs.BRANCH_NAME }} --title '${{ env.NEW_TITLE }} --repo ${{ env.TARGET_REPO }}
```
