### DISCUSSION TITLE
Is there a way to make Matrix definitions reusable?

### DISCUSSION THREAD

**Discussion by Fitzbert-Fitz** [community/community#52693] [Actions] [answered]
### Select Topic Area

Question

### Body

Assuming I have follwoing structure:
```yaml
job A:
  strategy:
    matrix:
      projects:
        - project-name: project1 
          key1: value1
          key2: value2
        - project-name: project2 
          key1: value1
          key2: value2
  do-stuff: ....

job B:
  strategy:
    matrix:
      projects:
        - project-name: project1 
          key1: value1
          key2: value2
        - project-name: project2 
          key1: value1
          key2: value2
  do-stuff: ....
```

this will run Jobs A & B for both projects. Further I do not want to merge these jobs. 
You can see that the matrix definiton is a config duplication. I would like to avoid that similar to the example below. The issue is, that the example is not working, since env does not take objects. Is there a known solution? I did not find anything.
```yaml
env:
  projects:
  - project-name: project1 
    key1: value1
    key2: value2
  - project-name: project2 
    key1: value1
    key2: value2
job A:
  strategy:
    matrix:
      projects:
        ${{ env.projects }}
  do-stuff: ....

job B:
  strategy:
    matrix:
      projects:
        ${{ env.projects }}
  do-stuff: ....
```
