### DISCUSSION TITLE
Can steps be used in a github-script script?

### DISCUSSION THREAD

**Discussion by Nessaek** [community/community#52707] [Actions]
### Select Topic Area

Question

### Body

Hi there,
I have a github-script action that runs a .js file like so:

```js
module.exports = async ({github, context}) => {
return steps.validate.outcome }
```

This is then used in my github workflow:

```yml
    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const script = require('./scripts/update.js')
          await script({github, context})

```

However, I always get an error that steps are undefined.  Is there a way of using them in the .js file?
