### DISCUSSION TITLE
GitHub-hosted actions runner returns Segmentation fault (core dumped) error Command failed with exit code 139

### DISCUSSION THREAD

**Discussion by adityabraj** [community/community#52715] [Actions]
GitHub Actions, github-hosted ubuntu-latest runner, Docker build, yarn build

Question

### Body

GitHub-hosted actions runner returns Segmentation fault (core dumped) error Command failed with exit code 139 while docker build at yarn build command. I have tried the same Dockerfile on multiple other hosts and builds fine. On GitHub actions itself I've tried with ubuntu-latest and ubuntu-20.04 github-hosted runners. I've tried it with github marketplace actions for setting up QEMU, buildx and docker build-push. I've also tried it by manually running commands on the ubuntu runner to setup QEMU, buildx and docker build-push.

**The code commented out is using the github marketplace actions/modules**
```
name: Production Image Build and Push
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: ************
  ECR_URL_PREFIX: https://ap-south-1.console.aws.amazon.com/ecr/repositories/***********

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::*********:role/*********
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2

#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@master

#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-
          
      - run: |
          sudo apt-get install qemu
          sudo apt-get install qemu-user-static
          
      - run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx inspect --bootstrap
          export DOCKER_BUILDKIT=1


      - name: Build Docker image
        id: build-push
        run: |
          docker buildx build \
               --platform linux/arm64 \
               --push \
               --tag ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY  }}:latest \
               --build-arg NEXT_PUBLIC_GTM_CODE=******** \
               .
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          builder: ${{ steps.buildx.outputs.name }}
#          platforms: linux/arm64
#          push: true
#          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY  }}:latest
#          #cache-from: type=local,src=/tmp/.buildx-cache-latest
#          #cache-to: type=local,dest=/tmp/.buildx-cache-new
#          build-args: |
#            NEXT_PUBLIC_GTM_CODE=********

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache 
```
This is the Dockerfile

```
FROM node:16.14.0-slim

WORKDIR /home/node/www

ENV AWS_ACCESS_KEY_ID "************"
ENV AWS_SECRET_ACCESS_KEY "**********************"
ENV AWS_DEFAULT_REGION "ap-south-1"

RUN chown -R node:node /home/node/www

# Install deps
RUN apt-get -y update
RUN apt-get -y install curl unzip build-essential

WORKDIR /tmp
RUN  if [ $(arch) = 'aarch64' ] ; then curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"  ; else curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; fi

RUN unzip /tmp/awscliv2.zip && \
    ./aws/install

WORKDIR /opt/www

COPY ./package*.json ./
# COPY ./yarn.lock ./

# Log in to AWS Code Artifact for access to private npm registry
RUN yarn co:login
RUN yarn --network-timeout 1000000

COPY ./ ./


ARG NEXT_PUBLIC_GTM_CODE

RUN env


RUN rm -f *.env*
RUN NEXT_PUBLIC_GTM_CODE=${NEXT_PUBLIC_GTM_CODE} 

RUN yarn build

ENV NODE_ENV=production


EXPOSE 3011
ENV PORT 3011

# Learn more here: https://nextjs.org/telemetry
ENV NEXT_TELEMETRY_DISABLED 1



CMD ["yarn", "start"]
```
