### DISCUSSION TITLE
Allow auto variables & secrets parsing from environment

### DISCUSSION THREAD

**Discussion by bormando** [community/community#52756] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi,

I find it useful to create an environment and fill it with variables/secrets. But it's absolutely uncomfortable for me to specify what vars/secrets I'd like to get from the environment, i.e.:

```
e2e-tests:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      TOKEN: ${{ secrets.TOKEN }}
```

See? My **Staging** environment contains values for vars/secrets but I have to define them in `env` block.

Now imagine if you've got 20+ vars/secrets - looks pretty messy!

My idea is - it'd be great if we could just specify environment like this:

```
environment: Staging
```

And that's it! What do you think? Consider it as a **feature request**.
