### DISCUSSION TITLE
Command runs when `if` gets false conditions

### DISCUSSION THREAD

**Discussion by yusancky** [community/community#52771] [Actions] [answered]
### Select Topic Area

Bug

### Body

```yaml
    - name: Configure filenames (Linux)
      run: |
        echo "typst_zip_name=unknown-linux-gnu" >> $GITHUB_ENV
        echo "typst_zip_extend=tar.gz" >> $GITHUB_ENV
      shell: bash
      if: ${{ runner.os }} == 'Linux'

    - name: Configure filenames (Windows)
      run: |
        echo "typst_zip_name=pc-windows-msvc" >> $GITHUB_ENV
        echo "typst_zip_extend=zip" >> $GITHUB_ENV
      shell: bash
      if: ${{ runner.os }} == 'Windows'

    - name: Configure filenames (macOS)
      run: |
        echo "typst_zip_name=apple-darwin" >> $GITHUB_ENV
        echo "typst_zip_extend=tar.gz" >> $GITHUB_ENV
      shell: bash
      if: ${{ runner.os }} == 'macOS'
```

I have made some changes to the [example provided in this GitHub Docs](https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system). Obviously, when I ran it with `windows-latest`, I was expecting the second case. Unfortunately, it turned out to be the third case.

I think this was probably overwritten, meaning that all three were considered correct.

I checked the Debug log and the relevant content can be found at https://github.com/yusancky/setup-typst-examples/actions/runs/4695424992/jobs/8324660009#step:3:37. Indeed, all three get `true`. What do I need to change?
