### DISCUSSION TITLE
Unable to access GHCR despite GITHUB_TOKEN having enough permissions

### DISCUSSION THREAD

**Discussion by aurecchia** [community/community#52814] [Actions]
### Select Topic Area

Bug

### Body

Hi,

I have just encountered a weird situation that I'm pretty sure is some sort of bug with permissions when using service containers.

I am setting up a new workflow that runs some tests against a database. The database is spun up as a service container using a _custom image_ that lives in the GitHub Container Registry. The repository where the workflow runs has been allowed to read the package, and **the repository is set up to grant read and write permissions to the `GITHUB_TOKEN`**. The `service` block has the credentials section to authenticate:

```yml
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/dotnet/sdk:6.0

    services:
      postgres:
        image: ghcr.io/valora-digital/custom-postgres-14:latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    ...
```

With this setup, the action run fails with "Error response from daemon: denied" when trying to start the container.

By adding the following `permissions` block to the job, the container can be started successfully.

```yml
    permissions:
      contents: read
      packages: read
```

What is confusing, and the reason why I suspect there might be some kind of bug, is that the `GITHUB_TOKEN` should already have those permissions (as per the repository's settings), and that is confirmed by the logs.

In the "Set up job" section of the **failing run**, the token has the following permissions:
   
    GITHUB_TOKEN Permissions
      Actions: write
      Checks: write
      Contents: write
      Deployments: write
      Discussions: write
      Issues: write
      Metadata: read
      Packages: write
      Pages: write
      PullRequests: write
      RepositoryProjects: write
      SecurityEvents: write
      Statuses: write

whereas in the **successful run**, it has fewer permissions, only has those requested explicitly:

    GITHUB_TOKEN Permissions
      Contents: read
      Metadata: read
      Packages: read

I have double-checked my tests, and I am able to re-produce the issue just by commenting out the `permissions` block.

Am I missing something, or is this actually a bug?

Thanks for any clarifications
