### DISCUSSION TITLE
How do i create an issue_template with a dropdown that can add labels/tags?

### DISCUSSION THREAD

**Discussion by Omzig** [community/community#52824] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I want to add a bug issue_template yaml file that allows my customers to pick the bug severity. 

- Low
- High
- Critical
- Visual
- Content

from the documentation i cannot figure out how to add things to the labels array via a dropdown:
```yaml
name: Bug report 🐛
description: Create a bug report
labels: bug,requires triage
body:
- type: dropdown
  id: Severity
  attributes:
    label: Severity
    description: What severity of the bug? (this should add a tag, not an additional section to the body of the issue)
    options:
      - Low
      - High
      - Critical
  validations:
    required: true
- type: textarea
  attributes:
   label: Steps to Reproduce
   description: > 
      List of steps, sample code, failing test or link to a project that reproduces the behavior.
      Make sure you place a stack trace inside a code (```) block to avoid linking unrelated issues.
   placeholder: >
      I am experiencing a problem with X.
      I think Y should be happening but Z is actually happening.
  validations:
     required: true
```
