### DISCUSSION TITLE
One big job with one setup and multiple steps vs multiple jobs with less steps ( parallel )

### DISCUSSION THREAD

**Discussion by jtuchel** [community/community#52927] [Actions]
### Select Topic Area

Question

### Body

I have a Monorepo ( Turborepo ) containing multiple apps and pacakges based on Node/JavaScript and want to perform multiple checks on pull requests

- check the code ( linting + formatting )
- run tests
- build the apps
- ...

Given the following sample workflow

```yaml
name: QA on pull request

on: pull_request

jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

  build_apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
```

All the jobs are running in parallel. But they all have to make a new setup... I could also use one big job and call them sequentially.

This might be faster because I don't need a setup x times. But it might be slower because they are not running in parallel... 

Are there any guides for this?
Thanks for help!

**Comment by airtower-luna** [comment]
> This might be faster because I don't need a setup x times. But it might be slower because they are not running in parallel...

There are a bunch of tradeoffs that you'll have to decide for yourself:

* In real time, parallel jobs are likely to be (marginally) faster, because the respective steps after `npm install` don't wait for each other. How much of a difference it really is depends on your code.
* In CPU (and billable) time, one job is going to be faster, because you get rid of a lot of duplication.
* In terms of reporting separate jobs might be nicer because you get a check for each job. Personally I don't think it's worth it, a [job summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) is almost as nice at lower cost.

Over all, I'd recommend a single job in this situation for efficiency.

Another opportunity to save time & energy is here:

```yaml
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

I don't see anything in your jobs that'd need the repository history. If you remove the `fetch-depth` parameter (or set it to the default of `1`), `actions/checkout` will only fetch the latest commit. Depending on how big your repository history is that can save a *lot*.
