### DISCUSSION TITLE
How to trigger a workflow when a repo is created from a template

### DISCUSSION THREAD

**Discussion by plastikfan** [community/community#52965] [Actions] [answered]
### Select Topic Area

Question

### Body

I have looked at the list of events documented in [events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#watch) and none of these seem to be appropriate for what I need.

I have defined a golang template repo that is designed to enable a user to quickly create a cli app with various features without going through the laborious process of implementing boilerplate functionality. Currently when the template is instantiated into a new repo, there are multiple references in the new repo that need to be modified. To ease this process, I have also defined various shell functions (zsh/bash) that perform these updates. But it is still a manual process. I had the idea of automating this via an event so that when the instantiation occurs, the script could be invoked. (Clearly, the event should only be triggered in the new repo, not the template). This means that when the use clones the repo, it is ready to work on immediately. Is there a way to do this? Perhaps even via a web hook? If not, I'll try and raise a feature request to get a new event defined.

Thanks.

**Comment by airtower-luna** [comment, marked as answer]
Looking at how the [GitHub Skills templates do it](https://github.com/skills/communicate-using-markdown/blob/5d2ce972a65be94b5df492e6af6d5920f68509b7/.github/workflows/0-start.yml): They use the `push` event, with one job that checks if the push is actually the one on repository creation, and another that runs only if that first job confirmed it is. You could do something similar, and recommend people delete the workflow after.

**Reply by plastikfan** [reply]
Thanks @airtower-luna, that looks like a really good resource that I've never heard of and I'll continue my research there. I haven't fully read it yet, but the last point you bring up by recommending users delete the workflow, I think I could automate that part too, simply by implementing a self destruct (ie delete the workflow file) in the workflow itself, so the user would be none the wiser as to what's happened, they would have no interest in this. Thanks again.

**Comment by plastikfan** [comment]
Just for documentation purposes, I'm posting how I fixed this issue with the info gleaned from the [GitHub Skills templates do it](https://github.com/skills/communicate-using-markdown/blob/5d2ce972a65be94b5df492e6af6d5920f68509b7/.github/workflows/0-start.yml):

```yml
name: Initialise Repo
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  run-script:
    name: run script

    # We will only run this action when this repository isn't the
    # template repository
    #
    if: >-
      ${{ !github.event.repository.is_template }}

    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_EMAIL}"
        shell: bash

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script
        run: |
          . ./scripts/create-version-file.sh
          create-version-file

      # TODO: delete this workflow file

      - name: Add files and commit changes
        run: |
          git add .
          git commit -m "Automated changes"
          git push -u origin master
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

The script invoked, ___create-version-file___ simply creates an initial VERSION file, which is checked in by the subsequent steps.

I suppose the only thing I could do to improve the workflow would be to find a way to get the branch name dynamically, as it is currently hardcoded to master, which clearly wont work if the default branch is main.
