### DISCUSSION TITLE
Github workflow not triggered when release is edited

### DISCUSSION THREAD

**Discussion by grzegorzkrukowski** [community/community#53137] [Actions]
### Select Topic Area

Bug

### Body

It seems that the workflow is never triggered when editing the release:

```
name: Release - Edited

on:
  release:
    types: [published, edited]

jobs:
  fail_test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Build
        id: build
        run: echo "Build"
```

I tried editing pre-release and latest release (non-drafts) and it's never triggering this workflow.
It only works for `published` event type.

**Comment by sebaaaz** [comment]
hi, is there any update about this?

**Comment by itsjusth** [comment]
I am also experiencing an issue with the "edited" trigger in Pull Requests.  The user is meant to edit the PR body to add a link to the Work Item number in Azure DevOps.  When they save that edit, I expect the workflow to be triggered.  Instead, the user must trigger the flow manually.

``` yaml
name: 'Description contains AB# with a valid work item id'
on: # rebuild any PRs for main branch changes
  workflow_call:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - master
      - main
      - 'release/**'
      - 'hotfix/**'
jobs:
  create-edit-comment:
    name: AzDOWorkItemRequired
    runs-on: ubuntu-latest
    steps:
      - uses: my-org-name/.github/actions/azure-boards-pr-check@master
```
