### DISCUSSION TITLE
How to run screen linux command with github actions?

### DISCUSSION THREAD

**Discussion by mihalt** [community/community#53141] [Actions]
### Select Topic Area

Question

### Body

Hi! I try to use this config to run django command and it even doesn't start to run on server. In the time, when in my repository Actions section it is shown as completed. 

```
on:
  push:
    branches: [ "production" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update_db_by_messages:
      runs-on: self-hosted
      steps:
        - name: Smoke Test
          if: github.event.schedule == '* * * * 0'
          run: screen -Ldm -c /var/www/project_name python3 manage.py update_messages
```
