### DISCUSSION TITLE
Serverless commands fail to resolve nested variables when using `inputs` inside a composite action or reusable workflow

### DISCUSSION THREAD

**Discussion by ezmiller** [community/community#53167] [Actions]
### Select Topic Area

Question

### Body

I have a Github composite action that uses the Serverless Framework to deploy my stack. The action takes two inputs, `serverless-path` and `stage`, and includes the following steps:

```
inputs:
  serverless-path:
    description: 'The relative path to the project root.'
    type: string
    required: true
  stage:
    description: 'The serverless deployment stage to use.'
    type: string
    required: true
    default: 'dev'
  otherArgs:
    description: 'Additional arguments to provide to the serverless deploy command.'
    type: string
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16.13.0'
        cache: yarn

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: *** 

    - name: Install project dependencies
      shell: bash
      run: yarn install --frozen-lockfile
      working-directory: ${{ inputs.serverless-path }}

    - name: debug step
      shell: bash
      run: yarn run serverless print --stage ${STAGE}
      working-directory: ${{ inputs.serverless-path }}
      env:
        STAGE: ${{ inputs.stage }} 
```

However, when I run this action, the serverless command fails with the following error:

```
Run yarn serverless print --stage ${STAGE}
  yarn serverless print --stage ${STAGE}
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_PKG_AUTH_TOKEN: ***
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    STAGE: dev​
yarn run v1.22.19
$ /home/runner/work/***/***/node_modules/.bin/serverless print --stage dev​
Environment: linux, node 16.13.0, framework 3.19.0 (local), plugin 6.2.2, SDK 4.3.2
Error:
Docs:        docs.serverless.com
Cannot resolve serverless.yml: Variables resolution errored with:
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

  - Cannot resolve variable at "provider.environment.SHOP": Value not found at "self" source
error Command failed with exit code 1.
```

Interestingly, if I replace `${{ inputs.stage }}` with a static string like `dev`, the serverless command runs successfully. This makes me suspect that the problem has to do with how inputs are passed to the serverless command. 

Also this _only_ happens using `inputs` within a composite action or a reusable workflow. When I call the same command feeding it `{{ matrix.stage }}` where the values of stage are `dev`, `qa`, `prod`. The command runs without error. 

What could be causing this error and how can I fix it?

Some additional debugging information. I tried a couple things to test that the value of `${{inputs.stage}}` is valid.

 1. I simply did an `echo '${{ inputs.stage }}'` above the place where I run the command in the github action. Teh output looked correct:
```
Run echo 'dev​'
  echo 'dev​'
  shell: /usr/bin/bash -e {0}
  ...
dev​
```
2. I also tried an experiment commenting out the offending line with the nested variable expression in my serverless.yml, and then just added a few env definitions that pull the stage value in a number of ways:
```
provider: 
  ...
  environment:
    CUSTOM_STAGE: ${self:custom.stage}
    OPT_STAGE: ${opt:stage}
    SLS_STAGE: ${sls:stage}
    # SHOP: ${self:custom.environment.${self:custom.stage}.SHOP}
...
custom:
  stage: ${opt:stage, 'default'}
```
When I ran this, the `sls print` command actually executes without error, and the stage definnitions are all as expected, i.e. they pick up the `dev` value from `inputs.stage`:
```
provider:
  ...
  CUSTOM_STAGE: dev
  OPT_STAGE: dev
  SLS_STAGE: dev
```
So it seems as though the value is actually making it into the serverless variable resolution process, but somehow when nested variables are involved, and the value is taking from Github 's `inputs`, it blows up...
