### DISCUSSION TITLE
Job doesn't trigger when commenting on pull request

### DISCUSSION THREAD

**Discussion by esonhey** [community/community#53207] [Actions]
### Select Topic Area

Bug

### Body

I have trouble making my job run when `issue_comment` event happens

minimal setup 
```yml
name: Lint files and run tests

on: issue_comment

jobs:
  run-linters-and-cypress:
    # if: github.event.issue.pull_request && contains(github.event.comment.body, '/ok-to-test')
    runs-on: ubuntu-latest
```

my job used to work properly when having 
```yml
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [review_requested]
```
 my original problem was that I didn't want to trigger job twice as I assign two persons for review request
 is there anyway that I only let the job run only once on a commit?
