### DISCUSSION TITLE
GithubActions - using functions in run-name

### DISCUSSION THREAD

**Discussion by funes79** [community/community#53309] [Actions] [answered]
### Select Topic Area

Product Feedback

### Body

Hi, it seems that in github actions workflows currently this (using replace function in curly bracket placeholders) is not supported:

```
name: Manual test

on: 
  workflow_dispatch:
    inputs:  
      something:
        required: true
        type: string
        description: "Some input"

run-name: Manual run of ${{ inputs.something }} on  ${{ replace(github.event.ref, 'refs/heads/', '') }} by @${{ github.actor }}

```

Is there any plan to support it? Or is there any other way to do a string replacement? thanks
