### DISCUSSION TITLE
Github Workflow jobs are split into two groups in Summary view

### DISCUSSION THREAD

**Discussion by sheharyarn** [community/community#53564] [Actions]
### Select Topic Area

Question

### Body

Hi, I'm trying to improve my Github actions skills, and I'm currently writing an advanced workflow (composed of smaller reusable workflows) to deploy a test app to production. As part of that, this is what I'm doing:

 - **Run CI jobs in parallel**
   - Run Lint
   - Run Unit Tests
   - Run E2E Tests
 - **Request Approval from codeowners**
   - Wait for approval using [`trstringer/manual-approval`](https://github.com/marketplace/actions/manual-workflow-approval)
 - **Deploy App**
   - Build and deploy docker image to hosting service

Now the entire workflow does actually work as expected, following all the steps in the right order.

# My Issue

_My issue is that three jobs in the first `CI` workflow are split into two groups in the "Summary" view, when it should have just been one group:_

| Sidebar | Summary Diagram |
|--------|--------|
| <img width="200" alt="image" src="https://user-images.githubusercontent.com/2355108/233867944-e0881694-7b8d-4609-ae1a-9f2ff3d3dbe9.png">  | <img width="700" alt="image" src="https://user-images.githubusercontent.com/2355108/233867226-e22bc216-9722-4de5-bac3-6c9f5d838502.png"> | 

In the summary screenshot above, the `test:e2e` job is shown in a separate group/box for some reason, when it should have been in the box with the other two `CI` jobs. But in the sidebar screenshot, they are still grouped together.

# Code Organization

I have two repos with actions, organized as follows (click to view details):

<details>
  <summary><h3>Repo 1: <code>testorg/devops</code></h3></summary>

 - This repo is for common workflows that I want to share across multiple projects
 - It currently has two workflows:
   - `request-approval`
   - `deploy`
 - Both workflows work as expected without issues
</details>
<details>
  <summary><h3>Repo 2: <code>testorg/myapp</code></h3></summary>

 - This is the app that I am trying to setup CI/CD for production
 - This app uses both of the shared workflows from `testorg/devops`
 - It currently has three workflows:
   - `ci`
     - This workflow is run automatically on every PR
     - It defines the `lint`, `test:unit`, and `test:e2e` jobs
   - `deploy-stage`
     - It is run automatically on every commit on the `main` branch
     - It uses the `ci` workflow above, followed by the `deploy` workflow from devops
   - `deploy-prod`
     - It can only be run manually using `workflow_dispatch`
     - It uses the `ci` workflow above, followed by `request-approval` and `deploy` workflows from devops
   - Both deployment workflows face the same problem but it does not happen in the `ci` workflow. 
</details>

<br />

| CI Workflow | Deploy Staging Workflow |
|--------|--------|
| <img width="300" alt="image" src="https://user-images.githubusercontent.com/2355108/233868649-04bea1c2-f156-40cc-973e-51eb45dc85e6.png"> | <img width="500" alt="image" src="https://user-images.githubusercontent.com/2355108/233868667-f5b5f79e-933d-42b1-8547-06ffee5e7e87.png"> | 

# Workflow Code

As a minimal example here, I will focus on the `ci` and `deploy-stage` workflows since they are all we need to reproduce the issue (click to view details):

<details>
  <summary><h3><code>myapp/deploy-stage.yml</code></h3></summary>
  
  ```yaml
  name: Deploy Staging
  
  on:
    workflow_dispatch:
    push:
      branches: [ 'main' ]
  
  jobs:
    ci:
      name: CI
      uses: ./.github/workflows/ci.yml
  
    deploy:
      name: Deploy to Staging
      needs: ci
      uses: testorg/devops/.github/workflows/deploy.yml@main
      with:
        APP_ENV: stage
      secrets: inherit
  ```
</details>

<details>
  <summary><h3><code>myapp/ci.yml</code></h3></summary>
  
  ```yaml
  name: CI
  
  
  on:
    workflow_call:
    pull_request:
      branches: [ 'main' ]
  
  
  env:
    NODE_VERSION: '18.6.0'
    DB_NAME: app_test
    DB_USER: postgres
    DB_PASS: postgres
  
  
  
  jobs:
  
    lint:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ env.NODE_VERSION }}
            cache: 'yarn'
  
        - name: Install Dependencies
          run: yarn install --frozen-lockfile
  
        - name: Run Linter
          run: yarn lint
  
  
    unit_tests:
      name: test:unit
      runs-on: ubuntu-latest
  
      services:
        postgres:
          image: postgres
          env:
            POSTGRES_DB: ${{ env.DB_NAME }}
            POSTGRES_USER: ${{ env.DB_USER }}
            POSTGRES_PASSWORD: ${{ env.DB_PASS }}
          ports:
            - 5432:5432
  
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ env.NODE_VERSION }}
            cache: 'yarn'
  
        - name: Install Dependencies
          run: yarn install --frozen-lockfile
  
        - name: Run Unit Tests
          run: yarn test:unit
  
  
    e2e_tests:
      name: test:e2e
      runs-on: ubuntu-latest
  
      services:
        postgres:
          image: postgres
          env:
            POSTGRES_DB: ${{ env.DB_NAME }}
            POSTGRES_USER: ${{ env.DB_USER }}
            POSTGRES_PASSWORD: ${{ env.DB_PASS }}
          ports:
            - 5432:5432
  
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ env.NODE_VERSION }}
            cache: 'yarn'
  
        - name: Install Dependencies
          run: yarn install --frozen-lockfile
  
        - name: Run E2E Tests
          run: yarn test:e2e

  ```
</details>

<br/>

Here's the code for other workflows:

<details>
  <summary><h3><code>devops/deploy.yml</code></h3></summary>
  
  ```yaml
  name: Deploy to Fly.io
  
  on:
    workflow_call:
      inputs:
        APP_ENV:
          required: true
          type: string
      secrets:
        FLY_API_TOKEN:
          required: true
  
  env:
    APP_ENV: ${{ inputs.APP_ENV }}
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  
  jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: fly deploy --remote-only
  ```
</details>

<details>
  <summary><h3><code>devops/request-approval.yml</code></h3></summary>
  
  ```yaml
  name: Request Approval
  
  on:
    workflow_call:

  jobs:
    request:
      name: Request
      runs-on: ubuntu-latest
  
      steps:
        - name: Wait for approval
          uses: trstringer/manual-approval@v1
          timeout-minutes: 60
          with:
            approvers: user1,user2,user3
            minimum-approvals: 1
            issue-title: "🚀"
            issue-body: |
              New production deployment requested by @${{ github.triggering_actor }}.
  ```
</details>
