### DISCUSSION TITLE
Build Dockerfile success on local machine but failed on github actions/

### DISCUSSION THREAD

**Discussion by longtt2705** [community/community#53593] [Actions]
### Select Topic Area

Question

### Body

My application depends on a private repository. Here is it in the package.json:
```
"dependencies": {
   ...
    "protobuf": "git://github.com/xxx/protobuf",
    ...
 }
```
I want to install and built the project into docker image. I used this command: `docker build -t service --build-arg ACCESS_TOKEN=token . ` and it worked totally fine. Here is my Dockerfile:
```
FROM node:18-alpine

ARG ACCESS_TOKEN

USER root

# Install Git
RUN apk update && apk add git

# Add the keys and set permissions
RUN git config --global url."https://${ACCESS_TOKEN}@github.com/".insteadOf git://github.com/

WORKDIR /app/

COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./
COPY ./ ./


RUN yarn install --frozen-lockfile
RUN yarn prisma generate
RUN yarn build

EXPOSE 8100

CMD yarn start

```

But when it is built in the workflow of github action, when yarn trying to fetch the package, I got this error:
```
#13 6.038 [2/4] Fetching packages...
#13 9.959 error Command failed.
#13 9.959 Exit code: 128
#13 9.959 Command: git
#13 9.959 Arguments: ls-remote --tags --heads git://github.com/xxx/protobuf
#13 9.959 Directory: /app
#13 9.959 Output:
#13 9.959 remote: Repository not found.
#13 9.959 fatal: repository 'https://github.com/xxx/protobuf/' not found
#13 9.959 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Here is my github action pipeline:

// pipeline.yml
```
name: Root pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      GITHUB_PACKAGE_REPO_NAME: service
    secrets: inherit
```
// build.yml
```
name: Build & push image

on:
  workflow_call:
    inputs:
      GITHUB_PACKAGE_REPO_NAME:
        required: true
        type: string

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Github Packages
        uses: docker/login-action@abcxyz
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add VERSION_LABEL with commit short sha
        run: echo "VERSION_LABEL=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        
        with:
          context: .
          push: true
          tags: ghcr.io/xxx/${{ inputs.GITHUB_PACKAGE_REPO_NAME }}:${{ env.VERSION_LABEL }}
          build-args: |
            ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
```

I tried to create a PAT with full permissions but nothing changed. Can anyone help me?
