### DISCUSSION TITLE
Feature request: add succesful and failed to the workflow_run types

### DISCUSSION THREAD

**Discussion by erikologic** [community/community#53617] [Actions]
### Select Topic Area

Product Feedback

### Body

```
AS A lazy dev
I WANT TO only filter `workflow_run`s that were of `type` `succesfull`
SO THAT I don't have to redeclare `if: ${{ github.event.workflow_run.conclusion == 'success' }}` in each job 
```

Seems quite straightforward to me.  
My suggestion would be to leak all the workflow runs status as defined in here: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-required-workflow
e.g. `completed, action_required, cancelled, failure, neutral, skipped, stale, success, timed_out, in_progress, queued, requested, waiting, pending`

**Comment by erikologic** [comment]
Example:
```yml
name: Deploy
on:
  workflow_run:
    workflows:
      - Tests
    types:
      - success
jobs:
  deploy:
    ...
```
