### DISCUSSION TITLE
How can I create a fork from an action?

### DISCUSSION THREAD

**Discussion by mehtakaran9** [community/community#53623] [Actions]
### Select Topic Area

Question

### Body

```
name: My Actions

on:
  push:
    branches:
      - 'main'
permissions:
  actions: write
  contents: write
  repository-projects: write
  pull-requests: write
  id-token: write
  security-events: write

jobs:
  fork-the-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Forking the repo
        run: gh repo fork mehtakaran9/test-app-js --fork-name test-app-fork --clone --remote
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I am trying to fork a repository from inside the GitHub actions, but every time I try to do so, I face this issue: 

**failed to fork: HTTP 403: Resource not accessible by integration (https://api.github.com/repos/mehtakaran9/test-app-js/forks)**

I am not sure what I am doing wrong, since I have also set the permissions for the fork to happen. 
I also tried using a PAT in the gh CLI, but that did not work as well 
Is there any other way?

**Comment by airtower-luna** [comment]
The permissions of the `GITHUB_TOKEN` are limited to the current repository. Creating a fork means creating a *new repository*, so that won't work.

A PAT should work, if it has the right permissions. I'd expect **repo** to be the right scope, possibly additionally **workflow**, but I haven't tried forking using `gh` myself. As it didn't work for you, exactly how did you provide the PAT to `gh`?

**Reply by mehtakaran9** [reply]
```
name: Call GitHobbit

on:
  push:
    branches:
      - 'main'
env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  fork-the-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Forking the repo
        run: gh repo fork mehtakaran9/test-app-js --fork-name test-app-fork --clone --remote
  call-workflow:
    uses: mehtakaran9/githobbit/.github/workflows/actions.yml@main
    with:
      owner: mehtakaran9
      repository: test-app-fork
      branch: main
      target-branch: typescript
      file-mode: false
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
```
I tried PAT by the above. But I got this error:

```
  gh repo fork mehtakaran9/test-app-js --fork-name test-app-fork --clone --remote
  shell: /usr/bin/bash -e {0}
  env:
    GH_TOKEN: 
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
  env:
    GH_TOKEN: ${{ github.token }}
```
Notice that the GH_TOKEN doesn't have "***" as you generally would have while running actions. I have the ACCESS_TOKEN in the settings.

**Reply by mehtakaran9** [reply]
Here is the snap
<img width="826" alt="image" src="https://user-images.githubusercontent.com/22137222/234103219-1dce7c70-1780-4319-94ce-427c6e36886a.png">

**Reply by airtower-luna** [reply]
Did you add that token to the repository as a secret named `ACCESS_TOKEN`? That'd be the most obvious issue for me.

Also try setting the environment variable for the step only instead of the whole workflow. I've read from other on the forum that there's some sanitizing to prevent secrets from leaking between jobs, but it's not well documented.

**Reply by mehtakaran9** [reply]
So my purpose is forking from a reusable workflow. 

Action 1 looks like this:
```
name: Call GitHobbit

on:
  push:
    branches:
      - 'main'

jobs:
  call-workflow:
    uses: mehtakaran9/githobbit/.github/workflows/actions.yml@main
    with:
      owner: mehtakaran99
      repository: test-app-js
      branch: main
      target-branch: typescript
      file-mode: false
```

And this is what Action 2 looks like:

```
name: Run automated typer

on:
  workflow_call:
    inputs:
      owner: 
        required: true
        type: string
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
      target-branch:
        required: true
        type: string
      file-mode:
        required: true
        type: boolean
      files:
        required: false
        type: string
      working-directory:
        required: false
        type: string
        default: '.'

env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN_PAT_CLASSIC }}

jobs:
  directory-typer:
    runs-on: ubuntu-latest
    if: ${{ inputs.working-directory }} != null && ${{ inputs.file-mode }} == false
    steps:
      # Add forking step
      - name: Forking the repo
        run: gh repo fork ${{ inputs.owner }}/${{ inputs.repository }} --clone --remote
    
```

I get this error where Action 1 is triggered: 

**Run gh repo fork mehtakaran99/test-app-js --clone --remote
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
  env:
    GH_TOKEN: ${{ github.token }}**
