### DISCUSSION TITLE
Using BuildKit with Dockerfile support for Actions

### DISCUSSION THREAD

**Discussion by qrkourier** [community/community#53642] [Actions]
### Select Topic Area

Question

### Body

I couldn't find any info about using BuildKit in [the article about Dockerfile support](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions), and I couldn't find a way to turn it on for my Docker Container Action. The situation is that it's much easier to express some things in a Dockerfile with the syntax that BuildKit supports, and Docker Container Actions are limited to pre-BuildKit Dockerfile syntax.

I tried to enable Buildkit like this, but the `DOCKER_BUILDKIT` variable was ignored.

```yaml
      - name: Set up Docker BuildKit
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build binary and package
        uses: ./.github/actions/openziti-tunnel-build-action
        env:
          DOCKER_BUILDKIT: 1
        with:
          arch: ${{ matrix.arch.cmake }}
          config: Release
```

There are no other values but `runs.using`: `docker` according to [the syntax reference](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions).
