### DISCUSSION TITLE
Understanding concurrency keyword at the job level

### DISCUSSION THREAD

**Discussion by gmariottiAtWolt** [community/community#53768] [Actions]
### Select Topic Area

Question

### Body

Hi, I'm trying to understand how `jobs.<job_id>.concurrency` works compared to `concurrency` at the workflow level. If I have a workflow defined below, what should happen if commit `A` starts the workflow before commit `B`, but `B.build` causes `B.deploy` to start before `A.deploy`? Should `A.deploy` get canceled?

```yaml
jobs:
  build:
    name: Build
    steps:
      - name: Build project
        uses: actions/build-project@main
    # ...
  
  deploy:
    name: Deploy
    needs: build
    concurrency: deploy
    uses: actions/.github/workflows/deploy-project.yaml@main
    # ...
```

I'm asking because we had a case where this didn't happen, and `A.deploy` was actually executed after `B.deploy` was completed. Looking at the [documentation about concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency), my feeling is that it occurred because `A.deploy` was not queued on time, could that be the reason?
