### DISCUSSION TITLE
Cannot use composite action if job uses custom container

### DISCUSSION THREAD

**Discussion by nvincent-vossloh** [community/community#53771] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hello,

I have a job that requires a custom docker container (it contains specific tools, toolchain, ...). Inside that job I perform various steps, and one of them is a calling a composite action.

The composite action is called, it evaluates the individual steps of that composite action, however if I call a script inside that composite action, it is not called as it does not find the script.

I managed to showcase the bug with the following yaml workflow:
```yml
name: action on push
on: [push, workflow_dispatch]
jobs:
  use-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Composite action
        uses: nicovince/hello-world-composite-action@main

  use-composite-with-custom-container:
    name: Custom Container call reusable composite
    runs-on: ubuntu-latest
    container: ghcr.io/siemaapplications/zephyr-arm-build:v0.0.3
    steps:
      - name: Composite action
        uses: nicovince/hello-world-composite-action@main
```
The first job, use the default github container and that job calls the composite action properly.
The second job use a custom container, and the composite action fails.

See the logs here:
https://github.com/nvincent-vossloh/sandbox/actions/runs/4807100912

Do I need anything in my custom container to be able to call composite action ?

Thanks,
Nicolas.

**Comment by nvincent-vossloh** [comment, marked as answer]
I found a workaround by manually specifying the volume where my composite action has been downloaded, in order for the job's container to have access to the scripts called from the composite action.
Here is the fixed yaml workflow:
```yml
name: action on push
on: [push, workflow_dispatch]
jobs:
  use-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Composite action
        uses: nicovince/hello-world-composite-action@main

  use-composite-with-custom-container:
    name: Custom Container call reusable composite
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siemaapplications/zephyr-arm-build:v0.0.3
      volumes:
        - /home/runner/work/_actions/nicovince/hello-world-composite-action/main:/home/runner/work/_actions/nicovince/hello-world-composite-action/main
    steps:
      - name: Composite action
        uses: nicovince/hello-world-composite-action@main
```

However, I believe that the paths where composite actions have been downloaded should automatically be mounted into custom container.
