### DISCUSSION TITLE
Error: read ETIMEDOUT while running PostgreSQL migrations in GitHub Actions pipeline

### DISCUSSION THREAD

**Discussion by romanlobai** [community/community#53900] [Actions]
### Select Topic Area

Question

### Body

Migrations are using typeorm for execution. Locally it works fine, it runs in a 1-2mins.
The issue appears when I'm running the same script in pipeline.
It takes about 5-7mins to run migration step and after this period of time throws ETIMEDOUT

Credentials are correct, because sometimes execution was successful (very rare case)
<img width="1066" alt="Screenshot 2023-04-27 at 21 06 42" src="https://user-images.githubusercontent.com/50998487/234953648-046e2599-d367-42e9-9d85-fb6d1e8801fe.png">

Most of time it runs without any success
<img width="1057" alt="Screenshot 2023-04-27 at 21 08 37" src="https://user-images.githubusercontent.com/50998487/234953851-17dc59c7-1c7c-4c63-9c0a-b7317a42447a.png">

I had an idea that it can be related to database queries timeout, so I increased statement_timeout in parameter group in AWS RDS to max value. Now it runs longer but anyway fails after 20mins(this time is random)
<img width="1067" alt="Screenshot 2023-04-27 at 21 12 44" src="https://user-images.githubusercontent.com/50998487/234954740-37e0ac62-12d1-4eeb-a2b5-54b39004375f.png">

I have no idea how it can fail after 20mins of run while on local env it runs a few mins. More confusing thing is that sometimes it works fine, but it's rare case. It seems to me that network of GitHub Actions is very unstable or slow causing this issue.

It would be great if someone can help to find the solution. It seems that I faced up with something really specific.
I'm going to migrate to AWS Code Build but before this I wan't to make sure that I don't miss something in my understanding of GitHub Actions

Pipeline code

```
name: Staging migrations pipeline
on:
  push:
    branches:
      - staging

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
  POSTGRES_HOST: staging-db.xxxxxxxx.us-east-2.rds.amazonaws.com
  POSTGRES_PORT: 5432
  POSTGRES_USER: ${{ secrets.POSTGRES_STAGE_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_STAGE_PASSWORD }}
  POSTGRES_DATABASE: sync-db
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install
      
      - name: Run migration
        run: npm run migration:run

      - name: Building the project
        run: npm run build

      - name: Update version
        run: |
          git config --global user.email "${NPM_EMAIL}"
          git config --global user.name "cicd"
          npm version patch -m "[skip ci]-new version" --force
      - name: Push tags
        run: git push origin && git push origin --tags

      - name: Publish vesion
        run: npm publish
```
