### DISCUSSION TITLE
Workflow for Angular Universal SSR Fails/Succeeds Sporadically; No Clue as to Why

### DISCUSSION THREAD

**Discussion by MissHenesy** [community/community#53988] [Actions]
### Select Topic Area

Question

### GitHub Workflow Deploys with Working SSR Sometimes, No SSR at Other Times

I've finally written a GitHub workflow that will deploy an Angular Universal website, with working SSR.

The only trouble is that I usually have to re-run the workflow 1-3 times before the SSR will "take", and I see the HTML on my web pages when I click on "View Page Source".

Here's a snippet of the code where I *think* that things fall apart:
```
- name: Install Site Dependencies
  run: yarn --cwd ./site install

- name: Build Staging SSR
  run: yarn --cwd ./site build:ssr:staging
```

"build:ssr:staging" runs `ng build --configuration=staging && my-site:server:staging`.
I'm not sure why I think this is where the SSR succeeds or fails, especially since the workflow logging doesn't mention anything failing anywhere. I just have a sense that something isn't exactly getting triggered as it should at this point.

But, I could be wrong! 
So here is how the workflow continues from there:
```
- name: Copy SSR assets into site/dist/functions
  run: cp ./site/assets/ssr_functions/* ./site/dist/functions

- name: Get functions yarn cache directory path
  id: functions-yarn-cache-dir-path
  run: echo "::set-output name=dir::$(yarn cache dir --cwd ./site/dist/functions)"

- name: Cache site/dist/functions/yarn.lock
  uses: actions/cache@v1
  id: functions-yarn-cache
  with:
    path: ${{ steps['functions-yarn-cache-dir-path'].outputs.dir }}
    key: ${{ runner.os }}-dist-functions-yarn-${{ hasFiles('./site/dist/functions/yarn.lock') }}
    
- name: Install SSR Function Dependencies
   run: yarn --cwd ./site/dist/functions install
   
- name: Deploy Site
  if: success()
  run: |
     cd site
     firebase deploy --project=staging
 env:
   FIREBASE_TOKEN: ${{ secrets.OUR_SECRET_TOKEN }}
```

Today, I had to re-run this workflow 3 times before the web pages actually showed HTML in "View Page Source".

Is it me?

Or is it GitHub Actions?
