### DISCUSSION TITLE
GitHub Actions Organization permissions issue

### DISCUSSION THREAD

**Discussion by arudaev** [community/community#54172] [Actions] [answered]
### Select Topic Area

Question

### Body

So I am trying to set up the https://githubnext.com/projects/repo-visualization for my organization repository, but I am running into an issue:
```bash
A  diagram.svg
diff: A  diagram.svg

Commit and push diagram
  /usr/bin/git commit -m Repo visualizer: update diagram
  [main 350486a] Repo visualizer: update diagram
   1 file changed, 1 insertion(+)
   create mode 100644 diagram.svg
  /usr/bin/git push
  remote: Permission to myOrg/myOrgRepo-mobile-app.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/myOrg/myOrgRepo-mobile-app/': The requested URL returned error: 403
  Error: Error: The process '/usr/bin/git' failed with exit code 128
```
I know it is an access issue, so I tried to give the job my personal `PAT`, didn't work:
```yaml
name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
          token: ${{ secrets.REPO_PAT }}
```
It doesn't have write access

In `RepoSettings/Actions/General` I tried to change workflow permissions, but I cannot even press the bullet
![image](https://user-images.githubusercontent.com/66517969/235487870-6a217d7e-b0c1-4981-81bc-08bd1ef203f2.png)

**Comment by arudaev** [comment]
I am probably dumb, but there is just too much information on GitHub Actions, no documentation inside GitHub Next, and too many similar, but different issues on StackOverflow 😆
I have been sitting on this for 5 hours now. Help needed

**Comment by airtower-luna** [comment, marked as answer]
You should be able to give the the `GITHUB_TOKEN` the necessary write permission in your workflow, or just for the job, with the [`permissions` key](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions):

```yaml
permissions:
  contents: write
```

If that still doesn't work, check if you have any setting in your organization that'd restrict it, as I understand the docs the organization setting should only dictate the default (as you see).

If you really want to use the PAT make sure it has all the necessary permissions to write to that repo, but generally the `GITHUB_TOKEN` will be much more convenient.

**Reply by arudaev** [reply]
Should it be like this:
```yaml
name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
```

---

**Update:** It works, the permissions solution worked.
> If anybody else is having an issue with permissions for jobs, here is a link to [Jobs Permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)
