### DISCUSSION TITLE
Long-running task leads to error in GitHub workflow action

### DISCUSSION THREAD

**Discussion by haimat** [community/community#54233] [Actions]
### Select Topic Area

Question

### Body

We train our AI models via GitHub workflows, using our own GitHub runner, which basically works quite well. However, in some cases such a training runs longer than 24 hours - and  that leads to the following error on GitHub:

> Unable to extend GITHUB_TOKEN expiration time due to: GITHUB_TOKEN has expired.

After some research we found out that this is by design, as GitHub does not allow the default `GITHUB_TOKEN` to be used for more than 24 hours in a workflow. One has to use a GitHub *Personal Access Token* (PAT) in such a case.

However, even using such a PAT we ran into the same issue, the GitHub action stops after 24 hours with the error message from above. But maybe we are using the PAT within the GitHub workflow not as we should? For your reference, here are the relevant parts of that workflow:

```yaml
jobs:
  train-and-report:
    if: "contains(github.event.head_commit.message, '[TRAIN]')"
    timeout-minutes: 10080  # 1 week
    runs-on: [self-hosted, gpu, cml]      
    # ...
      
    steps:
      # ...
          
      - name: Train model
        env:
          GITHUB_TOKEN: ${{ secrets.CML_REPO_TOKEN }}  # CML_REPO_TOKEN = company-wide secret PAT
        run: |
          # Train model via our custom Python framework
          # ...
```

Now our question: What is the supposed way to use a PAT instead of the default `GITHUB_TOKEN` for GitHub workflows that run longer than 24 hours?
