### DISCUSSION TITLE
Step stdout curly braces truncated if secrets present

### DISCUSSION THREAD

**Discussion by redrick** [community/community#54300] [Actions] [answered]
### Select Topic Area

Question

### Body

We have a cron job that simply runs some script, simplified example like so:

```
name: Cron 
run-name: Cron

on:
  schedule:
    - cron: "30 2 * * *" # every day 02:30 UTC
  workflow_dispatch:

env:
  token: ${{ secrets.token }}

jobs:
  comparison:
    name:  comparison 
    runs-on: [default]
    container:
      image: ruby:3.1
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global url."git+ssh://git@github.com/".insteadOf "https://github.com/"
      - name: compare
        run: ruby compare.rb
```

`compare.rb` is just ruby script running stuff, but for simplification, reproducible with simply this script:

```ruby
require 'json'

puts "#{{"ccc"=>"34", "fff"=>["rr_11"], "sss"=>"", "X"=>false, "gg"=>[ "fddd"], "sdsdsd"=>["3333"]}.to_json}"
```

In reality this outputs some more formatted result to stdout that is displayed in GHA (but the same way as demonstration above). Catch is that in string that appears on stdout there is multiple JSONs in it and they get completely  destroyed like so:

```
Ran for: 
***"ccc"=>"34", "fff"=>["rr_11"], "sss"=>"", "X"=>false, "gg"=>[ "fddd"], "sdsdsd"=>["3333"]***
 time: 0.083s                              time: 0.071s 
Resulted in PASS
File location: /tmp/edbe9136-1a31-49f6-ab13-57b3eb27a331.json
```

second line from above is JSON, but curly braces got replaced from any of `{`/`}` to `***` which is now unusable...

Had no problem running this previously on literally any other CI/CD solution there is, but now GHA does this. Could be some setting I am missing?

**Comment by airtower-luna** [comment]
Things getting replaced with `***` smells of the secrets censoring mechanism, but it seems odd (to say the least) that it'd apply to single curly braces. :sweat_smile: 

What happens if you send the output to a file, and upload that as an artifact? If the artifact is okay that'd confirm it's only the log censoring.

**Reply by redrick** [reply]
@airtower-luna thanks for the quick reply, frankly tho I am not able to put in the time to discover about file in artifacts, because I know 100% this is not what I am printing, this was previously running for 2 years in droneIO like a charm with me and team using it on daily basis.... only thing that was changed was phasing out droneCI and now using GHA...

I am wondering why would GHA do this to some stdout :man_shrugging: 

And I would be happy to correct this, now it is too painfull. 

What we came up with now is replacing that particular JSON part of the string with base64 encoded string and then copy pasting that to terminal and decoding.... that way string is correct nothing is replaced in it and we can use it... but that is so time consuming and straight up stupid... (sry getting emotional here, I am not completely liking these Github Workarounds)

**Reply by airtower-luna** [reply]
> I am wondering why would GHA do this to some stdout

They try to prevent credentials and the like from leaking into logs. That includes anything defined as a *secret* in your repository (or organization it belongs to), but they also seem to have some other patterns, e.g. for URLs containing credentials. A detected secret is replaced with `***` (only in the log, not commands, I/O, etc. within the job), that's where my guess comes from.

> sry getting emotional here, I am not completely liking these Github Workarounds

Keep in mind most of the people here (including myself) are just other users. :wink:

**Reply by redrick** [reply]
@airtower-luna note mated, I know, is just the frustration you know...

Anyways this is a bit sus anyway, replacing only curly braces but nothing within them... hmmm...

At this point my question would be how to name/phrase this better so it reaches more people then. I am 100% sure that I am not the only one running task in GHA that gives JSON on stdout in some form... Somebody must have come across this and already has it solved, out base64 workaround is barely acceptable solution to this ATM

again many thanks for the replies :)

**Reply by airtower-luna** [reply]
JSON output on stdout works, I've done that, e.g. here: https://github.com/airtower-luna/convert-to-sarif/actions/runs/4773419206/jobs/8486479906#step:4:5

So I don't think it's a general problem with JSON, more likely something to do with secrets in your repo (which I can't see, obviously), or (less likely) masks applied in your workflow, maybe by actions you use.

**Reply by redrick** [reply]
OK amazing @airtower-luna seems we are getting somewhere, I edited my yaml job config above. From what you sent seems it is either image I used in GHA (`ruby:3.1`), which I used also previously when it worked so that is unlikely, or `webfactory/ssh-agent@v0.7.0` usage.

Otherwise there is nothing else in the cronjob (sucks that I cannot just copy paste a real one, is company under NDA)

**Reply by redrick** [reply]
ok this is another sad thing about Github Workarounds :( 

So I forgot to paste in use of secrets :man_facepalming:  That is my bad and now up in the question I corrected... the thing is that once in the yaml `secrets` appears, it behaves like this and as they call it [here](https://docs.github.com/en/github-ae@latest/actions/security-guides/security-hardening-for-github-actions), secrets need to be redacted which is correct, but also they redact all `{` and `}` just for good measure :man_facepalming: 

when I delete `secrets` from the yaml I can see that even basic stuff appears ok (in step init):
```
  shell: bash --noprofile --norc -e -o pipefail {0}
``` 

Once I add back the env with `secrets` used in it all the redaction hell breaks loose:
```
  shell: bash --noprofile --norc -e -o pipefail ***0***
  env:
    TOKEN: ***
```
Cannot do this without use of secrets tho, cannot store token willy-nilly because of this situation...

As far as I am concerned now, there is not even a workaround for this ATM, so please anybody reading this if you know how to properly contact github support, It would be highly appreciated, I consider this a bug in GHA TBH :man_shrugging: 

EDIT: I corrected also question title according toi my findings written above

**Reply by airtower-luna** [reply]
Now that makes me wonder if any of your secrets contains braces, maybe JSON data? The [documentation warns it can mess with secret masking](https://docs.github.com/en/actions/security-guides/encrypted-secrets) though there's little detail. :thinking: 

> To help ensure that GitHub redacts your secret in logs, avoid using structured data as the values of secrets. For example, avoid creating secrets that contain JSON or encoded Git blobs.

**Reply by redrick** [reply, marked as answer]
@airtower-luna  Yup just discovered the same :man_facepalming:  I don't know how this went completely over my head but yes, one of the secrets is GCP credentials json of course :man_facepalming: 

So i know probably everybody now knows how to get around that, but I will leave here my approach as I will have this problem in other repos in future I think. SO I can also leave it as green answer, just tested and works like a charm. I will explain on example I gave in the question, so it makes at least a bit sense here....

So job setup stays basically the same, I will just add the GCP json credentials there, but there is a twist to them... they need to be base64 encoded, so for me it was just:
```
echo $GOOGLE_APPLICATION_CREDENTIALS_JSON | base63 -i -
```
and copy output of this one, the base64 string, and paste into repository secrets for github actions so we can use this further in GHA.

So yaml now looks like this:
```yaml
name: Cron 
run-name: Cron

on:
  schedule:
    - cron: "30 2 * * *" # every day 02:30 UTC
  workflow_dispatch:

env:
  token: ${{ secrets.token }}
  GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64: ${{ secrets.GCP_BASE64 }}  # <<<< here they are

jobs:
  comparison:
    name:  comparison 
    runs-on: [default]
    container:
      image: ruby:3.1
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global url."git+ssh://git@github.com/".insteadOf "https://github.com/"
      - name: compare
        run: ruby compare.rb
```
Nevermind the naming, I used base64 in names so it is more readable that something special is going on in there

Now the script we run changes a bit, so it decodes the base64 secret and uses that:
```ruby
require 'json'
require 'base64'

if ENV['GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64']
  ENV['GOOGLE_APPLICATION_CREDENTIALS_JSON'] = Base64.decode64(ENV['GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64'])
else
  raise 'Missing correct GCP credentials!!'
end
puts "#{{"ccc"=>"34", "fff"=>["rr_11"], "sss"=>"", "X"=>false, "gg"=>[ "fddd"], "sdsdsd"=>["3333"]}.to_json}"
```
And now just profit :man_shrugging: Your stdout is not touched by reducting anything more than those secrets in init which is completely correct...

Really dumb of me to complain and miss such a completely basic piece of puzle there, but things happen and this is just one of dozens and dozens of workarounds we have in place in GHA ATM... but TBH this is one of the reasonable ones, because it guards our secrets, so I can sleep ok with having this :+1: 

many thanks for your inside @airtower-luna  and all the time you gave this, and sorry for using you as my programming duck, but all that matters is that it worked out at the end and I can sleep ok now :) Also hopefully this will help somebody else also, Thanks :rocket:
