### DISCUSSION TITLE
What is the purpose of `repository-projects` permission in `GITHUB_TOKEN`?

### DISCUSSION THREAD

**Discussion by Dzieni** [community/community#54538] [Actions] [answered]
### Select Topic Area

Question

### Body

[A part of the docs](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions) claim, that

> `GITHUB_TOKEN` is scoped to the repository level and cannot access projects.

But in the [other part of the docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) I see that there is a permission called `repository-projects`. There are no more details about it, but the name suggests that it should allow accessing the projects that are linked to the repository you're running the action from.

Unfortunately, it does not work. Here is a demo: https://github.com/Dzieni/github-actions-permission-test

It contains a really simple workflow based on the [minimal example of `octokit/graphql-action`](https://github.com/octokit/graphql-action#usage):

```yaml
name: Log repository projects
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  logRepoProjects:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_projects
        with:
          query: |
            query projects($owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                projectsV2(first: 50) {
                  nodes {
                    id
                    title
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'project release: ${{ steps.get_projects.outputs.data }}'"
```

When you go to the projects section, you can see that the repo has at least one project:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/5893812/236454973-c3ee5044-560b-4540-b940-2b7f3e82e0b5.png">

Then the workflow run has following permissions (note `RepositoryProjects`):

```
  Actions: read
  Checks: read
  Contents: read
  Deployments: read
  Discussions: read
  Issues: read
  Metadata: read
  Packages: read
  Pages: read
  PullRequests: read
  RepositoryProjects: read
  SecurityEvents: read
  Statuses: read
```

However, the result is an empty list of projects. It does work when using a personal token instead of the `GITHUB_TOKEN`.

Therefore - if `repository-projects` does not list projects from a given repo, then what is the actual purpose? It would be great if such an information was included in the docs.
