### DISCUSSION TITLE
Why does dismissing a CodeQL alert trigger a postback?

### DISCUSSION THREAD

**Discussion by chris-jenkinson** [community/community#54547] [Pull Requests]
### Select Topic Area

Product Feedback

### Body

It's incredibly common in a pull request for CodeQL to find false positives in unit tests. To get to a "clean" review, I'm flagging these alerts as false positives. Unfortunately, the Dismiss Alert button triggers a postback, taking me to the top of the pull request, requiring me to scroll back down to wherever I was at in the PR. This is a time consuming activity for even medium PRs, making me more likely to just ignore CodeQL alerts rather than address them.

**Comment by AlonaHlobina** [comment]
Hey @chris-jenkinson, 
Thanks for taking the time to provide us with your feedback. We appreciate it, and it helps us to improve our services. The code scanning them is looking into improving the behaviour now. 
Additionally, I suggest that you consider [specifying directories to exclude test files](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning#specifying-directories-to-scan) from the code scanning analysis. This can help minimize the number of false positives you encounter in non-production code.

**Reply by chris-jenkinson** [reply]
Thanks!

Unfortunately, CodeQL doesn't offer path exclusion for .NET.

**Reply by AlonaHlobina** [reply]
May I also ask you to provide a link with the view which is affected? Thank you!

**Reply by chris-jenkinson** [reply]
I don't have any active or public pull requests I can link to, but it's the /files (Files Changed tab) route on the pull request view. Dismissing any inline CodeQL alert refreshes the page, taking me all the way to the top of the page.

**Reply by jketema** [reply]
> Unfortunately, CodeQL doesn't offer path exclusion for .NET.

This is true. You might however filter your results with the filter SARIF action: https://github.com/advanced-security/filter-sarif

**Reply by chris-jenkinson** [reply]
If my `language` has more than one language in the array, how do I tokenize everything in the `filter-sarif` and `upload-sarif` steps?

**Reply by jketema** [reply]
I'm not sure what you mean by tokenize. Note that if you have more than one language and use the CodeQL action, this will spawn a separate job for each language.

**Reply by chris-jenkinson** [reply]
I'm currently using the template action found here: https://github.com/github/codeql-action and then specifying
```
strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp', 'javascript' ]
```

In the filter-sarif example, there's this step that I've converted for csharp:
```
- name: filter-sarif
      uses: advanced-security/filter-sarif@v1
      with:
        patterns: |
          +**/*.cs
          -**/*Test*.cs
        input: sarif-results/csharp.sarif
        output: sarif-results/csharp.sarif
```
It's not clear if there's a way to say "filter like this for csharp, filter like this for javascript" but rather it appears that if I want to use this step I would need to split out my current .yml into two files, one for csharp and one for javascript?

**Reply by jketema** [reply]
There are two options here. One if is to make the step conditional and have one per language:
```yaml
- name: filter-sarif
      uses: advanced-security/filter-sarif@v1
      if: matrix.language == 'csharp'
      with:
        patterns: |
          +**/*.cs
          -**/*Test*.cs
        input: sarif-results/csharp.sarif
        output: sarif-results/csharp.sarif
```

If you don't mind that the list of patterns contains patterns from multiple languages, something like the following should also be possible:
```yaml
- name: filter-sarif
      uses: advanced-security/filter-sarif@v1
      with:
        patterns: |
          +**/*.cs
          -**/*Test*.cs
          +**/*.js
          -**/*Test*.js
        input: sarif-results/${{ matrix.language }}.sarif
        output: sarif-results/${{ matrix.language }}.sarif
```
