### DISCUSSION TITLE
Release publish is not triggering my github workflow

### DISCUSSION THREAD

**Discussion by Nuckerr** [community/community#54574] [Actions] [answered]
### Select Topic Area

Question

### Body

So I have this github workflow setup:
```
name: Publish release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      # Make the Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # Run the gradle task
      - name: Run gradle task
        run: ./gradlew publishReleasePublicationToHangar -Pio.papermc.hangar-publish-plugin.default-api-key=${{ secrets.hangar-api-key }}
```

This is designed to run this gradle task when a release is created on github, however, after drafting a release with a tag and publishing it, the action does not run.
Its definitely configured correctly because I have a very similar workflow that runs on every commit but releases to a nightly channel. This leads me to believe that I am either releasing wrong or missing a piece of configuration (permissions maybe). Any ideas?

**Comment by Nuckerr** [comment]
![image](https://user-images.githubusercontent.com/62883418/236611858-6cb134eb-3038-4b1c-8fe8-7f416b875c17.png)
Same directory as two other workflows that work fine that are triggered by commits.

And this is how I'm publishing the release
![brave_lbZkdVEIJj](https://user-images.githubusercontent.com/62883418/236611971-5001e186-cb60-4ab2-be6c-a43fd975663d.gif)

You can also see that there are no errors or warnings under the action.

And the fact that the other actions work means that its enabled right?

**Reply by epomatti** [reply]
Did you manage to fix this? Same issue here

**Reply by Nuckerr** [reply, marked as answer]
I ended up copying a friend's config, and I think the change that fixed it was making sure to use an array:
```yaml
on:
  release:
    types: [published]
```

**Reply by epomatti** [reply]
hmmm.. well I have the same thing.. thanks for responding anyways. I'll see if the problem persists on my side.

**Reply by James-Mart** [reply]
But OP already has `[published]` as an array.... so that can't be what fixed it? Am I missing something?

**Reply by pgangloff-hbs** [reply]
This is NOT the fix. I have the same config, I want my action to trigger as soon as someone creates a new release on the github.com "create release" UI/console.And it is NOT triggering...

**Reply by pgangloff-hbs** [reply]
Just to update, I did get this (trigger a GitHub action when creating a new release on the github.com UI) to work some time ago with:
```
on:
  release:
    types:
      - published
```
