### DISCUSSION TITLE
Workflow run with an environment is not always a deployment

### DISCUSSION THREAD

**Discussion by mike-schenk** [community/community#5463] [Actions]
From https://docs.github.com/en/actions/reference/environments#referencing-an-environment:
> When a workflow references an environment, the environment will appear in the repository's deployments.

Sometimes a workflow needs to reference an environment to make use of environment secrets, but the workflow isn't really a "deployment." For example, we have a workflow with a pull request trigger that runs `terraform plan` to let us preview infrastructure changes, but it doesn't change anything in the target environment. We have _another_ workflow that will run `terraform apply` and actually make those changes in the target environment; it's only the latter workflow that should be counted as a deployment.

Another example is a workflow that's used like a "runbook" to perform some environment-specific maintenance on a deployed application without "deploying" the application. It needs environment secrets and the environment's "required reviewers" protection, but it isn't a deployment.

The main problem is on viewing the [deployments page](https://docs.github.com/en/developers/overview/viewing-deployment-history). When a non-deployment workflow run is the most recent, it is shown as the "Active" deployment, making it hard to determine what the prior _regular_ deployment was.

It would be great to be able to indicate within the workflow whether its execution should be reported as a deployment in the repository. Or maybe there could be a way to indicate that this workflow should use the `auto_inactive: false` when it creates its deployment.

Or is there a workaround, maybe through the API, to remove a deployment that is automatically created? Or to set the status of the prior deployment back to "Active"?

Note also, that the concurrency feature should be independent of this. In other words, a workflow that targets an environment but doesn't "deploy" to it should still be able to use concurrency groups to limit simultaneous access to a target environment.

**Comment by jackmpcollins** [comment]
We have the same use case: we would like to run `terraform plan` using environment-specific secrets without this being registered with GitHub as a deployment. A simple solution that would work for us would be to have a boolean `jobs.<job_id>.environment.deployment` to toggle whether a deployment should be created. Usage would look like:

```yaml
environment:
  name: prod
  deployment: false
```

docs on current `environment` options: https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#example-using-environment-name-and-url

---

Currently, to work around this we use `environment` only to track the deployment and we do not use environment secrets. Instead we use organization or repo-level secrets with a prefix for each environment and use [`format`](https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/expressions#format) to select these secrets. Roughly

```yaml
jobs:
  terraform:
    environment: ${{ inputs.terraform_command == 'apply' && inputs.aws_env || null }}
    name: Terraform Command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', inputs.aws_env)] }}
          aws-secret-access-key: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', inputs.aws_env)] }}
          aws-region: ${{ inputs.aws_region }}

      ...
```

Obviously this is not as clean and simple as it should be.

Ternary expression is from https://github.com/actions/runner/issues/409#issuecomment-752775072
