### DISCUSSION TITLE
Github Action setting env and input at global level

### DISCUSSION THREAD

**Discussion by roshitho** [community/community#54705] [Actions]
### Select Topic Area

Question

### Body

I am having a workflow (migrating from groovy) for which I have different jobs. The very first job is setting the env. It does the following tasks.

1. Corresponding to the environment (stage/test etc) load a JSON secret that contains specific environment settings [I am in enterprise server, and it does not have variables (free on personal account has)]
2. In the inputs given to the workflow remove any special characters etc.
3. Set standard timestamp of the workflow, uuid (from github_id) etc .

These will be used by all downstream jobs. 

Right now, the way I was able to do it is:
``` 
name: Test FLow
on:
  # For testing 
  workflow_dispatch:
    # Input parameters
    inputs:
      input1:
        description: 'Sample input1'
        required: true
        default: 'input1'
      input2:
        description: 'Sample input2'
        required: true
        default: 'input2'
:
#Set defaults		
defaults:
  run:
    shell: bash
#Cleanup the inputs for a workflow run removing any special characters        
jobs:
  Set_Build_Env:
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: test
    outputs:
      INPUT1: ${{ steps.sanitize_input.outputs.INPUT1 }}
      INPUT2: ${{ steps.sanitize_input.outputs.INPUT2 }}
      START_TIMESTAMP: ${{ steps.sanitize_input.outputs.START_TIMESTAMP }}
      BUILD_UUID: ${{ steps.sanitize_input.outputs.BUILD_UUID }}
    steps:
      - name: Sanitize inputs
        # Clean up the inputs for any special characters and set it for the rest of the flows
        id: sanitize_input
        run: |
		  #Sanitize input
          input1=$(echo "${{inputs.input1}}" | sed 's/[^a-zA-Z0-9_\/\\-\\., ]//g')
          echo "::set-output name=INPUT1::$input1"
 
          #Set job specifics
          echo "::set-output name=START_TIMESTAMP::$(date +'%Y-%m-%dT%H:%M:%S')"
          echo "::set-output name=BUILD_UUID::${{ github.run_id }}"
		  
		  #Get environment specific variable/JSON in secret
		  BuildEnv=$(echo $TEST_ENV | base64 --decode)
          
  Read_input_value:
    runs-on: self-hosted
    needs: [Set_Build_Env]
    steps:
      - name: read values
        id: read_values
        env:
          INPUT1: ${{needs.set_build_env.outputs.INPUT1}}
          INPUT2: ${{needs.set_build_env.outputs.INPUT2}}
          START_TIMESTAMP: ${{needs.set_build_env.outputs.START_TIMESTAMP}}

        run: |
          echo "$INPUT1"
          echo "$INPUT2"
          echo "$START_TIMESTAMP"
``` 

Am I doing it the right way, seems highly convoluted? Is there any better way to do it. I have about 20 variables that need to be passed around between jobs (environment specific+ input + some global variables - read and written to). If I write into a file as a JSON or something, will it help?

As a novice any pointer would help. Thanks

Note: I know set-output is deprecated but not sure if it the enterprise server or the runner version currently it is only working GITHUB_OUTPUT gives ambiguous redirect error.
