### DISCUSSION TITLE
PAT and workflow_dispatch event

### DISCUSSION THREAD

**Discussion by mih-kopylov** [community/community#54718] [Actions] [answered]
### Select Topic Area

Question

### Body

I've created a PAT and put it to `Repository secrets` section of /settings/secrets/actions path of my repo.
The secret is used to checkout sources.

However, when I trigger `workflow_dispatch` event from GH UI, the token is empty: https://github.com/mih-kopylov/our-spb-bot/actions/runs/4900070532/jobs/8750548532
```
##[debug]Register post job cleanup for action: actions/checkout@v3
##[debug]Loading inputs
##[debug]Evaluating: secrets.UPDATE_DEPENDENCIES_PAT
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'UPDATE_DEPENDENCIES_PAT'
##[debug]=> null
##[debug]Result: null
```

But if the workflow is triggered by Push, the PAT is evaluated correctly.

Why is the token empty in the first case, and what is the way for token to be evaluated when run from `workflow_dispatch` event?

**Comment by mih-kopylov** [comment, marked as answer]
False alarm.

The reason it didn't work was in fact I referred workflow from another repository. 
To make it work the secrets should be passed as secret parameters of an external workflow:

```
on:
  workflow_call:
    secrets:
      token:
        required: true
```

And when it's called:
```
jobs:
  my-job:
    uses: user/workflows/.github/workflows/my-job.yml@master
    secrets:
      token: ${{ secrets.PAT }}
```


https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context
