### DISCUSSION TITLE
I want to get the default branch in actions.

### DISCUSSION THREAD

**Discussion by Goryudyuma** [community/community#54817] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello, I have a question about the github actions context.
I would like to get the default branch in a github actions context.

https://docs.github.com/en/actions/learn-github-actions/contexts
I have looked at this page and it looks like there is none. I may be missing something.
The purpose is that I want to put in a file that defines a common job for multiple repositories, but the default branch is main or master in each of them.
How can I do this?
(Sorry if there is the same discussion, please guide me.)

Translated with www.DeepL.com/Translator (free version)

**Comment by airtower-luna** [comment]
There is no built-in variable for the default branch.

You can get it [from the repositories API](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository) but I'm not sure if that will help you. If you want to use the default branch name within a job it will work, but if you want to set up a branch filter or similar it won't.

**Comment by rffontenelle** [comment]
You can use Git information for this, like [this solution from StackOverflow](https://stackoverflow.com/a/44750379/21680236) :

```shell
git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'
```

You can set a variable with that value to use in another step:

```yaml
    steps:
        - name: get default branch
          run: echo "DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@') >> $GITHUB_ENV
        - name: echo default branch
          run: echo $DEFAULT_BRANCH
```
