### DISCUSSION TITLE
passing mount volume  when using docker

### DISCUSSION THREAD

**Discussion by hridyeshpant** [community/community#54823] [Actions]
### Select Topic Area

Question

### Body

I have requirement where my docker image need  mount volume , specified by user test directory.
my action file is looks like below and i need to pass somethings like **"${{ github.workspace }}/user_test_directory:/perf"** volume  . so that when user run my action, user test directory is available inside the docker container  and run .

Is there way i can pass docker volume, when using 'docker' in action file or any workaround
```
runs:
  using: 'docker'
  image: 'image_name:1.7.5'
  env:
     URL: "${{ inputs.url }}"
 ```
