### DISCUSSION TITLE
How to check if the PR is up to date with base branch in github action

### DISCUSSION THREAD

**Discussion by krimeshshah** [community/community#54825] [Actions]
### Select Topic Area

Question

### Body

HI Team,

We have github action workflow for terraform apply  that triggers when we make specific comment "e.g tf apply dev" on PR. Now in workflow before it runs terraform apply step, we want to check if the PR created is up to date with the base branch considering  there might be of changes being pushed to base branch in parallel. Is there any action or other way i can achieve in github action?

Regards,
krimesh

**Comment by jsoref** [comment]
If you're being lazy and your users aren't aggressive, you can check the merge commit and see if it's a fast-forward or a merge.

I have a really hard time finding GitHub's documentation on this magic ref, but:

https://stackoverflow.com/questions/71115192/git-checkout-refs-merge-not-merging-with-head-of-main

Warning: sometimes the ref will not be current. GitHub does a lot of things asynchronously, this is especially true for refs/pull/#/*

**Comment by gajus** [comment]
Two ways:

Faster:

```yaml
  before_all:
    name: 'before all'
    runs-on:
      - self-hosted
      - contra-general-purpose
    steps:
      - name: Check if branch is ahead of main
        run: |
          PR_HEAD_SHA=${{ github.event.pull_request.head.sha }}
          MAIN_SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/git/ref/heads/main" \
            | jq -r '.object.sha')

          COMPARE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/compare/$MAIN_SHA...$PR_HEAD_SHA")

          STATUS=$(echo $COMPARE | jq -r '.status')
          if [ "$STATUS" != "identical" ] && [ "$STATUS" != "ahead" ]; then
            echo "This branch is not up to date with main."
            exit 1
          fi
```

Slower, but easier to maintain:

```yaml
  before_all:
    name: 'before all'
    runs-on:
      - self-hosted
      - contra-general-purpose
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check if branch is ahead of main
        run: |
          if ! git merge-base --is-ancestor origin/main ${{ github.event.pull_request.head.sha }};
          then echo "This branch is not up to date with main";
          exit 1; fi
      - run: echo "Starting CI"
```
