### DISCUSSION TITLE
Why is the margin on the right So big on my device?

### DISCUSSION THREAD

**Discussion by saranatour1** [community/community#54837] [Other Feature Feedback, Questions, & Ideas] [answered]
### General Discussion

Question: why is the margin this big on the main page? 

### Body

I have a 14.1 inches Display, and the margin on the right is calculated to match the 900px+ width for the respective display size, it is driving me crazy. 
![image](https://user-images.githubusercontent.com/77834808/236754874-ef452c4f-e7ac-435b-b425-bb984c13f9e5.png)
```css
@media (min-width: 768px)
.feed-content {
/*the width needs to be decreased */
  max-width: calc(995px + var(--feed-sidebar) + 48px);
}
```
