### DISCUSSION TITLE
Unable to choose the runner group using : RUNNER_GROUP variable

### DISCUSSION THREAD

**Discussion by arununzer** [community/community#54864] [Actions]
### Select Topic Area

Question

### Body

Using the following image in my Runnerdeployment file "

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-org-self-hosted-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      organization: corp
      # https://github.com/actions-runner-controller/actions-runner-controller/blob/master/docs/detailed-docs.md
      image: ghcr.io/actions/actions-runner-controller/actions-runner:ubuntu-20.04
      labels:
        - gha-org-self-hosted-runner
      env:
        - name: RUNNER_ORG
          value: corp
        - name: RUNNER_LABELS
          value: gha-org-self-hosted-runner
        - name: RUNNER_GROUP
          value: organization-runner 

```
However, its getting registered to the default group ..I also specified explicitly in the manifest via RUNNER_GROUP variable to point to the respective runner group..however its not taking it. Is there way to point to the right runner group for this image : **ghcr.io/actions/actions-runner-controller/actions-runner:ubuntu-20.04**
