### DISCUSSION TITLE
Feature Request: Branch filter for the create event

### DISCUSSION THREAD

**Discussion by DKnodel** [community/community#54860] [Actions]
### Select Topic Area

Actions Feature Request

### Body

It is a fairly common task to trigger an action on the creation of a branch for example:

```
on:
  create:
     branches:
      - 'release/**'
 ```

The filter on release branches is not supported at the moment which leads to lots of spam aka started actions runs for every feature branch that is pushed. Each of those runs than need to check on the actual job via something like this:  if: ${{ contains(github.ref, 'refs/heads/releases/') }} if we actually want to do something.

Lots of people ask for it in this thread that is marked as answered:
https://github.com/orgs/community/discussions/26286

**Comment by berniedurfee-renaissance** [comment]
This would be a great feature. We have the same issue.

**Comment by TheHumanJenkins** [comment]
I also recommend this filter; if possible 🚀 📦

**Comment by Franklin89** [comment]
Waiting for this since years. For release branching this is a must have. Rather sooner than later please.

**Comment by mrea1** [comment]
This would be very helpful. Using a workaround currently

**Comment by axelhwang** [comment]
That would be awesome !

**Comment by psiservices-uwidmark** [comment]
Seems like such an obvious feature when you have the same thing on pushing a change.
Alternatively, pushing a new branch could also trigger the "push" action.

**Comment by jsoref** [comment]
My guess is that you could use a reusable workflow to limit the events in the view you care about, as I suggested to another person who was concerned about that:
https://github.com/community/community/discussions/101695#discussioncomment-8232676

Thus, you'd have two workflows:

trigger.yml -- with the logic to decide which conditions you care about which would can the reusable workflow 
release.yml -- with `on: workflow_call` and the code to do what you want

To see runs that are interesting, you'd just look at the workflow runs for the second workflow file.

**Comment by petter-eikeland** [comment]
100% needed

**Comment by davidnewman** [comment]
Original situation goes back to 2020. Pretty crazy we don't have any response from Github on such an obvious feature.

The alternatives are all pretty horrible because you wind up littering your workflows with conditionals and coming up with conventions for managing workflows that are confusing.

It's basically turtles all the way down...

**Comment by Yury-Fridlyand** [comment]
Workaround I found:
```yml
jobs:
    check-condition:
        name: Check condition
        if: >
            ((github.event_name == 'create' && github.event.ref_type == 'branch' && startsWith(github.event.ref, 'release-') || github.event_name != 'create')
        runs-on: ubuntu-latest
        steps:
            - run:

    main-job:
        needs: [check-condition]
        ...
```
This adds a job where I added extra checks for `create` event. The job does nothing, but it skips and skips all dependent jobs if condition isn't satisfied.
