### DISCUSSION TITLE
No output or visualization from Actions

### DISCUSSION THREAD

**Discussion by BradyMcIntosh** [community/community#54918] [Actions] [answered]
### Select Topic Area

Bug

### Body

I have tried to follow the [Quickstart for GitHub Actions](https://docs.github.com/en/actions/quickstart) guide, and the test action I created with this guide runs and results in a Success status, but there are no step results or visualization data available.

![Screenshot 2023-05-08 234538](https://user-images.githubusercontent.com/36173519/236988829-a76208b6-a477-46ad-9ea9-30547e01877b.jpg)

Here are the contents of the workflow file at .github/workflows/text.yml, the source of this action:
```
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
``` 

This is lifted directly from the quickstart guide, so I can't imagine there's a problem in this file specifically, but I figure it's worth showing.
