### DISCUSSION TITLE
pull_request_target isn't triggering workflow

### DISCUSSION THREAD

**Discussion by kvet** [community/community#54937] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi.

I run into the problem that in one of the private repos we have in our organisation, a workflow with the `pull_request_target` trigger isn't starting.

Here is the example workflow file:

```yml
name: Test PR

on:
  pull_request_target:
  # push:
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  dump_contexts_to_log:
    name: ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo '${{ toJSON(github) }}'
```

It works for the `push` and `pull_request` events but not for `pull_request_target`. I feel that there might be some settings I need to turn on to allow it. Can you guide me, please?
