### DISCUSSION TITLE
jobs.uses attribute fails to parse reusable workflow path

### DISCUSSION THREAD

**Discussion by davildaran** [community/community#54956] [Actions] [answered]
### Select Topic Area

Bug

### Body

Getting the following error

```
error parsing called workflow
...
: the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```

for the second `job` when running the following workflow listed below. 

Despite the fact that the first `job` is successful at parsing the same format: `{owner}/{private-repo}/../file.yaml@ref`...

Via the GH Repo Action Settings, I have enabled the private repo to Allow other private repos in the same GH Org to access and use these reusable Workflows.

The Workflow is as follows:

```
name: my-caller-workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  call-workflow-1: # this one works, GH Actions has no trouble parsing this and executing the reusable Workflow
    uses: my-org/private-repo-A/.github/workflows/build-image.yaml@main
    with:
      ...
    secrets: inherit

  call-workflow-2: # this one fails, GH Action Runner complains when parsing the `uses` directive/attribute below...
    needs: call-workflow-1
    uses: my-org/private-repo-A/.github/workflows/deploy-container.yaml@main
    with:
      ...
    secrets: inherit
```
