### DISCUSSION TITLE
The job could not retrieve the repository token.

### DISCUSSION THREAD

**Discussion by rizowski** [community/community#54970] [Actions] [answered]
### Select Topic Area

Question

### Body

👋🏻 Hey!

I'm trying to use local reusable workflows but I've run into this error:

```
The job could not retrieve the repository token.
```

I am using a self hosted runner. It exits immediately so there aren't any logs. If I watch the build as it's being ran, the only logs I see are:
![image](https://github.com/community/community/assets/574835/e690deca-4429-49ac-9483-b1a90846a199)

But otherwise it's just 

<img width="403" alt="image" src="https://github.com/community/community/assets/574835/3b8a9281-ecc5-4069-9939-dd3644d7aeff">

My reusable workflow does the following

```yml
on:
  workflow_call:
    inputs:
      lane:
        description: "The lane to deploy"
        required: true
        type: string
      service:
        description: "The service to deploy"
        required: true
        type: string
      node_version:
        description: "The node version to use"
        required: true
        type: string
        default: 18.x

jobs:
  test:
    runs-on:
      - self-hosted
      - linux
    timeout-minutes: 30
    environment: ${{ github.event.inputs.lane }} - ${{ github.event.inputs.service }} - test
    defaults:
      run:
        working-directory: ./api
    services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: data
          POSTGRES_USER: local
          POSTGRES_PASSWORD: local
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v3.0.0
        with:
          port: 8000
          cors: "*"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.event.inputs.node_version }}
```

Then the workflow calling this is pretty basic, just passing in any inputs for it to run:

```yaml
name: api/services

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/api.services.yaml

jobs:
  test-services:
    uses: ./.github/workflows/ru-test-service.yaml
    secrets: inherit
    with:
      lane: dev
      service: services
      node_version: 18.x
```

If I copy the contents over to the primary workflow, it works fine. I've tried using `secrets: inherit` hoping that was the issue. I've also tried setting the github.token directly to the checkout step. But It seems to be failing before it even gets to the reusable workflow. I've also tried manipulating the token with `permissions` but per it failing before hand, I don't think it matters.

I'm also having a terrible time trying to find anything on this error. Has anyone run across this error before and have any pointers on what to try out?
