### DISCUSSION TITLE
GitHub Action schedule if using day of month and day of week together

### DISCUSSION THREAD

**Discussion by eltoncdc** [community/community#55008] [Actions]
### Select Topic Area

Questions

### Body

`on:
  schedule:
    - cron: '40 9 22-28 1,5,9 2'`

Given the above schedule, it's expected the job runs at "09:40 on every day-of-month from 22 through 28 and on Tuesday in January, May, and September.”

How to make it runs on the only Tuesday that is within the 22nd and 28th of the Month (Jan, May, September)?

**Comment by kebshell** [comment]
Having a similar issue with this cron schedule that I only want to run on the first Monday of the month
```
    schedule:
        - cron: '0 4 1-7 * 1'
```
the GitHub Actions editor explains it as
> Runs at 04:00, between day 1 and 7 of the month, and on Monday.

My action is currently triggering daily from the 1st to the 7th of the month and all Mondays, which is not ideal.

I didn't really want to add an initial job step to check "is it Monday?", but that feels like the only workaround for this at the moment.

---

```yaml
on:
    schedule:
        - cron: '0 4 1-7 * *'

jobs:
    do-it:
        runs-on: ubuntu-latest
        steps:
            - name: Schedule - Only run on Monday
              if: ${{ github.event_name == 'schedule' }}
              run: |
                  if [ "$(date +%u)" -ne 1 ]; then
                      echo "It's not Monday, exiting"
                      exit 1
                  fi
```
