### DISCUSSION TITLE
Workflow on pull_request with branch pattern not being executed

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#55057] [Actions]
### Select Topic Area

Question

### Body

I have the following GHA workflow trigger

```yaml
on:
  pull_request:
    branches:
      - 'something/**'
  workflow_dispatch:
    inputs:
      BRANCH:
        description: The branch to run the workflow from
        required: true
```

I then create a PR from branch named `something/test-001` to `master`.

However the workflow is not running.

What am I missing?
