### DISCUSSION TITLE
Add support for Branch Variables and Secrets?

### DISCUSSION THREAD

**Discussion by Justin-JHG** [community/community#55111] [Actions]
### Select Topic Area

Product Feedback

### Body

hi there, just wondering is there any plan to implement Branch based Variables? 

we currently use Environment Varibles and Secrets to set different values for each environment. 
the issue with that is once you use Environment handle, then GitHub will treat the job as a deployment, and add a deployment history records.
e.g.
```
 Check:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: ${{ github.ref_name }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3   
```
        
    
 

![image](https://github.com/community/community/assets/41654878/3f751082-fd64-407f-a65c-3b23a80fabc9)

but in reality, not every workflow is a deployment workflow, maybe I just want to do some validaiton or spell check as my workflow. But I still need to have different variable values for each branch. Currently the only way to have different value for the same variable is to define them as Environment varaibles.  e.g. ${{ vars.blah }}

so just wondering can we add support so that we can have different values for same variable based on branch? so that it won't rigger the GitHub Deployment History event. 

We only want the deployment history to show the actual deployment events. 

hope that make sense.

Thanks
