### DISCUSSION TITLE
Schedule workflows with multiple cron statements / time collision causes failure, no warning.

### DISCUSSION THREAD

**Discussion by jasonm23** [community/community#55127] [Actions]
### Select Topic Area

Bug

### Body

So I found an undocumented issue with scheduled workflows.

```
on:
  schedule:
    - cron: "0 * * * *"
    - cron: "0/15 1 * *"
```

These schedules will collide at **01:00**, which you may assume is not a problem. 

However, at **01:00** the workflow will not run, nor will it run at the **15** minute steps at **01:00 - 01:59**. Instead the workflow will resume running again at **02:00**.

If I remove the time set intersection:

```
on:
  schedule:
    - cron: "0 * * * *" # run every hour
    - cron: "15/15 1 * *" # run at 01:15, 01:30, 01:45
```

The schedules will run as expected.

The error appears to occur for any overlapping times.
