### DISCUSSION TITLE
Write access to repository not granted. fatal: unable to access 'https://github.com/..../.......git/': The requested URL returned error: 403

### DISCUSSION THREAD

**Discussion by JawadZein** [community/community#55143] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi :)

When trying to Add and commit changes to GitHub getting this error. 

Thanks

**Comment by airtower-luna** [comment]
The message means you don't have permission to push to the repository. It's impossible to say why without full context, but the first thing to check is the token you're using.

**Reply by JawadZein** [reply]
I'm getting an error in this block when trying to push from repo to another repo 
- name: Add and commit changes to Git
        if: steps.check_new_release.outputs.result != 'no_new_release'
        run: | 
          git remote set-url origin https://github.com//.git
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --list
          git add .
          git commit -m "Downloaded latest release"
          git push -u origin main
        shell: pwsh


For the token I'm using GITHUB_TOKEN 
 run: |
          curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer GITHUB_TOKEN " \
                -H "X-GitHub-Api-Version: 2022-11-28" \

**Reply by airtower-luna** [reply]
In that case the reason is obvious: You haven't set up a token that allows pushing to the other repository. The `GITHUB_TOKEN` is scoped to the repository running the workflow and won't be allowed to push elsewhere. You'll need to provide a PAT or a deploy key with permission to write to the other repo.

Which token you give to `curl` doesn't matter for Git.

**Reply by JawadZein** [reply]
Do you have any link to this as I created a PAT ( Fine-grained tokens ) and gave the required permissions

**Reply by airtower-luna** [reply]
First you need to store the PAT [as a secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) if you haven't already.

Then you'll need to make Git actually use the token. By default [`actions/checkout`](https://github.com/actions/checkout) configures Git to use the token it uses (`GITHUB_TOKEN` by default) for any future Git operations on the repository.

* If your PAT has read permissions on the repository the workflow is running from, you could just pass it to `actions/checkout` with the `token` parameter.
* Otherwise you could set `persist-credentials: false` for `actions/checkout` so the `GITHUB_TOKEN` isn't saved, and then (in another step) set the token you want to use in the `Authorization` header, the same way `actions/checkout` would:
  ```yaml
  run: git config --local http.https://github.com/.extraheader "AUTHORIZATION: Bearer ${YOUR_PAT}"
  env:
    YOUR_PAT: ${{ secrets.YOUR_PAT }}
  ```
  And then at the end a step with `if: always()` that does `git config --local --unset-all http.https://github.com/.extraheader` to make sure it's gone (again, like `actions/checkout`).

There are other ways to do it, but those are likely the best.

**Reply by JawadZein** [reply]
Thank you :) after applying those changes got a new error " fatal: could not read Username for 'https://github.com/': No such device or address " tried to use but this doesn't work git config --global user.name "${{ github.actor }}"
                                                                                      git config --global user.email "${{ github.actor }}@users.noreply.github.com"

**Reply by jge162** [reply]
Your syntax is wrong to add a username and/or email

`git config --global user.name "<your-username>"`
`git config --global user.email "<your-email>"`

example should be this 

`git config --global user.name "jge162"`
`git config --global user.email "example@gmail.com"`

**Reply by jge162** [reply]
> Thank you :) after applying those changes got a new error " fatal: could not read Username for 'https://github.com/': No such device or address " tried to use but this doesn't work git config --global user.name "${{ github.actor }}"            git config --global user.email "${{ github.actor }}@users.noreply.github.com"

`"${{ github.actor }}"` is for GitHub Action

**Reply by JawadZein** [reply]
Thank you , I tried to use those git config --global user.name "jge162"
git config --global user.email "example@gmail.com" but also doesn't work

**Reply by jge162** [reply]
Did you use your personal info correct not the generic names I gave you

**Reply by JawadZein** [reply]
Yes, my names, and also used this git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

**Reply by jge162** [reply]
Ok. And you already did regular token. I assume you want to do remote pushes etc.

**Reply by JawadZein** [reply]
Test this locally it work, but I'm going to do remote pushes from public repo to mine

**Reply by jge162** [reply]
you did this in git to setup up remote access?

`git remote set-url origin https://YourToken@github.com/username/reponame.git`

replace username with yours, and repo_name  with correct repo and replace your_token with your token
after this it should work.

**Reply by jge162** [reply]
> Test this locally it work, but I'm going to do remote pushes from public repo to mine

ok use the git i just gave you

**Reply by jge162** [reply]
Are you trying to make this a GitHub action? not using command line right??

**Reply by JawadZein** [reply]
Yes GitHub actions,  I tried this git remote set-url origin https://YourToken@github.com/username/reponame.git and tried to use ssh instead of HTTP but same

**Reply by jge162** [reply]
try using a regular `token` and `not fine grain` version... @JawadZein

**Reply by JawadZein** [reply]
I  used regular Token ERROR " create mode 100644 download
fatal: could not read Username for 'https://github.com/': No such device or address
Error: Process completed with exit code 1. " can share with you the full code ?

**Reply by jge162** [reply]
is the GitHub action in your repo? or is it confidential, if so then do not share.

**Reply by JawadZein** [reply]
Correct, Will add you as a contributor  :) ?

**Reply by jge162** [reply]
No need, I won't have enough time to fix tonight, I have to be up early tomorrow. But, seems like a small syntax error somewhere in the GitHub action. Cause token is good and from the code you have provided I see no errors.

**Reply by JawadZein** [reply]
Thank you for contributing :)

**Reply by jge162** [reply]
Before I go to bed here is a generic version of your use case cleaned up. Hope this helps...gngn

```yaml
name: Add and commit changes to Git

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git configuration
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --list

      - name: Check for new release
        id: check_new_release
        run: |
          # Add your code to check for new releases
          echo "::set-output name=result::no_new_release"

      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Downloaded latest release"
          git push -u origin main
        if: ${{ steps.check_new_release.outputs.result != 'no_new_release' }}

      - name: Update GitHub API version
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/owner/repo
```
I ran it in a debug repo i have and no issues, see image below

<img width="1056" alt="Screenshot 2023-05-12 at 1 21 23 AM" src="https://github.com/community/community/assets/31228460/90c90168-284e-443b-a67c-fd018f60c372">
