### DISCUSSION TITLE
How to know the name of the current deployment environment?

### DISCUSSION THREAD

**Discussion by lbruun** [community/community#55292] [Actions]
### Select Topic Area

Question

### Body

From within a workflow step, I would like to know the name of the current deployment environment (if any), so that I can use it in e.g. Bash.

Here's a minimal example:
```yaml
jobs:

  job1:
    runs-on: ubuntu-latest
    environment: myenv1

    steps:
      - run: echo "GitHub deployment env : ..."

  job2:
    runs-on: ubuntu-latest
    environment: myenv2

    steps:
      - run: echo "GitHub deployment env : ..."
``` 
To be precise, in this example, line 8 should print `GitHub deployment env : myenv1`  and Line 15 should print `GitHub deployment env : myenv2` 

How to do that?
