### DISCUSSION TITLE
Worklfow choice input with on|off values gets displayed as true|false

### DISCUSSION THREAD

**Discussion by arminrosu** [community/community#55373] [Actions]
### Select Topic Area

Bug

### Body

Looks like a minor UI bug, but it's confusing.

I have a workflow configured as such:

```yaml
name: 'Production: Toggle Pipelines'
on:
  workflow_dispatch:
    inputs:
      toggle:
        description: 'Turn the pipelines: '
        required: true
        default: 'on'
        type: choice
        options:
          - on
          - off
```

The choice field doesn't display "on" or "off", instead it shows them as "true" or "false".

![_01](https://github.com/community/community/assets/612952/9ddf6472-1e1b-4585-965c-9ccecb4339a0)
![02](https://github.com/community/community/assets/612952/746bbae8-3593-415b-82e1-6349520ed990)

Quoting the options values fixes the issue and shows the expected UI:

```yaml
        options:
          - 'on'
          - 'off'
```

<img width="319" alt="Screenshot 2023-05-13 at 11 25 54" src="https://github.com/community/community/assets/612952/26c0f13c-b195-4b6e-ad69-42c7e3bad4e5">
