### DISCUSSION TITLE
Need help with GitHub Action not working on a new branch

### DISCUSSION THREAD

**Discussion by Moemu** [community/community#55390] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello everyone,

I'm currently working on creating an HTML page that utilizes a font automatically compressed by a GitHub Action. For the sake of keeping the directory organized, I decided to create a new branch in this repository specifically for the GitHub Action files and font compress. However, it seems like the action is not functioning as expected. I also modified FortuneUpUp.js on the main branch.

I would greatly appreciate your assistance in troubleshooting this issue. Below is a portion of the content from the action file:

```
name: Font Subsetting and Compression

on:
  push:
    branches:
      - main
    paths:
      - 'FortuneUpUp.js'

jobs:
  ...
```

Thank you in advance for your help!

**Comment by airtower-luna** [comment]
This is a branch filter, that'll prevent the workflow from running on any branch other than `main`:

```
on:
  push:
    branches:
      - main
```

See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore for how branch filters work.
