### DISCUSSION TITLE
404 om GitHub Pages site even though the deploy was fine

### DISCUSSION THREAD

**Discussion by dxvv-software** [community/community#55405] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Bug

### Body

the deploy was fine but it still showed a 404
why is that? website: https://project-novagon.github.io/

**Comment by jge162** [comment]
Not enough information to help you at all. Need more details.

**Reply by dxvv-software** [reply]
here is some more information.
well the workflow to deploy didn't fail but it's still showing a 404

**Comment by ryanlua** [comment]
Hi @dvnlx,

From my guess the reason you are getting a 404 page is that you are using the wrong URL and the GitHub page is located in a different URL.

Can you go to your repository which has the page you want and go to Settings > Pages > GitHub Pages > Visit site to confirm you are using the correct URL?

**Reply by dxvv-software** [reply]
i am using the right URL.

**Comment by airtower-luna** [comment, marked as answer]
There's a clear [error message in the log](https://github.com/project-novagon/project-novagon.github.io/actions/runs/4968413117/jobs/8890996095#step:7:62):

> cp: no such file or directory: /home/runner/work/project-novagon.github.io/project-novagon.github.io/build/.*

Apparently the directory you told the `peaceiris/actions-gh-pages` action to deploy doesn't exist, you'll have to investigate why. That the step doesn't *fail* after that seems like a bug to report to the action author. :thinking: 

If you want to get a list of all the actually present files and directories, you can add a step like this after the build step:

```yaml
      - run: find .
```

Two other remarks:

* You're using outdated versions of `actions/checkout` and `actions/setup-node`, as well as Node itself, you probably should update.
* If you keep having trouble with that 3rd party deployment action, you might want to look at the official ones, the [Pages starter workflows](https://github.com/actions/starter-workflows/tree/main/pages) have examples.

**Reply by dxvv-software** [reply]
i made my own workflow so here is the code 
```

name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_KEY }}
          publish_dir: ./build

```

**Reply by airtower-luna** [reply]
That's the workflow I saw, yes. If I hadn't I couldn't comment on the steps and outdated versions. :wink: 

If you follow the link in my post you'll see exactly *where* in your workflow things went wrong.

**Reply by dxvv-software** [reply]
i'm gonna try re-running it and then changing it for the find thing

**Reply by dxvv-software** [reply]
also, there are no default github pages options for react and typescript

**Reply by airtower-luna** [reply]
No, but the principle is the same: Run whatever build steps you need, and then deploy the result. The second part is the same, you just have to adjust *what* is being deployed. :slightly_smiling_face:

**Reply by dxvv-software** [reply]
i added `find .`. what do i do now?

**Reply by airtower-luna** [reply]
Look at the output to see what *actually* exists after the build finished. :slightly_smiling_face: 

I just did, and [it's obvious that the `build/` directory does exist](https://github.com/project-novagon/project-novagon.github.io/actions/runs/4973324108/jobs/8899102390#step:7:108). So either there's a bug in the action that you're using to deploy (well, another one), or the parameters you give it are wrong.

Honestly, I think it'd be best to drop that action and use the official ones to deploy. As a bonus, that way you won't need the `gh-pages` branch any more.

**Reply by dxvv-software** [reply]
the thing is i cant use a official one, i use react and typescript

**Reply by airtower-luna** [reply]
I don't mean to copy one of the starter *workflows*, I mean you should use the deployment actions used there. They don't care how you build your site, you just run the build as you do now and then point them at the result. "Deploy this directory as my site", basically.

For example, if you look at the [Jekyll starter workflow](https://github.com/actions/starter-workflows/blob/87fbe43482b4d29e522c97acec91fddeeb2b5a88/pages/jekyll.yml), you just need to adjust three things:
* You don't need the [Setup Ruby step](https://github.com/actions/starter-workflows/blob/87fbe43482b4d29e522c97acec91fddeeb2b5a88/pages/jekyll.yml#L36-L41) (because you use Node, not Ruby). Set up Node instead, like you do in your current workflow (but seriously, use the current version of `actions/setup-node`, and if possible of Node itself, Node 14.x is *very, very* outdated).
* Replace the [Jekyll build](https://github.com/actions/starter-workflows/blob/87fbe43482b4d29e522c97acec91fddeeb2b5a88/pages/jekyll.yml#L45-L49) with the stuff you currently do to build your site.
* And finally, point the [`actions/upload-pages-artifact` step](https://github.com/actions/starter-workflows/blob/87fbe43482b4d29e522c97acec91fddeeb2b5a88/pages/jekyll.yml#L50-L52C15) at your `build/` directory instead of the default `_site/`. The parameter for that [is called `path`](https://github.com/actions/upload-pages-artifact/blob/64bcae551a7b18bcb9a09042ddf1960979799187/action.yml#L9-L12).

That should deploy directly from the workflow. :slightly_smiling_face:

**Reply by airtower-luna** [reply]
I should mention that this is the [Publishing with a custom GitHub Actions workflow](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow) approach. You'd be building the site and directly deploying the result, without committing to a `gh-pages` branch first (like the current workflow would do if it worked).

**Reply by dxvv-software** [reply]
thanks! i'll try that

**Reply by dxvv-software** [reply]
now it gives me an error
code:
```
name: Deploy

on:
  push:
    branches: master


permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
        
      - name: Find all items
        run: find .
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
``` 
error:

```
Error: Error: No uploaded artifact was found! Please check if there are any errors at build step, or uploaded artifact name is correct.
    at getSignedArtifactUrl (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/api-client.js:93:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/deployment.js:52:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/index.js:30:1)
Error: Error: No uploaded artifact was found! Please check if there are any errors at build step, or uploaded artifact name is correct.
```
