### DISCUSSION TITLE
Allow Secrets to be overridden when using Inherit with reusable workflows

### DISCUSSION THREAD

**Discussion by rijnhard** [community/community#55437] [Actions]
### Select Topic Area

Product Feedback

### Body

Imagine you have 100 secrets, and one of them needs to change.

```yaml
jobs:
  myjob:
    uses: ./.github/workflows/C.yaml
    secrets: 
      - inherit
      - SECRET_100: ${{ secrets.SECRET_100_FOR_A }}
```
