### DISCUSSION TITLE
env per matrix variable

### DISCUSSION THREAD

**Discussion by noaKurman** [community/community#55449] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi all, 
I have a job running on a dynamically created matrix like so: 
```
  build:
    needs: generate-matrix
    strategy:
      matrix:
        app: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
     uses: ./.github/workflows/build.yml
     secrets: inherit
     with:
      dockerfile: $dockerfile
```
My problem is with creating the dockerfile name. If the app is app1 the file should be `apps/app1/file` and if the app is app2 than the file should be `apps/unrealtedName/file`
I tried adding include, for example: 
```   
    needs: generate-matrix
    strategy:
      matrix:
        app: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
        include:
          - app: app1
            dockerfile: 'apps/app1/file'
          - app: app2
            dockerfile: 'apps/unrealtedName/file'
```
But it will run both app1 and app2, when in reality the matrix sometimes can only include app1 or app2 
Another issue is that I can not use steps to defind the dockerfile since the job is calling a callable workflow which is in the level of job itself.
I also thought maybe I could set env vars and call the var name with a variable (for example `${{ env.${{ matrix.app }}_fileName }}` but couldn't find a way to do that.
Any ideas how to accomplish this?
Thanks in advance!
