### DISCUSSION TITLE
UI Suggestion - Show used environment name in workflow run page

### DISCUSSION THREAD

**Discussion by RDavis3000** [community/community#55452] [Actions]
### Select Topic Area

Product Feedback

### Body

I'm using Repository environments in GitHub Actions.
AKAIK there is no way to know which environment a given run used.
This is especially annoying when using a workflow_dispatch with a UI input environment:

```
on:
  workflow_dispatch:
    inputs:
      environmentName:
        type: environment
        description: Select the environment   
```

It would be great if the environment name was both on the list of runs as well as the detail of the run.

![image](https://github.com/community/community/assets/16304586/32df6353-d99e-4029-92ca-757101530b49)

![image](https://github.com/community/community/assets/16304586/74d1a47c-dca1-4ddc-8bca-45b63fde08d8)
