### DISCUSSION TITLE
Composite action suddenly throwing `Unexpected value 'continue-on-error'`

### DISCUSSION THREAD

**Discussion by joeypiccola** [community/community#55573] [Actions] [answered]
### Select Topic Area

Question

### Body

I have the following directory structure with a `build` workflow that calls a `test` composite action. Suddenly when the `build` workflow runs it throws the following error. This had been working. This surfaced after making a change in an unrelated part of the repo (nothing in .github has changed). Any help is appreciated, thanks! 

```
# .github directory structure
.
├── actions
│   ├── test
│       └── action.yml
└── workflows
    └── build.yaml
```

`Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/localadmin/actions-runner/_work/myRepo/myRepo/./.github/actions/test/action.yml (Line: 52, Col: 7): Unexpected value 'continue-on-error'`

The action looks like this:

```
runs:
  using: composite
  steps:
    - name: Checkout Github Repo
      uses: actions/checkout@v3

    - name: {omitted}
      shell: bash
      id: {omitted}
      run: |
        {omitted}
      continue-on-error: true
```
