### DISCUSSION TITLE
Use nix-shell for custom shell?

### DISCUSSION THREAD

**Discussion by allwalte** [community/community#55678] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm trying to set a custom shell for a step (specifically ```nix-shell --run```).  This needs some config files which are in my repo, which have been checked out in a previous step.  If do ```nix-shell --run``` as a command within the step itself, i.e. with the shell being bash, it's already automatically in my repo, finds the file and it works.  However, since I'm running a number of different commands in this job, including multiline ones with logic, etc... what I'd really like is to do is to set ```nix-shell --run {0}``` as the shell and then run the step's GHA-created temp script with that, the way the examples show using ```perl``` as a custom shell, etc.  However, even though this works and finds the config *within* the job, if I set it as the shell it doesn't yet appear to be in the repo directory, as it says it can't find the package config.  Is there any way to set the directory that the shell runs from?

**Comment by jge162** [comment]
Yes you can do that I have done it. updated...

```yaml
 steps:
  - name: Set custom shell
    run: echo 'nix-shell --run "$0"' > shell-script.sh

  - name: Run commands in custom shell
    run: |
      chmod +x shell-script.sh
      ./shell-script.sh 'cd /path/to/repo && your-command'

```
Explained: 

Make the script executable with `chmod +x shell-script.sh`, and then execute it with the desired command and working directory using `./shell-script.sh 'cd /path/to/repo && your-command'`. You can replace `/path/to/repo` with the actual path to your repository directory, and `your-command` with the command you want.

**Comment by allwalte** [comment]
Sorry, to clarify - I don't have a script file.  The script I'm referring to is the temporary one that GHA creates with the contents of the "run" section of the step.

I want to do:
```
    - name: linux-installers
      shell: nix-shell --run "{0}"
      run: |
          <command 1 here>
          <command 2 here>
          <command 3 here>
          etc
  ```

Which theoretically works, except nix-shell needs some config files in my repo dir to start up, and it doesn't seem to have moved into that dir yet when "shell" gets invoked.

**Reply by jge162** [reply]
In that case then. You can `run` step by changing the working directory to the repository root using `cd ${{ github.workspace }}`. Then, within the `nix-shell --run` command, you can add your desired commands directly...for your use case.

```yaml
- name: Run commands in custom shell allwalte
        run: |
          # Change directory to repo root (e.g. ./root)
          # cd ./root             (example if root was root) 
          cd ${{ github.workspace }}
          
          # Run commands within nix-shell context
          nix-shell --run '
            # Add your commands here allwalte
            echo "Running command 1"
            <command 1 here>

            echo "Running command 2"
            <command 2 here>

            echo "Running command 3"
            <command 3 here>
          '
```

**Comment by allwalte** [comment]
Yes, that does work for a basic job - but some of our steps have a lot of complex, multi-line logic structures that use a lot of their own slashes, semi-colons, parenthesis, etc... and we've run into a lot of difficulty getting that all to play nicely with using nix-shell run on the commands themselves.  Our current CI system does it this way I'm trying to do - essentially running the whole job as a script inside of nix-shell --run, even though the command are in the pipeline file rather than a separate script file, and it looked like I could leverage custom shell to do the same thing.

**Reply by jge162** [reply, marked as answer]
Have you tried `bash -c`? That should be able to handle your use case, because you can maintain the complex logic structures and execute the entire job script within the `nix-shell environment "..."`. Test and report back hopefully it works. If not I have no more ideas sorry. 

```yaml
- name: Run commands in custom shell shell: bash
        run: |
          nix-shell --run 'bash -c "
            # Add your commands here allwalte
            echo Running command 1
            <command 1 here>

            echo Running command 2
            <command 2 here>

            echo Running command 3
            <command 3 here>
          "'
```

**Comment by allwalte** [comment]
Ooooh....I hadn't thought about nesting the bash -c within the nix-shell!  I'll try it shortly and report back; thanks!  I got stuck on trying to make the custom shell work just because it seemed like an exact analogue for what we're doing in our current CI system I'm migrating from, so it just clicked with me.

**Reply by jge162** [reply]
I ran a test version in a debug repo I have and it runs fine, I just do not have package so I added a default.nix for my run to work. So I did Hello world LOL. 

```yaml
name: GitHub test

on:
  push:
    branches:
      - '**'
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: debugging
        uses: jge162/Action-RunScript@2.0.0

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          echo "PATH=$HOME/.nix-profile/bin:$PATH" >> $GITHUB_ENV

      - name: Run commands in custom shell
        shell: bash
        run: |
          nix-shell --run "bash -c '
          echo Running command 1 && hello && 
          echo Running command 2 && echo Hello, world! && 
          echo Running command 3 && echo Hello again!'"
```

<img width="734" alt="Screenshot 2023-05-16 at 4 21 28 PM" src="https://github.com/community/community/assets/31228460/9c6f10f0-67fd-4f14-99e9-ab2887668a15">
<img width="735" alt="Screenshot 2023-05-16 at 4 21 11 PM" src="https://github.com/community/community/assets/31228460/c7fb707a-3990-41cb-98e1-bb8acf697990">
