### DISCUSSION TITLE
Required workflow check works only for default branch

### DISCUSSION THREAD

**Discussion by arunanandhan** [community/community#55789] [Actions]
### Select Topic Area

Question

### required workflow

We have the organization required workflow setup, that runs for all the PRs for all the repo in that org. 

Our repository defaults default branch is set to **master**. So, the required workflow is effective only for the repositories that have the default branch name called **master**. It does not work/prevent merge if check fails for any other branch names (main, develop, etc..)

Is there any way to make this work for all the repositories with their preferred default branch, without changing all the repo default branch name to master?

**Comment by jge162** [comment]
Hello @arunanandhan You can do it yes, I setup an action and tested it. It worked fine and does what you want it to do except I did not setup any valid workflows.


```yaml
name: Organization Workflow

on:
  push:
    branches:
      - main  # Adjust as per your requirements

jobs:
  fetch-repos:
    name: Fetch Repositories
    runs-on: ubuntu-latest

    steps:
      - name: Repo Search
        uses: Engineering-Actions/CheckOut@1.0.0

      - name: Get Repositories
        id: repo-list
        run: |
          ORGANIZATION=Engineering-Actions
          ACCESS_TOKEN=${{ secrets.WORKFLOW_SECRET }}
          REPO_LIST=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/orgs/$ORGANIZATION/repos?per_page=100" | jq -r '.[].name')

          # Iterate over each repository and fetch the default branch
          for REPO_NAME in $REPO_LIST; do
            DEFAULT_BRANCH=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$ORGANIZATION/$REPO_NAME" | jq -r '.default_branch')
            if [[ "$DEFAULT_BRANCH" == "null" ]]; then
              DEFAULT_BRANCH="master"  # Set a fallback default branch name, such as "main" or "master"
            fi
            echo "DEFAULT_BRANCH_$REPO_NAME=$DEFAULT_BRANCH" >> ${{ github.workflow }}.env
            echo "Default Branch for $REPO_NAME: $DEFAULT_BRANCH"
          done

  trigger-workflow:
    name: Trigger Required Workflow
    needs: fetch-repos
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow
        id: trigger
        run: |
          REPO_OWNER=${{ github.repository_owner }}
          ACCESS_TOKEN=${{ secrets.WORKFLOW_SECRET }}
          DEFAULT_BRANCH=${{ needs.fetch-repos.outputs.default_branch }}
          for REPO_NAME in ${{ needs.fetch-repos.outputs.repos }}; do
            curl -X POST -H "Authorization: token $ACCESS_TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches" -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"branch\": \"$DEFAULT_BRANCH\"}}"
          done
```

Screen shot below shows it read the three repos and shows default branches, then next you can go ahead and setup workflow as need. 

<img width="1078" alt="Screenshot 2023-05-17 at 4 46 18 PM" src="https://github.com/community/community/assets/31228460/cfc2be8f-64ea-4b8c-a704-f5e9831d05cc">
