### DISCUSSION TITLE
How can I use Semver Regex in Github Actions?

### DISCUSSION THREAD

**Discussion by nurullah** [community/community#55854] [Actions]
### Select Topic Area

Question

### Body

I was used the `v[0-9]+.[0-9]+.[0-9]+` regex code but i realised semver has a [advice](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) for the regex. When I was using this regex I get an error that says the like below;

```
push event contained invalid tags patterns: the following globs were invalid: v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
```

``` yaml
name: Archive Build and Release
'on':
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - name: Build and Archive for Production
        run: yarn build && 
                mv build build-${{ github.ref_name }} && 
                tar -zcvf build-${{ github.ref_name }}.tar.gz build-${{ github.ref_name }}
        env:
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          REACT_APP_API: ${{ secrets.REACT_APP_API }}
          REACT_APP_MODE: production
          REACT_APP_ANALYTICS_ID: ${{ secrets.REACT_APP_ANALYTICS_ID }}
```
