### DISCUSSION TITLE
Github action not triggered when github-actions bot makes pull request.

### DISCUSSION THREAD

**Discussion by emewjin** [community/community#55906] [Actions] [answered]
### Select Topic Area

Question

### Body

I wrote a GitHub Action to send a Slack message when the main target PR is opened or edited. 
However, the action doesn't get triggered only when the **github-actions bot creates the PR.** 
It doesn't even run, let alone fail.
Github Action runs fine when I create PR myself.

![image](https://github.com/community/community/assets/76927618/0de20c16-5595-47c9-b872-c9e4b77219e1)

Here is my full github action yaml. Why this happens and how can I fix it?
```yaml
name: sample

on:
  pull_request:
    branches:
      - main
    types: [opened, edited]

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Send slack message when pr opened
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "pr": "${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets. }}
```
