### DISCUSSION TITLE
Error at line 7, in my yaml file

### DISCUSSION THREAD

**Discussion by abdel792** [community/community#55931] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello,

I'm new to using GitHub workflows.

After reading a lot of documentation regarding the syntax of yaml files in a workflow, I was able to create my own workflows myself.

However, sometimes I need to debug to see where my errors are coming from.

For example, I have an error which is certainly due to an indentation problem, but the debugger gives me an error on line 7, which is normally well written.

To check my yaml files, I use actionlint, available here:

https://github.com/rhysd/actionlint

You will find the content of my yaml file below, could you tell me where the error is?

Thanks in advance.

```
name: Release On Tag
on:
  push:
    tags:
      - v2.**

jobs:
  date-formatting:
    name: Date formatting
    runs-on: ubuntu-latest
    steps:
      - uses: ajilraju/actions-date@master #release v0.1
        with:
          args: date +%F

  install-python:
    name: Install Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install scons markdown
          sudo apt update
          sudo apt install gettext

  built:
        needs: [date-formatting, install-python]
    name: Built
    runs-on: ubuntu-latest
    steps:
      - name: Dev condition
        if: endsWith (github.ref.name, "-dev")
        run: |
          scons version=$(date +%Y%m%d).1.0"
      - name: Stable condition
        if: !endsWith (github.ref.name, "-dev")
        run: |
          scons version="$date +%Y%m%d).0.0"

  automatic-release:
    needs: [install-python, built]
    name: Automatic release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
      - name: Dev condition
        if: endsWith (github.ref.name, "-dev")
        prerelease: true
        title: Development Build
      - name: Stable condition
        if: !endsWith (github.ref.name, "-dev")
        prerelease: false
        title: Stable build
        files: |
          *.nvda-addon
```

**Comment by airtower-luna** [comment, marked as answer]
You have uneven indentation within the `built` job, `needs` must be at the same level as `name`, `runs-on` etc.:

```
  built:
        needs: [date-formatting, install-python]
    name: Built
    runs-on: ubuntu-latest
```

Unfortunately the GitHub Actions parser isn't very good at pinpointing problems, it often points at the enclosing object of wherever an error occurs. :sweat_smile:

**Comment by abdel792** [comment]
Hi @airtower-luna ,

Thanks for your quick reply.

I still have small errors, related to the conditional assignment of variables.

Apparently I have to use environment variables, I don't think the ternary operator is usable, according to the discussions I've been.

**Reply by airtower-luna** [reply]
There are definitely more errors, but that's the one that causes a YAML syntax error. :wink: 

In the `automatic-release` job the last two steps are missing a `run` or `uses`, that'll cause errors too (not sure what your steps are meant to do, but you need either to tell the runner what to do). And I see at least one missing parenthesis in a `run` step in the `built` job.

**Reply by abdel792** [reply]
THANKS.

In fact, this workflow is supposed to run when a tag is pushed to the remote repo.

It should analyze if the tag name ends with '-dev' and depending on the result, it builds a stable or development version of the add-on.

By creating named steps, I think the code is clearer than the one I posted earlier, because there are no more dependencies between job IDs.

However, the major problem remains in the definition of the condition allowing to build a stable or development version.

**Reply by airtower-luna** [reply]
Your `if` conditions as such should almost work, with two fixes:

```yaml
if: endsWith(github.ref.name, '-dev')
```

* Strings in Actions expressions [must use single quotes](https://docs.github.com/en/actions/learn-github-actions/expressions#literals).
* Remove the space between function name and opening brace.

The `if` applies to that *full step*, nothing else. You need to have a `run` or `uses`. Whether it makes more sense for you to have two build steps with opposite conditions or steps that set some variables that are then used in a unified build steps depends on details.

**Reply by abdel792** [reply]
Hi @airtower-luna ,

I think I have succeeded in my workflow.

Thanks to your good advice, here is the result, which works perfectly:

```
name: Release On Tag
on:
  push:
    tags:
      - v*
  workflow_call:

jobs:
  create-release-on-tag:
    name: Create release on tag
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Date formatting
      uses: ajilraju/actions-date@master #release v0.1
      with:
        args: date +%F

    - name: Environment variable for current date
      run: |
        echo "CUR_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Conditional environment variables for dev
      if: ${{ endsWith(github.ref_name, '-dev') }}
      run: |
        echo 'RELEASE_TITLE=Dev build' >> $GITHUB_ENV
        echo 'MINOR_PATCH=1.0' >> $GITHUB_ENV
        echo 'PRE_RELEASE=true' >> $GITHUB_ENV

    - name: Conditional environment variables for stable
      if: ${{ !endsWith(github.ref_name, '-dev') }}
      run: |
        echo 'RELEASE_TITLE=Stable build' >> $GITHUB_ENV
        echo 'MINOR_PATCH=0.0' >> $GITHUB_ENV
        echo 'PRE_RELEASE=false' >> $GITHUB_ENV

    - name: Check new environment variables
      run: |
        echo '${{ env.CUR_DATE }} ${{ env.RELEASE_TITLE }} ${{ env.PRE_RELEASE }} ${{ env.MINOR_PATCH }}'

    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install scons markdown
        sudo apt update
        sudo apt install gettext

    - name: Built
      run: |
        scons version=${{ env.CUR_DATE }}.${{ env.MINOR_PATCH }}

    - name: Automatic release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ github.ref_name }}
        prerelease: ${{ env.PRE_RELEASE }}
        title: ${{ env.RELEASE_TITLE }}
        files: |
          *.nvda-addon
```
