### DISCUSSION TITLE
${{ github.event.issue.body }} fails to parse body with backticks

### DISCUSSION THREAD

**Discussion by gualterandre** [community/community#56059] [Actions] [answered]
### Select Topic Area

Bug

### Body

I have this very simple action:

```
name: 'Repro case'
on:
  issues:
    types: [opened]
jobs:
  repro-case:
    runs-on: ubuntu-latest
    steps:
      - name: repro
        run: |
         TEXT="${{ github.event.issue.body }}"
         echo $TEXT
````

which works for this body payload:

```
hello world!
```
 
but errors with this one:

```
asdadasd
  
  `asdasdasd`
  
  
  adsd
```

output of the action:

```
Run TEXT="asdadasd
  TEXT="asdadasd
  
  `asdasdasd`
  
  
  adsd"
  
  echo $TEXT
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/98[2](https://github.com/gualterandre/testing-chatgpt/actions/runs/5038961351/jobs/9036790981#step:2:2)b[3](https://github.com/gualterandre/testing-chatgpt/actions/runs/5038961351/jobs/9036790981#step:2:3)de8-11[4](https://github.com/gualterandre/testing-chatgpt/actions/runs/5038961351/jobs/9036790981#step:2:4)f-4748-aa[6](https://github.com/gualterandre/testing-chatgpt/actions/runs/5038961351/jobs/9036790981#step:2:6)6-8aaad[7](https://github.com/gualterandre/testing-chatgpt/actions/runs/5038961351/jobs/9036790981#step:2:7)61bd17.sh: line 6: asdasdasd: command not found
Error: Process completed with exit code [12](https://github.com/gualterandre/testing-chatgpt/actions/runs/5038961351/jobs/9036790981#step:2:13)7.
```

How can I escape this? I can't even parse the variable so that I can find and replace anything.

I also tried using the event json file:

`TEXT="$(jq '.issue.body' $GITHUB_EVENT_PATH)"`

which parses but then serves me no use if I want to update the issue's body through `gh` (my main use case, this is just a minimal repro case) based on the initial body.

Thoughts?

**Comment by airtower-luna** [comment, marked as answer]
Don't use Actions syntax (`${{ ... }}`) within the `run` script if you can at all avoid it. It's replaced *literally* before the shell ever sees your script, so it will break in weird ways if the value contains control characters (as you noticed). Instead, pass the data as an environment variable, and then make sure to quote properly:

```yaml
- name: repro
  run: |
    echo "${TEXT}"
  env:
    TEXT: ${{ github.event.issue.body }}
```
