### DISCUSSION TITLE
lang HTML Attribute misused in Markdown Renderer

### DISCUSSION THREAD

**Discussion by TheV360** [community/community#5608] [Other Feature Feedback, Questions, & Ideas]
Hello! I've noticed a problem with the markdown renderer GitHub uses for README files and such.

## Issue
[Fenced code blocks](https://github.github.com/gfm/#fenced-code-block) written with the `text` [info string](https://github.github.com/gfm/#info-string) result in `<pre>` tags with invalid `lang` attributes.

[The `lang` HTML attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) is intended to indicate what [human language](https://www.rfc-editor.org/rfc/rfc5646.html#section-2) [(old link)](https://www.ietf.org/rfc/bcp/bcp47.txt#theres-no-id-so-i-cant-directly-link-to-it-but-look-at-the-intro-to-section-2) an element is written in, not to indicate what programming language an element uses. The use of `lang` is not mentioned anywhere in the GitHub-flavored Markdown specification.

> Language tags are used to help identify languages, whether spoken, written, signed, or otherwise signaled, for the purpose of communication.  This includes constructed and artificial languages but excludes languages not intended primarily for human communication, such as programming languages.

This can affect text rendering on the page and could negatively impact screen readers.

## Background
Using a CSS-replacing extension, I set many sites I visit to use `font-family: monospace !important;` for their `code` & `pre` tags. Alongside that, I've set the monospace font in my browser (the latest version of Firefox) to be "Iosevka Term".

While on [this page](https://github.com/DanielKeep/cargo-script#readme), I noticed my browser had rendered *some* code blocks as my configured monospace font and others as "Courier New" (the browser's out-of-the-box default). I was confused, and thought this was a browser bug. Like, it certainly looks like one:

![A lightly-modified screenshot of GitHub. On the left, I've selected a `pre` element with the browser's built-in debug tools. On the right, I'm viewing (effectively what is) the computed CSS elements for the element. The hover information on the style rule reports that it's using the monospace font family, but Firefox's Font tab reports that it's using "Courier New".](https://user-images.githubusercontent.com/25177071/132969528-c7f3344f-b83c-4345-8f12-7b9a840e2217.png)

But it turns out the issue isn't with the browser -- it lies within the attribute used on the `pre` tag. This `lang="text"` value is invalid, and Firefox falls back to a different set of default fonts for invalid languages. After changing the default fonts in the "Other Writing System" category within Firefox's settings, the page displayed correctly.

## Example
This appears to only occur with the `text` language, as in code blocks made with the following markdown:

````md
```text
this is the affected type of code block
```
````

### `shell` language:
```shell
$ echo "hello world" > example.txt
$ cat example.txt
hello world
$
```
⇒ results in a `<pre>` element

### `text` language:
```text
$ echo "hello world" > example.txt
$ cat example.txt
hello world
$
```
⇒ results in a `<pre lang="text">` element

## small addendum

oh yeah -- I also added this to my injected CSS, to more easily spot misconfigured `lang` attributes:
```css
:root:not(#a#b) :is(code, kbd, pre, samp, tt):is([lang^="rust"], [lang^="text"], [lang^="markdown"], [lang^="shell"], [lang^="toml"]),
:root:not(#a#b) :is(code, kbd, pre, samp, tt):is([lang^="rust"], [lang^="text"], [lang^="markdown"], [lang^="shell"], [lang^="toml"]) :is(code, kbd, pre, samp, tt) {
	background-image: url("data:image/svg+xml,<?xml version=\"1.0\"?><svg width=\"64\" height=\"64\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:svg=\"http://www.w3.org/2000/svg\" style=\"stroke: none; fill: %23ffffff1f; font: 24px monospace;\"><text text-anchor=\"middle\" transform=\"matrix(0.75, 0, 0, 0.770833, -2.46875, 5.61458)\" x=\"45.958333\" xml:space=\"preserve\" y=\"20.702703\">invalid</text><text text-anchor=\"middle\" transform=\"matrix(0.881944, 0, 0, 0.804167, -0.944445, 12.2396)\" x=\"38.062992\" xml:space=\"preserve\" y=\"49.471503\">[lang]</text></svg>") !important;
	background-attachment: fixed;
}
```
which will show this tiled background:
![image](https://user-images.githubusercontent.com/25177071/136479502-140b8ac8-2e20-415a-bf6e-deed8fb457a8.png)
