### DISCUSSION TITLE
Prefer Local Node Version - node-setup action

### DISCUSSION THREAD

**Discussion by dorsegal** [community/community#56102] [Actions]
### Select Topic Area

Question

### Body

I am using this actions - https://github.com/marketplace/actions/setup-node-js-environment?version=v3.6.0
Using self-hosted runner that has node 18.12 pre installed.
```
      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "18.x"
```

Every time this action runs it is downloading node and install it even there is a local node installed already. 
What am I missing?
