### DISCUSSION TITLE
Docker runner - service mysql Connection Refused from CI

### DISCUSSION THREAD

**Discussion by christrt9** [community/community#56105] [Actions]
### Select Topic Area

Question

### Body

Hi,
Github Runner is with container install. 
It create service mysqld database in container.

We are testing some Github Runners but we get error Connection Refused when we run one command from CI.
When i put sleep in CI and connect to container and run manually the command is success. 
I add some print command to show me the connection and is the correct one.

The init database it finish with success, it failed to `php artisan app:prepare -vvv` . 

I 

CI
```
jobs:
  test:
    runs-on: [self-hosted, test]
    services:
      mysql:
        image: mysql:8.0.23
        env:
          MYSQL_USER: test
          MYSQL_ROOT_PASSWORD: test
        ports:
          - 3306
     steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

     - name: Get the mysql host
        id: get_host
        run: |
          host=`docker network inspect -f '{{(index .IPAM.Config 0).Gateway}}' bridge`
          echo "db-host=$host" >> $GITHUB_OUTPUT

      - name: Init Database
        run: |
          host=`docker network inspect -f '{{(index .IPAM.Config 0).Gateway}}' bridge`
          mysql -uroot --password=test -h ${{ steps.get_host.outputs.db-host }} --port ${{ job.services.mysql.ports['3306'] }} -e "SET GLOBAL sql_mode = ''"

   - name: PHP artisan command
        run: | 
            cp -a .env.ci .env
            sed -i 's/127.0.0.1/${{ steps.get_host.outputs.db-host }}/g' .env
            sed -i 's/3306/${{ job.services.mysql.ports['3306'] }}/g' .env
            php artisan app:prepare -vvv

```

Error 
```
  1   vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
      PDOException::("SQLSTATE[HY000] [2002] Connection refused")
```
