### DISCUSSION TITLE
Make action use environment based on branch name

### DISCUSSION THREAD

**Discussion by DutchJelly** [community/community#56123] [Actions] [answered]
### Select Topic Area

Github environments integration into jobs

### Body

Hi all,

I've been trying to run a github action on an environment based on branch name. Unfortunately, I'm unable to dynamically set the environment name using the branch name.
```yml
name: Docker Image CI

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${GITHUB_REF##*/}
    steps:
    - uses: actions/checkout@v3
    - name: Set environment variables
      run: echo PORT ${{ vars.PORT }} && echo PORT ${{ env.PORT }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag express:${GITHUB_REF##*/}
```
These are my environments:
![image](https://github.com/community/community/assets/20456306/123a4da8-b6b6-489d-9f7b-08ad8bd0f604)

Does someone know how I could do this?
