### DISCUSSION TITLE
Disallow "extra" inputs to a workflow

### DISCUSSION THREAD

**Discussion by JoshMcCullough** [community/community#56149] [Actions]
### Select Topic Area

Product Feedback

### Body

Would it be possible to throw an error if a workflow is called with an input that it doesn't accept?

**Workflow**

```yml
name: my-workflow
on:
    workflow_call:
      inputs:
        fav-color:
          type: string
```

**Calling the Workflow**

```yml
jobs:
  call-my-workflow:
    uses: ./path/to/my-workflow.yml
    with:
      fav-color: red
      something-else: 123
```

I'd like to see the error:
> The workflow at path ... does not define the input: something-else

The real use case here is to account for typos (e.g. `my_input` instead of `my-input`), and adjustments after a workflow has changed (inputs added).

**The above applies to `secrets` as well.**
