### DISCUSSION TITLE
Issue on github action build flutter app

### DISCUSSION THREAD

**Discussion by hasanisaeed** [community/community#56184] [Actions]
### Select Topic Area

Question

### Body

this is my config file:
```yml
name: Build, Release app, CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-22.04]
    steps:
    - uses: actions/checkout@v3
    - uses: flutter-actions/setup-flutter@v2
      with:
          channel: stable
          version: 3.10.1
    - name: 'Run flutter pub get'
      run: flutter pub get
    - name: Enable flutter web
      run: flutter config --enable-web
    - name: 'Build Web App'
      run: flutter build web --web-renderer canvaskit --release
```
also i have to brances, `develop` and `main`.
on the `main` branch action done successfully but on the `develop` branch this error occured:
```js
Run flutter pub get
/usr/bin/env: ‘bash’: Permission denied
Error: Process completed with exit code 12[6](https://github.com/hasanisaeed/users/actions/runs/5053273/jobs/96989645#step:5:7).
```

---

the only different between two branches is the SECRECT KEYs
