### DISCUSSION TITLE
GitHub Action to upload artifacts or files to a AWS S3 bucket

### DISCUSSION THREAD

**Discussion by tomg-formpak** [community/community#56207] [Actions]
### Select Topic Area

Question

### Body

As part of our CI/CD pipeline, we are running a job to upload files to an S3 bucket. 

But we were getting errors due to ACL permission and all. When I changed the S3 bucket permission to public and ACl enabled, it's working fine. 

But **I would like to know what are the best least permissions to set up for an AWS S3 bucket so that GitHub Action have the permission to upload artefacts.**  Any detailed screenshots/steps to configure S3 bucket permission will be appreciated. Our requirement is to upload the file to the S3 bucket and also to read those uploaded files for other jobs. 

Please see below for the jobs 

```
    - name: Uploading Extracted Artifacts to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}/$BUILD_VERSION_NO
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ${{env.RELEASE_FOLDER_NAME}}/release
```
Thank you
