### DISCUSSION TITLE
az acr login with docker on self hosted runner?

### DISCUSSION THREAD

**Discussion by vgzclk** [community/community#56231] [Actions]
### Select Topic Area

Question

### Body

Greetings.

Actually we are connecting to ACR using the following code in order to use our private images:

```
jobs:
  build:
    runs-on: self-hosted
    container:
      image: myregistry.azurecr.io/base/java:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
```

Our  runner has permissions as identity service in our ACR. Can login just using "az login --identity"
But commands only can be used at steps: phase.
Theres a way to use this identity validation in order to avoid the pass of credentials?

```
credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
```
I saw this can be achieved on self hosted running in the same host, but not for ACR. I tried already a previous step for AUTH but the information is not transmitted through jobs.
