### DISCUSSION TITLE
In Github action, I can not pass a string argument to reusable workflow

### DISCUSSION THREAD

**Discussion by skyhos** [community/community#56288] [Actions]
### Select Topic Area

Bug

### Body

reusable-workflow.yml
```
name: Print destination
on:
  workflow_call:
    inputs:
      destination:
        type: string
        required: true
jobs:
  print_destination:
    runs-on: [ self-hosted ]
    steps:
      - name: Print inputs
        run: |
          echo "destination:" ${{ github.event.inputs.destination }}
```
trigger.yml
```
name: Pass destination
on:
  workflow_dispatch:
jobs:
  print_destination:
    uses: myaccount/myrepository/.github/workflows/reusable-workflow.yml@main
    with:
      destination: myword
```
result:
```
Run echo "destination:" 
  echo "destination:" 
  shell: /usr/bin/bash -e {0}
destination:
```
Current runner version: '2.293.1'

I expect that the result prints `myword` but it does not. Can somebody tell me what's wrong?
