### DISCUSSION TITLE
Error: src refspec Documentation does not match any

### DISCUSSION THREAD

**Discussion by matthieuEv** [community/community#56328] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello everyone,

I'm relatively new to GitHub Actions and I'm encountering an issue while working on a workflow for generating and deploying documentation for my project. I would appreciate your assistance in resolving the following error, happening in the "Create and switch to Documentation branch" step:

```
error: src refspec Documentation does not match any
error: failed to push some refs to 'https://github.com/example/repository'
```
Here's a brief explanation of what I'm trying to achieve:

1) I have a workflow set up using GitHub Actions to generate HTML documentation using Doxygen.
2) The generated documentation is stored in the docs/html directory within my repository.
3) I want to create a new branch called "Documentation" and push only the contents of the docs/html directory to that branch.
4) After that i will use Github Pages to host the doc

I have already attempted to implement this workflow using the following YAML configuration:

```
name: Documentation
on: workflow_dispatch
run-name: ${{ github.actor }} is running Documentation
      
jobs:
  Get-HTML-Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install doxygen
        run: sudo apt-get install doxygen
      - name: Compile Doxyfile
        run: doxygen docs/Doxyfile
      - name: List HTML documentation
        run: ls -l docs && ls -l docs/html
      - name: Upload HTML documentation
        uses: actions/upload-artifact@v2
        with:
          name: HTML-Documentation
          path: docs/html

  Deploy-HTML-Documentation:
    needs: Get-HTML-Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
      - name: Create and switch to Documentation branch
        run: |
            git branch -D Documentation || true
            git checkout --orphan Documentation
            git ls-files | grep -v '^docs/html' | xargs git rm -rf
            git clean -fd
            if test -d docs/html; then
              cp -R docs/html/* .
              git add .
              git commit -m "Add HTML documentation"
            fi
            git push origin Documentation
      - name: Switch back to main branch
        run: git checkout main
```

If you could review my YAML configuration and provide any insights or suggestions on how to fix the error mentioned above, I would greatly appreciate it.

Thanks 🤗
