### DISCUSSION TITLE
github actions to publish gradle artifact ends up with Unauthorized (401)

### DISCUSSION THREAD

**Discussion by harishrpatel** [community/community#56327] [Actions] [answered]
### Select Topic Area

Question

### Body

I am trying to publish Java library artifact using Gradle to Github Packages. It is a private repo. It works with Personal Access Token (PAT) on command line (./gradlew -d publish) but does not work with Github Actions.

Here is the YML file:
```
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publish
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```

And this is the error:
```
Execution failed for task ':qsrkit:data:publishData-releasePublicationToGitHubPackagesRepository'.
> Failed to publish publication 'data-release' to repository 'GitHubPackages'
   > Could not PUT 'https://maven.pkg.github.com/BottleRocketStudios/Android-QSRKit/com/github/BottleRocketStudios/android-qsrkit-data-release/0.0.2/android-qsrkit-data-release-0.0.2.aar'. Received status code 401 from server: Unauthorized
```

Tried to pass PAT using these lines on YML:
```
      env:
        USERNAME: ${{ secrets.QSRKIT_USERNAME }}
        TOKEN: ${{ secrets.QSRKIT_TOKEN }}
```
But this is the error I get:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':qsrkit:data:publishData-releasePublicationToGitHubPackagesRepository' (type 'PublishToMavenRepository').
  - In plugin 'org.gradle.api.publish.maven.plugins.MavenPublishPlugin$Inject' type 'org.gradle.api.publish.maven.tasks.PublishToMavenRepository' property 'credentials.username' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'credentials.username'.
      2. Mark property 'credentials.username' as optional.
    
    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#value_not_set for more details about this problem.
```
