### DISCUSSION TITLE
[Request] Allow threaded conversations on PRs and Issues

### DISCUSSION THREAD

**Discussion by daniellepintz** [community/community#5633] [Pull Requests]
Currently it is not possible to create a threaded comment on a PR (except for comments directly on the code) or Issue like it is in GH discussions. this would be a nice feature to have.

**Comment by tchaton** [comment]
Hey @daniellepintz.

Do you mean something similar to Slack to discuss deeper some specific comments? I think it is worth exploring, but IMO this could have a negative impact on the reflection flow and the creation of a strong consensus on issues and RFCs. Commenters might skip the threads.

**Reply by daniellepintz** [reply]
I mean something like GH discussions, for example the comment I am making right now is threaded. I'd like to be able to do the same thing on PRs and Issues, especially PRs since often someone will make a comment on the PR that requires a direct response

**Reply by afilbert** [reply]
Second this. It's really annoying and messy to have to "Quote reply" to top-level PR comments when a thread would keep things topical.

<img width="930" alt="Screen Shot 2021-12-20 at 11 47 15 AM" src="https://user-images.githubusercontent.com/523157/146810219-61f1982d-4b2c-4676-89b4-44f9251e11fd.png">

**Reply by cylewitruk** [reply]
Omg please implement this... As mentioned 3 years ago this exists for discussions and _still_ not for PR's... It's not about hiding information in threads, it's about keeping discussions around a PR organized. Nothing prevents having multiple views for users to choose from, i.e. threaded vs. most recent.

**Reply by tberriotmicoworks** [reply]
80 years later

**Reply by Alhajras** [reply]
100 years later

**Comment by rachmcnamara** [comment]
Please add this feature - this causes a lot of angst in our org and it would be AMAZING to be able to have threaded conversations without having to pepper them throughout the code!

**Comment by seanweiss91** [comment]
As a temporary work around we've been editing comments that someone else has made. So you could reply by editing at the bottom with a header such as: 

## `Reply - Name`
**Your reply here.**

Of course this will only work if you have permissions for this kind of edit.

**Comment by trgardos** [comment]
+1 from me too. GitLab allows this btw, :-)

**Reply by kavehv** [reply]
+1...as does Bitbucket.

**Reply by fellipetav** [reply]
I really don't understand why @github-staff had not implemented that yet.

**Comment by p0fi** [comment]
This should definitely be a thing!

**Comment by thclark** [comment]
I actually disagree, my sense is that if an issue is large enough to have to have many smaller threads of conversation, the issue is probably too large and should be subsumed under a larger group (eg using the new 'tracked in' feature, or a third party tool).

In practice I suppose it does happen that issues become behemoths - especially early in app prototyping when you can have issues like "Develop the app" 🤣. So it's not like I'd despair if this feature came in, but I would be pretty nonplussed overall.

**Reply by freakyfelt** [reply]
The problem for me is when reviewing a PR without a specific line (more of a general comment). I end up using an arbitrary line with a note at the top saying as much to allow for commenting

**Reply by daniellepintz** [reply]
@thclark what about PRs, do you agree this would be useful there?

**Reply by thclark** [reply]
We already have them in PRs - sub conversations that can then be resolved (although they can only be created within a review). The conversation creation context is worth thinking about, though - each “thread” relates to a granular thing (“start conversation” on a line of code, in that case).

Which could be a good model for how to implement this in issues, if you’re going to…

A generic scramble of threads and responses that people have or haven’t bothered to put in the thread may well reduce clarity (particularly for big OSS projects), because things are no longer presented in timeline order, meaning you then need to pick apart what should or shouldn’t be in a thread (relying on humans to structure information correctly guarantees you will fail to structure information!!!!).

And yet conversations on PRs work well, because of the initial association with a granular thing (which you can then build a more comprehensive feature around). How about something like “propose solution” and/or “ask question” buttons to create a specific context for threads within issues? You’ve then got additional functionality that you can build onto that later (“2 questions unresolved”, or “solution available”).

**Reply by p0fi** [reply]
Actually the "ask a question" feature which would offer threaded answers sounds not too bad.

**Comment by bangank36** [comment]
+1 from me, I can see github supports threaded comments in discussions already, would be great if it can be ported into PR and Issue, even as optional

**Comment by liamkeily** [comment]
When a user posts actionable feedback on a pull request, it would also be good to mark it as resolved without resorting to posting another comment. Threaded conversations on PR's and Issues should allow that via the "Resolve Conversation" button:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/2040842/218084711-0fd4fbed-2a4c-483d-ac1d-1056931ca313.png">

**Comment by Sti2nd** [comment]
Duplicate of #8469 ?

**Reply by fellipetav** [reply]
Hi, 

Indeed, that refers only to PRs. This one refers to issues as well.

**Comment by scottmarlow** [comment]
> Duplicate of #8469 ?

Yes and also note that #8469 links to a roadmap item for addressing this issue via https://github.com/github/roadmap/issues/552

Thanks @daniellepintz for starting this important discussion!

**Reply by lambertjosh** [reply]
FYI that roadmap item is now closed as not planned.

**Reply by tberriotmicoworks** [reply]
So like for the next 100 years of glorious prosperity of Github, definitely acted that humans must do review 1 comment by 1 comment without natural conversation flow, supeeeeeeeeer 👍 👍 👍 👍 👍

**Comment by pbylina** [comment]
We've migrated from bitbucket, and this is actually an unpleasant surprise :(

**Reply by fellipetav** [reply]
@github-staff

**Reply by bdetweiler** [reply]
I've been struggling with this as well since moving from an Atlassian team to a GitHub team. It's really making me realize how much better BitBucket is.

**Reply by xavier-symbe** [reply]
Same here. Surprising, since otherwise Github has been ahead of the curve on most other comparisons.

**Comment by mpl1018** [comment]
Hi everyone! We've created a free GitHub App + Action that enables threads on PR issue comments and can also be fully integrated with Slack. You can [test it out in this PR](https://github.com/pullpo-io/cli/pull/7).
More info on how to use it [here](https://docs.pullpo.io/channels-full-sync). 

https://github.com/community/community/assets/44880660/5f77c50c-46f4-4de0-bdc7-c521af5bc882

@daniellepintz @tchaton @rachmcnamara @seanweiss91 @trgardos @kavehv @fellipetav @freakyfelt @bangank36 @liamkeily @scottmarlow @pbylina

**Reply by romanr** [reply]
This requires external tool subscription? and unclear if it's free or not.

**Reply by 0xdevalias** [reply]
Looking at the [setup docs](https://docs.pullpo.io/channels-full-sync#how-to-enable-git-hub-pr-issue-threads) for this, it seems the threading feature is enabled by a GitHub action that they include inline on the docs page

<details><summary><code>.github/workflows/pullpo.yaml</code></summary>

```yaml
## .github/workflows/pullpo.yaml

    name: Pullpo PR Threads

    on:
    pull_request:
        types: [opened]

    jobs:
    pullpo_threads:
        runs-on: ubuntu-latest
        permissions:
        contents: write
        steps:
        - uses: actions/checkout@v4
            with:
            ref: ${{ github.event.pull_request.head.ref }}
            fetch-depth: 0
        - name: Create Pullpo thread file with PR SHA
            run: |
            mkdir -p 一pullpo一
            rm -rf 一pullpo一/*
            echo "# Pullpo Threaded Conversations on GitHub
            ## What is the 一pullpo一 directory I see on my project?
            The `一pullpo一` directory allows your team to respond to comments that do not reference code in a
            dedicated thread, instead of having to \"quote reply\" which makes following a conversation more
            complex than it needs to be.

            **DO NOT REMOVE OR .GITIGNORE THIS DIRECTORY OR THE AUTO-GENERATED FILES IT CONTAINS**. Doing so will
            prevent you, your reviewers and ohter contributors from being able to have threaded messages in GitHub.
            ## What files does it contain?
            The files inside this directory are created by a workflow (which you can probably find in `.github/workflows`)
            that is executed when a new pull request is open in this repository. This file is added in a new commit to
            your pull request. The **Pullpo GitHub App** transforms your normal comments into threaded comments by
            commenting on this uniquely named file.
            ## Will this directory keep getting bigger and bigger?
            No, the workflow removes all previous files in the directory. Since files have unique names within a
            repository, this avoids merge conflicts and also prevents an infinetly increasing file list. If the 
            `一pullpo一` directory contains more than one file, it is likely because multiple pull requests were open at
            the same time at one point.
            ## How will this appear on my Pull Request `Conversation` or `Files Changed` tabs?
            The `Conversation` tab will have the new threaded comments. Ideally you'll have 
            [logged into Pullpo](https://pullpo.io/login/github) with your GitHub account so the Pullpo App will be able
            to replace the new comments as authored by you. Otherwise they will show up as an action that the bot made and
            you'll be tagged in the new threaded comment. 

            As for the `Files Changed` tab, the `一pullpo一` directory has been named by prefixing a
            special character that sorts it to the bottom of the page, so all comment threads will sit at the bottom and
            won't disturb anyone trying to read your changes.
            ## So, what now...?
            Keep contributing as you're used to; your pull requests will receive an additional commit that enables 
            threaded comments. Other than that everything stays as usual.
            " > 一pullpo一/README.md
            touch 一pullpo一/pr_${{ github.event.pull_request.number }}_threads.txt
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "add-pullpo-pr-threads"
            git push
```

</details> 

Summarizing that GitHub action with ChatGPT 4o:

> This GitHub Action is designed to integrate **Pullpo**'s threaded conversation feature into pull requests by automatically creating a special directory and files when a new PR is opened. Here's a high-level breakdown of what it does:
> 
> 1. **Triggered on New PRs**  
>    - The action runs when a new pull request is opened.
> 
> 2. **Checks Out the PR Branch**  
>    - It checks out the PR branch with full history (`fetch-depth: 0`) to allow proper commit history handling.
> 
> 3. **Creates a Special Directory (`一pullpo一`)**  
>    - The action ensures the existence of a directory named `一pullpo一`.
>    - Any previous files in this directory are removed to keep it clean.
> 
> 4. **Adds a README File Explaining Pullpo**  
>    - It creates a `README.md` inside the directory, explaining that Pullpo enables threaded discussions for PR comments.
> 
> 5. **Generates a Unique Thread File**  
>    - A placeholder file is created (`pr_<PR_NUMBER>_threads.txt`), which will be used by Pullpo to track threaded conversations.
> 
> 6. **Commits & Pushes the Changes**  
>    - The workflow sets up Git with `github-actions` as the user.
>    - The new directory and files are committed and pushed to the PR branch.
> 
> ### Purpose
> 
> This automation ensures that every new pull request includes the necessary files for **Pullpo to enable threaded discussions on GitHub**, allowing more structured conversations instead of relying on manual quoting.

Looking at the [demo PR](https://github.com/pullpo-io/cli/pull/7)'s 'How does it work?' section:

> When a pull request is opened, it creates a special folder called 一pullpo一 if it doesn't already exist. We named it this way so that it always appears at the end of the files changed tab. Inside this folder, a simple text file is created to track discussions related to this specific pull request. Based on how it works, these files will never create merge conflicts.
> 
> Then when someone creates an issue comment on GitHub (or in a PR Slack channel), the Pullpo app is going to take that message and transform it into a file comment message referencing this newly created file.
> 
> Basically, this action sets up a spot for threaded conversations linked to pull requests. It helps the Pullpo app to organize comments more neatly.

---

Based on the above:

> This requires external tool subscription? and unclear if it's free or not.

@romanr From a quick skim, the GitHub action seems to do very little by itself, only creating a the placeholder file that the main app uses. It seems the bulk of this functionality will be handled by the Pullpo app itself; and therefore based on what I can determine from a skim of their [pricing page](https://pullpo.io/pricing), sounds like it will require a paid subscription.

Based on the description of how this feature works, at a high level, it seems like the Pullpo app will just notice when someone has made a comment on the main PR, convert that to a new [file comment](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#:~:text=To%20comment%20directly%20on%20a%20file) on the `一pullpo一/pr_<PR_NUMBER>_threads.txt` placeholder file ([creating the comment as the user](https://github.com/pullpo-io/cli/pull/7#pullrequestreview-1948496305) if it has permission to; and [falling back to posting as the app bot](https://github.com/pullpo-io/cli/pull/7#pullrequestreview-1948895541) if it doesn't have permissions to post as that user), and then deletes the old top-level comment.

Based on that functionality.. you could probably implement something similar purely within a GitHub action alone if you really wanted to... though personally, I don't really like the idea of littering my PR's with an unrelated file just to serve as a placeholder for where to create these new comment threads on.

I haven't deeply reviewed/tested the following GitHub Action, but here's a quick proof-of-concept I knocked up for this using ChatGPT `o3-mini-high`. It can't post the new comment as the user themselves.. but aside from that I think it pretty much implements the same basic workflow/etc:

- Event: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment
- Payload: https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment
- Creating a comment: https://docs.github.com/en/rest/pulls/comments#create-a-review-comment-for-a-pull-request

```yaml
name: Convert PR Top-Level Comment to File Comment

on:
  issue_comment:
    types: [created]

env:
  COMMITTER_NAME: "github-actions"
  COMMITTER_EMAIL: "github-actions@github.com"

jobs:
  convert-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request != null }}
    env:
      PLACEHOLDER_FILE: "thread-comments/pr_${{ github.event.issue.number }}_threads.txt"
    steps:
      - name: Get PR details
        id: pr_details
        uses: actions/github-script@v6
        with:
          script: |
            const pull_number = context.payload.issue.number;
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number
            });
            core.setOutput("head_ref", pr.head.ref);
            core.setOutput("head_sha", pr.head.sha);
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr_details.outputs.head_ref }}
          token: ${{ secrets.ADMIN_TOKEN }}
          fetch-depth: 0

      - name: Ensure placeholder file exists
        id: ensure_placeholder
        run: |
          if [ -f "${PLACEHOLDER_FILE}" ]; then
            echo "Placeholder file exists. Skipping creation."
          else
            mkdir -p "$(dirname "${PLACEHOLDER_FILE}")"
            cat <<EOF > "${PLACEHOLDER_FILE}"
# Threaded Discussion Placeholder

This file is used to anchor threaded comments for this pull request.
Do not modify this file manually.

<!-- Auto-generated by GitHub Action -->
EOF
            git config user.name "${COMMITTER_NAME}"
            git config user.email "${COMMITTER_EMAIL}"
            git add "${PLACEHOLDER_FILE}"
            git commit -m "Add placeholder file for threaded discussions"
            git push origin ${{ steps.pr_details.outputs.head_ref }}
          fi

      - name: Create file-level review comment on placeholder file
        id: create_review_comment
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.issue.number;
            const commit_id = "${{ steps.pr_details.outputs.head_sha }}";
            const placeholderPath = "${PLACEHOLDER_FILE}";
            const body = `**Threaded comment by @${context.payload.comment.user.login}:**\n\n${context.payload.comment.body}`;
            // Using subject_type "file" creates a file-level review comment.
            const { data: reviewComment } = await github.rest.pulls.createReviewComment({
              owner,
              repo,
              pull_number,
              commit_id,
              path: placeholderPath,
              body: body,
              subject_type: "file"
            });
            core.info("Created review comment with ID: " + reviewComment.id);
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Delete original top-level comment
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id
            });
            core.info("Deleted original top-level comment");
          token: ${{ secrets.ADMIN_TOKEN }}
```

---

**Edit:** Captured in this gist for posterity:

- https://gist.github.com/0xdevalias/7807fa0a8febe648a5e6f70a3a4ac0b6#convert-top-level-pr-comments-to-file-attached-review-comments-via-github-actions
