### DISCUSSION TITLE
Environment Variable does not work from self hosted runner (ARC)

### DISCUSSION THREAD

**Discussion by zura101** [community/community#56345] [Actions] [answered]
### Select Topic Area

Question

### Body

I have Action runner controller running in kubernetes.
created `GITHUB PAT` and added `GH_PAT` and `MY_TEST` Environment variables in my self-hosted runner.
I can reach them during workflow, 
![ENV_CHECK](https://github.com/community/community/assets/7302925/0c0bb3fe-7dc8-4f62-875c-4c55cb258b5a)

but somehow I cannot use my `GH_PAT` for actions/checkout@v3.

when I use my `GITHUB PAT` from secrets everything works fine
```
- name: Checkout argocd repo
  uses: actions/checkout@v3
  with:
    repository: leaderbet/argocd
    token: ${{secrets.GH_PAT}} 
    ref: master
```
but when I try to get it from self-hosted runner's Environment variables
```
- name: Checkout argocd repo
  uses: actions/checkout@v3
  with:
    fetch-depth: 0
    repository: leaderbet/argocd
    token: $GH_PAT  # `GH_PAT` is a secret that contains your PAT
    ref: master
```

I got next error 
![ENV_ERROR](https://github.com/community/community/assets/7302925/75f13cc1-b2fc-426b-88cf-d3b08dae2d6c)

Any advice how should I pass my `GH_PAT` variable to actions/checkout@v3 to make it work?
