### DISCUSSION TITLE
How to change Feedback PR's text (e.g. to another language)

### DISCUSSION THREAD

**Discussion by eliocamp** [community/community#56352] [GitHub Education] [answered]
### Hi everyone,

I teach in a Spanish-speaking country but the text in the feedback PR is in English. Many of my students don't know English so I want to customise the text that appear on the PR to write it in Spanish and also add course-specific stuff. Can this be done?

**Comment by markpatterson27** [comment, marked as answer]
If you are happy to write your own [workflows](https://docs.github.com/en/actions/using-workflows) and use template repositories, you can create the Feedback PR yourself, or edit the one Classroom creates, with your own translated content,

You can see the workflow for creating a "Feedback" PR in my [classroom introductory assignment](https://github.com/markpatterson27/GitHub-Classroom-Introductory-Assignment/blob/9cf1b2a31680b7451c13a7ce66e79e8e1c91102a/.github/workflows/classroom.yml#LL236C1-L283C85)

It might be better to edit the PR in your case though. Workflow would be something like this.

```yaml
name: Update Feedback PR

on: 
  pull_request: # run workflow when PR opened on feedback branch
    types: [opened]
    branches: [feedback]

# update Feedback PR
  update-feedback-pr:
    name: Update Feedback PR
    runs-on: ubuntu-latest
    steps:
      # checkout files so can access template
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # read template
      - uses: markpatterson27/markdown-to-output@v1 # this action parses markdown files to step outputs
        id: mto
        with:
          filepath: .github/templates/pr_body.md # put PR body text in this file and commit file to repo
      
      # find PR if it exists. PR should be #1, but just in case it isn't. PR number might be in `github` context somewhere: use that instead of this step
      - name: Find PR number
        uses: markpatterson27/find-pull-request-action@pre-pr-release-v1.8.0
        id: check-pr
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          title: Feedback
          base: feedback
          branch: ${{ github.event.repository.default_branch }}
          state: all
      - run: echo "Feedback PR number - ${{ steps.check-pr.outputs.number }}"

      # create feedback pr
      - name: Create Feedback PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: "Feedback"
          body: ${{ steps.mto.outputs.body }}
          base: feedback
          head: ${{ github.event.repository.default_branch }}
          number: ${{  steps.check-pr.outputs.number }}
        run: |
          gh pr edit "$number" --title "$title" --body "$body"
```
(^There might be some typos and mistakes in this)

Commit the workflow to your template repository and it will run whenever just after one of your students accepts an assignment.
