### DISCUSSION TITLE
Unable to process file command 'env' successfully. Error: Invalid format

### DISCUSSION THREAD

**Discussion by AlfinIndrawan** [community/community#56372] [Actions]
### Select Topic Area

Question

### Body

this is my code workflow

```
name: Create Release
on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Release Notes
        id: read_release_notes
        run: |
          release_notes=$(cat release_notes.txt)
          echo "RELEASE_NOTES=${release_notes}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          RELEASE_NOTES: ${{ env.RELEASE_NOTES }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
```

so i want to copy the release_notes.txt basically it contain previous commits after tag push so i set them into release body

the file contain
Alfin Indrawan Sistema , asdadsa
Alfin Indrawan Sistema ,  i hope this is last
Alfin Indrawan , Update main.yml

those are previous commit that i echo into file and this workflow take them after pushing tag so i will set it into release body

but it give the error:
Error: Unable to process file command 'env' successfully.
Error: Invalid format 'Alfin Indrawan Sistema ,  i hope this is last'

do anyone know? i have tried ask copilot but it give me this and this again
