### DISCUSSION TITLE
GitHub Actions not running after changing default branch

### DISCUSSION THREAD

**Discussion by wolkkthetalk** [community/community#56371] [Actions] [answered]
### Select Topic Area

Bug

### Body

We currently have a few GitHub Action Workflow using different triggers (`push`, `pull_request`, `workflow_dispatch`, and `schedule`). We've also recently changed our default branch from `main` to `develop`. The `workflow_dispatch` and `schedule` workflows were recently added, but the first two have existed before for a long time (a few months). Here is a sample code for the workflow using the `pull_request` and `push` triggers.

```
name: Status Check and Analyze
on:
  push:
    branches:
      - main
  #     - develop
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main
      - develop
```

So, before the default branch switch, they were working fine. **But after the switch, they are not triggering every time a PR has been created, edited, or synchronized**.  I've tried switching back to the `main` branch, but it doesn't seem to work also. I've also look at the documentations but couldn't anything relevant in solving this issue. I wish to know if there's anything that might be missing? Thanks in advance!
