### DISCUSSION TITLE
[Issue Forms][Feature] Add suppot at if like workflow

### DISCUSSION THREAD

**Discussion by workgroupengineering** [community/community#5642] [Projects and Issues]
```yaml
name: Bug Report
description: Report a bug encountered while developing with Uno
labels: [kind/bug, triage/untriaged, difficulty/tbd]
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: Describe how the issue manifests
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what the desired behavior should be.
   
  - type: dropdown
    id: platforms
    attributes:
      label: Affected platforms
      multiple: false
      options:
        - iOS
        - Android
        - Windows
        - Linux
    
   - type: dropdown 
     id: platforms_win
     if: {{ body.platforms == 'Windows' }}
     attributes:
      label: Windows Version
      multiple: false
      options:
        - Windows 7 32bit
        - Windows 7 46bit
        - Windows 8 32bit
        - Windows 8.1 32bit
        - Windows 10 20H2
        - ...

   - type: dropdown 
     id: platforms_linux_dist
     if: {{ body.platforms == 'Linux' }}
     attributes:
      label: Linux Distrubution
      multiple: false
      options:
        - Ubuntu 20.04
        - Suse Lunux
        - ...
...    

```

When if codition is true, the element is show
