### DISCUSSION TITLE
Avoid creating another deployment when environment is referenced in a workflow run triggered "on deployment"

### DISCUSSION THREAD

**Discussion by itskingori** [community/community#56443] [Actions]
### Select Topic Area

Product Feedback

### Body

When a workflow job that references an environment runs, it creates a deployment object with the environment property set to the name of your environment. This makes sense in most cases and is likely what one would want but in the case of a workflow that is triggered on deployment it results in two deployments being created.

For example, I have a workflow that I want to trigger a workflow run on the `deployment` event as you see below ...

```yaml
name: deploy-application
run-name: Deploy Application

on:
  - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: sandbox
      url: https://sandbox.example.com
    steps:
      - name: Debug Variables
        run: |
          echo "Environment Variable:  ${{ vars.TEST_ENV_VAR }}"
          echo "Repository Variable:  ${{ vars.TEST_VAR }}"
      - name: Debug Deployment
        run: echo '${{ toJSON(github.event.deployment) }}'
```

I then have an application that I will be consuming [the `deployment.create` event](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#deployment). The problem I am having with using [environments for deployment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) in my case is that this triggers two  `deployment.create` events because two deployments are created:

1. The first one is created when my application creates a deployment - this will be seen as a deployment **by my app** on the GitHub Deployment UI on behalf of the user (which is what I want).
2. The second one is created by the workflow run because of referencing environment - this will be seen as a deployment **by GitHub Actions** on the GitHub Deployment UI on behalf of the user (because it's not created by my app which is not what I want).

I think, the workflow run when triggered by a deployment event **shouldn't create a second deployment**. The only way to avoid this at the moment is avoid setting `environment:` but then that means one can't use [environment secrets](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-secrets) or [environment variables](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-variables).

### Related

* https://github.com/orgs/community/discussions/36919
* https://github.com/orgs/community/discussions/5463

### References

* https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions
* https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
* https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#deployment
