### DISCUSSION TITLE
issue form is not showing on private repo in organisation

### DISCUSSION THREAD

**Discussion by mesqueeb** [community/community#56546] [Projects and Issues]
### Select Topic Area

Bug

### Select Feature Area

- [X] Issues
- [ ] Projects

### Body

this `body` in an issue template does not show as a form in my private repo in the organisation:
```
body:
  - type: textarea
    id: current
    attributes:
      label: 現在 | Current
      description:
      placeholder: ''
      value: ''
  - type: textarea
    id: expected
    attributes:
      label: 期待変更 | Desired Change
      description:
      placeholder: ''
      value: ''
```

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
