### DISCUSSION TITLE
How to set timeout for the whole workflow (details inside)?

### DISCUSSION THREAD

**Discussion by vitalyk-multinarity** [community/community#56600] [Actions]
### Select Topic Area

Question

### Body

My workflow is:

```
jobs:  
  launch-runner:
....
  processing:  # using self-hosted runner
  timeout-minutes: 40
   needs: launch-runner
   runs-on: [ self-hosted]
.....
delete-runner:
needs: processing
if: always() || cancelled()
.....
````

From time to time self-hosted runner doesn't register properly, so 'processing' job stuck in the queue, and the **cloud VM stays running** until I delete it manually.  
In order to prevent that,  I want to run 'delete-runner' job after one hour  - but I couldn't find how to do that.

**Comment by jge162** [comment]
You can use needs and then set sleep for one hour then delete the runner. 

```yaml
on: [workflow_run]

jobs:
  launch-runner:
    …
  processing:
    ...
  delete-runner:
    needs: [processing]
    runs-on: self-hosted
    steps:
      - name: Sleep for one hour
        run: sleep 3600  # Sleep for 3600 seconds (1 hour)
      - name: Delete runner
        run: <delete-runner-script-or-command>
```
