### DISCUSSION TITLE
Error: Docker pull failed with exit code 1  invalid reference format: repository name must be lowercase

### DISCUSSION THREAD

**Discussion by MohdRashid01** [community/community#56708] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

Hi,

Here is my action.yml which is keep at root directory of my private repo

```
name: 'build' 

on: # rebuild any PRs and main branch changes
 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3
 
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_TOKEN }}

#       - name: Build and run Dev Container task
#         uses: test/test-actions@v1.0
#         with:
#            test_spec_url: 'https://xxxx.com'
#            description: Open File
#            required: true
#            default: 'https://xxxx.com'
   
      - name: Pre-build dev container image
        uses: test/test-actions@v1.0
        with:
          imageName: ghcr.io/testi/test:main
#          cacheFrom: ghcr.io/example/example-devcontainer
#          push: always 

# name: Test  Repo

# on:
#   push:
#     branches: ['master']

# jobs:
#   build-and-push-image:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
        
      
#       - name: Test Action
#         uses: testi/test-actions@v1.0
#         with:
#            test_spec_url: 'https://xxxx.coml'
#            description: Open File
#            required: true
#            default: 'https://xxxxx.com'
```
Im new to action.yml and my app is launch in marketplace 

I dont know how to write action.yaml and dont know to run it through action..

I have image which store in public repo  
Image-Name :- ghcr.io/testi/test:main (image is visible is public but its in private repo and that is github package store)
Repo-Name :- testi/test-actions (repo is public/private for testing i create this repo from there i create above action.yml file in Action taking above imagename to test weather app is working fine or not ...testing im doing)

please tell me how to run action.yml through github container registry image

i search in google and chatgp but nothing to help me

Here is my error in Action
![1](https://github.com/community/community/assets/7812871/d856eee8-dd93-4bc1-acf4-ae98a67563a2)
