### DISCUSSION TITLE
"Error: The operation was canceled." during install dependencies step

### DISCUSSION THREAD

**Discussion by xperrylinn** [community/community#56709] [Actions]
### Select Topic Area

Question

### Body

Howdy!

I've been stuck on getting my build to get past the install dependencies step for several hours now. I've tried several different build specification variations, but all are getting stuck on the step of installing dependencies into a miniconda environment from a YAML file. The YAML file contains packages from conda-forge and pip and when I create a conda environment from this YAML file on my local machine it takes > 10 minutes and I think most of the time is spent solving the dependencies. Below is a screen capture of the failed build. I've also included my build specification that afforded this result. Any help getting past this issue would be greatly appreciated.

![install_step_failure_runner_action](https://github.com/community/community/assets/25185558/53b05a25-f2ba-431e-bcfe-33a8702067dc)

Build specification:

```
name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yaml --name base
      - name: Test with pytest
        run: |
          $CONDA/bin/pytest
```

**Comment by jge162** [comment]
Try splitting it up to see if one fails and the other succeeds. Report back 

```yaml
- name: Install conda dependencies
  run: conda env update --file environment.yaml --name base

- name: Install pip dependencies
  run: |
    conda activate base
    pip install -r requirements.txt
```

**Comment by xperrylinn** [comment]
Hi @jge162,

Thank you for the suggestion. I've split each conda and pip install into its own build step. Installing each independently helped me realize and resolve a snag related to one of the conda installs. I'm now snagging on installing a pip dependency from a GitHub repository via an SSH URL, `pip install git+ssh://git@github.com/orionarcher/pymatgen-io-openmm.git`, with an error of `git@github.com: Permission denied (publickey)` and screen captured below. That repository is public and should be pip installable by anyone. Are additional build steps required to enable pip installing a GitHub repo SSH or HTTPS URL?

![Screenshot 2023-05-29 at 9 41 31 PM](https://github.com/community/community/assets/25185558/d407db9b-917b-435e-b2b7-11d6ab712fa4)

**Reply by jge162** [reply]
You should be able to install it yes. 

```yaml
- name: Install pip dependencies
  run: pip install      
  git+https://github.com/orionarcher/pymatgen-io-openmm.git
```
