### DISCUSSION TITLE
Issue with `workflow_dispatch` event not waiting for manual actions on `pull_request` open event

### DISCUSSION THREAD

**Discussion by MehdiBenHamida** [community/community#56750] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm currently facing an issue with the GitHub Actions workflow where the `workflow_dispatch` event trigger in combination with the `pull_request` event does not wait for manual actions and triggers automatically upon PR opening.

I have defined a workflow with the following configuration:
```yml 
name: Manual Workflow on PR
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ...
```
Based on the documentation and examples, my understanding is that the `workflow_dispatch` event should allow manual triggering of the workflow. However, regardless of manual triggering, the workflow always starts automatically when a new pull request is opened.

I have double-checked the indentation of the workflow file and ensured that the `workflow_dispatch` section is correctly aligned with the `pull_request` section. Additionally, I have confirmed that the latest version of the workflow file is committed and pushed to the repository.

I expect the workflow to wait for manual actions when triggered through the "Run workflow" button on the GitHub Actions tab. However, it currently triggers automatically on PR opening, bypassing the need for manual interaction.

I would appreciate any insights or suggestions to resolve this issue and make the workflow trigger manually as expected.

**Comment by jge162** [comment]
Why dont you set workflow trigger to be true for manual triggers. So you don’t have the issue anymore. 

```yaml
name: Manual Workflow on PR
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manually trigger the workflow'
        required: true
```
