### DISCUSSION TITLE
adding a random string after an expression in a conditional job will be evaluated as true

### DISCUSSION THREAD

**Discussion by v-rosa** [community/community#56827] [Actions]
### Select Topic Area

Bug

### Body

Adding a random string or even a single char in end of a conditional job after, is always interpreted as true.

See the following example:

```yml
name: reproduce-bug
  on:
    workflow_dispatch:
  jobs:
    a:
      name: a
      runs-on: ubuntu-latest
      steps:
        - run: echo "A"
        - id: set
          run: |
            echo "executed A"
    b:
      name: b
      runs-on: ubuntu-latest
      needs:
        - a
      steps:
        - run: echo "executed B"
    c:
      name: c
      runs-on: ubuntu-latest
      needs:
        - a
        - b
      if: ${{ !always() }}
      steps:
        - run: echo "executed C"
```

Job 3 is expected to never be executed. Now add a single quote `'` at the end of the expression and job3 will be executed.

```yml
name: reproduce-bug
  on:
    workflow_dispatch:
  jobs:
    a:
      name: a
      runs-on: ubuntu-latest
      steps:
        - run: echo "A"
        - id: set
          run: |
            echo "executed A"
    b:
      name: b
      runs-on: ubuntu-latest
      needs:
        - a
      steps:
        - run: echo "executed B"
    c:
      name: c
      runs-on: ubuntu-latest
      needs:
        - a
        - b
      if: ${{ !always() }} '
      steps:
        - run: echo "executed C"
```

The same would happen if you add any other char/string instead of `'`.

IMO this is a bug because if we remove the expression `${{ }}`, the workflow would be considered invalid, e.g.

`if: stringaaa`

> The workflow is not valid. .github/workflows/reproduce-bug.yml (Line: 26, Col: 9): Unrecognized named-value: 'stringaaa'. Located at position 1 within expression: stringaaa

## Runner Version and Platform

Runner version: `2.304.0`

OS of the machine running the runner: `Linux`

**Comment by airtower-luna** [comment]
Only the part within `${{ ... }}` is evaluated as an expression, anything outside is just a string literal, and a non-empty string evaluates to `true`.

One catch: If you write an `if` condition without any `${{ ... }}`, the parser adds it implicitly around the whole value (which is usually what you want). But in that case the single quote creates a syntax error. :wink:

**Reply by v-rosa** [reply]
> Only the part within ${{ ... }} is evaluated as an expression, anything outside is just a string literal, and a non-empty string evaluates to true.

So in the _if condition_, the expression is ignored if there is anything outside of the explicit expression?

**Reply by airtower-luna** [reply]
Not technically (it's evaluated, and then type weirdness happens), but that's the effect, yes. :sweat_smile:

**Reply by v-rosa** [reply]
But shouldn't the _if condition_ evaluation be more consistent, either it expects an explicit expression `${{..}}` or an implicit expression as you stated.

I wonder what's the use case to accept this: `if: ${{ !always() }} && dummy=="foo"` if the whole condition will always be evaluated as true.

This happens because the `if condtion` performs a `or` operation between the expression `${{ .. }}` and anything outside of it? If this is correct shouldn't this behaviour be documented somewhere?

**Reply by airtower-luna** [reply]
I strongly suspect there was no design decision, just a consequence of using the same evaluation logic as everywhere else. :sweat_smile: 

> This happens because the `if condtion` performs a `or` operation between the expression `${{ .. }}` and anything outside of it? If this is correct shouldn't this behaviour be documented somewhere?

No, what happens is the same thing as if you use `${{ .. }}` anywhere else. Imagine you have a step like this:

```yaml
run: echo "$TEXT"
env:
  TEXT: 'Hello ${{ input.name }}!'
```

The `${{ .. }}` in `TEXT` is substituted, converted to a string because of the context, and the whole value is the result.

For `if` the problem then comes from the [type conversion rules](https://docs.github.com/en/actions/learn-github-actions/expressions#operators):

> If the types do not match, GitHub coerces the type to a number. GitHub casts data types to a number using these conversions:
> 
> [...]
> 
> String | Parsed from any legal JSON number format, otherwise NaN.  Note: empty string returns 0.
> 
> [...]

And apparently NaN gets coerced to `true`.
