### DISCUSSION TITLE
Accessing variable from one job in another job within a GitHub Actions workflow

### DISCUSSION THREAD

**Discussion by MehdiBenHamida** [community/community#56849] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a GitHub Actions workflow defined as follows:
```yml
name: Test workflow
on:
  workflow_dispatch:
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          pr_count=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        --header "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository_owner }}:${branch_name}" \
                        | jq length)
          if [ $pr_count -eq 1 ]; then
            pr_number=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                            --header "Accept: application/vnd.github.v3+json" \
                            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository_owner }}:${branch_name}" \
                            | jq -r '.[0].number')
            echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
          else
            echo "PR count is not equal to 1. Exiting workflow."
            exit 1
          fi
  publish:
    needs: [check-pr]
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ needs.check-pr.env.PR_NUMBER }}
    name: publish v0.0.1.dev$PR_NUMBER
    steps:
      # ...
```
In this workflow, I have two jobs: `check-pr` and `publish`. The` check-pr` job retrieves the PR number based on the branch name and sets it as an environment variable using `$GITHUB_ENV`.

I want to access the value of the `PR_NUMBER` variable, which is written to `$GITHUB_ENV` in the check-pr job, within the publish job. However, when I try to use `$PR_NUMBER` in the publish job, it doesn't seem to have the expected value.

I have already confirmed that the `check-pr` job sets the `PR_NUMBER` correctly by logging it to the console. However, I'm unable to access it in the publish job.

Could someone please guide me on how to properly access the `PR_NUMBER` variable written in `$GITHUB_ENV` from the `check-pr` job in the `publish` job? Am I missing any additional configuration or syntax?

Any help or suggestions would be greatly appreciated. Thank you in advance!

**Comment by airtower-luna** [comment, marked as answer]
> Could someone please guide me on how to properly access the `PR_NUMBER` variable written in `$GITHUB_ENV` from the `check-pr` job in the `publish` job? Am I missing any additional configuration or syntax?

Variables set in `GITHUB_ENV` apply only to the current job. To carry the value over to another job, you need a [*job output*](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs). Mind that you need to define the job output based on the step output.

```yaml
jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.check-prs.outputs.PR_NUMBER }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          # ...
          echo "PR_NUMBER=$pr_number" >> $GITHUB_OUTPUT

  publish:
    needs: [check-pr]
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ needs.check-pr.outputs.pr-number }}
```
