### DISCUSSION TITLE
Feature Request: Expand options for determining whether or not a workflow should run

### DISCUSSION THREAD

**Discussion by JoshMcCullough** [community/community#56841] [Actions]
### Select Topic Area

Product Feedback

### Body

Currently, for the `push` event, we can determine whether or not a workflow should run for a a branch+path combo, like this:

```yml
on:
  push:
    branches:
      - master
      - f/**
    paths:
      - path/to/src/**
      - something-else.buildfile
```

This is very handy, but it doesn't allow for an important use case, the ability to force a build with a commit message. To get around this, I have to use a different workflow which uses a 3rd party component _and requires a container to be launched to determine if the build should even run_:

```yml
on:
  push:
    branches:
      - master
      - f/**
jobs:
  find-changes:
    runs-on: ...
    outputs:
      has-changes: ${{ steps.check-paths.outputs.should-run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Paths
        id: check-paths
        uses: dorny/paths-filter@v2
        with:
          base: ${{ github.ref }}
          filters: |
            should-run:
              - path/to/src/**
              - something-else.buildfile

  build-and-test:
    name: Build and Test
    needs: find-changes
    if: needs.find-changes.outputs.should-run == 'true' || contains(github.event.head_commit.message, '[build api]')
    runs-on: ...
    # ... additional config
```

Breaking it down:
1. Use a top-level check to only build branches we want to build.
2. Launch a container and use the 3rd party `dorny/paths-filter` action to see if some paths have changes which should cause a build.
3. Launch another container to do the build if the paths have changed or the commit message contains `[build api]`.

I'd like to propose that GHA bring this functionality to the core product and allow us to do these three checks directly, without starting a separate job just to check if we should build.

## Syntax Option 1
Instead of providing `branches` and `paths`, ability to provide an `if` like we can with jobs and steps. `branches` and `paths` could be provided still, but not when `if` is being used (one way or the other).

```yml
on:
  push:
    if: github.ref == 'master || startsWith(github.ref, 'f/')
```

## Syntax Option 2
Add an additional clause, `commit-message`, which can be used in combination with the existing `branches` and `paths` options:

```yml
on:
    branches:
      - master
      - f/**
    paths:
      - path/to/src/**
      - something-else.buildfile
    commit-message:
      - pattern: '[build api]'
        if-matched: always()
```

Option to build when the commit message and branches match:

```yml
commit-message:
  - pattern: '[build api]'
    if-matched: branchesMatch() 
```

Option to build when the commit message, branches, and paths match (`if-matched` in this example would make sense as the default value if it's not provided -- so all 3 would have to match):

```yml
commit-message:
  - pattern: '[build api]'
    if-matched: branchesMatch() && pathsMatch()
```

Multiple `pattern` options (patterns are just for illustrative purposes are of course would not be this verbose). If any of `pattern + if-matches` options result in a "proceed" outcome, then the `commit-message` check is "truthy":

```yml
commit-message:
  - pattern: '[build api NOW]'
  - pattern: '[build api if branch matches]'
    if-matched: branchesMatch()
```

---

_Thank you, community & GitHub, for your time and consideration._
