### DISCUSSION TITLE
Dynamically specify branch name in inputs

### DISCUSSION THREAD

**Discussion by ghost** [community/community#56891] [Actions]
### Select Topic Area

Product Feedback

### Body

In some cases we may need to specify branch name at workflow start and in case of manual run we may use [`inputs`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs). 

As for now we may set it as a string
```yaml
on:
  workflow_dispatch:
    inputs:
      manual_branch:
        description: Set branch
        required: true
        type: string
        default: main
      # dynamic_branch:
      #   description: Select branch
      #   required: true
      #   type: dynamic_branch
      #   default: main
```

It may be very usefully to have a special type like `dynamic_branch` which will show a list of branches in the repository, something like this
<img width="335" alt="Screenshot 2023-05-31 at 23 09 54" src="https://github.com/community/community/assets/88528265/70680e1a-2796-4b93-8162-8314f2eb64f3">

Something related - [ How I can generate user inputs choice based on files in the repo #25291](https://github.com/orgs/community/discussions/25291), because we can do that in Jenkins.

Thanks!
