### DISCUSSION TITLE
How to setup an action to clone and update the github wiki?

### DISCUSSION THREAD

**Discussion by plenzjr** [community/community#56893] [Actions] [answered]
### Select Topic Area

Question

### Body

i'm trying to run an action that clones the wiki and updates it with some docs.

here is the simple case:

```yml
name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone wiki
      run: |
        mkdir -p /tmp/wiki/
        git clone https://${{ secrets.GH_PAT }}@github.com/<username>/<repository>.wiki.git /tmp/wiki

    - name: Add file to wiki
      run: |
        echo "Hello, world!" > /tmp/wiki/newfile.md

    - name: Push to wiki
      run: |
        cd /tmp/wiki
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "docs: Added new file"
        git push
```

the action fails with the error:

`remote: Personal access tokens (classic) are forbidden from accessing this repository.`

I have the owner rule for the repository, and i created a classic token with the `repo` and `workflow` scopes.
Added it to the repository secret as `GH_PAT`.
How can I remove this restriction or which type of token/scope should i use?

**Comment by airtower-luna** [comment, marked as answer]
I'm not sure what permissions a PAT would need, but assuming the workflow is running in the repository the wiki belongs to the simplest solution is definitely to just [use the `GITHUB_TOKEN`](https://github.com/airtower-luna/hello-github-actions/blob/9bbfd8a8461fc8d3a0ec65dfcb6f6692a219e880/.github/workflows/wiki-bot.yaml#L20-L23),  in this case via `actions/checkout` (adjust `path` as needed):

```yaml
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
```

`contents: write` permissions for the job are enough. :slightly_smiling_face:
