### DISCUSSION TITLE
GitHub Actions step is hanging

### DISCUSSION THREAD

**Discussion by SasankaHPE** [community/community#56955] [Actions]
### Select Topic Area

General

### Body

I am unable to figure out where problem is, please refer the below image where slack notification step keeps on running.

![image](https://github.com/community/community/assets/128839064/40f20fb5-a15c-4a28-8f0a-46b6644c08b4)

Workflow:

```
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      id: slack-report
      if: ${{ always() }}
      env:
        MSG_MINIMAL: true
        #SLACK_CHANNEL: glcp-solution-testing-runs
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'    
        SLACK_MESSAGE: Dashboard:${{join(steps.allure-report.outputs.*, '\n')}}
        SLACK_TITLE: Cluster:${{github.event.inputs.ENVIRONMENTS}}
        #SLACK_USERNAME: glcp-sol-test
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}  
```
