### DISCUSSION TITLE
Clone repo from public reusable workflow called from private repo

### DISCUSSION THREAD

**Discussion by JamesHutchison** [community/community#57037] [Actions]
### Select Topic Area

Question

### Body

I have this reusable workflow:
https://github.com/JamesHutchison/ptyme-track/blob/github-token-secret/.github/workflows/time_tracking.yaml

I've defined the PAT secret:

```
on:
  workflow_call:
    inputs:
      base-branch:
        required: true
        type: string
      pr-number:
        required: true
        type: string
    secrets:
      PAT:
        required: true
```

And I plug it into the checkout:

```
    - name: Checkout repository
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 2
        ref: refs/pull/${{ inputs.pr-number }}/head
        token: ${{ secrets.PAT }}
```

I then call it and pass in the GITHUB_TOKEN

```
name: Get logged time
on:
  pull_request:
    paths:
      - 'gcp/.ptyme_track/*'

jobs:
  track-time:
    uses: JamesHutchison/ptyme-track/.github/workflows/time_tracking.yaml@github-token-secret
    permissions:
      pull-requests: write
    with:
      base-branch: origin/${{ github.event.pull_request.base.ref }}
      pr-number: ${{ github.event.pull_request.number }}
    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
```

However, I get an error indicating that it is unable to access it:

```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/pull/3/head:refs/remotes/pull/3/head
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/JamesHutchison/<my private repo>/' not found
```

What is the intended way to do this?
