### DISCUSSION TITLE
Windows Powershell passes successfully after a command exits with error code

### DISCUSSION THREAD

**Discussion by eighty4** [community/community#57182] [Actions] [answered]
### Select Topic Area

Question

### Body

This returns a non-zero exit code, yet `powershell` or `pwsh` continues running commands and exits successfully. I've read that GHActions sets `$ErrorActionPreference = "Stop"` implicitly and I've also tried explicitly but this only handles errors for the running of a command. Whether the command returns 0 or 1 doesn't seem to matter. How can I fail these tasks when a command is successfully started with an unsuccessful result reporting exit code?

```
  test-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: test
        shell: powershell
        run: |
          go test
```

**Comment by macrombilux** [comment]
> ### Select Topic Area
> 
> Question
> 
> ### Body
> 
> This returns a non-zero exit code, yet `powershell` or `pwsh` continues running commands and exits successfully. I've read that GHActions sets `$ErrorActionPreference = "Stop"` implicitly and I've also tried explicitly but this only handles errors for the running of a command. Whether the command returns 0 or 1 doesn't seem to matter. How can I fail these tasks when a command is successfully started with an unsuccessful result reporting exit code?
> 
> 
> 
> ```
> 
>   test-windows:
> 
>     runs-on: windows-2022
> 
>     steps:
> 
>       - uses: actions/checkout@v2
> 
>       - uses: actions/setup-go@v3
> 
>         with:
> 
>           go-version: 1.19.5
> 
>       - name: test
> 
>         shell: powershell
> 
>         run: |
> 
>           go test
> 
> ```

**Reply by eighty4** [reply]
Did you have a comment about the quote reply?

**Comment by deleugpn** [comment]
Facing this issue right now, any way to make it fail?

**Comment by eighty4** [comment, marked as answer]
`Exit $LASTEXITCODE` is the magic you're looking for.

```yaml
      - name: test util
        shell: powershell
        working-directory: util
        run: |
          $env:TMP="$env:USERPROFILE\AppData\Local\Temp"
          $env:TEMP="$env:TMP"
          go test
          Exit $LASTEXITCODE
```

Example in a workflow yaml:

https://github.com/eighty4/maestro/blob/main/.github/workflows/verify.yml#L227
