### DISCUSSION TITLE
How to Link User Site README as Profile Page README?

### DISCUSSION THREAD

**Discussion by mortonmills** [community/community#57202] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

I'm trying to link my user site repo README as my profie page README. 
As suggested from StackOverflow, I've tried creating a symlink to the repo README with this address.
"../1960s.github.io/blob/main/README.md"
Repo here:
[(https://github.com/1960s/1960s)](https://github.com/1960s/1960s)

Will be grateful for any direction on the matter

**Comment by radar-blip** [comment]
I think maybe this is what you're looking for: [Profile Readme](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme#about-your-profile-readme)

Pay attention to Step 2 in _Adding a Profile Readme_ 👍🏻

**Reply by mortonmills** [reply]
Thanks for the suggestion, I did read up on it.
I've successfully been able to get a profile README to work before.
My trouble however is getting my user repo (github.io) README to be identical to my profile README.
So when I make changes to the user repo README those changes will show up in the profile README.

**Comment by DSDmark** [comment, marked as answer]
Hi @1960s,

Your GitHub username is **1960s** and your GitHub profile is `1960s/README.md` and you have a GitHub page which is `1960s.github.io` which is also contained the same **README** file as `1960s/README.md`. So, your question is (if I understood correctly), there is a way to add those two **reamdes** to make only one. So, whenever you made change. You will not need to change both of separately.

So, if i m correct. Then, it is hard to do. But, if your end goal is to maintain both file. Then, you can do by creating GitHub page.

### First way.

- Go to your **1960s** repository on GitHub.

- Click on the **Settings** tab.

- Scroll down to the **GitHub Pages** section.

- In the **Source** dropdown, select the branch that contains your consolidated **README.md** file (typically the default branch, such as main) like this:

![image](https://github.com/community/community/assets/85744816/961c54fc-d9fd-4b15-8efe-8c812322fb13)

- Choose the root folder `("/")` as the publishing source.

- Click on the **Save** button.

In this method, you can manage your **GitHub page** on this URL `https://dsdmark.github.io/1960s/` like this [**DSDmark's profile**](https://dsdmark.github.io/DSDmark/) and [**DSDmark's GitHub page**](https://github.com/DSDmark/)

### Second way.

And other way to use GitHub action like this, which is change another repo file content.

```yml
name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Update README in otherrepo
      run: |
        # Read the contents of the README file
        readme_contents=$(cat README.md)
        
        # Clone the otherrepo repository
        git clone https://github.com/DSDmark/otherrepo.git
        
        # Update the README file in otherrepo with the contents from actionofgithub
        echo "$readme_contents" > otherrepo/README.md
        
        # Commit and push the changes
        cd otherrepo
        git config user.name "Your Name"
        git config user.email "your@email.com"
        git add README.md
        git commit -m "Update README from actionofgithub"
        git push
```
