### DISCUSSION TITLE
Is there some way to refer to the workflow file itself using `on.*.paths`

### DISCUSSION THREAD

**Discussion by aucampia** [community/community#57204] [Actions]
### Select Topic Area

Question

### Body

For example, I want to run a workflow file `.github/workflows/foo.yml` if the workflow file is updated, or if files inside `foo/` are updated.

One way to do this is to have:

```yaml
on:
  push:
    branches:
      - main
    paths:
      - 'foo/**'
      - '.github/workflows/foo.yml'

  pull_request:
    paths:
      - 'foo/**'
      - '.github/workflows/foo.yml'
```

The problem with this is though that if someone renames the file it will break. It would be nice if there was some keyword for referring to the workflow file itself, e.g.

```yaml
on:
  push:
    branches:
      - main
    paths:
      - 'foo/**'
      - '@worfklow.file'

  pull_request:
    paths:
      - 'foo/**'
      - '@worfklow.file'
```

Is there some way to do that, or is the best option to just use `.github/workflows/**` instead of the specific workflow file name?
