### DISCUSSION TITLE
Preview for creating a workflow sorts blank lines to the end

### DISCUSSION THREAD

**Discussion by jsoref** [community/community#57255] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Bug

### Body

1. Visit https://github.com/jsoref/workflow-needs/new/prerelease/.github/workflows
2. Fill in the file name field with `needs.yml`
3. Fill in the contents with:
    ![image](https://github.com/community/community/assets/2119212/f86afbec-d9ae-4e97-adef-31432e5be9d5)

```yml
on:

  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: fail
      run: 'false'

  second:
    needs:
    - first
    runs-on: ubuntu-latest
    steps:
    - name: pass?
      run: 'echo I guess?'

```

4. Click preview
    ![image](https://github.com/community/community/assets/2119212/012e02dd-c4b4-437e-9db9-8769878d888f)

Each blank line not counting the last line in the file is sorted to the end of the file.
