### DISCUSSION TITLE
How to disable action input auto conversion?

### DISCUSSION THREAD

**Discussion by retzero** [community/community#57266] [Actions]
### Select Topic Area

Question

### Body

Hello.

Here is my workflows;

```yaml
      - uses: MyAccount/TestRepo@main
        with:
          version: '2023-06-01T02:34:19'
```

And the composite action;

```yaml
inputs:
  version: 
    type: string

runs:
  using: "composite"
  steps:
    - run:  echo "${{ inputs.version }}"
      shell: bash
```

The problem is, `version` input is automatically converted into date format. 
```
Run echo "06/01/2023 02:34:19"
06/01/2023 02:34:19
```

How to disable this auto-conversion? I need the **actual** input string.

**Comment by ChristopherHX** [comment]
I would also be shocked about this, it is not expected to replace the date and change the format. Even more this doesn't happen at all in composite actions (where the parser is fully open source).

I think the following worked in the past
```yaml
      - uses: MyAccount/TestRepo@main
        with:
          version: ${{ '2023-06-01T02:34:19' || 0 }} #  || 0 is just to prevent the parser to optimize the expression away and avoid weird secret conversion rules
```
