### DISCUSSION TITLE
Can I get the environment being used for the GitHub Action from Environment Variables?

### DISCUSSION THREAD

**Discussion by brignano** [community/community#57285] [Actions]
### Select Topic Area

Question

### Body

**Problem Statement:** I need to dynamically set the corresponding API endpoint used by my Action based on environment (i.e. `dev`, `qa`, `prod`).

I spent a long time reading through all of the [Variables - GitHub Docs](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) but there doesn't seem to be an easy way to get the environment which my GitHub Action is using.

For example, I am trying to optimize `inputs` in below `.yml`,

```yml
jobs:
   # ...
   ansible:
      runs-on: [ self-hosted ]
      environment: 'dev' # I want to access this
      steps:
         - uses: MyOrgActions/iac-ansible
           with:
              environment: 'dev' # this feels redundant
   # ...
```

If I could access `jobs.ansible.environment` in my Action (i.e. `process.env.GITHUB_ACTION_ENVIRONMENT`) then I would not need the user to repeat themselves here but I haven't been able to find a good way to do that yet.
