### DISCUSSION TITLE
How to handle required status checks for branch protection when the workflow isn't always run?

### DISCUSSION THREAD

**Discussion by spenserblack** [community/community#57334] [Repositories] [answered]
### Select Topic Area

Question

### Body

For example, let's say that this is the workflow:
```yml
on:
  pull_request:
    paths: ['packages/foo/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo success
```

If I set this up to be a required status check in a branch protection, it seems like it's still required even if it's never run, for example if the PR only changes `packages/bar/...`. Is there a way to require a status check only for certain subfolders? It looks like the branch protection was waiting on the workflow to run, so the PR couldn't be merged without a protection override.

Also some feedback -- IMO the status check should be considered "passed" in this case, not "pending."
