### DISCUSSION TITLE
pushed a tag to our repository but didn't trigger any workflow

### DISCUSSION THREAD

**Discussion by DeboBurro** [community/community#57446] [Actions]
### Select Topic Area

Question

### Body

Today, I pushed tags but none of them triggered the workflows.
Yesterday, everything was fine. All the tags start with the `v` triggered the workflows.
Usually, I should see the workflow being triggered and it should find our self-hosted runners to run the jobs. But today, nothing shows on the Github Actions page. 
Our workflow is like
```
name: Workflow name

on:
  workflow_dispatch:

  push:
    # Any git tag starts with `v` be pushed to the repo will trigger this workflow
    # ex: `git push origin v1.0` or `git push origin v2.6.6`
    tags:
      - v*
```
