### DISCUSSION TITLE
How to use matrix in jobs.<job_id>.if?

### DISCUSSION THREAD

**Discussion by rea1shane** [community/community#57496] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a custom action, like this:

```yaml
jobs:
  job1:
    outputs:
      matrix: ${{ steps.outputer.outputs.VERSIONS }}
    steps:
      - id: outputer
        run: echo 'VERSIONS=["master", "1.2", "1.3"]' >> "$GITHUB_OUTPUT"

  job2:
    needs: job1
    strategy:
      matrix:
        version: ${{ fromJson(needs.job1.outputs.matrix) }}
    env:
      SKIP_FLAG: false
    steps:
      - name: step 0
        if: github.event_name == 'schedule' && matrix.version != 'master'
        run: echo "SKIP_FLAG=true" >> "$GITHUB_ENV"
      - name: step 1
        if: env.SKIP_FLAG
        run: ...
      - name: step 2
        if: env.SKIP_FLAG
        run: ...
      - name: step 3
        if: env.SKIP_FLAG
        run: ...
```

now I want to simplfy it:

```yaml
jobs:
  job1:
    outputs:
      matrix: ${{ steps.outputer.outputs.VERSIONS }}
    steps:
      - id: outputer
        run: echo 'VERSIONS=["master", "1.2", "1.3"]' >> "$GITHUB_OUTPUT"

  job2:
    needs: job1
    if: github.event_name == 'schedule' && matrix.version != 'master'
    strategy:
      matrix:
        version: ${{ fromJson(needs.job1.outputs.matrix) }}
    steps:
      - name: step 1
        run: ...
      - name: step 2
        run: ...
      - name: step 3
        run: ...
```

But wrong:  `Unrecognized named-value: 'matrix'`. Is there anyway to do this?

**Comment by airtower-luna** [comment]
I suspect it's because that'd skip the *whole* job, not just one matrix element. :thinking: 

Anyway, wouldn't it be simpler to not add `master` to your versions list in the first place?

```yaml
jobs:
  job1:
    outputs:
      matrix: ${{ steps.outputer.outputs.VERSIONS }}
    steps:
      - id: outputer
        run: | 
          if [ "${GITHUB_EVENT_NAME}" = "schedule" ]; then
              echo 'VERSIONS=["1.2", "1.3"]' >> "$GITHUB_OUTPUT"
          else
              echo 'VERSIONS=["master", "1.2", "1.3"]' >> "$GITHUB_OUTPUT"
          fi
```
