### DISCUSSION TITLE
Add dependabot config option to combine updates that belong together

### DISCUSSION THREAD

**Discussion by nostadt** [community/community#57505] [Pull Requests]
At least in the PHP world it's common to have one mono repository and then work with subtree split to create individual packages. See Symfony for example. Now, whenever the Symfony framework has a new release, I will receive a lot of PRs. I find it handy if I receive one PR to bump all changes. That can be either all in one commit, or separate commits. My primary intention is to save my time and CI runtime. Whenever I want to bump symfony, I want to bump all packages that are part of the release.

Sum up of my motivation:
- save developer time, because only one PR needs to be reviewed
- save organization costs, because less CI runs are needed to bump a framework
- reduce needed electricity, because less CI runs are needed

Implementation ideas:
Either way, I would manage it locally in each repository. I can imagine the following configuration options:

```yaml
combine_packages:
  - symfony/*
  - typo3/cms-*
```

```yaml
combine_packages:
  symfony:
    - symfony/process
    - symfony/translate
  typo3_a:
    - https://typo3.org/dependabot-combine-config.yml
  typo3_b:
    - /my-github-org/shared-dependabot-config/.github/typo3.yml
```
