### DISCUSSION TITLE
docker-compose volume mapping doesn't work in GitHub workflow.

### DISCUSSION THREAD

**Discussion by ehg-mengxu** [community/community#57502] [Actions]
### Select Topic Area

Question

### Body

I have a GitHub workflow having a step for running tests from a container brought up by docker-compose.

The docker-compose.yml:

```
services:
  test-ci:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ./coverage:/app/coverage
      - ./src:/app/src
```
However the volume mapping won't work, because when it runs `docker-compose run test-ci`, I couldn't find the mounted `/app/src`.

I did some searching and figured it could be due to the `.` needs to be referenced as `$PWD`, so I modified the docker-compose.yml, but still doesn't seem to work.

Then I tried adding OPTIONS to the workflow job:
```
jobs:
  run-tests:
    name: RUN TESTS
    runs-on: ubuntu-latest
    container:
      image: <our private image>
      options: -v /home/runner/work/<reponame>/<reponame>:/app:rw
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write
      contents: read
      packages: read
```
Because I figured `/home/runner/work` is mounted as `/__w` to the runner, and WOKDIR of the runner is set to the mounted workspace. However, with the OPTIONS, `/app` is mounted to every active container in the workflow process.

Then I changed the mounted path to something else, then the docker-compose volume mapping seems broken.

Wondering if I could get some advice on how to address this? Many thanks in advance!
