### DISCUSSION TITLE
Firebase generated pipeline triggers randomly

### DISCUSSION THREAD

**Discussion by Eindall** [community/community#57511] [Actions]
### Select Topic Area

Bug

### Body

Hello !

I've ran the command `firebase init hosting` and selected Github Actions, which generated two distinct workflow (Deploy to Firebase Hosting on merge and Deploy to Firebase Hosting on PR), according to the Firebase documentation.

Even though these workflow appears on my Github repository, I can't manage to have them run sustainably.
I'm currently pushing everything directly unto master branch as I work alone on a small "test" project, and I do not need to work with branches.

Some times the workflow run correctly, sometimes it can be 30min late, sometimes it just doesn't trigger at all, and I have to deploy manually.

Here is the content of the file `firebase-hosting-merge.yml` : 
```yml
name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    ...
```

Do I miss something ?
