### DISCUSSION TITLE
Can't get output variable

### DISCUSSION THREAD

**Discussion by tomaskatz96** [community/community#57551] [Actions]
### Select Topic Area

Question

### Body

I've created an action that runs a python code. in the action I put an output variable 
```
outputs:
  my_secure_app:
    description: 
      Appdome build output
```
in the python code I wrote this 
```
    if "GITHUB_OUTPUT" in os.environ:
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            print("{0}={1}".format("my_secure_app", my_secure_app), file=f)
```
and read the os.environ["GITHUB_OUTPUT"] to check that it has what I put in.
Then I run my action 
```
  steps:
   - uses: actions/checkout@v3
   - name: Appdome build-2secure
     id: appdome-build
     uses: Appdome/github_build-2secure@1.0
     with:
        APP_FILE: "./file.apk"
        FUSION_SET_ID: "*******************"
        SIGN_OPTIONS: **********************
        APPDOME_API_TOKEN: *********************
        SIGN_FINGERPRINT:************
   - name: Find secure app file
     id: secure_app_file
     run: |
        echo ${{ steps.appdome-build.outputs.my_secure_app }}
```
and the ${{ steps.appdome-build.outputs.my_secure_app }} is always empty even though my action finishes with success.
