### DISCUSSION TITLE
New YAML issue templates does not works with unicode

### DISCUSSION THREAD

**Discussion by xvitaly** [community/community#5761] [Projects and Issues]
Description
=====================

New YAML templates does not works with unicode.

Example 1:
```yaml
name: Сообщить об ошибке
description: Создать заявку с сообщением об ошибке, либо неточности в FAQ
labels: [bug]
body:
  - type: input
    attributes:
      label: URL страницы с ошибкой
      description: >-
        Укажите URL-адрес страницы с ошибкой в [веб-версии FAQ](https://russianfedora.github.io/FAQ/).
  - type: textarea
    attributes:
      label: Подробное описание ошибки
      description: >-
        Кратко опишите возникшую проблему, чтобы мы могли диагностировать и исправить её.
    validations:
      required: true
```

Adding `id` fixed previous issue, but introduced another one:
```
Name must be unique.
```

Example 2:
```yaml
name: Сообщить об ошибке
description: Создать заявку с сообщением об ошибке, либо неточности в FAQ
labels: [bug]
body:
  - type: input
    id: bug-url
    attributes:
      label: URL страницы с ошибкой
      description: >-
        Укажите URL-адрес страницы с ошибкой в [веб-версии FAQ](https://russianfedora.github.io/FAQ/).
  - type: textarea
    id: bug-description
    attributes:
      label: Подробное описание ошибки
      description: >-
        Кратко опишите возникшую проблему, чтобы мы могли диагностировать и исправить её.
    validations:
      required: true
```

Reproduction Steps
=====================

1. Commit YAML template with non-latin characters.
2. Open preview.

Result
=============

```
There is a problem with this template

body[0]: id must be of type String and cannot be empty.
```

Screenshots
=================

![image](https://user-images.githubusercontent.com/966711/134339293-e16f1591-1f80-4fdc-bac2-657890009c0e.png)
