### DISCUSSION TITLE
Checkout error using permissions: id-token: write

### DISCUSSION THREAD

**Discussion by matthieuEv** [community/community#57621] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi,
I'm trying to publish to Pypi using pypa/gh-action-pypi-publish@release/v1.8
```YAML
pypi-publish:
    # needs: [Windows, Ubuntu, macOS]
    needs: [Ubuntu]
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: mkdir
        run: |
          ls -l pypi_packaging
          mkdir -p pypi_packaging/<project-name>/
          echo "============================="
          ls -l pypi_packaging
      - name: Swig __init__.py
        run: |
          swig -python -c++ <project-name>.i
          mv <project-name>.py pypi_packaging/<project-name>/__init__.py
      - name: Download artifact so
        uses: actions/download-artifact@v2.1.1
        with:
          name: <project-name>.so
          path: dir_<project-name>.so
      - name: Move <project-name>.
        run: |
          mv dir_<project-name>.so/<project-name>.so pypi_packaging/<project-name>/_<project-name>.so
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: |
          ls -l
          echo "============================="
          cd pypi_packaging
          ls -l
          python3 -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: |
          ls -l
          echo "============================="
          cd pypi_packaging
          ls -l
          python3 -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          password: ${{ secrets.TOKEN }}
          repository-url: https://test.pypi.org/legacy/
```
i was just testing so i use the example [here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/), but when i ran my yaml file, i encountered the error: 
```BASH
Run pypa/gh-action-pypi-publish@release/v1.8
  with:
    repository-url: https://test.pypi.org/legacy/
    user: __token__
    repository_url: https://upload.pypi.org/legacy/
    packages_dir: dist
    verify_metadata: true
    skip_existing: false
    verbose: false
    print_hash: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.11/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.11/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.11/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.11/x64/lib
/usr/bin/docker run --name ed866e33f4ee4903a343818967608878d84434_a330de --label ed866e --workdir /github/workspace --rm -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "INPUT_PASSWORD" -e "INPUT_REPOSITORY-URL" -e "INPUT_USER" -e "INPUT_REPOSITORY_URL" -e "INPUT_PACKAGES-DIR" -e "INPUT_PACKAGES_DIR" -e "INPUT_VERIFY-METADATA" -e "INPUT_VERIFY_METADATA" -e "INPUT_SKIP-EXISTING" -e "INPUT_SKIP_EXISTING" -e "INPUT_VERBOSE" -e "INPUT_PRINT-HASH" -e "INPUT_PRINT_HASH" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/<repo-name>/<folder>":"/github/workspace" ed866e:33f4ee4903a343818967608878d84434  "__token__" "" "https://test.pypi.org/legacy/" "" "" "" "false" ""
Notice: Attempting to perform trusted publishing exchange to retrieve a temporary short-lived API token for authentication against https://test.pypi.org/legacy/ due to __token__ username with no supplied password field
Error: Trusted publishing exchange failure: 
OpenID Connect token retrieval failed: GitHub: missing or insufficient OIDC token permissions, the ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variable was unset

This generally indicates a workflow configuration error, such as insufficient
permissions. Make sure that your workflow has `id-token: write` configured
at the job level, e.g.:

'''yaml
permissions:
  id-token: write
'''

Learn more at https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings.
```
So i try adding the permission as it is said
```YAML
permissions:
  id-token: write
```
```YAML
pypi-publish:
    # needs: [Windows, Ubuntu, macOS]
    needs: [Ubuntu]
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
          [....]
```
But now i got the error `repository 'https://github.com/<username>/<project-name>/' not found`
```YAML
Run actions/checkout@v3
  with:
    fetch-depth: 0
    token: ***
    repository: <username>/<project-name>
    ssh-strict: true
    persist-credentials: true
    clean: true
    lfs: false
    submodules: false
    set-safe-directory: true
Syncing repository: <username>/<project-name>
Getting Git version info
  Working directory is '/home/runner/work/<project-name>/<project-name>'
  /usr/bin/git version
  git version 2.40.1
Temporarily overriding HOME='/home/runner/work/_temp/39eba631-bb64-4b5d-bbf8-de64a82dc512' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/<project-name>/<project-name>
Deleting the contents of '/home/runner/work/<project-name>/<project-name>'
Initializing the repository
  /usr/bin/git init /home/runner/work/<project-name>/<project-name>
  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint: 
  hint: 	git config --global init.defaultBranch <name>
  hint: 
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint: 
  hint: 	git branch -m <name>
  Initialized empty Git repository in /home/runner/work/<project-name>/<project-name>/.git/
  /usr/bin/git remote add origin https://github.com/<username>/<project-name>
Disabling automatic garbage collection
  /usr/bin/git config --local gc.auto 0
Setting up auth
  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/<username>/<project-name>/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 20 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/<username>/<project-name>/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 17 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/<username>/<project-name>/' not found
  Error: The process '/usr/bin/git' failed with exit code 128
```
I tried searching on google and i found [this issue](https://github.com/actions/checkout/issues/254) on the repo of the checkout action. It is said that it could be an error of the action System, so i checked the [Github Status Page](https://www.githubstatus.com/) but all system was operationnal. Someone said that it could be the [permissions](https://github.com/actions/checkout/issues/254#issuecomment-1118411040), i checked mine and that was all good.
![image](https://github.com/community/community/assets/95125079/80e4c360-7d25-4562-b2ea-868edd38c2b4)
![image](https://github.com/community/community/assets/95125079/0263b7d8-2010-4819-a663-b1cb45935591)
![image](https://github.com/community/community/assets/95125079/8f9a1bbb-cbf5-4eb4-9cd3-86a922289af2)

If someone here can help me, that would be very helpfull, thanks

**Comment by airtower-luna** [comment, marked as answer]
Once you add a `permissions` setting to a job/workflow, it will have *only* the listed permissions instead of the defaults. That's why it now can't read the repository, which requires the `contents` permission. If read access is sufficient, just add that:

```yaml
permissions:
  contents: read
  id-token: write
```
