### DISCUSSION TITLE
Does a workflow triggered on merge know about which PR/commit triggered it?

### DISCUSSION THREAD

**Discussion by kaykhan** [community/community#57631] [Actions]
### Select Topic Area

Question

### Body

We have 2 workflows, `terraform-ci` and `terraform-cd`.

`terraform-ci` is triggered on a `pull_request`
`terraform-cd` is triggered on a push to `main`

All code must be pushed to main via a pull_request.

In `terraform-ci` we create an artifact which we would like `terraform-cd` to make use of. We need an identifier which both `terraform-ci` and `terraform-cd` know about. We will use this identifier to name the artifact. 

We would like some way for us to know within `terraform-cd` which pull request was merged/commited to main. So that we can fetch an artifact created by `terraform-ci`based on the common identifier.

**terraform-ci.yml**

```
name: terraform-ci

on:
  pull_request:

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
       - name: Terraform Plan
         id: plan
         continue-on-error: true
         run: |
           tfplan_identifier=${{ github.event.pull_request.base.sha }}
           echo "tfplan_identifier=$tfplan_identifier" >> $GITHUB_OUTPUT
           terraform plan -var-file="prod.tfvars" -input=false -no-color -out=${tfplan_identifier}
           ls
       - uses: actions/upload-artifact@v3
         with:
           name: ${{ steps.plan.outputs.tfplan_identifier}}
           path: ${{ steps.plan.outputs.tfplan_identifier}}        
        
 ```
 
 **terraform-cd.yml**
 
 ```
 name: terraform-cd

on:
  push:
    branches: [ "main" ]

concurrency: terraform-cd


jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
       - name: Terraform Plan
         id: plan
         run: |
           tfplan_identifier = ???
       - uses: actions/downloa-artifact@v3
         with:
           name: ${{ steps.plan.outputs.tfplan_identifier}}
           path: ${{ steps.plan.outputs.tfplan_identifier}}        
        
```
