### DISCUSSION TITLE
Docker noob, trouble spinning up docker container after building through GitHub Actions

### DISCUSSION THREAD

**Discussion by jconnorbuilds** [community/community#57671] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm new to GitHub Actions and Docker, so I'm hoping my question has a simple answer, but been banging my head against a wall for a day now to no avail... 

I ran through this tutorial:
https://testdriven.io/blog/deploying-django-to-linode-with-docker-and-github-actions/

I've also added a Tag images command right after Build images:
```
      - 
        name: Tag images
        run: |
          docker tag npt_prod:latest ${{ env.WEB_IMAGE }}:latest
          docker tag npt_nginx_prod:latest ${{ env.NGINX_IMAGE }}:latest
```

My github action runs with no issues until the very last step of the workflows file:
```
      - name: Build and deploy images on Linode
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp  -o StrictHostKeyChecking=no -r ./.env ./docker-compose.prod.yml root@${{ secrets.LINODE_IP_ADDRESS }}:/app
          ssh -o StrictHostKeyChecking=no root@${{ secrets.LINODE_IP_ADDRESS }} << 'ENDSSH'
            cd /app
            source .env
            docker login ghcr.io -u $NAMESPACE -p $PERSONAL_ACCESS_TOKEN
            docker pull $WEB_IMAGE
            docker pull $NGINX_IMAGE
            sudo docker compose -f docker-compose.prod.yml up -d
          ENDSSH
```
here's the end of the log showing the error:
```
nginx Pulling 
web Pulling 
nginx Error 
web Error 
2 errors occurred:
	* unable to prepare context: path "./app" not found
	* unable to prepare context: path "./nginx" not found
```

On my linode server, /app contains `.env` and `docker-compose.prod.yml.` It seems like `docker compose build` is looking for my Dockerfile, but I was under the impression that my docker images are already built, so I can just run them. When I add "app" and "nginx" directories, I get an error saying that the Dockerfiles couldn't be found. 

Adding my `docker-compose.ci.yml` file for more context:
```
version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: npt_prod:latest
    command: gunicorn New_Pipeline.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
    - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    image: npt_nginx_prod:latest
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
```

EDIT: Before, I was using a single dockerfile, `docker-compose.prod.yml` (contents above), in both the build and deploy stages, which was causing it to build twice. Now, I've re-named that `docker-compose.ci.yml`, and have a new file called `docker-compose.prod.yml `which looks like this:

```
version: '3.8'

services:
  web:
    image: ghcr.io/phoenixudon/new_pipeline/web:latest
    env_file:
      - ./.env

  nginx:
    image: ghcr.io/phoenixudon/new_pipeline/nginx:latest
    env_file:
      - ./.env
    ports:
      - 80:80
```
This was a shot in the dark based off of a stackoverflow answer I read, and github actions is now finishing with no errors, but the containers shut down right after startup, with no errors in the logs. For what it's worth, I'm able to pull the containers down from github manually and build them with `docker-compose.ci.yml`, and it works fine.

Where am I going wrong? Would be grateful for any advice pointing me in the right direction.

**Comment by jconnorbuilds** [comment, marked as answer]
Reading more about using multiple docker-compose files led me to a solution. Ended up with docker-compose.prod.yml that looked like this, which worked.

```
services:
  web:
    image: ghcr.io/<username>/<repo name>/web:latest
    command: gunicorn New_Pipeline.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
    - 8000
    env_file:
      - ./.env
  nginx:
    image: ghcr.io/<username>/<repo name>/nginx:latest
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
```
