### DISCUSSION TITLE
Prevent workflow jobs run twice on push and PR

### DISCUSSION THREAD

**Discussion by chraebsli** [community/community#57827] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a GitHub workflow file which I use for testing an application.
These run on push and on pull requests, so I see when it fails after pushing and when I want to merge it to the main branch.

The problem: If I created a pull request and push afterward to the branch which should be merged, all jobs run twice: one for the push event and one for the PR event.

How can I prevent it to execute all jobs twice?

This is how my `ci.yml` file looks like:
```yaml
name: CI
on: [ push, pull_request ]
jobs:
  job1: ...
  job2: ...
```

**Comment by sebthom** [comment, marked as answer]
Try this: 
```yaml
name: CI
on: [ push, pull_request ]
jobs:
  job1:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    ...

  job2:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    ...
```

Found at https://github.com/zopefoundation/meta/issues/145#issuecomment-1247814559 and https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/

**Comment by Timmmm** [comment]
Not tested, but maybe this works?

```
on:
  pull_request:
  push:
    branches: ["master"]
```
