### DISCUSSION TITLE
Github Action in locally built container

### DISCUSSION THREAD

**Discussion by arykov** [community/community#57842] [Actions]
### Actions

Question

### Body

Suppose scenario where I don't want to use container registry and docker image is built locally in a job preceding the one supposed to run in the container. The way I am trying to do it does not work as container is trying to pull from registry and predictably fails.
A question is similar to the one posted here:
https://stackoverflow.com/questions/61154750/use-local-dockerfile-in-a-github-action

```
jobs: 
  checkout:
   ...
  build-custom-container:
    needs: checkout
    runs-on: [self-hosted-gha]
    steps:
    - run: |
           docker build --rm -t mytag --no-cache=true . -f Dockerfile
  build:
    needs: build-custom-container
    container:
        image: mytag
    steps:
     - run: |
     ....
```
