### DISCUSSION TITLE
Download non-public images inside Actions

### DISCUSSION THREAD

**Discussion by jeffstoner-scilo** [community/community#57969] [Enterprise]
### Select Topic Area

Product Feedback

### Body

Platform: GitHub Enterprise Server 3.9.0 (on-prem)

To help with FedRamp certification and internal security requirements, we have to compartmentalize our code, processes, and users (ie, certain people only see certain code for certain projects.) We are trying to create reusable Actions that use Docker images. Example:

```
---
name: "Complex Action"
description: "Action to accomplish complex stuff"
inputs:
  input1:
    description: "Input #1"
    default: "Rumplestiltskin"
runs:
  using: 'docker'
  image: 'docker://containers.<GHES_HOSTNAME>/<ORG>/complex-action:v1.0.0'
```

Currently, using Images in an Action _requires_ the image to be accessible via a public registry:
"a public image in Docker Hub or another registry"
ref: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsimage

This completely breaks our desired security model since all images would be accessible to all users across all projects.

What we need is a way to log in to a container registry in an Action to pull the image. Ideally, the built-in Container Registry in GitHub should use the existing GITHUB_TOKEN for authentication to the registry. And, because we use a 3rd party (on-prem) container registry, we would also like to be able to log in and pull images from there, too.

Related discussions: #45536 #50548 #30173
