### DISCUSSION TITLE
Unable to recognize installed python scripts in a conda environment on Windows and unable to conda init on MacOS runners

### DISCUSSION THREAD

**Discussion by ZhangxiJesseFeng** [community/community#57997] [Actions] [answered]
### Continuous integration - Runner issues

Question

### Body

The immediate errors are as the title says:

1. In a windows runner, the workflow successfully built an environment based on a specified environment file. Using conda env list, it shows that the environment is visible. Using conda activate, it has no errors on activating the environment (of course there is no visual clue as to whether if the environment is actually active). On my own Windows machine, after activating the environment, the shell was able to auto-complete the installed "myenv-" scripts, but it fails in the runner with error: `The term 'myenv-config' is not recognized as a name of a cmdlet, function, script file, or executable program.`
2. In a MacOS runner, the workflow successfully built the environment from a conda-lock file. But when attempting to conda activate, it returns error: `CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'. To initialize your shell, run $ conda init <SHELL_NAME>`, despite the `conda init` and `source` commands ran before it returned no issues.

Can anyone help take a look and see where the problem might be? Thanks! - Jesse

```
  build-on-windows:
    name: Build my-env von Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - run: conda --version
      - run: conda env create -f environment_windows.yml
      - run: conda list
      - run: conda info --envs
      - run: conda activate my-env
      - run: myenvv-config 

  build-on-macos:
    name: Build my-env on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - run: conda --version
      - run: which conda
      - run: sysctl -a | grep brand
      - run: conda create --name test-env --file conda-osx-64.lock
      - run: conda init bash
      - run: echo ". /usr/local/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
      - run: source ~/.bashrc
      - run: conda activate test-env
```
