### DISCUSSION TITLE
Invoking a workflow inside another workflow

### DISCUSSION THREAD

**Discussion by vansh2552** [community/community#58000] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm trying to construct a parent child kind of architecture where a parent workflow will invoke a child workflow dynamically. I've tried using workflow_run but it invoked the child workflow after the completion of parent workflow but I want such a mechanism where I could give a command in parent workflow to execute the child workflow.

**Comment by jge162** [comment]
Easy peasy, use [Repository_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) make the child listen for the parent and trigger.

**Comment by vansh2552** [comment]
@jge162 Thanks for the reply. Can you give an example for this how can I trigger a child workflow from a parent workflow.

**Reply by jge162** [reply, marked as answer]
Sure I just tested both actions in my debug repo. Ran perfect. Create two separate yaml files. Parent.yml and child.yml or edit names as you please per your use case. Report back if you need anything else. 

```
name: VANSH2552 Parent Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger_child_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Child Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}
          event-type: run-child-workflow
```

```yaml
name: VANSH2552 Child Workflow

on:
  repository_dispatch:
    types: [run-child-workflow]

jobs:
  child_job:
    runs-on: ubuntu-latest

    steps:
      - name: Child Workflow Step
        run: |
          echo "Child workflow is running"
          # VANSH2552 child workflow 
```
