### DISCUSSION TITLE
Transffering contents from one file to another

### DISCUSSION THREAD

**Discussion by vansh2552** [community/community#58001] [Actions]
### Select Topic Area

Question

### Body

I am trying to copy the data from one yaml file to another inside a github actions step. I have used this command to do so
 Copy-Item -Path ".github\\workflows\\src.yaml" -Destination ".github\\workflows\\dest.yaml" -Force
 The thing is that inside the workspace it is getting done, a dest.yaml file is getting generated and the content is getting copied but it is not reflecting on the github repo. No file is getting generated inside my github repositary. Why is this happening. Is there any other way I can achieve this transfer of contents from one file to another?

**Comment by jge162** [comment]
To push the data you must use git commands. Are you doing that? I can’t tell if you are from your questions. But, that is what I believe is your issue. 

Here is a basic example GitHub action. You must obviously update for your use case. 

```yaml
name: Vansh2552 Copy File Example

on:
  push:
    branches:
      - main

jobs:
  copy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy file
        run: |
          cp .github/workflows/src.yaml .github/workflows/dest.yaml

      - name: Configure Git
        run: |
          git config --global user.name "Vansh2552”
          git config --global user.email "Vansh2552@email.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update dest.yaml"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
   ```

**Reply by airtower-luna** [reply]
You really should be using `git push` instead of calling a third-party action. It's both simpler and much more secure, and `actions/checkout` sets up branch and credentials already. :slightly_smiling_face:

**Reply by jge162** [reply]
Correct I agree. Was just trying to give basic example but over complicated it. 👍🤝

**Reply by jge162** [reply]
@vansh2552 here is updated version more simplified 

```yaml
name: Vansh2552 Copy File Example

on:
  push:
    branches:
      - main

jobs:
  copy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy file
        run: |
          cp .github/workflows/src.yaml .github/workflows/dest.yaml

      - name: Configure Git
        run: |
          git config --global user.name "Vansh2552"
          git config --global user.email "Vansh2552@email.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update dest.yaml"

      - name: Push changes
        run: git push origin main
 ```
