### DISCUSSION TITLE
How to write a loop in Github Action?

### DISCUSSION THREAD

**Discussion by mendax1234** [community/community#58007] [Actions] [answered]
### Select Topic Area

Question

### Body

How to write a loop in Github Action?

**Comment by jge162** [comment, marked as answer]
Mendax loop example 

```yaml
name:  Mendax Example

on:
  push:
    branches:
      - main

jobs:
  loop_job:
    runs-on: ubuntu-latest

    steps:
      - name: Mendax Loop through numbers
        id: loop
        run: |
          for i in 1 2 3 4 5
          do
            echo "Mendax Current number: $i"
          done
 ```
