### DISCUSSION TITLE
How can I pass credentials (password) from JOB1 to JOB2

### DISCUSSION THREAD

**Discussion by stranger900** [community/community#58017] [Actions]
### Select Topic Area

Question

### Body

How can I pass credentials (password) from JOB1 to JOB2

**Comment by stranger900** [comment]
.. in GitHub Actions pipeline

**Comment by HappyMicky0317** [comment]
One way to pass credentials from JOB1 to JOB2 is by using a credential store. You can store the password in the credential store and then retrieve it in JOB2. Another option is to use environment variables to pass the password from JOB1 to JOB2. You can set the password as an environment variable in JOB1 and then access it in JOB2.

**Comment by dumitrux** [comment]
To prevent the password value from appearing in the logs, you can mask the value when working with Bash.
```
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      secret-password: ${{ steps.set-password.outputs.secret-password}}
    steps:
      - id: set-password
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-password=$the_secret" >> "$GITHUB_OUTPUT"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use that secret output (protected by a mask)
        run: |
          echo "The password is ${{ needs.job1.outputs.secret-password}}"
```
