### DISCUSSION TITLE
Skip approval for specific jobs

### DISCUSSION THREAD

**Discussion by lestermarch** [community/community#58020] [Actions]
### Select Topic Area

Question

### Body

Currently, when a job is associated with an environment for which there are required reviewers the job will always need to be approved before running.

In some cases, the environment context is required for the job to retrieve environment-specific variables and/or secrets even if approval is not required.

For example, when using Terraform to deploy infrastructure via GitHub Actions it is reasonable to split the `plan` and `apply` steps into separate jobs. Paired with required reviewers this allows a reviewer to check the plan output from the `plan` job before approving the second `apply` job. However, if both jobs are associated with the same environment (e.g. to retrieve environment-specific credentials) then a reviewer will need to approve the `plan` job. 

One alternative is to have seperate environments e.g. `prod-plan`, `prod-apply` with protection rules only associated with `prod-apply`. However this would then require duplication of environment-specific variables and/or secrets.

It would be useful if an attribute was added to the `jobs.<job_id>.environment` object to signify that approval is not required for that specific job, irrespective of the environment context it runs in. For example:  

```yaml
jobs:
  plan:
    name: 'Plan'
    runs-on: ubuntu-latest
    env:
      CREDS: ${{ secrets.CREDS }}
    environment:
      name: 'Prod'
      skip-approval: true # Suggestion

  apply:
    name: 'Apply'
    runs-on: ubuntu-latest
    env:
      CREDS: ${{ secrets.CREDS }}
    environment:
      name: 'Prod' 
```

Is there some other way of accomplishing this that I may be missing?
