### DISCUSSION TITLE
I do not find the button **Run workflow** to run it manually.

### DISCUSSION THREAD

**Discussion by ZedZipDev** [community/community#58022] [Actions] [answered]
### Select Topic Area

Question

### Body

I read the doc https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
and p4.
4. Above the list of workflow runs, select **Run workflow**.

But I do not find this button **Run workflow**.  The action is running automatically after files were changed in repository.
What I do wrong?

**Comment by jge162** [comment]
Where is your action to verify its setup correctly. Just the on part. Run workflow is in the action tab. Select action. You want to run manually. Then select run workflow

**Comment by ZedZipDev** [comment]
My action executes automatically, I see the log etc. But I cannot run it because I do not find the button.
![workflows](https://github.com/community/community/assets/25686753/865d0f76-3106-4e64-b322-a1f0151d1b37)

**Reply by jge162** [reply]
I need to see the on section to verify it is correct. Just that part of the GitHub action.

**Reply by ZedZipDev** [reply]
Where is it?

**Reply by jge162** [reply]
At the top of the GitHub action. 

This part

```yaml
on:
  push:
    branches:
      - main
```

**Reply by ZedZipDev** [reply]
Yes, I have this in my yml file. But I have no "Run workflow" what described in p.4 here https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

**Reply by ZedZipDev** [reply]
That is my yml file 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - run: dotnet --version
      - run: dotnet build

**Reply by jge162** [reply]
You are missing workflow_dispatch: that’s why it’s not working for you

**Reply by jge162** [reply, marked as answer]
Add this 

```yaml
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - run: dotnet --version
      - run: dotnet build
```
