### DISCUSSION TITLE
What is incorrect in my yml file?

### DISCUSSION THREAD

**Discussion by ZedZipDev** [community/community#58047] [Actions]
### Select Topic Area

Question

### Body

I have created the workflow but it completed with error:
```
Run dotnet tool install -g Amazon.Lambda.Tools
  dotnet tool install -g Amazon.Lambda.Tools
  shell: /usr/bin/bash -e {0}
  env:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/PM[2](https://github.com/ZedZipDev/PM2AWS/actions/runs/5268304907/jobs/9524787387#step:4:2)AWS/PM2AWS/./Services'. No such file or directory
```

Here is my file:
```
name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./Services

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      #working-directory: ./Services
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Restore dependencies
      run: dotnet restore PM2AWS.sln
    - name: Build
      run: dotnet build --no-restore PM2AWS.sln
    - name: Deploy to Lambda
      working-directory: ./Services/ApiServices
      run: dotnet lambda deploy-serverless

```

What is incorrect and how to fix it?
