### DISCUSSION TITLE
[Issue Forms] type:markdown heading and paragraph not rendered for submitted issue

### DISCUSSION THREAD

**Discussion by mloskot** [community/community#58049] [Projects and Issues] [answered]
### Select Topic Area

Bug

### Select Feature Area

- [X] Issues (The feature that allows you to track ideas, feedback, tasks, or bugs for work on GitHub. Not for any issue you are having).
- [ ] Projects (For planning and tracking work on GitHub - not any open source or other type of project).

### Body

1. Go to your **private** GitHub repository
2. Create GitHub form with `type: markdown` according to https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#example-of-markdown and according to the notice in the blue TIP box , save it as `test.yaml`

    ```yaml
    ---
    name: Test
    description: Submit request
    title: "[request] <feature>"
    body:
    - type: markdown
      attributes:
        value: "## Thank you for contributing to our project!"
    - type: markdown
      attributes:
        value: |
          Thanks for taking the time to fill out this bug report.
          
    - type: textarea
      id: repro
      attributes:
        label: Reproduction steps
        description: "How do you trigger this bug? Please walk us through it step by step."
        value: |
          1.
          3.
          4.
          ...
        render: bash
      validations:
        required: true
    ```

3. Go to your GitHub repository and preview `.github/ISSUE_TEMPLATE/test.yml`, and notice the `type: markdown` fields are rendered as expected
    
    ![image](https://github.com/community/community/assets/80741/2396cb45-f10b-4cb1-8e60-cfd33e501523)

4. Create new issue using the `test.yaml` form, submit it.
5. Observe the `type: markdown` fields are not rendered, are gone completely

    ![image](https://github.com/community/community/assets/80741/80e218cd-ca8d-4395-aa18-d51bb6c54f71)

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
