### DISCUSSION TITLE
Cannot pull base image (private) from ghcr.io using GITHUB_TOKEN

### DISCUSSION THREAD

**Discussion by oleg-andreyev** [community/community#58083] [Actions]
### Select Topic Area

Bug

### Body

Buildx logs

```
time="2023-06-14T21:12:04Z" level=debug msg=resolving host=ghcr.io spanID=49330bdae1d7e96c traceID=1abec7fab47e46f63eeb5f3a70a84cae
  time="2023-06-14T21:12:04Z" level=debug msg="do request" host=ghcr.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=buildkit/v0.11 request.method=HEAD spanID=49330bdae1d7e96c traceID=1abec7fab47e46f63eeb5f3a70a84cae url="https://ghcr.io/v2/atta-1/pim-base/manifests/latest"
  time="2023-06-14T21:12:04Z" level=debug msg="fetch response received" host=ghcr.io response.header.content-length=73 response.header.content-type=application/json response.header.date="Wed, 14 Jun 2023 21:12:04 GMT" response.header.www-authenticate="***"[https://ghcr.io/token\](https://ghcr.io/token/)",service=\"ghcr.io\",scope=\"repository:atta-1/pim-base:pull\"" response.header.x-github-request-id="28C0:0C38:3A4E38:53AF31:648A2D24" response.status="401 Unauthorized" spanID=49330bdae1d7e96c traceID=1abec7fab47e46f63eeb5f3a70a84cae url="https://ghcr.io/v2/atta-1/pim-base/manifests/latest"
  time="2023-06-14T21:12:04Z" level=debug msg=Unauthorized header="***"[https://ghcr.io/token\](https://ghcr.io/token/)",service=\"ghcr.io\",scope=\"repository:atta-1/pim-base:pull\"" host=ghcr.io spanID=49330bdae1d7e96c traceID=1abec7fab47e46f63eeb5f3a70a84cae
  time="2023-06-14T21:12:04Z" level=debug msg="do request" host=ghcr.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=buildkit/v0.11 request.method=HEAD spanID=49330bdae1d7e96c traceID=1abec7fab47e46f63eeb5f3a70a84cae url="https://ghcr.io/v2/atta-1/pim-base/manifests/latest"
  time="2023-06-14T21:12:04Z" level=debug msg="fetch response received" host=ghcr.io response.header.content-length=86 response.header.content-type=application/json response.header.date="Wed, 14 Jun 2023 21:12:04 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.x-github-request-id="28C0:0C38:3A4E3E:53AF3B:648A2D24" response.status="403 Forbidden" spanID=49330bdae1d7e96c traceID=1abec7fab47e46f63eeb5f3a70a84cae url="https://ghcr.io/v2/atta-1/pim-base/manifests/latest"
  time="2023-06-14T21:12:04Z" level=error msg="/moby.buildkit.v1.frontend.LLBBridge/Solve returned error: rpc error: code = Unknown desc = ghcr.io/atta-1/pim-base:latest: pulling from host ghcr.io failed with status code [manifests latest]: 403 Forbidden"
  ghcr.io/atta-1/pim-base:latest: pulling from host ghcr.io failed with status code [manifests latest]: 403 Forbidden
```

Action
```yaml
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/atta-1/pim-release
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/php/prod.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

Replaced GITHUB_TOKEN with PAT (and everything is passing)
