### DISCUSSION TITLE
How to populate $GITHUB_OUTPUT from Windows runner?

### DISCUSSION THREAD

**Discussion by Integralist** [community/community#58166] [Actions] [answered]
### Select Topic Area

General

### Body

The following code runs fine on Linux and macOS but not Windows...

```yaml
run: |
  echo "gobuild=$(go env GOCACHE)" >> $GITHUB_OUTPUT
  echo "gomod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
```

I tried following this approach https://www.jamescroft.co.uk/setting-github-actions-environment-variables-in-powershell/ but it didn't work...

```yaml
shell: pwsh
run: |
  echo "gobuild=$(go env GOCACHE)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
  echo "gomod=$(go env GOMODCACHE)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
```

Does anyone know how to get this working?

Thanks!
