### DISCUSSION TITLE
actions/cache@v3 errors with lots of "Cannot open: File exists"

### DISCUSSION THREAD

**Discussion by Integralist** [community/community#58174] [Actions]
### Select Topic Area

Question

### Body

👋🏻 

I have the following step that caches/restores a directory: 

```yaml
- name: Retrieve Go Paths
  shell: bash
  run: |
    echo "gomod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
  id: go-cache-paths
  
- name: Go Mod Cache
  uses: actions/cache@v3
  with:
    path: ${{ steps.go-cache-paths.outputs.gomod }}
    key: ${{ runner.os }}-lint-go-mod-${{ hashFiles('**/go.sum') }}
```

But every time it tries to restore the cache it complains that the file already exists.

Interestingly, it errors like this for Linux and macOS but not Windows? 🤔 

> **NOTE:** In case it's relevant, I have two separate jobs (one that only runs on Linux, and the other using a matrix to run on all three platforms: Linux, macOS and Windows) and both jobs (for Linux) are effectively caching `/home/runner/go/pkg/mod`. I thought that maybe because they both can run in parallel there would be a race condition of sorts and so I made the second job `need` the first but that made no difference and the same error persisted (and besides, the error happens with macOS and that's only run on one of the jobs). 

Here is what the errors look like...

<img width="1320" alt="Screenshot 2023-06-15 at 19 19 40" src="https://github.com/community/community/assets/180050/8a33de25-ea0e-4bc4-a4fc-1e91b16ef4bb">

**EDIT:** I did a bit more research and it seems that it _might_ be a permissions issue with where the files are being extracted to (the directory path to be cached is `/home/runner/go/pkg/mod`).
