### DISCUSSION TITLE
Installing custom development tool

### DISCUSSION THREAD

**Discussion by vitara-srinivasan** [community/community#58236] [Actions]
### Select Topic Area

Question

### Body

My dev toolset is e2studio from Renesas Electronics. I would like to install this on a windows based github runner.

Guidance on such runners would be appreciated.

Srini

**Comment by the-officialjosh** [comment]
To set up a Windows-based GitHub runner and install e2studio from Renesas Electronics, you can follow these general steps:

1. Set up a Windows machine: You'll need a Windows machine to act as the GitHub runner. This can be a physical or virtual machine running Windows.

2. Create a GitHub repository: If you haven't already, create a repository on GitHub to host your project.

3. Install Git: Download and install Git on the Windows machine. You can get it from the official Git website: https://git-scm.com/downloads

4. Install the GitHub runner: Go to your GitHub repository, navigate to the "Actions" tab, and click on "New workflow." Follow the prompts to create a new workflow file.

5. Configure the runner: In the workflow file, specify the configuration for the GitHub runner. You'll need to define the operating system as Windows and provide other necessary settings. Here's an example:

```yaml
name: Windows Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Renesas e2studio
      run: |
        # Install e2studio
        # Add any other necessary installation commands here
```

6. Save and commit the workflow file: Save the workflow file in your repository with a meaningful name, such as `.github/workflows/windows.yml`.

7. Install e2studio: In the workflow file, after the "Set up Renesas e2studio" step, add the necessary commands to download and install e2studio. You'll need to find the appropriate download link and installation instructions from the Renesas Electronics website.

8. Commit and push changes: Commit the changes to the workflow file and push them to your GitHub repository.

9. Start the runner: Go back to the "Actions" tab in your GitHub repository, and you should see the new workflow. Click on it to start the runner, and it will execute the steps defined in the workflow file, including the installation of e2studio.

Please note that the specific commands and steps for installing e2studio will depend on the installation package provided by Renesas Electronics. Make sure to refer to their documentation for the exact steps.

Additionally, keep in mind any licensing requirements for using e2studio, as you may need to provide appropriate licenses or agreements during the installation process.
