### DISCUSSION TITLE
Start "services" in a job that has a reusable workflow

### DISCUSSION THREAD

**Discussion by cezar-tech** [community/community#58243] [Actions]
### Select Topic Area

Question

### Body

Since this is not solved here: https://github.com/actions/runner/issues/822

I'm in need of finding workarounds. The issue is many projects will use a reusable workflow, but each project has its own needs for service containers, and absolutely none of them need all services at once, which would happen if I just keep adding services in my reusable workflow's job.

The services are required for integration tests in my repos.

As an example's sake, maybe this can be easier to achieve:
```
jobs:
  main:
    uses: path/to/my/reusable/workflow/workflow.yaml@branch
    services: # start only the services required for my particular case, and not all of them inside the reusable workflow
      consul: # consul's container config, not relevant for the example
      vault: # vault's container config, not relevant for the example
```
Let's say I have projects that need distinct services, how can I achieve this without starting up all of them inside my reusable workflow ?
