### DISCUSSION TITLE
Github Actions with self-hosted runners sometimes not finding working directory

### DISCUSSION THREAD

**Discussion by jwechsler10** [community/community#58278] [Actions] [answered]
### Select Topic Area

Bug

### Body

I've noticed that randomly when using self-hosted runners, my workflow will fail sometimes when I've got a `working-directory` specified for some commands. I am checking out my code before I try do use `working directory`. My workflow looks like:

```
jobs:
  deploy-terraform:
    name: Run terraform
    runs-on: self-hosted
    env:
      TF_DIR: terraform/${{ inputs.env }}
      AWS_REGION: ${{ inputs.region }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: <redacted-role-arn>
          role-session-name: ghActionsECR
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve -no-color
        working-directory: ${{ env.TF_DIR }}
        continue-on-error: false
```
I'll get the following error: `An error occurred trying to start process '/usr/bin/bash' with working directory '/opt/actions-runner/_work/redacted-org-name/redacted-repo-name/terraform/qa'. No such file or directory`. However, it doesn't always happen, just occasionally. When I go onto the server I can see the directory is there at the path specified in the error.

**Comment by airtower-luna** [comment]
What crates the `terraform/` directory? The checkout action won't, because the repository is placed in a `main/` directory. And of course the `inputs.env` value might mess with things.

**Reply by jwechsler10** [reply]
It's in the repo that's being checked out, so checking it out to the `main` directory won't create it?

**Reply by airtower-luna** [reply]
Your repo get checked out into a `main/` directory, that's what the `path` input does:

```yaml
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
```

So if there's a `terraform/` directory in the repo, it'll end up in `main/terraform/`. I assume the best solution here is to remove the `path` input, so the repository gets checked out right into the workspace. :slightly_smiling_face:

**Reply by jwechsler10** [reply]
yup, going to try that next. I had the path there because it was causing issues on checkout to have it, but I think it's because we weren't cleaning up our self-hosted runners properly. Now that we are, I am going to go back to the way it was without a path.

**Reply by airtower-luna** [reply]
By default `actions/checkout` should clear the directory it's checking out into. If that doesn't work you might want to check if any files not owned by the runner user remained there.

**Comment by the-officialjosh** [comment]
It seems that you are experiencing intermittent failures in your workflow when using self-hosted runners with a specified working directory. The error message suggests that the specified working directory does not exist at the time the process is trying to start.

Here are a few potential causes and solutions you can consider:

1. Timing issue: There might be a delay in the self-hosted runner checking out the code and creating the specified working directory before executing the subsequent steps. To mitigate this, you can introduce a small delay before executing the steps that require the working directory. You can use the `sleep` command to pause the workflow execution for a few seconds to ensure that the working directory is properly set up before proceeding.

2. Permissions issue: Ensure that the user account or the runner process executing the workflow has sufficient permissions to access and create directories in the specified path. You may need to adjust the permissions accordingly to allow the runner to create the working directory if it doesn't exist.

3. Clean up previous runs: If the workflow is executed multiple times on the same runner, it's possible that remnants from previous runs are causing conflicts. Make sure to clean up any artifacts or remnants from previous workflow runs before starting a new one to ensure a clean environment.

Additionally, you can enable debug logging in your workflow to gather more information about the environment and potential errors. This can help you pinpoint the exact cause of the intermittent failures.

By addressing these potential causes and implementing the suggested solutions, you should be able to reduce or eliminate the intermittent failures when using the specified working directory in your workflow.

Let me know if you have any further questions!

**Reply by FaizanAhmedSP707** [reply]
How to clear the cache from previous runs?? I have noticed this always happens if you try to run the same workflow file again after making a few changes.

**Comment by jwechsler10** [comment, marked as answer]
I've found the solution. Turns out the checkout wasn't the issue.  The `setup-terraform` action I am using is dependent on Nodejs. Once I added a step to setup node before I ran any Terraform commands, this solved to issue. I found the solution [here](https://github.com/hashicorp/setup-terraform/issues/84) The new workflow now looks like:
```
jobs:
  deploy-terraform:
    name: Run terraform
    runs-on: self-hosted
    env:
      TF_DIR: terraform/${{ inputs.env }}
      AWS_REGION: ${{ inputs.region }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: <redacted-role-arn>
          role-session-name: ghActionsECR
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve -no-color
        working-directory: ${{ env.TF_DIR }}
        continue-on-error: false

```
