### DISCUSSION TITLE
Remapping environment variable value to a new name

### DISCUSSION THREAD

**Discussion by itaibh** [community/community#58358] [Actions]
### Select Topic Area

Question

### Body

I'm using an action that creates an environment variable in a certain name, but I need to use its value in a different name.
I can see the variable when running `env` (on linux, but eventually I'll need it to be cross-platform)
I tried something like this:

```
  jobs: tests
    steps:
      - name: "test"
        env:
          MY_VAR: ${{ env.SOME_VAR }}
        run: |
          echo "MY_VAR: $MY_VAR"
          echo "SOME_VAR: $SOME_VAR"
```
suppose that SOME_VAR is set to "ABC", the results of the `echo` commands are:

```
MY_VAR:
SOME_VAR: ABC
```

I also tried some other methods according to docs and even consulted with chat GPT, nothing worked.
What am I doing wrong?

**Comment by airtower-luna** [comment]
I just tried something like this, and it worked flawlessly: https://github.com/airtower-luna/hello-github-actions/actions/runs/5303730212/workflow?pr=50#L30-L35

Maybe there's a typo somewhere? It's hard to say without seeing your code, a link to the workflow log would be best. :thinking: 

And asking ChatGPT is just asking to have your time wasted. :sweat_smile:

**Comment by Yarden-zamir** [comment]
I belive your confusion is coming from the difference (or specifically, lack therof) between env.SOME_VAR and $SOMEVAR. Also, please note that what you are doing is not remapping, but assigning. What you are doing is aquivilent to
```bash
      - run: |
          x=1
          b=$x
          echo $x
          echo $b
```
but in your example you didn't show the first step, and you moved the second step to env statement like so
```yaml
      - run: |
          echo "x=1" > $GITHUB_ENV
          # this is an example of how you possible set x.
      - run: |
          echo $x
          echo $y
        env:
          b: ${{ env.x }}
```
hopfuly this gives you a better picture of how those work. And you can look at your workflow and see why you are getting the result you are. If not we'll need more info or to see your actual workflow because, assuming you are setting `SOME_VAR` curectly, the example you showed should work perfectly well.

**Reply by itaibh** [reply]
This is my `.yml` file:

```yml
name: Test on all platforms
on:
  push:
  pull_request:

jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: nanasess/setup-chromedriver@v2
      - name: "Selenium Unit Tests"
        run: | 
          env | sort
          echo "CHROMEWEBDRIVER: $CHROMEWEBDRIVER"
          echo "DRIVER_PATH: $DRIVER_PATH"
        env:
          DRIVER_PATH: ${{ env.CHROMEWEBDRIVER }}
```

The result of this run is this:

```
> Run env | sort
ACCEPT_EULA=Y
AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
ANDROID_HOME=/usr/local/lib/android/sdk
... many other env vars go here ...
XDG_RUNTIME_DIR=/run/user/1001
_=/usr/bin/env
CHROMEWEBDRIVER: /usr/local/share/chrome_driver
DRIVER_PATH: 
```

How do I copy / remap / rename / assign `CHROMEWEBDRIVER` to `DRIVER_PATH`?
