### DISCUSSION TITLE
Actions Is Not Tracking The Changes of files in repository.

### DISCUSSION THREAD

**Discussion by ssavi-ict** [community/community#58486] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello Community, 
I write a Python script that scraps some data from a website and saves the data into a JSON file. I am trying to implement the following - 
- I aim to run a GitHub action to run that Python script once a day. 
- While running the script, I wish the changes will be stored in the designated file generated by that Python script.
- Right after that the Action script should track and commit the changes if there are any.
- And then the script should raise a PULL request in that repository to merge the changes.
- 
To achieve that, I wrote the following Action script -
```yaml
name: Daily Contest Script

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run at 00:00 UTC daily
  workflow_dispatch:

jobs:
  run_contest_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Check if branch exists
        run: |
          branch_exists=$(git ls-remote --exit-code --heads origin automate-c-json-update || echo "")
          if [ -n "$branch_exists" ]; then
            git fetch origin automate-c-json-update
            git checkout automate-c-json-update
          else
            git checkout -b automate-c-json-update
          fi

      - name: Run contest.py script
        run: python scripts/contest.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/contests.json
          git commit -m "Update JSON file"
          git push origin automate-c-json-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated pull request for JSON file update
          title: Automated Pull Request
          branch: automate-c-json-update
          base: main
          body: |
            This pull request updates the JSON file automatically.
```

From the log, I can see that there are changes in the `contests.json` file but the Action script does not commit the changes somehow. I have tried several solutions but none of them really works.

Any Help Will Be Appreciated. If it is needed to share the `contest.py` script please let me know.
Thanks.
