### DISCUSSION TITLE
Is there any way to reuse the workflows in a loop untill we stop/disable the parent work flow manually ?

### DISCUSSION THREAD

**Discussion by pothurajtharun** [community/community#58533] [Actions]
Hi Guys,

I'm new to Github Actions. I was implementing some work flows and faced the [issue](https://github.com/orgs/community/discussions/8488)

Here is the requirement:

1. WorkFow1(has two jobs) will take input and execute the Job1 & will pass the input value to Job2 which actually calls WorkFlow2
2. WorkFow2(has two jobs) will take input and execute the Job1 & will pass the input value to Job2 which calls WorkFlow1

The above two steps should run in a loop untill we stop/disable the WorkFlow1 manually.

Please let me know if there is any way to achieve this. Any suggestions/solutions are much appreciated. 

Thanks! 

**WorkFlow1.yml**
```
name: To run bat tests on mac.
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version.'
        required: true
        default: '1.0.0'
        type: string

    workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  run-bat-tests: **#job1**
    runs-on:
      - self-hosted
      - label-1
    outputs:
      version: ${{ steps.version-no.outputs.version }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Check the release version
        id: version-no
        run: |
          echo "version=${{ inputs.version }}" >> $GITHUB_ENV
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT

  uninstall-test: **#job2**
    if: ${{ always() }}
    needs: run-bat-tests
    uses: ./.github/workflows/WorkFlow2.yml
    with:
      version: ${{ needs.run-bat-tests.outputs.version }}
```

**WorkFlow2.yml**
```
name: To run uninstall test on mac.

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  run-mac-uninstall-test: **#job1**
    runs-on:
      - self-hosted
      - label-1
    outputs:
      version: ${{ steps.version-no.outputs.environment }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Check the release version
        id: version-no
        run: |
          echo "version=${{ inputs.version }}" >> $GITHUB_ENV
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT


  trigger-bat-tests: **#job2**
    if: ${{ success() }}
    needs: run-mac-uninstall-test
    uses: ./.github/workflows/WorkFlow1.yml
    with:
      version: ${{ needs.run-mac-bat-tests.outputs.version }}
```
