### DISCUSSION TITLE
Upload images in the workflow summary

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#58569] [Actions]
### Select Topic Area

Question

### Body

Currently I am uploading some images produced during my workflow execution more or less as follows

```yaml
      - uses: actions/upload-artifact@v3
        with:
          name: test artifacts
          path: |
            my1.png
            my2.png
```

The problem is that these are uploaded as artifacts and therefore compressed (`.zip`) files and are not previewable.

I am aware of the [actions summary functionality](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), however there are no instructions on how to do this with images.

Is there a way around this?
