### DISCUSSION TITLE
Installing packages from private repositories into a Docker image

### DISCUSSION THREAD

**Discussion by sstbrg2** [community/community#58616] [Actions]
### Select Topic Area

Question

### Body

Hi,
I have a GitHub Actions flow that builds a docker image and pushes it to AWS ECR.
The requirements.txt contains dependencies on private repositories under our organization, e.g.:
```
numpy
pandas
MyPackage @git+https://github.com/MyPackage/MyPackage.git
other_stuff
```

Docker fails to pull MyPackage when it executes pip install -r requirements.txt.

Any ideas how to do it?

The docker file:
```
`FROM python:3.9-slim-buster AS build
WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.9-slim-buster AS runtime
WORKDIR /app
COPY --from=build /opt/venv /opt/venv
COPY . .

# set env vars
ENV PATH="/opt/venv/bin:$PATH"

CMD ["python", "main.py"]`
```

The main.yml of the flow:
```
on:
  release:
    types: [published]

name: CI on AWS ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPO }}
        IMAGE_TAG: ${{github.ref_name}}
        ENVIRONMENT: staging
      run: |
        # Build a docker container and push it to ECR 
        echo "Bulding the Docker image..."
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
```
