### DISCUSSION TITLE
GHA: Run on a runner or a container conditionally

### DISCUSSION THREAD

**Discussion by cfoch** [community/community#58670] [Actions]
### Select Topic Area

Question

### Body

Hello. I have a job that should run the same steps on a container (for Linux) or in a runner (macos case). I can use `if`, but that would imply to write the steps again.

```
  build:
    needs: setup
    runs-on: ${{ inputs.matrix.runner }}        # Or this
    container:
      image: ${{ inputs.matrix.container }}     # Or this
      credentials:
        username: ${{ secrets.GHCR_USER_BUILDBOT }}
        password: ${{ secrets.GHCR_TOKEN_BUILDBOT }}
    steps:
      - name: Same steps here
        run: # the same
```

What alternatives do I have? What I see now is the following:
 - Reusable workflow: not an alternative, because I will have the same issue inside the reusable workflow.
 - Put common steps on a script (disadvantage, steps will not be listed on GHA UI.
 - Create a new custom Github Action: This looks like too much.
