### DISCUSSION TITLE
Event always runs for create.tags & never runs on push.tags

### DISCUSSION THREAD

**Discussion by SachinMeier** [community/community#58681] [Actions] [answered]
### Github Actions Create vs. Push Trigger

Question

### Problem

I have the following simple workflow. When line 4 is set to `push`, the workflow never runs even when i push a tag. When line 4 is set to `create`, the workflow runs for any tag i push, regardless of whether or not it matches the regex. 

I'm experiencing what is described in [this issue](https://github.com/actions/runner/issues/1699), but [the fix](https://github.com/actions/runner/issues/1699#issuecomment-1046724792) is not working for me

```
name: Tag Build

on:
  push:
    tags:
      - '^release\/.*$'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${GITHUB_REF_NAME}"
 ```

**Comment by airtower-luna** [comment, marked as answer]
The problem is probably that the expressions for tag/branch filters *aren't regexps*, but extended globs, see here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

I assume your release tags aren't literally meant to start with a `^`. Try something like:

```yaml
on:
  push:
    tags:
      - 'release/*'
```

The `create` event simply doesn't have a branch/tag filter. :wink:
