### DISCUSSION TITLE
Allow null-container in Github Actions workflow

### DISCUSSION THREAD

**Discussion by cfoch** [community/community#58763] [Actions] [answered]
### Github Actions syntax check

Question

### Body

I have a matrix where I want to run a container, optionally (in a matrix strategy). This workflow does pass Github Actions schema

```
jobs:
  build:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ''
    steps:
      - name: Hello
        run: echo 'Hello World'
```

I get this error:
```
Invalid workflow file: .github/workflows/build-recipes.yml#LXX
The workflow is not valid. .github/workflows/build-recipes.yml (Line: XX, Col: XX): Unexpected value ''
```

I reported it in https://github.com/actions/runner/issues/2667 but now I am not sure if the error is somewhere else.

**Comment by ChristopherHX** [comment, marked as answer]
The origin of the schema validation error is in multiple locations (only a subset is public)
- vscode Github Actions extension - typescript workflow parser schema https://github.com/actions/languageservices/blob/8f2f59092edf10e9c4494dd13db3f497bb8d579b/workflow-parser/src/workflow-v1.0.json#L2233
_I believe this extension reports your error seen after push just while editing your worlflow_
- github/actions-dotnet, private has a copy of the schema
- workflow parser golang, private has a copy of the schema

> Similar to [`actions/expressions](https://github.com/actions/languageservices/blob/main/expressions), this project is just one of multiple implementations of the GitHub Actions workflow parser. We therefore cannot accept contributions that significantly modify the schema or the overall behavior of the parser. If you would like to propose changes to Actions itself, please use our [Community Forum](https://github.com/community/community/discussions/categories/actions-and-packages).

Actually they seem to say here is the correct place to suggest a schema chang, but I have my doubts the schema has been  barely relaxed since 2019.


actions/runner has an barely maintained copy, which has removed the non-empty-string constaint.

> This workflow does pass Github Actions schema

It does? Do you mean the web editor? (the webeditor doesn't use the real actions schema, it might use a different json schema, or other ide might use this schema lite)

If you just want to run some jobs in a container, use an expression and github/actions-dotnet won't show you any error. 
```yaml
jobs:
  build:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image || '' }}
    steps:
      - name: Hello
        run: echo 'Hello World'
```
Now add a matrix with an `image` field for all container jobs / just omit the field or use an empty string for all running on a vm.
