### DISCUSSION TITLE
Stopping all processes automatically when using the github GUI

### DISCUSSION THREAD

**Discussion by kevinabbot** [community/community#58760] [Repositories] [answered]
### Select Topic Area

Question

### Body

So I created my repo for my project and I have automated batch file that runs the following commands: 
```
cd /d "C:\Users\xxx\Documents\GitHub\aerocast"
git add .
git commit -m "commit"  
git push 
```

Most of the time it works fine and commits but every once in a while it does not commit because of this message:
```
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

I have read up on how to solve the issue and it is simple as:

`rm -f .git/index.lock`

The problem is that because this repo was run originally from the github GUI my folder does not have a .git folder but instead a .github folder with no index.lock file in it, but when I go through the GUI and try to commit it gives me the option to delete a index.lock (unlock index I guess). Is there another location where this file would be located in? So when I send my code to commit it can remove any previous process already taking place automatically? 

**Update:** 

I may have found something: My .github folder had a .yml and one of the conditions I can change is this:

```
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true
```
cancel-in-progress  was set to false earlier. Now that I set it to true would this work?
