### DISCUSSION TITLE
Connection reset by peer - recvfrom(2)

### DISCUSSION THREAD

**Discussion by Ramesh7** [community/community#58849] [Projects and Issues]
### Select Topic Area

General

### Body

I am using GitHub hosted runner to run my CI and from the CI first provision machine and run some long running command over SSH. The command sometime has nothing to return so the connection become ideal and after 4-5 minutes of time I return with `Connection reset by peer - recvfrom(2)` error at `Provision environment` step which is quite frequent for my workflow.

Here is my GitHub action look like : 
```
# This is a generic workflow for Puppet module acceptance operations.
name: "Module Acceptance"

on:
  workflow_call:
    inputs:
      runs_on:
        description: "The operating system used for the runner."
        required: false
        default: "ubuntu-latest"
        type: "string"
      matrix:
        description: "The matrix of platforms to test."
        required: false
        default: ''
        type: "string"

jobs:

  setup_matrix:
    name: "Setup Test Matrix"
    runs-on: ${{ inputs.runs_on }}
    outputs:
      acceptance_matrix: ${{ steps.get-matrix.outputs.matrix }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: "Bundle environment"
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: "Provision environment"
        run: |
          bundle exec rake "litmus:provision[provision:provision_service,${{ matrix.platforms.image }},$DOCKER_RUN_OPTS]"
```
I tried to tweak **ClientAliveInterval** as well as **ClientAliveCountMax** on provisioned server as well as also passed Server level params for connection ideal but nothing helped and the behaviour of connection reset is consistent.

Also tried via SSH command which internally it uses same and seem same behaviour : 
```
<github-runner>$ time ssh  -o ServerAliveInterval=1800 litmuseor9kgph@34.83.30.133
litmuseor9kgph@34.83.30.133's password:
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Thu Jun 22 11:45:13 2023 from 103.208.69.51
[litmuseor9kgph@litmus-faab7a0f8bdb5a88 ~]$ client_loop: send disconnect: Broken pipe

real	4m41.420s
user	0m0.006s
sys	0m0.007s
```
In above case the **ClientAliveInterval** is set to 1 hour and **ClientAliveCountMax** set to 5 times.
And if I do it from my machine then it never close connection before the provided config value exhausted.

Now I am run out of thoughts so wanted to get some guidance or inputs to avoid this issue.
