### DISCUSSION TITLE
Reusable Workflows - Input deprecatedMessage

### DISCUSSION THREAD

**Discussion by javib51** [community/community#58855] [Actions]
### Select Topic Area

Question

### Body

I am getting a weird error. My workflow has some inputs, looks like this:
```yml
name: Something
on:
  workflow_call:
    inputs:
      my-var:
        description: "This input is not used anymore, but removing it will break existing workflows."
        type: string
        required: false
     ...
jobs:
...
```
And it works perfectly. However, I want to deprecate `my-var` on the following way:
```yml
my-var:
        description: "This input is not used anymore, but removing it will break existing workflows."
        type: string
        required: false
        deprecationMessage: "This input is not used anymore, it will be removed on future versions of this action."
```

However, Im getting this following error: `Unexpected value 'deprecationMessage'`. Is that expected?
