### DISCUSSION TITLE
Unable to locate build jar file

### DISCUSSION THREAD

**Discussion by dniald** [community/community#58861] [Actions]
Hi everyone,

I'm new to GitHub Actions and I'm facing some difficulties locating the built JAR file in the Git Action workflow. I have researched that the built JAR file should be located in the target directory, but when I check, it is empty.

The build process itself seems to be successful, but I can't find the JAR file to proceed with the next step of uploading it to an S3 bucket. Only the classes and META-INF/build-properties files are generated and uploaded.

Below is the script I am using: 
```

    name: Upload Build JAR to S3 bucket
    on:
      push:
        branches:
          - danial
    jobs:
      build:
        runs-on: ubuntu-latest
        permissions:
          packages: write
          contents: write
          id-token: write
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up JDK 8
            uses: actions/setup-java@v3
            with:
              java-version: "8"
              distribution: adopt

          - name: Build JAR
            run: |
                mvn -B package --file pom.xml -Dmaven.test.skip=true 

          - name: Build Artifact
            uses: actions/upload-artifact@v3
            with:
              name: Package
              path: target
              if-no-files-found: error

          - name: Set up AWS credentials
            uses: aws-actions/configure-aws-credentials@master
            with:
              aws-region: xxxxx
              role-to-assume: xxxxxx
              role-session-name: AssumeRoleSession

          - name: Upload JAR to S3
            run: >
                aws s3 cp target/ s3://mybucket/ --recursive
```
    

If anyone has any insights or suggestions on how to resolve this issue and locate the built JAR file correctly, it would be greatly appreciated.

Thank you!

<img width="1334" alt="image" src="https://github.com/community/community/assets/38592307/140b91ec-2860-4006-a98c-798cb3e4273d">
<img width="173" alt="image" src="https://github.com/community/community/assets/38592307/05563319-1b95-4620-9aed-92ac791403a0">
