### DISCUSSION TITLE
GHA pipeline for a databrick's job

### DISCUSSION THREAD

**Discussion by StephenDsouza90** [community/community#58926] [Actions]
### Select Topic Area

Question

### Body

I have the below pipeline 

```yml
name: Build Databricks Job

on:
  push:
    branches:
      - feature/prototype-for-etl-pipeline

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Build Wheel
        run: |
          pip install --upgrade pip
          pip install wheel
          python setup.py bdist_wheel

      - name: Install Databricks CLI
        run: |
          pip install --upgrade pip
          pip install --upgrade databricks-cli

      - name: Set up Databricks CLI
        run: |
          echo ${{ secrets.DATABRICKS_TOKEN }} | databricks configure --token
          echo "host = https://adb-XXXXXXXXXXXXXXXX.X.azuredatabricks.net" > ~/.databrickscfg

      - name: Configure Databricks CLI
        run: |
          databricks configure --profile ~/.databrickscfg

      - name: Upload Wheel to Data Bricks File System
        run: |
          databricks fs cp dist/*.whl dbfs:/FileStore/jars/my_wheel.whl

      - name: Build Job
        run: |
          databricks jobs create-or-update --json-file path/to/file.json
```

I see the error 

```
Databricks Host (should begin with https://): Error: The host does not start with https://
Aborted!
Databricks Host (should begin with https://):
```

I have tried multiple approaches to set up the cli with the host name but I always get the error.

Can someone help me figure this out?
