### DISCUSSION TITLE
github.event.workflow_run.conclusion is always null

### DISCUSSION THREAD

**Discussion by AngelIntel** [community/community#58929] [Actions]
### Select Topic Area

Question

### Body

I am using github.event.workflow_run.conclusion in conjunction with worflow_run:

```
on:
  workflow_run:
    workflows: [workflow1]
    types:
      - completed
```
 
```
jobs:
  job1:
    runs-on: [self-hosted,Linux]
    timeout-minutes: 400
    steps:
      - name: Passing case 
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo workflow1 succeeded
     - name: Failing case 
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo workflow1 failed
```

However, github.event.workflow_run.conclusion is always returning null, and both passing and failing cases are skipped.

I found an old discussion about a similar issue. They used octokit/request-action as a workaround, but that is not working for me.

Additionally, workflow_run (id, name, conclusion) attributes seem to be empty or null.

Why github.event.workflow_run attributes (id, name, conclusion) are empty?
Any new workarounds?
