### DISCUSSION TITLE
How to access `output` from a custom action?

### DISCUSSION THREAD

**Discussion by thekaushikls** [community/community#58980] [Actions] [answered]
Hello all,

I'm trying to create my first github action using python (IronPython to be more specific)
The action takes in some inputs, creates some output (dll) file that needs to be set to the `output` of the action.
After almost a lot of trials, I think I need help with this.

How do I access `output` from a test-action that uses my custom action? Any help is appreciated. TIA

My Action: [action.yml](https://github.com/thekaushikls/python-hello-world-action/blob/main/action.yml)
The test file, that uses this action: [test_action.yml](https://github.com/thekaushikls/python-hello-world-action/blob/main/.github/workflows/test_action.yml)

Line I'm seeking help for: 
```YAML
  - name: Check
    shell: bash
    run: echo build_path "${{steps.build-plugin.outputs.build_path}}"
```

Current Output
![image](https://github.com/community/community/assets/50703773/f096e79a-8aaf-4132-bc5b-1648c71bafc3)

**Comment by airtower-luna** [comment]
The [`run` step where you create the output](https://github.com/thekaushikls/python-hello-world-action/blob/4c8dd8814029a64934bb5a9e0f8b7bc2304da60e/action.yml#L39-L48) is set to run with `shell: pwsh`, but the script is written in Unix shell syntax (not Powershell). That's the main issue, the easiest solution is to set `shell: bash` instead.

Two other issues:

* Using Actions syntax (`${{ ... }}`) within `run` scripts is brittle, if the inserted value contains any characters with special meaning for the shell (e.g. quotes, semicolon) it can break in weird ways, and possibly cause security issues (shell injection). You should provide value through environment variables instead, that way the shell knows about the variable and the usual quoting works.
* Remove the `set-output` line, [as the log tells you](https://github.com/thekaushikls/python-hello-world-action/actions/runs/5363597606/jobs/9731284104#step:3:879) it'd deprecated (and a duplicate anyway).

The corrected step should look similar to this:

```yaml
    - name: Check
      shell: bash
      env:
        BUILD_PATH: ${{steps.compile.outputs.BUILD_PATH}}
      run: |
        echo SETTING VALUES TO OUTPUT
        echo "The build_path is: ${BUILD_PATH}"
        echo "build_path=${BUILD_PATH}" >> $GITHUB_OUTPUT
```
