### DISCUSSION TITLE
Issues form automatic dropdown list basing on releases

### DISCUSSION THREAD

**Discussion by daroga0002** [community/community#5903] [Projects and Issues]
I am started adopting issues form in our project. 

We are going to build a obligatory field:

```
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0
        - 1.1
        - ...........
    validations:
      required: true
``` 

It will be nice to have a possibility to link a `options` into repository current GitHub releases (potentially with limiting option to last X releases). Then it will become more interactive and automated way
