### DISCUSSION TITLE
Start workflow only if several specified workflows have completed successfully

### DISCUSSION THREAD

**Discussion by budarin** [community/community#59065] [Actions]
### Select Topic Area

Question

### Body

```yml
name: Publish Pages

on:
    workflow_run:
        workflows: [Build the project, Playwright Tests]
        types: [completed]
        branches: [master]

jobs:
    publish:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
```

the workflow is executed every time each each of the workflows in the workflows list completes successfully
![image](https://github.com/community/community/assets/8055157/65831006-3f67-4e6a-bcd8-dfe9d73a463b)

How do I start workflow only once after successfully completing both?

**Comment by anhtran917** [comment]
Hello, Budrian.
I understood your problem and suggest this modification.
Try this change and let me know the result.
```
name: Publish Pages

on:
  workflow_run:
    workflows: [Build the project, Playwright Tests]
    types:
      - completed
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
           needs.Build_the_project.result == 'success' &&
           needs.Playwright_Tests.result == 'success' }}
```

**Reply by budarin** [reply]
unfortunately, the workflow starts after one of the tasks is completed while the other is still running
![image](https://github.com/community/community/assets/8055157/3d9acf3d-5a14-4850-97d9-d6e186b83b17)

**Reply by budarin** [reply]
![image](https://github.com/community/community/assets/8055157/42394e32-9756-4983-be0e-be799bdf87c4)

[workflow](https://github.com/budarin/zustand-clean-architecture/blob/master/.github/workflows/github-pages.yml)

**Reply by airtower-luna** [reply]
That "answer" looks like a chatbot hallucination. :unamused: 

The [`needs` context](https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context) provides access to jobs results *from the same workflow* if and only if the current job depends on them. The only explanation I have for the job running at all is because of the `if: >`: It doesn't cut off the newline at the end (like `>-` would), so the result is always a non-empty string, which evaluates to `true`. :sweat_smile: 

I don't have a solution either, [the documentation is very clear](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) that any of the listed workflows will trigger the `workflow_run` event. There's no syntax for collecting multiple events.

**Reply by budarin** [reply]
I am confused by the results of these calls
```yaml
    empty-job:
        runs-on: ubuntu-latest
        steps:
            - name: Do nothing
              run: |
                  echo ${{ github.event_name }}
                  echo ${{ github.ref }}
                  echo ${{ github.event.workflow_run.conclusion }}
                  echo ${{ needs.Build_the_project.result }}
                  echo ${{ needs.Playwright_Tests.result }}
```
the results
```
Run echo workflow_run
workflow_run
refs/heads/master
success


```

echo ${{ needs.Build_the_project.result }} -> empty
echo ${{ needs.Playwright_Tests.result }} -> empty
