### DISCUSSION TITLE
How to write custom action to publish pages?

### DISCUSSION THREAD

**Discussion by budarin** [community/community#59076] [Actions]
### Select Topic Area

Question

### Body

I've created the action but it does not work
```yml
name: Publish Pages

on:
    workflow_run:
        workflows: ['Build the project', 'Playwright Tests']
        types: [completed]
        branches: [master]

permissions:
    pages: write
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        timeout-minutes: 5

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Git Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              id: setup_node_step
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: build
              run: yarn build

            - name: Upload Pages Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: github-pages
                  path: docs/ # Измените на директорию, где находятся собранные файлы

            - name: Deploy Pages
              id: deployment
              uses: actions/deploy-pages@v2
```

Build command creates `docs` folder
Default publish page action successfully publishes the pages but mine - not 

Error:
![image](https://github.com/community/community/assets/8055157/85ae373b-552e-4461-bba3-3442230c4ada)

the error message by link in error
```json
{
    "$id": "1",
    "innerException": null,
    "message": "The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.",
    "typeName": "Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server",
    "typeKey": "UnauthorizedRequestException",
    "errorCode": 0,
    "eventId": 3000
}
```

**Comment by airtower-luna** [comment]
Can you look at the content of the artifact? I'm surprised the workflow didn't fail in the *checkout* step already, because the `permissions` don't include read access to repository contents. :thinking:

**Reply by budarin** [reply]
but `read` access is enabled by default! Am I wrong?

**Reply by airtower-luna** [reply]
Once you add a `permissions` key *all* unset permissions are disabled, only the explicitly granted permissions remain ([see docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)). The defaults apply only if you don't configure `permissions` at all.

**Reply by budarin** [reply]
will that be enough?

```yml
permissions:
    contents: read
    pages: write
    id-token: write
```

**Reply by airtower-luna** [reply]
It should, at least it's what the [starter workflows use](https://github.com/actions/starter-workflows/blob/0582bb6eb45cd5c60bcb0ce2a35fe50bbc0c2c0d/pages/static.yml#L13-L16).

It's possible that there's some additional problem, but that's hard to say without seeing the log (a link would be best).

**Reply by budarin** [reply]
[link](https://github.com/budarin/zustand-clean-architecture/actions/runs/5370833823/jobs/9743197240)

**Reply by airtower-luna** [reply]
Try to add an [`actions/configure-pages` step](https://github.com/actions/starter-workflows/blob/0582bb6eb45cd5c60bcb0ce2a35fe50bbc0c2c0d/pages/static.yml#L34-L35) to the job. The documentation doesn't explicitly say it's required, but all the starter workflows use it. :thinking:

**Reply by budarin** [reply]
![image](https://github.com/community/community/assets/8055157/46611c2b-414f-45e3-9f9a-bfa676b91c8d)

[workflow](https://github.com/budarin/zustand-clean-architecture/blob/master/.github/workflows/github-pages.yml)

**Reply by airtower-luna** [reply]
Two more thoughts:

* Did you actually enable Pages deployment from a custom workflow in the repository settings? [`actions/configure-pages` docs mention](https://github.com/actions/configure-pages/blob/f156874f8191504dae5b037505266ed5dda6c382/action.yml#L18-L21) that can't be done automatically unless you provide a PAT.
* Just a guess: Maybe the workflow trigger (`workflow_run` instead of `push`) makes a difference somewhere non-obvious? Just a guess though.

**Reply by budarin** [reply]
![image](https://github.com/community/community/assets/8055157/e2fccef8-28c0-45e4-9902-24f4872fd157)

The 2nd point is not really understood

**Reply by airtower-luna** [reply]
That config looks correct to me.

I mean that *all* the examples of pages deployments I've seen so far used a `push` event to trigger. A `workflow_run` event has different properties. I'm simply wondering if that makes a difference, somewhere where it's not obvious but breaks the deployment. It's just a guess, but one that's relatively easy to test. :sweat_smile:

**Comment by ChristopherHX** [comment]
I usually use `actions/upload-pages-artifact@v1` to create the pages artifact, but you have been using the plain  `actions/upload-artifact` action.

Your error message implies that GitHub Pages does not accept the format of your artifact, so this can still work by creating a valid artifact with `actions/upload-pages-artifact@v1`.

```yaml
name: Publish Pages

on:
    workflow_run:
        workflows: ['Build the project', 'Playwright Tests']
        types: [completed]
        branches: [master]
   # push: # My workflow uses the push event, no idea if this works with workflow_run

permissions:
    contents: read
    pages: write
    id-token: write

concurrency: # Cancel parallel deployments before starting a new one
  group: "pages"
  cancel-in-progress: true

jobs:
    publish:
        runs-on: ubuntu-latest
        timeout-minutes: 5 # This is enough time?
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Git Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              id: setup_node_step
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Enable Cache
              id: cache_step
              uses: actions/cache@v3
              with:
                  key: ${{ hashFiles('yarn.lock') }}
                  path: node_modules

            - if: ${{ steps.cache_step.outputs.cache-hit != 'true' }}
              run: yarn install --frozen-lockfile

            - name: build
              run: yarn build

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@v1 # This action is the prefered way to create a GitHub Pages artifact not upload-artifact
              with:
                  path: docs # Измените на директорию, где находятся собранные файлы

            - name: Deploy Pages
              id: deployment
              uses: actions/deploy-pages@v2
```

Disclaimer: I have not tested the provided example, the following is my working workflow https://github.com/ChristopherHX/runner.server/blob/main/.github/workflows/deploy-pages.yml
