### DISCUSSION TITLE
Actions won't work

### DISCUSSION THREAD

**Discussion by ghost** [community/community#59322] [Actions]
### Select Topic Area

Question

### Body

My actions shows [here](https://github.com/Sinetian/dict/actions/runs/5377082230/workflow).
Why does this happen? It only told me every actions steps must contain a `steps` or `use`. Why?

**Comment by airtower-luna** [comment]
Each step must contain a `run` or `uses` key because that's what tells the step what to do. A step that doesn't do anything wouldn't be very useful. :sweat_smile: 

Looking at your workflow it kinda seems like there's an extra `-` (which starts a new list element in YAML, so a new step) on line 36: https://github.com/Sinetian/dict/actions/runs/5377082230/workflow#L36 I assume the `name: Get date` is meant to be part of the same step as `id: tag_name`, in that case this would be correct:

```yaml
    - name: Get date
      id: tag_name
      run: |
        echo "" >> DATE
        echo "VERSION=$(date +'%Y').$(date +'%m').$(date +'%d')" >> DATE
```

I can't help but notice the command is a lot more complex than it needs to be though, it'd be much simpler if you gave the full pattern to `date` instead of calling it three times and assembling the results:

```yaml
    - name: Get date
      id: tag_name
      run: |
        echo "" >> DATE
        echo "VERSION=$(date +'%Y.%m.%d')" >> DATE
```
