### DISCUSSION TITLE
Masking values by writing to a file

### DISCUSSION THREAD

**Discussion by sidekick-eimantas** [community/community#59326] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi

Currently to set environment variables in a step that persist within the job, you must do the following:

```yml
jobs:
  test:
    steps:
      - run: echo "MY_SECRET={value}" >> "$GITHUB_ENV"
```

We have custom tooling that allows us to fetch secrets from a remote secrets store:

```yml
jobs:
  test:
    steps:
      - run: echo "MY_SECRET=$(skm get-secret skm-secrets/my-secret)" >> "$GITHUB_ENV"
```

In this tooling, we would also like to automatically mask the secrets when running in github actions
Here's the simplified code:

```py
def get_secret(key: str) -> None:
    value = core.get_secret_value(key=key)
    mask_value(value=value)
    print(value, end="", file=sys.stdout, flush=True)
    return

def mask_value(value: str) -> None:
    if config.Main.RUNNING_IN_GITHUB_ACTIONS:
        _mask_value_in_github_actions_logs(value=value)


def _mask_value_in_github_actions_logs(value: str) -> None:
    # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-a-log
    print(f"::add-mask::{value}", end="", file=sys.stdout, flush=True)
```

However, if we do this, when the tool is used as shown in the example, what gets appended to the file is `::add-mask::{secret}`, because stdout is being captured

To facilitate this usecase, it would be great if there was a file that we could write to the values to be masked. In the same way that we can set env vars by writing to $GITHUB_ENV
