### DISCUSSION TITLE
Is the SHELL environment variable available for jobs running on Ubuntu hosts

### DISCUSSION THREAD

**Discussion by debarshiray** [community/community#59413] [Actions]
### Select Topic Area

Question

### Body

I am trying to run the [Toolbx](https://containertoolbx.org/) test suite through a GitHub Actions workflow on Ubuntu 22.04 hosts.  It looks as if the `SHELL` environment variable is mysteriously missing in some cases.

I added a *Debug* step to the beginning of the job to illustrate this:
```
name: ubuntu-tests

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-jammy-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Debug
        run: |
          echo "$SHELL"
          env | grep SHELL
          useradd --defaults
          cat /proc/$$/cmdline

      - name: Checkout
        uses: actions/checkout@v3

...
...
```

It produces:
```
/bin/bash
POWERSHELL_DISTRIBUTION_CHANNEL=GitHub-Actions-ubuntu22
GROUP=100
HOME=/home
INACTIVE=-1
EXPIRE=
SHELL=/bin/bash
SKEL=/etc/skel
CREATE_MAIL_SPOOL=no
/usr/bin/bash-e/home/runner/work/_temp/a030d627-edc2-4e52-ad17-539ed85a4577.sh
```

So, `echo $SHELL` leads to `/bin/bash`, but `SHELL` is absent from the output of `env(1)`, and `/proc/$$/cmdline` confirms that I am indeed using Bash.  For what it's worth, it seems like processes spawned from the job don't have `SHELL` set in their environments either.

Is this expected?  Do the GitHub Actions workflows do something special to the `SHELL` environment variable?

I am struggling to come up with the right keywords for searching because the phrase *SHELL environment variable* is often used to mean *any* environment variable instead of specifically *SHELL*.
