### DISCUSSION TITLE
Action failing but working just fine locally

### DISCUSSION THREAD

**Discussion by maytee-sanchez-wizeline** [community/community#59476] [Actions]
### Select Topic Area

Question

### Body

Hello!

I'm currently working on a GitHub action with the aim of keeping the editorial-preview branch updated with main.
The action looks as follows:

```
name: Update editorial-preview branch

on:
  push:
    branches: [ main ]

jobs:
  update-branch:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git user
        run: |
          git config --global user.email "myemail"
          git config --global user.name "username"

      - name: Clean conflict files
        run: git clean -f

      - name: Fetch all branches
        run: git fetch --all

      - name: Update branch
        run: |
          git fetch origin main
          git checkout editorial-preview
          git fetch origin editorial-preview
          git rebase origin/main
          git push -f origin editorial-preview --no-verify
```

I've tested locally (running it when I push to my test branch instead of main) and it works fine, but then when I change to execute it when pushing main, and after merging my changes to main it fails with the following error:

```
Run git fetch origin main
From https://github.com/The-news-movement/next-the-news-movement
 * branch            main       -> FETCH_HEAD
Switched to a new branch 'editorial-preview '
branch 'editorial-preview ' set up to track 'origin/editorial-preview '.
From https://github.com/The-news-movement/next-the-news-movement
 * branch            editorial-preview    -> FETCH_HEAD
Auto-merging .eslintrc.json
CONFLICT (add/add): Merge conflict in .eslintrc.json
Rebasing (1/360)
Auto-merging .gitignore
error: could not apply [8](https://github.com/The-news-movement/next-the-news-movement/actions/runs/5393548376/jobs/9793438661#step:6:9)aa8f34... Initial commit from Create Next App
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Auto-merging next.config.js
CONFLICT (add/add): Merge conflict in next.config.js
Auto-merging package.json
CONFLICT (add/add): Merge conflict in package.json
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 8aa8f34... Initial commit from Create Next App
Error: Process completed with exit code 1.
```

It doesn't make sense to me, because editorial-preview branch has just been created from main, there are no conflicts.
I'd appreciate any comments/suggestions you have. 
Thanks!
