### DISCUSSION TITLE
Allow actions/checkout to checkout a different private repo in same org

### DISCUSSION THREAD

**Discussion by damar-block** [community/community#59488] [Actions]
### Select Topic Area

Question

### Body

How can I configure the `actions/checkout` action to checkout a different private repo in the same org?

The action configuration is:
```
      - name: Clone bla-bla
        uses: actions/checkout@v2
        with:
           repository: myOrg/bla-bla
           token: ${{ secrets.GITHUB_TOKEN }}
```

However, this workflow fails. I read that indeed the default GITHUB_TOKEN has permission to the same repo only, how can I configure it to allow access to other private repos in my org?
