### DISCUSSION TITLE
If statement in actions elongates "Setup job"

### DISCUSSION THREAD

**Discussion by wi5nia** [community/community#59530] [Actions]
### Select Topic Area

Bug

### Body

I have job with 7 steps in it. It runs on my self-hosted runners on an Azure VM. The whole job took around 2 minutes to complete.

Now I have introduced an _if_ statement to one of my steps:

```yaml
- name: 'Azure Login'
     uses: azure/login@v1
     if: ${{ !contains(fromJson(inputs.json_arguments).someKey, 'someString') }}
     with:
       creds: ${{ secrets.myCred }}
       allow-no-subscriptions: true
```

The moment I have added this the "Setup job" takes 2-2,5 minutes every time which makes the whole job finish in around 4 minutes which is double the time it used to without the _if_ statement.

The JSON from which it is reading is not big: 36 lines and 1 391 bytes in size so I don't see that being a problem.

Has anyone seen such behaviour and maybe seen some solutions?
