### DISCUSSION TITLE
Workflow not triggered when release is published

### DISCUSSION THREAD

**Discussion by drewhemm** [community/community#59549] [Actions]
### Select Topic Area

Bug

### Body

I have a workflow that starts like this:

```yaml
---
on:
  release:
    types:
      - published
```

It is merged to the default branch. However, when I create releases in the UI or in the CLI, the workflow is not triggered. All other workflows trigger as expected in response to tags and commits and PR actions etc. 

The releases created are fully-published, not in draft status etc.
