### DISCUSSION TITLE
Action stopped working on schedule

### DISCUSSION THREAD

**Discussion by kristijan-ristic** [community/community#59547] [Actions] [answered]
### Select Topic Area

Question

### Body

As you can see bellow I have both manual trigger and cron set on this job.
Scheduler was working great for a years and few days ago (4) it stopped working. 
What could be the reason, is there any change that happened on github actions? Manual run is still working fine? What should I check? It is weird because I didn't do any change in workflows during that period. 
Thanks in advance!
```
on:
  schedule:
  - cron:  "05 22 * * 1-6"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Run tests on branch'
        required: true
        default: 'main'
```
