### DISCUSSION TITLE
Issues/footguns/doc issues with GitHub Actions

### DISCUSSION THREAD

**Discussion by rotu** [community/community#59596] [Actions]
### Select Topic Area

Product Feedback

### Body

I was looking into some actions and I found the following issues. It's not clear to me whether these need fixes or better documentation:

1. The `matrix` context [documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#matrix-context) says that property values must be strings. The GitHub yaml editor allows values to be primitives like booleans. And the runner allows values to be any object.

  ```yaml
  strategy:
    matrix:
      x:
        - 'true'
        - true
        - { key: 'value' }
  ```

2. Coercion is funky. `if` statements coerce their values to booleans. So `if: true` and `if: 'true'` are functionally equivalent. It's very surprising that `true == 1` is true and `'1' == 1` is true but `true == 'true'` is false. I'd expect that, especially when interoperating with shell scripts, primitives decay to strings for equality comparison (instead of to numbers, [as they apparently do](https://docs.github.com/en/actions/learn-github-actions/expressions#operators)).

3. Assigning an object to `env` appears to work! This is undocumented and it's not clear whether it's behavior that can be relied upon. In this context, the boolean `true` and the string `'true'` *do* seem to both get converted to the string "true" as environment variable values.

  ```yaml
  strategy:
    matrix:
      myenv: [{ s: 'true', b: true }, { i: 'z'}]
  steps:
    run: env
    env: ${{ matrix.myenv }}
  ```
