### DISCUSSION TITLE
New/Update Feature: Filter Options in Choice List depending on another Input

### DISCUSSION THREAD

**Discussion by NonfriPax8** [community/community#59590] [Actions]
### Select Topic Area

Product Feedback

### Body

It would be pretty efficent to be able to filter the list provided in a choice, depending on a previous set input.

For Example:

I have a GHA workflow that takes in the following inputs:

- teamName
- suiteXML

The given scenario is to address when running a similar setup of automated tests that are owned by a specific team.

So given this scenario, I would like to be able to kick off the GHA workflow in which i was able to choose a team name and the list of xmls under the suiteXML choice list changes depending on the choice option selected for Team Name.

Ideas:

```
workflow_dispatch:
     inputs:
      teamName:
        type: choice
        description: "Supported Teams"
        required: true
        default: 'HackRockAthon'
        options:
              - HackRockAThon
              - HeWasNumber1
              - AccountingSucks
      xmlTestSuite:
         type: filterChoice
         description: 'XML Test Suite'
         required: true
         default: ''
         dependsOn: teamName
         options:
                optionsFor: HackRockAThon
                    - SQLInjection.xml
                    - BlackBox.xml
                 optionsFor: HeWasNumber1
                    - smoke.xml
                    - regression.xml
                    - sanity.xml
                 optionsFor: AccountingSucks
                    - InvoiceChecks.xml
                    - PricingChecks.xml
```
                    
 This seems like a pretty easy configuration to setup to have a dynamic responsive dropdown in the Workflow setup. Now when a team member from "HackRockAThon" decides to kickoff this workflow, the suiteXML list will automatically filter to show only the available options for "HackRockAThon" Team.
 
 This would help so much in Teams using the actions appropriately and another team cannot mistakenly kickoff another teams owned choices. Current implementations are creating multiple workflows that call the main automation workflow. Each duplicative workflow is only contains the xmls that are tied to their team.
