### DISCUSSION TITLE
Checks required for merging

### DISCUSSION THREAD

**Discussion by Renato66** [community/community#59692] [Actions]
### Select Topic Area

Question

### Body

I got my branch protected by this check, but i only want to check prettier if anything changes at those specific paths, 
then when i open a PR pointing to that branch, i got a required check and I can't proceed if I'm not an admin of the repository

<img width="766" alt="image" src="https://github.com/community/community/assets/9284273/c6fe8d95-b1d4-4319-8063-d6ee69843f5f">

```yml
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - '**.js'
      - '**.css'
      - '**.vue'
      - '**.json'
      - '**/check-eslint-stylelint-prettier.yml'
```

<img width="904" alt="image" src="https://github.com/community/community/assets/9284273/fa27fef6-bc13-4f58-b782-af5faa109029">
