### DISCUSSION TITLE
Ref is blank on published event

### DISCUSSION THREAD

**Discussion by bryannaegele** [community/community#59766] [Actions]
### Select Topic Area

Bug

### Body

Starting today the ref on release published events has started coming through as empty in the github context. This is breaking actions such as Docker metadata.

Today
```
Context info
  eventName: release
  sha: xxx
  ref: 
  workflow: Release Pipeline
  action: docker_meta__base
  actor: bryannaegele
  runNumber: 30
  runId: xxx
  ::endgroup::
```

Yesterday
```
Context info
  eventName: release
  sha: xxx
  ref: refs/tags/xxx
  workflow: Release Pipeline
  action: docker_meta__base
  actor: bryannaegele
  runNumber: 28
  runId: xxx
```
