### DISCUSSION TITLE
Open an Issue and get a HTTP 400 error

### DISCUSSION THREAD

**Discussion by Big-Cake-jpg** [community/community#5977] [Projects and Issues] [answered]
I want to open an Issue on [@bs-community/blessing-skin-server](https://github.com/bs-community/blessing-skin-server)
When I click submit,I get a HTTP 400 error
I use Chromium Microsoft Edge
When I get this I change my browser to Chrome
I also get a 400 error
I tried to open it on my iPhone with Safari
It still happening.
(P.S. I'm in China Mainland)

**Comment by victorpopkov** [comment, marked as answer]
We have faced with the similar problem. The issue was the missing `label` in `attributes`.

Try changing: https://raw.githubusercontent.com/bs-community/blessing-skin-server/f3d1b196ffe36dc648b7179841d95c8881b57c45/.github/ISSUE_TEMPLATE/bug-report.yml

```yml
  - type: markdown
    attributes:
      label: Verify # try adding this
      value: |
        Please filing an issue, please make sure you've read:
        - [FAQ](https://blessing.netlify.app/en/faq.html)
```

**Reply by Big-Cake-jpg** [reply]
It didn't happen in English issue template
but it happened in Chinese issue template

**Reply by victorpopkov** [reply]
It should be the same: https://raw.githubusercontent.com/bs-community/blessing-skin-server/f3d1b196ffe36dc648b7179841d95c8881b57c45/.github/ISSUE_TEMPLATE/bug-report-zh.yml

```yml
  - type: markdown
    attributes:
      label: Verify # try adding this
      value: |
        在报告问题之前，请确保您已经 **认真** 阅读：
        - [FAQ](https://blessing.netlify.app/en/faq.html)
        - [报告问题的正确姿势](https://blessing.netlify.app/report.html)
```
