### DISCUSSION TITLE
Multiple arguments with action "uses: docker://..."

### DISCUSSION THREAD

**Discussion by youroff** [community/community#59795] [Actions]
### Select Topic Area

Product Feedback

### Body

We're currently migrating from CloudBuild to Github Actions. Mostly loving it, however running a step in docker turned out to be a huge headache. This is how it used to be in CloudBuild:
```
  args:
  - '-c'
  - |
      apk add --no-cache --update build-base npm python3 py3-pip curl
```
There we could pass a multiline inline script to `/bin/sh`.

With GH Actions, `args` seems to be a string, while we can pass one multiline string like so it's not the same and it doesn't work as expected:
```
with:
    entrypoint: /bin/sh
    args: |
        -c
        apk add --no-cache --update build-base npm python3 py3-pip curl
```

Shouldn't args accept a list instead?

**Comment by ChristopherHX** [comment]
You might want to create an action.yml file using `image: docker://` instead of a Dockerfile. Then you can specify args as an array together with inputs of the action.

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file

Otherwise I would write the command to the workspace. Then use `script.sh` as args. `shell: cp {0} script.sh` (Might have problems if {0} has spaces in it) would make a run step write the script.sh to disk.

> Shouldn't args accept a list instead?

I also think so, it is an args list in action.yml.

Such a change might allow composite action to receive array inputs.

The way how the actions/runner has currently implemented action inputs, they only support string values as inputs.

**Reply by youroff** [reply]
Not sure I understand the first suggestion, I don't use a dockerfile for that step, just a standard image with language build tools. I also considrered moving that into a script, but that would be a significant loss in flexibility and convenience. As of now, I settled with this solution, which is almost what I needed really:

```
- name: Build
    uses: docker://elixir:1.14-otp-25-alpine
    with:
        entrypoint: /bin/sh
        args: >
            -c 
            "mix local.hex --force;
            mix local.rebar --force;
            mix deps.get;
            mix compile;"
```

**Reply by ChristopherHX** [reply]
I think your approuch will work, but undocumened features have no predictable future.

>  I don't use a dockerfile for that step

I know, but the docu does in their example action.yml file I have linked in my post.
I wanted to point out that the action.yml also allows using prebuild images for docker actions like in your first post / title.
Using the action.yml is the only official / documented way to provide an docker action arguments via an array.

Moving it to a script doesn't mean it needs an different file for example

```yaml
- name: Create Build Script
  run: |
      # 'EOF' is heredoc without $ expansion
      cat > "script-$GITHUB_RUN_ID.sh" << 'EOF'
      mix local.hex --force
      mix local.rebar --force
      mix deps.get
      mix compile
      EOF
  shell: bash
- name: Build
  uses: docker://elixir:1.14-otp-25-alpine
  with:
      entrypoint: /bin/sh
      args: script-${{ github.run_id }}.sh
```

I previously tried to pass the script via an env variable, but failed to get that working.
