### DISCUSSION TITLE
Why does my GitHub actions ci.yml deploy and old version of the dist folder?

### DISCUSSION THREAD

**Discussion by alexlapwood** [community/community#59802] [Actions]
### Select Topic Area

Question

### Body

Hello!

I'm trying to migrate from GitLab to GitHub. GitHub keeps deploying an old version of the dist folder, but GitLab is fine so I think I'm doing something wrong with the caching of my dist folder, can you see what I've done wrong? 

This is my GitHub `ci.yml`
```
name: CI

on:
  push:
    branches: [main]

jobs:
  install:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  lint:
    name: npm run ci:lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Lint
        run: npm run ci:lint

  test:
    name: npm run ci:test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Test
        run: npm run ci:test

  build:
    name: npm run ci:build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: npm run ci:build

      - name: Cache dist folder
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ hashFiles('dist/**') }}
          restore-keys: ${{ runner.os }}-dist-

  deploy:
    name: npm run ci:deploy
    runs-on: ubuntu-latest
    needs: [build, lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Restore dist folder from cache
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ hashFiles('dist/**') }}
          restore-keys: ${{ runner.os }}-dist-

      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm i -g firebase-tools
          npm run ci:deploy
```

This is my `.gitlab-ci.yml` for reference
```
image: node:18

stages:
  - Install dependencies
  - Build and test
  - Deploy

npm install:
  stage: Install dependencies
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

npm run ci:lint:
  stage: Build and test
  dependencies:
    - npm install
  script:
    - npm run ci:lint

npm run ci:build:
  stage: Build and test
  dependencies:
    - npm install
  script:
    - npm run ci:build
  artifacts:
    paths:
      - dist/

npm run ci:test:
  stage: Build and test
  dependencies:
    - npm install
  script:
    - npm run ci:test
  artifacts:
    when: always
    paths:
      - test-results.xml
    reports:
      junit: test-results.xml

npm run ci:deploy:
  stage: Deploy
  environment: production
  dependencies:
    - npm run ci:build
  script:
    - npm i -g firebase-tools
    - npm run ci:deploy
```
