### DISCUSSION TITLE
Pinned but untagged images

### DISCUSSION THREAD

**Discussion by gowizzard** [community/community#59847] [Packages]
### Select Topic Area

Question

### Body

Hello everyone, I have a question. I've been working with GitHub packages for the last few days. I have created an action which creates an image for `linux/arm64` for a project with `buildx`. This also tags all images correctly and allows to display the manifest data. Now I have modified the action to create two images for `linux/amd64` and `linux/arm64`.

The images can also be accessed via the packages and the two images are also displayed under OS, but unfortunately the images are also found under untagged images, although they seem to be assigned. Unfortunately, the manifest data is also missing from the image where the two OS versions are displayed. Does anyone know what this could be?

Here is my action:

```yml
name: GitHub Packages

on:
    push:
        tags:
            - 'v*.*.*'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  platforms: linux/arm64
                  push: true
                  provenance: false
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
```

Many greetings
Jonas

**Comment by ArdeshirV** [comment]
I think regarding the images being listed as untagged, one possible reason could be that the tags output from the docker/metadata-action step is not correctly capturing or passing the tags for the new images. Make sure that the tags output in the meta step captures all the relevant tags for both images (linux/amd64 and linux/arm64). You can check the output of the meta step by adding a debug log statement like run: echo "${{ steps.meta.outputs.tags }}". Verify if it includes the expected tags for both images.

As for the missing manifest data, it could be related to the provenance: false parameter you have set in the docker/build-push-action step. The provenance option controls whether to generate and include image provenance information in the manifest. Try setting provenance: true to include the manifest data when pushing the Docker images. This may resolve the issue with missing manifest data.

```
...
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
