### DISCUSSION TITLE
How to get the current time as an environment variable in actions? (windows)

### DISCUSSION THREAD

**Discussion by atsju** [community/community#59851] [Actions] [answered]
### Select Topic Area

Question

### Body

I hope to automatically create a new release through Actions and set the name to the current time, but I have failed many times. How can I do this?

The answer already exists for linux https://github.com/orgs/community/discussions/26342
But I need it for windows

**Comment by atsju** [comment, marked as answer]
I finally got it working with some stackoverflow help https://stackoverflow.com/questions/76596124/get-current-date-in-github-workflows-windows

Remember to use `$env:GITHUB_ENV` instead of `$GITHUB_ENV`
And use the new environment variable only in subsequent steps

```YAML
- name: Put current date into a variable
  run: |
    $NOW=& Get-Date -format yyyy-MM-dd
    echo "NOW=$NOW" >> $env:GITHUB_ENV
- name: Use variable
  run: |
    echo "${{env.NOW}}"
```
