### DISCUSSION TITLE
github actions keeps on timing out (or something) well under my timeout limit

### DISCUSSION THREAD

**Discussion by terrafrost** [community/community#59873] [Actions]
### Select Topic Area

Question

### Body

First, here's my .github/workflows/ci.yml file:

```
name: Benchmark

on:
  push

jobs:
  benchmark:
    strategy:
      matrix:
        PHP_VERSION: [
          '4.4',
          '5.0', '5.1', '5.2', '5.3', '5.4', '5.5', '5.6',
          '7.1', '7.2', '7.3', '7.4',
          '8.0', '8.0jit', '8.1', '8.1jit', '8.2', '8.2jit'
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Setup Docker and Git Repo"
        run: |
          git clone -b 1.0 --single-branch https://github.com/phpseclib/phpseclib.git
          if [[ "${{ matrix.PHP_VERSION }}" == "8"* ]]; then docker pull "quay.io/phpseclib/php${{ matrix.PHP_VERSION }}" && docker image tag "quay.io/phpseclib/php${{ matrix.PHP_VERSION }}" "phpseclib/php${{ matrix.PHP_VERSION }}"; else docker pull "phpseclib/php${{ matrix.PHP_VERSION }}"; fi
      - name: "Run Benchmark"
        run: |
          docker run -v "`pwd`:/opt/src" \
            -w "/opt/src" \
            "phpseclib/php${{ matrix.PHP_VERSION }}" \
            php test.php
    timeout-minutes: 10
```
On Github Action pretty much every job looks like this:

```
Cloning into 'phpseclib'...
Using default tag: latest
latest: Pulling from phpseclib/php4.4
2b15b7abe8b3: Pulling fs layer
292ae618967d: Pulling fs layer
71bbdbc9d3c1: Pulling fs layer
963fe8c066a2: Pulling fs layer
963fe8c066a2: Waiting
71bbdbc9d3c1: Verifying Checksum
71bbdbc9d3c1: Download complete
2b15b7abe8b3: Verifying Checksum
2b15b7abe8b3: Download complete
963fe8c066a2: Verifying Checksum
963fe8c066a2: Download complete
2b15b7abe8b3: Pull complete
292ae618967d: Verifying Checksum
292ae618967d: Download complete
292ae618967d: Pull complete
71bbdbc9d3c1: Pull complete
Error: The operation was canceled.
```
At that top it says `cancelled 5 minutes ago in 21s`. It's like it's just timing out after 21s even tho I have `timeout-minutes: 10` set.

I thought I'd try it without the matrix but without it works just fine:

```
name: Benchmark

on:
  push

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Setup Docker and Git Repo"
        run: |
          git clone -b 1.0 --single-branch https://github.com/phpseclib/phpseclib.git
          docker pull "phpseclib/php7.4"
      - name: "Run Benchmark"
        run: |
          docker run -v "`pwd`:/opt/src" -w "/opt/src" "phpseclib/php7.4" php test.php
    timeout-minutes: 10
```
Like without the matrix the docker container is able to be pulled and ran, all within the 10m `timeout-minutes`.

TLDR I can't figure this out my first Github Actions YAML is timing out when my second one doesn't have any issues what-so-ever.

Any ideas?
