### DISCUSSION TITLE
Docker Compose Run - AWS ECS

### DISCUSSION THREAD

**Discussion by codecharacter** [community/community#59883] [Actions]
### Select Topic Area

Question

### Body

**CURRENT SETUP**
- Currently running a couple of containers on an EC2 instance: web + api (node)
- The api container connects to an RDS instance.
- After deploying a new image of the api container we'd run > 
`docker-compose run --rm api npm db:migration:run`
  - it runs a container of this same image to update any schema changes in the database then removes it

**POC SETUP WITH GITHUB ACTIONS**
- Migrating to ECS and using GitHub Actions to automate the build, tag & deployment of new images.
- We've got this setup and tested it successfully so far.

**ISSUE**
- Unable to run the docker-compose run command
- Timeout error connecting to RDS instance during workflow
- I believe this container is running in a GitHub runner and not the ECS cluster, thus the inability to connect to the RDS instance and the error

**QUESTION**
- How to run this `docker-compose run` command in the cluster?
- Can you add a container to the Task Definition?  

GitHub Actions: cd.yaml
```
   # the rest of the build, tag, push, deploy are fairly well documented    
    - name: Get S3 File & Create .env
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp 
        source: s3://envt-vars-bucket/api-envt-vars-file.env
        destination: ./.env
      
    - name: Store .env Vars in GITHUB_ENV
      run: |
        cat ./.env >> $GITHUB_ENV
   
    - name: Run DB Migrations
      env:
        IMAGE_TAG: ${{ github.sha }}
        DATABASE_CONNECTION: ${{ env.DATABASE_CONNECTION }}
        DATABASE_HOST: ${{ env.DATABASE_HOST }}
        DATABASE_NAME: ${{ env.DATABASE_NAME }}
        DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        DATABASE_PORT: ${{ env.DATABASE_PORT }}
        DATABASE_SSL: ${{ env.DATABASE_SSL }}
        DATABASE_USERNAME: ${{ env.DATABASE_USERNAME }}
      run: |
        cd docker/application/api
        docker compose run --rm api npm run db:migration:run
```

docker-compose.yaml
```
version: '3.4'

services:
  api:
    image: 123456789123.dkr.ecr.us-west-2.amazonaws.com/ecr-repo:${IMAGE_TAG}
    environment:
      IMAGE_TAG: ${IMAGE_TAG}
      DATABASE_CONNECTION: ${DATABASE_CONNECTION}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SSL: ${DATABASE_SSL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
    ports:
      - 3000:3000
    expose:
      - 3000
```
Error Received during GitHub Actions Workflow
```
Error during migration run:
Error: connect ETIMEDOUT 10.30.222.208:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '10.30.222.208',
  port: 5432
}
```
- 10.30.222.208 is the IP address of the RDS instance

TROUBLESHOOTING STEPS
- Checked security groups, and added IP subnet
- Enabled debug logging to confirm env vars
- Contacted AWS Support and they recommended using ecs-cli
  - And ecs-cli refers to the AWS CoPilot CLI
