### DISCUSSION TITLE
NOT running workflow when creating repository from Template?

### DISCUSSION THREAD

**Discussion by DNIE-ecco** [community/community#60036] [Actions]
### Select Topic Area

Question

### Body

Hi

I have a template repository which I use to create new repositories by calling the Github API. The template repository contains a workflow file that triggers on: push

My problem is, I don't want the workflow to run on the initial "push" when the new repository is first created, as I have to create some vars and secrets in the new repository via the API, before the action file will execute successfully, but I can't figure out how to accomplish that....

**Comment by nirav-gajera** [comment]
In your workflow file (e.g., .github/workflows/main.yml), you can use the github.event_name context to determine if the current event is a "push" event or some other event like "repository creation."

ex:  
 
```
name: Your Workflow Name

on:
  push:
    branches:
      - main  # Replace 'main' with the default branch name of your template repository

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's the initial push
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Initial push detected. Skipping the rest of the steps."
            exit 78
          fi
      - name: Your other workflow steps
        # Add the rest of your workflow steps here
        # ...

```
