### DISCUSSION TITLE
Github Actions java maven don't resolve internal  dependency package

### DISCUSSION THREAD

**Discussion by jpalumbo1981** [community/community#60062] [Actions]
### Select Topic Area

Question

### Body

I have a java project which has a dependency on another java project. The first compiles fine and deploys correctly to github packages, however the second fails to download the dependency at compile time.

This is the pom.xml of java dependecy 
    
```xml
<distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/jpalumbo1981/DWModels</url>
        </repository>
    </distributionManagement>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>dwmodels</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
````

and the workflow:
```yml
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
 
 
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        BUILD_ENV: 'github-actions'
````
this is the important section of the java project pom
   ```xml
    <repositories>
        <repository>
            <id>github</id>
            <name>GitHub Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/jpalumbo1981/DWModels</url>
        </repository>
    </repositories>
    
    <dependencies>
        <dependency>
            <groupId>com.plogging</groupId>
            <artifactId>dwmodels</artifactId>
            <version>4.1.0</version>
        </dependency>
    </dependencies>
````
and this the workflow
```yml
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Configure Maven settings.xml
      uses: s4u/maven-settings-action@v2.8.0
      with:
        githubServer: false  
        servers: |
          [{
            "id": "github",
            "username": "${{ github.actor }}",
            "password": "${{ secrets.GITHUB_TOKEN }}"
          }]

    - name: Build with Maven
      run: mvn -B package --file pom.xml
````
finaly this is the error:
```plaintext
Error:  Failed to execute goal on project DWCore: Could not resolve dependencies for project com.plogging:DWCore:jar:4.4.1: Could not find artifact com.plogging:dwmodels:jar:4.1.0 in github (https://maven.pkg.github.com/jpalumbo1981/DWModels) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Error: Process completed with exit code 1.
````
