### DISCUSSION TITLE
Feature request: auto-retry failed jobs option for matrices having a given success rate

### DISCUSSION THREAD

**Discussion by gciatto** [community/community#60118] [Actions]
### Select Topic Area

Question

### Body

GHA supports extensive testing of software products by means of the `matrix` execution strategy.
When it is exploited, the same testing jobs are commonly repeated on top of different OS, platforms, and their many versions.

For instance, in [kt-math](https://github.com/gciatto/kt-math) (a Kotlin multiplatform project of mine targetting both JS and JVM), I need to run tests for:
- all major OS (win, mac, linux)
    - major JS versions from 16 to 20
    - several JDK distributions (adopt and temurin)
        - major JDK version 11, 17, and latest

Automatic release is in place, and it is conditioned to all such tests passing.

However, I noticed that, in big matrices, the situation where some jobs fail because of sporadic issues (e.g. network issues, Maven Central slowdown, etc) is quite frequent.

When this is the case I need to restart failed jobs manually, after a while, and (commonly) everything works.

I can commonly spot the situation where failures in tests are due to sporadic events because, commonly, only low percentages of jobs in the matrix fail (say 10%).

It would be nice to have GHA supporting the automatic retry of failed jobs in a matrix if the failure (resp. success) rate is below (resp. above) a given threshold.
Example below:

```yaml
jobs:
  test-jvm:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, macos-12, ubuntu-22.04 ]
        java-version: [11, 17, 19]
        jdk-dist:
          - adopt-hotspot
          - temurin
      retry:
        when-success-rate-above: 0.9
        delay: 10m
```

**Comment by suhas-coursera** [comment]
In addition, multiple retries on failed jobs will be helpful with a `retryLimit` to safegaurd, As I do have a case where 1/100 matrix Jobs got passed in a 2nd retry.

```
      retry:
        when-success-rate-above: 0.9
        delay: 10m
        maxLimit: 2 
```
