### DISCUSSION TITLE
Multiple jobs.

### DISCUSSION THREAD

**Discussion by terabytesoftw** [community/community#60144] [Actions]
### Select Topic Area

Question

### Body

I have an action in php, where i do global tests, but they are divided into groups in phpunit, here is the code.

```yml
name: build

on: [push, pull_request]

env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2]

    steps:
      - name: Generate french locale.
        run: sudo locale-gen fr_FR.UTF-8

      - name: Checkout.
        uses: actions/checkout@v3

      - name: Install PHP.
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: apc, curl, dom, imagick, intl, mbstring, mcrypt, memcached, pdo, pdo_sqlite, sqlite
          ini-values: date.timezone='UTC', session.save_path="${{ runner.temp }}"
          php-version: ${{ matrix.php }}
          tools: pecl

      - name: Install Memcached.
        uses: niden/actions-memcached@v7

      - name: Install dependencies.
        run: composer update $DEFAULT_COMPOSER_FLAGS

      - name: Run tests with phpunit and generate coverage.
        if: matrix.php == '8.1'
        run: vendor/bin/phpunit --coverage-clover=coverage.xml -colors=always

      - name: Run tests with phpunit.
        if: matrix.php != '8.1'
        run: vendor/bin/phpunit --exclude-group $PHPUNIT_EXCLUDE_GROUP --colors=always

      - name: Upload coverage to Codecov.
        if: matrix.os == 'ubuntu-latest' && matrix.php == '8.1'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
```

Now i want to divide the action by job to show in the output of the test, which groups pass the tests, then i wanted to see if it is possible to reuse this code, without writing it in each job, 

```yml
    steps:
      - name: Generate french locale.
        run: sudo locale-gen fr_FR.UTF-8

      - name: Checkout.
        uses: actions/checkout@v3

      - name: Install PHP.
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: apc, curl, dom, imagick, intl, mbstring, mcrypt, memcached, pdo, pdo_sqlite, sqlite
          ini-values: date.timezone='UTC', session.save_path="${{ runner.temp }}"
          php-version: ${{ matrix.php }}
          tools: pecl

      - name: Install Memcached.
        uses: niden/actions-memcached@v7

      - name: Install dependencies.
        run: composer update $DEFAULT_COMPOSER_FLAGS
```

I know how to use compound actions but. i wanted to see if there’s another possibility, 

thank you.
