### DISCUSSION TITLE
Environment-scoped variables aren't available in `jobs.<job_id>.if`

### DISCUSSION THREAD

**Discussion by eyalch** [community/community#60168] [Actions]
### Select Topic Area

Bug

### Body

I have a variable named `REF_NAME_TO_DEPLOY` defined on an environment named `staging`. I want for a job in my workflow to be run _only_ if the Git ref name (branch) that triggered the workflow is the same as the value of `REF_NAME_TO_DEPLOY`.

For example, if the branch I'm working on is `feature-a` then the `deployment` job should be run only if the value of `REF_NAME_TO_DEPLOY` is also `feature-a`.

It seems that the job is always being skipped regardless of the value of `REF_NAME_TO_DEPLOY`. From my testing, it seems that _environment-scoped_ variables aren't available in `jobs.<job_id>.if`. A _repository-scoped_ variable with _the same name and value_ does allow the job to run.

Another thing I tested is to temporarily change the condition to `github.ref_name == 'staging'`. This allowed the job to run successfully, which is another indicator that the issue is with `vars.REF_NAME_TO_DEPLOY`.

Here's the workflow:

```yaml
name: Staging

on: push

jobs:
  deployment:
    if: github.ref_name == vars.REF_NAME_TO_DEPLOY
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
```
