### DISCUSSION TITLE
Dependabot creates PRs for non-security updates

### DISCUSSION THREAD

**Discussion by bisgardo** [community/community#60174] [Code Security] [answered]
### Select Topic Area

Question

### Body

I have an [NPM project](https://github.com/bisgardo/github-action-regex-parse) with the following `dependabot.yml` file:
```yaml
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
```
The dependency sections of `package.json` are:
```json
  "dependencies": {
    "@actions/core": "^1.10.0"
  },
  "devDependencies": {
    "@vercel/ncc": "^0.36.1",
    "eslint": "^8.43.0",
    "jest": "^29.4.3"
  }
```

It's my impression that dependabot should suggest upgrades for security fixes only, which is also what I'd like to happen. But it seems to be suggesting upgrading through every release of `eslint` and `jest` (the others haven't done releases since I created the repo, so I don't know if the same would happen with them).

Can I configure dependabot to create PRs for updates that fix security issues only?

**Comment by carogalvin** [comment]
@bisgardo When you set up `dependabot.yml`, this is configuration for Dependabot version updates, which tries to bump you to latest. You can see more information in our documentation here: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

**Reply by bisgardo** [reply, marked as answer]
From your link I found the relevant option which is [`open-pull-requests-limit`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit). The corrected dependabot configuration (with the limitation applied to `npm` only) is
```yaml
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 0 # disable non-security updates
```

I've verified that PRs for ordinary upgrades are no longer created. I've yet to see if any will be created for security issues.
