### DISCUSSION TITLE
failed to create review: GraphQL: Resource not accessible by personal access token (addPullRequestReview)

### DISCUSSION THREAD

**Discussion by kernelsam** [community/community#60182] [Actions]
### Select Topic Area

Bug

### Body

When attempting to automate a code review from a codeowner in a dependabot workflow in an organization repository I am getting the following error: `failed to create review: GraphQL: Resource not accessible by personal access token (addPullRequestReview)`

Snippet of workflow config:
```
    runs-on: ubuntu-latest
      - name: Approve patch version PRs
        run: |
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.CODEOWNER_PR_RW_TOKEN }}
```

Running the same command (`gh pr review --approve "$PR_URL”`) locally with the codeowner token adds the review as expected. 

I am able to run the same workflow from my personal repository successfully, review is added as expected via codeowner token for dependabot pull requests.

Via debug logging I have confirmed that the token is populated during the run via an org level dependabot secret. 

I tried this as a repository level dependabot secret to closer mimic my working personal repository configuration to no avail, it fails with the same PAT error.

Review request via the REST API also results in the same error. 

I have also tested pulling out the dependabot piece and run a simplified workflow against an org repo where a pull request is approved via the same logic in the code snippet above using the gh cli and a repository action secret which worked as expected. 

Is there some sort of difference in dependabot secrets PAT behavior between personal and org repos? Why does the same gh cli command with the same token work locally?
