### DISCUSSION TITLE
Issue in github actions with schedule event

### DISCUSSION THREAD

**Discussion by SruthiChilukuri-AidenAI** [community/community#60205] [Actions]
### Select Topic Area

Question

### Body

How to implement schedule code merge every 15 minutes in github using github actions. I wrote github actions with schedule event but its not triggered.
on:
  schedule:
    - cron: "*/15 * * * *"
Schedule event like this in github actions.

**Comment by MateusOFCZ** [comment]
I have the same problem, I created cron:
```
name: Cron Workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
```
And the same is not running, I have GitHub PRO, and the repository is private, I'm looking for the solution, but I haven't found anything 😕
