### DISCUSSION TITLE
workflow ignoring inputs.<input_id>.default value?

### DISCUSSION THREAD

**Discussion by ozeta** [community/community#60217] [Actions]
### Select Topic Area

Bug

### Body

let say I have the simplest workflow:

```
name: wf
on:
  workflow_call:
    inputs:
      devel:
        description: 'enable pipeline devel'
        required: true
        type: boolean
        default: false
  push:
    branches:
      - input-flag
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: output 
        id: set-matrix
        run: |
            echo devel=${{ inputs.devel }}
```

i get this output:

```
Run echo devel=
  echo devel=
  shell: /usr/bin/bash -e {0}
devel=
```

so apparently the default value is not interpolated by the workflow and it prints nothing.

what am I missing?

**Comment by dumitrux** [comment]
How are you calling the reusable workflow?

I tried the same code and it works.

## caller-workflow.yml
```
name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: dumitrux/github-actions/.github/workflows/reusable-workflow.yml@main
    with:
      devel: true
```

## reusable-workflow.yml
```
name: Reusable workflow example

on:
  workflow_call:
    inputs:
      devel:
        description: 'enable pipeline devel'
        required: true
        type: boolean
        default: false

jobs:
  output-devel:
    runs-on: ubuntu-22.04
    steps:
      - name: output 
        id: set-matrix
        run: |
            echo devel=${{ inputs.devel }}
```


## Output
![image](https://github.com/community/community/assets/34145543/557455f6-3042-4ecd-93d8-c7472056953b)
