### DISCUSSION TITLE
Using transient environments with Azure static webapp with PR previews

### DISCUSSION THREAD

**Discussion by LordLyng** [community/community#60314] [Actions]
### Select Topic Area

Question

### Body

Hi all

This question might be mroe relvant to the `Azure/static-web-apps-deploy` action, but here goes anyway. The discussion might inspire a better solution.

I've been playing around with creating a workflow for deploying to Azure static web app using the PR preview feature.
Out of the box this works greatg with the workflow file created by Azure.

As I'm primarily managing resources and environments in GitHub i set out to create a solution that would reflect the preview environemtns in the Azure static web app in GitHub.

I'll post my workflow file here and discuss what issues i am encountering below.
```yaml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

# we evaluate if we are running in production to ensure we can set the correct ENV vars for the build
env:
  IS_PRODUCTION: ${{ github.ref_name == 'main' && github.event_name == 'push' && 'true' || 'false' }}

jobs:
# environment names can max be 255 characters long and is easier to manipulate via REST if it contains no slashes
# the environment name is resolved based on the source branch name. IF not run in PR mode the branch ahs to be main due to trigger and environment is production
  get_environment_name:
    runs-on: ubuntu-latest
    name: Get Environment name from ref
    env:
      REF_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || 'production' }}
    outputs:
      environmentName: ${{ steps.extravt_env.outputs.env_name }}
    steps:
      - id: extravt_env
        run: |
          sanitized=${REF_NAME//'/'/'-'}
          echo "env_name=${sanitized:0:255}" >> "$GITHUB_OUTPUT"

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    needs: [get_environment_name]
# environment name is resued from rpevioous job alongside the returned site url from the deploy task itself
    environment:
      name: ${{ needs.get_environment_name.outputs.environmentName }}
      url: ${{ steps.builddeploy.outputs.static_web_app_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_FLOWER_08B4A4403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          output_location: "build" # Built app content directory - optional
          skip_api_build: true
          app_build_command: "yarn run build:ci"
          ###### End of Repository/Build Configurations ######
        env:
          VITE_API_URL: ${{ fromJSON(env.IS_PRODUCTION) && vars.API_URL_PROD || vars.API_URL_PREVIEW }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    needs: [get_environment_name]
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_FLOWER_08B4A4403 }}
          action: "close"

# When the PR closes and the preview env is destroyed in Azure we want to remove the environment in GitHub as well to ensure consistency
      - name: Remove transient environment
        id: removeenv
        run: |
          gh api \
            --method DELETE \
            /repos/$REPO/environments/$ENVIRONMENT_NAME
        env:
          REPO: ${{github.repository}}
          ENVIRONMENT_NAME: ${{needs.get_environment_name.outputs.environmentName}}
          GH_TOKEN: ${{ github.token }}
```

It's a somewhat small addition to the auto-generated workflow file form Azure.

There's a couple of small issues here that bothers me, namely:

1. The deletion fails as the token resolved within the workflow doens't have permissions to delete environmetns, the call fails with the error "Resource not accessible by integration". This can be wroked around by creating a GitHub App and assigned environment rights to the app. Then create a token for the appå inside the workflow and use that for deleting the environment.
2. When posting a deployment to the REST api (https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#create-a-deployment) you get the option of amrking the environment as being transient, indicating that the environment itself is not long lvied and only exists to ahndle specific deployments. This seems to be correct when using it for PR previews. IT is however not possible (as far as I can see) to create transient environments using the `environment`property on job (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment). Again a workaround exists where you can manually create the environment alongside the deployment via the api in the workflow - this does however have the unpleasent side effect of forcing me to push deployment status updates manually where as the environment prop on the job hadnles that part neatly.

So in essence some of this might be an improvement suggestion.

Why isn't it possible to assign permissions for deleting environments within workflows? i get that some might fear malicious actions that will attempt to delete envrionments. But couldn't this be handled rather easy by requiring specific permisison properties on the given job/workflow?

Does anyone know what transient_environment prop on deployment creation actually do? I have a hard time finding an explanation for what's it's technical use is within GitHub.

Has anyone found another interesting way to track Azure staic web app previews within GitHub?
