### DISCUSSION TITLE
Using paths-ignore for ignoring everything but a sub-path

### DISCUSSION THREAD

**Discussion by bferreira** [community/community#60317] [Actions]
### Select Topic Area

Question

### Body

Hi!

I was trying to use `paths-ignore` to make it not run for a path, but to run for one sub-path and everything else.
Using a similar example to the one in the documentation:

```
on:
  push:
    paths-ignore:
      - 'sub-project/**'
      - '!sub-project/docs/**'
```

I have tried this and the opposite:
```
on:
  push:
    paths-ignore:
      - '!sub-project/docs/**'
      - 'sub-project/**'
```
But it does not run when I do a change for sub-project/docs/readme.md for example

Is there a way I can make this work?
Thanks

**Comment by ChristopherHX** [comment]
If you want both includes and excludes avoid using `*-ignore`, there is a small note about this in the docs.

I expect that the following example works.

```yaml
on:
  push:
    paths:
      - '**'
      - '!sub-project/**'
      - 'sub-project/docs/**'
```

**EDIT** Modified yaml example to fit description of OP.
