### DISCUSSION TITLE
Browser set monospace font is completely ignored by Github

### DISCUSSION THREAD

**Discussion by RaphGL** [community/community#60327] [Accessibility] [answered]
### Select Topic Area

Bug

### Body

Despite having set the monospace in both Chromium and Firefox, the font is not set on the website. This is an accessibility problem as the default font set by GitHub makes it very hard for me to read the page without straining my eyes. 
I've looked around and GitHub uses `ui-monospace` as their default, but changing it to `monospace` instead would allow people to override the monospace font in their browser settings as they see fit.

**Comment by moonfury-ops** [comment]
Thank you

**Comment by Calc-oholic** [comment]
Isn't possible.

**Reply by RaphGL** [reply]
can u further elaborate what you mean here?

**Reply by Calc-oholic** [reply]
shut up kid

**Comment by khaledh** [comment]
Can we re-open this? What's the purpose of being in control of fonts used by the browser when websites just ignore them?

Aside: Does anyone know how to map `ui-monospace` in macOS to a different font? I believe it defaults to SF Mono, but I'd like to use JetBrains Mono instead.

**Reply by RaphGL** [reply]
I closed the discussion myself as github seems to not listen nor care about their users. 
Just see how they still don't support IPv6, a lot of people have to waste extra money doing proxies to be able to use git with github on IPv6 only VPS or just pay extra for IPv4.

I'm gonna re-open this at your request but I've personally lost hope.
Also as a workaround what I've been doing is I've been setting the minimum monospace font size to be bigger so the code on github is more readable to me:
![image](https://github.com/community/community/assets/28673457/d8bc1872-6cc7-4ba6-bf5f-bb14ba347636)

**Reply by khaledh** [reply]
Thanks @RaphGL. I hope someone listens.

Meanwhile, I used an extension to override the font with custom css. It's a shame we have to jump through those hoops for some of the very basic features.

**Reply by khaledh** [reply]
For anyone wondering what my custom css is:

```css
tt, pre, code, samp,
.text-mono,
.react-code-text
.blob-code-inner {
    font-family: monospace;
}
```

**Reply by ericwbailey** [reply]
Hey there, @RaphGL. I'm a member of the GitHub accessibility team, and I've been assigned to work on this task. Unfortunately, this sort of functionality isn't part of our official support policy. That said, I'd like to help you out if I can.

If you're not already familiar, there is an option in [the Appearance section of your settings](https://github.com/settings/appearance) to set the Markdown editor font preference to use a monospace font.

If you want to adjust the entire UI to use a monospace font, I would recommend checking out a browser extension like [Stylus](https://add0n.com/stylus.html). It's actually something I use personally to tweak GitHub for things that don't work well for me as designed, and I take advantage of its cloud sync feature to ensure the experience is consistent on my work and personal laptops.

To touch on what @khaledh mentioned, you can write some selectors to target various portions of the UI. One thing you can do to affect a wide swath of the UI is to target the `body` selector and our our monospace font stack Custom Property declaration: 

```css
body {
  font-family: var(--fontStack-monospace) !important;
}
```

If you don't prefer the visual treatment of our monospace fonts, you can instead point the declaration to a font you have installed locally on your machine:

```css
body {
  font-family: 'YOUR-LOCALLY-INSTALLED-FONT' !important;
}
```

Both declarations should ideally override all font family declarations on github.com. 

I hope this approach helps you out, and also thank you for your patience with a reply here. I've also noted it in our internal feedback mechanisms, so we can hopefully begin to build out a case for future iteration on this concern.

**Reply by xPaw** [reply]
Well they didn't ask to change the font of the entire UI, but specifically the monospace font.

I was just looking at that myself wanting to change the `--fontStack-monospace`, but then things like the code viewer with its virtual textarea is just completely busted (`.react-blob-print-hide` does not use the css var for one, but even after changing its font the cursor is in the wrong position).

**Reply by ericwbailey** [reply]
The trouble with a design system is it is only as good as the teams who have adopted it, unfortunately. I've filed issues against the relevant team to update their declarations.

As you've noted, if you go the Stylus route you definitely can start to whittle down those declarations by adding then to [a `:where()` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:where) as discovered. If it's helpful you can also re-bind `--fontStack-monospace` to your own preferred font, both in the global scope on a per-selector basis:

```css
:root {
  --fontStack-monospace: 'YOUR-LOCALLY-INSTALLED-FONT';
}

:where(
  .react-blob-print-hide,
  .other-selector,
  .another-selector
) {
  --fontStack-monospace: 'YOUR-LOCALLY-INSTALLED-FONT';
  
  font-family: var(--fontStack-monospace) !important;
}
```
