### DISCUSSION TITLE
Workflow file parsing broken this morning

### DISCUSSION THREAD

**Discussion by bryannaegele** [community/community#60345] [Actions]
### Select Topic Area

Bug

### Body

One of our jobs started failing this morning (used successfully many times since any updates to the file). Other workflow files with the same first job but with different event triggers are working fine.

`The workflow is not valid. .github/workflows/release-pipeline.yml (Line: 11, Col: 5): Unexpected value 'uses' .github/workflows/release-pipeline.yml (Line: 12, Col: 5): Unexpected value 'with'`

```
name: "Release Pipeline"

on:
  release:
    types:
      - published

jobs:
  extract-project-version:
    uses: xxx/gha-workflows/.github/workflows/extract-project-version.yml@project-version-from-tag-v0.1.0-rc.6
    with:
      tag: ${{ github.event.release.tag_name }}
```
