### DISCUSSION TITLE
Empty Output of previous job is not evaluated on next job inside of if condition

### DISCUSSION THREAD

**Discussion by v-amolpatil** [community/community#60350] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hi Team,

Below is the code snippet, where job1 outputs ` Write-Output "name=''" >> $env:GITHUB_OUTPUT`. But in job2 `if` condition getting executed eventhough `name` field value is empty i.e. single quote. I see that the output is having double quotes and then single quote like this `"''"` . Could you please suggest on this ?

```
jobs:
  job1:
    uses: ./.github/workflows/job1.yaml
 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.name != ''}}
    steps:
       .....execute code if name is not empty.....
```
