### DISCUSSION TITLE
GitHub Action is not deleting remote files, which are removed in source

### DISCUSSION THREAD

**Discussion by smileBeda** [community/community#60369] [Actions]
I am using a simple GitHub workflow (see below code) that successfully pushes any new file or alteration of a file from source to remote.
However, it fails to _delete_ files on remote, that where removed in source.

Example:
1. Push new file to remote 🆗 
2. Make changes to file and push to remote 🆗 
3. Delete file from source, push to remote 🚫 

I already ensured the files on remote are owned by the same user used for the GitHub action, also the write/read permissions are set correctly.

This is my action file:
```
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: rsync -r --delete --quiet ${{ github.workspace }}/var/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}
    - name: cleanup
      run: rm -rf ~/.ssh
```

I also tried to remove `--quiet` to see some more verbose output, did not give me a clue as of why it would fail to delete the remote files
I also tried to add another step, as below, which also makes no difference:
```
- name: cleanup files
      run: rsync --delete --existing --ignore-existing --itemize-changes --progress --recursive ${{ github.workspace }}/var/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}
```

Basically, it plain outright fails to remove files from remote, if they are not present in source anymore.

Locally, this works just fine:
`rsync -r --delete --quiet /path/to/origin/* /path/to/remote`

I am thus sure this is related to the action, somehow.

If it matters, I am using VSCode to push from local to git repo, but that should really not matter, also because the push of _new files_, or _changes_ works just fine. Just _deleting_ files removed does not work

_I have read somewhere that rsync --delete does not work with wildcards, and that is clearly not true, since it works locally. BUT, amazingly and weirdly, when I do NOT use wildcard on the action, then it works. It makes not much sense to me why this would work locally, but not in a GitHub action._

I appreciate any help!
