### DISCUSSION TITLE
How do I access non-camelCase json keys on a json object within the job.if field?

### DISCUSSION THREAD

**Discussion by NullVoxPopuli** [community/community#60422] [Actions] [answered]
### Select Topic Area

Question

### Body

I have json from: https://jqplay.org/s/3fjQTNbPH3u
which looks like this:
```
{
  "test-app": {
    "test": {
      "local": false,
      "remote": false,
      "status": "MISS",
      "timeSaved": 0
    }
}    
```
And I'm trying to figure out how to access "test-app" from the json within a job.if:

```yml
  debug_pending_tasks:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: echo ${{  needs.setup.outputs.pending }}
      - run: echo '${{  needs.setup.outputs.pending.test-app.test }}'
      - run: echo '${{  fromJSON(needs.setup.outputs.pending.test-app) }}'


  test:
    name: "Default Tests"
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 5
    if: ${{ fromJSON(needs.setup.outputs.pending).test-app.test.status == 'MISS' }}
```

but in my debug_pending_tasks job, nothing ever gets printed (and it errors).

Here are the logs: https://github.com/universal-ember/ember-primitives/actions/runs/5498015280/jobs/10019200929

Thanks!

**Comment by ChristopherHX** [comment, marked as answer]
Your setup job doesn't set any output, due to a mistake.

Seems like you used `GITHUB_ENV` while expecting to use `GITHUB_OUTPUT` in the setup job.

```yaml
    outputs:
      pending: ${{ steps.set-pending.outputs.pending }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm build
      - id: set-pending
        run: echo "pending=$(./cache-status.sh)" >> $GITHUB_OUTPUT
      - run:  echo ${{ github.event.number }} > ./pr-number.txt
```
Otherwise access the value from `env`
```yaml
outputs:
      pending: ${{ env.pending }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm build
      - run: echo "pending=$(./cache-status.sh)" >> $GITHUB_ENV
      - run:  echo ${{ github.event.number }} > ./pr-number.txt

```

Your job if expressions seem to be correct, but due to an issue in job setup not working.
- `needs.setup.outputs.pending` has type string (due to a mistake in job prepare it's null)
- `needs.setup.outputs.pending.test-app.test` has type `null`, because a string (in this case null) has no property named `test-app` it is the same as `null`
- `needs.setup.outputs.pending.test-app` this is `null` and `null` converted to string '' is not valid json.

You can enable step level debugging to see step by step expression results, there is an checkbox to enable it if you press rerun job.
