### DISCUSSION TITLE
Problem writing github.json context to file

### DISCUSSION THREAD

**Discussion by flagrant99** [community/community#60515] [Actions] [answered]
### Select Topic Area

Question

### Body

Why Does the following work fine

```
- name: Echo GitHub context
      working-directory: ${{env.GITHUB_WORKSPACE}}
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        Write-Output "$GITHUB_CONTEXT"
```

But not this
```
    - name: Write GitHub context
      working-directory: ${{env.GITHUB_WORKSPACE}}
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        "$GITHUB_CONTEXT" | Out-File -FilePath .\github_context.txt -Force;
```

The file is always blank.
