### DISCUSSION TITLE
Mounting NFS volume from self-hosted runner

### DISCUSSION THREAD

**Discussion by walter-feddern** [community/community#60526] [Actions]
### Select Topic Area

Question

### Body

I am running self-hosted runners in EKS (kubernetes), using ARC and configured with horizontal runner autoscaler.
We have a use case where a user needs to mount an AWS EFS (NFS) volume in their workflow. When they try, it is getting an error b'mount.nfs4: Operation not permitted'. On a test pod I created (just running CentOS), I saw the same error on a mount attempt, but was able to resolve by setting securityContext: privileged: true on the pod deployment.

I have been reading through documentation, but can not understand where I would make the edit to a config file to either set the securityContext to privileged: true for the runner pods being created, or otherwise update the security permissions to just allow the mount command to be run.

I did try adding it to my RunnerDeployment, but it gets errors trying to validate (does not like 'privileged' here)

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gh-arc-runners
  namespace: github-actions-namespace
spec:
  template:
    spec:
      labels:
        - dependabot
      organization: redacted
      githubAPICredentialsFrom:
        secretRef:
          name: gh-arc-app-details
      resources:
        limits:
          cpu: "4"
          memory: "4Gi"
        requests:
          cpu: "100m"
          memory: "100Mi"
     securityContext:
        privileged: true

```
