### DISCUSSION TITLE
Can't access Dependabot alerts API via GitHub Action default token

### DISCUSSION THREAD

**Discussion by laughedelic** [community/community#60612] [Actions]
### Select Topic Area

Bug

## Context

I'm trying to access the `/repos/{owner}/{repo}/dependabot/alerts` API endpoint from GitHub Actions in a private (internal) repository

## Steps to reproduce

Here is a minimal workflow to reproduce it:

```yaml
name: Dependabot alerts

on:
  workflow_dispatch:
  
permissions: write-all

# also tried explicit permissions:
#   contents: write
#   security-events: write

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Call API
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api '/repos/{owner}/{repo}/dependabot/alerts'
```

## What happens

This fails with the message:

```
gh: Resource not accessible by integration (HTTP 403)
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/dependabot#list-dependabot-alerts-for-a-repository"
}
```

## Expectation

This call to the API should work because the Actions token has enough permissions. According to the [linked documentation](https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#list-dependabot-alerts-for-a-repository):

> You must use an access token with the `security_events` scope to use this endpoint with private repositories.

I've tried setting `security-events: write` permission in the workflow, but that didn't help.

Also, according to [the announcement](https://github.blog/changelog/2023-02-07-dependabot-alerts-default-permissions-change/):

> anyone with repository **write** or maintain roles will be able to view and act on Dependabot alerts by default

I don't know if this applies to GitHub Actions, but I also tried adding explicit `contents: write` permissions, which didn't help.

Even with the broadest `permissions: write-all`, it doesn't work and fails with the same error.

## What else I have tried

- I tried running `gh auth status` to check that the token is passed to the CLI correctly:

  ```
  github.com
    ✓ Logged in to github.com as github-actions[bot] (GH_TOKEN)
    ✓ Git operations for github.com configured to use https protocol.
    ✓ Token: ghs_************************************
  ```

- I tried using GraphQL API (adding to the last step):

  ```
            gh api graphql -F owner='{owner}' -F name='{repo}' -f query='
               query($name: String!, $owner: String!) {
                 repository(owner: $owner, name: $name) {
                      vulnerabilityAlerts(first: 10) {
                          nodes {
                              createdAt
                              securityVulnerability {
                                  package {
                                      name
                                  }
                              }
                          }
                      }
                 }
               }'
  ```
  It didn't fail, but returned an empty result:

  ```
  {"data":{"repository":{"vulnerabilityAlerts":{"nodes":[]}}}}
  ```

- I tried using a PAT with broad access to the repository. It works as expected. 
  This is not a solution, because providing such PAT as secret at the org level is a security concern and requires consumers of the reusable workflow to access this secret explicitly.

## Question

Since the documentation doesn't mention anything special about GitHub Actions and explicitly says that a token with the right permissions should have access, I assume that this is a bug or an unintentional limitation. Am I missing something? Is it a known bug? Is there any kind of configuration that would allow the intended usage ?
