### DISCUSSION TITLE
Problem with action to build on github-pages

### DISCUSSION THREAD

**Discussion by thiagosaud** [community/community#60655] [Actions]
### Select Topic Area

Question

### Body

I have a repository which I used `webpack `+ `html `+ `javascript `to make my website static, I had an old action to make the build in github-pages through this wokflow.

However, now it is giving the following error:
![image](https://github.com/community/community/assets/126628718/fbc6b87c-ef6a-4afc-8908-c0910e767186)

What I'm trying to do is just, when opening a PR, it will run some validation workflows, if everything is right it will run this workflow to do the automated build for github-pages.

**CODE**
```
name: GITHUB PAGES DEPLOY

on: workflow_call
permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  contents: read
  pages: write
  id-token: write

concurrency: # Allow one concurrent deployment
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        architecture: [x64]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Nodejs ${{ matrix.node-version }} - ${{ matrix. architecture }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: RUN YARN INSTALL
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: RUN YARN BUILD
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: RUN SETUP PAGES
        uses: actions/configure-pages@v3

      - name: RUN UPLOAD ARTIFACT
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist" # Upload entire repository

      - name: RUN DEPLOY TO GITHUB-PAGES
        id: deployment
        uses: actions/deploy-pages@v2
```
