### DISCUSSION TITLE
Using a different repositories secrets and vars

### DISCUSSION THREAD

**Discussion by JayMax23** [community/community#60755] [Actions]
.

**Comment by nirav-gajera** [comment]
To access secrets and variables from the subRepository in your GitHub workflow, you can use the following syntax:

`${{ secrets.subRepository.myEnvironemntName.I_AM_A_SECRET }}`

`${{ env.subRepository.myEnvironemntName.VAR_1 }}`

Replace subRepository with the actual name of your subRepository, and myEnvironemntName with the name of the environment collection where your secrets and variables are stored.

With this syntax, you can reference the secrets and variables specific to the subRepository and ensure that the workflow uses the correct values.

**Reply by nirav-gajera** [reply]
yes!

`${{ env.subRepository.myEnvironemntName.VAR_1 }}`

**Reply by nirav-gajera** [reply]
The issue might be due to the fact that environment variables defined in a sub-repository's environment context are not automatically inherited by the workflows in the main repository. You'll need to pass the environment variables explicitly from the main repository's workflow to the sub-repository's workflow

In the main repository's workflow (workflow.yml):


```
name: Run Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 2
        uses: actions/checkout@v2
        with:
          repository: Repo/tests
          path: tests

      - name: Run Repo 2 Workflow
        uses: Repo/tests/.github/actions/runTest@main
        env:
          MYKEY: ${{ secrets.tests.dev.KEY_ID }}
          USERNAME: ${{ secrets.tests.dev.TEST_USERNAME }}
          # Pass the environment variables to the sub-repository's workflow
          ENV_MYKEY: ${{ secrets.tests.dev.KEY_ID }}
          ENV_USERNAME: ${{ secrets.tests.dev.TEST_USERNAME }}
        with:
          github-token: ${{ secrets.DEPLOYMENT_PIPELINE_GITHUB_PACKAGES_READ }}
          env: |
            MYKEY=${{ secrets.tests.dev.KEY_ID }}
            USERNAME=${{ secrets.tests.dev.TEST_USERNAME }}

```

In the sub-repo (action.yml),

```
name: Build docker file and run it

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Print Environment Variables
        run: |
          echo "MYKEY: ${{ env.ENV_MYKEY }}"
          echo "USERNAME: ${{ env.ENV_USERNAME }}"
          cat .env
        env:
          ENV_MYKEY: ${{ inputs.env.MYKEY }}
          ENV_USERNAME: ${{ inputs.env.USERNAME }}

      - name: Build Docker Image
        run: |
          cd ${GITHUB_WORKSPACE}
          touch .env
          echo "MYKEY=${{ env.ENV_MYKEY }}" >> .env
          echo "USERNAME=${{ env.ENV_USERNAME }}" >> .env
          cat .env
          docker build .

```

By passing the environment variables from the main repository's workflow to the sub-repository's workflow, you should be able to access and use them correctly.
