### DISCUSSION TITLE
Conditional Jobs and matrix make it impossible to require correct statuses

### DISCUSSION THREAD

**Discussion by pbrisbin** [community/community#60792] [Actions] [answered]
### Select Topic Area

Question

### Body

<details>
<summary>Links to similar, but I think different, discussions</summary>
- https://github.community/t/github-pull-request-is-waiting-for-required-status-checks-even-with-ci-skip-in-commit-message/827
- https://github.community/t/github-actions-checks-when-not-in-triggers/194399
- https://github.community/t/pr-stuck-waiting-for-checks-which-should-be-skipped/18485
- https://github.community/t/feature-request-conditional-required-checks/16761
- https://github.community/t/skip-ci-ci-skip-dont-work-if-a-repo-has-branch-protection-enabled-travis-ci-pull-request/15326
- https://github.community/t/github-actions-and-required-checks-in-a-monorepo-using-paths-to-limit-execution/16586
- https://github.community/t/dealing-with-checks-enforced-by-branch-protection-but-skipped-by-path-filter/18451
- https://github.community/t/monorepos-and-limiting-workflows-by-changed-files-required-status-checks/136030
- https://github.community/t/force-succeed-required-workflow-when-skipped/124055
- https://github.community/t/path-filtering-on-required-pull-request-checks/18402
</details>

Consider the following workflow for a hypothetical backend component of a
monorepository:

```yaml
jobs:
  changes:
    # ...

  backend-build:
    needs: changes
    if: ${{ changes.outputs.sources == 'true' }}
    # ...

  backend-image:
    needs: backend-build
    strategy:
      matrix:
        image:
          - app-foo
          - app-bar

  backend-images:
    needs: backend-image
```

Such a Workflow will produce the following sets of PR statuses:

1- When the component has changed, and all is well:

- `backend-build`: :heavy_check_mark: 
- `backend-image (app-foo)`: :heavy_check_mark: 
- `backend-image (app-bar)`: :heavy_check_mark:
- `backend-images`: :heavy_check_mark:

Obviously, the PR should be green for this case.

2- When the component has changed, and an image fails:

- `backend-build`: :heavy_check_mark: 
- `backend-image (app-foo)`: :x:
- `backend-image (app-bar)`: :heavy_check_mark: 
- `backend-images`: _skipped_

We want the PR to be red for this case.

3- When the component has changed and the build fails:

- `backend-build`: :x:
- `backend-image`: _skipped_
- `backend-images`: _skipped_

We want the PR to be red for this case.

4- Finally, when the component has not changed:

- `backend-build`: _skipped_
- `backend-image`: _skipped_
- `backend-images`: _skipped_

We want the PR to be green for this case.

---

Notice that in cases 3 and 4, there are no `backend-image (app-x)` statuses at
all. This means that these cannot be made required; otherwise, PRs for the (very
common, very expected) case 4 would never turn green.

That’s why we added `backend-images`: that does appear in all 4 cases and so is
what we make required; that’s its only purpose. (Note: `backend-build` also
appears in all cases, and must be made required, so that case 3 is handled
correctly.)

But this creates a problem with case 2! If we can only rely on `backend-images`
as a required status, that case appears successful even though one of the matrix
builds failed. And since we can’t make the individual matrix a required status
without breaking case 4, we have no way to address this.

So, as far as I understand it, the inability to distinguish between "skipped due
to if" (case 4) and "skipped due to needed job failing" (case 2) makes it
impossible for us to set up required statuses in a way that it works correctly.

Am I missing anything?

**Comment by ChristopherHX** [comment]
Yeah I think GitHub should add expressions to required branch protection (legacy) and rules (beta).
To allow us to require one or another commit status and to create more powerful checks.
Due to the lazy evaluation design of job matrices, a skipped job may don't even have a valid matrix configuaration due to failed dependencies. (Even if your example doesn't make use of expressions, this would open a large area of inconsistencies if static and dynamic matrices would create different commit status names)

I think you can create a workflow, which creates a custom status check for your workflow.
```yaml
on:
  workflow_run:
    types:
    - completed
    workflows:
    - '**'
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - name: Create Status Check
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }} \
          -f state='${{ (github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'skipped') && 'success' || 'failure' }}' \
        -f target_url='${{ github.event.workflow_run.html_url }}' \
        -f description='Workflow ${{ github.event.workflow_run.conclusion }}' \
        -f context='${{ github.event.workflow.name }}'
      env:
        GH_TOKEN: ${{ github.token }}
```

Then make your workflow name required after merging this workflow to your default branch.

Alternatively you can fine tune your on purpose backend-images job to just run exit 1 and add an if condition like `if: failure() || cancelled()`.
Then you get skipped on success (pass), failure on cancel and broken PR

**Reply by pbrisbin** [reply]
> Alternatively you can fine tune your on purpose backend-images job to just run exit 1 and add an if condition like if: failure() || cancelled().
Then you get skipped on success (pass), failure on cancel and broken PR

This is super appealing, but I want to confirm and make sure I understand:

You're saying that in this case:

2- When the component has changed, and an image fails:

- `backend-build`: :heavy_check_mark: 
- `backend-image (app-foo)`: :x:
- `backend-image (app-bar)`: :heavy_check_mark: 
- `backend-images`: _skipped_

The `backend-images` job will see `true` from `cancelled()`? I would not expect that (since it was skipped, not cancelled).

Being able to observe cancelled-vs-skipped for this case would exactly solve my problem.

**Reply by ChristopherHX** [reply, marked as answer]
The idea is to let backend-images fail if it runs and it runs if any dependent job failed or the workflow was cancelled.

> The backend-images job will see true from cancelled()? I would not expect that (since it was skipped, not cancelled).

The failure / cancelled in the if condition will remove the implicit `success() && (<cond>)` from the Actions Service. So all skipped, success and failure cases from your post will change completely.

```yaml
jobs:
  changes:
    # ...

  backend-build:
    needs: changes
    if: ${{ changes.outputs.sources == 'true' }}
    # ...

  backend-image:
    needs: backend-build
    strategy:
      matrix:
        image:
          - app-foo
          - app-bar

  # This job will be skipped (same as success for required checks) if all dependends are either skipped or succeeded
  backend-images:
    needs: backend-image
    if: failure() || cancelled()
    steps:
    - name: Fail on purpose
      run: exit 1
```

The result of this is expected to be

Such a Workflow will produce the following sets of PR statuses:

1- When the component has changed, and all is well:

* `backend-build`: :heavy_check_mark:
* `backend-image (app-foo)`: :heavy_check_mark:
* `backend-image (app-bar)`: :heavy_check_mark:
* `backend-images`: _skipped_

2- When the component has changed, and an image fails:

* `backend-build`: :heavy_check_mark:
* `backend-image (app-foo)`: :x:
* `backend-image (app-bar)`: :heavy_check_mark:
* `backend-images`: :x:

3- When the component has changed and the build fails:

* `backend-build`: :x:
* `backend-image`: _skipped_
* `backend-images`: :x:

4- Finally, when the component has not changed:

* `backend-build`: _skipped_
* `backend-image`: _skipped_
* `backend-images`: _skipped_
