### DISCUSSION TITLE
Merge Queues and Wildcards

### DISCUSSION THREAD

**Discussion by ThomasHambach** [community/community#60819] [Pull Requests]
### Select Topic Area

Question

### Body

I've been trying to look for the reasoning behind not enabling wildcards for merge queues, however, I could not find it. Is this just a technical limitation for the time being? We can get around it by enabling this for each branch, but that would become quite tedious.

**Comment by azarudeena** [comment]
@ThomasHambach  why not simply use like this 

```
on:
  push:
    branches:
      - "main"
      - 'gh-readonly-queue/main/**'
     ....

```
