### DISCUSSION TITLE
I have two action caches with the same key

### DISCUSSION THREAD

**Discussion by hnwyllmm** [community/community#60841] [Actions]
### Select Topic Area

Question

### Body

It is strange that I have two action caches with the same key:
![image](https://github.com/community/community/assets/5187215/28e19aab-4770-4454-ac07-e5f55416e00b)

Below is my workflow file. I use the cache in ubuntu and centos.
```yml
name: Compile

jobs:
  ubuntu-x86_64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v3
      env:
        cache-name: cache-deps
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('deps/init/oceanbase.el7.x86_64.deps') }}
        path: deps/3rd
        
    - name: Build init
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: bash build.sh init
      
    - name: Build project
      shell: bash
      run: |
        bash build.sh debug
        cd build_debug && make -j4

  centos-x86_64:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
    - uses: actions/checkout@v3

    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v3
      env:
        cache-name: cache-deps
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('deps/init/oceanbase.el7.x86_64.deps') }}
        path: deps/3rd
        
    - name: Build init
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: bash build.sh init
      
```
