### DISCUSSION TITLE
Unexpected behaviour using `needs` expressions in concurrency group running reusable workflow

### DISCUSSION THREAD

**Discussion by sprymiker** [community/community#60887] [Actions]
### Select Topic Area

Bug

### Body

Greetings everyone. 
I spent a few hours understanding why my setup does not work as expected. So there is a story...

I simplified my setup to a minimal one. There is a cascade of workflows that behaves like this:

Problem:
-
<img width="1302" alt="image" src="https://github.com/community/community/assets/45598572/83f29589-5f0e-42ac-b721-52cfa2306e57">

```
Error when evaluating 'concurrency' for job 'perform'. sprymiker/test-gha/.github/workflows/test.level1.yml@bda5298e729eaaaba887153d4a4e4bbfd473af0c (Line: 27, Col: 18): Unexpected value ''
```

`test.master.yml`
```yaml
name: 'Concurrency test'

on:
  issue_comment:
    types: [created]

jobs:
  workflow:
    uses: ./.github/workflows/test.level1.yml

```
`test.level1.yml`
```yaml
name: 'Concurrency test'

on:
  workflow_call:

jobs:
  initiate:
    runs-on: ubuntu-latest
    outputs:
      group: ${{ steps.scope.outputs.group}}
    steps:
      - id: scope
        run: |
          echo "group=value1" >> $GITHUB_OUTPUT

  test-output:
    needs: [initiate]
    runs-on: ubuntu-latest
    steps:
      - name: Output value
        run: |
          # value is not empty:
          echo '${{ needs.initiate.outputs.group }}'

  perform:
    needs: [initiate, test-output]
    concurrency: ${{ needs.initiate.outputs.group }}
    uses: ./.github/workflows/test.level2.yml
    with:
      group: something
```
`test.level2.yml`
```yaml
name: 'Concurrency test'

on:
  workflow_call:
    inputs:
      group:
        required: true
        type: string

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - name: Output value
        run: |
          sleep 20
          echo '${{ inputs.group }}'
```

So according to logs in `initiate` and `test-output`, the group value is set and accessible. However it does not work as expected when used in concurrency.

But if you change the issued job like below, passing by the group value as input it WORKS.
```yaml
  perform:
    needs: [initiate, test-output]
    concurrency: ${{ needs.initiate.outputs.group }}
    uses: ./.github/workflows/test.level2.yml
    with:
      group: ${{ needs.initiate.outputs.group }}
 ```

Conclusion: 
-
The parameter used in the expression for concurrency MUST be passed as input to reusable workflow. It is not evident and challenging to figure out how to make it work.

I believe this behavior should be fixed or documented. :)

Cheers!
