### DISCUSSION TITLE
How can I view manual trigger arguments in UI after action start?

### DISCUSSION THREAD

**Discussion by NGorco** [community/community#60991] [Actions]
### Select Topic Area

Question

### Body

When I ran my action, I cannot check which inputs I did enter

UPD. Sorry, didn't write context. I want to see manual trigger arguments AFTER I triggered action or it was completed. Maybe it's a proposal for UI. 

I know I can log it somewhere in logs, but it's not convenient and doesn't make sense, since manual trigger arguments presented in UI, shy we cannot see it after we started?

**Comment by Akash1134** [comment]
Hi @NGorco ,

If you want to check the manual trigger arguments for a GitHub Actions workflow, you can use the `github` context object to access the `event` payload. The `event` payload contains information about the event that triggered the workflow, including any manual trigger arguments that were provided.

Here's an example of how to access the manual trigger arguments in a workflow:

```
name: My Workflow

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'My input description'

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print input value
        run: echo "My input value is ${{ github.event.inputs.my_input }}"
```

In this example, the `workflow_dispatch` event is used to manually trigger the workflow, and an input called `my_input` is defined with a description. In the `my_job` job, the `github.event.inputs.my_input` expression is used to access the value of the `my_input` input, and the value is printed to the console using the `echo` command.

When you manually trigger the workflow, you will be prompted to enter a value for the `my_input` input. Once you enter a value and trigger the workflow, the value will be printed to the console as part of the `Print input value` step.

By using the `github.event.inputs` object, you can access the manual trigger arguments for your workflow and use them in your workflow steps.
