### DISCUSSION TITLE
Why is this job being skipped every time?

### DISCUSSION THREAD

**Discussion by mimartin12** [community/community#61081] [Actions]
### Select Topic Area

Question

### Body

I have a workflow that performs the following.

- `setup:` Setup the environment by gathering relevant information.
- `diff:` Diff that checks the difference between two commits.
- `build-tag:` A job to build tags if a commit is a tag.
- `migrate-db:` to perform DB migrations.
- `acr-digest:` to pull SHA values from ACR.

Every time it's ran, the `acr-digest` job is skipped, and I don't understand why, because the jobs that are contained in the `needs:` are ran and complete successfully.

```yaml
  setup:
    uses: <github-user-or-org>/devops/.github/workflows/environment-setup.yaml@master
    with:
      environment: QA Cloud
      registry: <azure-registry>.azurecr.io
      ref: ${{ github.event.inputs.tag }}

  diff:
    name: Check For New Changes
    runs-on: ubuntu-22.04
    needs: setup
    env:
      _ENVIRONMENT: "QA Cloud"
      _SOURCE: ${{ needs.setup.outputs.source_name }}
      _SERVER_REF: ${{ needs.setup.outputs.proj_server_ref }}
      _SERVER_DEPLOYED_REF: ${{ needs.setup.outputs.proj_server_deployed_ref }}
    outputs:
      DEPLOY: ${{ steps.compare.outputs.deploy }}
    steps:
      [...]

  build-tag:
    name: Build Server Tag
    runs-on: ubuntu-22.04
    needs: 
      - setup
      - diff
    if: ${{ needs.setup.outputs.ref_is_tag == 'true' }}
    steps:
      [...]

  migrate-db:
    if: ${{ github.event.inputs.migrateDB == 'true' && always() || false }}
    needs: 
      - setup
      - diff
      - build-tag
    uses: <github-user-or-org>/devops/.github/workflows/mssql-db-migrator.yaml@master
    with:
      registry: ${{ needs.setup.outputs.registry }}
      ref: ${{ needs.setup.outputs.proj_server_tag }}
      environment: US-QA Cloud
    secrets:
      AZ_CREDENTIALS: ${{ secrets.<azure-credentials-secret-name> }}
      MSSQL_CONN_STRING: ${{ secrets.<mssql-conn-string-secret-name> }}

  acr-digest:
    name: Argo CD - Get Container SHA Digest
    runs-on: ubuntu-22.04
    needs:
      - setup
      - diff
    if: ${{ needs.diff.outputs.DEPLOY == 'true' }}
    steps:
      [...]
```

Skipped workflow
![image](https://github.com/community/community/assets/77340197/af709ff0-5df6-44f3-9a41-17aafb003a3d)
