### DISCUSSION TITLE
Can't trigger a workflow_action on a feature branch via the REST API

### DISCUSSION THREAD

**Discussion by dean-hpe** [community/community#61083] [Actions]
### Select Topic Area

Bug

### Body

In my <MY_WORKFLOW> .yml file I have

```
on:
  push:
  workflow_dispatch:
    branches:
      - my.long.feature.branch.name

```

This is the REST API call:

`curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer <MY_PAT>"   "https://api.github.com/repos/<OWNER>/<NAME>/actions/workflows/<MY_WORKFLOW>/dispatches" -d '{"ref": "my.long.feature.branch.name"}' -w "%{http_code}\n"`

It returns this error:

```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/actions#create-a-workflow-dispatch-event"
}
404

```

It triggering workflow_dispatch is limited to the main branch this needs to be clearly documented.
