### DISCUSSION TITLE
Including and excluding paths in the same workflow doesn't work

### DISCUSSION THREAD

**Discussion by theomelo** [community/community#61109] [Actions]
### Select Topic Area

Question

### Body

I have a GitHub workflow that's configured like this:
```
on:
  pull_request:
    paths:
    - 'lib/**'
    - '!lib/path_to_exclude/**'
```
According to [the documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths), if the changed file is `lib/path_to_exclude/something.txt`, then this workflow **shouldn't** run (which is not the case for me). Is there anything I'm missing?
