### DISCUSSION TITLE
Local composite action not found

### DISCUSSION THREAD

**Discussion by buxx** [community/community#61102] [Actions]
### Select Topic Area

Question

### Body

Hi,

I'm trying to set up composite action and use it locally. I created a "setup" action in `.github/actions/setup/action.yml` file. Containing : 

```yml
name: 'Install dependencies'
description: 'Install project OS dependencies (according using Ubuntu)'
runs:
  using: "composite"
  steps:
    - run: sudo apt-get install -y libasound2-dev libfontconfig-dev libudev-dev libzmq3-dev
      shell: bash
```

I'm trying to use it from a workflow, like this : 

```yml
[...]
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: ./.github./actions/setup
      [...]
[...]
```

But, pipeline fail with : 

> Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/OpenCombat/OpenCombat/.github./actions/setup'. Did you forget to run actions/checkout before running your local action?

My workflow do a `uses: actions/checkout@v3` before call my local action. I don't understand what is wrong.

You can see the code on this PR : https://github.com/buxx/OpenCombat/pull/122 and an error example on https://github.com/buxx/OpenCombat/actions/runs/5580754749/jobs/10198083010?pr=122 .

Thanks in advance for your time !
