### DISCUSSION TITLE
invalid registries config in dependabot.yml

### DISCUSSION THREAD

**Discussion by yunnysunny** [community/community#61121] [Code Security]
### Select Topic Area

Question

### Body

I add a dependabot.yml in my project https://github.com/yunnysunny/session-token.
```yaml
version: 2
registries:
  npm-mirror:
    type: npm-registry
    url: https://registry.npmmirror.com
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-mirror
    schedule:
      interval: "weekly"
```
But it encountered  an error:
```
The property '#/registries/npm-mirror/' of type object did not match one or more of the required schemas
```
https://github.com/yunnysunny/session-token/blob/master/.github/dependabot.yml

**Comment by lshigami** [comment]
The error you are getting is because the npm-mirror registry is not a supported registry by Dependabot. Dependabot only supports the following registries:

npmjs.com
yarnpkg.com
github.com/<organization>/<repository>
If you want to use the npm-mirror registry, you will need to use a different tool to manage your dependencies.

Here is the updated dependabot.yml file that you can use:

version: 2
registries:
  npmjs:
    type: npm-registry
    url: https://registry.npmjs.com
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
This will configure Dependabot to check for updates to your dependencies on the npmjs.com registry on a weekly basis.

**Reply by yunnysunny** [reply]
The offical docs says we can use private registries: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-private-registries .
But why can't I use public registry since even private one is supported.

**Reply by Finn-Buhse** [reply]
I tried using the same as in your updated dependabot.yml file but the error persisted

**Comment by nirav-gajera** [comment]
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    registry-url: https://registry.npmmirror.com

```

**Reply by yunnysunny** [reply]
It encountered an error:
```
The property '#/updates/0/' contains additional properties ["registry-url"] outside of the schema when none are allowed
```

**Reply by nirav-gajera** [reply]
```
version: 2
registries:
  npm-mirror:
    type: npm-registry
    url: https://registry.npmmirror.com
    name: "npm-mirror"
    # scope: ""

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-mirror
    schedule:
      interval: "weekly"
```
