### DISCUSSION TITLE
Local action not found with `./`

### DISCUSSION THREAD

**Discussion by Namchee** [community/community#61227] [Actions]
### Select Topic Area

Question

### Body

I'm currently developing a GitHub that I would like to test directly with 

```
jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - run: "ls -la"
      - name: Test the action
        uses: ./
        with:
          access_token: ${{ secrets.GH_TOKEN }}
```

However, I always get `Not Found` error whenever I tried to execute it. I'm pretty sure that the action definition is valid, however the action is stored on a private repository. Here's the screenshot of the execution log.

![Screenshot from 2023-07-19 16-05-42](https://github.com/community/community/assets/32661241/2080d581-6364-45a6-a332-fa5ff3f3ba72)

Here's the `action.yml`

```
name: summarizr
description: An experimental bot for later projects
author: Cristopher Namchee
inputs:
  access_token:
    required: true
    description: GitHub Personal Access Token
runs:
  using: 'node16'
  main: 'dist/index.js'
```

I can verify that `dist/index.js` exist.
