### DISCUSSION TITLE
using needs output from a workflow call in another workflow call

### DISCUSSION THREAD

**Discussion by jamesbradlee** [community/community#61239] [Actions]
### Select Topic Area

Bug

### Body

Using output from needed job in another job in `job.if` works as expected.

But, using output from needed job that calls a workflow does not.

![image](https://github.com/community/community/assets/125522276/ff722e44-2bfb-4107-a88f-56c284be49cb)

```yml
  versioning:
    name: Versioning
    uses: ./.github/workflows/fun-versioning.yml
    if: github.ref == 'refs/heads/main'
    with:
      strategy: semver
      input: ${{ inputs.releaseKind }}
  build:
    name: Build
    uses: ./.github/workflows/fun-build.yml
    if: needs.versioning.outputs.deploy == 'yes'
    needs: [versioning]
    permissions:
      contents: write
    with:
      version: ${{ needs.versioning.outputs.version }}
```
