### DISCUSSION TITLE
Action is queued but never starting.

### DISCUSSION THREAD

**Discussion by RobJohnson-RoJoPro** [community/community#61337] [Actions] [answered]
### Select Topic Area

Bug

### Body

My GitHub action enters the queued state, but never starts.  

I can cancel it ok and restart it but I've left it for over an hr on 3 different occasions but a runner never picks it up.

This is the setup:

```
name: "Terraform"

on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    CONFIG_DIRECTORY: "terraform"

jobs:
    terraform:
        runs-on: ubuntu-20:04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.3
            - run: terraform -chdir=terraform init
            - run: terraform -chdir=terraform fmt
            - run: terraform -chdir=terraform validate
```

Any help would be greatly appreciated.

Thanks
