### DISCUSSION TITLE
Private repository not found in my self-hosted runner

### DISCUSSION THREAD

**Discussion by avingoyal** [community/community#61423] [Actions]
### Select Topic Area

Question

### Body

Hey there, I've a git runner setup in my gcloud instance. It is running and showing up in my runners' list. Problem occurs when my go project I'm trying to build is using a private github module. 

Here are the steps I've followed:
- exposed environment variable: GOPRIVATE=github.com/<MY_ORG>/<MY_REPO>
- git config --global url."https://<PRIAVTE_ACCESS_TOKEN>:x-oauth-basic@github.com/".insteadOf "https://github.com/"

But I'm still getting the following error when I'm trying to access the private module:
	remote: Repository not found.
	fatal: Authentication failed for 'https://github.com/<MY_ORG>/<MY_REPO>/'

My github action workflow file looks like this:
```
name: CICD
on:
  workflow_dispatch:
     inputs:
        ENV:
            description: 'ENV'
            required: true
            default: 'poc'
        DOCKER_TAG:
            description: 'docker image tag'
            required: true
            default: 'latest'
env:
  NS: ${{ vars.NS }}
  ENV: ${{ github.event.inputs.ENV }}
  DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
  GOOS: ${{ vars.GOOS }}
  GOARCH: ${{ vars.GOARCH }}
  CGO_ENABLED: ${{ vars.CGO_ENABLED }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
  GKE_ZONE : ${{ vars.GKE_ZONE }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID:  ${{ vars.PROJECT_ID }}
  DOCKER_REPO:  ${{ vars.DOCKER_REPO }}
  APP_NAME:  ${{ vars.APP_NAME }}
  DOMAIN: ${{ vars.DOMAIN }}
  URL: ${{ vars.URL }}
  GOPRIVATE : ${{ vars.GOPRIVATE }}
  TOKEN: ${{ secrets.GITPAT }}

jobs:
  app-build:
    environment: ${{ github.event.inputs.ENV }}
    runs-on: my-self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure git for private modules
        run: git config --global url."https://$TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Build
        run: go build -o main main.go     <---- FAILING OVER HERE

```

**Comment by nirav-gajera** [comment]
the issue may be related to how the self-hosted runner on your gcloud instance is picking up the git configuration.

When using a self-hosted runner, it runs under the context of a specific user account. It's possible that the git configuration you set up using the command git config --global is not being used by the runner user.

To ensure that the runner user has the correct git configuration and GOPRIVATE environment variable set, you can do the following:

1. Log in to your gcloud instance and switch to the user account that the self-hosted runner is running as. Usually, this user account is the one used to run the GitHub Actions service on the runner machine.

2. Set up the git configuration and environment variable for that user account. Run the following commands:

```
git config --global url."https://github.com/".insteadOf "https://$TOKEN:x-oauth-basic@github.com/"
export GOPRIVATE=github.com/<MY_ORG>/<MY_REPO>

```
Additionally, consider using GitHub Actions' built-in support for authentication with private repositories. Instead of manually configuring the git credentials, you can use the actions/checkout action with a personal access token (PAT) that has access to the private repository. This can be done using the token input:

```
- name: Checkout
  uses: actions/checkout@v2
  with:
    token: ${{ secrets.GITPAT }}

```
