### DISCUSSION TITLE
Dynamically compute matrix array of objects

### DISCUSSION THREAD

**Discussion by y-chen** [community/community#61461] [Actions] [answered]
### Select Topic Area

Question

### Body

I am trying to dynamically compute a JSON array of objects to pass to a matrix.

This is what I have at the moment:

```
  compute-matrix:
    name: Compute matrix
    runs-on: ubuntu-latest
    needs: [get-environment-info]
    environment: ${{ needs.get-environment-info.outputs.environment }}
    outputs:
      matrix: steps.matrix.outputs.matrix

    steps:
      - name: Matrix
        if: github.event.inputs.build-all == 'false'
        id: matrix
        run: |
          echo '${{ env.BUILD_MATRIX }}' > build-matrix.json
          MATRIX=$(cat build-matrix.json | jq '[.[0]] | tostring')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Upload output
        uses: ./.github/actions/upload-artifact
        with:
          key: matrix
          value: ${{ steps.matrix.outcome == 'success' && steps.matrix.outputs.matrix || env.BUILD_MATRIX }}

      - name: Print
        run: |
          echo ${{ steps.matrix.outputs.matrix }}

  another-job:
    name: Another Job
    runs-on: ubuntu-latest
    needs: [get-environment-info, compute-matrix]
    environment: ${{ needs.get-environment-info.outputs.environment }}
    strategy:
      matrix: 
        app: ${{ fromJSON(needs.compute-matrix.outputs.matrix) }}
```

`BUILD_MATRIX` is a values obtained from GitHub secrets and it's an array of objects. What I am trying to do is to create an array with just the first element when `build-all` input is `false`.

The print and upload steps are just for debug and when I download the output from `matrix` step, the content of the file is a valid JSON. I can just copy and paste it in a website like https://jsonlint.com/ and it's a valid JSON.

But at the next job when I try to create a matrix from that output using `fromJSON` I get the error 

```
Error when evaluating 'strategy' for job 'another-job'. .github/workflows/wf.yaml (Line: 775, Col: 14): Error parsing fromJson,.github/workflows/wf.yaml (Line: 775, Col: 14): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/wf.yaml (Line: 775, Col: 14): Unexpected value ''
```

Any idea about why I can't read the output of the computation?

Thanks
