### DISCUSSION TITLE
How to start Action `on: release:` with a specific tag?

### DISCUSSION THREAD

**Discussion by classicrocker883** [community/community#61528] [Actions]
### Select Topic Area

Question

### Body

I'm looking to start an Action when a release with a specific tag or ref is used. The following example code (which doesnt work) gives you an idea of how I'm looking for it to work.

```yaml
on:
  release:
    types: [created]
    ref: 
      - 1.0.1
    
   # or it can be like
    tag: 
      - 1.1.2
```  
instead of `ref:` this can also be `tag:` or I have no idea. Is there a way to make this work? What is the correct syntax, or if there isn't one, can we implement one? Because it would be nice to make a certain Action based on 
```yaml
release:  
   types: [created] # or [published,draft] or whatever.
```
