### DISCUSSION TITLE
Preventing a default selection for dropdown's on Issue Forms

### DISCUSSION THREAD

**Discussion by jdschleicher** [community/community#61648] [Projects and Issues]
### Select Topic Area

Product Feedback

### Feature Area

Issues

### Body

Hi! I believe I am in the right place. 

I don't believe this is currently a capability for dropdown forms. It would be helpful to prevent an auto-filled selected in dropdowns so our Customers using self-service do not accidentally breeze through the form with an incorrect dropdown selection they didn't intend.

If there was a "default" attribute to add to the markdown this could give us the choice to default to a specific value or leave empty to ensure the Customer is making an intentional selection:

```yaml
  - type: dropdown
    id: non_default_selection
    attributes:
      label: What selection would you like?
      multiple: false
      default: false/none/empty
      options:
        - Yes
        - No
        - Maybe So

```

Thanks!

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).

**Comment by rakosi2** [comment]
I would also like this feature

**Comment by nijel** [comment]
I think an empty option with a validation works as you want:

```yaml
  - type: dropdown
    id: non_default_selection
    attributes:
      label: What selection would you like?
      multiple: false
      options:
        - ''
        - Yes
        - No
        - Maybe So
    validations:
       required: true
```
