### DISCUSSION TITLE
build a docker image containing a github packages module

### DISCUSSION THREAD

**Discussion by MeroFuruya** [community/community#61644] [Actions] [answered]
### Select Topic Area

Question

### Body

i have an app that uses some private npm packages hosted on github-packages.

they can be accesed via the `secrets.GITHUB_TOKEN`

now i want to containerize that image using docker and host the image with github-packages

now when i want to build the package in github actions and npm wants to install the dependencies in the image, there is an acces error when trying to fetch the npm package hosted on gh-packages.

i tried giving the npm in the image an npmrc file with secret files:

```yml
      - name: create .npmrc
        run: echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n@MeroFuruya:registry=https://npm.pkg.github.com/" > .secret_npmrc
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          secrets: |
            id=npmrc,src=./.secret_npmrc
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

```doker
# ofc i do copy all my source code and package.json/package-lock.json but thats not important atm ig
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc cat /root/.npmrc # <- it says there is no such file or directory
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm ci
CMD ["npm", "start"]
```

i always get this error:
```
3.637 npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@MeroFuruya/my-package/2.0.3/<id> - authentication token not provided
```

**Comment by yalegria** [comment]
Did you ever figure out this? I'm getting the same error when trying to build my image.

**Comment by MeroFuruya** [comment, marked as answer]
hey @yalegria, yeah i do remember figuring a way out..
but i don't remember exactly what i did to make it work.

checked the commit log real quick. only difference i see is that i created and mounted the file in another way:
```yaml
permissions:
    packages: read

...

      - name: create .npmrc
        run: 'echo -e "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN\n@mac-brand-spaces:registry=https://npm.pkg.github.com/" > .secret_npmrc'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          secret-files: |
            "npmrc=./.secret_npmrc"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

```docker
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm ci
```

hope this helps ❤️
