### DISCUSSION TITLE
Cannot setup python 3.11 on self-hosted Windows

### DISCUSSION THREAD

**Discussion by FelipeCybis** [community/community#61653] [Actions]
### Select Topic Area

Question

### Body

Hello, 

I am trying to setup a self-hosted workflow on my windows 11 machine.

Using `setup-python@v4` with a simple workflow:

```
name: Workflow

on: [push]

jobs:
  test311:
    runs-on: self-hosted
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Hello world
        run: python -c "import os; print('hello')"
  test39:
    runs-on: self-hosted
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Hello world
        run: python -c "import os; print('hello')"
```
The `test39` job runs correctly, but the `test311` fails on setup with the following error:

![image](https://github.com/community/community/assets/41338087/0371b532-b54a-44af-ae64-fd9259451716)

```
Error: Error happened during Python installation
At C:\actions-runner\_work\_temp\c1be49f0-419a-44cc-acd9-c96d78ae8b2d\setup.ps1:127 char:5
Error: +     Throw "Error happened during Python installation"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error happened ...on installation:String) [], RuntimeException
    + FullyQualifiedErrorId : Error happened during Python installation
Error: The process 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```

This may be related to what is written in the docs for python 3.8 [here](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner), because I do have another python 3.11 installation (as well as a 3.9, for which the test runs fine).

> MSI installers are used when setting up Python on Windows. A word of caution as MSI installers update registry settings.
The 3.8 MSI installer for Windows will not let you install another 3.8 version of Python. If setup-python fails for a 3.8 version of Python, make sure any previously installed versions are removed by going to "Apps & Features" in the Settings app.

There is also this open issue https://github.com/actions/setup-python/issues/679 that has not quite the same problem, but may be related. 

Has someone had similar issues with self-hosted windows and python 3.11 ? 

For now, the solution was to make a VM on a linux machine just for this.
