### DISCUSSION TITLE
Set Notifications Frequency for GitHub Advanced Security

### DISCUSSION THREAD

**Discussion by john-yacuta-submittable** [community/community#61778] [Code Security] [answered]
### Select Topic Area

Question

### Body

Is there a way in GitHub Advanced Security to create a frequency of notifications for critical/high findings, which includes Dependabot, Code scanning, and Secret scanning, for repository owners? I am getting feedback that repo owners are not getting notifications based on findings. 

Use case: As an engineer, I want to be kept up to date on new findings of critical/high GitHub Advanced Security findings in my owned repositories such as a weekly basis on every Monday morning.

**Comment by GhostOf0days** [comment]
You can use cron jobs (see https://cronexpressiontogo.com/, https://medium.com/nerd-for-tech/lets-run-cron-jobs-using-github-actions-df64496ffc4a, and https://www.hostinger.com/tutorials/cron-job) in a Github workflow or create 'dependabot.yml' (also set up 'codeql.yml' if you want') in a folder called '.github', such as the following:

```
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: 'daily'
     ```
