### DISCUSSION TITLE
Separate GitHub workflows for Build/Test and Release

### DISCUSSION THREAD

**Discussion by PaulWaldo** [community/community#61875] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm new to github workflows, so my knowledge is sparse.  I am creating a workflow that will run on all branches that does a test build and unit testing of my Go application.  I also have another workflow that will, when the destination is the main branch, create and release executables.  When I push this branch, the first workflow (test.yml) creates a build and runs the unit tests.  I can't seem to get the second one (deploy.yml) to trigger for the executable release.  Any suggestions would be appreciated.

## test.yml
```
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
      - develop
      - "*"
    tags-ignore:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
```

## deploy.yml
```
name: Deploy

on:
  workflow_run:
    workflows: Test
    # This will eventually be limited to just main
    branches:
      - main
      - develop
      - "*"

    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # `if` required because a workflow run is triggered regardless of
    # the result of the previous workflow (see the documentation page)
    # if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Checkout code
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x

      - name: Build the Go application
        run: go build -o myapp

      - name: Build and release executables
        run: |
          GOOS=darwin GOARCH=amd64 go build -o MastoTool
          GOOS=windows GOARCH=amd64 go build -o MastoTool.exe
          GOOS=linux GOARCH=amd64 go build -o mastotool

      - name: Upload executables as artifacts
        if: always() # Upload executables regardless of build success
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            MastoTool
            MastoTool.exe
            mastotool
```
