### DISCUSSION TITLE
Validation `required` is not working on default branch

### DISCUSSION THREAD

**Discussion by wu8685** [community/community#62007] [Projects and Issues]
### Select Topic Area

Bug

### Feature Area

Issues

### Body

Attribute required is not working on default branch.

I created several [issue tetmplates](https://github.com/KusionStack/kafed/blob/main/.github/ISSUE_TEMPLATE/bug-report.yaml) in my [private repository](https://github.com/KusionStack/kafed). Some of fields in these templates are configured to `required = true`. But the `required` is not working.
![image](https://github.com/community/community/assets/10124459/4f48cb20-f21d-4348-9857-d93623e01b56)

However, if I checkout another new branch like branch `develop`, the `required` is [working](https://github.com/KusionStack/kafed/blob/develop/.github/ISSUE_TEMPLATE/bug-report.yaml).
![image](https://github.com/community/community/assets/10124459/77964e5c-4a48-409f-9068-f8a15ed56895)

I doubt it relates with `default branch`, because after I set branch `develop` to `default branch`, the `required` is not working also, meanwhile the `required` in branch `main` is back to work.

this is one of my template:

```
name: Bug Report
description: As a User, I want to report a Bug.
title: "Bug: "
labels: ["kind/bug", "kafed"]
assignees:
- wu8685
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: reproduce-step
    attributes:
      label: Minimal reproduce step
      placeholder: a step by step guide for reproducing the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What did you see instead
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What is your KusionStack components and its version?
    validations:
      required: true
```

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
