### DISCUSSION TITLE
How to create an action which creates an issue when a pull request creates a new file?

### DISCUSSION THREAD

**Discussion by vishalchangrani** [community/community#62021] [Actions]
### Select Topic Area

Question

### Body

Hi,
I would like to create an action that automatically creates a new issue if someone creates a pull request which introduces a new .md file.
More specifically, in this repo - https://github.com/onflow/flips, if any user creates a `.md` file with the name `YYYYMMDD-descriptive-name.md`, I want an issue to be automatically created .
Would love some direction.
Thank you,
V

**Comment by nirav-gajera** [comment]
.md file in the `onflow/flips` repository.

```yaml
name: Create issue on md file creation
on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches:
      - main
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create issue
        if: github.event.action == 'opened'
        run: |
          yarn install
          yarn run create-issue
      - name: Close issue
        if: github.event.action == 'closed'
        run: |
          yarn install
          yarn run close-issue
```

This action will first checkout the repository and install the dependencies. Then, it will run the `create-issue` script. This script will check the name of the .md file that was created in the pull request. If the name of the file matches the pattern `YYYYMMDD-descriptive-name.md`, then the script will create a new issue with the following information:

* Title: The name of the .md file
* Body: The contents of the .md file
* Assignees: The name of the user who created the pull request
* Labels: The labels that are associated with the pull request

If the pull request is closed, then the action will run the `close-issue` script. This script will close the issue that was created by the `create-issue` script.

To use this action, you will need to create a new file in your repository called `.github/workflows/issue-on-md-file-creation.yml` and paste the contents of the action above into it. Then, you will need to add the following line to your `.github/workflows/main.yml` file:

```
jobs:
  ...
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: onflow/create-issue-on-md-file-creation@v1
```
