### DISCUSSION TITLE
Where can i get access to the parameter reference tabe of github pages?

### DISCUSSION THREAD

**Discussion by Sewens** [community/community#62047] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

Hola, I try to host a hugo blog on `pages` via gh actions.

Almost every guidance just tell me use these parameters like `${{ steps.deployment.outputs.page_url }}`, `${{ runner.os }}` or `${{ steps.pages.outputs.base_url }}`, while I can't even know about what these param really for.

So, where can I get access to these CI/CD parameter reference to learn the details?

**Comment by nirav-gajera** [comment]
The CI/CD parameter reference for GitHub Actions is available in the GitHub Actions documentation: https://docs.github.com/en/actions. You can find the list of all available parameters under the "Inputs and outputs" section for each action.

For example, the `pages` action has the following inputs and outputs:

* **Inputs:**
    * `branch`: The branch of the repository to deploy.
    * `deploy_key`: The SSH key to use for deployment.
    * `environment`: The environment to deploy to.
* **Outputs:**
    * `base_url`: The base URL of the deployed site.
    * `page_url`: The URL of the deployed page.

You can use these parameters in your workflow by referencing them using the dollar sign syntax. For example, the following workflow uses the `base_url` output from the `pages` action to set the `siteUrl` property of the Hugo site:

```yaml
name: Deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-hugo@v2

      - name: Build site
        run: hugo

      - name: Deploy site
        uses: microsoft/gh-pages@v4
        with:
          branch: gh-pages
          publish-dir: public

      - name: Set Hugo site URL
        run: |
          echo "siteUrl: ${{ steps.pages.outputs.base_url }}" > config.toml
```

This workflow will first checkout the code from the repository, then set up Hugo. Next, it will build the Hugo site and deploy it to the `gh-pages` branch. Finally, it will update the `siteUrl` property of the Hugo site to the value of the `base_url` output from the `pages` action.

For more information on using CI/CD parameters in GitHub Actions, please see the GitHub Actions documentation: https://docs.github.com/en/actions.

Here are some additional resources that may be helpful:

* GitHub Actions documentation on inputs and outputs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
* GitHub Actions documentation on using CI/CD parameters: https://github.com/readme/guides/sothebys-github-actions
* GitHub Actions documentation on the `pages` action: https://github.com/peaceiris/actions-gh-pages
* Hugo documentation: https://gohugo.io/
