### DISCUSSION TITLE
Template & replace GitHub action expressions from a string

### DISCUSSION THREAD

**Discussion by LawrenceWarren** [community/community#62059] [Actions]
### Select Topic Area

Question about GitHub actions

#### Issue overview

I have a string which contains the GitHub actions expression syntax:

```
SOME_VAL=${{ secrets.MY_SECRET }}
```

This string lives in a file, and I'm reading the contents of the file via an action. I want to template this string out, so that the expression  is replaced by the expected value, in this case the value of `secrets.MY_SECRET`, so that I can use this string as an input for another action (specifically the Docker build action)

```yaml
...
- name: Build and push
  uses: docker/build-push-action@v2
  with:
    push: true
    tags: aihumn/${{ env.IMAGE_NAME }}:${{ steps.read_yaml.outputs['version'] }}
    build-args: ${{ steps.read_yaml.outputs['build_args'] }} # This line is the using the string
```

Unfortunately, the string is literally placed as `SOME_VAL=${{ secrets.MY_SECRET }}`, not the value of the secret. Is there some kind of function I can call to template this string, e.g. `${{ template(steps.read_yaml.outputs['build_args']) }}`? 

This would be similar to the `tpl` function in [Go templating.](https://itnext.io/reference-other-values-in-helm-chart-values-file-19d44d9276c7#:~:text=tpl%20Function%20to%20Rescue,template%20string%20to%20be%20processed.)

---

#### A detailed description of the use case

I am trying to create a repository that will contains multiple Docker images, with one action that will build an individual Docker image upon push to `main` (only 1 image will be altered at a time in each commit on the main branch). The repo structure would look something like
```
.
├── images
│   ├── atlantis
│   │   ├── Dockerfile
│   │   ├── info.yaml
│   ├── jenkins
│   │   ├── Dockerfile
│   │   ├── info.yaml
..........
```

The contents of `info.yaml`, alongside each Dockerfile, would contain the images semantic version, and also the images build vars. This is important as each image has different build vars.

For example, `info.yaml` would be formatted like this:

```yaml
version: v1.2.7
build_vars: |
  SOME_VAR=SOME_VAL
  ANOTHER_VAR=ANOTHER_VAL
```

I have found [this wonderful action](https://github.com/pietrobolcato/action-read-yaml/tree/1.1.0/) for reading the YAML from `info.yaml`, and so my build command would look something like this:

```yaml
...
- name: Build and push
  uses: docker/build-push-action@v2
  with:
    push: true
    tags: aihumn/${{ env.IMAGE_NAME }}:${{ steps.read_yaml.outputs['version'] }}
    build-args: ${{ steps.read_yaml.outputs['build_args'] }}
```

This works if the build args are hard coded. If I want to use a GitHub expression, for example, this breaks:

```yaml
version: v1.2.7
build_vars: |
  SOME_VAR=SOME_VAL
  ANOTHER_VAR=ANOTHER_VAL
  A_SECRET_VAR=${{ secrets.MY_SECRET }}
```

The `${{ secrets.MY_SECRET }}` string is not templated & resolved into the secret value, it is placed literally into the build args as the string `${{ secrets.MY_SECRET }}`.
