### DISCUSSION TITLE
New user: Trouble connecting Node.js app to services in GitHub actions

### DISCUSSION THREAD

**Discussion by pineapplemachine** [community/community#62061] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi, I'm trying to migrate a repository from another CI provider to GitHub actions instead for automated tests. Our test runner needs to have a redis service available, but I am having trouble understanding how to have our Node.js application connect to a redis service in a GitHub action.

I'm getting this error when our app tries to connect with redis. The redis host is set to "redis", the name of the service, as in the [documentation](https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers):

```
Error: getaddrinfo EAI_AGAIN redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
Error: Process completed with exit code 1.
```

Here are the relevant parts of my GitHub actions yml file. (Note that the app also needs to connect to a postgres service, but the redis connection error is occurring before the app attempts to connect to postgres, so I don't know yet whether connecting to the postgres service is set up correctly or not.)

``` yaml
name: Run Automated Tests
run-name: ${{ github.actor }} is running automated tests
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x", "18.x"]
    services:
      postgres:
        image: "postgres:11.19-bullseye"
        ports: 
          - 5432
        env:
          POSTGRES_DB: "testdb"
          POSTGRES_USER: "testuser"
          POSTGRES_PASSWORD: "testpassword"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: "redis:6.0.16"
        ports:
          - 6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      
      - name: Install dependencies using yarn
        run: |
          yarn --frozen-lockfile
        
      - name: Run tests
        run: |
          npm run test
        env:
          POSTGRES_HOST: "postgres"
          POSTGRES_PORT: 5432
          POSTGRES_NAME: "testdb"
          POSTGRES_USER: "testuser"
          POSTGRES_PASSWORD: "testpassword"
          REDIS_HOST: "redis"
          REDIS_PORT: 6379
```

Any help would be very much appreciated!
