### DISCUSSION TITLE
Permission denied to pull image from github container registry

### DISCUSSION THREAD

**Discussion by nuvious** [community/community#62116] [Actions]
### Select Topic Area

Question

### Body

I'm working in an org and have setup a workflow to build a builder docker image and push it to the github container registry. I then follow that up with a job that uses that docker image to do a basic cmake build. Right now things are simple and seem like they could be done easier in other ways, but the build container and build process are going to get more complicated and this is just foundation work.

For now, I'm having an issue where the login to the github container registry seems to be working, but I then run into the following errors that break the build:

```
/usr/bin/docker --config /home/runner/work/_temp/.docker_8a[33](https://github.com/myorg/TestRepo/actions/runs/5697343991/job/15444074756#step:2:36)79c3-0114-4893-92e7-174c7120e21f login ghcr.io -u nuvious --password-stdin
  /usr/bin/docker --config /home/runner/work/_temp/.docker_8a3379c3-0114-4893-92e7-174c7120e21f pull ghcr.io/myorg/testrepo-builder:latest
  Error response from daemon: denied
  Warning: Docker pull failed with exit code 1, back off 5.02 seconds before retry.
```

Here's my workflow:

```yaml
name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-builder

jobs:
  push_to_registry:
    name: Push Docker image container registry
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./docker/builder/
          file: ./docker/builder/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  build_with_cmake:
    needs: push_to_registry
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/myorg/testrepo-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run cmake
        run: cmake .
      - name: Make
        run: make
      - name: Run for fun
        run: ./hello_cmake
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: hello_cmake
```

I have granted the repository write permissions to the org package repository and it successfully builds and pushes the container, but then in the very next step when I try to pull it, it fails. Still unsure what the issue is. I have access tokens enrolled as well and am not trying to use personal access tokens unless there's a feature gap in this functionality.

Thanks in advance for any pointers!
