### DISCUSSION TITLE
Feature request: share credentials between jobs (job outputs)

### DISCUSSION THREAD

**Discussion by pascalgulikers** [community/community#62269] [Actions]
### Select Topic Area

Feature request: add a secret output option which makes output values masked between jobs, for instance:
echo "mysecret=MySecretValue" >> $GITHUB_SECRET_OUTPUT

### Body

See: https://github.com/aws-actions/amazon-ecr-login/issues/483

To pull a custom container image at job level, credentials might be needed, i.e.

```
job-1:
    environment: ${{ needs.Initialize.outputs.environment }}
    runs-on: ubuntu-latest
    needs: [Initialize, Setup]
    permissions:
      contents: write
      packages: write
      pull-requests: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
### The following 2 lines of code are trying to leak secret data to non secret storage
      docker_username: ${{ steps.login-ecr.outputs[format('docker_username_{0}_dkr_ecr_eu_central_1_amazonaws_com', needs.Setup.outputs.accountId)] }}
      docker_password: ${{ steps.login-ecr.outputs[format('docker_password_{0}_dkr_ecr_eu_central_1_amazonaws_com', needs.Setup.outputs.accountId)] }}
    steps:
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: arn:aws:iam::${{ needs.Setup.outputs.accountId }}:role/${{ inputs.ghaIamRolePrefix }}-${{ github.event.repository.name }}
          role-session-name: GitHubActions
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
job-2:
    environment: ${{ needs.Initialize.outputs.environment }}
    runs-on: [self-hosted, X64, Linux, default ]
    needs: [Initialize, Setup, job-1]
    container: 
      image: ***.dkr.ecr.eu-central-1.amazonaws.com/our_custom_baseimage:latest
      credentials:
        username: ${{ needs.job-1.outputs.docker_username }}
        password: ${{ needs.job-1.outputs.docker_password }}
```
The above example works, but ofcourse the credentials are visible in the job output. echo ::add_mask:: isn't helpful, see: https://github.com/actions/runner/issues/475

Feature request: add a secret output option which makes output values masked between jobs, for instance:
`echo "mysecret=MySecretValue" >> $GITHUB_SECRET_OUTPUT`
