### DISCUSSION TITLE
Github actions are skipped and there's no valid reason for it

### DISCUSSION THREAD

**Discussion by vijaynallagatla** [community/community#62297] [Actions]
### Select Topic Area
GH Actions are SKIPPED

Bug

### Body

I have a CI that looks like below for publishing the tags and even though I have a valid tag generated, GH actions are skipped.
```
name: Service
on:
  release:
    types: [ published ]

jobs:
  build:
    env:

    runs-on: ubuntu-22.04
    environment: production
    if: startsWith(github.ref, 'refs/tags/service-tag_')
```
I have published a tag with prefix `service-tag_0.0.1` but still the  gh actions are SKIPPED.

**Comment by joshjohanning** [comment]
The `if` condition looks right to me, and when I tested with something similar, from a release, I was able to get it to work. 

I would remove the `if` check and then add this to your workflow for debugging:

```yml
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
```

This will show you the `github.ref` that it's using to trigger the workflow to see if it aligns.
