### DISCUSSION TITLE
Wrong path?

### DISCUSSION THREAD

**Discussion by saragon** [community/community#62303] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello,

I'm trying to trigger a workflow to be given the following situation: that the PR is into the master branch and only occur changes in solidity .sol files:

```
on:
  pull_request:
    types: [ synchronize ]
    paths:
      - "**/*.sol"
    branches:
      - master
```
But doesn't work.
Having read through all the documentation, I'm not sure what I'm doing wrong. Maybe it doesn't recognize the solidity files?
