### DISCUSSION TITLE
Github Actions submodule auto update checks out wrong branch

### DISCUSSION THREAD

**Discussion by domantaskudzius** [community/community#62325] [Actions]
### Select Topic Area

Question

### Body

I've been trying to make automatic submodule update in my parent directory work, however, I am running into issues.

The issue is that it `git submodule status` shows that I have a development branch active:

> fc201723dcb196093b... staging/api (heads/development)

Thus ending with this error eventually:

> fatal: Unable to find refs/remotes/origin/staging revision in submodule path 'staging/api'

The weirdest thing is that if I try to run `git submodule status` locally, it points me to staging branch and I can auto update successfully without any problems via `git submodule update --recursive --remote` but running it via github actions gives me the error due to checking out wrong branch?

The staging branch indeed does exist and my secret key is correct. Here is the **Action configuration:**

```
on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Git Submodule Update
        run: |
          git submodule status
          git submodule update --recursive --remote

      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.CI_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"

```

And **.gitmodules:**
```
[submodule "staging/api"]
	path = staging/api
	url = https://github.com/****/api.git
	branch = staging

```
