### DISCUSSION TITLE
Caching container actions

### DISCUSSION THREAD

**Discussion by fflaten** [community/community#62397] [Actions]
### Select Topic Area

Question

### Body

Is it possible to cache container actions somehow?

**Scenario**: I have a workflow running `playwright`. Until now I've cached the browser using `actions/cache` but it requires some OS-deps that are missing in the ubuntu runner-image. Since I'm not able to cache these dependencies, I switched to their docker-image hoping it would be faster. Unfortunately now I spend almost the same time pulling the same image on every job.

Example: 
```yml
    - name: Run Playwright tests
      uses: docker://mcr.microsoft.com/playwright:v1.36.2-jammy
      with:
        # env HOME=/root is required for Firefox
        args: env HOME=/root npx playwright test
```
