### DISCUSSION TITLE
Path filtering is triggering the ignored workflow even though there are changes there

### DISCUSSION THREAD

**Discussion by mahdiar-naufal-shyftplan** [community/community#62453] [Actions]
### Select Topic Area

Question

### Body

I have a configuration of ignoring workflow if there are no changes on filtered path following this link (I use wayback machine since the page is not there anymore): https://web.archive.org/web/20230608231526/https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks.

The problem is when I made a pull request consisting changes from a, b, and c at the same time, one of the workflows are ignored. Here's the pull request example: https://github.com/mahdiar-naufal-shyftplan/paths-ignore-test/pull/1

Could this be a misconfiguration? I want to make the a, b, and c workflow as required checks before merge

Repo's directory tree:
```
.github
  workflow
    a.yml
    a-ignored.yml
    b.yml
    b-ignored.yml
    c.yml
    c-ignored.yml
a
  README.md
b
  README.md
c
  README.md
```

and this is the workflow file:
```
# a.yml
name: A
on:
  push:
    branches:
      - main
    paths:
      - 'a/**'
  pull_request:
    types:
      - ready_for_review
      - synchronize
    paths:
      - 'a/**'

concurrency:
  group: ${{ github.workflow }}/${{ github.head_ref || github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "Test done"'

# a-ignored.yml
name: A
on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
    paths-ignore:
      - 'a/**'

concurrency:
  group: ${{ github.workflow }}/${{ github.head_ref || github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No test required"'

# b.yml
name: B
on:
  push:
    branches:
      - main
    paths:
      - 'b/**'
  pull_request:
    types:
      - ready_for_review
      - synchronize
    paths:
      - 'b/**'

concurrency:
  group: ${{ github.workflow }}/${{ github.head_ref || github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "Test done"'

# b-ignored.yml
name: B
on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
    paths-ignore:
      - 'b/**'

concurrency:
  group: ${{ github.workflow }}/${{ github.head_ref || github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No test required"'

# c.yml
name: C
on:
  push:
    branches:
      - main
    paths:
      - 'c/**'
  pull_request:
    types:
      - ready_for_review
      - synchronize
    paths:
      - 'c/**'

concurrency:
  group: ${{ github.workflow }}/${{ github.head_ref || github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "Test done"'

# c-ignored.yml
name: C
on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
    paths-ignore:
      - 'c/**'

concurrency:
  group: ${{ github.workflow }}/${{ github.head_ref || github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No test required"'

```
