### DISCUSSION TITLE
git subtree in actions

### DISCUSSION THREAD

**Discussion by jasonl-domuso** [community/community#62592] [Actions]
### Select Topic Area

Question

### Body

I am trying to run a git subtree add on a private repository in the same organization and I keep getting the error "repository not found".   However, when I run this same command locally, it works as expected.  I am using https and a pat if that matters.  How can I get this to work in github actions?

Thanks!

**Comment by jasonl-domuso** [comment]
Adding to this, I can run git clone on this same target repo within the action and it works as expected.

**Comment by karlludwigweise** [comment]
I am having the same issue. In my case it's a private repo from an organization.
I'm using a PAT that works fine locally and on servers that don't have my git config.
I've tried in workflows using `run` and in actions using an alpine docker container.

From my Dockerfile action setup:

Workflow file
```
name: "update subtree"
on:
  push:
  workflow_dispatch:

jobs:
  update-lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/subtree-pull
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
```

action.yml
```
name: "subtree-pull"
description: "run git subtree command"
inputs:
  github_token:
    description: "Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
```

Dockerfile:
```
FROM alpine:3.15.4

USER root

RUN apk add \
    bash \
    git \
    openssh \
    git-subtree

WORKDIR /app
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/bin/sh", "/app/entrypoint.sh"]
```

entrypoint.sh
```
#!/bin/bash

# Fix dubious ownership
git config --global --add safe.directory /github/workspace

# Make sure there are no prompts for git commands
git config --global url."https://api@github.com/".insteadOf "https://github.com/"
git config --global url."https://ssh@github.com/".insteadOf "ssh://git@github.com/"
git config --global url."https://git@github.com/".insteadOf "git@github.com:"
echo 'echo ${INPUT_GITHUB_TOKEN}' > $HOME/.git-askpass
cat $HOME/.git-askpass
chmod +x $HOME/.git-askpass
GIT_ASKPASS=$HOME/.git-askpass

# Debug
git --version
git subtree add --help

# Update subtree
git subtree pull --prefix=lib https://github.com/xxx/yyy.git main --squash --message "Updating subtree"
```

The `git subtree pull` command fails with

```
remote: Repository not found.
fatal: repository 'https://github.com/xxx/yyy.git/' not found
```
