### DISCUSSION TITLE
Passing GITHUB_TOKEN to checkout repository action then making file changes and committing using git errors with exit code 128

### DISCUSSION THREAD

**Discussion by PlaceReporter99** [community/community#62663] [Actions] [answered]
### Select Topic Area

Bug

### Body

To make changes to a repository via Github Actions, I pass `${{ secrets.GITHUB_TOKEN }}` to `actions/checkout@v3.5.3` , then I make the changes using a Python script (it just writes to 1 file). The `git` command part then fails because of a HTTP 403 error, saying it has no access to the repository. Here is the workflow file:
```yml
name: Search for spam

on:
  workflow_dispatch:
  schedule:
    - cron: '4/5 * * * *'

jobs:
  update_links:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3.5.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install_packages
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: run_script
        run: python3 spamsearch.py > spam_posts.md

      - name: update_repo_git
        run: |
          git config --global user.name "PlaceReporter99"
          git config --global user.email "106759534+PlaceReporter99@users.noreply.github.com"

          git add -A
          git commit -m "Update spam links"
          git push
```
