### DISCUSSION TITLE
Stuctured rich data support and better data processing helpers

### DISCUSSION THREAD

**Discussion by noirbizarre** [community/community#62670] [Actions]
### Select Topic Area

Product Feedback

### Body

While GitHub Actions is such an amazing product, there are to me lots of small things that really degrade its usability.
One of them being the lack of support for structured data (only env vars, aka. Strings) coupled by the very poor DSL which is paradoxically not providing much string processing helpers and the fact that it's `yaml` stripped from anchors (aka. you can't reuse any defined structure or data).

This could be solved by:
- allowing rich data declaration (I find it very sad to use `yaml` and only be able to use strings as data)
- huge effort on provided helpers, ideally same level of features than most high level languages builtins

(Note: I post here and hope that this is the proper place for it)

## Rich data

Given workflows are `yaml`, they have native support for rich and typed data. However, we are stuck with environment variables which are strings only and not available everywhere in the workflow (not possible to have a matric declared at root level and used in every job).

Why not provide an explicit `data` attribute at both workflow level and `job` level then available as a `data` context. It would allow at least this kind oof construct:

```yaml
name: Do something on all supported versions

on:
  push:

data:
  python-versions: ["3.10", "3.11"]
  something:
	3.10: Something for 3.10
	3.11: Something for 3.11

jobs:
  job-1:
    strategy:
      matrix:
        python-version: ${{ data.python-versions }}
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      something: ${{ data.something[matrix.python-version] }}

  job-2:
    strategy:
      matrix:
        python-version: ${{ data.python-versions }}
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      something: data.something[matrix.python-version]
```
(This example is only here to illustrate a possible `data` but to be fair and honest, I believe here the real issue is the fact that it's not possible to define a matrix at workflow level)

Obviously it needs some thinking to define proper rules of availability (is data available in env vars ?, how overriding is done, first key level or deep merge, is interpolation available within data declaration...) but being able to express structured typed data would solve a lot of issues and save a lot of pain while working daily with Github Actions

## Data processing helpers

As of today we only have access to [few helpers](https://docs.github.com/en/actions/learn-github-actions/expressions) and each time I read someone asking "How do you... ?" the answer is "You can't easily, just use bash" 😳 Not that bash isn't a great tool, but maybe in 2023 we can find something better than bash to perform basic string processing... (replacement with `sed` works, but I think it is overkill and not ergonomic nor user-friendly at all, and I don't talk about maintainability however I find myself writing this kind of processing in most workflows)

If we stick with pure string processing, I think there should be at least the common operations we find on most string types in most languages, like [JavaScript String prototype](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/String) or [Python `str` methods](https://docs.python.org/fr/3/library/stdtypes.html#string-methods).

If Github Actions is extended with rich data support, obviously having the same kind of helpers for main supported types (let's say numbers, boolean, dicts/objects, lists/arrays) could be great.
