### DISCUSSION TITLE
Pull Requests trigger push events on source branch

### DISCUSSION THREAD

**Discussion by griechelTs** [community/community#62673] [Actions]
### Select Topic Area

Question

### Body

I have two branches: `staging` and `production`. Each branch deploys to its respective environment via the following configuration:

```
#staging 
on:
  push:
    branches:
       - staging
       
 ... rest of staging deploy action defined

#production 
on:
  push:
    branches:
       - production
       
 ... rest of production deploy action defined
```

Approximately once a day, I trigger a prod release by opening a PR to merge changes into the `production` branch from `staging`. When this PR is opened, I was surprised to find that the staging deploy workflow is executed. I do not have any configuration that triggers deployments off `pull_request` actions. 

**Why does opening a PR from `staging` into `production` seemingly count as a "push" event into `staging`?**

I understand I can get around this by creating a new branch off of `staging` then opening a PR into `production` from that third branch, but I would prefer to keep the number of steps to a minimum. Also, I'm genuinely curious why this is happening!

**Comment by zMynxx** [comment]
You can try using `branches-ignore` as mentioned [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs) to work around this issue.
However, I don't see why to work with a "push" trigger on environment branches, it doesn't really follow any git strategy.

**Reply by zMynxx** [reply]
From further digging I've encountered  the [following](https://stackoverflow.com/a/61565445):
`since a merged PR will always create a push event to the branch it's being merged onto.`
Possibly the same scenario as opening a PR, I think "under the hood" each PR triggers a push, might just by it's implementation.

P.s do you have protection rules in place?

**Comment by jge162** [comment]
> ### Select Topic Area
> Question
> 
> ### Body
> I have two branches: `staging` and `production`. Each branch deploys to its respective environment via the following configuration:
> 
> ```
> #staging 
> on:
>   push:
>     branches:
>        - staging
>        
>  ... rest of staging deploy action defined
> 
> #production 
> on:
>   push:
>     branches:
>        - production
>        
>  ... rest of production deploy action defined
> ```
> 
> Approximately once a day, I trigger a prod release by opening a PR to merge changes into the `production` branch from `staging`. When this PR is opened, I was surprised to find that the staging deploy workflow is executed. I do not have any configuration that triggers deployments off `pull_request` actions.
> 
> **Why does opening a PR from `staging` into `production` seemingly count as a "push" event into `staging`?**
> 
> I understand I can get around this by creating a new branch off of `staging` then opening a PR into `production` from that third branch, but I would prefer to keep the number of steps to a minimum. Also, I'm genuinely curious why this is happening!

Hello @griechelTs 
Easy fix, just add push event to listen for which branch got push event. 

```yaml

#staging 
on:
  push:
    branches:
       - staging
jobs:
  build:
    if: github.event_name == 'push'
    # ... rest of staging deploy action defined

#production 
on:
  push:
    branches:
       - production
jobs:
  build:
    if: github.event_name == 'push'
    # ... rest of production deploy action defined
```
