### DISCUSSION TITLE
Use different icon when the build is cancelled/skipped rather than ❌ icon of the failed build

### DISCUSSION THREAD

**Discussion by marcofugaro** [community/community#62680] [Actions]
### Select Topic Area

Product Feedback

### Body

I am using the "no concurrent runs" feature:

```yml
# Allow one concurrent deployment at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
```

Which results in builds automatically being cancelled if a new action is run on the branch (in this case triggered by a commit push):

<img width="630" alt="image" src="https://github.com/community/community/assets/7217420/95ea29ec-7069-4cdb-8c72-5ea59d2b0ea1">

Which is nice and intended behaviour. However the icon on the skipped build commit is the ❌, which is the same for when the build fails.

<img width="321" alt="Screenshot 2023-08-04 at 16 10 01" src="https://github.com/community/community/assets/7217420/94a9f3a6-230f-45d3-bebe-72f89a71756e">

This results in some confusion, seeing a lot of commit with the ❌ the team becomes insensible and actually ignores when there is an actual action fail (in this case the tests fail.)

It would be ideal if the "Build Cancelled" icon on the commit was different from the "Build Failed" icon. 🙏
