### DISCUSSION TITLE
Reusing action/checkout for any job/workflow

### DISCUSSION THREAD

**Discussion by v-amolpatil** [community/community#62779] [Actions]
### Select Topic Area

Question

### Body

Currently below is working as expected but `action/checkout` is used in every job and it takes time to checkout for the same pr branch. I have also used fetch-depth: 2 as i am always looking for PR branch. Here in reusable jobs, jobA, jobB, jobC, jobD file/job internally has `action/checkout` which checkout my specific branch using `ref` condition. 
Question: Is there a way I can avoid multiple checkout to same branch? In below example all of the jobs are referencing same pr branch and also there are some logic in each of the file due to which I cannot combine each of it into a single file. Instead of doing `action/checkout` at every job, can i make only 1 checkout and reuse at any job or workflow? Is there any example that can help me in improving the performance of this?

```
on:
  repository_dispatch:
jobs:
  jobA:
    uses: ./.github/workflows/getA.yaml --> inside of this it has `action/checkout`
  jobB:
    needs: jobA
    if: ${{ condition that checks if jobA output value is not null}}
    uses: ./.github/workflows/getB.yaml  --> inside of this it has `action/checkout` to pr branch
  jobC:
    needs: jobC
    if: ${{ condition that checks if jobB output value is not null}}
    uses: ./.github/workflows/getC.yaml  --> inside of this it has `action/checkout` to pr branch
  jobD:
    needs: jobC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout -->here also it has `action/checkout` to pr branch
      - shell: pwsh
         id: step1
         run: |
            ....do something with the output from jobA,jobB,jobC...
```
