### DISCUSSION TITLE
Viewing pixel art sprites is difficult due to their small size.

### DISCUSSION THREAD

**Discussion by legoatoom** [community/community#62799] [Repositories]
### Select Topic Area

Product Feedback

### Body

Pixel art related projects often contain sprites that are relatively small.
At the moment GitHub renders them at their actual size.
When a sprite is small, e.g. 16x16, it is difficult to see the texture in detail  ([Example Apple Sprite](https://github.com/Mojang/bedrock-samples/blob/main/resource_pack/textures/items/apple.png)).
Zooming in generally does not work as images are rendered non pixelated.

At the moment I use custom CSS to 'fix' this:
```css
section[aria-labelledby="file-name-id"] img {
    width: 512px;
    image-rendering: pixelated;
}
```
However this does not work as well when the using a sprite-map, GUI elements, or viewing non-pixel art.
