### DISCUSSION TITLE
How to deploy only after test passes?

### DISCUSSION THREAD

**Discussion by kezif** [community/community#62999] [Actions]
### Select Topic Area

Question

### Body

I have two github actions: one to perform tests and other to deploy to server.
I’m aware that action could be triggered with different event for example on push to repository. But I dont understand how to tie test passing to deploy. For now my best idea is to check commit _status_ and deploy when it succeed. 
Unfortunatelly github documentation page on event triggers not clear to me.
What is best practice on how to deploy after tests passes?

[my sample repository](https://github.com/kezif/github-actions-playground/tree/main/.github/workflows)

**Comment by mehulrajdev** [comment]
Check in the local desktop first

**Reply by kezif** [reply]
you mean check tests? If so I think it break the whole idea of continuous integration

**Comment by diegocatao** [comment]
Hi @kezif,
There are different ways to achieve this.

For example, you could have two jobs, the first one would execute the checks, and if that one passes, you could trigger the job that does the deployment stuff.

```
jobs:
  tests_job:
  # Job where your tests are executed
  
    steps:
    # Your tests steps; ensure that this job prompts an error whenever a test fails

  deployment_job:
   # Job where your deployment happens
     needs: tests_job # This will make this job wait until the other job passes

    steps:
    # Your deployment steps
```

You can read more about that strategy [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds).

Hope that helps!
