### DISCUSSION TITLE
Required workflows not being triggered on pull_request closed events.

### DISCUSSION THREAD

**Discussion by Neriuzz** [community/community#63029] [Actions]
### Select Topic Area

Bug

### Body

It looks like something has recently changed with required workflows, such that a required workflow with:
```yml
on:
  pull_request:
    types:
      - closed
```
is not triggered when a pull request is closed. I first noticed this behaviour on 04/08/2023.

I also tested with a normal (non-required) workflow, and the workflow is triggered and executes as expected when a pull request is closed. Even having two workflows that are identical, but one is globally required and the other is local to a repository, the one local to the repository gets triggered on pull requested closed, but the global required one does not.

**Steps to Reproduce**
1. Create a test organisation on GitHub.
2. Create a repository for required workflows and add the following `yml` file to the repository:
```yml
name: test
run-name: Testing required workflow

on:
  pull_request:
    types:
      - closed

jobs:
  test-required-workflow:
     name: Test required workflow
     runs-on: ubuntu-latest
  
     steps:
       - name: The test
         shell: bash
         run: echo "Hey"
```
3. Register the above workflow as required in your organisation settings.
4. Create another repository, with a `.github/workflows` directory inside it. Inside that directory, add the same workflow.
5. Open and close a pull request on the above repository.
6. Visit the 'actions' tab and notice that the workflow local to the repository has run, but the required one has not.
