### DISCUSSION TITLE
macOS runner always exceeds rate limit for github API requests

### DISCUSSION THREAD

**Discussion by matcool** [community/community#63032] [Actions]
### Select Topic Area

Bug

### Body

Using this action:
```yml
name: Test macos

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Testing macos request
    runs-on: macos-latest
    steps:
      - shell: bash
        run: |
          set -xe
          curl https://api.github.com/repos/geode-sdk/geode/releases/tags/nightly > out.json
          cat out.json
```
Will always result in:
```
+ cat out.json
{"message":"API rate limit exceeded for 199.19.85.226. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```
However, if macos-latest is switched to ubuntu-latest or windows-latest, the action works fine.
