### DISCUSSION TITLE
[Feature Request] Dynamic Job Name based on Inputs

### DISCUSSION THREAD

**Discussion by zirkelc** [community/community#63118] [Actions]
### Select Topic Area

Product Feedback

### Body

The feature for dynamic workflow run names has [recently been added](https://github.blog/changelog/2022-09-26-github-actions-dynamic-names-for-workflow-runs/). 

I would like to suggest the same feature for jobs as well. I have a reusable workflow `deploy.yml` that deploys to environments based on the input `inputs.environment`. 

```yml
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency:
      group: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v3
```

The workflow is being called from another workflow `ci.yml`.

```yml
on:
  push:

jobs:
  deploy-staging:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
```

In the UI I was expecting the job name to be a concatenation of `<calling workflow job name> / <reusable workflow job name>`, in this case the job name should be `Deploy / Staging`. But it seems like job names cannot be set dynamically, so instead the job name was shown as `Deploy / deploy`.

I think in the case of reusable workflows, it would be very nice to have dynamic jobs names like this example from the [GitHub docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview):
![Workflow](https://docs.github.com/assets/cb-34427/mw-1440/images/help/actions/reusable-workflows-ci-cd.webp)

**Comment by rtack** [comment]
@zirkelc I've added this to our workflow and it works as expected. e.g. 
with the below it would use the value from `name` and not just `deploy` in the UI.
```
jobs:
  deploy:
    name: ${{ inputs.environment }}
```

**Reply by PaulRBerg** [reply]
Is this because the `.name` property (i.e. `inputs.environment`) takes priority over the YAML object name (i.e. `deploy`)?

I've seen this in the docs but I'm not sure:

https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#setting-a-name-for-a-job

**Reply by pwojATS** [reply]
I'm using .needs in order to wait for the build step to complete. The .name property shows the correct name when the build step completes:

![image](https://github.com/community/community/assets/115571978/5c82aadd-a4a4-4b32-97ef-4952a5f141c0)

Is there any way to populate the names on workflow start to achieve what we have in this sample:

![image](https://github.com/community/community/assets/115571978/110b6e94-9718-4216-815e-c391f6fab1c4)

**Reply by fclante** [reply]
Another usecase is when using a matrix that has several items in it and you want the job name to reflect the current item processed by the job --> 

```yaml
name: ${{ matrix.jobs.job-name }}
run: yada yada yada
shell: bash
```

If the matrix is empty the job name shows as ´${{ matrix.jobs.job-name }}´ in the summary which looks ugly.
