### DISCUSSION TITLE
github's secret(array) to workflow

### DISCUSSION THREAD

**Discussion by prashantsbd** [community/community#63112] [Actions]
Are there any ways to keep an array as a github secret and call individual value of an array(secret) in workflow?

**Comment by nirav-gajera** [comment]
Yeah there are two ways to keep an array as a GitHub secret and call individual values of an array(secret) in workflow:

* **Use the `secrets.GITHUB_TOKEN` secret.** The `GITHUB_TOKEN` secret is a special secret that is automatically available to all workflows. You can use this secret to access any secret in your repository, including arrays.

For example, the following workflow will print the first value of the `secrets.array` secret:

```
name: Print the first value of an array secret
on: workflow_run
jobs:
  print-array:
    runs-on: ubuntu-latest
    steps:
      - name: Print the first value of the array
        run: echo "${secrets.array[0]}"
```

* **Use the `fromJSON` function.** The `fromJSON` function can be used to parse a JSON string into a JavaScript object. This can be used to access the values of an array secret.

For example, the following workflow will print the first value of the `secrets.array` secret:

```
name: Print the first value of an array secret
on: workflow_run
jobs:
  print-array:
    runs-on: ubuntu-latest
    steps:
      - name: Print the first value of the array
        run: echo $(fromJSON(secrets.array)[0])
```

**Reply by prashantsbd** [reply]
I want to know more about using secret  Github token 
So as to obtain a single value from the array we set on github how should we set the repo action secret 
Name = ['pratik', 'hari', 'sunil']

Should we set the entire above line within the secret and make calls ? 

Or should we set 
['pratik', 'hari', 'sunil']

Or else

As regarding the github secret array[0] is gonna echo *** no matter if it takes the entire section or only the first word .

**Reply by nirav-gajera** [reply]
1. You can set the entire array as a single value. In this case, you would need to use the `fromJSON` function to parse the array into a JavaScript object. For example, the following secret would set the array `['pratik', 'hari', 'sunil']` as a single value:

```
secrets:
  array: '["pratik", "hari", "sunil"]'
```

To access a value from the array, you would use the following syntax:

```
echo $(fromJSON(secrets.array)[0])
```

2. You can set each value of the array as a separate value. In this case, you would not need to use the `fromJSON` function. For example, the following secrets would set the array `['pratik', 'hari', 'sunil']` as three separate values:

```
secrets:
  array_0: pratik
  array_1: hari
  array_2: sunil
```

To access a value from the array, you would use the following syntax:

```
echo secrets.array_0
```
