### DISCUSSION TITLE
How to add dependabot bot to environment code reviewer for Github Action?

### DISCUSSION THREAD

**Discussion by GeneralTao2** [community/community#63129] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi. 

I use Deployment protection rules for repository Environment to set Required reviewers. I would like somehow to auto-approve workflows of commits pushed by dependabot, to allow for workflow to proceed. I wanted to add the bot to Required reviewers list, but it doesn't seem possible. Is there any way to automate this process?

Thanks!

**Comment by nirav-gajera** [comment]
Yes, there is a way to automate the process of auto-approving workflows of commits pushed by dependabot, even if you can't add the bot to the Required reviewers list. You can use a GitHub Actions workflow to automatically approve the pull request created by Dependabot.

Here is an example of a GitHub Actions workflow that you can use:

```
name: Dependabot auto-approve
on: pull_request
permissions: pull-requests: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

This workflow will be triggered whenever a pull request is created by Dependabot. The workflow will then check if the actor of the pull request is the Dependabot bot. If it is, the workflow will approve the pull request using the GitHub CLI.

Once you have created the workflow, you can enable it by clicking the "Enable" button.


source: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
