### DISCUSSION TITLE
Why new issues doesn't appear on Pull Request after SARIF upload

### DISCUSSION THREAD

**Discussion by serhiykrupka** [community/community#63125] [Code Security]
### Select Topic Area

Bug

### Body

I have created a new pull request where new security issues have been introduced, but Code scanning says that no new issues are found on this PR (first screenshot). However, if we navigate to the Security tab and filter by per we can see the issue has been introduced in the current PR (see second screenshot).

# PR Result
<img width="877" alt="Screenshot 2023-08-08 at 12 34 21" src="https://github.com/community/community/assets/56821503/a8a1a9f2-498d-47b8-9182-84c5c02e1ed0">

# Security tab:
<img width="978" alt="Screenshot 2023-08-08 at 12 33 40" src="https://github.com/community/community/assets/56821503/33e5ecf1-622c-4cf4-ab72-f0216311156f">

# Workflow

```
name: Trivy Image Scanning
on:
  pull_request:
permissions: write-all
jobs:
  scan:
    name: images-scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'redis:7.2-rc3-bookworm'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
```
