### DISCUSSION TITLE
How to Retry failed commands or composite action configured in a step from a Github action.yml file

### DISCUSSION THREAD

**Discussion by GithubUserPraveen** [community/community#63127] [Actions]
### Select Topic Area

General

### Body

Hi All, 

I am new to github. But I have past experience with git.
I have a query regarding retry the failed commands or composite actions.
These commands or composite actions are configured as a step in my action.yml.
I want to give a retry to these failed steps from the action.yml.

Any suggestion or documents are welcome.

Thank you,
Praveen

**Comment by nirav-gajera** [comment]
There are two ways to retry failed commands or composite actions in your action.yml file:

* **Use the retry-step action.** The retry-step action is a GitHub Action that allows you to retry a failed step up to a specified number of times. The retry-step action takes the following inputs:
    * `command`: The command to run.
    * `max_attempts`: The maximum number of times to retry the command.
    * `retry_wait_seconds`: The number of seconds to wait between retries.

For example, the following action.yml file will retry the `npm install` command up to 3 times, with a 10-second delay between retries:

```
steps:
  - name: Install dependencies
    run: npm install
    retry:
      command: npm install
      max_attempts: 3
      retry_wait_seconds: 10
```

* **Use the `continue-on-error` attribute.** The `continue-on-error` attribute allows you to continue the workflow even if a step fails. This means that you can retry the failed step manually by running the workflow again.

For example, the following action.yml file will continue the workflow even if the `npm install` command fails:

```
steps:
  - name: Install dependencies
    run: npm install
    continue-on-error: true
```

**Reply by GithubUserPraveen** [reply]
Hi Nirav,

Thank you for the reply.
Is this feature will also be available in Github enterprise. 
I get an error : Unexpected value 'retry'.

Is it because my company doesn't allow to use global action only local actions can be used withing the company enterprise Github account.

**Reply by GithubUserPraveen** [reply]
Hi All,

Even I tried running retry-setup action as mentioned above from my private account on github.
I am getting the same error which says "Unexpected value 'retry'."
Can anyone help me below is the step I have defined in my workflow file.

 - name: Test Retry
        run: npm install
        retry:
          command: npm install
          max_attempts: 3
          retry_wait_seconds: 5

**Reply by tao12345666333** [reply]
@GithubUserPraveen maybe its retry-step action. 
https://github.com/marketplace/actions/retry-step

**Reply by carolinectan** [reply]
GitHub Actions doesn’t have a built-in retry: key, but I was able to hand-roll a retry loop in the workflow step itself. For example:

```
- name: "Run specific folder of tests"
  run: |
    max_attempts=3
    attempt=1

    # First run (no retry message)
    bundle exec rspec spec/integration && exit 0

    # Retries if the first run failed
    until [ "$attempt" -ge "$max_attempts" ]
    do
      echo "❌ Attempt $attempt failed. Retrying..."
      attempt=$((attempt+1))
      bundle exec rspec spec/integration && exit 0
    done

    echo "❌ All $max_attempts attempts failed."
    exit 1
```

**Comment by Jaber-Saed** [comment]
Hello Praveen,

In GitHub Actions, you can indeed implement retry logic for failed steps, including commands or composite actions, directly within your workflow YAML file (often named `main.yml` or similar). This retry functionality helps improve the stability of your workflow by allowing certain steps to be retried if they fail due to transient issues.

Here's how you can set up retry logic for specific steps within your workflow:

```yaml
name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Commands or Composite Actions
        run: |
          # Your commands or use of composite actions here

      - name: Retry on Failure
        if: ${{ failure() }}
        run: |
          echo "Retrying step..."
          # Additional retry logic or necessary actions here
```

In the example above, after the `Run Commands or Composite Actions` step, there's a step named `Retry on Failure`. This step uses the `failure()` function to check if the previous step failed. If the previous step failed, this step will run, allowing you to implement any retry logic or additional actions you want to take when a step fails.

Keep in mind the following tips:

1. **Customize Retry Logic:** You can customize the retry logic inside the `Retry on Failure` step according to your needs. For example, you might want to add a delay using `sleep` before retrying, or you might want to retry a certain number of times before giving up.

2. **Scope of Retry:** The retry logic provided in the example will only retry the steps within the same job. If you have multiple jobs in your workflow, each job's steps are independent of one another.

3. **Workflow-Level Retry:** If you want to retry the entire workflow in case of failure, you can use the `on` event to trigger the workflow only on failure:

   ```yaml
   on:
     push:
       branches:
         - main
     workflow_run:
       workflows: ["My Workflow"]
       types:
         - completed
       result:
         - failure
   ```

   This example will trigger the workflow on each push to the `main` branch, and also whenever a workflow run (in this case, "My Workflow") completes with a failure result.

Remember to carefully design your retry logic to avoid excessive retries and to handle transient failures gracefully. Additionally, GitHub Actions provides built-in retry mechanisms for certain actions, such as `jobs.<job_id>.steps[*].with.tries` and `jobs.<job_id>.steps[*].with.max-parallel`.

For more advanced retry scenarios and additional options, you can explore GitHub's official documentation on workflow syntax:
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)

Happy coding and welcome to GitHub Actions! If you have more questions, feel free to ask.
