### DISCUSSION TITLE
Job Task Restarts each time file is modified

### DISCUSSION THREAD

**Discussion by chrisleyva** [community/community#63137] [Actions]
### Select Topic Area

Question

### Body

Hello, 

I have the following workflow job that runs when we create PRs.
I have a problem with the 3rd `run` task: `run: npm run build:lighthouse-config`

As a result of that, a file is modified. But then the task re-runs. And this happens infinitely until I cancel the job.
**_Is there a way to modify a file as part of a workflow job and not have the task restart each time?_**

Thank you!

```yaml
name: Lighthouse Audit
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install && npm install -g @lhci/cli@0.8.x
      - run: npm run build
      - run: npm run build:lighthouse-config
      - run: lhci collect
      - run: lhci upload
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
```

Screenshot of the restart message.
![image](https://github.com/community/community/assets/1437143/73d2d860-bcf8-4082-b471-355106e3d7bf)
