### DISCUSSION TITLE
Scheduled workflow is not running anymore

### DISCUSSION THREAD

**Discussion by dorienmc** [community/community#63146] [Actions]
### Select Topic Area

Question

### Body

I have encountered strange behaviour for one of my (daily) scheduled workflows, a month ago it suddenly stopped running.
This is strange because;

1. The workflow is not disabled 
2. It's on a private organizational repository (so automatic disable should not be done by github)
3. A similar workflow (different parameters, different cron time) does run daily
4. The latest commit/PR on the repository was on July 5th (so way less than 60 days ago)
5. The same workflow on different repositories does run daily
6. The workflow syntax has not changed (latest change was on May 4th)
7. The last run (on July 3th) was successful (and so where at least the 10 before that)

It's not like the schedule event is triggered and the flow fails, the schedule event is never even triggered. 
Note that it uses `cron: '0 12 * * 1-5'` which is considered a peak hour, but so do our other repositories (about 10 of them) and those all run fine. It's neither a point of permissions, as a similar workflow (see point 3) runs fine. And in that case I would expect it to fail instead of not be triggered at all.

**More on point 2**
This workflow does run daily
```
# ./github/workflows/deploy-production.yml
name: Daily deploy to production

on:
  schedule:
    # Deploy every weekday at 08:00 UTC
    - cron: '0 8 * * 1-5'

jobs:
  deploy:
    uses: '<internal organization repo>/.github/workflows/deploy.yml@main'
    secrets: inherit
    with:    
      environment: production
```

But this workflow does one not
```
# ./github/workflows/deploy-staging.yml
name: Daily deploy to staging

on:
  schedule:
    # Deploy every weekday at 12:00 UTC
    - cron: '0 12 * * 1-5'

jobs:
  deploy:
    uses: '<internal organization repo>/.github/workflows/deploy.yml@main'
    secrets: inherit
    with:    
      environment: staging
```

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by ThibauldC** [comment]
Did you ever solve this @dorienmc ? We are facing the same issue

**Comment by HApolonio** [comment]
I have the same behaviour on some of my workflows, and I'm still searching for answers in late 2025...

**Comment by reukiodo** [comment]
Our scheduled workflows were all disabled because of no active commits, even though the build process pulls in newest images and libraries from each run, so every build result is different.

**Comment by Scolliq** [comment]
If you want to know immediately when a scheduled workflow stops running (rather than discovering it days later), you can add a heartbeat ping as the final step:

```yaml
- name: Report success
  if: success()
  run: curl -fsS --retry 3 https://gabe.usegabe.workers.dev/ping/YOUR_ID
```

Or use the GitHub Action:

```yaml
- uses: Scolliq/gabe-action@v1
  with:
    ping-url: ${{ secrets.GABE_PING_URL }}
```

[Gabe](https://github.com/Scolliq/gabe) monitors the pings and alerts you via Slack/Discord webhook if one is missed. Free for 3 monitors, open source.
