### DISCUSSION TITLE
Run rustfmt on CI

### DISCUSSION THREAD

**Discussion by harrydt** [community/community#63210] [Actions]
### Select Topic Area

Question

### Body

Is there a way to run rustfmt and clippy/other rust linters in Github action?

**Comment by sebsadface** [comment]
### Using `rustfmt` in GitHub Actions:

You can use `rustfmt` to automatically format your Rust code according to the Rust style guidelines. Here's a sample GitHub Actions workflow to run `rustfmt`:

```yaml
name: Rust Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt

    - name: Run rustfmt
      run: cargo fmt -- --check
```

### Using `clippy` in GitHub Actions:

`clippy` is a collection of lints to analyze your Rust code. Here's a sample GitHub Actions workflow to run `clippy`:

```yaml
name: Rust Clippy Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy

    - name: Run clippy
      run: cargo clippy -- -D warnings
```

### Notes:

- These workflows will run on every push and pull request to the `main` branch. You can modify the `on` section to customize the triggering conditions.
- The `cargo fmt -- --check` command checks the code format without making any changes. To automatically format the code and commit the changes, you would need additional steps.
- The `cargo clippy -- -D warnings` command treats warnings as errors, failing the build if any are found. You can customize the clippy command to suit your project's requirements.

By integrating these workflows into your GitHub Actions, you can ensure that every pull request and commit adheres to the code style and passes the lint checks, maintaining code quality and consistency.
