### DISCUSSION TITLE
Could it be possible to edit a JSON file with Github Pages?

### DISCUSSION THREAD

**Discussion by ljpprojects** [community/community#63238] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Feature Area

Projects

### Body

I was wondering if you could edit a JSON file on GitHub Pages, knowing that you can't use PHP or Node.js.  For example if I had a JSON file named "data.JSON" containing the following data -> `{
    "Data":[
        {"Greeting": "Hello!"}
    ]
}`
```
Could I edit the value of "Greeting"? Or will I have to use something other than GitHub Pages? (If so could you give me some recommendations that are free?)
If possible using JS or something that I can embed into my website and run.

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).

**Comment by nirav-gajera** [comment, marked as answer]
you can use Netlify. Netlify is a static site hosting service that allows you to use PHP and Node.js to dynamically edit your pages.


Using a GitHub Action:
```
name: Edit JSON file
on:
  push:
    branches:
      - main
jobs:
  edit-json-file:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the JSON file
        run: |
          git fetch
          cp data.json data.json.bak

      - name: Edit the JSON file
        run: |
          sed -i 's/"Greeting": "Hello!"/"Greeting": "Goodbye!"/g' data.json

      - name: Save the JSON file
        run: |
          git add data.json
          git commit -m "Edited the JSON file"
          git push
```


 you can edit the value of "Greeting" using JavaScript. You can use the following code to edit the value of the "Greeting" property:

```
const data = require("./data.json");

data.Data[0].Greeting = "Goodbye!";

const updatedData = JSON.stringify(data);

fs.writeFileSync("data.json", updatedData);
```
This code will first load the JSON file into a JavaScript object. Then, it will change the value of the "Greeting" property to "Goodbye!". Finally, it will save the updated JSON file to disk.

You can embed this code into your website using a script tag. The following is an example of how you can do this:
```

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
$(document).ready(function() {
  // Load the JSON file
  const data = require("./data.json");

  // Edit the value of the "Greeting" property
  data.Data[0].Greeting = "Goodbye!";

  // Save the updated JSON file to disk
  const updatedData = JSON.stringify(data);
  fs.writeFileSync("data.json", updatedData);
});
</script>
```
