### DISCUSSION TITLE
[Generate release's note] Generate changelogs for a merge commit that has multiple labels

### DISCUSSION THREAD

**Discussion by vctqs1** [community/community#63249] [Repositories]
### Body

Let's consider a scenario where we have 1 PR with labels Service A, Service B, and Service C:

![image](https://github.com/community/community/assets/30227910/60f25910-1360-4036-a4c6-82a35a9877fc)

The release.yaml file appears as follows:

```
changelog:
  categories:
    - title: AAA Service
      labels:
        - AAA
    - title: BBB Service
      labels:
        - BBB
    - title: CCC Service
      labels:
        - CCC
    - title: Other Changes
      labels:
        - "*"
``` 

When generating the changelogs, we expected the merge commit of the above PR to be included in all three services. However, it only gets included in the first one, which has top priority:

![image](https://github.com/community/community/assets/30227910/7b7551c5-1551-4649-a67d-721e0aaf7834)

Do we expect it to appear in the changelogs of Service A, B, and C as well? If so, how can we achieve that?

### Guidelines

- [X] I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.
