### DISCUSSION TITLE
on.push.branch: '**' filter required to make on.push.paths filters work?

### DISCUSSION THREAD

**Discussion by papadeltasierra** [community/community#63314] [Actions]
### Select Topic Area

General

### Body

I've found some posts that imply that in order to make a workflow work if...
- one or more path file changes happen OR
- specific tags are pushed

... I also have to add a branches filter like this:
```yaml
on:
  push:
    paths:
      - 'this/dir/*'
      - 'a/tree/**'
    branches:
      - '**'
    tags:
      - 'v1.0.*'
```
Can someone please explain why the `on.push.branches` filter is required?
