### DISCUSSION TITLE
Add a condition in GitHub Action for review_requested

### DISCUSSION THREAD

**Discussion by ClayGao** [community/community#63340] [Actions]
### Select Topic Area

Question

### Body

I have the following question: I hope that when my team clicks "Request Review" in a PR, it can trigger a workflow to send a code review notification to Slack. If they click on the "Reviewers" list and then select the members they want to request a review from, it will run only once, which is fine because the review is a one-time action.

<img width="475" alt="image" src="https://github.com/community/community/assets/48955965/d301870a-6004-4414-abcb-471e292d6837">

However, if they click on "Suggestion" for a member, each time they click "Request," it sends duplicate notifications.

<img width="449" alt="image" src="https://github.com/community/community/assets/48955965/94c8eda6-4779-4448-b2d9-3be6e0508596">

Is there a condition I can use in GitHub Action to determine whether the Pull Request already has reviewers assigned, so that the workflow won't run again?

Here's the current GitHub Action I have attached:

Please note that you need to provide the actual content of the GitHub Action for further assistance.

```
name: PR Review

on:
  pull_request:
    branches: [main, staging, staging-ci]
    types: [review_requested]

jobs:
  ## https://github.com/marketplace/actions/slack-pr-open-notification
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack PR when request review
         run: echo run job
```
