### DISCUSSION TITLE
Re-run failed jobs, doesn't use the updated PR body even with having 'edited' within types.

### DISCUSSION THREAD

**Discussion by Vishnum98** [community/community#63375] [Actions]
### Select Topic Area

Bug

### Body

The issue is same as this thread: https://github.com/orgs/community/discussions/48251
Even after having `edited` within types.

Github actions is picking the stale PR description which was present on the last commit. And always failing.

I have to push a commit to get it to pick the latest PR description.

```
name: PR Description Check
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  pr-description-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check PR Description
        run: |
          pr_description=$(
            cat <<END
            ${{ github.event.pull_request.body }}
          END
........
```

**Comment by paulo-a-junior** [comment]
Stumbled on the same issue... Managed to get it done by manually fetching the PR Details and updating the PR Body, and dumping to a file, for later usage.

Sample code: 
```
            const prDetails = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            core.setOutput('prBody', prDetails.data.body);

            const fs = require('node:fs');
            let contextCopy = JSON.parse(JSON.stringify(context.payload));
            contextCopy.pull_request.body = prDetails.data.body;
            fs.writeFileSync('githubcontext.json', JSON.stringify(contextCopy, null, 2));
```

**Comment by ostaquet** [comment]
Same here, I had the same issue.

Here is a very simple way to manage it in the CI:

```
name: ci

on:
  pull_request:
    branches:
      - '**'

jobs:
  validate-pr-desc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
      - name: Validate PR description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          PR_BODY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
            | python3 -c "import sys, json; print(json.load(sys.stdin)['body'] or '')")
          export PR_BODY
          bash .github/scripts/check-pr-desc.sh

[...]
```

Then, the script is a simple bash:

```
#!/bin/bash
# Check that the PR description has been properly filled in by the developer.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

PR_BODY="${PR_BODY:-}"

if [[ -z "$PR_BODY" ]]; then
    echo -e "${RED}ERROR: PR_BODY environment variable is not set.${NC}"
    exit 1
fi

[... perform tests on $PR_BODY...]
```
