### DISCUSSION TITLE
GitHub not caching the LLVM build on Windows

### DISCUSSION THREAD

**Discussion by skill-issue0** [community/community#63439] [Actions]
### Select Topic Area

Question

### Body

```name: Windows CI (LLVM)

on: [push, pull_request]

jobs:
  x86_64-windows-llvm:
    runs-on: windows-2022
    steps:
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@cec98b9d092141f74527d0afa6feb2af698cfe89 # v1.12.1

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm
          key: llvm-libs-16.0.3-msvc

      - name: Download LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          iwr https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.3/llvm-16.0.3.src.tar.xz -OutFile llvm.tar.xz
          (Get-FileHash -Algorithm SHA256 .\llvm.tar.xz).hash -eq "D820E63BC3A6F4F833EC69A1EF49A2E81992E90BC23989F98946914B061AB6C7"
          7z x llvm.tar.xz
          7z x llvm.tar
          mv llvm-* llvm-src
      - name: Download LLVM's CMake files
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          iwr https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.3/cmake-16.0.3.src.tar.xz -OutFile cmake.tar.xz
          (Get-FileHash -Algorithm SHA256 .\cmake.tar.xz).hash -eq "B6D83C91F12757030D8361DEDC5DD84357B3EDB8DA406B5D0850DF8B6F7798B1"
          7z x cmake.tar.xz
          7z x cmake.tar
          mv cmake-* cmake
      - name: Build LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        working-directory: ./llvm-src
        run: |
          cmake . -Thost=x64 -DLLVM_TARGETS_TO_BUILD="X86;AArch64" -DLLVM_USE_CRT_RELEASE=MT -DBUILD_SHARED_LIBS=OFF -DCMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_ENABLE_ZSTD=OFF
          cmake --build . --config Release
          cmake -DCMAKE_INSTALL_PREFIX=$(pwd)\llvm -P cmake_install.cmake
          
  x86_64-windows-test:
    runs-on: windows-2022
    needs: [x86_64-windows-llvm]
    steps:
      - name: Disable CRLF line ending substitution
        run: |
          git config --global core.autocrlf false
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@cec98b9d092141f74527d0afa6feb2af698cfe89 # v1.12.1

      - name: Restore LLVM
        uses: actions/cache/restore@v3
        with:
          path: llvm
          key: llvm-libs-16.0.3-msvc
          fail-on-cache-miss: true```

This is my workflow. In the LLVM step, cable manages to build llvm after a long time and my workflow didn't even cache it.

**Comment by nirav-gajera** [comment]
To fix this, you can update the `cache-llvm` step to include the `fail-on-cache-miss` option. This will ensure that the workflow will only build LLVM from scratch if the cache is missing.


```
- name: Cache LLVM
  id: cache-llvm
  uses: actions/cache@v3
  with:
    path: llvm
    key: llvm-libs-16.0.3-msvc
    restore-keys: llvm-libs-16.0.3-msvc
    fail-on-cache-miss: true
```

**Reply by skill-issue0** [reply]
Lemme try and turn real quick

**Reply by skill-issue0** [reply]
```Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set. Input key: llvm-libs-16.0.3-msvc```
I get this error now

**Reply by nirav-gajera** [reply]
https://github.com/actions/cache/issues/1114
https://github.com/actions/runner/issues/2448

**Reply by skill-issue0** [reply]
Can you make changes to my workflow (repo: skill-issue0/test), would really appreciate as I have not found the correct fix,  u can submit a PR or edit my current workflow code and send the updated one here 🙏

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by Ravenwater** [comment]
I am running into this issue as well. Caching works on Linux and MacOS but fails on Windows. 

```
Run actions/cache@v3
  with:
    path: llvm-install
    key: Windows-llvm-release/19.x-
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.1[2](https://github.com/branes-ai/dfa-dynamics/actions/runs/13610185201/job/38046314295#step:4:2).9\x64
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\[3](https://github.com/branes-ai/dfa-dynamics/actions/runs/13610185201/job/38046314295#step:4:3).12.9\x64/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.9\x6[4](https://github.com/branes-ai/dfa-dynamics/actions/runs/13610185201/job/38046314295#step:4:4)
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.9\x[6](https://github.com/branes-ai/dfa-dynamics/actions/runs/13610185201/job/38046314295#step:4:6)4
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.[9](https://github.com/branes-ai/dfa-dynamics/actions/runs/13610185201/job/38046314295#step:4:9)\x64
Cache not found for input keys: Windows-llvm-release/19.x-
```

Is this a known issue, or has it been resolved?
