### DISCUSSION TITLE
Cannot Automate E2E Testing using Playwright in a CI Environment with GitHub Actions.

### DISCUSSION THREAD

**Discussion by shirotamaki** [community/community#63567] [Actions]
### Select Topic Area

Question

### Body

Hello Everyone,

I am currently working on building a CI environment using GitHub Actions. My goal is to automate E2E testing with Playwright. I've set up a .yml file in GitHub Actions and defined a workflow. However, I'm encountering an error that I cannot resolve.

While the tests run successfully on my local machine, the settings in the frontend/playwright.config.ts file aren't being reflected in GitHub Actions.

How can I make sure that frontend/playwright.config.ts is properly applied within GitHub Actions?

Development Environment:
React: 18.2.0
Next.js: 13.4.6
Ruby: 3.2.1
Rails: 7.0.4

Repository:
https://github.com/shirotamaki/outdoor-heart-sutra 

.github/workflows/frontend-test.yml:

```yml
name: "Frontend Test"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.8
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: "3.2.1"
          bundler-cache: true
      - name: Install libvips
        run: sudo apt install -y libvips
        working-directory: ./backend
      - name: Install dependencies
        run: bundle install
        working-directory: ./backend
      - name: Set up database
        run: |
          bundle exec rails db:schema:load RAILS_ENV=test
          bundle exec rails db:reset RAILS_ENV=test
        working-directory: ./backend
      - name: Start Rails server
        run: |
          bundle exec rails s -p 3000 &
          sleep 30
        working-directory: ./backend
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend
      - name: Start Next.js server
        run: |
          npm run dev &
          sleep 30
        working-directory: ./frontend
      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.ts
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
        working-directory: ./frontend
```

I tried again, but the error persists.

I suspect the issue arises because the settings in playwright.config.ts are not being imported correctly. This is based on the error message Timeout 30000ms exceeded, even though the playwright.config.ts configuration specifies a timeout of 60 * 1000 milliseconds.

Error details can be found here: https://github.com/shirotamaki/outdoor-heart-sutra/actions/runs/5841889070/job/15842461005?pr=383
```
Run npx playwright test --config=playwright.config.ts
  npx playwright test --config=playwright.config.ts
  shell: /usr/bin/bash -e {0}
  env:
    RAILS_ENV: test
    DATABASE_URL: ***localhost:5432/rails_test
    USER_EMAIL: ***
    USER_PASSWORD: ***
    BASE_URL: ***
=================================================================
***
***
***
=================================================================

TimeoutError: page.fill: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('input[type="email"]')
============================================================

   at global-setup.ts:37

  35 |   } else {
  36 |     // New Google sign in form
> 37 |     await page.fill('input[type="email"]', userEmail)
     |                ^
  38 |     await page.locator('#identifierNext >> button').click()
  39 |     await page.fill('#password >> input[type="password"]', userPassword)
  40 |     await page.locator('button >> nth=1').click()

    at globalSetup (/home/runner/work/outdoor-heart-sutra/outdoor-heart-sutra/frontend/playwright/global-setup.ts:37:16)


Error: Process completed with exit code 1.
```
