### DISCUSSION TITLE
Unexpected cancellations when using job-level concurrency group and matrix

### DISCUSSION THREAD

**Discussion by jalaziz** [community/community#63579] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a workflow with a job that looks like:
```
  deploy_to_k8s:
    needs: [build_and_push_docker_image]
    concurrency: deploy-k8s-${{ inputs.environment }}
    strategy:
      matrix:
        chart: [chartA, chartB, chartB]
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      ...
```

When running this workflow, it occasionally fails due to cancellation with the message `Canceling since a higher priority waiting request for 'deploy-k8s-dev' exists`.

What has been troubling and confusing is that there are no other deployment jobs running when we see the cancellation.

After some experimentation, I realized that each matrix item is competing for the same concurrency group rather than the concurrency group "wrapping" the matrix jobs.

Changing the concurrency group to `concurrency: deploy-k8s-${{ inputs.environment }}-${{ matrix.chart }}` fixes the cancellations, but offers different semantics than what we'd like.

Is there any way to specify a job-level concurrency group with a matrix such that the job itself is prevented from concurrent runs across other workflow runs but not across matrix jobs?

**Comment by denpolischuk** [comment, marked as answer]
Hi @jalaziz 
I found your post while looking for a solution to pretty much the same problem that you have. 
What I discovered just recently is that if you 'wrap' your parallel matrix into a separate re-usable workflow and call it with concurrency tag from your parent workflow, then it'll work as you want it to - without attaching concurrency tag to parallel run under the matrix.
For example:
```yaml
# parent-workflow.yaml
name: Main workflow
on:
# ...
jobs:
...
  deploy_to_k8s:
    uses: jalaziz/repo-with-your-child-action/.github/workflows/deploy-to-k8s.yaml@master
    needs: [build_and_push_docker_image]
    concurrency: deploy-k8s-${{ inputs.environment }}
    with:
      environment: ${{ inputs.environment }}
      ...
```

```yaml
# deploy-to-k8s.yaml deployment workflow
name: Deploy to k8s
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
...
jobs:
  deploy_to_k8s:
    strategy:
      matrix:
        chart: [chartA, chartB, chartB]
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      ...
```
Make sure that you set concurrency inside parent workflow, while matrix settings should be defined in child re-usable job.
Hope that helps :+1:
