### DISCUSSION TITLE
Passing inputs with spaces only first word is recognised as environment variable

### DISCUSSION THREAD

**Discussion by mohit2152sharma** [community/community#63606] [Actions] [answered]
### Select Topic Area

Question

### Body

So I have a custom github action, in which I am passing input parameters. The issue I am facing is, if my input contains a space, while redefining it only first word is used. For example, I have this action [rewiser-gpt](https://github.com/mohit2152sharma/rewiser-gpt), this action takes an input variable `subject`. 

```yml
inputs:
  ......
  subject:
    description: "Email subject"
    required: false
    default: "Rewiser Email" 
  ........
runs:
  using: "composite"
  steps:
    - name: Send Rewiser mail
      run: |
        echo "exporting environment variables"
        .....
        export INPUT_SUBJECT=${{ inputs.subject }}
        echo $INPUT_SUBJECT
        ....
        pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
        python ${GITHUB_ACTION_PATH}/main.py
      shell: bash
```
And if for example, I pass a `subject` like `"Hello world"`, the environment variable `INPUT_SUBJECT` is assigned to `"Hello"` only and all the words after space are stripped away.

What's the fix for this issue?
