### DISCUSSION TITLE
Call composite actions with dynamic names in a workflow

### DISCUSSION THREAD

**Discussion by Prudvi-data** [community/community#63675] [Actions] [answered]
### Select Topic Area

Question

### Body

I have Github Workflow that run certain jobs for different repos using strategy matrix. In each matrix job I am trying to call a action from different repo that runs specific steps for the repo. However I am unable to achieve this while trying call action using ${{ matrix.repo }} expression. Is this unsupported or I am missing anything here, please suggest any good way to achieve this. Thanks

```
Test-Run:
    strategy:
      matrix:
        repo: ${{ REPOS_LIST }}
    runs-on: ubuntu-latest
    container:
      image: image_name
      env:
        LANG: en_US.utf8
    steps:
      - name: Setup  config
        run:  some steps
      - name: Call action
        uses: ${{ matrix.repo }}/.github/actions/some_action/action.yml
```

But somehow this fails with below error

```Unrecognized named-value: 'matrix'. Located at position 1 within expression: matrix.repo```

**Comment by nirav-gajera** [comment]
The error message "Unrecognized named-value: 'matrix'. Located at position 1 within expression: matrix.repo" indicates that the `matrix` variable is not supported in the `uses` step. The `uses` step is used to run an action from another repository, and the `matrix` variable is only available in the `jobs` step.

To fix this, you can use the `env` step to set the `repo` variable to the value of the `matrix.repo` variable. You can then use the `repo` variable in the `uses` step.

Here is an example of how you can fix this:

```
Test-Run:
    strategy:
      matrix:
        repo: ${{ REPOS_LIST }}
    runs-on: ubuntu-latest
    container:
      image: image_name
      env:
        LANG: en_US.utf8
        repo: ${{ matrix.repo }}
    steps:
      - name: Setup  config
        run:  some steps
      - name: Call action
        uses: ${{ env.repo }}/.github/actions/some_action/action.yml
```

**Comment by Prudvi-data** [comment]
Even using env throws the same error.

```Unrecognized named-value: 'env'. Located at position 1 within expression: env.REPO ```

**Reply by nirav-gajera** [reply]
try this: 

```
Test-Run:
    strategy:
      matrix:
        repo: ${{ REPOS_LIST }}
    runs-on: ubuntu-latest
    container:
      image: image_name
      env:
        LANG: en_US.utf8
    steps:
      - name: Setup  config
        run:  some steps
      - name: Call action
        uses: ${{ matrix.repo }}/.github/actions/some_action/action.yml@main
        with:
          repo: ${{ matrix.repo }}
```

**Reply by Prudvi-data** [reply]
No luck, seems like this syntax is not supported to call actions.

``` Unrecognized named-value: 'matrix'. Located at position 1 within expression: matrix.repo```

**Reply by nirav-gajera** [reply]
the last hope: 


```
Test-Run:
    strategy:
      matrix:
        repo: ${{ REPOS_LIST }}
    runs-on: ubuntu-latest
    container:
      image: image_name
      env:
        LANG: en_US.utf8
    steps:
      - name: Setup  config
        run:  some steps
      - name: Call action
        run: |
          echo "#!/bin/sh" >> action_script.sh
          echo "node ${{ matrix.repo }}/.github/actions/some_action/action.yml" >> action_script.sh
          echo "echo 'The repo is ${{ matrix.repo }}'" >> action_script.sh
          chmod +x action_script.sh
          cat action_script.sh
        shell: bash
      - name: Run action
        uses: actions/github-script@v3
        with:
          script: ./action_script.sh
```

**Reply by Prudvi-data** [reply]
github-script expects js and  github api calls only. I couldn't achieve my requirement with this. I will try and look for some other alternatives

**Reply by nirav-gajera** [reply]
you can refer this: https://github.com/seferov/pr-lint-action/issues/69
https://stackoverflow.com/questions/69493352/error-passing-secret-to-reusable-workflow
https://stackoverflow.com/questions/64670494/github-action-pass-environment-variable-to-into-action-using-powershell

**Comment by soumyamahunt** [comment, marked as answer]
`uses` expects the action name to be determined before running the action, so while running the action you can't specify dynamic action for `uses`. You have to wrap your dynamic invocation inside a composite action and invoke the composite action path from your job. That way you can adjust the content of the composite action just before the action is invoked. You can use something like this:

```yml
Test-Run:
    strategy:
      matrix:
        repo: ${{ REPOS_LIST }}
    runs-on: ubuntu-latest
    container:
      image: image_name
      env:
        DYNAMIC_ACTION: ./.dynamic-action
        LANG: en_US.utf8
    steps:
      - name: Setup  config
        run:  some steps

      - name: prepare composite action
        uses: actions/github-script@v6
        with:
          script: |
            const path = require('path');
            const fs = require('fs/promises');
            const dyn = '${{ env.DYNAMIC_ACTION }}';
            const action = {
              runs: {
                using: 'composite',
                steps: [
                  {
                    // clean up dynamically created action
                    name: 'Cleanup',
                    uses: `actions/github-script@${{ github.action_ref }}`,
                    with: {
                      script: `await io.rmRF('${dyn}')`
                    }
                  },
                  {
                    name: `Call action for ${{ matrix.repo }}`,
                    uses: `${{ matrix.repo }}/.github/actions/some_action/action.yml`
                  }
                ]
              }
            };
            const content = JSON.stringify(action);
            core.debug(`Writing action:\n${content}\n`);
            await io.mkdirP(dyn);
            await fs.writeFile(path.join(dyn, 'action.yml'), content);

      - name: Call wrapper action
        uses: ./.dynamic-action
```

I am using this approach currently to test github action branch [here](https://github.com/SwiftyLab/setup-swift/blob/86e007cef8044fb2f809e74b67071f5c3864a1e4/.github/workflows/main.yml#L240-L305).

**Comment by jenseng** [comment]
See also #27048

I ran into this same limitation awhile back and went with a similar approach as @soumyamahunt... I wrapped it in to a reusable action so that I could use it in various repos/scenarios. Give [`jenseng/dynamic-uses@v1`](https://github.com/marketplace/actions/dynamic-uses) a spin (or feel free to borrow/fork/adapt its [action.yml](https://github.com/jenseng/dynamic-uses/blob/main/action.yml))

Given a step like so:

```yaml
- uses: actions/setup-node@v3
  with:
    node-version: 18
```

If you want your `uses` to be dynamic you can do:

```yaml
- uses: jenseng/dynamic-uses@v1
  with:
    # now you can use expressions 🥳
    uses: actions/setup-node@${{ inputs.version }}
    # the `with` needs to be converted to a valid json string
    with: '{ "node-version": 18 }'
```
