### DISCUSSION TITLE
Unable to trigger the GitHub Actions' workflow from main branch

### DISCUSSION THREAD

**Discussion by ryanlyh25** [community/community#63673] [Actions]
I have set the .yml file to run on pull request on main branch. However, the triggered workflow only work from the branch that is merged to the main but not from the main branch. 

For my case, the workflow must be started from main branch since I set my AWS credential to only allow workflow from repo:main. Is there any way that I can trigger my workflow to work from main branch instead of the merging branch?

**Comment by nirav-gajera** [comment]
you can trigger your workflow to work from main branch instead of the merging branch by using the `on` property in your .yml file. The `on` property specifies the events that will trigger the workflow. In your case, you can set the `on` property to `pull_request` and `branch: main`. This will tell GitHub to trigger the workflow when a pull request is opened or merged to the main branch.

Here is an example of how you can set the `on` property in your .yml file:

```
name: My workflow

on:
  pull_request:
    branches:
      - main
```


You can also use the `workflow_dispatch` event to trigger your workflow from main branch. The `workflow_dispatch` event is a manual event that can be triggered by anyone. 

example:

```
name: My workflow

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - echo "This workflow is triggered from main branch."
```

**Reply by ryanlyh25** [reply]
I have already used on: pull_request in main branch but the action still work from the merging branch. 

Here is my code:

```
name: sst_CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
env:
  AWS_REGION: <region> #Change to reflect your Region

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  sst-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: using node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: <role> #change to reflect your IAM role’s ARN
          role-session-name: <OIDC>
          aws-region: <region>
  
      <actions>

```

**Reply by nirav-gajera** [reply]
I see. The reason why your action is still working from the merging branch is because the `on` property in your .yml file is set to `pull_request` and `branches: main`. This means that the workflow will be triggered when a pull request is opened or merged to the main branch. However, the workflow will also be triggered when a pull request is merged to any other branch.

To fix this, you can specify the `source` property in your .yml file. The `source` property specifies the branch that the workflow will be triggered from. In your case, you can set the `source` property to `main`. This will tell GitHub to only trigger the workflow when a pull request is merged to the main branch.


```
name: sst_CI
on:
  pull_request:
    branches:
      - main
    source: main
env:
  AWS_REGION: <region> #Change to reflect your Region

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  sst-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: using node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: <role> #change to reflect your IAM role’s ARN
          role-session-name: <OIDC>
          aws-region: <region>
  
      <actions>
```

**Reply by ryanlyh25** [reply]
Is there any document page about the attribute "source"? It seems that "source" is not found as an attribute in the .yml .

**Reply by nirav-gajera** [reply]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

**Reply by ryanlyh25** [reply]
I have found the problem and on : push should be used in this case. For the .yml, there is no merge trigger and will use the main branch when pull_request trigger is used that the merging branch will be the active one and the workflow will be active from the merging branch. For this case, the merging must active the push function and using the push trigger will run the workflow from main.
More info can be found in https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged.
Thanks for your reply anyway.

```
name: sst_CI
on:
  push:
    branches:
      - main
env:
  AWS_REGION: <region> #Change to reflect your Region

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  sst-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: using node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: <role> #change to reflect your IAM role’s ARN
          role-session-name: <OIDC>
          aws-region: <region>
  
      <actions>

```
