### DISCUSSION TITLE
curl returns 28 error code: a connection timeout after trying to connect to specific IP during tests

### DISCUSSION THREAD

**Discussion by didix16** [community/community#63700] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi,

I'm using github actions to run tests after pushing the code repository. There are 2 tests that needs to connect to specific API IP using PHP curl functions but after a period of 10 seconds I receive a connection time out (curl error 28) and thus makes the test to fail. On my local machine the connection works. So I supose Github has some kind of firewall or something that is blocking the connection.

Is there any way to instruct the workflow of github actions that allows to connect to a blocked connection or something?

Any help should be apreciated. Thanks

**Comment by nirav-gajera** [comment, marked as answer]
yeah,  there is a way to instruct the workflow of GitHub Actions to allow you to connect to a blocked connection. You can do this by setting the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. These environment variables specify the proxy servers that GitHub Actions should use to connect to the internet.

To set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables, example of how to set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables:

```
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set proxy
        run: |
          echo "HTTP_PROXY=http://10.10.10.10:3128" >> $GITHUB_ENV
          echo "HTTPS_PROXY=http://10.10.10.10:3128" >> $GITHUB_ENV
      - uses: actions/setup-php@v2
      - name: Install curl
        run: |
          apt-get update
          apt-get install -y curl
      - name: Run test
        run: |
          curl -v https://www.google.com
```

In this example, the `HTTP_PROXY` and `HTTPS_PROXY` environment variables are set to `http://10.10.10.10:3128`. This means that GitHub Actions will use the proxy server at `10.10.10.10:3128` to connect to the internet.

Once you have set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables, the tests in your workflow should be able to connect to the blocked connection.
