### DISCUSSION TITLE
Progress bar on all Jobs

### DISCUSSION THREAD

**Discussion by danm** [community/community#63705] [Actions]
### Select Topic Area

Product Feedback

### Body

Hi there, we saw the screenshot of using the Actions Job progress bar to see progress through a job. This only seems to be available when using `environment` in a deployment-style job, but it would be great to have it as an option for all Jobs.

```
jobs:
  build:
    name: build files
    runs-on: [self-hosted, linux, x64]
    progress-bar: true
    steps: ...
```

![image](https://github.com/community/community/assets/6394846/0d6e0895-9ea9-4dd7-933e-8f6ba7cbec27)
