### DISCUSSION TITLE
Is it possible to evaluate `permissions` after `if`?

### DISCUSSION THREAD

**Discussion by git-developer** [community/community#63736] [Actions] [answered]
### Select Topic Area

Question

### Body

Consider the following simplified use case:

```console
$ cat .github/workflows/trigger.yml
```
```yaml
name: Trigger
on:
  workflow_dispatch:

jobs:
  job:
    uses: ./.github/workflows/deploy.yml
    with:
      registry: dockerhub
```

```console
$ cat .github/workflows/deploy.yml
```
```yaml
on:
  workflow_call:
    inputs:
      registry:
        type: string

jobs:
  ghcr:
    if: inputs.registry == 'ghcr'
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to GHCR
  dockerhub:
    if: inputs.registry != 'ghcr'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to Docker Hub
```

Running the workflow _Trigger_ results in an [error message](https://github.com/git-developer/gh-demo/actions/runs/5859128353/workflow):
> `The workflow is not valid. .github/workflows/trigger.yml (Line: 6, Col: 3): Error calling workflow 'git-developer/gh-demo/.github/workflows/deploy.yml@64c5038ded77419ad18a47a2d71093abe8cf8a9b'. The nested job 'ghcr' is requesting 'packages: write', but is only allowed 'packages: read'.`

I didn't expect this because the condition for job `ghcr` is not satisfied. I didn't find anything about this behavior in the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif). Is there a specific reason for this behavor, or is it a bug?

**Comment by git-developer** [comment]
The problem does not occur when workflow permissions are changed from default ("Read repository contents and packages permissions") to read/write in the repository settings. So apparently the [permission elevation of the `GITHUB_TOKEN`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job) seems not to work in combination with `if`.

**Comment by git-developer** [comment]
GitHub Support pointed out that it makes a difference whether permissions are defined in the calling workflow or the called workflow.

When defined in the caller workflow (`trigger.yml` in the example above), the `permissions` entry _defines_ the permissions granted for the workflow (including all called workflows). These permissions override the default "Workflow permissions" configured in the repository settings. When defined in a called workflow (`deploy.yml` in the example above), it _restricts_ the permissions from the caller. It is not possible to elevate permissions in a called workflow.

Albeit that, the following trigger workflow fails when run with default inputs:
```yaml
name: Trigger
on:
  workflow_dispatch:
    inputs:
      registry:
        type: string
        default: dockerhub

jobs:
  ghcr:
    if: inputs.registry == 'ghcr'
    permissions:
      packages: write
    uses: ./.github/workflows/deploy.yml
    with:
      registry: ${{ inputs.registry }}

  dockerhub:
    if: inputs.registry != 'ghcr'
    uses: ./.github/workflows/deploy.yml
    with:
      registry: ${{ inputs.registry }}
```

Error message:
> **Invalid workflow file:** .github/workflows/trigger.yml#L18
> `The workflow is not valid. .github/workflows/trigger.yml (Line: 18, Col: 3): Error calling workflow 'git-developer/gh-demo/.github/workflows/deploy.yml@fdf28d525c496dfbcb1044537b167ef9678700ca'. The nested job 'ghcr' is requesting 'packages: write', but is only allowed 'packages: read'.`
