### DISCUSSION TITLE
Workflow run status is `canceled` when fail-fasting a matrix of reusable workflows

### DISCUSSION THREAD

**Discussion by p0deje** [community/community#63860] [Actions]
### Select Topic Area

Bug

### Body

When a matrix strategy with `fail-fast: true` is used for a single job and one of the jobs fails, the whole workflow run is also marked as failed. For example, the following workflow simple workflow where `failure` aborts the `slow` job:

<details>
<summary>Code</summary>

```yaml
# .github/workflows/rc.yml
name: RC
on: push

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        include:
          - job: success
            run: exit 0
          - job: slow
            run: sleep 60
          - job: failure
            run: exit 1
    runs-on: ubuntu-latest
    steps:
      - run: ${{ matrix.run }}
```
</details>

<details>
<summary>Screenshot</summary>
<img width="874" alt="Screenshot 2023-08-14 at 09 45 37" src="https://github.com/community/community/assets/665846/3b099abc-eb3a-418b-a7d7-69cbf6a2d8b1">
</details>

However, when the similar pattern is used to run reusable workflows and one of them aborts the build, the workflow run status is `canceled`, not `failed`:

<details>
<summary>Code</summary>

```yaml
# .github/workflows/test.yml
name: Test
on:
  workflow_call:
    inputs:
      run:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ inputs.run }}
```

```yaml
# github/workflows/rc.yml
name: RC
on: push

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        include:
          - job: success
            run: exit 0
          - job: slow
            run: sleep 60
          - job: failure
            run: exit 1
    uses: ./.github/workflows/test.yml
    with:
      run: ${{ matrix.run }}
```
</details>

<details>
<summary>Screenshot</summary>
<img width="824" alt="Screenshot 2023-08-14 at 09 42 41" src="https://github.com/community/community/assets/665846/f6a2430c-5761-4c20-9e37-1c7e76a5452b">
</details>

I would expect the matrix `fail-fast` to mark the workflow run `failed` in both scenarios.

**Comment by nbr** [comment]
I am curious whether the individual matrix jobs within the reusable workflow exhibit a race condition when attempting to set the status of the `test` job, consequently affecting the status of the caller workflow.

Adding the specific error annotation tied to all matrix jobs when the workflow status is cancelled. (this doesn't appear to be logged from https://github.com/actions/runner):
> FailFast: cancelling since parallel instance has failed

Here is an example of this in the wild; the same scheduled workflow appears to variably have a `failure` or `cancelled` status when the `SdkRuntimeAutomation (python) / build` jobs fails.
- [Failed](https://github.com/microsoft/Oryx/actions/workflows/automationTrigger.yaml?query=is%3Afailure)
- [Cancelled](https://github.com/microsoft/Oryx/actions/workflows/automationTrigger.yaml?query=is%3Acancelled)

**Comment by johannesnormannjensen** [comment]
> ### Select Topic Area
> Bug
> 
> ### Body
> When a matrix strategy with `fail-fast: true` is used for a single job and one of the jobs fails, the whole workflow run is also marked as failed. For example, the following workflow simple workflow where `failure` aborts the `slow` job:
> 
> Code
> Screenshot
> However, when the similar pattern is used to run reusable workflows and one of them aborts the build, the workflow run status is `canceled`, not `failed`:
> 
> Code
> Screenshot
> I would expect the matrix `fail-fast` to mark the workflow run `failed` in both scenarios.

We are experiencing the same thing and it's quite frustrating. This is as mentioned only when using reusable workflows

**Comment by MaximeLaurenty** [comment]
We are experiencing the same issue with an additional twist: when fail-fasting a matrix of reusable workflows, neither `failure()` nor `cancelled()` are triggered, which is quite painful as we have no way to be alerted when our pipeline stops on main (except removing fail-fast) : 
![Screenshot 2024-04-12 at 19 15 14](https://github.com/community/community/assets/13254296/38b455a3-14f0-4940-a5fd-bc43aa48b7ca)

Cancelling manually the workflow in the UI triggers `cancelled()` correctly, and using a matrix without reusable workflows triggers `failure()` correctly as well.

As noted above by nbr, finding the origin of the `FailFast: cancelling since parallel instance has failed` message when using a reusable workflow (which differs from the `The job was canceled because "failure_exit_1" failed.` message when defining the action directly in the file) may help fixing this, but I couldn't find where this is coming from.

<details> 
<summary>Code</summary>

```yaml
# .github/workflows/test_parallel_failure.yml
name: Test parallel cancellation not triggering cancelled()

on:
  push:

jobs:
  parallel-run-and-fail:
    strategy:
      fail-fast: true
      matrix:
        include:
          - job: success
            run: exit 0
          - job: slow
            run: sleep 30
          - job: failure
            run: exit 1
    uses: ./.github/workflows/test.yml
    with:
      run: ${{ matrix.run }}
      name: ${{ matrix.job }} in workflow

  some-success:
    runs-on: ubuntu-latest
    steps:
      - name: Simple success
        run: echo 'simple success'

  action-on-failure:
    if: (failure() || cancelled())
    needs:
      - some-success
      - parallel-run-and-fail
    runs-on: ubuntu-latest
    steps:
      - name: Whatever action
        run: echo "triggered as expected"
```

```yaml
# .github/workflows/test.yml
name: Reusable workflow
on:
  workflow_call:
    inputs:
      run:
        type: string
      name:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ inputs.run }}
        name: ${{ inputs.name }}
```
</details>
