### DISCUSSION TITLE
How do you include a file with a reusable workflow?

### DISCUSSION THREAD

**Discussion by kthompson** [community/community#63863] [Actions]
### Reusable Workflows
General

### Body

Given a file structure like below:

```
calleerepo/
calleerepo/.github/workflows/myworkflow.yaml
calleerepo/.github/workflows/script.js

callerrepo/.github/workflows/default.yaml
```

And
* `callerrepo/.github/workflows/default.yaml` calls the reusable workflow `calleerepo/.github/workflows/myworkflow.yaml`
* `calleerepo/.github/workflows/myworkflow.yaml` depends on `calleerepo/.github/workflows/script.js`

When `myworkflow.yaml` is called from `default.yaml` it says that the dependent file `script.js` isnt found.

Is there special handling for how `myworkflow.yaml` should reference `script.js`? Currently it cannot detect the existence of  `script.js`.

**Comment by nirav-gajera** [comment]
Yes, there is special handling for how `myworkflow.yaml` should reference `script.js`. When you call a reusable workflow, GitHub Actions will copy the contents of the workflow file to the current working directory. This means that the `script.js` file will not be available in the current working directory unless you explicitly reference it.

To reference the `script.js` file, you can use the `uses` keyword. The `uses` keyword allows you to import a workflow file from another repository. In your case, you would use the following syntax:

```
uses: calleerepo/.github/workflows/script.js@main
```

The `@main` part of the syntax specifies the branch of the repository that the workflow file is located in. In this case, the workflow file is located in the `main` branch of the `calleerepo` repository.

Once you have referenced the `script.js` file, it will be available in the current working directory and you can use it in your workflow.

Here is an example of how you can call the `myworkflow.yaml` workflow from the `default.yaml` workflow:

```
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: calleerepo/.github/workflows/myworkflow.yaml@main
```

In this example, the `myworkflow.yaml` workflow is called from the `build` job. The `myworkflow.yaml` workflow will be copied to the current working directory and the `script.js` file will be available.

**Reply by kthompson** [reply]
Thanks for the reply. I finally got around to testing this out but I don't quite understand where I would put the `uses:` specifier in the callee workflow. If i put it under steps I get an error indicating that it must be at the job level. If I put it at the job level, I get a different error `invalid value workflow reference: workflow file should have either a '.yml' or '.yaml' file extension`. It doesn't seem to like it at the top level either so maybe I am missing something?

**Reply by sudhakarinka** [reply]
@nirav-gajera ,
 are you sure this works or should one use actions/GitHub-script.

Repo1  onPR--> repo2-->Workflow that  invoke another reusable workflow(eorkfl9w_call) and typescript task.

**Comment by marcransome** [comment]
@kthompson What you're trying to achieve doesn't appear to be documented anywhere. Having said that, you can clone the repository containing the reusable workflow and associated files in its own step, thereby making the files available to subsequent steps in the workflow:

For example, given a repository named `calling-workflow-repo` with the following structure:

```ascii
.github/
└── workflows/
    └── calling-workflow.yml
```

And given a separate repository named `called-workflow-repo`, containing a reusable workflow named `called-workflow.yml` and associated config file named `called-workflow-config.json`:

```
.github/
└── workflows/
    ├── called-workflow.yml
    └── called-workflow-config.json
```

To access the JSON config file from the reusable workflow—given that it executes in the context of the calling workflow—clone the repository first[^1]:

`called-workflow-repo/.github/workflows/called-workflow.yml`:

```yaml
name: called-workflow
on:
  workflow_call:
jobs:
  called-workflow-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: '<owner>/called-workflow-repo'
        path: 'called-workflow-repo'
        ref: 'main'
    - name: Print config file
      run: |
        cat called-workflow-repo/.github/workflows/called-workflow-config.json
```

The `path` value used with the the `actions/checkout` action is relative to the `$GITHUB_WORKSPACE` environment variable (or `github.workspace`). Since this is also the default working directory, you can refer to the config file using a relative path in subsequent steps (e.g. `called-workflow-repo/<path>`) without the need to prefix it with `$GITHUB_WORKSPACE/`, as seen in the `Print config file` step.

The calling workflow can be written simply as:

`calling-workflow-repo/.github/workflows/calling-workflow.yml`:

```yaml
name: calling-workflow
on:
  workflow_dispatch:
jobs:
  calling-workflow-job:
    uses: <owner>/called-workflow-repo/.github/workflows/called-workflow.yml@main
```

[^1]: For simplicity sake, it is assumed that all content in the `called-workflow-repo` resides on the `main` branch, and this is the branch named as the `ref` value in the `actions/checkout` action. Consider scenarios where the `actions/checkout` ref and calling workflow `uses:` ref may differ. It isn't currently possibly to determine the ref of the called workflow within the workflow (see #18602).
