### DISCUSSION TITLE
Actions do not queue

### DISCUSSION THREAD

**Discussion by misamu** [community/community#63930] [Actions] [answered]
### Select Topic Area

Bug

### Body

I created an Actions workflow to a repository under one of the organizations I am in and it has two triggers:
```
on:
  push:
  workflow_dispatch:
```
When I pushed that `.github/workflows/depcheck.yml` nothing happened. Then I tried to trigger dispatch from the web and from the console and got "Workflow run was successfully requested.", but still nothing happened and there is no queued workflow.

I created a second workflow, but with this, I also got the same result and nothing happened.
```
name: hello-world

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: test-step
        run: echo "Hello World!"
```

I have a personal organization where I tried the same actions and there those queues and run without any problems. Settings between those two organizations are exactly the same.

My last attempt was to create a new repository under the organization where Actions does not work and even with this new one the problem persists.
