### DISCUSSION TITLE
actions/cache matrix cache key collision

### DISCUSSION THREAD

**Discussion by tateexon** [community/community#63953] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a workflow that uses a matrix to run many different go tests, we split them up into a matrix to split tests out that can't run in parallel normally can run in parallel in CI to reduce CI run time. All these tests use the same go modules so caching them under the same key makes sense and since there are so many at this point that if I use a unique one for each matrix job I will be well over the 10gb cache limit. The cache restore works fine for the jobs but the post run cache when there are changes is where the problems occur. Since all of the matrix jobs are trying to write to the same cache name only the first to try wins and gets the file lock while all the others waste time building the cache only to fail when trying to secure the file lock. Is there a better way to handle this use case or could this be considered a bug in the actions/cache?

```
jobs:
  smoke-tests-matrix:
    environment: integration
    needs: [build, changes, build-test-image]
    strategy:
      fail-fast: false
      matrix:
        product:
          - name: testRun1
          - name: testRun2
          - name: testRun3
          - ...many more
    runs-on: ubuntu latest
    name: Integration Tests ${{ matrix.product.name }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.5.3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
           go-version-file: ./go.mod
           check-latest: true
      - name: Cache Vendor Packages
        uses: actions/cache@v3
        id: cache-packages
        with:
           path: |
             ~/.cache/go-build
             ~/go/pkg/mod
             ~/go/bin
           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
           restore-keys: |
             ${{ runner.os }}-go-
      - name: Run Go tests ...
```

**Comment by spenserblack** [comment]
Personally, I wouldn't consider this a bug in actions/cache. There might be better ways to handle this, but off the top of my head you could identify a "base" run that runs tests and performs caching, and then make the rest of the tests in the matrix depend on that run.

For example:
```yaml
jobs:
  base:
    # I always save the cache if the key changes
    name: Initial Job
    steps:
      - uses: actions/cache@v3
        with:
          path: my-cached-stuff
  matrix-tests:
    # I wait for base to release the cache lock, then get the cached files
    needs: base
    name: Test ${{ matrix.thing }}
    strategy:
      matrix:
        thing: [bar, baz]
    steps:
      - uses: actions/cache@v3
        with:
          path: my-cached-stuff
```
