### DISCUSSION TITLE
Set commit sha associated to manual run

### DISCUSSION THREAD

**Discussion by miguelb-gk** [community/community#63961] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a manual action which takes in a commit sha as an input to build. The code builds correctly and we checkout the correct sha based on the user input. However, the deployment and commit sha shown in the UI always uses the latest commit sha. How can I override this to passed in the commit sha to the deployment and in the run overview screen? 

Thanks

**Comment by FreeZe5K** [comment]
Sounds like you already have the input commit sha and check it out correctly, I'm going to write an example of the same logic to roll with so you can follow along easier for the additional steps.

Given the input sha:

```yaml
inputs:
  commit_sha:
    description: 'Commit SHA to checkout and deploy'
    required: true
```

and checking that sha out:

```yaml
- name: Checkout code
  uses: actions/checkout@v2
  with:
    ref: ${{ github.event.inputs.commit_sha }}
```

you need to set the action's env variable. This will allow you to reference the commit sha later on:

```yaml
- name: Set SHA as env variable
  run: echo "COMMIT_SHA=${{ github.event.inputs.commit_sha }}" >> $GITHUB_ENV
```

so now instead of referencing the default commit sha, you can use the environment variable you set:

```bash
echo $COMMIT_SHA
```

There isn't a direct way to override the commit SHA displayed in the GitHub Actions UI as it is automatically generated based on the triggering event. However, consider adding a step at the beginning of your action that displays the commit SHA being used:

```yaml
- name: Displaying the used commit SHA
  run: echo "Deploying commit SHA: $COMMIT_SHA"
```

Hope this points you in the right direction!

**Reply by miguelb-gk** [reply]
@FreeZe5K This is what we have. However the deployment in the deployment history and the manual action overview, where it shows "Manually triggered n days ago..." show the latest sha when the run ran. It doesn't show the sha we have checked out based on the input.

**Reply by FreeZe5K** [reply]
You can't change the "Manually triggered n days ago..." message, but how about setting a more descriptive job name to make this less confusing?

```yaml
jobs:
  deploy:
    name: Deploy Commit ${{ github.event.inputs.commit_sha }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.commit_sha }}
```

Alternatively, you could set a custom deployment status. If you are using the GitHub Deployments API to register deployments, make sure when you create or update a deployment status, you use the desired commit SHA. When creating or updating a deployment through the API, you can specify the ref that you're deploying. Ensure that this ref is the SHA you've checked out, not the default SHA of the workflow context.

**Reply by miguelb-gk** [reply]
@FreeZe5K We aren't setting it through API, the deployment is automatically being set because we specify the environment. 
I'm attaching some screenshots to illustrate the issue. 
- Screenshot 1: I launched a manual task for our "staging" environment for an old commit

![Screenshot 1](https://github.com/community/community/assets/127885590/0cfee525-8286-465c-a94a-d1fbd414f0b1)

- Screenshot 2: The run overview shows the latest commit sha

![Screenshot 2](https://github.com/community/community/assets/127885590/d3cdb349-69e8-4482-9757-69ab412db379)

- Screenshot 3: The deployment history screen shows the latest commit sha

![Screenshot 3](https://github.com/community/community/assets/127885590/f841f36f-7b83-43a7-ad7a-e194fbdbe649)

We have the code you illustrated above, but not sure how to associate the "run" to that specific commit and not just the code checkout.

**Reply by FreeZe5K** [reply, marked as answer]
Got it, I misunderstood with my original comment. When you define an environment in a job, GitHub automatically creates a deployment event using the current workflow's context (i.e., the commit from which the workflow was triggered), even if you checkout a different commit within the job. That's why you're seeing the latest commit SHA in the deployment history and the run overview. To associate the "run" to the specific commit, you would have to manually handle the deployment process instead of relying on the built-in environment mechanism.

Here's how you'd do that:

1) Remove the environment keyword from your job to prevent automatic deployment events.

2) Manually create a deployment using gh CLI or GitHub API. This gives you control over the SHA that's associated with the deployment. Here's a simplified example using the gh CLI:

```yaml
- name: Create deployment
  run: |
    gh api repos/miguelb-gk/:repo/deployments -f ref=${{ github.event.inputs.commit_sha }} -f environment=staging
```

3) Handle deployment in your workflow as usual, using the specified commit SHA.

4) Update the deployment status using the gh CLI or GitHub API after the deployment completes:

```yaml
- name: Update deployment status
  run: |
    # This is just a simplified example; you'll need to update with the appropriate status and other necessary information.
    gh api repos/miguelb-gk/:repo/deployments/:deployment_id/statuses -f state=success
```

By manually creating and updating the deployment, you have full control over the associated commit SHA, and it should correctly reflect in the deployment history. Doing it this way though, you might lose some of the built-in benefits of using the environment keyword in GitHub Actions, like automatic protection rules.
