### DISCUSSION TITLE
Merge queue checks don't report status back

### DISCUSSION THREAD

**Discussion by guy-saban-ws** [community/community#64027] [Actions]
### Select Topic Area

Bug

### Body

I have 2 jobs that are marked as required checks, each one is triggered based on the event

```
jobs:
  RunRegression:
    name: Run regression
    if: github.event_name == 'merge_group'
    uses: ./.github/workflows/test_setup.yml
    with:
      category: "Regression"
      create_container: true

  RunSanity:
    name: Run sanity
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/test_setup.yml
    with:
      category: "Sanity"

```
`test_setup.yml` is a reusable workflow

```
on:
  workflow_call:
    inputs:
       ...

jobs:
  reusable_workflow_job:
    runs-on: linux_runner
    steps:
      ...
```

The first job is triggered as expected by the merge queue event, however it doesn't report the status back and the merge queue just hangs and get closed after an hour. How can I solve this?

**Comment by Its-Kaizen** [comment]
check this out

**Comment by nirav-gajera** [comment]
The reason why the merge queue is hanging and getting closed after an hour is because the first job, `RunRegression`, is not reporting its status back. This means that the merge queue is not able to determine whether the job has succeeded or failed, so it eventually times out and closes.

To solve this issue, you need to make sure that the first job is reporting its status back. You can do this by adding the following steps to the job:

```
- name: Report status
  uses: actions/github-status@v2
  with:
    status: ${{ job.status }}
    target_url: ${{ github.workspace }}/results.html
```

This will create a status check for the job and report its status back to GitHub. Once the status check is reported, the merge queue will be able to determine whether the job has succeeded or failed and will proceed accordingly.
