### DISCUSSION TITLE
Is it possible to run jobs within a container from a saved container image?

### DISCUSSION THREAD

**Discussion by yzhang-23** [community/community#64091] [Actions]
### Select Topic Area

Question

### Body

According to the documentation at https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container, one can run jobs in a container created from a pre-built docker image. However, it looks that this image must be pulled from some registry (correct?). I was wondering if it is possible to use a saved docker image (e. g., some .tar file) to create the container. I'm asking this because I want to create some large temporary images and then run jobs with them, but no need to push them into some registry. I also find it very difficult to remove an image once it is in some registry, so I'm trying not to push them into a registry. Any directions? Many thanks!

**Comment by christophercouch** [comment]
Hi @yzhang-23,

Yes, you're correct that the current GitHub Actions setup pulls container images from a registry. However, to directly use a saved .tar docker image, there's no built-in functionality. But you can work around it:

1. In your workflow, before your job, you can load the saved docker image using:

```
- name: Load saved image
  run: docker load < your-image-name.tar
```

2. Once loaded, you can reference this image as you would any other in the subsequent steps or jobs, since it's now available in your runner's local Docker cache.

Keep in mind, for this to work, your .tar file should be accessible within the GitHub Actions runner (e.g., checked into your repository or fetched from an external source).

I hope this helps!

**Comment by yzhang-23** [comment]
> Hi @yzhang-23,
> 
> Yes, you're correct that the current GitHub Actions setup pulls container images from a registry. However, to directly use a saved .tar docker image, there's no built-in functionality. But you can work around it:
> 
>     1. In your workflow, before your job, you can load the saved docker image using:
> 
> 
> ```
> - name: Load saved image
>   run: docker load < your-image-name.tar
> ```
> 
>     2. Once loaded, you can reference this image as you would any other in the subsequent steps or jobs, since it's now available in your runner's local Docker cache.
> 
> 
> Keep in mind, for this to work, your .tar file should be accessible within the GitHub Actions runner (e.g., checked into your repository or fetched from an external source).
> 
> I hope this helps!



> Hi @yzhang-23,
> 
> Yes, you're correct that the current GitHub Actions setup pulls container images from a registry. However, to directly use a saved .tar docker image, there's no built-in functionality. But you can work around it:
> 
>     1. In your workflow, before your job, you can load the saved docker image using:
> 
> 
> ```
> - name: Load saved image
>   run: docker load < your-image-name.tar
> ```
> 
>     2. Once loaded, you can reference this image as you would any other in the subsequent steps or jobs, since it's now available in your runner's local Docker cache.
> 
> 
> Keep in mind, for this to work, your .tar file should be accessible within the GitHub Actions runner (e.g., checked into your repository or fetched from an external source).
> 
> I hope this helps!

hi, Chris,
     Thank you very much for your directions! Just one more question about your workaround: after I load the saved image with the command "docker load < your-image-name.tar", how this image be accessible to the subsequent jobs, which are supposed to be running in different runners? I tried the following workflow but not working:

```
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: build and push a test image
        run: |
          cat <<EOF>> test.Dockerfile
          FROM ubuntu:20.04
          EOF
          docker build -t test-image:tmp -f test.Dockerfile .
          docker save -o /tmp/testimage.tar test-image:tmp
      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: testimage
          path: /tmp/testimage.tar

  load-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Download image from artifact
        uses: actions/download-artifact@v3
        with:
          name: testimage
          path: /tmp
      - name: Load saved image
        run: docker load < /tmp/testimage.tar

  test-run-in-container:
    runs-on: ubuntu-latest
    needs: load-image
    container:
      image: test-image:tmp
    steps:
      - name: test run
        run: echo "Test run successfully!"

```
In the last job, the image test-image:tmp could not be pulled for not finding it. I may not understand your suggestions correctly. Please point out the problem in my workflow. Thank you very much for your help!

**Reply by christophercouch** [reply]
Your workflow correctly saves and loads the Docker image as an artifact. However, the issue lies in the fact that each `runs-on` in a GitHub Actions workflow is a separate runner instance. When you load the Docker image in the `load-image` job, the subsequent job `test-run-in-container` can't access it because it's on a fresh instance.

To fix this:

1. Combine `load-image` and `test-run-in-container` into a single job. This ensures the loaded image is available for use within the same runner:
```
jobs:
  build-image:
    # ... (same as before)

  load-and-test:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Download image from artifact
        uses: actions/download-artifact@v3
        with:
          name: testimage
          path: /tmp
      - name: Load saved image
        run: docker load < /tmp/testimage.tar
      - name: test run in container
        run: |
          docker run --rm test-image:tmp echo "Test run successfully!"
```

By loading and then using the image immediately in the same runner instance, you avoid the problem of the image being inaccessible in subsequent jobs.
