### DISCUSSION TITLE
Output Environment Variable from Child Template

### DISCUSSION THREAD

**Discussion by delarooster** [community/community#64102] [Actions] [answered]
### Select Topic Area

Question

### Body

I have been making the conversion from Azure Pipelines to GitHub Actions and, for the most part, able to do pretty much what I need to (although I would *love* the ability to pass more complex objects natively, like `stepList`s and general `object`s!)  I digress.

I am attempting to pass a dynamically generated output from one job to another when using `workflow_dispatch` child templates. Currently have been reading documentation extensively and have yet to come up with a working solution.

Parent template:
```
name: Deploy Bicep

on: [push, workflow_dispatch]

jobs:
  jobA:
    uses: [...]/.github/workflows/deploy-bicep.yaml@main
    with:
        bicepTemplatePath: 'env/main.bicep'
        clientAffix: 'Test test 123'
        env: 'Ts'
        resourceGroup: 'rg-acr-test'
    secrets: inherit
  
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    defaults:
      run:
        shell: pwsh
    steps:
      - run: |
          Write-Host "ACR Name -> " ${{ needs.inputs.outputs.acrName }}
```

Child template:
```
name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      bicepTemplatePath:
        description: 'The path to the top-level bicep template, e.g. main.bicep'
        default: env/main.bicep
        type: string
      additionalBicepParameters:
        default: ''
        type: string
      clientAffix:
        required: true
        type: string
      env:
        default: Dv
        type: string
      resourceGroup:
        type: string
        required: true
      resourceGroupLocation:
        type: string
        default: 'eastus'
      variablesYamlPath:
        type: string
        default: './pipelines/variables.yaml'
      vmImage:
        type: string
        default: 'ubuntu-latest'

jobs:
  deploy-bicep:
    runs-on: ${{ inputs.vmImage }}
    defaults:
      run:
        shell: pwsh
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          # Credentials inherited from parent workflow
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Read YAML variables
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: yaml-data
        with:
          config: ${{ inputs.variablesYamlPath }}

      - run: |
          az account show
          az group create --name ${{ inputs.resourceGroup }} --location ${{ inputs.resourceGroupLocation }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH

      - run: |
          $inputValue = "${{ steps.current-time.outputs.time }}".Replace(":", "-")
          $keyValuePair = "currentTime=$inputValue"
          Set-Content -Path .env -Value $keyValuePair

      - name: Deploy Bicep Template
        id: bicep-deploy
        run: |
          $currentTime = (Get-Content -Path .env).Split("=")[1]

          az --version
          az deployment group create `
            --resource-group ${{ inputs.resourceGroup }} `
            --name azuredeploy-$($currentTime) `
            --template-file ${{ inputs.bicepTemplatePath }} `
            --parameters `
              clientAffix=${{ steps.yaml-data.outputs['clientAffix'] }} `
              env=${{ steps.yaml-data.outputs['env'] }} `
              projectAffix=${{ steps.yaml-data.outputs['projectAffix'] }} `
              ${{ inputs.additionalBicepParameters }}
      
      - name: 'Capture Bicep Outputs'
        id: bicep-outputs
        run: |
          $currentTime = (Get-Content -Path .env).Split("=")[1]
          Write-Host "Current time: $currentTime"
          $out = az deployment group show -g ${{ inputs.resourceGroup }} -n "azuredeploy-$($currentTime)" | convertfrom-json | foreach properties | foreach outputs
          if($out -ne $null)
          {
              $provisionOutputs = [PSCustomObject]@{}
              $out | Get-Member -MemberType NoteProperty | ForEach-Object {
                $name = $_.name
                $provisionOutputs | Add-Member -MemberType NoteProperty -Name $name -value $out.$name.value
                Write-Host "BICEP output key/value -> $($name): $($out.$name.value)"
                # first attempt: Write-Host "$($name)=$($out.$name.value)" >> "$env:GITHUB_ENV"
                # second attempt: Add-Content -Path $env:GITHUB_ENV -Value "$($name)=$($out.$name.value)"
                $keyValuePair = "$($name)=$($out.$name.value)"
                Set-Content -Path .env -Value $keyValuePair
              }
          }
          else {
              Write-Host "BICEP outputs are null"
          }
```

The last step in the child template "Deploy bicep" the task "Capture Bicep Outputs" I'm attempting to Write-Host (and Add-Content as my latest plea) to output the key/value pair to the pipeline variables for use in JobB `${{ needs.jobA.outputs.acrName }}` as this is a regular pattern I use for post-deployment steps for configuration, updates, etc after my IaC has been deployed.

I can't remember how many iterations of various tries of syntax I've attempted at this point but could use some assistance when it comes to dynamically generating these outputs for use by a later job in the workflow.  Suggestions?

Thanks,
Austin

**Comment by christophercouch** [comment]
Hello Austin,

It sounds like you want to pass dynamic outputs from a child template job to another job in the parent workflow. Here's a brief overview and suggested changes:

1. **Setting the Output:**

In your child template, within the "Capture Bicep Outputs" step, after generating and setting the desired values, you'll need to set the output for the step using the ::set-output command.
```
- name: 'Capture Bicep Outputs'
  id: bicep-outputs
  run: |
    ...
    echo "acrName=$($out.acrName.value)" >> "$GITHUB_ENV"
    echo "::set-output name=acrName::$($out.acrName.value)"
```

2. **Accessing the Output:**

In your parent template, you can access the output from jobA and use it in jobB:
```
- run: |
    Write-Host "ACR Name -> " ${{ needs.jobA.outputs.acrName }}
```

This approach should allow you to pass the output value from your child template job to the next job in the parent workflow.

Hope this helps!

**Reply by delarooster** [reply]
Thanks for the fast respond, @christophercouch.

Correct me if I'm wrong but I thought `set-output` [was being deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)?  
Is it still the recommended pattern to use this method?

**Reply by christophercouch** [reply]
Thank you for sharing the details from GitHub's changelog regarding the deprecation of save-state and set-output commands.

Based on the information provided, GitHub recognized the substantial use of these commands and postponed their removal. While they originally intended to fully disable these commands by 1st June 2023, they've chosen to delay this due to significant customer impact.

For authors and users affected by these deprecations, the recommended actions are as follows:

1. Self-hosted runners: Ensure that they are updated to version 2.297.0 or greater.
2. Action authors using the toolkit: Update the @actions/core package to v1.10.0 or higher to get the new saveState and setOutput functions.
3. Authors using save-state or set-output via stdout: It's recommended to switch to the new environment files.

To directly answer your question, considering the shared deprecation information, the updated method to set outputs in a workflow would look like:
```
- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

This method aligns with GitHub's latest practices and would be the recommended way to dynamically generate and pass outputs between jobs in a workflow.

**Reply by delarooster** [reply]
You would think so, that's been my trial thus far.  That recommendation simply provides an empty string in later references.
```
- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

Have you tested by using PowerShell Core and seen any difference in the syntax?  PS would be my preference but appears to have varying results.
During the step providing the outputs I have the value as expected:
`BICEP output key/value -> acrName: DvContosoAcr`

But then referencing in the next job: 
```
Run Write-Host "ACR Name -> " 
  Write-Host "ACR Name -> " 
  shell: /usr/bin/pwsh -command ". '{0}'"
ACR Name -> 
```

**Reply by christophercouch** [reply]
Hey @delarooster,

It seems you're facing issues with dynamically setting outputs in PowerShell. Here's a suggestion:

In the child template, instead of:
`echo "{name}={value}" >> $GITHUB_OUTPUT`

Try:
`echo "name=$($out.acrName.value)" | Out-File -Append $env:GITHUB_ENV`

Then, in the parent template, access it as you've been doing:
`Write-Host "ACR Name -> " ${{ needs.jobA.outputs.acrName }}`

Ensure your step has an ID and that the variable name (acrName in this case) matches across both templates.

Hope this resolves the issue!

**Reply by delarooster** [reply]
Unfortunately still not able to reproduce actual passing of these variables between steps, @christophercouch.
Even attempted to hard-code the output as I've seen in some documentation (which I'm trying to avoid, ultimately, because it'll only make creating these outputs dynamic even more challenging)

jobA task:
```
- name: 'Capture Bicep Outputs'
  id: bicep-outputs
  run: |
    $out = az deployment group show -g ${{ inputs.resourceGroup }} -n "azuredeploy-$GITHUB_RUN_ATTEMPT" | convertfrom-json | foreach properties | foreach outputs
    if($out -ne $null)
    {
        $provisionOutputs = [PSCustomObject]@{}
        $out | Get-Member -MemberType NoteProperty | ForEach-Object {
          $name = $_.name
          $provisionOutputs | Add-Member -MemberType NoteProperty -Name $name -value $out.$name.value
          Write-Host "BICEP output key/value -> $($name): $($out.$name.value)"
          echo "$($name)=$($out.$name.value)" | Out-File -Append $env:GITHUB_ENV
        }
    }
    else {
        Write-Host "BICEP outputs are null"
    }
outputs: 
acrName: ${{ steps.bicep-outputs.outputs.acrName }}
```
<img width="964" alt="image" src="https://github.com/community/community/assets/24897179/ae0ef1d9-307e-4ad4-a6cc-a6edc3b30e42">

Trying any number of associations and correlations to potentially extract the given key/value.
jobB: 
```
- run: |
          Write-Host "ACR Name -> " ${{ needs.jobA.outputs.acrName }}
          Write-Host "ACR Name -> " ${{ needs.jobA.bicep-outputs.outputs.acrName }}
          Write-Host "ACR Name -> " ${{ needs.bicep-outputs.outputs.acrName }}
```
<img width="714" alt="image" src="https://github.com/community/community/assets/24897179/60edf1b9-e196-4ed7-abe2-8f52f53a71e7">

**Comment by delarooster** [comment]
Ok I did a bit more of hard-coded testing this morning and came to the conclusion that this *does*, indeed, work, but only when both jobs are on the same plane:
```
jobs:
  jobA:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Hard-Coded Outputs
      id: bicep-outputs
      run: |
        echo "Hard-coded outputs:"
        echo "acrName=Blah123" | Out-File -Append $env:GITHUB_OUTPUT
    outputs: 
      acrName: ${{ steps.bicep-outputs.outputs.acrName }}
  
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    defaults:
      run:
        shell: pwsh
    steps:
      - run: |
          Write-Host "ACR Name -> " ${{ needs.jobA.outputs.acrName }}
```

---

But still, when jobA is calling a child template and needs the outputs to pass to a new job, is it even possible?

parent workflow:
```
jobs:
  jobA:
    uses: [...]/.github/workflows/deploy-bicep.yaml@main
  
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    defaults:
      run:
        shell: pwsh
    steps:
      - run: |
          Write-Host "ACR Name -> " ${{ needs.jobA.outputs.acrName }}
```

child workflow (called from jobA):
```
jobs:
  deploy-bicep:
    runs-on: ${{ inputs.vmImage }}
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Hard-Coded Outputs
        id: bicep-outputs
        run: |
          $outputs = "acrName=Blah123"
          echo "Hard-coded outputs: $outputs"
          echo $outputs | Out-File -Append $env:GITHUB_OUTPUT
    outputs: 
      acrName: ${{ steps.bicep-outputs.outputs.acrName }}
```

As many times before, the result from the second iteration of jobB is an empty string.

**Comment by iamazeem** [comment]
You need to configure [`on.workflow_call.outputs`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_calloutputs) to propagate output parameters from the "called" workflow in addition to job level `outputs` i.e. [`jobs.<job_id>.outputs`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs).

Also, see [using outputs from a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow) for more details.

**Comment by delarooster** [comment, marked as answer]
With the vast limitations of having to hard-code outputs from a child workflow to its parent, and then that parent workflow having to have hard-coded output references I ended up creating individual files in an `outputs/` folder and publishing the outputs folder to the artifact directory, such as the following:

```
- run: |
    Set-Content -Path bicep-outputs/$($name) -Value $($out.$name.value)

- uses: actions/upload-artifact@v3
        with:
          name: bicep-outputs
          path: bicep-outputs/
```
In which the second job in the calling workflow can easily download such artifact and read them whenever necessary.  Much more decoupled and manageable than the prescribed method of using "outputs" ->

```
steps:
      - uses: actions/download-artifact@v3
        with:
          name: bicep-outputs
          path: bicep-outputs
          
      - name: Display structure of downloaded files
        run: ls -R

      - run: |
          Write-Host "ACR Name -> " $(Get-Content -Path bicep-outputs/acrName)
```

Passing variables between jobs on the same plane appears just fine, but still, creating variables dynamically without specific references for consumption by later steps and jobs, no matter the plane of the workflow, seems to be a feature-miss from the fork of Azure Pipelines.  
Or perhaps intentional?  Either way thankfully the above works as expected.
