### DISCUSSION TITLE
feature request: custom text in auto-generated release notes template

### DISCUSSION THREAD

**Discussion by ilya-lesikov** [community/community#6417] [Other Feature Feedback, Questions, & Ideas] [answered]
Hello, saw your new [auto-generated release notes](https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/#introducing-auto-generated-release-notes), looks great.

There is one feature we still really missing: could you allow us to add custom text before/after release notes or, ideally, between the categories too?

We need it to add short installation instructions to Release pages and to provide alternative download links to the secure TUF-repo we maintain. This also might be used for things such as:
* Providing links (maybe with short installation instructions) to the other means of software distribution, like apt-repositories, container registries, npm repositories, etc.
* Adding short license notes, disclaimers, descriptions, instructions, links to docs, etc.

Could look something like this:
```yaml
# release.yml

changelog:
  categories:
    - title: Description
      content: |
        This is a description.
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Install
      content: |
        ### NPM
        ```
        npm install package@${{ github.ref }}
        ```
        
        ### Docker
        ```
        docker run -d package:${{ github.ref }}
        ````
```
