### DISCUSSION TITLE
github actions to publish maven artifact ends up with Unauthorized (401)

### DISCUSSION THREAD

**Discussion by MaheshBabu11** [community/community#64207] [Actions]
### Select Topic Area

Question

### Body

I have been trying to publish my maven package by it keeps erroring out due to authorization issue, I tried with the secrets.GITHUB_TOKEN and PAT with write access for packages.

This is my workflow file : 

```
name: Maven Package
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        packages: write
    steps:
    - uses: actions/checkout@v3
    - run: |
          git config user.name "GitHub Actions"
          git config user.email "git@github.com"
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}  # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Commit all changes before publishing
      run: |
        git add .
        git commit -m "added version changes"
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -V -B -X -Darguments="-DskipTests" release:clean release:prepare release:perform       
      env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          GITHUB_ACTOR : 'MaheshBabu11
```

Can anyone help me with this ?
All the code are available here : https://github.com/MaheshBabu11/Excel2DataMap

**Comment by MaheshBabu11** [comment]
Issue was resolved by support

**Reply by mrvamsidhar-ais** [reply]
how?

**Reply by MaheshBabu11** [reply]
this is the new action file  seemed to solve the issue

```
name: Maven Package
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        packages: write
    steps:
    - uses: actions/checkout@v3
    - run: |
          git config user.name "GitHub Actions"
          git config user.email "git@github.com"
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR : 'MaheshBabu11'
```
