### DISCUSSION TITLE
Event for triggering workflow when someone comments on a merged commit

### DISCUSSION THREAD

**Discussion by harshtrivedi134** [community/community#64229] [Actions]
### Select Topic Area

Question

### Body

I am planning to build a workflow A that checks whether a merged PR is approved by a specific group created in GitHub. Based on approval, I am going to trigger another workflow B. However, if approval is not obtained and someone from that group comments with a 🚢 emoji to the merged commit, I am planning to trigger workflow A again. Treating 🚢  as a secondary approval. 

What would be the workflow event that should be used in this case?

**Comment by ghost** [comment]
Use an issue_comment webhook. You can use that to check for that emoji.

**Comment by Jaber-Saed** [comment]
For your scenario, you can set up two workflows: one for the initial approval process (Workflow A) and another to respond to the 🚢 emoji comment (Workflow C). The triggering events you should use for each workflow would be as follows:

1. **Workflow A (Initial Approval Check)**:
   - Use the `pull_request` event with the `merged` action.
   - This will trigger Workflow A when a PR is merged.

2. **Workflow C (🚢 Emoji Secondary Approval)**:
   - Use the `issue_comment` event with the `created` action.
   - In the workflow YAML, you can add a condition to check if the comment contains the 🚢 emoji and if the commenter is a member of the specific group you're targeting.
   - If the condition is met, Workflow C can be triggered to re-run Workflow A.

Here's a basic example of how Workflow C might look in your workflow YAML:

```yaml
name: Secondary Approval

on:
  issue_comment:
    types:
      - created

jobs:
  check_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check for 🚢 emoji and commenter
        id: check_ship
        run: |
          if [[ ${{ github.event.comment.body }} == *":ship:"* ]] && [[ ${{ github.event.comment.user.login }} == "approved-group-member" ]]; then
            echo "🚢 Comment and user match the criteria"
            echo "::set-output name=approve::true"
          else
            echo "🚢 Comment or user don't match the criteria"
            echo "::set-output name=approve::false"
          fi

      - name: Trigger Workflow A
        if: steps.check_ship.outputs.approve == 'true'
        uses: actions/trigger-workflow@v2
        with:
          workflow: 'Workflow-A.yml'
          token: ${{ secrets.GITHUB_TOKEN }}
```

In this example, `approved-group-member` should be replaced with the actual username of the member in your approval group. Adjust the condition as needed to match the specifics of your setup.

Remember to replace `'Workflow-A.yml'` with the actual filename of your Workflow A YAML file.

By using this approach, you can achieve the behavior you described: triggering Workflow A when a PR is merged, and re-running Workflow A when a specific group member comments with the 🚢 emoji.
