### DISCUSSION TITLE
Push Jekyll site to specific branch after build

### DISCUSSION THREAD

**Discussion by asim-rehman** [community/community#64248] [Actions]
### Select Topic Area

Question

### Body

I have a Github build file for building a Jekyll site that i have
``` yml
name: Ruby

on:
  pull_request:
    branches: ["master"]
    types: [closed]

permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: build jekyll
      run: bundle exec jekyll build`
```

This builds my Jekyll site once i push into master and merge. However after build is complete I want to push the contents of the _site directory that the "bundle exec jekyll build" generates and push that into a **test** branch

This test branch will then be automatically be picked up by AWS Amplify via WebHooks. I am struggling to find out how to do this? I am on the free plan.

**Comment by Akash1134** [comment]
Hi @asim-rehman ,

To push the contents of the `_site` directory to a test branch after building your Jekyll site, you can add the following steps to your GitHub Actions workflow:

```yaml
name: Ruby

on:
  pull_request:
    branches: ["master"]
    types: [closed]

permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: build jekyll
      run: bundle exec jekyll build
    - name: Push to test branch
      uses: ad-m/github-push-action@master
      with:
        branch: test
        directory: ./_site
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

This workflow uses the `ad-m/github-push-action` action to push the contents of the `_site` directory to a test branch named `test`. The `directory` parameter specifies the directory to push, and the `github_token` parameter uses the built-in `GITHUB_TOKEN` secret to authenticate the push.

Once the contents of the `_site` directory are pushed to the `test` branch, AWS Amplify can pick up the changes via WebHooks.

I hope this helps! Let me know if you have any further questions.
