### DISCUSSION TITLE
feature proposal

### DISCUSSION THREAD

**Discussion by ghost** [community/community#64314] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

General

### Body

I want to see a function that can extract from a zip archive after uploading to a repository. If the entire repository is downloaded and zipped in a zip archive, then the archive will be extracted to the root of the repository after being uploaded to the newly created repository

**Comment by rifqifarhansyah** [comment]
If I understand correctly, you're looking for a way to automate the process of extracting a ZIP archive that's uploaded to a GitHub repository, and you want the extracted files to be placed at the root of the repository. GitHub itself doesn't provide built-in functionality for this specific task, but you can achieve this using GitHub Actions, which allows you to automate various tasks and workflows within your repository.

Here's a high-level overview of how you could set this up:

1. **Create a Workflow:**
   In your GitHub repository, navigate to the "Actions" tab and create a new workflow file (e.g., `.github/workflows/extract-zip.yml`).

2. **Define the Workflow:**
   Inside the workflow file, define the workflow configuration. You'll need to specify when the workflow should be triggered (e.g., when a ZIP archive is pushed to a certain branch), and the steps to perform.

   ```yaml
   name: Extract ZIP Archive

   on:
     push:
       paths:
         - '**.zip'

   jobs:
     extract:
       runs-on: ubuntu-latest

       steps:
         - name: Check out code
           uses: actions/checkout@v2

         - name: Extract ZIP Archive
           run: |
             unzip -q '*.zip'
             rm *.zip
             git add .
             git commit -m "Extracted ZIP archive"
             git push
   ```

3. **Workflow Explanation:**
   - The workflow is triggered on a push event when a ZIP archive is pushed to the repository.
   - The `actions/checkout` action checks out the repository's code into the runner environment.
   - The `unzip` command extracts the uploaded ZIP archive files.
   - The `rm` command removes the extracted ZIP archive.
   - The `git add`, `git commit`, and `git push` commands commit and push the changes (the extracted files) back to the repository.

4. **Configure and Test:**
   Make sure you adjust the workflow configuration to match your needs, including specifying the correct branch and file paths. After setting up the workflow, upload a ZIP archive to your repository and observe the automated extraction process.

Remember that GitHub Actions can execute custom scripts within the runner environment, so you can further customize the process if needed. Additionally, consider testing the workflow in a test repository before applying it to a production repository to ensure it works as intended.
