### DISCUSSION TITLE
(Unknown event) (Unnamed workflow) Error (again?)

### DISCUSSION THREAD

**Discussion by garydgregory** [community/community#64320] [Actions]
### Actions

This might the same as what happened in 2020: https://github.com/orgs/community/discussions/26457 ?

For example, in Apache Commons we have many like "[(Unknown event)](https://github.com/apache/commons-jcs/actions/runs/5908729945) (Unnamed workflow) #3: Scheduled"

- https://github.com/apache/commons-lang/actions/runs/5908752919
- https://github.com/apache/commons-codec/actions/runs/5911479880

**Comment by garydgregory** [comment]
See ok now. We (on the Apache side) has some email confirmation from GH to handle (or something to that effect).

**Comment by prashant-kumar-exa** [comment]
Do we have any solution for this issue?

**Comment by nimeshmaharjan1** [comment]
I hope its relevant here. The issue I am currently facing is I create a PR from my fork repo into the upstream repo what I wanted is the e2e tests to run after a preview deployment but from the fork PR it says unkown event

but it works for the branches in the upstream repo

I think I understand why this behaviour is occuring but is there a way to fix this?

![image](https://github.com/user-attachments/assets/606cced6-47f5-44bd-ae39-b20e02f3a697)

the below is my e2e.yml inside .github/workflows

```
# Using pnpm & Node v20
name: End-to-end testing

on:
  deployment_status:

jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    timeout-minutes: 60
    runs-on: ["self-hosted"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Log Deployment Status
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Deployment Status: ${{ github.event.deployment_status.state }}"
          echo "Deployment Environment: ${{ github.event.deployment_status.environment }}"
          echo "Deployment URL: ${{ github.event.deployment_status.environment_url }}"
          echo "Echoing successful deployment message."
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        env:
          NEXT_PUBLIC_APP_URL: ${{ github.event.deployment_status.environment_url }}
        run: pnpm exec playwright test

      - name: All test artifacts
        if: always()
        run: |
          mkdir -p test-artifacts
          cp -r playwright-report test-artifacts/
          cp -r test-results test-artifacts/

      - name: Upload combined test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-artifacts/
          retention-days: 30
```
