### DISCUSSION TITLE
Unable to let my action build download one of my github package

### DISCUSSION THREAD

**Discussion by mimir234** [community/community#64489] [Actions]
### Select Topic Area

Question

### Body

Hi everybody

I'm facing a pretty dumb issue I think, but i didn't find a way to fix it

I have two repos maven/java : 
- the first one is a library that is automatically built and deployed into github packages repository
- the second one is an application which has the first as a dependency

The problem that I'm facing is that my action build of my second repo failes to download the first repo package. 
The maven build has an 401 unauthorized  responses from github package repository.

I've tried to define the action build like the following : 

    - name: Build with Maven
      run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

but it doesn't fix the issue

I know that the fix should be very simple but I'm not able to find out the solution by myself. May you please indicate the apropriate way to do ?

**Comment by nirav-gajera** [comment]
try: 
```

name: Build with Maven
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
