### DISCUSSION TITLE
Why github.ref_name is empty?

### DISCUSSION THREAD

**Discussion by brunocalza** [community/community#64528] [Actions] [answered]
### Select Topic Area

Question

### Body

Suddenly my jobs started failing because `github.ref_name` is coming empty. 

The jobs are triggered when a new release is created. 

Here's the workflow code: https://github.com/tablelandnetwork/go-tableland/actions/runs/5927734903/workflow

**Comment by arafajs** [comment]
The github.ref_name context variable is only available when the workflow is triggered by a push event to a branch or tag. Since your workflow is triggered by a release creation event, the github.ref_name context variable will be empty.

To get the tag name in this case, you can use the GITHUB_REF context variable. The GITHUB_REF variable contains the full ref that triggered the workflow, including the branch or tag name.

For example, if the workflow is triggered by a release creation event for the tag v1.2.3, the GITHUB_REF variable will be set to refs/tags/v1.2.3.

You can then use the GITHUB_REF variable to get the tag name by removing the refs/tags/ prefix. For example:

`echo "Tag name: ${{ env.GITHUB_REF#refs/tags/ }}"`
This will print the tag name, which in this case is v1.2.3.

You can update your workflow to use the GITHUB_REF variable as follows:

```
on: release:
  types:
    - published

jobs:
  get_tag_name:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        run: echo "Tag name: ${{ env.GITHUB_REF#refs/tags/ }}"
```
This workflow will now print the tag name when a new release is created.
