### DISCUSSION TITLE
Issue Uploading Compressed Files as Assets in a Release

### DISCUSSION THREAD

**Discussion by sharklatan** [community/community#64554] [Actions]
### Select Topic Area

Question

### Body

Hello everyone,

I’m encountering an issue while attempting to upload compressed files as assets in a GitHub release. I’ve set up a GitHub Actions workflow that builds and publishes my .NET project. The workflow correctly generates compressed files (SharkGoFiles.zip and SharkGoFiles.tar.gz) within the publish folder of my repository.

However, when I try to attach these compressed files as assets to a release, the files don’t appear in the release’s asset section. I’ve verified that the files are generated correctly and that the path in the workflow configuration is properly set.

Here’s the relevant part of my workflow:

# My current workflow configuration

- name: Upload Release Artifact .NET 6.0 and Compressed Files
  uses: actions/upload-artifact@v2
  with:
    name: release-artifact-net6.0
    path: |
      ./publish/net6.0
      ./publish/SharkGoFiles.zip
      ./publish/SharkGoFiles.tar.gz

Has anyone else faced a similar issue or could provide guidance on how to troubleshoot this problem? I appreciate any help you can provide.

Thank you in advance!

**Comment by Kaysuto** [comment]
Hello!

The issue seems to be that the compressed files SharkGoFiles.zip and SharkGoFiles.tar.gz are not included in the artifact uploaded by the actions/upload-artifact action.

To fix this, you can use the actions/upload-release-asset action instead to directly upload the compressed files as release assets:

```
- name: Upload Release Assets
  uses: actions/upload-release-asset@v1
  env: 
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: |
      ./publish/SharkGoFiles.zip   
      ./publish/SharkGoFiles.tar.gz
    asset_name: |
      SharkGoFiles.zip
      SharkGoFiles.tar.gz
    asset_content_type: application/zip
```

Some key points:

The upload_url needs to be retrieved from a previous step of creating the release (using actions/create-release)
Specify the path to each compressed file in asset_path
Define the file name and content-type in asset_name and asset_content_type
With this configuration, the compressed files should be correctly uploaded and visible in the GitHub Release Assets section.

Let me know if you have any other questions! I'm happy to help explain further.

**Reply by sharklatan** [reply]
After reviewing, I realized it was the directory, and I finally fixed it. But it gave me another issue...

And that is that I want to use the same tag and keep updating new posts or edit the same one.

Could you help me solve it?
![image](https://github.com/community/community/assets/5210221/17c2cc27-d63f-47ff-ad3b-8281a1d4da50)


```
name: Build, Compress, and Publish

on:
  push:
    branches:
      - master

jobs:
  build-compress-publish-net6-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x' # Usa la versión apropiada

      - name: Build and Publish .NET 6.0
        run: |
          dotnet restore
          dotnet build --configuration Release --framework net6.0
          dotnet publish --configuration Release --framework net6.0 --output ./publish/net6.0

      - name: Compress Files
        run: |
          cd ./publish/net6.0
          Compress-Archive -Path Resources, runtimes, ICSharpCode.SharpZipLib.dll, iMobileDevice-net.dll, Newtonsoft.Json.dll, plist-cil.dll, SharkGo.deps.json, SharkGo.dll, SharkGo.exe, SharkGo.pdb, SharkGo.runtimeconfig.json -DestinationPath ../../SharkGoFiles.zip
          cd ../..

      - name: List files in publish directory
        run: ls -R ./publish/net6.0

      - name: Upload Release Artifact .NET 6.0 and Compressed Files
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact-net6.0
          path: |
            ./publish

      - name: Get Last Commit
        id: last_commit
        run: echo "::set-output name=commit::$(git log -1 --pretty=format:'%h - %s')"

      - name: Get Last Push Date
        id: last_push
        run: echo "::set-output name=push_date::$(git log -1 --pretty=format:'%cd' --date=short)'"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Beta # Define un nombre de etiqueta predeterminado (puedes cambiarlo)
          release_name: "Beta Release - ${{ steps.last_push.outputs.push_date }} - ${{ steps.last_commit.outputs.commit }}" # Establece el nombre del lanzamiento
          draft: false
          prerelease: true # Establece como versión preliminar

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SharkGoFiles.zip
          asset_name: SharkGoFiles.zip
          asset_content_type: application/zip

```

**Comment by Kaysuto** [comment]
Here is the solution to reuse the release tag using the full workflow YAML:


```
# Get ID of latest release
- name: Get Release ID
  id: get_release 
  uses: bruceadams/get-release@v1.2.2
  env:
    GITHUB_TOKEN: ${{ github.token }}

# Remove release creation step 
#- name: Create Release
# uses: actions/create-release@v1

# Upload assets to existing release
- name: Upload Release Asset
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release.outputs.id }}/assets{?name,label}
    asset_path: ./SharkGoFiles.zip
    asset_name: SharkGoFiles.zip
    asset_content_type: application/zip
    
# Check if assets changed
- name: Check for changes
  id: changes
  uses: trilom/file-changes-action@v1.2.4
  with:
    file_path: ./SharkGoFiles.zip

# Only upload if changed 
- name: Upload if changed
  if: steps.changes.outputs.any_changed == 'true'
  uses: actions/upload-release-asset@v1
  with:
    upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release.outputs.id }}/assets{?name,label}
    asset_path: ./SharkGoFiles.zip
```

This will upload the assets to the same release on each run. Let me know if you have any other questions!
