### DISCUSSION TITLE
Include description when rendering YAML-based form into Markdown

### DISCUSSION THREAD

**Discussion by funkypenguin** [community/community#6458] [Projects and Issues]
Hey guys,

In response to your request for feedback, I'd like to point out that it'd be helpful if the description from a YAML block was rendered in the final issue Markdown. For example..

```
  - type: checkboxes
    id: sanity_check
    attributes:
      label: 🤪 Sanity check
      description: Let's confirm that this is not a recipe which has previously been discussed / proposed
      options:
        - label: I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue) / [closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr) / [closed](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this recipe
          required: true       
        - label: I have confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)
          required: true
```

It'd be helpful if the final issue included the description text `Let's confirm that this is not a recipe which has previously been discussed / proposed`, because it adds context to the options the user has selected.

Cheers!
D
