### DISCUSSION TITLE
Setting PR status from workflow

### DISCUSSION THREAD

**Discussion by anero** [community/community#64657] [Actions]
### Select Topic Area

Question

### Body

We recently refactored our CI to split the work for building docker images and running tests and linters on the code. So we've an initial workflow (`Docker Image CI`) that runs on every push and builds the docker images, pushing to GHCR, and then a 2nd workflow that is triggered by the first one that runs the tests.

### Workflow building the docker image
```
name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
jobs:
  build:
  ...
```

### Workflow running the tests
```
name: Test Suite
run-name: 'Test: ${{ github.event.pull_request.head.label || github.event.head_commit.message }}'
on:
  workflow_run:
    workflows: [Docker Image CI]
    types:
      - completed
jobs:
  lint:
  ...
  rspec:
  ...
```

The problem with this is that after moving the test and linter jobs out of the initial workflow we lost the PR checks summary, and need to manually check if the last workflow run for the PR was successful before merging. I did some research but couldn't find any docs that explain how the PR checks are set by default from Actions; I assume this is done automatically via the [Checks API](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28). 

So my question is: do we need to manually implement calls to the checks API from our workflow, or use something like https://github.com/marketplace/actions/pull-request-status-action? Or is it possible to write the 2nd workflow in a way that it reports the status back to the PR so that the checks are correctly displayed?
