### DISCUSSION TITLE
Share file generated in one workflow with another called/child/reusable workflow

### DISCUSSION THREAD

**Discussion by pratiyush05** [community/community#64728] [Actions]
### Select Topic Area

Question

### Body

Hi 
I would like to know how can we share a file created in a workflow with another called/reusable/child workflow .

My Scenario -
Running git action on self-hosted runner .
Workflow_1.yaml - It has multiple jobs .One of the job has script which generates a yaml file . In next job, this workflow calls another Workflow_2.yaml . Used [link](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow:~:text=./.github/workflows/%7Bfilename%7D) as both workflows are in same repo .
Workflow_2.yaml - Uses that yaml file created in previous workflow .

Workflow_2 runs after success completion of workflow_1 .
Both are in same repo .

Since files are deleted after a workflow completion , how can I achieve this type of file sharing ??

**Comment by pratiyush05** [comment]
@Vapercut 
Adding worlfow files sudo code -
Worflow_1.yaml - 

```
on: push

job:
   build_11:
   steps:
      -
      - creates xxx.yaml file

   call-workflow-2:
    needs: build_11
    uses: ./.github/workflows/workflow_2.yaml
```


Workflow_2.yaml
```
on:
  workflow_call:
    inputs:
   
 job:
    build_21:
    steps:
      -
      - run: |
            cat xxx.yaml
```


I was expecting that connected workflows (caller and called worflows ) ran from starting till their end in a single folder when running on self-hosted runner . But [here](https://github.com/orgs/community/discussions/26174) I came to know that files are deleted after successful execution of a single workflow . So we cannot simply create files in one workflow and use it in another connected reusable workflow .
Please correct me wherever I am wrong .
