### DISCUSSION TITLE
github action triggered the unexpected workflow

### DISCUSSION THREAD

**Discussion by xgui3783** [community/community#64732] [Actions]
### Select Topic Area

Question

### Body

Dear all, 

It's my first time posting on here. Apologies if I have made any mistakes.

I have been staring at the triggered workflow https://github.com/FZJ-INM1-BDA/siibra-api/actions/runs/5950706305 and cannot make sense of a few things

- the flow is triggered by publish of tag [v0.3.12-rc5](https://github.com/FZJ-INM1-BDA/siibra-api/releases/tag/v0.3.12-rc5)
- (apologies as the workflow file is rather large), as the release ref contains the string `rc`, I had expected:
  - [deploy-rc-on-okd](https://github.com/FZJ-INM1-BDA/siibra-api/actions/runs/5950706305/workflow#L129-L141) to be run
```yml
  # snippet for convenience
  deploy-rc-on-okd:
    needs: setup-envvar
    if:  ${{ github.event_name == 'release' && contains(github.ref, 'rc') }}
    
    uses: ./.github/workflows/deploy-on-okd.yml
    with:
      okd_endpoint: https://okd.hbp.eu:443
      flavor: rc
      queues: ${{ needs.setup-envvar.outputs.queues }}
      version: ${{ needs.setup-envvar.outputs.version }}
      workerimage: docker-registry.ebrains.eu/siibra/siibra-api:rc-worker
    secrets:
      okd_token: ${{ secrets.OKD_PROD_SECRET }}
```

  - [deploy-rc-on-data-validation](https://github.com/FZJ-INM1-BDA/siibra-api/actions/runs/5950706305/workflow#L157-L170) to be run
```yml
  # snippet for convenience
  deploy-rc-on-data-validation:
    needs:
    - setup-envvar
    - data-validation-config-hash
    if: ${{ github.event_name == 'release' && contains(github.ref, 'rc') }}
    uses: ./.github/workflows/deploy-on-okd.yml
    with:
      okd_endpoint: https://okd.jsc.hbp.eu:443
      flavor: rc
      queues: ${{ needs.setup-envvar.outputs.queues }}
      version: c.${{ needs.data-validation-config-hash.outputs.CONFIG_SHORT_REV }}
      workerimage: docker-registry.ebrains.eu/siibra/siibra-api:rc-worker
    secrets:
      okd_token: ${{ secrets.OKD_JSC_SECRET }}
```
  - but [deploy-prod-on-okd](https://github.com/FZJ-INM1-BDA/siibra-api/actions/runs/5950706305/workflow#L172-L194) to be skipped

```yml
  # snippet
  deploy-prod-on-okd:
    needs: setup-envvar
    if:  ${{ github.event_name == 'release' && !contains(github.ref, 'rc') }}
    strategy:
      fail-fast: false
      matrix:
        deploy-site: ['jsc', 'cscs']
        include:
        - deploy-site: 'jsc'
          okd-endpoint: https://okd.jsc.hbp.eu:443

        - deploy-site: 'cscs'
          okd-endpoint: https://okd.hbp.eu:443
```
But the reality was the exact opposite. 

![Screenshot 2023-08-23 174549](https://github.com/community/community/assets/19381783/02a5219d-4760-47cb-b2e3-95497fa7a338)
Am I missing something?

Thanks in advance.

X
