### DISCUSSION TITLE
Missing sender information on workflow_dispatch event payload

### DISCUSSION THREAD

**Discussion by anero** [community/community#64776] [Actions]
### Select Topic Area

Bug

### Body

According to [docs](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch), the `workflow_dispatch` event's payload should include a `sender` field, but on my tests when manually triggering the workflow this field is empty.
I'm verifying this with a workflow like the one below:

```
name: User triggering the workflow
on:
  workflow_dispatch:
jobs:
  capture-event-payload:
    runs-on: ubuntu-22.04
    steps:
      - name: Print the Github event payload for debugging
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_SENDER: ${{ github.event.workflow_dispatch.sender }}
        run: |
          echo ${{ env.GITHUB_EVENT_NAME }}
          echo ${{ env.GITHUB_EVENT_SENDER }}
```

I confirmed that the event is `workflow_dispatch` with the first echo, but `GITHUB_EVENT_SENDER` is always empty. I've also tried using `github.event.workflow_dispatch.sender.id` based on [this question](https://github.com/orgs/community/discussions/27947), but that also fails.

My goal is to forbid users other than admins to manually trigger the action, I was hoping the `sender` would include a reference to the teams it belongs to, or their role.
