### DISCUSSION TITLE
${{ github.ref }} is empty on tagged build

### DISCUSSION THREAD

**Discussion by papadeltasierra** [community/community#64817] [Actions]
### Select Topic Area

Question

### Body

Is this a bug?  Here is my workflow snippet...
```
on:
  push:
    paths:
      <some paths here>
    branches:
      - '**'

jobs:
  BuildMe:
    runs-on: windows-latest
    name: Test build.
    steps:
        - uses: actions/checkout@v3

        - if: github.ref_type == 'tag'
          uses: ./actions/common/semver
          with:
            tag: ${{ github.ref }}
```
My action fails because the `tag` variable is always empty.  I have seen reports of this happening for release triggered builds recently but is this also affecting tag triggered builds or have I done something obviously wrong?

**Comment by papadeltasierra** [comment]
FYI it appears that `${{ github.ref_name }}` is correctly populated but why not `${{ github.ref }}`?

**Comment by arafajs** [comment]
Try to use `github.event.head_commit.ref` variable instead.

**Comment by arafajs** [comment]
Like this:

```
on:
  push:
    paths:
      <some paths here>
    branches:
      - '**'

jobs:
  BuildMe:
    runs-on: windows-latest
    name: Test build.
    steps:
        - uses: actions/checkout@v3

        - if: github.event_type == 'push'
          uses: ./actions/common/semver
          with:
            tag: ${{ github.event.head_commit.ref }}
```

**Comment by nirav-gajera** [comment]
yes,maybe this is a bug in the GitHub Actions workflow syntax. The github.ref variable is not populated for tag triggered builds. This is a known issue

-In the meantime, you can workaround this issue by using the github.event_name variable instead. The github.event_name variable will be set to "push" for tag triggered builds.

ex: 

```
on:
  push:
    paths:
      <some paths here>
    branches:
      - '**'

jobs:
  BuildMe:
    runs-on: windows-latest
    name: Test build.
    steps:
        - uses: actions/checkout@v3

        - if: github.event_name == 'push'
          uses: ./actions/common/semver
          with:
            tag: ${{ github.ref }}
```
