### DISCUSSION TITLE
Rust Cross-Compile Testing Fails with `File Does Not Contain a Valid CIL Image`

### DISCUSSION THREAD

**Discussion by magicaldave** [community/community#64826] [Actions]
I'm uncertain if this is a bug in the github runner itself or not, but I cannot reproduce this behavior anywhere except inside of GitHub itself. 

I have a relatively simple rust project in a private repository, using a github actions workflow to build and test it on windows and linux. The application compiles in both environments. Then, a cargo test is ran for both environments. The Linux version passes,  but the windows build fails in numerous ways. Particularly, this:

```
Warning:     Finished test [unoptimized + debuginfo] target(s) in 53.83s
     Running unittests src/lib.rs (target/x86_64-pc-windows-gnu/debug/deps/dreamweave-254981be5d2b5d45.exe)
Cannot open assembly '/home/runner/work/Dreamweave-server/Dreamweave-server/target/x86_64-pc-windows-gnu/debug/deps/dreamweave-254981be5d2b5d45.exe': File does not contain a valid CIL image.
```

Here is the full content of the workflow file:
```
name: Default Build
run-name: ${{ github.actor }} sent a push to GitHub.
on: [push]
jobs:
  Run-windows-tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update && sudo apt-get -y install gcc-multilib libtinfo5 mingw-w64
          echo "Automatically triggered by a ${{ github.event_name }} event."
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
          directory: ${{ runner.temp }}/llvmsteps
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      - name: Use cmake
        run: cmake --version
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - name: Run Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu --all-features
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target x86_64-pc-windows-gnu --all-features

```

I found a handful of mentions of similar issues online, but these were all related to C#/++ applications, which mine is  certainly not (Rust with static C linkage). I'm not sure how or why it would be running the wrong "interpreter" for these executable files, but it doesn't happen when running the actions locally with `act` or when doing it manually inside a fresh ubuntu docker container, so it certainly appears to be exclusive to ubuntu.
