### DISCUSSION TITLE
Deploy action not able to clone repo on remote server

### DISCUSSION THREAD

**Discussion by StanCodes** [community/community#64820] [Actions] [answered]
### Select Topic Area

Question

### Body

Hey everyone! 

I have a problem cloning my repo on a remote server. I want to have a deploy action job that deploys my app on a remote server via SSH. I have followed the tutorials and successfully created SSH keys  to connect GitRepo to remote server.
The job connects successfully(which I confirm with command "ls" and can see remote server files), but when running:
`git clone git@github.com:$USERNAME/$REPONAME.git`
it fails with:
`err: git@github.com: Permission denied (publickey).`
On the remote server I am able to successfully clone the repo with SSH:
```
root@$SERVER:~# ssh git@github.com
Enter passphrase for key '/root/.ssh/id_rsa':
PTY allocation request failed on channel 0
Hi $USERNAME! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```

Any ideas?

**Comment by arafajs** [comment]
If you are able to successfully clone the repo on the remote server, then the SSH key is configured correctly and the permissions are correct. This means that the problem is likely with the GitHub SSH URL.

Try to check the following:

- The GitHub SSH URL is correct. You can find the correct URL in your GitHub settings under the "SSH and GPG keys" tab.
- The email address in the GitHub SSH URL matches the email address that you used to create your SSH key.
- Try cloning the repo using a different SSH URL.
- Try cloning the repo from a different machine.
- Try cloning the repo using a different SSH key.

**Reply by StanCodes** [reply]
Thanks for the fast reply!

It seems that in my SSH URL there is no email , it's with the userName - git@github.com:StanCodes/$REPONAME.git, I also haven't stated my email while creating the SSH key pair, could this be the problem?

**Reply by arafajs** [reply]
@StanCodes 
Yes, that could be the problem. The email address in the SSH URL must match the email address that you used to create your SSH key. If you did not specify an email address when creating your SSH key, then you will need to create a new SSH key with an email address.

**Reply by StanCodes** [reply]
@arafajs 
I created the pair this time with my email address, but the result was exactly the same...
this is my deploy yml:
```
name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEPLOY_SSH_HOST}}
          key: ${{secrets.DEPLOY_SSH_PRIVATE_KEY}}
          username: ${{secrets.DEPLOY_SSH_USER}}
          passphrase: ${{secrets.DEPLOY_SSH_PASS}}

          script: |
            ls
            git clone git@github.com:StanCodes/$reponame.git
            echo 'Deployment successful!'
```
I have the created private key as secret in `DEPLOY_SSH_PRIVATE_KEY` and also added the public one in my Account Settings, SSH and GPG keys.
