### DISCUSSION TITLE
Using GITHUB_TOKEN to authenticate with the GitHub Packages

### DISCUSSION THREAD

**Discussion by JayamalHettiarachchi** [community/community#64853] [Actions]
### Select Topic Area

Question

### Body

We have published several GitHub packages for the internal use of our organization. We have configured GitHub actions for the publishing process, and it's working without any issues. For reference, here is the code,

```
name: Java Package

on:
   workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: build

    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
``` 
As I mentioned, we have no issues with the publishing process when using **GITHUB_TOKEN**. However, we face problems when using **GITHUB_TOKEN** to download packages. For your reference, here is the code,

```
    runs-on: windows-2019
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v3  
    - name: Set up JDK 8
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.7.1

    - name: Copy Dependencies with Gradle
      uses: gradle/gradle-build-action@v2.7.1
      with:
        arguments: copyDependencies
        gradle-executable: build/gradlew.bat
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
``` 
The problem is that you cannot download packages using **GITHUB_TOKEN**. It's working with personal access tokens, but we are trying not to use them anymore. These packages are in another repository.  

I have tried with **packages: write** permission as well. But I'm still waiting and posting this question after messing around with this matter for hours. Really appreciate your support.
