### DISCUSSION TITLE
Secret Value is visible for the first time creation

### DISCUSSION THREAD

**Discussion by yaswanth-badam** [community/community#64910] [New to GitHub]
Hello,

Secret Value is visible to eye for the 1st time creation. Is there any possibility to mask the secret value for the 1st time creation also?

Please share the best practices how to mask the secret value even for first time creation?

Thanks

**Comment by nirav-gajera** [comment]
You can do this by using the `::add-mask::` command in a GitHub Actions workflow. This command will mask the secret value with asterisks (*).



```
name: Mask secret value

on:
  push:
    branches:
      - main

jobs:
  MaskSecret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mask secret value
        run: echo ::add-mask:: ${{ secrets.SECRET_KEY }}
```

Once you have added the `::add-mask::` command to your workflow, you will not be able to see the secret value in plain text.


or: `INJECTED_ENV_VAR:     ${{secrets[github.event.inputs.injectedEnvVar]}}`
