### DISCUSSION TITLE
Upload the contents of the dist directory without including the dist directory itself

### DISCUSSION THREAD

**Discussion by DeployIsComing** [community/community#64973] [Actions]
### Select Topic Area

Question

### Body

Hello,  I want to upload the contents of the dist directory without including the dist directory itself. I just want to upload only the js transpiled files. but it is always creating the dist folder.... I want to keep everything in the root folder such as the index.js... I tried different approaches such as the one using wildcards but I got always the same results. Here my the part of my yml. 

`      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            dist/*
            package.json`

**Comment by TahirAhmad01** [comment]


**Reply by DeployIsComing** [reply]
Hello, all good? 

First of all, the answer you provided is Ipsis Litteris the same ChatGPT provided. I have also ChatGPT and I check all resources I have available before posting in a forum. If you are doing that to improve your reputation you are doing in the wrong way. I consider it as a spam. Just a tip for you ;)

Secondly, this workflow didn't work it has a few flaws.
Thanks!!

**Comment by DeployIsComing** [comment]
For those who came here... the working version / solution I reached so far is the below one. FYI I just added the LS command for debugging info you  can remove as you wish. 

```yml
name: 🔌 BUILD & DEPLOY

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: my-runner

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install
        run: npm install
      
      - name: npm build
        run: npm run build --if-present
      
      - name: Create temp folder
        run: mkdir temp_dist

      - name: Copy built files 
        run: cp -r dist/* temp_dist/

      - name: Copy package
        run: cp package.json temp_dist/

      - name: List root 
        run: ls

      - name: List target folder 
        run: ls temp_dist
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: temp_dist/*

# DEPLOY PART HERE...
```
