### DISCUSSION TITLE
a Required Workflow is only run for certain `types`; but failure isn't preventing merges

### DISCUSSION THREAD

**Discussion by qci-amos** [community/community#64998] [Actions]
### Select Topic Area

Question

### Body

We have a workflow that looks like this:
```yaml
name: Bump version

on:
  pull_request:
    types: [opened, labeled, closed]
    branches:
      - develop
      - development
      - staging
      - master
      - main
```
We want this workflow to be required, but it only needs to be run when the PR is opened or if the labels on the PR change (it's how we have devs specify how their PR should change the version number).

The problem is that if they didn't specify the version when they open the PR, that push will fail, but then all subsequent pushes will not trigger this workflow (and therefore get a green checkmark). Then when they want to merge, GH doesn't seem to be seeing that this action failed and isn't blocking the merge.

While I think we could work around this by removing `types`, this feels like it could be a GH bug or at least something worth documenting [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks). The closest documentation I can find is [here](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution), but my issue seems different from a "conditional".
