### DISCUSSION TITLE
Support for build-arg in docker-container-action

### DISCUSSION THREAD

**Discussion by amardeep2006** [community/community#65094] [Actions]
### Select Topic Area

Product Feedback

### Body

I am following this documentation for building and running containers on runtime https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

I am facing limitations while passing `--build-arg`  to the Dockerfile . It seems this is not possible currently. 
Why I need this feature. I want to make Dockerfile dynamic so that I can pass few arguments .
It will be a good addition if we could pass custom build arguments like this : 

```
# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  custom-build-argument:  # id of input
    description: 'Custom arg'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  build_args:
    - ${{ inputs.custom-build-argument }}
  args:
    - ${{ inputs.who-to-greet }}
```
