### DISCUSSION TITLE
Is it possible to a container service as dependency to another container service?

### DISCUSSION THREAD

**Discussion by Nosfistis** [community/community#65196] [Actions]
### Select Topic Area

Question

### Body

In a CI workflow, I mention 2 container services as dependencies, Keycloak and MariaDB. The latter is supposed to be the DB for the former, which means it should have started before Keycloak starts.

That is easy to define in a docker compose, but in a github workflow configuration is it possible?

**Comment by arafajs** [comment]
Yes, it is possible to define a container service dependency in a GitHub workflow configuration. You can do this by using the services keyword in the jobs section of your workflow. For example:

```
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql
    steps:
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
```
