### DISCUSSION TITLE
The images are not uploading correctly

### DISCUSSION THREAD

**Discussion by nishanthmathiyazhagan9704** [community/community#65209] [Actions]
### Select Topic Area

Question

### Body

Hello everyone,

I hope you're all doing well. I'm reaching out to ask for help with a situation I'm facing. I'm trying to run a script that redirects to different pages, takes screenshots, and then uploads them to a tool. Right now, I'm using the Safari browser for this process. Interestingly, on my local setup, everything works fine. The screenshots are taken correctly and are uploaded without any issues.

However, when I try to run the same script using GitHub Actions, I encounter a problem. While some screenshots get uploaded properly, others show issues. For example, I'm getting blank white pages or pages that haven't loaded properly. I've even tried adding a `max_wait` parameter, but that hasn't helped.

I'm reaching out to the community for any insights, suggestions, or guidance on how to address this problem. If any of you have faced a similar issue in the past or have ideas on how to troubleshoot and resolve this GitHub Actions problem, I would greatly appreciate your input.

Thank you in advance for your assistance.

**Here's my yml file** 

```
name: Crawl Website and Take Screenshots

on: [pull_request]

jobs:
  run_crawl_and_screenshots:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Git config
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Configure Safari WebDriver
        run: |
          sudo safaridriver --enable

      - name: Run the script with Safari
        run: |
          # Set maximum wait time in seconds
          MAX_WAIT_TIME=1200
          
            bundle exec rspec spec/crawler_spec.rb
        env: 
          API_KEY: ${{ secrets.API_KEY }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
```

**Environment Details:**

    Operating System: macOS Monterey 12.1
    Browser: 15.2 
    GitHub Actions Environment: macOS-latest
