### DISCUSSION TITLE
Always trigger a given step

### DISCUSSION THREAD

**Discussion by fspaniol** [community/community#65223] [Actions]
### Select Topic Area

Question

### Body

I have a workflow that has a step that always need to be run, even if it already passed on the first try.

For instance:

```yaml
jobs:
  a:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: sleep 90
      - run: echo A

  b:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [a]
    steps:
      - run: exit 1
```

Basically, I need `a` to run every time the workflow is triggered. This is an issue when using `Re-run failed jobs`. It will use the state from the previous run.

A few solutions here are possible:
- Deactivate running failed jobs for a given workflow (or repository altogether) 
- Have an alternative to the `always` function which is indeed always run
- Have a bundle of steps that need to be run together always
  - This is currently possible if you use a reusable workflow, I believe. If one of the jobs within a reusable workflow, the step on the calling workflow will fail, but that seems a bit overkill
