### DISCUSSION TITLE
Github Action Job Status is Wrong

### DISCUSSION THREAD

**Discussion by muhammedsaidkaya** [community/community#65359] [Actions]
### Select Topic Area

Bug

### Body

The problem is;

when we try to cancel a job with timeout-minutes property or make a job to fail manually (running exit 1 bash command), even if job exit code is 1, job status seems as succeeded (green mark).

On our example, We expect that the job, which is named e2e-test, fails.

![image](https://github.com/community/community/assets/32541088/87f90178-d4be-4f6b-ba30-88428d03fa68)

You can reproduce the problem with the following code block
```
name: E2E Tests

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      e2e: ${{ steps.set_output.outputs.e2e || steps.run_e2e.outputs.e2e }}
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run E2E tests
        id: run_e2e
        run: |
          sleep 100
          echo "e2e=success" >> $GITHUB_OUTPUT

      - name: Job Result Failure
        id: set_output
        run: |
          echo "e2e=failure" >> $GITHUB_OUTPUT
        if: failure()

      - name: If action is canceled or failure, then exit with code 1
        if: failure() || cancelled()
        run: |
          exit 1

  send-slack-notification:
    runs-on: ubuntu-latest
    needs: [e2e-test]
    steps:
      - name: Send slack notification
        run: |
          e2e_result="${{needs.e2e-test.outputs.e2e}}"
          if [[ -z "$e2e_result" ]]; then
            e2e_result="failure"
          fi
          echo "E2E Result: $e2e_result"
```

There is a related issue with it. [https://github.com/orgs/community/discussions/13955](https://github.com/orgs/community/discussions/13955)
