### DISCUSSION TITLE
Remote workflow using a local workflow misbehaving when using tags on push events

### DISCUSSION THREAD

**Discussion by tmcalves** [community/community#65447] [Actions]
### Select Topic Area

Bug

### Body

I have the following pipeline called p2p.yaml:

```
name: P2P
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  p2p:
    uses: myorg/myrepo/.github/workflows/p2p.yaml@v0.4.0
    with:
       project-id: ${{ vars.PROJECT_ID }}
       project-number: ${{ vars.PROJECT_NUMBER }}
       tenant-name: ${{ vars.TENANT_NAME }}

```
The `p2p.yaml` in the `myorg/myrepo` calls another workflow and looks like this:

```
name: IDP P2P

on:
  workflow_call:
    inputs:
      project-id:
        required: true
        type: string
      project-number:
        required: true
        type: string
      tenant-name:
        required: true
        type: string
      dry-run:
        required: false
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/execute-command.yaml
    with:
      command: p2p-build
...
```
`v0.4.0` is a tag created in `myorg/myrepo`

On pull_request events, everything works perfectly as intended. 
On push events things start misbehaving. I get the error:
```
Invalid workflow file: .github/workflows/p2p.yaml#L10
error parsing called workflow
".github/workflows/p2p.yaml"
-> "myorg/myrepo/.github/workflows/p2p.yaml@v0.3.0" (source tag with sha:ae1d86566beff750f626a55a2d2c0ddca2a4c402)
--> "./.github/workflows/execute-command.yaml"
: workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.
```
Reiterating that there is no error with this exact same pipeline on pull_request events.

If I change the tag `v0.4.0` to a branch (main or any other branch) everything works on both push and pull_request events.

This feels like a specific error/bug when using tags with push events.
Any ideas what's going on? 

Thanks in advance!
