### DISCUSSION TITLE
.NET 8 Support for deploying Blazor

### DISCUSSION THREAD

**Discussion by imsam67** [community/community#65486] [Actions]
### Select Topic Area

Question

### Body

Hi,

I'm trying to deploy a Blazor WASM app targeting .NET 8 to Azure Static Web Apps service using a GitHub action but it's failing with a message that indicates .NET 8 is currently not supported.

Any idea when GitHub actions will support .NET 8?

In case, it helps, this is the action I'm using to deploy the app to Azure Static Web Apps:

```
name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "/MyApp/" # location of your client code
  APP_ARTIFACT_LOCATION: "wwwroot" # location of client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing deployment token for your static web app

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    permissions:
      contents: none
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          action: "close"
```
