### DISCUSSION TITLE
Github Actions for PyPI: files not detected in dist/

### DISCUSSION THREAD

**Discussion by honsonbiosci** [community/community#65497] [Actions]
### Select Topic Area

Question

### Body

I am trying to use Github Actions as a Trusted Publisher for deployment to PyPI. This is my .yml file:

```
name: Upload probeutils

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```

And I get the error:

`[upload release to PyPI: # >> PyPA publish to PyPI GHA: MISSING DISTS <<#L1](https://github.com/honsonbiosci/probe_utils/commit/0c1428c3459bdb6ee6ab1d4002b68a703df8bda9#annotation_13777027108)
 It looks like there are no Python distribution packages to publish in the directory 'dist/'. Please verify that they are in place should you face this problem.`

However, I have already built the distribution packages using PyPA and I can see them on Github:

<img width="953" alt="Screenshot 2023-08-30 at 12 23 12 PM" src="https://github.com/community/community/assets/142455910/83eca958-f07b-436d-a9b9-6cf1ec9be08a">

Does anyone know what's going on here? I've double checked that the project name in PyPI matches my setup.py file but I can't think of anything else. I'm getting conflicting information from the PyPI and Github Actions documentation, as Actions seems to think you should use an API token whereas PyPI says having a release environment and setting the above conditions should work, so I'm very confused about what needs to be in the .yml file. I'm sure it's very obvious but I'd appreciate some help.
