### DISCUSSION TITLE
Why the difference between Composite Actions inputs and reusable workflow inputs

### DISCUSSION THREAD

**Discussion by MarcHagen** [community/community#65588] [Actions]
### Select Topic Area

Question

### Body

With a workflow that has a `workflow_call:` you can add inputs.
These inputs have a type and default value reflecting the type.

```yaml
  workflow_call:
    inputs:
      fail-on-low-coverage:
        default: false <<< this is actually a boolean
        description: Should this workflow fail when the coverage is below the minimum
        required: false
        type: boolean
      coverage-low:
        default: 60 <<< this is actually a integer
        description: Minimal required percentage of code that should be covered by tests, optionally fail when coverage is below minimum
        required: false
        type: number
```
Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
Schema validation: https://json.schemastore.org/github-workflow.json

Composite Actions also have inputs but lack the `type:` key and are always strings.
```yaml
inputs:
  php-extensions:
    default: dom, curl, libxml, mbstring, mailparse, zip, pcntl, pdo, pdo_mysql <<< string
    description: PHP extensions to enable
    required: false
  fail-on-low-coverage:
    default: "false" <<< must be string
    description: Should this workflow fail when the coverage is below the minimum
    required: false
  coverage-low:
    default: "60"  <<< must be string
    description: Minimal required percentage of code that should be covered by tests, optionally fail when coverage is below minimum
    required: false
```
Docs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
Schema validation: https://json.schemastore.org/github-action.json

Why is this different here?
It seems that only the workflow adheres to the [input-context](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context) while (composite) actions are whole different 

_also the name for both is so confusing. GitHub Actions, which has workflows and actions which both are separate things._
