### DISCUSSION TITLE
Workflow ignores "on" conditions

### DISCUSSION THREAD

**Discussion by Epithumia** [community/community#65582] [Actions]
### Select Topic Area

Question

### Body

I have set up a workflow to publish a package on PyPi for my repository (pyrailroad), but for some reason, it ignores the conditions:
```yaml
on:
  push:
    branches:    
      - main
    # Sequence of patterns matched against refs/tags
    tags:        
      - 'v*'
```

and triggers every time I push on the main branch.

I have another repository (Woodle) that is set up exactly the same, yet correctly follows the conditions. What am I missing?

**Comment by MarcHagen** [comment]
Your `Epithumia/Woodle` uses branch `master` and `Epithumia/pyrailroad` uses `main`.
It is exactly doing what it is supposed to do.

If you want only to run it on tags, you should use the following
```yaml
on:
  push:
    tags:        
      - 'v*'
```

**Reply by Epithumia** [reply]
Ah, good catch about the wrong branch name on Woodle (which means it was sort of doing what I wanted by accident).

If I want the condition for the workflow to trigger to be on `main` *and* when a 'v*' tag is pushed (so that it ignores a tag when a branch is pushed, or are tags independent of branches?), how would I go around to doing that, if that makes sense?

Or would
```yaml
on:
  release:
    types: [published]
``` 
make more sense? So that only when I manually create a release on github and it will then publish to PyPi?

**Reply by MarcHagen** [reply]
`on release` is a possibility, but not different from just a pushed tag.

You could also add an if too the whole job that checks for the github ref:
```yaml
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    # Only publish on `main` branch
    if: github.ref == 'refs/heads/main'
...
```
_untested but should work_
