### DISCUSSION TITLE
Can action access the input properties it defines?

### DISCUSSION THREAD

**Discussion by gilzow** [community/community#65621] [Actions]
### Select Topic Area

Question

### Body

When writing a composite action, can the action during its steps access properties of the `inputs` object it defines? 

As an example, let's say my action has the following inputs:

```
inputs:
  num-octocats:
    description: 'Number of Octocats'
    required: false
    default: '1'
  octocat-eye-color:
    description: 'Eye color of the Octocats'
    required: true
```

Given that we dont have `types` for action inputs yet, some times you have to verify that the input is what you expect. What I would like to do is in a step be able to access the `description`, and `default` properties of the inputs I've defined. For example:

```
runs:
  using: "composite"
  steps:
    - name: verify how many cats we need
      id: verify-cats
      shell: bash
      run: |
            totalcats=${{ inputs.num-octocats }}
            if [ -z "${totalcats##*[!0-9]*}" ]; then
               echo "::warning::The value you gave me for ${{ inputs.num-octocats.description }} isn't a number. Resetting to the default of ${{ inputs.num-octocats.default }}."
               totalcats=${{ inputs.num-octocats.default }}
            fi
            echo "cats=${totalcats}" >> $GITHUB_OUTPUT
```

Is something like this possible?
