### DISCUSSION TITLE
Deploy with GitHub Pages on super linter succeed

### DISCUSSION THREAD

**Discussion by geoffreylgv** [community/community#65661] [Actions]
### Select Topic Area

General

### Body

Hi lovely people,

## Context
I have a repo and made it to deploy on branch (_main_) when push or merge to it
At this point, I did not use GitHub action for the deployment.

I've added super linter (GitHub action workflow) to check all the codebase for clean code _(nothing much, only markdown actually, but it will be profitable for everyone in future with proper programming language)_

## Question
How can I do the deployment after all check of super linter passed ?
Do I need to create a workflow for deployment ?
How can i write that ?

**Comment by orazmyradov** [comment]
To deploy your code after the Super-Linter check has passed, you can set up a GitHub Actions workflow. This involves creating a new workflow file or updating an existing one.

Here's a step-by-step guide:

1. **Set up Super-Linter**

   If you haven't already, add the Super-Linter action to a workflow file (e.g., `.github/workflows/linting.yml`). The basic setup is:

   ```yaml
   name: Lint Code Base

   on:
     push:
       branches:
         - main

   jobs:
     lint:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Lint Code Base
         uses: github/super-linter@v4
         env:
           DEFAULT_BRANCH: main
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   ```

2. **Set up Deployment Workflow**

   Now, to deploy after linting, you can add your deployment steps to the same workflow file after the Super-Linter step or create a new workflow (e.g., `.github/workflows/deploy.yml`).

   For example, assuming you are deploying to a web server via SSH:

   ```yaml
   name: Lint and Deploy

   on:
     push:
       branches:
         - main

   jobs:
     lint-and-deploy:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Lint Code Base
         uses: github/super-linter@v4
         env:
           DEFAULT_BRANCH: main
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       - name: Deploy to Server
         if: success() # This ensures that deployment happens only if linting is successful
         run: |
           scp -r ./ your_username@your_server:/path/to/destination
           # any other deployment steps you might have
         env:
           PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
   ```

   In this example:

   - We use `scp` for deployment, assuming you have SSH access to the destination server.
   - `PRIVATE_KEY` is an SSH private key stored in GitHub secrets which can authenticate with the server. You should store secrets in the GitHub repository's "Settings" tab under "Secrets". Do NOT hardcode secrets in the workflow file.

3. **Adjust to Your Deployment Needs**

   The above example is generic and uses SSH for demonstration. Depending on where and how you deploy, you might need to adjust it. If you deploy to cloud services like AWS, Azure, or Google Cloud, there are specific GitHub Actions available for each platform. You just need to replace the "Deploy to Server" step with steps specific to your deployment process.

By setting up the workflow as described above, every time you push to the `main` branch, the Super-Linter will check your code, and if all checks pass, the deployment steps will execute.
