### DISCUSSION TITLE
cross-org reusable workflows with access to organization secrets is not working?

### DISCUSSION THREAD

**Discussion by ahmadnassri** [community/community#65766] [Actions]
### Select Topic Area

Question

### Body

I have the following scenario:

a private repository: `private-org/private-project/.github/workflows/workflow.yml`

```yaml
name: push

on: push

permissions: read-all

jobs:
  main:
    uses: user-account/actions/.github/workflows/reusable-workflow.yml@main
    secrets: inherit
```

the public repo & reusable workflow:

```yaml
on: workflow_call

jobs:
  main:
    uses: ./.github/workflows/job.yml
    secrets: inherit
```

the `job.yml` file:

```yaml
on: workflow_call

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TOKEN_TERRAFORM }}
```

the org-level secret `TOKEN_TERRAFORM` is set in `private-org`

the problem is, when running the action on `private-org/private-repo` the `secrets.TOKEN_TERRAFORM` is not being populated.

is this due to the reusable workflow being from a different org?! I can't seem to find documentation to confirm this

> **Note**
> The reusable workflows work perfectly fine within the context of `user-account` repositories ...
> the only differences that I can see are:
> - user account vs. org account
> - secrets are set on the repo level, not org (because user accounts don't have "org level secrets")
