### DISCUSSION TITLE
No GitHub Actions logs show when pushing code to a private Repo

### DISCUSSION THREAD

**Discussion by prag-sri** [community/community#65865] [Actions]
### Select Topic Area

Question

### Body

I am a member of a private GitHub Repo and have got all permissions like 'Write', etc. I am able to push code and everything but the problem is GitHub Actions shows no logs whatsoever.

Below is my yml file -
```
name: Run Karate tests (Maven)
on: push: branch: main
jobs: karate-tests: runs-on: ubuntu-latest
steps:
- name: Checkout code
  uses: actions/checkout@v2
- name: Set up JDK 11
  uses: actions/setup-java@v3
  with:
    java-version: '11'
    distribution: 'temurin'
    cache: maven
- name: Enable Debug Mode
  run: |
    echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
- name: Initialize Database
  run: |
    psql -U prag-sri -d ${{ secrets.DB }} -a -f path/to/setup_script.sql
- name: Karate tests
  working-directory: src/test/java
  env:
    HOST: ${{ secrets.HOST }}
    DB: ${{ secrets.DB }}
    PASS: ${{ secrets.PASS }}
  run: ./run-tests.sh
- name: Print Message
  run: |
    echo "This is a custom message to the logs."
- name: Teardown Database
  run: |
    psql -U prag-sri -d ${{ secrets.DB }} -a -f path/to/teardown_script.sql
- uses: actions/upload-artifact@v3
  with:
    name: Karate Report
    path: target/customReport
```

I tried 'echo "This is a custom message to the logs."' but nothing shows. 
I have also set environment variables : 'ACTIONS_RUNNER_DEBUG' and 'ACTIONS_STEP_DEBUG' as true.
