### DISCUSSION TITLE
Import all variables & secrets (both org and repo) to Action workflow

### DISCUSSION THREAD

**Discussion by gopac25** [community/community#65904] [Actions] [answered]
### Select Topic Area

Question

### Body

Currently I have more than 100 variables that needed to run my workflow. I am defining all the variables in each workflow file. Its very difficult to add/remove any new variables in actions file.

Do we have any options to import everything?

My file looks like,

name: Test 

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

env:
  HEALTH_CHECK: ${{ vars.HEALTH_CHECK }}
  HEALTH_CHECK_STATUS_CODES: ${{ vars.HEALTH_CHECK_STATUS_CODES }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_SECRETS: ${{ secrets.AWS_SECRETS }}
  dev_AWS_SECRETS: ${{ secrets.DEV_AWS_SECRETS }}

**Comment by ChristopherHX** [comment, marked as answer]
For example assign the whole vars/secrets object to env (could also be undocumented)

```yml
on: workflow_dispatch
env: ${{ vars }}
jobs:
  test:
    runs-on: ubuntu-latest
    env: ${{ secrets }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Dump env
      run: env
```

And now an undocumented (unsupported, but technically working) way

```yml
on: workflow_dispatch
env:
  ${{ insert }}: ${{ vars }}
  ${{ insert }}: ${{ secrets }}
  MY_STATIC_ENV: MY_STATIC_VALUE
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Dump env
      run: env
```

_Those examples has not been tested by me, should be accepted by GitHub Actions as of fall 2019_

Otherwise is tojson(secrets) your friend, so you can export the secrets / vars dynamically to the environment.
