### DISCUSSION TITLE
Workflows are unable to write to forked PRs even with "Allow edits and access to secrets by maintainers" ticked.

### DISCUSSION THREAD

**Discussion by winstxnhdw** [community/community#65939] [Actions]
### Select Topic Area

Bug

### Body

I contribute to an open source repository and I have written a workflow that intends to format a contributor's PR scripts and commit to their fork.

This is so I can avoid enforcing annoying pre-commit hooks in the codebase and provide contributors with a better development experience. 

Currently, it seems that it's not possible to do this.

I have tried the following.

```yaml
name: Format

on: [pull_request]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore tools
        run: dotnet tool restore

      - name: Format scripts
        run: dotnet tool run dotnet-format --fix-whitespace --no-restore

      - name: Set Git config
        run: |
          git config user.name octocat
          git config user.email octocat@users.noreply.github.com

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "style: fix whitespaces" || true
          git push origin ${{ github.head_ref }}
```

**Comment by AdnaneKhan** [comment]
This is because all workflows that run from fork PRs on the `pull_request` trigger only have read permissions since the workflow file runs in the context of the forked repository. If you look at a build log you'll see that the `GITHUB_TOKEN` will just have read access.

You need to run on the `pull_request_target` trigger in order to have write access. **Be careful** that the tools you are running do not run arbitrary code from the fork. Also make sure to put `${{ github.head_ref }}` in an environment variable otherwise someone could inject code using it.

**Reply by winstxnhdw** [reply]
Hey, thanks for the response! Really appreciate it. I'll test it out soon.

**Reply by winstxnhdw** [reply]
Seems to work so far.

**Reply by winstxnhdw** [reply]
Okay, never mind. It didn't work.

Something like this did, though. Bad thing about this implementation is that contributors will not get the benefits of the formatter if they are working off a branch with the name `master`.

```yaml
name: Format

on:
  push:
    branches-ignore: [master]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Format scripts
        run: |
          dotnet tool restore
          dotnet tool run dotnet-format --fix-whitespace --no-restore

      - name: Set Git config
        run: |
          git config user.name octocat
          git config user.email octocat@users.noreply.github.com

      - name: Commit changes
        run: |
          git add .
          git commit -m "style: fix whitespaces" || true
          git push
```

**Reply by AdnaneKhan** [reply]
Curious why on `pull_request_target` didn't work? For a fork PR (provided the PR creator allows edit access to their fork) it _should_ work. Same permissions error? I wonder if it needs write access to PRs in addition to contents.

The approach with on push will work, but by default forks have actions disabled, so nothing will run unless the contributor enables actions in their fork.

**Reply by consultors** [reply]
name: Format

on: [pull_request]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore tools
        run: dotnet tool restore

      - name: Format scripts
        run: dotnet tool run dotnet-format --fix-whitespace --no-restore

      - name: Set Git config
        run: |
          git config user.name octocat
          git config user.email octocat@users.noreply.github.com

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "style: fix whitespaces" || true
          git push origin ${{ github.head_ref }}

**Reply by winstxnhdw** [reply]
@AdnaneKhan Not sure why it doesn’t work, but the workflow doesn’t run. I tried specifically matching `synchronize` but still no go. 

> default forks have actions disabled, so nothing will run unless the contributor enables actions in their fork.

It’s the best we can do now, I guess.

**Reply by AdnaneKhan** [reply]
Can you share the trigger? it should look like this:

```
name: Format

on: [pull_request_target]

permissions:
  contents: write

```

**Reply by winstxnhdw** [reply]
Yup, that's what I tried as well. I also tried [this](https://github.com/G-Research/consuldotnet/blob/1b4aa1fa446027a79753b12f92f5f23267828431/.github/workflows/formatter.yml).

**Reply by AdnaneKhan** [reply]
Also, remember that the workflow has to be in the repository before it will run. Once you add the workflow to a branch on the repository, `pull_request_target` will trigger once you make a PR against that branch.

**Reply by winstxnhdw** [reply]
Yeah, it doesn't run when the PR is updated either. Tried everything --- editing the PR, adding a comment, pushing a new commit, etc.

**Reply by AdnaneKhan** [reply]
@winstxnhdw That's because the workflow isn't in the target repo yet (I took a look at the PR you have open, and the workflow is only in your fork, not the base repo). If you want to test that it works, do this:

Update to `pull_request_target` in your fork, from _another_ fork create a PR to that fork. You'll see that the workflow runs and that it is able to push updates to the 2nd fork branch.

If you would update https://github.com/winstxnhdw/consuldotnet/blob/formatter/.github/workflows/formatter.yml in your fork back to `pull_request_target` I can quickly show you.

**Reply by winstxnhdw** [reply]
You're right. I just ran a test on my private repository. It seems to work!

**Reply by winstxnhdw** [reply]
Can't seem to get it to commit to the fork though.. I am doing this now.

```yaml
name: Format

on:
  pull_request_target:
    paths:
      - '**.editorconfig'
      - '**.globalconfig'
      - '**.cs'
      - .github/workflows/main.yml

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Format scripts
        run: |
          dotnet tool restore
          dotnet tool run dotnet-format --fix-whitespace --no-restore

      - name: Set Git config
        run: |
          git config user.name 'octocat'
          git config user.email 'octocat@users.noreply.github.com'

      - name: Commit changes
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          echo "test" >> new_file.txt
          git add .
          git commit -m "style: fix whitespaces" || true
          git push $BRANCH_NAME
```

This is the error I am getting

```
[master 6fbafea] style: fix whitespaces
 1 file changed, 1 insertion(+)
fatal: 'werf' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Process completed with exit code 128.
```
