### DISCUSSION TITLE
Workflow enabled only for particular user ?

### DISCUSSION THREAD

**Discussion by a-hultin** [community/community#66029] [Actions]
### Select Topic Area

Question

### Body

Can a workflow with workflow-dispatch trigger be configured to only be enabled for a particular user, disabled for others ?

Example -  a deploy to production workflow should only be able to be triggered by 'special user'.

**Comment by kehiy** [comment]
hello @a-hultin 
Yes, it is possible to configure a workflow with the workflow-dispatch trigger to only be enabled for a particular user and disabled for others. This can be achieved by adding a conditional expression in the workflow file that checks the value of the GITHUB_ACTOR environment variable, which contains the user who triggered the workflow.

```yaml
name: Deploy to Production
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == 'special_user'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to production
        run: |
          # command to deploy to production
```
