### DISCUSSION TITLE
Accessing a secret output from a job, in a job using a reusable workflow

### DISCUSSION THREAD

**Discussion by Arr-n-D** [community/community#66044] [Actions]
### Select Topic Area

Question

### Body

I have a repository that contains multiple environments containing different credentials

In job-2, I set the environment to a dynamic environment output from the previous job, job-1, in a manner similar to this.

Please note the following yaml files aren't fully valid.

```yml
 job-2:
        runs-on: ubuntu-latest
        needs: [job-1]
        environment: ${{ inputs.folder }}-${{ needs.job-1.outputs.ENVIRONMENT }}
        outputs: 
            AWS_ACCOUNT: ${{ steps.xx.outputs.AWS_ACCOUNT }}
            AWS_REGION: ${{ steps.xx.outputs.AWS_REGION }}
        
       steps:
           AWS_ACCOUNT: some encryption job to set its value and set it as output

```

My job-3 then needs to consume job-2's outputs, which then calls a reusable workflow with those outputs.

```yml
job-3:
        needs: [job-1, job-2]
        uses: reusable_workflow.yaml
        secrets:
            AWS_ACCOUNT: output from job-2
```

From what I understand, it is impossible to pass secrets between jobs as they're being run by different workers, so the only way is to unmask them. I managed to set the output of job-2 using encryption, but I now need to decrypt it in job-3, which is not possible as job-3 only executes a reusable workflow. 

My question is, how could I manage to use an output from job-2, which is a secret, inside of job-3, which uses a reusable workflow, apart from modifying the reusable workflow itself?

**Comment by neilime** [comment]
This is really blocking to do not have  a way to pass generated secrets to a reusable workflow. Here is another use case:

> Generate a github app token then pass it to nested workflows

**⚠ This is not working but we need a solution to make it work.**

The warning occurred: `Skip output 'token' since it may contain secret.`

```yml
jobs:
  generate-token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.generate-token.outputs.token }}
    permissions:
      id-token: write
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ vars.CI_BOT_APP_ID }}
          private_key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}

  internal-job:
    uses: ./.github/workflows/test-workflow-secret.yml
    secrets:
      token: ${{ needs.generate-token.outputs.token }}

  external-job:
    uses: neilime/test-workflow/.github/workflows/test-workflow-secret.yml@0.1.0
    secrets:
      token: ${{ needs.generate-token.outputs.token }}

```
