### DISCUSSION TITLE
Github action cannot install NPM package hosted on the Github package registry.

### DISCUSSION THREAD

**Discussion by wrux** [community/community#66089] [Actions]
### Select Topic Area

General

### Body

I have published a NPM package on Github, set it up as a dependency locally and in Vercel no problem. I'm just having issues getting it installing as a dependency in Github actions. 

My package: https://github.com/wrux/sanity-analytics-dashboard-widgets/pkgs/npm/sanity-analytics-dashboard-widgets

Here's my local `.npmrc` config, nothing special:
```
@wrux:registry=https://npm.pkg.github.com
npm.pkg.github.com/:_authToken=XXXXXX
```

I understand that I need to setup my action properly with `actions/setup-node@v3`, but I'm not sure where I'm going wrong. I  assume the configuration will be very simple and I've read through the readme, but not sure where to proceed. 

Here's what my [workflow file](https://github.com/wrux/callum/blob/feature/sanity-analytics-dashboard-widgets/.github/workflows/eslint.yml#L14) looks like. 

Any ideas here? I cannot really find much info on how to setup a project with Github's NPM package registry as a dependency.

**Comment by arafajs** [comment]
1. Make sure you are using `actions/setup-node@v3` or later. Earlier versions did not support installing from GitHub's package registry by default.
2. Set the `node-version` input for `actions/setup-node` to match the Node.js version used in your package.json.

```yaml
- uses: actions/setup-node@v3
  with: 
    node-version: 16
```

3. Add the `.npmrc` file to your repository with the GitHub registry and auth token configured. 
4. In your workflow, use the `settings` input for `actions/setup-node` to point to the `.npmrc` file.

```yaml 
- uses: actions/setup-node@v3
  with:
    settings-path: .npmrc
```

5. Make sure you are authenticating with the GitHub registry before trying to install packages. You can use the `actions/npm-auth` action for this.

```yaml
- uses: actions/npm-auth@v1
  with:
    registry-url: 'https://npm.pkg.github.com'
```

6. Run `npm install` after the auth step to install your dependencies.
That should allow npm to find and install your GitHub hosted package in the workflow.

**Reply by wrux** [reply]
I'm confused, was this a Chat GPT response? 

Asking because most of this reply was suggesting something that does not exist:

1. The action `actions/setup-node` has no argument `settings-path`
2. The package `actions/npm-auth` doesn't even exist.

**Reply by sciutand** [reply]
I guess you found your answer by now but these are these are the requirements

1:  in the package repository settings add the repository you want to checkout from in the authorised GitHub action repositories

2: in your workflow grant the token read permissions:

```
permissions:
   packages: read
```
3: add the required env.  `actions/setup-node` assumes the correct token is set at `env:NODE_AUTH_TOKEN`

```
env:
     NODE_AUTH_TOKEN: ${{ github.token }}
```

4 use `actions/setup-node`

```
 - name: Install Node.js
    uses: actions/setup-node@v3
    with:
      registry-url: https://npm.pkg.github.com/
```
