### DISCUSSION TITLE
reusable workflows, actions, local references and branching

### DISCUSSION THREAD

**Discussion by splitbrain** [community/community#66094] [Actions]
### Select Topic Area

Question

### Body

I'm trying to set up a a bunch of reusable workflows and custom actions that will be reused by many other repositories. But I'm having some trouble with referencing things.

I try to give a simplified picture below. In my repository (lets call it `example/actionflow`) I have:

* Two custom actions.
  * `.github/actions/action1/` (with `action.yml` and `index.js`)
  * `.github/actions/action2/` (with `action.yml` and `index.js`)
* Multiple workflows with one that calls all others
  * `.github/workflows/all.yml`
  * `.github/workflows/flow1.yml`
  * `.github/workflows/flow2.yml`

So far so good. In a different repository (`example/actiontest`) I have the following:

```
jobs:
  all:
    uses: example/actionflow/.github/workflows/all.yml@devel
```

As you can see, I'm currently using the devel branch of the `actionflow` repo. I will continue working on it, while others might already use the stable `main` branch. Because of this, I want to avoid hardcoding any branch names in the workflows above, because that makes merging a pain.

So far this works fine for the workflows, by using relative paths in `all.yml`

``` 
jobs:
  first:
    uses: ./.github/workflows/flow1.yml
  second:
    uses: ./.github/workflows/flow2.yml
```

Above will run fine within the `example/actiontest` repo.

However where it breaks apart is when we add an action to one of the flows.

```
jobs:
  flow1:
    runs-on: ubuntu-latest
    steps:
      - name: run action1
        uses: ./.github/actions/action1
```

Running this within the `example/actiontest` repo will result in the following error:

> Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/actiontest/actiontest/.github/actions/action1'. Did you forget to run actions/checkout before running your local action?

So while the earlier, when using only workflows, the `./.github/` path correctly referenced the directory in the `example/actionflow` repository, the calls to actions now reference the `example/actiontest` repository and can no longer find the actions I want to use.

Of course I could always use a line like `uses: example/actionflow/.github/actions/action1@devel`, but that would hardcode the branch name.

So here's the question: how do I reference actions relative to the workflow file they are called from?

**Comment by RemyMachado** [comment]
This seem like a common use case and it's not explained in the official documentation.
Did you find the correct way to achieve it?

**Reply by splitbrain** [reply]
It simply seems to be unsupported. I ended up writing a script to quickly change the branch name in all actions and need to remember running it before merging. Similar to what @joshjohanning suggests below.

**Comment by joshjohanning** [comment]
When calling a reusable workflow, the repo isn't `cloned` to disk in the same way that referencing another action repo is. When referencing a reusable workflow, you just retrieve the workflow logic as if it was running from your original repo. 

The reason you get this error is that it's expecting a local action (as in, local to the CALLING repo not the REUSABLE WORKFLOW repo)
> Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/actiontest/actiontest/.github/actions/action1'. Did you forget to run actions/checkout before running your local action?

As far as I know, you either have to hardcode the branch name in the reusable workflow or somehow dynamically clone the reusable workflow repo and have the actions placed in the appropriate subdirectory it's expecting. 

Updating the branch names can be a chore, especially if you have multiple, but some folks have created linting/parsing scripts to make sure the branch names all match before allowing a merge.

**Reply by RemyMachado** [reply]
I'm starting to doubt its feasable. Here's the full context:
**In the same private organization**, I have a reusable workflow in a repository (let's call it Repo B), and this reusable workflow is trying to use composite actions that are also defined in Repo B. However, when I call this reusable workflow from another repository (let's call it Repo A), it doesn't work. What's the correct way to do that? I just need a 10 lines code snippet showing how to use the actions on Repo B. I'm hopeless...

Here's what I tried so far in the reusable workflow (Repo B):
```yml
jobs:
  job-of-reusable-workflow:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Retrieve Repo B composite github actions'
        uses: actions/checkout@v4
        with:
          repository: 'org-name/repo-b'
          sparse-checkout: '.github/actions/'
     - name: 'Calling my composite Repo B action'
        uses: 'org-name/repo-b/.github/actions/my-composite-action/action.yml@main'
```

I scanned so many threads and stack-overflow's pages, all with this exact problem, but no solution.
Any help would be greatly appreciated.

PS: I added the correct GHActions access rights to Repo B to allow Repo A from accessing it.

**Reply by joshjohanning** [reply]
> However, when I call this reusable workflow from another repository (let's call it Repo A), it doesn't work.

yes because the workflow is running from the _context of repo a_ - it is NOT going to have any of the files (thus, actions) from repoB. Nor is it going to have authentication to be able to access repoB.

But it looks like you are trying to do 2 things in the reusable workflow - use a _local action path_ and a _git ref action reference_. Also, I don't know if you can place a composite action in the `.github/workflows` folder like this (this directory is often treated differently).  I would model it similar to how the [CodeQL action](https://github.com/github/codeql-action/) does; each separate action is in a different directory, ie: `analyze`, `autobuild`, etc.

Let's say you moved your action from `./.github/actions/my-composite-action` to `./my-composite-action`. This is what I would try:

1. Reference the action this way - no need to check out the repo-b

```yml
jobs:
  job-of-reusable-workflow:
    runs-on: ubuntu-latest
    environment: production
    steps:
     - name: 'Calling my composite Repo B action'
        uses: 'org-name/repo-b/my-composite-action@main' # no need to reference `action.yml`
```

2. This could also work, but you need your own token:

```yml
jobs:
  job-of-reusable-workflow:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Retrieve Repo B composite github actions'
        uses: actions/checkout@v4
        with:
          repository: 'org-name/repo-b'
          token: ${{ secrets.MY_PAT }}
     - name: 'Calling my composite Repo B action'
       uses: './my-composite-action' # no need to reference `action.yml` or `@main`
       # uses: './repo-b/my-composite-action'  # could also be this depending on pathing

```

Instead of a PAT, I would recommend using a [GitHub App](https://josh-ops.com/posts/github-apps/) and this [action](https://github.com/marketplace/actions/create-github-app-token) to retrieve a token that can be used to fetch Repo-b.

This should work. This is similar to what you would have to do before GitHub Actions supported non-public actions.

**Reply by RemyMachado** [reply]
Thank you for your prompt response.

1. The first code snippet doesn't match the exact need I currently have, but I'll definitely try it soon.
2. The second one however is what I needed. I tried the following and it works:
```yml
# inside the reusable workflow (Repo B)
jobs:
  job-of-reusable-workflow:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout Repo B composite actions'
        uses: actions/checkout@v4
        with:
          repository: 'org-name/repo-b'
          sparse-checkout: '.github/actions/'
          token: ${{ secrets.MY_PAT }}
      
      - name: 'Use Repo B action'
        uses: './.github/actions/repo-b-action'
```

#### I have several points/questions resulting of this way of doing:
- I'm stuck with `envionment: production`, I didn't succeed to make it dynamic, how would I make this reusable workflow work for any environment?
- Why would I need a Personal Access Token, when I'm in the same organization, this is really inconvenient.
- The Personal Access Token is linked to an account and it doesn't fit the way you would use a CI/CD tool. An organization/repository/deploy key would be more suitable.
- Can GitHub Apps be private? Is it only available for GitHub enterprises? I'm currently using a small team plan.

I think GitHub actions are really simple to use and a perfect tool for CI/CD, but this use case of simply sharing private workflows and actions across an organization is a nightmare to handle.

**Reply by joshjohanning** [reply]
> I'm stuck with envionment: production, I didn't succeed to make it dynamic, how would I make this reusable workflow work for any environment?

You could add the environment as an input, like this: https://github.com/joshjohanning-org/reusable-workflows/blob/main/.github/workflows/deploy-sample.yml#L14-L27


> Why would I need a Personal Access Token, when I'm in the same organization, this is really inconvenient.

That's just how GitHub Actions is designed; designed to have authentication to be able to read/write to the _current_ repository, and if you need anything else, you need to provide your own cred.  

https://docs.github.com/en/actions/security-guides/automatic-token-authentication

> When you enable GitHub Actions, GitHub installs a GitHub App on your repository. The GITHUB_TOKEN secret is a GitHub App installation access token. You can use the installation access token to authenticate on behalf of the GitHub App installed on your repository. The token's permissions are limited to the repository that contains your workflow. For more information, see "[Permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)."

> The Personal Access Token is linked to an account and it doesn't fit the way you would use a CI/CD tool. An organization/repository/deploy key would be more suitable.

I suppose you could use a deploy key and the `ssh-key` input with the `actions/checkout` action.  The deploy key is only valid for a single repository though. I like using a GitHub App since it is more scalable to other repositories as well as other configurable permissions.

See: 
- https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow#authenticating-with-a-github-app
- https://josh-ops.com/posts/github-apps/

> Can GitHub Apps be private? Is it only available for GitHub enterprises? I'm currently using a small team plan.

Yes the app can be private. It can be created/owned by the organization or your user account. If you're an org owner, you can create the app under the org and install it on select repo(s) or for all repos in the org.  If you're not an org owner, you can create the app under your user account and request it to be installed to the org and/or repo(s) you need, then your org owner will have to approve.  The org owner can also make you a [GitHub App Manager](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#github-app-managers) to give you rights to be able to create the app under the org without being an org owner.

And make sure not to confuse "App" with "this is an app that needs code" - a GitHub App is effectively just a bot account that can receive permissions and optionally webhook events.

**Reply by joshjohanning** [reply]
> I think GitHub actions are really simple to use and a perfect tool for CI/CD, but this use case of simply sharing private workflows and actions across an organization is a nightmare to handle.

But I still think there is an easier way to do it than **solution # 2** above (closer to # 1) where you can refer to your reusable workflow + composite action without providing any auth. 

## Calling workflow

link: https://github.com/joshjohanning-org/call-reusable-workflow-calling-composite-action/blob/main/.github/workflows/ci.yml

```yml

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dev:
    uses: joshjohanning-org/reusable-workflows/.github/workflows/reusable-workflow-call-composite-action.yml@add-composite-action
    with:
      environment: dev
```

## reusable workflow calling composite action in the same repo

link: https://github.com/joshjohanning-org/reusable-workflows/blob/add-composite-action/.github/workflows/reusable-workflow-call-composite-action.yml

```yml
name: reusable-workflow-call-composite-action

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      environment:
        description: environment in github
        type: string
        default: dev
jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    environment: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v4
    
    - uses: joshjohanning-org/reusable-workflows/composite-action@add-composite-action
      with:
        who-to-greet: mona
```

You'll note how I called the composite action that's located in the same directory as the reusable workflow - like this

```yml
- uses: joshjohanning-org/reusable-workflows/composite-action@add-composite-action
```

The perhaps only thing is that you can't use an input or variable for the git branch / ref / tag here `@add-composite-action`.  Actions is designed to be able to version these independently.  Refer to it as `@main` if you always need it to be latest.

**Reply by RemyMachado** [reply]
Great!
I don't know why I thought I couldn't just pass the environment as a dynamic input, but it works!
___
Indeed, using a deploy key with the `ssh-key` input of the `checkout` action is much cleaner, I'm glad you advised it to me!
___
I'm not sure I understand what GitHub Apps is for and how it would help in this situation. What I understood is that it's comparable to a Discord bot for automating Discord stuff, except here in the GitHub ecosystem for automating GitHub stuff. The workflow actions are already doing the automation, I don't understand why I would need to create a GitHub App.
___
> reusable workflow calling composite action in the same repo
```yml
jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    environment: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v4
    
    - uses: joshjohanning-org/reusable-workflows/composite-action@add-composite-action
      with:
        who-to-greet: mona
```
1. In your example you are using `actions/checkout` without telling which repository to pull, which would result in pulling Repo A (caller workflow) if I understood right.

2. I may have explained my use case incorrectly. The actions are inside `org/repo-b/.github/actions/` and I need to use them from `org/repo-b/.github/workflows/` when called from another repository workflow `org/repo-a/.github/workflows`.
When I tried with absolute paths without token/ssh-key it didn't succeed to checkout the actions.
___
I'm quite happy with the changes you made me do and I think I'll stick with that.
Also, I think this is a really popular use-case and what you explained to me deserves its own place in the official documentation.

Thank you very much @joshjohanning for your help.
