### DISCUSSION TITLE
How to enable git submodules on GitHub pages

### DISCUSSION THREAD

**Discussion by LiquidZulu** [community/community#66112] [Actions]
### Select Topic Area

Question

### Body

I have an [Astro](https://astro.build) site that uses a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for one of the content collections (just a bunch of markdown). When the site is building on GitHub, Astro errors telling me that the content collection cannot be found. The build logs indicate that submodules are disabled:

```
Run actions/checkout@v3
  with:
    repository: LiquidZulu/liquidzulu.github.io
    ...
    submodules: false
    ...
```

The [docs page](https://docs.github.com/en/pages/getting-started-with-github-pages/using-submodules-with-github-pages) on using git submodules with GitHub pages says that the submodule must be public and be using "the `https://` read-only URL." The submodule is public, which draws me to the second criterion: what exactly is an `https://` read-only URL? I have tried both:

```
[submodule "src/content/brain"]
	path = src/content/brain
	url = https://github.com/LiquidZulu/brain.git
```

and
```
[submodule "src/content/brain"]
	path = src/content/brain
	url = https://github.com/LiquidZulu/brain
```

In the `.gitmodules`, neither work, and I am out of ideas for different URLs to try.

**Comment by LiquidZulu** [comment]
The solution is to add the following to the `deploy.yml`:
```yaml
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout your repository using git
              uses: actions/checkout@v3
              with:
                  submodules: 'true'
```
