### DISCUSSION TITLE
1 manual job in a workflow

### DISCUSSION THREAD

**Discussion by WillSmithTE** [community/community#66132] [Actions]
### Select Topic Area

Question

### Body

Hi, I'd like to have 1 manual job in my workflow but can't find a way to do that anywhere.

Here is something like my main workflow, `main.yml`.

```
name: "main-push"
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm --version && node --version

  dev-deploy:
    needs: unit-test
    uses: ./.github/workflows/deploy.yml
    with:
      env-upper: DEV
      env-lower: dev
```

Right now I have a separate workflow `prod-deploy.yml`, which I trigger manually (usually every few commits) to push to prod.

```

name: prod-deploy
on: 
    workflow_dispatch:
permissions:
    id-token: write
    contents: read
jobs:
    prod-deploy:
        uses: ./.github/workflows/deploy.yml
        with:
            env-upper: PROD
            env-lower: prod
```

The problem is, I should only be able to push commits to prod which have already gone through the `main-push` workflow. Soon I'll be adding e2e tests  to that workflow, and want to make sure I only push to prod what has gone through those e2e tests on dev.

Essentially what I want to add to `main.yml`

```
prod-deploy:
        on: manual
        uses: ./.github/workflows/deploy.yml
        with:
            env-upper: PROD
            env-lower: prod
```

Then I want to be able to see for a particular commit the unit tests, dev-deploy, dev e2e tests, and have the option to manually push that to prod.

How are you all doing this? Sorry if I've missed something obvious, the only suggestions I've seen are the separate prod-deploy workflow I have, or running the `prod-deploy` conditionally, something like `if: eventName == 'workflow_dispatch'`. But that means I have to run the whole workflow, which doesn't work for me. Thanks a lot!

**Comment by DirkLachowski** [comment]
We auto deploy on each push in a deployment step but have a dedicated production branch
- pushing (merging) to that branch deploys to production
- all other pushes deploy to staging (it’s a bit more elaborated here as we have multiple staging environments, but you get the idea)

You could also opt to only deploy to prod using the prod branch and skip the staging deploy (but using auto deploy to staging also opens up the option to use [deployment protection rules](https://docs.github.com/en/actions/deployment/protecting-deployments/configuring-custom-deployment-protection-rules)).

Another option is to use a tag to trigger a deploy to prod. In the end, you’ll want to be able to pin what you have deployed, so a manual trigger that isn’t resembled somewhere in the repo maybe isn’t your optimal choice.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by WillSmithTE** [comment]
Not dormant. For now using a dedicated prod branch like Dirk, but there's no guarantee the commit I chose has already gone through my CI on a test environment.

Gitlab lets me do this

![sWpgj](https://github.com/community/community/assets/26863411/9f53e681-3e17-4b0b-b30c-b7d593aac4e9)

**Reply by DirkLachowski** [reply]
If you're on GH Enterprise, you can do the same exact thing in GH, see https://docs.github.com/en/actions/deployment/protecting-deployments/configuring-custom-deployment-protection-rules . We're using this together with Jira Service Management that has a nice integration with GH's protection rules. See https://community.atlassian.com/t5/Jira-Service-Management-articles/Introducing-deployment-gating-for-GitHub-in-Jira-Service/ba-p/2638870

**Comment by rreihl** [comment]
Moving from GitLab to GitHub, this is a major issue for me. I deploy cloud infrastructure with CI by running terraform plan automatically, but requiring a manual trigger to apply the plan. That gives you a chance to review the plan before it is applied. 

I could make a dummy environment as a hacky workaround to get closer to my desired workflow, but surely this must be solved properly somewhere in GitHub???

**Reply by DirkLachowski** [reply]
If GH Enterprise isn't an option, maybe check https://github.com/marketplace/actions/manual-workflow-approval

But careful: This action keeps the WF running, so it can be a more costly solution than using GH Enterprise

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by ThomasAFink** [comment]
You can get “manual jobs” in GitHub Actions by using Environments + required reviewers (approval gates).

- In your workflow, put the slow/production step behind an environment:
```
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: ./deploy.sh
```

- Then go to Repo → Settings → Environments `https://github.com/owner/repo/settings/environments`, create/select the environment (e.g. production), and under Deployment protection rules set Required reviewers.
- You can choose yourself, a team, or specific users.

If you add yourself, it’s effectively “self-approve”: the workflow will pause at that job until you click Review deployments / Approve and deploy in the Actions UI.

<img width="723" height="248" alt="Screenshot 2026-03-18 at 13 34 07" src="https://github.com/user-attachments/assets/f66bd2d7-a0be-4698-ac61-4fd3ae1dfe3f" />

Not sure if this is also in the free Github Version
