### DISCUSSION TITLE
Possible Bug - PR Auto-merging and Github Environments

### DISCUSSION THREAD

**Discussion by leotomas837** [community/community#66145] [Actions]
### Select Topic Area

Bug

### Body

After trying the PR auto-merging feature on a test repo (works fine), I am having issue when using it with Github Environments on another repo.

![image](https://github.com/community/community/assets/97767501/ab48b4b6-9c1a-4096-884b-f575edc8a0dd)

I have 3 Github environments: `Production` for branch `master`, `Development` for branch `dev` and `Staging` for branch `staging`. 

![image](https://github.com/community/community/assets/97767501/4601999d-dbf7-4552-9e85-f6a356e415f5)

Thanks to protection rules, I enforce PRs to be merged first into the `dev` branch, then `staging` and finally `master`. For example here is what is setup in the protection rule targeting `master`:

![image](https://github.com/community/community/assets/97767501/a6d2f793-8cdf-4d54-85ad-9e5051445707)

When pushing to `dev`, `staging` and `master`, a workflow is triggered creating the environment deployment after 5-10 minutes. Keeping only the essential, the workflow is similar to the following:

```yaml
name: Running Deployment

on: [push]

env:
    REF_NAME: ${{ github.ref_name }}

jobs:
    TestingCommitValidity:
        uses: ./.github/workflows/ci.yml
        with: {}
        secrets: inherit

    SelectingDeploymentProfile:
        name: Selecting deployment profile
        runs-on: ubuntu-latest
        needs: [TestingCommitValidity]
        if:
            github.ref_name == 'dev' || github.ref_name == 'staging' || github.ref_name == 'master'
        outputs:
            deployment_profile:
                ${{ steps.select_deployment_profile.outputs.deployment_profile }}
        steps:
            - name: Selecting deployment profile
              id: select_deployment_profile
              run: |
                  case "${REF_NAME}" in
                      'dev' )
                          printf 'deployment_profile=Development\n' >> "$GITHUB_OUTPUT"
                          ;;
                      'master' )
                          printf 'deployment_profile=Production\n' >> "$GITHUB_OUTPUT"
                          ;;
                      'staging' )
                          printf 'deployment_profile=Staging\n' >> "$GITHUB_OUTPUT"
                          ;;
                  esac

    Deployment:
        name: Deploying
        runs-on: ubuntu-latest
        needs: [SelectingDeploymentProfile]
        environment: ${{ needs.SelectingDeploymentProfile.outputs.deployment_profile }}
        [...]
```

This works perfectly without the auto-merge feature enabled. For example, after merging `mybranch` into `dev` but not in `staging`, the open PR to `master` is (still) blocked:

![Screenshot 2023-09-06 at 18 39 30](https://github.com/community/community/assets/97767501/d55c0a3a-ce6e-4f24-acd4-59abb7b16710)

Once merged into `staging` and the `Staging` deployment created, I am then able to merge into `master` manually.

Yet the issue is when enabling the auto-merge feature, for example after merging into `dev` and the `Development` deployment successful, and having the auto-merge feature enabled on the PR into `staging`,  here is what I get:

![image](https://github.com/community/community/assets/97767501/bc6826ae-8354-4b76-bf4d-a4e5d1b5b1ed)

![Screenshot 2023-09-06 at 18 53 45](https://github.com/community/community/assets/97767501/820478f1-aee9-404e-9858-a4465dd3cf1d)

As you can see:
- 'Auto-merge' is enabled on the PR, and the PR mentions 'Merging can be performed automatically'
- The `Development` environment deployment was successfully deployed
- All checks where successful
- Nothing blocks the PR from being merged

Yet the PR is not automatically merged. Is this a bug?
