### DISCUSSION TITLE
Suggestions : inspirational posters with kittens

### DISCUSSION THREAD

**Discussion by romainmenke** [community/community#66195] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Product Feedback

### Body

As a maintainer of open source software with also a full time job I expect GitHub to be a tool designed to help me.

It should help me be the best version of me.

I don't think the current feed is a good change to that end.

I propose that the feed is removed and replaced with random inspirational posters.
Each poster should feature at least one kitten, more are allowed but cuteness is more important than quantity of the kittens.

The posters should have messages that feel personal and relevant to the current state of my GitHub account.

A quick mockup : 

<img width="1470" alt="Screenshot 2023-09-06 at 23 20 36" src="https://github.com/community/community/assets/11521496/28e23491-50ab-4d79-b0c6-afefefe88b33">

-------

jokes aside, I do appreciate the time and effort that goes into every feature that is created at GitHub.

What would help me the most is a personal todo list.

A scratch pad where I can list some stuff, cross some stuff of,...

Like a random piece of paper, but I won't lose it.

The space currently occupied by the feed would be perfect for that.

**Comment by leeoniya** [comment]
i already find the static mockup more useful than the new feed. :shipit:

**Comment by beeman** [comment]
I prefer this over the 'For You' tab.

And I don't even like kittens.

**Comment by dzaima** [comment]
Userstyle mockup:
```css
div[data-target="feed-container.content"] * {
  display:none;
}
div[data-target="feed-container.content"] {
  background-image: url("https://raw.githubusercontent.com/your_favorite_cat_image_here") !important;
  width: 60%;
  margin: auto;
  height: 2000px;
  background-size: contain;
  background-repeat: no-repeat;
}
```
I'm.. actually keeping this on for now, it doesn't decrease the amount of information in my feed at least.
