### DISCUSSION TITLE
How to add an edited action with workflow_dispatch to action availability.

### DISCUSSION THREAD

**Discussion by RonShvarz** [community/community#66279] [Actions]
### Select Topic Area

Question

### Body

I am making changes to a previously ran action, in which i want to allow it to run manually using 
```
  workflow_dispatch:
    inputs:
      image-ref:
        description: Full docker image path (e.g. docker.io/hkube/site:v1.2.3)
        required: false
        default: 'docker.io/hkube/site:latest'
```

It won't show up, and i understood it needs to run once successfully before it becomes available, 
the issue at hand is it will fail untill it is ran manually and provided with the value above - image-ref.

File url is :
https://github.com/kube-HPC/kube-HPC.github.io/pull/48/files#diff-86074bc26083ca63c88e706d230f9cfebe66f21be849a202ed1fbd450a0c0996
Would love to understand what is the correct order of things in order to add a new action with worflow_dispatch dependancy.

Thanks in advance.
