### DISCUSSION TITLE
Possible Undocumented "Pending" State in Check Suite API Response

### DISCUSSION THREAD

**Discussion by Avenel** [community/community#66341] [Actions]
### Select Topic Area

Product Feedback

### Body

Hello,

I have come across an anomaly regarding the Check Suite API response that's not included in the official [API documentation](https://docs.github.com/en/rest/checks/suites?apiVersion=2022-11-28#get-a-check-suite). The documented states for Check Suite API response are "queued", "in_progress", and "completed". However, I have encountered an additional state, namely "pending".

This "pending" state can be induced by implementing a concurrency within a workflow. This action prevents the same workflow from being executed simultaneously. Here's an example of how this might be set up in YAML:

```
name: Do something

on:
  push:
    branches:
    - main
    
concurrency: test

jobs:
  one:
    runs-on: ubuntu-latest
    name: Do it
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Wait
      run: |
        sleep 120
```

When this workflow is triggered twice, the API response includes the "pending" state:

```
{
  "id": 9170123123,
  "node_id": "CS_kwSOJbvS3c8AAAADsy2zEw",
  "head_branch": "main",
  "head_sha": "3bcc59988530adbb6e031f1b526a763e7418d920",
  "status": "pending",
  "conclusion": null,
  "url": "https://api.github.com/repos/my-test-repo/wf-test/check-suites/15291018543",
  ...
  "pull_requests": [],
  "app": {
    "id": 15238,
    "slug": "github-actions",
    ...
  }
}

```

I'm intrigued if this "pending" state is actually present in the source code but might have been omitted from the OpenAPI definition. Could you clarify this matter, please?

Thank you in advance for looking into this.

Best Regards.
