### DISCUSSION TITLE
Variables in code

### DISCUSSION THREAD

**Discussion by Vitminee** [community/community#66401] [Actions]
### Select Topic Area

Question

### Body

I can use secret variables in the code and then in GitHub actions insert secret and send via FTP?
I am using this script 
```
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: 21
        protocol: ftp
        server-dir: /gymcl.tk/
        state-name: web/.ftp.json
        exclude: |
          **/.git/**
          **/.github/**
          README.md
```
But on the FTP server is still this 
```
<?php
/* Database credentials. Assuming you are running MySQL
server with default setting (user 'root' with no password) */
define('DB_SERVER', 'localhost');
define('DB_USERNAME', '${{ secrets.LOGIN_CHAT_NAME }}');
define('DB_PASSWORD', '${{ secrets.LOGIN_CHAT_PASS }}');
define('DB_NAME', '${{ secrets.LOGIN_CHAT_NAME }}');
 
/* Attempt to connect to MySQL database */
$link = mysqli_connect(DB_SERVER, DB_USERNAME, DB_PASSWORD, DB_NAME);
 
// Check connection
if($link === false){
    die("ERROR: Could not connect. " . mysqli_connect_error());
}
?> 
```
Secrets in code not inserted
