### DISCUSSION TITLE
Cache saved from the `merge_group` to `main` event can't be restored on future PRs to `main`

### DISCUSSION THREAD

**Discussion by yogurtearl** [community/community#66430] [Pull Requests]
### Select Topic Area

Product Feedback

### Body

Let's say I have Merge Queues enabled for the `main` branch. 

If I save via `actions/cache` from the `merge_group` triggered workflow (targeting the `main` branch), best I can tell, I can NOT restore those caches in a future PR, because they where created on `merge_group` for `main`  and not `push` for `main`. 

Seems related to these restrictions: 
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

**Feature request:** allow storing to cache on `merge_group` to `main` and then restoring those caches on future PRs to `main`. 

This allows us to avoid having to run some workflows on `push` to `main` when then are redundant with the workflows that are running via `merge_group`

```yaml
on:
  # would like to save to cache here, and then restore it on PRs:
  merge_group:
  # for some use cases, would like to avoid this 👇 trigger altogether and just use the cache from `merge_group` in future PRs
  push:
    branches:
      - main
```
