### DISCUSSION TITLE
How to run a workflow after another has completed?

### DISCUSSION THREAD

**Discussion by jwerre** [community/community#66512] [Actions] [answered]
### Select Topic Area

Question

### Body

I have two workflows: Validate and Deploy. I'd like validate  to run when there is a push to any branch but I'd only like deploy to run after validate has completed successfully *and* when the branch is 'beta'. My workflow yaml files look like this at the moment:

### validate.yml

```yaml
name: Validate

# always validate on every push.
on: 
    - push

jobs: [ run lint and unit tests etc ...]

```

### deploy.yml

```yaml
name: Deploy


# run after validate workflow has completed and the current branch is 'beta'
on:
    workflow_run:
        workflows: ['Validate']
        types: [completed]
        branches:
            - 'beta'

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps: [ deploy project ...]
```

My problem is that `Validate` is running but `Deploy` is not. What am I doing wrong here?
