### DISCUSSION TITLE
How to use secrets in GitHub pages?

### DISCUSSION THREAD

**Discussion by lethargistic** [community/community#66648] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

I'm looking to get my API key on Github pages and use it, I couldn't figure out anything myself and all tutorials lead to using `process.env.INSERT_KEY_NAME` in Node.js however according to this [thread](https://github.com/orgs/community/discussions/22507) using Node.js with GitHub pages is impossible and getting the key in front-end javascript doesn't seem possible aswell.

How do I use secrets? Am I missing something?

**Comment by seyLu** [comment, marked as answer]
#### Hi @maksiksking 

Yes, Github Pages is a static hosting site as metioned in the [thread you mentioned](https://github.com/orgs/community/discussions/22507). You can host the node.js web app/api on another hosting platform that supports node.js (eg. [heroku](https://www.heroku.com/), [render](https://render.com/), etc.). And have the frontend that consumes the api hosted in github pages.

Secrets are mainly used for Github Actions. Github Actions are used for CI/CD pipelines -- in simple terms, it's used to automate stuff like testing, linting, build & deploy, etc. when an event in Github triggers.

Secrets allow you to store sensitive information such as tokens that limit the permissions of these workflows. These automated workflows may need additional permission to access/modify certain stuff for example, but you don't want them to have admin access that they can just delete your repo. See example workflow snippet:

```yaml
# sample workflow snippet
steps: 
  - name: Build and deploy
    working-directory: ./app
    run: npm run deploy
    env:
      token: ${{ secrets.DEPLOY_TOKEN }}
       # deploy token is used to build and deploy to a gh-pages branch 
       # (needs permission to create a branch, build the app and modify that branch, 
       # push changes to that branch, and deploy to github pages)
```

You can read more at the Github official docs: [Using secrets in Github Actions](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)
