### DISCUSSION TITLE
Does `secrets: inherit` need to have the secrets with the same name

### DISCUSSION THREAD

**Discussion by copdips** [community/community#66654] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

Hello,

From the [doc](https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow), 

We can transform the syntax of:

```yaml
jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
```

to: 

```yaml
jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit
```

Shall we have the same name of the secret in the caller workflow ? Which means `secrets.envPAT` ? otherwise it will raise error in the calling reusable-workflow.yml ?
