### DISCUSSION TITLE
Mechanism to add metadata/context to the workflow run

### DISCUSSION THREAD

**Discussion by rochana-atapattu** [community/community#66660] [Actions]
### Select Topic Area

Product Feedback

### Body

There is no why for us to identify manually trigger workflow runs as I have mentioned [here](https://github.com/orgs/community/discussions/65735) for.

- workflow_dispatch
- repository_dispatch

 It would we really helpful if we can receive  a context of the unique identifier of the triggered event and correlate it with a workflow run ID, also passing this context to webhook events will also be helpful for integrations.

We have to resort to crude methods like this to pass the context
```
on:
  repository_dispatch:
    types:
      - pullrequest
run-name: MyWorkflowName [ID:${{ github.event.client_payload.id }}]
```
Also mentioned in [issue](https://github.com/cli/cli/issues/4001)
