### DISCUSSION TITLE
When setting "packages: write" permission in Github Action to publish the cache to Github Nuget Registry, reading from the registry fails with 403

### DISCUSSION THREAD

**Discussion by GasimGasimzada** [community/community#66683] [Packages]
### Select Topic Area

Question

### Body

This question is related to both Github Actions and Github Packages

I have a job in Github actions where I am building packages using vcpkg and publishing the generated packages to Github Nuget Registry. So, I have set the following in my job:

```yaml
  build-dependencies:
    name: Build dependencies
    permissions:
      packages: write
   # ...
```

I initially thought that when I set `write`, `read` is implied from it but after testing it out, I realized that if I set the permission to `write`, I cannot read from the packages. Here is how I am trying to install and and publish to the registry:

```yaml
# Github action
inputs:
  triplet:
    description: Triplet
    required: true
  mono:
    description: Mono prefix for linux
    required: true
  token:
    description: Github token
    required: true
env:
  NUGET_SOURCE: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
run: |
  alias nuget="${{ inputs.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`"
  nuget sources remove -name nuget.org

  nuget sources add \
    -name "GitHub" \
    -source "$NUGET_SOURCE" \
    -username "${{ github.repository_owner }}" \
    -password "${{ inputs.token }}" \
    -storepasswordincleartext 

  nuget setapikey "${{ inputs.token }}" -source "$NUGET_SOURCE"

  ./vcpkg/vcpkg Install --triplet ${{ inputs.triplet }} --debug 
  
# Usage
runs-on: ${{ matrix.os }}
steps:
  - uses: actions/checkout@v4
  - uses: ./.github/actions/install-dependencies
    with:
      triplet: ${{ matrix.triplet }}
      mono: ${{ matrix.mono }}
      token: ${{ secrets.GITHUB_TOKEN }}
```

If I change to `permissions: read`, read works but write fails.
