### DISCUSSION TITLE
When setting "packages: write" permission in Github Action to publish the cache to Github Nuget Registry, reading from the registry fails with 403

### DISCUSSION THREAD

**Discussion by GasimGasimzada** [community/community#66682] [Actions]
### Select Topic Area

Question (possibly a Bug)

### Body

This question is related to both Github Actions and Github Packages

I have a job in Github actions where I am building packages using vcpkg and using the binarycaching to publish the packages to Github Nuget Registry. So, I have set the following in my job:

```yaml
build-dependencies:
  name: Build dependencies
  permissions:
    packages: write
# Matrix removed to keep the snippet smaller
runs-on: ${{ matrix.os }}
steps:
  - uses: actions/checkout@v4
  - uses: ./.github/actions/install-dependencies
    with:
      triplet: ${{ matrix.triplet }}
      mono: ${{ matrix.mono }}
      token: ${{ secrets.GITHUB_TOKEN }}
```

I initially thought that when I set `write`, `read` is implied from it but after testing it out, I realized that if I set the permission to `write`, I cannot read from the registry. Here is how I am trying to install and and publish to the registry:

```yaml
env:
  NUGET_SOURCE: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,read"
  VCPKG_USE_NUGET_CACHE: true
run: |
  alias nuget="${{ inputs.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`"
  nuget sources remove -name nuget.org

  nuget sources add \
    -name "GitHub" \
    -source "$NUGET_SOURCE" \
    -username "${{ github.repository_owner }}" \
    -password "${{ inputs.token }}" \
    -storepasswordincleartext 

  nuget setapikey "${{ inputs.token }}" -source "$NUGET_SOURCE"

  # Using vcpkg binarycaching
  ./vcpkg/vcpkg Install --triplet ${{ inputs.triplet }} --debug 
```

If I change to `permissions: read`, read works but write fails. What am I doing wrong here?

I am using a public organization and repository with package creation set to private at organizational level.

**Comment by GasimGasimzada** [comment]
**Update:** Maybe I am missing something here but this seems to be a bug because I created a personal access token with `packages:write` permission and used the token for authentication with nuget registry and everything seemed to work.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by tangturtle** [comment]
I have the same issue. I used a personal classic token with `packages: read/write`, and when using `nuget` on my private repository, I can read but cannot write to `nuget`. Below is my `github action` log:

I replaced my username with "???".

```TXT
[DEBUG] 1230: cmd_execute_and_stream_data() returned 0 after   654696 us
7467
[DEBUG] 1232: execute_process(/usr/bin/mono /home/runner/work/sast-readium-CI/sast-readium-CI/vcpkg/downloads/tools/nuget-6.10.0-linux/nuget.exe push -ForceEnglishOutput -Verbosity detailed -NonInteractive /home/runner/work/sast-readium-CI/sast-readium-CI/vcpkg/buildtrees/libb2_x64-linux.0.98.1-vcpkg9ac5315f0508d9f07543f65863c2094bddc9dd35d037007d9e0628b9f9826f8e.nupkg -Timeout 100 -Source https://nuget.pkg.github.com/???/index.json)
7468
NuGet Version: 6.10.0.107
7469
Pushing libb2_x64-linux.0.98.1-vcpkg9ac5315f0508d9f07543f65863c2094bddc9dd35d037007d9e0628b9f9826f8e.nupkg to 'https://nuget.pkg.github.com/???'...
7470
  PUT https://nuget.pkg.github.com/???/
7471
WARNING: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
7472
  Forbidden https://nuget.pkg.github.com/???/ 369ms
7473
Response status code does not indicate success: 403 (Forbidden).
7474
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
7475
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () [0x00046] in <3588d5c507ec48a6b5d13a6d5ae64da2>:0 
7476
  at NuGet.Protocol.Core.Types.PackageUpdateResource.EnsureSuccessStatusCode (System.Net.Http.HttpResponseMessage response, System.Nullable`1[T] codeNotToThrow, NuGet.Common.ILogger logger) [0x00044] in <b870c412959345c6b2ace6896ca5f118>:0 
7477
  at NuGet.Protocol.Core.Types.PackageUpdateResource+<>c__DisplayClass26_0.<PushPackageToServer>b__0 (System.Net.Http.HttpResponseMessage response) [0x00000] in <b870c412959345c6b2ace6896ca5f118>:0 
7478
  at NuGet.Protocol.HttpSource.ProcessResponseAsync[T] (NuGet.Protocol.HttpSourceRequest request, System.Func`2[T,TResult] processAsync, NuGet.Protocol.Core.Types.SourceCacheContext cacheContext, NuGet.Common.ILogger log, System.Threading.CancellationToken token) [0x000f5] in <b870c412959345c6b2ace6896ca5f118>:0 
7479
  at NuGet.Protocol.Core.Types.PackageUpdateResource.PushPackageToServer (System.String source, System.String apiKey, System.String pathToPackage, System.Boolean noServiceEndpoint, System.Boolean skipDuplicate, System.TimeSpan requestTimeout, System.Boolean warnForHttpSources, System.Boolean allowInsecureConnections, NuGet.Common.ILogger logger, System.Threading.CancellationToken token) [0x004be] in <b870c412959345c6b2ace6896ca5f118>:0 
7480
  at NuGet.Protocol.Core.Types.PackageUpdateResource.PushPackageCore (System.String source, System.String apiKey, System.String packageToPush, System.Boolean noServiceEndpoint, System.Boolean skipDuplicate, System.TimeSpan requestTimeout, System.Boolean warnForHttpSources, System.Boolean allowInsecureConnections, NuGet.Common.ILogger log, System.Threading.CancellationToken token) [0x00181] in <b870c412959345c6b2ace6896ca5f118>:0 
7481
  at NuGet.Protocol.Core.Types.PackageUpdateResource.PushPackagePath (System.String packagePath, System.String source, System.String symbolSource, System.String apiKey, System.Func`2[T,TResult] getSymbolApiKey, System.Boolean noServiceEndpoint, System.Boolean skipDuplicate, NuGet.Protocol.Core.Types.SymbolPackageUpdateResourceV3 symbolPackageUpdateResource, System.Boolean allowInsecureConnections, System.TimeSpan requestTimeout, NuGet.Common.ILogger log, System.Threading.CancellationToken token) [0x0016f] in <b870c412959345c6b2ace6896ca5f118>:0 
7482
  at NuGet.Protocol.Core.Types.PackageUpdateResource.Push (System.Collections.Generic.IList`1[T] packagePaths, System.String symbolSource, System.Int32 timeoutInSecond, System.Boolean disableBuffering, System.Func`2[T,TResult] getApiKey, System.Func`2[T,TResult] getSymbolApiKey, System.Boolean noServiceEndpoint, System.Boolean skipDuplicate, NuGet.Protocol.Core.Types.SymbolPackageUpdateResourceV3 symbolPackageUpdateResource, System.Boolean allowInsecureConnections, NuGet.Common.ILogger log) [0x0014e] in <b870c412959345c6b2ace6896ca5f118>:0 
7483
  at NuGet.Commands.PushRunner.Run (NuGet.Configuration.ISettings settings, NuGet.Configuration.IPackageSourceProvider sourceProvider, System.Collections.Generic.IList`1[T] packagePaths, System.String source, System.String apiKey, System.String symbolSource, System.String symbolApiKey, System.Int32 timeoutSeconds, System.Boolean disableBuffering, System.Boolean noSymbols, System.Boolean noServiceEndpoint, System.Boolean skipDuplicate, NuGet.Common.ILogger logger) [0x003da] in <b870c412959345c6b2ace6896ca5f118>:0 
7484
  at NuGet.CommandLine.PushCommand.ExecuteCommandAsync () [0x0017c] in <b870c412959345c6b2ace6896ca5f118>:0 
7485
  at NuGet.CommandLine.Command.Execute () [0x0014a] in <b870c412959345c6b2ace6896ca5f118>:0 
7486
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) [0x001ee] in <b870c412959345c6b2ace6896ca5f118>:0 
  ```

This is my workflow file:
```YML
name: CI (CMake Presets + vcpkg)

on:
    push:
    pull_request:

permissions:
    contents: write
    packages: write

env:
    VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
    VCPKG_FEATURE_FLAGS: dependencygraph
    USERNAME: ???
    FEED_URL: https://nuget.pkg.github.com/???/index.json
    VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/???/index.json,readwrite"

jobs:
    build_on_linux:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
                 ......
 
          - name: Install dependencies
                  ......

          - name: Install cmake and ninja
                ......

          - name: Install vcpkg
            uses: lukka/run-vcpkg@v11
            with:
                vcpkgJsonGlob: '**/vcpkg.json'
                runVcpkgInstall: false

          - name: Bootstrap vcpkg
            shell: bash
            run: |
                ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

          - name: Add NuGet sources
            shell: bash
            env:
                VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
                USERNAME: ???
                FEED_URL: https://nuget.pkg.github.com/???/index.json
            run: |
                mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
                sources add \
                -Source "${{ env.FEED_URL }}" \
                -StorePasswordInClearText \
                -Name GitHubPackages \
                -UserName "${{ env.USERNAME }}" \
                -Password "${{ secrets.GH_PACKAGES_TOKEN }}"
                mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
                setapikey "${{ secrets.GH_PACKAGES_TOKEN }}" \
                -Source "${{ env.FEED_URL }}"

          - name: Install dependencies via vcpkg
            run: vcpkg install --debug --binarysource="clear;nuget,${{env.FEED_URL}},readwrite"
            env:
                VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
                VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
                VCPKG_FEATURE_FLAGS: dependencygraph
                GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

          - name: Build
            uses: lukka/run-cmake@v10
            with:
                configurePreset: Release-Unix
                buildPreset: Release-Unix


```
