### DISCUSSION TITLE
Initialize containers step failing with error “Docker login for ghcr.io failed with exit code 1”

### DISCUSSION THREAD

**Discussion by chandrakanthbala** [community/community#66719] [Actions]
I'm running a workflow with a container on self hosted runner. And the container I'm using is hosted on GHCR. Sometimes the workflow is failing at step "Initialize containers" with docker login to ghcr failed error. This is occurring intermittently and I'm not able to reproduce it on demand. I tried to pass the credentials like below, but that didn't help.

```
job: 
  runs-on: self-hosted 
  container:
    image: ghcr.io/image:tag
    credentials: 
      username: ${{github.respository_owner}}
      password: ${{secrets.GITHUB_TOKEN}}
```
What could be the reason for this error? 
Runner Version: 2.292.0
