### DISCUSSION TITLE
How to get the branch name that triggered a workflow_run?

### DISCUSSION THREAD

**Discussion by jwerre** [community/community#66784] [Actions]
### Select Topic Area

Question

### Body

I've set up a [`workflow_run`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) that is triggered when another workflow is completed *and* if the branch is either `main` or `beta`. Like this:

```yaml
on:
    workflow_run:
        workflows:
            - Test
        types:
            - completed
        branches:
            - beta
            - main
```

I'd like to do different things depending on wether the branch is `beta` or `main` but when I get the branch with `${{ github.head_ref || github.ref_name }} ` it seems to always be `main` even when I push to the `beta` branch. Is there a way to get the correct branch name in a `workflow_run`?
