### DISCUSSION TITLE
Why do I only see the readme.md file when I go deploy the github page for my react app?

### DISCUSSION THREAD

**Discussion by anitachu99** [community/community#66794] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I followed the github page deployment tutorial but at the end I only see the readme file after deploying with the script "npm run deploy". I also have set the branch to "gh-pages" and the folder to be "/(root)". Any help is appreciated!

Here is my repository link: 
https://github.com/anitachu99/FurEverHome_1.0

**Comment by seyLu** [comment]
Hi @anitachu99,

The deployment workflow failed. Thus, reverting back to the previous successful build. 

You can think of github actions as a separate computer running commands in the cloud (so it doesn't have the same stuff that is in your local machine). NPM is a node package manager so it cannot exist without Node.
![image](https://github.com/community/community/assets/98249191/63906e24-4990-49c3-8c0a-528c06a5dc14)

You forgot some steps, after checking out the branch, we then setup Node, specify the version (maybe also cache it for faster workflow runs), then install proj dependencies. Then we can safely call the deploy script. See sample workflow snippet:
```yaml
- name: Checkout repository
  uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v3.5.3

- name: Set up Node ${{ matrix.node-version }}
  uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.7.0
  with:
    node-version: ${{ matrix.node-version }}
    cache: 'npm'
    cache-dependency-path: ./app/package-lock.json

- name: Install Dependencies
  working-directory: ./app
  run: npm ci --prefer-offline

- name: Build & Deploy
  working-directory: ./app
  run: npm run deploy
```

**Reply by anitachu99** [reply]
I'm sorry I'm a beginner when it comes to deploying websites so I hope you don't mind I ask some more questions. I don't really understand the workflow snippet and what to do in order to achieve what you are explaining. Which branch am I checking out of? Also I have node installed so I am wondering why I need to setup node and what type of dependencies do I have to install?

**Reply by seyLu** [reply]
My bad, it's a bad habit of mine.

Ignore the prev snippet, let's dumb it down:

```yaml
# Just think of this step as
# kinda like doing git clone but in
# another computer somewhere in the cloud
- name: Checkout branch
  uses: actions/checkout@v3

# This step will install the latest node version
# into the computer that is running this
# workflow. Even though you have node
# installed in the computer you're
# using, this is not your computer. So
# stuff you have like node doesn't exist
# in this computer that is running this action.
- name: Setup Node
  uses: actions/setup-node@v3
  with:
    node-version: latest

# When I checked the error logs in the action
# that failed, the error was react-scripts
# is not recognized or something. The
# reason for that is that the npm dependencies are not
# installed. Why? Again, because this is
# not your computer. So after setting up node,
# then and only then can you use npm
# to install the dependencies of your project.
- name: Install Dependencies
  run: npm install

# Once everything is set up in this other
# computer, it is now safe to build and
# deploy site to github pages
- name: Build and deploy
  run: npm run deploy
```

If you have any more questions/clarifications, don't be afraid to ask. Just remember, there are no such things as dumb questions, they're just questions. I'm here to help, and I'm sure other devs in this community are too.
