### DISCUSSION TITLE
Does dependabot.yml have .github repo support?

### DISCUSSION THREAD

**Discussion by KonradHoeffner** [community/community#66869] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

Can I put a `.github/dependabot.yml` in my organization's `.github` repo or my personal `username` repo to enable a default configuration for all repositories in that organization, respectively repository?

I could not find an answer both in [official](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) and [unofficial](https://devopsjournal.io/blog/2021/11/26/GitHub-magic-files) sources.

It would be great if this could be clearly stated in the [official](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) docs and if it is not yet possible if this could be implemented.

As an exemplary use case, I manage all my GitHub action versions with the same dependabot.yml and it gets cumbersome to do that for nearly 100 repositories:

```yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
