### DISCUSSION TITLE
Self hosted runner: Docker Proxy troubles

### DISCUSSION THREAD

**Discussion by floli** [community/community#66874] [Actions]
### Select Topic Area

Question

### Body

Hello,

I have a workflow to build a docker image:

```yaml
jobs:
  BuildDockerImage:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with: [...]
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "docker"
          push: true
          tags: latest
```

In the `docker` subdirectory, there is a simple `Dockerfile`

```
FROM ubuntu:focal
RUN apt update && apt install -y curl
ENTRYPOINT /usr/bin/bash
```
which build and runs fine using `docker build .` and `docker run -it`. However, when executed in the same environment in the self-hosted runner it fails with proxy trouble:

```
ERROR: failed to solve: ubuntu:focal: failed to do request: Head "https://registry-1.docker.io/v2/library/ubuntu/manifests/focal": dial tcp: lookup registry-1.docker.io on 10.58.195.11:53: no such host
##[error]buildx failed with: ERROR: failed to solve: ubuntu:focal: failed to do request: Head "https://registry-1.docker.io/v2/library/ubuntu/manifests/focal": dial tcp: lookup registry-1.docker.io on 10.58.195.11:53: no such host
```

The repo is located at a self-hosted GitHub enterprise installation. The self-hosted runner needs to use a proxy to access the internet, but it is aware of that:

```
Runner is running behind proxy server 'http://127.0.0.1:3128/' for all HTTP requests.
Runner is running behind proxy server 'http://127.0.0.1:3128/' for all HTTPS requests.
```

and bulding the docker locally works just fine. The proxy information is set in the environment variables 

Any more ideas what could be the problem here?

Thanks a lot!
