### DISCUSSION TITLE
github issue template - not adding to project

### DISCUSSION THREAD

**Discussion by JamesRivers** [community/community#66878] [Projects and Issues]
### Select Topic Area

Question

### Feature Area

Issues

### Body

I am using a github template as follows: 

```
name: 'ACCOUNT-ITEM'
about: Action required on account.
title: ''
labels: "ACC-ISSUE"
assignees: johnsmith
projects: daily
```
Everything is acted on in this template - except for the allocation of the project to the issue... Projects just remains unlinked. 

Using gh to create issue from cli.  

Any thoughts? 

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).

**Comment by ryanmio** [comment]
GitHub's issue templates don't natively support automatic project assignment but you can use GitHub Actions as a workaround to automatically add new issues to a specific project.

Here's a sample GitHub Actions YAML:

```yaml
name: Add to Project
on:
  issues:
    types: [opened]
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add issue to project
      run: |
        gh api -X POST /projects/columns/COLUMN_ID/cards -H "Accept: application/vnd.github.inertia-preview+json" -F "content_id=${{ github.event.issue.id }}" -F "content_type=Issue"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Replace COLUMN_ID with the ID of the project column you want the issue to be added to.

For more information, see the [GitHub API documentation on projects](https://docs.github.com/en/rest/reference/projects#cards).

Also make sure to give your GitHub Action permission to write to projects.
