### DISCUSSION TITLE
CodeQL and default branch

### DISCUSSION THREAD

**Discussion by flagrant99** [community/community#66894] [Code Security] [answered]
### Select Topic Area

Question

### Body

Are we supposed to only run CodeQL workflow  against the default branch? 

I am trying to set up CodeQL workflow on a new non default branch. And nothing seems to work right..

If I click on code scanning button it keeps filtering by is:open branch:master regardless of the branch I am in now. 
I can't add a button to manually run CodeQL work flow to non default branch?
My screen shots don't match documentation.  Where is tools status page. I can't find it. 
"The analyze action will upload your database automatically after the analysis completes. But it will only do this on the default branch."

Is CodeQL workflow only meant to be run on default branch?

**Comment by aregtech** [comment]
I'm not sure, but if I understood you in the right way, you are asking whether you can run the _CodeQL_ on a push to any branch, right?

Yes you can. At the begging of action workflow, you have instructions where to run and when to run, [like this](https://github.com/aregtech/areg-sdk/blob/master/.github/workflows/codeql-analysis.yml):
```
name: "CodeQL"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main]
  schedule:
    - cron: '32 22 * * 1'
```
If you want to run the _CodeQL_ on any branch and on each push, replace the displayed part to this:
```
name: "CodeQL"

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main]
```

As you notice, I removed branch information `branches: [ main ]`, but left for PR. By this, it will be triggered by each _push_.

I hope, I understood you in the right way and this helped you.
