### DISCUSSION TITLE
Update Status Badge for Reusable Workflows triggered via Workflow_call

### DISCUSSION THREAD

**Discussion by Hyperclaw79** [community/community#66910] [Actions]
### Select Topic Area

Product Feedback

### Body

Currently, the only we to update the status in a status badge for a reusable workflow is either to run it on push or via workflow_dispatch. It would be nice if the status updates even when the workflow is run as part of workflow_call by another workflow.

**Comment by hoanganhminh** [comment]
The behavior you've described regarding status badges in reusable workflows is indeed the current default behavior in GitHub Actions. Status badges in a reusable workflow typically reflect the status of the workflow run when it is directly triggered, either on push or via a manual trigger (`workflow_dispatch`). 

However, there is a workaround to achieve what you're looking for. You can use a combination of GitHub Actions workflow outputs and a separate workflow to update the status badge.

Here are the general steps:

1. **Update the Reusable Workflow:** Modify your reusable workflow to output the status or any other relevant information using `set-output`. For example:

   ```yaml
   steps:
     - name: Run some steps
       # ...

     - name: Set Status Output
       id: set-status
       run: echo "::set-output name=status::success"
   ```

2. **Update the Workflow That Calls the Reusable Workflow:** In the workflow that calls the reusable workflow using `workflow_run`, capture the output from the reusable workflow using the `outputs` context:

   ```yaml
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: Trigger Reusable Workflow
           uses: actions/checkout@v2
           with:
             ref: main
           # Trigger the reusable workflow
           run: |
             repo_token="${{ secrets.GITHUB_TOKEN }}"
             workflow_file="path/to/reusable-workflow.yml"
             payload="{\"ref\": \"main\", \"inputs\": {}}"
             response=$(curl -X POST "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${workflow_file}/dispatches" \
               -H "Authorization: Bearer $repo_token" \
               -H "Accept: application/vnd.github.v3+json" \
               -d "$payload")
             echo "$response"
           id: reusable

         - name: Update Status Badge
           if: ${{ success() }}
           run: echo "::set-output name=status::success"
           # This sets the status to 'success' if the reusable workflow was successful
           # You can adapt this based on your needs
   ```

3. **Update the Status Badge in README or elsewhere:** Finally, update your status badge in your README or wherever it's displayed using the output from the previous step:

   ```markdown
   ![Status Badge](https://img.shields.io/badge/Status-${{ steps.build.outputs.status }}-green)
   ```

This approach allows you to capture the status of the reusable workflow and update your status badge accordingly, even when the reusable workflow is run as part of `workflow_run` by another workflow.

Make sure to adapt the example code to your specific use case and requirements.
