### DISCUSSION TITLE
Can a CodeQL workflow produce sarif file?

### DISCUSSION THREAD

**Discussion by flagrant99** [community/community#67038] [Code Security] [answered]
### Select Topic Area

Question

### Body

Here is my code ql workflow. It runs fine and I get a 1 GB CodeQL database download link from the action page. Can It produce sarif output download links to sarif file(s)? How do I get the sarif produced from this run? NOTE: I cannot run under master "default" branch. I want to be able to download it just like the artifact for the database. Do I need to add some kind of upload command for the workflow? 

```
name: "CodeQL"

on:
  workflow_dispatch:
  push:
    branches: [ "releases/**" ]    

jobs:
  analyze:
    name: Analyze
    runs-on: [ GITBUILD1STL ]
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp', 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        db-location: ./codeql_output/
        languages: ${{ matrix.language }}

    # We must compile CSharp for CodeQL to analyze it
    - name: 👟Write GitHub Runner Context
      working-directory: ${{env.GITHUB_WORKSPACE}}
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        Write-Output $env:GITHUB_CONTEXT | Out-File -FilePath .\github_context.json -Force;
        
       
    - name: 🔨 BuildQL
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: pwsh .\Build\DoCodeQLBuild.ps1
     
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

    - uses: actions/upload-artifact@v3
      with:
        name: CodeQLArtifact
        path: ./codeql_output/
        
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
```

**Comment by aibaars** [comment]
I think the [`sarif-output`](https://github.com/github/codeql-action/blob/8e0b1c74b1d5a0077b04d064c76ee714d3da7637/analyze/action.yml#L82-L83) property is what you are looking for 

```yaml
  sarif-output:
    description: Absolute, local path to the directory containing the generated SARIF file.
```
I think something like this should work:
```yaml
...
    - name: Perform CodeQL Analysis
      id: analyze
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

    - uses: actions/upload-artifact@v3
      with:
        name: CodeQLSARIF
        path: ${{ steps.analyze.outputs.sarif-output }}
```
