### DISCUSSION TITLE
Actions not respecting Makefile &&

### DISCUSSION THREAD

**Discussion by C-Williams** [community/community#67099] [Actions]
### Select Topic Area

Question

### Body

Sorry for the rather provocative title, I couldn't think of a more succinct way to summarize my issue.

I am attempting to build a project using GitHub Actions and am running into a strange issue. My workflow yml looks a bit like this:

```
name: run-tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EventsMiddleware Repo
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Prereqs
        run: |
          docker pull something
          pip3 install something else
      - name: Setup Tests
        run: |
          make test-setup
      - name: Run Tests
        run: |
          make test
```

In my Makefile, I have a task that looks like this:
```
unit-test-postgres:
	echo '--- Postgres Unittests ---' && \
	psql -X 'dbname=postgres host=127.0.0.1 user=postgres password=postgres port=5434' -f sql/recreate_database_structure.sql &> /dev/null && \
	docker exec -e PROFILE=1 -w /var/task postgres_test python3 -m unittest discover -s tests -p test*.py && \
	echo "-----------------------"
```

The basic process is that we setup some containers, one of which is a postgres container. Then unit tests are run which fill in that container. 

When run in the GitHub Actions, the docker exec line executes before the the database structure has been completely filled. This causes an error because the table doesn't exist when the unit test is run. 

According to the syntax here, I would have thought the `&& \` line prevented this from happening.

When I modify the above Makefile task to the below code, everything functions with no errors (NOTE: The only difference is the inclusion of `sleep 5`).
```
unit-test-postgres:
	echo '--- Postgres Unittests ---' && \
	psql -X 'dbname=postgres host=127.0.0.1 user=postgres password=postgres port=5434' -f sql/recreate_database_structure.sql &> /dev/null && \
	sleep 5 && \
	docker exec -e PROFILE=1 -w /var/task postgres_test python3 -m unittest discover -s tests -p test*.py && \
	echo "-----------------------"
```

Does anyone know what is going on here?
