### DISCUSSION TITLE
github actions run a job on pull request merge to specific branch

### DISCUSSION THREAD

**Discussion by ash-dey-sa** [community/community#67160] [Actions] [answered]
### Select Topic Area

Question

### Body

0

I am trying to run a job within github actions workflow with the following condition. My aim is to run the job if a pull request to develop branch is merged. However, when I merge a pull reqest to develop branch, the job is skipped. Can someone pl point me what I may be doing wrong?

```
on:
  push:
  pull_request:
    branches:
      - develop
      - main
      - test
      - feature
  workflow_dispatch:
```

and then the condition for the specific job

`    if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}`

If I change the heads to base in the above if condition, its still the same result i.e. the job is skipped.

**Comment by P-mistry** [comment]
Indentation and Syntax: Make sure your YAML file has the correct indentation and syntax. YAML is whitespace-sensitive, so any indentation issues can cause problems.

Workflow Name: Ensure that the specific job you want to run has a unique name within your workflow. GitHub Actions requires jobs to have unique names in a workflow.

Workflow YAML Structure: Your YAML structure for the on section should be indented correctly. It should be at the same level as your job definitions. Here's the corrected YAML:

on:
  push:
    branches:
      - develop
      - main
      - test
      - feature
  pull_request:
    branches:
      - develop
      - main
      - test
      - feature
  workflow_dispatch:
and then 
Check Event Payload: Ensure that the pull request you're merging is indeed targeting the develop branch. The condition github.ref == 'refs/heads/develop' checks if the event is happening on the develop branch.

Check Action Trigger: Verify that you are merging the pull request correctly. The condition github.event.action == 'closed' && github.event.pull_request.merged == true checks if the pull request was closed and merged.

Debugging: You can add some debug output to your workflow to see the values of these variables during the workflow run. For example:

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Variables
        run: |
          echo "github.ref = ${{ github.ref }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.pull_request.merged = ${{ github.event.pull_request.merged }}"
This will help you see the values of these variables and debug any issues with your conditions.

Workflow Logs: Check the logs of your workflow runs in the GitHub Actions tab. It should provide information on why a job was skipped if it indeed was skipped.
By checking these points and debugging the workflow as needed, you should be able to identify why your job is not running as expected when a pull request to the develop branch is merged.

**Comment by elendil7** [comment, marked as answer]
### Option [1]
Hello. A potential workaround could be **removing** the following snippet:
`if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}` 
And instead relying solely on the following configuration:

```yaml
on:
  pull_request:
    # For the develop branch only.
    branches:
      - develop
    # Execute the action on closed (merged) PR.
    types:
      [closed]
    workflow_dispatch:
```

**Note**: I removed all branches except "develop" from the *branches* field. If you have separate jobs that run on those branches, consider making another GitHub Actions yml file for this job specifically. Abstraction and separation of concerns is your best friend here.

### Option [2]
GitHub unfortunately does not have the *pull-request-merged* event. However, in the case that the **only** action you take with regards to the **develop** branch is opening and merging PRs to it, you could simply do the following:

```yaml
on:
  push:
    # For the develop branch only.
    branches:
      - develop
    workflow_dispatch:
```

A merged PR to the *develop* branch will always trigger the *push* event, which executes your GitHub actions file's jobs accordingly.

### Option [3]
The final option (and perhaps most reliable option, if done right) is the best of both worlds. It ensures that your jobs only run if the following conditions are met:
- Event _must_ be a Pull Request
- Type of event _must_ be closed
- The Pull Request _must_ be merged

```yaml
on:
  pull_request:
    branches:
      - develop
    types:
      - closed

# Later, in the jobs section of your actions.yml file.
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was successfully merged.
```

#### Edits (ignore)
1. Added missing line "on:" in Option 2
