### DISCUSSION TITLE
Syntax error when input of type 'number' are forwarded by 'workflow_dispatch' to the reused workflow

### DISCUSSION THREAD

**Discussion by kunalherkal** [community/community#67182] [Actions]
### Select Topic Area

Bug

### Body

**Describe the bug**
When a 'workflow_dispatch' calls reusable workflow, and forwards it's input of type 'number' to the called workflow, it results into syntax error.

**To Reproduce**
This is the reusable workflow that is called:
```
name: Called workflow

on:
  workflow_call:
    inputs:
      inputA:
        description: Number input
        required: true
        type: number
      inputB:
        description: String input
        required: true
        type: string

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: echo "Hello world"
```
This is the caller workflow that calls above workflow:
```
name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      inputA:
        description: Number input
        required: true
        type: number
      inputB:
        description: String input
        required: true
        type: string

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/called-workflow.yml
    with:
      inputA: ${{ inputs.inputA }}
      inputB: ${{ inputs.inputB }}

```
Error:
When triggering the workflow_dispatch using UI, I pass `1000` as value for `inputA` and some string for `inputB`.
The job doesn't even start and I see following syntax error:
```
Caller Dispatch Workflow: .github#L1
The template is not valid. .github/workflows/caller-workflow.yml (Line: 19, Col: 15): Unexpected value '1000'
```
Also if I hardcode `inputA` when calling the called workflow, run succeeds. for example:
```
jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/called-workflow.yml
    with:
      inputA: 1000
      inputB: ${{ inputs.inputB }}
```

**Expected behavior**
There should be no syntax error in the case explained above.

## Runner Version and Platform
Version of your runner?
Github Hosted: '2.309.0'

OS of the machine running the runner? OSX/Windows/Linux/...
```
Ubuntu
  22.04.3
  LTS
```

**Comment by danikv** [comment]
Also having this problem, any suggestions ?

**Comment by unru006** [comment]
Just experienced that bug as well - still no reaction on this? :-(

**Comment by sszemeresky** [comment]
same issue here, guys this is crucial :|

**Comment by ghost** [comment]
Exact issue in my repo's [workflow](https://github.com/CrimsonEdgeHope/LabynetFriendNetworkGraph/actions/runs/7296858201). 
Perhaps a workaround can be setting the type to string, leave conversion to inside the workflow.😕

**Reply by sherbie** [reply]
This is the workaround I use with an additional type assertion in a shell script.

**Reply by sszemeresky** [reply]
> This is the workaround I use with an additional type assertion in a shell script.

could you please share your solution? I'm wanting to use an input as a nr of matrix elements to run tests on x workers

**Comment by PrzemekZglinicki** [comment]
Same problem here - https://github.com/OxlaCom/Oxla/actions/runs/7543017434

**Comment by arjan-noordende** [comment]
Same here. This is clearly a bug that needs picking up.

**Comment by legoGoat** [comment]
I ran into this yesterday as well. I tried all sorts, even found the old GHA bug where one couldn't pass caller workflow's `inputs.` variables into a called workflow's `with` block, which has long since been resolved.
But, yes, it seems like at some point between being input into the first workflow and trying to pass into the second workflow, a number stops being a number and it is just passed around as a string.
So, `on.workflow_call.inputs.variable-name.type: number` is clearly a big no, doesn't work. ❌ 😬

**Comment by paupujolasparset** [comment]
As a workarround I use the [fromJson](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson) expression.

In the example above would be:
```
call_reusable_workflow:
    uses: ./.github/workflows/called-workflow.yml
    with:
      inputA: ${{ fromJson(inputs.inputA) }}
      inputB: ${{ inputs.inputB }}
```
