### DISCUSSION TITLE
Tag trigger doesn't work

### DISCUSSION THREAD

**Discussion by tisonkun** [community/community#67498] [Actions] [answered]
### Select Topic Area

Question

### Body

See https://github.com/apache/incubator-opendal/issues/3121.

The trigger is as:

```yml
name: Bindings Java Release

on:
  push:
    tags:
      # Staging JARs on Apache Nexus repository for RCs. Read more on
      # https://opendal.apache.org/docs/contributing/release#release-maven-artifacts
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
  workflow_dispatch:
```

But when a tag named `v0.40.0-rc2` pushed, no workflow instance was triggered.

The pattern match is tested against https://regex101.com/:

<img width="1429" alt="image" src="https://github.com/community/community/assets/18818196/7e540df2-878d-488c-b20b-8baee1995f00">

Shall I escape the `.`?
