### DISCUSSION TITLE
matrix->include doesn't follow #example-adding-configurations

### DISCUSSION THREAD

**Discussion by MichaelTiemannOSC** [community/community#67591] [Actions]
### Select Topic Area

Bug

### Body

I'm having great difficulty implementing a matrix strategy following the pattern described by https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-adding-configurations

I think there's a bug.

Here are the relevant bits from my CI file (https://github.com/MichaelTiemannOSC/pint-pandas/blob/master/.github/workflows/ci.yml):

```
jobs:
  test:
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]
        numpy: ["numpy>=1.20.3,<2.0.0"]
        pandas: ["pandas==2.0.2", "pandas>=2.1.0" ]
        pint: ["pint>=0.21.1,<0.22", "pint==0.22", "pint>=0.23rc0"]
	uncertainties: [""]
        include:
          - python-version: 3.9
            numpy: "numpy>=1.20.3,<2.0.0"
            pandas: "pandas>=2.1.0"
            pint: "pint==0.23rc0"
            uncertainties: "uncertainties==3.1.7"
```

What works: I get the full matrix of permutations with `uncertainties` as null, plus I get the special case of `(3.9, "numpy>=1.20.3,<2.0.0", "pandas>=2.1.0", "pint==0.23rc0", "uncertainties==3.1.7"), which can be seen here: https://github.com/hgrecco/pint-pandas/actions/runs/6234737890

However, what I think the pattern promises, and what I have not been able to achieve, is to get test cases for all three Python versions, not just the one.  What I thought should work would be this:

```
jobs:
  test:
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]
        numpy: ["numpy>=1.20.3,<2.0.0"]
        pandas: ["pandas==2.0.2", "pandas>=2.1.0" ]
        pint: ["pint>=0.21.1,<0.22", "pint==0.22", "pint>=0.23rc0"]
	uncertainties: [""]
        include:
            pandas: "pandas>=2.1.0"
            pint: "pint==0.23rc0"
            uncertainties: "uncertainties==3.1.7"
```

I thought this would work because we are only overwriting some specific matrix variables, so what I think should happen is that we get additionally all test cases where the variables are being overwritten.  What seems to happen instead is that the additional test cases don't carry forward with them the permutations of variables not being overwritten.  Thus the extra test cases are being constructed as just the one assignment ("pandas>=2.1.0", "pint==0.23rc0", "uncertainties==3.1.7"), and because python-version is not a part of that, the other rules governing `test` (such as installing `pytest`) never run.

Moreover, when I attempt to unroll to explicitly list each version of `python-version` separately, the `CI.yml` file fails: https://github.com/hgrecco/pint-pandas/actions/runs/6234647556/workflow

So, is this a bug, or an error in my understanding of the pattern?

**Comment by djc** [comment]
I'm having substantially the same issue. The documentation says:

> For each object in the `include` list, the key:value pairs in the object will be added to each of the matrix combinations if none of the key:value pairs overwrite any of the original matrix values. If the object cannot be added to any of the matrix combinations, a new matrix combination will be created instead. Note that the original matrix values will not be overwritten, but added matrix values can be overwritten.

My setup:

```
    strategy:
      matrix:
        python: [3.9, "3.10", "3.11"]
        include:
          - os: ubuntu-latest
            target: x86_64
          - os: windows-latest
            target: x64
          - os: macos-latest
            target: aarch64
```

Here, I would expect to get 9 jobs: one per `python` for each `os`/`target` combination. None of the "key:value paris overwrite any of the original matrix values" (that is, none of the objects in the `include` list define `python`), so it seems like this should work.

(For the OP: the unrolling fails because you have multiple `include` lists, if you include these as objects inside a single `include` it might work?)
