### DISCUSSION TITLE
Issue dropdown field and project filter

### DISCUSSION THREAD

**Discussion by aborruso** [community/community#67598] [Projects and Issues]
### Select Topic Area

Question

### Feature Area

Projects

### Body

Hi,
I have the issue template below field.

I would like to create a project view that contains only all issues associated to `sezione==🧰 risorse`.

Is it possible to add this kind of filter? If yes, how to?

Thank you

```yaml
- type: dropdown
  id: sezione
  attributes:
    label: Sezione
    description: lorem ipsum
    options:
      - ✍️ contenuti
      - 🧰 risorse
      - 🎖️ soddisfazioni
```

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
