### DISCUSSION TITLE
Issue dropdown field and project custom field

### DISCUSSION THREAD

**Discussion by aborruso** [community/community#67618] [Projects and Issues]
### Select Topic Area

Question

### Feature Area

Projects

### Body

Hi,
I have the below issue template field.

I would like that when I associate one of its value to an issue, I have the item in my project associated to a related Project custom field.
I want to use issue dropdown form field to associate a Project custom field to that issue.

Does the way to do it is to use a github action and in example gh cli?

Thank you

```yaml
- type: dropdown
  id: sezione
  attributes:
    label: Sezione
    description: lorem ipsum
    options:
      - ✍️ contenuti
      - 🧰 risorse
      - 🎖️ soddisfazioni
```

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
