### DISCUSSION TITLE
Trying to use an app token to create a PR doesn't work

### DISCUSSION THREAD

**Discussion by rubenvp8510** [community/community#67610] [Actions]
### Select Topic Area

Question

### Body

Hello

I'm trying to use an app token to create a PR from my repository fork to an organization repository, I'm currently created 

Concrete example is 
I have my fork https://github.com/rubenvp8510/community-operators and want to create a PR to this repo https://github.com/k8s-operatorhub/community-operators

```
- name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.PUBLISH_APP_ID }}
          private_key: ${{ secrets.PUBLISH_APP_PRIVATE_KEY }}
          installation_id:  ${{ secrets.PUBLISH_APP_INSTALLATION_ID }}
          permissions: >-
            {"pull_requests": "write", "metadata": "read", "contents": "write"}
```

My test app has all the permissions and is installed on my repository. but then when the action tries to create the PR I'm getting this error

```
 branch 'update-tempo-operator-to-12.1.1' set up to track 'origin/update-tempo-operator-to-12.1.1'.
pull request create failed: GraphQL: Resource not accessible by integration (createPullRequest)
Error: Process completed with exit code 1.
```

Do I miss something? is there any other considerations that I need to have?

Thank you very much
