### DISCUSSION TITLE
What Pull Request event should be used in a workflow to generate a badge for the destination branch (where PRs is merged to)?

### DISCUSSION THREAD

**Discussion by minherz** [community/community#67642] [Actions]
### Select Topic Area

Question

### Body

Hi,
I am trying to reduce the total number of actions that run during a lifetime of the single PR. To do this I used the following event configuration for the workflow (action):

```yaml
on:
  pull_request:
    types: [opened,synchronize,reopened]
```

One of the results of this configuration is that I can display badge for this action on the "source" branch of the PR.

If I want to get a badge of this action running on the "destination" (base ref) branch, I need to add additional event to the configuration:

```yaml
on:
  pull_request:
    types: [opened,synchronize,reopened]
  push:
  - branch_name_1
  - branch_name_2
```

I did not check it but maybe the same effect can be reached by adding `closed` type to the list of the `pull_request` types that trigger the action. However, both of these changes will result in running the action (at least) one extra time. And, if the action is defined as required, guarantee to have the fixed (green) result.

Is there a way to make the badge to be updated for both branches when a `pull_request` event with a type that is not `closed` happens?
