### DISCUSSION TITLE
Auto-rerun github workflow on failure

### DISCUSSION THREAD

**Discussion by agunapal** [community/community#67654] [Actions]
### Select Topic Area

Question

### Body

I am using the following in my workflow file to rerun the workflow if there is a failure
```
- name: Re-run on failure
        if: ${{ failure() }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/rerun-failed-jobs
```

However I get the message

```
Run curl -L \
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   168  100   168    0     0   [14](https://github.com/pytorch/serve/actions/runs/6242336118/job/16946100156#step:12:15)35      0 --:--:-- --:--:-- --:--:--  1435
{
  "message": "This workflow is already running",
  "documentation_url": "https://docs.github.com/rest/actions/workflow-runs#re-run-failed-jobs-from-a-workflow-run"
}
```
I get the same error for both `/rerun` and `/rerun-failed-jobs`
How do I rerun this workflow?

This is an example run that I am trying
https://github.com/pytorch/serve/actions/runs/6242336118

**Comment by xxFREESHROUDxx** [comment]
Hello @agunapal 

Here's what you can do to troubleshoot this:

Wait for the Current Workflow to Finish: The error message indicates that the workflow is still running. You cannot rerun it until the current execution completes. You should wait for the ongoing workflow to finish before attempting to rerun it.

Check Workflow Status: Go to the Actions tab of your GitHub repository and check the status of the workflow you're trying to rerun. Make sure it has either completed or failed before attempting to rerun it.

Verify Workflow Run ID: Ensure that the github.run_id you're using in your workflow is correct. It should correspond to the specific run you want to rerun.

Double-Check Trigger Conditions: Make sure that the conditions set for rerunning the workflow are met. In your case, you're using if: ${{ failure() }}, which means the workflow should rerun only if it fails. Ensure that the previous run did indeed result in a failure.

Use the Correct API Endpoint: You're using the /rerun-failed-jobs endpoint, which is correct for rerunning failed jobs. If you want to rerun the entire workflow, you can use /rerun instead. Make sure you're using the appropriate endpoint for your use case.

Review the Workflow Configuration: Check your workflow configuration file to ensure there are no issues with the way the rerun step is defined. Verify that you're not inadvertently triggering the rerun under conditions that you didn't intend.

**Comment by agunapal** [comment]
Hi @xxFREESHROUDxx  Thanks for getting back. 

I am deliberately trying to rerun the same workflow when I see that it has failed. I guess technically the workflow is still running because the cleanup is not complete yet. 
So, how do i retry on failure?


I also attempted this with jobs. I am getting the same error with jobs as well

Here is the workflow file https://github.com/pytorch/serve/actions/runs/6243287777/workflow

and here is the run https://github.com/pytorch/serve/actions/runs/6243287777

I created a job called retry and passing the job id from the main job to this to rerun. However it still says

```
The workflow run containing this job is already running
```

I am not able to figure out how to re-run a failed job or workflow automatically. Could you please help?

**Comment by nkraetzschmar** [comment]
I recently stumbled upon the same problem and was able to "solve" it using the following workaround:
- create a second workflow that has a `workflow_dispatch` trigger with a `run_id` input
- in this secondary workflow wait for `run_id` to complete and then trigger a rerun
- in the original workflow, instead of directly initiating a rerun, issue a workflow run of the secondary workflow with the current workflows `run_id` as input

## example:

**test.yml:**
```yaml
on: push
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: false
  re-run:
    needs: fail
    if: failure() && fromJSON(github.run_attempt) < 3
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: gh workflow run rerun.yml -F run_id=${{ github.run_id }}
```

**rerun.yml:**
```yml
on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - name: rerun ${{ inputs.run_id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: |
          gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
          gh run rerun ${{ inputs.run_id }} --failed
```
