### DISCUSSION TITLE
Dlete workflow runs from Mattraks/delete-workflow-runs@v2

### DISCUSSION THREAD

**Discussion by dileepainivossl** [community/community#67666] [Actions]
### Select Topic Area

Question

### Body

Hi, Im using github action to delete my previous workflow runs.
[Github Action](https://github.com/marketplace/actions/delete-workflow-runs)

```
name: Delete Previous Workflow Runs

on:
  push:
    branches: ['develop']
 
jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 6
```

But after running that actions there are some workflow runs remaining. and some of them are skipped
![image](https://github.com/community/community/assets/124654997/1221e29f-ec6f-46b4-9680-2180b88afd98)

Is there a new configuration to add ?
