### DISCUSSION TITLE
Bad credentials error on Git Actions Enterprise

### DISCUSSION THREAD

**Discussion by naz141** [community/community#67684] [Enterprise]
### Select Topic Area

Question

### Body

The "Bad credentials" message appears when git action workflows sets below env.

```
env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
I am trying to do auto merge using the [pascalgn/automerge-action](https://github.com/pascalgn/automerge-action) and the full workflow file is as below.

```
name: Auto-merge

on:
  pull_request:
    branches: [ development ]

jobs:
  auto-merge-build-and-deploy:
    runs-on: [ self-hosted ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
  
    - id: automerge
      name: automerge
      uses: "synced-actions/automerge-action@v0.15.6"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I have tried other ways setting custom token saved in secrets as below.

```
 GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
```

![image](https://github.com/community/community/assets/4230962/263ac7d5-70d6-4e1b-864f-8793051216f7)
