### DISCUSSION TITLE
How to configure Dependabot to create PRs for security vulnerability that has  allow and ignore config set

### DISCUSSION THREAD

**Discussion by yhy-1** [community/community#67747] [Actions]
### Select Topic Area

Question

### Body

Hi, 
I have been trying to get security updates PR for all the security vulnerabilities but having issues since I want to ignore patch dependency updates. But it seems like security updates are ignored. I read that update-types only ignore dependencies update and not security in documentation but it doesn't seem like that is the case.

I know you can set the `pull-request-limit=0` to just get the security update but would love to also get the dependency update that satisfies the allow and ignore config.  Do we know if this is possible or how to configure it? 

All security updates
Updates (major, minor) for dependencies in the mycompany registry.
Currently, my dependabot.yml file looks like this:

```
version: 2
registries:
  mycompany:
    type: npm-registry
    url: 'https://npm.pkg.github.com'
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - 'mycompany'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
   allow:
      - dependency-name: '@mycompany/*'
   ignore: 
     - dependency-name: '@mycompany/*'
       update-types: ['version-update:semver-patch'] 
```

**Comment by davidfstr** [comment]
> I know you can set the pull-request-limit=0 to just get the security update but would love to also get the dependency update that satisfies the allow and ignore config. Do we know if this is possible or how to configure it?

I get security updates plus their dependency update by disabling all other update-types explicitly:

```
version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"  # where to find: pyproject.toml, poetry.lock
    schedule:
      interval: "weekly"
    # Disable all updates except security updates
    ignore:
      # Disable all updates except security updates
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
```
