### DISCUSSION TITLE
[Request] Add environment support to Reusable Workflows on GitHub Actions

### DISCUSSION THREAD

**Discussion by kjluedke** [community/community#6782] [Actions] [answered]
I would like the ability to have environment support on Reusable Workflows on GitHub Actions so that I can cleanly and safely refer to environment secrets.

For example, I have two environments: `development` and `production`, and both have a secret stored named `MY_SECRET` with different values.  I cannot cleanly reference MY_SECRET from either environment because the `job.<job_id>.environment` cannot be used if `job.<job_id>.uses` is also being used.

The desired functionality would look something like this:

```
name: Deploy 
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: development

 deploy:
    uses: MyOrg/MyRepository/.github/workflows/_common-deploy-workflow.yml
    environment: ${{ github.event.inputs.environment }}
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
```

**Comment by kjluedke** [comment, marked as answer]
Answering my own question here:  this is already possible - but it is not intuitive.

The common workflow will look like this:

```
 name: Deploy 
 on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: development

 deploy:
    uses: MyOrg/MyRepository/.github/workflows/_common-deploy-workflow.yml
    inputs:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
```


The '_common-deploy-workflow.yml' will look something like this:

```
name: Common Deploy Workflow
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
        env: 
         MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "${MY_SECRET:0:1}-${MY_SECRET:1}"
```
