### DISCUSSION TITLE
Using environment vars in job returns in empty strings

### DISCUSSION THREAD

**Discussion by SiddhantSadangi** [community/community#67846] [Actions]
### Select Topic Area

Bug

### Body

Issue raised here: https://github.com/actions/runner/issues/2472

**Comment by oyekamal** [comment]
any solution?

**Comment by mh1622** [comment]
We're hitting this issue. I want to call a reusable workflow that itself references GitHub Environment variables from the caller workflow. These env vars **are** set if referenced in a job _step_, but **are not** set if referenced in a `jobs.<job_id>.if` conditional.

[The workaround](https://github.com/actions/runner/issues/2472#issuecomment-1543979982) I'm using involves creating another job and having a step in that job output the variable so that the later conditional job can reference it. This is not ideal (more yaml), and if you've got deployment protection rules in place, they get triggered twice for one workflow run due to this.

**Comment by Qiming-Liu** [comment]
In 2026, this is still a issue for us 😞

**Comment by AUG235772** [comment]
Hi **@SiddhantSadangi**,

This behavior is tied directly to the **Context Availability Lifecycle** inside the GitHub Actions runner core design architecture, as documented in upstream runner issue [#2472](https://github.com/actions/runner/issues/2472).

When you use the `env` block context, you are setting **shell-level environment variables** that are passed to the runner OS block. However, referencing those variables inside top-level structural declarations (such as `jobs.<job_id>.outputs`, `jobs.<job_id>.if` conditions, or cross-workflow orchestration properties) will always evaluate to an empty string `""`.

---

###  Why This Happens (Context Resolution Phases)

GitHub Actions runs interpolation over your YAML structure in strict chronological phases:

1. **Phase 1: Workflow Parsing (Static Evaluation)**: GitHub evaluates top-level properties like `jobs.<job_id>.outputs`, expressions inside `if:` logic blocks, and structural parameters. At this specific point, **only the `vars`, `secrets`, `inputs`, and `github` contexts exist.** 
2. **Phase 2: Job Initialization**: The runner spins up. Job-level `env:` variables are evaluated and injected into the target shell space.
3. **Phase 3: Step Execution (Dynamic Evaluation)**: Individual execution blocks run. Shell environment variables (e.g., `$MY_VAR` or `${{ env.MY_VAR }}`) are only populated and valid *inside* these runtime operations.

Because a job's return properties/outputs are evaluated during the compilation handoff between Phase 1 and Phase 2, they cannot read the runtime `env` context. It evaluates them early, resulting in an **empty string**.

---

###  Production-Ready Workarounds

To safely pass variables up to job levels or use them conditionally without getting empty strings, use one of these architectural approaches:

#### Method A: Use the Native `vars` Configuration Context (Recommended)
If your environment variables are configuration values that do not change dynamically during runtime, move them completely out of the `env:` block and use GitHub configuration variables. The `vars` context is available during Phase 1:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    # This works perfectly because vars context is available at parsing time!
    outputs:
      app_version: ${{ vars.GLOBAL_APP_VERSION }} 
    steps:
      - run: echo "Initializing compilation..."
```

#### Method B: Map a Dynamic Step Output to the Job Output
If the variable is generated dynamically or must be set inside the runtime workflow, you must write it directly to the `$GITHUB_OUTPUT` file stream within a step, and then explicitly map that step's reference to your job-level return profile:

```yaml
jobs:
  export-variable:
    runs-on: ubuntu-latest
    outputs:
      matrix_target: ${{ steps.setter-step.outputs.TARGET_ENV }}
    steps:
      - id: setter-step
        run: |
          # Write your runtime variable down to the Step Output buffer
          echo "TARGET_ENV=production" >> "$GITHUB_OUTPUT"

  deploy-infrastructure:
    needs: export-variable
    runs-on: ubuntu-latest
    # Now you can safely consume the variable across separate jobs
    environment: ${{ needs.export-variable.outputs.matrix_target }}
    steps:
      - run: echo "Deploying infrastructure target..."
```

---

###  Recommended Discussion Closing Response

To update your active community thread with these prescriptive action steps for other passing users, you can use the reply update block below:

```text
Update: This is an intentional architectural scoping separation in the runner framework rather than a transient platform bug. 

The `env` context block is evaluated during job execution (Phase 2), whereas structural declarations like job `if:` conditions and `outputs` mappings are compiled beforehand (Phase 1). This compilation mismatch causes the evaluator to resolve unknown context elements down to a default empty string ("").

To bypass this tracking limitation:
1. Use the `vars` context directly in structural assignments for non-dynamic configurations.
2. For runtime variables, write them down to the `$GITHUB_OUTPUT` file descriptor within an explicit workflow step, then map that `steps.<step_id>.outputs` context path out to the broader job structure.
```
