### DISCUSSION TITLE
Workflows getting stuck on "Starting job..." using self-hosted runners

### DISCUSSION THREAD

**Discussion by dmerrick** [community/community#67878] [Actions]
### Select Topic Area

Bug

### Body

Hello!

We've been using GitHub Actions with self-hosted runners for several years now. Unfortunately recently (in the last week or so) _some_ of our workflows are getting stuck on the `Starting job...` phase.

Strangely, not all of our workflows are getting stuck. Most of them are fine, but the ones that are getting stuck are occupying our runners and backing up other jobs.

We have not made any changes to the runners themselves. We are running the latest version of the self-hosted runner software `2.309.0`. We have tried reverting to an older version but the same issue exists (it also seems like the runners update themselves on startup so that could be why).

The workflows that are getting stuck don't seem to have anything in common (compared to the workflows that still function fine). We haven't made any changes to them recently, they just suddenly stopped working. The latest change was upgrading `actions/checkout` from `v3` to `v4`... reverting this change does not prevent these workflows from getting stuck.

When I look at the logs on the runner, I can see the workflow getting assigned to the runner, but don't see any output that would be useful:
```
Sep 21 14:01:11 ip-20-10-91-22 /supervisord[559]: runner_00 √ Connected to GitHub
Sep 21 14:01:11 ip-20-10-91-22 /supervisord[559]: runner_00 Current runner version: '2.309.0'
Sep 21 14:01:11 ip-20-10-91-22 /supervisord[559]: runner_00 2023-09-21 14:01:11Z: Listening for Jobs
Sep 21 17:36:42 ip-20-10-91-22 /supervisord[559]: runner_00 2023-09-21 17:36:42Z: Running job: check-diffs
<stays like this for hours>
```

The runners are not under load during this time. Cancelling the job via the GitHub webui will allow another job to be assigned... but if it's one of the workflows that has this issue, it will get stuck again.

Changing the workflow from `self-hosted` to `ubuntu-latest` _does_ let the jobs get assigned, but we can't do that for all of our currently-broken workflows.

We have run our problematic workflows through YAML syntax checkers to make sure that they are valid (and they are), but regardless these very same workflows worked fine before this issue suddenly popped up.

The sudden occurance of this issue being apparently unrelated to any code changes on our side leads be to believe it might be a change on GitHub's side, but I haven't seen any other reports of this or related incidents on status.github.com.

Here is an example workflow that has this issue, only slightly modified to post publicly:

```yaml
on:
  pull_request:
    paths:
      - .github/workflows/k8s.yml
      - .github/workflows/scripts/check-status.sh
      - .github/workflows/scripts/post-to-slack.py
      - k8s/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/k8s.yml
      - .github/workflows/scripts/check-status.sh
      - .github/workflows/scripts/post-to-slack.py
      - k8s/**

# this will run `kubectl diff` to check for unapplied changes
name: Kubernetes
jobs:
  check-diffs:
    name: check-diffs
    defaults:
      run:
        # this is the defaults, but without -e
        # we have this to allow the k8s diff command to fail
        # c.p. https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
        shell: bash --noprofile --norc -o pipefail {0}
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
    
      - name: dump-github-context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: set-path
        run: echo ./.github/workflows/scripts >> $GITHUB_PATH

      - name: login-to-stage
        run: |
          aws eks update-kubeconfig --role-arn arn:aws:iam::1234567890:role/CIRole --name stage-eks-cluster
          kubectl get pods
          kubectl version --short

      - id: common-stage
        name: common
        run: |
          kubectl diff -k k8s/common/stage
          check-status.sh $?

      - name: post-to-slack
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
          SLACK_WEBHOOK_URLPATH: ${{ secrets.SLACK_INFRABOT_WEBHOOK_URL }}
        run: |
          pip3 install slack_webhook
          post-to-slack.py
```

Thank you!
