### DISCUSSION TITLE
Trigger a workflow on push based on the pull request status

### DISCUSSION THREAD

**Discussion by nakedsushi** [community/community#67893] [Actions]
### Select Topic Area

Question

### Body

Hello, I'm not sure if this is possible, but is there a way to trigger an action on push _only if_ there's a pull request  associated with the push? Basically, I want to run a certain workflow whenever a change is pushed to pull request that is in "ready for review" mode.

Something like this (which doesn't work b/c the event is a `push`, not a `pull_request`:
```
on:
  push:
    branches-ignore:
      - main
jobs:
  do-something:
    if: !github.event.pull_request.draft
    run: echo "this should only run on pushes to a PR that's ready"
```

**Comment by Zerotask** [comment]
As far as I know, this is not possible at the moment. You can just get the state of a PR: draft, open or closed.

Example:
```yaml
jobs:
  check-pull-request-state:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request State
        id: pr_state
        run: |
          PR_URL=$(jq -r .pull_request.url "$GITHUB_EVENT_PATH")
          PR_STATE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL | jq -r .state)

          echo "::set-output name=pr_state::$PR_STATE"
      
      - name: Run Workflow if PR is Ready
        if: steps.pr_state.outputs.pr_state == 'open'
        run: |
          # Your workflow steps here
```
