### DISCUSSION TITLE
ENOENT on spawn

### DISCUSSION THREAD

**Discussion by theSherwood** [community/community#67908] [Actions]
### Select Topic Area

Question

### Body

I'm trying to compile an electron app in github actions. The build and step runs fine locally, but fails in github actions with `ENOENT`. I have verified that the file is there prior to `electron-builder` running. I have verified that the file is has the correct permissions.

This is a minimal repro repo: https://github.com/theSherwood/electron_build_bug_minimal_repro
Here are some logs for the failing build: https://github.com/theSherwood/electron_build_bug_minimal_repro/actions/runs/6267565614/job/17020896667

Here is the action config:
```
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          # cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
```

Here is the error I'm getting (which you can see in the build logs at the link above):
```
  > @codex/electron@0.0.1 compile
  > env-cmd -e prod electron-builder build --config electron-builder.config.js --dir
  
    • electron-builder  version=24.6.4 os=21.6.0
    • artifacts will be published if draft release exists  reason=CI detected
    • loaded configuration  file=/Users/runner/work/electron_build_bug_minimal_repro/electron_build_bug_minimal_repro/apps/electron/electron-builder.config.js
    • description is missed in the package.json  appPackageFile=/Users/runner/work/electron_build_bug_minimal_repro/electron_build_bug_minimal_repro/apps/electron/package.json
    • installing production dependencies  platform=darwin arch=x64 appDir=/Users/runner/work/electron_build_bug_minimal_repro/electron_build_bug_minimal_repro/apps/electron
    • packaging       platform=darwin arch=x64 electron=26.2.0 appOutDir=dist/mac
    ⨯ spawn /Users/runner/work/electron_build_bug_minimal_repro/electron_build_bug_minimal_repro/node_modules/app-builder-bin/mac/app-builder_amd64 ENOENT  failedTask=build stackTrace=Error: spawn /Users/runner/work/electron_build_bug_minimal_repro/electron_build_bug_minimal_repro/node_modules/app-builder-bin/mac/app-builder_amd64 ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
      at onErrorNT (node:internal/child_process:485:16)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
  npm ERR! Lifecycle script `compile` failed with error: 
  npm ERR! Error: command failed 
  npm ERR!   in workspace: @codex/electron@0.0.1 
  npm ERR!   at location: /Users/runner/work/electron_build_bug_minimal_repro/electron_build_bug_minimal_repro/apps/electron 
  npm ERR! Lifecycle script `build` failed with error: 
  npm ERR! Error: command failed 
  npm ERR!   in workspace: @codex/electron@0.0.1 
  npm ERR!   at location: /Users/runner/work/electron_build_bug_minimal_repro/electron_build_bug_minimal_repro/apps/electron 
```

This part in particular:
```
stackTrace=Error: spawn /Users/runner/work/electron_build_bug_minimal_repro/electron_build_bug_minimal_repro/node_modules/app-builder-bin/mac/app-builder_amd64 ENOENT
```

I have verified that the file exists and that it has exec permissions:
```
  START OF FILENAMES IN DIRECTORY: /Users/runner/work/electron_build_bug_minimal_repro/electron_build_bug_minimal_repro/node_modules/app-builder-bin/mac
  app-builder_amd64
  app-builder_arm64
  END OF FILENAMES
  
  MODE BEFORE: 33279
  MODE AFTER: 33279 
```

The repo is using `turbo` and is using `level` which has native dependencies. If I remove the `level` dependency, the problem disappears. So I it's got something to do with the native dependencies, I think, but I can't figure out why it errors in github actions and not locally.
I've talked it over with the maker of `electron-builder` and we didn't make headway. Has anyone run into this sort of issue before or have any idea how to approach it?
