### DISCUSSION TITLE
Composite action that calls a local TS action: "Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action"

### DISCUSSION THREAD

**Discussion by nedredmond** [community/community#67904] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a repo with a composite action that calls a local action. The purpose of the composite action is to gather data that the local action takes as input. That all seems to work well until it calls the other action.

It works great when I test in the action repo's workflows, but when I try to call the action from another repository, I get this message.

The code looks like this...

### Composite action:
```yml
name: 'Do thing'
description: 'Does thing'
author: 'Ned Redmond'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Call external action
      uses: some/external-action@v0
      id: external-action

    - name: Do thing for real now
      uses: ./my-ts-action
      with:
        input: ${{ steps.external-action.result }}

```

### My TS action:
```yml
name: 'Let's go'
description: 'Time to actually do the thing'
author: 'Ned Redmond'

inputs:
  input:
    description: gimme result of other action, thanks
    required: true

runs:
  using: node20
  main: dist/index.js
```

### My structure:
```yml
- root:
  - action.yml
  - my-ts-action:
    - action.yml
    - dist:
      - index.js
  - src:
    - action.ts
```

Everything works great per the output until we call `my-ts-action` and I see the message `Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action`.

Things I've tried:
```yml
    - name: Do thing for real now
      uses: ${{ github.action_path }}/my-ts-action # Just doesn't work.
      with:
        input: ${{ steps.external-action.result }}
```
```yml
    - name: Do thing for real now
      uses: owner/do-thing-repo/my-ts-action@v0 # Same problem as just using path.
      with:
        input: ${{ steps.external-action.result }}
```

What am I missing? Do I just need get rid of the composite action and compose within the consumer? Thanks in advance.

**Comment by nedredmond** [comment, marked as answer]
Turns out this is possible by checking out the same repo as the one I'm in, like so:
```yml

    # Checkout necessary files to run next action
    - uses: actions/checkout@v4
      with:
        repository: owner/do-thing-repo
        path: do-thing-path
        sparse-checkout: |
          my-ts-action
        
    - name: Do thing for real now
      uses: ./do-thing-path/my-ts-action
      with:
        input: ${{ steps.external-action.result }}
```

Big issues with this, however. I cannot access the ref of my composite action (env variables held the ref of the current action (i.e., v4 for `actions/checkout` and the ref of the calling workflow), so this would access whatever is on `main`. Smaller issue is I wouldn't want to use a static path name in case there was some collision with the parent repo (from which the workflow called this action), but `uses` does not take variables.

So I just removed this composite wrapper and specified in the docs how to compose the consuming workflow to get the necessary data.

**Reply by kamranayub** [reply]
Just ran into this while building a demo composite action. This seems like a bug. The Actions runner should know it's loading a composite action that may be referencing local actions, so it needs to treat local action paths as relative to `github.action_path`, not the workspace.

For a private repo, I also needed to add `with.token` set to a PAT with `Repository: Contents` (read-only) permission and access to my repo(s).

For the version being checked out, I workaround this using outputs. You can access `github.action_ref` from within the `env` of a composite action step, so I take this and create a step output (which happens in the context of the composite action), passing it to the `checkout` action:

```yaml
runs:
  using: composite
  steps:

  - name: Set reference to current action version
    id: set-action-version
    # Use workflow command to set `ref` output
    run: echo "ref=$ACTION_REF" >> $GITHUB_OUTPUT
    shell: bash
    env:
      # Composite actions can access `action_ref` context in `env`
      ACTION_REF: ${{ github.action_ref }}

  - name: Setup workaround for local actions
    uses: actions/checkout@v4
    with:
      repository: owner/do-thing-repo
      # Reference the composite action ref from the previous step output
      ref: ${{ steps.set-action-version.outputs.ref }}
      # PAT with fine-grained access to private repo and read-only "Repository Contents" permission
      token: ${{ inputs.github-token }} 
      # A dot folder is unlikely to conflict
      path: .local-action-cache
      sparse-checkout: |
        my-ts-action

  - uses: './.local-action-cache/my-ts-action'
 ```

It works:

![image](https://github.com/user-attachments/assets/a4e0f46d-ba2a-4007-844e-1700cf46562d)

When run from a consumer, it checks out the correctly referenced action version 💥
