### DISCUSSION TITLE
Unexpected trailing new-line when using `jq` and `while read` loop on Windows runners

### DISCUSSION THREAD

**Discussion by doragonroudo** [community/community#67930] [Actions]
### Select Topic Area

Bug

## Describe the bug

When executing `jq` command with `while read line` using `shell: bash` on `windows-2022` and `windows-2019` runner. There is unexpected extra new line passed through the loop. This behavior doesn't appear in `ubuntu` runners.

## To Reproduce

1. Create a new workflow that has a strategy matrix to run on any `windows` runner and any `ubuntu` runner that execute following bash script:
```yaml
echo '[{"name": "foo"}, {"name": "bar"}]' |
jq -r '.[].name' |
while read -r line; do
  echo "=$line="
done
```
2. The output of `windows` runner will have unexpected new-line before `=`
```shell
=foo
=
=bar
=
```
While the output from `ubuntu` runner will be normal
```
=foo=
=bar=
```

## Expected behavior

There should be no extra new-line character.

## Runner Version and Platform

- `windows-2022` / Runner version `2.309.0`
- `windows-2019` / Runner version `2.309.0`

## Job Log Output

I have create a test workflow to compare between `ubuntu` and `windows` runner.
Please see more detail on this workflow run: https://github.com/doragonroudo/jq-read-trailing-new-line-issue-on-windows-runner/actions/runs/6271202540

Source:

```yaml
name: "Trailing new-line issue"

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        os:
        - windows-2022
        - windows-2019
        - ubuntu-22.04
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: "jq + read"
      shell: bash
      run: |
        echo "======= print versions ======="
        bash --version
        jq --version

        echo "======= echo / read ======="

        echo "hello" |
        while read -r line; do
          echo "=$line="
        done

        echo "======= jq / read ======="

        echo '[{"name": "foo"}, {"name": "bar"}]' |
        jq -r '.[].name' |
        while read -r line; do
          echo "=$line="
        done

        echo "======= jq / read / parameter expansion ======="

        echo '[{"name": "foo"}, {"name": "bar"}]' |
        jq -r '.[].name' |
        while read -r line; do
          echo "=${line//[$'\t\r\n']}="
        done
```

<img width="670" alt="image" src="https://github.com/actions/runner/assets/39604556/429b243c-0d8c-4a90-aa65-1139fa9777a4">

<img width="661" alt="image" src="https://github.com/actions/runner/assets/39604556/69f7cfcf-f177-4e8e-b9fa-8233ffcdb5c6">

Not sure if this is a known issue on Windows git bash or it is runner's false. Please let me know. Thanks.
