### DISCUSSION TITLE
Github actions (docker push ghcr.io) in custom runners are failing intermittently

### DISCUSSION THREAD

**Discussion by davcevski** [community/community#67944] [Actions]
### Select Topic Area

Question

### Body

I switched from using PAT to GITHUB_TOKEN, now every time I push and trigger the actions, random actions will fail at times. Other times the same actions pass but there's always at least couple of jobs for `docker push` that are failing. However whenever I re-trigger manually (trough the github UI) all of the jobs are always passing.

I tried deleting the packages to let the action republish them since I have a new token, but no luck.

I am using 15 custom runners hosted on the same machine as different systemctl processes, here is example of couple of jobs.  `release-mqtt` always succeeds `release-cloudapi` fails intermittently, other times it passes:

```
  release-mqtt:
    name: Release mqtt
    needs: release-base-image
    runs-on:
    - k3s-staging
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build docker image
      run: docker build --file app/mqtt/Dockerfile --tag "ghcr.io/xxxx/mqtt:$GITHUB_SHA" --build-arg GIT_COMMIT="$GITHUB_SHA"  .
    - name: Publish to container registry
      run: docker push "ghcr.io/xxxx/mqtt:$GITHUB_SHA"
  release-cloudapi:
    name: Release cloudapi
    needs: release-base-image
    runs-on:
    - k3s-staging
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build docker image
      run: docker build --file app/yyyy/Dockerfile --tag "ghcr.io/xxxx/yyyy:$GITHUB_SHA" --build-arg GIT_COMMIT="$GITHUB_SHA"  .
    - name: Publish to container registry
      run: docker push "ghcr.io/xxxx/cloudapi:$GITHUB_SHA"
```

The errors are usually something along the lines:

```
bc83938ff3a6: Preparing
denied: denied
Error: Process completed with exit code 1.
```

At first I thought its a concurrency issue, but then why is it that from the UI they work all the time?
