### DISCUSSION TITLE
Deploy to GitHub pages failing

### DISCUSSION THREAD

**Discussion by GlobalMin** [community/community#67961] [Actions]
**EDIT: This seems to be fixed. What a roller coaster of a day. Thanks to all**
---
I am building a github pages site and have an automated workflow to build the docs and publish to pages with each push. It's worked great until this morning. I can build the docs locally fine and the failed step is here:

``` ruby
Run actions/deploy-pages@v2
  
Artifact exchange URL: https://pipelinesghubeus7.actions.githubusercontent.com/nVYPfQ46MHmX10vrCRYdexjLlXvj0ehIIwps4sKKnqwCUwP61A/_apis/pipelines/workflows/6275405289/artifacts?api-version=6.0-preview
Creating Pages deployment with payload:
{
	"artifact_url": "https://pipelinesghubeus7.actions.githubusercontent.com/nVYPfQ46MHmX10vrCRYdexjLlXvj0ehIIwps4sKKnqwCUwP61A/_apis/pipelines/1/runs/26/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "f43d43acc9f66a2f4f5e2463c67270b8f0f04c6a",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: Invalid artifact url
    at /home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/api-client.js:126:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/deployment.js:80:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 400) with build version f43d43acc9f66a2f4f5e[24](https://github.com/GlobalMin/jameson-resume/actions/runs/6275405289/job/17042818285#step:8:25)63c67[27](https://github.com/GlobalMin/jameson-resume/actions/runs/6275405289/job/17042818285#step:8:28)0b8f0f04c6a. Responded with: Invalid artifact url
```

Is it possible that there is an issue with GH Actions right now?

Here is my workflow.yml that has worked over 22 prior commits perfectly.

``` yaml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Commit documentation changes
        run: |
           sphinx-build -nW --keep-going -b html docs/ rendered_docs/_build/html
           cd rendered_docs
           touch .nojekyll
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: 'rendered_docs/_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
