### DISCUSSION TITLE
GITHUB_STEP_SUMMARY file is empty

### DISCUSSION THREAD

**Discussion by dkirrane** [community/community#67991] [Actions]
### Select Topic Area

Question

### Body

When I try to read the content of the `GITHUB_STEP_SUMMARY` file it is empty.
In the first step below I output to `GITHUB_STEP_SUMMARY`
In the second step I read it with `fs.readFileSync` but it's always empty. Possibly cause it's not flushed to disk??

I'm trying to read it so I can output it as a comment in the PR also.

```yaml
name: Job Summary

on:
  workflow_dispatch:
  push:

jobs:

  Run:
    runs-on: ubuntu-latest

    steps:

    - run: |
        echo "foo" >> $GITHUB_STEP_SUMMARY
        echo "bar" >> $GITHUB_STEP_SUMMARY

    - uses: actions/github-script@v6
      with:
        script: |
          // Read summary
          console.log("Summary file:")
          console.log(process.env.GITHUB_STEP_SUMMARY)

          console.log("Summary content:")
          const fs = require('fs')
          const summary = fs.readFileSync(process.env.GITHUB_STEP_SUMMARY, 'utf8')
          console.log(summary)

```

**Comment by seyLu** [comment]
#### Hi @dkirrane,

In this line, we get ambiguous redirect:
![image](https://github.com/community/community/assets/98249191/f81ff0e4-647a-44f3-9ec3-52058cf445bc)
 
Bash manual states to put quotes around variables to prevent word splitting:
![image](https://github.com/community/community/assets/98249191/64e31937-53c4-46f1-8a4d-9748405b1a5e)

Instead of `>>`, we can instead use command substitution `$(<command>)`:
![image](https://github.com/community/community/assets/98249191/bf213458-1857-4d28-9cf5-c8db0d899e3f)


You can read more on:
- [StackExchange: Ambiguous Redirect](https://superuser.com/questions/1735939/where-is-the-ambiguous-redirect-in-this-bash-line)
- [TLDP: Quoting Variables](https://tldp.org/LDP/abs/html/quotingvar.html)
- [StackOverflow: How to redirect output to a variable in shell](https://stackoverflow.com/questions/2559076/how-do-i-redirect-output-to-a-variable-in-shell)
- [TLDP: Command Substitution](https://tldp.org/LDP/abs/html/commandsub.html)

**Reply by dkirrane** [reply]
There doesn't seem to be any issue with the GitHub Summary itself, it outputs ok.

The problem is the second step where I try read the Summary but it's empty

![image](https://github.com/community/community/assets/1280116/bc94afbf-910a-46db-8b77-197a68f901b8)

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by leonid-deriv** [comment]
really helpful not not answer ... I have the same problem

**Comment by rclement** [comment]
Stumbled upon this exact issue today. Apparently this is the expected behavior according to the documentation: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#adding-a-job-summary

> Job summaries support [GitHub flavored Markdown](https://github.github.com/gfm/), and you can add your Markdown content for a step to the GITHUB_STEP_SUMMARY environment file. GITHUB_STEP_SUMMARY is unique for each step in a job. For more information about the per-step file that GITHUB_STEP_SUMMARY references, see [Environment files](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#environment-files).

The only workaround I could find is to write to a local file the markdown content and then dispatch the usage in each steps afterwards, e.g. generating some markdown content for the job summary and create/update a comment on source pull request (issue):

```yaml
      - name: Generate Markdown content
        run: echo "## Markdown content" >> content.md
      - name: Export Markdown content to job summary
        run: cat content.md >> $GITHUB_STEP_SUMMARY
      - name: Add Markdown content as comment to pull request
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')

            const body = fs.readFileSync('content.md', 'utf-8')

            comments = await github.paginate(
              github.rest.issues.listComments({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            )
            matches = comments.filter(comment => comment.body && comment.body.includes('Markdown content'))
            comment = matches[0]

            if (comment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id.toString(),
                body: body,
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body,
              })
            }
```

Hope that helps
