### DISCUSSION TITLE
CodeQL Failed - Exit code was 32 and error was: CodeQL detected code written in Java/Kotlin but could not process any of it.

### DISCUSSION THREAD

**Discussion by hanwenzhang123** [community/community#68044] [Code Security]
### Select Topic Area

Question

### Body

I set up `.github/workflows/codeql.yml` as of
```
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
        upload-database: false
```

Got an error when running Perform CodeQL Analysis
`Exit code was 32 and error was: CodeQL detected code written in Java/Kotlin but could not process any of it.`
![Screenshot 2023-09-23 at 11 23 42 AM](https://github.com/community/community/assets/79280844/64dcbd4b-b4f6-49b9-8536-649be13d0961)

Any advice on how to fix it? Thank you

**Comment by aibaars** [comment]
Have you read the troubleshooting guide mentioned in the error message? https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/no-source-code-seen-during-build

Could you provide a bit more context? Before `github/codeql-action/analyze` step, does your workflow file contain a `github/codeql-action/init` step followed by either a `github/codeql-action/autobuild` step or an explicit build command? If you have all that, then most likely the "autobuild" or explict build command did not compile and Java or Kotlin code.

**Reply by hanwenzhang123** [reply]
Hi @aibaars,
The `autobuild` failed. So I am building the project manually. 
Here is more context of the script before the analyze
```
    - name: Build Java project
      run: mvn -B package --file code/SoloSavingsApp/pom.xml

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
```
