### DISCUSSION TITLE
Combine matrix with reusable workflows

### DISCUSSION THREAD

**Discussion by pmmax** [community/community#68092] [Actions] [answered]
### Select Topic Area

Question

### Body

I am experiencing an issue with a "reusable" workflow that expects a "path" as an input. The workflow works fine when called from another workflow using the "uses/with" syntax to send the "path" parameter. However, I encounter a problem when trying to call it from a matrix-based workflow, as illustrated below:

```
jobs:
  caller-job:
    strategy:
      matrix:
        path:
          - "path1"
          - "path2"
    uses: ./.github/workflows/target.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      path: ${{ matrix.path }}
    secrets: inherit
```

In this case, the target workflow never receives the "path" parameter. I cant find why it works when called from a non-matrix workflow but fails in this matrix-based scenario. When I dump ```${{ toJSON(github) }}``` in the target workflow, I can see that the input is missing from "event.inputs."
The "environment" input works fine, which comes from "workflow_call.inputs.environment", the problem is specific for "path".
