### DISCUSSION TITLE
Can we use a static site with an apple-app-site-association file?

### DISCUSSION THREAD

**Discussion by haIIux** [community/community#68175] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I have a static site built using HTML/CSS with no JS (outside of Bootstrap CDN). This uses a workflow labeled `static.yml` as displayed below. I am trying to use an `apple-app-site-association` file with this. I have placed it within the root of the project and set it up so I can hit a specific endpoint however, Github Pages 404's and does not actually work.

I've seen a few hacks that state you need to place in your `_config.yml` file something along the lines of `include: [.well-known]` however I cannot seem to get that work? I'd love to know if this is possible of if I am going to need to migrate to something else to get this to work as it's crucial for my application...

```yaml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
