### DISCUSSION TITLE
Get start time of the needs job?

### DISCUSSION THREAD

**Discussion by retzero** [community/community#68201] [Actions]
### Select Topic Area

Question

### Body

How can I get the triggered or finished time of the previous job(`get_models`) in the example below from the `model_job`?
The `echo "${{ needs.get_models }}"` is empty. 😢 Can I get the any context of the previous job?

```
on:
  workflow_dispatch:

jobs:
  get_models:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.models.outputs.matrix }}
    steps:
      - id: models
        run: |
          echo "My own scripts..."
          echo "matrix=${cat ./result.json}" >> $GITHUB_OUTPUT

  model_job:
    needs: get_models
    strategy:
      matrix: ${{ fromJson(needs.get_models.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.get_models }}"
```
