### DISCUSSION TITLE
Needs on skipped matrix doesn't trigger dependency

### DISCUSSION THREAD

**Discussion by Fran-Rg** [community/community#68214] [Actions]
### Select Topic Area

Question

### Body

Related to https://github.com/orgs/community/discussions/27096 and https://github.com/dorny/paths-filter/issues/66

I have a matrix strategy which needs to run after another matrix strategy.
The first matrix strategy might not run and thus being skipped if output "changes" is empty.
The dependency needs to run if output "posttriggers" is not empty .
Here's an example workflow:
```
name: test 1

on:
  workflow_dispatch:

jobs:
  filters:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Filtering step"
    outputs:
      changes: "[]"
      posttriggers: '["run1"]'

  before-apply:
    needs: filters
    if: ${{ needs.filters.outputs.changes != '[]' }}
    strategy:
      matrix:
        service: ${{ fromJSON(needs.filters.outputs.changes) }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "before apply step"

  waitchanges:
    needs:
      - before-apply
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Echo
        run: echo "All changes have been deployed"

  post-apply:
    needs: waitchanges
    if: ${{ needs.filters.outputs.posttriggers != '[]' }}
    strategy:
      matrix:
        service: ${{ fromJSON(needs.filters.outputs.posttriggers) }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "post apply step"
```

"post-apply" job never runs despite the matrix strategy
The only solution atm is to set:
```
  post-apply:
    needs: waitchanges
    if: always()
```
Which will break if `posttriggers == '[]'`

Can we have strategy matrix: [] to be supported?
