### DISCUSSION TITLE
Triggering a workflow when a non-Github-Actions-driven check passes

### DISCUSSION THREAD

**Discussion by nikki-quant** [community/community#68243] [Actions]
### Summary

I have a repo which runs a non-Github-Actions pipeline when a pull request is open or when a merge to main is made, and I want to trigger a Github Actions job to start to run **only once that build has finished**. How can I best do that?

### Specifics

Hi folks! New Github Actions user here, with a question about how to trigger workflows.

I have a repo which triggers a build using a Github App when a pull request is open or when a merge to main is made. I want to trigger a Github Actions job to start to run **once that build has completed** on any branch (either a feature branch or main).

I can see the status of the build is reported on both the `check_suite` and `check_run` APIs, eg: 

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer xxxxxx" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/<myorg>/<myrepo>/commits/<mycommit>/check-suites
{
  "total_count": 3,
  "check_suites": [
    {
      "id": xxx,
      "node_id": "xxxx",
      "head_branch": "xxxx",
      "head_sha": "xxxxx",
      "status": "completed",
      "conclusion": "success",
      ...
```

The Actions docs say that check runs and check suites are documented as events that you can trigger a workflow on in https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#check_run, but I have spent a while trying to trigger jobs based on them and not managed it. Has anyone got an example of triggering workflows on non-main branches based on the results of a check_run or check_suite event? I have tried running the following from the main branch of a repo:

```
name: Check triggered by passing checks
on: [ status, check_suite, check_run ]
      
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Print out the event context
      env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
```

I'm using this dummy check to produce check results:

```
name: "Tests: Fake Happy Passing Check"

on:
  pull_request:
    branches:
    - main

jobs:
  example:
    name: Pretend I'm doing a cool test
    runs-on: ubuntu-latest
    steps:
      - name: be happy
        run: echo "Hell yea this check works!!!"
```

I can see that fake check reporting success by API:

```
$ curl -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer xxxxx" \
https://api.github.com/repos/<myorg>/<myrepo>/commits/<mycommit>/check-runs \
 | jq '[.check_runs[].name]'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4165  100  4165    0     0   8064      0 --:--:-- --:--:-- --:--:--  8231
[
  "Pretend I'm doing a cool test"
]
```

But Github Actions doesn't see it, regardless of whether the workflow file is in the default branch or a feature one. I've tried breaking the `on` conditions out into individual list items or dictionaries with event type filters. No dice either way. The pull request triggered job runs every time but I haven't found a way to trigger anything when the results come back from it.

I found [a thread](https://github.com/orgs/community/discussions/26169) on this forum that mentions only Github Apps can create check suites or runs and [suggests instead using the `status` API endpoint](https://github.com/orgs/community/discussions/25007), so I tried that, but I find that status endpoint is reported as pending for commits even when the check suites are working. That status endpoint is presumably updated by direct API calls and not by Github Apps using the check APIs, so I'd expect using the check API should work for me.

Any advice?
