### DISCUSSION TITLE
How to define a trigger for changed files in a directory working on certain brachnes?

### DISCUSSION THREAD

**Discussion by igorwojda** [community/community#68263] [Actions]
### Select Topic Area

Question

### Body

I would like my script to run with PR when any of these conditions is true
file is changed inside `samples/starter-projects/` 
OR
branch name starting with `release`
OR
branch name starting with `renovate`

I came up with this but it does not work 🤔 Any ideas on how to fix it?

```yml
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'release-*'
      - 'renovate*'
    paths:
      - 'samples/starter-projects/**'
```
