### DISCUSSION TITLE
React & Vite = 404

### DISCUSSION THREAD

**Discussion by cpi28** [community/community#68262] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

I'm trying to deploy a web page with react and vite, I've followed all the steps you mentioned before but I still have a 404 response :/
![image](https://github.com/community/community/assets/57321517/ce341189-a281-4500-89c5-79add0036898)
**My Vite config:**
![image](https://github.com/community/community/assets/57321517/8dc523e2-93d6-43ea-b879-ee8c6db02433)
**My Package JSON:**
![image](https://github.com/community/community/assets/57321517/b682253a-22a6-4594-9ff5-41cb9f663172)
**My deployments seem to be ok:**
![image](https://github.com/community/community/assets/57321517/c2e0ec2b-51cb-4c87-b007-3e475c71505d)
**My web page link:**
https://cpi28.github.io/cursoReact/

I'd be grateful for any suggestion.

**Comment by seyLu** [comment, marked as answer]
#### Hi @cpi28,

I've went and [deployed a copy of your site](https://seylu.github.io/cursoReact/). Stuff I did to get the site working:
- followed [Vite docs on how to deploy site to github pages](https://vitejs.dev/guide/static-deploy.html#github-pages). 
- added `.github/workflows/deploy.yaml`:

```yaml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload dist repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
- on repo settings, configured pages to build and deploy with github actions:
![image](https://github.com/community/community/assets/98249191/228fc619-24ee-4288-b454-0cc10d65e960)
- configured base in `vite.config.js`:
```diff
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
+ base: '/cursoReact/',
  plugins: [react()],
})
```
- configured Router basename in `App.jsx`:
```diff
- <Router>
+ <Router basename={import.meta.env.BASE_URL}>
```
- fixed broken links

<br>

You can read more on:
- [Vite docs: Deploy to github pages](https://vitejs.dev/guide/static-deploy.html#github-pages)
- [Vite docs: Shared options - base](https://vitejs.dev/config/shared-options.html#base)
- [React Router docs: Router](https://reactrouter.com/en/main/router-components/router)
