### DISCUSSION TITLE
Excluding `dependabot` PRs using `branches-ignore`

### DISCUSSION THREAD

**Discussion by vy** [community/community#68308] [Actions] [answered]
### Select Topic Area

Question

### Body

I am having trouble making `branches-ignore` work in a workflow. Consider the following `build.yaml`:

```
# ...
on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    branches-ignore:
      - "dependabot/**"
# ...
```

I was expecting this to *not* trigger the workflow for PRs from `dependabot/`-prefixed branches. Though [see this `build.yaml` running for a PR from the `dependabot/test` branch](/vy/github-workbench/actions/runs/6310679609). Any ideas about what might I be missing?

For the record, I had following unsuccessful attempts too:

- without quotes
- with single quotes
- `branches: ["!dependabot/**"]`
