### DISCUSSION TITLE
My actions simply don't get triggered

### DISCUSSION THREAD

**Discussion by debych** [community/community#68408] [Actions]
### Select Topic Area

Bug

### Body

There is such github action

```
name: Publish Docker Image to Docker Hub.

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Publish to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: lendzlabs/notifications-service
          registry: docker.io
          tags: ${BRANCH_NAME}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
```

This file is pushed in `.github/workflows` dir to the specific branch (not main\master)

Nothing happens on push to that branch
