### DISCUSSION TITLE
Can CodeQL be configured to only scan the changed items?

### DISCUSSION THREAD

**Discussion by Liturgist** [community/community#68465] [Code Security]
### Select Topic Area

Question

### Body

When a pull is done which contains only one (1) change file, it appears that CodeQL scans the -complete- default branch of the repo. This takes time.

Is it possible to configure CodeQL to only scan the new and changed items? If so, how would that be expressed in the workflow .yml?

**Comment by Neved4** [comment]
I believe you could use `git diff`'s output as a series of steps to detect and analyze only the changed files:
```yaml
- name: Identify changed files
  run: |
    changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
    echo "Changed files: $changed_files"

- name: Build CodeQL database
  run: codeql database create <opts> $changed_files

- name: Run CodeQL analysis
  run: codeql database analyze <opts> ${{ github.workspace }}/codeql-db
```

**Comment by aeisenberg** [comment]
That's not a recommended way of running codeql. There are two reasons:

1. codeql takes into account global dataflow, a change in one file can trigger a vulnerability in another, unchanged file. Or, more likely, codeql will not be able to determine the declarations of functions that are outside of the changed file.
2. (Only for compiled languages: java, go, c, c++, kotlin) codeql requires hooking into the build system of the project you are scanning. Unless you can selectively build a single file of your project, you will have to build everything.

**Comment by Liturgist** [comment]
I pull .ps1, .psm1, and .psd1 scripts which CodeQL does not examine. I do not want to prevent CodeQL from running. It is doing important work. But, these pulls are not changing any file that CodeQL would analyze. Still, CodeQL must run over all of the Python files.

**Reply by aeisenberg** [reply]
That is a different scenario. You can change your workflow to avoid running when only those files are changed. See [the docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore).

You could do something like this:

```
on:
  push:
    paths-ignore:
      - '**/*.ps1'
      - '**/*.psm1'
      - ...etc
```
