### DISCUSSION TITLE
Container creation failed despite devcontainer creation returning a 0 exit code

### DISCUSSION THREAD

**Discussion by chalmiller1** [community/community#68474] [Codespaces]
### Select Topic Area

Question

### Body

Hi there,

We are currently setting up Codespaces with a Docker Compose file. During the startup process, the devcontainer startup is returning a 0 exit code and returning `Outcome: success User: root WorkspaceFolder: ../app`, but right after that I see a `Container creation failed.` message. Here are the files we are using, along with the error message:

`docker-compose.yml`:
```
version: '3.9'
services:
  web:
    command: bundle exec rdbg --open --host 0.0.0.0 --port 12345 --nonstop --command -- puma --port ${LEARNING_WEB_CONTAINER_PORT:-80} --bind tcp://0.0.0.0 --threads 4 --workers 1
    build:
      context: .
      args:
        - "NPMRC=[redacted]"
    working_dir: /working_dir
    deploy:
      resources:
        limits:
          memory: 2g
    volumes:
      - .:/working_dir
      - bundle-cache:/bundle # so bundle installed gems can be cached
      - yarn-cache:/usr/local/share/.cache/yarn/v6 # so yarn's global cache persists
      - webpack-data:/workramp/public/packs # persist data even if container shuts down
      - node-modules:/workramp/node_modules # share node_modules
      # let container have the following all to itself
      - /working_dir/public/packs-test # might be able to deprecate this requirement?
      - /working_dir/public/javascripts/i18n # maybe should never have been checked in to repo?
      - /working_dir/tmp # because rails is dirty with pid files sometimes, also doing this for tmp is probably a good call anyway
    ports:
      - "80:${LEARNING_WEB_CONTAINER_PORT:-80}" # web server
      - "12345:12345"
    depends_on:
      - db
      - redis
    environment:
      BUNDLE_GEMS__CONTRIBSYS__COM: [redacted]
      BUNDLE_ENTERPRISE__CONTRIBSYS__COM: [redacted]
      DATABASE_HOST: db
      DATABASE_NAME: [redacted]
      DATABASE_USER: [redacted]
      LAUNCH_DARKLY_USER_ID: [redacted]
      ACADEMY_HOSTS: [redacted] # pass through for development.rb hosts config
      PAGER: busybox less # otherwise pry gem uses some unavailable flags for the environment
      PIDFILE: /dev/null
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
      WEBPACKER_DEV_SERVER_HOST: webpack
      SMTP_ADDRESS: mail
    tty: true
    stdin_open: true
    networks:
      default:
        aliases:
          - [redacted]

  webpack:
    command: bin/webpack-dev-server
    build:
      context: .
      args:
        - "NPMRC=[redacted]"
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - 3035:3035 # webpack hot module reload
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/working_dir
      - bundle-cache:/bundle # so bundle installed gems can be cached
      - yarn-cache:/usr/local/share/.cache/yarn/v6 # so yarn's global cache persists
      - webpack-data:/working_dir/public/packs # persist data even if container shuts down
      - node-modules:/working_dir/node_modules # share node_modules

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: [redacted]
      POSTGRES_USER: [redacted]
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432 # so we can connect local software to our dev db

  redis:
    image: redis:7.0.7
    ports:
      - 6379:6379

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  webpack-data: # named volumes can be managed easier using docker-compose
  bundle-cache: # to cache bundled gems
  node-modules: # to cache node modules
  yarn-cache: # to cache yarn's global cache
  caddy_data: # For caddy's persisted data
```

`Dockerfile.yml`:
```
FROM ruby:3.1.4-slim

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
    build-essential \
    git \
    pkg-config \
    libvips \
    curl \
    node-gyp \
    libpq-dev \
    shared-mime-info \
    ffmpeg \
    tzdata \
    net-tools \
	; \
	rm -rf /var/lib/apt/lists/*

# Install node
ARG NODE_VERSION=16.15.0
ARG YARN_VERSION=1.22.19
ENV PATH=/usr/local/node/bin:$PATH
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    npm install -g yarn@$YARN_VERSION && \
    rm -rf /tmp/node-build-master

WORKDIR /working_dir

# specify bundle location so we can use a volume to store installed gems
ENV BUNDLE_PATH=/bundle
ENV BUNDLE_BIN=/bundle/bin
ENV GEM_HOME=/bundle
ENV PATH="${BUNDLE_BIN}:${PATH}"

RUN gem install bundler -v 2.4.6 --no-document

ARG NPMRC
RUN test -n "$NPMRC" || (echo "Must run 'export NPMRC=\$(cat ~/.npmrc|base64)' before building image to install private yarn packages" && exit 1)
RUN sh -c 'echo $NPMRC| base64 -d > ~/.npmrc'
```

`devcontainer.json`
```
{
    "name": "Web CodeSpace",
    "dockerComposeFile": "../docker-compose.yml",
    "service": "web",
    "workspaceFolder": "../app"
}
```

Here's the - from what I can tell - relevant part of the error log:
```
2023-09-27 16:23:58.980Z: Outcome: success User: root WorkspaceFolder: ../app
2023-09-27 16:23:58.993Z: devcontainer process exited with exit code 0

====================================== ERROR ====================================
2023-09-27 16:24:01.017Z: Container creation failed.
```
