### DISCUSSION TITLE
Extra Newline in Output in Multi-Output Job Step

### DISCUSSION THREAD

**Discussion by tylertitsworth** [community/community#68472] [Actions]
### Select Topic Area

Bug

### Body

Say I have a bash script like so:
```bash
#!/bin/bash
# Input string
input_string="$1"

# Find the line that contains '/my-command'
if [[ $input_string == *"/my-command"* && $input_string == *"#"* ]]; then

  input_string="${input_string#*\/my-command}"
else
  # If the pattern is not found, exit
  echo "Error: The input string does not contain a line with '/my-command'."
  exit 1
fi

# Extract key-value pairs from the matched line
IFS=',' read -ra pairs <<< "$input_string"
# Loop through the key-value pairs
for pair in "${pairs[@]}"; do
  # Remove leading and trailing spaces
  pair="${pair// /}"

  # Check if the pair contains "=" or ":"
  if [[ $pair == *"="* ]]; then
    # Extract the key and value using "=" as the separator
    key="${pair%%=*}"
    value="${pair#*=}"
  elif [[ $pair == *":"* ]]; then
    # Extract the key and value using ":" as the separator
    key="${pair%%:*}"
    value="${pair#*:}"
  else
    # If neither "=" nor ":" is found, skip this pair
    continue
  fi
  # Send to GitHub Outputs
  echo "$key=$value" >> $GITHUB_OUTPUT
done
```
and I execute it in a GitHub Action like so:
```yaml
name: My GitHub Action
on:
  pull_request:
    types: [edited]
jobs:
  my-action:
  ...
  outputs:
    key1: ${{ steps.my-action.outputs.key1 }}
    key2: ${{ steps.my-action.outputs.key2 }}
  ...
  steps:
    - name: Get Inputs
      id: comment-inputs
      run: bash my-script.sh "${{ github.event.pull_request.body }}"
```
With a pull request body of:
```markdown
# Header
...
command: /my-command key1: val1, key2: val2
...
```
when I later re-use these outputs, the last output `key2:val2`'s value will include a newline when getting passed as an argument during job execution.
Example:
```yaml
- name: Get Directory
  run: cat "./${{ needs.my-action.outputs.key2 }}/filename.txt"
```
will execute as:
```
cat "./val2
/filename.txt"
```

Correct: 
![image](https://github.com/community/community/assets/43555799/f5592177-6901-4b21-98aa-20a018ac40e6)

Incorrect: 
![image](https://github.com/community/community/assets/43555799/fa78ff8d-b7da-41ba-a970-552fccb5dd85)

How can I modify my bash script to workaround this issue? I have tried truncating the last newline output from the last key:value pair, but that just causes actions to not pick up the last value. I have verified that my script's input is only the word, and not any extra whitespace by removing the `>> $GITHUB_OUTPUT` and appending `| tr ' \n' '#$'` onto the end of my command to ensure that there is no extra whitespace being sent to actions.
