### DISCUSSION TITLE
How do I upload `.gitignore`'d files as artifacts?

### DISCUSSION THREAD

**Discussion by ero-qt** [community/community#68507] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi,

I am building a .NET app via a GitHub runner. I would like to upload the resulting binaries as artifacts to use in another job. Of course, these binaries should never be committed normally. Thus, I ignore them. This results in the warning `No files were found with the provided path`.

How can I work around this?

**Comment by Neved4** [comment]
Have you tried specifying them manually within the action?

```yml
- name: Upload artifacts
  uses: actions/upload-artifact@v2
  with:
    name: artifacts
    path: |
      ./path-some-artifact
      ./path-other-artifact
  ```
  
 Alternatively, you can programatically list the files with a `git` call, using `git ls-files -i --exclude-standard -o` or `git clean -Xdn`:
```yml
- name: List ignored files
  run: |
    git clean -Xdn | cut -d' ' -f3 > ignored.txt
```
