### DISCUSSION TITLE
Chained ternary operator on runs-on in Github actions workflow yml

### DISCUSSION THREAD

**Discussion by dadom12345** [community/community#68534] [Actions]
### Select Topic Area

Question

### Body

Hi all,

i am currently trying to make a two-conditional runs-on statement but it somehow seems not to work. even when inputs.stage is set to "--stage" as default its always taking "project-standard" as label it seems

Can you please show me the correct approach if you have two conditions where project-force-build label should be used instead of project-standard?

Thanks!
```
name: Development

  push:
    branches:
      - "develop"
  workflow_call:
    inputs:
      do_forcebuild:
        type: boolean
        default: false
      stage:
        type: string
        default: "--stage"

jobs:
  build-project:
    name: Build Project
    runs-on: ${{ inputs.do_forcebuild == true && 'project-force-build' || (inputs.stage == '--stage' && 'project-force-build' || 'project-standard') }}


```

**Comment by socketbox** [comment]
Thanks for this sample syntax of a chained ternary expression.

For those coming to this question wondering (as I did) if, in general, chained ternary expressions are valid in workflows, here's a working proof of concept:
```
name: Chained Ternary Test
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'app name'
        required: true
        default: 'foo'
        type: string

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test step
        run: |
          echo "result: $withvar"
        env:
          withvar: ${{ inputs.app == 'foo' && 'foo-bg-deploy' || ( inputs.app == 'bar' && 'star-bar-bg-deploy' || 'rocket-lite-bg-deploy' )}}
```

When I provide the app input with a string that does not match `foo` or `bar` it echoes `rocket-lite-bg-deploy`.
