### DISCUSSION TITLE
How to run scripts belonging to the reusable workflow repo?

### DISCUSSION THREAD

**Discussion by dkirrane** [community/community#68735] [Actions]
### Select Topic Area

Question

### Body

I think this is a limitation of reusable workflows but doesn't seem to be called out in the [docs ](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)??

My reusable workflow throws `No such file or directory` when trying to run a script in it's repo:
![image](https://github.com/community/community/assets/1280116/30c7ef3a-8016-44e2-8a8c-f247e885239a)

What is the recommended way to do this? Do I need to change the path to the script? Is there some location to where the reusable workflow is cloned to?

I have this reusable workflow in a remote repo:
`test.sh` exists in reusable workflow repo.
```yaml
on:
  workflow_call:

jobs:

  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script file
        run: |
           chmod +x ./test.sh
           ./test.sh
        shell: bash
```

This is the caller workflow calling reusable workflow above:
```yaml
on:
  workflow_dispatch:

jobs:

  Call:
    uses: company/my-repo/.github/workflows/test.yml@main
    secrets: inherit
```

**Comment by dkirrane** [comment]
Looks like its a Reusable workflow limitation. This should really be called out clearly in the docs.

I need to switch to using a Composite action instead
https://stackoverflow.com/questions/72133102/how-to-execute-a-a-remote-script-in-a-reusable-github-workflow

**Reply by brianjmurrell** [reply]
Composite actions are not substitutable for workflows 1:1.  Workflows can have multiple jobs.  Workflows would have to be broken down in to any number of composite actions which would have to be called one after another in the caller (that used to have a single reference to a reusable workflow).

Start duplicating this across dozens of repos/projects and you are back to the DRY problem you tried to solve with reusable workflows.

TL;DR: here is that GH still have a lot of work to do to eliminate (or at least greatly reduce) the amount of duplicate code we are copying to every repo, and the efforts we are expending keeping all of those duplications in sync.

**Comment by yogesh-mishra-pagero** [comment]
Have been searching the same, seems like embedding the scripts in the yaml with the run task is the way to go ! Any other suggestions ?

**Reply by brianjmurrell** [reply]
That's a horrible requirement.  The main reason for putting scripts into their own files is so that they can be used in more than one place **AND** they are lintable.  Big scripts in `run:` tasks are a nightmare to maintain.

**Comment by marco-merola-ef** [comment]
You have to define your **composite action** and then call it from your reusable workflow.
Embedding the script within the reusable workflow may work but only if the script is few lines.

https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

**Reply by grandmas-favorite** [reply]
Nice one @marco-merola-ef! 

That's what I would have suggested as well!

**Comment by antoninnoel** [comment]
Hey ! Did you figure it out?

**Reply by brianjmurrell** [reply]
Figure what out?

**Reply by antoninnoel** [reply]
How to run scripts belonging to the reusable workflow repo?

**Comment by ejimz** [comment]
If anyone is still having trouble, I managed to resolve it by using Docker. I created a Dockerfile, added the necessary scripts, and ran it within Docker.
I used this configuration in the GA reusable workflow https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions

**Comment by cerossi** [comment]
Posting for future reference. As answered by micguo [here](https://stackoverflow.com/questions/72133102/how-to-execute-a-a-remote-script-in-a-reusable-github-workflow), using the ${{ github.action_path }} context variable seems to be the real way to go in such a case.

By running a simple find I managed to find out that my action script (as well as all its repo content) was stored in github runner file system under the path /opt/actions-runner/my_org/my_custom_action_repo/[branch|tag]/.

As ${{ github.action_path }} was equal to /opt/actions-runner/my_org/my_custom_action_repo/[branch|tag]/, I was able to seamlessly run the scripts versioned in my action repo.

**Reply by AjaySinghSAP** [reply]
Is this for composite action or reusable workflow? 
For me, the reusable workflow is failing to run the script this way.

**Comment by djaboxx** [comment]
I get around this by pulling the file directly from its "raw" url in GitHub user content. Any file in a public repository can be pulled directly from its "raw" url. 

For instance, https://github.com/HappyPathway/centralized-actions/blob/main/.github/workflows/gtag.yml#L59

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Reply by kambhamj** [reply]
it is not resolved

**Comment by brianjmurrell** [comment]
None of the 3 options provided in https://github.com/orgs/community/discussions/68735#discussioncomment-11503544 apply.  This question is simply not yet answered.  But it's now closed as both Closed **and** Unanswered.  How does that square? 

Oh wait.  I know.  Let's just try to close everything even if it's not actually resolved.

The community's goal should not be to close discussions regardless of outcome but should be to actually answer questions with a meaningful answer.  And leave them opened until a meaningful answer is provided.

Please reopen this discussion until a reasonable answer is provided.

**Comment by isyarov** [comment]
I too feel that the question remains unanswered. Even if the approach (or should I say the workaround) with ${{ github.action_path }} might work for a step of a job which runs directly on the runner, it does not work when the step is part of a job which is running in a container e.g. when we have
```
...
jobs:
  job:
    runs-on: <runner>
    container:
      image: <image>
    steps:
      - name: run-script
        uses: <composite-action>
```
and for the composite action we have
```
...
runs:
  using: 'composite'
  steps:
    - name: run-script
      shell: bash
      run: ${{ github.action_path }}/script.sh
```
In the above case ${{ github.action_path }} expands to the location of the action on the runner and not the location on which it was mounted in the container

**Comment by kambhamj** [comment]
is there any solution for this..?

**Reply by upld-brickerson** [reply]
Yeah I figured out a way to do it, but it's a bit dumb. I created another repository for scripts that are being used in my reusable workflows. What happens is, during my workflow, that 3rd repo is cloned and the script is used from there.

So for example, let's say I have these 3 repos `my-workflows`, `my-scripts`, and `application`. 

`my-workflows` - reusable workflows
`my-scripts` - scripts repo
`application` - the downstream repo that is using the reusable workflows

**Example reusable workflow**
```yaml
name: My Workflow

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: 'GitHub token for authentication'
        required: true

jobs:
  my_job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: my-org/my-scripts
          path: scripts
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Run the script
        run: |
          python3 scripts/my-script.py
```

The `application` repo uses the `My Workflow` action and it's able to use the script without any issues.

**Example application workflow**
```yaml
name: Downstream Workflow

on:
  workflow_dispatch:

jobs:
  downstream_workflow:
    name: Downstream Workflow
    uses: my-org/my-workflows/.github/workflows/script-workflow.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
```
