### DISCUSSION TITLE
Ordering of matrix jobs when running

### DISCUSSION THREAD

**Discussion by sohail-mp** [community/community#68732] [Actions]
### Select Topic Area

Bug

### Body

Given we have a parent workflow with a matrix job that calls a reusable child workflow that also has a matrix and this child workflow also calls a reusable workflow.  When Job "a" depends on job "b", after job "a" completes, job "b" starts running and appears in a position above job "a".  When the job completes the order sometimes changes and sometimes stays the same. 

Is this intentional? because its make it hard to read the flow of deployment

<img width="349" alt="image" src="https://github.com/community/community/assets/92020439/b99cebf2-f062-4fcd-b118-baf6900b2f89">

Here are my 3 example workflow files:

`matrix.yml` uses `_child-matrix.yml` which uses `grand-child.yml`

`matrix.yml`
```yml
name: matrix

on:
  workflow_dispatch: # manual trigger
  push: # push to all branches
jobs:
  dev:
    uses: ./.github/workflows/_child-matrix.yml
    strategy:
      matrix:
        brand: [sky, virgin]
      fail-fast: false
    with:
      environment: development
      brand: ${{ matrix.brand }}
  uat:
    needs: dev
    uses: ./.github/workflows/_child-matrix.yml
    strategy:
      matrix:
        brand: [sky, virgin]
      fail-fast: false
    with:
      environment: uat
      brand: ${{ matrix.brand }}
  prod:
    needs: uat
    uses: ./.github/workflows/_child-matrix.yml
    strategy:
      matrix:
        brand: [sky, virgin]
      fail-fast: false
    with:
      environment: prod
      brand: ${{ matrix.brand }}
```

`_child-matrix.yml`
```yml
name: _child-matrix

on:
  workflow_call: # reusable workflow
    inputs:
      environment:
        required: true
        type: string
      brand:
        required: true
        type: string

jobs:
  deploy-a:
    strategy:
      fail-fast: false
      matrix:
        region: [east, west]
    uses: ./.github/workflows/_grand-child.yml
    with:
      environment: ${{ inputs.environment }}
      brand: ${{ inputs.brand }}
      region: ${{ matrix.region }}
  deploy-b:
    needs: deploy-a
    strategy:
      fail-fast: false
      matrix:
        region: [north, south]
    uses: ./.github/workflows/_grand-child.yml
    with:
      environment: ${{ inputs.environment }}
      brand: ${{ inputs.brand }}
      region: ${{ matrix.region }}
```

`_grand-child.yml`
```yml
name: _grand-child
on:
  workflow_call: # reusable workflow
    inputs:
      environment:
        required: true
        type: string
      brand:
        required: true
        type: string
      region:
        required: true
        type: string

jobs:
  component-a:
    name: A - ${{ inputs.environment }} - ${{ inputs.brand }} - ${{ inputs.region }}
    runs-on: ubuntu-latest
    steps:
      - run: echo DELAY=$(( ( RANDOM % 10 )  + 1 )) >> $GITHUB_ENV
      - run: sleep ${{ env.DELAY }}
      - run: echo "Deploying brand ${{ inputs.brand }} to env ${{ inputs.environment }}"
      - run: sleep ${{ env.DELAY }}
      - run: echo "Deploying component A to ${{ inputs.region }}"
      - run: sleep ${{ env.DELAY }}
  component-b:
    name: B - ${{ inputs.environment }} - ${{ inputs.brand }} - ${{ inputs.region }}
    needs: component-a
    runs-on: ubuntu-latest
    steps:
      - run: echo DELAY=$(( ( RANDOM % 10 )  + 1 )) >> $GITHUB_ENV
      - run: sleep ${{ env.DELAY }}
      - run: echo "Deploying brand ${{ inputs.brand }} to env ${{ inputs.environment }}"
      - run: sleep ${{ env.DELAY }}
      - run: echo "Deploying component B to ${{ inputs.region }}"
      - run: sleep ${{ env.DELAY }}

```

In this example prod is showing before uat, however the dependencies are quite clear that it should be after:

<img width="1414" alt="image" src="https://github.com/community/community/assets/92020439/316d1cf4-9cc8-42d2-901b-4b73fd612f31">

I believe this to be a bug in the left panel that lists the jobs of a Github action run.  Please can this be looked into.
