### DISCUSSION TITLE
command "git push" inside to runner

### DISCUSSION THREAD

**Discussion by rodrigociro** [community/community#68891] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello guys, Could you help me with one doubt?
I just trying to make change in the runner (development branch) after that my goal is push this change in development branch and merge to master branch. I just execute my job inside of the runner. this is the following command:

echo "1.0.0" > VERSION
git config user.email "user@hotmail.com"
git config user.name "Name Surname"
git add . 
git commit -m "create version file"
git push
git push https://USER:${{ secrets.PASSWORD}}@github.com/OWNER/REPO.git BRANCH

The both command give me a 403 error.

Do Github Actions allow us to do this?

Regards.
Rodrigo

**Comment by harxh-v** [comment, marked as answer]
Dear @rodrigociro 

The 403 error you're encountering indicates that you do not have the necessary permissions to push to the repository or branch. GitHub Actions allow you to automate various tasks, including pushing changes to a repository, but you need to ensure that you have the correct permissions and that you're using the correct credentials in your workflow.

Here are some steps to troubleshoot and potentially resolve the issue:

1. **Check Permissions**:
   - Ensure that the GitHub user associated with the provided email address ("user@hotmail.com") has the necessary permissions to push to the repository. You need to have write access to the repository to push changes.

2. **Secrets**: Double-check that the `secrets.PASSWORD` secret you are using in your `git push` command is correctly defined in your repository's GitHub Secrets. Go to your repository on GitHub, navigate to Settings > Secrets, and verify that the secret name matches.

3. **Authentication**:
   - Make sure you're using the correct format for your Git credentials. The URL in your `git push` command should include your GitHub username and a Personal Access Token (PAT) or password. Ensure that `${{ secrets.PASSWORD }}` is correctly replaced with the actual secret value.
   - When using a PAT, it should have the necessary permissions to push to the repository. If you're using a password, make sure it's the correct password for the GitHub account with write access to the repository.

4. **Workflow Environment**:
   - Ensure that your GitHub Actions workflow is running in an environment where it has access to the necessary credentials. GitHub provides certain environment variables like `GITHUB_TOKEN` that you can use for authentication in your workflows. Consider using these built-in tokens for authenticating with GitHub.

Here's an example of how you might use `GITHUB_TOKEN` in your workflow:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make and push changes
      run: |
        echo "1.0.0" > VERSION
        git config user.email "user@hotmail.com"
        git config user.name "Name Surname"
        git add .
        git commit -m "create version file"
        git push
```

GitHub Actions' built-in token, `GITHUB_TOKEN`, typically has the necessary permissions to push changes back to the repository where the workflow is running. You don't need to specify a username or password when using it.

If the issue persists, double-check your permissions, secrets, and authentication credentials. Additionally, you can review the GitHub Actions logs for more specific error messages that might provide insights into what's causing the 403 error.

**Comment by l3aalteshuva** [comment]
-author:l3aalteshuva

`from time, if name : main 
then import sys && import os;

  jobs:
    build:
      runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make and push changes
      run: |
        echo "1.0.0" > VERSION
        git config user.email "l3aalteshuva"
        git config user.name "l3aalteshuva"
        git add .
        git commit -m "create version file"
        git push`

**Comment by 1amkaiz3n** [comment]
Yes, GitHub Actions allow you to push changes to a repository, including creating commits and merging branches. However, when using GitHub Actions, you should avoid hardcoding passwords or sensitive information directly in the scripts due to security concerns.

In your script, you are attempting to push using a hardcoded username and password which is not recommended and can lead to security risks. GitHub provides a safer way to authenticate actions using personal access tokens (PATs) or secrets.

Here's a recommended approach to push changes in GitHub Actions:

1.Create a Personal Access Token (PAT):
Go to your GitHub account settings, then navigate to "Developer settings" > "Personal access tokens" and generate a new token. Make sure to give it the necessary permissions for the repository actions you intend to perform.

2.Add the Personal Access Token as a GitHub Secret:
In your GitHub repository, go to "Settings" > "Secrets" and add a new secret with the name you prefer (e.g., **GH_TOKEN**) and the value of your personal access token.

3.Modify Your GitHub Actions Workflow:
Update your GitHub Actions workflow to use the provided secret to authenticate. Here's an example:

```
name: Push to GitHub

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "user@hotmail.com"
          git config user.name "Name Surname"

      - name: Create version file
        run: echo "1.0.0" > VERSION

      - name: Commit version file
        run: |
          git add .
          git commit -m "Create version file"

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push https://USERNAME:${GH_TOKEN}@github.com/OWNER/REPO.git BRANCH

```


Replace **USERNAME** with your GitHub username, **GH_TOKEN** with the secret you created,  **OWNER** with the GitHub account or organization, **REPO** with the repository name, and **BRANCH** with the branch you want to push to.

This way, you're using a GitHub secret to authenticate the push, enhancing security while achieving your goal of pushing changes in the GitHub Actions workflow.
