### DISCUSSION TITLE
Cannot use a reusable workflow recursively

### DISCUSSION THREAD

**Discussion by ffisc** [community/community#68997] [Actions]
### Select Topic Area

Bug

### Body

Take for instance the following workflow:

```
on:
  workflow_call:
    inputs:
      retry:
        description: 'Run the workflow a second time'
        type: boolean
        required: true
        default: true

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.retry }}  # Anything else

  retry:
    if: inputs.retry == true
    uses: ./.github/workflows/this-workflow.yaml
    with:
      retry: false
```

It will, by definition, always call itself at most once.
However, when trying to run it, the error message says
```
: job "retry" calls workflow "/.github/workflows/this-workflow.yaml, but doing so would exceed the limit on called workflow depth of 3
```

I don't understand why
