### DISCUSSION TITLE
Group Dependabot PRs for GitHub Actions updates

### DISCUSSION THREAD

**Discussion by 3f6a** [community/community#69099] [Actions] [answered]
### Select Topic Area

Question

### Body

Is there a way to configure Dependabot so that all PRs related to updates to GitHub Actions workflows are bundled together in a single PR?

**Comment by Zerotask** [comment, marked as answer]
You have this option: https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

```yaml
version: 2
  updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: weekly
    # New!
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      dev-dependencies:
        # A pattern can be...
        patterns:
          - "rubocop" # a single dependency name
          - "aws*"  # or a wildcard string that matches multiple dependencies
          # If you'd simply like to group as many dependencies together as possible, 
          # you can use the wildcard * - but keep in mind this may open a very large PR!
        # Additionally, you can specify any dependencies to be excluded from the group
        exclude-patterns:
          - "aws-sdk"
```  
(from the blog article)
