### DISCUSSION TITLE
`paths` matching more than expected

### DISCUSSION THREAD

**Discussion by dmmartins** [community/community#69131] [Actions]
### Select Topic Area

Question

### Body

Hi, I have this config on my actions

```
on:
  push:
    paths:
      - docker/*
    branches-ignore:
      - acceptance
```

and I expected that would only trigger a build when something on the `docker` folder changed, but it's triggering the build for other changes, that don't touch that folder and don't have `docker` on the path of any of the changed files.
if had `docker/**` before and it has same behavior. tried `/docker/*` and it doesn't match anything, not even changes on files on `docker/`
that is very similar to the example on the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths). What am I missing?
