### DISCUSSION TITLE
Running python scripts in CI and accessing nfs paths

### DISCUSSION THREAD

**Discussion by kgleeson2** [community/community#69146] [Actions]
### Select Topic Area

Question

### Body

I'm trying to move my python project to github and utilize the CI features. Previously, we used git with gerrit, and it was simple enough to use my regular nfs path files and folders, and to access the outputs also from nfs. So far, with github CI, I haven't been able to find documentation that would support a similar need. I'm sure it exists though. My scripts dynamically will need to pick up files/folders from nfs in the scripts, and I'd prefer to write here as well, so that I can utilize the gui if needed and look around at my results (although this part isn't quite as necessary). When I try to run, it launches but I get errors that cannot write to nfs filesystem. Are there tips or documentation pages that can help? This is what my yaml has currently (then the program reads input files included in the repo):

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |                 
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: get env
      run: env 
    - name: Test with pytest
      run: |
        python myscript input_file1 input_file2

**Comment by ghost** [comment]
To run Python scripts in a Continuous Integration (CI) environment and access NFS paths, you can follow the steps below. This solution assumes that you are using GitHub Actions as your CI system and that the NFS server is set up and accessible:

Install NFS Client:
Add a step in your YAML file to install the NFS client on the GitHub Actions runner.
````
- name: Install NFS Client
  run: |
    sudo apt-get update
    sudo apt-get install -y nfs-common
````
Mount NFS:
Add a step to mount the NFS path on the runner.
```
- name: Mount NFS
  run: |
    sudo mkdir -p /mnt/nfs
    sudo mount -t nfs 192.168.1.100:/exported_directory /mnt/nfs  # Replace with your NFS server IP and exported directory
```
Adjust Paths in Python Script:
Modify your Python script to use the mounted NFS paths.
```
with open('/mnt/nfs/input_file1', 'r') as file:
    # Read contents of input_file1

with open('/mnt/nfs/output_file', 'w') as file:
    # Write results to output_file
```
Run Python Script:
In your YAML file, adjust the step that runs your Python script to use the mounted NFS paths.
```
- name: Test with pytest
  run: |
    python myscript /mnt/nfs/input_file1 /mnt/nfs/input_file2
```
The complete YAML file will look like this:
```
name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |                 
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install NFS Client
      run: |
        sudo apt-get update
        sudo apt-get install -y nfs-common
    - name: Mount NFS
      run: |
        sudo mkdir -p /mnt/nfs
        sudo mount -t nfs 192.168.1.100:/exported_directory /mnt/nfs  # Replace with your NFS server IP and exported directory
    - name: get env
      run: env 
    - name: Test with pytest
      run: |
        python myscript /mnt/nfs/input_file1 /mnt/nfs/input_file2
```
Replace 192.168.1.100:/exported_directory with your NFS server IP and exported directory, and adjust the file paths in the Test with pytest step as needed.
