### DISCUSSION TITLE
Accessing secrets in github pages

### DISCUSSION THREAD

**Discussion by calbertan** [community/community#69173] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I have a Next.js application and on my local machine. I have provided it with some environment variables in my .env file. I am accessing said variables by calling process.env.VARIABLE and it is working for both dev and prod.

When deploying my application through github actions, these secrets are undefined. I am using next.js workflow provided by github actions to deploy the website. Here are the things I have done so far:

1. add environment secrets to the 'github-pages' environment
2. add repository secrets and provide them to the deploy step in actions

This is the current deploy step that I have
```
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: https://github.com
    runs-on: ubuntu-latest
    needs: build
    env:  
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
I am pretty stuck and unsure if there is something that I am missing. Any help would be appreciated!
