### DISCUSSION TITLE
Infinite build process

### DISCUSSION THREAD

**Discussion by hovo92000** [community/community#69190] [npm] [answered]
### Select Topic Area

Bug

### Feature Area

Issues

### Body

Hi!
I trying to deploy my project.It always worked correct, but now it takes a lot of time for building app and don't end building.I didn't change nothing.
1)this is the log from GitHub
2023-10-03T18:43:45.9941224Z Requested labels: ubuntu-latest
2023-10-03T18:43:45.99415657 Job defined at: myRepo/directory/ github/workflows/main-yml@refs/heads/main
2023-10-03T18:43:45.9941674Z Waiting for a runner to pick up this job...
2023-10-03T18:43:46.9408124Z Job is waiting for a hosted runner to come online.
2023-10-0371:43:49.71578372 Job is about to start running on the hosted runner: GitHub Actions 1 (hosted)
2)This is log of process 
Run npm run build
> frontend@0.1.0 build
> vue-cli-service build
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.
-  Building for production... (edited) 

### Guidelines

- [x] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).

This is my main.yml
```
name: FTP Deploy

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build Vue.js app
        run: npm run build
        working-directory: frontend

      - name: frontend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4

        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_FRONT_USER }}
          password: ${{ secrets.FTP_FRONT_PASSWORD }}
          local-dir: ./frontend/dist/
          remote-dir: /

      - name: backend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_BACK_USER }}
          password: ${{ secrets.FTP_BACK_PASSWORD }}
          local-dir: ./backend/
          remote-dir: /
```
