### DISCUSSION TITLE
Passing environment variables to utility functions

### DISCUSSION THREAD

**Discussion by mjgs** [community/community#69262] [Actions]
### Select Topic Area

Question

### Body

I have an npm module cache step as follows:

```
- name: Cache NodeJS dependencies 
  if: ${{ env.cache_enabled == 'yes' }}
  id: cache
  uses: actions/cache@v3
  with: 
    path: ${{ env.repo_dir }}/node_modules
    key: modules-${{ hashFiles('repo/package-lock.json') }}
```

The repo directory used in the key value is actually stored in the $repo_dir env variable. I have hard coded the value to ‘repo’ just to get something working, but I’d like to use the env variable. 

As far as I gather, I can’t use 
${{ env.repo_dir }} since that would result in a nested expression, which I guess isn’t allowed. Is that right?

How can I use the $repo_dir variable to construct the path that gets passed to hashFiles?
