### DISCUSSION TITLE
Workflow not starting after push anymore

### DISCUSSION THREAD

**Discussion by GuyLescalier** [community/community#69289] [Actions]
### Select Topic Area

Bug

### Body

Hello,

We are using GitHib Server (on prem) 3.8.2 (upgarded to 3.8.10 hoping it would fix the issue but it didn't).

Since about a week or two, our build workflow stopped triggering on push and pull requests.
We added the `workflow_dispatch` to trigger it manually which works fine.

The runner is reported as available in the repository config :
![image](https://github.com/community/community/assets/44168224/d21363f6-9712-46fb-a90c-49d597d195d5)

Here is the event config part of the workflow :
```
on:
  workflow_dispatch:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
```

Is there a way to debug this issue ? Log file showing events occurring on a repository and why workflows are picked or discarded ?

Thanks for your help
