### DISCUSSION TITLE
workflow not triggering on PR setup.. Why?

### DISCUSSION THREAD

**Discussion by DavidSagan** [community/community#69502] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I have a workflow that automatically creates a PR

```
name: dcs-push

on:
  push:
    branches-ignore: main

#
jobs:
  create-pull-request:
    if: ${{ github.triggering_actor == 'DavidSagan' }}

    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: gh pr create -B main -H ${{ github.ref_name }} --title "${{ github.ref_name }}" --body "${{ github.event.head_commit.message }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

This works fine. Another workflow should be triggered by a PR and do some testing:

```
name: Build & Test

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main
  push:
    branches:
      - "main"

  # Run on pull requests
  pull_request:
```

Normally this second workflow is triggered when a PR is created. However when the PR is created by the  first workflow the second workflow is not triggered which is not what I want. Example is: <https://github.com/DavidSagan/bmad-ecosystem/pull/8>.

How do I fix this so that the  second workflow is triggered by a PR created by the first workflow?
