### DISCUSSION TITLE
github action slowness causing cypress test case to fail

### DISCUSSION THREAD

**Discussion by EashBhanu-CCD** [community/community#69579] [Actions]
### Select Topic Area

Question

### Body

Github action is not working as expected or even slow as compared to my local and TC gets failed in github action, can anyone pls suggest if i can run on some specific server or put timeout in github action yaml file below is my github action yaml file

```
name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          browser: chrome
          spec: cypress/e2e/Customer.cy.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
