### DISCUSSION TITLE
Ways to ignore security updates via dependabot.yml

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#69580] [Code Security]
### Select Topic Area

Question

### Body

I have a large monorepo.

I am only interested in the security updates of say 4 out of 10 folders (each folder is a project).

If I use a `dependabot.yaml` like this

```yaml

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/folder1"
    schedule:
      interval: "daily"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
  - package-ecosystem: "go"
    directory: "/folder2"
    schedule:
      interval: "daily"
    # Disable version updates for go dependencies
    open-pull-requests-limit: 0
.
.

```

so that it includes only the folders of interest, will it automatically ignore the rest of the folders or does it need an explicit `ignore` for them?
