### DISCUSSION TITLE
How to configure Dependabot to create PRs for security vulnerabilities on a branch other than the main one

### DISCUSSION THREAD

**Discussion by davidfstr** [community/community#69615] [Actions]
### Select Topic Area

Question

### Body

I would prefer that Dependabot create PRs not on the main branch but a different branch (`develop`). I have tried to tell Dependabot to only use the `develop` branch by specifying that branch as the `target-branch` in the `dependabot.yml` configuration file:

```
# .github/dependabot.yml
version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"  # where to find: pyproject.toml, poetry.lock
    schedule:
      interval: "weekly"
    target-branch: "develop"
    # Disable all updates except security updates
    ignore:
      # Disable all updates except security updates
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
```

However I see in [this documentation](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) that "target-branch" is ignored:

> Note: In order for Dependabot to use this configuration for security updates [...] you should not specify a target-branch.

How can I tell Dependabot to create PRs related to security updates on a custom branch?
