### DISCUSSION TITLE
Setting `ubuntu-18.04` runner label makes the job hang

### DISCUSSION THREAD

**Discussion by rhysd** [community/community#69688] [Actions]
### Select Topic Area

Bug

## Repro

1. Create some repository on github.com
2. Write the following contents to `.github/workflows/test.yml` and push it to github.com
3. GitHub Actions tries to run the `test.yml` workflow and hangs

```yaml
on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - run: echo hello
```

## Expected behavior

`ubuntu-18.04` is no longer available so it should cause some error and stop the job run

## Actual behavior

The job run hangs with the following message in the build log:

```
Requested labels: ubuntu-18.04
Job defined at: your-name/your-repo/.github/workflows/test.yml@refs/heads/main
Waiting for a runner to pick up this job...
```

I confirmed the job didn't stop after 10 minutes.
