### DISCUSSION TITLE
Docker authentication failing when downloading private service containers

### DISCUSSION THREAD

**Discussion by DanielArmyrConversy** [community/community#69690] [Actions]
### Select Topic Area

General

### Body

I am trying to implement a CI/CD pipeline where we build a docker image and upload to a private registry in one step. In the next step, we download that same container back as a service container. We can then interact with it from the outside just like an end user would.

The error message I am getting when trying to download the container from the private registry as a service container is the following:

```
/usr/bin/docker --config /home/runner/work/_temp/.docker_89dc3924-6afb-4e25-befa-165b2a39812b login  -u DanielArmyrConversy --password-stdin
  Error: Docker login for '' failed with exit code 1
```

The relevant part of the GitHub Actions script is as follows:
```
name: Test

env:
  IMAGE_NAME_GH: 'ghcr.io/conversy-ai/conversy-web-client:commit-${{github.sha}}'

jobs:  
  docker-build:
    name: "Docker build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Build the docker"
        run: |          
          docker build . -t ${IMAGE_NAME_GH}
      - name: "Upload to Github"
        run: |           
          echo '${{secrets.GH_REGISTRY_KEY}}' | docker login  -u ${{ github.actor }} --password-stdin https://ghcr.io                     
          docker push ${IMAGE_NAME_GH}

  service-test:
    name: "Service Test"
    needs: [docker-build]
    runs-on: ubuntu-latest
    services:
      frontend:
        image: ${IMAGE_NAME_GH}
        ports:
          - 3000:3000
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REGISTRY_KEY }}
    steps:
      - name: "APT test"
        run: |
          # Run some scripts that test the APIs
```

What has me stumped is that when I do the login myself at the end of the `docker-build` step, it works perfectly. But then when I use the same credentials to try to use the build-in login feature, I get the above error message.

I have tried running in debug mode, but it gives no additional information on what happened during the login command itself.
