### DISCUSSION TITLE
Is it possible to use an expression in concurrency cancel-in-progress

### DISCUSSION THREAD

**Discussion by sandermvanvliet-stack** [community/community#69704] [Actions]
### Select Topic Area

Question

### Body

I have a workflow where for pull requests I want the workflow to cancel any in-progress run if a new commit is pushed to the PR branch but for the `main` branch have the workflows run to completion (but still limit to 1 active workflow)

In the documentation I see `cancel-in-progress` is always set to `true`, however I'd like to use an expression but can't confirm if that is supported.

So given this (abbreviated) workflow:

```yaml
on:
   pull_request:
   push:
      branches:
        - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
```

GitHub accepts the workflow (no invalid workflow errors) but it keeps cancelling the workflows on `main` when a new commit is pushed.

Are expression supported for `cancel-in-progress`?

**Comment by sandermvanvliet-stack** [comment]
[This StackOverflow answer](https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha) seems to suggest that an expression in `cancel-in-progress` doesn't seem to work and has an alternative approach.

**Comment by BenedekFarkas** [comment]
Expressions work, this is from the docs:

> A concurrency group can be any string or expression. The expression can only use [github](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), [inputs](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context) and [vars](https://docs.github.com/en/actions/learn-github-actions/contexts#vars-context) contexts.

Note that a lot of parameters are not available at the time when the concurrency key is evaluated (`github.job` isn't available for example).

Input parameters are available (strategy matrix parameters too for jobs), this is what I'm using for example: `cancel-in-progress: ${{ inputs.cancel-in-progress-for-this-pr == 'true' }}`.

**Comment by xWuWux** [comment]
Yes, expressions are supported for the `cancel-in-progress` field in GitHub Actions workflows. This allows you to implement more dynamic and flexible cancellation behavior based on specific conditions or parameters. The `cancel-in-progress` field takes an expression as its value, and this expression can utilize various contexts to evaluate its logic.

The available contexts for cancel-in-progress expressions are:

github: This context provides access to various GitHub-specific variables, such as `github.event_name`, `github.ref`, and `github.workflow`.

inputs: This context allows you to access input parameters defined in the workflow. This is particularly useful for conditional cancellation based on user-specified settings.

vars: This context provides access to workflow-defined variables, which can be used to store intermediate values or constants.

When evaluating expressions for `cancel-in-progress`, certain parameters may not be available at the time of evaluation. For instance, the `github.job` context is not accessible, as it's specific to the running job and not the concurrency group.

Example of Using an Expression for `cancel-in-progress`

Consider a workflow that needs to cancel in-progress runs only for pull requests but allow them to complete on the main branch. Here's how you can achieve this using an expression:  
`on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}` 
  In this example, the `cancel-in-progress` expression evaluates to `true` for pull requests, triggering the cancellation of any in-progress runs. For main branch pushes, the `cancel-in-progress` expression evaluates to `false`, allowing the workflows to complete.

**Comment by rvesse** [comment]
Is there some actual official GitHub documentation on this topic.  I'm seeing the same behaviour that my workflow with the following:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}
```

Is still cancelling concurrent builds on `release/<foo>` branches which intuitively is not what I expect.  I'm using Maven release process so it does two pushes in quick succession, one with the release version, and one with the next SNAPSHOT version and I want both builds to run but the SNAPSHOT build is cancelling the release build.

Did I just make an error in my conditional here?  Or is there something else going on?

**Reply by rvesse** [reply]
Wondering if at least for me this somehow relates to the Maven release plugin and how it pushes commits.

The following test workflow does exhibit the expected behaviour:

```yml
name: Conditionals

# Run workflow for any push to a branch
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

# Only permit one build per branch/tag
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show Reference Name
        run: |
          echo ${{ github.ref_name }}

      - name: Is release branch?
        if: ${{ contains(github.ref_name, 'release/') }}
        run: |
          echo "RELEASE BRANCH"

      - name: Is dev branch?
        if: ${{ !contains(github.ref_name, 'release/') }}
        run: |
          echo "DEV BRANCH"

      # Intentional sleep step so we can push additional commits to see how conditionals evaluate in 
      # cancel-on-progress conditions
      - name: Sleep
        run: |
          sleep 180
```

Multiple commits on non-release branches cause existing actions runs to be cancelled, but on `release/<foo>` branches they queue up and all get executed.

**Reply by rvesse** [reply]
Ah, think I understand what is going on now.

My conditionals in `cancel-in-progress` are being correctly honoured, **however** GitHub only queues up the most recent pending build i.e. you can only have one running and one pending build in your concurrency group irregardless of your `cancel-in-progress` setting.

For example:

- Push something that starts a build with a concurrency group, call it build A
- Push something in the same concurrency group, this gets queued by GitHub as A is still running, build B is now pending
- Push another thing in the same concurrency group, this gets queued by GitHub as A is still running and B is cancelled because this new build, C, is now the pending queued build for the concurrency group

**Reply by BenedekFarkas** [reply]
That's right, [documentation](https://docs.github.com/en/actions/using-jobs/using-concurrency#using-concurrency-in-different-scenarios) says:

> When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled.

But it would be a bit more clear if it stated something like "the queue depth for each concurrency group is 1", even better would be if it was configurable.

**Reply by rvesse** [reply]
Indeed - https://github.com/github/docs/pull/30647

**Reply by erfan125** [reply]
> Wondering if at least for me this somehow relates to the Maven release plugin and how it pushes commits.
> 
> The following test workflow does exhibit the expected behaviour:
> 
> ```yml
> name: Conditionals
> 
> # Run workflow for any push to a branch
> on:
>   push:
>     branches:
>       - '**'
>   workflow_dispatch:
> 
> # Only permit one build per branch/tag
> concurrency:
>   group: ${{ github.workflow }}-${{ github.ref_name }}
>   cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}
> 
> jobs:
>   test:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Show Reference Name
>         run: |
>           echo ${{ github.ref_name }}
> 
>       - name: Is release branch?
>         if: ${{ contains(github.ref_name, 'release/') }}
>         run: |
>           echo "RELEASE BRANCH"
> 
>       - name: Is dev branch?
>         if: ${{ !contains(github.ref_name, 'release/') }}
>         run: |
>           echo "DEV BRANCH"
> 
>       # Intentional sleep step so we can push additional commits to see how conditionals evaluate in 
>       # cancel-on-progress conditions
>       - name: Sleep
>         run: |
>           sleep 180
> ```
> 
> Multiple commits on non-release branches cause existing actions runs to be cancelled, but on `release/<foo>` branches they queue up and all get executed.
>

**Comment by 7Hazard** [comment]
I want the previous workflows to cancel if they have not yet begun, and I had the idea of using the expression `github.job == null` to know whether a job is currently running in the workflow or not. But it appears `github.job` always is null, even if a job is actually running, causing the expression to always be true and always cancelling the workflow when a new run for the concurrency group is initiated.
I'm using environments with review approvals, and don't want the workflows to run concurrently, and cancel workflows that has yet to be approved when a new workflow run is initiated, but not workflows that are already running.
Have figured out a nice way of solving this yet.

**Reply by rvesse** [reply]
> I want the previous workflows to cancel if they have not yet begun

So this is already the GitHub behaviour AFAICT, you can have at most one in progress and one pending job in a concurrency group.  If further jobs are triggered while one is in progress then only the most recently triggered job within the concurrency group remains pending, any older pending jobs are cancelled

Not sure I followed the rest of your use case but given the behaviour I've described it might be a case of you needing to define your concurrency group better

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by melroy89** [comment]
Yes, I use this for pull requests:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
```
