### DISCUSSION TITLE
Secrets context not available in inputs of reusable workflow

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#69774] [Actions]
### Select Topic Area

Question

### Body

I have created a reusable workflow that is actually a wrapper around the official docker build-push [action][1] .

I want to pass build-time secrets as follows

```
jobs:
  test-secrets-passing:
    uses: MyOrg/MyRepo/.github/workflows/myworkflow.yaml@main
    with:
      image_name: some-name
      image_tag: some-tag
      build_args: |
        MY_VAR=${{ vars.MY_VAR }}
      build_secrets: |
        MY_SECRET=${{ secrets.MY_SECRET }}
```

This fails with:

```
The workflow is not valid. .github/workflows/myworkflow.yaml (Line: 19, Col: 22): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.MY_SECRET
```

Isn't the `secrets` context supported from within `with` context of reusable workflows?

  [1]: https://github.com/docker/build-push-action
