### DISCUSSION TITLE
Output Key as Dynamic

### DISCUSSION THREAD

**Discussion by ajay-varma-penumetcha-db** [community/community#69904] [Actions]
### Select Topic Area

Question

### Body

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        option1: ["value1", "value2"]   
    # Map a step output to a job output
    outputs:
      **output1**: ${{ steps.step1.outputs.test }}
      **output2**: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
        
        
        
       I need output1, output2 as dynamic, something like this
    outputs:
        ${{ steps.step2.outputs.test }}: ${{ steps.step1.outputs.test }}

**Comment by Mahitej28** [comment]
@ajay-varma-penumetcha-db In GitHub Actions, you can use dynamic outputs by defining an if condition for the output and referencing the steps you want to use in your matrix strategy. Here's how you can set up your workflow to achieve dynamic outputs:

```
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        option1: ["value1", "value2"]
    outputs:
      ${{ matrix.option1 }}-output: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
    
```

With this setup, the outputs section will create dynamic outputs based on the matrix.option1 values, and it will map them to the steps.step1.outputs.test output. This means you will have outputs like value1-output and value2-output in your job, each mapped to the result of step1.

And if you want to include step2 in your dynamic outputs, you should modify your workflow accordingly by adding a second step similar to step1. However, you'll need to ensure that these steps are conditionally executed based on your matrix strategy, so that each value of `matrix.option1` corresponds to a different step.
