### DISCUSSION TITLE
pre-commit action: Abort commit if pre-commit actions fails

### DISCUSSION THREAD

**Discussion by hollspat** [community/community#69913] [Actions]
### Select Topic Area

Question

### Body

I'm totally new at github, so you'll have to give me some slack. 
I've tried to create a pre-commit action that will abort the commit if any of the jobs in the pre-commit fails. 
But the commit is still done even if the pre-commit fails. 

Shouldn't it be possible to abort the commit when using a pre-commit action?

**Comment by Mahitej28** [comment]
@hollspat Sometimes pre-commit actions may not block a commit due to various reasons, like configuration issues or how the pre-commit script is set up. So just make sure your pre-commit script is correctly set up also, check your `.pre-commit-config.yaml` file or other relevant configuration files. I think this might solve your issue

**Comment by hollspat** [comment]
Hi, thanks for the quick response!

A couple of questions:
Is .pre-commit-config.yaml just another name for squid/.github/workflows/pre-commit.yml (my pre-commit action), or is this an additional file?

I have a pre-commit that will check the syntax of squid config. It looks like this:
---------------------------------------------------------------------------------------------------
```
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: ['squid.conf']
  pull_request:
    branches: [ "main" ]
    paths: ['squid.conf']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    container: hollspat/alpine_ansible:1.0.1

    steps:
      # Checkout repo
      - name: checkout repo
        uses: ***@***.***
      # Check syntax
      - name: Check syntax for squid config
        run: squid -k parse -f ./squid.conf
```
----------------------------------------------------------------------------------------------

Are there any obvious faults in this? If I edit squid.config and intentionally break the syntax and commit the changes, I'll get an error in the "Check syntax for squid config" step, the step is marked as failed (red) in the gui. But the commit is still done.

I would have thought that the default behavior would be to cancel the commit if the pre-commit fails.

Cheers
Patrik

**Comment by Mahitej28** [comment]
It seems there might be some confusion between the `.pre-commit-config.yaml` file, GitHub Actions, and pre-commit checks. Let me clarify:

1. `.pre-commit-config.yaml`: This file defines configurations for pre-commit hooks, which are local checks that run before you commit code. Pre-commit hooks are independent of GitHub Actions. The `.pre-commit-config.yaml` file is typically used in your local development environment to set up pre-commit hooks to check code quality, formatting, or other criteria before allowing a commit. It doesn't prevent a commit from being made but enforces checks locally.

2. GitHub Actions: GitHub Actions is a CI/CD (Continuous Integration/Continuous Deployment) service provided by GitHub. It allows you to automate workflows for building, testing, and deploying your code. GitHub Actions can run checks on your code pushed to a repository, and you can define workflows using YAML files in the `.github/workflows` directory.

In your provided YAML file, you have defined a GitHub Actions workflow that checks the syntax of your `squid.conf` file. It runs whenever code is pushed to the "main" branch or when a pull request is created, specifically for changes to the `squid.conf` file.

Regarding your question about the default behavior: GitHub Actions workflows don't inherently block commits from happening. They are separate from the local pre-commit checks. If you want to block a commit based on checks run in GitHub Actions, you would need to configure your workflow accordingly.

To block a commit in GitHub Actions, you can use the `if` conditional in your workflow. For example, you can conditionally cancel the workflow based on the outcome of the syntax check:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check syntax for squid config
        run: |
          if squid -k parse -f ./squid.conf; then
            echo "Syntax check passed"
          else
            echo "Syntax check failed, exiting..."
            exit 1
          fi
```

In this example, if the syntax check fails, the workflow will exit with an error code, which can prevent further steps in the workflow or block a commit, depending on your GitHub Actions configuration.

Remember that pre-commit checks are primarily for local development, while GitHub Actions workflows are for automating checks and tasks in your repository. You can customize your GitHub Actions workflows to suit your requirements, including blocking commits on certain conditions.
