### DISCUSSION TITLE
Containerized jobs use wrong docker image

### DISCUSSION THREAD

**Discussion by pettermk** [community/community#69911] [Actions]
### Select Topic Area

Bug

### Body

Hi,

I've ran into an issue with my containerized CI pipeline. Code looks like this

```yaml
jobs:
  build:
    name: Build
    runs-on: [linux, docker]
    if: ${{ ! contains( github.event.pull_request.labels.*.name, 'do not build' ) }}
    timeout-minutes: 360
    container:
      image: gcr.io/company/builder:v108
      credentials: <...>
 ```
 
When we recently bumped the docker image tag to v109, new pull requests that had not been rebased were launched on v109 even though the code said v108.

To me that sounds like it must be a bug - but I would appreciate a confirmation on that or an explanation why I should expect older pull requests to still run on the newest docker image tag.

I should add that this is on a self-hosted runner, if that can affect it somehow

Thanks :smile:
