### DISCUSSION TITLE
Is it possible to use GHA to automatically post a comment on any PR including changes to a certain filepath?

### DISCUSSION THREAD

**Discussion by nicholaspshaw** [community/community#69944] [Actions] [answered]
### Select Topic Area

Question

### Body

I've been searching to try and find an example relevant to my needs.

I've found lots of similar things but I'm not sure how I can limit the scope of an auto comment to a specific subset?  In my case, I'm looking to post a comment containing a PR checklist to any PR that hits our automated testing folder and any files under it.

I found hashFiles(path) which seems like it's for a similar purpose.

Also, as mentioned, I'm posting a checklist, I'm fairly worried the formatting will be completely ruined/be very difficult using GHA.  Is there any way to test such things since it's an auto comment post or do you just need to merge the change and tweak from there?

**Comment by santoshvandari** [comment]
You can use GitHub Actions to automatically post a comment on any pull request (PR) that includes changes to a specific file path or directory. To achieve this, you can use the GitHub API to create a comment on the PR. Here's a high-level approach to implementing this:

- ***Create a Workflow File:*** Create a GitHub Actions workflow file in your repository. This workflow will run when a pull request is opened or modified.

- ***Specify Trigger Events:*** Define the events that trigger the workflow. In your case, you want the workflow to trigger pull_request events.

Define Conditions: In the workflow file, define conditions that check if the PR includes changes to the specific file path or directory (e.g., the automated testing folder). You can use the GitHub.event.pull_request.changed_files context to access the list of changed files in the PR.

- ***Use GitHub API:*** If the conditions are met, use the GitHub API to create a comment on the PR. You can format the comment as needed, including adding a checklist.

Here's an example of a GitHub Actions workflow YAML file that posts a comment to a PR if changes are made to files in a specific directory:

```yaml
name: Auto Comment on PR

on:
  pull_request:
    paths:
      - 'path/to/automated_testing_folder/*'

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR Changes
      id: pr-changes
      run: echo "::set-output name=changes::${{ toJson(github.event.pull_request.changed_files) }}"

    - name: Create Comment
      if: steps.pr-changes.outputs.changes != '[]'
      run: |
        # Use GitHub API to create a comment on the PR
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMENT="Your checklist comment here"
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

        curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"
```
In this example, the workflow checks if any files in the `path/to/automated_testing_folder/` directory have changed in the PR. If changes are detected, it uses the GitHub API to post a comment on the PR with the specified checklist comment.

Ensure you replace `path/to/automated_testing_folder/*` and `Your checklist comment here` with your specific file path and comment content.

Remember that you can customize the comment's formatting and content within the workflow file as needed.

To test the formatting, you can push a PR with changes to the specified directory, and the workflow will automatically create the comment on the PR. You can then review the comment and make any necessary adjustments to the formatting as required.

**Reply by nicholaspshaw** [reply]
Thank you for the help @santoshvandari , this allowed me to get something created pretty rapidly.  Unfortunately, though it seems valid, it doesn't appear to be working.

The PR with the above changes appears to be valid given successful build etc.

However, when I create a PR with that PR as a base, I'm not seeing the action triggered or any comment on the PR.  The change to use get changed files is because it already exists in the codebase and is used by other workflows successfully, it outputs a single line of filenames.

Here's what I have:

```

name: QA Code Review Checklist PR Comment

on:
  pull_request:
    paths:
      - 'features/*'
    types:
      - opened

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        id: changed_files
        uses: ./.github/actions/get-changed-files
      - name: Create Comment
        if: ${{ steps.get-changed-files.outputs.files }}
        run: |
          # Using GitHub API to create a comment on the PR
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="checklist comment here"
          GITHUB_TOKEN=${{ secrets. GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"`


```

**Reply by nicholaspshaw** [reply]
As a follow-up, for my needs anyway, there's no need to check changed files, the Paths argument is enough

**Comment by xWuWux** [comment, marked as answer]
The answer to your question is yes. It is possible to use GitHub Actions to automatically post a comment on any PR including changes to a certain filepath.

To do this, you can use the following steps:

Create a new GitHub Actions workflow file in your repository. This workflow will run when a pull request is opened or modified.
In the workflow file, define the events that trigger the workflow. In your case, you want the workflow to trigger pull_request events.
Define conditions that check if the PR includes changes to the specific file path or directory. You can use the GitHub.event.pull_request.changed_files context to access the list of changed files in the PR.
Use the GitHub API to create a comment on the PR. You can format the comment as needed, including adding a checklist.
Here's an example of a GitHub Actions workflow YAML file that posts a comment to a PR if changes are made to files in a specific directory:

YAML
`name: Auto Comment on PR

on:
  pull_request:
    paths:
      - 'path/to/automated_testing_folder/*'

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR Changes
      id: pr-changes
      run: echo "::set-output name=changes::${{ toJson(github.event.pull_request.changed_files) }}"

    - name: Create Comment
      if: steps.pr-changes.outputs.changes != '[]'
      run: |
        # Use GitHub API to create a comment on the PR
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMENT="Your checklist comment here"
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

        curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"
`

In this example, the workflow checks if any files in the path/to/automated_testing_folder/ directory have changed in the PR. If changes are detected, it uses the GitHub API to post a comment on the PR with the specified checklist comment.

Ensure you replace path/to/automated_testing_folder/* and Your checklist comment here with your specific file path and comment content.

Remember that you can customize the comment's formatting and content within the workflow file as needed.

To test the formatting, you can push a PR with changes to the specified directory, and the workflow will automatically create the comment on the PR. You can then review the comment and make any necessary adjustments to the formatting as required.

In the case of the example you provided, it seems that the workflow is not triggering because the changed_files step is not returning any results. This could be because the features/* path is not being changed in the PR.

To troubleshoot this, you can try the following steps:

Add a debug step to the workflow file before the Create Comment step. This will print the contents of the changed_files output to the console.
Push a PR with changes to the features/* directory.
Check the console output for the workflow to see if the changed_files output contains the expected file paths.
Once you have confirmed that the changed_files output is returning the correct results, you can remove the debug step and the workflow should start working as expected.

**Reply by nicholaspshaw** [reply]
Thanks @xWuWux I think this would work or get pretty close, I'll share my solution in an answer too just in case anyone is trying to do similar

**Reply by bfelbo** [reply]
I’m indeed trying to do something similar. Did you end up using the solution above or can you share your solution?

**Reply by nicholaspshaw** [reply]
sorry @bfelbo cannot remember if I did post elsewhere but posted my solution here now -> https://github.com/orgs/community/discussions/69944#discussioncomment-10796276

**Comment by nicholaspshaw** [comment]
Here's the solution I went with, sorry cannot remember if I posted it elsewhere at the time

````
name: Review Checklist PR Comment

on:
  pull_request:
    types:
      - opened
    paths:
      - 'features/**'
      
jobs:
  auto-comment:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: PR Comment
        run:
          gh pr comment $PRNUM --body-file .github/workflows/review_checklist.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
````
