### DISCUSSION TITLE
How do I make a single action, with multiple triggers, create only a single check?

### DISCUSSION THREAD

**Discussion by GabeMillikan** [community/community#69992] [Actions] [answered]
### Select Topic Area

Question

### Body

I have created an action which processes a PR's labels and changed files to determine which and how many codeowner(s) need to review the PR. The details of how it works are not particularly important, but it needs to run on both `pull_request` and `pull_request_review` triggers since it depends on labels and reviews (respectively).

These triggers are currently causing two different checks to run, but I only need the latest check to pass. How can I combine both these checks into one, so that merging is allowed? (screenshot: first run fails, subsequent run succeeds under a different trigger)
![Action (pull_request) FAILED + Action (pull_request_review) SUCCEEDED = BLOCKING](https://github.com/community/community/assets/44247924/61140143-2e8a-4289-868f-48ecb0168672)

Here's my `.github/workflows/review-requirements.yml`
```yml
name: Reviews
on: 
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, edited, dismissed]


jobs:
  check_review_requirements:
    runs-on: ubuntu-latest
    name: Check Review Requirements
    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4
      - name: Check Review Requirements
        uses: ./.github/actions/label-based-review-requirements
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

and here's `.github/actions/label-based-review-requirements/action.yml`
```yml
name: 'Review Requirements'
description: 'Enforces review requirements based on the applied labels.'
inputs:
  token:
    description: GitHub Access Token. Will be used to fetch PR reviews.
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
```

`.github/actions/label-based-review-requirements/dist/index.js` looks something kind of like this (actual logic removed)
```js
if (!requiredReviewersApproved()) {
  core.setFailed("Need more appovals!");
}
```

[The documentation](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-multiple-events) doesn't say much about this.

**Comment by Hielamon** [comment]
I have the same confusion about this.

**Comment by Weinell** [comment]
What is the status on this? I face the same issue.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by mars** [comment]
I've tried using [`run-name`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name), but that results in only the **Actions** tab name changing, not the checks in the PR.

**Comment by mattalbr** [comment]
Still facing this issue!

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by VishalMandala** [comment]
--------------------------------------------------
Single Check with Multiple Triggers in GitHub Actions
--------------------------------------------------
Problem:
- If a workflow has multiple triggers (e.g., push + pull_request),
  GitHub can create multiple check runs for the same change.

Solutions:
1) Use conditional statements in jobs:
   - Add `if: github.event_name == 'push' || github.event_name == 'pull_request'`
     to ensure the job runs only once per logical event.

2) Use `workflow_run`:
   - Create a "master" workflow that runs the check.
   - Trigger it from multiple workflows to centralize the check.

3) Avoid overlapping triggers:
   - Don't trigger on push to branches that also trigger pull requests.
   - Use `paths` or `paths-ignore` to narrow triggers.

Summary:
- Multiple triggers can fire the workflow, but you can control
  job execution to ensure a single check.
- Use conditional logic or a master workflow for centralized checks.

**Reply by GabeMillikan** [reply]
This is obviously nonsense and AI generated.

**Comment by dpetzev** [comment]
It is actually mind-boggling how this is still an issue. Can't we have one event group like `pull_request_events` that includes both the `pull_request_review` and `pull_request` triggers

**Comment by anthony-hayes** [comment]
FYI I found a workaround for this: create a commit status from a workflow that runs on both pull_request_review and pull_request, and then do a status check in GitHub on the status name (the context value)
https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status

**Reply by mars** [reply]
> do a status check in GitHub on the status name (the context value)

How did you accomplish this? A sample might clarify how others might try this solution.

**Reply by anthony-hayes** [reply]
It's basically 

1. add a workflow that runs on both pull_request and pull_request_review
2. add the script from the link (try the CURL one) to that workflow: https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status
3. configure your required status checks to require a status check with the same name as the commit status, (the `context` value) as if it were a job: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging

**Reply by mattalbr** [reply, marked as answer]
Here's an example from our repo, thanks @anthony-hayes for the great workaround. I wanted to get it working before I posted, and then I totally forgot.

```
name: Sample Action
on:
  pull_request_review:
    types: [submitted]
    branches:
      - dev
  pull_request:
    types: [synchronize, reopened]
jobs:
  sample_action:
    name: Sample Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    steps:
      - name: Set commit status
        uses: myrotvorets/set-commit-status-action@master
        with:
          status: pending
          sha: ${{ github.event.pull_request.head.sha }}
          context: "sample_action"
          allowForks: true
          description: 'Status check pending'
      - name: Do the thing
        id: do_the_thing
        continue-on-error: true
        run: ./do_the_thing.sh
     - name: Set commit status
        if: always()
        uses: myrotvorets/set-commit-status-action@master
        with:
          status: ${{ steps.do_the_thing.outcome == 'success' && 'success' || 'failure' }}
          sha: ${{ github.event.pull_request.head.sha }}
          context: "check_owners"
          allowForks: true
          description: ${{ steps.do_the_thing.outcome == 'success' && 'Do The Thing passed' || 'Do The Thing failed' }}
```

We use this for a janky custom OWNERS check, for example, since github CODEOWNERS absolutely does not work for our use case, and we're a small team that doesn't need something huge built out.
