### DISCUSSION TITLE
Irrelevant jobs displayed under the Pull Request if the branch has multiple PRs open.

### DISCUSSION THREAD

**Discussion by bartoszsuchocki** [community/community#70005] [Actions]
### Select Topic Area

Bug

### Problem Description
I have a situation where I need to create two Pull Requests from the same branch that are directed to different targets.
Those two **different target branches have different jobs configured to run** on the pull_request event.
Unfortunately, **all the jobs are listed under both pull requests**.

### Example
Job 1 - Validate PR - Delta
```
name: Validate PR - Delta

on:
  pull_request:
    branches: 
      - bugfix/tooManyJobsFix
      - bugfix/tooManyJobsFixTarget2

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache SFDX
      run: echo "PR delta validated!"
 ```
 Job 2 - Validate PR - Full Validation:
 ```
 name: Validate PR - Full Validation

on:
  pull_request:
    branches: 
      - bugfix/tooManyJobsFixTarget2
        
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache SFDX
      run: echo "Full codebase validated!"
 ```
 
 As you can see, the `Validate PR - Delta` is configured to run for PRs target to both target branches (`bugfix/tooManyJobsFix`, `bugfix/tooManyJobsFixTarget2`) and `Validate PR - Full Validation` runs only for the `bugfix/tooManyJobsFixTarget2` target branch.
 
 I raised two PRs:
 1. testPRBranch -> bugfix/tooManyJobsFix
 2. testPRBranch -> bugfix/tooManyJobsFixTarget2
 
 And, here is what I see under the testPRBranch -> bugfix/tooManyJobsFix PR (remember that it runs only one job!):
 
![image](https://github.com/community/community/assets/37738969/221dfe51-05ef-475f-8b93-572f86e014c7)

### Conclusion
It seems like Github is displaying all the jobs related to source branch and does not make distinction based on the target branch.
Do you know how to resolve this issue?
