### DISCUSSION TITLE
Feature Request: Annotations

### DISCUSSION THREAD

**Discussion by eliezercazares** [community/community#70035] [Actions]
### Select Topic Area

Product Feedback

### Body

It would be nice to be able to add annotations on Workflow and/or Actions level.
So a large workflow calling other workflows can make use of those tags. 

I.e.

test-1.yaml, test-2.yaml.. test-5.yaml
````
name: My Regression Test (Reusable workflow)

on:
    schedule:
        cron:
..etc
````

orchestrator.yaml
````
name: Call many workflows

on:
     workflow_dispatch:
         tags/annotations: @Regression @BugFix

env:
    ENVIRONMENT_: dev

jobs:
@Integration @Feature5
    test1:
        uses: ./.github/workflows/test-1.yaml 
        secrets: inherit
        with:
             MYVAR_: myvalue

@Regression @Feature4
    test2:
        uses: ./.github/workflows/test-2.yaml 
        secrets: inherit
        with:
             MYVAR_: myvalue

@Regression @Feature3
    test2:
        uses: ./.github/workflows/test-2.yaml 
        secrets: inherit
        with:
             MYVAR_: myvalue

@Regression @BugFix
    test2:
        uses: ./.github/workflows/test-2.yaml 
        secrets: inherit
        with:
             MYVAR_: myvalue

@Regression @Feature1 @Feature9
    test2:
        uses: ./.github/workflows/test-2.yaml 
        secrets: inherit
        with:
             MYVAR_: myvalue
````

So only the actions/workflows tagged with a specified tag would be executed.

And because they could be set at a workflow level, even if the "orchestrating" workflow calls a reusable workflow that contains the tag @ignore at a workflow level, the reusable workflow should be ignored.
