### DISCUSSION TITLE
Unable to get a comment to post automatically on PRs that are created

### DISCUSSION THREAD

**Discussion by nicholaspshaw** [community/community#70087] [Actions] [answered]
### Select Topic Area

Question

### Body

Seeking a bit of help here as my multiple attempts seem to be failing.  My first try, I was able to see the check had run because it failed to compile (I tried to use paths: and paths-ignore:)

Great, that's an easy fix I thought.  However, after fixing this, I see no evidence of the action working/triggering at all.  

I also have no idea how to even get an idea of what is wrong through debugging.  I just have the PR for the branch I'm making the change, then another PR which has the other as a base and I'm thinking should show evidence the change is working/broken/exists outside my imagination

I realise push: is incorrect for what I'm trying to do, I just read some accounts of paths: not working on pull_request: so was trying something else.

Here's the simple code, can anyone tell me what's wrong or how I can better debug what's wrong?

```
name: Code Review Checklist

on:
  push:
    paths:
      - 'features/**'

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
      - name: PR Comment
        run: gh pr comment ${{ github.head_ref }} --body 'Code Review checklist'
```

**Comment by JairTorres1003** [comment, marked as answer]
The YAML code  is supposed to comment on pull requests when changes are pushed to specific paths. Here's a potential issue in your workflow:

You've defined the trigger as push, but you mentioned that you want to comment on pull requests. To achieve your goal, you should use the pull_request event instead of push. Here's the modified workflow:

```yml
name: Code Review Checklist

on:
  pull_request:
    paths:
      - 'features/**'

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
      - name: PR Comment
        run: gh pr comment ${{ github.head_ref }} --body 'Code Review checklist'
```

Additionally: You can add logging statements or debug printouts to your workflow to see if the workflow is running and where it might be failing. For example:

```yml
jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Workflow is running."
          gh --version
          echo "GitHub head ref: ${{ github.head_ref }}"
          echo "GitHub event name: ${{ github.event_name }}"
          echo "GitHub event path: ${{ github.event_path }}"
      - name: PR Comment
        run: gh pr comment ${{ github.head_ref }} --body 'Code Review checklist'
```

No estoy seguro de la implementacion correcta que planeas hacer, tambien podrias añadir un comentario a los pull de la siguiente manera: [Reference code](https://github.com/JairTorres1003/JT-Workflows/blob/main/workflows/file-checker.yml#L48-L66)

```yml
    - name: Add Comment Pull
      env:
        COMMENTS_RESULTS: ${{ steps.find-specific-word.outputs.RESULTS }}
        FOUND_CONSOLE: ${{ steps.find-specific-word.outputs.FOUND }}
      if: steps.find-specific-word.outputs.FOUND != ''
      run: |
        # Get the comment content
        comment=$(cat "$COMMENTS_RESULTS")
        echo "$comment"
        
        # Use jq to format the comment as JSON
        comment_json=$(jq -n --arg body "$comment" '{"body": $body'})
        
        # Add the comment to the pull request
        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d "$comment_json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"


        exit 1
```
