### DISCUSSION TITLE
delpoy source code to gh pages from a PR

### DISCUSSION THREAD

**Discussion by tar-aldev** [community/community#70173] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

Usecase:
1. I have a PR where I run e2e tests and get html report as an artifact
2. I then want to publish it to github pages and have a unique url per each PR report
Problem:
It doesn't seem to be possible (unless I am missing smth)
I am using the following jobs
```
publish-playwright-report:
    name: Publish playwright report
    env:
      # Unique URL path for each workflow run attempt
      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
    # using always() is not ideal here, because it would also run if the workflow was cancelled
    if: "success() || needs.test.result == 'failure'"
    needs: frontend-next-e2e-playwright
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Download playwright report artifacts
        id: download-playwright-report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
          path: ${{ env.HTML_REPORT_URL_PATH }}
      - name: 'Echo download path'
        run: echo ${{steps.download-playwright-report.outputs.download-path}}
      - name: Upload artifact for github pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ steps.download-playwright-report.outputs.download-path }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Output Report URL as Worfklow Annotation
        run: |
          FULL_HTML_REPORT_URL=https://**/**/$HTML_REPORT_URL_PATH
          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
```

Of course if I follow the url outputted in the last step, it gives 404 page not found.
if I go to root page I can see a report, but I really want to have a unique url per report. Otherwise if there are 2 PRs, the reports will overwrite each other.

Is it possible with gh actions?
