### DISCUSSION TITLE
Octorust optional query params incorrectly generated as required

### DISCUSSION THREAD

**Discussion by SebastianGoeb** [community/community#70248] [Apps, API and Webhooks]
### Select Topic Area

Bug

## Disclaimer

Hi guys, first off I'm not sure about the right place to put this, but [octorust](https://docs.rs/octorust/latest/octorust/) doesn't seem to have a public repository, and the only contact link points directly to GitHub (https://support.github.com/contact?tags=rest-api), so I'm guessing it's a first party GitHub product, and the community here might be able to help

## The Problem

I think many optional query params are being incorrectly generated as required in the Rust API client [octorust](https://docs.rs/octorust/latest/octorust/).

My concrete example is from trying to automate my own repo settings, where I am using the endpoint `/user/repos` ([docs](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-the-authenticated-user)) to fetch the names of all my repos, to subsequently fetch all their settings individually. In particular `/users/{owner}/repos` does not work, because it only lists public repos.

Now, `/user/repos` has a bunch of optional query params that I don't care about. In particular, I'm really not even **allowed** to set visibility + type, and I am actively running into that 422 error because in octorust these are **required** parameters and there is no way to not set them.
```yaml
# https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.2022-11-28.yaml
# Line 42033 - 42082, sorry GitHub doesn't want to display the massive yaml file
  "/user/repos":
    get:
      summary: List repositories for the authenticated user
      ...
      parameters:
      - name: visibility
        description: Limit results to repositories with the specified visibility.
        in: query
        required: false
        schema:
          type: string
          enum:
          - all
          - public
          - private
          default: all
      - name: type
        description: Limit results to repositories of the specified type. Will cause
          a `422` error if used in the same request as **visibility** or **affiliation**.
        in: query
        required: false
        schema:
          type: string
          enum:
          - all
          - owner
          - public
          - private
          - member
          default: all
```

Octorust generates the following. The dates are proper `Option<DateTime>` types, but `visibility`, `type`, etc. (which **are** optional in the spec) are non-`Option`, and `is_empty()` is used as a stand-in, **however** there IS NO WAY for me to make these parameters produce `""` because the enum has no `::Noop` (like some other ones do), and `::FallbackString` always renders to `"*"` in `Display` (which provides `to_string()`.

I am little confused, how a supposedly "fully generated" (see [docs](https://docs.rs/octorust/latest/octorust/#:~:text=A-,fully%20generated,-%2C%20opinionated%20API%20client)) client, would produce non-`Option` types, for types that are optional in the spec, thus preventing me from using some endpoints entirely.

PS. sorry for the 🧂 !
```rust
pub async fn list_all_for_authenticated_user(
        &self,
        visibility: crate::types::ReposListVisibility,
        affiliation: &str,
        type_: crate::types::ReposListType,
        sort: crate::types::ReposListOrgSort,
        direction: crate::types::Order,
        since: Option<chrono::DateTime<chrono::Utc>>,
        before: Option<chrono::DateTime<chrono::Utc>>,
    ) -> ClientResult<crate::Response<Vec<crate::types::Repository>>> {
        let mut query_args: Vec<(String, String)> = Default::default();
        if !affiliation.is_empty() {
            query_args.push(("affiliation".to_string(), affiliation.to_string()));
        }
        if let Some(date) = before {
            query_args.push(("before".to_string(), date.to_rfc3339()));
        }
        ...
        if !type_.to_string().is_empty() {
            query_args.push(("type".to_string(), type_.to_string()));
        }
        if !visibility.to_string().is_empty() {
            query_args.push(("visibility".to_string(), visibility.to_string()));
        }
    }

/**
 * Can be one of `all`, `public`, or `private`. Note: For GitHub AE, can be one of `all`, `internal`, or `private`.
 */
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone, JsonSchema, Default)]
pub enum ReposListVisibility {
    #[serde(rename = "all")]
    #[default]
    All,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "public")]
    Public,
    #[serde(other)]
    FallthroughString,
}

impl std::fmt::Display for ReposListVisibility {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ReposListVisibility::All => "all",
            ReposListVisibility::Private => "private",
            ReposListVisibility::Public => "public",
            ReposListVisibility::FallthroughString => "*",
        }
        .fmt(f)
    }
}

/**
 * Can be one of `all`, `owner`, `public`, `private`, `member`. Note: For GitHub AE, can be one of `all`, `owner`, `internal`, `private`, `member`. Default: `all`  
 *     
 *   Will cause a `422` error if used in the same request as **visibility** or **affiliation**. Will cause a `422` error if used in the same request as **visibility** or **affiliation**.
 */
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone, JsonSchema, Default)]
pub enum ReposListType {
    #[serde(rename = "all")]
    #[default]
    All,
    #[serde(rename = "member")]
    Member,
    #[serde(rename = "owner")]
    Owner,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "public")]
    Public,
    #[serde(other)]
    FallthroughString,
}

impl std::fmt::Display for ReposListType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ReposListType::All => "all",
            ReposListType::Member => "member",
            ReposListType::Owner => "owner",
            ReposListType::Private => "private",
            ReposListType::Public => "public",
            ReposListType::FallthroughString => "*",
        }
        .fmt(f)
    }
}
```
