### DISCUSSION TITLE
runs-on support conditional variable

### DISCUSSION THREAD

**Discussion by zxkane** [community/community#70323] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a project using self-hosted or an organization's large runners to accelerate the workflow running. But I want to keep the workflow running on the forked repo with the default standard runner.

The `runs-on` does not support conditional variables to archive this.

I found a workaround below to make the duplicated job with different `if` checking, which is not easy for maintaining the workflow.

```yaml
name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build-with-standard-runner:
    if: ${{ vars.LARGE_RUNNER == '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Test build
        run: |-
          npm run build
  build-with-large-runner:
    if: ${{ vars.LARGE_RUNNER != '' }}
    runs-on: ${{ vars.LARGE_RUNNER }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Test build
        run: |-
          npm run build
```

**Comment by ChristopherHX** [comment, marked as answer]
> The `runs-on` does not support conditional variables to archive this.

You want to try this ( the `||` works similary to javascript, if `vars.LARGE_RUNNER` is `''/null/0 ` it returns `ubuntu-latest`

```yaml
name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ${{ vars.LARGE_RUNNER || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Test build
        run: |-
          npm run build
```

You are correct GitHub Actions Expressions doesn't have the following operator `<cond> ? <on-true> : <on-false>`, but most of the time you can rewrite it to if `<on-true>` is truthy => `<cond> && <on-true> || <on-false>` else `<on-true>` is falsy `!(<cond>) && <on-false> || <on-true>`
