### DISCUSSION TITLE
How to access caller workflow variables in the called composite action without `env` and `with` syntax

### DISCUSSION THREAD

**Discussion by copdips** [community/community#70343] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello,

In a called composite action, is there anyway that I can access the caller workflow variables without sending explicitly the variables as action input ?

As for my test, below syntax  is OK in a reusable workflow but not allowed in a composite action:
`echo "vars: ${{ toJson(vars) }}"` with error:

> Unrecognized named-value: 'vars'. Located at position 8 within expression: toJson(vars)

**Comment by ChristopherHX** [comment]
You could merge your action input / env with all variables (the Actions service will send all vars to the runner if you do it, otherwise only explicitly used variables of a job are sent, somehow GitHub classify vars similar to secrets without masking).

```yaml
# access your vars like ${{ env.<varname> }} inside the action
- uses: <ref>
  env:
    MYENVV: gzdh
    ${{ insert }}: ${{ vars }}
- uses: <ref>
  env: ${{ vars }}
# access your vars like ${{ inputs.<varname> }} inside the action
# This will generate warning if your actions doesn't declare your vars as inputs
- uses: <ref>
  with:
    my-input: gzdh
    ${{ insert }}: ${{ vars }}
```

_This would work in GitHub Actions, but not in a tool called act_

You could also use `VARS: ${{ tojson(vars) }}` and do `${{ fromjson(inputs.VARS).<varname> }}`

**Reply by ChristopherHX** [reply]
`env: ${{ vars }}` can also be moved to top level of your workflow file, so all jobs and actions called in the file can access vars as env variables

**Comment by copdips** [comment]
@ChristopherHX 
Thanks for your prompt, in fact, I've known already how to send explicity caller workflow vars by `with` as action input or by `env` as action env.
My question is more or less how to not use `with` and `env`, and to access vars inside composite action directly.
Becasue my action needs to access all the vars, and my current solution is to ask users to send all the vars every time as you mentionned in your second example:

```yaml
# in caller workflow
- name: <name>
  uses: <my composite action ref>
  with:
    vars: ${{ toJson(vars) }}
```

But for me this is not very elegant as of user experience, users should always give `vars: ${{ toJson(vars) }}`, it's the same everytime.
I'm searching for a solution without `with` nor `env`

```yaml
- name: <name>
  uses: <my composite action ref>
```

**Reply by ChristopherHX** [reply, marked as answer]
Maybe rewrite your initial post to explicitly state this is a feature request, because my answer (as a random GitHub Free user) would be no you can't.

You currently do it per action, this makes it per workflow file for all jobs and all actions. By opting out of security, you don't like to have.
```yaml
on:
  push:
# This is the only line needed to access all `vars` by using `env` in all actions per workflow file,
# it disables hiding variables from actions and processes
# using env is the most elegant way, to disable hiding variables
# No need for fromjson
# No need to pass them directly to the action
env: ${{ vars }}
jobs:
  _:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ env.MY_VAR }} # works now in both job and composite action, just not using ${{ vars.MY_VAR }} directly
    - name: <name>
      uses: <my composite action ref> # Just do `env.` and not `vars.` 
    - name: <name>
      uses: <my composite action ref>
    - name: <name>
      uses: <my composite action ref>
    - name: <name>
      uses: <my composite action ref>
```

In an action.yml
```yaml
runs:
  using: composite
  steps:
  - run: echo ${{ env.MY_VAR }} # works now in both job and composite action, just not using ${{ vars.MY_VAR }} directly
```

> I'm searching for a solution without with nor env

I can't help you with that, have a nice day.
