### DISCUSSION TITLE
Matrix job failes are overriden by the passing ones

### DISCUSSION THREAD

**Discussion by grzebiel** [community/community#70437] [Actions]
### Select Topic Area

Question

### Body

Hi All!

I have two workflows for pull requests and for merge queue separately. To allow them to work as expected at the end of each workflow there is a single trivial job, that supposed to check if everything that is really required is passing.
According to [this discussion](https://github.com/orgs/community/discussions/26822#discussioncomment-3305794), I should be able to simply require the matrix job, and check its result. 

Unfortunately, clearly the failed result is overridden by the other job from the matrix, which passes after the fail. Is it expected behavior? Do I have to hack result reporting on my own?

Workflow fie:
```yml
name: "Master checks"

on:
  merge_group:

jobs:
  build-and-test:
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, RelWithDebInfo]
        sanitizers: [Sanitize, NoSanitize]
    with:
      arch: X64
      compiler: ${{ matrix.compiler }}
      build_type: ${{ matrix.build_type }}
      sanitizers: ${{ matrix.sanitizers == 'Sanitize' }}
      clang_tidy: ${{ matrix.compiler == 'clang' && matrix.sanitizers == 'NoSanitize' }}

  postgres:
    name: "Postgres tests"
    uses: ./.github/workflows/blackbox.yml
    secrets: inherit
    strategy:
      matrix:
        test_env: [pit, client_queries]
    with:
      arch: X64
      image: "noname"
      test_env: ${{ matrix.test_env }}
      configuration: "postgres.yml"

  passed:
    runs-on: [ self-hosted, X64 ]
    name: "passed"
    needs: [build-and-test, postgres]
    if: ${{ always() }}
    steps:
      - run: echo "${{ toJSON(needs) }}"
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'timed_out') }}
        run: exit 1
      - run: |
          echo YOUVE DONE IT, REJOICE
```

Problematic run example:
![image](https://github.com/community/community/assets/10223474/dc6706b2-24d3-411c-9c8c-1561fa8b4256)
