### DISCUSSION TITLE
Runner not passing input params correctly to container hook

### DISCUSSION THREAD

**Discussion by seschi98** [community/community#70488] [Actions] [answered]
### Select Topic Area

Bug

### Body

Hello, I am experiencing a weird situation when using the [runner-container-hooks](https://github.com/actions/runner-container-hooks) with a self hosted runner:

I installed the Github runner on a fresh Ubuntu 22.04 server with Docker and created a simple workflow:
```yaml
name: Hello Docker

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: [self-hosted]
    steps:
      - uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: 'Mona the Octocat'
```

As expected, the job displays the correct message:
![image](https://github.com/community/community/assets/8929221/a926526e-431e-4de3-b8b3-a71e191091a4)

Then I downloaded the latest release (0.4.0) of the docker runner-container-hook and put the path to the `index.js` file in my `.env` file. When running the same workflow (see above) with this modified setup, it does not print out the whole message:
![image](https://github.com/community/community/assets/8929221/f44e904b-36ba-4b2a-949f-e224ef4a69fe)

I then did a little bit of debugging, by adding a debug log to the [run function of the hook](https://github.com/actions/runner-container-hooks/blob/main/packages/docker/src/index.ts#L18) to output the input parameters:
```ts
async function run(): Promise<void> {
  try {
    checkEnvironment()
    const input = await getInputFromStdin()

    // added debug message
    core.debug(`Hook input: ${JSON.stringify(input, null, 4)}`)

    // ... rest of the file
```

The output is very interesting, instead of one element in the `entryPointArgs` there are multiple substrings of the input, with some weird escape characters:
<img width="1033" alt="image" src="https://github.com/community/community/assets/8929221/c9583c66-fab4-421b-9354-77f64fe43eb8">

I think the problem might be that the runner applications does not pass the input to the hook correctly.

I would be glad to receive some help on this topic because I have to customize the "docker run" command line statements and therefore use the hook. Thanks in advance! 🙏🏻
