### DISCUSSION TITLE
Cannot push changes to origin if it touches the workflow being run

### DISCUSSION THREAD

**Discussion by jbergstroem** [community/community#70491] [Actions]
### Select Topic Area

Bug

### Summary

When trying to push changes via git to the workflow file being used, it fails with an error whereas other changes getting pushed works just fine.

### Details

I have a job that updates a release branch based on certain criteria. It looks (almost, some company obfuscation) like this:

```yaml
name: Deploy
on:
  workflow_dispatch:
  schedule:
    # note: all times are in UTC - you cannot define a timezone in github actions at the moment
    # https://github.com/orgs/community/discussions/13454
    - cron: "0 12-23 * * 1-4"
    - cron: "0 12-18 * * 5"

concurrency:
  group: "release-production"
  cancel-in-progress: false

permissions:
  contents: write

env:
  TARGET_BRANCH: "release/production"
  DEFAULT_BRANCH: "${{ github.event.repository.default_branch }}"

jobs:
  branch-status:
    name: Branch status
    runs-on: ubuntu-22.04
    outputs:
      deploy: ${{ steps.branch_changes.outputs.deploy }}
      sha: ${{ steps.get_commit_to_merge.outputs.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.DEFAULT_BRANCH }}

      - name: Get commit to merge
        id: get_commit_to_merge
        run: |
          offset="--before='4 hours ago'"
          commit=$(eval git log -1 --format='%h' "${offset}" ${{ env.DEFAULT_BRANCH }})
          echo "::notice::Using ${commit} as merge point"
          echo "sha=${commit}" >> "$GITHUB_OUTPUT"

      - name: Check for differences
        id: branch_changes
        run: |
          uxtime_target_sha="$(git log -1 --format='%at' ${{ steps.get_commit_to_merge.outputs.sha }})"
          uxtime_target="$(git log -1 --format='%at' refs/remotes/origin/${{ env.TARGET_BRANCH }})"
          if [ "${uxtime_target_sha}" -gt "${uxtime_target}" ]; then
            target_ref="$(git log -1 --format='%h' refs/remotes/origin/${{ env.TARGET_BRANCH }})"
            echo "::notice::Scheduled commit (${{ steps.get_commit_to_merge.outputs.sha }}) is ahead of the target branch (${{ env.TARGET_BRANCH }}@${target_ref}). Lets keep going!"
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::Scheduled commit (${{ steps.get_commit_to_merge.outputs.sha }}) is in sync or newer than the target branch (${{ env.TARGET_BRANCH }}). Stopping."
            echo "deploy=false" >> "$GITHUB_OUTPUT"
          fi

  unit-test:
    name: Unit tests
    needs: branch-status
    if: needs.branch-status.outputs.deploy == 'true'
    uses: ./.github/workflows/test-unit.yml
    secrets: inherit
    with:
      ref: ${{ needs.branch-status.outputs.sha }}

  e2e-test:
    name: E2E Tests
    needs: branch-status
    if: needs.branch-status.outputs.deploy == 'true'
    uses: ./.github/workflows/test-e2e.yml
    secrets: inherit
    with:
      ref: ${{ needs.branch-status.outputs.sha }}

  merge:
    name: Merge into target branch
    runs-on: ubuntu-22.04
    if: needs.branch-status.outputs.deploy == 'true'
    environment:
      name: Production
      url: https://myurl.com
    needs: [branch-status, unit-test, e2e-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.TARGET_BRANCH }}

      - name: Merge into target branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git rebase refs/remotes/origin/${{ env.DEFAULT_BRANCH }} --onto "${{ needs.branch-status.outputs.sha }}"
          echo "::notice::Rebased ${{ env.TARGET_BRANCH }} onto ${{ needs.branch-status.outputs.sha }}"

      - name: Push changes to branch
        run: git push origin
```

..this recently started to fail for reasons I couldn't figure out. `git push` complains about workflow permission errors:
```bash
To https://github.com/org/repo
 ! [remote rejected]   release/production -> release/production (refusing to allow a GitHub App to create or update workflow `.github/workflows/deploy-to-production.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/org/repo'
Error: Process completed with exit code 1.
```

Here's a list of deployments that started working after I manually pushed commits that touched the workflow file to the branch (then breaking again sincet there were more changes to `deploy-to-production.yml`).

<img width="1025" alt="Screenshot 2023-10-18 at 6 39 36 PM" src="https://github.com/community/community/assets/176984/4f95d698-f5f3-4d5b-92a9-6b8187d2d74b">

So, the summary seems to be that when you're trying to push changes to the workflow file that is being run, the change is rejected. As I pushed manually to the branch the job runs fine. This seems like a bug to me, or perhaps a lack of exposed permission knobs I should be able to control?
