### DISCUSSION TITLE
workflow_dispatch: and run-name: ${{ github.event.head_commit.message }}

### DISCUSSION THREAD

**Discussion by urbaned121** [community/community#70621] [Actions]
### Select Topic Area

Question

### Body

Hello, 
I have a workflow where I must run it manually, what comes out when we change the trigger from on:push to on:workflow_dispatch, the commit message in WebUi is replaced by the workflow name or workflow file path if the name is empty, 
What we need is to keep workflow_dispatch and display the latest commit message on the action run. 

```
run-name: ${{ github.event.head_commit.message }} 
name: learn-github-actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check object
        run: |
          sleep 1
```

looks like github.event.head_commit.message does not exist with workflow_dispatch 👎🏼 
Thanks in advance!
