### DISCUSSION TITLE
Does dependabot work even when the Docker image of a Docker container action is updated?

### DISCUSSION THREAD

**Discussion by zacky1972** [community/community#70630] [Actions]
### Select Topic Area

Question

### Body

Hi,

If the following workflow is placed at `.github/workflows/`:

```yaml
name: Docker sample

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  sample:
    name: Docker sample
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker://hello-world:latest
```

And if the following dependabot is placed at `.github/`:

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule: 
      interval: "daily"
```

Then, will the dependabot  generate a bump pull request when the docker image of `hello-world:latest` is updated?
