### DISCUSSION TITLE
nslookup fail to find service

### DISCUSSION THREAD

**Discussion by taoberquer** [community/community#70643] [Actions]
### Select Topic Area

Bug

### Body

Hi, I'm trying to access a database from a container with nslookup and I'm getting an error. I've made an example of my github actions to reproduce the error. If I've forgotten anything, please let me know.

The error :
```
Run nslookup postgres
  
Server:		127.0.0.11
Address:	127.0.0.11:53

** server can't find postgres.psu1waqqpzqu3mj[4](https://github.com/sedeotech/inferni/actions/runs/6588514445/job/17900939871#step:3:4)5gsqnyggvb.xx.internal.cloudapp.net: NXDOMAIN

** server can't find postgres.psu1waqqpzqu3mj[4](https://github.com/sedeotech/inferni/actions/runs/6588514445/job/17900939871#step:3:5)[5](https://github.com/sedeotech/inferni/actions/runs/6588514445/job/17900939871#step:3:6)gsqnyggvb.xx.internal.cloudapp.net: NXDOMAIN
```

The example :
```
name: Test

on:
  push:
    branches: ["*"]


jobs:
  test:
    services:
      postgres:
        image: postgis/postgis:15-3.4-alpine
        env:
          POSTGRES_PASSWORD: changeme
          POSTGRES_DB: database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
        - run: nslookup postgres

```
