### DISCUSSION TITLE
variables

### DISCUSSION THREAD

**Discussion by rnadupal** [community/community#70665] [Actions] [answered]
### Select Topic Area

Question

### Body

Hi, 

How to use GH action variables as environment variables in the scripts, and as parameters in the build tasks?

**Comment by Xrenya** [comment, marked as answer]
![Screenshot (2)](https://github.com/community/community/assets/51479797/5604191a-a3b8-429e-89ff-3541d6cedcf9)
1. Add variable e.g.: `JOB_NAME: test`
2. Add variable into YAML config file:
```
jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
```

Here is another example with variable env: `$NAME, $BUILD, $JAVA_VERSION`
```
name: Java CI with Maven

env:
  NAME: 'Snyk Demo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
        JAVA_VERSION: '11'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{env.JAVA_VERSION}}
      uses: actions/setup-java@v3
      with:
        java-version: ${{env.JAVA_VERSION}}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Print name
      run: echo "Hello $NAME. $BUILD. Using Java Version $JAVA_VERSION"
      env:
        BUILD: 'We are currently running the Build job'
```
