### DISCUSSION TITLE
Error in passing multiline string to workflow_dispatch inputs

### DISCUSSION THREAD

**Discussion by Undertone0809** [community/community#70754] [Actions]
### Select Topic Area

Bug

### Body

So here is my yml

```YAML
name: Chat with finetune model

on:
  workflow_dispatch:
    inputs:
      raw_requirement:
        description: 'user raw requirement'
        type: string
        required: true
        default: "This is user raw requirement"

jobs:
  chat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Install poetry
      run: pip install poetry

    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Setup OpenAI key
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    - name: Run Python script
      run: |
        poetry run chat --raw_requirement ${{ github.event.inputs.raw_requirement }}
```

As you can see, my parameter "raw_requirement" is a string. An example like: I want to build a web app.

Expected command is `poetry run chat --raw_requirement "I want to build a web app"`.
Actual command is `poetry run chat --raw_requirement I want to build a web app`.

An error will occur if not "". Therefore, the output result in this case is as follows:

![image](https://github.com/community/community/assets/72488598/8c12165a-40b0-403d-8d71-7fd1d2c0a442)

**Q1: Why `raw_requirement` is not a string even if I set `type: string` ?**

I realize I can use `poetry run chat --raw_requirement "${{ github.event.inputs.raw_requirement }}"` to solve the problem. So another question is: It doesn't work if I have "" in my raw_requirement.

![image](https://github.com/community/community/assets/72488598/afcdf59d-43b3-4380-8a0e-4aecd4180fb3)

**Q2: Is there a solution in this case?**

I know to can use `\"` to replace it. But is there any better solution?

**Q3: What should I do if i want to pass a multiline string parameter in `inputs`?**

**Comment by initial-d** [comment]
A practical workaround is to avoid interpolating the multiline value directly into the shell script body. Put the dispatch input into an environment variable first, then read that environment variable from Python or write it to a file. That avoids most quoting/newline surprises.

```yaml
on:
  workflow_dispatch:
    inputs:
      raw_requirement:
        description: user raw requirement
        type: string
        required: true

jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Save dispatch input
        env:
          RAW_REQUIREMENT: ${{ inputs.raw_requirement }}
        run: |
          python - <<'PY'
          import os
          from pathlib import Path

          Path("raw_requirement.txt").write_text(os.environ["RAW_REQUIREMENT"])
          PY

      - name: Use input
        run: |
          poetry run python your_script.py --requirement-file raw_requirement.txt
```

If you need to pass a multiline value between steps, use the documented environment-file delimiter form for `GITHUB_ENV` / `GITHUB_OUTPUT`, for example:

```bash
{
  echo "RAW_REQUIREMENT<<EOF"
  cat raw_requirement.txt
  echo "EOF"
} >> "$GITHUB_ENV"
```

Two caveats:

1. Pick a delimiter that cannot appear in the value. For fully arbitrary user text, generate a random delimiter instead of hard-coding `EOF`.
2. The Actions web UI for `workflow_dispatch` string inputs is still not a great textarea-style editor for long text. For long prompts/specs, it is usually more reliable to pass a file, use `gh workflow run -f raw_requirement="$(cat file.txt)"`, or store the prompt in the repo and pass a filename/key as the dispatch input.

Relevant docs: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#multiline-strings
