### DISCUSSION TITLE
Allow status checks without having to disable direct push to main branch, and without the need for extra branches or merging at all

### DISCUSSION THREAD

**Discussion by Julynx** [community/community#70780] [Actions]
### Select Topic Area

Product Feedback

### Body

I really love the idea behind GitHub Actions and how you can use them to run custom checks to ensure everything is running fine before merging.

However, GitHub currently forces you to enable the option to require users to push to an alternate branch and then merge, in order to actually be able to enforce status checks for new code.

![Screenshot_2023-10-22-01-11-06-339_com brave browser_1](https://github.com/community/community/assets/64993676/7ddd6205-a2f1-4848-8225-4a9616c156cb)

This actually doesn't make much sense, as those are completely unrelated features. 

I should be able to use one without the other: I should be able to enforce status checks on commit, without having to disable direct commits to the main branch and force users to commit to an alternate branch, then merge.

At the end of the day, my status check is a pre-commit GitHub action. It runs before commits, it doesnt need extra branches, nor merges, so why do I have to enable those features to enforce it?

P.D.: With "enforcing status checks" I mean especifically, to put commits on hold until the action completes, and reject the push if the action fails. I want to be able to do this with direct pushes to the main branch, I have no need for merging or extra branches for this functionality.

**Comment by seyLu** [comment]
#### Hi @Julynx,

Imposing a lint/format status check when the code has already been pushed to `main` branch in GitHub doesn't really make any sense -- I mean, the code has already been pushed to what is usually considered the stable branch. ([refer to Github Flow for more context](https://docs.github.com/en/get-started/quickstart/github-flow))

There's a python package called [pre-commit](https://pre-commit.com/) that does what you want -- it rejects code to be committed if it doesn't pass the status checks of the pre-commit hooks you configured.

I noticed you code in Python. As a Python developer myself, I highly recommend [ruff](https://astral.sh/ruff) for linting, [black](https://black.readthedocs.io/en/stable/) for formatting, [mypy](https://mypy.readthedocs.io/en/stable/) for type checking, and [pytest](https://mypy.readthedocs.io/en/stable/) for testing.

I prefer putting type check, tests, security checks, compatibility checks, etc. on CI so my pre-commit configuration usually looks like this:

`pre-commit-config.yaml`
```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
```

And for tooling configuration:
`pyproject.toml`
```toml
[project]
name = <project_name>
version = "0.0.1"
requires-python = <python_version>
license = "MIT"
authors = [
    {name = <author_name>, email = <author_email>},
]


[tool.ruff]
select = [
    "E", # Pyflakes
    "F", # Pycodestyle
    "B", # flake8-bugbear
    "I001" # isort
]
ignore = ["E501"]
unfixable = ["B"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401"]


[tool.mypy]
strict = true
implicit_reexport = true
check_untyped_defs = true


# Exclude type checking on files/dirs
exclude = [
    # TOML basic string (double-quotes, backslash and other characters need escaping)
    # TOML literal string (single-quotes, no escaping necessary)
]
```
