### DISCUSSION TITLE
Github Dependabot yml file invalid credentials error

### DISCUSSION THREAD

**Discussion by Xmaxer** [community/community#70809] [Actions]
### Select Topic Area

Question

### Body

I have defined a dependabot.yml file that uses the secrets defined at an organisation level for a custom NPM registry, to avoid remembering/copy-pasting URLs all over.

It looks like this:

```yaml
registries:
  internal-nexus:
    type: npm-registry
    url: ${{ secrets.NEXUS_NPM_PRIVATE_URL }}
    username: ${{ secrets.NEXUS_NPM_PUBLISHER_USERNAME }}
    password: ${{ secrets.NEXUS_NPM_PUBLISHER_PASSWORD }}}
```

The problem is, pushing this triggers an error on Github:

![image](https://github.com/community/community/assets/7211424/86a67616-dad6-41d4-842a-05788248edac)

The thing is, I know the URL stored in there is 100% correct. It is in the format of:

`https://nexus.mydomain.com/repository/npm-private`

And if I use that by directly inserting it into the dependabot file, it doesn't complain. What's weirder is I noticed dependabot still triggers sometimes even after claiming there's an error.

I should also note the secrets are definitely correctly inserted in the organisation -> secrets -> dependabot section

![image](https://github.com/community/community/assets/7211424/b1f8ac77-a5d5-4ba2-9a8b-b01c9deccdf5)

Has anyone else had this issue?
