### DISCUSSION TITLE
Building on self-hosted runners only on private copy of repo

### DISCUSSION THREAD

**Discussion by jonaski** [community/community#70846] [Actions] [answered]
### Select Topic Area

Question

### Body

Because building on self-hosted runners is a security risk I've created a private copy of the repository, on the private repository I want to only build on the self-hosted runner, while on the public repository I only want to build on the public github runners.
Is there a good way to keep the two repository copies identical while doing this?

My GitHub Actions CI looks something like this:

```
    strategy:
      matrix:
       runner: [ macos-13, macos-arm64 ]
       buildtype: [ release, debug ]

    runs-on: ${{ matrix.runner }}

    steps:

```

**Comment by jonaski** [comment, marked as answer]
Something like this:

```
jobs:

  set-runner:
    name: Set runner
    runs-on: ubuntu-latest
    outputs:
      runner: ${{steps.set_runner.outputs.runner}}
    steps:
      - name: Set runner
        id: set_runner
        shell: bash
        run: echo "runner=$(test "${{github.repository}}" = "jonaski/private-repo" && echo "macos-arm64" || echo "macos-11")" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs:
      - set-runner
    strategy:
      matrix:
       buildtype: [ release, debug ]
    runs-on: ${{needs.set-runner.outputs.runner}}
    steps:
```
