### DISCUSSION TITLE
New design is poor UX for wide screen monitor users.

### DISCUSSION THREAD

**Discussion by Kivylius** [community/community#7096] [Other Feature Feedback, Questions, & Ideas]
See screenshot:

need a max-width or just go back to original view where its restricted just like header and content.

<img width="1923" alt="Screenshot 2021-11-01 at 11 12 30" src="https://user-images.githubusercontent.com/1041335/139663382-1cba68b7-5688-43b7-81e0-c2af1af53b3f.png">
w.

**Comment by gaknoll** [comment]
@Kivylius thanks for sharing this feedback! I'll share this with the team working on responsive layouts

**Comment by jglick** [comment]
I have been asking for the width restriction on GitHub pages to be removed for years. The GitHub web UI is barely usable by default on a 4k screen. Uses maybe ⅓ of my screen real estate. Deeply frustrating to, say, review a PR with long lines of text when you have to keep on moving a horizontal scrollbar inside a tiny newspaper-like column in the center of the screen. Maybe someone loves this choice but there should at least be an option in profile settings or something to utilize the available screen width.

My workaround is to use Stylus with https://uso.kkx.one/style/108591 (and https://uso.kkx.one/style/108592). Includes overrides like

```css
.container {
  width: 100% !important;
  padding-right: 30px !important;
  padding-left: 30px !important;
}
.repository-content {
  width: 100% !important;
}
```
