### DISCUSSION TITLE
Why new issues doesn't appear on Pull Request after SARIF upload

### DISCUSSION THREAD

**Discussion by anrouxel** [community/community#70996] [Code Security] [answered]
### Select Topic Area

Question

### Body

Hello,
I have created a new pull request where new security issues have been introduced, but Code scanning says that no new issues are found on this PR.
![image](https://github.com/community/community/assets/59473377/c4e1b1d5-170b-437c-a6d5-28a985c94a42)

However, if we navigate to the Security tab and filter by per we can see the issue has been introduced in the current PR.
![image](https://github.com/community/community/assets/59473377/fc7ded73-a6e4-48b5-bba8-0ba41c596c8c)

Repository : [https://github.com/anrouxel/test.git](https://github.com/anrouxel/test.git)

Github Action :
```
name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: gradle/wrapper-validation-action@v1
      - name: Quality - Detekt
        run: ./gradlew detekt
      - uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
          category: detekt
      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: '**/build/reports'
```

Best Regards
