### DISCUSSION TITLE
Github action ran twice but check only displayed once

### DISCUSSION THREAD

**Discussion by lsarni** [community/community#70990] [Actions]
### Select Topic Area

Question

### Body

We have a workflow triggered by `deployment_status`. This will happen twice per PR change, which is expected given our setup. The job has a check meaning that it will only execute one of those times.
```
name: Deploy App
on:
  deployment_status:
jobs:
  app-preview:
    if: github.event.deployment_status.environment == 'Preview'
```
But the overview of the checks executed on the PR only displays the skipped execution, which can be confusing:
![image](https://github.com/community/community/assets/15196342/787aacf3-3207-446f-800b-3eccd96cd9dc)

The checks tab on the PR does display both:
![image](https://github.com/community/community/assets/15196342/c763a51a-169b-43fb-acc5-ce681f628d82)

Is there anything we can do to either display both on the overview or only the successful one? The skipped on will always end first, which is why it makes it to the overview, but that is to be expected.
