### DISCUSSION TITLE
Feature request: fromJson, matrix, plain-text values should not be compared to values, added as secrets in GitHub actions

### DISCUSSION THREAD

**Discussion by Mykp3** [community/community#71024] [Actions]
### Select Topic Area

Bug

### Describe the bug

Today, Mon 23 Oct noticed that Actions unable to initialise because of "values", that are coming into strategy. Last successful initialisation and last run was 2 weeks ago so I don't know exact date when it went wrong.

So any values that are coming in a form of inputs (that are in json) are failing to be "consumed", not even "if" is able to perform right when evaluating whether that or other value are exist/empty.

**Error message description: 2 errors:**
`Error when evaluating 'strategy' for job 'plan'. operations-tpl.yml@(Line: 210, Col: 18): Error parsing fromJson,.github/workflows/operations-tpl.yml@(Line: 210, Col: 18): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/cluster-operations-tpl.yml@(Line: 210, Col: 18): Unexpected value ''`

```
[cluster_operations / Prepare Variables for templated job](https://github.com/actions/runs/6890248763/job/18742895132#step:27:2)
**Skip output 'matrix' since it may contain secret.**

```

Clear indication GitHub sniffs values, even if those values are not accessed by using "${{secrets.some_secret}}". Github started to compare plain-text JSON values with secrets, I don't believe this must be absolutely default behaviour, we shall have control on it.
  
Build agent

#6 [ 1/14] FROM docker.io/library/`ubuntu:20.04`
`runner version: '2.310.2',` Pods are 32 days old so the same agents that were running it with success ~two weeks ago
### Reproduce

I already excluded couple possible reasons for this issue, 
- verified proper inputs coming from workflow, that is passing json values to reuse main workflow with.
- verified  `printf "matrix=%s" "$matrix" >> $GITHUB_OUTPUT` would populate matrix with correct json array 

I see this is very similar [issue from the early year ](https://github.com/actions/runner/issues/2424)(could be reproduced easier?)

assuming we will get matrix.json file from calling workflow 
(Bare in mind I did not tested following code but 90% of moving parts are there, I removed a lot of sensitive information and information indicating customer so it could cause some minor error.
I have High hopes developers of this product will figure it out based on previous linked issue) 

```
name: foo
on:
  push:
    branches:
      - bug/foo
  workflow_dispatch:

jobs:

  generate-matrix:
    runs-on: self-hosted
      - name: Generate Matrix
        id: generate-matrix
        run: |
          printf '%s' "$matrix" > "base/${{ github.run_id }}/${{ github.run_id }}_matrix.json"

      - name: terraform plan upload
        uses: actions/upload-artifact@v3
        with:
         name: "${{ github.run_id }}_matrix.json"
         path: "base_infra/${{ github.run_id }}/*.json"
         retention-days: 30


  operations:
    needs: [generate-matrix]
    uses: ./.github/workflows/operations-tpl.yml
```

operations-tpl.yml file:

```
name: cluster-operations
on:
  workflow_call:

jobs:
#=== Generate Matrices for applies ===#
  EnvSetup:
    name: Prepare Variables for templated job
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.load-matrix.outputs.matrix }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        id: GetMatrix
        with:
          name: "${{ github.run_id }}_matrix.json"
          path: "base_infra/${{ github.run_id }}"

      - name: Load Matrix
        id: load-matrix
        run: |
          matrix=$(jq -c 'map(select(.AU_NAME != ""))' "base_infra/${{ github.run_id }}/${{ github.run_id }}_matrix.json")
          printf "matrix=%s" "$matrix" >> $GITHUB_OUTPUT
          echo $matrix



  plan:
    if: ${{ (needs.EnvSetup.outputs.matrix_create == '[ ]' || needs.EnvSetup.outputs.matrix_create == ' ' || needs.EnvSetup.outputs.matrix_create == '') && (needs.EnvSetup.outputs.matrix_destroy == ' ' || needs.EnvSetup.outputs.matrix_destroy == '[ ]') }}
    name: Plan ${{matrix.AU_NAME}} ${{matrix.plan_for}}
    needs: EnvSetup
    runs-on: self-hosted
    timeout-minutes: 30
    env:
      AR15:                              ${{ matrix.AR15}}
    defaults:
      run:
        shell: bash
        working-directory: base/ad
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.EnvSetup.outputs.matrix) }}
```

**FEATURE REQUEST:**

Allow GitHub Action users to decide, whether they want GitHub to compare (sniff) all plain-text values and compare those values to the values, that are added as part of GitHub secrets.
