### DISCUSSION TITLE
[Feature Idea]: Automatically retry Failed Jobs or Steps

### DISCUSSION THREAD

**Discussion by ghost** [community/community#72195] [Actions]
### Select Topic Area

Product Feedback

### Body

Hey Community,

Sometimes, in GH Actions, Workflow Jobs / Steps fail due to numerous reasons.
I've been wondering why GH does not implement Automatic Retry for Jobs and Steps?

Something like: 

```` yml
...
jobs:
  job_1:
    runs-on: ubuntu-latest
    retry: 4 # Numeric value
````

There are none-native ways to do this (e.g. with some third-party actions).
Looking forward to discussing this.
