### DISCUSSION TITLE
Reusable workflows not triggering workflow_run

### DISCUSSION THREAD

**Discussion by jdebbink** [community/community#72631] [Actions]
### Select Topic Area

Bug

### Body

I have a workflow that is run once a release is created:
```
name: Deploy on Release

on:
  release:
    types: [published]
jobs:
  deploy:
    uses: "./.github/workflows/deploy.yml"
```

```
name: Deploy
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying"
```

I want to trigger a workflow when the `Deploy` workflow completes:
```
name: Deploy Status
on:
  workflow_run:
    workflows: [Deploy]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy ${{ github.event.workflow_run.conclusion }}"
```

The `Deploy Status` job never runs. If I add a `workflow_dispatch` to `Deploy` and manually run it then I get the job to trigger but that isn't what I want. Is this something that should work? All files are on the default branch. 

This demonstrates the issue: https://github.com/jdebbink/actions-test-issue
