### DISCUSSION TITLE
Rustdocs from GH Actions

### DISCUSSION THREAD

**Discussion by KGrewal1** [community/community#72823] [Actions] [answered]
### Select Topic Area

Question

### Body

Is it possible to deploy rustdocs directly from gh actions.
Current attempt is 

```
name: DeployAndBuild

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false


jobs:
  docs:
    name:  BuildDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build documentation
        uses: dtolnay/rust-toolchain@stable
      - run:  cargo doc --no-deps
        # with:
        #   command: doc
        #   args: --verbose --no-deps --all-features

      - name: Finalize documentation
        run: |
          CRATE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]' | cut -f2 -d"/")
          echo "<meta http-equiv=\"refresh\" content=\"0; url=${CRATE_NAME/-/_}\">" > target/doc/index.html
          touch target/doc/.nojekyll

      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: target/doc

  deploy:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
but fails with

```Artifact could not be deployed. Please ensure the content does not contain any hard links, symlinks and total size is less than 10GB.```
