### DISCUSSION TITLE
Running a reusable workflow with a dynamic ref

### DISCUSSION THREAD

**Discussion by fiddlermikey** [community/community#72839] [Actions]
I have not found a way to do this, and cannot find any documentation or examples that say this is possible. 
```
name: My Bootstrap Workflow

env:
  TOOLS_BRANCH: release-2.0

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize]
  push:

jobs:
  call-starter-workflow:
    uses: myorg/actions/.github/workflows/starter.yml@${{env.TOOLS_BRANCH}}
    secrets:
      token: ${{ secrets.2BUILDTOKEN}}
      
```
The closest I have found is [this action from jsnseng](https://github.com/jenseng/dynamic-uses)

I suppose I could use checkout of a branch and run it locally? Am I missing something? I'll bet it's obvious, right? Yeah, pretty sure...

**Comment by Mr-Gleidson** [comment]
It appears that you're trying to reference a GitHub Actions workflow file located in a specific branch of a repository. The code you provided is mostly correct, but there are a couple of things that need to be adjusted for this to work as intended.

The code you've provided references an external workflow file from a specific branch, and you want to use this workflow in your own GitHub Actions workflow. Here's a revised version of your workflow:

```yaml
name: My Bootstrap Workflow

env:
  TOOLS_BRANCH: release-2.0

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize]
  push:

jobs:
  call-starter-workflow:
    runs-on: ubuntu-latest  # Or choose an appropriate runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This step checks out your repository.
      with:
        ref: ${{ env.TOOLS_BRANCH }}  # Specify the branch to check out.

    - name: Run Starter Workflow
      run: |
        cd .github/workflows  # This is the directory containing your workflow file
        mv starter.yml main.yml  # Rename the workflow file to main.yml
      working-directory: ${{ github.workspace }}
    
    - name: Execute Starter Workflow
      uses: ./.github/workflows  # Use the local directory where the workflow is placed
      with:
        token: ${{ secrets.BUILDTOKEN }}

```

Here's what this workflow does:

It starts with the usual workflow setup.

In the call-starter-workflow job:

It checks out the repository using the actions/checkout action, which is the repository where the workflow file you want to use is located.
It renames the external workflow file starter.yml to main.yml. The local workflow files are typically expected to be named main.yml.
Finally, it uses the local workflow ./.github/workflows directory and runs the workflow. Make sure to replace the token value with the correct secret name from your repository.

This setup should allow you to execute the external workflow in your own GitHub Actions workflow.
