### DISCUSSION TITLE
an issue: An action in the root repo folder is running ok, while the one in frontend folder is not

### DISCUSSION THREAD

**Discussion by sinisarudan** [community/community#72893] [Actions]
### Select Topic Area

Question

### Body

I have an action
REPO-FOLDER/.github/workflows/main-demo.yml

```yml
name: Main Demo Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
    - name: Print a message
      run: echo "This is a Main Demo workflow."
```
that is run correctly.

I've made the one
REPO-FOLDER/frontend/.github/workflows/frontend.yml
with the same content, but it is not run at all.
When I check
https://github.com/MY-REPO/actions tab, I see the main one is executed with success, while the frontend.yml does not run at all.

I've tried to limit the frontennd.yml execution so that two workflows don't interfere, but it still doesn't work:

```yml
name: main-frontend-demo
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'frontend/**'

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
    - name: Print a message
      run: echo "This is a 'main-frontend-demo' workflow."
```

I've made several changes after actions creation and pushed them, but still no difference
