### DISCUSSION TITLE
docker/login-action is OK, but I can't use my registry during docker/build-push-action.

### DISCUSSION THREAD

**Discussion by Reivax47** [community/community#72955] [Actions]
### Select Topic Area

Question

### Body

Hello,

When the action is running, everything is fine until build-push. 
I can managed to log in my private registry. I can also execute 'docker login -u user -p password myregistry.com' but during docker/build push, I can't use 
'FROM myregistry.com/myimage' and I can't push also.
The error I get is : 
`tls: failed to verify certificate: x509: certificate signed by unknown authority`

Is my jobs description : 
```
`name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Construction du container
        uses: docker/setup-buildx-action@v3
      - name: Login to myRegistry
        uses: docker/login-action@v3
        with:
          registry: registry.athome.fr
          username: ${{ secrets.REGISTRYNAME }}
          password: ${{ secrets.REGISTRYPASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.athome.fr/monrepo:v1`
          
```
  The (very light ) Dockerfile :
  `FROM registry.athome.fr/mcusyspreweb:latest
LABEL authors="xavier"
CMD touch /coucou.txt`

At this point, it's failed. I can't get my image and build.
Any ideas ? 
Thanks a lot.
