### DISCUSSION TITLE
Checking out a repo does not require job permissions

### DISCUSSION THREAD

**Discussion by stackptr** [community/community#72975] [Actions]
### Select Topic Area

Bug

### Body

The `actions/checkout` action succeeds when disabling permissions for a job by setting `permissions: {}`[^1]. At the very least, this contradicts [existing documentation for OIDC][2] that shows the following configuration snippet:

```yaml
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
```

This is observed in an [draft PR][3] (public repo) which shows that the job is setup with the expected `GITHUB_TOKEN` permissions:

![image](https://github.com/community/community/assets/4542907/fa306887-feb9-4049-99dc-5328db109329)

[^1]: [Workflow syntax for GitHub Actions][1]

[1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defining-access-for-the-github_token-scopes
[2]: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#updating-your-actions-for-oidc
[3]: https://github.com/freckle/typescript-action-template/pull/110
