### DISCUSSION TITLE
Reusable workflow

### DISCUSSION THREAD

**Discussion by raghusrinim** [community/community#72980] [Actions]
### Select Topic Area

Question

### Body

I am trying to invoke a reusable workflow from another job. The resuable workflow is invoked. In the workflow, I get an error: 

Unrecognized named-value: 'steps'. Located at position 1 within expression: steps.auth.outputs.credentials_file_path

 --cred-file="${{ steps.auth.outputs.credentials_file_path }}".

Any leads please?

**Comment by b8zeek** [comment]
The error message suggests that the workflow doesn't recognize `steps.auth.outputs.credentials_file_path`.

Maybe, te step with id `auth` is not correctly defined or doesn't exist in the same job where you're trying to use the output. Or, that same step does not correctly set credentials_file_path as an output.
Here's an example of how you can set an output in a step:

```
steps:
  - id: auth
    run: |
      # Your commands here
      echo "::set-output name=credentials_file_path::/path/to/credentials"
```

If you're trying to use the output in a different job or a different workflow, you'll need to use environment variables.

🍀
