### DISCUSSION TITLE
Status check in branch protection rules runs in all open and close PR

### DISCUSSION THREAD

**Discussion by Ting-Ching-Chou** [community/community#73015] [Actions]
### Select Topic Area

Question

### Body

Recently, I created a workflow that would be triggered when the PR was opened / labeled / unlabeled. The workflow contained a job, which I wanted to be added in required status check in protection rules.

Workflow
```
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-for-block:
    name: Block merge if labels contain 'BLOCKED'
    if: |
      contains(github.event.pull_request.labels.*.name, 'BLOCKED')
    runs-on: ubuntu-latest
    steps: ...
```

Branch protection rule
```
[x] Require status checks to pass before merging

    |     Status checks that are required.     |
    |  --------------------------------------  |
    | Block merge if labels contain 'BLOCKED'  |

```

However, this rule will block all open PRs and generate tons of pending checks in close PRs.

Block open PRs

![image](https://github.com/community/community/assets/91191381/08146951-680e-4943-8aa0-68c0275322ff)

Generate pending checks in close PRs

![image](https://github.com/community/community/assets/91191381/47a94fd6-e6cc-4372-9d1c-ebfe5ba96b7e)

How to fix this issue, so that it will only run in open PRs, and will not block previous open PRs without 'BLOCKED' label?
