### DISCUSSION TITLE
Re-try Docker Login/Pull Mechanism for jobs ran in containers

### DISCUSSION THREAD

**Discussion by mikebowyer** [community/community#73069] [Actions] [answered]
### Select Topic Area

Product Feedback

## Problem Statement

The current implementation of [running jobs in containers](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container) lacks a re-try feature. This is problematic if a container registry comes under load and is not perfectly available, causing workflows to fail sporadically, and there is no mechanism to increase robustness of jobs/workflows within GitHub Actions. 

# Solution Proposal
A common approach to this issue is a a feature known as "re-try", or the more advanced on "re-try after". The tool `curl` is a great example of how this feature can be implemented, as discussed [here](https://everything.curl.dev/usingcurl/downloads/retry).

## Solution Proposal Details
From a user perspective it would be ideal to extend the existing list of container run options, as described [here](url) as such:

```
name: CI

on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    retry-attempts: 5 # Indicates that docker login and docker pull will be attempted a maximum of 5 times before failing.
    retry-after: 10 # Indicates how long before a re-try attempt will be made after a failure. 
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
```
