### DISCUSSION TITLE
Error when evaluating 'strategy' for job - Unexpected type of value '', expected type: Sequence.

### DISCUSSION THREAD

**Discussion by tonysathre** [community/community#73178] [Actions]
I'm trying to convert this workflow to use the new output syntax, but am getting this error. My workflow looks like this:

Here's the full error:

```
Error when evaluating 'strategy' for job 'decom'. .github/workflows/test_decom.yml (Line: 37, Col: 18): Error parsing fromJson,.github/workflows/test_decom.yml (Line: 37, Col: 18): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/test_decom.yml (Line: 37, Col: 18): Unexpected type of value '', expected type: Sequence.
```

```
name: Decommission VDI

on:
  workflow_dispatch:

env:
  delivery-controller: server.example.com
  citrix-tag: decom

jobs:
  setup:
    runs-on: citrix
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: set-matrix
        id: set-matrix
        run: |
          $machines = (Get-BrokerMachine -AdminAddress ${{ env.delivery-controller }} -Tag ${{ env.citrix-tag }})
          echo "matrix=$(ConvertTo-Json @($machines.HostedMachineName) -Compress)" >> $env:GITHUB_OUTPUT
        shell: powershell

  decom:
    needs: setup
    runs-on: citrix
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        machine: ${{ fromJson(needs.setup.outputs.matrix) }}
        
    steps:
          - name: Output Matrix
            if: always()
            run: echo ${{ matrix.machine }}
            shell: pwsh
```

This is how it was originally before migrating it to the new output syntax which was working:

```
jobs:
  setup:
    runs-on: citrix
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: set-matrix
        id: set-matrix
        run: |
          $machines = (Get-BrokerMachine -AdminAddress ${{ env.delivery-controller }} -Tag ${{ env.citrix-tag }})
          Write-Output "::set-output name=matrix::$(ConvertTo-Json @($machines.HostedMachineName) -Compress)" # cast to array. See https://stackoverflow.com/a/58617520
        shell: powershell
```

Am I missing something?

Thanks
