### DISCUSSION TITLE
Trigger Github actions pull request on feature branch

### DISCUSSION THREAD

**Discussion by ducminhleeh** [community/community#73225] [Pull Requests] [answered]
### Select Topic Area

Question

### Body

I'm setting up my Github actions workflow for Pull request, as I read document on [Github page](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), I think just need to `open`/ `push a new commit` to pull request, it will trigger the Github actions (not have any condition about the branch or based branch), but it doesn't.

When I added the workflow on based branch, it works on feature branch. This is my config on feature branch:
```yml
name: Test
on: 
  pull_request:
    branches-ignore:
      - 'master'
      - 'development'
      - 'staging'
    types: [edited, reopened, ready_for_review, synchronize, opened]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        run: ## run some command
```

**Comment by b8zeek** [comment, marked as answer]
Your current configuration is set to ignore pull requests that target the `master`, `development`, and `staging` branches. This means that the workflow will not run when a pull request is opened against these branches. I guess that's the issue here.

If you want the workflow to run on pull requests for any branch, you can simply remove the branches-ignore section, e.g:

```
name: Test
on: 
  pull_request:
    types: [edited, reopened, ready_for_review, synchronize, opened]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        run: ## run some command
```

This configuration will trigger the workflow whenever a pull request is opened, synchronized (i.e., updated with new commits), edited, marked as ready for review, or reopened, regardless of the target branch.

Hope this clarifies it for you. 😃 

🍀
