### DISCUSSION TITLE
Cron Job does not run at 00:35 AM

### DISCUSSION THREAD

**Discussion by woctezuma** [community/community#73251] [Actions] [answered]
### Select Topic Area

Product Feedback

### Body

Hello,

I have a job scheduled as follows:
```yml
on:
  workflow_dispatch:
  schedule:
    - cron: '35 18-23 * * 3'
    - cron: '35 0-12 * * 4'
```

I would expect the job to run:
- on Wednesdays at 18:35, 19:35, ..., 23:35, **and it does**,
- on Thursdays at 00:35, 01:35, ..., 12:35, **yet it skips 00:35 UCT** (so **01:35 GMT+1**).

![Picture](https://i.imgur.com/W4amzRM.png)

Similarly, the previous week, it skipped **00:35 UCT** (so **02:35 GMT+2** due to daylight saving time).

![Picture](https://i.imgur.com/rE5vlQB.png)

I wonder if this skip is linked to a high load at midnight mentioned [in this other discussion](https://github.com/orgs/community/discussions/52477), despite the delay of 35 minutes.
It is not a big deal, but I am confused as I see nothing wrong with the schedule.
