### DISCUSSION TITLE
How to fetch default argument of an action

### DISCUSSION THREAD

**Discussion by jay0129** [community/community#73282] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello,

Is there any way I can get default value of action argument?
So that I don't need to miss updates of default values but customize them at the same time.

For example of https://github.com/coderabbitai

```
    runs-on: self-hosted
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        with:
          system_message: ${{ arguments.system_message.default }} + " Translate in Korean"
```

**Comment by b8zeek** [comment, marked as answer]
There isn't a built-in way to access the default value of an action's argument...

But!

If I understood, you can manually update the input value in your workflow file whenever the action's default value changes. This requires you to keep track of updates to the action.

You can also use environment variables, you could set the default value as an environment variable in your workflow file, and then append your custom value to it. Not ideal solutions as it requires you to update the environment variable whenever the action's default value changes. E.g. below:

```
runs-on: self-hosted
env:
  DEFAULT_SYSTEM_MESSAGE: 'The default system message'
steps:
  - uses: coderabbitai/ai-pr-reviewer@latest
    with:
      system_message: ${{ env.DEFAULT_SYSTEM_MESSAGE }} + " Translate in Korean"
```

Hope this solves your issue! Take care. 🍺 

🍀
