### DISCUSSION TITLE
Github actions integration with firebase testlab

### DISCUSSION THREAD

**Discussion by suresh-durai** [community/community#73294] [Actions]
### Select Topic Area

Question

### Body

Hello everyone, I'm currently working on integrating firebase test lab with github actions in my project. I can successfully run my android tests and can view the results on the firebase console. Now, I'm looking to generate a similar report on GitHub Actions and eventually set up Slack notifications for these test results. I've been searching for documentation on this but haven't found any. Has anyone already tackled this or can provide any helpful references?

**Comment by b8zeek** [comment]
I think I can help with this... Fist, generate a report on GitHub Actions, I think that Firebase Test Lab provides a REST API that you can use to fetch test results. You can add a step in your GitHub Actions workflow to call this API and fetch the test results after the tests have run. You can then parse these results and generate a report in a format that you want.

To setup the notifications to Slack, you can use the `slackapi/slack-github-action` GitHub Action. You can add a step in your workflow that runs this action after the tests have run and the report has been generated. You just have to provide a Slack bot token and the ID of the channel where you want to send the notifications.

Your file might look something like this, you'll maybe have to tune it up a bit (definitely replace `your-channel-id` and `{your report}`):
```
name: Run tests and notify Slack
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        # Your command to run tests on Firebase Test Lab

    - name: Fetch test results
      run: |
        # Your command to call the Firebase Test Lab API and generate a report

    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.14.0
      with:
        channel-id: your-channel-id
        slack-message: 'Test results: ${your report}'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

Hope this solves the issue for you. Cheers! 🍺 

🍀
