### DISCUSSION TITLE
Syntax error in issue forms markdown help

### DISCUSSION THREAD

**Discussion by ferdnyc** [community/community#7335] [Projects and Issues]
The sidebar help (shown next to the web editor for issue forms) gives the following Example syntax for `- type: markdown` fields with headings:
```yml
body:
- type: markdown
  value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
```

Problem is, that's a syntax error. `value` can't be used at that level. It needs to be:
```yml
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
```
