### DISCUSSION TITLE
Calling Workflows per Pull Request on schedule

### DISCUSSION THREAD

**Discussion by bloudraak** [community/community#73402] [Actions]
### Select Topic Area

Question

### Body

Whenever a pull request is created, we create an ephemeral environment where changes can be tested. When the pull request is closed, the ephemeral environment is destroyed. However, to save costs, we want to destroy those ephemeral environments daily. They will be resurrected when there's a change to the pull request.

I started writing a TypeScript action, and I can get the list of pull requests and call a workflow. Could you tell me how I can ensure the workflow runs within the context of the pull request as if someone modified it? For example, we need to checkout the branch and run some commands to destroy it effectively.

**Comment by esurov** [comment]
To achieve the desired workflow where you want to automatically destroy ephemeral environments daily for pull requests and resurrect them when there's a change, you can create a GitHub Actions workflow that is triggered daily and performs the following steps within the context of the pull request:

1. Identify Pull Requests to Process:
   - Use the GitHub API or a GitHub Actions context to list the open pull requests in your repository.

2. Loop Through Pull Requests:
   - For each open pull request, proceed to the following steps.

3. Checkout the Branch:
   - Checkout the branch associated with the pull request. You can use `actions/checkout` to achieve this.

4. Run Cleanup Commands:
   - Run the necessary commands to destroy the ephemeral environment or perform any cleanup operations specific to your use case.

5. Commit and Push Changes:
   - If you made any changes in the branch (e.g., changes to configuration files), commit and push those changes back to the pull request branch. This step is crucial to trigger GitHub Actions for the pull request.

6. Create a Workflow Dispatch Event:
   - Use the GitHub API to trigger the workflow associated with the pull request. You can use the `repository_dispatch` event or a custom event to trigger the workflow. Pass any necessary information about the pull request in the event payload.

7. Workflow Execution:
   - Define a separate GitHub Actions workflow that is triggered by the workflow dispatch event. This workflow will run within the context of the pull request, just like someone modified it.

8. Resurrection of the Ephemeral Environment:
   - Within the triggered workflow, perform the necessary actions to resurrect the ephemeral environment based on the changes made to the pull request.

Here's an example of a GitHub Actions workflow YAML file for the daily cleanup and resurrection process:

```yaml
name: Daily Environment Cleanup

on:
  schedule:
    - cron: '0 0 * * *' # Trigger daily at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Cleanup Commands
        run: |
          # Add your cleanup commands here

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Cleanup changes"
          git push

      - name: Trigger Workflow Dispatch
        run: |
          # Use the GitHub API to trigger the workflow associated with the pull request
          # Include pull request details in the event payload

  resurrection:
    needs: cleanup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Resurrection Commands
        run: |
          # Add your commands to resurrect the ephemeral environment
```

In this example, the "Daily Environment Cleanup" workflow is triggered daily and, upon successful cleanup, triggers the "Resurrection" workflow associated with the pull request.

Please note that this is a high-level overview, and you will need to implement the specific API calls, event triggers, and commands based on your project's requirements. Additionally, ensure you have the necessary permissions and tokens to trigger workflows and make changes to the pull request branches.
