### DISCUSSION TITLE
Outputs not working

### DISCUSSION THREAD

**Discussion by shaimona** [community/community#73419] [Actions]
### Select Topic Area

Question

### Body

I'm trying to use output of a job to be used by another one. However the output is empty. Can you please tell me why the output of `build-container-image-production` is empty? Here is the gist of my pipeline. https://gist.github.com/shaimona/3a6f90b434b51ba7b5937452fee0ccaf

**Comment by b8zeek** [comment]
I just took a look at your GitHub Actions workflow, it seems like you're trying to pass the output of the `build-container-image-production` job to the `deploy-to-production` job and if I understood, you're seeing that the output is empty.

The issue might be due to the way you're setting the output in the `build-container-image-production` job. In your run command, you're echoing the output, but you're not actually setting it as an output of the job.

To do that, you can use the `::set-output name=<name>::<value>` command. Here's how you can modify your build-container-image-production job to set the image output:
```
build-container-image-production:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker images
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

    - name: Set output
      id: vars
      run: echo "::set-output name=image::${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}"
```

Then, in your `deploy-to-production` job, you can access this output using `needs.build-container-image-production.outputs.image`:
```
deploy-to-production:
  needs: [build-container-image-production]
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to Production
      run: echo "Image: ${{ needs.build-container-image-production.outputs.image }}"
```
This should correctly pass the image output from the `build-container-image-production` job to the `deploy-to-production` job.

Hope this helps buddy. Cheers! 🍺 

🍀

**Reply by airtower-luna** [reply]
`set-output` was [deprecated over a year ago](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) due to security issues. But you can't expect ChatGPT to "know" that.

**Comment by airtower-luna** [comment]
The use of outputs seems correct syntax-wise. Could you share a link to the actual log? :thinking:

**Reply by shaimona** [reply]
@airtower-luna Please see the log below. As you can see, IMAGE_ID is empty
2023-10-31T04:54:15.5988600Z ##[group]Run aws-actions/amazon-ecs-render-task-definition@v1
2023-10-31T04:54:15.5989420Z with:
2023-10-31T04:54:15.5989886Z   task-definition: ./aws/task_definition_prod_api.json
2023-10-31T04:54:15.5990560Z   container-name: <redacted>
2023-10-31T04:54:15.5991017Z env:
2023-10-31T04:54:15.5991377Z   AWS_REGION: us-east-1
2023-10-31T04:54:15.5991907Z   ECR_REPOSITORY_PREFIX: test
2023-10-31T04:54:15.5992406Z   ECS_SERVICE_PREFIX: test
2023-10-31T04:54:15.5992883Z   ECS_CLUSTER_PREFIX: test
2023-10-31T04:54:15.5993477Z   ECS_TASK_DEFINITION_PREFIX: ./aws/task_definition
2023-10-31T04:54:15.5994057Z   CONTAINER_NAME_PREFIX: test
2023-10-31T04:54:15.5995389Z   PIPELINE_EXECUTION_ROLE: arn:aws:iam::***:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-DJDH6D
2023-10-31T04:54:15.5996374Z   BRANCH_NAME: main
2023-10-31T04:54:15.5996801Z   ENVIRONMENT: prod
2023-10-31T04:54:15.5997331Z   APP_ROLE: api
2023-10-31T04:54:15.5997720Z   IMAGE_ID: 
2023-10-31T04:54:15.5998142Z   AWS_DEFAULT_REGION: us-east-1
2023-10-31T04:54:15.5998913Z   AWS_ACCESS_KEY_ID: ***
2023-10-31T04:54:15.5999515Z   AWS_SECRET_ACCESS_KEY: ***
2023-10-31T04:54:15.6008579Z   AWS_SESSION_TOKEN: ***
2023-10-31T04:54:15.6009073Z ##[endgroup]
2023-10-31T04:54:15.6661102Z ##[error]Input required and not supplied: image

**Reply by airtower-luna** [reply]
I didn't doubt the value really is empty, the question is *why*.

The first place I'd look is where the output is *created* (maybe something's going wrong there?), and the other thing is typos (couldn't tell those from an edited Gist). A third one: Are there any secrets used in constructing the output? I know GitHub is censoring those in outputs too, but not the exact conditions.

**Reply by shaimona** [reply]
Thank you for your willingness to help. I have been staring at this for few days and can’t figure out why it is not working. I even created a separate step for outputs. Still same issue. Not sure what to try next.

**Comment by ChristopherHX** [comment]
Your issue is probably related to these actions in the first job together with a small warning in the finish job section and not in the job log you have uploaded.

```yaml
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: samrolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
```

- By default they make use of `::add-mask::` for e.g. account id (Look ath their docs, they might have inputs to disable masking)
- actions/runner detect the image string partially as a masked secret
- actions/runner doesn't upload job outputs containing secrets (there are discussions about this topic, but GitHub didn't change that)
