### DISCUSSION TITLE
How to install Boost and use with pybind11

### DISCUSSION THREAD

**Discussion by marcmgame** [community/community#73433] [Actions]
### Select Topic Area

General

### Body

I am trying to use GitHub actions on a Python package with pybind11 that uses Boost. I can install Boost but CMake cannot find it when trying to compile the code.

Here is a link to a repo with a sample code

https://github.com/marcmgame/pybind11_boost_example

**Comment by esurov** [comment]
If you're using GitHub Actions to build a Python package with pybind11 and Boost, you'll need to ensure that Boost is properly installed and that CMake can find it during the build process. Here are the steps you can follow to troubleshoot and resolve this issue:

1. Install Boost on your GitHub Actions runner:

   You need to ensure that Boost is installed on the runner where your GitHub Actions workflow is executed. You can use the `setup-cpp` action to set up the necessary C/C++ tools and libraries, including Boost. Here's an example of how you can do this in your GitHub Actions workflow file (`.github/workflows/main.yml`):

   ```yaml
   name: Build and Test
   on: [push]

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: 3.8

       - name: Set up C/C++ tools
         uses: actions/setup-cpp@v2
         with:
           cpp-version: 17
           boost-version: 1.72

       - name: Build and Test
         run: |
           mkdir build
           cd build
           cmake ..
           make
           ctest
   ```

   In the above example, we use the `setup-cpp` action with the `boost-version` parameter to specify the Boost version you want to install. Adjust the version according to your needs.

2. Verify CMake configuration:

   In your CMake configuration, make sure you're finding Boost correctly. You can use the `find_package` command to locate the Boost libraries. Here's an example of how to do this in your `CMakeLists.txt` file:

   ```cmake
   find_package(Boost REQUIRED)
   include_directories(${Boost_INCLUDE_DIRS})

   add_executable(your_target your_source.cpp)
   target_link_libraries(your_target ${Boost_LIBRARIES})
   ```

   Ensure that the `find_package` command is correctly finding Boost.

3. Check GitHub Actions log:

   After running your GitHub Actions workflow, check the logs for any error messages related to Boost or CMake. This can help you identify any issues that may be preventing CMake from finding Boost.

4. Confirm Boost library paths:

   If CMake is still having trouble finding Boost, you can set the `BOOST_ROOT` CMake variable to specify the location of the Boost library installation. You can do this in your GitHub Actions workflow by adding a step before the CMake configuration:

   ```yaml
   - name: Set BOOST_ROOT
     run: cmake -DBOOST_ROOT=/path/to/boost ..
   ```

   Replace `/path/to/boost` with the actual path to your Boost installation.

By following these steps, you should be able to set up Boost, configure CMake to find it, and build your Python package with pybind11 in your GitHub Actions workflow. If you continue to experience issues, double-check your Boost installation and the CMake configuration in your project.
