### DISCUSSION TITLE
how to upload multiple files to artifact splitly

### DISCUSSION THREAD

**Discussion by sovzzz** [community/community#73432] [Actions]
### Select Topic Area

Question

### Body

I have several zip files
I'm using
```
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: ./distr/*.zip
```
I want I can choose which zip file to download on the actions page, but this  action only create a whole my-artifacts.zip containing those zips. how should I edit it?

**Comment by esurov** [comment]
If you want to be able to choose and download individual zip files from the GitHub Actions page instead of having them bundled into a single `my-artifacts.zip`, you can follow these steps to achieve that:

1. Create a new directory where you will store the individual zip files. Let's call it `individual_artifacts`.

2. Modify your workflow file to move the zip files to the `individual_artifacts` directory before using the `actions/upload-artifact` action. You can use the `mv` command for this. Here's how you can modify your workflow:

```yaml
- name: Move Zip Files
  run: |
    mkdir -p individual_artifacts
    mv ./distr/*.zip individual_artifacts/
- name: Upload Individual Artifacts
  uses: actions/upload-artifact@v2
  with:
    name: my-artifacts
    path: individual_artifacts/
```

In this modified workflow:

- First, a directory called `individual_artifacts` is created to store the individual zip files.
- Then, the `mv` command moves all the zip files from the `./distr` directory to the `individual_artifacts` directory.
- Finally, the `actions/upload-artifact` action uploads the `individual_artifacts` directory as a single artifact.

This way, you'll have individual zip files in the `individual_artifacts` directory inside the artifact, and you can download them separately from the GitHub Actions page.

Note that if you want to make the files even more accessible from the GitHub Actions page, you can create a simple HTML page or Markdown document within your repository that lists the individual zip files with download links. This would allow users to click on the links to download specific files easily.
