### DISCUSSION TITLE
Pull an image from a private artifact in a Docker container action

### DISCUSSION THREAD

**Discussion by AdityaHitachi** [community/community#73529] [Actions]
### Select Topic Area

Question

### Body

We want to pull image from our private artifact in one of our Dockerize action. While calling that action its giving error
_Error response from daemon: Head "my-image": unknown: Authentication is required
Error: Docker pull failed with exit code 1_

For example my `action.yaml` file for composite action looks like this, Is there any syntax with which we can provide authentication to this image using "cred"

```
name: Action
description: A GitHub Action that runs a Docker container 

inputs:
  name:
    description: 'Add name'
    required: true
runs:
  using: 'docker'
  image: docker://my-image
  env:
    STEPS_JSON: ${{ inputs.steps_json }}
```
