### DISCUSSION TITLE
loop problem and until

### DISCUSSION THREAD

**Discussion by ghost** [community/community#73525] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Bug

### Body
i'm ansible
Hi everyone, I'm making a playbook on ansible and I'll add my Latin if someone would be kind enough to look I put the until outside the block or in the block it doesn't work error message thank you ERROR ! 'until' is not a valid attribute for a Block.

The error appears to be in '/rootfs/data/users/admin/shared/ansible/aurore-zbsysupdate.yml': line 11, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        zbsysupdate_done: not zbsysupdate_done
    
until: zbsysupdate_done^ here

Do you have an idea thanks

- name: Mise à jour du client
  hosts: all
  become: yes  # Pour exécuter en tant que root
  tasks:
    - name: Liste des paramètres pour commencer
      ansible.builtin.set_fact:
        zbsysupdate_params: "--update --auto --confirm"
    - name: Contrôle d'exécution de la boucle
      ansible.builtin.set_fact:
        zbsysupdate_done: not zbsysupdate_done
    - until: zbsysupdate_done  
      block:
        - name: Exécution de zbsysupdate
          command: "/usr/zunobox/sbin/zbsysupdate {{ zbsysupdate_params }}"
          ignore_errors: no
          register: zbsysupdate_result
        - name: Si la commande s'est exécutée correctement, on s'arrête
          ansible.builtin.set_fact:
            zbsysupdate_done: zbsysupdate_result.rc == 0   
      rescue:
        - name: On s'arrête pour de bon si on a 2 fois la même erreur
          fail:
            msg: "Deux erreurs consécutives avec le même code de retour : {{ zbsysupdate_result.rc }}"
          when: zbsysupdate_result.rc == zbsysupdate_previous_rc
        - name: On enregistre le code de retour actuel
          ansible.builtin.set_fact:
            zbsysupdate_previous_rc: "{{ zbsysupdate_result.rc }}"
        - name: Nouvelle tentative après nettoyage si manque de place clair
          when: zbsysupdate_result.rc in [2, 3]
          block:
            - name: Supprimer les anciennes sauvegardes de MAJ
              command: "/usr/zunobox/sbin/zbsysupdate --cleanup"
            - name: Déplacer les enregistrements audio
              command: "/usr/packages/teambox/sbin/zbrecordcall --cleanup --upload --remove"
              when: zbsysupdate_result.rc == 2
            - name: Relancer la mise à jour avec --oksmall si nécessaire
              when: zbsysupdate_result.rc == 3
              ansible.builtin.set_fact:
                zbsysupdate_params: "{{ zbsysupdate_params }} --oksmall"   
            - name: Forcer la mise à jour en cas de version de départ inconnue
              when: zbsysupdate_result.rc in [7]
              ansible.builtin.set_fact:
                zbsysupdate_params: "{{ zbsysupdate_params }} --force"
      always:
    - name: Noter le problème
      when: zbsysupdate_result.rc == 0
      ansible.builtin.set_fact:
          zbsysupdate_reason: "Mise à jour terminée"
          zbsysupdate_done: true
    - name: Autre problème
      when: zbsysupdate_result.rc == 1
      ansible.builtin.set_fact:
        zbsysupdate_reason: "Erreur fatale"
        zbsysupdate_done: true
    - name: Manque d'espace disque
      when: zbsysupdate_result.rc in [2, 3]
      ansible.builtin.set_fact:
        zbsysupdate_reason: "Manque d'espace disque"
    - name: Système modifié
      when: zbsysupdate_result.rc == 4
      ansible.builtin.set_fact:
        zbsysupdate_reason: "Le système contient des modifications non standard"
        zbsysupdate_done: true
    - name: Déjà à jour
      when: zbsysupdate_result.rc == 5
      ansible.builtin.set_fact:
        zbsysupdate_reason: "Le système est déjà à jour"
        zbsysupdate_done: true
    - name: Pas de downgrade
      when: zbsysupdate_result.rc == 6
      ansible.builtin.set_fact:
        zbsysupdate_reason: "Le système est à une version supérieure, pas de downgrade"
    - name: Version initiale inconnue
      when: zbsysupdate_result.rc == 7
      ansible.builtin.set_fact:
        zbsysupdate_reason: "Le système est à une version inconnue"
    - name: Mise à jour invalide
      when: zbsysupdate_result.rc == 8
      ansible.builtin.set_fact:
        zbsysupdate_reason: "La mise à jour n'est pas valide"
        zbsysupdate_done: true
    - name: Erreur inconnue
      when: zbsysupdate_result.rc not in [0, 1, 2, 3, 4, 5, 6, 7, 8]
      ansible.builtin.set_fact:
        zbsysupdate_reason: "Une erreur inconnue: {{ zbsysupdate_result.rc }}"
        zbsysupdate_done: true
    - name: Enregistrer le résultat dans un fichier log
      ansible.builtin.copy:
        content: "{{ inventory_hostname }} mise à jour terminée : {{ zbsysupdate_reason }}"
        dest: /var/log/majclients.log
      delegate_to: localhost
    - name: Garder stderr en cas de problème
      when: zbsysupdate_result.rc != 0
      ansible.builtin.copy:
        content: "{{ inventory_hostname }} stderr:\n{{ zbsysupdate_result.stderr }}\n--------------------------"
        dest: /var/log/majclients.log
      delegate_to: localhost
zbs

**Comment by EliasAfara** [comment]
It appears that the issue is related to the incorrect placement of the until condition in the YAML playbook. To fix the bug, you should move the until condition inside the ansible.builtin.set_fact task where it is supposed to be. Here's the corrected version of your playbook:

```yaml
- name: Mise à jour du client
  hosts: all
  become: yes # To run as root
  tasks:
    - name: Liste des paramètres pour commencer
      ansible.builtin.set_fact:
        zbsysupdate_params: "--update --auto --confirm"
    
    - name: Contrôle d'exécution de la boucle
      ansible.builtin.set_fact:
        zbsysupdate_done: not zbsysupdate_done
      until: zbsysupdate_done
      block:
        - name: Exécution de zbsysupdate
          command: "/usr/zunobox/sbin/zbsysupdate {{ zbsysupdate_params }}"
          ignore_errors: no
          register: zbsysupdate_result
    
        - name: Si la commande s'est exécutée correctement, on s'arrête
          ansible.builtin.set_fact:
            zbsysupdate_done: "{{ zbsysupdate_result.rc == 0 }}"
    
      rescue:
        - name: On s'arrête pour de bon si on a 2 fois la même erreur
          fail:
            msg: "Deux erreurs consécutives avec le même code de retour : {{ zbsysupdate_result.rc }}"
          when: "zbsysupdate_result.rc == zbsysupdate_previous_rc"
    
        - name: On enregistre le code de retour actuel
          ansible.builtin.set_fact:
            zbsysupdate_previous_rc: "{{ zbsysupdate_result.rc }}"
    
        - name: Nouvelle tentative après nettoyage si manque de place clair
          when: "zbsysupdate_result.rc in [2, 3]"
          block:
            - name: Supprimer les anciennes sauvegardes de MAJ
              command: "/usr/zunobox/sbin/zbsysupdate --cleanup"
    
            - name: Déplacer les enregistrements audio
              command: "/usr/packages/teambox/sbin/zbrecordcall --cleanup --upload --remove"
              when: "zbsysupdate_result.rc == 2"
    
            - name: Relancer la mise à jour avec --oksmall si nécessaire
              when: "zbsysupdate_result.rc == 3"
              ansible.builtin.set_fact:
                zbsysupdate_params: "{{ zbsysupdate_params }} --oksmall"
    
        - name: Forcer la mise à jour en cas de version de départ inconnue
          when: "zbsysupdate_result.rc in [7]"
          ansible.builtin.set_fact:
            zbsysupdate_params: "{{ zbsysupdate_params }} --force"
    
    - always:
        - name: Noter le problème
          when: "zbsysupdate_result.rc == 0"
          ansible.builtin.set_fact:
            zbsysupdate_reason: "Mise à jour terminée"
            zbsysupdate_done: true
    
        - name: Autre problème
          when: "zbsysupdate_result.rc == 1"
          ansible.builtin.set_fact:
            zbsysupdate_reason: "Erreur fatale"
            zbsysupdate_done: true
    
        - name: Manque d'espace disque
          when: "zbsysupdate_result.rc in [2, 3]"
          ansible.builtin.set_fact:
            zbsysupdate_reason: "Manque d'espace disque"
    
        - name: Système modifié
          when: "zbsysupdate_result.rc == 4"
          ansible.builtin.set_fact:
            zbsysupdate_reason: "Le système contient des modifications non standard"
            zbsysupdate_done: true
    
        - name: Déjà à jour
          when: "zbsysupdate_result.rc == 5"
          ansible.builtin.set_fact:
            zbsysupdate_reason: "Le système est déjà à jour"
            zbsysupdate_done: true
    
        - name: Pas de downgrade
          when: "zbsysupdate_result.rc == 6"
          ansible.builtin.set_fact:
            zbsysupdate_reason: "Le système est à une version supérieure, pas de downgrade"
    
        - name: Version initiale inconnue
          when: "zbsysupdate_result.rc == 7"
          ansible.builtin.set_fact:
            zbsysupdate_reason: "Le système est à une version inconnue"
    
        - name: Mise à jour invalide
          when: "zbsysupdate_result.rc == 8"
          ansible.builtin.set_fact:
            zbsysupdate_reason: "La mise à jour n'est pas valide"
            zbsysupdate_done: true
    
        - name: Erreur inconnue
          when: "zbsysupdate_result.rc not in [0, 1, 2, 3, 4, 5, 6, 7, 8]"
          ansible.builtin.set_fact:
            zbsysupdate_reason: "Une erreur inconnue: {{ zbsysupdate_result.rc }}"
            zbsysupdate_done: true
    
        - name: Enregistrer le résultat dans un fichier log
          ansible.builtin.copy:
            content: "{{ inventory_hostname }} mise à jour terminée : {{ zbsysupdate_reason }}"
            dest: /var/log/majclients.log
            delegate_to: localhost
    
        - name: Garder stderr en cas de problème
          when: "zbsysupdate_result.rc != 0"
          ansible.builtin.copy:
            content: "{{ inventory_hostname }} stderr:\n{{ zbsysupdate_result.stderr }}\n--------------------------"
            dest: /var/log/majclients.log
            delegate_to: localhost
```

In this corrected version, the until condition is correctly placed inside the ansible.builtin.set_fact task, where it is supposed to be. This should resolve the issue you were facing.

**Reply by EliasAfara** [reply]
It appears that the issue you are experiencing is related to using a loop and the until condition in Ansible. To address this issue, it's important to understand how to structure your playbook correctly.

In Ansible, you can use the until loop in combination with register and until conditions to repeat a task until a certain condition is met. Here's an example of how you can structure your playbook to address this issue:


```yaml
- name: Mise à jour du client
  hosts: all
  become: yes # To run as root
  tasks:
    - name: Liste des paramètres pour commencer
      ansible.builtin.set_fact:
        zbsysupdate_params: "--update --auto --confirm"
    
    - name: Contrôle d'exécution de la boucle
      block:
        - name: Exécution de zbsysupdate
          command: "/usr/zunobox/sbin/zbsysupdate {{ zbsysupdate_params }}"
          ignore_errors: no
          register: zbsysupdate_result

        - name: Si la commande s'est exécutée correctement, on s'arrête
          ansible.builtin.set_fact:
            zbsysupdate_done: "{{ zbsysupdate_result.rc == 0 }}"
          until: zbsysupdate_done
          retries: 5
          delay: 10
          
        - name: Handling for when the condition is not met
          debug:
            msg: "The 'until' condition was not met after 5 retries."

      rescue:
        - name: Handling for rescue or failure
          fail:
            msg: "Task failed, handle the failure appropriately."

        # Add additional tasks as needed for different failure scenarios.

      always:
        - name: Final cleanup or logging tasks
```
In this example:

- The "Contrôle d'exécution de la boucle" block contains the task "Exécution de zbsysupdate," which is the task you want to repeat until the zbsysupdate_done condition is met.
- The until condition is used to retry the task until the zbsysupdate_done condition is true. The retries and delay parameters control the number of retries and the delay between retries, respectively.
- Inside the "always" section, you can add any tasks for final cleanup or logging.

By using this structure, you can repeat the task until the condition is met while handling failures or rescue scenarios appropriately. Make sure to customize it further to fit your specific use case and handle different failure scenarios as needed.
