### DISCUSSION TITLE
GitHub Action CI Integration on Katalon

### DISCUSSION THREAD

**Discussion by qcadins** [community/community#73540] [Actions]
### Select Topic Area

Question

### Body

How to use GitHub Actions with Katalon Studio after pushing/committing new code and cover code scanning in one workflow

thankyou 😊

**Comment by b8zeek** [comment]
Hey. 👋🏼 

Create a new file in your repository, `.github/workflows`. Create your workflow file in it.

Below is an example which will be triggered every time on push and pull request to the `main` branch. It has two jobs, testing (`katalon-test`) and code scanning (`code-scanning`). Testing check the code and runs Katalon Studio test suite while code scanning checks your code, initializes CodeQL for JS and performs analysis. Here you go:

```
name: Katalon Test and Code Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Katalon Studio Action
      uses: katalon-studio/katalon-action@v1
      with:
        args: '-noSplash -runMode=console -projectPath=".katalon/Katalon Studio Project.prj" -retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -executionProfile="default" -browserType="Chrome (headless)"'

  code-scanning:
    needs: katalon-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'javascript'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
```

P.S. Replace placeholders with an actual values.

Hope it helps, enjoy. 🍺 

🍀

**Reply by qcadins** [reply]
Hey thankyou for the respond

```
name: Katalon Test and Code Scanning

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'

  code-scanning:
    needs: katalon-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'groovy'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
```

i tried the workflow and adjust a little, the process is stuck at initialize codeql and give error 

`Run github/codeql-action/init@v[2](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:2)
  with:
    languages: groovy
    token: ***
    matrix: null
    setup-python-dependencies: true
    debug: false
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/github/codeql-action/v2/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async requestWithGraphqlErrorHandling (/home/runner/work/_actions/github/codeql-action/v2/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
    at async Job.doExecute (/home/runner/work/_actions/github/codeql-action/v2/node_modules/bottleneck/light.js:405:18) {
  status: 40[3](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:3),
  response: {
    url: 'https://api.github.com/repos/qcadins/ATeSign/code-scanning/analysis/status',
    status: [4](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:4)03,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 07 Nov 2023 02:2[5](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:5):11 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=3153[6](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:6)000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '[7](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:7)002:3569:CD6A1C:1A1DB[8](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:9)B:654[9](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:10)A007',
      'x-ratelimit-limit': '[10](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:11)00',
      'x-ratelimit-remaining': '992',
      'x-ratelimit-reset': '1699327026',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '8',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repos/qcadins/ATeSign/code-scanning/analysis/status',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'CodeQL-Action/2.22.5 octokit-core.js/3.6.0 Node.js/16.20.2 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"action_name":"init","action_oid":"unknown","action_ref":"v2","action_started_at":"2023-[11](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:12)-07T02:25:10.802Z","action_version":"2.22.5","analysis_key":".github/workflows/codacy.yml:code-scanning","commit_oid":"1c83db6a689da906a1f55f7cfc22e1815de6617a","job_name":"code-scanning","job_run_uuid":"e75cdcd4-5311-4[12](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:13)1-b6b4-6627c7b23e85","ref":"refs/heads/master","runner_available_disk_space_bytes":2453777[20](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:21)32,"runner_os":"Linux","runner_total_disk_space_bytes":89297309696,"started_at":"20[23](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:24)-11-07T02:[25](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:26):10.802Z","status":"starting","testing_environment":"","workflow_name":"Katalon Test and Code Scanning","workflow_run_attempt":1,"workflow_run_id":6779203607,"matrix_vars":"null","runner_arch":"X64","runner_image_version":"202310[30](https://github.com/qcadins/ATeSign/actions/runs/6779203607/job/18425908091#step:3:31).2.0"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}
Error: Resource not accessible by integration`

any solution?? thankyou 😊

**Comment by b8zeek** [comment]
Check this out:
>As of July 12, 2023, automatic dependency installation is disabled by default for new users of CodeQL for Python, with new users defined as those who have no prior Python projects set up for code scanning with CodeQL via advanced setup.

More on this link ➡️ https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning.

So, seems like you have to install dependencies manually, I copied the workflow from your repository and updated it a bit:
```
name: Katalon Test and Code Scanning

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'

  code-scanning:
    needs: katalon-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up JDK 1.8
    uses: actions/setup-java@v2
    with:
      java-version: '8'
      distribution: 'adopt'

    - name: Install Groovy
      run: |
        sudo apt-get update
        sudo apt-get install groovy

    - name: Install Dependencies
      run: |
        echo "groovy.grape.report.downloads=true" > ~/.groovy/grapeConfig.xml
        groovy -e "groovy.grape.Grape.grab(group:'commons-cli', module:'commons-cli', version:'1.4')"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
```

P.S. Definitely read the documentation in order to understand what is happening. ☺️

Good luck. 🍺 

🍀
