### DISCUSSION TITLE
GitHub Action deployment template to azure VM

### DISCUSSION THREAD

**Discussion by il-globaladmin** [community/community#73544] [Actions]
### Select Topic Area

Question

### Body

I am using Github action for my build and deployment i am using github hosted runner ,my source is git repository and my destination is Azure VM which is on ubuntu 22.04 LTS i am not getting any template for this .
Please anyone can help me with this

**Comment by b8zeek** [comment]
Of course. 😄 

Basic example of the workflow; this is triggered on every push to the `main` branch, obviously has two jobs `build` and `deploy`:

```
name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/path/to/your/project/on/the/server"

    - name: Execute commands on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /path/to/your/project/on/the/server
          npm install
          npm run start
```

P.S. Make sure to replace project path with an actual value, to add server's host, username and SSH.

P.P.S. In case you need these workflows, you can find the examples on GitHub Gist.

Good luck. 🍺 

🍀
