### DISCUSSION TITLE
How can I open a pull request in a separate repository from within a workflow?

### DISCUSSION THREAD

**Discussion by JesseTG** [community/community#73719] [Actions] [answered]
### Select Topic Area

Question

### Body

I'm writing a [package](https://github.com/JesseTG/melonds-ds) with an automated release pipeline. As part of this release, I'd like to send a pull request to [another repository](https://github.com/libretro/libretro-super) to update some related metadata. (They've already said it's fine.)

I have this release process _mostly_ in place, but I'm struggling to open the pull request to the metadata repository. [When I try](https://github.com/JesseTG/melonds-ds/actions/runs/6777867496/job/18422388176) with [these steps](https://github.com/JesseTG/melonds-ds/actions/runs/6777867496/workflow#L169-L199), I get the following error:

```
 pull request create failed: GraphQL: Resource not accessible by personal access token (createPullRequest)
```

The token I'm using has the following permissions:

![Screenshot 2023-11-06 191308](https://github.com/community/community/assets/1175189/d94d7b70-f18c-499c-a0b4-98b5f3c07ccb)

**How can I use GitHub Actions to submit a pull request to another repository after committing to a branch on my own fork of it?**

**Comment by b8zeek** [comment, marked as answer]
Greetings Jesse. 👋🏼 

Check this package, I think this is what you need ➡️ https://github.com/peter-evans/create-pull-request. Example workflow might look something like this:
```yaml
name: Create Pull Request

on:
  push:
    branches:
      - your-branch-name

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: your-username/your-forked-repo
          token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
          title: 'Your PR title'
          body: 'Your PR description'
          branch: 'branch-name-for-PR'
          base: 'branch-name-you-want-to-merge-changes-into'
          draft: false
```

P.S. Make sure to replace the values with the actual values.

Hope this solves the problem. Good luck. 🍺 

🍀
