### DISCUSSION TITLE
Using `env` or even just `github` inside of the `<job>.needs` field

### DISCUSSION THREAD

**Discussion by odinho** [community/community#74441] [Actions]
### Select Topic Area

Question

### Body

I am getting this error:

```
The workflow is not valid. .github/workflows/test-and-deploy.yml (Line: 74, Col: 12): 
  Unrecognized named-value: 'github'.
  Located at position 1 within expression:

    github.event_name == 'push' && github.ref == 'refs/heads/main'
      && fromJSON('["build_pkg", "test", "lint", "playwright"]') || 'build_pkg'
```

I have the following job:

```yaml
---                                                                                                                     
name: Test and deploy preview
on:                                                                                                                     
  pull_request:                                                                                                         
  push:                                                                                                                 
    branches:                                                                                                           
      - main                                                                                                                               
env:                                                                                                                                                                                                             
  MAIN_PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && '1' || '' }}                                                                                                                                                                                        
jobs:
   preview:
     if: github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main'
     needs: ${{ github.event_name == 'push' && fromJSON('["build_pkg", "test"]') || 'build_pkg' }}
     runs-on: ubuntu-latest
     steps:
        ...
```

So in other words, I am trying to dynamically set up a 'needs' relationship if this is a main push. I want the actual PRs to be much quicker in giving a preview deploy.

I at first tried to use `env.MAIN_PUSH`, but that didn't work. **It seems like `github` context is also not available in 'needs'.** Or is indeed nothing dynamic available there?
