### DISCUSSION TITLE
snake svg doesn't work on my github readme

### DISCUSSION THREAD

**Discussion by Codekaito** [community/community#74444] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello to all,

Since few months, i'm not able anymore to deploy my snake eating contributions svg, it seems it cannot create the svg, can someone help me?

I already enabled the read and write permissions on my repo.

![image](https://github.com/community/community/assets/57111980/4d84ae49-740d-476e-8250-2b0e9fbeb02e)

![image](https://github.com/community/community/assets/57111980/3be28fb1-a2db-427e-8a69-af0301e51c90)

**Comment by therasuldev** [comment]
the same problem . Did you solve the problem??

**Reply by Codekaito** [reply]
Hello, not yet. But it seems regarding my own profile, probably because I deleted some repo in the past

**Reply by sssfasih** [reply]
@therasuldev @CodeKaito check my comment

**Comment by sssfasih** [comment, marked as answer]
You need to update your `yaml` file. Just follow these three simple steps You'll not even need to update the username.

**Step 1: Replace all contents of `.github/workflows/MAIN.yml` file with:**
```
# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v3

    # Generates the snake  
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - name: Show build status
        run: git status

      - name: Push new files to output branch 
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Step 2: Run Workflow:**
 Click on your repository > Actions > Generate Snake (From left pane) > Run Workflow > Run Workflow

![image](https://github.com/community/community/assets/57562613/186345b4-787b-418a-b7f7-4d1782d67b0b)

**Step 3: Add these lines replacing your GitHub Username in place of `USERNAME` in your `README.md` file:**

```
<img alt="GitHub Snake" src="https://raw.githubusercontent.com/USERNAME/USERNAME/output/github-contribution-grid-snake.svg" />
```

**For Example:**
```
<img alt="GitHub Snake" src="https://raw.githubusercontent.com/sssfasih/sssfasih/output/github-contribution-grid-snake.svg" />
```

Click **Commit** and you're done! 

You may add `-dark` after the filename if you prefer the dark svg file.
