### DISCUSSION TITLE
Can't publish scoped NPM package in npm.pkg.github.com using GITHUB_TOKEN or PAT

### DISCUSSION THREAD

**Discussion by OnkelTem** [community/community#74608] [Actions]
### Select Topic Area

Question

### Body

I'm in a private GitHub repository and I need to publish my scoped packages in `npm.pkg.github.com`.

I haven't created an organization (because what for?) so it's just a private repository representing a monorepo with a scope.

First, I tried to use `secrets.GITHUB_TOKEN` along with `actions/setup-node@v3` but it didn't work out:

```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://npm.pkg.github.com/@myscope%2fmypackage - Permission permission_denied: The requested installation does not exist.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

Second, I tried to use PAT, but now I'm getting this error:

```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://npm.pkg.github.com/@myscope%2fmypackage - Permission permission_denied: create_package
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

Any ideas about what is going wrong here?

**Comment by pyhedgehog** [comment]
Project->Settings->Actions->General->Workflow permissions
By default it's set to "Read repository contents and packages permissions".
Switch it to "Read and write permissions" and retry.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by konsumer** [comment]
I have the same issue, even though I set my project to "Read and write permissions" and still get 403.

```yml
name: Publish package to GitHub Packages

# trigger by adding a release in Github interface
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@myorg'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

I also have a repository field in package.json:

```json
{
  "name": "@myorg/project",
  "repository": "https://github.com/myorg/project",
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/"
  }
}
```
