### DISCUSSION TITLE
Feature Request: schedule with inputs

### DISCUSSION THREAD

**Discussion by pbrisbin** [community/community#74698] [Actions]
### Select Topic Area

Product Feedback

### Body

I have a few workflows that can be run manually but also run on a schedule:

```yaml
name: Reset Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to reset"
        required: true

  schedule:
    - cron: "..." # reset staging every night
```

Imagine there are many such inputs.

I end up having to basically check for empty inputs and default it to what should be used in the `schedule` case:

```yaml
steps:
  - id: prep
    run: |
      env=${{ github.event.inputs.environment }}
      env=${env:-staging} # must be scheduled, reset staging
      echo "env=$env" >>"$GITHUB_OUTPUTS"

  - uses: whatever/whatever@x
    with:
      env: ${{ steps.prep.outputs.env }}
```

Again, imagine there are many such inputs.

This is cumbersome, hard to reason about, and error-prone. It also means that I can't schedule the workflow additional times with other values. There is only the one "not `workflow_dispatch`" branch available.

All of this would be solved if `schedule` elements supported an `inputs` key that became `github.event.inputs` when the workflow is executing for that schedule.

Then I could do the following:

```yaml
name: Reset Environment

on:
 workflow_dispatch:
    inputs:
      environment:
        description: "Environment to reset"
        required: true

  schedule:
    - cron: "..."
      inputs:
        environment: staging # self documenting
    - cron: "..."
      inputs:
        environment: other # not possible before

# ...

steps:
  - uses: whatever/whatever@x # no prep step needed
    with:
      env: ${{ github.event.inputs.environment }}
```

**Comment by pbrisbin** [comment]
For future readers, this can be made somewhat nicer by (ab)using `env`:

```yaml
name: Reset Environment

on:
 workflow_dispatch:
    inputs:
      environment:
        description: "Environment to reset"
        required: true

  schedule:
    - cron: "..."

env:
  ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }} # centralize fallbacks

steps:
  - uses: whatever/whatever@x # no prep step needed
    with:
      env: ${{ env.ENVIRONMENT }}
```

You still cannot do multiple schedules (you only get one fallback-when-unset), nor is it self-documenting in the `schedule` event definition that the default is "staging". But at least it's a little nicer than an extra prep step and bash substitutions.
