### DISCUSSION TITLE
I can't see the one who stars my repo

### DISCUSSION THREAD

**Discussion by Drun1baby** [community/community#74777] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I can't see the one who stars my repo

**Comment by eymeen** [comment]
try:
```
https://github.com/<USERNAME>/<REPOSITORY>/stargazers
```

**Reply by Drun1baby** [reply]
actually I see it, but I am there is no message appears in my github page

**Reply by elderguardian** [reply]
Hey, if you want to get notifications you can try [Star Notifier](https://github.com/marketplace/star-notifier).

You could also use GitHub Actions to execute something after someone starred your repository:
```
For example, you can run a workflow when someone stars a repository, which is the started activity type for a watch event.

on:
  watch:
    types: [started]
```
(https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#watch)
