### DISCUSSION TITLE
Pass arguments during the workflow execution

### DISCUSSION THREAD

**Discussion by Bakiera** [community/community#74828] [Actions] [answered]
### Select Topic Area

Question

### Body

Is it possible to create a workflow in GitHub which in the first step draws one number from 1 to 5, and then asks me to enter this number somewhere, then in the next step displayed "Answer correct/incorrect"? I need to pass values on the fly.

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by chienhsiang-hung** [comment]
Hi @Bakiera 

To pass runtime parameters in a GitHub workflow, you can use the workflow_dispatch event to manually trigger a workflow and define inputs that can be provided at runtime. Here's a step-by-step guide:
1. **Define the Workflow Dispatch Event:** In your workflow file, use the workflow_dispatch event to enable manual triggers. For example:
    ```yaml
    on:
      workflow_dispatch:
        inputs:
          number:
            description: 'Enter a number from 1 to 5'
            required: true
            default: '1'
    ```
2. **Use the Inputs in Your Workflow:** Access the provided inputs using the github.event.inputs context. For example, in a job step:
    ```yaml
    jobs:
      check-number:
        runs-on: ubuntu-latest
        steps:
          - name: Check if the number is correct
            run: |
              if [ ${{ github.event.inputs.number }} -eq $RANDOM_NUMBER ]; then
                echo "Answer correct"
              else
                echo "Answer incorrect"
              fi
    ```
    Replace `$RANDOM_NUMBER` with the logic to generate a random number between 1 and 5.
3. **Run the Workflow Manually:** Navigate to the 'Actions' tab of your GitHub repository, select the workflow, and then click on 'Run workflow' to provide the input parameter.

For more detailed information, you can refer to a guide by Damien Aicheh on setting runtime parameters to GitHub Actions workflows https://damienaicheh.github.io/github/actions/2022/01/20/set-dynamic-parameters-github-workflows-en.html.

Please note that the actual syntax and logic might vary based on your specific workflow setup and requirements. The above is a simplified example to illustrate the concept. If you need more tailored assistance, you might want to consult with a colleague who specializes in GitHub Actions within your organization.

**Comment by ooaklee** [comment, marked as answer]
Hey @Bakiera, I'm unsure if you are still interested in this feature. However, I've created a GitHub Action that allows you to do this and more (such as support `file` type inputs) - it's called [**Interactive Inputs**](https://github.com/boasiHQ/interactive-inputs/).

Check it out when you can, and give me a shout if you need a hand with anything.

## Basic Implementation for your use case

Here's an example workflow  for your described use case, and see its yaml underneath the gif

![InteractiveInput_GeneratedNumberCheckerFlow](https://github.com/user-attachments/assets/6c925b7a-de4b-40be-9dc7-b8ca0a02b9cc)


### Workflow



```yaml
name: '[Example] Match generated number flow'

on:
  push:

jobs:

  interactive-inputs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Generate random number
        id: get-random-number
        uses: actions/github-script@v7
        with:
          result-encoding: string
          # Script for generating random number sourced from: https://stackoverflow.com/a/7228322
          script: |
            function randomIntFromInterval(min, max) { // min and max included 
              return Math.floor(Math.random() * (max - min + 1) + min);
            }

            return randomIntFromInterval(1, 5);

      - name: Example Interactive Inputs Step
        id: interactive-inputs
        uses: boasiHQ/interactive-inputs@v2
        with:
          timeout: 300
          title: 'We need you to select your desired flow(s) to execute'
          interactive: |
            fields:
              - label: display-number
                properties:
                  description: This is a generated number
                  display: Generated Number
                  type: textarea
                  defaultValue: ${{ steps.get-random-number.outputs.result }}
                  readOnly: true
              - label: selected-number
                properties:
                  description: Match the generated number specified in the text field above
                  display: Enter the number you see above
                  type: number
                  required: true
          notifier-slack-enabled: "false"
          notifier-slack-channel: "#random"
          notifier-slack-token: ${{ secrets.SLACK_TOKEN }}
          notifier-discord-enabled: "false"
          notifier-discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          github-token: ${{ github.token }}
          ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Check if number matches
        id: check-number
        shell: bash
        run: |
          if [[ ${{ steps.interactive-inputs.outputs.selected-number }} -eq ${{ steps.get-random-number.outputs.result }} ]]; then
            echo "The number matches!"
          else
            echo "The number does not match."
          fi

```
