### DISCUSSION TITLE
Using an internal action within a composite action

### DISCUSSION THREAD

**Discussion by dreinhardt89** [community/community#74934] [Actions] [answered]
### Composite Actions

Currently I have a composite action that I manage in a private repo that is used by other private repos without issue. Within the composite action I also have references to a couple other composite actions within the same repo. My question is if it's possible to refer to the internal composite actions locally? I've tried setting the uses statement to `./path/to/dir` but that just picks up the working directory of the triggering action (which is checked out as the first step in the composite action).

My current workaround is to reference the internal action just like I would any composite action however making changes can get annoying as I have to update the `@v2` to whatever branch I'm currently working on.

Example of the composite action:
```yaml
name: 'Example Composite Action'
description: 'This composite action is stored on a private repository and is triggered in other private repositories.'
inputs:
  example_input:
    description: 'Example.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Example Internal Action - This internal composite action is stored in the same repository
      uses: Owner/repo/internal-actions/name-of-action@v2
```
