### DISCUSSION TITLE
[bug] dropdown failed with two options

### DISCUSSION THREAD

**Discussion by Arondight** [community/community#7496] [Projects and Issues]
```
  - type: dropdown
    id: git-status
    attributes:
      label: 代码状态：是否修改
      description: 运行命令 `git diff-index --quiet HEAD && echo 'Clean' || echo 'Dirty'` 并观察输出是。
      options:
        - Clean
        - Dirty
    validations:
      required: false
```

bug i get a `None` and dropdown has 3 options

![image](https://user-images.githubusercontent.com/13673702/140879390-f1c1875a-58ee-46b3-b5fc-f2e5868c1d28.png)
