### DISCUSSION TITLE
Tag filter in GitHub Actions containing underscore

### DISCUSSION THREAD

**Discussion by spydon** [community/community#75167] [Actions]
### Select Topic Area

Bug

### Body

I am trying to get our GitHub Actions workflow to match tags that look like this:
```
package_name-v1.2.3-dev
```
I have split up the tag filter into two sections, since the last part is optional, so it looks like this:

```yaml
name: Publish packages
on:
  push:
    tags:
      - '[a-z0-9_]+-v[0-9]+.[0-9]+.[0-9]+'
      - '[a-z0-9_]+-v[0-9]+.[0-9]+.[0-9]+-[A-Za-z0-9]+' # I've also tried without this one
```

```
push event contained invalid tags patterns: [a-z0-9_]+-v[0-9]+.[0-9]+.[0-9]+
(throws that "invalid tags patterns" error)
```

If I remove the `_` it stops complaining, but I need the tag name to be able to contain underscore. Any ideas?
