### DISCUSSION TITLE
The GitHub theme mode is weird.

### DISCUSSION THREAD

**Discussion by hwookim** [community/community#75361] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Product Feedback

### Body

For about a week now, GitHub has been showing me dark mode in some places.

I have the Light default selected with single theme option.
The system theme is dark, but I want GitHub to be light.

Am I the only one?
Is there a workaround?

This is Chrome on macOS.
I don't have the same issue in Safari.

I think the style is being applied incorrectly.
It seems to be mainly these two parts.
```css
.markdown-body {
    text-size-adjust: 100%;
    color: var(--color-fg-default);
    background-color: var(--color-canvas-default);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
    font-size: 16px;
    line-height: 1.5;
    overflow-wrap: break-word;
    margin: 0px;
}

```
```css
.color-bg-subtle {
    background-color: var(--bgColor-muted, var(--color-canvas-subtle)) !important;
}
```

![스크린샷 2023-11-13 오후 8 27 40](https://github.com/community/community/assets/45786387/e8d69810-f44c-42f6-add3-fd314e8eb833)
![스크린샷 2023-11-13 오후 8 30 39](https://github.com/community/community/assets/45786387/70da069d-89cc-4ae9-acb2-fbabdd36492e)
![스크린샷 2023-11-13 오후 8 35 35](https://github.com/community/community/assets/45786387/ac9c5703-39d0-46f7-ba16-688c21f19573)
