### DISCUSSION TITLE
Required dropdown lists in Issue Forms are not really required

### DISCUSSION THREAD

**Discussion by laurent22** [community/community#75372] [Projects and Issues]
### Select Topic Area

Bug

### Feature Area

Issues

### Body

I have a required dropdown list defined like so:

```yaml
- type: dropdown
  id: os
  attributes:
    label: "Operating system"
    multiple: false
    options:
      - "Windows"
      - "macOS"
      - "Linux"
      - "Android"
      - "iOS"
  validations:
    required: true
```

So what I would expect is that the user must pick one of the operating systems. However when creating a new issue, the field displays like so:

<img width="157" alt="image" src="https://github.com/community/community/assets/1285584/119b6b50-f86f-45fc-bcef-dc68cd9cfbd3">

So the user doesn't have to fill up this field, they can just leave the default value. What I would expect instead is to have a default  "empty" value and if the user didn't choose something else, there would be an error. This is for example how Discourse works.

In fact it seems it's also how it's supposed to work on GitHub as I see there's this magical "None" option that's documented here and there, except it's not showing up.

Any idea if setting a default empty value is possible?

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
