### DISCUSSION TITLE
How to set actions version same as reusable workflow version

### DISCUSSION THREAD

**Discussion by IndraGunawan** [community/community#75485] [Actions]
### Select Topic Area

Question

### Body

let's say i have an reusable workflow

```yaml
# org/repo/.github/workflows/ci.yaml
name: ci

on:
  workflow_call:
    inputs:
      some-input:
        description: Some input
        type: string
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: call action
        uses: org/repo/action1@main
        with:
          some-input: ${{ inputs.some-input }}
```

`action1` action is on the same repo as the reusable workflow

and i call above reusable workflow from another repository

```yaml
# org/another-repo/.github/workflows/ci.yaml
name: ci

on:
  workflow_dispatch:

jobs:
  ci:
    uses: org/repo/.github/workflows/ci.yaml@main
    with:
      some-input: some-input
    secrets: inherit
```

is there a way to make `action1` action automatically use the same revision as the reusable workflow?
current condition:

```
antoher-repo --> `ci` reusable workflow with `main` revision --> `action1` action with `main` revision
```

even when i change the reusable workflow to use another branch, the reusable workflow will still call `action1` action from `main`

```
antoher-repo --> `ci` reusable workflow with `feature1` revision --> `action1` action with `main` revision
```

what i want is

```
antoher-repo --> `ci` reusable workflow with `feature1` revision --> `action1` action with `feature1` revision
```

without updating the reusable workflow
