### DISCUSSION TITLE
Composite action versioning

### DISCUSSION THREAD

**Discussion by rsenden** [community/community#75505] [Actions]
### Select Topic Area

Question

### Body

I have a single repository containing multiple reusable composite actions, i.e.:

* `my-org/my-action/action.yml`
* `my-org/my-action/sub-action1/action.yml`
* `my-org/my-action/sub-action2/action.yml`

The top-level composite action may use `sub-action1`, and `sub-action2` may use `sub-action2`. These actions are to be versioned together, so if a workflow uses `my-org/my-action@v1` (effectively using `@v1.1.2` for example), the top-level action should use the corresponding `sub-action1@v1` or `sub-action1@v1.1.2` version.

Given the number of sub-action invocations, and the fact that we don't know the next version number to be released upfront (version numbers are automatically determined based on semantic commit messages), manually updating all `uses:` statements is not an option.

Is there any way to have sub-action invocations 'inherit' the version number from the action that's invoking the sub-action? I've tried the following, but GitHub doesn't accept either format:

- `uses: my-org/my-action/sub-action1@${{github.action_ref}}`
- `uses: my-org/my-action/sub-action1` (omitting the version number)

Any suggestions how to properly implement this?

**Comment by rsenden** [comment]
It seems like GitHub doesn't support use cases like this out of the box, so I've been working on a GitHub Actions workflow that automatically updates the version numbers/branch names for sub-action invocations. This workflow is based on [release-please-action](https://github.com/google-github-actions/release-please-action), which we were already using for automatic versioning based on conventional commit messages.

The workflow contains two jobs:
- `update-action-references`: Triggered on any push to any branch, this job will update all sub-action usages to use `org/github-action/sub-action@<branch-name>`. For example, when testing a new feature, we can have a test workflow that uses `org/github-action@feat-1`,which in turn properly uses `org/github-action/sub-action@feat-1`.
- `build-and-release`: Triggered on pushes to the `main` branch, using release-please-action to generate a release PR if applicable and updating that release PR to insert the proper `use: org/github-action/sub-action@<version from version.txt>`. When merging a release PR, release-please-action will generate the appropriate `v<major>.<minor>.<patch>` tag, and the job will add `v<major>` and `v<major>.<minor>` tags. 

This is just a proof of concept for now; any suggestions for improvement are welcome.

`update-action-refs.sh` script used by the workflow below:
```bash
#!/bin/bash
for f in $(find . -name 'action.yml'); do 
  if grep -qrlZ 'uses: org/github-action/' $f; then
    echo "Updating $f: version $1" && \
    sed -r -i -e "s|(uses: org\/github-action\/[^@]+)@.*|\1@$1|g" "$f"
  fi
done
```

GitHub Actions workflow
```yaml
on:
  push:
      
permissions:
  contents: write
  pull-requests: write
      
name: Publish release
jobs:
  update-action-references:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out source code
        uses: actions/checkout@v4
      - name: Update action version references to match branch
        run: |
          ./update-action-refs.sh "${GITHUB_REF#refs/heads/}"
          git config user.name github-actions
          git config user.email github-actions@company.com
          git add . && git commit -m "chore: Update action references" && git push || \
            echo "No update needed" 
            
  build-and-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: update-action-references
    steps:
      - name: Check-out source code
        uses: actions/checkout@v4
      
      - name: Generate and process release PR
        id: release_please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: ${{ github.event.repository.name }}
          
      - name: Publish v{major}.{minor} tag
        if: steps.release_please.outputs.release_created
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{steps.release_please.outputs.major}}.${{steps.release_please.outputs.minor}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Publish v{major} tag
        if: steps.release_please.outputs.release_created
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{steps.release_please.outputs.major}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update release PR
        if: steps.release_please.outputs.pr
        shell: bash
        run: |
          prBranch=${{ fromJSON(steps.release_please.outputs.pr).headBranchName }}
          git fetch origin "${prBranch}"
          git checkout "${prBranch}"
          version=v$(cat version.txt)
          ./update-action-refs.sh "${version}"
          git config user.name github-actions
          git config user.email github-actions@company.com
          git add . && git commit -m "chore: Update action references" && git push || echo "No update needed" 
```
