### DISCUSSION TITLE
Accept SHA hashes and tags as refs in workflow_dispatch API

### DISCUSSION THREAD

**Discussion by matfax** [community/community#75513] [Apps, API and Webhooks]
### Select Topic Area

Product Feedback

### Body

At the moment, the workflow_dispatch API does only accept branches, no tags or hashes.

github/docs#590

I propose adding the support for all ref types. The git refs API uses all three types analogically as well.

[REST API: Git References](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28)

Related: #45871

**Comment by ElvenSpellmaker** [comment]
To add to this, it's not possible to use `refs/pull/209/merge` style references too, which means you end up having to trigger based on the `HEAD` branch i.e. `feat/foo-bar`, and then checkout the `merge` reference in the checkout step which isn't ideal...

**Reply by dan-phantom** [reply]
@ElvenSpellmaker could you give an example? I'm trying to restart a workflow when we manually start a different one but I don't manage to 🙏

**Reply by ElvenSpellmaker** [reply]
Hey @dan-phantom, the way I do it is to trigger a build using a HEAD branch ref, but I pass through the merge commit ref as an input to the called Pipeline:

```yml
on:
  workflow_dispatch:
    inputs:
      BranchRef:
        description: "The branch to checkout, e.g. 'refs/pull/10/merge', or 'main'"
        required: true
        default: 'main'
        type: string
```

```pwsh
$json = @{"BranchRef" = $MergeBranchRef}

...

	ConvertTo-Json `
		-InputObject $json `
		-Depth 10 `
	| gh workflow run `
		$workflowName `
		--ref $HeadBranchRef `
		--json
```

And then when you checkout, use the input ref:
```yml
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.BranchRef }}
```
