### DISCUSSION TITLE
How to set PR title as run-name for merge_group job/wf

### DISCUSSION THREAD

**Discussion by kiran-pedduri-sndk** [community/community#75594] [Actions]
### Select Topic Area

Question

### Body

I have a workflow on merge_group (below is the example), as the event for this workflow is merge_group, How can I set run-name as the PR title?

************************************************
name: GK Job (Post PR verify Job)
run-name: ${{ github.event.pull_request.title }}

on:
  merge_group:
    branches:
        - 'xyz'

**Comment by ivnvxd** [comment]
In GitHub Actions, the `run-name` field doesn't directly support the use of context expressions like `${{ github.event.pull_request.title }}` to set dynamic names based on event payloads. This is primarily because the `run-name` is evaluated and set at the beginning of the workflow run, before many context variables are populated.

However, there's a workaround to achieve a similar result by using a step within your workflow to dynamically name your run, although it won't change the name of the workflow run itself, but can help in labeling or tagging steps or artifacts within the workflow.
```yaml
name: GK Job (Post PR verify Job)

on:
  merge_group:
    branches:
      - 'xyz'

jobs:
  set-run-name:
    runs-on: ubuntu-latest
    steps:
      - name: Set Run Name
        run: echo "RUN_NAME=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

```
In this example, a new job `set-run-name` is added to capture the PR title and set it as an environment variable `RUN_NAME`. You can then use this environment variable in subsequent steps or jobs within the same workflow.

The `RUN_NAME` will only be available in the steps after it is set, not in the initial stages of the workflow. It won't change the display name of the workflow run in the GitHub Actions UI.
