### DISCUSSION TITLE
How to publish artifacts github actions to on premises windows vm

### DISCUSSION THREAD

**Discussion by spatil25v** [community/community#75635] [Actions]
### Select Topic Area

Question

### Body

publish artifacts github actions to on premises windows vm

**Comment by jamirou** [comment]
You must have a .yml file in the .github/workflows folder in your repository. https://www.baeldung.com/spring-yaml
configure your personal GitHub token and store it as a secret in your repository. Then, use the token in your workflow to authenticate.
To configure you can use: `gh workflow run -R owner/repo -f publish-artifacts.yml`
Check and refresh the project. I hope it work my friend:)

**Comment by wasimtikki120** [comment]
Publishing artifacts from GitHub Actions to an on-premises Windows VM involves a few steps. GitHub Actions provide a feature called "artifacts" that allows you to upload and download files between jobs. Below is a general guide on how you can achieve this:

### 1. Create a GitHub Actions Workflow:

Create a `.yml` file in the `.github/workflows` directory of your repository. This file defines your GitHub Actions workflow.

Here's a basic example:

```yaml
name: Publish Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add your build steps here
    
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/your/artifacts
```

Replace `path/to/your/artifacts` with the path where your build artifacts are generated.

### 2. Set up a Self-Hosted Runner:

Since you want to publish artifacts to an on-premises Windows VM, you need to set up a self-hosted runner on that VM. The runner will execute the GitHub Actions workflow on your VM.

Follow the GitHub documentation to set up a self-hosted runner: [Configuring a self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners)

### 3. Configure the Workflow for Self-Hosted Runner:

Update your workflow file to specify that the job should run on the self-hosted runner. For example:

```yaml
name: Publish Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add your build steps here
    
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/your/artifacts
```

### 4. Set Up the Windows VM:

Make sure the Windows VM has the necessary dependencies installed for your build. This may include Git, any build tools, and any other dependencies required by your project.

### 5. Run the Workflow:

Push changes to your repository to trigger the workflow. GitHub Actions will execute the workflow on the self-hosted runner on your Windows VM.

### 6. Retrieve Artifacts on the Windows VM:

If the workflow is successful, you can download the artifacts on the Windows VM using the GitHub API or GitHub CLI. For example:

```bash
gh run download <run-number> --workflow=<workflow-name>
```

Replace `<run-number>` with the run number of the workflow and `<workflow-name>` with the name of your workflow.

This is a basic guide, and you may need to customize it based on your specific build and deployment requirements.
