### DISCUSSION TITLE
[Help] Failing to push to origin after having cloned a different public repo

### DISCUSSION THREAD

**Discussion by albbus-stack** [community/community#75865] [Actions]
### Select Topic Area

Question

### Body

```yml
name: Update Kit Stack to latest version
on: workflow_dispatch
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./repo

      - name: Update repo (& create PR)
        run: |
          BRANCH_NAME="kit-stack-update"

          cd repo/
          # Create a new feature branch for the changes.
          git checkout -b $BRANCH_NAME

          cd ..
          git clone --depth=1 https://github.com/albbus-stack/kit-stack ./kit-stack

          # Move all the updated kit-stack repo files
          cp -r ./kit-stack/.[!.]* ./repo
          rm -rf ./kit-stack

          cd repo

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          # Commit the changes and push the feature branch to origin
          git add .
          git commit -m "chore: update kit-stack"
          git push origin $BRANCH_NAME
```

I have this workflow but it keeps failing with `fatal: could not read Username for 'https://github.com/': No such device or address`. The repo that I'm cloning is public and it pulls it correctly. The problem is when I push the changes; it seems like the repo remote origin gets changed up even if I'm working in a different directory. In the end all I'm trying to do is push a new branch to the repo owned by this workflow...

I have also setup the correct write permission for workflows inside the repo settings.

Do you have any ideas on how can I fix this?
