### DISCUSSION TITLE
Error when evaluating 'strategy' for job,  Unexpected value

### DISCUSSION THREAD

**Discussion by kunaltyagi** [community/community#75886] [Actions]
### Select Topic Area

Question

### Body

```yaml
  do_job:
    needs: [data_wrangling]
    strategy:
      max-parallel: ${{ needs.data_wrangling.outputs.count}}
      matrix:
        server: ${{ fromJson(inputs.data) }}
```

This results in an error for `max-parallel`, with `Unexpected value '3'` (or some number as string).

Using `fromJson` doesn't help, no matter how many times (or where) it is applied.

What could be a workaround for this?
