### DISCUSSION TITLE
Jobs not getting picked up by the runner group

### DISCUSSION THREAD

**Discussion by tusharmath** [community/community#75978] [Actions]
### Select Topic Area

Question

### Body

Below is my `benchmarking-runner` group. Which I have integrated in my `bench.yml`

https://github.com/tailcallhq/graphql-benchmarks/blob/1bf2bc316127e70fd1b2427f72cbcd62aa77088e/.github/workflows/bench.yml
```yml
name: "Run benchmark"

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, edited]

permissions: write-all

jobs:
  build:
    runs-on:
      group: benchmarking-runner

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false # Avoids persisting credentials

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.pull_request.head.repo.full_name }}

      - name: Build devcontainer and run benchmarks
        uses: devcontainers/ci@v0.3
        with:
          imageName: graphql-benchmarks
          push: never
          runCmd: |
            bash ./setup.sh
            bash ./run_benchmarks.sh

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update performance results in README.md"
```

<img width="956" alt="Screenshot 2023-11-19 at 10 22 43 AM" src="https://github.com/community/community/assets/194482/42f680e5-a70b-4287-821c-31fd3a67b9dc">

**Expected**
The job should have been picked up by the runner.

**Actual**
The job remains pending and the runner remains idle.
