### DISCUSSION TITLE
Unexpected Merge Queue Behaviour

### DISCUSSION THREAD

**Discussion by kam-ushur** [community/community#76042] [Actions]
### Select Topic Area

Question

### Body

Perhaps our usage of the merge queue feature is incorrect but what is observed is if a merge queue has the following PRs:

PR 1
PR 2
PR 3

Then the PRs will run github action checks in parallel on our CI/CD servers. So PR 1 might be running some github actions while PR 2  and PR 3 might be running some other github actions. Once all checks pass for PR 1 then the PR gets merged and it is immediately removed from the merge queue.

However what is surprising is that PR 2 and PR 3 now restart all the CI/CD checks. Is that expected? We're not seeing the behaviour outlined here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#successful-ci where once all checks pass for all the PRs then the whole group of PRs are merged in one shot.

Also what seems ideal to me is that if PR 1 is merged then the PR 2 ci/cd checks should just continue from where they started (some jobs may have already succeeded) but what we see is that everything get cancelled and they start from scratch.

Our workflow looks like the following below. I wonder if cancel-in-progress or concurrency config is causing issues with the merge_queue event (?)

```
name: Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    name: Tests
    runs-on: "some-server"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: | 
          echo "Running tests"
          exit 0
```
