### DISCUSSION TITLE
`strategy.matrix` doesn't accept `fromJson(JSON)` as an input

### DISCUSSION THREAD

**Discussion by kunaltyagi** [community/community#76213] [Actions]
### Select Topic Area

Bug

### Body

![image](https://github.com/community/community/assets/2657068/43321224-6a1e-4202-ba8f-184e4eea7254)

This error is despite using:
```yaml
  broadcast:
    needs: [data_wrangling]
    strategy:
      fail-fast: false
      max-parallel: ${{ fromJson(needs.data_wrangling.outputs.num_jobs_json) }}
      matrix:
        server: ${{ fromJson(needs.data_wrangling.outputs.server_json) }}
```

Both num_jobs and server json are set identically:
* using `return JSON.stringify(<variable>);`
* inside a `actions/github-script@v7.0.0` script context
