### DISCUSSION TITLE
GH Action: On push event filter branch

### DISCUSSION THREAD

**Discussion by Laerciogj** [community/community#76226] [Actions]
### Select Topic Area

Question

### Body

How do you specify/allow hyphen(-) characters on the branches filter? I've tried the following, but none seemed to work and trigger the action.

```yaml
on:
  push:
    branches:
      - 'sample'
      - '!sample/**'
      # - '[a-zA-Z-]+/**' # Doesn't work
      # - '[a-zA-Z\-]+/**' # Doesn't work
      # - '[a-zA-Z\\-]+/**' # Doesn't work
      # - '[a-zA-Z]+-+/**' # Doesn't work
```

ps.: pushes from branch `my-test-branch/something123` doesn't seem to trigger the action.

ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

Thank you, any help is much appreciated.
