### DISCUSSION TITLE
Workflow for tags is not triggered after performing `git push --follow-tags` with PAT in Actions environment

### DISCUSSION THREAD

**Discussion by frantic1048** [community/community#76402] [Actions]
### Select Topic Area

Bug

### Body

**Description**

We have a repository with a GitHub action that conditionally create a new commit(and annotated git tag(s)) and push it back to the repository with a  **Personal Access Token**, done through  [beachball](https://microsoft.github.io/beachball/)'s  `publish`  command.

```
git config --local user.email "npm-publisher@rightcapital.com"
git config --local user.name "GitHub Actions[bot]"
git remote set-url origin "https://${{ secrets.REPO_AUTOMATION_TOKEN }}@github.com/${{ github.repository }}.git"
pnpm beachball publish --yes -m 'chore(release): applying package updates'

```

> reference:  [https://github.com/RightCapitalHQ/frontend-style-guide/blob/8052e3de61efb8c2b1aea424ce14c30b1ad89f50/.github/workflows/ci.yml#L98-L101](https://github.com/RightCapitalHQ/frontend-style-guide/blob/8052e3de61efb8c2b1aea424ce14c30b1ad89f50/.github/workflows/ci.yml#L98-L101)

> About  `beachball publish`, it does a  `git tag <args>`([tagPackages.ts](https://github.com/microsoft/beachball/blob/8d587c9f4afe57d4e203f0d5111790df2f494cff/src/publish/tagPackages.ts#L6)) and followed by a  `git push --follow-tags`([bumpAndPush.ts](https://github.com/microsoft/beachball/blob/8d587c9f4afe57d4e203f0d5111790df2f494cff/src/publish/bumpAndPush.ts#L70)).

After pushing the new commit and tags(always start with  `@rightcapital/`), it successfully triggers workflow for the branch(`on.push.branches: ['main']`), but never triggers workflow for tags(`on.push.tags: ['@rightcapital/**']`) (We're using this workflow to create Releases on GitHub). Here's the workflow definition:

-   runs on branch push:  [https://github.com/RightCapitalHQ/frontend-style-guide/blob/8052e3de61efb8c2b1aea424ce14c30b1ad89f50/.github/workflows/ci.yml](https://github.com/RightCapitalHQ/frontend-style-guide/blob/8052e3de61efb8c2b1aea424ce14c30b1ad89f50/.github/workflows/ci.yml)
-   runs on tag push:  [https://github.com/RightCapitalHQ/frontend-style-guide/blob/8052e3de61efb8c2b1aea424ce14c30b1ad89f50/.github/workflows/release.yml](https://github.com/RightCapitalHQ/frontend-style-guide/blob/8052e3de61efb8c2b1aea424ce14c30b1ad89f50/.github/workflows/release.yml)

Example commit(with tags on it) that only triggers workflow for branch, but does not trigger workflow for tag:  [https://github.com/RightCapitalHQ/frontend-style-guide/commit/8052e3de61efb8c2b1aea424ce14c30b1ad89f50](https://github.com/RightCapitalHQ/frontend-style-guide/commit/8052e3de61efb8c2b1aea424ce14c30b1ad89f50)

I think both workflows(includes the workflow runs on tag push) should run when push new commit with tags.

---

**Other info**:

Here's a minimal repo with similar automation process as above repo([https://github.com/RightCapitalHQ/frontend-style-guide](https://github.com/RightCapitalHQ/frontend-style-guide)). Unfortunately I  **cannot reproduce**  the same symptom in this minimal repo.

[https://github.com/frantic1048/workflow-for-automated-tags](https://github.com/frantic1048/workflow-for-automated-tags)

**Reproduction Steps**

Each time the commit  `chore(release): applying package updates`  with tags are pushed to the repo([RightCapitalHQ/frontend-style-guide](https://github.com/RightCapitalHQ/frontend-style-guide)), for example:

-   [https://github.com/RightCapitalHQ/frontend-style-guide/commit/8052e3de61efb8c2b1aea424ce14c30b1ad89f50](https://github.com/RightCapitalHQ/frontend-style-guide/commit/8052e3de61efb8c2b1aea424ce14c30b1ad89f50)
-   [https://github.com/RightCapitalHQ/frontend-style-guide/commit/171d0a87ae52ada1f80e5a421affa81eaf8304ac](https://github.com/RightCapitalHQ/frontend-style-guide/commit/171d0a87ae52ada1f80e5a421affa81eaf8304ac)  (Note: there is a workflow for tag being created on this commit, it is triggered by a human manually pushing a tag from a computer, not by GitHub workflow)

**Comment by I-Want-ToBelieve** [comment]
Confirmed that the issue is reproduced: Neither GITHUB_TOKEN nor PAT can trigger tags listening for other actions

**Comment by I-Want-ToBelieve** [comment]
https://github.com/orgs/community/discussions/27194#discussioncomment-7038913

**Comment by sysserv** [comment]
**You can modify your workflow to trigger on both commit and tag push events. this will ensure that the workflow runs whenever a new commit or tag is pushed to the repository.**

```
name: Release

on:
  push:
    branches: [ main ]
  tags:
    tags: [ '@rightcapital/**' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        uses: actions/create-release@v6
        with:
          tag_name: ${{ github.event_name }}
          release_name: ${{ github.event_name }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: release-assets
          path: ./dist/*.zip

```

**the workflow will run whenever a new commit or tag is pushed to the repository. for commits, it will trigger on the main branch, while for tags, it will trigger on any tag that starts with @rightcapital/**
