### DISCUSSION TITLE
org. reusable action running script in reusable action repo, not the caller missing ENV

### DISCUSSION THREAD

**Discussion by LegendSebastiano-L** [community/community#76412] [Actions]
### Select Topic Area

Question

### Body

I'm creating a reusable action, or that would be the idea but I'm having some problems with executing the correct script.

We have a repo which is a full app containing all the scripts needed to execute the job, E.g this is where my reusable action live `my-org/my-repo/.github/workflows/my-action.yml@my-branch`

and this is how I call it in the other repo (`my-org/my-other-repo/`):
```
name: Export
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  export:
    uses: my-org/my-repo/.github/workflows/my-action.yml@my-branch
```

`my-action.yml` looks like this
```
      - name: Export the Contentful Environment and Upload to a S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: yarn serverless invoke local --function exportContentfulSpace
```

this `yarn serverless` script is coming from the `my-org/my-repo` package.json file but isn't accessible from the parent making the workflow failing.

Is there a way to run this app completely from `my-org/my-repo/` without care from where it's called?

**Comment by LegendSebastiano-L** [comment]
OK I got it working with docker though now the code is searching for a `.env` file and can't specify them with the `env` key

I've tried
```
inputs:
  CONTENTFUL_SPACE_ID:
    description: 'Contentful space ID'
    required: true
  CONTENTFUL_ENVIRONMENT_ID:
    description: 'Contentful space environment'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
     CONTENTFUL_SPACE_ID: ${{ inputs.CONTENTFUL_SPACE_ID }}
     CONTENTFUL_ENVIRONMENT_ID: ${{ inputs.CONTENTFUL_ENVIRONMENT_ID || 'master' }}
```

and then:
```
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Export
        uses: XXXX
        with:
          CONTENTFUL_SPACE_ID: space-id
          CONTENTFUL_MANAGEMENT_TOKEN: CONTENTFUL_MANAGEMENT_TOKEN
```

I've also tried to remove the input/env from the child and just replace the `with` with `env` in the parent workflow but no luck.

It returns: `DOTENV: Could not find .env file.` which seems to be needed by https://www.serverless.com/framework/docs/environment-variables
