### DISCUSSION TITLE
Only run a specific actions based on the project name in a mono repo?

### DISCUSSION THREAD

**Discussion by lifeofmoo** [community/community#76613] [Actions]
### Select Topic Area

Question

### Body

Hello,

Similar to https://github.com/orgs/community/discussions/59309

We have a simple workflow which calls a reusable workflow.

```
name: Build dev infrastructure
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  workflow_dispatch:

jobs:
  build-infrastructure:
    uses: My-Ltd/terraform-gha/.github/workflows/build-infrastructure.yaml@main
    with:
      ENV: (could be dev,stg,live)
      TERRAFORM_DIR : i.e terraform/ecr-repos
    secrets: inherit
```
Looking at my repo folder tree
```
├── .github
│   └── workflows
└── terraform
    ├── cloudfront
    ├── ecr-repos
    ├── oidc
    └── organization
```

 If I made a commit/push to main branch, how could I provide / pass in the following to inputs.

- TERRAFORM_DIR
- ENV

Yes this can be done with inputs with workflow_dispatch but that is a manual trigger.
