### DISCUSSION TITLE
Incorrect branch name for `workflow_run` trigger

### DISCUSSION THREAD

**Discussion by jozefizso** [community/community#76693] [Actions]
### Select Topic Area

Question

### Body

When workflow uses the `workflow_run` trigger and sets custom `run-name` the `${{ github.ref_name }}` value incorrectly refers to `main` (the default branch) instead of the `release/v1.0.0` which is the actual branch that the dependent workflow was run with.

```yaml
name: deploy

run-name: Release build ${{ github.event.run_number }} (${{ github.ref_name }})

on:
  workflow_run:
    workflows: [build]
    branches: ['release/*']
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
    - name: deploy
      run: ./run-deploy.sh 
```
