### DISCUSSION TITLE
API call to create GHE release failed with status code 401

### DISCUSSION THREAD

**Discussion by liangming2003** [community/community#76830] [Enterprise]
### Select Topic Area

Question

### Body

Hi Guys

I'm using a Azure pipeline template to upload a release asset to GitHub Enterprise.

Here is the error I got from run that template.

**API call to create GHE release failed with status code 401.**

I googled it , 401 means "unauthorized", so what's wrong with my setup of template to get this "unauthorized" error.

Is there way I can get more information from that template API call to figure out why it is "unauthorized"? Thanks

Here is my template setup:

```
- template: steps/git/github-create-release.yaml@templates
  parameters:
    githubRepo: "client/SysInfo"
    githubUrl: "github.azc.ext.xx.com"
    githubUser: "winapp"
    githubToken: "$GithubToken"
    assets: $BUILD_ARTIFACTSTAGINGDIRECTORY\\*.msi
    body: "Test Release"
    draft: true
    name: "My first release"
    tagName: "v1.0.0"
```

Here is the part of template yaml:

```
parameters:
  - name: githubUser
    type: string

  - name: githubToken
    type: string

  - name: githubRepo
    type: string

  - name: githubUrl
    type: string

  - name: tagName
    type: string

  - name: name
    type: string

  - name: body
    type: string

  - name: draft
    type: boolean

  - name: prerelease
    type: boolean

  - name: assets
    type: string


steps:
  - bash: |
      echo "Creating a release at ${{ parameters.githubUrl }}/api/v3/repos/${{ parameters.githubRepo }}/releases with tagName [${{ parameters.tagName }}] and name [${{ parameters.name }}]."
      release_parameters() {
        draft=${{ parameters.draft }}
        prerelease=${{ parameters.prerelease }}
        cat <<EOF
      {
        "tag_name": "${{ parameters.tagName }}",
        "name": "${{ parameters.name }}",
        "body": "${{ parameters.body }}",
        "draft": ${draft,,},
        "prerelease": ${prerelease,,}
      }
      EOF
      }
      RESPONSE=$(curl -u ${{ parameters.githubUser }}:${{ parameters.githubToken }} \
          --location --request POST ${{ parameters.githubUrl }}/api/v3/repos/${{ parameters.githubRepo }}/releases \
          --header "Content-Type: application/json" \
          --data "$(release_parameters)" \
          -s -w "%{http_code}")
      STATUS=$(tail -n1 <<< "$RESPONSE")    // status code 401 returned from here.

      if [ $STATUS -eq 201 ]; then
        echo "Successfully created a new release tagged ${{ parameters.tagName }}."
        // code for upload the asset
      else
        echo "API call to create GHE release failed with status code $STATUS."
      fi
```
