### DISCUSSION TITLE
Add a comment to the pull request if CI fails?

### DISCUSSION THREAD

**Discussion by laurent22** [community/community#76884] [Actions]
### Select Topic Area

Question

### Body

I would like to have a GitHub Action that checks other Actions for failure on pull requests. And if one of the GA fails, it will add a comment to the pull request.

I assume this is a common use case but I can't find anything about it. I only found this [comment-failure-action](https://github.com/quipper/comment-failure-action) but it's discontinued and undocumented. Is there anything better I could use?

**Comment by aangelinsf** [comment]
Is there any way you can add the comment to the end of the action that is failing? If that's not possible, you could watch for a failed workflow_run. Something like this:

```
name: Notify user of failed workflows

on:
  workflow_run:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Make comment on failed GA
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ env.REPO_FULLNAME }}
          issue-number: ${{ env.ISSUE_NBR}}
          body: |
            This failed.
  ```
  
  The issue_nbr in this case is actually the PR id.
