### DISCUSSION TITLE
"Unable to resolve action" when running shared workflow calling a composite workflow calling a custom workflow, all internal to org

### DISCUSSION THREAD

**Discussion by brandon-happyreturns** [community/community#76965] [Actions]
### Select Topic Area

Question

### Body

I have a js based custom workflow in repository A and a suite of shared and composite workflows in repository B.

I've created a composite workflow in repo B that calls the custom workflow in repository A, and when either are called independently in other caller workflows within my org everything works fine.

I have a shared workflow in repository B that tests my composite workflow in repo B that's calling the custom workflow in repo A - when this shared workflow in repository B runs, I get the error: 
```Error: Unable to resolve action `<org>/<repo A>`, repository not found```

All permissions are setup fine as evident by the composite and custom workflows working in other caller workflows. I'm checking out the composite workflow within the shared workflow without issue. 

I only seem to get this error when running the shared workflow in repo B that calls the custom workflow within the composite worfklow.

Has anyone else experienced this?

**Comment by sysserv** [comment]
To resolve this issue, 

Make sure the custom workflow in repository A is public. The custom workflow needs to be public so that the shared workflow in repository B can access it.

Use a personal access token to authenticate with repository A. If the custom workflow is private, you can use a personal access token to authenticate with repository A when calling the custom workflow from the shared workflow.

Clone the custom workflow from repository A into repository B. This will allow the shared workflow to access the custom workflow without having to authenticate with repository A.


**Example of how to use a personal access token to authenticate with repository A:**

```
steps:
- uses: actions/checkout@v3
  with:
    fetch-depth: 1
- uses: actions/setup-node@v3
  with:
    node-version: '16'
- name: Authenticate with repository A
  uses: octokit/request-action@v3
  with:
    token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    repository: '<org>/<repo A>'
    path: /repos/<org>/<repo A>/actions/workflows/custom-workflow.yaml
    method: GET
- name: Run custom workflow
  uses: ./.github/actions/custom-workflow
```
