### DISCUSSION TITLE
Github Action - Event "create" - filtering on branch

### DISCUSSION THREAD

**Discussion by MClauwaert** [community/community#77088] [Actions]
### Select Topic Area

Question

### Body

We recently added a trigger to a Github action using the [create](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#create) trigger.
We wanted to filter on certain branches (eg. if a new branch 'master' is created. Then this workflow should trigger for/on that branch). We presumed based on a StackOverflow answer that we could use the "branches" filter. Similar on how the "push" trigger works.

However this does not work as intended. If someone creates a new branch "GH/AddEventCreate". This also triggers the yml. Although we only wanted to filter/limit it on 'master'. 

```
on:
  create:
    branches:
        - develop #This doesnt work. 
  workflow_dispatch:
    inputs:
        branch:
            description: 'Define branch name'
            required: true
            default: 'develop'
  push:
    branches:
    - develop
    paths:
    - src/Api/**
    - src/Common**
    - src/Data**
    - src/Services**
```

![image](https://github.com/community/community/assets/91329133/d8254b7c-4605-41f9-8ce1-dbc7a0f226c1)

- Can we limit the "create" trigger to only trigger for certain branches?
