### DISCUSSION TITLE
GHA workflow not being invoked when comment is made by Github bot

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [community/community#77083] [Actions]
I have the following GHA workflow:

```yaml

name: Add comments
on:
  issue_comment:
    types: [created, edited]

jobs:

  add-comments:
    if: github.event.comment.body == 'my comment' && github.event.issue.pull_request
    strategy:
      matrix:
        environment: [dev1, dev1]
    name: add extra comments
    runs-on: ubuntu-latest
    steps:

      - name: add ${{ matrix.environment }} comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "${{ matrix.environment }}-do something"
```

i.e. when someone makes a `my comment` comment to a PR, the above workflow should be triggered and add two extra comments, `dev1-do something` and `dev2-do something`.

When I add `my comment` manually, everything works as expected.

I have another workflow that:

a) creates a pr
b) adds a comment to the pr that should trigger the above workflow

```yaml
    - name: create the PR
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          committer: ${{ env.COMMITER }}
          branch: ${{ steps.pr-branch-name.outputs.pr_branch_name }}
          base: 'master'
          title: Some title
          body: PR automatically created by GitHub Action

      - name: add the comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.create-pr.outputs.pull-request-number }}
          body: "my comment"
```

However, when the second workflow completes with success and **does** add the comment, the first one is never invoked. If I manually add the `my comment` comment, the initial workflow works as expected. Does this somehow relates with permissions or the velocity to which the a) pr is created b) the comment is made?

I have no clue whatsoever up till now what might be causing the initial workflow not to be invoked.
