### DISCUSSION TITLE
Referencing reuseable workflow referencing a local one not working with any tag

### DISCUSSION THREAD

**Discussion by higaski** [community/community#77106] [Actions] [answered]
### Select Topic Area

Question

### Body

Hello

I'm new to reusable workspaces and have just started trying to write one for a running unit tests in C++. The workflow itself re-references another local workflow in the same [repository](https://github.com/ZIMO-Elektronik/.github-workflows/blob/master/.github/workflows/ctest.yml) (`x86_64-linux-gnu-gcc.yml`).

```yml
name: ctest

on:
  workflow_call:
    inputs:
      target:
        description: 'CMake test target'
        default: ${{ github.event.repository.name }}Tests
        required: false
        type: string

jobs:
  x86_64-linux-gnu-gcc:
    uses: ./.github/workflows/x86_64-linux-gnu-gcc.yml
    with:
      target: ${{ inputs.target }}
      upload-artifact: true

  ctest:
    needs: x86_64-linux-gnu-gcc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          name: build.tar
          path: .
      - run: tar -xvf build.tar
      - run: ctest --test-dir build --schedule-random
```

I'm now trying to use this workflow from another repository like this:
```yml
jobs:
  tests:
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/ctest.yml@v0.0.1
    with:
      target: all
```

But for some reason this doesn't seem to work. GitHub keeps telling me that the local workflow doesn't exist:
```sh
error parsing called workflow ".github/workflows/tests.yml" -> "ZIMO-Elektronik/.github-workflows/.github/workflows/ctest.yml@v0.0.1" (source tag with sha:c23f5c8f48bf22556705346de61cbca499db5839) --> "./.github/workflows/x86_64-linux-gnu-gcc.yml" : workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.
```

If I checkout the same workflow using `@master` instead of a versioned tag however this works fine:
```yml
jobs:
  tests:
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/ctest.yml@master
    with:
      target: all
```

```sh
Current runner version: '2.311.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4.1.1' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
Download action repository 'actions/upload-artifact@v3.1.3' (SHA:a8a3f3ad30e3422c9c7b888a15615d19a852ae32)
Uses: ZIMO-Elektronik/.github-workflows/.github/workflows/x86_64-linux-gnu-gcc.yml@refs/heads/master (231ab4aa81d7f3ebe02d7f0910e7359b3ed6da14)
 Inputs
Complete job name: tests / x86_64-linux-gnu-gcc / x86_64-linux-gnu-gcc
```

Why is that?
