### DISCUSSION TITLE
Trigger multiple workflows

### DISCUSSION THREAD

**Discussion by elipesatya** [community/community#77121] [Actions]
### Select Topic Area

General

### Body

Hi All

Im trying to codify a work flow that inturn triggers multiple workflows, but Im thrown with"message": "Not Found" error, looks like URL doesn't point to the workflow to be triggered. Wonder whats wrong in the URL, can anyone see an issue there ?

Many thanks in advance. 

Code:
```
name: Trigger Multiple Workflows

on:
  workflow_dispatch:

jobs:
  trigger-multiple-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger "checkov scans for staging weblets"
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/organization/repo/actions/workflows/checkov_scans_staging_web.yml/dispatches" \
            -d '{"ref":"master"}'
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Repeat the above step for each workflow you want to trigger
```

Error:
```
Run curl -X POST \
  curl -X POST \
    -H "Authorization: token ***" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/organization/repo/actions/workflows/checkov_scans_staging_web.yml/dispatches" \
    -d '{"ref":"master"}'
  shell: /usr/bin/bash -e {0}
  env:
    PERSONAL_ACCESS_TOKEN: ***
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   151  100   135  100    16    395     46 --:--:-- --:--:-- --:--:--   444
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event"
}```
