### DISCUSSION TITLE
ENV/Secrets within Reusable workflows limitations and workarounds

### DISCUSSION THREAD

**Discussion by Nithos** [community/community#77259] [Actions]
### Select Topic Area

Question

### Body

I will start that as far as I can tell this is not feasible currently but wondering if there is a workaround. 

First some context, I have a reusable workflow for building docker images directly or through a bake file. This works great, I call the reusable workflow from any org repository and pass it my Dockerfile location, targets (if bake file), any other input params I need that are exposed along with the login credentials for the container registry. The reusable workflow takes all that input builds the image and pushes it to the registry. 

Example
```
bake:
    name: Build Docker Images
    needs:
      - bake-target
    uses: org/repo/.../reusable-bake-build.yaml@main
    with:
      file: "docker-bake.hcl"
      push: ${{ github.event_name != 'pull_request' }}
      group: ${{ needs.bake-target.outputs.target }}
      registry: "ghcr.io"
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}
```

Up to this point this works great, however I have a new request now. I need to build an image that contains a reference to a private maven repository that pulls a dependency down. For this to work I have to pass secrets to the docker file, is there any way to accomplish this with a reusable workflow?

As far as I can tell a reusable workflow can not inherit ENV variables, it can inherit secrets but I don't think I can specify both `inherit` **and** specify specific `secrets` inputs to the workflow. I can not simply add more secrets/inputs as it needs to be generic and should not care/know what other variables are required to build the image. Is there a way to pass in a secrets file or a `.env` file that can then be extracted?

It seems that the only option here is to abandon the reusable workflow and do it within the main workflow as a regular job which will have access to any ENV that were set ahead of time.

Has anyone worked around this issue before?
