### DISCUSSION TITLE
Github Action to mantain repository

### DISCUSSION THREAD

**Discussion by rubenmgx** [community/community#77283] [Actions]
### Select Topic Area

Question

### Body

Hi Guys!

Im pretty new with Github Actions, sorry if this is a "dumb" question :D 

I would like to mirror a repository and each time there is a new release created, have a Github Action to detect the new release, then modify one of the files with the new version and afterwards push the changes to the main branch (for example).

I believe that  to detect the new release coming to my repo should be something like:

```
on:
  release:
    types: [published, created, edited]
```

But in terms of editing a file and pushing the changes I've not been able to find much around. Do you have any idea if this is possible?

Im also thinking of a possibility of adding a variable to the file to automatically pick up the new version release, so I could skip the editing part and just perform a commit?

Thanks in advance!

**Comment by elderguardian** [comment]
Hey, you are on the right track with the workflow event. This is untested but could work:

You will need to add the secrets `COMMIT_EMAIL` and `COMMIT_NAME` or hardcode the values.
This works by executing a file called `change-version.js` to do the actual changes.
```
name: Update Version

on:
  release:
    types: [published]
    
jobs:
  update-version:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.email "${{ secrets.COMMIT_EMAIL }}"
          git config --global user.name "${{ secrets.COMMIT_NAME }}"
          echo 'machine github.com login ${{ secrets.COMMIT_NAME }} password ${{ secrets.GITHUB_TOKEN }}' > ~/.netrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Change Version
        run: node change-version.js

      - name: Commit and Push Changes
        run: |
          git add --all
          git commit -m "Update Version"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
