### DISCUSSION TITLE
Best trigger to make sure all PRs pass a CI build?

### DISCUSSION THREAD

**Discussion by SimonCockx** [community/community#77434] [Apps, API and Webhooks] [answered]
### Select Topic Area

Question

### Body

Hi

In my attempt to setup a CI build on PRs using Github actions, I noticed some PRs trigger the build _twice_:
```
name: Maven Build on Ubuntu

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Build with Maven
      run: mvn -B -U clean package
```

By reading the docs, I figured that a `git push` triggers both the `push` trigger and the `pull_request` trigger of type `synchronize`. It seems to me that the `synchronize` event was exactly what I was looking for, so I changed the trigger to this:
```
on:
  workflow_dispatch:
  pull_request: # types `opened`, `reopened` and `synchronized` are the default
```

Today however, I stumbled on [this discussion](https://github.com/open-telemetry/opentelemetry-python/issues/1370), which many repositories seem to use as a reference. They are pleading for this trigger:
```
on:
  push:
    branches: master
  pull_request:
    types: [opened, reopened]
```

So, what is the best practice for triggering a CI build to protect a repository from merging PRs with a build failure?

**Comment by b8zeek** [comment, marked as answer]
Greetings Simon. 👋🏼 

The best practice for triggering a CI build to protect a repository from merging pull requests with a build failure is definitely to use both `push` and `pull_request` events. However, you should limit the `push` event to only the main / master branch to avoid duplicate runs.

Update:
```
name: Maven Build on Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Build with Maven
      run: mvn -B -U clean package
```

Hope this is what you're looking for. Cheers! 🍺 

🍀
