### DISCUSSION TITLE
Missing job output value

### DISCUSSION THREAD

**Discussion by Kisiel02** [community/community#77569] [Actions]
### Select Topic Area

Question

### Body

Hi there,

I'm currently navigating the world of GitHub workflows and have been tasked with creating one, drawing inspiration from an existing setup.

The workflow's objective is to build an app from the repository, create a Docker image, tag it, push it to an ECR registry, and subsequently deploy it to two environments by updating the task definition in ECS.

The challenge I'm facing is the inability to pass the output of the first job to the second. While the values are present during the first job, they appear empty in the second. Strangely, when I pass a hardcoded value like _hello=world_, everything works as expected. It's only when values are dynamically evaluated that they seem to vanish.

Here's the essential part of my workflow:

```yaml 
name: Build and Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
        - 'README.md'
        - '.gitignore'

jobs:
  build-push:
    name: Build and push to ECR
    runs-on: ubuntu-latest
    env:
      BUILD_PATH: app/publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dotnet Tooling
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: tests
        run: dotnet test
  
      - name: package
        run: |
            cd <app name>.API
            dotnet publish <app name>.API.csproj -o $BUILD_PATH

      - name: Build Image
        run: |
          cd <app name>.API 
          test -d $BUILD_PATH
          docker build --build-arg BUILD_PATH=$BUILD_PATH -t <app name>-api .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GA_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: 'arn:aws:iam::<account id>:role/<role>'
          aws-region: eu-central-1
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and publish Image to ECR
        id: build-image
        env:
            ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
            ECR_REPOSITORY: <repository name>
            DIGEST: ${{ github.sha }}
        run: |
            docker tag <app name>-api $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker tag <app name>-api $ECR_REGISTRY/$ECR_REPOSITORY:$DIGEST
            docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
            echo "::set-output name=latest::$ECR_REGISTRY/$ECR_REPOSITORY:latest"
            echo "hello=world" >> "$GITHUB_OUTPUT"
            echo "image_output=$ECR_REGISTRY/$ECR_REPOSITORY:$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Print outputs
        env:
          PUSH_OUTPUT_IMAGE: ${{ steps.build-image.outputs.image_output }}
          PUSH_OUTPUT_LATEST: ${{ steps.build-image.outputs.latest }}
          HELLO_WORLD: ${{ steps.build-image.outputs.hello }}
        run: |
          echo "Image output: $PUSH_OUTPUT_IMAGE"
          echo "Image latest output: $PUSH_OUTPUT_LATEST"
          echo "Hello: $HELLO_WORLD"

    outputs:
      image_output: ${{ steps.build-image.outputs.image_output }}
      image_output_latest: ${{ steps.build-image.outputs.latest }}
      hello: ${{ steps.build-image.outputs.hello }}

  print-outputs:
    name: Print output of build-push
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Print output
        run: |
          echo "Value from outputs image: ${{ needs.build-push.outputs.image_output }}"
          echo "Value from outputs latest: ${{ needs.build-push.outputs.image_output_latest }}"
          echo "Value from outputs hello: ${{ needs.build-push.outputs.hello }}"
          
  deploy-stage:
    name: Deploy stage
    needs: [build-push, print-outputs]
    runs-on: ubuntu-latest
    env:
      STAGING_ACCOUNT: <staging account id>
    steps:
      - name: Configure AWS credentials for service account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GA_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ env.STAGING_ACCOUNT }}:role/<role>
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Download existing task definition
        run: aws ecs describe-task-definition --task-definition <app service> --query taskDefinition > task-definition.json

      - name: Replace new image in task definition
        id: define-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: <app service>
          image: ${{ needs.build-push.outputs.image_output }}

      - name: Deploy new task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.define-task.outputs.task-definition }}
          service: <app service> 
          cluster: <cluster name>
          wait-for-service-stability: true

```
In the _Print outputs_ step within the _build-deploy_ job, everything appears fine, and the image tag is successfully logged, both latest and with digest. Images are visible in the ECR.

However, in the _print-outputs_ job, the _hello_ variable has the value _world_, but _image_output_ and _image_output_latest_ are empty.  In the _deploy-stage_ job, the image is also empty.

I'm seeking guidance on what might be amiss in this workflow. Any insights or assistance would be greatly appreciated!
