### DISCUSSION TITLE
gha-runner-scale-set - specifying custom dind image

### DISCUSSION THREAD

**Discussion by LillyHolden-Tide** [community/community#77566] [Actions]
### Select Topic Area

Question

### Body

Is there an option to specify a custom dind image in gha-runner-scale-set chart?
Seems like the [values file](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml#L135) indicates that this can be done but I can see that the value is hardcoded in the [chart](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/_helpers.tpl#L99)?

We need this feature as we are hitting dockerhub rate limiting and would like to be able to pull the image from our local registry instead.

**Comment by ohookins** [comment]
Yes it's possible, but you have to override the entire template section, e.g.:

```
# From: https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml#L108
template:
  spec:
    initContainers:
    - name: init-dind-externals
      image: <YOUR_IMAGE>

      <MORE STUFF HERE>

    containers:
    - name: runner
      image: <RUNNER_IMAGE>

      <MORE STUFF HERE>

    - name: dind
      image: <YOUR_IMAGE>
```

And then provide that as a values file to Helm.
