### DISCUSSION TITLE
two GitHub I/O sites from one repository - can't use GitHub desktop or command line

### DISCUSSION THREAD

**Discussion by v-stephclark** [community/community#77580] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Question

### Body

I have a public repo from which I need to publish two GitHub I/O sites for different audiences. One site will use one folder and the other site a different folder. The pages will be published using GitHub actions. Both sites must use the same theme (just-the-docs) and the same ruby gems (see example pages.yml code below). I do not have the ability to use GitHub desktop or run commands from a command line as I am working on a virtual machine without those privileges/apps. I think this can be done using either two sets of publishing actions in the pages.yml folder or by publishing one site from the main and the other from a branch. However, I can't figure out how to designate two different URLs or how to make the branch automatically update and publish when changes are made to the main folder. Can anyone help? Here is the current pages.yml file (I do have the Gemfile and Gemfile.lock files in the repository and it is currently publishing correctly from the docs folder):

```
name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
    paths-ignore: 'Coach/**'          # this is the other folder that needs the second site published from it

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'        # Not needed with a .ruby-version file
          bundler-cache: true            # runs 'bundle install' and caches installed gems automatically
          cache-version: 0        #  Increment this number if you need to re-download cached gems
          path-ignore: 'Coach/**'          #   this is the other folder that needs the second site published from it
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
