### DISCUSSION TITLE
How to manage conditional dependencies ?

### DISCUSSION THREAD

**Discussion by h2oearth** [community/community#77732] [Actions]
### Select Topic Area

Question

### Body

I would like to know how to ensure that `job3` is always executed after `job1` or `job2`. My issue is that if `job2` does not run due to` branch != master`, `job3` won't run! 

What do you think is the best way to manage this scenario?

```
jobs:
 job1:
    name: job1
    uses: ./.github/workflows/job1.yml
 job2:
    name: job2
    if: ${{  startsWith(github.ref_name, 'master')  }}
    needs: [job1]
    uses: ./.github/workflows/job2.yml
 job3:
    name: job3
    if: ${{ needs.job1.result == 'success' && needs.job2.result == 'success'  }}
    needs: [job1, job2]
    uses: ./.github/workflows/job3.yml
```
