### DISCUSSION TITLE
Feature Request: gha-runner-scale-set: Support annotations to ServiceAccount via Helm chart regardless of containerMode

### DISCUSSION THREAD

**Discussion by Nuru** [community/community#77817] [Actions]
### Select Topic Area

Bug

### Body

In [the Helm chart for `gha-runner-scale-set`](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set), you can add annotations to the runner's ServiceAccount *only* when running in "kubernetes" mode. I would like to be able to add annotations in "dind" or customized mode as well.

My primary use case is to assign an IRSA role to the runners. 

1. While we could probably use GitHub OIDC, those credentials are limited to 6 hours. Some jobs (e.g. end-to-end testing) run considerably longer than that. IRSA credentials automatically refresh, but GitHub OIDC credentials do not.
2. By assigning IRSA roles (possibly with no IAM permissions) to runners, we can limit access to IAM roles to specific runner groups. 
3. This provides compatibility with Summerwind's `actions.summerwind.net` API group, allowing us to use the same workflows without modification.

**Comment by dakshithadissanayaka** [comment]
Sure, here is a summary of the discussion and a possible solution:

**Issue:**

A user is asking if it's possible to automatically create pull requests from issues in GitHub.

**Possible Solution:**

Yes, it is possible to automatically create pull requests from issues in GitHub using automation tools like GitHub Actions. This can be helpful for streamlining workflows and ensuring that pull requests are created for relevant issues.

Here's an example of how to set up a GitHub Actions workflow to automatically create pull requests from issues:

```yaml
name: Create Pull Request from Issue

on:
  issue_comment:
    types: [created, edited]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if issue has 'PR' label
        id: check-label
        run: |
          if [ "$(gh issue labels --issue=${{ github.event.issue.number }} | grep 'PR')" != '' ]; then
            echo "Issue already has 'PR' label. Skipping pull request creation."
            exit 1
          fi

      - name: Create pull request
        if: steps.check-label.outcome != 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const title = context.issue.title;
            const body = context.issue.body;

            github.issues.createPullRequest({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              base: context.repo.default_branch,
              head: `refs/heads/${issueNumber}`,
              draft: false
            });
```

This workflow will listen for comments on issues. If a comment is added or edited, it will check if the issue has a label named "PR". If it doesn't, it will create a pull request from the issue.

You can customize this workflow to fit your specific needs, such as adding more conditions for creating pull requests or adding labels to the pull request.
