### DISCUSSION TITLE
Finish your review box does not stick to the button

### DISCUSSION THREAD

**Discussion by e102** [community/community#77848] [Pull Requests]
### Select Topic Area

Bug

### Body

In the PR review page, the "finish your review" box that pops up is no longer stuck to the header and instead moves down the page as you scroll.

Steps to reproduce:
- go to the "files changed" tab
- scroll down a bit
- click "finish your review"
- scroll up

<img width="1701" alt="Screenshot 2023-12-04 at 12 52 22" src="https://github.com/community/community/assets/9124637/4821c411-0dc6-4a8f-961d-1b46213df23e">

**Comment by dakshithadissanayaka** [comment]
Sure, here is a summary of the discussion and a possible solution:

**Issue:**

A user is reporting that the "Finish your review box" in GitHub pull request review pages is no longer sticking to the header and moves down the page as they scroll.

**Possible Solution:**

The issue of the "Finish your review box" moving down the page when scrolling can be resolved by adding fixed positioning to the CSS class responsible for the box. Here's the CSS code to fix the positioning:

```css
.pr-review-box--stuck {
  position: fixed;
  top: 0;
  right: 0;
  width: 300px;
  z-index: 100;
  background-color: #fff;
  border: 1px solid #ccc;
  padding: 10px;
}
```

This CSS code will ensure that the "Finish your review box" remains fixed to the top-right corner of the window, even when scrolling the page.
