### DISCUSSION TITLE
Need help on how to delete stale branches in github repositories using github actions

### DISCUSSION THREAD

**Discussion by salini8642** [community/community#77867] [New to GitHub]
Can anyone help me on how to delete stale branches using github actions without touching protected branches and open PRs are also.
Thanks in advance.

sorry, where 30days is mentioned, if in case I need to change time period at least 90 days how it can happened
and if in case I need to use github actions with octokit how can I proceed if you know can you please help me

**Comment by dakshithadissanayaka** [comment]
Sure I can help with that. Here is an example workflow that you can use to delete stale branches using GitHub Actions:

```yaml
name: Delete stale branches

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    types: [closed]

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all --tags

      - name: List stale branches
        id: list-stale-branches
        run: |
          excluded_branches=$(git config --local --list branch.protection.*.name | cut -d '=' -f 2)
          excluded_branches_list=$(for branch in $excluded_branches; do echo "- $branch"; done)
          stale_branches=$(git branch -r --sort=-committer-date | sed '1d' | grep -v -e "^\*" -e "$excluded_branches_list")

          echo "Excluded branches: $excluded_branches"
          echo "Stale branches: $stale_branches"

      - name: Delete stale branches
        run: |
          for branch in $stale_branches; do git push origin --delete $branch; done

          echo "Deleted stale branches: $stale_branches"
```

This workflow will run every day at 00:00 UTC. It will also run when a pull request is closed. The workflow will first fetch all branches, including tags. Then, it will list all stale branches. A stale branch is a branch that has not been updated in at least 30 days. Finally, the workflow will delete all stale branches.

Here is a breakdown of the workflow:

* The `on` section specifies that the workflow should run every day at 00:00 UTC and when a pull request is closed.
* The `jobs` section specifies that there is one job called `delete-stale-branches`.
* The `delete-stale-branches` job runs on the `ubuntu-latest` runner.
* The first step in the `delete-stale-branches` job checks out the repository to the runner.
* The second step fetches all branches, including tags.
* The third step lists all stale branches. A stale branch is a branch that has not been updated in at least 30 days.
* The fourth step deletes all stale branches.

I hope this helps!
