### DISCUSSION TITLE
Using a single yaml file for multiple environments

### DISCUSSION THREAD

**Discussion by kendjr** [community/community#77898] [Actions] [answered]
### Select Topic Area

Question

### Body

I am attempting to use one yaml workflow file for a number of different environments. I cannot determine if there is a way to use a variable specific to an environment in a single yaml file. I have read about reusing workflows (https://docs.github.com/en/actions/using-workflows/reusing-workflows), but it still appears as though you would need to create a yaml file for every environment. 
How can I pass the variables for a specific environment into one yaml file?

```
jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      environment:
            name: {{DETERMINE THE ENVIRONMENT BASED ON THE BRANCH?}}
            url: ${{ steps.deploy.outputs.DEPLOYMENT_URL }}
      steps:
# use the environment specific variable "DEV_ALIAS"
      - run: echo "URL is ${{ vars.DEV_ALIAS }}"

```

**Comment by guspan-tanadi** [comment, marked as answer]
Somehow have seen related [comment](https://github.com/actions/starter-workflows/issues/245#issuecomment-803708937) of the issue for deploy multiple targets through single configuration.

By referring as provided based on [Max Ivanov](https://github.com/actions/starter-workflows/issues/245#issuecomment-803708937) comment.

```YAML
jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
#     environment:
#           name: {{DETERMINE THE ENVIRONMENT BASED ON THE BRANCH?}}
#           url: ${{ steps.deploy.outputs.DEPLOYMENT_URL }}
      steps:
# use the environment specific variable "DEV_ALIAS"
#     - run: echo "URL is ${{ vars.DEV_ALIAS }}"

      - name: Set env vars (dev)
        if: endsWith(github.ref, '/dev')
        run: |
          echo "DEPLOYMENT_URL=staging.example.com" >> $GITHUB_ENV
          echo "GH_SECRET_DEPLOYMENT_KEY=SECRET_NAME_FOR_DEV" >> $GITHUB_ENV
      - name: Set env vars (docs)
        if: endsWith(github.ref, '/docs')
        run: |
          echo "DEPLOYMENT_URL=docs.example.com" >> $GITHUB_ENV
          echo "GH_SECRET_DEPLOYMENT_KEY=SECRET_NAME_FOR_DOCS" >> $GITHUB_ENV
      - name: Set env vars (prod)
        if: endsWith(github.ref, '/master')
        run: |
          echo "DEPLOYMENT_URL=prod.example.com" >> $GITHUB_ENV
          echo "GH_SECRET_DEPLOYMENT_KEY=SECRET_NAME_FOR_PROD" >> $GITHUB_ENV

      # environment-independent steps
      ...

      # Use environment variable defined above in deploy to environment
      - name: Run deployment action
        uses: deploy-with@1
        with:
          target: ${{ env.DEPLOYMENT_URL }}
          deployment-key: ${{ secrets[env.GH_SECRET_DEPLOYMENT_KEY] }}
```
