### DISCUSSION TITLE
Cannot use continue-on-error in a job that uses a reusabale workflow

### DISCUSSION THREAD

**Discussion by ThishaniLucas** [community/community#77915] [Actions]
### Select Topic Area

Question

### Body

I have a job in a workflow that uses a matrix and a reusable workflow. The workflow runs fine. But I wanted to configure continue-on-error for the job so that if one of the matrix jobs fails, the rest will continue. But seems I cannot add this property to the job. I get the error "Property continue-on-error is not allowed". Following is my job.

```
release:
    needs: [xyz]
    if: ${{ needs.xyz.outputs.abc != '[]' }}
    strategy:
      matrix:
        path: ${{ fromJSON(needs.xyz.outputs.abc) }}
    uses: ./.github/workflows/build-executor.yml
    secrets: inherit
    with:
      env: matrix.path
```

**Comment by ghost** [comment]
In [Handling failures](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures) described two configuration options
> `jobs.<job_id>.strategy.fail-fast` applies to the entire matrix
> `jobs.<job_id>.continue-on-error` applies to a single job

Did you test `fail-fast: false` for you matrix?
```yaml
release:
    needs: [xyz]
    if: ${{ needs.xyz.outputs.abc != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(needs.xyz.outputs.abc) }}
```

**Reply by thebuck25** [reply]
I have the same issue - failing fast only applies to the current job, it does not seem apply to chained jobs of reusable workflows.  For instance if I have the following jobs: deploy-dev, deploy-stage, deploy-prod.  Each job calls a "deploy" reusable workflow with a different set of env vars pertaining to the environment.  Each job specifies the prior job in the needs directive.  You then use a matrix to deploy an array of lambdas thru the pipeline.  In this case, fail fast set to false will allow all lambda deployment jobs instantiated by the matrix to continue to run even if the first one fails. But only for the job in which the failure occurs.  The pipeline ends there as the next job sees that there was a failure in the previous due to the "needs" directive.

For example - I have 3 lambdas I want to deploy because there were changes to these in my last merge to main.  The matrix creates 3 parallel "deploy-dev" jobs - one of which fails.  The other two will continue to deploy to dev.  However! The pipeline cannot continue to deploy to stage & prod for the two jobs which passed the dev deployment, because continue-on-error isn't allowed at the top level of a reusable workflow caller since it requires runs-on.  Adding continue-on-error to the reusable workflow has no effect on the callers.

**Reply by ghost** [reply]
1. `continue-on-error: true` - workflow will go to next job/step even if error occur in the current one
2. `strategy.fail-fast: false` - martix initiated jobs will not be cancelled even if one of them will fail
3. `if: success() || failure()` - job(step) will be executed even if required job (`needs:[]`) will fail

I case when we call a reusable workflow in each matrix element it is an independent entity from matrix fail strategy and should be controlled at its own job/step levels.

[Status check functions](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions)
```yaml
jobs:
  job1:
    continue-on-error: true

  job2:
    needs: job1
    if: success() || failure()
    continue-on-error: true

  lambdas:
    needs: [job1, job2]
    if: success() || failure()
    strategy:
      fail-fast: false
      matrix:
        env: [dev, stage, prod]
```

**Reply by thebuck25** [reply]
Except that this will not work and throws an error because job1 as a reusable workflow has no runs-on directive which is mandatory for continue-on-error. 

Real life example: yaml snippet of a reusable workflow caller which needs to continue on error:
```
  Deploy_Dev:
    name: '🔵 🚀 Deploy Dev Infra 🚀 🔵'
    needs: [getMatrices, Plan_Dev]
    if: >-
      needs.getMatrices.outputs.any_changes == 'true' && ...
    uses: blah/deploy.yml@main
    strategy: 
      fail-fast: false
      matrix: ${{ fromJSON(needs.getMatrices.outputs.path_matrix) }}
```
Now adding the continue-on-error at the job level:

<img width="620" alt="image" src="https://github.com/community/community/assets/106441113/862574ad-6cdf-48d6-8658-787e4129b575">
<br><br>
Ignoring the IDE error and committing malformed yaml results in a pipeline error.

I've worked around this by detecting the failure on the reusable workflow as a step and exiting with success regardless:

```
      - name: do something
        id: plan
        run: some-script --args 1 2 3
        continue-on-error: true

      - name: check status
        if: steps.plan.outcome == 'failure'
        run: exit 0
```

This workaround is ... less than ideal

**Reply by ghost** [reply]
> Now adding the continue-on-error at the job level:

Not matrix job, but reusable workflow level (inside it) like you did it for the steps.

Not sure if I got your issue. Did a test to check a simple case
<details>
<summary>example</summary>

`caller.yml`
```yaml
name: Caller

on:
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: exit 1

  prod:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  deploy:
    needs: [dev, prod]
    strategy:
      fail-fast: false
      matrix:
        env: [dev, prod]
    uses: ./.github/workflows/reusable.yaml
    with:
      env: ${{ matrix.env }}
```
`reusable.yaml`
```yaml
name: Reusable

on:
  workflow_call:
    inputs:
      env:
        type: string

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Show environment
        run: echo "Environment is ${{ inputs.env }}"

      - name: Exit
        run: |
          [[ "${{ inputs.env }}" == "dev" ]] && exit 1 || exit 0

      - name: Status
        if: success() || failure()
        run: echo "Test passed"
```
</details>

1. dev
2. prod
3. deploy

Result is the following
1. dev `failed` - execution continue
2. prod `success` - execution continue
3. deploy is called for `dev` and `prod` environments and it require both previous jobs - dev and prod
4. dev reusable `failed` - execution continue and last step passed
5. prod reusable `success` - execution continue and last step passed
6. final workflow status is `success` - green

<img width="1133" alt="Screenshot 2024-02-08 at 23 01 06" src="https://github.com/community/community/assets/88528265/e5882295-f6bb-4345-908b-50be33bc9a72">

**Reply by thebuck25** [reply]
Right - so in my situation you would have 3 apps being deployed lets say 
`matrix: fromJSON({ "apps": [ "name": "funca", "name":"funcb", "name":"funcc" ] })`

And two reusable workflows instead of one..

Code would look like this maybe (pls excuse lack of formatting & err checking - I'm just typing this from memory):

```
name: Caller

on:
  workflow_dispatch:

jobs:
  planmtx:
    id: plan
    runs-on: ubuntu-latest
    run: |
      echo "matrix_json: { \"apps\": [ \"name\": \"funca\", \"name\":\"funcb\", \"name\":\"funcc\" ] }" >>> "$GITHUB_OUTPUT"

  build:
   needs: [plan]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.plan.outputs.matrix_json) }}
    uses: ./.github/workflows/build.yaml
    with:
      name: ${{ matrix.apps.name }}

  deploy:
    needs: [plan,build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.plan.outputs.matrix_json) }}
    uses: ./.github/workflows/deploy.yaml
    with:
       name: ${{ matrix.apps.name }}
```

Ok so in this scenario lets say `funca` is successfully built, but `funcb` and `funcc` fail.  The pipeline stops and the execution of `deploy` for the matrix is not performed as the `continue-on-error`directive in `build.yml` has no effect on a single matrix array element.  Overall it would seem that because 2 of the 3 array elements failed with exit 1, `needs: build` is causing the pipeline to stop before deployment for all matrix elements.

Therefore what I've done instead is catch the error in `build` with a comment and exit 0 explicitly on the failed step.  Since no deployment artifact is built, moving to the `deploy` job works for `funca` but not for `funcb` or `funcc` since those 2 have no artifact to deploy.  This works, but again, it's not ideal.

**Reply by ghost** [reply]
Hopefully, these workflows reflect in general your configuration

Even, if `build (func-b)` and  `build (func-c)` failed, these jobs marked as passed because we use `job.build.continue-on-error: true` inside `reusable-build.yml` workflow at job level and entire workflow go further and execute `deploy` where same things is happening.

The latest step in reuable workflows is commented and provided just as an example how we can execute it in case of need - condition `if: success() || failure()` is required.

<img width="1476" alt="Screenshot 2024-02-09 at 09 45 56" src="https://github.com/community/community/assets/88528265/25f3c816-c88e-4520-a4c4-de3495de2e4f">

<details>
<summary>example</summary>

`caller.yml`
```yaml
name: Caller

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:
      - id: setup
        uses: druzsan/setup-matrix@v2
        with:
          matrix: |
            app:
              - func-a
              - func-b
              - func-c

  build:
    needs: [plan]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.plan.outputs.matrix) }}
    uses: ./.github/workflows/reusable-build.yml
    with:
      app: ${{ matrix.app }}

  deploy:
    needs: [plan, build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.plan.outputs.matrix) }}
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      app: ${{ matrix.app }}
```

`reusable-build.yml`
```yaml
name: Reusable - Build

on:
  workflow_call:
    inputs:
      app:
        type: string

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Show app
        run: echo "App is ${{ inputs.func }}"

      - name: Exit
        run: |
          [[ "${{ inputs.app }}" != "func-a" ]] && exit 1 || exit 0

      # - name: Status
      #   if: success() || failure()
      #   run: echo "Test passed"
```

`reusable-deploy.yml`
```yaml
name: Reusable - Deploy

on:
  workflow_call:
    inputs:
      app:
        type: string

jobs:
  deploy:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Show app
        run: echo "App is ${{ inputs.func }}"

      - name: Exit
        run: |
          [[ "${{ inputs.app }}" != "func-a" ]] && exit 1 || exit 0

      # - name: Status
      #   if: success() || failure()
      #   run: echo "Test passed"
```
</details>

**Comment by thebuck25** [comment]
I’ll try modifying my if statements further.

From: Air ***@***.***>
Date: Friday, February 9, 2024 at 12:48 AM
To: community/community ***@***.***>
Cc: Chris Lohl ***@***.***>, Comment ***@***.***>
Subject: Re: [community/community] Cannot use continue-on-error in a job that uses a reusabale workflow (Discussion #77915)

Hopefully, these workflows reflect in general your configuration

Even, if build (func-b) and build (func-c) failed, these jobs marked as passed because we use job.build.continue-on-error: true inside reusable-build.yml workflow at job level and entire workflow go further and execute deploy where same things is happening.

The latest step in reuable workflows is commented and provided just as an example how we can execute it in case of need - condition if: success() || failure() is required.
Screenshot.2024-02-09.at.09.45.56.png (view on web)<https://github.com/community/community/assets/88528265/25f3c816-c88e-4520-a4c4-de3495de2e4f> example

caller.yml

name: Caller



on:

  workflow_dispatch:



jobs:

  plan:

    runs-on: ubuntu-latest

    outputs:

      matrix: ${{ steps.setup.outputs.matrix }}

    steps:

      - id: setup

        uses: ***@***.***/use-python-dockerfile

        with:

          matrix: |

            app:

              - func-a

              - func-b

              - func-c



  build:

    needs: [plan]

    strategy:

      fail-fast: false

      matrix: ${{ fromJson(needs.plan.outputs.matrix) }}

    uses: ./.github/workflows/reusable-build.yml

    with:

      app: ${{ matrix.app }}



  deploy:

    needs: [plan, build]

    strategy:

      fail-fast: false

      matrix: ${{ fromJson(needs.plan.outputs.matrix) }}

    uses: ./.github/workflows/reusable-deploy.yml

    with:

      app: ${{ matrix.app }}

reusable-build.yml

name: Reusable - Build



on:

  workflow_call:

    inputs:

      app:

        type: string



jobs:

  build:

    continue-on-error: true

    runs-on: ubuntu-latest

    steps:

      - name: Show app

        run: echo "App is ${{ inputs.func }}"



      - name: Exit

        run: |

          [[ "${{ inputs.app }}" != "func-a" ]] && exit 1 || exit 0



      # - name: Status

      #   if: success() || failure()

      #   run: echo "Test passed"

reusable-deploy.yml

name: Reusable - Deploy



on:

  workflow_call:

    inputs:

      app:

        type: string



jobs:

  deploy:

    continue-on-error: true

    runs-on: ubuntu-latest

    steps:

      - name: Show app

        run: echo "App is ${{ inputs.func }}"



      - name: Exit

        run: |

          [[ "${{ inputs.app }}" != "func-a" ]] && exit 1 || exit 0



      # - name: Status

      #   if: success() || failure()

      #   run: echo "Test passed"

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by duaneking** [comment]
This really needs an easy fix

**Reply by ghost** [reply]
Do you have any special case, it looks that we have all the options to drive the flow?

**Reply by duaneking** [reply]
I have multiple jobs that are peers of each other that do builds of a codebase with hundreds of millions of lines of code, for multiple different platforms.

The graph of dependencies is complex;  None of the platforms strictly depend on each other because we want to make the build as asynchronous as possible. We also have to take into account that a platform might fail and that could be okay as long as other tasks work successfully.

The issue here is that I need to cancel peer jobs on failure; I also need an optional way to fail the entire pipeline after optionally waiting for the metrics job to finish.

**Reply by ghost** [reply]
That topic is about a specific use case and it is solvable - we can continue on errors with reusable workflows.

Probably your case is more complex and have a lot of chains.

One of the issue which might be related - [Command to early-exit the job and set check conclusion #662](https://github.com/actions/runner/issues/662).

**Comment by edwardpeek-crown-public** [comment]
Another minimal example of this deficiency we came across is:
```yaml
name: Parent Workflow

on:
  workflow_dispatch:

jobs:
  call-child:
    uses: ./.github/workflows/child.yml
    # This is currently unsupported
    # continue-on-error: true

  on-success:
    needs: call-child
    if: ${{ needs.call-child.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Do something in response to success"

  on-failure:
    needs: call-child
    # `!cancelled()` needed for this to run regardless of earlier failure
    if: ${{ !cancelled() && needs.call-child.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Do something in response to failure"
```

The workaround with `!cancelled()` is non-ideal as the workflow is still considered "failed" triggering email notifications etc. and making it harder to notice "true" workflow errors.

While it is technically possible to refactor the child job to use inputs & outputs as a side channel for error reporting, that would be significantly more complicated that just being able to set this flag like the docs indicate should be possible.

**Comment by edgao** [comment]
Another example of why this would be useful, is when the child workflow belongs to a concurrency group, and we want the parent workflow to be marked successful if the child was preempted. For example:
```yaml
name: Build+Deploy
on:
  push: <snip>
jobs:
  build: <snip>
  deploy:
    needs: build
    # this workflow has `concurrency.group` set to some constant string (we only want one deploy in-flight at a time,
    # and we're OK with skipping `deploy` if multiple commits happen in rapid succession)
    # If another workflow preempts our `deploy` call,
    # we want the overall build+deploy workflow to be marked as successful.
    uses: ./.github/workflows/deploy.yml
    # currently unsupported option
    continue-on-error: true
  # fail the workflow if the deploy failed, since we had continue-on-error
  check-deploy:
    needs: deploy
    steps:
      - name: Check deploy result
        run: |
          if test ${{ needs.deploy.result }} = 'failed'; then
            echo 'Deploy was unsuccessful'
            exit 1
          fi
```

(obviously, it would be even better if we had an option like `preemptable`, i.e. continue-on-error but don't propagate cancellation to the parent workflow. But in the absence of such, getting `continue-on-error` would be a reasonable workaround.)

**Comment by rcmorano** [comment]
I have a very simple use case I cannot solve because `continue-on-error` is not supported in reusable workflows, which is, making the vuln scan for some folders "optional" (ok to fail):

```
jobs:
  depcheck:
    permissions:
      actions: read
      security-events: write
      contents: read
    needs: set-gitignore-artifact
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.2"
    with:
      download-artifact: example-gitignore-artifact
      scan-args: |-
        --recursive
        ./

  depcheck-services:
    continue-on-error: true
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.2"
    with:
      scan-args: |-
        --recursive
        ./examples
```
