### DISCUSSION TITLE
Does an existing token in .npmrc be used in the github actions too ?

### DISCUSSION THREAD

**Discussion by SarathSantoshDamaraju** [community/community#77937] [Actions]
### Select Topic Area

Question

### Body

I have a private github package (@org/PKG-1) that loads another github packages (@org/PKG-2)
So we have created a token with READ scope and added it in the `.npmrc` on the (@org/PKG-1).

```bash
//.npmrc 
@org:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=<NPM_AUTH_TOKEN>
```
Now when we are trying to deploy this package (@org/PKG-1) i see an error saying 
```bash
- Permission permission_denied: The token provided does not match expected scopes.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

Few points
1. I have set permissions on the actions yml file like below
```yml
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      RUNNING_ON_GITHUB_ACTION: true
```
2. And also when i try to publish the (@org/PKG-1) without the `NPM_AUTH_TOKEN` it gets PUBLISHED, but i need that to install other private packages. 

Does github actions use the `NPM_AUTH_TOKEN` in the `.npmrc` when its available ?

How do i solve this ?

- TIA
