### DISCUSSION TITLE
Github Workflow Required check never resolving - "Expected - Waiting for status to be reported"

### DISCUSSION THREAD

**Discussion by AmyJoT** [community/community#77942] [Actions]
### Select Topic Area

Bug

### Body

When opening PRs we are sometimes seeing this situation occur:
1) PR is raised, kicking off the workflow
2) A second workflow is kicked off, and initial workflow is immediately cancelled due to concurrency rules:
`Canceling since a higher priority waiting request for 'Flight Checks-refs/pull/142836/merge' exists`
3) Second workflow completes, but status check stays like this:

<img width="759" alt="Screenshot 2023-12-05 at 14 00 06" src="https://github.com/community/community/assets/36444263/b0c0a0f2-2e76-47df-8ed9-1dfab76d827e">

Triggers and concurrency are set up as follows:

```
# Will run on the following PR events:
on:
  pull_request:
    types:
    - opened
    - edited
    - reopened
    - synchronize
    - labeled
    - unlabeled

# Cancel other in progress runs of this workflow 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

Any ideas why this is happening? It feels like some sort of race condition is being hit.

Note: this doesn't always happen, and this occured on an automated Renovate PR.

**Comment by sayhiben** [comment]
My organization is also encountering this issue. We made no recent relevant changes, and it seems to manifest across required checks without an obvious pattern. At a guess, there must be some issue with the check status webhooks not being received on GitHub's side.

**Comment by sayhiben** [comment]
We have at least one case reoccurring this evening. I'm unsure if this is resolved.

**Comment by AmyJoT** [comment]
Still occuring multiple times over here, so not resolved

**Comment by AmyJoT** [comment]
We're having more engineers reach out to us about seeing this issue appear on their PRs.

**Comment by jessebrennan** [comment]
Also seeing this a lot more recently. It seems to occur when pushing to the same branch multiple times in quick succession. I suspect setting `cancel-in-progress: false` may be a sufficient work around if you can afford to do so.

**Comment by lrotschy** [comment]
Hi folks, thanks for reporting this. Are you still seeing this issue? And could you clarify if it is happening with required status checks or with ruleset workflows, or both? Are you seeing it on other checks that are not required?

**Reply by AmyJoT** [reply]
This is still happening as far as I am aware yes, though I haven't had as many reports this week (though it is christmas, so maybe less folk to encounter it). It is happening in a workflow which runs on PRs which is also a required check (apologies if this is what a ruleset workflow is). I'm pretty sure there is something race-condition wise going on with the concurrency ruleset we need to use for this workflow.

The following is the main idea of the setup in which we are seeing this issue:

```
name: Flight Checks

# Will run on the following PR events:
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
      - unlabeled

# Cancel other in progress runs of this workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Access scopes for the GITHUB_TOKEN created as part of the workflow
permissions:
  contents: read
  pull-requests: write
  repository-projects: read

jobs:
  flight-checks:
... etc
```

**Reply by lrotschy** [reply]
I think it would be worth opening a customer support issue for this, especially since others are seeing it as well. https://support.github.com/features/actions

**Comment by dcacenabes** [comment]
Hi @lrotschy we are also seeing the issue. I reported it already 3 weeks ago:
https://support.github.com/ticket/enterprise/36/2492908
But still no solution from Github.

I even created a sample project that demonstrates the issue very easily:
https://github.com/dcacenabes/demonstrate-event-trigger-issues/

It basically contains a script that creates N (defined via parameter) pull requests in a loop. Eventually some of those hit the issue (e.g.
[1](https://github.com/dcacenabes/demonstrate-event-trigger-issues/pull/47) and [2](https://github.com/dcacenabes/demonstrate-event-trigger-issues/pull/45) )

It does not happen for every PR, but it is definitely easy to reproduce.

**Reply by lrotschy** [reply]
Not sure what's going on with the ticket. I'll check with support and see if we can track it down. My apologies for the delay.

**Reply by dcacenabes** [reply]
Thanks @lrotschy !
Please let me know if you need further info regarding steps to reproduce.
This is a very annoying bug because the current workaround is costing us money (triggering new workflow runs means more minutes for runners)

**Comment by lalten** [comment]
Hi, we're hitting this multiple times per day and it's becoming very annoying. Is there any solution/workaround?

**Comment by broksonic21** [comment]
We also have seen this a ton starting 2 days ago - anyone from Github able to fill us in if there's a solution? We use the exact same action setup as the Original Poster.

**Reply by dcacenabes** [reply]
The reply from Github was that this is expected behavior. This is from our ticket with support:

>Our engineering team has shared the root cause of this issue. In essence, status checks will look up the status of the latest run and as cancel-in-progress is true, the latest runs will sometimes be cancelled and as a result they will not be reported. When using concurrency, we do not guarantee the order in which the runs are cancelled as outlined in the note in our documentation [here](https://docs.github.com/en/actions/using-jobs/using-concurrency#using-concurrency-in-different-scenarios). The current workaround would be to set cancel-in-progress to false.

**Reply by broksonic21** [reply]
That makes cancel-in-progress useless, to be honest and would cost us a large amount extra per month in $ since significant # of extra runs would run. 

That's _very_ unfortunate. @lrotschy please put us down as well as _really_ wanting a fix for this.

**Comment by takirala** [comment]
Any update on this - in terms of fix from GH or any workarounds someone has tried ?

**Comment by DariuszKalita** [comment]
This issue stil happens, actually I haven't completed any PR when this check is set. I'm talking about a new, trivial project with trivial PR, configured with Xcode Cloud. Xcode Cloud builds just fine, however: _Xcode Cloud Expected — Waiting for status to be reported_ never resolves.

**Comment by Devinwong** [comment]
Anu update on this? Thanks.

**Comment by rido-min** [comment]
Same here, I see the Azure Pipeline as completed, but the check is still waiting for status to be reported.

**Comment by shivang-certify** [comment]
Facing this regularly as well. Can someone please escalate and get this fixed?

**Comment by Lyngsoe** [comment]
Same problem here. Would love some input from GitHub on how to resolve this 🙏

**Comment by jonesp1** [comment]
We are also seeing this problem please do something about it Github?

**Comment by h3rmanj** [comment]
Ran into this as well. Seems that PR Status checks only reports from specific pull request types. I don't know exactly which, but `labeled` is one of them. That combined with a concurrency group will make the labeled workflow run cancel the run that a status check will pick up on.

Our workaround was to make a separate concurrency group for the `labeled` event:

```yaml
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

concurrency:
  # PR Labeled events only cancels each other to not interfere with status checks
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.action == 'labeled' }}
  cancel-in-progress: true
```
