### DISCUSSION TITLE
xcodebuild when using Xcode 15 ignores -destination

### DISCUSSION THREAD

**Discussion by simonmcl** [community/community#78049] [Actions]
### Select Topic Area

Bug

### Body

I've recently upgraded my local machine to Sonoma and Xcode 15. I made some minor changes to a swift package based on warnings from Xcode 15 and wanted to update my github action to use Xcode 15 too. My Swift package is iOS only (due to a dependency), therefore it can't be built with Swift build, it must be built with xcodebuild forcing the destination to be iOS only. Something like this:

```
xcodebuild test -scheme xxxxx -destination "platform=iphonesimulator,OS=16.4,name=iPhone 14 Pro"
```

Otherwise it will attempt to build it for macos as well, which will cause the build to fail

This works fine on my machine for Xcode 13, 14 and 15. It works fine on github actions using Xcode 13 and 14. But when using 15, it seems to ignore this and trys to build for macos. This means i'm unable to make use of Xcode 15

Xcode 14 run using:
```
steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app/Contents/Developer'

.....

- name: Test
        run: xcodebuild test -scheme KukaiCoreSwift -destination "platform=iphonesimulator,OS=16.4,name=iPhone 14 Pro" -enableCodeCoverage YES -resultBundlePath "$PWD/xcode-$NOW.xcresult"
```

https://github.com/kukai-wallet/kukai-core-swift/actions/runs/7117775835

Passes without issue

Xcode 15 run using:

```
steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'

.....

- name: Test
        run: xcodebuild test -scheme KukaiCoreSwift -destination "platform=iphonesimulator,OS=17.0,name=iPhone 15 Pro" -enableCodeCoverage YES -resultBundlePath "$PWD/xcode-$NOW.xcresult"
```

https://github.com/kukai-wallet/kukai-core-swift/actions/runs/7117800234

Fails due to an attempt to build on macos. Same command runs fine for me locally. ANy help would be appreciated
