### DISCUSSION TITLE
Dependabot not applying all proposed updates

### DISCUSSION THREAD

**Discussion by jdholbrook81** [community/community#78149] [Pull Requests]
### Select Topic Area

Question

### Body

When I reviewed two dependabot PRs this month they both indicated they were making multiple updates, but the commit only showed a single update in each one. Is this expected, a bug, misconfiguration? Example below. I resolved this by discarding the dependabot PR and created a PR manually to apply the changes proposed.

Dependabot.yml snippet
```
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      providers:
        patterns:
          - "*"
```

What it said it was doing:
![image](https://github.com/community/community/assets/7423387/8eca5bcd-a653-483c-a50d-d22f34504dae)

The only commit in the PR:
![image](https://github.com/community/community/assets/7423387/64faa731-664b-4fc2-b253-12666467a0f0)
