### DISCUSSION TITLE
Location of documentation describing the `type: environment`

### DISCUSSION THREAD

**Discussion by AJamesPhillips** [community/community#78181] [Actions] [answered]
### Select Topic Area

Question

### Body

This changelog page: https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/ and this documentation page: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-onworkflow_dispatchinputs both have examples of using: `type: environment` but I can't find out what that actually means in practice?  If you have the following `run_tests.yaml` workflow:

```
on:
  workflow_dispatch:
    inputs:
      some_env:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  run_tests:
    ...
```

Which of the following values to `some_env` are allowed?

```
jobs:
  run_staging_tests:
    steps:
      - name: Run tests against staging
        uses: my-org/my-repo/.github/workflows/run_tests.yaml@main
        with:
          some_env: staging           # valid?
          # some_env: production  # valid?
          # some_env: prod            # valid?
          # some_env: "staging"    # valid?
          # some_env: 123              # valid?
```

I would like to find documentation describing what the job can be invoked with / what validation rules are applied?  And what happens with disallowed values / what error is raised?
