### DISCUSSION TITLE
Auto Assign reviewers

### DISCUSSION THREAD

**Discussion by ayushkatiyar01** [community/community#78260] [Actions]
### Select Topic Area

Question

### Body

Can we auto-assign a set of people from different teams for a raised PR in a repo? Is there any method for this like gh actions or some repo configuration ?

**Comment by fury-05** [comment]
GitHub do not have a built-in feature to automatically assign specific individuals from different teams to a pull request.
 
But you can achieve this using **GitHub Actions** in combination with the GitHub API and custom scripts.

**For Example script like this :** 

Code in yml file

```
name: Auto-Assign Reviewers
on:
  pull_request:
    types:
      - opened

```
