### DISCUSSION TITLE
Documentation for 3rd party/custom actions vs Github actions referenced in UI

### DISCUSSION THREAD

**Discussion by AJamesPhillips** [community/community#78273] [Actions]
### Select Topic Area

Question

### Body

I'm trying to understand what parameters and options I can use in a custom action.  For example I have the following files:

```
.github/
|- actions/
|  |- post_message/
|     |- action.yaml
|
|- workflows/
   |- runtests.yaml
```

Where runtests.yaml has an `input` like:

```
on:
  workflow_call:
    inputs:
      stage_env:
        description: 'Environment to test against'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
```

I wanted to use a similar `type: choice` [as documented for workflows](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-onworkflow_dispatchinputs) in the custom "post_message" action however this does not seem to be supported.  **Does anyone know where the documentation for these actions is located?**

Whenever I search for it I'm left confused as I seem to only find the mentions of GitHub actions that are referenced from the UI, and this is not what I want e.g.:
<img width="511" alt="Cursor" src="https://github.com/community/community/assets/526509/3479039b-1133-4ad0-b889-9eaf08844a49">
