### DISCUSSION TITLE
Passing string with line breaks as action input

### DISCUSSION THREAD

**Discussion by AtaTaheri** [community/community#78284] [Actions] [answered]
### Select Topic Area

How to pass string with line breaks to an action without breaking value?

### Body

I'm trying to send a slack notification with some formatting from my workflows. Since the header of the notification is shared between different notifications, I created an action with an input just for the message like this: 

workflow file: 
```
  start-notif:
    name: Send start notif
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send to webhook
        uses: ./.github/actions/slack-notification
        with:
          message: "${{  github.ref_name }}  \n\nBuild started."
```

action file: 

```
runs:
  using: composite
  steps:
    - name: Send to webhook
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_URL: REDACTED
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "blocks": [
                // a header here
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.message }}"
                    }
                }
            ]
          }

```

Doing so, the passed `\n` chars are interpreted as actual line breaks & the payload becomes invalid. (have tried without them and the problem is indeed the line break chars)
How to get around this issue?

Also have tried a single line JSON like: 
`
        payload: '{"blocks":[ HEADER_HERE {"type":"section","text":{"type":"mrkdwn","text":"${{ inputs.message }}"}}]}'
`

Same issue again.

**Comment by ChristopherHX** [comment, marked as answer]
You can tell actions to insert an json encoded value instead of plain text
```yaml
runs:
  using: composite
  steps:
    - name: Send to webhook
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_URL: REDACTED
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "blocks": [
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": ${{ tojson(inputs.message) }}
                    }
                }
            ]
          }
```
As bonus it escapes other quotes and more.

Note: You won't get `\r\n` sequences this way and only see `\n`

I'm not shure if you target system supports json with comments so I removed `// a header here`.
