### DISCUSSION TITLE
Allow GitHub Actions matrix exclusions to take an array

### DISCUSSION THREAD

**Discussion by alexedwardjones** [community/community#7835] [Actions]
I have a job in one of my workflows that includes quite a large matrix with a lot of different combinations. I have an ever increasing number of exclude fields but I want to keep everything consolidated in one job.

The exclude list is getting quite long and doesn't seem to support providing an array which would shorten it significantly. Is this possible?

So...
```
      matrix:
        project: [projectA, projectB, projectC, projectD]
        region: [uk, france, germany]
        exclude:
          - region: uk
            project: projectA
          - region: uk
            project: projectB
          - region: france
            project: projectD
          - region: germany
            project: projectD
```
...would become...
```
      matrix:
        project: [projectA, projectB, projectC, projectD]
        region: [uk, france, germany]
        exclude:
          - region: uk
            project: [projectA, projectB]
          - region: [france, germany]
            project: projectD
```

**Comment by caspiano** [comment]
Ditto for `include`

**Comment by ethomson** [comment]
Hi @alexedwardjones - unfortunately, no, `include` and `exclude` do not support specifying an array in this manner, where it would get expanded into its component pieces.  This particular syntax would not be possible, since `include` and `exclude` do support specifying _an array_ however, because you can use dictionaries and arrays in matrix definitions.

In other words - this is legal:

```yaml
strategy:
  matrix:
    a: [one, two]
    b:
    - ['1', '2']
    - ['3', '4']
```

which would produce a four element matrix ` { a=one, b=[1, 2] }`, `{ a=one, b=[3, 4] }`, `{ a = two, b=[1, 2] }`, `{ a = two, b=[3, 4] }`.  In the `{ a=one, b=[1, 2] }` case you can refer to `b`'s elements as `${{ matrix.b[0] }}` and `${{ matrix.b[1] }}`.

This is also legal:

```yaml
strategy:
  matrix:
    a: [one, two]
    b:
    - ['1', '2']
    - ['3', '4']
    exclude:
    - a: two
      b: ['3', '4']
```

Which will remove the `{ a=two, b=[3,4] }` matrix entry.

I mention this not to dismiss your problem, but because these more advanced matrix scenarios might also be able to solve your problem.  But if not, in the new year, I'd like to make complex workflows easier to specify and will keep your workflows in mind.

Thanks much for the feedback.

**Reply by chrispat** [reply]
Another option would be a dynamic matrix using job outputs.  I thought we had an example in the docs but I can't find it right now, however, here is a helpful blog post https://michaelheap.com/dynamic-matrix-generation-github-actions/.

**Reply by xor-freenet** [reply]
I understand that it would be difficult to make the existing GitHub Actions implementation work like this.  
However the implementation should follow the needs of the user, the user should not be forced to obey the needs of the implementation.

A workaround would be possible by e.g. using `{}` instead of `[]` or any different characters as replacement for the brackets, or requiring an escape character, e.g. `\[`. And you could probably come up with an infinite further amount of workarounds.

Even if you don't, heck, just require people to write "ACTIONS_PLEASE_PARSE_THIS_AS_ARRAY" before it, that's certainly unused and as long as it works I'm fine :)

I support this request because the lack of this is annoying in the following usecase which might be somewhat common:

```yml
matrix:
  os: [ubuntu-latest, windows-latest, ...]
  java-version: [..., 15, 16, 17, ...]

  exclude:
    - os: windows-latest
      java-version: [16, 17, ...] # Not available yet / broken
 ```
