### DISCUSSION TITLE
Inquiry Regarding Github Actions Permissions for Pull Request

### DISCUSSION THREAD

**Discussion by ono-max** [community/community#78355] [Actions]
### Select Topic Area

Question

### Body

Hello,

I am seeking clarification on the permissions associated with `pull_request` events in Github Actions, specifically regarding write permissions. The documentation states:

> You can use the permissions key to add and remove read permissions for forked repositories, but typically you can't grant write access.

[Link to documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token)

However another section of the documentation suggests otherwise:

> By default, GitHub Actions workflows triggered by Dependabot get a GITHUB_TOKEN with read-only permissions. You can use the permissions key in your workflow to increase the access for the token.

[Link to documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions)

Based on this information and [this blog](https://github.blog/changelog/2021-10-06-github-actions-workflows-triggered-by-dependabot-prs-will-respect-permissions-key-in-workflows/), I inferred that only Dependabot has special privileges to receive write permission when creating a pull request from a forked repository. To test this hypothesis, I conducted the following experiment:

First, I created a YAML file that enables auto-merging pull requests:

```
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Node.js CI workflow...
    ...

  dependabot:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run : |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
``` 

Then, I created the following pull requests:

1. [Checked whether a forked pull request by a personal account is merged or not](https://github.com/ono-test-security/test-auto-merge/pull/1) -> **not merged**
2. [Checked whether a forked pull request by Dependabot is merged or not ](https://github.com/ono-test-security/test-auto-merge/pull/4)-> **merged**
3. [Checked whether a forked pull request by Renovate is merged or not](https://github.com/ono-test-security/test-auto-merge-v2/pull/9) -> **merged**

The result for case 3 is confusing to me because I assumed that only pull requests triggered by Dependabot are treated as special. Despite being from forked repository, the pull request by Renovate was granted write permission.

Could you provide insights into this behavior? Thank you.
