### DISCUSSION TITLE
action  "jfrog/setup-jfrog-cli" - stopped working

### DISCUSSION THREAD

**Discussion by veljkosbbb** [community/community#78483] [Actions]
### Select Topic Area

Question

### Body

Hello,

I have defined GH Action which downloads packages from JFrog Artifactory repository.
I have been using access tokens but also I've tried with passwords and API key.

My action definition is the following:
```
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: 'https://artifactory.domain.dev/'
        JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        JFROG_CLI_LOG_LEVEL: DEBUG
    - name: Tests connection to artifactory
      run: |
        Test-NetConnection artifactory.domain.dev -Port 443
    - name: Test download
      run: |
        jf rt dl project-generic-snapshot-local/components/POC/project.zip
```

I have connectivity because telnet connection from hosted runner (windows-latest) works.
Once the action is executed I am getting:
```
[Warn] The server response: 503 Service Unavailable
<html> 
  <head>
    <title>No Server Available</title>
  </head> 
  <body style="font-family:Arial,Helvetica,sans-serif;">
<h2> No server is available to process your request. </h2>
  </body> 
</html>
```

So telnet works.
This same code worked before.
My current user with the token has permissions to access that repo.
Further on, when I try login with same user on lap top with jfrog cli tool  - I can download the same package.
But the strangest thing is that I used this code previously with no errors, and then after I retried it after some time it throws the error above. 
I have tried also with re-generating token.

What might be wrong?
I run out of options... Thank you
