### DISCUSSION TITLE
Two Identical GitHub Action Workflow files, One is shown the other is not shown in the Actions tab. Why?

### DISCUSSION THREAD

**Discussion by ShahryarSaljoughi** [community/community#78628] [Actions]
### Select Topic Area

Question

### Body

I have a repository with two identical workflow files in the same repository, in the same path (`.github/workflows`), both in the same branch which is the default branch. One is shown in the Actions tab, whereas the other one is not. 
Triggers for both of them are the same. They have two triggers: `on push` and `on workflow_dispatch`.  
How can I solve the issue so that they are both shown in the Actions tab.  

### More context:
I had a base repo with 12 workflows, from which I forked a new repository. In the fork repository 11 of workflows are shown, one not. I created a new workflow  identical to the missing workflow, using the `New workflow` button in the Action tab. The new one is shown the missing workflow still is not shown.

Here is part of those identical workflow files:
```
name: update database prompts production

on: 
  push:
    branches: 
      - not_existing_branch
  workflow_dispatch:
    inputs:
        branch:
            description: 'Branch to release from'
            required: true
            default: 'main'
```
I've read all I could find on this issue, none of the answers helped so far.
