### DISCUSSION TITLE
dynamic runs-on label definition causes job being stuck in queue for ever

### DISCUSSION THREAD

**Discussion by Jensssen** [community/community#78674] [Actions] [answered]
### Select Topic Area

Bug

### Body

I have two self hosted runners, one with an extra "cpu" label and one with an extra "gpu" label. 
Some of my unit tests should be executed on the "cpu" runner and others on the "gpu" runner. 
I use the following yaml to run on on or the other runner, depending on a working-directory variable. 

```
jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ${{ (inputs.working-directory == 'folder1') && '[self-hosted, linux, x64, gpu]' || '[self-hosted, linux, x64, cpu]' }}
...
```
If I trigger the job, the github action is stuck. No job is picked up by any runner. They are stuck in queue for ever and I just get the following prompt (for one of my jobs as example): 

```
Requested labels: [self-hosted, linux, x64, gpu]
Job defined at: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Reusable workflow chain:
xxxxxxxxxxxxxxxxxxxx
-> xxxxxxxxxxxxxxxxxxxx
--> xxxxxxxxxxxxxxxxxxxx
Waiting for a runner to pick up this job...
```
If I use `runs-on: [self-hosted, linux, x64, gpu]` all unit tests are executed on the gpu machine. However, I can not hardcode this logic, would like to make the selection of labels dependent on my working-directory input variable. 

So it seems that the "dynamic" selection of labels does not work? Even though I see the correct set of labels in the prompt. However, none of my runners is picking up any jobs. The job is stuck in queue for ever.
