### DISCUSSION TITLE
Allow access to env vars in path filter

### DISCUSSION THREAD

**Discussion by hughesjs** [community/community#78711] [Actions]
### Select Topic Area

Question

### Body

Why can't I do this? 

```
env:
  TARGET_DIR: '2023/1-1-trebuchet'

on:
  pull_request:
    paths:
      - '${{ env.TARGET_DIR }}/**'
  workflow_dispatch:
```

**Comment by DylanDevelops** [comment]
GitHub Actions does not support using environment variables in the `paths` filter of the `on` keyword. The `paths` and `paths-ignore` keywords accept a pattern or an array of patterns, but these patterns do not support variable substitution.

This is a limitation of the event filter pattern described in the GitHub Actions documentation. The patterns are matched against the file paths in the commit, not against the environment variables or the outputs of previous steps.

If you need to run a workflow only when files in a specific directory are changed, you will need to hardcode the directory path in the `paths` filter like this:

```yml
on:
  pull_request:
    paths:
      - '2023/1-1-trebuchet/**'
  workflow_dispatch:
```

If the directory path changes frequently and you don't want to update the workflow file each time, you might need to use a different strategy, such as a script that checks the changed files and decides whether to continue the workflow.

**Comment by hughesjs** [comment]
Sorry, you misunderstand me, I was being rhetorical.
I *know* it's a limitation. My question is *why* is it a limitation.

**Reply by DylanDevelops** [reply]
It's because of security reasons. They want to ensure that any access to environmental variables is protected and secure.

**Reply by hughesjs** [reply]
What security implication is there from their parser reading an env var and throwing it in a path filter when they're determining whether or not to run an action?

**Reply by DylanDevelops** [reply]
I'm not sure sorry. This is just the way that this is.

**Reply by hughesjs** [reply]
"That is just the way that this is" isn't really a great response to a feature request...

**Reply by DylanDevelops** [reply]
I'm not a member of the GitHub staff. Unfortunately, I can't change things. I'm just telling you how it is right now.

**Comment by sh13y** [comment]
The YAML code you've provided seems to be a GitHub Actions workflow configuration file. If you're facing issues, it could be due to various reasons. Let's go through the code and address potential problems:

```
env:
  TARGET_DIR: '2023/1-1-trebuchet'

on:
  pull_request:
    paths:
      - '${{ env.TARGET_DIR }}/**'
  workflow_dispatch:
```

Here are some considerations:

1. **Syntax and indentation:** YAML is sensitive to indentation, so make sure the indentation is correct. In your provided code, it appears to be correct.

2. **Quoting in YAML:** The single quotes around the value of `TARGET_DIR` are fine if you want to maintain the exact string, but for path matching in `paths`, you may not need them. Try without quotes:

```
env:
  TARGET_DIR: 2023/1-1-trebuchet

```

3. **Double curly braces in quotes:** You've used single quotes around `${{ env.TARGET_DIR }}`, which may not be necessary. GitHub Actions doesn't require quotes in such cases. You can simplify it to:

```
on:
  pull_request:
    paths:
      - ${{ env.TARGET_DIR }}/**
  workflow_dispatch:
```

4. **Check if the path is correct:** Ensure that the path specified in `paths` is correct and matches the actual directory structure in your repository.

5. **Workflow dispatch:** Ensure that you're triggering the workflow dispatch correctly. You can manually trigger the workflow from the GitHub Actions page by clicking the "Run workflow" button.

If you are encountering a specific error or issue, please provide more details about the problem or any error messages you are seeing. This information will help in providing a more accurate and targeted solution.
