### DISCUSSION TITLE
How do I put all of my html, css, and javascript files inside of one `src` folder for better organization?

### DISCUSSION THREAD

**Discussion by DylanDevelops** [community/community#78723] [Other Feature Feedback, Questions, & Ideas] [answered]
### Select Topic Area

Question

### Body

I've been working on my website for over a year now, and recently, I realized how messy the root directory had become. I want to move all the src files into a `src' directory. When I tried, it didn't load those but only displayed my readme.

Is there a way to have all those files in a folder called `src`?

You can view the repository in question here: https://github.com/DylanDevelops/dylanravel.com

**Comment by seyLu** [comment, marked as answer]
#### Hi @DylanDevelops,

There is an npm package [`gh-pages`](https://www.npmjs.com/package/gh-pages#command-line-utility) that allows us to deploy to github pages programmatically.

After moving all your files under `src/` directory, install `gh-pages` then add to your `package.json`:

<table><tr>
<td width="300px">

```bash
npm i -D gh-pages
```

</td>
<td width="400px"> 

```diff
"scripts": {
+  "deploy": "gh-pages -d src",
``` 

</td>
</tr></table>

Run the deploy script:

```
npm run deploy
```
 
This will create a `gh-pages` branch in your repo and put the stuff in your `src/` directory to this branch. Then you'll have to configure in your repo settings to build and deploy from the `gh-pages` branch.

![image](https://github.com/community/community/assets/98249191/fe95d7ad-5529-401b-bdf5-e50215fe7c79)

By this point, things should work as expected (albeit manual) and you can ignore the next step(s). 

---

Butttttttttttt, there's always room for automation. We can leverage the power of GitHub actions to automate stuff. In `.github/workflows/deploy.yaml`:

```yaml
name: Build & Deploy
run-name: Deploying ${{ github.repository }}

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  pages: write

jobs:
  lint:
    name: Perform Build & Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ea8b747819ff6d82907eb4018229f1a75c174697 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@5ef044f9d09786428e6e895be6be17937becee3a # v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci --prefer-offline

      - name: Build & Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d src -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
