### DISCUSSION TITLE
GH Actions Array Support

### DISCUSSION THREAD

**Discussion by blairlong3** [community/community#7875] [Actions]
We recently ran into an issue where we had to create a work around in a GH workflow yaml file in order to populate an array. 

We have a job that sets up a `strategy` `matrix` called `apps` that should contain an array of strings. Each string is a directory. Each of these directories is packaged and deployed. We've gathered that because `apps` is in `strategy.matrix` that it must be an array even if it is just one string. We based this assumption off the examples in the docs here. https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-including-new-combinations

Sometimes the `apps` should just point to one directory that is supplied as an input for a manual run. There appeared to be no way to input an array or to put a string input into an array. It would be nice to have either option available. 

What we did as a work around is added an intermediate job that created a json string like this:
```
    format-input-app-json:
        runs-on: 
...
        outputs: 
            app-json: ${{ steps.get-json.outputs.app-json }}
        steps:
            - id: get-json
              run: |
                export appjson='{"app": ["${{github.event.inputs.app}}"] }'
                echo "::set-output name=app-json::$appjson"
```
 
Then in the deploy job when setting `strategy.matrix.apps`, we use `fromJSON(needs.format-input-app-json.outputs.app-json)['app']` if `github.event.inputs.app` is provided. This resolved our issue, but would be simpler if there were something like:
`toArray('string1','string2',...)`.

**Comment by ethomson** [comment]
Thanks for the feedback - at the moment, the `fromJson()` approach that you've taken is indeed the one that I'd recommend.  I'm interested in doing some work in the new year to make advanced workflows like this easier to build, and I'll keep this in mind.

**Reply by blairlong3** [reply]
Thank you for taking a look at this post, and I look forward to your work in the new year!

**Comment by jameslawson** [comment]
Hello! I'm also interested in array of string support for  GitHub actions

My use case: Reusable action for deploying. 

I have a custom GitHub action that runs an input deploy script (by calling some command). As the script is running, my custom action monitors the script's progress and updates comments in the pull request (adding comments like "Deployment in progress" and "Deployment Finished"). The action additionally provides various DX things like: showing the deploy time in PR comments, showing the deployed website URL in PR comments, and updating [deployments](https://docs.github.com/en/rest/deployments?apiVersion=2022-11-28). It's similar to what [Netlify](https://answers.netlify.com/t/cannot-find-the-deploy-preview-button-of-a-pull-request-on-github/48771/11) and [vercel](https://vercel.com/docs/workflow-collaboration/comments/integrations) do.

To make it reusable across my codebase, it's designed as such so that different apps we own with different commands can plug in and provide their own commands via action inputs. At first, I tried a single string input called `command` ... 

```yaml
# Right now only this is possible
- name: Deploy Site
  uses: ./packages/my-custom-github-action
  with:
    command: "npx build site-a --environment production --some-other-arg 'this is my value'"
```

but later discovered action would be easier to write if the command name and arguments are *separated*, *with the arguments forming an array*. 

```yaml
# This is not possible (args is a array of strings)
- name: Deploy Site
  uses: ./packages/my-custom-github-action
  with:
    command: 'npx'
    args:
      - 'build'
      - 'site-a'
      - '--environment'
      - 'production' 
      - '--some-other-arg' 
      - 'this is my value'
```

Why do this separation of command name and args?  I believe it's same as asking: Why does [spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) in Node.js separate command name from args, and why does Google Cloud Platform accepts a list of args in [their builder yaml](https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts)? And why does Docker [CMD](https://docs.docker.com/engine/reference/builder/#cmd) use a list? (and so on...)
```javascript
// Node.js spawn: args are array
const ls = spawn('ls', ['-lh', '/usr']);
```

```yaml
# Google Cloud Platform builder: args are array
steps:
- name: 'bash'
  args: ['./myscript.bash']
```

```dockerfile
// Docker CMD args are array
CMD ["executable","param1","param2"]
```

It's an important pattern to prevent information being lost, and I'd much prefer to use this for the design of my action. Right now I can't have a list of args to my action and I'm actually forced to do some very horrible hacky string processing when it comes time for my custom action makes a call to [`spawn`](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options), where at this time I'm it reading what is passed in from the action input. 

You might ask *"can't your action just accept a single string for the whole command + args, then find the args by splitting the string by spaces?"* But this is somewhat flawed as some arguments themselves can contain spaces (e.g. `--some-other-arg 'this is my value'`). Doing such a split will produce an incorrect args list of `["--some-other-arg", "'this", "is", "my" "value'"]` instead of the desired args list that spawn wants: `["-some-other-arg", "'this is my value'"]`. Hope this makes sense. Thanks for reading!
