### DISCUSSION TITLE
No longer able to configure/obtain AWS credentials for s3 in reusable workflow

### DISCUSSION THREAD

**Discussion by zgarrard12** [community/community#78846] [Actions]
### Select Topic Area

Question

## Background
I have been using an Actions workflow for a few months to deploy files to s3 using the aws-actions/configure-aws-credentials workflow without any problems. I recently modified other parts of my deployment job as part of the workflow without changing any part of the AWS credentials configuration and now the configuration step fails every time with the following error:

```shell
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

On the surface this seems like a common problem for users that fail to specify the `id-token` and `contents` permissions with write access and read access respectively for their workflow to use GitHub's OIDC token endpoint, but I have included this from the beginning and it has not changed at all recently so this cannot be part of the problem.

I am using an organization-level secret to set the role-to-assume ENV and SECRET role ARN and the SECRET KEY private SSH key obtained from AWS in the workflow and the ARN and key are still active. 

_**As a bonus question, if someone could advise me how I can try using these credentials another way like on my local machine command line to sanity check that they are working and valid external from the AWS management console, that would be much appreciated.**_

## Action step logs

Here is a snippet from the new failing Action runs at the Configure AWS credentials step:

```shell
Run aws-actions/configure-aws-credentials@v3
  with:
    audience: sts.amazonaws.com
    aws-region: us-east-1
    role-session-name: GitHubActions
    role-duration-seconds: 3600
  env:
    AWS_REGION: us-east-1
    REPOSITORY_NAME: <redacted>/
    GIT_USER: zgarrard1[2](<redacted>/actions/runs/7171647477/job/19530089046#step:10:2)
    BRANCH_NAME: zach/2[3](<redacted>/actions/runs/7171647477/job/19530089046#step:10:3)1211-add-warehouse-release-ci-cd
    COMMIT_SHA: <redacted>
    ARTIFACT_NAME: artifact
    DEPENDENCY_LIST: gzops/dependencies.txt
    MISSING_DEPENDENCY_LIST: gzops/missing-dependencies.txt
    MISSING_DEPENDENCIES: false
    ROLE_TO_ASSUME: 
    SSH_AUTH_SOCK: /tmp/ssh-cVs60JRoBimJ/agent.[17]<redacted>/actions/runs/7171647477/job/19530089046#step:10:17)84
    SSH_AGENT_PID: 1785
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

And here is the log from the same step in my prior Actions run the last time it was working:

```shell
Run aws-actions/configure-aws-credentials@v3
  with:
    audience: sts.amazonaws.com
    aws-region: us-east-[1](<redacted>/actions/runs/7136803989/job/19435817885#step:8:1)
    role-to-assume: ***
    role-session-name: GitHubActions
    role-duration-seconds: 3600
  env:
    AWS_REGION: us-east-1
    REPOSITORY_NAME: <redacted>/
    GIT_USER: chencangyi
    BRANCH_NAME: main
    COMMIT_SHA: <redacted>
    ARTIFACT_NAME: artifact
    DEPENDENCY_LIST: gzops/dependencies.txt
    MISSING_DEPENDENCY_LIST: gzops/missing-dependencies.txt
    MISSING_DEPENDENCIES: false
    SSH_AUTH_SOCK: /tmp/ssh-Yvzxk9Na9ova/agent.[17]<redacted>/actions/runs/7136803989/job/19435817885#step:8:17)93
    SSH_AGENT_PID: 1794
Assuming role with OIDC
Authenticated as assumedRoleId AROAU4WLPVYKDUAGUEYJJ:GitHubActions
```

## Relevant parts of my workflow for reference

My reusable workflow does uses another reusable workflow at the beginning to determine the build environment:

### _determine-deploy-env-from-branch.yml_
```yml
name: 🧐 Determine Environment

on:
  workflow_call:
    outputs:
      environment:
        description: 'The environment from the branch name'
        value: ${{ jobs.determine-environment.outputs.environment }}
      role-to-assume:
        description: 'The role to assume for the environment'
        value: ${{ jobs.determine-environment.outputs.role-to-assume }}


jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine-environment.outputs.environment }}
      role-to-assume: ${{ steps.determine-environment.outputs.role-to-assume }}
    steps:
      - name: Determine Environment
        id: determine-environment
        run: |
          if [ ${{ github.ref_name }} == 'main' ] || [ ${{ github.ref_name }} == 'master' ]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "role-to-assume=${{ secrets.AWS_ROLE_S3_FIRMWARE_DEV }}" >> $GITHUB_OUTPUT
          elif [ ${{ github.ref_name }} == 'release/test' ]; then
            echo "environment=test" >> $GITHUB_OUTPUT
            echo "role-to-assume=${{ secrets.AWS_ROLE_S3_FIRMWARE_TEST }}" >> $GITHUB_OUTPUT
          elif [ ${{ github.ref_name }} == 'release/alpha' ]; then
            echo "environment=alpha" >> $GITHUB_OUTPUT
            echo "role-to-assume=${{ secrets.AWS_ROLE_S3_FIRMWARE_ALPHA }}" >> $GITHUB_OUTPUT
          elif [ ${{ github.ref_name }} == 'release/beta' ]; then
            echo "environment=beta" >> $GITHUB_OUTPUT
            echo "role-to-assume=${{ secrets.AWS_ROLE_S3_FIRMWARE_BETA }}" >> $GITHUB_OUTPUT
          elif [ ${{ github.ref_name }} == 'release/stage' ]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
            echo "role-to-assume=${{ secrets.AWS_ROLE_S3_FIRMWARE_STAGE }}" >> $GITHUB_OUTPUT
          elif [ ${{ github.ref_name }} == 'release/prod' ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
            echo "role-to-assume=${{ secrets.AWS_ROLE_S3_FIRMWARE_PROD }}" >> $GITHUB_OUTPUT
          else # TODO - set to unknown
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "role-to-assume=${{ secrets.AWS_ROLE_S3_FIRMWARE_DEV }}" >> $GITHUB_OUTPUT
          fi
```

And finally here are the relevant parts of the primary reusable workflow where the AWS credentials configuration step is failing:

### _publish-release.yml_
```yml
name: 🚀 GZOps Publish Release

on:
  workflow_call:
    inputs:
      artifact-dir:
        type: string
        description: 'The directory with the gzops build config'
        default: gzops

env:
  AWS_REGION: us-east-1
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  GIT_USER: ${{ github.actor }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  ARTIFACT_NAME: artifact
  DEPENDENCY_LIST: ${{ inputs.artifact-dir }}/dependencies.txt
  MISSING_DEPENDENCY_LIST: ${{ inputs.artifact-dir }}/missing-dependencies.txt
  MISSING_DEPENDENCIES: false
  ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_S3_FIRMWARE_DEV }} # default to dev, will be overwritten in the set-role job

jobs:
  determine-environment:
    name: 🧐 Determine Environment
    uses: ./.github/workflows/determine-deploy-env-from-branch.yml
    secrets: inherit      

  verify-and-publish:
    name: 🕵️ Verify dependencies and publish release
    runs-on: ubuntu-20.04
    needs: [determine-environment]

    permissions: # needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      statuses: write
      contents: read
    
    if: ${{ needs.determine-environment.outputs.environment != 'unknown' }}

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:    
      - name: 🕵️ Set role to assume
        run: |
          echo ROLE_TO_ASSUME=${{ needs.determine-environment.outputs.role-to-assume }} >> $GITHUB_ENV

      - name: 👽 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: GitHubActions
          role-duration-seconds: 3600
```

## What I have already tried

I have already tried the following:
  - Creating another Github organization secret with the same contents and using it instead
  - Rerunning a prior Action using the previous iteration of my workflow, **and it does authenticate successfully**
  - Hard-coding the raw ARN into the `role-to-assume` property. 
  - Tried using configure-aws-credentials v4.0.0

_Any help the community could provide to help me understand why the AWS credentials configuration step is no longer working would be greatly appreciated!_
