### DISCUSSION TITLE
Giving Maintainer Privileges to a GitHub Actions Workflow?

### DISCUSSION THREAD

**Discussion by JohnathonBowers** [community/community#79181] [Actions]
### Select Topic Area

Question

### Body

Hello!

@BigSamu and I are developing a GitHub Actions reusable workflow for the Open Search Dashboards repository, aimed at automating changelog updates. The workflow is hosted at [BigSamu/Open_Search_Change_Set_Create_Action](https://github.com/BigSamu/OpenSearch_Change_Set_Create_Action).

We're facing a challenge with GitHub token permissions. When the workflow is triggered by a PR from a fork, it fails to write files or commit changes due to insufficient permissions, resulting in a 403 error ("Resource not accessible by integration"). This issue does not occur with PRs opened within the same repository.

**Our question:** Is there a way to enable a GitHub Action, triggered by a `pull_request_target` event, to have write and commit permissions on PRs originating from a fork?

We've considered using a Personalized Access Token (PAT), but are seeking a more streamlined solution that minimizes overhead for maintainers and contributors.

We know that fork owners can give maintainers of the base repo permission to commit to their working branch when they open a PR. However, maintainers have to make these commits manually. Would it be at all possible for a workflow to be given maintainer privileges?

We're eager to hear any suggestions or insights on how to resolve this permission issue. Or if a different approach would help us accomplish our goal more effectively, we would welcome your thoughts!

Here's a snippet from our `action.yml` file in the workflow, showing our setup including the PAT attempt:

```
name: "Update Changelog"
description: "Update changelog file when a pull request is raised"
inputs:
  token:
    description: "GitHub token for authentication"
    required: true
  changeset_token:
    description: "Personalized PAT token for creating changeset files"
    required: true
  changeset_path:
    description: "Path where the changeset files will be added"
    # required: true
    default: "changeset/fragments"
runs:
  using: "node16"
  main: "index.js"
```

And here's the proposed workflow configuration for the OpenSearch Dashboards repository:

```
name: Create Change Set

on:
  pull_request_target:
    types: [opened, edited]
    paths-ignore:
      - 'changelogs/fragments/**/*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update Changelog
        uses: BigSamu/OpenSearch_Change_Set_Create_Action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          changeset_token: ${{ secrets.CHANGESET_TOKEN }}
          changeset_path: changelogs/fragments
```

Regards,
Johnathon Bowers
