### DISCUSSION TITLE
Checkout private repo with Github App

### DISCUSSION THREAD

**Discussion by W1zardTech** [community/community#79190] [Actions]
### Select Topic Area

Question

### Body

I need to clone a private repository in my action workflow. I have a GitHub App installed, both in the current repo and the one I want to clone. How do I do this?

Seems like a simple and frequent use case, but haven’t been able to find an answer. This is easy to do in Jenkins using the Github Branch Source plugin, but I’m looking to migrate to actions.

**Comment by W1zardTech** [comment]
I think I found my answer here: https://github.com/marketplace/actions/create-github-app-token#use-app-token-with-actionscheckout

**Comment by github-actions** [comment]
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬

**Comment by thiagofis** [comment]
Here’s how to do it:

1. **Ensure your GitHub App has `Contents: Read` permission** on the target repository.
2. **Use the [`[actions/create-github-app-token](https://github.com/actions/create-github-app-token)`](https://github.com/actions/create-github-app-token) action** to generate a scoped token.
3. **Use the [`[actions/checkout](https://github.com/actions/checkout)`](https://github.com/actions/checkout) action** with that token to clone the private repository.

### ✅ Example Workflow Snippet

```yaml
- uses: actions/create-github-app-token@v2
  id: bot-app-token
  with:
    app-id: ${{ secrets.APP_ID }}
    private-key: ${{ secrets.APP_PRIVATE_KEY }}
    owner: <target-repo-owner> # e.g. MyOrganization

- name: Checkout Target Repository
  uses: actions/checkout@v3
  with:
    repository: <target-repo-owner>/<target-repo-name> # e.g. MyOrganization/MyPrivateRepo
    token: ${{ steps.bot-app-token.outputs.token }}
    ref: <target-repo-branch-name> # e.g. main, master
```

### 🔐 Notes
- Your GitHub App **must be installed in the target repository** for the token to have access.
- The `owner` field should match the organization or user that owns the target repository.
- This approach works well for monorepos, shared workflows, or any setup where cross-repo access is needed.
