### DISCUSSION TITLE
Need help on How to send email notification for specific group about workflow ouput

### DISCUSSION THREAD

**Discussion by salini8642** [community/community#79224] [New to GitHub]
Actually I'm trying to running github actions for deleting stale branches here I need help on how to send notification to specific group what are the branches are deleted.
This is my workflow file:
on:
  schedule:
    - cron: "0 0 15 * *"
   # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:
 jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: Satisfy my repo CDO
    steps:
      - name: Delete those pesky dead branches
        uses: uhg-actions/github-actions-delete-abandoned-branches@v1
        id: delete_stuff
        with:
          github_token: ${{ secrets.Stale_Branch_Token }}
          last_commit_age_days: 120
          ignore_branches: master,develop,Release.*,Integration,hcc_branch,refs/pull/
           # Disable dry run and actually get stuff deleted
          dry_run: no
       - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete_stuff.outputs.deleted_branches }}'"

**Comment by sukhostavets** [comment]
Hi @salini8642,

GitHub Actions doesn't directly send emails, but you can use a third-party action for this.
For example `dawidd6/action-send-mail` that lets you send emails using SMTP (the thing that sends emails in most apps). 

Add this step to your workflow file, after the step where you delete branches:

```yaml
- name: Send Email Notification
  uses: dawidd6/action-send-mail@v2
  with:
    server_address: smtp.yourmail.com
    server_port: 465
    username: ${{secrets.EMAIL_USER}}
    password: ${{secrets.EMAIL_PASS}}
    subject: Deleted Branches Update
    body: These branches were deleted: ${{ steps.delete_stuff.outputs.deleted_branches }}
    to: yourgroup@email.com
    from: youremail@email.com
```

You should add login details as secrets in your GitHub repo for safety.
Ref: https://github.com/marketplace/actions/send-email
Hope this helps!
