### DISCUSSION TITLE
Enforce that all applicable workflows pass before merging

### DISCUSSION THREAD

**Discussion by SimonCockx** [community/community#79237] [Actions] [answered]
### Select Topic Area

Question

### Body

I have multiple workflows which I would like to enforce before a PR can be merged. Some workflows are only triggered if certain files are modified, e.g.,
```
on:
  pull_request:
    paths:
      - 'pom.xml'
      - 'CVE-suppressions.xml'
      - '.github/workflows/cve-scanning.yml'
```

How do I enforce that all _triggered_ workflows must pass before merging? It seems I am only able to define a list of specific workflows that should always pass, which is not useful for my use case. Either:
- I mark every workflow as required, which does not work, since some workflows may not run on every PR, so their status will never "go green", or
- I do not require workflows that might not run in certain situations. This is not ideal.

Any ideas to only enforce applicable workflows?

**Comment by Manpreet-Singh-MS** [comment]


**Reply by SimonCockx** [reply]
How is this gonna make the workflow required?

**Comment by SimonCockx** [comment, marked as answer]
Found this related issue: https://github.com/orgs/community/discussions/13690

**Comment by vitalyk-multinarity** [comment]
I met the same issue last week, and I don't see a good solution so far.
Meanwhile, I decided to trigger the required CI jobs, but just exit them with the 'success' status early.

**Reply by SimonCockx** [reply]
That's an interesting workaround. Could you share how you configure them to exit early?

**Reply by vitalyk-multinarity** [reply]
Well, not too elegant - there is no way to really exit job early :-(
So I used fkirc/skip-duplicate-actions and added a condition to every step.
Something like:

```
- id: skip_check
   uses: fkirc/skip-duplicate-actions@v5
   with:
          cancel_others: 'false'
          paths_ignore: '["directory-to-ignore/**"]'
 - name: "Build  X86"
    if: steps.skip_check.outputs.should_skip != 'true'
    ....
 ```
