### DISCUSSION TITLE
Fail-Fast at different tiers of parallelism

### DISCUSSION THREAD

**Discussion by joshua-temple** [community/community#79238] [Actions]
### Select Topic Area

Product Feedback

### Body

Ask: Provide a **_fail-fast_** solution to allow us to terminate parallel concepts on a given event.

I can see this pie being cut a few different ways, the most extensible being the [Template Groups](#template-groups)

### Workflow Run
* If any of the workflows report a failure, all listed workflows are terminated.
* This, while explicit, means an additional workflow.. sure wish we had a way to [organize](https://github.com/orgs/community/discussions/18055) our workflows better.
```yaml
on:
  workflow_run:
    workflows: [...]
    types: requested
    fail-fast: true
```
### <h3 id="template-groups">Template Groups</h3>
* A means to provide various reactionary behaviors 
* This path feels like it could be expanded quickly into other use cases and likely needs to be ironed out.
* If `status` is not set, inherit `on` value. `status` is the reflected status for the workflow, providing override controls.
```yaml
on:
  ...
  
groupings:
  - workflows: [identifier1, identifier2]
    behavior: cancel
    on: failure
  - workflows: [identifier3, identifier4]
    behavior: skip
    on: success
    status: skipped
  - jobs: [job1, job2]
    behavior: cancel
    on: failure
  - steps: [step1, step2]
    behavior: skip
    on: success

  
jobs:
  ...
```
### Job Level
* Any job with this enabled will terminate itself if a parallel job fails.
* Somewhat described [here](https://github.com/orgs/community/discussions/38361)
```yaml
jobs:
  job-name:
    fail-fast: true
    steps:
      - ...
```
### Step Level 
* Similar to the Job level but scoped to the steps within a job.
* requires [this](https://github.com/orgs/community/discussions/14484) feature request which 👍 🙏 
```yaml
steps:
 - name: My Step
   fail-fast: true
```

I currently have a `workflow_run:requested` that when triggered, effectively polls the GH API checking the state of multiple workflows.

Example Step
```yaml
- name: Cancel Workflows
  env:
    TOKEN: ${{ inputs.token }}
    DRY_RUN: ${{ inputs.dry-run }}
    WORKFLOWS: ${{ inputs.workflows }}
  run: |
    IFS=',' read -ra workflow_files <<< "${WORKFLOWS}"
    for workflow_file in "${workflow_files[@]}"; do
      runs=$(curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/$workflow_file/runs?branch=${GITHUB_REF_NAME}" | jq -r '.workflow_runs[] | select(.status == "in_progress" or .status == "queued") | .id')
      if [ -n "$runs" ]; then
        for run_id in $runs; do
          echo "Terminating workflow run $run_id for $workflow_file..."
          if [ "${DRY_RUN}" == "true" ]; then
            echo "Dry Run: Would terminate workflow run $run_id for $workflow_file"
          else
            curl -X POST -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$run_id/cancel"
          fi  
        done
      else
        echo "No running or queued workflows found for $workflow_file on branch $branch_name."
      fi
    done
```

If in the event one of the workflows described by the trigger fails, the action will cancel the other workflows.

I could see this implemented in a similar manner, as a flag for `workflow_run` but ultimately that means everyone needs to add an additional workflow if they have a similar use case.

I could have made this a parallel job of the workflows this currently monitors but they are not inherently always parallel of one another.

In general I find there are a lot of facets within the different domains (workflow, job, step, etc) that could be leveraged functionally in a similar manner in other domains (types, paths, if, etc) that we seem to have missed the mark on.. all in due time.

TIA
