### DISCUSSION TITLE
Endless 'Waiting for a runner to pick up this job...'

### DISCUSSION THREAD

**Discussion by dhanyn10** [community/community#79279] [Actions]
### Select Topic Area

Question

### Body

hello, my company have private repository and try to use github actions with self hosted runner.
![image](https://github.com/community/community/assets/11478316/19ca7c12-4ecb-4d0b-9c8a-8d47084432b4)
here's the configuration
```yml
name: Docker Image CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
  
    runs-on: [self-hosted, Linux, X64]
    
    env:
      GH_TOKEN: ${{ secrets.COMPANY_PROFILE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy .env
        run: |
          touch .env
          php -r "copy('.env.docker', '.env');"

      - name: Run docker-compose
        run: docker-compose up -d

      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s

      - name: Config Cache
        run: docker exec cp-web php artisan config:cache

      - name: Database Migration with Docker
        run: docker exec cp-web php artisan migrate

      - name: Database Seed with Docker
        run: docker exec cp-web php artisan db:seed

      - name: Run Test Case inside Docker
        run: docker exec cp-web php artisan test
```
please help. Thanks
