### DISCUSSION TITLE
[Issues] Inherit and override parts of user/org-level issue forms

### DISCUSSION THREAD

**Discussion by Andre601** [community/community#79274] [Projects and Issues]
### Select Topic Area

Product Feedback

### Feature Area

Issues

## Idea

A feature should be implemented where you can define a repo-level issue form that inherits settings and values from a user/org-level issue form to then also override.

## What this is about

Currently, GitHub offers these kinds of issue forms:

- User/Org-level issue forms hosted on a `.github` repository which applies to all repositories not setting their own issue forms.
- Repo-level issue forms in a `.github` folder of the repository, which override any user/org-level issue form.

My proposal would add the ability to define issue forms to be inherited from org-level into a repo while the repo itself has issue forms defined.

## How it would work

I can think of two specific ways this could be implemented and achieved.

### 1.) Config.yml option

The issue config (The `config.yml` file located in a `ISSUE_TEMPLATE` folder) could receive a new option called `inherit`.
This option would be a list of issue form file names that should be included in the repositories issue template selector amongst other repo-level issue templates present.

Example:
```yaml
blank_issues_enabled: false
contact_links:
  - name: GitHub Docs
    about: The documentation of GitHub
    url: https://docs.github.com/
inherit:
  - bug_report.yml # Inherits '.github/ISSUE_TEMPLATE/bug_report.yml' from the .github repository of the user/org
```

The issue forms would just be inherited without any additional changes. For changes, I would use the second option I get to now.

### 2.) `inherit` option with overrides in issue form file

The YAML file used for an issue form could receive a new option called `inherit` which would tell it to take all the different options of the defined file to include and use.
This would be effectively the same as not having and repo-level issue forms present, at which point user/org-level issue forms would be used.

What makes this different and more useful would be the option to add and override options from the file.

Perhaps, to keep inheritance simple could also a boolean value (`true`, `yes`, ...) be used instead of a name at which point GitHub would use the name of the file that inherits to look for a matching one in the `.github` repo.

For the examples below, assume a `bug_report.yml` file to exist in `.github/ISSUE_TEMPLATE/` in a `.github` repository with the following content:
```yaml
name: Bug Report
description: Report a bug or issue with this project.

body:
  - type: markdown
    attributes:
      value: |-
        ## Thank you for filing a bug report
        Your help allows our project to improve. Please make sure to include all requested info in their entirety.
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Please select the main Operating System you used while encountering the issue.
      options:
        - Windows
        - Mac
        - Linux
        - Ubuntu
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Give a detailed explanation of what happened, including all the steps it took to encounter this problem.
      placeholder: When I did ... did ... happen.
```

To add a new option, one simply would add one to the form as they would do normally.
Example:
```yaml
inherit: true # Uses the name of this YAML file to look for and inherit from a file with matching name in the .github repository.

body:
  - type: input
    attributes:
      label: Logs
      description: Please upload your logs to https://paste.example.com and provide the generated URL.
      placeholder: https://logs.example.com/abc123
```
This would add an input field with label `Logs` at the end of the issue form.
It should perhaps be considered to allow options to set its position within the issue form. As an example a `index` option to define the index (position) in the list itself. In the above example would adding `index: 2` put the entry right after the Dropdown (Assuming the index would be treated as 0-indexed).
Perhaps some more advanced options that would use the id of an option could work too. Like a `after: <id>` to define the entry after which this one should appear and a `before: <id>` that does the same but puts the option before the one defined.

Another thing that should be considered is overriding existing options. For that should it be a requirement for the option to have an `id` field set, so that it could be identified properly and allow overriding all its aspects.

Here is an example with that mechanic:
```yaml
inherit: true # Uses the name of this YAML file to look for and inherit from a file with matching name in the .github repository.

body:
  - type: dropdown
    id: os # This would override the option with the same id in the inherited file
    attributes:
      label: Operating System
      description: Please select the main Operating System you used while encountering the issue.
      options:
        - Windows
        - Mac
    validations:
      required: true
```
The above would override the `os` option with the new list while leaving the options and their orders the same.

The question now would be on how to remove an option. Perhaps an option `removed` that accepts a boolean value could be used here to remove the option itself.

Also, it could probably be beneficial to have the issue form default to whatever the option uses originally if not present in the override. This would allow to cut of duplicate text, which in our example would be the type, label, description and validations options, leaving something like this:
```yaml
inherit: true # Uses the name of this YAML file to look for and inherit from a file with matching name in the .github repository.

body:
  - id: os # This would override the option with the same id in the inherited file
    attributes:
      options:
        - Windows
        - Mac
```

## Final words

I really hope my idea makes sense in its explanation. I put a lot of time into it to make sure it is understandable on what my idea is.

If things are unclear, don't hesitate to ask me and I'll try to explain it as good as I can.

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to the GitHub feature areas [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) and/or [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).

**Comment by somespecialone** [comment]
Find myself in situation where I need to redirect user who have a question to `GitHub Discussions` from issue choose menu with `contact_links` in `config.yml`.
Repos have user-level issue templates, but repo-level `config.yml` will overlap upper level templates as you describe. Would be nice to have ability to inherit top level templates by default or with option, OR have option where we can interpolate variable (related to accessed repository) in field in `config.yml` at user/org-level so it works in repo and we do not need to duplicate `config.yml` across repositories.

Just for instance, `<repo>` is a accessed repository name:
```yaml
contact_links:
  - name: Ask a Question
    url: https://github.com/user/<repo>/discussions/new?category=q-a
    about: Ask a question about project using GitHub Discussions
```
