### DISCUSSION TITLE
Action stuck on 'Set up Node.JS Version'

### DISCUSSION THREAD

**Discussion by JonahFoster** [community/community#79349] [Actions]
### Select Topic Area

Question

### Body

I have a workflow connected to Azure App services. The repo can be found [here](https://github.com/JonahFoster/college-baseball-stats). It was working great, but I switched from ES6 to CommonJS to be more compatible with my Azure setup. Subsequent actions runs have all gotten stuck on the Set Up Node.JS version of my workflow, which looks like
```
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'      
```
Some of the things I've tried include changing the setup-node version, specifying different node versions, and using a general version like 18.*. The entire workflow worked fine prior to switching to CommonJS, but I'm not sure how that would cause the problem. My package.json has been updated to accommodate it and everything works locally. Any help or advice would be appreciated!
