### DISCUSSION TITLE
`Generate release notes content for a release` API requires `contents: write`

### DISCUSSION THREAD

**Discussion by allanlei** [community/community#79377] [Actions]
### Select Topic Area

Bug

### Body

The [Generate release notes content for a release](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release) API requires `contents: write` when run in a Github Action.  The API will only generate release notes, but not save anywhere so it should not require write permissions.

> The generated release notes are not saved anywhere. They are intended to be generated and used when creating a new release.

According to https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
> Repository collaborators and people with write access to a repository can generate and customize automated release notes for a release.

but this should be referring to generating **and** creating the release (via UI)

This workflow will error with `403`

```yaml
name: Generate Release Notes

on:
  workflow_dispatch:

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          return await github.request('POST /repos/{owner}/{repo}/releases/generate-notes', {
            tag_name: 'v1',
            headers: {
              'X-GitHub-Api-Version': '2022-11-28',
            },
          })
```
