### DISCUSSION TITLE
GitHub Actions runners should report Azure region in the runner context

### DISCUSSION THREAD

**Discussion by DavidBoike** [community/community#8014] [Actions]
In our CI scripts we have dependencies on external services, such as Azure Service Bus, Cosmos DB, or other services hosted as containers in Azure Container Instances. In order to minimize the latency between the GitHub Actions runner and the other service, we'd like to set them up in the same Azure region.

The problem is that we don't know what region that is.

The best we can really do is to use the [Azure Instance Metadata Service](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows) like this:

```pwsh
echo "Getting the Azure region in which this workflow is running..."
$hostInfo = curl --silent -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
$region = $hostInfo.compute.location
```

Except now and then, that fails. And when that needs to be updated (and using the snippet above, it does!) now we have a TON of workflows where we need to do that.

It seems like this is something the GitHub runner, being hosted in Azure, should already know about. It would be really nice if we could just access it through the [runner context](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context) like this:

```yaml
- shell: pwsh
  run: |
    $region = '${{ runner.region }}'
    # Set up whatever service in $region
```

Maybe there are plans to have GitHub runners in different clouds someday? I would be Ok with this too:

```yaml
- shell: pwsh
  run: |
    $cloud = '${{ runner.cloud }}' # could be 'azure' or 'aws'
    $region = '${{ runner.region }}' # could be 'eastus2' in azure or 'us-east-2' in aws
```

Or even this:
```yaml
- shell: pwsh
  run: |
    $cloud = '${{ runner.cloud }}' # could be 'azure' or 'aws'
    $region = '${{ runner.azure_region }}' # could be null if runner in AWS
    $region = '${{ runner.aws_region }}' # could be null if runner in Azure
```
