### DISCUSSION TITLE
Support Regex in the Required Status Check Branch Protection

### DISCUSSION THREAD

**Discussion by SamuelCabralCruz** [community/community#8031] [Pull Requests]
Hi,

It would be really helpful, whenever working with monorepositories, to be able to specify a regex pattern to match any reported status check.

Example:
- I have two projects (Hello and World) and their respective CI will report both status check (job A and job B).
- The required status check would be:
    - job A - Hello
    - job B - Hello
    - job A - World
    - job B - World
 - If I need to add another project and once again have to duplicate both status check
 - Instead I would like to be able to simply list those two statuses:
     - regex: job (A|B) - *
 
Thanks in advance,

**Comment by SamuelCabralCruz** [comment]
At the moment, I am thinking about using [merge gatekeeper](https://github.com/upsidr/merge-gatekeeper) action instead.
This would also reduce workflows complexity related to the fact that paths filter syntax never report status check for skipped workflow which is another bummer.

**Comment by KyleJamesWalker** [comment]
This isn't an answer, just another use case this could work for.

This would also work for our use case, but I'd love an at least one required check to pass. Here's the issue we have, there are two GitHub actions that are both monitoring different paths in the repo so only one of them needs to pass at a time. And based on the files neither are guaranteed to ever run, so they can't be set to required.

The use case is we have one workflow for documentation changes, and one workflow for code changes. So when either is scheduled the pass is required.

**Comment by PsiKai** [comment]
I would like this feature as well for a different purpose.

We utilize the job matrix feature to shard our test suites and scale them horizontally to accommodate more tests and keep the build times reasonably short.

The issue is that every time the shard count it adjusted, the required status checks have to also be changed, which requires Github admin intervention.  This also means that PR builds and main branch builds have to keep the same exact status checks and shard counts, even if more or less tests are run between the two workflows.

What I would like is to create a pattern that matches every shard of a given job without the need for individual checks on each shard.

e.g.

```
jobs:
  test-e2e:
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
```

The required status check would only need to be:

```
test-e2e*
```

Instead of 

```
test-e2e (1)
test-e2e (2)
test-e2e (3)
test-e2e (4)
```

Which needs to change every time that count is adjusted....

**Reply by pmalek** [reply]
Having native support for regex for required checks would be nice but I just wanted to point out that there's a workaround for this by using an additional job which in turn is the only 1 that's required. Its sole purpose is to have all the dependents in its `needs` field like so:

```
  passed:
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
      - unit-tests
      - integration-tests
      - e2e-tests
    if: always()
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "Some jobs failed or were cancelled."
          exit 1
```

(credits go to https://github.com/orgs/community/discussions/26822#discussioncomment-3305794)

Drawback of this approach is that this job needs to be scheduled and in times of higher GH runners usage it might take some time and prolong the pipeline.
