### DISCUSSION TITLE
Run Action on certain tags

### DISCUSSION THREAD

**Discussion by TaCqz** [community/community#80704] [Actions] [answered]
### Select Topic Area

Question

### Body

Hey lads,

I am currently working on a project requiring two different deployments: one for beta and one for stable. For this purpose, I tried finding a way to only run the action if a release for a specific branch is created. The only thing I found, which was similar enough to work, was running the action depending on the release-tag. This is the definition of the action:

For Beta-Releases:

```
on:
    release: 
    types: [published] 
    tags: 'beta_v*.*.*'
```
For Stable-Releases:
```
on:
    release: 
    types: [published] 
    tags: 'stable_v*.*.*'
```
Saddly, this runs both actions on creating a release with either tag. Any Ideas how to correct his so it only runs the required action?

**Comment by GETrackerDan** [comment]
Make sure that the tags key is a list (using - for each item), and each pattern is enclosed in quotes as shown above. This setup should correctly trigger the workflow only for releases that match the specified tag patterns.

```
on:
  release:
    types: [published]
    tags:
      - 'beta_v*.*.*'
```

```
on:
  release:
    types: [published]
    tags:
      - 'stable_v*.*.*'
      ```

**Reply by TaCqz** [reply]
Tried that, but it still runs both actions on creating either release..

**Reply by TaCqz** [reply]
```
on:
  release:
    types: [published]
    tags: 
      - 'beta_v*.*.*'
```
Thats the way it is now, but it still triggers both action on releasing with the tag "beta_v0.0.1"

**Comment by GETrackerDan** [comment]
Try

beta-release.yaml

```name: Beta Release Workflow

on:
  release:
    types: [published]
    tags:
      - 'beta_v*.*.*'

jobs:

#Define your jobs for beta release here


```

stable-release.yaml

```name: Stable Release Workflow

on:
  release:
    types: [published]
    tags:
      - 'stable_v*.*.*'

jobs:

#Define your jobs for stable release here 

```

**Reply by TaCqz** [reply, marked as answer]
This didnt work. Using a YAML-Extension for VSCode it showed me, that the “tags”-tag is invalid. For future reference and anyone seeking the answer: I implemented the following If-Condition on job-level for the first job. The following jobs depend on that job, so the whole action wont run if the first one doesnt run:

```
on:
  release:
    types: [published]
    
jobs:
  prepare:
    name: Prepare
    runs-on: self-hosted
    permissions:
      actions: read
    if: startsWith(github.event.release.tag_name, 'beta') || startsWith(github.event.release.tag_name, 'beta_v')
    steps:
```
