### DISCUSSION TITLE
`failure()` function always returns `false` even if one or more ancestor jobs are failing

### DISCUSSION THREAD

**Discussion by hallgeir-osterbo-ac** [community/community#80788] [Actions]
### Select Topic Area

Bug

### Body

I'm trying to use the `success()` and `failure()` functions in GitHub Actions to detect failures in a previous job in a chain of jobs. According to the documentation at https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions `failure()` should return `true` if any ancestor job failed. Quote: "Returns true when any previous step of a job fails. **If you have a chain of dependent jobs, failure() returns true if any ancestor job fails.**".

However, this does not seem to be the case. I've made a minimal example below. Here there are three jobs:
- One that will always fail
- One that will always succeed
- One that should ALWAYS run, but should run different steps whether there's a failure or success in a previous job.

But it seems that in this example, the step that just outputs "Build completed" runs regardless of the status of the previous steps. Even if I set both the parent jobs to fail, the steps still evaluate `success()` to true, and `failure()` to false.

Is this a bug, or am I missing something?

```
name: Failure Test

on:
  pull_request:
    branches:
    - main
  
    paths:
    - '.github/workflows/failure-test.yml'

jobs:
  failingjob:
    runs-on: [ubuntu-latest]
    steps:
    - run: echo "Job 2.1"
    - run: exit 1
  
  succeedingjob:
    runs-on: [ubuntu-latest]
    steps:
    - run: echo "Job 2.2"

  build:
    needs: [failingjob, succeedingjob]
    runs-on: [ubuntu-latest]
    if: always()
    steps:
    - run: echo "Build completed"
      if: ${{ success() }}
    - run: exit 1
      if: ${{ failure() }}
      shell: pwsh

```
