### DISCUSSION TITLE
Customize badge according to the output of Github Actions

### DISCUSSION THREAD

**Discussion by VictorHuu** [community/community#80796] [Actions]
### Select Topic Area

Question

### Body

This is the workflow file which checks whether there're some files in specific format in 10 directories and counts the number of directories that meet the requirements.

At the end of yml file,I want to add a badge that shows the ratio of qualified directories(like **[Qualified ratio][x/10]**).But as I'm new to the Github Action,I only managed to add the markdown element about badge to the 2nd line of README.

Emm,is there any better solution for this?
```yml
name: Check Files in Directory

on:
  push:
    branches:
      - inspect

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Files
      run: |
        DIRECTORY_PATTERN="*Pattern"
        TARGET_DIRECTORIES=$(find . -type d -name "$DIRECTORY_PATTERN" -exec printf '%s@' {} +)
        COUNT=0
        IFS=$'@' 
        for dir in $TARGET_DIRECTORIES; do
          result=`find "$dir"  \( -type f -name "*.png" -o -name "*.jpg" -o -name "*.mdj" -o -name "*.docx" -o -name "*.md" \)`
          echo "Result is $result under $dir"
          #if [ -n "$result" ]; then
          #  ((COUNT++))
          #fi
        done
        echo "Found $COUNT directories with PNG, JPG, MDJ, DOCX, or MD files."
        BADGE="[![Found $COUNT directories](https://img.shields.io/badge/Found-$COUNT%20directories-green)](#)"
        sed -i '2i\'"${BADGE}" README.md
      env:
        DIRECTORY_PATTERN: ${{ secrets.DIRECTORY_PATTERN }}
```
