### DISCUSSION TITLE
Github action passing variables to a file

### DISCUSSION THREAD

**Discussion by Angelk90** [community/community#80954] [Actions]
### Select Topic Area

Question

### Body

I need to make sure to pass a variable to a js file.
The variable contains a json.
But I'm not getting it to work.

Can you give me a hand?

```yaml
name: Test

on:
  push:
    branches:
      - main

jobs:
  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run my script
        run: |
          echo 'MY_VAR_1000=$(node ./test/setTimeout1000.js)' >> $GITHUB_ENV

      - name: Print
        run: |
          echo "$MY_VAR_1000"
          echo $MY_VAR_1000
          echo "${{ env.MY_VAR_1000 }}"
          echo ${{ env.MY_VAR_1000 }}

      - name: Write test results to README.md
        run: |
          node ./MakeTable.js >> README.md
        env:
          a: echo "$MY_VAR_1000"
          b: echo $MY_VAR_1000
          c: echo "${{ env.MY_VAR_1000 }}"
          d: echo ${{ env.MY_VAR_1000 }}

      - name: Commit and push changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Test results updated"
          git push origin main
```

setTimeout1000.js
```js
const startTime = performance.now();
let callbackCalled = false;

setTimeout(() => {
  callbackCalled = true;
}, 1000);

const endTime = performance.now();
const timeTaken = endTime - startTime;

const json = {
  startTime,
  endTime,
  timeTaken,
  callbackCalled
};

/*
{
  startTime: 36.99421699999948,
  endTime: 37.8464260000037,
  timeTaken: 0.8522090000042226,
  callbackCalled: false
}
*/

console.log(json);
```

MakeTable.js

```js
const { a, b, c, d } = process.env;
console.log(a, b, c, d);
```

This is what is printed in the file README.md
`
echo "$MY_VAR_1000" echo $MY_VAR_1000 echo "$(node ./test/setTimeout1000.js)" echo $(node ./test/setTimeout1000.js)
`

Github action console:
<img width="1044" alt="Screenshot 2023-12-19 alle 23 20 40" src="https://github.com/community/community/assets/20476002/17d40ccc-ec22-43f9-8ca0-4021fc81ee9c">
