### DISCUSSION TITLE
[Feature Request] Add Projects v2 Events to Workflow Triggers

### DISCUSSION THREAD

**Discussion by enlightenedpie** [community/community#81187] [Actions]
### Select Topic Area

General

### Body

Currently `projects_v2` and `projects_v2_item` are webhook events, but it would be desired (and more consistent) if those events were also triggers in Workflows. Example:

```
name: Projects Workflow

on:
  projects_v2:
    types: [closed, created, deleted, edited, reopened]
  projects_v2_item:
    types: [archived, converted, created, deleted, edited, reordered, restored]
```

They are currently not active Workflow triggers, and the existing `project*` triggers don't work on the projects v2.

Thank you!
