### DISCUSSION TITLE
Trigger Github Actions on comment

### DISCUSSION THREAD

**Discussion by rondanen** [community/community#81382] [Actions]
### Select Topic Area

Question

### Body

Hello,
I need to trigger my CI when I write a specific comment on the pull request (not an in-line comment/issue). So when I do that kind of comment on a PR:
![Screenshot 2023-12-21 at 19 00 37](https://github.com/community/community/assets/10159985/e1d7285b-3704-4808-85a4-2086d15567a2)

I've tried the most basic YML configs but it did not work.
OPTION 1:
```
name: PR Review Comment Trigger

on:
  pull_request_review_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "A comment was added to a pull request review!"
```

OPTION 2:
```
name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "A comment was added to a pull request!"
```

I've looked at resources like [this discussion](https://github.com/orgs/community/discussions/25389) but none of them works, any idea?

**Comment by dmpapageo** [comment]
try this one:

```
name: Run CI on Comment

on:
  issue_comment:
    types: [created]

jobs:
  check-comment-and-run-ci:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/runci')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CI
        run: |
          echo "CI triggered by comment '/runci' on PR"
          # Add your CI commands here


```
