### DISCUSSION TITLE
workflow_dispatch trigger not available in branch, except it is!

### DISCUSSION THREAD

**Discussion by mrvanes** [community/community#8140] [Actions] [answered]
When triggering a workflow with workflow_dispatch action and then selecting the branch that actually contains this workflow including the `workflow_dispatch` trigger, I get the following error:

```Workflow does not exist or does not have a workflow_dispatch trigger in this branch.```

_main_ branch has this workflow as well and that one works. The idea is that I further develop the trigger in the test branch, but I can't trigger it manually?

Update:
Triggering the action (on the develop branch) using the API results in this response
```
$ curl \
  -H "Authorization: token xxxx" \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/abc/xyz/actions/workflows/runner.yml/dispatches \
  -d '{"ref":"feature-ci-runner"}'

{
  "message": "Workflow does not have 'workflow_dispatch' trigger",
  "documentation_url": "https://docs.github.com/rest/reference/actions#create-a-workflow-dispatch-event"
}
```
Which, as stated before, isn't true.

**Comment by mrvanes** [comment, marked as answer]
Never mind, there was a typo in the workflow that caused it to be unparsable in the develop branch.
I'll leave the question here for those encountering the same problems: have another close look at your workflow ;)

**Reply by Oksana-Kaliniouk** [reply]
Thank you for leaving your question and the solution to this!

**Reply by varshamehtre** [reply]
Thanks , it helped me.

**Reply by Pixie-Axerup** [reply]
thanks! I didn't realize that the workflow I manually added in the main branch needed to have the same name as the action I have in my branch that I don't want to merge yet :-) Now I know!

**Comment by vigneshindn** [comment]
Hi I Am facing the same issue but my case was a bit different, we have created a new branch not from any existing branch in the repo, just i try to add a workflow_dispatch to trigger manually but the workflow doesn't show in the action tab itself. i am search the workflow the in same other branch , am getting a error like "Workflow does not exist or does not have a workflow_dispatch trigger in this branch.". please any body suggest any solution to run the workflow_dispatch in a branch not created from main or master or any existing branch, but the workflow works if any push / PR happened in that branch if i reconfigure without manual trigger

**Reply by piotrekkr** [reply]
Check this out: https://stackoverflow.com/q/63362126/1089412 Good explanation there. You need to run workflow using `push` event at least once so GitHub will register it and then you can run it from your branch using `gh` cli tool. Or you can merge some dummy workflow with dispatch event trigger (so it will be registered) and then you can make another branch with actual workflow code to run and execute workflow using this branch with GitHub UI.

**Reply by vigneshindn** [reply]
Hi @piotrekkr 

i have try my best but not working

name: Android build based non-default tag-removed trigger1

```
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build Lint
        run: ./gradlew lintDebug
    
      - name: Upload Build Lint Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/lint-results-debug.html
```

Actually, i try this in a sub-branch, but the branch is not checkout/created from the main branch.

**Reply by piotrekkr** [reply]
Not sure you read SO question and answers properly but you can push something like this as `.github/workflows/test.yml` to your PR branch (example branch `feat/test-workflow`): 
```
name: Test workflow

on:
  workflow_dispatch:
  release:
    types: [created]  
  push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
```

this should register workflow in github and then you can remove `push:` and execute your workflow using

```
gh workflow run test.yml --ref feat/test-workflow
```
It should run your workflow and it should be visible in github actions tab in your repo without merging it to default repo branch
