### DISCUSSION TITLE
How to do ssh to a remote linux machine from GitHub actions?

### DISCUSSION THREAD

**Discussion by shikhindahikar** [community/community#81980] [Actions]
### Select Topic Area

Question

### Body

Hi, I would like to connect to a remote linux machine using ssh keys where I will have a public key on the remote and private key as a GitHub actions secret. I want to be able to run some terminal commands on the remote, such as git commands, and some build scripts. Any way I can achieve this using the GitHub actions? 
I have so far tried [appleboy/ssh-actions](https://github.com/appleboy/ssh-action) but it seems that it only works for docker containers.

**Comment by netxer** [comment]
It seems like you have connections issues to your machine rather issue with appleboy/ssh-action, verify firstly if you can even log with ssh to that machine.

And if you can, here is an example of how I used it to connect to windows machine with ssh it might help you:
```
- name: Deploying Script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          timeout: 300s

          script: |
            powershell command
```

**Reply by shikhindahikar** [reply]
Yes, I can ssh to the same machine using my local. It connects successfully without any password since I have my public key in the remote's authorized_keys. Only somehow it is not working on GitHub actions.

**Reply by shikhindahikar** [reply]
I tried your script and it still gives me same `dial tcp my_ip:22: connect: connection timed out`. 

This is my exact yml script:
```
name: Pull remote
on:
  workflow_dispatch:
    inputs:
      # IP address of the venue machine
      host:
        description: 'SSH host for the remote machine'
        required: true
      # username of the remote machine
      user:
        description: 'SSH user for authentication'
        required: true
jobs:
  git-pull:
    runs-on: ubuntu-latest
    steps:
    # checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Deploying Script
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ github.event.inputs.host }}
        username: ${{ github.event.inputs.user }}
        password: ${{ secrets.KEY }}
        port: 22
        timeout: 300s
    
        script: |
          cd test-ci-cd && git pull
```
