### DISCUSSION TITLE
Unintuitive & potentially dangerous behaviour for required & skipped status checks

### DISCUSSION THREAD

**Discussion by s0** [community/community#82691] [Repositories]
### Select Topic Area

Product Feedback

### Body

Creating a discussion here following feedback on GitHub docs: https://github.com/github/docs/discussions/30170

We have a situation at my company where we have a number of workflows across repos that are structured in a way that look something like this:

```yaml
jobs:
  matrix-test:
    strategy:
    matrix:
      prop: [value-a, value-b] # these values differ from repo-to-repo
  build-and-publish:
    needs: matrix-test
```

Now in addition to this, we have branch protection mechanisms that require `build-and-publish` to have succeeded, however when any of the `matrix-test` jobs fail, `build-and-publish` will be skipped, and this results in the branch protection considering the check as succeeding and allowing the merge, which has taken us by surprise and feels counter-intruitive.

I'm not sure that this is really the correct default behaviour, if a job is skipped due to a dependency failure, it seems intuitive to me that instead:

* by default, (from the point of view of the required status check) it should still be considered pending (not success).
* if a user wants to consider a failed dependency as passing the check, they should add a conditional that expresses this:

  ```yaml
  if: needs.matrix-test.result == 'success'
  ```
  the condition would be false, and then skipping would be considered a check success.

This seems to be a lot safer, as I think it would avoid many situations where others have made a similar assumption, and overwriting the default is a simple one-line condition.

## Current Workaround

As it currently stands, we can work around this by either:

* Updating our branch protection to also require status checks for each of the dependencies.
  * (this is not really feasible, as the size of the matrix can be very large, and is highly varied per-repo, and also prevents us from using e.g. organization-level repository rules across many repos at once).
* Using `always()` to cause the downstream job to run when the dependencies fail, and then also explicitly check the status, e.g:

  ```yaml
  jobs:
    matrix-test:
      strategy:
      matrix:
        prop: [value-a, value-b] # these values differ from repo-to-repo
    build-and-publish:
      needs: matrix-test
      if: always()
      steps:
       - name: Fail step
         if: ${{ needs.matrix-test.result != 'success' }}
         run: |
           echo "${{ toJSON(needs.matrix-test) }}"
           exit 1     
       - # rest of the steps
  ```

  Thanks @tonycch for this suggestion.

What are people's thoughts? Should the default behaviour be changed? (GitHub have [already opened an issue to clarify the documentation](https://github.com/github/docs/discussions/30170#discussioncomment-7892164)).
