### DISCUSSION TITLE
Issue Forms: Support .github org-level use of repo-specific links

### DISCUSSION THREAD

**Discussion by jeffpaul** [community/community#8285] [Projects and Issues]
I would like to be able to have a `bug-report.yml` file within our org's `.github` repo so that it applies to all repos without their own Issue Forms/Templates.  I would also like our org-level issue form to include a statement such as:

```
    - type: checkboxes
      id: terms
      attributes:
        label: Code of Conduct
        description: By submitting this issue, you agree to follow our [Code of Conduct](/CODE_OF_CONDUCT.md).
        options:
          - label: I agree to follow this project's Code of Conduct
            required: true
```

...where the `CODE_OF_CONDUCT.md` link when the issue form is rendered within a repo links to the Code of Conduct file within that repo.  I've yet to find a way to provide a generic link in an org Issue Form that when that Issue Form is utilized on a repo links to a file within that repo.  Please allow support for that in some manner, thanks!
