### DISCUSSION TITLE
Error for deployment_status event on PRs from forked repos

### DISCUSSION THREAD

**Discussion by redocecin** [community/community#83015] [Actions]
### Select Topic Area

Question

### Body

I need to implement a workflow that executes Playwright tests immediately after a successful deployment of a PR to a staging environment. The current structure of my workflow file is as follows:

```
name: Run Test

on:
  deployment_status:

jobs:
  run_test:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      ...
      - name: Run Playwright tests
        run: npx playwright test
      ...
```

This workflow functions as expected when I initiate a PR from a branch within the primary repository. However, when I initiate a PR from a forked repository, I encounter the following error message:
```
This run was triggered by the commit {commit_id} which is not referenced by any branches or tags in this repository. It is either an orphaned commit or from a fork of this repository.
```

Is this behavior intentional? If yes, can you please provide me with an alternative approach?
