### DISCUSSION TITLE
GitHub Actions | Show Parameters in Preview

### DISCUSSION THREAD

**Discussion by brettrowberry** [community/community#8303] [Actions] [answered]
I have a GitHub Actions workflow that defines a `workflow_dispatch` that takes some inputs, e.g.

```yml
name: CICD

on:
  push:
    branches:
      - master
      - cicd-*
  workflow_dispatch:
    inputs:
      deployment_git_rev:
        description: 'SHA or ref (branch, tag, other named thing) to deploy'
        required: true
        default: ''
      target_release_channel:
        description: 'Release channel (`Pre-prod` or `Prod`)'
        required: true
        default: 'Pre-prod'
      services:
        description: 'Space-separated list of services to deploy (e.g. dog cat). ALL to deploy all services'
        required: true
        default: ''
...
```

When I run it, I can see the workflow name, run number, and that it was manually run by me. All very helpful!

![actions_run](https://user-images.githubusercontent.com/10521647/144252078-eaebfa7c-2941-4dac-9dcf-6de88e6a6fed.png)

I wish I could see the branch it was run on and the parameters passed to the workflow run. Is there a way to do this, or would a change need to be made?

**Comment by ethomson** [comment]
Hi @brettrowberry - now that you mention it, we don't surface this information very easily.  I'll look into how to make this easier for you.  This is great feedback, I appreciate it.

**Reply by piotrcichosz** [reply]
@ethomson any news? We could use that feature, otherwise will probably have to migrate to composite action to create multiple workflows

**Reply by NielsJorck** [reply]
We would also very much like this information visible, especially which branch it was run on would be super helpful. Right now it is pretty hard to dig that information out.

**Reply by rburridge** [reply]
+1 on this too - I've added a step to display all the parameters but it would be really useful to see them in the summary!

**Reply by jmosley5** [reply]
+1 ☝🏼 Working on this now and this info would be really helpful. Thank you! 🙏🏼

**Reply by kdomagal** [reply]
almost a year and no update on it? 👎 This feature is very needed 🙄

**Reply by jpcastberg** [reply]
This is much needed context when viewing a workflow run. How can I debug a failed workflow when I can't even see the arguments passed to it??

**Reply by matosjoa** [reply]
Any news? really need this one

**Reply by kota65535** [reply]
Any progress? This feature is highly needed

**Reply by Wouter-Vugt-Shell** [reply]
No progress, but a rather important need. We need to know what values are used to start a workflow to find why it broke. This seems rudimentary and very very basic.

**Reply by harsha549** [reply]
Did we ever get an update about it

**Comment by ashwinv11** [comment]
Any update on this feature? This is sorely missed and one of the biggest reasons why we're not considering moving deployment workloads from Jenkins to GHA. 

Sort of related to having better visibility into the inputs provided into a `workflow_dispatch` run but, Jenkins has a [rebuilder](https://plugins.jenkins.io/rebuild/) plugin that we use heavily to re-run a job with the same set of inputs. It also allows us to edit specific inputs before re-running, that way we can override just one input but not need to fill out the entire input form each time we're trying to trigger a run.

This plugin plays nicely with Jenkins "parameters" where we can view the inputs provided to the run: 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/5572129/199338565-dffdce65-a5ed-41af-9391-3ba1a4c6c825.png">

**Comment by ChristopherHX** [comment, marked as answer]
GitHub recently added the `run-name` property (https://github.blog/changelog/2022-09-26-github-actions-dynamic-names-for-workflow-runs), which allows you to add the inputs and branch name to the run name displayed in the UI

For example:
```yaml
on:
  workflow_dispatch:
    inputs:
      test:
        type: choice
        options:
        - mychoice
        - a
        - b
      b:
        type: boolean
  push:
run-name: ${{ github.event_name == 'workflow_dispatch' && format('CI/CD-{0}-branch-{1}', tojson(inputs), github.ref_name) || '' }}
jobs:
  testa:
    runs-on: ubuntu-latest
    steps:
    - run: ${{tojson(inputs)}}
      shell: cat {0}
    - run: ${{tojson(github.event.inputs)}}
      shell: cat {0}
```
This is the result
![Screenshot_20221121-111656~2](https://user-images.githubusercontent.com/44845461/203025752-375cd555-8136-4a03-8fce-c79e8ec01385.png)

_`|| ''` in the run-name expression means use the default run name for other workflow events_

**Reply by ashwinv11** [reply]
Thanks @ChristopherHX! While this is definitely useful to see the inputs, it's still not ideal to help cut down the time it takes to re-trigger workflows with the same inputs. Especially if you have a workflow with many inputs, you have to copy and paste values between browser tabs/windows to fill out the input modal for the new run.

Ideally, there's some way for us to have a "pre-filled" input form in the UI from a previous run that we can use as a starting point before kicking off a new run. For eg. the "Git Ref" input's value should be pre-filled from the previous run if we're attempting to use another run as a starting point:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/5572129/203176639-64f35b85-d69b-4a5f-818b-e4e26f68b930.png">

**Reply by ahvigil** [reply]
cool workaround but its pretty gross that you have to stuff json into a name to workaround github action UI limitations

**Reply by kota65535** [reply]
Should this be marked as resolved? Frankly, this is a dirty workaround.

**Reply by brettrowberry** [reply]
I did something like the snippet below and it’s perfect (and no JSON displayed):

`run-name: ${{ github.event_name == 'workflow_dispatch' && format('Manual {0} | {1} | {2}', inputs.deployment_git_rev, inputs.environments, inputs.services) || '' }}`

which can produce something like:

`Manual my-branch | dev stage | adder subtracter`

**Reply by brettrowberry** [reply]
I filed this as an issue and a feature was added that perfectly meets the need I expressed.

**Reply by ahvigil** [reply]
I've opened [a separate discussion](https://github.com/orgs/community/discussions/49648) for cases where using run-name is not an acceptable solution

**Comment by brettrowberry** [comment]
@ethomson @ChristopherHX The `run-name` property meets my needs. I consider this resolved.

@ashwinv11 Pre-filling with previous inputs feels like a separate concern.

**Comment by Alex17Li** [comment]
Another possible workaround is to log the parameters as an output after you click into a job

```
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Display parameters
        shell: bash
        run: echo "${{ format('<h1>Parameters</h1><p>{0}</p>', tojson(inputs)) }}" > "$GITHUB_STEP_SUMMARY"
     ... other steps

```

Here's an example of what it might look like.

![Screenshot from 2024-07-09 21-47-20](https://github.com/community/community/assets/136381636/0c84ea6a-4885-47ce-8ca2-f49a48bbc501)

**Reply by Alex17Li** [reply]
Also, if you would like to format it as a table, you can install the jq library and change the output format into markdown table syntax with the following steps.

```
      - name: Install jq
        run : |
          apt update
          apt install -y jq
      - name: Display parameters this workflow was called with
        shell: bash
        run:
          printf '|Parameter|Value|\n|------|------|\n' >> $GITHUB_STEP_SUMMARY &&
          jq -r 'to_entries | map("|\(.key)|\(.value)|") | join("\n") | @text' <<< '${{tojson(inputs)}}' | sed 's/\\n/\n/g' >> $GITHUB_STEP_SUMMARY

```

We just print the markdown table header, then parse key value pairs with jq and format them with the markdown table | character separating them. Then we join the lines with \n and convert to text to remove the quotes. Finally we convert literal '\n' that appear in some versions of bash to actual newlines. You can modify this to, e.g. print one parameter per line without a table if you prefer.

Example output:

![Screenshot from 2024-11-05 14-06-29](https://github.com/user-attachments/assets/d2a03cf2-9cd9-4b77-b149-acd0842f583d)

**Comment by shayki5** [comment]
You can use my action which print the inputs to the logs and can add them to the summary:
[Print Workflow Dispatch Inputs](https://github.com/marketplace/actions/print-workflow-dispatch-inputs-and-env-vars)

**Comment by m-s-abeer** [comment]
You can use this simple re-usable action to directly print the input params to the GHA summary:-
```yaml
    steps:
      - name: Update GHA Summary with Workflow Inputs 
        uses: m-s-abeer/update-gha-summary-with-workflow-inputs@v1
```
Marketplace link:- https://github.com/marketplace/actions/update-gha-summary-with-workflow-dispatch-input-params
Example SS:-
![image](https://github.com/user-attachments/assets/8b8f28ad-15c5-423a-b10b-877bb67f3afb)

https://github.com/marketplace/actions/update-gha-summary-with-workflow-dispatch-input-params
