### DISCUSSION TITLE
GitHub Actions: Feedback to reusable workflows

### DISCUSSION THREAD

**Discussion by borekb** [community/community#8311] [Actions]
Hi, I'm trying to use [reusable workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) and have two pieces of feedback:

## 1: I cannot reference a reusable workflow via relative path

We have a shared deployment logic that I've put into `deploy-reusable.yaml` and then we have two "real" workflows, `deploy-preview.yaml` and `deploy-production.yaml`, where I'd like to do this:

```yaml
name: Deploy
on: push
jobs:
  deploy-preview:
    name: Preview
    uses: ./deploy-reusable.yaml
    with:
      deploymentKind: preview
```

However, the only accepted form is `{owner}/{repo}/{path}/{filename}@{ref}` (I tried 😄) so I have to do this:

1. Make changes in `deploy-reusable.yaml`
2. Commit it so that I have a SHA for the next steps
3. Update all the workflows that call it, e.g.
    - `deploy-preview.yaml`:
        ```yaml
        name: Deploy
        on: ...
        jobs:
          deploy-preview:
            name: Preview
            uses: our-org/our-repo/.github/workflows/deploy-reusable.yaml@c623e1c3cc623411d19b805620ba191b57f8ea8f
            with:
              deploymentKind: preview
        ```
    - `deploy-production.yaml`:
        ```yaml
        name: Deploy
        on: ...
        jobs:
          deploy-preview:
            name: Production
            uses: our-org/our-repo/.github/workflows/deploy-reusable.yaml@c623e1c3cc623411d19b805620ba191b57f8ea8f
            with:
              deploymentKind: production
        ```
4. Commit those files
5. Push the two commits

This double committing and inability to test changes in one go is quite annoying.

## 2: Name of the called workflow is shown in "checks" UI

This is mostly a cosmetic issue but the checks UI (e.g., at the end of pull requests) shows "{Workflow name} / {Job name}" so before, we had "Deploy / Preview" and "Deploy / Production".

Newly, as a side effect of the YAML refactoring, there's another part:

<img width="945" alt="Screen Shot 2021-12-01 at 19 22 14" src="https://user-images.githubusercontent.com/101152/144293376-85a272a7-af63-4653-9809-7d7670b4a00a.png">

It feels a little bit wrong that a change of YAML structure also affects the readability of our checks UI. I think that the called workflow job name shouldn't be printed in the checks UI.
