### DISCUSSION TITLE
500 error when you use checkboxes options with Korean

### DISCUSSION THREAD

**Discussion by llighter** [community/community#8342] [Projects and Issues]
When using the **checkboxes** type in the issue template, if you use Korean instead of English for the **label**(`- label: 이 프로젝트의 행동 강령을 따르는 데 동의합니다`) item under **options**, an error occurs when creating an issue. see the videos below.

```yml
  - type: checkboxes
    id: terms
    attributes:
      label: 행동 강령 Code of Conduct
      description: 이 문제를 제출함으로써 귀하는 [행동 강령](https://github.com/milky-ro/astro-blog/blob/main/CODE_OF_CONDUCT.md)을 준수하는 데 동의하게 됩니다.
      options:
        - label: 이 프로젝트의 행동 강령을 따르는 데 동의합니다
          required: true
```

**Server error with Korean**

https://user-images.githubusercontent.com/11993431/144419617-77656c1c-7602-47ea-ac8c-cec1c2cdef04.mov

**OK with English**

https://user-images.githubusercontent.com/11993431/144419684-8b190773-02d0-448a-8eec-4a4e0b095541.mov
