### DISCUSSION TITLE
Make "Unchanged files with check annotations" section collapsable

### DISCUSSION THREAD

**Discussion by valerie-maher** [community/community#8379] [Pull Requests]
My organization has a Beta feature called "Unchanged files with check annotations".  When I'm reviewing a pull request, I find this section to be distracting.  Could you make that section collapsable so that I can move it out of my view when I'm trying to focus on the PR?
I see that you can already collapse each item in the section, but I'd love the ability to collapse the entire section with just one click.
Thanks very much!

**Comment by caarmen** [comment]
I don't have an answer, but I'd like to add to this feedback.

I'd like to have the option to disable this feature on PRs.

Imagine that you start to work on a legacy project, and you introduce checks. Since there were no checks before, there may be many, many legacy issues. They will all appear in every new PR you create. It's not realistic to assume that you can first fix all the legacy issues before doing any new developments, just to have more relevant PR checks :)

**Comment by danielgomezrico** [comment]
The same thing is happening to us, which led us to disable all services like rubocop and codefactor on CI, and thats pretty sad

**Comment by rocklan** [comment]
I find this feature pretty useless, it would be great if we could hide it or turn it off somehow.

**Comment by nstanard** [comment]
Same, I'd really like to disable this feature.

**Comment by kylesethgray** [comment]
It's mildly annoying that this can't be disabled.

**Comment by valerie-maher** [comment]
Work-around: I was able to get rid of that section by setting up a 'remove()' filter in uBlock Origin

**Reply by dpwiz** [reply]
Unfortunately the section doesn't have a specific marker to it and the filter ends up very fragile.

**Reply by valerie-maher** [reply]
Yes, I wish there were a stable, unique ID.  You might be able to use something like one of these
```
github.com##*[src*="unchanged_files_with_annotations"]:remove()
github.com##div.*:has-text("Unchanged files with check annotations"):remove()
```

**Comment by rubengmurray** [comment]
How has it been this long and this hasn't been made configurable to turn off? Looks like it's been in 'beta' for 2 and a half years... 😩

**Comment by nielstenboom** [comment]
Hey guys, landed here going crazy over trying to turn these annotations off and figured I'd post the solution I found: 

```yaml
      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Disable check annotations
        run: |   
          echo "::remove-matcher owner=eslint-compact::"
          echo "::remove-matcher owner=eslint-stylish::"
          echo "::remove-matcher owner=tsc::"
```

With this they no longer appeared - Hope it helps to prevent someone from going nearly insane like I almost did 😄
