### DISCUSSION TITLE
Actions suddenly complains about syntax errors in yml

### DISCUSSION THREAD

**Discussion by lars-reimann** [community/community#8384] [Actions] [answered]
My actions no longer run and complain about syntax errors in the `yml` file, even though they worked this morning and are unchanged since.

### Example:

```yml
name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }} # <-- syntax error
  cancel-in-progress: true

# ...
```

### Shown message:
![image](https://user-images.githubusercontent.com/2501322/144639535-7d8eabd5-1bc8-425a-ab6f-e8b9d8895adb.png)

### Additional context:
* Last change to workflow: 18 days ago
* Ran fine at 11:34 UTC today triggered by Dependabot
* Now (16:33 UTC) fails on the same branch when Dependabot rebases it
* Occurs for all branches (not just Dependabot)

### Other examples where syntax errors are reported:
```yml
concurrency:
  group: ${{ github.head_ref }}__megalinter-reusable__lint # <-- syntax error
  cancel-in-progress: true
```

```yml
concurrency:
  group: ${{ github.head_ref }}__pr-format-reusable__check-title # <-- syntax error
  cancel-in-progress: true
```

```yml
concurrency:
  group: ${{ github.head_ref }}__pr-format__check-title # <-- syntax error
  cancel-in-progress: true
```

```yml
concurrency:
  group: ${{ github.head_ref }}__megalinter__lint # <-- syntax error
  cancel-in-progress: true
```

```yml
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }} # <-- syntax error
  cancel-in-progress: true
```
