### DISCUSSION TITLE
How to set variables based on command execution results

### DISCUSSION THREAD

**Discussion by suinxinliulang** [community/community#84013] [Actions]
### Select Topic Area

Question

### Body

I want to get version number from mvn command and set it as a variable in order to use it in next step, how to do it?

for example, I want to get project version using mvn help command, but below config is not working.

```yaml
- name: Get image name and version
  id: image-name-version
  run: echo "image_version=mvn help:evaluate -Dexpression=\"project.version\" -q -DforceStdout" >> "$GITHUB_OUTPUT"
- name: Echo Image Version
  env:
    VERSION: ${{ steps.image-name-version.outputs.image_version }}
```
