### DISCUSSION TITLE
Environment variables are not accessable when calling reusable workflow

### DISCUSSION THREAD

**Discussion by yvasyliev** [community/community#84036] [Actions]
### Select Topic Area

Question

### Body

I have a job `release-v2.yml` that deploys artifact to remote server. Before the deployment, the job first performs unit testing.

```yml
name: Release v2

on:
  # ...

jobs:
  # ...
  perform-tests:
    uses: ./.github/workflows/perform-tests.yml
  # ...
```

`release-v2.yml` job invokes reusable workflow `perform-tests.yml` located in the same repository to perform tests. `perform-tests.yml` requires some Test environment variables (secrets). 

<details>
<summary>perform-tests.yml</summary>

```yml
name: Perform tests

on:
  - push
  - pull_request
  - workflow_call

jobs:
  perform-tests:
    runs-on: ubuntu-latest
    environment: Test
    concurrency: perform-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        env:
          REDDIT_SUBREDDIT: ${{ secrets.REDDIT_SUBREDDIT }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ vars.SPRING_JPA_HIBERNATE_DDL_AUTO }}
          TELEGRAM_ADMIN_ID: ${{ secrets.TELEGRAM_ADMIN_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_SCHEDULE_POSTING_ENABLED: ${{ vars.TELEGRAM_SCHEDULE_POSTING_ENABLED }}
        run: mvn test
```

</details>

But `environment: Test` is ignored, when invoking `perform-tests.yml` out of `release-v2.yml`.
As you may see, almost all variables are empty:
![image](https://github.com/community/community/assets/44120348/e2249d33-824b-4a05-aaf2-96947e3ddbd4)

If I invoke `perform-tests.yml` manually, tests will pass.

How can I make it work when invoking from `release-v2.yml`?

[Project repo](https://github.com/yvasyliev/reddit-telegram-forwarder)
