### DISCUSSION TITLE
Does GitHub Actions support this non-standard Cron syntax?

### DISCUSSION THREAD

**Discussion by PaulRBerg** [community/community#84039] [Actions]
### Select Topic Area

Question

### Body

I saw this on the [crontab.guru](https://crontab.guru) website:

<img src="https://i.stack.imgur.com/Nn7m0.png" width="300"/>

Does GitHub Actions support this syntax? That is, can I define a CI workflow like this?

```yml
name: "Do something every week"
on:
  schedule:
    - cron: "@weekly"
```

**Comment by GunaPalanivel** [comment]
Yes, GitHub Actions supports cron syntax for scheduling workflows. You can use predefined strings like "@weekly" or define custom cron expressions. For example:

## GitHub Actions Workflow

```yaml
name: "Do something every week"
on:
  schedule:
    - cron: "0 4 * * 1"  # Run every Monday at 04:00
```


GitHub Actions supports cron syntax for scheduling workflows. You can use predefined strings like "@weekly" or define custom cron expressions. The cron syntax follows the standard format with five fields representing (minute, hour, day of month, month, day of week).

For more details, you can refer to the [GitHub Actions documentation on scheduling workflows](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events).
