### DISCUSSION TITLE
Unexpected branch matching in trigger when name contains `/`

### DISCUSSION THREAD

**Discussion by simPod** [community/community#84114] [Actions]
### Select Topic Area

Bug

### Body

I'm trying to trigger a workflow on branches with certain name only

This works for me

```yaml
on:
  pull_request:
    branches:
      - 'something'
```

This does not:

```yaml
on:
  pull_request:
    branches:
      - 'some/thing'
      - 'some/*'
```

I went through Actions docs but did not find any mention that would mention a `/` matching limitation or anything related. E.g. according to [Filter pattern cheat sheet](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) it should work.

_Similar issue https://github.com/orgs/community/discussions/76226_

How do I match those branches?
