### DISCUSSION TITLE
Github Actions build summaries are different on main branch than all other branches - workflow YAMLs are the same, but behavior is different?

### DISCUSSION THREAD

**Discussion by jim-bender-kr** [community/community#84146] [Actions]
### Select Topic Area

Question

### Body

We have a Github SaaS repo where we run the following workflow (included below)

This worklfow has been propagated to all branches and is identical on all branches, but the behavior is different (see screenshot)

![healthyBuild](https://github.com/community/community/assets/70488893/f0538501-2d4f-4d2c-9948-bbc13517b0dd)

On healthy builds, we see two additional links on the left under Jobs.  Every branch *other* than main does this just fine.  But on main branch, those last two Jobs links on the left don't show up -- Does anyone know why?

ALSO -- It should be noted -- the build logging on all branches *including* main shows that all of the build steps complete on all branches, even including main.  The only problem is that those links don't show up on the left on main for some reason? :(

Here is our workflow yaml:

```
name: 🚀 Manual Run Karate Docker Container
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Example: v0.0.0"
        required: true

jobs:
  run-integration-tests:
    name: Run Integration Test Container ${{ github.event.inputs.VERSION }}
    runs-on: [self-hosted, kroger]
    container:
      image: ####redacted####-docker-prod.jfrog.io/digitalbi/digital-bi-integration-tests:${{ github.event.inputs.VERSION }}
      credentials:
        username: ${{ secrets.ARTIFACTORY_USR }}
        password: ${{ secrets.ARTIFACTORY_USR_IDENTITY_SAAS }}
      env:
        JAVA_HOME: /jre

    steps:
      - name: Add JRE to path
        run: |
          echo "/jre/bin" >> $GITHUB_PATH
      - name: Run Karate Docker Container ${{ github.event.inputs.VERSION }}
        working-directory: /app
        run: |
          java -jar CollectorAppsIntegrationTests.jar
      - name: "List contents of /app/target/karate-reports"
        run: |
          ls -l /app/target/karate-reports
      - name: Upload Karate reports
        uses: actions/upload-artifact@v3
        with:
          name: Karate Reports
          path: /app/target/karate-reports

  publish-integration-test-results:
    name: Publish Integration Test Results
    runs-on: [self-hosted, kroger]
    defaults:
      run:
        working-directory: ./karate-reports
    needs:
      - run-integration-tests
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Download Karate Reports artifact from job
        uses: actions/download-artifact@v3
        with:
          name: Karate Reports
          path: ./karate-reports
      - name: Add Integration Test Results to PR
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: Add Integration Test Results to PR
          report_paths: "./karate-reports/*.xml"
      - name: Summarize Integration Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Summarize Integration Test Results # Name of the check run which will be created
          path: "./karate-reports/*.xml" # Path to test results
          reporter: java-junit # Format of test results
```
