### DISCUSSION TITLE
Actions, C++ project - Unexpected ECHO Output

### DISCUSSION THREAD

**Discussion by JustaSimpleUser** [community/community#84169] [Actions]
I'm new to Actions and .yml files.  I've scoured for examples of building an MS Visual Studio C++ project in an Action and have gotten this far but  have now hit the proverbial wall.  I have several questions but I'll deal with them one at a time.

```
name: Continuous Integration
on:
  workflow_dispatch:
  
permissions: read-all

jobs:
  build:
    name: Build the application
    runs-on: [ self-hosted, Windows ]
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: MSVS Setup
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\'

      - name: Output
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          echo ${{env.GITHUB_WORKSPACE}}
          echo ${{env.BUILD_CONFIGURATION}}
          echo ${{env.SOLUTION_FILE_PATH}}
          
      - name: Build
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
```
I have successfully created and used (on simpler workflow examples) a self-hosted runner.  I now have several obstacles to this running successfully, one being that the echo commands in the Output step output nothing, in fact, they simply display `echo ' '`. 

1. How can I examine the values of the env variables at runtime, or any time for that matter?
2. Where are the 2nd and 3rd envs created?
3. Do I actually need them to perform the build?

Cheers,

JaSU
