### DISCUSSION TITLE
Action - Local Machine Script Execution Policy with a Self-Hosted Runner

### DISCUSSION THREAD

**Discussion by JustaSimpleUser** [community/community#84172] [Actions]
I'm new to Actions and .yml files, and I have created the following workflow.   I have successfully created and used (on simpler workflow examples) a self-hosted runner and it will only run if I set the local machine execution policy to Bypass.:

```
name: Continuous Integration
on:
  workflow_dispatch:
  
permissions: read-all

jobs:
  build:
    name: Build the application
    runs-on: [ self-hosted, Windows ]
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: MSVS Setup
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\'

      - name: Output
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          echo ${{env.GITHUB_WORKSPACE}}
          echo ${{env.BUILD_CONFIGURATION}}
          echo ${{env.SOLUTION_FILE_PATH}}
          
      - name: Build
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
```
Why must I have permissions permanently configured as almost entirely open?  Isn't there a better way to permit script execution, perhaps something that is local to the workflow?
