### DISCUSSION TITLE
Workflow msbuild Command Fails

### DISCUSSION THREAD

**Discussion by JustaSimpleUser** [community/community#84171] [Actions] [answered]
I'm new to Actions and .yml files, and I have created the following workflow.  I've scoured for examples of building an MS Visual Studio C++ project in an Action and have not be able to successfully run a build:

```
name: Continuous Integration
on:
  workflow_dispatch:
  
permissions: read-all

jobs:
  build:
    name: Build the application
    runs-on: [ self-hosted, Windows ]
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: MSVS Setup
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\'

      - name: Output
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          echo ${{env.GITHUB_WORKSPACE}}
          echo ${{env.BUILD_CONFIGURATION}}
          echo ${{env.SOLUTION_FILE_PATH}}
          
      - name: Build
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
```
I have successfully created and used (on simpler workflow examples) a self-hosted runner.   The msbuild command in the Build step generates the error:  `error MSB4126: The specified solution configuration "|x64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.` 

The project builds on the local machine within MS Visual Studio 2022.  I check the .sln referenced in the error and it does, in fact, contain that string but it's not something over which I have control.  I checked the solution's Properties and I can't select anything other configuration that isn't determined by MSVS.

How do I get msbuild to work?
