### DISCUSSION TITLE
RSS Helm chart and customization

### DISCUSSION THREAD

**Discussion by github-samuel-rats** [community/community#84185] [Actions]
### Select Topic Area

Product Feedback

### Body

Hello good people, 

We are going more and more into GitHub Actions these days, and one of the things we would like to improve is the ability to create custom RSS runners without having to copy-paste the big amount of customization (volumes, env variables, that sort of things) to tweak a few things.

One "easy" fix for that would be replacing the use of YAML lists in the chart with maps, Helm being able to merge maps.

For example: if I want to use another image for my runner, I have to redefine the whole container list definition
```
template:
  spec:
    containers:
      - name: runner
        image: my-custom-runner-images
        command: ["/home/runner/run.sh"]
        resources:
          limits:
            cpu: "4"
            memory: "16Gi"
```

Let's say we have a map for containers, instead of a list:

```
template:
  spec:
    containers:
      runner:
        image: base-runner-images
        command: ["/home/runner/run.sh"]
        resources:
          limits:
            cpu: "4"
            memory: "16Gi"
```

I could have that in my `base.yaml` definition, and allow customization by using a new `custom.yaml` file such as;

```
template:
  spec:
    containers:
      runner:
        image: my-custom-runner-images
```

With that, I could do a `helm install my-custom-runner -f base.yaml -f custom.yaml oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set`. 

This applies to a bunch of values:
* template.spec
  * initContainers
    * env
    * volumeMounts
  * containers
    * env
    * volumeMounts
  * volumes

This would significantly reduce the amount of boilerplate code in an environment with a lot of different runners, without having to do some kind of yaml preprocessing before sending everything to Helm for installation.
