### DISCUSSION TITLE
How to trigger workflow when issue is connected to PR?

### DISCUSSION THREAD

**Discussion by t1m0thyj** [community/community#84696] [Actions]
### Select Topic Area

Question

### Body

I want to trigger a workflow whenever an issue is linked to a PR (in the "Development" section of the sidebar):
![image](https://github.com/community/community/assets/22344007/5d84f41c-04ca-4b9b-ae03-30e1d9631b74)

This generates a "connected" event that is returned by the ["List issue events" REST API](https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28#list-issue-events).

However I can't find a workflow event that corresponds to this in the list of [Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows).

**Comment by fury-05** [comment]
1. Define a Workflow File:
Create a .github/workflows/your_workflow.yml file in your repository. In this file, you define the workflow and specify the events that trigger it.

2. Use issues and pull_request Events:
You can use both issues and pull_request events and run your workflow when either event occurs.

```yaml
on:
  issues:
    types: [opened, edited, reopened, closed]
  pull_request:
    types: [opened, synchronize, closed]

```

This configuration will trigger your workflow whenever an issue is opened, edited, reopened, or closed, and whenever a pull request is opened, synchronized (updated), or closed.

3. Check for Link Between Issue and Pull Request:
Within your workflow, you can use GitHub API to check if the issue is linked to a pull request. You can use the pulls endpoint to get the linked pull requests for an issue.

```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue and PR Link
        run: |
          //Use GitHub API to check if the issue is linked to a PR
          //Your logic to determine if the issue is linked to a PR


```

You'll need to use GitHub API and appropriate scripting (e.g., using curl or a programming language) to check the relationship between the issue and the pull request. Look for the pull_request field in the issue data

I hope that this is what you were looking for.
