### DISCUSSION TITLE
"gh variable list" leads to error "Resource not accessible by integration"

### DISCUSSION THREAD

**Discussion by ed-mak** [community/community#84700] [Actions]
### Select Topic Area

Question

### Body

This is my test workflow file. 
```
name: test workflow

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: [push]

jobs:
  greet:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
          gh variable list
```

This is generating an error for me: `failed to get variables: HTTP 403: Resource not accessible by integration`

I've also double-checked my repo permissions and they seem to be correct
<img width="840" alt="image" src="https://github.com/community/community/assets/64488234/ee0ccb0e-5c9a-4b79-b242-96fadff3dd95">

Is anyone able to help figure out how else I can proceed? My next step is to be able to modify a repository variable called "LAST_EXECUTED".
