### DISCUSSION TITLE
[actions/setup-node] Error: need auth You need to authorize this machine using `npm adduser`

### DISCUSSION THREAD

**Discussion by SteeveGL** [community/community#84865] [Actions] [answered]
### Select Topic Area

Question

### Body

What ever I try, I always get this:
```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

II tried multiple configuration, versions and security parameters. the npmrc file is as documented. Nothing works.

I'm owner and maintainer on the repository.

Here is the job: [complete file here](https://github.com/UtopikSandcastle/accesscontrol-api/blob/main/.github/workflows/publish.yml)
```yaml
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: '@utopiksandcastle'
      - run: npm install
      - run: npm run build
      - run: npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I feel like npm ignore the npmrc file, but it looks fine:
```
Run npm install
  npm install
  shell: /usr/bin/bash -e {0}
  env:
    DOCKERFILE_PATH: src/AccessControlAPI
    REGISTRY: ghcr.io
    IMAGE_NAME: UtopikSandcastle/accesscontrol-api
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
```

```
Run cat $NPM_CONFIG_USERCONFIG
//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
@utopiksandcastle:registry=https://npm.pkg.github.com/
always-auth=true
```
