### DISCUSSION TITLE
SCP Code files from Runner to AWS Server not working

### DISCUSSION THREAD

**Discussion by itsarkcodes** [community/community#84906] [Actions]
### Select Topic Area

Question

### Body

I am trying to deploy my application on EC2 Instance. Currently i want to install dependencies and do eveything on the runner and then simple scp those files to my Ec2 website location /var/www/vhosts/mywebsite,in/
The below script works but it doesnt do changes on the server. What is the problem?
```yml
name: Deploy to Stage
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/enablr.in/enablr.in/enablrsales.com/v1/
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  
      
      - name: Install dependencies
        run: |
            npm install

      - name: Build
        run: |
            npm install -g grunt-cli
            grunt build

      - name: Copy folder content recursively to remote
        uses: appleboy/scp-action@master
        with:
          source: /home/runner/work/enablr.in/enablr.in/enablrsales.com/v1/
          target: /var/www/vhosts/showdigital.in/enablrsales
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
```

**Comment by Naimulnobel** [comment]
The issue might be related to the path you're using in the `working-directory` and `source` fields. The `working-directory` field should be a relative path from the root of your repository, and the `source` field should be a relative path from the root of the runner's workspace.

Here's how you can fix this:

1. Remove the `working-directory` field from the `defaults` section. This is not necessary as you're not changing the working directory for all the steps.

2. Update the `source` field in the `appleboy/scp-action@master` action to `"."`. This will copy all the files from the root of your repository.

Here's how your updated workflow file should look like:

```yaml
name: Deploy to Stage
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  
      
      - name: Install dependencies
        run: |
            npm install

      - name: Build
        run: |
            npm install -g grunt-cli
            grunt build

      - name: Copy folder content recursively to remote
        uses: appleboy/scp-action@master
        with:
          source: "."
          target: /var/www/vhosts/showdigital.in/enablrsales
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
```

This should resolve the issue and allow your files to be copied to your EC2 instance correctly.
