### DISCUSSION TITLE
How to trigger an action on pull request based on branch name starts with

### DISCUSSION THREAD

**Discussion by rizwannadeem2017** [community/community#84990] [Actions] [answered]
### Select Topic Area

Question

### Body

I would to setup a source branch check workflow.  

1 - on pull request master branch should only merge from staging branch (Done)
2 - on pull request staging branch should only merge from develop branch (Done)
3 - on pull request develop branch should only merge from branch starts with bug/ and hotfix/  (not working)

The first conditions are working but third one is not. 

here my code 

```
name: source-branch-check

on: [pull_request]

jobs:

  check-source-branch:
  
    runs-on: ubuntu-latest
    steps:
      - name: check source branch from prod 
        if: contains(fromJson('["master", "main"]'), github.base_ref) && github.head_ref !='staging'
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('Changes to staging should merge from staging') 

      - name: check source from develop
        if: github.base_ref == 'staging' && github.head_ref != 'develop'
        uses: actions/github-script@v6
        with:
          script: | 
              core.setFailed('Changes to staging should merge from staging')

      - name: check source from feature branch
        if:  github.base_ref == 'develop' && github.head_ref != startsWith(github.head_ref, 'feature/') 
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('Changes to staging should merge from bug or feature')

```

**Comment by nickkipshidze** [comment]
It looks like you have an syntax error.

I think doing this should fix it, I haven't tested it though:
```
if:  github.base_ref == 'develop' && ${{ !startsWith(github.head_ref, 'feature/') }}
```

**Reply by rizwannadeemupwork** [reply]
@NickKipshidze  I tested it, didn't work :( same issue

**Reply by rizwannadeem2017** [reply, marked as answer]
Solved it with this code: 

```
name: source-repo-check

on: [pull_request]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: check source branch from prod 
        if: contains(fromJson('["master", "main"]'), github.base_ref) && github.head_ref !='staging'
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('Changes to staging should merge from staging') 

      - name: check source from develop
        if: github.base_ref == 'staging' && github.head_ref != 'develop'
        uses: actions/github-script@v6
        with:
          script: | 
              core.setFailed('Changes to staging should merge from staging')
   
      - name: check source from feature branch
        if: github.base_ref == 'develop' && !(startsWith(github.head_ref, 'feature-') || startsWith(github.head_ref, 'bug-'))
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('Changes to staging should merge from bug or feature')

```
