### DISCUSSION TITLE
Cannot access API host from Docker in Github actions

### DISCUSSION THREAD

**Discussion by Venkat-Rajgopal** [community/community#85009] [Actions]
### Select Topic Area

Bug

### Body

My GitHub action has suddenly stopped running since it can't find the `localhost:8000` anymore where the FastAPI is running. Local testing this runs perfectly fine. 

docker-compose where the container is built

### Docker compose
```yml
services:
  fastapi:
    build:
      dockerfile: ./docker/api.dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: bla
      DB_PASSWORD: blabla
      DB_NAME: dada
    ports:
      - "8000:8000"
  database:
    image: public.ecr.aws/docker/library/postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: foo
      POSTGRES_DB: bar
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"
```

### Github CI

```yml
jobs:
    Unit-Testing:
      runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: [ "1.3.2" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start Container
      run: docker-compose up -d

    - name: Test Container status
      run: |
        docker ps
        curl http://localhost:8000

```

Github fails to `curl` either of `localhost:8000` or `http://0.0.0.0:8000` even though we can see in `docker ps` that the port is running at `8000:8000`. 

```console
CONTAINER ID   IMAGE                                                COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
67023f62f6b2   fastapi                         "/bin/sh -c 'poetry …"   31 seconds ago   Up Less than a second     0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   fastapi-1
9c14d9c8175c   public.ecr.aws/docker/library/postgres:15.2-alpine   "docker-entrypoint.s…"   31 seconds ago   Up 30 seconds (healthy)   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   database-1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
Error: Process completed with exit code 52.
```

I am not sure what the problem is and how this suddenly fails. 

Appreciate your inputs.
