### DISCUSSION TITLE
Reusable workflow doesn’t trigger status check

### DISCUSSION THREAD

**Discussion by twebner** [community/community#8512] [Actions]
We have a required PR check based on a GitHub Actions workflow. This workflow is normally triggered on branch push and works fine.

Recently, I created a new workflow to rebase a PR branch, and since I am using the default GITHUB_TOKEN, the updated branch does not automatically trigger the first workflow. So I made the first workflow reusable, and called it from my new workflow after a successful rebase using the `workflow_call` event.

But now when I run the rebase workflow, the PR check for the first workflow never passes, and instead displays `Expected — Waiting for status to be reported`.

So it seems like calling a workflow from another workflow does not properly notify that the check was run. Will this issue be fixed? Is there a suggested workaround?

**Comment by solarmosaic-kflorence** [comment]
I have the same problem. I just converted an action into a re-usable workflow and it no longer uses the job with matching name for updating the status check (they are both called `validate`).

In other words, the old workflow looked like this:

```yaml
name: library-sbt-scala-project_ci
on:
  pull_request:
    paths:
      - "libraries/sbt/plugins/scala-project/**"
      - "!libraries/sbt/plugins/scala-project/**.md"
jobs:
  validate:
    environment:
      name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - uses: ./.github/actions/cicd/codepipeline-library/ci
        with:
          aws-access-key-id: "${{ secrets.AWS_GITHUB_USER_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_GITHUB_USER_SECRET_ACCESS_KEY }}"
          project-name: "${{ env.PROJECT_NAME }}"
          project-path: "${{ env.PROJECT_PATH }}"

```

And the new one looks like this:

```yaml
name: library-sbt-scala-project_ci
on:
  pull_request:
    paths:
      - "libraries/sbt/plugins/scala-project/**"
      - "!libraries/sbt/plugins/scala-project/**.md"
jobs:
  validate:
    uses: ./.github/workflows/codepipeline_library_ci.yaml
    secrets: inherit
    with:
      project-name: library-sbt-scala-project
```

I have tried naming the project workflow job `validate` and the re-usable workflow also as `validate` but neither satisfies the `validate` status check. In the UI it shows up like this:

![Screen Shot 2022-06-15 at 5 05 39 PM](https://user-images.githubusercontent.com/52473140/173940339-cd0397b0-0e8e-4180-a972-bde9fa3a2fb6.png)

Is there any way to get it to honor one of the project workflow or the re-usable workflow job names? As a workaround for now I can manually set the status as passed at the end of the workflow, but that is pretty hacky.

```yaml
      - env:
          GITHUB_TOKEN: "${{ github.token }}"
        run: | # https://docs.github.com/en/rest/reference/repos#create-a-commit-status
          gh api "/repos/{owner}/{repo}/statuses/${{ github.event.pull_request.head.sha }}" \
            -f context="validate" \
            -f state="success" \
            -f description="Workaround for https://github.com/github-community/community/discussions/8512" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
```

**Reply by solarmosaic-kflorence** [reply]
I have submitted a ticket for this with my company's enterprise account. Will post back here if I get a response.

**Reply by solarmosaic-kflorence** [reply]
From GitHub support:

> When a job references a reusable workflow, the name of the reported check will capture the names of the jobs in both the caller and called workflow. So in this case, GitHub is reporting the check as `validate / validate` rather than `validate` (The branch protection rules expect the check to be named `validate`)

> For such scenarios, you'll need to edit the branch protection rule and remove `validate` as a required status check and instead select `validate / validate` which is the check that is being reported by the workflow.

It makes sense, but this makes it difficult for us to migrate from our old action-based workflows onto the new re-usable workflows without updating everything at once (not very realistic for us since we have a large monorepo). I will have to stick with the workaround above for now.

**Reply by davidamey** [reply]
Have just come across exactly the same issue.
Restructured our workflows to share common parts only for the required 'parent' check to never succeed.

Going to use your workaround for now, but it's a shame to have to.

**Reply by jalaziz** [reply]
Same exact issue. It's incredible frustrating. You can use the calling job as a check and it reports the correct status when it is "skipped", but not when it completes. Quite broken and inconsistent :(

**Comment by yanghua-ola** [comment]
This problem was annoying; and it just gets more annoying after `Organization Ruleset` became available to Pro Plan. In an ideal world, I define an Organization Ruleset to require certain check pass e.g. lint for all repositories. I make the `lint` workflow reusable to achieve minimal duplication and maximal maintainability.

However that's not possible because of the issue reported in this ticket: the reusable and reused workflow had different names.

### Proposed Solution

- idea 1: allow wildcard/regex when configuring required status check
- idea 2: have a consistent rule when reporting running status, e.g. always use job id / job name regardless of if the job was reused.

**Comment by fractiunate** [comment]
Is there any possible solution? I tried to implement our shared checks on org level but it does not link those two...:

```
---
name: PR Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

# PR Checks / lint-github-actions-workflows / Lint GitHub Actions Workflows
jobs:
  lint-github-actions-workflows:
    uses: our-org/.github/.github/workflows/pr-workflow-checks.yml@main
```

Shared:

```
---
name: "🧪 Test: Workflow Files Lint"

on:
  workflow_dispatch:
...
jobs:
  actionlint:
    name: Lint GitHub Actions Workflows
    steps:
...
```

Neither:

PR Checks / lint-github-actions-workflows / Lint GitHub Actions Workflows (pull_request)

nor
PR Checks / lint-github-actions-workflows / Lint GitHub Actions Workflows

work on org level branch ruleset...
