### DISCUSSION TITLE
Artifact newman report generate

### DISCUSSION THREAD

**Discussion by princekumar-stepinsolutions** [community/community#85451] [Actions]
### Select Topic Area

Question

### Body

During the pipeline run, I'm creating a newman folder which should contain the newman generated report index.html and then I want to use it as a source for GitHub Pages.

At the moment, the newman folder is empty. My question is what's wrong inside my code? I have tried everything I could.
and Newman report was generated i check from job summery
- name: Run ${{ matrix.collection }} 
id: report
run: newman run ./node/${{ matrix.collection }}.json -e ./node/Env/all-ENV.json -g ./node/Env/global-env.json --reporters cli,htmlextra --reporter-htmlextra-export ./newman/prod"${{ matrix.collection }}"-retrying-report.html

- name: Output prod Mailgun monitor collection
        if: ${{ failure() && steps.report.conclusion == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
            name: prod-report
            path: ./temp_newman

**Comment by Naimulnobel** [comment]
The issue might be related to the path you're providing to the `--reporter-htmlextra-export` option in the `newman run` command and the `path` field in the `actions/upload-artifact@v3` action.

In the `newman run` command, you're exporting the report to `./newman/prod"${{ matrix.collection }}"-retrying-report.html`. However, in the `actions/upload-artifact@v3` action, you're uploading files from the `./temp_newman` directory. 

If you want to upload the Newman report, you should make sure that the `path` field in the `actions/upload-artifact@v3` action points to the directory where the report is located. 

Here's how you can fix this:

1. Update the `--reporter-htmlextra-export` option in the `newman run` command to export the report to the `./temp_newman` directory:

```yaml
name: Run ${{ matrix.collection }}
id: report
run: newman run ./node/${{ matrix.collection }}.json -e ./node/Env/all-ENV.json -g ./node/Env/global-env.json --reporters cli,htmlextra --reporter-htmlextra-export ./temp_newman/prod"${{ matrix.collection }}"-retrying-report.html
```

2. Keep the `path` field in the `actions/upload-artifact@v3` action as `./temp_newman`:

```yaml
name: Output prod Mailgun monitor collection
if: ${{ failure() && steps.report.conclusion == 'failure' }}
uses: actions/upload-artifact@v3
with:
  name: prod-report
  path: ./temp_newman
```

This should resolve the issue and allow your Newman report to be uploaded as an artifact correctly.
