### DISCUSSION TITLE
Nuget packages registry stopped authenticating requests after enabling 2FA

### DISCUSSION THREAD

**Discussion by vulasau** [community/community#85667] [Packages] [answered]
### Select Topic Area

Question

### Body

I'm using actions to push nuget packages to github package registry.

Here is my action:
```
name: Publish NuGet

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Add github packages
      run: dotnet nuget add source https://nuget.pkg.github.com/[organization]/index.json -n github -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack [project].csproj --output nuget-packages --configuration Release
    - name: Push
      run: dotnet nuget push nuget-packages/*.nupkg -s "github" -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
```

Repository is **public**. Package (and all it's previous versions) is also **public**.
Before I enabled 2FA for my account (github.actor) everything was working fine and I had no problems with packages.
Now all my pipelines are broken.

All action steps before "**Push**" end successfully.
"**Push**" step fails with the following errors:
```
Pushing [project].[version].nupkg to 'https://nuget.pkg.github.com/[organization]'...
  PUT https://nuget.pkg.github.com/[organization]/
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
  Forbidden https://nuget.pkg.github.com/[organization]/ [13](https://github.com/[organization]/[project]/actions/runs/7460313334/job/20298136223#step:9:14)0ms
error: Response status code does not indicate success: 403 (Forbidden).
```

I never use my PAT - GITHUB_TOKEN is used instead and always had right permissions (worked before).
I have enabled 2FA recently (Jan 2024).

What can be the problem and how to fix it?
