### DISCUSSION TITLE
Custom code font

### DISCUSSION THREAD

**Discussion by intrnl** [community/community#8571] [Other Feature Feedback, Questions, & Ideas] [answered]
Make it easy for users to choose their own code font, currently I have this snippet of CSS where it can easily break at anytime due to changes no matter how large or small.

```css
.bBrJyO {
	font-family: sans-serif;
}

.buBiHK, /* Homepage code example */
.ckbNLI, /* Directory tree header */
.gxMGxq, /* Directory tree entry */
.jeLmvk, /* Directory tree up entry */
.iJPfxe, /* File path */
.iRDwdS, /* File LOC */
.jBicmA, /* File size */
.kBthvh, /* Code viewer */
.dhulmV, /* Selected definition */
.ktSXeD, /* Definition in flyout */
.hdkQmd, /* Definition LOC in flyout */
.bEUCKo, /* Matched code in flyout */
.iklEZP  /* Selected code in flyout */
{
	font-family: monospace;
}
```
