### DISCUSSION TITLE
I can't find my Status checks

### DISCUSSION THREAD

**Discussion by thiagosaud** [community/community#86098] [Repositories]
### Select Topic Area

Question

### Body

I've created an action called "`linters.yml`", where in this action it runs only when a pull request is opened. It simply scans the code to do best practice analysis. 

The rationale for me to have created this and want to add it to the "status check" of the repository, is that the merge button can only be enabled if this action runs successfully.

**CODE:**

```
name: LINTERS

on:
  pull_request:
    branches:
      - "release/*"
jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        architecture: [x64]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Nodejs ${{ matrix.node-version }} - ${{ matrix. architecture }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: CACHE NODE.JS MODULES
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: RUN YARN INSTALL
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: RUN COMMITLINT
        uses: borales/actions-yarn@v4
        with:
          cmd: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: RUN BRANCHLINT
        uses: lekterable/branchlint-action@2.0.0
        with:
          allowed: |
            /release\//i
          errorMessage: "Branches with the name are not allowed."

      - name: RUN PRETTIER CHECK
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier:check

      - name: RUN STYLELINT
        uses: borales/actions-yarn@v4
        with:
          cmd: stylelint:check

      - name: RUN ESLINT
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

```

![image](https://github.com/community/community/assets/126628718/28fc8e21-d6df-46e3-be3c-2b59af602790)
