### DISCUSSION TITLE
GH-PAGES deploy action doesn't find the directory.

### DISCUSSION THREAD

**Discussion by thiagosaud** [community/community#86097] [Actions]
### Select Topic Area

Question

### Body

I configured the repository to use a custom action to **deploy my static site on** `gh-pages`, however, the action runs correctly but it can't identify the files. When I access the "`gh-pages`" branch, all the files are there.

[THIS IS THE LINK TO MY REPOSITORY](https://github.com/thiagosauddev/thiagosauddev.github.io)
[THIS IS THE LINK TO THE BRANCH OF MY GH-PAGES](https://github.com/thiagosauddev/thiagosauddev.github.io/tree/gh-pages)
[THIS IS THE LOG OF THE ACTION
](https://github.com/thiagosauddev/thiagosauddev.github.io/actions/runs/7470420827/job/20329079841)

**THIS IS MY ACTION:**

```
name: GITHUB PAGES DEPLOY

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        architecture: [x64]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Nodejs ${{ matrix.node-version }} - ${{ matrix. architecture }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: RUN YARN INSTALL
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: CLEAN BUILD DIRECTORY
        run: rm -rf dist

      - name: RUN YARN BUILD
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: SETUP PAGES
        uses: actions/configure-pages@v4

      - name: RUN UPLOAD ARTIFACT
        uses: actions/upload-pages-artifact@v3
        with:
          path: "." # Upload entire repository

      - name: RUN DEPLOY TO GITHUB-PAGES
        id: deployment
        uses: actions/deploy-pages@v4
        # with:
        #   cname: thiagosaud.dev
```

**Comment by Naimulnobel** [comment]
The issue seems to be with the path you're providing to the `actions/upload-pages-artifact@v3` action. You're currently setting the path to `"."`, which means the entire repository. However, you should be pointing it to the directory where your build files are located.

In your case, since you're running `yarn build`, the build files are likely in the `dist` directory. So, you should update the `path` option to point to the `dist` directory:

```yaml
      - name: RUN UPLOAD ARTIFACT
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist" # Upload build files
```

Then, in the `actions/deploy-pages@v4` action, you should specify the `path` option to point to the `dist` directory as well:

```yaml
      - name: RUN DEPLOY TO GITHUB-PAGES
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: "./dist" # Deploy build files
```

This should resolve the issue and allow your GitHub Pages site to be deployed correctly.
