### DISCUSSION TITLE
[Feature Request] Github Actions Strict Path Checking

### DISCUSSION THREAD

**Discussion by jacobcrell** [community/community#86511] [Actions]
### Select Topic Area

Product Feedback

### Body

Hello,

I have encountered a semi consistent issue that I hope could be solved with a new feature in the `paths` portion of the Workflow syntax

Scenario:

- I have created a script for my CI named `foo.sh`
- I have setup my Github Action similar to the following, notice that `foo.sh` is run as part of the `test` step and it is in the `paths` so that tests will be run if `foo.sh` changes.

```
name: foo Tests
on:
  pull_request:
    paths:
      - "app/**"
      - "foo.sh"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run foo tests
        run: ./foo.sh
```

I then update the name of my file from foo.sh to bar.sh and update the workflow to look like the following. In doing so, I fail to update the `paths` and `paths` now points to a non-existent `foo.sh` file.

```
name: bar Tests
on:
  pull_request:
    paths:
      - "app/**"
      - "foo.sh"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run bar tests
        run: ./bar.sh
```

I've now lost the functionality of running my tests when changing the test script file and there is no compile-esque way of knowing that it has happened. Instead, tribal knowledge of the Action setup is needed to keep the `paths` up to date.

It would be excellent if I could apply a setting to the `paths` to operate in a strict manner and throw an error along the lines of `"Strict Path violation. foo.sh is specified in the workflow paths but does not exist in the repository" ` if the files specified in the `paths` do not exist within the codebase.  This could potentially look something like:
```
name: foo Tests
on:
  pull_request:
    paths:
      - "app/**"
      - "foo.sh"
    strict_paths: true
```

and would prevent the above described issue from occuring.
