### DISCUSSION TITLE
Creating Review Comments for Commits from Forked Repo

### DISCUSSION THREAD

**Discussion by NicHaley** [community/community#87714] [Apps, API and Webhooks]
### Select Topic Area

Question

### Body

I have a GitHub Action which will create Review Comments on a PR. This was working well, until a community member opened a PR from a forked repo and the action broke.

The reason was because the request to create the Review Comment gave a `401`, I believe because the [endpoint](https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-review-comment-for-a-pull-request) requires a `commitId` which belonged to the user outside the org.

It would be a bummer to not be able to have any CI review comments for any community generated PRs. Wondering if there might be a simple workaround?

**Comment by Naimulnobel** [comment]
The issue you're experiencing is a common one when dealing with GitHub Actions and pull requests from forked repositories. By default, GitHub Actions runs with read-only permissions on pull requests from forks for security reasons.

However, there is a workaround. You can use a Personal Access Token (PAT) instead of the default `GITHUB_TOKEN` to give your action the necessary permissions. Here's how you can do it:

1. Generate a new Personal Access Token in your account settings with the necessary scopes. Be careful with this token as it provides access to your account.

2. Add this token as a secret in your repository settings.

3. In your GitHub Actions workflow file, use this secret instead of `GITHUB_TOKEN`.

Here's an example of how to use the secret in your workflow file:

```yaml
name: Review Comments
on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run review comments action
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
        script: |
          // Your script

 here


```

Replace `YOUR_PERSONAL_ACCESS_TOKEN` with the name of the secret you added.

Please note that this approach has security implications. The token has the same permissions as the user who created it, so it can push to your repository, access secrets, etc. Be sure to understand these implications before using this approach.
