### DISCUSSION TITLE
Give the option to make check pass when only files matching paths-ignore have changed

### DISCUSSION THREAD

**Discussion by Anton-4** [community/community#8832] [Actions] [answered]
Say I want to ignore changes to markdown files for a workflow:
```
on:
  pull_request:
    paths-ignore:
          - '**.md'
...
```
When using branch protection and when only markdown files have changed, this workflow will not run and not be marked as passed.
This makes us unable to follow the normal merging procedure.

It would be lovely if a workflow can either pass for ignored files or allow a special flag/setting to be set to achieve this behavior.
