### DISCUSSION TITLE
How to put an OR Operator in to a Workflow Correctly

### DISCUSSION THREAD

**Discussion by JayMax23** [community/community#88402] [Actions]
### Select Topic Area

Question

### Body

Hi,

I have a workflow that can be run against multiple envs:

`
name: Automation Tests
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      choice:
        description: 'The environment to test: something-devdev or something-qa'
        required: true
        type: choice
        options:
          - something-dev
          - something-qa
`
          
          
 This then loads the correct Environment set in GitHub
 
 After Run i then write out to Slack
 
 `      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: channel-name
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/80687865?s=48&v=4
          SLACK_MESSAGE: 'E2E Results: ${{ job.status }}'
          SLACK_MSG_AUTHOR: ${{ github.actor }}
          SLACK_TITLE: 'Automation Tests - (ENV: ${{ github.event.inputs.choice }})'
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}`
 
 
`           SLACK_TITLE: 'Automation Tests - (ENV: ${{ github.event.inputs.choice }})'
`

Will return the selected input on select. However, when it runs on CRON it is Blank.

How can i get it to show a selected Env Choice OR hard text e.g.

          SLACK_TITLE: 'Automation Tests - (ENV: ${{ github.event.inputs.choice }} | 'My ENV)'

**Comment by faridnec** [comment]
It might be something like this? 
```yaml
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          # ... (other environment variables)

          SLACK_TITLE: 'Automation Tests - (ENV: ${{ github.event.inputs.choice || "My ENV" }})'
```
In the `SLACK_TITLE` field, `${{ github.event.inputs.choice || " | My ENV" }}` uses the OR operator (||) to check if github.event.inputs.choice is truthy. If it is, it will use the selected environment choice; otherwise, it will use the default text "My ENV". This way, when running on CRON, it will display the default text.
