### DISCUSSION TITLE
Is it possible to run a job on different runners based on the triggering branch?

### DISCUSSION THREAD

**Discussion by sr-murthy** [community/community#88552] [Actions] [answered]
### Select Topic Area

Question

### Body

I have a CI YML defining a number of jobs. I'd like the main job, which runs on both `master` and non-`master` feature/fix branch pipelines, to use different runners depending on whether the triggering branch is either `master` or non-`master`. Is this possible?

**Comment by KK-Repos** [comment, marked as answer]
yes its possible you can achieve this Using Labels and Self-Hosted Runners:

- Create two self-hosted runners, one for master and one for non-master branches.
- Assign different labels to these runners (e.g., master-runner and non-master-runner).

```

jobs:
  main:
    runs-on: ${{ github.ref_name == 'master' && 'master-runner' || fromJSON('["non-master-runner"]') }}
    steps:
      # ... your job steps
```
