### DISCUSSION TITLE
Environment's required reviewers at workflow level (instead of job)

### DISCUSSION THREAD

**Discussion by mikocot** [community/community#88692] [Actions]
### Select Topic Area

Question

### Body

Some of our environments require manual approvals for releases.
This can be easily done with environment protection rules, by turning on the required reviewers.

However, it seems to be applied at job level and not at the workflow level, ending up with 3-4 approvals for each workflow in our case.
I can barely think of any scenario where such approval would need to be re-done for every job, especially since the same rules are applied to all of them (you can't specify different reviewers for different jobs), so what's the point?

Is that by design? Is there any plan to add workflow level approvals at one point?

![image](https://github.com/community/community/assets/9884950/fc96fb9a-e2cd-4f50-81c4-546666bf05f6)

![image](https://github.com/community/community/assets/9884950/f0a08ff8-2930-44ce-ab6c-43fd67c2b91b)

The same applies to delays mechanism - each job/stage gets a delay. Also those approvals apply to every workflow running against the environment, including e.g. those thast do not modify the environment, but e.g. only run periodic tests. Ideally there would be a way to exlude those.

NOTE: What's interesting is thast we're only asked to approve the first 3 stages, not the last 2 jobs, at 4th stage. And all those 3 actually we need to approve belong to the sub-workflow referenced by the first job, which makes me think it might be a bug.

```
deploy:
    if: github.event.deployment.environment == 'production' && github.event.deployment.payload.version
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: production
```
