### DISCUSSION TITLE
Access the job.<job_id>.environment variable

### DISCUSSION THREAD

**Discussion by nilsguillermin** [community/community#88760] [Actions]
### Select Topic Area

Question

### Body

Notice I am looking for the `environment` input to the job, not environment variables.
If my job looks like this
```
jobs:
  job_name:
    runs-on: ubuntu-latest
    environment: production
        
    steps:
       - name: Print inputs
         run: echo "Environment to be updated: ${{ <what is this variable> }}"
```

Is it possible to access the string "production" inside the job? This is a very difficult thing to search up.
