### DISCUSSION TITLE
Concurrency and Reusable Workflows with multi-repositories

### DISCUSSION THREAD

**Discussion by servandorodrigues** [community/community#88761] [Actions]
### Select Topic Area

Question

### Body

I have two repos, one for UI and other for Tests,  I can't have two tests running at the same time so I added concurrency to the Tests repo, if that workflow is triggered twice it guarantees that it will not run at the same time. It worked.

Now I need to make the UI repo call the Tests workflow so I used the `workflow_call` trigger to accomplish this, but it seems that the concurrency is not working across repos. 

I mean, if I trigger the Tests workflow on UI repo and Test repo at the same time, both will run together. 
Is there a way that I can force concurrency between the repos?  
Like if the UI repo is currently running the Test workflow,  if I trigger the Test workflow on the Test repo it will keep pending and run only after the UI repo finishes the job.

Thank you for the help.

UI workflow:
```
name: Deploy Test Env
on:
  push:
    branches: ['develop']

jobs:
  deploy_develop: ...

  run_test:
    needs: [deploy_develop]
    uses: organization/test-repo/.github/workflows/test-run.yml@main
    with:
      environment: development
      repository: organization/test-repo
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

``` 
Tests workflow:
```
name: Tests
on:
    push:
    workflow_call: 
        inputs:
           environment:
           type: string
           default: development
        secrets:
            PAT_TOKEN:
              required: true

concurrency:
  group: testworkflow
  cancel-in-progress: false

jobs:
    test_run: ...
```
