### DISCUSSION TITLE
How to add timestamp in GitHub action as a global variable for use by all jobs?

### DISCUSSION THREAD

**Discussion by kjxbyz** [community/community#88772] [Actions] [answered]
### Select Topic Area

Question

### Body

How to add timestamp in GitHub action as a global variable for use by all jobs?

**Comment by fury-05** [comment]
GitHub Actions does not directly support global variables that can be easily shared across all jobs.

You can achieve a similar result by setting an environment variable in one job and then using it in subsequent jobs.

Here is sample code to implement the timestamp, it is stored as an environment variable, and you can use it in subsequent steps or jobs within the workflow.

```yaml
name: Timestamp Example

on: [push]

jobs:
  set-timestamp:
    runs-on: ubuntu-latest
    outputs:
      steps: ${{ steps.timestamp.outputs }}
    steps:
      - name: Set Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV

  use-timestamp:
    needs: set-timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Use Timestamp
        run: echo "Timestamp is $TIMESTAMP"

```

See if this will work for you.
