### DISCUSSION TITLE
Create a copy of the repository in every commit that is made and add it in a zip file

### DISCUSSION THREAD

**Discussion by Loweredgames** [community/community#89804] [Actions]
Hi I have a problem with the code:

```
name: Skyblock Nightly Building

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest,

steps:
    uses: actions/checkout@v2
    run: |
      zip -r Skyblock_Classic_Edition_Nightly.zip .
    uses: actions/upload-artifact@v2
    with:
      name: Nightly
      path: Skyblock_Classic_Edition_Nightly.zip
```

it gives me errors. I would like to create a copy of the repository in every commit that is made and add it in a zip file, downloading it from Github Actions. _sorry but I'm not very expert_
