### DISCUSSION TITLE
Side by Side Preview in web based readme.md editor

### DISCUSSION THREAD

**Discussion by SerratedSharp** [community/community#89986] [Other Feature Feedback, Questions, & Ideas]
### Select Topic Area

Product Feedback

### Body

When using the edit "Pencil" icon from my repo's homepage to edit the readme.md, is there a way to set the editor and preview to be side-by-side?

There's a number of features that are only present in this editor as far as I know(pasting screen clipping in and getting upload+link in one step for example), and some github specific markdown syntax that only renders correctly in this editor's preview, so for those two big reasons I really prefer to do all my editing in that we based editor.  But I often switch back and forth to catch my mistakes by checking the preview, but it's a bit high friction to find my place in the document's preview and then go back and find my editing location.  Is it possible to get the preview side-by-side with the editor?

**Comment by aadltya** [comment]
Hope it helps, Mark this as answer pls!

GitHub's web-based Markdown editor doesn't have a built-in feature to display the editor and preview side-by-side directly from the repository homepage when editing the README.md file using the "Pencil" icon.

However, you can achieve a similar result by opening the README.md file in a new tab or window. This allows you to have the editor in one tab/window and the preview in another, making it easier to switch between the two.

Here's a step-by-step guide:

Click the "Pencil" icon to open the README.md file in edit mode.
Right-click on the "Preview changes" tab (or the tab where the preview is displayed) and select "Open link in new tab" or a similar option depending on your browser.
Now, you have the editor in one tab and the preview in another. You can arrange these tabs side-by-side on your screen for a more convenient editing experience.

Keep in mind that GitHub's interface and features may evolve, and new functionalities might be introduced. It's a good idea to check GitHub's official documentation or announcements for any updates related to the Markdown editor.

**Comment by KaKi87** [comment]
Hi,

I managed to make the editor and preview appear side by side on gist.github.com *(I focused on that as Gist is my only use case for editing complex markdown files in browser)* :

![](https://github.com/user-attachments/assets/1a277395-4541-4f12-a7ff-aa9f14b14e1a)

Using the following CSS & JS :

```css
blob-editor {
    display: grid !important;
    grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
}

blob-editor .file-header,
blob-editor #focus-trap-banner,
blob-editor .commit-create label {
    grid-column: 1 / 3;
}

blob-editor .commit-create,
.container-preview:not(.show-code) .commit-create {
    display: contents !important;
}

blob-editor .js-commit-preview,
blob-editor.container-preview.show-code .js-commit-preview {
    display: block !important;
    grid-column: 2 / 3;
    grid-row: 2 / 3;
}
```

```js
setInterval(() => {
    document.querySelector('blob-editor [data-tab="show-code"]').click();
    document.querySelector('blob-editor [data-tab="preview"]').click()
}, 3000);
```
