### DISCUSSION TITLE
[Feature Request] Add support for env vars and secrets in a Github actions matrix

### DISCUSSION THREAD

**Discussion by hyperfocus1337** [community/community#9003] [Actions]
The Github Actions matrix currently does not support the ability to add dynamic `${{ env.VAR }}` or `${{ secret.SECRET }}`, which is a shame, because we need this functionality to add dynamic subscription ids per environment. Minimal example included below.

```
name: Azure landingzones

env:
  TEST_SUBSCRIPTION: "subscription-id"

on:
  pull_request:
    branches:
      - main

jobs:
  landingzones:
    name: ${{ matrix.action }} on ${{ matrix.landingzones.landingzone }} ( level${{ matrix.landingzones.level }} )
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prd' || 'tst' }}

    container:
      image: aztfmod/rover:1.0.9-2111.0103
      options: --user 0

    strategy:
      matrix:
        landingzones:
            - { level: "0", landingzone: "launchpad", subscription: "${{ env.TEST_SUBSCRIPTION_DOES_NOT_WORK }}" }
            - { level: "1", landingzone: "shared_services", subscription: "this-works-without-env-var-or-secret"}
         action: ["plan"]
```

Facing this issue.
![image](https://user-images.githubusercontent.com/24568457/146551077-18d1fb4c-b198-41bd-bc31-0eee29e473be.png)

Please make this possible, so my team can achieve this use case without needing any complicated workarounds.
