### DISCUSSION TITLE
Run a matrix element only if a condition is true

### DISCUSSION THREAD

**Discussion by maximousblk** [community/community#9044] [Actions]
**Describe the enhancement**
A way to define when to run a matrix. Similar to a jobs and steps, matrices would have and `if: ...` rule

**Code Snippet**
to fit the current syntax:

```yml
runs-on: ${{ matrix.os }}
strategy:
  matrix:
    node: [12, 14, 15]
    os: [macos-latest, windows-latest, ubuntu-latest]
    include:
      - if: contains("[lts]", github.event.head_commit.message) # special value
        node: 8                                                 # regular value
        os: ubuntu-latest

      - if: contains("[lts]", github.event.head_commit.message)
        node: 10
        os: ubuntu-latest
```

if a new syntax is acceptable, I'd like to propose Matrix Groups:

```yml
runs-on: ${{ matrix.os }}
strategy:
  matrix:
    groups:
      - name: test
        with:
          os: [macos-latest, windows-latest, ubuntu-latest]
          node: [12, 14, 15]

      - name: test:lts
        if: contains("[lts]", github.event.head_commit.message)
        with:
          os: ubuntu-latest
          node: [8, 10]
```

**Additional information**

I believe this is better than having two identical jobs just with a different matrix. If there is already a good way to do this, I would really like to know.

For the second syntax, I cannot think of a way to expose the group name under the `matrix` context. For me it's fine even if it's not. And if someone really wants the name, they could always do:

```yml
matrix:
  groups:
    - name: test
      with:
        name: test
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [12, 14, 15]
```

<sub>

---
This discussion was moved here from [actions/runner#897](https://github.com/actions/runner/issues/897)

</sub>
