### DISCUSSION TITLE
Configuring the security policy option

### DISCUSSION THREAD

**Discussion by ObserverOfTime** [community/community#9089] [Projects and Issues]
Now that we can configure the template chooser through `config.yml`,
it'd be nice if we could change how the security policy option is rendered.

```yaml
# example
security_policy:
    name: 🔒️ Security Vulnerability
    about:  Please review our security policy for more details
```
