### DISCUSSION TITLE
Issue form subsections

### DISCUSSION THREAD

**Discussion by ObserverOfTime** [community/community#9090] [Projects and Issues]
The new issue forms are great, but they're missing subsections.

So the example from the docs:

```yaml
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
```

could become something like this instead:

```yaml
- type: section
  attributes:
    label: Environment
    children:
      - type: input
        attributes:
          label: OS
          placeholder: Ubuntu 20.04
        validations:
          required: false
      ...
  validations:
    required: false
```
