### DISCUSSION TITLE
Extend "on" with possibility to ignore forks (run only for the original repo) and vice versa

### DISCUSSION THREAD

**Discussion by famod** [community/community#9098] [Actions]
Hi, I was [redirected here](https://github.com/actions/runner/issues/859#issuecomment-997041952) from https://github.com/actions/runner/issues/859:

The linked issues pretty much says it all but to summarize, it would come in very handy, if you could control for which repositories an event (e.g. `push`) should trigger.
E.g. to have a workflow only executed in the main repo:
```
on:
  push:
    repositories:
      - 'quarkusio/quarkus'
```
E.g. to have a workflow only executed in forks (not the main repo):
```
on:
  push:
    ignore-repositories:
      - 'quarkusio/quarkus'
```

And to answer [this](https://github.com/actions/runner/issues/859#issuecomment-997041952) question from @ethomson:
> My understanding here is that you have some jobs that you want to run in forks and some jobs that you want to run in the main CI?

Exactly!

Cheers,
Falko

**Comment by ethomson** [comment]
Thanks for opening this here @famod - I've put this on our backlog.

**Reply by monim67** [reply]
Is there any progress on this issue?

**Reply by justinmayer** [reply]
@ethomson: Two suggestions to include in the backlog item for excluding forks from GitHub Actions:

1. Allow this configuration at the _individual job level_ as well as for the entire workflow.
2. Support global exclusion of all forks _without_ having to [explicitly specify org+repository names](https://github.com/getpelican/pelican/pull/3200/files). Following is an example individual job that would benefit from the previously-proposed `ignore-forks: true
` syntax. This job is designed to publish new package releases (and thus should _never_ run on any fork):

```yaml
  deploy:
    ignore-forks: true
    name: Deploy
    environment: Deployment
    needs: [test, lint, docs]
    runs-on: ubuntu-latest
    if: github.ref=='refs/heads/main' && github.event_name!='pull_request'
    […]
```
