### DISCUSSION TITLE
Support using a Container Action input in field `runs: { image: ... }`

### DISCUSSION THREAD

**Discussion by umarcor** [community/community#9153] [Actions]
*Container Action*s are defined by an `action.yml` configuration file with fields `runs: { using: 'docker', image: ... }`: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action. Unfortunately, inputs cannot be used in field `image`, which prevents users from passing the image to be used as an argument.

```yml
# action.yml
inputs:
  image:
    description: 'Which container image to use'
    required: true
    default: 'debian:bullseye-slim'
runs:
  using: 'docker'
  image: '${{ inputs.image }}'
```

In order to provide such functionality, a *Composite Action* can be used as a workaround (see, for instance, https://github.com/VUnit/vunit_action/blob/master/action.yml). However, that requires Action developers to duplicate the built-in functionality with regard to settings envvars, bindings, workdir, etc. inside the container.

This is partially related to #9049, because supporting inputs in the `uses` fields of *Composite Action*s would allow to use *Container Step*s.
