### DISCUSSION TITLE
Starting multiple terminals on start up of dev containers

### DISCUSSION THREAD

**Discussion by MikeyBower93** [community/community#9180] [Codespaces]
Hello, I'm looking at creating a `devcontainer.json` definition for a mono repo, where there will be a couple of backend projects and a frontend project. One thing I would like to do is when the dev container starts it opens up a terminal for each of the projects (perhaps with a name for each terminal) and physically starts the codebase for each of the projects in the mono repo. This will mean as soon as somebody opens up the mono repo in a dev container they will have the entire codebase running.

Lets take an example just to illustrate this further. Imagine we have a mono repo called `test` in git, which had the following sub folders

- `serviceA` - (a nodeJS express application)
- `serviceB` - (a nodeJS express application)
- `frontend` - (a react application)

I would like it that when the dev container starts up it would start 3 terminals
- A terminal called `serviceA` which is running `serviceA` perhaps with something like `npm start`
- exactly the same as above but for `serviceB`
- A terminal called `frontend` which is running `frontend` perhaps with something like `npm start`

I couldn't quite find a way to do this in the reference (https://code.visualstudio.com/docs/remote/devcontainerjson-reference), however it does seem like something that can be done in Gitpod with "tasks". 

Thank you for any feedback/information.

**Comment by skaramicke** [comment]
I want the same thing.

I have a Wordpress plugin with a docker-compose that spins up a DB and Wordpress. The plugin has a public JS part and an admin JS part in two separate folders with a package.json, webpack.conf.js files and such each.
I want to automatically start three terminals;

1. `docker-compose up`
2. `cd public && npm i && npm run dev`
3. `cd admin && npm i && npm run dev`

This was easy to do in gitpod;
```yaml
tasks:
  - name: Docker Compose
    init: docker-compose pull
    command: docker-compose up

  - name: Public JS
    before: cd public
    command: |
      npm i
      npm run dev
  - name: Admin JS
    before: cd admin
    command: |
      npm i
      npm run dev
 ```
