### DISCUSSION TITLE
Concurrency group appears to have race condition and allow same workflow to run twice.

### DISCUSSION THREAD

**Discussion by josmartin** [community/community#9252] [Actions]
Reproduction of this can be seen in [this repository](https://github.com/josmartin/demo-release-action) by running the specific workflow  `gh workflow run concurrency-issue-trigger` with the github CLI.

Specifically - I have set up a single re-usable workflow `concurrency-issue-workflow-call` that enables a re-usable build for different input arguments. It has the basic form

``` yaml
on:
  workflow_call:
    inputs: ...

concurrency:
  group: concurrency-issue-workflow-call
  cancel-in-progress: false
```

This workflow is meant to run in a concurrency group `concurrency-issue-workflow-call` that should ensure that only one copy of this workflow runs at any one time.

This workflow is triggered using the `concurrency-issue-trigger` workflow which has the basic form

``` yaml
on:
  workflow_dispatch:

jobs:
  build-debian-stretch:
    uses: josmartin/demo-release-action/.github/workflows/concurrency-issue-workflow-call.yaml@main
    with: 
      dist-base: debian
      dist-tag: stretch

  build-debian-buster:
    uses: josmartin/demo-release-action/.github/workflows/concurrency-issue-workflow-call.yaml@main
    with: 
      dist-base: debian
      dist-tag: buster

...
```
In the linked repo there are 6 jobs each of which uses the `concurrency-issue-workflow-call` workflow. Reading the documentation on concurrency I expected only one of the 6 to run at anytime. However after I manually trigger the `concurrency-issue-trigger` workflow using `gh workflow run concurrency-issue-trigger` from a clone of the repo I frequently see 2 of the jobs running at the same time. A picture of this is given below - notice the icon on `debian-buster` and `debian-bullseye` both of which are running at the same time.
![Screenshot 2021-12-23 155843](https://user-images.githubusercontent.com/6057856/147266912-16233311-ec84-4a39-bdb8-64c620f5c734.png)

Once these 2 jobs had completed you can then see that `ubuntu-focal` and `ubuntu-hirsute` run together.
![Screenshot 2021-12-23 155930](https://user-images.githubusercontent.com/6057856/147267055-0151f75a-358d-4d23-98ce-efaeb73362b0.png)

In addition, for some reason, other jobs simply decide never to even run with no indication as to why - in this case the `debian-stretch` and `ubuntu-bionic` jobs. When you click on the them in the actions area they simply say "This check was skipped"

![Screenshot 2021-12-23 162521](https://user-images.githubusercontent.com/6057856/147267460-acb0832a-8b1c-4dc1-b5f1-98d32a3fed41.png)

So - 2 questions / potential bugs

1. Why sometimes do multiple copies of a single workflow that is set to have a specific `concurrency` group run at the same time?
2. Why do some jobs in a `concurrency` group never run?
