### DISCUSSION TITLE
[Feature request] Allow markdown in placeholder of Textarea

### DISCUSSION THREAD

**Discussion by BastianZim** [community/community#9341] [Projects and Issues]
My file currently looks like this (Excerpt):

```yaml
  - type: textarea
    attributes:
      label: Sample label
      description: Sample text
      placeholder: 1. PyPI 2. GitHub releases
    validations:
      required: true
```

and it would be great if I could format the placeholder like this:

```yaml
  - type: textarea
    attributes:
      label: Sample label
      description: Sample text
      placeholder: |
        1. PyPI
        2. GitHub releases
    validations:
      required: true
```

Currently, the output of this looks like 
```shell
1. PyPI2. GitHub releases
```
but
```
1. PyPI
2. GitHub releases
```
would be nice.
