### DISCUSSION TITLE
[Feature request] Render markdown in `label` of `input`s

### DISCUSSION THREAD

**Discussion by KotlinIsland** [community/community#9415] [Projects and Issues]
```yaml
  - type: input
    attributes:
      label: Configuration options from `pyptoject.toml` (and other config files)
```
![image](https://user-images.githubusercontent.com/65446343/147729846-cd1f1f72-4bfb-4eb5-9092-81b6e08f954e.png)
