### DISCUSSION TITLE
Accessing Step Context in a Composite Action

### DISCUSSION THREAD

**Discussion by aleto-ms** [community/community#9599] [Actions] [answered]
*Composite Actions* seems a great way to split workflows into reusable pieces. 
But cannot find a way to access a step context.
For example - One step is running some unit tests. And I want to create a Check in the next step denoting the status of unit tests.

```yaml
    - name: Run Benchmarks 
      uses: Happypig375/github-action-benchmark@v1
      id: benchmark-reporter

    - name: Checkrun for benchmark
      uses: LouisBrunner/checks-action@v1.2.0
      with:
        conclusion: ${{ steps.benchmark-reporter.outcome }}
        output_text_description_file: ./BenchmarkDotNet.Artifacts/results/joined-report-github.md
```

The above works when in a workflow directly, but in a Composite Action I get nothing from `steps`. Tried other properties as described in [Steps Context](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context), still nothing.

```
    - shell: bash
      run: echo ${{ toJson(steps) }}
```
I get just an empty `{ }` object. 

Any ideas? I couldn't find any mentioning of this behavior in documentation is that a bug?

Update: looks like overlaps with this issue: https://github.com/actions/runner/issues/1578

**Comment by chrispat** [comment, marked as answer]
Thank you for your feedback.

I agree this should work and seems like an oversight in implementation rather than a specific design decision.  I have passed it along to the team for prioritization.

**Reply by chrispat** [reply]
This has shipped https://github.com/actions/runner/pull/1600

**Comment by jenschelkopf** [comment]
Hi @aleto-ms, as @chrispat mentioned this is a bug in the implementation. We've merged a fix for it, and should be released soon. Thanks for bringing this to our attention!

**Reply by kkhosravitl** [reply]
Great to hear there is a bug fix for this, as we are also running into this issue. Is there any ETA for the release? Thanks!

**Comment by riosje** [comment]
Hi guys, same issue with the javascript actions, there is no way to access the steps context.
there is not implementation in the toolkit, also when I try to send the context through the Input it brings an empty object.

**Reply by riosje** [reply]
@kkhosravitl @aleto-ms just if still need some solution, my current workaround is use an "inline" github script action https://github.com/actions/github-script

by this way is possible to pass all the [contexts](https://docs.github.com/en/actions/learn-github-actions/contexts).

**Comment by alambike** [comment]
Hi @chrispat , @jenschelkopf ,

I am encountering a similar problem, in a composite action. Now we have access to the `steps` context, but we can only see in it the steps previously executed in the action itself, not all the steps executed in the job, where the action is used. 

Is there any way to reach them from a composite action? Or the only option is the one that @riosje [comments](https://github.com/orgs/community/discussions/9599#discussioncomment-4338573), with a `github-script` step inside the workflow itself?

**Comment by riosje** [comment]
As of today this works with Javascript Actions by this way, not sure if is still an issue with composite actions.

```YAML
      - name: My Action
        id: slack
        uses: myaction@main
        with:
          steps_context: '${{ toJson(steps) }}'
```
