### DISCUSSION TITLE
The `dispatches` API should return the run ID

### DISCUSSION THREAD

**Discussion by neilmayhew** [community/community#9752] [Actions] [answered]
The [Create a workflow dispatch event ](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event) returns empty content. However, this makes it very difficult to track the workflow that was triggered because getting its ID is inherently 'racy'. The triggered workflow may have finished before you can check for it, or another job may already be running. It would be much better if the API returned the ID of the workflow that was dispatched.

This is an ongoing problem in the [convictional/trigger-workflow-and-wait](https://github.com/convictional/trigger-workflow-and-wait) action that's available in the Marketplace, and there's currently a [PR](https://github.com/convictional/trigger-workflow-and-wait/pull/34) open that's trying to fix this, but it's going to be very difficult to make it robust.

**Update:** I wrote a better [PR](https://github.com/convictional/trigger-workflow-and-wait/pull/37) and it was merged. The [finished code](https://github.com/convictional/trigger-workflow-and-wait/blob/master/entrypoint.sh#L131) now has a robust mechanism for getting the run ID.

**Comment by chrispat** [comment]
Thank you for your feedback.

We are aware of this issue, however, at the moment there are some technical challenges with providing this information.  Under the covers the `workflow_dispatch` is a webhook just like all of the other events that trigger Actions workflows.  This means it is processed asynchronously and at the time of API call we simply don't know the run id so we can't return it.

It is something the team is aware of and hope to address in the future.

**Reply by neilmayhew** [reply]
Thank you, Chris. I'll mark this as answered, but please update the discussion if this ever gets implemented.

**Reply by nieuwsma** [reply]
Alternatively, It would be great if we could provide some sort of lookup ID.  I don't care if its not the primary lookup ID, but lacking some sort of queryable ID is a real pain to compensate for.

**Reply by atemate** [reply]
Thank you @chrispat! I join the request to have any sort of lookup of the ID, something less hacky than described in [this answer](https://stackoverflow.com/a/69500478)

**Reply by atemate** [reply]
I think, ideally it would have been great to have some sort of `--sync` option so that the server waits until the web hook gets scheduled and returns its ID.

**Reply by sandokandias** [reply]
Hi @chrispat, do you have some news about it?

We did a workaround by sending a `correlation_id` as a field of the inputs, and then we set the workflow attribute `run-name` to `run-name: ${{ inputs.correlation_id }}`. Marking event `workflow_run` on `Webhooks settings` we can receive the events `requested`, `in_progress`, `completed`. From `in_progress` event we get the information and store it on our side and make the correlation work. 

But guess what? - From 2023-04-20 the event in_progress is not being delivered _(by webhooks)_ for any workflow run, and this unexpected behaviour brokes our integration for monitoring workflow runs.

**Reply by BrianOpteran** [reply]
This is madness. It's basic API design. You can still be asynchronous with the webhook - return a UUID for this request and call that the `dispatch_uuid`. The UUID is attached to the payload that is part of the slower tasks. This UUID is attached to the workflow run information as `dispatch_uuid`...

**Reply by jebeaudet** [reply]
2+ years since this has been reported and no progress, this is really necessary for any kind of 3rd party integration launching and monitoring workflow in Github. Is there any news on this?

**Reply by keplerk** [reply]
Or at least if there was a way to send an identifier as part of the payload and have the way to search by that identifier would help as well, in that way it won't matter if it's async or not because the info will be part of the inputs.

**Reply by neilmayhew** [reply]
I unmarked this as "answered" because it's been 2y and there still isn't a real solution, only clunky workarounds.

**Reply by benc-uk** [reply]
This is API design 101 for any asynchronous task or API, amazing this made it to production in this state

**Comment by neilmayhew** [comment]
In case anyone finds this discussion and is looking for a workaround, I've implemented one in a new [PR](https://github.com/convictional/trigger-workflow-and-wait/pull/37). The idea is to compare the lists of run IDs before and after the trigger API is called. However, we don't need to fetch the full history of run IDs, only those since a couple of minutes before the trigger, and thankfully the `runs` API allows you to filter by time.

**Comment by aranair** [comment]
Is there a way to maybe expose a specific input from dispatched workflows (e.g. some id generated client-side and passed in when triggering)? We can then query using that, for the exact run-id via the api at a later time, when it is available? (or at the very least be able to "de-race" by inspecting that field for runs that happen at the same time)

All that's needed would be to add some whitelisted fields for this in the API?

**Comment by jdbodyfelt** [comment]
Can we please get a return run_ID or job_ID array for the dispatch? It's lack is making completion polling and logging a real PitA.

**Reply by neilmayhew** [reply]
I recommend you use the [convictional/trigger-workflow-and-wait](https://github.com/convictional/trigger-workflow-and-wait) action:

```yaml
- name: Example
  uses: convictional/trigger-workflow-and-wait@v1.6.5
  with:
    owner: my-org
    repo: other-repo
    workflow_file_name: other-workflow.yaml
    github_token: ${{ secrets.GH_TOKEN }}
    client_payload: '{"key1": "value1", "key2": "value2"}'
```

This takes care of waiting for the other job and returning a success or failure according to whether the other workflow succeeded or failed.

**Comment by xvzf** [comment]
So I solved this by injecting a non-used input field and search for it again when retrieving the workflows. This is a very much needed feature imho

**Reply by skuriyadi** [reply]
Please provide an example.
Thank you

**Reply by gusostow** [reply]
Does the workflow runs API return the input values?

**Reply by benbuckman** [reply]
I happen to be encountering the same issue now, and I'm not seeing where the raw inputs are returned in the workflow runs API. ☝️ 
Thanks

**Comment by ebracho** [comment]
Alternative approach:
1. Create a temporary branch ref for the commit sha (e.g. `tmp-${UUID}`) and trigger the workflow on it
2. Poll for workflow runs with `branch=tmp-${UUID}`
3. Delete the branch once you retrieve the workflow run 

This way you don't have to worry about other workflow runs triggering on the same ref.

**Comment by lasith-kg** [comment]
**Affilitiation:** I acknowledge that I am a major contributor to this GitHub Action.

[`lasith-kg/dispatch-workflow@v1`](https://github.com/lasith-kg/dispatch-workflow) is a GitHub Action that dispatches workflows either using `repository_dispatch` or `workflow_dispatch` event and has an optional flag `discover: true`. When this flag is enabled, it injects a **unique UUID** into the Workflow Run Name so that it can be correlated to the initial dispatch event. Once the workflow is discovered, the **Run ID** and **Run URL** is available from the step outputs.

```yaml
steps:
  - uses: lasith-kg/dispatch-workflow@v1
    id: dispatch-with-discovery
    name: "Dispatch Workflow With Discovery"
    with:
      dispacth-method: workflow_dispatch | repository_dispatch
      ...
      discover: true
  - id: echo-run-id-url
    name: "Echo Run ID and Run URL"
    run: |
      echo "${{ steps.dispatch-with-discovery.outputs.run-id }}"
      echo "${{ steps.dispatch-with-discovery.outputs.run-url }}"
```

Naturally, the receiving workflow needs to be modified to intercept this UUID in the `run-name`

#### `workflow_dispatch`

```yaml
name: Receiving Workflow
run-name: Receiving Workflow [${{ inputs.distinct_id && inputs.distinct_id || 'N/A' }}]

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: 'Distinct ID'
        required: false
```

#### `repository_dispatch`

```yaml
name: Receiving Workflow
run-name: >
  Receiving Workflow [${{
    github.event.client_payload.distinct_id &&
    github.event.client_payload.distinct_id || 'N/A' }}]

on:
  repository_dispatch:
    types:
      - deploy
```

**Reply by jdbodyfelt** [reply]
Perfect! Thank you!

**Comment by haolingdong-msft** [comment]
**Provide an alternative solution I use：**
Add an input parameter we call `UUID` to your workflow configuration yaml file, then set `run-name` to include `UUID`.
```
run-name: Receiving Workflow [${{ inputs.UUID }}]
```

Then you can filter using run-name by the UUID when [List workflow runs for a workflow](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-workflow). This call will return run name, then you just filter the matched run instance by the `run-name`. 
Note: list-workflow-runs-for-a-workflow supports pass in `create` as query parameter to filter requests, if you found get all runs is too time-costing, you can add the filter to only inlucde a time period run instances.
![image](https://github.com/community/community/assets/87355844/9fa6c667-0b8e-4508-aa4c-261e72274fb8)

**Comment by jstafford5380** [comment]
For what it’s worth, Jenkins addresses this by issuing a “queue id” at the time of the dispatch request. I imagine they simply generate and id and queue the dispatch. The id is passed back to the caller and then when the job starts, the build record (or workflow in the this case) will now have that id it as a property. Then the developer can query for recent build history for the particular job by name and then client side filter for the one with the id they were given and keep polling until the status comes back indicating the run is complete. Architecturally, it’s pretty straight forward, but I don’t know what the scheduling infra looks like on the GHA side

**Comment by lkfortuna** [comment]
Hey there 👋  ~~To provide an update here, we do not have this on our prioritized list for this year but have it on the list for next year. We do not have the funding to go after everything we want to fix, and we appreciate your patience on the delay.~~

I apologize I was wrong, we are work on fixing this this quarter, standby for more news on this!

**Reply by austinpray-mixpanel** [reply]
This is amazing news!! I can't wait to get my hands on this. We have sooo many workarounds for the lack of a dispatch ID littered around our codebase at this point.

**Reply by keplerk** [reply]
> This is amazing news!! I can't wait to get my hands on this. We have sooo many workarounds for the lack of a dispatch ID littered around our codebase at this point.

I'm eager as well, but still kinda skeptical at the moment.

**Reply by neilmayhew** [reply]
This is great news!

Regarding the funding, whenever I respond to one of the periodic surveys asking for our opinion of GitHub Actions, I always mention that I think it's underfunded for something so widely used and relied upon. My voice alone isn't going to make much difference, but if a lot of us say the same thing perhaps somebody will take notice and ultimately we can help to get more funding for your team. If there are other avenues where our voices would also make a difference, please let us know.

**Reply by robodenitro** [reply]
@lkfortuna are there any updates regarding this fix/feature? Thanks!

**Reply by nebuk89** [reply]
This slipped out slightly, we still aim to ship this by the end of the calendar year :) thank you for your patience and we are working on it currently ❤️

**Reply by tonit** [reply]
Eagerly awaiting an update @lkfortuna ! Any..news on this?

**Reply by lkfortuna** [reply]
hi - we are stil planning on shipping this like Ben said by end of CY, it got pushed out a bit, stay tuned!

**Reply by ethanr-bjss** [reply]
Eagerly awaiting this. This makes a massive difference to a project I'm working on, which relies heavily on cross-repo workflows. Tracing which workflow triggered what, and what triggered it, is really important.

Please do update when it is available! 🚀

**Reply by jstafford5380** [reply]
Just checking in @lkfortuna , we're at the end of the CY. How are we looking?

**Reply by lkfortuna** [reply]
hey there- unfortunately this work got delayed, we are still planning on doing this work, but it is now scheduled for this quarter.

**Reply by talcoh2x** [reply]
+1

**Reply by drodil** [reply]
So Q1/2025? :)

**Reply by franzwarning** [reply]
"we don't have the funding" lololol https://news.microsoft.com/announcement/microsoft-acquires-github/

**Reply by Suhas1104** [reply]
Hey @lkfortuna, are there any updates on this?

**Reply by claymccoy** [reply]
Hi @lkfortuna, updates? GitHub Enterprise user here that could really use this necessary feature.

**Reply by rcontreras-te** [reply]
Agreed, we'd love to see a fix for this to avoid having to implement a hacky workaround.

**Reply by claymccoy** [reply]
Q1/2025 is over. Was this an elaborate April Fools' joke?

**Reply by feedmypixel** [reply]
Came across this today. @lkfortuna any updates on the fix for this? Heres some free 🍰 to help you with prioritisation 😄

**Reply by ethanr-bjss** [reply]
<img width="288" alt="image" src="https://github.com/user-attachments/assets/cd8ec942-b01c-4d5a-a2ef-f5f42190f17b" />

**Reply by keplerk** [reply]
Honestly, I highly doubt this will be implemented in the short/medium future.

**Reply by Brend-Smits** [reply]
Hi @lkfortuna, 

Would you be able to provide an update on this please? No update is also an update! 
Thank you 👍🏼

**Reply by owattley-rotageek** [reply]
I know this is not any individual engineers fault and I do not wish to admonish people who are just doing their job, so I guess my ire is directed broadly at Microsoft/Github as a whole here...

I cannot believe what I am reading in this thread after facing this issue for the first time today. It must surely be a joke that a multi-billion dollar company can't even output the most fundamental piece of information an API consumer would require to warrant using the API in the first place.

Why build the API if it cannot be reliably used? It's like building a car but you forgot the brakes and steering wheel. Guess we'll have to rely on the public to stop and steer that car.

I am trying to run and monitor a workflow from outside Github, so using an existing GH Action workaround is not viable for my use case - but thanks to the community for building these.

It looks like the only truly reliable way of doing it without any changes to your workflow (e.g. adding inputs) is to create a temporary unique ref branched off your `main` branch as per [this comment](https://github.com/orgs/community/discussions/9752#discussioncomment-5247573). But this is so horrible. Nobody should need to be using this or any other workaround for what is essentially very basic data being returned in an API call.

Github, this issue was raised in 2022 and here we are in 2025. This is shamefully bad, please fix it.

**Reply by gm-k2v** [reply]
A year later and nothing still!?

**Reply by benc-uk** [reply]
Over three years and counting

**Reply by neilmayhew** [reply]
> I am trying to run and monitor a workflow from outside Github, so using an existing GH Action workaround is not viable for my use case - but thanks to the community for building these.

@owattley-rotageek The "finished code" linked to in my update to the original post can be used from anywhere. It's just bash code. Although it's part of an existing action, it doesn't use any features of the actions environment. It works reliably without any ugly workarounds.

**Reply by adelinn** [reply]
@lkfortuna we really need this. Workarounds aren't fun to work with. Please prioritize this.

**Reply by mukesh-nayal** [reply]
Same here, I am in a dire need of this functionality. Thanks

**Comment by neilmayhew** [comment]
To all who are complaining about this, there's a [robust solution](https://github.com/convictional/trigger-workflow-and-wait/blob/master/entrypoint.sh#L131) that doesn't involve any intrusive workarounds. Although it's currently in an existing action, it's just bash code and can be used from anywhere. (There's a link to it in my original post.)

It works by getting the list of currently running workflows before and after triggering the workflow, and seeing which are the new ones. Although there's a potential race condition if multiple external agents trigger the same workflow at the same time, it's fail-safe because the agents will just wait for all the new workflows to finish. Even though this isn't perfect, the race is unlikely to happen in practice.

The same logic could easily be written in another language, using the existing bash code as a guide.

**Reply by KoenWillemse** [reply]
It's a workaround that probably a lot of people are now using (me too), but I would not call it a _robust_ solution.

**Reply by neilmayhew** [reply]
That's a fair comment. However, it's more robust than any of the previous non-intrusive solutions, and it seems to work well in practice. Have you experienced any problems with it?

**Comment by ataylorme** [comment]
I follow these steps:

1. Create a temporary branch with a unique ID
2. Trigger the workflow via dispatch event with the temporary branch as the source
3. Delete the temporary branch
4. Polling for the triggered workflow run using `GET /repos/{owner}/{repo}/actions/runs`, which accepts `branch` as a search parameter

Polling takes less than 30 seconds in most cases, with edge cases being a GitHub Actions incident where jobs don't start. The temporary branch is necessary to ensure you select the correct workflow run and will ever only get the single, correct result when polling.

**Reply by austinpray-mixpanel** [reply]
We have been using this approach for a couple years now https://github.com/orgs/community/discussions/9752#discussioncomment-5247573. GitHub's APIs for creating branches are somewhat flakey at scale. I wish I didn't have to do this.

**Reply by ataylorme** [reply]
I also wish we didn’t have to jump through these hoops

**Comment by OsamaSBCrea** [comment]
Coming in early 2026 based on this: https://github.blog/news-insights/product-news/lets-talk-about-github-actions/

**Reply by keplerk** [reply]
And only took almost 4 years. Better later than never, I guess 😅

**Reply by neilmayhew** [reply]
That's a great blog post, and it's very pleasing to see this issue mentioned in the list of things to be done in early 2026. I understand now why this feature hasn't had any attention recently. The backend rearchitecture must have taken a lot of work, and as a fellow-developer I fully understand the need to put features on hold and work on core tech for a while.

**However**, it's very frustrating that the development team weren't able to let us know the reason for the delay. I understand the need for secrecy around internal product development sometimes, but in this case case it's hard to see why the rearchitecture work couldn't have been made public. A little more information would have helped a lot in reducing people's frustrations, and I hope this can be communicated up the chain to management.

**Reply by ThomasMatern** [reply]
Did this go live by accident already? Currently the create-workflow-dispatch API returns a 200 (instead of 204), with this response:

<img width="819" height="87" alt="image" src="https://github.com/user-attachments/assets/a0aae90d-7b2b-4e15-9267-30bfc31a936d" />

This also breaks PyGithub - because it only accepts a 204 response.
https://github.com/PyGithub/PyGithub/blob/61dcf49d30d6854849ab745c501cab8856267bdb/github/Workflow.py#L169

**Reply by WKBae** [reply]
I was also struck by the status code change. Created a separate discussion for this issue: https://github.com/orgs/community/discussions/182272

**Reply by rchui** [reply]
I can confirm that this now works. The workflow run id is returned in the response's data:
```yaml
    steps:
      - name: 'Workflow dispatch'
        id: workflow-dispatch-e2e
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GH_ACTIONS_PAT_SCOPE_REPO }}
          result-encoding: 'string'
          script: |
            const createWorkflowResponse = await github.rest.actions.createWorkflowDispatch({
              owner: '<owner>',
              repo: '<repo>',
              workflow_id: 'e2e-test-staging.yml',
              ref: 'development',
            });
            console.log(createWorkflowResponse);
            return createWorkflowResponse.data.workflow_run_id;
      - name: 'Watch e2e tests run'
        id: watch-e2e
        run: |
          run_id="${{ steps.workflow-dispatch-e2e.outputs.result }}"
          # Watch until completion
          gh run watch -R <owner>/<repo> --interval 45 $run_id

          # Check if any steps failed in any job
          if failed_logs=$(gh run view -R <owner>/<repo> $run_id \
              --log-failed 2>/dev/null) && [ -n "$failed_logs" ]; then
            echo "❌ e2e tests failed:"
            echo "$failed_logs"
            exit 1
          fi
          echo "✅ No failures found"
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT_SCOPE_REPO }}
```
