### DISCUSSION TITLE
Custom label when using matrix in GitHub action

### DISCUSSION THREAD

**Discussion by svoop** [community/community#9918] [Actions]
Given the following quite standard workflow:

```yml
name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [3.0, 3.1]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: SPEC_SCOPE=all bundle exec rake
```

The separate runs of test according to the matrix are labelled like so:

![fMoDp](https://user-images.githubusercontent.com/7255/148753070-d78c2e28-ccbd-4325-827d-0d96480e6a25.jpg)

For the sake of better understanding, could `jobs.<job_id>.strategy.matrix` be extended in a way to feature custom labels e.g. to change from "ubuntu-latest, 3.1" to something like "ubuntu-latest, ruby-3.1"?

**Comment by dhannanjay** [comment]
@svoop https://futurestud.io/tutorials/github-actions-customize-the-job-name

**Reply by svoop** [reply]
Thanks a lot for the hint, @dhannanjay !

**Reply by marcinkubica** [reply]
@dhannanjay 
if you have
```
  build:
    name: build ${{ matrix.site }}
    strategy:
      fail-fast: true
      matrix:
        site:
          - dev:
            some_var: ${{ vars.DEV_SOME_VAR }}
          - prod:
            some_var: ${{ vars.PROD_SOME_VAR }}

```
you get `buld Object` :)

![image](https://github.com/community/community/assets/1593987/7ef3207e-ebc1-48c7-8dfe-7b23092e953a)

needs an ugly hack with
```
  build:
    name: build ${{ matrix.site.env }}
    needs: test
    strategy:
      matrix:
        site:
          - dev:
            env: dev # hack for github ui job name
            ...other stuff
          - prod:
            env: prod # hack for github ui job name
            ...other stuff
```

**Reply by SimonAlling** [reply]
> @dhannanjay if you have
> 
> ```
>   build:
>     name: build ${{ matrix.site }}
>     strategy:
>       fail-fast: true
>       matrix:
>         site:
>           - dev:
>             some_var: ${{ vars.DEV_SOME_VAR }}
>           - prod:
>             some_var: ${{ vars.PROD_SOME_VAR }}
> ```
> 
> you get `buld Object` :)

Hi @marcinkubica! :blush:

It seems contrived and brittle to me to use different field names in different objects in the `site` list. I would suggest this instead, job name issue or not:

```yaml
  build:
    name: build ${{ matrix.site.env }}
    strategy:
      fail-fast: true
      matrix:
        site:
          - env: dev
            some_var: ${{ vars.DEV_SOME_VAR }}
          - env: prod
            some_var: ${{ vars.PROD_SOME_VAR }}
```

Then you always know the type/shape of `matrix.site`, and you have straightforward access to what env it was with `matrix.site.env`. Hope you'll find it useful! :blush:
